#############################################################
#  Message File: ACBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê um brahmin doméstico domesticado.}
{101}{}{A cabeça extra do brahmin é provavelmente o resultado de um regular
 Vaca sendo exposta logo em breve à radiação.}
{102}{}{Você não percebe nada de incomum no brahmin.}
{103}{}{Brahmin não é muito para conversas.}
{104}{}{Você não tem nada melhor a fazer do que sentar ao redor
 Falando com uma vaca de duas cabeças?}
{105}{}{Brahmin é uma raça mutada de vacas.}
