#############################################################
#  Message File: ACMynoc.msg                                #
#                                                           #
#       Body Type:  NMPRIM                                  #
#       Combat AI: Berzerker                                #
#       Weapons: Sledgehammer[in hand]                      #
#       HP: 75                                              #
#       Skills to note: 80% Throwing                        #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################

{100}{}{Você vê o guarda-ponte.}
{101}{}{Você vê Mynoc, o guarda-ponte.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{Antes de você ficar um grande guerreiro de sua aldeia,
 segurando uma lança.}
{151}{}{[CONVERSA]}
{152}{}{Olá, Escolhido. Off para encontrar o GECK?}
{153}{}{Sim.}
{154}{}{Sim. But before I go, I would like to ask you some
 questions.}
{155}{}{Ainda não. Eu vou olhar em volta um pouco
 um pouco mais.}
{156}{}{Bem, que os deuses cuidem de você.}
{157}{}{Obrigado, adeus.}
{158}{}{O que você quer saber?}
{159}{}{O que você pode me falar dos homens que trocam com nossos
 aldeia?}
{160}{}{O que você pode me falar sobre esse objeto que eu tenho?
 um cofre?}
{161}{}{Nada, esquece.}
{162}{}{Muito bem, mas não perca muito tempo. Sem o GECK,
 estamos condenados.}
{163}{}{Eu sei, não se preocupe - eu tenho tudo sob controle.}
{164}{}{Por quê?}
{165}{}{Eu devo ir. Adeus.}
{166}{}{Os comerciantes? Eles vêm de Klamath aproximadamente a cada dois meses. Lá
 não será outro aqui por um mês ou mais, mas Klamath é apenas alguns dias
 a leste daqui.}
{167}{}{Obrigado. Adeus.}
{168}{}{O que você pode me falar sobre esse objeto que eu tenho?
 o cofre sagrado?}
{169}{}{Parece uma calabaza metálica de água. Talvez o
 O vault nos enviou como um presságio.}
{170}{}{Você pode me dizer quem trouxe este item para nossa aldeia?}
{171}{}{Obrigado. Eu devo ir. Adeus.}
{172}{}{Espero que você faça.}
{173}{}{Seu excesso de confiança nos faz sofrer todos nós! Adeus!}
{174}{}{Adeus.}
{175}{}{Por quê? Look around you -- our village dies. The gardens wither and
 every day children and old ones collapse. You must bring Eden to us before
 it is too late!}
{176}{}{And I will take care of it.  Adeus.}
{177}{}{I am the Escolhido -- I "must" do only as I
 please. Adeus.}
{178}{}{Não me lembro do nome dele, só que ele era velho e alto - também
 alto por maneiras adequadas - mas ele sabia muitas coisas. Ele era de Klamath, leste
 como eu disse.}
{179}{}{Obrigado, adeus.}
{180}{}{Você ainda está aqui? Você deve procurar o GECK. Ficando aqui
 não nos ajuda.}
{181}{}{Esta ponte é tudo o que você precisa se preocupar,
 amigos. Eu posso cuidar de mim mesmo.}
{182}{}{Eu estava indo sair. Adeus meu amigo.}
{183}{}{Já não falo com você, porco insubordinado!}
{184}{}{Gostaria de lhe fazer outra pergunta.}
{185}{}{Aquilo foi rápido! Você encontrou o santo Cofre 13?}
{186}{}{Sim.}
{187}{}{Não, ainda não.}
{188}{}{Você tem? Maravilhoso! Você trouxe de volta o
 GECK?}
{189}{}{Não.}
{190}{}{Não. I haven’t spoken to the people of the vault yet.}
{191}{}{Eu não acredito que seja um negócio seu, meu amigo.}
{192}{}{Não? Escolhido, três idosos morreram desde que você saiu. Você deve
 não desperdice mais tempo.}
{193}{}{Eu vou achar, não se preocupe.}
{194}{}{Estou ficando doente de sua constante irritação.}
{195}{}{Bem, por que você está falando comigo? Fale com eles e pegue o GECK.}
{196}{}{Eu irei - tudo com o tempo, meu amigo.}
{197}{}{Estou ficando doente de sua constante irritação.}
{198}{}{Que novidades do GECK, Escolhido?}
{199}{}{Encontrei o cofre!}
{200}{}{Não consegui encontrar o Cofre 13.}
{201}{}{Bem, olha, é o Escolhido.}
{202}{}{Olá.}
{203}{}{Cale-se.}
{204}{}{Posso te fazer uma pergunta?}
{205}{}{Não, não tenho tempo para você.}
{206}{}{Tanto faz. Adeus.}
{207}{}{Ah bem. Até a próxima.}
{208}{}{Morra.}
{209}{}{Saudações, maçante! Veja a ponte? Você atravessa, você tenha cuidado.
 Ponte perigoso. Você não quer cair. OK?}
{210}{}{Umm ... Hunh?}
{211}{}{Desgraçado! Você falhou na aldeia!}
{212}{}{Você nos traiu. Por isso você vai morrer!}
{213}{}{Você é um traidor para seu próprio povo.}
{214}{}{Por que você faz isso?}
{215}{}{O Ancião estava errado. Você é mau.}

{300}{}{Meu pai me ensinou como fazer lâminas mais fortes do que a maioria. Me pegue um pedaço
 de pederneira e também consertarei sua lança. Você precisará dele na região selvagem.}
{301}{}{Onde eu conseguiria um pouco desse pederneira?}
{302}{}{Eles dizem que sua tia Morlis vem acumulando uma peça. Ela é tão
 mal-humorado, não acho que alguém tenha perguntado a ela. Claro, a bruxa vai querer
 algo em troca.}
{303}{}{Thanks. Adeus.}
{304}{}{Você falou sua tia fora de seu sílex?}
{305}{}{Sim, tenho alguns aqui.}
{306}{}{Ainda não.}
{307}{}{É uma boa peça. Me dê sua lança.}
{308}{}{Aqui está.}
{309}{}{Acho que não tenho um.}
{310}{}{Agora, você coloca as peças assim ...}
{311}{}{O Escolhido sem uma lança? Bem, você terá que tomar um dos
 meu. Agora, vamos ao trabalho ...}
{312}{}{Aqui está a sua nova lança.}
{313}{}{Obrigado, meu amigo - isso ajudará muito.}
{314}{}{Sim, mas eu estava pensando sobre sua lança. Parece um pouco
 diferente.}


# added in for time limit
{400}{}{Bem-vindo a casa, Escolhido! Você encontrou o cofre? Você voltou com o GECK?}
{401}{}{Não encontrarei ainda.}
{402}{}{Não, ainda não encontrei.}
{403}{}{I'm not in the mood for your questions. Adeus.}
{404}{}{As coisas não estão indo bem, Escolhido. A seca está piorando e nossas colheitas são
 Certo de falhar. Estamos tentando salvar o que podemos para construir nossas reservas alimentares.}
{405}{}{Por que nenhum comércio com outra aldeia?}
{406}{}{Estou fazendo o melhor que posso. Eu acho GECK. Eu volto.}
{407}{}{Por que não podemos trocar com outras aldeias pelos alimentos que precisamos?}
{408}{}{Estou fazendo o meu melhor. Quando eu encontrar o GECK, vou voltar com ele.}
{409}{}{Nós somos pessoas simples e temos pouco a oferecer no comércio. As poucas cidades que temos
 contatado enquanto você estava ausente mostrou nenhum interesse em nos ajudar.}
{410}{}{Eu vejo.}
{411}{}{Entendo.}
{412}{}{Você é nossa esperança, Escolhido. Por favor, não nos falhe!}
{413}{}{É bom ver você, Escolhido. Como avaliar sua missão?}
{414}{}{Eu ainda olho.}
{415}{}{Ainda estou olhando.}
{416}{}{Eu não quero falar sobre isso.}
{417}{}{Você deve se apressar. As coisas estão ficando pior aqui em casa. Em breve haverá pouca comida e
 O Ancião fala de racionar o que temos. Temo pelo futuro do Arroyo.}
{418}{}{Escolhido! Diga-me que você completou sua missão. Nossa aldeia está morrendo, e assim
 são nossas pessoas.}
{419}{}{Não, eu ainda olho.}
{420}{}{No, Ainda estou olhando.}
{421}{}{Como estão as coisas?}
{422}{}{Desculpe, Escolhido, mas estou começando a questionar minha fé em você. A própria vida de
 nosso povo está em suas mãos. Por favor, encontre o Santo Treze e volte para nós com o GECK!}
{423}{}{Nossos cultivos falham, o brahmin morre, todo mundo está com fome agora. Os gritos das crianças à noite
 não permita que ninguém durma. Estamos nos tornando pessoas desesperadas.}
{424}{}{Eu continuo olhando.}
{425}{}{Eu farei o que puder.}
{426}{}{Mais uma vez você retorna para nós, Escolhido. Não é com as mãos vazias, espero?}
{427}{}{Me desculpe, não encontre GECK ainda.}
{428}{}{Desculpe, ainda não encontrei o GECK.}
{429}{}{Eu já tive o suficiente disso.}
{430}{}{As pessoas estão morrendo aqui enquanto você passeia pelas terras. Talvez você deva procurar
 em outro lugar em vez de voltar aqui.}

{500}{}{Você já conversou com o Mais velho?}

#############################################################
#  TELL - ME - ABOUTS                                       #
#############################################################
{1000}{}{Mais velho}
{1001}{}{Fundador}
{1002}{}{Cofre Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Cofre}
{1006}{}{Escolhido}
{1007}{}{Xamã}
{1008}{}{Hakunin}
{1009}{}{Pó de cura}
{1010}{}{Ponte}
{1011}{}{Mynoc}

{1100}{}{The Mais velho is your mother and our leader.}
{1101}{}{Nosso grande antepassado que nos deu conhecimento.}
{1102}{}{O primeiro a lutar e vencer o caos.}
{1103}{}{Essa seria a nossa bela aldeia.}
{1104}{}{Esse é um posto comercial a poucos dias a leste daqui.}
{1105}{}{The Cofre is heaven.}
{1106}{}{You are the Escolhido.}
{1107}{}{Ele nos cura com suas ervas e magia. Ele está no
 parte norte da nossa aldeia.}
{1108}{}{Ele nos cura com suas ervas e magia. Ele está no
 parte norte da nossa aldeia.}
{1109}{}{É um pó mágico que irá curá-lo, mas será
 fazer você com sono.}
{1110}{}{The Great Ponte exits our village in the south.}
{1111}{}{Esse seria eu.}
