#############################################################
#  Message File: ACSporPL.msg                               #
#                                                           #
#       Body Type:  Spore Plant(Plant with Dark Soul)       #
#       Combat AI: ?                                        #
#       Weapons: ?                                          #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê uma planta de alma escura.}
{101}{}{Estas plantas não são apenas prejudiciais para o jardim. Eles também têm a capacidade de atacar seres humanos
 e outras criaturas.}
{102}{}{Essas plantas de alma escura são uma mutação estranha. É duvidoso que eles mutassem dessa maneira como
 resultado de causas naturais.}
{103}{}{Você não percebe nada extra sobre essas plantas - além do fato de que eles atacam seres humanos.}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################
{150}{}{Você destruiu o jardim de todas as plantas da alma escura.}
