{100}{}{Você vê um posseiro.}
{101}{}{Você vê Bill, o posseiro.}
{102}{}{Você vê um homem de meia idade vestindo roupas usadas.}
{103}{}{Desculpe, estranho. Não tenho tempo para conversar com você.}
{104}{}{Ei, eu disse que não tenho tempo para conversar. Por favor vá embora.}
{105}{}{Obrigado por ajudar a Rebecca. Isso foi uma coisa boa que você fez.}
{106}{}{Me deixe em paz. Eu não sou ameaça para você.}
#push messages
{107}{}{Tudo bem, tudo bem. Estou me movendo.}
