{100}{}{Você vê uma jovem mulher.}
{101}{}{Você vê Chrissy, a filha de Rebecca.}
{102}{}{Você vê uma mulher muito jovem. Ela parece confiante e capaz de lidar com ela mesmo em uma briga.}
{103}{}{Se você está aqui para tentar me violar, você estará vestindo suas bolas como uma gravata. Pegue?}
{104}{}{Deixe-me adivinhar. Os caras estão cansados   de eu chutá-los onde dói, então eles o enviaram aqui para
 faça algo obsceno. Bem, eu posso te machucar tão mal. Eu só preciso pular mais alto. Pegue?}
{105}{}{Gravata-borboleta?}
{106}{}{}
{107}{}{O que aconteceu aqui? Quem você?}
{108}{}{}
{109}{}{Gostaria de saber quem você é e o que está acontecendo aqui.}
{110}{}{Sim. Um pano extravagante usado em volta do pescoço para decoração. É como um cachecol, mas para
 homens. Agora, imagine-me chutando-te com tanta dificuldade que acabas vestindo o seu dangly sobre o pescoço. Obter
 isto?}
{111}{}{Eu entendi. Você não me machucou.}
{112}{}{Eu entendi a foto; por favor, não me machuque.}
{113}{}{Ok, então, por que você está aqui?}
{114}{}{}
{115}{}{Eu quero saber o que acontecer aqui? Quem você?}
{116}{}{}
{117}{}{Gostaria de saber quem você é e o que está acontecendo aqui.}
{118}{}{Mesmo? Impressionante! Vamos.}
{119}{}{OK.}
{120}{}{Em poucas palavras, meu nome é Chrissy e eu sou do Squat. Eu estava explorando a semana passada quando eu
 descobriu essa entrada lá fora. Eu pensei que poderia ser uma mina abandonada ou algo assim, então eu decidi
 Confira. Bem, não é uma mina; É uma entrada secreta no Vault 15. O cofre está sendo
 usado como base para uma banda de invasores chamado Khans. Eles me pegaram passeando e seu líder, Darion, me fez trancar aqui.}
{121}{}{OK. Me take you home.}
{122}{}{Tudo bem, eu o levarei para casa.}
{123}{}{Bem, eu vou ser condenado. Hoje deve ser o meu dia de sorte. A que devo o prazer de te ver
 novamente?}
{124}{}{}
{125}{}{O que aconteceu aqui? Quem você?}
{126}{}{}
{127}{}{Gostaria de saber quem você é e o que está acontecendo aqui.}
{128}{}{Por favor, leve-me para minha mãe, Rebecca.}
{129}{}{Meu cavaleiro em armadura brilhante retorna. Bem, isso brilharia se você limpasse de vez em quando
 enquanto. Ah, e você pode querer considerar se banhar também. Então o que posso fazer por você?}
{130}{}{Eu apenas disse oi. Eu vou agora.}
{131}{}{Só pensei em dizer oi. Eu irei agora.}
{132}{}{Ei, eu sei que tenho uma boca inteligente, mas quero que você saiba que estou muito grato por você salvar
 meu traseiro. Muito obrigado!}
{133}{}{Bem vindo.}
{134}{}{Seja bem-vindo.}

{135}{}{As pessoas do Squat estão protegendo esses caras, ajudando-os a manter o cofre em segredo, mas eles
 Não sei o que realmente está acontecendo aqui. Darion nos disse que o cofre estava sendo reparado para que pudéssemos ter
 um lugar seguro para viver com muita comida e água, mas é uma mentira. Eu estive lá e olhei
 por aí. O cofre está morto, e as máquinas de alimentos e água não funcionam. Nossa comida e água estão chegando
 dos despojos
 de ataques contra caravanas.}
{136}{}{Olha, eu tenho que ir para casa e avisar todos sobre o que está realmente acontecendo aqui. Não podemos ajudar estes
 monstros. Você vai me levar para casa?}
