{100}{}{Você vê uma jovem mulher com roupas esfarrapadas.}
{101}{}{Você vê Dalia.}
{102}{}{Você vê uma jovem mulher com roupas esfarrapadas. She seems very alert, and watches her surroundings
 carefully.}
{103}{}{Oi. Eu sou Dalia. Com o que posso ajudar?}
{104}{}{Nada, basta dizer oi.}
{105}{}{Uh, quem você?}
{106}{}{O que você faz aqui?}
{107}{}{Você parece com guarda.}
{108}{}{Eu vou agora.}
{109}{}{Apenas dizendo olá.}
{110}{}{Quem é Você?}
{111}{}{O que você está fazendo?}
{112}{}{Você parece estar guardando essa trilha.}
{113}{}{Eu irei agora.}
{114}{}{Bem, olá para você. Agora, desculpe, mas você deveria ir.}
{115}{}{Eu quero falar.}
{116}{}{Ok, eu vou.}
{117}{}{Quero falar com você.}
{118}{}{Tchau.}
{119}{}{Eu disse que sou Dalia. Olha, eu não quero ser grosseiro, mas não quero conversar com ninguém agora. OK?}
{120}{}{Tudo bem tchau.}
{121}{}{Apenas um pouco mais.}
{122}{}{Então vou embora.}
{123}{}{Eu só quero fazer uma pergunta.}
{124}{}{Eu gosto do ar fresco, eu gosto das árvores, então estou aqui. Você tem algum problema com isso?}
{125}{}{Desculpe, eu vou.}
{126}{}{Não, não é problema. Eu te pergunto uma coisa.}
{127}{}{Não tenho problema, mas estou curioso sobre alguma coisa.}
{128}{}{Desculpe, eu irei então.}
{129}{}{Não, não estou guardando a trilha. Não há nada neste buraco que valha a pena proteger. Eu te disse, eu sou
 Aproveitando o ar fresco. Agora vá embora.}
{130}{}{Você fala bem com isso. Eu falo mais.}
{131}{}{Desculpe-me incomodar. Eu vou.}
{132}{}{Mas estamos tendo uma conversa tão agradável, por que parar?}
{133}{}{Eu acho que é hora de sair.}
{134}{}{Oh não, é a praga novamente. Olha, não tenho nada para te dizer. Vá embora!}
{135}{}{}
{136}{}{}
{137}{}{Não tenho discussão contigo. Deixe-me ser.}
{138}{}{}
{139}{}{}
{140}{}{Oi. Eu sou Dalia. Com o que posso ajudar?}
{141}{}{A pessoa vai por aqui? Com pressa?}
{142}{}{Nada.}
{143}{}{Nada.}
{144}{}{Você viu alguém passar por aqui com pressa?}
{145}{}{Eu vejo as pessoas passarem aqui todos os dias. Eu realmente não presto muita atenção a eles.}
{146}{}{Eu não tenho tempo para você, porcaria.}
{147}{}{Oh, está bem.}
{148}{}{A vida das garotas está em jogo. Rapariga. Alguém filha. Você ajuda?}
{149}{}{Eu não tenho tempo para sua porcaria.}
{150}{}{Tudo bem, tchau.}
{151}{}{Olha, a vida de uma jovem está em jogo aqui. A filha de uma mãe preocupada. Você pode por favor
 me ajude?}
{152}{}{Eu não dou a bunda de um radrat ... Desculpe. Eu sou apenas uma arma que foi contratada para ficar aqui e proteger
 Esta trilha. Além disso, não sei o que está acontecendo aqui. Eu tive uma filha uma vez, no entanto,
 E ... sim, algum cara foi aqui. Eu o soltei porque ele conhecia o sinal apropriado ... assim como o
 Assine você me deu. Continue. Estou fora daqui.}
{153}{}{Obrigado. Eu não esqueço isso, Dalia.}
{154}{}{Obrigado. Não vou esquecer isso, Dalia.}
{155}{}{Então vá longe e me deixe ser!}
{156}{}{Feito.}
{157}{}{Então vá longe e me deixe ser!}
{158}{}{Feito.}
