{100}{}{Você vê um incursor de Khan.}
{101}{}{Você vê um incursor de Khan.}
{102}{}{Você vê uma pessoa de aparência difícil com armaduras, armas e uma má atitude. Deve ser um Khan.}
#node1
{103}{}{O que ... Eu não acho que eu conheço você. Quem diabos é você?}
#responses 1
{104}{}{Eu tenho a minha ID aqui! Deixe-me mostrar-lhe.}
{105}{}{O nome é ... umm ... Pat, e eu sou novo aqui.}
{110}{}{Morrer!}

#node 2
{106}{}{Tudo bem, sábio-burro. Faça o seu melhor tiro.}

#node 3
#made skill check
{107}{}{Oh sim. Desculpa. Não o reconheci no início. Continue com o seu negócio.}
{108}{}{Ei, eu não sou tão estúpido quanto você parece.}

#node 4
{109}{}{Você ainda não está morto? Merda.}

#idle talking messages
#BLOCK 1
{110}{}{Cara, Darion não me paga o suficiente para ficar por aqui e não fazer nada.}
{111}{}{Às vezes eu sento e penso absolutamente em nada.}
{112}{}{Eu geralmente não me importo com o que alguém pensa.}
{113}{}{A ignorância é felicidade ... eu acho.}
{114}{}{Quando a próxima caravana está passando? Eu poderia usar alguma ação.}
{115}{}{Eu poderia usar uma pausa.}

#BLOCK 2
{116}{}{Maldita seja, ainda machuco daquela cadela Chrissy chutando-me.}
{117}{}{Ei, nunca recebemos sangue novo por aqui.}
{118}{}{Então, quando vamos sair desse lugar estúpido?}
{119}{}{Eu não sei sobre você, mas acho que isso é uma merda.}
{120}{}{Não há nada para matar por aqui.}
{121}{}{Onde está o banheiro?}

#BLOCK 3
{122}{}{Ei, nunca temos uma pausa por aqui. Não existe alguma lei ou algo assim?}
{123}{}{Deveríamos começar um governo como nos velhos tempos.}
{124}{}{Cara, eu me pergunto o que era ser presidente naquela época?}
{125}{}{Aposto que você poderia fazer o que quisesse se fosse presidente.}
{126}{}{Acho que meu pai ficaria orgulhoso de mim hoje. Muito ruim, eu o matei.}
{127}{}{EU DEIO RATOS! ÓDIO ODEIR ÓDIO}

#BLOCK 4
{128}{}{Ei, é essa armadura nova que você tem? Como você avalia a obtenção de novas armaduras?}
{129}{}{Este maldito cofre cheira. Você não odeia isso?}
{130}{}{Ei, para quem é que devemos manter o olho aberto?}
{131}{}{Tudo o que faço é ficar de pé, ficar de pé, ficar de pé.}
{132}{}{Eu acho que devemos desperdiçar todos os altos e dizer ao inferno com esse lugar.}
{133}{}{O que diabos é o seu problema com os ratos?}

#BLOCK 5
{134}{}{Você já tirou uma das pernas de um rato?}
{135}{}{Eu gosto de armas, sim! ARMAS QUE GOSTO! ARMAS: EU REALMENTE, REALMENTE GOSTO!}
{136}{}{Ei, alguém está me ouvindo?}
{137}{}{Bem, eu apenas falo para manter-me sã de qualquer maneira.}
{138}{}{Ei, alguém se lembra do que estava em um Long Island Ice Tea?}
{139}{}{Sim, vodka, rum, tequila, tripla sec, lima e Nuka.}

#Lights on
{140}{}{Olá, olha - as luzes acenderam. O que...}
{141}{}{Darion disse que conseguiria as malditas luzes fixas. Eu acho que ele passou.}
{142}{}{Eu não acho que o gerador apenas se conserte, não é?}
{143}{}{Isso foi meio estranho; agora eu posso ver. Jesus, este lugar parece uma merda!}
{144}{}{Uau, é brilhante aqui. Onde está o controle do dimmer?}
