{100}{}{Você vê um homem curto carregando um livro nas mãos dele.}
{101}{}{Você vê Doc Jones, o médico.}
{102}{}{Você vê um homem curto com um livro chamado "Então, você quer ser um médico".}
{103}{}{Olá, sou Doc Jones. Você pode me chamar Doc. Com o que posso ajudar?}
{104}{}{Tenho owie. Voce conserta?}
{105}{}{Sinta-se icky. Voce conserta?}
{106}{}{Eu gimp, você conserta?}
{107}{}{Tem perguntas. OK?}
{108}{}{Desculpe, eu vou.}
{109}{}{Estou ferido. Pode me ajudar?}
{110}{}{Me sinto mal. Pode me ajudar?}
{111}{}{Estou aleijado. Pode me ajudar?}
{112}{}{Queria fazer algumas perguntas.}
{113}{}{Apenas dizendo olá.}
{114}{}{Por que, certamente. Aqui, nós lhe daremos um tiro disso - isso vai parecer um pouco - agora uma bandagem,
 E lá, você está tudo pronto.}
{115}{}{Obrigado. Tchau.}
{116}{}{Obrigado, Doc. Eu me sinto muito melhor.}
{117}{}{Por que, certamente. Aqui, você precisará beber isso - tudo isso, eu sei que é bom gosto. Agora, apenas
 Deite-se na cama lá, e eu vou acordá-lo pela manhã.}
{118}{}{Eu me sinto bem. Tchau.}
{119}{}{Obrigado Doc, isso fez o truque.}
{120}{}{Me desculpe, mas não tenho instalações adequadas para realizar uma cirurgia. Eu sugiro que você vá para um
 Das cidades maiores e veja um cirurgião. Experimente o Vault City. Está a norte daqui.}
{121}{}{OK. Tchau}
{122}{}{Tudo certo. Obrigado mesmo assim.}
{123}{}{O que você gostaria de saber?}
{124}{}{Você trabalha com Darion?}
{125}{}{Você sai daqui quando quer?}
{126}{}{O que você sabe sobre Darion?}
{127}{}{Como você está aqui?}
{128}{}{Você diz que Darion ficou cachorrinho?}
{129}{}{Eu vou agora.}
{130}{}{Você trabalha para Darion?}
{131}{}{Você pode sair daqui se quiser?}
{132}{}{O que você pode me falar sobre Darion?}
{133}{}{Como você veio para estar aqui em primeiro lugar?}
{134}{}{Você mencionou que Darion tem um cachorro?}
{135}{}{Obrigado pela informação. Eu vou sair agora.}
{136}{}{Bem, sim e não. Não é por escolha. Eu sou um prisioneiro aqui. Darion está subindo lá nos anos
 E ele precisa de um médico dedicado para cuidar dele. Os Khans me mantêm aqui por suas necessidades. eu preferiria
 Esteja aqui para as pessoas da cidade acima. Eles não têm nenhuma ajuda médica, e há muito que posso
 Faça para ajudá-los.}
{137}{}{OK. Precisa saber mais.}
{138}{}{Obrigado. Tchau.}
{139}{}{Isso é muito louvável de você.}
{140}{}{Entendo. Eu irei agora.}
{141}{}{Eles são invasores! Deixe-os morrer. Vamos em frente com sua vida.}
{142}{}{Não, estou muito preso aqui. Eu não posso deixar de preencher meus suprimentos médicos. Darion
 Envia para tudo o que preciso.}
{143}{}{Eu entendi. Vá agora.}
{144}{}{Precisa pedir mais.}
{145}{}{Eu acho que você simplesmente não é uma pessoa confiável suficiente para que a liberdade seja permitida.}
{146}{}{Tudo certo. Me desculpe, mas tenho que ir.}
{147}{}{Sinto muito por ouvir isso.}
{148}{}{Darion é um caso mental, simples e simples. Ele tem mais espetáculos na cabeça do que o cachorro dele
 Pulga. Tanto quanto eu consigo entender, ele era membro de outra gangue chamada Khans. Eles seqüestraram
 Essa garota, Tandi, e a segurou por resgate. Seu pai não aceitou gentilmente isso e contratou algum
 Para recuperá-la. Darion foi o único a sair vivo.}
{149}{}{Uh ... o que você disse.}
{150}{}{Tenho que ir agora.}
{151}{}{Uh-huh. Bem, vou sair agora.}
{152}{}{Uau; Estou impressionado com o seu conhecimento.}
{153}{}{Parece meu tipo de cara.}
{154}{}{Fui seqüestrada. Eu estava viajando de Vault City para New Reno para férias bem merecidas. Foi
 Para dormir uma noite e acordei e amordaçou na manhã seguinte. Mais ou menos uma semana, eu estava aqui. Fui
 Aqui desde então.}
{155}{}{Ugh.}
{156}{}{Obrigado. Eu vou embora agora.}
{157}{}{Os fracos são muitas vezes presas dos fortes.}
{158}{}{Sinto muito por ouvir isso.}
{159}{}{Interessante, mas preciso ir.}
{160}{}{Sim, ele tem um cachorro. Pessoalmente, acho que é a criatura mais má, mais vil do rosto de
 a Terra. Parece amar Darion, no entanto, acho que não pode ser tão ruim assim.}
{162}{}{Uau, tchau.}
{163}{}{Entendo. Bem, obrigado pelo aviso.}
{164}{}{Ah. Bem, tenho que ir.}
{165}{}{Eu não ajudarei alguém como você. Vá embora.}
{166}{}{Ok, bem, você cuida e volte se precisar de alguma coisa.}
{167}{}{Feito.}

{168}{}{Agora ele é paranóico. Ele acredita que Tandi está fora para buscá-lo. Ele está obcecado com a vingança, e ele
 Quer que Tandi esteja morto. Ele está cheio de culpa porque ele se escondeu e morou, em vez de morrer com o dele
 Gangue ... e a lista continua e continua.}
