{100}{}{Você vê um posseiro.}
{101}{}{Você vê John, o ocupante.}
{102}{}{Você vê um homem de meia idade vestindo roupas usadas.}
{103}{}{Desculpe, estranho, não tenho tempo para conversar com você.}
{104}{}{Por que não falar?}
{105}{}{Ok, ondulado.}
{106}{}{Tudo bem, vejo você.}
{107}{}{Espere um minuto. Por que você não fala comigo?}
{108}{}{Nós somos uma comunidade muito privada aqui, e não queremos nenhum problema ou interferência de fora
 fontes. Por favor, deixe-nos estar.}
{109}{}{OK.}
{110}{}{Olá e adeus.}
{111}{}{Obrigado por tudo o que você fez. Peço desculpas pelo ombro frio mais cedo.}
{112}{}{Toque você, idiota!}

{113}{}{Porra, eu odeio quando isso acontece.}
{114}{}{Pegue isso! Sim, isso te mostrará.}
