{100}{}{Você vê um invasor de Khan.}
{101}{}{Você vê Phil, um guarda Khan.}
{102}{}{Você vê um jovem de aparência dura em armadura de metal. Ele está fortemente armado.}
{103}{}{Eu devia matá-lo morto, mas estou meio curioso sobre o que você poderia ter que dizer
 mim.}
{104}{}{Eu procuro espião. Vá por este caminho.}
{105}{}{Eu procura menina desaparecida. Você sabe onde encontrar?}
{106}{}{Eu venho aqui acidente. Vá agora.}
{107}{}{Dane-se. Eu te mato morto.}
{108}{}{Uh, nós conversamos isso?}
{109}{}{Estou à procura de um espião que veio dessa maneira.}
{110}{}{Estou à procura de uma menina desaparecida. A viu?}
{111}{}{Desculpe, tomei a trilha errada por acidente. Tenho que ir.}
{112}{}{Suba a sua e tenha uma bala de café da manhã, idiota.}
{113}{}{Eu acho que podemos falar isso como dois seres civilizados.}
{114}{}{Ah, esse seria eu. Agora que você me encontrou, qual é o próximo?}
{115}{}{Por que você espia Rebecca?}
{116}{}{Agora eu sei não estar atirar pessoa errada. Obrigado!}
{117}{}{Nada, eu vou agora.}
{118}{}{Por que você está espionando Rebecca?}
{119}{}{Só queria me certificar de que estou atirando na pessoa certa. Obrigado, e tenha um bom dia!}
{120}{}{Hmm. Nada, acho que vou agora.}
{121}{}{Eu não posso acreditar que você acha que pode simplesmente valsa aqui e obter respostas para suas perguntas!
 Oh, o que diabos, você está prestes a morrer de qualquer maneira e eu me sinto generoso. Nós temos seu filho preso no
 Atrás e se divertiram com ela. Essa cadela, Rebecca, tentou encontrá-la, então
 Nós mantemos um olho aberto para garantir que ela não fique muito perto.}
{122}{}{Você está doente na cabeça. Me consertar, remova a cabeça.}
{123}{}{O que você quer dizer, divirta-se com a menina?}
{124}{}{Oh, isso explica. Eu vou embora agora.}
{125}{}{Você é um cachorro doente. Eu acho que vou te colocar para dormir agora.}
{126}{}{Tudo bem, divirta-se e irei agora.}
{127}{}{Entregue a menina e todos podemos sair aqui vivos.}
{128}{}{Pense nisso enquanto você morre, estúpido.}
{129}{}{}
{130}{}{}
{131}{}{Por que diabos devo fazer isso?}
{132}{}{É bom para a sua alma eterna.}
{133}{}{Porque eu sou a pior coisa que você pode ter medo de acontecer com você. Entregá-la ou sentir
 a dor.}
{134}{}{Porque se lutarmos, um de nós morrerá. Eu não quero morrer mais do que você, então vamos acabar
 Isso de forma pacífica. OK?}
{135}{}{Aperte esse barulho.}
{136}{}{}
{137}{}{}
{138}{}{Isso parece um desafio. Eu vou levar.}
{139}{}{}
{140}{}{}
{141}{}{Hmm ... Eu ... Sim, ok. Aqui está a chave para sua cela; Ela está na sala dos fundos da barraca. Leve ela
 E saia, mas não volte. Se eu te ver novamente, veremos quem vive e quem morre.}
{142}{}{Vamos ver quem sai da vida.}
{143}{}{Obrigado, você fez o certo.}
{144}{}{A única maneira que você está deixando aqui é os pés primeiro, em uma caixa.}
{145}{}{}
{146}{}{}
{147}{}{Você quer dizer o trancado na parte de trás com o qual nos divertimos? Não, eu não a vi.}
{148}{}{Você está doente na cabeça. Me consertar, remova a cabeça.}
{149}{}{O que você quer dizer, divirta-se com a menina?}
{150}{}{Oh. Eu vou embora agora.}
{151}{}{Você é um cachorro doente. Eu acho que vou te colocar para dormir agora.}
{152}{}{Tudo bem, divirta-se e irei agora.}
{153}{}{Entregue a menina e todos podemos sair aqui vivos.}

{154}{}{Então, você retornou. Vamos ver quem sai no topo.}
{155}{}{Nós matamos aquela cadela Chrissy, e agora é a sua vez de morrer!}
