{100}{}{Você vê uma mulher mais velha.}
{101}{}{Você vê Rebecca.}
{102}{}{Você vê uma mulher mais velha. Although she appears to have lived a hard life, she has not lost any of
 her natural beauty.}
{103}{}{Oi, sou Rebecca. Podemos falar em particular, por favor?}
{104}{}{Sobre o que falar?}
{105}{}{Por que precisa falar em privado?}
{106}{}{OK.}
{107}{}{Não, eu vou embora.}
{108}{}{Desculpe, não estou interessado.}
{109}{}{Sobre o que você quer falar comigo?}
{110}{}{Claro, onde podemos procurar privacidade?}
{111}{}{Por que a necessidade de privacidade?}
{112}{}{(Sussurrando) Minha filha está perdendo e eu preciso de ajuda para encontrá-la. Não posso falar sobre isso aqui,
 Apesar. Podemos ir a algum lugar privado?}
{113}{}{OK.}
{114}{}{Por que precisa falar em privado?}
{115}{}{Não, eu vou.}
{116}{}{Tudo bem, vamos.}
{117}{}{Por que a necessidade de privacidade?}
{118}{}{Não, obrigado, não quero me envolver.}
{119}{}{(Sussurrando) Você pode pensar que eu sou louco, mas tenho a sensação de estar sendo observado o tempo todo. Está
 Um pouco perturbador, e estou um pouco afim por causa disso.}
{120}{}{Ok, ficamos privados.}
{121}{}{Não há tempo para a doença na cabeça.}
{122}{}{Tudo certo; Onde podemos conversar?}
{123}{}{Desculpe, eu não gosto do som disso.}
{124}{}{Obrigado; Podemos ir à minha tenda.}
{125}{}{OK.}
{126}{}{Devemos poder conversar aqui.}
{127}{}{Ok, que problema?}
{128}{}{Eu primeiro fiz perguntas.}
{129}{}{Ok, então, o que é tão importante?}
{130}{}{Tenho algumas perguntas para você, primeiro.}
{131}{}{Eu tenho uma filha chamada Chrissy, que é um pouco de garoto. Ela gosta de correr, explorar,
 E praticamente enfia o nariz nas coisas. Chrissy é um bom garoto, no entanto. Ela não
 Causa problemas, ela está sempre a tempo e ela mostrou-se uma jovem jovem muito responsável.
 Eu a deixo fazer o que quiser na maioria das vezes. Na semana passada, Chrissy não voltou para casa. Eu perguntei
 Em volta, ninguém viu nem ouviu falar dela. Eu tentei encontrá-la eu mesmo, mas Zeke, ele é ... tipo de
 O prefeito aqui ... me deteve. Ele disse que não era seguro para eu sair olhando sozinho; Ele teria alguns dos
 Seus homens fazem isso. Eles também não conseguiram encontrá-la e disseram que talvez as escravas a conseguissem.}
{132}{}{Não, não se envolva.}
{133}{}{Preciso pensar antes de decidir.}
{134}{}{Ok, eu pareço ser um tipo de herói ultimamente.}
{135}{}{Desculpe, não estou interessado.}
{136}{}{Eu preciso pensar sobre isso.}
{137}{}{Tudo bem, Rebecca. Vou tentar ajudá-lo.}
{138}{}{Se eu te ajudar, o que há para mim?}
{139}{}{O que você quer saber?}
{140}{}{O que aconteceu aqui?}
{141}{}{Quem chefe?}
{142}{}{Eu tente encontrar o Vault 13. Você sabe onde está?}
{143}{}{Conte sobre vault.}
{144}{}{Conte sobre Darion.}
{145}{}{Obrigado. Nós conversamos com você problema?}
{146}{}{O que está acontecendo aqui?}
{147}{}{Quem está no comando aqui?}
{148}{}{Estou à procura de Vault 13. Você sabe alguma coisa sobre isso?}
{149}{}{Conte-me sobre o cofre.}
{150}{}{Então me fale sobre Darion.}
{151}{}{Obrigado Rebecca. Vamos falar sobre o seu problema agora.}
{152}{}{Chamamos esse lugar do "Squat" porque foi resolvido pelos sem-teto de muitas cidades. Não é
 Muito, mas é tudo o que temos. Para o oeste é uma cidade chamada NCR. Eles sabem sobre nós para alguns
 Tempo, e nunca nos ofereceu nenhum tipo de ajuda ou obstáculo. Agora, eles estão repentinamente reivindicando essa área como
 Casa ancestral, e eles querem de volta.}
{153}{}{OK.}
{154}{}{O que eles querem?}
{155}{}{Entendo.}
{156}{}{O que é que eles querem tão mal?}
{157}{}{Bem ... há um cofre aqui; Eu acho que é o número 15. Eles querem saqueá-lo para qualquer um dos antigos
 Tecnologia que ainda pode estar lá.}
{158}{}{Ah. Eu entendo.}
{159}{}{Eu sabia que tinha que haver algo aqui além dos habitantes do desperdício de carne.}
{160}{}{Consegui.}
{161}{}{Isso explica muita coisa. Você foi muito útil. Eu ainda tenho que fazer mais algumas perguntas.}
{162}{}{Esse seria Zeke. Ele corre tudo aqui. Você pode encontrá-lo no prédio lá.
 :: pontos norte-leste ::}
{163}{}{Obrigado. Peça mais.}
{164}{}{Obrigado. Preciso fazer mais algumas perguntas.}
{165}{}{Desculpe, não tenho ideia. Gostaria de perguntar sobre isso na NCR. Eles tiveram um grande interesse em
 Cofres ultimamente.}
{166}{}{Ok, eu sim.}
{167}{}{Tudo bem, eu vou.}
{168}{}{Bem ... não devemos falar sobre isso, mas desde que eu preciso de sua ajuda ... O cofre está sendo
 Reparado por Darion. Ele é nosso benfeitor. Quando é totalmente funcional, todos nós devemos mudar
 Onde estaremos a salvo dos incursores, escravos e outros. Até agora ele tem os sistemas de alimentação e água, mas
 é sobre isso.}
{169}{}{Eu vejo. Precisa saber mais.}
{170}{}{Preciso saber mais.}
{171}{}{Não há muito a dizer, na verdade. Darion mantém-se e nunca sai do cofre. Se ele tiver
 Qualquer coisa a dizer, ele diz isso através de Zeke. Eu só conheci ele uma vez, e ele parecia um bom cara.}
{172}{}{OK.}
{173}{}{Caras finais acabam por último. Eu me pergunto o que ele está fazendo?}
{174}{}{Entendo.}
{175}{}{Tudo bem. Você é muito útil.}
{176}{}{Não tenho nada para te dar além da minha eterna gratidão.}
{177}{}{Isso é mais que suficiente. Vou te ajudar.}
{178}{}{Vai demorar mais do que isso para comprar minha ajuda.}
{179}{}{Que diabos, eu vou te ajudar.}
{180}{}{Muito obrigado. Nunca poderei reembolsá-lo por isso. Espero aqui até você trazer ...
 Ei, havia alguém fora nos ouvindo! Vi a sombra deles na parede da tenda. Eles simplesmente fugiram
 dessa maneira! :: pontos do nordeste :: eles devem ter ouvido tudo!}
{181}{}{Paro, não se afaste!}
{182}{}{Você não se preocupa, eu acho garota.}
{183}{}{Ooops.}
{184}{}{Vou tentar e detê-los.}
{185}{}{Eles não me impedirão encontrar sua filha.}
{186}{}{Ah bem. Merda acontece.}
{187}{}{Por favor, simplesmente vá embora.}
{188}{}{Você já pensou em coisas?}
{189}{}{Eu faz perguntas.}
{190}{}{Não, ainda pensa.}
{191}{}{Não, eu ainda estou considerando tudo.}
{192}{}{Quero lhe fazer algumas perguntas.}
{193}{}{Você mudou de idéia? Você vai me ajudar?}
{194}{}{Desculpe, não.}
{195}{}{Eu ajudo.}
{196}{}{Sim, vou ajudá-lo.}
{197}{}{Você deve ser a pessoa que salvou minha filha. Eu nunca posso reembolsá-lo por sua bondade. Obrigado.
 Aguarde aqui, eu preciso falar com Chrissy e então eu gostaria de falar com você.}
{198}{}{Você salvou minha filha. Eu nunca posso reembolsá-lo por sua bondade. Obrigado.
 Aguarde aqui, eu preciso falar com Chrissy e então eu gostaria de falar com você.}
{199}{}{OK.}
{200}{}{Minha filha me contou tudo. Eu acho difícil acreditar que Darion é um monstro
 Afinal, ele está fazendo por nós. E para pensar, nós o ajudamos a esconder suas operações como incursor.
 Posso garantir-lhe que não aguentaremos mais. Já falei com Zeke e ele quer ver
 você. Você deveria vê-lo agora.}
{201}{}{Eu acho difícil acreditar que Darion é um monstro, depois de tudo o que ele tem feito por nós. E para
 Pense, nós o ajudamos a esconder suas operações como incursor. Eu posso garantir-lhe que não representaremos
 Por mais tempo. Vou conversar com Zeke e explicar tudo. Tenho certeza de que ele vai querer vê-lo. Você deveria ir
 Fale com ele mais tarde.}
{202}{}{Obrigado.}
{203}{}{Espero que você encontre Chrissy em breve.}
{204}{}{Eu olhando.}
{205}{}{Vou continuar a procurá-la.}
{206}{}{Obrigado por tudo o que você fez por mim.}

{207}{}{Não posso explicar o porquê, mas não acredito que os escravos a tenham levado. Estou com uma sensação de desconforto que
 Alguma coisa está acontecendo. E então há esse sentimento de que estou sendo seguido. Eu já tive
 Desde que falei com Zeke sobre Chrissy. Preciso de alguém para me ajudar a encontrar minha filha. Você vai me ajudar,
 por favor?}
{208}{}{Eles continuam enviando pessoas aqui para tentar nos convencer de nossa casa, mas eles não entendem
 Que não temos para onde ir. Nós não temos as habilidades necessárias para sobreviver por conta própria se nós sairmos
 Aqui.}
{209}{}{Você sabe, é engraçado que eles conseguiram obter algo complexo, mas não o
 Luzes. O maldito lugar é iluminado por tochas. De qualquer forma, Darion não quer que ninguém saiba o que está acontecendo
 Com o cofre. Ele tem medo de que alguém o retire de tudo se eles descobrirem. Então, nós somos informados
 Para expulsar alguém que aparece aqui - especialmente a NCR.}
