{100}{}{Você vê um posseiro.}
{101}{}{Você vê Roberta, um invasor.}
{102}{}{Você vê uma mulher de meia idade vestindo roupas usadas.}
{103}{}{Oh meu. Me desculpe, mas não tenho nada para lhe dizer. Por favor vá embora.}
{104}{}{Por favor vá embora. Eu não quero ser incomodado.}
{105}{}{Obrigado por ajudar a Rebecca. Eu estava errado sobre você.}
{106}{}{Eu não sou ameaça para você. Não me mate.}
