{100}{}{Você vê um posseiro.}
{101}{}{Você vê Sara, um posseiro.}
{102}{}{Você vê uma mulher de meia idade vestindo roupas usadas.}
{103}{}{Por favor, não me incomode; Estou muito ocupado agora.}
{104}{}{Por favor vá embora. Não há nada aqui para você.}
{105}{}{Obrigado por ajudar a Rebecca. Foi uma coisa maravilhosa para você fazer para um estranho.}
{106}{}{Eu não sou ameaça para você. Não me mate.}
