{100}{}{Você vê um idoso mais velho.}
{101}{}{Você vê Zeke, um invasor.}
{102}{}{Você vê um homem mais velho com cabelos brancos e desbasteados.}
{103}{}{Meu nome é Zeke, estranho. Me desculpe, mas não tenho tempo para falar com você - e não penso
 Há alguma coisa nesta cidade para você, mesmo assim. Você deve seguir em frente.}
{104}{}{Uh, está bem.}
{105}{}{Eu tenho perguntas.}
{106}{}{Tudo bem, vou embora.}
{107}{}{Eu só queria fazer algumas perguntas.}
{108}{}{Bem, acho que você achará que estamos fora das respostas aqui. Por que você não volta quando nós?
 obter uma remessa?}
{109}{}{Feito.}
{110}{}{Olá de novo. Ainda não tenho respostas para você, estranho. Por que você não toma uma dica e
 tirar o pato do Fodge?}
{111}{}{Feito.}
{112}{}{Rebecca me contou o que você fez por ela. Quero pedir desculpas pelo tratamento que você recebeu
 Aqui. Você certamente não mereceu isso. Com o que posso ajudar?}
{113}{}{Eu tenho perguntas.}
{114}{}{Nada. Ondulado.}
{115}{}{Eu tenho algumas perguntas para você.}
{116}{}{Nada por enquanto, obrigado.}
{117}{}{O que você quer saber?}
{118}{}{Você trabalha para Darion?}
{119}{}{O que você faz sobre incursores?}
{120}{}{Onde a porta da abóbada?}
{121}{}{Mais alguma coisa acontecer aqui?}
{122}{}{Eu vou embora agora.}
{123}{}{Você trabalha para Darion?}
{124}{}{O que você pretende fazer sobre os incursores?}
{125}{}{Onde está a entrada da abóbada?}
{126}{}{Tem alguma coisa acontecendo aqui?}
{127}{}{Eu acho que é isso. Eu irei agora.}
{128}{}{Sim eu quero. Eu agio como o homem do meio entre ele e as pessoas aqui em cima. Não estou muito feliz por
 o fato, agora que eu sei o que ele está fazendo.}
{129}{}{OK.}
{130}{}{Entendo.}
{131}{}{Nada. Eles têm armas, controlam a água e controlam a comida. Que significa
 Eles estão no comando. Período. Não temos habilidades e sem meios de apoio sem o apoio de Darion.
 Como podemos nos voltar contra ele? Estamos à sua mercê.}
{132}{}{Hmm. Eu penso que eu entendo.}
{133}{}{Hmm. Entendo.}
{134}{}{Está por trás dessa porta por aí, mas está trancada do outro lado e presa, também. Eu não tenho
 qualquer forma de abri-lo ... Espere um minuto. Encontrei esse cartão-chave há algum tempo, e não tenho ideia do que
 isto é para. Rebecca diz que você encontrou algum tipo de porta onde eles estavam segurando Chrissy. Talvez isto
 O cartão abrirá. Aqui, pegue isso.}
{135}{}{Eu obrigado.}
{136}{}{Obrigado. Vou dar uma chance.}
{137}{}{Há uma cidade a oeste daqui chamada NCR. Eles afirmam que o Vault 15 é sua casa ancestral e eles querem isso
 costas. Eles estão enviando pessoas aqui tentando nos conversar para sair, mas não estamos indo para isso. Esta é a única casa que conhecemos.}
{138}{}{Você talvez faça negócios NCR?}
{139}{}{Você consideraria fazer um acordo com a NCR?}
{140}{}{Tudo depende disso. O que voce tinha em mente?}
{141}{}{Junte-se à tribo NCR. Aprenda com os anciãos. Dê NCR você permissão entre o vault. Ambos felizes.}
{142}{}{Participe da NCR, deixe-os anexar seu território e dê-lhes acesso ao cofre. Em troca, eles podem ensinar-lhe todas as habilidades
 você precisa sobreviver por conta própria e oferecer-lhe sua proteção.}
{143}{}{Não está mal ... Eu gosto disso. Você conseguiu um acordo se você conseguir que a NCR concordasse com isso também. Mas...
 Olha, alguém tem que cuidar de Darion e seus amigos. Isso deve ser feito agora antes de perceber o que aconteceu
 e ter tempo para se preparar para um ataque. Por que não acabar com isso e tirar Darion agora?
 Você terá o elemento de surpresa do seu lado.}
{144}{}{Você está certo, eu cuido.}
{145}{}{Não tenho certeza.}
{146}{}{Sim, acho que tem que ser feito.}
{147}{}{Eu não sei.}
{148}{}{Excelente. Boa sorte para você, e obrigado.}
{149}{}{Feito.}
{150}{}{Bem, aproveite o tempo para pensar sobre isso, mas conheça isso - até Darion estar fora da foto, eu
 não tem escolha senão manter as coisas por aqui como estão. É para a segurança de todos
 preocupado. Isso significa que não há acordo e você ainda é persona non grata. Compreendo?}
{151}{}{OK.}
{152}{}{Oi. Ainda estou esperando uma resolução final para nossos problemas. Em outras palavras, chute a bunda de Darion!}
{153}{}{Feito.}
{154}{}{Você fez isso, amigo! Não estamos mais sob o jugo de Darion. Obrigado! Estou pronto para aceitar o seu acordo com a NCR agora.
 Basta mandar enviar um de seus representantes e selarei o acordo.}
{155}{}{Feito.}
{156}{}{Obrigado pela chance de uma nova vida. Todos nós devemos você.}
{157}{}{Apenas vá embora. Eu não tenho nada para dizer para voce.}
{158}{}{Aguarde, antes de ir ... Encontrei esse cartão-chave há algum tempo, e não tenho ideia do que é isso.
 Rebecca diz que você encontrou algum tipo de entrada onde eles estavam segurando Chrissy. Talvez este cartão
 abra. Aqui, pegue isso.}
{159}{}{Obrigado.}
{160}{}{Com o que posso ajudar?}
{161}{}{Apenas os problemas com a NCR, mas acho que o acordo que você ofereceu resolverá isso.}
{162}{}{Você fez isso, amigo! Não estamos mais sob o jugo de Darion. Obrigado!}

{163}{}{Agora que Darion se foi, não temos como chegar comida. Nós certamente morreremos! Muito obrigado.}
