{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal do computador da biblioteca.}
{102}{}{Você vê um terminal de computador padrão. Parece estar funcional e pronto para entrada.}
{103}{}{Você acessa o computador e examina rapidamente todos os arquivos disponíveis. Você encontra a localização do Vault 13
 e copie para o seu PIP-Boy.}
{104}{}{Você está tendo dificuldade em acessar os arquivos.}
{106}{}{Além da localização do Vault 13, o computador não contém informações úteis.}
