{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal de computador de Darion.}
{102}{}{Você vê um terminal de computador padrão. Parece estar funcional e pronto para entrada.}
{103}{}{Você acessa o computador e examina rapidamente todos os arquivos disponíveis. Entre algum jornal pessoal
 Entradas, você encontra vários relatórios detalhados sobre a NCR. Parece que há um espião em seu conselho.
 Você copia os relatórios para um holodisco.}
{104}{}{Você está tendo dificuldade em acessar os arquivos.}
{105}{}{Feito.}
{106}{}{Além da informação sobre o espião NCR, o computador não contém informações úteis.}
{107}{}{Feito.}
