{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal do computador do centro de energia.}
{102}{}{Você vê um terminal de computador padrão. Parece estar funcional e pronto para entrada.}
{103}{}{Este terminal monitora o gerador de energia. Isso indica que tudo está funcionando
 normalmente.}
{104}{}{Este terminal monitora o gerador de energia. Indica que a unidade está desligada devido a uma
 Mau funcionamento de algum tipo.}
{105}{}{Feito.}
