{100}{}{O gerador está funcionando normalmente. A saída de energia é otimizada.}
{101}{}{O gerador parece estar em um modo de espera de emergência. A potência de saída é mínima.}
{102}{}{Tente diagnosticar o problema.}
{103}{}{Ah bem. Tenho que ir.}
{104}{}{Deve ter havido um curto no sistema em algum momento. Os disjuntores de emergência derrubaram
 dentro, mas fundido na posição aberta. Você pode liberá-los e restaurar a energia.}
{105}{}{Você não consegue encontrar nada de errado. Simplesmente não funciona.}
{106}{}{Tente repará-lo.}
{107}{}{Hora de partir.}
{108}{}{Você conseguiu quebrar os contatos solto e restaurar o poder!}
{109}{}{Droga. Isso é mais difícil do que parece.}
{110}{}{Feito.}
