{100}{}{Você vê alguém em uniforme militar.}
{101}{}{Você vê alguém em uniforme militar.}
{102}{}{Você vê alguém vestindo um uniforme militar, mas parece ser mais tecnológico que um soldado.}

{103}{}{Ei. Como tá indo?}
{104}{}{'Roger que, eu tenho você no escopo' - desculpe, mas estou no meio de algo agora.}
{105}{}{Não posso falar agora.}
{106}{}{Sinta-se livre para olhar, mas não toque.}

{107}{}{Você é louco para andar aqui fora de uniforme? Seja adequado!}
{108}{}{Se o sargento te tirar do uniforme, ele vai te entregar seu traseiro.}
{109}{}{Por que você está fora de uniforme?}

{110}{}{Merda! Estamos sendo invadidos! Alerta!}
{111}{}{Intrusos! Ligue para o guarda!}
{112}{}{Guarda! Intrusos no controle de tráfego aéreo!}

{113}{}{Estás bem? Estamos sob ataque?}
{114}{}{Por que o alerta? O que está acontecendo?}
{115}{}{O que está acontecendo?}
