{100}{}{Você vê um cozinheiro.}
{101}{}{Você vê Cookie, o cozinheiro.}
{102}{}{Você vê um homem de armadura vestindo um chapéu de chef e um avental.}

{103}{}{Ei, soldado. Você está procurando algum grub ou apenas alguém para conversar?}
{104}{}{Eu quero comida.}
{105}{}{Eu quero falar.}
{106}{}{Eu poderia usar algo para comer.}
{107}{}{Vamos conversar por um tempo.}

{108}{}{Bem, aqui você vai. Tenha alguma merda em uma telha. A merda da neve e da mosca está por aí. Algo mais?}
{109}{}{O que você quer que eu coma?}
{110}{}{Merda? Neve? Que tipo de comida é essa?}

{111}{}{Me desculpe, você deve ser novo no exército. Não se ofenda com o que eu disse, é exatamente o que chamamos de coisas aqui.
 Merda na carne de bovino lascada em uma torrada. Snow and fly shit é outro nome para sal e pimenta.}
{112}{}{Oh ... obrigado. Conversamos enquanto comemos.}
{113}{}{Entendi, desculpe. Vamos conversar enquanto eu como.}

{114}{}{Sobre o que você quer falar?}
{115}{}{O que aconteceu aqui?}
{116}{}{Onde os planos de verão são?}
{118}{}{Onde a base principal?}
{119}{}{Eu preciso voltar a plantão. Obrigado.}
{120}{}{O que está acontecendo aqui?}
{121}{}{Estou interessado nos vertibirds. Se eu quisesse olhar os planos, onde eu poderia encontrá-los?}
{123}{}{Onde está a base principal do Enclave?}
{124}{}{Obrigado. Preciso voltar para o post do meu dever.}

{125}{}{À procura de algumas fofocas? Eu poderia te dar o mais recente sobre o que está acontecendo na manutenção, med lab, ou entre os grunhidos.}
{126}{}{O que você quer ouvir?}
{127}{}{E a manutenção?}
{128}{}{E o laboratório de med?}
{129}{}{E os grunhidos?}
{130}{}{Algo mais?}
{131}{}{Eu ouço o suficiente.}
{132}{}{O que está acontecendo na manutenção?}
{133}{}{O que você pode me falar sobre med lab?}
{134}{}{E a respeito de nós grunhidos?}
{135}{}{Mais alguma coisa acontecendo?}
{136}{}{Já ouvi o suficiente, penso.}

{137}{}{Raul, o mecânico de vertibird, não gosta de Quincy, o chefe de manutenção. Esses dois são sempre
 Entrando nisso. Eu também não acho que seja um caso de rivalidade profissional. Enfim, Raul é um arrogante
 Mas Quincy é um bom tipo de cara. Espero que ele vença no final.}
{138}{}{OK.}
{139}{}{Sim, eu ouço você.}

{140}{}{O laboratório de Med foi assumido por um Enclave egghead chamado Schreber. Maldito filho da puta; Não se importa
 Por nada ou por ninguém. Ele tem feito algum tipo de experimentos com os cânceres da morte lá embaixo, não sei
 O que embora. Enfim, ele estava fazendo todos os tipos de barulho até que o comandante ordenou que o quarto fosse insonorizado.}
{141}{}{Consegui.}
{142}{}{Isso é interessante.}

{143}{}{Ha! Estamos falando de romance, meu amigo. Parece que um dos geeks do computador caiu por um dos grunhidos, o guarda fora do laboratório de medicina. Mesmo tem um desses nomes cutesy para ela. Chama sua "Snookie" de todas as coisas.}
{144}{}{Fofa.}

{145}{}{Nah, é isso em torno deste lugar. Se eu ouvir algo mais, eu vou deixar você saber. Eu gosto de falar sobre isso tanto quanto eu gosto de ouvi-lo!}
{146}{}{Obrigado.}

{147}{}{Por que você está interessado nesses? Bem, não importa. Quincy mantém-os em manutenção, penso.}
{148}{}{OK.}
{149}{}{Onde isso?}
{150}{}{Entendo.}
{151}{}{Onde é isso?}

{152}{}{Northeast corner of the base, amigo. Não pode perder.}
{153}{}{OK. Obrigado.}

{156}{}{Estou surpreso que você não sabe, você deve ser um local, eu acho. Enfim, a base principal está no meio do maldito
 oceano. Bem, não poço no meio, mas pode ser bem. A única maneira de chegar lá é por navio ou vertibird
 E o maldito navio foi manipulado. Você precisa de um fob para operar a maldita coisa.}
{157}{}{Fob?}

{158}{}{Sim, uma senha. O comandante o guarda em seu escritório. Sem isso, você não pode acessar algumas áreas do navio e isso
 Mantém os moradores locais em San Fran de pagar uma visita indesejável.}
{159}{}{Boa ideia.}
{160}{}{Onde escritório do comandante?}
{161}{}{Essa é uma boa ideia.}
{162}{}{Então, onde está o escritório do comandante?}

{163}{}{Pegue o elevador na próxima sala para baixo, siga o corredor até a junção principal e siga em frente.}
{164}{}{Obrigado.}

{165}{}{Ei, soldado. É bom ouvir de você novamente. Grub ou conversa esta vez?}
{166}{}{Comida.}
{167}{}{Bate papo.}
{168}{}{Eu apenas disse oi.}
{169}{}{Nem, só estou dizendo oi.}

{170}{}{Aqui você vai. Está morto, está cozido, não é identificável. Apreciar.}
{171}{}{Uh... Obrigado.}

{172}{}{Filho, posso dizer com o cheiro que você não está usando nenhum desses ternos de armaduras motorizadas.
 Se o sargento o vir fora do uniforme você está ferrado. E eu não estou falando sobre o tipo de parafuso que se sente bem. Agora pegue seu culo para fornecer e atender.}
{173}{}{Pequena senhora, posso dizer com o cheiro que você não está usando nenhum dos seus ternos de armadura.
 Se o sargento o vir fora do uniforme você está ferrado. E eu não estou falando sobre o tipo de parafuso que se sente bem. Agora pegue seu culo para fornecer e atender.}
{174}{}{Onde isso?}
{175}{}{OK.}
{176}{}{Onde é isso?}
{177}{}{Eu cuidarei disso.}

{178}{}{Pegue o elevador no quarto seguinte para baixo, siga o corredor até a junção principal, vire à esquerda e é a primeira porta à sua esquerda. Você vai embora.}
{179}{}{Obrigado.}

{180}{}{Merda! Eu sou apenas um cozinheiro ... e um cego contra isso. Não vi nenhum intruso chegar aqui.}
{181}{}{Obrigado.}

{182}{}{Damned alarmas. Sempre seja um golpe tão grande quando eles saem.}
{183}{}{Por que diabos esta coisa tão maldita sobre esse tempo?}
{184}{}{Desejo que usássemos alarmes silenciosos, maldita coisa me dê uma dor de cabeça.}

{185}{}{Eu vou fritar sua bunda e servi-la em um prato.}
{186}{}{Seu ganso está cozido. Ha! Eu fiz um engraçado!}
{187}{}{Fora da frigideira e no fogo.}
