{100}{}{Você vê um cientista.}
{101}{}{Você vê o Dr. Schreber.}
{102}{}{Você vê um homem calvo em um bata de laboratório.}

{103}{}{Espero que você tenha uma boa razão para interromper meu trabalho, soldado.}
{104}{}{Eu quero fazer perguntas.}
{105}{}{Não, eu volto mais tarde.}

{106}{}{Muito bem. Eu tenho que viver com você grunhidos para que eu possa também fazer
 um esforço para se dar bem com você.}
{107}{}{O que você quer saber?}
{108}{}{Quem você?}
{109}{}{O que você faz?}
{110}{}{Qual é esse lugar?}
{111}{}{Por que o quarto não fez nenhum som?}
{112}{}{Por que D'garra em outro quarto?}
{113}{}{Por que cachorrinho pela porta sem movimento? Não há nada?}
{114}{}{Eu já fui embora.}
{115}{}{Quem é Você?}
{116}{}{O que você faz aqui?}
{117}{}{O que é este lugar?}
{118}{}{Por que este quarto é insonorizado?}
{119}{}{Por que há uma perna na outra sala?}
{120}{}{O que é com a estátua do cachorro perto da porta?}
{121}{}{Preciso ir agora.}

{122}{}{Meu nome é Schreber, Dr. Schreber. Eu sou o médico de base entre
 outras coisas. Não se preocupe com o seu nome, soldado. Todos vocês grunhidos olham
 o mesmo naquela armadura sua.}
{123}{}{OK.}
{124}{}{Consegui.}

{125}{}{Eu trabalho como médico de base, mas isso é apenas uma linha lateral. Na realidade,
 Sou geneticista.}
{126}{}{O que é isso?}
{127}{}{O que é um geneticista?}

{128}{}{Eu realmente não acho que você tenha a capacidade intelectual para
 Compreenda meu trabalho, soldado. Digamos que eu posso "personalizar" as pessoas
 ou animais.}
{129}{}{Sim claro.}
{130}{}{Sim ... Preciso te pedir mais algumas coisas.}

{131}{}{Este foi o laboratório de base da med. No entanto, senti que meus experimentos
 prevaleceu sobre as necessidades médicas mínimas dos soldados aqui
 Eu o converti em um laboratório.}
{132}{}{Quão legal.}
{133}{}{Isso é bom. Então me conte outra coisa.}

{134}{}{Por que o quarto não fez nenhum som? Oh, you mean the soundproofing! In the
 course of my research I perform... experiments on test subjects.
 Sometimes they get a little vocal. The base commander found this to
 be disturbing so he had the soundproofing installed.}
{135}{}{No decorrer da minha pesquisa eu executo ... experimentos em teste
 assuntos. Às vezes eles ficam um pouco vocais. O comandante da base encontrou
 Isso é perturbador, então ele teve a insonorização instalada.}
{136}{}{Ah ...}
{137}{}{Entendo.}

{138}{}{Grande, marrom e feio? É uma experiência que eu recentemente
 completado. Está programado para término.}
{139}{}{Qual terminação significa?}
{140}{}{Por que você vai matá-lo?}

{141}{}{Oh, meu ... Você não é brilhante? Terminar. Mate, derrube,
 dormir, morrer. Pegue?}
{142}{}{Eu consegui. Por que você quer matar D'garra?}

{143}{}{O Enclave procurou soldados baratos e descaráveis.
 Estamos interessados   em pernas mortas porque construíram armaduras e
 armas, e eles são maus como o inferno. Eles só precisam ser mais inteligentes para
 eles podem entender comandos, mas não muito inteligentes ou podem desenvolver
 uma vontade própria. Comigo até agora?}
{144}{}{Uh ... Sim.}
{145}{}{Sim, eu sigo você.}

{146}{}{Bem, conseguimos! Conseguimos realmente aumentar a sua
 inteligência. No entanto, comecei a suspeitar que fomos longe demais.
 Que talvez eles fossem muito mais inteligentes do que estavam deixando. assim
 Quando fui transferido aqui trouxe um deles comigo, então eu
 poderia colocar minha teoria à prova.}
{147}{}{E?}

{148}{}{Eu tinha razão! Os deathclaws aparentemente estão jogando
 burro, aguardando seu tempo e tentando aprender o máximo que puderem
 de nós. Eles podem até imitar o discurso humano! Eu realmente tive um
 conversa com aquele sujeito na sala ao lado.}
{149}{}{De qualquer forma. O fato de serem capazes de conceber
 Este plano e retirar a decepção mostra quão perigoso é
 eles são.}
{150}{}{Então, o que você planeja fazer agora?}
{151}{}{Então, o que você planeja fazer agora?}

{152}{}{Eu vou escrever um relatório sobre minhas descobertas e tê-lo
 transmitido para o Enclave. Claro que vou ter que recomendar o
 extermínio da raça deathclaw. Eles são muito perigosos
 uma ameaça.}
{153}{}{Eu consegui. Precisa pedir mais.}
{154}{}{Uh ... Você está seguro de que é insonorizado?}
{155}{}{Eu quero matar D'garra para você!}
{156}{}{Ei, posso matar a morte por você?}
{157}{}{Interessante. Posso lhe perguntar sobre outras coisas?}
{158}{}{Diga Doc, você tem certeza de que este quarto é insonorizado?}

{159}{}{Claro que tenho certeza. O comandante teria um ajuste diferente. Por quê?}
{160}{}{Sem motivo.}
{161}{}{Eu não quero que ninguém ouça você gritar enquanto eu mata você!}
{162}{}{Eu só estava curioso.}
{163}{}{Eu não quero que ninguém ouça seus gritos enquanto eu experimento em você.}

{164}{}{De volta? O que posso fazer por você desta vez?}
{165}{}{Você acha que é insonorizado?}
{166}{}{Eu tenho mais perguntas.}
{167}{}{Nada. Eu disse oi.}
{168}{}{Você tem certeza de que este quarto é insonorizado?}
{169}{}{Queria lhe perguntar outra coisa.}
{170}{}{Nada, eu só queria dizer 'Olá' novamente.}

{171}{}{Claro que tenho certeza. O comandante teria um ajuste diferente. Por quê?}
{172}{}{Sem motivo.}
{173}{}{Eu não quero que ninguém ouça você gritar enquanto eu mata você!}
{174}{}{Eu só estava curioso.}
{175}{}{Eu não quero que ninguém ouça seus gritos enquanto eu experimento em você.}

{176}{}{Seja meu convidado. Está no quarto ao lado.}
{177}{}{Obrigado!}

{178}{}{Isso é K-9, meu cachorro. Eu decidi ver se eu poderia ciber
 melhorar a sua inteligência. Funcionou, mas ele desenvolveu um caso ruim de
 moral. Ele decidiu que ele não gostava tanto do meu trabalho nem de mim, e ele me mordeu.}
{179}{}{Como punição, desabilitava as pernas, mas o deixava praticamente
 de outra forma. Agora ele fica sentado lá e observa cada
 coisa desagradável que eu faço.}
{180}{}{Ah ...}
{181}{}{Ele é consertado?}
{182}{}{Entendo.}
{183}{}{Ele pode ser consertado?}

{184}{}{Ai sim. Retirei seu circuito de motivação e entreguei a
 Raul em manutenção. Sempre pode ser posto de volta em ... Talvez
 Eu vou fazer um dia para ver se ele mudou sua atitude.}
{185}{}{OK.}
{186}{}{Tudo certo.}

{187}{}{Você é civil?}
{188}{}{Este é o laboratório de medicina. O arsenal está no corredor à sua esquerda.}
{189}{}{Por que você está fora de uniforme?}

{190}{}{Merda! Estamos sendo invadidos! Alerta!}
{191}{}{Intrusos! Ligue para o guarda!}
{192}{}{Guarda! Intrusos no laboratório de medicina!}

{193}{}{Estás bem? Estamos sob ataque?}
{194}{}{Por que o alerta? O que está acontecendo?}
{195}{}{O que está acontecendo?}

{196}{}{Não sou hostil, não me atire.}
{197}{}{Eu não me inscrevi para o combate, então me deixe em paz.}
{198}{}{Droga! Eu sou um médico não um soldado!}

{200}{}{[Mais]}
{201}{}{Queria fazer algumas perguntas.}
{202}{}{Não agora. Desculpe incomodá-lo.}

{800}{}{Você matou o doutor Schreber.}
