{100}{}{Você vê alguém em armadura de combate.}
{101}{}{Você vê o guarda da porta do comandante.}
{102}{}{Você vê alguém em armadura de combate. There is an insignia on the breastplate that you are not familiar with.}

{103}{}{Senhor! Qual é o seu negócio aqui?}
{104}{}{Qual é esse lugar?}
{105}{}{Uh ... eu novo aqui.}
{106}{}{Eu aqui limpo.}
{107}{}{Não me lembro. Eu vou.}
{108}{}{O que é este lugar?}
{109}{}{Oi, sou novo aqui.}
{110}{}{Estou aqui para limpar o escritório do comandante.}
{111}{}{Deixa pra lá.}

{112}{}{Este é o escritório do comandante da base. Esta área está fora de limites para todo o pessoal. Vou pedir-lhe que vá embora, senhor.}
{113}{}{Eu tenho negócios com o comandante.}
{114}{}{Bem.}
{115}{}{Tenho negócios com o comandante.}
{116}{}{Tudo certo.}

{117}{}{Qual é a natureza do seu negócio, senhor?}
{118}{}{Uh ...}
{119}{}{Merda. Eu estragado ...}
{120}{}{Deixa pra lá. Me go}
{121}{}{Bem...}
{122}{}{Uh, recebemos uma chamada da base de segurança. Parece que eles estão preocupados com a passagem do petroleiro na mão errada. Vamos bloqueá-lo.}
{123}{}{Estou indo embora.}

{124}{}{Senhor, este é o seu último aviso. Eu tenho que pedir-lhe para sair desta área.}
{125}{}{Está bem.}
{126}{}{Oh ... Foda-se. Eu vou atirar.}
{127}{}{Foda-se. Entrando com armas ardendo.}

{128}{}{O que? Oh, entendi. Você ferrou o cachorrinho e Dornan's conseguiu você em detalhes de limpeza.}
{129}{}{Sim ... eu parafuso ... doggy e ... yuck.}

{130}{}{(falando sozinho) Comandante. Os detalhes de limpeza estão aqui, senhor. (pausa) sim, senhor. (olhando para você) Continue.}
{131}{}{Obrigado.}

{132}{}{(falando sozinho) Comandante. O detalhe da segurança está aqui. A base principal quer que a senha do petroleiro seja segura. (pausa) sim, senhor. (olhando para você) Continue.}
{133}{}{Deixe-me ver suas ordens.}
{134}{}{Obrigado.}
{135}{}{Ah, não os trouxe comigo.}

{136}{}{(silenciosamente) Você deve estar perdido então. Este é o escritório do comandante da base. Ninguém é permitido aqui a menos que o velho o envie.}
{137}{}{Ninguém vem aqui? Sempre?}
{138}{}{Ninguém o vê?}

{139}{}{(silenciosamente) Ninguém. Bem, apenas a equipe de limpeza. Eles geralmente vem por aqui em uma hora ou assim. Além disso, este lugar está fora dos limites. Agora, é melhor você seguir em frente.}
{140}{}{OK.}

{141}{}{(falando sozinho) Comandante. Os detalhes de limpeza estão aqui, senhor. (pausa) sim, senhor. (olhando para você) Continue.}
{142}{}{Você é cedo. Volte mais tarde.}
{143}{}{OK.}

{144}{}{Em seguida, volte para o centro do centro e faça com que imprimam o pedido.}
{145}{}{OK.}

{146}{}{Você deve procurar o arsenal. Volte para o corredor, vire à direita e é a primeira porta à esquerda. Você terá seu problema lá.}
{147}{}{Obrigado.}

{148}{}{Quem diabos são vocês ... Alerta! Intrusos!}
{149}{}{Fomos infiltrados! Alerta!}
{150}{}{Múltiplos intrusos! Toque o alarme!}

{151}{}{Alerta de segurança! Selar a base!}
{152}{}{Proteja todas as estações! Estamos em alerta}
{153}{}{Alerta de intrusão! Digite o código vermelho!}

{154}{}{Nós vamos colocá-lo sob!}
{155}{}{O Enclave governará o mundo!}
{156}{}{Você morre para que o Enclave vai sobreviver!}

{160}{}{Você voltou. Você trouxe a ordem para o Fob com você?}
{161}{}{Não, ainda não. Eu entendi.}

{162}{}{Okay, certo. Eu lhe digo que a equipe de limpeza está chegando e então você, magicamente, se torna um deles.
 Você nem me deixou a vista. Você acha que eu sou um idiota? Saia daqui!}
