{100}{}{Você vê um guarda.}
{101}{}{Você vê o guarda do portão.}
{102}{}{Você vê um guarda com uma armadura de poder de um design incomum. Há uma insígnia no peitoral com a qual você não conhece.}

{103}{sgnt1a}{Bem-vindo ao Camp Navarro ... um civil! Como no inferno um civil chegou a essa base! Eu vou ter um traseiro para jantar! Obter este civil fora da propriedade do governo.}
{104}{sgnt1b}{Bem-vindo ao Camp Navarro ... civis! Como os civis chegaram a essa base! Eu vou ter um traseiro para jantar! Retire esses civis das propriedades do governo.}
{105}{}{Esperar. EU...}

{106}{sgnt2a}{Bem, eu vou ser condenado. Eu escolhi essa base e aqui está novamente. Eu não acho que você é civil, afinal. Mais do que provavelmente você é um espião! Sente o alarme e execute essa larva!}
{107}{sgnt2b}{Bem, eu vou ser condenado. Tive o grupo de vocês escoltado desta base e aqui está novamente. Eu não acho que vocês são civis depois de tudo. Mais do que provável, você é todo espião! Sente o alarme e execute essas larvas!}

{108}{sgnt3}{Bem-vindo ao Camp Navarro. Então, você é o substituto. Qual o seu nome, privado?}
{109}{}{Uh ... eu}
{110}{}{Eu estou}

{111}{sgnt4}{Oh amável. Eles me enviaram um mo-ron. Ouça com atenção. Você ficará de guarda no hangar. Esta é a sua publicação de dever. Você vai lá agora e fique de guarda até que seja dito de outra forma. Agora mova, soldado!}
{112}{}{Eu vou.}

{113}{sgnt5}{O que é que foi isso? Você esqueceu alguma coisa, maggot?}
{114}{}{Meu nome é}

{115}{sgnt6}{Eu não sou um senhor. Eu trabalho para ganhar a vida, você é mo-ron. Você vai me chamar de sargento ou sargento Dornan. Você me entende!}
{116}{}{Sim, sargento!}
{117}{}{Claro, Sargento. Tanto faz.}

{118}{sgnt7}{Excepcional. Prossiga no duplo para o hangar, onde você ficará de guarda. Você fará um bom trabalho. Voce entende?}
{119}{}{O que eu guardo lá, sargento?}
{120}{}{Sim, sargento!}

{121}{sgnt8}{Você ainda não deve questionar minhas ordens! Quando eu digo saltar, você pula! Quando eu digo luta, você luta! Quando eu digo que você morra por seu país, então você certamente morrerá! Fiz claro?}
{122}{}{Sim, sargento!}

{123}{sgnt9}{Bem-vindo ao Camp Navarro. Então, você é a nova substituição ... Você está fora de uniforme, soldado! Onde está sua armadura de poder?}
{124}{}{Uh ... eunot have.}
{125}{}{A base não me emitiu nenhum. Eles disseram que seria emitido aqui.}
{126}{}{Uh ... Eu não tive nenhuma armadura.}
{127}{}{Acontece que você está vestindo ... Eu vou tirar seu cadáver!}

{128}{sgnt10}{Não tem nenhum? Você espera que eu acredite nisso, maggot? A verdade é que você perdeu uma peça cara de equipamento do exército. Esse processo vai sair do seu salário, e você permanecerá neste exército do homem até que você tenha quinze anos de idade, o que é o número de anos que você terá que pagar por um Mark II Powered Combat Armor você perderam! Informe para o arsenal e tenha um novo terno emitido para você, então informe-me, privado! Demitido!}
{129}{}{OK. Eu vou pegar um terno.}
{130}{}{Sim, sargento!}

{131}{sgnt11}{Esses bichos de troca de papel! Como diabos eles esperam que eu execute esta unidade se eles continuam me falando em suprimentos! Dupla vez até o arsenal e obter o seu problema, então informe-me. Demitido!}
{132}{}{OK.}
{133}{}{Sim, sargento!}

{134}{sgnt12}{Se eu gosta de você, você pode me chamar de Sarge. Mas adivinhe o quê? Eu não gosto de você! Voce entende?}
{135}{}{Sim, sargento!}

{136}{sgnt13}{Excellent! You’re in uniform now so Eu estougoing to give you a rare opportunity. We are going to start over as if I never met your sorry ass. Would you like that, soldier?}
{137}{}{Sim, uh ... Sargent!}
{138}{}{Não! Eu não me importo mais. Eu chutá-lo, burro.}
{139}{}{Sim, sargento!}
{140}{}{I don’t particularly care now that Eu estouwearing this nice armor. Eu estougoing to kick your ass.}

{141}{sgnt14a}{Soldado, você ainda está fora de uniforme. Eu dei uma ordem direta para informar sobre suprimentos e obter seu problema. Agora, saia do meu rosto e não volte até você se parecer com um soldado!}
{142}{sgnt14b}{Esta é a segunda vez que você veio de mim fora do uniforme, Soldier. Não haverá um terceiro!}
{143}{}{OK! OK! Estou indo.}
{144}{}{Aperte isso. Estou cansado de uma porcaria.}
{145}{}{Sim, sargento! Eu estouon my way.}
{146}{}{Fuck it. Eu estounot cut out for this.}

{147}{sgnt15a}{Trooper, o que você está fazendo aqui? Volte para o seu posto de guarda!}
{148}{sgnt15b}{Idiota. Se eu te vejo longe de sua postagem novamente, será o dia mais engraçado da sua vida curta!}
{149}{sgnt15c}{Você é um perigo para todos nós. Isso vai acabar agora.}

{150}{sgnt16}{Esta base está em alerta e não reconheço você. Mostre-me seus papéis, soldado.}
{151}{}{Não tenho documentos comigo.}
{152}{}{Não tenho documentos necessários!}
{153}{}{Não tenho meus papéis comigo. Eles estão no meu footlocker.}
{154}{}{Papéis? Eu tenho seus papéis aqui!}

{155}{sgnt17}{Resposta errada, larva. Você deve levar seus papéis com você em todos os momentos e você deve saber disso!}
{156}{}{Oops.}

{157}{}{Fique atento, soldado!}
{158}{}{Boa. Você está na bola. Fique assim!}
{159}{}{Nada para denunciar, eu vejo. Fique em sua postagem.}
{160}{}{Se eu pegar qualquer um de você, eu vou ter certeza de que você dorme para sempre!}

{161}{}{Boa! Você encontrou seu local de inaptidão!}
{162}{}{Fique em sua postagem até você ser aliviado, soldado!}
{163}{}{No seu cargo post e acordado. Excelente!}
{164}{}{Mantenha-se acordado, fique atento, fique vivo!}

{165}{}{Alerta! Intrusos na base!}
{166}{}{Guardas! Intrusos!}
{167}{}{Quem diabos deixou esses bastardos? Guardas!}
{168}{}{Alerta! Spies no complexo!}

{169}{}{Onde o inferno é aquele parafuso privado ?!}

{200}{}{.}
{201}{}{, Senhor!}

{300}{}{Eu disse para você não voltar aqui de uniforme!}
