{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em armadura de poder.}
{102}{}{Você vê alguém com uma armadura de poder de um design incomum. Há uma insígnia no peitoral que você não conhece.}

{103}{}{Mova-se.}
{104}{}{Estou de serviço. Não tenho tempo para falar.}
{105}{}{Mantenha-o em movimento. Gate é desse jeito.}

{106}{}{Melhor ir buscar o seu problema.}
{107}{}{Não perambule por fora do uniforme.}
{108}{}{Você está no exército agora. Não fique apanhado de uniforme.}

{109}{}{Intrusos no portão principal!}
{110}{}{Toque o alarme! Intrusos!}
{111}{}{Implante o backup no portão principal. Temos intrusos!}

{112}{}{Alerta de segurança no portão principal!}
{113}{}{Proteja todas as estações! Portão principal sob ataque!}
{114}{}{Código vermelho no portão principal!}

{115}{}{Nós vamos colocá-lo sob!}
{116}{}{O Enclave governará o mundo!}
{117}{}{Você morre para que o Enclave vai sobreviver!}
