{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em armadura de combate.}
{102}{}{Você vê alguém vestindo uma armadura de combate. Há uma insígnia no peitoral com a qual você não conhece.}

{103}{}{Nada a declarar.}
{104}{}{Nada acontecendo comigo, e você?}
{105}{}{Você não deveria estar na sua postagem, soldado? Não é bom vagar por aqui.}

{106}{}{Você está fora de uniforme.}
{107}{}{É melhor informar o Sargento e se adequar.}
{108}{}{Você está tendo uma grande chance de estar fora do uniforme. Você melhor informará para fornecer.}

{109}{}{Quem diabos são vocês ... Alerta! Intrusos!}
{110}{}{Fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Toque o alarme!}

{112}{}{Alerta de segurança! Selar a base!}
{113}{}{Proteja todas as estações! Estamos em alerta}
{114}{}{Alerta de intrusão! Digite o código vermelho!}

{115}{}{Nós vamos colocá-lo sob!}
{116}{}{O Enclave governará o mundo!}
{117}{}{Você morre para que o Enclave vai sobreviver!}
