{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em armadura de poder.}
{102}{}{Você vê alguém com uma armadura de poder de um design incomum. Há uma insígnia no peitoral que você não conhece.}

{103}{}{Nada a declarar.}
{104}{}{Nada acontecendo comigo, e você?}
{105}{}{Você não deveria estar no seu pós-soldado? Não é bom vagar por aqui.}

{106}{}{Você está fora de uniforme.}
{107}{}{É melhor informar o Sargento e se adequar.}
{108}{}{Você está tendo uma grande chance de estar fora de uniforme. Você melhor informará para fornecer.}

{109}{}{Quem diabos vocês são ... Alerta! Intrusos!}
{110}{}{Fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Toque o alarme!}

{112}{}{Alerta de segurança! Selar a base!}
{113}{}{Proteja todas as estações! Estamos alerta}
{114}{}{Alerta de intrusão! Vá código vermelho!}

{115}{}{Nós vamos colocá-lo sob!}
{116}{}{O Enclave governará o mundo!}
{117}{}{Você morre para que o Enclave vai sobreviver!}

{200}{}{...Idiota...}
{201}{}{... sim, você MUDO se afastar ...}
{202}{}{... o que um Brownie Hound ...}
{203}{}{...sim senhor! Fuckin 'senhor! ...}
