{100}{}{Você vê homem de lata brilhante e brilhante.}
{101}{}{Um soldado em armadura de poder.}
{102}{}{Um soldado em algum novo tipo de armadura de poder, você imagina.}

{103}{}{Você acredita nisso? Eu ganhei o dever KP novamente!}
{104}{}{Palavra é que o velho vai dar licença para o SF!}
{105}{}{Para o inferno com a espera. Eu digo que nuke todas essas primitivas e acabar com isso.}
{106}{}{Tem uma luz? Ah, espere, não importa. Tenho um.}
{107}{}{Jogo de Craps por trás do gancho esta noite. Não deixe o CO saber.}

{108}{}{Quem--? <zzzt> Temos um intruso aqui!}
{109}{}{Você aí! Pare!}
{110}{}{Intruder na base!}

{111}{}{Espere-o, não importa.}
{112}{}{Olhe, é melhor obter o seu id. Esses falsos alarmes levaram todo mundo a um salto.}
{113}{}{Você deveria estar aqui, certo? Porra, esses falsos alarmes estão nervosos!}

{114}{}{Intruder está aqui! Pegue-os!}
{115}{}{Há o intruso!}
{116}{}{Por aqui! Não os deixe fugir!}

{117}{}{Temos um ataque na frente. Enviar backup!}
{118}{}{Não deixe o intruso chegar ao portão!}
{119}{}{Morrer, primitivo!}
