{100}{}{Você vê um cyberdog.}
{101}{}{Você vê o K-9.}
{102}{}{Você vê um cyberdog. It is part machine and part dog.}
{103}{}{As funções de vida do meu mestre foram encerradas. Você é meu novo mestre?}
{104}{}{Uh ... doggie talk?}
{105}{}{OK. Eu gosto de cachorrinho.}
{106}{}{Não. Não quero cachorrinho.}
{107}{}{Ha! Um cão falante.}
{108}{}{1; Eu sou um cão. Dois; Estou me comunicando vocalmente usando o comum
 Língua Inglesa. Portanto, é seguro assumir que a resposta à sua pergunta
 é "sim, conversa com cachorro". Agora, você pretende responder a pergunta que eu representei
 você faz um momento?}
{109}{}{1; Eu sou um cão. Dois; Estou me comunicando vocalmente usando o comum
 Língua Inglesa. Portanto, é seguro assumir que eu sou um cão falante. Agora, faça
 você pretende responder a pergunta que eu lhe dei há um momento?}
{110}{}{Desculpe, eu esqueci a pergunta.}
{111}{}{Sim.}
{112}{}{Não.}
{113}{}{(suspiro) Preste atenção. Concentrado. Olhe nos meus olhos. Agora, você está pronto?}
{114}{}{Pronto, o quê?}
{115}{}{Sim. Me ready.}
{116}{}{Eu ... Se não fosse pelo fato de seu QI ter menos
 Eu pensaria que você está tentando me irritar. Agora fique em silêncio. Pagamento
 atenção. Concentrado. Olhe nos meus olhos. Estou prestes a lhe fazer uma pergunta.}
{117}{}{Então vá em frente. Quem te deixa?}
{118}{}{As funções de vida do meu mestre foram encerradas. Você é meu novo mestre?}
{119}{}{Uh ... doggie talk?}
{120}{}{Sim. Me want doggie.}
{121}{}{Não, obrigado.}
{122}{}{Parece bom.}
{123}{}{Não, obrigado.}
{124}{}{Eu ... eu me recuso a passar por isso com você uma segunda vez! Eu estava
 capaz de motivação total Eu o mordi na parte carnuda do seu
 região anterior comumente referida como ...}
{125}{}{Bunda. Eu sei o que é o burro. Eu não sou fofo. Eu apenas brinco com você.}
{126}{}{Oh, uma piada. Hardy Har Har Har Har. Agora, você é meu novo mestre ou não?}
{127}{}{OK. Eu gosto de cachorrinho.}
{128}{}{Não. No want doggie.}
{129}{}{Excelente. Preciso de reparos, mestre. Minha unidade de motivação tem
 foi removido. Encontre, substitua e eu vou me juntar a você.}
{130}{}{Uh ... Onde eu encontro?}
{131}{}{Alguma idéia de onde posso encontrar essa parte?}
{132}{}{Não tenho certeza, mestre. Eu tentaria manutenção. Está no andar de cima no
 canto nordeste da base.}
{133}{}{OK. Eu vou.}
{134}{}{Vou tentar lá. Se eu não encontrá-lo, vou olhar para ele.}
{135}{}{Então me deixe em paz.}
{136}{}{OK.}
{137}{}{Você entendeu.}
{138}{}{Olá de novo. As funções de vida do meu mestre foram encerradas. Estamos
 você é meu novo mestre?}
{139}{}{OK.}
{140}{}{Não.}
{141}{}{Tudo certo.}
{142}{}{Não, obrigado.}
{143}{}{Você não é meu mestre. Eu não posso falar com você. Adeus.}
{144}{}{OK.}
{145}{}{Olá mestre. Você encontrou minha unidade de motivação?}
{146}{}{Não, eu olho mais.}
{147}{}{Sim. Me find.}
{148}{}{Não, ainda estou procurando por isso.}
{149}{}{Chegou aqui.}
{150}{}{Espero aqui para o seu retorno, mestre.}
{151}{}{OK.}
{152}{}{Então, instale a peça, mestre! Por favor, mestre!}
{153}{}{OK. Calm down.}
{154}{}{Parece ser totalmente funcional agora, mestre. Devo me juntar a você?}
{155}{}{Não é aí que isso acontece, mestre. Tem certeza de que sabe o que você
 estão fazendo?}
{156}{}{OK. Doggie come me.}
{157}{}{Eu sei o que fazer! Eu tente novamente.}
{158}{}{Sim, vamos lá.}
{159}{}{Ei, reparei coisas mais complexas do que o seu burro manchado. Estar
 quieto e vou tentar isso de novo.}
{160}{}{Vá embora. Eu não quero você para um mestre.}
{161}{}{Me deixe em paz.}
{162}{}{Eu não gosto de você. Vá embora.}
{163}{}{Eu terminarei você.}
{164}{}{Bloqueando armas no alvo. Prepare-se para se engajar.}
{165}{}{Você será destruído.}

{166}{}{Sim mestre?}
{167}{}{Você cura você mesmo.}
{168}{}{Você espera aqui. Eu voltei e peguei.}
{169}{}{Uh ... coloque a arma de fora. OK?}
{170}{}{Você fica perto.}
{171}{}{Você não se afasta.}
{172}{}{Você também está perto. Espalhar.}
{173}{}{Nós vamos agora.}
{174}{}{Eu terminou.}
{175}{}{Você deve curar-se agora.}
{176}{}{Preciso que você espere até eu voltar.}
{177}{}{Coloque sua arma longe, ok?}
{178}{}{Fica perto de mim.}
{179}{}{Não fique tão longe.}
{180}{}{Devemos nos espalhar um pouco}
{181}{}{Vamos.}
{182}{}{É por enquanto.}
{183}{}{Todos os sistemas estão funcionando a plena capacidade, mestre.}
{184}{}{Meus sistemas estão funcionando em uma capacidade quase total, mestre.}
{185}{}{Eu executei os reparos que posso, mestre, mas eu exigirei
 mais assistência.}
{186}{}{Eu executei os reparos que posso, mestre, mas falha no sistema
 é iminente sem assistência.}
{187}{}{Você espera aqui. Eu voltei e peguei.}
{188}{}{Uh ... coloque a arma de fora. OK?}
{189}{}{Você fica perto.}
{190}{}{Você não se afasta.}
{191}{}{Você também está perto. Espalhar.}
{192}{}{Nós vamos agora.}
{193}{}{Eu terminou.}
{194}{}{Preciso que você espere até eu voltar.}
{195}{}{Coloque sua arma longe.}
{196}{}{Fica perto de mim.}
{197}{}{Não fique tão longe.}
{198}{}{Devemos nos espalhar um pouco}
{199}{}{Vamos.}
{200}{}{É por enquanto.}
{201}{}{Espero aqui para o seu retorno, mestre.}
{202}{}{Você cura você mesmo.}
{203}{}{Uh ... coloque a arma de fora. OK?}
{204}{}{Você fica perto.}
{205}{}{Você não se afasta.}
{206}{}{Você também está perto. Espalhar.}
{207}{}{Nós vamos agora.}
{208}{}{Eu terminou.}
{209}{}{Você deve curar-se agora.}
{210}{}{Coloque sua arma longe.}
{211}{}{Fica perto de mim.}
{212}{}{Não fique tão longe.}
{213}{}{Devemos nos espalhar um pouco.}
{214}{}{Vamos.}
{215}{}{É por enquanto.}
{216}{}{Retirando arma, mestre.}
{217}{}{Você cura você mesmo.}
{218}{}{Você espera aqui. Eu voltei e peguei.}
{219}{}{Você fica perto.}
{220}{}{Você não se afasta.}
{221}{}{Você também está perto. Espalhar.}
{222}{}{Nós vamos agora.}
{223}{}{Eu terminou.}
{224}{}{Você deve curar-se agora.}
{225}{}{Preciso que você espere até eu voltar.}
{226}{}{Fica perto de mim.}
{227}{}{Não fique tão longe.}
{228}{}{Devemos nos espalhar um pouco}
{229}{}{Vamos.}
{230}{}{É por enquanto.}
{231}{}{Estreita distância entre nós, mestre.}
{232}{}{Você cura você mesmo.}
{233}{}{Você espera aqui. Eu voltei e peguei.}
{234}{}{Uh ... coloque a arma de fora. Ok?}
{235}{}{Você não se afasta.}
{236}{}{Você também está perto. Espalhar.}
{237}{}{Nós vamos agora.}
{238}{}{Eu terminou.}
{239}{}{Você deve curar-se agora.}
{240}{}{Preciso que você espere até eu voltar.}
{241}{}{Coloque sua arma longe.}
{242}{}{Não fique tão longe.}
{243}{}{Devemos nos espalhar um pouco.}
{244}{}{Vamos.}
{245}{}{É por enquanto.}
{246}{}{Aumentando a distância entre nós, mestre.}
{247}{}{Você cura você mesmo.}
{248}{}{Você espera aqui. Eu voltei e peguei.}
{249}{}{Uh ... coloque a arma de fora. OK?}
{250}{}{Você fica perto.}
{251}{}{Você também está perto. Espalhar.}
{252}{}{Nós vamos agora.}
{253}{}{Eu terminou.}
{254}{}{Você deve curar-se agora.}
{255}{}{Preciso que você espere até eu voltar.}
{256}{}{Coloque sua arma longe.}
{257}{}{Fica perto de mim.}
{258}{}{Devemos nos espalhar um pouco.}
{259}{}{Vamos.}
{260}{}{É por enquanto.}
{261}{}{Aumentando a distância até o máximo, mestre.}
{262}{}{Você cura você mesmo.}
{263}{}{Você espera aqui. Eu voltei e peguei.}
{264}{}{Uh ... coloque a arma de fora. OK?}
{265}{}{Você fica perto.}
{266}{}{Você não se afasta.}
{267}{}{Nós vamos agora.}
{268}{}{Eu terminou.}
{269}{}{Você deve curar-se agora.}
{270}{}{Preciso que você espere até eu voltar.}
{271}{}{Coloque sua arma longe.}
{272}{}{Fica perto de mim.}
{273}{}{Não fique tão longe.}
{274}{}{Vamos.}
{275}{}{É por enquanto.}
{276}{}{Me desculpe, mestre, mas não parece haver espaço para mim
 sua festa. Vou aguardar até que uma posição seja aberta.}
{277}{}{Como você manda, mestre.}
{278}{}{Você cura você mesmo.}
{279}{}{Você espera aqui. Eu voltei e peguei.}
{280}{}{Uh ... coloque a arma de fora. OK?}
{281}{}{Você fica perto.}
{282}{}{Você não se afasta.}
{283}{}{Você também está perto. Espalhar.}
{284}{}{Eu terminou.}
{285}{}{Você deve curar-se agora.}
{286}{}{Preciso que você espere até eu voltar.}
{287}{}{Coloque sua arma longe.}
{288}{}{Fica perto de mim.}
{289}{}{Não fique tão longe.}
{290}{}{Devemos nos espalhar um pouco.}
{291}{}{É por enquanto.}
{292}{}{Certo. Você parece um cachorro bastante bom.}
{293}{}{Não, obrigado.}

{300}{}{Eu triste. Eu não consigo consertar.}
{301}{}{Me desculpe, eu não posso consertar você.}

{400}{}{Você parece estar perdendo uma parte.}
{410}{}{Isso não faz nada.}
{420}{}{Isso não se encaixa.}

{800}{}{Você fixou o K9.}

{1000}{}{Sim mestre?}

{1100}{}{Todos os sistemas estão funcionando a plena capacidade, mestre.}
{1200}{}{Meus sistemas estão funcionando em uma capacidade quase total, mestre.}
{1300}{}{Eu executei os reparos que posso dominar, mas exigirei
 mais assistência.}
{1400}{}{Eu executei os reparos que posso dominar, mas a falha do sistema
 é iminente sem assistência.}

{1500}{}{Aguardo seu mestre de retorno.}

{1600}{}{Você espera que eu engula meu mestre de dentes?}

{1700}{}{Vou seguir seu mestre no calcanhar.}
{1800}{}{Vou mudar para um mestre de distância média.}
{1900}{}{Vou mudar para o mestre de alcance máximo aceitável.}

{2000}{}{Me desculpe, mestre, mas não parece haver espaço para mim
 sua festa. Vou aguardar até que uma posição seja aberta.}
{2200}{}{Como você manda, mestre.}
{2300}{}{Eu tenho um mestre de peles. Eu não carrego nenhuma outra marcha.}
{2400}{}{Não tenho vontade de remover meu pêlo, mestre.}
{2500}{}{Dentes, mestre. As coisas brancas brilhantes instaladas na minha boca.}

{2700}{}{Você é um asshole maior do que Schreber. Eu não vou me juntar a você.}
{2800}{}{Muito bem mestre. Estou a seu comando.}
{2900}{}{Você é um cretin. Não irei a lugar algum com você. Vá embora.}
