{100}{}{Você vê um mecânico.}
{101}{}{Você vê Kevin, o mecânico.}
{102}{}{Você vê um homem com uniforme militar. A julgar pelos pontos de gordura, você acha que ele é mais de
 um mecânico do que um soldado.}

{200}{}{Não posso falar agora. Vá ver Quincy.}
{201}{}{Quincy é responsável aqui. Vá vê-lo.}
{202}{}{Eu sou apenas um mecânico júnior. Você vai querer falar com Quincy.}

{300}{}{Você está fora de uniforme.}
{301}{}{É melhor se adequar ao soldado.}
{302}{}{Você está tendo uma grande chance de estar fora do uniforme. Você melhor informará para fornecer.}

{400}{}{Quem diabos são vocês ... Alerta! Intrusos!}
{401}{}{Fomos infiltrados! Alerta!}
{402}{}{Múltiplos intrusos! Toque o alarme!}

{500}{}{Merda! Obtenha os backups iniciados.}
{501}{}{Desligue todas as operações classificadas.}
{502}{}{Proteja o sistema e habilite todas as senhas de segurança.}

{600}{}{Eu sou um mecânico, não um lutador!}
{601}{}{O extremo pontilhado com o diodo laser vai para o inimigo. Em seguida, puxe o gatilho.}
{602}{}{Socorro! Socorro! Para manutenção!}
