{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda em armadura de combate.}
{102}{}{Você vê alguém vestindo uma armadura de combate. Há uma insígnia no peitoral
 Que você não conhece.}

{103}{}{Nada a declarar.}
{104}{}{Nada acontecendo comigo, e você?}
{105}{}{Você não deveria estar na sua postagem, soldado? Não é bom vagar por aqui.}

{106}{}{Você está fora de uniforme.}
{107}{}{É melhor informar o Sargento e se adequar.}
{108}{}{Você está tendo uma grande chance de estar fora de uniforme. Você melhor informará para fornecer.}

{109}{}{Quem diabos vocês são ... Alerta! Intrusos!}
{110}{}{Fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Toque o alarme!}

{112}{}{Alerta de segurança! Selar a base!}
{113}{}{Proteja todas as estações! Estamos alerta}
{114}{}{Alerta de intrusão! Vá código vermelho!}

{115}{}{Nós vamos colocá-lo sob!}
{116}{}{O Enclave governará o mundo!}
{117}{}{Você morre para que o Enclave vai sobreviver!}

{118}{}{Desculpe, soldado. Essa área está fora dos limites para o pessoal da base. Tenho que lhe perguntar
 deixar.}
{119}{}{Doc quer que eu mate D'garra. Ele não quer fazer ele mesmo.}
{120}{}{Ok, eu vou.}
{121}{}{Doc quer que mate o bicho por ele. Ele não quer fazer isso mesmo.}

{122}{}{Eu sabia que o bastardo não teria as bolas para fazer isso sozinho. Oh não, está tudo bem
 Se um de nós fodido. (Suspiro) Oh, bem. Continue e boa sorte, soldado.}
{123}{}{Obrigado.}

{124}{}{Por que você está me olhando assim, soldado?}
{125}{}{Eu ouço você chamar Snookie. Que fofo.}
{126}{}{Eu ouvi você se chamar Snookie. Eu acho que isso é fofo.}

{127}{}{O que ... Ele lhe disse isso? Quando eu sair de serviço eu vou chutar sua bunda ...
 Mova-se, soldado. E limpe o sorriso da sua cara!}
{128}{}{OK.}
