{100}{}{Você vê uma tecnologia.}
{101}{}{Você vê uma tecnologia de computador.}
{102}{}{Você vê alguém vestindo um bata de laboratório completo com um protetor de bolso e um cacho de canetas.}

{103}{}{Bom dia soldado.}
{104}{}{Por favor, não toque nada.}
{105}{}{Vocês grunhidos não devem estar aqui.}

{106}{}{Você está fora de uniforme.}
{107}{}{É melhor você se adequar. Armory está no corredor do lado esquerdo.}
{108}{}{Você está tendo uma grande chance de estar fora do uniforme. Você melhor informará para fornecer.}

{109}{}{Quem diabos são vocês ... Alerta! Intrusos!}
{110}{}{Fomos infiltrados! Alerta!}
{111}{}{Múltiplos intrusos! Toque o alarme!}

{112}{}{Merda! Obtenha os backups iniciados.}
{113}{}{Desligue todas as operações classificadas.}
{114}{}{Proteja o sistema e habilite todas as senhas de segurança.}

{115}{}{Eu sou um cientista, não um lutador!}
{116}{}{O extremo pontilhado com o diodo laser vai para o inimigo. Em seguida, puxe o gatilho.}
{117}{}{Socorro! Socorro! Ao laboratório de informática!}
