{100}{}{Você vê uma tecnologia.}
{101}{}{Você vê um técnico do Enclave.}
{102}{}{Você vê alguém usando um bata de laboratório. Ele parece confiante e seguro de si mesmo.}

{103}{}{Sim soldado?}
{104}{}{Qual é esse lugar?}
{105}{}{Eu apenas disse oi. Eu vou agora.}
{106}{}{O que é este lugar?}
{107}{}{Só dizendo Oi. Até mais.}

{108}{}{Esta é a sala de computadores. Esse é o mainframe por aí, o terminal da interface está ao lado dele e esses dispositivos são as unidades de armazenamento de dados holotape. Este é o mais recente e o melhor.}
{109}{}{Oh. Uh, o que você faz?}
{110}{}{Então, o que você faz aqui?}

{111}{}{Eu sou o analista sênior de informática. Eu consigo manter todo o equipamento aqui.}
{112}{}{Oh. Eu uso o computador?}
{113}{}{Eu não entendo. Eu vou.}
{114}{}{Diga, posso usar o sistema por um minuto? Você sabe, confira?}
{115}{}{Ei, ótima conversa com você. Vejo você mais tarde.}

{116}{}{Bem ... Eu não deveria permitir que ninguém além de pessoal treinado use o equipamento. É tudo bastante complexo e delicado que você entende.}
{117}{}{Por favor? Eu não tenho descanso.}
{118}{}{Eu prometo não quebrá-lo}

{119}{}{Tudo certo. Você pode acessar o sistema a partir do terminal lá. Apenas tenha cuidado, por favor. Eles dispararão nos dois se danificarem essa máquina. Ah, a senha do convidado é 'Snookie'.}
{120}{}{Desculpe, mas está fora de questão. Eu nem sequer eu deveria permitir que o pessoal alistado na sala permitia que eles usassem o equipamento.}
{121}{}{Snookie? O que é snookie?}
{122}{}{Está bem. Eu entendi.}
{123}{}{Snookie? O que diabos é um snookie?}
{124}{}{Tudo certo. Compreendo.}

{125}{}{'Snookie' é o apelido da minha namorada. Eu acho que é fofo. Essa é a sua saída no salão, por sinal. Ela é uma das guardas.}
{126}{}{Ok, tudo bem. Obrigado.}
{127}{}{Sim ... Bonito. Obrigado.}

{128}{}{Você está fora de uniforme.}
{129}{}{É melhor você se adequar. Armory está no corredor do lado esquerdo.}
{130}{}{Você está tendo uma grande chance de estar fora do uniforme. Você melhor informará para fornecer.}

{131}{}{Quem diabos são vocês ... Alerta! Intrusos!}
{132}{}{Fomos infiltrados! Alerta!}
{133}{}{Múltiplos intrusos! Toque o alarme!}

{134}{}{Merda! Obtenha os backups iniciados.}
{135}{}{Desligue todas as operações classificadas.}
{136}{}{Proteja o sistema e habilite todas as senhas de segurança.}

{137}{}{Eu sou um cientista, não um lutador!}
{138}{}{O extremo pontilhado com o diodo laser vai para o inimigo. Em seguida, puxe o gatilho.}
{139}{}{Socorro! Socorro! Ao laboratório de informática!}
