{100}{}{Você vê alguém em armadura de poder.}
{101}{}{Você vê o intendente.}
{102}{}{Você vê alguém com uma armadura de poder de um design incomum.
 Há uma insígnia no peitoral que você não conhece.}

{103}{}{Quem diabos vocês são ... Alerta! Intrusos na base!}
{104}{}{O que ... Eu posso ver por que você está aqui. Você obviamente quer
 Para se livrar desse terno antiquado que você está vestindo.}
{105}{}{Por que você está fora do uniforme, soldado?}
{106}{}{Morrer!}
{107}{}{Uh, sim ...}
{108}{}{Uh ...}
{109}{}{Eu novo aqui.}
{110}{}{Eu não sou um soldado!}
{111}{}{Uh, bem ...}
{112}{}{Eu sou novo aqui.}
{113}{}{Eu não sou um dos seus soldados!}

{114}{}{Uh, o que? Não consigo pensar em uma boa desculpa? Estou esperando, soldado!}
{115}{}{Ainda não tenho uniforme.}
{116}{}{Ainda não tenho um uniforme.}

{117}{}{Você é um pouco do lado lento, não é? (Suspiro) Bem, isso é
 não é sua culpa. Eu tenho um irmão como você. De qualquer forma, você é novo aqui?
 Não lembro de te ver antes.}
{118}{}{Você é novo aqui? Não lembro de te ver antes.}
{119}{}{Sim! Eu novo aqui!}
{120}{}{Yes, Eu sou novo aqui.}

{121}{}{Bem, você precisará do seu problema padrão, então. Ir para a armadura,
 Prepare-se e pegue sua arma. Você deve informar o sargento de perfuração
 depois.}
{122}{}{Obrigado!}

{123}{}{Seja bem-vindo. Agora sai daqui. Tenho trabalho a fazer e eu
 Não quer ser perturbado.}

{124}{}{Agora estou ocupado. Volte mais tarde.}

{125}{}{Olá, recrute. Acabei de receber uma chamada do seu sargento. Ele diz
 Eu devo te acompanhar e mandar de volta para ele. Este direito?}
{126}{}{Sim.}

{127}{}{Esta base está em alerta e não reconheço você. Me mostre seu
 Papéis, soldado.}
{128}{}{Não tenho documentos comigo.}
{129}{}{Não preciso de papéis de necessidade!}
{130}{}{Não tenho meus papéis comigo. Eles estão no meu footlocker.}
{131}{}{Papéis? Eu tenho seus papéis aqui!}

{132}{}{Resposta errada. Você deve levar seus papéis com você em todos os momentos
 E você deve saber disso!}
{133}{}{Oops.}
