{100}{}{Você vê um homem com uniforme militar.}
{101}{}{Você vê Quincy o mecânico.}
{102}{}{Você vê um homem com uniforme militar. Judging by the grease spots you think
 he is more of a mechanic than a soldier.}

{103}{}{Nome Quincy, soldado. Por que você está batendo no meu ombro e está perdido?}
{104}{}{Eu preciso pedir uma coisa.}
{105}{}{Nada.}
{106}{}{Oi. Eu preciso te perguntar uma coisa.}
{107}{}{Deixa pra lá.}

{108}{}{Tudo bem, mas faça isso rápido. Tenho inventário para fazer.}
{109}{}{O que você precisa saber?}
{110}{}{Qual é esse lugar?}
{111}{}{Eu procuro planos de vertibird. Onde encontrar?}
{112}{}{Eu disse por mim que eu encontre planos de vertibird aqui.}
{113}{}{Eu vou agora.}
{114}{}{O que é este lugar?}
{115}{}{Estou à procura de planos vertibird. Você sabe onde eu posso encontrá-los?}
{116}{}{Foi-me dito por uma tecnologia que eu poderia encontrar os planos de vertibird aqui.}
{117}{}{Bem, tenho que ir.}

{118}{}{Isso é manutenção. Reparamos praticamente qualquer coisa, exceto para os vertibirds.}
{119}{}{Onde o vertibird é reparado?}
{120}{}{Onde os vertibirds são reparados?}

{121}{}{Eles apenas se encaixam no hangar ou ao ar livre. Você descobriu a partir daí, ok?}
{122}{}{Oh ... tudo bem.}
{123}{}{Oh sim. Entendi.}

{124}{}{Bem ... eu tenho uma cópia dos planos, mas não posso apenas entregá-los para
 qualquer pessoa que os solicite. O que você quer com eles?}
{125}{}{Eu tenho amigos no sul que querem.}
{126}{}{Uh ... bem ...}
{127}{}{Tenho alguns amigos no sul que querem colocar as mãos sobre eles}
{128}{}{Fui informado pelo Sargento para obtê-los.}

{129}{}{No sul ... Sra merda! Nós temos um espião aqui! Guardas! Alerta!}
{130}{}{Ooops.}
{131}{}{Ooops. Coloque meu pé nessa vez.}

{132}{}{Você está a uma curta distância de um clipe completo, não é? Bem, eles te chamam
 grunhidos por um motivo. Olha, Einstein, não posso te dar os planos sem
 autorização, está bem? Então, volte para quem o enviou aqui e obtenha o bom
 papelada.}
{133}{}{Olha, Einstein, não posso te dar planos sem autorização, está bem?
 Então, volte para quem o enviou aqui e pegue a documentação adequada.}
{134}{}{Ok, eu vou.}
{135}{}{Não, eu tiro você primeiro, encontre planos em segundo lugar, então ... o que vem depois de dois?}
{136}{}{Ei, você entendeu.}
{137}{}{Não, acho que vou atirar em você em vez disso e olhar para os planos enquanto
 você sangra.}

{138}{}{Um técnico disse a você ... Você quer dizer Raul? Ele enviou você?}
{139}{}{Uh, sim.}
{140}{}{Uh, não.}
{141}{}{Sim, esse é o cara.}
{142}{}{Não, acho que não foi Raul.}

{143}{}{Droga! Você sabe, Raul perderia a cabeça se não fosse colocado tão
 firmemente na sua bunda! Esta é a terceira vez que ele perdeu aqueles
 planos! E agora ele nem sequer tem as bolas de saltear de bronze para vir até mim
 e pedir por eles? Tudo bem, eles estão no armário lá. Ah, e quando você
 entregue-os, conte esse idiota que eu quero vê-lo.}
{144}{}{Obrigado.}

{145}{}{Então você está de volta. Você obteve a autorização?}
{146}{}{Você novamente? O que é agora?}
{147}{}{Sim, eu tenho um rifle de plasma. Que bom o suficiente para mim!}
{148}{}{Não, ainda não.}
{149}{}{Sim, tenho uma grande arma. Isso é bom o suficiente para mim!}
{150}{}{Não, ainda não.}
{151}{}{Eu te pergunto uma coisa.}
{152}{}{Eu apenas digo 'Oi'.}
{153}{}{Eu preciso te perguntar uma coisa.}
{154}{}{Nada, apenas dizendo 'Oi'.}

{155}{}{Você é louco? Andando aqui fora de uniforme? Seja adequado!}
{156}{}{Se o sargento te tirar do uniforme, ele vai te entregar seu traseiro.}
{157}{}{Por que você está fora de uniforme?}

{158}{}{Merda! Estamos sendo invadidos! Alerta!}
{159}{}{Intrusos! Ligue para o guarda!}
{160}{}{Guarda! Intrusos de manutenção!}

{161}{}{Estás bem? Estamos sob ataque?}
{162}{}{Por que o alerta? O que está acontecendo?}
{163}{}{O que está acontecendo?}

{164}{}{Ei! Não esqueça essas gavetas.}
{165}{}{Eu disse para você não passar por minhas coisas! Guardas!}
{200}{}{Sim. Bem, não acredite em tudo o que você ouve.}
{201}{}{Quem te contou isso? Porque ele é o próximo depois que eu toque um pouco de senso em você.}
{300}{}{Você não vê que estou ocupada?}
{301}{}{Ei! Não esqueça essas gavetas!}
{302}{}{Eu disse para você não passar por minhas coisas! Guardas!}
