{100}{}{Você vê um mecânico.}
{101}{}{Você vê Raul, o mecânico.}
{102}{}{Você vê um homem com um uniforme militar imundo. A julgar pela graxa
 Pontos que você acha que ele é mais mecânico do que um soldado e que trabalha duro
 Um para inicializar.}

{103}{}{Desculpe, cara, mas não tenho tempo para chit-chat, você sabe? Eu tenho que obter
 Este pássaro funciona.}
{104}{}{Doc quer resolver o K-9. Ele diz que você fez parte.}
{105}{}{Uh ... ok.}
{106}{}{Uh, Quincy quer vê-lo. Ele me pede que lhe diga.}
{107}{}{O doc quer consertar seu cachorro. Ele me enviou para a parte.}
{108}{}{Bem. Tchau.}
{109}{}{Raul, Quincy quer vê-lo.}

{110}{}{Quincy, né? Bem, Raul não quer vê-lo, cara. Raul está cansado de
 Sua merda, você sabe?}
{111}{}{OK.}
{112}{}{Quincy diz que você está bravo. Você não recebeu bolas para vê-lo.}
{113}{}{Bem.}
{114}{}{Quincy disse que você era um idiota e que não teria
 As bolas para denunciá-lo.}

{115}{}{ Ei cara, Raul não tira nada de ninguém. Você vê Quincy trabalhando nesses
 Pássaros De jeito nenhum, cara. Somente Raul trabalha com esses bebês. Você sabe porque? Causa
 Quincy não conhece DICK, cara, por isso!}
{116}{}{Uh ...}
{117}{}{Bem...}

{118}{}{Ei, desculpa, cara. Raul não deveria estar gritando com você, você sabe? Está
 não é sua culpa; Você é apenas o mensageiro. Ei, cara, você está ocupado agora?}
{119}{}{Não, eu não estou ocupado. Por quê?}
{120}{}{Na verdade, por quê?}

{121}{}{Olhe, cara. Raul vai pagar uma visita a Quincy, você sabe?
 Raul vai limpar o relógio do velho homem.
 Você fica aqui e assiste os pássaros de Raul. Ok?}
{122}{}{Eu assisto.}
{123}{}{Certifique-se de Raul. Eu vou fazer isso por você, mas não por ninguém.}

{124}{}{Ei, obrigado, cara. Raul deve-lhe um!
 Não vá embora e, hey, cara, se alguém
 Parafusos com os pássaros de Raul, você os atira na bunda. Ok?}
{125}{}{OK.}

{126}{}{Ei cara, o que você acha que está fazendo? Afaste-se daquele pássaro,
 homem! Raul tem problemas suficientes sem você grunhir fodendo com as coisas, você
 conhecer? Malditos pilotos são ruins o suficiente!}
{127}{}{Eh, cara, Raul disse-lhe que ficasse longe de seus pássaros, cara.
 Agora, Raul deve ensinar você a ouvir. Vamos lá, cara. Tira a merda
 Armadura e vá um a um, mano e mano com Raul.}
{128}{}{Não, eu não penso assim.}
{129}{}{Toque você, Raul. Eu atirar-lhe ass morto!}
{130}{}{Não, obrigado, você é muito difícil para mim, amigo.}
{131}{}{Por que usar punhos quando tenho uma arma perfeitamente boa?}

{132}{}{Então não foda com os pássaros de Raul, cara! Saia daqui!}
{133}{}{OK.}

{134}{}{Raul acha que você deve ficar louco caminhando por aqui fora do uniforme.}
{135}{}{Ei, cara, se o sargento te tirar do uniforme, ele vai entregar
 Você é seu traseiro.}
{136}{}{Por que você está fora do uniforme, cara?}

{137}{}{Merda! Estamos sendo invadidos! Alerta!}
{138}{}{Intrusos! Chame o guarda!}
{139}{}{Guarda! Intrusos no hangar!}

{140}{}{E aí, cara? Estamos sob ataque?}
{141}{}{Por que o alerta, cara? O que está acontecendo?}
{142}{}{O que está acontecendo?}

{143}{}{Raul vai colocá-lo no laboratório de medicina, cara.}
{144}{}{Ei, cara, diga suas orações!}
{145}{}{Raul vai chutar sua bunda!}

{146}{}{Ei, cara, está no armário lá. Pegue e diga ao doc
 Raul diz oi.}
{147}{}{Obrigado.}

{150}{}{E aí cara! Raul não gosta quando as pessoas se mexem com sua merda. Saia, cara.}
{151}{}{Raul disse que você não passasse por suas coisas! Guardas!}
{200}{}{Raul ouviu falar que estava falando sobre ele de novo.}
{201}{}{Isso aconteceu uma vez com freqüência, asshole. Raul vai te ferir mal desta vez.}
{300}{}{Você não vê que Raul está ocupado?}
