{100}{}{Um soldado em uniforme de serviço.}
{101}{}{Alguns Pfc-Tech, grau X.}
{102}{}{Ele está usando um uniforme militar, mas é claro que esse cara é mais um técnico do que um soldado.}

{103}{}{Olha, quantas vezes eu tenho que te contar papai? Não perca o caminho!}
{104}{}{Você não tem algo para atirar?}
{105}{}{Saudações, soldado.}

{106}{}{Quem é Você? Guardas!}
{107}{}{O que diabos é isso? Infiltrador na base!}
{108}{}{Merda! Onde está minha arma!}

{109}{}{Olhem, eles já pesquisaram aqui e eles não encontraram nada.}
{110}{}{Jeez, esses falsos alarmes me deixam nervoso como o inferno.}
{111}{}{Ótimo, outro falso alarme. Agora, teremos que arrancar todo o sistema e colocá-lo de volta
 juntos novamente.}

{112}{}{Maldita seja! Por aqui! Obter o espião!}
{113}{}{Merda! É um ataque! Onde está minha peça?}
{114}{}{Tiroteio? Ninguém disse que haveria tiroteio!}

{115}{}{Quem diabos é você? Guardas!}
{116}{}{Você não é Enclave! Guardas!}
{117}{}{Infiltradores! Sabotadores! Por aqui!}

{118}{}{Ei, não mexa nos planos. Estou trabalhando aqui.}
{119}{}{Onde diabos é essa parte do gyrovator?}
{120}{}{Damn fly-boys, sempre quebrando minhas máquinas.}

{121}{}{Roger, nós conseguimos você no escopo - não me incomode, estou trabalhando.}
{122}{}{Olhe, não são permitidas chamadas pessoais, soldado.}
{123}{}{Desculpe, não posso ajudá-lo agora.}

{124}{}{Você tem negócios aqui em baixo? Caso contrário, fora do meu caminho.}
{125}{}{Esta é uma área restrita, soldado.}
{126}{}{Saia do meu caminho, soldado.}

{127}{}{Que diabos? O que está acontecendo lá em cima?}
{128}{}{Merda! Eles quebraram!}
{129}{}{Esses palhaços! Provavelmente é apenas mais um falso alarme.}
