{100}{}{Você vê uma tecnologia.}
{101}{}{Você vê um técnico do Enclave.}
{102}{}{Você vê alguém usando um bata de laboratório com um protetor de bolso e muitas canetas cheias. Ele tem aquele olhar um tanto confuso de alguém novo para um trabalho.}

{103}{}{Sim senhor?}
{104}{}{Eu novo aqui. Precisa perguntar.}
{105}{}{Eu apenas disse oi. Eu vou agora.}
{106}{}{Eu sou novo aqui. Preciso fazer algumas perguntas para me familiarizar com a base.}
{107}{}{Desculpe incomodá-lo. Apenas estou dizendo oi.}

{108}{}{Sou um novo recruta, senhor. Não sei se posso responder todas as suas perguntas, mas vou tentar.}
{109}{}{Com o que posso ajudar?}
{110}{}{Qual é esse lugar?}
{111}{}{O que você trabalha?}
{112}{}{Onde Enclave base principal em.}
{113}{}{Eu procuro planos de vertibird. Onde eu encontro?}
{117}{}{Eu vou embora agora.}
{118}{}{O que é este lugar?}
{119}{}{Qual é o seu trabalho aqui?}
{120}{}{Onde está a base principal Enclave localizada?}
{121}{}{Preciso examinar os planos do vertibird. Onde eles são mantidos?}
{125}{}{Nada. Eu tenho que ir.}

{126}{}{Este é o centro de comunicação. Nós lidamos com todas as comunicações com a base principal a partir daqui.}
{127}{}{Eu vejo. Eu peço mais.}
{128}{}{Tudo certo. Mais algumas perguntas.}

{129}{}{Eu sou um técnico de centro de comunicação, de segunda classe. Eu lido todas as comunicações com a base principal e mantenho o status do equipamento.}
{130}{}{Uh ... sim.}
{131}{}{Boa. Mantenha o bom trabalho.}

{132}{}{Você deve estar brincando, certo?}
{133}{}{Nenhum garoto. Onde a base?}
{134}{}{Parece que estou brincando?}

{135}{}{A base principal está localizada na costa do Pacífico, perto da cidade de São Francisco. Posso perguntar por que você está perguntando?}
{136}{}{Não. Razão militar. Quantas maneiras chegar à base?}
{137}{}{Não. Este é um assunto militar. Agora, quantas maneiras você conhece para alcançar a base?}

{138}{}{Bem ... há os vertibirds, mas isso é bastante óbvio. Depois, há o petroleiro em San Fran. Além disso, acho que você teria que nadar.}
{139}{}{Obrigado.}
{140}{}{Obrigado.}

{141}{}{Estariam localizados em manutenção, ao lado do controle de tráfego aéreo.}
{142}{}{OK.}
{143}{}{Consegui.}

{153}{}{Você está louco, andando aqui sem uniforme? Seja adequado!}
{154}{}{Se o sargento te tirar do uniforme, ele vai te entregar seu traseiro.}
{155}{}{Por que você está fora de uniforme?}

{156}{}{Merda! Estamos sendo invadidos! Alerta!}
{157}{}{Intrusos! Ligue para o guarda!}
{158}{}{Guarda! Intrusos no centro de comunicação!}

{159}{}{Estás bem? Estamos sob ataque?}
{160}{}{Por que o alerta? O que está acontecendo?}
{161}{}{O que está acontecendo?}

{162}{}{Eu sou apenas um técnico, não me atira!}
{163}{}{Eu não me inscrevi para o combate, apenas treinamento de tecnologia!}
{164}{}{Este é um bata de laboratório, não uma armadura! Estou fora daqui!}
