{100}{}{Você vê uma tecnologia.}
{101}{}{Você vê um técnico do Enclave.}
{102}{}{Você vê alguém usando um bata de laboratório. Ele parece confiante e seguro de si mesmo.}

{103}{}{Sim senhor?}
{104}{}{Eu novo aqui. Precisa perguntar.}
{105}{}{Eu apenas disse oi. Eu vou agora.}
{106}{}{Eu sou novo aqui e estou tentando me familiarizar com a base. Posso fazer-te algumas perguntas?}
{107}{}{Só dizendo Oi. Até mais.}

{108}{}{Certamente, soldado.}
{109}{}{Com o que posso ajudar?}
{110}{}{Qual é esse lugar?}
{111}{}{O que você trabalha?}
{112}{}{Onde a base principal Enclave?}
{113}{}{Eu procuro planos de vertibird. Onde eu encontro?}
{117}{}{Eu vou embora agora.}
{118}{}{O que é este lugar?}
{119}{}{Qual é o seu trabalho aqui?}
{120}{}{Onde está a base principal Enclave localizada?}
{121}{}{Preciso examinar os planos do vertibird. Onde eles são mantidos?}
{125}{}{Nada. Eu tenho que ir.}

{126}{}{Este é o centro de comunicação. A partir daqui, lidar com todas as comunicações com a base principal e quaisquer outros postos avançados que foram estabelecidos.}
{127}{}{Eu vejo. Eu peço mais.}
{128}{}{Tudo certo. Mais algumas perguntas.}

{129}{}{Eu sou um técnico de centro de comunicação, de primeira classe. Eu executo tarefas de supervisão. Principalmente eu me certifico de que os outros técnicos não estragarem.}
{130}{}{Uh ... sim.}
{131}{}{Boa. Mantenha o bom trabalho.}

{132}{}{Soldier, essa informação está em uma "necessidade de saber", apenas uma base. Se você tiver que fazer a pergunta, então você não precisa saber.}
{133}{}{OK.}
{134}{}{Vamos, não é como se eu fosse um maldito tribal ou algo assim. Estamos na mesma roupa; Observe as insígnias na armadura?}
{135}{}{Compreendo.}

{136}{}{Sim senhor. A base principal está localizada na costa do Pacífico, perto da cidade de São Francisco. Posso perguntar por que você está perguntando, senhor?}
{137}{}{Soldier, eu disse-lhe que a informação está em uma "necessidade de saber", apenas uma base.}
{138}{}{Por motivos de segurança, estou verificando o nível de conscientização da informação entre o pessoal da base. Agora, me diga todas as maneiras que você conhece pessoalmente para chegar à base principal.}
{139}{}{Compreendo.}

{140}{}{Sim senhor. Primeiro, os vertibirds são o principal método usado para alcançar a base principal. Devido à complexidade de sua operação, é duvidoso que os subversivos possam comandar um vertibird. Em segundo lugar, existe um petroleiro de combustível operacional no porto de São Francisco. O navio, no entanto, foi desativado e uma senha é necessária para reiniciá-lo. O comandante da base possui a senha na sua posse. Em terceiro lugar, com o equipamento adequado, você poderia nadar para base principal, mas a probabilidade de sobrevivência é próxima a zero.}
{141}{}{Obrigado.}
{142}{}{Obrigado.}

{143}{}{Estariam localizados em manutenção, ao lado do controle de tráfego aéreo.}
{144}{}{OK.}
{145}{}{Consegui.}

{155}{}{Você está louco, andando aqui sem uniforme? Seja adequado!}
{156}{}{Se o sargento te tirar do uniforme, ele vai te entregar seu traseiro.}
{157}{}{Por que você está fora de uniforme?}

{158}{}{Merda! Estamos sendo invadidos! Alerta!}
{159}{}{Intrusos! Ligue para o guarda!}
{160}{}{Guarda! Intrusos no centro de comunicação!}

{161}{}{Estás bem? Estamos sob ataque?}
{162}{}{Por que o alerta? O que está acontecendo?}
{163}{}{O que está acontecendo?}

{164}{}{Eu sou apenas um técnico, não me atira!}
{165}{}{Eu não me inscrevi para o combate, apenas treinamento de tecnologia!}
{166}{}{Este é um bata de laboratório, não uma armadura! Estou fora daqui!}
