{100}{}{Saudações, humanas. Eu sou o guerreiro Xarn. Você é meu executor?}
{101}{}{Sim.}
{102}{}{Não, eu aqui o resgata.}
{103}{}{Não sei. Eu quero saber por que você está aqui.}
{104}{}{Sim eu estou.}
{105}{}{Não, estou aqui para te resgatar.}
{106}{}{Eu não sei. Gostaria de saber por que você está aqui.}

{107}{}{Que assim seja. Não pretendo ir em silêncio, humano. Vamos fazer isso um
 Batalha para lembrar!}
{108}{}{OK.}
{109}{}{Esperar. Eu mudo a mente. Por quê você está aqui?}
{110}{}{Estou pronto. Vamos festejar.}
{111}{}{Espere um minuto. Por quê você está aqui?}

{112}{}{Eu acho difícil acreditar que um soldado Enclave esteja aqui para me resgatar.
 Mais provável, você está aqui para construir minhas esperanças para que você possa derrubá-las.}
{113}{}{Não. Eu aqui o resgata. Mesmo.}
{114}{}{Olha, estou realmente aqui para te resgatar!}

{115}{}{Você é minha última esperança, então eu farei minha confiança em você. que
 A porta por aí conduz a um arraial que sai no bosque acima.
 Eu deveria poder escalar o eixo e ganhar minha liberdade. Contudo,
 A porta está bloqueada de forma segura e requer uma senha para abrir.
 Encontre a chave, desbloqueie a porta e conceda-me a minha liberdade.}
{116}{}{Ok, eu sim.}
{117}{}{Eu penso nisso.}
{118}{}{Claro, vou fazer isso.}
{119}{}{Vou pensar sobre isso.}

{120}{}{(Xarn olha fixamente para você por um momento) Muito bem.
 O Enclave criou meu povo como uma raça guerreira escrava. Eles
 Aumentou o nosso intelecto na esperança de que pudéssemos entender melhor os seus
 Comandos, e ainda não reconhecem nosso status como escravos.
 Eles falharam; Somos muito mais inteligentes do que eles suspeitam.}
{121}{}{Nós decidimos jogar o tolo até conseguirmos
 liberdade. Nossa chance chegou quando o Enclave decidiu testar
 Nós fora do seu controle, aqui no continente. Doutor Schreber
 Opuseram-se a sua decisão, mas ele foi anulado.}
{122}{}{Não aceitando a decisão Enclave, ele escolheu o exílio para esta base,
 Me capturou e vem realizando experimentos para determinar meu
 verdadeira natureza. Ele foi bem sucedido. Quando ele relata suas descobertas
 Para o Enclave, meu povo será caçado e morto. Eu devo
 Escape e avise meu povo.}
{123}{}{(Xarn olha para você atentamente por um momento) Não tenho nada
 Para dizer-lhe, humano. Eu posso sentir a escuridão de sua alma.}
{124}{}{Se doutor ameaça por que você não mata?}
{125}{}{Toque você então. Eu tiro você burro.}
{126}{}{Se esse cara é uma ameaça, então, por que você não o matou?}
{127}{}{Até o seu, então. Morre, deathclaw.}

{128}{}{(Suspiro) Recentemente eu comecei a considerar apenas tal ação,
 Mesmo que não seja minha maneira de matar. Estou certo de que o médico
 Percebi porque ele parou de me ver pessoalmente. A escolha é
 Não é mais o meu para fazer.}
{129}{}{Você não se preocupa. Médico morto. Ele não fez um relatório.}
{130}{}{Eu obrigado pela história.}
{131}{}{Você não precisa se preocupar. O doc está morto e ele
 Não fez o relatório.}
{132}{}{Obrigado pela história. Foi interessante.}

{133}{}{Lamento ouvir sobre sua morte, mas é para a
 Melhor que isso seja assim. Eu pediria que você me ajudasse a escapar
 Esse lugar. Você poderia?}
{134}{}{Sim, eu sim.}
{135}{}{Eu penso nisso.}
{136}{}{Não, eu não penso assim.}
{137}{}{Sim, vou fazer isso.}
{138}{}{No, but Vou pensar sobre isso.}
{139}{}{Não, acho que não.}

{140}{}{Muito bem ... Vou esperar até chegar a uma decisão.}
{141}{}{Feito.}

{142}{}{Muito bem ... Estou triste com a sua decisão, mas é
 sua escolha. Se você mudar de idéia, eu estarei aqui.}
{143}{}{Tchau.}
{144}{}{Adeus.}

{145}{}{Eu pediria que você me ajudasse a escapar desse lugar. Você poderia?}
{146}{}{Sim, eu sim.}
{147}{}{Eu penso nisso.}
{148}{}{Não, eu não penso assim.}
{149}{}{Sim, vou fazer isso.}
{150}{}{No, but Vou pensar sobre isso.}
{151}{}{Não, acho que não.}

{152}{}{Olá de novo. Você está pronto para a nossa batalha?}
{153}{}{Não quero lutar, quero ouvir sua história.}
{154}{}{Eu não quero lutar. Eu aqui o resgate.}
{155}{}{Não. Eu vou.}
{156}{}{Sim. Me ready.}
{157}{}{Eu realmente não quero lutar. Posso ouvir a sua história em vez disso?}
{158}{}{Estou aqui para te resgatar, não lutar.}
{159}{}{Não. Vou sair agora.}
{160}{}{Tudo bem, vamos acabar com isso.}

{161}{}{Olá de novo. Você mudou de idéia? Você vai me ajudar?}
{162}{}{Sim.}
{163}{}{Não.}

{164}{}{Olá de novo. Você mudou de idéia? Você vai me ajudar?}
{165}{}{Sim.}
{166}{}{Não. Me still think about it.}
{167}{}{Não. Me not help.}
{168}{}{Não, ainda estou pensando.}
{169}{}{Eu não quero ajudá-lo.}

{170}{}{Olá de novo. Você encontrou a chave para a porta?}
{171}{}{Sim, eu estou aberto para você.}
{172}{}{Eu ainda olho.}
{173}{}{Sim, entendi. Vou abrir a porta para você.}
{174}{}{Ainda estou olhando.}

{175}{}{Obrigado. Não vou esquecer isso.}
{176}{}{Bem vindo.}
{177}{}{Você é bem vindo.}

{178}{}{Obrigado novamente, meu amigo. Eu devo uma dívida que não pode ser reembolsada.}

{179}{}{Saudações, humanas. A base está em alerta completo. Você é, por acaso, a causa?}
{180}{}{Olá de novo. A base está em alerta completo. Você é a causa?}
{181}{}{Sim, eu causo. Quem você, por que você quer saber?}
{182}{}{Sim, eu causo. Por quê?}

{183}{}{Eu sou Xarn, guerreiro do bloco. Permita-me juntar-se a você e lutar ao seu lado por nossa liberdade. Juntos, temos uma chance; Sozinho ... quem sabe?}
{184}{}{Em seguida, permita-me juntar-se a você e lutar ao seu lado. Juntos
 Podemos conseguir nossa liberdade; Sozinho ... quem sabe?}
{185}{}{Antes de mim decidir você diz por que você está aqui?}
{186}{}{Uh ... ok. Você vem comigo. Nós lutamos juntos.}
{187}{}{Você está sozinho. Eu fora daqui.}
{188}{}{Antes de chegar a qualquer decisão, gostaria de saber por que você está aqui?}
{189}{}{Bem. Estamos juntos nisso. Carregue suas garras e fale para baixo!}
{190}{}{Você está no seu amigo. Estou fora daqui.}

{191}{}{Uh ... ok. Você vem comigo. Nós lutamos juntos.}
{192}{}{Você está sozinho. Eu fora daqui.}
{193}{}{Bem. Estamos juntos nisso. Carregue suas garras e fale para baixo!}
{194}{}{Você está no seu amigo. Estou fora daqui.}

{195}{}{Agradeço-lhe, humano. Deixe-nos chutar alguns Enclave ass! Pack Gruthar! Grrrrrrrhh!}
{196}{}{OK.}

{200}{}{[Mais]}
{201}{}{Sim. Who are you?}
{202}{}{Sim. Why?}
{300}{}{Muito bem. O Enclave criou meu povo como uma raça guerreira escrava.
 Eles aumentaram o nosso intelecto na esperança de que pudéssemos entender melhor os seus
 Comandos, e ainda não reconhecem nosso status como escravos. Eles falharam; estamos
 Muito mais inteligentes do que eles suspeitam.}
{301}{}{Nós decidimos jogar o tolo até conseguirmos nossa liberdade. Nosso
 Chegou a chance quando o Enclave decidiu nos testar fora de seu controle, aqui
 No continente. O doutor Schreber opôs a sua decisão, mas ele foi anulado.}
{302}{}{Não aceitando a decisão Enclave, ele escolheu o exílio para esta base, capturou
 Eu, e tenho realizado experimentos para determinar minha verdadeira natureza. Ele tem
 Foi bem sucedido. Quando ele relata suas descobertas ao Enclave, meu povo será
 Caçado e morto. Devo escapar e alertar meu povo.}

{500}{}{Você é um verdadeiro irmão Pack. Podemos nos encontrar novamente em tempos mais pacíficos.
 Devo ir agora para preparar meu povo para a guerra.}
{501}{}{Eu vou arrancar seus membros e vencê-lo com eles.}
{502}{}{Morra, humano traiçoeiro!}
{503}{}{Isso vai te machucar muito mais do que eu.}

{600}{}{Juntos vamos esmagar nossos inimigos.}
{601}{}{Você os alinha e eu vou derrubá-los.}
{602}{}{Tempo para algum ataque de cabeça grave.}

{700}{}{Você vê uma morte. Observa você com olhos estranhamente inteligentes.}
{701}{}{Você vê Xarn, o deathclaw.}
{702}{}{Você vê uma morte típica. A criatura é enorme, com um corpo poderoso, dentes afiados e garras longas.}

{800}{}{Você matou Xarn.}
{810}{}{Você liberou Xarn.}
{820}{}{Você se juntou ao Xarn.}
