# Player uses a skill on the door
# Unlock Door
{170}{}{Você escolhe habilmente o bloqueio no armário.}
{171}{}{Sua falta de habilidade bloqueou o bloqueio neste armário.}
{172}{}{Você não consegue escolher o bloqueio neste armário.}

# Unlock Door
{173}{}{ Escolhe habilmente o bloqueio no armário.}
{174}{}{A falta de habilidade bloqueou o bloqueio neste armário.}
{175}{}{ Não conseguiu escolher o bloqueio neste armário.}

# Player uses an item on the door
{176}{}{Você roubou a fechadura da porta.}
{177}{}{Você pressiona suas costas enquanto tenta abafar o bloqueio e
 tomar um ponto de dano.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] pontos de dano.

{178}{}{Você pressiona suas costas enquanto tenta abafar o bloqueio e
 levar}
{179}{}{ pontos de dano.}
{180}{}{Você é muito fraco para destruir o bloqueio.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ Bifurca a fechadura da porta.}
{182}{}{ Estica as costas enquanto tenta abater a fechadura e leva
 um ponto de dano.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ Estica as costas enquanto tenta abater a fechadura e leva}
{184}{}{ pontos de dano.}

{185}{}{ é muito fraco para destruir o bloqueio.}
{186}{}{ Estica as costas enquanto tenta abater a fechadura e leva
 um ponto de dano.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ afasta-se de suas costas enquanto tenta abater a fechadura e leva}
{188}{}{ pontos de dano.}

# Lock Door
{189}{}{Você bloqueia habilmente o armário.}
{190}{}{Você não bloqueia o armário.}

# Lock Door
{191}{}{ bloqueia habilmente o armário.}
{192}{}{ falhou ao bloqueio do armário.}

{203}{}{O armário parece estar bloqueado.}

{800}{}{Você recuperou o fob.}
{810}{}{Você recuperou os planos.}
{820}{}{Você recuperou o motivador do K-9.}
