# 0. Look
{100}{}{Você vê um dependente.}
{101}{}{Esta pessoa é fortemente combatada.}
{102}{}{Parece que ele está cheio de chems.}
{103}{}{Parece que ela está cheia de chems.}
{104}{}{Ele parece muito ruim. Você suspeita que é retirada de algum tipo de chem.}
{105}{}{Ela viu dias melhores. Parece que ela está passando por retirada.}
{106}{}{Este dependente se parece com os mortos-vivos.}
{107}{}{Você acha que esse dependente apenas vomitou.}

# 1. CF: Attacked by PC
{150}{}{As luzes estão me machucando!}
{151}{}{Monstros em todos os lugares!}
{152}{}{Isso se sentiu estranho.}
{153}{}{Estou sangrando?}
{154}{}{Normalmente não parece isso real.}
{155}{}{Pare com isso, cara!}
{156}{}{Ninguém me ajudará?}
{157}{}{Socorro!}
{158}{}{Cai fora!}
{159}{}{Minha cabeça dói o suficiente como está!}
{160}{}{Me deixe em paz.}

# 2. CF: Normal
{200}{}{Uau, você tem um estranho brilho escuro.}
{201}{}{Meu, você é um cachorro grande.}
{202}{}{Não diga a eles o que sabemos que não existe.}
{203}{}{Ahhh…}
{204}{}{Você consegue me ver?}
{205}{}{Seja vewy, vewy quiet. Estou a caçar Wabbits.}
{206}{}{Como você conseguiu chegar aqui?}
{207}{}{Shhh, eu estou escondendo.}
{208}{}{Estou correndo mais rápido do que um lobo!}
{209}{}{Eu me sinto tão vivo!}
{210}{}{Está percorrendo minhas veias ...}
{211}{}{Bem lá, querida.}
{212}{}{Oooohhh, você pode sentir o poder?}
{213}{}{Uau, você está brilhando ...}
{214}{}{Eu te amo Cara!}
{215}{}{A vida tem sido tão boa para mim. Foi bom para você?}
{216}{}{Os pequeninos voam de noite.}
{217}{}{Diga olá para meu pequeno amigo.}
{218}{}{Menino, estou com sono ...}
{219}{}{Você viu meu cachorro?}
{220}{}{Shhh, estão logo atrás de você ...}
{221}{}{Meu!}
{222}{}{Oooh, minha cabeça.}
{223}{}{Eu sofro por toda parte.}
{224}{}{Estou começando a pegar os shakes.}
{225}{}{Oh, eu preciso de mais um pouco.}
{226}{}{Preciso de uma correção.}
{227}{}{Eu não posso esperar, eu preciso disso agora.}
{228}{}{Você pega minha merda?}
{229}{}{Ah, deixe-me em paz.}
{230}{}{Eu consegui as batidas ruins, cara.}
{231}{}{Eu odeio esta parte.}
{232}{}{Eu só quero morrer.}
{233}{}{Preciso de algo mais ruim.}
{234}{}{Não aguento mais isso.}
{235}{}{Eu acho que estou com febre.}
{236}{}{Eu acho que vou vomitar.}
{237}{}{Talvez se eu durmirei ...}
{238}{}{Eu consegui as batidas ruins, senhora.}

# 3. BGF: Hostile
{300}{}{Isso é sangue?}
{301}{}{Uau! Estou vendo? Não consigo sentir nada!}
{302}{}{Tingles.}
{303}{}{Quem fez isso?}
{304}{}{O que está acontecendo?}
{305}{}{Estou sangrando ... eu acho.}
{306}{}{Oh, a dor.}
{307}{}{Agora eu realmente preciso de uma correção.}
{308}{}{Apenas me deixe morrer.}

# 4. BGF: Normal
{350}{}{Ahhhh ...}
{351}{}{Estou flutuando ...}
{352}{}{Eu tenho o poder!}
{353}{}{Olá, Sr. Flor.}
{354}{}{Todas as cores ...}
{355}{}{Um amigo mais longo vê esse céu?}
{356}{}{Eles não estão ouvindo ...}
{357}{}{Onde estou?}
{358}{}{Aí está!}
{359}{}{Whoa, não! Pare! Esperar! Okay, vá em frente.}
{360}{}{Lá, ai ... ahh ...}
{361}{}{Sim, querida!}
{362}{}{O que é que foi isso?}
{363}{}{Sasha? Onde está você Sasha?}
{364}{}{As cores estão desaparecendo!}
{365}{}{Mamãe?}
{366}{}{Ei! Saia de perto de mim! Ah ...}
{367}{}{Você não faz isso!}
{368}{}{Não consigo ver ... novamente.}
{369}{}{Necessidade…}
{370}{}{Pegue mais…}
{371}{}{Lá? Não.}
{372}{}{Não. Não é possível encontrá-lo.}
{373}{}{Faça parar!}
{374}{}{Ug.}
{375}{}{Oh, a dor.}
{376}{}{<tosse> <tosse> <tosse>}
{377}{}{Ooh, minha cabeça!}
{378}{}{Onde eu coloquei meu esconderijo?}

# 5. Self Initiated: Attacking Player
{400}{}{Um demônio!}
{401}{}{O inimigo está sobre nós!}
{402}{}{Você assassino! Você matou pelo filho!}
{403}{}{Um monstro! Mate isso!}
{404}{}{Ah! Pargasraka!}
{405}{}{Pés do rato do queixo estão indo! Ahhh!}
{406}{}{Você não vai tirar isso de mim!}
{407}{}{Devolva!}
{408}{}{Não!!!}
{409}{}{Minha família!}
