{100}{}{Você vê um fantasma!}
{101}{}{Você vê Anna o fantasma.}

{150}{}{É um fantasma. Isso não é algo que você vê todos os dias.}
{151}{}{Ela parece bastante atormentada.}
{152}{}{[CONVERSA]}
{153}{}{Oh, a dor! Isso queima!}
{154}{}{Qual é o problema?}
{155}{}{Quem é Você?}
{156}{}{Begone, espírito sujo!}
{157}{}{Paro e toco em todas as portas, mas ninguém vem, ninguém ouve.}
{158}{}{I can hear you. Qual é o problema?}
{159}{}{Eu acho que você precisa desligar seu Stealth Boy, senhora.}
{160}{}{Cadê? Eu não consigo achar! Eu estou perdido! Ah ...}
{161}{}{O que você está procurando? Talvez eu possa ajudar.}
{162}{}{Você realmente precisa parar de gemer e gemer e começar a fazer sentido.}
{163}{}{Meu medalhão! Já se foi. Ladrao! Ladrao!}
{164}{}{Whoa, acabei de chegar aqui. Eu não fiz isso.}
{165}{}{Posso ajudá-lo a encontrá-lo?}
{166}{}{Ah, destino cruel.}
{167}{}{Você não pode me ouvir, você pode?}
{168}{}{Mais tarde, garota fantasma.}
{169}{}{Tchau. Vou tentar ajudar.}
{170}{}{Meu medalhão! Me dê isto!!! Oh !!!!}
{171}{}{De jeito nenhum! Vá para o inferno. Achei isso justo e quadrado.}
{172}{}{ESTÁ BEM. Aqui está.}
{173}{}{Aqui. Que você descanse em paz.}
{174}{}{ESTÁ BEM.}
{175}{}{Não.}
{176}{}{Meu medalhão, meu medalhão! Eu vou, papai! Estou chegando!}
{177}{}{Adeus.}
{178}{}{Esperar! Não vá!}
{179}{}{Entre na luz.}

{200}{}{Onde poderia ser?}
{201}{}{Ohhh.}
{202}{}{Mamãe? Papai? Onde está você?}
{203}{}{Não consigo encontrá-lo!}

{500}{}{Mamãe ... Papai ... Eu vou ...}
{501}{}{É tão brilhante ...}
{502}{}{Grammy, posso te ver ...}
{503}{}{Oh, é o tipo Mr. Cain. É bom ver você novamente...}

{550}{}{Esta casa é clara.}

{560}{}{GOTO BUSH!}
{561}{}{Ug.}
