{100}{}{Você vê um homem curto com bigode grosso.}
{101}{}{Você vê os Grandes Ananias.}
{102}{}{Você vê um homem curto, mustachioed, com um olhar um pouco furtivo para ele.}
{103}{}{Você! O que você quer fazer com o Ananias agora?}
{104}{}{Saia de perto de mim!}
{105}{}{Vai arruinar o negócio de outra pessoa.}
{106}{}{Retire-o de outra pessoa.}
{107}{}{Você já fez o seu pior para mim.}
{108}{}{Apenas vá embora, você me causou bastante mal.}
{109}{}{Estou com tanta fome.}
{110}{}{Como vou alimentar minha família agora?}
{111}{}{Você nasceu com 12 tamanhos de coração muito pequenos.}
{112}{}{Não, meu amigo, uma MUMMY! Direto das areias do antigo Egito para as areias dos Resíduos! Exclusivamente para você ver!}
{113}{}{OK, eu vou morder. Quanto ver o cadáver wizened?}
{114}{}{(Você mesmo) Hmm, uma múmia descreveria a forma como um ghoul parece. Ok, eu gostaria de dar uma olhada - quanto?}
{115}{}{Já vi cadáveres suficientes. Adeus.}
{116}{}{Olá, bem-vindo, saudações! Eu sou o Grande Ananias (ele oferece um leve arco, com um floreio). Eu trago mistérios de amigos próximos e distantes. Mistérios de um mundo além do nosso ... do Netherworld.}
{117}{}{Volte para aprender sobre os mistérios dos Ananias do Netherworld que você tem?}
{118}{}{Que tipo de mistérios?}
{119}{}{Bom, conheço o senhor Great Anus ... algo.}
{120}{}{Hmm, os mistérios me fazem dormir com dificuldade, é melhor ir. Adeus.}
{121}{}{Passa para a direita!}

{127}{}{Hoje, no quarto dentro, eu tenho, para os seus olhos exclusivamente ... Uma mamãe egípcia Jan-u-wine!}
{128}{}{Uma múmia?}
{129}{}{Uma múmia? Hmm, I wonder if it could be.... No, nobody could be that stupid.}
{130}{}{Não tenho interesse nesse tipo de coisa. Os cadáveres me assustam.}
{131}{}{Fora do caminho, você está bloqueando os clientes pagantes.}
{132}{}{Eu não acho que isso seja para você.}
{133}{}{Por que você não leva seu pequeno ser tribal em outro lugar.}
{134}{}{Isso não é realmente para você.}
{135}{}{Eu vejo, hmmm, que tal GO (ele aponta) AFASTADO!}
{136}{}{Para uma pessoa da sua óbvia classe, ficaria feliz em mostrar este exemplar único e histórico para você por apenas US $ 25.}
{137}{}{OK, vou tossir a massa. Agora ... Mostre-me a Múmia!}
{138}{}{Não quero gastar tanto. Eu acho que vou sobreviver sem ver o assunto. Adeus.}
{139}{}{Basta abrir a tampa do sarcófago e a maravilhosa Múmia será revelada, em toda sua antiga glória, para você. Mas por favor, sem tocar, e, uh, sem fotografia flash.}
{140}{}{Ótimo.}
{141}{}{Ai está! A mamãe! (A porta do sarcófago se abre para revelar um cadáver dessecado, que se parece muito com um ghoul comum, parado em um sarcófago de papel mal pintado, estilhaçado e quebrado).}
{142}{}{Ai está! Apresentando, o MUMMY! (Uma porta de cripta se abre para revelar uma múmia egípcia de jan-u-wine em um sarcófago aberto que parece ter sido feita de ouro puro!)}
{143}{}{Ei, espere um minuto. Isso não é uma Múmia. Isso é um ghoul. WOODY! Ei, WOODY! Isso é você?}
{144}{}{Isso parece um ghoul para mim.}
{145}{}{Isso é uma múmia? Eu não posso acreditar que eu apenas paguei $ 25 para ver um pedaço de seis pés de pedaços. Adeus.}
{146}{}{Uau, isso é fantástico ... acho. (Você olha a Múmia muito atentamente por um tempo). Uh, obrigado, adeus.}
{147}{}{(A Múmia, ressoa, se estende lánguidamente e depois olha para você com um piscar de sono em seus olhos) Olá. (Diz ele, com sono)}
{148}{}{Merda! Que * é * Woody! Corra Woody, corre por isso! Bem, uh, gimp para isso, então! Vá lá Woody!}
{149}{}{Eu asseguro-lhe que a Múmia é, de fato, bastante vinho de janeiro.}
{150}{}{Eu não acho que eu acreditei em você. Deixe-me tentar algo. WOODY! Ei, WOODY! Isso é você?}
{151}{}{Bem, se você diz. Mas eu certamente acho que parece um ghoul comum. Adeus.}
{152}{}{(Woody - pois é, de fato, Woody, não uma múmia, que fica um pouco arrepiante antes de você - agarra os lados do
 papel-
Mache sarcófago, solta um grito e corre para a porta, deixando uma trilha de papel higiênico "embrulhos de múmia"
 E um acelerado "Thankee gentilmente, estranho!" atrás dele.)}
{153}{}{Hah! Eu sabia! Você terminou nesta cidade. Você não é o Great Ananias mais, você é apenas mais um burro.}
{154}{}{Vá lá Woody! Ahah! Eu sabia!}
{155}{}{(O Grande Ananias encolhe os ombros) Eu sabia que deveria ter pegado aquele brahmin mono-cabeça em vez disso. Ah, bem, de volta ao quadro de desenho.}
{156}{}{Brahmin mono-cabeça? Claro, quem jamais acreditaria nisso! Adeus, você Charlatan.}
{157}{}{Você acordou Woody, o ghoul, e libertou-o da múmia fingida.}
{158}{}{Eu acho que ouviria a história dos fantasmas.}

{200}{}{Eu sei coisas que o mero homem mortal não deve ser conhecido. Aiiieeee! Nyarloth ... Oh, desculpe (heh, heh). Ficou um pouco levado
 Por um momento. Tenho histórias de um fantasma que assombra esses motivos, bem como um vinho de Jan-u-Egypt-ee-an Mummy que você
 Pode ver, aqui mesmo, neste maravilhoso sarcófago.}
{201}{}{Conte-me sobre a múmia. Estou morrendo de vontade de ouvir mais sobre isso.}
{202}{}{Acabei de ouvir essa história de fantasmas. Uh, eu recebo uma boa xícara quente de cacau para ir com isso?}
{203}{}{Eu não acho que tenho mais tempo para desperdiçar o que quer que seja que você esteja falando.}

{300}{}{Bem, você vê, (ele movimenta você mais perto) havia uma vez uma ótima rainha que governou toda a cidade vizinha. Ela a manteve
 Trono em virtude de um amuleto especial que ela manteve ao redor de seu pescoço em todos os momentos. Grandes coisas, hein?}
{301}{}{Uh, sim. Pode apostar. Então, essa princesa teve um amuleto * mágico *. Oh, continue. Eu simplesmente não suporto esse nível de suspense
 Muito mais longo (bocejo).}
{302}{}{ESTÁ BEM. Eu acho que já ouvi sobre o suficiente. Adeus.}

{400}{}{Bem, vou cortar a perseguição então. Então, o mago maligno envenenou a jovem princesa e pegou seu amuleto. Ela está vagando
 Em todo o lado da sala, desde então. Bem, uh, isto é, apenas na hora das bruxas, de qualquer maneira. É por isso que mantenho a porta trancada.
 Muito ruim assustador, hein?}
{401}{}{O fantasma de uma princesa amuleto na sala destroçada ao lado? É isso aí? Eu não posso acreditar que você está pedindo * que * como uma história.
 Eu preferiria ouvir sobre essa mamãe estúpida que você deveria ter aqui.}
{402}{}{ESTÁ BEM. Eu acho que já ouvi sobre o suficiente. Adeus.}
