# 8. BF: Hostile Primitive
{245}{}{Quieto! Eles estão perto.}
{246}{}{Mate homens maus.}
{247}{}{Não tire minha família de mim.}
{248}{}{Eu protejo a família.}
{249}{}{Não nos encontra.}
{250}{}{Eles são pessoas ruins.}

# 9. BF: Hostile Nomad
{260}{}{Esbarradores estão chegando. Todos estão quietos.}
{261}{}{Prepare-se. Eu acho que eles estão perto agora.}
{262}{}{Não vou sair sem uma briga.}
{263}{}{Eles nunca nos escravizarão.}
{264}{}{Aqueles escravos pagarão por isso.}
{265}{}{Nenhum escravo vai levar minha família.}
# looks
# primitive
{100}{}{Este homem parece bastante forte e alerta.}
{101}{}{Ela parece forte apesar do tamanho dela.}

# nomads
{200}{}{Ele parece estar muito magro, mas com raiva.}
{201}{}{Este parece bastante forte.}
{202}{}{Ele se move com grande velocidade.}

{210}{}{Ela não parece ter se banhado.}
{211}{}{Ela parece um lutador forte.}
{212}{}{Este não parece ser um grande problema.}

# 12. Combat Float: Hostile Primitive
{300}{}{Você morre agora!}
{301}{}{Eu mato!}
{302}{}{Você não machuca a família!}
{303}{}{Você não leva família!}
{304}{}{Eu protejo!}
{305}{}{Eu magoei-te!}
{306}{}{Você paga!}
{307}{}{Morrer!}
{308}{}{Eu vou te machucar.}

# 13. Combat Float: Hostile Nomad
{350}{}{Você não vai levar minha família, escravidão!}
{351}{}{Morra, escorrendo escória!}
{352}{}{Você pagará, seu bastardo!}
{353}{}{Lutaremos até a morte da minha família!}
{354}{}{Você não vai sair com isso!}
{355}{}{Você não vai sair com meus amigos!}
{356}{}{Eu vou buscá-lo para isso!}
{357}{}{Malditos escravos!}
{358}{}{Você pagará por isso!}
