{100}{}{Você vê um patrono do Hole.}

{150}{}{Esse colega não é muito atraente.}
{151}{}{Esse cara só recebeu um dente.}
{152}{}{[CONVERSA]}
{153}{}{Sua esposa com certeza é bonita!}
{154}{}{Afaste-se de nós.}
{155}{}{Você gosta dela, hein?}
{156}{}{Sim ela é.}
{157}{}{Sim.}
{158}{}{Eu certamente gostaria de fazê-la.}
{159}{}{Vá em frente.}
{160}{}{ESTÁ BEM. Isso será $ 50.}
{161}{}{Claro, mas isso custará US $ 200.}
{162}{}{De jeito nenhum! Afaste-se de nós!}
{163}{}{ESTÁ BEM.}
{164}{}{Não.}
{165}{}{Bem! Agora venha com Billy, docinho.}
{166}{}{Agora vá embora.}
{167}{}{Obrigado. Tchau.}
{168}{}{Tchau.}
{169}{}{Aw, shucks.}
{170}{}{[feito]}
{171}{}{Estou cheio de plumas.}
{172}{}{Eu voltarei.}
{173}{}{ESTÁ BEM.}
{174}{}{Você é certo é uma coisa bonita.}
{175}{}{Saia de perto de mim.}
{176}{}{Me dê $ 200 e você pode passar algum tempo comigo.}
{177}{}{Eu custa US $ 50, Mac.}
{178}{}{Hee hee. Obrigado.}
{179}{}{Não tenho dinheiro suficiente.}
{180}{}{Ok, US $ 50 então.}
{181}{}{Muito ruim para você.}
{182}{}{Até a próxima.}
{183}{}{Não me incomode. Eu estou procurando por pintinhos bonitos.}
{184}{}{Boa sorte. Você vai precisar disso.}
{185}{}{O que sou eu, fígado picado?}
{186}{}{Tchau.}
{187}{}{Oooh. ESTÁ BEM. Tchau.}
{188}{}{[looks you up and down] Não. I like chopped liver.}
{189}{}{Eu não preciso disso de você!}
{190}{}{Com licença, tenho que ir.}
{191}{}{Que pena. Eu pensei que você era fofo.}


{203}{}{Eu quero meu dinheiro de volta.}
{204}{}{Eu não estou lhe dando nada além de um buraco na cabeça.}
{205}{}{Ok, aqui está você.}
{225}{}{Eu não tenho isso.}

{206}{}{Ei.}
# Oh, venha, dê(player_name) Outra chance aqui.
{207}{}{Oh, venha, dê}
{208}{}{ Outra chance aqui.}
{209}{}{Eu posso ver que você não quer falar comigo. Estou indo embora.}

{210}{}{Eu dei sua chance e você explodiu.}
{211}{}{OK, mas apenas mais uma chance.}
{212}{}{Esse é o meu filho.}
{213}{}{Eu só vou ter que te matar, então.}

{220}{}{Ei, Frankie, só vou emprestar o quarto das costas por um momento.}
{221}{}{Ei, Frankie, veja o que eu segurei.}
{222}{}{Uh, Frankie, se alguém estiver ... uh ... procurando por mim, estarei de volta.}

{223}{}{Me siga.}
{224}{}{Vai ter que esperar. Eu falarei com você mais tarde.}


# 10.
{300}{}{Porra, estou fodido de forma plana.}
{301}{}{Wahoo.}
{302}{}{Isso foi ... foi ... WOW !!!}
{303}{}{Você poderia incendiar sua bunda.}
{304}{}{Porra que separou meu cabelo - bem, o que eu tenho.}
{305}{}{Certo, bate um rolo com Dave.}

# 11.
{320}{}{Nada mal nada mal...}
{321}{}{Eu talvez pague por isso novamente.}
{322}{}{Mmmm ...}
{323}{}{Nada mal nada mal.}
{324}{}{Teremos que fazer isso novamente e trabalhar com a nossa ... flexibilidade.}

# 12.
{350}{}{Parece que vou ficar acessível novamente.}
{351}{}{Não deixe a porta atingir o seu DRY ASS no caminho certo!}
{352}{}{Tempo para terminar o que você não poderia começar!}

# 13.
{370}{}{Oh, isso é legal.}
{371}{}{Billy gosta disso.}
{372}{}{Ohhhh sim.}
{373}{}{Agradável.}
{374}{}{Jeezus e ramona.}
{375}{}{Bom Gracioso.}
{376}{}{Eu deveria colocar uma caixa de tecido.}
{377}{}{Hmmm, quem deveria imaginar agora.}

# 14.
{390}{}{Ei, você não vê que estou ocupado aqui?}
{391}{}{Ei, ei, saia do trato.}
{392}{}{Ei, você não conseguiu terminar o trabalho, então saia.}
{393}{}{Você pode me pegar uma esfregona e voltar em 5?}

{400}{}{Billy, é melhor você não ter feito uma bagunça nesse colchão novamente!}
{401}{}{Hey Billy, você precisa de um esfregão?}
{402}{}{Billy, sua mosca está para baixo. NOVAMENTE!}
{403}{}{Yo Billy, não se esqueça de mudar suas calças mais tarde.}
{404}{}{Billy, você estava comendo donuts?}

{410}{}{Uhhh.}
{411}{}{Shucks}
{412}{}{Jeesh}
{413}{}{Ele, ele, ei ...}
{414}{}{Hã?}

{500}{}{* SPIT, SPIT * Eccchhhh ...}

{510}{}{Ei, amigo, se preocupa em "alugar" esse bom seu?}
{511}{}{Não pode esperar isso? Tenho que tomar uma bebida.}
{512}{}{Sim, se você quiser falar comigo, eu estarei no The Hole.}
{513}{}{Que tal você me conhece no The Hole e eu compro uma bebida?}

{520}{}{Desculpe, tenho pressa em chegar em casa. Acabei de receber uma pornografia nova.}
{523}{}{Estou cansada, por favor, deixe-me ir para casa e uhhh, durma ...}
{522}{}{Estou indo para Dave's. Ele tem uma asa de pornografia inteira!}

{530}{}{Uhhh, não, obrigado. Eu não tenho dinheiro para irritar isso novamente.}

{540}{}{Tudo bem, vou dar uma volta à sua culpa novamente.}
