{100}{}{Você vê um membro do Slaver's Guild.}

{150}{}{Você vê Metzger, chefe do Slaver's Guild.}
{151}{}{[CONVERSA]}
{152}{}{Guardas! Ataque!}
{153}{}{[feito]}
{154}{}{Volte da manhã, droga! Eu faço o meu negócio durante o dia.}
{155}{}{[feito]}
{156}{}{O que é agora? Você está realmente começando a me irritar.}
{157}{}{Eu gostaria de me desculpar.}
{158}{}{Desculpe, fui chocado anteriormente. Não quis dizer nada.}
{159}{}{Whoa, qual é o seu problema?}
{160}{}{Queria lhe fazer uma pergunta.}
{161}{}{Aparentemente, eu tenho. Adeus.}
{162}{}{Wah.}
{163}{}{Bem, é tarde demais para isso. Saia.}
{164}{}{Por favor por favor por favor; Eu sinto Muito.}
{165}{}{Bem, eu tentei.}
{166}{}{Toque você, então!}
{167}{}{Tudo bem, tudo bem. Desculpas aceitas.}
{168}{}{Whew. Posso fazer-te algumas perguntas?}
{169}{}{Fico feliz por ter resolvido isso. Até logo.}
{170}{}{Olá. É bom te ver.}
{171}{}{Oi Metzger. Nós precisamos conversar.}
{172}{}{Você também. Tchau.}
{173}{}{Blurp.}
{174}{}{Eu sou Metzger, chefe do Slaver's Guild. O que você precisa?}
{175}{}{Sim, tenho algumas perguntas.}
{176}{}{Não, obrigado. Eu vou agora agora.}
{177}{}{Swavuh ???}
{178}{}{Por favor saia. Agora.}
{179}{}{Ou o que?}
{180}{}{Bem. Mas voltarei!}
{181}{}{ESTÁ BEM. Tchau.}
{182}{}{O que você gostaria de saber?}
{183}{}{Sobre Trader Vic ...}
{184}{}{Posso me juntar ao Slaver's Guild?}
{185}{}{Gostaria de vender meu marido à escravidão.}
{186}{}{Gostaria de vender minha esposa. Quantos?}
{187}{}{Gostaria de vender um dos meus amigos aqui.}
{188}{}{Conte-me sobre a aliança.}
{189}{}{Que cidades compram seus escravos?}
{190}{}{Eu gostaria de comprar um escravo.}
{191}{}{Estou à procura de Vault 13. Você já ouviu falar sobre isso?}
{192}{}{Metzger? Esse é um nome estranho.}
{193}{}{Nada. Eu tenho que ir.}
{195}{}{É de uma língua antiga, pré-guerra ou algo assim.}
{196}{}{Metzger significa açougueiro. Ajustando, você não acha?}
{197}{}{Esse era o nome do meu bisavô. Ele pode de algum lugar longe para
 o leste. Através de um grande corpo de água.}
{198}{}{Eu li algum livro sobre um Metzger. Ele era um presidente, ou algo assim.}
{199}{}{Olha quem está falando trible.}
{200}{}{Germen, alemão, Garmen, ou algo assim. Linguagem antiga, de um
 Há muito tempo.}
{201}{}{Et tu, Brutus?}
{202}{}{Entendo. Ainda tenho uma pergunta.}
{203}{}{Essa é a coisa mais estúpida que já ouvi.}
{204}{}{Fascinante. Tenho que ir.}
{205}{}{Nossa missão é proporcionar uma força de trabalho estável e de alta qualidade para
 Lidar com as crescentes demandas das grandes cidades. Você gostaria de participar?}
{206}{}{Certo. Parece bom.}
{207}{}{De jeito nenhum.}
{208}{}{I’ll get back to you on that. Que cidades compram seus escravos?}
{209}{}{Desculpe, essa é a informação privada da aliança.}
{210}{}{ESTÁ BEM. Assine-me!}
{211}{}{Não! Vocês são pessoas doentes!}
{212}{}{Eu considerarei isso. Tenho mais perguntas.}
{213}{}{Hmm, voltarei mais tarde.}
{214}{}{Precisamos marcar uma marca pequena em sua testa para mostrar a todos
 Sua fidelidade à guilda dos eslavos. Você está pronto?}
{215}{}{Parece bom! Faça!}
{216}{}{Eu mudei de ideia. Posso fazer outra pergunta?}
{217}{}{Não tenho tempo agora. Eu tenho que ir.}
{218}{}{Bem-vindo à guilda!}
{219}{}{Ótimo, eu tenho dúvidas!}
{220}{}{Ok, obrigado. Eu voltarei.}
{221}{}{Vault 13? Não. Aguarde ... acho que é Vic's da Vault City. Talvez seja isso.}
{222}{}{Sim, onde está?}
{223}{}{Não. Ainda tenho outra questão.}
{224}{}{Não, não importa.}
{225}{}{Nós vendemos a maioria de nossos escravos para Vault City e New Reno. New Reno é
 Sudeste daqui e a maioria dos negócios de den com ele.}
{226}{}{Onde está a Cidade do Vault?}
{227}{}{Tenho mais perguntas.}
{228}{}{Obrigado, tenho que ir.}
{229}{}{Vault City fica a leste daqui e um pouco a sul. Vic é a partir daí.}
{230}{}{Tenho mais perguntas.}
{231}{}{Obrigado; tenho que ir.}
# Hmm, parece um escravo saudável. Eu te darei[x] moedas.
{232}{}{Hmm, parece um escravo saudável. Eu te darei}
{233}{}{ moedas.}
{234}{}{ESTÁ BEM! É um acordo.}
{235}{}{Uh, não importa.}
{236}{}{De jeito nenhum! Quero o dobro!}
{237}{}{Você faz uma barganha difícil. Aqui está o seu dinheiro!}
{238}{}{Obrigado. Eu tenho mais algumas perguntas.}
{239}{}{Obrigado. Tchau.}
{240}{}{Algo mais?}
{241}{}{Sim, tenho uma pergunta.}
{242}{}{Não. Tchau.}
{243}{}{Qual "amigo" você está vendendo?}
{244}{}{Hum, não importa.}
# Interessante. Eu te darei[x] moedas.
{245}{}{Interessante. Eu te darei}
{246}{}{ moedas.}
{247}{}{Vendido!}
{248}{}{Não, obrigado.}
{249}{}{Eu quero mais dinheiro do que isso!}
# Tudo bem, eu vou te dar[x] mas não mais!
{250}{}{Tudo bem, eu vou te dar}
{251}{}{ mas não mais!}
{252}{}{Vendido!}
{253}{}{Não esta bom o suficiente.}
{254}{}{Isso é muito pequeno. Estou indo embora.}
{255}{}{O que você quer com Vic? Ele é minha propriedade agora. Ele não deveria ter fodido comigo.}
{256}{}{Eu gostaria de comprá-lo.}
{257}{}{Por que você está mantendo ele aqui?}
{258}{}{Nada. Deixa pra lá.}
{259}{}{Ele ainda não está à venda.}
{260}{}{Por que não?}
{261}{}{Oh, está bem.}
{262}{}{Ele custará US $ 2000.}
{263}{}{Aqui está o seu dinheiro.}
{264}{}{Isso é muito. Talvez mais tarde.}
{265}{}{O custo é de US $ 1000.}
{266}{}{Aqui está o seu dinheiro.}
{267}{}{Ainda não tenho muito. Tchau.}
{268}{}{Nosso rádio está quebrado e ele está encarregado de corrigi-lo.}
{269}{}{Entendo.}
{270}{}{Você não conseguiu o dinheiro!}
{271}{}{Muito ruim para mim. Posso te fazer uma pergunta?}
{272}{}{Desculpe, voltarei.}
{307}{}{How dare you return after abandoning your brothers during a Slave Run! Guardas! Ataque!}
{308}{}{[feito]}
{309}{}{Excelente! Pode levar alguns dias para você viajar para lá e voltar. Você está pronto para sair agora?}
{310}{}{Não. Vou voltar.}
{311}{}{Sim estou pronto. Vamos.}
{312}{}{Ah, você está de volta da escravidão. Vamos ver como você fez ...}
{313}{}{[Mais]}
{314}{}{[Mais]}
{315}{}{Você matou potenciais escravos! Um homem morto não nos traz renda! Apenas mate os que são uma ameaça,
 Os outros não são de ameaça.}
{316}{}{[Mais]}
{317}{}{Você não devolve nenhum escravo! Que diabos está errado com você? Estamos tentando ganhar dinheiro aqui,
 Não o perca.}
{318}{}{[Mais]}
{319}{}{No geral, você fez bem esta corrida. Mantenha o bom trabalho e eu posso mantê-lo em torno de um tempo.}
{320}{}{Obrigado. Eu vou.}
{321}{}{Não sei se gosto muito disso.}
{322}{}{Você precisa melhorar sua técnica de escravização.}
{323}{}{Eu vou tentar.}
{324}{}{Peço desculpas pelo meu mau desempenho.}
{325}{}{Acho que sou bom o suficiente.}
{326}{}{Droga! Você fez terrivelmente nesta corrida. Você está tentando me arruinar? Seja mais cuidadoso na próxima vez.
 Você não precisa matá-los todos! Apenas mate os hostis. Deixe os desarmados para coleta.}
{327}{}{Me desculpe, Metzger.}
{328}{}{Ei, é difícil trabalhar para ser um escravo!}
{329}{}{Gostaria de ver você fazer melhor.}
{330}{}{Eu gostaria de seguir uma corrida de escravos.}
{331}{}{Droga! Odeio perder qualquer membro da guild em uma corrida. Tente assistir os outros de volta!}
{332}{}{No geral, você fez bem esta corrida. Aqui é $}
{333}{}{ Como um incentivo para você manter o bom trabalho.}
