{100}{}{Você vê um guarda.}

{150}{}{O guarda guarda a igreja velha.}
{151}{}{[CONVERSA]}
{152}{}{Como se atreve a mostrar seu rosto novamente!}
{153}{}{[Feito]}
{154}{}{Ho! Ninguém entra no armazém da família Wright à noite!}
{155}{}{Bem, o próprio Sr. Wright me enviou uma missão. Se você não sabe disso, muito ruim.}
{156}{}{Eu voltarei amanhã.}
{157}{}{Eu preciso entrar lá agora.}
{158}{}{[Parecendo nervoso] Desculpe ... Eu não sabia. Você tem algum trabalho?}
{159}{}{Por favor! Você pode mesmo ler?}
{160}{}{Não, ele não me deu nenhum.}
{161}{}{Deixei-os de volta com a guarda. Eu vou buscá-los.}
{162}{}{Você não pode entrar sem papéis.}
{163}{}{Aqui está a minha autorização! Ataque!}
{164}{}{Eu voltarei.}
{165}{}{[Embarrassed] Não ... um ... tudo bem, continue em ...}
{166}{}{Obrigado.}
{167}{}{Isso é mais parecido com isso.}
{168}{}{O que vocês querem?}
{169}{}{Nós precisamos entrar.}
{170}{}{Nós fomos enviados aqui pelo chefe.}
{171}{}{Eu teria ouvido se um grupo foi enviado aqui. Saia!}
{172}{}{Fora com a tua cabeça!}
{173}{}{OK, OK; estavam indo.}
{174}{}{Qual é o seu negócio aqui?}
{175}{}{Eu preciso entrar.}
{176}{}{Eu fui enviado no negócio oficial pelo chefe. Fique de lado!}
{177}{}{Removendo a cabeça dos ombros.}
{178}{}{Desculpe, lugar errado.}
{179}{}{Olá de novo. Você pode continuar.}
{180}{}{Obrigado.}
{181}{}{Ei, afaste-se da porta!}
{182}{}{Não toque na porta novamente, a menos que você queira problemas.}
{183}{}{Eu vejo você tocar nessa porta novamente, você vai pegar uma bala na cabeça.}
{184}{}{Ei, o que você acha que está fazendo?}
{185}{}{Eu já tive o suficiente de você.}
{186}{}{Desculpa; Posso deixar você entrar, mas seus amigos terão de esperar lá fora.}
{187}{}{Apenas um de vocês é permitido em um momento.}

{200}{}{Boa noite.}
{201}{}{Boa tarde.}
{202}{}{Bom Dia.}
{203}{}{Apenas termine seu negócio, obrigado.}

{250}{}{Você sabe, amigo, já tive o suficiente da sua merda!}
{251}{}{Você sabe, puta, eu já tive o suficiente da sua merda!}
{252}{}{[FIM]}
