# 0. Look
{100}{}{Você vê um cidadão do Den.}
{101}{}{Você vê Derek.}

{150}{}{Ele parece bastante ágil.}

# 1.  Night (From Where to go)
{200}{}{Cai fora.}
{201}{}{Estou cansado de falar.}
{202}{}{Saia do meu lugar.}
{203}{}{Faça o seu próprio lugar para dormir.}
{204}{}{Pare de me incomodar.}
{205}{}{Estou com ônus.}
{206}{}{Doh!}
{207}{}{Ei, o que você está fazendo aqui?}

# 2. Floats before Quest 2 (From Where to go)
{220}{}{Fique longe de Metzger, tribal.}
{221}{}{Por que sempre é tão quente?}
{222}{}{Por que vivemos no deserto?}
{223}{}{Sou um bom cozinheiro.}
{224}{}{Eu vou abrir meu próprio restaurante algum dia.}
{225}{}{Eu queria ter uma cozinha real.}
{226}{}{Por que estou sempre tendo o fim da vida?}
{227}{}{As pessoas estão sempre me aparecendo.}
{228}{}{Fred é um sonhador - plano mestre, minha bunda.}

# 3. Floats after Job 2, and having talk to him (From Where to go)
{240}{}{Shhhh! Eles estão em toda parte.}
{241}{}{Faça-os parar!}
{242}{}{Então você encontrou aquele maldito livro?}
{243}{}{Não sei por que Becky não vai me contratar.}
{244}{}{Eu não ficarei louco!}
{245}{}{Recebi meus aposentos!}
{246}{}{Eles saem à noite, principalmente.}
{247}{}{Eu gosto de batatas!}
{248}{}{Não ande no material verde sem botas!}
{249}{}{Basta virar para dentro.}
{250}{}{Oh, minha cabeça doeu muito agora.}
{251}{}{Sou um grande cozinheiro chefe!}
{252}{}{Eu nunca iria envenenar a comida de um novato.}

# 4. 1st Time, On Job (From Where to go)
{260}{}{Ei, você está procurando um pouco de pão fresco?}
{261}{}{Sim.}
{262}{}{Estou procurando o livro de Becky.}
{263}{}{Não, tchau.}

# 5. Next Times (From Where to go)
{270}{}{Oh, oi novamente.}
{271}{}{Então, onde está o livro de Becky?}
{272}{}{Ei, que tal um pouco desse pão?}
{273}{}{Tchau.}

# 6. Bread (From 4)
{280}{}{Ha! Eu também. Eu já lhe contei o que é uma ótima cozinheira que eu sou? Becky não vai me contratar por algum motivo. Ela diz que eu sou instável.}
{281}{}{Ela provavelmente está certa.}
{282}{}{Estou procurando o livro de Becky.}
{283}{}{Isso é ótimo. Eu tenho que ir.}

# 7. She's right (From 6)
{290}{}{O que? Você! Aperte seu amigo! Eu não sou ... Ow! Porra.}
{291}{}{O que? Você! Enrosque sua senhora! Eu não sou ... Ow! Porra.}
{292}{}{Droga.}
{293}{}{Nuf disse.}

# 8. Looking for Book (From 4-6)
{300}{}{Oh sim. Eu não gostei disso. Muitos beijos. Eu joguei na esquina daquele edifício ... não esse edifício ... não ... era um prédio? Talvez eu tenha deixado isso em outro lugar ... ou eu joguei isso? Ow! Minha cabeça!}
{301}{}{Livro? Ah, esse livro. Quem te enviou? Não tenho certeza se esse é o lado apropriado. Não esqueça o tecido.}
{302}{}{Eu não posso! Eles são ... ah porcaria ... Você tem o queijo? Ocultar!}
{303}{}{Ei! Não é problema meu. O que eu deveria fazer? Lutar contra eles? Pequenos homens verdes, grandes dentes pontudos! Porra! Ouch! Pare com isso!}
{304}{}{Minha cabeça dói! O que ... quem disse isso?}
{305}{}{Isso ajuda muito.}
{306}{}{Uh.}

# 9. More bread (From 5)
{310}{}{O que? Você está zombando de mim! Dane-se! Eu não sou instável! Eu posso cozinhar! Eu não tenho vozes na minha cabeça!}
{311}{}{Eu sou uma merda! Porra! Droga! Pare com isso. Fique quieto! O que? ... Ok.}
{312}{}{Ei! Sto- do ... fuck.}
{313}{}{Tchau.}
{314}{}{Nada.}

# 10. Dumb Floats (From Where to go)
{320}{}{Ei! Saia de perto de mim!}
{321}{}{Não me toque!}
