# 0. Look
{100}{}{Você vê um homem magro, gorduroso.}

{150}{}{Você vê Flick, dando à sua virilha um raspador minucioso.}
{151}{}{Você vê um sujeito imundo com uma contração facial desagradável.}

# 1. Low Intelligence (WtG)
{200}{}{Saia do heeya, seu idiota.}
{201}{}{Hey meatball! Sim, você. Saia do heeya.}
{202}{}{Você é idiota ou sumpina?}
{203}{}{Whatchur problem, hein?}
{204}{}{Saia do inferno da heeya.}

# 2. Hello (WtG, 3,4,6,7,911,12,13)
{220}{}{Hey der, eu sou o Flick. Que merda você quer, hein?}
{221}{}{O que agora? Você ficou no meu tempo heeya.}
{222}{}{Qual é o sotaque maluco, Flick?}
{223}{}{Que diabos você faz aqui?}
{224}{}{Estou à procura de um Vault - oh, sim, e algum comerciante chamado Vic também. Saiba onde eles podem estar?}
{225}{}{Eu gostaria de trocar com você.}

# 3. After Barter (2,3,9)
{240}{}{Com isso, faça isso por você, amigo?}
{241}{}{Na verdade, eu gostaria de dar uma olhada em seus produtos se eu puder.}
{242}{}{Na verdade, gostaria de lhe fazer uma pergunta.}
{243}{}{Isso fez isso. Vejo você em torno de Flick.}

# 4. What do you do here (2)
{260}{}{Sou um fodido provedor, pensou Waddya? Eu sou como um bom cara de Samurai-itan.}
{261}{}{Dizer oque?}
{262}{}{Sim, uh, bem ... deixe-me perguntar-lhe outra coisa.}
{263}{}{Uh, oh. ESTÁ BEM. Adeus, Flick.}

# 5. You do what? (4)
{280}{}{Presto-lhes pequenos paisanos.}
{281}{}{Você fornece pequenos pianos?}

# 6. Pianos?(5)
{290}{}{Pai-san-o, você sabe, as crianças. Meus filhos.}
{291}{}{Seus filhos?}
{292}{}{Bem, não estou realmente interessado em lições de música para crianças. Deixe-me perguntar-lhe sobre outra coisa.}

# 7. Seus filhos? (6)
{300}{}{Sim, bem, eles funcionam para mim. Eles me trazem coisas. Coisas pequenas. Você sabe.}
{301}{}{Uh, não.}
{302}{}{Ah ok. Deixe-me perguntar-lhe outra coisa então.}
{303}{}{Ah, eu vejo. Bem, eu não quero apertar o seu estilo, você. Adeus.}

# 8. They bring you things? (7)
{315}{}{Eles me trazem o que acham. Pequenas e pequenas coisas. Coisas, ninguém já não está mais. Em troca, eu cuido deles.}
{316}{}{Parece um bom arranjo.}

# 9. Nice arrangement (8)
{325}{}{(Os encolhimentos de ombros) eu faço por OK.}
{326}{}{Deixe-me perguntar-lhe sobre outra coisa então.}
{327}{}{Eles devem ter trazido algumas pechinchas reais. Vamos ver o que você tem.}
{328}{}{Apenas checando. Bem, adeus Flick.}

# 10. Wacky accent? (2)
{340}{}{Sobre o que você falou? Você acha que eu sou uma pirata estúpida? Algum estranho filio di puttana? Você acha que eu sou um palhaço? Estou aqui para divertir você, não é?}
{341}{}{Uh, não. Sorry, I was just curious. Let me ask you about something else.}
{342}{}{Sim, está certo, merda. E nada vai me divertir mais do que a sua morte.}
{343}{}{Bem, se você vai ficar com tudo, eu vou embora.}

# 11. Vic & Vault (2)
{360}{}{Vault, hein? Talvez mamãe saiba sobre isso, porque eu não. Mas esse cara Vic - ele eu sei. Metzger tem aquela pistola porca.}
{361}{}{Vic? Não é ele com você? Você biota. Mas mamãe, ela eu sei.}
{362}{}{Quem é Metzger?}
{363}{}{Quem é a mãe?}
{364}{}{Obrigado. Deixe-me perguntar-lhe outra coisa.}
{365}{}{Obrigado, é tudo o que preciso saber. Adeus.}

# 12. Quem é a mãe? (11,13)
{380}{}{Momma dirige um lugar de comida no lado leste de uma cidade. Passando o cemitério. Bom lugar, ela pegou boa massa, Mama mia.}
{381}{}{Obrigado, e esse companheiro de Metzger que tem Vic?}
{382}{}{Obrigado. Deixe-me perguntar-lhe outra coisa.}
{383}{}{Obrigado, é tudo o que preciso saber. Adeus.}

# 13. Quem é Metzger? (11,12)
{400}{}{Está certo. Metzger, aquele estronzo, ele está morto. Não sei o que aconteceu com Vic.}
{401}{}{Aquele Metzger, ele é um verdadeiro rompiballe, aquele. Executa o Slaver's Guild. Lado leste da cidade, ao norte de Momma. De qualquer forma, ele conseguiu Vic, eu sei.}
{402}{}{Obrigado, agora e a mamãe?}
{403}{}{Obrigado. Deixe-me perguntar-lhe outra coisa.}
{404}{}{Obrigado, é tudo o que preciso saber. Adeus.}
