# 0. Look
{100}{}{Você vê um cidadão do Den.}
{101}{}{Você vê Fred.}
{102}{}{Você vê Fred, vestindo roupas muito finas.}

{150}{}{Ele parece estar ocupado pensando em algo.}
{151}{}{Ele parece muito feliz com seus novos e legais tópicos.}

# 1.  Fred B4 Becky's Job (From Where to go)
{200}{}{Eu vou fazer isso grande algum dia.}
{201}{}{Oh, deixe-me em paz. Estou ocupado.}
{202}{}{O Plano mestre…}
{203}{}{Indo descobrir algum dia ...}
{204}{}{Por que eu sempre perco?}
{205}{}{As tabelas devem ser manipuladas.}
{206}{}{... Eu vou ser meu próprio lugar algum dia.}
{207}{}{Vou pegar roupas bonitas.}

# 2. Night (From Where to go)
{220}{}{E aí cara! Está tarde. Me deixe em paz.}
{221}{}{Não, não preciso de nenhuma empresa.}
{222}{}{Você sabe que horas são?}
{223}{}{Eu não tenho nada.}
{224}{}{Bug me da manhã. Estou cansado.}
{225}{}{Cai fora.}
{226}{}{Ninguém está em casa.}
{227}{}{Não posso falar. Estou me preparando para a cama.}
{228}{}{Ei moça! Está tarde. Me deixe em paz.}

# 3. Paid, Broke Floats (From Where to go)
{240}{}{Não há mais dinheiro! Me deixe em paz.}
{241}{}{Não há trabalho. O que eu vou fazer?}
{242}{}{Não me diga que devo a outra pessoa! Ahh!}
{243}{}{Eu nunca vou fazer isso grande agora.}
{244}{}{Estou tão quebrado.}
{245}{}{Oh, eu preciso de dinheiro.}
{246}{}{Nunca vou comprar roupas novas agora.}
{247}{}{Tenho que obter um novo plano mestre ...}

# 4. Covered, Floats (From Where to go)
{260}{}{Obrigado por me cobrir!}
{261}{}{Você é um salvador de vida real.}
{262}{}{Eu terei o dinheiro para você em breve.}
{263}{}{Eu vou ganhar grande em breve!}
{264}{}{Você é a primeira pessoa que vejo quando eu ganhar grande.}

# 5. Covered and Loaned, Floats (From Where to go)
{275}{}{O plano mestre está em ação!}
{276}{}{Obrigado pelo empréstimo! Você está com boas mãos!}
{277}{}{Essas mesas certamente são difíceis, mas não se preocupe.}
{278}{}{Vai ganhar grande um dia, graças a você.}
{279}{}{Eu sou devido em qualquer dia! Eu posso sentir isso.}
{280}{}{Eu vou pagar você de volta, eu juro!}
{281}{}{Eu vou ganhar muito rápido em breve. Eu posso sentir o cheiro.}

# 6. 1st Time on Job 1 (From Where to go)
{295}{}{Hã? Eu conheço você? O que você quer?}
{296}{}{Por que você continua incomodando-me? Eu nem conheço você. Vai investigar outra pessoa.}
{297}{}{Estou aqui para recolher algum dinheiro que você deve a alguém.}
{298}{}{Deixa pra lá.}
{299}{}{Reino Unido!}
{300}{}{Tchau.}

# 7. Won It BIG! (From Where to go)
{310}{}{EI! Aí está você! Estive procurando por você! Confira esses tópicos!}
{311}{}{Obrigado novamente.}
{312}{}{Parecendo muito legal.}
{313}{}{Você parece uma porcaria!}
{314}{}{Yuk!}
{315}{}{Ug.}

# 8. Look nice (From 7)
{320}{}{Obrigado. Muito obrigado! Graças a você, eu tenho quatro sets como esses!}
{321}{}{Então, você ganhou grande depois de tudo?}
{322}{}{Então, onde está o meu dinheiro?}

# 9. Look bad (From 7)
{330}{}{Você não gosta dos meus tópicos? Você sabe, eu acho seu direito. Eu também não gosto deles. Tempo para alguns novos - eu posso pagar!}
{331}{}{Então, você ganhou grande depois de tudo?}
{332}{}{Onde esta meu dinheiro?}
{333}{}{Hmph.}

# 10. Give me money 1 (From 8, 9)
{340}{}{Eu estava chegando lá! Até não me deixará ir em minha glória? Eu trabalhei duro por isso, você sabe.}
{341}{}{Eu sei, me desculpe.}
{342}{}{Dane-se isso. Onde está o dinheiro pelo qual te cubri?}
{343}{}{I don't give a crap. Onde esta meu dinheiro?}

# 11. Give me money 2 (From 10)
{350}{}{Fine. Here. [Fred gives you $500] There's a little extra for trusting me. Well, see you later. Obrigado novamente.}
{351}{}{Obrigado!}
{352}{}{Tanto faz.}

# 12. Covered 1 (From 8-10)
{360}{}{Muito obrigado por me cobrir. Realmente significava muito para mim, para ser confiado por um completo estranho. Deixe-me dar-lhe isso.}
{361}{}{OK.}
{362}{}{Você não deveria ter.}
{363}{}{Uh.}

# 13. Loaned 1 (From 8-10)
{370}{}{Eu devo muito a você. Você confiou em mim quando eu estava com a minha sorte. Como um pequeno gesto de gratidão, tenho algo para você.}
{371}{}{OK.}
{372}{}{Você não deveria ter.}
{373}{}{Uh.}

# 14. Covered 2 (From 12)
{380}{}{Aqui. [Fred lhe dá $ 1000.] Espero que isso ajude. Tenho certeza que você encontrará algum lugar para gastá-lo.}
{381}{}{Desculpe, não posso aceitar isso.}
{382}{}{Obrigado.}
{383}{}{Na verdade não, mas vou entender.}
{384}{}{Yum.}

# 15. Loan 2 (From 13)
{390}{}{Aqui. [Fred lhe dá $ 2000, 5 células Fusion, 5 células de energia e uma granada de plasma.] Espero que isso ajude, pelo menos um pouco.}
{391}{}{Desculpe, não posso aceitar isso.}
{392}{}{Muito obrigado.}
{393}{}{Na verdade não, mas vou entender.}
{394}{}{Yum.}

# 16. Refused reward (From 15)
{400}{}{O que? Bem, se você insistir. Muito obrigado. Cuide bem de você.}
{401}{}{Tchau.}

# 17. Dumb, beat it (From 6)
{410}{}{O que? Você está fazendo algum quim estranho? Você não se parece com um jato. Afaste-se de mim, você é uma aberração.}
{411}{}{Cai fora!}
{412}{}{Ug.}

# 18. Here to collect (From 6)
{420}{}{Do que você está falando? Não devo nada a ninguém. Com quem diabos você está falando?}
{421}{}{Sim, você disse na última vez. Eu não sei do que você está falando? Quem é essa pessoa imaginária novamente?}
{422}{}{Becky diz que lhe deve US $ 500}
{423}{}{Becky me enviou.}
{424}{}{Rebecca diz que ela emprestou US $ 200.}

# 19. Sure she lent me $200 (From 18)
{430}{}{Ah sim, certo. Rebecca me emprestou $ 200 ... Oh, espere. Talvez ... ummm ...}
{431}{}{Ela me disse para quebrar o pescoço se você não pagar.}
{432}{}{Entregue-o.}

# 20. Owe $500 (From 18)
{440}{}{Okay, certo. Nunca vi tanto dinheiro antes na minha vida.}
{441}{}{Hmmm.}
{442}{}{Oh.}

# 21. Becky Swear or Pissed (From 19)
{450}{}{Certo! Esse será o dia. Becky não feriria uma mosca. Ela certamente é bonita.}
{451}{}{Bem, você está errado, idiota.}
{452}{}{Talvez fosse outra pessoa.}

# 22. Remembers money (From 19, 33-35)
{460}{}{Droga. Eu acho seu direito, mas - estou quase quebrado. Eu não posso pagar esse tipo de dinheiro! Eu tenho que comer você sabe.}
{461}{}{Desculpa.}
{462}{}{Tough luck.}

# 23. Tuff Luck (From 22)
{470}{}{Oh, droga. Eu quase não posso pagar US $ 100. Você poderia me ver metade? Eu prometo que vou te pagar de volta!}
{471}{}{Não desculpe.}
{472}{}{Vamos. Pague o montante total!}
{473}{}{Certo, tudo bem.}

# 24. Will pay 200 (From 23, 37)
{480}{}{Droga. Você vai me arruinar! Bem, está bem aqui. Agora estou completamente quebrado.}
{481}{}{Oh, tudo bem. Eu o cobrirei.}
{482}{}{Obrigado. Manage your money better next time.}
{483}{}{Agradeço pelos seus serviços.}

# 25. Failed Speech for Full amount (From 23, 37)
{490}{}{Eu te disse! Eu não posso! Eu vou morrer de fome se eu fizer. Oh, vamos, você não pode me ajudar?}
{491}{}{Tudo certo. Cobriria metade disso.}
{492}{}{Não desculpe. I don't have the cash either.}
{493}{}{Eu voltarei.}

# 26. PC will Cover (From 23-25, 29, 37)
{500}{}{O que? Mesmo? Uau! Muito obrigado, cara! Aqui estão $ 100. Recebo os outros $ 100 para você o mais rápido possível!}
{501}{}{O que? Mesmo? Uau! Muito obrigado, senhora! Aqui estão $ 100. Recebo os outros $ 100 para você o mais rápido possível!}
{502}{}{Sem problemas.}
{503}{}{É melhor me pagar de volta.}

# 27. Better pay PC back! (From 26)
{510}{}{Oh, não se preocupe. Eu vou! Você tem minha palavra e não vou esquecê-la desta vez!}
{511}{}{OK.}

# 28. Fred asks for Loan (From 26-27)
{520}{}{Diga, você sabe o que? Que cem realmente vão ... atrasar as coisas. Você acha que eu poderia emprestar um pouco de volta?}
{521}{}{Quantos?}
{522}{}{De jeito nenhum.}

# 29. Wait I know… (From 25)
{530}{}{Esperar! Eu sei. Diga-lhe o que, eu lhe darei $ 100 e você me observará pelos outros US $ 100 que devo à Becky. Eu vou pagar de volta em breve.}
{531}{}{Certo, tudo bem.}
{532}{}{Nenhum acordo.}

# 30. Amount of Loan (From 28)
{540}{}{Apenas US $ 50. Por favor! Tudo faz parte do plano principal!}
{541}{}{Tudo certo.}
{542}{}{Mas isso só vai me deixar com US $ 50 para pagar seu empréstimo de US $ 200.}
{543}{}{Não.}

# 31. PC gave Loan (From 30)
{550}{}{Wha-uh ... Droga! Você não vai se arrepender disso! Eu sou bom para isso!}
{551}{}{Sem problemas.}

# 32. Clarification of amount of loan (From 30)
{560}{}{Uh, sim. Vejo suas habilidades de matemática, quero dizer, por favor! Não é muito para você, tenho certeza, mas é muito para mim.}
{561}{}{OK.}
{562}{}{Não.}

# 33. Becky sent PC (From 18)
{570}{}{Sim, claro que sim. Todo mundo sabe que ela odeia esse nome. Você não está me enganando!}
{571}{}{Não lhe devo nada.}
{572}{}{Ela disse que você era esquecida.}
{573}{}{Olha, não tenho tempo para isso. Pague maldição!}
{574}{}{Rebecca disse que emprestou isso a você um tempo atrás.}

# 34. Forgetful (From 33)
{580}{}{Eu não estou! Eu espero. Havia uma vez. Não paguei as costas? Eu pensei que fiz ...}
{581}{}{Não, você não. É por isso que ela me enviou.}
{582}{}{Apenas pague para que eu possa sair daqui.}

# 35. Don't quite remember (From 33)
{590}{}{Eu não me lembro ... mas Becky certamente me ajudou e meus amigos no passado.}
{591}{}{Entregue os $ 200.}
{592}{}{Apenas me dê o dinheiro.}

# 36. Get out of here (From 33)
{600}{}{Me deixe em paz.}
{601}{}{Tanto faz.}
{602}{}{OK.}

# 37. Remembers (From Where to go)
{610}{}{Uh. Oi de novo. Então, uh, suponho que você quer o dinheiro. Você acha que poderia me proteger por metade?}
{611}{}{Não, desculpe.}
{612}{}{Se ela emprestou US $ 200, você pagará.}
{613}{}{Certo, tudo bem.}
