# 0. Look
{100}{}{Você vê um guarda.}

{150}{}{Ele é um dos guardas de Tyler.}

# 1. Hostile
{200}{}{Você ainda está vivo?}

# 2. CF: Gang 2 Defeated
{210}{}{Nós os mostramos, não é?}
{211}{}{Ninguém confusa com a gente.}
{212}{}{Nós chutamos o traseiro.}
{213}{}{Com o tempo, terminamos com eles.}
{214}{}{Não posso esquecer o olhar em seu rosto. Foi ótimo.}
{215}{}{Estou surpreso com Metzger não ficou chateado.}
{216}{}{Pergunto-me por que o Metzger não entrou.}

# 3. ELSE
{225}{}{Não sei por que Metzger nos guarda essa merda.}
{226}{}{Quem vai tentar roubar essa porcaria?}
{227}{}{Este trabalho é um passeio de pastelaria.}
{228}{}{Ninguém nunca se preocupa conosco.}
{229}{}{Eu acho que essas coisas vieram de um Vault ou algo assim.}
{230}{}{O que você está procurando de qualquer maneira?}
{231}{}{Não há nada aqui, exceto nós, ratos.}
{232}{}{Não perca seu tempo, verificamos essas coisas mais de um milhão de vezes.}

# 4. SET
{233}{}{Esta noite é a noite.}
{234}{}{Eu odeio esperar.}
{235}{}{Eu vou passar as bebidas para isso a qualquer momento.}
{236}{}{Já é tempo? Mal posso esperar.}
{237}{}{Espero ter a primeira matança.}
{238}{}{Por que eles esperaram até agora para se mexer com a gente?}
{239}{}{Isso vai ser interessante.}

# 5. NOSHOW
{240}{}{Muito ruim, não conseguimos nenhuma ação depois de tudo.}
{241}{}{Pergunto-me por que eles mudaram de idéia.}
{242}{}{Tudo isso esperando e nada.}
{243}{}{Então, o que aconteceu com essa armadilha, você nos ajudaria a definir?}
{244}{}{O que aconteceu na outra noite?}
{245}{}{Muito ruim, aqueles covardes se irritaram. Teria sido bom terminá-los.}
{246}{}{Não posso acreditar que os bastardos tentassem nos emboscer.}
