# 0. Look
{100}{}{Você vê um gangster.}

{150}{}{Ele parece ser um membro da gangue de Lara.}
{151}{}{Ela parece ser um membro da quadrilha de Lara.}

# 1. Hostile
{200}{}{Cara sábio.}
{201}{}{Aí está você.}
{202}{}{Retorno.}
{203}{}{Venha aqui.}
{204}{}{Eu não termino com você.}
{205}{}{Cadela.}

# 2. Metzger's Dead
{225}{}{Imagina por quanto tempo as coisas durarão aqui com Metzger ido?}
{226}{}{Então, Metzger está finalmente morto?}
{227}{}{Foi o seu trabalho manual?}
{228}{}{O Den nunca mais será o mesmo.}

# 3. 2Won
{240}{}{Eu não posso acreditar, nós realmente os vencemos!}
{241}{}{Metzger tem que nos mostrar o respeito agora.}
{242}{}{Nós mostramos isso.}
{243}{}{Nós lhes demos a nossa própria marca de justiça.}
{244}{}{Não poderíamos ter feito isso sem você!}
{245}{}{Obrigado pela ajuda!}
{246}{}{Nós fizemos isso!}

# 4. NO SHOW
{247}{}{Você está a virar com a gente?}
{248}{}{Melhor assistir você pisar.}
{249}{}{Lara é a única razão pela qual não te encadernamos agora.}
{250}{}{O que você estava tentando puxar?}

# 5. COWARD
{251}{}{Covarde.}
{252}{}{Você me deixa doente.}
{253}{}{Dá o fora}
{254}{}{Cai fora.}

# 6. FIGHT
{255}{}{Estamos prontos quando você estiver.}
{256}{}{Já é hora de devolvê-los.}
{257}{}{Eu odeio esperar.}
{258}{}{Vamos já.}
{259}{}{Você está pronto ainda?}
{260}{}{Apenas deixe Lara saber quando é hora.}

# 7. NO
{270}{}{Você está procurando juntar-se?}
{271}{}{Você deve estar aqui para ver Lara.}
{272}{}{Como tá indo?}
{273}{}{Lara é a pessoa com quem você deveria conversar.}
{274}{}{Oi.}
{275}{}{Você está aqui para ver Lara?}

# 8. Else
{300}{}{Oi.}
{301}{}{Como tá indo?}
{302}{}{Espero que as coisas estejam indo bem.}
{303}{}{Então você pode nos ajudar?}
{304}{}{Bom te ver.}
{305}{}{Nós devolveremos Tyler em breve ...}
{306}{}{Alguma novidade?}

# 9. Lara Dead
{310}{}{Obrigado pela ajuda. Muito ruim sobre Lara.}
{311}{}{Nós finalmente conseguimos em!}
{312}{}{Não poderíamos ter feito isso sem você.}
{313}{}{Pelo menos Lara saiu na luta.}
{314}{}{Não posso acreditar que Lara não conseguiu.}
{315}{}{Certamente mostramos o melhor de Metzger.}
{316}{}{Metzger está melhor com a gente.}

# 10. Running to fight
{350}{}{Você disse isso!}
{351}{}{Eles são carne morta!}
{352}{}{Nós vamos chutar um traseiro sério!}
