# 0. Look
{100}{}{Você vê um jogador.}
{101}{}{Este jogador parece estar indo extremamente bem.}
{102}{}{Ele parece estar ganhando, mas todo seu dinheiro está na mesa.}
{103}{}{Ela parece estar ganhando, mas todo seu dinheiro está na mesa.}
{104}{}{Esta pessoa não parece estar ganhando ou perdendo}
{105}{}{Esta pessoa não ganhou em um tempo.}
{106}{}{Parece que está prestes a chorar e parece estar quase sem dinheiro.}
{107}{}{Ele parece muito irritado e parece estar perdendo grande.}

# 1. PC Killed Becky, NPC are still around (From Where to go)
{200}{}{Não me machuque!}
{201}{}{Não atire!}
{202}{}{Eu não tenho dinheiro!}
{203}{}{Por que você teve que matar o pobre Becky?}
{204}{}{O que ela sempre fez com você?}
{205}{}{Eu não fiz nada!}
{206}{}{Por favor, não vou contar.}

# 2. CF: Gambling (From Where to go)
{300}{}{Sim! Os dados me amam!}
{301}{}{Ah, estava perto.}
{302}{}{Não me interrompa. Você vai arruinar minha série de vitórias.}
{303}{}{Eu sou gata!}
{304}{}{Dinheiro dinheiro dinheiro!}
{305}{}{Eu amo este jogo!}
{306}{}{Você viu isso! Sim!}
{307}{}{A roleta é o jogo a jogar!}
{308}{}{Estou muito bem, e você?}
{309}{}{Estou fazendo o melhor do que o normal.}
{310}{}{Ótimo lugar, você não acha?}
{311}{}{As mesas de Becky são melhores do que o New Reno.}
{312}{}{Você gosta desse jogo? É muito divertido.}
{313}{}{Eu não tive um bom rolo por um tempo.}
{314}{}{Eu preciso de um bom rolo.}
{315}{}{Bem, pelo menos não estou perdendo.}
{316}{}{Eu não estou indo a lugar nenhum.}
{317}{}{Estou acabando de terminar.}
{318}{}{Você deve jogar os números.}
{319}{}{Apenas apostar no vermelho ou no preto é uma má probabilidade.}
{320}{}{Os dados não estão se comportando.}
{321}{}{Estou caído e não está ficando bem.}
{322}{}{Espero que você faça melhor do que eu.}
{323}{}{Eu vi dias melhores.}
{324}{}{Eu sei como jogar, honesto.}
{325}{}{A bola não está saltitando hoje em dia.}
{326}{}{Outro dia de pagamento perdeu para sempre.}
{327}{}{Estou quase quebrada!}
{328}{}{Droga. Isso é uma merda.}
{329}{}{Por que isso sempre acontece comigo?}
{330}{}{Não posso ganhar.}
{331}{}{Eu odeio esse jogo.}

# 3. BGF: Becky Dead (From Where to go)
{400}{}{Maldito, Becky foi o único lugar para jogar por aqui!}
{401}{}{Ficar longe.}
{402}{}{Não atire!}
{403}{}{Deixe-nos solitários.}

# 4. BGF: Gambling (From Where to go)
{500}{}{Não pare por aí.}
{501}{}{Continue andando.}
{502}{}{VENHA 7!}
{503}{}{Sim!}
{504}{}{Deixe vir!}
{505}{}{Becky! Eu vou pegar todo o seu dinheiro hoje!}
{506}{}{Woohoo! Vencedora!}
{507}{}{Me dê outro bom salto!}
{508}{}{Sim!}
{509}{}{Tudo certo!}
{510}{}{Novamente, vamos ver isso de novo.}
{511}{}{Vamos.}
{512}{}{Foi o que eu queria.}
{513}{}{Quase.}
{514}{}{Não é ruim.}
{515}{}{Como isso aconteceu?}
{516}{}{Oops.}
{517}{}{Não há wammies, nem wammies. Pare!}
{518}{}{Bem, o jogo está à altura do seu nome.}
{519}{}{Eu só preciso de uma grande vitória.}
{520}{}{Figuras!}
{521}{}{Novamente?}
{522}{}{Isso não parece estar bem.}
{523}{}{A roleta é uma porcaria!}
{524}{}{Becky! Vocês mesas estão me matando!}
{525}{}{São os dados carregados ou o quê?}
{526}{}{De novo não!}
{527}{}{Por que eu?}
{528}{}{Droga! Tão perto!}
{529}{}{Oh doce doce Jesus, MORREM-ME AGORA!}
{530}{}{Eu odeio esse jogo!}
{531}{}{Droga! Esse foi o meu número no último turno!}
{532}{}{Black novamente!?!?}

# 5. CF: Hostile (From Where to go)
{600}{}{Cai fora!}
{601}{}{Porque você fez isso?}
{602}{}{Cai fora!}
{603}{}{Pare com isso, sou frágil.}
{604}{}{Eu não faria isso você.}
