{100}{}{Você vê um bandido.}
{101}{}{Você vê Joey.}

{150}{}{Esse cara não parece muito amigável.}
{151}{}{[CONVERSA]}

# 1.
{152}{}{Eu vou cortar você, fucker!}
{153}{}{Sim? Venha e tente.}
{154}{}{Ei, espere apenas um minuto!}
{155}{}{Eu pensaria duas vezes se eu fosse você.}

# 2.
{156}{}{O que você quer? Por que eu não deveria simplesmente te matar ao invés de ouvir
 para suas besteiras depois do que você fez?}
{157}{}{Quero falar com você sobre um fantasma que vem por aqui à noite.}
{158}{}{Você pegou um medalhão da casa assombrada?}
{159}{}{Deixa pra lá. Em vez disso, vou chutar a sua bunda.}
{160}{}{Nada. Apenas passando.}

# 3.
{161}{}{Que diabos você está falando?}
{162}{}{Você roubou um medalhão daquela casa assombrada?}
{163}{}{Nada. Deixa pra lá.}
{164}{}{Esqueça. Vou matá-lo agora e resolver as peças mais tarde.}

# 4.
{165}{}{Eu ... eu não sei do que você está falando.}
{166}{}{Oh, eu acho que você faz! Você roubou o medalhão de uma garota morta, e agora seu espírito não pode descansar.}
{167}{}{Então eu vou pegar com força.}

# 5.
{168}{}{T-Isso é louco! Você deve ter sido r-realmente fodido em alguma merda de Tubby. Eu - eu nunca vi nenhum g-ghost w-quando eu fiquei t-there - apenas uma viagem ruim, não era f-fucking real.}
{169}{}{Olha, vou comprá-lo de você.}
{170}{}{Dê para mim ou você pode se juntar a ela.}
{171}{}{Se você não retornar agora, ela irá depois de você. E ela não pode
 ser parado.}

# 6.
{172}{}{Hã? Oh sim. Sim. T-Isso é seguro. Você vai ter que ganhar com alguns dólares com certeza. Você não está conseguindo isso de graça! US $ 50 ou vença!}
{173}{}{Ok, aqui está o dinheiro.}
{174}{}{Pegue US $ 20 e fique feliz, eu não apenas tire isso de você.}
{175}{}{Nah, eu mudei de idéia. Até mais.}
{176}{}{Dê para mim ou eu mato você por isso.}

# 7.
{177}{}{Aqui. Agora, deixe-me em paz.}
{178}{}{Com alegria.}
{179}{}{Não me deixe pegar você fazendo isso de novo!}

# 8.
{180}{}{H-Hey! Você não tem dinheiro! Saia já daqui!}
{181}{}{Oops. Eu voltarei.}
{182}{}{Então eu acho que eu tenho que matá-lo.}

# 9.
{183}{}{Ei. Como vai'?}
{184}{}{OK e tu?}
{185}{}{Não tão bom.}
{186}{}{Você pegou um medalhão daquela casa assombrada?}
{187}{}{O que você sabe sobre esse fantasma que vem por aqui à noite?}

# 10.
{188}{}{Ei, cara, eu sou Joey. O que você está fazendo no meu território?}
{189}{}{Seu relvado? Acho que não.}
{190}{}{Talvez eu esteja procurando por você.}
{191}{}{Apenas saindo. Tchau.}
{192}{}{À procura de alguma informação.}

# 11.
{193}{}{Ei, bolos para bebês. Você está procurando por Joey? Aqui estou.}
{194}{}{Não vá embora.}
{195}{}{Talvez. O que você está me oferecendo?}
{196}{}{Eu quero alguma informação.}
{197}{}{Não, desculpe. Eu tenho que ir agora.}

# 12.
{198}{}{Ei, eu tenho um jato. É ótimo e novo de Reno. Quer um pouco?}
{199}{}{De jeito nenhum!}
{200}{}{Quantos?}
{201}{}{Não, eu quero informações.}
{202}{}{Eu tenho que ir. Tchau.}

# 13.
{203}{}{Que tal você e eu entendemos?}
{204}{}{OK.}
{205}{}{Não se você fosse o último homem não morto no planeta.}
{206}{}{Er, não ... Eu não penso assim. Preciso de outra coisa.}

# 14.
{207}{}{Você vai voltar.}
{208}{}{Talvez.}
{209}{}{Não conte com isso.}
{210}{}{Esperar! Posso te perguntar uma coisa?}

# 15.
{211}{}{Ninguém fala comigo assim!}
{212}{}{Eu apenas fiz. Você faz mais do que falar?}
{213}{}{Tanto faz. Você está vendendo algo ou apenas fazendo pequenas conversas?}
{214}{}{Me desculpe. Estou realmente olhando ao redor e não conheço a área.}

# 16.
{215}{}{O que você quer?}
{216}{}{Estou procurando um medalhão.}
{217}{}{Preciso saber mais sobre essa casa assombrada.}
{218}{}{Qual é o acordo com a igreja antiga e esses guardas?}
{219}{}{Nada que você possa fornecer.}
{220}{}{Você já ouviu falar do Vault 13?}
{221}{}{Hum, não importa. Até a próxima.}

# 17. The Church
{222}{}{Oh, você quer dizer Tyler e sua gangue? Eles guardam uma merda que vem da Cidade do Vault. Grandes caixas de porra. De vez em quando você vê-los serem apanhados pelas caravanas em direção a New Reno.}
{223}{}{Posso lhe perguntar mais sobre eles?}
{224}{}{Posso pedir-lhe outra coisa?}
{225}{}{Ok, obrigado. Tchau.}

# 18.
{226}{}{O que mais você quer saber?}
{227}{}{Quem é Tyler?}
{228}{}{Onde está o novo Reno?}
{229}{}{Então, o que eles estão guardando?}
{230}{}{Quero lhe perguntar sobre outra coisa.}
{231}{}{É isso aí. Tchau.}

# 19 Who's Tyler?
{232}{}{Tyler é apenas uma doninha que ferrou todo o resto de nós por um doce negócio com
 Metzger, mas foda essa merda! Eu não me importo mais. Eu poderia chutar o seu maldito culo, no entanto.
 Lara e ele ainda têm um sangue muito ruim. Algo sobre Tyler e seu irmão.}
{233}{}{That could be useful. Posso lhe perguntar mais sobre eles?}
{234}{}{Posso pedir-lhe outra coisa?}
{235}{}{Ok, obrigado. Tchau.}

# 20. New Reno?
{236}{}{O novo Reno está no sul por longos caminhos, depois pelo leste. Há muito
 de ação a ser feita lá, mas é muito perigoso também. Eu posso voltar
 algum dia. Aqui, posso mostrar-lhe onde está naquela tela fantasiosa sua.}
{237}{}{I think I can find it now. Posso lhe perguntar mais sobre eles?}
{238}{}{Posso pedir-lhe outra coisa?}
{239}{}{Ok, obrigado. Tchau.}

# 21. Contents?
{240}{}{Inferior se eu souber.}
{241}{}{Interesting. Posso lhe perguntar mais sobre eles?}
{242}{}{Posso pedir-lhe outra coisa?}
{243}{}{Ok, obrigado. Tchau.}

# 22.
{244}{}{Para você, vou vender jato por US $ 500.}
{245}{}{Não, obrigado. Tchau.}
{246}{}{Não, obrigado, mas gostaria de lhe perguntar uma coisa.}
{247}{}{Isso é demais!}
{248}{}{OK, vou comprá-lo.}

# 23.
{249}{}{Se você não tem o dinheiro, volte quando você pode pagar. Não me deixe ver
 você está comprando de qualquer outra pessoa ou eu vou chutar seu bicho maldito. Eu sou o único com o puro
 merda não cortada, enviada diretamente de New Reno.}
{250}{}{Espere, vou comprá-lo.}
{251}{}{Bem, posso te perguntar uma coisa?}
{252}{}{Tchau.}

# 24.
{253}{}{OK, vou deixar o preço para US $ 350, mas não menos! Essa é a minha oferta final. Você tem que pagar
 dólar superior pela boa merda. Não compre contra Tubby ou qualquer um desses perdedores. Eles cortaram
 merda. Eu sou o único por milhas que pode conseguir as melhores coisas.}
{254}{}{Esqueça. Posso te perguntar uma coisa?}
{255}{}{OK, vou comprá-lo.}
{256}{}{Never mind. Tchau.}

# 25
{257}{}{Vault ... Vault ... Vault 13? Não, nunca ouvi falar disso. Não me diga que eles apareceram
 com outro novo químico! Nada pode vencer o jato!}
{258}{}{Não, seu idiota.}
{259}{}{Não, é um lugar. Posso perguntar outra coisa?}
{260}{}{Sim, um químico maravilhoso.}
{261}{}{Não, tchau.}

# ??Don't know what this is for.
{262}{}{Joey aqui não é muito conversador.}

# 4. extra
{300}{}{Probably not. Tchau.}

# Addition for Node 17
{350}{}{Você estava dormindo? Acontece que Lara é uma pequena puta, afinal. Ela tirou Tyler para baixo. Eu ouvi que Metzger estava no assunto. Bem, é melhor eu voltar para ... trabalhar.}
{351}{}{Você estava dormindo? Acontece que Lara era uma pequena puta, apesar de tudo, muito ruim, ela está morta. Bombardeou o grupo de Tyler. Sua gangue está correndo lá, agora, eu ouvi por última vez.}
