# 0. Look
{100}{}{Você vê Lara.}

{150}{}{Ela é a líder dessa quadrilha.}

# 1. Start (From Where to go)
{200}{}{O nome é Lara; Eu executo essa quadrilha. É melhor não estar aqui para causar problemas ou
 Você está em um mundo de dor.}
{201}{}{Oi de novo. Preciso de algo?}
{202}{}{Tem algum trabalho?}
{203}{}{Apenas olhando por aí.}
{204}{}{Estou à procura de um comerciante chamado Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}

# 2. Dumb, bye (From 1, 26)
{220}{}{Não temos médicos na cidade e não posso ajudá-lo.}
{221}{}{Desculpe, eu ainda não entendo.}
{222}{}{Ack.}

# 3. Vic (From 1)
{230}{}{O nome não soa um sino, mas, novamente, eu não acompanho quem entra e sai da cidade. Verifique com Becky. Todo mundo acaba passando por lá. Ela pode saber.}
{231}{}{Tem algum trabalho?}
{232}{}{Obrigado. Tchau.}

# 4. Looking around (From 1)
{240}{}{Se você não veio ao Den por uma razão específica, provavelmente você deveria sair. Não é muito seguro por aqui.}
{241}{}{Oh, está bem.}
{242}{}{Tem algum trabalho?}
{243}{}{Eu posso lidar comigo mesmo.}
{244}{}{Ok, obrigado.}

# 5. Handle (From 4)
{250}{}{Sem dúvida. Caso contrário, você provavelmente não teria feito isso aqui vivo.}
{251}{}{Uh, sim, então eu ouvi. Você já disse isso.}
{252}{}{Tem algum trabalho?}
{253}{}{Ok, obrigado.}

# 6. Got work? (From 1, 3-5)
{260}{}{Bem, depende do que você é bom. Há algo sobre o que tenho curiosidade. Se você consegue descobrir, eu vou pagar um pouco.}
{261}{}{Como eu disse, estou procurando mais informações sobre uma certa coisa ... ou em algum lugar. Vou pagar, é claro.}
{262}{}{Claro, o que é isso?}
{263}{}{Talvez mais tarde.}

# 7. Bye, let me know if mind changes (From 6)
{270}{}{Deixe-me saber se você mudar de opinião.}
{271}{}{Tudo certo.}

# 8. Setting Crates (From 6)
{280}{}{Bem, há uma igreja a leste daqui. Metzger tem algumas pessoas protegendo o que for
 está dentro. Descubra o que e eu pagarei US $ 200.}
{281}{}{Essa foi fácil. Eu já sei.}
{282}{}{Certo.}
{283}{}{Verei o que posso fazer.}

# 9. Thanks (From 8)
{290}{}{Obrigado. Não entre em uma luta ... ainda. Eu tenho um plano.}
{291}{}{Sem problemas.}
{292}{}{Eu volto já.}

# 10. Crates Answered (From 8)
{300}{}{O que é isso?}
{301}{}{Compostos químicos brutos em grandes caixotes.}
{302}{}{Grandes recipientes que possuem produtos químicos de algum tipo.}
{303}{}{Deixe-me verificar novamente.}

# 11. Crates Answered (From 10, 18)
{310}{}{Isso realmente faz sentido. Obrigado. Aqui está o seu dinheiro.}
{311}{}{Por que é que?}
{312}{}{Sem problemas. Bye.}

# 12. Makes Sense? (From 11)
{320}{}{Eu vi caravanas de Vault City entrar e, em seguida, alguns deles são apanhados pelas caravanas de New Reno.}
{321}{}{Assim? Por que isso faz sentido?}
{322}{}{Oh.}

# 13. Makes Sense, Bye (From 12)
{340}{}{O novo Reno é o químico capital por aqui. Eles têm que obter as matérias-primas para fazer chems de algum lugar, certo? Parece que eles estão recebendo algum, ou tudo isso, da Vault City.}
{341}{}{Onde está o novo Reno?}
{342}{}{Ok, obrigado.}

# 14. Located? (From 13)
{350}{}{Não tenho certeza exatamente. Algum lugar para o sul, eu acho. Eu nunca estive lá, eu só vejo suas caravanas parar de comprar de vez em quando - uma vez por muito tempo.}
{351}{}{Oh, está bem. Thanks.}

# 15. (From 11-14)
{360}{}{Você está procurando um dinheiro mais rápido e fácil? $ 50. Dinheiro fácil.}
{361}{}{Certo.}
{362}{}{Faça isso rápido.}

# 16. Set Ask (From 15)
{370}{}{Preciso que você verifique com a Metzger para ver se ele ficaria bem se Tyler e eu instalássemos algumas pessoas idosas. Ele vai entender o que quero dizer.}
{371}{}{Por que você quer que eu pergunte?}
{372}{}{Se eu tiver uma chance}
{373}{}{OK.}

# 17. Why PC ask Metzger (From 16)
{380}{}{Porque eu não quero que Tyler veja nenhuma das minhas pessoas entrando ou saindo do lugar de Metzger. Eu não quero dar uma gorjeta na nossa mão.}
{381}{}{Você não entendeu. Se Tyler me ver de repente, conversando com Metzger, ele pode apanhar algo de peixe.}
{382}{}{Veremos.}
{383}{}{OK.}

# 18. On Crate Quest (From WTG)
{390}{}{Então, você descobriu o que está lá?}
{391}{}{Compostos químicos brutos em grandes caixotes.}
{392}{}{Grandes recipientes que possuem produtos químicos de algum tipo.}
{393}{}{Ainda não.}

# 19. Ask/Permission (From WTG)
{400}{}{Então você falou com ele ainda? O que ele disse?}
{401}{}{Ele disse sim. Se você ganhar, você pode ter seu trabalho, como antes.}
{402}{}{N / D.}

# 20. Permission Done (From 19)
{410}{}{Ótimo. Eu estava esperando tanto. Eu ouvi dizer que ele se queixou recentemente sobre eles. Aqui está o seu dinheiro.}
{411}{}{Eu suponho que há algo mais agora?}
{412}{}{Obrigado. Tchau.}

# 21. Wait, need info… (From 20)
{420}{}{Tenho mais um emprego para você. Não tenho certeza de como você vai fazer isso, mas desde que você conseguiu entrar, talvez eles confiem em você.}
{421}{}{Eu entrei dentro.}
{422}{}{O que é isso?}

# 22. Snuck (From 21)
{430}{}{Tenho certeza que você pode descobrir algo.}
{431}{}{Ok, o que é isso?}

# 23. Setting Find (From 20-22)
{440}{}{Não podemos levá-los à força atual. Eles têm financiamento extra
 e um pouco depois nos conta nos. Se você pode encontrar algum tipo de fraqueza, podemos usar
 para equilibrar as probabilidades ou algo que possamos explorar ...}
{441}{}{Hã? Encontrar uma fraqueza? Como eu deveria fazer isso?}
{442}{}{Quantos?}
{443}{}{Considere isso feito.}

# 24. How Much? (From 23)
{450}{}{Nós vamos dar-lhe $ 150. Não há como chegar perto o suficiente para descobrir por nós mesmos.}
{451}{}{Se eu chegar a isso.}
{452}{}{OK.}

# 25. Weakness??? (From 23)
{460}{}{Eu não sei. É por isso que eu estou pedindo que você ajude.}
{461}{}{Vou tentar.}
{462}{}{Isso é inútil.}

# 26. Find/Weakness report (From WTG)
{470}{}{Você encontrou algo?}
{471}{}{Sim. Eles estão tendo uma festa esta noite.}
{472}{}{Ainda não. I'll let you know.}
{473}{}{Gra.}
{474}{}{N / D.}

# 27. Skeleton crew(From 4)
{480}{}{Excelente! Eles têm certeza de deixar uma equipe de esqueletos. Aqueles devem ser bons
 probabilidades. Vamos retirar aqueles na festa depois que atingimos a igreja.}
{481}{}{E meu dinheiro?}

# 28. Money ? (From WTG & 27)
{490}{}{Acho que não. Você terá que vir conosco se quiser o seu dinheiro. Você
 não terá que lutar, mas apenas para ter certeza de que não é uma armadilha. Vamos dar-lhe total de US $ 300.}
{491}{}{Esta pronto?}
{492}{}{Ok, vamos fazer isso.}
{493}{}{Me dê um pouco para se preparar.}
{494}{}{De jeito nenhum. Mantenha seu dinheiro!}

# 29. Wait to fight. (From 28, 30)
{500}{}{Ok, mas temos de agir em breve, então não demoremos ou vamos arruinar a nossa chance.}
{501}{}{OK.}

# 30. Coward (From WTG & 28)
{510}{}{Você não precisa lutar. Dinheiro fácil.}
{511}{}{Bem, você mudou de idéia?}
{512}{}{Vamos. Estou pronto.}
{513}{}{Okay, Eu volto já.}
{514}{}{Não.}
{515}{}{Reino Unido}

# 31. CF: No Show (From WTG)
{520}{}{Por causa de você, nossa chance.}
{521}{}{Covarde!}
{522}{}{Você não obteve nada.}
{523}{}{Provavelmente era uma armadilha de qualquer forma.}
{524}{}{Desculpe, você não é confiável.}
{525}{}{Não posso confiar em você.}

# 32. CF: 2 Won (From WTG)
{530}{}{Nós fizemos isso!}
{531}{}{Obrigado pela ajuda.}
{532}{}{Agradecimentos especiais para você!}
{533}{}{Eu finalmente paguei Tyler de volta pelo que ele fez com meu irmão.}
{534}{}{Obrigado novamente.}

# 33. CF: Metzger Dead (From WTG)
{540}{}{Agora, o Metzger está morto, eu não sei o que vai acontecer.}
{541}{}{Talvez devêssemos apenas arrumar.}
{542}{}{Você ouviu Metzger morreu? Não sei o que fazer agora.}
{543}{}{O que vai acontecer com o Den agora? Talvez algo melhor.}
{544}{}{Isso poderia ser para melhor.}

# 34. CF: Hostile (From WTG)
{550}{}{Desgraçado!}
{551}{}{Cadela!}

# 35. CF:  Reward (From WTG)
{560}{}{Obrigado. Aqui está o seu dinheiro e US $ 100 extra.}

# 36. Gang Dead (From WTG)
{570}{}{Você matou Tyler e seus guardas? Como devemos provar a Metzger? Ele nunca nos contratará agora. Essa foi a nossa única chance.}
{571}{}{Não temos nenhum trabalho. Alguém matou os guardas de Metzger e agora ele não vai falar conosco. Ele pensa que nós fizemos isso. Ah bem.}
{572}{}{Desculpa.}
{573}{}{Que pena.}
{574}{}{Foi eu, e você é o próximo.}
{575}{}{Oh. Tudo bem tchau.}
{576}{}{Uhr?}
{577}{}{Ug.}

# 37. Gang Dead Cont. (From 36)
{590}{}{Eu disse que iremos juntos. Como ninguém estava lá para assistir o lugar, ele foi saqueado e agora Metzger está mais louco do que o inferno.}
{591}{}{Eu disse para você encontrar uma fraqueza, e não matá-los! Como ninguém estava lá para assistir o lugar, ele foi saqueado e agora Metzger está mais louco do que o inferno.}
{592}{}{Droga! Eu disse para você pedir a Metzger para não matá-los! Como ninguém estava lá para assistir o lugar, ele foi saqueado e agora Metzger está mais louco do que o inferno.}
{593}{}{Droga! Eu disse para não atacá-los! Como ninguém estava lá para assistir o lugar, ele foi saqueado e agora Metzger está mais louco do que o inferno.}
{594}{}{Oh, bom, eu tenho que ir.}
{595}{}{Isso é uma vergonha.}
{596}{}{Você é o próximo, cadela.}
{597}{}{Hmph!}
{598}{}{Você é o próximo.}

# 38. CF: Next times Gang Dead (From WTG)
{610}{}{Você realmente sabe arruinar as coisas, não é?}
{611}{}{Não precisamos de mais ajuda.}
{612}{}{Vá incomodar outra pessoa.}
{613}{}{Metzger melhor não tira nada de nós.}
{614}{}{Eu sinto Muito. Não posso ajudá-lo.}
{615}{}{Não posso falar. Estou tentando descobrir o que fazer agora.}
{616}{}{Espero que a Metzger não pense que estivemos envolvidos.}
{617}{}{O que nós vamos fazer agora?}
{618}{}{É melhor irmos em breve caso o Metzger pense que matamos seus guardas.}
{619}{}{Você já esteve em New Reno? Talvez nós vamos lá - ou no norte.}

# 39. Running to Fight
{650}{}{Bem! Vamos! Todos me seguem!}
