# 0. Look
{100}{}{Você vê um guarda.}
{101}{}{Você vê Marc, um guarda.}
{102}{}{Você vê Marc, um dos guardas de Tyler.}

# 1. Door opened
{150}{}{Yo, Tyler!}

# 2. Hostile
{200}{}{O que…?}

# 3. Gang 1 Won War
{225}{}{Eu sabia que poderíamos levar esses coxins.}
{226}{}{Obrigado pela dica. Isso foi algo divertido.}
{227}{}{Muito ruim, nós os matamos a todos. Agora, o que devemos fazer?}
{228}{}{Estamos gostosos ou o quê?}
{229}{}{Nós somos muito bons.}
{230}{}{Nós cobramos uma bunda! Fuck yeah!}

# 4. TRAP NO
{250}{}{Tyler é a pessoa com quem falar, não eu, senhora.}
{251}{}{Estás bem. Você precisa de algo, você tem que falar com Tyler aqui.}
{252}{}{O que você está olhando?}
{253}{}{Tyler é o único com quem falar, não eu, cara.}

# 5. TRAP SET
{255}{}{Nós iremos chutar um bunda esta noite!}
{256}{}{Esta noite é a noite!}
{257}{}{Eu vou me lembrar desta noite com certeza.}
{258}{}{Nem me diga que eles estão sortidos.}
{259}{}{Oh, eu espero que esses fuckers mostrem.}

# 6. TRAP NOSHOW
{260}{}{Eu sabia que esses coxins não mostrariam.}
{261}{}{Nós devemos simplesmente ir chutar seus jumentos apenas por pensar em lutar contra nós.}
{262}{}{Nós teríamos rasgado por eles se tivessem mostrado.}
{263}{}{Eu poderia ter tomado por mim sozinho.}
{264}{}{Tyler e eu teríamos chutado um traseiro sério.}
