{100}{}{Você vê o proprietário do salão.}
{101}{}{Você vê Becky.}

{150}{}{Isso parece com o proprietário.}
{151}{}{Este é Becky, dono deste lugar.}
{152}{}{[CONVERSA]}
{153}{}{Olá, estranho, e bem-vindo ao meu salão. Sou Becky.}
{154}{}{Olá eu sou}
{155}{}{. O que há para fazer aqui?}
{156}{}{Oi eu sou}
{157}{}{. Posso fazer algumas perguntas?}
{158}{}{Mamãe?}
{159}{}{Mag gah.}
{160}{}{Corra junto. Não preciso do seu tipo aqui.}
{161}{}{Mmmm ...}
{162}{}{Dane-se.}
{163}{}{Vou.}
{164}{}{Desculpe, nenhuma ofensa foi feita. Posso perguntar algo?}
{165}{}{A bebida de whisky é de US $ 5 e as mesas de jogo estão bem ali. Tenha um bom.}
{166}{}{Posso fazer uma pergunta?}
{167}{}{Eu quero uma bebida!}
{168}{}{Hmm, são algumas bebidas baratas. Vamos ver um.}
{169}{}{Obrigado. Tchau.}
{170}{}{Vault 13? Não, nunca ouvi falar disso.}
{171}{}{Hmm, posso perguntar outra coisa?}
{172}{}{Porra, eu preciso encontrá-lo. Tchau.}
{173}{}{O que você gostaria de saber?}
{174}{}{Onde é um bom lugar para comer?}
{175}{}{Você sabe onde é o Vault 13?}
{176}{}{Por que suas bebidas são tão baratas?}
{177}{}{Nada. Tchau.}
{178}{}{A mãe corre um pequeno restaurante em toda a cidade.}
{179}{}{Mamãe! Mamãe!}
{180}{}{Mais uma pergunta.}
{181}{}{Obrigado. Tchau.}
{182}{}{Cai fora.}
{183}{}{Gwah.}
{184}{}{Eu vou te dar algo para vencer.}
{185}{}{Breve pergunta primeiro?}
{186}{}{Tchau.}
{187}{}{Um tiro de whisky é de US $ 5. Pague primeiro.}
{188}{}{Hã?}
{189}{}{Aqui está o dinheiro.}
{190}{}{Mudei de ideia.}
{191}{}{Estou um pouquinho de dinheiro. Posso ter uma guia?}
{192}{}{Posso fazer uma pergunta?}
{193}{}{Tenho que ir.}
{194}{}{Aqui está a bebida. Algo mais?}
{195}{}{Questão?}
{196}{}{Yeha, e você e eu ...}
{197}{}{Não.}
{198}{}{Ei, você não tem dinheiro suficiente para esta bebida. Você é mais pobre do que mesmo esses sops!}
{199}{}{Desculpa.}
{200}{}{Hmm, voltarei.}
{201}{}{Hmm. Deixe-me levar alguém a assistir o bar. Você e eu podemos entrar na sala das costas e jogar um pouco
 jogo que eu chamo de "First Strike". Se você é bom, bem, há "Ground Zero".}
{202}{}{ESTÁ BEM!}
{203}{}{Er ... uh ... eu tenho que ir.}
{205}{}{Você estava OK.}
{206}{}{Na próxima vez, vamos jogar "Into the Glow". Mas para agora...}
{207}{}{Você pode fazer algo para mim?}
{208}{}{Eu tenho que ir, mas vou voltar.}
{209}{}{O que posso fazer por você, bochechas doces?}
{210}{}{Eu preciso de mais um amor.}
{211}{}{Eu tenho algumas perguntas.}
{212}{}{Como você pode vender suas bebidas tão barato?}
{213}{}{Que tal uma bebida?}
{214}{}{Tenho que correr. Até mais.}
{215}{}{Agora não. Talvez mais tarde. Sim, definitivamente mais tarde.}
{216}{}{Posso fazer uma pergunta?}
{217}{}{Mais tarde, então.}
{218}{}{Eu tenho um ainda no porão. Eu fiz isso sozinho. Beats pagando triplo aos novos Reno
 gangsters.}
{219}{}{Garota inteligente Eu gosto disso!}
{220}{}{Hmm, tenho que ir. Vejo você mais tarde.}
{221}{}{Por quê? Por que você destruiu meu silêncio? Seu desgraçado!}
{222}{}{Nada pessoal. Eu paguei para fazê-lo.}
{223}{}{Eu sinto Muito.}
{224}{}{Tchau.}
{225}{}{Eu vou fazer outro, você sabe.}
{226}{}{Eu sei.}
{227}{}{Bem, isso é bom.}
{228}{}{Tchau.}
{232}{}{Por quê? Por que você destruiu meu silêncio? Sua cadela}

{233}{}{Onde está você, bebê?}
{234}{}{Você está vindo?}
{235}{}{Estou esperando.}
{236}{}{Estou aqui, amante.}

{237}{}{Tenho um bar para correr.}
{238}{}{Siga-me, açúcar.}

{240}{}{Como você ... Faça isso ... Uhhh ...}
{241}{}{É O.K. tamanho realmente não importa.}
{242}{}{Isso foi, hum, legal - eu acho.}
{243}{}{Obrigado, docinho; foi divertido.}
