# 0. Look
{100}{}{Você vê um lutador de meia-idade resistente.}
{101}{}{Você vê um escravo bastante grande.}

{150}{}{Há um escravo que parece aproveitar o trabalho dele.}
{151}{}{Este escravo parece ser muito forte, mas não brilhante.}

# 1. Metzger's Bedroom Guard (2nd Time = Hostile)
{200}{}{Retire-se da porta.}
{201}{}{Por que diabos você acha que está fazendo?}
{202}{}{Metzger terá sua cabeça. Retorna o homem.}
{203}{}{Ei, puta, afaste-se da porta.}
{204}{}{Nenhuma cadela está indo no quarto de Metzger. Recuar.}
{205}{}{Volte, puta. Slaver ou não, o quarto de Metzger está fora dos limites.}

# 2. CF: Generic
{250}{}{Fale com Metzger, não comigo, amigo.}
{251}{}{Você vai se juntar à guild?}
{252}{}{Há um bom dinheiro se você estiver na guilda.}
{253}{}{Você terá muita ação se estiver na guilda.}
{254}{}{Fale com Metzger, não comigo, senhora.}
{255}{}{Metzger não vai contratar uma cadela, então vença.}
{256}{}{Cai fora.}
{257}{}{E aí cara.}
{258}{}{Você tem sorte, você só precisa seguir as corridas.}
{259}{}{Ser um guarda de porta é uma vida chata.}
{260}{}{Como tá indo?}
{261}{}{Você é a primeira mulher que Metzger já contratou.}
{262}{}{Metzger deve ter um ponto fraco para você.}
{263}{}{Você é toda pequena, pequena senhora.}
{264}{}{Uma mulher escrava ... Nunca pensei em vê-lo.}
