# 0. Look
{100}{}{Você vê um homem malvado.}
{101}{}{Você vê Metzger, o slaver master.}

{150}{}{Metzger é o chefe da Slaver's Guild.}

# 1. CF: Hostile (From WTG)
{200}{}{Você pagará por isso.}

# 2. 1st Time, Self Initiated (From 2-WTG)
{210}{}{Que merda você quer? Esta é a Guild da Slaver não é segura
 Casa para você, jorra cabeça de jato.}
{211}{}{Que diabos você quer, sua cadela feia? Este é o Slaver's
 Guild não é uma merda de merda.}
{212}{}{Que diabos você quer, puta? Esta é a Guilda do Slaver não alguns
 porra da merda.}
{213}{}{Você está começando a me irritar. Que diabos você quer agora?}
{214}{}{E agora, porra?}
{215}{}{O que?}
{216}{}{Oh, é melhor você fazer isso rápido.}
{217}{}{Você está aqui para trabalhar por uma maldita mudança?}
{218}{}{Estou começando a me acostumar com sua caneca feia. Então ... você está aqui por uma razão ou o quê?}
{219}{}{Eu pareço seu papo maldito ou algo assim? Com certeza, espero que não. Agora cuspiu
 para fora, o que você quer?}
{220}{}{Oh, olha quem está aqui. Você acha que é especial ou algo assim? Fale ou obtenha o
 fuck out.}
{221}{}{O que você quer agora, slaver?}
{222}{}{Você vai ficar parado ou você vai dizer alguma coisa?}
{223}{}{Fala. Eu não tenho o dia inteiro por essa porcaria.}

# 3. Selling NPC (From 5, 13)
{230}{}{Ah, e 'quem' seria isso? Espero que você não planeje ver essa pessoa novamente ...}
{231}{}{Você não tem ninguém que eu esteja interessado. Só estou interessado em pessoas -
 normais, isso é.}
{232}{}{Você está louco, o que você acha que sou, uma merda ou algo assim? Se você pegar
 um escravo que você gostaria de vender, avise-me. Se você deseja vender outra coisa, vá para uma merda de loja.}
{233}{}{Miria}
{234}{}{Davin}
{235}{}{Vic}
{236}{}{Myron}
{237}{}{MacRae}
{238}{}{Sulik}
{239}{}{Posso fazer-lhe outra pergunta?}
{240}{}{Eu mudei de ideia. Tchau.}

# 4. Before PC responses (From ?Everywhere?)
{245}{}{Continue.}
{246}{}{Sim?}
{247}{}{Eu não sou seu maldito servo, então apresse-se.}
{248}{}{O que é isso? Eu não tenho o dia todo.}
{249}{}{Atire.}
{250}{}{Talvez.}

# 5. Main body, yes? (From 3)
{255}{}{Eu tenho algo que eu gostaria de vender.}
{256}{}{Sobre Vic ...}
{257}{}{Procuro um comerciante.}
{258}{}{Lara queria que eu pedisse permissão para lutar contra Tyler.}
{259}{}{Posso me juntar à guild?}
{260}{}{O que você pode me falar sobre sua aliança?}
{261}{}{Eu gostaria de seguir uma corrida de escravos.}
{262}{}{Deixa pra lá. Tchau.}
{263}{}{ quer doente.}
{264}{}{N / D.}

# 6. Want to join slaver's guild? (From 5, 7, 8)
{270}{}{Você acha que pode cortá-lo? Eu não aceito ninguém ... O que diabos. E se
 Você foda, eu vou te vender. Você terá que se tatuar na testa
 identificando você como um escravo para todos. É permanente, então não há pensamentos secundários.}
{271}{}{Então, nossa florinha delicada retorna ... Você mudou de idéia então?
 Vai começar essa tat depois de tudo?}
{272}{}{Sim, você pode fazer ... Você não precisa muito no caminho dos cérebros para correr.
 Se você fodar, eu só vou te vender. Se você acha que pode cortá-lo, você terá
 para se tatuar em sua testa identificando você a todos como escravas.}
{273}{}{Vamos fazer isso.}
{274}{}{Eu tenho que pensar sobre isso. Eu voltarei para você.}
{275}{}{Talvez não. Tchau.}
{276}{}{Uya! [aceno com a cabeça]}
{277}{}{Não não não não não!}

# 7. Tell me about Guild (From 4)
{285}{}{O que você pensa mal? Esta é uma aliança de escravos. Compre e venda escravos.}
{286}{}{Onde você consegue os escravos?}
{287}{}{Eu gostaria de me juntar.}
{288}{}{Outra pergunta, por favor.}
{289}{}{Oh, está bem. Tchau.}

# 8. Slaves from? (From 7)
{300}{}{Ah, aqui e ali. Recolhemos principalmente primitivos e nômades quando corremos por eles.}
{301}{}{Parece divertido. Como posso entrar nisso?}
{302}{}{Eu tenho outra pergunta.}
{303}{}{Oh, está bem. Tchau.}

# 9. Self Initiated, Just got Tattoo (From WTG)
{310}{}{O que você sabe, você nem sequer chorou. Estou tão orgulhoso de você ... na verdade, essa tatuagem
 parece muito bom com você. Apenas dê um grito quando estiver pronto para sua primeira corrida de escravos.}
{311}{}{Obrigado. Tchau.}
{312}{}{Estou pronto agora.}
{313}{}{Me matar AGORA!}
{314}{}{Entendido}

# 10. Slave Run (From 9)
{320}{}{Dois dos meus homens vão te aproximar dos seus objetivos. Seu salário será baseado
 no número dos escravos que você retorna, mas observe as costas dos outros. Se alguém
 é morto, seu salário será severamente cortado.}
{321}{}{Droga, todos somos criados. Tenho que esperar que alguns primitivos voltem para o
 área. Talvez devêssemos começar a criá-los.}
{322}{}{Desculpe, você não está apenas trabalhando. Muitas perdas e isso é um negócio. eu preciso
 para ganhar dinheiro, não o perca.}
{323}{}{Tudo certo. Eles estão prontos.}
{324}{}{Bom, você pode sair agora.}
{325}{}{Mova-se nisso então.}
{326}{}{Boa. Veja-me quando terminar.}
{327}{}{OK.}
{328}{}{Uh.}

# 11. Slave Run Description (From 10)
{340}{}{Apenas mata todos os hostis. Se eles atacarem, mata-os. Eu não
 quero lidar com eles mais, muito grande de um maldito problema. Depois de terminar,
 Os outros escravos irão arredondar e marcar o resto.}
{341}{}{OK.}
{342}{}{Oh.}

# 12. Slave Run Description 2 (From 11)
{350}{}{Uma vez que eles começam a marcar os escravos, você pode voltar atrás, se quiser. Leva
 treinamento especial, então não tente subjugar os outros você mesmo. Você pode fazer o que for
 Você quer tanto quanto não danificar a mercadoria.}
{351}{}{Tudo certo.}
{352}{}{Uh hein.}

# 13. Selling other NPCs (From 3)
{360}{}{Ah sim. Ela é muito legal. Vou dar-lhe $}
{1360}{}{ para ela. Que tal?}
{361}{}{Ele está bem. Eu provavelmente poderia tirá-lo de suas mãos, oh, diga $}
{1361}{}{?}
{362}{}{Você é idiota. O que diabos faz você pensar que eu quero aquele idiota de volta? Levou
 Ele para sempre para consertar um maldito rádio! Um rádio! Você está preso com ele. Eu não quero ele
 quebrando qualquer coisa por aqui.}
{363}{}{Eu não sei que este é muito magro ... mas um inteligente? Isso pode valer alguma coisa. Vou dar-lhe $}
{1363}{}{.}
{364}{}{Este parece ser realmente capaz de lutar. Hmm ... $}
{1364}{}{.}
{365}{}{Outro primitivo. Este é um show assustador. Ainda assim, ele parece forte e esse olhar pode extrair algo extra. $}
{1365}{}{?}
{366}{}{Que tal outra pessoa?}
{367}{}{Bem, deixe-me fazer-lhe outra pergunta, então}
{368}{}{OK.}
{369}{}{Bem.}
{370}{}{OK.}
{371}{}{Não vale a pena.}
{372}{}{Não.}

# 14. NPC Sold SPECIAL DIALOG (From 13)
{380}{}{Tudo bem, meninos, coloque-o nas canetas.}
{381}{}{Tudo bem, meninos, coloque-a nas canetas.}
{382}{}{Certo, chefe.}

# 15. Turned down Selling NPC (From 13)
{390}{}{Bem, não perca a minha puta vez. Se você alguma vez conseguir algo, você é
 Olhando para se separar, venha me ver.}
{391}{}{Tenho outra pergunta para você.}
{392}{}{OK. Bye.}

# 16. Permission (From 5)
{400}{}{O que diabos arrastou seu traseiro de repente? Eu dei a essa cadela uma chance
 um tempo atrás. Não achava que ela tinha as bolas para tentar isso.}
{401}{}{Do que você está falando?}
{402}{}{Então está tudo bem?}

# 17. What kind of outfit… (From 16)
{410}{}{Oh, não tocas comigo. Eu sei exatamente o que ela planeja fazer. Eu
 deu-lhe uma chance por um tempo atrás e ela não conseguiu cortá-lo, mas se ela
 acha que ela está de acordo com isso ...}
{411}{}{Então está tudo bem?}

# 18. Então está tudo bem? (From 17)
{420}{}{Bem, eu disse que a oferta permaneceria aberta. Se ela finalmente pensa que ela pode chutar sua bunda e
 é melhor capaz de proteger minha merda ...}
{421}{}{Bem?}
{422}{}{Então, esse é um sim?}

# 19. Permission Granted (From 18)
{430}{}{Olha, eu não dou uma merda que deles a protege. Apenas enquanto nenhum dos meus bens for
 danificado, eu não ligo.}
{431}{}{Outra pergunta, por favor.}
{432}{}{Ok, obrigado.}

# 20. I'm looking for a Merchant (From 5, 20)
{440}{}{Por que você está me pedindo? Parece um tipo de merda ... oh,
 esperar. Você provavelmente está procurando Vic?}
{441}{}{Ele é aquele que se "especializa" na tecnologia do vault, ou então ele diz. Ele é meu
 propriedade agora. Ele não vai a lugar nenhum.}
{442}{}{E ele?}
{443}{}{Sim, é ele.}
{444}{}{Posso vê-lo?}
{445}{}{Por que você está mantendo ele aqui?}
{446}{}{Ok, obrigado. Bye.}

# 21. Radio Fix/Not Fixed (From 20)
{455}{}{Essa coxa - ele me vendeu um rádio que ele disse que seria capaz de pegar
 algumas transmissões. Não foi. Eu peguei sua bunda tentando fugir da cidade antes
 Eu descobri. Erro negativo. Ninguém foda comigo. Ele tem sorte de estar vivo.}
{456}{}{Como eu disse. Ele precisa corrigir algo primeiro. Depois disso, veremos.}
{457}{}{Bem, ele finalmente conseguiu esse maldito rádio para trabalhar, mas isso não significa que eu vou deixar
 Ele é tão fácil.}
{458}{}{Ele ainda tentou me ferrar.}
{459}{}{Posso vê-lo?}
{460}{}{De que tipo de transmissão você está falando?}
{461}{}{Ok, obrigado.}
{462}{}{Talvez algum dinheiro possa ajudar a esclarecer as coisas?}
{463}{}{De que tipo de transmissões você estava falando antes?}

# 22. Set See Vic is Okay (From 20-21)
{475}{}{Pelo que? Ah, foda, não importa. Apenas não o impede de corrigir essa droga
 rádio - e ele melhorá-lo em breve. Estou cansado de alimentar seu traseiro preguiçoso.}
{476}{}{Por que você está mantendo ele aqui?}
{477}{}{Obrigado.}

# 23. Transmissions (From 21)
{485}{}{O Enclave e o Novo ... ei. O que diabos você se importa? É um negócio. Preciso ter certeza de que ninguém está tentando me foder. Isso é tudo o que você precisa saber.}
{486}{}{Não é da tua conta.}
{487}{}{OK.}

# 24. Pay for Vic (From 21, 23)
{495}{}{Claro, mas isso vai custar-lhe $}
{496}{}{$}
{1496}{}{.}
{497}{}{Não podemos resolver algo?}
{498}{}{OK. Here.}
{499}{}{Posso fazer-lhe mais algumas perguntas.}
{500}{}{Desculpe, não posso pagar isso ainda.}

# 25. Bought Vic (From 24)
{510}{}{Certo, ele é seu, mas tire seu traseiro daqui antes de mudar de idéia
 e coloque uma bala naquela cabeça idiota dele.}
{511}{}{Posso fazer mais algumas perguntas?}
{512}{}{Obrigado.}

# 26. Female Sex (From 24)
{520}{}{Ai sim. Podemos trabalhar tudo legal e suave ... Eu vou te dar
 Meia parte se você ganhar a pena ...}
{521}{}{Você deveria parar de me provocar, feminino. Não tenho muita paciência.}
{522}{}{Somente se você é bom para mim.}
{523}{}{Claro, por que não.}
{524}{}{Talvez mais tarde.}

# 27. Good to me (From 26)
{530}{}{Oh, é melhor acreditar.}
{531}{}{Boa.}

# 28. Paying for Run (From WTG)
{540}{}{Aqui está $}
{1540}{}{. Muito bom trabalho.}
{2540}{}{.}
{541}{}{Aqui está o seu $}
{1541}{}{. Você chutou um traseiro sério. Mantem.}
{542}{}{Good job out there. Aqui está $.}
{1542}{}{.}
{543}{}{Aqui está o seu dinheiro.}
{1543}{}{$ $.}
{2543}{}{.}
{544}{}{$.}
{1544}{}{ não é algo para rir, mas você não pode fazer muito mais do que isso.}
{545}{}{Bem, é $}
{1545}{}{ desta vez. Muito bom trabalho.}
{546}{}{It wasn't that tough, now was it? Next time no mistakes. Aqui está $.}
{1546}{}{.}
{547}{}{$}
{1547}{}{? Não é ruim.}
{548}{}{Vamos! $.}
{1548}{}{? Você pode fazer melhor do que isso.}
{549}{}{Remember, watch each other's backs and only kill the hostile slaves. Aqui está $.}
{1549}{}{.}
{550}{}{Apenas $.}
{1550}{}{! Isso é pitiful! Mude-se ou vou chutar o seu traseiro.}
{551}{}{Você quer ganhar dinheiro ou não? Você está me irritando. Como fodido
 pode ser difícil? Agora pegue seus $.}
{1551}{}{ e saia.}
{552}{}{Qual foi o seu problema? Você não ganha merda desta vez. Estamos
 Nisso, para ganhar dinheiro, não dick around.}
{553}{}{Eu vou fazer melhor na próxima vez.}
{554}{}{Obrigado por nada.}
{555}{}{obrigado}
{556}{}{Ug.}

# 29. (From WTG)
{570}{}{Maldita puta, foi a sua primeira vez? Não havia como não ser a sua primeira vez.}
{571}{}{Maldita garota, foi a sua primeira vez?}
{572}{}{Muito bom, acho.}
{573}{}{Muito bom, talvez possamos fazê-lo novamente em algum momento.}
{574}{}{Droga! Isso foi ... dinheiro muito bem gasto.}
{575}{}{Droga! Você foi o melhor pedaço de culo que já tive, e eu tive muito.}

# 43. Abandon Slave Run
{600}{}{VOCÊ FUCK ESTÚPIDO! Como você ousa abandonar seus companheiros de escravos lá fora. [Esmaga em seu rosto] MATÁVEL-LHE!}
{601}{}{Mas eu...}
{602}{}{Tudo bem, vamos fazer isso.}

# 30. Returned from run, attacked slaver and lived to tell about it. (From WTG)
{620}{}{Bem, é bom ver que você poderia recuperar.}
{621}{}{Sim, foi uma corrida difícil.}
{622}{}{Obrigado. Things got a little harry out there.}
{623}{}{Agra Moo ne!}

# 31. Dumb hostile run (From 30)
{630}{}{Ah, quer dinheiro? Você quer ser pago?}
{631}{}{Yah.}
{632}{}{Ugh.}

# 32. Dumb 2 (From 31)
{640}{}{É claro que EU AMEi ajudá-lo, mas ... há esse pequeno problema que eu tenho ... algo sobre atacar um dos meus homens.}
{641}{}{Desculpa! Eu não quis dizer ... Quero dizer ... Ug?}
{642}{}{Uh, oh.}

# 33. Dumb 3 (From 32)
{650}{}{Oh, não se preocupe. Tenho certeza de que posso encontrá-lo no meu coração para pagar - quero dizer, pagar você. Homens, é dia de pagamento.}
{651}{}{Oh, não se preocupe. Tenho certeza de que posso encontrá-lo no meu coração para pagar - quero dizer, pagar você. Homens,
 tire esta cadela para baixo.}
{652}{}{Oops.}
{653}{}{Garaka!}
{654}{}{Uh ... Tank?}

# 34. Tough run, hostile (From 30)
{670}{}{Tenho certeza. Esta linha de trabalho não deve ser tomada levemente. É preciso confiança e lealdade. Nós observamos as costas uns dos outros. Boa política, não acha?}
{671}{}{Eu acho.}
{672}{}{Uh, o que está acontecendo?}
{673}{}{Definitivamente.}

# 35. I guess (From 34)
{680}{}{Você acha? Eu não pensei que você era tão inteligente. Você realmente é uma merda estúpida.
 [Metzger olha para você, então olha para seus guardas e movimentos em sua direção.]}
{681}{}{Ações?}
{682}{}{O que?}

# 36. What's going on? (From 34)
{690}{}{Oh, então você não é tão burro quanto você age. Bem, isso é uma vergonha. Você vê, estou tendo um pouco de dilema. Alguém teve a coragem de atacar meus homens.}
{691}{}{Mesmo?}
{692}{}{Foi um acidente!}

# 37. Definitely (From 34)
{700}{}{Mesmo? I'm so glad you agree. Now what would you do if someone betrayed this trust?}
{701}{}{Uh, dar-lhes um aviso?}
{702}{}{Aqui. Deixe-me te mostrar. [ataque]}
{703}{}{Faça com que paguem.}

# 38. Trust, warn? (From 37)
{710}{}{Você acha? Honestamente? Eu não sei. Eu estava pensando em algo um pouco mais ... permanente. [Com um sorriso malvado, Metzger olha para seus guardas e acena com a cabeça.]}
{711}{}{O que?}
{712}{}{Oh garoto…}

# 39. Trust Pay? (From 37)
{720}{}{Fico feliz por termos concordado. [Metzger olha para seus guardas.] Homens, é dia de pagamento.}
{721}{}{Uh ...}

# 40. Mesmo? (From 36)
{730}{}{Sim. É uma vergonha realmente. Essa pessoa simplesmente não parece obtê-lo, mas
 Eu acho que eles estão prestes a. [Você vê Metzger fazendo um pequeno gesto à mão para o dele
 homens.] Tempo de jogo.}
{731}{}{Sério?}
{732}{}{Uh oh.}

# 41. Accident? (From 36)
{740}{}{Sim, tenho medo que os acidentes ocorram por aqui com bastante frequência. Na verdade, eu tenho medo de termos outro. [Metzger sorri agradavelmente e depois acena com os homens.]}
{741}{}{Pode vir!}
{742}{}{Não estou saindo disso sou eu?}

# 42. Getting out? (From 41)
{750}{}{Ah, mas isso será divertido. Confie em mim.}
{751}{}{Foda-se.}
{752}{}{Uh, está bem.}

{800}{}{Você matou o líder do Slave Guild.}
