# 0. Look
{100}{}{Você vê uma mulher mais velha de aparência gentil.}

{150}{}{Você vê a mãe, ocupada cozinhando e limpando.}
{151}{}{Você vê uma mulher mais velha e robusta, com um sorriso alegre no rosto.}

# 1. Low Intelligence (WtG)
{200}{}{Olá, eu sou mãe. Eu não vi você por aqui antes.}
{201}{}{Olá de novo. O que a mãe pode fazer por você?}
{202}{}{Eu .}
{203}{}{Mmmm. Ook? Tchau, mamãe.}

# 2. Low IQ more (1)
{220}{}{Você já me comeu fora de casa e em casa. Por que não encontrar outro lugar para sair por um tempo? Você já comeu aqui o suficiente hoje.}
{221}{}{Bem.}
{222}{}{ você com certeza parece como se estivesse confundido. Odeio ver uma besta sofrer. Quer comer alguma coisa?}
{223}{}{Estou cheio. Comida de mãe boa. Tchau mãe.}
{224}{}{Eu pago?}
{225}{}{Eu vou. Tchau mãe.}

# 3. Pay? (2)
{240}{}{Bem ok. O que você tem? (Mãe alcança sua bolsa)}
{241}{}{Mamãe? (você aguenta sua bolsa)}
{242}{}{Não! Eu vou. Tchau, mamãe.}

# 4. No, not really (7,9)
{250}{}{Não, na verdade não. Eu sinto Muito. Nós apenas temos torta de rato, pão de rato e espaguete.}
{251}{}{O que será essa vez?}
{252}{}{Uh, eu poderia conseguir algo sem tanto rato nisso?}
{253}{}{Eu acho que vou ter o pão de rato.}
{254}{}{Eu acho que vou ter a torta do rato.}

# 5. Not so much rat in it (4)
{270}{}{Você poderia ter o espaguete. Não tem muito rato nele - apenas o molho, isso é tudo.}
{271}{}{Bem, ok, acho que vou ter o espaguete com molho de rato.}

# 6. Here's your food (4,5)
{280}{}{Eu terei uma boa ajuda de imediato. Isso será $ 10.}
{281}{}{Não tenho dinheiro suficiente agora. Deixe-me fazer uma pergunta em vez disso.}
{282}{}{$ 10 para o rato? Você deve estar louco. Porra, ao redor da aldeia, cobramos muito mais por uma boa suculenta. Isso é um acordo.}
{283}{}{Bem ok. Aqui está o seu dinheiro.}
{284}{}{Eu acho que eu mudei de idéia. Deixe-me fazer uma pergunta em vez disso.}
{285}{}{Penso que vou voltar mais tarde. Adeus.}

# 7.  Thanks Mom (6,20)
{300}{}{Você tem bastante apetite lá. Adoro ver um comedor saudável. Isso o fará por você?}
{301}{}{Não é uma chance, mãe. Quero segundos.}
{302}{}{Certamente. Deixe-me perguntar-lhe uma coisa, mãe.}
{303}{}{É por enquanto. Adeus, mãe.}

# 8. What's there to do here? (13)
{320}{}{Bem, eu preciso de alguém para entregar uma refeição a Smitty. Ele está apenas a oeste daqui no junkyard. Você fará isso por mim? Eu vou te dar uma refeição grátis se você fizer.}
{321}{}{Claro, não me importo.}
{322}{}{Deixe-me pensar sobre isso. Enquanto isso, deixe-me perguntar-lhe sobre outra coisa.}
{323}{}{Uh, desculpe, mãe. Não posso. Adeus.}

# 9. Random Food item list (13)
{340}{}{Você está com sorte. Nós estamos tendo utensílio de radscorpion.}
{341}{}{Estamos tendo porco-rato assado.}
{342}{}{Estamos servindo caudas de radscorpion ao vapor na manteiga desenhada.}
{343}{}{Sopa de repolho é tudo o que tenho agora.}
{344}{}{Fritadas de brahmin frescas!}
{345}{}{Torta de gecko quente de Pipin, chegando.}
{346}{}{Flank steak.}
{347}{}{Molerat bem marmoreado.}
{348}{}{Flutuador Fricasseed.}
{349}{}{Filet mignon.}
{350}{}{Medalhões de gecko grelhado.}
{351}{}{Mantis Marsala.}
{352}{}{Molerat manicotti.}
{353}{}{brahmin en brochette.}
{354}{}{Radscorpion en croute.}
{356}{}{Uh, não tenho certeza, mas gosto de frango.}
{357}{}{Centaur chops, minha especialidade.}
{358}{}{É uma surpresa.}
{359}{}{É Smeat!}
{360}{}{Mesmo?}

# 10. Low IQ hand food (3)
{375}{}{Aqui está. Você está meio morto de fome. (Mãe lhe entrega um grande prato fumegante de deliciosos alimentos cheirosos).}
{376}{}{Tank-u, mãe.}

# 11. Low IQ fed (10)
{385}{}{Ai está. Eu sabia que você iria gostar disso.}
{386}{}{Mmm, yum yum. Tchau mãe.}

# 12. Sure I'll deliver it (8)
{395}{}{Muito obrigado. Eu faria isso sozinho, mas não há ninguém para assistir o lugar enquanto eu vou embora. Aqui está a refeição de Smitty. Se eu não tivesse trazido para ele, eu tenho certeza que ele esqueceria de comer.}
{396}{}{Vou trazê-lo diretamente para ele.}

# 13. Hello (WtG, 6,7,8,15,18)
{405}{}{Estou tão decepcionado com você. Pobre Smitty teve que vir buscar sua própria refeição. Agora, o que você quer?}
{406}{}{Olá, meu nome é mãe e eu corro esse lugar. Tem a melhor comida ao norte de New Reno, também.}
{407}{}{Com o que você queria falar com mamãe?}
{408}{}{Você não é minha mãe.}
{409}{}{Você já ouviu falar de um Vault ou de alguém chamado Vic?}
{410}{}{O que há para fazer aqui na cidade?}
{411}{}{O que você tem para comer aqui?}

# 14. I'm not your mom (13)
{425}{}{Eu sei disso. Mas todos me chamam disso. Heck, eu até tratar as pessoas como se fossem meus parentes - enquanto você obedecer minhas regras.}
{426}{}{Regras?}

# 15. Regras? (14)
{435}{}{Está certo. Sem roubar, sem xingamento e sem luta - não na minha loja, você não. Porque se você fizer isso, você vai embora. Eu gosto de coisas pacíficas aqui.}
{436}{}{Entendo. Deixe-me perguntar-lhe outra coisa.}
{437}{}{Isso faz sentido. Vejo você mais tarde, mãe.}

# 16. Vic or Vault? (13)
{445}{}{Bem, agora, há uma Cidade de Vault um caminho a leste daqui e um pouco a norte. E Vic, hmm, pensa lemme.}
{446}{}{Espero que você saiba onde é Vic. Ele é um comerciante.}
{447}{}{Obrigado, mas é tudo o que preciso saber. Tchau mãe.}

# 17. Trader Vic (16)
{455}{}{Trader Vic? Agora isso soa um sino. Sim, acho que ele está sendo atendido por Metzger por algum motivo.}
{456}{}{Quem é o Metzger e onde o encontro?}
{457}{}{Isso é ótimo, mãe. Obrigado.}

# 18. Who's Metzger (17)
{465}{}{Metzger é o chefe da Guilda local da escrava. Ele tem todos os tipos de pessoas presas em seu lugar. Está bem na rua, ao norte daqui.}
{466}{}{Metzger costumava ser o chefe do Slaver's Guild local. Ele tinha todos os tipos de pessoas presas em seu lugar. Mas eu não sei agora - eu ouvi dizer que ele foi morto.}
{467}{}{Obrigado pela informação. Deixe-me perguntar-lhe outra coisa, mãe.}
{468}{}{Eu preciso ir cuidar de algum negócio. Obrigado, mãe.}

# 19. Smitty's meal in progress (WtG)
{475}{}{Vá em frente e obtenha essa refeição para Smitty agora.}
{476}{}{Eu não vou ajudá-lo até você manter sua palavra.}
{477}{}{Apresse-se agora.}
{478}{}{Vá dar a Smitty sua refeição. Se apresse.}
{479}{}{Pare o seu lollygaging e obtenha essa refeição para Smitty.}

# 20. Reward (WtG)
{485}{}{Foi um bom trabalho. Você deve ter feito bastante apetite.
 Tenho um verdadeiro deleite para você como uma recompensa. Uma placa combinada do melhor
 comida maldita que eu tenho aqui, só para você.}
{486}{}{Isso parece ótimo! Deixe-me falar com isso!}
{487}{}{Gee, mãe. Eu não acho que posso comer agora mesmo, mas obrigado de qualquer maneira. Adeus.}

# 21. O que você sabe sobre essa casa assombrada? (13)
{500}{}{Hmm, não sei muito sobre isso. Alguém provavelmente está apenas tendo
 um pouco divertido, é só isso.}
{501}{}{Sempre foi assombrada?}
{502}{}{Alguém usa essa casa?}
{503}{}{Concordo. Tchau.}

# 22. Started 2 years back… (21)
{520}{}{Iniciou cerca de 2 anos atrás. Ouvi sobre os gemidos e os espíritos e tudo mais.
 Não acredite em mim mesmo.}
{521}{}{Dois anos, hein? Alguém usa o lugar naquela época?}
{522}{}{Nem eu. Obrigado.}

# 23. Anyone used it then? (21-22)
{540}{}{Um dos meninos costumava dormir há alguns anos atrás. Talvez ele saiba algo.}
{541}{}{Quem?}
{542}{}{Provavelmente não. Tchau.}

# 24. Quem? (23)
{560}{}{Ele costumava passar e tentar pegar coisas. Jóias principalmente. Eu lembro
 um pequeno medalhão de ouro que ele guardava para si mesmo.}
{561}{}{Você se lembra do nome dele?}
{562}{}{Medalhão? Estranho. Quem foi?}
{563}{}{Deixe-me perguntar-lhe outra coisa.}
{564}{}{Obrigado tchau.}

# 25. Name? (24)
{580}{}{Não tenho certeza. Pense que era Joseph, Joel ou algo assim. Ele tem quase 19 anos
 agora ... uma vergonha, na verdade. Eu acredito que ele se juntou a alguns bandidos locais.}
{581}{}{Obrigado. Eu tenho outra pergunta para você.}
{582}{}{Obrigado tchau.}

# 13b. PC Responce line added to node 13
{600}{}{O que você sabe sobre essa casa assombrada?}
