# 0. Look
{100}{}{Você vê um escravo.}

{150}{}{Ele parece estar muito alerta.}

# 1. Messed with Door 2nd Time
{200}{}{Toque isso novamente e você perderá um membro.}
{201}{}{É isso aí!}

# 2. CF: Not Slaver
{210}{}{Nada além dos escravos estão lá.}
{211}{}{Os escravos não recebem visitantes.}
{212}{}{Somente membros da aliança através desta porta.}
{213}{}{Você está procurando um escravo? Fale com Metzger.}
{214}{}{Fale com Metzger. As canetas escravas estão fora dos limites.}
{215}{}{Por que você está vagando por aqui? Cai fora.}
{216}{}{Bata, cadela. Os escravos não recebem visitantes.}

# 3. CF: Slaver
{230}{}{Como está indo, amigo?}
{231}{}{Pouco lento hoje.}
{232}{}{Espero que você esteja gostando da aliança.}
{233}{}{Seu tat saiu bem.}
{234}{}{Você passou na última corrida?}
{235}{}{Oi.}
{236}{}{Você é meu tipo de senhora.}
{237}{}{Uma escrava feminina - conseguiu respeitar isso.}
{238}{}{Olá.}
{239}{}{Parece bom.}
