#############################################################
#                                                           #
#  Message File: dcPetey.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 12, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and examined.                                    #
#############################################################

{100}{}{Você vê um químico dependente.}
{101}{}{Você vê Petey.}

{150}{}{Este é um pobre dependente de químicos.}
{151}{}{Petey aqui parece que ele poderia usar alguma ajuda.}
{152}{}{[conversa]}
{155}{}{[tosse, tosse] Alguma mudança de reposição para Petey?}
{156}{}{Claro, aqui você vai.}
{157}{}{Não, afaste-se de mim.}
{158}{}{Peewee?}
{159}{}{Você está pior do que eu. [tosse] Obrigado de qualquer maneira.}
{160}{}{Desculpa; tchau.}
{161}{}{Duh, você é bem-vindo, uh-huh, sim.}
{162}{}{Talvez na próxima vez. Obrigado mesmo assim. [tosse]}
{163}{}{[feito]}
{164}{}{Muito obrigado. [tosse] Então, então, muito.}
{165}{}{Seja bem-vindo.}
{166}{}{Sim sim.}
{167}{}{Senhor, [tosse] você pode ajudar um homem pobre na sua sorte?}
{168}{}{Aqui estão $ 5.}
{169}{}{Hoje nao.}
{170}{}{Arrume um emprego.}
{171}{}{Senhora amável, ajude [tosse] a um homem pobre e faminto que está [tossinho] muito doente para trabalhar.}
{172}{}{Você é pobre, aqui tem US $ 5.}
{173}{}{Eu faço questão de não dar dinheiro aos manipuladores de mão.}
{174}{}{Não.}

{200}{}{E aí cara; me dê algum dinheiro?}
{201}{}{Poupe alguma mudança, senhor amável?}
{202}{}{Ei, você pode me ajudar com alguns dólares?}
{203}{}{Você acha que pode me ajudar com um coupla de dólares?}
{204}{}{Você acha que poderia me emprestar alguns dólares?}
{205}{}{Poupe alguma mudança, senhora gentil?}
{206}{}{Ei moça; poupar algum dinheiro?}

{220}{}{Por favor me ajude, senhor.}
{221}{}{Ahhh, dói.}
{222}{}{Eu preciso de ajuda. Dói muito.}
{223}{}{Senhora, você pode me ajudar?}

{225}{}{Eu aprecio muito isso.}
{226}{}{Ei, o que você acha que está fazendo?}

{230}{}{Parece tão bom.}
{231}{}{Uhhh ...}
{232}{}{[risadinha]}
{233}{}{Ei...}

#dealer dead messages
#tubby dead
{300}{}{Ahhh, alguém diabos matou Tubby?}
{301}{}{O que diabos aconteceu com Tubby?}
{302}{}{Oh merda, Tubby's ...}
#generic
{303}{}{Ahhh...}
{304}{}{Na verdade, não gostava desse idiota.}
#flick dead
{305}{}{Flick está morto? Porcaria.}
{306}{}{O que aconteceu com o Flick?}
{307}{}{Estalido...}

#dealer far, ask for assistance
#ask tubby
{310}{}{Ei, Tubby, eu, Uhhh, precisamos de ajuda aqui.}
{311}{}{HEY TUBBY!}
#ask any
{312}{}{Olá.}
{313}{}{EI!}
#ask flick
{314}{}{Hey Flick, eu, Uhhh, preciso de ajuda aqui.}
{315}{}{HEY FLICK!}

#ask dealer for drug messages
#from tubby
{320}{}{Ei, Tubby, você pode me ligar? Eu tenho dinheiro.}
{321}{}{Ummm, Tubby, tenho dinheiro.}
#from any
{322}{}{Uhhh ...}
{323}{}{Preciso de um homem reparador.}
#from flick
{324}{}{Ei, Flick; você pode me ligar? Eu tenho dinheiro.}
{325}{}{Ummm, Flick, eu tenho um pouco de dinheiro.}

#thank dealer for drugs messages
#thank tubby
{330}{}{Uhhh ... Thanks again, Tubby.}
{331}{}{Você é um amigo, Tubby.}
#thank generic
{332}{}{Eu prometo. Vou matar amanhã.}
{333}{}{Você é um amigo.}
#thank flick
{334}{}{Uhhh ... Thanks again, Flick.}
{335}{}{Você é um amigo, Flick.}
