#0. Look
{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda do Becky's Casino Bar.}
{150}{}{Ele parece estar atento a esta porta.}

#1. CF: Hostile
{200}{}{Você não está saindo tão fácil.}

#2. CF: Generic
{210}{}{Isto é para o quarto de Rebecca. Ninguém é permitido.}
{211}{}{Espero que você esteja se divertindo.}
{212}{}{Você está procurando por Becky? Ela está ali mesmo.}
{213}{}{Oi.}
{214}{}{Desfrute das mesas.}
{215}{}{Becky tem as bebidas mais baratas da cidade.}

#3. Self Initiated: Door tampered with
{230}{}{Afaste-se disso agora mesmo.}
{231}{}{Não toque nisso novamente.}
{232}{}{Recuar!}
{233}{}{Deixe isso sozinho.}
{234}{}{O que você pensa que está fazendo?}

#4. Self Initiated: Door opened
{240}{}{Ladrao!}

#5. Self Initiated: Caught Stealing.
{250}{}{Nós não toleramos isso aqui.}

# left post message
{300}{}{Baby, você está fazendo alguma coisa depois do trabalho?}
{301}{}{Você está bem, como sempre.}
{302}{}{Você realmente sabe como correr a mesa, querida.}
{303}{}{Ei, querida, você pode pegar esses dados de novo? Adoro o jeito que você se move.}
{304}{}{Ei. Como está indo, doçura?}
{305}{}{Então ... você e eu ... depois do trabalho?}
{306}{}{Becky pode me dar amanhã se você estiver ... disponível.}
{307}{}{Eu sempre lhe disse quais belos olhos você tem?}

# leaving message
{350}{}{Você me ignora de novo. Dois podem jogar esse jogo.}
{351}{}{O que? Você ainda chateou comigo?}
{352}{}{Você está fazendo um bom trabalho ... continue com seu trabalho ...}
{353}{}{O que? Você me ignora de novo?}
{354}{}{Você está ocupada ... entendo. Vamos conversar mais tarde.}
{355}{}{Cara, você sabe como jogar duro para conseguir.}
{356}{}{Eu vou ... uh, fale com você depois disso.}
{357}{}{Bastante falando com você também ... Eu vou estar voltando para lá, então.}

# door open
{375}{}{Ah Merda...}
