#0. Look
{100}{}{Você vê um guarda.}
{101}{}{Você vê um guarda do Becky's Casino Bar.}
{150}{}{Ele parece estar olhando a multidão para ladrões.}
{151}{}{Ela parece estar atenta a todos na sala.}

#1. Hostile
{200}{}{Agora você conseguirá.}
{201}{}{Você não está fugindo desta vez.}

#2. CF: Generic
{210}{}{Desculpe, Becky não quer que nos perturbe os clientes.}
{211}{}{Espero que você esteja se divertindo.}
{212}{}{Tenha certeza, temos uma política de tolerância zero para o roubo.}
{213}{}{Você está seguro dentro dessas paredes.}
{214}{}{Rebecca tem as melhores bebidas.}
{215}{}{Rebecca é o melhor chefe que já tive.}
{216}{}{Você está com sorte hoje a noite? Blackjack é o meu jogo.}
{217}{}{Becky está bem ali, se precisar de alguma coisa.}
{218}{}{As mesas de Rebecca são honestas, então tente sua sorte.}

#3. Self: Caught Stealing
{230}{}{Nós não toleramos isso aqui.}
