# 0. Look
{100}{}{Você vê uma jovem jovem muito atraente.}
{101}{}{Você vê Rebecca.}

{150}{}{Você vê Rebecca, dono do Becky's Casino Bar.}

# 1. Greetings (From WTG)
{200}{}{Oi, eu sou Rebecca. Posso pegar algo para beber? Tenho certeza de que você está com sede
 Depois da sua viagem pelos resíduos.}
{201}{}{Ei! Você quer uma bebida ou você acabou de voltar para dizer oi?}
{202}{}{Oi! Fico feliz que você voltou. Qualquer dúvida ou você está aqui para algum whisky fino?}
{203}{}{Realmente feliz em vê-lo. Estás bem? Preciso de algo?}
{204}{}{Espero que tudo esteja indo bem para o meu cliente favorito! O que podemos fazer por você hoje?}
{205}{}{Olá!}
{206}{}{Sempre prazer em vê-lo novamente.}
{207}{}{Oi! Você se importa com uma bebida? O uísque mais fino da terra!}
{208}{}{Olá!}
{209}{}{É você! Eu pensei assim. Que tal uma bebida, meu querido?}
{210}{}{Você volta para o grande entretenimento de Rebecca ou o whisky mundialmente famoso?}
{211}{}{Bem-vindo ao Rebecca's Bar and Casino. Como posso ajudá-lo?}
{212}{}{Olá. como podemos te ajudar?}
{213}{}{Alguma coisa para você hoje? Que tal uma bebida?}
{214}{}{Você se importaria com uma bebida hoje, ou talvez alguma outra coisa?}
{215}{}{Como posso ser útil?}
{216}{}{Saudações. O que podemos fazer com você?}
{217}{}{Preciso de algo?}
{218}{}{Prazer em vê-lo novamente. Como posso ajudá-lo hoje?}
{219}{}{O que?}
{220}{}{Sim?}
{221}{}{O que agora?}
{222}{}{Mantenha-o curto. É um dia atarefado. O que você precisa?}
{223}{}{O que posso fazer para você? Estou realmente ocupado.}
{224}{}{Você está aqui para tomar uma bebida? As mesas estão por aí.}
{225}{}{Eu realmente não estou com vontade. E agora?}
{226}{}{Você já está de volta? Eu acho que você quer uma bebida, então?}

# 2. Prelude to questions (From ?)
{240}{}{Claro, bonito.}
{241}{}{O que você gostaria de saber?}
{242}{}{Eu ficaria feliz.}
{243}{}{Mas é claro.}
{244}{}{Certo.}
{245}{}{Não me importo.}
{246}{}{Eu vou ajudar se eu puder.}
{247}{}{Claro, não seja bobo.}
{248}{}{Qualquer coisa. Agora, o que era?}
{249}{}{Vou fazer o meu melhor para ajudá-lo. O que você precisava saber?}
{250}{}{Pergunta à vontade.}
{251}{}{Se você insiste.}
{252}{}{Eu acho.}
{253}{}{Vamos ficar curtos. Eu tenho um negócio para correr.}
{254}{}{Bem, tudo bem. O que é isso?}
{255}{}{Eu suponho.}
{256}{}{O que?}
{257}{}{Não, desculpe.}
{258}{}{Não agora.}

# 3. Questions (From 1-2)
{270}{}{Eu preciso de uma bebida.}
{271}{}{Estou à procura de um comerciante que vende equipamentos da Vault.}
{272}{}{Procuro um comerciante chamado Vic.}
{273}{}{Você tem algum trabalho?}
{274}{}{Sobre esse trabalho ...}
{275}{}{Mais trabalho para mim?}
{276}{}{Nada. Tchau.}
{277}{}{Wekee.}
{278}{}{Ruh ruh?}
{279}{}{Iho shasha.}
{280}{}{Dy.}
{281}{}{Ruh ruh?}

# 4. Whiskey (From 3)
{300}{}{Whiskey é minha especialidade. É quase uma tradição na família Dyer. Eu cobro o
 Preço baixo e baixo de apenas US $ 5.}
{301}{}{As bebidas ainda são de US $ 5, e a família Dyer faz as melhores bebidas no mundo inteiro.}
{302}{}{Você está bem? Você quer whisky? Apenas US $ 5.}
{303}{}{Vou tomar uma bebida.}
{304}{}{Por que suas bebidas são tão baratas?}
{305}{}{Tintureiro?}
{306}{}{Posso fazer uma pergunta?}
{307}{}{Tchau.}
{308}{}{Wekee}
{309}{}{Urka.}

# 5. Dyer (From 4)
{320}{}{Ah, esse é o nome da família. O nome Dyer esteve no negócio do bar para um
 Muito tempo - antes da guerra, é claro.}
{321}{}{Como eu disse, é o meu nome de família. Costumava haver pubs Dyer, salões ou algo assim,
 No mundo todo.}
{322}{}{Vou tomar uma bebida.}
{323}{}{Posso fazer outra pergunta?}
{324}{}{Tchau.}

# 6. Why drinks are so cheap (From 5)
{330}{}{Bem, já que você é um bom cliente, eu vou deixar você entrar em um pequeno segredo.
 É realmente simples - eu tenho uma calma. Um amigo de uma cidade próxima me ensinou como
 faz um. Então, você gostaria de outro?}
{331}{}{Desculpe, é um segredo comercial. Além disso, eu realmente não conheço você tão bem. Eu não gostaria
 Quer que Frankie descubra. Ele é o suficiente como é. Você ainda quer um? Eles
 Realmente atingiu o local.}
{332}{}{Certo. I'll have one.}
{333}{}{Posso fazer outra pergunta?}
{334}{}{Ok, obrigado.}

# 7. Drinking (From 4-6)
{340}{}{Aí está você. Muito obrigado.}
{341}{}{Obrigado. Posso te fazer uma pergunta?}
{342}{}{Ok, obrigado.}
{343}{}{Thankey youey.}
{344}{}{Nopey nopey.}

# 8. (From )
{350}{}{Desculpa. Acho que não.}
{351}{}{Fred me deve US $ 200. Se você puder coletá-lo de alguma forma, vamos resolver algo.}
{352}{}{Eu ainda tenho essa dívida que eu preciso colecionar.}
{353}{}{Derek emprestou um livro meu há um tempo atrás. Eu pagarei $ 80 se você puder obtê-lo
 De volta para mim.}
{354}{}{Ainda estou procurando esse livro meu.}
{355}{}{Qual é a captura?}
{356}{}{Me diga mais.}
{357}{}{Posso te fazer uma pergunta?}
{358}{}{Tchau.}

# 9. Job 1 & 2 Introductions (From 8)
{370}{}{Pegar? Oh, bem, se você conhecesse o Fred, você entenderia. Ele me devia o dinheiro
 Por muito tempo. Eu escrevi isso como uma perda, mas se você puder recuperá-lo, eu seria
 Impressionado ... e agradecido. Ele está em algum lugar da cidade, tenho certeza.}
{371}{}{O livro foi The Lavender Flower. Derek deveria terminar com a mãe no lado leste.}
{372}{}{Verei o que posso fazer.}
{373}{}{Claro, parece fácil.}
{374}{}{Eu já encontrei.}
{375}{}{Eu vou ter que voltar para você.}

# 10. (From 3, )
{385}{}{Você realmente não conseguiu, você? Eu ficaria impressionado.}
{386}{}{Ah, você encontrou meu livro? Derek melhor não ter esgueirado.}
{387}{}{Sim eu fiz.}
{388}{}{Eu sinto Muito. Ele está morto.}
{389}{}{Desculpe, mas Derek também está morto.}
{390}{}{Me desculpe, mas ele está morto.}
{391}{}{Sim. Aqui está.}
{392}{}{Não, desculpe.}

# 11. Finished Job 1 or 2 (From 10)
{400}{}{Não posso acreditar nisso. Como você fez isso? Oh, não importa. Estou atordoado,
 Isso é tudo. Para mostrar minha apreciação, vou dividi-lo com você, logo abaixo
 meio. Obrigado novamente, isso foi muito honesto de você.}
{401}{}{Oh, estou tão feliz que você conseguiu encontrá-lo ... Muito obrigado. Aqui está o seu dinheiro.}
{402}{}{Seja bem-vindo.}

# 12. Deaths (From 10)
{410}{}{Não posso acreditar que ambos estão mortos. Eu sinto Muito. Obrigado por descobrir por
 mim. Se você me desculpe ...}
{411}{}{Não posso acreditar que ele está morto ... depois de todos esses anos.}
{412}{}{Certo.}

# 13. Vic (From 3)
{420}{}{Sim, eu sei quem é esse. É o Vic - o cara que Metzger encerrou.}
{421}{}{Sim, eu conheço Vic. Metzger o colocou trancado. Ainda não sei por que.}
{422}{}{Quem é Metzger?}
{423}{}{Eu tenho outra pergunta.}
{424}{}{Great! Tchau.}

# 14. Who's Metzger (From 13)
{430}{}{Você veio ao Den e você não sabe quem é Metzger? Ele é o mestre escravo.
 Ele está no lado leste da cidade. Difícil de perder.}
{431}{}{Eu tenho outra pergunta.}
{432}{}{Obrigado.}

# 15. CF: Hostile & Childkiller (From WTG)
{440}{}{Assassino!}
{441}{}{Childkiller!}
{442}{}{Por favor saia.}
{443}{}{Não vou lidar com os gostos de você.}
{444}{}{Eu não vou sair sem uma briga!}

# 16. Buffy 1 (From WTG)
{450}{}{Buffy! É você! Como você está? Faz muito tempo!}
{451}{}{Hã?}
{452}{}{Hã?}

# 17. Buffy 2 (From 16)
{460}{}{Dave envia o seu melhor e deseja que ele possa estar aqui para dizer oi, mas ele teve que fugir.}
{461}{}{Para onde?}

# 18. Buffy 3 (From 17)
{470}{}{Algo sobre um comando ... ou que ele estava indo atrás de um comando. Não tenho certeza
 exatamente. Algo parecido.}
{471}{}{Oh.}

# 19. Buffy 4 (From 18)
{480}{}{Ah, ele disse para lhe dar isso. É um presente da família Hendee. Deveria
 Ajudá-lo a alguns.}
{481}{}{O que é isso?}

# 20. Buffy 5 (From 19)
{490}{}{Ah, apenas alguns bugigangas. Aqui está. [Becky lhe entrega $ 1000, 5 Stimpaks,
 Metal Armor, um Uzi, 5 clipes de munição, uma Granada de Plasma e flor]}
{491}{}{Obrigado!}

# 21. Buffy 6 (From 20)
{500}{}{Sem problemas. Eu estava segurando-os para você. Bem, é melhor eu voltar ao trabalho.}
{501}{}{Obrigado tchau.}

# 22. Metzger's Dead! (From WTG)
{510}{}{Você não ouviu! Ele está morto! Oh, eu sei que não devo ser feliz, mas ele foi muito
 homem maligno.}
{511}{}{Ele certamente fez uma boa luta.}
{512}{}{Eu tenho uma pergunta.}
{513}{}{Sim, era. Adeus.}
{514}{}{ matar!}

# 23. Metzger's dead 2 (From 22)
{520}{}{O que? You? I... don't know what to say. He was such an evil man...}
{521}{}{Um agradecimento seria suficiente.}
{522}{}{Humph.}

# 24. Metzger Reward (From 23)
{530}{}{Ah, um agradecimento seria suficiente. Eu sei que isso não está certo, mas ... aqui, pegue isso
 dinheiro. [Becky dá-lhe 1000 dólares]}
{531}{}{Mantenha seu dinheiro, Rebecca.}
{532}{}{Muito obrigado.}
{533}{}{Tanque!}
{534}{}{Ug! Perdy laDy.}

# 25. Metzger's Dead No reward, Gain Karma (From 24)
{540}{}{Você é um homem maravilhoso. Embora eu não tolere suas ações. Você fez o
 Mundo um ótimo serviço.}
{541}{}{Você é uma mulher maravilhosa. Embora eu não tolere suas ações. Você fez o
 Mundo um ótimo serviço.}
{542}{}{Obrigado.}

# 26. Still destroyed, after talk (From WTG)
{550}{}{You are not welcome here. Por favor saia.}
{551}{}{Por favor saia.}

# 27. Still destroyed (From WTG)
{560}{}{Por que você destruiu meu imóvel? O que eu sempre fiz para você?}
{561}{}{Fui pago para fazê-lo.}
{562}{}{Eu não tenho que responder a ninguém.}
{563}{}{Eu não sei do que você está falando.}
{564}{}{Tanto faz.}
{565}{}{Ooba gooba.}

# 28. Still 2 (From 27)
{570}{}{Sério? Aquele maluco que Frankie colocou para você, tenho certeza disso. Eu vou apenas
 Faça outro, você sabe.}
{571}{}{Não importa. Recebi o pagamento.}
{572}{}{Assim.}
{573}{}{Eu não ficaria surpreso.}

# 29. Still 3(From 28)
{580}{}{Então, você é um covarde também? Figuras.}
{581}{}{...}
