# examines
{100}{}{Você vê um escravidente de idade média e difícil.}
{101}{}{Você vê escravas com uma grande cicatriz no rosto.}
{102}{}{Você vê um escravo bastante grande.}

{150}{}{Há um escravo que parece aproveitar o trabalho dele.}
{151}{}{Este escravo parece ser muito forte, mas não brilhante.}
{152}{}{Este escravo parece estar bem armado, como os outros.}

# 1. CF: Hostile Not Done - no kills
{225}{}{Vamos pegar eles.}
{226}{}{Apenas mate os hostis.}
{227}{}{Lidere o caminho; estamos logo atrás de você.}
{228}{}{Apenas tire os hostis - os outros são nossos salários.}
{229}{}{Estou pronto para dividir algumas cabeças.}
{230}{}{Onde eles estão? Você vê-los?}

# 2. CF: Hostile Not Done - have kills
{235}{}{Não é hora de partir ainda.}
{236}{}{Obtenha o último dos hostis.}
{237}{}{Deixe os desarmados sozinhos. Obtenha os outros.}
{238}{}{Ainda há um pouco mais de sangue esperando por nós.}

# 3. CF: Done with run - Poor
{245}{}{Essa foi uma corrida horrível.}
{246}{}{Isso não valia a pena. Nós não ficamos merda.}
{247}{}{Da próxima vez, tire apenas os hostis. Isso não é tudo divertido e jogos.}
{248}{}{Metzger ficará chateado.}

# 4. CF: Done with run - Average
{255}{}{Não é ruim - mas da próxima vez, deixe os desarmados sozinhos, se você quiser que nos paguemos.}
{256}{}{Isso não era tão ruim assim. Nós temos alguns escravos decentes fora disto.}
{257}{}{Eu já vi melhor, mas pelo menos seremos pagos.}

# 5. CF: Done with run - Good
{265}{}{Ei, nós ficamos muito bons. Nós quase conseguimos todos eles.}
{266}{}{Obrigado pela ajuda.}
{267}{}{Bom trabalho. O pagamento dessa corrida deve ser bom.}
{268}{}{Isso foi divertido e devemos retirar um bom dinheiro.}

# 6. CF: Done with run - Perfect
{275}{}{Nós chutamos um burro sério. Metzger melhor nos dá um grande bônus.}
{276}{}{Isso foi perfeito! Eu vou ficar com tanta carinha nesta noite.}
{277}{}{Fuck'n A. Nós chutamos o traseiro.}
{278}{}{Essa é a maneira de fazê-lo!}

# 7. BF: Hostile Not Done - no kills
{285}{}{Onde eles estão?}
{286}{}{Eu vou me dar um pouco de amor.}
{287}{}{Aposto que vou ter mais mortes do que você desta vez.}
{288}{}{Aqui, gatinha, gatinha, gatinha.}

# 8. BF: Hostile Not Done - have kills
{295}{}{O resto de vocês está morto; você ainda não sabe disso.}
{296}{}{Você não pode se esconder de nós!}
{297}{}{Saia, ou eu vou explodir sua cabeça de merda.}
{298}{}{Ah, isso foi bom! Onde estão os outros?}

# 9. BF: Done with run - Poor
{305}{}{Merda.}
{306}{}{Isso sugou.}
{307}{}{Droga.}
{308}{}{É melhor não fazer isso de novo.}
{309}{}{Foda-se ... e eu ia beber hoje à noite.}
{310}{}{Vamos sair daqui. Isso é uma merda.}

# 10. BF: Done with run - Average
{320}{}{Não é ruim.}
{321}{}{Espero que tenhamos o suficiente. Preciso reabastecer o meu abastecimento de jato.}
{322}{}{Vamos.}
{323}{}{Eu vi melhor, mas o dinheiro do dinheiro.}
{324}{}{Metzger deve estar bem com estes.}

# 11. BF: Done with run - Good
{325}{}{Muito bom.}
{326}{}{Se apresse. Vamos vencê-lo.}
{327}{}{Isso deve ser feito bem.}
{328}{}{Bom arrastar.}
{329}{}{Vamos. I want my money.}

# 12. BF: Done with run - Perfect
{335}{}{Tempo de bônus!}
{336}{}{Arrebentar.}
{337}{}{Junte-os e vamos começar.}
{338}{}{Stop fuck'n around. Vamos.}
{339}{}{Porra, essa corrida parece doce.}
