# looks
# primitive
{100}{}{Você vê um homem grande e de aparência primitiva.}
{101}{}{Você vê uma mulher primitiva delgada.}

# nomads
{200}{}{Você vê um homem de aparência estranha.}
{201}{}{Você vê um homem de aparência irregular.}
{202}{}{Você vê um homem com roupas esfarrapadas.}

{210}{}{Você vê uma mulher muito suada.}
{211}{}{Você vê uma mulher bastante suja.}
{212}{}{Você vê uma mulher de aparência escaldante.}

# 10. BF: Fleeing Primitive
{270}{}{Eles não me encontram.}
{271}{}{Deve se esconder. Deve se esconder.}
{272}{}{Por que eles querem magoar?}
{273}{}{Me assustou.}
{274}{}{Eu não luta.}
{275}{}{Eu quero viver.}
{276}{}{Não machucou a família.}

# 11. BF: Fleeing Nomad
{280}{}{Ah Merda!}
{281}{}{Porque é que eles estão a fazer isto?}
{282}{}{E a minha família?}
{283}{}{Não quero morrer.}
{284}{}{Não quero ser escravo.}
{285}{}{Eu mereço melhor do que isso.}

# 14. Fleeing Primitive
{300}{}{Ahhh!}
{301}{}{Não mate! Não mate!}
{302}{}{Pare!}
{303}{}{Heeeelp!}
{304}{}{Corre!}
{305}{}{Deixe em paz!}
{306}{}{Não machuque!}
{307}{}{Não te machuque!}
{308}{}{Eu não lutei!}

# 15. Fleeing Nomad
{350}{}{Corra por suas vidas!}
{351}{}{Não deixe que eles o peguem!}
{352}{}{Esclavistas! Corra por isso!}
{353}{}{Ajude alguém! Por favor!}
{354}{}{Corra por isso, Marty!}
{355}{}{Ahhh!}
{356}{}{Pare a insanidade!}
{357}{}{Nós não fizemos nada! Nos deixe em paz!}
{358}{}{Eu reconheço essa tatuagem!}
{359}{}{Não por favor!}
{360}{}{Por favor, não me mate!}
{361}{}{Não vou lutar; não me mate!}
{362}{}{Por favor, eu não quero morrer!}
{363}{}{Vocês são escravas você não é? Oh Deus.}
