{100}{}{Você vê uma prostituta.}

{150}{}{Este é o seu costume, corrida do moinho, prostituta.}

{152}{}{[CONVERSA]}
{153}{}{Ei, eu não faço pintinhos!}
{154}{}{Tanto faz.}
{155}{}{Desculpa.}
{156}{}{Mamãe?}
{157}{}{Ei, vai custar mais se você tiver uma audiência com você.}
{158}{}{Ei, eles vão para onde eu vou.}
{159}{}{Quero-os comigo.}
{160}{}{Eu voltarei.}
{161}{}{Mamãe?}
{162}{}{Oh bebê. Onde você esteve toda a minha vida?}
{163}{}{Bem, baby.}
{164}{}{Quanto, irmã?}
{165}{}{Eu preciso ir. Tchau.}
{166}{}{Whee!}
{167}{}{Eu gosto deles grandes e idiotas.}
{168}{}{Este sou eu!}
{169}{}{Yay!}
{170}{}{Oh. Não. Tchau.}
{171}{}{Que grande menino você é!}
{172}{}{Do jeito que você gosta.}
{173}{}{Sim, senhora.}
{174}{}{Eu tenho que ir.}
{176}{}{ESTÁ BEM!}
{177}{}{Não. Tchau.}
{178}{}{Você voltará.}
{179}{}{Veremos.}
{180}{}{Um, não.}
{181}{}{[drool]}
{182}{}{Você não tem dinheiro suficiente. Perder-se, querido.}
{183}{}{Eu voltarei.}
{184}{}{Você não vale a pena, toots.}
{185}{}{Wah!}
{186}{}{Você foi incrível!}
{187}{}{Sempre, meu amor.}
{188}{}{Tanto faz.}
{189}{}{Você também estava.}
{190}{}{Eu comestível!}
{191}{}{Você foi ótimo!}
{192}{}{Obrigado. Você também.}
{193}{}{Hmm.}
{194}{}{Sim.}
{195}{}{Ótimo!}
{196}{}{OK, terminamos. Tchau.}
{197}{}{É isso aí?}
{198}{}{ESTÁ BEM. Tchau}
{199}{}{Foi bom.}
{200}{}{Tchau tchau.}
{201}{}{Não pago o suficiente para isso.}
{202}{}{Não é como se você valesse o dinheiro de qualquer forma.}
{203}{}{Você vai sentir minha falta.}
{204}{}{Tchau.}
{205}{}{Perdido?}
{206}{}{Volte a qualquer hora.}
{207}{}{ESTÁ BEM. Tchau.}
{208}{}{Okay, certo.}
{209}{}{Whoo!}
{210}{}{Até mais.}
{211}{}{Tchau.}
{212}{}{Tchau tchau.}
# Custará $(amount) para uma sessão. Pague primeiro.
{213}{}{Custará $}
{214}{}{ para uma sessão. Pague primeiro.}
{215}{}{Me siga.}
{216}{}{Estou esperando.}
{217}{}{Não vou ficar aqui nesta sala fria o tempo todo.}
{218}{}{Você se apresse?}
{219}{}{Última chance.}
{220}{}{Bem; Não aguento mais.}
{221}{}{Vamos! Vamos.}
{222}{}{Ficando excitado ou algo assim?}
{223}{}{Me siga.}
{224}{}{Ei, amigo, mantenha suas mãos fora da mercadoria.}
{225}{}{Bata fora! Eu não sou apenas um brinquedo para usar.}

{230}{}{Uhhh ...? Foi sua primeira vez?}
