# 0. Look
{100}{}{Você vê um escravo.}

{150}{}{Ele parece ser um dos guardas pessoais de Metzger.}

# 1. CF: Hostile
{200}{}{Aí está você.}
{201}{}{Agora você morre.}

# 2. CF: Normal
{300}{}{Você quer ver o chefe? Vá logo dentro.}
{301}{}{Metzger é o homem com quem falar, não eu.}
{302}{}{Continue.}
{303}{}{Comporte-se.}
{304}{}{Metzger está bem na porta.}
{305}{}{Não mexe Metzger fora.}
{306}{}{Não estamos vendendo se é por isso que você está aqui.}
{307}{}{Ainda não pode me acostumar com uma mulher escravista.}
{308}{}{É bom ter você conosco.}
{309}{}{Oi. Como tá indo?}
{310}{}{Você ainda abre qualquer escravo?}
{311}{}{Oi de novo.}
{312}{}{Ir para outra corrida?}
{313}{}{As coisas estão bastante calmas.}
{314}{}{Quando eu vou ver alguma ação?}
{315}{}{Eu sinto falta de corridas de escravos. Guardando é uma merda.}
{316}{}{As corridas de escravos são uma explosão.}
{317}{}{Ei, cara, prazer em tê-lo conosco.}
