# 0. Look Primitive
{100}{}{Você vê um homem grande e de aparência primitiva.}
{125}{}{Ele cortou e machucou todo seu corpo.}

{150}{}{Você vê uma mulher esbelta e primitiva.}
{175}{}{Parece que ela foi espancada.}

# 1. Look Nomad
{200}{}{Você vê um homem de aparência irregular.}
{225}{}{Ele não parece muito saudável.}

{250}{}{Você vê uma mulher cativa.}
{275}{}{Ela está suja e parece estar desnutrida.}

# 2. CF: Freed
{300}{}{Sem dores, por favor!}
{301}{}{Partimos agora?}
{302}{}{Não conversa. Deve correr.}
{303}{}{Obrigado pela ajuda.}
{304}{}{Muito obrigado!}
{305}{}{Você é um santo.}
{306}{}{O que você está fazendo? Nós devemos ir.}
{307}{}{Por favor, ajude-nos a escapar.}

# 3. CF: PC is Slaver
{320}{}{Você é ruim!}
{321}{}{Nós não conversamos com você.}
{322}{}{Nós nos liberamos.}
{323}{}{Você não nos mantém.}
{324}{}{Você é escravo}
{325}{}{Por que os escravos fazem isso?}
{326}{}{Como você pode trabalhar para essas pessoas?}
{327}{}{Não somos primitivas!}
{328}{}{Você não tem nenhuma moral?}
{329}{}{O que vai acontecer conosco?}
{330}{}{O que fizemos de errado?}
{331}{}{Deixe-nos em paz, escravidão!}
{332}{}{Não me machuque!}
{333}{}{Saia de perto de mim!}

# 4. CF: PC is Not Slaver
{350}{}{Quem você?}
{351}{}{Você não é escravo.}
{352}{}{Você não está magoado?}
{353}{}{Amigos?}
{354}{}{Você ajuda?}
{355}{}{O que vai acontecer conosco?}
{356}{}{Você também foi capturado?}
{357}{}{Não somos primitivas!}
{358}{}{Quem essas pessoas pensam que são?}
{359}{}{Por favor nos ajude!}
{360}{}{Tire-me daqui.}

# 5. BGF: Not Free
{380}{}{Você não nos mantém aqui!}
{381}{}{Não há direito!}
{382}{}{Não somos ruins!}
{383}{}{Nós ajudamos?}
{384}{}{Livre-nos!}
{385}{}{Não como.}
{386}{}{Lugar ruim.}
{387}{}{Por que pessoas ruins fazem isso?}
{388}{}{Nós não somos escravos!}
{389}{}{Nós não fazemos nada de errado.}
{390}{}{Solte!}
{391}{}{O que aconteceu?}
{392}{}{Grande barulho?}
{393}{}{Quem luta?}
{394}{}{O que acontece?}
{395}{}{Algo aconteceu?}
{396}{}{Alguém nos ajude!}
{397}{}{Ei! Ninguém pode me ouvir?}
{398}{}{Isso está errado!}
{399}{}{Nós não fizemos nada!}
{400}{}{Deixe-nos sair daqui!}
{401}{}{Alguém nos tire!}
{402}{}{O que nós fizemos?}
{403}{}{Nós não fizemos nada.}
{404}{}{Nós não merecemos isso.}
{405}{}{Aqueles bastardos!}
{406}{}{Ajude-nos!}
{407}{}{Deixe-me sair!}
{408}{}{Nós não somos escravos!}
{409}{}{Não somos primitivas! Deixe-nos sair daqui!}
{410}{}{O que está acontecendo?}
{411}{}{Alguém está aqui para nos salvar?}
{412}{}{Por aqui!}
{413}{}{Socorro! Não nos deixe!}
{414}{}{O que foi o tiroteio?}
{415}{}{O que está acontecendo?}

# 7. BGF: Fleeing
{420}{}{Ahhh!}
{421}{}{Ug!}
{422}{}{Não pare!}
{423}{}{Sim!}
{424}{}{Estou indo tão longe do local quanto possível.}
{425}{}{Continue andando!}
{426}{}{Liberdade! Finalmente livre!}

# 8. Metzger is Dead (From Where to go)
{440}{}{Qual ruído alto da arma? O que você quer?}
{441}{}{Ei! O que foi todo esse tiroteio? Os escravos estão mortos?}
{442}{}{Hey! What was all that gunfire? O que está acontecendo?}
{443}{}{Essa foi a bússola de Metzger.}
{444}{}{Oh nada. Apenas checando em você. Tchau.}
{445}{}{Você está livre para ir. Metzger está morto.}
{446}{}{Você esta livre.}
{447}{}{ amigos. Ele mata Mezgur. Você vai agora.}
{448}{}{ amigos. Ela mata Mezgur. Você vai agora.}

# 9. Metzger is Dead (From 8)
{460}{}{Ele morto? Eu, obrigado! Nós deixamos rápido. Tchau. Seu amigo.}
{461}{}{O que? Metzger está morto? Oh, muito obrigado! É melhor deixar antes que outros apareçam. Obrigado novamente.}
{462}{}{Seja bem-vindo. Agora sai daqui.}
{463}{}{Cuidar.}
{464}{}{Seja bem-vindo.}

# 10. Metzger Dead, Next Times (From Where to go)
{480}{}{O que você quer?}
{481}{}{O que você quer?}
{482}{}{Oh nada.}

# 11. Bullet (From 8)
{500}{}{Hã?}
{501}{}{Deixa pra lá. Você está livre para ir. Metzger está morto.}

# 12. You Free (From 8)
{510}{}{Wha? Livre? Homens maus foram? Nós vamos agora! Obrigado. Seu amigo! Tchau!}
{511}{}{Livre? O que? Você matou todos eles? Muito obrigado! É melhor sairmos enquanto ainda pudermos. Obrigado novamente, você é um santo!}

# 13. NPC Sold to Slavery (From WTG)
{520}{}{Maldito!}
{521}{}{Apodrecer no inferno!}
{522}{}{Você pagará por isso.}
{523}{}{Por que você está falando comigo mesmo?}
{524}{}{Me deixe em paz.}
{525}{}{Eu não quero falar com você.}
{526}{}{Como você pode?!}
{527}{}{Eu nunca quero ver você de novo.}
{528}{}{Isso não vai mudar as coisas.}
{529}{}{Eu irei no caminho, se você não se importar.}
{530}{}{Por favor, deixe-me sair.}
{531}{}{Apenas deixe-me estar a caminho.}
{532}{}{Ainda não quero falar com você.}
{533}{}{Me deixe em paz.}
{534}{}{Não há chance.}
{535}{}{Você acha que isso torna as coisas melhores?}

# 6. BGF: Just Freed
{600}{}{Nós vamos?}
{601}{}{Sem dores?}
{602}{}{Ir!}
{603}{}{Casa!}
{604}{}{Livre?}
{605}{}{Hã?}
{606}{}{O que?}
{607}{}{Você falou grátis?}
{608}{}{Estou fora daqui!}
{609}{}{Vamos!}
{610}{}{Todos! Somos livres!}
{611}{}{Yaaahooo!}

{700}{}{Você liberta os escravos de suas canetas.}
