# 0. Look
{100}{}{Você vê um escravo.}
{000}{}{Você vê um escravo chamado Aidan.}

{150}{}{Parece que ele poderia facilmente cuidar de si mesmo em uma briga.}

# 1. First Time - Self Initiated (From Where to go)
{200}{}{Ah, carne fresca ... Bem-vindo à guild da escrava. O nome é Aidan. Já aqui
 o negócio? Você é melhor.}
{201}{}{O que exatamente a sua aliança faz?}
{202}{}{A aliança de Slaver?}
{203}{}{Salvar guld?}
{204}{}{Aruk kun cantou?}

# 2. Yes, join (From 4)
{215}{}{[Aidan olha você para cima e para baixo.] Bem, parece que você entraria bem, amigo, mas você vai
 tenha uma conversa sobre Metzger, é claro. Mesmo assim, a porta das costas.}
{216}{}{[Aidan olha você para cima e para baixo.] Você não parece que poderia estragar, amigo, mas quem
 Sou um juiz? Você deve falar com Metzger. Ele atravessa a porta dos fundos.}
{217}{}{Eu disse ta falar com Metzger. Você é surdo, burro ou simplesmente burro?}
{218}{}{Quem é o Metzger?}
{219}{}{Outra pergunta para você, então.}
{220}{}{Obrigado, eu vou.}
{221}{}{Medger}
{222}{}{Uh ... kay.}

# 3. Hostile, Start Combat. (From Where to go)
{230}{}{Agora você morre.}

# 4. (From Where to go, 1-2, 6, 10-11, 16-18)
{240}{}{Tem que me fazer uma merda! Nós capturamos e vendemos escravos. Isso é o que você está aqui, certo?
 Você está procurando alguma ação?}
{241}{}{Tem que me fazer uma merda! Nós capturamos e vendemos escravos. Se você não está aqui para isso, o que?
 quer?} # Intentional errors, please do not change.
{242}{}{Então, você se juntou. Isso deve ser interessante. Se você gosta de ação, você está na linha de trabalho correta. Se você não, você não durará muito.}
{243}{}{Nunca pensei em ver aquela tat na mulher. Parece bem, no entanto. Surpreendido Metzger ... foda-se. Então, o que você precisa?}
{244}{}{O que você quer? Você perdeu ou alguma coisa?}
{245}{}{Olá de novo. senhora. O que você precisa?}
{246}{}{O que?}
{247}{}{Estou procurando se juntar.}
{248}{}{Onde você consegue seus escravos?}
{249}{}{Gostaria de comprar alguns escravos.}
{250}{}{Você conhece um homem chamado Vic?}
{251}{}{Estou à procura de um comerciante.}
{252}{}{Você já ouviu falar do Vault 13?}
{253}{}{Tchau.}
{254}{}{Trabalhos.}
{255}{}{Comida.}
{256}{}{Matar.}
{257}{}{Ug.}

# 5. Dumb Kill (From 4)
{270}{}{Ah, uma sanguinária. Bem ... Fale com o chefe. Podemos ter um lugar para você. Atravesse a porta dos fundos.}
{271}{}{Metzger nunca teve uma escrava da cadela, mas se você realmente é tão sanguinário, verifique com ele. Ele atravessa essa porta.}
{272}{}{Okke.}
{273}{}{Uh.}
{274}{}{Krook}

# 6. Buy slaves (From 4)
{280}{}{Converse com Metzger sobre isso. Ele normalmente não vende ao público. Tem as mãos cheias com ... clientes maiores.}
{281}{}{Quem é o Metzger?}
{282}{}{Posso perguntar outra coisa então?}
{283}{}{Tudo bem tchau.}
{284}{}{E quanto a Vic?}

# 7. Dumb Exit (From 1, 4)
{290}{}{Você não diz. Cai fora!}
{291}{}{Cadela muda.}
{292}{}{Oook?}
{293}{}{Hmph.}

# 8. What about buying Vic (From 6, 19)
{300}{}{Não é provável. Aquele idiota Vic irritou Metzger com algum rádio ou algo assim. Eu duvido que ele o venda. Você terá que falar com você mesmo.}
{301}{}{Bem, eu ouvi dizer que ele finalmente corrigiu o rádio. Você deve perguntar ao Metzger. Ele não usa muito agora, não é uma boa qualidade de comércio.}
{302}{}{Quem é o Metzger?}
{303}{}{Onde está Metzger?}
{304}{}{Ok, obrigado. Tchau.}

# 9. Where's Metzger (From 8)
{310}{}{Ele está na parte de trás da porta por aí.}
{311}{}{Você está brincando comigo? Ele está bem lá. Apenas passe por essa porta.}
{312}{}{OK.}
{313}{}{Obrigado.}

# 10. Quem é o Metzger? (From 2, 8, 16)
{320}{}{Porra, você não conhece Metzger? O que você está fazendo nesta cidade, se não o vê? Ele é o chefe do Slaver's Guild.}
{321}{}{Quantas vezes eu tenho que te dizer? Ele é o mestre escravo. Ele dirige coisas nesta cidade.}
{322}{}{Posso pedir-lhe outra coisa?}
{323}{}{Ok, obrigado.}

# 11. Where do you get slaves from? (From 4)
{330}{}{Eu não estou falando sobre isso. Metzger vai me amarrar. Além disso, não queremos nenhuma competição externa.}
{331}{}{Eu já disse. Não vou falar sobre isso.}
{332}{}{Diga-me antes de fazer um buraco na sua cabeça.}
{333}{}{Compreendo. Outra pergunta?}
{334}{}{Tudo bem tchau.}

# 12. Threatened life (From 11)
{340}{}{Escute aqui, cabeça de merda, não se atreva a me ameaçar ou a qualquer outra pessoa em nossa aliança, ou você está morto. Pegue isso? Morto.}
{341}{}{Ouça aqui, você é uma boceta. Não se atreva a me ameaçar ou a qualquer outra pessoa em nossa aliança, ou sua morte. Pegue isso? Morto.}
{342}{}{Agora, jovem jato, você vai morrer.}
{343}{}{Dane-se.}
{344}{}{Desculpe, não me machuque.}
{345}{}{Tanto faz. Eu vou deixar você viver dessa vez.}

# 13. Threaten back (From 12)
{350}{}{Sério? Talvez eu devesse explodir um todo na sua cabeça aqui mesmo agora. O que você acha, tiro quente?}
{351}{}{Faça o seu melhor tiro.}
{352}{}{Não me faça rir.}
{353}{}{Eu estava brincando, cara.}
{354}{}{Eu sinto Muito. Eu estava apenas tentando impressioná-lo.}

# 14. Run along (From 12, 13)
{360}{}{Corra, antes de mudar o m'mind.}
{361}{}{OK.}

# 15. Food? (From 4)
{370}{}{O que? Oh, you must be looking for Mom's. You're one building off.  She's in the building directly south. S-o-u-t-h. That way. [Aidan points out the door.]}
{371}{}{Hã? Uh ... Oh.}

# 16. Yes, join - Female (From 4)
{380}{}{Parece que você poderia entrar, mas a Metzger nunca contratou uma mulher. Não tenho certeza por que, mas duvido que ele comece agora.}
{381}{}{Você não parece o tipo. Inferno, Metzger nunca contratou uma mulher antes. Não tenho certeza por que, mas duvido que ele esteja começando agora.} # Error intentional, please do not remove.
{382}{}{Eu disse ta falar com Metzger.}
{383}{}{Quem é o Metzger?}
{384}{}{Outra pergunta.}
{385}{}{Obrigado, eu vou.}
{386}{}{Medger}
{387}{}{Uh ... kay.}

# 17. Vault 13? (From 4)
{400}{}{Não, mas eu verificaria com o chefe. Ele provavelmente esteve por toda parte.}
{401}{}{Outra pergunta.}
{402}{}{Ok, obrigado. Tchau.}

# 18. Vic/Merchant? (From 4)
{410}{}{Comerciante? Oh, você deve significar Vic, esse cara que vende o antigo material do Vault. Ele está fodido. Metzger estava muito chateado com 'm.}
{411}{}{Sim, Vic ... esse Merchant, certo? Aquele que vende o antigo conteúdo do Vault. Ele está fodido. Metzger estava muito chateado com 'm.}
{412}{}{Quantas vezes você vai me perguntar isso? Metzger obteve.}
{413}{}{Quem é o Metzger?}
{414}{}{Posso fazer outra pergunta?}
{415}{}{Ele está à venda?}
{416}{}{Ok, obrigado.}

# 19. Float Greeting (From WTG)
{430}{}{Ei, garotos, olhem quem está de volta.}
{431}{}{Corra, é um escravidão! Ah, eu me separo.}
{432}{}{Voltar para alguma ação?}
{433}{}{Você conhece o caminho.}
{434}{}{Continue.}
{435}{}{Ele está esperando por você.}
{436}{}{O que agora?}
{437}{}{Eu conheço esse rosto feio.}
{438}{}{Como vai'?}
{439}{}{Você está de volta. Você vai se juntar?}
