# 0. Look
{100}{}{Você vê uma galeira velha gordurosa.}

{150}{}{Você vê Smitty, o proprietário da mecânica e junkyard.}
{151}{}{Você vê uma galeira gordurosa e velha com roupa de trabalho suja.}

# 1. Get out floats (WtG)
{200}{}{Você é Varmint! Git outta aqui antes que eu devesse aprender você!}
{201}{}{Git outta meu lugar!}
{202}{}{Git off my land!}
{203}{}{Dang varmint, git outta aqui.}
{204}{}{Vá longe de mim.}

# 2. Low Intelligence (WtG)
{220}{}{Ei, git off my land.}
{221}{}{Você está lá, idiota, está aqui fora.}
{222}{}{Git, continue, git!}
{223}{}{Não tenho tempo para o seu tipo.}
{224}{}{Desculpe, acho que não falo idjit.}

# 3. Hello (WtG, 4,5,11, 17,20,25)
{240}{}{Olá, jovem feller. Por que o Smitty já pode fazer?}
{241}{}{Olá, fofo. Por que o Smitty já pode fazer?}
{242}{}{Jumpin 'jiminy, o que posso fazer agora?}
{243}{}{Ei, eu realmente gostei da minha refeição da mãe. Obrigado. Agora o que o velho Smitty pode fazer por você?}
{244}{}{Eu só queria saber o que você faz aqui?}
{245}{}{Diga, timer antigo, eu tenho essa coisa aqui que peguei no Gecko ....}
{246}{}{Hey Smitty, eu estava pensando sobre o carro que você tinha para venda.}
{247}{}{Eu trouxe sua refeição da mãe.}
{248}{}{Diga, timer antigo, eu tenho essa coisa aqui que eu peguei em Klamath ...}
{249}{}{Eu só estava olhando um pouco. Vejo você mais tarde, Smitty.}

# 4. Thing from Gecko (3)
{260}{}{Deixe o velho Smitty aqui dar uma olhada nisso.}
{261}{}{Claro aqui está.}
{262}{}{Pensando bem, deixe-me perguntar-lhe sobre outra coisa.}
{263}{}{Talvez outra hora. Adeus, Smitty.}

# 5. Thing from Klamath (3)
{280}{}{Deixe o velho Smitty aqui dar uma olhada nisso.}
{281}{}{Claro aqui está.}
{282}{}{Pensando bem, deixe-me perguntar-lhe sobre outra coisa.}
{283}{}{Talvez outra hora. Adeus, Smitty.}

# 6. Use Controller? (4)
{300}{}{Bem, agora, isso me parece que é um antigo controlador de célula de combustível. Hmm, aposto se eu usei isso com o velho Highwayman, eu poderia fazer com que ela fosse ronronada como uma gatinha.}
{301}{}{Hã?}

# 7. Use Regulator? (5)
{310}{}{Hmm, isso parece jist como um regulador de célula de combustível. Se eu tivesse um carro que funcionasse, certamente aumentaria a quilometragem.}
{311}{}{Hã?}

# 8. Meal from Mom's delivered (3,18)
{320}{}{Isso era um grande tipo de você. Muito obrigado, compadre. Aqui está um pouco para o seu problema. Vai ser útil por estas peças. (Ele lhe entrega um Stimpack).}
{321}{}{Obrigado, Smitty. Sem problemas. Até a próxima.}
{322}{}{Bem, uhhh ... Obrigado, mas já fui até mamãe e comeu-me a comer, então não vou precisar disso.}
{323}{}{Opa, não sou a pessoa de entrega habitual. Ele convidou hoje doente. Posso obter alguns pontos de experiência de qualquer maneira?}
{324}{}{Ok, desculpe pelo mixup. Espero que minha mãe não me atire! Eu realmente preciso desse emprego.}
{325}{}{Você sabe que não estamos fazendo a refeição gratuita depois das 24 horas mais, certo?}
{326}{}{Bem, talvez eu apenas coma eu mesmo.}
{327}{}{Mamãe não vai ficar muito feliz com isso.}

# 9. Tell about car (6,7)
{330}{}{Bem, você vê, eu tenho esse carro, um Chrysalis Motors Highwayman. Ela também é uma beaut. Eles costumavam dizer "Nada pode parar um Highwayman". Construído duro, era o que eram.}
{331}{}{Sim, então, o que isso tem a ver comigo?}

# 10. Car-Controller (9)
{340}{}{Bem, você entende, eu pensei que precisava de uma bateria para a coisa, mas tudo o que eu realmente preciso é um controlador de célula de combustível. As coisas sempre foram ruins neles.}
{341}{}{Bem, eu tenho um desses}

# 11. I've got one of those (10)
{350}{}{Este direito? Aqui está o acordo. Você me dá $ 2.000 e eu vou vender o carro. Heck vou instalar o controlador da célula de combustível para você. Deve correr bem como novo. Vou mesmo carregá-lo com algumas células de micro fusão extra que eu consegui.}
{351}{}{Isso parece bom para mim. Aqui está o dinheiro e a parte.}
{352}{}{Eu não acho que eu quero fazer isso agora. Deixe-me perguntar-lhe sobre outra coisa, Smitty.}
{353}{}{Deixe-me pensar sobre isso. Eu vou te ver, Smitty.}

# 12. Here's the car (12)
{370}{}{Jist tome calma com ela até que ela aquece, agora.}
{371}{}{Sim eu vou. Obrigado, Smitty.}

# 13. Car-Regulator (9)
{380}{}{Bem, muito e não tanto ao mesmo tempo.}
{381}{}{Hã?}

# 14. What? (13)
{390}{}{O que estou dizendo é que um regulador é bom, mas você precisa encontrar um controlador de célula de combustível.}
{391}{}{Por que isso?}

# 15. Why? (14)
{400}{}{Porque se você tivesse um controlador e US $ 2.000, eu poderia consertar aqui o Chrysalis Motors Highwayman que cheguei aqui e você poderia dirigir com estilo.}
{401}{}{Mesmo? Onde posso encontrar um controlador de célula de combustível?}

# 16. Where do I find one of those? (15)
{410}{}{Agora, essa é uma pergunta tola. Você não pensa se eu soubesse disso, então eu dirigiria o carro?}
{411}{}{Uau. Eu vou ter que procurar por um desses.}

# 17. Look for one (16)
{420}{}{Seja uma boa ideia. Se você encontrar um jist, volte aqui com ele. Ah, e também não esqueça os $ 2.000.}
{421}{}{Parece um plano, Smitty. Ei, deixe-me perguntar-lhe sobre outra coisa.}
{422}{}{Eu vou procurar um agora. Adeus.}

# 18. Player bought car (WtG)
{430}{}{Ei ai, como esse carro corre por você?}
{431}{}{Muito bom, Smitty, mas achei essa parte do carro e não sei o que fazer com isso.}
{432}{}{Ótimo, Smitty, ótimo. Ei, trouxe-lhe uma refeição. Elogios de mamãe.}
{433}{}{Muito bom, Smitty, muito bom. Obrigado. Até a próxima. Adeus.}

# 19. Have regulator (18)
{450}{}{Bem, agora, esse é um regulador de célula de combustível. Isso lhe dará melhor quilometragem por célula de energia. Eu poderia colocar isso para você, se você tivesse dito $ 750 para o meu problema.}
{451}{}{Isso parece um acordo, Smitty. Aqui está a parte e o dinheiro.}
{452}{}{Eu vou ter que pensar sobre isso, Smitty. Até logo.}

# 20. What do you do here? (3)
{460}{}{Principalmente, eu apenas monto tudo sobre esse lixo antigo. Só tinha uma coisa valiosa doodly-squat.}
{461}{}{O que é isso?}
{462}{}{Achei isso. Deixe-me perguntar-lhe outra coisa.}

# 21. What's worth anything? (20)
{470}{}{Por que, não é senão este Chrysalis Motors Highwayman. Eles usaram ta dizer que "Nada pode parar um Highwayman". Eles os construíram duro, eu direi isso para eles.}
{471}{}{Uow, ele corre?}

# 22. Does it run? (21)
{480}{}{Se correu, você acha que eu ainda estaria neste lugar de uma cidade?}
{481}{}{Uh, sim.}
{482}{}{Eu acho que não.}

# 23. Yes (22)
{490}{}{Bem, você provavelmente está certo. Eu me encontrei um pouco aqui.}
{491}{}{Entendo.}

# 24. No (22)
{500}{}{Bem, então, novamente, mebebe eu também. Eu me sinto confortável aqui.}
{501}{}{Compreendo.}

# 25. Got car (23,24 )
{510}{}{Ainda não me importaria de vender o carro. Se alguém me trouxesse a bateria - não acerte isso, uh, acho que eu precisaria de um controlador de célula de combustível. Sim, se eu tivesse um deles, eu venderia o carro por US $ 2.000. Mesmo instale o controlador para que ele correu corretamente.}
{511}{}{Isso parece interessante. Eu vou ter que voltar se eu encontrar um controlador de célula de combustível. Deixe-me perguntar-lhe outra coisa agora.}
{512}{}{Quando eu encontrar um, volto. Adeus, Smitty.}

# 26. Regulator installed  (19)
{520}{}{Ai está. Melhor não é novo. Tome a calma com ela agora.}
{521}{}{Eu vou. Obrigado, Smitty. Adeus.}

{600}{}{VOCÊ GIRA O INFERNO ATRÁS DO MEU CARRO!}

{650}{}{Não me deixe atrapalhar o meu carro assim novamente.}
{651}{}{Você não vai.}
{652}{}{Uggg-K}
