{100}{}{Você vê o patron do bar.}
{101}{}{Você vê Stacy.}
{102}{}{Ela parece estar um pouco triste.}
{103}{}{Pare com isso!}
{104}{}{Como você pode?}
{105}{}{Saia de perto de mim!}
{106}{}{Por quê?}
{107}{}{Por favor pare!}
{108}{}{Você assassino!}
{109}{}{Pobre Mãe! Você pagará por isso!}
{110}{}{Mamãe...}
{111}{}{Mas ela era tão simpática com todos ...}
{112}{}{Desculpe, não consigo pensar em nada mais interessante.}
{113}{}{Meus cérebros estavam secos.}
{114}{}{É isso aí.}
{115}{}{Oi.}
{116}{}{Você já disse olá para a mãe ainda?}
{117}{}{Oh Olá.}
{118}{}{Ah, você de novo.}
{119}{}{Conte-me sobre o seu gato.}
{120}{}{Por que a flan glum?}
{121}{}{Você vem aqui frequentemente?}
{122}{}{Eu vou ter que te pegar mais tarde. Tchau.}
{123}{}{Okah?}
{124}{}{Ug.}

# Node 005 removed

{131}{}{Por favor, não me incomode. Eu realmente não estou com humor agora mesmo.}
{132}{}{Ugra.}
{133}{}{Fegi.}
{134}{}{Oh, nada realmente. Às vezes eu consigo pensar sobre minha mãe e meu gato. Eu sinto tanto falta deles.}
{135}{}{Gato?}
{136}{}{Desculpe ouvir isso. Tchau.}
{137}{}{Sim, Cuddles. Ela era um gato tão doce. Eu realmente não sinto como falar sobre isso ... Bem, a menos que você gostaria de me comprar uma bebida. Isso pode ajudar.}
{138}{}{Como eu disse, preferiria não falar sobre isso agora. Se você gostaria de me comprar uma bebida, pode afrouxar minha língua.}
{139}{}{Claro que eu vou. Eu adoraria saber sobre isso.}
{140}{}{Certo.}
{141}{}{Desculpe, não posso poupar $ 10 agora.}
{142}{}{Obviamente.}
{143}{}{Você acha que é engraçado ou algo assim? Obtenha uma linha melhor.}
{144}{}{Então, por que o floco de gluma?}
{145}{}{Seja o que for, tchau.}
{146}{}{Ouvi dizer que costumava haver aqueles que eram tão grandes quanto você e eu. Eles costumavam comer animais tão grandes como um brâmane. Agora, isso é coisa assustadora.}
{147}{}{Isso não é nada.}
{148}{}{Sim é.}
{149}{}{O tipo de que estou falando é um pequeno animal fofo, maior do que um rato, mas menor do que um cachorro. Alguns são esponjosos, como meus Cuddles, mas outros têm cabelo curto.}
{150}{}{Mesmo?}
{151}{}{Eles gostam de ser pet como um cachorro, mas os gatos fazem esse maravilhoso som relaxante quando você os ama.}
{152}{}{Estranho.}
{153}{}{Cuddles costumava me ajudar a dormir à noite. Penso nela todas as noites quando tento dormir.}
{154}{}{Parece bom.}
{155}{}{Continue.}
{156}{}{Eu a tinha quando eu era criança, mas ela desapareceu. Eu não sabia o que aconteceu com ela, eu era muito jovem.}
{157}{}{Por quê?}
{158}{}{Bem, a comida era muito escassa naquela época e as pessoas tinham que comer. É realmente muito triste ...}
{159}{}{O que?}
{160}{}{As pessoas iriam caçá-los porque eram uma presa tão fácil. Nenhum deles está por perto por causa disso.}
{161}{}{Doente!}
{162}{}{Eu posso entender isso.}
{163}{}{Aqueles eram os selvagens, mas tenho certeza que é o que aconteceu com os meus. Agora eu sei por que mamãe sempre olhou atentamente sobre ela.}
{164}{}{Que triste.}
{165}{}{Eu sinto Muito.}
{166}{}{Ah ...}
{167}{}{Isso me deixa triste em pensar ...}
{168}{}{Tchau.}
{169}{}{Stacy lhe contou uma doce história sobre seu querido gato Cuddles.}
