{100}{}{Você vê o patron do bar.}
{101}{}{Você vê Leanne.}
{102}{}{Ela é muito bonita, mas parece estar perdida no pensamento.}
{103}{}{Pare com isso!}
{104}{}{Por que você está fazendo isso?}
{105}{}{Me deixe em paz!}
{106}{}{Por favor pare!}
{107}{}{Você assassino!}
{108}{}{Como você pode fazer isso com Becky!}
{109}{}{O que ela fez com você?}
{110}{}{Você vai apodrecer no inferno.}
{111}{}{Desculpe, todas as histórias.}
{112}{}{Obrigado pela bebida.}
{113}{}{Prazer em falar com você.}
{114}{}{Obrigado por ouvir.}
{115}{}{Prazer em vê-lo novamente.}
{116}{}{Viagens seguras.}
{117}{}{Por que Olá! É bom ver um novo rosto por aqui. Meu nome é Leanne. Como você está, se preocupe em se sentar?}
{118}{}{Olá de novo. Bem-vinda, espero?}
{119}{}{Então, me diga o que você conhece sobre o Mestre.}
{120}{}{Ótimo. Como estão as coisas com você?}
{121}{}{Muito bom.}
{122}{}{Não posso falar agora. Tchau.}
{123}{}{Igsby?}
{124}{}{Bgy.}

# Node005 removed.

{131}{}{Oh, me desculpe. Eu não entendo. Talvez você não devesse beber tanto.}
{132}{}{Ugra.}
{133}{}{Fegi.}
{134}{}{Oh muito bom. Obrigado por perguntar. Becky tem uma história familiar tão interessante. Você tem um você mesmo?}
{135}{}{Ainda está indo bem, obrigado. Agora, onde estávamos? Eu acho que você estava falando sobre sua história familiar?}
{136}{}{Sim. Eu sou o Escolhido. Meu antepassado salvou o mundo de um chamado mestre.}
{137}{}{Sim. Meu antepassado supostamente salvou o mundo de alguém chamado "Mestre".}
{138}{}{Eu tenho que ir.}
{139}{}{Ok, ok. Prazer em conhecê-lo Escolhido ... Na verdade. Já ouvi algo sobre um mestre antes ...}
{140}{}{Que interessante. Isso me faz lembrar de uma história que ouvi há muito tempo. Algo sobre um mestre.}
{141}{}{Mesmo? O que foi isso?}
{142}{}{Conte-me.}
{143}{}{Oh, está bem. Tchau.}
{144}{}{Bem, isso pode demorar um pouco. Seja um cavalheiro e me compre uma bebida, você não gostaria? No entanto, não é whisky, Nuka-Cola.}
{145}{}{Bem, isso pode demorar um pouco. Seja uma boneca e me compre uma bebida, você não gostaria? No entanto, não é whisky, Nuka-Cola.}
{146}{}{Devemos começar? Lembro-me muito bem agora.}
{147}{}{Certo.}
{148}{}{Desculpe, não posso poupar US $ 5 agora.}
{149}{}{Obrigado. Agora vejamos ... Lembro-me de minha mãe me contar sobre essa enorme migração que aconteceu 70 ... ou foi há 80 anos ...}
{150}{}{Por favor continue.}
{151}{}{Realmente grandes mutantes com armas tão altas como você e eu vieram do sul. Mamãe disse que parecia uma grande migração de algum tipo.}
{152}{}{Quantos?}
{153}{}{Não sei, mas havia vários grupos deles. Alguns continuariam para o norte, outros se dirigiam para o leste. Ninguém sabia para onde eles estavam indo.}
{154}{}{Continue.}
{155}{}{Eles estavam bastante chateados e pareciam estar fugindo de alguma coisa.}
{156}{}{Mesmo?}
{157}{}{Sim, também havia outros com vestes sujas e esfarrapadas ... continuavam tagarelando sobre como o Mestre estava morto ...}
{158}{}{Interessante.}
{159}{}{Alguns deles até se suicidaram aqui na cidade!}
{160}{}{Assim?}
{161}{}{Bem, você não vê. Eles estavam falando sobre o Mestre, aquele que seu antepassado matou.}
{162}{}{Obrigado pela história.}
{163}{}{Bem, está ficando tarde. Tchau.}
{164}{}{O prazer é meu. Tchau.}
{165}{}{Tchau.}
{166}{}{Deixa pra lá.}
{167}{}{Leanne contou sua história sobre o Mestre.}
