{100}{}{Você vê um bandido.}

{150}{}{O bandido parece muito implacável.}
{151}{}{Saia do meu rosto.}
{152}{}{Você está procurando por problemas?}
{153}{}{Mantenha-se à direita na caminhada.}
{154}{}{Não interessado.}
{155}{}{Vá embora.}

{200}{}{Ei punk.}
{201}{}{Você quer algum problema?}
{202}{}{Venha aqui, sissy.}
{203}{}{Não me faça vir e bater sua bunda.}
{204}{}{Você falando comigo?}
{205}{}{Você quer algo disso?}
{206}{}{Ei, baby, venha aqui.}
{207}{}{Ei, você gosta do que vê?}
