{100}{}{Você vê o dono da loja.}
{101}{}{Você vê Tubby.}

{150}{}{Este é o dono da loja.}
{151}{}{Este é Tubby, o dono da loja.}
{152}{}{[CONVERSA]}
{153}{}{Preferiria que você fizesse o seu negócio em outro lugar.}
{154}{}{Você é um homem de negócios. Vamos conduzir negócios.}
{155}{}{Posso te perguntar uma coisa.}
{156}{}{Tchau.}
{157}{}{Estou tão feliz em vê-lo novamente. O que eu posso fazer para você hoje?}
{158}{}{Vamos trocar.}
{159}{}{Posso te perguntar uma coisa?}
{160}{}{Nothing for now. Tchau.}
{161}{}{Olá, senhor, e bem-vindo ao Tubby's. Eu sou o proprietário. Posso ajudar
 você?}
{162}{}{Sim, vamos negociar.}
{163}{}{Preciso de algumas informações.}
{164}{}{Adeus.}
{165}{}{Ola senhora. Eu sou chamado Tubby pelos meus amigos, e eu o agradeço
 para minha loja. Como posso ajudá-lo?}
{166}{}{Eu quero comprar algumas coisas.}
{167}{}{Preciso de algumas informações.}
{168}{}{Adeus.}
{169}{}{Preferiria que você fosse embora.}
{170}{}{Tchau.}
{171}{}{O que você gostaria de saber?}
{172}{}{Quem é responsável por esta cidade?}
{173}{}{Por que todos estão vendendo chems?}
{174}{}{Você sabe onde o Vault está localizado?}
{175}{}{Gostaria de trocar, afinal.}
{176}{}{Deixa pra lá. Tchau}
{177}{}{Oh meu. Posso dizer que teremos um problema de comunicação. Assente com a cabeça
 se você gostaria de negociar qualquer mercadoria.}
{178}{}{[Aceno com a cabeça]}
{179}{}{Tchau tchau.}
{180}{}{Ninguém, tenho medo. O Den é um lugar anarquista onde uma espécie de
 A luta darwiniana se desenrola. Somente o mais forte, mais rápido ou mais inteligente
 sobreviverá aqui. Tenho certeza que você encontrará seu nicho.}
{181}{}{Um, obrigado.}
{182}{}{ESTÁ BEM. Chems são a base para o sistema econômico desta cidade, assim como outro
 A cidade pode usar grãos ou ouro.}
{183}{}{Obrigado.}
{184}{}{Ouvi falar de um lugar chamado Vault City. Mas, infelizmente, não posso
 ajudá-lo com instruções. Você vê, muito poucos de nós, cidades, podem oferecer aceitáveis
 troca pelos serviços médicos que eles fornecem, então a maioria de nós nunca foi
 há.}
{185}{}{OK. Obrigado.}
{186}{}{Esse não é o tipo de informação que eu simplesmente daria a ninguém.}
{187}{}{Algum dinheiro mudaria de idéia?}
{188}{}{Que tal eu lhe dou $ 50 e você me conta.}
{189}{}{O que você diz que me fornece informações, ou eu lhe dou um novo buraco
 na cabeça.}
{190}{}{Deixa pra lá.}
{191}{}{Bem, posso perguntar-lhe outra coisa, então?}
{192}{}{Claro, esse tipo de dinheiro pode me ajudar a mudar de ideia. Mas você não tem
 isto!}
{193}{}{Devo tê-lo deixado em algum lugar. Eu vou procurar por isso.}
{194}{}{Eu não acho que isso seja suficiente.}

#tell petey to hold on messages
{500}{}{Claro, Petey. Estarei lá em um segundo.}
{501}{}{Espera, Petey!}
{502}{}{Eu estou chegando, estou chegando.}

#sell petey drug messages
{510}{}{Aqui está, Petey.}
{511}{}{Você sabe, Petey, você deveria chutar essa merda.}
{512}{}{Pegue isso e saia daqui, Petey.}
