# LOOKS
{100}{}{Você vê um químico dependente.}

{110}{}{Você vê uma merda de jato.}
{111}{}{Você vê uma das putas de Jet Tubby.}

# EXAMINES
{150}{}{Parece ser um amigo de Tubby.}

{160}{}{Ela parece estar extremamente dopada.}
{161}{}{Ela parece estar sofrendo grandes retiradas.}

# 1. CF: Tubby's Dead
{200}{}{Oh cara. Onde vamos pegar nossa merda agora?}
{201}{}{Por que matou Tubby?}
{202}{}{Oh, homem, isso é uma merda.}
{203}{}{Agora, o que devemos fazer?}
{204}{}{Oh cara…}
{205}{}{Ei, isso não é justo.}
{206}{}{Não nos machuque, não vamos contar.}

# 2. CF: Standard
# LOW KARMA
{220}{}{Uau, você parece muito malvado.}
# HIGH KARMA
{221}{}{Ei, você é um cara muito legal. Alguém já disse isso?}
{222}{}{Ei, você é uma garota muito legal. Alguém já disse isso?}
# GENERIC
{223}{}{Somos os guardas de Tubby.}
{224}{}{Não mexa com Tubby. Esse é o lugar dele.}
{225}{}{Droga, estou me sentindo bem.}
{226}{}{Você pode acreditar que somos guardas? Legal, não é.}
{227}{}{Essa merda é excelente.}
{228}{}{Oh, cara, eu não consigo sentir minhas pernas.}
{229}{}{O nosso amigo de Tubby.}
{230}{}{Tubby nos mantém felizes.}
{231}{}{Oh garoto, oh, garoto, oh garoto ... Maldito meus olhos.}
# SLAVER
{232}{}{Ei, cara, você é escravista? Uau…}
{233}{}{Essa tatuagem doeu?}
{234}{}{Vocês escravizantes certamente são difíceis.}
{235}{}{Não é perigoso ser um escravo?}
# METZGER DEAD
{236}{}{Ei, eu ouvi seu chefe ter disparado ou algo assim. Tough luck.}
{237}{}{Ei, você ouve? Metzger está morto ou algo assim.}
{238}{}{Uau, alguém cortou o Metzger the Butcher.}
{239}{}{Hope Tubby pode ficar no negócio com Metz ido.}

# 3. BGF: Tubby Dead (From Where to go)
{250}{}{Uau, cara. Ele matou Tubby.}
{251}{}{Acho que minha merda foi ruim.}
{252}{}{Woh, o que está acontecendo?}
{253}{}{O que era todo esse barulho?}
{254}{}{Dang, era uma merda desagradável.}
{255}{}{Uau, cara. Ela matou Tubby.}

# 4. BGF: Standard
{260}{}{Ooooohhyaaa ... Bom material.}
{261}{}{O que é isso?}
{262}{}{Oh, sim, estou voando agora.}
{263}{}{Oh, tão quente.}
{264}{}{Ela é tão bonita.}
{265}{}{Oh, blackout ... Merda, não consigo ver.}

# 5. Conversation
# CONVERSATION 1
{270}{}{Uau, você vê isso?}
{271}{}{Sim, você sabe o que era?}
{272}{}{Eu acho que era um pássaro.}
{273}{}{Não, um cachorro.}
{274}{}{Mas estava voando homem.}
{275}{}{De jeito nenhum - aumentou o zoom no chão.}
{276}{}{Sim, você está vendo coisas, cara.}
{277}{}{De jeito nenhum. Isso foi real.}
{278}{}{Tanto faz.}
{279}{}{Ahhhh está chutando novamente. Ahh.}

# CONVERSATION 2
{290}{}{Muitas luzes.}
{291}{}{Muitas luzes.}
{292}{}{Eles são tão quentes.}
{293}{}{E as árvores.}
{294}{}{Onde estão as mulheres?}
{295}{}{Tão verde e bonito.}
{296}{}{Eu gosto de batatas.}
{297}{}{As árvores são feitas de madeira.}
{298}{}{Eu gosto de mulheres e batatas.}
{299}{}{Eles fazem fumaça quando queimam.}
{300}{}{Mas não juntos.}
{301}{}{Os animais vivem em árvores.}
{302}{}{Não, não mulheres e árvores, mulheres e batatas.}
{303}{}{Posso escalar uma árvore.}
{304}{}{Uma mulher escalando uma árvore comendo batatas? Você é idiota.}
{305}{}{De onde vêm as árvores?}
{306}{}{Você não pode escalar uma árvore e comer batatas.}
{307}{}{Eu também gosto de arbustos.}
{308}{}{Bem, não muito facilmente.}
{309}{}{Porque eles são verdes.}
{310}{}{As batatas não são verdes.}
{311}{}{Ohhh, as lindas luzes.}
{312}{}{Oh, minha cabeça doi ...}

# 6. CF: Hostile
{320}{}{Não fale comigo, cara. Minha cabeça dói.}
{321}{}{Não vou contar a ninguém.}
{322}{}{Não me machuque.}
{323}{}{Eu não fiz nada.}
{324}{}{Não vi nada.}
{325}{}{Não ouvi nada.}
{326}{}{Por favor, simplesmente vá embora.}
{327}{}{Lady, eu não sinto muito como falar. Minha cabeça de merda está me matando.}

# 7. BGF: Hostile
{340}{}{Oh cara, você sugam.}
{341}{}{O que você foi e arruinou um alto perfeito?}
{342}{}{Homem, isso doeu!}
{343}{}{Que diabos?}
{344}{}{Como isso vai acontecer?}

# CRACH WHORES
#8. Click Floats
{400}{}{Tubby é tão maravilhoso.}
{401}{}{Jet me deixa tão excitado.}
{402}{}{Tubby sabe como cuidar de suas mulheres!}
{403}{}{Não é Tubby maravilhoso?}
{404}{}{Oh, querida, espere! Você não é Tubby.}
{405}{}{Onde está o nosso grande homem?}
{406}{}{Não faz apenas a sua pele tremer?}
{407}{}{Tubby tem o melhor fornecimento na cidade.}
{408}{}{Eu me sinto tão vivo!}

{420}{}{Você ouviu uma carga bang?}
{421}{}{Não vi Tubby há algum tempo.}
{422}{}{Onde está o Tubby?}
{423}{}{Você viu Tubby?}

{440}{}{Oh, minha cabeça!}
{441}{}{Onde está o Tubby! Eu acho que vou morrer!}
{442}{}{Não aguento mais isso.}
{443}{}{Oh, a dor está ficando realmente ruim.}
{444}{}{Tubby não nos deu nenhum por um tempo. Onde ele está?}
{445}{}{Meus lábios estão entorpecidos.}
{446}{}{Não consigo sentir meus dedos.}

#9. Hostile
{460}{}{Não me machuque!}
{461}{}{Por favor, não!}
{462}{}{Não entendi!}
{463}{}{Não era eu!}
{464}{}{Me deixe em paz!}
{465}{}{Eu não sabia que era seu!}
