# 0. Look
{100}{}{Você vê Tyler.}
{101}{}{Você vê Tyler, o líder dessa gangue.}

{150}{}{Ele parece bastante forte.}

# 1. Messed with door.
{200}{}{Ei, não toque na porra da porta.}
{201}{}{Idiota.}

# 2. Hostile
{210}{}{Agora terminamos.}

# 3. CF: Gang 1 Won.
{220}{}{Disse-lhe que seria um pedaço de bolo.}
{221}{}{Isso foi como levar cordeiros ao abate.}
{222}{}{Essa puta puta finalmente está morta!}
{223}{}{Obrigado pela dica, isso foi doce.}

# 4. CF: No Show
{230}{}{Se você estivesse triste?}
{231}{}{Trap minha bunda! Maldita mentirosa.}
{232}{}{Eu deveria deixá-lo agora mesmo.}
{233}{}{Tanto para o plano, idiota.}
{234}{}{É melhor você não ter empurrado para mim.}
{235}{}{Como você fodiu este?}

# 5. CF: Trap Set
{240}{}{Você acabou de liderar esses bastardos estúpidos aqui e nós os pregamos na parede.}
{241}{}{Nós estamos esperando.}
{242}{}{Não podemos esperar a noite toda.}
{243}{}{O que você está esperando? Estou pronto para o sangue.}
{244}{}{Faça isso já! Não os deixe suspeitar.}
{245}{}{Apresse-se bem.}

# 6. Trap = No (From WTG)
{250}{}{Quem diabos é você e o que você quer?}
{251}{}{Então, o que você quer desta vez?}
{252}{}{Metzger me enviou.}
{253}{}{Estou aqui para inspecionar a igreja.}
{254}{}{Eu voltarei.}
{255}{}{Eu}
{1255}{}{!}
{256}{}{Aruwa?}

# 7. Metzger sent me (From 6)
{260}{}{Por que diabos? Suas coisas não vão a lugar nenhum.}
{261}{}{Sua porcaria ainda não se moveu um centímetro.}
{262}{}{Oh sim. Você é escravista agora, eh? Então, o que ele queria? Não vai a lugar algum - não como poderia.}
{263}{}{Ele queria que eu checasse para ele.}
{264}{}{Bem, ele quer ter certeza.}
{265}{}{Deixa pra lá.}

# 8. Failed 1st speech roll for entrance (From 7)
{270}{}{Claro que sim. Eu nunca vi você por aqui antes. Agora, vença.}
{271}{}{Deixe-me entrar agora, antes de ter que ficar com raiva no seu rosto!}
{272}{}{Olha, ele me fez entrar na cidade apenas para inspecionar suas malditas coisas. Eu poderia me preocupar menos.}
{273}{}{OK.}

# 9. Whatever, go in (From 7, 8)
{280}{}{O que quer que seja, escravidão. Apenas vá dentro. Ele acha que só vai subir e sair?
 Quem diabos quereria essa merda?}
{281}{}{Foda-se. Apenas entre. Será que ele pensa que vai subir e sair? Quem
 O inferno quereria essa merda de qualquer maneira?}
{282}{}{Tchau.}

# 10. Don't care. (From 8)
{290}{}{Ok, porra. Não é como se eu realmente me importasse. Como você saberia o que fazer com qualquer uma dessas merdas, mesmo assim.}
{291}{}{Grrrr.}
{292}{}{Obrigado.}

# 11. Threaten, failed (From 8)
{300}{}{Bata, cara duro, antes de me irritar no teu rosto.}
{301}{}{Bata, cadela. Metzger não teria enviado uma mulher de qualquer forma, então faça uma caminhada.}
{302}{}{Cadela? Eu vou mostrar o que essa puta pode fazer.}
{303}{}{Foda-se.}
{304}{}{[Sair]}

# 12. Door = Never (From WTG)
{310}{}{Cai fora.}

# 13. EuName (From 6)
{320}{}{That's nice. EuTyler. Eugo bye bye.}
{321}{}{Ur.}
{322}{}{Uh ...}

# 14. Dumb (From 6, 18)
{330}{}{Bata-o, louco.}
{331}{}{Sukyu!}
{332}{}{Um tapete!}

# 15. Enter, no. (From 8, 16)
{340}{}{Acho que não. Agora vença.}
{341}{}{OK.}
{342}{}{Mas!}
{343}{}{Bem.}

# 16. Metzger Not Known, Search Church (From 6)
{350}{}{Sim, aposto que você é. Quem te enviou?}
{351}{}{Sim, você já disse isso, foda-se. Quem te enviou?}
{352}{}{Quem você acha, idiota? Agora pare de se mexer e me deixar entrar.}
{353}{}{A Pantera Cor de Rosa.}
{354}{}{Ok, você vai se arrepender disso.}

# 17. Pink panther (From 16)
{360}{}{O quê? Saia daqui!}
{361}{}{Mas...}
{362}{}{Bem.}

# 18. Find (From WTG)
{370}{}{Agora, o que diabos o chefe quer? Outra inspetiva insidiosa inspeção?}
{371}{}{Sim?}
{372}{}{E agora?}
{373}{}{Como tá indo?}
{374}{}{Desculpe, tenho que ir.}
{375}{}{Reino Unido.}
{376}{}{Lub?}

# 19. Charisma Good (From 18)
{380}{}{Na verdade, ótimo! Quase esqueci - um amigo meu ganhou grande nas mesas e ele está compartilhando a riqueza, se você sabe o que quero dizer.}
{381}{}{Muito fodido. Odeio guardar - mas, hey, as coisas não podem ser tão ruins. Um amigo meu ganhou grande nas mesas e ele está compartilhando a riqueza, se você sabe o que quero dizer.}
{382}{}{Grandes planos, então?}
{383}{}{Parece divertido.}

# 20. (From 18)
{390}{}{Sim, ele está jogando uma festa esta noite em seu lugar. Deve ser uma explosão.}
{391}{}{Sim, ele está jogando uma festa esta noite em seu lugar. Deve ser uma explosão. I'd invite you, honey, but it's only for his closest friends.}
{392}{}{Algumas cervejas para mim.}
{393}{}{Entendo, obrigado. Diverta-se.}
{394}{}{Até mais.}

# 21. Have fun. (From 20)
{400}{}{É melhor você acreditar! Nós vamos beber até cairmos!}
{401}{}{Tchau}

# 22. Failed, how are you (From 18)
{410}{}{What the fuck do you care. Cai fora.}
{411}{}{Sim, então.}
{412}{}{Você está tentando me irritar?}
{413}{}{Não é ruim.}
{414}{}{Cansado.}
{415}{}{OK.}
{416}{}{Cai fora.}
{417}{}{Estive melhor.}
{418}{}{Oh.}

# 23. CF: Weakness is still set (From WTG)
{430}{}{Não posso esperar por essa festa. Espero que ele tenha algumas putas lá novamente.}
{431}{}{Meu amigo realmente sabe como jogar uma festa.}
{432}{}{Tempo quase de festa.}
{433}{}{Festa! Gostaria de estar lá agora.}

# 24. Gang War = Fight (From WTG)
{440}{}{E ai, como vai? Quase tempo para essa festa.}
{441}{}{Estás bem?}
{442}{}{Tenho algumas informações sobre as quais você pode estar interessado.}
{443}{}{Nada.}
{444}{}{Uhg.}
{445}{}{Urseco?}

# 25. Dumb, Gang War = Fight (From 24)
{450}{}{Porra, o que diabos está errado com você hoje? Apague os chems.}
{451}{}{Os chems são ruins para você, cara.}
{452}{}{Chems são ruins para você, senhora.}
{453}{}{[Grunhido]}

# 26. Information (From 24)
{460}{}{Oh sim? O que é isso?}
{461}{}{Vai custar-lhe.}
{462}{}{Lara está planejando bater neste lugar esta noite.}
{463}{}{Espere um minuto.}

# 27. Float reward (From WTG)
{470}{}{Você ganho isso. Aqui está o seu dinheiro. Eu queria acabar com eles
 por um tempo.}

# 28. It'll cost you (From 26)
{480}{}{Sim, foda-se você. Depende do que é. Você me diz, então vou decidir
 se eu pagar qualquer coisa por isso.}
{481}{}{Lara está planejando bater neste lugar esta noite.}
{482}{}{Não, desculpe.}

# 29. Lara's plan (From 26, 28)
{490}{}{Sério? Então, essa cadela tem algumas bolas depois de tudo? Bem, isso vale $ 100.}
{491}{}{Obrigado.}

# 30. Plan 2 (From 29)
{500}{}{Não tão rápido, liso. Só para ter certeza, vamos esperar até depois mostrarem.
 Você poderia estar mentindo para mim por tudo o que eu conheço. Você só tem certeza de que eles mostram, e eu pagarei você depois.}
{501}{}{Mas eu sou um amante, não um lutador.}
{502}{}{Parece bom.}

# 31. Lover (From 30)
{510}{}{Olha, eu não dou o traseiro de um rato como você é. Eu não estou lhe dando um dólar
 até depois de mostrarem. Vamos fazer a luta, mas é melhor você ter certeza de que eles mostram.}
{511}{}{OK.}

# 32. CF: Can go through door (From WTG)
{600}{}{Então, você é o novo garoto do chefe?}
{601}{}{O que você quer?}
{602}{}{O que há com o Metzger? Ele não confia mais em nós?}
{603}{}{Você já verificou essa merda ainda?}
{604}{}{Disse que a merda de Metzger não estava indo a lugar nenhum.}
{605}{}{Então, você terminou lá ou o quê?}
{606}{}{Tenho certeza de que Metzger precisa de você para algo. Por que você não corre e checa?}
{607}{}{O que diabos está errado com Metzger? Pensando que não estamos guardando sua merda ...}
{608}{}{Você ainda está aqui? Você não tem outra pequena tarefa para concorrer a Metzger?}
{609}{}{Então, você é a nova menina chicoteada do chefe?}

# 12. Additional Never Floats
{700}{}{Eu não estou no clima.}
{701}{}{Agora não.}
{702}{}{Estou ocupado.}

# New Node 33
{710}{}{O burro inteligente está de volta! Então você realmente quer nesta igreja? Por quê? Não há nada aqui que você esteja interessado.}
{711}{}{Agora, que merda você quer?}
{712}{}{Você vê essa marca na minha testa? Deixe-me entrar. Agora!}
{713}{}{Eu sou sua nova cadela, é por isso! Se você não me deixar no momento, eu vou ter certeza de que você se encontra no topo de sua lista de merda.}
{714}{}{Olha, amigo. Metzger vai ter meu esconderijo se eu não inspecionar tudo em breve. Você sabe como ele recebe.}
{715}{}{Não é o seu negócio de merda. Se o chefe quer que sua merda seja verificada, é o que eu faço. Não faço perguntas.}
{716}{}{Deixa pra lá.}
{717}{}{Shaka?}
