{100}{}{Você vê um escravo.}
{101}{}{Você vê Vic.}

{150}{}{Este escravo parece ser mantido sob vigilância apertada.}
{151}{}{Este é Vic.}
{152}{}{[CONVERSA]}

# Node 1
{153}{}{Você poderia dizer a ele que não posso ... aguardo. Quem é Você? Você não é um
 Slaver. O que você está fazendo aqui?}
{154}{}{Meu nome é}
{155}{}{. Estou aqui para tirá-lo.}
{156}{}{Eu estou}
{157}{}{, Mas por que você foi trancado nesta sala?}
{158}{}{Você pode me dizer onde é o Vault 13?}
{159}{}{Eu estou}
{160}{}{. Eu volto já.}
{161}{}{Dubba iba}
{162}{}{.}

# Node 2
{163}{}{Metzger ainda está muito chateado comigo, apesar de arrumarmos seu maldito rádio.
 Ele está ameaçando me vender! Eu farei qualquer coisa que você perguntar se você pode me tirar
 Desta bagunça.}
{164}{}{Sim eu vou.}
{165}{}{Desculpe, não posso. Tchau.}
{166}{}{Whoo.}

# Node 3
{167}{}{Oh, oi novamente. Este rádio maldito não vai se reparar sozinho. Como é que
 Ele espera que eu conserte isso?}
{168}{}{Onde posso obter as peças?}
{169}{}{Talvez eu possa repará-lo.}
{170}{}{Você pode usar este rádio que encontrei?}
{171}{}{Verei o que posso fazer.}
{172}{}{Spa pa?}

# Node 4
{173}{}{Eu sei que posso fazê-lo, eu só preciso das peças sobressalentes. Existe um rádio antigo em
 Minha barraca de volta em Klamath que tem exatamente o que eu preciso. Você foi para o Dunton's?
 Minha barraca ... bem, estava exatamente a leste do lugar deles.}
{174}{}{Você quer dizer esse rádio?}
{175}{}{Eu irei procurá-lo.}
{176}{}{Hmmm ... volto.}

# Node 4b
{206}{}{Está bem aqui. [Apontando para um mapa]}

# Node 5
{177}{}{Isso é ótimo! Eu vou ter o rádio resolvido em nenhum momento.}
{178}{}{Ok, vou falar com Metzger.}

# Node 6
{179}{}{Obrigado.}
{180}{}{Tchau.}

# Node 7
{181}{}{Pardon? Eu estousorry but I don't understand.}
{182}{}{Hurm.}

# Node 8
{183}{}{Thank you! Eu estouforever in your debt. What can I do to repay you?}
{184}{}{Diga-me onde está o Vault 13.}
{186}{}{Venha comigo, eu poderia usar uma mão.}
{187}{}{Não foi nada. Adeus.}
{188}{}{Candy?}

# Node 9
{189}{}{Vault 13? Há uma cidade de Vault ao leste daqui. Eu troco lá,
 as vezes.}
{190}{}{Quer ir comigo?}
{191}{}{Obrigado. Tchau.}

# Node 10
{192}{}{Sure, I’ll join up with you! This old fart has one big adventure left
 in him. Eu estousure of it! Eu estoupretty good at repairing things too, despite what
 Metzger says.}
{193}{}{Ótimo, vamos lá.}
{194}{}{Bem vindo a bordo.}
{195}{}{Tanto faz.}
{196}{}{Vic me bess frend.}

# Node 11
{197}{}{Deseja se juntar a mim na minha pesquisa?}
{198}{}{Ótimo! Obrigado.}

# Node 12 OLD IF IN PARTY. REMOVED NODE. Lines 199, 200, 202 (Don't know where 201 is)

# Node 13
{203}{}{Vault City fica a leste daqui. Vou apontar para o seu mapa.}
{204}{}{Obrigado.}

# Node 14
{220}{}{Darn it. Está perto, mas preciso do rádio da minha cabana em Klamath. Eu sei que tem as partes que eu preciso.}

# used in node 12 REMOVED 230 that was here. Node 12, removed. was What else do you need to know?

# Node 15
{300}{}{Sim, provavelmente posso ajudá-lo, mas você precisa me tirar daqui primeiro.}
{301}{}{Eu te disse. Se você pode me tirar daqui, eu vou ajudá-lo com o que quiser.}
{302}{}{Como fazemos isso?}
{303}{}{Você está sozinho, então.}
{304}{}{Ok, vou ver o que posso fazer.}

# Node 2b
{350}{}{Você acha que pode me ajudar?}
{351}{}{Metzger ainda não me deixa sair.}
{352}{}{Não posso aguentar muito mais disso.}
{353}{}{Eu farei qualquer coisa por você se você me ajudar.}
{354}{}{Recebo todas as despesas que você possa incorrer!}

# 3b
{400}{}{Você ainda não esteve na minha casa? Eu realmente preciso desse rádio,
 Metzger está ficando mais irritado comigo por dia.}

# water flask question, Question used in Node 9 and Node 1010
{450}{}{Onde você pegou este frasco de água?}
{451}{}{Eu tinha um balão de água que tinha um grande amarelo 13 sobre ele. Você se lembra de onde você conseguiu?}

# Additions to Node 11
{500}{}{Oh sim. Eu lembro disso. Comprei isso da Ed. Ele é um comerciante do brahmin em Vault City.}
{501}{}{Frasco de água? Oh espere. Sim, eu tinha algumas dúzias de 'm. Vendido muito bem. Eu tenho de Ed. UMA
 Revendedor brahmin em Vault City.}
{502}{}{Vault City?}

# Node 1000, if said Boss many times.
{550}{}{Você vai parar de me chamar de Chefe?}

# Node 16
{600}{}{Claro, chefe!}
{601}{}{Quero dizer, STOP IT!}
{602}{}{Eu acho que vai ter que fazer.}

# Node 17
{650}{}{Você conseguiu, Sport!}
{651}{}{Uggg!}

{700}{}{Bee meu amigo.}

# Node 1b - Added a line to node 1 for Vic
{710}{}{Você poderia dizer-lhe que não consigo corrigir isso sem as partes. Eu não sei ... aguarde.
 Quem é Você? Alguns recrutas novos? Ele não enviou você aqui para me deixar novamente.
 ele? Não vai fazer diferença. Não consigo corrigi-lo aqui.}

# 20. Here to get you out. (From 1)
{750}{}{Uau! Você faria isso por mim? Eu faria qualquer coisa se pudesse me tirar essa bagunça.
 O único problema é que o Metzger me pegou aqui até eu corrigir esse rádio e
 Eu não tenho as peças que eu preciso.}
{753}{}{Onde posso obter as peças que você precisa?}
{754}{}{Verei o que posso fazer.}

# 21. Why in this room? (From 1)
{760}{}{É uma longa história. Eu acho que você poderia dizer que Metzger está me mantendo aqui até
 Eu reparo esse maldito rádio. O tiro do cristal e eu não temos peças sobressalentes. Como é que
 Ele espera que eu conserte isso?}
{761}{}{Well, Eu estouhere to get you out.}
{764}{}{Não sei. Até mais.}

# 22. Como fazemos isso?
{800}{}{Tenho que corrigir esse rádio. Se você pode me ajudar a fazer isso, então talvez possamos raciocinar com ele.}
{801}{}{Onde posso obter as peças?}
{803}{}{Eu duvido. Boa sorte.}

# 23. In Mom's, never joined party. (From WTG)
{810}{}{Why'd you kill poor Mom… I guess you had your reasons… Eu estousorry, Boss. It's not my place to question you. This is a pretty bad town. Eu estousure she did something pretty bad.}
{811}{}{Ei, chefe. Obrigado por me tirar dessa bagunça com Metzger. Voce precisa de alguma coisa? A mãe tem sido gentil o suficiente para me alimentar enquanto você se foi. Ajudo-a pelo lugar ...}
{812}{}{Tchau.}
{813}{}{Oooh.}
{814}{}{Beiye}

# Additions to Node 9
{823}{}{Onde está seu amigo Ed, novamente?}

# Additions to Node 10
{830}{}{Eu faria, se pudesse, mas você não está ficando bem. Eu só seria um fardo. Agora que mamãe se foi, acho que vou sair. Não sei onde ... talvez nos veremos novamente. Obrigado por tudo o que você fez por mim.}
{831}{}{Eu faria, se pudesse, mas você não está ficando bem. Parece que você mal pode cuidar de si mesmo. Eu só seria um fardo. Vou esperar aqui, a culinária da mãe me faz lembrar da minha ex-esposa ...}
{832}{}{Eu, honesto. Eu faria quase qualquer coisa por você. É só que você não parece que você está em qualquer forma para liderar qualquer um. Eu só seria um fardo. Eu vou dirigir-me para a mãe, um pouco ... até que você possa resolver as coisas. Eu não tive sua cozinha caseira há muito tempo.}
{833}{}{Desculpe, Chefe. Parece que você está muito lotado. Agora que mamãe se foi, acho que vou sair. Não sei onde ... talvez nos veremos novamente. Obrigado por tudo o que você fez por mim.}
{834}{}{Você está um pouco cheio, Boss. Eu espero aqui por você até que você tenha trabalhado as coisas. A culinária da mãe me faz lembrar da minha ex-esposa ... não tenho certeza se é algo bom ou ruim ...}
{835}{}{Eu adoraria, chefe. É só que você não parece ter mais espaço. Vou dirigir-me para a mãe. Eu não estive lá há algum tempo. Apenas venha me buscar se você encontrar algum espaço para mim.}

# Additions to Node 11
{840}{}{Ed está no Vault City. Ele é um revendedor brahmin. Ele era apenas um dos meus muitos fornecedores. Vault City não está longe daqui.}

# Additions to Node 13
{845}{}{Eu disse que está aqui. [Vic aponta para uma localização no seu PIPBoy2000.]}

{900}{}{Você aprendeu sobre Vic ser comerciante.}

# 1000 in party dialog
{1000}{}{Eu preciso te perguntar uma coisa.}

# 1001 After healing
{1100}{}{Totalmente curado, chefe. Algo mais?}
{1200}{}{Condição quase perfeita, chefe.}
{1300}{}{Eu estoumostly heled up, Boss, but I've been better.}
{1400}{}{I tried, Boss, but Eu estounot doing so hot. I'll do what I can though.}

# 1002 I need you to wait here until I come back
{1500}{}{O que quer que você diga, chefe.}
{1501}{}{Aqui? Bem aqui? Ok, você é o chefe.}
{1502}{}{Certo. Eu vou ficar aqui até você voltar, chefe. Você vai voltar, certo?}
{1503}{}{As long as you want. Eu estounot going anywhere.}
{1504}{}{Claro, chefe.}

# 1003 Put your weapon away.
{1600}{}{Se você diz.}
{1601}{}{Boa chamada Boss.}
{1602}{}{Um grande pensamento, chefe.}
{1603}{}{Claro, chefe. Algo mais?}
{1604}{}{Lá é, chefe.}
{1605}{}{Não há problema, chefe.}
{1606}{}{Feito, Chefe.}

# 1004 Stay close to me
{1700}{}{Claro, chefe.}
{1701}{}{Feche, Boss.}
{1702}{}{Você sabe melhor, Boss.}
{1703}{}{Eu estouright behind ya, Boss.}
{1704}{}{Como cola, chefe.}
{1705}{}{Se você diz, chefe.}
{1706}{}{Oh. Ok, chefe.}

# 1005 Don't get too far away.
{1800}{}{OK, vou manter minha distância, mas não muito longe, Boss.}
{1801}{}{Ok, não vou, chefe.}
{1802}{}{Só vou ficar um pouco atrás, chefe.}
{1803}{}{Claro, chefe.}

# 1006 We should spread out a bit
{1900}{}{Chefe direito. Eu vou ficar de volta.}
{1901}{}{O que quer que você diga, chefe.}
{1902}{}{Lá você vai, chefe.}
{1903}{}{De pé, chefe.}
{1904}{}{Saindo, chefe.}
{1905}{}{Espalhando, chefe.}
{1906}{}{Ok, chefe.}

# 1100a Rejoin: Crowded
{2000}{}{Uh, chefe? Você parece um pouco cheio. Vou aguardar aqui por você.}

# 1100b Rejoin: Additional NPC response, PC Charisma 1
{2100}{}{Você está me assustando, chefe. O que aconteceu com você? Você parece bem,
 assustador. Eu acho que vou sair aqui por um tempo ...}

# 1100c Rejoin:
{2200}{}{Você aposta, Chefe!}
{2201}{}{Darn, certo, eu vou, chefe.}
{2202}{}{Claro, chefe.}
{2203}{}{Pronto para ir quando você estiver, chefe.}
{2204}{}{Ótimo! Vamos.}
{2205}{}{Ótimo!}
{2206}{}{Você é o melhor, chefe!}
{2207}{}{Você não ficará desapontado. Não há mais erros!}
{2208}{}{Eu terei cuidado desta vez, não se preocupe!}
{2209}{}{Eu sabia que você me perdoaria por isso ... um. Então, uh, chefe. Qual é o plano?}
{2210}{}{Eu não vou decepcioná-lo, chefe!}
{2211}{}{Você é super, chefe!}
{2212}{}{Eu sabia que não era muito velho para isso. Essas eram apenas más chances! Certo, Chefe?}

# 1007 Vault 13 Flask?
{2300}{}{De Ed. Ele é um comerciante do brahmin em Vault City. Você já esteve lá antes?
 Deixe-me mostrar-lhe sobre esse mapa sua.}

# 1008 Where's Ed again? Not Marked
{2305}{}{Vault City. Aqui. Deixe-me mostrar-lhe esse mapa elegante do seu.}

# 1009 Where's Ed again?
{2310}{}{Ele deveria estar por aqui em algum lugar.}
{2311}{}{Vault City. Verifique se esse mapa sofisticado é seu.}

# 1010 Other Questions
{2403}{}{Onde você pegou o balão de água do Vault 13?}
{2404}{}{Deixa pra lá.}

# 1011 Other questions greeting (From 1000)
{2500}{}{Claro, chefe.}
{2501}{}{Pergunte a qualquer coisa, chefe.}
{2502}{}{Eu vou ajudá-lo se puder, chefe.}
{2503}{}{Eu estounot in trouble am I, Boss?}
{2504}{}{Eu fiz algo errado, chefe?}
{2505}{}{Claro.}

# 1012 Standard Greeting, (WTG) Moved From Node 1000
{2600}{}{O que faremos agora, chefe?}
{2601}{}{Qual é o plano, Chefe?}
{2602}{}{Fazendo o meu melhor, chefe.}
{2603}{}{O que posso fazer por você, Chefe?}
{2604}{}{Mudança de planos, Chefe?}
{2605}{}{Estratégia diferente, Chefe?}

# 1013 Crippled
{2700}{}{Chefe, eles me deram bem. Você deve me levar ao médico. Não sei se posso
 Mais você está de volta.}
{2701}{}{I need a doctor, Boss. Eu estoureally messed up. I don't know if I can fight
 with you anymore.}
{2702}{}{Boss, Eu estoureally messed up. You got to get Lenny to check me out.}

# 1014 Waiting
{2800}{}{Ei, chefe. Você quer que eu participe de você?}
{2801}{}{Hey, Boss. I don't mind waiting for you. Eu estoua real patient man.}
{2802}{}{Nós nos juntamos novamente, Boss? Vou tentar mais.}
{2803}{}{Eu estava com medo que você não voltasse. Com certeza, é bom ver você de novo, chefe.}
{2804}{}{Você procura empresa novamente?}
{2805}{}{Eu estouready to go, Boss.}
{2806}{}{Eu sabia que você não iria me deixar.}
{2807}{}{Precisa de alguma cópia de segurança?}
{2808}{}{Need something repaired, don't you? Eu estouyour man, Boss!}
{2809}{}{Não se preocupe, chefe. Sulik e eu vamos nos dar bem, honesto.}
{2810}{}{Vamos.}
{2811}{}{Stay here. Eu volto já.}
{2812}{}{Eu vou.}

# 1017 Remove armor: Yes
{3100}{}{O que? Uh… okay, Boss. Se você diz.}
{3101}{}{Can I put something else on, Boss? Eu estoua little worried.}
{3102}{}{Ok ... você não vai me deixar aqui ... Você é, chefe?}
{3103}{}{But… I mean… Claro, chefe. Coming right off.}

# 1018 Best Weapon
{3200}{}{Well, Boss…. Eu estoupretty good with small arms. I can handle almost any rifle, shotgun, and most small-medium pistols. I 'can' use knives. I've also got a pretty good throwing arm, but my aim's not the best in the world… actually it's pretty horrible. Sorry, Boss. Eu estoureally trying to get better.}
{3201}{}{Como eu disse, chefe, eu prefiro armas pequenas. Eu posso lidar com quase qualquer rifle, espingarda e a maioria dessas pistolas de pequeno e médio. Se estamos realmente em uma pitada eu posso tentar usar uma faca ou mesmo armas jogadas.}

# 1019 Other weapons he can use.
{3300}{}{I 'can' use knives and I've got a pretty good throwing arm, but… my aim's not the best in the world. Actually it's pretty horrible. Sorry, Boss. Eu estoureally trying to get better.}
{3301}{}{Como eu disse, chefe. Facas e eu tenho muito bom braço jogando ... Eu apenas sinto falta de muita coisa.}

# 1020 Hostile
{3400}{}{Eu tive-o até aqui!}
{3401}{}{Eu estougoing to rip your darn head off! No one hurts my family!}

# 1101 Vic's being Pushed
{4000}{}{Por aqui?}
{4001}{}{Esse chefe melhor?}
{4002}{}{Que tal aqui?}
{4003}{}{Sim chefe.}
{4004}{}{O que?}
{4005}{}{Onde estamos indo?}
{4006}{}{Nós deixamos Boss?}
{4007}{}{Eu estoumoving.}
{4008}{}{Desculpe Boss.}
{4009}{}{Melhor?}
{4010}{}{Ooof.}
{4011}{}{Como é esse chefe?}
{4012}{}{Eu vou ficar por aqui.}
{4013}{}{Vou passar aqui agora.}

# 1102 BGF: Crippled
{4100}{}{Boss! Eu estounot doing so well here.}
{4101}{}{Eu preciso de um doutor.}
{4102}{}{Oh garoto. Isso realmente dói.}
{4103}{}{Ow!}
{4104}{}{Ouch.}
{4105}{}{Dang.}
{4106}{}{Médico?}
{4107}{}{Eu estouhanging in there… barely.}

# 1103 Removed

# 1104 BGF: Random on Specific Map
{4200}{}{Eu nunca gostei desse lugar.}
{4201}{}{Por que esse lugar é tão limpo?}
{4202}{}{Você cheira alguma coisa, chefe?}
{4203}{}{Você sabe, chefe. Não acho que voltarei aqui quando terminarmos. Eu não posso mais chamá-lo para casa.}
{4204}{}{Com certeza, é muito mais sujo do que eu lembro.}
{4205}{}{Nós não ficamos aqui por muito tempo, nós somos chefe?}
{4206}{}{Este lugar nunca mudará.}
{4207}{}{Boss, Eu estounot going to miss this place.}
{4208}{}{Obrigado novamente por me tirar desse lugar, Boss.}
{4209}{}{Eu realmente te devo um, chefe.}
{4210}{}{Uau, este lugar com certeza mudou.}
{4211}{}{Eu não estive aqui há séculos.}
{4212}{}{Eu estougoing to retire here.}
{4213}{}{Eu poderia abrir uma loja de reparo por aqui.}

# 1105 BGF: for specific area on a map
{4300}{}{Ah, um site para olhos doloridos. Este é ... foi meu lugar, mas acho que você sabia disso. Certo, Chefe?}

# 1106 Removed

# 1107 BGF: with Specific NPC
{4400}{}{Sulik, você não está me olhando desse jeito.}
{4401}{}{Chefe, Sulik está me olhando de novo.}
{4402}{}{Bom cachorrinho.}

# 1108. BGF: Level Up, Not to be Placed in MSG file

# 1109. BGF: Waiting
{4500}{}{La de da ...}
{4501}{}{Ho hum.}
{4502}{}{Esperando o Chefe ....}
{4503}{}{Eu estouwaiting for the Boss.}
{4504}{}{Apenas esperando.}
{4505}{}{O Chefe, com certeza, não me deixaria para trás ....}
{4506}{}{Knock Knock ... quem está lá ... espera. Como foi isso ...}
{4507}{}{Ainda esperando.}
{4508}{}{Que cheiro é esse?}
{4509}{}{Alguma coisa para reparar por aqui?}
{4510}{}{Aqui estou ... esperando pelo Chefe.}
{4511}{}{Um homem velho como eu, desperdiçando seus talentos, apenas parado aqui.}
{4512}{}{Eu certamente gostaria de ter uma vara de goma ... foram décadas.}
{4513}{}{Eu preciso sair do negócio da relíquia ... nada além de problemas.}
{4514}{}{Por que está esperando tão cansativo ...?}

# 1110. PC used Healing on PC
{4600}{}{Uh, obrigado, chefe.}
{4601}{}{Obrigado.}
{4602}{}{Você sabe o que está fazendo?}
{4603}{}{Não podemos simplesmente descansar?}
{4604}{}{Devemos fazer acampamento?}
{4605}{}{Eu estou tão mal?}

# 1111. PC used Drugs on NPC
{4700}{}{Não muito, chefe.}
{4701}{}{Se você insistir, chefe.}
{4702}{}{Chefe, minha cabeça não vai explodir, não é?}
{4703}{}{Boss, I think Eu estoustarting to like that stuff.}
{4704}{}{Eu estoufeeling a bit funny, Boss.}
{4705}{}{Você tem certeza de que tem o suficiente para poupar.}
{4706}{}{Claro, chefe. I'll take some.}
{4707}{}{Obrigado, chefe.}
{4708}{}{Não é ruim.}
