# 0. Look
{100}{}{Você vê um escravo.}

{150}{}{Ele parece estar prestando muita atenção à porta ao lado dele.}

# 1. Self Initiated Floats
{200}{}{Ei! Mãos fora.}
{201}{}{É isso aí!}

# 2. Open Door 1 - Self Initiated Floats
{210}{}{Problemas?}
{211}{}{Praticando?}
{212}{}{Hmmm.}

# 3. Open Door 2 - Self Initiated Floats (From 9, 16)
{220}{}{Ai está.}

# 4. Starting Node (From Where to go)
{230}{}{Ei, como está indo?}
{231}{}{Ei, você se juntou, né? Legal. Espero que vamos em algumas corridas juntas.}
{232}{}{Então, do que você quer falar?}
{233}{}{Então, quem está aí?}
{234}{}{Sobre Vic ...}
{235}{}{Bom, obrigado.}
{236}{}{Tenho que ir.}
{237}{}{Wuk?}
{238}{}{Meko veek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}

# 5. Who's that? & Sobre Vic ... (From 4)
{250}{}{Seu nome é Vic - um comerciante que quebrou algo do meu chefe, ou algo assim. Não tenho muita certeza.}
{251}{}{Seu nome é Vic - um comerciante que quebrou algo do chefe, ou algo assim. Não tenho muita certeza.}
{252}{}{Ah, ele? Sim, algum comerciante. Eu acho que ele quebrou algo, mas não tenho certeza. Por quê? Você o conhece?}
{253}{}{Ah, ele? Sim, algum comerciante. Eu acho que ele quebrou algo, mas não tenho certeza. Por quê? Você o conhece?}
{254}{}{Sim?}
{255}{}{Por que você está protegendo ele?}
{256}{}{Quem é o seu chefe?}
{257}{}{Posso vê-lo?}
{258}{}{Bem, sou bastante especialista em reparar coisas. Talvez eu poderia ajudar?}
{259}{}{Bem, sou bastante especialista em ciências, talvez eu possa ajudar?}
{260}{}{A porta está trancada. Você poderia abri-lo?}
{261}{}{Obrigado.}

# 6. Guard Will let PC see Vic. (From 18)
{275}{}{Obrigado pelo dinheiro. Estou apenas deixando você falar com ele. Não há coisas engraçadas. Ele não pode sair daquele quarto sem a aprovação de Metzger.}
{276}{}{Agora, estou deixando você falar com ele, ok? Não há coisas engraçadas. Ele não pode sair daquele quarto sem a aprovação de Metzger.}
{277}{}{OK.}

# 7. Why guarding Vic (From 5)
{285}{}{Para ter certeza de que ninguém o bicho enquanto ele trabalha em algo para o chefe, mas principalmente para ter certeza de que ele não foge.}
{286}{}{Apenas para ter certeza de que ele não foge, acho. Ele reparou de alguma forma esse rádio.}
{287}{}{Quem é o seu chefe?}
{288}{}{Posso vê-lo?}
{289}{}{Posso vê-lo?}
{290}{}{Ok, obrigado.}

# 8. Can I see him - Slaver (From 7)
{295}{}{Ah com certeza. Eu não quis dizer que você poderia vê-lo, agora que você é um escravista e tudo mais.}
{296}{}{Ah com certeza. Eu acho. Ele não está ocupado e ele não vai a lugar algum, então não há mal, acho.}
{297}{}{Bem, você poderia abrir a porta então?}
{298}{}{Ok, obrigado.}

# 9. Unlock door, Okay to see (From 5, 8)
{305}{}{Claro. Eu não sabia que queria falar com ele agora, desculpe. Eu simplesmente pensei que você estava curioso ou algo assim.}
{306}{}{Obrigado.}

# 10. Quem é o seu chefe? (From 5, 7, 18)
{310}{}{Hã? Você tem o hábito de caminhar em lugares que você não conhece? Este é o Slaver's Guild.}
{311}{}{Oh, então isso faria o nome do seu chefe ...}
{312}{}{Ah, é onde eu estou? Embora eu estivesse no Kansas.}
{313}{}{Ok, obrigado.}

# 11. Kansas (From 10)
{320}{}{Onde? Não, nunca ouvi falar disso. Este é o Den. Não tenho certeza sobre esse lugar, mas não saio muito. Desculpa.}
{321}{}{Idiota.}
{322}{}{Uh, okay. Obrigado.}

# 12. Don't know Boss? (From 10)
{330}{}{Caramba cara. Metzger é o mestre escravo. Ele corre por aqui.}
{331}{}{Maldita senhora. Este é o último lugar, uma senhora como você gostaria de ser. Metzger é o mestre escravo.}
{332}{}{Ah, onde está o escritório dele?}
{333}{}{Tudo bem tchau.}

# 13. Where's his office? (From 12)
{340}{}{Através da porta das costas lá.}
{341}{}{Obrigado.}

# 14. Dumb Exit (From 4, 15, 20)
{350}{}{Desculpe, não entendo.}
{351}{}{Hmph.}

# 15. Dumb Vic ? (From 4)
{360}{}{Desculpe, Vic não recebe visitantes.}
{361}{}{Sim, é Vic.}
{362}{}{Seve?}
{363}{}{Surek?}
{364}{}{Gaw.}

# 16. Dumb Can See Vic (From 15)
{370}{}{Claro, você pode vê-lo.}
{371}{}{Claro, você pode vê-lo. Let me unlock that for you.}
{372}{}{Tanque.}

# 17. Repair or Science skills (From 5)
{380}{}{Sério? Tenho certeza de que o chefe apreciaria isso. Apenas enquanto ele permaneça colocado. Não queremos que ele fique novamente.}
{381}{}{Obrigado.}

# 18. Can I see Vic? (From 5, 7)
{390}{}{Não, desculpe. Ele está ocupado trabalhando em algo para o chefe.}
{391}{}{Desculpe, não posso fazer isso. Ordens diretas do chefe.}
{392}{}{Bem, você conseguiu meu dinheiro?}
{393}{}{Eu só preciso lhe fazer algumas perguntas.}
{394}{}{Oh vamos lá. Apenas deixe-me falar com ele muito rápido.}
{395}{}{Sim. Aqui.}
{396}{}{Não vou voltar.}
{397}{}{Quem é o seu chefe?}
{398}{}{Deixa pra lá. Tchau.}

# 19. See Vic is Never (From )
{410}{}{Pare de me incomodar. Vá falar com Metzger. Ele é o chefe.}
{411}{}{Me deixe em paz! Qual é o seu problema?}
{412}{}{Eu disse conversar com Metzger!}
{413}{}{Certo, tudo bem! Você pode conversar com ele, mas é isso! Ele não está pisando um pé fora daquele quarto. Consegui? Agora vença!}
{414}{}{OK.}
{415}{}{Obrigado!}

# 20. Wuk? (From 4)
{430}{}{Sim, fale com Metzger. Tenho certeza de que ele tem algum trabalho disponível. Eu acho que ele disse que precisava de outro homem.}
{431}{}{Sim, fale com Metzger. Tenho certeza de que ele tem algum trabalho disponível. Ele disse que precisava de outro homem ... mas tenho certeza que você fará.}
{432}{}{Fale com Metzger.}
{433}{}{Ruru?}
{434}{}{Uh?}
{435}{}{Oh.}

# 21. Hostile (From Where to go)
{450}{}{Pegue-o, pessoal.}
{451}{}{Pegue-a, caras.}

# 22. Just a few questions. (From 18)
{460}{}{Ele está ocupado.}
{461}{}{Por favor, ele não vai sair da sala. Eu prometo.}
{462}{}{Não podemos resolver algo - financeiramente, talvez?}
{463}{}{Tudo bem tchau.}

# 23. Bribe 1 (From 22)
{470}{}{Bem, eu ... eu não sei. Eu acho que não faria mal apenas para você falar com ele. $ 300 e eu vou deixar você entrar.}
{471}{}{Você está louco. Isso é demais!}
{472}{}{Toque você, amigo!}
{473}{}{Certo.}
{474}{}{Desculpe, não posso pagar isso.}

# 24. Bem. (From 22)
{480}{}{Tudo bem, veja se eu me importo.}
{481}{}{OK.}
{482}{}{Bem.}

# 25. No. (From 23)
{490}{}{Não, desculpe.}
{491}{}{Eu disse não. Agora vença. Você deve conversar com Metzger}
{492}{}{OK.}

# 26. Vic Free (From Where to go)
{500}{}{Para mal, você não se juntou a nós.}
{501}{}{Você deve se juntar à guilda.}
{502}{}{Apenas fazendo essa coisa de guarda.}
{503}{}{Hope Vic trabalha para você.}
{504}{}{Vic melhor estar trabalhando duro para você.}
{505}{}{Talvez eu possa te pegar em uma corrida.}
{506}{}{Como tá indo?}
{507}{}{Oi de novo.}
