# 0. Look
{100}{}{Você vê um quadro de avisos.}

{150}{}{Parece haver algumas mensagens postadas nela.}

# 1. Main Page
{200}{}{Den Bulletin: Mantido pelo Rebecca's Casino Bar, melhores bebidas no Den.}
{201}{}{Den Bulletin: Mantido pelo Rebecca's Casino Bar ...}
{202}{}{[Alguém escreveu algo no lado desta postagem.]}
{203}{}{[Você percebe que uma parte desta publicação foi arrancada.]}
{204}{}{Slaver's Guild}
{205}{}{Barras e jogos de azar}
{206}{}{Jantar}
{207}{}{Lojas}

# 2. Slaver's Guild
{225}{}{The Slavers's Guild é o melhor e único fornecedor de escravos nos resíduos.}

# 3. Slaver's - Continuar
{250}{}{Para oportunidades de emprego, compra ou venda de escravos, veja Slave Master Metzger.}

# 4. Slaver's - Directions
{275}{}{O Slaver's Guild está localizado no lado leste da cidade, passado Becky's e Frankie's.}

# 5. Slaver's - Not selling
{300}{}{Atualmente, eles não estão vendendo escravos para o público em geral, devido ao aumento da demanda.}

# 6. Bars and Gambling
{325}{}{[Dois estão listados.]}

# 7. Becky's Casino Bar
{350}{}{Rebecca's Casino Bar tem jogos de azar e excelentes bebidas acessíveis.}

# 8. Becky's Directions.
{375}{}{Estamos localizados a leste daqui. Nós somos o primeiro edifício à esquerda como você entra na cidade. Certifique-se de passar e dizer olá!}

# 9. Frankie's Message
{400}{}{Becky é uma ferida e suas bebidas são diluídas! Ela é uma cachorrinha e um mentiroso! [A escrita é praticamente legível.]}
{401}{}{[A mensagem que estava aqui está arrumada.]}

# 10. Dumb Board
{425}{}{Palavras palavras ... por ... palavras ... Bar ... palavras ... no Den.}
{426}{}{Você achou tudo muito confuso e sua cabeça começa a doer.}

# 11. Frankie's
{450}{}{Frankie dirige um bar, uma pousada e um negócio de "prazer" no lado leste da cidade.}

# 12. Jantar
{475}{}{Mamãe é o único restaurante no Den. Ela está localizada no lado leste da cidade, ao sul da Slaver's Guild.}

# 13. Becky Dead
{500}{}{[Parece que alguém tentou incendiar. Você não pode distinguir nenhuma das postagens.]}

# 14. Lojas
{525}{}{[Existem três posts.]}

# 15. Tubby's
{550}{}{Tubby vende todos os tipos de itens, mas principalmente chems e munições.}

# 16. Tubby's Directions
{575}{}{O Tubby's está localizado a oeste deste quadro de avisos. É o primeiro edifício à direita, à medida que você entra na cidade.}

# 17. Flick
{600}{}{Flick vende vários itens de seu "escritório" no prédio residencial diretamente a sul a partir daqui e logo abaixo do Rebecca's Casino Bar.}

# 18. Smitty
{625}{}{Smitty é o mecânico local. Ele às vezes tem coisas à venda.}

# 19. Smitty Directions
{650}{}{Smitty's localizado no junkyard no canto sudoeste da cidade.}

# MENU OPTIONS
{1000}{}{Continuar}
{1010}{}{Instruções:}
{1020}{}{Saída}
{1030}{}{Flick's}
{1040}{}{Frankie's}
{1050}{}{Rebecca's Casino Bar}
{1060}{}{Retornar para a Página principal}
{1070}{}{Smitty}
{1080}{}{Nota especial:}
{1090}{}{Tubby's}s
