{100}{}{Um homem em armadura de poder.}
{101}{}{Arthur, filho de Uther Pendragon.}
{102}{}{Sua mosca está baixa.}
{103}{}{Salve, viajantes. Meu nome é Arthur, filho de Uther Pendragon, da Brotherhood of Steel. Nós
 estão em busca da Granada de mão sagrada de Antioquia. Você viu isso?}
{104}{}{O que é de quem?}
{105}{}{Resposta do jogador}
{106}{}{Unga.}
{107}{}{Não há tempo para conversar. Estamos na busca.}
{108}{}{Buscamos a Granada de mão sagrada de Antioquia.}
{109}{}{Para a Irmandade do Aço!}
{110}{}{Hmm ... Andorinha africana ou europeia?}
{111}{}{Ei agora! Isso não é seu, não é?}
{112}{}{Estou te avisando. Mantenha suas mãos para si mesmo.}
{113}{}{É isso aí. Já é suficiente.}
{114}{}{A Granada de mão sagrada de Antioquia? Por que, é apenas a maior mão, arma anti-pessoal
 de seu tipo.}
{115}{}{Por que você procura por uma arma tão terrível?}
{116}{}{Nós da Brotherhood of Steel procuramos encontrar esta arma mais devastadora de nossos antepassados, e
 assegure-o daqueles que abusariam do poder da Sagrada Grade Mágica de Antioquia.}
{117}{}{Por quê?}
{118}{}{Bem ... porque a Brotherhood of Steel é dedicada a proteger os fracos e indefesos, e
 Isso poderia machucar alguém.}
{119}{}{Por quê?}
{120}{}{Umm ... porque é realmente a única coisa moral a fazer.}
{121}{}{Por quê?}
{122}{}{Wha ... um ... Olhe agora, estamos muito ocupados. Você vai nos ajudar ou não? Você viu
 a Granada de mão sagrada de Antioquia ou não?}
{123}{}{Sim.}
{124}{}{Não.}
{125}{}{Bem, por que você não disse? Se você pudesse nos dizer onde, vamos sair e você pode obter
 De volta ao que quer que você esteja fazendo.}
{126}{}{[Você aponta em uma direção aleatória.]}
{127}{}{Certo então. Obrigado pela ajuda. Alguma coisa para o seu problema.}
{128}{}{Esperar! Eu também estou em questão. Procuro o sagrado GECK. Você já viu?}
{129}{}{Bem, não há sentido em continuar essa conversa. Estavam fora.}
{130}{}{[FIM]}
{131}{}{Camaleão sangrento!}
{132}{}{[FIM]}
{133}{}{GECK, você disse? Por que sim, temos dois deles. Não precisa de outro. Agradece a todos a mesma
 Apesar.}
{134}{}{Como você tem dois deles, talvez você possa me dar um.}
{135}{}{Não. Não. Couldn't do that. Wouldn't be right to end your quest that easily. There's some more
 of them that way. Go get your own. [He points in a direction about the same way you pointed when you
 told him where the Holy Hand Grenade of Antioch was.]}
{136}{}{[FIM]}

{200}{}{Você fala a língua do rei?}
{201}{}{Hellooo.}
{202}{}{Ei, estou aqui.}
{203}{}{Se você pudesse poupar um momento do seu tempo.}
{204}{}{Ahem.}
{205}{}{Agora vamos. Não me ignore.}
{206}{}{Pleeeease! Preciso lhe perguntar algo importante.}

{207}{}{Bem, devemos continuar nossa busca pela Granada de Mãos de Antioquia. Venha, Patsy.}
