{100}{}{Você vê um enorme tijolo de um homem.}
{101}{}{Você vê um enorme tijolo de um homem.}
{102}{}{Ele é um gigante de um homem e provavelmente come pessoas como você para o café da manhã.}
{103}{}{Velho, você virá conosco.}
{104}{}{Nos deixe em paz. Nunca apoiarei a causa de seus superiores.}
{105}{}{Não vou pedir novamente. Venha agora, ou você será feito um exemplo de.}
{106}{}{Prefiro que conhecimento eu tenha desaparecido comigo no túmulo.}
{107}{}{Que assim seja. Mate todos.}
{108}{}{Este não é seu caso. Vire-se e vá embora.}
{109}{}{Você parece encontrar algumas pessoas no lugar errado na hora errada.}
