{100}{}{Um homem em armadura de poder.}
{101}{}{Sir Bedemir.}
{102}{}{Ele parece ser um pensamento profundo.}
{103}{}{Sir Bedemir ao seu serviço.}
{104}{}{... e é assim que sabemos que a Terra é em forma de banana.}
{105}{}{Deixe-me explicar como as veias de ovelhas podem ser empregadas para prevenir terremotos.}
{106}{}{Preciso de algum tempo para pensar. Por favor, vá incomodar alguém.}

{200}{}{Aqui agora! Suas mãos estão geladas!}
{201}{}{Isso não pertence a você.}
{202}{}{Ei, essas são minhas coisas!}
