{100}{}{Você vê um grande monumento de pedra que parece ser ... murmurando para si mesmo?}
{101}{}{Você vê um monumento de pedra da cabeça do morador da abóbada. É uma semelhança muito lisonjeira, porém
 Você duvida que a cabeça do morador do Vault fosse na verdade desse tamanho.}
{102}{}{Você vê um grande monumento de pedra.}
{103}{}{Você vê um monumento de pedra da cabeça do morador da abóbada. É uma semelhança muito lisonjeira, porém
 Você duvida que a cabeça do morador do Vault fosse na verdade desse tamanho.}
{104}{}{Malditos turistas ...}
{105}{}{"Eu sou o Escolhido". Que crapola.}
{106}{}{Se eu fosse você, "Escolhido", eu saía daqui.}
{107}{}{Zzzzzz Snzzzzz Zzzzzzzzzz}
{108}{}{ZZZZZZZzzzzzzzz}
{109}{}{Zsnzzz ... * snort * ... zzzzsZZZZZ}
{110}{}{Zzssnnnnnzzzzz}
{111}{}{ZZZZzzzzzZZZZZ}
{112}{}{Eu queria ver o que está por trás de mim.}
{113}{}{Se apenas alguém viesse e cavasse o resto de mim ...}
{114}{}{Tenho certeza de que essas formigas comendo pedras estarão a qualquer momento para me devorar.}
{115}{}{"Seja uma grande cabeça de pedra! Veja o mundo!" O que é uma culpa.}
{116}{}{É um mistério para mim como acabei aqui no deserto.}
{117}{}{Ainda não vejo por que tenho que me sentar aqui no deserto, enquanto essa outra cabeça fica pendurada
 Na aldeia.}
{118}{}{Quero dizer, ele é adorado e limpo e rezou para ... tudo o que consigo é olhar para a areia o dia todo.}
{119}{}{Ouvi esses caras na Ilha de Páscoa ficam muito bons.}
{120}{}{Aposto que Stonehenge recebe mais visitantes que eu.}
{121}{}{Hrnnfff ... uh-uh, mãe ... não há escola hoje ... Zsnzzzzz}
{122}{}{Zzzsnnnzzzz ... Eu não quero levantar até ... Zzznnsss}
{123}{}{Zzsssccs ... eh?}
{124}{}{Wha--?}
{125}{}{GET YOUR DAMN HANDS OFFA ME!}
{126}{}{O jogador deve se virar, dar alguns passos para trás, depois voltar e enfrentar o monumento.}
{127}{}{* Ahem *}
{128}{}{QUEM PROIBA A APROXIMAÇÃO DA CABEÇA SAGRADA DO VAQUEIRO ?!}
{129}{}{É eu, o Escolhido.}
{130}{}{HA HA HA HA HA HA!}
{131}{}{*VOCÊ*?! O ESCOLHIDO?!}
{132}{}{VOCÊ NÃO É MAIS GRANDE DO QUE MEU DEDO!}
{133}{}{VOCÊ NÃO É * O ESCOLHIDO.}
{134}{}{Sim eu estou.}
{135}{}{NÃO, VOCÊ NÃO É.}
{136}{}{Sim eu estou.}
{137}{}{UH-UH.}
{138}{}{Uh-huh.}
{139}{}{UH-UH.}
{140}{}{Uh-huh.}
{141}{}{UH ... UH ...}
{142}{}{Uh ... eh ...}
{143}{}{UH ... BASTANTE DESTE!}
{144}{}{MUITO BEM! VOCÊ TE PROVOU!}
{145}{}{VOCÊ * É * O ESCOLHIDO!}
{146}{}{PEGUE ISSO!}
{147}{}{AGORA ME DEIXE!}
{148}{}{Ei, obrigado!}
{149}{}{TANTO FAZ. AGORA TENHA AQUI AQUI.}
{150}{}{TURISTAS DAMADOS.}
{151}{}{Eu já te dei um presente.}
{152}{}{BEGONE!}
{153}{}{Idiota.}
{154}{}{O QUE?! ROLE DE MIM, VOCE ?!}
{155}{}{MORRER!}
{156}{}{Desintegre o jogador com a animação da morte por plasma.}

{200}{}{(12 horas mais tarde)}
