{100}{}{Você vê ... um modelo de herói preto.}
{101}{}{Você vê um homem preto pesadamente musculoso em um macacão Vault 13. Ele está olhando para você com ressentimento.}
{102}{}{Você vê um modelo de herói preto. Ele está olhando para você com ressentimento.}
{103}{}{Você vê um modelo de herói preto. Ele está olhando para você com ressentimento.}
{104}{}{Eu era originalmente um dos modelos heróis da Fallout 1.}
{105}{}{Claro, * * * não fiz o corte final.}
{106}{}{Eles alegaram que era "muita animação". "Muitos quadros", disseram eles.}
{107}{}{Eu sou preto. * Você * descobrir.}
{108}{}{Toda vez que você acha que está ficando à frente, Whitey muda as regras.}
{109}{}{Gostaria de poder colocar as minhas mãos ...}
