{100}{}{Você vê o Guardião da Ponte da Morte.}
{101}{}{Você vê um homem de olhos curtos com uma barba desordenada e uma voz raspada. O olho esquerdo parece que é
 sobre pronto para saltar de sua cabeça.}
{102}{}{Você vê o Guardião da Ponte da Morte.}
{103}{}{Você vê um homem de olhos curtos com uma barba desordenada e uma voz raspada. O olho esquerdo parece que é
 sobre pronto para saltar de sua cabeça.}
{104}{}{Pare! Quem atravessaria a Ponte da Morte deveria responder-me a estas perguntas três, antes da
 Outro lado ele vê.}
{105}{}{Cee ... Deeee ... Eee ... Ffff ... Gggg}
{106}{}{Desliga.}
{107}{}{Muito bem.}
{108}{}{Pergunte-me as perguntas, pontífice. Eu não estou com medo.}
{109}{}{Talvez eu volte mais tarde.}
{110}{}{Qual é o seu nome?}
{111}{}{Hhhh .... Olho ... Jay ... Kay ... Lell ...}
{112}{}{?}
{113}{}{Eu} #continue at 172
{114}{}{Desliga.}
{115}{}{de Arroyo.}
{116}{}{Harry}
{117}{}{Hakuin}
{118}{}{Testocles}
{119}{}{Richard Gray}
{120}{}{Seymour Heine}
{121}{}{O Escolhido!}
{122}{}{Talvez eu volte mais tarde.}
{123}{}{Qual é a sua missão?}
{124}{}{Mmmm .... nnnn .... oh ... peee}
{125}{}{GEK. Arro-yo}
{126}{}{(Shamble off)}
{127}{}{Para procurar o sagrado GECK.}
{128}{}{Para procurar uma maneira de salvar minha aldeia.}
{129}{}{Para encontrar minha tribo sequestrada.}
{130}{}{Para consertar um petroleiro quebrado.}
{131}{}{Uh ... quest?}
{132}{}{Talvez eu apenas volte quando você está se sentindo um pouco melhor.}
{133}{}{O personagem não-jogador da Fallout 1 sobreviveu para aparecer na sequela, embora o referido
 a pessoa pode ser agora muito antiga?}
{134}{}{Qual personagem não-jogador da Fallout 1 sobreviveu para aparecer na sequela?}
{135}{}{Já é velho?}
{136}{}{C-qwell?}
{137}{}{(Shamble off)}
{138}{}{Wha --?! Eu não sei disso!}
{139}{}{Uh ... Ian?}
{140}{}{Uh ... Carne de cachorro?}
{141}{}{Uh ... Tandi?}
{142}{}{Uh ... Tycho?}
{143}{}{Uh ... Harold?}
{144}{}{O que você quer dizer? Você conta com encontros especiais como realmente parte da sequela ou eles são?
 tratados como eventos especiais?}
{145}{}{O que você quer dizer? NPC aliados ou NPC inimigos?}
{146}{}{Quanto peso pode uma pessoa com uma força de seis carregar assumindo que ele tem o Strong Back
 perk?}
{147}{}{Eu realmente não sei.}
{148}{}{Uh ... duzentos libras?}
{149}{}{Uh ... duzentos e vinte e cinco quilos?}
{150}{}{Uh ... duzentos e cinquenta libras?}
{151}{}{Uh ... duzentos e setenta e cinco quilos?}
{152}{}{Uh ... trezentos quilos?}
{153}{}{Uh ... trezentos e vinte e cinco quilos?}
{154}{}{Quantos níveis do percurso Strong Back a pessoa tem?}
{155}{}{Qual é o requisito mínimo para o Quick Pockets perk?}
{156}{}{Eu realmente não sei.}
{157}{}{Uh ... força de cinco?}
{158}{}{Uh ... agilidade de cinco?}
{159}{}{Uh ... agilidade de seis?}
{160}{}{Uh ... nível três?}
{161}{}{Uh ... nível seis?}
{162}{}{Uh ... nível nove?}
{163}{}{O que você quer dizer? A estatística ou requisito de nível?}
{164}{}{Certo. Você vai embora.}
{165}{}{Fank você}
{166}{}{Goodie}
{167}{}{Oh, obrigado. Muito obrigado.}
{168}{}{Eu não sei disso!}
{169}{}{O jogador está desintegrado.}
{170}{}{Heh heh.}
{171}{}{Por algum motivo, acho que devo salvar meu jogo em um novo slot.}

{172}{}{nome do ano?}

{173}{}{Eu nunca consigo fazer as boas perguntas.}
{174}{}{Eu vou falar com o meu agente sobre tudo isso.}
{175}{}{Eu continuo dizendo a ele que eu tenho que parar de fazer esses shows de queijo.}
{176}{}{Como eu sempre vou ter respeito que eu mereço estar em filmes de baixo orçamento e videogames.}
{177}{}{Hmmm .. Eu realmente deveria pensar em entrar no reparo do carro.}
{178}{}{Eu ouço que é onde todo o dinheiro é feito nos dias de hoje.}

{200}{}{AAAAAAHHHHHHHHhhhhhh!}
