{100}{}{Você vê um jumper de reivindicação.}
{101}{}{Nós estávamos aqui primeiro.}
{102}{}{Vá encontrar sua própria reivindicação para saltar.}
{103}{}{Apenas outro entalhe na minha pistola.}
{104}{}{Não posso deixar você ir agora.}
{105}{}{Você já viu demais.}
