{100}{}{Você vê um cachorro meeeean.}
{101}{}{Você vê Dogmeat.}
{102}{}{Você vê Dogmeat.}
{103}{}{O cão dá uma baixa gargalhada quando vê o fato do vault. Parece que quer vir com você.}
{104}{}{Apito}
{105}{}{Talvez você venha comigo quando eu tiver mais ruum.}
{106}{}{Uh-uh, cachorrinho. Yu ficar.}
{107}{}{Vamos, garoto. Tempo para fazer algum dano.}
{108}{}{Não se preocupe, garoto. Eu vou voltar e pegar você quando eu tiver algum espaço na minha festa.}
{109}{}{Desculpe, Dogmeat. Não dessa vez.}
{110}{}{O cão engoliu a iguana em uma vara e depois olha para você com expectativa.}
{111}{}{Apito}
{112}{}{Talvez você venha comigo quando eu tiver mais ruum.}
{113}{}{Uh-uh, cachorrinho. Yu ficar.}
{114}{}{Vamos, garoto. Tempo para fazer algum dano.}
{115}{}{Não se preocupe, garoto. Eu vou voltar e pegar você quando eu tiver algum espaço na minha festa.}
{116}{}{Desculpe, Dogmeat. Não dessa vez.}
{117}{}{Você vê um cachorro de meeeean.}
{118}{}{Apito}
{119}{}{Talvez você venha comigo quando eu tiver mais ruum.}
{120}{}{Espere cachorrinho, sem movimento.}
{121}{}{Shamble off}
{122}{}{Vamos, garoto. Tempo para fazer algum dano.}
{123}{}{Eu vou voltar e pegar você quando eu tiver algum espaço na minha festa.}
{124}{}{Fique perto de mim. Tudo bem, garoto?}
{125}{}{Mantenha uma distância média, carne de cachorro.}
{126}{}{Fique longe de mim, Dogmeat. Observe minhas costas.}
{127}{}{Fique, Dogmeat. Fique!}
{128}{}{Eu acho que vou deixar Dogmeat sozinho.}
{129}{}{A carne de cachorro dá uma casca afiada, depois um rosnado baixo.}
{130}{}{Fique perto de mim. Tudo bem, garoto?}
{131}{}{Mantenha uma distância média, carne de cachorro.}
{132}{}{Fique longe de mim, Dogmeat. Observe minhas costas.}
{133}{}{Fique, Dogmeat. Fique!}
{134}{}{Obrigado, Dogmeat. Você joga o traseiro.}
{135}{}{Awooooooooooo}
{136}{}{Awooooooooooo}
{137}{}{Ey'e mate, veste comigo cachorro.}
{138}{}{Grrrrr ....}
{139}{}{(Eu me pergunto se eu posso obter Dogmeat para me seguir de forma diferente?)}
