{100}{}{Você vê um homem magro e bronzeado.}
{200}{}{Você vê uma mulher magra e bronzeada.}
# male
{101}{}{Você vê um fazendeiro.}
# female
{201}{}{Você vê um fazendeiro.}
{102}{}{Você percebe que ele tem um bronzeado de fazendeiro.}
{202}{}{Você percebe que ela tem um bronzeado de fazendeiro.}
{103}{}{Você chegou apenas no tempo. Se você não tivesse chegado aqui quando você fez ... Bem, vamos apenas
 Seja grato por você ter vindo quando você fez. Nós não temos muito, mas eu gostaria que você aceitasse isso como um
 Recompensa por nos ajudar. [Ele te dá algo.]}
{104}{}{Obrigado.}
{105}{}{Ug}
{106}{}{Obrigado novamente por nos ajudar.}
{107}{}{}
{108}{}{}
{109}{}{Você mantém suas mãos onde posso vê-las. Já fomos atormentados por bandidos recentemente e acho que
 Você pode ser apenas um deles. O que você quer?}
{110}{}{Eu só queria trocar por suprimentos.}
{111}{}{Estou apenas passando. Estarei à caminho.}
{112}{}{Ug.}
{113}{}{Bem, acho que não há dano nisso. Aqui eu tenho que trocar.}
{114}{}{[Trocar]}
{115}{}{Ok, agora git!}
{116}{}{[Trocar]}
{117}{}{Eu disse git!}
{118}{}{}
{119}{}{[Ele relaxa um pouco.] Você é muito estúpido para ser um bandido. Você precisa de suprimentos?}
{120}{}{Uh hein.}
{121}{}{Eh eh.}
{122}{}{Bem, não temos negócios. Você continua se movendo, então.}
{123}{}{[FIM]}
{124}{}{Deixe minha fazenda!}
{125}{}{Ninguém vai tirar minha casa de mim.}
{126}{}{Bandidos sujos.}
{127}{}{Saia da minha terra.}
{128}{}{Não posso confiar em ninguém hoje em dia.}
{129}{}{Malditos bandidos.}
{130}{}{Eu trabalhei muito para desistir agora.}
{131}{}{Talvez eu vá cultivar em outro lugar.}
{132}{}{Eu sou apenas um agricultor pobre.}
{133}{}{Por favor, não queime minha fazenda.}
{134}{}{Eu não gostava de cultivar de qualquer maneira.}
{135}{}{Eu voltarei.}
{136}{}{Pegue minha esposa - por favor ...}
