{100}{}{Pescador.}
{101}{}{Você chegou a tempo de testemunhar as bênçãos da Deusa do Mar.}
{102}{}{[Mais]}
{103}{}{}
{104}{}{Pouco antes de uma grande tempestade, lançamos lanças no mar para mostrar nossa bravura contra os elementos.
 Se nos provamos ser dignos, a Deusa nos recompensa com frutos.}
{105}{}{Quando a estação das tempestades começa, lançamos flores Broc no mar com a maré. Depois de
 A Deusa trabalha sua magia, ela retorna as flores Broc como a rara raiz Xander.}
{106}{}{Oferecemos tributo à Deusa do Mar a cada ano sob a forma de raiz Xander. Se o
 A deusa nos considera digna, ela transformará a raiz Xander em flores Broc.}
{107}{}{Depois de uma colheita abundante, damos tributo à Deusa do Mar que ela pode vigiar
 e nos proteja. Todos os anos, ela recompensou nossa piedade ao enviar lanças na maré como sinal de que ela
 está cuidando de nós.}
{108}{}{Posso ver o que a Deusa lhe concedeu?}
{109}{}{Ug}
{110}{}{Aqui está o que a grande Deusa nos deu este ano. Com prazer, compartilharemos suas bênçãos com
 você, por um preço.}
{111}{}{Junk [10]}
{112}{}{Pistola a laser [$ 10000]}
{113}{}{Palitos afiados [40]}
{114}{}{Frutos [5]}
{115}{}{Xander [20]}
{116}{}{Broc [10]}
{117}{}{Tchau.}
{118}{}{[Ele o aponta na direção do mar.] Apenas continue andando. A Deusa deseja conhecer você
 pessoalmente.}
{119}{}{[Fim]}
{120}{}{Que a bênção da Deusa do Mar vá com você.}
{121}{}{[Fim]}
{122}{}{[Ele franziu o cenho quando você não conseguiu produzir a soma de dinheiro necessária.] Talvez outra vez, então.}
{123}{}{[Fim]}
