{100}{}{Um homem em armadura de poder.}
{101}{}{Sir Galahad.}
{102}{}{Ele se ruboriza quando percebe que está olhando para ele.}
{103}{}{Sir Galahad, pronto!}
{104}{}{Uma vez fui um prisioneiro de Castle Anthrax.}
{105}{}{Sir Launcelot me salvou. Maldito seja ele!}
{106}{}{Eu poderia ter sido prisioneiro. [Farejar]}

{200}{}{Aqui agora! Suas mãos estão geladas!}
{201}{}{Isso não pertence a você.}
{202}{}{Ei, essas são minhas coisas!}
