{100}{}{Você vê um eremita.}
{101}{}{Você vê um eremita.}
{102}{}{Parece que ele não lavou anos.}
{103}{}{Pode imaginar você por que eu eremita? [Parece que ele não falou com ninguém em anos.]}
{104}{}{Por quê?}
{105}{}{Apenas passando.}
{106}{}{Ug.}
{107}{}{Eu quero ficar sozinho.}
{108}{}{Desde que eu estou aqui, talvez possamos trocar. Tenho certeza de que tenho algo que você deseja.}
{109}{}{Vou deixá-lo em paz, então.}
{110}{}{Comércio. Então deixe você vontade.}
{111}{}{OK, aqui está o que eu tenho que negociar.}
{112}{}{Eu vou embora.}
{113}{}{Saia agora.}
{114}{}{Eu irei agora.}
{115}{}{Hmm ... Eu gosto de você. Nenhuma orelha fala. Fique me troque e você.}
{116}{}{K '}
{117}{}{Eu vou.}
{118}{}{Boa conversa. Vá agora. Cansado eu.}
{119}{}{[FIM]}
{120}{}{Fale com dor na cabeça. Ir.}
{121}{}{Fez-me falar com você.}
{122}{}{Não conversa. Ir.}
{123}{}{Vá embora!}
{124}{}{Saia de casa!}
{125}{}{Como você se atreve a atacar!}
{126}{}{Deixe-me sozinho.}
{127}{}{Eu vou.}
