{100}{}{Um homem raspando um alaúde.}
{101}{}{Joshua.}
{102}{}{Um minstrel viajando.}

{103}{}{Brave Sir Robin fugiu ...}
{104}{}{Bravamente fugiu, longe ...}
{105}{}{Quando o perigo criou sua cabeça feia, ele bravamente virou a cauda e fugiu ...}
{106}{}{Sim, o bravo Sir Robin se voltou ...}
{107}{}{E, galantemente, ele se irritou. Bravamente, levando-se de pé ...}
{108}{}{Ele bateu um retiro muito corajoso ...}
{109}{}{Oh, bravo senhor Robin.}
