{100}{}{Você vê um homem vestindo uma armadura de metal.}
{101}{}{Você vê Kaga.}
{102}{}{Sim, é Kaga o que não é tão bom. Ele tem armadura de metal e quer matá-lo.}
{103}{}{Você novamente!}
{104}{}{Fico cansado de nossas reuniões constantes.}
{105}{}{Escolhido - hmph!}
{106}{}{Vamos acabar com isso.}
{107}{}{Você vai se arrepender de ter ouvido o nome de Kaga!}
{108}{}{Minhas habilidades aumentaram desde a última vez que nos encontramos.}
{109}{}{Isso está a ser um mau hábito.}
{110}{}{Kaga precisa treinar um pouco mais.}
{111}{}{Kaga retornará.}
