{100}{}{Você vê um homem que usa armadura de poder MKII. Ele não parece amigável.}
{101}{}{Você vê Kaga na armadura de poder MKII.}
{102}{}{Um grande pedaço de metal com armas e armas.}
{103}{}{Eu me canso da perseguição. Vamos terminar isso.}
{104}{}{Esta é a última vez que você encontrará Kaga.}
{105}{}{Você não é igual para Kaga.}
{106}{}{Estou ansioso para enviá-lo para sua próxima vida.}
{107}{}{Você tem sido um inimigo digno.}
{108}{}{Esta parte dos resíduos não precisa de um bom desempenho como você.}
{109}{}{Depois de te matar, eu serei a pessoa mais temida nesta parte dos resíduos.}
{110}{}{Estou ansioso para ir para casa para Arroyo - para queimá-lo.}
{111}{}{Kaga será famosa por matar você.}
