{100}{}{Você vê um homem vestindo roupas mínimas.}
{101}{}{Você vê Kaga.}
{103}{}{Ele está usando calças e parece que ele veio de uma tribo.}
{104}{}{Eu deveria ter sido o Escolhido!}
{105}{}{Como se atreve, Arroyo me expulsou da tribo.}
{106}{}{Eu vou me vingar de você!}
{107}{}{Kaga enviará você para a próxima vida.}
{108}{}{Nós nos encontraremos novamente!}
{109}{}{Nunca fui espancado antes!}
{110}{}{Vou me dedicar à sua destruição.}
