{100}{}{Você vê um homem com uma armadura de couro.}
{101}{}{Você vê Kaga.}
{102}{}{Ele está usando armaduras de couro e tem um hábito irritante de falar sobre si mesmo na terceira pessoa.}
{103}{}{Esta será a última vez que Kaga te encontrar.}
{104}{}{Depois de matar Kaga, ele arderá Arroyo ao chão.}
{105}{}{Sinta a ira de Kaga!}
{106}{}{Eu sou o grande Kaga!}
{107}{}{Kaga deve ser temido por todos.}
{108}{}{Kaga terá sua cabeça para um troféu.}
{109}{}{Entregue e sua morte será rápida.}
{110}{}{Kaga estará de volta!}
{111}{}{Você não pode matar o grande Kaga!}
{112}{}{Você tem sorte Kaga tem negócios em outro lugar.}
{113}{}{Kaga irá encontrá-lo novamente.}
