{100}{}{Você vê um pouco rugrat.}
{101}{}{Você vê Melchior, Jr.}

{150}{}{Ele parece um cara sorridente e de olhos grandes.}

{200}{}{Olá! Eu sou Melchior, Jr.}
{201}{}{Meu pai é um mineiro. O nome dele é Melchior como o meu.}
{202}{}{Meu pai é um bom mineiro, mas ele quer ser um mágico.}
{203}{}{O nome artístico do papai é Melchior the Magnificent.}
{204}{}{Seu melhor truque foi tirar um rato de um chapéu.}
{205}{}{Ele saiu com alguns homens vestidos com roupas de metal.}
{206}{}{Espero que o pai volte logo. Sinto falta de seus truques mágicos.}
{207}{}{Eu vou ser um grande mago como meu pai.}
