{100}{}{Um nômade.}
{101}{}{Chefe do nómada.}
{102}{}{Por seu vestido e pela maneira como ele se carrega, ele deve ser um líder de algum tipo.}
{103}{}{Ah, um viajante. Seja bem-vindo à minha tenda humilde. Tire a sombra do calor interminável da terra.}
{104}{}{Obrigado; Aceito graciosamente a sua oferta de sombra.}
{105}{}{Devo recusar sua oferta. Estou apenas de passagem.}
{106}{}{Ooga.}
{107}{}{Seja bem vindo, então. Nós ficamos longe das terras "civilizadas". Precisamos de
 certos itens. Talvez possamos negociar?}
{108}{}{O que você tem para negociar?}
{109}{}{Não tenho nada para negociar. Desculpa.}
{110}{}{Talvez outra vez, então? Que suas viagens estejam livres de perigo.}
{111}{}{Tchau.}
{112}{}{Que pena. Então descanse e seja bem vindo no meu acampamento.}
{113}{}{Tchau.}
{114}{}{Minha oferta de sombra chegou muito tarde para você. O sol deve ter fervido palavras de seu
 cérebro. Eu devo ser gentil com aqueles menos afortunados do que eu. Fique o tempo que você quiser no meu acampamento, maldito.}
{115}{}{Tchau.}
{116}{}{Infiel!}
{117}{}{Por que você nos ataca?}
{118}{}{Defenderei a tribo com a minha vida!}
{119}{}{Como você ousa violar nossa hospitalidade.}
{120}{}{Sai!}
{121}{}{Nos deixe.}
{122}{}{Somos uma tribo pacífica.}
