{100}{}{Um nômade.}
{101}{}{Olá, você parece novo por aqui.}
{102}{}{Você deveria conversar com o chefe.}
{103}{}{Eu não acho que é tão quente hoje como foi ontem.}
{104}{}{Então, como é a vida na cidade?}
{105}{}{Infiel!}
{106}{}{Por que você nos ataca?}
{107}{}{Defenderei a tribo com a minha vida!}
{108}{}{Como você ousa violar nossa hospitalidade!}
{109}{}{Sai!}
{110}{}{Nos deixe.}
{111}{}{Somos uma tribo pacífica.}
