{100}{}{Um nômade.}
{101}{}{Noman shaman.}
{102}{}{O forte cheiro de ervas se agarra à roupa da pessoa.}
{103}{}{Olá estranho. Eu sou o chaman da tribo. Sou especialista na arte da cura.}
{104}{}{Olá de novo.}
{105}{}{Preciso de cura.}
{106}{}{Você pode combinar a raiz xander e a flor broc?}
{107}{}{Tchau.}
{108}{}{Ooga.}
{109}{}{Fique quieto e eu vou examiná-lo.}
{110}{}{[Continuar]}
{111}{}{Encontrei essas aflições.} #continue at 136
{112}{}{Pode me ajudar?}
{113}{}{Posso realizar o seguinte por um preço:} # continue at 140
{114}{}{Por favor, extraia o veneno do meu corpo.}
{115}{}{Por favor, cure-me.}
{116}{}{Veja o que você pode fazer para o meu membro quebrado.}
{117}{}{Tchau.}
{118}{}{Você foi curado.}
{119}{}{Você foi curado.}
{120}{}{Você foi curado.}
{121}{}{Preciso de mais de suas habilidades.}
{122}{}{Thank you; I feel much better. Tchau.}
{123}{}{Minhas habilidades são limitadas e não posso ajudá-lo mais nessa área.}
{124}{}{[Continuar]}
{125}{}{Você não requer esse tipo de cura.}
{126}{}{[Continuar]}
{127}{}{Ahh ... Você está familiarizado com as propriedades curativas dessas duas plantas. Isso só custará
 você} # continue at 150
{128}{}{Combine as duas plantas para mim.}
{129}{}{Talvez mais tarde, tchau.}
{130}{}{[Você vê como ele esmaga cuidadosamente e combina as duas plantas e, em seguida, entrega você precisamente
 doses medidas do pó.]}
{131}{}{Tchau.}
{132}{}{Você parece ser curto em dinheiro. Retorne mais tarde quando sua bolsa estiver mais gorda.}
{133}{}{[FIM]}
{134}{}{Não tenho tempo para tantas bobagens. Sair!}
{135}{}{[FIM]}
{136}{}{[Envenenado]}
{137}{}{[Ferido]}
{138}{}{[Radiado]}
{139}{}{[Aleijado]}
{140}{}{Cure venenoso}
{141}{}{Corrija os membros incapacitados,}
{142}{}{Cura $}
{143}{}{Infiel!}
{144}{}{Por que você nos ataca?}
{145}{}{Defenderei a tribo com a minha vida!}
{146}{}{Como você ousa violar nossa hospitalidade.}
{147}{}{Sai!}
{148}{}{Nos deixe.}
{149}{}{Somos uma tribo pacífica.}
{150}{}{e eu vou combinar os dois para você.}
