{100}{}{Prospector}
{101}{}{Segure-o ali mesmo, estranho! Não estou acostumado a emboscar estranhos, mas eu preciso de suprimentos e eu
 não posso deixar minha reivindicação. Quer fazer um comércio rápido?}
{102}{}{Certo.}
{103}{}{Não tenho nada para negociar. Desculpa.}
{104}{}{Booga.}
{105}{}{Que sorte de sorte. Você não pode falar, você pode? Não posso falar, não posso dizer a ninguém onde minha reivindicação
 é. Vamos trocar.}
{106}{}{[Trocar]}
{107}{}{OK, vença! E é melhor não contar a ninguém onde é minha reivindicação.}
{108}{}{[Fim]}
{109}{}{Eu acho melhor você seguir em movimento.}
{110}{}{Não temos mais nada para falar.}
{111}{}{No seu caminho!}
{112}{}{Vá buscá-los.}
{113}{}{Não é possível que você diga a ninguém onde é meu pedido.}
{114}{}{Por que você me atacou?}
{115}{}{Agora eu tenho que matá-lo.}
{116}{}{Eu só queria alguns suprimentos.}
{117}{}{Você pode ter meu pedido!}
{118}{}{Misericórdia!}
