{100}{}{Essa pessoa parece estar balançando ligeiramente.}
{101}{}{Você vê o barman do partido.}
{102}{}{Parece que ele está avaliando algumas de suas mercadorias.}
{202}{}{Parece que ela está avaliando algumas de suas próprias mercadorias.}
{103}{}{Wha ... whas ... o que eu consigo. [Caipira.]}
{104}{}{Nuka Cola [$ 6]}
{105}{}{Cerveja [$ 15]}
{106}{}{Booze [$ 30]}
{107}{}{Nada hoje. Obrigado.}
{108}{}{Ug.}
{109}{}{Ohhhh ... isso não é nada divertido. [Ele lhe entrega sua bebida.]}
{110}{}{[Fim]}
{111}{}{Aqui você vai. É um pouco quente porque não teve tempo de esfriar. Venda as coisas mais rapidamente do que eu
 Pode fazê-lo. [Está quente, é amarelo, é ...]}
{112}{}{[Fim]}
{113}{}{[Você sente que as paredes do seu estômago se dissolvem à medida que você toma um grande gole.]}
{114}{}{[Fim]}
{115}{}{Whoa ... [hick] Eu acho que você não tomou nuf ta já.}
{116}{}{[Fim]}
{117}{}{Ahhh homem! Você não tem enuf dinheiro! Cum quando você recebe soma.}
{118}{}{[Fim]}
{119}{}{Ele tem um olhar selvagem para ele.}
{120}{}{Você vê um dependente.}
{121}{}{Ele parece um pouco nervoso.}
{122}{}{Qual é o significado? Igotitall!}
{123}{}{Mentats [$ 560]}
{124}{}{Buffout [$ 400]}
{125}{}{Psycho [$ 800]}
{126}{}{Nada hoje. Obrigado.}
{127}{}{Ug.}
{128}{}{Isso é ótimo! Givemethemoney e chegar a outro lado. Igotabusinesstorun.}
{129}{}{[Fim]}
{130}{}{Likethesayinggoes. Nomoneynohoney. Oh. Thatsforsex. Howaboutnodoughnoow.
 Comeback, quando você gotsomecash.}
{131}{}{[Fim]}
{132}{}{Heheheh! Parece que você pode fazer parabéns. Giveme $ 1000.}
{133}{}{[Dê ao homem $ 1000]}
{134}{}{Eu vou.}
{135}{}{OH SIM! Isso irá ajudá-lo!}
{136}{}{[FIM]}

#Drunk: sets the sex flag
{150}{}{Ei, você é meio fofo. qual o seu nome?}
{151}{}{All mais alto. Oh, sim.}
{152}{}{Você está pronto ... fique com isso?}
{153}{}{Naw..naw ..naw ..naw nuh naw.}
{154}{}{Assista assim. Sim.}
#Drunk: the sex flag is set and you got some
{155}{}{Agora não vá embora.}
{156}{}{Seja bebido por aqui.}
{157}{}{Vá ficar com jiggy ... em algum outro lugar.}
#prop Drunk
{158}{}{Que tal você e eu nos afastarmos da multidão?}
{159}{}{Uhh, vamos fazê-lo!}
{160}{}{Naa, estou bêbado.}
{161}{}{[Burb] :: smile ::}

#Addict: set the sex flag
{170}{}{Ei, você quer ir atrás desse mato?}
{171}{}{Você já esteve alto e feito?}
{172}{}{Eu poderia te mostrar as estrelas, querida.}
{173}{}{Você sabe que eu quero um pouco de amor.}
{174}{}{Eu estava esperando para encontrar alguém que estava pronto para ir.}
#Addict: the set flag is set and you got some
{175}{}{Isso foi o suficiente para mim.}
{176}{}{Ei, você tem um cigarro?}
{177}{}{Ei, agora não se apegue demais - Eu gosto da minha liberdade.}
#prop Addict
{178}{}{Você é tão elegante como uma pantera e eu quero você.}
{179}{}{Esta pronto?}
{180}{}{Agora não; Tenho que disparar.}
{181}{}{Man as escotilhas. Nós estamos entrando.}

{200}{}{Não seja um idiota!}
{201}{}{Ir para outro lugar.}
{202}{}{Quem te deixou entrar?}

{203}{}{Isso não é legal!}
{204}{}{Cara frio.}
{205}{}{Relaxe homem!}
