{100}{}{Orgulho alegre!}
{101}{}{Com heteros!}
{102}{}{Outsiders não são bem-vindos!}
{103}{}{Orgulhoso de ser um dique!}
{104}{}{Poder feminino!}
{105}{}{Não precisa de um homem!}
{106}{}{A Confederação do Arco-íris irá viver.}
{107}{}{Retire-se da Barraca de Amor.}
{108}{}{Nós devemos superar!}
{109}{}{Bem-vindo à Confederação do Arco-íris.}
{110}{}{Seu tipo é bem-vindo aqui.}
{111}{}{Você é um de nós.}
{112}{}{Colonizadores.}
{113}{}{Colono.}
{114}{}{Queer.}
{115}{}{Pansy.}
{116}{}{Rainha.}
{117}{}{Lesbo.}
{118}{}{Sapatona.}
{119}{}{Isso parece ser um}
