{100}{}{Você vê ... um modelo de heroína de cabelos ruivos.}
{101}{}{Você vê uma mulher de cabelos ruivos atraente e atraente em um macacão Vault 13. Ela está furiosa com raiva
 na distância.}
{102}{}{Você vê um modelo de heroína rouca. Ela está olhando para a distância.}
{103}{}{Você vê um modelo de heroína rouca. Ela está olhando para a distância.}
{104}{}{Não posso acreditar que não fiz o corte final no Fallout 1.}
{105}{}{Eles escolheram esse * strumpet de cabelo preto * em vez disso. De todo o nervo!}
{106}{}{A * modelo feminino de cabelo preto *. Você pode obter mais genéricos? Chato.}
{107}{}{Os Redheads são infinitamente mais interessantes.}
{108}{}{Esse modelo feminino de cabelos negros entrou apenas porque dormiu com * cada * artista na equipe.}
{109}{}{E os programadores.}
{110}{}{E o líder do projeto. Eles são tão facilmente balançados. Mostre um pouco de pele, e suas espinhas se voltam para
 borracha.}
{111}{}{Então, eu veio e acabo sendo "NPCs de preenchimento" no Vault 13. Keee-Rist. Fale sobre falsificação.}
{112}{}{Estou surpreso que eles renderam aquele modelo feminino de cabelos negros com qualquer roupa.}
{113}{}{Quero dizer, não é como se estivesse neles muito durante o processo de triagem.}
{114}{}{*Suspiro*}
{115}{}{Eu odeio homens.}
{116}{}{Bem, exceto por esse sonhador Scotty Everts.}
{117}{}{Eu acho que ele pegou para mim. Eu só tive que dormir com ele poucas vezes para ele votar por mim.}
