{100}{}{Um homem em armadura de poder.}
{101}{}{Sir Robin.}
{102}{}{Parece que ele está pronto para correr.}
{103}{}{Sir Robin, ao seu serviço.}
{104}{}{Você não vai tentar me machucar, você está?}
{105}{}{Não há necessidade de violência, está?}
{106}{}{Por favor vá embora.}

{200}{}{Aqui agora! Suas mãos estão geladas!}
{201}{}{Isso não pertence a você.}
{202}{}{Ei, essas são minhas coisas!}
