{100}{}{Você vê ... Set.}
{101}{}{Você vê um ghoul decadente com as peças da máquina saindo da cabeça dele. É difícil dizer se
 Ele é senil ou não.}
{102}{}{Você vê Set. Ele está falando consigo mesmo.}
{103}{}{Você vê Set. Ele está falando consigo mesmo.}
{104}{}{"Dirtnap!"}
{105}{}{"Dirtnap!"}
{106}{}{"Dirtnap ... Faz minha sombra crescer".}
{107}{}{Heh heh.}
{108}{}{Sujeira.}
{109}{}{Sesta.}
{110}{}{Dirtnap!}
{111}{}{Heh heh. I ruuule Necropolis.}
{112}{}{Normies. Em todo lugar, normies.}
{113}{}{Conjunto de nomes. O seu é World-a-hurt.}
{114}{}{Chuckle-Ruckle.}
{115}{}{Sesta. Sujeira. Napdirt!}
