{100}{}{Estes irão buscar um bom preço no mercado.}
{101}{}{Tente não danificar a mercadoria.}
{102}{}{Você fará um escravo espirituoso.}
{103}{}{Isto não é bom.}
{104}{}{Retiro!}
{105}{}{Talvez eu vou vender móveis em vez disso.}
{106}{}{Os companheiros de escravos não devem atacar uns aos outros.}
{107}{}{A guild ouvirá sobre isso!}
{108}{}{O que você está fazendo?}
{109}{}{Alguma sorte?}
{110}{}{Encontrar algum bom escravo?}
{111}{}{Estamos à procura de novas ações.}
{112}{}{Este é o nosso território.}
