{100}{}{Você vê um spammer com aspecto patético.}
{110}{}{Você não vê absolutamente nada de interesse.}

# Grim's Floats
{120}{}{Haverá uma versão para Mac?}
{121}{}{Eu quero multiplayer!}
{122}{}{Eu odeio todos vocês!}
{123}{}{Ahhh!}
{124}{}{Você não pode me machucar!}
{125}{}{Eu sou o Grim Reaper, você não pode me matar. Não sou engraçado.}
{126}{}{Eu quero um tanque!}
{127}{}{Onde está a minha motosserra?}
{128}{}{Não me machuque.}
{129}{}{Não queria ser um idiota.}
{130}{}{Não quis dizer aquelas ameaças de morte.}
{131}{}{Sinto muito, Buffy!}
{132}{}{Desculpe, não lavado! Eu só queria ser notado.}
{133}{}{Eu quero uma versão on-line!}
