{100}{}{Você vê ... Tandi.}
{101}{}{Você vê uma garota linda, de cabelos curtos, com uma expressão maravilhosa. Ela está olhando sonhadoramente para a
 distância.}
{102}{}{Você vê Tandi. Ela está olhando sonhadoramente à distância.}
{103}{}{Você vê Tandi. Ela está olhando sonhadoramente à distância.}
{104}{}{Oi! Então você é um descendente do herói Fallout 1? Uau! Eu sou Tandi! Oi!}
{105}{}{Eu não queria apenas explodir, mas seu avô com certeza era fofo! *Suspiro*}
{106}{}{Ian? Eu acho que ele ainda está em Fallout 2 em algum lugar. A Abadia, talvez?}
{107}{}{Na verdade, eu ouço * Estou * em Fallout 2 em algum lugar. Eu não quero ir me encontrar, no entanto ... pode arrasar
 Nós dois.}
{108}{}{Desculpe, eu não tinha melhores habilidades de combate em Fallout 1. Eu acho que não saí muito.}
{109}{}{Diga ... você e Tycho continuam em contato?}
{110}{}{Então, houve esse erro quando você me salvou dos incursores e me trouxe de volta para papai, ele iria
 balístico. Gosh, que sugado!}
{111}{}{Eu me juntaria a você, mas estou esperando meu pai, Aradesh, para aparecer. Ele deveria se juntar a mim alguns
 Revisões atrás.}
