{100}{}{Você vê um homem em algum tipo de armadura.}
{101}{}{Você vê um homem em algum tipo de armadura.}
{102}{}{Sua armadura parece estar bastante enferrujada.}
{103}{}{Lata de óleo.}
{104}{}{Muito obrigado. Você não tem idéia de quanto tempo eu fiquei preso aqui. Bem, pegue isso por seu problema. Eu tenho que ir.}
{105}{}{Uhh, obrigado.}
{106}{}{Desculpe, tenho que ir. Vejo você mais uma vez.}
