{100}{}{Quer ouvir uma nova receita?}
{101}{}{Que tipo?}
{102}{}{Rato surpresa.}
{103}{}{Parece bom. Como eu faço?}
{104}{}{Pegue o rato. Cuidado sem esmagar demais.}
{105}{}{Como não squish? Toda vez que eu os encaixota, eles pisam. Muito bagunçado.}
{106}{}{Você quer ouvir uma receita ou não? Pegue o seu problema na ratazana.}
{107}{}{Me desculpe.}
{108}{}{Como disse, pegue um rato. Pendure por cauda na parede.}
{109}{}{Deixe cair até a cauda cair. Está pronto então.}
{110}{}{Coma rapidamente, se deixa ficar muito tempo, a surpresa se arrastar e voar para longe.}
{111}{}{Muito gostoso.}
