{100}{}{Você vê um homem sujo e sem barulho.}
{200}{}{Você vê uma mulher suja e abatida.}
{101}{}{Caçador.}
{102}{}{Melhor não chegar muito perto. Algumas das criaturas em sua roupa podem estar procurando um limpador
 casa.}
{103}{}{Howdy. Não encontre pessoas muitas vezes aqui no país do caçador. O que quer?}
{104}{}{Você tem alguma pele de gecko para venda?}
{105}{}{Apenas passando.}
{106}{}{Ug.}
{107}{}{Bem, eu acho que posso vender minhas roupas. Isso me salvará o problema de entrar
 Cidade.}
{108}{}{O que você tem?}
{109}{}{Deixa pra lá.}
{110}{}{Ug.}
{111}{}{Aqui está o que eu tenho:}
{112}{}{Pele comum de gecko.}
{113}{}{peles douradas de gecko.}
{114}{}{Vou pegar tudo o que tens.}
{115}{}{Talvez na próxima vez. Tchau.}
{116}{}{É bom fazer negócios com você. Até a próxima.}
{117}{}{Tchau.}
{118}{}{Parece que você está com menos dinheiro. E você me dá cinco minutos com sua mulher. Eu vou fazer isso
 Vale o seu tempo.}
{119}{}{Parece que você está com menos dinheiro. Como me dar 5 minutos com o seu homem. Você sabe o que eu quero dizer. Posso dar-lhe peles no comércio.}
{120}{}{Parece que você está com menos dinheiro. Diga-lhe o que, eu tenho estado nessas madeiras por muito tempo, se você
 pegue minha deriva. Eu farei valer a pena.}
{121}{}{Certo.}
{122}{}{Not a chance. Tchau.}
{123}{}{[Miria vai te perdoar ... eventualmente. Mas, do lado positivo, o caçador deu-lhe alguns
 peles.]}
{124}{}{[Davin parece não ser pior para o desgaste após a experiência.]}
{125}{}{[Você se sente sujo em mais de um sentido da palavra - mas você tem algumas peles gecko.]}
{126}{}{Tchau.}
{127}{}{[Ele ergue a mão direita e diz] Como. Meu poderoso caçador. Caçar grandes geckos. Eu não significa
 atravesse sua terra. Deixe pacificamente. [Ele lhe entrega uma pele de gecko como presente.]}
{128}{}{[FIM]}
{129}{}{Não tenho mais negócios com você.}
{130}{}{Sapsucker de ventre amarelo!}
{131}{}{Este é o meu território de caça. Sair!}
{132}{}{Eu vou te proteger vivo!}
{133}{}{Eu vou usar sua cabeça como um troféu.}

{134}{}{Uma pelagem regular de gecko: $}
{135}{}{Uma pele dourada de gecko: $}

{136}{}{OK, diretor. Você ganha.}
{137}{}{Sorte por você, tenho que ir verificar minhas armadilhas.}
{138}{}{Eu acho que ouço mamãe me chamar.}
