{100}{}{Um viajante.}
{101}{}{Saudar! Companheiro de viagem.}
{102}{}{Preciso de instruções. Você pode me ajudar?}
{103}{}{Onde você está indo?}
{104}{}{O que você faz?}
{105}{}{Ug.}
{106}{}{Bem ... eu não sei. Eu sou muito novo nesta área e só fui nas seguintes áreas.}
{107}{}{Novo Reno}
{108}{}{Vault City}
{109}{}{Redding}
{110}{}{The Den}
{111}{}{São Francisco}
{112}{}{Nova República da Califórnia}
{113}{}{Uma mina abandonada.}
{114}{}{Não, já estive lá. Obrigado mesmo assim.}
{115}{}{Novo Reno -- now that's a great place to go. Sex, chems and gambling.  What more can one ask for?
 Here, let me show you where it is.}
{116}{}{Obrigado.}
{117}{}{Vault City - agora é uma cidade de idiotas. Cresça um dedo extra e eles tratam você como algum tipo
 de aberração. Nunca estive dentro, mas sei onde está.}
{118}{}{Obrigado.}
{119}{}{Redding ... Eu não sei muito sobre isso, além de ser uma antiga cidade mineira. Está localizado no norte,
 Certo golpe no meio de algumas das mais malvadas montanhas que você já viu.}
{120}{}{Obrigado.}
{121}{}{Eu ficaria longe do Den se eu fosse você. É um ímã para pessoas baixas da área. eu vou te mostrar
 onde é, mas eu não recomendo que você vá lá.}
{122}{}{Obrigado.}
{123}{}{São Francisco. Um...all I can say is that the people there are...strange. It's located on the
 coast.}
{124}{}{Obrigado.}
{125}{}{The Nova República da Califórnia...now there's a nice place. I'd like to settle down and live there
 some day. Clean, nice people, and very well maintained. It's located right here on your map.}
{126}{}{Obrigado.}
{127}{}{Sim, um tempo atrás, encontrei um campo de mineração abandonado. Pensei que descansaria um dia ou dois,
 Mas então os lobos começaram a aparecer e achei melhor se eu fosse embora. Uma vergonha também; parece o
 Os mineiros deixaram com pressa. Eles deixaram muitas coisas para trás. Não estou planejando voltar, então acho que é
 Tudo bem, se eu lhe mostrar onde está.}
{128}{}{Obrigado.}
{129}{}{Ah ... realmente não importa. Eu apenas decidi viajar um dia e bem, aqui estou eu.}
{130}{}{Talvez você possa me ajudar. Preciso de algumas direções.}
{131}{}{O que você faz?}
{132}{}{Bastante conversando com você.}
{133}{}{Eu faço trabalhos estranhos aqui e aí para me ajudar. Mas principalmente eu apenas viajo.}
{134}{}{Talvez você possa me ajudar. Preciso de algumas direções.}
{135}{}{Onde você dirigiu?}
{136}{}{Bastante conversando com você.}
{137}{}{Eu realmente deveria ir agora. Foi legal conversar com você.}
{138}{}{Talvez nos encontremos novamente.}
{139}{}{Eu quero fazer a próxima cidade ao anoitecer. É melhor eu ir.}
{140}{}{Eu irei.}
{141}{}{Emboscada!}
{142}{}{Não pode confiar em ninguém hoje em dia.}
{143}{}{Você quebrou o código do viajante.}
{144}{}{Hora de ir.}
{145}{}{Eu sumi minha saudação.}
{146}{}{Devo partir.}
