{100}{}{Um vendedor.}
{101}{}{Willy.}
{102}{}{Um bom vendedor ambulante.}
{103}{}{Saudações, amigo, meu nome é Willy e tenho um acordo para você. [Ele parece estar lendo de
 um cartão, e depois de um tempo você cochila.]}
{104}{}{Zzzzzzz ...}
{105}{}{[Você groggily abre seus olhos como você finalmente percebe que alguém está chutando você.] Bem, você está
 interessado ou não?}
{106}{}{Interessado em que?}
{107}{}{Erg?}
{108}{}{Por que, ele fatiga isso, e também pode ser útil contra bichos traquinas. Uma barganha em qualquer
 preço, mas para você é especial para apenas}
{109}{}{Por que é feito apenas da melhor madeira ao redor. Use-o para jab em criaturas para mantê-los à distância ou,
 Se você é habilidoso o suficiente, jogue-o. É muito aerodinâmico e não vai impactar. O que você disse?
 É apenas um roubo}
{110}{}{Esta arma é feita com o melhor aço reciclado. Apenas sinta como isso se encaixa confortavelmente em seu
 mão. E não se preocupe, nossos engenheiros o testaram por segurança e confiabilidade. Nenhum ladrão no seu direito
 A mente se atreveu a tentar roubar se você acenou este bebê ao redor. E isso só irá torná-lo de volta}
{111}{}{Esta pequena jóia é verdadeiramente única. Do outro lado de ... Isso funciona apontando-o
 como ... Olha, não sei o que é isso. Você quer ou não? O preço é}
{112}{}{Este pequeno dândi apenas grita. "Não mexa comigo!" A mera visão dele enviará sua
 inimigos correndo. Uma pechincha no}
{113}{}{Posso dizer que você é o tipo de pessoa que gosta de se aproximar e pessoal ao lidar com
 riff raff. Bem, este pequeno doohickey é exatamente o que você precisa, e isso só vai custar-lhe}
{114}{}{Eu vou levar.}
{115}{}{Vou passar.}
{116}{}{Sim, de fato, você não vai se arrepender disso. Foi bom dar-lhe o negócio. Até a próxima.}
{117}{}{[Fim]}
{118}{}{Merda! Que desperdício do meu tempo. Continue, vença!}
{119}{}{[Fim]}
{120}{}{Bem, esse foi um discurso desperdiçado. $} #continue on 152
{121}{}{Sim.}
{122}{}{Não.}
{123}{}{Ei, é você de novo. Recebi algumas coisas novas - você estava interessado?}
{124}{}{Claro, vamos ouvir o que você conseguiu.}
{125}{}{Não há chance, Willy.}
{126}{}{Sim.}
{127}{}{Não.}
{128}{}{Cai fora! Estou ocupado.}
{129}{}{Volte quando você ganhou algum dinheiro.}
{130}{}{VÁ EMBORA!}
{131}{}{Nenhum reembolso.}
{132}{}{Sem trocas.}
{133}{}{Sem crédito.}
{134}{}{Vá embora, estou ocupado.}
{135}{}{Não é uma jogada inteligente.}
{136}{}{Desgraçado!}
{137}{}{Isso deveria me fazer baixar meus preços?}
{138}{}{Tudo bem, vou baixar os preços.}
{139}{}{Que tal um desconto de 20%?}
{140}{}{Que tal um desconto de 40%?}
{141}{}{Que tal um desconto de 80%?}
{142}{}{Ok, LIVRE; aqui, pegue!}
{143}{}{Willy}
{144}{}{George}
{145}{}{Mike}
{146}{}{Walter}
{147}{}{Charlie}
{148}{}{Freddy}
{149}{}{Mick}
{150}{}{Smitty}
{151}{}{Jack}

{152}{}{. Você quer ou não?}
{200}{}{.}
