{100}{}{Por Unidade!}
{101}{}{Segure-os, cavalheiros!}
{102}{}{Mate os intrusos!}
{103}{}{Proteja a cidade!}
{104}{}{Ir! Ir! Ir!}
{105}{}{Tenha cuidado! Raiders!}
{106}{}{Vamos sair daqui!}
{107}{}{Oh, homem ... quando pensei que estávamos a salvo! Não mais! Não mais!}
{108}{}{Corra por isso!}
{109}{}{Trate nossas pessoas com respeito.}
{110}{}{Não quebre a lei.}
{111}{}{Se você está pensando em causar problemas, lembre-se de nós. Aja legal e Marcus vai agir bem.}
{112}{}{Somos pessoas pacíficas em Broken Hills, mas sabemos como lutar.}
