{100}{}{Deve avisar Lynette!}
{101}{}{Deve avisar a Vault City!}
{102}{}{Outworlder scum ...}
{103}{}{Degenerar a sujeira ...}
{104}{}{Tempo para eliminar mais lixo estrangeiro ... Morra, outworlders!}
{105}{}{O que você está fazendo em torno do Vault City?}
{106}{}{Qual é o seu negócio perto da Vault City?}
{107}{}{Isso faz parte do território da Cidade do Vault.}
{108}{}{Tenha cuidado.}
{109}{}{Vault City não é um santuário para * todos. * Então, siga em frente.}
{110}{}{Seu tipo pertence ao Den.}
{111}{}{Eu sugiro que você vá lá agora.}
{112}{}{Olá, cidadão.}
{113}{}{Qualquer coisa que possamos fazer por você, cidadão?}
{114}{}{Você precisa de uma escolta para Vault City?}
{115}{}{O que você está fazendo tão longe da cidade de Vault, cidadão?}
{116}{}{Estávamos preocupados com o fato de ter sofrido ferimento, cidadão.}
