{150}{}{Deixe nossa terra.}
{151}{}{Você ultrapassa.}
{152}{}{Esta é a nossa terra.}
{153}{}{Deixe os espíritos do céu molharem em você.}
{154}{}{Que o espírito da terra engula você.}
{155}{}{Que os espíritos do vento sopram um mau cheiro na sua direção.}
{156}{}{Espíritos da água deserta você.}
{157}{}{Grandes espíritos de fogo o amaldiçoam.}
