{100}{}{Você vê Buffy, um membro dos aldeões não lavados.}
{101}{}{Você vê Doombot, um membro dos Aldeados não lavados.}
{102}{}{Você vê Panoply, um membro dos aldeões não lavados.}
{103}{}{Você vê Lerk, um membro dos aldeões sem lavagem.}
{104}{}{Você vê Ymir, um membro dos aldeões não lavados.}
{105}{}{Você vê Iguana Eater, um membro dos aldeões não lavados.}
{106}{}{Você vê a Coruja da Noite, um membro dos Aldeados não lavados.}
{107}{}{Você vê Shadow Dancer, um membro dos Aldeios Sem Lavagem.}
{108}{}{Você vê Amish Commando, um membro dos Aldeados sem Lavagem.}
{109}{}{Você vê Alexand the Killer Bee, um membro dos Aldeados não lavados.}
{110}{}{Você vê Hatchetman, um membro dos aldeões não lavados.}
{111}{}{Você vê o BlueCross, um membro dos aldeões não lavados.}

# Examines
{113}{}{Você vê Buffy, uma líder de torcida muito bonita, inteligente e perky. Primeira mulher dos aldeões não lavados.}
{114}{}{Você vê Doombot, Deusa do som e irmã de Buffy. Ela parece muito com Marie Osmond.}
{115}{}{Você vê Panoply, uma menina tipo duende, cujos olhos traem um leve caso de demência.}
{116}{}{Você vê Lerk, Líder da equipe SWAT não lavada - Artista dos aldeões não lavados - Tree Talker.}
{117}{}{Você vê Ymir, o abaixo do poeta e co-fundador do Poetry Bastards - Village Educator.}
{118}{}{Você vê Iguana Eater, Grande Senhor de Smeet Lite.}
{119}{}{Você vê a coruja noturna, ele que observa o sono - co-fundador dos bastões de poesia.}
{120}{}{Você vê Shadow Dancer, Poesia gótica Bastard - Curiosamente, ele se parece muito com Kevin Bacon.}
{121}{}{Você vê Amish Commando, Commissar Of Blunt Force Trauma, Sub-comandante da Unwashed SWAT Team.}
{122}{}{Você vê Alexand the Killer Bee, uma variedade gentil e inteligente de abelhas assassinas - Head Scribe Of The Unwashed Villagers.}
{123}{}{Você vê Hatchetman, Gunsmith of the Unwashed - Starter of fires - Keeper of the Shadowrun lore.}
{124}{}{Você vê o diretor de fabricação BlueCross, Low Priest of the Unwashed.}

# UV Leaving Floats
{200}{}{Aldeados sem lavagem salvar o dia, mais uma vez!}
{201}{}{A morte é muito boa para ele.}
{202}{}{E fique morto!}
{203}{}{A aldeia está segura, mais uma vez!}
{204}{}{Protegemos os inocentes e mantém a paz.}
{205}{}{E nós vamos patrulhar os resíduos. Mantendo-o salvo dos spammers.}
{206}{}{Venha se juntar a nós algum dia!}
{207}{}{Partição é tão doce e armagurado....}
{208}{}{E o Diabo veio e viu quão terrível era ...}
{209}{}{Payback é uma cadela, não é?}
{210}{}{Grim finalmente encontrou um uso - fertilizante.}
{211}{}{Isso é o que você obtém para usar sabão ...}
{212}{}{Estamos fora daqui!}
{213}{}{"Esta casa está limpa".}
{214}{}{Posso puxá-lo com uma vara para ter certeza?}
{215}{}{Não espere por nós!}
{216}{}{É um trabalho sujo, e eu realmente gosto disso!}
{217}{}{De volta à patrulha!}
{218}{}{Os aldeões não lavados. Manter a paz em um terreno desolado.}
{219}{}{Ele teve o que mereceu.}
{220}{}{Eu vou corrê-lo!}

# UV Combat Floats
{300}{}{Sabonete? Não precisamos de sabão colado!}
{301}{}{Rally sem lavar! Destrua o Spammer!}
{302}{}{Morte ao Spammer!}
{303}{}{Isso é para ameaçar a vida das pessoas!}
{304}{}{Agora você vai morrer Grim Reaper.}
{305}{}{Você vai voltar "abaixo"!}
{306}{}{O pool de genes precisa de um pouco de cloro.}
{307}{}{Hora da vingança!}
{308}{}{Agora você vai conseguir isso.}
{309}{}{O aldeão não lavado está aqui para proteger as pessoas da escória como você!}
{310}{}{Deixe as pessoas em paz!}
{311}{}{O poder de DIRT!}
{312}{}{Podemos ser Unwashed, mas estamos aqui para limpar!}
{313}{}{Você não pode nos escapar esta vez!}
{314}{}{Proteja o Escolhido das idiotices do Spammer!}
{315}{}{Escolhido! Junte-se a nós!}
{316}{}{VENGÊNCIA DESPERDIÇADA!}
{317}{}{Você nunca será um tolo infantil "não lavado"!}
{318}{}{Você não tem chance!}
{319}{}{Ainda não terminamos!}
{320}{}{Estive esperando este dia por um tempo muito longo.}

# 1 Buffy Personal Floats
{400}{}{Isso é para me ameaçar!}
{401}{}{Como eu tenho certeza! Você não machucaria uma garota, você é?}
{402}{}{'A vingança é um prato que se serve frio.'}
{403}{}{Eu sou Buffy ... sua torrada.}

# 2 Doombot Personal Floats
{405}{}{Ninguém ameaça Doombot!}
{406}{}{Grim Buster!}

# 3 Panoply Personal Floats
{410}{}{Apenas um guanabana poderia comparar com o sabor desta vitória ...}

# 4 Lerk Personal Floats
{415}{}{A vila é um lugar feliz, mas você ficou muito irritado.}

# 5 Ymir Personal Floats
{420}{}{Você envergonhou nosso país com suas ações pela última vez!}

# 6 Iguana Eater Personal Floats - None

# 7 Night Owl Personal Floats
{430}{}{Eu vou deixá-lo dormir para sempre!}

# 8 Shadow Dancer Personal Floats
{435}{}{Todos estamos indo para o inferno, e eu estou dirigindo o ônibus.}
{436}{}{Venha meu filho, deixe-me tirar a sua dor.}
{437}{}{Você está morto. Você ainda não sabe disso.}

# 9 Amish Commando Personal Floats
{440}{}{Pegar algum!}
{441}{}{Você quer algo disso?}
{442}{}{Não é o rosto, não o rosto!}

# 10 Killer Bee Personal Floats
{445}{}{Dante não escreveu sobre o inferno, eu estou enviando você para ...}

# 11 Hatchetman Personal Floats
{450}{}{Armas! Armas! Armas! Onde estão minhas armas!}
{451}{}{Ok, sim. Eu sou louco. Lide com isso.}

# 12 BlueCross Personal Floats - None
