{100}{}{Você vê ... um modelo de herói branco.}
{101}{}{Você vê um homem branco pesadamente musculoso em um macacão Vault 13. Ele está sorrindo e rindo enquanto ele
 Conta sua história.}
{102}{}{Você vê um modelo de herói branco. Ele está sorrindo e rindo.}
{103}{}{Você vê um modelo de herói branco. Ele está sorrindo e rindo.}
{104}{}{Era impossível manter a carne de cachorro vivo em Fallout 1, especialmente no final.}
{105}{}{Ele simplesmente não era suficientemente resistente para o final do jogo!}
{106}{}{Adorei esse cachorro. Eu queria que ele fosse exibido no filme final.}
{107}{}{Havia esse jogador, Vince DeNardo, que tinha essa tática para manter a carne de cachorro vivo no
 fim.}
{108}{}{Ele o trancaria em uma sala de campo de força em todos os níveis para mantê-lo fora de combate.}
{109}{}{A parte irritante estava fazendo isso em todos os níveis sem que os mutantes desperdiçassem a carne de cachorro.}
{110}{}{Eu acho que ele tirou isso.}
