{100}{}{Você vê ... um modelo de heroína branco.}
{101}{}{Você vê uma bela garota de cabelos curtos em um macacão Vault 13. Ela está brincando e rindo com
 os outros à sua volta.}
{102}{}{Você vê um modelo de heroína branco. Ela está brincando e rindo.}
{103}{}{Você vê um modelo de heroína branco. Ela está brincando e rindo.}
{104}{}{Eu estava sendo administrado por um personagem furtivo, eu acho.}
{105}{}{Ele continuou tentando roubar de todos ... funcionou. A maior parte do tempo.}
{106}{}{Mas garoto, quando não ...}
{107}{}{Nunca vi tantos salva e recarrega na minha vida. Sheesh. Me dê um garoto de combate qualquer dia.}
{108}{}{Sabe, gostei muito da aparência da armadura de combate.}
{109}{}{Eu nunca disse nada antes, mas Ian costumava ... bem, me olha muito em Fallout 1.}
{110}{}{Isso me deixou desconfortável.}
{111}{}{Pensei em conversar com os designers sobre isso, mas eu pensei enquanto Ian não fazia uma sensação, ele
 não foi um problema.}
{112}{}{Ian estava bem olhando; é que ele realmente precisou de um corte de cabelo.}
{113}{}{E um banho. Whoooo-eeeee.}
