{100}{}{Você vê um punk com um meio sorriso.}
{101}{}{Você vê o texugo.}
{102}{}{Você vê um punk com um meio sorriso na cara dele.}
{103}{}{::: Ele grita alto :: Whaddya quer?}
{104}{}{::arroto:::}
{105}{}{Você quem?}
{106}{}{Quem é Você?}
{107}{}{Você pode me falar sobre esse petroleiro?}
{108}{}{O que você faz aqui?}
{109}{}{Gostaria que você invadisse um computador para mim.}
{110}{}{Como está chegando o hacking?}
{111}{}{Nada. Belch agradável.}
{112}{}{:: Ele convoca outro burp throaty ::}
{113}{}{:: Belch mais alto ::}
{114}{}{Bruto.}
{115}{}{:: Ele escreve um horrível eructo que desafia o próprio céu em seu volume e profundidade ::}
{116}{}{::Aplaudir::}
{117}{}{Eu sou um texugo. Eu costumava ter uma banda. :: suspiro :: Chamou-nos aí, nós fumamos. Agora eu sou a tecnologia de informática residente em San Francisco.}
{118}{}{Ah! Tanques!}
{119}{}{Que tipo de coisa de computador você faz?}
{120}{}{Aposto que sua banda sugou.}
{121}{}{A banda era boa?}
{122}{}{Obrigado. Tchau.}
{123}{}{Uhh ... ok.}
{124}{}{Tchau!}
{125}{}{Você deve falar com Marc ou com o Capitão sobre isso.}
{126}{}{Onde posso encontrar o Marc?}
{127}{}{Onde posso encontrar o Capitão?}
{128}{}{Eu sou o genio do computador residente.}
{129}{}{Que tipo de coisa de computador você faz?}
{130}{}{Obrigado. Tchau.}
{131}{}{Não me incomode. :: Ele fala: estou trabalhando nisso, tudo bem?}
{132}{}{Tudo bem, tudo bem. Apenas me avise quando terminar.}
{133}{}{Bem, digamos que sou um especialista em recuperação de informações.}
{134}{}{Você pode recuperar algumas coisas para mim?}
{135}{}{O que isso significa?}
{136}{}{Sim, bem, foda-se você.}
{137}{}{Ei!}
{138}{}{Foda-se também.}
{139}{}{Eu direi! Nós chutamos o traseiro! Nosso cantor era ... umm ... um pouco de ponce, e Aaron sempre suava, e tudo o resto era culpa de Todd. Mas estávamos bem.}
{140}{}{Muito ruim você não está de volta juntos. Eu gostaria de ter ouvido você.}
{141}{}{Umm. Certo. Eu tenho mais perguntas.}
{142}{}{Aposto que você sugou.}
{143}{}{Você geralmente pode encontrar o Marc no bar.}
{144}{}{Obrigado. Eu tenho mais perguntas.}
{145}{}{Obrigado. Isso é tudo.}
{146}{}{O capitão geralmente está na ponte. Basta subir as escadas no bar.}
{147}{}{Obrigado. Eu tenho mais perguntas.}
{148}{}{Obrigado. Isso é tudo.}
{149}{}{Sim, mas vai custar-lhe.}
{150}{}{Qual é o seu preço?}
{151}{}{Tanto faz. Eu tenho que ir.}
{152}{}{Isso significa que eu posso encontrar dados que você precisa.}
{153}{}{Você pode fazer algo para mim?}
{154}{}{Entendo. Legal. Eu tenho mais perguntas.}
{155}{}{Entendo. Obrigado.}
{156}{}{Sim, você teria. De qualquer forma, tenho que voltar a isso.}
{157}{}{Esperar. Eu tenho mais perguntas.}
{158}{}{Obrigado. Até mais.}
{159}{}{Acho que gosto de você o suficiente para que eu possa fazer isso por você agora. Quem você quer que eu visite?}
{160}{}{Os Hubologists.}
{161}{}{O Shi.}
{162}{}{Nem. Apenas checando.}
{163}{}{Suponho que eu posso fazer isso de graça, já que você escolheu minha namorada. Vai demorar um pouco, no entanto. Quem você quer que eu atinja?}
{164}{}{Os Hubologists.}
{165}{}{O Shi.}
{166}{}{Nem. Apenas checando.}
{167}{}{Você deve me fazer um favor, primeiro. Minha namorada se perdeu no petroleiro. Encontre-a para mim e eu vou fazer isso.}
{168}{}{Você entendeu. Até mais.}
{169}{}{Esqueça. Até mais.}
{170}{}{Como roubar doces de um bebê. Eles nunca me encontrarão. O que você quer deles?}
{171}{}{Ótimo. Eu tenho mais perguntas.}
{172}{}{Ótimo. Eu voltarei.}
{173}{}{Eu posso obtê-los. Eles são bastante protetores de suas informações, e eles têm um gelo grave protegendo suas máquinas. Tem certeza de que deseja que eu vá atrás deles?}
{174}{}{Bem, boa sorte. Eu tenho mais perguntas.}
{175}{}{Boa sorte. Voltarei mais tarde.}
{176}{}{Ei, encontre minha namorada e depois conversemos.}
{177}{}{Tudo bem, tudo bem.}
{178}{}{Ela está morta? Ela está morta? Como ela morreu? Não, espere ... não me diga. Me dê algumas horas para me juntar.}
{179}{}{Claro, claro.}
{180}{}{Saia, Sparky. Temos uma merda para fazer.}
{181}{}{Tudo certo. Estou melhor agora.}
{182}{}{Boa. Eu preciso te perguntar uma coisa.}
{183}{}{Bom para você. Eu não queria falar com você.}
{184}{}{Obrigado, obrigado, obrigado. Não posso agradecer o suficiente por salvá-la. O que você quer?}
{185}{}{Eu tenho algumas questões.}
{186}{}{Sua gratidão é suficiente para mim. Tanto tempo.}
{187}{}{Ok, entrei nos computadores Shi. Não sei se eu fiz isso sem ser detectado. Eu acho que agora o melhor é esconder. Você quer alguma outra coisa?}
{188}{}{Sim.}
{189}{}{Não. Veja-te.}
{190}{}{Tenho os Hubologists. Sem problemas. Precisa de mais alguma coisa?}
{191}{}{Sim.}
{192}{}{Não. Veja-te.}
{193}{}{Você cometeu um grande erro, amigo. Acabei de transformar o Shi e os Hubologists contra você através de seus computadores. Você terminou em São Francisco.}
{194}{}{Acho melhor te matar então.}

{195}{}{Me dê algumas horas para me juntar.}
{196}{}{Você quer que eu corte um computador formatado? A informação está desaparecida. Não vai acontecer.}

{197}{}{Eu vou ter que desocupar este lugar.}
{198}{}{É bom te ver.}

{199}{}{Estou procurando algum combustível.}
{200}{}{Eu ouvi o Hubologists ter algum combustível, e eu poderia ter uma aparência em seu computador para você.}
{201}{}{O Shi tem todo o combustível por aqui. Eu poderia dar uma olhada no seu mainframe para você.}
{202}{}{Você pode?}

{203}{}{O que diabos você quer?}
{204}{}{Texugo dos punks, presumo?}
{205}{}{Você desonrou nosso Imperador pela última vez!}
{206}{}{Eu acho que irei buscar alguns doces de Lao Chou na cidade.}
{207}{}{Tanto para um julgamento justo. Hmmm ...}
{208}{}{Cara, acenda. Eu só queria alguns doces.}

{209}{}{Você pode transferir o combustível da nave espacial para o petroleiro?}
{210}{}{Você pode me dar uma cópia do seu plano vertibird?}
{211}{}{Você pode transferir o combustível e me pegar os planos?}
{212}{}{Sim, eu preciso do que eles têm.}
{213}{}{Nah, vou descobrir de outra maneira.}
{214}{}{Tudo bem, mas a merda pode acertar o ventilador.}
{215}{}{Você pode transferir o combustível das suas reservas para o petroleiro?}
{216}{}{Não importa, eu vou fazer de outra maneira.}
{217}{}{Deixa pra lá.}
{218}{}{Bem. Volte comigo em um dia ou mais e eu vou deixar você saber.}
{219}{}{Você conseguiu o que eu precisava?}
{220}{}{Sim, consegui o combustível.}
{221}{}{Sim, eu tenho os planos verti.}
{222}{}{Sim, consegui o combustível e os planos.}
{223}{}{Muito obrigado. Até mais.}

