{100}{}{Você vê uma pessoa com pijama engraçado.}
{101}{}{Você vê um cidadão Shi.}
{102}{}{Essa pessoa parece diferente de qualquer um que você já viu antes. Eles não parecem se importar muito com você.}
{103}{}{Você não é um espião, não é?}
{104}{}{Quem é Você?}
{105}{}{Peixe e algas marinhas. Isso é tudo o que conseguimos.}
{106}{}{Ha ha! Olhe os divertidos olhos redondos!}
{107}{}{Você parece um Hubologist.}
{108}{}{Deixe-nos em paz.}
{109}{}{Viva Lo Pan!}
{110}{}{Com o Dragão!}
{111}{}{Lo Pan é um herói.}
{112}{}{Procure o Dragão. Ele é um problema.}
{113}{}{Esses punks são sempre tão altos.}
{114}{}{Trabalho Trabalho trabalho. Arroz, arroz, arroz. ::suspiro::}
{115}{}{Não existe mais na vida do que isso?}
{116}{}{Nós somos mais inteligentes do que você pensa.}
{117}{}{Veja! A lao wai!}
{118}{}{Bem-vindo ao San Francisco.}
{119}{}{Você parece uma pessoa com uma cabeça reta.}
{120}{}{Lo Pan pode usar sua ajuda.}
{121}{}{Não machuque as pessoas em vermelho, lao wai.}
{122}{}{Lao wai significa "estrangeiro".}
{123}{}{Você está do nosso lado, certo?}
{124}{}{Mate o Dragão para nós, você vai?}
{125}{}{Você nos honra com sua presença.}
{126}{}{Nosso líder! Acometido!}
{127}{}{Devemos vingar-se de Lo Pan!}
{128}{}{Quem nos levará à grandeza se Lo Pan estiver morto?}
{129}{}{O que é que devemos fazer agora?}
{130}{}{Somos desonrados. Devemos morrer como Lo Pan.}
{131}{}{A vida não tem sentido.}
{132}{}{Se Lo Pan está morto, nossos sonhos são esmagados.}
{133}{}{Lo Pan foi o último grande líder.}
{134}{}{O Dragão está morto! Lo Pan é vitorioso!}
{135}{}{Mock os perdedores!}
{136}{}{O Dragão caiu!}
{137}{}{Lo Pan! Lo Pan! Lo Pan!}
{138}{}{Nós somos os vencedores!}
{139}{}{O Dragão está morto. sim!}
{140}{}{Trabalho Trabalho trabalho. Arroz, arroz, arroz. ::suspiro::}
{141}{}{Não existe mais na vida do que isso?}
{142}{}{Nós somos mais inteligentes do que você pensa.}
{143}{}{Veja! A lao wai!}
{144}{}{O porta-voz do imperador! Morto! A cidade desmoronará!}
{145}{}{O que acontece agora?}
{146}{}{Espero que os selvagens não nos invadem agora.}
{147}{}{Os bons sempre morrem jovens.}
{148}{}{Espero que possamos sobreviver sem Ken Lee.}
{149}{}{Ouvi dizer que Ken Lee foi o único que manteve o Imperador na fila.}
{150}{}{Ouvi dizer que o Imperador era apenas uma fachada para Ken Lee.}
{151}{}{Talvez Lo Pan pudesse pegar o ponto de Ken Lee ...}
{152}{}{Trabalho Trabalho trabalho. Arroz, arroz, arroz. ::suspiro::}
{153}{}{Não existe mais na vida do que isso?}
{154}{}{Nós somos mais inteligentes do que você pensa.}
{155}{}{Veja! A lao wai!}

{163}{}{Você matou AHS-9? sim!}
{164}{}{Aqueles Hubologists me dão rancor.}
{165}{}{Você nos fez um excelente serviço.}
{166}{}{Morte aos Hubologists!}
{167}{}{Isso vai apressar aqueles Hubologists fora daqui.}
{168}{}{Estúpidos Hubologists, nem podem proteger seu próprio líder.}
{169}{}{Os Hubologists melhor não vem depois de nós em vingança.}
{170}{}{Eu acho que você não é um espião.}
{171}{}{Filho de porco! Morrer!}
{172}{}{Você desonrou sua família!}
{173}{}{Deixe-nos em paz, lao wai!}
{174}{}{Você não fez danos suficientes?}
{175}{}{Eu te odeio!}
{176}{}{Deixe essa cidade!}
{177}{}{Vá para casa para o seu povo!}
{178}{}{Não obscureça minha vida com seu rosto!}
{179}{}{O que será necessário para se livrar de você?}
{180}{}{Socorro! Socorro!}
