{100}{}{Você vê um punk calvo.}
{101}{}{Você vê Chip. Ele parece melhor.}
{102}{}{Você vê um punk calvo. He seems much recovered.}
{103}{}{Ooh, minhas tripas ... ow, ow, ow.}
{104}{}{Duts?}
{105}{}{Owie?}
{106}{}{Qual o problema com você?}
{107}{}{Você está com dor? Ja ha ha.}
{108}{}{Quem é Você?}
{109}{}{Você tem alguma informação para mim sobre meu povo?}
{110}{}{Oooh, minhas tripas. Estou com dor. Por favor, deixe-me só.}
{111}{}{Entendido.}
{112}{}{O que se passa comigo? Eu vou te dizer: é que fiquei bêbado na semana passada, comecei a jogar com Lao Chou e perdi. Eu estava tão bêbado cego que apostei meu baço. Agora ele tem, e eu preciso de volta.}
{113}{}{VOCÊ VENDE seu baço?}
{114}{}{Isso é ruim.}
{115}{}{Que manequim você deve ser.}
{116}{}{Sim, bem, eu preciso de algumas informações em vez de seu bellyaching.}
{117}{}{:: ele sopra para o ar :: Foda-se.}
{118}{}{:: ele respira para o ar :: Piss off.}
{119}{}{Tanto faz.}
{120}{}{Ei, eu mudei de idéia. Eu quero ajudar.}
{121}{}{Sim, eu vendi. Eu estava bêbado! Além disso, acho que Lao Chou tirou um pouco de Jet na minha bebida. Preciso do meu baço porque eu estou começando a infectar agora.}
{122}{}{Ei, você perdeu. É problema teu. Você lida com isso.}
{123}{}{Bem, diabos, vou dar uma olhada nisso.}
{124}{}{Sim. Preciso do meu baço porque eu estou começando a infectar agora.}
{125}{}{Ei, você perdeu. É problema teu. Você lida com isso.}
{126}{}{Bem, diabos, vou dar uma olhada nisso.}
{127}{}{Eu realmente aprecio isso. Vá falar com Lao Chou, o comerciante, e diga a ele que eu preciso do meu baço de volta.}
{128}{}{Eu voltarei.}
{129}{}{Eu sou Chip. E estou com muita dor.}
{130}{}{Qual o problema com você?}
{131}{}{Você está com dor? Ja ha ha.}
{132}{}{Isso é ruim. So long.}
{133}{}{Em formação? Estou com dor e você quer informação?}
{134}{}{Qual o problema com você?}
{135}{}{Você está com dor? Ja ha ha.}
{136}{}{Esqueça.}
{137}{}{Você já encontrou meu baço?}
{138}{}{Sim. O Dr. Wong Yi Tze tem, e ele irá devolvê-lo. Vá falar com ele sobre isso.}
{139}{}{Sim. Vá ver o cadáver do Dr. Wong.}
{140}{}{Mais ou menos. Dr. Wong Yi Tze tem. Ele não quer me dar isso.}
{141}{}{Eu descobri onde está, mas acho que o Dr. Wong comeu.}
{142}{}{Não, ainda não. Mas eu vou.}
{143}{}{Na verdade, não estou olhando.}
{144}{}{Tudo certo. :: pant :: Antes de eu fazer, talvez devêssemos configurar uma maneira de recuperá-lo. Fale com o Dr. Fung sobre isso, certo? Obrigado.}
{145}{}{Tudo certo.}
{146}{}{Não.}
{147}{}{Eu realmente aprecio o que você está fazendo por mim. Não vou esquecer isso.}
{148}{}{Sem prob.}
{149}{}{Cara, não consigo realmente conseguir lugares sem muito esforço. Se você não pode me ajudar, estou ferrado.}
{150}{}{Bem. Vou falar com Fung.}
{151}{}{Bem. Eu não dou nada por você mesmo.}
{152}{}{Se você pudesse fazer algo sobre isso ... matá-lo, ou falar algum sentido nele, ou algo assim ... Eu vou morrer sem ele.}
{153}{}{Verei o que posso fazer.}
{154}{}{Desculpe, cara ... Eu acho que você está ferrado. Não posso ajudar.}
{155}{}{Sem baga, vou morrer. Obrigado pela sua ajuda de qualquer forma.}
{156}{}{Eu encontrei. Vá até o lugar do Dr. Wong.}
{157}{}{Oh, eu vou te cobrir. Aproxime-se de Fung's.}
{158}{}{Sem prob. Good luck.}
{159}{}{Você falou com Fung?}
{160}{}{Sim, e ele diz que ele vai ficar em você de graça.}
{161}{}{Sim, e ele está me cobrando US $ 1.000.}
{162}{}{}
{163}{}{Uau. Você tem algumas conexões sérias. Volte em um dia e vou ver o que ajuda eu posso lhe dar.}
{164}{}{Você entendeu.}
{165}{}{Você pode me cobrir?}
{166}{}{Sim, suponho.}
{167}{}{Não.}
{168}{}{Eu realmente aprecio isso. Volte em um dia e vou ver o que ajuda eu posso lhe dar.}
{169}{}{Você é melhor.}
{170}{}{Não posso fazer isso sozinho. Acho que vou morrer.}
{171}{}{Oh, tudo bem, vou te cobrir.}
{172}{}{Resistente. Estou quebrado.}
{173}{}{Não posso dizer o quanto melhor eu sinto. Agora, o que você queria de mim?}
{174}{}{Como faço para executar este barco?}
{175}{}{Onde estão minhas pessoas? Você sabe?}
{176}{}{Preciso de algum trabalho de computador feito.}
{177}{}{Nada agora, obrigado. Tchau.}
{178}{}{Verifique com o capitão. Ele mora no escritório do capitão no andar de cima.}
{179}{}{Obrigado. Mais perguntas...}
{180}{}{Obrigado. Tchau.}
{181}{}{A palavra é que eles foram levados para o oeste, através da água. Sua melhor aposta em chegar lá está fazendo funcionar esta banheira.}
{182}{}{Obrigado. Mais perguntas...}
{183}{}{Obrigado. Tchau.}
{184}{}{O trabalho em computador? Se você não pode obtê-lo do Shi ou dos Hubologists, você quer falar com o texugo. Ele é um susto.}
{185}{}{Obrigado. Mais perguntas...}
{186}{}{Obrigado. Tchau.}
{187}{}{Merda. Fale com o Hubologists ou o Shi. Com Badger morto, não tenho ideia.}
{188}{}{Obrigado. Mais perguntas...}
{189}{}{Obrigado. Tchau.}
{190}{}{Desprezível.}
{191}{}{Você vai precisar de analgésicos.}
{192}{}{Dirtball. Eu vou te ajudar.}
{193}{}{Você vê um punk calvo.}
{194}{}{Você vê Chip. Ele parece estar com muita dor.}
{195}{}{Você vê um punk calvo. He is holding his side and gasping in pain.}

{196}{}{Tudo certo. I will talk to Fung.}
{197}{}{Mais sorte com meu baço?}
{198}{}{Sim, e ele queria US $ 1000 - mas eu paguei por isso.}
{199}{}{Obrigado por toda sua ajuda, amigo.}
{200}{}{Cara, eu ouvi você encontrar meu baço. Você sabia falar com o Dr. Fung sobre colocá-lo de volta em mim?}
