{100}{}{Você vê um homem Shi com uma careta no rosto.}
{101}{}{Você vê Dr. Jing Tie Gahng}
{102}{}{Você vê um homem Shi com um casaco de laboratório.}
{103}{}{Quem é Você? O que você quer?}
{104}{}{Wha?}
{105}{}{Quem é Você?}
{106}{}{Eu estou}
{107}{}{Não é da sua conta.}
{108}{}{Nothing. Eu estou leaving now.}
{109}{}{Você não pertence aqui se você for imbecil. Corra agora, antes de chamar os guardas.}
{110}{}{Você realmente não me entende, não é? Talvez você compreenda os guardas. Guardas! Intruso!}
{111}{}{-feito-}
{112}{}{Eu sou Jing Tie Gahng. Estou a cargo do laboratório químico do Steel Palace ... e você está interrompendo um trabalho importante. Por favor saia. AGORA - antes de chamar os guardas.}
{113}{}{Vá em frente e ligue para eles, velho.}
{114}{}{Fine, fine. Eu estou leaving.}
{115}{}{Bem,}
{116}{}{Yes. Eu estou here to obtain fuel for the Poseidon Oil tanker.}
{117}{}{Gostaria de saber o que você faz aqui.}
{118}{}{Eu estou here to obtain fuel for the Hubologists.}
{119}{}{No. Eu estou just leaving now.}
{120}{}{Ahh, mas você vê, é meu negócio. Este é o meu laboratório. Agora, indique o seu negócio.}
{121}{}{Eu estou here to obtain fuel for the Poseidon Oil tanker.}
{122}{}{Gostaria de saber o que você faz aqui.}
{123}{}{Eu estou here to obtain fuel for the Hubologists.}
{124}{}{No. Eu estou just leaving now.}
{125}{}{Você quer combustível para o petroleiro? Eu quero uma armadura de poder endurecida. Eu entendo um Hubologist, um chamado Crocket, tem um processo pelo qual um terno regular de armadura de poder pode ser atualizado. Me pegue tal roupa e eu vou desviar o combustível para você.}
{126}{}{Eu farei isso.}
{127}{}{Não posso fazer promessas.}
{128}{}{Eu tenho um aqui.}
{129}{}{I create compounds and devices for the Emperor and for the Emperor's advisor, Ken Lee. Currently, Eu estou working on fuel derivatives and polymers that will withstand massive attack. Of course, this is of no interest to you since it is, for the most part, theoretical.}
{130}{}{Na verdade, é de interesse. Eu gostaria de combustível para o petroleiro Poseidon.}
{131}{}{Aposto que seria de interesse para os Hubologists. Eles querem combustível.}
{132}{}{Ainda não, não é. Mas voltarei.}
{133}{}{They want fuel, do they? Bem, as irritating as they are, they do have their uses. I have heard they have developed a process wherein they make a suit of power armor even more invincible. If they will upgrade such a suit of armor for me, I will pass the fuel along the pipeline. I assume it's for their toy spaceship.  It is the one called Crocket that you will wish to speak with.}
{134}{}{Eu farei isso.}
{135}{}{Não posso fazer promessas.}
{136}{}{Eu tenho um aqui.}
{137}{}{Mesmo que eu quisesse ajudá-lo, não pude. Nossas reservas de combustível foram esgotadas. Talvez seja melhor você pedir ajuda aos Hubologists. Adeus.}
{138}{}{Oh. Bem, that's all, then.}
{139}{}{Isso será completamente impossível. Nosso abastecimento de combustível já desapareceu. Mesmo que eu quisesse ajudar os Hubologists, o que eu não faço, não pude. Dia bom.}
{140}{}{OK. Tchau.}
{141}{}{Good. Then let me get back to what Eu estou doing.}
{142}{}{-feito-}
{143}{}{You can't do it? Then I can't sell you the fuel. Now go away. Eu estou busy.}
{144}{}{-feito-}
{145}{}{Você endureceu a armadura de poder? Excelente! Como você quer ser pago?}
{146}{}{Canal de combustível para os Hubologists em troca disso.}
{147}{}{Canal de combustível para o petroleiro Poseidon Oil.}
{148}{}{Que tal um pouco de dinheiro? Eu acho $}
{149}{}{Eu decidi que eu preferiria mantê-lo.}
{150}{}{Considere isso feito. Eu vou fazer os ajustes em breve. Agora, se você me desculpar, devo voltar ao trabalho.}
{151}{}{Obrigado. Tchau.}
{152}{}{Muito? Ah! No entanto, para um terno de armadura tão poderoso para estudar ... muito bem. Aqui está o seu dinheiro.}
{153}{}{Obrigado. Tanto tempo.}
{154}{}{Você quer mantê-lo? Muito bem. Se você mudar de opinião, avise-me.}
{155}{}{Eu vou. Tchau.}
{156}{}{Muita chance. Tchau.}
{157}{}{Guardas! Guardas! O estranho está de volta! Mate ele!}
{158}{}{Você falou com este Hubologist que se chama Crocket e obteve a armadura?}
{159}{}{Não, ainda não.}
{160}{}{Então, por que você continua voltando aqui para me incomodar?}
{161}{}{Porque tenho algumas perguntas.}
{162}{}{Eu não faço ideia. Adeus.}
{163}{}{Não tente minha paciência.}
{164}{}{O que você quer?}
{165}{}{O que você faz aqui?}
{166}{}{Eu estou here to obtain fuel for the Poseidon Oil Tanker.}
{167}{}{Eu estou here to obtain fuel for the Hubologists.}
{168}{}{Nada. Desculpa.}
{169}{}{We're all out of fuel now. I can't help you with anything else. Eu estou too busy with this armor. Good day.}
{170}{}{-Tchau-}

{171}{}{. Eu estou just looking around.}
{172}{}{, você realmente tem negócios aqui?}
{173}{}{ seria bom.}
{174}{}{Tenho tudo o que preciso. Fale com Wong se você deve.}
