{100}{}{Você vê um cientista bastante jovem e calvo. Ele parece atento ao seu trabalho.}
{101}{}{Você vê Crocket, o cientista do Hubologist.}
{102}{}{Você vê um cientista relativamente jovem e calvo. Ele parece um geek desleixado.}
{103}{}{Sim? Whaddya quer?}
{104}{}{Agh. Um. Duur.}
{105}{}{O Dr. Jing me enviou. Ele quer alguma armadura de poder endurecida.}
{106}{}{Você pode atualizar a armadura de energia?}
{107}{}{Quem é Você?}
{108}{}{O que você faz aqui?}
{109}{}{Nada, obrigado.}
{110}{}{Eu juro que há mais subhumanos correndo todos os dias. Shoo! Shoo!}
{111}{}{Awww.}
{112}{}{Sim, posso fazer isso. Mas o que você está disposto a trocar por isso?}
{113}{}{O Dr. Jing provavelmente estará disposto a vender seu combustível para a nave espacial.}
{114}{}{Eu posso pagar por isso.}
{115}{}{Eu vou deixar você viver.}
{116}{}{Nada. Esqueça.}
{117}{}{Eu sou Crocket. Eu sou cientista e reparo. Posso voltar para ele?}
{118}{}{Não. Eu tenho mais perguntas.}
{119}{}{Sim claro.}
{120}{}{Desenvolvo novas tecnologias e recebo minha parte da culpa cultista, se você conseguir o meu significado.}
{121}{}{Então você não é um Hubologist?}
{122}{}{Entendi. Tenho mais perguntas.}
{123}{}{Não. O que você quer dizer?}
{124}{}{Qual tecnologia nova você desenvolveu?}
{125}{}{Alto e claro. Até mais.}
{126}{}{Bem ... eu adivinho * que terá que fazer. É um acordo. Você tem a armadura para ser endurecida em você?}
{127}{}{Sim.}
{128}{}{Não.}
{129}{}{Ótimo. Isso custará US $ 10.000, direto, sem troca. Preciso de algum equipamento novo.}
{130}{}{US $ 10.000? Isso é ultrajante! Eu não tenho esse tipo de dinheiro!}
{131}{}{Tudo certo. Aqui está.}
{132}{}{Eu voltarei para você.}
{133}{}{:: ele parece divertido
Você está realmente me ameaçando por isso?}
{134}{}{Sim. Do it or die.}
{135}{}{Não, eu estava brincando.}
{136}{}{Deixe-o aqui por um dia e eu vou fazer isso. Antes de ir, você deve saber que eu só tenho o material para fazer isso por dois conjuntos de armaduras.}
{137}{}{Coisa certa. Tenho mais perguntas.}
{138}{}{Eu voltarei para a armadura.}
{139}{}{Não posso muito bem trabalhar minha magia se você não tiver. Volte quando você faz.}
{140}{}{Tenho mais perguntas.}
{141}{}{Tchau.}
{142}{}{:: ele encolhe os ombros
Você quer essa armadura ou não? São $ 10.000 por todo plano.}
{143}{}{Eu voltarei para você.}
{144}{}{Bem. Aqui.}
{145}{}{Roubo na rodovia. De jeito nenhum.}
{146}{}{:: ele olha nos seus olhos e decide que você é sério ::
Você tem a armadura aqui?}
{147}{}{Sim.}
{148}{}{Não.}
{149}{}{:: ele olha nos seus olhos e decide que está blefando ::
Experimente, bucko. Você terá protetores na sua bunda e você nunca aprenderá a endurecer sua armadura.}
{150}{}{Bem. Morrer, pescoço de lápis.}
{151}{}{Merda. Você chamou meu blefe.}
{152}{}{Bluffer. Eu acho que vamos ver o que os guardas têm a dizer sobre isso.}
{153}{}{Droga!}
{154}{}{Esses caras não conhecem ciência real - eu os ajudo a justificar sua extravagância em troca de algum tempo de inatividade com as senhoras e um salário robusto.}
{155}{}{Hmm. Tive mais perguntas que queria fazer.}
{156}{}{Nada mal. Até mais.}
{157}{}{Vamos ver ... Eu construí um reator nuclear para a nave espacial. Eu criei o processo de endurecimento da armadura de energia. E reparo coisas que estão quebradas.}
{158}{}{I see. Well, Tenho mais perguntas.}
{159}{}{Hmm. Gotta go. Tchau.}
{160}{}{Ei, não tenho carne com você. Apenas não me machuque.}
{161}{}{Eu tenho algumas perguntas para você.}
{162}{}{Estou aqui para minha armadura.}
{163}{}{Muito tarde.}
{164}{}{Tchau.}
{165}{}{Ainda não está pronto. Você tem que me dar tempo!}
{166}{}{Bem. Eu tenho algumas questões.}
{167}{}{Bem. Eu voltarei.}
{168}{}{Eu entendi aqui para você. Pegue, pegue.}
{169}{}{Obrigado. Eu tenho dúvidas.}
{170}{}{Obrigado.}
{171}{}{Obrigado. NOW you can die.}
{172}{}{Estou sem químicos para isso. Desculpa.}
{173}{}{Então você pode me responder algumas perguntas.}
{174}{}{Então você pode morrer.}
{175}{}{Oh. Damn. Tchau.}
{176}{}{Então, onde está o meu combustível? Você me prometeu combustível, buraco.}
{177}{}{Você conseguirá, você conseguirá. Agora responda algumas perguntas.}
{178}{}{Sim, bem, eu te ferrei.}
{179}{}{E pela última vez, também. GUARDAS!}
{180}{}{Morra, idiota.}
{181}{}{Merda. Estou fora daqui.}
{182}{}{Ok, agora, o que você quer?}
{183}{}{Você está pronto para pagar os US $ 10,00 desta vez?}
{184}{}{Deixe-o aqui por um dia e eu vou fazer isso. Lembre-se, porém, este é o último conjunto que posso fazer.}
{185}{}{Ei, eu tenho outro terno para você atualizar.}
