{100}{}{Você vê um homem de cabelo arenoso.}
{101}{}{Você vê Dave H.}
{102}{}{Você vê um homem de cabelo arenoso com um brilho esperançoso para o olho.}
{103}{}{Por que você quer nos ferir?}
{104}{}{Saudações, iluminadas.}
{105}{}{Eu vou seguir em Vikki ... umm ... em breve.}
{106}{}{Como posso ajudá-lo?}
{107}{}{O que você quer?}
{108}{}{Da ... oooh ...}
{109}{}{Quem é Você?}
{110}{}{O que você faz aqui?}
{111}{}{Falei com Vikki. Ela e Juan se burlaram de você e disseram que você não é um homem de verdade.}
{112}{}{Falei com Vikki. Ela disse que você é gostosa e ela quer você em algum momento.}
{113}{}{Você quer que eu fale com Vikki para você?}
{114}{}{De maneira alguma. Obrigado.}
{115}{}{Ummm ... oookay. Tanto faz. Diga, o que está por ai?
[À medida que você se volta para olhar, ele voltou para o que estava fazendo e ignora você]}
{116}{}{-feito-}
{117}{}{Sou Dave Handy. Estou do Canadá.}
{118}{}{Então, o que você faz aqui?}
{119}{}{O que o levou para baixo?}
{120}{}{Obrigado. Tchau.}
{121}{}{Eu mostro a esses caras como mover seus dados e eu respondo estúpidas perguntas durante todo o dia.}
{122}{}{Você poderia invadir o banco de dados Shi?}
{123}{}{Que tipo de perguntas estúpidas?}
{124}{}{Bem, eu tenho outras perguntas para você.}
{125}{}{Parece bom. Tchau.}
{126}{}{Prometa não rir.}
{127}{}{OK.}
{128}{}{Não, esqueça.}
{129}{}{O recrutador do Hub, Vikki Goldman. Eu vi um de seus filmes no Canadá, e eu só sabia que ela se apaixonaria por mim. Ainda não aconteceu, mas estou trabalhando nisso.}
{130}{}{Vou mantê-lo debaixo do meu chapéu. Eu tenho mais algumas perguntas.}
{131}{}{Ha ha! O que você é schlepp! Ela é uma estrela pornô, amigo. Ela não quer você.}
{132}{}{Você percebe que ela apenas irá interessar-se em você para garantir que você permaneça um bom Hubologist, certo?}
{133}{}{Bem, sim ... mas vale a pena, caso algo aconteça!}
{134}{}{Se você diz isso ... se você diz isso. Eu tenho mais perguntas.}
{135}{}{Tanto faz. Até logo.}
{136}{}{:: ele senta em silêncio atordoado por um momento ::
:: dor cruza o rosto ::
Ah bem.
:: ele vira a cabeça fora ::}
{137}{}{Aposto que você quer voltar para ela.}
{138}{}{Desculpa. Eu tenho mais perguntas.}
{139}{}{Tendo entregue essas notícias ... por tanto tempo!}
{140}{}{Você acha que sim. O que você precisa?}
{141}{}{Preciso dos planos vertibird do seu computador.}
{142}{}{Preciso que você forme o disco rígido Hubologist.}
{143}{}{Eu quero que você invadir as bases de dados Shi e obter algum combustível canalizado para o petroleiro Poseidon.}
{144}{}{Eu quero que você reencaminhe o combustível da nave espacial para o petroleiro Poseidon.}
{145}{}{Nada. Tanto tempo.}
{146}{}{Ai está. Agora sai daqui. Eu vou formatar o computador e partir.}
{147}{}{Preciso dos planos vertibird do seu computador.}
{148}{}{Eu quero que você invadir as bases de dados Shi e obter algum combustível canalizado para o petroleiro Poseidon.}
{149}{}{Eu quero que você reencaminhe o combustível da nave espacial para o petroleiro Poseidon.}
{150}{}{Bem, eu realmente estava brincando. Ela realmente não disse isso.}
{151}{}{Boa sorte. Até mais!}
{152}{}{Lá. Ensine esses bastardos a usar e rejeitar-me. Adeus.}
{153}{}{Bem, eu realmente estava brincando. Ela realmente não disse isso.}
{154}{}{Adeus.}
{155}{}{Ela não disse isso. Oh, bom.}
{156}{}{Então, eu fiz todo esse mal por nada. Eu vou matar você agora.}
{157}{}{Tente.}
{158}{}{Ela fez? Mesmo? Uau. :: um sorriso beatifico atravessa lentamente o rosto :: Obrigado! O que posso fazer para você?}
{159}{}{Preciso dos planos vertibird do seu computador.}
{160}{}{Preciso que você forme o disco rígido Hubologist.}
{161}{}{Eu quero que você invadir as bases de dados Shi e obter algum combustível canalizado para o petroleiro Poseidon.}
{162}{}{Eu quero que você reencaminhe o combustível da nave espacial para o petroleiro Poseidon.}
{163}{}{Ahh, nada. Continue e divirta-se.}
{164}{}{Ai está. Algo mais?}
{165}{}{Preciso dos planos vertibird do seu computador.}
{166}{}{Preciso que você forme o disco rígido Hubologist.}
{167}{}{Eu quero que você reencaminhe o combustível da nave espacial para o petroleiro Poseidon.}
{168}{}{Eu quero que você invadir as bases de dados Shi e obter algum combustível canalizado para o petroleiro Poseidon.}
{169}{}{Não. Tanto tempo!}
{170}{}{Formate o disco rígido? Você está de brincadeira? De jeito nenhum! Não posso fazer isso!}
{171}{}{É apenas uma limpeza de rotina. Já fiz backup de tudo mais.}
{172}{}{Oh tudo bem. Eu tenho mais perguntas.}
{173}{}{Oh tudo bem. Tchau.}
{174}{}{Oh. Bem, se você apoiou tudo, eu vou fazer isso. :: ele bate no teclado :: Lá você vai.}
{175}{}{Obrigado! Tanto tempo!}
{176}{}{Eu apenas joguei você como um otário. Tanto tempo!}
{177}{}{Eu vou verificar isso sozinho. Não acho mais fácil formatar o mainframe ainda.}
{178}{}{Tudo certo. Eu tenho mais perguntas.}
{179}{}{Tudo certo. Tchau.}
{180}{}{Não, não ... Eu ficaria muito envergonhado.}
{181}{}{Bem bem. Eu tenho mais perguntas.}
{182}{}{Bem bem.}
{183}{}{Eu deveria ser capaz de. Mas apenas se você tiver uma tarefa específica em mente.}
{184}{}{Desvie o combustível para o petroleiro Poseidon.}
{185}{}{Não consigo pensar em nada específico neste momento. Eu aviso você.}
{186}{}{Oh, como:}
{187}{}{"O meu terminal possui suporte a cartão 3D?"}
{188}{}{"Por que não consigo obter conexão de multiusuário?"}
{189}{}{"Eu acho que devemos mudar a interface, mesmo que esta funcione perfeitamente bem!"}
{190}{}{"Por que não consigo usar uma espada ou uma motosserra no meu monitor?"}
{191}{}{"Eu deveria poder ter duas armas. Por que não posso usar duas armas?"}
{192}{}{"A interface no meu terminal é lenta e desajeitada. Penso que é sua culpa".}
{193}{}{Curtiu isso.}
{194}{}{Entendo. Essas pessoas soam como se fossem muito divertidas. Eu tenho mais perguntas.}
{195}{}{Entendo. Bem, por tanto tempo.}
{196}{}{Eu poderia fazer isso. Mas eu precisaria de um bom motivo para fazê-lo, e eu simplesmente não tenho isso. Desculpa. Algo mais?}
{197}{}{Sim, tenho mais perguntas.}
{198}{}{Não, acho que não.}
{199}{}{Desculpe, o sistema deles não respondeu há algum tempo. Não há nenhuma maneira para eu entrar nisso.}
{200}{}{Eu vou seguir em Vikki ... umm ... em breve. What can I help you with?}
