{100}{}{Você vê uma pessoa suja e malvada.}
{101}{}{Você vê um posseiro.}
{102}{}{Você vê uma pessoa suja e malvada.}
{103}{}{Esta é uma das melhores casas que já tivemos nos anos!}
{104}{}{Ahh ... ar do mar!}
{105}{}{Esta é a vida, hein? Sem patrões, sem governos ... apenas a brisa do mar limpa.}
{106}{}{Há um carro no oceano lá. Muito ruim, está enferrujado.}
{107}{}{Aposto que as crianças adoram aqui.}
{108}{}{Marisco fresco todas as noites! Tasty, mesmo que tenha duas cabeças.}
{109}{}{Nossos vizinhos são certamente "interessantes".}
{110}{}{Nós vamos mudar em algum momento, tenho certeza.}
{111}{}{Você gosta de nossas casas?}
{112}{}{Adoro viver na praia.}
{113}{}{Por favor, não me machuque!}
{114}{}{Não! Não me machuque!}
{115}{}{Deixe meus filhos sozinhos!}
{116}{}{Pare! Não nos machuque!}
{117}{}{Eu farei qualquer coisa!}
{118}{}{Socorro!}
{119}{}{Ah não! Um opressor!}
{120}{}{Oh, se apenas tivéssemos guardas!}
{121}{}{Lamento desistir da proteção da sociedade agora ...}
