{100}{}{Você vê um camponês xi.}
{101}{}{Você vê um trabalhador portuário.}
{102}{}{Você vê um camponês xi cuja roupa é manchada com escamas de peixe, alcatrão e sal.}
{103}{}{Bom dia para estar no oceano.}
{104}{}{Sempre gostei das ondas.}
{105}{}{Você gosta de suco de peixe?}
{106}{}{Sol, ar fresco e frutos do mar. O que mais alguém poderia querer, mas um banho?}
{107}{}{Estou ficando doente de peixe.}
{108}{}{Minhas costas doem.}
{109}{}{Oh, olha ... Outro turista.}
{112}{}{Procure os monstros no petroleiro. Oh, espere ... acho que você já fez.}
{113}{}{Então você está passando pelo petroleiro tudo bem?}
{114}{}{Esse petroleiro é um lugar difícil. Isso é o que dizem os punks.}
{115}{}{Você está chegando a algum lugar lá?}
{116}{}{Bom dia para estar no oceano.}
{117}{}{Sempre gostei das ondas.}
{118}{}{Você gosta de suco de peixe?}
{119}{}{Sol, ar fresco e frutos do mar. O que mais alguém poderia querer, mas um banho?}
{120}{}{Estou ficando doente de peixe.}
{121}{}{Minhas costas doem.}
{122}{}{Oh, olha ... outro turista.}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{}
{150}{}{Hora de morrer, turista.}
{151}{}{Acha que você pode lidar com uma luta na doca?}
{152}{}{Eu não acho que você será muito difícil.}
{153}{}{Vamos ver como você gosta do áspero e da queda de um trabalhador portuário Shi!}
