{100}{}{Você vê uma criança.}
{101}{}{Você vê um garoto doca.}
{102}{}{Você vê uma criança.}
{103}{}{Não gosto deste lugar.}
{104}{}{Há uma grande poeira mal cheia na praia.}
{105}{}{Eww! O que é isso?}
{106}{}{O ar cheira engraçado aqui.}
{107}{}{Quer nadar?}
{108}{}{Eu vou jogar.}
{109}{}{Onde está minha mãe?}
{110}{}{Nós moramos na praia!}
{111}{}{Estou animado.}
{112}{}{Eeeee!}
{113}{}{Socorro!}
{114}{}{Ah não! O bicho papão!}
{115}{}{Mommeeeeeeeeeeeeeeeee!}
{116}{}{Fugir! É um monstro!}
