{100}{}{Você vê um homem Shi curto e rotundo.}
{101}{}{Você vê o Dr. Wong Yi Tze.}
{102}{}{Você vê um homem Shi curto e rotundo.}
{103}{}{Posso ajudá-lo com alguma coisa?}
{104}{}{Daghi nu?}
{105}{}{Você quem?}
{106}{}{Eu ouço você ter o baço de outra pessoa.}
{107}{}{Quem é Você?}
{108}{}{O que você faz aqui?}
{109}{}{Não, obrigado. Isso é tudo.}
{110}{}{Devo confessar, não falo sua língua. Talvez você deva falar com Ken Lee, ele entende muitas línguas diferentes.}
{111}{}{Aagh!}
{112}{}{Eu sou o Dr. Wong. Eu sou o principal cientista desta instalação.}
{113}{}{Mais perguntas, por favor.}
{114}{}{Obrigado. Tchau.}
{115}{}{Eu supervisiono as experiências científicas que criamos e corremos aqui. Eu também estou no comando da rede informática.}
{116}{}{O que você está planejando?}
{117}{}{Como um tem acesso à rede de computadores?}
{118}{}{Eu tenho outras perguntas.}
{119}{}{Entendo. Tchau.}
{120}{}{Ah, mas se eu lhe contar os nossos planos, todos saberão. Receio que eles sejam planos secretos, por enquanto.}
{121}{}{Fine, fine. Eu tenho outras perguntas.}
{122}{}{Obrigado. Tchau.}
{123}{}{Que tal se eu pegar uma arma no seu nariz e forçá-lo a me dizer?}
{124}{}{Por que, alguém aprende como invadir, ou como fazer amizade com um dos meus subordinados. Estou brincando, é claro, com a invasão - se você fizesse isso, eu enviaria alguém depois de você para matá-lo. [Ele sorri para mostrar que ele não significa nenhuma ofensa.]}
{125}{}{Você realmente me mataria?}
{126}{}{Então, você não teria nenhuma objeção real para eu entrar no computador?}
{127}{}{Eu tenho algumas outras perguntas.}
{128}{}{Claro que sim. Tchau.}
{129}{}{Então eu teria que considerá-lo como uma ameaça e adverti-lo que tal curso de ação pode ser prejudicial para sua saúde.}
{130}{}{Vamos tentar.}
{131}{}{I was just kidding. Eu tenho outras perguntas.}
{132}{}{[Ele sorri] Devemos proteger a nossa honra, estranha.}
{133}{}{Err, certo. Então, você teria alguma objeção real para eu entrar no computador?}
{134}{}{Riiight. Eu tenho outras perguntas.}
{135}{}{Aposto. Tchau.}
{136}{}{Se você pode convencer meus subordinados a fazê-lo. Mas certamente não vou.}
{137}{}{E se eu coloquei uma arma no nariz?}
{138}{}{Ótimo. Bem, eu tenho mais perguntas.}
{139}{}{Hmm. Entendo. Bem, tanto tempo.}
{140}{}{Ahh, sim! De fato. Eu vou prepará-lo com favas e um bom chianti.}
{141}{}{Você ainda entendeu? Boa. Chip precisa de volta.}
{142}{}{Isso é um baço humano, seu bastardo doente!}
{143}{}{Você sabe que você deveria servir fígado com esse vinho em vez de baço, certo?}
{144}{}{Isso é um baço humano, você sabe.}
{145}{}{Quem é esse Chip? É o meu baço agora, e eu estou comendo para o jantar.}
{146}{}{Chip é o proprietário original do baço. Ele estava bêbado e vendeu para Lao Chou.}
{147}{}{Ele precisa de sobreviver, você sabe. Ela veio de dentro de seu corpo.}
{148}{}{Então talvez seja melhor eu te matar por isso.}
{149}{}{Um acordo é um acordo. Ele não pode ter isso. Desculpe, mas fizemos uma pechincha e só porque Chip se arrepende agora não significa que ele possa voltar para o acordo dele.}
{150}{}{-Mais-}
{151}{}{É um baço humano? Lao Chou não me disse isso!}
{152}{}{No entanto, por causa da grosseria do mensageiro, acredito que vou manter todas as partes no negócio. Experimentarei em vez disso.}
{153}{}{Diga ao seu amigo para entrar no próximo dia, e com prazer vou devolvê-lo. Só espero que você possa encontrar uma maneira de substituí-lo em seu corpo no tempo.}
{154}{}{Muito bem.}
{155}{}{Ha ha! Sim, eu também vi esse filme antigo.
Espere ... o que você está dizendo? Você está dizendo isso ...?}
{156}{}{Sim, é um baço humano.}
{157}{}{Na verdade, eu me oponho a isso. Você não se mostrou ser de bom caráter. Na verdade, não sei por que estou falando com você. Dia bom.}
{158}{}{-feito-}
{159}{}{Aiee! Guardas! O intruso lao wai está aqui!}
{160}{}{Você tem certos esquemas para me dar?}
{161}{}{Ken Lee me disse para dar isso a você.}
{162}{}{Sim. Agora, o que eu recebo?}
{163}{}{Não, ainda não.}
{164}{}{Fale com Ken Lee, e ele deve discutir o que acontece no seu futuro. Obrigado. Devemos verificar alguns dos nossos dados de teste com estes. Dia bom.}
{165}{}{Na verdade, eu tinha outras perguntas.}
{166}{}{Tanto tempo.}
