{100}{}{Você vê um velho velhote com uma blusa branca.}
{101}{}{Este é o Dr. Fung.}
{102}{}{Você vê um homem idoso com uma blusa branca}
{103}{}{Ajudá-lo com alguma coisa?}
{104}{}{Owie! Ouch! Owwwwwww!}
{105}{}{Sim, estou ferido e parece que você é um médico.}
{106}{}{Sim. Preciso de um médico para o meu amigo.}
{107}{}{Você tem algum stimpacks? Gostaria de comprar alguns.}
{108}{}{Quem é Você?}
{109}{}{Eu tenho um amigo que está faltando um baço. Você pode ajudá-lo?}
{110}{}{O que você pode me falar sobre esse lugar?}
{111}{}{Tchau.}
{112}{}{Deixe-me dar uma olhada nisso. Hmm. Sim. Eu vou ter que cobrar você, é claro.}
{113}{}{Quantos?}
{114}{}{Esqueça.}
{115}{}{Eu posso curar ... mas por um preço, você entende.}
{116}{}{Quantos?}
{117}{}{Esqueça.}
{118}{}{Quem sou eu? Eu sou o Dr. Fung. Eu ensinar e eu curar.}
{119}{}{Dr. Fung? Você conhece Doc Holliday?}
{120}{}{Prazer em conhecê-lo. Preciso de cura.}
{121}{}{Um amigo meu precisa ser curado.}
{122}{}{I see. Obrigado. Tchau.}
{123}{}{Holliday? Sim! Eu ensinei tudo o que ele sabe! Onde ele está agora?}
{124}{}{Ele está morando em Broken Hills.}
{125}{}{Ele foi para casa, ele mesmo? Espero que tenha encontrado paz lá.}
{126}{}{Eu acho que ele tem. Tenho mais perguntas.}
{127}{}{Probably. I have to go. Tchau.}
{128}{}{Isso custará US $ 100.}
{129}{}{Eu vou pagar.}
{130}{}{Esqueça.}
{131}{}{Isso parece ser grave. Isso custará US $ 200.}
{132}{}{Eu vou pagar.}
{133}{}{Esqueça.}
{134}{}{São feridas impressionantes. $ 300 é necessário para obter meus serviços.}
{135}{}{Eu vou pagar.}
{136}{}{Esqueça.}
{137}{}{Por tanto dano, tenho medo de ter que pedir $ 400.}
{138}{}{Eu vou pagar.}
{139}{}{Esqueça.}
{140}{}{Sentar-se. Você precisará quando você ouvir minha conta. Os membros aleijados custam US $ 600.}
{141}{}{Eu vou pagar.}
{142}{}{Esqueça.}

{158}{}{O que? Você não tem o dinheiro? Como você espera que eu sobreviva se você me pede cura gratuita?}
{159}{}{Você tem stimpacks?}
{160}{}{Não, obrigado.}
{161}{}{Foi um prazer fazer negócios com você.}
{162}{}{Obrigado.}
{163}{}{Sua oferta, infelizmente, não é aceitável.}
{164}{}{Que tal agora?}
{165}{}{É tudo o que quero oferecer. Tanto tempo.}
{166}{}{Você está machucado? Tsk, tsk. Um remédio antigo irá curar isso.}
{167}{}{OK!}
{168}{}{}
{169}{}{Foram realizadas. Agora, vá e tenha cuidado!}
{170}{}{Tanques!}
{171}{}{Você precisa de mais?}
{172}{}{Preciso de cura.}
{173}{}{Eu tenho um amigo que precisa de cura.}
{174}{}{Quem é Você?}
{175}{}{Conte-me sobre este lugar.}
{176}{}{Eu tenho um amigo que está faltando um baço. Você pode ajudá-lo?}
{177}{}{Não. Obrigado, no entanto.}
{178}{}{Você veio à pessoa certa. Você gostaria de uma longa história ou curta?}
{179}{}{Longo.}
{180}{}{Curto.}
{181}{}{Nem. Eu tenho outras perguntas, no entanto.}
{182}{}{Nosso povo pousou aqui no submarino Shih-huang-ti, quando os mísseis explodiram pelo mundo. Com a ajuda de um culto, nós, os Shi, reconstruímos São Francisco. Essa é a versão curta.}
{183}{}{E a versão longa?}
{184}{}{Obrigado. I have more questions.}
{185}{}{Obrigado.}
{186}{}{A versão longa é esta: estamos aqui porque nosso povo é descendente da tripulação de um submarino nuclear, chamado Shih-huang-ti. Quando os mísseis caíram no Grande Dilúvio, os sistemas a bordo do submarino falharam e dormimos no escuro durante muitos dias.}
{187}{}{-Mais-}
{188}{}{Finalmente, nós derrubamos a terra. Encontramo-nos perto das ruínas de San Francisco. A maior parte da cidade foi devastada na guerra. Tivemos que recriar a sociedade com base nos poucos sobreviventes que haviam rastejado de volta para a cidade.}
{189}{}{-Mais-}
{190}{}{Reconstruímos com o que pudemos encontrar, e temos cientistas e tecnologia que o mundo deve invejar. Estamos reconstruindo a civilização, mas não como essa horrível criatura mestre fez.}
{191}{}{Entendo. Tenho mais perguntas.}
{192}{}{Obrigado. Tchau.}
{193}{}{Claro que eu posso. E desde que você está ciente de Doc Holliday ... Eu não farei isso por causa da amizade. Diga ao seu amigo sem batismo para vir aqui e eu vou substituí-lo por ele.}
{194}{}{Obrigado! Tenho mais perguntas.}
{195}{}{Obrigado!}
{196}{}{Sim. Eu posso fazer isso. Vai custar-lhe $ 1000 dólares para fazê-lo. Na frente. Você aceita?}
{197}{}{Sim.}
{198}{}{Não.}
{199}{}{Diga ao seu amigo para vir aqui e eu vou substituí-lo por ele.}
{200}{}{Obrigado. I have more questions.}
{201}{}{Obrigado.}
{202}{}{Não posso fazer nada por ele, até você ter os $ 1000. Dia bom.}
{203}{}{Dia bom.}
{204}{}{Não tratarei os inimigos do meu povo. Minhas humildes desculpas.}
{205}{}{Honrado senhor, eu recomendo que você procure os médicos do seu culto.}

{206}{}{O que você pode me falar sobre implantes de armadura?}
{207}{}{Ajudei a escrever o artigo sobre implantes de armadura. Tudo o que preciso é minha experiência e seus materiais. Que tipo de implantes você deseja?}
{208}{}{Qual é o tipo de coisa?}
{209}{}{Os implantes dérmicos.}
{210}{}{A atualização dérmica.}
{211}{}{Implantes de Phoenix.}
{212}{}{A atualização Phoenix.}
{213}{}{Umm ... esqueça. Eu tenho outras perguntas.}
{214}{}{None, actually. Tchau.}
{215}{}{Possui implantes dérmicos, que protegem contra danos concêntricos. Se você gosta desse trabalho, podemos adicionar um único aprimoramento a ele. Nós também temos implantes de Phoenix, que protegem contra ataques à base de calor, e que também possuem uma atualização disponível. Se você estiver interessado nas atualizações, você terá, naturalmente, que esperar até que o conjunto inicial tenha sido instalado. E antes de perguntar, sim, você pode ter as quatro operações.}
{216}{}{Ótimo. Vou tomar os implantes dérmicos.}
{217}{}{Eu quero os implantes dérmicos.}
{218}{}{Me dê a atualização dérmica.}
{219}{}{I’d like the Implantes de Phoenix.}
{220}{}{Tempo para a atualização Phoenix.}
{221}{}{Umm ... esqueça. Eu tenho outras perguntas.}
{222}{}{None, actually. Tchau.}
{223}{}{Excelente. Preciso de um conjunto de armaduras de combate e, oh, $ 5500. Você precisará de dois dias e a habilidade de não escolher as escamas.}
{224}{}{Vamos fazer isso.}
{225}{}{Esqueça. So long.}
{226}{}{A atualização dérmica, hein? Isso vai custar-lhe vários dias de sua vida, $ 33000, armadura de combate e um novo conjunto de cicatrizes que você nunca perderá enquanto viver.}
{227}{}{Assim? Posso pagar tudo isso.}
{228}{}{Hmm. Eu não acho que eu quero pagar tanto. Tanto tempo.}
{229}{}{Se você não se importa de sair com US $ 8500, alguns dias e um conjunto de armaduras de combate, podemos começar a operação agora.}
{230}{}{Me amarre, doc. Estou pronto para ir.}
{231}{}{Isso é um pouco íngreme. Deixe-me voltar para você.}
{232}{}{Esta é uma operação importante. Vai custar-lhe o seu "bom visual", um conjunto de armaduras de combate e $ 49000. Você está disposto a investir nisso?}
{233}{}{Hell yes. Vamos fazer isso.}
{234}{}{Uau. Isso é caro. Eu voltarei para você.}
{235}{}{:: ele balança a cabeça :: Não brinque comigo. Você está perdendo os ingredientes necessários. Ouça mais atentamente para mim na próxima vez. Agora vá e volte quando posso ajudá-lo.}
{236}{}{OK.}
{237}{}{Ai está! Você está ... aprimorado. Lembre-se ... não escolha as escamas, a menos que você queira cicatrizes horríveis para adicionar a sua aparência repentinamente incomum.}
{238}{}{Obrigado, doc. Tanto tempo.}

{239}{}{Eu tenho o dinheiro para o baço.}
{240}{}{Você está interessado novamente em implantes?}
