{100}{}{Você vê alguém em um manto flexível.}
{101}{}{É outro Hubologist vestido.}
{102}{}{Parece ser alguém vestindo um manto.}
{103}{}{Quem é Você? O que você está fazendo aqui?}
{104}{}{Você não deve estar aqui, está?}
{105}{}{Veja! Rim meat!}
{106}{}{Ei! Quem deixou a carne da jante?}
{107}{}{Você não deveria estar vagando sem escolta.}
{108}{}{Ahh! Você está mexendo com meus neurodynes!}
{109}{}{Vá embora, infiel!}
{110}{}{Não fale comigo - sou uma pessoa ocupada.}
{111}{}{Ei! Você está limpando meus neurodynes!}
{112}{}{Talvez eu goste de você melhor se você for alinhado.}
{113}{}{O Pai das Estrelas te amará se você o deixar.}
{114}{}{Você não quer ver Quetzel? Junte-se a nós!}
{115}{}{Vá falar com AHS-7 e junte-se!}
{116}{}{Temos celebridades que são Hubologists, você sabe.}
{117}{}{Juan Cruz e Vikki Goldman são famosos! É por isso que me juntei.}
{118}{}{Aposto que as celebridades vão falar com você se você é legal e legal.}
{119}{}{Eu amo o Hub.}
{120}{}{Gosto de ser um Hubologist.}
{121}{}{Eu quero atualizar minha potencialidade.}
{122}{}{Ainda estou aprendendo a linguagem, para dizer a verdade.}
{123}{}{Elogie o Hub!}
{124}{}{Elogie a grande roda!}
{125}{}{Vamos ao Quetzel!}
{126}{}{Estou ansioso para ir para casa para as estrelas.}
{127}{}{Por favor, não me incomode; Estou concentrando meus neurodynes.}
{128}{}{Por favor, não desalague meus neurodynes.}

{138}{}{Ah não! O perseguidor!}
{139}{}{O não iluminado!}
{140}{}{Mantenha-se longe de mim, carne malvada!}
{141}{}{Você obviamente tem alguns neurodynes ruins!}
{142}{}{Não! Não me polua com seu ódio!}
{143}{}{Guardas! Guardas! O bárbaro está aqui!}
{144}{}{Não me toque!}
{145}{}{Socorro! Guardas!}
{146}{}{O inimigo do nosso povo!}
{147}{}{Os tempos sombrios estão de novo sobre nós!}
{148}{}{Star Father! Salve-me dos pagãos!}
{149}{}{Alguém vai te ferir por sua perfídia!}

{150}{}{Eu amo o Hub.}
{151}{}{Gosto de ser um Hubologist.}
{152}{}{Eu quero atualizar minha potencialidade.}
{153}{}{Ainda estou aprendendo a linguagem, para dizer a verdade.}
{154}{}{Elogie o centro!}
{155}{}{Elogie a grande roda!}
{156}{}{Vamos ao Quetzel!}
{157}{}{Estou ansioso para ir para casa para as estrelas.}
{158}{}{Estou prestes a um alinhamento.}
{159}{}{Estou esperando para ouvir o AHS-9 falar novamente!}
{160}{}{Espero que meus neurodynes estejam certos.}
{161}{}{Eu quero ser um maior Aligned Hub Seeker!}
{162}{}{Tempo para eu me concentrar em meu auto-crescimento.}
{163}{}{A ciência "real" é toda uma série de mentiras.}
{164}{}{Não escute o que os "cientistas" lhe dizem.}
{165}{}{Somente o Hub e o AHS-9 têm a resposta.}

{178}{}{Louvado seja o Pai da Estrela! Nós finalmente vamos às estrelas!}
{179}{}{Planet Quetzel, aqui vamos nós!}
{180}{}{Todo esse trabalho árduo finalmente valeu a pena!}
{181}{}{Meus neurodynes estão totalmente relaxados agora!}
{182}{}{É melhor ficar alinhado antes de decolar.}
{183}{}{Ooh! O Pai da Estrela! O Pai da Estrela!}
{184}{}{Eu sou todo aflutter para a decolagem!}
{185}{}{Em quanto tempo vamos embora?}
{186}{}{Aposto que as altas AHS não são tão nervosas.}
{187}{}{Uau ... as estrelas. Finalmente.}
{188}{}{Eu não vou mais ter que usar um chapéu de papel alumínio!}
