{100}{}{Você vê uma guarda bem armada.}
{101}{}{Você vê uma guarda Hubologist.}
{102}{}{Você vê uma pessoa bem armada com um olhar cruel para os olhos.}
{103}{}{Intruso!}
{104}{}{Obter o intruso!}
{105}{}{Por aqui! Por aqui!}
{106}{}{Hora de morrer, infiel! A Great Wheel rola sobre você!}
{107}{}{Nós somos os Guardiões. Você vai morrer agora.}
{108}{}{Star Father, guia meu objetivo.}
{109}{}{Você contaminou nossos princípios!}
{110}{}{Se os advogados não funcionam, nossas armas irão.}
{111}{}{Nós somos o braço longo da lei do Hub.}
{112}{}{Transgressor!}
{113}{}{Veja seu passo.}
{114}{}{Pegue levemente, estranho.}
{115}{}{Não toque qualquer coisa que você não deveria.}
{116}{}{Se você sair da linha, faremos carne crua de você.}
{117}{}{Seja muito, muito cuidadoso.}
{118}{}{Nós somos a lei do Hub. Não quebre.}
{119}{}{Eu sou AHS-4.}
{120}{}{Eu vou "alinhar" você se você se comportar mal.}
{121}{}{Eu tenho sanção da Grande Roda.}
{122}{}{Saudações, companheiros de viagem.}
{123}{}{Saudações,}
{124}{}{Fico feliz em tê-lo conosco.}
{125}{}{Continue com o seu negócio.}
{126}{}{Não incomode aqueles que tentam se concentrar.}
{127}{}{Sua presença é bem-vinda ... lá.}
{128}{}{O Hub nos colocou a vigiar o seu rebanho.}
{129}{}{O Pai das Estrelas cuida de você. É por isso que ele te deu.}
{130}{}{Somos leais à AHS-9.}
{131}{}{Obedecer.}
{132}{}{Dormir.}
{133}{}{Consumir.}
{134}{}{Nós temos seus melhores interesses no coração.}
{135}{}{.}
