{100}{}{Você vê um punk feminino.}
{101}{}{Você vê um punk feminino.}
{102}{}{Você vê uma jovem bonita e cínica.}
{103}{}{Aposto que meu namorado se ofereceu para me compartilhar.}
{104}{}{Às vezes eu fico cansado de viajar.}
{105}{}{Com certeza, seria bom viver aqui.}
{106}{}{Aposto que podemos fazer uma cena de cena.}
{107}{}{Você esteve do outro lado da água?}
{108}{}{Eu flertaria com você, mas não estou interessado.}
{109}{}{:: sarcasmo :: Certeza são muitas mulheres fortes por aqui, hein?}
{110}{}{Você espera que eu venha para você? Seja real.}
{111}{}{Eu sou único! Assim como todos os outros!}
{112}{}{Às vezes, o cinismo cansado do mundo me aborrece.}
{113}{}{Na próxima vez, quero encontrar uma tribo de góticos.}
{114}{}{Eu ouço o Imperador Shi é desumanamente inteligente.}
{115}{}{Estes Shi com certeza parecem engraçados.}
{116}{}{Tenho a mente aberta, hein?}
{117}{}{Olhe para todos esses novos punks. Posers.}
{118}{}{AHS-9 nos enganou e ele também o enganará se você o deixar.}
{119}{}{O próximo bozo que me chama "cadela" está ficando fritado.}
{120}{}{Então, como foi, levando-o de um mutante?}
{121}{}{Esse grande mutie forte Francis te machucou?}
{122}{}{Estou surpreso que você possa seguir o que Francis fez.}
{123}{}{Eu acho que você ainda estaria sangrando depois de Francis.}
{124}{}{Não posso acreditar que você não ajudaria Chip.}
{125}{}{Bastardo egoísta. Aposto que Chip o ajudaria.}
{126}{}{Todos gostavam de Chip. Agora, ninguém gosta de você.}
{127}{}{Você é bem idiota, não é?}
{128}{}{Já pensou em alguém além de você mesmo?}
{129}{}{Oh, olha, é o "herói".}
{130}{}{Ei, todos! É o idiota egoísta!}
{131}{}{Oh, você novamente? Como se alguém quiser conversar com você agora.}
{132}{}{Chip-Hater!}
{133}{}{Muito ruim sobre o baço.}
{134}{}{Aposto que alguém comeu o fígado de Chip.}
{135}{}{Eu me pergunto se Chip já estará bem novamente.}
{136}{}{Eu acho que Chip é o melhor!}
{137}{}{Mesmo que ele não tenha baço, eu faria Chip em um segundo!}
{138}{}{Obrigado por tentar recuperar o baço de Chip.}
{139}{}{Você fez o seu melhor para Chip.}
{140}{}{Aqui está outra linguagem sobre Chip.}
{141}{}{Pergunto-me se o baço provou bem?}
{142}{}{Yay! Agora eu posso ter Chip e seu baço!}
{143}{}{Eu vou ver Chip agora mesmo!}
{144}{}{Chip é o melhor!}
{145}{}{Eu gosto de você. Você é bom.}
{146}{}{Estou tão feliz por Chip.}
{147}{}{Chip é um homem inteiro agora.}
{148}{}{Você quer se divertir com Chip e eu?}
{149}{}{Você fez bem com o baço de Chip.}
{150}{}{Como você é altruísta de você!}
{151}{}{Suze está de volta! Boa!}
{152}{}{Suze está de volta ... Droga!}
{153}{}{Suze sempre foi muito legal para mim.}
{154}{}{Eu gosto de Suze.}
{155}{}{Obrigado por salvá-la.}
{156}{}{Algumas pessoas precisam aprender a não vagar.}
{157}{}{Quem sabe?}
{158}{}{Pobre texugo. Talvez ele precise de alguém para confortá-lo.}
{159}{}{É melhor eu me certificar de que o Badger esteja bem.}
{160}{}{O texugo é fofo, mas ele não é um dreamboat.}
{161}{}{Pergunto-me por que o texugo pira e faz grandes gestos.}
{162}{}{Badger provavelmente pateta porque está triste.}
{163}{}{Pobre texugo.}
{164}{}{É um mundo velho e difícil em que vivemos.}
{165}{}{Suze deveria ter sabido melhor.}
{166}{}{Se você estiver tomando o barco, devemos deixar isso.}
{167}{}{Desculpe pelo estado em que está o barco.}
{168}{}{Então você estará levando o navio, hein?}
{169}{}{O PMV Valdez é um bom navio - foi uma boa casa.}
{170}{}{Tempo para arrumar minhas coisas, eu acho.}
{171}{}{Aproveite o barco.}
{172}{}{Boa sorte para encontrar o seu povo.}
{173}{}{Eu vou estar indo agora.}
{174}{}{Espero que possamos encontrar outro lugar para viver.}
{175}{}{Pobre texugo. He was a real cutie.}
{176}{}{Quem quer matar Badger?}
{177}{}{Badger cheirava engraçado, mas eu gostava dele.}
{178}{}{Ouvi dizer que o texugo era gay, mas depois conseguiu uma namorada.}
{179}{}{Eu sempre pensei que Badger era abusivo, mas de forma linda.}
{180}{}{Aposto que Badger está mostrando isso a seus amigos.}
{181}{}{Badger ... :: sniff ::}
{182}{}{Badger era uma verdadeira princesa de conto de fadas.}
{183}{}{Você asshole. Por que você o matou?}
{184}{}{Você acha que vamos nos juntar aos Hubologists agora?}
{185}{}{Você é idiota e estúpido.}
{186}{}{Os Hubologists também vão te enganar.}
{187}{}{Você vai para o inferno! Você vai para o inferno e você morreu!}
{188}{}{Eu te odeio.}
{189}{}{Você é um merda.}
{190}{}{Sheepie sheepie sheep!}
{191}{}{Cultist louco!}
{192}{}{Algumas pessoas simplesmente são estúpidas, acho.}
{193}{}{Ei! É o idiota que não consegue pensar por si mesmo!}
