{100}{}{Você vê um Shi entusiasmado.}
{101}{}{Você vê Mai Da Chiang, o proprietário do Red 888 Guns.}
{102}{}{Este é um Shun rotundo que parece que ele está correndo em overdrive permanente.}
{103}{}{Oi! Bem-vindo ao Red 888 Guns! Eu sou Mai Da Chiang, o proprietário. Como posso ajudá-lo?}
{104}{}{Grokken di ma!}
{105}{}{Eu compro!}
{106}{}{Eu estava procurando algum armamento.}
{107}{}{Conte-me sobre o lugar.}
{108}{}{Esqueça.}
{109}{}{Eu sinto Muito! Eu não falo seu idioma! Tenha um bom dia!}
{110}{}{Rrr?}
{111}{}{Ahh, uma arma, hein? Bem, isso é o que eu tenho.}
{112}{}{-Mais-}
{113}{}{Ótimo ótimo. Agradeço pelos seus serviços. Volte logo!}
{114}{}{Mais perguntas!}
{115}{}{Tchau!}
{116}{}{Não é bom o suficiente. Sinto muito. Outra coisa talvez?}
{117}{}{Mais perguntas.}
{118}{}{Não, tchau}
{119}{}{Você precisa de algo mais?}
{120}{}{Eu compro!}
{121}{}{Não, tchau.}
{122}{}{Eu estava procurando algum armamento.}
{123}{}{Conte-me sobre o lugar.}
{124}{}{Esqueça.}
{125}{}{Vivemos aqui há anos, mas nem sempre vivemos aqui. O Dr. Fung conhece a história completa. Aposto que o que você procura é o que fazemos agora.}
{126}{}{Sim.}
{127}{}{Na verdade, eu queria conhecer a história. Eu irei encontrar o Fung. Até logo.}
{128}{}{Agora, somos principalmente pescadores e cientistas. Nossos pescadores pegam peixe. Nossos cientistas estão trabalhando em um projeto que eles dizem que vai mudar o mundo.}
{129}{}{Mude o mundo como?}
{130}{}{O que mais está acontecendo na cidade?}
{131}{}{Hmm. Interessante. Eu tenho mais perguntas.}
{132}{}{Obrigado. Tchau.}
{133}{}{Eu não sei. Eles mantêm seus segredos para si mesmos.}
{134}{}{I see. O que mais está acontecendo na cidade?}
{135}{}{Entendo. Eu tenho mais perguntas.}
{136}{}{Obrigado. Tchau.}
{137}{}{Temos dois rivais de artes marciais na cidade. Eles são Lo Pan, um amante de si mesmo, e o Dragão, que ama os outros. Dizem que quem ganha determinará o futuro das artes marciais.}
{138}{}{Entendo. Mais alguma coisa na cidade?}
{139}{}{Entendo. Eu tenho mais perguntas.}
{140}{}{Obrigado.}
{141}{}{Há uma gangue de vagabundos que se mudaram para o petroleiro Poseidon Oil no cais. Havia monstros vivos dentro dele, mas os vagabundos os selaram no casco inferior. Embora sejam pessoas de fora, agradecemos os drifters para essa tarefa.}
{142}{}{Alguma outra notícia?}
{143}{}{Entendo. Eu tenho mais perguntas.}
{144}{}{Obrigado. Tchau.}
{145}{}{Os cientistas relatam que alguém perdeu a segurança do computador e roubou nossos segredos.}
{146}{}{Alguma outra notícia?}
{147}{}{Entendo. Eu tenho mais perguntas.}
{148}{}{Obrigado. Tchau.}
{149}{}{Isso é tudo o que posso pensar no momento. Dia bom.}
{150}{}{Dia bom.}
{151}{}{Você é um ladrão, um assassino e um vilão. Tenho medo de matá-lo.}

