{100}{}{Você vê um casal ansiosamente saudável.}
{101}{}{Você vê Juan Cruz e Vikki Goldman, duas das estrelas de cinema mais notáveis   de New Reno.}
{102}{}{Você vê um homem de cabelos escuros e uma mulher loira, ambos extremamente atraentes. Eles exalam uma vibrante "come-up" vibe.}
{103}{}{Ele: Olá! Sou Juan Cruz! Ela: E eu sou Vikki Goldman! Ambos: somos celebridades! E endossamos o Hubology! Ambos: observe que quaisquer semelhanças entre nós e pessoas ou instituições, vivas ou mortas, são inteiramente coincidentes.}
{104}{}{Ah? Cluz? Doldnin?}
{105}{}{Celebridades? O que faz você celebridades?}
{106}{}{Similitudes? O que você quer dizer?}
{107}{}{Eu quero ser um Hubologist. Como faço para me juntar?}
{108}{}{Eh, Vikki, Dave H. está apaixonado por você.}
{109}{}{Ótimo. Tenho que ir.}
{110}{}{Ele: um pobre filho do lixo. Ela: talvez um alinhamento ajudasse? Ele: Sim. Você. Você gostaria de um alinhamento?}
{111}{}{'Es!}
{112}{}{Não!}
{113}{}{Ela: eu espero que tenha ajudado. Boa sorte nas suas viagens!}
{114}{}{Goo-bye!}
{115}{}{Certamente tem!}
{116}{}{Ele: Se você não aceitar a nossa ajuda ... Ela: ... então não podemos ajudá-lo. Adeus.}
{117}{}{Tchau!}
{118}{}{Ele: Ah, você vê? Os ensinamentos do Hub demonstraram o seu valor novamente!}
{119}{}{Eu tenho algumas questões.}
{120}{}{Thanks! Tchau!}
{121}{}{Ela: por que, estávamos no negócio do cinema em New Reno. Criamos centenas de filmes, muitos deles clássicos, como "Top Bun", "Frisky Bizness" e "Days of Rubber". Isso é o que nos faz celebridades.}
{122}{}{Ele: Mas, como membro da indústria, você já sabia disso.}
{123}{}{É bom finalmente colocar rostos aos nomes.}
{124}{}{Quem se importa se você o aprova? Não devo fazer minhas próprias escolhas?}
{125}{}{Entendo. Bem, eu tenho mais perguntas para você.}
{126}{}{Obrigado tchau.}
{127}{}{Ela: Ah, sim, você definitivamente deve fazer suas próprias escolhas. Ele: E com o último livro do Hub, você pode aprender como fazer a escolha DIREITA!}
{128}{}{Seu último livro? Ele não está morto?}
{129}{}{A escolha certa. Certo. E quanto ao livre arbítrio?}
{130}{}{Parece bom. Como faço para me juntar?}
{131}{}{Certo. Eu tenho mais perguntas.}
{132}{}{Certo. Tchau.}
{133}{}{Ele: Mais perguntas? Então nós temos as respostas! Provado pelas graças da Grande Rodada, é claro.}
{134}{}{Como faço para me juntar?}
{135}{}{O que faz você celebridades?}
{136}{}{Não devo fazer minhas próprias escolhas, em vez de deixar que as celebridades me guiem?}
{137}{}{Como faço para me juntar?}
{138}{}{Eh, Vikki, Dave H. está apaixonado por você.}
{139}{}{Não, não há mais perguntas.}
{140}{}{Ela: [olhar gelado em branco] Ele: Obrigado.}
{141}{}{Err... Eu tenho algumas questões.}
{142}{}{Isso é tudo para mim! Tanto tempo!}
{143}{}{Ele: Morto? Ha ha! Possivelmente. Nós gostamos de pensar que ele alinhou todos os seus neurodynes e foi juntar-se ao Star Father. Ela: Nós usamos amplamente suas notas anotadas e manuscritos mal encaminhados para espalhar a palavra do Hub. Ele: por exemplo, encontramos uma sucata que dizia: "2 doz. Ovos / Leite / TP". Obviamente isso é significativo. Precisa ser ouvido.}
{144}{}{Err ... certo. Eu tenho mais perguntas.}
{145}{}{O que, porque algum crackpot escreveu algo, sente a necessidade de publicar tudo?}
{146}{}{Yes! Praise the Hub! I see the light! Como faço para me juntar?}
{147}{}{Certo. Tchau.}
{148}{}{Ele: Sim. Alguns podem pensar que nos parecemos a certas pessoas. Ela: Mas a verdade é que é totalmente coincidente.}
{149}{}{Whew. Bem, isso é uma carga. Diga, eu tenho mais perguntas.}
{150}{}{Consegui. Tanto tempo.}
{151}{}{Ela: Claro que você tem seu livre arbítrio. Você tem a opção de permitir que seus neurônios sejam preenchidos com a imundície do mundo. Ele: você tem a opção de viver uma existência sem alegria e sem sentido na raça dos ratos. Ambos: Ou você pode chegar a uma maior compreensão da vida através da Grande Roda.}
{152}{}{Neurodynes? O que eles são?}
{153}{}{Parece bom. Como posso me juntar?}
{154}{}{Hmm. Eu acho que vou ficar com a corrida de ratos.}
{155}{}{Direito-o. Bem, eu tenho que correr.}
{156}{}{Ela: você se atreve a chamar o Hub (louve sua visão) um crackpot? Aqui? Em uma fortaleza dedicada ao seu estudo? Ele: saia daqui. Se você conversar com alguém a caminho, você será atacado. Infiel. Ambos: bom desembarque.}
{157}{}{Talvez eu melhor pular neles. Eu sempre detestei seus filmes de qualquer maneira. Vamos ver você fazer uma cena da morte.}
{158}{}{Seus filmes sugam. Tchau.}
{159}{}{Tchau.}
{160}{}{Ela: Neurodynes são a essência das almas destruídas na Grande Guerra, poluindo sua essência espiritual e orientando-se por você. Ele: se você quiser saber mais sobre nossos ensinamentos, você terá que se juntar à nossa igreja.}
{161}{}{Sim, isso parece fascinante.}
{162}{}{Eu tinha ouvido isso era ficção científica, mas eu não sabia o quanto. O Hub deve ter sido um crackpot.}
{163}{}{Bem, definitivamente estou curioso sobre o que você tem. Conte comigo.}
{164}{}{Hmm. Nah, não agora. No entanto, tenho mais perguntas.}
{165}{}{Umm... gotta go. Tchau.}
{166}{}{Ele: Isso é muito avançado - pensando em você. Ela: muito iluminada. Ele: oferecemos nossas opiniões às pessoas - e se nossa celebridade pode atrair mais crentes, estamos ansiosos para usá-la.}
{167}{}{Tenho outras questões.}
{168}{}{Estou interessado em participar.}
{169}{}{Entendo. Bem, por tanto tempo.}
{170}{}{Ele: Bem, é muito simples. Nós apenas lhe damos esse holodisco informativo. Ela: ... você sente um filme curto ... Ele ... e então você vai falar com a AHS-7! Ela: Fácil, não é?}
{171}{}{Vamos fazer isso.}
{172}{}{Eu não acho que estou pronto para isso.}
{173}{}{Ela: é sua prerrogativa. Ele: E espero que você entenda que não pode permitir-se vagar pela nossa base. Ela: então é melhor você sair - os guardas provavelmente vão atirar em você se você ficar por aí.}
{174}{}{Caramba, valeu. Convide-me para me recrutar e me atirar se eu não me inscrever? Bom show.}
{175}{}{Talvez seja melhor você atirar em você primeiro.}
{176}{}{Estou fora daqui.}
{177}{}{Ele: esta é a sua última chance de mudar de ideia. Ela: Odiamos ver algo ruim acontecer com você.}
{178}{}{Dane-se.}
{179}{}{Fine. Como faço para me juntar?}
{180}{}{Algo ruim está a ponto de acontecer com você.}
{181}{}{Não. Eu irei me arriscar. Tanto tempo.}
{182}{}{Ele: fizemos tudo o que podemos para você. Ela: boa sorte nas suas viagens.}
{183}{}{Tchau!}
{184}{}{Ela: Dave? O cara do computador? Ele: Ha ha! Que perdedor! Vikki é minha, toda mina - de jeito que ele ... desculpe, essa é energia negativa que estou canalizando. Devo ter esfregado meu neurodynes. Ela: [sussurra para você] Eu acho que Dave é uma bela, mas nada pode acontecer enquanto Juan está por perto. Ele: Whew. Neurodyne está claro novamente.}
{185}{}{Bem, eu tenho mais perguntas.}
{186}{}{That's all. Tchau.}
{187}{}{Ela: Isso não foi tão ruim, foi? Ele: Agora, vá falar com AHS-7 e seremos camaradas no Hubology! Ela: Estou tão animada! Ele: Obter novos recrutas me deixa excitado. Ela: Oh, querida ... Ele: Oh, querida ...}
{188}{}{Eu apenas volto mais tarde.}
{189}{}{Ele: muito ruim. Ela: você está comprometida agora.}
{190}{}{-feito-}
{191}{}{Ele: você tomou uma decisão que altera a vida. Ela: E, infelizmente, era errada. Ambos: Guardas! Guardas!}
{192}{}{Droga.}
{193}{}{Ele: Saudações,}
{194}{}{Então, o que eu faço agora que sou um Hubologist?}
{195}{}{Como posso me conectar com vocês?}
{196}{}{Isso é praticamente tudo o que eu queria. Tanto tempo!}
{197}{}{}
{198}{}{}
{199}{}{Ele: você poderia falar com Harry Rocket na superfície. Talvez ele precise de ajuda. Ela: Ou você poderia falar com AHS-7 ou AHS-9. Eles geralmente têm idéias. Ele: Ou você pode assistir o PrayScreen. Ela: Ou você poderia causar maldade entre os inimigos da Roda.}
{200}{}{Obrigado. Como me ligar com vocês?}
{201}{}{Obrigado. Isso é tudo o que eu queria saber.}
{202}{}{Ela: tão triste como é - porque o Pai das Estrelas sabe que você é uma linda - provavelmente não devemos. Ele: Mas ambos estamos lisonjeados! Ela: talvez algum dia possamos todos ir para New Reno e fazer um filme juntos.}
{203}{}{Oh tudo bem. O que mais há para fazer como um Hubologist?}
{204}{}{Oh tudo bem. Tanto tempo.}
{205}{}{Ela: mentir é ruim para o seu neurodynes. Ele: está certo. Ela: é por isso que tenho que ser sincero e dizer que não te acho atraente. Ele: Mas nós ainda te amamos como um seguidor companheiro do Hub!}
{206}{}{Caramba, valeu. Então, o que mais tem para fazer como um Hubologist?}
{207}{}{Tanto faz. [muting] idiotas.}
{208}{}{Saudações, novos recrutas!}
{209}{}{Eu sou Vikki Goldman!}
{210}{}{E eu sou Juan Cruz!}
{211}{}{Nós somos celebridades, como você já conhece.}
{212}{}{Pensamos que o Hubology é o caminho a seguir.}
{213}{}{Nós SABEMOS O Hubology é o caminho a seguir.}
{214}{}{Eu posso fritar erros com o poder do meu cérebro!}
{215}{}{Parece bom em chapéus de papelão!}
{216}{}{Talvez se você trabalhe duro para se otimizar, você pode se associar conosco.}
{217}{}{Gostaríamos certamente disso.}
{218}{}{Sim. Estamos sempre à procura de amigos ...}
{219}{}{... enquanto estiverem dispostos a otimizar-se.}
{220}{}{E são tão altos como nós.}
{221}{}{Nós somos AHS-5.}
{222}{}{Você pode ser AHS-5 algum dia.}
{223}{}{Se você doar muito dinheiro, você pode ser AHS-5 ainda mais rápido.}
{224}{}{Mas não pense que nós só queremos você pelo dinheiro.}
{225}{}{Não, queremos ajudá-lo.}
{226}{}{E é disso que se refere a Hubology.}
{227}{}{[aplausos]}

{228}{}{. Espero que sua iluminação esteja indo bem. Ela: temos tantas ... grandes ... esperanças para você.}

{229}{}{Lição 1: Aqui temos a eternidade, a Grande Roda. [aponta para algo] E aqui é onde estamos. [aponta para algo] Agora, tudo o que temos a fazer é andar muito longe e conhecer nossos irmãos estrelados lá.}
{230}{}{Cara, vamos precisar de muitos sapatos.}

{231}{}{Ele: Agora, vá falar com AHS-7 e seremos camaradas no Hubology! Ela: Estou tão animada! Ele: Obter novos recrutas me deixa excitado. Ela: Oh, querida ... Ele: Oh, querida ...}
