{100}{}{Você vê um homem Shi curioso que parece ser cheio de conhecimento.}
{101}{}{Você vê Ken Lee, conselheiro do Imperador.}
{102}{}{Você vê um homem curioso Shi e um meio sorriso.}
{103}{}{O que você gostaria, amigo?}
{104}{}{O que você quer?}
{105}{}{O que posso fazer para você?}
{106}{}{Você?}
{107}{}{Quem é Você?}
{108}{}{O que é este lugar?}
{109}{}{Estou à procura de alguns aldeões perdidos.}
{110}{}{Preciso de combustível.}
{111}{}{Gostaria de falar com o Imperador.}
{112}{}{Os Hubologists me designaram para matar o Imperador.}
{113}{}{Nada. Obrigado. Tchau.}
{114}{}{Eu sou Ken Lee, conselheiro do Imperador. E você, meu amigo, parece ser simples, então lembre-se disso: se você procurar o Enclave, então você deve pegar o petroleiro Poseidon. Você precisará de combustível para o petroleiro. Você tem minha benção.}
{115}{}{Tanques!}
{116}{}{Eu sou Ken Lee. Eu sou o conselheiro do imperador. O Imperador me aconselha a não falar com você, e assim não o farei. Bom dia, tolo.}
{117}{}{Grrr!}
{118}{}{Ahh, viajante, não posso ajudá-lo. Talvez você possa encontrar a resposta para sua missão de outra forma. Dia bom.}
{119}{}{Dood dia!}
{120}{}{Eu sou Ken Lee. Sou o conselheiro do Imperador dos Shi. Trago a sabedoria do Imperador. E quem é você?}
{121}{}{Gostaria de ver o Imperador.}
{122}{}{eu sou}
{123}{}{Você soa como um flunky crescido para mim.}
{124}{}{Ninguém é importante. Adeus.}
{125}{}{Este é o Palácio de Aço do Imperador. Este é o coração de Shi-town.}
{126}{}{E onde está o imperador?}
{127}{}{Que tipo de pesquisa você faz aqui?}
{128}{}{Qual é a história do lugar?}
{129}{}{Entendo. Tanto tempo.}
{130}{}{Se você deseja ver o Imperador, então você deve me dar seu próprio nome.}
{131}{}{Oh. Certo. Eu estou}
{132}{}{Certo. Meu nome é}
{133}{}{Sim.}
{134}{}{Esqueça.}
{135}{}{Nem todo mundo tem a chance de ver o Imperador. Você deve primeiro provar seu valor. Você está disposto a provar o seu?}
{136}{}{Sim.}
{137}{}{Não. Já tive testes suficientes nos últimos meses para me durar toda a vida.}
{138}{}{Não acredito que o Imperador gostaria de vê-lo. Foi-me dito para proibir a entrada para aqueles que me ofendem ou que relembram o mal. Você faz os dois, viajante. Dia bom.}
{139}{}{-feito-}
{140}{}{Insultos não o levará a lugar algum, viajante, exceto removido do Steel Palace. Por favor, controle sua língua.}
{141}{}{Me faz.}
{142}{}{Bem.}
{143}{}{O Imperador permanece escondido de olhos curiosos. Como meu trabalho é agir como a tela do Imperador, não posso nem direi onde ele está.}
{144}{}{Bem. Tenho mais perguntas.}
{145}{}{Bem. Bye.}
{146}{}{Fazemos pesquisas que mudarão o mundo. Para mais respostas para suas perguntas, você deve procurar o Dr. Wong Yi Tze.}
{147}{}{Eu vou. E eu tenho mais perguntas.}
{148}{}{Eu vou. Tchau.}
{149}{}{Nós fomos os sobreviventes do naufrágio de um submarino. Quando encurralamos, despojamos o metal do submarino para criar o Palácio. Alguns não acreditam nisso.}
{150}{}{Hm. Parece quase como se estivesse repreendendo alguém.}
{151}{}{Entendo. Obrigado. Tchau.}
{152}{}{Ah sim! Eu vi alguns de seus filmes. Ainda assim, esse não é o seu nome real?}
{153}{}{Claro que é.}
{154}{}{Não. Meu verdadeiro nome é}
{155}{}{É todo o nome que você precisa, velho.}
{156}{}{Isso será completamente impossível. Dia bom.}
{157}{}{-feito-}
{158}{}{Certamente você deve me dar mais crédito do que isso. Eu sei como o "biz" funciona. Viajei a New Reno antes.}
{159}{}{Ok, meu nome é}
{160}{}{Esse é o meu verdadeiro nome! Agora, deixe-me falar com o Imperador!}
{161}{}{Excelente. Isto é o que eu preciso de você: há uma pequena base militar no norte daqui, chamada Navarro. Existem numerosos vertibirds lá. Precisamos planos e planos para fabricar alguns dos nossos. Procure isso e você estará no seu caminho para ver o Imperador.}
{162}{}{Você entendeu.}
{163}{}{Esqueça.}
{164}{}{Você irá reconsiderar a nossa prova?}
{165}{}{Não.}
{166}{}{Oh tudo bem. Eu vou fazer isso.}
{167}{}{Aldeões perdidos? Não ouvi nada disso. Talvez o Imperador os conhecesse.}
{168}{}{Tenho mais perguntas.}
{169}{}{Obrigado. Eu farei isso.}
{170}{}{Você deve completar um segundo teste: os Hubologists são nossos inimigos. Seu líder, AHS-9, vem seqüestrando e lavando o cérebro de nossos filhos. Mate-o pelo bem do Shi e eu direi-lhe como falar com o Imperador.}
{171}{}{Ele está tão bem como morto.}
{172}{}{Não, acho que não.}
{173}{}{Não? Isso me entristece, mas eu entendo. Boa sorte na sua missão. Se você mudar de idéia, você sabe onde me alcançar.}
{174}{}{Sure do. Tenho mais perguntas.}
{175}{}{Sim. Tchau.}
{176}{}{eu sou anxious to see the result of your attempt. Dia bom.}
{177}{}{Dia bom.}
{178}{}{Berating alguém? Qualquer idiota que tenha feito suas pesquisas pode ver que a própria base de Shi-town é o naufrágio deste submarino. Parece infrutífero argumentar com aqueles que diriam que não há submarino.}
{179}{}{Isso é muito temperado de você.}
{180}{}{Certamente é. E lidar com essas pessoas em uma base diária. Infelizmente!}
{181}{}{Well, Tenho mais perguntas.}
{182}{}{Sim, pobre você. Tchau.}
{183}{}{Você certamente é um destinatário digno do nosso combustível. Eu acredito que posso confiar em você com nossos segredos. Na sala das costas, você achará que o campo de força para o computador grande foi desligado. Digite a senha "CSPDMSHR-Shih-huang-ti-X9372" e você se encontrará conectado ao Emperor Computer. O Imperador poderá dirigir nosso combustível para onde você precisa.}
{184}{}{Obrigado.}
{185}{}{Guardas! O inimigo está entre nós! Guardas!}
{186}{}{Eles realmente? Talvez você gostaria de virar as tabelas sobre eles? Posso prometer-lhe o nosso auxílio se você concordar em matar AHS-9.}
{187}{}{Ele está tão bem como morto.}
{188}{}{Não.}
{189}{}{Excelente. Espero ouvir o seu sucesso em breve.}
{190}{}{You will. Tenho mais perguntas.}
{191}{}{Você irá. Tchau.}
{192}{}{Then in that case, you can only be an enemy. Dia bom.}
{193}{}{Dia bom.}
{194}{}{Com a morte de AHS-9, o Grande e Terrível, os Hubologists não representam uma ameaça real para nós e nossas pesquisas. Bem feito. Você tem nossa gratidão. Gostaria de falar com o Imperador?}
{195}{}{Sim.}
{196}{}{Não agora. Eu tenho outras perguntas, no entanto.}
{197}{}{Você provou ser um amigo do Shi. Eu acredito que posso confiar em você com nossos segredos. Na sala das costas, você achará que o campo de força para o computador grande foi desligado. Digite a senha "CSPDMSHR-Shih-huang-ti-X9372" e você se encontrará conectado ao Emperor Computer. Espero que isso seja útil para você.}
{198}{}{O Imperador é um COMPUTADOR?}
{199}{}{Got it. Obrigado.}
{200}{}{Sim. It stores our history, our research, and projects possibilities for the future. It is far better than any fallible human- yet we temper its suggestions with our own knowledge of human nature.}
{201}{}{Entendo. Bem, obrigado pelo seu tempo. Eu tenho uma aldeia para resgatar.}
{202}{}{Nossos espiões relatam que você deu os planos do vertibird aos Hubologists. Roube-os para nós e você será recompensado.}
{203}{}{Você entendeu. I have some questions.}
{204}{}{De jeito nenhum.}
{205}{}{Thank you for the vertibird plans, traveler. O que posso fazer para você?}
{206}{}{Eu tenho dúvidas.}
{207}{}{Um ... Nada.}
{208}{}{Uma vez que você obteve os planos de vertibird, entregue-os ao Dr. Wong Yi Tze. Ele irá usá-los.}
{209}{}{OK. Eu tenho outras perguntas.}
{210}{}{OK. Tchau.}

{211}{}{. Gostaria de ver o Imperador.}
{212}{}{.}

{213}{}{Lembre-se, você deve levar os planos para o Dr. Wong Yi Tze.}
{214}{}{Você voltou a me insultar novamente. Eu acho que não.}
{215}{}{Como expliquei, precisarei saber o seu nome.}
{216}{}{Tudo bem, é}
{217}{}{Esqueça, seu idiota!}
{218}{}{Lembre-se, o Imperador aguarda a morte de AHS-9.}
{219}{}{eu sou sorry.  But I cannot offer what fuel we have to you.  Perhaps if you were to speak to the Emperor?}
{220}{}{Como faço isso?}
{221}{}{Posso fazer outra pergunta?}
{222}{}{Gostaria de poder oferecer-lhe o nosso combustível, mas, infelizmente, nossas lojas estão vazias. Eles foram desviados por algum meio para os Hubologists. É possível que você possa encontrar alguém para desviá-lo de volta.}
{223}{}{Posso ver o Imperador agora?}
{224}{}{Respeito respeitosamente que, a menos que você tenha dado os planos do vertibird ao Dr. Wong Yi Tze, não posso conceder-lhe acesso ao Imperador. Espero que entenda.}

#Ken Lee's guard floats
{500}{}{Saia imediatamente, ou ligarei para os guardas.}
{501}{}{Saia agora. Este é o seu segundo aviso.}
{502}{}{Este é o último aviso.}
