{100}{}{Você vê um homem que parece muito com um comerciante.}
{101}{}{Você vê Lao Chou, o comerciante.}
{102}{}{Você vê um homem com roupas funcionais e confortáveis.}
{103}{}{Saudações! Bem-vindo à minha loja, Flying Dragon 8.}
{104}{}{O que posso fazer para você?}
{105}{}{Da aggle oo!}
{106}{}{Coisa!}
{107}{}{Quem é Você?}
{108}{}{Estou procurando algum equipamento.}
{109}{}{Estou procurando por alguma informação.}
{110}{}{Tchau.}
{111}{}{Você quer comprar algo?}
{112}{}{:: cabeça de cabeça ::}
{113}{}{::balançar a cabeça::}
{114}{}{É isso que temos, então.}
{115}{}{- fim -}
{116}{}{Bem, tenho medo que seja tudo o que posso fazer por você. Dia bom.}
{117}{}{-feito-}
{118}{}{Eu sou Lao Chou. Eu administra este estabelecimento, Flying Dragon 8, uma loja geral. Fui conhecido por negociar ... informações.}
{119}{}{Que tipo de informação?}
{120}{}{Entendo. Eu gostaria de algum equipamento.}
{121}{}{Pouco acontece nessa cidade que eu não conheço. Claro, você deve saber a pergunta certa para perguntar, sim? O que você precisa saber?}
{122}{}{Estou procurando atualizações para o meu equipamento.}
{123}{}{Onde posso encontrar planos de vertibird?}
{124}{}{Preciso encontrar combustível para o PMV Valdez.}
{125}{}{Eu entendo que eu preciso de um FOB para acessar o computador do Valdez.}
{126}{}{Preciso de algumas peças de computador para o PMV Valdez.}
{127}{}{Estou procurando um baço.}
{128}{}{Eu ouvi algumas máquinas voadoras trouxeram uma carga de aldeões por este caminho.}
{129}{}{Nothing. Tchau.}
{130}{}{Fale com Crocket, no campo de Hubologist. Ele é o cientista principal deles.}
{131}{}{Obrigado. Eu quero mais informações.}
{132}{}{Thanks. Tchau.}
{133}{}{Olhe para o norte, em Navarro. Há uma base escondida perto do posto de gasolina.}
{134}{}{Obrigado. Eu quero mais informações.}
{135}{}{Thanks. Tchau.}
{136}{}{Você já tentou procurar nos Vaults antigos? Eu ouvi dizer que eles são uma riqueza de informações e tecnologia dos antigos.}
{137}{}{Obrigado. Eu quero mais informações.}
{138}{}{Thanks. Tchau.}
{139}{}{Um baço? Ha ha! Sim, Chip do Valdez perdeu seu baço em um jogo de cartas no outro dia. Eu vendi para o Dr. Wong. Ele ficou fascinado por isso.}
{140}{}{Dr. Wong? Onde posso encontrá-lo?}
{141}{}{Como você perde um baço?}
{142}{}{Obrigado. Tenho mais perguntas.}
{143}{}{Ah, so. Tchau.}
{144}{}{O Dr. Wong é o principal cientista do Steel Palace. Procure-o lá.}
{145}{}{Como você perde um baço, aliás?}
{146}{}{Obrigado. Eu quero mais informações.}
{147}{}{Thanks. Tchau.}
{148}{}{Ele estava bêbado. Muito, muito bêbado. Ele estava obcecado com seu baço durante toda a noite. E então ele apostou.}
{149}{}{Então você pegou sua SPLEEN?}
{150}{}{Entendo. Bem, eu tenho mais perguntas.}
{151}{}{Sim. Era uma dívida. Ele é um homem honrado.}
{152}{}{Entendo. Preciso de mais informações.}
{153}{}{Você é um bastardo doentio e grosseiro, não é?}
{154}{}{Right. Tchau.}
{155}{}{Você é uma pessoa desonravel. Eu não vou ter você na minha loja. Volte outra vez.}
{156}{}{Tanto faz.}
{157}{}{Eles não. Eles vieram do norte e voaram sobre nós, indo para o mar.}
{158}{}{Além do horizonte? Como eu chego lá?}
{159}{}{Sim, certo, eles fizeram. Diga-me onde estão antes de abri-lo como uma lata de sardinha.}
{160}{}{Bem ... nenhum dos nossos barcos é capaz desse tipo de distância. A menos que...}
{161}{}{A menos que...?}
{162}{}{Obrigado pela ajuda". Eu vou me dar um conselho real.}
{163}{}{... a menos que você consiga o antigo petroleiro nas docas funcionando. É um navio antigo, mas provavelmente ainda funcional, se algum trabalho é colocado nisso. Peça aos punks para obter mais informações.}
{164}{}{Obrigado. Eu quero mais informações.}
{165}{}{Thanks. Tchau.}
{166}{}{A palavra diz que os Hubologists entraram em uma grande quantidade de combustível recentemente. Bargain com eles.}
{167}{}{Obrigado. Eu quero mais informações.}
{168}{}{Thanks. Tchau.}
{169}{}{Você pode tentar alguns dos cientistas Shi no Steel Palace. Talvez eles possam ajudá-lo com suas necessidades de combustível.}
{170}{}{Obrigado. Eu quero mais informações.}
{171}{}{Thanks. Tchau.}
{172}{}{Você é um inimigo do meu povo. Morrer!}
{173}{}{Você teve um bom desempenho para minha gente em matar AHS-9. Espero que eu possa ajudá-lo de alguma forma.}
{174}{}{Quem é Você?}
{175}{}{Estou procurando algum equipamento.}
{176}{}{Estou procurando por alguma informação.}
{177}{}{Tchau.}
{178}{}{Você já os deu aos Hubologists. Não?}
{179}{}{Ah, sim ... ah ... Posso perguntar outra coisa?}
{180}{}{Oh yeah...Tchau.}
