{100}{}{Você vê um guarda com roupas soltas, vestindo um olhar de tédio cauteloso.}
{101}{}{Você vê uma Guarda do Palácio.}
{102}{}{Você vê uma Guarda do Palácio.}
{103}{}{Apenas continue movendo-se e não haverá problema.}
{104}{}{Você tem negócios aqui?}
{105}{}{Estamos de olho em você.}
{106}{}{Não tente nada engraçado.}
{107}{}{Trate nossas pessoas com respeito.}
{108}{}{Não toque nisso e esse é o seu último aviso.}
{109}{}{Manter longe de lá.}
{110}{}{Volte, lao wai, ou vou preenchê-lo com tanto metal, você clank quando você andar.}
{111}{}{Afaste-se lentamente disso. Faça um movimento para suas armas e você está morto.}
{112}{}{Nem pense nisso.}
{113}{}{Pare com isso. AGORA.}
{114}{}{Morra, inimigo das pessoas!}
{115}{}{Eu estou enviando você para o inferno de metal ardente!}
{116}{}{Que o Buda tenha misericórdia de seu espírito!}
{117}{}{Sofre, inimigo!}
