{100}{}{Você vê um gangster Shi arrogante.}
{101}{}{Você vê Lo Pan, um homem dominador e implacável.}
{102}{}{Você vê um gangster Shi, vestido com roupas de seda. Suas mãos são callosas e difíceis. Ele parece perigoso e venenoso.}
{103}{}{O que você quer?}
{104}{}{Daggle aggle aggle!}
{105}{}{Quem você?}
{106}{}{Quem foi que você estava lutando?}
{107}{}{Quem é Você?}
{108}{}{Eu quero aprender a lutar como você. Ensine-me.}
{109}{}{Desejo desafiá-lo.}
{110}{}{Esqueça.}
{111}{}{Saia daqui, idiota. Não tenho nada a dizer para você.}
{112}{}{GRR!}
{113}{}{Eu sou Lo Pan. Eu sou o melhor lutador da cidade, com exceção do Dragão. E um dia, ele é um homem morto. Quando isso acontecer, vou ensinar aos outros meu estilo.}
{114}{}{Ensine-me!}
{115}{}{Tank yu.}
{116}{}{Você quer aprender? Você tem o que é preciso? Vamos ver.}
{117}{}{-feito-}
{118}{}{Te ensinam? Acho que não. Você parece muito auto-justo. Saia daqui.}
{119}{}{O que... ?}
{120}{}{Oh, olha, o idiota. Eu não quero falar com você. Vá embora.}
{121}{}{Duhhh ...}
{122}{}{Ele? O Dragão. Ele é um fraco que promove fraqueza.}
{123}{}{As pessoas são ovelhas. Você deve se servir.}
{124}{}{O que, você é mau?}
{125}{}{Entendo. Tenho mais perguntas.}
{126}{}{Mal? Dificilmente. Apenas inteligente. Talvez se você estiver tão preocupado em fazer o que é certo pelas pessoas, você deveria ver o Dragão. Ele gosta de fracos fracos como você.}
{127}{}{-feito-}
{128}{}{Sim eu deveria. E eu faço. Infelizmente, o Dragão está no caminho. Estamos muito equilibrados em nossa luta uns contra os outros. Preciso de apenas uma pessoa treinada para me ajudar.}
{129}{}{Eu sou essa pessoa.}
{130}{}{Entendo. Bem, eu tenho mais perguntas.}
{131}{}{Entendo. Bem, tanto tempo.}
{132}{}{Você está? Você pode lutar contra um homem de mãos dadas, de pé a cara, sem confiar em armaduras e armas?}
{133}{}{Posso, mas por que eu deveria?}
{134}{}{Parece justo para mim. Como funciona este teste?}
{135}{}{Oh. Bem, nesse caso, eu tenho que ir.}
{136}{}{Porque, de outra forma, os camponeses vão me amaldiçoar e isso vai tornar muito mais difícil levá-los quando eu vencer o Dragão.}
{137}{}{Consegui. Vamos começar o teste.}
{138}{}{Consegui. Tenho mais perguntas.}
{139}{}{Riiight. Até mais.}
{140}{}{Você quer me combater até a morte, ou você quer apenas ver quem está melhor?}
{141}{}{Até o final. Eu posso te levar.}
{142}{}{Um teste de habilidades. Não quero matar você.}
{143}{}{Neither. Esqueça.}
{144}{}{Ótimo. Espero que você tenha um túmulo pronto. O Dragão enviou você?}
{145}{}{Sim. Estou fazendo isso para o Shi.}
{146}{}{Não. Estou fazendo isso porque acho que você é escória.}
{147}{}{Um difícil, hein? Você vai lutar contra meus homens primeiro, e então veremos se você é digno de me combater.}
{148}{}{-início-}
{149}{}{Eu sou Lo Pan. Eu também sou o "inimigo jurado" do Dragão. Por que ele insiste em ter um inimigo jurado está além de mim. Eu apenas lutar tão bem quanto ele, e acho que ele é de coração fraco e permite que outros vivam sob suas sombras. Somos inimigos porque temos o mesmo estilo de luta, e quem ganha será aquele que carrega a tradição.}
{150}{}{Eu não estou tão mal na mão-a-mão me combate. Quer me tentar?}
{151}{}{Isso é interessante. Deve ser gratificante. Tenho mais perguntas.}
{152}{}{Obrigado. Tchau.}
{153}{}{Eu posso ser uma brincadeira, mas nunca será dito que eu não defendi meu povo. Eu vou te machucar antes de morrer.}
{154}{}{-feito-}
{155}{}{Então você é um tolo e um cachorro fazendo a licitação dos outros. Eu vou rir quando você morrer.}
{156}{}{- ataque agora, com armaduras e armas -}
{157}{}{- entrar no anel, remover armaduras e armas e lutar mão a mão -}
{158}{}{Boa. Pelo menos você é seu próprio mestre. Você é resistente o suficiente para lutar sem armas ou armaduras?}
{159}{}{- ataque agora, com armaduras e armas -}
{160}{}{- entrar no anel, remover armaduras e armas e lutar mão a mão -}
{161}{}{Baaa, ovelha, baaa! Volte para seus mestres vestidos. Não tenho nada a dizer para você.}
{162}{}{-feito-}
{163}{}{Não lhe disse para falar com o Dragão sobre suas críticas morais? Ele segurará sua mão. Eu não vou. Agora vá embora.}
{164}{}{-feito-}
{165}{}{Você deve admitir que é melhor lutador do que eu. Você quer tentar o Dragão?}
{166}{}{Sim. Eu vou fazer isso agora.}
{167}{}{Na verdade não é minha luta.}
{168}{}{Claro, mas tenho algumas perguntas.}
{169}{}{Não, não é. Mas o Dragão ainda me bate. Se você tem uma espinha dorsal, você vai tirá-lo. Mas então, nunca esperava o orgulho de um lao wai.}
{170}{}{Certo. Eu tenho dúvidas.}
{171}{}{Tanto faz. Tchau.}
{172}{}{Acabei de voltar de matar um lao wai que tentou roubar nossos segredos. O Dragão e eu o levamos para fora. Trabalhamos bem juntos, devo admitir.}
{173}{}{Ótimo. Eu tenho dúvidas.}
{174}{}{Ótimo. Tchau.}
{175}{}{O Dragão está morto. Eu não acredito nisso. Pelo menos agora, não teremos essas tradições trapezinhas perseguindo todos os nossos passos. Obrigado.}
{176}{}{Ótimo. Eu tenho dúvidas.}
{177}{}{Ótimo. Tchau.}

{200}{}{Lo Pan detecta seu avanço e você desliza por ele.}
{201}{}{Olha, não aprecio que ninguém tome minhas coisas, então vá roubar outras. Saia agora.}
{202}{}{Eu lhe avisei para sair, para não morrer. Ah bem.}
{203}{}{Você já tomou a prova do Dragão!}

{204}{}{Acabei de treinar hoje. Volte para o amanhã.}

{205}{}{Eu sou Master Khung, seu teste final.}
{206}{}{Eu sou Imbot. Esteja pronto.}
{207}{}{Eu sou o Wejungh. Se prepare.}
{208}{}{Eu sou Loopal. Você não terá mais nada.}
{209}{}{Eu sou Smitty. É seu tempo para ser espancado.}
{210}{}{Eu sou o mestre Krall. Você terminou.}
{211}{}{LUTA!}
{212}{}{Você precisa treinar mais.}
{213}{}{Se prepare!}
{214}{}{Você bateu Lo Pan no combate mortal. Por algum motivo, o sol parece um pouco mais brilhante hoje.}
{215}{}{Você já derrotou meus homens. Você passou meu teste. Você está pronto para lutar contra o Dragão.}
{216}{}{Você já está bem. Vá aprender a disparar ou algo assim.}

#training messages
{217}{}{Comecemos. Siga o meu comando.}
{218}{}{O treinamento é feito para o dia.}
{219}{}{Você aprendeu bem.}

{220}{}{Você já derrotou meus homens. Nenhum outro deseja desafiar você.}

{221}{}{Você me ajudou e nem sabia disso. Com o Dragão morto, eu não tenho que seguir essas tradições morais desatualizadas.}
{222}{}{Foi um prazer. Tchau.}
{223}{}{Seja bem-vindo. Tchau tchau.}
{224}{}{Seja bem-vindo. Posso fazer uma pergunta?}
{225}{}{Bem vinda. Eu pergunto?}

{226}{}{Você ganha!}
{227}{}{Você perdeu!}
{228}{}{Próximo oponente!}

{229}{}{Ei, olhe o que encontrei.}

{230}{}{Primeiro, você precisará provar que você pode fazê-lo. Eu vou ter que enfrentar cinco dos meus lutadores - um de cada vez. Se você vencê-los, então você receberá seu teste final.}
{231}{}{O que é isso?}
{232}{}{Parece demais. Tchau.}
{233}{}{Você precisará me vencer. No entanto, nenhuma dessas batalhas será para a morte - para proteger meus homens, é claro. [Ele zombou]}
{234}{}{Vamos obtê-lo em!}
{235}{}{Você pode cuidar do Dragão você mesmo.}
{236}{}{[Lo Pan estuda você e, em seguida, lança um soco rápido que cheira no nariz antes que você possa reagir.] Você não é bom o suficiente.}
{237}{}{Ok, mas posso perguntar algo mais?}
{238}{}{Bem. Tchau.}
