{100}{}{Você vê um punk amigável.}
{101}{}{Você vê Marc.}
{102}{}{Você vê um punk amigável.}
{103}{}{Você filho da puta - como você pode nos fazer isso?}
{104}{}{O que posso fazer por você, mama-jamma?}
{105}{}{Para que posso te fazer, mama-jamma?}
{106}{}{Ooh! Ooh! Aah!}
{107}{}{Quem é Você?}
{108}{}{O que é este lugar?}
{109}{}{Quem está no comando?}
{110}{}{Nada. Tchau.}
{111}{}{Hmm. Não, desculpe, não posso ajudá-lo com isso. Talvez você devesse tentar outra pessoa.}
{112}{}{Anks?}
{113}{}{Eu sou Marc. Sou o residente inteligente e sei-tudo. ::ele sorri::}
{114}{}{Oh. Eu tenho outras perguntas.}
{115}{}{Tchau.}
{116}{}{Este é o Poseidon Marine Vessel Valdez - também chamado PMV Valdez. Se você quer mais informações sobre o Valdez, a melhor pessoa a perguntar é o Capitão.}
{117}{}{O capitão? Quem é aquele?}
{118}{}{Eu tenho outras perguntas.}
{119}{}{Tchau.}
{120}{}{No comando? Ninguém está a cargo de nós.}
{121}{}{De onde você veio?}
{122}{}{Eu tenho outras perguntas para lhe perguntar, então.}
{123}{}{Tchau.}
{124}{}{O capitão é um homem militar resistente. Ele senta lá em cima e verifica o lugar. Ele tem algum conhecimento profundo sobre este navio.}
{125}{}{Obrigado. Tenho mais perguntas.}
{126}{}{Thanks. Tchau.}
{127}{}{Oh, em todo o deserto. Nós ouvimos coisas sobre São Francisco, transmitidas de nossos anciãos. Alguns de nós têm antepassados   que moravam aqui antes da grande guerra. Você quer ouvir mais?}
{128}{}{Sim.}
{129}{}{Não, mas queria perguntar-lhe outra coisa.}
{130}{}{Não, isso é tudo.}
{131}{}{Somos uma banda de músicos, tekheads, geeks e artistas. Pensávamos que voltaríamos para algum lugar famoso pela liberdade artística e pessoal. Eu vim aqui para gerar. Quer ouvir mais ainda?}
{132}{}{Sim.}
{133}{}{Não, mas queria perguntar-lhe outra coisa.}
{134}{}{Não, isso é tudo.}
{135}{}{Bem, quando chegamos aqui, descobrimos que acamparíamos aqui até descobrirmos como conseguir que este caminhão fosse novamente ou até que pensássemos em outra coisa.}
{136}{}{Você descobriu como mover o petroleiro?}
{137}{}{Conte-me sobre os Hubologists.}
{138}{}{Conte-me sobre o Shi.}
{139}{}{Eu tenho outras perguntas.}
{140}{}{Thanks. Tchau.}
{141}{}{Acho que o capitão descobriu como fazê-lo - mas precisamos de vários elementos primeiro. Nós basicamente desistiram de assumi-lo por nós mesmos, para dizer a verdade - nós temos outros planos agora.}
{142}{}{O que eles são?}
{143}{}{Onde posso encontrar o Capitão?}
{144}{}{Eu queria perguntar outra coisa.}
{145}{}{Tchau.}
{146}{}{Eles são loucos. Não confie neles - a menos que você seja mentalmente fraco ou como ser ferrado. Eles estão interessados   apenas em seu dinheiro e sua alma, e há uma boa chance de destruí-lo para chegar no outro. Eu vi isso acontecer muitas vezes.}
{147}{}{Você descobriu para mover o petroleiro?}
{148}{}{Conte-me sobre o Shi.}
{149}{}{Eu tenho outras perguntas.}
{150}{}{Tchau.}
{151}{}{Eles são um bom tipo, tanto quanto eles vão. Eles são um pouco desconfiados de pessoas de fora, mas então, nem sempre é uma atitude tão ruim para assumir nestes tempos. Eles têm alguns costumes estranhos e eles falam engraçado, mas eles estão bem.}
{152}{}{Você descobriu para mover o petroleiro?}
{153}{}{Conte-me sobre os Hubologists.}
{154}{}{Eu tenho outras perguntas.}
{155}{}{Tchau.}
{156}{}{Você quer saber quais são nossos planos? Nós vamos continuar caminhando até encontrar um lugar que não tenha sido ferrado pela ganância humana e então vamos tentar criar uma sociedade melhor.}
{157}{}{Você sabe como vai fazer isso?}
{158}{}{Eu tenho outras perguntas.}
{159}{}{Thanks. Tchau.}
{160}{}{Esperamos que se possamos evitar os erros da sociedade. Inferno, as coisas não podem ficar muito piores.}
{161}{}{Você descobriu para mover o petroleiro?}
{162}{}{Conte-me sobre os Hubologists.}
{163}{}{Conte-me sobre o Shi.}
{164}{}{Eu tenho outras perguntas.}
{165}{}{Thanks. Tchau.}

{166}{}{Você viu a namorada de Badger ao redor?}
{167}{}{Acho que a vi ir abaixo. Há um buraco no lado norte deste deck.}
