{100}{}{Você vê um vagão-tanque masculino.}
{101}{}{Você vê um punk masculino.}
{102}{}{Você vê um homem bastante bonito e cínico com roupas esfarrapadas.}
{103}{}{Nada está acontecendo.}
{104}{}{Estou cansada de peixe.}
{105}{}{Quanto mais cedo nós avançarmos, melhor.}
{106}{}{A melhor coisa sobre ser um nômade é o autocontrole.}
{107}{}{Na verdade, prefiro morrer do que te dar controle.}
{108}{}{Ninguém corre minha vida! Eu sou o rei de mim!}
{109}{}{Eu sou meu próprio chefe.}
{110}{}{Eu sou único! Assim como todos os outros!}
{111}{}{Às vezes, o cinismo cansado do mundo me aborrece.}
{112}{}{Na próxima vez, quero encontrar uma tribo de góticos.}
{113}{}{Vi Selmy e Barro derrubados lá embaixo.}
{114}{}{Eu ouço o Imperador Shi é desumanamente inteligente.}
{115}{}{Estes Shi com certeza parecem engraçados.}
{116}{}{Tenho a mente aberta, hein?}
{117}{}{Eu compartilharei minha namorada se você compartilhar a sua.}
{118}{}{Olhe para todos esses novos punks. Posers.}
{119}{}{AHS-9 nos enganou e ele também o enganará se você o deixar.}
{120}{}{Ovelha. Você não é nada além de uma ovelha matadora.}
{121}{}{Diga a esses bastardos Hubologists que nunca vamos encontrar.}
{122}{}{Nunca está indo ao Hub.}
{123}{}{Espero que você esteja orgulhoso de si mesmo.}
{124}{}{Será que eles nunca perceberão que matar nosso "líder" não nos fará seguir o deles?}
{125}{}{Você é um idiota.}
{126}{}{Baah! Baah!}
{127}{}{Então, como foi, levando-o de um mutante?}
{128}{}{Esse grande mutie forte Francis te machucou?}
{129}{}{Francisco brinca com você?}
{130}{}{Francis é um cara muito grande.}
{131}{}{Olá grande, hein?}
{132}{}{}
{133}{}{Ei! É o gimp!}
{134}{}{Ei, se você precisar de alguma ajuda de nós, não se preocupe em perguntar.}
{135}{}{Uau! Um idiota falante!}
{136}{}{Você puxa qualquer coisa como um idiota?}
{137}{}{Sacrifique nossa Chippie, você vai?}
{138}{}{Poor Chip.}
{139}{}{Oh, olha, é o "herói".}
{140}{}{Ei, todos! É o idiota egoísta!}
{141}{}{Como se alguém quiser conversar com você agora.}
{142}{}{Chip-Hater!}
{143}{}{Posso fazer qualquer coisa por você? Que pena!}
{144}{}{Não fale comigo.}
{145}{}{Muito bom para você tentar o baço de Chip.}
{146}{}{Pelo menos tentaste.}
{147}{}{Poor Chip.}
{148}{}{Ruptura difícil para ol 'Chippie.}
{149}{}{Chip está ficando mais fraco. Que pena.}
{150}{}{Bom com o baço!}
{151}{}{Uau ... um herói e um buscador de baço.}
{152}{}{Não sabia que eles faziam baços.}
{153}{}{Obrigado por salvar Chip.}
{154}{}{Ei, Chip lover!}
{155}{}{Estamos todos felizes com Chip.}
{156}{}{Obrigado por salvar Chip.}
{157}{}{Agora, Badger será mais fácil de viver.}
{158}{}{Eu sempre gostava de Suze. Feliz que ela não esteja morta.}
{159}{}{Pergunto-me se Suze vai babá para meus filhos?}
{160}{}{Mate os monstros, salve a namorada ... Existe alguma merda de herói que você não faz?}
{161}{}{Você pode salvar minha namorada também? Ha ha!}
{162}{}{Talvez o texugo durma com você por salvar sua namorada.}
{163}{}{Aposto que Badger está realmente feliz agora.}
{164}{}{Talvez você deva pedir a Badger alguns favores.}
{165}{}{Pobre texugo. Poze Suze.}
{166}{}{Eu avisei que não fosse lá ...}
{167}{}{... Damn Hold-Monsters ...}
{168}{}{Sinto muito por Badger agora.}
{169}{}{Morte no navio. Poze Suze.}
{170}{}{Homem ... a vida vai melhorar?}
{171}{}{É perigoso lá embaixo!}
{172}{}{Geez ... por que ela ia lá?}
{173}{}{Devemos selar o porão.}
{174}{}{Vamos sair do navio.}
{175}{}{Você vai pegar o petroleiro para o oeste?}
{176}{}{Adivinha que está prestes a abandonar o navio.}
{177}{}{Estou pronto para sair daqui.}
{178}{}{Eu consegui minha merda toda empacotada.}
{179}{}{Não pense que eu quero ir para o oeste.}
{180}{}{}
{181}{}{}
{182}{}{}
{183}{}{Conheça bons lugares para se estabelecer?}
{184}{}{Certifiquei-me de que o lugar esteja limpo antes de ir.}
{185}{}{Vamos começar o show na estrada!}
{186}{}{Geez ... não mais Badger.}
{187}{}{Quem o teria matado?}
{188}{}{Não sei cagar sobre computadores. Você?}
{189}{}{Homem ... Badger conhecia todos os lugares legais para ir.}
{190}{}{Agora nunca vou ouvir sua banda tocar!}
{191}{}{Assassinos estúpidos ... se livrando de Badger ... estúpido.}
{192}{}{Estou tão cheio de ódio agora.}
{193}{}{Eu quero vingança para Badger!}
{194}{}{A vida parece tão inútil sem Badger.}
