{100}{}{Você vê um comerciante.}
{101}{}{Você vê um comerciante.}
{102}{}{Você vê um comerciante animado de Shi. Como todos os outros, ele parece estar cheio de vento.}
{103}{}{Venha comprar o polvo! Muito saboroso!}
{104}{}{Você gosta de peixe? Nós conseguimos peixe!}
{105}{}{Ei! Ei! Compre isso! Compre isso!}
{106}{}{Não compre com ele! Ele é um ladrão péssimo!}
{107}{}{Venha aqui e veja isso! Você gosta muito disso!}
{108}{}{Confira! Confira! Confira!}
{109}{}{Ei, lao wai! Você quer um acordo? Eu tenho ofertas!}
{110}{}{Venha antes! Venha antes! Venha antes!}
{111}{}{Você acha que é bom? Veja isso!}
{112}{}{Nós conseguimos peixe, pegamos algas, pegamos arroz, nós conseguimos ... umm ...}
{113}{}{Não há muito que cresça aqui, mas o que é que nós conseguimos em estoque!}
{114}{}{Você vai para casa! Você vai para casa, lao wai!}
{115}{}{Nós não queremos o seu negócio!}
{116}{}{Sair! Sair!}
{117}{}{Seu dinheiro não é bom aqui! Você vai agora!}
{118}{}{Você vai agora!}
{119}{}{Você não gosta de lutar? Mai Da Chiang tem armas para você!}
{120}{}{Você é um amante e não um lutador, hein?}
{121}{}{Ei, gafanhoto!}
{122}{}{Venha comprar o polvo! Muito saboroso!}
{123}{}{Você gosta de peixe? Nós conseguimos peixe!}
{124}{}{Ei! Ei! Compre isso! Compre isso!}
{125}{}{Não compre com ele! Ele é um ladrão péssimo!}
{126}{}{Venha aqui e veja isso! Você gosta muito disso!}
{127}{}{Confira! Confira! Confira!}
{128}{}{Hey lao wai! Você quer um acordo? Eu tenho ofertas!}
{129}{}{Venha antes! Venha antes! Venha antes!}
{130}{}{Você acha que é bom? Veja isso!}
{131}{}{Nós conseguimos peixe, pegamos algas, pegamos arroz, nós conseguimos ... umm ...}
{132}{}{Não há muito que cresça aqui, mas o que é que nós conseguimos em estoque!}
{133}{}{Nós conseguimos uma venda de conselheiro morto!}
{134}{}{Homem ... o novo líder nos dará novos impostos?}
{135}{}{Pobre Ken Lee.}
{136}{}{Shi-Town nunca mais será o mesmo sem o velho Ken Lee.}
{137}{}{Você gosta de peixe? Nós conseguimos peixe!}
{138}{}{Ei! Ei! Compre isso! Compre isso!}
{139}{}{Não compre com ele! Ele é um ladrão péssimo!}
{140}{}{Venha aqui e veja isso! Você gosta muito disso!}
{141}{}{Confira! Confira! Confira!}
{142}{}{Hey lao wai! Você quer um acordo? Eu tenho ofertas!}
{143}{}{Venha antes! Venha antes! Venha antes!}
{144}{}{Você acha que é bom? Veja isso!}
{145}{}{Nós conseguimos peixe, pegamos algas, pegamos arroz, nós conseguimos ... umm ...}
{146}{}{Não há muito que cresça aqui, mas o que é que nós conseguimos em estoque!}
