{100}{}{Você vê um homem bem vestido.}
{101}{}{Você vê AHS-9, o Grande e Terrível.}
{102}{}{Você vê um homem bem vestido.}
{103}{}{Você blasfema do nome do Hub! Você deve morrer!}
{104}{}{Sua perfídia não conhece limites!}
{105}{}{A Grande Roda vai acabar com você!}
{106}{}{Você está na presença de AHS-9, o Grande e Terrível. O que você deseja dele?}
{107}{}{Agh a nu, AHS!}
{108}{}{Estou procurando meu povo. Ouvi dizer que eles derrubaram-se por aí em navios voadores.}
{109}{}{Tenho muitas perguntas para você, AHS-9.}
{110}{}{O Iluminado da NCR queria que eu entregue uma carta. Ela disse algo sobre uma recompensa?}
{111}{}{O Iluminado da NCR queria que eu entregue uma carta. Aqui está.}
{112}{}{Oh, AHS-9, venho trazendo uma carta do seu agente na NCR. Eu me inclino para a sua glória.}
{113}{}{Sua morte. Adeus, velho.}
{114}{}{Nada, desculpa.}
{115}{}{Sim, meu filho?}
{116}{}{Hinchoaf? [Você pode me entender?]}
{117}{}{Aagga diggle doodle doo! [Oh, graças a Deus. Estou procurando meu povo. Preciso superar a grande água.]}
{118}{}{Calças cagadas! [Bem, obrigado pelo seu tempo. Eu tenho que estar correndo agora. Um prazer em falar com você.]}
{119}{}{Não consigo entender uma palavra que você está dizendo. Talvez você veja Juan ou Vikki sobre um alinhamento.}
{120}{}{Anks!}
{121}{}{Claro, criança. O alinhamento limpou seus neurodynes básicos e alinhou-os com os meus e os raios da Grande Roda. O que você precisa?}
{122}{}{Aagga diggle doodle doo! [Oh, graças a Deus. Estou procurando meu povo. Preciso superar a grande água.]}
{123}{}{B-b-b-enny [Nada, obrigado. É ótima poder conversar com você. Tchau!]}
{124}{}{Se você concordar em me fazer um favor, posso ajudá-lo, criança.}
{125}{}{Oik? [O que é isso? Eu ficaria feliz em ser de ajuda.]}
{126}{}{Não!}
{127}{}{O meu homólogo, o Imperador da cidade de Shi, tem me deixado miserável. Eu gostaria que você terminasse o dele. Em troca, eu me certificarei de que você pode chegar onde você precisa estar.}
{128}{}{Ays! [Eu vou fazer isso.]}
{129}{}{Não!}
{130}{}{Se você mudar de opinião, avise-me. Lembre-se, eu posso ser a única maneira de alcançar sua família.}
{131}{}{Está bem. [O que é esse favor?]}
{132}{}{Didgeroo! [Obrigado, eu não preferiria nada a ninguém. Tanto tempo!]}
{133}{}{Boa. Deixe-me saber quando terminar, e vou começar a fazer perguntas sobre maneiras de alcançar seu objetivo ao mesmo tempo. Despedida, criança.}
{134}{}{Adeus! [Por enquanto, AHS-9. Você é um grande homem.]}
{135}{}{Você completou sua tarefa? Seu futuro e o da Roda neste planeta dependem disso.}
{136}{}{Unh-uh [Ainda não. Eu só queria dizer oi.]}
{137}{}{Eu estou trabalhando nisso. Eu tenho algumas questões.}
{138}{}{Ainda não. Eu voltarei para você.}
{139}{}{Saudações para você também. Agora, termine seu trabalho para que eu possa ajudá-lo.}
{140}{}{Ng! Ng! [Sim senhor!]}
{141}{}{Posso ver pelas suas emanações que você conseguiu livrar o mundo dos neurônios poluentes do Imperador.}
{142}{}{Jirsa! [Sim, eu tenho. Como é que sua parte da negociação está chegando?]}
{143}{}{Sim, eu tenho. Agora eu preciso de sua ajuda para ajudar meu povo.}
{144}{}{Se você for às docas da cidade de Shi, você encontrará o PMV Valdez. Entre no navio. Dirija à sua direita e até a estação do capitão. Pressione o botão Ir e o petroleiro irá navegar para o seu destino.}
{145}{}{Anks! [Foi um prazer, AHS-9. Desejo a todos o melhor. Adeus.]}
{146}{}{Navios voadores? Você deve estar se referindo ao Enclave e seus vertibirds.}
{147}{}{Sim, eu acho que sim.}
{148}{}{Enclave? Enclave quem?}
{149}{}{Confie em mim, criança, você está se referindo ao Enclave.}
{150}{}{Sim, tudo bem. Como faço para encontrá-los?}
{151}{}{O Enclave é um remanescente do passado - um neurodyne que ainda não está alinhado. Eles escondem bases em todos os fragmentos da velha Califórnia, e sua fortaleza mais forte é para o oeste, sobre as águas.}
{152}{}{Como eu chego lá?}
{153}{}{Como você sabe tudo isso?}
{154}{}{Isso, meu filho, você terá que descobrir por sua conta. Pergunte ao redor e você encontrará a verdade.}
{155}{}{Muito útil. Eu tenho mais perguntas.}
{156}{}{Como você sabe tudo isso?}
{157}{}{Tanto faz. Tchau.}
{158}{}{Criança, eu sou AHS-9. Eu vejo muitas coisas que ocorrem no mundo carnudo. Você tem mais perguntas ou posso voltar às minhas meditações?}
{159}{}{Mais perguntas.}
{160}{}{Retorne às suas meditações. Terminei.}
{161}{}{Você matou o Imperador e destruiu seus minions?}
{162}{}{Sim, eu tenho.}
{163}{}{Então, não há ninguém que possa estar no meu caminho! Mas não vejo necessidade de ser obrigado a uma mera ferramenta. Adeus - e bom arrumoso!}
{164}{}{Por que, você se arruina. Eu vou matar você agora.}
{165}{}{Oh. Bem, se é assim que deve ser. Tanto tempo.}
{166}{}{Uma carta do Iluminado? É isso que ela se chama agora? Bah. [Ele tira a carta de você] E ela prometeu uma recompensa? Você tem uma recompensa - minha gratidão. Dia bom.}
{167}{}{É isso aí? Velho, você está morto.}
{168}{}{Err, eu tive algumas perguntas.}
{169}{}{Gee, ótimo. Tchau.}
{170}{}{Dirija suas perguntas à AHS-7. Eu sou AHS-9, o Grande e Terrível, e eu tenho muitos assuntos em minha mente. Não me incomode, carne.}
{171}{}{Se você não responder às minhas perguntas, você responderá às minhas armas.}
{172}{}{Tanto faz.}
{173}{}{Ahh, uma carta do meu agente de campo. Pese a que ela se chama "A Iluminada" - mostra que ela realmente não está esclarecida. Você tem minha gratidão.}
{174}{}{Sem problemas. Eu tenho uma ou duas perguntas, no entanto.}
{175}{}{Ótimo. Tchau.}
{176}{}{Sim, meu filho?}
{177}{}{Quando a nave espacial decola?}
{178}{}{Você tem alguma tarefa para mim?}
{179}{}{Onde é que todo o dinheiro que fornecemos vai?}
{180}{}{Oh nada. Esqueça.}
{181}{}{O meu homólogo, o Imperador da cidade de Shi, tem me deixado miserável. Eu gostaria que você terminasse o dele. Em troca, eu me certificarei de que você pode chegar onde você precisa estar.}
{182}{}{Claro, chefe. Até mais.}
{183}{}{Eu prefiro que nao.}
{184}{}{Procure o texugo, cuja presença cáustica mantém esses patéticos vagabundos-tanque juntos. Arrumou nossa cidade justa dele. Quando você tiver feito isso, visite AHS-7.}
{185}{}{Claro, chefe. Até mais.}
{186}{}{Eu prefiro que nao.}
{187}{}{Não sabia que fizesse um pedido, filho. Mate ele!}
{188}{}{Não.}
{189}{}{Oh tudo bem. Eu vou fazer isso.}
{190}{}{Você desobedece aos comandos da AHS-9, o Grande e o Terrível? Então você morrerá.}
{191}{}{Pode vir.}
{192}{}{Aguarde, eu mudei de idéia.}
{193}{}{Muito tarde, carne. Você mostrou que não pode ser confiável. Morrer!}
{194}{}{-feito-}
{195}{}{Criança, há algumas coisas que você não deve saber por enquanto. [Ele sorri benignamente.]}
{196}{}{Tudo certo. Eu tenho mais perguntas.}
{197}{}{Hm. Tchau.}
{198}{}{O ESS Quetzel será lançado quando as estrelas estiverem corretas.}
{199}{}{Direito-o. Eu tenho mais perguntas.}
{200}{}{Obrigado. Tchau.}
{201}{}{A sua aura enrugada me diz que você vem aqui, o que significa que eu não é bom. Diga-me, criança, você deseja aproveitar seu empreendimento?}
{202}{}{Sim.}
{203}{}{Não.}
{204}{}{Não, eu só quero que você morra.}
{205}{}{Isto, então, é minha pechincha: volte ao Shi e elimine Ken Lee e o Imperador. Eu vou pagar com mais dinheiro do que você já sonhou.}
{206}{}{Não, eu não penso assim.}
{207}{}{Você tem um acordo, homem gordo.}
{208}{}{Então, vá e mata aquelas almas problemáticas. Aguardo a palavra do seu sucesso. [Ele sorri beatificamente.]}
{209}{}{Tanto tempo.}
{210}{}{Não, espere, eu mudei de idéia. Eu quero você morto.}
{211}{}{Ah, criança, como você pode se afastar do caminho da verdade assim? Vejo da sua aura que você planeja me matar. Estou amargamente decepcionado. Amargamente. Ah bem. Vamos prosseguir.}
{212}{}{Sim, vamos. Morrer.}
{213}{}{Lembre-se, você precisará visitar o AHS-7 quando tiver concluído sua tarefa.}
{214}{}{Todas as nossas necessidades foram atendidas. Agora é hora de eu meditar.}
