{100}{}{Você vê um Hubologist coberto. De alguma forma, isso parece diferente.}
{101}{}{Você vê AHS-7, o segundo no comando.}
{102}{}{Você vê um Hubologist coberto.}
{103}{}{Guardas! Um opressivo! Derrube-o!}
{104}{}{Você. Indique seu negócio.}
{105}{}{Aaagh! Nu! Nee!}
{106}{}{Eu tenho uma carta para AHS-9 do Iluminado na NCR.}
{107}{}{Estou aqui para falar com Crocket sobre alguma armadura.}
{108}{}{Eu gostaria de olhar ao redor.}
{109}{}{Estou interessado em participar potencialmente do seu grupo.}
{110}{}{Quem é Você?}
{111}{}{Eu vim para matar todos vocês.}
{112}{}{Ah, pobre criança. Gostaria de estar alinhado?}
{113}{}{'Es!}
{114}{}{Não!}
{115}{}{Filho pobre. Já alinhados, mas incapazes de articular. Continue.}
{116}{}{'Ank yu!}
{117}{}{Entre e encontre Juan e Vikki. Eles podem ajudá-lo. Boa sorte, criança.}
{118}{}{'Ank yu!}
{119}{}{:: sua voz endurece :: Então não vejo nenhuma razão para você ser admitido aqui. Dia bom.}
{120}{}{'Ey!}
{121}{}{Muito bem. Seja rápido, porém - ele é um homem ocupado e ocupado.}
{122}{}{OK.}
{123}{}{Este não é um lugar aberto para passeios aleatórios. Dia bom.}
{124}{}{-feito-}
{125}{}{Excelente! Entre, entre. Fale com Juan Cruz e Vikki Goldman - são celebridades, você sabe, mas eles vão falar com você.}
{126}{}{Quem são eles?}
{127}{}{Ooh! Celebridades!}
{128}{}{Eu sou AHS-7, o segundo ao comando desta facilidade. Antes de perguntar: AHS significa Aligned Hub Seeker, o que significa que eu limpei sete níveis de neurodynes do meu espírito. Isso significa que estou mais iluminado e mais perto do centro da Grande Roda do que você. E isso significa que você vai me dizer o que você quer aqui. Agora.}
{129}{}{Eu tenho uma carta para AHS-9 do Iluminado na NCR.}
{130}{}{Estou aqui para falar com Crocket sobre alguma armadura.}
{131}{}{Eu gostaria de olhar ao redor.}
{132}{}{Estou interessado em participar potencialmente do seu grupo.}
{133}{}{Eu vim para matar todos vocês.}
{134}{}{São estrelas de New Reno. Eles ouviram a verdade por trás do nosso evangelho e vieram limpar seus neurodynes.}
{135}{}{Onde eu os encontro?}
{136}{}{Bem, esqueça. Estou fora daqui.}
{137}{}{Você pode encontrá-los na sala de oração, mostrando todos os nossos novos recrutas e a carne crua, o quão gratificante é ser um Hubologist.}
{138}{}{Bem, deixe-me com eles!}
{139}{}{Eu serei o juiz disso. Vamos começar o show na estrada.}
{140}{}{Esqueça. Estou fora daqui.}
{141}{}{Então agora você falou com Juan e Vikki. Você está interessado em se juntar aos nossos amigos na busca da iluminação para a Grande Roda?}
{142}{}{Ai sim. Sim Sim Sim.}
{143}{}{Certo.}
{144}{}{Não agora. Posso voltar para você?}
{145}{}{Eu não acho que seja minha bolsa. Desculpa.}
{146}{}{De jeito nenhum. Seu culto louco merece ser incendiado até o chão.}
{147}{}{:: ele sorri :: você não vai se arrepender disso. Você pode ter o funcionamento do composto. Oh ... você é uma pessoa que sabe como usar uma arma. Você gostaria de usar o seu no serviço da Grande Roda?}
{148}{}{Sim.}
{149}{}{Talvez mais tarde.}
{150}{}{Não espere muito antes de retornar com uma resposta. Seus neurodynes serão preenchidos com mais e mais poluição até que possamos começar o processo de limpeza.}
{151}{}{Eu mudei de ideia. Eu vou me juntar.}
{152}{}{Você entendeu. Falo com você mais tarde.}
{153}{}{Você pode deixar este composto com segurança, viajante, mas eu recomendaria não retornar. Se você não viajar conosco, então você trabalha contra nós - e eu odiaria vê-lo doer.}
{154}{}{Obrigado pela preocupação. Até logo.}
{155}{}{Eu não acho que eu fiquei doido. Tanto tempo.}
{156}{}{Nos toca? TORCH US? GUARDAS! MATAR O UNBELIEVER!}
{157}{}{-feito-}
{158}{}{Assim. Você já teve tempo para reconsiderar sua decisão. Você vai se juntar a nós?}
{159}{}{Sim.}
{160}{}{Não.}
{161}{}{Ainda preciso de mais tempo.}
{162}{}{Você não tem mais tempo. Faça sua escolha, carne.}
{163}{}{Tudo bem, vou me juntar.}
{164}{}{Esqueça. Não gosto de táticas de braço forte.}
{165}{}{O Shi opressivo vem contestando nosso poder e causando estragos entre os nossos irmãos com seus modos de influenciar o neuroentismo. Acreditamos que, se seu Imperador for morto, eles verão o erro de seus caminhos. Você matará o Imperador?}
{166}{}{Sim, vou fazer isso.}
{167}{}{Não, o Shi nunca me fez nada.}
{168}{}{Talvez você reconsidere. Deixe-me saber se você faz. Agora, existe alguma coisa que o Hub possa providenciar para você, recrutar?}
{169}{}{Sim, tenho algumas perguntas.}
{170}{}{Não, agora mesmo, obrigado.}
{171}{}{Você pensou em nos ajudar na nossa luta contra o Shi opresivo? O Pai das Estrelas o abençoará se você participar da nossa cruzada.}
{172}{}{Ainda não tenho certeza de que quero fazê-lo.}
{173}{}{Eu vou fazer isso.}
{174}{}{Talvez eu possa aliviar sua alma incomodada. O que você precisa?}
{175}{}{Onde posso obter combustível para o petroleiro Poseidon?}
{176}{}{Onde posso encontrar o significado de todos os termos que você usa?}
{177}{}{Quando o navio decola?}
{178}{}{Onde está Crocket?}
{179}{}{Nada, obrigado. Tchau.}
{180}{}{Deixe-nos saber quando você completou sua tarefa.}
{181}{}{Vai fazer. Eu tenho mais perguntas.}
{182}{}{Coisa certa. Tchau.}
{183}{}{Você removeu a mancha opressiva do Imperador dessa existência material?}
{184}{}{Ainda não.}
{185}{}{Sim, AHS-7. Ele está morto.}
{186}{}{O líder de fato dos vagabundos Tanker é um pedaço de carne crua anti-terapêutica chamada Badger. Com sua morte, eles entenderão nossa posição. Você o removerá?}
{187}{}{Eu vou fazer isso.}
{188}{}{Ele não me causou nenhum dano. Eu prefiro que nao.}
{189}{}{Então ... você reconsiderou se você removeria esse "texugo"?}
{190}{}{Eu vou fazer isso.}
{191}{}{Eu ainda preferiria não.}
{192}{}{Você removeu este "texugo"?}
{193}{}{Ainda não.}
{194}{}{Sim. He's gone.}
{195}{}{Seu povo deve abraçar o Hub! Tudo ficará bem! Você realizou um ótimo serviço!}
{196}{}{Obrigado! Eu tenho mais perguntas.}
{197}{}{Eu faço tudo para a Roda. Despedida.}
{198}{}{Na verdade, agora vou matar você também.}
{199}{}{Agora que o navio está cheio de combustível, aguardamos apenas a palavra AHS-9, o Grande e Terrível, para conseguir o desapego.}
{200}{}{Claro que sim. Eu tenho algumas questões.}
{201}{}{Obrigado. Tchau.}
{202}{}{Além do precioso combustível, precisamos nos lançar no peito de nossos irmãos estrelados no planeta Quetzel, não consigo pensar em um lugar. Talvez o Shi?}
{203}{}{Hã. Eu tenho mais perguntas.}
{204}{}{Sim talvez.}
{205}{}{Eu entendo que o Shi tem um enorme tanque de combustível. Talvez você possa roubá-lo deles.}
{206}{}{Essa é uma idéia. Eu tenho mais perguntas.}
{207}{}{Talvez. Obrigado.}
{208}{}{Basta usar o holodisc Juan e Vikki fornecidos para você e verificar o Glossário.}
{209}{}{Obrigado. Mais perguntas?}
{210}{}{Obrigado.}
{211}{}{Quando AHS-9 recebe sua visão do Hub, vamos sair e juntar-se a ele em glória celestial!}
{212}{}{Sim, elogie a Roda ou seja o que for. Eu tenho mais perguntas.}
{213}{}{Most informative. Obrigado.}
{214}{}{Ele geralmente está no laboratório, trabalhando em maneiras de aperfeiçoar nossos corpos e nossos espíritos.}
{215}{}{Obrigado. I wanted to ask something else.}
{216}{}{Obrigado.}
{217}{}{Antes de poder realmente ser um de nós, devemos realizar uma varredura zeta inicial - um alinhamento. Você está preparado para sua digitalização?}
{218}{}{Não! No scan!}
{219}{}{Certo. Let's do it.}
{220}{}{Sem uma varredura, você não pode se juntar a nós. Tem certeza de que deseja recusar?}
{221}{}{Certeza absoluta. Eu não quero ser monkeyed com as suas máquinas.}
{222}{}{Oh tudo bem. Verifique-me.}
{223}{}{Nós eliminamos alguns de seus neurônios mais sujos. Agora você é avaliado como AHS-1. Você está pronto para se juntar a nossa causa nobre?}
{224}{}{Ai sim.}
{225}{}{Não. Não quero agora.}

{226}{}{Lição 1: Aqui temos a eternidade. Aqui é onde está Quetzel. [aponta para algo] E aqui é onde estamos. [aponta para algo] Agora, tudo o que temos a fazer é andar muito longe para chegar lá.}
{227}{}{Cara, vamos precisar de muitos sapatos.}

{228}{}{Ainda posso pensar sobre isso?}
{229}{}{Você novamente? O que?}
{230}{}{Existe mais alguma coisa que você precisa que eu faça?}
{231}{}{Você não é procurado aqui. Saia agora.}
