{100}{}{Você vê alguém usando o chapéu de um capitão.}
{101}{}{Você vê o Capitão A. Ron Meyers}
{102}{}{Você vê um punk com roupas esfarrapadas vestindo o chapéu de um capitão.}
{103}{}{O que diabos você quer? Não falo com ninguém, a menos que sejam amigos ou pessoas boas. Faça algo por um dos meus amigos e depois venha falar comigo.}
{104}{}{-feito-}
{105}{}{Ouvi o que você fez pelos meus homens. Obrigado. Com o que posso ajudar?}
{106}{}{Você quem?}
{107}{}{Ouvi dizer que você é quem sabe tudo sobre esse navio.}
{108}{}{Por que eles o chamam de Capitão?}
{109}{}{Como você consegue isso?}
{110}{}{Nada.}
{111}{}{Eu sou o capitão. Eu corro o navio. Mais perguntas, vá falar com um dos Shi ou Badger ou com alguém. Não tenho tempo para você.}
{112}{}{-feito-}
{113}{}{Este navio é um petroleiro Poseidon. Está equipado com tecnologia que durou a guerra. Tem um FOB que permite o acesso à sala de computadores de navegação, e tem um transponder IFF que o protege das armas de Poseidon.}
{114}{}{Como você sabe tudo isso?}
{115}{}{O que é um transponder do IFF?}
{116}{}{Como você consegue isso?}
{117}{}{Obrigado. Tchau.}
{118}{}{Eu costumava servir com o Enclave. Então eu percebi que não era os EUA que eu estava lutando; Era para os ricos velhos bastardos que não queriam desistir de seu poder. Abandonei e agora vivo aqui com pessoas mais honestas.}
{119}{}{Pessoas mais honestas? Esses caras?}
{120}{}{O que exatamente é o Enclave?}
{121}{}{Como você consegue isso?}
{122}{}{Tchau.}
{123}{}{Como você piloto este equipamento? Preencha-se com algum gás - experimente os Hubologists ou o Shi depois de cuidar de tudo o resto - e pressione o botão. O computador cuidará o resto, se ainda estiver funcionando. Vai direto para a plataforma de petróleo, e eles não vão disparar para você porque você tem o transponder IFF. Apenas tenha certeza de que você precisa acessar tudo: FOB, computador e combustível. Fácil o suficiente, hein?}
{124}{}{Sure. Como você sabe tudo isso?}
{125}{}{O que é um transponder IFF e um FOB?}
{126}{}{Qual plataforma de petróleo?}
{127}{}{Yes. Tchau.}
{128}{}{IFF: Identificar amigo ou inimigo. Isso significa que este navio é identificado como um amigo, de modo que outras coisas de Poseidon - como, digamos, uma plataforma de petróleo - não dispararão contra você quando você entrar no alcance. Ah, e um FOB é uma espécie de tecnologia Enclave que permite que você entre uma porta eletronicamente. Você provavelmente encontrará um deles em uma das suas bases ou em algum desses lugares.}
{129}{}{Como você sabe tudo isso?}
{130}{}{Qual plataforma de petróleo?}
{131}{}{Obrigado. Tchau.}
{132}{}{Sim. Com essas pessoas, você sabe exatamente onde você está. Eles não jogam jogos. O Enclave era como um pacote de hienas - eles iriam ligar para você em um segundo.}
{133}{}{O que exatamente é o Enclave?}
{134}{}{Como você se conectou com eles?}
{135}{}{O Enclave é restos dos velhos tempos. Se você levar esta coisa através da água para a plataforma, você descobrirá por si mesmo.}
{136}{}{Como eu o piloteio?}
{137}{}{Qual plataforma?}
{138}{}{Bastante fácil. Acabei de deixar a base de Navarro um dia e dirigi-me para cá. Achei que era o último lugar onde qualquer pessoa olharia. Além disso, não sou importante o suficiente para o Enclave procurar-me - eu sou apenas uma extremidade solta.}
{139}{}{O que exatamente é o Enclave?}
{140}{}{Obrigado. Tchau.}
{141}{}{Há uma grande plataforma de petróleo Poseidon deixada de fora na água. Essa é a base final do Enclave, e a menos que sinta falta da minha aposta, é aí que também estão os seus amigos.}
{142}{}{Como você sabe tudo isso?}
{143}{}{O que mais está acontecendo lá no equipamento?}
{144}{}{Obrigado. Tchau.}
{145}{}{Word dá uma volta.}
{146}{}{I see. O que mais está acontecendo lá no equipamento?}
{147}{}{I see. Tchau.}
{148}{}{Me bate. Eu era uma tecnologia Navarro, não um operador de plataforma. Nós falamos com eles sobre as linhas de comunicação, e isso era sobre a extensão disso.}
{149}{}{Entendo. Como faço para pilotar isso de novo?}
{150}{}{Obrigado. Tchau.}
{151}{}{Você cometeu um erro errado com o capitão e seus amigos ...}
{152}{}{Como você piloto este equipamento? Bem, vejo que você já a gaseificou. Quando você cuidou de mais alguma coisa, basta pressionar o botão. O computador cuidará o resto, se ainda estiver funcionando. Vai direto para a plataforma de petróleo, e eles não vão disparar para você porque você tem o transponder IFF. Apenas tenha certeza de que você precisa acessar tudo: FOB, computador e combustível. Fácil o suficiente, hein?}
{153}{}{Oh sim. Você também precisa fazer funcionar o computador de navegação. Aposto que você encontrará peças para isso em um desses cofres antigos.}
{154}{}{Bom te ver de novo. O que você precisa?}
