{100}{}{Você vê um punk parcialmente raspado.}
{101}{}{Você vê Ryan, Font of All Wisdom.}
{102}{}{Você vê um punk que tem um ar de arrogância e risada por ele.}
{103}{}{Você deve lutar por essa merda, cara.}
{104}{}{Este lugar é um buraco de merda.}
{105}{}{Eu vou fazer você até sangrar. Desculpe, foi isso demais?}
{106}{}{Ay carumba! Nalgas con queso!}
{107}{}{Woo hoo hoo hoo hoo!}
{108}{}{Estou fora daqui.}
{109}{}{Eu conheci o grande Jesus Mordino quando ele era o bebê Jesus.}
{110}{}{Jesus Maria Mãe de Deus!}
{111}{}{Eu sou um produtor. Eu faço jogos. Os jogos são divertidos. Jogue meus jogos.}
{112}{}{Compre flamers para flamers.}
{113}{}{Eles me chamam ... O MARTELO POLAR.}
{114}{}{Eu vim para San Fran para fazer alguns jogos e chutar o traseiro.}
{115}{}{Amor de verão'...}
{116}{}{Hola, senhor! Ou é senorita?}
{117}{}{Tê-lo!}
{118}{}{Homem ... este lugar é como uma promessa feita em Stockton - todo o vento e nenhuma ação.}
{119}{}{Meu amigo Scott achou que a capital da velha Califórnia era Stockton. Promessa!}
{120}{}{Gostaria de passar um pouco de calor no Chip.}
{121}{}{Cara!}
{122}{}{Awww, acesse!}
{123}{}{Aggro-suuuuuuuuuurge!}
{124}{}{Não me faça colocar o rosto em frente.}
{125}{}{Okay, certo?}
{126}{}{Exatamente, senhor. Heh heh heh.}
