{100}{}{Você vê um guarda em roupas soltas, vestindo um olhar de tédio cauteloso.}
{101}{}{Você vê uma guarda do palácio}
{102}{}{Você vê uma guarda do palácio carrying a dangerous-looking weapon.}
{103}{}{Apenas continue movendo-se e não haverá problema.}
{104}{}{Você tem negócios aqui?}
{105}{}{Estamos de olho em você.}
{106}{}{Não tente nada engraçado.}
{107}{}{Trate nossas pessoas com respeito.}
{108}{}{Não toque nisso. Esse é o seu último aviso.}
{109}{}{Manter longe de lá.}
{110}{}{Volte, estranho.}
{111}{}{Afaste-se lentamente disso.}
{112}{}{Nem pense nisso.}
{113}{}{Pare com isso. Agora.}
{114}{}{Morra, inimigo das pessoas!}
{115}{}{Eu estou enviando você para o inferno da queima de metal!}
{116}{}{Que o Buda tenha misericórdia de seu espírito!}
{117}{}{Sofre, inimigo!}
