{100}{}{Você vê uma criança.}
{101}{}{Uma criança.}
{102}{}{Esse garoto se parece muito com outras crianças.}
{103}{}{Você parece malvado.}
{104}{}{Não me machuque, 'kay?}
{105}{}{O que há de errado com seus olhos?}
{106}{}{Isso é um lao wai?}
{107}{}{O que você é?}
{108}{}{Alguém gosta de você?}
{109}{}{Você não vai machucar minha mãe e meu pai, você está?}
{110}{}{Eu vou jogar agora.}
{111}{}{Ha ha! Quatro olhos!}
{112}{}{Alerta de Dork! Alerta de Dork!}
{113}{}{:: os olhos do miúdo se alargam quando Marcus se aproxima ::}
{114}{}{Esse é um grande senhor verde.}
{115}{}{Por que esse homem está vestindo uma saia?}
{116}{}{Esse homem quer ser uma menina?}
{117}{}{Eeek! Tribal!}
{118}{}{Ei, senhor! Você tem um osso no nariz!}
{119}{}{Eeeek! Um zumbi!}
{120}{}{Mamãe, esse homem é contagioso?}
{121}{}{Fofo doggy! Bom garoto!}
{122}{}{Eeeee! Um monstro!}
{123}{}{Olhe o tagalong dorky!}
{124}{}{É a sua mãe?}
{125}{}{Socorro! Há um robô vindo depois de mim!}
{126}{}{Socorro! Há um robô vindo depois de mim!}
{127}{}{Isso fica quente lá? Olá? Você pode me ouvir?}
{128}{}{O que você é? Are you a person?}
{129}{}{Você é muito grande.}
{130}{}{Waaaaaah!}
{131}{}{Não me machuque!}
{132}{}{::chorando::}
{133}{}{Ajuda, mamãe!}

