{100}{}{Você vê um Shi com roupas brancas.}
{101}{}{Você vê uma tecnologia de laboratório Shi}
{102}{}{Você vê um Shi com roupas brancas em um laboratório de ciências.}

{103}{}{Man ... Wong certeza é um driver escravo.}
{104}{}{Trabalho Trabalho trabalho. Isso é tudo para o que somos bons.}
{105}{}{Vamos mudar o terreno com esta experiência!}
{106}{}{Olhe, pára-quedismo! Nós temos algo para você!}
{107}{}{Quero ver o sol novamente.}
{108}{}{Misture isso. Misture isso. Estou tão aborrecido às vezes.}
{109}{}{Você viu os resultados mais recentes da grande experiência! Mais agradável!}
{110}{}{Com licença.}

{116}{}{Ha! Ensine esses espiões a tentar entrar!}
{117}{}{Os hackers nunca tentarão isso novamente.}
{118}{}{Se não pudermos vencê-los com a ciência, os vencemos com nossos lutadores.}
{119}{}{Lo Pan e o Dragão juntos. Esse é um pensamento assustador.}
{120}{}{Esse hacker não durou muito.}
{121}{}{Trabalho Trabalho trabalho. Isso é tudo para o que somos bons.}
{122}{}{Vamos mudar o terreno desolado!}
{123}{}{Olhe, pára-quedismo!}
{124}{}{Quero ver o sol novamente.}

{127}{}{Sheng Ming é uma lesão vil.}
{128}{}{Um desses dias, vamos terminar.}
{129}{}{Para a glória do Imperador. Certo.}
{130}{}{Você ouviu? Alguém cortou nossos computadores!}
{131}{}{Aposto que foram os Hubologists que fizeram isso.}
{132}{}{Devemos liberar um vírus nos Hubologists.}
{133}{}{Eu quero vingança contra os hackers!}
{134}{}{Um dia, descobriremos quem nos cortou.}
{135}{}{Trabalho Trabalho trabalho. Isso é tudo para o que somos bons.}

{144}{}{Estamos fazendo um bom trabalho aqui! Não o arruine!}
{145}{}{Estamos tentando salvar a terra desolada, seu idiota!}
{146}{}{Não! Não nossos cientistas!}
{147}{}{Socorro! Guardas!}
{148}{}{Por favor! Você não entende!}
{149}{}{Não! Nossos experimentos!}
