{100}{}{Você vê uma mulher com uma expressão preocupada em seu rosto.}
{101}{}{Você vê Suze.}
{102}{}{Você vê uma mulher com uma expressão preocupada em seu rosto.}
{103}{}{Aieee! Ajude-me!}
{104}{}{Me salve! Por favor!}
{105}{}{Eles estão tentando me matar!}
{106}{}{Por favor! Eles vão me matar!}
{107}{}{Pare com eles! Aieee!}
{108}{}{Badger enviou você? Eu sabia que ele iria. Estou tão aliviado.}
{109}{}{Aagggh.}
{110}{}{O que você estava fazendo lá embaixo?}
{111}{}{Sim. Me siga.}
{112}{}{Oh, seu pobre querido. As radiações e os terrenos baldios não são agradáveis, não é? Espero que alguém possa ajudá-lo.}
{113}{}{É uma espécie de estúpido, realmente. Eu estava apenas explorando porque o texugo estava no computador e eu desci as escadas e me perdi e depois a próxima coisa que você conhece, estou cercada por monstros. Bom, você veio.}
{114}{}{Tenho mais perguntas.}
{115}{}{Sim. Encontrar algo interessante?}
{116}{}{Sim. Vamos.}
{117}{}{Encontrei o quarto em que eu estava. Também encontrei um quarto que parecia uma área de abastecimento. Eu não consegui muito mais longe por causa dos monstros.}
{118}{}{Tenho mais perguntas.}
{119}{}{De onde você é?}
{120}{}{Ótimo. É tudo por agora.}
{121}{}{Eu sou de um lugar ao sul do Boneyard e ao sul do Glow. Não estamos muito longe do mar. Eu costumava ser uma babá, mas as crianças se transformaram em monstros.}
{122}{}{Tenho mais perguntas.}
{123}{}{Como você conheceu o texugo?}
{124}{}{Fascinante. É tudo por agora.}
{125}{}{Ele desceu para o sul e foi para um clube ao qual eu costumava ir. Então, quando as coisas caíram para mim, pensei que este seria o lugar certo.}
{126}{}{Tenho mais perguntas.}
{127}{}{Isso é tudo. Obrigado.}
{128}{}{Você salvou minha vida. Eu responderei todas as perguntas que você tiver.}
{129}{}{Yaaaah.}
{130}{}{O que você estava fazendo lá embaixo?}
{131}{}{Você achou algo interessante?}
{132}{}{De onde você é?}
{133}{}{Como você conheceu o texugo?}
{134}{}{Nenhum agora. Tchau.}
{135}{}{Oh meu deus ... O texugo está morto ... Eu não sei o que vou fazer ... Não tenho amigos aqui ... toda a minha família está morta ... oh meu Deus ...}
{136}{}{Obrigado por toda sua ajuda. Eu vou encontrar o texugo.}
