{100}{}{Você vê um comerciante.}
{101}{}{Você vê Jenna, o comerciante.}
{102}{}{Você vê um bom proprietário da loja.}
{103}{}{Oi! Eu sou Jenna. Posso te ajudar?}
{104}{}{Eu quero informações.}
{105}{}{O que você tem?}
{106}{}{Não, eu vou.}
{107}{}{Eu quero alguma informação.}
{108}{}{Claro, me mostre o que você tem.}
{109}{}{Não agora.}
{110}{}{Aprendi que quanto menos você conhece, mais tempo você viver. Não tenho outra informação para você. Gostaria de ver meus produtos?}
{111}{}{Sim.}
{112}{}{Não.}
{113}{}{Ótimo. Dar uma olhada.}
{114}{}{}
{115}{}{Está bem.}
{116}{}{Algo mais?}
{117}{}{Sim.}
{118}{}{Não.}
{119}{}{Bem, você tem um ótimo dia então.}
{120}{}{}
{121}{}{Está bem.}
{122}{}{Olá de novo. Existe outra coisa com a qual posso ajudá-lo?}
{123}{}{Sim.}
{124}{}{Não.}
{125}{}{Me desculpe, mas estou fechado. Abro às oito; por favor, volte então.}
{126}{}{}
{127}{}{Está bem.}
{128}{}{Eu não estou aberto a você. Saia da minha loja!}
{129}{}{}
{130}{}{Está bem.}
{131}{}{Espero que a entrega entre em breve.}
