{100}{}{Você vê um barman.}
{101}{}{Você vê Slim, o barman.}
{102}{}{Você vê um barman. He's wearing an apron and is holding a glass that he constantly cleans by spitting into it and wiping it with a dirty towel. He looks like he doesn't take crap from anyone.}
{103}{}{Eu sou magro. O que você terá?}
{104}{}{Eu quero informações.}
{105}{}{O que você tem?}
{106}{}{Não, eu vou.}
{107}{}{Eu quero alguma informação.}
{108}{}{Claro, me mostre o que você tem.}
{109}{}{Nada, eu vou embora.}
{110}{}{Informação hein? Bem, eu não sou uma biblioteca e isso não é uma sala de computadores. Beba ou saia. Quer um pouco de bebida ou não?}
{111}{}{Sim.}
{112}{}{Não.}
{113}{}{Bem. Se essa merda não te mata, nada será.}
{114}{}{}
{115}{}{Está bem.}
{116}{}{Isso para você?}
{117}{}{Sim.}
{118}{}{Não.}
{119}{}{Mais tarde, então.}
{120}{}{}
{121}{}{Está bem.}
{122}{}{Bem vindo de volta. Precisa de mais bebidas alcoólicas?}
{123}{}{Sim.}
{124}{}{Não.}
{125}{}{Estou fechado. Vá embora.}
{126}{}{}
{127}{}{Está bem.}
{128}{}{Eu não estou aberto a você. Saia da minha loja!}
{129}{}{}
{130}{}{Está bem.}
