{100}{}{Você vê um comerciante.}
{101}{}{Você vê Cal, o comerciante de armas.}
{102}{}{Você vê um homem entediado, mas amigável.}
{103}{}{Bom dia para você, senhor. Posso te ajudar?}
{104}{}{Bom dia para você, senhorita. Posso te ajudar?}
{105}{}{Eu quero informações.}
{106}{}{O que você tem?}
{107}{}{Não, eu vou.}
{108}{}{Eu quero alguma informação.}
{109}{}{Claro, me mostre o que você tem.}
{110}{}{Deixa pra lá.}
{111}{}{Não tenho informações para vender. Eu lido apenas em armas. Você quer ver meus produtos?}
{112}{}{Sim.}
{113}{}{Não.}
{114}{}{Eu acho que você ficará satisfeito com minha seleção. Tome seu tempo e examine as coisas.}
{115}{}{Está bem.}
{116}{}{Haverá alguma outra coisa?}
{117}{}{Sim.}
{118}{}{Não.}
{119}{}{Então, eu lecio um dia agradável.}
{120}{}{Está bem.}
{121}{}{Olá de novo. Volte para mais?}
{122}{}{Sim.}
{123}{}{Não.}
{124}{}{Me desculpe, mas estou fechado. Abro em torno de 8. Volte, então, se você quer alguma coisa.}
{125}{}{Está bem.}
{126}{}{Eu não vou vender para você. Saia da minha loja!}
{127}{}{Está bem.}
{128}{}{Espero que a entrega entre em breve.}
