{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê a estação de trabalho de biologia.}
{102}{}{Você vê um terminal de computador funcional.}
{103}{}{Saudações. Por favor, confirme sua identidade.}
{104}{}{[Oooh! Olhe para as luzes piscando!]}
{105}{}{:: guess password ::}
{106}{}{INTLVR-Dnky-Pnch-98790}
{107}{}{:: hackear no computador ::}
{108}{}{Sair}
{109}{}{Dados para encontrar: -Botânica programa- Programa genético- -Xeno programa-}
{110}{}{Programa de Botânica.}
{111}{}{Programa genético.}
{112}{}{Programa Xeno.}
{113}{}{Nota de pessoal.}
{114}{}{Desative a estação de trabalho.}
{115}{}{Senha incorreta. Fale com o administrador do sistema. Adeus.}
{116}{}{:: hackear no computador ::}
{117}{}{::sair::}
{118}{}{Alerta de intruso ativada. Desligando. Tenha um bom dia.}
{119}{}{-feito-}
{120}{}{(depois de cerca de vinte minutos, você descobre isso: os resultados iniciais da ruptura da radiação botânica se revelam pouco promissores. O Dr. Sheng desenvolve uma vida vegetal resistente à radiação - seguem os efeitos colaterais desagradáveis. A vida vegetal resultante é considerada muito perigosa. Sheng insiste em perseguir a linha e misturá-la com programa genético.)}
{121}{}{Programa genético.}
{122}{}{Programa Xeno.}
{123}{}{Notas de pessoal recentes.}
{124}{}{Costas.}
{125}{}{(depois de cerca de vinte minutos você junta essa informação: usando o básico do vírus FEV, o Dr. Long Wang está convencido do sucesso na criação de soldados mutantes. Ele cria um soro fornecendo resultados interessantes com experiências de roedores. Ele se injeta e se dissolve em uma poça O Dr. Sheng desactiva a linha de inquérito. Com a morte do Dr. Long, o Dr. Sheng é responsável. Sheng exige foco na vida das plantas que consomem radiação.)}
{126}{}{Programa de Botânica.}
{127}{}{Programa Xeno.}
{128}{}{Notas de pessoal recentes.}
{129}{}{Costas.}
{130}{}{"O assunto em que esperávamos estabelecer uma série de experimentos significativos desapareceu, presumivelmente destruído ou roubado pelos Hubologists. Outras investigações provaram ser infrutíferas. Até que sejam obtidos outros espécimes, este banco de dados permanecerá inoperante".
- Dr. Sheng}
{131}{}{Programa de Botânica.}
{132}{}{Programa genético.}
{133}{}{Notas de pessoal recentes.}
{134}{}{Costas.}
{135}{}{Dr. Wong: Novo projeto de Biologia, além de Física de Pesquisa.
Dr. Sheng: chefe de projeto de biologia até dois meses atrás. Um mês sabático com o novo "soro de sentimentalismo botânico" representado; além de um enigma. O Dr. Wong assume o controle do Programa de Biologia.
Dr. Long: recém-morto via soro de VEF.}
{136}{}{Programa de Botânica.}
{137}{}{Programa genético.}
{138}{}{Programa Xeno.}
{139}{}{Costas.}
{140}{}{Estação desativada.}
{141}{}{Ative a estação.}
{142}{}{-sair-}
{143}{}{[A sua abordagem entre as chaves desencadeia a senha correta ... sua sorte é incrível!]}
{144}{}{-Mais-}


{145}{}{O computador não responde a nenhuma entrada.}
{146}{}{Você não consegue encontrar em qualquer lugar para colocar isso.}
