{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê a estação de trabalho de química.}
{102}{}{Você vê uma estação de trabalho de computador.}
{103}{}{Saudações. Digite sua senha para confirmar sua identidade.}
{104}{}{? Não entendi grandes palavras.}
{105}{}{TIUASPO-Lo-Shi-S12908}
{106}{}{:: hackear no computador ::}
{107}{}{Sair.}
{108}{}{Base de Dados de Química: -Fuel e derivados- -Polímeros-}
{109}{}{Combustível e derivados.}
{110}{}{Polímeros.}
{111}{}{Desative a estação de trabalho.}
{112}{}{Sair.}
{113}{}{Fale com o administrador do sistema. Adeus.}
{114}{}{:: hackear no computador ::}
{115}{}{::sair::}
{116}{}{Alerta de intruso ativada. Desligando. Tenha um bom dia.}
{117}{}{-feito-}
{118}{}{(Depois de examinar as fórmulas químicas complexas e as notas de laboratório, você conclui que o Shi criou uma espécie de combustível de extratos de plantas e sealife. Aparentemente, eles se engancharam em oleodutos previamente existentes para que eles possam transportar combustível para uma grande variedade de destinos)}
{119}{}{(Você encontra uma vasta gama de fórmulas químicas complexas e notas de laboratório. Você não tem certeza do que isso significa.)}
{120}{}{Combustível direto para o petroleiro Poseidon.}
{121}{}{Combustível directo para Hubologists.}
{122}{}{Costas.}
{123}{}{(Depois de ter passado pela simbologia e discussão técnica, você descobre que o Shi está trabalhando em um novo tipo de armadura de combate polimérica que é resistente tanto à chama quanto à penetração. Ainda há anos a partir da conclusão. Você também vê menção de novas armas e capacidades de construção. Aparentemente, o Shi tem alguns planos para o futuro.)}
{124}{}{Costas.}
{125}{}{Combustível direcionado em conformidade. Tanques de armazenamento = Vazio. Programa de encerramento.}
{126}{}{-feito-}
{127}{}{Combustível direcionado em conformidade. Tanques de armazenamento = Vazio. Programa de encerramento.}
{128}{}{-feito-}
{129}{}{Estação desativada.}
{130}{}{Ative a estação.}
{131}{}{-sair-}
{132}{}{[Sua abordagem aleatória faz maravilhas ... você está na máquina!]}
{133}{}{-Mais-}

{134}{}{O computador não responde a nenhuma entrada.}
{135}{}{Você não consegue encontrar em qualquer lugar para colocar isso.}

{136}{}{:: guess password ::}
{137}{}{Combustível direto ao longo do encanamento.}
{138}{}{Destino necessário.}
