{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê um computador Hubologist.}
{102}{}{Você vê um computador. Parece estar em bom estado de funcionamento, embora primitivo.}
{103}{}{Esta unidade não aceita comandos. Adeus.}
{104}{}{[Tente como você pode, você não parece quebrar a criptografia que controla esse computador.]}
{105}{}{Sair.}
{106}{}{Bem-vindo ao HubLink.}
{107}{}{Digite seus comandos agora.}
{108}{}{Banco de dados de acesso.}
{109}{}{Controles de acesso.}
{110}{}{Sair.}
{111}{}{Selecione o banco de dados.}
{112}{}{Pesquisa.}
{113}{}{Objetivos futuros.}
{114}{}{Finanças.}
{115}{}{Costas.}
{116}{}{[Depois de percorrer o gobbledygook religioso, parece que os Hubologists criaram um meio de endurecimento da armadura de poder. Eles também encontraram uma maneira de calcular a trajetória de lançamento, as órbitas e os destinos espaciais. Além disso, parece que eles estão trabalhando no controle do tempo.]}
{117}{}{Costas.}
{118}{}{Sair}
{119}{}{[Você gasta cerca de meia hora lendo sobre os objetivos que a AHS-9 está tentando alcançar. Além da iluminação e reunião com o Pai da Estrela, parece que ele também não tem escrúpulos em destruir humanos que não estavam com ele desde o início. Ele é um pouco louco.]}
{120}{}{Costas.}
{121}{}{Sair.}
{122}{}{[A Igreja Hubologist parece ser extremamente rica. A abordagem padrão é pedir a um novo recruta para doar todos os seus bens mundanos para a Igreja como um sinal de boa fé. Quando alguém não é convidado a fazer isso, aparentemente isso significa que os Hubologists não pretendem lidar com justiça. Eles têm um enorme cache de pilhagem escondido em algum lugar no deserto. Você não consegue descobrir as coordenadas.]}
{123}{}{Costas.}
{124}{}{Sair.}
{125}{}{Controles acessados. Selecione a operação.}
{126}{}{Formate o disco rígido.}
{127}{}{Verificação do status do sistema.}
{128}{}{Costas.}
{129}{}{Sair.}
{130}{}{Operação restrita. Consulte o administrador do sistema. Concluindo. Adeus.}
{131}{}{-feito-}
{132}{}{Não parece haver uma interface para isso.}

{133}{}{ESS Quetzel abastecido e pronto para lançar.}
{134}{}{ESS Quetzel desabotoado.}
{135}{}{Mainframe operacional. Pipeline operacional. Estações de operação operacionais. Centro de reparo operacional. Câmeras operacionais.}
{136}{}{Costas.}
{137}{}{Sair.}
