#{100}{}{Você vê um computador poderoso.} //This is for the computer object itself
#{101}{}{Você vê o computador do imperador.}
#{102}{}{Você vê um computador grande, cantarolando, totalmente funcional que tem "Imperador v8.8" estampado em sua caixa inferior.}
{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal do computador do Imperador.}
{102}{}{Você vê um computador com uma tela de toque embutida para sua interface. Gravado ao lado é "Emperor v8.8 Computer Terminal".}
{103}{}{Saudações. Digite sua senha para confirmar sua identidade.}
{104}{}{:: babar ::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ: Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{:: hackear no computador ::}
{109}{}{Sair.}
{110}{}{Identidade confirmada.}
{111}{}{Qual função você deseja acessar?}
{112}{}{Diagnóstico.}
{113}{}{Base de dados.}
{114}{}{Previsão.}
{115}{}{Nenhum.}
{116}{}{Fale com o administrador do sistema. Adeus.}
{117}{}{:: hackear no computador ::}
{118}{}{::sair::}
{119}{}{Alerta de intruso ativada. Desligando. Tenha um bom dia.}
{120}{}{-feito-}
{121}{}{Funções de diagnóstico?}
{122}{}{Digitalização em rede.}
{123}{}{Formatar drive.}
{124}{}{Verifique a integridade do disco rígido.}
{125}{}{Costas.}
{126}{}{Qual banco de dados você gostaria de verificar?}
{127}{}{Biologia.}
{128}{}{Química.}
{129}{}{Física.}
{130}{}{História.}
{131}{}{Costas.}
{132}{}{Os filhos de Shi-town estão em perigo. 50% de chance de assasio se mudar entre eles.}
{133}{}{Perigo chegou a Shi-town. 75% de probabilidade de danos aos residentes.}
{134}{}{O lançamento espacial do Hubologist é provável que 95% falham. Fatores: sem combustível, vedante impróprio, liderança fraca, falta de iniciativa.}
{135}{}{15% de chance de designar "Escolhido" tendo sucesso na tarefa.}
{136}{}{A entrada indica "Enclave" mais poderoso do que se acreditava anteriormente; não se aproxime.}
{137}{}{Causas do submarino reaparecendo neste jogo: 0%}
{138}{}{Vagabundos de tanques 0% provavelmente limparão a infestação por criatura sem assistência externa. Processo de desejabilidade de prestar assistência.}
{139}{}{Entrada: Poseidon Petroleiro impróprio para viajar. Exigir mais entrada.}
{140}{}{Não processando. Exigir entrada.}
{141}{}{-Mais-}
{142}{}{Costas.}
{143}{}{Estação de biologia: ativa}
{144}{}{Estação de biologia: Inativa}
{145}{}{Estação de química: ativa}
{146}{}{Estação de Química: Inativa}
{147}{}{Estação de física: ativa}
{148}{}{Estação de física: Inativa}
{149}{}{Desativar a Estação de Biologia.}
{150}{}{Desativar a Estação de Química.}
{151}{}{Desativar a Estação de Física.}
{152}{}{Estação de Biologia de Acesso.}
{153}{}{Acesse a Estação de Química.}
{154}{}{Access Physics Station.}
{155}{}{Activar a Estação de Biologia.}
{156}{}{Ativar Estação de Química.}
{157}{}{Ativar a Estação de Física.}
{158}{}{Costas.}
{159}{}{Formatar drive: todos os dados serão perdidos. Você tem certeza?}
{160}{}{Sim.}
{161}{}{Não.}
{162}{}{A integridade funcional deste sistema é de 92%. O núcleo blindado do Emperor Computer é 100%. A integridade dos dados é de 100%. O nó de previsão está sofrendo pequenos atrasos de energia - tempo projetado para reparar 6 dias. Previsão 15% operacional.}
{163}{}{Costas.}
{164}{}{Tem certeza de que deseja formatar esta unidade? Este é um processo irreversível.}
{165}{}{Sim.}
{166}{}{Não.}
{167}{}{Formatação ... formatação ... formatação completa. A reinicialização requer uma instalação completa. Desligando. Shutting ... down ... complete ...}
{168}{}{-feito-}
{169}{}{Dados para encontrar: - Programa de botânica - Programa genético - Programa Xeno}
{170}{}{Programa de Botânica.}
{171}{}{Programa genético.}
{172}{}{Programa Xeno.}
{173}{}{Costas.}
{174}{}{(Após cerca de vinte minutos, você descobriu isso: os resultados iniciais da ruptura da radiação botânica se revelam promissores. O Dr. Sheng desenvolve uma vida vegetal resistente à radiação - seguem os efeitos colaterais desagradáveis. A vida vegetal resultante é considerada muito perigosa. Sheng insiste em prosseguir a linha e misturá-la Com programa genético.)}
{175}{}{Programa genético.}
{176}{}{Programa Xeno.}
{177}{}{Costas.}
{178}{}{(Após cerca de vinte minutos, você juntará essa informação: usando o básico do vírus FEV, o Dr. Long Wang está convencido de sucesso na criação de soldados mutantes. Ele cria um soro fornecendo resultados interessantes com experiências de roedores. Ele se injeta e se dissolve em um Poça de goo. Dr. Sheng desactiva a linha de investigação. Com a morte do Dr. Long, o Dr. Sheng é responsável. Sheng exige foco na vida útil das radiações.)}
{179}{}{Programa de Botânica.}
{180}{}{Programa Xeno.}
{181}{}{Costas.}
{182}{}{"O assunto sobre o qual esperávamos estabelecer uma série de experimentos significativos desapareceu, presumivelmente destruído ou roubado pelos Hubologists. Pesquisas adicionais se mostraram infrutíferas. Até que sejam obtidos outros espécimes, este banco de dados permanecerá inoperante". - Dr. Sheng}
{183}{}{Programa de Botânica.}
{184}{}{Programa genético.}
{185}{}{Costas.}
{186}{}{Base de Dados de Química: Combustível e Derivados - Polímeros}
{187}{}{Combustível e derivados.}
{188}{}{Polímeros}
{189}{}{Costas.}
{190}{}{(Depois de analisar as complexas fórmulas químicas e notas de laboratório, você conclui que o Shi criou um tipo de combustível de extratos de plantas e sealife. Aparentemente, eles se engancharam em oleodutos anteriormente existentes para que eles possam transportar combustível para uma grande variedade De destinos)}
{191}{}{(Você encontra uma vasta gama de fórmulas químicas complexas e notas de laboratório. Você não tem certeza do que isso significa.)}
{192}{}{Combustível direto para o petroleiro Poseidon.}
{193}{}{Combustível directo para Hubologists.}
{194}{}{Costas.}
{195}{}{(Depois de percorrer a simbologia e a discussão técnica, você descobre que o Shi está trabalhando em um novo tipo de armadura de combate polimérica que é resistente tanto à chama quanto à penetração. Ainda é anos de conclusão. Você também vê menção de novas armas E capacidades de construção. Aparentemente, o Shi tem alguns planos para o futuro.)}
{196}{}{Costas.}
{197}{}{Combustível direcionado em conformidade. Tanques de armazenamento = Vazio. Programa de encerramento.}
{198}{}{-feito-}
{199}{}{Combustível direcionado em conformidade. Tanques de armazenamento = Vazio. Programa de encerramento.}
{200}{}{-feito-}
{201}{}{Base de dados de física: Exploração - Teoria}
{202}{}{Exploração}
{203}{}{Teoria}
{204}{}{Costas}
{205}{}{"Com a recente aquisição de planos de vertibird, a possibilidade de criar uma máquina de vôo prática deu um salto considerável para a frente. Esperamos ter um protótipo de trabalho no final do ano e a capacidade de produzir em massa esses veículos dentro de dois anos. " -Dr. Wong}
{206}{}{::copy plans:: Costas.}
{207}{}{Costas.}
{208}{}{"Ainda estamos preparando um modelo de trabalho de um veículo aéreo. Nenhum dos projetos que criamos provou ser seguro ou aerodinâmico. Talvez se tivéssemos acesso aos planos dos antigos ..." -Dr. Wong}
{209}{}{Costas.}
{210}{}{(Depois de avançar através da introdução e da matemática, você descobre que os Shi estão aprendendo a desenvolver a energia nuclear novamente, reconstruindo as teorias de viagens espaciais dos antigos - e eles zombam dos Hubologists ao fazê-lo - e aproveitando a energia do sol, o vento E ao mar. Pelo menos, é o que as notas lêem como.)}
{211}{}{Costas.}
{212}{}{Estação ativada.}
{213}{}{Costas.}
{214}{}{O terminal do computador não parece ter uma interface para isso.}
{215}{}{O terminal do computador parece não operacional.}

{216}{}{Houve um compromisso no sistema. As ordens são para atacar!}
{217}{}{Ataque o intruso!}
{218}{}{Tempo para pagar seus atos, lao wai!}
{219}{}{Há um traidor em nosso meio!}

{220}{}{Geo-Location.}
{221}{}{O que você deseja localizar?}
{222}{}{Os aldeões da minha casa.}
{223}{}{97% de chance agregada - Aldeões localizados nas coordenadas atuais do composto Enclave.}
