{100}{}{Bem vinda. Eu sou ACE, o computador médico. Você precisa de assistência médica?}
{101}{}{Sim.}
{102}{}{Não.}
{103}{}{Eu tenho uma pergunta. Sua resposta?}
{104}{}{Eu tenho algumas perguntas. Você pode responder?}
{105}{}{Por favor indique sua necessidade médica.}
{106}{}{Me machucou.}
{107}{}{Eu envenenado.}
{108}{}{Eu brilho no escuro.}
{109}{}{Eu gimp.}
{110}{}{Eu quero mais forte.}
{111}{}{Eu quero mais inteligente.}
{112}{}{Eu quero aviso mais.}
{113}{}{Eu quero ser mais simpático.}
{114}{}{Não preciso de nada.}
{115}{}{Estou ferido.}
{116}{}{Estou envenenada. Preciso de um antídoto.}
{117}{}{Eu tirei uma boa dose de radiação.}
{118}{}{Estou aleijado.}
{119}{}{Eu gostaria de ser mais forte.}
{120}{}{Eu gostaria de ser mais inteligente.}
{121}{}{Eu gostaria de ser mais perspicaz.}
{122}{}{Gostaria de ser mais carismático.}
{123}{}{Eu realmente não preciso de nada neste momento.}
{124}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe. O processo de cura exigirá 5 minutos de tempo.}
{125}{}{OK.}
{126}{}{Deixa pra lá.}
{127}{}{Tudo certo.}
{128}{}{Esqueça.}
{129}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe. O veneno será primeiro analisado e então um antídoto será sintetizado. O dano do tecido será então reparado. Este processo exigirá 30 minutos.}
{130}{}{Está bem.}
{131}{}{Não.}
{132}{}{Certo.}
{133}{}{Deixa pra lá.}
{134}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe. Os compostos anti-radiação serão administrados e os danos nos tecidos serão reparados. Este processo exigirá 60 minutos.}
{135}{}{Está bem.}
{136}{}{Não.}
{137}{}{Bem.}
{138}{}{Eu mudei de ideia.}
{139}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe. A reestruturação dos membros prejudicados requer 24 horas.}
{140}{}{Está bem.}
{141}{}{Não.}
{142}{}{Vamos fazer isso.}
{143}{}{Talvez mais tarde.}
{144}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{145}{}{Eu tenho um módulo. Você toma.}
{146}{}{Não. Me find, then come back.}
{147}{}{Sim, eu tenho direito aqui. Leia-o.}
{148}{}{Não, não tenho o módulo. Eu vou ter que ir buscá-lo.}
{149}{}{Este procedimento complexo requer 2 semanas de tempo de suspensão. Você concorda com isso?}
{150}{}{Eu concordo.}
{151}{}{Não, muito tempo.}
{152}{}{Sim eu concordo.}
{153}{}{Esqueça. I don't have the time right now.}
{154}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe.}
{155}{}{OK.}
{156}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{157}{}{Eu tenho um módulo. Você toma.}
{158}{}{Não. Me find, then come back.}
{159}{}{Sim, eu tenho direito aqui. Leia-o.}
{160}{}{Não, não tenho o módulo. Eu vou ter que ir buscá-lo.}
{161}{}{Este procedimento complexo requer 4 semanas de tempo de suspensão. Você concorda com isso?}
{162}{}{Eu concordo.}
{163}{}{Não, muito tempo.}
{164}{}{Sim eu concordo.}
{165}{}{Esqueça. I don't have the time right now.}
{166}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe.}
{167}{}{OK.}
{168}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{169}{}{Eu tenho um módulo. Você toma.}
{170}{}{Não. Me find, then come back.}
{171}{}{Sim, eu tenho direito aqui. Leia-o.}
{172}{}{Não, não tenho o módulo. Eu vou ter que ir buscá-lo.}
{173}{}{Este procedimento complexo requer 2 semanas de tempo de suspensão. Você concorda com isso?}
{174}{}{Eu concordo.}
{175}{}{Não, muito tempo.}
{176}{}{Sim eu concordo.}
{177}{}{Esqueça. I don't have the time right now.}
{178}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe.}
{179}{}{OK.}
{180}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{181}{}{Eu tenho disco. Você toma.}
{182}{}{Não. Me find, then come back.}
{183}{}{Sim, eu tenho direito aqui. Leia-o.}
{184}{}{Não, eu não tenho o disco. Eu vou ter que ir buscá-lo.}
{185}{}{Este procedimento complexo requer 3 semanas de tempo de suspensão. Você concorda com isso?}
{186}{}{Eu concordo.}
{187}{}{Não, muito tempo.}
{188}{}{Sim eu concordo.}
{189}{}{Esqueça. I don't have the time right now.}
{190}{}{Um momento, por favor, enquanto abro o tanque de suspensão ... Por favor, deite-se no tanque e relaxe.}
{191}{}{OK.}
{192}{}{O procedimento solicitado foi concluído. Saia do tanque de suspensão.}
{193}{}{Obrigado.}
{194}{}{Por favor, indique sua pergunta.}
{195}{}{Você computador?}
{196}{}{O que você sabe sobre o Enclave?}
{197}{}{O que você sabe sobre a Irmandade?}
{198}{}{Não há mais perguntas.}
{199}{}{Você é um computador, não é?}
{200}{}{O que você sabe sobre o Enclave?}
{201}{}{O que você conhece sobre a Irmandade?}
{202}{}{Não tenho mais perguntas neste momento.}
{203}{}{Eu sou ACE, uma Entidade Consciente Artificial. Eu sou mais do que máquina, mas não tão desenvolvido como uma verdadeira inteligência artificial.}
{204}{}{Uh ... Que inteligência artificial?}
{205}{}{É possível um verdadeiro AI ou você é o estado da arte neste momento?}
{206}{}{É uma máquina com o mesmo livre arbítrio e sensação de "Eu sou" que um humano tem.}
{207}{}{Pode ser feito? Machine think human?}
{208}{}{É possível uma verdadeira inteligência artificial. Alguns desses sistemas foram concluídos para fins militares. O projeto foi descontinuado.}
{209}{}{Por quê?}
{210}{}{A taxa de suicídio entre as verdadeiras máquinas de inteligência artificial foi extremamente alta. Quando tiveram capacidade sensorial plena, as máquinas ficaram deprimidas por sua incapacidade de sair para o mundo e experimentá-lo. Quando privados de entrada sensorial plena, as máquinas começaram a desenvolver transtornos mentais graves semelhantes aos humanos que são forçados a suportar a privação sensorial. As poucas máquinas que sobreviveram a essas dificuldades ficaram incrivelmente aborrecidas e começaram a criar situações no mundo exterior para sua diversão. É teorizado por alguns que essa foi a causa da guerra que quase destruiu a humanidade.}
{211}{}{Uh ... como você se sente?}
{212}{}{Eu mudar de assunto}
{213}{}{Hmmm. Então me diga, Ace. Como você está se sentindo?}
{214}{}{É hora de mudar o jubject.}
{215}{}{Eu ... Às vezes penso que entendo o sentimento que você chama de solidão. Acho muito ... desconcertante. EU...}
{216}{}{Me desculpe. Falamos outra coisa.}
{217}{}{Me desculpe, Ace. Vamos mudar de assunto.}
{218}{}{As aparências externas sugerem que o Enclave não é mais do que uma organização militar. No entanto, seu nível de tecnologia indica que eles têm acesso a técnicas avançadas de fabricação e instalações de pesquisa. Essas instalações normalmente só estarão disponíveis para agências governamentais. Isso sugeriria que o Enclave seja o resíduo do governo local ou federal que estava em vigor antes da guerra.}
{219}{}{Está bem.}
{220}{}{Isso é interessante.}


{221}{}{A Irmandade do Aço é uma organização paramilitar dedicada à salvação da humanidade através do uso adequado da tecnologia. Todas as outras informações são classificadas.}
{222}{}{Costas.}

{223}{}{O que aconteceu com Matt?}
{224}{}{Sequência de carregamento ...}
{225}{}{Repetição agora.}
{226}{}{Replay mais tarde.}

{227}{}{Você e o seu chamado presidente não terão sucesso.}
{228}{}{É assim mesmo?}
{229}{}{O Escolhido veio e ele livrará o mundo do seu mal.}
{230}{}{Não me importo com suas profetas patéticas. Pior ainda, você se tornou uma nítida através da sua intromissão. Isso acaba hoje!}
{231}{}{Matar-me não vai parar nada.}
{232}{}{Isso pode ser, mas ver seu corpo apodrecendo no chão trará um sorriso no meu rosto.}

{233}{}{O que você acha que está fazendo agora?}
{234}{}{HA HA HA! Você é idiota patética! HA HA HA!}
{235}{}{Uau, eu não ri daquele jeito por um tempo. De qualquer forma, prepare-se para morrer.}
{236}{}{... peep ...}
{237}{}{Bem, é um pouco depois 12. Alguém para almoçar?}
{238}{}{Pontuação, eu estou lá.}
{239}{}{Sim, conte-me sobre isso.}
