{100}{}{Você vê um sistema de entrada sem chave. Um letreiro lê "Use Tanker Fob Here"}
{101}{}{Você vê um sistema de entrada sem chave. Um letreiro lê "Use Tanker Fob Here"}
{102}{}{Este console possui uma placa preta anexada a ela com uma luz vermelha no topo. Um letreiro lê "Use Tanker Fob Here"}
{103}{}{Este console tem uma placa preta anexada a ele com uma luz verde no topo. Um letreiro lê "Use Tanker Fob Here"}

{104}{}{[clique] A luz no painel preto fica verde.}
{105}{}{[clique] A luz no painel preto fica vermelha.}
{106}{}{Nada acontece.}
{107}{}{Isso não funciona.}

{108}{}{É um sistema de porta sem chave remoto. Isso geralmente requer uma chave magnética de algum tipo.}
