{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê a estação de física.}
{102}{}{Você vê um terminal de computador funcional.}
{103}{}{Saudações. Por favor, confirme sua identidade.}
{104}{}{[Oooh! Olhe para as luzes piscando!]}
{105}{}{:: guess password ::}
{106}{}{KSLJKJ: Ken-Lee-97313}
{107}{}{:: hackear no computador ::}
{108}{}{Sair.}
{109}{}{Base de dados de física: -Exploração- -Teloria-}
{110}{}{Exploração...}
{111}{}{Teoria...}
{112}{}{Desative a estação.}
{113}{}{Senha incorreta. Fale com o administrador do sistema. Adeus.}
{114}{}{:: hackear no computador ::}
{115}{}{::sair::}
{116}{}{Alerta de intruso ativada. Desligando. Tenha um bom dia.}
{117}{}{-feito-}
{118}{}{"Com a recente aquisição de planos de vertibird, a possibilidade de criar uma máquina de vôo prática deu um salto considerável para a frente. Esperamos ter um protótipo de trabalho no final do ano e a capacidade de produzir em massa esses veículos dentro de dois anos. " -Dr. Wong}
{119}{}{:: copiar planos :: Voltar.}
{120}{}{Costas.}
{121}{}{"Ainda estamos preparando um modelo de trabalho de um veículo aéreo. Nenhum dos projetos que criamos provou ser seguro ou aerodinâmico. Talvez se tivéssemos acesso aos planos dos antigos ..." - Dr. Wong}
{122}{}{Costas.}
{123}{}{(Depois de avançar através da introdução e da matemática, você descobre que os Shi estão aprendendo a desenvolver a energia nuclear novamente, reconstruindo as teorias de viagens espaciais dos antigos - e eles zombam dos Hubologists ao fazê-lo - e aproveitando a energia do sol, do vento e ao mar. Pelo menos, é o que as notas lêem como.)}
{124}{}{Costas.}
{125}{}{Estação desativada.}
{126}{}{Ative a estação.}
{127}{}{-sair-}
{128}{}{De alguma forma, você escreve aleatoriamente uma seqüência de letras e acabou ganhando acesso! Quão feliz você consegue?}
{129}{}{-Mais-}
{130}{}{O computador não responde a nenhuma entrada.}
{131}{}{Você não consegue encontrar em qualquer lugar para colocar isso.}

{132}{}{Planos de cópia ..... Copiar completo ... Voltar para ... Erro de E / S ... GPF ... Desativação do Terminal.}
