{100}{}{Você vê um computador PoseidoNet.}
{101}{}{Você vê um computador PoseidoNet.}
{102}{}{Você vê um computador PoseidoNet.}


{103}{}{:: bip :: mau funcionamento do terminal. Exigir a instalação NavComp. ::bip::}
{104}{}{-feito-}
{105}{}{Bem-vindo ao PoseidoNet. Este terminal é limitado à transmissão entre um petroleiro - PMV Valdez - e plataforma de ancoragem. Comando?}
{106}{}{Ir.}
{107}{}{Verifique o status.}
{108}{}{Sair}
{109}{}{- Tanques de combustível: vazio - Confidencialidade: vazio - Computador de navegação: não funcional - Linhas de gerenciamento: anexado -}
{110}{}{-costas-}
{111}{}{Sair.}
{112}{}{- Tanques de combustível: Full- -Cargo Hold: Empty- -Navigation Computador: Non Functional- -Morando Linhas: Attached-}
{113}{}{-costas-}
{114}{}{Sair}
{115}{}{ERRO: tanques de combustível vazios.}
{116}{}{ERRO: Navagational Computer non Functional.}

{117}{}{-Fuel Tanks: Empty- -Cargo Hold: Empty- -Navigação Computador: Functional- -Mooring Lines: Attached-}
{118}{}{- Tanques de combustível: Full- -Cargo Hold: Empty- -Navigation Computer: Functional- -Mooring Lines: Attached-}

{119}{}{Você vê um computador PoseidoNet Navagational.}

{129}{}{[Você corre rapidamente pela sequência de lançamento e o navio foge da plataforma.]}
{130}{}{-feito-}
{131}{}{Computador Navagacional on-line.}
