{100}{}{Você vê um Ghoul particularmente curioso.}
{101}{}{Você vê Harold.}
{102}{}{Você vê um ghoul muito antigo, mas ainda de aspecto rápido.}

{103}{hld1a}{Eu tenho que te dizer, ol 'Harold é um pouco lento no sorteio. Nós dois conversando não teríamos feito muito.}
{104}{hld1b}{Ahh, você não é fofo. Eu simplesmente não tenho tempo para tentar entender você agora.}
{105}{hld1c}{Heh heh, você não é um chute.}

{106}{hld2a}{Olá, liso. O nome é Harold. Ajudo a manter esta cidade em funcionamento.}
{107}{hld2a1}{O que você precisa, jovem?}

{108}{hld2b}{Bem, maldito, pele lisa. Você nos fez um grande favor ajudando nossa usina. O nome é Harold. Eu mantenho esta cidade em funcionamento.}
{109}{hld2c}{Mighty kind of 'ya nos ajudando com a usina de energia atômica. Estamos de sua dívida. Agora, o que essa carcaça irritadiça pode fazer por você?}
{110}{hld2d}{Você é alguma coisa. Assim como o original. O que o velho Harold pode fazer por você, Vault Dweller?}
{111}{hld2e}{Você não fez danos suficientes, pele lisa? O que você quer agora?}
{112}{}{Pele macia? Por que você me ligou assim?}
{113}{}{Vault Dweller? Eu não sou um morador do Vault.}
{114}{}{Olá, Harold. O que você faz aqui?}

{115}{}{Existe algum lugar onde posso trocar ou reabastecer aqui?}
{116}{}{Isso é uma árvore que cresce fora de sua cabeça?}
{117}{}{Você deve saber se há algo chamado um kit de criação do Garden of Eden aqui.}
{118}{}{Harold, eu gostaria de saber onde posso curar.}
{119}{}{Eu sei que você provavelmente ainda está bravo, mas você mencionou o Mestre. Meu antepassado o matou.}
{120}{}{Olá, Harold. Apenas passando. Adeus.}

{121}{hld3}{Wha, o que for preciso para manter este lugar juntos. Melhor trabalho nisso do que eu.}
{122}{}{Este lugar está se afastando?}
{123}{}{Você não parece tão bom.}

{124}{hld3a}{Sim, mas estou ótimo por estar morto! Nunca me canso dos olhares quando digo isso.}
{125}{}{Ahh, certo ... Então você diz que o lugar está caindo aos pedaços?}
{126}{}{Morto, você diz? Bem, nesse caso você está ótimo. Tão bom, você pode responder a minha próxima pergunta.}

{127}{hld4a}{Bem, sorta. Nãosso reator atômico é um ácaro ... sensível. As pessoas que consegui correr significam bem, mas ... bem, elas não são as ferramentas mais afiadas no galpão. Se você souber o que quero dizer.}
{128}{hld4b}{Bem, estamos melhorando agora, você corrigiu nosso reator. Nunca pensei que ninguém conseguisse esses idjits na Vault City para nos ajudar.}
{129}{hld4c}{Você sabe, não é tão ruim agora. Você conserta a usina, então você obtém a informação que precisamos para torná-la boa como nova. Golly-be-damned, não é alguma coisa ?!}
{130}{}{O que você quer dizer?}
{131}{}{Eu não queria ver o Vault City destruir sua cidade.}
{132}{}{Well, Eu não queria ver o Vault City destruir sua cidade. Besides it was in their best interest to fix your power plant as well.}
{133}{}{Bem, uma vez que é no melhor interesse da Vault City consertar seu reator, não foi muito difícil obter as informações de otimização.}
{134}{}{Eu não gosto de completar nenhum trabalho apenas a meio caminho.}
{135}{}{Bem, eu adoraria ficar e conversar com você, mas eu tenho coisas para fazer e lugares para ir. Boa sorte.}

{136}{hld5}{Bem, tecnicamente ... é uma coisa.}
{137}{}{Ok, o que ele faz?}

{138}{hld6}{Precisa de um pouco de tempo na pedra forte, hein? Quero dizer, eles não são muito brilhantes. Aqui está um exemplo. Não outro dia, recebo um relatório. Sobre isso, diz que a válvula de refrigerante principal deve ser desligada. Isso causaria uma fusão que tornaria o Grand Canyon parecido com um cascalho de porco.}
{139}{}{Isso parece ruim.}

{140}{hld7}{Uh, sim, isso seria ruim. Agora, eu consertei as coisas no tempo, mas chegamos perto do fim. Eles precisam de alguém para cuidar deles.}
{141}{}{Bom, você está aqui para ajudá-los.}

{142}{hld8}{Quem pensou que estaria fazendo coisas corretas? Embora, se não conseguirmos um Regulador de Magnetosfera Hidrelétrica muito rápido, haverá problemas.}
{143}{}{O que diabos é Hydra-magna-whateveraltor?}
{144}{}{Hmm, parece um problema real, tudo bem. Deixe-me perguntar-lhe outra coisa.}
{145}{}{Problema? Que tipo de problema?}
{146}{}{Bem, tirei o suficiente do seu valioso tempo. Adeus.}

{147}{hld9}{Heck, se não fosse por você, eles malditos idem em Vault City woulda nos colocou para a grande soneca.}
{148}{}{Eu não podia deixar Vault City matar todos vocês.}
{149}{}{Feliz em ajudar, Harold. Permitam-me perguntar-lhe sobre outra coisa, no entanto.}

{150}{hld11a}{Mighty kind a'ya. Nem muitos peitos suaves fariam isso por uma cidade cheia de ghouls. Um pouco me lembra de um smoothie que eu conhecia, de volta quando.}
{151}{hld11b}{Você sabe, você é muito parecido com o Vault Dweller.}
{152}{}{Another smoothie? O que você quer dizer?}
{153}{}{Obrigado. Estou esperando viver de acordo com meu antepassado. Deixe-me perguntar-lhe outra coisa enquanto estiver aqui que possa ajudar.}
{154}{}{Feliz por ajudar. Permitam-me perguntar-lhe sobre outra coisa.}
{155}{}{Bem, tudo em um dia de trabalho realmente. Eu tenho que ir agora, no entanto. Pessoas para salvar, monstros para matar, desastres para evitar, você sabe, todo esse tipo de coisa. Adeus.}

{156}{hld14}{Você corta com a borda maçante da faca, não é? Você não parece uma casca de laranja à esquerda no sol o dia todo. Sua pele ainda é macia e purty.}
{157}{}{Me trouxe lá. Vou tentar fazer minha próxima pergunta um pouco mais valer a pena.}
{158}{}{Oh. Sim. Ei, deixe-me perguntar-lhe outra coisa.}
{159}{}{Você é melhor não receber dúvidas divertidas sobre minha pele macia.}
{160}{}{Bem, é melhor eu ir. Adeus.}

{161}{hld15}{Idéias engraçadas? Bem, você quer dizer como esfolar você com uma faca enferrujada, aborrecida e velha, e depois enxertar sua pele ainda quente, úmida, reluzente, oh-tão suave, sobre meu gook crocante e podre?}
{162}{}{Ei! Você simplesmente me afasta de mim. Estou saindo daqui enquanto ainda tenho a minha pele!}
{163}{}{Sim, é exatamente o que eu quis dizer. Boa decisão.}

{164}{hld16}{Bem, você não tem nada com que se preocupar ... não consigo encontrar minha faca.}
{165}{}{Por que eu mudo o assunto com outra pergunta?}
{166}{}{Bem, é melhor você manter suas luvas sujas na minha pele. Adeus.}

{167}{hld17}{Mais pele! ... Precisa de mais pele! (risadas) O que aconteceu? Deixe seu senso de humor na poeira no caminho da cidade?}
{168}{}{Eu tenho muita coisa na minha cabeça, está bem? Preciso de mais informações.}
{169}{}{Eu acho que irei procurá-lo. Adeus.}

{170}{hld18}{Eu apenas deixo um grande peido e ainda não cobre seu fedor. Por que você simplesmente não se afasta?}
{171}{}{Ok, mas primeiro eu queria me desculpar pela maneira como eu agi mais cedo.}
{172}{}{Coloque uma meia nele, velho e maldito ghoul. Adeus.}

{173}{hld19}{Isso é um começo, mas você terá que fazer melhor.}
{174}{}{Não sei o que mais dizer. Eu acho que não ligo bem com coisas novas para mim. Desculpe-me, no entanto.}
{175}{}{Ok, e quanto a isso? Se eu estivesse nervoso que parecia meio tão ruim quanto você, eu o queimaria apenas para evitar envenenar os catadores que pudessem acontecer sobre isso. Tchau.}

{176}{hld20a}{Bem, tudo bem. Mas é melhor você parar de ser um bonehead.}
{177}{hld20b}{Bem, eu digo-lhe jovem. Experimente, mas você ainda é um idjit. Talvez essa seja a lição que você precisa. Você está fora daqui.}
{178}{}{Eu sinto Muito. Agora que temos isso resolvido. Deixe me perguntar algo.}
{179}{}{Ok, adeus.}

{180}{hld21a}{Prefiro parecer isso do que parecer com você e ter que ser você. Você é uma cabeça de osso. Saia daqui a mais.}
{181}{hld21b}{Você é como aquele booger ruim, você não pode sacudir o dedo. Mas ainda estou tremendo ... Oh, olhe, vá lá!}
{182}{hld21c}{Bem, veja o que o vento caiu. Meu turd favorito. Por que não esbarrar aqui?}
{183}{hld21d}{Quer saber como manter um idjit em suspenso?}
{184}{hld21e}{Ei, eu estava esperando que você aparecesse. Você ganhou um prêmio por ter sido o maior idiota. Há uma festa em sua honra a dez milhas a norte da cidade. Melhor se apressar.}

{185}{hld26}{Their best interest? O que você quer dizer?}
{186}{}{Bem, de acordo com alguns dados econômicos que recebi da Vault City, é muito melhor se eles o ajudem a reparar sua usina.}
{187}{}{Quero dizer, é sempre melhor tentar se dar bem com os outros.}
{188}{}{Uh, nada.}
{189}{}{Uau, é muito mais tarde do que pensei que fosse. É melhor eu ir. Adeus.}

{190}{hld27}{Dados econômicos? Você não lhes deu essa informação, de que Gordon continua a bater o seu jeito, não é?}
{191}{}{Uh, sim, eu fiz. Por quê?}
{192}{}{Uh, não, claro que não.}

{193}{hld28}{Sim, bem, tenho certeza de que um pouco de osso, muito parecido com você, disse o mesmo sobre o Mestre.}
{194}{}{Parece uma ótima história. Gostaria de ter tempo para ouvir, mas eu tenho que ir.}
{195}{}{O mestre? Meu antepassado o matou!}

{196}{hld29}{Nada, hein? Não estou comprando isso. Você apenas nos colocou em um vínculo. Por que você não se encaixa enquanto penso em fazer o que fazer?}
{197}{}{U desculpe.}
{198}{}{Sim claro. Por que você não faz isso? Geez, tente ajudar algumas pessoas ....}

{199}{hld30}{Por quê?! Agora, Vault City sabe o quanto precisamos de minério de urânio de Broken Hills. Eles poderiam cortar os embarques e nós estaríamos finalizados.}
{200}{}{Ah, não pode ser tão ruim quanto tudo. Eles pareciam pessoas razoáveis   para mim.}
{201}{}{Eu não sabia que era para o que eles usariam as informações. Eu sinto Muito. Adeus.}

{202}{hld31}{Bem, espero que não. Esses idjits em Vault City odeiam ghouls. Eles cortaram nossas remessas de minério de Broken Hills em um minuto quente. Então eles estabeleceram os termos. Não demoraria até que Gecko fosse um campo de escravos.}
{203}{}{Tenho certeza de que não fariam isso. Parecem bastante razoáveis.}
{204}{}{Bem, é uma coisa boa que não lhes contei nada assim. Heh heh. Ei, deixe-me perguntar-lhe outra coisa.}
{205}{}{Bem, a merda acontece. Às vezes acontece com você. Adeus.}

{206}{hld32}{Razoável? Razoável! Bem, tenho certeza de que as pessoas disseram que o Mestre também era razoável. Que cabeça de osso. Dar o fora. Agora!}
{207}{}{Talvez tenham a ideia certa. Talvez seja hora de pôr fim a enrugamentos como você. Adeus.}
{208}{}{Uh, bem, eu sei, isso é. Adeus.}

{209}{hld33}{Bem, você pode tentar falar com Wooz no Harp. Você não pode perder isso - é apenas do outro lado do caminho.}
{210}{}{Obrigado. Deixe-me perguntar-lhe outra coisa.}
{211}{}{Obrigado, é tudo o que preciso saber por enquanto. Adeus.}

{212}{hld34}{Com ciumes? O nome dele é Herbert. Eu falo com ele quando eu ficar solitário ... Heh heh. Apenas entendendo ... O nome dele é Bob.}
{213}{}{Certo ... Bem, talvez você ou Bob saibam a resposta para isso.}
{214}{}{Obrigado, é muito mais do que eu preciso saber por enquanto. Adeus.}

{215}{hld35}{Um Kit de Criação do Jardim do Éden? A GECK, certo? Parece lembrar que Vaults teve aqueles. Não sei onde você encontra um hoje.}
{216}{}{Obrigado. Deixe-me perguntar-lhe outra coisa.}
{217}{}{Obrigado, é tudo o que preciso saber por enquanto. Adeus.}

{218}{hld36}{Apenas fale com o meu assistente, Lenny. Ele será capaz de corrigi-lo bem.}
{219}{}{Obrigado. Deixe-me perguntar-lhe outra coisa.}
{220}{}{Obrigado, é tudo o que preciso saber por enquanto. Adeus.}

{221}{hld37}{Outro pele lisa. Tinha muito respeito por isso.}
{222}{}{Quem era aquele?}

{223}{hld38}{Bem, eu provavelmente poderia lembrar se eu não estava morto. Nunca me canso dessa brincadeira.}
{224}{}{Talvez você não ...}

{225}{hld38a}{Bem, para ser sincero, não consigo lembrar o nome. Mas eles usavam um terno engraçado. Um pouco como o que você está vestindo.}
{226}{}{Estou vestindo o Vault Suit que meu antepassado usava. É um totem da minha santa missão.}
{227}{}{Oh, esse antigo?}

{228}{hld38b}{Sem mentira}
{229}{}{Estou vestindo o Vault Suit que meu antepassado usava. É um totem da minha santa missão.}
{230}{}{Nenhuma mentira, Harold.}

{231}{hld39}{É assim? Bem, bem, bem. Isso explica uma coisa ou duas. Perguntei por que você parecia familiar. Eu não estou perdendo as últimas bolas de coupla que eu tenho deixado.}
{232}{}{Nós realmente nos parecemos?}
{233}{}{Diga-me como era o Vault Dweller.}

{234}{hld40}{Sim, parecia exatamente assim. Venha pensar nisso, tinha um 13 sobre isso também.}
{235}{}{Na verdade, este é o terno do meu antepassado, o Vault Dweller.}

{236}{hld41}{Há uma semelhança. Perto como eu me lembro, de qualquer maneira. Você sabe, seu antepassado salvou todo o nosso grande.}
{237}{}{O Vault Dweller salvou todos os ghouls?}
{238}{}{Obrigado. É bom saber. Olha, tenho que fugir um pouco. Vejo você mais tarde.}

{239}{hld42}{Iniciando conclusões, jovem. Isso vai acabar com seu traseiro. Todos nós. Salvo cada baralhote de duas pernas no planeta dang.}
{240}{}{Não percebi isso.}
{241}{}{Eu acho que já ouvi o suficiente por enquanto. Adeus.}

{242}{hld43}{Bem. Agora você faz. E o que aconteceu depois? Para um agradecimento, as malditas e altas Vauros iniciaram o Vault Dweller. Sempre me perguntei o que aconteceu depois disso.}
{243}{}{Posso dizer o que aconteceu.}
{244}{}{Basta relembrar, deixe-me perguntar-lhe outra coisa.}

{245}{hld44}{Bem, eu gostaria de ouvir isso.}
{246}{}{A lenda do Vault Dweller começa com o Vault lançando-o para os resíduos secos .... [Você conta a Harold a história do seu antepassado] ... e por isso estou procurando pelo Vault 13 agora.}

{247}{hld45}{Obrigado por contar. Eu estava curioso durante todos esses anos. Você obteve seu trabalho cortado para você. Eh, você sabe ...}
{248}{}{Sabe o que?}
{249}{}{Já tomei o suficiente do seu tempo. É melhor eu ir. Adeus.}

{250}{hld46a}{Bem, eu tenho guardado estes para um dia chuvoso, mas parece que você vai precisar mais do que nunca. Aqui, pegue estes.}
{251}{hld46b}{Eu lhe daria alguns estoques curativos, mas me diga, se eu não fizesse isso já. Eu digo a você que está sentindo o velho na memória.}
{252}{}{Obrigado. Permitam-me perguntar-lhe sobre algo.}
{253}{}{Obrigado por tudo. É melhor eu ir embora. Adeus.}

{254}{hld48a}{Sem um regulador de magnetosfera hidroelétrico funcional, estamos vazando refrigerante radioativo nas águas subterrâneas. Agora, isso significa que qualquer pessoa que use essa água não é uma arma que precisa de uma luz noturna para fazer uma meada de meia-noite. Além disso, precisamos de mais combustível porque a nossa usina de energia não o está queimando de forma muito eficiente.}
{255}{hld48b}{Precisamos de um Regulador de Magnetosfera Hidrelétrica e precisa ser instalado em breve ou temos alguns problemas reais.}
{256}{}{Soa mal. Onde você obteria um Hydro-magnetosomething-or-other?}
{257}{}{O que acontece se você não conseguir a parte?}
{258}{}{De quem você compra o seu combustível?}
{259}{}{Desculpe ouvir isso. Deixe-me perguntar-lhe sobre outra coisa.}
{260}{}{Eu acho que vou ter que deixá-lo para seus problemas agora mesmo. Adeus.}

{261}{hld49}{Bem, estou certo de que os bastardos da vila de Vault têm um. Não que compartilhassem. Inferno, mesmo que tivéssemos uma dessas coisas, não estou tão certo de que Festus poderia instalar a coisa dang.}
{262}{}{Vault City não lhe daria a parte? Mesmo que isso signifique que as águas subterrâneas não serão poluídas mais?}
{263}{}{Parece que você tem muito em sua mente. Adeus.}

{264}{hld50}{Se não entendemos, você pode apostar que os ossos da cidade de Vault desligam nossa usina, permanentemente.}
{265}{}{O que você vai fazer então?}

{266}{hld51}{Recebemos nosso combustível do Broken Hills. Essa é uma comunidade de mineração, algumas maneiras para o sul.}
{267}{}{Interessante. Onde você conseguiria um daqueles Hydro-magnetosomething-ou-outros?}
{268}{}{O que acontece se você não conseguir aquela Hydro-part?}
{269}{}{Hmm, acho que devo deixar você descobrir isso sozinho. Adeus.}

{270}{hld52}{Faça cochilos. Vault City não joga legal. Eles virão aqui e matar todos nós se não conseguirmos essa parte. Bem, pelo menos eu vou ter uma árvore para um monumento.}
{271}{}{Qual o nome dessa parte novamente?}
{272}{}{Parece que você precisa de Hydro-thingy muito mal. Deixe-me perguntar-lhe outra coisa agora mesmo.}
{273}{}{Parece um problema. Preciso fugir e ver o que posso fazer. Tchau.}

{274}{hld53}{Bem, eles só nos ajudariam se achassem que era do seu melhor interesse fazê-lo. Hã. Não há muita chance de isso acontecer.}
{275}{}{Hmm, você pode estar certo. Ainda assim, se alguém pudesse convencê-los de que eles deveriam ajudá-lo ...}

{276}{hld54}{Eles atiraram ghouls à vista. Faz uma conversa um pouco complicada.}
{277}{}{Pergunto-me se alguém poderia dizer-lhes.}
{278}{}{Sim, seria. Agora eu tenho outra pergunta.}
{279}{}{Ei, você nunca sabe. Vejo você mais tarde.}

{280}{}{Para o norte}
{281}{}{Para o nortewest}
{282}{}{Para o próximo}
{283}{}{Para o sudoeste}
{284}{}{Para o sul}
{285}{}{Para o suleast}
{286}{}{Para o leste daqui}
{287}{}{Para o norteeast}
{288}{}{Eu não entendo.}
{289}{}{Eu não sei.}
{290}{}{Isso machuca.}
{291}{}{Isso realmente dói.}
{292}{}{Isso deve doer.}
{293}{}{Eu não sei nada sobre isso.}
{294}{}{sim}
{295}{}{Não}
{296}{}{Por que você me fala assim?}
{297}{}{Você não é legal.}
{298}{}{Obrigado.}
{299}{}{Isso é bom.}
{300}{}{Isso não é bom.}
{301}{}{Tenho uma boa sensação sobre isso.}
{302}{}{Eu tenho um mau pressentimento sobre isso.}
{303}{}{Essas pessoas estão loucas.}
{304}{}{Não aprendi nada.}
{305}{}{Eu aprendi algo}
{306}{}{Todos estão loucos aqui?}
{307}{}{Deve haver outro caminho.}
{308}{}{Me siga.}
{309}{}{Tente isso.}
{310}{}{Venha aqui.}
{311}{}{Eu estou assustado.}
{312}{}{Estou preocupado.}
{313}{}{Eu encontrei algo.}
{314}{}{Eu tive sorte.}
{315}{}{Você precisa corrigir isso.}
{316}{}{Você precisa ativar isso.}
{317}{}{Você precisa desbloquear isso.}
{318}{}{Você precisa abrir isso.}
{319}{}{Talvez devêssemos voltar aqui.}
