{100}{}{}
{101}{}{}
{102}{}{}

{103}{powr1}{ENCLAVE aqui. Por que o seu feed de vídeo não funciona?}
{104}{}{Uh, está funcionando bem. Eu posso ver você.}
{105}{}{Está quebrado.}
{106}{}{Estamos trabalhando no link visual agora. Eu só queria testá-lo.}
{107}{}{(Sair.)}

{108}{powr2}{Que diabo é isso?}
{109}{}{Uh, todos estamos bem aqui. Como você está?}
{110}{}{Isso é caau, rit, sss, pu-, me atrapalha. Sobre.}
{111}{}{Eu sou o Escolhido, então é melhor ver seu idioma.}
{112}{}{Esta é a Unidade Três relatando em.}

{113}{powr3_c}{Bem, sua unidade ainda não parece estar operacional, Pal. Quem é?}
{114}{powr3a}{Isso não significou muita diferença. Ainda não estou tendo uma droga. Quem é Você?}
{115}{}{Por favor repita. Sobre.}
{116}{}{Eu poderia te dizer, mas então eu teria que matá-lo.}
{117}{}{Eu sou o Escolhido.}
{118}{}{Bem, isso não é incomum, não é? Nada mais funciona.}
{119}{}{Isso é para mim saber e para descobrir. Adeus.}

{120}{powr3b_b}{Do que você está falando? Quem - quem é esse?}
{121}{}{Eu poderia te dizer, mas então eu teria que matá-lo.}
{122}{}{Eu sou o Escolhido.}
{123}{}{Bem, isso não é incomum, não é? Nada mais funciona.}
{124}{}{Isso é para mim saber e para descobrir. Adeus.}

{125}{powr4a_a}{O presidente! Eu, uh ...}

{126}{powr4b_b}{Ah Um cara sábio, hein? Olha, estou te traçando agora, amigo. Veremos o quão inteligente você sente com a segurança interna em todo o seu traseiro fricking. Dickhead!}
{127}{powr4c_a}{Agora, já tive o suficiente da sua besteira. Como você gostaria de jogar dodge-the-plasma com o Assault Squad? Hã?}
{128}{}{Ei, desculpe, não queria incomodar você.}
{129}{}{Eu tenho o seu rastro para você, e posso mostrar-lhe exatamente onde empurrá-lo.}
{130}{}{Você está me riscando? Bem, estou trazendo um traço em você também, amigo.}
{131}{}{Eu adoraria ficar em pé e conversar com todos os seus amigos sobre o chuveiro nupcial que você planejou, mas eu tenho melhores coisas para fazer com o meu tempo. Adeus.}
{132}{}{Bem, eu, eu tenho que ir. Adeus.}

{133}{powr5_a}{Experimente o ganho.}
{134}{}{Lá ... isso deve ser feito. Melhor?}
{135}{}{Ganho? O que eu deveria ganhar? Eu permaneço bastante ativo, acho que não posso ganhar nada.}
{136}{}{Vou tentar mais tarde. Adeus.}

{137}{powr6_a}{Escolhido, hein? Bem, uh, perdoe-me por não ter soprado o sol na sua bunda, mas estou um pouco ocupado por essa besteira.}
{138}{}{Arrefecer-se diante de mim e posso poupar sua vida. Gee, eu gosto do som disso.}
{139}{}{Não insisto mais na genuflexão. Um leve arco para beijar meu anel deve ser suficiente.}
{140}{}{Uh, eu quis dizer que eu era o * escolhido * para consertar a unidade de comunicação. Parece que nada mais funciona.}
{141}{}{Bem, acho que já tive bastante da sua insolência. Adeus, camponeses.}

{142}{powr7_a}{Unidade Três? Eu pensei que você ainda estava na base de Navarro?}
{143}{}{Base Navarro? Ah, sim, base de Navarro. É aí que estamos. Certo. Eu sabia.}
{144}{}{Não, tivemos que sair daqui.}
{145}{}{Seu sinal está terminando. Adeus.}

{146}{powr8_a}{Huh, não é a verdade. Não deixe que ninguém que tenha ouvido o presidente ouça isso. Você estará fazendo gado-corre para New Reno até o fim dos tempos, amigo.}
{147}{}{O presidente?}
{148}{}{Só tenho duas pernas. Eu ficaria bastante cansado quando cheguei lá.}
{149}{}{Bem, não há descanso para os perversos. É melhor eu voltar a corrigir isso. Adeus.}

{150}{powr9_a}{Sim, é um novo. Desde que meu vídeo está funcionando, você pode ver que estou rolando no chão aqui. Parece que tudo é um maldito segredo, hein? Todas as operações especiais no continente. Não vejo como nada é feito.}
{151}{}{No continente? Por que, onde você está?}
{152}{}{Bem, é assim por toda parte.}

{153}{powr10_a}{Sim, você sabe o quanto ele é infeliz quando as pessoas reclamam. Ele é pessoal, como se fosse uma coisa de fidelidade. Talvez seja apenas o Presidente dos Estados Unidos. Ou o que resta deles.}
{154}{}{O Presidente dos Estados Unidos?}
{155}{}{Não votei para ele. Eu pensei que ele estava muito interessado em ficar deitado. Eu prefiro um candidato que é muito velho para recuperá-lo - mantém sua mente no trabalho mais.}
{156}{}{Talvez assim. Você sabe, é melhor eu voltar ao trabalho. Adeus.}

{157}{powr11}{Oh, muito engraçado. Mas você teria um ótimo lugar para se recuperar da sua corrida - pelo menos do que eu ouço.}
{158}{}{Então você não está em New Reno então?}
{159}{}{Bem, é melhor eu voltar ao trabalho. Tenho que corrigir este link. Adeus.}

{160}{powr12}{O Presidente dos Unidos-fodendo-Estados-da-América. De quem você pensaria que eu estava falando? Quem é o fu - Quem é - O que - Eu devia chutar seu bicho maldito, quem é esse?}
{161}{}{Eu sou o Escolhido. Kiss my...feet.}
{162}{}{Eu sou o Escolhido.}
{163}{}{Eu sou o presidente. Você está com um monte de problemas.}
{164}{}{Você não é importante o suficiente para essa informação.}
{165}{}{É melhor eu ir. Muito trabalho a fazer aqui. Adeus.}

{166}{powr13}{Isso é ENCLAVE main comm. ... Mas você deve saber disso. Quem é Você?}
{167}{}{Oh, eu só ... hey, você já percebeu que o gecko cozido tem um gosto de brahmin butt.}
{168}{}{Eu sou o Escolhido e você aprenderá a lembrar disso.}
{169}{}{Ninguém é importante. Adeus.}

{170}{powr14}{Ah, mais alguns momentos e vou ter o seu culpa triste em uma funda. Ei, espere um minuto. Isso não pode estar certo ... Eu tenho você em algum lugar do continente.}
{171}{}{Isso é certo, otário. Bem, onde você não pode me pegar.}
{172}{}{Isso não pode estar certo. Eu estou na mesa de comando do outro lado do corredor de você ... Fez você olhar. O que é um rube.}
{173}{}{Sim, estou na planta de energia Poseidon Oil número 12. Venha me pegar.}

{174}{powr15}{Eu tenho você, no Poseidon Oil, reator número 5. Ah, bem, por que você não se sente bem e eu vou encomendar uma pequena festa para você. Incluindo fogos de artifício.}
{175}{}{Oh, bom. Eu apenas gosto de fogos de artifício. Envie-me muito.}
{176}{}{Eu sou o Escolhido. You just better make sure you say that with a smile.}
{177}{}{Eu não sou ninguém importante. Eu vou agora. Adeus.}

{178}{powr16_a}{Sim, seja qual for o seu nome, acabei de despachar uma equipe de verti-assalto para sua localização. Tenha um bom dia.}
{179}{}{Gee, se o vídeo funcionasse, você poderia me ver tremer.}
{180}{}{E o que eles vão fazer?}
{181}{}{Bem, é melhor eu ir lá. Eu odiaria que eles apareçam antes de eu pegar o tapete vermelho todos desenrolados. Adeus.}

{182}{powr17}{Normalmente, eles simplesmente passam a disparar. Eles deixaram alguém peneirar as cinzas para descobrir o que estava acontecendo.}
{183}{}{Sim, bem, eles não vão me pegar.}
{184}{}{Oh, agora você me deixou com medo. Preciso mudar minhas roupas íntimas.}
{185}{}{Bem, eu odiaria pensar que eu passei o dia todo dia pulando minhas armas por nada.}
{186}{}{Sim claro. Eu matei melhor. Adeus.}

{187}{powr18}{Adeus. A próxima notícia sobre você será quando leio o relatório pós-ação.}
{188}{}{O que? Você pode ler!}
{189}{}{Sim, claro o que quer que seja.}
{190}{}{Ei, você entrou na minha lista.}

{191}{powr19_a}{Você teve que sair? Por quê? Você está na costa. Você tem grandes defesas. Eu não ouvi nada sobre isso ... Ei, quem diabos é isso mesmo?}
{192}{}{Eu sou o grande e poderoso Willie. Ajoelhe-se diante de mim e implore meu perdão e ainda posso poupar-me.}
{193}{}{Ninguém é importante. Onde está este Navarro de novo?}
{194}{}{Sim, bem, nós levamos Navarro e encontrei essas fotos nuas de sua mãe. Ou era só seu pai se vestir novamente? Não é de admirar que você seja tão feio. Adeus, idiota.}

{195}{powr20}{Sim, você pode dizer isso de novo. E tudo está sempre mais apertado aqui em ENCLAVE e o maldito presidente está nos observando como um falcão.}
{196}{}{O presidente?}
{197}{}{Lá fora? Onde você está exatamente?}
{198}{}{Bem, é assim que vão as coisas. Bem, é melhor eu voltar ao trabalho. Adeus.}
