{100}{}{Você vê um ghoul curto.}
{101}{}{Você vê Percy Crump, o comerciante ghoul bem sucedido.}
{102}{}{Você vê um ghoul mais curto e bastante robusto. Ele está bem vestido - uh, por um ghoul, isso é.}
{103}{}{Por Deus e por golly. Eu simplesmente não acredito em agradecer o suficiente para recuperar meu amigo. Gee-whillikers. Eu tenho que te dar problemas de vontade.}
{104}{}{Fiquei satisfeito em ajudá-lo.}
{105}{}{O que eu ganho?}
{106}{}{Bem, é melhor valer a pena. Isso certamente foi muito trabalho, e muita viagem também. Perigoso, foi o que era. Eu poderia estar ferido.}
{107}{}{Você não quer ajudar ole Percy com seu problema? I shore poderia usar a ajuda.}
{108}{}{Uh, deixe-me pensar um pouco mais. Enquanto isso, conseguiu algo para negociar?}
{109}{}{Bem, por que você não me fala mais sobre isso.}
{110}{}{Eu não sabia que você ia me incomodar sobre isso toda vez que eu entrei. Sheesh. Adeus.}
{111}{}{Você encontra Woody ainda? Eu estou realmente preocupado. Ele nunca foi tão longe há tanto tempo.}
{112}{}{Uh, ainda não, mas ainda estou olhando. Ei, você tem alguma coisa que eu possa trocar?}
{113}{}{Não, eu não tenho certeza. É melhor eu voltar lá e continuar olhando.}
{114}{}{Olá, Percy Crump aqui, Master Merchant nesta localidade. Mas seu parente me liga simplesmente a Ole Percy. Sim você pode.
 Heck, todo mundo faz. Agora, para o que posso te fazer?}
{115}{}{O que você pode percorrê-lo?}
{116}{}{Eu só queria saber o que está acontecendo aqui na cidade.}
{117}{}{Eu queria saber se você tinha alguma coisa que eu poderia comprar ou negociar?}
{118}{}{Uh, nada realmente, eu estava apenas olhando ao redor. Adeus.}
{119}{}{Comércio?}
{120}{}{Goo? Eu vou adeus.}
{121}{}{Jist quer congra-chew-late you fer makin 'nosso reator atômico corre tão purdy. Ela é um purrin 'como uma gatinha agora.
 De qualquer forma, não é assim, meu amigo Woody acabou de sair.}
{122}{}{Tenho que ser obrigado, gentilmente, por consertar nosso Atomic Reactor. Aquele tolo tolo Festus tweren't nunca é bom demais.
 De qualquer forma, não é assim, meu amigo Woody acabou de sair.}
{123}{}{Não é muito novo aqui na cidade. Eu ouço Wooz roubou um novato de uma Black Orchid no outro dia. Heh, heh, hee.
 De qualquer forma, não é assim, meu amigo Woody acabou de sair.}
{124}{}{Bem, conte-me mais sobre isso.}
{125}{}{Oh isso é muito ruim. Bem, eu odeio histórias tristes. Vou deixá-lo em paz com sua dor. Adeus.}
{126}{}{Por que eu costumo fazer, heck, obteve todos os tipos de coisas aqui o preço certo que eu faço.}
{127}{}{Obtenha tudo o que precisa ou deseja mais?}
{128}{}{Eu quero coisas?}
{129}{}{Hmm, vamos ver o que você tem.}
{130}{}{Deixe-me dar uma olhada em seus produtos.}
{131}{}{Isso é para mim. Obrigado, Percy. Adeus.}
{132}{}{Oog. Eu vou adeus.}
{133}{}{Esta grande caixa de águas antiguas de medicina anti-radee-ation não me está fazendo nada de bom. Jist sobre um hunnert-sumpin 'anos também
 tarde para usá-lo. Heh, heh, heee. Aqui, vá, estou achando que os amigos valem mais a mais todos os anos. Obrigado ... amigo.}
{134}{}{Fiquei satisfeito em ajudá-lo e Woody. Obrigado pelos medicamentos.}
{135}{}{Trabalho legal e fácil para o saque de lotes. Eu gosto disso.}
{136}{}{Bem, você vê, eu tinha um amigo, nome de Woody. Que Woody, ele pode dormir como ninguém que eu já vi. O que é pior, ele
 gosta de viajar. Realmente gosta de chutar o pó que se faz.}
{137}{}{OK.}
{138}{}{Bem, isso não é um problema, "por aqui. Mas, por último, ouvi Woody estava a dar uma volta
 para o Den. Você sabe onde está o Den?}
{139}{}{Sim, eu sei onde é o Den. Continue.}
{140}{}{Na verdade, não sei onde está o Den.}
{141}{}{Ah, é muito fácil chegar. Aqui: Eu vou marcá-lo para você no seu pequeno mappy-thing-doohickie.}
{142}{}{Ei, tenha cuidado com isso! Ok, continue agora.}
{143}{}{Bem, qualquer coisa, como eu estive dizendo que não é um grande problema 'Gecko. Mas, veja, pessoas em outras partes
 não é tão útil do jeito que nos parece.}
{144}{}{Assim?}
{145}{}{Você não colocou dois e dois ta-gether? Estou preocupado com o fato de Woody ter se dado uma soneca no Den - é um longo
 viagem depois de tudo - e então eles teriam enterrado o pobre cuss vivo! Eu preciso de alguém para ir olhar. Estou lá.}
{146}{}{E...?}
{147}{}{Bem, sinto falta de mim. É por isso. (Percy pisca, úmido, em você) Oh, eu vejo, você quer saber o que há para você?}
{148}{}{Esta é geralmente a parte em que me interessa mais. Diga.}
{149}{}{Bem, eu sei de onde morro um grande número de ações de pré-guerra, jan-u-wine, Rad-X e RadAway. Não me faça
 não é bom, não, como, mas acho que valeu valer a pena sumpin para um bom gosto como você. Você vai me interessar ou não? eu vou
 Apenas pague você se eu sei que o Woody está seguro.}
{150}{}{Apenas quanto é um pedaço de um?}
{151}{}{Sim, vou fazer isso. Eu voltarei para você em breve.}
{152}{}{Não, acho que não quero ajudá-lo agora mesmo.}
{153}{}{Deixe-me pensar sobre isso. Adeus.}
{154}{}{É uma visão mais difícil que você nunca precisará, isso é o quanto é. Você vai fazer isso?}
{155}{}{Sim, vou fazer isso. Eu voltarei para você em breve.}
{156}{}{Não, acho que não quero ajudá-lo agora mesmo.}
{157}{}{Deixe-me pensar sobre isso. Adeus.}
{158}{}{Agradeço-amável por achar meu amigo Woody. Agora, o que parente de Percy faz você?}
