{100}{}{A pessoa que você vê está brilhando fracamente. Sua pele parece estar gravemente queimada.}
{101}{}{Você vê um Glowing One, um cidadão de Gecko.}
{102}{}{Você vê alguém que foi exposto a tanta radiação que está brilhando fracamente.
 Que muita radiação parece ter devido matá-los, mas eles parecem bem o suficiente.}

{110}{}{Esta radiação certamente gera segurança no trabalho para mim.}
{111}{}{Olhe para isso brilha. Você pode vê-lo?}
{112}{}{Adoro vir ao trabalho todos os dias.}
{113}{}{Indo mais necessidade de urânio.}
{114}{}{Acho que todos nós somos atômicos aqui.}

{120}{}{Eu simplesmente amo o calor aqui.}
{121}{}{É maravilhoso aqui.}
{122}{}{Eu não sei o que eu faria Se eu tivesse que viver em outro lugar.}
{123}{}{Adoro a sensação de radiação na parte da manhã.}
{124}{}{Pelo menos eu nunca preciso de uma luz noturna.}
{125}{}{(Leva seu dedo incandescente para você) Telefone para casa.}
{126}{}{Você sabe, se você fechar a porta, eu não resplandece mais.}
{127}{}{Este é um lugar que eu realmente sinto como se eu pertencesse.}
{128}{}{Não posso acreditar que as pessoas da cidade de Vault desejam destruir minha casa.}
{129}{}{Reator, reator doce.}
{130}{}{Seja tão humilde.}
{131}{}{Aquecimento energético atômico ... tenho que amar.}

{140}{}{Obrigado por consertar o reator. Agora é um pouco mais frio, mas não muito ruim.}
{141}{}{Brrr ... obrigado por consertar nosso reator.}
{142}{}{Eu queria ter conseguido essa parte.}
{143}{}{Obrigado pela ajuda.}
{144}{}{Talvez as pessoas da cidade de Vault não sejam tão ruins depois de tudo.}

{150}{}{Não consigo lembrar quando o reator correu isso bem.}
{151}{}{Está bem frio aqui hoje.}
{152}{}{Brrrr, estou congelando.}
{153}{}{Eu acho que tenho geladura ou algo assim.}
{154}{}{Isso é frio para você?}
