#############################################################
#  Message File: GeckJunk.msg                               #
#                                                           #
#  Created: August 14, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

{100}{}{Você entrou no junkyard Gecko.}
