{100}{}{Você vê uma mulher de meia-idade ligeiramente atraente.}
{101}{}{Você vê Aileen, um dos químicos da cidade.}
{102}{}{Você vê uma mulher de meia-idade ligeiramente atraente. She looks tough and capable. Her hands are stained with chemicals.}
{103}{}{Obrigado por ajudar a causa.}
{104}{}{Fico feliz que você seja um de nós.}
{105}{}{Vamos mostrar essas distâncias.}
{106}{}{Com os direitos humanos, camarada.}
{107}{}{Você tem as coisas certas.}
{108}{}{Saia daqui.}
{109}{}{Mutie-lover.}
{110}{}{É melhor você manter sua boca fechada, se você sabe o que é bom para você.}
{111}{}{Maldito simpatizante mutante.}
{112}{}{Por que você não volta para seus amigos mutantes?}
{113}{}{Solidariedade humana, camarada.}
{114}{}{Somos nós contra eles.}
{115}{}{Você escolheu o lado vencedor.}
{116}{}{Essas mutis estão diminuindo.}
{117}{}{Vamos mostrar os mutantes que são chefe.}
{118}{}{Mesmo muias não podem respirar veneno.}
{119}{}{A hora da humanidade está próxima.}
{120}{}{Eu adoro a idéia de mutis sufocando a morte.}
{121}{}{Nossa vitória está quase aqui.}
{122}{}{Logo, Broken Hills será nosso.}
{123}{}{Damn mutie lover.}
{124}{}{Saia daqui.}
{125}{}{Você é apenas um lacaiista mutante imperialista.}
{126}{}{Você escolheu errado dessa vez.}
{127}{}{Você vai se arrepender do que você fez aqui.}
{128}{}{Git out, você manchou idjit.}
{129}{}{Você deve ser parte mutante.}
{130}{}{Saia daqui, impuro.}
{131}{}{Stupid fool. Saia daqui.}
{132}{}{Não tenho tempo para quem gosta de você.}
{133}{}{Fale com Jacob se quiser alguma coisa.}
{134}{}{Meu marido Jacob pode cuidar de suas necessidades.}
{135}{}{Uh, você poderia parar de me incomodar?}
{136}{}{Não posso ajudá-lo, mas meu marido, Jacob, pode.}
{137}{}{Apenas me deixe em paz.}
{138}{}{Muito bom para você visitar. Agora saia.}
{139}{}{Por que você rastreou em toda essa lama?}
{140}{}{Você agirá assim na sua própria barraca?}
{141}{}{Por favor, deixe-me só.}
{142}{}{Eu não sei o que você quer, mas gostaria que você me deixasse sozinho.}
{143}{}{Nós fomos configurados! Nós não matamos essas pessoas nos túneis!}
