{100}{}{Você vê um mutante grande e corpulento com uma sensação de propósito em seus olhos.}
{101}{}{Você vê um dos guardas do banco, um mutante grande e resistente.}
{102}{}{Você vê um guarda bem armado e alerta; Um mutante que carrega uma arma bastante perversa.}

{103}{}{Posso ajudar?}
{104}{}{Agga agga!}
{105}{}{Eu na construção! Oooh!}
{106}{}{Apenas olhando por aí.}
{107}{}{Err ... não, na verdade não.}
{108}{}{Sim. Estou aqui para conversar com seus prisioneiros.}
{109}{}{Você considerou que você pode estar segurando seus prisioneiros ilegalmente?}

{110}{}{Ótimo, outro de vocês. Por favor saia.}
{111}{}{Aaaaahn!}
{112}{}{OK!}

{113}{}{Sim, bem, procure outro lugar. Nós temos criminosos aqui. Ir.}
{114}{}{Oh. Tudo certo.}

{115}{}{Nós podemos ajudar todos que vêm aqui por algum motivo. Se você não pode ser ajudado, então você tem que ir. Continue antes de ajudá-lo.}
{116}{}{Vou me fazer?}
{117}{}{Consegui.}

{118}{}{Você está aqui para falar com eles, hein? Bem, você pode conversar conosco. O que você tem a dizer?}
{119}{}{Você considerou que você está segurando ilegalmente?}
{120}{}{Coma isso, mutie!}
{121}{}{Nada. Eu irei agora.}

{122}{}{Err ... o que você quer dizer?}
{123}{}{O que quero dizer é que eles não cometeram nenhum crime, exceto pelo discurso deles. Eles falaram apenas de mutantes. Não estou dizendo que não cometerão um crime ... mas você gostaria de ser detido por um crime que você poderia cometer?}
{124}{}{Esse poder faz a lei. Eu tenho o poder. Bem aqui.}

{125}{}{Não, eu não faria, mas eles são claramente perigosos.}
{126}{}{Até que cometem um crime, eles são culpados de nenhum crime. Até que eles realmente colocaram seus planos e começaram a execução do crime, eles não são culpados. Certo?}
{127}{}{Perigoso? Eu sou perigoso. Você é perigoso. Nós não estamos na prisão.}
{128}{}{E daí?}

{129}{}{Mas ... mas ... tudo bem. Eles estão fora. Você é responsável. Eu apenas espero que você esteja certo. Aqui está a chave.}
{130}{}{Isso é tudo o que eu queria. Ótimo. Obrigado. Tchau.}

{131}{}{Sim, mas talvez devêssemos ser. Agora, eles são. E eles ficam lá até que alguém possa me mostrar uma razão melhor para deixá-los sair. Agora ... saia.}
{132}{}{Não.}
{133}{}{Tudo certo.}

{134}{}{Então eles vão ficar na prisão por enquanto. Temos de proteger a sociedade. Agora ... saia.}
{135}{}{Não.}
{136}{}{Tudo certo.}

{137}{}{Você! Que diabos está fazendo? Saia já daqui!}

{138}{}{Você vai colocar suas armas agora, amigo.}

{139}{}{Você novamente? O que você quer?}
{140}{}{Apenas olhando por aí.}
{141}{}{Err ... não, na verdade não.}
{142}{}{Sim. Estou aqui para conversar com seus prisioneiros.}
{143}{}{Você considerou que você pode estar segurando seus prisioneiros ilegalmente?}

{144}{}{Você não deveria estar por aqui. Saia agora.}
{145}{}{Se eu já descobrir onde esses malditos prisioneiros fugiram, haverá um inferno para pagar!}
