{100}{}{Você vê um homem agachado com roupas escaldantes.}
{101}{}{Você vê Brian.}
{102}{}{Você vê um homem agachado com roupas escaldantes. He has a toothpick in his mouth and is covered in grease. His fingernails are dirty.}
{103}{}{Vamos ver como você gosta disso, você é anti-social.}
{104}{}{Whaddya quer?}
{105}{}{Nyug aarg.}
{106}{}{Quem é Você?}
{107}{}{O que é este lugar?}
{108}{}{Já ouviu falar de um GECK?}
{109}{}{Diga, Eric me pediu para ajustar a ração de energia em sua casa. Ele disse que está suando demais.}
{110}{}{Ei, Eric é muito feliz em sua linda casa legal. E percebo que o poder não falhou na cidade.}
{111}{}{Eu simplesmente fui e conversei com Eric e ele disse que ele costumava dirigir o lugar e que há muito poder nas lingotes de urânio que você nunca notaria o pequeno dreno que ele tomaria. Por isso, tossir o poder.}
{112}{}{Nada. Tchau.}
{113}{}{Eu? Eu sou Brian. Eu trabalho o gerador que alimenta esse lugar.}
{114}{}{Então você é o cara que eu preciso ver. Eric diz que ele é muito desconfortável em seu lugar, e ele precisa de mais poder para o seu ar condicionado.}
{115}{}{Entendo. Isso é muito interessante. Deve ser um trabalho gratificante.}
{116}{}{Ótimo. Eu tenho mais perguntas.}
{117}{}{Este lugar é a estação de energia para Broken Hills. O que eu faço é essencialmente um trabalho de manutenção no lugar ... certifique-se de que ele continua funcionando. É bastante malditamente funcional, porém ... alimentado por slugs de urânio.}
{118}{}{Isso deve ser ótimo. Diga, eu tenho mais perguntas.}
{119}{}{Slugs de urânio?}
{120}{}{Interessante. Tchau,}
{121}{}{UM GECK? Nunca ouvi falar disso. Eu imagino que ninguém mais aqui tem. Parece um animal ou algo que tem garras desagradáveis, no entanto.}
{122}{}{Não, na verdade não. Eu tenho mais perguntas.}
{123}{}{Não é isso mesmo. Tchau.}
{124}{}{Eric quer mais poder? Eric não pode ter mais poder. Este é um equilíbrio de energia muito delicado que atravessamos aqui, e se Eric tiver mais poder, então o hospital fecha-se. Ou as luzes. Ou a mina. Não podemos ter isso.}
{125}{}{Se esta máquina é executada em slugs de urânio, você tem energia suficiente para preencher este lugar e New Reno e nem percebe o dreno. Agora tossir.}
{126}{}{Mas ... mas ... ele está sofrendo.}
{127}{}{Então, não há como você pode fazer alguns pequenos ajustes?}
{128}{}{[ele olha sombriamente para baixo em seus mostradores e diz com uma voz pequena:] Você é malvado.}
{129}{}{Sim. Tchau!}
{130}{}{Ei! Não toque em nada! Este é um equipamento delicado! Fora! Lado de fora! Continue! Ir para casa!}
{131}{}{Ooooh! Butunz!}
{132}{}{Bem, não, não é. Na verdade não. Eu simplesmente apenas sentei-me aqui e certifique-se de que nenhum dos mostradores deslize para fora. Faço pequenos ajustes. Desligue alguns interruptores. Isso é sobre tudo. Qualquer um poderia fazê-lo.}
{133}{}{Então, digamos, você poderia enviar mais energia para a casa de Eric?}
{134}{}{Alguém, eh? Tenho outras questões.}
{135}{}{Obrigado. Tchau.}
{136}{}{Bem, com a mina de urânio ali mesmo, e com o poder atômico sendo o poder do futuro, parece correto que continuemos com os tempos. Podemos ser pequenos, mas somos progressivos.}
{137}{}{Hmm. Certo. Tenho outras questões.}
{138}{}{Certo. Tchau.}
{139}{}{Bem, claro, tecnicamente isso é verdade, mas ...}
{140}{}{Mas nada. Você é apenas preguiçoso. Faça um movimento.}
{141}{}{Você não precisa ser malvado com isso. [ele pica a cabeça e gira um mostrador]. Diga-lhe para parar de reclamar agora.}
{142}{}{Você é todo o coração, grande cara.}
{143}{}{Vá empurrá-lo para cima dos lábios com os quais você nunca beija. Não, obrigado por você por fazer isso mais difícil do que deveria ser.}
{144}{}{Talvez ele devesse tomar banho com mais frequência. Dia bom.}
{145}{}{Tchau.}
{146}{}{Não. Não tenho medo. As necessidades da cidade superam as necessidades de um.}
{147}{}{Eu tenho outras perguntas, então.}
{148}{}{Isso é muito utilitário de você. Eu vou deixar ele saber que ele não é importante. Adeus.}
{149}{}{Hmm ... wha '... hein?}
{150}{}{Zzzzzz ... ronco ...}
{151}{}{Whadda quer ...? Hmm...? ::ronco::}
