{100}{}{Você vê um homem empoeirado e com sono.}
{101}{}{XXX}
{102}{}{Você vê um homem empoeirado e com sono. His clothes look very, VERY old fashioned.}
{103}{}{:: ele esfrega o sono de seus olhos :: Wha '... hein? Onde estou? Há quanto tempo eu durmo?}
{104}{}{Urr?}
{105}{}{Quem é Você?}
{106}{}{Não tenho idéia de quanto tempo você está dormindo, mas você está em Broken Hills, perto da Nova República da Califórnia.}
{107}{}{Ah não! Eu dormi por tanto tempo que o mundo se tornou estúpido! Aieeeeeeee! :: ele foge em pânico ::}
{108}{}{-feito-}
{109}{}{Eu sou Chuck Stodgers, o maior piloto de avião do mundo! Infelizmente ... eu bati. Eu cambaleei para esta caverna para me afastar da explosão, e os fumos me abalaram.}
{110}{}{Isso parece com desconfiança a premissa de uma série de desenhos animados de celulose.}
{111}{}{Novo O QUE? CALIFÓRNIA? O MUNDO ALTEROU MUITO? AIEEEEEEEEEEEEEEEEE! :: ele foge em pânico ::}
{112}{}{Ei, agora, espere um segundo ...}
{113}{}{Sim, sim, não é? Tenho que ir ver o que aconteceu no mundo. Boa sorte, amigo!}
{114}{}{Você também, Sr. Stodgers!}
{115}{}{Você descobriu mais uma outra referência de cultura pop obscura.}
{116}{}{Zzzzzzzzzzz.}
