{100}{}{Você vê um conjunto de química.}
{101}{}{Você vê um químico Li'l.}
{102}{}{Você vê um Li'l Chemist, um conjunto de química que permite criar combinações interessantes.}

{103}{}{Onde você quer começar? Você tem quatro líquidos em frascos: vermelho, azul, amarelo e claro.}
{104}{}{Vermelho.}
{105}{}{Azul.}
{106}{}{Amarelo.}
{107}{}{Claro.}
{108}{}{Não faça nada.}

{109}{}{Você seleciona o vermelho. Com o que você deseja misturar?}
{110}{}{Azul. This will make Purple.}
{111}{}{Amarelo. This will make Orange.}
{112}{}{Claro. This will make Vermelho.}
{113}{}{Beba.}
{114}{}{Azul. This, you know, will make jet, an habit-forming amphetamine-like chem… if you get the correct
 dosages.}
{115}{}{Amarelo. Your scientific mind realizes this will, if successfully mixed, make hydrochloric acid.}
{116}{}{Claro. Your trained eye knows that this will make a powerful vitamin… but only if you measure
 the correct amounts.}
{117}{}{Pare agora.}

{118}{}{Você seleciona o azul. Com o que você deseja misturar?}
{119}{}{Vermelho. This will make Purple.}
{120}{}{Amarelo. This will make Green.}
{121}{}{Claro. This will make Azul.}
{122}{}{Vermelho. This, you know, will make jet, an habit-forming amphetamine-like chem… if you get the correct
 dosages.}
{123}{}{Amarelo. Before you mix it, you calculate the solution in your head. You know that it will make
 nitroglycerine, an explosive.}
{124}{}{Claro. This will make a toxic chemical that is good for nothing but mimicking the effects of
 radiation.}
{125}{}{Beba.}
{126}{}{Pare agora.}

{127}{}{Você seleciona o amarelo. Com o que você deseja misturar?}
{128}{}{Azul. This will make Green.}
{129}{}{Vermelho. This will make Orange.}
{130}{}{Claro. This will make Amarelo.}
{131}{}{Beba.}
{132}{}{Azul. Before you mix it, you calculate the solution in your head. You know that it will make
 nitroglycerine, an explosive.}
{133}{}{Amarelo. Your scientific eye realizes this will, if successfully mixed, make hydrochloric acid.}
{134}{}{Claro. You know that this will create a weak poison if you continue. }
{135}{}{Pare agora.}

{136}{}{Você seleciona o líquido transparente. Com o que você deseja misturar?}
{137}{}{Azul, para fazer azul.}
{138}{}{Vermelho, para fazer vermelho.}
{139}{}{Amarelo, para amarelar.}
{140}{}{Beba.}
{141}{}{Amarelo. You know that this will create a weak poison if you continue. }
{142}{}{Azul. This will make a toxic chemical that is good for nothing but mimicking the effects of
 radiation.}
{143}{}{Vermelho. Your trained eye knows that this will make a powerful vitamin… but only if you measure
 the correct amounts.}
{144}{}{Pare agora.}

{145}{}{Você conseguiu criar um líquido roxo interessante. O que você quer fazer com isso?}
{146}{}{Beba.}
{147}{}{Coloque-o no meu inventário.}

{148}{}{Hmmm. Uma cor laranja interessante. O que você vai fazer com isso?}
{149}{}{Beba.}
{150}{}{Coloque-o no meu inventário.}

{151}{}{Uma cor vermelha forte. E agora?}
{152}{}{Beba.}
{153}{}{Coloque-o no meu inventário.}

{154}{}{Uma sombra doentia de resultados verdes. E agora?}
{155}{}{Beba.}
{156}{}{Coloque-o fora.}

{157}{}{Esta é uma sombra interessante de azul. O que você vai fazer?}
{158}{}{Beba.}
{159}{}{Salve para mais tarde.}

{160}{}{Este amarelo parece urina e cheira pior. O que você vai fazer?}
{161}{}{Beba.}
{162}{}{Salve isso. Pode ser útil.}

{163}{}{Ahh, um doce sucesso. Você fabricou jato. Você poderia ser muito popular em New Reno com isso.
 O que você vai fazer com isso?}
{164}{}{Beba.}
{165}{}{Salve-o para usar em alguma seiva desavisada.}

{166}{}{Uh oh! Você criou algumas estranhas fumos tóxicos! Você percebeu isso e você está fora do chão. Você
 parece merda.}
{167}{}{-feito-}

{168}{}{Essa coisa parece potente. O que você vai fazer com isso?}
{169}{}{Beba.}
{170}{}{Salve para mais tarde.}

{171}{}{Ah não! Você misturou muito forte! Come através da garrafa e na sua mão! Ouch!}

{172}{}{Você criou com sucesso uma fórmula explosiva!}
{173}{}{Beba.}
{174}{}{Coloque-o no meu inventário.}

{175}{}{Um jiggle aqui, um joggle lá, e ... uh-oh ... BOOM!}

{176}{}{Ah não! Seu idiota! Você apenas engoliu uma fórmula explosiva!}

{177}{}{Você se sente um pouco engraçado. Não, você se sente muito engraçado. Na verdade, você sente que o seu coração é
 acelerando e o mundo está abrandando e você não sabe o que está acontecendo e alguém não pode ajudar
 você porque você não sabe o que é isso, oh, não olhe para fora! AAAAAAH! VOCÊ ESTÁ FREAKING OUT !!!}

{178}{}{Você faz uma careta com o gosto e então percebe que está queimando você todo o caminho para baixo. Ouch. OUCH.
 OUCH !! Está quebrando o seu interior!}

{179}{}{É um pouco calcada, mas você conseguiu engasgar. Curiosamente, você se sente um pouco melhor agora.}

{180}{}{Ahh, o que diabos. Apesar da aparência, você derruba a bebida desagradável. Você começa imediatamente
 cuspir e engasgar. Você foi irradiado!}
{181}{}{-fim-}

{182}{}{Bem ... tudo bem. Rememorando as coisas que você bebeu quando criança, você inclina o
 Retorne e deixe fluir. Seu estômago aninha enquanto o fluido o atinge. Você sente que você apenas
 foi picado por um radscorpion.}

{183}{}{Ei, parece água, então deve ser tão bom, hein? Assim que as coisas atingirem sua garganta,
 você percebe que cometeu um erro. Isso é QUEIMADURA. Você está sofrendo por um longo, longo tempo.}

{184}{}{Um pouquinho disso, um pouco disso ... espere um segundo ... porque é que a garrafa está fumando ... o que está indo?
 errado? AH NÃO! A garrafa explode no seu rosto!}

{185}{}{Você mistura as coisas juntas alegremente, esperando que você tenha criado a combinação certa de produtos químicos. Então
 Você se senta e espera por sua recompensa. E você espera. E você espera. O líquido se transforma em um sombrio e úmido
 Castanho. Está desperdiçado.}

{186}{}{Você conseguiu criar uma vitamina potente. O que você quer fazer com isso?}
{187}{}{Beba.}
{188}{}{Salve para mais tarde.}

{189}{}{Você criou uma toxina! Tudo certo! E agora?}
{190}{}{Beba.}
{191}{}{Salve para mais tarde.}

{192}{}{Você criou com sucesso uma fórmula que simula os efeitos do envenenamento por radiação. o que
 você gostaria de fazer isso?}
{193}{}{Beba.}
{194}{}{Coloque-o no meu inventário.}
