{100}{}{Você vê um homem de aspecto amável e magro.}
{101}{}{Você vê Chad, o caravaneiro.}
{102}{}{Você vê um homem magro que usa um sorriso como um escudo. Ele usa roupas indescritíveis e carrega
 Ele mesmo como se soubesse o que estava fazendo.}

{120}{}{Howdy, amigo! O que posso fazer para você?}
{121}{}{Mais perguntas? Vou ver o que posso fazer por respostas.}
{122}{}{Deecer Deer!}
{123}{}{Você quem?}
{124}{}{Marcus perguntou algumas perguntas sobre você.}
{125}{}{Há provas suficientes de que você estava roubando dinheiro que deveria ir para Broken Hills
 que você pode ser preso. Você irá cair.}
{126}{}{Há provas suficientes de que você estava roubando dinheiro que deveria ir para Broken Hills
 que você pode ser preso. Corte-me por US $ 1000 e eu vou garantir que você possa fugir da cidade.}
{127}{}{Quem é Você?}
{128}{}{Conte-me sobre este lugar.}
{129}{}{Nada. Tchau.}

{130}{}{Veja o que a terra destruiu foi arrastada! Desculpe, amigo, não posso ajudá-lo.}
{131}{}{Doobye!}

{132}{}{Eu sou o Chade.}
{133}{}{Olha, estou muito ocupado. Por favor, procure alguém para incomodar.}
{134}{}{Eu sou o mestre da caravana da cidade. Eu cuido do negócio no outro lado do comércio
 rotas. Hoje em dia, estou focando principalmente no Gecko.}
{135}{}{D'okay!}
{136}{}{Gostaria de conseguir um emprego com você.}
{137}{}{Parece emocionante.}
{138}{}{Parece chato.}
{139}{}{Eu tenho mais perguntas.}
{140}{}{Obrigado. Tchau.}

{141}{}{Conte-te sobre Broken Hills? Bem ... mudei-me alguns anos atrás. Obteve um emprego com Bill -
 Esse é o Outfitter - e foi até onde estou agora. Eu informo a Marcus e ao Bill, mas eu sou
 responsável pelo sustento da cidade.}
{142}{}{Eu tenho mais perguntas.}
{143}{}{Tchau.}

{156}{}{Fale com o Bill. Ele irá ajudá-lo.}
{157}{}{Eu tenho mais perguntas.}
{158}{}{Obrigado. Tchau.}

{159}{}{Sim é. Você não pensaria, mas eu viajo e vejo o mundo ... e eu sinto que eu
 Contribua para a cidade aqui. É uma boa vida.}
{160}{}{Parece bom. Eu gostaria de um trabalho assim.}
{161}{}{Na verdade, isso parece muito chato.}
{162}{}{Eu tenho mais perguntas.}
{163}{}{Tchau.}

{164}{}{Provavelmente muito mais emocionante do que o que você faz com sua vida, jerkoff.}
{165}{}{Yeah, whatever. Eu tenho mais perguntas.}
{166}{}{Ha ha ha ha! Certo. Veja você, perdedor.}

{167}{}{Você pagará por algum dia, você coloca.}

{168}{}{Saia da minha vista, seu idiota.}

{169}{}{Você realmente abriu essa caravana, meu amigo. Muito pelo seu dinheiro.}
{170}{}{Você certamente ferrou o cachorrinho naquela caravana, meu amigo. Boa sorte alguma vez recebendo outro de Broken Hills.}
{171}{}{Bom trabalho naquela caravana. Aqui estão os seus $ 200.}

{172}{}{Saia daqui. Sua ajuda não é mais desejada.}

{173}{}{Mantenha os olhos abertos.}
{174}{}{Vou ver suas costas.}
{175}{}{Não deixe que os bastardos se esgueirem para você.}
