{100}{}{Você vê um homem preocupado.}
{101}{}{Você vê Dan, o cônjuge preocupado.}
{102}{}{Você vê um homem bem vestido, cujo rosto parece estar à beira da histeria.}
{103}{}{Quem é Você? O que você está fazendo na minha casa?}
{104}{}{Ack? Oop?}
{105}{}{Eu estou}
{106}{}{Ninguém é importante.}
{107}{}{Eu estouhere to rob you.}
{108}{}{Nada. Ninguém. Tchau.}
{109}{}{Não na minha casa, por favor. Há uma rua de onde você pode dormir e fazer o que quer que seja você, as pessoas "especiais" fazem.}
{110}{}{Thppt!}
{111}{}{Ótimo ótimo. Prazer em conhecê-lo. [Ele parece distraído.] Ei, olha ... você é um tipo de aventura, certo?}
{112}{}{Sim.}
{113}{}{Você não reconhece o Escolhido?}
{114}{}{Não.}
{115}{}{Qual negócio é seu?}
{116}{}{A razão pela qual eu pergunto, você vê, é porque minha esposa está perdendo. Não sei onde ela está. Ela já se foi há dias. Perguntei pela cidade, e ninguém a viu. Você pode encontrá-la para mim?}
{117}{}{O que há para mim?}
{118}{}{Eu vou olhar ao redor. Como ela se parece?}
{119}{}{Nope. Eu estoubusy.}
{120}{}{Eu posso dar-lhe US $ 500. Essa é minha economia de vida.}
{121}{}{Isso é bom o suficiente. Eu vou fazer isso.}
{122}{}{Não. Não pode fazê-lo.}
{123}{}{Por favor. Por favor. Minha esposa ... ela é tudo para mim. Por favor.}
{124}{}{Eu disse não!}
{125}{}{Bem. Tudo bem, pare de me incomodar.}
{126}{}{Aqui está o dinheiro. Agora, por favor, POR FAVOR ... encontre minha esposa e me diga onde ela está. Talvez ela tenha sido arruada com outra pessoa, talvez ela tenha me deixado ... mas eu só preciso saber.}
{127}{}{Você entendeu, amigo. Como ela se parece?}
{128}{}{Coisa certa. Vou fazer o meu melhor.}
{129}{}{:: ele soluce incontrolavelmente por alguns instantes :: Muito bem. Vá embora. E perceber que você quebrou meu coração.}
{130}{}{Veja você, perdedor.}
{131}{}{Ela é loira, sexy e tem a voz de canto mais incrível ... A última vez que vi ela andou por essa área. Ela não gostava de mutantes ou ghouls, então ela não teria estado perto de nenhum deles. Ninguém sabe para onde ela foi. É como se ela tivesse desaparecido.}
{132}{}{Isso deve ser suficiente.}
{133}{}{Bem? Você a encontrou? Meu coração bate com cada momento.}
{134}{}{Desculpe, amigo, ainda está olhando.}
{135}{}{Sim, eu a encontrei.}
{136}{}{Não, ainda não. Eu continuarei olhando.}
{137}{}{Oh, meu coração dolorido. Por favor, deixe-me saber quando você a encontra.}
{138}{}{Claro, coisa certa.}
{139}{}{Actually, Eu estounot going to look for her anymore.}
{140}{}{Você a encontrou? :: seus olhos se iluminam :: Onde?}
{141}{}{Ela era uma bela e sem pernas?}
{142}{}{I found a group of dead people in the tunnels below the city. She was one of them. Eu estousorry.}
{143}{}{O que? Não! Ela tinha ótimas pernas!}
{144}{}{Oh. Certo. Bem, ela não tem grandes pernas agora. Ela realmente ficou selvagem, e suas pernas estão desligadas. Ela está totalmente morta, e ela sofreu antes de morrer.}
{145}{}{Right. Well, I think I found her in the tunnels below the city. She's dead. Eu estouvery sorry.}
{146}{}{Obrigado por me dizer. Eu acho que tenho que ir chorar.}
{147}{}{Sim, você vai chorar, seu perdedor de pensamentos.}
{148}{}{Desculpe, amigo.}
{149}{}{Eu te odeio! Todo mundo odeia você! Morra! ::soluço::}
{150}{}{Encontrei uma carta sobre sua esposa. Isso indica que ela pode ter sido parte de uma conspiração para matar os mutantes em Broken Hills.}
{151}{}{Meu Deus! Eu ... Eu não posso acreditar nisso ... Não é ... [Suspere profundamente]. Suponho que seja verdade. Ela parecia
 Para odiar cada mutante e ghoul com quem entrou em contato. Eu nunca soube o porquê.}
{152}{}{Seja como for, você pode querer considerar que os assassinatos podem não parar com sua esposa. Se ela estava implicada, você também pode estar.}
{153}{}{Você não quer dizer que minha vida também está em perigo? Oh céus. Tu podes estar certo. Estive ouvindo ruídos fora
 A casa à noite. Sussurra e mistura.}
{154}{}{Pode ser uma boa idéia sair. Tome cuidado. Boa sorte.}
{155}{}{Thanks so much for your help. Eu estounot staying here any longer than I have to.}
{156}{}{Você informou Dan do assassinato de sua esposa.}
{157}{}{.}
