{100}{}{Você vê um velho idoso com um casaco de médico.}
{101}{}{Você vê Doc Holliday.}
{102}{}{Você vê um velho velhote em um casaco de medico um pouco sangrento. O homem irradia um ar de
 conhecimento. Ele também parece um pouco doentio.}

{103}{}{:: wheeze :: Oi lá. Eu sou Doc Holliday. Como posso ajudá-lo?}
{104}{}{Agora, o que você quer?}
{105}{}{Ouchie!}
{106}{}{Estou machucado e preciso de cura.}
{107}{}{Um dos meus amigos está ferido e precisa de cura.}
{108}{}{O que você faz aqui?}
{109}{}{Conte-me sobre a cidade.}
{110}{}{Alguma fofoca?}
{111}{}{Apenas me venda alguns estimpacks.}

{112}{}{Esqueça. Desculpa.}

{113}{}{Deixe-me dar uma olhada nisso. Posso curar você, mas isso vai custar.}
{114}{}{Quantos?}
{115}{}{Esqueça.}

{116}{}{Sim, posso curar isso ... :: wheeze :: por um preço.}
{117}{}{Quantos?}
{118}{}{Esqueça.}

{119}{}{O que eu faço aqui? Você está no hospital. Estou vestindo um casaco de médico. Estou coberto de sangue.
 Há coisas afiadas e pontiagudas que se encontram ao redor. Ou eu sou um assassino bem-sucedido ou um médico justo. Faça sua escolha.}
{120}{}{Acho que posso chamá-lo de médico.}
{121}{}{Não fique comigo, velho.}
{122}{}{Um bom médico não estaria recebendo sangue por completo.}

{123}{}{Vamos ver. Nasci aqui há anos. Place estava apenas começando. Eu peguei quando eu era um
 adolescente e trabalhada ao redor do lugar por um tempo. Conheceu uma mulher. Se apaixonou. Ela morreu de doença. Eu
 decidiu então que eu iria me tornar um médico.}
{124}{}{Sim? Continue.}
{125}{}{Estávamos falando sobre Broken Hills, não sua história.}

{126}{}{Você ficaria surpreso com o que as pessoas dizem quando estão com dor.}
{127}{}{Oh sim? Como o quê?}
{128}{}{Eu mudei de ideia. Prefiro fazer outras perguntas.}

{129}{}{Isso custará US $ 50.}
{130}{}{Eu vou pagar.}
{131}{}{Esqueça.}

{132}{}{Por feridas assim, você estará perdendo $ 100.}
{133}{}{Eu vou pagar.}
{134}{}{Esqueça.}

{135}{}{Parece que deve ter dano. Indo ferir sua carteira também ... $ 150.}
{136}{}{Eu vou pagar.}
{137}{}{Esqueça.}

{138}{}{Ouch! Você vai precisar de alguns remendos sérios. $ 200.}
{139}{}{Eu vou pagar.}
{140}{}{Esqueça.}

{141}{}{Whew ... amigo, isso vai te machucar muito. $ 300 e você é bom como novo.}
{142}{}{Eu vou pagar.}
{143}{}{Esqueça.}

{144}{}{Ele deveria estar bem após uma pequena ajuda de mim ... :: wheeze :: a melodia de $ 50.}
{145}{}{Eu vou pagar.}
{146}{}{Esqueça.}

{147}{}{Você está vendo alguma ação? Lembro-me de volta quando eu era um pequeno espirito. Tem muitos buracos
 em mim também. Esta desvantagem custará US $ 100.}
{148}{}{Eu vou pagar.}
{149}{}{Esqueça.}

{150}{}{Kid, você cuida dos seus amigos? :: tosse :: Se você vai cuidar deste amigo,
 você precisará pagar US $ 150.}
{151}{}{Eu vou pagar.}
{152}{}{Esqueça.}

{153}{}{Você deve ser muito bom para inspirar lealdade como essa dos seus amigos. Espero que você esteja bem ...
porque isso vai custar :: tough :: $ 200.}
{154}{}{Eu vou pagar.}
{155}{}{Esqueça.}

{156}{}{Ouch! Eu precisarei colocar um elenco sobre isso ou algo assim. Para o meu extenso conhecimento médico, você
 se separe com US $ 300.}
{157}{}{Eu vou pagar.}
{158}{}{Esqueça.}

{159}{}{Amigo, você não tem esse tipo de dinheiro. Posso vender alguns estimpacks se quiser, mas com
 A cura que você está procurando, você não pode pagar o que eu posso dar ao luxo de lhe dar.}
{160}{}{Me dê o stimpacks.}
{161}{}{Não, obrigado.}

{162}{}{Foi um prazer.}
{163}{}{Obrigado.}

{164}{}{Isso não é aceitável.}
{165}{}{Que tal agora?}
{166}{}{É tudo o que quero oferecer. Tanto tempo.}

{167}{}{:: wheeze :: Você está ferido? Deixe-me dar uma olhada nisso. Você tem dinheiro?}
{168}{}{Dinheiro?}
{169}{}{'Es!}

{170}{}{Deixe-me dar uma olhada na sua bolsa. (Ele olha através da sua bolsa e leva algo) Ok. Agora isso
 pode doer um pouco.}
{171}{}{Ferido?}

{172}{}{Sim. Agora ... Lá! Foram realizadas. Boa sorte para você, ok? Não se machuque!}
{173}{}{Tanques!}

{174}{}{Está certo. Eu sou um médico. É bom ver que a inteligência está viva e bem no pós-nuclear
 mundo.}
{175}{}{Ha! E está dando uma volta dentro do corpo de um homem de 70 anos!}
{176}{}{Eu não quero tirar nada de você, velho.}
{177}{}{Ummm ... Sim. Eu tive mais perguntas.}
{178}{}{Tchau.}

{179}{}{Ameaça o único médico da cidade. Bem pensado. :: tosse :: amigo, se você quiser alguma coisa, você
 pode pedir educadamente. Caso contrário, saia do meu hospital.}
{180}{}{Morda-me, homem velho. Prepare-se para morrer.}
{181}{}{Sim. Tanto faz.}
{182}{}{Desculpa. Dia ruim.}
{183}{}{Eu estava apenas brincando.}

{184}{}{Stripling, você tem muito a aprender sobre o respeito.}
{185}{}{Criança, você tem muito a aprender sobre o humor.}
{186}{}{Sim, tudo bem.}
{187}{}{Ok, você me irritou. Agora você precisará se curar.}

{188}{}{(Você pode ver um riso nos olhos dele atrás dos óculos.) Não veja muitos outros
 lugares estes dias. Os jovens do mundo, por exemplo ...}
{189}{}{Ei!}
{190}{}{Velho, não me empurre.}
{191}{}{... são o repositório do que os anciãos já conheceram ...}
{192}{}{Sim, sim, sim ... tenho que ir.}

{193}{}{Relaxe, criança. Apenas brincando com você.}
{194}{}{Sim, eu sei. Então ... ummm ...}

{195}{}{... e o que nos recusamos a contar pequenos bastardos! (ele explode rindo) Kid, a próxima vez
 Você precisa me ver por alguma ajuda médica, está na casa.}
{196}{}{Tive algumas outras questões.}
{197}{}{Obrigado. I’ll see you around.}

{198}{}{Você está machucado? Deixe-me consertar isso.}
{199}{}{Umm ...}
{200}{}{Obrigado. See ya!}

{201}{}{Quem está ferido? Oh, apenas alinhe e eu cuidarei muito de você.}
{202}{}{Mais uma coisa…}
{203}{}{Obrigado! Tchau!}

{204}{}{Surpreendentemente, pouco. Desculpe, mas quando estou concentrado em curar alguém, eu costumo pagar
 atenção aos seus segredos mais íntimos.}
{205}{}{Oh. Você responderá a mais perguntas?}

{206}{}{Então, viajei para São Francisco e estudei sob os chineses ... um velho cavalheiro por
 O nome do Sr. Fung me ensinou tudo o que sei sobre remédios. Ele também me ensinou alguma sabedoria.}
{207}{}{Então, o que aconteceu?}
{208}{}{E isso liga em Broken Hills como?}

{209}{}{Estou chegando a isso! Crianças hoje em dia ... tão impacientes.}
{210}{}{Desculpa. Continue.}
{211}{}{Isso é uma merda. Estou fora daqui.}

{212}{}{Então, eu voltei aqui e assisti Marcus construir a cidade a partir da calçada que eu lembro da minha
 Jovens para a "metrópole alargada" que você vê antes de você. Vi pessoas atraídas por promessas de
 riqueza. Eu vi pessoas crescerem e morrerem. Eu vi as correntes da história.}
{213}{}{Então, isso significa…}

{214}{}{Isso significa que não conheço a maioria das pessoas novas nos dias de hoje. A maioria das minhas memórias são apenas
 isso - memórias.}
{215}{}{Oh. Bem, obrigado pela história.}
{216}{}{Seu otário! Você me fez esperar tanto por nada?}

{217}{}{Não, obrigado por me ouvir divertir. Da próxima vez que você estiver aqui e precisar de cura, está na
 casa.}
{218}{}{Obrigado! Então de qualquer forma…}
{219}{}{Obrigado. So long!}

{220}{}{Sim. Espero que tenha valido a pena! (ele cackles)}
{221}{}{Não. Na verdade, não. Diga-me outra coisa.}
{222}{}{No. You shriveled old jerk. Tchau.}

{300}{}{Quem deseja que eu cure?}
{301}{}{Vic.}
{302}{}{Myron.}
{303}{}{Marcus.}
{304}{}{MacRae.}
{305}{}{Sulik.}
{306}{}{Lenny.}
{307}{}{Cyberdog.}
{308}{}{Doc.}
{309}{}{Goris.}
{310}{}{Davin.}
{311}{}{Miria.}
{312}{}{Robobrain.}
{313}{}{Deixa pra lá.}

{314}{}{Você está machucado? Deixe-me consertar isso. I'll take care of your companions too.}
{315}{}{Você está lá. Tudo melhor.}

{316}{}{[continuar]}
{400}{}{Comida de cachorro.}
{401}{}{K9.}
