{100}{}{Você vê uma pessoa entediada vestida com uma armadura de couro.}
{101}{}{Você vê (x), o guarda da caravana.}
{102}{}{Você vê uma pessoa empoeirada e entediada com uma armadura de couro. Do fedor bravo e confiante
 Caminhar, esta pessoa é claramente uma guarda de caravanas.}

{103}{}{Eu posso te ajudar com alguma coisa?}
{104}{}{Urg?}
{105}{}{Ny trabalhe aqui!}
{106}{}{Quem é Você?}
{107}{}{O que você pode me falar sobre o Chade?}

{108}{}{Não tenho paciência para os idiotas. Desculpe, amigo, mas você terá que encontrar outra pessoa para brincar.}
{109}{}{::farejar::}

{110}{}{Eu sou (x). Eu sou um dos guardas da caravana.}
{111}{}{O que você pode me falar sobre o Chade?}
{112}{}{Obrigado. Tchau.}

{113}{}{Chad é um bom cara. Tough, mas justo. Lavish com suas recompensas para aqueles de nós que trabalham bem.}
{114}{}{Quem é Você?}
{115}{}{Obrigado. Tchau.}

{116}{}{Obrigado. Não mesmo. Obrigado por aparar nossos bônus. As únicas pessoas que Chad estava doendo foram
 As pessoas com as quais trocamos; Ele estava nos ajudando, e você acabou com isso. Fracassado.}
{117}{}{Tchau.}

{118}{}{É o inimigo! Morrer!}
{119}{}{Oops.}
