{100}{}{Você vê uma pessoa vestida de armadura de couro preto, usando uma expressão sombria e carregando um poderoso
 arma de fogo.}
{101}{}{Entende}
{102}{}{Entendea caravan guard, covered in the dust of the trail and sweat of combat; you infer this
 to mean that the caravan routes are growing more dangerous these days.}

{103}{}{Ajudar você?}
{104}{}{Aggle também!}
{105}{}{Eu estou trabalhando?}
{106}{}{Sim, estou procurando o mestre da caravana.}
{107}{}{Eu queria saber se eu poderia fazer algumas perguntas sobre o Chadee.}
{108}{}{Quem é Você?}
{109}{}{Desculpe pelo Chadee. Quem é o novo chefe?}
{110}{}{Não, obrigado.}

{111}{}{Se você está procurando trabalho, você pode querer conversar com Bill, o cara lá dentro. Dentro. Ele
 pode entender você. Boa sorte!}
{112}{}{Duhhhh ...}

{113}{}{Isso seria}
{114}{}{Sim.}
{115}{}{Não.}

{116}{}{Você recebeu perguntas, talvez eu tenha respostas. Whaddya quer saber?}
{117}{}{Como ele é?}
{118}{}{Pode ser confiado?}
{119}{}{Onde ele ganha dinheiro?}
{120}{}{Qual é a história dele?}
{121}{}{Esqueça. Até logo.}

{122}{}{Eu? Eu estou}

{123}{}{Você desculpa pelo Chade? Ha! Fez um bom lucro, não é? O novo chefe é}
{124}{}{Tchau.}

{125}{}{Nesse caso, você quer conversar com Bill, o Outfitter of Broken Hills. Ele pode conectá-lo.}
{126}{}{Obrigado.}

{127}{}{Tudo certo. Veja, então.}

{128}{}{Como ele é? Well, he’s friendly, but abrasive. He’s a good boss, and usually fair to us. He
 doesn’t treat us badly or anything, if that’s what you mean. Any more questions?}

{129}{}{Eu sempre assumi que ele tinha trazido com ele - e muito disso, nisso. Não é a
 tipo de coisa que você pergunta a um cara, você sabe. Mais alguma pergunta?}

{130}{}{Bem, ele é um pouco sombrio, acho ... mas, então, a maioria das pessoas nos dias de hoje. Alguma outra pergunta?}

{131}{}{Não tenho idéia do que é a história dele. Quero dizer, quase todos nós, guardas de caravanas, somos drifters
 Quem veio aqui para o trabalho. Imagine que ele é outro que teve que abandonar outro lugar com pressa. Qualquer
 mais perguntas?}

{132}{}{Porque eu sou o novo chefe, provavelmente sou a única pessoa aqui que não odeia você. o que
 posso fazer por você?}
{133}{}{Eu quero um emprego.}
{134}{}{Você esquenta o topo?}
{135}{}{Quando é a próxima caravana sair?}
{136}{}{Nada, obrigado.}

{137}{}{Fale com Bill, como sempre.}
{138}{}{OK.}

{139}{}{Depois do que aconteceu com o Chadee? Acho que não. Algo mais?}

{140}{}{Estava aqui. Aqui estão os seus $ 500. Se você quiser voltar, nós vamos no final do dia. Você vai
 Ganhe o dinheiro no caminho de volta, também, se você quiser. De uma forma ou de outra, porém, estamos saindo daí.}
{141}{}{Até mais.}

{142}{}{Você está pronto para sair?}

{143}{}{Obrigado. Here’s your $500. You want a new job, talk to Bill.}

{144}{}{Você é um perdedor doente! Você vai morrer agora!}
{145}{}{Umm ...}
{150}{}{, a guarda da caravana.}
{151}{}{. Sou um guarda para as caravanas de Bill. Algo mais?}
{152}{}{.}
{153}{}{. Deveria estar por aqui em algum lugar. Procurando um emprego?}
{154}{}{. Boa sorte trabalhando com ele. Empurrão.}

{200}{}{Chade}
{201}{}{Chocar}
{202}{}{Rígido}
{203}{}{Darin}
{204}{}{Michael}
{205}{}{Harry}
{206}{}{Jake}
{207}{}{Matt}
{208}{}{Ted}
{209}{}{Argila}
{210}{}{Scott}
{211}{}{Prentiss}
{212}{}{Eddie}
{213}{}{John}
{214}{}{Max}

{301}{}{Tawni}
{302}{}{Kim}
{303}{}{Urs}
{304}{}{Susan}
{305}{}{Cindy}
{306}{}{Jen}
{307}{}{Lisa}
{308}{}{Buffy}
{309}{}{Urze}
{310}{}{Cathy}
{311}{}{Lori}
{312}{}{Maria}
{313}{}{Julie}
{314}{}{Sarah}
