{100}{}{Você vê um homem gorduroso e suado.}
{101}{}{Você vê Eric.}
{102}{}{Você vê um homem gorduroso e suado. He looks quite miserable.}
{103}{}{Como essa cidade, precisava de mais sorte. Como * eu * precisava de mais.}
{104}{}{Entre já! Feche a porta atrás de você! Não deixe entrar as moscas!}
{105}{}{Dries? F-f-f!}
{106}{}{Tudo bem, tudo bem. Não há necessidade de gritar.}
{107}{}{Você está gritando comigo?}
{108}{}{Eu vou deixar todas as malditas moscas que eu quero. Fracassado.}
{109}{}{Certo. Tanto tempo.}
{110}{}{Feche a porta! Por favor! Vá embora e leve essas malditas moscas com você!}
{111}{}{D'okay!}
{112}{}{Desculpa. Estou apenas um pouco em vantagem. Todas essas malditas moscas e sem ar condicionado. Se eu tivesse um pouco mais de poder, eu seria capaz de agitá-los ... mas eu não.}
{113}{}{Quem é Você?}
{114}{}{Como você obtém o poder?}
{115}{}{Por que as moscas estão vindo aqui?}
{116}{}{Você poderia tentar banhar-se, você sabe.}
{117}{}{Boa sorte para você, amigo. Tanto tempo.}
{118}{}{Hmm. Que pena. Tanto tempo.}
{119}{}{Há uma estação geradora de energia no centro da cidade que controla o poder para a cidade. Se você pudesse ir lá e obter permissão para me dar um pouco mais de energia para o meu ar condicionado, eu ficaria grato.}
{120}{}{Quão grato? Dinheiro ou equipamento?}
{121}{}{Sim, vou fazer isso por você.}
{122}{}{Não tenho tempo. Talvez mais tarde.}
{123}{}{Você é louco? De jeito nenhum. Talvez você fique tão miserável que você morre. Faça um favor ao mundo.}
{124}{}{Eles vêm aqui porque, por algum motivo estranho, eu exalo os nutrientes da mosca. Meu corpo é rico em alimentos para eles, e essa transpiração só piora.}
{125}{}{Isso é simplesmente desagradável. Por que não tomar banho ou algo assim?}
{126}{}{Então, eu vou te fazer um favor matando você.}
{127}{}{Entendo. Isso é mais do que eu precisava saber. Adeus.}
{128}{}{Eu tentei isso. Eu tentei tudo. O único que mantém as moscas fora de mim é não suar ... e quando eu não tenho energia suficiente para me manter legal, não posso.}
{129}{}{Entendo. Tenho mais perguntas.}
{130}{}{Entendo. Adeus.}
{131}{}{Sim?}
{132}{}{Falei com Brian e ele disse que as rações de poder são tão apertadas que ele não pode permitir que você aumente sua participação.}
{133}{}{De onde vêm as moscas?}
{134}{}{Você tentou se banhar?}
{135}{}{Onde está o gerador de energia?}
{136}{}{Quem é Você?}
{137}{}{É muito melhor aqui. Confortável?}
{138}{}{Nada. Esqueça.}
{139}{}{Eu poderia arrumar um pouco para você se você fizesse isso. Não posso prometer muito, mas também não é um grande favor.}
{140}{}{Você conseguiu um acordo. Certifique-se de ter algo para mim quando eu conseguir o seu poder para você.}
{141}{}{Vou fazer isso de graça. Sem cobrança.}
{142}{}{Esqueça. Eu não quero fazer isso.}
{143}{}{Deixe-me pensar sobre isso.}
{144}{}{Não posso te dizer o quanto estou agradecido por você. Por favor, deixe-me saber, assim que você terminar, para que eu possa subir o ar condicionado e tomar um banho.}
{145}{}{Vai fazer. Tive algumas outras questões.}
{146}{}{Vai fazer. Tanto tempo.}
{147}{}{Por favor, não espere muito por isso ... Estou ficando realmente cansado de todas essas moscas.}
{148}{}{Certo. Tive algumas outras questões.}
{149}{}{Certo. Eu aviso você.}
{150}{}{Muito obrigado por sua compaixão. Isso é sarcasmo, por sinal, no caso de você não ter notado. Saia da minha casa.}
{151}{}{Por que não ir para o inferno e morrer?}
{152}{}{Por enquanto, garoto voador!}
{153}{}{O gerador de energia está à sua esquerda quando você entra em Broken Hills do mundo exterior. É administrado por um cara chamado Brian, um filho de puta preguiçoso que faz o menor trabalho possível.}
{154}{}{Parece um verdadeiro trabalho. Obrigado. Tenho mais perguntas.}
{155}{}{Entendo. Bem isso é tudo por agora.}
{156}{}{Eu sou Eric. Eu costumava dirigir o hotel na cidade, mas eu tinha que vendê-lo por causa do problema da minha mosca. Eu também corri a taberna, mas também tive que sair disso, pelo mesmo motivo. Finalmente, costumava executar o gerador, mas as moscas continuavam entrando nisso.}
{157}{}{Isso é uma grande quantidade de empregos. Tenho mais perguntas.}
{158}{}{Entendo. Tanto tempo!}
{159}{}{Ele disse isso, ele? Bem, você diz a ele que o gerador é alimentado com urânio e que a minúscula quantidade de energia que eu exijo apenas se registraria no gerador. E diga a ele que eu quero meu poder!}
{160}{}{Vai fazer! Bom discurso!}
{161}{}{Eu digo a ele. Eu tenho outras perguntas.}
{162}{}{Certo. Tchau.}
{163}{}{Você terminou com o gerador? Muito obrigado, tanto. Não consigo nem começar a descrever o quão grato eu sou.}
{164}{}{A maneira comum de agradecer é através de brindes de dinheiro ou equipamentos.}
{165}{}{Não, então. Estou bem com seus agradecimentos.}
{166}{}{Francis the mutant tem um punho de poder. Ele continua apostando em concursos de luta armada. O problema é ser mais forte que ele. Se você está interessado, posso dar-lhe algumas pílulas que devem dar-lhe a vantagem sobre ele.}
{167}{}{Coisa certa.}
{168}{}{Prefiro ter dinheiro, se você tiver.}
{169}{}{Eu não quero uma recompensa.}
{170}{}{Essas pílulas são chamadas buffouts. Eles aumentarão sua força, mas sua mente sofrerá um pouco. Não tome muitos ou você pode ficar viciado. Boa sorte com o punho!}
{171}{}{Obrigado! Tanto tempo!}
{172}{}{Você acha que pode me ajudar com o problema da minha mosca? Eu ficaria muito grato.}
{173}{}{Quão grato?}
{174}{}{Coisa certa.}
{175}{}{Deixe-me pensar sobre isso.}
{176}{}{De jeito nenhum.}
{177}{}{Aqui está todo o dinheiro que eu tenho ... $ 150. Obrigado.}
{178}{}{Não, obrigado. Tanto tempo.}
{179}{}{Então estou duplamente grato. Oh ... ouço que você está procurando por um GECK. Tente perguntar ao redor na NCR. É para o sul.}
{180}{}{Obrigado! Tchau!}
{181}{}{Ai sim. As moscas diminuíram, o ar esfriou e eu estou menos suado. Melhor negócio para todos ao redor!}
{182}{}{Eu direi. Bom, isso é tudo. Tanto tempo!}
{183}{}{Você vê um homem gorduroso e suado. He looks quite comfortable.}
