{100}{}{Você vê um homem esfarrapado, sujo e irritado.}
{101}{}{Você vê Franc, um dos inimigos mutantes locais.}
{102}{}{Você vê um homem desalinhado, sujo e irritado, que parece que ele não apreciaria mais do que colocar um
 bala na cabeça de alguém. Ele se carrega como um animal rabioso.}

{103}{}{Whadda você quer?}
{104}{}{Aggggg! :: babar ::}
{105}{}{Você! Eu! Ir!}
{106}{}{Quem é Você?}
{107}{}{Por que você está preso?}
{108}{}{O que você pode me falar sobre esse lugar?}
{109}{}{O que você pode me falar sobre Marcus?}

{110}{}{Não tenho idéia do que você está dizendo, freak. Saia da minha frente.}
{111}{}{Oooooh ...}

{112}{}{Eu sou franco. Eu perguntaria quem você é, mas eu não ligo.}
{113}{}{Oh, um cara duro, eh?}
{114}{}{Tudo bem. Eu também não me importo com quem você é.}
{115}{}{Tanto faz. Tchau.}

{116}{}{Estou aqui porque o "homem" que dirige esse lugar por trás das cenas não confia em mim e o que
 Estou dizendo às pessoas desta cidade. Estou dando a verdade sobre mutantes e Marcus não gosta disso.
 Estou sendo silenciado por minhas crenças.}
{117}{}{Soa severo.}
{118}{}{Ou talvez seja porque você é um odiador que está tentando assustar as pessoas em tirar pessoas
 quem é diferente?}
{119}{}{Sim, isso é interessante. O que você pode me falar sobre Broken Hills?}
{120}{}{Suuuure. O que você pode me falar sobre Marcus?}
{121}{}{Oookay. Tchau.}

{122}{}{O lugar costumava ser um paraíso. Então os mutantes vieram e transformaram-na em um shithole. Agora somos todos
 Esperava esquecer o passado e viver com eles. Eu não! Viva livre ou morra!}
{123}{}{Not quite what I was looking for, but thanks anyway. O que você pode me falar sobre Marcus?}
{124}{}{Umm, está bem. Tanto tempo.}

{125}{}{Marcus conta a todos que ajudou a descobrir a cidade. Ele não fez. Foram os humanos aqui primeiro, e ele
 e sua multidão se mudou e assumiu e esperava que qualquer outra pessoa se inclinasse e deixasse os mutantes darem
 para eles. Marcus é o líder do circo inteiro.}
{126}{}{Você está realmente louco, eu acho.}
{127}{}{Malditos mutantes. Assim como pensei.}

{128}{}{Sim, sou um cara duro. Se eu não estivesse na prisão, eu provaria isso para você. Você acha que é difícil?
 Acha que pode provar isso, perdedor?}
{129}{}{Claro.}
{130}{}{Eu não tenho nada para provar a você, lowlife.}

{131}{}{Saia da minha vista, seu idiota! Eu mataria você se eu tivesse a chance!}
{132}{}{Tchau.}

{133}{}{A lei aqui está baseada no amor mutante. Você odeia mutantes?}
{134}{}{Sim.}
{135}{}{Não.}

{136}{}{Sim? Então, fale com Jacob, o químico. Eu vou pegar você mais tarde.}

{137}{}{Mutie-lover! Saia daqui! Eu não quero respirar o mesmo ar que você!}

{138}{}{Você novamente? O que você quer?}
{139}{}{Conte-me sobre Broken Hills.}
{140}{}{Me fale sobre Marcus.}
{141}{}{Por que você está preso?}

{142}{}{Você falou com Jacob? O que você está esperando? Retire-nos daqui!}

{143}{}{Obrigado por nos levar para lá. Muito ruim, não conseguimos matar ninguém antes de sairmos.}

{144}{}{Ha! Killin 'essas mutile quase valia a pena estar no slammer!}

{145}{}{Basta configurar o interruptor explosivo, e nós faremos o resto.}

{146}{}{Ótimo trabalho, amigo. Nós estamos saindo da cidade. Você provavelmente também deve. Tanto tempo!}

{147}{}{Você foi e ferrou tudo isso! Você deve morrer agora, amigo!}

{148}{}{Vamos sair daqui.}

{149}{}{Nutting. ByeTchau.}
{150}{}{Nevermind. Tchau.}

{151}{}{Isso não é justiça. Você deve se envergonhar de si mesmo.}

{152}{}{Obrigado pela sua ajuda, amigo. Vamos falar com Jacob e Aileen.}

{153}{}{Você executou o jailbreak com sucesso.}

{154}{}{Obrigado pela sua ajuda no slammer, estranho.}
{155}{}{Sem problemas.}
