{100}{}{Você vê um super-mutante poderosamente construído. Ele parece entediado.}
{101}{}{Você vê Francis, o lutador de braço mutante.}
{102}{}{Você vê um super-mutante poderosamente construído. Ele está vestido com couro preto e o tédio está escrito
 em seu rosto.}

{103}{}{Ajudá-lo com algo?}
{104}{}{Ook! Ook! Eep orp ook!}
{105}{}{Hoo você?}
{106}{}{Ei amigo. Quem é Você?}
{107}{}{O que há para fazer neste lugar?}
{108}{}{Você está com um braço, Sr. Iron-Pecs?}

{109}{}{Pal, não tenho ideia do que você está tentando dizer. Desculpa.}

{110}{}{Sou Francis. Eu sou o campeão de braço da cidade. Tenho uma aposta em corrida que ninguém pode
 me bata.}
{111}{}{Sou Francis, lembra? O campeão do braço-wrestling da cidade? Tenho uma aposta em corrida que ninguém pode
 me bata.}
{112}{}{Eu te venci! Eu! Eu!}
{113}{}{Aposto que você não teve muitos compradores.}
{114}{}{Aposto que posso.}
{115}{}{Que bom, hein?}

{116}{}{O que fazer na cidade? Bem, vamos ver ... há o salão, as minas, a refinaria e o
 caravana. Não temos muito tempo para se divertir aqui, e o que fazemos, geralmente devemos beber.
 Além disso, trabalhamos em relações humanas / mutantes.}
{117}{}{Que legal.}
{118}{}{Tudo bem, obrigado.}
{119}{}{Relações humanos / mutantes? O que você quer dizer?}

{120}{}{Eu estou sempre pronto. Você quer ir?}
{121}{}{Não, só estou pedindo minha saúde.}
{122}{}{Umm, não.}
{123}{}{Claro que eu faço.}

{124}{}{[ele te dimensiona e mede sua musculatura] Eu não penso assim, amigo. Só seria um desperdício do meu tempo. Não me chateies.}
{125}{}{Você acha que pode me levar, hein? Tudo certo. Você ganha, você consegue esse punho de poder. Eu ganho e você é
 meu gimp para uma noite. Você quer fazer isso agora, ou você gostaria de levar algum tempo para descansar?}
{126}{}{Descansar! Descansar!}
{127}{}{Agora. Nós agora!}
{128}{}{Eu gostaria de descansar primeiro.}
{129}{}{Eu sou um jogo para isso agora.}
{130}{}{Eu mudei de ideia. Eu não quero lutar contra você.}

{131}{}{Essa é a verdade. Parece que não há ninguém neste deserto perdido por Deus que irá por isso,
 ou.}
{132}{}{Pena disso. Se eu encontrar alguém, eu os enviarei para você. Tchau.}
{133}{}{Só porque você é forte não significa que você é inteligente, amigo. Lembre-se disso.}

{134}{}{Buddy, se você não gosta disso, há um mundo inteiro lá fora.}

{135}{}{Sem problemas. Qualquer outra coisa que você precisa, sinta-se à vontade para perguntar a Phil o barman ou outra pessoa.}

{136}{}{Buddy, você quer armar ou não? Não tenho tempo para desperdiçar com comentários curiosos
 e covardes.}
{137}{}{Sim claro. Vamos fazer isso.}
{138}{}{Não, eu não penso assim.}

{139}{}{Você vem de volta e me encontra quando estiver pronto, então. Eu deveria estar por perto.}

{140}{}{Saia daqui antes que meu cérebro estupido decida bater seu rosto.}

{141}{}{Saindo, eh? Covarde. Eu pensei tanto.}
{142}{}{Tudo bem, tudo bem, eu vou fazer isso.}
{143}{}{Tanto faz. Até mais.}

{144}{}{Bem, amigo, é a primeira vez que alguém me espancou em um concurso justo. Você ganha. Pegue isso.
 Bem feito.}
{145}{}{Você perdeu. Não é uma grande surpresa. Hora de chegar em casa comigo.}

{146}{}{Eu lhe digo o que, amigo, eu não vi um braço assim em séculos. Você usa esse direito, você irá
 longe. Aproveite a luva!}

{147}{}{Você não conseguiu o suficiente de mim antes? Você quer tentar novamente? O mesmo negócio?}
{148}{}{Sim, vamos fazer isso.}
{149}{}{Não, desculpe.}

{150}{}{Já ouvi sobre você. Eu não associo a escória.}

{151}{}{Buddy, obrigado por pisar para salvar nossa cidade. Deixe eu te pagar uma bebida.}
{152}{}{Howdy, herói!}

{153}{}{Escumalha! Morrer!}

{154}{}{Você pode ter percebido que conseguimos mutantes e humanos na cidade. Estamos tentando trabalhar assim
 que todos vivamos em paz. Infelizmente, há alguns que querem destruir isso. Nosso líder, Marcus,
 ajudou a encontrar a cidade. Você quer ouvir mais?}
{155}{}{Sim, me conte mais.}
{156}{}{Não, na verdade não.}
{157}{}{Francamente, acho que você mutantes são escória e esses humanos são traidores por trabalhar com você.}

{158}{}{Às vezes eu me preocupo com as pessoas aqui ... é muito difícil para alguns deles superar suas
 medo. A palavra tem que há uma tempestade de merda descendo o pique - mas isso pode ser apenas um boato.}
{159}{}{Obrigado. Tchau.}

{160}{}{Tudo certo. Bem, se você precisar de mais informações, você sabe onde me encontrar.}
{161}{}{Sure. Obrigado. Tchau.}

{162}{}{Mesmo? Essa é uma atitude fascinante. Muito ruim, não esmagamos sua aldeia quando controlamos
 a terra do desperdício. Saia da minha vista, verme.}
{200}{}{-feito-}
{201}{}{Tchau.}
{202}{}{Obrigado. Tchau.}
{203}{}{-Mais-}
{204}{}{Sure. Obrigado. Tchau.}

{300}{}{Pal, não acho que você sabe como usar o que tenho para oferecer. Volte quando tiver um
 um pouco mais de experiência no seu cinto.}
{301}{}{Você vê um super-mutante poderosamente construído. Ele está vestido com couro preto e o tédio está escrito
 em seu rosto. Ele parece ter uma enorme luva de algum tipo afastando sua bolsa.}
{302}{}{Você se sente dolorido. Você parece estar carregando uma lembrança de sua visita com Francis.}

{400}{}{Urrggghh!}
{401}{}{Arrrrr!}
{402}{}{Aiiigggggg.}
{403}{}{Rnnrnrnnrrr.}
{404}{}{Hagggahhhaaaggga.}
{405}{}{Hominahominahomina.}
{406}{}{Eeeeeccchhhh.}
{407}{}{Grunhido!}
{408}{}{Gemido!}
{409}{}{Ouchie!}
{410}{}{Ow! Meu braço!}
{411}{}{Ha ha! Peguei vocês!}

{500}{}{Por cima, Francis! Acima do topo!}
{501}{}{Cara, é isso que eu chamo de corrida de ARMs! Hahahah!}
{502}{}{Geez, vocês deveriam se juntar ao ARMy. Har Har Har!}
{503}{}{Eu tenho que dar isso a você, amigo. Você está despertando sua vida tentando vencer Francis!}
{504}{}{Ouch! Direito nos metacarpos!}
{505}{}{Ei, Francis! Você deve TRICEP - arrumar o braço do ombro.}
{506}{}{Esta luta com certeza é HUMERUS! Guffaw Guffaw!}
{507}{}{Use sua clavícula, Francis! Use sua clavícula!}
{508}{}{Uh oh ... é melhor eu sair do caminho do ARM! Ha ha ha!}
{509}{}{Olhe para eles, bíceps vá!}
{510}{}{Eu acho que ouço um tendão se preparar para pop ...}
{511}{}{Você sabe, um simples cálculo da relação de massa parece favorecer Francis.}
{512}{}{Francis! Fran-CEI! FRAN-CIS!}
{513}{}{Lick 'em, Francis! Não, não com a sua língua!}

{530}{}{Tudo bem, Francis! Você tem certeza que DEVE-ER!}
{531}{}{Bem-vindo Francis!}
{532}{}{Uau! Eu nunca vi isso acontecer antes!}

{599}{}{Encontrei uma nota nos túneis com os nomes Francis e Zaius sobre isso. Parece que você cometeu alguns crimes.}
{600}{}{Droga. Zaius deixou as notas de novo, eh? Bem, humano, deixe-me dizer-lhe isso: eu
 sabia que há pessoas tentando matar mutantes nesta cidade, e eu sabia que Marcus seria apenas
 prenda-os com provas. Eu só queria fazer isso acontecer com o menor derramamento de sangue possível.}
{601}{}{Então você matou inocentes, hein?}
{602}{}{Certo. Então, o que você propõe fazer sobre isso?}

{603}{}{Inocentes? Ha! As pessoas que eu matei estavam tentando me matar! Acabei de retornar o favor
  e se certificou de que suas mortes serviram para outro propósito - um que poderia promover a causa da paz.}
{604}{}{Mas assim você ainda não é mais do que um criminoso e um assassino - e eu só
 Tenha a sua palavra de que há uma conspiração.}
{605}{}{O único que satisfará a causa da paz é que todos os assassinos morram.
 E eu vou fazer a minha parte matando você.}

{606}{}{Se você falou com algumas pessoas da cidade sobre o seu ódio contra os mutantes,
  Você descobriria sobre a conspiração. Eu sei que dois erros não fazem um certo, mas eu chamo de autodefesa.
 Eu fiz algo errado, e eu admito isso. Não posso ficar aqui. Vou buscar uma maneira de expiar minhas ações ...
 Isso satisfaz seu senso de justiça?}
{607}{}{Vai ter que.}
{608}{}{Não, não. Eu também vou matar você.}

{700}{}{Você bateu Francis no braço de combate.}
{701}{}{Você confrontou Francis sobre a nota para Zaius.}

{800}{}{(Olhando o mutante maciço, você percebe que não teria
 tive uma chance. Tempo para se afastar enquanto você ainda obteve sua digitação.)}
