{100}{}{Você vê uma coisa mutante estranha, com pele manchada e um sorriso horrível.}
{101}{}{Você vê um cidadão ghoul.}
{102}{}{Você vê um ghoul. Sua pele parece estar pronta para destruir a criatura. Parece também
 é facilmente aceito pelos outros habitantes da cidade.}

{103}{}{O trabalho de refinaria é difícil.}
{104}{}{Os mutantes e os humanos parecem estar no limite ultimamente.}
{105}{}{Não gosto de trabalhar perto do ácido.}
{106}{}{Esta cidade está ficando muito cheia ultimamente, parece.}
{107}{}{Os seres humanos não são todos ruins.}
{108}{}{Bem-vindo ao Broken Hills.}
{109}{}{Onde foi Hank? Alguém já viu Hank?}
{110}{}{Trabalhamos duro para fazer Broken Hills o que é hoje.}
{111}{}{Quando é a próxima refeição, afinal?}

{112}{}{Chad foi preso? Os humanos devem ter vergonha de si mesmos.}
{113}{}{Nem todos os seres humanos são como o Chade.}
{114}{}{Bummer sobre Chad, cara.}
{115}{}{Eu me pergunto se eu posso entrar naquela ação de caravana ...}
{116}{}{Onde foi Hank? Alguém já viu Hank?}
{117}{}{Trabalhamos duro para fazer Broken Hills o que é hoje.}
{118}{}{Quando é a próxima refeição, afinal?}
{119}{}{Você não precisa de um meteorologista para saber de que maneira sopra o vento.}
{120}{}{Pare! Ei ... como é esse som?}

{121}{}{Com os opressores!}
{122}{}{Como você poderia matar Tchad assim?}
{123}{}{O que, Chade resistiu violentamente à prisão ou a algo?}
{124}{}{Eu vejo um dia sombrio para Broken Hills.}
{125}{}{Chad conseguiu o que estava vindo para ele.}
{126}{}{Deixe o castigo se encaixar no crime.}
{127}{}{Pobre Chade. Pelo menos ele não tinha família.}
{128}{}{Os humanos estão chateados com o Chade.}
{129}{}{Os mutantes observam melhor ... os humanos podem querer se vingar do Chade.}

{130}{}{Quem faria algo tão monstruoso?}
{131}{}{Com os mutantes desaparecidos, somos verdadeiramente indefesos contra invasores.}
{132}{}{Marcus ... Zaius ... Francis ... todo o resto ... ido ...}
{133}{}{O futuro é sombrio.}
{134}{}{Foram os humanos que fizeram isso? Foi Cameron?}
{135}{}{Quem deve nos guiar agora que Marcus se foi?}
{136}{}{Onde podemos nos refugiar agora?}

{137}{}{Os bastardos da NCR. É melhor não vir mais aqui, não se eles saibam o que é bom para eles.}
{138}{}{Eu me pergunto se NOSSOS humanos estavam por trás disso ...}
{139}{}{Obrigado por salvar os mutantes.}
{140}{}{Nós devemos linchar o bastardo que tentou envenenar nossos mutantes.}
{141}{}{Tanto está acontecendo ... está fazendo girar minha cabeça ...}
{142}{}{Provavelmente deveria voltar ao trabalho.}

{143}{}{Quem teria permitido que esses dois não fossem? Também matando guardas ... Marcus deve estar chateado.}
{144}{}{Há algum negócio sangrento acontecendo na cidade.}
{145}{}{Você percebeu que a cidade cheira de problemas ultimamente?}
{146}{}{Eu pensei que este seria um lugar pacífico para se estabelecer. Parece que eu estava errado.}
{147}{}{Quem pensou que esse tipo de violência poderia vir a Broken Hills?}
{148}{}{Franc e Manson ... alguém tem um desejo de morte para os mutantes.}

{149}{}{Como você pode deixar aqueles dois fora da prisão?}
{150}{}{Você deveria ter vergonha de si mesmo.}
{151}{}{Espero que você esteja certo de que Franc e Manson não representam uma ameaça ... os mutantes vão culpá-lo por
 isto.}
{152}{}{Franc e Manson ... de volta à sociedade ... hoo boy. Talvez eu vá embora da cidade.}
{153}{}{Há algum negócio sangrento acontecendo na cidade.}
{154}{}{Você percebeu que a cidade cheira de problemas ultimamente?}

{155}{}{Bem feito em trazer esses idiotas para a justiça!}
{156}{}{Sempre pensei que Jacob era um pouco estranho.}
{157}{}{Isso ensinará aos humanos que eles não podem exibir as leis.}
{158}{}{Venha ... Aileen? Eu não acredito que ela faria isso.}
{159}{}{Que golpe para os humanos! Eles estão muito envergonhados de si mesmo agora. Muito defensivo.}
{160}{}{Will Broken Hills conseguirá consertar a fenda entre humanos e mutantes?}
{161}{}{Aqueles bastardos, Jacob e Aileen, sempre me trataram como um cidadão de segunda classe. Isso os ensinará.}

{162}{}{Eu não acho que Broken Hills se recuperará da perda da mina ...}
{163}{}{Todos os mutantes ... mortos ...}
{164}{}{... agora nunca saberemos se pudéssemos ter feito a paz entre os mutantes e os humanos ...}
{165}{}{Tempo para sair e ver o que o resto do mundo tem para oferecer ... não vale a pena cavar
 as minas.}
{166}{}{Gostaria de saber se, em qualquer outro lugar, a Califórnia precisa de refinadores de urânio?}
{167}{}{Acho que vou voltar para Gecko agora ...}

{168}{}{Você é bastardo de deuses.}
{169}{}{Você não tem vergonha, sem decência?}
{170}{}{Por que você tenta destruir nossa cidade?}
{171}{}{Você não percebe que se você tivesse destruído a mina, você também nos teria destruído?}
{172}{}{Eu não quero falar com você.}
{173}{}{Vá embora.}

{174}{}{Bom trabalho.}
{175}{}{Muito ruim, essas pessoas morreram sob a cidade.}
{176}{}{Eu me pergunto como essas pessoas cavaram os túneis sem que percebêssemos.}
{177}{}{Agora sabemos o que Franc e Manson estavam fazendo.}
{178}{}{Aqueles pobres, pobres. Suas famílias pobres.}

{180}{}{Não me machuque.}
{181}{}{Me deixe em paz.}
{182}{}{Não! Não! Não!}
{183}{}{Eu irei agora.}
{184}{}{Deixe a nossa cidade!}
