{100}{}{Você vê um homem desgrenhado vestindo um bata de laboratório.}
{101}{}{Você vê Jacob o químico.}
{102}{}{Você vê um homem desgrenhado com um casaco de laboratório manchado. Suas mãos estão descoloridas contra produtos químicos.}

{103}{}{Olá. Eu sou Jacob, o químico da Farmácia de Química. O que posso fazer para você?}
{104}{}{O que você quer?}
{105}{}{Olá de novo! O que posso para você hoje?}
{106}{}{Bem vindo de volta. O que posso fazer para você?}
{107}{}{Da yagga! Eep oop op!}
{108}{}{Dugstore? Rugstore?}
{109}{}{Tenho um pouco de minério que eu quero refinado, e não quero pagar os preços da refinaria.}
{110}{}{O que você pode me falar sobre Broken Hills?}
{111}{}{Quero alguns produtos químicos misturados.}
{112}{}{Foi-me dito para falar com você sobre um certo assunto sobre os mutantes.}
{113}{}{Tchau.}

{114}{}{:: Um olhar de noção cruza o rosto dele :: Saia daqui. Não tenho tempo para você.}
{115}{}{-feito-}

{116}{}{Farmacia. É uma farmácia. Olha, quer alguma coisa?}
{117}{}{Você novamente? Você quer alguma coisa?}
{118}{}{'Es!}
{119}{}{Unh uh.}

{120}{}{Bem. Vamos ver o que você quer.}
{121}{}{-Mais-}

{122}{}{Então saia.}
{123}{}{-feito-}

{124}{}{Lá. Foram realizadas. Obrigado pela dica. Agora, saia.}
{125}{}{D'okay!}

{148}{}{Por que você não me diz como se sente sobre os mutantes primeiro?}
{149}{}{Eu odeio eles.}
{150}{}{Sou ambivalente com eles.}
{151}{}{Eu gosto deles!}

{152}{}{Nesse caso, vou lhe dar a história real.}
{153}{}{Um humano chamado Jacob - fui nomeado depois dele - fundou este lugar. O mutante Marcus veio
 E obrigou todos sob seu domínio.}

{154}{}{É o bastante. Você é louco. Adeus.}
{155}{}{Me diga mais.}

{156}{}{Talvez se eu lhe contar a história real, você mudará de idéia.}
{157}{}{OK. Conte-me.}
{158}{}{Não, não estou realmente interessado.}

{159}{}{Nesse caso, é ótima estar aqui. Esta cidade tem tudo o que você poderia querer ... mutante
 Xerife, mina de urânio, hospital, loja ... você pode obter apenas sobre qualquer coisa aqui. Você quer alguma outra coisa?}
{160}{}{Sim.}
{161}{}{Não.}

{162}{}{Great. Tchau.}
{163}{}{Tchau.}

{164}{}{Ele governou aqui desde que o Mestre foi destruído. Ele coloca qualquer um que discorda
 Com ele ... ou eles simplesmente "desaparecem". O lugar parece civilizado no topo das coisas, mas a verdade é
 Que é um campo de morte para mutantes sanguinários. Há um amigo de um amigo que teve amigos que
 Desapareceu depois de falar.}
{165}{}{Continue.}
{166}{}{É o bastante. Você é louco. Adeus.}

{167}{}{Todos nós fingimos que esta é uma cidade civilizada, que estamos todos subindo e subindo ... mas todos nós vivemos
 Com medo da raiva mutante. Cada dia, há cada vez menos humanos.}
{168}{}{Todos os mutantes que eu vi parecem velhos e decrépitos.}
{169}{}{Por que não lutar de volta?}

{170}{}{Isso é porque eles estão tentando te enganar, amigo. Eles estão tentando te enganar.}
{171}{}{Por que não lutar contra eles, então?}
{172}{}{Me engana? Entendo. Bem, tenho de ir. Bastante conversando com você.}

{173}{}{Na verdade, nós somos. Alguns amigos meus e eu estamos planejando dar um golpe que vai livrar isso
 Cidade de mutantes, mas precisamos tirar alguns amigos da prisão. Você está conosco?}
{174}{}{Não.}
{175}{}{Não. And I’m turning you in. You’re crazy.}
{176}{}{Certo!}

{177}{}{Você tem certeza? Esta é uma chance de manter a humanidade livre, você sabe, daqueles mutantes viciosos
 Bastardos.}
{178}{}{Ainda não está.}
{179}{}{Oh tudo bem. Você me convenceu.}

{180}{}{Então essa é sua escolha. Eu vou deixar você continuar com sua vida. Pity, no entanto. Você parece difícil.}
{181}{}{Yeah. Tchau.}

{182}{}{Você é, eh? Eu não penso assim, traidor.}
{183}{}{O que?}

{184}{}{Eu tenho um pequeno trabalho para você. Nossos amigos, Manson e Franc, estão sendo presos na prisão. eu quero você
 Para tirá-los. Faça-o em silêncio, se possível. Não quero toda a cidade em sua cabeça.}
{185}{}{E se eu matar alguém?}
{186}{}{Consegui. Tenho mais perguntas.}
{187}{}{Esqueça. Estou fora.}
{188}{}{Consegui. Até mais.}

{189}{}{Sem problemas. Todos eles são todos mutantes. Mas faça isso em silêncio, pelo amor de Deus.}
{190}{}{Consegui. Tenho mais perguntas.}
{191}{}{Consegui. Até mais.}

{192}{}{Mais perguntas?}
{193}{}{Tenho um pouco de minério que eu quero refinado, e não quero pagar os preços da refinaria.}
{194}{}{O que você pode me falar sobre Broken Hills?}
{195}{}{Quero alguns produtos químicos misturados.}
{196}{}{Nothing. Tchau.}

{222}{}{Maneira de ativar seu próprio tipo, mutie-lover. Como você pode fazer isso com o Chade? Não me importo com o que você fez por nós. Você é um
 Desgraça para a humanidade.}
{223}{}{Tchau.}

{224}{}{Bem feito no trabalho da prisão!}
{225}{}{Obrigado.}

{226}{}{Você realmente teve que matar todos? Agora todos estão preocupados. Bem, não importa.}
{227}{}{Desculpa.}

{228}{}{Você os pegou. Acho que essa é a parte importante. Claro, agora, todos na cidade sabem
 Você está ligado a Manson e Franc de alguma forma. Ah bem.}
{229}{}{Desculpa.}

{230}{}{Eu acho que posso confiar em você com algo importante. Como você gosta de fazer um pouco mais de trabalho?}
{231}{}{O que mais posso fazer por você, amigo?}
{232}{}{Mais trabalho? Como o quê?}
{233}{}{Preciso de um minério refinado.}
{234}{}{Ainda não. Preciso de alguns produtos químicos.}
{235}{}{Not just yet, thanks. Tchau.}

{258}{}{É tipo isso. Odiamos os mutantes. Queremos matá-los. A melhor maneira de se livrar deles é
 Exploda as minas enquanto estão dentro. Queremos que você planifique a carga.}
{259}{}{Eu vou fazer isso!}
{260}{}{Não posso fazer isso.}

{261}{}{Excelente, meu amigo! Aqui. Pegue este interruptor explosivo. Conecte-o ao purificador de ar e saia daqui.
 Nós providenciamos para que os mutantes da cidade estejam na mina.}
{262}{}{Apenas me avise quando você está pronto para ir.}
{263}{}{Vai fazer.}
{264}{}{Não posso fazê-lo.}

{265}{}{Por que não? Você está assustado ou algo assim? Você está certo de que não vai fazer isso?}
{266}{}{Sim.}
{267}{}{Não, acho que vou fazer isso.}

{268}{}{Suponho que posso entender. Você será igualmente compreensivo, espero, quando eu lhe disser para obter o
 fora da minha vista. Traidor.}
{269}{}{-feito-}

{270}{}{Você está pronto para continuar com o plano?}
{272}{}{Sim. Let’s do it.}
{273}{}{Eu mudei de ideia. Eu não quero fazer isso.}

{274}{}{Boa. Estive esperando por esse dia. Basta anexar o interruptor explosivo ao purificador na mina
 e saia do trato. Haverá uma enorme explosão. Vejo você depois!}
{275}{}{Tanto tempo! Morte aos mutantes!}
{276}{}{Eu mudei de ideia. Eu não quero fazer isso.}

{277}{}{Você é o traidor.}

{278}{}{Você fez um bom trabalho. Uma vez. Muito ruim, você se virou contra nós.}

{279}{}{Estamos finalmente livres do flagelo mutante impuro. Muito obrigado pela sua ajuda. Existe um pequeno cache de
 armas no porão sob a Liz's General Store. Para sua lealdade, ajude-se ao que você encontra lá.}

{280}{}{Nós estamos saindo da cidade. Você deveria também.}

{281}{}{Venha me encontrar quando eu estiver na loja e conversemos.}

{282}{}{O seu minério está pronto. Aqui está.}
{283}{}{Obrigado!}

{284}{}{Ainda não terminei com o minério. Me dê um tempo.}
{285}{}{Tive outras questões.}
{286}{}{Okay. Tchau.}

{287}{}{Pronto para a distração?}
{288}{}{Pronto para tentar essa distração de novo?}
{289}{}{Você entendeu. Quer me ajudar a fazer uma distração?}

{290}{}{Eu gostaria de comprar algum ... uh ... medicamento.}
{291}{}{Algo mais?}
{292}{}{Sim.}
{293}{}{No, thanks. Tchau.}

{294}{}{Agora você pode ver o quão traiçoeiro são os mutantes. Se você já visse anteriormente.}

{295}{}{Se você não nos ajudar, não vamos ajudá-lo.}
{296}{}{Bem, o que você está a aguentar? Você tem patriotas para resgatar do encarceramento!}
{297}{}{Oh ... Isso mesmo.}

{298}{}{Eu disse-lhe que os separe da prisão, não os matem! Qual é o problema com você?}
{299}{}{Me desculpe ... eu só ...}

{300}{}{Nada mais. Se você quisesse ou não, você realmente prejudicou nossos planos para esta cidade. Agora você vai pagar.}

{301}{}{Desculpe, amigo, mas ... acabei de perder meus dois melhores amigos. Aqueles mutis bastardos os mataram na prisão.}
{302}{}{Urrggg. Toooo badddd. Tchau.}
{303}{}{Uh... Gee. I'm really sorry. You have my condolences. Tchau.}
{304}{}{Oops.}

{305}{}{Opa? Você disse 'Oops?' Você não teve nada a ver com isso, não é?}
{306}{}{Foi um acidente, eu juro!}
{307}{}{De jeito nenhum. Claro que não! Malditas muias!}

{308}{}{Acidente, minha bunda! Coma isso, você mutie-lovin 'rat-bastard!}

{309}{}{Sim, bem ... seu dia está chegando.}

{310}{}{Já lhe disse tudo o que você precisa saber sobre esse lugar. Então o que você quer?}
{311}{}{Eu tenho algumas outras perguntas.}
{312}{}{Nada. Esqueça.}

{313}{}{Obrigado.}
{314}{}{[continuar]}

{315}{}{Ei, amigo. Agradeço a sua ajuda para conseguir nossos amigos fora do seu problema. Você está bem no meu livro.}
{316}{}{Obrigado.}
