{100}{}{Você vê uma mulher com um olhar de cenho perpétuo.}
{101}{}{Você vê Liz, gerente da Loja Geral.}
{102}{}{Você vê uma mulher de meia-idade cujo cenho franziu a cara. Ela parece ser uma dessas
 pessoas que têm um prazer perverso em uma vida difícil.}

{103}{}{Oi. Eu sou Liz. O que você quer?}
{104}{}{O que agora?}
{105}{}{Nggg! Nnnnnng!}
{106}{}{Me nget ssssstUFF!}
{107}{}{Gostaria de comprar algo.}
{108}{}{O que você pode me falar sobre essa cidade?}
{109}{}{Eu quero matar algo. O que se passa?}
{110}{}{O que há com as armas no seu porão?}
{111}{}{Eu entendo que você tem um excesso de armas. Eu preciso de algum.}
{112}{}{Nada.}

{113}{}{Oh, Deus ... outro bebê mutante de cabeça leve. Quando alguém vai atirar nessas coisas?}
{114}{}{Gorgolejo.}

{115}{}{Fale devagar e claramente e vou ver se posso ajudá-lo.}
{116}{}{Nn! Coisa! Eu!}
{117}{}{Dood bye!}

{118}{}{Você quer comprar algo?}
{119}{}{Sim!}
{120}{}{Não não não.}

{121}{}{Tudo certo. O que você quer?}
{122}{}{Trocar.}

{123}{}{Não esqueça a taxa de serviço.}
{124}{}{Tank yoo!}

{125}{}{Você quer comprar algo? Fine. This is what I’ve got.}
{126}{}{Outra coisa ...}
{127}{}{Obrigado. Até mais.}

{128}{}{É uma pequena cidade de mineração chata e cheia de todo tipo de indesejáveis. Você quer uma visita guiada,
 fale com Steve ou com alguém.}
{129}{}{Uau, um maldito. Eu tenho mais perguntas.}
{130}{}{OK. Tchau.}

{131}{}{O que você tem em mente para matar?}
{132}{}{Radscorpions, ratos, esse tipo de coisa.}
{133}{}{Ah, o humanoide ocasional.}
{134}{}{Você. Morra, cadela.}
{135}{}{Caras ruins.}
{136}{}{Ninguém. Esqueça.}

{137}{}{Quem te contou sobre isso? Quero dizer ... claro que não! Não seja ridículo!}
{138}{}{relaxar. Jacob me disse.}
{139}{}{Sim, tudo bem, é toda a cidade e é um segredo aberto.}
{140}{}{Seu segredo está seguro. Eu obtive isso de uma fonte confiável.}

{141}{}{Você pode tentar as cavernas ou a área perto das casas. Eu entendo que há muitos monstros
 há.}
{142}{}{Obrigado. Tchau.}

{143}{}{Humanoides, hein? Algum humanoids em particular?}
{144}{}{Humanos.}
{145}{}{Ghouls.}
{146}{}{Mutantes.}
{147}{}{Só brincando.}

{148}{}{Qual é a sua definição de cara ruim?}
{149}{}{Qualquer um que eu não goste. Humanoids, principalmente.}
{150}{}{Qualquer um que se interponha no meu caminho.}
{151}{}{É uma definição bastante fluida.}

{152}{}{Oh, bem, se você conseguiu isso de uma fonte confiável, então sim. Você vai acabar com o
 dominação dos mutantes?}
{153}{}{Sim.}
{154}{}{Não.}

{155}{}{Então, acho melhor começar a limpar as extremidades soltas.}
{156}{}{-feito-}

{157}{}{Eu não apoio killin 'nesta loja. Saia.}
{158}{}{Tanto faz. Cadela.}

{159}{}{Ghouls são escravos úteis. Eles não têm mentes suficientes para serem pessoas, mas não são
 vale a pena matar, também. Eu não apoio a morte de ghouls.}
{160}{}{Bem. Eu quero outra coisa.}
{161}{}{Tanto faz. Tchau.}

{162}{}{Se você está realmente interessado em matar mutantes, talvez você deva falar com Jacob o químico.}
{163}{}{Jacob, hein? Vai fazer.}

{164}{}{Achei que você poderia estar. Agora, fique bem.}
{165}{}{Certo.}

{166}{}{Nesse caso, pegue a passagem escondida no chão no meu quarto até a fortaleza. eu tenho um
 pequeno arsenal lá embaixo. Git vai.}
{167}{}{Obrigado.}

{168}{}{Coincidentemente, tirei-me de todas as armas que tinha, exceto o que você vê aqui. Ajudá-lo com
 mais alguma coisa?}
{169}{}{Sim.}
{170}{}{Não.}

{171}{}{Eu não estou vendendo para você. Saia da minha loja.}
{172}{}{-feito -}

{173}{}{A loja está fechada. Abrimos às oito.}
{174}{}{Ei! Afaste-se daí!}
{175}{}{É isso aí! Você pediu por isso!}
{178}{}{Não me importa se você o obteve do próprio Deus! Só vou me certificar de que ninguém mais descubra.}
{179}{}{Ei! Não vá lá!}
{180}{}{Não vou avisá-lo novamente. Fique longe de lá!}
{181}{}{É isso aí! Venha pra cá!}
{182}{}{Com o que mais você vai me incomodar?}

{183}{}{Obrigado.}
{184}{}{[continuar]}

{185}{}{Ei! Quem diabos está lá fora?}
{186}{}{Eu não sei quem você é, mas vou para você '.}
