{100}{}{Você vê um biped masculino da espécie homosapien.}
{101}{}{Você vê um cidadão masculino.}
{102}{}{Você vê um cidadão masculino. He’s dirty, but he carries his head high.}

{131}{}{Todos os mutantes ... morto ... Não posso acreditar.}
{132}{}{Quem faria tal coisa?}
{133}{}{De onde veio esse veneno?}
{134}{}{Com todos os mutantes mortos, vamos precisar da NCR para proteção.}
{135}{}{Eu quero vingança sobre os bastardos responsáveis.}
{136}{}{Quem podemos matar em troca?}
{137}{}{NCR tem um exército? Quem nos protegerá agora?}
{138}{}{Acho que não precisamos nos preocupar com eventuais tumultos mutantes agora ...}
{139}{}{Poor Marcus ... quem nos guiará agora?}

{147}{}{Agora não é seguro?}
{148}{}{Quando o atrevimento tornou-se tão comum?}
{149}{}{Estou pensando em mudar ... já não está seguro aqui.}
{150}{}{Ouvi dizer que Franc e Manson são verdadeiros mutieiros.}
{151}{}{Fico feliz que eles saíram ... Eu me pergunto onde estão agora.}
{152}{}{Franc e Manson são venenosos. Esta cidade nunca mais será a mesma coisa até que sejam pegos de novo.}
{153}{}{Quem mataria aqueles guardas? Isso é desumano.}
{154}{}{Não posso acreditar que essa cidade costumava ser tão pacífica.}

{155}{}{Como você conseguiu convencer os guardas a deixar esses dois bastardos?}
{156}{}{Obrigado por deixar Franc e Manson. Eles não estavam causando nenhum problema real.}
{157}{}{Onde estão Franc e Manson agora? Eles realmente deveriam estar de volta à prisão.}
{158}{}{Alguns dos meus melhores amigos são mutantes e ghouls ...}
{159}{}{Gostaria que tivéssemos mais algumas lâmpadas.}
{160}{}{Que cheiro é esse?}
{161}{}{Estou preocupado com o fato de a NCR tentar nos atrapalhar.}
{162}{}{Você acha que o novo Reno seria um bom lugar para viver?}
{163}{}{Eu não tenho nada contra mutantes, mas eles são tão engraçados.}

{164}{}{Eu lhe diria "bom trabalho", mas provavelmente você me faria entrar.}
{165}{}{Jacob e Aileen eram mutie-haters, hein? Eles pareciam tão agradáveis.}
{166}{}{Vamos ... Aileen?}
{167}{}{Não consigo acreditar que as relações humanas / mutantes tenham caído tão baixas.}
{168}{}{Marcus deve estar chateado com os humanos agora.}
{169}{}{Eu acho que todos nós, seres humanos, melhor, simplesmente relaxe e respire fácil por um tempo.}
{170}{}{Ouvi dizer que os mutantes estão se unindo para destruir os humanos!}
{171}{}{O que os ghouls pensam sobre tudo isso?}

{172}{}{A mina ... destruída ... nossas casas não valem nada agora.}
{173}{}{Estamos arruinados.}
{174}{}{Este é o fim de Broken Hills.}
{175}{}{Eu vou para a NCR.}
{176}{}{Quem faria uma coisa dessas?}
{177}{}{Meu deus ... a mina ...}
{178}{}{Onde está a justiça no mundo?}
{179}{}{Acho que vou me matar. Sem o meu, não posso me sustentar.}
{180}{}{Oh, amor ... a vida é difícil.}

{181}{}{Uau ... Nunca conheci alguém suficientemente forte para vencer Francis.}
{182}{}{Você é tão forte!}
{183}{}{Você é muito difícil, hein?}
{184}{}{Às vezes eu me sinto como uma bola mágica de 8. Eu simplesmente explodir aleatoriamente e me afastar.}
{185}{}{Alguma vez você já lutou contra um deathclaw?}
{186}{}{Você é tão inteligente quanto forte?}

{187}{}{Francis certamente parece feliz ultimamente.}
{188}{}{Francis tem bastante brilho. Ele ficou deitado?}
{189}{}{Ei, gimp!}
{190}{}{Ainda andando em linha reta?}
{191}{}{Francisco cicatrizou você?}
{192}{}{Você está caminhando um pouco solto, lá.}
{193}{}{Como você poderia ser estúpido o suficiente para lutar contra Francis por essas chances?}
{194}{}{Espero que tenha gostado tanto quanto Francisco.}

{198}{}{Fico feliz em tê-lo na cidade.}
{199}{}{Vai ficar por um tempo?}
{200}{}{Espero que você goste aqui!}
{201}{}{Você está fazendo um bom trabalho. Já considerou ser xerife?}
{202}{}{A cidade parece muito melhor ultimamente.}
{203}{}{Eu acho que as coisas estão finalmente começando a seguir nosso caminho.}

{204}{}{Afaste-se de mim, bêbado.}
{205}{}{Eu não associo com o seu tipo.}
{206}{}{Quem te deixou entrar?}
{207}{}{Eu não sei por que eles não cortam você fora da cidade.}
{208}{}{Por favor, deixe-me só.}
{209}{}{Não me incomode.}
{210}{}{Não posso ajudá-lo. Vá embora.}
{211}{}{Morra no deserto, idiota.}
{212}{}{Vá embora.}

{213}{}{Ajude-me!}
{214}{}{Ele está aqui!}
{215}{}{Aaaaaaaaaaah!}
{216}{}{Traidor!}
{217}{}{Desprezível!}
{218}{}{Me deixe em paz!}
{219}{}{Não! Não! Não!}
{220}{}{Não me toque!}
{221}{}{Não me machuque!}

{250}{}{Aqueles pobres pessoas.}
{251}{}{Quem caiu na escada de Jacob?}
{252}{}{Bem, veja o que o deserto arrastou.}
{253}{}{Alguns dos meus melhores amigos são mutantes e ghouls ...}
{254}{}{Gostaria que tivéssemos mais algumas lâmpadas.}
{255}{}{Que cheiro é esse?}
{256}{}{Estou preocupado com o fato de a NCR tentar nos atrapalhar.}
{257}{}{Você acha que o novo Reno seria um bom lugar para viver?}
{258}{}{Eu não tenho nada contra mutantes, mas eles são tão engraçados.}
{259}{}{A vida é dura. O rotgut de Phil não deve ser.}
{260}{}{Não posso acreditar aquele filho da puta.}
{261}{}{A respiração do meu gato cheira a comida de gato.}
