{100}{}{Você vê um homem desalinhado com roupas desgastadas.}
{101}{}{Você vê Manson, uma das milícias locais do ódio.}
{102}{}{Você vê um jovem com uma barba rasgada, roupas esfarrapadas e um insano, mas de alguma forma
 Confiante brilho em seus olhos.}

{103}{}{O que?!}
{104}{}{Duhhh ... gabba gabba eh?}
{105}{}{Eu tenho bares?}
{106}{}{Quem é Você?}
{107}{}{Por que você está preso?}
{108}{}{Conte-me sobre Broken Hills.}
{109}{}{Nada. Esqueça.}

{110}{}{Não conheça essa conversa louca e estúpida. Você acaba de sair daqui, então me faça
 Estúpido também.}
{111}{}{Ah!}

{112}{}{Manson. Rebelde ganha a sociedade.}
{113}{}{Sobre o que você está se rebelando?}
{114}{}{sim! Lute contra o poder!}
{115}{}{Perdedor na sociedade, mais como.}
{116}{}{Manson?}
{117}{}{Entendo. Tchau!}

{118}{}{Estou aqui por favor e Franc estava trabalhando contra o que a sociedade quer que acreditemos.}
{119}{}{E isso é…}
{120}{}{sim! Lute contra o poder!}

{121}{}{Broken Hills? Vivei aqui toda a minha vida. É assim que eu conheço todas as coisas ruins que acontecem aqui.
 É por isso que eu sei o quanto os mutantes são maus. É bom que alguns de nós vejam o
 verdade.}
{122}{}{Sim, vou dizer. Lute contra o poder, hein?}
{123}{}{Você está ouvindo o ódio, e essa não é a verdade.}
{124}{}{Talvez você deva perceber que os únicos óculos que você possui são os que você permite que outros
 As pessoas que colocam em você, e que pregar a política do ódio apenas faz você parecer mais estúpido.}
{125}{}{Sim. Tchau.}

{126}{}{A sociedade quer que acreditemos que humanos e mutantes devem viver juntos. Mas os mutantes
 Estão fora para nos matar! Pelo menos, é isso que Franc diz.}
{127}{}{Você realmente gosta de Franc, hein?}
{128}{}{Essa deve ser a coisa mais estúpida que já ouvi.}
{129}{}{Tudo certo. Tchau.}

{130}{}{Está certo! Nós devemos ... umm ... pense por nós mesmos! Isso é o que Franc e Jacob sempre dizem!}
{131}{}{Uau, você realmente sugere esses dois. Por que não tentar pensar em si mesmo em vez de papagaios
 O que outras pessoas lhe dizem?}
{132}{}{Você realmente gosta de Franc, hein?}
{133}{}{Tchau.}

{134}{}{O que você saberia, seu idiota? Saia daqui antes de se machucar!}

{135}{}{Nos últimos tempos, havia um cara que nos contou tudo o que tínhamos pensado. Minha mãe
 E papai disse que estava relacionado comigo. Ele morreu na prisão, mas ele era realmente influente para mim. As pessoas disseram
 Ele era realmente inteligente. Eu acho que eles estavam certos. Quer dizer, olhe pra mim!}
{136}{}{Umm ... sim. Olhe para você.}
{137}{}{Você? Inteligente? Ha!}
{138}{}{Sure. Tchau.}

{139}{}{Wha'?}
{140}{}{Nada.}

{141}{}{Sim, acho que ele é uma das pessoas mais sábias que já conheci. Jacob é inteligente, mas ele não é tão
 Diretamente como Franc.}
{142}{}{Franc é apenas uma brincadeira virulenta. Ele não vai chegar a você em qualquer lugar.}
{143}{}{Sim, eu conheci ele. Ele é um bom cara.}
{144}{}{Não conheci o cara. Nenhuma opinião sobre ele.}
{145}{}{Thanks. Tchau.}

{146}{}{O que mais você quer?}
{147}{}{Quem é Você?}
{148}{}{Por que você está preso?}
{149}{}{Conte-me sobre Broken Hills.}
{150}{}{Você gosta de Franc?}
{151}{}{Por que você é chamado Manson?}
{152}{}{Porque você é tão estupido?}
{153}{}{Nada. Esqueça.}

{154}{}{Você está conosco? Então tire-nos daqui!}
{155}{}{Eu estou trabalhando nisso. Até mais.}

{156}{}{Obrigado pela ajuda. Sabia que podíamos contar com um colega humano para ver a luz!}
{157}{}{Sim. Eu sou bem assim.}

{158}{}{Então, o que mais eu posso fazer por você?}
{159}{}{Estou curioso sobre seus planos agora.}
{160}{}{Como significa seu nome?}
{161}{}{Nada. Just looking around.}

{162}{}{Agora destruímos a mina enquanto os mutantes estão dentro. Aqueles que são deixados, nós esfregamos à mão.}
{163}{}{Eu quero em.}
{164}{}{Não conte comigo.}
{165}{}{Legal. Boa sorte.}

{166}{}{Bem, as pessoas pensam que ele era um cara de banda ou algo assim. Mas o Manson que me nomeou começou um
 Religião e foi morto por causa disso. Ele era um mártir. Talvez eu também seja um.}
{167}{}{Soa ... fascinante. De qualquer forma…}

{168}{}{Você terá que falar com Jacob sobre isso. Tenho certeza de que com seu jailbreak, ele vai querer você.}
{169}{}{Legal. Até mais.}

{170}{}{Eu queria trabalhar com você. Ah bem. Até mais!}

{171}{}{Seu otário! Confiamos em você para nos ajudar!}

{172}{}{Uau ... você pode matar como ninguém. E agora estamos livres dos mutantes. Isso é muito legal!}

{173}{}{Estamos saindo da cidade. Você provavelmente também pode ... as mutis estarão à procura de bodes expiatórios.}

{174}{}{Nós seguiremos você.}

{175}{}{Você pregou a mente aberta para Manson.}

{176}{}{Nós nos moldamos! Nós nos moldamos!}

{177}{}{Obrigado pela sua ajuda, amigo. Vamos falar com Jacob e Aileen.}

{178}{}{Você executou o jailbreak com sucesso.}

{179}{}{Boa sorte na mina, irmão.}
