{100}{}{Você vê um velho e corpulento mutante.}
{101}{}{Você vê Marcus the Mutant, xerife de Broken Hills.}
{102}{}{Você vê um mutante corpulento com um elenco cansado em seu rosto. Ele ainda parece vigoroso e resistente.}

# node 1
{103}{mcs1a}{Bem, o que diabos. Eu não vi uma dessas roupas por um longo, longo tempo. Me leva de volta.}
{104}{mcs1b}{O que você quer, humano?}
{105}{mcs1c}{Algo mais que você queria?}
{106}{}{Uggie.}
{107}{}{Quem é Você?}
{108}{}{Qual é a história com esse lugar?}
{109}{}{Por que você não está me atacando mutantes?}
{110}{}{Quais as novidades?}
{111}{}{Eu tenho algo que eu queria lhe dizer.}
{112}{}{Você quer viajar comigo?}
{113}{}{Tchau.}

{114}{mcs3}{Sim, sou um feio mutante. Eu também administra esse lugar. Você tem algum problema com isso?}
{115}{}{Uh!}
{116}{}{Nuh.}

{117}{mcs4}{Você quer me lutar?}
{118}{}{Uh!}
{119}{}{Nuh.}

{120}{mcs5}{Faça o seu melhor tiro, humano.}

{121}{mcs6a}{Boa.}
{122}{mcs6b}{Mantenha seu nariz limpo e você não terá problemas.}
{123}{}{Uh?}

{124}{mcs7}{Eu sou Marcus. Ajudou a construir o lugar. Agora eu sou xerife.}
{125}{}{Você ajudou a construir este lugar? Isso deve ter sido há muito tempo ...}
{126}{}{Besteira. Como você pode ter passado por tanto tempo?}
{127}{}{Tchau.}

{128}{mcs8}{Longa história. Quer que seja curto ou o todo?}
{129}{}{Me dê a versão curta.}
{130}{}{Inferno, não estou muito ocupado. Vamos ouvir tudo.}
{131}{}{Nem. Eu tenho mais perguntas.}
{132}{}{Nem. Até mais.}

{133}{mcs9}{Certo. Eu e um humano chamado Jacob construíram esse lugar em torno desse banco antigo há cerca de 60 anos. Seja bem-vindo aqui, desde que mantenham a paz.}
{134}{}{Ótimo. Eu tenho mais perguntas.}
{135}{}{Fair enough. Tchau.}

{136}{mcs10}{Certo ... Depois que o Mestre e os tábuas foram destruídos, eu passeei um pouco. Não há lugar para ir. Um dia foi atacado por essa vestimenta de vestimenta.}
{137}{}{Mesmo?}

{138}{mcs11}{Isso foi Jacob, da Brotherhood of Steel. Ele jurou algum juramento para destruir mutile. Nós agimos por um tempo - provavelmente um dia ou dois. Depois de um tempo, começamos a rir. Qual foi o ponto?}
{139}{}{Então o que?}

{140}{mcs12}{Nós nos tornamos amigos. Dirigiram-se juntos. Em seguida, outras pessoas começaram a nos seguir. Adivinhei que eles pensavam se não estavam seguros com um mutie e um Steel Knight, o cofre não aconteceria.}
{141}{}{Então você configurou aqui. Por quê?}

{142}{mcs13}{Mina de urânio. Eu sabia que havia um em torno de mapas antigos. Agora, seja bem vindo aqui, "enquanto eles correm direito. Outros podem não pensar muito em nós, mas ninguém é mais livre do que nós. Lá você vai.}
{143}{}{Espere ... você era amigo de um cara da Irmandade?}
{144}{}{O que, você não está matando seres humanos mais?}
{145}{}{Obrigado.There I go. Tchau.}

{146}{mcs14}{Ah, de que poço você é? Muitas e normais fizeram a paz há muito tempo.}
{147}{}{Eu sou de uma aldeia fundada pelo Vault Dweller original.}
{148}{}{De uma aldeia ao noroeste.}
{149}{}{Oh. My mistake. Well, thanks. Tchau.}

{150}{mcs15a}{O que é novidade ... o que é novidade ...}
{151}{mcs15b}{Bem, ficando meio preocupado com um dos nossos caravanas. Chade. Ele pode estar desnatando. Você está prescindindo de mim?}
{152}{}{O que há para mim?}
{153}{}{Certo. Eu vou fazer isso.}
{154}{}{Eu estou um pouco ocupado.}
{155}{}{Você tem mais alguma coisa?}

{156}{mcs16}{Minha eterna gratidão. Certo?}
{157}{}{Bom o suficiente para mim.}
{158}{}{Nada de bom. Eu quero algo.}
{159}{}{Quanto mais perguntas enquanto penso sobre isso.}
{160}{}{Let me think about it. Tchau.}

{161}{mcs17}{Isso não é bom o suficiente para você? Então saia.}
{162}{}{Tchau.}

{163}{mcs18}{Tenho um pequeno problema com a mina. Se você estiver interessado em ajudar a corrigi-lo, vá falar com Zaius, o mestre da mina.}
{164}{}{Onde posso encontrá-lo?}
{165}{}{Você conseguiu algo mais?}
{166}{}{Eu tenho mais perguntas.}
{167}{}{Maybe later. Tchau.}

{168}{mcs19}{Normalmente na mina. Às vezes, o salão.}
{169}{}{Tem alguma outra coisa?}
{170}{}{Eu tenho mais perguntas.}
{171}{}{Tchau.}

{172}{mcs20}{Alguém queixou dois loucos da prisão no banco. Encontre-os. Diga-me e os recobrarei.}
{173}{}{Tem alguma outra coisa?}
{174}{}{Eu tenho mais perguntas.}
{175}{}{Tchau.}

{176}{mcs21}{O que exatamente você quer? Está bem. Nós sentimos algumas pessoas desaparecidas. Não faz ideia do que aconteceu. Encontre-os, obtenha $ 500.}
{177}{}{Eu vou fazer isso de graça.}
{178}{}{$ 500? Parece bom.}
{179}{}{Não tenho tempo.}
{180}{}{Eu tenho mais perguntas.}
{181}{}{Tchau.}

{182}{mcs22}{Ótimo. Deixe-me saber quando você encontrou algo, certo?}
{183}{}{Certo. Eu tenho mais perguntas.}
{184}{}{Will do. Tchau.}

{185}{mcs23}{Sim? O que?}
{186}{}{Você queria que eu encontrasse as pessoas desaparecidas. Encontrei alguns túneis abaixo da cidade. Eles podem estar lá.}
{187}{}{Descobri as pessoas desaparecidas. Eles estão em túneis abaixo da cidade.}
{188}{}{Esses dois condenados escaparam? Eles estão em cahoots com Jacob e Aileen. Eles estão se escondendo em torno da farmácia de Jacob.}
{189}{}{Jacob e Aileen me pediram para quebrar duas pessoas fora da prisão. Eu acho que eles têm um plano de como fazê-lo.}
{190}{}{Jacob e Aileen querem que eu exploda a mina. Penso que você pode querer saber.}
{191}{}{Um cientista da NCR quer experimentar uma técnica experimental que irá eliminar os mutantes. Tenha cuidado com o que você come e bebe.}
{192}{}{Chade levou $ 6000 do representante em Gecko. O representante estava reclamando sobre o preço ... disse que ia subir.}
{193}{}{O Chade manteve cerca de US $ 1000 do último carregamento de urânio para ele próprio. Ele está planejando sair da cidade.}
{194}{}{Nada. Esqueça.}

{195}{mcs24}{Túneis sob a cidade? Adivinha que não é tão surpreendente com as minas ao redor. Você vai continuar procurando por essas pessoas, certo?}
{196}{}{Certo.}

{197}{mcs25a}{Eles estão mortos? Maldito ... Eu direi às famílias eu mesmo.}
{198}{mcs25b}{Aqui está a sua recompensa. $ 500. Obrigado pelo seu tempo.}
{199}{mcs25c}{Oh, hey, eu sei que você disse que faria isso de graça, mas pegue isso como nosso agradecimento.}
{200}{}{Certo.}

{201}{mcs26}{Certo. Me and my deputies will take it from here...And, thanks. I don’t forget things like this.}
{202}{}{No prob. Tchau.}

{203}{mcs27}{O que é que as pessoas têm contra mutantes? Estaremos atentos. Obrigado. A cidade deve-lhe. E nunca me esqueço de coisas assim.}
{204}{}{My pleasure. Tchau.}

{205}{mcs28}{Mantenha seu olho nele, você vai? Eu quero pegá-lo em flagrante.}
{206}{}{Sem problemas.}

{207}{mcs29}{Bem, nesse caso, seria melhor ter certeza de detê-lo. Quer vir junto?}
{208}{}{Certo.}
{209}{}{Não, obrigado.}

{210}{mcs30}{Você quer que eu venha junto com você? Ah, o que diabos, eu sou muito velho para me estabelecer. Nós vamos agora?}
{211}{}{Sim.}
{212}{}{Não, agora não.}

{213}{mcs31}{Ah, há muito acontecendo agora. Quando as coisas se acalmam, então eu só poderia.}
{214}{}{Certo. I got more questions.}
{215}{}{Tchau.}

{216}{mcs32}{Malditamente certo. Melhor amigo que já tive.}
{217}{}{Sim, certo, você o teria mergulhado como todos os outros.}
{218}{}{Tchau.}

{219}{mcs33}{Inferno, sim, eu teria. Que grande mutante ele teria sido.}
{220}{}{Eu não acho que ele fico feliz em ouvir você dizer isso.}
{221}{}{Tchau.}

{222}{mcs34}{(risos) Tivemos esse argumento o tempo todo. (suspiro) Sinto falta daquela cabeça dura.}
{223}{}{E o ódio do Mestre pelos humanos?}
{224}{}{Ainda acho que é um destino podre.}
{225}{}{Tchau.}

{226}{mcs35}{Você está falando há muito tempo. O mundo mudou-se. Você quer ouvir história antiga?}
{227}{}{Definitivamente.}
{228}{}{Não agora. Gostaria de fazer algumas outras perguntas, no entanto.}
{229}{}{Não agora. Eu falarei com você mais tarde.}

{230}{mcs36}{Certo. Well, never really HATED humans. We just had a better way. These new governments, they think they've got all the answers.  Blah, blah. Been there, seen that, got the scars.}
{231}{}{Então, qual foi a melhor maneira?}

{232}{mcs37}{O Mestre queria elevar todos ao seu nível, então não nos lutaríamos mais. Ele estava convencido de que não o faria por nós mesmos - não podia. Tivemos que ser forçados a evoluir.}
{233}{}{Você concorda?}

{234}{mcs38}{Enquanto Jacob estava vivo, pensei que o Mestre estava errado. Mas parece que, enquanto alguns homens podem atender a chamada e se elevar acima de tudo, a maioria simplesmente foge.}
{235}{}{Então você acha que o Mestre estava certo?}

{236}{mcs38a}{Jacob escutou o chamado e abraçou-o. O mesmo ocorreu com o Vault Dweller. Mas não importa quantos se levante acima, as massas sempre os destruirão, certo?}
{237}{}{Talvez.}

{238}{mcs39}{O Mestre queria que todos vejam claramente. O Vault Dweller terminou esse sonho.}
{239}{}{Parece que você admirava e odiava o Vault Dweller ao mesmo tempo.}
{240}{}{Você era um humano. Como você pode justificar o que o Mestre fez com você?}
{241}{}{Então, você acha que o plano do Mestre estava certo?}
{242}{}{Eu sou descendente do morador original do Vault, você sabe.}

{243}{mcs40}{Você está certo. Se todos os humanos lutassem pelo que eles acreditavam assim, não teríamos precisado o plano do Mestre em primeiro lugar.}
{244}{}{O Mestre queria escravizar a humanidade!}
{245}{}{Giro interessante. Eu tenho que ir.}

{246}{mcs41}{Não esqueça, eu conheci as pessoas envolvidas. Eles eram os melhores que a humanidade tinha para oferecer. Seu povo vai contar a história de maneira diferente, certo?}
{247}{}{Err… maybe. Umm, Eu tenho mais perguntas.}
{248}{}{Errado!}

{249}{mcs42}{O "habitante original do Vault"? Você quer dizer aquele que matou o Mestre e destruiu os vagões?}
{250}{}{Ummm ... sim.}
{251}{}{Malditamente certo. Vou fazer algo sobre isso, mutie?}
{252}{}{Nooo ... esta é outra pessoa. Eu não sei do que você está falando.}

{253}{mcs43}{Não é um problema. Como eu disse, isso foi há muito tempo.}
{254}{}{Eu não tenho medo de você.}
{255}{}{Por que você odia os humanos naquela época?}

{256}{mcs44}{Não há motivo para ser, a menos que você me atravesse ou alguém na minha cidade. Seja civilizado, é tudo o que eu pergunto.}
{257}{}{I’ll keep it in mind. Eu tenho mais perguntas.}
{258}{}{I’ll keep it in mind. Tchau.}

{259}{mcs45}{Deixe isso claro: nada vai acontecer aqui, a menos que você comece. Apenas fique civilizado enquanto estiver na minha cidade.}
{260}{}{Yeah, right. Eu tenho mais perguntas.}
{261}{}{Yeah, right. Tchau.}

{262}{mcs46}{As minhas lembranças de ser humano não são tão claras quanto antes, mas lembro de mesquinhez, ódio, ciúme ... Prefiro ser um mutante.}
{263}{}{Então, você acha que o plano do Mestre estava certo?}
{264}{}{Huh. You’re a lot uglier this way. Tchau.}
{265}{}{Then you’re fine. Tchau.}

{266}{mcs47}{Estava falho. Nós deveríamos ter tomado o melhor. Olhar em volta. A maioria dos mutantes não teve a mente ou a vontade de suportar a tensão. (suspiro) Se ao menos tivéssemos escolhido melhor ...}
{267}{}{Então você teria mergulhado Jacob? Ou o Vault Dweller?}
{268}{}{Sim, é uma tragédia. Bem, até mais!}

{269}{mcs48}{Você já voltou lá, diga-lhes que a guerra acabou. Já faz muito tempo.}
{270}{}{Ummm. Está bem. Eu tenho mais perguntas.}
{271}{}{Sure thing. Tchau.}

{272}{mcs49alt}{Obrigado pela ajuda. Poderia ter sido um problema. Nós pegamos seu cache de armas e desativamos suas bombas.}
{273}{}{Ótimo! Eu tenho algumas questões...}

# Not using
{274}{}{Ei, encontrei algo.}

# Not using
{275}{}{Não aprendi nada.}

# I'm leaving you responses
{276}{mcs103a}{Muitas pessoas. Eu fiz minhas viagens com uma horda.}
{277}{mcs103b}{Eu pensei que você era um dos bons. Eu não vou com você.}
{278}{mcs103c}{Eu não vou com você agora. Desculpa. [Ele olha você para cima e para baixo com desagrado.]}
{279}{}{Tudo certo.}

# 104. Fear/Defeat Floats, are we using?
{280}{}{Isso me assusta.}
{281}{}{Não há muito no terremoto me assusta ... isso sim.}

# 105. Victory Floats, are we using?
{282}{}{Você deve ser tão estúpido quanto você parece se vai lutar contra mim.}
{283}{}{Kickin 'alguma bunda ... novamente.}
{284}{}{É quase tão fácil.}

# 106. Combat Taunt Floats, are we using?
{285}{}{Você não tem alguns amigos que podem ajudar você mesmo?}
{286}{}{Teve o sufuciente?}

# 107. Skill use Success Confirm Float, are we using?
{287}{}{Consegui. Só assim você sabe.}

# 108. Skill use Failure Confirm Float, are we using?
{288}{}{Humph. Algo não estava certo.}

# 109. Rejoin Party, NEEDED. Waiting for Voc file.
{289}{mcs109}{Você me quer de volta agora?}
{290}{}{Está bem.}
{291}{}{Ainda não. Adeus.}

# 110. NPC in party
{292}{mcs110}{O que você quer?}
{293}{}{Como você está se sentindo?}
{294}{}{Cure você mesmo.}
{295}{}{Preciso que você espere até eu voltar.}
{296}{}{É por enquanto.}

# 111. Heal Yourself
{297}{mcs111a}{Tudo pronto.}
{298}{mcs111b}{Não tem nada que nos desacelere.}
{299}{mcs111c}{Você conseguiu algo para ajudar?}
{300}{mcs111d}{Talvez você deva dar uma olhada nisso.}
{301}{}{Use suas habilidades para se curar.}
{302}{}{Deixa pra lá.}
{303}{}{Está bem}

# 112. Wait here
{304}{mcs160}{Eu vou ficar aqui e apertar as calças no meu ombro.}
{305}{}{Deixa pra lá.}
{306}{}{Está bem}

# Prases, Not using any but 2 and those are duplicated at the bottom
# Lines 317 is now 20,000 and 315 is 20,001
# Lines 307 through 348
{307}{}{Norte.}
{308}{}{Noroeste.}
{309}{}{Oeste.}
{310}{}{Sudoeste.}
{311}{}{Sul.}
{312}{}{Sudeste.}
{313}{}{Leste.}
{314}{}{Nordeste.}
{315}{}{Não me pergunte. Eu não sei.}
{316}{}{Sim.}
{317}{}{Certo.}
{318}{}{Não.}
{319}{}{Por que você está falando comigo assim?}
{320}{}{Não é muito bom.}
{321}{}{Obrigado.}
{322}{}{Isso é bom.}
{323}{}{Isso não é bom.}
{324}{}{Eu gosto disso. Muito.}
{325}{}{Eu tenho um mau pressentimento sobre isso.}
{326}{}{Essas pessoas são loucas.}
{327}{}{Não aprendi nada.}
{328}{}{Aprendi algo.}
{329}{}{Alguém está aqui sã?}
{330}{}{Tenho que ser de outra maneira.}
{331}{}{Me siga.}
{332}{}{Tente isso.}
{333}{}{Venha aqui.}
{334}{}{Encontrou algo que você pode querer ver.}
{335}{}{Tanto quanto eu posso dizer, é seguro acampar aqui.}
{336}{}{Não é seguro acampar aqui.}
{337}{}{Podemos descansar aqui.}
{338}{}{Eu tive sorte.}
{339}{}{Corrija isso, você poderia?}
{340}{}{Vire isso.}
{341}{}{Essa coisa precisa ser desbloqueada.}
{342}{}{Você vai abrir isso?}
{343}{}{Poderia querer voltar aqui mais tarde.}
{344}{}{Eu não entendo.}
{345}{}{Não sei.}
{346}{}{Ow.}
{347}{}{Isso realmente dói.}
{348}{}{Isso não pode se sentir bem ...}

# Player responces leading to pregnancy
{349}{}{Uh ... quando você disse 'Espero que ela não fique grávida' na Pata do gato em New Reno,
 o que você quis dizer?}

# 113. Waiting for Vocs.
{350}{mcs113}{Os pais não explicaram isso?}
{351}{}{Não, quero dizer, pensei que todos vocês mutantes estavam estéril.}
{352}{}{Deixa pra lá.}

# 114. Waiting for Vocs.
{353}{mcs114}{O que? Onde diabos você ouviu isso?}
{354}{}{Então ... você não é estéril?}
{355}{}{Deixa pra lá.}

# 116. Waiting for Vocs.
{356}{mcs116}{Não. Well, not now. It takes a few years after bein' dipped to get the juices flowing again. Why?}
{357}{}{Oh. Uh. Deixa pra lá.}

# Exp description
{360}{}{Você expôs a conspiração contra os mutantes de Broken Hills.}
{361}{}{Marcus concordou em se juntar à sua festa.}

# Additional Player responses
{400}{}{Sobre as pessoas desaparecidas ...}
{410}{}{Sobre Jacob e Aileen ...}
{420}{}{Sobre o Chade ...}
{430}{}{Sobre os convictos escapados ...}
{440}{}{Sobre um cientista da NCR ...}

# Float, Pissed
{500}{}{Você tem muito nervo mostrando seu rosto aqui novamente.}

# Player additional responses
{501}{}{Deixa pra lá. Could I ask you something?}
{502}{}{Deixa pra lá. Tchau.}

# Marcus floats
{600}{}{Eu não me sinto tão bem, chefe.}
{601}{}{Não faça isso.}
{602}{}{Você não acha que este lugar é um pouco assustador?}
{603}{}{Espero que você tenha adeus do quadril ... nós estamos caminhando em alguma merda pesada.}
{604}{}{Eu não gosto muito dos looks desse lugar.}
{605}{}{Este osso quebrado pode apenas moer tanto antes de passar, chefe.}
{606}{}{Ahh, humanidade.}
{607}{}{Agora, este é um bom exemplo de por que o Mestre estava certo.}
{608}{}{E você pensou que os mutantes estavam doidos.}
{609}{}{Cuidado aqui, chefe. Esses caras parecem difíceis.}
{610}{}{Homem ... vocês, humanos, nunca deixam de me surpreender.}
{611}{}{Espero que você saiba para onde vamos ...}
{612}{}{Vamos chutar seus jumentos, chefe.}
{613}{}{São idiotas como estes que me deixam louco.}
{614}{}{Ahh, em casa novamente.}
{615}{}{Não esqueça ... Ajudei a construir este lugar. Seja bom.}
{616}{}{É bom ver o 'ol homestead novamente.}
{617}{}{Eu sempre detestei esse lugar.}
{618}{}{Quando nós saimos?}
{619}{}{Vamos sair daqui.}
{620}{}{Não pense que eu sou procurado aqui, chefe.}
{621}{}{Então é aí que tudo começou, eh?}
{622}{}{Vamos curar aqui, hein?}
{623}{}{Quer jogar, cachorro?}
{624}{}{Remova, cachorro! Fingir de morto!}
{625}{}{Ei, cachorro! Sic 'em!}
{626}{}{Ei, Lenny! Você já vai para Broken Hills?}
{627}{}{Lenny! Vamos beber alguma coisa!}
{628}{}{É bom ter outro humano evoluído no grupo, Lenny.}
{629}{}{Hey Myron! Quer wreslte?}
{630}{}{Não se preocupe, pequeno Myron. Eu vou cuidar de você.}
{631}{}{Confira o grande cérebro no Myron!}
{632}{}{Phwheew !!! Alguém acabou de cortar um muffin?}
{633}{}{[apito] Margarida, margarida ... [cantar]}
{634}{}{Cara, eu tenho um bocado de wedgie.}
{635}{}{Na minha idade, é bom desacelerar de vez em quando.}
{636}{}{Apenas observando as nuvens ...}
{637}{}{Zzzzzzzzz.}
{638}{}{Obrigado chefe.}
{639}{}{Uh ... obrigado, amigo.}
{640}{}{Err ... obrigado. Eu acho.}
{641}{}{Obrigado.I was thirsty.}
{642}{}{Whoa ... eu me sinto um pouco engraçado.}
{643}{}{Eu acho que Francis tinha razão sobre Jacob. Esse bastardo assassino não causará mais problemas nesta cidade.}
{644}{}{Você recebeu um rifle de caça escopo.}
# End of Floats

# Marcus Dialog, in party response
{1100}{mcs43alt}{Não é um problema.}

# Player responses
{3000}{}{Vamos sair.}
{3100}{}{Esqueça que eu perguntei então, idiota.}
{3200}{}{Deixa pra lá então. Sua perda.}
{3300}{}{Darn. Talvez mais tarde.}

# Player responses, that should have been replaced by new party format. Keeping just to be safe
{9999}{}{Queria fazer algumas perguntas ...}
{10001}{}{Tire um pouco mais e se cure.}
{10002}{}{Marcus, Preciso que você espere até eu voltar.}
{10003}{}{Coloque sua arma longe.}
{10004}{}{Fica perto de mim.}
{10005}{}{Não fique tão longe.}
{10006}{}{Devemos nos espalhar um pouco.}
{10100}{}{Vamos, Marcus. Tempo para sair.}
{10007}{}{Vamos então.}


# New Marcus dialog for new party structure, waiting for Vocs, from Phrases 81 and 79
{20000}{mcs81b}{Certo.}
{20001}{}{Heh. Eu posso usar quase qualquer arma grande, como foguetes ou miniguns,
 e as grandes armas de energia. Eu não estou mal com meus punhos, e eu sou um tiro com granadas. Eu não
 use armadura. Eles simplesmente não conseguem o meu tamanho.}
