{100}{}{Você vê um mutante em roupas empoeiradas segurando uma picareta.}
{101}{}{Você vê um mineiro mutante.}
{102}{}{Você vê um mutante em roupas empoeiradas segurando uma picareta. From the calluses on his hands and the
 tired expression, you figure out this mutant must be a miner. He looks tired, and a little confused.}

{103}{}{Whaddya quer?}
{104}{}{Ag-ag! Ooo!}
{105}{}{Ork! Ooky!}
{106}{}{Dallo?}
{107}{}{Dallo!}
{108}{}{O que há para fazer aqui?}
{109}{}{Quem é Você?}

{110}{}{Oh, bom. Um idiota. Tocada pela radiação, eh, amigo? Não consigo entender você. Não posso ajudá-lo.}

{111}{}{Eu disse que não posso ajudá-lo! Vá embora e incomodar alguém!}

{112}{}{O que há para fazer? Bem, a mina está fechada porque não temos um purificador de ar que
 trabalho. Há o salão. Há os caravanes, e há a loja geral. É sobre isso.
 Espere ... do que estávamos falando?}
{113}{}{Com quem falo sobre a mina?}
{114}{}{Onde está o salão?}
{115}{}{Onde estão os caravanes?}
{116}{}{Onde está a loja geral?}
{117}{}{Obrigado. Tchau.}

{118}{}{Apenas um dos mineiros. Você quer alguém importante?}
{119}{}{Sim.}
{120}{}{Não.}
{121}{}{Tchau.}

{122}{}{Os moventes e agitadores da cidade são Marcus, que é um pouco o prefeito e xerife, Zaius, quem é
 O capataz da mina e o Chade, que dirige a caravana. Phil the bartender é o líder dos ghouls, acho ...
 Se você pode dizer que eles têm um líder. Quem era você novamente?}
{123}{}{Onde posso encontrar Marcus?}
{124}{}{Onde posso encontrar Zaius?}
{125}{}{Onde posso encontrar Cameron?}
{126}{}{Onde posso encontrar o Chade?}
{127}{}{Onde posso encontrar Phil?}
{128}{}{Obrigado. Tchau.}

{129}{}{Se você acha que pode ajudar na mina, vá falar com Zaius. Ele geralmente está na cabana do capataz
 Fora da mina. Ele está de mau humor porque o purificador de ar está desligado. Algo mais?}

{130}{}{Phil the ghoul dirige o salão. Ele é o porta-voz dos ghouls da cidade. Você pode encontrar
 Ao leste do banco. Algo mais?}

{131}{}{Chad corre as caravanas para fora do seu lugar na extremidade sudoeste da cidade. Algo mais?}

{132}{}{Liz, que é um tipo decente para um humano, corre a loja geral, a oeste do banco. Algo mais?}

{133}{}{Tudo bem então. Até logo.}
{134}{}{Cameron é o líder dos humanos normais aqui. Ele não gosta muito de mutantes ou ghouls, mas ele
 Nos trata bem. Ele é um político, então você geralmente o encontrará no banco ou no salão. As vezes você
 Pode até encontrá-lo trabalhando no ferreiro. Algo mais? E onde eu estou, afinal? Oh, sim ... então ... qualquer coisa
 outro?}

{135}{}{Marcus é nosso líder. Ele ajudou a encontrar Broken Hills. Você geralmente pode encontrá-lo no Banco ou
 a prisão. Algo mais?}

{136}{}{Bastardo ganancioso. Você sabe o quanto nós trabalhamos? Espero que você apodreça.}

{137}{}{Obrigado pelo minério!}

{138}{}{Não posso acreditar que a mina explodiu. Todos nós morreremos de fome agora. Essa foi a
 Só mantendo essa cidade em pé. Bem, pelo menos eu posso ir senil sem mais trabalho ...}

{139}{}{Seu desgraçado! Morrer!}

{140}{}{Obrigado por consertar a minha para nós. Nós realmente devemos você por isso. O que posso fazer para você?}
{141}{}{Quem é Você?}
{142}{}{O que há para fazer nesta cidade?}
{143}{}{Nada.}

{144}{}{Nós devemos você por nos salvar daqueles bastardos NCR. Obrigado, amigo. O que posso fazer para você?}
{145}{}{Quem é Você?}
{146}{}{O que há para fazer nesta cidade?}
{147}{}{Nada.}
