{100}{}{Você vê um velho mutante.}
{101}{}{Você vê um velho mutante, um residente de Broken Hills.}
{102}{}{Ao examinar mais de perto, você vê um mutante em envelhecimento. A força nos músculos do mutante ainda é
 Aparente, como é o orgulho defensivo com o qual se carrega.}

{103}{}{Eu acho ... que ... o gás de radão mantém os mineiros jovens.}
{104}{}{Estou perdendo minhas lembranças ... tudo voltou para mim ... espere ...}
{105}{}{Você já ouviu falar que os humanos estão planejando matar-nos?}
{106}{}{Gostaria de sermos mais aceitos pelos humanos. Somos humanos a nossa maneira.}
{107}{}{Como o mundo está fora? Eu não ouço muito hoje em dia.}
{108}{}{Alguém disse que o VEF que nos fez está nos tornando senil.}
{109}{}{Tudo parece estar se afastando de mim. Eu costumava ser forte e rápido ... agora eu sou um pouco mais
 Do que um humano, parece.}
{110}{}{O que a vida importa quando tudo termina de qualquer maneira?}

{132}{}{Quem deixou esses cachorros? Eu vou esmagá-los!}
{133}{}{Franc e Manson melhor ficam escondidos ... Eu vou esmagar seus crânios com a mão aberta se eu os pegar.}
{134}{}{Franco. Manson. Scum o 'the earth.}
{135}{}{Pequenos fuckwads são livres para matar novamente, hein?}
{136}{}{Devemos ter um grupo de busca naqueles dois.}
{137}{}{Eu não vou dormir fácil até que esses loucos estejam mortos.}
{138}{}{Pensa em segurança.}
{139}{}{Bem ... ummm ... quem era você?}

{140}{}{Franc e Manson se comportarão? Essa é uma promessa feita em Stockton se eu alguma vez ouvi uma.}
{141}{}{Nós não agradeceremos se esses dois shitheads causam mais problemas, você sabe.}
{142}{}{Tudo bem ... Estou disposto a dar a esses dois wankers uma chance ...}
{143}{}{Como chego em casa?}
{144}{}{Eu não conversei com você?}
{145}{}{Eu não vou dormir fácil até que esses loucos estejam mortos.}
{146}{}{Pensa em segurança.}
{147}{}{Bem ... ummm ... quem era você?}

{148}{}{Eu sabia! Eu sabia que os golpes de merda o tinham para nós!}
{149}{}{Nunca confiei no Jacob bastard.}
{150}{}{Então ... os humanos tentam nos matar. Talvez nós os matemos.}
{151}{}{Não todos os humanos estão fazendo isso, certo?}
{152}{}{Bem, bem, bem ... mais trapaça humana?}
{153}{}{Perco mais todos os dias ... minhas memórias e minha fé na humanidade foram hoje.}
{154}{}{Você é um bom, você é.}

{162}{}{Francisco está impressionado. Eu também sou.}
{163}{}{Como um humano pode vencer um braço-wrestling mutante? Você enganou?}
{164}{}{Então, como você vai usar seu novo prêmio?}
{165}{}{Forte. Muito forte.}

{166}{}{Uma vez que você conhece um mutie, você nunca voltará.}
{167}{}{Eu ouvi você ser legal e sim ... para Francis.}
{168}{}{Estou surpreso por você mesmo estar andando.}
{169}{}{Heh ... Francis pode ser velho, mas ele ainda conseguiu!}

{170}{}{Aqueles pobres.}
{171}{}{Estando preso debaixo do chão ...}
{172}{}{Eu disse então, eu disse: "Jacob e Aileen são problemas. Então são Franc e Manson". Mas alguém
 ouço? Noooooo.}
{173}{}{Túneis, hein? Eu sempre sabia que esses bastardos eram ratos e vermes.}
{174}{}{Então, esses corpos são o que esse mau cheiro era, hein?}

{175}{}{Por que você nos machucou?}
{176}{}{Os seres humanos nunca confiam em mim.}
{177}{}{Me deixe em paz.}
{178}{}{Por que você não morreu já?}
{179}{}{Por que os humanos sempre esmagam o que temem?}
{180}{}{Você é escória.}
{181}{}{Sua vida não vale a pena.}
{182}{}{Você ... Lembro-me de uma pessoa como você ...}
{183}{}{Eu sou velho demais para te odiar.}
