{100}{}{Você vê um homem de tamanho médio vestindo roupas empoeiradas.}
{101}{}{Você vê Bill, o Outfitter.}
{102}{}{Você vê um homem de tamanho médio com roupas empoeiradas. Ele cheira como se estivesse cuidando de brâmane.}

{103}{}{Howdy, pard. O que posso fazer para você?}
{104}{}{Nimma ardle ah!}
{105}{}{Você dá trabalho?}
{106}{}{Estou à procura de trabalho.}
{107}{}{Preciso comprar coisas.}
{108}{}{O que você pode me falar sobre o Chade?}
{109}{}{Desculpe pelo Chade. Ele tinha chegado.}
{110}{}{Adivinhe seu mestre de caravanas Chad está com uma merda profunda agora.}
{111}{}{Quem é Você?}

{112}{}{Desculpe, criança, mas não consigo entender o que você está dizendo. Tem um pirulito.}
{113}{}{Oooh!}

{114}{}{Certo. Há um monte de brahmin cagar de volta. Pára por um dia e eu lhe darei $ 100.
 Combinado?}
{115}{}{Você quer um emprego? Bem, nós temos duas opções: Empurre o esterco brahmin por um dia por US $ 100, ou você pode
 Acompanhe uma de nossas caravanas por US $ 200. Nós adquirimos caravanas para Gecko, New California Republic e Vault
 Cidade.}
{116}{}{OK!}
{117}{}{Naw.}
{118}{}{Eu vou empurrar a porcaria por um tempo.}
{119}{}{Vou fazer a caravana para Gecko.}
{120}{}{Vou fazer a caravana para a NCR.}
{121}{}{E a Vault City?}
{122}{}{Eu mudei de ideia. Gostaria mais de uma coisa.}
{123}{}{Tchau!}

{124}{}{Sim? O que você quer comprar?}

{125}{}{Você recebeu perguntas sobre o Chade? Como o quê?}
{126}{}{Ele está saindo do topo?}
{127}{}{Você confia nele?}
{128}{}{O que você pode me falar sobre ele?}

{129}{}{Eu? Eu sou Bill. Eu sou, como o homem disse, o Bill que você tem que pagar. Embora tecnicamente, suponho,
 às vezes eu pago você. Eu sou o superintendente da caravana para esta cidade. Planejo as rotas de caravanas e
 providenciar o provisionamento. Empacoço pessoas para empregos, e eu também sou responsável pelas Patrulhas da Unidade.}
{130}{}{Empregos? Que tipo de emprego?}
{131}{}{Obrigado. Tchau!}

{132}{}{Tudo certo. Iniciar.}

{133}{}{Não interessado? Tudo certo. Volte quando eu posso fazer algo por você.}
{134}{}{OK!}
{135}{}{Bem, na verdade, eu estava interessado em outra coisa.}
{136}{}{Tchau.}

{137}{}{Tudo certo. Gecko é. Volte no dia 1 do mês e você estará a caminho. Quer alguma coisa mais?}
{138}{}{Sim.}
{139}{}{Não.}

{140}{}{Tudo certo. A República é. Volte no dia 11 do mês e você estará no seu caminho. Quer alguma coisa mais?}
{141}{}{Tudo certo. Vault City é. Volte no dia 21 do mês e você estará no seu caminho. Quer alguma coisa mais?}

{142}{}{O que você quer?}
{143}{}{Estou à procura de trabalho.}
{144}{}{Preciso comprar coisas.}
{145}{}{O que você pode me falar sobre o Chade?}
{146}{}{Desculpe pelo Chade. Ele tinha chegado.}
{147}{}{Adivinha o seu mestre de caravana com uma merda profunda agora.}
{148}{}{Quem é Você?}

{149}{}{Muito bem com você. Você quer algo mais de mim?}
{150}{}{Desculpa. Isso não o corta para mim. Você quer algo mais de mim?}
{151}{}{Não. Tchau!}

{152}{}{Sim? Ótimo. Aqui estão os seus $ 100, e se você precisar de mais alguma coisa, deixe-me saber.}

{153}{}{Pal, volte em uma hora ou duas e ficarei feliz em vender-lhe algo. Agora estou ocupado
 com estes brahmin. Você quer mais alguma coisa?}

{154}{}{Ele está saindo do topo? Not as far as I can tell. For a load of uranium, we charge $5,000.
 We get back $5,000. Ain’t no skimming there, far as I can tell. He’s got a nice place and always seems
 to have plenty of cash, but he might’ve brought that with him when came here.}
{155}{}{Eu tenho mais algumas perguntas.}
{156}{}{Eu quero algumas outras coisas.}
{157}{}{Entendo. Isso é tudo. Obrigado.}

{158}{}{Eu confio nele? Obviamente ... até certo ponto. Eu confio nele para dirigir minhas caravanas para mim. Ele pode ser
 sombrio, mas até me dar uma razão para não confiar nele, continuarei como eu.}
{159}{}{Eu tenho mais algumas perguntas.}
{160}{}{Eu quero algumas outras coisas.}
{161}{}{Ótimo. Obrigado pelo seu tempo.}

{162}{}{Locatário. Ele veio para Broken Hills fora do deserto. Ele não tinha muito, mas sua sabedoria. Ele olhou
 como se estivesse sendo caçado por alguém, mas não dizia quem. Ele sempre ficou calmo sobre o passado.
 E ... ele é um mestre do caravana. Isso é tudo.}
{163}{}{Eu tenho mais algumas perguntas.}
{164}{}{Eu quero algumas outras coisas.}
{165}{}{Obrigado.}

{166}{}{Estou fora de serviço agora. Fale comigo quando estou na loja.}

{167}{}{Ele tinha vindo? Você é uma merda, não vale a pena matar o dinheiro. Saia do meu
 loja.}
{168}{}{Tchau.}

{169}{}{Qualquer problema em que ele esteja, ele fez para si mesmo. Muito ruim ... ele era um mestre do caravana. Você quer
 alguma coisa?}

{170}{}{Fora da minha loja. Você queria aqui.}

{171}{}{Você está pronto para ir a Vault City?}

{172}{}{Pronto para ir para a NCR?}

{173}{}{Você está pronto para ir ao Gecko?}

{174}{}{Caravana cancelada. Nós não estamos enviando mais nada para esse pedaço de mentira, não se
 Eles vão tentar matar nossa gente. Você quer alguma outra coisa?}

{175}{}{Você está rastejando na minha caravana?}
{176}{}{Bem, preciso de mais tempo aqui.}
{177}{}{Eu queria mudar as atribuições de caravanas.}

{178}{}{Mais tempo? Bem. Você ganhou mais tempo. Volte quando você pretende cumprir suas responsabilidades.}

{179}{}{Mudança? Qual caravana você quer? Gecko sai no 1º, NCR no dia 11, e Vault City no dia 21.}
{180}{}{NCR.}
{181}{}{Gecko.}
{182}{}{Vault City.}

{183}{}{Sim? Bem. Saia da minha loja. Volte quando você tem coragem suficiente para fazer a viagem.}

{184}{}{Ótimo. Então, continue.}
{185}{}{Eu queria algo mais primeiro.}
{186}{}{Tudo certo.}

{187}{}{Pal, não posso fazer mais nada por você agora. Com todos os mutantes mortos, não temos ninguém para trabalhar o
 mina efetivamente. Essa cidade vai fantasma em um ano ou dois. Não há mais nada aqui. Tanto tempo.}

{188}{}{Desculpe, amigo. Não tenho nada para você fazer mais. Ya tachou toda a porcaria que eu tinha.}
{189}{}{Você quer um emprego? Bem, ao ver como você empurrou toda a porcaria do brahmin, tudo que eu tenho à esquerda é caravanas.
 Você pode escoltar um deles por US $ 200. Nós adquirimos caravanas para o Gecko, a Nova República da Califórnia,
 e Vault City. Eles saem uma vez por semana.}
{190}{}{Awwwww darrn. Me lyk braaaamin craaap. Bye Tchau.}
{191}{}{Você quer um emprego? Bem, ao ver como você empurrou toda a porcaria do brahmin, tudo que eu tenho à esquerda é caravanas.
 Você pode escoltar um deles por US $ 200. Nós adquirimos caravanas para Gecko e Vault City. Eles saem uma vez por semana.}
{192}{}{Você quer um emprego? Bem, nós temos duas opções: Empurre o esterco brahmin por um dia por US $ 100, ou você pode
 Acompanhe uma de nossas caravanas por US $ 200. Nós adquirimos caravanas para Gecko e Vault City. Eles saem uma vez por semana.}

{193}{}{Você se tornou um expedidor experiente excremento!}
{194}{}{Sua habilidade de fala aumentou 5%.}

{195}{}{Vou pegar uma caravana.}
{196}{}{Você já disse que iria ao Gecko no dia 1 de mês.}
{197}{}{Você já disse que iria para a NCR no dia 11 do mês.}
{198}{}{Você já disse que iria a Vault City no dia 21 do mês.}

{200}{}{Gostaria de mudar de caravana.}
{201}{}{Ah, está certo. Deixa pra lá.}
{202}{}{Seu desgraçado! Você abandonou a maldita caravana! Saia já daqui!}
{203}{}{Deixa pra lá. Eu vou passar as caravanas por enquanto.}

{204}{}{Tudo certo. Gecko it is. The caravan leaves today. Are you ready to go?}
{205}{}{Tudo certo. The Republic it is. The caravan leaves today. Are you ready to go?}
{206}{}{Tudo certo. Vault City it is. The caravan leaves today. Are you ready to go?}
{207}{}{Sim, estou tudo pronto. Vamos.}
{208}{}{Not quite yet. I'll let you know when I'm ready. Obrigado.}
{209}{}{Not yet. I'll let you know when I'm ready. Eu tenho mais algumas perguntas.}

{210}{}{Obrigado.}
{211}{}{[continuar]}

{212}{}{Me desculpe, mas sem o Chad para ajudar a administrar pessoal, não posso deixar o trabalho como costumava fazer. Vou sentir falta
 aquele pobre bastardo. Dyin 'fora nos desperdícios como algum brahmin ferido.}
{213}{}{Sorry. Tchau.}
