{100}{}{Você vê um ghoul vestindo um avental.}
{101}{}{Você vê Phil, o barman. Ele está lavando um copo.}
{102}{}{Você vê um ghoul usando um avental e lavando um copo. Vendo como ele está logo atrás do bar, você
 Suponha que ele é o barman deste salão.}

{103}{}{Howdy, estranho. Bem-vindo à cidade. Qual o seu nome?}
{104}{}{Doi?}
{105}{}{!}
{106}{}{.}
{107}{}{Nenhum dos seus negócios, amigo.}
{108}{}{Bem, estou meio disfarçado agora mesmo.}

{109}{}{Doi é o seu nome? Ha! Apenas brincando, amigo. Aqui. Tenha um Nuka-Cola. Tente não incomodar o outro
 clientes.}
{110}{}{Ganks!}

{111}{}{Eh? Bem, prazer em conhecê-lo, bucko. Quer algo para beber?}
{112}{}{Grink sim!}
{113}{}{Ah não. Não não não não.}

{114}{}{, prazer em conhecê-lo. Eu sou Phil. Eu possuo este lugar. Agora ... o que será?}
{115}{}{Nuka-Cola.}
{116}{}{Cerveja.}
{117}{}{Rotgut.}
{118}{}{Nada.}
{119}{}{Nada, desculpa. Tchau!}

{120}{}{Tudo bem, amigo. Seja assim. Eu sou Phil. Eu possuo esse lugar e administra-o. O que será?}

{126}{}{Em segredo, hein? Acho que posso entender isso. Eu sou Phil, por sinal. O que será?}

{132}{}{Você quer cerveja? Rotgut? Nuka-Cola?}
{133}{}{Deer!}
{134}{}{Notblut!}
{135}{}{Gola!}

{136}{}{Bem, você me deixa saber quando quer algo e eu vou te arrumar, amigo. Nao tente
 Perturbe os outros clientes, tudo bem?}
{137}{}{O-tay!}

{138}{}{É uma cerveja. Isso será $ 3, mais uma dica de US $ 1 para mim. Isso é $ 4, kiddo.}
{139}{}{'Antes!}
{140}{}{Não tem.}

{141}{}{Bebida poderosa, rapaz! Isso é $ 5, mais uma dica de US $ 1 para mim, o que faz US $ 6,00.}
{142}{}{Bebida poderosa, moça! Isso é $ 5, mais uma dica de US $ 1 para mim, o que faz US $ 6,00.}

{145}{}{Bom para você, bom para sua pele. São $ 2. Eu até vou te deixar sem me derrubar. Isso é
 $ 2, direto para cima.}

{148}{}{. Você precisa de mais alguma coisa para beber, você vem de volta para me ver.}
{149}{}{Otay!}

{150}{}{! Você quer algo para beber?}
{151}{}{Grink 'es!}
{152}{}{Grink não!}

{153}{}{Ei, Doi! Bem vindo de volta. Tinha seu assento aquecido para você lá.}
{154}{}{Anks!}

{155}{}{Isso será $ 2.}
{156}{}{Isso será $ 4.}
{157}{}{São $ 5.}
{158}{}{Lá você vai.}
{159}{}{[Dê Phil a $ 1 Dica] Aqui está, Phil.}
{160}{}{[Dê Phil a $ 2 Tip] Obrigado, Phil.}
{161}{}{Ops, toplo.}

{162}{}{Nada? Ha. Ha. Você não se estaciona aqui sem beber alguma coisa, amigo. Eu tenho que pagar
 As contas também. Vamos tentar isso de novo. ASSIM! O que será?}
{167}{}{Esqueça. Estou fora daqui.}

{168}{}{Até que você esteja comprando, eu não estou falando. Qual é o seu prazer?}
{173}{}{Esqueça isso e esqueça suas lindas bebidas!}

{174}{}{Obrigado. Algo mais?}
{175}{}{Ei, obrigado! Algo mais?}
{176}{}{Uau! Obrigado! Mais alguma coisa que eu possa fazer por você?}
{177}{}{Quero mais beber.}
{178}{}{O que tem acontecido na cidade?}
{179}{}{O que há para fazer aqui?}
{180}{}{O que há de novo?}
{181}{}{Nada. Forget it.}

{182}{}{Tapped, hein? Que pena. Você pode ficar por aqui, mas não se preocupe com os clientes. Eu tenho trabalho para fazer.
 Até logo.}
{183}{}{Tchau!}

{184}{}{Ei! Bem vindo de volta. O que será?}
{185}{}{Bem-vindo de volta, pard. O que será?}
{186}{}{Você novamente? O que será?}
{187}{}{Você novamente? Whaddya quer?}
{192}{}{Para lhe dizer meu nome. Está}
{193}{}{Nada, desculpa. Tchau!}

{194}{}{Bem, tudo bem então! O que será?}

{198}{}{O que tem acontecido na cidade? Well… a couple of loons’ve been locked up for spreading hate
 propaganda. Mine’s purifiers are down. Caravans all over the place. That’s about normal.}
{199}{}{Obrigado. Tenho mais perguntas.}
{200}{}{Obrigado. Tchau.}

{201}{}{O que fazer, o que fazer ... vamos ver ...}
{202}{}{- Mais -}

{203}{}{Alguém queixou esses lunáticos da prisão!}
{204}{}{Alguém destruiu a mina! A cidade está condenada!}
{205}{}{Todos os mutantes estão mortos!}
{206}{}{Não muito.}
{207}{}{Tenho mais perguntas.}
{208}{}{Obrigado. Até mais.}

{209}{}{Você parece um cara muito corpulento. Estou apostando que você poderia lutar com Francis. Ele é o
 Mutante sentado lá. Aparentemente ele tem um prêmio de algum tipo. Interessado? Vá falar com Francis.}
{210}{}{Obrigado. Mais alguma coisa?}
{211}{}{Obrigado. Até mais.}

{212}{}{Há algumas pessoas desaparecidas. Não temos certeza de onde eles estão. Se você pudesse encontrá-los, tenho certeza
 Haveria algo para você. Você quer começar com isso? Vá falar com Marcus.}
{213}{}{Obrigado. Algo mais?}
{214}{}{Obrigado! Falo com você mais tarde.}

{215}{}{Hmm. Os purificadores de ar da mina estão quebrados. Você pode querer falar com Zaius, o mestre da mina,
 sobre isso.}
{216}{}{Tudo certo. Algo mais?}
{217}{}{Obrigado. Até mais.}

{218}{}{Eu entendo que você pode empurrar a mina agora. Inferno, se você encontrar alguma coisa, você pode até
 Consiga mantê-lo.}
{219}{}{Você conseguiu algo mais?}
{220}{}{Obrigado.}

{221}{}{Isso aí! Descubra onde foram esses dois lunatics Franc e Manson!}
{222}{}{Estou com isso.}
{223}{}{Consegui. Até mais.}

{224}{}{Sempre há uma caravana dirigida para fora em algum lugar. Se você quer fazer parte de uma dessas, você pode
 Fale com o Bill, o Outfitter. Além disso, não temos muito o que fazer neste lugar. Desculpa.}
{225}{}{Obrigado! Eu tenho mais algumas perguntas.}
{226}{}{Tudo certo. Bem, estou fora daqui. Até mais.}

{227}{}{Sim? Como o quê?}
{228}{}{Quero mais beber.}
{229}{}{O que tem acontecido na cidade?}
{230}{}{O que há para fazer aqui?}
{231}{}{O que há de novo?}
{232}{}{Nada. Forget it.}

{233}{}{Espero que você não se importe comigo, dizendo que as pessoas estão aqui um pouco chateadas com você
 Guardou esse urânio para você mesmo. Você foi avisado. De qualquer forma ... pronto para uma bebida?}
{234}{}{Sim.}
{235}{}{Não. Mas eu tenho algumas perguntas.}

{236}{}{Algumas pessoas podem estar um pouco chateadas com o Chade. Você foi avisado. Pronto para uma bebida?}
{237}{}{Sim.}
{238}{}{Não. Mas eu tenho algumas perguntas.}

{239}{}{Todos os mutantes estão mortos. Alguém explodiu o maldito meu enquanto eles estavam dentro dele. Algum bastardo deve ter
 Lobo gritado e todos acabaram de correr para ajudar. Eu simplesmente não entendo algumas pessoas. Inferno ... Posso pegar uma bebida?}
{240}{}{Sim.}
{241}{}{Não. Mas eu tenho dúvidas.}

{242}{}{Saia do meu bar. Agora. Desprezível.}
{300}{}{!}
{301}{}{.}
{302}{}{Bem,}
{303}{}{Obrigado,}
{304}{}{Oi de novo,}
{305}{}{Ei,}
{306}{}{Você novamente,}

{307}{}{No problem, pal. Here's your drink, too. Ei,anything else I can do ya' for?}
{308}{}{Ei amigo, obrigado por todas as dicas. Lemme 'dá-lhe um em troca. Ouvi dizer que Liz, dono da Loja Geral,
 Mantém uma série de armas em seu porão. Mas você não entendeu isso de mim.}
{309}{}{Gee, obrigado Phil. Vou manter isso sob o meu ... uh ... chapéu, ou algo assim.}
