{100}{}{Você vê um homem aturdido com um casaco de laboratório.}
{101}{}{Você vê o professor. Parece que ele está envolvido em algum esquema louco.}
{102}{}{Você vê um homem aturdido em um colete de laboratório cercado por equipamentos de laboratório. Há um brilho insano em seus olhos.}
{103}{}{Você novamente?}
{104}{}{O que é que você quer? Fora com isso! Eu sou um homem ocupado!}
{105}{}{Noo beezy?}
{106}{}{Teste!}
{107}{}{Quem é Você? E o que é com o escorpião?}
{108}{}{Gostaria de fazer um teste.}
{109}{}{Nada. Tchau.}
{110}{}{Ah,um assunto de teste! Gostaria de fazer um teste,meu amigo?}
{111}{}{Sim!}
{112}{}{Não!}
{113}{}{Você deseja fazer um teste,hein? Você quer testar suas mãos,seus olhos ou seus cérebros?}
{114}{}{'Ands!}
{115}{}{Yeyes!}
{116}{}{Chuva!}
{117}{}{Nenhum!}
{118}{}{Então por que você está desperdiçando meu tempo? Eu disse que estou ocupado,não? Eu tenho muito a fazer para ficar perdendo tempo conversando com pessoas como ... porque ainda falo com você? Dia bom!}
{119}{}{Byeeeeee!}
{120}{}{Err ... sim. Tchau.}
{121}{}{Você deseja fazer um teste,hein? Você quer testar sua destreza manual,sua percepção ou sua inteligência?}
{122}{}{Gostaria de testar minha agilidade.}
{123}{}{Vamos testar meus olhos.}
{124}{}{Que tal minhas inteligências inteligentes?}
{125}{}{Hmm. Nenhum deles. Esqueça.}
{126}{}{Muito bem. Eu vou combinar você contra o escorpião. Vocês tentarão desbloquear essas caixas. Boa sorte.}
{127}{}{Ir!}
{128}{}{Vamos fazer isso.}
{129}{}{Certo. Você ficará atrás deste trilho,e você e o escorpião vão me contar as letras que você lê,de cima para baixo,da esquerda para a direita.}
{130}{}{Ir!}
{131}{}{Consegui. Vamos.}
{132}{}{Você e o escorpião estarão jogando um jogo da minha própria invenção. Eu chamo isso de "xadrez". Você está pronto?}
{133}{}{'Es!}
{134}{}{Sim. Estou pronto.}
{135}{}{Eu sou o Professor. O que faço é o teste de inteligência aplicada. Eu crio compostos químicos para aumentar a inteligência. Eu estou tentando alguns fora deste radscorpion aqui,depois do meu fracasso na planta.}
{136}{}{Você experimentou isso em uma fábrica?}
{137}{}{Gostaria de fazer uma prova.}
{138}{}{Você fez algo que funcione?}
{139}{}{Entendo. Isso é tudo o que eu queria saber. Tchau.}
{140}{}{Claro que eu tentei em uma fábrica! Estou tentando aumentar a inteligência desde o início!}
{141}{}{I see. Você fez algo que funcione?}
{142}{}{Gostaria de fazer uma prova.}
{143}{}{Isso é tudo o que eu queria saber.}
{144}{}{Sim,eu tenho,muito obrigado! Você já ouviu falar de "Mentats"? Eu ajudei a desenvolver um método para fácil produção em massa desse químico! E outros! Muitos outros!}
{145}{}{Tudo bem,tudo bem. Diga,eu gostaria de experimentar minhas habilidades contra seu escorpião.}
{146}{}{Tudo bem,eu acredito em você. Eu simplesmente vou embora.}
{147}{}{Como ... como você pode matar meu escorpião assim? Eu estava perto ... tão perto ...}
{148}{}{Shamble off}

# Agility Test
{200}{}{Woo hoo! BEM QUE,Sr. Exoesqueleto.}
{201}{}{Wooooooo Hoooo!}
{202}{}{Droga!}
{203}{}{Aaaargh!}
{204}{}{::click clack ::}
{205}{}{Como você escolheu um bloqueio com CLAWS?}
{206}{}{Como U pik wiff CLAWS?}
{207}{}{::Chitter ::}
{208}{}{Bem,isso foi um empate.}
# The following 4 strings are used in the phrase:
# "Você perdeu. Escorpião:[SCORE],[Player Name]:[SCORE]."
{209}{}{Você perdeu. Escorpião:}
{210}{}{,}
{211}{}{:}
{212}{}{.}
{213}{}{Errr?}
{214}{}{Você provou que você é tão ágil quanto o radscorpion.}
{215}{}{Here,take these Mentats. You appear to need them.}

# Perception Test
{300}{}{E ... Z ... W ... T ... O ... D ... F ... E..R ... T ... F ... P ... Y .. .J ... M}
{301}{}{Yes,that's correct.}
{302}{}{M ... O ... O ... Moo?}
{303}{}{Uh...no,I'm sorry. That's way off.}
{304}{}{::chitter chitter::::click clack ::::chirp (tail swing)::}
{305}{}{Um lugar para outro! Bom garoto! Menino Gooooood! Suas habilidades de código Morse estão melhorando bem.}
{306}{}{Você provou que você é tão perspicaz quanto o radscorpion.}

# Intelligence Test
{400}{}{Checkmate :: clique ::}
{401}{}{O QUE? Você trapaceou!}
{402}{}{Ecmat?}
{403}{}{Não seja um perdedor dolorido.}
{404}{}{e ... xeque-mate!}
{405}{}{Chekmaaate!}
{406}{}{::Chitter ::Kill plant! ::click-clack-click::}
{407}{}{Você provou que você pode subverter um radscorpion que é mais inteligente que você.}
