{100}{}{Você vê uma planta de esporos.}
{101}{}{Você vê Seymour a planta de esporos.}
{102}{}{Você vê uma planta de esporos que, de algum modo, irradia uma aura de inteligência.}
{103}{}{Oi! Bom tempo que estamos tendo, hein?}
{104}{}{Yoo fala?}
{105}{}{Rrr?}
{106}{}{Com licença, mas esta é a planta que está falando?}
{107}{}{Você está conectado com esse cientista de alguma forma?}
{108}{}{Tchau.}
{109}{}{Sim, eu falo. Melhor que algumas pessoas, parece. Eu sorriria para você agora mesmo, mas eu simplesmente não tenho uma boca. [Risos] Diga, você poderia me fazer um grande favor?}
{110}{}{'Es.}
{111}{}{Nuh.}
{112}{}{Estou procurando um lugar melhor para ser. Aqui é legal e tudo, mas, francamente, essas plantas não são muito para a conversa. Eu estava pensando lá, pelo prédio com todos os ghouls nele ... Você me replantaria?}
{113}{}{'Es!}
{114}{}{Nuh!}
{115}{}{Certo.}
{116}{}{Eu acho que não.}
{117}{}{Ótimo! Tudo o que você precisa fazer é encontrar uma pá, desenterrar-me e me plantar por aí. Quando você fizer isso, vou lhe dizer um segredo.}
{118}{}{OK!}
{119}{}{Nuh uh.}
{120}{}{Tudo certo. Bem, um ... Estarei esperando por você. Não é como se eu tivesse uma escolha, você sabe. Tanto tempo!}
{121}{}{Byeeee!}
{122}{}{Se você mudar sua mente, você sabe onde me encontrar. Abaixei as raízes aqui. Ha ha ha! Apenas um pouco de humor vegetal para você. Oh, não me deixe manter você. Tanto tempo!}
{123}{}{Tchau.}
{124}{}{Bem dito, bem dito! Quão delicioso ver um homo sapiens usar seu cérebro em toda a extensão. Meu querido amigo, você estaria disposto a me fazer um favor?}
{125}{}{'Es.}
{126}{}{Nuh!}
{127}{}{Porque sim! Sim! Muito astutos, amigos, muito astutos. Eu posso ver que você não germinou ontem! Meu companheiro de prova fina, você seria tão gentil para me fazer um favor?}
{128}{}{Certo.}
{129}{}{Acho que não.}
{130}{}{Deee-lightful! Estou muito satisfeito. Basta encontrar uma pá e vir de volta. Quando terminar, talvez eu possa lhe dizer um segredo. Meu amigo, espero que continue a florescer.}
{131}{}{Um, certo. Tanto tempo.}
{132}{}{Eu mudei de ideia.}
{133}{}{Ah, sim, o professor. Ele me criou de uma pequena espora e me nutriu ... mas percebi desde cedo que se eu fosse agir tão inteligente quanto eu realmente
 Sou, ele me cortou em pedaços para me examinar. Então, eu joguei burro e fui plantado aqui. É legal ... mas gostaria de me afastar um pouco.
 Sabe, talvez seja plantado em algum outro lugar ...}
{134}{}{"Subir". De fato.}
{135}{}{Certo. O que você quer?}
{136}{}{Uh... huh. I gotta go. Tchau.}
{137}{}{Então ele ainda tem o escorpião? Essa coisa é um jogador de xadrez médio ... tem muita latido e mordida,
 Se você sabe o que quero dizer ... mas eu sei como vencê-lo. Se você me fizer um favor, eu vou te dizer como.}
{138}{}{Mesmo? Como?}
{139}{}{Isso é fascinante. Uma planta de xadrez. Quão prosaico. Adeus.}
{140}{}{Meu bom amigo, se você me replantar perto da casa dos ghouls lá, ficarei feliz em transmitir meu conhecimento profundo do xadrez.}
{141}{}{É um acordo.}
{142}{}{Não, obrigado. Eu lidar com o escorpião sozinho.}
{143}{}{Ahh, meu amigo, você voltou. Este é um lugar maravilhoso aqui. A sombra é perfeita, e a empresa é simplesmente deslumbrante. Que Typhon, o que é mais difícil! Ele realmente deixa minha seiva intelectual fluir!}
{144}{}{Xadrez?}
{145}{}{O que você mencionou sobre xadrez?}
{146}{}{Tchau.}
{147}{}{Bem, era sobre como vencer o escorpião do professor no xadrez. Meu amigo, é a simplicidade em si.
 O Flying Liver Attack é como um flytrap para esse bug - ele entra diretamente e não pode se livrar. Eu garanto seu sucesso.}
{148}{}{'Anks! Tchau!}
{149}{}{Agradeço a informação! Tchau!}
{150}{}{Minha amiga! O sol brilhava sobre você? Como o dia florece? Você está pronto para o movimento? Eu certamente sou!}
{151}{}{'Es!}
{152}{}{Nuh uh! Sem movimento!}
{153}{}{Vamos.}
{154}{}{Eu mudei de ideia. Eu não quero ajudá-lo.}
{155}{}{Estou tão animado que eu poderia lançar uma nuvem de esporos por completo! Vamos!}
{156}{}{-feito-}
{157}{}{Isso é uma pena, isso é uma pena. Espero que você mude de idéia em algum momento. Talvez o pólen do seu
 A indecisão vai voltar ao meu caminho novamente. Dia bom.}
{158}{}{Uh.}
{159}{}{Bom dia, na verdade.}
{160}{}{Oooh ... o solo aqui sente isso ... diferente. Mais claro, de alguma forma. Provavelmente porque não tenho que compartilhá-lo com
 Essas outras plantas. Ahhh. Ah! Sim! Se você já se deparou com o professor e seu escorpião, lembre-se deste xadrez
 Manobra: é chamado de Flying Liver Attack, eo escorpião não aguenta contra ele.}
{161}{}{'Anks!}
{162}{}{Obrigado. Vou tentar isso. Tchau!}
{163}{}{Gostaria também de lhe dizer que eu conheço o ghoul Typhon dentro deste edifício sabe o paradeiro
 De um tesouro. Talvez isso possa ser útil para você algum dia.}
{164}{}{'Anks! Byee!}
{165}{}{Você já teve tempo para reconsiderar? Você gostaria de me ajudar?}
{166}{}{'Es!}
{167}{}{Nuh!}
{168}{}{Certo.}
{169}{}{Eu acho que não.}
{170}{}{Infelizmente, você não parece ter uma pá. Até que você possa encontrar um, não posso ir. Aguardo seu retorno com pistilo abatido.}
{171}{}{Tchau.}
{172}{}{Psst! Ei! Ei, amigo! Por aqui!}
{173}{}{C'mere! Eu prometo que não vou te machucar.}
{174}{}{Vamos. Você assustou uma planta?}
{175}{}{Por aqui! Vamos lá!}
{176}{}{Sim, sou uma fábrica faladora. Aproxime-se e fale comigo.}
{177}{}{Whoa, amigo. Não basta começar a cavar. Temos que strategize primeiro o movimento. Vamos conversar sobre isso.}
{178}{}{Você replantou Seymour pela casa dos antigos ghouls.}
{179}{}{Haf Shuvl! Plante agora!}
{180}{}{It just so happens I have a shovel right here. Vamos.}
