{100}{}{Você vê um homem sorridente vestido com uma armadura de couro.}
{101}{}{Você vê Steve, o pórtico da Broken Hills.}
{102}{}{Você vê um homem amigável em armadura de couro. Parece que ele fica aqui o dia inteiro aguardando
 com quem falar.}

{103}{}{Olá! Eu sou Steve. Eu sou o cara que pode dizer-lhe onde é onde e o que é o que nesta bela
 Cidade. Posso dirigi-lo em algum lugar, ou dar-lhe alguma ajuda hoje?}
{104}{}{Duh ...}
{105}{}{Noken Heel?}
{106}{}{Conte-me sobre o lugar.}
{107}{}{Quem vive aqui?}
{108}{}{Quem está no comando?}
{109}{}{O que há de novo aqui?}
{110}{}{Que serviços você tem aqui?}
{111}{}{Não. Desculpa.}

{112}{}{Oh céus. Outra criança pobre dos resíduos. Bem, entre. Você encontrará que somos tão hospitaleiros
 como qualquer uma das outras cidades da terra desolada.}
{113}{}{Guyyyyyyyyyy!}

{114}{}{De fato. Boa sorte, errante. E adeus.}
{115}{}{Nood olho!}

{116}{}{Broken Hills. Somos uma cidade mineira. Nós buscamos coisas. Então os vendemos.}
{117}{}{Bedig?}
{118}{}{Stell!}

{119}{}{Está certo. Fora do solo. Nós temos uma mina. Eu não acho que eles tenham um emprego para você lá,
 Apesar. Se você quer um, fale com o Outfitter.}
{120}{}{Oh-kay.}
{121}{}{Vender coisas?}

{122}{}{Nós vendemos o que nós cavamos para outras cidades por aqui. Eles acham útil. Se você quer vender
 Algo, você pode falar com muitos dos comerciantes aqui. De qualquer forma, tenho que voltar ao trabalho. Você ficará bem
 e cuidado aqui, ok?}
{123}{}{Oh-kay! Byeeee!}

{124}{}{Tenho que voltar ao trabalho. Você é bom e cuidadoso aqui, ok?}
{125}{}{Você novamente? Bem, você sabe o que você tem a fazer - seja bom e cuidadoso. Cuidar!}
{126}{}{Oh-kay! Byeeeeeeeee!}

{127}{}{Coloque suas armas fora, parceiro. Você não receberá nenhuma resposta de mim enquanto estiver acenando
 assim como isso.}

{128}{}{Somos uma pequena comunidade de mineração. Nós fomos fundados há várias décadas por nosso xerife, Marcus e
 um homem chamado Jacob. Os dois escolheram este site porque estava perto de alguns depósitos de urânio. Seria
 Você gosta de ouvir mais?}
{129}{}{Sim.}
{130}{}{Não.}

{131}{}{Somos um coletivo de seres humanos, mutantes e ghouls. Não temos tensões raciais que
 praga Vault City; Em nossos olhos, todos são iguais.}
{132}{}{Você mora ao lado de mutantes? Você não sabe que eles são maus?}
{133}{}{Igual?}
{134}{}{Obrigado. Tchau.}

{135}{}{Nomeadamente, o xerife Marcus é responsável pela cidade. Ele ajudou a encontrar, e ele nos ajuda até
 nossas crises. Na verdade, porém, todos na cidade têm voz.}
{136}{}{Isso parece inviável.}
{137}{}{Isso parece uma boa maneira de executar as coisas.}
{138}{}{Continue.}
{139}{}{O cara que ajudou a criar a cidade ainda está no comando? Isso o tornaria muito, muito velho.}
{140}{}{Obrigado. Tchau.}

{141}{}{Além de todos os mutantes sendo DEAD e esta cidade sendo DOOMED ...}
{142}{}{Além de os mutantes estarem mortos e nossa única fonte de subsistência destruída ...}
{143}{}{Além de ser um herói para expor a corrupção em nosso meio ...}
{144}{}{Além de perceber que temos um câncer em nosso meio com a fuga de Franc e Manson ...}
{145}{}{Além da traição de Chade da cidade e da sua justiça - pelo qual todos estão agradecidos -}
{146}{}{Não muito, realmente.}
{147}{}{Eu tenho mais perguntas.}
{148}{}{Tchau.}

{149}{}{Oh. Você novamente.}
{150}{}{Oi de novo.}
{151}{}{Bem vindo de volta.}
{152}{}{Você quer saber mais?}
{153}{}{O que há de novo aqui?}
{154}{}{Quem está no comando?}
{155}{}{Conte-me sobre o lugar.}
{156}{}{Quem vive aqui?}
{157}{}{Que serviços você tem aqui?}
{158}{}{Não, obrigado.}

{159}{}{Nós ganhamos nossa vida refinando o minério que cavamos nas colinas e vendemos para as proximidades
 comunidades como Vault City, Gecko e a Nova República da Califórnia. Usamos alguns nós para o nosso
 próprio poder. Mais?}
{160}{}{Sim.}
{161}{}{Não.}

{162}{}{Todos são iguais. Todos nós viermos dos humanos; todos nós temos o mesmo núcleo embaixo do exterior.
 Para dizer que o mal de alguém apenas por causa de sua aparência indica apenas a ignorância.}
{163}{}{Você está me chamando de ignorante?}
{164}{}{Isso é verdade.}
{165}{}{Não necessariamente. Quem sabe o que o vírus que o transformou fez na sua mente?}
{166}{}{Whatever. Tchau.}

{167}{}{Achamos que funciona bem para nossos propósitos. Além disso, Marcus é eminentemente justo.}
{168}{}{Onde posso encontrar Marcus?}
{169}{}{Tchau.}

{170}{}{Ele é velho. Mas ele está agarrando bem. Veja, ele é um mutante, e aparentemente eles vivem mais do que
 a maioria das outras pessoas.}
{171}{}{Você está deixando um MUTANT executar este lugar? O que você é, nozes?}
{172}{}{Mesmo? Eu teria pensado que a maioria deles teria morrido agora.}
{173}{}{Um xerife mutante, hein? Aposto que a maioria das pessoas aqui é muito legal, então. Isso deve funcionar
 bem.}
{174}{}{Tchau.}

{175}{}{Então, agora estamos vivendo, criando nossa própria versão da civilização e fazendo o nosso melhor
 para evitar ceder a Vault City ou NCR - não precisamos de seu estilo de governo. Isso é tudo.}
{176}{}{Great. Eu tenho mais perguntas.}
{177}{}{Obrigado. Tchau.}

{178}{}{Se você persistir em acreditar, pode julgar a mente de alguém pelo que vê na
 fora, então sim. Você é inegavelmente ignorante.}
{179}{}{Para o inferno com você, amigo. VOCÊ é o ignorante.}
{180}{}{Oh tudo bem. Você tem um ponto.}

{181}{}{De qualquer forma, é tudo o que eu queria dizer. Bem-vindo ao Broken Hills.}
{182}{}{Esperar.}
{183}{}{Tchau.}

{184}{}{Se os mutantes nos pretendessem prejudicar, eles teriam se mudado para nós antes disso. Eles não vão durar
 para sempre - na verdade, a maioria deles está indo senile agora. Construir uma comunidade não vai ajudá-los
 alcançar seus objetivos.}
{185}{}{Você tem um ponto.}
{186}{}{Eles ainda são do mal.}
{187}{}{Tchau.}

{188}{}{Pal, mais eu falo com você, o mais fofo, eu me sinto me tornando. Com uma atitude como essa, você
 não será bem-vinda em Broken Hills. Com licença. Tenho um trabalho a fazer.}
{189}{}{Empurrão.}
{190}{}{Hora de morrer, idiota.}

{191}{}{Nós temos uma mina, uma refinaria, uma taberna, um hotel - o que, a propósito, perdeu seu dono, então nós
 Apenas deixe as pessoas ficarem lá gratuitamente - um hospital, uma loja geral e um químico. Nós cultivamos nossa própria comida.}
{192}{}{All right. Eu tenho mais perguntas.}
{193}{}{Tchau.}

{194}{}{Bem, muitos deles têm. Uma vez que os mutantes são estéril ... ou então eu sou levado a acreditar ... eles estão morrendo
 Fora. Os que ficaram parecem estar ficando senil também. Ainda não Marcus. Ele ainda está tão afiado quanto
 sempre.}
{195}{}{Onde posso encontrar o Marcus?}
{196}{}{Eu tenho mais perguntas.}
{197}{}{Tchau.}

{198}{}{Marcus, você tem certeza de que não quer ficar por aí e nos guiar por um tempo?}
{199}{}{Marcus: Não há futuro nisso. Você vai fazer o bem sem mim.}
{200}{}{-Mais-}

{201}{}{Pal, você não é desejado aqui. Você causou bastante dano.}
{202}{}{-feito-}

{300}{}{Você geralmente pode encontrar Marcus perto do Banco - que também serve como uma prisão mais dura - ou no
 Cadeia. Às vezes ele está na taberna ou em casa, mas ele geralmente trabalha.}

{301}{}{Vadio!}
{302}{}{Droga!}
{303}{}{Hooray!}
{304}{}{Scrollrels!}
{305}{}{Esse bastardo de ratos!}
