{100}{}{Você vê uma coisa mutante estranha com a pele manchada e um sorriso horrível.}
{101}{}{Você vê o supervisor da refinaria.}
{102}{}{Você vê um ghoul. Sua pele parece estar pronta para eliminar a criatura. Parece também
 É facilmente aceito pelos outros habitantes da cidade.}

{103}{}{Você não deveria estar aqui!}
{104}{}{O que você quer?}
{105}{}{Da yagga! Eep oop op!}
{106}{}{Não sei.}
{107}{}{Tenho um pouco de minério a ser refinado.}
{108}{}{Quem é Você?}
{109}{}{O que é este lugar?}
{110}{}{Eu quero urânio.}
{111}{}{Nada.}
{112}{}{Esqueça. Tchau.}

{113}{}{Olha, filho, desculpe-me por não ter mente. Mas você não pode estar aqui. Corra agora.}
{114}{}{-feito-}

{115}{}{Você não pode estar aqui. É perigoso. Corra agora.}
{116}{}{-feito-}

{117}{}{Ótimo. Isso será $ 1000, não há regateios. Você pode pensar que é caro, mas é um roubo
 Considerando o que você obterá para o produto acabado de um comprador interessado.}
{118}{}{É um acordo.}
{119}{}{$ 1000? Isso é ridículo. Esqueça.}

{120}{}{I’m the supervisor of this refinery. O que você quer?}
{121}{}{O que é este lugar?}
{122}{}{Quero um pouco de refinado.}
{123}{}{Eu quero urânio.}
{124}{}{Nada.}

{125}{}{Esta é a refinaria de Broken Hills. Aqui é onde purificamos o minério escavado da mina. o que
 você quer?}
{126}{}{O que é este lugar?}
{127}{}{Quero um pouco de refinado.}
{128}{}{Eu quero urânio.}
{129}{}{Nada.}

{130}{}{Você não tem dinheiro suficiente. Volte quando você faz.}
{131}{}{-feito-}

{132}{}{Tudo certo. Dê-nos um dia e vamos tê-lo pronto para você.}
{133}{}{Ótimo. Tchau.}

{134}{}{Boa sorte ficando refinado em qualquer outro lugar. O processo é perigoso - apenas um profissional
 Deve fazê-lo. Você quer ou não?}
{135}{}{Sim.}
{136}{}{Não.}

{137}{}{Bem. Você não tem nenhum negócio aqui. Saia para que possamos fazer o nosso trabalho.}
{138}{}{Tchau.}

{139}{}{Isso é ridículo. Nós não estamos dando a você.}
{140}{}{Então, morra.}
{141}{}{Fine. Tchau.}

{142}{}{Ei! Afaste-se de lá ou você sofrerá as consequências!}

{143}{}{Saia da minha refinaria! Agora!}

{144}{}{Ainda estamos trabalhando na refinação de seu minério. Dê-nos tempo. Isso não é instantâneo.}
{145}{}{Quero lhe perguntar uma coisa.}
{146}{}{Fine. Tchau.}

{147}{}{Seu minério está pronto. Antes de levá-lo, ouça - nossa cidade realmente precisa desse minério. Se você doar isso para o
 Cidade, vou reembolsar o seu dinheiro. Inferno, se você quer mais dinheiro para isso, posso até dar-lhe um extra de US $ 500 para que valha a pena o seu tempo.
 Por favor. Com o fiasco na mina, Broken Hills precisa disso para ficar à tona. O que você disse?}
{148}{}{De jeito nenhum.}
{149}{}{Certo. Não se preocupe com os $ 500 adicionais. Você provavelmente precisa disso mais do que eu.}

{150}{}{Bem. Seja assim. Aqui está o seu minério. Agora saia da minha refinaria.}
{151}{}{Tchau.}

{152}{}{Obrigado! Aqui está o seu dinheiro de volta. Broken Hills não esquecerá isso.}
{153}{}{Sem problemas.}

{154}{}{Eu disse para você sair daqui!}

{155}{}{... pequeno bastardo vem aqui e <grumble> <rant> ...}

{156}{}{Um extra de US $ 500? Claro, vou aceitar.}

{157}{}{Obrigado! Aqui está o seu dinheiro de volta com US $ 500 adicionais.}
{158}{}{Ótimo. Obrigado.}

{159}{}{Você descobriu como obter minério de urânio refinado em Broken Hills.}
{160}{}{Você deu o minério refinado de volta a Broken Hills.}
{161}{}{Você vendeu o minério refinado de volta a Broken Hills.}
