{100}{}{Você vê um homem alto, grisalho, com uma jarra de cerveja.}
{101}{}{Você vê John L. Sullivan. O pugilista.}
{102}{}{Você vê um homem alto, mais velho, com braços musculosos e um bigode cinza, mas bem arrumado, com guiador.}
{103}{}{Certo agora, você já teve um pouco demais.}
{104}{}{Begorah, mas você não é estúpido.}
{105}{}{Você daria a Torr uma boa corrida por seu dinheiro.}
{106}{}{No seu caminho agora, você é estranho.}
{107}{}{Ach, outro tribal tiched no hayed.}
{108}{}{(Olha para cima e para baixo avaliadoramente) Bem, agora, o que temos aqui? Parece que você sabe muito sobre a ciência doce, não é?}
{109}{}{Se você pudesse sair do seu cavalo alto, eu poderia ver ajudar um pouco com suas habilidades.}
{110}{}{Do que você está falando?}
{111}{}{Uh, sim, seja o que for, senhor. Até a próxima. Talvez.}
{112}{}{Bem, é apenas a minha opinião educada, mas posso ver, pelo jeito que você move, que você poderia fazer com algumas dicas.}
{113}{}{Ponteiros? Com o que?}
{114}{}{Eu não penso assim, velho. Duvido que * você * possa me ensinar qualquer coisa. Adeus.}
{115}{}{Sobre a ciência doce, é claro. O esporte art.}
{116}{}{Uh, a arte? Você está falando sobre magia? Você pode me ensinar feitiços mágicos?}
{117}{}{Do que você está falando?}
{118}{}{(sorriu amplamente) Claro e begorah, eu poderia te ensinar sobre os pequeninos, leprechauns, spriggans, Ban'sidhe e coisas do género. Você gostaria disso?}
{119}{}{Isso parece ótimo. Ensine a distância.}
{120}{}{Pugilismo, a arte vã do combate mão-a-mão. É o que eu quero dizer.}
{121}{}{Pugilismo, a arte masculina, uh e feminina do combate mão-a-mão. É o que eu quero dizer.}
{122}{}{Bem, acho que poderia usar alguma ajuda com isso.}
{123}{}{Eu acho que já sei mais sobre isso do que você poderia me ensinar.}
{124}{}{(falando com aqueles ao seu redor) Você ouviu isso? Eu me tornei vivo aqui. Quer ouvir as fadas e os pequeninos duendes e tal. (Hooo, haah, haah, ele se dobra de gargalhadas) Aqui, rapaz, tome uma bebida em mim, esse é o seu bilhete para os reinos da fay folk.}
{125}{}{(falando com aqueles ao seu redor) Você ouviu isso? Eu me tornei vivo aqui. Quer ouvir as fadas e os pequeninos duendes e tal. (Hooo, haah, haah, ele se debruçou de riso) Aqui, moça, tome uma bebida em mim, esse é o seu bilhete para os reinos da Fay Folk.}
{126}{}{Tudo que eu preciso é uma bebida? Isso é ótimo. Obrigado pela dica.}
{127}{}{De alguma forma, eu sinto como se estivesse puxando minha perna um pouco.}
{128}{}{Bem, a bebida é apenas um começo. Você tem que encontrar um montículo de fadas. (winks nos patronos circundantes)}
{129}{}{O que então?}
{130}{}{Bem, sente-se ao lado do monte e espere até ver o círculo de fadas no orvalho. Se você pular no anel de fadas, você será feito para dançar até o amanhecer com os pequeninos. Se você sobreviver, eles vão te roubar para a terra do fairie. (heee, hah, hah, hah)}
{131}{}{Uau, como você descobriu isso?}
{132}{}{De alguma forma, acho que você está puxando minha perna.}
{133}{}{Oh, está em mim sangue, é claro. Erin vai bragh! (ele mantém sua jarra no alto)}
{134}{}{Sim, vá se gabar de Erin. OK. Obrigado pelas dicas. Ei, deixe-me perguntar-lhe sobre outra coisa.}
{135}{}{De alguma forma, acho que você está puxando minha perna sobre tudo isso.}
{136}{}{Uh, bem, uh, posso ver que você é um homem ocupado. Até logo. Adeus.}
{137}{}{(Ele olha para você.) Mebbe 'então. Mebbe 'então. Bem, trate-se.}
{138}{}{Eu vou. Adeus.}
{139}{}{Bem, eu estou com isso. Ne'er-the-less, você era um bonny bom esporte sobre isso. Aqui está uma cerveja, em mim, para tê-lo tão bem.}
{140}{}{Obrigado. Agora, o que você estava falando sobre a ciência doces?}
{141}{}{Não vou tirar uma cerveja de você. Eu sei mais do que você poderia me ensinar, você velho bêbado. Adeus.}
{142}{}{Bem, vamos sair e ver o que eu posso te ensinar. Você vê, trata-se de obter todo o seu corpo para encaixar, assim como um chicote ...}
{143}{}{Uh, hein.}
{144}{}{Não tenho tempo para isso agora. Adeus.}
{145}{}{(Várias, suadas, horas depois) Então você vê o que estava fazendo errado então?}
{146}{}{Sim eu quero. Obrigado por tomar o tempo para me ajudar, Sr. Sullivan.}
{147}{}{Isso foi ótimo. Deixe-me dar-lhe $ 10 por algum brew em mim. É o mínimo que posso fazer.}
{148}{}{Sim, eu acho que sim. Obrigado. Adeus.}
{149}{}{Foi com muito prazer. Você cuida agora mesmo. E se alguém perguntar ... você apenas diz para eles que Fightin 'John Sullivan lhe ensinou como lutar dessa maneira.}
{150}{}{Will, John. Obrigado. Adeus.}
{151}{}{Não não não. Eu não poderia pegar dinheiro com você. Foi muito prazer ensinar o que eu conheço. Você está cuidando de si mesmo agora mesmo. Você tem um potencial real.}
{152}{}{Isso é ótimo, deixe-me perguntar uma coisa. Onde você aprendeu a lutar assim?}
{153}{}{Obrigado, John. Adeus.}
{154}{}{Isso foi há muito tempo atrás. Quando eu era um jovem pequeno, um dinnay tem algum sentido em mim cabeça grossa. Um lugar chamado Reno. Você mantém seu nariz limpo e fique longe do que gosta desse lugar.}
{155}{}{Onde está o Reno?}
{156}{}{Oh, okay. Obrigado, John. Adeus.}
{157}{}{Eu não posso falar com você. Você continua agora. Apenas mantenha o caminho do mal. Agora tchau.}
{158}{}{OK, obrigado novamente. Adeus, John.}
{159}{}{Mantenha-se com problemas. Eu ensinei tudo o que eu conheço.}
{160}{}{Obrigado. Você mencionou algo sobre a arte antes?}
{161}{}{Obrigado, John. Eu certamente aprecio isso. Adeus.}
{162}{}{Quero dizer, a arte do pugilismo. Eu estava apenas puxando sua perna sobre as outras coisas. É melhor que eu esteja de volta para mim xícara agora. Boa sorte para você.}
{163}{}{Oh, okay. Obrigado, John. Adeus.}
{164}{}{John Sullivan ajudou você a melhorar suas habilidades de combate corpo a corpo e desarmado.}
