{100}{}{Você vê um velho ghoul.}
{101}{}{Você vê Typhon, filho de Set.}
{102}{}{Você vê um velho ghoul com inteligência bastante brilhante de seus olhos.}
{103}{}{Howdy there, kiddo, e bem-vindo ao Old Ghouls 'Home!}
{104}{}{Nol Ghul?}
{105}{}{Old Ghouls 'Home?}
{106}{}{Quem é Você?}
{107}{}{Ei, você já ouviu falar de um GECK?}
{108}{}{Tchau.}
{109}{}{Outro desperdício, né? Ei, garoto, você quer saber um segredo?}
{110}{}{Yeh!}
{111}{}{Nuh uh.}
{112}{}{De volta aos meus dias corridos, ganhei algumas corridas, fiz um pouco de dinheiro. Há muito tempo, aguento todos os meus ganhos, não muito longe de
 Aqui. Se alguém me fizesse um favor ou dois, eu poderia dizer a eles onde é esse "tesouro".}
{113}{}{Contar!}
{114}{}{Sem cuidados.}
{115}{}{Que tipo de tesouro?}
{116}{}{Que tipo de favor?}
{117}{}{Tive outras questões.}
{118}{}{Tchau!}
{119}{}{Heh. Tudo bem então. Eu não tenho nada para você. Continue, git.}
{120}{}{Tchau.}
{121}{}{Cara, quer que me faça um favor, primeiro.}
{122}{}{Okey!}
{123}{}{Nuh uh!}
{124}{}{O que é isso?}
{125}{}{Esqueça.}
{126}{}{Eu sou um cara velho, e "eu não sai demais". Não tem muita chance de ação, sabe o que quero dizer? Então, o que eu quero é uma revista Cat's Paw. Encontre-me um.}
{127}{}{'Antes! [Dê Pata De Gato para Typhon]}
{128}{}{Okey!}
{129}{}{Nuh!}
{130}{}{Aqui está. [Dê Pata De Gato para Typhon]}
{131}{}{Tudo certo. Eu voltarei.}
{132}{}{Esqueça.}
{133}{}{Obrigado pela mag, garoto. Deixe-me voltar para você em uma hora ou mais.}
{134}{}{OK!}
{135}{}{Eu ainda não terminei, criança! Sheesh! Um velho ghoul não pode ter sua privacidade?}
{136}{}{-feito-}
{137}{}{Que tipo de tesouro? Dinheiro, criança, muito e muito dinheiro. O suficiente para satisfazer qualquer pessoa sã.}
{138}{}{Qual é a captura?}
{139}{}{Não preciso de dinheiro.}
{140}{}{Você está de volta, hein? Você quer saber sobre esse tesouro, garoto?}
{141}{}{'Es!}
{142}{}{Nuh-uh.}
{143}{}{Que tipo de tesouro é esse?}
{144}{}{Sim, diga-me.}
{145}{}{Primeiro tive perguntas para você.}
{146}{}{Não.}
{147}{}{Como o quê?}
{148}{}{This is the Old Ghouls 'Home?}
{149}{}{Você já ouviu falar de um GECK?}
{150}{}{Quem é Você?}
{151}{}{Mais alguma coisa que você possa me dizer?}
{152}{}{É uma piada. Não há nenhum ghouls, mas velhos ghouls. Nós somos todos estéreis, veja, mas somos incrivelmente duradouros. Somos a primeira e última geração de ghouls. Este é um lugar para aqueles que apenas queremos descansar por um tempo.}
{153}{}{I see. Tive outras questões.}
{154}{}{Got it. Tchau.}
{155}{}{Eu sou Typhon. Você já ouviu falar de Set? Ele costumava dirigir a antiga cidade da Necrópole. Eu sou seu filho. Nascemos antes que a radiação nos atingisse, então eu cresci mutante. Nunca foi de outra maneira para mim.}
{156}{}{Conte-me sobre Set.}
{157}{}{Conjunto? Ouvi dizer que ele era um bastardo total!}
{158}{}{I see. Tive outras questões.}
{159}{}{Got it. Tchau.}
{160}{}{Sim. Usado para ter alguns, mas todos os seres humanos de tensão pura os roubaram para criar seus próprios Jardins do Éden. Vault City pode ser a sua melhor opção para encontrar um. Ou lá ou NCR para o sul.}
{161}{}{Droga. Ok, eu tive mais perguntas.}
{162}{}{Damn. Tchau.}
{163}{}{"Total bastardo" seria uma ótima maneira de descrever o velho. Ser transformado em um ghoul da radiação não fez muito por seu senso de humor ou senso de autoridade, deixe-me dizer-lhe. "Claro, ele meio que ferrou o cérebro de todos. Eu acho que crescer o ghoulie tornou-me um pouco mais fácil.}
{164}{}{I see. Tive outras questões.}
{165}{}{Thanks. Tchau.}
{166}{}{Bem? Você ainda tem a minha revista Paw do gato?}
{167}{}{'Es. [Dê Pata De Gato para Typhon]}
{168}{}{Nuh-uh.}
{169}{}{Yup. Aqui está. [Dê Pata De Gato para Typhon]}
{170}{}{Ainda não. Tive outras questões.}
{171}{}{Não.}
{172}{}{Bem, apresse-se! Eu sou um velho e velho ghoul, e eu te digo, eu tenho que relaxar! Agora vá, vá, vá!}
{173}{}{-feito-}
{174}{}{Kid, aquela revista agitou os sucos de ol, e acho que, pelo tipo de tesouro que estou falando, você pode me caçar mais algumas coisas. Vá me dar uma boneca explosiva. Você provavelmente pode encontrar um em New Reno.}
{175}{}{Okey! Tchau!}
{176}{}{Nuh-uh!}
{177}{}{Aqui vai! [Dê Blow-Up Doll para Typhon]}
{178}{}{Tudo certo. Eu tive mais perguntas.}
{179}{}{All right. Tchau.}
{180}{}{Esqueça.}
{181}{}{Chegou aqui. [Dê Blow-Up Doll para Typhon]}
{182}{}{Isso, criança, atingirá o local. Dê algumas horas e conversaremos mais. Continue. [ele vê a boneca com lúgubre]}
{183}{}{-feito-}
{184}{}{Não é possível que um cara tenha pouca privacidade! Git! Git! G'wan!}
{185}{}{-feito-}
{186}{}{Estou tocado agora. Vá me pega um pouco e falamos sobre o tesouro. Phil o bartender deve ser capaz de cuidar o 'para você.}
{187}{}{Rite! Tchau!}
{188}{}{Não!}
{189}{}{Levar! [Dê Rotgut para Typhon]}
{190}{}{Consegui. Aqui está. [Dê Rotgut para Typhon]}
{191}{}{Será isso?}
{192}{}{All right. Tchau.}
{193}{}{Esqueça.}
{194}{}{Provavelmente vou querer ... ah, mais uma coisa. Eu vou te dizer o que é quando você me pega minha rotunda, está bem?}
{195}{}{Bem. Eu vou fazer isso.}
{196}{}{Esqueça.}
{197}{}{Isso realmente atingiu o local, criança. Eu ia te pedir uma planta, mas oi, vou dar uma pausa.}
{198}{}{'Ank you!}
{199}{}{Thanks. Tive outras questões.}
{200}{}{Isso é um pouco vago, mas obrigado. Até mais.}
{201}{}{Você encontra esse tesouro ainda, criança?}
{202}{}{Nuh uh.}
{203}{}{Ainda não.}
{204}{}{Não. I had some questions.}
{205}{}{Não. Tchau.}
{206}{}{Bem, continue procurando. Você é obrigado a obtê-lo eventualmente.}
{207}{}{OK.}
{208}{}{Guess so. Tchau.}
{209}{}{Como está o tesouro, criança?}
{210}{}{Mau! Cápsulas!}
{211}{}{Foi tudo o que foi para bottlecaps! Não vale a pena!}
{212}{}{Ha ha. Engraçado. Eu tive algumas perguntas.}
{213}{}{Esqueça.}
{214}{}{Poo! Tchau.}
{215}{}{O que, eles não usam bonés como dinheiro mais? Você quer dizer tudo o que se recolher e esconder e se preocupar com alguém vai roubar meu
 stash foi por nada? Droga! Desculpe fazê-lo correr assim, criança. Se eu soubesse ...}
{216}{}{'S okay. Tchau!}
{217}{}{Sim, bem, você cometeu seu último erro, velho ghoul. Hora de morrer.}
{218}{}{Suponha que isso poderia acontecer com qualquer um. Eu tive algumas perguntas.}
{219}{}{Yeah, yeah. OK. Tchau.}
{220}{}{Guess it was an honest mistake. Tchau.}
{221}{}{Gud. Onde munnee?}
{222}{}{Gee, Typhon. Você é tão pensativo. Então, onde está o dinheiro?}
{223}{}{Tudo certo. Lembro-me de esconder o dinheiro em algum lugar do centro da cidade. Já faz tantos anos, e os edifícios foram
 construído e reconstruído uma e outra vez, que não tenho certeza exatamente onde está. Se isso ajuda qualquer coisa, lembro-me de pensar que eu deveria colocá-lo
 Em algum lugar que não era susceptível de ser derrubado ou arado. Em algum lugar indispensável, você sabe? Boa sorte para você.}
{224}{}{Você finalmente conseguiu que Typhon desperdiçasse suas tripas sobre a localização do pilhagem escondida.}

# Typhon/Seymour Floats.
{300}{}{Mas a dialética de Hegel não explica ...}
{301}{}{Hegel, Hegel, Hegel! Você está sempre interessado em Hegel!}
{302}{}{Então a mulher diz: "Isso não é um coelho, vigário!"}
{303}{}{Ha ha ha ha!}
{304}{}{E o primeiro próton diz: "Sim, eu sou positivo!"}
{305}{}{[gargalgia] Isso é tão ruim, eu estou murchando.}
{306}{}{Não é fácil ser verde.}
{307}{}{Conte-me sobre isso.}
{308}{}{Mas é completamente evidente que este é um beco sem saída filosófica!}
{309}{}{Isso é só porque você não examinou todas as ramificações disso. Agora, se você ...}
{310}{}{Você quer um pouco de fruta?}
{311}{}{Alimente-me, Seymour.}
{312}{}{Brains ... braaaaaains ... desculpe, velho hábito.}
{313}{}{Tudo bem. Eu não tenho um, lembra?}
{314}{}{Bem, certamente o estrume funciona bem, mas não há nada como um cadáver apodrecendo para compostagem.}
{315}{}{Então é por isso que você queria passar por aqui! Colhidas fáceis.}
{316}{}{Deixe-me dizer-lhe, não há nada como uma boa corrida rápida.}
{317}{}{Você realmente sente o vento através dos fios do cabelo, sim?}
{318}{}{Eu não tenho polinizado em anos!}
{319}{}{Imagine estar preso neste corpo! Nenhuma ação! Nenhuma ação!}
{320}{}{Talvez se você tenha dado fotosíntese ao acaso ...}
{321}{}{Eu não sou responsável pelas minhas raízes evolutivas, você bastardo verde!}
{322}{}{Whoo-ee! Espero que você possa processar o metano!}
{323}{}{Minhas folhas! Minhas pobres deixa! Aaaaagh!}
{324}{}{Eu gosto deste lugar. Estou pensando em colocar raízes aqui.}
{325}{}{Ok, o suficiente com as intermináveis   piadas da planta, amigo.}
{326}{}{Eu me pergunto como estão meus primos em Arroyo? Espero que estejam florescendo.}
{327}{}{Claro que eles são! A menos que algum bastardo de ratos abate todos eles.}
{328}{}{Bem, acho que vou abrir uma porta ou algo assim ...}
{329}{}{Eu acho que tenho uma inveja inimiga oponível.}
{330}{}{Não sair de um membro aqui ...}
{331}{}{Aaaaaaaaaaaaaagh! Mais piadas de plantas!}
{332}{}{Verifique os grãos naquela haste de trigo! Woo woo!}
{333}{}{Down boy! Eu não acho que suas vacuolas podem levá-lo.}
{334}{}{Quer que eu leie uma história?}
{335}{}{Como sobre a árvore de dar? Jack e o Beanstalk? Apanhador no Campo de Centeio?}
{336}{}{UM GECK? Sim, havia um cara que ...}
{337}{}{Shhh! Shh! Alguém está ouvindo!}
{338}{}{É o grande ciclo da vida, você vê ... A vida se alimenta da vida se alimenta da vida ...}
{339}{}{Uh hein. Mas você ainda come estrume. Sheesh ... filosofia da planta ...}
{340}{}{Posso jogar com sua armadura de poder algum dia?}
{341}{}{Você quer dizer aquele terno antigo que eu mantenho no armário? Tê-lo ...}
{342}{}{Sim, eu tenho metido na polinização cruzada.}
{343}{}{Não que haja algo ERRADO com isso.}
