{100}{}{Você vê um velho mutante de aparência dura.}
{101}{}{Você vê Zaius, o mestre da mina.}
{102}{}{Em um exame mais atento, você vê um mutante velho resistente com um capacete e um capacete de mineiro.}

{103}{}{Você é o cara novo na cidade?}
{104}{}{Eek, oog og!}
{105}{}{Novo! Eu! Cidade!}
{106}{}{Está certo.}
{107}{}{Sim, rodou um pouco atrás.}
{108}{}{Não, gênio, vivi aqui o tempo todo e você nunca me notou.}
{109}{}{Ouvi dizer que você está tendo um pequeno problema com a mina.}
{110}{}{O que você pode me falar sobre esse lugar?}

{111}{}{Ummm ... riiiight. Dizer-te o que. Aqui estão alguns dólares. Dirija-se ao salão e ganhe
 Você é algo para beber.}
{112}{}{Yagga? Ogg? Gronk!}

{113}{}{Não consigo entender você, amigo. Por que não ir para o salão? Inferno, talvez Francisco
 Bravo com você.}
{114}{}{Wessle? OK!}

{115}{}{Certo. Bem, eu sou Zaius. Agora que somos apresentados ... Você é bom com suas mãos? Nós temos um
 Problema com o nosso purificador de ar no nível mais baixo da mina, mas não temos as peças para corrigi-lo
 Ou a engrenagem protetora para evitar ser dominada pelo gás radão que vem acumulando.}
{116}{}{Eu não sou muito bom. Desculpa.}
{117}{}{Não muito pobre. O que vai demorar?}

{118}{}{Bem, espero que você aproveite a sua estadia aqui em Broken Hills.}
{119}{}{(Mais)}

{120}{}{Ha. Ha. Engraçado. Nada melhor do que um cara esperto para resolver um problema.}
{121}{}{Mais inteligente do que qualquer outra pessoa nesta cidade de Shithole.}
{122}{}{Ah Há um problema? O que é isso?}
{123}{}{O principal problema aqui é que você é um idiota.}
{124}{}{Este sou eu. Cara esperto. Qual é o seu problema?}

{125}{}{Nosso purificador de ar está quebrado. Está no nível inferior. Não temos partes e não temos
 Equipamento de proteção. Sem as partes, não podemos consertá-lo. Sem a proteção, o gás de radão nos unirá. Você é algum
 Bom com as mãos?}
{126}{}{Estou bem.}
{127}{}{Não. Na verdade, não.}

{128}{}{Você novamente, hein?}
{129}{}{Ork! Ooo! Ug ug!}
{130}{}{Oi! HIIIII! Eu (nome)!}

{131}{}{Pal, já lhe dei dinheiro. Vá incomodar outra pessoa, hein?}

{132}{}{Oi de novo. Por que não vai verificar ... umm ... o banco na cidade? Tenho certeza de que há muitas pessoas lá
 Quem adoraria conversar com você.}

{133}{}{Bem, se alguma vez você pensa em uma maneira, me avise.}

{134}{}{Mesmo? Você faria isso por mim ... e, o mais importante, por Broken Hills?}
{135}{}{O que há para mim?}
{136}{}{Claro, vou fazer isso.}
{137}{}{Não agora.}

{138}{}{Izzat então? Bem, meu amigo inteligente, por que não consertar o purificador de ar abaixo? Você precisará do
 Partes, e você precisará encontrar uma maneira de respirar o gás. Até que você possa me mostrar, você pode fazer isso, eu acho
 Eu vou assumir que a única coisa inteligente sobre você é a sua boca.}
{139}{}{O que há para mim?}
{140}{}{Claro, vou fazer isso.}
{141}{}{Você está de brincadeira?}

{142}{}{O principal problema é que eu sou um idiota. Estou repetindo isso porque não acredito que o seu
 Asshole apenas desperdiçou algo que soou como palavras. Saia da minha vista, larva.}

{143}{}{Além dos idiotas que continuam a me assediar, o problema é o purificador de ar na mina. Está
 Arruinados, e não temos o equipamento de proteção para respirar o radão e não temos as peças para corrigi-lo.
 Você pode, certo? Porque você é tão inteligente?}
{144}{}{O que há para mim?}
{145}{}{Claro, vou fazer isso.}
{146}{}{Você está de brincadeira? No way.}

{147}{}{. Como é esse som?}
{148}{}{Como uma merda. Eu quero mais.}
{149}{}{Parece bom para mim.}
{150}{}{Esqueça. Estou fora.}

{151}{}{Ótimo! Você vai precisar das peças, é claro. Vá para New Reno e procure Renesco. Ele tem ferramentas
 Mentindo pela loja. Diga-lhe que Zaius enviou você. Diga-lhe que eu disse: "O canário está chutando o
 Balde. "Eu não sei onde obter equipamento de proteção para o gás. Suponho que você poderia entrar sem nenhum
 Mas você vai doer. Mais uma vez obrigado.}
{152}{}{Sem problemas. Tchau.}

{153}{}{Não? Bem, se você mudar de idéia, sabe onde me encontrar.}
{154}{}{Coisa certa. Tchau.}

{155}{}{ é então. Pegue a metade agora. Eu vou te dar a outra metade quando terminar. Vá para New Reno e
 Procure Renesco. Ele tem ferramentas que estão mentindo ao redor de seu escritório. Ele deve ser capaz de ajudá-lo com o
 Partes.}
{156}{}{Até mais.}

{157}{}{Desculpa. Esse é o limite. É pegar ou largar.}
{158}{}{Eu vou levar.}
{159}{}{Vou deixá-lo.}

{160}{}{Bem. Deixe, então. Não, obrigado.}
{161}{}{Tanto faz.}

{162}{}{Oi amigo!}
{163}{}{Oh, bom. É você novamente.}
{164}{}{Howdy.}
{165}{}{Sabei, sabia que os bastardos Franc, Manson, Jacob e Aileen tinham para nós. Bem feito! Assim…}
{166}{}{Espero que você tenha pensado em dar o minério de volta à cidade ... então ...}
{167}{}{Obrigado por vender o minério. Não é como se não pudéssemos usá-lo ou qualquer coisa. Assim…}
{168}{}{Muito obrigado por devolver esse minério. Você não sabe o quão difícil nós trabalhamos para essas coisas.}
{169}{}{O que você quer agora?}
{170}{}{Você pode me falar sobre a cidade?}
{171}{}{Ouvi dizer que você está tendo problemas com a mina.}
{172}{}{Como são as coisas?}
{173}{}{Você se dá bem com os humanos?}

{174}{}{Você mudou de idéia sobre tentar consertar a mina ainda?}
{175}{}{O que há para mim?}
{176}{}{Claro, vou fazer isso.}
{177}{}{Não agora.}
{178}{}{Não.}

{179}{}{Como está chegando? Espero que você vá cuidar disso em breve ...}
{180}{}{Está chegando tudo bem.}
{181}{}{Sou um homem ocupado. Ainda não consegui chegar.}
{182}{}{Eu deveria poder informá-lo em breve.}

{183}{}{Você tem as peças? Ótimo ... Espero que você tenha algum equipamento de proteção. Os fumos podem derrubá-lo.}
{184}{}{Estou pronto para ir.}
{185}{}{Eu irei em breve.}

{186}{}{Você tem as peças? Ótimo ... Espero que você tenha algum equipamento de proteção. Os fumos podem derrubá-lo.}
{187}{}{Estou pronto para ir.}
{188}{}{Eu irei em breve.}

{189}{}{Você corrigiu isso? Excelente! Diga, eu sei que você estava fazendo isso de graça, mas ... Eu não poderia deixar você
 faça isso. Então eu e os caras se juntaram e conseguiram isso. É uma espingarda de combate. Boa sorte. E
 obrigado.}
{190}{}{Sem problemas. Obrigado!}

{191}{}{Você corrigiu isso? Excelente! Conforme acordado, aqui está o restante do que lhe devemos. Obrigado novamente.}

{192}{}{Seu desgraçado. Você vai morrer agora.}

{193}{}{Bom Bom. Com pressa, porém ... nossa cidade precisa do que saímos daqui.}
{194}{}{Sure thing. Até mais.}
{195}{}{Não me apresse. Sou um homem ocupado. Empurrão.}

{196}{}{Bem, desculpe, Sr. Alto e Mighty, mas acho que a sobrevivência da cidade pode ser um pouco
 mais importante. Apresse-se, você vai?}
{197}{}{Bite me. I’ll get it done. Até mais.}
{198}{}{Essa é a última gota. Adeus, homem morto.}

{199}{}{Por favor, despacha-te. A mina é o sangue vital da nossa cidade.}
{200}{}{Tudo bem, tudo bem.}

{201}{}{Bem, a melhor pessoa com quem falar sobre isso seria Marcus, no banco, ou Steve, o
 Greeter para a cidade.}
{202}{}{Hmm. Tudo bem, obrigado.}
{203}{}{Eu vou perguntar-lhes, então.}

{204}{}{Eu teria que dizer que eles estão bem. Ainda ... eles sempre poderiam ser melhores.}
{205}{}{Heh. Obrigado por toda a informação.}

{206}{}{Bem, como os mutantes não estão apenas envelhecendo e senil - o gás os mantém jovens, ou
 Algo - eu teria que dizer que as coisas são muito boas. Quero dizer, não queremos matar todos e, como
 Tanto quanto eu posso dizer, os humanos não pensam muito mal de nós. "Claro, isso não inclui os humanos
 Dos outros lugares por aí ... agora são alguns bastardos.}
{207}{}{Tudo bem, obrigado. Tchau.}

{300}{}{. Como é esse som?}
{301}{}{. Como é esse som?}
{302}{}{$}
{381}{}{Sou uma mulher ocupada. Ainda não consegui chegar.}
{382}{}{Não me apresse. Sou uma mulher ocupada. Empurrão.}
{383}{}{Bem, desculpe, Sra. High e Mighty, mas acho que a sobrevivência da cidade pode ser um pouco
 mais importante. Apresse-se, você vai?}

{400}{}{Tenho uma nota com o seu nome. Encontrou isso em uma mulher morta nos túneis. Você gostaria de comentar?}
{401}{}{Ei, acabei de receber a nota. Vá falar com Francisco sobre isso, está bem? Ele é o único
 quem escreveu isso.}
{402}{}{Se você tivesse uma mão em matar essas pessoas, eu quero saber sobre isso.}
{403}{}{All right. Até mais.}

{404}{}{Não! Estamos apenas nos protegendo da conspiração. Marcus acredita em lei e
 Evidência, e mesmo que ele saiba que essas pessoas são perigosas, ele não sabe quem elas são -
 E ele é muito honrado para provar provas. Minha parte é manter Francis restringido de todo o lado
 vingança.}
{405}{}{Parece muito arrumado. Eu vou verificar isso com Francis.}

{406}{}{Eu sabia que Francis não conseguia lidar com a exposição. Ele sabia os riscos do que ele fazia, mas acho que ele
 Não foi encontrado em algum momento. Ele estará bem, eventualmente. Espero que o mesmo seja verdade para
 Broken Hills.}
{407}{}{Eu também espero. Eu tenho algumas questões.}
{408}{}{Eu também. Tchau.}
