{100}{}{"Zaius: Marcus não está fazendo nada sobre esse Jacant mutante e seus condenados conspiradores. Primeiro, eles desativam o ar
 purificador ... e depois, o que? Encontrei seus túneis de reunião secretos. Eu acho que um corpo ou dois lá embaixo podem implicar Jacob. Se vocês
 quero, avise-me. E queime a maldita nota desta vez! "- Assinatura, Francis}
{101}{}{Meu Deus! Se eu contar a Marcus sobre essa nota, a cidade vai subir de chamas. É melhor eu falar com Zaius ou Francis sobre isso ... e obter algumas respostas.}
