# 0. QUICK LOOK
{100}{}{Você vê um mercenário bem armado.}

# 0. LOOK
{150}{}{Você vê um homem robusto vestido com uma armadura de couro. Numerosas cicatrizes e feridas de bala cobrem seu corpo. Sua armadura e armas, por outro lado, parecem bem mantidas, quase novas.}
{151}{}{Você vê um incursor bem armado. Ele está examinando a área e dedilhando sua arma.}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{Bem, olhe para as bolas de bronze neste filho da puta ...}
{201}{}{Contato!}
{202}{}{A área foi violada!}
{203}{}{Nos conseguimos um intruso, meninos!}
{204}{}{Scramble, meninos, nós temos um intruso!}
{205}{}{Bem, olha quem parou em ta morrer ...}
{206}{}{Droga! Alguém nos encontrou!}
{207}{}{Você tem alguma areia aqui dentro ...}
{208}{}{Você entrou no lugar * errado *, cadela.}
{209}{}{Bem, olhe o swagger nesta cadela ...}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{250}{}{Nós saímos bebendo, e ele chamou de "hora de ajuste da atitude", então nós chutamos sua bunda.}
{251}{}{Precisamos verificar esses clusters na caverna ...}
{252}{}{Quase tempo para fazer outro controle do perímetro ...}
{253}{}{Homem, esse tribo * fede. * Todo o seu tipo faz.}
{254}{}{Damn Vault City laser canhões ...}
{255}{}{Cansado de polir minha arma ... ambos.}
{256}{}{Quanto tempo temos que ficar aqui fora?}
{257}{}{Devemos estar nos movendo em alguns dias ...}
{258}{}{Não posso esperar e voltar para Reno. * 'Especialmente * a Pata do gato.}
{259}{}{Os escorpiões estão ficando com fome novamente. Ouvi-los clicando ontem à noite ... * clique * * clack * * clique *}
{260}{}{Você verificou as minas na entrada como eu * disse * você?}
{261}{}{O capitão está respirando pelo pescoço novamente porque quase deixei esse comerciante fugir ...}
{262}{}{Eu me pergunto como eu posso sair desta roupa de merda de galinha.}
{263}{}{Lynette é uma mulher bonita. Bem, de uma maneira aristocrática, dominadora e defensora dos escravos.}
{264}{}{... então então * ela * diz, 'esse é meu barriga, dipshit!' Haw! Essa piada * sempre * me mata.}
{265}{}{Bom para ir.}
{266}{}{O Capitão está realmente derrubando minhas bolas ...}
{267}{}{Eu me sinto como se estivesse aqui para sempre, apenas esperando por alguém para mostrar.}
{268}{}{Gostaria de ter algum outro mapa ao qual eu pudesse ir.}
