# 0. QUICK LOOK
{100}{}{Você vê um capitão mercenário.}

# 0. LOOK
{150}{}{Você vê um homem robusto vestido com uma armadura de combate. Suas armaduras e armas ficam bem conservadas, quase novas.}
{151}{}{Você vê um capitão mercenário. He is scanning the area and fingering his weapon.}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{Bem, olhe para as bolas de bronze neste filho da puta ...}
{201}{}{Contato!}
{202}{}{Nos conseguimos um intruso, meninos!}
{203}{}{Scramble, meninos, nós temos um intruso!}
{204}{}{Bem, olha quem parou em ta morrer ...}
{205}{}{Droga! Alguém nos encontrou!}
{206}{}{Você tem alguma areia aqui dentro ...}
{207}{}{Você entrou no lugar * errado *, cadela.}
{208}{}{Bem, olhe o swagger nesta cadela ...}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{215}{}{É melhor chamar essas equipes assassinas em breve ...}
{216}{}{Eu acho que a equipe de Bravo é alguns klicks ao sul da Cidade do Vault ... eles ainda seguem essa caravana.}
{217}{}{Essa cereja do deserto melhorará logo ... esse tipo de merda não vai lavar por aqui.}
{218}{}{Quase tempo para enviar alguns homens para verificar o perímetro ...}
{219}{}{Se pudéssemos apenas sabotar os canhões laser Vault City ...}
{220}{}{Ainda está aguardando a palavra do Bispo ...}
{221}{}{Foi uma semana desde que Bishop enviou um mensageiro.}
{222}{}{Eu acho que a próxima caravana deve ser da NCR para Vault City ...}
{223}{}{Temos que estar preparados para sair com um aviso prévio.}
{224}{}{Espero que esses garotos tenham verificado as armadilhas.}
{225}{}{A equipe Alpha e Bravo voltou a verificar ainda?}
