# 0. QUICK LOOK
{100}{}{Você vê Shadow-Who-Walks.}

# 0. LOOK
{150}{}{Você vê um primitivo pesadamente musculoso com cicatrizes negras cobrindo seu rosto. Ele está olhando você silenciosamente.}
{151}{}{Você vê Shadow-Who-Walks. His face is heavily scarred by ritual tattoos.}

# 1. CLICK ON HIM (WTG)
{200}{}{Ele apenas olha para você em silêncio.}
{201}{}{Ele o observa silenciosamente.}

# WABBITS
{300}{}{Shhh ... eu estou sentindo gatinhos.}
