# 0. LOOK
{100}{}{Você vê um enorme cofre de ferro preto.}
{101}{}{Você vê uma coisa quadrada negra com um grande nariz.}

# 2.  EXAMINE SAFE, CLOSED (WTG, 10)
{200}{}{Você vê uma grande coisa quadrada de metal preto com um nariz na frente.}
{201}{}{Você vê um enorme cofre de ferro preto que parece muito pesado para se mover. Há uma combinação de discagem na frente.}
{202}{}{Ullo box me}
{203}{}{ Hoo você?}
{204}{}{Torça o nariz}
{205}{}{Afastar-se}
{206}{}{Hmmmm. Talvez os números dessas três marcas de cachorro possam abrir o seguro ...}
{207}{}{Rode o disco, ouça os ruídos do clique.}
{208}{}{Gire o mostrador aleatoriamente.}
{209}{}{Examine o cofre para armadilhas.}
{210}{}{Deixe o cofre sozinho.}

# 3.  SAFE IS OPEN (WTG, 2, 4, 5, 6, 7, 8)
{220}{}{Existe um KER-KLANK. O seguro agora está desbloqueado.}
{221}{}{O seguro é desbloqueado.}
{222}{}{O nariz gira na sua mão! Parece que você poderia abrir o rosto se você quisesse.}
{223}{}{A grande coisa do quadrado de metal parece que pode ser aberta.}
{224}{}{Abra o rosto}
{225}{}{Afastar-se}
{226}{}{Arraste o cofre.}
{227}{}{Deixe o cofre sozinho.}

# 4.  TRAPS, SUCCESS . . . ? (2, 6)
{235}{}{A inspeção fechada do cofre revela um fio preto que atravessa a sujeira logo abaixo do cofre. Escovando a sujeira, você descobre que o fusível corre para uma vara de dinamite com um temporizador.}
{236}{}{Hmmmm. Talvez os números nas três marcas de cachorro podem abrir o seguro ...}
{237}{}{Tente e desarmar a armadilha.}
{238}{}{Deixe o cofre sozinho.}

# 5.  CLICKING (2, 5, 6, 8)
{250}{}{Você gira o disco lentamente por vários minutos, mas você não consegue resolver nada.}
{251}{}{Hmmmm. Talvez os números dessas três marcas de cachorro possam abrir o seguro ...}
{252}{}{Rode o disco, ouça os ruídos do clique.}
{253}{}{Gire o mostrador aleatoriamente.}
{254}{}{Deixe o cofre sozinho.}

# 6.  TRAPS . . . ? (2, 6)
{275}{}{Você não encontra nenhuma armadilha no cofre.}
{276}{}{Hmmmm. Talvez os números nas três marcas de cachorro podem abrir o seguro ...}
{277}{}{Rode o disco, ouça os ruídos do clique.}
{278}{}{Gire o mostrador aleatoriamente.}
{279}{}{Examine o cofre para armadilhas novamente.}
{280}{}{Deixe o cofre sozinho.}

# 7.  SPIN RANDOM, SUCCEED (2, 5, 6, 8, 9)
{290}{}{Você está girando o botão ... quando de repente há um KER-KLANK. O seguro agora está desbloqueado!}
{291}{}{Você está girando o mostrador aleatoriamente, quando de repente o disco trava em um número ... há um KER-KLANK. O seguro
 agora está desbloqueado!}
{292}{}{Hullo? Hulllooo? Um amigo?}
{293}{}{Pare o seu grinde e solte a sua roupa ...}
{294}{}{Sim, tenho o toque ...}

# 8.  SPIN RANDOM, FAIL (2, 5, 6, 8, 9)
{305}{}{Você gira o botão, mas a pequena porta não vai abrir!}
{306}{}{Você gira o dial por vários minutos, e nada acontece.}
{307}{}{Hulllooo? Caixa Hulllo ...}
{308}{}{Continue torcendo o nariz.}
{309}{}{Afastar-se}
{310}{}{Hmmmm. Talvez os números dessas três marcas de cachorro possam abrir o seguro ...}
{311}{}{Rode o disco, ouça os ruídos do clique.}
{312}{}{Continue girando o mostrador aleatoriamente.}
{313}{}{Deixe o cofre sozinho.}

# 9.  HELLO? (2, 8, 9)
{320}{}{A coisa não responde.}
{321}{}{A coisa do cubo preto não parece notar você.}
{322}{}{A caixa de metal ignora você.}
{323}{}{Helloooooo? Eu}
{324}{}{ Hoo yoo?}
{325}{}{Torça o nariz}
{326}{}{Afastar-se}

# 10.  TRAP DISARMED . . . ? (4)
{340}{}{Com precisão cirúrgica, você desarmar o fusível e puxar a dinamite sob a sujeira. A armadilha está agora desarmada.}
{341}{}{Agora para crack este seguro ...}
{342}{}{Deixe o cofre sozinho.}

# During Combat
{343}{}{Você não tem tempo para tentar o cofre durante o combate.}

# Safe opening Message
{344}{}{Você criou o cofre dos invasores.}
