#############################################################
#  Message File: kcitizen.msg                               #
#                                                           #
#       Body Type:  NAROBE                                  #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê um dos cidadãos de Klamath.}
{101}{}{Você vê um dos cidadãos de Klamath.}

#############################################################
#  The following lines are floaters for citizens            #
#############################################################

{150}{}{Por que você não volta para sua tribo?}
{151}{}{Eu vou te dar algumas contas bonitas, se você me deixar em paz.}
{152}{}{Bom tribal, bom tribal, não me machuque.}
{153}{}{Eu certamente gostaria de ter uma parede ao redor da cidade.}
{154}{}{Não tenho nada para roubar; vá embora.}
{155}{}{Por que você está olhando assim para mim?}
{156}{}{Ótimo, outro tribal.}
{157}{}{Por que você não volta para o gecko dourado?}
{158}{}{Apenas fique longe de mim.}
{159}{}{Nós não precisamos de você para provocar problemas.}
{160}{}{Você deve ter vindo para o norte do Den.}
{161}{}{A última coisa que precisamos é mais como você.}

{170}{}{Olá, estranho.}
{171}{}{Eu certamente espero que a armadilha seja boa nesta temporada.}
{172}{}{Muita brahmin está faltando ultimamente.}
{173}{}{(Crunch, crunch) A carne seca de Dunton é gostosa.}
{174}{}{Você veio aqui para trocar peles por água de fogo?}
{175}{}{Eu pensei que todo seu povo colocava um osso nos narizes.}
{176}{}{Cuidado com os ratos em Trapper Town.}
{177}{}{Agora, onde eu coloquei esses feijões mágicos?}
{178}{}{Geckos sabem como frango enlatado, se você cozinhar direito.}
{179}{}{Eu vou relaxar no Bathhouse.}
{180}{}{Cuidado com os Duntons.}
{181}{}{A casa Buckner sempre me dá um preço justo em meus produtos.}
{182}{}{Bom Dia hoje.}
{183}{}{Você parece Sulik.}
{184}{}{Pergunto-me onde o idiota Torr foi?}
{185}{}{O grande segredo é - ei, o que é isso no meu bolso?!?}
{186}{}{Sem descanso para os pobres.}
{187}{}{Minhas articulações doem; O clima deve estar mudando.}
{188}{}{O vento se aproxima um pouco.}

{190}{}{É bom te ver.}
{191}{}{Mais como você em casa?}
{192}{}{Espero que você esteja gostando de Klamath.}
{193}{}{Podemos usar mais algumas pessoas do seu calibre aqui.}
{194}{}{O que há amigo?}
{195}{}{Boa sorte para você.}
{196}{}{Se você precisa comprar qualquer coisa, vá para Buckner House.}
{197}{}{Você não é como Sulik.}
{198}{}{Você é a tribo mais civilizada que já conheci.}
{199}{}{Cuidado com os geckos que mudaram de cor.}
{200}{}{Olá, viajante.}
{201}{}{Fico feliz em tê-lo em Klamath.}
{202}{}{Howdy, estranho.}
{203}{}{Cuidado com esses Duntons; eles são perigosos.}
{204}{}{Trapper Town tem certeza de que há muitos ratos.}

#############################################################
#  TELL ME ABOUTS WILL BE REMOVED                           #
#############################################################
{1000}{}{Mais velho}
{1001}{}{Fundador}
{1002}{}{Cofre Dweller}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Cofre}
{1006}{}{Escolhido}
{1007}{}{Xamã}
{1008}{}{Hakunin}
{1009}{}{Pó de cura}
{1010}{}{Ponte}
{1011}{}{Mynoc}

{1100}{}{The Mais velho is your mother and our leader.}
{1101}{}{Nosso grande antepassado que nos deu conhecimento.}
{1102}{}{O primeiro a lutar e vencer o caos.}
{1103}{}{Essa seria a nossa bela aldeia.}
{1104}{}{Isso é comercializado em alguns dias a leste daqui.}
{1105}{}{The Cofre is heaven.}
{1106}{}{You are the Escolhido.}
{1107}{}{Ele nos cura com suas ervas e magia. Ele está na parte norte
 da nossa aldeia.}
{1108}{}{Ele nos cura com suas ervas e magia. Ele está na parte norte
 da nossa aldeia.}
{1109}{}{É um pó mágico que irá curá-lo, mas irá fazer você
 sonolento.}
{1110}{}{The Great Ponte exits our village in the south.}
{1111}{}{Ele guarda a ponte que conduz à nossa aldeia.}
