{100}{}{Você vê um cão de guarda.}
{101}{}{Você vê um cachorro selvagem.}

{120}{}{Você vê um cão de guarda.}
{121}{}{Você vê um cachorro selvagem.}

{200}{}{:: CRESCIMENTO ::}
{201}{}{:: SNARL ::}
{202}{}{:: COBERTURA ::}

{205}{}{Woof}
{206}{}{Woof woof}

{210}{}{Os cães parecem ser treinados para proteger o que está dentro do galpão.}
{211}{}{Doggy não como eu.}
{212}{}{Bom cachorrinho!}

{250}{}{Este cachorro parece que pode realmente arrancá-lo se necessário.}
