# Before Jonny Found
{100}{}{Soluço-}
{101}{}{Jonny ...}
{102}{}{Farejar...}
{103}{}{Sinto falta do meu filho.}

# Player accepts find Jonny Seed
{110}{}{Encontre Jonny.}

# After Jonny Found
{120}{}{Por favor, traga Jonny de volta.}

# Jonny Returned
{121}{}{Obrigado por me mandar Jonny.}

# looks
{150}{}{Você vê a esposa de Baltha.}
{151}{}{Você vê a esposa de Baltha. She looks pretty upset.}
{152}{}{Você vê a esposa de Baltha. She appears to be in a pleasant mood now.}
