{100}{}{Um pesado homem com um avental de couro.}
{101}{}{Balthas o curtidor.}
{102}{}{Um homem alto e musculoso que olha e cheira em couro.}

{151}{}{Meu filho foi erroneamente matado na luta.}
{152}{}{Não posso suportar viver sem Jonny.}
{153}{}{[Soluço]}
{154}{}{Encontre-nos na Ghost Farm. Vamos atacar os fantasmas.}
{155}{}{Olá, meu nome é Balthas. Eu corro o curtume aqui em Modoc. Posso ajudar?}
{156}{}{Parece um pouco preocupado; há algo de errado?}
{157}{}{Gostaria de ver seus produtos.}
{158}{}{Você viu um relógio de ouro ao redor de qualquer lugar?}
{159}{}{Voltarei mais tarde.}
{160}{}{Estou procurando por um item chamado GECK. Você sabe, por acaso, algo sobre isso, ou como eu
 pode obter um?}
{161}{}{GECK?}
{163}{}{Com o que posso ajudar?}
{168}{}{Apenas olhando, obrigado.}
{171}{}{Alguma sorte encontrando Jonny?}
{172}{}{Achei isso no fundo do velho poço seco. Uma parte do poço havia caído, e
 Isso estava nos detritos. Me desculpe, mas acredito que Jonny está morto.}
{173}{}{Não, nada ainda.}
{175}{}{Obrigado por me devolver o meu filho. Não há nenhuma maneira em que eu possa pagar você, mas por favor, pegue isso
 armadura de couro como obrigado. Experimentei um novo processo de cura; Eu acho que você encontrará isso
 armadura muito durável, e além disso - você parece muito bom nisso.}
{176}{}{Obrigado por salvar meu filho!}
{177}{}{Por favor, deixe-me no meu sofrimento.}
{178}{}{Jonny está vivo! Algumas pessoas chamadas Slags o resgataram. Se você puder esperar um pouco mais,
 Estou trabalhando de uma maneira que Jonny volte para casa para você.}
{179}{}{Jonny foi seqüestrada. Os fantasmas na fazenda o pegaram e planejam sacrificá-lo aos seus
 Deus das trevas.}
{180}{}{Compreendo; lamento perturbá-lo.}
{181}{}{Hã? Olha, não discuto minha vida pessoal com estranhos. Você tem algum negócio comigo ou
 não?}
{182}{}{Perdoe-me, meu nome é}
{183}{}{. Agora que somos devidamente apresentados, você parece incomodado.}
{184}{}{Sim, estou interessado em alguns artigos de couro.}
{186}{}{Eu acho que não.}
{187}{}{Você disse}
{188}{}{? Sim, acho que já ouvi falar de você. Um dos guardas de uma caravana que passava mencionou algo de bom
 coisas sobre uma pessoa com esse nome. Eu sei que acabamos de conhecer, mas eu realmente poderia usar seu
 Socorro.}
{189}{}{Por que você não me diz qual é o seu problema, e talvez eu possa ajudar.}
{190}{}{Tenho problemas meus, desculpe.}
{191}{}{[Ele pega um cinzel de metal e começa a torcer ansiosamente. Para seu espanto, o formão começa
 para dobrar como massa. Este cara é forte!] Meu filho, Jonny, está desaparecido! Ele saiu para jogar há alguns dias e
 nunca voltou. Nós buscamos em todos os lugares, mas ainda não o encontramos.}
{192}{}{Onde Jonny normalmente joga? Ele costuma brincar com outra pessoa?}
{193}{}{Desculpe-me pelo seu filho, mas o que eu poderia fazer?}
{194}{}{Isso é horrível! Mas eu simplesmente parei para olhar alguns artigos de couro. Eu não acho que eu poderia
 veja algumas das suas mercadorias?}
{195}{}{Oooh! Olha as horas. Eu tenho que ir.}
{196}{}{Isso significa que você vai me ajudar? Obrigado! Jonny foi visto pela última vez jogando vaqueiros e índios com
 seu cachorro Laddie na frente. Os dois são inseparáveis; na verdade, foi assim que soubemos que algo foi
 errado. Um dia, Laddie voltou sem Jonny. Estivemos procurando desde então. Tome Laddie com
 você; Talvez vocês dois possam encontrar Jonny.}
{197}{}{Bem, você tem o ar de um viajante experiente. Com suas habilidades, talvez você seja capaz de
 rastreie meu filho.}
{198}{}{Bem, sim! Eu sou um rastreador bastante experiente, se eu mesmo disser isso. Ok, eu vou ajudar.}
{199}{}{A lisonja irá levá-lo a lugar nenhum. Olha, preciso fazer algumas perguntas.}
{200}{}{Minhas orações são respondidas! Tome Laddie com você; talvez ele possa ajudar. Por favor
 pressa!}
{201}{}{Bem, talvez você esteja certo. Obrigado por ouvir.}
{202}{}{Já ouvi falar de você. Olha, não quero problemas; Somos uma comunidade pacífica. Vamos apenas manter
 O assunto às empresas, OK?}
{203}{}{Eu tenho algumas perguntas para você.}
{204}{}{Eu não tenho nenhum negócio com você por enquanto. Tchau.}
{205}{}{Bem ... estou preocupado com o meu filho desaparecido, Jonny. Nós buscamos em todos os lugares, mas ainda não conseguimos encontrar
 ele. Temo que talvez os animais selvagens o tenham conseguido.}
{206}{}{Talvez eu possa ajudar. Eu faço muitas viagens; Vou cuidar do seu filho.}
{208}{}{Eu realmente iria apreciar isso. Cada pouco ajuda. Entretanto, você teve algum
 negócios comigo?}
{210}{}{Não, na verdade não. Eu irei agora, obrigado.}
{211}{}{Desculpe, nunca ouvi falar disso.}
{214}{}{Hehehe. O Old Cornelius também fez você procurar o relógio de bolso? Não, você não encontrará isso aqui.
 Aquele velho galeão provavelmente já saiu de algum lado e esqueceu disso.}
{215}{}{Obrigado mesmo assim. Eu continuarei olhando. Tchau}
{216}{}{[Ele olha você de perto e depois sorri.] Por que você não é um bom garotinho e corre fora
 e jogar?}
{217}{}{[Ele olha você de perto e depois sorri.] Por que você não é uma boa garotinha e corre fora
 e jogar?}
{218}{}{Continue procurando. Eu sei que ele ainda está vivo, eu posso sentir isso!}
{219}{}{Essa é a arma do BB de Jonny, tudo bem. Noooooooooooooooooooo! [Balthas quebra e começa a chorar
 incontrolavelmente.]}
{220}{}{Eu sabia que Jonny não estava morto! Você diz que eu tenho que esperar ... Eu não entendo! Ele está ferido? Meus instintos
 Diga-me para ir ao meu filho, mas sinto que você tem o melhor interesse do meu filho no coração. Por favor, apresse-se e traga
 meu filho de volta para mim.}
{221}{}{Ah não! Não são os fantasmas! Eu sabia que devíamos queimar esse lugar no chão. Eu não vou deixá-los
 pegue meu garoto ... vou recuperar o Jonny, seja qual for o custo. Tenho certeza de que os moradores de Modoc
 vai me ajudar a recuperar meu filho! Conheça-nos no Ghost Farm. Vamos matá-los todos!}

{230}{}{Você retornou com segurança Jonny de volta ao Modoc.}
