# 0. Look
{100}{}{De acordo com a etiqueta em sua gola, o nome é Bess.}
{101}{}{Você vê Bess.}

{110}{}{Parece que foi atacado por algum animal selvagem. Está doendo muito ruim.}
{111}{}{Esse é um bom brahman que alguém se orgulharia de possuir.}

# 1. Bubble text
{120}{}{Moooooo!}
{121}{}{[Este pobre brahmin está ferido.]}

# 2. Jerky
{130}{}{Mooooooooo.}
{131}{}{[Bess solta um moo baixo e triste]}
{132}{}{Pobre garota - talvez eu não devesse ter vendido você por espalhafatoso. Gostaria de sair daqui?}
{133}{}{Sim! Você vai fazer um pungente e saboroso poquinho. Até mais.}

# 3. Escape? (2)
{140}{}{Mooooooo.}
{141}{}{[Isso soou como um moo muito mais feliz.]}
{142}{}{Ok, então vamos sair daqui.}
{143}{}{Só brincando. Preciso do instante mais do que eu preciso de você.}

# 4. Bubble message
{150}{}{Mooo.}

{200}{}{As habilidades de primeiros socorros não ajudarão a curar a perna quebrada deste pobre brahmin.}

{300}{}{Você cura bem a perna quebrada do brâmane.}
{310}{}{Você não cura a perna quebrada do brâmane.}
