#############################################################
#  Message File: mcChild.msg                                 #
#                                                           #
#       Body Type: CHILD                                    #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Um menino pequeno.}
{101}{}{Uma garotinha.}

{120}{}{Um menino pequeno. He seems rather playful.}
{121}{}{Uma garotinha. She seems rather playful.}
#############################################################
#  The following lines are floaters for children            #
#############################################################
{150}{}{Não me coma!}
{151}{}{Eeeee! O boogy-monster!}
{152}{}{Papai diz que você é uma pessoa má.}
{153}{}{Aieeee! Fugir!}
{154}{}{Você está me assustando.}
{155}{}{Pare de olhar para mim.}
{156}{}{Não devo conversar com tribais.}
{157}{}{Wiener dog.}
{158}{}{Minha mãe disse que você vai me comer se eu estiver mal.}
{159}{}{Eu não tenho medo de você!}
{160}{}{Me ajude!}
{161}{}{Está atrás de mim!}
{162}{}{Por favor, não me machuque!}
{163}{}{Fique longe de mim!}
{164}{}{Eeeeeeeee!}
{165}{}{Eu te odeio!}
{166}{}{Mamãe mãe mamãe!}
{167}{}{Me deixe em paz!}
{168}{}{Você fede!}

{170}{}{Olá.}
{171}{}{Quer jogar casa?}
{172}{}{Você realmente pica um osso pelo nariz?}
{173}{}{Por que você é tão engraçado?}
{174}{}{Minha mãe diz que você é primitiva.}
{175}{}{Sua tribo parou de comer pessoas?}
{176}{}{Quem te vestiu tão engraçado?}
{177}{}{Aposto que você é melhor do que parece.}
{178}{}{Vamos jogar tag. Você é isso.}
{179}{}{Você não cheira tão mal.}
{180}{}{Você viu meu amigo invisível?}
{181}{}{Eu quero viajar pelo mundo quando estou tão velho quanto você.}
{182}{}{Você é um bom tribal, não como os outros.}
{183}{}{Aposto que você se banhe.}
{184}{}{Você é mais esperto do que Torr.}
{185}{}{Essa lâmina é realmente nítida?}
{186}{}{Eu quero ser como você quando eu crescer.}
{187}{}{Meu cachorro ama a carne seca.}
{188}{}{Eu tenho um seixo brilhante.}
{189}{}{Você viu meu amigo invisível?}

{190}{}{Posso me juntar à sua tribo?}
{191}{}{Você é legal.}
{192}{}{Você parece engraçado.}
{193}{}{O que está vestindo?}
{194}{}{Eu quero um passeio brahmin!}
{195}{}{Você é de longe?}
{196}{}{Weeee! Ha, ha, ha!}
{197}{}{Não deixe!}
{198}{}{Você tem algum alimento?}
{199}{}{Estou incomodando você?}
{200}{}{Onde você está indo?}
{201}{}{Posso ir com você?}
{202}{}{Quantos anos você tem?}
{203}{}{Qual o seu nome?}
{204}{}{Você gosta de crianças?}
{205}{}{O que é isso?}
{206}{}{Você quer jogar um jogo?}
{207}{}{O que está fazendo?}
{208}{}{Você já viu algum erro?}
{209}{}{Onde você conseguiu isso?}
{210}{}{Eu posso ter aquilo?}
{211}{}{O que você faz?}
{212}{}{Eu posso correr rápido. Quero ver?}
{213}{}{Me veja! Me veja!}
{214}{}{Mamãe diz que eu falo muito.}
{215}{}{Onde está sua casa?}
{216}{}{Heeee! Heeee!}
{217}{}{Você vai ficar aqui?}
{218}{}{Você tem filhos?}
{219}{}{Por que você veio aqui?}
{220}{}{Eu gosto de você.}
{221}{}{Você gosta de mim?}
{222}{}{Você é casado?}
{223}{}{Um, dois, três ... Weee!}

{300}{}{Desconhecido!}
