{100}{}{Um homem velho.}
{101}{}{Cornelius.}
{102}{}{Além do olhar ligeiramente instável em seu rosto, parece não haver nada fora do
 comum sobre ele.}

{150}{}{Bem-vindo ao Rose's Bed and Breakfast. Meu nome é Rose - quero dizer, Cornelius - e eu corro essa cama
 e café da manhã. Posso ajudar?}
{151}{}{Se você executar este lugar, então, como é que se chama ROSE'S Bed and Breakfast?}
{152}{}{Estou à procura de um relógio dourado.}
{153}{}{O que você faz aqui?}
{154}{}{Quem é Rose?}
{155}{}{Estou interessado em conseguir um quarto.}
{156}{}{Questões? Eu estava lhe perguntando algo? Oi, meu nome é Cornelius.}
{162}{}{Você precisa de alguma ajuda séria, velho.}
{163}{}{Farrel tem o seu relógio em uma parede segura. Vamos encaderná-lo.}
{164}{}{Encontrei seu relógio na casa de Farrel. Você estava certo; Farrel é o ladrão.}
{165}{}{Parece um rato industrioso feito com seu relógio. Recuperei isso do seu ninho.}
{166}{}{Olá, thar! A gente se conhece?}
{176}{}{Meu Deus! Alguém matou meu melhor amigo, Farrel! Toda a cidade está à procura do assassino.
 Nós vamos linchá-lo quando o pegarmos!}
{177}{}{Eu o matei. O que vai fazer sobre isso, seu velho louco?}
{178}{}{Uau! Olha as horas. Eu tenho que ir.}
{179}{}{Rose é minha esposa; Eu nomeei esse lugar depois dela. Você sabia que eu sou casada?}
{180}{}{Posso fazer mais algumas perguntas?}
{181}{}{ENTÃO POR QUE NÃO PEDE QUE NENHUMA FARREL !? PODE VENDER VOCÊ O RELÓGIO QUE ESTÁ A PARTIR DE MIM!
 Agora, se você não se importa, estou bastante ocupado. Eu consegui afiar o brâmane.}
{182}{}{Eu administrai este motel. Sim, este lugar desmoronaria se não fosse por mim. Você esteve no
 Dependência? O mais limpo que você já teve. Isso está fazendo.}
{183}{}{O que tem uma dependência limpa tem a ver com a execução deste lugar?}
{184}{}{Rose é minha esposa. Ela dirige a cozinha. Você não encontrará uma refeição melhor qualquer outra coisa. Rose, ela é
 tão bonito. Eu vou me casar com ela algum dia.}
{185}{}{Eu pensei que você simplesmente disse que Rose é sua esposa.}
{186}{}{Eu tenho um quarto. Eu durmo até lá. Onde você dorme?}
{187}{}{Eu não acho que você entende. Gostaria de alugar um quarto para a noite.}
{188}{}{Há algum tempo, eu esqueci quando ... meu melhor amigo de 30 ... ou foi 40 anos? Ah, não importa,
 O que importa é que ele roubou meu precioso relógio de bolso de ouro. Foi transmitido na minha família para
 cinco, seis, err ... quatro gerações. Sim, eu lembro claramente de colocá-lo na minha mesa. Então,
 Quando eu olhei na mesa da cozinha, ele desapareceu.}
{189}{}{OK, vou trazer seu relógio de volta.}
{190}{}{Você tentou procurá-lo na sua mesa?}
{191}{}{Você vai me ajudar? Isso é ótimo! Vá bater Farrel e pegar meu relógio de volta. Ele provavelmente o escondeu bem.
 Então rasgue sua casa e procure por ela.}
{192}{}{Do que você está falando?}
{193}{}{Olha, não quero nada disso.}
{194}{}{Mate Farrel, veja o relógio ... entendeu? Eu volto já.}
{195}{}{Kill Farrel? Quem vai matar Farrel? Ele é meu melhor amigo! Eu encordoo pessoalmente o
 vilão que tenta matar Farrel.}
{196}{}{Aceito o trabalho, e espero pagamento após a conclusão.}
{197}{}{Eu não aguento mais isso. Estou indo embora.}
{198}{}{Claro, vou te pagar. Assim que terminar de limpar o celeiro, volte e me veja.}
{199}{}{Tenho um relógio. Era um relógio dourado. Eu me pergunto onde eu coloco isso?}
{200}{}{Sim Sim Sim. Eu olhei na minha gaveta de meia. Também não está lá.}
{201}{}{Vou ficar atento ao seu relógio enquanto estou na cidade.}
{202}{}{Não há como ajudar um velho louco como você. Estou fora daqui.}
{203}{}{Eu sabia que não podia confiar nele! Vou amarrá-lo pelos ouvidos até me devolver o meu
 Assistir.}
{204}{}{Não há nada lá. O xerife Jo e eu já olhamos para lá.}
{206}{}{Ele fez? Eu sabia! Eu vou ensinar-lhe uma lição que ele nunca esquecerá. É melhor ficar aqui ou você
 pode se machucar.}
{207}{}{Esse é o meu relógio! O que você está fazendo com isso? Devolva! [Ele pega o relógio do seu
 mãos.] Eu acho melhor você ir; Nós não aceitamos gentilmente os ladrões por aqui.}
{208}{}{Isso é gratidão por você.}
{209}{}{Você já experimentou omeletes de Rose? Eles são deliciosos.}
{210}{}{Eu vi Jonny jogando pelo poço com seu cachorro, Laddie. Que criança legal.}
{211}{}{Não vá para o Ghost Farm, a menos que você esteja cansado de viver.}
{212}{}{Miria é uma boa garota. Nós costumávamos jogar médico quando ela era pequena.}
{213}{}{Davin é um bom garoto. Pergunto-me por que ele não se parece com seu pai?}
{214}{}{Eu estava sentada no banheiro um dia e um grande cão saiu do esgoto. Me assustou metade para
 morte.}
{215}{}{Grisham é um bom sujeito. Ele nos vende restos para alimentar o frango gigante.}
{216}{}{Fique longe do galinheiro! Eu quase perdi um braço alimentando essa coisa.}
{217}{}{Os cachorros de Rose são viciosos, mas eu apenas joguei um pouco e não me pagam.}
{218}{}{O melhor amigo de Farrel em todo o mundo.}
{219}{}{Laddie é um cão inteligente. Eu falo com ele o tempo todo.}
{220}{}{Ouço que Grisham está tentando se casar com seus filhos. Eu me pergunto se Rose não se importaria se eu tivesse outro
 esposa.}
{222}{}{Pog? O que aconteceu com esse jogo, afinal? Bem, tenho de ir. Talvez possamos jogar depois.}
{223}{}{ENCONTREI O ASSASSINO! Ele ADMITIDO PARA MATAR FARREL! DEIXE-LHE OBTER!}
{224}{}{ENCONTREI O ASSASSINO! ELA ADMITIDA PARA MATAR FARREL! DEIXE-LHE!}
{225}{}{Eu matar Farrel.}

{300}{}{[Hmmm ... Certas palavras parecem colocá-lo fora.] Rose ... Room ... Running ...}
{301}{}{Ooga.}

{501}{}{Eu sempre soube que você era um ladrão!}
{502}{}{Como você pode fazer isso com seu melhor amigo!}
{503}{}{Eu vou te matar!}
{504}{}{Eu vou montar sua cabeça na minha parede!}

{550}{}{Ele parece estar pré-ocupado no momento.}

{600}{}{Você retornou o relógio para Cornelius.}
{650}{}{Você resolveu a disputa entre Cornelius e Farrel.}
