{100}{}{Um jovem bonito.}
{101}{}{Você vê Davin.}
{102}{}{Um jovem de vinte anos. Ele se parece muito com Grisham.}

{150}{}{Se você perguntou, você poderia me ter.}
{151}{}{Hmpf! Miria não é tão boa na cama.}
{152}{}{Eu não acredito que você me tenha pimpedicado.}
{153}{}{Vamos tentar um trio na próxima vez.}
{154}{}{Ooo ... ele é uma linda.}
{155}{}{Pergunte a ela.}
{156}{}{Isso foi ótimo; quem é o próximo?}
{157}{}{Oi! Meu nome é Davin; Ajudo meu pai a administrar o matadouro em Modoc.}
{158}{}{Estou à procura do relógio de ouro de Cornelius. Você viu isso em qualquer lugar?}
{159}{}{O que você faz no matadouro?}
{160}{}{Ouço rumores sobre você e o braim.}
{161}{}{Conte-me sobre o seu pai.}
{162}{}{Olá de novo.}
{163}{}{Eu sabia que você voltaria para mim.}
{168}{}{Por que não nos sentimos mais confortáveis?}
{171}{}{Fique aqui.}
{172}{}{Claro, não estou ocupado. Pergunta à vontade.}
{178}{}{Não, não o vi em qualquer lugar.}
{179}{}{Posso fazer mais algumas perguntas?}
{180}{}{Bem, eu ... quero dizer, eu ... eu supervisiono e cuido de coisas. Eu sou o filho do proprietário, afinal. Eu estou
 vai herdar este lugar quando meu pai começar.}
{182}{}{É mentira. Eu só sai para o celeiro de noite para ... Certifique-se de que tudo esteja trancado. Você
 Sabe, com todos os animais selvagens ao redor e todos.}
{184}{}{Papai dirige o matadouro. Ele está bem até onde vão os pais. Uma palavra de conselho se você fizer alguma
 negócios com ele. Geralmente, há mais negócios dele do que ele deixa.}
{186}{}{Volte e me veja se quiser ... fale novamente.}
{187}{}{Uau, nunca pensei que uma mulher tão bonita tentasse me seduzir. O que! Você não é uma mulher!
 Não se preocupe, você é tão bonita, não digo nada se não quiser.}
{188}{}{Eu tenho que estar sonhando. Não acredito que uma mulher tão bonita tente me seduzir. Tu es
 tentando me seduzir, né?}
{189}{}{Olhar em seus olhos é puro paraíso. Não vamos quebrar o feitiço deste momento precioso com
 palavras. Deixe nossas ações falarem por si mesmas.}
{190}{}{Pare de falar; Você vai arruinar isso para nós dois. Apenas sente-se e aproveite.}
{191}{}{Deve haver algum erro; Eu só queria fazer algumas perguntas.}
{192}{}{Obrigado pela oferta, mas não. Uhhh ... vou sair agora.}
{193}{}{Oh Deus! Leve-me! Leve-me agora! [Ele arranca suas roupas, depois suas roupas ... então ... Use seu
 imaginação]}
{194}{}{[Giggles] Eu sou "caboose"! Você pode ser a próxima vez.}
{195}{}{[Duas horas depois: a terra se moveu, e esta cama nunca mais será a mesma.]}
{196}{}{[Uma hora depois, e o melhor orgasmo que você já teve].}
{197}{}{[Meia hora depois, você está deitado exausto.]}
{198}{}{[Quinze minutos e alguns grunhidos depois.]}
{199}{}{[Você chegou até a remoção da sua camisa antes que você não sentisse mais a necessidade.]}
{200}{}{Eu tenho que ir. Tchau.}

# wedding script dialog
{400}{}{Papai!}
{401}{}{Uh-oh!}
{402}{}{Eu certamente faço!}

{410}{}{Uhh ...}
{411}{}{Uhhh ... Continue, por favor ...}
{412}{}{Eu com certeza o inferno ...}
{413}{}{Um ... eu sei.}

{450}{}{Uhhh, eu não sou o único que você deveria estar falando também.}

{500}{}{Oh garoto, eu vou ser o único responsável aqui.}

{1000}{}{Sim, meu doce.}
{1001}{}{O que posso fazer por você, garoto amante?}
{1100}{}{Estou completamente curado e pronto para ir.}
{1200}{}{Muito mais do que um arranhão deixado em mim agora.}
{1300}{}{Bem, estou curado principalmente, mas eu poderia usar mais cura quando tivermos uma chance.}
{1400}{}{Eu me curei tanto quanto pude, mas ainda estou muito mal.}
{1500}{}{Nenhum bebê; Eu quero ir com você.}
{1600}{}{Claro, eu vou deixar isso.}
{1700}{}{OK, estou bem atrás de você todo o caminho.}
{1800}{}{Então eu não seria capaz de protegê-lo. Não, é melhor ficar perto.}
{1900}{}{É isso? De jeito nenhum. Não estou deixando você fora da minha vista, sua pequena pistola sexual.}
{1005}{}{Você não entende. Eu simplesmente não quero que você fique comigo tanto quando estamos caminhando.}
{1006}{}{O que você está fazendo de errado, eu preciso que você fique muito para trás.}
{1007}{}{Mas ... Mas ... O que eu fiz de errado?}
{1008}{}{O que você quer de mim, meu querido?}
{1009}{}{Obrigado, estava começando a chatear de qualquer maneira. Então, agora, amor?}
{1010}{}{Eu costumava esconder o brâmane no matadouro, então eu sou muito útil com o
 faca. Também o pai me fez bater um braçal até a morte com um pé uma vez. Eu acho que eu poderia usar
 um clube se eu precisar. Uhhh, oh, sim, meu pai me levou a disparar uma pistola uma vez, mas eu entendi
 assustado e quase atirou nele por acidente.}
{1020}{}{Preciso de um pouco de espaço, Davin.}
