{100}{}{Um homem velho. Ele faz uma ameixa fresca fresca.}
{101}{}{Farrel.}
{102}{}{Você ouve o som de ramos secos quebrando toda vez que ele se move.}

{150}{}{Ei, afaste-se daí!}
{151}{}{Pare com isso!}
{152}{}{Ladrao!}
{153}{}{Eu não roubei o relógio, então pare de vir aqui e assediando o velho e velho Farrel!}
{154}{}{Cornelius diz que você roubou seu relógio de ouro.}
{155}{}{Onde você conseguiu o dinheiro para as novas ferramentas?}
{156}{}{O que você pode me falar sobre o Modoc?}
{157}{}{O que você faz por aqui?}
{158}{}{Assistir? Do que você está falando?}
{159}{}{O que agora!?}
{162}{}{O que você está escondendo na parede segura?}
{165}{}{Você pode me levar para o seu jardim?}
{166}{}{Limpei todos os vermes do seu jardim.}
{167}{}{Você mencionou algo sobre um relógio mais cedo.}
{168}{}{Este é o relógio que você estava procurando?}
{169}{}{Todos os furries estão mortos!}
{170}{}{Gar-din?}
{171}{}{De novo não! Quantas pessoas Cornelius vai enviar para procurar seu relógio? Eu não fiz
 isto! Na verdade, provavelmente fui vítima do mesmo ladrão. Ao mesmo tempo, seu relógio desapareceu,
 Algumas das minhas ferramentas foram roubadas. Tenho certeza que você não acredita em mim, então você pode dar uma olhada
 Em volta, caso contrário, você nunca vai embora. Bem, continue!}
{172}{}{Eu acho que vou dar uma olhada.}
{173}{}{Miria lhe disse isso? Eu vou ter que espancar seu fundo para espalhar rumores novamente! Olha, eu posso
 seja pobre, mas eu tenho meu orgulho. Ajudei um dos comerciantes a consertar seu vagão e, em troca, ele me deu alguns
 Ferramentas.}
{174}{}{Admita isso - você é culpado!}
{175}{}{Que prova você tem, o que você diz é verdade?}
{176}{}{Você espera que eu acredite nisso?}
{177}{}{Minha honra sozinha prova bastante que minhas palavras são verdadeiras. Não posso oferecer mais nada.}
{178}{}{Se você não aceitou, então, quem você acha que tomou?}
{179}{}{Eu suspeito que um ladrão que atravessasse a cidade tomasse o relógio e, desde então, mudou-se. Embora eu não possa
 Para a vida de mim, penso em uma razão que ele gostaria de minhas velhas ferramentas ...}
{180}{}{Você espera que eu acredite nisso?}
{181}{}{Não, mas, como eu sei que não fiz isso, essa é a única teoria que eu poderia encontrar.}
{182}{}{Posso fazer mais algumas perguntas?}
{183}{}{HA! Se você acha que eu sou tão culpado, por que você não acaba de me disparar e acabar com isso. Seu pequeno
 Punk, venha e me pegue!}
{184}{}{Como você achou isso? Escondi aquele cofre para que ninguém pudesse encontrá-lo. Você deve ser um
 ladrão profissional. Hmm ... onde você estava quando o relógio dourado desapareceu? Eu acho melhor sair,
 e nada melhor está faltando no cofre ou eu terei Sheriff Jo em você. Agora saia!}
{185}{}{O Modoc é uma pequena comunidade de fazendeiros e fazendeiros. Nós fornecemos a maior parte do alimento para o
 cidades vizinhas, negociando nossas culturas para vários itens essenciais. Na verdade, é muito bom
 arranjo. No entanto, isso pode mudar com a seca. Nós podemos apenas nos manter alimentados, vamos
 sozinho, tem um excedente para o comércio.}
{187}{}{Bem, na maioria das vezes eu me torno no jardim, tentando fazer essas malditas plantas crescerem sem
 agua. Não posso fazer isso agora porque algo grande se mudou e não consigo me livrar disso.
 E para superar tudo, ninguém me ajudará porque acham que eu roubei o relógio de ouro de Cornelius.}
{188}{}{Bem, na maioria das vezes eu me torno no jardim, tentando fazer essas malditas plantas crescerem sem
 agua. Mas não posso fazer isso agora porque algo grande se mudou e não consigo me livrar disso.
 Sem comida do meu jardim, eu vou morrer de fome.}
{189}{}{Eu posso ajudá-lo, por um preço.}
{190}{}{Ficarei feliz em ajudar.}
{191}{}{Admita que você roubou o relógio e eu vou ajudar.}
{193}{}{Olhar em volta! Eu sou apenas um pobre velho. Eu quase não consigo me manter alimentado, e muito menos recompensar
 você.}
{194}{}{Ficarei feliz em ajudá-lo de qualquer maneira.}
{195}{}{Desculpe, não posso ajudá-lo então.}
{196}{}{Isso seria maravilhoso. Não posso te agradecer o suficiente. Meu jardim é um pouco a leste daqui. Venha
 comigo, vou te mostrar.}
{197}{}{Obrigado! Você é verdadeiramente um herói entre heróis. Muitas pessoas não arriscaram suas vidas por um
 estranho total. Obrigado! Obrigado! Obrigado ... [Você fica com essa sensação fuzzy quente todo o caminho até
 seus dedos do pé.]}
{198}{}{Posso fazer mais algumas perguntas?}
{199}{}{Prefiro morrer de fome do que manchar meu bom nome! Vá para o inferno!}
{200}{}{Todo mundo está me acusando de roubar o relógio de bolso de ouro do meu melhor amigo Cornelius. Eu e
 Cornelius foi amigo desde que me lembro; Eu nunca tomaria seu relógio. Procurei
 Em todos os lugares, na esperança de encontrá-lo para que possamos ser amigos de novo, mas não tive tanta sorte.}
{201}{}{Estarei por um tempo. Se eu encontrar isso, eu vou deixar você saber.}
{202}{}{That’s really too bad. Posso fazer mais algumas perguntas?}
{203}{}{Você realmente? Ninguém me ajudará porque acham que eu roubei o relógio. Seria bom
 Tenha alguém do meu lado, por uma vez. Eu já questionei todos sobre isso, mas não vai doer para perguntar
 todos de novo. Talvez eles lhe digam algo que eles não me diriam. Também não vai doer para picar
 nariz em torno de Rose's Bed and Breakfast; Cornelius é notório por colocar coisas e esquecer
 onde ele colocou um minuto depois.}
{205}{}{Deixe-me ver isso! Sim, é isso! Você disse que um rato que morava pelo poço de esgoto o roubou? E você
 Desceu lá e recuperou? EWWW! Eu vou dar isso a Cornelius agora mesmo! Agora podemos ser
 amigos novamente. Obrigado.}
{206}{}{Ooga de volta para você. Como você gostaria de fazer o velho Farrel um favor, meu pouco inclinado
 amigos? Eu tenho esse pequeno problema de vermes no meu jardim. Faça as pequenas pragas se afastarem e eu darei
 você é uma recompensa.}
{207}{}{Não, não, não ... eu não faço.}
{208}{}{Sim. Eu faço.}
{209}{}{Tchau tchau!}
{210}{}{Então, saia, você morreu o morador das cavernas!}
{211}{}{Tão bom com você, meu querido amigo. [Ele toma sua mão e o leva até o jardim.] Não quereria
 você se perderá. Volte e me veja quando terminar de matar as pragas.}
{212}{}{Minha querida, doce, mulher. Você é tão gentil com um homem velho. [Ele toma sua mão e o leva até a
 jardim.] Não quer que você se perca. Volte e me veja quando terminar de matar as pragas.}
{213}{}{Fantástico! E aqui está a sua recompensa. [Ele escava nas calças e produz um biscoito meio comido.] Agora
 seja um bom homem das cavernas e tire seu biscoito lá fora e brinque.}

{300}{}{Eu vou matar aquele bastardo.}
{301}{}{Eu o odeio...}
{302}{}{Grrr ...}

{501}{}{Eu não roubei seu relógio estúpido!}
{502}{}{Eu sou inocente, eu te falo!}
{503}{}{Você não poderia bater no lado de fora de um celeiro!}

{550}{}{Ele não está prestando atenção ao que você está dizendo.}

{600}{}{Você resolveu pacificamente a disputa entre Farrel e Cornélio.}
