{100}{}{Um velho muito ativo.}
{101}{}{Grisham.}
{102}{}{Você não pode colocá-lo, mas parece familiar.}

{151}{}{Eu disse que você pegaria o seu!}
{152}{}{Bwahahaha!}
{153}{}{Vá embora!}
{154}{}{Estou ocupado!}
{155}{}{Eu sabia que minha filha era estranha.}
{156}{}{Pessoas diferentes, gostos diferentes, suponho.}
{157}{}{Eu acho que vou ficar doente.}
{158}{}{Eu sabia que meu filho era estranho.}

{159}{}{Acho que você é família, agora.}
{160}{}{Você cuida bem da minha filha.}
{161}{}{Você cuida bem do meu filho.}

# Node 0
{162}{}{O nome é Grisham. Bem-vindo ao meu matadouro. Você está saindo ou pegando?}
{163}{}{Acho que pegou? Estou interessado em comprar algumas provisões de viagem.}
{164}{}{Você não teria visto um relógio de ouro aqui em algum lugar?}
{350}{}{[Olhando para Bessy].}

# Node 1
{165}{}{O que posso fazer por você agora?}
{166}{}{Gostaria de comprar alguns dos seus famosos idiotas.}
{168}{}{Você pode me contar um pouco sobre o matadouro?}
{169}{}{Eu vejo que a seca ainda não afetou sua empresa.}
{360}{}{Gostaria que você fizesse alguns problemas para mim.}

# Node 2
{170}{}{Eu sabia que você seria capaz de lidar com isso. Vejamos agora, devo-lhe US $ 1000 para completar o trabalho. Claro,}
{171}{}{ Brahmin foi morto devido ao seu descuido. Por US $ 100 por brâmane, sua recompensa é}
{172}{}{. Não se preocupe em mentir sobre o número de brahmin morto - eu fiz um de meus meninos segui-lo
 E assista a distância.}
{173}{}{Você nunca disse nada sobre me acusar se algum brahmin morresse!}
{174}{}{Por que, conivente, secou uma velha galeira. Arg! Marque minhas palavras - esta é a última vez que você obtém o melhor
 de mim!}
{175}{}{Obrigado, pops; Prazer em fazer negócios com você.}

# Node 3
{176}{}{Como se atreve a mostrar seu rosto por aqui. Perdi dez brâmanes devido à sua covardia. No entanto, se
 Você deseja compensar, $ 1500 faria muito para cobrir minhas perdas.}
{177}{}{Esses brahmin não valiam mais que US $ 1000.}
{178}{}{Eu não tenho esse tipo de dinheiro, e se eu fizesse, eu não daria isso a um pequeno ladrão como
 você.}
{179}{}{Deixei meu dinheiro no meu quarto; Deixe-me ir buscá-lo por você.}

# Node 10
{180}{}{Ah! É claro é claro. Vejamos, para viajar, recomendo nossa brahminha seca mundialmente famosa
 tiras. Não estragará na estrada e também é gostoso. Apenas US $ 10 por pacote. Estás interessado?}
{181}{}{Parece bom; Me dê um pacote.}
{182}{}{Não, obrigado, talvez mais tarde. Gostaria de lhe fazer algumas perguntas, no entanto.}
{183}{}{É um prazer fazer negócios com você. Existe algo mais que eu possa fazer por você?}
{185}{}{Esperar! Você procura ser um viajante capaz. Eu não suponho que você estaria interessado em fazer alguns
 dinheiro?}
{186}{}{Tem certeza de que não está interessado em ganhar algum dinheiro? Tenho certeza de que você poderá resolver
 Meu problema com bastante facilidade.}
{187}{}{Depende. Quanto eu tenho que fazer e, o mais importante, QUANTO?}
{188}{}{Inteligente como chicote! Você me lembra de mim mesmo quando eu era jovem. Simples ... alguns cachorros selvagens foram
 Saindo das colinas ultimamente procurando comida. Eu acho que eles encontram brahmin fácil presa e foram
 Atacando meus rebanhos todas as noites. Limpe o seu pacote e eu lhe darei $ 1000.}
{189}{}{Você está segurando algo de volta, sua velha galeira. Qual é a captura?}
{190}{}{Perceptivo e inteligente. Eu sabia que não seria capaz de tirar nada em você. A captura é
 Que, para cada brahmin, você seja morto, cobro-lhe US $ 100. Eu pago bem pelo sucesso e também cobro
 Por falha. Esse é o risco que você toma trabalhando para mim.}
{191}{}{Ótimo! Dirija-se para as pastagens à noite e mata o pacote de cachorros selvagens que estão atacando meu
 brâmane. Volte aqui quando terminar o trabalho.}
{192}{}{Great jumping horny jacko-snatchers! Cornelius ainda está procurando seu relógio perdido? Por que ele não pode?
 Aceita que tenha desaparecido? Que o relógio dang nunca funcionou de qualquer maneira, e eu serei um tio brahmin se fosse
 Na verdade feito de ouro. Desistir; Você nunca vai encontrá-lo.}
{193}{}{Na verdade, Farrel me pediu para procurá-lo.}
{194}{}{Posso fazer mais algumas perguntas?}
{195}{}{Agradeço o mesmo, mas continuarei olhando.}
{196}{}{Não fiz? Você tem certeza? Eu poderia ter jurado, eu lhe disse ... talvez da próxima vez você não vá aceitar
 Trabalhos até que você conheça todos os detalhes. Agora, se você não se importa, eu tenho outro trabalho a ser atendido.}
{197}{}{Hehehe. Agora, tudo depende. Você está planejando ficar na cidade por muito mais tempo? Bwahahahaha!}
{198}{}{Vejo que você não é um tolo. OK - $ 1000 então, e nós chamamos isso mesmo. Agite nele.}
{199}{}{[AGITE AS MÃOS COM GRISHAM]}
{200}{}{Agora aguarde um minuto. Agora que penso nisso, esses brahmin pareciam um pouco magros. Como cerca de US $ 750,
 em vez de?}
{201}{}{Eu mudei de idéia, não quero pagar você.}
{202}{}{[Dá-lhe um grande sorriso toothy] É bom ver que você é uma pessoa de caráter.}
{203}{}{[Grisham transforma a beterraba vermelha e fala com você com os dentes apertados.] OK, $ 750 então. Me dê o dinheiro!}
{204}{}{Você sabe, US $ 750 ainda parece um pouco caro. Aqueles brahmin morreriam mesmo se os cães
 Não os obteve primeiro. Mas não sou totalmente egoísta; Eu lhe darei $ 50.}
{206}{}{BEM! DÊ ME O DINHEIRO E SORTE-SE!}
{207}{}{[DEIXE SEM PAGAR]}
{208}{}{Marque minhas palavras, você receberá o seu. Se não por mim, então, por outra pessoa.}
{209}{}{[Grisham sorri para você de tal forma que você involuntariamente dê um passo para trás.] Por que você não
 Apenas mantenha seu dinheiro? Tenho a sensação de que você precisará disso mais tarde.}
{210}{}{Não há muito para contar. Eu dirijo o matadouro em Modoc; Você quer algo abatido, você traz
 isso para mim. Eu vou matá-lo para você e torná-lo em alguns dos melhores jerky que você já provou.}
{211}{}{E quanto às peles e outras partes do animal?}
{213}{}{Na verdade, tem ajudado meu negócio. Ninguém conseguiu crescer o suficiente
 Comida para o seu brahmin, então eles estão abatiendo severamente seus rebanhos. Mas isso é apenas uma coisa temporária;
 Você tem que olhar para o quadro geral. Com o declínio na população brahmin, meu negócio só pode
 Sofra.}
{215}{}{[Grisham anda ao seu redor, puxa você um par de vezes e depois abre sua boca e verifica sua
 Dentes.] Ah! Um espécime bem e saudável. Você vai fazer o bem. Ahem ... Doggies ruins, matando um bom brahmin. Vai matar
 Os cachorrinhos ruins para o seu amigo Grisham. Grisham dará grande recompensa. ok?}
{216}{}{Não, eu gosto de cachorrinhos. Somente homem ruim não como cachorrinhos. Eu me afasto do homem ruim.}
{217}{}{Eu faço. Vá lá agora!}
{218}{}{Boa! Lembre-se, coisas ruins vão 'Woof! Woof! "As coisas boas vão 'Moo.' Tente não matar as coisas boas.}
{219}{}{Você parece ser um pouco curto de dinheiro. Não aceito crédito e certamente não acredito em
 Dando algo por nada.}
{221}{}{Isso é o que eu recebo por enviar um Neanderthal. Apenas vá!}
{222}{}{Uh ... snarf ick unga bunga. Agora tire seu dinheiro e seja um bom Neanderthal e vá embora.}
{223}{}{Você é rápido, não é? Bem, se você pedir que você possa recuperar qualquer parte do animal que você deseja.
 Balthus geralmente comprará os couros, e a Rose comprará o que quer que você não queira. Ela usa isso para
 Fazer sopa e alimentar seus cachorros.}
{225}{}{Você só pode estar brincando. Todo mundo sabe que Farrel pegou o relógio. Por que ele pediria que você pesquisasse?
 Por isso ... a menos que Farrel não tenha roubado o relógio depois de tudo! Ou talvez este seja um truque para convencer todos
 Ele não aceitou. Eu preciso pensar isso.}
{228}{}{Menino, nem tente explicar isso. Eu não quero ouvir isso. Eu vou pegar o pregador, fazer
 Isso é legal, e você vai embora e levará meu filho com você quando você for.}
{229}{}{Não posso dizer que não estou apenas ligada por isso, mas não posso viver na casa
 Agora que eu já vi. Vocês dois terão que ficar engatados e sair.}
{230}{}{Você se importa de explicar o que você está fazendo com minha filha?}
{231}{}{Você se importa de explicar o que você está fazendo com meu filho?}
{232}{}{Deixe-me explicar isso com delicadeza, aparece. Existem estes pássaros e abelhas, você vê ...}
{233}{}{Eu sou um médico, e eu estava apenas dando a ela uma física completa.}
{234}{}{Eu sou um médico, e eu estava apenas lhe dando um físico completo.}
{235}{}{Isso não é o que parece ser.}
{236}{}{Isso é ótimo. Eu vou ter um burro inteligente como genro. Bem, venha ... filho. Vamos pegar
 Acabou com isso.}
{237}{}{Isso é ótimo. Eu vou ter um burro inteligente como uma nora. Bem, venha ... filha. Vamos pegar
 Acabou com isso.}
{238}{}{Deixe-me ver. Olhou para mim que você e minha filha estavam imitando o braimmin durante o acasalamento
 estação.}
{239}{}{Deixe-me ver - olhou para mim que você e meu filho estavam fazendo o tango horizontal entre o
 folhas.}
{240}{}{OK, talvez seja o que parece ser. Mas é só sexo, não é como se houvesse amor envolvido ou
 qualquer coisa.}
{241}{}{Eu entendo perfeitamente. Hormonas, e essa é a época especial do ano.}
{242}{}{Fico feliz que você entenda.}
{243}{}{Compreendo. Espero que você entenda que vocês dois terão que ser engatados. Não pode ter rumores
 Voando sobre a cidade, você sabe. Venha e vamos buscar o pregador. Não me faça preencher você cheio de
 Buckshot.}
{244}{}{Mesmo? Então por que você estava ambos nus?}
{245}{}{Germes? Eu quero dizer GERMS! Muito importante para ser limpo ao fazer esses exames.}
{246}{}{Bem, enquanto você for um médico, acho que está tudo bem. Você melhor se vestir; Rumores tendem a começar
 Por causa de mal-entendidos como este. Enquanto você está aqui, eu tenho tido essas dores no meu
 Anus e estava pensando se você poderia examiná-lo.}
{247}{}{Err ... Eu vou ver isso mais tarde. Tenho outro paciente esperando por mim. Tchau.}
{248}{}{Sim. Por que você não vem comigo para conseguir o pregador? Não tente nada de engraçado, ou você vai
 Precisa de um médico.}

{260}{}{Eu sabia que você seria capaz de lidar com isso. Vejamos agora, devo-lhe US $ 1000 para completar o trabalho. Aqui
 Você vai.}

# rape script dialog
{300}{}{Que diabos está acontecendo aqui?}
{301}{}{Uhhh ... Senhor, eu estava apenas ...}
{302}{}{Você mantém suas mãos malditas dela ...}

#define wedding script dialog
{400}{}{O que está acontecendo aqui?}
{402}{}{Merda! eu sabia}
{452}{}{ Era diferente, mas há apenas uma maneira de fazer isso certo!}
{403}{}{Como você ousa sentir a honra do meu}
{453}{}{. Há apenas uma maneira de fazer isso certo!}
{404}{}{Uh, Jo, podemos simplesmente ignorar as partes de atadura de votos?}
{406}{}{Garoto...}
{407}{}{Missy ...}
{410}{}{Não me faça fazer}
{460}{}{ uma viúva.}
{461}{}{ Um viúvo.}
{412}{}{Miria}
{413}{}{Davin}

{220}{}{Você não vai a lugar nenhum, garoto!}
{221}{}{Você não vai a lugar nenhum, senhorita!}

# Node 4
{500}{}{Por que, é um animal bem parecido que você tem lá. Deveria fazer um bom jerky. Dizer-te o que,
 Eu vou manter um pouco de equilíbrio como pagamento. O que você disse?}
{501}{}{De jeito nenhum! Eu amo Bess. Ninguém vai se afastar dela.}
{502}{}{Parece bom para mim. Quando posso voltar para pegar minha sacudida?}
{503}{}{Esqueça, gramps. Estou fora daqui.}

# Node 5
{510}{}{Oh ... você é um daqueles. Não gostaria de tirar seu "amigo" de você. Noites no
 O deserto provavelmente seria muito solitário sem ela. Não tenho tempo para isso; Tenho trabalho a fazer.}

# Node 6
{515}{}{Ótimo! Volte em cerca de uma semana. Você pode pegar sua bagunça no fumo localizado apenas
 Fora do matadouro. Vou deixá-lo em um saco para você. Bom negócio com você.}

# Node 50
{600}{}{Howdy}
{1600}{}{. Espero que esteja cuidando bem da minha filha, Miria. Ela é a luz da minha vida e isso
 Quebraria meu coração se alguma coisa acontecesse com ela. Onde está a propósito? Eu tinha certeza de que esperava
 Para vê-la novamente.}
{601}{}{Bem, se não for}
{1601}{}{. Como a vida de casado te trata? Eu vejo meu filho Davin não viajar com você. tenho certeza
 Faça falta dele. Talvez a próxima vez que você visitar, você pode trazê-lo. Com certeza, faria um velho
 Feliz se ele pudesse ver seu único filho novamente.}
{602}{}{Uhhh, ele está morto.}
{603}{}{Uhhh, ela está morta.}
{604}{}{Miria estava viva quando eu a deixei, mas tenho certeza de que ela está morta até agora.}
{605}{}{Davin estava vivo quando eu a deixei, mas tenho certeza de que ela está morta até agora.}
{606}{}{Davin, uhhh, não poderia fazer a viagem, mas eu vou deixar que você diga: "Oi", quando eu o ver novamente.}
{607}{}{Miria, uhhh, não conseguiu fazer a viagem, mas vou enviar seu amor quando a vejo de novo.}

# Node 51
{700}{}{Aggg ... [Um olhar chocado aparece sobre o rosto de Grisham quando de repente ele agarra seu peito e desabava no chão.]}

# Node 52
{750}{}{Bem, eu tenho que voltar a trabalhar agora. Eu te vejo por aí.}

{800}{}{Você salvou o brahmin de Grisham.}
