{100}{}{Um menino pequeno.}
{101}{}{Jonny.}
{102}{}{Cabelo loiro, olhos azuis; Seu típico garoto de aparência americana.}

{150}{}{Waaaaa!}
{151}{}{Eu quero meu cachorro de volta!}
{152}{}{Choradeira…}
{153}{}{Desconhecido!}
{154}{}{Rapaz! Eu senti falta de você, garoto. Obrigado por trazer meu cão de volta para mim.}
{155}{}{Olá, eu não vi você por aqui antes.}
{156}{}{O seu nome é Jonny?}
{157}{}{Qual o seu nome, menino?}
{158}{}{Diga-me seu nome, seu pequeno monstro.}
{159}{}{Gostaria de alguns doces, criança?}
{160}{}{Olá de novo.}
{166}{}{Sua mãe e seu pai enviaram-me para encontrá-lo.}
{168}{}{Você conversou com Vegeir sobre mim indo para casa?}
{169}{}{Sim. Ele diz que quer que seus pais baixem e peguem você.}
{170}{}{Não, ainda não.}
{171}{}{Meu pai disse que Laddie foi com você para me procurar. Onde ele está? Sinto falta dele.}
{172}{}{Desculpe Jonny. Laddie morreu enquanto estávamos procurando por você.}
{173}{}{Rose disse que cuidaria do seu cachorro.}
{174}{}{Meu nome é Jonny. O que é seu?}
{175}{}{Meu nome é}
{176}{}{.}
{177}{}{Meu nome não é importante.}
{178}{}{Meu nome é Jonny, e eu não gosto de você.}
{179}{}{[He points to you and starts screaming.] Desconhecido! Desconhecido! Desconhecido!}
{180}{}{Muito prazer em conhecê-lo}
{181}{}{.}
{182}{}{Te vejo, criança.}
{183}{}{Isso é inchado! Eu queria ir para casa, mas Vegeir diz que seu povo não pode viajar tão acima
 Chão e não me levaria ... Não que eu duvide de você, mas qual o nome do meu pai?}
{184}{}{Farrel.}
{185}{}{Cornelius.}
{186}{}{Balthas.}
{187}{}{Davin.}
{188}{}{Joshua.}
{189}{}{Você não confia em mim, Jonny?}
{190}{}{Hmm ... não. Obrigado por trazer meu cão de volta para mim, mas tenho que ir agora. Tchau.}
{191}{}{Estava certo de conhecê-lo, mas tenho que ir agora. Tchau.}
{192}{}{Está certo! Yipee! Eu estou indo para casa. Peça a Vegeir se está tudo certo para você me levar para casa. Ele é
 Foi tão gentil comigo, não quero partir até que ele diga que está tudo bem. Por favor, despacha-te; Estou com saudade de casa.}
{193}{}{Ok, senhor, eu acredito em você. Peça a Vegeir que está tudo bem para você me levar para casa. Ele tem sido tão legal
 Para mim, eu não quero partir até que ele diga que está tudo bem.}
{194}{}{Ok, sinto sua falta, eu acredito em você. Peça a Vegeir que está tudo bem para você me levar para casa. Ele tem sido tão legal
 Para mim, eu não quero partir até que ele diga que está tudo bem.}
{195}{}{Não. Vou brincar com meus amigos agora. Tchau.}
{196}{}{Não devo falar com estranhos. Tchau.}
{197}{}{Sim! Como você sabia? Laddie deve ter-lhe dito. Ela é um cão tão inteligente.}
{199}{}{Você está vindo comigo, garoto. Há uma recompensa por trazê-lo de volta.}
{200}{}{Sim, acho que é melhor. Embora eu confie em você, tenho certeza de que Vegeir só quer ter certeza de que eu recebo
 Casa com segurança. Obrigado pela ajuda.}
{201}{}{Por favor, despacha-te. Eu quero ir para casa.}
{202}{}{Não! Eu não acredito em você! Me devolva meu cachorro! [Waaaaa!]}
{203}{}{Ah não! Você não sabe que Rose usa cachorro nos pratos dela !? Laddie provavelmente é um hamburguer até agora.}

{300}{}{Rapaz!!!}

{400}{}{Obrigado por me salvar, senhor.}
{401}{}{É bom estar em casa!}
{402}{}{Wahoo ...}
{403}{}{Você já não tem medo do escuro!}
{404}{}{Obrigado por me salvar, senhora.}
