{101}{}{Uma pessoa média, de altura média, de tez média. Nada fora do comum.}
{102}{}{Jo.}
{103}{}{Trader Jo.}
{104}{}{Sheriff Jo.}
{105}{}{Mayor Jo.}
{106}{}{Justice of the Peace Jo.}

{150}{}{Nós matamos todos. Até as crianças ... [soluços]}
{151}{}{Conheça-nos no Ghost Farm. Atacamos imediatamente.}
{152}{}{Obrigado por salvar os moradores de Modoc.}
{153}{}{O que você está fazendo?}
{154}{}{Ei! Deixe isso sozinho!}
{155}{}{Ladrao!}
{156}{}{Desculpe, esta posição comercial é fechada indefinidamente devido à seca.}
{157}{}{Então, quem diz que estou aqui para negociar?}
{158}{}{Eu sou novo aqui. O que você pode contar sobre essa cidade?}
{159}{}{Eu não suponho que você tenha um relógio de ouro à venda?}
{160}{}{GECK!}
{161}{}{O que posso fazer para você?}
{162}{}{Estou procurando um determinado item, e eu queria saber se você poderia me ajudar a localizá-lo.}
{164}{}{Estou olhando para comprar um relógio de bolso dourado. Você sabe onde posso conseguir um?}
{165}{}{O que você tem para negociar?}
{166}{}{O que você pode me falar sobre essa cidade?}
{167}{}{O que você faz aqui?}
{168}{}{GECK!}
{169}{}{Você voltou! O que você descobriu sobre a fazenda?}
{170}{}{Limpei seu problema de Ghost Farm. Você pode assumir a fazenda a qualquer momento.}
{171}{}{Tenho uma mensagem para você do líder das Slags.}
{172}{}{Mess-aj.}
{173}{}{Fazenda?}
{174}{}{As coisas ruins desapareceram!}
{175}{}{Eu vou.}
{176}{}{Volto quando tiver mais para denunciar.}
{179}{}{Há um bêbado no Den que combina com a descrição de Karl. Diz que ele também era um fazendeiro.}
{180}{}{Esses corpos são falsos. Apenas dummies cobertos de coragem de brahmin. Eles estavam lá para assustá-lo longe das colheitas.}
{181}{}{O que eu deveria fazer de novo?}
{182}{}{O que? Oh, você deve ser novo por aqui. Bem-vindo ao Modoc. Meu nome é Jo, eu administrai o posto comercial
 Aqui no Modoc.}
{183}{}{Estou em uma missão. Procuro o sagrado GECK. Sabe onde posso encontrá-lo?}
{186}{}{Bem, você está com sorte. Eu apenas sei onde é. Eu acho que temos algum negócio para
 Discutir depois de tudo.}
{187}{}{O negócio? Apenas me diga onde posso encontrar o sagrado GECK e eu irei no meu caminho.}
{188}{}{Nosso único negócio é que você vai me dizer onde o sagrado GECK está localizado antes de algo ruim
 Acontece.}
{189}{}{O que você deseja para essa informação?}
{190}{}{Ah, sim, o que eu quero ... Se você ainda não notou, nossa pequena comunidade agrícola está experimentando uma
 Das suas piores secas. A estação das chuvas foi excepcionalmente curta este ano, e nossas colheitas estão mortas ou
 Morrendo por falta de água. Para dizer sem rodeios, nossa comunidade está à beira de desaparecer com a nossa
 cultivo.}
{191}{}{Umm ... Você sabe que não posso fazer chover, certo?!?}
{192}{}{[Ele ri de graça] Não, não ... claro que não. Eu não pediria que você fizesse algo tão impossível quanto
 aquele. Você realmente não pode fazer chover, você pode ... Não, claro que não pode! Enfim, como eu disse, estamos
 Em dificuldade e poderíamos usar sua ajuda.}
{193}{}{OK, eu estou ouvindo.}
{194}{}{Há esta fazenda nos arredores da cidade, onde nenhuma fazenda deveria ser. Há alguns anos atrás, apenas
 "Apareceu" do nada.}
{195}{}{Você está dizendo que essa fazenda surgiu da noite para a noite? Okay, certo!}
{196}{}{Um grupo de nós estava caçando quando percebemos a nova fazenda. Mas isso não era estranho.
 Logo depois, alguns de nós se juntaram para visitar nosso novo vizinho, apenas para descobrir que não havia
 alguém aí.}
{197}{}{Continue.}
{198}{}{Depois de muitos meses tentando entrar em contato com os proprietários sem sucesso, foi decidido que a fazenda
 Deve ter sido abandonado logo após a construção. Então, em vez de deixar as culturas apodrecer nos campos,
 O jovem Karl mudou-se.}
{199}{}{Hmm…}
{200}{}{Foi quando as coisas ficaram ruins. Karl começou a contar histórias de ver figuras incrivelmente estranhas
 Cuidando as culturas e alimentando os animais à noite. Todos nós rimos dele, pensando que ele estava inventando
 Histórias. Então, um dia, Karl parou de chegar à cidade.}
{201}{}{O que aconteceu com ele? Você o procurou?}
{202}{}{Claro que nós fizemos! Nós fomos lá, assim que suspeitamos que algo estava errado. [Ele começa a
 Treme violentamente.] O horror. Corpos espalhados por toda parte. Alguns crucificados, enquanto outros eram
 Deixada para apodrecer ao sol. Eu ainda acordo gritando no meio da noite do horrível
 Imagens que eu vi naquele dia.}
{203}{}{Então, deixe-me adivinhar. Você quer que eu vá para esta fazenda e descubra o que aconteceu.}
{204}{}{Normalmente, eu deixaria aquele lugar amaldiçoado, mas por algum motivo as colheitas nesta fazenda
 Ainda estão florescendo apesar da seca. Nós morreremos de fome se não recebermos comida em breve. Você nos ajudará
 Livrar a fazenda desses fantasmas?}
{205}{}{O que eu saio disso?}
{206}{}{Em troca de nos ajudar, eu direi onde você pode encontrar o que procura.}
{207}{}{OK, então vamos selar o acordo. Corte seu dedo mindinho direito.}
{208}{}{Então é um acordo. Mostre-me onde está esta fazenda fantasma.}
{209}{}{O que?!? É assim que você marca um acordo de onde você é? Estamos desesperados e acredito que você é o
 Única pessoa que poderia tirar isso. Então, acho que é um pequeno sacrifício, se isso salvará nossa cidade. [Jo
 Tira uma faca e prossegue para cortar o dedo mindinho direito!]}
{210}{}{[Você o pára apenas a tempo.] Espere! Eu vejo agora que você estava falando a verdade e realmente precisa de
 Socorro. Vou te ajudar.}
{211}{}{Agora, pegue o dedo e refogue-o com um molho de alho leve. Prato muito saboroso!}
{212}{}{Esta fazenda é cerca de um dia de viagem a nordeste daqui. [Ele tira um mapa e aponta para um ponto
 Nordeste de Modoc.] Volte quando você encontrou alguma coisa.}
{213}{}{[Jo calmamente envolve sua mão em uma atadura e depois procede a tirar uma espingarda!] Vamos ver se
 Você pode rir assim, burro inteligente!}
{214}{}{[ESTRONDO!]}
{215}{}{Você deve estar brincando! Eu não vou cortar meu dedo. Estou desesperado, não estúpido! Agora, faça
 Você quer o trabalho ou não?}
{216}{}{OK, eu vou fazer isso mesmo. Onde está localizada esta fazenda?}
{217}{}{Você obviamente não está desesperado o suficiente. Vou passar.}
{218}{}{O que é que foi isso? Você disse GECK?}
{219}{}{Unh. GECK.}
{220}{}{Eu vou.}
{222}{}{Meu nome é Jo. Você pode dizer que Jo? Não importa; Você vê essa coisa retangular por aí? Aquilo é um
 porta. Tenha cuidado para não deixá-lo atingido no caminho certo.}
{223}{}{[Você não entende tudo o que ele está dizendo, mas você sorri e volta para sair.]}
{224}{}{[Ele parece tentar algo por um pouco e depois sorri e olha para você.] Talvez possamos
 Elaborar um comércio depois de tudo. Meu nome é Jo; Eu administrai esta postagem comercial aqui. Tenho algumas informações sobre
 GECK. Estás interessado?}
{225}{}{[Você acena com a cabeça para cima e para baixo.]}
{226}{}{[Você balança a cabeça da esquerda para a direita.]}
{227}{}{Fantástico! Há esse fantasma ... er, fazenda à beira da cidade. É cerca de um dia de caminhada a nordeste de
 Aqui. As coisas ruins acontecem lá. Faça as coisas ruins pararem, então volte e eu falarei sobre GECK.}
{228}{}{Eu vou agora.}
{229}{}{Bem, não temos mais nada para falar. A porta está bem ali.}
{230}{}{Sim, esse é um grande chip no seu ombro. Por que você não volta quando esse chip não é tão
 grande? Você tem um bom dia e cuidado com essa porta na sua saída.}
{231}{}{Bem, então - bem-vindo ao Modoc. Meu nome é Jo e eu corro esse post comercial aqui. Nós não temos
 Muito de; Apenas algumas fazendas, um matadouro, Rose's Bed and Breakfast e um curtume. Apenas o suficiente para
 Produzir bens para o comércio. Embora isso possa mudar com esta seca.}
{232}{}{O que você pode me falar sobre o matadouro?}
{233}{}{Rose's Bed and Breakfast?}
{234}{}{Conte-me sobre a posição comercial.}
{235}{}{Onde está o curtume?}
{236}{}{Posso fazer mais algumas perguntas?}
{237}{}{O matadouro é administrado por Grisham e seu filho Davin. Está a leste daqui. Ele faz o
 O melhor maldito toque deste lado das Montanhas Rochosas.}
{242}{}{Rose's Bed and Breakfast fica no lado norte da cidade. Os viajantes de todos os lugares vêm apenas para
 Experimente as omeletes mundialmente famosas. Alguns dizem que suas omeletes podem curar as pessoas do que as aflige. Francamente, eu
 Acho que é só um monte de bobagens.}
{247}{}{Apenas siga o seu nariz e você vai encontrá-lo. Você pode cheirar esse mau cheiro no ar? Esse é o
 Tanning tanques ao norte daqui. Se você negligenciar o cheiro, você não encontrará um lugar melhor para obter
 artigos de couro. Balthus pode fazer milagres com couro.}
{252}{}{Como eu disse antes, meu nome é Jo e eu administrai o posto comercial para o Modoc. Eu organizo o comércio entre
 Modoc e outras cidades que precisam de alimentos e artigos de couro. Mas com esta seca, tudo pode vir a
 Um fim real em breve. Estamos ficando desesperados.}
{257}{}{Sobre o que você quer falar? O matadouro, Rose's Bed and Breakfast, o curtume ou o
 Posto comercial?}
{262}{}{Bem, cuspiu. Não posso ajudá-lo se você não me disser o que está procurando e eu tenho certeza
 Não vai ficar aqui e tentar adivinhar o que você está procurando.}
{263}{}{Estou à procura do sagrado GECK.}
{264}{}{Deixa pra lá.}
{265}{}{Como confio muito nos produtos das pessoas da Modoc, não tenho muito para trocar. Você
 Sabe, com a seca e tudo. Você ainda está interessado?}
{266}{}{Vamos fazer algum negócio.}
{267}{}{Não, obrigado, mas posso fazer mais algumas perguntas?}
{268}{}{Não, talvez mais tarde. Eu tenho que ir agora.}
{269}{}{Agora, essa é uma boa pergunta. Principalmente, eu acabei de executar este post comercial aqui. Mas na ocasião, eu sou o
 Xerife, prefeito, juiz e qualquer outro funcionário que você possa pensar.}
{270}{}{Uau; Você deve ser um sujeito muito popular para ser confiado com todos esses deveres.}
{271}{}{Obrigado pela informação; Eu irei agora.}
{272}{}{Nah ... acabei de tirar a palha curta. Parece que eu estava comprando algum material e quando voltei,
 Descobri que as pessoas da cidade foram e me elegeram. Parece que ninguém mais queria o trabalho. Exceto pela
 Argumento ocasional, eu realmente não tenho que fazer nada - o que me convém bem.}
{273}{}{Posso fazer mais algumas perguntas?}
{274}{}{O que! Você está tentando ser um burro sábio? Todo mundo sabe que o velho Corny perdeu seu relógio de bolso dourado.
 Ele mesmo me fez procurar a casa de seu melhor amigo procurando por ele. Se você sabe o que é bom para você, você
 Mantenha seu nariz fora disso. Dia bom!}
{275}{}{[Ele tira a mensagem das escórias.] O que é isso? É das pessoas que vivem no Fantasma
 Fazenda. Isto é incrível; Você leu ... oops, é claro que você não. Ainda há algumas coisas que
 Precisa ser trabalhado entre Slags e Modoc, mas é muito complexo para o seu minúsculo cérebro
 Entenda, então você não precisa se preocupar com isso.}
{276}{}{GECK agora!}
{277}{}{Bem, isso poderia ser um pouco difícil. Você vê que eu realmente não sei o que é um GECK. Mas eu sei
 De um lugar chamado Gecko, nunca estive lá, mas ouvi dizer que está em algum lugar a leste daqui. eu sinto
 Muito ruim em enganá-lo. Eu gostaria de poder dar-lhe mais no caminho da compensação do que isso,
 Mas o melhor que posso lhe oferecer é um desconto em bens. Eu não estou muito abastecido agora mesmo, mas eu sou
 Certo, as coisas vão se aproximar por aqui logo e eu ficaria honrado em ajudá-lo a economizar.}
{278}{}{Empurrão!}
{280}{}{Eu não culpo você por estar bravo comigo, mas não sinto muito por ter feito isso. Precisamos de alguém para o trabalho
 E você se encaixa na conta. Tudo o que posso dizer é "obrigado", e enviá-lo no seu caminho.}
{282}{}{Sim ... faaarmm. Fazenda no nordeste. Vá fazenda. Faça as coisas más ir adeus.}
{283}{}{Isso é ótimo! Vou enviar algumas pessoas imediatamente para começar a colher as colheitas. Você salvou
 nos.}
{284}{}{Mostre GECK!}
{285}{}{Slags? Quem são eles? O que é isso? [Jo abre e lê a mensagem.] Isso é incrível! Eles têm
 Estava vivendo no subsolo todo esse tempo. Eles dizem que estariam dispostos a trocar alimentos por suprimentos médicos
 E outras coisas. Não sei se eles podem ser confiáveis. Afinal, eles mataram Karl e todos aqueles outros
 pessoas. O que você acha?}
{286}{}{Todos esses corpos são falsos. Nada além de manequins cobertos de entranhas de brahmin. Eles só queriam
 Evitar que você roube suas colheitas.}
{287}{}{Eles são extremamente sensíveis à luz. Eu acho que um pequeno grupo de pessoas armadas com flares
 Seja capaz de limpar toda a sua comunidade.}
{288}{}{Encontrei Karl no Den. Ele saiu porque ninguém acreditaria nele sobre os fantasmas e ele era
 assustada.}
{289}{}{Eles estão segurando o pequeno refém de Jonny! Precisamos atacar agora!}
{290}{}{Falso! Mas, eu vi os corpos com meus próprios olhos. De qualquer forma, Karl ainda está desaparecido. Como eles
 explique isso? Eu não confiarei neles até estar certo de que eles estão em cima e para cima.}
{292}{}{Eles disseram que a pessoa que mudou em alguns anos deixou de repente.}
{293}{}{Karl não faria isso. Provavelmente o mataram! Não, até descobrir o que aconteceu com Karl, eu
 Não pense em poder confiar neles. Eu estava esperando que não viesse a isso, mas vamos ter que
 Assumir a sua fazenda. Somos nós ou eles.}
{294}{}{Não espere! Deixe-me tentar descobrir o que aconteceu com Karl. Deve haver uma explicação para o seu
 desaparecimento.}
{295}{}{Eu concordo que devemos atacar! A sua fraqueza são os olhos deles.}
{296}{}{Eu não concordei com isso. Descobri o que está acontecendo no Ghost Farm. Agora me diga onde eu
 Pode encontrar o sagrado GECK.}
{297}{}{Eu vou dar um mês para descobrir o que você pode sobre Karl. Se você não voltar dentro disso
 Tempo, eu vou mobilizar os moradores de Modoc e vamos levar a fazenda pela força.}
{298}{}{OK, um mês! Não faça nada de erupção até então. Eu voltarei.}
{299}{}{Eu preciso de mais tempo. Será impossível encontrá-lo em tão curto período de tempo.}
{300}{}{Um mês, não mais! Eu disse que estávamos desesperados. Nosso fornecimento de alimentos está sendo extremamente baixo.
 Nós temos o suficiente por um mês; Depois disso, todos começamos a passar fome. Eu vou começar a organizar o
 Pessoas imediatamente. Você se apressa!}
{301}{}{Por favor, não faça nada de erupção cutânea até retornar!}
{302}{}{[Chocado] The Den! Eu - eu acho que nós somos um pouco difíceis com ele. Posso imaginar o que ele passou em
 A Ghost Farm, sem que ninguém acreditasse nele e a todos. Você diz que ele é um bêbado agora, no Den? Se você pudesse
 Dê-lhe a mensagem de que acreditamos nele e que ele deveria voltar para casa, eu ficaria muito agradecido. Dentro
 Entretanto, eu acredito que já é hora de os Slags e os moradores de Modoc se familiarizarem.}
{303}{}{Eu acredito ter cumprido a minha parte da barganha. Que tal me dizer onde eu posso encontrar o
 Sagrado GECK?}
{304}{}{[Parecendo um pouco envergonhado.] Um ... bem, você vê, eu realmente não sei nada sobre este santo
 GECK coisa que você está procurando. Você tem que entender; Estávamos desesperados! No entanto, eu sei de um lugar
 Chamado Gecko. É uma maneira a leste de aqui. Se eu fosse um homem de apostas, eu apostaria seu geco GECK
 Está localizado lá. Gostaria de deixar mais que eu poderia te dar, mas ainda somos uma comunidade pobre com não
 Muito no caminho das ofertas. O melhor que posso fazer é oferecer-lhe bens basicamente em meu custo. Mas
 Eu ficaria honrado em ajudar a mantê-lo abastecido para suas viagens quando eu tenho os bens e tenho certeza de que qualquer
 Dos outros residentes estariam igualmente gratos se você lhes pedisse. Obrigado! Você nos salvou a todos.}
{305}{}{Bem, eles mataram Karl junto com todas aquelas outras pessoas apostadas na frente de sua fazenda.
 OK vamos fazê-lo. Você viu seu esconderijo e parece bastante capaz; Você vai nos levar à vitória sobre
 Aqueles Slags traiçoeiros?}
{306}{}{Claro! Por uma causa justa, ficaria feliz em ajudá-lo a derrotar os Slags.}
{307}{}{Talvez essa não seja uma boa ideia; Pensemos em outra maneira.}
{308}{}{Isso é ótimo; Eu irei reunir os moradores e nos encontraremos lá.}
{309}{}{Você viu Jonny lá! Estivemos procurando em todos os lugares por ele. Esses monstros, estão roubando
 nossos filhos. Não estaremos seguros até que eles estejam todos mortos. Eu juntaremos as pessoas da cidade e nós iremos
 Tempestade seu esconderijo. Conheça-nos no Ghost Farm logo que possível.}
{310}{}{Como você pode viver com você mesmo? Estamos em uma crise aqui e tudo o que você pode pensar é o seu próprio
 Necessidades egoístas. Muito bem, por que você não vai para Gecko? Está a leste de aqui em algum lugar. Se alguém souber
 Sobre esse assunto de GECK, tenho certeza que sim. Agora, se você não se importa, eu preciso me encontrar com as pessoas da cidade, então
 Podemos descobrir o que fazer.}
{311}{}{Isso é ótimo. Quais eram essas coisas, afinal?}
{312}{}{Apenas uma comunidade de mutantes. Se não fossem fantasmas antes, eles estão agora.}
{313}{}{Eles eram fantasmas. Eles foram embora. É tudo o que você precisa saber. Agora, me diga onde posso encontrar o
 Sagrado GECK.}
{314}{}{Você quer dizer que você entrou e matou todos ?! Não queria dizer que você fizesse isso. Você foi enviado
 Para investigar o que estava acontecendo na fazenda e depois retornar com a informação. Eu acho você melhor
 sair.}
{315}{}{Vamos atacar, mas apenas como último recurso. Temos apenas um suprimento de alimentos por mês
 Antes de começar a morrer de fome. Você tem até então para descobrir o que está acontecendo. Não vou negociar com
 A menos que eu tenha certeza de que eles não fizeram nada para Karl.}
{316}{}{Vamos atacar, mas apenas como último recurso. Temos apenas um suprimento de alimentos por mês
 Antes de começar a morrer de fome. Você tem até então para descobrir o que está acontecendo. Não vou negociar com
 A menos que eu tenha certeza de que eles não fizeram nada para Karl e eu tenho que saber o motivo deles
 Por apostar todas essas pessoas na frente da fazenda. Não vou lidar com os selvagens.}
{317}{}{Eu acho que você gosta de matar pessoas um pouco demais para o meu gosto. Eu acho que é melhor ir embora.}
{318}{}{[Chocado] The Den! Eu - eu acho que nós somos um pouco difíceis com ele. Eu posso imaginar o que ele passou
 Na Ghost Farm, sem que ninguém acreditasse nele e a todos. Você diz que ele é um bêbado agora, no Den? Se vocês
 Poderia dar-lhe a mensagem de que acreditamos nele e que ele deveria voltar para casa, eu seria o mais
 Apreciativo.}
{319}{}{Eu também descobri que todos aqueles corpos que cercam o Ghost Farm são falsos. Dummies, coberto
 Com tripas brahmin.}
{320}{}{Agora você vai falar com o líder do Slags?}
{321}{}{Isso é tudo o que sei por agora.}
{322}{}{Falso! Isso é impossível, eu os vi com meus próprios olhos. Sangue e sangue em todos os lugares. Mas eu acho
 É possível, nós não ... Quero dizer ... bem [O rosto de Jo se transforma em vermelho]. Nós todos nós nos voltamos e corremos
 Quando vimos os corpos. Ninguém realmente teve coragem de examiná-los de perto.}
{326}{}{Sim, acredito que Slags e as pessoas do Modoc poderão chegar a algum tipo de mutuamente
 Acordo benéfico. Obrigado por salvar as pessoas do Modoc.}
{327}{}{Há esta pequena coisa sobre minha recompensa? Você disse que me diria onde estava o sagrado GECK.}
{328}{}{Você precisa descobrir quem são essas pessoas apostas na frente da Fazenda Fantasma.}
{329}{}{Karl desapareceu da fazenda há algum tempo. Descubra o que aconteceu com ele.}
{330}{}{Obrigado, vou ver o que posso descobrir.}
{331}{}{Nós não queremos o seu tipo por aqui.}

{400}{}{[Deixando ele cortar o dedo] OK, agora vou ajudar.}
{410}{}{Qual é o grande edifício branco no meio da cidade?}

{500}{}{Oh, essa é a nossa igreja da cidade. As pessoas de Modoc construíram para mostrar sua fé. Recentemente,
 Não há muito para agradecer, então ninguém atende mais aos sermões.}

# wedding script dialog
{600}{}{Caro amado: estamos aqui reunidos ...}
{602}{}{[Jo transforma algumas páginas em seu livro.]}
{603}{}{Ok, hum ... Antes de começar, alguém na sala conhece algum motivo por que esses dois
 Aqui, antes de nós, não deveríamos juntar-nos no santo matrimônio?}
{604}{}{Você}
{605}{}{ levar}
{606}{}{ Para ser legalmente casado}
{607}{}{Então, por lei de fronteira, eu declaro você em anexo. Agora você pode beijar a noiva.}
{608}{}{Então, por lei de fronteira, eu declaro você em anexo. Suas noivas agora podem se beijar.}
{609}{}{Então, por lei de fronteira, eu declaro você em anexo. Agora você pode beijar o outro.}

{625}{}{marido?}
{626}{}{esposa?}
{627}{}{Uhhh ... outro? Sim, legalmente casado?}
{628}{}{de outros?}

{629}{}{Miria}
{630}{}{Davin}

{800}{}{Nós vamos atacar as Slags em}
{801}{}{ Dias a menos que você possa me convencer de outra forma.}
{802}{}{Nós vamos atacar as Slags amanhã, a menos que você possa me convencer de outra forma.}
{803}{}{Estamos atacando as Slags imediatamente! Você está dentro ou fora?}
{804}{}{Conte comigo!}
{805}{}{Eu já tive o suficiente disso, conte-me!}
{806}{}{Vamos atacar agora. As Slags mostraram que não podem ser confiáveis.}

{820}{}{O que posso fazer para ajudar?}
{821}{}{Eu não quero parte disso. Cumpriu o meu fim da barganha. Diga-me onde está o GECK.}

{850}{}{Volto quando descobrir o que aconteceu com Karl.}

{900}{}{Mais uma vez, meu amigo, por salvar nossa pequena cidade.}
{925}{}{Seja bem-vindo. Ver você de novo.}

{1000}{}{Você salvou a cidade de Modoc.}
