{100}{}{Uma pessoa muito bêbada. [Ele tem um sinal que diz: "Trabalhará por comida"].}
{101}{}{Karl.}
{102}{}{Ele é tão imundo que você percebe que flores selvagens crescem de seus cabelos.}

{150}{}{Aqui, tome uma cerveja.}
{151}{}{Aqui, tenha uma garrafa de bebidas alcoólicas.}
{152}{}{Aqui, tenha um Nuka-Cola.}
{153}{}{Ei.}
{154}{}{Ei!}
{155}{}{EI!!}
{156}{}{Os fantasmas não poderão me encontrar aqui ... [soluço]}
{157}{}{É bom voltar para casa.}
{159}{}{É Karl; Ele desmaiou.}
{160}{}{Ele vai ter que dormir.}
{161}{}{Ah! Os fantasmas da fazenda vieram me pegar!}
{162}{}{Poupe alguma mudança para (hic) um fazendeiro fora do trabalho?}
{163}{}{Claro, cara; quanto você precisa?}
{164}{}{Que tal eu compro uma refeição quente?}
{165}{}{Desculpe, eu não tenho dinheiro.}
{166}{}{Qual a sua história?}
{167}{}{Aqui é cha-ange?}
{168}{}{Jooky.}
{169}{}{Oh, pessoa gentil e generosa. (Hic) Como Karl pode ajudá-lo hoje? (Hic) [Ele tira o boné e
 Estende a mão.]}
{170}{}{Aqui. Aqui estão $ 100.}
{173}{}{Desculpe, não tenho nada para você. Tchau.}
{174}{}{Você sabe onde posso encontrar um GECK?}
{175}{}{Você mencionou algo sobre um jardim mais cedo. Me diga mais.}
{178}{}{Eu vou.}
{179}{}{Ei, cheapskate! (Ai) Venha, eu sei que você gots dinheiro ... (hic) Apenas algumas mudanças de reposição, então ... (hic)
 alguma coisa qualquer coisa! Mostre alguma compaixão.}
{180}{}{Aqui. Aqui estão $ 25.}
{184}{}{Aqui. Aqui é $ 1.}
{185}{}{Aqui dinheiro.}
{186}{}{Sem dinheiro.}
{187}{}{O que você quer?}
{188}{}{[Conte a Karl sobre o que Jo disse.]}
{189}{}{Fantasmas, Karl ... eles estão em todos os lugares. Olha, há um agora!}
{190}{}{Gibba gibba.}
{191}{}{Você está aqui (hic) para se divertir com o pobre Karl novamente? (Hic) Bem, o que você está esperando? (Hic)
 Vamos acabar com isto!}
{198}{}{[Em uma voz arruada.] Poderoso tipo de você ... (hic) A $ 1000 otta me atrapalha.}
{199}{}{Claro, aqui está você.}
{200}{}{Por quanto tempo, um ano? De jeito nenhum; Aqui tem $ 25.}
{201}{}{Você deve me levar por um tolo. Estou fora daqui.}
{202}{}{[A boca de Karl fica aberta com surpresa] Obrigado! Você é uma pessoa (muito) muito generosa ... (hic) Se
 Qualquer coisa que você precisa (hic) apenas venha me ver. Por sinal, o nome é Karl.}
{203}{}{Claro, Karl; Agora que você menciona, estou procurando um item chamado GECK. Qualquer indicação de
 Onde eu poderia encontrar um?}
{204}{}{Eu vou manter isso em mente. Cuide-se, Karl.}
{205}{}{Que tipos de pessoa é você? (Hic) Jogando truques em uma fazenda sem residência pobre (hic) -er. Deixe-me
 sozinho!}
{206}{}{Sim ... (hic) Algum tipo de lagarto (hic) eu ouço. Nunca vi um, no entanto.}
{207}{}{Não, estou procurando um GECK, não um gecko.}
{208}{}{Deixa pra lá. Obrigado pela informação.}
{209}{}{Ah! Ya significa gecko ... (hic) Sim, é um liz- (hic) -ard sobre tão grande. [Karl detém as mãos para
 Mostre o tamanho. Você não pode dizer, mas o lagarto tem 3 polegadas de comprimento ou 3 pés de comprimento.]}
{210}{}{Deixe-me tentar explicar. Não estou à procura de um lagarto chamado gecko. Procuro um objeto
 Chamado GECK.}
{212}{}{Por que você não disse isso? (Ai) Eu sei onde conseguir ... (hic) Jardim de ... [Karl cai no chão
 Enfrenta e passa para fora.]}
{213}{}{[Talvez quando Karl acordar, você pode conversar com ele novamente.]}
{214}{}{Te abençoe! (Hic) Ya me salvou a vida.}
{215}{}{Procuro um GECK; pode me ajudar?}
{216}{}{Não mencione isso. Eu vou ver você ao redor, Karl.}
{217}{}{Um ... (hic) Eu não estou realmente com fome agora ... (hic) Que tal se você me der o dinheiro e eu vou ter
 mais tarde? (Hic)}
{219}{}{Você shyster. Aposto que você usa o dinheiro que você coleciona para comprar chems, não é?}
{220}{}{Shi ... tímido ... shick ... Tudo o que você acabou de sed? (Hic) Tome isso de volta ... (hic) Seja o que for, não pode
 seja bom.}
{221}{}{[Antes de poder responder, Karl cai e passa para fora.]}
{222}{}{Thaaaats ok ... (hic) Eu não suponho que você tenha nenhuma atualização líquida. Ele é poderoso (hic)
 Frio aqui à noite.}
{224}{}{Você é verdadeiramente o meu melhor amigo neste mundo amaldiçoado (hic). [Karl procede a beber
 O refresco líquido, em que ponto ele passa para fora]}
{225}{}{Bem, talvez você possa conversar com Karl mais tarde.}
{226}{}{Você é verdadeiramente o meu melhor amigo neste mundo amaldiçoado (hic). [Karl abre a garrafa
 E procede a beber - e depois prosseguiu para você em toda parte.] Ptui! O que?! Você está tentando
 Envenenar-me ou algo assim ?! Saia daqui!}
{227}{}{Por que, obrigado (ai) você; Você é tão (do) tipo. Por que não o ajudo com essa bolsa pesada? [Karl
 Entre na sua bolsa e leva metade do seu dinheiro.] Muito gentil de você (hic) se você precisar de alguma coisa,
 Não hesite em perguntar.}
{228}{}{GECK?}
{229}{}{Eu vou.}
{230}{}{Jooky ... hic ... É uma festa em uma lata.}
{231}{}{Talvez depois, então.}
{232}{}{Gee ... (hic) ... obrigado. Talvez eu consiga comprar uma bala para me disparar. (Hic) Curso eu gostaria
 Tem que salvar (hic) para a arma.}
{233}{}{Você quer dizer ... Eu posso ir para casa? Não há mais fantasmas? [Karl quebra e chora. Menino, nada como ver
 Um homem adulto chora.] Obrigado, eu posso finalmente voltar para casa novamente!}
{234}{}{Onde?! Nooooooooo! Eles me encontraram!}
{235}{}{Por que sim, eu tinha o maior jardim (hic) que uma pessoa poderia querer. Exceto (hic) de onde eu venho, nós
 Chama isso de fazenda ...}
{236}{}{Você não se lembra? Estávamos falando sobre o GECK, e você mencionou um jardim.}
{237}{}{Esqueça, isso não vai a lugar nenhum.}
{238}{}{Ei! (hic) You’re kind a cute! Let’s me and you go out back (hic) and gets better acquainted. I can
 pay… I’ve got a $1000. [Karl leers suggestively to you.]}
{239}{}{Você sabe que está falando com um homem, não é?}
{240}{}{Claro, mas isso custará US $ 1000.}
{241}{}{Obrigado pela oferta, mas prefiro falar sobre encontrar um GECK.}
{242}{}{Não em sua vida!}
{243}{}{Yer sooo purty ... (hic) Se você não diz nada, não vou. (Hic)}
{244}{}{[Você dificilmente pode evitar engasgar.] Eu tenho que ir.}
{245}{}{OK, US $ 1000.}
{246}{}{[Você e Karl deslizam para trás para um quickie. Para sua surpresa, você achou que você gostou.]}
{247}{}{[Ele se calma rapidamente e começa a contar o seu conto.] Eu costumava ser um cidadão errado antes
 vindo aqui. Eu era um fazendeiro pacífico que trabalhava nos campos tão duro quanto qualquer homem - até que eles começaram
 Aparecendo à noite. Tudo brilhante, com peles brancas pastosas ... Destruí o inferno de mim, sim. Noite
 Depois da noite, eles apareceram e roubaram culturas e gado semelhante; Não pude fazer nada para detê-los. eu sei
 O que você vai dizer - "Por que você não pediu ajuda?" Eu falo, eu fiz! Ninguém acreditaria em mim, eles
 Pensei que era uma loucura. Finalmente, tornou-se demais para mim. EU NÃO PODE TOMAR-LHE! Acabei
 E saiu e vim aqui - e aqui já estive. [Karl começa a chorar incontrolavelmente. Você
 Decide deixá-lo com sua miséria.]}
{248}{}{Oh, jeez. Devo ter abandonado meu dinheiro ao longo do caminho. Aqui está $}
{249}{}{.}

{250}{}{Zzz}
{251}{}{Zzzzzz}
{252}{}{Zzzzzzzzz}
{253}{}{Zzzzzzzzzzzz}
{254}{}{Zzzzzzzzzzzzzzz}
{255}{}{* Snort * * grunt * * snort *}

{260}{}{Oh, jeez. Devo ter abandonado meu dinheiro ao longo do caminho. Aqui está $}
{261}{}{. É tudo o que tenho.}
{262}{}{Oh, jeez. Devo ter abandonado meu dinheiro ao longo do caminho. Desculpe, foi divertido de qualquer maneira.}

{300}{}{Estou indo para casa, graças a você!}

{400}{}{Você enviou Karl no caminho de volta para Modoc.}
