{100}{}{Parece ser um border collie.}
{101}{}{Rapaz.}
{102}{}{Este cão parece ser realmente alerta e inteligente.}
{103}{}{Você não tem dúvidas de que este cão provavelmente é mais inteligente do que você.}

{150}{}{Woof!}
{151}{}{Woof! Woof!}
{152}{}{Woof! Woof! Woof!}
{153}{}{[Este cachorro parece muito agitado.]}
{154}{}{Boa cachorrinha.}
{155}{}{Você sabe onde está Jonny, garoto?}
{156}{}{Fique aqui, Laddie}
{157}{}{Vamos encontrar Jonny.}
{158}{}{Jonny caiu no poço, Laddie?}
{159}{}{Qual é o assunto boy, você está tentando me dizer algo?}
{160}{}{Grrrr! [Laddie leva uma mordida viciosa para você.]}
{161}{}{[Hmm ... Por algum motivo ele não gosta de você.]}
{162}{}{Woof! Woof! Woof! [Laddie salta sobre você e começa a lamber seu rosto.]}
{163}{}{[O que é um bom doggy.]}
{164}{}{Woof? [Você quase pode ouvir o cachorro rindo de você.]}
{165}{}{[Ninguém gosta de um burro inteligente.]}
{167}{}{Jonny está em algum lugar perto em Modoc?}
{168}{}{Jonny deixou Modoc?}
{169}{}{Jonny foi sequestrado por alienígenas?}
{170}{}{Não tenho tempo para jogar, Laddie; Precisamos encontrar Jonny. Vamos.}
{171}{}{Perto do matadouro?}
{172}{}{Perto do curtume?}
{173}{}{Perto da posição comercial?}
{174}{}{Perto do poço?}
{175}{}{Talvez algum outro lugar, então?}
{177}{}{Near Rose's Bed and Breakfast?}
{180}{}{Ele foi para o norte?}
{181}{}{Ele foi para o sul?}
{182}{}{Ele foi para o leste?}
{183}{}{Ele foi para o oeste?}
{186}{}{Woof?}
{187}{}{Okay, Okay… Talvez algum outro lugar, então?}

{190}{}{He was playing cowboys and Indians when he accidentally fell down the well and you want me to
 get a rope and go down and rescue him. Okay, let's go, Rapaz. [Astounding!]}
{191}{}{He was playing cowboys and Indians when he accidentally fell down the well and you want me to
 use my rope and go down and rescue him. Okay, let's go, Rapaz. [Astounding!]}
{195}{}{OK, vou pegar uma corda e descer o poço para resgatar Jonny.}
{196}{}{OK, eu posso usar minha corda e descer o poço para resgatar Jonny.}
