{100}{}{Oh meu! Uma mulher muito bonita e sedutora.}
{101}{}{Miria.}
{102}{}{Você não tem certeza, mas as medidas 36-24-36 vêm à mente.}

{150}{}{Cadela!}
{151}{}{Como você ousa mostrar seu rosto por aqui!}

{152}{}{Isso é apenas doente!}
{153}{}{Espero que vocês dois estejam felizes juntos.}

# Node 0
{154}{}{Por que, olá, estranho. Eu sou Miria.}
{155}{}{Estou tão satisfeito que você voltou. O que posso fazer por você agora?}
{156}{}{O que você faz por aqui?}
{157}{}{O que você pode me falar sobre o matadouro?}
{158}{}{Ouviu algum bom rumor?}
{159}{}{Hubba! Hubba!}

# Node 2
{160}{}{Se eu não estivesse tão entediado, eu diria que não. Então, pergunte.}

# Node 10
{164}{}{Há rumores de que Farrel roubou o relógio.}
{165}{}{Por que Farrel roubaria o relógio?}
{166}{}{O melhor amigo de Farrel Cornelius?}
{167}{}{Conte-me mais rumores.}

# Node 11
{168}{}{Porque as pessoas pobres tendem a roubar para chegar ao fim. Farrel definitivamente cai nos pobres
 Categoria, e isso explicaria as novas ferramentas que ele comprou logo que o relógio de Cornelius desapareceu.}
{170}{}{Posso fazer mais algumas perguntas?}

# Node 12
{171}{}{Sim, eles eram grossos como ladrões, esses dois. É por isso que penso que Farrel roubou o relógio. Quem
 Senão Farrel teria o acesso e a oportunidade de roubar o relógio de Cornelius?}

# Node 13
{174}{}{Nada a dizer. Minha família corre no matadouro. Pessoas de todos os lados trazem seu brahmin
 Aqui para o abate. Depois de serem abatidos e a carne tratada, é vendida a comerciantes que por sua vez
 Vendê-lo para comerciantes em várias cidades. Tudo muito aborrecido, se você me perguntar.}

# Node 14
{176}{}{Você veio ao lugar certo! Esta cidade é tão chata, não há mais nada além de fofoca
 E ... [Ela continua falando por algum tempo e, algum tempo depois, você é capaz de obter uma palavra.]}
{177}{}{O que mais você quer saber?}
{178}{}{O que você sabe sobre o relógio que falta Cornelius?}
{179}{}{Você mencionou algo sobre Rose?}
{180}{}{O que há sobre um brahmin mutado?}
{181}{}{Conte-me sobre Davin.}
{182}{}{Vamos falar sobre outra coisa.}

# Node 15
{183}{}{Ah, Rose. O proprietário da Rose's Bed and Breakfast. Agora, você não ouviu isso
 Eu, mas você já se perguntou por que sua "coop" está tão bem protegida? Ela diz que é para
 Proteja suas galinhas de predadores, mas se você olhar de perto parece que ela é
 Tentando manter algo em vez de sair. Além disso, quem já ouviu falar de galinhas, deixando 12 libras
 ovos?}
{184}{}{Diga-me mais rumores.}

# Node 16
{186}{}{É realmente estranho, mas eu ouço alguns fazendeiros dizerem que de vez em quando um brâmane vai
 Dar à luz um bezerro com apenas uma cabeça. Fale sobre estranho!}

# Node 17
{189}{}{Ele é família; Eu não espalhei rumores sobre minha própria família.}

# Node 18
{192}{}{Quem eu? Eu faço trabalhos estranhos aqui e ali. Certamente nada vale a pena falar. [Ela vibra com ela
 Olha para você.]}
{193}{}{Eu realmente gostaria de saber mais sobre você.}
{194}{}{Você está certo, fala o suficiente. Vamos obtê-lo em! Você sabe que você quer.}

# Node 19
{196}{}{Estou realmente tocado. Ninguém jamais tenta me conhecer melhor. Tudo o que eles querem é sexo, sexo, sexo!
 Eu fico tão cansado de ter sexo selvagem o tempo todo. Estou tão feliz que você não é como os outros.}
{197}{}{Você puta! Eu pensei que você era especial por um momento.}
{198}{}{Você sabe, eu sou apenas um cara normal como todos os outros. Por que meus amigos dizem: "}
{199}{}{ Você é tão legal porque você é normal, como todos os outros. "Sim, normal, sou eu.}
{200}{}{Bem, nunca conheci ninguém tão interessante quanto você.}

# Node 20
{202}{}{Quer o que? Apenas o que você está insinuando?}
{203}{}{Acho que você sabe do que estou falando, querida. Você sabe que isso é o que você quer. [Você sorri e
 Começar a despir.]}
{204}{}{Esqueça; Eu sinto Muito. Não queria dizer nada.}

# Node 21
{205}{}{Como você ousa me chamar de puta! Deixe-me dizer-lhe, eu sou muito exigente com as pessoas com quem eu durmo.
 Por que só dormi com 10 ou 20 pessoas este mês! Acho que essa conversa terminou!}

# Node 22
{206}{}{Que decepção. Você é como todos os outros, não é?}

# Node 23
{208}{}{Não. Não penso assim. Estou cansado dessa conversa. Adeus.}

# Node 24
{209}{}{[Ela corva] Pare, você está me envergonhando. Você é apenas a coisa mais doce. Por que não vem
 Por aqui e sente-se perto de mim.}
{210}{}{Eu acho que isso vai muito longe. Não podemos falar?}
{211}{}{Eu pensei que você nunca perguntaria. Por que não ficamos um pouco mais confortáveis.}
{212}{}{Tudo certo! Você sabe o que eu quero, querida!}
{213}{}{Você é uma vagabunda, não é você?}

# Node 25
{214}{}{Eu não aguento mais isso! Você é perfeito. [Ela arranca suas roupas, suas roupas e depois ...]}
{215}{}{[Seu mundo nunca mais será o mesmo.]}

# Node 26
{216}{}{Isso não significa o que eu acho que isso significa.}
{217}{}{Aoooga!}
{218}{}{Urg?}

# Node 27
{219}{}{Sim! Isso foi o que eu pensei. É engraçado como o discurso de Neanderthal e civilizado atravessa estradas
 este assunto. [Você nem vê-lo vir. Mas você tem certeza de que a impressão vermelha da mão no seu rosto irá
 Desaparecer um dia.]}

# rape script dialog
{250}{}{Ajuda, papai! Retire-o!}
{251}{}{Cai fora!}
{260}{}{Ajuda, papai! Tire-a embora!}

# wedding script dialog
{400}{}{Papai!}
{401}{}{Uh oh!}
{402}{}{Eu certamente faço!}

{410}{}{Uhh ...}
{411}{}{Uhhh ... Continue por favor ...}
{412}{}{Com certeza, o inferno ...}
{413}{}{Um ... eu sei.}

{450}{}{Uhhh, acho que papai é o único que você deveria estar falando também.}

{500}{}{Ótimo, acho que isso significa que eu tenho que executar este despejo agora.}

# in party dialog
{1000}{}{O que faremos agora, querida?}
{1001}{}{O que faremos agora, querido?}
{1002}{}{O que faremos agora, pooky?}
{1003}{}{O que faremos agora, amante?}
{1004}{}{O que faremos agora, fundo de açúcar?}
{1005}{}{Não, não, não ... Não esse tipo de distância! Preciso que você dê um passo atrás quando estamos caminhando.}
{1006}{}{Relaxe, apenas me dê mais espaço quando estamos caminhando.}
{1007}{}{Vou tentar mais, bolos de manteiga. É difícil conseguir o tempo de "nós" aqui neste deserto.}
{1008}{}{As minhas coisas são suas coisas.}
{1009}{}{Ok, muffin, mas temos que parar com apenas a armadura?}
{1010}{}{Armas afiadas como facas me deixam excitada, embora eu possa usar armas como um SMG em
 Uma pitada se eu precisar. Apenas não espere que eu realmente toque nada.}
{1020}{}{Precisamos falar sobre a distância entre nós.}
{1100}{}{Estou completamente curado e pronto para ir.}
{1200}{}{Muito mais do que um arranhão deixado em mim agora.}
{1300}{}{Bem, estou principalmente curado - mas eu poderia usar mais cura quando tivermos uma chance.}
{1400}{}{Eu me curei tanto quanto pude, mas ainda estou muito mal.}
{1500}{}{Nenhum bebê; Eu quero ir com você.}
{1600}{}{Certo, vou deixar isso longe.}
{1700}{}{}
{1800}{}{Não, não, ervilha doce. Eu preciso estar perto de você.}
{1900}{}{Mas então eu não estaria perto de você, caroços de açúcar.}
