{100}{}{Você vê um cidadão.}

# General
{200}{}{Certamente espero que chove em breve.}
{201}{}{Nossos cultivos estão morrendo por falta de água.}
{202}{}{Mesmo os poços ficaram secos.}
{203}{}{Nenhuma núvem no céu.}
{204}{}{Estou pensando em me afastar daqui.}
{205}{}{Modoc costumava ser uma comunidade agrícola próspera.}
{206}{}{A vida em Modoc é lenta. Assim como eu gosto disso.}

# Ghost Farm Seed Active
{220}{}{Ouvi dizer que as pessoas viram figuras brilhantes durante a noite na Ghost Farm.}
{221}{}{Você ouviu? Eles encontraram um idiota para investigar o Ghost Farm.}
{222}{}{Fui ao Ghost Farm. Assustador!}
{223}{}{O dia é o melhor momento para ir ao Ghost Farm.}
{224}{}{Karl costumava morar na Ghost Farm. Agora ele provavelmente o assombra.}
{225}{}{As pessoas não devem mexer com o sobrenatural.}
{226}{}{Por que os fantasmas cultivariam alimentos?}

# If player delivered message from slags to Jo - Delivered=yes
{240}{}{Eles descobriram que as pessoas que vivem no Ghost Farm se chamam Slags.}
{241}{}{Que tipo de nome é Slag?}
{242}{}{Eu não confio no Slags.}
{243}{}{Talvez eu pudesse confiar no Slags se soubesse o que aconteceu com Karl.}

# If Player Agrees to help Modoc to Attack the Ghost Farm
{260}{}{Vou encontrá-lo na Ghost Farm.}
{261}{}{Vamos matar um monte de escórias assassinas.}
{262}{}{Espero que possamos fazer o que é certo.}
{263}{}{Devemos atacar durante o dia, enquanto eles estão dormindo.}

# If the player and the town wipeout the Slags
{280}{}{As Slags eram como nós ...}
{281}{}{Nós até matamos as mulheres e os filhos das Slags.}
{282}{}{Eu me sinto sujo.}
{283}{}{As manchas de sangue não sairão das minhas mãos!}
{284}{}{Espero que ninguém descubra o que fizemos.}
{285}{}{O que fizemos com o Slags estava errado.}

# If the player kills the Slags by himself
{300}{}{Você ouviu? Um sacerdote poderoso exorcizava os fantasmas da fazenda.}
{301}{}{A colheita da Ghost Farm deve nos manter alimentados por mais um ano.}
{302}{}{Não há uma gota de água no Ghost Farm.}
{303}{}{Talvez o solo da Ghost Farm seja mágico. De que outra forma as culturas poderiam crescer sem água?}
{304}{}{Talvez os fantasmas usassem sangue para alimentar suas colheitas.}
{305}{}{Eu acho que os fantasmas estavam roubando nossa água.}
{306}{}{Aposto que as coisas voltarão ao normal por aqui, agora que os fantasmas se foram.}

# If the player successfully completes the Ghost Farm seed. Best ending.
{320}{}{Nós vamos trocar com Slags.}
{321}{}{As Slags ofereceram fornecimento de água para Modoc durante a seca.}
{322}{}{Você é o que nos ajudou, não é? Você é um herói!}
{323}{}{Você salvou a cidade de Modoc.}
{324}{}{Você será sempre bem-vindo no Modoc.}
