{100}{}{Você vê um guarda escória.}

# surrender
{150}{}{Entregue ou morra!}
{151}{}{Eu me rendo.}
{152}{}{Morrer!}
{153}{}{Ug!}
{154}{}{Se você precisa ver o Vegeir, podemos escoltá-lo para ele.}
{155}{}{Agora não. Vejo Vegeir mais tarde.}
{156}{}{Sim, preciso ver o Vegeir imediatamente.}

{160}{}{Você é mais idiota que a sujeira, não é você! Se você quiser ver o Vegeir, você pode ir buscá-lo sozinho.}

# caves
# - general
{200}{}{Eu não confio em "surfacers".}
{201}{}{Vegeir disse não prejudicá-lo ... AINDA!}
{202}{}{Estamos encarregados de proteger nossas pessoas.}
{203}{}{Estou te observando.}

# - mission complete
{220}{}{Eu acho que você está OK ... para um "surfacer".}
{221}{}{Talvez possamos nos dar bem com os "surfacers".}
{222}{}{Fico feliz por estar errado com você.}
