{100}{}{Uma mulher agradavelmente gorda.}
{101}{}{Rosa.}
{102}{}{Seu cabelo cinza é feito em um pão solto, e ela caminha com um ligeiro pavão. Você não pode ajudar, mas
 sente-se relaxado ao redor dela.}

{150}{}{Me desculpe, estamos fechados. Houve uma morte na família. [farejar]}
{151}{}{Ei! Eu sou o único permitido percorrer a caixa perdida e encontrada.}
{152}{}{Estou começando a pensar que você é um ladrão!}
{153}{}{Ladrao! Ladrao! Ladrao!}
{154}{}{Bem-vindo ao Rose's Bed and Breakfast. Meu, você não é o jovem de cintas. O que pode ajudar Rose?
 você com hoje?}
{155}{}{Bem-vindo ao Rose's Bed and Breakfast. Oh, minha querida e linda senhora você. O que Rose pode fazer?
 para você hoje?}
{156}{}{Estou morrendo de fome! O que você tem para comer aqui?}
{157}{}{Gostaria de alugar um quarto para a noite.}
{158}{}{Você deve ouvir as coisas trabalhando aqui. Lembre-se de fazer algumas perguntas?}
{159}{}{[Você bate seus lábios com um POP alto]}
{160}{}{Fico feliz em vê-lo novamente! O que posso fazer para você?}
{165}{}{Oh meu! É você. Todo mundo está falando sobre como você arriscou sua vida por nós e resolveu a
 mistério da Ghost Farm. Saiba que você é sempre bem-vindo aqui e, claro, todas as suas refeições estão em
 a casa. Você também pode derrubar a caixa perdida e encontrada e levar o que desejar como especial
 recompensa.}
{166}{}{É o herói do Modoc! Bem vindo de volta.}
{167}{}{Gostaria muito de ter um de seus omeletes deliciosos agora.}
{168}{}{Isto é o que eu gosto de ouvir. Um menino jovem e crescente precisa comer para manter sua força, e eu posso
 Diga que você não está comendo adequadamente. Você simplesmente sente-se e olha o menu.}
{169}{}{E assim você deveria estar. Quando foi a última vez que você teve uma boa refeição, jovem? Por que você é como
 fino como um trilho. Você apenas olha o menu e conta a Rose o que você gostaria de comer.}
{170}{}{batatas fritas brahmin. [$ 5]}
{171}{}{Omelete de Wasteland. [$ 25]}
{172}{}{Agua. [$ 1000]}
{173}{}{cães brahmin. [$ 5]}
{174}{}{Hambúrgueres de Canis. [$ 7]}
{175}{}{Guisado de pastor. [$ 3]}
{176}{}{Não, obrigado; Eu não estou com fome agora mesmo.}
{177}{}{Oh, desculpe, mas você não parece ter dinheiro suficiente. Por que você não volta mais tarde?}
{178}{}{Mas estou morrendo de fome! Talvez eu possa pedir algo mais barato.}
{179}{}{Esperar! Posso te fazer algumas perguntas?}
{180}{}{Volte para mais alguns, vejo. Você deve realmente gostar de batatas fritas brahmin. Eu sinto Muito; já que você segura o
 registro, você não pode entrar no concurso novamente até que outra pessoa quebre sua pontuação.}
{181}{}{Brahmin fritas é, então. Temos um concurso sobre quem pode comer a maioria das batatas fritas brahmin; até agora, o
 O registro é 36. Se você quebrar o registro, você não precisa pagar a guia para sua refeição. Você parece
 você poderia vencer o registro sem nenhum problema. Você está interessado em tentar?}
{182}{}{Tudo bem, estou disposto a pagar para comer o seu delicioso escroto de brahmin frito.}
{183}{}{Estou com tanta fome. Provavelmente posso duplicar essa pontuação. Pode vir.}
{184}{}{Não, obrigado; apenas um pedido, por favor.}
{185}{}{Oh, isso é apenas grande. Cada pedido consiste em 10 peças. Eu vou ter que pedir-lhe o dinheiro para cima
 frente. Eu vou reembolsá-lo assim que você quebrar o registro. Isso será $ 20, por favor.}
{186}{}{Eu não tenho tanto. Por que não tento para o registro mais tarde? Vou receber um pedido. Obrigado.}
{187}{}{Claro, vou recuperá-lo quando eu quebrar o registro.}
{188}{}{[Rose tira o dinheiro e volta com um prato amassado de batatas fritas brahmin. Eles não são
 o que você esperava. Eles parecem ter o tamanho das bolas de golfe, cobertas de massa e fritas
 Óleo para um marrom profundo e dourado. Você toma uma mordida tentativa de uma das batatas fritas. Estes são deliciosos! Você
 Comece com a fartura com alegria.]}
{189}{}{[At around the 34th fry, you start to feel the effects of overeating. A crowd has gathered to
 witness the historic event of the old record being broken. In an attempt to regain your composure, you
 strike up a conversation with Rosa.]}
{190}{}{[Você faz uma frita na sua boca.] 'Mmff ... splt ... mnch ...' Não fale com a boca cheia, querida. [Você
 andorinha.]}
{191}{}{Como você prepara estes? Se não é um segredo ou nada, eu conheço algumas pessoas de volta para casa, quem
 adoraria estes.}
{192}{}{Ah, não é segredo. Você simplesmente mergulha na massa, adicione um pouco de sal e frita em graxa. [Você é pop
 outro na sua boca.]}
{193}{}{Como você prepara a carne de brahmin? Tem uma textura tão única. [Você coloca ainda mais um
 sua boca. Estes são bons!]}
{194}{}{Isso é 37! Você acabou de quebrar o registro! [A multidão cheers!]}
{195}{}{[Você sente como se tivesse conseguido que você estivesse com o segundo vento e que outra frite em sua boca.]}
{196}{}{[A multidão grita, "38!"] Bem, o que faz o nosso gosto tão especial é que você tem que colher isso
 enquanto o braim ainda está vivo. Você apenas pega o brâmane pelo escroto e "pega" quatro com um
 cortar. Você tem cuidado; O brahmin geralmente é irritado nesse ponto.}
{197}{}{[O 38º brahmin tidbit deve ter estado indo à velocidade da luz, pois é de repente e
 forçado de sua boca.]}
{198}{}{Não podemos contar o último, mas você quebrou o recorde em 37! Aqui está o seu dinheiro de volta.
 Parabéns!}
{199}{}{[Você está doente.]}
{200}{}{Ah, essa é a minha especialidade. Espero que você esteja com fome; Garanto que nunca tenha experimentado uma omelete como
 este em qualquer lugar. [Ela sai e volta com o maior omelete que você já viu.]}
{201}{}{[Você se sente revitalizado após uma refeição tão grande.]}
{202}{}{[Ela desaparece rapidamente atrás do balcão e retorna com seu pedido.]}
{203}{}{Posso te fazer algumas perguntas?}
{204}{}{Desculpe, docinho, estou muito ocupada atendendo clientes. Talvez se você tenha encomendado algo que eu tenha
 hora de conversar com você entre ordens.}
{205}{}{Nesse caso, estou morrendo de fome. O que você tem para comer?}
{206}{}{Claro, mas faça isso rápido, querido. Não quero manter os outros clientes em espera.}
{207}{}{O que você pode me falar sobre o relógio desaparecido de Cornelius?}
{208}{}{Você já ouviu falar de um GECK?}
{209}{}{O que você sabe sobre o Ghost Farm?}
{210}{}{Nunca vi um omelete do tamanho daquele que você me serviu. Que tipo de animal estabelece
 ovo grande?}
{211}{}{O que é um hambúrguer de canis?}
{212}{}{Oh céus! Você falou com meu marido Cornelius? Todo esse negócio com o relógio é
 apenas terrível. Cornelius conseguiu toda a cidade acreditando que seu melhor amigo, Farrel, tomou seu relógio.
 Se você falou com ele, tenho certeza que você percebeu que sua mente não está funcionando corretamente. Eu sou bonita
 Certo, a pobrezinha acabou de deixar o relógio em algum lugar e esqueceu onde.}
{213}{}{Agora, se você não precisa de mais nada, eu tenho outros clientes para servir.}
{214}{}{Posso fazer mais algumas perguntas?}
{215}{}{Um momento, ainda estou com fome.}
{216}{}{Você disse GECK? Não, não posso dizer o que tenho. Ouvi falar de boa receita de sopa que requer
 três geckos. Mas não, não ouvi falar de nada sobre um GECK.}
{217}{}{[Ela se arrepende involuntariamente.] Fique longe de lá! Ouvi contos de viajantes sobre
 corpos apodrecidos amarrados a estacas e formas brilhantes que se deslocam pelos campos à noite. Eu não sei como
 Muito disso é verdade, mas sei um pouco atrás, Karl se mudou para lá e não foi visto desde então.}
{218}{}{Ah, você teve o omelete do deserto. Delicioso, não era? Algumas pessoas dizem que tem cura
 propriedades. [Ela olha em volta nervosamente.] Oh! Alguns clientes acabaram de entrar. Volto logo. [Hmm…
 Ela nunca respondeu sua pergunta.]}
{220}{}{Nossos hambúrgueres são feitos de nada além do cão escolhido, selecionado, de grau A. A carne está triturada e
 feito em empanadas de meio-libra. E para dar-lhe esse único sabor fumegante, eles são lentos grelhados sobre secas
 esterco de brahmin.}
{221}{}{Pobrezinho. Você está meio morrendo de fome. Venha, sente-se e deixe Rose tomar algo para comer. [Ela
 sai e volta com uma omelete grande.] Agora, você não se move daquele lugar até terminar todos os bits
 por essa.}
{222}{}{Desculpe, estamos completos. Uma grande caravana tem todos os quartos alugados.}
{225}{}{Mesmo!? Você deve estar realmente com sede. Levantei o preço para desencorajar os clientes de ordená-lo.
 A água potável é premium aqui, com a falta de chuva e o bom secar. Você ainda quer
 alguns?}
{226}{}{Sim! Preciso de água desesperadamente.}
{227}{}{Na verdade, estou com muita fome.}
{228}{}{Desculpe, paramos de servir omeletes. Alguns idiotas entraram em nossa cela e mataram nossa ... frango.}
{229}{}{Estou com muita fome, então vamos ver o que mais você tem.}
{230}{}{Eu estava realmente ansioso para a sua omelete mundialmente famosa. Acho que vou passar fome.}
{231}{}{Ahh! Oogie!}

{300}{}{[Ela retorna rapidamente com um copo de alguma substância líquida acastanhada. Parece que existe
 mais sujeira que a água no copo. No entanto, você tem tanta sede que você o bebe de qualquer maneira.] Eu trouxe
 um biscoito para você desfrutar com isso, docinho.}
