# Description
{100}{}{Você vê um rapaz escorrente no trabalho cuidando do brahmin.}
{101}{}{Você vê o menino estável.}
# Examine:
{150}{}{Ele parece estar ocupado.}

# General
{200}{}{Desculpe, os estábulos estão cheios. Você terá que procurar em outro lugar.}
{201}{}{Estou muito ocupado agora.}

# If shitter is exploded
{250}{}{Cheiro? Eu acho que você se acostume com isso.}
{251}{}{Não cheira tão mal.}
{252}{}{Eu acho que não tenho que fertilizar os campos este ano. Obrigado.}

# General Stable Comments
{300}{}{Este precisa de um feno fresco.}
{301}{}{Tenho que obter mais água.}
{302}{}{Whew! Tempo para pegar a pá.}
{303}{}{Tudo parece bom com este.}
{304}{}{É melhor manter um olho nisso. Parece um pouco doente.}

# trying to sleep
{350}{}{Zzz ... estou dormindo ... Zzz ...}
{351}{}{* YAWN * Tenho que acordar cedo.}
{352}{}{Ei, ainda estou crescendo. Eu preciso do meu sono.}
{353}{}{Por que você não fala com outra pessoa?}
{354}{}{Boy, eu tenho sono. Se alguém não continuasse falando comigo.}
