# Flee
{100}{}{Corre!}
{101}{}{Socorro!}
{102}{}{Estamos a ser atacados pelos surfacers.}
{103}{}{Deixe-nos em paz.}
{104}{}{Não podemos simplesmente nos dar bem?}

# Attack
{150}{}{Volte de onde você veio.}
{151}{}{Você não é desejado aqui.}
{152}{}{Todos vocês, surfacers, são parecidos.}
{153}{}{Você não escapará.}

# General Dialogue (above ground)
{200}{}{Gemido!}
{201}{}{Vaia!}
{202}{}{Moaaaaaan.}
{203}{}{* Clank *}
{204}{}{* Clink *}

# General Dialogue (below ground)
{250}{}{Nós costumávamos viver acima do solo.}
{251}{}{Como é sobre o solo?}
{252}{}{Está tão alto lá em cima.}
{253}{}{Como é o sol?}
{254}{}{Olá, surfacer.}

# General Dialogue when Seed is completely done
{300}{}{Eu sabia que poderíamos confiar em você.}
{301}{}{Obrigado por nos ajudar.}
{302}{}{É um prazer ver você de novo.}
