# 0. Look
{100}{}{Parece ser um guarda de algum tipo.}
{101}{}{Um protetor.}

{150}{}{Além da pele pálida e das pupilas alargadas, ele parece ser uma pessoa comum.}

# 1. Floats - When player first falls down hole
{200}{}{Merda!}
{201}{}{Oooh! Agora isso deve doer.}

# 2. ( ) Floats - When player falls down hole other times.
{210}{}{Você sabe que pode entrar da porta dos fundos ...}
{211}{}{Bwahahahaha!}
{212}{}{Não vou dizer uma palavra.}
{213}{}{Oh Deus! Você está me matando! Faça isso novamente!}
{214}{}{Que idiota!}
{215}{}{Hahahaha!}

# 3. ( ) First Time Talk
{220}{}{Nós fomos instruídos a levar todos os surfacers a Vegeir. Você não será prejudicado. Por favor
 venha conosco.}
{221}{}{Vá para o inferno, eu não vou a lugar algum com você.}
{222}{}{Gostaria de fazer algumas perguntas.}
{223}{}{Duh?}

# 4. ( ) Go to hell
{224}{}{Deixe-me elaborar a minha declaração anterior. Você não será prejudicado a menos que resista. Estamos
 Você está resistindo?}
{225}{}{Sim, eu vou absolvê-lo.}
{226}{}{Não, eu sei que a resistência é inútil. Eu irei com voce.}

# 5. ( ) Questions
{230}{}{Vegeir responderá todas as suas perguntas. Por favor, venha conosco.}
{231}{}{Ok, eu irei com você pacificamente por enquanto.}
{232}{}{Não, não vou a lugar algum com você, a menos que receba algumas respostas.}

# 6. ( ) You're dumb!
{240}{}{Hmm ... Eu me pergunto se esta é uma exceção à regra. Não não não. Vegeir disse que TODOS os surfacers,
 Até mesmo os idiotas. Venha comigo.}
{241}{}{[Vá com os guardas.]}
{242}{}{[Mate todos e deixe que os deuses que eles adorem classificem-los.]}

# 7. ( ) General Floats
{250}{}{Eu sinto Muito; Você não pode sair desse jeito.}
{251}{}{Esta entrada é para os trabalhadores.}
{252}{}{É preciso muito esforço configurar as rampas para apenas uma pessoa.}
{253}{}{Se quiser sair, pergunte a Vegeir.}

# goes in node 3
{260}{}{Ogey Dogey.}
