{500}{}{Você vê um comerciante.}

# General (Roses B&B)
{100}{}{Rose faz os melhores omeletes.}
{101}{}{Psst ... Fique longe das batatas fritas brahmin.}
{102}{}{Paro com todas as chances de Rose.}
{103}{}{Você já experimentou omeletes de Rose?}

# If player blows up the shitter (Roses B&B)
{110}{}{Você cheira alguma coisa?}
{111}{}{Bom Deus! Por que diabos você está entrando?}
{112}{}{Você pode ficar a favor do vento? Estou tentando comer.}

# Bedroom (Rose's B&B)
{120}{}{Você se importa? Estou tentando dormir um pouco.}
{121}{}{Ei, o que você está fazendo no meu quarto ?!}
{122}{}{Saia!}

# If player let the chicken out of the coop (Roses B&B) overrides above text
{130}{}{Rose está fora de omeletes.}
{131}{}{Vou matar a pessoa que deixa sua galinha escapar.}
{132}{}{Não há sentido vir aqui se não conseguir uma omelete.}

# Pre Ghost General
{140}{}{Não sei por que me incomodo vir aqui para negociar.}
{141}{}{Esta cidade está morrendo.}
{142}{}{Esta costumava ser uma cidade agrícola próspera.}

# If player kills Slags by himself
{150}{}{Ouço que Modoc "adquiriu" uma fazenda próspera no nordeste daqui.}
{151}{}{Não sei se quero trocar por comida cultivada no Ghost Farm.}
{152}{}{As culturas da Ghost Farm provavelmente são amaldiçoadas.}

# If town slaughter ghost farm
{160}{}{Ouvi dizer que eles mataram mulheres e crianças inocentes.}
{161}{}{Não quero trocar com os selvagens que matam imprudentemente.}
{162}{}{Depois de ouvir o que fizeram, quase vomitava.}
{163}{}{Seja qual for o motivo deles, não acho que venha pela Modoc para negociar mais.}
{164}{}{As pessoas de Modoc são assassinas.}

# If the player completes ghost farm seed - best ending.
{170}{}{Parece que as coisas estão olhando por aqui.}
{171}{}{Provavelmente preciso contratar outra equipe para levar todos os alimentos a partir daqui.}
{172}{}{Parece que o Modoc vai ficar bem depois de tudo.}
