{100}{}{Você vê o líder das Slags.}
{101}{}{Você vê Vegeir.}
{102}{}{Um homem alto e majestoso. Seus movimentos lembram um gato que persegue sua presa.}

{150}{}{Você pode sair através da porta da armadilha localizada na parte traseira deste edifício.}
{151}{}{Entregue a mensagem ao Modoc.}
{152}{}{Modoc é o sul daqui.}
{153}{}{Sul.}
{154}{}{Não, o outro sul.}
{155}{}{Um visitante - o quão conveniente. Eu tenho contemplado uma maneira de entrar em contato com os surfacers,
 Mas agora eu não tenho que me preocupar com isso - graças à sua chegada atempada. Bem-vindo à casa do
 Escórias.}
{156}{}{Que bom de você retornar. Eu aceito que você entregou a mensagem para o Modoc, então. Como foi
 recebido?}
{157}{}{Eles precisam de tempo para pensar sobre isso.}
{158}{}{Eles têm algumas reservas.}
{159}{}{Quero levar Jonny para casa aos pais.}
{160}{}{Você reconsiderou nos ajudar?}
{161}{}{Preciso fazer algumas perguntas, primeiro.}
{162}{}{A resposta ainda não é.}
{163}{}{Eu decidi ajudá-lo.}
{165}{}{Obrigado por nos ajudar. Você sempre será bem-vindo aqui. Para seus serviços, eu ofereço isso como um
 Recompensa. [Vegeir lhe entrega um rifle de assalto].}
{166}{}{Obrigado por nos ajudar. Você sempre será bem-vindo aqui.}
{167}{}{Seria certo levar Jonny para casa aos pais?}
{168}{}{Por favor, me desculpe pelas circunstâncias desagradáveis   em que nos encontramos. Normalmente, o
 Os protetores teriam tentado assustá-lo. Normalmente, cadeias chocantes e alguns gemidos baixos são
 o suficiente para assustar alguém, mas recentemente eles foram instruídos a trazer os surfacers que eles acham
 para mim.}
{169}{}{Está tudo bem. Eu vou estar indo agora.}
{170}{}{O que você quer comigo?}
{171}{}{Fantasmas?}
{172}{}{Você irá se e quando eu decidir que você pode ir. Não antes.}
{173}{}{Um pedido simples. Precisamos entrar em contato com a cidade ao sudoeste; Eu acredito que é chamado
 "Modoc". Você nos faria esse favor?}
{174}{}{O que eu saio disso?}
{175}{}{Eu tenho muitas perguntas a perguntar antes que eu possua essa missão.}
{176}{}{Justo. Eu não esperaria que alguém aceitasse cegamente tarefas de estranhos sem primeiro
 aprendendo um pouco sobre eles, primeiro. Faça suas perguntas, e eu responderei o melhor que puder.}
{177}{}{Por que você não envia uma das suas próprias pessoas para enviar a mensagem?}
{178}{}{Conte-me sobre o seu povo.}
{179}{}{Quais são suas defesas?}
{180}{}{Ouvi o suficiente. Estou pronto para tomar minha decisão.}
{181}{}{Faça suas perguntas.}
{190}{}{Por que você voltou à superfície?}
{191}{}{Por que o grande fantasma aparece na superfície?}
{192}{}{Qual é o propósito da sua mensagem?}
{194}{}{Desde a Selagem, nós, como povo, mudamos. Poucos podem suportar estar na superfície porque eles
 não estão acostumados a ter um mar negro de nada acima deles. A sensação de cair para cima é tão
 ótimo para eles que eles ficam congelados, agarrando o chão. Mas esse não é o principal motivo. Todos nós
 não suporta a luz brilhante daquilo que você chama o sol; vivendo no subsolo há tanto tempo fez
 nossos olhos também são sensíveis à luz. Não podemos viajar longe da segurança de nossas casas sob o solo.}
{195}{}{Posso fazer mais algumas perguntas?}
{197}{}{Uma vez, há muito tempo, já fomos como os surfacers. Nós também moramos acima do solo, até o mundo
 acima pegou fogo. Nossos antepassados   - que faziam parte de uma milícia secreta - se selaram e os seus
 Famílias aqui embaixo para proteção. Por gerações, aqui em baixo permanecemos, escondidos com segurança dentro de
 o útero da Mãe Terra.}
{200}{}{Nossa população aumentou constantemente desde a selagem. Logo se tornou aparente que poderíamos
 não mais sobreviver aqui sem outros fornecimentos. Então o Selo estava quebrado, e nós novamente olhamos
 para a superfície para a sobrevivência.}
{203}{}{Anos atrás, alguém tentou assumir a nossa fazenda, colhendo colheitas e roubando animais
 eles não tinham direito a. Nós não somos pessoas violentas por natureza, mas algo deve ser feito. Nosso
 A sobrevivência no momento dependia dessas culturas. Foi quando surgimos a idéia fantasma. Smearing
 nós mesmos com fungos brilhantes, fomos capazes de assustar essa pessoa e outros vizinhos curiosos.
 Infelizmente, isso tem sido um pouco muito eficaz. Ultimamente, procuramos entrar em contato com
 as superfícies, mas ninguém mais vem à fazenda por medo dos fantasmas. Por sorte, você deixou cair.}
{206}{}{Suficiente! Não há mais perguntas. Faça sua decisão agora!}
{207}{}{Sinto muito; Eu não posso te ajudar.}
{208}{}{Sim, congratulo-me por levar sua mensagem ao Modoc.}
{209}{}{Lamento ouvir isso. Por favor, considere-se um convidado do Slags. Quando finalmente
 estabelecer contato com os surfacers, você poderá sair. Até então, não tente
 deixa as cavernas - as consequências seriam mais desagradáveis.}
{210}{}{Com a conclusão dos novos sistemas de irrigação, nosso suprimento de alimentos excede as nossas necessidades. Nós
 desejam estabelecer comércio com os surfacers e trocar alimentos excedentes por medicamentos muito necessários.}
{213}{}{Por favor, ilumine-nos com a sua sabedoria.}
{216}{}{Eu sabia que você entenderia. Aqui está uma mensagem que retransmite nosso pedido. Por favor, leve para Modoc
 e entregue-a ao responsável. Volte aqui quando sua tarefa estiver completa. Eu direi aos protetores
 para esperar o seu retorno. Agradecemos por nos fazer este serviço.}
{217}{}{Quão típico dos surfacers. Nunca fazendo nada para ninguém, a menos que haja algum tipo de pessoal
 ganho envolvido. Obviamente, não podemos confiar em uma pessoa como você. Encontraremos alguém para entregar o
 mensagem. Embora não somos pessoas violentas, não tente deixar as cavernas ou se arrependerão.}
{218}{}{Hmm, eu entendo. Tal decisão não pode ser feita de forma leve. Mantenha-me informado sobre os seus
 progresso.}
{219}{}{Então não me incomode mais.}
{220}{}{Sobre o que?}
{221}{}{Eles não confiam em você. Afinal, você mata os transeuntes e coloca os corpos na frente do seu
 Fazenda.}
{222}{}{Querem saber o que aconteceu com o agricultor que vivia aqui.}
{223}{}{Somos pessoas pacíficas e não matamos ninguém. Esses corpos são apenas adereços que fabricamos
 para assustar aqueles que tentam nos roubar. Se você examinar os corpos de perto, você notará que eles
 não são mais que corrompidas e manequins.}
{224}{}{Então, e o pobre Karl? Você sabe, o fazendeiro que vivia em sua fazenda?}
{225}{}{Era o nome dele, Karl? Nós o assustámos da fazenda, nada mais. Eu suponho que ele voltou para casa
 quando descobriu que a fazenda estava assombrada. Os protetores relataram que ele se dirigia para o oeste. Você pode tentar
 procurando por ele dessa maneira.}
{226}{}{Eu vou mantê-lo informado sobre o meu progresso.}
{227}{}{Nós o assustamos da fazenda - nada mais. Eu suponho que ele voltou para casa quando descobriu o
 A fazenda estava assombrada. Os protetores relataram que ele se dirigia para o noroeste. Você pode tentar buscá-lo que
 caminho.}
{231}{}{Vejo que você conheceu Jonny. Encontramos ele vagando na escuridão de um dos nossos túneis mais profundos.
 Ele disse que tinha caído um poço seco por sua casa, e depois foi preso em um túnel por uma caverna. Nós
 tratá-lo como um dos nossos e ele é amado por todos - então você vai entender que eu desconfio de
 confiando-o a um estranho que ainda não se demonstrou como confiável. Vou retornar Jonny
 quando tiver certeza de que ele vai chegar em casa com segurança.}
{232}{}{Você provou sua confiabilidade sem dúvida. Apesar do fato de que vamos sentir falta do pequeno Jonny
 Aqui, arranjamos uma escolta para você e Jonny para voltar ao Modoc agora mesmo.}
{233}{}{Oh garoto! Não é de admirar que você não estivesse assustado com nossos pequenos truques. Você é muito estúpido para ter medo.
 Odeio depender de um indivíduo tão desafiado intelectualmente, mas precisamos de seus serviços.
 Leve essa mensagem para o Modoc. Dê ao líder do Modoc e tente não se perder.}

{300}{}{Eu vou estar indo agora.}
{301}{}{O que você quer comigo?}
{302}{}{Tchau.}
{303}{}{Fantasmas?}

{400}{}{A mensagem foi bem recebida. A cidade de Modoc gostaria de estabelecer comércio com seu povo.}
