#############################################################
#  Message File: ModMain.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{Uma pequena e pequena comunidade agrícola, cercada por vastos campos de culturas mortas ou moribundas.}

# from the vermin hunter seed
{500}{}{Parece que eu matei todos eles.}

# Coin Bag Descriptions
{600}{}{Você vê uma mochila.}
{601}{}{Você vê uma mochila. Someone probably tossed it into the well to make a wish.}
{610}{}{Este é o meu sonho, MEU desejo, e eu estou recuperando. Estou levando todos de volta.}

# KILL THEM ALL
{1000}{}{Mate todos!}
{1001}{}{Morte às escórias!}
{1002}{}{Eu quero vê-los gritar!}
{1003}{}{Vamos buscá-los!}

# fall through floor
{1100}{}{Você cai cerca de 15 pés em uma caverna mal iluminada. Vários equipamentos agrícolas colocam-se perfeitamente
 Armazenado contra a parede distante.}

# blown out of hole
{1200}{}{Você conseguiu sair do buraco a tempo de a explosão sair atrás de você,
 Enviando você voando pelo ar.}
