# QUICK LOOK
{100}{}{Você vê uma atriz pornô.}

# EXAMINES
{150}{}{Você vê uma mulher atraente. Ela parece estar falando consigo mesma.}
{151}{}{Parece que está memorizando suas linhas. Eventualmente, ela desiste, faz um "O" com a boca e começa a balbuciar a cabeça.}
{152}{}{Você vê uma atriz pornô. She coldly ignores you.}

# 1. [MALE, ENCLAVE IS DESTROYED]
{200}{}{Suponho que eu deveria agradecê-lo por salvar o mundo, mas prefiro ter sexo selvagem e apaixonado com você. É aquele
 Tudo certo?}
{201}{}{Ouvi dizer que você é o garoto que chutou o traseiro do Enclave.}
{202}{}{Os indivíduos que chutam o burro dos enclaves do governo malignos me deixam molhada.}
{203}{}{Ouço que os Irmãos estão procurando por você. Eles querem fazer um filme baseado em sua aventura.}

# 2. [FEMALE, ENCLAVE IS DESTROYED]
{210}{}{Suponho que agradeço você por salvar o mundo. Uh ... obrigado.}
{211}{}{Ouvi dizer que você é quem chutou o traseiro do Enclave. Estou impressionado.}
{212}{}{Ouço que os Irmãos estão procurando por você. Eles querem fazer um filme baseado em sua aventura. Uh, can you try and get me a part…?}

# 3. [POWER ARMOR]
{220}{}{Você poderia parar de se enganar naquele levantamento? Estou tentando memorizar minhas linhas.}
{221}{}{Volte para qualquer jogo battlemech que você veio! Este é um RPG!}
{222}{}{Sobre compensar por alguma coisa?}

# 4. [PORN STAR]
{230}{}{Como está pendurado,}
{231}{}{Parecendo bem,}
{232}{}{Ei, querida! Você está cuidando de si mesmo?}
{233}{}{Não estou sendo pago o suficiente.}
{234}{}{Vamos ver ... "Oh Deus" ... "Dê-me ..." Droga! Qual é a próxima linha ?!}
{235}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{236}{}{Vamos ver ... (Script de estudos) ... ele entra, nós fazemos sexo. Consegui.}
{237}{}{O que eu realmente quero fazer é direto.}
{238}{}{Graças a Deus, eles finalmente instalaram essa cabeceira acolchoada.}
{239}{}{Não sei o que os Irmãos da Córsega vêem nela ...}
{240}{}{Eu queria que ela fosse embora.}
{241}{}{Ela engasga meu estilo.}
{242}{}{Oh, ela é um homem-comedor bem, um canibal regular.}
{243}{}{Hmmpph. Lixo de calha.}
{244}{}{Ela é tão talentosa como uma pedra e duas vezes mais feia.}

# 5. [PRIZEFIGHTER]
{250}{}{Como está pendurado,}
{251}{}{Agora há um problema em que quero entrar.}
{252}{}{Procurando por mim?}
{253}{}{Por que você não vem mais frequentemente?}
{254}{}{Tenho uma abertura que você pode preencher.}
{255}{}{Sobre o tempo, um homem real apareceu aqui ...}
{256}{}{Vamos ver ... "Oh Deus" ... "Dê-me ..." Porra! Qual é a próxima linha?}
{257}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{258}{}{Vamos ver ... (Script de estudos) ... ele entra, nós fazemos sexo. Consegui.}
{259}{}{O que eu realmente quero fazer é direto.}
{260}{}{Graças a Deus, eles finalmente instalaram essa cabeceira acolchoada.}

# 6. [MADE MAN]
{265}{}{Como está pendurado,}
{266}{}{Agora há um problema em que quero entrar.}
{267}{}{Procurando por mim?}
{268}{}{Por que você não vem mais frequentemente?}
{269}{}{Tenho uma abertura que você pode preencher.}
{270}{}{Sobre o tempo, um homem real apareceu aqui ...}
{271}{}{Vamos ver ... "Oh Deus" ... "Dê-me ..." Porra! Qual é a próxima linha?}
{272}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{273}{}{Vamos ver ... (Script de estudos) ... ele entra, nós fazemos sexo. Consegui.}
{274}{}{O que eu realmente quero fazer é direto.}
{275}{}{Graças a Deus, eles finalmente instalaram essa cabeceira acolchoada.}

# 7. [NO REP]
{280}{}{Que cheiro é esse?}
{281}{}{Ótimo. Outro golpe de merda tribal.}
{282}{}{Não fale comigo.}
{283}{}{Vamos ver ... "Oh Deus" ... "Dê-me ..." Porra! Qual é a próxima linha?}
{284}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{285}{}{Vamos ver ... (Script de estudos) ... ele entra, nós fazemos sexo. Consegui.}
{286}{}{O que eu realmente quero fazer é direto.}
{287}{}{Graças a Deus, eles finalmente instalaram essa cabeceira acolchoada.}
{288}{}{Eu preferiria isso se você não conversasse quando me falou. Pense em silêncio consigo mesmo, depois fale com a resposta que estou respondendo a você.}
{289}{}{Quem é Você?}
{290}{}{Você é um dos conselheiros?}

# 8. [POWER ARMOR]
{295}{}{Você não é um pouco curto para um soldado de tempestade?}
{296}{}{Aighhhhhh! O que você está tentando fazer? Me dê um ataque cardíaco ?! Saia daqui!}
{297}{}{Em que filme você está tentando? O Dia em que a Terra ficou imóvel? Saia daqui!}
{298}{}{Você poderia parar de se enganar naquele levantamento? Estou tentando memorizar minhas linhas.}
{299}{}{Sobre compensar por alguma coisa?}

# 9. [MALE, PORN STAR]
{305}{}{Como está pendurado,}
{306}{}{Quer me ajudar a ensaiar minhas linhas?}
{307}{}{Quer tomar banho juntos antes da próxima cena?}
{308}{}{Eu amo essa coisa que você faz com sua língua.}
{309}{}{Eles me colocaram como estudante de intercâmbio francês da porta ao lado.}
{310}{}{Você é o mordomo ou o motorista na cena 3?}
{311}{}{Você poderia me configurar com um pequeno Jet?}
{312}{}{Esses rebentos estão esticados ... er, esgotando-me.}
{313}{}{Eu acho que estamos finalmente fazendo uma cena juntos.}
{314}{}{Meus namorados não sabem que eu trabalho aqui. Não é que eu me importo com o que eles pensam.}
{315}{}{Eu não vi os Irmãos ao redor ... tente o escritório, talvez?}
{316}{}{Eu realmente não me importo com o destino, apenas certifique-se de que a câmera recebe o tiro do dinheiro.}
{317}{}{Você é um homem de paixão e mistério. Um homem de luxúria.}
{318}{}{Bem, podemos fazê-lo de qualquer maneira, é o mais confortável para você.}
{319}{}{Estarei pronto para a próxima cena assim que eu tomar um banho longo e quente.}
{320}{}{Sou mãe para todos aqueles que precisam de amor.}
{321}{}{Você vai ser uma estrela. Uma estrela grande, brilhante e brilhante.}
{322}{}{Você é mais erupção do que um vulcão em um dia ruim.}
{323}{}{Adoro isso quando você faz o sotaque espanhol.}
{324}{}{Você está bem, querida.}

# 10. [PORN STAR, FEMALE]
{330}{}{:: Ignora você ::}
{331}{}{Você é a francesa ou a menina russa na próxima cena?}
{332}{}{Gostaria que o controle de natalidade fosse um pouco mais confiável.}
{333}{}{Você roubou meus saltos altos?}
{334}{}{Estou me sentindo um pouco cansado ... tenho algum Jet?}
{335}{}{Hmphhh!}
{336}{}{Não, sinto muito, querido. Não sei onde estão os Irmãos.}
{337}{}{Mostrar a saída?}
{338}{}{Você colocou algum peso?}
{339}{}{Você pode dar uma volta um pouco. Sua ... fragrância ... está me deixando enjoado.}
{340}{}{Ouvi dizer que os Irmãos estão prestes a deixar você ir. Desculpe, é uma pena.}
{341}{}{Acho que se um não-talento como você pode fazê-lo, estou destinado a coisas ainda melhores.}
{342}{}{Sua bunda é tão gorda! Que fofo!}
{343}{}{Eu acho que não é difícil fazê-lo nesta indústria.}
{344}{}{* Eu não disse nada sobre você ser gordo ou feio. Isso deve ter sido outra pessoa.}
{345}{}{Não ouço nenhum dos atores querer trabalhar com você.}
{346}{}{Você não se banhou antes de aparecer?}

# 11. [MALE, PRIZEFIGHTER OR MADE MAN]
{350}{}{Como está pendurado,}
{351}{}{Sair do boxe e da pornografia? A mesma coisa, estágio diferente.}
{352}{}{Quer saltar no ringue comigo, campeão?}
{353}{}{Quer caixa, campeão?}
{354}{}{Cuidado com o Masticador. Ele é um verdadeiro idiota. Ele tentou morder minha orelha uma vez.}
{355}{}{Quer me ajudar a ensaiar minhas linhas?}
{356}{}{Você poderia me configurar com um pequeno Jet?}
{357}{}{Esses rebentos estão esticados ... er, esgotando-me.}
{358}{}{Venha experimentar algumas das coozinas?}
{359}{}{Bom pedaço de ferro lá.}
{360}{}{Meus namorados não sabem que eu trabalho aqui. Não é que eu me importo com o que eles pensam.}
{361}{}{Não estou fazendo nada mais tarde, se você estiver procurando por companhia.}
{362}{}{Você está entrando no negócio? Bem vindo a bordo.}
{363}{}{Boa unidade, você chegou lá.}
{364}{}{Você deveria entrar na pornografia. Você conseguiu o corpo para isso.}
{365}{}{Bom pedaço de ferro lá.}
{366}{}{Não estou fazendo nada mais tarde, se você estiver procurando por companhia.}
{367}{}{Ouvi sobre você. Você é}
{368}{}{Seu chefe manda você para mim?}
{369}{}{Você está tentando extorquem algum sexo fora de mim? Continue.}
{370}{}{O chefe sempre me menciona?}

# 12. [FEMALE, PRIZEFIGHTER OR MADE MAN]
{380}{}{Como é o boxe?}
{381}{}{Cuidado com o Masticador. Ele é um verdadeiro idiota. Ele tentou morder minha orelha uma vez.}
{382}{}{Ame sua roupa. Muito chique.}
{383}{}{Essa roupa parece ótima para você.}
{384}{}{O que você wa ... oh! Senhora! Bem-vindo ao estúdio.}
{385}{}{Meus namorados não sabem que eu trabalho aqui. Não é que eu me importo com o que eles pensam.}
{386}{}{Um ... você não poderia me arrumar com um pequeno Jet, você poderia, senhora?}
{387}{}{Esses rebentos estão esticados ... er, esgotando-me.}
{388}{}{Estou fazendo algo mais tarde? Er ... não, senhora. De modo nenhum.}
{389}{}{Como é trabalhar com o chefe?}
{390}{}{O chefe nunca falou sobre mim?}

# 13. [LEATHER]
{395}{}{Olhe, escravidão e S & M são somente às quartas-feiras. Agora chame seu burro de couro aqui fora.}
{396}{}{Eu duvido seriamente que os Irmãos estejam procurando por outro ato de couro depois do Happia Leather After fiasco.}
{397}{}{Por favor, pare de me incomodar. Estou tentando memorizar essas linhas.}
{398}{}{Pensei que cheirava couro. Eu pensei que era um sofá.}
{399}{}{Olhe, coelho de couro, se você não tiver o seu próprio chicote, os Irmãos nem sequer lhe darão a hora do dia.}

# 14. [MALE, NO REP]
{410}{}{Você? Não, obrigado. Eu poderia ter melhor sexo com meu batom.}
{411}{}{Por que você não se diverte com um apontador de lápis?}
{412}{}{Não tenho tempo para ter uma conversa aborrecida sem sentido com você agora.}
{413}{}{Eu não me importo se você pode martelar um pico de seis polegadas através de uma placa com seu pénis. Agora, perca-se.}
{414}{}{Sexo? Não, eu sou casada, caso contrário eu ainda não faria.}
{415}{}{Não encontro namorados brancos.}
{416}{}{Você não poderia ser melhor do que meu massager de chuveiro.}
{417}{}{Você não parece que você poderia suportar o meu hábito de compra.}
{418}{}{Querida, você não poderia me pagar.}
{419}{}{Só estou à procura do cara certo. Obrigado por manter-me companhia até que ele apareça.}
{420}{}{Você não terá nenhuma sorte entrando na minha calça. Só há espaço para um asshole lá.}
{421}{}{Me desculpe, pensei que fosse bom, mas estava enganado.}
{422}{}{Você? Desculpe, eu nunca serei tão desesperado.}
{423}{}{Eu não vi os Irmãos ao redor ... agora não me incomode. Eu sou uma atriz.}
{424}{}{Por favor ... sem autógrafos.}
{425}{}{Eu realmente quero dirigir.}
{426}{}{Eu estou dançando nos casinos na quinta-feira. Pegue meu ato e traga algumas fichas.}
{427}{}{Você não poderia imaginar o estresse da minha vida.}
{428}{}{Meus namorados não sabem que eu trabalho aqui. Não é que eu me importo com o que eles pensam.}
{429}{}{POR FAVOR deixe de me incomodar. Estou tentando memorizar essas linhas.}
{430}{}{Se você está procurando um emprego, fale com os Irmãos.}
{431}{}{Você é o novo fluffer?}
{432}{}{Você é o novo zelador? Não imagino o que mais você poderia ser.}
{433}{}{Se você é o novo zelador, você poderia começar limpando minha bunda.}
{434}{}{Eu não vi os Irmãos ao redor, garota ... agora não me incomoda. Eu sou uma atriz.}
{435}{}{Por favor, garota ... sem autógrafos.}
{436}{}{PODE, se você se limpar, mais um pouco, você poderia ser um fluffer.}
{437}{}{Desculpe, não, eu não poderia ser lésbica por menos de 200 fichas. Para você, 300.}
{438}{}{Eu estou dançando nos casinos na quinta-feira. Pegue meu ato e traga algumas fichas.}
{439}{}{Menina, você não poderia imaginar o estresse da minha vida.}

{1230}{}{?}
{1231}{}{.}
{1250}{}{?}
{1265}{}{?}
{1305}{}{?}
{1350}{}{?}
{1367}{}{não é você?}
