# 0. QUICK LOOK
{100}{}{Você vê um brahmin mal-humorado.}

# 0. LOOK
{150}{}{Você vê um bravo enorme e mal-humorado. Seu estômago parece distendido, e seus olhos estão injetados no sangue.}
{151}{}{Você vê um bravo enorme e mal-humorado. Seu estômago parece distendido, e seus olhos estão injetados no sangue. It looks very sick. Maybe there's some way to help him out.}

# 2.  FLOAT/CLICK
# success doctor skill
{198}{}{:: Rnnrrrrr? ::}
{199}{}{:: Hrrnnnnr? ::}
# any
{200}{}{Moo}
{201}{}{Mooooooooo}
{202}{}{Moooo}
{203}{}{:: Rnnr ::}
# failed doctor skill
{204}{}{:: Rnnrrrrr !!! ::}
{205}{}{:: Gnnnnrrrr !!! ::}
{206}{}{:: Hrrnnnnr !!! ::}

# 3.  DESCRIPTION: GOOD DOCTOR SKILL
{225}{}{Você retirou algo que foi alojado nos intestinos do braçim.}

# 4.  DESCRIPTION: FAIL DOCTOR ROLL
{235}{}{Há algo hospedado nos intestinos do braçim, mas você não conseguiu segurá-lo.}
