{100}{}{Senhoras e senhores!}
{101}{}{Meninos e Meninas!}
{102}{}{O jogo da noite é trazido para você por ...}

{103}{}{... ROTGUT!}
{104}{}{Quando você absolutamente tem que ter algo para beber e não se importa com o que é ...}
{105}{}{Escolha Rotgut!}

{123}{}{... Gamma Gulp Beer!}
{124}{}{Quando a sua pele não tem aquele "brilho especial" ...}
{125}{}{Escolha Gamma Gulp Beer!}

{143}{}{... a pata do gato!}
{144}{}{Quando você comeu essa coceira que PRECISA raspar ...}
{145}{}{Dirija-se à Pata do gato!}

{163}{}{... New Reno Arms!}
{164}{}{Quando você precisa matar alguém a uma distância segura ...}
{165}{}{Venha para New Reno Arms!}

{106}{}{Nesta esquina, o desafiante, pesando em}
{1106}{}{ libras, novas do deserto e novas para New Reno,}
{2106}{}{!}
{107}{}{E nesta esquina ... pesando em}
{1107}{}{ libras, você CONHECE, você o ama ...}
{2107}{}{!}
{108}{}{Então, sem mais ...}
{109}{}{Vamos receber Reeeeeeeady para BEAT ALGUNS ASS!}

{200}{}{E o wiiiiinnnner é ...}
{201}{}{... por meio de nocaute ...}
{202}{}{... por meio de nocaute técnico ...}
{203}{}{... por meio da desqualificação ...}
{204}{}{... com uma pontuação de}
{205}{}{ para}
{206}{}{...}

{210}{}{!!!}
