{100}{}{Você vê Frenchy.}
{101}{}{Você vê Paine.}
{102}{}{Você vê Sims.}

# 0. MALE (WTG)
{150}{}{Você vê um homem de aparência irregular. Ele está amontoado ao lado do fogo da lixeira, cantando. Ele tem uma boa voz.}
{151}{}{Você vê um cantor. Ele está amontoado ao lado do fogo da lixeira, cantando.}

# 1. CLICK (WTG)
{200}{}{Ei…}
{1200}{}{! O grande herói! como podemos te ajudar? Talvez cante algo especial, hein?}
{1201}{}{. Podemos ajudar?}
{1202}{}{. Ajudá-lo com algum som, campeão?}
{203}{}{Hep, você sabe algo, filho?}
{204}{}{:: Dicas de um chapéu imaginário. :: Hep, você está sabendo alguma coisa, senhora?}
{205}{}{Doo yoo não 'row row boat down stream?'}
{206}{}{Ken ... ken you seng Nine BILLYun bottahs uf cerveja na parede?}
{207}{}{Não, eu vou agora}
{208}{}{Eu ficaria honrado se você fosse. Obrigado pessoal.}
{209}{}{Aqui estão alguns dólares. Você pode jogar outra coisa?}
{210}{}{Não, apenas ouvindo, obrigado.}

# 2. SURE (1)
{300}{}{Tudo bem então ... você ouviu o homem, meninos. Vamos tentar um pouco mais.}
{301}{}{Tudo bem então ... você ouviu a senhora, meninos. Vamos tentar um pouco mais.}
{302}{}{Thanxxx}
{303}{}{Obrigado pessoal.}

# 3. FLOAT (SONG] (WTG)
{400}{}{Oooooh}
{402}{}{Meu bebê não está chegando em casa ...}
{405}{}{Meu bebê fez-me wroooong ...}
{408}{}{Meu bebê foi e me deixou todo o mundo ...}
{409}{}{}

# 4. FLOAT (SONG] (WTG)
{500}{}{Continue}
{501}{}{Experimente a dor}
{502}{}{Cum novamente otimo dia}
{503}{}{}

# 6. FLOAT (SONG] (WTG)
{600}{}{ Garrafas de cerveja no muro ...}
{601}{}{ Garrafas de cerveja ...}
{602}{}{Pegue um ...}
{603}{}{Passar por aí ...}
{605}{}{}

# 7. FLOAT (SONG] (WTG)
{700}{}{Row Row Row}
{701}{}{Yer Boat}
{702}{}{Gire lentamente o fluxo}
{703}{}{Alegremente}
{706}{}{A vida é apenas um sonho...}
{707}{}{}

# 8. FLOAT (HERO SONG] (WTG)
{800}{}{Não precisamos de outro herói ...}
{801}{}{Não precisamos conhecer o caminho de casa ...}
{802}{}{Tudo o que precisamos é mais do que ...}
{803}{}{Metadona}
{804}{}{}

# 5. FLOAT (SONG] (WTG)
{900}{}{Me dê}
{901}{}{Um beijo para construir um sonho}
{902}{}{E minha imaginação}
{903}{}{Vai prosperar nesse beijo}
{904}{}{Mmmmm}
{905}{}{Amada,}
{906}{}{Eu não pergunto mais do que isso:}
{910}{}{Um beijo antes de me deixar}
{912}{}{Alimenta meu coração faminto}
{913}{}{Deixe-me uma coisa antes de nos separarmos ...}
{915}{}{Quando estou sozinho}
{916}{}{Com minhas fantasias}
{917}{}{Eu serei com yoooou}
{918}{}{Tecendo ro-mances}
{919}{}{Fazendo acreditar que são verdadeiras}
{920}{}{Oh, me dê seus lábios por apenas um momento}
{921}{}{E minha imaginação will make that moment live…}
{923}{}{Me dê what you alone can give}
{925}{}{:: trompete da boca ::}
{930}{}{Eu estarei com yoooou}
{933}{}{Ohhhh}
{935}{}{Lábios apenas por um momento}
{937}{}{Vai viver esse momento}
{941}{}{}
