# QUICK LOOK
{100}{}{Você vê um barman.}

# EXAMINE
{150}{}{Você vê um homem de aparência gorda cuidando do bar. Ele acena com a cabeça para você.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ei!}
{201}{}{! Maneira de chutar a bunda do Enclave! Quer uma bebida?}

# 2. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA = SAME CASINO (WTG)
{206}{}{! Estás bem?!}

# 3. FLOAT DIALOGUE: NORMAL (WTG)
{210}{}{Um tiro de rotgut chegando ...}
{211}{}{Isso será três chips ...}
{212}{}{Outro, amigo?}
{213}{}{Aqui está um torniquete se você precisar.}
{214}{}{Não inspire o Jet de uma só vez ... pegue um golpe, uma respiração profunda e depois dê
 Hora de se instalar.}
{215}{}{Você quer dois sacos de ½ onça ou um recipiente?}
{216}{}{O extra do inalador de jato ...}
{217}{}{Deixe-me adivinhar: coloque-o na sua aba?}
{218}{}{Uma arma nuclear nas rochas, começando.}
{219}{}{Nós não deixamos que os clientes tomem Buffout aqui, amigo.}

# 4. CLICK DIALOGUE: THREAT (WTG)
{225}{}{É melhor sair daqui para que você seja servido mais do que você pode
 Lidar com, entender?}
{226}{}{Continue ... saia. Nós não queremos nenhum problema.}
{227}{}{Eles vão te matar se você ficar por aí. Cai fora.}
{228}{}{Estamos todos fora de tudo. Agora continue, git.}

# 5. INTRO (WTG)
{236}{}{! Qual é o seu veneno?}
{237}{}{Heeeey, champ! Qual é o seu veneno?}
{238}{}{Qual é o seu veneno, amigo?}
{239}{}{Qual é seu veneno, querida?}
{240}{}{Poy-sun soa bem}
{241}{}{Poção?! Eu não quero veneno!}
{242}{}{O que há na torneira?}
{243}{}{Que tipo de chems você tem?}
{244}{}{Quem é o velho amigo dessa slot machine?}
{245}{}{Quem é o cara no bar com a faca?}
{246}{}{Nada hoje, obrigado.}

# 6. WHAT'S WITH McGEE? (5)
{250}{}{Oh, você quer dizer o velho McGee? Ele é principalmente inofensivo. Passou perto de uma fortuna em
 Aquela antiga máquina caça-níqueis e não viu um retorno em anos. De qualquer forma ... posso te pegar
 Algo, amigo?}

# 7.  WHAT'S WITH LIL' JESUS? (5)
{260}{}{Esse é o menino pequeno de Jesus, Lil 'Jesus. Ele e aquela faca são tão próximos
 Amigos ... Eu vi ele fazer algumas coisas perversas com isso. De qualquer forma, posso obter
 Você é algo, amigo?}
