# QUICK LOOK
{100}{}{Você vê um dos guarda-costas de Bishop.}

# EXAMINE
{150}{}{Você vê um homem de aparência acidentada vestido com uma armadura de couro.Numerosas cicatrizes e feridas de bala
 cobre seu corpo.}
{151}{}{Você vê um dos guarda-costas de Bishop.He is scanning the area and fingering his weapon.}

# 1.FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ei!}
{201}{}{!Maneira de chutar a bunda do Enclave!}

# 2.FLOAT DIALOGUE: POWER ARMOR (WTG)
{205}{}{Como você vai ao banheiro com essa coisa?}

# 3.FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [ARMED] (WTG)
{210}{}{Bishop esperando você,}
{211}{}{? Vá em frente.Apenas não acertei aquela arma à sua volta.}

# 4.FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [SNEAK] (WTG)
{215}{}{Uh, olha ...Bishop está esperando você, certo,}
{216}{}{? Vá em frente.Desligue a maldição, no entanto.}

# 5.FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [NORMAL] (WTG)
{221}{}{? Vá em frente.}

# 6.FLOAT/CLICK DIALOGUE: MADE MAN, FA=NOT BISHOP (WTG)
{225}{}{Você simplesmente entrou no lugar ERRADO, dipshit.}
{226}{}{Bem, olhe para as bolas de bronze neste filho da puta ...pegue, garoto, antes de matá-lo.}
{227}{}{Este cara está pedindo problemas ...}
{228}{}{É melhor você sair,}
{229}{}{Bem, se não for}
{230}{}{Eu ouço o}
{231}{}{Não pensou em membros da família}
{232}{}{Você entrou no lugar ERRADO, cadela.}
{233}{}{Bem, olhe o swagger nesta cadela ...}
{234}{}{Get, menina.Antes de matá-lo.}
{235}{}{Esta cadela está pedindo problemas ...}
{236}{}{Eu ouço o}

# 8.FLOAT DIALOGUE: MALE, PRIZEFIGHTER [ARMED] (WTG)
{245}{}{Você é campeão.Não há armas aqui, 'kay?}
{246}{}{Você é campeão!Coloque essa arma longe.}
{247}{}{Ei,}

# 9.FLOAT DIALOGUE: MALE, PRIZEFIGHTER AND MALE PORN STAR [SNEAK] (WTG)
{255}{}{Por que você está se esgueirando?}
{256}{}{Você está tentando evitar seus fãs?}
{257}{}{Por que todo o segredo?}

# 10.FLOAT DIALOGUE: MALE/FEMALE, PRIZEFIGHTER (WTG)
{265}{}{Eu,}
{266}{}{Eu,}

# 11.FLOAT DIALOGUE: MALE/FEMALE, PORN STAR [ARMED] (WTG)
{275}{}{Eu,lover-boy.No weapons in here, 'kay?}
{276}{}{Ei,}
{277}{}{Eu,}
{278}{}{Querida, você não pode estar carregando armas aqui.Heh-heh ...Você é bastante mortal como está.}
{279}{}{Ei,}

# 13.FLOAT DIALOGUE: [PORN STAR, FEMALE] [SNEAK] (WTG)
{285}{}{Querida, com um corpo como esse, você não poderá se esgueirar em qualquer lugar.}

# 14.FLOAT DIALOGUE: [PORN STAR] (WTG)
{290}{}{Adoro os filmes,}
{291}{}{Te amei em Great Balls for Hire.}
{292}{}{Te amei com boa vontade de ferrão.}
{293}{}{Sou um grande fã do seu trabalho em Pokeahotass.}
{294}{}{:: assobios ::}

# 16.FLOAT DIALOGUE: SLAVER [ARMED] (WTG)
{300}{}{Você está procurando preencher uma sepultura no Golgotha, escravidão? Coloque essa coisa longe.}
{301}{}{Coloque essa arma fora, escravidão, ou eu vou usar você para a prática do alvo.}
{302}{}{Slaver, é melhor você proteger essa arma agora.}

# 17.FLOAT DIALOGUE: SLAVER [SNEAK] (WTG)
{305}{}{Você está procurando preencher uma sepultura no Golgotha, escravidão? Pare de se esgueirar.}
{306}{}{Pare de se esgueirar, escravidão, ou eu vou usar você para a prática do alvo.}
{307}{}{Talvez seja melhor você voltar para a escola ninja, escrava - agora pare de se esgueirar.}
{308}{}{Slaver, é melhor você parar de se esgueirar com a merda agora.}

# 18.FLOAT DIALOGUE: MALE/FEMALE, NO REP [ARMED] (WTG)
{315}{}{Você está procurando preencher uma sepultura no Gólgota, tribal? Coloque essa coisa longe.}
{316}{}{Coloque essa arma longe, tribal, ou eu vou usar você para a prática do alvo.}
{317}{}{Tribal, é melhor você proteger essa arma agora.}

# 19.FLOAT DIALOGUE: MALE/FEMALE, NO REP [SNEAK] (WTG)
{325}{}{Você está procurando preencher uma sepultura no Gólgota, tribal? Pare de se esgueirar.}
{326}{}{Pare de se esgueirar, tribal, ou eu vou usar você para a prática do alvo.}
{327}{}{Talvez seja melhor você voltar para a escola ninja, tribal - agora pare de se esgueirar.}
{328}{}{Tribal, é melhor você parar de se esconder por causa da merda agora.}

# 20.FLOAT DIALOGUE: COMPANION: ROBOBRAIN (WTG)
{335}{}{Retire esse robô aqui.Agora.}
{336}{}{Retire esse robô antes de transformá-lo em um fogo de lixeira.}
{337}{}{Esse robô vai ser peças de reposição se ficar.}

# 21.FLOAT DIALOGUE: COMPANION: MARCUS (WTG)
{345}{}{Eu * pensei * Eu cheirei mutante.É melhor você tirar seu traseiro amarelo aqui.Agora.}
{346}{}{Você e seu amigo mutante que procuram disparar? Cai fora.}
{347}{}{Esse mutante melhor sair aqui agora, ou vamos montar a cabeça em uma parede.}

# 22.FLOAT DIALOGUE: COMPANION: LENNY (WTG)
{355}{}{Eu * pensei * Eu cheirei algo apodrecendo.Pegue esse ghoul fora daqui.}
{356}{}{Pegue esse ghoul fedido aqui fora.Agora.}
{357}{}{Esse ghoul não está fora de aqui em um minuto, ele vai ser mais morto do que ele já é.}

# 23.FLOAT DIALOGUE: MALE/FEMALE, NO REP (WTG)
{365}{}{Pegue a luta na noite passada?}
{366}{}{Estou batendo no bar depois do trabalho.}

# 24.CLICK DIALOGUE: MALE/FEMALE, MADE MAN: BISHOP, BISHOP = DEAD (WTG)
{370}{}{Você pode subir se quiser.O bispo foi atacado, então você também pode usar a piscina.}

# 25.INTRO (WTG)
{375}{}{O que você quer, amigo? Faça isso rápido.}
{376}{}{O que você quer, querida? Faça isso rápido.}
{377}{}{Você novamente.Que diabos você quer agora?}
{378}{}{Eu quero paz mundial}
{379}{}{Eu quero subir de escada}
{380}{}{Hoo Yoo}
{381}{}{Afastar-se}
{382}{}{Qual é a escada?}
{383}{}{Estou aqui para ver o Sr.Bishop.}
{384}{}{Estou aqui para ver o Sr.Bishop.I have a suitcase for him from Mr.Moore.}
{385}{}{Desculpe, parece ter tomado uma curva errada.Eu irei agora.}

# 26.TRY TO GO UPSTAIRS (WTG)
{390}{}{Você tem algum negócio no andar de cima, amigo?}
{391}{}{Você tem algum negócio no andar de cima, querido?}

# 27. RETARD (25, 26, 29, 30, 32, 33)
{405}{}{Cara, você é um filho de puta estúpido, não é?}
{406}{}{Cara, você é uma cadela estúpida, não é?}
{407}{}{Olhe, saia daqui antes de bater o resto de seus cérebros para você.}
{408}{}{ME QUERO O MUNDO PAZ ME QUER A PAZ DO MUNDO}
{409}{}{ME DIMO QUE QUERO GO UP STAIRS}
{410}{}{HOO YOO}
{411}{}{Shamble off}
{412}{}{Deixe-me passar.}
{414}{}{Tudo certo.Estou indo embora.}

# 28.LOUD RETARD (27)
{420}{}{Dipshit, você ganhou um bilhete para um mundo de dor.}
{421}{}{Bitch, você ganhou um bilhete para um mundo de dores.}
{422}{}{YOO ONE WHO GET HURT}
{423}{}{ só quer ficar sozinho, mas o MUNDO dói}
{424}{}{ assim}
{425}{}{ SMASH PUNY HUMANS}
{426}{}{Gritar e mergulhar para cobrir}
{427}{}{Vá em silêncio, prepare-se e prepare-se para fazer algum dano.}
{428}{}{Você quer alguns desses, meninos ?!VOCÊ QUER ALGUM?!Então venha receber alguns, você patético SONS OF
 POUCO --}

# 29.WHAT'S UP THOSE STAIRS? (25, 26)
{435}{}{Se você não sabe, então você NÃO PRECISA saber.Agora, sopre.}

# 30. BISHOP DEAD (25, 26, 27, 29)
{445}{}{Bem, isso é muito ruim assim, o Bispo levou a estrada para o céu não muito tempo atrás.Agora vença.}
{446}{}{Você é surdo? John Friggin 'Bishop é friggin' DEAD, awright? Agora saia daqui antes de se juntar a ele.}
{447}{}{Olha, eu preciso subir as escadas, só por um segundo.}
{448}{}{Ok, vou embora.}

# 31.I'M HERE TO SEE BISHOP (25, 26, 27)
{455}{}{Não, conheço o cronograma do Sr.Bishop e você não está nisso.}
{456}{}{Ele está me esperando.Diga-lhe que estou aqui.}
{458}{}{Tudo bem então.Adeus.}

# 32.HE'S EXPECTING ME.(31)
{465}{}{Bem, amigo.Qual é o seu nome? Eu vou verificar com o chefe.}
{466}{}{Muito bem, hon.Qual é o seu nome? Eu vou verificar com o chefe.}
{467}{}{Eu estou}
{468}{}{.}
{469}{}{Você não precisa do meu nome.Apenas deixe-me vê-lo.}
{471}{}{Esqueça.Você não precisa verificar ...Eu irei.}

# 33.HE'S EXPECTING ME (REFUSE) (32)
{475}{}{(Os passos de guarda por um momento, abre um painel de uma das paredes e sussurra algo.Ele espera por um minuto, escuta, depois volta para você.)}
{476}{}{Ele não conhece você.Piss off, amigo.Você está perdendo nosso tempo.}
{477}{}{Ele não conhece você.Piss off, hon.Você está perdendo nosso tempo.}
{478}{}{Deixe-me vê-lo.Agora.}
{479}{}{Diga-lhe que tenho uma mala para ele ...do Sr.Moore.}
{480}{}{Esqueça, então.}

# 34.HE'S EXPECTING ME (AGREE) (25, 26, 27, 28, 29, 33)
{490}{}{(Os passos de guarda por um momento, abre um painel de uma das paredes e sussurra algo.
 Ele espera por um minuto, escuta, depois volta para você e encolhe os ombros.) Ele diz que você pode seguir em frente.}
{491}{}{Tudo certo.}

# 35.MADE MAN: BISHOP (WTG)
{495}{}{Eu,}
{496}{}{!}
{497}{}{Sr.Bishop 'xpecting you?}
{498}{}{Sim.Posso seguir em frente? Nós temos negócios para discutir.}
{499}{}{Não, agora não.Tome cuidado, pessoal.}

# 36.MADE MAN (35)
{505}{}{Claro, continue,}
{506}{}{.}
{507}{}{Da próxima vez, nem se preocupe perguntando ... apenas siga em frente.}
{508}{}{Obrigado.}

# END LINES
{1228}{}{.Now.}
{1229}{}{.Ain't your family gonna be missing you?}
{1230}{}{ family is a bunch of pussies.What you think about that?}
{1231}{}{ tive tempo de fazer muito mais do que beijar o traseiro dos seus chefes.}
{1236}{}{ family is a bunch of pussies.Now I see it's true.}
{1247}{}{!You can't be showing weapons in here, awright?}
{1265}{}{.You taking care of yourself?}
{1266}{}{.What's up?}
{1276}{}{!You can't be showing weapons in here, awright?}
{1277}{}{!Put that weapon away.}
{1279}{}{!You can show your tits, but you can't show weapons in here, awright?}
{1290}{}{!}
