# 0. QUICK LOOK
{100}{}{Você vê um guarda-costas dos irmãos da Córsega.}

# 1. LOOK (WTG)
{150}{}{Você vê uma mulher de aparência dura com um mohawk verde. Ela está embalando sua sub-metralhadora como um bebê.}
{151}{}{Você vê um guarda-costas dos irmãos da Córsega.}


# 2. FLOAT (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{200}{}{Salvo o mundo, hein? Big frickin 'deal.}
{201}{}{Oh, gee, você é meu herói. Agora PISS OFF.}

# 3. What, you too good for me or what?
{300}{}{Hullow?}
{301}{}{Você sabe que esta linda loira ...}
{302}{}{O que, você também é bom para falar comigo?}
{303}{}{Diga algo. Qualquer coisa!}

# 4. Prick
{400}{}{Prick.}
{401}{}{Jerkhole.}
{402}{}{Idiota.}
{403}{}{Sim, continue caminhando, idiota.}
{404}{}{Eu espero que eu nunca tenha o "prazer" de conhecer esse título novamente.}
{405}{}{Essa garota precisa de menta de respiração.}
{406}{}{Cadela.}

# 5. Nothing
{500}{}{Ela simplesmente olha para você em branco.}
{501}{}{Ela aparentemente não tem nada a dizer.}

# 6. Porn Star
{600}{}{Eu realmente gostaria de levá-lo ao jogo de bola.}
{601}{}{Você pode me ligar com ele algum dia?}
{602}{}{Hmmm ...}
{603}{}{Você pode me ligar com ela algum dia?}
{604}{}{Gostaria muito de ir com ela.}
{605}{}{Eu tenho a * maior * paixão por ela, mas estou com muito medo de dizer qualquer coisa.}
