# QUICK LOOK
{100}{}{Você vê o Sr. Bishop.}

# EXAMINES
{150}{}{Você vê um homem de meia idade de aparência poderosa.}
{151}{}{Você vê o Sr. Bishop. He looks grim.}

# 1. CLICK: MADE MAN, ANY OTHER FAMILY (2, 3, 4, 9, 11, 13, 14, 16, 17, 18, 22, 24, 25, 26, 27, 28, 29, 31, 33, 35, 36, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 51, 57, 59, 62, 63)
{200}{}{Você conseguiu algumas bolas aqui.}
{201}{}{Você tem algumas bolas.}
{202}{}{Por que você não pegou um sinal em seu peito que diz: 'boba mãe muda?'}
{203}{}{Coma, você}
{204}{}{ Desgraçado.}
{205}{}{Coma, vocêstupid son of a bitch.}
{206}{}{Coma a cabeça, puta.}
{207}{}{Eu não gosto muito de chumbo}
{208}{}{Shamble off}
{209}{}{Se é isso que você quer esculpido em sua lápide, então seja ...}
{210}{}{Pequena escolha das últimas palavras.}
{211}{}{(Executar por isso.)}

# 2. MAIN DIALOGUE: NORMAL (WTG)
{220}{}{O que? Quem é você e o que o INFERNO quer?}
{221}{}{Eu}
{222}{}{.}
{223}{}{EuWhoo?}
{224}{}{Afastar-se}
{225}{}{Eu sou um guerreiro em uma missão sagrada para recuperar o Kit de Criação do Jardim do Éden. Você sabe onde posso encontrá-lo?}
{226}{}{Estou procurando um Kit de Criação do Jardim do Éden. Pode me ajudar?}
{227}{}{Estou à procura de um lugar chamado Vault 13. Você já ouviu falar disso?}
{228}{}{Eu pensei que você poderia ter algum trabalho mais para mim.}
{229}{}{Desculpe - sala errada.}

# 3. BOYS SAID YOU GOT A BRIEFCASE FOR ME (WTG)
{240}{}{(Estudos você.) Mesmo sob todo o que se levanta, você ainda parece um deles tribal ... (Snorts.) Os meninos disseram que você conseguiu um
 Pasta para mim. De um "conhecimento" mútuo. Vamos ver isso.}
{241}{}{Aqui está.}
{242}{}{Uh ... coisa engraçada, que ... parece que, em algum lugar da porta até aqui, eu me perdi.}
{243}{}{Na verdade, eu gostaria de me apossar disso. Eu vou trazê-lo de volta em um tempo.}

# 4. HERE YOU GO. . . (3)
{250}{}{(Abre a maleta, verifica o conteúdo, o snaps case é fechado). É de Moore, tudo bem. "Cerrou esta nota aqui diz
 Não se pode confiar mais do que uma cobra pode merda. Você entrou na sala WRONG, tribal.}
{251}{}{(Abre a maleta, verifica o conteúdo, o snaps case é fechado). É de Moore, tudo bem. Diz você verificar, tribal. Por sorte
 Para você ... (Smiles.) ... você vem aqui com um representante ruim, e você está pedindo uma rápida viagem ao céu.}
{252}{}{Talvez sim, mas eu serei o único a sair.}
{253}{}{Bem, entreguei o caso como Moore perguntou ... agora sobre o pagamento ...?}
{254}{}{Estou curioso. O que há na maleta?}
{255}{}{Contente, tudo está em ordem ... olha, eu tenho que ir.}

# 5. HERE YOU GO. . . (4)
{265}{}{Segure seus cavalos, tribal ... nós ainda não discutimos o pagamento.}
{266}{}{Segure seus cavalos, tribal ... Tenho algumas perguntas para você primeiro.}
{267}{}{(Estudos você.) Então ... de onde você conhece Moore? Ele tenta jogar política entre as tribos agora? Ha! Aquele garoto perdeu
 Seu chamado.}
{268}{}{Eu o conheci em Vault City, espalhando a palavra. Eu ofereci ajudá-lo a entregar esta maleta para você.}
{269}{}{Acabei de atravessá-lo durante minhas viagens. Eu ofereci ajudá-lo a entregar esta maleta para você.}

# 6. HERE YOU GO. . . (5)
{275}{}{Heh ... maldito humano de você ... para toda sua pregação, ol 'Tomcat Moore não consegue sair de sua caixa de sabão o suficiente para realmente
 Para fazer qualquer trabalho de mão-de-obra. Heh ... ainda, isso não o torna diferente de qualquer outro garoto NCR.}
{276}{}{Ele prega muito. Ainda assim, ele parece ter muito sentido.}
{277}{}{Ele tem um certo ... caminho com palavras.}
{278}{}{Sim, bem, em algum momento o trabalho tem que ser feito, e eles me chamam para garantir que as coisas sejam entregues ... como
 Essa pasta.}

# 7. HERE YOU GO. . . (6)
{285}{}{(Para si mesmo). Claro, ser capaz de chicotear uma multidão em um frenesi não é muito ruim se você estiver indo para a política ...
 (Estuda você com desconfiança.) Você também não é NCR, você está? Tomcat é sobre o único deles que eu posso suportar o momento.}
{286}{}{Sim, também sou da NCR. Não é o melhor, mas é uma vida. Eu sou praticamente um agente gratuito.}
{287}{}{Não, sou apenas um viajante. Concordei em ajudar Moore porque precisava de trabalho.}

# 8. HERE YOU GO. . . (7)
{295}{}{(Nods no caso.) Bem, esta pasta valia a pena. Uma pequena fatia de Vault City, algumas das preciosas
 Tech, essa cadela gelada com a qual Lynette não quer se separar ... mas oi, tribal, ainda não te recebi. Aqui está o seu corte.}
{296}{}{Diga ... Eu não tenho outros trabalhos alinhados no momento. Você tem algum trabalho para mim?}
{297}{}{Sim ... obrigado. Olha, eu tenho que ir.}

# 9. I'VE GOT TO GO . . . NO JOBS (8, 34, 49)
{305}{}{Não ... Eu não tenho mais trabalho para você ... mas oi, obrigado por tudo o que você fez.}
{306}{}{Não ... Não tenho nada para você. As mortes de Lotta na NCR recentemente tornaram minha vida um pouco mais fácil ... mas oi, obrigado
 Para a entrega.}
{307}{}{(Nods na saída.) Agora você continua e sai daqui. Eu tenho outros negócios para atender.}
{308}{}{Entrego esse estúpido caso até a cidade de Vault, então você me tira a escova? Eu
 Acho que vou tirar o REST do meu pagamento do seu cofre.}
{309}{}{Não, eu não acho que vou sair ainda. Você ainda tem negócios comigo ... homem morto.}
{310}{}{Tudo bem então. Estou indo embora.}

# 10. I'VE GOT TO GO . . . JOB OFFER (8)
{315}{}{Aguarde um minuto, tribal ... (Smiles, maleta de toques.) Ol 'Tomcat diz que você é um jogador da equipe. Preciso de pessoas assim.
 Eu tenho um emprego para você, se você estiver interessado.}
{316}{}{Estou ouvindo.}
{317}{}{Não, eu realmente tenho que estar em frente.}

# 11. MISSION ONE (8, 10, 33, 59, 63)
{325}{}{(Chega-te por um momento, depois acena com a cabeça.) Sim ... consegui um emprego para ti.}
{326}{}{Eu tenho esse ... "problema" no sul da NCR. Este cara, Westin, tem uma grande boca que precisa ser fechada ... permanentemente.
 Meio dinheiro grande e fácil.}
{327}{}{Sem problemas. O Westin é tão bom como morto.}
{328}{}{Não interessado. Encontre outra pessoa.}

# 12. WESTIN: (11)
{335}{}{Aguente. Não acabei dizendo nada ainda. Eu quero esse morto morto, mas não pode parecer que ele foi atendido. Não coloque uma bala no crânio, não apuntela na morte, não faça nada do que cheire de um golpe.}
{336}{}{O que? Como  --}
{337}{}{Isso vai custar ex -}
{338}{}{Porque...?}

# 13. WESTIN: (12)
{345}{}{Porque é assim que tem que ser feito. Você irrita alguém lá embaixo, faça-os pensar que eu TENGA QUALQUER COISA
 Faça com aquele filho da puta chutando o balde, e eu me certificarei de que ninguém possa identificar seu cadáver.}
{346}{}{Como diabos eu deveria bater em alguém e NÃO fazê-lo parecer assassinato?}
{347}{}{Esqueça ... não meu estilo. Encontre outra pessoa. Estou fora daqui.}

# 14. HOW THE HELL AM I SUPPOSED . . . (13, 17, 18, 19, 23, 24, 25, 26, 27, 28, 29)
{355}{}{Esse é o seu problema, tribal, não o meu. Faça algum mumbo-jumbo, misture algumas plantas venenosas e coloque-a na bebida dele,
 Bloqueá-lo enquanto dormia, empurrá-lo para fora de um prédio, não me importo. Só assim não parece um sucesso.}
{356}{}{Tudo bem ... e mais uma vez no caso de eu não ser criado CRISTAL claro: tem que parecer um acidente ou
 não é bom.}
{357}{}{Feito. Eu voltarei depois que Westin teve seu ... "acidente".}
{358}{}{Eu te ouvi pela primeira vez. Eu voltarei depois que Westin teve seu ... "acidente".}
{359}{}{Se você não quiser que eu coloque uma bala no crânio, isso aumentará um pouco o preço.}
{360}{}{Você quer que eu pareça um acidente, hein? Então eu preciso saber mais sobre este "Westin".}
{361}{}{Eu não sou a pessoa para esse trabalho. Esqueça.}

# 15. DONE. I'LL BE BACK . . . (14)
{370}{}{Tudo bem então. Espero ouvir de você em breve. E lembre-se, tribal, você não me conhece e nunca tivemos isso
 conversação. A palavra sai, e eu vou te derrubar.}
{371}{}{Não se preocupe comigo, bispo. Você apenas certifica-se de que você conseguiu esse dinheiro esperando por mim quando eu voltei.}
{372}{}{Sem problemas. Eu voltarei.}

# 16. WELL, IF YOU DON'T WANT ME TO PUT A BULLET . . . (14)
{380}{}{Já estou pagando mais do que o valor da sua vida, tribal. Não me empurre.}
{381}{}{Mil ou nada. Este é um trabalho especial, e eu recebi despesas. Eu tenho que chegar à NCR, organizar o "acidente"
 E provavelmente terá que gastar mais dinheiro por alguns itens especiais "acidentais" para fazer as coisas. assim
 Não me aperte, tudo bem?}
{382}{}{Torná-lo um milhar, e você conseguiu um assassino.}
{383}{}{750 fichas para cobrir isso.}
{384}{}{500 fichas, então. Westin é um homem morto.}
{385}{}{Então esquece. Pegue outra pessoa. Estou fora daqui.}

# 17. NEGOTIATED UP, BAD DEAL (16)
{390}{}{Você quer o que? Tribal, você tem sorte em obter o quanto você está recebendo.}
{391}{}{Olhe, última vez: vai custar-lhe mais de 500 fichas.}
{393}{}{Então esquece. Encontre outra pessoa. Estou fora daqui.}

# 18. NEGOTIATED UP, DONE (16)
{400}{}{Tudo bem então! Você melhor entrega, tribal. Você não, se você bagunçar isso ou se NENHUM ouvir sobre este negócio, e
 Eu vou colocar uma ferida em seu corpo para cada chip que você pediu.}
{401}{}{Sem problemas. Westin é um homem morto.}
{402}{}{É assim? Bem, então encontre alguém para resolver seu problema. Estou fora daqui.}

# 22. YOU WANT ME TO MAKE IT LOOK LIKE AN ACCIDENT, THEN I'LL NEED TO KNOW MORE . . . (14, 23-29)
{410}{}{Hmmmm. Tudo bem, justo o suficiente ... o que você precisa saber?}
{411}{}{Gostar...?}
{412}{}{Onde posso encontrar esse cara? Eu não quero ter que caçar seu traseiro quando eu chegar à NCR.}
{413}{}{Esse cara conseguiu parentes, alguma família? Alguma testemunha com a qual eu tenho que me preocupar?}
{414}{}{Como é a saúde desse tipo? Alguma doença?}
{416}{}{O que esse Westin FAZ? Qual é o horário de seu trabalho?}
{417}{}{Não quero esse trabalho. Encontre outra pessoa.}

# 23. YOU WANT ME TO MAKE IT LOOK LIKE AN ACCIDENT, THEN I'LL NEED TO KNOW MORE . . . (22)
{425}{}{Ele tem uma fazenda na NCR. Siga o cheiro brahmin, e você deve encontrá-lo sem muito problema.}
{426}{}{Eu tive algumas outras perguntas sobre Westin ...}
{428}{}{Quanto mais eu ouço sobre isso, menos eu gosto disso. Esqueça isso.}

# 24. ANY KIN, ANY FAMILY . . . (22)
{435}{}{Sem filhos, sem esposa, sem família para falar. Pode haver algumas mãos no rancho, mas não devem ser demais.}
{437}{}{Espere um minuto ... "as mãos do rancho?" Eles estão ARMADOS? E quantos são ALGUNS?}
{438}{}{Tudo bem, é bom o suficiente para continuar. Westin é um homem morto.}

# 25. ANY KIN, ANY FAMILY . . . (22, 24)
{445}{}{Provavelmente armado ... e quanto a uma equipe de funcionários, eu não recebi uma. Eu sei que ele tem trabalhadores, e provavelmente há mais
 Do que um. Lidar com eles é SEU problema, tribal.}
{446}{}{Great, that's really helpful. Look, Eu tive algumas outras perguntas sobre Westin ...}
{447}{}{Bem, é o suficiente para continuar. Westin é um homem morto.}

# 26. ANY KIN, ANY FAMILY . . . (22)
{455}{}{Bem ... rumor, ele não sai muito. Eu pensei que ouvi algo sobre ele ter um coração ruim, então ele não
 Exerça-se muito. (Snorts.) Ou isso, ou ele não gosta do sol.}
{456}{}{Hmmmm. Eu tive algumas outras perguntas sobre Westin ...}
{457}{}{Problemas cardíacos, hein? Ele tem um médico? Ele toma alguma medicação para isso?}

# 27. TAKE ANY MEDICATION . . . (26)
{465}{}{(Sorrisos.) Eu gosto do jeito que você pensa, tribal ... bem, eu não sei se ele leva algum chems para o coração dele, mas eu sei que ele teria
 Para ser bastante cuidadoso com o que ele levou com aquele coração dele.}

# 28. WHAT DOES HE DO? . . . (22)
{475}{}{(Frowns.) Ele é um fazendeiro brahmin. Um pastor animal. Assim?}
{476}{}{All right then. Eu tive algumas outras perguntas sobre Westin ...}
{477}{}{Não, ele é algo mais. Ou então, não estaríamos tendo essa conversa.}

# 29. WHAT DOES HE DO? . . . (WTG)
{485}{}{(Glares para você.) Ele também é conselheiro no congresso NCR. A SCARE você, tribal? Não deveria. Faça seu trabalho, e
 Você não tem nada com que se preocupar. Foda-se, e Westin será o mínimo de suas preocupações.}
{488}{}{Um "conselheiro no Congresso NCR"? Aperte isso. Encontre alguém mais ... alguém com um desejo de morte.}

# 30. NO WAY, BISHOP. I'M OUTTA HERE . . . (10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48)
{495}{}{Tudo bem então. Não seja um estranho agora ... Sempre obtive trabalho para alguém que obtém resultados.}
{496}{}{Eu vou manter isso em mente. Adeus.}

# 31. YOU DONE THE HIT YET? . . . (WTG)
{500}{}{Você já fez Westin?}
{501}{}{Você DAMN, melhor, tenha boas notícias para mim. Westin está morto ou não?}
{502}{}{Tribal, minha paciência está desgastando. Você fez o maldito trabalho ou não?}
{503}{}{Na verdade ... coisa engraçada, você pode apreciar a ironia ... Eu tive uma contra-oferta. Deixe-me mostrar o que é.}
{504}{}{Westin teve um ... acidente, sim. Verdadeira vergonha, um homem como esse morrendo tão de repente. Agora, sobre o dinheiro que você me deve ...}
{505}{}{Ainda não. Eu tenho algumas coisas para cuidar primeiro.}
{507}{}{Voltei para lhe dizer que não vou fazer o trabalho. Esqueça.}

# 32. FUCKED UP WESTIN (WTG)
{515}{}{Seu estúpido bastardo ...}
{516}{}{Sua cadela idiota ...}
{517}{}{Você conseguiu algumas bolas voltando aqui depois de fucking do jeito que você fez na NCR. Por que você não pegou um sinal no Westin?
 Dizendo: "contrato hit?" Yer vai morrer muito.}
{519}{}{Escolha pobre das últimas palavras, Bispo ...}

# 33. YOU RECONSIDER? (WTG)
{525}{}{Ei, tribal. Esse trabalho ainda está aberto ... se você quiser. O pagamento é bom. Estás interessado?}

# 34. SUCESSFULLY KILL WESTIN (31)
{536}{}{Aqui está o seu pagamento.}
{537}{}{Mais um trabalho para mim?}
{538}{}{Isso resolve coisas entre você e eu agora? Se assim for, eu irei.}
{539}{}{Tudo bem então. Prazer em fazer negócios com você.}

# 35. I'VE GOT TO GO . . . JOB OFFER (34)
{545}{}{Aguarde um minuto, tribal ... você fez o bem. Recebi outro trabalho para você, se você estiver interessado.}
{547}{}{Não, obrigado. Eu não estou interessado.}

# 36. MISSION 2 (8, 10, 33, 34, 35, 59, 63)
{550}{}{(Checou por um momento, depois acena com a cabeça).}
{551}{}{Sim ... consegui um emprego para você.}
{552}{}{Eu tenho outro ... "problema" na NCR. Pregue um, outro aparece. O nome desse homem morto é Carlson. Ele não sabe que ele é
 Morto ainda.}
{553}{}{Eu tenho um ... "problema" no sul da NCR. O nome do homem morto é Carlson. Ele não sabe que ele está morto ainda.}
{554}{}{Faça acontecer, e vale 500 para você.}
{555}{}{Sem problemas. Este Carlson é tão bom como morto.}
{556}{}{OUTRO assassinato?}

# 37. ANOTHER FUCKING MURDER? (36)
{565}{}{Não é assassinato. O assassinato é uma palavra feia. Isso é um negócio. Política, se você quiser. Ambas as instituições respeitáveis.
 Você quer o trabalho ou o quê?}

# 39. CARLSON 2: (36, 37, 40, 41, 43, 44, 45, 46, 47)
{575}{}{Mais uma coisa: eu não me importo se você entrar lá armas ardendo com ol 'Carlson. Ele é obrigado a ser escondido lá linda
 Apertado após Westin comprá-lo, então não precisa ser bonito, só precisa ser FEITO, capiche?}
{576}{}{Eu não me importo se você entrar lá armas ardendo com ol 'Carlson. Ele está escondido em sua mansão apertado, então não precisa
 Para ser lindo, só precisa ser FEITO, capiche?}
{577}{}{E mais uma vez no caso de eu não me deixar claro: não me importo COMO você golpeia esse filho da puta enquanto ele é
 Morto e permanece assim.}
{578}{}{Entendido. Estou com isso.}
{579}{}{Tudo certo ... Eu te escutei pela primeira vez. Estou com isso.}
{580}{}{Se é assim que deve ser ... agora vamos falar sobre esse preço.}
{581}{}{Eu vou precisar de alguma informação sobre esse cara de Carlson antes de fazer qualquer coisa.}
{582}{}{Ah, então, AGORA, está certo entrar com armas ardentes? Isso teria sido útil com Westin. Esqueça isso.}
{583}{}{Não interessado. Encontre outra pessoa.}

# 40. WE STILL NEED TO NEGOTIATE CARLSON PRICE. (39)
{590}{}{O que diabos é essa merda com você? EU DEVO-lhe o preço. NÓS NÃO iremos negociar. Fim da história ... capiche?}
{591}{}{Olha, bispo. Enfeitei Westin. Ele não era um bolo, mas eu FALHO. Nenhum dos seus meninos poderia ter feito isso, ou você teria
 Enviou um deles. Você quer resultados? Então você fala comigo e é melhor falar um preço que eu quero ouvir.}
{592}{}{1000 fichas. Isso é tudo o que será necessário para colocar a Carlson na reforma antecipada.}
{593}{}{500 fichas então. Carlson é um homem morto.}
{594}{}{Então esquece. Encontre outra pessoa.}

# 41. 1000 chipS OKAY . . . (40)
{600}{}{Tudo bem ... mil fichas. E é isso. Eu não quero ouvir mais besteira. Próximas palavras que atravessam seus lábios
 Melhor ser 'sim, senhor Bishop. Eu vou fazer isso.'}
{601}{}{Sim, Sr. Bishop. Eu vou fazer isso.}
{602}{}{Eu vou SETTLE para 1000 fichas. Desta vez.}
{603}{}{1000 fichas? Você está brincando? Faça 1500 e você conseguiu um acordo.}
{604}{}{Esqueça. Não preciso dessa merda.}
{605}{}{Esqueça. Não preciso disso.}

# 42. I NEED TO KNOW MORE ABOUT CARLSON . . . (39, 43, 44, 45, 46, 47)
{615}{}{(Chews over, então acena ligeiramente.) Justo o suficiente ... o que você precisa saber?}
{616}{}{Gostar...?}
{622}{}{O que Carlson FAZ? Qual é o horário de seu trabalho?}

# 43. YOU WANT ME TO MAKE IT LOOK LIKE AN ACCIDENT, THEN I'LL NEED TO KNOW MORE . . . (42)
{630}{}{Ele está escondido na mansão presidencial da NCR. Não pode perder. Encontrar um jeito de entrar e bater o geezer é o seu trabalho.}
{631}{}{Eu tive algumas outras perguntas sobre Carlson ...}
{632}{}{Tudo bem, é bom o suficiente para continuar. Carlson é um homem morto.}

# 44. ANY KIN, ANY FAMILY . . . (42)
{640}{}{Sua esposa está morta, mas ele tem um filho, com apenas sete ou oito anos, que vive na mansão com ele ... (Pensa).
 O lugar é obrigado a ser protegido, porém, então fique atento para a segurança.}
{642}{}{Aguarde um minuto ... como muitos guardas?}

# 45. ANY KIN, ANY FAMILY . . . (44)
{650}{}{Não sei exatamente quantos. Eu conseguiria o lugar, entendi os números. Claro, lidar com eles
 SEU problema, tribal.}
{651}{}{Great, that's really helpful. Look, Eu tive algumas outras perguntas sobre Carlson ...}
{652}{}{Bem, é o suficiente para continuar. Carlson é um homem morto.}

# 46. ILLNESSES . . . (42)
{660}{}{Não, nada disso ... do que eu sei. Ele é um bastardo paranóico, claro, mas não acho que ele esteja doente ou nada. (Frowns.) Então
 Novamente, ele é um cara muito velho, então sua saúde não pode ser tão boa.}

# 47. WHAT DOES HE DO? . . . (42)
{670}{}{(Glares a você.) Ele é o vice-presidente da NCR. Não deixe incomodá-lo ... entre em um bom tiro, e eles vão se encaixar com ele
 Para um caixão. Certifique-se de que você é capaz de entrar em pelo menos um bom tiro.}
{671}{}{All right then. Eu tive algumas outras perguntas sobre Carlson ...}
{673}{}{O "vice-presidente da NCR?" Aperte isso. Encontre alguém mais ... alguém com um desejo de morte.}

# 48. YOU DONE CARLSON HIT YET? . . . (WTG)
{680}{}{Você já fez Carlson?}
{681}{}{Você DAMN, melhor, tenha boas notícias para mim. Carlson está morto ou não?}
{682}{}{Tribal, minha paciência está desgastando. Você matou Carlson ou não?}
{683}{}{Eles estão adaptando Carlson para um caixão agora. Bem, o que resta dele, mesmo assim.}

# 49. SUCESSFULLY KILL CARLSON (WTG)
{695}{}{(Smiles.) Bom trabalho, tribal. Estou impressionado ... e não sou um homem fácil de impressionar.}

# 50. SUCESSFULLY KILL CARLSON (49)
{705}{}{Não exatamente ... (Smiles.) O que recebi é uma OFERTA: que tal se tornar parte da Família? Eu tenho grandes planos, e eu poderia
 Usá-lo: você é engenhoso, resistente e você faz as coisas FAZER. Esse é o tipo de soldado que eu preciso.}
{706}{}{Estou interessado. O que há para mim?}
{707}{}{Obrigado, mas não posso ser amarrado ... minha aldeia e meu povo estão contando comigo.}

# 51. KILL PLAYER (34, 49, 50, 52, 53)
{715}{}{Aguarde ... você não achou que eu deixaria você simplesmente andar com o que sabia, não é? Heh. Vamos agora ... há esqueletos que
 Precisa ser enterrado antes que este assunto seja fechado. Deixando você andar por aí ... é apenas uma política ruim.}
{716}{}{Aguarde ... você não pensou que as coisas estavam resolvidas entre nós, não é? Heh. Vamos agora ... pelas minhas contas, você ainda tem muito
 Você precisa pagar. Além disso, não posso deixá-lo sair com o que você conhece ... política ruim.}
{717}{}{Não fale burro, bispo. Deixe-me ir, ou eu transformarei o seu casino backwater em um inferno. "Capiche?"}
{718}{}{Faz sentido. Deixe-me apresentar-lhe a minha política de 9mm.}
{719}{}{"Política ruim?" Eu MOSTRAR-LHE MAIS POLÍTICA, VOCÊ FILHO DE UM B -}

# 52. TAKEN CARE OF? HOW? (51)
{725}{}{Tudo bem então, linha inferior:}
{726}{}{Você tem gosto pelas mulheres? Posso ter certeza de que você NÃO ESTÁ sozinho novamente. Talvez você não goste das cadelas,
 Está bem, vou pegar alguns glitterboys em que você pode estacionar sua carne.}
{727}{}{Você tem algum espião jovem que você gosta? Eu vou preparar você com todos os meninos bonitos que você deseja. Ou talvez você faça o contrário,
 Eh? Certifique-se de ter um parceiro para todos os dias da semana.}
{728}{}{Continue falando.}

# 53. TAKEN CARE OF? HOW? (52)
{735}{}{Você gosta de voar, ficar alto, ligar? Eu posso te dar tudo isso. Você quer armas, hardware novo, um pedaço de ferro melhor
 Para ligar algum Schlep? Toda essa besteira ... sua. IF ... (Eleva um dedo.) Se você se juntar à família.}
{736}{}{Parece bom. Assine-me ... chefe.}

# 54. TAKEN CARE OF? HOW? (53)
{740}{}{Tudo bem então...! Você tem um nome que você quer ser chamado?}
{741}{}{...}

# 55. TAKEN CARE OF? HOW? (54)
{745}{}{...I like it, I like it. Now, if you wanna cash in on your reputation, hit the bar downstairs, or head down Virgin
 Street to the Cat's Paw. If you want to get some weapons, head on over to New Reno Arms.}
{746}{}{Will do...boss.}

# 56. TAKEN CARE OF? HOW? (WTG)
{750}{}{Hey... }
{751}{}{. Todo mundo tratando você bem?}
{752}{}{Tudo está indo bem, Sr. Bishop. Acabei de fazer check-in, certifique-se de que tudo esteja indo bem para você.
 Até logo.}
{753}{}{Everything's going great. YOUR family in particular is showing me...EVERY courtesy. (Smile knowingly, then leave.)}

# 57. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 56)
{755}{}{Hey, before you go...you going to be stopping by and seeing my wife again, tribal? }
{756}{}{Hey, before you go...you going to be stopping by and getting high with my daughter again, tribal? }
{757}{}{Faça um pouco de prisioneiro de guerra? Eh? (Bishop está sorrindo, mas não há nenhum traço de humor nele.)}
{758}{}{What happened between me and Leslie...er, Mrs. Bishop...didn't mean anything. We might as well have been...shaking hands.}
{759}{}{Hey...look, nothing happened, all right?}
{760}{}{E sobre isso, Bishop?}
{761}{}{Talvez se você tenha prestado ATENÇÃO a Angela de vez em quando, ela não procuraria atenção ... em outro lugar.}
{762}{}{Você ficaria surpreso com o quanto essas "pow-wows" agradam a sua esposa. É como se NUNCA tivesse bom sexo.}
{763}{}{Esse é o último crack tribal que você vai fazer. Prepare-se para morrer.}

# 58. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (57)
{770}{}{O que, você acha um pouco como você pode foder minha esposa em minha cobertura e dizer 'NÃO' quando eu pedir um favor simples?}
{771}{}{Você acha um pouco como você pode foder MINHA filha na minha cobertura e então "NÃO", quando eu pedir um favor simples?}
{772}{}{Nada aconteceu! Eu juro! Eu não me importo com o que ela disse! Eu estava bêbado! E alto! Era algum outro modelo de herói, não eu!}
{773}{}{Chegue ao POINT, bispo.}
{774}{}{Chegue ao POINT, bispo. I don't have time for your faux jealousy, all right?}
{775}{}{Que tal eu faço a sua família inteira um favor e matá-lo agora mesmo?}

# 59. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (58)
{785}{}{Minha esposa pertence a mim. Qualquer coisa que TOQUE minha esposa pertence a mim. Você tem uma escolha, tribal: ou me dê uma libra
 De carne, ou você toma o trabalho, e nós estamos pardos.}
{786}{}{Minha esposa pertence a mim. Qualquer coisa que seja colocada na minha esposa pertence a ME. Você tem uma escolha, tribal: ou me dê uma libra
 De carne, ou você toma o trabalho, e nós estamos pardos.}
{787}{}{Minha filha é MINE. Qualquer coisa que seja colocada na minha filha pertence a mim. Você tem uma escolha, tribal: quer me dar
 Uma libra de carne, ou você toma o trabalho, e nós estamos pardos.}
{788}{}{You can have the pound of flesh...just come get it.}
{789}{}{All right then. I'll do it...}
{790}{}{Sua esposa não vale muito.}
{791}{}{Sua filha não vale muito.}

# 60. NO WAY, BISHOP. I'M OUTTA HERE (WIFE/DAUGHTER) . . . (8, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 56)
{800}{}{Hey, but before you go...I like the look of your weapons there, tribal...kind of reminds me of this rumor I heard not too
 long ago.}
{801}{}{Boato?}

# 61. IF PLAYER WIPED OUT RAIDERS, THREAT 1 (60)
{805}{}{Yeah...rumor in the wastes is somebody that matches your description wiped out those raiders south of Vault City. }
{806}{}{Tinha um mutante de big-ass com um torno ligado a seu ombro com ele.}
{807}{}{Tinha algum tribo com um osso no nariz dele com ele.}
{808}{}{Tinha algum robô com um cérebro em uma cúpula com ele.}
{809}{}{O que você tem a dizer a isso?}
{810}{}{Diga para wut?}
{811}{}{Ah, foi ME! MIM! Eu fiz isso!}
{812}{}{Sim, era eu.}
{813}{}{O que eu tenho a dizer a isso? Nada. Por quê?}
{814}{}{Grande deserto, muitos incursores. Você pode estar enganado.}
{815}{}{Grande deserto, muitos modelos de personagens se parecem comigo. Você pode estar enganado.}

# 62. THAT'S ME/RAIDER THREAT 2 (61)
{820}{}{Bem, você deve ser algum tipo de filho da puta bolha para desperdiçar todos esses meninos pelo seu solitário.}
{821}{}{Bem, você deve ser um tipo de cadela malvada para desperdiçar todos esses meninos pelo seu solitário.}
{822}{}{Poderia ser QUE NÃO GOSTO do que você fez lá. PODERIA ser uma das minhas melhores pessoas nesse acampamento.}
{823}{}{Pode ser que, se alguma arma for desenhada aqui, você ENCONTRARá o que aconteceu com esses incursores pessoalmente.}
{824}{}{Talvez você deveria tê-los treinado melhor. Era como disparar um monte de geckos. Geckos BEBIDOS.}
{825}{}{Eu não sabia que eles estavam trabalhando para você. Eles não queriam falar exatamente.}

# 63. RAIDER THREAT 3. . . (61, 62)
{835}{}{É assim? Eu acho que você estava lá. Eu acho que você é responsável.}
{836}{}{Como eu vejo, você me deixa grande, tribal. Você deve fazer o trabalho de vinte homens para pagar essa dívida.}
{837}{}{You take the job, then...maybe...we can call it even.}
{838}{}{Não de onde eu estou de pé. Eu acho um tiro à sua cabeça para limpar a dívida.}
{840}{}{Eles me atacaram, bispo. Não te devo nada, e não vou fazer o seu trabalho sujo. Compreendo?}

{900}{}{Você entregou a pasta de Thomas Moore.}
{925}{}{Você assassinou Westin.}
{950}{}{Você bateu Carlson.}
{975}{}{Você se tornou um homem feito da família Bishop.}
