# QUICK LOOK
{100}{}{Você vê um dos homens de Bishop.}

# EXAMINES
{150}{}{Você vê um homem robusto vestido com uma armadura de couro. Numerosas cicatrizes e feridas de bala
 cobre seu corpo.}
{151}{}{Você vê um dos homens de Bishop. He is scanning the area and fingering his weapon.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE
{200}{}{Ei!}
{201}{}{::Felicidades::}
{202}{}{:: aplausos ::}
{203}{}{:: assobios ::}

# 2. FLOAT DIALOGUE: POWER ARMOR
{205}{}{Como você vai ao banheiro com essa coisa?}

# 3. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [ARMED]
{210}{}{Bom pedaço que você chegou lá,}

# 4. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [SNEAK]
{215}{}{Uh, por que você está se esgueirando,}
{216}{}{Uh, hey,}

# 5. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=BISHOP [NORMAL]
{220}{}{Eu,}
{221}{}{Ei,}
{222}{}{Ei,}

# 6. FLOAT/CLICK DIALOGUE: MADE MAN, FA=NOT BISHOP
{225}{}{Você simplesmente entrou no lugar errado, tremendo.}
{226}{}{Bem, olhe para as bolas de bronze neste filho da puta ... pegue, garoto, antes de matá-lo.}
{227}{}{Este cara está pedindo problemas ...}
{228}{}{Eu ouço o}
{229}{}{É melhor você sair,}
{230}{}{Bem, se não for}
{231}{}{Não pensou em membros da família}
{232}{}{Você entrou no lugar errado, cadela.}
{233}{}{Bem, olhe o swagger nesta cadela ...}
{234}{}{Get, menina. Antes de matá-lo.}
{235}{}{Esta cadela está pedindo problemas ...}
{236}{}{Eu ouço o}

# 8. FLOAT DIALOGUE: MALE, PRIZEFIGHTER [ARMED]
{250}{}{Eu,champ. No weapons in here, 'kay?}
{251}{}{Eu,champ! Coloque essa arma longe.}
{252}{}{Ei,}

# 9. FLOAT DIALOGUE: MALE, PRIZEFIGHTER AND MALE PORN STAR [SNEAK]
{255}{}{Por que você está se esgueirando?}
{256}{}{Você está tentando evitar seus fãs?}
{257}{}{Por que todo o segredo?}

# 10. FLOAT DIALOGUE: MALE/FEMALE, PRIZEFIGHTER
{260}{}{Eu,}
{261}{}{Eu,}

# 11. FLOAT DIALOGUE: PORN STAR [ARMED]
{265}{}{Eu,lover-boy. No weapons in here, 'kay?}
{266}{}{Ei,}
{267}{}{Eu,}
{268}{}{Querida, você não pode estar carregando armas aqui. Heh-heh ... você é bastante mortal como está.}
{269}{}{Ei,}

# 13. FLOAT DIALOGUE: [PORN STAR, FEMALE] [SNEAK]
{275}{}{Querida, com um corpo como esse, você não poderá se esgueirar em qualquer lugar.}

# 14. FLOAT DIALOGUE: [PORN STAR, NORMAL]
{280}{}{Adoro os filmes,}
{281}{}{Te amei em Great Balls for Hire.}
{282}{}{Te amei com boa vontade de ferrão.}
{283}{}{Sou um grande fã do seu trabalho em Pokeahotass.}
{284}{}{Adorei "Vault Sex-Teen". Foi inspirado. Um tour-de-força cinematográfico.}
{285}{}{:: Whistles ::}

# 16. FLOAT DIALOGUE: SLAVER [ARMED]
{295}{}{Você está procurando preencher uma sepultura no Golgotha, escravidão? Coloque essa coisa longe.}
{296}{}{Coloque essa arma fora, escravidão, ou eu vou usar você para a prática do alvo.}
{297}{}{Slaver, é melhor você proteger essa arma agora.}

# 17. FLOAT DIALOGUE: SLAVER [SNEAK]
{300}{}{Você está procurando preencher uma sepultura no Golgotha, escravidão? Pare de se esgueirar.}
{301}{}{Pare de se esgueirar, escravidão, ou eu vou usar você para a prática do alvo.}
{302}{}{Talvez seja melhor você voltar para a escola ninja, escrava - agora pare de se esgueirar.}
{303}{}{Slaver, é melhor você parar de se esgueirar com a merda agora.}

# 18. FLOAT DIALOGUE: MALE/FEMALE, NO REP [ARMED]
{305}{}{Você está procurando preencher uma sepultura no Gólgota, tribal? Coloque essa coisa longe.}
{306}{}{Coloque essa arma longe, tribal, ou eu vou usar você para a prática do alvo.}
{307}{}{Tribal, é melhor você proteger essa arma agora.}

# 19. FLOAT DIALOGUE: MALE/FEMALE, NO REP [SNEAK]
{310}{}{Você está procurando preencher uma sepultura no Gólgota, tribal? Pare de se esgueirar.}
{311}{}{Pare de se esgueirar, tribal, ou eu vou usar você para a prática do alvo.}
{312}{}{Talvez seja melhor você voltar para a escola ninja, tribal - agora pare de se esgueirar.}
{313}{}{Tribal, é melhor você parar de se esconder por causa da merda agora.}

# 20. FLOAT DIALOGUE: COMPANION: ROBOBRAIN
{315}{}{Retire esse robô aqui. Agora.}
{316}{}{Retire esse robô antes de transformá-lo em um fogo de lixeira.}
{317}{}{Esse robô vai ser peças de reposição se ficar.}

# 21. FLOAT DIALOGUE: COMPANION: MARCUS
{320}{}{Eu * pensei * Eu cheirei mutante. É melhor você tirar seu traseiro amarelo aqui.}
{321}{}{Você e seu amigo mutante que procuram disparar? Cai fora.}
{322}{}{Esse mutante melhor sair aqui agora, ou vamos montar a cabeça em uma parede.}

# 22. FLOAT DIALOGUE: MALE/FEMALE, NO REP
{325}{}{Pegue a luta na noite passada?}
{326}{}{Eu estou batendo a Pata do gato depois do trabalho.}

# 23. CLICK DIALOGUE: ENCLAVE DESTROYED IS TRUE
{330}{}{Eu pensei que o presidente era um mito, um homem boogey costumava assustar crianças.}
{331}{}{Parece que você atravessou o inferno e voltou. Relaxe um pouco. Você merece isso.}
{332}{}{Eles iriam despejar algum vírus novo no ar? Bastardos. Espero que você tenha disparado alguns para mim.}
{333}{}{Você pode querer reproduzir o jogo como um personagem diferente.}
{334}{}{Você tem algum músculo para destruir o Enclave como você fez.}
{335}{}{Apenas vagueando depois de terminar, pegando alguns EXPs, hein? Bem, não faça
 mate-ME, 'kay?}
{336}{}{O novo Reno foi projetado por Chris Avellone e roteado por Tom French. Há rumores de que eles vão
 case-se em breve.}
{337}{}{Espero ter um personagem importante no Fallout 3, como Tandi ou Ian. Ser um bandido é uma merda.}
{338}{}{Sim, marquei com Tandi uma vez. Quando era jovem, quero dizer.}
{339}{}{Que Lynette chick está com muita necessidade de algum amor, sabe?}
{340}{}{Ouvi dizer que você entrou no Enclave para o sul. Muito corajoso.}

# 24. CLICK DIALOGUE: MALE/FEMALE, MADE MAN, SAME FAMILY
{350}{}{Ei,}
{351}{}{Eu,}
{352}{}{Ei,}
{353}{}{Ouvi Tommy the Balls voltou à cidade, verificando as coisas. Cuidado com ele.}
{354}{}{Você vê Tommy the Balls, fique fora do caminho.}
{355}{}{Coloque uma boa palavra com o Bispo para mim?}
{356}{}{Lindos fios. Gostaria de ter tido bom com o chefe, também.}
{357}{}{Alguma dicas para um cara como eu?}
{358}{}{O Bispo da Família foi bom para mim.}
{359}{}{John Bishop vai governar esta cidade.}
{360}{}{Tudo está bastante quieto hoje.}
{361}{}{A tempestade está chegando.}
{362}{}{Fedor do Golgotha   foi horrível ontem à noite.}
{363}{}{Quando vamos atacar uma das outras famílias?}
{364}{}{Com você do nosso lado, essas outras famílias não têm chance, chefe.}
{365}{}{Pegue tudo, chefe?}
{366}{}{Alguma palavra sobre as outras famílias?}
{367}{}{Um, tem algum Jet?}
{368}{}{Eu certamente poderia usar uma bebida ...}
{369}{}{A Sra. Bishop estava me revisando novamente. Isso me deixa desconfortável.}
{370}{}{A Sra. Bishop continua me olhando como uma laje de carne. Eu gostaria que ela percebesse que eu apenas
 quer ser realizada.}
{371}{}{Essa bisca é uma bunda bonita.}
{372}{}{Aquela garota bispo é um problema.}
{373}{}{Ouvi um dos meninos ter bebido a filha do Bispo, e o Sr. Bishop o esfolou.}
{374}{}{Se você fala com o Bispo, fique longe da esposa e da filha ... nada além de problemas.}

# 25. CLICK DIALOGUE: PRIZEFIGHTER
{380}{}{Ouvi, a Sra. Bishop estava procurando por você. Cuidado, amigo.}
{381}{}{Ouvi, a filha do bispo estava procurando por você. Ela está com problemas.}
{382}{}{Você não parece tão difícil, Sr. Prizefighter.}
{383}{}{Você sabe, Family Bishop pode realmente usar alguém como você. Resistente. Intransigente.}
{384}{}{Você deveria conversar com Bishop sobre um trabalho.}
{385}{}{Você pode querer considerar juntar-se a nós. Nós iremos governar New Reno.}
{386}{}{Eu ganhei US $ 20 em você!}
{387}{}{Ei,champ! That last fight was great!}
{388}{}{Viu você bater no ringue. Maldito bom gancho direito você joga.}
{389}{}{Você vai pegar o outono? Eu ganhei US $ 30 em você.}
{390}{}{Quanto você bancou?}
{391}{}{Onde você trabalha fora?}
{392}{}{Cuidado com o Masticador. Ele tem gosto de ouvidos.}
{393}{}{Eu pegaria uma bebida se eu não tivesse jogado todo meu dinheiro apostando em seu oponente.}
{394}{}{Quer ardente?}
{395}{}{Você não parece tão difícil, Ms. Left Hook.}
{396}{}{Posso ver seus músculos abdominais flexionar?}

# 27. CLICK DIALOGUE: PORN STAR
{400}{}{Ouvi, a Sra. Bishop estava procurando por você. Cuidado, amigo.}
{401}{}{Me pegue um emprego, amigo? Vamos lá. Eu sou o rei dos pregos.}
{402}{}{Adoro os filmes,}
{403}{}{Te amei em Great Balls for Hire.}
{404}{}{Te amei com boa vontade de ferrão.}
{405}{}{Sou um grande fã do seu trabalho em Pokeahotass.}
{406}{}{Adorei "Vault Sex-Teen". Foi inspirado. Um tour-de-força cinematográfico.}
{407}{}{Ouvi, a filha do bispo estava procurando por você. Ela está com problemas.}
{408}{}{Tem alguma abertura no estúdio?}
{409}{}{Adorei "Vault Sex-Teen". Foi inspirado. Um tour-de-força cinematográfico.}
{410}{}{Ouvi Tommy the Balls quer dar uma seleção particular.}
{411}{}{Adorei seu último filme. Posso ajudá-lo a ensaiar para o próximo?}
{412}{}{Faça-me um emprego, e vou mostrar-lhe alguns dos meus movimentos.}
{413}{}{Quando você vai parar e me ver?}
{414}{}{Ei,you gonna dance here tonight?}
{415}{}{Parecendo mortal, querido.}
{416}{}{Lady Luck ficará com ciúmes, você continua vindo aqui.}

# 29. CLICK DIALOGUE: [SLAVER]
{420}{}{Como estão as coisas no Den?}
{421}{}{Essa marca de escravo doeu quando você entendeu?}
{422}{}{Pensei em me tornar um escravo, mas eu odeio todas as viagens.}
{423}{}{Você está procurando os estábulos? É aí que eles mantêm a maioria dos escravos.}
{424}{}{Estar na Família do Bispo é um bom show.}
{425}{}{Você traz uma nova cultura de escravos, ou você está fazendo um caravanismo?}
{426}{}{Vocês precisam encontrar algum estoque novo ... esse último lote de escravos era piss-poor.}
{427}{}{Vocês pegam mais escravos tribais?}
{428}{}{Qual é a taxa atual para os escravos hoje em dia?}
{429}{}{Escravos, brahmin, o mesmo.}

# 30. CLICK DIALOGUE: MALE/FEMALE, NO REP (Good Reaction)
{440}{}{Se você está procurando trabalho, poderíamos usar alguém como você. Fale com o Sr. Bishop.}
{441}{}{Você está procurando trabalho? Você pode querer falar com o Sr. Bishop.}

# 31. CLICK DIALOGUE: MALE, NO REP (Bad Reaction)
{445}{}{Piss off, tribal.}
{446}{}{Não tenho problemas para você, tribal.}
{447}{}{Vá fumar o seu cachimbo de paz, tribal.}
{448}{}{Não tenho vontade de conversar. Cai fora.}
{449}{}{Scram, tribal.}
{450}{}{Você sabe quem eu sou? Sou um dos homens de Bishop. Agora foda.}
{451}{}{Você está procurando me irritar? Você não vai gostar de mim quando estou brava.}
{452}{}{Piss off antes de usá-lo para a prática alvo.}
{453}{}{Procurando problemas? Continue falando comigo, veja o que acontece.}

# 32. CLICK DIALOGUE: FEMALE, NO REP (Bad Reaction)
{460}{}{Eu não estou procurando nenhuma bunda tribal agora. Volte mais tarde.}
{461}{}{Não tenho tempo para fazer você agora, tribal. Por que você não volta mais tarde?}
{462}{}{Não, eu não sei onde é isso, agora zangado! :: Tributos estúpidos. ::}
{463}{}{Piss off, tribal.}
{464}{}{Os bispos não falam com o lixo tribal, temos melhores coisas para fazer.}
{465}{}{Não tenho problemas para você, tribal.}
{466}{}{Vá fumar o seu cachimbo de paz, tribal.}
{467}{}{Não tenho vontade de conversar. Cai fora.}
{468}{}{Scram, tribal.}
{469}{}{Você sabe quem eu sou? Sou um dos homens de Bishop. Agora foda.}
{470}{}{Você está procurando me irritar? Você não vai gostar de mim quando estou brava.}
{471}{}{Piss off antes de usá-lo para a prática alvo.}
{472}{}{Procurando problemas? Continue falando comigo, veja o que acontece.}
{473}{}{Eu não tenho cerveja tão ruim. Dá o fora.}
{474}{}{Você deve ser a tribo mais feia que já vi.}
{475}{}{Saia daqui antes de te deixar mais feio que você.}
{476}{}{Vá locar a alguém mais bêbado do que eu, cadela.}

# 34. FLOAT DIALOGUE: COMPANION: LENNY
{490}{}{Eu * pensei * Eu cheirei algo apodrecendo. Pegue esse garoto ghoul para você aqui.}
{491}{}{Pegue esse ghoul fedido aqui fora. Agora.}
{492}{}{Esse ghoul não está fora de aqui em um minuto, ele vai ser mais morto do que ele já é.}

# END OF LINES
{1200}{}{! Maneira de chutar a bunda do Enclave!}
{1210}{}{.}
{1215}{}{?}
{1216}{}{... por que o segredo?}
{1220}{}{O que está tremendo?}
{1221}{}{, O que você tem feito?}
{1222}{}{! Você ficou sem problemas?}
{1228}{}{ A família é um monte de gatinhos. O que voce pensa sobre isso?}
{1229}{}{. Agora.}
{1230}{}{. A sua família não vai sentir sua falta?}
{1231}{}{ tive tempo de fazer muito mais do que beijar o traseiro dos seus chefes.}
{1236}{}{ A família é um monte de gatinhos. Agora eu vejo que é verdade.}
{1252}{}{! Você não pode mostrar armas aqui, certo?}
{1260}{}{. Você está cuidando de si mesmo?}
{1261}{}{. Estás bem?}
{1266}{}{! Você não pode mostrar armas aqui, certo?}
{1267}{}{! Coloque essa arma longe.}
{1269}{}{! Você pode mostrar suas tetas, mas você não pode mostrar armas aqui, tímido?}
{1280}{}{!}
{1350}{}{. O que está acontecendo?}
{1351}{}{. O que está tremendo?}
{1352}{}{. Você ficou sem problemas?}
{1402}{}{!}
