# 0. QUICK LOOK
{100}{}{Você vê o Big Jesus Mordino.}

# 0. LOOK
{150}{}{Você vê um homem gordo com olhos pretos claros. Ele está coberto de suor e respira pesadamente.}
{151}{}{Você vê o Big Jesus Mordino. He is covered in sweat and is breathing heavily.}

# 1. WARNING FLOAT (WTG)
{200}{}{Fique longe de lá.}
{201}{}{Isso não ... pertence a você.}
{202}{}{Toque isso novamente, e você deve ... morrer no Gólgota.}

# 2. FLOAT (WTG)
{210}{}{:: Wheeze ::}
{211}{}{*COF cof*}
{212}{}{:: Wipes suam da testa. ::}

# 3. MADE MAN: MORDINO (WTG)
{220}{}{Você é a ... * tosse * ... mais valorizada dos meus homens.}
{221}{}{As pessoas de Reno estão mostrando ... * tosse * ... respeito apropriado?}

# 4. MORDINO HEART ATTACK (WTG)
{230}{}{Urgggg ...}
{231}{}{...Meu Deus...}
{232}{}{...meu coração...}
{233}{}{Hurrkkkk}

# 5.  NORMAL INTRO (WTG)
{240}{}{(O homem se virou para encará-lo. Ele parece doente com febre: o suor escorre no rosto e mancha suas roupas.}
{241}{}{Ele está ignorando você e olhando para Myron; Parece que ele está esperando Myron para falar.)}
{242}{}{Ele está olhando para você; Parece que ele está esperando por você para falar.)}
{243}{}{Olhe para ele com seu olhar mais malvado.}
{244}{}{Olhe para ele com um leve desinteresse.}
{245}{}{Olhe para ele com um olhar irritado}
{246}{}{Olhe para ele com o desinteresse afetado}
{247}{}{Afastar-se}
{248}{}{Quem é Você?}
{249}{}{Você é Jesus Mordino?}
{250}{}{Desculpa. Eu entrei no quarto errado.}

# 6. STARE BACK AT HIM (WTG, 5, 19, 22, 28, 30, 33)
{260}{}{Você. (Mordino olha para Myron enquanto ele entra, relâmpago preto em seus olhos.) Você ... deixou sua postagem. Seu uso
 Para mim está em um ... fim. (Ele faz um movimento, e seus guardas alcançam suas armas.)}
{261}{}{(O olhar do homem escurece. Ele faz um movimento, e seus guardas alcançam suas armas).}
{262}{}{(O olhar de Big Jesus torna-se preto. Ele faz um movimento, e seus guardas alcançam suas armas).}
{263}{}{Aieeeeeeee!}
{264}{}{Colabore!}
{265}{}{Corre!}
{266}{}{Uau! Uau…!}
{267}{}{Ei! Espere um segundo...!}
{268}{}{Você quer um pouco disso, * Fatman?! * Você QUER ALGUNS de}

# 7. WHO ARE YOU? (WTG, 5)
{275}{}{(O homem fala com uma voz raspada.) Eu ... sou Jesus Mordino. Você ... abordará como SENOR Mordino. (Uma gota de suor goteja
 Abaixo da testa.) O que ... é o seu negócio comigo?}
{276}{}{Você retornou. (Uma nota de suor escorre pela testa.) O que ... é o seu negócio comigo?}
{277}{}{Estou procurando trabalho.}
{278}{}{I spoke to your son, Senor Mordino. Estou procurando trabalho.}
{1278}{}{I spoke to your son, Senor Mordino. I'm a slaver, and Estou procurando trabalho.}
{279}{}{Falei com seu filho, senhor Mordino. Sou escravista e procuro vender escravos.}
{280}{}{Você sabe alguma coisa sobre a morte do filho do Sr. Wright?}
{281}{}{O calor está incomodando você? Parece ... desconfortável.}
{282}{}{Nenhum negócio hoje. Eu tenho que ir agora.}

# 8. I'M LOOKING FOR WORK [REFUSE] (7, 12)
{290}{}{(Estuda você por um longo período de tempo e, em seguida, sacode a cabeça.) Você ... não parece suficientemente forte. Não tenho trabalho para você.}
{291}{}{(Estuda você por um longo tempo, então sacode a cabeça.) Você ... é uma MULHER. O que eu preciso fazer não é o trabalho da mulher.}
{1291}{}{Muito bem. Você está interessado em comprar escravos?}
{292}{}{Me de uma chance. Me dê um emprego - qualquer trabalho - eu posso fazer isso.}
{293}{}{Me dê uma chance, senhor Mordino. Dê-me um emprego, qualquer trabalho, posso fazê-lo.}
{294}{}{Deixe-me provar a mim mesmo. Eu posso fazer isso.}
{295}{}{Deixe-me provar a mim mesmo, senhor Mordino. Eu posso fazer isso.}
{296}{}{Tudo bem então. Pegue você mais tarde.}

# 9. I'M LOOKING FOR WORK [SECOND TIME REFUSE] (8, 25, 50)
{305}{}{(Sweat escorre pelo rosto de Mordino. Sua expressão escurece.) Eu ... falei. Não tenho trabalho para você. Deixe ... e NÃO volte.}
{306}{}{Vamos, Big Jesus ... apenas uma chance ...}
{307}{}{Tudo bem então. Adeus.}

# 10. BAD NEWS (9, 17, 33, 47)
{315}{}{(Mordino fica em silêncio por um momento, então ele fala.) Eu sou Jesus Mordino. Chefe da família Mordino. Você veio
 Para ... meu cassino. Minha casa. Você me mostrou ... não há respeito. Você vai aprender.}
{316}{}{Eu acho que VOCE vai aprender uma coisa ou duas ...}
{317}{}{Uau! Aguarde ... vamos falar sobre isso! Vamos agora ...}
{318}{}{Corra para a porta.}
{319}{}{:: Dive for cover, tire as armas em câmera lenta enquanto os bandidos explodem da madeira. ::}

# 11. QUESTION NODE (12, 13, 14, 15, 16, 46, 47, 48, 49)
{325}{}{(Mordino espera. Enquanto você assiste, outro talão de suor escorre pelo lado do rosto).}
{326}{}{Eu estava procurando vender alguns escravos ...}
{327}{}{O que você sabe sobre a morte de Richard Wright?}
{329}{}{Deixa pra lá.}

# 12. SLAVER (7, 11)
{335}{}{(Estudos você.) Eu ... não conheço você, mas vou ... ouvi-lo. (Wipes suam de sua testa).}
{336}{}{Você tem escravos para vender?}
{337}{}{Sim, aqui mesmo comigo. Dê uma olhada e me faça uma oferta.}
{338}{}{Não, eu não. Na verdade, cometi um erro. Estou procurando trabalho, não para vender escravos.}
{339}{}{Não ... Na verdade, eu fiz algumas perguntas para você.}
{340}{}{Não me desculpe. Acabei de lembrar que eu tenho que estar em outro lugar.}

# 13. SLAVE DEALINGS? (12, 16)
{345}{}{(Mordino estuda seus companheiros. Seu olhar pára em Miria, e ele lambe seus lábios.) Seu puta parece fresco ... Eu vou
 Dê-lhe 250 fichas para ela.}
{346}{}{(Mordino estuda seus companheiros. Seu olhar pára em Davin.) Embora pareça fraco, levarei aquele garoto lá.
 200 fichas para ele.}
{347}{}{(Mordino estuda seus companheiros. Seu olhar pára em Sulik ... e ele enruga o nariz.) O tribal ... ele fede, mas ele
 Parece forte. Vou levá-lo por 100 fichas.}
{348}{}{(Mordino estuda seus companheiros. Seu olhar pára em Vic.) Vou pegar o velho ... parece que ele tem alguns anos
 De trabalho deixado nele. Vou levá-lo por 100 fichas.}
{349}{}{(Mordino estuda seus companheiros. Seu olhar pára em Cassidy.) Vou pegar o velho ... ele parece que ele tem um
 Poucos anos de trabalho deixados nele. Vou levá-lo por 100 fichas.}
{350}{}{(O olhar de Mordino pára imediatamente no Robobrain.) Essa máquina lá. Eu lhe darei 500 fichas para ele.}
{351}{}{(O olhar de Mordino pára de imediato no cyberdog.) Eu comprarei aquele ... cão de máquina de você. Eu lhe darei 500
 Chips para ele.}
{352}{}{(Mordino estuda seus companheiros, então balança a cabeça.) Você não tem nada que eu queira.}
{353}{}{Senhor Mordino, por favor ... o escravo vale muito mais do que isso. Tem muitos anos de serviço fiel restante.}
{354}{}{Esse é um preço justo. Você pode ter o escravo.}
{355}{}{Na verdade, não estou procurando vender aquele ainda. Eu fiz algumas perguntas que queria lhe perguntar ...}
{356}{}{Na verdade, não estou olhando para vender esse escravo. Vamos tratar outro momento.}
{357}{}{Muito bem. Eu tive algumas perguntas para você, no entanto ...}
{358}{}{Tudo certo. Outra vez, quando eu conseguir um estoque melhor, então.}

# 14. SLAVE DEALINGS 2, BARTER FAIL (13)
{370}{}{Não. Ela viu muita viagem difícil e parece cansada ... 250 fichas para ela ou nada.}
{371}{}{O garoto parece suave e fraco. Não vou dar mais de 200 fichas para ele.}
{372}{}{Não. O tribal cheira e parece ser ... difícil. Será difícil derrubá-lo. 100 fichas.}
{373}{}{O homem é velho. Vou levá-lo por 100 fichas.}
{375}{}{500 fichas.}
{377}{}{Senhor Mordino, por favor ... você corre o risco de me insultar. Este é estoque primário, vale muito mais do que isso.}

# 15. SLAVE DEALINGS 2, BARTER SUCCEED (13)
{390}{}{(Mordino anda em torno de Miria, examina seu rosto cuidadosamente e depois bate o traseiro.) Hmmmm. 500 fichas para ela, então.}
{391}{}{(Mordino anda em torno de Davin, enrola a manga do garoto e examina seus músculos, depois verifica seus olhos para usar quimicamente).
 Hmmmm. Ele parece forte o suficiente. 400 fichas para ele, então.}
{392}{}{(Mordino anda em torno de Sulik, franzindo a testa.) Hmmmm. Ele parece forte ... e tolerante com a dor, enfiar um osso na sua
 Nariz até agora. 200 fichas para ele.}
{393}{}{(Mordino caminha em torno de Vic, franzindo a testa.) Hmmmmm. Vou levá-lo por 200 fichas. Não mais.}
{394}{}{(Mordino anda por Cassidy, franzindo a testa.) Hmmmmm. Vou levá-lo por 200 fichas. Não mais.}
{395}{}{(Mordino estuda o Robobrain por alguns minutos.) Mil pedaços, então.}
{396}{}{(Mordino estuda o cyberdog por alguns minutos.) Mil pedaços, então.}

# 16. SLAVE DEALINGS 2, BARTER SUCCEED (13, 14, 15)
{410}{}{(Mordino levou Miria embora contando seu dinheiro.) Aqui.}
{411}{}{(Mordino Davin levou embora contando seu dinheiro.) Aqui.}
{412}{}{(Mordino tirou o Sulik enquanto contava o seu dinheiro.) Aqui.}
{413}{}{(Mordino tem Vic levado embora contando seu dinheiro.) Aqui.}
{414}{}{(Mordino conduziu Cassidy enquanto conta seu dinheiro.) Aqui.}
{415}{}{(Mordino Robobrain levou embora enquanto contava seu dinheiro.) Aqui.}
{416}{}{(Mordino tem o cyberdog levado embora contando seu dinheiro.) Aqui.}
{417}{}{Gostaria de ver o que mais tenho em estoque?}
{418}{}{Obrigado, senhor Mordino. Por sinal, tive algumas perguntas que queria lhe fazer ...}
{419}{}{Obrigado, senhor Mordino. Espero que o escravo sirva você bem. Adeus.}

# 17. SLAVE DEALINGS 2, PUSH TOO FAR (14, 15)
{430}{}{(Sweat escorre pelo rosto de Mordino. Sua expressão escurece.) Você é um cão e um FILHO de um cachorro. Eu não comprarei
 De você gosta de você. Deixe ... e NÃO volte.}
{431}{}{Senhor Mordino, por favor ... reconsidere ...}
{432}{}{(Deixe em silêncio.)}

# 18. I'M LOOKING FOR WORK [AGREE] (8, 7, 12)
{440}{}{(Mordino o estuda.) Muito bem. Eu ... trabalho para você. Pegue ... (Leve uma respiração ofegante profunda, limpa o suor de sua testa).
 ... este pacote ... para os * estábulos * a norte de Reno. Dê a um homem ... Ramirez, então volte.}
{441}{}{OK. Soa bastante fácil.}
{442}{}{Eu vou lá agora, senhor Mordino.}
{443}{}{O que está no pacote?}
{444}{}{Uh, eu mudei de idéia. Eu acho que vou passar.}

# 19. WHAT'S IN THE PACKAGE? (18)
{450}{}{Eu ... não pago ... para fazer perguntas.}
{451}{}{Bem, eu gostaria de saber o que estou carregando antes de deixá-lo. É perigoso?}
{452}{}{Deixa pra lá então. Eu estou fora.}

# 20. I'LL DO THE DROP (18, 19)
{460}{}{Dirija para o norte pela rua Virgin, depois dos casinos ... siga a trilha que leva fora da cidade. Você irá ...
 Estábulos. Agora vá.}
{461}{}{(Siga as instruções dele)}

# 21. HAVE YOU DONE AS I ASKED (WTG)
{470}{}{Tem ... você fez o que eu pedi?}
{471}{}{Não, ainda não entreguei o pacote.}
{472}{}{Sim, entreguei a Ramirez como você pediu.}
{473}{}{Sim, estive nos estábulos e deixei seu pacote ... você sabe o que eles fazem lá? Estão torturando
 Escravos com chems.}
{474}{}{Sim, entreguei seu pacote a esse guarda, Ramirez ... você sabe que esse cara é um jato? Ele estava REEKING de fumos de jato.}

# 22. HAVE YOU DONE AS I ASKED (21)
{480}{}{Então, por que você está aqui? (Big Jesus limpa a testa, então respira profundamente.) POR QUE você não entregou a embalagem?}
{481}{}{Bem, eu tive algumas perguntas primeiro ...}
{482}{}{Eu vou fazer isso agora mesmo.}
{483}{}{Uh, você sabe o que? Eu acho que vou cuidar disso agora ...}

# 23. HAVE YOU DONE AS I ASKED - YES (21, 24, 51, 52)
{490}{}{(Nods.) Muito bem. Aqui está ... o seu pagamento. Cem ... fichas. Para uma ... entrega simples ... é
 mais do que o suficiente.}
{491}{}{É melhor do que nada, acho.}
{492}{}{Obrigado, senhor Mordino.}

# 24. I'VE BEEN TO THE STABLES (21)
{500}{}{(Squints com raiva. Um grânulo de suor escorre pelo lado do rosto). Eles são ... gado. Não mais.}
{501}{}{Você monstro ... você acabou de assinar seu próprio mandado de morte.}
{502}{}{Uh ... apenas checando. Sobre o meu pagamento ...}

# 25. NO MORE WORK (23, 31, 41)
{510}{}{Eu não tenho mais ... trabalho para você. (Nods na porta.) Eu desejo estar sozinho. Deixe agora ... e NÃO volte.}
{511}{}{Ah, vamos. Deve haver algum outro trabalho que eu possa fazer ...}
{512}{}{OK.}

# 26. MISSION 2 (23)
{520}{}{Eu ... tenho mais trabalho para você. Preciso de alguém ... (Ele respira profundamente e depois toca o suor de sua testa). ... para coletar
 Minha porcentagem dos ... Irmãos da Córsega. Eles são TARDE em seus pagamentos.}
{523}{}{Eu acho que vou passar. Obrigado mesmo assim.}

# 27. MISSION 2, AGREE (X)
{530}{}{Dirija para o norte da rua Virgin. Eles estão do outro lado da academia ... se eles te deram problemas ... se eles fizerem desculpas ... PERDA deles.}
{531}{}{OK. I'm on it.}
{532}{}{Muito bem, senhor Mordino.}

# 28. CORSICAN BROS DEAD (WTG)
{540}{}{Eu disse que você poderia ... HURT the Corss Brothers. Eu não lhe dei permissão para ... matá-los.}
{541}{}{Ei, olha ... eles começaram a jogar fora e acabei de me defender ...}
{542}{}{Eles estavam dizendo coisas ruins sobre sua mãe, Big Jesus. EU DEVEM matá-los.}
{543}{}{Oh. Adivinha que eu ouvi.}

# 29. HAVE YOU DONE AS I ASKED (WTG)
{551}{}{Uh ... sim, mas não tenho dinheiro comigo. Apenas me dê algum tempo, e eu vou devolvê-lo para você.}
{552}{}{Sim, aqui está o dinheiro.}
{553}{}{Não, ainda não.}
{554}{}{Não, eu vou cuidar disso agora.}

# 30. HAVE YOU DONE AS I ASKED (29)
{560}{}{Então, por que você está aqui? (Ele limpa a testa, então respira profundamente.) POR QUE você não tem o dinheiro?}
{561}{}{Bem, você vê, eu tive algumas perguntas primeiro ...}
{562}{}{Good question. Eu vou fazer isso agora mesmo.}

# 31. HAVE YOU DONE AS I ASKED - YES (29)
{570}{}{(Nods como você lhe dá o dinheiro.) Aqui. Metade ... é sua. Heh. Eles já me pagaram este mês, mas eu gosto
 Para mantê-los ... em seus dedos.}
{571}{}{Ei, obrigado, Big Jesus.}

# 32. I'M LOOKING FOR WORK [AGREE] (31)
{580}{}{(O senhor Mordino olha para você por um longo tempo, então acena ligeiramente.) Eu tenho um último emprego para você. Lá ... (Takes
 Uma respiração sibilante profunda, limpa o suor de sua testa.) ... é um homem que deve morrer.}
{581}{}{Ele está tão bem como morto. O cadáver recebeu um nome?}
{582}{}{Quem é esse homem?}
{583}{}{Quem é este homem que você deseja morto, senhor Mordino?}
{584}{}{Whoa, ninguém diz nada sobre o assassinato. Esqueça.}
{585}{}{Não posso aceitar este trabalho, senhor Mordino, desculpe. Adeus.}

# 33. REFUSE JOB (18, 19, 26, 32, 35, 36, 52)
{595}{}{Você vem para mim por trabalho. Eu te dou ... trabalho e você se queixa como uma CRIANÇA. (Toma uma respiração profunda e raspada, depois tosses.)
 Você ... não é mais bem vindo aqui ... no meu cassino. Sair.}
{596}{}{Você vem para mim por trabalho. Você recusa minha ... oferta. (Toma uma respiração profunda e raspada, depois tosses.)
 Você ... não é mais bem vindo aqui ... no meu cassino. Sair.}
{597}{}{Antes de ir, tive algumas perguntas que queria lhe perguntar ...}
{598}{}{Ainda não fiquei falando com você, "Big Jesus".}
{599}{}{Minhas desculpas, senhor Mordino. Eu irei imediatamente.}
{600}{}{Por que você não me deixa sair?}

# 34. THE CORPSE GOT A NAME? (32)
{610}{}{Este homem, Louis Salvatore ... ele matou muitos dos meus homens ... muitos homens ORGULHOS da família Mordino. Ele ... os matou
 Na rua como ... cães. (Sua mão se aperta em um punho.) É minha vontade que esse homem morra.}
{611}{}{Se você pegou as fichas, ele está bem morto.}
{612}{}{Espere um minuto. Louis Salvatore que governa a família Salvatore? Aqueles que têm os fabricantes de luz que
 Pode cortar homens ao meio?}
{613}{}{Vou ver a família Mordino vingada, senhor Mordino. Eu retornarei quando tiver completado a tarefa.}
{614}{}{Não aceito essa tarefa. Estou indo embora.}
{615}{}{Tudo bem então. Eu vou fazer isso.}

# 35. THE CORPSE GOT A NAME 2? (X)
{620}{}{Devo pagar-lhe ... quando Salvatore não respira mais.}
{621}{}{Espere um minuto. Louis Salvatore que governa a família Salvatore? Os que possuem os fabricantes de luz que podem
 Cortar homens pela metade?}
{1621}{}{Bem ... tudo bem então. Eu vou fazer isso.}
{623}{}{Eu não coloco meu pescoço para nada. Estou fora daqui.}

# 36. WHOA. SALVATORES? (34, 35)
{630}{}{(Mordino acena com a cabeça, estuda sua expressão.) Isso ... faz você ter medo? Se assim for, saia. (Pontos na porta.) O Mordino
 A família não tem utilidade para ... covardes.}
{631}{}{Não, eu vou fazer isso.}
{633}{}{Ligue-me um covarde, mas eu gosto de respirar. Eu vou passar neste trabalho.}

# 37. I'LL DO IT (34, 35, 36)
{640}{}{(Nods.) Isso é bom. O homem é velho ... um paralítico ... ele se esconde em seu bar, "Salvatore's", perto do Bishop Casino.
 Ele é um ... covarde e nunca deixa seu quarto no andar de cima. Quando ele é ... morto, volte.}
{641}{}{Aleijado?}
{642}{}{Tudo certo.}

# 38. CRIPPLE? (37)
{650}{}{(Nods.) As pernas do açougue ... são fracas. (Jesus limpa sua testa, então tira outro suspiro fraco).
 Ele também tem ... dificuldade ... respirar. Ele leva ar através de um ... tanque de oxigênio.}
{651}{}{Oxygen tank, huh? Hmmmm. Tudo certo.}
{652}{}{Eu voltarei quando ele estiver morto, senhor Mordino.}

# 39. KILL SALVATORES (WTG)
{660}{}{Louis Salvatore vive. Por que você retornou?}
{661}{}{(Uma nota de suor escorre pelo lado do rosto de Mordino.) Você fez o que eu pedi? Louis Salvatore está morto?}
{662}{}{Ele está morto. Sua família é vingada, senhor Mordino.}
{663}{}{Não, voltarei quando o matar.}
{664}{}{Salvatore está muito bem guardado. Eu vou ter que cancelar neste trabalho.}

# 40. TRY AND QUIT SALVATORE JOB (39)
{670}{}{Se você ... fugir desse trabalho, eu terei você ... MATADO.}
{671}{}{Como você disse assim, eu voltarei quando ele estiver morto.}
{672}{}{Tente qualquer coisa, e você vai se juntar aos Mordinos, os Salvatores matados.}

# 41. SALVATORE JOB, SUCCEED (39)
{680}{}{Então eu ouvi. (Nods respeitosamente.) Você fez ... bem. Minha fé em você não está fora de lugar. Aqui está ... seu
 Forma de pagamento. Quinhentos ... chips.}
{681}{}{Obrigado.}
{682}{}{Isso vai fazer ... por enquanto.}
{683}{}{E ... armadura e uma arma que você pode achar ... útil.}

# 42. YOU HAVE DONE AS I ASKED. . . (41)
{690}{}{(Nods.) Seu sucesso ... me agrada. Gostaria de recebê-lo na Família Mordino. (Feche os ombros.) Will
 Você se junta à nossa família? Sua força deve ser ... nossa força.}
{691}{}{Isso me agrada se tornar um membro da família Mordino.}
{692}{}{Não posso me juntar aos Mordinos. Mas não me interpretem mal, Big Jesus: Foi um prazer trabalhar com você.}
{693}{}{Não quero participar, obrigado. Eu tenho uma aldeia que tenho que salvar primeiro.}

# 43. YOU HAVE DONE AS I ASKED. . . (42)
{700}{}{(Nods.) Me desculpe, essa é a sua escolha. Como eu disse, seu sucesso me agrada ... Eu odiaria suas habilidades
 Para ser usado por um dos meus ... concorrentes. (Moções para seus guardas, que alcançam suas armas.)}

# 44. YOU HAVE DONE AS I ASKED. . . (42)
{710}{}{Isso é bom. Você tem ... um nome pelo qual você deseja ser chamado? Todos os Mordinos ... todos os Reno ... devem
 Conheça esse nome.}
{711}{}{Sim, e tal ...}

# 45. CALL ME. . . (44)
{720}{}{... esse é um bom nome. (Nods.) O nome Mordino tem ... peso em New Reno. Visite ... a Pata do gato ... New Reno Arms ... e
 Diga-lhes que você é da minha família ... eles vão te tratar bem.}

# 46. WHAT ABOUT RICHARD? (7, 11)
{730}{}{(Olha para você por um longo período de tempo, então entra em confusão.) Por que ... você me pergunta isso? Eu já ouvi o que aconteceu. (Toalhetes
 A garota tirou demais Jet e morreu.}
{731}{}{Esse é o problema. Os Mordinos são os maiores fornecedores de Jet em New Reno. Isso faz você quem quiser
 assuma a culpa.}
{732}{}{Você sabe onde ele pegou o Jet?}
{733}{}{Tudo bem então. Só perguntando. Tive algumas outras questões ...}
{734}{}{Entendo. Acho que é melhor eu ir.}

# 47. YOU'RE GONNA TAKE THE BLAME (46)
{740}{}{(Sibila, limpa mais suor de sua testa.) Se os Wrights tivessem ... SENTIDO com quem eles nasceram, eles saberiam
 Não somos a única família com Jet in New Reno. Nós ... NÃO matamos crianças.}
{741}{}{Apenas adultos, hein? Quero dizer, Jet demora um pouco para matar alguém, mas funciona, certo?}
{742}{}{Alguém mais pode, e eles podem enegrecer o nome de Mordino. Você sabe quem pode ter vendido Richard the Jet
 Isso o matou?}
{743}{}{Entendo. Olha, eu tive algumas outras perguntas ...}
{744}{}{Obrigado pela informação, senhor Mordino. Eu devo ir agora.}

# 48. YOU KNOW WHO MIGHT HAVE SOLD IT TO HIM? (46, 47)
{750}{}{(Shakes head.) Eu ... conheço poucas vidas de empurradores em Reno. (Toma uma respiração raspada, tosse ligeiramente). Você ... pode perguntar
 Meu filho ... no cassino, abaixo.}
{751}{}{Eu vou. Tive algumas outras questões ...}
{752}{}{Eu vou. Obrigado, senhor Mordino.}

# 49. I HAVE A HEART CONDITION . . . (7, 11)
{760}{}{A temperatura não ... concorda comigo. Minha respiração é ... às vezes difícil. Em momentos de estresse ou outros fatores físicos
 Atividade, eu me canso rapidamente. Às vezes, tenho dores no peito.}
{761}{}{Mesmo. Bem, é bom que você não tome nenhuma metafetaminas ou estimulantes, então. Tive algumas outras questões ...}
{762}{}{Entendo. É melhor eu ir agora.}

# 50. I HAVE A HEART CONDITION . . . (7)
{770}{}{Eu não conheço você ... você vem para mim ... sem a palavra de ninguém para dar sua oferta ... peso. (Limpa a testa, depois tira
 Uma respiração profunda e chata.) NÃO tenho trabalho para você.}
{771}{}{Vamos, me dê uma chance. Me dê um emprego, qualquer trabalho ... Eu posso fazer isso.}

# 51. RAMIREZ IS A JET HEAD (24)
{780}{}{Nem todos nos estábulos ... SABEM que eles são sujeitos de teste.}
{781}{}{Uh ... vem de novo?}
{782}{}{Oh. Uh, sobre o meu pagamento, então ...}

# 52. COME AGAIN? (51)
{790}{}{Ramirez deixou ... quatro escravos escaparam no mês passado. (Bate sua cabeça ligeiramente). Isso não é bom. Dentro do
 Hora, o Jet que você deu a Ramirez vai parar o seu ... coração. É PUNTO.}
{792}{}{Você me usou para matar esse cara? É isso, Jesus, estou fora daqui.}

{850}{}{Você coletou o tributo de Big Jesus.}
{875}{}{Você assassinou o grande Jesus.}
{900}{}{Você se tornou um homem feito da família Mordino.}
{925}{}{Você completou o contrato para Big Jesus.}

# END LINES
{5268}{}{? !! Então VENHA ALGUMA, VOCÊ FAT FILHO DE UM B--}
