# quick look
{100}{}{Você vê uma fã de boxe emojada.}

# examine
{150}{}{Você vê um homem de aparência selvagem. Ele está gritando sua cabeça sobre algo.}
{151}{}{Você vê uma fã de boxe emojada.He is screaming for blood.}
{152}{}{Você vê uma mulher de aparência selvagem. Ela está gritando sua cabeça sobre algo.}
{153}{}{Você vê uma fã de boxe emojada.She is screaming for blood.}

# 1. FLOAT DIALOGUES [FAN=MALE, PC NOT A PRIZEFIGHTER]
{200}{}{Yeeeaaaaahhhhh!}
{201}{}{:: scream :: :: bellow :: :: scream ::}
{202}{}{Mate ele,}
{1202}{}{!}
{203}{}{Você é o melhor,}
{1203}{}{!}
{204}{}{Pegue-os,}
{1204}{}{!}
{205}{}{sim! Dê isso a ele!}
{206}{}{}
{1206}{}{ é o melhor. Ao melhor.}
{207}{}{}
{1207}{}{!!!}
{208}{}{}
{1208}{}{, você é o cara!}
{209}{}{}
{1209}{}{ É o melhor campeão de boxe que já vi.}
{210}{}{}
{1210}{}{ É realmente inteligente também. Ele realmente sabe como machucar alguém.}
{211}{}{}
{1211}{}{ Se preocupa com seus fãs. Ele não os mata como os outros boxeadores.}
{212}{}{}
{1212}{}{ É muito bonito.}
{213}{}{}
{1213}{}{ É tão manhoso.}
{214}{}{eu amo}
{1214}{}{ Aiiiieeeeeee!}
{215}{}{:: screech :: :: screech ::}
{216}{}{}
{1216}{}{ É cuidar e nutrir. Foi o que ele me disse na noite passada.}

# 2. FLOAT DIALOGUES [FAN=MALE, PC = FEMALE OR MALE PRIZEFIGHTER]
{250}{}{}
{1250}{}{, você é o cara!}
{251}{}{}
{1251}{}{ É realmente inteligente também. Ele realmente sabe como machucar alguém.}
{252}{}{}
{1252}{}{ Se preocupa com seus fãs. Ele não os mata como os outros boxeadores.}
{253}{}{Eu ouço}
{1253}{}{ Era quase um desconhecido, fresco fora dos resíduos, antes de chegar à caixa em New Reno.
 Misterioso! Mortal!}
{254}{}{Ohmódodo!}
{1254}{}{! Assine um autógrafo!}
{255}{}{Punch me! Punch me! Eu quero dizer aos meus filhos que você me perfurou!}
{256}{}{Você é o melhor,}
{1256}{}{! Dê-lhes o inferno!}
{257}{}{Mate ele,}
{1257}{}{!}
{258}{}{Você é o melhor,}
{1258}{}{!}
{259}{}{Pegue-os,}
{1259}{}{!}
{260}{}{sim! Dê isso a ele!}
{261}{}{}
{1261}{}{, você é o melhor. Ao melhor.}
{262}{}{}
{1262}{}{!!!}
{263}{}{Yeeeaaaaahhhhh!}
{264}{}{:: scream :: :: bellow :: :: scream ::}
{265}{}{}
{1265}{}{ É o melhor campeão de boxe que já vi.}
{266}{}{}
{1266}{}{, Você é a mulher mais dura do mundo!}
{267}{}{Você é mais difícil que Robbin 'Givens!}
{268}{}{}
{1268}{}{, Você é a mulher!}
{269}{}{}
{1269}{}{ É realmente inteligente também. Ela realmente sabe como machucar alguém.}
{270}{}{}
{1270}{}{ Atenciosamente sobre seus fãs. Ela não os mata como os outros boxeadores.}
{271}{}{Eu ouço}
{1271}{}{ Era quase um desconhecido, fora dos resíduos, antes de entrar na caixa em New Reno. Ela é tão misteriosa!}

# 3. FLOAT DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{280}{}{Beijo de sorte?}
{281}{}{}
{1281}{}{, você é o cara!}
{282}{}{}
{1282}{}{ É muito bonito.}
{283}{}{}
{1283}{}{ Tem a construção de um tanque!}
{284}{}{}
{1284}{}{ É realmente inteligente também. Ele realmente sabe como machucar alguém.}
{285}{}{}
{1285}{}{ Se preocupa com seus fãs. Ele não os mata como os outros boxeadores.}
{286}{}{Eu ouço}
{1286}{}{ Era quase um desconhecido, fresco fora dos resíduos, antes de chegar à caixa em New Reno. Misterioso! Mortal!}
{287}{}{Ohmódodo!}
{1287}{}{! Assine um autógrafo!}
{288}{}{Punch me! Punch me! Eu quero dizer aos meus filhos que você me perfurou!}
{289}{}{Você é o melhor}
{1289}{}{! Dê-lhes o inferno!}
{290}{}{Mate ele,}
{1290}{}{!}
{291}{}{Você é o melhor,}
{1291}{}{!}
{292}{}{Pegue-os,}
{1292}{}{!}
{293}{}{sim! Dê isso a ele!}
{294}{}{}
{1294}{}{, você é o melhor. Ao melhor.}
{295}{}{}
{1295}{}{!!!}
{296}{}{Aiiiieeeeeee!}
{297}{}{:: screech :: :: screech ::}
{298}{}{}
{1298}{}{ É o melhor campeão de boxe que já vi.}
{299}{}{}
{1299}{}{, Você é a mulher mais dura do mundo!}
{300}{}{Você é mais difícil que Robbin 'Givens!}
{301}{}{}
{1301}{}{, Você é a mulher!}
{302}{}{}
{1302}{}{ É realmente inteligente também. Ela realmente sabe como machucar alguém.}
{303}{}{}
{1303}{}{ Atenciosamente sobre seus fãs. Ela não os mata como os outros boxeadores.}
{304}{}{Eu ouço}
{1304}{}{ Era quase um desconhecido, fora dos resíduos, antes de entrar na caixa em New Reno. Ela é tão misteriosa!}

# 4. CLICK DIALOGUES [FAN=FEMALE OR MALE, PC NOT A PRIZEFIGHTER]
{320}{}{ Vai matar qualquer um que se interponha em seu caminho!}
{321}{}{ é o melhor. Ao melhor.}
{322}{}{!!!}
{323}{}{ É o homem!}
{324}{}{ É o melhor campeão de boxe que já vi.}
{325}{}{ É realmente inteligente também. Ele realmente sabe como machucar alguém.}
{326}{}{ Se preocupa com seus fãs. Ele não os mata como os outros boxeadores.}
{327}{}{ É muito bonito.}
{328}{}{ É cuidar e nutrir. Foi o que ele me disse na noite passada.}

# 5. CLICK DIALOGUES [FAN=MALE, PC = PRIZEFIGHTER]
{350}{}{}
{1350}{}{, você é o cara!}
{351}{}{Eu tenho um pouco de suor em uma jarra em casa.}
{352}{}{Ohmódodo!}
{1352}{}{! Assine um autógrafo!}
{353}{}{Punch me! Punch me! Eu quero dizer aos meus filhos que você me perfurou!}
{354}{}{Você é o melhor}
{1354}{}{! Dê-lhes o inferno!}
{355}{}{Você é o melhor,}
{1355}{}{!}
{356}{}{Vá buscá-los}
{1356}{}{!}
{357}{}{}
{1357}{}{, você é o melhor. Ao melhor.}
{358}{}{}
{1358}{}{!!!}
{359}{}{Yeeeaaaaahhhhh!}
{360}{}{}
{1360}{}{, Você é o melhor campeão de boxe que já vi.}
{361}{}{}
{1361}{}{, Você realmente sabe como machucar alguém.}
{362}{}{}
{1362}{}{, Você realmente se preocupa com seus fãs. Você não os mata como os outros boxeadores.}
{363}{}{Eu ouçoyou were an unknown, fresh out of the wastes, before you came to box in New Reno. Where are you from?}
{364}{}{}
{1364}{}{, Você é a mulher mais dura do mundo!}
{365}{}{Você é mais difícil que Robbin 'Givens!}
{366}{}{}
{1366}{}{, Você é a mulher!}

# 6. CLICK DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{380}{}{Beijo de sorte?}
{381}{}{}
{1381}{}{, você é o cara!}
{382}{}{}
{1382}{}{, Você é tão bonito.}
{383}{}{:: Parece fraco quando você fala com ela ::}
{384}{}{Eu tenho um pouco de suor em uma jarra em casa.}
{385}{}{Ohmódodo!}
{1385}{}{! Assine um autógrafo!}
{386}{}{Punch me! Punch me! Eu quero dizer aos meus filhos que você me perfurou!}
{387}{}{Você é o melhor}
{1387}{}{! Dê-lhes o inferno!}
{388}{}{Mate ele,!}
{1388}{}{!}
{389}{}{Você é o melhor,}
{1389}{}{!}
{390}{}{Pegue-os,}
{1390}{}{!}
{391}{}{.}
{1391}{}{, você é o melhor. Ao melhor.}
{392}{}{}
{1392}{}{!!!}
{393}{}{Aiiiieeeeeee!}
{394}{}{}
{1394}{}{, Você é o melhor campeão de boxe que já vi.}
{395}{}{}
{1395}{}{, Você realmente sabe como machucar alguém.}
{396}{}{}
{1396}{}{, Você realmente se preocupa com seus fãs. Você não os mata como os outros boxeadores.}
{397}{}{Eu ouçoyou were an unknown, fresh out of the wastes, before you came to box in New Reno. Where are you from?}
{398}{}{}
{1398}{}{, Você é a mulher mais dura do mundo!}
{399}{}{Você é mais difícil que Robbin 'Givens!}
{400}{}{}
{1400}{}{, Você é a mulher!}
