# quick look
{100}{}{Você vê um boxeador.}

# examine
# black
{150}{}{Você vê um homem preto pesadamente musculoso. Ele parece ter acabado de trabalhar.}
{151}{}{Você vê um enorme homem negro. E eu quero dizer ENORME.}
{152}{}{Ele parece ter acabado de trabalhar.}
{153}{}{Você quase confundi-lo com uma pequena montanha.}
{154}{}{Ele é enorme. Huuuuuge.}
{155}{}{Ele está sorrindo para você sem dentes.}
{156}{}{Ele parece ter acabado de trabalhar.}
{157}{}{Você quase confundi-lo com uma pequena montanha.}
{158}{}{Ele é enorme. Huuuuuge.}
{159}{}{Ele está sorrindo para você sem dentes.}
# generic
{160}{}{Ele está batendo contra um oponente invisível e grunhindo ameaças ao ar.}
{161}{}{Parece momentaneamente confuso, como se tivesse esquecido de quem ele era, então
 Sorri e arranha a cabeça.}
{162}{}{Ele está agachando.}
# white
{163}{}{Você vê um grande homem branco. Seus braços parecem troncos de árvores.}
{164}{}{Você vê um homem branco pesadamente musculoso. Ele está flexionando e grunhindo para si mesmo.}
{165}{}{Você vê um homem branco pesadamente musculoso. Ele está olhando sua cabeça como uma bolsa de pancadas.}
{166}{}{Ele está batendo contra um oponente invisível e grunhindo ameaças ao ar.}
{167}{}{Parece momentaneamente confuso, como se tivesse esquecido de quem ele era, então
 Sorri e arranha a cabeça.}
{168}{}{Ele está olhando sua cabeça como uma bolsa de pancadas.}

# random float
{200}{}{Hnffff}
{201}{}{Hnrggg}
{202}{}{:: Flexões ::}

# player has power armor or is prizefighter
{203}{}{:: O boxeador olha para você com olhos amedrontados ::}
{204}{}{Yessur?}
{205}{}{Ken eu empresto uma soma de teef?}
{206}{}{Você precisa de um observador?}
{207}{}{Uh-huh.}
{208}{}{:: Nods estupidamente em tudo o que você diz ::}
{209}{}{Grande pershun. Eu pequeno.}
{210}{}{U duro. Eu é fraco.}
{211}{}{Estou com fome.}

# talk female
{212}{}{Eu não gosto de falar.}
{213}{}{Você cheira guuud.}
{214}{}{Você cheira como mamãe.}
{215}{}{Basta falar. Hora de dormir.}
# talk shared
{216}{}{:: Sorrisos sem dente ::}
{217}{}{:: Scratches self ::}
{218}{}{:: Flexões ::}
{219}{}{Grunhido}
# talk male
{220}{}{Você luta comigo?}
{221}{}{Fique irritado ficando irritado.}
{222}{}{Fow-cuss, Fow-cuss.}
{223}{}{Obter critikal.}
{224}{}{Ligue além dessa merda.}
{225}{}{Eu preciso de um observador.}
{226}{}{Você pessoa pequena.}
{227}{}{Eu não gosto de falar.}

# boxing boxers messages

# punch
# hit noise
{300}{}{Ernhhh}
{301}{}{Unfff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooof}

# dodge
{310}{}{Muito devagar!}
{311}{}{Não é o rosto!}
{312}{}{Você socos como minha avó!}
{313}{}{Sem bater abaixo do cinto!}
{314}{}{Você não está mal.}
{315}{}{Dat tudo que você tem?}

# knock down
{320}{}{E fique abaixo!}
{321}{}{Você foi derrubado da foda!}
{322}{}{Quem é seu pai?}
{323}{}{Se ele morrer, ele morre.}

{330}{}{Coulda foi um concorrente!}
{331}{}{Como poderia um ... geggghhh ...}
{332}{}{* Huuuuurrrrllllll *}
{333}{}{Ooo, ursos de cuidado ...}
{334}{}{Acho que vou ficar aqui por um momento.}
{335}{}{Sem dor, sem dor, sem dor ...}

# punching
{340}{}{Coma isso!}
{341}{}{Você quer um pouco disso ?!}
{342}{}{Cadela!}
{343}{}{Agora você é meu.}
{344}{}{Eu como boinas verdes para o café da manhã.}
{345}{}{Haadookin.}
{346}{}{Agora você morre.}
{347}{}{SUPER ... NUCLEAR ... TORNADO ... FIST ...}

# taunt
{350}{}{Adrian! Adrian!}
{351}{}{Você irá cair!}
{352}{}{Faça você uma cadela ...}
{353}{}{Eu devo quebrar você.}
{354}{}{Você está lutando como um vagabundo!}
{355}{}{Você não tem coragem!}
{356}{}{Você é um vagabundo! Um vagabundo!}
{357}{}{Vou vencê-lo como um cachorro ...}

# corner
{360}{}{Não será uma revanche!}
{361}{}{Bata como uma borboleta ...}
{362}{}{Mantenha as mãos para cima ...}
{363}{}{Mantenha-se afiado!}
{364}{}{Lute após essa merda!}
{365}{}{Seja crítico!}
{366}{}{Me corte, Mick.}
{367}{}{Lembre-se, coloque o jab!}
{368}{}{Eu vejo três deles!}
