# quick look
{100}{}{Você vê um patrono do cassino.}

# examines
{150}{}{Você vê um dos patrocinadores do cassino. Ele parece cansado.}
{151}{}{Você vê um dos patrocinadores do cassino. Ele tinha um brilho dourado em seus olhos.}
{152}{}{Você vê um dos patrocinadores do cassino. Ele está colocando o rosto em suas mãos.}
{153}{}{Você vê um dos patrocinadores do cassino. Ele parece um pouco irritado.}
{154}{}{Você vê um dos patrocinadores do cassino. Ele lhe dá uma piscadinha larga, depois cambaleia.}
{155}{}{Você vê um dos patrocinadores do cassino. Ele está tentando chamar a atenção da garçonete.}
{156}{}{Você vê um dos patrocinadores do cassino. Ela parece cansada.}
{157}{}{Você vê um dos patrocinadores do cassino. Ela tem um brilho dourado em seus olhos.}
{158}{}{Você vê um dos patrocinadores do cassino. Ela está agarrando o rosto nas mãos.}
{159}{}{Você vê um dos patrocinadores do cassino. Ela parece um pouco embriagada.}
{160}{}{Você vê um dos patrocinadores do cassino. Ela dá uma piscadinha larga, então se afunda.}
{161}{}{Você vê um dos patrocinadores do cassino. Ela está tentando chamar a atenção do garçom.}

# float
{200}{}{:: Claps ::}
{201}{}{::Felicidades::}
{202}{}{Maneira de queimar os bastardos do Enclave! Maneira de ir!}
{203}{}{Maneira de esmagar o Enclave,}
{204}{}{Parabéns em pisar o Enclave,}
{205}{}{Parabéns em pisar o Enclave,}
{206}{}{Uh-oh. Saia do caminho.}
{207}{}{Apenas olhando para ele ... ela ... é ... * qualquer coisa que seja me dá arrepios.}
{208}{}{Acha que essa coisa está procurando alguém?}
{209}{}{É a fúria do inferno dada carne. Uh, embaixo da armadura, isso é.}
{210}{}{Fique fora do caminho dessa coisa.}
{211}{}{Fale sobre perigoso ...}
{212}{}{*Gole*}
{213}{}{Eu acho que o Sr. Roboto cara estava me digitalizando.}
{214}{}{Eu acho que o tanque ambulante apenas me deu o olhar da morte. Estou fora daqui.}
{215}{}{Ouvi dizer que esta coisa fragmentou três assassinos apenas ontem.}
{216}{}{Apenas olhar para ele me dá arrepios.}
{217}{}{Pensa que ele está procurando alguém?}
{218}{}{Fique longe do caminho desse homem.}
{219}{}{Eu acho que ele estava olhando para mim.}
{220}{}{Acho que ele me deu o olhar da morte. Estou fora daqui.}
{221}{}{Ouvi dizer que derrubou três assassinos ontem.}
{222}{}{Uh-oh. Saia do caminho.}
{223}{}{É a fúria do inferno dada carne.}
{224}{}{Fale sobre perigoso ...}
{225}{}{*Gole*}
{226}{}{La Femme Nikita, depois alguns.}
{227}{}{Apenas olhar para ela me dá arrepios.}
{228}{}{Acha que ela está procurando alguém?}
{229}{}{Eu acho que ela estava olhando para mim.}
{230}{}{Eu acho que ela apenas me deu o olhar da morte. Estou fora daqui.}
{231}{}{Ouvi dizer que ela abateu três assassinos apenas ontem.}
{232}{}{Que burro! Uh, burro ruim, isso é.}
{233}{}{Você não parece tão difícil, Sr. Prizefighter.}
{234}{}{Recebi 20 fichas montando sobre você!}
{235}{}{Ei, campeão! Essa última luta foi ótima!}
{236}{}{Viu você bater no ringue. Maldito bom gancho direito você joga.}
{237}{}{Você vai pegar o outono? Tenho 30 fichas montadas em você.}
{238}{}{Quanto você bancou?}
{239}{}{Onde você trabalha fora?}
{240}{}{Cuidado com o Masticador. Ele tem gosto de ouvidos.}
{241}{}{Eu pegaria uma bebida se eu não tivesse jogado todo meu dinheiro apostando em seu oponente.}
{242}{}{Você não parece tão difícil, Ms. Left Hook.}
{243}{}{Posso ver seus músculos abdominais flexionar?}
{244}{}{Uau. Dê uma olhada.}
{245}{}{Você olharia * que *?}
{246}{}{:: Boca a palavra 'maldita'. ::}
{247}{}{Eu sabia que deveria ter me afogado hoje.}
{248}{}{Venha conversar comigo por um segundo, melharucos.}
{249}{}{Tribais pegou-lhes tits! Droga!}
{250}{}{Confira a prateleira na tribal.}
{251}{}{Que há a principal galinha do meu rebanho.}
{252}{}{Eu me banharia com aquela mulher.}
{253}{}{Eu tenho sua mãe lode aqui.}
{254}{}{Agite-o!}
{255}{}{Trabalhe!}
{256}{}{:: Whistles ::}
{257}{}{As pernas vão todo o caminho?}
{258}{}{Daaaaaamn.}
{259}{}{Você tem batatas fritas para ir com aquela vibração, linda?}
{260}{}{Talvez ela dance hoje à noite.}
{261}{}{Você viu seu último filme? Vermelho quente, homem, vermelho QUENTE.}
{262}{}{Com licença. Eu tenho que ir ao banheiro e er, pentear meu cabelo por um segundo.}
{263}{}{Gostaria de ser sua calcinha.}
{264}{}{Gostaria de ser sua cueca.}
{265}{}{Gostaria de cheirar seus calções.}
{266}{}{Essa é uma cadela foxy.}
{267}{}{Droga. Todos eles curvam e eu sem freios.}
{268}{}{Bem, hellloooo stud.}
{269}{}{Um garanhão como você na necessidade de uma sela? Estou à vontade amanhã à noite.}
{270}{}{O que você faz depois, marinheiro?}
{271}{}{Posso sentir seus músculos?}
{272}{}{Por que você não desmaia quando você se erige?}
{273}{}{Quer ir ao meu lugar para tomar uma bebida?}
{274}{}{Quero comer o jantar no peito.}
{275}{}{Precisa de um parceiro para o seu próximo filme?}
{276}{}{:: Olha no seu bíceps. ::}
{277}{}{É algum tipo de slot machine que o acompanha?}
{278}{}{Isso é uma máquina robo-slot?}
{279}{}{Seu robô faz truques? Uh ... truques de mágica, quero dizer.}
{280}{}{Isso parece mais louco que as raposas das galinhas.}
{281}{}{Enrole os ossos.}
{282}{}{Baby precisa de um novo par de sapatos ...}
{283}{}{Damn lowrolling tourist ...}
{284}{}{Droga! Eu estava acima * 53 * chips, então ...}
{285}{}{De toda a sorte podre ...}
{286}{}{Tão perto!}
{287}{}{Estou fazendo o banco.}
{288}{}{Me? Estou fazendo o banco. Watch me go.}
{289}{}{House estava contra mim.}
{290}{}{Fortune's contra mim.}
{291}{}{Lady Luck, não me deixe agora.}
{292}{}{A casa está comigo.}
{293}{}{Entre as dicas e essas explosões de gastos embriagados ...}
{294}{}{Continue apostando assim, e você vai ligar para o Golgotha   em casa ...}
{295}{}{Empregada de mesa, outra bebida!}
{296}{}{Garçom, outra bebida!}
{297}{}{Essas bebidas sabem ... estranho.}
{298}{}{Tenho a febre!}
{299}{}{Todos os meus chips já foram?}
{300}{}{A sorte é uma cadela inconstante, e também é minha sogra.}
{301}{}{Mais escravos na cidade recentemente.}
{302}{}{Imagine o que acontece nos estábulos fora da cidade.}
{303}{}{Outra briga pode começar em breve.}
{304}{}{Malditas cruzadas por todo o lugar ...}
{305}{}{Ótimo, outro rolo baixo.}
{306}{}{Eu sou tão dinheiro.}
{307}{}{Eu vou dormir quando eu estiver morto.}
{308}{}{Cara, eu tenho que mijar. Meus dentes estão nadando.}
{309}{}{Cara, eu tenho que drenar a cobra.}
{310}{}{Droga, eles vão deixar alguém aqui.}
{311}{}{Vamos 7!}
{312}{}{Você tem dificuldade, amor.}
{313}{}{Quem é o grande vencedor esta noite? Mikey!}
{314}{}{Não cague ... vamos lá ...}
{315}{}{Eu tenho que "jorrar" ... se você sabe o que quero dizer.}
{316}{}{Isso é TAL besteira.}
{317}{}{Eu só perdi 60 fichas. Nos primeiros cinco minutos, isso é.}
{318}{}{Red 23! Red 23! Vamos ... vermelho 23 ...}
{319}{}{50 fichas no preto 15 ...}
{320}{}{Em volta e volta, vai ... onde pára, ninguém sabe ...}
{321}{}{Maneira de queimar os bastardos do Enclave! Maneira de ir!}
{322}{}{Eu sempre soube que o presidente queria matar todos nós.}
{323}{}{O presidente estava vivo? Quando foi a última eleição?}
{324}{}{Destruiu o Enclave, hein? Bem, deixe-me comprar uma bebida.}
{325}{}{Maneira de esmagar o Enclave,}
{326}{}{Com a destruição do Enclave, você fez deste cassino um lugar melhor para meus filhos. Como posso te agradecer?}
{327}{}{O Enclave nunca confundiu comigo, mas fico feliz por terem ido embora.}
{328}{}{Não posso acreditar que o Enclave ainda estava lutando contra a guerra depois de todo esse tempo. Idiotas.}
{329}{}{Senti um grande distúrbio ... como se uma centena de bastardos malignos em uma torre de petróleo gritasse de terror
 e de repente foram silenciados. Estranho.}
{330}{}{Parabéns em pisar o Enclave,}
{331}{}{Parabéns em pisar o Enclave,}
{332}{}{Você está procurando seu irmão Robby? Você sabe, o Robot? Ah, nunca perca.}
{333}{}{Desculpe, eu estava no seu caminho? Vou sair da cidade.}
{334}{}{Desculpe, estava respirando o seu ar? Eu irei parar.}
{335}{}{Eu não sabia que eles faziam as portas em seu tamanho.}
{336}{}{:: Knocks on armor :: Alguém lá dentro?}
{337}{}{"Perigo, Will Robinson! Perigo, Will Robinson! ' Heh heh. Uh ... apenas uma piada.}
{338}{}{Armadura de Niiiiice. Tem ar condicionado?}
{339}{}{Você não fica quente lá?}
{340}{}{Posso esfregar esses dados contra sua armadura por sorte?}
{341}{}{Perder seu coração, homem de lata?}
{342}{}{Uh, olá, senhor ... ou senhora ... ou seja o que for.}
{343}{}{Dê meus cumprimentos a quem lhe deu essa armadura.}
{344}{}{Qualquer coisa errada, senhor ... senhora ... o que quer que seja?}
{345}{}{Você é um dos novos instigadores? Ou algum novo jogo de arcade a pé?}
{346}{}{Não, não vou deixar as articulações.}
{347}{}{Sua armadura pode transformar-se em um jato e voar ao redor? Apenas curioso.}
{348}{}{Sim, sim, "clank-whirrr-clank" para você, também.}
{349}{}{Se você acha que a armadura me intimida, você está certo.}
{350}{}{Você deve ser um daqueles consoles de videogame anteriores à guerra.}
{351}{}{Olhe, por favor ... Eu não quero nenhum problema. Estou na cidade para o dia.}
{352}{}{Olhe, por favor ... Eu não quero nenhum problema.}
{353}{}{Desculpe, eu estava no seu caminho? Vou sair da cidade.}
{354}{}{Desculpe, estava respirando o seu ar? Eu irei parar.}
{355}{}{Dê meus cumprimentos ao seu chefe.}
{356}{}{Uh ... * gulp * ... qualquer coisa errada?}
{357}{}{Olhe, por favor ... Eu não quero nenhum problema. Estou na cidade para o dia.}
{358}{}{Olhe, por favor ... Eu não quero nenhum problema.}
{359}{}{Você está vendendo?}
{360}{}{Posso comprar suas roupas? Quero dizer, agora mesmo?}
{361}{}{Eu sabia que deveria ter me afogado hoje.}
{362}{}{Venha conversar comigo por um segundo, melharucos.}
{363}{}{Vamos, lábios de mel ... caminhe comigo.}
{364}{}{Nimble little minx, aincha?}
{365}{}{Eu me banharia por você.}
{366}{}{Eu tenho sua mãe lode aqui.}
{367}{}{As pernas vão todo o caminho?}
{368}{}{Você vai dançar esta noite?}
{369}{}{Com licença. Eu tenho que ir ao banheiro e er, pentear meu cabelo por um segundo.}
{370}{}{Eu gostaria de ser sua cueca.}
{371}{}{Gostaria de cheirar seus calções.}
{372}{}{Você é uma cadela foxy.}
{373}{}{Aperte-me se eu estiver errado, querido, mas você não quer me beijar?}
{374}{}{Droga. Todos eles curvam e eu sem freios.}
{375}{}{Saiba o que ficaria bem com você? Eu.}
{376}{}{Sua calcinha pode não ser a melhor coisa na terra, mas eles estão muito perto disso.}

{503}{}{!}
{504}{}{! Você chuta a bunda! Você chuta ASS!}
{505}{}{! Você é tão DINHEIRO!}
{625}{}{!}
{630}{}{! Você chuta a bunda! Você chuta ASS!}
{631}{}{! Você é tão DINHEIRO!}
