# QUICK LOOK
{100}{}{Você vê um bouncer de cassino.}

# LOOK
{150}{}{Você vê um bouncer de cassino. He's HUGE.}
{151}{}{Você vê um bouncer de cassino. He looks big. And angry.}
{152}{}{Você vê um bouncer de cassino. He's looking at you suspiciously.}
{153}{}{Você vê um bouncer de cassino. You thought only mutants got that big.}

# 1. FLOAT DIALOGUE: POWER ARMOR
{200}{}{Uh ... você precisará remover essa armadura ... na verdade, nunca perca.}
{201}{}{Uh, senhor ... ou senhora ... você precisará remover essa armadura ... uh, nunca perca.}
{202}{}{Senhor ... senhora ... você não pode usar isso no cassino ... uh, a menos que você realmente queira. Deixa pra lá.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK
{205}{}{Uh, por que você está se esgueirando, senhor?}
{206}{}{Uh, você está disfarçado, senhor?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK
{210}{}{Uh, por que você está se esgueirando, senhora?}
{211}{}{Uh, você está embutido, senhora?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT
{215}{}{Boa noite senhor.}
{216}{}{Noite, senhor.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT
{220}{}{Boa noite, senhora.}
{221}{}{Noite, senhora.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO
{225}{}{Bom Dia senhor.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO
{230}{}{Bom dia, senhora.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO
{235}{}{Amigo, você está entrando no casino errado.}
{236}{}{É melhor você sair. Agora.}
{237}{}{Este não é o lugar para jogar com sua vida. É melhor você sair.}

# 9. FLOAT DIALOGUE: FEMALE, MADE MAN, NOT SAME CASINO
{240}{}{Cadela, você está entrando no cassino errado.}
{241}{}{É melhor você sair. Agora.}
{242}{}{Este não é o lugar para jogar com sua vida. É melhor você sair.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED)
{245}{}{Senhor, desculpe, você terá que proteger essa arma.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED)
{250}{}{Senhor, desculpe, você terá que proteger essa arma.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED)
{255}{}{Querida, desculpe, não pode levar armas ao cassino. Heh-heh ... você é bastante mortal como está.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK)
{260}{}{Querida, com um corpo como esse, você não poderá se esgueirar em qualquer lugar.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED)
{265}{}{Tribal, é melhor você proteger essa arma agora.}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK)
{270}{}{Tribal, é melhor você parar de se esconder por causa da merda agora.}

# 16. MYRON, MORDINO
{275}{}{Ei, ei ... Myron! Não foi visto fora do laboratório há muito tempo.}
{276}{}{Você está aqui para experimentar algumas das novas mercadorias, Myron?}
{277}{}{Ei! Entre, Myron.}

# 17. MARCUS
{280}{}{Não há mutantes. Ele espera lá fora.}
{281}{}{Mantenha seu animal de estimação fora, mutante-amante.}
{282}{}{Esse tipo de mutante não é permitido aqui.}

# 18. ROBOBRAIN
{285}{}{Sem droides.}
{286}{}{Nós não servimos droids.}
{287}{}{Sem droides. They wait outside.}

# 19. CLICK DIALOGUES: MADE MAN, SAME CASINO
{290}{}{Bem-vindo ao cassino, senhor.}
{291}{}{Como os tópicos, senhor.}
{292}{}{Não há problemas hoje, senhor.}
{293}{}{Uh, há um problema, senhor? Ou apenas visitando?}
{294}{}{Tommy the Balls envia seus cumprimentos.}
{295}{}{Dê uma boa palavra com o chefe para mim?}
{296}{}{Bem-vindo ao cassino, senhora.}
{297}{}{Como os fios, senhora.}
{298}{}{Não há problemas hoje, senhora.}
{299}{}{Uh, tem algum problema, senhora? Ou apenas visitando?}

# 21. CLICK DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR
{310}{}{Bem-vindo ao cassino, senhor.}
{311}{}{Como os tópicos, senhor.}
{312}{}{Quando é a sua próxima partida, senhor?}

# 22. CLICK DIALOGUE: FEMALE, PRIZEFIGHTER
{315}{}{Bem-vindo ao cassino, senhora.}
{316}{}{Como os fios, senhora.}
{317}{}{Quando é a sua próxima partida, senhora?}

# 24. CLICK DIALOGUE: FEMALE, PORN STAR
{320}{}{Quando você vai parar e me ver?}
{321}{}{Ei, seja bem vindo ao cassino! Você vai dançar esta noite?}
{322}{}{Parecendo mortal, querido.}
{323}{}{Lady Luck ficará com ciúmes, você continua vindo aqui.}
{324}{}{Ouço Tommy the Balls quer dar uma seleção privada.}

# 25. CLICK DIALOGUE: MALE, NO REP
{330}{}{Casino está dentro. Não fale comigo.}
{331}{}{O INTERIOR DO BANHEIRO. DENTRO. Tribos estúpidos.}

# 26. CLICK DIALOGUE: FEMALE, NO REP (CUTE/UGLY)
{335}{}{Vá se menear com outra pessoa, tribal.}
{336}{}{O INTERIOR DO BANHEIRO. DENTRO. Tribos estúpidos.}
{337}{}{Eu não estou procurando nenhuma bunda tribal agora. Obter.}
{338}{}{Blow, dogface. Estou trabalhando.}
{339}{}{Vá lidar com alguém mais bêbado do que eu, cara de cachorro.}

# 28. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE
{345}{}{Eu não estou interessado em conversar enquanto estava de plantão, mas estou feliz que você tenha chutado o traseiro do Enclave.}
{346}{}{Está bem, tribal. Descanse de salvar o mundo e se divertir.}
{347}{}{Ouvi dizer que Tommy the Balls está procurando por você. Cuidado.}

# 29. CLICK DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE
{350}{}{Você conseguiu algumas bolas sérias para tirar o Enclave assim.}
{351}{}{Eu acho que tirar o Enclave como você fez mais bolas do que todos em New Reno combinados.}
{352}{}{Busting the Enclave faz com que você seja quase um badass como Tommy the Balls.}
{353}{}{Eu não estou interessado em conversar enquanto estava de plantão, mas estou feliz que você tenha chutado o traseiro do Enclave.}
{354}{}{Está bem, tribal. Descanse de salvar o mundo e se divertir.}
{355}{}{Você conseguiu algumas bolas sérias para tirar o Enclave assim. Well, not BALLS, per se, but you know what I mean.}
{356}{}{Honey, Eu acho que tirar o Enclave como você fez mais bolas do que todos em New Reno combinados.}
{357}{}{Acha que você poderia ir para um cara como eu? Quero dizer, eu não sou um tipo de economia mundial, mas eu sou muito forte e tenho um bom coração.}

# 30. FLOAT/CLICK DIALOGUE: LENNY
{360}{}{Que ghoul vem aqui, ele vai morrer duas vezes.}
{361}{}{O ghong fica afastado.}
{362}{}{Nós não deixamos ghouls aqui. Leve-o de volta a Gecko, onde seu tipo pertence.}
