# 0. QUICK LOOK
{100}{}{Você vê Chris Wright.}

# 0. LOOK
{150}{}{Você vê um jovem alto com um mohawk. Ele está usando muitas correntes e couro.}
{151}{}{Você vê Chris Wright.}
{152}{}{Você vê Chris Wright. He looks bored out of his skull.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Ei!}
{201}{}{Cheio,}
{202}{}{Rock on,}
{203}{}{::Felicidades::}
{204}{}{:: Claps ::}
{205}{}{:: Whistles ::}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{215}{}{Como você vai ao banheiro com essa coisa?}

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Howdy,}
{221}{}{Damn hot, innit,}
{222}{}{Howdy,}

# 4. FLOAT/CLICK (DAD IS DEAD) (WTG)
{230}{}{Ainda não posso acreditar que o pai está morto. Há tanto que eu queria dizer a ele ...}

# 5. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM] (WTG)
{235}{}{Não me chateies.}
{236}{}{Não me chateies. I mean it.}
{237}{}{Não tenho nada para lhe dizer.}

# 6. INTRO (NORMAL) (WTG)
{245}{}{Sim?}
{246}{}{Ei!How's it going, }
{1246}{}{? Todo mundo tratando você bem? Qualquer coisa que você precise?}
{247}{}{Ei, você recebeu meus agradecimentos por descobrir quem matou Richard,}
{248}{}{. Eu te devo grande, e a família Wright sempre paga suas dívidas. O que posso fazer para você?}
{249}{}{Mattah. O homem é Mattah!}
{250}{}{Hoobajuube}
{251}{}{Afastar-se}
{252}{}{Quem é Você?}
{253}{}{Na verdade sim. Estou à procura de trabalho. A contratação da Family Wright?}
{254}{}{Digamos que eu encontrei sua mãe.}
{255}{}{Você pode me falar sobre Richard?}
{256}{}{Nada, obrigado. Desculpe incomodá-lo.}

# 7.  RETARD (6)
{265}{}{Piss off, retardar. Não tenho tempo para fazer linguagem de sinais com você.}
{266}{}{Afastar-se}

# 8.  WHO ARE YOU? (6)
{275}{}{Eu sou Chris. Chris Wright. Da Família Wright. Ainda bem que você perguntou?}
{276}{}{Na verdade sim. Estou à procura de trabalho. A contratação da Family Wright?}
{277}{}{Família Wright? Quem é aquele?}
{278}{}{Chris Wright, huh? Digamos que eu encontrei sua mãe.}
{279}{}{Você pode me dizer o que aconteceu com seu irmão Richard?}
{280}{}{Na verdade não. Desculpe incomodá-lo.}

# 9. FAMILY WRIGHT? WHO'S THAT? (8, 10, 12)
{290}{}{Você não é ouvido sobre a família Wright? Vocês já estiveram no deserto por muito tempo. Família Wright
 É a maior família de crimes em Reno. Vamos governar esta cidade.}
{291}{}{Mesmo? Parece que a família Wright possui todas as cartas. Eles estão contratando?}
{292}{}{Na verdade, tive a impressão de que eram uma das famílias mais fracas ... Quero dizer, eles
 Apenas lidam com álcool, eles não têm cassino ou comércio químico, e seus números são muito menores do que
 Outras famílias.}
{293}{}{Falando em família, encontrei sua mãe.}
{294}{}{Você pode me dizer o que aconteceu com seu irmão Richard?}
{295}{}{Mesmo? Quão interessante ... bem, olha, eu tenho que ir.}

# 10. QUESTIONS (15, 16, 17, 18, 19, 20, 22, 25, 26, 28)
{305}{}{Como o quê?}
{306}{}{Você pode me falar sobre Family Wright?}
{307}{}{A contratação da Family Wright?}
{308}{}{Eu encontrei sua mãe há pouco tempo. Boa moça.}
{309}{}{Você pode me dizer o que aconteceu com seu irmão Richard?}
{310}{}{Não, não há outras perguntas. É melhor eu ir.}

# 11. INTRO (SLAVER) (WTG)
{315}{}{(O jovem se volta para você, olha você para cima e para baixo. Seus olhos param na marca em sua testa.) Bem, agora.
 (Ele zombou, então cuspiu nos pés.) Por que você não se faz útil e lava isso, escravidão?}
{316}{}{(O jovem se volta para você, olha você para cima e para baixo.) Bem, agora. (Ele zombou, então cuspiu nos pés.) Por que você não
 Faça-se útil e lamba isso, você pedaço de [FA] dogshit?}
{317}{}{Chute com a bota que ele cuspiu.}
{318}{}{Afastar-se }
{319}{}{Deixe-o sozinho e vá embora. Desta vez.}

# 12. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 8, 9, 10)
{325}{}{Bem ... Eu ... quero dizer, a família Wright ... minha família ... pode ter uma abertura. Não estou prometendo nada, mas vou para a mansão
 Ao sul daqui, encontre meu irmão Keith e diga-lhe que eu enviei você. Nome Chris. Chris Wright.}
{326}{}{Uh, Família Wright? Quem é aquele?}
{327}{}{Wright, hein? Eu encontrei sua mãe.}
{328}{}{Você pode me dizer o que aconteceu com seu irmão Richard?}
{329}{}{Obrigado. Eu vou falar com ele.}

# 13. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 8, 9, 10)
{335}{}{Naw, não consigo pensar em nenhum lugar que esteja contratando. A maioria das famílias da cidade é bastante estreita.}
{336}{}{Tudo bem então.}

# 14. I RAN INTO YOUR MOM (NORMAL) (6, 9, 10, 11, 12)
{345}{}{Oh, ótimo. Ela lhe deu um discurso?}
{346}{}{Um pouco. Você não gosta da sua mãe?}
{347}{}{Não. Ela costuma?}
{348}{}{Na verdade não. Olha, é melhor eu ir.}

# 15. I RAN INTO YOUR MOM (INSULT) (9, 16)
{355}{}{Que uma * piada? * Em caso afirmativo, muito bem, perdeu a marca engraçada por uma milha. Você está tentando começar algo com Família
 Wright, cara sábio?}
{356}{}{Comece alguma coisa? Não, apenas * termine *.}
{357}{}{Não me desculpe. Eu não quis dizer isso assim. Olha, eu tive algumas outras perguntas ...}
{358}{}{Não, não é nada. Acho que é melhor eu ir.}

# 16. DO YOU NOT LIKE YOUR MOM? (14)
{365}{}{Ela simplesmente não presta atenção ao que está acontecendo ao seu redor. Eu a amo todo, mas às vezes, ela é tão cega como uma mula.}
{366}{}{Bem, não há muito tempo, ela cobrou o nosso álcool ainda aqui e arruinou o lugar, destruindo nossa safra inteira. Eu a amo tudo, mas às vezes ela é tão cega como uma mula.}
{367}{}{Heh heh. E ela se parece com uma, também.}
{368}{}{Cego? O que você quer dizer?}
{369}{}{Oh. Tive algumas outras questões ...}
{370}{}{Eu suponho. Olha, é melhor eu ir.}

# 17. WHAT DO YOU MEAN? (16)
{380}{}{Ela volta e prega tudo sobre pecar e coisas, mas ela nem sabe realmente o que o pai faz.
 Ou isso, ou ela ignora.}
{381}{}{O que o seu pai faz?}
{382}{}{Hmmmm. Diga, eu tive algumas outras perguntas ...}
{383}{}{Interessante. Bem, eu tenho que ir.}

# 18. WHAT DOES YOUR DAD DO? (17)
{390}{}{Faz álcool, corre armas, esfrega pessoas que fodem com ele ... coisas familiares típicas. Você ficaria chateado
 Se ela realmente se importasse com o que estava acontecendo. E 'especialmente se ela achou isso ainda, aqui.}
{391}{}{Quão irritada ela seria?}
{392}{}{Hmmmm. Diga, eu tive algumas outras perguntas ...}
{393}{}{Interessante. Bem, eu tenho que ir.}

# 19. HOW PISSED? (18)
{400}{}{Provavelmente chateado o suficiente para destruir este lugar ... pelo menos. Então ela nos daria a todos uma língua que amarrava e alguns
 Dias sólidos de pregação. Heh.}
{401}{}{Interessante. Diga, eu tive algumas outras perguntas ...}
{402}{}{Hmmmmm. Obrigado.}

# 20. WHAT ABOUT RICHARD? (6, 8, 9, 10, 12)
{410}{}{Rico? Ah, você sabe, ele foi encontrado como um daqueles ladrões de jato, morto em uma das calhas. Perto como podemos
 Figura, alguém o empurrou com chems até que ele estivesse morto.}
{411}{}{"Alguém" deu-lhe muito? Como você sabe que ele não overdose porque ele tomou demais?}
{412}{}{Quem você imagina pode ter feito isso?}
{413}{}{Desculpe ouvir isso. Tive algumas outras questões ...}
{414}{}{Desagradável. Olha, eu tenho que ir.}

# 21. GAVE HIM TOO MUCH? (20)
{420}{}{Porque ele era um filho limpo ... Mamãe ensinou-lhe tanto. E se você quiser dizer algo diferente, talvez você e eu
 Deveria resolver isso aqui.}
{421}{}{Eu não quis dizer isso assim. Desculpe-me que o criei.}
{422}{}{Não se cegue à possibilidade de ele ter tomado isso. Jet é extremamente formador de hábitos.}
{423}{}{Olhe, KID, se você sabe o que é bom para você, você vai parar de jogar cada vez que uma pequena verdade vem
 E morda você na bunda.}
{424}{}{Quem você imagina pode ter feito isso?}
{425}{}{Não estou à procura de nenhum problema. Eu irei.}

# 22. I'M SORRY. I DIDN'T MEAN IT LIKE THAT (21)
{435}{}{Sim, bem, apenas assista. Suas palavras de luta para qualquer Wright, então não vá atirando sua boca assim, tá bom?}
{436}{}{Não se cegue à possibilidade de ele ter tomado isso. Jet é extremamente formador de hábitos.}
{437}{}{Olha, KID, não comece comigo. Se você sabe o que é bom para você, você vai parar de tentar jogar para baixo a cada vez
 Uma pequena verdade vem e te morda na bunda.}
{438}{}{Desculpe, nenhuma ofensa pretende. Diga, eu tive algumas outras perguntas ...}
{439}{}{Entendido. É melhor eu ir.}

# 23. APOLOGY FAILED (15, 21, 22)
{445}{}{Não me chateies. I ain't got nothing more to say to you.}
{446}{}{Aguarde, acabei de ter uma pergunta mais ...}
{447}{}{Eu vou sair, vou embora.}

# 24. IMPLY RICH KEPT TAKING DRUGS (15, 21, 22, 23)
{455}{}{(Chris olha fixamente para você por um momento e depois se desloca para você!)}
{456}{}{Então, é como vai ser, hein? TODOS CERTO ENTÃO, DEIXE G -}

# 25. WHO DO YOU THINK DID IT? (20, 21)
{465}{}{Meu palpite é o Mordinos, um dos seus revendedores ou um dos próprios Mordino. Bastardos fazem toneladas de Jet.}
{466}{}{Consegui. Diga, eu tive algumas outras perguntas ...}
{467}{}{Qual dos negociantes você acha vendido a Richard?}
{468}{}{Entendo. É melhor eu ir.}

# 26. WHO DO YOU THINK SOLD IT? (25)
{475}{}{Poderia ter sido um deles: Jagged Jimmy J, aquele filho de puta marcado na esquina da Virgin Street, ou
 Renesco 'the Rocketman', que garimpe, que vende Jet outta que fortificou o invólucro no West Side.}
{476}{}{Algum outro revendedor?}
{477}{}{Consegui. Diga, eu tive algumas outras perguntas ...}

# 27. WHO DO YOU THINK SOLD IT? (28)
{485}{}{Ei, cara, obrigado.}
{486}{}{Ei, senhora, obrigado.}
{487}{}{Você descobriu quem matou meu irmão, e toda a família Wright vai agradecer. E isso não é um pouco obrigado, entende?}
{488}{}{Compreendo. Pegue você mais tarde, Chris.}

# 28. ANYBODY ELSE? (26)
{495}{}{Jules na cabeça da cidade também vende Jet, mas ele vende principalmente para os turistas ... então está o pequeno Jesus Mordino:
 Ele mighta empurrou chems em Rich, enquanto Rich estava sozinho. Ele sai no Desperado.}
{496}{}{Consegui. Diga, eu tive algumas outras perguntas ...}
{497}{}{Jagged Jimmy J, Renesco o Rocketman, Jules e Little Jesus ... Eu vou verificá-los. Obrigado pela informação, Chris.}


# end lines
{1200}{}{! Maneira de chutar a bunda do Enclave!}
{1201}{}{! Você é demais!}
{1202}{}{!}
{1220}{}{. O que você tem feito?}
{1221}{}{?}
{1222}{}{. Como estão as coisas?}
