# 0. LOOK
{150}{}{Você vê um mecânico coberto de graxa.}
{151}{}{Você vê um dos boyz de chop shop.}
{152}{}{Você vê um mecânico de aspecto aparente. Você mal consegue distinguir suas características sob a graxa e o óleo.}

# 1. FLOAT OR CLICK DIALOGUES [POWER ARMOR] (WTG)
{200}{}{Merda sagrada. * Gulp * Veja o que apenas entrou.}
{201}{}{Bem, se não é Mr. Fucking Coffee Can.}
{202}{}{Alguém naquela coisa?}
{203}{}{Podemos obter qualquer coisa? Uma cerveja? Um pouco de água? Um dinamarquês?}
{204}{}{Espero que nada esteja errado, uh, senhor ... ou senhora. O que quer que você esteja lá dentro.}
{205}{}{Seja o que for errado, T-Ray é responsável. Eu o veria.}
{206}{}{Isso é algum tipo de carro novo?}
{207}{}{Não queremos nenhum problema.}
{208}{}{Talvez você tenha procurado o T-Ray. Ele está na parte de trás.}

# 2. FLOAT/CLICK TEXT [PORN STAR/CHR > 5, FEMALE] (WTG)
{220}{}{Bem, olá, amiga, pequena senhora. Bom desempenho que você dá.}
{221}{}{Uau. Não tenha muitos visitantes. O que podemos fazer por você, senhorita}
{5221}{}{?}
{222}{}{Como você conseguiu suas pernas sobre sua cabeça assim?}
{223}{}{São esses melharucos reais? Posso me certificar?}
{224}{}{Seria demais para você verificar sob meu capuz?}
{225}{}{Ah, diabos, eu pareço uma porcaria, então você aparece. Não se importe com a gordura, senhorita.}
{226}{}{Você está procurando talento? T-Ray nas costas, então não se preocupe em ir lá.}
{227}{}{Eu sabia que deveria ter lavado hoje ...}
{228}{}{Verifique o seu óleo? Heh heh.}
{229}{}{Quer ver meu macaco lubrificante?}
{230}{}{:: Whistles ::}
{231}{}{Droga. Todos eles curvam e eu sem freios.}
{232}{}{Bem, olá, amiga, pequena senhora.}
{233}{}{Uau. Não tenha muitos visitantes. O que podemos fazer por você, senhorita?}
{234}{}{Você está procurando um amor quente? T-Ray nas costas, então não se preocupe em ir lá.}

# 3. FLOAT/CLICK DIALOGUES [PRIZEFIGHTER] (WTG)
{245}{}{Viu você bater no ringue. Maldito bom gancho direito você joga.}
{246}{}{Você vai pegar o outono? Tenho 30 fichas montadas em você.}
{247}{}{Você não parece tão difícil para um atacante.}
{248}{}{Quanto você bancou?}
{249}{}{Onde você trabalha fora?}
{250}{}{Cuidado com o Masticador. Ele tem gosto de ouvidos.}
{251}{}{Quer cerveja? Costumamos guardá-los para quando estamos trabalhando.}
{252}{}{T-Ray disse que você não é tão difícil. Eu lhe darei 5 fichas, se você for dar um soco.}
{253}{}{T-Ray disse que você pegou um maxilar de vidro. Ele está na parte de trás se quiser ir falar com ele.}
{254}{}{Esse Mastictor é um grande wuss. Uh, não diga a ele que eu disse isso, no entanto.}

# 4. FLOAT/CLICK DIALOGUES [MADE MAN] (WTG)
{265}{}{Espero que nada esteja errado, senhora.}
{266}{}{Não queríamos dizer desrespeito, senhora.}
{267}{}{Merda sagrada. * Gulp * Veja o que apenas entrou.}
{268}{}{O que podemos fazer por você,}
{5268}{}{?}
{269}{}{Podemos obter qualquer coisa? Uma cerveja? Um pouco de água? Um dinamarquês?}
{270}{}{Seja o que for errado, T-Ray é responsável. Eu o veria.}
{271}{}{Informe a seu chefe, ola, de todos nós.}
{272}{}{Talvez você tenha procurado o T-Ray. Ele está na parte de trás.}
{273}{}{Espero que nada esteja errado, senhor.}
{274}{}{Não queríamos dizer desrespeito, senhor.}

# 5. FLOAT OR CLICK DIALOGUES [CAR RECOVERED] (WTG)
{300}{}{Desculpe-me por esse mal-entendido com o Highwayman.}
{301}{}{Nós não sabíamos que o Highwayman era seu.}
{302}{}{Sim, o Highwayman não é um carro ruim, mas prefiro um Omni.}
{303}{}{Você está procurando vender o Highwayman?}
{304}{}{Ir, relâmpago engrasado, vá.}
{305}{}{A graxa é a palavra que ouvi ... dum dum dum dum ...}
{306}{}{O Highwayman é um carro doce; Chryslus certamente sabia como fazê-los na época.}
{307}{}{T-Ray está "trabalhando" na parte de trás novamente. Bastardo preguiçoso.}
{308}{}{Estou cansada de pegar a folga de T-Ray.}
{309}{}{T-Ray está examinando minha mulher novamente.}
{310}{}{T-Ray dormiu com minha irmã. E minha mãe. E meu cachorro.}
{311}{}{T-Ray mais excitado do que uma cabra de quatro cabeças.}
{312}{}{T-Ray na parte de trás. No telefone.}
{313}{}{O motor ainda é bom.}
{314}{}{O interior cheira como se alguém estivesse lá.}
{315}{}{O interior cheira a gecko.}
{316}{}{Não é um carro ruim, mas prefiro um Omni.}
{317}{}{O Highwayman tem um sistema analógico completo, 800 + Potência, de 0 a 60 em menos de um segundo.}
{318}{}{Rápido? O Highwayman passa de 0 a 60 em menos de um segundo.}
{319}{}{O Highwayman tem o poder: 800+, na verdade.}
{320}{}{Você deveria estar aqui?}
{321}{}{Sinta pena do idiota que deixou esse Highwayman deitado ao redor.}
{322}{}{Eu não suor; O Highwayman tem um sistema analógico completo e nenhum computador. Nenhuma das coisas extravagantes.}

# 6. FLOAT DIALOGUES [WARNING] (WTG)
{330}{}{As mãos desligadas ou as mãos saem. Compreendo?}
{331}{}{Retire o HELL do carro.}
{332}{}{Sua vida não vale mais do que aquele carro. Toque novamente e eu vou provar isso para você.}
