# 0. QUICK LOOK
{100}{}{Você vê um dos Irmãos da Córsega.}

# 0. LOOK
{150}{}{Você vê um homem bem vestido que cheira como vaselina. Por algum motivo, ele o atinge como um pouco reptil.}
{151}{}{Você vê Marty, um dos Irmãos da Córsega. O cabelo dele está recheado e o rosto dele está coberto com um magro brilho de suor.}
{152}{}{Você vê Sid, um dos Irmãos da Córsega. Ele está vestindo um toupee, e ele está usando óculos escuros.}

# 1. FALLOUT2 = ENCLAVE_DESTROYED (WTG)
{200}{}{Ei,}
{201}{}{}
{202}{}{Eu,}

# 2. POWER ARMOR (WTG)
{210}{}{Como você vai ao banheiro com essa coisa?}
{211}{}{Isso é um novo tipo de vibrador?}
{212}{}{É esse um novo preservativo do corpo?}

# 3. PORN STAR (WTG)
{220}{}{Você é mais erupção do que um vulcão em um dia ruim.}
{221}{}{VocÊ e uma estrela. Uma estrela cadente.}
{222}{}{VocÊ e uma estrela. Uma estrela de SPURTING.}
{223}{}{VocÊ e uma estrela. Uma estrela de THROBBING.}
{224}{}{Você entrega um desempenho no valor de mil hard-ons.}
{225}{}{}
{226}{}{VocÊ e uma estrela. Uma estrela brilhante.}
{227}{}{Ei,welcome back!}
{228}{}{Venha conversar comigo por um tempo.}
{229}{}{Fale comigo sobre negócios.}
{230}{}{Volte novamente!}
{231}{}{Saiba o que estou olhando? Estou olhando para a cadela mais foxi em todo o mundo.}
{232}{}{}
{233}{}{Ei,welcome back, honey-tits!}

# 5. MADE MAN (WTG)
{245}{}{Uh-oh. Um terno. Todo mundo em seus pés.}
{246}{}{Olá,}

# 6. PRIZEFIGHTER (WTG)
{250}{}{Olá, você sexual Hercules!}
{251}{}{Confira esses pecs. Flexa algumas vezes.}
{252}{}{Já pensou em uma carreira no negócio,}
{253}{}{Eu poderia fazer você configurar algumas cenas, se você quiser. Apenas pense nisso, ok?}
{254}{}{Bom estilo de luta que você obteve. Como é seu estilo de quarto?}
{255}{}{Você é bem-vindo aqui a qualquer momento. Diga, se você quer falar negócios ...}
{256}{}{Dizer,}
{257}{}{Volte novamente!}
{258}{}{Batalha, Xena.}
{259}{}{Bom estômago apertado que você tem lá. Como um trampolim.}

# 8. SLAVER (WTG)
{270}{}{Estamos todos estocados, slaver.}
{271}{}{Esses escravos são meus, escravos. Veja esses olhos.}

# 9. FLOAT/CLICK [COMPANION: ROBO-DOG] (WTG)
{275}{}{Uh, bom robo-dog, mas não fazemos esse tipo de fotos. Ainda.}
{276}{}{Essa casa de cão de robo foi quebrada?}

# 10. FLOAT/CLICK [COMPANION: ROBOBRAIN] (WTG)
{280}{}{Uau. Confira os passos sobre esse bot.}
{281}{}{É aquele daqueles vibradores robóticos de quem eu ouvi falar?}
{282}{}{Esse robô está interessado no filme?}

# 11. FLOAT/CLICK [COMPANION: MARCUS] (WTG)
{290}{}{Olha, tira o teu amigo mutante aqui. Nós não fazemos esse tipo de filmes aqui.}
{291}{}{Francamente, não acho que nenhuma das nossas atrizes possa lidar com seu amigo mutante.}
{292}{}{Nós já fizemos uma imagem mutante - o mutante comeu todas as atrizes. E quero dizer isso no sentido convencional.}

# 12. FLOAT/CLICK [COMPANION: LENNY] (WTG)
{300}{}{Keee-rist! Tire esse ghoul stinkard fora daqui antes que o cheiro se encaixe.}
{301}{}{Nós não estamos interessados   em imagens de ghoul. Tire-o para fora daqui.}
{302}{}{* Phewww * Que ghoul apanha o alto céu! Obtenha um ar fresco aqui antes de eu passar.}

# 13. FLOAT DIALOGUES (WTG)
{310}{}{Bem, a iluminação está apagada ...}
{311}{}{Como qualquer um vai CUIDAR se o boom estiver no tiro!}
{312}{}{Podemos nos concentrar no saque, por favor?}
{313}{}{Atirou há muito tempo. Irrompeu pagando fluffers ...}
{314}{}{Ele quer o que ?! Diga-lhe que se machuque e que o brâmane tenha entrado!}
{315}{}{As coisas estavam melhores nos dias dos implantes ...}
{316}{}{A sobrecarga vai nos matar.}
{317}{}{Adorei esse cara Diggler.}
{318}{}{O cara é dinamite sexual!}
{319}{}{Eu não vou te atirar assim.}
{320}{}{Ele é um míssil! Ele é um foguete! Ele está apenas saindo, Sid, estou te falando!}
{321}{}{Abso-frigging-lutely!}
{322}{}{Você diz a esse bastardo que ele pode ir para o inferno!}
{323}{}{Olha, se esse bolo de doce chega novamente ...}
{324}{}{Wham-bam-thank-you-madame.}
{325}{}{Se isso não bater em todos ...}
{326}{}{Sem pele da minha bunda.}
{327}{}{Você diz a esse filhote de galinha, você DIZ-O ...}
{328}{}{Bem, então ele pegou uma caixa de esquilos de costura.}
{329}{}{Isso não é um MP. Isso é um * YP. *}
{330}{}{20 minutos, babe.}
{331}{}{Vamos ver: (Cheque o script.) Digite Randy, ele e Sylvia vão para ele ... Christy vai ao banheiro, Peter junta-se a ela, eles vão para ele. Entre Ron ...}

# 14. INTRO (NORMAL) (WTG)
{345}{}{Os Irmãos da Córsega no seu serviço ... (Olhares para cima, irritados, depois fazem uma dobra.) Ei ... você é o único de antes - estava olhando para esfolar, certo?}
{346}{}{Os Irmãos da Córsega em seu serviço ... (Olhos, irritados.) Você novamente. Olha, você está interessado no fluffer
 posição ou não?}
{347}{}{Os Irmãos da Córsega em seu serviço ... (Olhares, irritados, depois fazem uma dupla.) VOCÊ é o novo fluffer?}
{348}{}{Os Irmãos Corsos no seu serviço ... (Olhos, irritados.) Você é o novo fluffer?}
{349}{}{Eu fluf}
{350}{}{Não há nenhum fluf! Me tofu!}
{351}{}{Afastar-se}
{353}{}{Claro que estou.}
{354}{}{Na verdade, minha esposa é.}
{356}{}{Não. Estou aqui para o dinheiro do grande Jesus Mordino.}
{357}{}{Não. Desculpe incomodá-lo.}
{358}{}{Nooooooo. Desculpe incomodá-lo.}

# 15. ME fluff (UGLY) (14, 58)
{370}{}{Assustador, brainiac. Pay's 5 ... er, 3 chips para um tiro. Entre no dormitório e enrole o eixo do fella.}
{371}{}{Eixo ... ele é um mutha ruim -}
{372}{}{Faça o que o homem diz}

# 16. SHAFT 2 (15)
{380}{}{Meça suas palavras.}
{381}{}{Estou falando sobre o Eixo!}

# 17. SHAFT 3 (16)
{390}{}{(Segure as mãos.) Eu posso cavar.}
{391}{}{Vai a cera, o eixo da fella}

# 18. ME fluff (GOOD-LOOKING) (14, 51, 54, 58)
{400}{}{Hmmmm. Quanto você bancou, amigo?}
{401}{}{Hmmmm. Você é tão difícil quanto parece, melharucos?}
{402}{}{Eu banco}
{403}{}{Eu não, faça-me fazer mulher}
{404}{}{Me dinheiro-tits}
{405}{}{Eu tufo}

# 19. ME BENCH/ME NO DO BENCH (18)
{415}{}{Riiiiight. Pal, eu sei de onde você está vindo, e eu sei exatamente onde você está indo. Você gosta de agir?}
{416}{}{Riiiiight. Querido, eu sei de onde você vem, e eu sei exatamente onde você está indo. Você gosta de agir?}
{417}{}{Eu gosto de coisas}
{418}{}{Aja como o que}

# 20. ME LIKE STUFF (19)
{425}{}{Sem merda? Eu também! Nós já temos muito em comum! Veja, somos um estúdio, fazemos MAGIC aqui. Você…}
{426}{}{você, amigo, pode ser PARTE dessa mágica!}
{427}{}{Você, melharucos, pode ser PARTE daquela magia!}
{428}{}{Okee-Dokee}
{429}{}{Magia! Magia! Eu gosto de magia!}

# 21. ACT LIKE WHAT (19)
{435}{}{Aja como uma beterraba. Como um rinoceronte selvagem. Um animal primitivo, construído apenas para aproveitar sua concupiscência pela gratidão das massas!
 MAGIA, BEBÊ, MÁGICA! É disso que estou falando!}
{436}{}{Aja como uma beterraba. Como uma mynx selvagem. Um animal primitivo cujo desejo SOUL é inflamar as luxúrias das massas!
 MAGIA, BEBÊ, MÁGICA! É disso que estou falando!}

# 22. MAGIC! MAGIC! ME LIKE MAGIC! (20, 21)
{445}{}{X-cellent! Agora, hora de experimentar. Preciso ver como você supera a "joroba".}
{446}{}{Você é o jogo, amigo?}
{447}{}{Você jogo, melinhos?}
{448}{}{Oh-Kay}

# 23. OKEE-DOKEE!/SURE! (22, 44, 59)
{455}{}{Vamos fazê-lo, então! Nao ha tempo a perder! Ei! Alguém me faça um extra!}
{456}{}{Tudo bem, amigo, hora de brilhar ...}
{457}{}{Tudo bem, melharucos, hora de brilhar ...}
{458}{}{Faça como o homem estranho dirige ...}
{459}{}{Pode apostar. Você ainda não viu NADA.}

# 24. POOR AGILITY (23)
{465}{}{Desculpe, amigo, você não é suficientemente flexível para o que precisamos. Trabalhe nisso, e talvez possamos conversar negócios mais tarde, ok?}
{466}{}{Desculpe, melharucos, você não é suficientemente flexível, pelo que precisamos. Trabalhe nisso, e talvez possamos conversar negócios mais tarde, ok?}
{467}{}{EU COMO fazer negócios dooo-ing aqui. Eu estou de volta}
{468}{}{* Snffff * O-kay. * Snffff * Me me sinto usado}
{469}{}{Vou tentar trabalhar na minha agilidade. Talvez na próxima vez.}
{470}{}{Talvez eu esteja de volta. Depois de um banho. Um longo banho.}

# 25. POOR CON (23)
{475}{}{Desculpe, amigo, seu bem e você são flexíveis o suficiente, é só que você conseguiu, uh, resistência, precisamos ... Trabalhe fora
 um pouco, e então talvez façamos algum negócio, ok?}
{476}{}{Desculpe, melharucos, você é legal e flexível o suficiente, é só que você conseguiu a resistência que precisamos ... Trabalho
 um pouco, e então talvez façamos algum negócio, ok?}
{479}{}{Vou tentar trabalhar na minha resistência. Talvez na próxima vez.}

# 26. POOR SEX EXPERIENCE (23)
{485}{}{Desculpe, amigo, bem, você é flexível, obteve o vigor de um brahmin, mas experimente um pouco mais na
 saco antes que possamos fazer negócios, ok? Não temos tempo para treiná-lo.}
{486}{}{Desculpe, melharucos, seu bem, você é flexível, obteve a resistência, mas experimente um pouco mais na
 saco antes que possamos fazer negócios, ok? Não temos tempo para treiná-lo, doce.}
{489}{}{Vou tentar aumentar minha uh, "experiência". Talvez na próxima vez.}

# 27. PLAYER IS A STAR! (23)
{495}{}{Pal, isso era credível.}
{496}{}{Meladas, isso era credível.}
{497}{}{Você era ouro lá fora, puro ouro de Reno! Essa performance valeu milhares de hard-ons! Você quer fazer um filme com
 nos? Vamos, vamos falar, querida, vamos conversar!}
{498}{}{Ok, Dokee ... eu falo com você. Eu quero fazer isso de novo e de novo}
{499}{}{Uh-uh. Eu quero ir agora. Eu me sinto sujo por dentro}
{500}{}{Estou interessado. Meu preço: 200 fichas ... tiro.}
{501}{}{Estou interessado. Mas primeiro, algumas condições. Primeiro, eu só trabalho com atores limpa, espero pelo menos 500 fichas para
 cada filmagem, 20% de royalties, e não BULLSHIT. Sou uma estrela e você sabe disso.}
{503}{}{De jeito nenhum. Eu preciso de um banho. Um longo banho.}

# 28. OKEE DOKEE . . . ME TALK WITH YOU . . . (27, 29)
{515}{}{(Ele arranca um pedaço de papel de sua jaqueta e tem que arranhar um "X" nele.) Feito! Vamos filmar! Primeiro, você vai
 precisa de um nome artístico, algo que grita STAR. Alguma ideia?}
{516}{}{(Ele arranca um pedaço de papel de sua jaqueta e dirige-o para esbarrar sua assinatura nele.) Feito! Vamos filmar!
 Primeiro, você precisará de um nome artístico, algo que grita STAR. Alguma ideia?}
{517}{}{Assustado - e quanto a outro nome?}

# 29. I'M INTERESTED, BUT . . . (SMART) (28)
{525}{}{Eu ... hmmmm ... eu ... hmmmm. Olha, eu concordarei com as 500 fichas, mas SEM ROYALTIES. Você me escuta?}
{526}{}{Tudo certo.}
{527}{}{Nenhum acordo. Te vejo em breve.}
{528}{}{Sem royalties, não}
{5528}{}{. Estou fora desse estúdio de galinha.}

# 30. INPUT LINE: X = NOT RECOGNIZED. (28)
{535}{}{Tudo certo! "}
{5535}{}{! "EU GOSTO! GOSTO! Agora, vamos FILMAR ...}
{6535}{}{! Luzes! Câmera! Açao!}
{536}{}{Achtung! Achtung!}
{537}{}{Começar a trabalhar.}

# 31. INPUT LINE: X = RON JEREMY. (28)
{545}{}{Eh ... não esse nome, 'kay? Bad ass-ociations. Quero dizer, ninguém quer ver alguém chamado isso em qualquer porno decente.
 Escolha outro nome, hein?}
{546}{}{OK…}
{547}{}{Mas eu realmente gosto do nome}
{548}{}{Mas eu realmente gosto desse nome.}

# 32. INPUT LINE: X = DIRK DIGGLER. (28)
{555}{}{Now, THAT'S a name so bright and so sharp, that it'll just EXPLODE because it's just so powerful! Good choice, pal, good choice. Now, let's FILM! Luzes! Câmera! Açao!}
{556}{}{Now, THAT'S a name with some history and magic associated with it. Good choice, pal, good choice. Now, let's FILM! Luzes! Câmera! Açao!}
{557}{}{Now, THAT'S a name with some magic associated with it. Good choice, honey-tits, good choice. Now, let's FILM! Luzes! Câmera! Açao!}

# 33."FILMING" FADE. (30, 31, 32)
{565}{}{Tudo certo! Tudo certo! Vamos fazer isso, pessoas! Vamos! Olhe vivo! Esta pronto?}
{566}{}{Eu pronto como freddie}
{567}{}{Eu nasci pronto.}

# 34. FILMING DONE (STUPID) (33, 48)
{575}{}{Tudo bem, meu amigo vulcânico. Já terminamos por hoje. Desempenho STELLAR! ESTELAR! E esse dinheiro disparou! Perfeito!
 Você quer fazer outro, você volta e nos vê em um mês, você ouve?}
{576}{}{Tudo bem, melharucos. Já terminamos por hoje. Desempenho STELLAR! ESTELAR! Você quer fazer outro, você volta e
 nos veja em um mês, você ouve?}
{577}{}{Oké ... Bye-bye}

# 35. FILMING DONE (SMART) (33, 48)
{585}{}{Cortar! Tudo bem, amigo.}
{586}{}{Cortar! Tudo bem, melharucos.}
{587}{}{Isso é um invólucro. Desempenho STELLAR!}
{588}{}{E esse dinheiro disparou!}
{589}{}{E esse crooning!}
{590}{}{Perfeito! Aqui está o seu corte:}
{591}{}{200 fichas.}
{592}{}{500 fichas.}
{593}{}{Você quer fazer outro, você vem nos ver em um mês, você ouve?}
{594}{}{Tudo bem então.}

# 36. UH, WHAT'S A fluffER? (UGLY) (14, 58)
{610}{}{Você arrancou meu membro? Olha, se você precisa perguntar, então NÃO É a pessoa para o trabalho. Agora, whaddya quer?}
{612}{}{Um trabalho, hein? Bem, então, EU SOU um fluffer. O melhor fluffer no negócio.}
{613}{}{Hum, nada. Eu devo estar no lugar errado.}

# 37. UH, WHAT'S A fluffER? (ATTRACTIVE) (14, 58)
{620}{}{Whoa, what am I thinking? You come in here, a class act, and I babble like an idiot! Look, pal, sorry 'bout that.
 Dizer,um, you looking for work? None of that fluffing crap. I'm talking ACTING, see?}
{621}{}{Whoa, what am I thinking? You come in here, a class act, and I babble like an idiot! Look, honey-tits, sorry
 'bout that. Dizer,um, you looking for work? None of that fluffing shit. I'm talking ACTING, see?}
{622}{}{Primeiro, o que é esse lugar?}
{623}{}{Se houver um salário constante, estou interessado.}

# 38. SURE AM. (UGLY) (14, 36, 40, 41, 42, 43)
{630}{}{Certo, então. Dirija-se para trás, comece a depilar os eixos. Aqui está o seu salário: 5 fichas.}
{631}{}{Faça como ele diz.}
{632}{}{Na verdade, eu mudei de idéia. Não, obrigado. Melhor eu vou agora.}

# 39. MY SPOUSE IS. (14, 58)
{640}{}{Yer cônjuge, hein? Hmmmmm. Assustado. Tenha sua cabeça de parceiro de vida para trás, comece a esmercer-brilhar os eixos. Aqui está o salário: 3 fichas.}
{641}{}{Faça como o homem diz, Davin-mel. Faz}
{5641}{}{ orgulhoso.}
{642}{}{Faça como ele diz, Miria meu doce. AGORA.}

# 40. WHAT'S THIS PLACE? (14, 36, 37, 47, 48, 58, 59)
{650}{}{Esse lugar? Vamos, o quê, você está comigo? Este é o Globo de Ouro, um estúdio FILM, o único em Reno, provavelmente
 O ÚNICO ainda está ereto e em pé. O que, você não conhece sua própria casa? Isso machuca!}
{651}{}{Esse lugar? Aqui estão os Globos de Ouro, um estúdio FILM, amigo, o único em Reno, provavelmente o ÚNICO ainda
 ereto e parado, veja? Agora, você vai falar meus ouvidos, ou você quer trabalhar?}
{652}{}{Esse lugar? Aqui estão os Globos de Ouro, um estúdio FILM, querido, o único em Reno, provavelmente o ÚNICO ainda
 ereto e parado, veja? Agora, você vai falar meus ouvidos, ou você quer trabalhar?}
{653}{}{Esse antigo lugar? Aqui estão os Globos de Ouro, um estúdio FILM, provavelmente o ÚNICO ainda ereto e em pé
 o mundo. Mas o suficiente sobre este lugar ... você está procurando um emprego, amigo? NECESSITAMOS talentos como você.}
{654}{}{Esse antigo lugar? Aqui estão os Globos de Ouro, um estúdio FILM, provavelmente o ÚNICO ainda ereto e parado no
 mundo. Mas o suficiente sobre este lugar ... você está procurando um emprego, melharucos?}
{655}{}{Como você "filme?" Quero dizer, vamos ... você precisaria de câmeras, filmes, projetores ... onde você conseguiria todas essas coisas?}
{657}{}{Não, obrigado. Eu tenho que ir.}
{658}{}{Apenas checando. Eu me sinto um pouco esgotado, ultimamente.}

# 41. WHERE DO YOU GET THE STUFF (ATTRACTIVE) (40, 52, 55)
{670}{}{Tivemos sorte ... não PRECISAMOS nada daquela lixeira. Nós tropeçamos por um projetor gráfico porno ... er, holo ....
 Nenhum equipamento volumoso, sem barulho ... e nenhuma bagunça desagradável.}
{671}{}{Reeeeally ... que especificações o projetor tem?}
{672}{}{Eu vejo ... bem, olha: Estou interessado em um trabalho, se você ainda está oferecendo.}
{673}{}{Bastante conversando com você, mas tenho que ir.}

# 42. SPECS (41)
{680}{}{Bem ... nós ainda não atingimos a capacidade da unidade QEWB - quase como posso dizer, é sobre um cubo de memória de alta densidade de 300 GB.
 Mesmo que o Winblows 57 O.S. come 70-75% disso, podemos filmar por cem anos nesse cubo.}
{681}{}{Onde está esse cubo agora? Posso ver?}
{683}{}{Uau. Isso é muita pornografia. Eu acho que vou pensar nisso por um tempo.}

# 43. CUBE (42)
{690}{}{Não, tentamos manter todos fora do cinema ... todos querem jogar seus dois centavos quando se trata de
 edição e armazenamento. 'Lados, o ouro do cubo para nós - não queriam nada acontecer com isso.}
{692}{}{Faz sentido. Deus sabe o que usar algum ladrão poderia colocar esse cubo se eles conseguissem as mãos sobre ele. Ah bem. Tchau!}

# 44. I'll TAKE A JOB . . . (ATTRACTIVE) (37, 40, 41, 42, 43)
{700}{}{X-cellent! A-course, I'll need ta see what yer made of, a little try-out to see how you get over the 'hump.' Você é o jogo, amigo?}
{701}{}{X-cellent! A-course, I'll need ta see what yer made of, a little try-out to see how you get over the 'hump.' Você jogo, melinhos?}
{702}{}{Certo.}
{703}{}{Uh, não, obrigado. Eu mudei de ideia. Em alguma outra hora.}

# 45. FUCK OFF! (50)
{710}{}{Então, vá até lá, sua pequena merda! Nós não precisamos de você! Dá o fora! Você nunca mais irá trabalhar em pornografia!}
{711}{}{Eu não quero de qualquer maneira! TÃO LÁ!}
{712}{}{Dane-se! Você não é meu chefe. Você não é o meu chefe. Eu sou o fodido chefe de}
{5712}{}{!}

# 46. BROS. PISSED (WTG)
{720}{}{Saia daqui. Não tenho nada para te dizer.}
{721}{}{Eu e você não tem nada para se dizer. Golpe.}

# 47. PORN STAR, LESS THAN 30 DAYS (WTG)
{730}{}{Ei,welcome back, }
{5730}{}{! Não estamos atirando hoje, mas tente novamente em breve.}
{732}{}{Você pode me contar um pouco sobre o estúdio?}
{733}{}{Fico feliz que você tenha dito isso. Veja, estou aqui para o dinheiro do grande Jesus Mordino.}
{734}{}{Tudo certo. I'll try back later.}

{735}{}{(Winks.) Você é dinheiro, baby, nada além de dinheiro!}

# 48. PORN STAR, MORE THAN 30 DAYS (WTG)
{740}{}{The Corsican Brothers at yer service… (The man glances up, smiles.) Ei,welcome back, }
{5740}{}{! Você está procurando por outra sessão de cinema?}
{743}{}{Claro que estou. Let's break some bedsprings.}
{745}{}{Na verdade não. Estou aqui para o dinheiro do grande Jesus Mordino.}
{746}{}{Não, obrigado.}

# 49. NO THANKS (48)
{755}{}{Whoa ... você não quer fazer isso ?! O que, você também, BOM para nós, agora? Nós fizemos você o que você é, '}
{5755}{}{! ' E você não esquece isso!}
{756}{}{Eu não me esqueço, não fique zangado, me deixa triste, volte, mas eu tenho que ir agora}
{758}{}{Ignore-o e vá embora}
{759}{}{Acalme-se. Eu simplesmente não quero disparar hoje, ok? Sheesh. Eu apenas volto mais tarde quando você esfriou.}
{760}{}{Vão se ferrar. Não preciso dessa merda brahmin. Eu sou uma estrela! Uma grande e brilhante estrela!}

# 50. DRUGS . . . (48)
{765}{}{Ei ... você está bem? Você parece um pouco fora disso. Você não está em chems, está? Porque eu NÃO vou te atirar assim.}
{766}{}{Eu quero filmar AGORA pessoa pequena}
{768}{}{Você não é o meu chefe! Eu quero foder, é o meu pau grande, então todos se preparam para fodidamente filmes agora.}
{769}{}{Você não é o meu chefe! Eu quero foder, é minha grande vagina, então todos se preparam para fodidamente filmes agora.}
{770}{}{Tudo certo. I'll try back later when I've, uh, calmed down.}

# 51. PRIZEFIGHTER, BUT NOT PORN STAR (WTG)
{780}{}{O Bros corso no seu serviço ... (O homem olha para cima, irritado, depois faz uma dobra.) Santo ...}
{5780}{}{?! Como você não foi antes? Ótima luta pelo caminho! Grande luta! O que posso fazer para você?}
{781}{}{Eu 4! Eu 4!}
{782}{}{Nada}
{783}{}{O que é este lugar?}
{784}{}{Você pode me contar um pouco sobre o estúdio?}
{785}{}{Tem algumas ... aberturas ... eu poderia preencher?}
{786}{}{Tem algum trabalho para alguém como eu?}
{787}{}{Estou aqui para o dinheiro do grande Jesus Mordino.}
{788}{}{Nada. Sorry to bother you.}

# 52. PRIZEFIGHTER: WHAT IS THIS PLACE? (51)
{795}{}{O estúdio Golden Globes, o estúdio para todos os talentos no que resta do mundo. E você, amigo, você poderia ser um STAR, sabe
 O que eu estou dizendo? Você está interessado em agir?}
{797}{}{Certo. Are you serious?}
{799}{}{Não no momento. Desculpe incomodá-lo.}

# 53. ANY OPENINGS? (51, 52)
{805}{}{Claro que sim! Vamos tentar você! Ei! Pegue-me alguns extras aqui! Nós temos uma estrela em nós!}
{806}{}{Faça como o homem dirige ...}

# 54. MADE MAN, BUT NOT PORN STAR (WTG)
{810}{}{O Bros corso no seu serviço ... (O homem olha para cima, irritado, depois faz uma dobra.) Santo ...uh…hey, how you doing, }
{5810}{}{?! How's Boss}
{6810}{}{? Sente-se! Então, para o que posso te fazer?}
{812}{}{Nuthin}
{813}{}{O que é este lugar?}
{814}{}{Conceda-me. Conte-me um pouco sobre esse estúdio.}
{815}{}{Boa pergunta. Você conseguiu ... aberturas ... eu poderia preencher?}
{816}{}{Good question. Tem algum trabalho para alguém como eu?}

# 55. MADE MAN: WHAT IS THIS PLACE? (54, 57)
{825}{}{O estúdio Golden Globes, THE studio para todos os talentos no que resta do mundo. Então ... uh, o que posso fazer por você hoje?}
{827}{}{Você tem tempo para fazer uma audição contra mim? Estou pensando que eu poderia ser uma estrela, você sabe o que estou dizendo?}
{829}{}{Nada today. Sorry to bother you.}

# 56. MADE MAN: AUDITION ME? (54, 55)
{835}{}{Um, sure. Certo. Let's, uh, give you a try. See if you got what it takes. I mean, we're pretty booked, but
 we can try you out, okay? Uh…some extras over here, please! Hurry up!}
{836}{}{Faça como o homem dirige.}

# 57. I'M HERE FOR THE MONEY (14, 47, 48, 51, 52, 54, 55, 58, 59)
{845}{}{Um, sure, sure! Certo...here ya go. 250 chips. And, uh, say hello to Big Jesus for me, okay?}
{846}{}{Um, sure, sure! Certo...sorry about the misunderstanding. Here ya go. 250 chips. And, uh, say hello to Big Jesus for me, okay?}
{847}{}{Antes que você seja rápido para me sair daqui, por que você não me fala sobre sua pequena operação, liso?}
{848}{}{Sim. Talvez. Mais tarde para você, amigo.}

# 58. SECOND TIME (WTG)
{855}{}{Irmãos da Córsega no seu serviço ... (Olha para cima.) Você novamente. Você está procurando mais trabalho, Senhor
 Fluffs-A-Lot?}
{856}{}{Irmãos da Córsega no seu serviço ... (Olha para cima.) Você novamente. Você está procurando por mais trabalho, Little
 Miss Fluffs-a-Lot?}
{857}{}{Irmãos da Córsega no seu serviço ... (Olha para cima.) Você! O que aconteceu com você? Quero dizer, é bom,
 é bom ... eu perdi
 algo antes. Você estava interessado em fluffing, foi isso?}
{861}{}{Uh, o que é um fluffer?}
{862}{}{Sim. Existe mais trabalho para mim?}

# 59. SECOND TIME (WTG)
{875}{}{Irmãos da Córsega no seu serviço ... (Olhares para cima.) Ei! Você pensou sobre minha oferta? Eh?}
{876}{}{Irmãos da Córsega no seu serviço ... (Olhares para cima.) Ei! Você quer outra tentativa? É isso?}
{877}{}{Irmãos da Córsega no seu serviço ... (Olhares para cima.) Ei! Você pensou sobre minha oferta? Você quer ir novamente, veja se você ainda
 conseguiu a magia? Eh?}
{879}{}{Doh-Kay}
{881}{}{Sim. Eu mudei de ideia. Eu deveria simplesmente chicoteá-lo ou ...?}
{882}{}{Sim. Eu mudei de ideia. Devo soltar minhas calças ou ...?}

# 60. ENCLAVE_DESTROYED (WTG)
{895}{}{... Ouvi sobre seus X-ploits ... como você soprou o equipamento de cada membro no Enclave. Isso tomou um estômago de ferro.}
{896}{}{Sim}
{897}{}{Nup}
{899}{}{Uh, não explodi todos os membros do Enclave. Você vê, o que aconteceu foi -}
{900}{}{É melhor eu ir.}

# 61. ENCLAVE_DESTROYED, PT 2 (60)
{910}{}{Não seja modesto. Eu sei que deve ter sugado. A maioria das pessoas não teria tido o estômago para isso. Mas você engoliu
 Seu orgulho e quem precisava ser feito. É o poder da estrela.}
{911}{}{Sim}
{914}{}{Uh, olha, EU NÃO soprei todos os membros do Enclave, veja -}
{915}{}{É melhor eu ir.}

# 62. ENCLAVE_DESTROYED, PT 3 (61)
{920}{}{Saiba o que estou pensando,}
{5920}{}{? Estou pensando em um filme com base em seus X-ploits. Nós chamaríamos isso de "Pullout: Post-Nuclear Boogalo". Estamos juntos?
 nisto? Eh?}
{921}{}{Você é um herói,}
{5921}{}{. Um herói genuíno. Não vou esquecer toda a merda que você teve que engolir para nós. E uma vez que todos os recibos da bilheteria chegam,
 O mundo inteiro também saberá.}
{922}{}{Sim}
{924}{}{Simpity-yup. Byeeee}
{926}{}{Claro, o que diabos. Eu resolvi esse jogo. Vamos fazer isso.}
{927}{}{Greeeeat. Obrigado...}
{928}{}{Deixe-me ir salvar o jogo primeiro, então eu posso voltar e fazê-lo.}

# 63. CUBE GONE (WTG)
{935}{}{Arruinado. Estamos arruinados.}
{936}{}{Sem esse cubo ... arruinado.}
{937}{}{Oh, Deusas sexuais cruéis e cruéis! Que ofensa nós lhe demos que causou que você tirasse o cubo de nós?}
{938}{}{:: Suspiro :: Com o cubo ido, talvez eu devesse tomar Macramé.}

# Display Messages
# stupid dude
{1000}{}{Eu me sinto doentio - doente na barriga.}
# regular dude
{1100}{}{Ack! :: spit, spit :: That SUCKED!}
{1101}{}{Você tem um sabor imundo e não cheio em sua boca, e você se sente doente em seu estômago. Mas hey, 5 chips são 5 chips!}
# spouse
{1200}{}{Eu ... não me sinto tão bem.}
{1201}{}{O verdadeiro amor triunfa mais uma vez. Seu cônjuge parece ter ficado doente, mas pelo menos você é 3 chips mais rico!}

{1250}{}{Você se tornou uma estrela. Uma grande e brilhante estrela brilhante.}

# END-LINES
{5200}{}{! Apenas o herói que queríamos ver!}
{5201}{}{, nosso herói amigo, conseguimos um acordo para você!}
{5202}{}{! Nós ouvimos sobre o que você fez no Enclave! Agora vamos discutir o que podemos fazer por você ...}
{5225}{}{ é ouro. Ouro puro.}
{5232}{}{! Amada! Melharucos!}
{5246}{}{. Bom clima hoje, né?}
{5252}{}{?}
{5256}{}{, se você QUERIA fazer um tiro com a gente ...}
