{100}{}{Você vê um comediante.}
{150}{}{Você vê um quadrinho ridículo. Ele está nervoso, e isso mostra.}

{200}{}{Ele está muito ocupado em sua rotina para conversar agora.}

{1000}{}{Então ... uh ... por que o radscorpion atravessou a estrada?}
{1001}{}{Para se afastar de seu ASS ASSISTENTE!}
{1002}{}{Eu digo que matamos esse cara!}
{1003}{}{Porque o radscorpion ... uh, queria se afastar das partículas de precipitação radioativas ...}
{1004}{}{Você é um merda!}
{1005}{}{FODA VOCÊ!}
{1006}{}{Uh, a piada, veja, já que já era um mutante, não precisava atravessar a estrada, então ... uh ...}
{1007}{}{}

{2000}{}{Heh heh. Gecko ... ghouls, certo? Ghouls ... homem, eles STINK.}
{2001}{}{Você fede!}
{2002}{}{Esse cara só deveria estar nos sábados à noite!}
{2003}{}{Uh ... heh-heh ... então, uh, ghouls certo, eles cheiram mal. Então, como, uh ...}
{2004}{}{Eu mencionei o cheiro de ghouls?}
{2005}{}{Um, então eu acho esse ghoul, certo, eu pergunto: "Vocês são invejosos que eu não foda?"}
{2006}{}{Ele diz: "Não. Uh, por que você pergunta?"}
{2007}{}{Eu disse, porque você é VERDE.}
{2008}{}{Uh ... verde com inveja. Pegue?}
{2010}{}{Booo!}
{2011}{}{}

{3000}{}{Então ... havia essa prostituta, certo, essa puta estúpida ...}
{3001}{}{Sua mãe é uma vagabunda!}
{3002}{}{"Slut?" Eu vou apontar você até a morte depois do show!}
{3003}{}{E ... uh ... ela vai, certo, ela vai, 'isso é um Gecko em seu bolso ou você está apenas ... uh, excitado?'}
{3006}{}{Uh ... eu mencionei que era um Gecko que respirava fogo ...? Heh heh.}
{3007}{}{}

{4000}{}{Vertibirds?}
{4001}{}{Verti what?}
{4002}{}{De que diabos este cara está falando?}
{4003}{}{Que tal aqueles sacos de amendoim que servem em vôos?}
{4004}{}{Que tal o salame você é servido?}
{4005}{}{O que é ... com isso?}
{4006}{}{}

{5000}{}{Traços opcionais?}
{5001}{}{*Bocejar*}
{5002}{}{Você sabe, como jinks. Alguém viu isso ultimamente?}
{5003}{}{Alguém já viu seu lapicão ultimamente?}
{5004}{}{Uhhh ... Você acha que há alguém que diz: "Ei, acho que quero mais falhas críticas?"}
{5005}{}{Quem são essas pessoas?}
{5006}{}{Ei, eu ouvi esse um algum lugar antes.}
{5007}{}{}

{6000}{}{Radscorpions?}
{6001}{}{O que é tão radical sobre eles?}
{6002}{}{É curto para RADIATION, asshole.}
{6003}{}{Quem são essas pessoas que pensam escorpiões mutantes ...}
{6004}{}{São tão rad?}
{6005}{}{Você é um merda!}
{6006}{}{}

{7000}{}{Molerats?}
{7001}{}{Oh garoto...}
{7002}{}{O que há com essas coisas?}
{7003}{}{Eles são moles ...}
{7004}{}{Ou...}
{7005}{}{Eles são RATOS?}
{7006}{}{E quanto às raças?}
{7007}{}{O que há com isso?}
{7008}{}{Uhhh ... sim, o que há com isso?}
{7009}{}{}

{8000}{}{Super mutantes?}
{8001}{}{Esse asshole nunca deixa de contar essas piadas estúpidas?}
{8002}{}{O que é tão SUPER sobre eles?}
{8003}{}{Quando foi a última vez que viu um super mutante ...}
{8004}{}{Tirar um gato de uma árvore?}
{8005}{}{Nunca! Sabe por quê?}
{8006}{}{*Bocejar*}
{8007}{}{Uhhh ... porque os super mutantes não resgatam gatos ...}
{8008}{}{Eles matam sem piedade!}
{8009}{}{Deseja que alguém te mate mershssmbl ...}
{8010}{}{Então, quem os chama SUPER mutantes?}
{8011}{}{Quem são essas pessoas?}
{8012}{}{Provavelmente os mesmos idiotas que o contrataram!}
{8013}{}{}

{9000}{}{E quanto a esse dork, Myron?}
{9001}{}{Ele está falando sobre mim?}
{9002}{}{Quero dizer, que geek! É como se ele estivesse no porão de seus pais toda sua vida.}
{9003}{}{* Ha * * Ha * * Ha *}
{9004}{}{Ei!}
{9005}{}{Bem, Myron, você é um dork.}
{9006}{}{Não se preocupe com isso, Myron. Ele está apenas tentando ser engraçado.}
{9007}{}{Sim, você é apenas sortudo, eu não tiro sua bunda, amigo!}
{9008}{}{}

{10000}{}{Então, você ouviu falar sobre a estúpida filha do Bispo que foi nocauteada?}
{10001}{}{* Clap * * Clap * * Clap *}
{10002}{}{::Apito::}
{10003}{}{Surpreendente!}

{11000}{}{Heh heh. Você ouviu aquele sobre o tribal que eliminou o Enclave?}
{11001}{}{O tribal era tão estúpido que, uh, o tribal, certo ... uh, explodiu seu equipamento.}
{11002}{}{ESTRONDO!}
{11003}{}{Eu mencionei que o tribal era estúpido?}
{11004}{}{Você é o único que é estúpido!}
{11005}{}{}
