# examine
{150}{}{Você vê um homem com roupas enrugadas. Ele está esfregando o nariz e olhando furtivamente.}
{151}{}{Você vê um comerciante químico.}
{152}{}{Você vê um comerciante químico. It looks like he's trolling for a customer.}

# float
{200}{}{Ei, herói! Você está procurando celebrar com algum Jet? Fale comigo!}
{201}{}{Maneira de chutar a bunda do Enclave, herói! Você quer relaxar e celebrar com algum Jet?}
{202}{}{::Felicidades::}
{203}{}{:: Whistles ::}
{204}{}{Nada melhor do que um tiro de Jet depois de chutar a bunda do Enclave, hein? Estou certo?}
{205}{}{Eu tenho uma merda que o ajudará a beijar o céu, herói.}
{206}{}{Você tem experiência?}
{207}{}{Herói, você quer doces cerebrais, você vem lidar comigo. Marro para TODA minha merda por você.}
{208}{}{Eu sei o que você está procurando, amigo, e eu entendi. Todo o jato que você PRECISA.}
{209}{}{Por que andar quando você pode FLY?}
{210}{}{Recebi o Jet mais puro da cidade. Não é barato, mas vale a pena todo.}
{211}{}{Você está olhando para voar? Você ganhou dinheiro? Você fala comigo.}
{212}{}{Eu tenho uma merda que o ajudará a beijar o céu, amigo.}
{213}{}{Eu tenho Jet e mais Jet. Vamos conversar.}

# click dialogue
{214}{}{Deixe-me saber como posso ajudá-lo, herói. Diga-me as suas necessidades, e eu lhe darei a melhor tarifa na cidade.}
{215}{}{Então, você quer celebrar com algum Jet, herói? Você veio ao lugar certo. Para você, TUDO é especial.}
{216}{}{Menos que eu posso fazer é marcar meu estoque para você, herói. Apenas a minha pequena maneira de agradecer por salvar nossa pele.}
{217}{}{Nada melhor do que um tiro de Jet depois de chutar a bunda do Enclave, hein? Estou certo? All my stock's on special for you.}
{218}{}{Eu tenho uma merda que o ajudará a beijar o céu, herói.  And for you: a nice discount. How does that sound?}

{219}{}{Tenho doces?}
{220}{}{Afastar-se}
{221}{}{O que voce conseguiu?}
{222}{}{Não quero nada, obrigado.}

# player great
# male
{230}{}{Ei, ei ... Estou na presença de grandeza. Para você, amigo, meu estoque é especial. Diga a todos os seus amigos sobre mim, todos
 certo?}
{231}{}{Então, você quer fazer festa com algum Jet, amigo? Você veio ao lugar certo. Para você, TUDO é especial.}
{232}{}{Tenho bastante Jet para colocá-lo em órbita, meu bom amigo. E para você: um desconto. Falaremos de preço?}
{233}{}{Eu tenho uma merda que o ajudará a beijar o céu, amigo.  And for you: a discount. That sound all right?}
{234}{}{Pelo menos eu posso fazer é marcar meu estoque para você, amigo. Apenas meu jeito de ser amigável.}
# generic
{235}{}{Você tem aula, sabe disso? Classe. E quando alguém tão elegante como você lida comigo, eles obtêm um desconto em
 na loja, veja?}
{236}{}{Deixe-me saber como posso ajudá-lo, amigo. Diga-me as suas necessidades, e eu lhe darei a melhor tarifa na cidade.}
{237}{}{Nada melhor do que um tiro de Jet depois de um longo dia de corrida, hein? Estou certo? Para você, todas as minhas ações são especiais.}
# female
{238}{}{Ei, ei ... Estou na presença de grandeza. Para você, senhorita, meu estoque é especial. Diga a todos os seus amigos sobre mim, está bem?}
{239}{}{Então, você quer fazer festa com algum Jet, senhorita? Você veio ao lugar certo. Para você, TUDO é especial.}
{240}{}{Eu tenho o suficiente Jet para colocá-lo em órbita, minha amiga. E para você: um desconto. Falaremos de preço?}
{241}{}{Eu tenho uma merda que o ajudará a beijar o céu, senhorita. E para você: um desconto. Isso soa bem?}
{242}{}{Menos que eu posso fazer é marcar meu estoque para você, senhorita. Apenas meu jeito de ser amigável.}

{247}{}{Eu sei o que você está procurando, o escravo, e eu entendi. Todo o jato que você PRECISA.}
{248}{}{Por que andar quando você pode FLY? You want Jet, I got it.}
{249}{}{Slaver, Recebi o Jet mais puro da cidade. Não é barato, mas vale a pena todo.}
{250}{}{Você está procurando voar, escravidão? Você obteve fichas? Você fala comigo.}
{251}{}{Recebi uma merda que o ajudaria a beijar o céu, o escravo.}
{252}{}{Eu tenho Jet, Jet e MORE Jet. Vamos conversar.}
{253}{}{Eu tenho o suficiente Jet para colocá-lo em órbita, escravidão. Falaremos de preço?}
{254}{}{Você é experiente, escravidão? Deixe-me configurá-lo com o melhor Jet da cidade.}
{255}{}{Você está olhando para o Jet? Vamos, escravidão, vamos lidar.}
{256}{}{Você está olhando para o Jet? Vamos, escravidão, você e eu: vamos conversar.}

{261}{}{Eu sei o que você está procurando, amigo, e eu entendi. Todo o jato que você PRECISA.}
{262}{}{Por que andar quando você pode FLY?}
{263}{}{Recebi o Jet mais puro da cidade. Não é barato, mas vale a pena cada chip.}
{264}{}{Você está olhando para voar? Você obteve fichas? Você fala comigo.}
{265}{}{Eu tenho uma merda que o ajudará a beijar o céu, amigo.}
{266}{}{Recebi Jet, Jet e MORE Jet. Vamos conversar.}
{267}{}{Tenho bastante Jet para colocá-lo em órbita, amigo. Falaremos de preço?}
{268}{}{Você tem experiência? Let me set you up with the best Jet in town.}
{269}{}{Você está olhando para o Jet? Vamos lidar.}
{270}{}{Você está olhando para o Jet? Vamos conversar.}

{519}{}{ COMO doce!}
