# 0. QUICK LOOK
{100}{}{Você vê Eldridge.}

# 0. LOOK
{150}{}{Você vê um homem fortemente armado coberto de graxa. Ele está olhando para a coleção de armas nas paredes e sorrindo sonhadoramente.}
{151}{}{Você vê Eldridge. He is gazing at his weapon collection and smiling dreamily.}

# 1. FALLOUT2 = ENCLAVE_DESTROYED (WTG)
{200}{}{Parabéns, herói! Você fez o bem!}
{201}{}{:: Fira sua arma no ar, começa a chatear e gritar :: Th 'Enclave's DEAD! MORTO! MORTO! Yeeee-haw!}
{202}{}{:: Ding-dong, o Enclave morreu, o Enclave está morto ... ::}
{203}{}{O Enclave é uma boa razão para cada cidadão ter os braços de porte certos.}
{204}{}{Da próxima vez, você não vai para o Enclave sem parar aqui primeiro ... Eu me certificarei de que você tenha todo o poder de fogo
 você precisa.}

# 2. POWER ARMOR (WTG)
{210}{}{Holeeee Peter Paul n 'Mary. Armadura de energia!}
{211}{}{Shooooo-eeee. :: Rubs eyes :: That Power Armor ?!}
{212}{}{Alguém me aperta. É essa POWER ARMOR ?!}
{213}{}{Tapdance no meu túmulo e xixi no meu primogênito! Power Armour! Em Reno!}
{214}{}{Você vende essa Power Armor, amigo? !! Ei! Alguém em casa?!!}

# 3. NORMAL FLOATS (WTG)
{220}{}{Um FINE de 9mm, mas um .233 tem poder de parada ...}
{221}{}{O que eu realmente quero é uma arma do Red Ryder BB.}
{222}{}{Espero que ninguém fique com um rifle de plasma turbo antes de eu fazer.}
{223}{}{Imagine onde os Salvatores conseguem essas armas a laser ...}
{224}{}{Já estava sonhando com armas de plasma na noite passada ...}
{225}{}{É melhor conseguir esse novo carregamento de escudos de espingarda para os Wrights ...}
{226}{}{Espero que os Mordinos tenham o ouro para pagar o pedido ...}
{227}{}{Essa arma? Punch um buraco através de uma parede de metal, pode.}
{228}{}{Esse garoto é um gênio ... dificilmente o saberia olhar para ele ...}
{229}{}{Melhor levar esses cachorros para uma caminhada antes de começar a fazer xixi em todos os lugares.}
{230}{}{Os aldeões sem lavagem estão armazenando mais armas ... eles são um grupo difícil.}
{231}{}{Eu queria que alguém me roubasse para que eu pudesse dispará-los.}
{232}{}{Preciso limpar as prateleiras em breve ...}
{233}{}{Não posso esperar para ir às gatas de Huntin na próxima semana ...}
{234}{}{Eu recebi SMGs, pistolas, dinamite, granadas ... e ainda pessoas vêm em desejos de espadas e arcos.}

# 4. INTRO (WTG)
{240}{}{Bem-vindo, herói! Maldito bom trabalho que você fez do Enclave ... salvou todos os nossos couros, você fez, e agradeço por isso. Eldridge's
 o nome. Você no mercado de algum ferro para preencher o seu coldre?}
{241}{}{Bem-vindo, senhor ... Eldridge é o nome. Você no mercado de algum ferro para preencher o seu coldre?}
{242}{}{Bem-vindo, viajante ... Eldridge é o nome. Você no mercado de algum ferro para preencher o seu coldre?}
{243}{}{Ernnnnh? Hole-sterrr?}
{244}{}{Depende do que você está vendendo.}

# 5. INTRO, FALLOUT 2 (WTG, 4)
{250}{}{Bem-vindo de volta, herói! Maldito bom trabalho que você fez do Enclave ... salvou todos os nossos couros, você fez, e agradeço por isso.}
{251}{}{Você vê algo que você gosta, me avise, e vamos descobrir um desconto * especial *, certo?}
{252}{}{Rito de Awwww}
{253}{}{Vaguear longe}
{254}{}{Ótimo! Posso ver o que você obteve no estoque?}
{255}{}{Eu não sei se você pode me ajudar ... Estou procurando por algo especial.}
{256}{}{Meu chefe...}
{262}{}{Excelente ... posso te ver ações especiais?}
{257}{}{Jules me disse para vir aqui se eu estivesse procurando armas.}
{258}{}{Os Salvatores compram seus atacantes aqui?}
{259}{}{Eu trouxe você aquela pistola a laser que prometi.}
{260}{}{Você pode atualizar as armas?}
{261}{}{Eu voltarei a olhar ao redor então.}

# 6. INTRO (WTG, 9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26)
{270}{}{Aqui, no New Reno Arms, temos os mais recentes dispositivos de proteção pessoal necessários para impedir que todos os mortos de sonuvabitch com ossos amarrados em suas trilhas. (Sorri malvado)}
{272}{}{Olá, amigo. O que posso fazer para você?}
{273}{}{Tal como?}
{274}{}{Me conte como coisas que você gosta de coisas demais?}
{276}{}{Você é apenas o homem que eu estava procurando. Posso ver o que você obteve no estoque?}
{277}{}{Posso ver o que você obteve no estoque?}
{286}{}{Posso ver ações especiais?}
{283}{}{Você pode modificar ou atualizar armas?}
{284}{}{Não está interessado agora, obrigado.}
{285}{}{Nada hoje, obrigado.}

# 7. RETARD (4, 5, 6, 19, 20)
{300}{}{Veja algo brilhante que você deseja? Vamos, deve haver algo aqui que lhe interessa.}
{301}{}{Uh ... claro, claro. (Olha para você criticamente.) Você me lembra meu escravo, Al. Você quer ver o que temos em estoque, amigo?}
{302}{}{Yuh}
{303}{}{Me vant somefin NOT stock}
{304}{}{Nuh}

# 8. JULES (5, 6)
{310}{}{Jules lhe enviou o meu caminho, hein?}
{311}{}{"Bout o tempo que o bastardo preguiçoso fez o trabalho dele ... então, o que posso te fazer, senhor?}
{312}{}{"Bout o tempo que o bastardo preguiçoso fez o trabalho dele ... perdoe meu francês. Então, o que posso te fazer, senhorita?}

# 9. CAN YOU UPGRADE WEAPONS, ALGERNON DEAD (5, 6, 8)
{330}{}{Não, não ... costumávamos estar no negócio de fazer isso, mas ... (parece dolorido.) ... bem, tem havido um
 Acidente ... e simplesmente não fazemos mais nada. Mais alguma coisa que eu possa fazer por você?}
{331}{}{Tudo bem então. Estou interessado em algo mais ...}

# 10. CAN YOU MODIFY OR UPGRADE WEAPONS? (5, 6, 8, 11, 12, 13, 17)
{340}{}{Claro que pode. O que você precisa?}
{1340}{}{Claro que pode. (Olhares para o seu equipamento.) Mas você não parece ter nada com o que eu possa mexer.
 Traga por alguma virgem ... eh, pistolas e rifles "normais", e talvez eu possa ajudá-lo.}
{341}{}{Você pode fazer qualquer coisa com alguma dessas pistolas?}
{342}{}{Um dos meus rifles poderia usar alguns anexos.}
{343}{}{Você pode fazer alguma coisa com este projeto de gado aqui?}
{344}{}{Deixa pra lá. Eu estava interessado em algo mais ...}
{345}{}{Na verdade, nada hoje.}
{1345}{}{Tudo certo. Eu estava interessado em algo mais ...}
{1346}{}{Eu farei isso. Adeus.}

# 11. PISTOLS MENU (10)
{350}{}{(Mancha seu magnum.) Posso colocar um carregador de velocidade naquele magnum lá por $}
{351}{}{Aquela Desert Eagle que você obteve ... se você quiser, posso dar uma revista expandida por $}
{352}{}{Coloque o carregador de velocidade no magnum.}
{353}{}{Expanda a revista nesta águia do deserto aqui.}
{354}{}{Na verdade, eu tinha outra arma em mente ...}
{355}{}{Deixa pra lá. Eu queria algo mais ...}
{356}{}{Na verdade, nenhum deles. Eu tenho que ir.}
{357}{}{Muito rico para o meu sangue. Volto quando tiver mais dinheiro.}

# 12. RIFLES MENU (10)
{365}{}{(Estuda seus rifles, acena com a cabeça).}
{366}{}{Posso colocar um escopo nesse rifle de caça por $}
{367}{}{Esse rifle de assalto que você chegou lá ... Eu posso dar uma revista expandida por $}
{368}{}{Eu tenho um alcance de pouca luz, eu posso colocar esse FN FAL que você obteve por $}
{369}{}{Tudo bem então ... coloque um escopo no rifle de caça Colt.}
{370}{}{Expandir a revista do rifle de assalto AK-112.}
{371}{}{Anexe esse escopo de luz baixa no FN FAL.}

# 13. MELEE MENU (10)
{385}{}{Você quer que o gado seja suco? Eu posso SUPERCARAR por US $}
{386}{}{Certo.}

# 14. RETURN ITEMS MENU (11, 12, 13)
{395}{}{(Eldridge leva o item, examina-o de forma crítica.) Tão errado ... você apenas aguenta um pouco e eu vou ver o que posso fazer.
 (Ele desaparece nas costas).}
{396}{}{OK.}

# 15. RETURN ITEMS MENU (14)
{400}{}{(Você espera ...)}
{401}{}{Esperar...}

# 16. RETURN ITEMS MENU (15)
{405}{}{(E aguarde mais ...)}
{406}{}{Dum de dum de dum ...}

# 17. RETURN ITEMS MENU (16)
{410}{}{(Você está prestes a assentir, quando de repente Eldridge retorna.) Desculpe pela espera ... aqui, vá. Isso pode lhe dar
 Uma vantagem contra qualquer filho de cadelas que tente n 'passo em sua sombra.}
{411}{}{Obrigado. Você pode atualizar minhas outras armas?}
{412}{}{Obrigado. Eu queria algo mais ...}
{413}{}{Obrigado. Eu vou tentar.}

# 18. I'M LOOKING FOR SOMETHING SPECIAL (5, 6, 7, 8)
{420}{}{Oh ... nós conseguimos um cliente discrimnatino, hein? Bem, às vezes, algumas peças premiadas fazem o seu caminho pela cidade ... pegue
 Isto, por exemplo. (Manter algo ... estranho.) Genuine pré-guerra de tecnologia. Innit algo?}
{423}{}{Uh ... é "algo", tudo bem. Posso dar uma olhada?}
{424}{}{Claro que é. Eu estava interessado em outra coisa, no entanto ...}
{425}{}{Não interessado. Obrigado mesmo assim.}

# 19. MODULE 2 (18)
{430}{}{(É uma bonita praça de plástico com buracos e linhas de metal desenhadas por toda parte. Algumas coisas engraçadas do símbolo da palavra estão escritas nele. Isso lembra uma galleta pop mecânica e sua boca começa a regar).}
{431}{}{(É o que parece uma placa de circuito. É um pouco empoeirada, mas parece estar em boas condições. Parece que faz parte de ... algo. Impresso no quadro é: 'Módulo de reconhecimento de voz do Vault Tec'.)}
{432}{}{(É uma placa de circuito complexa. É inserido um chip de memória, e uma série de conexões de computador estão ao lado, incluindo uma entrada e saída. Impresso no quadro é: 'módulo de reconhecimento de voz do Vault Tec.')}
{433}{}{Me vant tasty board}
{434}{}{Me vant sumfin else}
{435}{}{Me vant to go}
{436}{}{"Vault Tec?" Este * tem * para ser importante. Quantos?}
{437}{}{Sobre o tempo ... quanto para este módulo?}
{438}{}{Não, obrigado, queria outra coisa ...}
{439}{}{Não hoje, obrigado.}

# 20. BUY IT (19, 20)
{450}{}{Três mil dólares. É pegar ou largar.}
{451}{}{Última vez: três mil dólares. É pegar ou largar.}
{452}{}{Okee-dokkeee}
{454}{}{Vá para a garganta e pegue a palha-pop mecânica}
{455}{}{Folhe}
{457}{}{Uh, isso é um pouco íngreme. Que tal ... 1500?}
{458}{}{Não, obrigado. Eu queria algo mais ...}
{459}{}{Vou deixá-lo.}

# 21. BUY IT (20)
{470}{}{US $ 2500. E essa é a minha oferta final.}
{471}{}{Tudo bem, tudo bem. Aqui está.}
{472}{}{Esqueça, então. Eu queria algo mais ...}
{473}{}{Não, obrigado, então. Até a próxima.}
{474}{}{Muito rico para o meu sangue. Vamos falar mais uma vez quando tiver mais dinheiro.}

# 22. BUY IT (20, 21)
{480}{}{(Sorria, esfrega as mãos quando você coloca o dinheiro na mesa.) Está bem, aqui está você. Algo mais?}
{481}{}{(Pensa por um momento, te estuda, depois acena com a cabeça.) Certo, então ... Eu vou deixar você ter um roubo, mas
 aqui está. (Manua o módulo, leva o seu dinheiro.)}
{482}{}{Algo mais?}
{485}{}{Sim, estava interessado em algo mais ...}
{486}{}{Nada mais hoje, obrigado.}

# 23. CAN I BUY LASER PISTOLS HERE? (5, 6, 8)
{495}{}{(Parpadeia de surpresa, depois ri.) Haw! Não, não ... essas armas são outra coisa, não são? Claro Gostaria
 Para pegar minhas mãos em um, no entanto ... confira o alcance, o poder, a taxa de incêndio ... (atenta na distância, suspiros.)}
{496}{}{E se eu oferecesse oferecer um?}
{497}{}{Eu seria bom ter um, tudo bem. Diga, eu queria algo mais ...}
{498}{}{Ah bem. Tive que pedir. Obrigado, Eldridge.}

# 24. WHAT IF I GOT YOU ONE? (23)
{505}{}{(Squints para você, como se decidisse se ele podia confiar em você.) Eu não diria que não ... se você o fizesse, como um silêncio. Identidade
 Pague por seus problemas ... (Frowns.) ... assumindo que você não CAUSA nenhum.}
{506}{}{Nada de problema ... Eu tenho um em mim. Aqui está.}
{507}{}{Eu vou fazer isso. Antes de eu, eu queria algo mais ...}
{508}{}{Deixa pra lá então. Talvez você possa me ajudar com outra coisa ...}
{509}{}{Feito. Eu vou te enganar um, depois trazê-lo de volta.}
{510}{}{Não posso prometer que ... eu e o problema parecem viajar juntos. Vejo você mais tarde, Eldridge.}

# 25. LASER PISTOL RETRIEVED? (5, 6, 8, 24)
{520}{}{Bem, mija nas minhas costas e me diga que está chovendo!}
{521}{}{Bem, então, então! Fiel à minha palavra, aqui está algo para o seu problema ...}
{522}{}{(Dá-lhe um monte de batatas fritas, pega a pistola.) Porra ... coisa estranha, innnit? (Examina o barril.) Hmmm ...}
{523}{}{Eu queria algo mais ...}
{524}{}{Prazer em fazer negócios com você, Eldridge. Apreciar.}

# 26. REP: MADE MAN (5, 6, 8)
{530}{}{(Eldridge olha você para cima e para baixo, e seu tom torna-se mais respeitoso.) Claro, claro. Deixe-me mostrar-lhe o nosso
 Estoque especial ... com desconto, é claro.}
{532}{}{Na verdade, eu estava interessado em algo mais ...}
{533}{}{Deixa pra lá. Eu voltarei.}

# 27. AFTER HOURS (Dogs Barking)
{545}{}{Vocês, cães, fecharam a boca, y'hear?}
{546}{}{Cale a boca, você está a virar!}
{547}{}{Criaturas da noite ... cala a boca!}
{548}{}{Packard! Buck! Missy! Você está bem, cala a boca, ou eu vou entrar!}
{549}{}{Malditos cachorros!}
{550}{}{Mais um WOOF de você e eu vou lá!}

# 28. DOOR
{560}{}{O que, você acha que estou usando uma venda de olhos?}
{561}{}{Pegue suas mãos naquela porta!}
{562}{}{Não mexa com a porta novamente.}
{563}{}{Toque nessa porta, e essa é a última coisa que você vai tocar.}
{564}{}{Engraçado, a última pessoa que tocou essa porta foi enterrada no Golgotha. Não toque novamente.}

# 29. ROOM:
{575}{}{Você não deveria estar lá! Saia! Saia daqui!}
{576}{}{Você não está autorizado na parte de trás! Saia!}
{577}{}{Saia das costas antes de preenchê-lo cheio de buracos!}
{578}{}{Fique na parte de trás, e você será alvo de prática!}

{600}{}{Menino, estamos fechados ...}
{601}{}{Missy estamos fechados ...}
{610}{}{Então, eu sugiro que você se afaste daqui antes de matá-lo morto.}

{700}{}{Malditos cachorros! Eu vou voltar para a cama.}
{701}{}{Cães Estúpidos! Estou deixando todos a dormir o primeiro amanhã.}
{702}{}{Vocês poderiam ficar calados! Ninguém é estúpido o suficiente para entrar em uma loja de armas!}

{800}{}{Você entregou uma pistola a laser para Eldridge.}

# END LINES
{5256}{}{... me disse para parar, e que você "me prepararia".}
{5500}{}{.}
