# QUICK LOOK
{100}{}{Você vê um fluffer.}

# 1. LOOK (PLAYER IS MALE)
{150}{}{Você vê uma mulher moderadamente atraente. Ela parece estar checando você.}
{151}{}{Você vê um fluffer. She seems to be wondering whether she should attend to you or not.}

# 2. LOOK (PLAYER IS FEMALE)
{160}{}{Você vê uma mulher moderadamente atraente. Ela está olhando para você como se você fosse um rival.}
{161}{}{Você vê um fluffer. She's looking at you as if you're a rival.}

# 3. [ENCLAVE DESTROYED]
{200}{}{Oh meu ... é ele.}
{201}{}{Você é o maior espetáculo do mundo.}
{202}{}{:: Swoons ::}
{203}{}{Ouço que os Irmãos estão procurando por você. Eles querem fazer um filme baseado em sua aventura.}
{204}{}{Sim,}
{205}{}{:: Claps ::}
{206}{}{::Felicidades::}
{207}{}{Oh meu ... é ela.}
{208}{}{Vai nessa, garota!}
{209}{}{:: Dá-lhe o thumbs up sign ::}

# 4. [POWER ARMOR]
{225}{}{Não, eu estou fluffing essa coisa.}
{226}{}{Como você vai ao banheiro com essa coisa?}
{227}{}{Isso é um novo tipo de vibrador?}
{228}{}{Isso é um novo preservativo do corpo?}

# 5. [MALE, PORN STAR]
{235}{}{Precisa de algo,}
{236}{}{Por aqui,}
{237}{}{Veja! É ele!}
{238}{}{Está}
{239}{}{Eu queria poder fazer uma cena com}
{240}{}{Esse garoto realmente traz o creme.}
{241}{}{Ele pode me dar um cogumelo roxo a qualquer momento.}
{242}{}{Cobra desagradável de virilha pequena que você chegou lá.}

# 6. [PORN STAR, FEMALE]
{245}{}{Precisa de algo,}
{246}{}{Se eu tiver que cuidar de um ator mais hoje, vou vomitar.}
{247}{}{Estánot easy being a fluffer.}
{248}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{249}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{250}{}{Desejo que os Irmãos me deixem agir.}
{251}{}{Não sei o que os Irmãos da Córsega vêem nela ...}

# 7. [MALE, PRIZEFIGHTER]
{255}{}{Oh meu ... é ele.}
{256}{}{Olhe para esses músculos! Me deixa fraco ...}
{257}{}{Ele foi construído como um tanque. Confira esse barril.}
{258}{}{Confira o barril naquele tanque ...}
{259}{}{Ele é todo meu ...}
{260}{}{::Suspiro::}
{261}{}{Esse garoto realmente traz o creme.}
{262}{}{Cobra desagradável de virilha pequena que você chegou lá.}

# 8. [FEMALE, PRIZEFIGHTER]
{270}{}{Oh meu ... é ela.}
{271}{}{Bem-vindo ao estúdio, senhora.}
{272}{}{Ela parece tão ... (arrepios) ... perigoso.}
{273}{}{Ela é muito sexy.}
{274}{}{Olá Madame. Deixe-me saber se posso ajudá-lo com qualquer coisa.}

# 9. [MALE, MADE MAN/BERSERKER]
{280}{}{Oh meu ... é ele.}
{281}{}{Bem-vindo ao estúdio, senhor.}
{282}{}{Ele parece tão ... (arrepios) ... perigoso.}
{283}{}{Esse é um badass se eu já vi um.}
{284}{}{Esse garoto realmente traz o creme.}
{285}{}{Cobra desagradável de virilha pequena, ele chegou lá.}

# 10. [FEMALE, MADE MAN/BERSERKER]
{290}{}{Oh meu ... é ela.}
{291}{}{Bem-vindo ao estúdio, senhora.}
{292}{}{Ela parece tão ... (arrepios) ... perigoso.}
{293}{}{Ela é muito sexy.}
{294}{}{Olá Madame. Deixe-me saber se posso ajudá-lo com qualquer coisa.}

# 11. [MALE, NO REP + MYRON]
{300}{}{Oh, shit! EstáMyron! Run!}
{301}{}{Crap! EstáMyron. Stay calm…he can smell fear.}
{302}{}{É melhor evitar Myron de mim.}
{303}{}{Myron, é melhor ficar com o INFERNO longe de mim.}
{304}{}{Se Myron começar a trabalhar aqui, eu já fui.}
{305}{}{Myron, você passou a marca de cinco segundos ainda?}
{306}{}{Myron, é melhor você sair daqui antes que os Irmãos o vejam.}

# 12. FLOAT/[LEATHER]
{315}{}{Nem esses bandidos de couro sabem que eles deveriam estar aqui nas quartas-feiras?}
{316}{}{Ótimo. Outro ato de S & M.}
{317}{}{Oooooh. Couro preto. Agora, isso é novo.}
{318}{}{Nós não estamos fazendo nenhum couro ou escravidão até a semana que vem.}
{319}{}{Ótimo, outro coelho de couro.}
{320}{}{Olha, coelho de couro, o elenco está na quarta-feira, está tudo bem?}

# 13. [NO REP + BONENOSE]
{325}{}{Se eu tiver que cuidar de um ator mais hoje, vou vomitar.}
{326}{}{Estánot easy being a fluffer.}
{327}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{328}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{329}{}{O cara com o osso no nariz é meio fofo. De uma maneira sadomasoquista.}
{330}{}{Quem é o cara com o osso no nariz?}
{331}{}{Confira a tribal com o osso no nariz. Ele irá muito longe.}
{332}{}{Whoa, eu vi acidentes no set, mas nunca um cara que pegou um osso no nariz.}
{333}{}{Desejo que os Irmãos me deixem agir.}
{334}{}{:: Glares em você ::}
{335}{}{Ótimo. OUTRO fluffer. Ela provavelmente trabalhará a metade do preço com a aparência dela.}
{336}{}{Quem é ela?}
{337}{}{Quem é Você?}

# 14. [NO REP]
{345}{}{Se eu tiver que cuidar de um ator mais hoje, vou vomitar.}
{346}{}{Estánot easy being a fluffer.}
{347}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{348}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{349}{}{Desejo que os Irmãos me deixem agir.}
{350}{}{Ótimo. OUTRO fluffer. Ela provavelmente trabalhará a metade do preço com a aparência dela.}
{351}{}{:: Glares em você ::}
{352}{}{Quem é ela?}
{353}{}{Quem é Você?}

# 15. [ENCLAVE DESTROYED]
{360}{}{O Enclave? Presidente? Conte-me toda a história.}
{361}{}{Tom French me escreveu. Ele tem mãos suaves e suaves.}
{362}{}{Eles ainda estavam lutando contra a GUERRA ?! Mesmo! Bom, você desperdiçou esses bastardos.}
{363}{}{Você é um maldito total. Quero dizer, você começa a partir de uma simples tribo de lance-chucking - sem ofensa - e vá para
 Salve o mundo inteiro. Você chuta o traseiro. Fim da história.}
{364}{}{Você deve repetir o jogo como um tipo diferente de personagem.}
{365}{}{Conte-me tudo sobre sua briga com o Enclave ... Eu vou pegar uma cerveja gelada.}
{366}{}{Ouço que os Irmãos estão procurando por você. Eles querem fazer um filme baseado em sua aventura.}

# 16. [PORN STAR]
{370}{}{Ooops. Deixei cair alguma coisa na sua calça. Deixe-me entender.}
{371}{}{Um, você não gostaria de sair para tomar bebidas, não é? Que tal apenas sexo sem sentido?}
{372}{}{Como você se mantém tão apto?}
{373}{}{Você pode me dar seu autógrafo? No meu baú?}
{374}{}{Você está sendo ajudado,}
{375}{}{Preciso de ajuda com esse seu barril.}
{376}{}{Eu ouvi dizer que você é muito ... difícil de trabalhar.}
{377}{}{Eu ouvi você copar uma atitude, então você faz uma sensação. Por mim tudo bem.}
{378}{}{Estou muito feliz em conhecê-lo! Quero dizer, uau, você é}
{379}{}{Eu sei que não há filmagens, mas você precisa de um fluffer de qualquer maneira?}
{380}{}{Precisa de alguém para cuidar disso?}
{381}{}{Precisa de uma toalha úmida,}
{382}{}{Eu amei você em Great Balls for Hire.}
{383}{}{Eu amei-o em boa vontade, batendo.}
{384}{}{Você foi ótimo em Pokeahotass.}
{385}{}{Você foi ótimo em Vault Sexteen. Inspirado, mesmo.}
{386}{}{Eu não vi os Irmãos ao redor ... tente o escritório, talvez?}
{387}{}{Alguma chance de você falar os Irmãos da Córsega para me deixar agir?}
{388}{}{Fluffers tem o importante trabalho de manter os atores difíceis.}
{389}{}{Posso atuar no seu próximo filme?}
{390}{}{Eu não quero ser um fluffer toda a minha vida. Não mesmo.}
{391}{}{Só estou fazendo isso para pagar pela escola.}
{392}{}{Meu namorado não sabe que eu trabalho aqui.}
{393}{}{Hum job? Eu falarei sobre eles algum outro momento.}
{394}{}{Meu namorado não sabe que eu trabalho aqui.}
{395}{}{Eu queria que alguns dos atores tomassem banho. Quero dizer, um banho regular.}
{396}{}{Eu realmente quero agir.}
{397}{}{Minha namorada não sabe que eu trabalho aqui.}
{398}{}{Você pode me dar seu autógrafo?}
{399}{}{Um, você não gostaria de sair para tomar bebidas, não é? Se você estiver nas mulheres, isso é.}
{400}{}{:: Ignora você ::}

# 17. [PRIZEFIGHTER]
{420}{}{Quer saltar no ringue comigo, campeão?}
{421}{}{Boa unidade que você chegou lá.}
{422}{}{Precisa de alguém para cuidar disso para você, campeão?}
{423}{}{Sair do boxe e da pornografia? O mesmo, estágio diferente.}
{424}{}{Você está entrando no negócio também? Bem-vindo a bordo, campeão.}
{425}{}{Entrar no negócio? Bem, pelo menos você não terá que começar onde eu estou.}
{426}{}{Eu? Eu sou um fluffer. As vezes.}
{427}{}{Fluffers tem o importante trabalho de manter os atores difíceis.}
{428}{}{Os Irmãos dizem que eu sou valioso. É por isso que eles dormem comigo tanto.}
{429}{}{Você deveria entrar na pornografia. Você conseguiu o corpo para isso.}
{430}{}{Quer caixa?}
{431}{}{Hum job? Eu falarei sobre eles algum outro momento.}
{432}{}{Cuidado com o Masticador. Ele é um verdadeiro idiota. Ele tentou morder minha orelha uma vez.}
{433}{}{Olá Madame. Posso lhe ajudar com algo?*}
{434}{}{Um, se você está procurando por uma pequena empresa mais tarde, senhora ...}
{435}{}{Você quer o habitual, senhora?}

# 18. [MADE MAN]
{450}{}{Olá senhor. Posso lhe ajudar com algo?*}
{451}{}{Se você está procurando uma pequena empresa mais tarde ...}
{452}{}{Você quer o habitual, senhor?}
{453}{}{Precisa de alguém para cuidar disso?}
{454}{}{Dê uma boa palavra com o chefe para mim?}
{455}{}{Você está pensando em entrar no negócio também?}
{456}{}{Você deveria entrar na pornografia. Você conseguiu o corpo para isso.}
{457}{}{Hum job? Eu falarei sobre eles algum outro momento.}
{458}{}{Olá Madame. Posso lhe ajudar com algo?*}
{459}{}{Um, se você está procurando por uma pequena empresa mais tarde, senhora ...}
{460}{}{Você quer o habitual, senhora?}

# 19. [BONE-NOSE]
{465}{}{Desculpe, não, obrigado. Eu poderia ter um melhor sexo com meu batom.}
{466}{}{Você? Desculpe, eu nunca serei tão desesperado.}
{467}{}{Uh, seu amigo está com o osso no nariz compensando por alguma coisa?}
{468}{}{Seu amigo está com o osso no nariz vendo alguém?}
{469}{}{Seu amigo com o osso no nariz é meio fofo. De uma maneira sadomasoquista.}
{470}{}{Quem é seu amigo fofo com o osso no nariz?}
{471}{}{Diga ao tribal com o osso no nariz que ele irá muito longe nesta indústria.}
{472}{}{Whoa, eu vi acidentes no set, mas nunca um cara que pegou um osso no nariz.}
{473}{}{Eu não vi os Irmãos ao redor ... tente o escritório, talvez?}
{474}{}{Fluffers tem o importante trabalho de manter os atores difíceis.}
{475}{}{Eu realmente quero agir.}
{476}{}{Eu não quero ser um fluffer toda a minha vida. Não mesmo.}
{477}{}{Meu namorado não sabe que eu trabalho aqui.}
{478}{}{Você está sendo ajudado?}
{479}{}{Se você está procurando um emprego, fale com os Irmãos.}
{480}{}{Estou apenas fazendo isso para pagar a faculdade.}
{481}{}{Eu bang Avellone de graça.}
{482}{}{Estánot that I don't want to talk to you, but...oh, wait that IS it.}
{483}{}{Preciso me deitar.}
{484}{}{Hum job? Eu falarei sobre eles algum outro momento.}
{485}{}{Você não tem um problema com filmes de pele, não é?}
{486}{}{Você é o novo fluffer?}
{487}{}{Tem uma toalha? Um dos atores teve um ... acidente.}
{488}{}{Apenas não morda os atores, e você deve fazer o bem.}
{489}{}{Eu queria que alguns dos atores tomassem banho. Quero dizer, um banho regular.}
{490}{}{Um, você é novo aqui?}
{491}{}{Malte de sal Acostume-se a eles.}

# 20. [NO REP]
{500}{}{Desculpe, não, obrigado. Eu poderia ter um melhor sexo com meu batom.}
{501}{}{Você? Desculpe, eu nunca serei tão desesperado.}
{502}{}{Eu não vi os Irmãos ao redor ... tente o escritório, talvez?}
{503}{}{Fluffers tem o importante trabalho de manter os atores difíceis.}
{504}{}{Eu realmente quero agir.}
{505}{}{Eu não quero ser um fluffer toda a minha vida. Não mesmo.}
{506}{}{Meu namorado não sabe que eu trabalho aqui.}
{507}{}{Você está sendo ajudado?}
{508}{}{Se você está procurando um emprego, fale com os Irmãos.}
{509}{}{Estou apenas fazendo isso para pagar a faculdade.}
{510}{}{Eu bang Avellone de graça.}
{511}{}{Estánot that I don't want to talk to you, but...oh, wait that IS it.}
{512}{}{Preciso me deitar.}
{513}{}{Hum job? Eu falarei sobre eles algum outro momento.}
{514}{}{Você não tem um problema com filmes de pele, não é?}
{515}{}{Você é o novo fluffer?}
{516}{}{Tem uma toalha? Um dos atores teve um ... acidente.}
{517}{}{Apenas não morda os atores, e você deve fazer o bem.}
{518}{}{Eu queria que alguns dos atores tomassem banho. Quero dizer, um banho regular.}
{519}{}{Um, você é novo aqui?}
{520}{}{Malte de sal Acostume-se a eles.}

{1200}{}{. Aquele que chutou o traseiro do Enclave.}
{1204}{}{! Maneira de chutar a bunda do Enclave!}
{1207}{}{. Aquele que chutou o traseiro do Enclave.}
{1235}{}{?}
{1236}{}{!}
{1238}{}{!}
{1239}{}{.}
{1245}{}{?}
{1255}{}{.}
{1270}{}{.}
{1280}{}{.}
{1290}{}{.}
{1374}{}{?}
{1378}{}{!}
{1381}{}{?}
