# quick looks
{100}{}{Você vê um boxeador.}
{101}{}{Você vê Evan Hollyfeld.}

# examines
{150}{}{Você vê um homem preto agachado com um maxilar quadrado grosso. Seus ouvidos parecem ter sido horrivelmente salvos.}
{151}{}{Seus ouvidos parecem ter sido horrivelmente salvos.}
{152}{}{Seus ouvidos parecem ter sido horrivelmente salvos.}

# FLOAT DIALOGUES
{200}{}{Hnffff}
{201}{}{Hnrrgggg}
{202}{}{:: Gemeu, toca ouvidos ::}
{203}{}{:: Flexões ::}

# CLICK DIALOGUE
# MALE, PRIZEFIGHTER
{300}{}{:: detém as mãos sobre as orelhas e olha para você ::}
# other
{301}{}{Eu gosto de cabeça}
{302}{}{Eu e Mike toca cabeças}
{303}{}{Eu bato Mike, mas ele morda meus ouvidos}
{304}{}{Mike morda meus ouvidos porque ele está com fome}
{305}{}{Eu não ouço bem}
{306}{}{:: Sucos de ouvido de arranhões ::}
{307}{}{Hã?}
{308}{}{O que? Eu não ouço você.}
{309}{}{Ouvido hoje ido amanhã}
# FEMALE, ANY BUT PRIZEFIGHTER
{310}{}{Você morda?}
{311}{}{Inferno-o pessoa de bom cheiro}
{312}{}{Hell-o girl person}
{313}{}{Queras?}
{314}{}{Eu gosto de cabeça}
{315}{}{Eu e Mike toca cabeças}
{316}{}{Eu bato Mike, mas ele morda meus ouvidos}
{317}{}{Mike morda meus ouvidos porque ele está com fome}
{318}{}{Eu não ouço bem}
{319}{}{:: Sucos de ouvido de arranhões ::}
{320}{}{Hã?}
{321}{}{O que? Eu não ouço você.}
{322}{}{Ouvido hoje ido amanhã}
