# 0. QUICK LOOK
{100}{}{Você vê Jagged Jimmy J.}

# 0. LOOK
{150}{}{Você vê um homem de aparência deslumbrante. Ele tem uma cicatriz irregular que corre pelo lado do rosto e um leve tic facial.}
{151}{}{Você vê Jagged Jimmy J. It looks like he's trolling for a customer.}
{152}{}{Você vê Jagged Jimmy J. He nods as he catches sight of you.}
{153}{}{Você vê Jagged Jimmy J. He catches your eye and waves at you to come over.}

# 1. FLOAT (ENCLAVE DESTROYED = TRUE) (WTG)
{200}{}{Ei, se não é}
{201}{}{Ei,}
{202}{}{Há um mau muthuh ... e Jimmy J conhece um mau muthuh quando ele vê um.}
{203}{}{Nem todos os dias alguém pisa o presidente em seu próprio quintal.}
{204}{}{Você quer relaxar e marcar a vitória com algum Jet de Jagged Jimmy, herói?}
{205}{}{Salve o mundo, e Jagged Jimmy'll DÁ-lhe o mundo, herói. Todo o jato que você precisa.}
{206}{}{Ouça os Bros Corsos que estão procurando por você, ele ...}

# 2. FLOAT DIALOGUES (WTG)
{220}{}{Jagged Jimmy é o nome, e eu consegui todo o Jet que você PRECISA.}
{221}{}{Você está olhando para ficar alto? Jagged Jimmy é seu homem.}
{222}{}{Olhando para voar? Jagged Jimmy tem seu bilhete aqui.}
{223}{}{Você quer se preparar, Jagged Jimmy's tem o Jet.}
{224}{}{Você está olhando para sair do chão? Jagged Jimmy's tem o Jet que você PRECISA.}
{225}{}{Eu ganhei uma especial esta semana, vamos, vamos lidar.}
{226}{}{Você pode comprar a merda que mata pessoas, ou você compra a merda limpa e forte de Jagged Jimmy.}
{227}{}{Jimmy J SEMPRE abre para negócios, amigo.}
{228}{}{Quer chegar ao céu, deixar uma trilha enquanto voa, conversar com Jimmy, ele é seu cara.}

# 3. INTRO, FIRST TIME (WTG)
{240}{}{(Este homem tem um leve tic facial e uma cicatriz de uma de suas bochechas. A cicatriz parece uma ferida de faca.)}
{241}{}{Irmão, fiquei de olho em você desde que você caminhou pela rua. Você sabe o que eu vejo?}
{242}{}{Irmã, fiquei de olho em você desde que você caminhou pela rua. Você sabe o que eu vejo?}
{243}{}{Entenda}
{244}{}{O que você vê?! O que você vê?!}
{245}{}{Eu tenho que ir n -}
{246}{}{O que você vê?}
{247}{}{Corte a conversa, você é estúpido}
{248}{}{Desculpe, não interesse -}

# 4. SPIEL 1 (3)
{260}{}{Eu vejo um piloto. Vejo alguém que quer FLY. Você só precisa de uma pequena ajuda, um pouco ... JET.}
{261}{}{Hunh? Jato? No Sky? Onde?}
{263}{}{Jet, hein? Eu tive alguma questão -}
{264}{}{Olha, não estou -}

# 5. SPIEL 2 (4)
{270}{}{E meu amigo-piloto, quando se trata de Jet, Jagged Jimmy J é o seu HOMEM. Tenho a melhor merda em New Reno, puro
 Jet, Jet direto, o Jet SAFEST.}
{271}{}{Wherez Jet? Eu não vejo isso no céu}
{272}{}{Eu tenho que ir N--}
{273}{}{Jagged Jimmy J, hein? Diga, eu tive alguma questão -}
{274}{}{Olha, não sou interesse -}

# 6. SPIEL 3 (5)
{280}{}{OUTROS negociantes, eles não se importam com a qualidade, mas eu, eu gosto de manter minha base de clientes e mantê-los felizes, saber o que sou
 dizendo? É só o meu jeito ... a maneira Jimmy J.}
{281}{}{Eu não vejo frig-in Jet, você mente para}
{5281}{}{ você mente para}
{6281}{}{ sobre jato?}
{282}{}{EU DEIXO-ME G--}
{283}{}{Ei,the, uh, "Jimmy J way" sounds great and all, and that's why I had some quest--}
{284}{}{Não, eu não penso assim -}

{5200}{}{! Venha um pouco de jato de J-J agora ...}
{5201}{}{! Se você está olhando para comemorar com algum Jet, venha falar com Jimmy J ...}
#related
# 7. 2nd TIME, PLAYER GOT THE BULLSHIT SPEECH (WTG)
{290}{}{Sabia que você voltou, sabia disso! Jagged Jimmy J disse que seja a MANEIRA? Mantenha-os felizes, e eles nunca vão deixar você cair. assim
 meu piloto amigo ... o que Jagged Jimmy J pode fazer por você hoje?}
{291}{}{Bem, bem, se não for o meu "amigo" piloto, você volta para trás porque você PRECISA de Jagged Jimmy?}
{292}{}{Um ... Eu esqueci o que eu vou dizer. Eu vou}
{294}{}{Nós trad stuf? Eu como stuf}
{295}{}{Você recebeu Jet? Bem, vamos tratar ... amigo.}
{296}{}{Como você pegou essa cicatriz, Jimmy?}
{297}{}{Onde você recebe o seu Jet, Jimmy?}
{298}{}{Você sabe quem deu aquele filho Wright o Jet que o matou?}
{299}{}{Você disse antes que seu Jet fosse o "mais seguro". Não há nenhum Jet Jet ruim, está lá?}
{300}{}{Nada hoje, obrigado, Jimmy.}

# 8. SPIEL 4 (6, 10, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 33, 36, 39, 40, 41, 42, 43, 44, 45)
{310}{}{Então, o que você diz? O que Jagged Jimmy J pode fazer por você hoje?}
{311}{}{Sim, o que você quer? Mantenha-o rápido ... Não tenho tempo para gravar falar com você.}
{312}{}{Você tem desejos, você tem dúvidas ... o que pode fazer Jagged Jimmy J para você hoje?}
{314}{}{Me esqueci! Eu finalmente tive um pensamento e Me esqueceu!}
{5314}{}{ MATAR VOCÊ}

# 9. JIMMY FINALLY RECOGNIZES CHARACTER (7, 8, 9)
{330}{}{Ei ... você parece FAMILIAR para Jimmy. Eu conheço você, meu amigo-piloto?}
{331}{}{Eu gostaria de saber quem você é, meu amigo-piloto. Você parece malditamente familiar ...}
{332}{}{ME BIG HERO ME SOLUÇÃO DE JOGO E KICK PREZ ASS E FLUXO DE ÓLEO FLATFORM E SALVAR MUNDO}
{333}{}{Eu lutar no ringue na frente de lotz de gritar pessoas hoo gritar matar matar o filho da puta, então eu o soco até ele ficar de pé}
{334}{}{Eu não dou com os estranhos que falam muito com Deus}
{335}{}{Eu fiz o homem. Eu BIG man in REEno}
{336}{}{Como um pode VERULMENTE conhecer outro, Jimmy? É mesmo possível enquanto estamos nesta bobina mortal? Ou só é possível quando
 Nós nos libertamos de nossos corpos físicos?}
{337}{}{Eu QUERO falar, mas você NÃO DEIXE-ME BYE}
{338}{}{Bem, eu parei os planos do Enclave de assassinar todos no mundo, derrotado o Presidente, explodi
 sua base, e mal escaparam da minha vida.}
{339}{}{Eu lutei no ringue de boxe.}
{340}{}{Eu desenhei alguns filmes. Ouvido de}
{5340}{}{?}
{341}{}{Estou apertado com o}
{5341}{}{ família.}
{342}{}{Não, acho que não, Jimmy. Estamos aqui para lidar ou o quê?}
{343}{}{No, I don't think so. Ei,I wanted to ask you something…}
{344}{}{Não, eu tenho que ir. Pegue você mais tarde, Jimmy.}

# 10. JIMMY FINALLY RECOGNIZES CHARACTER, VOL 2 (9)
{360}{}{É isso aí! Eu sabia que eu tinha visto você em algum lugar antes! Porra, por que você não puxou desde o início, colocou Jimmy em seu lugar ... ?!
 Inferno, o que posso fazer por você?}
{361}{}{Um ... eu esqueci. Eu vou.}
{363}{}{Bem, estou procurando algum Jet ...}
{364}{}{Ei,I wanted something else…}
{365}{}{Eu tenho que ir. Pegue você mais tarde, Jimmy.}

# 11. PHILOSOPHY (9)
{375}{}{(Jimmy cai em um silêncio atordoado. Você acha que paralisou o cérebro dela).}
{376}{}{(Roube tudo o que ele tem).}
{377}{}{ O trabalho aqui está pronto.}

# 12. SCAR (7, 8)
{385}{}{Jagged Jimmy J tem muito amor, meu amigo-piloto, mas o mundo nem sempre ama Jagged Jimmy J de volta, vê?}
{386}{}{Eu te escuto. Eu te escuto.}
{387}{}{Não sei disso. Às vezes, o mundo é um lugar cruel.}
{388}{}{Essa é uma ótima história. Diga, Jimmy, eu tive algumas outras perguntas ...}
{389}{}{Boa história. Agora você conseguiu algum Jet, eu tenho algumas fichas ... vamos lidar?}
{390}{}{Boa história. Eu tenho que ir embora, Jimmy.}

# 13. SCAR 2 (12)
{400}{}{(Pontos na sua cicatriz.) Eu consegui isso enquanto eu estava parando este um grande filho da puta de bater de bater nessa garota de garotas que ela não gosta
 do jeito que ele estava tocando nela, certo?}
{401}{}{Mesmo? O que aconteceu?}
{402}{}{Grave? Cara, homens que espancaram as mulheres merecem ser abatidos.}

# 14. SCAR 3 (13)
{415}{}{(Obtém a posição de luta.) Então, eu entro, certo, e ele puxa uma FACA no ol JJ! Eu não tenho nada em mim, mas minhas mãos nuas, certo? Então ele obtém
 em um corte de sorte antes que eu ... * BAM! * Cancelou sua bunda!}
{416}{}{Sério? Jules diz que você estava "voando" no Jet e cortou o rosto tentando se proteger com sua faca de combate.}
{417}{}{Sem merda? Eu não acho que eu teria tido o ferro para pisar assim. Inferno, esse homem poderia matá-lo.}
{418}{}{GREAT story. Ei,Tive algumas outras questões ...}
{419}{}{Sim ... olha, eu tenho algumas fichas ... vamos lidar?}
{420}{}{Boa história ... tão bom que eu tenho que sair.}

# 15. TRUTH ABOUT SCAR REVEALED (14)
{430}{}{Wha...? Bem, Jules pode beijar minha bunda negra natural, e seria a única bunda da cidade em que ele ainda não foi beijado. Ele não conhece SHIT. Ele não
 até mesmo ter as bolas para falar cague na minha cara. Você decide quem está dizendo a verdade.}
{431}{}{Sim sim…. Olha, você ganhou Jet, eu tenho algumas fichas ... vamos lidar?}
{432}{}{Sim, sim ... .say, Jimmy, tive algumas outras perguntas ...}
{433}{}{Olhe, Sr. Big Talk, vamos lidar ou sentar aqui e ouvir você no dia todo?}
{434}{}{Bem, já ouvi o suficiente, Jimmy. Você se vê raspando, ouviu?}
{435}{}{Tudo bem então. Pegue você mais tarde, Jimmy.}

# 16. GO ON, JIMMY, TELL THE STORY 1 (14)
{445}{}{Ele quase fez, também! Sabe, quando entrei nisso, não estava pensando como 'Eu vou ser o homem de monstros bravos' e 'tudo, mas ...}
{446}{}{Você acabou de fazer o que era natural para você, certo?}
{447}{}{Uh-huh. Olha, eu tive algumas outras perguntas ...}
{448}{}{Eu tenho que ir. Pegue você mais tarde, Jimmy.}

# 17. GO ON, JIMMY, TELL THE STORY 2 (16)
{455}{}{Sim ... sim ... Acabei de ver algo errado, e eu tinha que fazer ALGO, certo? De jeito nenhum, eu poderia deixar algo assim ir
 enquanto eu estava em cena, sabe?}
{456}{}{Você obteve BALLS para fazer o que fez, Jimmy. A maioria das pessoas teria acabado de pendurar as cabeças e se afastou.}
{457}{}{Compreendo. Diga, eu tive algumas outras perguntas ...}

# 18. GO ON, JIMMY, TELL THE STORY 3 (17)
{465}{}{GOSTO de pessoas, e NÃO ESTOU como se alguém mexe com outra pessoa só porque elas podem. Essa merda é simplesmente errada.}
{466}{}{Você é um homem corajoso, Jimmy, um homem corajoso. Use sua cicatriz com orgulho. Diga, posso ver o que você tem no estoque?}
{467}{}{Você está certo sobre isso. Diga, eu tive algumas outras perguntas ...}

# 19. SO SHALL WE GET DOWN TO BUSINESS? (18)
{475}{}{Inferno, meu amigo piloto, eu gosto de você, então você não está puxando essa tela de troca com seus fusíveis e fios e tudo.}
{476}{}{Uh ... ok ... então, como vamos lidar ...?}

# 20. SO SHALL WE GET DOWN TO BUSINESS? (19)
{480}{}{Olha, isso é um negócio ruim e tudo, e não vai contar nada sobre isso, mas lembre-se de você.
 entre amigos. Na próxima vez, um curso, você tem que pagar, mas esse está no Jagged Jimmy J, está bem?}
{481}{}{Obrigado, Jimmy. Diga, posso ver o que você tem em estoque?}
{482}{}{Ei,thanks. Say, Tive algumas outras questões ...}
{483}{}{Tudo bem então. Obrigado, Jimmy.}

# 21. WHERE DO YOU GET YOUR JET, JIMMY? (7, 8)
{490}{}{Fico feliz que você perguntou, meu amigo piloto, feliz que você perguntou. Veja, todos eles OUTROS negociantes, certo, eles conseguem sua merda de segunda mão,
 diluído, diluído com todo o tipo de merda.}
{491}{}{Mas o Jet, por outro lado ...}
{492}{}{Na verdade, esqueça que eu perguntei. Tive algumas outras questões ...}

# 22. WHERE DO YOU GET YOUR JET, JIMMY? (COMPANION: MYRON, NOT IN PARTY) (7, 8)
{500}{}{Eu costumava obtê-lo do próprio deus, Myron, ver, mas ele foi para cima e para a esquerda ... ou acertou. Agora eu principalmente coloquem diretamente do
 Família Mordino.}
{501}{}{Bem, EU RECEBEi obtê-lo de Olron Myron, antes que ele obtivesse todo o uppity e deixou o negócio ... não está certo, Myron? Ha!
 Agora, eu grosso modo pedo a merda Mordino de run-o-the-mill.}
{502}{}{Interessante. Tive algumas outras questões ...}

# 23. WHERE DO YOU GET YOUR JET, JIMMY? VOL. 2 (8, 22)
{510}{}{Eu, eu tenho vínculos com o CREATOR, meu amigo-piloto. Eu pego meu Jet direto do brainiac, o deus vivo dos compostos químicos,
 MYRON.}
{511}{}{Myron?}
{512}{}{Interessante. Diga, eu tive algumas outras perguntas ...}
{513}{}{Myron, hein? Posso conhecer isso ... Deus vivo?}
{514}{}{Mesmo? Bem, vou ter certeza de voltar e comprar mais tarde. Obrigado, Jimmy.}

# 24. WHO'S MYRON? (23)
{520}{}{Ele é o menino dourado da família Mordino. Ele fez o Jet. Comprar de Jagged Jimmy é como comprar do próprio Myron, y'hear? Isso é
 Por que J-J pegou o puro Jet. O BEST Jet.}
{521}{}{Parece bom. Vamos lidar.}
{523}{}{Penso que eu poderia encontrar este Myron?}

# 25. CAN YOU TAKE ME TO MYRON? (23, 24)
{530}{}{De jeito nenhum! Os Mordinos pegaram aquele garoto preso mais apertado do que uma nova virgem de Reno. De jeito nenhum, eles vão deixar alguém tocar
 seu sustento, sabe o que estou dizendo?}
{531}{}{Eu te escuto. Então, quanto segurança eles conseguiram com esse cara?}
{532}{}{Exceto que eu ouvi Myron tem muita prostituta ... amigos. Como isso acontece se ele estiver trancado tão apertado?}
{533}{}{Entendido. Diga, eu tive algumas outras perguntas ...}
{534}{}{Interessante. Obrigado pela informação, Jimmy.}

# 26. SECURITY? (25)
{540}{}{Guardas, guardas e mais guardas. Além disso, segurança eletrônica mais apertada em New Reno. Você teria sorte se você ousar
 Sobre alguém que vê Myron, ele é tão bem guardado.}
{541}{}{Bem guardado, hein? Onde exatamente?}
{543}{}{Entendo. Diga, eu tive algumas outras perguntas ...}

# 27. STABLES? (26)
{550}{}{Eles o colocaram estacionado neste lugar chamado "Estábulos", para o Norte, fora dos limites da cidade. Eu só estive lá
 uma vez - eles nunca me deixaram além dos portões, e eu TRABALHO para a Família.}
{551}{}{Venha, deve haver alguma maneira de eu vê-lo.}
{554}{}{The Stables, hein? Fora da cidade para o Norte ... (Vou gravar isso no Pip Boy realmente rápido aqui) ... obrigado pela
 lowdown, Jimmy.}

# 28. HOW COULD I GET TO SEE MYRON? NO (27)
{560}{}{Beats the hell outta me, friend. I SELL for the boy, and I ain't hardly see him but once or twice from a hundred yards
 away. Big Jesus Mordino don't let nobody near him who ain't tight with the família.}
{561}{}{Tudo bem, vamos lidar.}
{564}{}{Tudo bem então. Obrigado, Jimmy. I got to be going.}

# 29. ANY WAY I COULD GET TO SEE MYRON? (25, 26, 27, 28)
{570}{}{Agora, é um ... buraco ... história diferente, meu amigo piloto. Oh meu, sim.}
{571}{}{Acho que essa é uma história que quero ouvir. Vamos, Jimmy ...}
{572}{}{Deixa pra lá. Tive algumas outras questões ...}
{573}{}{Não acho que tenha tempo para esta história, Jimmy. Eu tenho que ir.}

# 30. ANY WAY I COULD GET TO SEE MYRON 2? (29)
{580}{}{Veja, Myron é bem cuidada ... Mordinos dá a sua pequena vida o MELHOR de New Reno.}
{581}{}{E por isso, você quer dizer ...?}
{582}{}{Você quer dizer prostitutas, não é? Por curiosidade ociosa, onde os Mordinos recebem essas prostitutas e como elas são escolhidas?}
{584}{}{Entendo. Obrigado, Jimmy. Eu tenho que ir.}

# 31. ANY WAY I COULD GET TO SEE MYRON 2? (30)
{590}{}{Th 'Mordinos entrega as putas aos estábulos pessoalmente, depois escolta-os novamente. Heh heh. Myron tem apenas dezenove anos e
 ele tem os hormônios do vinte ... vinte homens, isso é.}
{592}{}{Interessante ... por sua vez, por curiosidade IDLE, onde os Mordinos recebem essas prostitutas e como elas são selecionadas?}

# 32. HOW DOES MORDINO SELECT THESE PROSTITUTES? (30, 31)
{600}{}{(Shrugs.) Um dos meninos de Mordino cruza a Pata do gato na rua, eu ouço, escolhe um Myron pode gostar da Miss Kitty's
 estoque ... (Jimmy de repente pára de falar. Ele esboça você e franziu a testa.) Espere um minuto ...}
{601}{}{O que está errado?}
{602}{}{Uh ... nunca mais. Diga, eu tive algumas outras perguntas ...}
{603}{}{Bem, obrigado pela informação, Jimmy.}

# 33. HOW DOES MORDINO SELECT THESE PROSTITUTES? (32)
{610}{}{Por que você quer saber merda assim? Eu tenho Jet, é tudo o que você precisa saber. Você não precisa saber nada sobre Myron,
 ou o que ele teve para o jantar, ou quem ele faz, ele vai para a cama à noite.}
{611}{}{Por que você quer saber uma merda assim ... (Pausa, então sorri e olha você para cima e para baixo.) Ah, agora eu entro sua deriva.
 Você vai direto para a fonte para você Jet, certo, irmã?}
{612}{}{Não no momento. Vamos ver o que você conseguiu, Jimmy.}
{613}{}{Esqueça, então. Vamos lidar.}
{614}{}{Deixa pra lá então. Tive algumas outras questões ...}
{615}{}{Eu devo. Diga, eu tive algumas outras perguntas ...}
{616}{}{Não, apenas curioso. Obrigado, Jimmy. Eu tenho que ir.}
{617}{}{Tudo bem então. Mais tarde, Jimmy. Eu tenho que ir.}

# 36. YOU SAYING HE SELLS SHIT THAT KILLS PEOPLE? (7, 8, 43)
{625}{}{Inferno, tudo digo, Jimmy gosta de seus compradores felizes e VIVOS. Desenhe suas próprias conclusões, meu amigo-piloto.
 A respiração é mais importante para você do que para raspar alguns chips da sua próxima compra Jet?}
{626}{}{Entendido. Nós vamos lidar?}
{627}{}{Saiba alguma coisa sobre este vaso de jato vazio?}
{628}{}{Eu não acho que o filho ODED no Jet. Acho que ele foi envenenado.}
{629}{}{Tive algumas outras questões ...}

# 37. YOU KNOW ABOUT WRIGHT KID'S OD? (7, 8)
{635}{}{Ah, então, AGORA, ele sai, não é ?! Você quer saber se ol 'Jimmy tem algo a ver com isso, hein ?!}
{636}{}{Não, eu só perguntava -}
{637}{}{Tudo bem, nunca perca isso. Nós vamos lidar?}
{638}{}{Olhe, eu tive algumas outras perguntas -}
{639}{}{Obrigado pela dica, Jimmy. É melhor eu ir -}

# 38. YOU KNOW ABOUT WRIGHT KID'S OD? (37)
{645}{}{FUCK você! Eu vendo CLEAN merda! Você quer saber quem envenenou aquele garoto Wright, você vai perguntar a esse velho idiota Renesco, ou aquilo
 Weasel Jules, e você vê o que eles dizem!}
{646}{}{Está bem, está bem. Acalme-se --}
{648}{}{Tudo bem, tudo bem. Olha, eu tive outra questão -}

# 39. TRY AND LEAVE (38)
{655}{}{Você ouve, e você ouve BOM. Se eu soubesse que você estava falando sobre mim, tenho alguma coisa a ver com aquela criança do Wright
 morte, eu me certificarei de ter um túmulo no Gólgota bem próximo a ele.}
{656}{}{Renesco disse que vende Jet atado com arsênico.}
{659}{}{No problem. Look, Tive algumas outras questões ...}
{660}{}{Morto, hein? Como Richard?}
{661}{}{Você não me ameaça, seu pequeno cocksucker. Mexa comigo, e eu vou te matar tantas vezes você vai
 acho que você era Lázaro.}
{662}{}{Fácil, Jimmy. Ninguém vai falar.}
{663}{}{Não vou dizer nada, Jimmy. Vou agora, vejo? Vou.}

# 40. CANISTER 1 (36, 39)
{675}{}{(Takes canister, estuda isso.) Naw, I ... (Bocal Sniffs, depois franziu a testa.) Sheeee-it. Este jato tem suco de radscorp nele.
 Quem quer que esteja sugando isso não é longo para este mundo ... (Manuscrito de volta).}
{676}{}{Está envenenado?}
{677}{}{Hmmm. Tive algumas outras questões ...}
{678}{}{Entendo. Obrigado.}

# 41. CANISTER 2 (40)
{685}{}{Claro que sim! Preciso ter cuidado nessa cidade com merda como se fosse passado ... é por isso que Jimmy sempre diz -}
{686}{}{Alguma idéia de onde isso poderia ter vindo?}

# 42. ANY IDEA . . . (41)
{695}{}{Naw, eu não ... olha, agora, não espalhe a palavra que é minha ... se eu fosse você, eu pediria a Jules e Renesco
 sobre isso ... mas você não ouviu isso de mim, certo?}
{696}{}{All right then. Tive algumas outras questões ...}
{697}{}{Renesco e Jules, hein? Eu vou perguntar sobre isso. Obrigado pela dica.}

# 43. ANY IDEA . . . (36, 39)
{705}{}{Não me surpreenda nenhum.}
{706}{}{O que você está dizendo?}
{707}{}{I see. Tive algumas outras questões ...}
{708}{}{Deixa pra lá então.}

# 44. ANY IDEA . . . (39)
{715}{}{Sim, ele diria isso, porque ele conhece tudo sobre isso.}
{716}{}{O que você quer dizer?}

# 45. WHAT DO YOU MEAN? (7, 8, 44)
{725}{}{O que eu quero dizer? Quero dizer, Jimmy gosta de seus compradores felizes e VIVOS. Renesco não desenha nenhuma distinção entre os dois,
 embora ... então você tira suas próprias conclusões, meu amigo-piloto.}
{727}{}{Obrigado pela dica, Jimmy. É melhor eu ir agora.}

{800}{}{Você descobriu que Richard Wright foi envenenado.}
