# 0. QUICK LOOK

# 0. LOOK
{150}{}{Você vê um homem negro com um terno gasto. Quando ele chama a atenção, ele sorri, seu dente de ouro
 Brilhando à luz das lâmpadas.}
{151}{}{Você vê Jules.}

# 1. FLOAT [SLAVER] (WTG)
{200}{}{Deixe Jules mostrá-lo em volta, escravidão.}
{201}{}{Vá ver os Mordinos, escravos. Eles são o mercado para a maioria dos escravos que chegam a New Reno.}
{202}{}{Novo em Reno, slaver? Vale a pena falar comigo.}
{203}{}{Ei, escravidão. Venha falar comigo por um segundo.}
{204}{}{Slaver, se você não está falando com Jules, você não conhece metade do que o novo Reno pode oferecer.}
{205}{}{Eu, escravidão! Você conseguiu um minuto?}
{206}{}{À procura de algo, escravidão? Deixe Jules ajudá-lo a encontrá-lo.}

# 2. FLOAT [IF PLAYER HAS NEVER SPOKEN TO JULES] (WTG)
{220}{}{Novo na cidade? Vale a pena falar comigo, amigo.}
{221}{}{Ei você. Venha falar comigo por um segundo.}
{222}{}{Amigo, se você não conversou com Jules, não conhece metade do que o novo Reno pode oferecer.}
{223}{}{O novo Reno é um lugar perigoso, amigo. Deixe-me preenchê-lo no que é saudável e o que não é.}
{224}{}{Yo! Você conseguiu um minuto, amigo?}
{225}{}{Amigo, você e eu temos que ter algumas palavras. Deixe Jules mostrá-lo ao redor.}
{226}{}{À procura de algo, amigo? Deixe Jules ajudá-lo a encontrá-lo.}

# 3. FLOAT ENCLAVE_DESTROYED (WTG)
{240}{}{Aleluia! Eu sempre soube que você seria o herói! Eu sabia!}
{241}{}{Chegou o Hero! Faça o caminho, faça caminho!}
{242}{}{Venha dizer olá ao seu velho amigo Jules agora.}
{243}{}{Você vai compartilhar alguma fama comigo, meu amigo?}
{244}{}{Você vai compartilhar algumas das suas novas riquezas comigo, meu amigo?}
{245}{}{Jules sempre te tratou direito ... então, diga a todos que você me conhece, certo?}
{246}{}{Ouça o Corso Bros estão procurando por você, ele-ro ...}

# 4. FLOAT [POWER ARMOR] (WTG)
{260}{}{Daaamn. Eu acho que você e eu devemos ser amigos.}
{261}{}{Como você vai ao banheiro com essa coisa?}
{262}{}{Que diabo é isso? Um carro a pé?}
{263}{}{Esses viciados vão virar quando eles veem você entrar naquela coisa.}

# 5. FLOAT [MADE MAN] (WTG)
{280}{}{Você vai dar uma boa palavra ao chefe para mim, irmão?}
{281}{}{Você é irmão, agora você não se esqueceu de seu amigo Jules em sua ascensão até o topo, você tem?}
{282}{}{Você é sombrio e mortal! Olha para mim como New Reno tem sido BOM com você!}
{283}{}{Se o seu chefe precisa de alguém para lidar com Jet, estou aqui ...}
{284}{}{Você vai dar uma boa palavra ao chefe para mim, irmã?}
{285}{}{Você é irmã, agora você não se esqueceu de seu amigo Jules em sua ascensão até o topo, você tem?}

# 7. FLOAT [MALE PRIZEFIGHTER] (WTG)
{300}{}{Você é campeão! Olha para mim como o novo Reno está sendo bom para você!}
{301}{}{Você é campeão, você não se esqueceu de seu amigo Jules em sua ascensão até o topo, não é?}
{302}{}{Lady Luck está brilhando sobre você, irmão. Você obteve a MÁGICA.}
{303}{}{Eu sempre soube que você teria seu nome em luzes. Eu sabia que a primeira vez que eu vi você.}
{304}{}{Você é irmã com os punhos! Olha para mim como o novo Reno está sendo bom para você!}
{305}{}{Você, meu irmão, você não se esqueceu de seu amigo Jules em sua ascensão até o topo, não é?}
{306}{}{Lady Luck está brilhando sobre você, Miz Prizefighter. Você obteve a MÁGICA.}

# 9. FLOAT [MALE PORN STAR] (WTG)
{320}{}{Droga, olhe para ESTA estrela brilhante ... você é tão brilhante que mal posso te ver, irmão!}
{321}{}{Eu, meu irmão de baixa altura! Olha para mim como New Reno tem sido BOM com você!}
{322}{}{Que tal você me apresentar algumas dessas atrizes em que você trabalha, irmão?}
{323}{}{Você, agora, você não se esqueceu de seu amigo Jules em sua ascensão ao topo, você tem?}
{324}{}{Lady Luck está brilhando sobre você, cara. Você obteve a MÁGICA.}
{325}{}{Eu sempre soube que você teria seu nome em luzes. Eu sabia que a primeira vez que eu vi você.}

# 10. FLOAT [FEMALE PORN STAR] (WTG)
{340}{}{Olhe para esta doce alma irmã.}
{341}{}{Meu coração pulsa para te ver.}
{342}{}{Vamos, irmã, dê um beijo ao seu amigo antigo Jules.}
{343}{}{Droga, olhe para ESTA estrela brilhante ... tão brilhante que mal posso te ver, irmã!}
{344}{}{Yo! Olha para mim como New Reno tem sido BOM com você!}
{345}{}{Que tal você me deixa entrar em algumas cenas com você, doçura?}
{346}{}{Você, agora, você não se esqueceu de seu amigo Jules em sua ascensão ao topo, você tem?}
{347}{}{Lady Luck está brilhando em você, doçura. Você obteve a MÁGICA.}
{348}{}{Eu sempre soube que você teria seu nome em luzes, irmã. Eu sabia que a primeira vez que eu vi você.}
{349}{}{Você é uma senhora elegante quando está sentindo e gritando na tela.}
{350}{}{As palavras não podem descrever o quanto eu tenho para te ver.}

# 11. FLOAT [COMPANION: MARCUS] (WTG)
{365}{}{Que um MUTANTE?}
{366}{}{Esse mutante é um grande muthuh.}
{367}{}{Mutantes em New Reno? Deve significar uma tempestade que vem ...}
{368}{}{Mutantes dos resíduos? Não foi oitenta anos atrás?}
{369}{}{Esse mutante não vai durar muito tempo em Reno ...}
{370}{}{Vai ser um assassinato se as famílias encontrarem esse mutante ...}

# 12. FLOAT [COMPANION: ROBOBRAIN] (WTG)
{380}{}{Isso é algum tipo de máquina caça-níqueis que o está seguindo?}
{381}{}{Isso é uma máquina robo-slot?}
{382}{}{Seu robô faz truques? Uh ... truques de mágica, quero dizer.}
{383}{}{Você vende esse robô? Você pode manter o cérebro.}

# 13. FLOAT [COMPANION: LENNY] (WTG)
{390}{}{Um ghoul ... pensei que eu cheirava algo.}
{391}{}{Esse garoto ghoul não vai durar muito tempo em Reno ...}
{392}{}{Vai ser um assassinato se as famílias encontrarem esse ghoul ...}

# 14. FLOAT [COMPANION: ROBODOG] (WTG)
{400}{}{Nice cyber-doggie ... bom cibercafé ...}
{401}{}{Bom cachorrinho ... bom cachorro ... talvez eu tenha um esterno ...}
{402}{}{Esse cão é a primeira boa razão que já vi por leis de trela.}
{403}{}{Esse cão é parte de metal? Eu pensei que era um maldito.}
{404}{}{Pergunto se você pode criar ciber-cães ...}

# 15. FLOAT [NO REP] (WTG)
{410}{}{Reno pode ter um homem para o café da manhã. Ou um buffet.}
{411}{}{Um homem pode se perder aqui, e Jules é quem pode encontrá-lo.}
{412}{}{Esta cidade pode tirar o despreparado ... fale comigo e eu vou definir você diretamente.}
{413}{}{Mulheres, fichas, mulheres, fichas ... o que mais você precisa?}
{414}{}{Jet, mulheres, armas ... Eu entendi tudo. Tudo que você precisa fazer é pedir.}
{415}{}{Reno ... a cidade que nunca dorme.}
{416}{}{Jet, chips, Jet, chips ... o que mais você precisa?}
{417}{}{Venha um, venha tudo.}
{418}{}{Jules é seu EYES, seus EARS, de New Reno.}
{419}{}{Maior cidade pequena em todos os resíduos, amigo.}
{420}{}{Você é novo na cidade? Vale a pena falar comigo, amigo.}
{421}{}{Jules é o homem com o que você PRECISA.}
{422}{}{Você obteve o desejo, recebi a poupança.}
{423}{}{Reno fica acordado toda a noite, então você precisa estar preparado.}
{424}{}{Reno pode ter uma mulher para o café da manhã. Então eu posso.}
{425}{}{Uma mulher pode perder-se aqui. Deixe Jules ser aquele que o encontra.}
{426}{}{Essa cidade pode tirar o despreparado ... fale comigo. Eu vou te despachar.}
{427}{}{Yo! Venha falar comigo, irmã!}
{428}{}{Você é novo na cidade, irmã? Vale a pena falar comigo, senhora.}
{429}{}{Você precisa do Jet? Você precisa de armas? Irmã, entendi tudo. Tudo que você precisa fazer é pedir.}

# 16. BASIC INTRO, 1st TIME (WTG)
{450}{}{(Sorrisos, exibindo um dente dourado reluzente. Sua colônia é tão forte que quase chokes você.)}
{451}{}{BEM-VINDO à cidade brilhante de New Reno, meu irmão!}
{452}{}{BEM-VINDO à cidade brilhante de New Reno, minha irmã!}
{453}{}{Hunh? Wh-?}
{454}{}{E você é…?}

# 17. BASIC INTRO, 1st TIME, PT 2 (16)
{460}{}{Jules, do Nome, e eu ficaria mais satisfeito por fazer seu conhecimento, mostrá-lo ao redor e prepará-lo com o que for
 Você está procurando.}
{461}{}{Jules de Nome, e posso dizer que nunca vi uma mulher mais bela caminhar por esta rua até este momento. Seria
 Seja o MEU prazer em fazer um tour de Reno e prepará-lo com o que você está procurando.}
{462}{}{Ei, hey, hey, bem-vindo de volta! O que você precisa de Jules, meu amigo?}
{463}{}{Eu estou procurando ... um. Me esquece de novo}
{464}{}{Afastar-se}
{465}{}{Tudo certo. Como você pode me ajudar?}
{466}{}{Bem, eu tive algumas perguntas ...}
{467}{}{Sabe o que aconteceu com o filho do Sr. Wright, Jules?}
{468}{}{Jules, você viu meu carro? Eu o estacionei aqui um tempo atrás, e agora ele se foi.}
{469}{}{Olhe ... "Jules", não é? Você, obviamente, espera algo dessa conversa, então esteja bem comigo na frente.
 O que você está procurando?}
{470}{}{Então, estou curioso ... o que você tira do guia de turismo, Jules?}
{471}{}{Não hoje, Jules, obrigado.}
{472}{}{Nada, obrigado. Vejo você, Jules.}

# 18.  RETARD (17, 81)
{480}{}{Eh ... não estude o cérebro, irmãozinho. Você não se machuca, agora, ouve?}
{481}{}{Eh ... não estique o cérebro, irmãzinha. Você não se machuca, agora, ouve?}
{482}{}{Olá, T, Olá, T, Olá, T, ho}

# 19.  HOW CAN YOU HELP? (17, 20-59, 68-77, 83, 84, 85, 86, 87, 88, 89)
{490}{}{Posso te pegar tudo o que você precisa, irmão. Se você precisa voar, fique alto, deslize para baixo em um luscious ho, Jules sabe
 onde ir. A questão é: eu gots o tesouro, então qual é o seu prazer?}
{491}{}{Tudo o que você precisa, Jules é o HOMEM, irmã. Se você precisa voar, fica alto, deslize para baixo, Jules sabe para onde ir.
 A questão é: eu gots o tesouro, então, qual é o seu prazer?}
{492}{}{Tudo o que você precisa, Jules é a MAN, minha doce irmã. Se você precisa voar, fique alto, deslize para baixo, Jules sabe onde
 ir. A questão é: eu gots o tesouro, então qual é o seu prazer?}
{493}{}{Certeza, coisa certa ... Eu gots o tesouro, então, qual é o seu prazer?}
{494}{}{Você pode me contar um pouco sobre New Reno?}
{495}{}{Onde posso obter alguns chems?}
{496}{}{Estou procurando comprar algum poder de fogo pesado.}
{497}{}{Estou procurando suprimentos.}
{498}{}{Eu quero me deitar.}
{499}{}{Estou procurando por um lugar chamado Vault 13.}
{500}{}{Estou à procura da minha tribo. Eles foram sequestrados.}
{501}{}{Você sabe como consertar um petroleiro?}
{502}{}{Estou procurando um Kit de Criação do Jardim do Éden.}
{503}{}{Nada hoje, obrigado.}

# 20.  CAN YOU TELL ME ABOUT NEW RENO? (19)
{515}{}{Jules TELL você sobre New Reno? Claro que sim! PRIMEIRA coisa que você deve saber: Reno é governado por quatro famílias: Mordinos,
 Os Salvatores, os Bispos e os Wrights. Cada um deles pegou uma fatia da torta de Reno.}
{516}{}{Reno tem quatro famílias: Mordinos, Salvatores, Bispos, Wrights. Cada um deles pegou uma fatia da torta de Reno.}
{517}{}{Conte-me sobre as famílias.}
{518}{}{E a lei?}
{519}{}{Na verdade, tive algumas outras perguntas ...}
{520}{}{Interessante. Obrigado por falar comigo.}

# 21. LAW (20)
{525}{}{Não há lei, não é po-piolho, não é um xerife, não é um órgão governamental. APENAS as famílias.}
{527}{}{Quem mantém ordem em Reno então?}
{528}{}{Entendo. Tive algumas outras questões ...}

# 22. ORDER? (21)
{535}{}{As Famílias mantêm as coisas funcionando sem problemas. Eles não gostam de problemas em Reno, porque isso prejudica o comércio turístico, e isso
 Significa menos dinheiro para eles. Não faça problemas e cubra suas apostas, você ficará fora do Golgotha.}
{537}{}{Gólgota?}

# 23. GOLGOTHA? (22)
{545}{}{Sim, este cemitério fora da cidade. É onde eles colocaram devedores e pessoas que atravessaram as famílias.
 Eles apenas os colocam em posts e deixam-nos morrer lentamente ao sol. Não é minha escolha "morrer". Fodido como lá fora.}
{547}{}{Interessante. Diga, eu tive algumas outras perguntas ...}
{548}{}{Parece bom. Obrigado pela informação.}

# 24. INFO'S EXPENSIVE (20-23, 26-53)
{555}{}{Bem, agora, uma coisa que você tem que saber sobre New Reno não é nada grátis. Se for, ex-amine a mercadoria.}
{556}{}{Bem, agora, esse tipo de informação não é barato. Você pegou as fichas? Então você chamou minha atenção.}
{557}{}{Pague 25 fichas.}
{558}{}{Pague 50 fichas.}
{559}{}{Pague 75 fichas.}
{560}{}{Pague 100 fichas.}
{561}{}{Na verdade, eu tive algumas outras questões relacionadas à não-família ...}
{562}{}{Parece que não posso pagar nenhuma informação agora. Eu voltarei quando tiver algumas fichas.}
{563}{}{Eu vou manter isso em mente. Obrigado pela dica, Jules.}

# 25. TELL ME ABOUT SOME MORE ABOUT THE FAMILIES (24)
{575}{}{(Jules enfia as fichas com tanta rapidez, você jura que elas desapareceram). Então ... qual das famílias boas te interessa hoje?}
{576}{}{(Jules puxa as fichas). Então ... qual família você precisa saber?}
{577}{}{Conte-me sobre a família Mordino.}
{578}{}{Conte-me sobre a família Salvatore.}
{579}{}{Conte-me sobre a Família Bispo.}
{580}{}{Conte-me sobre a família Wright.}
{581}{}{Eu tive algumas perguntas sobre New Reno ...}
{582}{}{Na verdade, nunca perca. Falaremos mais uma vez.}

# 26.  TELL ME ABOUT MORDINOS 1 (25)
{590}{}{(Segure dois dedos.) Os Mordinos são uma besta de duas cabeças, um amigo e cada um deles chamado Jesus Mordino.}
{591}{}{Continue…}
{592}{}{Eu sempre suspeitava que Jesus tinha vínculos com o crime organizado.}
{594}{}{Voltemos para as outras famílias.}
{596}{}{Na verdade, nunca perca. Obrigado por falar comigo.}

# 27.  TELL ME ABOUT MORDINOS 2 (26)
{615}{}{Há o pai, o Grande Jesus Mordino, e o filho, Lil 'Jesus, e ambos são os filhos de puta que você já conheceu.
 Usado para ser escravo aqui, mas eles viraram as mesas anos atrás e criaram seu próprio império lil.}
{616}{}{Quão grande é o seu "império?"}

# 28.  TELL ME ABOUT MORDINOS 3 (27)
{625}{}{Possuem o Desperado na rua. Não pode perder. Eles também receberam o maior suprimento de Jet em ALL o 'New Reno.
 Então, se você tiver o desejo de voar ...}
{626}{}{Falando sobre isso, você sabe onde posso obter alguns chems por aqui?}
{627}{}{Como os Mordinos têm o maior suprimento de Jet?}
{628}{}{Conte-me sobre as outras famílias.}

# 29.  HOW COME MORDINOS HAVE BIGGEST SUPPLY OF JET? (28, 29, 31, 32, 33)
{635}{}{Eles estão no topo da pilha, amigo. Não há mais razão do que isso. Eles adquiriram a fábrica, o fabricante e a
 distribuição. Eles são como uma maldita companhia aérea que tiveram tanto Jet.}
{636}{}{Sim, e sobre isso?}
{637}{}{Que fábrica?}
{638}{}{O que "criador"?}
{639}{}{Quão extensa é a sua rede de distribuição?}

# 30. WHAT FACTORY? (29)
{650}{}{Tornou fábricas em todo New Reno, arrancando a merda de dia e de noite. É por isso que você pode comprar tudo
 O Jet que você precisa mais em qualquer lugar: bares, casinos, na rua ... e um curso, de ME.}
{651}{}{Posso ver o que você obteve no estoque?}
{652}{}{Volte para o Mordinos e Jet ...}

# 31. MAKER? (29)
{660}{}{Sim ... (Leias dentro.) ... veja, os Mordinos conseguiram uma mina de ouro lil pelo nome de Myron. Bata o jackpot com ele ... veja,
 Ele fez um jato.}
{662}{}{O suficiente sobre os Mordinos e as famílias por enquanto. Conte-me sobre este Myron ...}

# 32. DISTRIBUTION? (29)
{670}{}{Eles bombeiam tudo para New Reno, para iniciantes. Para o norte até o Den, e também ... uh ... (Pega-se, então encolhe os ombros e continua).
 ... bem, também está fazendo a Redding hoje em dia, também, que não prejudica a bolsa Mordinos nenhuma.}
{672}{}{Conte-me sobre Redding.}

# 33. REDDING? (32)
{685}{}{Não é muito para dizer. Cidade da mineração noroeste do 'aqui. A palavra é, Mordino quer ter alguma influência lá, obter alguns dos
 Que Redding GOLD eles desenterram. Então ele os envia jet, eles enviam ouro, todos felizes.}

# 34.  TELL ME ABOUT SALVATORES (25)
{695}{}{Conjunto silencioso. Eles são liderados por Louis Salvatore, um gângster original começando nos anos. O seu território está no lado ocidental;
 O berço deste bar chamou Salvatore's na 2nd Street. Não esteja fazendo problemas lá.}
{696}{}{Por que não?}

# 35.  WHY NOT? (34)
{710}{}{Alguns conselhos gratuitos: Você vê um Salvatore, mantenha a cabeça baixa na boca fechada, ou eles vão cortá-lo em dois. Eles conseguiram o melhor
 Poder de fogo desse lado de Cee-Ay, então ninguém com um pouco de senso foda com eles, entende?}
{711}{}{Que tipo de "poder de fogo" tem os Salvatores?}
{712}{}{Parece que eles conseguiram uma merda muito pesada. O que eles estão empacotando?}
{715}{}{Interessante ... obrigado pelo aviso.}

# 36.  WHAT KIND OF WEAPONS TO THE SALVATORES HAVE? (35)
{725}{}{Pistolas ... 'cept eles disparam LUZ. Agora, Reno é uma cidade de luzes, mas a luz que essas pistolas brilham pode cortar um homem em
 Dois ... * swuppp * ... (Jules faz o movimento de fatiamento.) Faz uma queima limpa entre as duas metades, sim.}
{726}{}{Eles disparam a luz? Eles chamam as pistolas a laser das pistolas?}
{727}{}{Certamente terei cuidado, então. Você pode me falar sobre as outras famílias?}

# 37.  WHAT KIND OF WEAPONS TO THE SALVATORES HAVE? (36)
{735}{}{Bem, eu realmente não sei ... Não tenho certeza do que você está falando. Mas pegue minha palavra para isso: não pergunte
 Os Salvatores sobre essas pistolas. Eles têm esse hábito estridente que matam pessoas curiosas.}
{736}{}{Por "pistolas laser", Jules, quero dizer pistolas que emitem feixes de luz coerente. Um feixe de potência suficiente - digamos, vários
 Megawatts - poderia causar danos consideráveis   se focado em um alvo por alguns segundos, produzindo o efeito que você descreveu.}
{737}{}{Eles sempre tiveram essas pistolas?}

# 38.  WHERE ARE THEY COMIN' FROM (37)
{750}{}{Eles nem sempre os tinham ... senão eles estavam no comando de New Reno ... TODO o novo Reno. Por enquanto, são apenas
 Construindo em silêncio. Essas pistolas apareceram ... talvez alguns meses atrás, "no tempo do massacre".}
{751}{}{Massacre?}

# 39.  MASSACRE? (38)
{765}{}{Ah, sim ... dois meninos de Salvatore com aquelas pistolas mataram os homens de uma brigada buncha e derrubaram alguns meninos de Mordino que
 Estava tentando entrar no West Side. Desde então, as outras famílias se afastaram dos Salvatores.}
{766}{}{Definitivamente, parece com lasers. Você sabe como os Salvatores conseguem suas pistolas a laser? Eles empregam baterias,
 Células de fusão ou sistemas de energia cabos de qualquer tipo?}
{767}{}{Alguma idéia de onde eles estão tirando essas pistolas?}

# 40.  ANY IDEA WHERE THEY GET THE LASER WEAPONS? (39)
{780}{}{Não há ideia, amigo, eu não estou perguntando, e você não deve ... tomar meu conselho. Você está procurando armas, existe
 Outros ... mais seguros ... lugares que você pode tentar.}
{781}{}{Gosta de onde?}
{782}{}{Conte-me mais sobre as famílias.}

# 41.  BY LASER PISTOLS I MEAN (37, 39)
{795}{}{Uh ... agora, eu não sei sobre isso, e ... hmmmm. Sabe, você fala como um deles em branco nos estábulos. Você não é
 um deles?}
{796}{}{Estábulos?}

# 42.  STABLES? (41)
{810}{}{(Leans in.) Agora, eu não quero continuar com os mais agradáveis   novos sites de Reno, mas há uma blusa branca buncha
 Quem fala como você neste prédio, o Stables, norte da cidade. Muito guardado pelos homens de Mordino.}
{811}{}{O que eles fazem lá?}

# 43.  WHAT DO THEY DO? (42)
{825}{}{Teste novos tipos de Jet, do que eu ouço. Agora, estou lhe dizendo isso em CONFIANÇA, amigo: não vá cutucando
 Lá ... os Mordinos não gostam de visitantes. 'Lados ... Jules pode lhe fornecer todos os jatos que você precisa.}
{826}{}{Por que os Mordinos continuam testando o Jet? Parece que está formando hábitos como é.}
{827}{}{A quem os Mordinos testam os chems?}
{828}{}{Do you know how I can get into the Estábulos?}

# 44.  WHO DO THEY TEST IT ON? (43, 45, 46, 47)
{840}{}{Escravos, praticamente. Mantenha-os em bancas nos estábulos, como brahmin.}
{841}{}{Mordinos compra um grupo de escravos que passam.}
{842}{}{Mordinos compra um grupo de pessoas escravas como você que passam por New Reno.}
{843}{}{Eles também compram muito, porque os escravos continuam ficando doentes, fugindo ... ou morrem. Principalmente morrem.}

# 45.  WHY DO THEY KEEP TESTING JET? (43, 44, 46, 47)
{860}{}{Apenas para melhorá-lo, acho, aperfeiçoe o processo, refine o químico. Jet é bom, mas se eles conseguem fazer isso mesmo
 MELHOR ... diferença entre raspar o céu e voar para a lua, suponho.}

# 46.  ANY IDEA HOW I CAN GET IN THERE? (44, 45)
{880}{}{Agora aguarde um minuto - eu nem pensaria nisso se eu fosse você, amigo. Os Mordinos guardam esse lugar como
 Cães raivosos. Basta colocar o pensamento fora de sua mente.}
{881}{}{Deve haver uma maneira de ...}
{886}{}{Tudo bem, nunca mais diga. Obrigado pela informação.}

# 47.  THERE MUST BE A WAY IN . . . (46)
{895}{}{Bem ... se você puder falar tudo bem como você estava fazendo, você poderia passar por um dos casacos brancos lá.
 "Claro, você também pode contratar com os Mordinos e colocar lá ...}

# 48.  TELL ME ABOUT BISHOP (25)
{910}{}{Ha! John Bishop? Não há muito a dizer: Bishop é inteligente, resistente, e ele está procurando por tudo.}
{911}{}{Sim, bem, ele terá que me lutar por isso. Onde está este território de jerk-off?}
{912}{}{Onde está seu território?}

# 49.  TELL ME ABOUT BISHOP (48)
{925}{}{Ele anda no Shark Club na 2ª Rua. Ele está cercado por guardas, então não vá fazer uma visita a menos que você tenha REAL
 Negócios com ele. (Smiles evily.) E mantenha seu negócio longe de sua esposa. E a filha dele.}
{926}{}{Uh, negócios?}
{927}{}{Não há perigo disso.}

# 50.  BID-NESS (49)
{935}{}{Você sabe o que quero dizer, irmão. Apenas fique longe deles dois, "menos o pensamento de estar na lista do Bispo é algo"
 você gosta.}
{936}{}{Bem, talvez assim, mas o que você conseguiu entre suas pernas não importa ... para Missus Bishop, pelo menos. Ela balança como uma porta do salão.}
{937}{}{Uh, conte-me mais sobre as famílias.}

# 51.  TELL ME ABOUT WRIGHT (25)
{945}{}{Os Wrights? Heh. Os Wrights são a única familia que é a família. As outras famílias, veja, eles receberam mercenários
 E tumbleweeds para músculo, mas a família Wright é a família Wright, entende?}
{946}{}{Tenho um aviso para você onde os Wrights estão preocupados, escravos ... veja, os Wrights são a única família que é a família.}
{947}{}{Eles são familiares? Quantos existem?}

# 52.  TELL ME ABOUT WRIGHT 2 (51)
{960}{}{Quase vinte ou mais Wrights de sangue verdadeiro. Significa como cuspir e cada um deles mais feio que o próximo.}
{961}{}{Quase vinte ou mais Wrights de sangue verdadeiro, e eles não aceitam gentilmente as pessoas em sua linha de trabalho. Palavra é, eles
 Perdeu uma irmã de volta quando a um escravo, e eles não gostam de escravas desde então.}
{962}{}{O que o Wrights controla em New Reno?}

# 53.  WHAT DO WRIGHTS CONTROL? (52)
{975}{}{Eles não recebem nenhum casino, eles lidam principalmente com álcool e vendem para as outras famílias. Então, se você estiver olhando
 Para hootch ... eles ficam no lado leste da cidade em uma grande mansão.}

# 54.  WHERE CAN I GET SOME DRUGS? (19, 28)
{985}{}{Irmão, você não precisa olhar mais longe do que o próprio Jules.}
{986}{}{Irmã, você não precisa olhar mais longe do que o próprio Jules.}
{987}{}{Minha doce irmã, você não precisa olhar mais longe do que o próprio Jules.}
{988}{}{Eu entendi tudo, e se eu não conseguir, você não quer isso. Devemos chegar à bizness?}
{989}{}{Certo. Vamos lidar.}
{990}{}{Que tipo de chems posso entrar no New Reno?}
{991}{}{Não agora. Tive algumas outras questões ...}
{992}{}{Na verdade, não estou interessado em nenhum problema agora. Eu tenho que ir.}

# 55.  WHAT KIND OF DRUGS CAN I GET IN NEW RENO? (54)
{1005}{}{Todos os KINDS o 'shit. Eu tenho uma merda, faça você ficar excitado, faça sua mulher excitada, faça você duro, faça você feliz, faça você forte,
 Torná-lo inteligente ... e, claro, eu consegui o químico, a merda que vai deixar voar ... Jet.}
{1006}{}{Todos os KINDS o 'shit. Eu tenho uma merda, fico excitado, faço você molhar, esvaziá-lo, acalme-se, faça sexo com você, faça você feliz,
 Torná-lo forte, torná-lo inteligente ... e, claro, eu tenho a merda que vai deixar você voar ... Jet.}
{1008}{}{De onde vem Jet? Sempre foi por aí?}

# 56.  WHERE DOES JET COME FROM? (55)
{1025}{}{Bem ... uh ... Jet vem daqui ... Reno, quero dizer. Não há muito tempo, mas está em DEMANDA, sabe o que estou dizendo? (Winks.)
 Numero um porque nós conseguimos turistas como você.}
{1026}{}{Bem, estou olhando para comprar alguns chems. Vamos lidar.}
{1027}{}{Mas por que Jet veio daqui?}

# 57.  BUT WHY DOES JET COME FROM HERE? (31, 56)
{1035}{}{Ah, agora ... veja, a família Mordino atingiu o jackpot um dia quando encontraram esse pequeno brainiac chamado Myron. Parece que ele é um
 Natural quando se trata de fazer chems. Ele fez o Jet.}
{1036}{}{Myron, hein? Onde posso encontrá-lo?}

# 58.  WHERE CAN I FIND HIM? (57)
{1045}{}{(Leans in.) Agora, eu não quero continuar com os sites menos agradáveis   do New Reno, mas há esse edifício, The Stables,
 Norte da cidade. Muito conservado pela família Mordino. É aí que está Myron.}
{1046}{}{Estábulos fora da cidade?}

# 59.  WHERE CAN I FIND HIM? (58)
{1055}{}{Sim, Mordinos mantém o garoto dourado lá, dá-lhe batatas fritas, putas, qualquer coisa que ele quiser, enquanto ele faz chems. Jato
 Era o seu mais importante. Não se vê nada tão hábito em muito tempo. Voltou Reno, o fez.}
{1056}{}{Penso que eu poderia encontrar este Myron?}

# 60.  THINK I COULD MEET THIS MYRON? = FEMALE (59)
{1065}{}{(Jules pára e estuda você, seus olhos se deslocam para cima e para baixo em seu corpo).}
{1066}{}{Jules? Olá? Perguntei se havia alguma maneira de encontrar Myron.}

# 61.  THINK I COULD MEET THIS MYRON? (59, 60)
{1075}{}{Whoa, agora, irmão, aqui está um conselho gratuito: você não vai procurar Myron, porque os Mordinos pegarão vento, E eles vão te destruir e deixar
 Você morre no Gólgota.}
{1076}{}{Eu não estaria tentando. Se você precisar de Jet, não vá ver Myron, porque você pode obtê-lo de mim. Mordinos se aproxima de você
 Ao ver Myron, eles vão te destruir e deixá-lo morrer no Gólgota.}
{1077}{}{Bem, agora ... Você pode vê-lo. A coisa é, os Mordinos pegarem o vento, eles vão te destruir e deixá-lo morrer
 Gólgota.}
{1078}{}{Não havia nenhuma maneira de vê-lo?}
{1079}{}{Por que eu poderia vê-lo?}
{1080}{}{Por que você estava me estudando como uma escultura um segundo atrás?}
{1081}{}{Gólgota? What's that?}
{1083}{}{Interessante. Obrigado pela informação.}

# 62. UH, GOLGOTHA? (61, 63, 64)
{1101}{}{Não havia nenhuma maneira de ver Myron?}
{1102}{}{Por que eu poderia ver o Myron?}
{1103}{}{Por que você estava me estudando como uma escultura um segundo atrás?}

# 63.  WHY WOULD I BE ABLE TO SEE HIM (61, 62)
{1115}{}{Eu estava fazendo aquilo porque eu estava vendo se você fosse o tipo de Myron, mas você não olha isso. Talvez se você se limpar
 Alguns, Myron'd lhe deu uma segunda olhada ... veja, ele gosta das mulheres.}
{1116}{}{(Leers.) Porque, querida, você está bem. E Myron gosta de mulheres que se vejam BOM.}
{1117}{}{Boy é como um coelho, e SEMPRE está procurando um novo remendo de repolho.}
{1118}{}{What was that about Gólgota?}
{1119}{}{Uh, ótimo. Obrigado pela dica, Jules. Diga, eu tive algumas outras perguntas ...}
{1120}{}{Bem, nessa nota, acho melhor eu ir.}
{1121}{}{Quão eloquente. Quando você fala, é poesia - o uso de "patch de repolho" produz imagens surpreendentes. Obrigado.}

# 64.  ISN'T THERE ANY WAY I COULD SEE HIM? (61, 62)
{1130}{}{Se você fosse uma mulher bonita, talvez, senão, você precisaria primeiro da permissão dos Mordinos. Ambos não são
 Muito provável.}
{1132}{}{Entendo. Diga, eu tive algumas outras perguntas ...}

# 65.  I'M LOOKING FOR SOME HEAVY FIREPOWER. (19, 40)
{1145}{}{Você quer armas, você vai ver o meu homem Eldridge no West End. Ele pegou uma merda que vai matar pessoas que você ainda não está pronto.
 Diga-lhe que enviei você.}
{1146}{}{Eu ouço você, irmão, eu ouço você. Você quer o melhor, você vai ver o meu homem Eldridge no West End. Ele pegou uma merda que vai matar
 Pessoas que você ainda não está com o MET. Diga-lhe que enviei você.}
{1147}{}{Eu ouço você, irmã, eu ouço você. Você quer o melhor, você vai ver o meu homem Eldridge no West End. Ele pegou merda que vai
 Mate pessoas que você ainda não está com o MET. Diga-lhe que enviei você.}
{1148}{}{Doce, você já comeu alguma merda séria com esse seu corpo. Ainda assim, se você quiser mais, vá ver meu homem
 Eldridge no West End. Ele pegou uma merda que vai matar pessoas que você ainda não está pronto. Diga-lhe que enviei você.}
{1150}{}{Obrigado pela dica, acho melhor eu ir.}

# 66.  I'M LOOKING FOR SOME SUPPLIES. (19)
{1165}{}{Você precisa de alguns suprimentos? Bem, você pode ver Renesco no West End ... mas aqui está a captura: não compre nenhum chems
 Dele, porque eles não são seguros. Ele tem suprimentos tudo bem, mas se você quiser chems, fale comigo.}
{1166}{}{Eu vou manter isso em mente. Diga, eu tinha mais algumas perguntas ...}
{1167}{}{Seus chems não estão seguros, né? Bem, obrigado pela dica, acho melhor ir.}

# 67.  I WANT TO GET LAID. (19)
{1175}{}{Eu ouço você, irmão. A maioria dos tURISTAS, veja, eles atravessam a rua Virgin e ficam atraídos por uma meretriz de dois chips.
 Você parece que você tem aula, então vá até a Pata do gato 'atravessar a rua lá. Diga-lhes que Jules enviou você.}
{1176}{}{Eu ouço você, irmã. A maioria dos tURISTAS, veja, eles atravessam a rua Virgin e ficam chupados por algum glitterboy.
 Você parece que você tem aula, então vá até a Pata do gato 'atravessar a rua lá. Diga-lhes que Jules enviou você.}
{1177}{}{(Sorria, levanta os braços.) Não olhe mais longe, minha doce irmã. Jules está a seu comando.}
{1178}{}{Uh, obrigado, Jules, mas não. Diga, eu tinha mais algumas perguntas ...}
{1180}{}{Bem, obrigado pela dica. Acho que é melhor eu ir.}
{1181}{}{Bem, obrigado de qualquer forma, mas acho melhor ir.}

# 68.  VAULT 13. (19)
{1190}{}{Você quer dizer Vault CITY, não é? Isso é para o nordeste. Não pode perder, todas as trilhas da caravana conduzem diretamente a isso.}
{1191}{}{Tudo certo. Diga, eu tinha mais algumas perguntas ...}
{1192}{}{Bem, obrigado pela dica. É melhor eu ir.}

# 69.  GECK (19)
{1200}{}{Jardim de wha? Que algum tipo de chem? O que essa "coisa Garden" faz? Você está bem?}
{1201}{}{Não, é ... bem, nunca perca. Tive algumas outras questões ...}
{1202}{}{Deixa pra lá. Eu realmente estou melhor indo.}

# 70.  MY TRIBE (19)
{1210}{}{Não sei nada sobre isso. Desculpe pela sua perda. Talvez fossem escravas?}
{1211}{}{Poderia ser. Tive algumas outras questões ...}

# 71.  TANKER (19)
{1220}{}{Um que?}
{1221}{}{Esqueça. Tive algumas outras questões ...}

# 72.  RICHARD WRIGHT (17)
{1230}{}{Uh ... Wright, garoto? Sim, eu ouvi sobre isso. Uma pena vergonha. Os filhos de sua idade não deveriam estar fazendo chems. Eles conseguiram tanto
 Para viver sem ser dado merda impura.}
{1231}{}{Falando em merda impura, Renesco disse que vende Jet atado com arsênico.}
{1232}{}{O que você quer dizer, "merda impura?"}
{1233}{}{Você sabe alguma coisa sobre este vaso de jato vazio?}
{1234}{}{Interessante, você deve dizer isso ... Eu não acho que ele tenha overdosed no Jet. Acho que ele foi envenenado.}

# 73.  IMPURE SHIT (85)
{1250}{}{(Shrugs.) Alguns comerciantes não se importam com o que vendem, e as pessoas morrem. Agora não digo nada, mas eu verificaria com ol '
 Renesco o Rocketman e veja como é boa a sua merda.}
{1251}{}{Eu chequei com Renesco ... ele disse que vende Jet atado com arsênico.}
{1252}{}{Reno é um grande lugar, Jules. Qualquer outra pessoa que possa ser responsável?}
{1253}{}{Tive algumas outras questões ...}
{1254}{}{Tudo certo. Vou verificá-lo.}

# 74.  DEALERS (73)
{1270}{}{Os comerciantes da Lotta na cidade ... Lil 'Jesus Mordino, talvez, mas por que ele vendeu para um Wright não faz sentido. Há Jagged
 Jimmy J na 2ª rua, ao norte daqui, mas ele é pequeno. Eu ainda verificaria com Renesco, no entanto.}
{1272}{}{"Jagged Jimmy J?" Quem é aquele?}
{1273}{}{Lil 'Jesus Mordino? Onde posso encontrá-lo?}
{1274}{}{Maybe I will. Say, Tive algumas outras questões ...}
{1275}{}{Lil 'Jesus ... Jagged Jimmy J ... Renesco. Consegui. Obrigado.}

# 75.  WHAT DO YOU EXPECT? (17)
{1290}{}{(O sorriso de Jules morre.) Eu olho para pessoas como você que estão entrando em Reno. Este é o ponto principal para lidar. Além disso, certo
 Os estabelecimentos me pagam para encaminhar os recém-chegados. QUE uma resposta boa o suficiente para você?}
{1291}{}{Sim. Agora eu preciso da resposta para algumas outras perguntas ...}
{1292}{}{Apenas curioso. Obrigado pela honestidade.}

# 76.  CAR STOLEN (ACT INNOCENT) (17)
{1305}{}{Seu CARRO? Você tem certeza que você estacionou aqui? Não fui visto.}
{1306}{}{O que, de repente, você se sentiu cego? Você vê meu FIST, mãe fucker? Você vê?!! Agora me diga novamente que você não viu meu
 Carro ... eu foda-me.}
{1307}{}{Jules, se você não me disser o que aconteceu com o meu carro, eu direi à família Wright. VOCÊ vendeu seu filho o Jet que
 matou ele. Você estará morto dentro de uma hora. Conversa.}
{1308}{}{ASSIM QUE você não viu, Jules?}
{1309}{}{Sim, tenho certeza de que o estacionei aqui. Alguma idéia de onde pode ser?}
{1310}{}{All right then. Tive algumas outras questões ...}
{1311}{}{É melhor ir procurar por ele.}

# 77.  YOU SURE YOU HAVEN'T SEEN IT? (76)
{1320}{}{Naw, irmão, eu não fui visto.}
{1321}{}{Naw, irmã, eu não fui visto.}
{1322}{}{Eu vou ficar de olho por isso, no entanto. (Shrugs.) Ainda assim, Reno é um grande lugar ...}
{1323}{}{Jules, eu tenho esse FILHO louco que você sabe onde meu carro foi. Se você não me diz onde está, eu vou usá-lo para
 Prática alvo. Agora fale.}
{1324}{}{Thanks anyway. Tive algumas outras questões ...}

# 78.  CAR STOLEN (CAUGHT) (76, 77)
{1340}{}{Irmã, eu não sei nada sobre seu carro.}
{1341}{}{Irmão, não conheço nada sobre o seu carro.}
{1342}{}{Não vi o que aconteceu com isso, e não sei onde está.}
{1343}{}{(Ele lançou um olhar odioso a Cody, atravessando a rua).}
{1344}{}{Mesmo? Isso me parece uma carga de SHIT.}
{1345}{}{É assim? Eu sei que você fez algo com isso, então é melhor me dizer onde é antes de fazer algo com você.}
{1346}{}{Deixa pra lá então. Eu continuarei procurando por isso.}

# 79.  ALL RIGHT, ALL RIGHT (78)
{1360}{}{Tudo bem, irmão, tudo bem!}
{1361}{}{Tudo bem, irmã, tudo bem!}
{1362}{}{... Eu vi alguns rapazes pegar o carro há pouco tempo. Mas havia muitos deles para eu parar, você sabe, e -}
{1363}{}{Cala-te e leva-me para onde eles foram. Agora.}
{1364}{}{Deixa pra lá. Eu vou buscá-los sem sua ajuda.}

# 80.  FOLLOW HIM (79)
{1375}{}{Está bem, está bem…}
{1376}{}{By the way ... Jules? Se você tanto como GLANCE o caminho errado naquela criança do outro lado da rua, eu vou voltar e matar
 Você tantas vezes você vai precisar de testamentos múltiplos. Compreendo? Agora, dirija.}
{1377}{}{Mais uma coisa, Jules: eu tanto quanto ouvi que você estava mexendo com Cody, eu vou matar você. Agora, leve-me para
 Onde está o meu carro.}
{1378}{}{(Siga-o.)}

# 81. INTRO, CODY = DEAD (WTG)
{1385}{}{H ... ei. (Smiles incômodo. Sua colônia chega em você como uma onda.) Nome Jules. O que você precisa, meu amigo, hein? A ... alguma coisa?}
{1386}{}{H ... ei. Ei, bem-vindo de volta! (Sorria incómodo. Sua colônia bate em você como uma onda.) O que você precisa de Jules, meu
 Amigo, hein? A ... alguma coisa?}
{1389}{}{Eu tive algumas perguntas ...}
{1390}{}{Colonia agradável, Jules. Eu cheirei tudo no corpo de Cody. Você está morto.}
{1391}{}{Cody está morto, Jules. Eu aposto que você era responsável. Você está morto.}

# 82.  RUN (81)
{1405}{}{H-hey, eu desejo que eu poderia ajudar, mas não sei nada ... olha, eu tenho que ir.}
{1406}{}{Colonia agradável, Jules. Eu cheirei tudo no corpo de Cody. Você está morto.}
{1407}{}{Cody está morto, Jules. Eu aposto que você era responsável. Você está morto.}
{1408}{}{Vejo você, Jules.}

# 83.  JJJ? (74, 84)
{1415}{}{Ele é este idiota sonuvabitch que pensa que ele é um negociante de grandes tempos. Você não pode sentir falta dele ... seu rosto está marcado.
 O tolo estava voando no Jet uma noite e tentou se barbear com uma faca de combate. A parte triste é que não MATA "eu".}
{1416}{}{And Lil 'Jesus Mordino? Onde posso encontrá-lo?}
{1417}{}{Lotta love in this town...say, Tive algumas outras questões ...}

# 84.  LIL' JESUS? (74, 83)
{1425}{}{Bem, amigo, eu terei o cuidado de entrar e acusar Lil 'Jesus de qualquer coisa. Mas se você REALMENTE quiser
 Conversa com ele, não vou parar com você. Ele sai no Desperado, atravessa a rua lá.}
{1426}{}{And "Jagged Jimmy J?" Quem é aquele?}
{1427}{}{Say, Tive algumas outras questões ...}

# 85.  POISONED (72)
{1435}{}{Não me surpreende ... esse tipo de coisa parece acontecer muito nesta cidade.}
{1436}{}{O que você quer dizer com isso?}
{1437}{}{O que você pode me falar sobre este vaso de jato vazio?}
{1439}{}{Entendo. Bem, obrigado pelo seu tempo.}

# 86.  JET CANISTER (85, 72)
{1450}{}{(Olhares para isso.) Como cem outros que eu vi. Não é meu, porém ... poderia ser Jagged Jimmy J ou Renesco's.}
{1451}{}{Jagged Jimmy J?}
{1452}{}{Renesco?}
{1453}{}{Hmmm. Tive algumas outras questões ...}

# 87.  JJJ 2? (86)
{1470}{}{Ele é este montuoso filho na segunda rua, ao norte daqui. Você não pode sentir falta dele ... seu rosto está marcado. o
 O tolo estava voando no Jet uma noite e tentou se barbear com uma faca de combate. A parte triste é que não MATA "eu".}
{1471}{}{E Renesco? Onde posso encontrá-lo?}
{1473}{}{Consegui. Obrigado.}

# 88.  RENESCO? (86, 87)
{1485}{}{Ele é este velho cracker que administra uma farmácia na Commercial Row ... suba algumas ruas para o norte, vire à esquerda onde Salvatore's
 E o casino do bispo se encontra, então continue indo por aquela rua. Está à direita.}
{1486}{}{E "Jagged Jimmy J?" Onde posso encontrá-lo?}
{1487}{}{All right...say, Tive algumas outras questões ...}

# 89.  ARSENIC? (72, 73, 74)
{1500}{}{Você diz a essa cadela que ele continua falando como essa, e 'eu vou matar' antes do velho Wright. Você sabe que tipo
 De conversa que é? É a conversa de um homem que é SCARED, é o que é isso.}
{1501}{}{I see...say, Tive algumas outras questões ...}
{1502}{}{Eu te escuto. Eu vou verificá-lo.}

# CAR FLOATER
{2000}{}{Que um CARRO? Daaaamn.}
