# QUICK LOOKS
{100}{}{Você vê um viciado em aparência perdida.}
{101}{}{Você vê um viciado hiperativo.}

# EXAMINES
# 1. [MALE, CRASH AND BURN]
{150}{}{Você vê um viciado em aparência perdida. He is moving very slowly.}
{151}{}{Você vê um viciado em aparência perdida. He looks ill.}
{152}{}{Você vê um viciado em aparência perdida. He is so thin, he looks like he would break in a strong wind.}
{153}{}{Você vê um viciado em aparência perdida. He is looking at you blearily.}
{154}{}{Você vê um viciado em aparência perdida. His eyes are so bloodshot it looks like he could cry bloody tears.}
{155}{}{Você vê um viciado em aparência perdida. Every time he moves, he winces, as if being stabbed with needles.}
{156}{}{Você vê um viciado em aparência perdida. There are bags under his eyes and a pained expression on his face.}
# 2. [MALE, HIGH ON JET]
{160}{}{Você vê um viciado. Ele tem uma expressão feliz no rosto.}
{161}{}{Você vê um viciado. Ele está sorrindo um pouco e se mudando para uma batida invisível.}
{162}{}{Você vê um viciado. Ele está olhando para o espaço.}
{163}{}{Você vê um viciado. Ele sorri e acena com algo além da orelha.}
{164}{}{Você vê um viciado. Ele continua tocando seu rosto e murmurando para si mesmo.}
{165}{}{Você vê um viciado. Apesar das malas sob seus olhos, ele está sorrindo como se ele tivesse ganhado a loteria.}
# 3. [FEMALE, CRASH AND BURN]
{170}{}{Você vê um drogado desperdiçado. Ela está se movendo muito devagar.}
{171}{}{Você vê um drogado desperdiçado. Parece que ela não comeu em meses.}
{172}{}{Você vê um drogado desperdiçado. Ela é tão fina, parece que ela quebraria em um vento forte.}
{173}{}{Você vê um drogado desperdiçado. Seus olhos são como fusos queimados.}
{174}{}{Você vê um drogado desperdiçado. Ela está olhando para você com avidez.}
{175}{}{Você vê um viciado desperdiçado com olhos inJetados.}
{176}{}{Você vê um viciado em aparência perdida. Every time she moves, she winces, as if being stabbed with needles.}
{177}{}{Você vê um drogado desperdiçado. Há bolsas debaixo de seus olhos e uma expressão dolorida em seu rosto.}
# 4. [FEMALE, HIGH ON JET]
{180}{}{Você vê um viciado. Ela tem uma expressão feliz em seu rosto.}
{181}{}{Você vê um viciado. Ela está chorando e sorrindo ao mesmo tempo.}
{182}{}{Você vê um viciado. Ela está sorrindo e dançando para uma música invisível.}
{183}{}{Você vê um viciado. Ela está olhando para o espaço e suspirando.}
{184}{}{Você vê um viciado. Ela sorri e acena com algo além da orelha.}
{185}{}{Você vê um viciado. Ela continua coçando as mãos.}
{186}{}{Você vê um viciado. Ela está dobrando e tecendo e mal consegue se levantar em linha reta.}
{187}{}{Você vê um viciado. Apesar de sua aparência esfarrapada, ela está sorrindo como se ela tivesse acabado de ganhar a loteria.}

# FLOAT DIALOGUE:
# 5. JUNKIE=WASTED; ENCLAVE DESTROYED IS TRUE
{200}{}{:: Cheers, então winces ::}
{201}{}{:: Claps fracamente, estremecendo quando ele bate}
{202}{}{:: Apito seco ::}
# 6. JUNKIE=STONED; ENCLAVE DESTROYED IS TRUE
{210}{}{Você é o melhor ... uh, algo. Você é o melhor ALGO!}
{211}{}{:: Howls ::}
{212}{}{, Você é melhor do que JET!}
{213}{}{:: Cheers wildly ::}
{214}{}{:: Claps wildly ::}
{215}{}{:: Whistles ::}
# 7. JUNKIE = WASTED
{220}{}{Minha cabeça…}
{221}{}{Acumule e queime ... quebre e queime ...}
{222}{}{Feriu pior do que a última vez ...}
{223}{}{E acho que vai ser um longo, longo tempo ...}
{224}{}{:: Ooooooh ::}
{225}{}{:: Cries ::}
{226}{}{:: Tosse ::}
{227}{}{:: Scratches self ::}
{228}{}{:: Mumbles to self ::}
{229}{}{Não posso ... não posso continuar como ... isso ...}
{230}{}{Você viu Jules? Preciso de uma correção.}
{231}{}{Você viu Jagged Jimmy J ao redor? Preciso de uma correção.}
{232}{}{Estou procurando a Farmácia de Renesco. Renesco me preparou.}
{233}{}{Eu sei que o Fallout 2 não é um Jogo em 3D, mas ainda deve apoiar meu novo cartão 3DFX.}
# 8. JUNKIE = HIGH
{240}{}{[Canta.] Eu ... só quero voar. Coloque seus braços em volta de mim, baby, coloque seus braços em volta de mim, bebê.}
{241}{}{[Canta.] Rocketman, queimando o mmmmumble lá sozinho ...}
{242}{}{Cuidado! Pink deathclaw, três horas do dia!}
{243}{}{Muitas luzes! Queimando meus olhos, queimando meus olhos ...}
{244}{}{As luzes estão ... muito brilhantes ... :: Começa a chorar ::}
{245}{}{Reeeeee-no. Reeeeee-no. Reno?}
{246}{}{Onde eu deixei minha cabeça?}
{247}{}{Beber - cerveJas - fumar - erva daninha}
{248}{}{Snootchie Boochies}
{249}{}{:: Giggles ::}
{250}{}{:: Risos ::}
{251}{}{:: Sorrindo e balançando ligeiramente ::}
{252}{}{Wheeeeeeee}
{253}{}{Linda rua. Bela parede. Bastante apedreJado.}
{254}{}{Whoa ... onde o céu foi ...?}
{255}{}{Se minhas roupas não parem de falar comigo, eu vou tirá-las.}
{256}{}{Meus sapatos estão respirando.}
{257}{}{Eu sei que o Fallout 2 não é um Jogo em 3D, mas ainda deve apoiar meu novo cartão 3DFX.}
{258}{}{Você está me olhando ?! Você está me olhando? !! Eu vou matar você!}
# 9. JUNKIE=WASTED; ENCLAVE DESTROYED IS TRUE
{270}{}{Uh, eu torceria sua vitória sobre o Enclave, mas minha cabeça está batendo demais. Volte de noite.}
{271}{}{:: Tenta aplauso, continua faltando ::}
{272}{}{Maneira de ir. Eu estava muito alto para ver o que você fez, mas tenho certeza que foi legal.}
{273}{}{Uh ... obrigado por nos salvar. Você, obteve algumas fichas extras de sobra?}
{274}{}{Eu também salvei o mundo uma vez. Eu acho que. Talvez eu estivesse alta.}
{275}{}{O Enclave tem algum Jet?}
{276}{}{Você é quem causou esse grande boom para o sul? Isso me doeu a cabeça.}
{277}{}{Eu sei que você salvou o mundo, mas somos NPCs menores que têm que lidar com as conseqüências.}
{278}{}{Chris Avellone me proJetou, Tom French me escreveu, então tecnicamente, eu não sou responsável por
 Meu vício de Jet.}
{279}{}{Sim, sim, é ótimo que você tenha resolvido o Jogo. Claro, isso significa que você estará excluindo todos
 Nós de seu disco rígido em breve. Muito obrigado.}
# 10. JUNKIE=STONED; ENCLAVE DESTROYED IS TRUE
{291}{}{Você é o melhor ... uh, algo. Você é o melhor ALGO!}
{292}{}{, Você é melhor do que JET!}
{293}{}{Cara, eu gostaria de poder ver esse explosivo enquanto eu estava alto. Musta foi alguma coisa, hein?}
{294}{}{Eu te amo! Você é um HERÓI. UM HERÓI GODDAMN. EU PODERIA ABRAÇAR-LHE PARA A MORTE.}
{295}{}{Da próxima vez que você chutar o traseiro do Enclave, venha me pegar primeiro, e nós o faremos JUNTO.}
{296}{}{Arrebentar,}
{297}{}{Eu sei que você salvou o mundo, mas somos NPCs menores que têm que lidar com as conseqüências.}
{298}{}{Você deve Jogar o Jogo novamente como um personagem baseado em quimica. Mesmo! Pegue o Chem Reliant Trait!
 EU AMO esse.}
{299}{}{Obrigado por nos salvar. Eu te beiJaria se não estivesse vomitando.}
{300}{}{Eu poderia ter derrotado o Enclave eu mesmo se eu tivesse levado bastante Jet.}
{301}{}{[Canta.] "Não precisamos de outro herói, não precisamos saber o caminho de casa ..."}
{302}{}{Chris Avellone me proJetou, Tom French me escreveu, então tecnicamente, eu não sou responsável por
 Meu vício de Jet.}
{303}{}{Vamos Juntar um pouco Jet e celebrar a sua vitória. Você está comprando.}
{304}{}{Depois de excluir este Jogo do disco rígido, existiremos?}
{305}{}{Uh ... que tipo de teste de quimica estava fazendo o Enclave? Havia Jato grátis?}

# CLICK DIALOGUE:
# 11. JUNKIE = WASTED, PLAYER = POWER ARMOR
{320}{}{Como você vai ao banheiro com essa coisa?}
{321}{}{Uh ... você está falando comigo?}
{322}{}{Oh cara, essas DTs devem estar piorando. Agora, as pessoas metálicas estão falando comigo.}
{323}{}{Alguém trouxe metal para você?}
{324}{}{Eh, uh ... você tem algum Jet lá?}
{325}{}{Poupe algumas fichas ...? Uh, nunca perca.}
{326}{}{:: Bates na sua armadura :: Olá? Alguém em casa?}
{327}{}{Você é algum tipo de híbrido frigorífico-humano estranho?}
{328}{}{Isso fica quente lá?}
# 12. JUNKIE = WASTED, PLAYER = SLAVER
{350}{}{Me dê algum Jet, e posso dizer onde você pode encontrar algumas capturas fáceis por aqui, o escravo.}
{351}{}{Você pode ter meus filhos, escravos, se você tiver algum Jet para pagar por eles ...}
{352}{}{Apenas algumas fichas, e eu serei seu escravo ... apenas deixe-me ir buscar Jet Jet primeiro.}
{353}{}{Eu serei seu escravo, se você puder me dar um pouco de Jet.}
{354}{}{Você pode me vender na escravidão se você me der um Jato.}
{355}{}{Não, cara, estou fora de chems. Uh ... por quê? Você está comprando?}
# 13. JUNKIE = WASTED, PLAYER = PRIZEFIGHTER OR MADE MAN
{360}{}{Você é lutador? Você pegou algumas fichas que eu emprestei?}
{361}{}{Vamos, dê apenas algumas fichas.}
{362}{}{Ken empresto algum dinheiro? Olha, vou te pagar de volta.}
{363}{}{Eh, uh ... você tem algum Jet?}
{364}{}{Cara, eu preciso voar, * saber o que estou dizendo?}
{365}{}{Eu realmente preciso de algum remédio para o meu filho. Me aJude.}
{366}{}{Poupe algumas fichas?}
{367}{}{Eu só preciso de algumas fichas para comprar comida ...}
{368}{}{Eu serei seu escravo, se você puder me dar um pouco de Jet.}
{369}{}{Você pode me vender na escravidão se você me der um Jato.}
{370}{}{Não, cara, estou fora de chems. Uh ... por quê? Você está comprando?}
{371}{}{Você é um membro do}
{372}{}{Posso emprestar algumas fichas ...? Vamos, eu sou bom para isso.}
{373}{}{Vou trabalhar para Jet ...}
# 14. JUNKIE = MALE, WASTED, PLAYER = NO REP OR PORN STAR
{380}{}{Ei irmão? Você pode me aJudar a voar?}
{381}{}{Eu farei qualquer coisa que você quiser para alguns chips. Ou Jet, se você conseguiu.}
{382}{}{Você precisa de alguém com quem ficar alto, cara?}
{383}{}{Papai?}
{384}{}{Cara, eu preciso voar, * saber o que estou dizendo?}
{385}{}{Não, cara, estou fora de chems. Uh ... por quê? Você está comprando?}
{386}{}{Psssst. Você pode configurar com algum Jet?}
{387}{}{Posso emprestar algumas fichas ...? Eu pagarei você de volta.}
{388}{}{Vou trabalhar para Jet ...}
{389}{}{Vamos, amigo, dê apenas algumas fichas.}
{390}{}{Ken empresto algum dinheiro? Olha, vou te pagar de volta.}
{391}{}{Eh, uh ... você tem algum Jet, amigo?}
{392}{}{Eu realmente preciso de algum remédio para o meu filho. Me aJude.}
{393}{}{Poupe algumas fichas?}
{394}{}{Eu só preciso de algumas fichas para comprar comida ...that's all…}
{395}{}{Eu vou dormir com você por algum Jet ou algumas fichas. Estou limpo, eu prometo.}
{396}{}{Eu costumava ser o melhor homem aqui em Reno. Posso dar-lhe a scoop para algum Jet ...}
{397}{}{Eu serei seu escravo, se você puder me dar um pouco de Jet.}
{398}{}{Você pode me vender na escravidão se você me der um Jato.}
{399}{}{Ei irmã? Você pode me aJudar a voar?}
{400}{}{Vamos, senhorita, dê apenas algumas fichas.}
{401}{}{Eh, uh ... você tem um Jet, senhorita?}
{402}{}{Olha, preciso voar, saber o que estou dizendo?}
{403}{}{Não, estou fora de chems. Uh ... por quê? Você está comprando?}
{404}{}{Mamãe?}
# 15. JUNKIE = FEMALE, WASTED, PLAYER = MALE, NO REP OR PORN STAR
{420}{}{Ei irmão? Você pode me aJudar a voar?}
{421}{}{Vamos, garoto, dê apenas algumas fichas.}
{422}{}{Eu vou dormir com você por algum Jet ou algumas fichas. Estou limpo, eu prometo.}
{423}{}{Eu sou mais barato que as putas da família. Uh, não diga a eles que estou proxeneta, no entanto.}
{424}{}{Eu farei o que quiser para algumas fichas ... ou Jet, se você entendeu.}
{425}{}{Eu costumava ser a rainha da beleza aqui em Reno. Ainda entendi ...}
{426}{}{Você precisa de alguém com quem ficar alto, cara?}
{427}{}{Não, cara, estou fora de chems. Uh ... por quê? Você está comprando?}
{428}{}{Papai?}
{429}{}{Psssst. Você pode configurar com algum Jet?}
{430}{}{Posso emprestar algumas fichas ...? Eu pagarei você de volta.}
{431}{}{Vou trabalhar para Jet ...}
{432}{}{Ken empresto algum dinheiro? Olha, vou te pagar de volta.}
{433}{}{Eh, uh ... você tem algum Jet, amigo? Cara, eu preciso voar, * saber o que estou dizendo?}
{434}{}{Eu realmente preciso de algum remédio para o meu filho. Me aJude.}
{435}{}{Poupe algumas fichas?}
{436}{}{Eu só preciso de algumas fichas para comprar comida ...that's all…}
{437}{}{Eu serei seu escravo, se você puder me dar um pouco de Jet.}
{438}{}{Você pode me vender na escravidão se você me der um Jato.}
{439}{}{Vamos, senhorita, dê apenas algumas fichas.}
{440}{}{Ei irmã? Você pode me aJudar a voar?}
{441}{}{Eu posso agradar você ... se você tiver algum Jet para mim.}
{442}{}{Eh, uh ... você tem algum Jet, irmã?}
{443}{}{Irmã, preciso voar, * saber o que estou dizendo?}
{444}{}{Não, irmã, estou fora de chems. Uh ... por quê? Você está comprando?}
{445}{}{Mamãe?}
# 16. ANY STONED REACTION, POWER ARMOR
{450}{}{Piedosos...! O que você é? Algum tipo de row-bot?}
{451}{}{O que diabos você estava tomando para ficar coberto de metal assim?}
{452}{}{Uau. Um metal humano. Falando comigo.}
{453}{}{Se você é de outro planeta, você deveria voltar lá ... não há nada aqui para você
 conquistar.}
{454}{}{Oooooh. Posso ver as luzes de New Reno na sua viseira.}
{455}{}{Estou tão alto que ... uh, o que eu estava falando?}
{456}{}{Cara, você deve estar QUENTE nessa coisa.}
{457}{}{Alguém naquela coisa?}
{458}{}{Bem, se não for o Sr. Darttth Vadrrr}
{459}{}{Cara, eu tenho que ter alguma dessas merdas que você está tomando. Você parece um grande metal ... coisa.}
{460}{}{Homem, você está no Jogo errado. Experimente um dos Jogos mech PC da batalha.}
{461}{}{Você é um astronauta?}
{462}{}{Eu precisaria de mais alguns hits de Jet antes de pensar em mexer com você.}
# 17. ANY STONED REACTION, ANY SLAVER OR PRIZEFIGHTER
{470}{}{Ei, escravidão, wazzup ?!}
{471}{}{Você vai me escravizar? Hã? Apenas tente! Sou invencível!}
{472}{}{Tente me pegar, escravidão!}
{473}{}{Quer compartilhar alguns Jet, slaver?}
{474}{}{Eu mal consigo vê-lo lá embaixo, eu sou tão alto.}
{475}{}{Você está passando comigo, escravidão? Eu sou uma central elétrica Jato-bombada! Vou chutar o ASS!}
{476}{}{Você quer voar comigo, escravidão?}
{477}{}{Por que há dois o 'você? Que seu gêmeo?}
{478}{}{Hã? Você é real?}
{479}{}{Estou tão alto que ... uh, o que eu estava falando?}
{480}{}{Você está olhando para voar? Fale com Juuuuules.}
{481}{}{Jagged Jimmy J 'consertar você, sabe o que estou dizendo?}
{482}{}{Você vê Renesco, diga-lhe que vou dar-lhe o dinheiro amanhã.}
{483}{}{Jagged Jimmy's shit é o MELHOR. Leve-o tão alto, você NUNCA quer descer.}
{484}{}{Você falando comigo? Você falando comigo?!}
{485}{}{Você quer um pouco disso ?! Hã?}
{486}{}{:: Glares em você passado olhos quimicamente preJudicados ::}
{487}{}{Você quer voar comigo?}
{488}{}{Ei, campeão, wazzup ?!}
{489}{}{Você vai me caixas? Hã? Vamos lá!}
{490}{}{Você está passando comigo, campeão? Eu sou uma central elétrica Jato-bombada! Vou chutar o ASS!}
# 18. ANY STONED REACTION TO MADE MAN
{500}{}{Ho! Made Man comin 'through!}
{501}{}{Eu quase não consigo ver você lá, gangster, eu estou tão alto.}
{502}{}{Por que há dois o 'você? Que seu gêmeo?}
{503}{}{Hã? Você é um Real Made Man?}
{504}{}{Gangster, Estou tão alto que ... uh, o que eu estava falando?}
{505}{}{Você quer voar comigo, gangster?}
{506}{}{Você está olhando para voar, gangster? Fale com Juuuuules.}
{507}{}{Jagged Jimmy J 'consertar você, sabe o que estou dizendo?}
{508}{}{Se você está aqui para colecionar para Renesco, diga que eu vou ter o dinheiro amanhã.}
{509}{}{Jagged Jimmy's shit é o MELHOR. Uh, a menos que você não goste dele.}
{510}{}{Você falando comigo? Você falando comigo?!}
{511}{}{Você está passando comigo, ferramenta mafiosa? Eu sou uma central elétrica Jato-bombada! Vou chutar o ASS!}
{512}{}{Você quer um pouco disso, gangster ?! Hã?}
{513}{}{:: Glares em você passado olhos quimicamente preJudicados ::}
# 19. ANY STONED REACTION TO DRUGGED PLAYER
{520}{}{Whoa ... o que você está? Alguma parte para compartilhar?}
{521}{}{Eu pensei que * eu estava fodido.}
{522}{}{Ei, amigo ... compartilhe algumas dessas merdas em que você está.}
{523}{}{Eu pediria voce, mas parece que você Já está lá.}
{524}{}{Por que há dois o 'você? Que seu gêmeo?}
{525}{}{Onde você conseguiu essa merda, você está?}
# 20. ROBOBRAIN OR MARCUS
{530}{}{Cara, não olhe agora, mas você conseguiu esse cérebro em uma caixa que o acompanha.}
{531}{}{Uau. Devo tomar alguma merda de baaad ... Estou vendo os cérebros de robôs correndo por aí.}
{532}{}{Se eu veJo aquele robô com o cérebro zumbindo por aqui novamente, eu vou desistir de Jet
 para sempre.}
{533}{}{Eu me senti como o seu amigo robô antes ... diga-lhe que ele estará bem, uma vez que ele derrubar
 De seu alto.}
{534}{}{O que diabos aconteceu com o seu amigo com o cérebro? Ele perdeu seu corpo?}
{535}{}{Diga-me que o cérebro do robô não é real. Por favor.}
{536}{}{Uau. Confira o cérebro do robô. Há seu cérebro em chems se eu Já vi isso.}
{537}{}{Você quer voar comigo? How about your robot friend?}
{538}{}{Você está passando comigo, amante do robô? Eu sou uma central elétrica Jato-bombada! Vou chutar o seu burro
 E depois a bunda do seu robô!}
{539}{}{Você quer um pouco disso, robô-amante ?! Hã?}
{540}{}{Hã? Você é real?}
{541}{}{Estou tão alto que ... uh, o que eu estava falando?}
{542}{}{Você está olhando para voar? Fale com Juuuuules.}
{543}{}{Jagged Jimmy J 'consertar você, sabe o que estou dizendo?}
{544}{}{Você vê Renesco, diga-lhe que vou dar-lhe o dinheiro amanhã.}
{545}{}{Jagged Jimmy's shit é o MELHOR. Leve-o tão alto, você NUNCA quer descer.}
{546}{}{Você falando comigo? Você falando comigo?!}
{547}{}{:: Glares em você passado olhos quimicamente preJudicados ::}
{548}{}{Cara, não olhe agora, mas você conseguiu esse mutante seguindo você.}
{549}{}{Uau. Devo tomar alguma merda de baaad ... Estou vendo mutantes correndo por aí.}
{550}{}{Estou alto, ou seu amigo tem duas histórias de altura?}
{551}{}{:: Risos :: Your mutant has a vise growing out of his shoulder.}
{552}{}{Uh ... que um mutante, ou estou alto?}
{553}{}{Seu grande amigo parece realmente fodido.}
{554}{}{Yer big friend looks all yellowy and shit. :: Giggles ::}
{555}{}{Esse cara grande com você de verdade? Ele parece um mutante.}
{556}{}{Você quer voar comigo? How about your mutant friend?}
{557}{}{Você está passando comigo, amante mutante? Eu sou uma central elétrica Jato-bombada! Vou chutar o ASS!}
{558}{}{Você quer um pouco disso, amante mutante ?! Hã?}
# 21. STONED MALE REACTION TO COMP: SULIK OR NO REP AT ALL
{560}{}{Cara, não olhe agora, mas você tem esse tribal seguindo você.}
{561}{}{Uau. Confira essa tribal. Grande osso.}
{562}{}{Uau. Seu amigo sabe que ele tem um osso saindo do nariz?}
{563}{}{Uau. Devo tomar alguma merda de baaad ... Acabei de ver esse cara com um osso crescendo
 Do nariz dele.}
{564}{}{Estou alto, ou seu amigo conseguiu um osso crescendo do nariz?}
{565}{}{É melhor dizer ao seu amigo que alguém empurrou um osso no nariz.}
{566}{}{Eu mal posso te ver lá, estou tão alto.}
{567}{}{Por que há dois o 'você? Que seu gêmeo?}
{568}{}{Hã? Você é real?}
{569}{}{Estou tão alto que ... uh, o que eu estava falando?}
{570}{}{Você quer voar comigo?}
{571}{}{Você está olhando para voar? Fale com Juuuuules.}
{572}{}{Jagged Jimmy J 'consertar você, sabe o que estou dizendo?}
{573}{}{Você vê Renesco, diga-lhe que vou dar-lhe o dinheiro amanhã.}
{574}{}{Jagged Jimmy's shit é o MELHOR. Leve-o tão alto, você NUNCA quer descer.}
{575}{}{Você falando comigo? Você falando comigo?!}
{576}{}{Você está comigo? Eu sou uma central elétrica Jato-bombada! Vou chutar o ASS!}
{577}{}{Você quer um pouco disso ?! Hã?}
{578}{}{:: Glares em você passado olhos quimicamente preJudicados ::}

# use Jet on Junkie dialog
{600}{}{Agradável...}
{601}{}{Mmmm ...}
{602}{}{Você é um amigo.}
{603}{}{J}
{604}{}{J}
{605}{}{Me dê um J ... ummm ...}

# endings for middle insertion dialogs
{796}{}{! ARREBENTAR!! O QUE É PRÓXIMO, BEBÊ, O QUE É PRÓXIMO? !!!}
{871}{}{ family? Can you set me up with some Jet?}
