# 0. QUICK LOOK
{100}{}{Você vê Keith Wright.}

# 0. LOOK [MALE]
{150}{}{Você vê um jovem magro e de rosto pálido com longos cabelos loiros. Ele está olhando para você com cautela.}
{151}{}{Você vê Keith Wright. He's looking at you warily.}

# 1. FLOAT DIALOGUE: WARNING (WTG)
{200}{}{Quem é Você?}
{201}{}{O que você quer?}

# 2. FLOAT DIALOGUE: WARNING - KNOWS PLAYER BUT NOT MADE MAN (WTG)

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Ei,}

# 4. INTRO (WARNING) (WTG)
{230}{}{Faça outro movimento em direção a essa porta, e 'você vai se arrepender.}

# 5. FLOAT (DAD IS DEAD) (WTG)
{240}{}{Ainda não posso acreditar que o pai está morto. Há tanto que eu queria dizer a ele ...}

# 6. INTRO (NORMAL) (WTG)
{250}{}{Slaver, você fez chegar ao lado errado da cidade. Se você não começar a explicar "você mesmo, você vai ser
 em toda uma bagunça de problemas.}
{251}{}{Eu não conheço você, meu pai não conhece você, e se você não começar a explicar, isso não vai importar.}
{252}{}{Como vai',}
{253}{}{Obrigado por descobrir quem matou Richard,}
{254}{}{O que você quer agora?}
{255}{}{Mattah. O homem é Mattah!}
{256}{}{Jabawokee Ding Dong}
{257}{}{Afastar-se}
{258}{}{Estou à procura de trabalho. A contratação da Family Wright?}
{259}{}{Estou à procura de trabalho. Chris me enviou. A contratação da Family Wright?}
{262}{}{Ei,Keith. I ran into your Mom.}
{263}{}{Você pode me falar sobre seu irmão Richard?}
{264}{}{Deixa pra lá. Desculpe incomodá-lo.}

# 7. RETARD (6)
{280}{}{Saia daqui, dimbulb. Da próxima vez que você me falar, eu vou te ligar os buracos fulla.}
{281}{}{Buracos nos orifícios nas minhas solas}
{282}{}{Shamma Lamma DING DONG}

# 8. HOLES HOLES HOLES IN MY SOLES (7)
{290}{}{Saia daqui! Eu não estou advertindo você novamente!}
{291}{}{A-gin, my shin, muito din-din}
{292}{}{DING DONG! DING DONG!}

# 9. A-GIN, MY SHIN, LOTS OF DIN-DIN (8)
{300}{}{Eu te avisei, dim ...}
{301}{}{Hunh?}

# 10. WHO ARE YOU? (6, 11)
{310}{}{Sou Keith Wright da Família Wright. Agora, você vai me dizer o que você está fazendo aqui?}
{312}{}{Chris me disse para parar. Estou procurando trabalho. Pode me ajudar?}
{313}{}{Keith Wright, hein? Eu encontrei sua mãe.}
{315}{}{O que é este lugar?}

# 11. WHAT IS THIS PLACE (6, 10)
{325}{}{Esta é a Family Wright HOUSE. Agora, você vai me dizer o que você está fazendo aqui?}

# 12. CHRIS TOLD ME TO STOP BY . . . (6, 10, 11)
{335}{}{Chris enviou você, hein?}
{336}{}{Está certo. Ele disse que você pode ter algum trabalho para mim.}

# 13. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 10, 11)
{345}{}{Não sei se seria bom, mas acho que poderia pedir Pa ...}
{346}{}{Se você pudesse, eu apreciaria isso.}

# 14. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 10, 11)
{355}{}{Naw ... não contratamos músculo como as outras famílias, pelo menos não agora.}
{356}{}{Naw ... não traficamos com biscoitos como as outras famílias.}
{357}{}{É melhor você git.}
{358}{}{Não vou embora até ver o Sr. Wright.}
{359}{}{Tudo bem então.}

# 15. I'M NOT LEAVING UNTIL I SEE MR. WRIGHT. (14)
{365}{}{Naw, eu acho que você vai sair, porque você se parece com a pessoa que gosta de viver. Agora receba.}
{366}{}{Eu não vou embora.}
{367}{}{Tudo certo.}

# 16. I'M NOT LEAVING. (15)
{375}{}{Eu te avisei…}
{376}{}{Você quer alguns desses, MENINO ?! Você quer um pouco disso ?! Então venha pegar s -}

# 17. TELL ME ABOUT MOM (6, 10)
{380}{}{Uh ... e ela? Ela voltou a ficar com problemas?}
{381}{}{Não. Essa é uma ocorrência comum?}
{383}{}{Não, eu estava curioso. Mais tarde, Keith.}

# 18. NO. IS THAT A COMMON OCCURRENCE? (17)
{390}{}{As vezes. Ela sempre está pregando e está furiosa sobre os males da bebida e do gamblin e maldito
 perto de tudo o resto. Provoca bastante agitação, às vezes, e deixa papai realmente chateado.}
{391}{}{Sua mãe tem alguma idéia do que sua família faz?}
{392}{}{Aposto. Bem, obrigado por falar comigo, Keith.}

# 19. DOES YOUR MOM HAVE ANY IDEA WHAT YOUR FAMILY DOES? (17, 18)
{400}{}{Naw, ela não conhece metade disso. Ela acha que papai está limpo e acima do quadro, mas ela também não está
 brilhante para entender o que ele está fazendo. Se ela achasse isso ainda abaixo da estação de trem, ela levaria cain, ela faria.}
{401}{}{Entendo. Obrigado, Keith.}

# 20. MOM = AFTER WRECKED STILLS (17)
{410}{}{(Shakes head.) Ela fez isso desta vez, destruindo os alambiques de Pa n 'tudo. Os trabalhadores estavam com muito medo
 ta para ela, e Pa jogou um jeito, e ela jogou um direito de volta para ele. (Shrugs.) Levará Pa um tempo para
 volte para os pés.}

# 21. CAN YOU TELL ME ABOUT RICHARD? (6, 10)
{420}{}{Bom garoto. Porra, se alguma vez descobrimos quem fez isso com ele ...}
{421}{}{Alguma idéia de quem poderia ter feito isso?}
{422}{}{Bem, espero que você encontre o assassino. Tchau, Keith.}

# 22. ANY IDEAS WHO MIGHT'VE DONE IT? (21)
{430}{}{Lotta outras famílias vendem Jet, poderia ser qualquer um deles. Mordino tem mais revendedores Jet, no entanto,
 porque eles fazem o máximo de Jet. Eu, eu acho que era um deles.}
{431}{}{Que traficantes você suspeita?}
{432}{}{Você pode me contar um pouco sobre Richard?}

# 23. WHAT DEALERS ARE SUSPECT? (22, 24)
{440}{}{Bunch of: Jagged Jimmy J na 2nd Street, o velho sonuvabitch Renesco no West End ... e Jules
 também, na cidade da fronteira, mas principalmente para turistas burros. Depois, está o pequeno Jesus Mordino.}
{441}{}{Pequeno Jesus Mordino?}
{442}{}{Você pode me contar um pouco mais sobre Richard?}
{443}{}{Obrigado pela informação, Keith.}

# 24. CAN YOU TELL ME A LITTLE MORE ABOUT RICHARD? (22, 23, 27)
{450}{}{Criança tranquila, criança limpa. Mantido problemas, e para um Wright, isso é algo. Nós enterramos
 Ele nas planícies do Golgotha   há algum tempo, mas mesmo assim, mamãe ainda não quer que seu quarto seja perturbado.
 É difícil para ela deixar, sabe?}
{451}{}{Qual sala era dele? Você acha que sua mãe se importaria se eu olhasse lá?}
{452}{}{Os negociantes que você suspeita podem ter lhe dado o Jet?}
{454}{}{Buried in Golgotha, huh? Hmmm. Obrigado pela informação, Keith.}

# 25. CAN I LOOK AROUND HIS ROOM? (24)
{460}{}{Quarto dele? É o vazio junto ao quarto da mãe, o segundo da cozinha. Como fer olhando ao redor ... bem ... olhe, não fique
 longo ... e não mexa no lugar, ou mamãe aparecerá um clipe se descobrir.}
{461}{}{Obrigado, Keith. Não demorarei.}

# 26. JOB, SUCCESS . . . (12, 13)
{470}{}{Aguente. (Bata na porta atrás dele.) Pa? (Ele enfia a cabeça, há um murmúrio, depois ele volta e acena com a cabeça para a porta).
 Você entra, mas fique atento. Papai está com um humor pissy.}
{471}{}{Obrigado.}

# 27. LIL' JESUS (23)
{480}{}{Ele é o filho do grande Jesus. Um bastardo, mais parecido. Ele conseguiu pegar Richard sozinho, depois bombeou-o fulla
 Jet outta apesar. Você está procurando por ele, confira o Desperado. O pequeno Jesus fica lá com seu velho.}



# END LINES
{1220}{}{. O que está acontecendo?}
{1252}{}{ Todo mundo está te tratando bem? Algo que eu possa fazer por você?}
{1253}{}{. Nós lhe devemos grande, e os Wrights sempre pagam suas dívidas. O que posso fazer para você?}
