# 0. QUICK LOOK
{100}{}{Você vê Miss Kitty.}

# 0. LOOK
{150}{}{Você vê uma mulher deslumbrante. Apesar dela ... vestido revelador, seu porte é profissional e comercial.}

# 1. FLOAT [MALE, ENCLAVE IS DESTROYED]
{200}{}{As receitas do primeiro trimestre aumentaram ligeiramente ... agora, se considerarmos o aumento da homenagem ...}
{201}{}{Se eu a pegar tomando Jet, mesmo um cheiro *, ela está fora daqui ...}
{202}{}{Físicos mensais estão por vir novamente ... bem no tempo para a nova temporada de caravanas.}
{203}{}{Preciso conseguir mais algumas meninas para essa festa na piscina do Bishop's ...}
{204}{}{Damn Macrosoft spreadsheets ...}
{205}{}{Gaste tanto tempo atualizando essas planilhas, não realizo nenhum trabalho REAL.}
{206}{}{Jules melhor envia alguns gostosos ... e ricos ... pessoas dessa maneira em breve.}

# 2. INTRO DIALOGUE (WTG)
{215}{}{(A mulher antes de você é incrivelmente linda. Ao dirigir-se a ela, ela olha para cima do trabalho dela e
 Sorrisos.) Ah, um novo rosto! Sou Miss Kitty ... bem vindo à Pata do gato.}
{216}{}{Olá de novo!}
{217}{}{Por que, se não é o mais famoso saqueador de Reno!}
{218}{}{Perguntei-me quando o Sr.}
{1218}{}{ Te enviaria ... (Winks.)}
{219}{}{Meu, se não é a estrela da tela dourada.}
{220}{}{ Qual é o seu prazer hoje, senhor?}
{221}{}{ Qual é o seu prazer hoje, senhorita?}
{222}{}{Preshshure?}
{223}{}{Yuu haf prettee hair}
{224}{}{Yuu disse 'pleashure' Huh-Huh-Huh-Huh-Huh}
{225}{}{George Sayz, nós vamos ter alguns achers de owr próprio 'Eu shud manter longe de você ou ele não vai lemme
 Jogue com o rabbitz para que eu vá agora}
{226}{}{Jules me disse para vir aqui se eu estivesse procurando alguma ... ação.}
{227}{}{Estou procurando alguma ação ...}
{228}{}{Na verdade, gostaria de fazer algumas perguntas.}
{229}{}{Você sabe, eu tenho encontrado revistas chamado "Pata de gato" em todo o deserto, e eu não tenho
 Ideia o que são. Eu tenho um aqui.}
{230}{}{Aqui está aquela coleção de revistas Cat's Paw que você pediu.}
{231}{}{Nada hoje, obrigado.}

# 3. RETARD ANSWER (2)
{240}{}{(A linda senhora coloca a palma da mão na testa.) Oh,você é pobre ... você pode ficar aqui
 Por algum tempo para entrar do calor, mas você não pode estar aqui por muito tempo, ok? Prometa-me agora.}
{241}{}{Okayy, linda linda com você}

# 4. LOOKING FOR ACTION (2, 12)
{245}{}{(Sorrisos e piscadinhos.) É assim? Bem, então, você veio ao lugar certo. Seja qual for o seu prazer ou
 Fantasia, podemos providenciá-lo ... e não seja tímido, ouvimos tudo. Então, o que você gostaria?}
{246}{}{Bem, perdoe-me por ter vindo forte, mas gostaria de conhecê-lo melhor. A que horas você sai?
 Uh, trabalho, quero dizer.}
{247}{}{Depende ... o que há no menu?}
{248}{}{Gostaria de ligar meu amigo aqui com um pouco de algo especial.}
{249}{}{Gostaria de ligar um dos meus amigos aqui. São seus ... uh, aniversário.}
{250}{}{Gostaria de fazer algumas perguntas ...}
{251}{}{Na verdade, eu mudei de idéia. Desempenho de ansiedade e tudo. Adeus.}

# 5. ASK HER OUT (4)
{255}{}{Estou lisonjeado, mas ... não. Não posso.}
{256}{}{Ah, vamos. Apenas uma bebida. Sem pressão. Teremos um ótimo momento.}
{257}{}{Olha, se você não gosta de mulheres, está bem. Inferno, não gosto da maioria das mulheres que conheço. Temos algo em
 Comum já.}
{258}{}{Ei, não se preocupe ... Não irei usar a armadura de poder, ok?}
{259}{}{Tudo bem então.Gostaria de fazer algumas perguntas ...}
{260}{}{Desculpe, não queria pressionar você. Adeus.}

# 6. ASK HER OUT (5)
{265}{}{(Olha por aí, então se inclina e sussurra.) Olha ... volte depois
 Você fez o que teve que fazer para salvar seu povo e depois conversamos, ok?}
{266}{}{Tudo bem então. Tive algumas outras questões ...}
{267}{}{É um encontro. Vejo você então.}

# 7. MENU (6)
{275}{}{Bem ... (Descarte o menu em seus dedos.) ... nós amamos o amor, o redemoinho da vareta, humjobs e vários
 Outra exotica. (Smiles.) Pergunta é, para que VOCÊ ESTÁ com vontade?}
{276}{}{Gostaria de alguma ... atenção oral.}
{277}{}{Apenas algum sexo básico, atrevido, baixo e baixo, me deixa bem.}
{278}{}{Gostaria de um exercício completo do corpo superior e inferior.}
{279}{}{Está certo se eu apenas, você sabe, converse com eles?}
{280}{}{Eu tenho um pedido especial ... dramático ....}

# 8. & 9 BLOWJOB (7)
{290}{}{Tudo bem então.}
{291}{}{(Winks.) Isso não será responsável.}
{292}{}{Isso será}
{293}{}{Feito. Aqui está o dinheiro.}
{294}{}{Não pode argumentar sobre esse preço. Vamos fazer isso.}
{295}{}{Nevermind. Gostaria de fazer algumas perguntas ...}
{296}{}{Não tenho dinheiro suficiente ... talvez mais uma vez.}

# 10. TALK (7)
{320}{}{Por que, claro, você pode. Nós chamamos isso de "Kesting especial".}
{322}{}{Custa apenas}
{323}{}{Por que você chama isso?}
{325}{}{Parece um acordo. Eu tomarei isso então.}
{326}{}{Maybe some other time. Gostaria de fazer algumas perguntas ...}

# 11. KESTING (10)
{335}{}{Bem ... rumores de que havia uma vez um funcionário de uma famosa empresa de informática que gostava de conversar com
 outras. (Shrugs.)}
{336}{}{Por coincidência, ele também fez apenas}
{1336}{}{ Fichas por semana.}
{337}{}{Por coincidência, ele também não fez nenhum dinheiro, então conversar era tudo o que ele podia pagar.}
{338}{}{Oh. Bem, inscreva-me para a sessão de conversa então. Aqui está o}
{340}{}{I think I'll pass. Gostaria de fazer algumas perguntas ...}

# 12. QUESTIONS (2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 18, 19, 20, 21, 23, 25, 28, 29, 30)
{350}{}{Sim?}
{351}{}{Bem, não há mal em perguntar ...}
{352}{}{Tudo certo. (Smiles.) As respostas podem custar-lhe, no entanto ...}
{353}{}{Certo. Que perguntas você teve?}
{354}{}{Ouvi algumas das suas meninas serem escolhidas para ir ... visitar Myron.}
{355}{}{Jules me disse para vir aqui para alguns ... ação.}
{361}{}{Na verdade, é melhor eu ir.}

# 13. MENU (7)
{375}{}{As possibilidades são que podemos acomodá-lo. Seu pedido seria ...?}
{376}{}{Gostaria que meu parceiro se veste com um macacão no Vault, me chame o "Vault Dweller", e eu tenho que encontrar
 Seu "Vault Sex-Teen".}
{377}{}{Eu gostaria de ser "capturado" por uma fascinante she-mutant, então ser forçado a dar um mergulho no seu "IVA" mutante.}
{378}{}{Gostaria de desempenhar o papel de "Herk", um jovem escravo nubile roubado de sua aldeia por uma banda de lusty
 Mulheres escravas. Aqui está a captura ... ele só pode se comunicar usando seu CORPO.}
{379}{}{Gostaria de desempenhar o papel de "Zena", um jovem escravo nubile roubado de sua aldeia por uma banda de
 Escravos. Aqui está a captura ... ela só pode se comunicar usando seu CORPO.}
{380}{}{Gostaria de ser "capturado" por um tenente sarcástico mutante, interrogado grosseiramente, depois mergulhado
 Em seus recipientes de mutação.}
{381}{}{Você tem meninas que se parecem com Angela Bishop? Eu preciso resolver alguma emoção.}
{382}{}{Você tem meninas que se parecem com a Sra. Bishop? Eu preciso resolver alguma emoção.}
{383}{}{Gostaria de fazer algumas perguntas em vez disso ...}
{384}{}{Na verdade, Nevermind. Eu tenho que ir.}

# 14. FRIEND LAID (4, 12)
{395}{}{Claro. (Scans seus companheiros.) Qual deles?}
{396}{}{Você poderia cuidar de Lenny? Eu não acho que ele nunca beijou uma garota.}
{397}{}{Você conseguiu alguém que possa, uh, "lidar" com Marcus?}
{398}{}{Este pequeno pervertido Myron aqui.}
{399}{}{"Bone Nose" aqui, se você pegar minha deriva. Heh heh.}
{400}{}{Cassidy aqui. Eu acho que já faz um tempo.}
{401}{}{Vic. "Trader" Vic.}
{402}{}{Uma das suas meninas pode ler o dicionário para Robo Brain? Estimula seu centro cerebral.}
{403}{}{Doc está olhando para tomar uma "temperatura" ou duas.}
{404}{}{Davin aqui poderia usar ... muito ... mais experiência.}
{405}{}{Miria quer dar um passeio pelo lado selvagem.}
{406}{}{Na verdade, ninguém, obrigado.}

# 15. FRIEND LAID 2 (4, 12, 14)
{420}{}{Esse é seu amigo aqui? (Olha seu companheiro para cima e para baixo, acena com a cabeça.) Eu acho que podemos acomodá-lo ...}
{421}{}{(Olha seu companheiro para cima e para baixo, acena com a cabeça.) Eu acho que podemos acomodá-lo ...}
{422}{}{ salgadinhos.}
{423}{}{Não se preocupe com o dinheiro. Não há cobrança.}
{424}{}{OK. Aqui está.}
{425}{}{Não pode argumentar com esse preço. Feito.}
{426}{}{Talvez mais tarde ... olhei, eu tive algumas outras perguntas.}
{427}{}{Hmmm. Talvez algum outro momento em que eu tenha dinheiro suficiente.}
{428}{}{Na verdade, eu mudei de idéia. Adeus.}

# 16. CAT'S PAW (2, 12)
{440}{}{(Parece surpreso.) Deixe-me ver. (Glances na revista.) Bem, bem ... você sabe, eu tinha ouvido um rumor de que
 - nos anos de pré-guerra - a Pata do gato era uma editora ... para materiais pornográficos.}
{441}{}{Por pornogru - porn-o-gra - pornu - uh, uma editora, você disse?}
{442}{}{Esse lugar era uma editora?}

# 17. CAT'S PAW 2 (16)
{450}{}{Sim ... os quartos aqui foram usados   para filmes com modelos de todo o mundo. (Parece fascinado pela revista.)
 Um pedaço de história que você tem lá.}
{451}{}{Bem, você sabe, acabei de ler isso para os artigos.}
{452}{}{Estou apenas feliz de saber o que é a maldita coisa. É irritante continuar examinando e recebendo
 A mesma mensagem repetidamente. Provavelmente AINDA vou conseguir, mesmo que seja identificado agora.}

# 18. CAT'S PAW 2 (17)
{460}{}{Você sabe ... se você pode me trazer um conjunto completo ... diga, dez questões, vou comprá-los de você. Seriam bons para
 Uma exibição, pode atrair clientes. Você está interessado?}
{461}{}{Se eu puder ENCONTRAR que muitos ... digamos, eu tive algumas outras perguntas ...}
{462}{}{Na verdade, eu tenho dez aqui mesmo.}
{463}{}{Certo. Se eu me deparar com isso, eu vou ter certeza de parar.}

# 19. CAT'S PAW, SOLVED (2, 12, 18)
{470}{}{Maravilhoso! Eu lhe darei $ 500 para o set.}
{471}{}{$ 500? Depois de recolher TODOS estes? De jeito nenhum. Faça mil.}
{472}{}{Parece bom. Aqui está. Mas oi, cuidado com o número cinco ... as páginas parecem serem coladas juntas.}
{473}{}{Não, acho que vou mantê-los ... diga, tive algumas outras perguntas ...}
{474}{}{Não, obrigado, fiquei apegado a eles. Talvez outra hora.}

# 20. CAT'S PAW, SOLVED (19)
{480}{}{Hmmmmm. Sete e cinquenta, e você conseguiu um acordo.}
{481}{}{$ 750? Tudo bem então. Sao seus.}
{482}{}{Eu acho que vou mantê-los depois ... diga, eu tive algumas outras perguntas ...}
{483}{}{Esqueça. Talvez outra hora.}

# 21. CAT'S PAW, SOLVED, 750 (20)
{490}{}{Aqui está. (Contesta o dinheiro, entrega pra você.) Obrigado novamente.}
{491}{}{Diga, eu tive algumas outras perguntas ...}
{492}{}{Não é um problema. Adeus.}

# 22. CAT'S PAW, SOLVED 2 (19)
{500}{}{Mesmo? (Examina o número 5, depois passa pelo resto da sua pilha.) Hmmmm. Bem, parece que você tem
 Dois deles, então você pode ter esse de volta ... mas deixe-me tirar a mancha primeiro.}
{501}{}{OK. Uh ... por sinal, essa mancha não é minha. Não tenho ideia de como chegou lá.}
{502}{}{OK. Tem certeza de que consegue essa mancha? Parece colado lá muito apertado.}

# 23. CAT'S PAW, SOLVED 3 (22)
{510}{}{Acontece todo o tempo por aqui ... (Miss Kitty começa a limpar a revista.) ... principalmente nos lençóis. que
 Deve fazê-lo ... (Detendo isso.) ... bom problema - tem um artigo sobre armas de energia, parece. Aqui está.}
{511}{}{Tive algumas outras questões ...}
{512}{}{Um artigo sobre armas de energia? Obrigado. Posso lê-lo mais tarde.}

# 24. ENCLAVE VICTORY SPEECH (WTG)
{520}{}{(Como você fala, ela olha para cima, assustada.) Você! Você voltou! Eu ... eu pensei que você poderia estar morto. (Ela parece
 Aliviado.) Eu estava tão preocupado. * Arriscando sua vida, assumindo o Enclave ... é a coisa mais corajosa que já ouvi.}
{521}{}{(Como você fala, ela olha para cima, assustada.) Você! Já ouvi sobre você. (Seu rosto irradia admiração.) Risco
 Sua vida, assumindo o Enclave ... essa é a coisa mais corajosa que já ouvi.}
{522}{}{! Estou feliz por ter voltado novamente. Basta ter um herói como você mesmo faz maravilhas para negócios:
 Arriscando sua vida, assumindo o Enclave ... Essa é a coisa mais corajosa que já ouvi.}
{523}{}{Shucks, Miss Kitty. Ele não deixa nada que ninguém mais faria no lugar de mah.}
{524}{}{Daaaaamn certo, bebê. E essa é a coisa mais corajosa que você vai ouvir, porque eu sou o MAIOR DE
 o mal.}
{525}{}{Não era nada que nenhuma mulher irritada que tivesse sua aldeia seqüestrada não teria feito.}
{526}{}{E essa é a coisa mais corajosa em que você SEMPRE vai ouvir, porque eu sou a cadela MAIOR
 Nos resíduos.}
{527}{}{Obrigado. Apenas fazendo o meu trabalho como uma heroína.}
{528}{}{Obrigado. Apenas fazendo o meu trabalho como um herói.}
{529}{}{Kicking ass e tomando nomes, esse é o meu trabalho.}

# 25. ENCLAVE VICTORY SPEECH (24)
{545}{}{Você é tão humilde.}
{546}{}{Você é tão forte. Então ... confiante.}
{547}{}{Eu amo isso em você. (Faz um gesto de varredura na Cat's Paw.) Você é sempre bem-vindo aqui, gratuitamente.}
{548}{}{Então ... que tal essa data falamos sobre o caminho de volta quando?}
{549}{}{Então ... e sobre ... você sabe, você e eu ... como ... você sabe.}
{550}{}{Baby, eu tenho que me sentir como uma máquina, e isso não é maneira de sentir. C'mere.}
{551}{}{Ótimo! Olha, eu tive algumas perguntas antes de me entregar ...}
{552}{}{Obrigado. Aprecio, Miss Kitty.}
{553}{}{Eu não espero nada menos. Eu vou coletar mais tarde.}

# 26. ENCLAVE VICTORY SPEECH (25)
{565}{}{Tudo bem então,}
{566}{}{... deixe-me apenas pegar meu casaco.}
{567}{}{Sem pressa. Não tenha pressa.}
{568}{}{Bom, eu tenho o meu "casaco" no bolso. Heh heh.}
{569}{}{Certo. Mas apressar-se ... temos reservas às oito. Nas minhas calças.}
{570}{}{Certo. Mas apresse-se ... você e minha língua tiveram reservas às oito.}

# 27. MACHINE (25)
{575}{}{Oh,}
{576}{}{, Você é Enclave-smashing animal ...}
{577}{}{:: Bwanbwan-bwan-ba-bwan oookwaka oookwaka ::}

# 28. MYRON (12)
{585}{}{(Nods.) Sim, está correto. Normalmente, temos que treiná-los para suprimir suas características naturais
 Repugnância. É quase um rito de passagem agora. Ainda assim, se uma menina pode cumprir Myron, isso significa que ela é dura ...}
{586}{}{Gostaria de conhecê-lo. Penso que eu poderia ser voluntário para ser sua próxima "escolha"?}
{587}{}{I see. Tive algumas outras questões ...}
{588}{}{Hmmmm. Obrigado pela informação.}

# 29. EVALUATE (28)
{595}{}{(Estuda você, então faz um gesto circundante com o dedo dela). Volte-se para mim. Hmmmm ...}
{596}{}{Não, eu não acho que você faria o corte. Talvez se você se limpar um pouco mais, feito
 Você mesmo ... apresentável. Desculpa.}
{597}{}{Sim ... sim, acho que você faria bem. Você está interessado no trabalho? Todas as minhas outras garotas
 Estão doentes disso}
{598}{}{Certo.}
{599}{}{Hmmmph. Tive algumas outras questões ...}
{600}{}{No, but I may ask again later. Tive algumas outras questões ...}

# 30. EVALUATE (29)
{610}{}{(Nods.) Excelente. Um dos tenentes de Mordino deveria aparecer logo. Se você quer tomar um
 Assento, vou apresentar você como um dos ... candidatos.}
{611}{}{Tudo bem ... Vou esperar por ele.}
{612}{}{Actually, forget it. Tive algumas outras questões ...}
{613}{}{Nevermind ... Eu mudei de idéia. Talvez outra hora.}

# 31. STRANGE REQUEST (4, 12, 13, 14)
{620}{}{(Olha para cima e para baixo, então acena com a cabeça.) Eu acho que podemos acomodá-lo ...}
{621}{}{(Olha seu companheiro para cima e para baixo, então acena com a cabeça.) Eu acho que podemos acomodar seu amigo ...}
{623}{}{(Winks.) Não há cobrança, então não suar o dinheiro.}

# sex responses
{700}{}{Oooooh-sim.}
{701}{}{Shag-a-riffic.}
{702}{}{Uau. Isso foi profundo.}
{703}{}{Uau.}
{704}{}{* Whew *}
# marcus
{705}{}{Tenho certeza de não ter ficado grávida.}

{710}{}{Você fala por horas. As meninas da Paw do gato têm uma visão incrível da natureza humana.}
{711}{}{O tenente Mordino chega, e parece impressionado com você. Ele o leva para o norte de
 Cidade para algum lugar chamado "estábulos".}

# party applause
# general
{720}{}{* Apitos *}
{721}{}{* Clap Clap Clap *}
{722}{}{Maneira de ir!}
{723}{}{Wahoo.}
# spouse
{730}{}{* Solteira soluço soluço *}
{731}{}{Eu me sinto tão ... tão enganado ...}
# goris
{740}{}{*Grunhido*}
# cyberdog
{750}{}{* Aaawoooo *}
# robobrain
{760}{}{* Bzzzt *}
# vic
{770}{}{Bom, chefe! Não foi feito sexo sozinho em um tempo muito longo.}

{800}{}{Você entregou as revistas Cat's Paw para Miss Kitty.}
