# 0. QUICK LOOK

# 0. LOOK
{150}{}{Você vê um jovem jovem queimado de sol vestido com couro preto e correntes. Seu rosto está marcado
 Com cicatrizes de acne.}
{151}{}{Você vê Lil 'Jesus Mordino.}
{152}{}{Você vê Lil 'Jesus Mordino. He is dressed mostly in black leather and playing with one of his knives.}

# 1. FLOAT [ENCLAVE DESTROYED] (WTG)
{200}{}{Yo!}
{201}{}{Fuckin'-A,}
{202}{}{:: Dá você thumbs up sign ::}
{203}{}{:: Whistles ::}

# 2. FLOAT [POWER ARMOR] (WTG)
{220}{}{Como você se engana com essa coisa?}

# 3. FLOAT/CLICK [MADE MAN, SAME FAM, ARMED (WTG)
{230}{}{Uma boa peça que você chegou lá,}

# 4. FLOAT/CLICK [MADE MAN, SAME FAMILY, SNEAK] (WTG)
{240}{}{O que você está rastejando, eh,}

# 5. FLOAT [MADE MAN: MORDINO] (WTG)
{250}{}{Wazzup,}
{5250}{}{?}
{251}{}{Heeey ...}
{252}{}{Sheee-it, está quente.}
{253}{}{Heeey! Whacha estava preparado,}
{254}{}{Bom te ver,}
{255}{}{Ei! Venha verificar minha nova faca}
{256}{}{Que merda papai te fez fazer agora,}
{257}{}{Nós vamos sair esta noite,}
{258}{}{Minha faca precisa de um sangue de Bispo ...}
{259}{}{Vai esculpir tantos Salvatores, eles vão me chamar de "açougueiro" ...}

# 7. FLOAT [MADE MAN, NOT SAME FAMILY] (WTG)
{270}{}{Yo!Cabron! Vocêlooking for th' Angel o' Death?Beat it!}
{271}{}{Você conseguiu alguns cojones aqui,}
{272}{}{Hijo de puta ...}
{273}{}{Você}
{274}{}{Se você ainda estiver aqui quando eu terminar minha bebida, vou esculpir meu nome no seu rosto.}
{275}{}{:: Começa jogando com sua faca de forma ameaçadora. ::}
{276}{}{Olhando para a sua irmã,}
{277}{}{O que o fu ... você! Você, o que você está fazendo aqui?}
{278}{}{Yo!Puta! Vocêlooking for th' Angel o' Death?Beat it!}
{279}{}{Pensei que o mantinham preso no canil, puta.}
{280}{}{Se você não está aqui para beijar minha bunda,}
{281}{}{Hija de puta ...}

# 9. FLOAT/CLICK [MALE, ARMED, RESPECTFUL] (WTG)
{300}{}{Yo!Hombre, you can't be carrying that around in here.}
{301}{}{Yo!Homes, put that thing away 'fore you start making people nervous.}

# 10. FLOAT/CLICK [FEMALE, ARMED, RESPECTFUL] (WTG)
{310}{}{Yo!Chica, you can't be carrying that around in here.}
{311}{}{Yo!Chica, put that thing away 'fore you start making people nervous.}

# 11. FLOAT/CLICK [MALE, SNEAK, PRIZEFIGHTER] (WTG)
{320}{}{Por que diabos você se esgueirou,}

#12. FLOAT/CLICK [FEMALE, SNEAK, PRIZEFIGHTER] (WTG)
{330}{}{Por que você saiu, chica?Com esse gancho direito você conseguiu, você deveria andar alto.}

# 13. FLOAT [MALE, PRIZEFIGHTER] (WTG)
{340}{}{Onde você aprende a lutar,}
{341}{}{Vocêgot the cojones of a Mordino.}
{342}{}{A última luta foi algo fora de um épico, um homem.}
{343}{}{Voe como uma borboleta, como uma abelha. Thaz você, ali mesmo,}
{344}{}{Sabe, os Mordinos podem usar algum músculo como você,}
{345}{}{Bet on you, best money I ever placed. Vocêwere throwing hooks like nobody's business.}
{346}{}{Viu você lutar no ringue,}
{347}{}{Quanto você bancar,}
{348}{}{Onde você trabalha, eh?}
{349}{}{Cuidado com o Masticador. Ele gosta de comer ouvidos.}
{350}{}{Eu pegaria uma bebida se eu não tivesse jogado todo meu dinheiro apostando em seu oponente.}
{351}{}{De onde você luta, você luta assim?Voce é bom. Eu quis dizer bom.}
{352}{}{Onde você aprende a lutar,chica?You're vicious. Vocêgot the MOVES.}
{353}{}{A última luta foi algo fora de um fodido épico, menina.}
{354}{}{Onde você trabalha, eh?Need a spotter?}

# 15. FLOAT/CLICK [ARMED, PORN STAR, FEMALE] (WTG)
{370}{}{Ei, hey, hey! Chica, você precisa de mim para colocar essa arma longe para você?}
{371}{}{O que, você quer que eu tire a tiragem você e tudo?Vamos, peguei esse ferro antes de eu me preocupar.}

# 16. FLOAT [MALE, SNEAK, PORN STAR] (WTG)

# 17. FLOAT/CLICK [SNEAK, PORN STAR, FEMALE] (WTG)
{390}{}{De jeito nenhum, você está esgueirando por Lil 'Jesus com um corpo assim, menina.}

# 18. FLOAT [PORN STAR] (WTG)
{400}{}{Seu filme não foi ruim, mas você obviamente precisa de algumas dicas de mim. :: Risos ::}
{401}{}{Ei,}
{402}{}{Estou pronto, estou disponível, você me colocou em um filme, ok?Estamos falando bilheteria,}
{403}{}{Eu sou o melhor amante do latim. Não há amante latino como eu.}
{404}{}{Fale com os Irmãos sobre mim,}
{405}{}{Dê uma boa palavra aos irmãos para mim, tudo bem?}
{406}{}{Vocêare doin' the right thing, brushing up with the Mordinos. We're going places.}
{407}{}{Precisa de chems?Hootch?Algumas batatas fritas?Posso configurá-lo. Eu sou co-nnected, ver?}
{408}{}{Então, e você e eu fazendo um filme?Eu vou te tratar direito, menina. Eu mostro o que um amante latino pode fazer.}
{409}{}{Por que você não pára depois do trabalho?}
{410}{}{Vocêgot any friends?}
{411}{}{Vocêneed some Jet?I can set you up, chica.}
{412}{}{Chica, não há nada que eu não faria por você ... vamos, agora. Me dê um pequeno beijo.}

# 20. FLOAT/CLICK [ARMED, SLAVER] (WTG)
{425}{}{Não mostre ferro por aqui, amigo. Coloque isso fora.}

# 21. FLOAT/CLICK [SNEAK, SLAVER] (WTG)
{435}{}{Não esqueça, slaver, tudo bem?Você está entre amigos.}

# 22. FLOAT/CLICK [ARMED, NO REP] (WTG)
{445}{}{Yo!Vocêdumb or something?Put that thing away before I haveta hurt you.}
{446}{}{Vocêlookin' for a backalley lobotomy?Put that thing away.}
{447}{}{Yo, chica! Vocêdumb or something?Put that thing away before I haveta hurt you.}

# 24. FLOAT/CLICK [SNEAK, MALE, NO REP] (WTG)
{455}{}{What the hell you sneaking around for?Vocêlooking to get shot?}

# 25. FLOAT/CLICK [SNEAK, FEMALE, NO REP] (WTG)
{460}{}{What you sneaking around for, chica?Vocêlooking to get shot?}

# 26. FLOAT/CLICK [COMPANION: ROBOBRAIN] (WTG)
{465}{}{Pegue esse lixo de papelão fora daqui.}
{466}{}{Nenhum bots permitido aqui. Cai fora.}
{467}{}{Esse robô vai ser sucata se ficar.}

# 27. FLOAT/CLICK [COMPANION: MARCUS] (WTG)
{475}{}{Pensei que eu cheirava mutante. Tire-o daqui a diante, ficamos bravos.}
{476}{}{Vocêa mutant lover?His place is OUTSIDE. Or else.}
{477}{}{Esse mutante se aproxima, ele se tornará uma prática alvo.}

# 28. FLOAT/CLICK [COMPANION: LENNY] (WTG)
{485}{}{Pensei que eu cheirava a alguma podridão. Tire esse garoto ghoul de seu para fora aqui.}
{486}{}{Pegue esse ghoul fedido fora daqui. Agora.}
{487}{}{Esse ghoul não está fora de lugar aqui em um minuto, ele ficará mais morto do que ele já é.}

# 29. IF KNIFE (WTG)
{495}{}{Ei,you. C'mon over here and let me see that knife.}
{496}{}{Boa faca.}
{497}{}{Posso ver aquela faca por um segundo?}

# 30. INTRO (WTG)
{505}{}{Hunh?}
{506}{}{Algo que você quer, amigo?}
{507}{}{Algo que você quer, chica?}
{508}{}{Hoo ooh?}
{511}{}{Afastar-se}
{512}{}{Quem é Você?}
{513}{}{Desculpa. Eu pensei que você fosse outra pessoa.}

# 31. SECOND TIME, NORMAL (WTG)
{522}{}{Eh...?Vocêagain?What do you want now?}
{523}{}{Heeeey ... whatzzup, amigo?Algo em sua mente?}
{524}{}{Eu de onde}
{525}{}{Ay-me-go?}
{526}{}{Cheee-ka Cheeek-aaaah}
{529}{}{Eu tive algumas perguntas ...}
{530}{}{Deixa pra lá. Desculpe incomodá-lo.}

# 32. PRIZEFIGHTER (WTG)
{540}{}{}
{541}{}{}
{542}{}{Ei,hey, hey! You're }
{544}{}{Incêndio, ateio fogo}
{547}{}{Thanks, Lil' Jesus. Ei,I had some questions for you…}
{548}{}{Obrigado pelo elogio. Eu estava apenas parando; Eu tenho que ir.}
{549}{}{Sim, não preciso que você me diga isso. Basta assistir a si mesmo.}

# 33. MADE MAN (SAME) (WTG)
{560}{}{Heeeey! Como tá indo,}
{562}{}{Vocêbeing helped, or do I got to call over one of the putas ta get you set up?Ha!}
{563}{}{Vocêbeing helped, or do I got to call over one of the waitresses ta get you set up?Ha!}
{567}{}{Não, eu estou bem. Diga, eu fiz algumas perguntas para você, Jesus ...}
{568}{}{Não, estou bem, obrigado. Pegue você mais tarde.}

# 34. SLAVER (WTG)
{582}{}{Eh?Vocêlooking to deal, slaver?Got some stock you wanna unload?}
{583}{}{Eu descarregar! Eu descarregar!}
{586}{}{Certo. Você é quem fala?}
{587}{}{Não agora. Eu tive algumas perguntas para você, no entanto ...}
{588}{}{Não agora. Talvez mais tarde.}

# 35. RETARD (30, 31, 32, 33, 34, 36, 63)
{600}{}{Heh. Vocêbeen out squatting in the sun too long. Get.}
{601}{}{Eh…right. Vocêtake care, amigo. I'll catch you later.}
{602}{}{Eh…right. Vocêtake care, chica. I'll catch you later.}
{603}{}{Heh. Talvez você devesse voltar e se agachar ao sol, tribal. Limpe o ar aqui.}
{604}{}{Okeee Doh-kee}

# 36. SECOND TIME (WTG)
{620}{}{Saia daqui.}
{621}{}{Venha por aqui novamente, e eu vou preenchê-lo tão cheio, mesmo que o Superman não possa ver através de você.}
{622}{}{:: Jogos com faca ameaçadoramente ::}
{623}{}{:: Spits at your feet ::}
{624}{}{Vocêlook like someone who don't know when they're about to die.}
{625}{}{Bata-o antes de desperdiçá-lo.}
{626}{}{Volte aqui novamente, e eu vou fugir de você.}

# 37. QUESTION NODE (31, 32, 33, 34, 38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 50, 51, 52, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65)
{640}{}{(Pega as unhas com faca.) Perguntas ... TODAS pessoas têm perguntas ...}
{641}{}{(Pega seus dentes com uma unha suja). Sim?}
{642}{}{Algo em sua mente?}
{643}{}{O que você estava falando sobre a família Mordino novamente?}
{1643}{}{Quem é essa família Mordino de que você estava falando?}
{644}{}{Estou à procura de trabalho.}
{645}{}{O que há para fazer em torno de New Reno para relaxar?}
{646}{}{Vocêknow anything about Richard Wright overdosing on Jet?}
{647}{}{Você pode me ensinar a faca lutando?}
{648}{}{Deixa pra lá. Pegue você mais tarde.}

# 38. WHO ARE YOU?(30, 31, 32, 33, 34, 36, 63, 64, 65)
{660}{}{Eu?Se você precisa perguntar ... heh. Nome de Jesus. Jesus Mordino. O mesmo que meu pai, ele é o GRANDE Jesus, chefe da família INTEIRA Mordino
 Aqui em Reno. Então, a maioria me liga Lil 'Jesus. Evita confusão, sabe?}
{661}{}{Família Mordino?Quem são eles?}
{662}{}{Ouvi falar sobre sua família. Eu ouço que vocês são uma força a ser contada.}
{663}{}{Estou à procura de trabalho. Is Family Mordino hiring?}
{665}{}{Saiba o que tem a ver com New Reno para relaxar?}
{666}{}{I see. Say, Eu tive algumas perguntas ...}

# 39. FAMILY MORDINO?WHO'S THAT?(37, 38)
{680}{}{Nós, Mordinos, vamos dirigir New Reno ... e Redding, também. Você verá.}
{681}{}{Family MORDINO?Vocêbeen taking too much Jet, homes?We Mordinos run New Reno…and Redding, too.}
{682}{}{Family MORDINO?Vocêbeen taking too much Jet, chica?We Mordinos run New Reno…and Redding, too.}
{683}{}{Parece que a família Mordino é a única que pode se conectar com ... você pode me configurar?}
{684}{}{O que você quer dizer de Redding?}
{685}{}{Redding?Onde é isso?}
{686}{}{Sounds like the Mordinos have a bright future. Say, Eu tive algumas perguntas ...}
{687}{}{VocêMordinos talk big, but got small cojones. What you got to say about that, LITTLE Jesus?}

# 40. REDDING?WHERE'S THAT?(39)
{700}{}{Para o noroeste, casas.}
{701}{}{Ao noroeste, chica.}
{702}{}{Se você não esteve lá, você não está faltando nada. Um grupo de mineiros que não gostam de você, que gosta de FLY, sabe o que estou dizendo?}
{703}{}{Na verdade não. O que você quer dizer?}
{704}{}{Eles são um monte de quimiantes?}
{705}{}{Eu te escuto. Tive algumas outras questões ...}
{706}{}{Eu tenho que ir. Mais tarde, Jesus.}

# 41. WHAT DO YOU MEAN ABOUT REDDING?(39)
{720}{}{Grupo de mineiros sem pescoço, cavar a sujeira, mas eles gostam de FLY, sabe o que estou dizendo?}

# 42. NOT REALLY. WHAT DO YOU MEAN?(40, 41)
{740}{}{Eles não cuidam de ouro, veja, mas o que nós lhes damos é melhor do que o ouro, sabe o que estou dizendo?Eles nos da TODOS
 O ouro que eles desenterram apenas para um LEETLE Jet. Todo mundo feliz.}
{742}{}{Parece que sim. Olha, eu tive algumas outras perguntas ...}

# 43. THEY'RE A BUNCHA DRUG ADDICTS?(40, 41, 42)
{760}{}{Well, when they got their first taste o' Jet, they were. Vocêcan't have just one.}
{761}{}{De onde vem o Jet?}
{762}{}{Eu te escuto. Olha, eu tive algumas outras perguntas ...}

# 44. WHERE DOES THE JET COME FROM?(43)
{780}{}{O Jet?Vem de AQUI. Veja, nós não cavamos pelo ouro, nós o fazemos: ouro líquido. Jato. Vale a pena uma fortuna para os mineiros, custa
 Ao lado de nada a fazer. Nós o enviamos para Redding, eles disparam, eles voam, eles nos enviam ouro. Que simples.}
{781}{}{Há quanto tempo isso vem acontecendo?Parece que você já teria controlado todo o norte da Califórnia se Jet fosse isso
 Formando hábitos.}

# 45. HOW LONG HAS IT BEEN GOING ON?(44)
{800}{}{Você está certo sobre isso ... veja, nós não sempre TEMOS Jet. Mas nós tropeçamos por esse garoto - ele deu uma olhada na merda
 Chems que vendemos e disse que ele poderia fazer "melhor". E ele fez. Agora ele trabalha para nós. Que simples.}
{801}{}{Quem é esse garoto e onde ele está?}

# 46. WHO IS THIS KID?(45)
{820}{}{O nome do filho é Myron. Quanto a onde ele é, isso é algo que você não precisa saber.}
{821}{}{Kid's name's Myron. We got him set up in the stables, north of town, testing new chems. Vocêcould go over and see him if
 you want, but he's busy most of the time…either with the chems or the women.}
{822}{}{Por que você não fica inteligente e me conta de qualquer maneira?}
{823}{}{Consegui. Tive algumas outras questões ...}
{824}{}{Myron, hein?Tudo bem, Jesus. Obrigado pela conversa.}

# 48. RELAX?(36, 37, 38)
{840}{}{O Desperado é o lugar para estar, casas. Nós conseguimos o Jet, os jogos, a ação ... e nós conseguimos todas as putas que você precisa
 Direito, molhado e disposto. Paraíso, casas. Par-a-dados.}
{841}{}{O Desperado é o lugar para estar, menina. Nós conseguimos o Jet, os jogos e a ação. Você
 Não é necessário ir a outro lugar.}
{842}{}{Então ... você quer re-lax, chica?Heh ... então, como você e eu conseguimos um amor doce?}
{843}{}{Tentador, mas não tenho dez segundos para o seu doce amor agora, Little Jesus.}
{844}{}{Estou lisonjeada, mas não obrigado. Diga, eu tive algumas outras perguntas ...}
{846}{}{Estou à procura de trabalho. Know of any place that's hiring?}
{847}{}{Obrigado pela dica, obrigado.}
{848}{}{Por que você não começa sem mim?Eu tenho que ir.}

# 49. I AIN'T GOT 10 SECONDS FOR YOU RIGHT NOW . . . [BAD RESPONSE] (48, 52)
{860}{}{Eh?What are you talkin ab --?(Gets it.) Vocêfucking PUTA! Vocêbetter get yo tramp ass outta here 'fore I carve you
 into so many pieces your own mother won't recognize you.}
{861}{}{Eh?What are you talkin ab --?(Gets it.) Vocêbetter get your ass out here, homes, 'fore I take my knife and give
 you a second smile on that neck of yours.}
{862}{}{Experimente e veja o que acontece, PEQUENO Jesus.}
{863}{}{Experimente, e adicionei tantas cicatrizes ao seu rosto, você ficará como um quebra-cabeça.}
{864}{}{Acalme-se ... estava brincando com você.}
{865}{}{Calafrio. Tive algumas outras questões ...}
{867}{}{Estou indo embora. Grande conversa com alguém tão cultivado como você.}

# 50. I AIN'T GOT 10 SECONDS FOR YOU RIGHT NOW . . . [GOOD RESPONSE] (48, 52)
{880}{}{Ha! Vocêall right, chica. Vocêall right. Lil' Jesus gonna be keeping an eye on you…not that I couldn't help myself. What
 can I do for you?}
{881}{}{A primeira coisa que você pode fazer por mim é manter seus olhos para você, PEQUENO Jesus. Eu mais cedo consideraria humping uma rocha antes
 Tocando aquela paisagem cratera que você chama de rosto.}
{882}{}{Estou à procura de trabalho. Know of anyone who's hiring?}
{883}{}{Tive algumas outras questões ...}
{884}{}{Na verdade, eu tenho que ir. Bom conversando com você, Jesus.}

# 51. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (37, 38, 39, 48)
{890}{}{(Checou você, acena com a cabeça.) Estamos sempre procurando sangue novo ... "sangue especialmente novo que está disposto a derramar sangue, sabe o que estou dizendo?Suba as escadas, fale com o meu pai, diga-lhe que lhe enviei e talvez possamos fazer negócios.}
{891}{}{(Checa você, mata a cabeça.) Não contratamos chicas ... "em certas posições. Experimente no andar de cima, diga a ele que eu enviei.
 Talvez você possa fazer algum negócio.}
{892}{}{Maybe so. Say, Tive algumas outras questões ...}
{893}{}{Eu vou vê-lo então. Mais tarde, Jesus.}

# 52. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (37, 38, 39, 48)
{900}{}{I don't know. Vocêdon't look too strong to me…maybe you should try somewhere else, homes.}
{901}{}{Naw ... minha mente está em branco. Nossa família não está contratando, e as outras famílias logo te matariam do que te ouvir. Você
 Outta sorte, casas.}
{902}{}{Naw...I don't know of no place hiring. Vocêmight try and find a pimp, MAYBE earn some cash charging rent on yer
 ass, y'know?}
{903}{}{NÓS não estamos contratando, mas com um corpo como esse, você pode experimentar o estúdio Bros Corsica na rua. (Grins.) Mas se você estiver olhando
 Para alguns chips rápidos, meu quarto está no andar de cima ...}
{904}{}{All right then. Tive algumas outras questões ...}
{905}{}{Uh, I'll pass. Tive algumas outras questões ...}
{906}{}{Prefiro não, obrigado. Eu tive algumas outras perguntas para você, no entanto ...}
{907}{}{Oh, eu aposto que seria rápido. Não, obrigado.}
{908}{}{Deixa pra lá então. Obrigado mesmo assim.}
{909}{}{Não, obrigado. É melhor eu ir.}

# 53. CALM DOWN. I WAS JUST KIDDING (X)
{920}{}{Oh, então isso faz tudo melhor então, hein?(Sente-se aos seus pés). Tire o inferno aqui, antes que eu o corteie.}
{921}{}{Apenas tente e veja o que acontece ... PEQUENO Jesus.}
{922}{}{Calma, Jesus ... olha, eu tive algumas outras perguntas ...}
{923}{}{Estou indo embora.}
{924}{}{Vocêspit on my shoe?Vocêfuck! I'm gonna teach you a lesson about respect, mother fucker.}

# 54. I WANNA DEAL WITH SLAVES (34)
{930}{}{Não, não eu ... siga no andar de cima e veja meu pai. Ele é o único com quem quer conversar.}
{931}{}{E você é...?}
{932}{}{All right then. Before I go, Eu tive algumas perguntas ...}
{933}{}{Obrigado.}

# 55. YOU'RE A REAL HUMANITARIAN/STANDARD BAD RESPONSE?(39, 46, 57, 62, 65)
{940}{}{FUCK você. Saia do casino da minha família antes de esculpir minhas iniciais em sua cadáver.}
{942}{}{Você não me ameaça, Jesus.}
{943}{}{Hold on - Tive algumas outras questões ...}
{944}{}{Calm down, Jesus. Estou indo embora.}

# 56. WHAT ABOUT RICHARD?(36, 37, 38)
{950}{}{That little piss-ass Wright kid?Ha! Vocêtrying to pin that shit on me?Vocêoutta luck; I ain't sorry the little
 fucker's dead, but I didn't have NOTHIN' to do with it.}
{951}{}{Oh sim?Bem, os Mordinos são os maiores fornecedores de Jet em New Reno. Isso faz de vocês os primeiros que são
 Vai ter a culpa.}
{952}{}{I don't believe you. I think you ARE the one responsible. Vocêand the rest of the Mordinos.}
{953}{}{Quem você imagina pode ter feito isso?}
{954}{}{Okay…look, Tive algumas outras questões ...}
{955}{}{Tudo bem então. Só perguntando.}

# 57. OH, YEAH?YOU'RE GONNA TAKE THE BLAME (56)
{965}{}{(Olhos estreitos.) Olhe agora, eu não tive NADA para fazer com a morte desse filho. Não sei o que ouviu, mas se eu tivesse matado
 Aquele garoto, eu o teria esculpido, não o fiz bater e queimar em Jet, entende?}
{966}{}{Sim, então, e se culparmos?Não quer dizer que o fizemos. Pequena merda tomou muito. Não lamento que ele esteja morto. E
 Se o homem Wright começar a jogar, nós o enterraremos ao lado de seu filho viciado.}
{967}{}{Você é um humanitário real, Jesus.}
{968}{}{Essa é uma ótima atitude, Jesus.}
{969}{}{Vocêknow who sold Richard the Jet that killed him?}
{970}{}{Well, that certainly clears matters up for me. Tive algumas outras questões ...}
{971}{}{Obrigado pela informação, Jesus. Você foi muito útil.}

# 58. ANY IDEA WHO MIGHT'VE SOLD IT TO HIM (56, 57)
{980}{}{Sim, Renesco ... o "Rocketman". Vende muito Jet, ele poderia atirar em você para a lua. Ele está no lado oeste, em Salvatore
 território. Ele não gosta do Wrights nenhum, e seus chems não são PUROS, sabe o que estou dizendo?}
{981}{}{Ele não pode ser o único revendedor em uma cidade desse tamanho.}
{982}{}{Lado oeste, hein?Eu posso parar. Mas eu tive algumas outras perguntas ...}
{983}{}{Tudo certo. Eu vou verificar isso. Obrigado, Jesus.}

# 59. IS HE THE ONLY DEALER IN TOWN?(58)
{990}{}{Não, há outros, mas Renesco é o único que fez isso.}
{991}{}{O que te faz dizer isso?}
{992}{}{Quem são os outros revendedores?}
{993}{}{Yeah, you said that already. Look, Tive algumas outras questões ...}
{994}{}{Tudo bem, Jesus. Obrigado pela informação.}

# 60. WHAT MAKES YOU SAY THAT?(59, 61)
{1000}{}{CAUSE he's a half-blind cracker with a mean streak a mile wide that sells BAD SHIT, that's fucking why. Vocêgo see him,
 you see what he says about the Wright kid, and THEN you'll see I'm right.}
{1001}{}{O que outros negociantes existem?}
{1002}{}{I may do that. Look, Tive algumas outras questões ...}
{1003}{}{Tudo bem, Jesus. Vou verificar este Renesco.}

# 61. WHAT OTHER DEALERS ARE THERE?(59, 60)
{1010}{}{Há Jules, na frente da cidade, pede principalmente aos recém-chegados ... n 'Jagged Jimmy J, na 2ª rua pela academia ... não pode
 Sinto falta desse punk-ass porque ele cortou o rosto uma noite enquanto estava no Jet ... é tão ruim que seu rosto inteiro é tudo cicatrizado.}
{1011}{}{Eu também ouço que você também trate de cumprimentos, Jesus. Como o seu nome não estava na lista?}
{1012}{}{O que faz você pensar que Renesco é responsável?}
{1013}{}{Interesting. Tive algumas outras questões ...}
{1014}{}{Renesco, Jules e Jagged Jimmy J. Obteve. Obrigado pela informação.}

# 62. HOW COME YOUR NAME AIN'T COME UP?(61)
{1020}{}{CAUSA, mãe fucker, EU NÃO ES um revendedor.}
{1021}{}{CAUSA EU NÃO ES UM revendedor, BITCH.}
{1022}{}{Posso vender Jet às vezes, mas eu sou Lil 'Jesus MORDINO, e não um punk de dois bits Jet-push que tem que trabalhar dez
 Clientes por dia apenas para fazer o suficiente para comer. Então FUCK você.}
{1023}{}{Vocêbetter watch your mouth with me, Jesus.}
{1024}{}{Easy, easy, just curious…look, Tive algumas outras questões ...}
{1025}{}{Tudo bem então. Obrigado pela informação.}

# 63. GOT A KNIFE (WTG)
{1030}{}{(Lil 'Jesus olha para a faca em sua mão, sacode a cabeça.)}
{1031}{}{(O homem olha para a faca em sua mão, sacode a cabeça.)}
{1032}{}{* Tchhhh. * Você não sabe como segurar uma faca, casas?}
{1033}{}{* Tchhhh. * Você não sabe como segurar uma faca, menina?}
{1034}{}{Here, like this… (Adjusts your grip.) Vocêneed some instruction.}
{1035}{}{(Look at knife. Look at ugly man. Look at knife.) Vocêtouch }
{1036}{}{Kagagoogoo}
{1038}{}{Mesmo?Você pode me ensinar?}
{1040}{}{Na verdade, eu fiz algumas perguntas para você, Jesus ...}
{1041}{}{Talvez algum outro momento, obrigado.}

# 64. CAN YOU TEACH ME?(37, 63)
{1050}{}{Hmmmmm ...}
{1051}{}{Eu não sei, casas ... Quero dizer, eu não tenho muito tempo livre e as facas são uma ARTE, sabe?}
{1052}{}{Eu não sei, chica ... Quero dizer, eu não tenho muito tempo livre e luta de faca é uma ARTE, sabe?}
{1053}{}{Eu não sei, chica ... Quero dizer, EU POSSO estar disposto a fazer uma exceção para uma mulher como você, mas eu não sou
 Tem muito tempo livre ... e a faca é uma ARTE, sabe?}
{1054}{}{Eu lhe darei uma centena de fichas.}
{1055}{}{Eu lhe darei duzentos chips.}
{1056}{}{O meu amor também é uma arte. Quer trocar estilos?}
{1058}{}{Actually, Eu tive algumas perguntas ...}
{1059}{}{Mais uma vez, então ... quando eu tenho fichas suficientes para mudar de idéia.}
{1060}{}{Talvez algum outro momento, então, obrigado.}

# 65. CAN YOU TEACH ME?(63)
{1070}{}{Hmmmmm. 200 e é um acordo.}
{1071}{}{Naw ... Eu estava pensando em algo, você sabe?(Seus olhos deriva pelo seu corpo, lambe seus lábios rachados).}
{1072}{}{Diga-me que significa 200 fichas. POR FAVOR, diga-me que significa 200 fichas.}
{1073}{}{Oh, você estava pensando em sexo?Bem, continue pensando, porque isso não acontecerá.}
{1074}{}{Ok, ok. Vamos fazer isso. Qualquer coisa para alguma habilidade de faca adicionada.}
{1075}{}{Tudo certo. Aqui está o dinheiro.}
{1076}{}{Deixa pra lá. Uh, quem é você, afinal?}
{1077}{}{Forget it. Tive algumas outras questões ...}
{1079}{}{Talvez algum outro momento, obrigado. I REALLY have to be going.}

# 66. CAN YOU TEACH ME?(65)
{1090}{}{Hmmmm...all right, yeah, I'll do it. Vocêlook like you might have the cojones for it. Look, now, the first thing you
 gotta do is…}
{1091}{}{Hmmmm...all right, yeah, I'll do it. Vocêlook like you might have the cojones for it…no offense. Look, now, the first
 thing you gotta do is…}
{1092}{}{(Smiles, displaying the rotted remains of his teeth.) All right, yeah, I'll do it. Vocêgot some time right NOW, chica?
 Then let's get down to business…}
{1093}{}{Tudo certo...}

# post-knife training
{2000}{}{Lil' Jesus shows you some vicious knife fighting tricks. Vocêhave become more skilled with knives.}
{2001}{}{At the cost of your dignity, you have become more skilled with knives. Vocêalso desperately want a shower.}

# END LINES
{5200}{}{! Maneira de chutar a bunda do Enclave!}
{5201}{}{, Maneira de ensiná-los a Enclave tonto foda como as coisas são feitas DOWNTOWN.}
{5230}{}{.}
{5240}{}{?Mordinos anda orgulhoso.}
{5251}{}{! Que pasa?}
{5253}{}{?}
{5254}{}{. Onde você esteve?}
{5255}{}{.}
{5256}{}{?}
{5257}{}{. Vocêcomin' wit us?}
{5271}{}{. Perder e andar, ou então.}
{5273}{}{Foda-se com a gente, você será um wormfood. Saia daqui!}
{5276}{}{?Ela acabou de me beijar na bunda. Agora você também pode explodir.}
{5280}{}{, É melhor você sair.}
{5320}{}{?Com esse gancho direito você conseguiu, você deveria andar alto.}
{5340}{}{?You're vicious. Vocêgot the MOVES, hombre.}
{5343}{}{.}
{5344}{}{. Outras famílias vêem você chegar, eles caíram em um segundo.}
{5346}{}{. Vocêwere *wasting* that guy.}
{5347}{}{?}
{5380}{}{?Vamos, caminhe alto.}
{5401}{}{! Que pasa?Vocêgonna set me up with the Brothers, or what?}
{5402}{}{, bilheteria!}
{5404}{}{…Vamos lá. Eu posso fazer isso.}
{5542}{}{! O grande lutador! Cara, você é bom!}
{5543}{}{! O lutador da menina desagradável! Você é bom, chica!}
{5560}{}{?}
# these three are related
{6035}{}{'S hand No TOUCH}
{7035}{}{Mão}
{8035}{}{ NÃO COMO}
