# 0. QUICK LOOK

# 0. LOOK
{150}{}{Você vê um homem magro e com fome. Ele tem um olhar abatido e uma fina camada de restolho
 cobre seu queixo.}
{151}{}{Você vê Pretty Boy Lloyd.}
{152}{}{Você vê Pretty Boy Lloyd. He is watching you warily.}

# 1. FLOAT DIALOGUES (WTG)
{200}{}{Tenho que sair da cidade ...}

# 2. INTRODUCTIONS IN IGNORANCE (WTG)
{210}{}{Quem é você? O que você está fazendo aqui embaixo ?!}
{211}{}{Você novamente?! O que você está fazendo aqui embaixo ?!}
{212}{}{Mel Nuttin}
{213}{}{Eu}
{214}{}{Afastar-se}
{215}{}{O quê você está fazendo aqui em baixo?}
{216}{}{Acalme-se, amigo, ENTÃO conversaremos. Tudo está certo?}
{217}{}{Você Lloyd? Pretty Boy Lloyd?}
{218}{}{Nada. Apenas olhando por aí. Até logo.}

# 3. NUTTIN' HONEY (2)
{225}{}{Bem, saia daqui. E você não está dizendo a ninguém que você me viu, você ouve?}
{226}{}{Euhere. Now me gone!}

# 4. ME X ME X ME X WHO U/WHO ARE YOU AND WHAT ARE YOU DOING DOWN HERE/CALM DOWN, FRIEND . . . (2, 28)
{230}{}{Não é da sua conta ... amigo. Eu sugiro que você siga a cabeça de volta para aquelas escadas e esqueça
 nos encontramos.}
{231}{}{EuForget. 4-get, four-git…uh…forget whut?}
{232}{}{Ok Dokee}
{233}{}{Não me importo muito com sua sugestão ... amigo. Qual é o problema aqui?}
{234}{}{Você soa como um homem com problemas. Talvez eu possa ajudá-lo.}
{235}{}{Você parece um homem que valoriza sua privacidade. Para alguém tão falador como eu, esquecendo
 você poderia ser muito caro.}

# 5. WHAT SEEMS TO BE THE PROBLEM HERE? [LLOYD NOT AFRAID] (4)
{245}{}{Problema? O problema está bem na minha frente.}
{246}{}{Agora não vou dizer novamente, cara: deixe.}
{247}{}{Agora não vou dizer novamente, querido: saia.}
{248}{}{Você * me ameaça? Pense muito com atenção antes de responder.}

# 6. WHAT SEEMS TO BE THE PROBLEM HERE? [LLOYD AFRAID] (4)
{255}{}{Problema? Não há problema, amigo, sem nenhum problema. Apenas procurando um pouco de privacidade é tudo.}
{256}{}{Problema? Não há problema, querido, não há problema. Apenas procurando um pouco de privacidade é tudo.}
{257}{}{Problema? De modo nenhum. Apenas procurando um pouco de privacidade é tudo. Ainda ... era rude de mim afastar uma senhora tão encantadora.}
{258}{}{Eu acho que você tem um problema. Veja, toda essa privacidade torna difícil para alguém ouvir
 O que está acontecendo aqui embaixo. Talvez eu apenas mata você, hein?}
{260}{}{Para alguém tão falador quanto eu, a privacidade pode ser bastante dispendiosa.}
{261}{}{Tudo bem então. Desculpe incomodá-lo.}
{262}{}{Você está certo. Era grosseiro. Eu irei agora.}

# 7. YOU THREATENING ME? [BAD, LLOYD NOT AFRAID] (5)
{270}{}{(Olhos estreitos).}
{271}{}{Se você veio aqui procurando problemas, você bateu no jackpot, amigo.}
{272}{}{Se você desceu aqui procurando problemas, você bateu no jackpot, querido.}
{273}{}{Espero que você tenha feito seus respeitos ...}
{274}{}{Você quer algum problema? Você teve dificuldade -}

# 8. YOU THREATENING ME? [LLOYD SCARED SHITLESS] (5)
{283}{}{Uh ... agora, olhe ... Não estou ameaçando ninguém, e certamente não estou procurando nenhum problema.}
{284}{}{Eu acho que você tem um problema. Veja, toda essa privacidade torna difícil para alguém ouvir
 O que está acontecendo aqui embaixo. Talvez eu apenas mata você, hein?}
{285}{}{Você parece um homem com problemas, e talvez eu possa ajudá-lo. O que você disse?}
{286}{}{Você soa como um homem que valoriza sua privacidade. Para alguém tão falador como eu, esquecendo
 você poderia ser muito caro.}
{287}{}{Tudo bem então ... desculpe incomodá-lo.}

# 9. THREATEN TO KILL LLOYD… [LLOYD NEGOTIATES] (6, 8)
{295}{}{Uh ... ei, agora ... não há necessidade desse tipo de conversa. Talvez possamos falar sobre algo
 ELS: quanto seu amigo Lloyd pode ajudá-lo.}
{296}{}{Estou interessado. Você continua conversando.}
{297}{}{Não interessado. Estou fora daqui.}
{298}{}{Esqueça, Lloyd. Seu número está acima. Prepare-se para morrer.}

# 10. THREATEN TO KILL LLOYD… [LLOYD FREAKS] (6, 8, 12)
{305}{}{(O rosto do homem fica pálido. Ele engole por um segundo ... então se lança com você!)}
{306}{}{Filha da p -}

# 11. KEEP TALKING . . . (4, 5, 6, 8, 9)
{315}{}{Eu tenho algumas fichas ... talvez um pouco de dinheiro possa limpar o ar entre nós, manter tudo civil?}
{316}{}{Bem. Eudê tudo o que você tem.}
{318}{}{Mantenha seu dinheiro. Estou fora daqui.}

# 12. FINE. GIVE ME EVERTHING YOU GOT . . . (11)
{325}{}{Tudo bem, tudo bem ... (Ele alcança o bolso, tira algumas fichas, depois as entrega para você.) ... agora
 Que tal você pegue esse dinheiro, vá para o andar de cima e divirta-se com Lloyd, você ouve?}
{326}{}{Talvez você seja surdo. EU DISSE, me dê tudo o que você obteve.}
{327}{}{OK. Bem, depois de te matar.}
{328}{}{Tudo bem então. Estou fora daqui.}

# 13. I SAID, GIVE ME EVERTHING YOU GOT [LLOYD FRIGHTENED] (12)
{335}{}{Uh, agora ... é tudo que eu tenho no mundo, amigo. Eu não tenho mais nada; Eu já dei tudo
 para você.}
{336}{}{Não fique comigo, Lloyd. Eu sei que você obteve
 Mais; Você é um cara inteligente. Última chance: onde está o resto?}
{337}{}{Vamos ver sobre isso, Lloyd. Eu vou ver o que encontro quando busco seu cadáver.}

# 14. DON'T FUCK WITH ME LLOYD . . . (4, 5, 6, 8, 13)
{345}{}{Eu ... Eu disse ... ehh ... tudo bem agora ... Eu sei onde você pode encontrar mais dinheiro ... não é meu, veja e é
 mais problemas do que vale, mas você quer, é seu.}
{346}{}{Poderia ser eu sei onde é que você pode encontrar algum dinheiro ... não é meu, veja e é mais problema
 do que vale a pena, mas você quer, é seu.}
{347}{}{Continue falando e mantenha-o interessante.}
{348}{}{Na verdade, estava a brincar com você, Lloyd. Eu vou matar
 Você e deixe os espíritos resolverem isso.}
{349}{}{Eu não estou interessado em sua merda brahmin de dupla conversa. Estou fora daqui.}

# 15. KEEP TALKING AND KEEP IT INTERESTING (14)
{355}{}{Tudo bem então ... está na planície do Gólgota ao sul de Reno, enterrada em um dos
 túmulos. Só que sei onde é, no entanto.}
{357}{}{Conte-me.}
{358}{}{Essa é a maior carga de ... oh inferno, eu vou matar você, Lloyd e deixar os espíritos
 resolver isso.}
{359}{}{Oh, esqueça essa coisa de cavalos. Estou fora daqui.}

# 16. TELL ME WHERE THE MONEY IS (15, 24, 25)
{365}{}{Dirija-se ao sinal na encruzilhada do Golgotha, vá ao noroeste até chegar ao terceiro túmulo, então
 siga para o nordeste até atingir a primeira estaca. É uma sepultura próxima, marcada como "Arch Stanton".
 Desenterre cerca de seis pés, e você vai encontrá-lo.}
{366}{}{Sinal da cara, vá para o noroeste de três túmulos, vá para o nordeste até a primeira estaca, então procure
 "Arch Stanton" ... tudo bem, vamos lá, Lloyd. Preciso de alguém para escavar, afinal.}
{367}{}{Tudo bem então. Estou fora daqui. Make yourself scarce. (Let Lloyd leave.)}
{368}{}{Isso era tudo o que eu precisava saber ... eles estarão enterrando você naquela sepultura pela manhã.}

# 17. SHOW ME WHERE THE MONEY IS (15, 16, 24, 25)
{375}{}{(Lloyd parece que ele está prestes a dizer alguma coisa, pensa melhor nela e acena com a cabeça.) Tudo bem
 então. Parece que não tenho escolha. Vamos.}
{376}{}{Eu tenho algumas coisas para cuidar primeiro. Você espera aqui, volto em uma hora. (Deixe, esconda
 fora da sala, então veja se Lloyd sai e segue-o.)}
{377}{}{Eu tenho algumas coisas para cuidar primeiro. Você espera aqui, voltarei.}
{378}{}{Estou logo atrás de você.}

# 18. YOU LOOK LIKE A MAN IN TROUBLE, AND I MIGHT BE ABLE TO HELP YOU. WHAT DO YOU SAY? (4, 5, 6, 8)
{385}{}{Hmmmmm. Eu não conheço você, amigo ... mas estou pensando que eu gostaria. Nome Lloyd. Alguns me chamam Pretty Boy
 Lloyd, mas são eles, não eu.}
{386}{}{Hmmmmm. Eu não conheço você, querido ... mas estou pensando que eu gostaria. Nome Lloyd. Alguns me chamam Pretty Boy
 Lloyd, mas são eles, não eu.}
{387}{}{Hmmmmm. não sou tolo o suficiente para desistir da ajuda de uma mulher bonita. Nome Lloyd. Alguns me chamam Pretty Boy
 Lloyd, mas são eles, não eu.}
{388}{}{Prazer em conhecê-lo. Então ... sobre a minha oferta ...?}

# 19. WHAT MISUNDERSTANDING? (36)
{395}{}{A família Salvatore e eu tivemos ... desacordo sobre o meu sucesso em uma das suas mesas de jogo.
 Eu acho que o assunto só pode ser resolvido removendo-me tão longe do New Reno quanto possível.}
{396}{}{Sucesso em suas mesas de jogo, hein? Quanto você ganha, Lloyd?}
{397}{}{Como posso ajudar?}
{398}{}{O que há para mim?}
{399}{}{Eu não acho que posso te ajudar, Lloyd. Eu acho melhor que esqueçamos que nos conhecemos. Adeus.}

# 20. HOW CAN I HELP? (19)
{405}{}{Hmmmm ... você parece bem equipado para servir como guarda-costas. Euajude a sair da cidade. Acompanhe-me
 para a planície de Gologtha para o sul, e posso pagar algumas fichas pelo seu problema.}
{407}{}{Feito. Vamos. (Siga-o.)}

# 21. SUCCESS AT THEIR GAMBLING TABLES . . . ? (19, 20)
{415}{}{(Pales, então recupera a compostura.) O suficiente para irritá-los. A maioria foi gasto em subornos mantendo o Salvatore
 bandidos das minhas costas o tempo suficiente para escorregar aqui e se esconder. Tenho medo de me mostrar na cidade ...}
{416}{}{(Parece surpreso, então recupera a compostura.) O suficiente para irritá-los. A maioria foi gasto em subornos mantendo os bandidos Salvatore fora
 minhas costas o tempo suficiente para escorregar aqui e se esconder. Tenho medo de me mostrar na cidade ...}
{417}{}{Eu vou ajudá-lo, mas vou querer metade do dinheiro que você ganhou, Lloyd. Não me engane neste caso, se você
 saiba o que é bom para você.}
{418}{}{Me dê metade do que você ganhou nas mesas, e eu vou ajudá-lo, Lloyd. É uma troca justa
 para ver que você sai da cidade de uma só peça.}
{419}{}{Tudo bem, vou ajudá-lo. Vamos sair daqui. (Siga-o.)}
{420}{}{Eu não acho que posso te ajudar, Lloyd. Adeus.}

# 22. GIVE ME HALF (21)
{425}{}{(Parece que ele está prestes a dizer alguma coisa, pensa melhor nela e acena com a cabeça.) Parece que não consegui
 escolha. Vamos.}
{427}{}{Não, você espera aqui e fique quieto até eu voltar. Eu tenho que cuidar de algumas coisas, então
 Eu voltarei e iremos na nossa viagem de campo.}

# 23. YOU LLOYD? PRETTY BOY LLOYD? (2, 4)
{435}{}{(Stiffens.) Talvez. Quem é Você? Eu não acredito que tive o prazer ...}
{436}{}{(Stiffens, então levanta uma sobrancelha.) Talvez. Tenho certeza de que eu me lembraria de você, senhorita.
 Eu não acredito que tive prazer ...?}
{437}{}{Dispense com a besteira, Lloyd. Estou aqui pelo dinheiro que roubou do Sr. Salvatore.}
{438}{}{Olhe, Lloyd, entregue o dinheiro e EU ESQUEIO que esqueci que eu já vi você até você estar longe
 daqui.}
{439}{}{Lloyd, o Sr. Salvatore enviou-me aqui para recuperar o dinheiro e me fazer um ... exemplo de você.
 Não precisa ser assim ... Se nós dois podemos chegar a um acordo.}

# 24. DISPENSE WITH THE BULLSHIT (23, 28, 29, 31, 32, 33)
{445}{}{Tudo bem ... tudo bem agora ... (Swallows.) Está nas planícies do Golgotha   ao sul de Reno, enterrado
 uma das sepulturas. Só que sei onde é, no entanto.}
{446}{}{Mostre-me.}
{448}{}{Essa é a maior carga de ... oh inferno, eu vou matar você e encontrar o dinheiro
 por mim mesmo.}

# 25. I MIGHT FORGET I EVER SAW YOU . . . (23)
{455}{}{Hmmmmmm. Eu não acho que nenhum de nós acredita que ... (Swallows.) Mas talvez eu possa confiar em você.
 O dinheiro está enterrado nas planícies do Golgotha   ao sul de Reno, em uma das sepulturas. Só sei onde
 é, porém.}
{459}{}{Oh, esqueça essa coisa de cavalos. Estou indo embora. Mantenha seu dinheiro e seu segredo e saia da minha vista.}

# 26. ARRANGEMENT . . . (23, 29, 31)
{465}{}{Hmmmm. Um "arranjo" que você diz ... tudo bem, tudo bem ... o que você quer?}
{466}{}{Vou tirar você da cidade por metade do dinheiro que ganhou do Sr. Salvatore, Lloyd.}
{467}{}{Vou levá-lo para fora da cidade em troca de todo o dinheiro que ganhou do Sr. Salvatore, Lloyd.}
{468}{}{Ah, nunca perca. Eu não quero nada - saia daqui antes de mudar de ideia.
 (Imagine sair, esconder, depois segui-lo.)}
{469}{}{Aw, nevemind. Eu não quero nada - saia daqui antes de mudar de ideia.}

# 27. THE DEAL (26)
{475}{}{Bem, agora ... hmmmm ... parece que não tenho escolha. Eu vou ter que levá-lo para onde está o dinheiro,
 no entanto, porque você não encontrará o contrário. Vamos.}
{476}{}{Eu tenho algumas coisas para cuidar primeiro. Você espera aqui, volto em uma hora. (Fingir
 deixe, esconda, depois siga-o.)}
{477}{}{Não, você espera até eu voltar. Eu tenho que cuidar de algumas coisas, então eu voltarei
 para você e iremos em nossa viagem de campo.}
{478}{}{Estou logo atrás de você. (Follow him.)}

# 35. I'M HERE TO SHOW YOU OUTTA TOWN (WTG)
{555}{}{(Saltos.) Uh ... pronto para ir?}
{556}{}{Sim. Vamos. (Siga-o.)}
{557}{}{Não, você espera até eu voltar. Eu tenho que cuidar de algumas coisas primeiro.}

# 36. YOU LOOK LIKE A MAN IN TROUBLE, AND I MIGHT BE ABLE TO HELP YOU. WHAT DO YOU SAY? (18)
{565}{}{E quanto à sua oferta, eu poderia usar alguma ajuda. Veja, eu preciso sair da cidade, mas coisas
 foi complicado por causa de um certo ... mal-entendido ...}
{566}{}{Que mal-entendido?}

# 101. FLOAT (WTG)
{585}{}{Tempo para sair do Reno ...}
{586}{}{Maldita caixa ...}
{587}{}{Mais pesado do que eu lembro ...}

# 102. FLOAT (WTG)
{595}{}{Aqui estamos…}
{596}{}{É este aqui mesmo.}

# 103. HERE'S THE GRAVE (WTG)
{605}{}{Aqui estamos…*whew*...the money's in…this grave here.}
{606}{}{Desça, Lloyd.}
{607}{}{Deixe-me dar uma olhada neste primeiro grave ...}
{609}{}{Bem, fique de pé e deixe-me descobrir ...}
{610}{}{Saia daqui, Lloyd. O dinheiro agora é meu.}

# 104. DIG IT UP, LLOYD (103)
{615}{}{(Looks winded.) Como ... parte de seus ... deveres de guarda, eu ... agradeço se você ... desenterrar.}
{616}{}{Uh ...}
{617}{}{Há dois tipos de pessoas neste mundo, Lloyd. Aqueles com armas carregadas e aqueles que cavam.}
{620}{}{Tudo bem então, eu vou fazer ...}

# 105. DIG IT UP, LLOYD (104, 109)
{625}{}{(Lloyd murmura em voz baixa, depois passa a cavar).}
{626}{}{(Lloyd murmura em voz baixa, depois passa a cavar ... cuidadosamente. Menos de um minuto
 mais tarde, ele tira uma minhoca de debaixo da sujeira e a deixa de lado. Ele encolhe os ombros timidamente.)}
{627}{}{É isso mesmo. Você está indo bem. Mantem. Cavar um pouco mais rápido.}
{628}{}{Um bom, Lloyd. Continue cavando. Vamos ver o que mais está por aí.}

# 106. LLOYD KEEPS DIGGING (105, 108)
{635}{}{(Meia hora depois, Lloyd mergulhou a sujeira suficiente para revelar uma pequena
 A tampa do reservatório é colocada no chão ... você tem certeza de que não a teria encontrado se Lloyd não tivesse informado sobre isso.
 Lloyd respira profundamente e limpa sua testa.) Antigo ... precipício ... abrigo.}
{636}{}{(Uma meia hora mais tarde, você cavou a sujeira bastante o suficiente para revelar uma pequena tampa de poço definida em
 o chão. Você não teria encontrado se Lloyd não lhe dissesse para onde cavar. Como você descobriu, Lloyd fala.)
 É um antigo refúgio. Achei uma semana atrás enquanto visitávamos a área.}
{637}{}{Bem, deixe-me abrir isso, e vamos começar a trabalhar.}
{638}{}{Abra o orifício, Lloyd.}

# 107. EXAMINE THE GRAVE (103, 104)
{645}{}{(A sujeira ao redor da sepultura parece ter sido perturbada recentemente. Por algum motivo, a
 distância Lloyd está de pé para o túmulo faz você se perguntar se não foi preso.)}
{646}{}{Eu acho que você deveria cavar, Lloyd.}
{647}{}{Hmmmm. Deixe-me examinar mais de perto o túmulo ...}
{648}{}{Retire-se, Lloyd. Eu vou começar a cavar.}

# 108. EXAMINE THE GRAVE (103, 104)
{655}{}{(A sujeira ao redor da sepultura parece ter sido perturbada recentemente. Isso faria
 Se Lloyd enterrou as fichas aqui.)}

# 109. LOOK FOR TRAPS (107)
{665}{}{(Você faz uma análise do site e escova a sujeira. Como você, você percebeu um
 Mina terrestre enterrada na sujeira. Você desarmá-lo com cuidado e guardá-lo em seu pacote.)}
{666}{}{Esqueça disso, Lloyd? Vamos ver se você pode esquecer ESTE, homem morto.}
{667}{}{Eu acho que você deveria cavar, Lloyd. Conheça isso.}
{668}{}{Vou deixar isso passar, Lloyd ... desta vez. Agora fique de volta enquanto eu continuo cavando.}

# 110. MANHOLE COVER (106)
{675}{}{(A tampa do reservatório abre com um grito enferrujado, revelando um buraco escuro que conduz para baixo).}
{676}{}{Entre lá, Lloyd.}
{677}{}{Retire-se, Lloyd. Eu vou entrar.}

# 111. MANHOLE COVER, LLOYD FIRST (110)
{685}{}{(Lloyd franziu a testa, pensa em fazer um comentário, então encolhe os ombros e sai no poço
 tampa.)}
{686}{}{Apresse-se, Lloyd.}
{687}{}{HEY LLOYD, CAPTURA! (Coloque a minas no buraco).}
{688}{}{Eu estou descendo depois de você, Lloyd.}

# 112. WAIT . . . (111)
{695}{}{(Você ouve Lloyd grunhir abaixo.) Segure-se ... quase conseguiu ... (Existe a raspagem de metal,
 depois silêncio.)}
{696}{}{Faça um movimento, Lloyd. Nós não temos o dia todo.}
{698}{}{Estou descendo, Lloyd.}

# 113. MANHOLE COVER (111, 112)
{706}{}{Tudo em um dia de trabalho...}

# 114. LLOYD, TAKE OFF (103, 107, 108, 109)
{715}{}{Certo, certo ... todo seu. Sem problemas. Estou indo embora. (Retorna, depois se afasta.}
{716}{}{(Deixe ele ir.)}
{717}{}{(Tire-o nas costas.)}

# GOLGOTHA ENTRANCE MESSAGE
{1000}{}{Depois de uma longa caminhada, você alcança os contrafortes do Golgotha. Uma vez lá, Lloyd leva você a um
 dos túmulos.}
{1001}{}{Você segue Lloyd ao Golgotha. Uma vez lá, ele escava uma das sepulturas.}
{1002}{}{Você perde Lloyd quando você sai de New Reno.}
{1050}{}{Você deixa Lloyd partir.}

# END LINES
{5213}{}{ Eu}
{7213}{}{Quem U}
