# 0. QUICK LOOK
{100}{}{Você vê Mason.}

# 0. LOOK
{150}{}{Você vê um homem de meia-idade poderosamente construído com uma linha de cabelo retraída.}
{151}{}{Você vê Mason. He is watching you carefully.}

# 1. FLOAT (WTG)
{200}{}{O que você está fazendo aqui em cima?}

# 2. FLOAT: PLAYER IS TRAVELING WITH COMPANIONS (WTG)
{205}{}{Bem, confira este buquê de idiotas.}

# 3. FLOAT: PLAYER TOUCHES DOOR, PERMISSION = FALSE (WTG)
{210}{}{Toque nessa porta novamente, e eu vou transformá-lo em uma tocha.}

# 4. FLOAT/CLICK: PERMISSION = TRUE (WTG)
{215}{}{Você pode continuar ... ESTA vez.}

# 5. INTRO (WTG)
{220}{}{Você fez uma caminhada no lugar errado, tribal. Obter.}
{221}{}{Este não é um estúdio pornográfico. Obter.}
{222}{}{O que você está fazendo aqui, pungente? Perder o seu caminho para o anel de boxe? Saia daqui.}
{223}{}{Fique esperto}
{224}{}{Oog faz declaração de missão}
{225}{}{Afastar-se}
{226}{}{O que está por trás dessa porta?}
{227}{}{Quero ver o Sr. Salvatore.}
{228}{}{Posso perguntar-lhe onde você consegue essas pistolas a laser?}
{229}{}{A palavra é, você Salvatores envenenou aquele garoto de Wright.}
{230}{}{Tudo bem, então eu vou embora.}

# 6. GET SMART (5)
{240}{}{Bata, retardue. Eu não vou te contar de novo.}
{241}{}{Diga-me WHUT novamente?}

# 7. I WANT TO SEE MR. SALVATORE (5, 11)
{250}{}{A vida está cheia de decepções. Agora, GET, capiche?}
{251}{}{(Sarcástico.) Atrás dessa porta? Essa porta está bem ali? Por que, esse é o quarto de Mr. SALVATORE. Agora bata-o.}
{252}{}{Quero ver o Sr. Salvatore. I want a job.}
{253}{}{Olhe, dipshit ... você ainda quer ter seu trabalho amanhã? Tenho algumas informações sobre uma das outras famílias em Reno
 que o Sr. Salvatore vai querer ouvir. Então, deixe-me falar com ele AGORA.}
{254}{}{Onde você consegue essas pistolas a laser?}

# 8. LOOK, DIPSHIT . . . (FAILED) (7)
{265}{}{}
{266}{}{Menino, você deve ser mais bêbado do que falar comigo assim. Mais uma palavra, apenas mais uma palavra, e
 e uma tocha.}
{267}{}{Garota, você deve ser mais fofo do que falar comigo assim. Mais uma palavra, apenas mais uma palavra, e
 e uma tocha.}
{268}{}{I SAID, Quero ver o Sr. Salvatore.}
{270}{}{(Deixe em silêncio.)}

# 9. LOOK, DIPSHIT . . . (SUCCEEDS) (7)
{275}{}{(Seu rosto enrubesce. De repente, fala com o ar.) Com licença, Sr. Salvatore, este é Mason.}
{276}{}{Isso ... homem ... diz que ele tem algo que você quer ouvir.}
{277}{}{Esta ... mulher ... diz que ela tem algo que você quer ouvir.}
{278}{}{(Esperar...)}
{279}{}{(Aça Mason antes que ele possa continuar.)}

# 10. I WANT TO SEE MR. SALVATORE. I WANT A JOB. (7)
{285}{}{Olha, talvez você não tenha ouvido, tribal, mas este é o lugar de Salvatore. O meu trabalho é garantir que o chefe
 não é incomodado por cachorros como você. Agora corra de volta para a sua tribo e cozinhe uma das suas pessoas para o jantar.}

# 11. WHERE DO YOU GET THOSE LASER PISTOLS? (5, 7, 10)
{295}{}{Estas pistolas? Ah, gee, não posso dizer com razão. Apenas esqueci. (Scowls.) Olha, tribal. Se você não
 Desligue agora, vou transformá-lo em uma tocha. Agora receba.}
{298}{}{OK! Eu vou, vou.}
{299}{}{Deixe em silêncio.}

# 12. FINAL STRAW (6, 8)
{305}{}{EU AVISI-lo, asshole, agora você está ... (Mason de repente pausa, ouvindo algo que você não pode ouvir. Depois de um momento, seus dentes se fecham.) O Sr. Salvatore diz que você pode entrar ...}
{1305}{}{.}
{306}{}{Oh, eu irei bem. Depois de te matar.}
{307}{}{Agradeço, assholio, vou ter certeza de mencionar seus costumes para o Sr. Salvatore.}
{308}{}{Tudo bem então.}

# 13. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (56)
{315}{}{(Mason pára você.) Olhe ... (Inclina-se, baixa a voz.) ... algumas regras básicas, menino.}
{316}{}{Olhe ... (Inclina-se, baixa a voz.) ... Algumas regras básicas, garota.}
{317}{}{Não desperdice o tempo do Sr. Salvatore, e não lhe dê nenhuma besteira, ou você me responderá.}
{318}{}{Entendido.}
{319}{}{Sim, sim, seja o que for. Saia do meu caminho.}

# 14. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (13)
{325}{}{(Mason pára você de novo.) Eu ainda não fiquei. Você mostra-lhe o RESPETO. Você o chama * Mr. Salvatore * em todos os momentos,
 e quando ele fala, você * cale a boca e escute. * Entenda?}
{327}{}{Última chance, Mason: Saia do meu caminho.}

# 15. WARNING ABOUT MR. SALVATORE BEFORE GOING IN (14)
{335}{}{Um dia, você e eu resolveremos esse problema com autoridade.}
{336}{}{Não tenho problema. Tudo é legal.}
{337}{}{Explique-me.}

# 16. PATIENCE = 0 (5, 7, 10, 13, 14, 15, 17, 18, 19, 20, 21, 22, 27, 30, 34, 35, 36, 42, 53, 56, 57, 58, 59)
{345}{}{Tudo bem, isso faz isso, inteligente! Você cruzou a linha ... (Cracks knuckles.) ... agora você vai se machucar.}
{346}{}{Ferido? William?}
{347}{}{Vamos dançar.}
{348}{}{Não, VOCE é a pessoa que vai ter HURT! Você me escuta, MASON ?! VOCÊ É O QUE O QUE GANHA OBTER H -}

# 17. MISSION ONE LLOYD = MASON (WTG)
{355}{}{O tempo que você mostrou, menino.}
{356}{}{O tempo que você mostrou, menina.}
{357}{}{'Bout time que você mostrou. Não sei por que o Sr. Salvatore iria contratar lixo porno, mas não vou questioná-lo
 nele.}
{358}{}{Este bum que roubou do Sr. Salvatore, seu nome é Lloyd. O Sr. Salvatore o quer morto e esse dinheiro
 ele roubou de volta. Quando você fez o trabalho, informe de volta para ME, entenda? Acha que pode lidar com isso?}
{359}{}{Onde posso encontrar o Lloyd?}
{360}{}{Como é Lloyd?}
{361}{}{Quanto ele roubou?}
{362}{}{Por que você não está rastreando Lloyd?}
{364}{}{Certo. Obrigado Mason.}
{365}{}{Eu dou conta disso. Agora, fique de volta e deixe-me trabalhar.}
{366}{}{Já cuidei da "situação" de Lloyd.}

# 18. QUESTION NODE? (19, 20, 21, 22, 23, 24, 25, 26)
{375}{}{Sim? Como o quê?}
{381}{}{Isso é tudo o que preciso saber. Obrigado Mason.}
{382}{}{Isso é tudo o que preciso saber. Afaste-se e deixe-me chegar ao trabalho, Mason.}

# 19. WHERE CAN I FIND LLOYD? (17, 18)
{390}{}{Ele está deitado, então, rastreá-lo, será o seu trabalho, garoto.}
{391}{}{Ele está ficando baixo, então rastreá-lo vai ser seu trabalho, garota.}
{392}{}{Melhor aposta? Verifique alguns dos bares da rua Virgin. Lloyd pode estar correndo outra hora lá.}
{393}{}{Tive algumas outras questões ...}

# 20. WHAT DOES LLOYD LOOK LIKE? (17, 18)
{400}{}{Lloyd? Inferno ... ele está em altura média, cabelos brancos e castanhos. Por último, eu o vi, ele tinha uma camisa bronzeada e escura
 cachecol marrom. Ele provavelmente não mudou suas roupas desde que eu o vi por último.}
{401}{}{Você sabe, estranhamente, que descreve muitas pessoas que vi desde que saí de Arroyo.}

# 21. SIMILAR MODELS (20)
{410}{}{Haw! Você está me dizendo. Os nomes são a única maneira de dizer as pessoas hoje em dia. Você pensaria que existe
 apenas dez tipos de pessoas no mundo. (Leans in.) Como eu percebi, houve um grande acidente de clonagem no passado.}

# 22. HOW MUCH DID HE STEAL? (17, 18)
{420}{}{Cerca de mil fichas. Agora olhe, isso não está faltando ao Sr. Salvatore, mas ele tem essa política
 com respeito a pessoas que tiraram de tudo. Se eu fosse você, lembro disso. O Sr. Salvatore vai querer todos os chips
 costas.}

# 23. WHY AREN'T YOU TRACKING DOWN LLOYD? (17, 18)
{430}{}{Fiquei com os olhos abertos, mas Lloyd tem sido bastante cuidadoso em manter-se fora da vista ... de Salvatore
 olhos, mesmo assim. Estou apostando que o chefe mostra que você pode ter melhor sorte, ser novo na cidade e 'tudo.}
{431}{}{Tanto faz. Eu estou fora -}
{432}{}{Eu tive algum outro qu -}
{433}{}{Tudo bem então, eu vou verificar -}

# 24. CHILL. I WAS JUST CURIOUS. (57)
{440}{}{Tudo bem então.}
{442}{}{Isso é tudo o que preciso saber. Agora volte e deixe-me trabalhar.}

# 26. YOU FOUND LLOYD? (WTG)
{465}{}{Você encontrou o Lloyd ainda?}
{466}{}{(Scowls.) You BETTER have some good news for me. Você encontrou o Lloyd ainda?}
{467}{}{(Scowls.) Você MELHOR tem boas notícias para o Sr. Salvatore ou você estará dormindo com os radscorpions.}
{468}{}{Não, ainda não. Eu tinha mais algumas perguntas sobre Lloyd ...}
{470}{}{Sim, encontrei Lloyd.}
{472}{}{Não, acho que ele deixou a cidade com o dinheiro.}
{473}{}{Ainda não. Desculpe incomodá-lo.}

# 27. LAST TIME (18, 19, 20, 21, 22, 24, 25, 26, 57)
{480}{}{Aguarde um minuto, rápido. Eu tornarei este VERDADEIRO claro para que você possa entender: não fale comigo novamente até
 você encontra Lloyd. Ou você vai me irritar. Agora faça o seu trabalho.}
{481}{}{Tudo bem, tudo bem…}
{482}{}{Morda-me, Mason.}

# 28. LAST TIME (26)
{490}{}{Eu disse para você não voltar até encontrar Lloyd ... EU DEVO-O. (Taps sua cabeça.) Você é estúpido ?! Devemos ser,
 porque aqui você está falando comigo novamente. Estúpido ... e DEAD.}
{491}{}{Vamos, Shitheel.}
{492}{}{Pode vir.}
{493}{}{Não, VOCE é a pessoa que é ESTÚPIDA E MORTE! Você me escuta, MASON ?! VOCE É O QUE É STU -}

# 29. NO, HE LEFT TOWN WITH THE CASH (26)
{500}{}{(Olha para você com descrença.) Você fez uma careta. Nós lhe damos um trabalho simples, e você parafusa. Isto. Acima.}
{501}{}{Você deve ser o filho de puta mais estonteante vivo.}
{502}{}{Você deve ser a cadela STUPIDEST viva.}
{503}{}{(Sneers, alcança armas). Hora de morrer, tribal.}
{506}{}{Não, VOCE é a pessoa que vai morrer! Você me escuta, MASON ?! VOCE É O QUE O QUE GONNA D -}

# 30. SUCCESS (26)
{514}{}{Bem, por que diabos você não disse isso no primeiro lugar, idiota? Diga ao Sr. Salvatore o que você encontrou.}
{515}{}{(Nods, franzindo a testa um pouco). Bem, entao, então, diga ao Sr. Salvatore o que encontrou.}
{516}{}{Sério? É ISSO o que devo fazer? Obrigado Mason. Sem você, eu nem sabia como obter
 de um lugar para outro. Sheesh. Idiota.}
{517}{}{Tudo certo.}

# 31. FLOAT MESSAGE: DONE JOB? (WTG)
{520}{}{Você já fez o trabalho?}

# 32. FLOAT MESSAGE: GO SEE THE BOSS (WTG)
{525}{}{Vá ver o Sr. Salvatore. Ele está esperando por você.}

# 33. TRIBUTE = MASON (WTG)
{530}{}{Certo, então. Você será uma agência de cobrança de um homem. Simples da broca: visite a farmácia de Renesco
 na fila comercial, colete o tributo, 1000 fichas, depois traga de volta aqui.}
{531}{}{Tudo certo...anything else?}

# 34. RETURN FROM RENESCO (WTG)
{535}{}{Você ainda recolhe o tributo?}
{536}{}{(Frowns.) Você ainda recolhe o tributo?}
{537}{}{(Scowls.) Você MELHOR tem o dinheiro desta vez, dipshit. A espera do Sr. Salvatore.}
{539}{}{Onde eu deveria colecionar de novo?}
{540}{}{Renesco está me dando merda. Diz que ele deu duas semanas atrás, e ele não deveria pagar mais um mês.}
{542}{}{Uh ... conseguiu. Aqui está o dinheiro.}
{543}{}{Fiz isso, mas não tenho dinheiro comigo ...}
{544}{}{Quase. Eu vou tê-lo na próxima vez, Mason.}
{546}{}{Eu tenho seu tributo aqui ... homem morto.}

# 35. RENESCO'S? (34)
{555}{}{* Farmacia de Renesco. * No lado oeste. Mil fichas. Agora continue.}
{556}{}{Isso é tudo o que preciso saber. Agora fique de volta e deixe-me chegar ao trabalho, Mason.}

# 36. WARNING (34, 35, 38, 39, 59)
{565}{}{Aguarde um minuto, rápido. Eu tornarei esta VERDADEIRA clara para que você possa entender: não me fale novamente
 até obter esse dinheiro da Renesco. Ou você vai me irritar. Agora faça o seu trabalho.}

# 37. LAST TIME (34)
{575}{}{Eu disse para você não voltar até você ter esse dinheiro ... EU TE DEVO. (Taps sua cabeça.) Você é estúpido ?!
 Deve ser, porque aqui você está falando comigo novamente. Estúpido ... e DEAD.}

# 38. RENESCO'S GIVING ME SHIT. (34)
{585}{}{(Os olhos de Mason são estreitos). Então, friggin 'o que? Você fala para quem você trabalhou?}
{586}{}{Sim.}
{587}{}{Bem não.}

# 39. YES. (38)
{595}{}{Então você mostrou a quem você trabalhou?}
{596}{}{Mostre a ele?}
{598}{}{Uh, não. Eu vou tê-lo na próxima vez, Mason.}

# 40. NO. (38, 39)
{605}{}{O que, eu tenho que segurar sua MÃO ?! Mais fácil maldita coisa do mundo, e você vem chorando pra mim
 'May-son, May-son, então, não está pagando seu tributo'.}
{606}{}{Agora aguarde ...}

# 41. IF PLAYER KILLED RENESCO. (WTG)
{615}{}{(Assim que ele vê você, Mason sneers.) Apenas o filho da mãe tolo que eu estava procurando.}
{617}{}{Você não pode coletar tributo de pessoas mortas. (Alcança suas armas.) Você acabou de ferrar, mas BOM.}
{618}{}{Sim, bem, eu estava ficando cansado de você de qualquer maneira ...}
{619}{}{Não, VOCE é a pessoa QUE FIZ CHEIO, MAS BOM! Você me escuta, MASON ?! VOCE É O QUE FOI FU -}

# 42. PLAYER GOT MONEY. (34)
{625}{}{(Mason acena com a cabeça, parece desapontado.) Heh. Achei que sangrássemos o Renesco de seu último centavo. Tudo bem então,
 bem ... entre no chefe. (Frowns.) Vá em frente agora.}

# 43. GET THE HELL OUTTA HERE. (WTG)
{635}{}{Saia daqui. O Sr. Salvatore não quer mais fazer negócios com você.}

# 44. GUARD = MASON (WTG)
{640}{}{Certo, o chefe diz que você está vindo em uma pequena TRANSACÇÃO que estamos fazendo. Certifique-se de que você venha
 armado ... não traga nenhum pea-shooters ... então volte e fale comigo.}
{642}{}{O Sr. Salvatore disse que você deveria me dar uma pistola a laser.}
{643}{}{O que esta transação estava fazendo?}
{644}{}{Estou pronto para ir agora. Vamos fazer isso.}
{645}{}{Me dê algum tempo para me preparar, e vou voltar.}

# 45. SALVATORE SAID YOU WERE GOING TO GIVE ME A LASER PISTOL. (44, 46, 49)
{655}{}{Sim, essa é a palavra. Aqui você vai ... também não esteja jogando com isso. Você machuca NENHUMA com essa coisa,
 e eu vou atirar em você morto.}
{656}{}{Você pode me ensinar a usar isso?}
{658}{}{Tudo bem então, eu estou bem para ir. Vamos fazer isso.}

# 46. WHAT IS THIS TRANSACTION WE'RE DOING? (44, 45, 49, 51, 52)
{665}{}{(Sneers.) Se o chefe não lhe falou, então você não precisa saber. Então feche seu buraco ... e não seja
 contando a alguém sobre o que está acontecendo, nem, ou vou garantir que você nunca mais diga nada.}

# 47. I'M READY TO GO RIGHT NOW. (45, 46, 49, 51, 52)
{675}{}{Vamos então.}
{676}{}{Siga-o e os outros Salvatores no deserto ...}

# 48. GIVE ME SOME TIME TO GET READY . . . (44, 45, 46, 49, 51, 52)
{685}{}{Certifique-se de se apressar. Nós só temos uma janela de 24 horas antes que o negócio fique fora. Você sente falta, e eu me certificarei
 você apodrece no Golgotha.}
{686}{}{Não se preocupe. Eu estarei lá.}

# 49. RETURN . . . (WTG)
{695}{}{Você sofreu bastante sono? Talvez agora você esteja pronto para ir?}
{696}{}{O que esta transação estava fazendo de novo?}
{697}{}{Sim. Let's do it.}
{698}{}{Preciso de um pouco mais de tempo, então voltarei.}
{699}{}{Você pode me ensinar a usar esta pistola?}

# 50. RETURN LATE . . . (WTG)
{705}{}{Eu tenho tido pena de matá-lo por um longo tempo ... EU AVISei o que aconteceria se você estivesse atrasado.}
{706}{}{Bem, perdoe me foda por não ter um relógio.}
{707}{}{Não, VOCE é aquilo foi AVISADO! Você me escuta, MASON ?! VOCE É AQUELE QUE ADVERTIR -}

# 51. WHY DO I NEED . . . (52)
{715}{}{Por que você precisa questionar tudo o que eu digo ?! Olhe: a outra parte nesta transação não vai
 ser ferido por esses lightbringers, ok? Então, certifique-se de ter algo mais com você.}

# 52. CAN YOU TEACH ME . . . (45, 49, 51)
{725}{}{(Grunts.) Maldição ... olhe, primeiro, segure-o como ESTA. (Ajusta a sua aderência). Agora, a câmara de carga
 está aqui ... (Depois de uma hora e alguma prática, Mason melhorou sua habilidade com armas de energia.)}
{726}{}{Então, por que eu preciso de algo diferente disso? Estas pistolas parecem bastante poderosas.}
{728}{}{Bem, eu estou bem para ir. Vamos fazer isso.}
{729}{}{Tudo bem então. Me dê algum tempo para me preparar, e vou voltar.}

# 53. MADE MAN. (WTG)
{735}{}{(Grunts.) Ei, lá ...}
{736}{}{Pegue os itens.}

# 54. MADE MAN 2. (53)
{745}{}{Além disso, nós Salvatores ... nós conseguimos um ENTENDIMENTO especial com Miss Kitty na Cat's Paw. E Eldridge
 na loja de armas ... e na de Renesco. (Winks.) Divirta-se.}
{746}{}{Obrigado Mason.}
{747}{}{Gee, Mason, obrigado ... exceto na próxima vez, por que você não me liga, senhor? Gostaria disso. HA HA HA HA HA HA ...}
{748}{}{Gee, Mason, obrigado ... exceto na próxima vez, por que você não me liga, "senhora?" Gostaria disso. HA HA HA HA HA HA ...}

# 55. MADE MAN 2. (WTG)
{755}{}{Olá senhor.}
{756}{}{Olá Madame.}

# 56. LOOK, DIPSHIT . . . (SUCCEEDS) (9)
{765}{}{(Mason faz uma pausa, ouve algo que não pode ouvir. Depois de um momento, seus dentes se apertam). Sr. Salvatore
 diz que você pode entrar,}
{766}{}{Obrigado, assholio. Vou ter certeza de mencionar seus costumes para o Sr. Salvatore.}

# 57. WHY AREN'T YOU TRACKING DOWN LLOYD? (23)
{775}{}{(Olhos estreitos). Claro, se você estiver IMPLYANDO eu não estou fazendo o meu trabalho, então você e eu podemos ter
 uma discussão de perto e pessoal agora. O Sr. Salvatore não vai perguntar o que aconteceu com o culpa dele.}
{776}{}{Eu não estou sugerindo que você não está fazendo o seu trabalho, splinterdick. Estou dizendo a você.}
{777}{}{Acalme-se. Eu só estava curioso.}
{778}{}{Esta conversa está começando a me aborrecer. Estou fora daqui.}

# 58. EXTORTION ASSIGNMENT (33)
{785}{}{Não deixe que gramps lhe dê qualquer besteira ... se ele fizer, diga que você trabalha para o Sr. Salvatore. Isso deve ser claro
 todos os mal-entendidos. Você entendeu?}
{786}{}{Consegui. Agora, fique de volta e deixe-me trabalhar.}

# 59. NO 2. (40)
{795}{}{Cresça algumas BOLAS, garoto, e tome * cuidado dela. *}
{796}{}{Devia ter pensado que isso aconteceria, enviando uma mulher para fazer o trabalho do homem. Saia do seu * bitching * e tome * cuide disso. *}
{797}{}{Eu vou cuidar disso, então. Obrigado Mason. You've been a BIG help.}
{798}{}{Eu vou cuidar disso, então.}
{799}{}{Oh, eu vou cuidar disso. Começando com você.}

# 60. IF SALVATORE WAS ASSASSINATED (WTG)
{805}{}{Pobre Sr. Salvatore ... ele estava muito velho. Adivinha que ele finalmente respirou o último.}
{806}{}{* Snff * ... Sr. Salvatore ... ele era como um pai para mim.}
{807}{}{Adorei aquele sussurro velho. Agora ele está morto, e ele nunca saberá como eu sentia.}

# 61. IF PC KILLED RENESCO BEFORE TALKING TO MASON (WTG)
{815}{}{(Sneers quando ele vê você.) Ouvi dizer que Renesco teve um "acidente". Palavra na rua você tinha algo
 para fazer com isso. Só para você saber, ele era um dos nossos, tribal. Acho que nos deve ... no sangue.}
{818}{}{Não, VOCE é a pessoa que vai RETIRE! Você me escuta, MASON ?! VOCÊ É O QUE O QUE GONNA R -}

# 62. ACCUSE MURDER (5, 7, 10)
{825}{}{(O rosto de Mason fica frio, depois ele alcança suas armas).}
{826}{}{Eu não acho que você vai me matar tão fácil quanto envenenar esse garoto ...}

# 63. TRADE DISRUPTED (WTG)
{835}{}{Deixa pra lá. O trabalho foi cancelado. Saia daqui.}

# 64. GO SEE THE BOSS
{840}{}{Feliz que você finalmente voltou. O chefe quer vê-lo.}


# END LINES
{5735}{}{. O Sr. Salvatore enviou a palavra de sua promoção. Parabéns. Eu tenho algumas coisas para você ... lessee ... (Ele lhe dá um
 uma grande quantidade de itens.) Cuidado com essas coisas ...}
{5765}{}{.}
