# quick looks
{100}{}{Você vê um boxeador.}
{101}{}{Você vê Pete "The Hurricaine" McKneely.}

# examines
{150}{}{Você vê o que parece ser um homem branco pesadamente musculoso. Ele parece tão fraco que você poderia derrubá-lo com uma fatia de pizza.}
{151}{}{Seu maxilar brilha como vidro.}
{152}{}{Parece que ele não duraria sete segundos no ringue.}
{153}{}{Parece que você poderia derrubá-lo com uma fatia de pizza.}

# FLOAT DIALOGUE
{200}{}{* Hnffff *}
{201}{}{* Hnrggg *}
{202}{}{:: Flexões ::}
{203}{}{Estou arruinada}
{204}{}{estou cansado}
{205}{}{* Phewwww * dia áspero}
{206}{}{Trabalhar fora sempre me deixa cansado}
{207}{}{Luta me esgota}
{208}{}{Melhor ir polir minha maxila de vidro}

#CLICK DIALOGUE
# (ANY PRIZEFIGHTER)
{300}{}{:: O boxeador olha para você e cobre sua mandíbula ::}
{301}{}{:: O boxeador olha para você e esfrega a mandíbula ::}
# (NORMAL)
{302}{}{Trabalhar fora sempre me deixa cansado}
{303}{}{Estou bem se o meu gerente pode entrar no ringue e parar a luta}
{304}{}{Eu sou Pete. Pete "Derrote" McKneely.}
{305}{}{Eu gosto de pizza, mas devo ter cuidado com a crosta}
{306}{}{Abri a porta esta manhã e o vento me derrubou}
{307}{}{Luta me esgota}
{308}{}{Melhor ir polir minha maxila de vidro}
{309}{}{Se eu continuar treinando, posso durar dez segundos no ringue}
# (FEMALE)
{310}{}{Eu só posso durar sete segundos no ringue, mas eu posso durar dez segundos na cama}
