# QUICK LOOK
{100}{}{Você vê um homem idoso.}
{101}{}{Você vê Old Man McGee.}

# LOOK
{150}{}{Você vê um homem idoso. He looks angry and is mumbling to himself.}
{151}{}{Você vê Old Man McGee. He looks angry and is mumbling to himself.}

# 1. FLOAT [McGEE = JACKPOT, MALE] (WTG)
{200}{}{Você sumabitch! Você me pegou toda a sorte!}
{201}{}{Eu vou matar você! Tome isso, raider!}
{202}{}{Acho que não tenho areia, whippersnapper? Vamos então!}
{203}{}{Cão e filho uva cão!}
{204}{}{Vou derrubar o vento para você, empurrá-lo de volta, então puxe-o para fora de você novamente.}
{205}{}{Você quer alguns dos Old McGee, whippersnapper?}
{206}{}{Eu consegui seu número, seu pequeno cocksucker.}
{207}{}{Eu vou balear o sagrado, uivando o alcatrão para você.}
{208}{}{Você quer alguns de mim, isso? Vou consertar seu vagão.}
{209}{}{Eu vou cortar o figo de você, cara.}
{210}{}{Eu vou te geld como um brahmin.}

# 2. FLOAT (McGEE = JACKPOT, FEMALE] (WTG)
{225}{}{Você é uma prostituta! Vocês roubaram a sorte da mah!}
{226}{}{Eu consegui seu número, sua pequena puta.}
{227}{}{Olha para pegar meu punho, garota?}
{228}{}{Vou bater-te, menina.}

# 3. FLOAT (SLOT MACHINE) (WTG)
{235}{}{Goddurn peça o 'brahmin merda!}
{236}{}{Friggin 'one-armed raider! Pague ol 'McGee!}
{237}{}{Pare de aguentar no ol 'McGee, querida ...}
{238}{}{A casa ganha-me novamente!}
{239}{}{Vamos agora, garota, seja bom para McGee agora ...}
{240}{}{Me dê a soma luv, querida.}
{241}{}{Eu fiz tudo sobre a recompensa, vamos agora!}
{242}{}{Jest mais um puxão ...}
{243}{}{Gonna GIT my goddurn chips, iffen leva todo o ano ...}
{244}{}{Pox on yore hide, um bandido de um braço!}
{245}{}{Mebbe eu tenho um chanst hoje ...}
{246}{}{Tomorry tem que ter uma cara de linda.}
{247}{}{Hoje vou ganhar. Lady Luck sez está perto disso.}
{248}{}{:: Máquina Bangs ::}

# 4. FLOAT (McGEE WARNING] (WTG)
{255}{}{Toque minha máquina novamente, e vejo que você esconde roturando no Gólgota.}
{256}{}{Você é melhor ficar longe da minha máquina, se você sabe o que é bom para você ...}

# 5. FLOAT (McGEE BROKE] (WTG)
{260}{}{Droga! Estou quebrando novamente!}
{261}{}{A casa ganha-me novamente!}
{262}{}{Precisa de mais algumas fichas ...}
{263}{}{Goddurn máquina! Mantém todas as minhas fichas ...}

# 6. FLOAT (McGEE APOLOGIZES] (WTG)
{270}{}{Você fez minhas desculpas, estranho. A sorte seja com você.}
{271}{}{Desculpe, perdi a paciência. O sol do deserto faz um homem dizer algumas coisas horríveis.}
{272}{}{:: Dicas de um chapéu imaginário ::}

# 7. JACKPOT, ATTACK (WTG)
{275}{}{}
{276}{}{}
{277}{}{Você! Você quem bateu no jackpot na minha máquina! O que eu tenho jogado com cinco anos poderosos *
 e nunca obteve um chip de Deus!}
{278}{}{Ernnhh?}
{279}{}{Agora, segure -}

# 8. JACKPOT, CHANCE TO TALK (7)
{285}{}{Eu puxei todas as poupanças de vida naquela puta de um braço e ela nem sequer me dá a
 hora do dia. Então VOCÊ vem e não pegue tudo!}
{286}{}{Eu recebi seu número, seu pequeno cocksucker!}
{287}{}{Eu consegui seu número, sua puta pequena!}
{288}{}{Hunh? Little koksuker? Eu BIG koksucker}
{289}{}{Hunh? Onde puta? Eu tenho dez centavos}
{290}{}{Não, eu, koksucker. Eu}
{291}{}{Não, eu sou puta. Eu}
{292}{}{Calma, Sr. McGee. Podemos falar sobre isso?}
{293}{}{Acalme-se agora, senhor. Podemos falar sobre isso?}
{294}{}{Olha, ganhei o quadrado de dinheiro e justo.}
{295}{}{Espere um minuto. Que tal eu concedo o dinheiro que ganhei?}
{296}{}{Cocksucker? COCKSUCKER ?! Gramps, você vai precisar de cirurgia para tirar minha bota do seu traseiro.}
{297}{}{Slut? SLUT? Gramps, você vai precisar de cirurgia para tirar minha bota do seu traseiro.}
{298}{}{Tanto faz. Estou indo embora.}

# 9. JACKPOT, McGEE NEGOTIATING (8)
{305}{}{Conversa?! CONVERSA?! O que, no INFERNO, temos que falar, seu maldito ladrão!}
{307}{}{Olha, ganhei o dinheiro quadrado e justo, gramps. Não gosta? Esse é o seu problema.}
{309}{}{Ladrao? Gramps, é melhor você observar sua língua antes de empurrá-la pela garganta.}
{310}{}{Esqueça, então. Estou indo embora.}

# 10. JACKPOT, McGEE COMBAT (8)
{315}{}{Boy, não vamos falar sobre SHIT. A única coisa que você vai fazer está pegando balas.}
{316}{}{Girlie, não vamos falar sobre SHIT. A única coisa que você vai fazer está pegando balas.}
{317}{}{(Alcança seu rifle, aperta o ar) Eh? Onde diabos é meu rifle ...?}
{318}{}{Deixe-me te mostrar...}

# 11. JACKPOT, SQUARE AND FAIR (8, 9)
{325}{}{Quadrado e justo, meu ASS de lírio branco! Menino, você foi e fez assinou seu próprio mandato de morte!}
{326}{}{Quadrado e justo, meu ASS de lírio branco! Girlie, você foi e fez assinou seu próprio mandato de morte!}

# 12. RECOMPENSATE McGEE . . .? (8, 9)
{335}{}{O que? (Pisca) Você está falando sobre me dar meus ganhos de volta? Todos os 473 chips?}
{336}{}{Uh, e quanto a 250 fichas?}
{337}{}{Certo. Todos os 473 chips. Aqui você vai.}
{338}{}{Bem, ainda não posso. Eu não tenho muito sobre mim.}
{339}{}{Esqueça. Estou indo embora.}

# 13. GIVE McGEE BACK ½ (12)
{345}{}{}
{346}{}{}
{347}{}{Hmmmmmm. Wahl, agora ... não está perto do que eu perdi naquela máquina, mas isso não
 parece um negócio muito ruim para mim.}
{348}{}{Tudo bem, garoto. 250 fichas, e isso vai resolver as coisas bem.}
{349}{}{Tudo bem, menina. 250 fichas, e isso vai resolver as coisas bem.}
{350}{}{Tudo bem então.}

# 14. McGEE SAYS NO DICE (12, 9)
{355}{}{Sem dados, garoto. Estou recebendo meus ganhos agora mesmo.}
{356}{}{Sem dados, menina. Estou recebendo meus ganhos agora mesmo.}

# 15. PAY McGEE BACK EVERYTHING (12)
{365}{}{}
{366}{}{}
{367}{}{(Parpadeia como chips trocam de mãos) Bem, agora ... diabos, eu não sei o que dizer.}
{368}{}{Foi um tipo poderoso, garoto ... senhor, senhor. EU…}
{369}{}{Era um tipo poderoso de você, garota ... er, senhorita. EU…}
{370}{}{Sim?}

# 16. TURN BACK ON McGEE (8, 12, 9)
{375}{}{Não se atreva a me voltar, garoto!}
{376}{}{Não se atreva a voltar para mim, garota!}

# 17. McGEE INTRO (WTG)
{385}{}{}
{386}{}{}
{387}{}{Eh? O que você quer, garoto?}
{388}{}{Eh? O que você quer, garota?}
{389}{}{Eh? O que, na condenação, você está querendo agora, garoto?}
{390}{}{Eh? O que, na condenação, você está querendo agora, garota?}
{391}{}{Quem você}
{392}{}{ quer jogar máquina}
{393}{}{Afastar-se}
{394}{}{Quem é Você?}
{395}{}{O que você está fazendo?}
{396}{}{Mente se eu dê uma atração?}
{397}{}{Nada. Desculpe incomodá-lo.}

# 18. BOTHERING McGEE (17)
{405}{}{(Uma série de símbolos rola na máquina caça-níquel, e há um * bzzzzt *) Dammmit!
 Máquina obstinada! Eu vou receber minhas fichas de volta a qualquer hora agora ...}
{407}{}{ vá agora! By-yye}
{409}{}{Uh ... há quanto tempo você está fazendo isso?}
{410}{}{Deixa pra lá. Desculpe incomodá-lo.}

# 19. McGEE's REASON FOR LIVING (18)
{415}{}{}
{416}{}{}
{417}{}{Feche agora até cinco anos ... Eu acho que qualquer dia agora esta máquina tem que sair, e quando é ...
 Paydirt! Heh heh!}
{418}{}{Uh, boa sorte para você, então.}
{419}{}{Greeeeeat. Fale com você mais tarde.}

# 20. McGEE JEALOUS (17, 18)
{425}{}{}
{426}{}{}
{427}{}{(Sneers) Deixe você tocar minha máquina? N 'Jinx mah sorte ?! De jeito nenhum! Git fora daqui!}
{428}{}{Tudo bem então...}

# 21. RETARDED vs. McGEE (8)
{435}{}{Damn slobberin 'retard! Estou levando esse dinheiro agora mesmo!}

# 22. McGEE LOSES TEMPER, VOL. 56 (9, 12)
{445}{}{Parece que vou tirar meu dinheiro do seu cadáver, então, garoto! Prepare-se para comer!}
{446}{}{Parece que vou tirar meu dinheiro do seu cadáver, então, garota! Prepare-se para comer!}

# 23. JACKPOT, ATTACK 2 (7)
{455}{}{Eu puxei todas as poupanças de vida naquela puta de um braço e ela nem sequer me dá
 na hora do dia. Então VOCÊ vem e tira tudo!}

# 24. PAY McGEE BACK EVERYTHING (15)
{465}{}{O sol do deserto pode fazer um homem dizer uma série de coisas terríveis, e você fez minhas desculpas
 bem aqui e agora. (Dicas um chapéu imaginário respeitosamente.)}
{466}{}{Sorte seja com você, senhor.}
{467}{}{Sorte seja com você, senhorita.}
{468}{}{Tudo bem então. Apology accepted.}

# end lines
{1290}{}{.}
