# QUICK LOOK
{100}{}{Você vê um dos homens de Mordino.}
# RAMIREZ
{101}{}{Você vê Ramírez.}

# LOOK
{150}{}{Você vê um homem queimado pelo sol com muito restolho e pele escamosa. Ele está olhando nervosamente.}
{151}{}{Você vê um dos homens de Mordino.}
{152}{}{Você vê um dos homens de Mordino. He looks a little jumpy.}
{153}{}{Você vê um dos homens de Mordino. He looks nervous.}
{154}{}{Você vê um dos homens de Mordino. He looks like he hasn't slept in a while.}
# RAMIREZ
{160}{}{Você vê um homem de aparência deslumbrante com cabelos pretos espinhosos. Ele está olhando nervosamente.}

# 1. FLOAT [ENCLAVE DESTROYED]
{200}{}{Yo!}
{201}{}{Fuckin'-A,}
{202}{}{:: Dá você thumbs up sign ::}
{203}{}{:: Whistles ::}

# 2. FLOAT [POWER ARMOR]
{205}{}{Como você se engana com essa coisa?}

# 3. FLOAT/CLICK [MADE MAN, SAME FAM, ARMED
{210}{}{Uma boa peça que você chegou lá,}

# 4. FLOAT/CLICK [MADE MAN, SAME FAMILY, SNEAK]
{215}{}{O que você está rastejando, eh,}

# 5. FLOAT [MADE MAN, SAME FAMILY]
{220}{}{Algum Jet em você, casas?}
{221}{}{Ei,}
{222}{}{Claro que poderia usar uma bebida. Droga…}
{223}{}{Sheee-it, está quente.}
{224}{}{Qualquer notícia do topo, eh,}

# 7. FLOAT [MADE MAN, NOT SAME FAMILY]
{230}{}{Yo!Cabron! You looking for th' Angel o' Death? Beat it!}
{231}{}{O que o fu ... você! Você, o que você está fazendo aqui?}
{232}{}{Yo!Puta! You looking for th' Angel o' Death? Beat it!}

# 9. FLOAT [MALE, ARMED, RESPECTFUL]
{235}{}{Yo!Sorry hombre, you can't be carrying that around in here.}
{236}{}{Yo!Homes, put that thing away 'fore you start making people nervous.}

# 10. FLOAT [FEMALE, ARMED, RESPECTFUL]
{240}{}{Yo!Chica, you can't be carrying that around in here.}
{241}{}{Yo!Chica, put that thing away 'fore you start making people nervous.}

# 11. FLOAT [MALE, SNEAK, PRIZEFIGHTER]
{245}{}{Por que diabos você se esgueirou,}

# 12. FLOAT [FEMALE, SNEAK, PRIZEFIGHTER]
{250}{}{Por que você saiu, chica? Com esse gancho direito você conseguiu, você deveria andar alto.}

# 13. FLOAT/CLICK [PRIZEFIGHTER]
{255}{}{Onde você aprende a lutar,}
{256}{}{Você conseguiu os cojones de um Mordino.}
{257}{}{A última luta foi algo fora de um épico, um homem.}
{258}{}{Cuidado com o Masticador. Ele gosta de comer ouvidos.}
{259}{}{Voe como uma borboleta, como uma abelha. Thaz você, ali mesmo,}
{260}{}{Eu costumava lutar no ringue, mas eu machuquei meu braço, então eu não brigo mais, sabe?}
{261}{}{Sabe, os Mordinos podem usar algum músculo como você,}
{262}{}{De onde você luta, você luta assim? Voce é bom. Eu quis dizer bom.}
{263}{}{Você deveria conversar com Lil 'Jesus sobre um trabalho,}
{264}{}{Aposte com você, melhor dinheiro que eu já coloquei. Você estava jogando como fora de negócios de ninguém.}
{265}{}{Viu você lutar no ringue,}
{266}{}{Quanto você bancar,}
{267}{}{Onde você trabalha, eh?}
{268}{}{Eu pegaria uma bebida se eu não tivesse jogado todo meu dinheiro apostando em seu oponente.}
{269}{}{Onde você aprende a lutar,chica? You're vicious. You got the MOVES.}
{270}{}{Você conseguiu que o espírito fosse um Mordino.}
{271}{}{A última luta foi algo fora de um épico, menina.}
{272}{}{Onde você trabalha, eh? Need a spotter?}
{273}{}{Cuidado com o Masticador. Ele gosta de comer ouvidos ... ele é um cara doente.}

# 15. FLOAT/CLICK [ARMED, PORN STAR, FEMALE]
{280}{}{Ei,hey, hey! Chica, you need to me to put that weapon away for you?}
{281}{}{O que, você quer que eu tire a tiragem você e tudo? Vamos, peguei esse ferro antes de eu me preocupar.}

# 16. FLOAT [MALE, SNEAK, PORN STAR]
{285}{}{Por que diabos você se esgueirou,}

# 17. FLOAT/CLICK [SNEAK, PORN STAR, FEMALE]
{290}{}{De jeito nenhum, você está furioso por um Mordino com um corpo assim, menina.}

# 18. FLOAT [PORN STAR]
{295}{}{Seu filme não foi ruim, mas você obviamente precisa de algumas dicas de mim.}
{296}{}{Dê uma boa palavra aos irmãos para mim, tudo bem?}
{297}{}{Ei,}
{298}{}{Estou pronto, estou disponível, você me colocou em um filme, ok? Estamos falando bilheteria,}
{299}{}{Eu sou o melhor amante do latim. Não há amante latino como eu.}
{300}{}{Fale com os Irmãos sobre mim,}
{301}{}{Eu ouço Tommy the Balls quer dar uma seleção privada.}
{302}{}{Então, e você e eu fazendo um filme? Eu vou te tratar direito, menina. Eu mostro o que um amante latino pode fazer.}
{303}{}{Por que você não pára depois do trabalho?}
{304}{}{Você tem amigos?}
{305}{}{Você está fazendo a coisa certa, esticando os Mordinos. Nós estamos indo lugares.}
{306}{}{Você precisa de um Jet? Posso te preparar, chica.}
{307}{}{Chica, não há nada que eu não faria por você ... vamos, agora. Me dê um pequeno beijo.}
{308}{}{Precisa de chems? Hootch? Algumas batatas fritas? Posso configurá-lo. Eu sou co-nnected, ver?}

# 20. FLOAT/CLICK [ARMED, SLAVER]
{315}{}{Não mostre ferro por aqui, amigo. Coloque isso fora.}

# 21. FLOAT/CLICK [SNEAK, SLAVER]
{320}{}{Não esqueça, slaver, tudo bem? Você está entre amigos.}

# 22. FLOAT/CLICK [ARMED, NO REP]
{325}{}{Yo!You dumb or something? Put that thing away before I haveta hurt you.}
{326}{}{Você procura uma lobotomia de backalley? Coloque essa coisa longe.}
{327}{}{Yo, chica! Você é burro ou algo assim? Coloque essa coisa antes que eu tenha que machucá-lo.}

# 24. FLOAT/CLICK [SNEAK, MALE, NO REP]
{330}{}{Por que diabos você se esgueirou? Você está olhando para ser baleado?}

# 25. FLOAT/CLICK [SNEAK, FEMALE, NO REP]
{335}{}{Por que você saiu, chica? Você está olhando para ser baleado?}

# 26. FLOAT/CLICK [COMPANION: ROBOBRAIN]
{340}{}{Pegue esse lixo de papelão fora daqui.}
{341}{}{Nenhum bots permitido aqui. Cai fora.}
{342}{}{Esse robô vai ser sucata se ficar.}

# 27. FLOAT/CLICK [COMPANION: MARCUS]
{345}{}{Pensei que eu cheirava mutante. Tire-o daqui a diante, ficamos bravos.}
{346}{}{Você é um amante mutante? O seu lugar é FORA. Se não.}
{347}{}{Esse mutante procura tornar-se alvo de prática? Fique em volta e ele receberá o seu desejo.}

# 28. FLOAT/CLICK [COMPANION: LENNY]
{350}{}{Pensei que eu cheirava a alguma podridão. Tire esse garoto ghoul de seu para fora aqui.}
{351}{}{Pegue esse ghoul fedido fora daqui. Agora.}
{352}{}{Esse ghoul não está fora de lugar aqui em um minuto, ele ficará mais morto do que ele já é.}

# 29. FLOAT [ENCLAVE DESTROYED]
{355}{}{Eu fiz uma audição para a parte de um dos principais NPCs, mas eu só consegui esse pouco de parte do NPC. Espero que eu não receba um problema.}
{356}{}{O novo Reno foi desenhado por Chris Avellone e roteado por Tom French. Eles são um grupo de pacientes doentes.}
{357}{}{Yo!}
{358}{}{Fuckin'-A,}
{359}{}{Ouviu que os Irmãos da Córsega estão procurando por você.}
{360}{}{Eu pensei que o presidente era apenas uma lenda.}
{361}{}{Você parece ter atravessado o inferno e de volta. Relaxe um pouco. Você merece isso.}
{362}{}{Cara, os bastardos do Enclave têm sorte de não mexerem com os Mordinos.}

# 30. FLOAT [MADE MAN, SAME FAMILY]
{370}{}{Algum Jet em você, casas?}
{371}{}{Como está pendurado? Pendura como um martelo, homem, tudo bem.}
{372}{}{Heh? :: Spits :: Whazzup,}
{373}{}{Bom, vejo você,}
{374}{}{Claro que poderia usar uma bebida. Droga…}
{375}{}{Sabe, mesmo velho, mesmo velho. Como está com você}
{376}{}{Sheee-it, está quente.}
{377}{}{Big Man Mordino está bem? Diga-lhe que estou cuidando dele, eh,}
{378}{}{Conectou um scorp ontem à noite. Quase me picado, fez.}
{379}{}{Os bispos mexem com nós, eles serão comida de vermes, certo?}
{380}{}{Qualquer notícia do topo, eh,}
{381}{}{Quando vamos atacar alguns Bispos, hein? Minha arma está enferrujada.}
{382}{}{Eles Salvatores caminham como se fossem Reno. Eles precisam ser levados de volta à escola, você sabe?}
{383}{}{Ouço Tommy the Balls estar na cidade. Melhor se deitar.}
{384}{}{Você tem Jet sobre você, chica? Estou aqui atrás.}

# 32. CLICK [MADE MAN, NOT SAME FAMILY]
{400}{}{Você tem alguns cojones por aqui. Eu sugiro que você os perca e caminhe.}
{401}{}{Sua mãe devia estar em um canil, pelo seu aspecto.}
{402}{}{Você parece um homem que não sabe quando ele está prestes a morrer.}
{403}{}{Hijo de puta ...}
{404}{}{Você falando comigo? Você falando comigo?}
{405}{}{Fale comigo de novo, e vou preenchê-lo tão cheio, mesmo que o Superman não possa ver através de você.}
{406}{}{:: Spits at your feet ::}
{407}{}{Você acha que pode caminhar e conversar com um Mordino, conversar sobre isso? Cai fora.}
{408}{}{Fale comigo novamente, e eu vou matar sua família, seu cachorro, então você. Duas vezes.}
{409}{}{:: Spits at your feet ::}
{410}{}{Você acha que pode caminhar e conversar com um Mordino, conversar sobre isso? Cai fora.}
{411}{}{Fale comigo novamente, puta, e eu vou preenchê-lo tão cheio, mesmo que o Superman não possa ver através de você.}
{412}{}{Você não está melhor voltando ao seu canil, puta?}
{413}{}{Você deve ser a puta mais estúpida em todo o mundo até mesmo falar comigo.}
{414}{}{Hija de puta ...}

# 34. CLICK [SLAVER]
{420}{}{Naw, eu não sou o cara para conversar sobre escravos ... você deve conversar com Lil 'Jesus.}
{421}{}{Quando você vai trazer alguns escravos de boa aparência? Desculpe, colhei a última temporada, slaver. Gasto.}
{422}{}{Mordinos não precisa de nenhum escravo para conseguir isso. Claro, se você tiver algum, precisa descarregar ...}
{423}{}{Eu não sou a pessoa a quem falar sobre lidar com escravos.}
{424}{}{Você está fazendo a coisa certa, esticando os Mordinos. Nós estamos indo lugares.}
{425}{}{Como estão as coisas no Den, hein?}

# 35. CLICK [MALE/FEMALE, NO REP, GOOD REACTION]
{430}{}{Procurando por trabalho, hein? Fale com Lil 'Jesus.}

# 36. CLICK [NO REP, BAD REACTION]
{435}{}{Olha, eu não sou sua compadre, então não me falem mais.}
{436}{}{Mordinos não tem amigos, exceto Mordinos. Sopro, tribal.}
{437}{}{Sopro, tribal.}
{438}{}{Eu não tenho tempo para você agora.}
{439}{}{Saia daqui.}
{440}{}{Lixo tribal ...}
{441}{}{O que diabos você quer, tribal?}
{442}{}{Eu não tenho tempo para você agora.}
{443}{}{Obter.}
{444}{}{Lixo tribal ...}
{445}{}{Eu não vou te dar nenhum Jet, não importa o quanto você implora. Git.}
{446}{}{Olha, não sou seu irmão, então não esteja falando mais comigo.}
{447}{}{Olha, preciso de uma prostituta, vou comprar uma. Agora, git, chica.}
{448}{}{Mordinos não tem amigos, exceto Mordinos. Blow, puta.}
{449}{}{Blow, puta.}

# RAMIREZ UNIQUE DIALOG
# 37. CLICK [DELIVERY = ASSIGNED] (WTG)
{460}{}{(Olha como você se aproxima, zombou.) Você está procurando problemas, casas?}
{461}{}{(Olha como você se aproxima, zombou.) Você está procurando problemas, menina?}
{462}{}{Você Ramirez? O grande Jesus me deu esse pacote para lhe dar.}
{463}{}{Sem problemas. Eu irei.}

# 38. CLICK [DELIVERY = ASSIGNED] (37)
{470}{}{(Takes box.) 'Bout time. Nós corremos quase fora Jet. (Sniffs, tosse ligeiramente). Não consigo imaginar tudo
 Vai ... eh?}
{471}{}{Sim, bem, você cuida agora -}
{472}{}{A julgar pela tosse do jato e pelo jeito que você está esfregando o nariz, não estou com vontade de dizer onde todos os jatos enviados aqui vão.}

# 39. CLICK [DELIVERY = ASSIGNED] (38)
{473}{}{J grande, veja, ele cuida de nós, hein? Na semana passada, peguei três escravos que ficaram tolos o bastante para correr.
 Então recebo uma recompensa, veja? Heh. E você não está ficando com ela. Você se curve e busca. Eu, eu sou GUARDA.}
{474}{}{Sim, ótimo. Você cuida agora.}
{475}{}{Pergunto-me se o Grande Jesus percebe como esses três escravos poderiam ter escapado sob os NOSES de uma pessoa tão perspicaz, Jet-dependente
 Guardas como você.}
{476}{}{Ramirez ... tenha cuidado com o que você me diz, está bem? Não deixe sua boca levar seu traseiro em problemas.}

# 40. CLICK [DELIVERY = ASSIGNED] (39)
{480}{}{(Pisca.) Eh ...? O que você diz?}
{481}{}{Nada que você entenda ou eu gostaria de repetir agora. Você se importa, ok?}
{482}{}{Eu disse: "Eu me pergunto se o Grande Jesus percebe como esses escravos poderiam ter escapado sob o NOSES de tal
 Guardas perspicazes, jazentes, como você. "}

# 41. CLICK [DELIVERY = ASSIGNED] (40)
{490}{}{(Parpadeia, sorri na confusão.) Eh? Sim sim. Eu sou afiado, veja ... per-septive ... Eu sou um GUARD, certo?}
{491}{}{Sim, você mencionou isso antes. Se eu fosse você, Ramirez, eu faria toda a humanidade um favor e tomaria essa caixa inteira
 De Jet de uma só vez. Até logo.}
{492}{}{Rapaz, fico feliz por ter tido a sabedoria para lhe dar todas as armas automáticas. Me faz sentir seguro. Mais tarde, Ramírez.}

# 42. CLICK [DELIVERY = ASSIGNED] (39)
{493}{}{(Pisca.) Eh ...? O que você diz?}
{494}{}{Esqueça. Vá agachar em uma arma de fogo e puxar o gatilho, está tudo bem?}
{495}{}{Nada. Se eu fosse você, Ramírez, eu faria todo o bem-estar da humanidade e levaria toda a caixa de Jet de uma só vez. Até logo.}
{496}{}{(Ir embora.)}

# 43. CLICK [DELIVERY = ASSIGNED] (39, 40, 41, 42)
{500}{}{(À medida que você se afasta, Ramirez grunhiu.) Ei! Esta caixa foi aberta!}
{501}{}{Você esquenta, casas?}
{502}{}{Você esquenta, menina?}
{503}{}{Ninguém confusa com Ramirez, você me ouve ?!}
{504}{}{Sim, eu ouço você. Mas não por muito mais tempo.}
{505}{}{Essas são as últimas palavras malditas, Ramírez.}

# delivered box
{600}{}{Você entregou o pacote de Big Jesus para Ramirez.}

# END OF LINES
{1200}{}{! Maneira de chutar a bunda do Enclave!}
{1201}{}{, Maneira de ensinar-lhes bastardos Enclave como as coisas são feitas DOWNTOWN.}
{1210}{}{.}
{1215}{}{? Mordinos anda orgulhoso.}
{1221}{}{! Que pasa?}
{1224}{}{?}
{1245}{}{? Com esse gancho direito você conseguiu, você deveria andar alto.}
{1255}{}{? Você é vicioso. Você obteve os MOVES, casas.}
{1259}{}{.}
{1261}{}{. Outras famílias vêem você chegar, eles caíram em um segundo.}
{1263}{}{.}
{1265}{}{. Você estava perdendo esse cara.}
{1266}{}{?}
{1285}{}{? Vamos, caminhe alto.}
{1297}{}{! Que pasa? Você vai me arrumar com os Irmãos, ou o que?}
{1298}{}{, bilheteria!}
{1300}{}{… Vamos lá. Eu posso fazer isso.}
{1357}{}{! Maneira de chutar a bunda do Enclave!}
{1358}{}{, Maneira de ensinar-lhes bastardos Enclave como as coisas são feitas DOWNTOWN.}
{1372}{}{?}
{1373}{}{. Onde você esteve?}
{1375}{}{?}
{1377}{}{?}
{1380}{}{?}
