# 0. QUICK LOOK
{100}{}{Você vê um guarda.}

# 0. LOOK
{150}{}{Você vê um guarda de aparência aborrecida. Parece que ele preferiria estar em outro lugar.}
{151}{}{Você vê um dos guardas de aparência aborrecida de Myron.}
{152}{}{Você vê um dos guardas de aparência aborrecida de Myron. He looks like he would rather be anywhere else.}

# 1. FLOAT [TOUCH LOCKER] (WTG)
{200}{}{Toque minha merda novamente, e eu vou matar você.}

# 2. FLOAT [TOUCH DOOR AND MYRON_PERMISSION = TRUE] (WTG)
{205}{}{Continue. Tudo está legal.}
{206}{}{Entre. É legal.}

# 3. FLOAT [TOUCH DOOR] (WTG)
{210}{}{Pegue essa porta novamente, e você tirará um toco.}
{211}{}{Afaste-se daqui.}

# 4. COMPANION: MYRON (X)
{215}{}{Ei, Myron. Você está caminhando?}
{216}{}{Fique atento, Myron.}
{217}{}{Não tenha problemas, Myron, assustado?}
{218}{}{Não vá longe demais, Myron.}

# 5. FLOAT [MADE MAN]
{225}{}{Ei,}
{5225}{}{! Whazzup?}

# 6. FLOAT [MADE MAN, NOT MORDINO, ARMED]
{230}{}{É um dos}
{5230}{}{S! Desperte-os!}

# 7. FLOAT/CLICK [MALE, MADE MAN, NOT SAME FAMILY]
{235}{}{Você tem alguns cojones por aqui. Eu sugiro que você os perca e caminhe.}
{236}{}{Você parece um}

# 8. CLICK [FEMALE, MADE MAN, NOT SAME FAMILY]
{240}{}{Você não está melhor voltando para o seu}
{241}{}{Você parece um}

# 9. FLOAT [ARMED, MALE, NO REP]
{245}{}{Coloque essa arma longe ... a menos que você QUER problema.}

# 10. FLOAT [SNEAK, MALE, NO REP]
{250}{}{Intruso!}

# 11. FLOAT [COMPANION: ROBOBRAIN]
{260}{}{Pegue esse lixo de papelão fora daqui.}
{261}{}{Nenhum bots permitido aqui. Cai fora.}
{262}{}{Esse robô vai ser sucata se ficar.}

# 12. FLOAT [COMPANION: MARCUS]
{270}{}{Eu * pensei * Eu cheirei mutante. Tire-o daqui a diante, ficamos bravos.}
{271}{}{Você é um amante mutante? O seu lugar é FORA. Se não.}
{272}{}{Esse mutante procura tornar-se alvo de prática? Fique em volta e ele receberá o seu desejo.}

# 13. FLOAT [COMPANION: LENNY]
{280}{}{Eu * pensei * Eu cheirei algo apodrecendo. Tire esse garoto ghoul de seu para fora aqui.}
{281}{}{Tenha a mãe fodida fodida da fome aqui. Agora.}
{282}{}{Esse ghoul não está fora de lugar aqui em um minuto, ele ficará mais morto do que ele já é.}

# 14. [PORN STAR, FEMALE OR FEMALE, CHR > 5] (WTG)
{290}{}{:: Whoa. :: Verifique isso.}
{291}{}{Ei,chica, you looking for some company?}
{292}{}{Quer perder algum tempo conosco, chica?}
{293}{}{:: Açaa como um lobo quando ele vê você :: Awooooooo!}

# 15. [SLAVER] (WTG)
{300}{}{Que diabos você quer, slaver? Os escravos estão no andar de cima.}

# 16. FLOAT [MYRON_LEFT_STABLES] (WTG)
{305}{}{O que aconteceu com Myron?}

# 17. FLOAT [NORMAL] (WTG)
{310}{}{Myron ainda está dormindo?}
{311}{}{Estou entediado.}
{312}{}{Pegue a luta na noite passada?}
{313}{}{Não posso esperar até que essa mudança acabe.}

# 18. INTRO (WTG)
{320}{}{Ajudá-lo com alguma coisa, amigo? Esta área está fora dos limites.}
{321}{}{Bem, bem, bem ... nós conseguimos uma estrela em nosso meio. Você recebeu uma consulta com Myron, chica?}
{322}{}{Ajudá-lo com alguma coisa, menina? Esta área está fora dos limites.}
{323}{}{(O guarda sorri, olha você para cima e para baixo.) Tem uma consulta com Myron, chica?}
{324}{}{Eu quero paz mundial}
{325}{}{Eu quero ir atrás da porta}
{326}{}{Hoo Yoo}
{327}{}{Afastar-se}
{328}{}{Fora dos limites? O que está por trás dessa porta?}
{329}{}{Estou aqui para ver Myron.}
{330}{}{Estou aqui para ver Myron. I have a badge.}
{331}{}{Estou aqui para ver Myron. Me and him got a "special appointment," see?}
{332}{}{Claro que sim. Você vai me manter parado aqui, bonito, ou seus olhos ainda estão preenchidos?}
{333}{}{Eu sinto Muito? Qual nomeação?}
{334}{}{Desculpe, lugar errado. Eu irei agora.}

# 19. RETARD (18)
{350}{}{Você escapa da sua barraca, escravo? Talvez seja melhor levantar o seu traseiro para cima antes de colocá-lo em um
 Das gaiolas.}
{351}{}{ME QUERO O MUNDO PAZ ME QUER PAZ MUNDIAL}
{352}{}{ME DIMO QUE QUERO IR PORTA PASSADA}
{353}{}{HOO YOO}
{354}{}{Shamble off}

# 20. LOUD RETARD (19)
{360}{}{(Lei de armas). Eu vou gostar disso. Eu não fui espancado por pelo menos uma hora ...}
{361}{}{(Lei de armas). Eu vou gostar disso. Não fui morto por dois dias ...}
{362}{}{YOO ONE WHO GET HURT}
{363}{}{ ESMAGAR}
{364}{}{Tente e execute.}
{365}{}{Pal, você está prestes a obter o chicote de um tempo de vida.}

# 21. WHAT'S BEHIND THAT DOOR? (18, 30)
{370}{}{(Sneers.) Desculpe. "Need-ta-know" base. Agora perca ... amigo.}
{371}{}{(Sneers.) Desculpe. "Need-ta-know" base. Agora se perca, menina.}
{374}{}{Deixe-me passar. Tenho que superar essa porta.}
{375}{}{Tudo bem, tudo bem.}

# 22. I'M HERE TO SEE MYRON (18, 21, 30)
{380}{}{Oh, você é, você está? Bem, porra, por que você não disse algo antes? Nós poderíamos ter evitado
 Esta conversa, e eu poderia ter lhe dito que se mexeram desde o início.}
{381}{}{Myron está esperando por mim. É melhor me deixar vê-lo, ou você vai ouvir sobre isso mais tarde.}

# 23. MYRON'S EXPECTING ME (22, 29)
{390}{}{Nah. Você não vai vê-lo. Agora se preocupe antes de me irritar.}
{391}{}{Você pode, pelo menos, dar uma mensagem para mim?}

# 24. MYRON'S EXPECTING ME  2 (21, 22, 23)
{400}{}{Não. Agora piss OFF, sua pequena merda.}
{401}{}{Eu vou ficar até você me deixar entrar. Na verdade, eu gostaria de vê-lo TRY e me mover.}
{402}{}{Eu vou ficar até me deixar entrar. Na verdade, eu gostaria de vê-lo desculpa sacos de merda Tente e me mude.}
{404}{}{Tudo certo.}

# 25. I'M STAYING (24)
{411}{}{Nem eu…}
{412}{}{Defenda-se.}

# 26. MYRON + BADGE (18, 21, 22, 23, 24, 29, 30)
{425}{}{Sim? Deixa eu ver. Hmmmm. (Emblema de cheques, encolhe os ombros.) Tudo bem, mas mantenha-o rápido. Myron está ocupado, e ele não
 Como sendo perturbado.}
{426}{}{Consegui.}

# 27. SURE DO (18)
{435}{}{(Os olhos vagam para cima e para baixo do seu corpo.) Sim, por enquanto ... heh heh ... no entanto, talvez eu precise de um outro preencher um pouco
 mais tarde. Quando você terminar, isso é.}
{436}{}{Eu vou ... tenha isso em mente. Posso entrar?}
{437}{}{Vamos ver, tudo bem?}

# 28. CAN I HEAD ON IN? (27, 31)
{445}{}{Claro, querido. Participe em.}
{446}{}{Sim, dirija-se.}
{447}{}{Obrigado.}

# 29. SKANKY REFUSAL (18)
{455}{}{Você? Ha! Chica, a menos que Myron de repente tenha ficado cego, você não vai lá. Eu conheço seus gostos, certo?
 Ele não está interessado em nenhuma prostituta queimada por Jetank.}
{457}{}{Look, Estou aqui para ver Myron. I have a badge.}
{458}{}{Eu irei agora.}

# 30. APPOINTMENT? (18)
{465}{}{Oh, desculpe. Achei que você era outra pessoa. O que você quer, menina?}
{466}{}{O que está por trás dessa porta?}

# 31. MADE MAN OR PERMISSION (WTG)
{475}{}{Myron esperando por você?}
{5476}{}{! Myron está logo atrás dessa porta. Ele está esperando por você?}
{477}{}{Sim. Posso entrar? Temos negócios para discutir.}
{478}{}{Não, agora não. Tome cuidado, pessoal.}

# 32. MYRON AIN'T AROUND (WTG)
{485}{}{Myron não está.}
{5486}{}{, whatzzup? Oh, hey…Myron não está.}
{487}{}{Posso seguir de qualquer jeito?}

# 33. MYRON AIN'T AROUND 2 (32)
{495}{}{(Shrugs.) Eu não ligo. Se você quiser esperar por ele, vá em frente. Eu não sei quando ele vai voltar ... ou se
 Ele vai voltar.}

# END LINES
{5236}{}{ Homem que não sabe quando ele está prestes a morrer.}
{5240}{}{ Canil, puta?}
{5241}{}{ Cadela que não sabe quando está prestes a morrer.}
