# 0. QUICK LOOK
{100}{}{Você vê Orville Wright.}

# 0. LOOK
{150}{}{Você vê um cavalheiro bem vestido. Ele parece sempre irritado. É provavelmente por isso que seu cabelo castanho está grisalho pelas bordas.}
{151}{}{Você vê uma ruim de Orville Wright. Parece que ele está prestes a retirar o que resta do cabelo dele.}
{152}{}{Você vê uma ruim de Orville Wright. Ele parece chateado e suspira muito.}

# 1. THIEF WARNING MESSAGE (WTG)
{200}{}{Afaste-se daí!}

# 2. COMBAT MESSAGES (WTG)
{210}{}{Crianças, vá embora! É um sucesso!}
{211}{}{Você vai morrer, seu sonuvabitch.}
{212}{}{Entre na minha casa, você ...}
{213}{}{Então eles mandam você para fazer seu trabalho sujo ...}
{214}{}{Você é um hitman de dois bits, esse é o seu último trabalho ...}

# 3. FLOAT COMMENTS (WTG)
{220}{}{O casamento não é uma palavra. É uma sentença de morte.}
{221}{}{Damn Salvatores ...}
{222}{}{Onde estão essas crianças malditas ...}
{223}{}{Alguém já viu Christopher? Diga a esse garoto que eu quero vê-lo. Agora.}
{224}{}{Pergunto-me se o nosso casamento é juridicamente vinculativo ...}
{225}{}{Os lucros deste trimestre estão baixos ... melhor começar a regar o acéfalo.}
{226}{}{Precisa de mais álcool etílico. E menos Eyl Wright ...}
{227}{}{Salvatores estão em silêncio ...}
{228}{}{Onde diabos é essa mulher? Etilo! Etilo!}
{229}{}{Preciso parar de amaldiçoar as crianças ...}
{230}{}{Teremos que expandir a distribuição se continuarmos no mapa de Reno ...}
{231}{}{Se Christopher me dá mais backtalk ...}
{232}{}{Traga-me o meu livro.}
{233}{}{Pobre Richard ...}
{234}{}{Um pouco de paz e tranquilidade para pedir ?! Controle-se!}

# 4. INTRO (PERMISSION = TRUE) (WTG)
{240}{}{(Os enrugamentos cobrem o rosto deste homem velho ... parece que qualquer expressão que não seja um carranca é estranha a ele. Somente alguns castanhos
 os cabelos são deixados em seus cabelos grisalhos grossos).}
{241}{}{Comece a falar, tribal. Quem é você e o que você quer?}
{242}{}{Comece a falar, escravidão. Quem é você e o que você quer?}
{243}{}{Eu}
{244}{}{Boogity boogity}
{245}{}{Yoo Boo Hoo Yooooo}
{246}{}{Kootchie Kootchie Koooo}
{247}{}{Quem diabos você}
{248}{}{Eu sou um viajante simples ... procurando trabalho.}
{249}{}{Os nomes}
{250}{}{Na verdade, parece ter entrado no quarto errado. Eu vou sair agora.}

# 5. RETARD SPEAK (4)
{260}{}{(Scowls.) Saia da minha visão. Você volta aqui novamente, eu vou ter voce, você me ouve?}
{262}{}{Uh-uh}
{263}{}{Você beija mamãe com essa boca?}
{264}{}{Você não pode me atirar em mim. Tirar-me só me faz ANGREE}
{265}{}{Vá no caminho e descubra outra coisa para falar com quem é tão engraçado}

# 6. WRIGHT ANGRY, NOT GONNA TAKE ANYMORE BULLSHIT (WTG, 5, 14, 19, 32, 34)
{275}{}{(Quando ele vê você, o rosto do Sr. Wright invade um grunhido e ele começa a gritar.)}
{276}{}{(O rosto do Sr. Wright invade um grunhido e ele começa a gritar.)}
{277}{}{Rapazes! Nós temos um visitante procurando uma parcela de terra no Golgotha! Entre aqui!}
{278}{}{Get in here, boyz! Euwanna play}
{279}{}{Whoa, agora aguarde ...!}
{280}{}{Isso faz isso! Estou cansada de sua besteira. Você estará morto antes que seus meninos possam chegar aqui.}
{281}{}{Eles não chegarão aqui a tempo de salvar sua vida ...}
{282}{}{Excuse me. Euand the exit have an appointment.}

# 7. ACTUALLY, I SEEM TO HAVE ENTERED THE WRONG ROOM. PARDON ME. (4, 8, 9, 10, 13, 14, 16, 17, 43)
{290}{}{Sim, talvez você MEJA sair e rapidamente. Se você ainda estiver aqui em cinco segundos, eu vou ter voce, você me ouve?}
{291}{}{Sim, parece que você tem esse hábito entrando e saindo. Talvez seja melhor cuidar desse problema o seu.}
{292}{}{Vou.}
{293}{}{O que você m -?}
{294}{}{Meus pensamentos exatamente. Tempo para você morrer.}

# 8. I AM A SIMPLE TRAVELER (4)
{300}{}{Não é SHIT? (Sneers.) Bem, prazer em conhecê-lo, "viajante simples". Fico feliz que você tenha parado, muito bom vizinho de você. (Sneer
 desmorona em um olhar franzido enquanto ele olha para você.) Procurando trabalho na família Wright, hein?}
{301}{}{Não é SHIT? (Sneers.) Bem, prazer em conhecê-lo, SLAVER. Fico feliz que você tenha parado, muito bom vizinho de você. (Sneer desmorona
 em uma careta.) Nós não lidamos com o seu tipo, você ouve? Agora, saia!}
{302}{}{Sim eu --}
{303}{}{Na verdade, parece ter entrado no quarto errado. Perdoe-me.}
{304}{}{Aguarde um minuto, não terminei conversando com você ainda. EU…}
{305}{}{Tudo certo. Parece que irei.}

# 9. I AM (4)
{310}{}{Não é SHIT? (Sneers.) Bem, prazer em conhecê-lo, "}
{311}{}{Sim eu --}

# 10. I'M LOOKING FOR A JOB. (8, 9)
{320}{}{Então, a minha familia é família Wright. Sangue mais espesso do que água e tudo. (Scowls.)}
{321}{}{O que faz você pensar que eu gostaria de lixo tribal como você na minha família? Recebi todos os assassinos que eu preciso.}
{322}{}{O que faz você pensar que eu preciso de um pedaço de galinha tribal como você na minha família? Eu consegui putas suficientes para sugar todo Cali do Norte.}
{323}{}{Dê-me um teste, então. Deixe-me provar a mim mesmo.}
{324}{}{Parece que eu vim para o lugar errado. Eu irei agora.}

# 11. GIVE ME A TEST (10)
{330}{}{(Estuda você por um momento.) Tudo bem. Talvez você não esteja na família poderia ser uma coisa boa. (Scowl desaparece.) Você tem filhos?}
{331}{}{Não é do meu conhecimento.}
{332}{}{Não é do meu conhecimento. I think I'd remember.}

# 12. NOT TO MY KNOWLEDGE (11)
{340}{}{Um dos meus filhos ... meu filho, Richard, faleceu recentemente. Sobredosagem de Chem. Jato.}
{341}{}{Como posso ajudar?}
{342}{}{Uh ... Eu realmente não vejo como posso -}

# 13. HOW CAN I HELP? (12)
{350}{}{Eu quero saber o que o negociante deu a SHIT a Richard e forçou-o a aceitar isso. Toda vez que envio meus meninos para descobrir,
 eles não aparecem em nada. Talvez alguém que não tenha sangue Wright possa obter algumas respostas.}
{351}{}{Uh, "forçou-o a aceitar?"}
{352}{}{Vou pegar o emprego.}
{353}{}{Não, esse trabalho não é meu estilo. É melhor eu ir.}

# 14. FORCED HIM TO TAKE IT? (13)
{360}{}{(O rosto fica vermelho.) Meus meninos estão limpos, e eles sabem ficar longe dessa merda, ou eu vou matá-los. Então, SUDDENLY, Richie ODs.
 Alguém bombeou uma tonelada de jato nele, tanto que fumos escorreram do nariz.}
{361}{}{Bem ... isso não significa que alguém seja responsável. Seu filho poderia ter tomado demais. Jet é altamente formador de hábitos.}
{362}{}{Hmmm. Vou pegar o emprego.}

# 15. I'LL DO IT (13, 14)
{370}{}{(Nods.) Tudo bem então. Agora olhe: você encontra aquele filho da puta que matou meu garoto, você não toca 'eu ... você apenas volta
 e me diga o nome do homem morto. (Eyes flaze.) Eu cuidarei disso a partir daí.}
{371}{}{Não falamos um preço.}
{372}{}{Alguma ligação?}
{373}{}{Encontre a pessoa que lhe deu o Jet, não os machuque, apenas volte e conte. Consegui.}

# 16. TALKED PRICE (13)
{380}{}{Sim, não estamos falando no preço, porque você não fez nada MAS fala. Estou deixando você provar seu valor. Faça seu trabalho,
 e você não precisa se preocupar com o dinheiro. Eu dou a minha palavra como Wright.}
{383}{}{Esqueça isso, então. Somente os tolos trabalham por nada. Estou fora daqui.}

# 17. LEADS? (15, 16)
{390}{}{(Eyes blaze.) Não ... todo mundo está assustado demais para falar ... com um Wright, mesmo assim. Se eu fosse você, eu "questionaria" alguns dos Reno
 químicos, veja o que eles sabem. Esse Jet veio de ALGUMA PARTE.}
{391}{}{Qualquer empurrador que suspeite?}
{393}{}{Olha, este trabalho não é meu estilo. É melhor eu ir.}

# 18. YOU FIND OUT WHO KILLED MY SON? (WTG)
{400}{}{Você novamente. Você descobriu quem matou meu filho?}
{401}{}{Ainda não. Eu estou trabalhando nisso.}
{402}{}{Sim, era Jules, o negociante na frente da cidade.}
{403}{}{Jagged Jimmy J, o negociante na 2ª Rua.}
{404}{}{Esse velho geezer, Renesco the Rocketman.}
{405}{}{Lil 'Jesus Mordino. Ele lança Jet.}
{406}{}{Seu filho não morreu de uma overdose. Ele foi envenenado.}

# 19. NAMED A KILLER, EXCEPT KILLER DEAD (18, 47)
{415}{}{É assim? A palavra é, o bastardo já morreu, mas não estou falando nada de novo. EU DEVO-lhe não tocar nele
 - você estragou tudo. Agora, você está morto.}
{416}{}{Esperar --}
{417}{}{Oh, sim, bem -}

# 20. NAMED A KILLER, KILLER IS ALIVE (18, 47)
{425}{}{Aquele bastardo viu seus últimos dias. Venha, ele estará morto. Mas ele vai morrer por muito tempo ...}
{426}{}{Agora, sobre o preço por fazer o meu trabalho ...}
{427}{}{Não menos do que ele merece.}
{428}{}{Uh, mas Renesco não deu Richard o Jet ... ele não sabia para quem era ... eram os SALVATORES
 que envenenou seu filho.}

# 21. PRICE (20, 50, 51)
{435}{}{Eu devo-lhe ... eu devo-lhe.}
{436}{}{Bem, agora, antes de entrar em detalhes, vamos liquidar contas primeiro ...}
{437}{}{Aqui está um pouco de dinheiro para o seu problema, além de algumas munições, bebidas alcoólicas do meu estoque privado ... e outra
 trabalho para você, se você estiver interessado.}
{438}{}{Estou interessado.}
{439}{}{Não, obrigado. Eu te vejo por aí.}

# 22. NOT YET (MURDER) (18, 52)
{445}{}{Se você voltar aqui novamente e você não fez o que eu pedi, eu vou ver você pendurado no Gólgota, tribal. NINGUÉM
 Perdi meu tempo. Você me entende?}
{446}{}{Se você acha que pode empurrar-me para isso, tribal, você está completamente errado. Eu tive isso com sua besteira. (Começa gritando.)
 Rapazes! Entre aqui!}
{447}{}{Entendido.}
{448}{}{Eu não sou o único para este trabalho, Sr. Wright. Encontre outra pessoa.}
{449}{}{Foda-se neste trabalho, foda-se com o seu filho morto e experimente-o. Estou fora daqui.}
{451}{}{Isso faz isso! Estou cansada de sua besteira. Você vai se juntar ao seu filho morto que usa quimicamente no inferno.}
{453}{}{Saia daqui.}

# 24. WHAT KIND OF PROPOSITION? (21, 29)
{465}{}{Acontece, não muito tempo atrás, encontrei um mapa que mostra uma antiga base do exército nas montanhas, não muito longe daqui. Você encontra uma maneira lá, e eu vejo que você é cuidada de ...}
{466}{}{Okee Dokee Mister Orderville}
{467}{}{ ir.}
{468}{}{Tudo certo. Eu vou verificar isso.}
{469}{}{Por que eu deveria ir? Você não enviou alguém já?}
{470}{}{Não está interessado, obrigado. Adeus.}
# extra 24
{471}{}{Já encontrei uma maneira de entrar na base. Há muitas armas antigas
 e hardware militar lá, tudo para a tomada.}
{472}{}{Já encontrei um caminho dentro da base. O problema é que houve um ... acidente ...
 A base está contaminada.}

# 25. YOU ALREADY SENT SOMEONE, DIDN'T YOU . . . (24)
{480}{}{(A expressão do Sr. Wright se aperta por um momento, então ele ressoa.) Heh. Não exatamente. As pessoas com quem obtive o mapa estão mortas.
 Eles eram um grupo difícil, mas todos foram aniquilados tentando entrar na base.}
{481}{}{Eles nem sequer ficaram no interior?}

# 26. YOU ALREADY SENT SOMEONE, DIDN'T YOU . . . (25)
{485}{}{Sim, o único sobrevivente disse ... pouco antes de sua morte infeliz ... disse que havia algum tipo de torres super-armas
 guardando a entrada. Eliminou a maioria de seus meninos.}
{486}{}{O que aconteceu com o sobrevivente?}
{487}{}{Hmmmm. I'll have to be careful then. Vou pegar o emprego.}
{488}{}{Esqueça isso. Ninguém disse que seria perigoso.}

# 27. WHAT HAPPENED TO THE ONLY SURVIVOR? (26)
{495}{}{Oh, ol 'Sam Pritchard? História triste. Tomei um bêbado uma noite, mencionou ao meu garoto Keith que ele achou essa "base", e antes de você
 Ele, ele me desenha um mapa e DIES. Ele está dormindo no Golgotha   agora.}
{496}{}{Seems like Reno's filled with sad stories these days. Vou pegar o emprego.}
{497}{}{Sabe, são histórias desse tipo que me fazem perceber que não posso aceitar esse trabalho. Mais tarde, Wright.}

# 28. REFUSE (21, 26, 27, 29)
{505}{}{(Bate sua cabeça.) Muito ruim. Você volta e me vê se mudar de idéia.}
{506}{}{Eu farei isso.}

# 29. CHANGE YER MIND ABOUT THE BASE? (WTG)
{515}{}{(Wright sorri quando ele vê você.) Você tropeça de idéia sobre essa proposição que eu tive?}
{516}{}{Qual foi essa proposição novamente?}
{517}{}{Não, apenas parando. Eu irei agora.}

# 30. AGREE CRACK OPEN BASE (24, 26, 27)
{525}{}{(Nods, sorrisos.) Tudo bem então. Volte quando você encontrou uma maneira, e eu vejo que você é bem recompensado. Agora, como para
 a localização da base ... siga para o norte, então ... (Dá-lhe as coordenadas para a base do exército).}
{526}{}{Tudo certo. Eu vou verificar isso. When I find a way inside, I'll be back.}

# 31. YOU FIND THAT ARMY BASE? (X)
{535}{}{Ah, é você. Você tem algumas boas notícias para mim? Você encontra um caminho para a base desse exército?}
{536}{}{Se você está de volta e não fez o que eu perguntei, então você está em um mundo de dor.}
{537}{}{Ainda não.}
{538}{}{Sim. Eu consegui entrar e encontrei muitas armas antigas e hardware militar lá. Está tudo lá para a tomada.
 Agora, sobre o meu pagamento ...}
{539}{}{Entrei na base, mas houve um ... acidente ... a base está contaminada.}
{540}{}{Desculpa. Eu retornarei uma vez que eu entro na base do exército.}
{541}{}{Aperte este trabalho e atinja você. Estou fora daqui.}

# 32. NOT YET. (31)
{550}{}{Se você não é feito o que eu perguntei, então o que no INFERNO você está fazendo de volta aqui ?! Preciso que você racha essa base, então não
 Volte aqui até que você tenha feito isso!}
{551}{}{Tudo certo. Eu retornarei uma vez que eu entro na base do exército.}

# 34. SORRY . . . (WARNING) (31)
{560}{}{Se você voltar aqui novamente e você não fez o que eu pedi, eu vou ver você pendurado no Gólgota, tribal. NINGUÉM desperdiça meu
 Tempo. Você me entende?}
{561}{}{Desculpa? DESCULPA?! Isso não o corta desta vez, tribal. Se você acha que pode desperdiçar meu tempo, você está enganado. eu posso conseguir
 alguém para preencher seus sapatos. (Gritos na porta.) Meninos! Entre aqui!}
{562}{}{Entendido. I'll be back when I've done the job.}

# 35. MADE MAN (31)
{575}{}{. Eu gosto disso, eu gosto disso. Tem estilo. Agora você pára pela Pata do gato e New Reno Arms, e eles vão cuidar
 você. Você precisa de folga livre, de frente na estação de trem, também. Eu vou configurar você.}
{576}{}{Thanks. Eu farei isso.}

# 37. REWARD/LOSS (SIERRA ARMY BASE) (31)
{580}{}{(Olhos brilham.) Você fez o bem,}
{581}{}{Um "acidente"? Ah, inferno, eu nem quero saber. Saia daqui e nunca volte.}
{582}{}{Obrigado, Sr. Wright. Se eu for um Homem Feito, então eu gostaria de ser chamado ...}
{583}{}{Tudo bem então.}

{584}{}{Então, o que você quer que nós liguemos para você?}

# 38. REP: MADE MAN INTRO (WTG)
{590}{}{(Sorria quando ele vê você.)}
{591}{}{Certo. Como estão as coisas com você, Sr. Wright?}
{592}{}{Certo. Eu estava apenas parando, Sr. Wright. Você se importa, senhor.}

# 39. HOW ARE THINGS WITH YOU, MR. WRIGHT? (38)
{600}{}{(Chuckles.) Nada mal, não é ruim. Minha esposa ainda está sendo um terror sagrado, mas isso não é novidade. As alegrias do casamento.}
{601}{}{Compreendo. Bem, eu estava apenas parando, Sr. Wright. Você se importa, senhor.}

# 40. MY WIFE JUST BUSTED UP ONE OF MY CELLS (38)
{610}{}{Bravo? Inferno, sim, minha maldita esposa acabou de ficar louca por um dos meus alambiques. Não sei como diabos ela descobriu, mas ...}
{611}{}{Bravo? Inferno, sim, algum sonuvabitch baixo destruiu um dos meus alambiques. Não sei como diabos ele conseguiu, mas ...}
{612}{}{Bravo? Inferno, sim, meus clientes estão caindo ... literalmente. Algo está errado com o álcool, e eu acho que está matando
 pessoas. Pergunto-me se o processo de fermentação é venenoso ...}
{613}{}{Ela provavelmente apenas tropeçou por isso. Suave sorte, sem dúvida! Não acho que ninguém tenha contado a ela, não. Muito improvável.}
{614}{}{Bem, essas máquinas antigas se quebram o tempo todo! Eu não acho que alguém fez isso de propósito. Muito improvável.}
{615}{}{Bem, certamente não poderia ter nada a ver com o veneno de radscorpion escorrendo nas cubas de um radscorpion cortado
 A cauda foi deixada cair lá. Eu não pensaria nisso.}

# 41. MY SON GOT A GUN FROM SOMEWHERE (38)
{620}{}{Engraçado você deve perguntar. Meu filho pegou uma arma de algum lado ... acho que é uma das outras famílias, tentando levá-lo a atirar
 ele mesmo ou seu velho. Quando pego o bastardo ...}
{621}{}{Uh, uma arma? Mesmo? Você está certo, senhor, provavelmente uma das outras famílias deu a ele. Seja difícil localizar quem
 fez isso, no entanto. Eu não pagaria nada.}

# 42. PROB NOTHING . . . (40, 41)
{625}{}{(Nods.) Provavelmente nada. Aw, bem ...}
{626}{}{Certo. Oh, bem, eu estava apenas parando, Sr. Wright. Você se importa, senhor.}

# 43. PUSHERS YOU SUSPECT? . . . (17)
{630}{}{(Frowns.) Como eu vejo, provavelmente foi um empurrador de Mordino ... essa maldita família controla quase todo o Jet em Reno.
 Eu conseguiria o Desperado, ver o que os negociantes passavam por aí.}

# 44. POISONED . . . (18)
{640}{}{Wh -? "Envenenado?" Em que nome do inferno você está falando?}
{641}{}{Eu inspecionei o corpo do seu filho. Jet não o matou ... seu corpo ainda tinha vestígios de veneno de radscorpion.}
{642}{}{Encontrei este jato de jato que Richard usou ... er, foi usado em Richard. Havia vestígios de veneno de radscorpion
 no cartucho.}
{643}{}{Eu encontrei uma jarra de jato que Richard usou ... er, foi usado em Richard. Havia vestígios de veneno de radscorpion
 no cartucho.}
{644}{}{Ele foi envenenado com veneno de radscorpion. A sobredosagem de jato foi apenas uma cobertura para o envenenamento.}

# 45. MY SON'S BODY . . . (44, 52)
{650}{}{"Inspecionou o corpo de meu filho?"}
{651}{}{Sim, tive que abrir o túmulo para fazer uma autópsia.}
{652}{}{Uh ... você sabe, NÃO FIZ. Eu perdi de mal. "O corpo do filho?" Eu quis dizer "alguém". Sim, foi o que eu quis dizer.}
{653}{}{Este pode não ser o melhor momento para discutir isso. Eu falarei com você mais tarde.}

# 46. SON'S BODY, DEAD . . . (45)
{660}{}{Você é maldito filho da puta ...}
{661}{}{Você é uma cadela malvada ...}
{662}{}{ Você acabou de ganhar SEU MISMO TERRA no Golgotha. Se encontrarem todas as peças. (Começa gritando.) Meninos! Entre aqui!
 E traga suas facas!}
{663}{}{Aguente! Não podemos falar sobre isso?}
{664}{}{Você vai precisar de mais do que facas para me derrubar ...}
{665}{}{Com licença. A saída e eu temos um compromisso.}

# 47. VENOM FOUND . . . (44)
{670}{}{Supondo que eu acredite nisso por um segundo ... e eu não estou dizendo que EU SOU ... então, quem ENVEJOU meu filho? E por que eles foram para o
 Problema de fazê-lo com Jet?}
{671}{}{Palavra é que era o Salvatores. Eles o bombearam com Jet atado com veneno de radscorpion, depois o deixou para você encontrar.}
{672}{}{Não sei qual dos Salvatores fez. Renesco arrumou alguns Jet para eles, sem saber que eles iriam usá-lo para
 envenene seu filho.}
{673}{}{Eu não sei.}

# 48. VENOM FOUND . . . (20, 47)
{680}{}{Agora, por que diabos eles fariam isso?}
{681}{}{Assim que eu vejo, os Mordinos controlam o Jet em Reno. Naturalmente, você culpava-os por uma overdose química ... e então haveria
 seja guerra. Se vocês dois não se dissiparam, você pelo menos ficará enfraquecido pela luta. Isso torna a vida mais fácil para o
 Salvatores ... tudo sobre o que eles precisam se preocupar é os Bispos.}
{682}{}{Eu não sei. Maybe you should ask them.}

# 49. SOLUTION . . . (48)
{690}{}{(Olha para você por um longo tempo, então uma risada seca escapa de seus lábios.) Você me responde e não posso fazer nada sobre
 isto. Os Salvatores ... maldição. (Respira profundamente.)}
{691}{}{O que está errado?}
{692}{}{"Você não pode fazer nada sobre isso?" O que você quer dizer?}

# 50. PROBLEM . . . (49)
{700}{}{Saiba o que os bastardos de Salvatore estão com ARMADO, amigo? Aqueles damned lightbringers. ONE Salvatore embala esse tipo
 de calor pode matar toda a minha família sem olhar. Para vencer isso, eu precisaria ...}
{701}{}{O que?}
{702}{}{Não se preocupe com isso, já chutei as canelas de debaixo dos Salvatores.}

# 51. SALVATORES . . . (50)
{710}{}{Ha! Os que estão em Reno talvez, mas você tem muito a aprender sobre as famílias ... ainda há Salvatores chutando
 ao redor de Reno, e mesmo que haja apenas um, isso é problema. Para vencê-los, eu precisaria ...}

# 52. I DON'T KNOW . . . (47)
{720}{}{(Frown aprofunda.) Isso cheira como uma pilha de merda de brahmin para mim ...}
{721}{}{Não acredite em mim? Olhe, eu inspecionei o corpo do seu filho, e REEKED do veneno de radscorpion.}
{722}{}{Olhe, confie em mim ... seu filho estava ENVENENADO. Eu não sei por quem, mas alguém se esforçou para fazer parecer um
 Sobredosagem de jato.}

{750}{}{Você resolveu o assassinato.}
{775}{}{Você tocou um suspeito na morte de Richard Wright.}
{800}{}{Você identificou corretamente quem matou Richard Wright e o motivo.}
{825}{}{Você se tornou um homem feito da família Wright.}

# END LINES
{5243}{}{!}
{5249}{}{. Estou interessado em um emprego.}
{5261}{}{!}
{5310}{}{"Fico feliz que você parou, muito bem vizinho de você. (Sneer desmorona em uma careta). Procurando trabalho na família Wright, hein?}
{5467}{}{ crack base.}
{6467}{}{ esmagar!}
{5580}{}{. Vá para o Cat's Paw e New Reno Arms ... Diga-lhes que você é de mim, e eles vão te preparar. Você é família agora ... uma feita
 homem, e tudo o que Reno vai saber.}
{5590}{}{... todos estão te tratando bem? Não tem problemas?}
