# 0. QUICK LOOK (ANY)
{100}{}{Você vê um dos habitantes da cidade de Reno.}

# 1. LOOK, MALE (WTG)
{150}{}{Você vê um homem de aparência irregular. Ele parece entediado.}
{151}{}{Você vê um homem de aparência irregular. Ele tem um olhar maçante no olho.}
{152}{}{Você vê um homem de aparência irregular. Parece que está cuidando de ressaca.}
{153}{}{Você vê um homem de aparência irregular. Ele parece um pouco embriagado.}
{154}{}{Você vê um homem de aparência irregular. Ele dá um olhar irritado, então ignora você.}
{155}{}{Você vê um homem de aparência irregular. Ele parece chateado.}

# 2. LOOK, FEMALE (WTG)
{160}{}{Você vê uma mulher de aparência irregular. Ela parece entediado.}
{161}{}{Você vê uma mulher de aparência irregular. Ela tem um olhar maçante no olho dela.}
{162}{}{Você vê uma mulher de aparência irregular. Ela está olhando a mil milhas de distância.}
{163}{}{Você vê uma mulher de aparência irregular. Ela parece um pouco bêbada.}
{164}{}{Você vê uma mulher de aparência irregular. Ela lhe dá um olhar irritado, então ignora você.}
{165}{}{Você vê uma mulher de aparência irregular. Quando ela chama a atenção, ela zombou.}

# 3. FLOAT (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{200}{}{:: Claps ::}
{201}{}{::Felicidades::}
{202}{}{Maneira de queimar os bastardos do Enclave! Maneira de ir!}
{203}{}{Maneira de esmagar o Enclave,}
{204}{}{Parabéns em pisar o Enclave,}
{205}{}{Parabéns em pisar o Enclave,}

# 4. FLOAT (ANY) TO [POWER ARMOR] (WTG)
{215}{}{Uh-oh. Saia do caminho.}
{216}{}{Apenas olhando para ele ... ela ... é ... O QUE É isso é me dá arrepios.}
{217}{}{Acha que essa coisa está procurando alguém?}
{218}{}{É a fúria do inferno dada carne. Uh, embaixo da armadura, isso é.}
{219}{}{Fique longe do caminho dessa coisa.}
{220}{}{Fale sobre perigoso ...}
{221}{}{*Gole*}
{222}{}{Eu acho que o Sr. Roboto cara estava me digitalizando.}
{223}{}{Eu acho que o tanque caminhando só me deu o olhar da morte. Estou fora daqui.}
{224}{}{Ouvi dizer que essa coisa deixou três assassinos apenas ontem.}

# 5. FLOAT AND CLICK (FEMALE) TO [MALE, PORN STAR] (WTG)
{240}{}{Bem, hellloooo stud.}
{241}{}{Um garanhão como você na necessidade de uma sela? Estou à vontade amanhã à noite.}
{242}{}{O que você faz depois, marinheiro?}
{243}{}{Posso sentir seus músculos?}
{244}{}{Por que você não desmaia quando você fica ereto?}
{245}{}{Quer ir ao meu lugar para tomar uma bebida?}
{246}{}{Quero comer o jantar no peito.}
{247}{}{Precisa de um parceiro para o seu próximo filme?}
{248}{}{:: Olha no seu bíceps. ::}
{249}{}{:: Claps, whistles ::}

# 6. FLOAT (MALE) TO [FEMALE, PORN STAR] (WTG)
{255}{}{Uau. Dê uma olhada.}
{256}{}{Você olharia para isso?}
{257}{}{:: Boca a palavra 'maldita'. ::}
{258}{}{Eu sabia que deveria ter me rasurado hoje.}
{259}{}{Venha conversar comigo por um segundo, melharucos.}
{260}{}{Tribais pegou-lhes tits! Droga!}
{261}{}{Confira a prateleira na tribal.}
{262}{}{Que existe a principal galinha do meu rebanho.}
{263}{}{Eu me banharia por aquela mulher.}
{264}{}{Eu tenho sua mãe lode aqui.}
{265}{}{Agite-o!}
{266}{}{Trabalhe!}
{267}{}{:: Whistles ::}
{268}{}{As pernas vão todo o caminho?}
{269}{}{Ei, linda, você tem uma língua para ir com essa bunda?}
{270}{}{Você tem batatas fritas para ir com aquela vibração, linda?}
{271}{}{Talvez ela dance hoje à noite.}
{272}{}{Você viu seu último filme? Vermelho quente, homem, vermelho QUENTE.}
{273}{}{Com licença. Eu tenho que ir ao banheiro e er, pentear meu cabelo por um segundo.}
{274}{}{Gostaria de ser sua calcinha.}
{275}{}{Eu gostaria de ser sua cueca.}
{276}{}{Eu gostaria de cheirar seus shorts.}
{277}{}{Essa é uma senhora foxy.}
{278}{}{Droga. Todos eles curvas e eu sem freios.}
{279}{}{Confira esses bazoongas!}
{280}{}{Confira essas begônias!}
{281}{}{Quero ver melhor esses grandes olhos castanhos.}
{282}{}{Daaaaamn.}
{283}{}{Verifique esses faróis.}
{284}{}{Aposto que ela tem problemas de volta.}

# 7. FLOAT AND CLICK (ANY) TO [MALE, PRIZEFIGHTER] (WTG)
{285}{}{Você não parece tão difícil, Sr. Prizefighter.}
{286}{}{Recebi 20 fichas montando sobre você!}
{287}{}{Ei, campeão! A última luta foi ótima!}
{288}{}{Viu você lutar no ringue. Droga, bom gancho, você joga.}
{289}{}{Você vai pegar o outono? Tenho 30 fichas montadas em você.}
{290}{}{Quanto você bancou?}
{291}{}{Onde você trabalha fora?}
{292}{}{Cuidado com o Masticador. Ele tem gosto de ouvidos.}
{293}{}{Eu pegaria uma bebida se eu não tivesse jogado todo meu dinheiro apostando em seu oponente.}
{294}{}{Você não parece tão difícil, Ms. Left Hook.}
{295}{}{Posso ver seus músculos abdominais flexionar?}

# 8. FLOAT (ANY) TO [MADE MAN] (WTG)
{300}{}{Fique longe do caminho desse homem.}
{301}{}{Eu acho que ele estava olhando para mim.}
{302}{}{Eu acho que ele apenas me deu o olhar da morte. Estou fora daqui.}
{303}{}{Ouvi dizer que derrubou três assassinos ontem.}
{304}{}{Apenas olhar para ele me dá arrepios.}
{305}{}{Pensa que ele está procurando cap para alguém?}
{306}{}{Uh-oh. Saia do caminho.}
{307}{}{É a fúria do inferno dada carne.}
{308}{}{Fale sobre perigoso ...}
{309}{}{*Gole*}
{310}{}{La Femme Nikita, depois alguns.}
{311}{}{Apenas olhar para ela me dá arrepios.}
{312}{}{Pensa que ela está procurando cap para alguém?}
{313}{}{Eu acho que ela estava olhando para mim.}
{314}{}{Eu acho que ela apenas me deu o olhar da morte. Estou fora daqui.}
{315}{}{Ouvi dizer que derrubou três assassinos ontem.}
{316}{}{Que burro! Uh, burro ruim, isso é.}

# 9. FLOAT (ANY) TO [SLAVER] (WTG)
{320}{}{O que há com todos os escravos por aqui recentemente?}
{321}{}{Não vi esse escravidão por aqui antes ...}
{322}{}{Eu me pergunto se o escravo se dirigiu para os estábulos ...}
{323}{}{Gostaria de saber se aquele escravo obteve algum estoque ...}
{324}{}{Você dirigiu-se aos estábulos, escravas?}
{325}{}{Outra escravidão. Mordino deve ter descoberto uma mina de ouro em algum lugar ...}
{326}{}{Slaver está com destino ao Gólgota.}
{327}{}{Esse fedor do Gólgota foi horrível na noite passada ...}
{328}{}{Friggin 'slavers ...}
{329}{}{De toda a sorte podre ...}
{330}{}{Ouvi dizer que eles receberam uma nova cultura de escravos.}
{331}{}{Nova safra de escravos no mercado.}
{332}{}{Conjunção, junção.}
{333}{}{Estou fazendo o banco.}
{334}{}{Às vezes, muito para beber não é suficiente.}
{335}{}{Malditas cruzadas nos casinos ...}
{336}{}{Ótimo, outro rolo baixo.}
{337}{}{House estava contra mim.}
{338}{}{Fortune contra mim.}
{339}{}{Gostou de colocar aquele cara na prateleira ...}
{340}{}{Stinkard sujo ...}
{341}{}{Eslavos andando como se fossem o lugar ...}
{342}{}{A casa está comigo.}
{343}{}{Má sorte, vento doente, não bons tempos, não bons tempos ...}
{344}{}{O aquecimento de Reno, o tempo em que se move.}
{345}{}{Essa filha do bispo está fora de controle.}
{346}{}{Se a União de Temperança me ensinar uma vez mais ...}
{347}{}{Saw Tully desmaiou novamente na calha.}
{348}{}{Damn Den gutter trash.}
{349}{}{Eu tenho que sair desta cidade.}
{350}{}{Viu outro O.D. esta manhã. Voa por toda a sua boca. E ele estava SORRINDO.}
{351}{}{Tentou sair, mas ...}
{352}{}{Slaver melhor vê-lo nesta cidade ...}
{353}{}{Eu odeio essa cidade maldita.}
{354}{}{Eu já estive nesta cidade por muito tempo.}
{355}{}{Esta cidade é excelente ... exceto para os turistas.}
{356}{}{A cidade é ótima ... exceto para os escravos.}
{357}{}{A cidade é ótima ... exceto pelos proxenetas e putas.}

# 10. FLOAT AND CLICK (ANY) TO [COMPANION: ROBOBRAIN] (WTG)
{365}{}{Isso é algum tipo de máquina caça-níqueis que o está seguindo?}
{366}{}{Isso é uma máquina robo-slot?}
{367}{}{Seu robô faz truques? Uh ... truques de mágica, quero dizer.}

# 11. FLOAT (ANY) TO [COMPANION: MARCUS] (WTG)
{375}{}{Diga-me que não é um mutante.}
{376}{}{Que um mutante?}
{377}{}{Merda sagrada. Mutantes em New Reno. Deve significar problemas.}
{378}{}{Esse mutante é um grande mutha.}
{379}{}{Filthy mutant-lover ...}

# 12. FLOAT (ANY) TO [COMPANION: BONE-NOSE] OR MALE TOWNSPERSON REACTION TO [COMPANION = FEMALE SPOUSE] (WTG)
{385}{}{Seu amigo tem um osso no nariz.}
{386}{}{Todo mundo em sua pequena banda cola um osso no nariz para provar a si mesmo?}
{387}{}{Esse cara com você da tribo 'stick-a-bone-up-my-honker'?}
{388}{}{Esse cara com o osso no nariz é prova de que as tribos nunca mais serão civilizadas.}
{389}{}{Esse cara pegou um osso no nariz?}
{390}{}{Esse cara tem um osso no nariz do tamanho do meu braço. Keeee-rist.}
{391}{}{Eu nem quero saber como esse amigo seu obteve esse osso no nariz dele.}
{392}{}{Ótimo. É um daqueles criminosos tribais.}
{393}{}{Quantos tribals irão chegar a esta cidade?}
{394}{}{Outro primata.}
{395}{}{O destino do menino para o Gólgota.}
{396}{}{Esse fedor do Gólgota foi horrível na noite passada ...}
{397}{}{Turistas de Friggin.}
{398}{}{De toda a sorte podre ...}
{399}{}{Ouvi dizer que eles receberam uma nova cultura de escravos.}
{400}{}{Conjunção, junção.}
{401}{}{Estou fazendo o banco.}
{402}{}{Às vezes, muito para beber não é suficiente.}
{403}{}{Malditas cruzadas nos casinos ...}
{404}{}{House estava contra mim.}
{405}{}{Fortune contra mim.}
{406}{}{Gostou de colocar aquele cara na prateleira ...}
{407}{}{Stinkard sujo ...}
{408}{}{A casa está comigo.}
{409}{}{Má sorte, vento doente, não bons tempos, não bons tempos ...}
{410}{}{O aquecimento de Reno, o tempo em que se move.}
{411}{}{Essa filha do bispo está fora de controle.}
{412}{}{Se a União de Temperança me ensinar uma vez mais ...}
{413}{}{Saw Tully desmaiou novamente na calha.}
{414}{}{Maldita ferner.}
{415}{}{Aquele não é por aqui.}
{416}{}{Eu tenho que sair desta cidade.}
{417}{}{Viu outro O.D. esta manhã. Voa por toda a sua boca. E ele estava SORRINDO.}
{418}{}{Tentou sair, mas ...}
{419}{}{Por que correr o risco de saltar uma reivindicação assim?}
{420}{}{Eu odeio essa cidade maldita.}
{421}{}{Eu já estive nesta cidade por muito tempo.}
{422}{}{Esta cidade é excelente ... exceto para os turistas.}
{423}{}{A cidade é ótima ... exceto para os escravos.}
{424}{}{A cidade é ótima ... exceto pelos proxenetas e putas.}
{425}{}{Você vende essa mulher para você?}
{426}{}{Quanto para aquela mulher que você conseguiu com você?}
{427}{}{A mulher que você conseguiu com você é bonita.}
{428}{}{Essa mulher pode cozinhar? Se assim for, vou levá-la.}
{429}{}{Quanto para aquela saia que você recebeu com você?}
{430}{}{Confira o novo chefe da caminhada.}
{431}{}{Vou fazer alguma ação esta noite!}
{432}{}{A Sra. Bishop shore conseguiu uma bunda doce.}

# 13. FLOAT [NO REP] (WTG)
{450}{}{A margem da Sra. Bishop teve uma bunda doce.}
{451}{}{Se a União de Temperança me ensinar uma vez mais ...}
{452}{}{Ótimo. É um daqueles criminosos tribais.}
{453}{}{Quantos tribals irão chegar a esta cidade?}
{454}{}{Outro primata.}
{455}{}{Tribal está destinado ao Golgotha.}
{456}{}{Esse fedor do Gólgota foi horrível na noite passada ...}
{457}{}{Não consegue encontrar sua bunda em uma tempestade de areia ...}
{458}{}{Turistas de Friggin.}
{459}{}{De toda a sorte podre ...}
{460}{}{Ouvi dizer que eles receberam uma nova cultura de escravos.}
{461}{}{Conjunção, junção.}
{462}{}{Estou fazendo o banco.}
{463}{}{Às vezes, muito para beber não é suficiente.}
{464}{}{Malditas cruzadas nos casinos ...}
{465}{}{Ótimo, outro rolo baixo.}
{466}{}{House estava contra mim.}
{467}{}{Fortune contra mim.}
{468}{}{Gostou de colocar aquele cara na prateleira ...}
{469}{}{Stinkard sujo ...}
{470}{}{A casa está comigo.}
{471}{}{Má sorte, vento doente, não bons tempos, não bons tempos ...}
{472}{}{O aquecimento de Reno, o tempo em que se move.}
{473}{}{Essa filha do bispo está fora de controle.}
{474}{}{Saw Tully desmaiou novamente na calha.}
{475}{}{Maldita ferner.}
{476}{}{Aquele não é por aqui.}
{477}{}{Eu tenho que sair desta cidade.}
{478}{}{Viu outro O.D. esta manhã. Voa por toda a sua boca. E ele estava SORRINDO.}
{479}{}{Tentou sair, mas ...}
{480}{}{Por que correr o risco de saltar uma reivindicação assim?}
{481}{}{Eu odeio essa cidade maldita.}
{482}{}{Eu já estive nesta cidade por muito tempo.}
{483}{}{Esta cidade é excelente ... exceto para os turistas.}
{484}{}{A cidade é ótima ... exceto para os escravos.}
{485}{}{A cidade é ótima ... exceto pelos proxenetas e putas.}
{486}{}{Poderia ir para o centro, veja se novos homens estão na cidade ...}
{487}{}{Se a União de Temperança me ensinar uma vez mais ...}

# 14. CLICK (ANY) TO [FLAG: ENCLAVE DESTROYED] (WTG)
{490}{}{Maneira de queimar os bastardos do Enclave! Maneira de ir!}
{491}{}{Eu sempre soube que o presidente queria matar todos nós.}
{492}{}{O presidente estava vivo? Quando foi a última eleição?}
{493}{}{Maneira de esmagar o Enclave,}
{494}{}{O Enclave nunca mexeu comigo, mas estou feliz por terem ido embora.}
{495}{}{Não posso acreditar que o Enclave ainda estava lutando contra a guerra depois de todo esse tempo. Idiotas.}
{496}{}{Senti um grande distúrbio ... como se uma centena de bastardos malignos em uma torre de petróleo gritasse de terror e de repente fosse silenciado. Estranho.}
{497}{}{Parabéns em pisar o Enclave,}
{498}{}{Este jogo foi trazido a você pela letra Z.}
{499}{}{Nós sentimos falta de Tim Cain. Ele costumava cozinhar pão maravilhoso. Então ele nos espancaria como crianças pequenas.}
{500}{}{Sim, sim, eu também sou o Avatar.}
{501}{}{O novo Reno foi desenhado por Chris Avellone e Tom French. O rumor é que eles se casarão em breve.}
{502}{}{Feargus ficou com um olhar franzido em seu rosto quando viu quantas mensagens de texto flutuantes eu tenho.}
{503}{}{Você pontua é 192 de 208. Você realmente deveria ter usado o dedo mordido no Horrigan.}

# 15. CLICK (ANY) TO [POWER ARMOR) (WTG)
{510}{}{Você está procurando seu irmão Robby? Você sabe, o Robot? Ah, nunca perca.}
{511}{}{Desculpe, estava no seu caminho? Vou sair da cidade.}
{512}{}{Desculpe, estava respirando o seu ar? Eu irei parar.}
{513}{}{:: Knocks on armor :: Alguém lá dentro?}
{514}{}{"Perigo, Will Robinson! Perigo, Will Robinson! ' Heh heh. Uh ... apenas uma piada.}
{515}{}{Armadura de Niiiiice. Tem ar condicionado?}
{516}{}{Você não fica quente lá?}
{517}{}{Perder seu coração, homem de lata?}
{518}{}{Uh, olá, senhor ... senhora ... o que quer que você seja.}
{519}{}{Qualquer coisa errada, senhor ... senhora ... uh, seja lá o que for?}
{520}{}{Você é algum tipo de novo jogo de arcade a pé?}
{521}{}{Você é um desses novos sistemas de console que estão saindo?}
{522}{}{Não, não vou deixar as articulações.}
{523}{}{Parece que você estava a caminho de um daqueles jogos de PC de batalha e se perdeu.}
{524}{}{Sim, sim, "clank-whirrr-clank" para você, também.}
{525}{}{Se você acha que a armadura me intimida, você está certa.}

# 16. CLICK (MALE) TO [FEMALE, PORN STAR] (WTG)
{540}{}{Você está vendendo?}
{541}{}{Posso comprar suas roupas? Quero dizer, agora mesmo?}
{542}{}{Eu sabia que deveria ter me rasurado hoje.}
{543}{}{Venha conversar comigo por um segundo, querida.}
{544}{}{Vamos, lábios de mel ... caminhe comigo.}
{545}{}{Nimble little minx, aincha?}
{546}{}{Eu me banharia por você.}
{547}{}{Eu tenho sua mãe lode aqui.}
{548}{}{As pernas vão todo o caminho?}
{549}{}{Você vai dançar esta noite?}
{550}{}{Com licença. Eu tenho que ir ao banheiro e er, pentear meu cabelo por um segundo.}
{551}{}{Gostaria de ser sua cueca.}
{552}{}{Gostaria de cheirar seus calções.}
{553}{}{Você é uma senhora foxy.}
{554}{}{Me aperte se eu estiver errado, querida, mas você não quer me beijar?}
{555}{}{Droga. Todos eles curvas e eu sem freios.}
{556}{}{Saiba o que parece ser bom com você? Eu.}
{557}{}{Sua calcinha pode não ser a melhor coisa na terra, mas eles estão muito perto disso.}
{558}{}{Bazoongas agradáveis!}
{559}{}{Bons begônias!}
{560}{}{Os seus faróis vão me cegar.}
{561}{}{Tens problemas de volta?}

# 17. CLICK (ANY) TO [MALE, MADE MAN) (WTG)
{580}{}{Olá senhor. Como você está?}
{581}{}{Qualquer coisa errada, senhor?}
{582}{}{Desculpe, estava no seu caminho? Vou sair da cidade.}
{583}{}{Desculpe, estava respirando o seu ar? Eu irei parar.}
{584}{}{Dê meus cumprimentos ao seu chefe.}
{585}{}{Olhe, por favor ... Eu não quero nenhum problema.}
{586}{}{Olá Madame. Como você está?}
{587}{}{Algo errado, senhora?}

# 18. CLICK (ANY) TO [SLAVER] (WTG)
{600}{}{O que há com todos os escravos por aqui recentemente?}
{601}{}{Eu não vi você por aqui antes ...}
{602}{}{Se você quiser vender escravos, experimente os Mordinos.}
{603}{}{Você dirigiu-se para os estábulos? Eles mantêm a maioria dos escravos lá.}
{604}{}{Mostre-me o seu estoque.}
{605}{}{Se você está procurando vender escravos, verifique com os Mordinos.}
{606}{}{Eu odeio essa cidade maldita.}
{607}{}{Eu já estive nesta cidade por muito tempo.}
{608}{}{Esta cidade é excelente ... exceto para os turistas.}
{609}{}{A cidade é ótima ... exceto para os escravos.}
{610}{}{A cidade é ótima ... exceto pelos proxenetas e putas.}
{611}{}{Há testes químicos feitos em escravos ao norte de New Reno, eu ouço.}
{612}{}{Gólgota ao sul de Reno, no deserto.}
{613}{}{Eu posso ser pobre, mas não em espírito.}
{614}{}{Eu não sou pobre, eu apenas tenho sorte podre.}
{615}{}{Esse fedor do Gólgota foi horrível na noite passada ...}
{616}{}{Droga! Veja, eu estava com 53 fichas, então ...}
{617}{}{É melhor ter cuidado com essas partes, ou você estará ligado ao Golgotha.}
{618}{}{O novo Reno não seria um lugar ruim para todos os turistas de friggin.}
{619}{}{Conjunção, junção.}
{620}{}{Estou fazendo o banco.}
{621}{}{Às vezes, muito para beber não é suficiente.}
{622}{}{Malditas cruzadas nos casinos ...}
{623}{}{Um rolo baixo é alguém que vem para a cidade e aposta apenas um chip ou dois nas mesas.}
{624}{}{House estava contra mim.}
{625}{}{Fortune contra mim.}
{626}{}{Gostou de colocar aquele cara na prateleira ...}
{627}{}{Stinkard sujo ...}
{628}{}{O que você quer?}
{629}{}{Má sorte, vento doente, não bons tempos, não bons tempos ...}
{630}{}{O aquecimento de Reno, o tempo em que se move.}
{631}{}{Essa filha do bispo está fora de controle.}
{632}{}{Se a União de Temperança me ensinar uma vez mais ...}
{633}{}{Saw Tully desmaiou novamente na calha.}
{634}{}{Eu tenho que sair desta cidade.}
{635}{}{Viu outro O.D. esta manhã. Voa por toda a sua boca. E ele estava SORRINDO.}
{636}{}{Tentou sair, mas ...}
{637}{}{Pare de me incomodar.}
{638}{}{Olha, não tenho tempo para falar com você agora.}

# 19. CLICK (ANY) TO [COMPANION: BONE-NOSE] OR MALE TOWNSPERSON TO (COMPANION: SPOUSE = FEMALE) (WTG)
{650}{}{Seu amigo tem um osso no nariz.}
{651}{}{Todo mundo em sua pequena banda cola um osso no nariz para provar a si mesmo?}
{652}{}{Esse cara com você da tribo 'stick-a-bone-up-my-honker'?}
{653}{}{Esse cara com o osso no nariz é prova de que as tribos nunca mais serão civilizadas.}
{654}{}{Esse cara pegou um osso no nariz?}
{655}{}{Esse cara tem um osso no nariz do tamanho do meu braço. Keeee-rist.}
{656}{}{Eu nem quero saber como esse amigo seu obteve esse osso no nariz dele.}
{657}{}{Eu odeio essa cidade maldita.}
{658}{}{Eu já estive nesta cidade por muito tempo.}
{659}{}{Esta cidade é excelente ... exceto para os turistas.}
{660}{}{A cidade é ótima ... exceto para os escravos.}
{661}{}{A cidade é ótima ... exceto pelos proxenetas e putas.}
{662}{}{Há testes químicos feitos em escravos ao norte de New Reno, eu ouço.}
{663}{}{Gólgota ao sul de Reno, no deserto.}
{664}{}{Eu posso ser pobre, mas não em espírito.}
{665}{}{Eu não sou pobre, eu apenas tenho sorte podre.}
{666}{}{Esse fedor do Gólgota foi horrível na noite passada ...}
{667}{}{Droga! Veja, eu estava com 53 fichas, então ...}
{668}{}{É melhor ter cuidado com essas partes, ou você estará ligado ao Golgotha.}
{669}{}{O novo Reno não seria um lugar ruim para todos os turistas de friggin.}
{670}{}{Conjunção, junção.}
{671}{}{Estou fazendo o banco.}
{672}{}{Às vezes, muito para beber não é suficiente.}
{673}{}{Malditas cruzadas nos casinos ...}
{674}{}{Um rolo baixo é alguém que vem para a cidade e aposta apenas um chip ou dois nas mesas.}
{675}{}{House estava contra mim.}
{676}{}{Fortune contra mim.}
{677}{}{Gostou de colocar aquele cara na prateleira ...}
{678}{}{Stinkard sujo ...}
{679}{}{O que você quer?}
{680}{}{Má sorte, vento doente, não bons tempos, não bons tempos ...}
{681}{}{O aquecimento de Reno, o tempo em que se move.}
{682}{}{Essa filha do bispo está fora de controle.}
{683}{}{Se a União de Temperança me ensinar uma vez mais ...}
{684}{}{Saw Tully desmaiou novamente na calha.}
{685}{}{Eu tenho que sair desta cidade.}
{686}{}{Viu outro O.D. esta manhã. Voa por toda a sua boca. E ele estava SORRINDO.}
{687}{}{Tentou sair, mas ...}
{688}{}{Pare de me incomodar.}
{689}{}{Olha, não tenho tempo para falar com você agora.}
{690}{}{Ela é sua "esposa", hein? Posso pedir emprestado uma hora ou duas?}
{691}{}{Quer trocar esposas por um tempo?}
{692}{}{Você vende essa mulher para você?}
{693}{}{Quanto para aquela mulher que você conseguiu com você?}
{694}{}{A mulher que você conseguiu com você é bonita.}
{695}{}{Essa mulher pode cozinhar? Se assim for, vou levá-la.}
{696}{}{Quanto para aquela saia que você recebeu com você?}
{697}{}{A Sra. Bishop shore conseguiu uma bunda doce.}

# 20. CLICK (ANY) TO [NO REP] (WTG)
{700}{}{Vou fazer alguma ação esta noite!}
{701}{}{Encontre uma prostituta, faça um pouco de jogo.}
{702}{}{A Sra. Bishop shore conseguiu uma bunda doce.}
{703}{}{Há testes químicos feitos em escravos ao norte de New Reno, eu ouço.}
{704}{}{Gólgota ao sul de Reno, no deserto.}
{705}{}{Eu posso ser pobre, mas não em espírito.}
{706}{}{Eu não sou pobre, eu apenas tenho sorte podre.}
{707}{}{Quantos tribals irão chegar a esta cidade?}
{708}{}{Diga ao resto da sua tribo que fique em casa.}
{709}{}{Outro primado? Vocês tribais se criam como mantis.}
{710}{}{Esse fedor do Gólgota foi horrível na noite passada ...}
{711}{}{Droga! Veja, eu estava com 53 fichas, então ...}
{712}{}{É melhor ter cuidado com essas partes, ou você estará ligado ao Golgotha.}
{713}{}{O novo Reno não seria um lugar ruim para todos os turistas de friggin.}
{714}{}{Ouvi dizer que eles receberam uma nova cultura de escravos.}
{715}{}{Nova safra de escravos no mercado.}
{716}{}{Conjunção, junção.}
{717}{}{Estou fazendo o banco.}
{718}{}{Às vezes, muito para beber não é suficiente.}
{719}{}{Malditas cruzadas nos casinos ...}
{720}{}{Um rolo baixo é alguém que vem para a cidade e aposta apenas um chip ou dois nas mesas.}
{721}{}{House estava contra mim.}
{722}{}{Fortune contra mim.}
{723}{}{Gostou de colocar aquele cara na prateleira ...}
{724}{}{Stinkard sujo ...}
{725}{}{O que você quer?}
{726}{}{Má sorte, vento doente, não bons tempos, não bons tempos ...}
{727}{}{O aquecimento de Reno, o tempo em que se move.}
{728}{}{Essa filha do bispo está fora de controle.}
{729}{}{Se a União de Temperança me ensinar uma vez mais ...}
{730}{}{Saw Tully desmaiou novamente na calha.}
{731}{}{Eu tenho que sair desta cidade.}
{732}{}{Viu outro O.D. esta manhã. Voa por toda a sua boca. E ele estava SORRINDO.}
{733}{}{Tentou sair, mas ...}
{734}{}{Pare de me incomodar.}
{735}{}{Olha, não tenho tempo para falar com você agora.}
{736}{}{Poderia ir para o centro, veja se novos homens estão na cidade ...}
{737}{}{Felizmente, eles colocaram esse asshole no rack ...}

# endlines
{1203}{}{!}
{1204}{}{! Você chuta a bunda! Você chuta ASS!}
{1205}{}{! Você é tão DINHEIRO!}
{1493}{}{!}
{1497}{}{! Você chuta a bunda! Você chuta ASS!}
