# quick look
{100}{}{Você vê um proxeneta.}

# examine
{150}{}{Você vê um homem bem vestido. Suas roupas pegam a luz e refletem isso, quase te cegando.}
{151}{}{Você vê um homem com roupas tão alto que deve ter um botão de volume.}
{152}{}{Você vê um proxeneta. He's styling.}
{153}{}{Você vê um proxeneta. He nods at you.}
{154}{}{Você vê um proxeneta. He looks fly enough to be pimp of the year.}
{155}{}{Você vê um proxeneta. His clothes are so loud they need a volume knob.}

# 1. ENCLAVE DESTROYED (MALE)
{200}{}{Cara, ouvi voce destruir o Enclave. Talvez AGORA você quer se deitar?}
{201}{}{O homem destrói o Enclave, acha que ele é dono do mundo ... sheee-it.}
{202}{}{Eu, cara! A única coisa melhor do que soprar uma plataforma de petróleo é ter
 Alguém soprando sua plataforma, sabe o que estou dizendo?}

# 2. ENCLAVE DESTROYED (FEMALE)
{220}{}{Ouvi dizer que você destruiu o Enclave, mulher. Talvez AGORA você venha trabalhar para mim?}
{221}{}{A mulher destrói o Enclave, acha que ela possui o mundo ... sheee-it.}
{222}{}{Uma mulher atraente que Enclave-busting como você poderia ganhar um LOTTA chips nesta cidade ...}

# 3. (MALE PORN STAR)
{230}{}{Mulher melhor tem meu dinheiro ...}
{231}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{232}{}{Bitch melhor não está me segurando ...}
{233}{}{Continue então. Continue.}
{234}{}{Você está procurando alguma ação?}
{235}{}{Por que você não entende uma das minhas senhoras para você, irmão?}
{236}{}{Você quer um parceiro real, experimente uma das minhas mulheres para você.}
{237}{}{Você precisa de fluffers? Eu os peguei.}
{238}{}{Estes não são escravos, são profissionais, escutam o que estou dizendo?}
{239}{}{Quando você me configurará no biz, filme erroneo staaar?}
{240}{}{Me dê algum tempo na câmera, vou te mostrar estrela.}
{241}{}{Eu posso fazer O QUE você faz, faça o que você faz e faça-a MELHOR do que você.}
{242}{}{Você deve me deixar ensinar algumas dicas, irmão.}
{243}{}{Eu tenho essa mulher que você deveria experimentar para filmes; ela tem esse bico de frutas suculentas e suaves.}
{244}{}{Deixe-me configurá-lo, cara. Eu era proxeneta do ano dois anos consecutivos.}
{245}{}{Não entendo como VOCÊ tem que ser uma estrela ...}

# 4. (PORN STAR FEMALE)
{260}{}{Mulher melhor tem meu dinheiro ...}
{261}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{262}{}{Bitch melhor não está me segurando ...}
{263}{}{Continue então. Continue.}
{264}{}{Confira aquele bico suculento de frutas suculentas.}
{265}{}{Baby, venha, deixe-me espremer essa suculenta suculenta fruta e seu.}
{266}{}{:: Whistles ::}
{267}{}{:: Boca a palavra 'maldita'. ::}
{268}{}{Você dança nos casinos em breve, doçura?}
{269}{}{Você quer um parceiro real, você deve me tentar, querida.}
{270}{}{Quando você me configurará no biz, perca o filme staaar?}
{271}{}{Deixe-me fazer você na câmera, eu vou te mostrar estrela.}
{272}{}{Eu posso fazer você melhor do que já foi feito.}
{273}{}{Você deveria me deixar ensinar-lhe alguns truques, mulher.}
{274}{}{Porra, um corpo como esse deveria ser legal.}
{275}{}{Mulher, é uma maravilha que a rua não derreta sob suas pernas o seu.}
{276}{}{Venha trabalhar para mim, mulher. Eu era proxeneta do ano dois anos consecutivos.}
{277}{}{Bebê, deixe-me espremer essa suculenta e suculenta fruta.}
{278}{}{Daaaamn.}

# 5. (MALE, MADE MAN)
{290}{}{Mulher melhor tem meu dinheiro ...}
{291}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{292}{}{Bitch melhor não está me segurando ...}
{293}{}{Você está procurando alguma ação?}
{294}{}{Você está procurando alguma ação? Eu lhe dou um brinde, irmão.}
{295}{}{Deixe-me estender uma cortesia para você, amigo. Eu dou uma de minhas mulheres por uma noite inteira.}
{296}{}{Fale comigo, amigo. Eu tenho uma mulher para você.}
{297}{}{A sua família precisa de um homem como eu para manter as mulheres na fila ...}
{298}{}{Você estilo, cara, você estilo.}
{299}{}{Filmes agradáveis, boy-eee.}
{300}{}{Diga a palavra e 'Eu vou estar olhando você de volta, irmão.}
{301}{}{Eu tenho suas costas, irmão.}
{302}{}{Você, o homem principal, sabe o que estou dizendo agora?}
{303}{}{Deixe-me configurá-lo, cara. Eu era proxeneta do ano dois anos consecutivos.}
{304}{}{Gangster Man vindo por ...}
{305}{}{Homem grande que vem ...}

# 6. (FEMALE MADE MAN)
{320}{}{Mulher melhor tem meu dinheiro ...}
{321}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{322}{}{Bitch melhor não está me segurando ...}
{323}{}{Quem é essa mulher beeeewt-ifull que eu vejo?}
{324}{}{Porra, eu amo uma mulher que conhece seu crime.}
{325}{}{Você estilo, irmã, você estilo.}
{326}{}{Filmes agradáveis, mulher.}
{327}{}{Você está vestindo tudo letal e merda, eu gosto disso.}
{328}{}{Diga a palavra, e 'Eu vou estar assistindo você de volta, irmã.}
{329}{}{Eu tenho suas costas, irmã.}
{330}{}{Adoro esse cabelo preto e sua atitude gangsta sobre você, mulher.}

# 7. (MALE PRIZEFIGHTER)
{350}{}{Mulher melhor tem meu dinheiro ...}
{351}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{352}{}{Bitch melhor não está me segurando ...}
{353}{}{Você procura alguma ação, campeão?}
{354}{}{Você precisa de alguma ação, campeão? Eu dou-lhe um brinde.}
{355}{}{Deixe-me estender sua cortesia a você, campeão. Eu dou uma de minhas mulheres por uma noite inteira.}
{356}{}{Fale comigo, campeão. Eu peguei a mulher para você.}
{357}{}{Este não é nenhum dos Givens de Robbin que eu ganho ... você é uma boa mulher, sabe o que estou dizendo?}
{358}{}{Você estilo, campeão, você estilo.}
{359}{}{Não me decepcione no ringue, você ouve?}
{360}{}{Tenho 100 fichas montando você, campeão. Não me decepcione agora.}
{361}{}{Você precisa de um parceiro de boxe para esta noite, campeão? Eu pego um amigo.}
{362}{}{Diga a palavra, e 'vou estar assistindo você de volta, campeão.}
{363}{}{Eu tenho suas costas, campeão.}
{364}{}{Deixe-me configurá-lo, campeão. Eu era proxeneta do ano dois anos consecutivos.}
{365}{}{Champ chegando ...}
{366}{}{Homem grande que vem ...}

# 8. (FEMALE PRIZEFIGHTER)
{380}{}{Mulher melhor tem meu dinheiro ...}
{381}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{382}{}{Bitch melhor não está me segurando ...}
{383}{}{Quem é essa mulher beeeewt-ifull que eu vejo?}
{384}{}{Porra, eu amo uma mulher que sabe bater um homem.}
{385}{}{Você estilo, irmã, você estilo.}
{386}{}{Filmes agradáveis, mulher.}
{387}{}{Você está vestindo tudo letal e merda, eu gosto disso.}
{388}{}{Diga a palavra, e 'Eu vou estar assistindo você de volta, irmã.}
{389}{}{Eu tenho suas costas, irmã.}
{390}{}{Você, a mulher, a rainha, o campeão de ALL, sabe o que estou dizendo agora?}
{391}{}{Não me decepcione no ringue, você ouve?}
{392}{}{Tenho 100 fichas montadas em você, irmã. Não me decepcione agora.}
{393}{}{Eu amo o seu cabelo preto e seu gancho de esquerda perverso.}

# 9. FLOAT (COMPANION: MYRON)
{410}{}{Mulher melhor tem meu dinheiro ...}
{411}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{412}{}{Bitch melhor não está me segurando ...}
{413}{}{Vocês estão procurando alguma ação?}
{414}{}{Você parece que você precisa se molhar.}
{415}{}{Eu, Myron! Whazzup?}
{416}{}{Eu, Myron! Precisa de alguma empresa para esta noite? Eu tenho essa nova mulher para você ...}
{417}{}{Você está querendo ficar ... molhado?}
{418}{}{Você não consegue encontrar uma cauda mais doce, QUALQUER LUGAR.}
{419}{}{Eu sou tão brilhante, eu faço Reno parecer fraco.}
{420}{}{Você parece que você goteia um FOGO abaixo.}
{421}{}{Fale comigo, meus amigos. Eu tenho mulheres que você pode usar para toda a noite.}
{422}{}{Você obteve as batatas fritas, você pode ter um gosto do paraíso.}
{423}{}{Myron, eu não quero te pegar sem fazer um saquinho de chá em minhas mulheres novamente.}
{424}{}{Myron, eu não quero pegar você não fazendo nenhum golpe de burro em minhas mulheres novamente.}
{425}{}{Myron, eu não quero pegar você não fazendo cogumelos roxos nas minhas mulheres novamente.}
{426}{}{Myron, eu não quero pegar você não fazendo camelos voadores em minhas mulheres novamente.}
{427}{}{Myron, eu não quero pegar você não fazendo Cleveland Steamers em minhas mulheres novamente.}
{428}{}{Eu, Myron! Você precisa de um amigo para esta noite, Myron? Eu pego um amigo.}
{429}{}{Estes não são escravos, são profissionais, escutam o que estou dizendo?}
{430}{}{Myron! Menino, você ainda me deve para a semana passada!}
{431}{}{Ela pode sugar uma mangueira de jardim através de uma bola de golfe? Claro que sim.}
{432}{}{Eu tenho mulheres que fazem você um homem de verdade, só custam algumas fichas.}
{433}{}{Eu consegui o lode da mãe no meu estábulo.}
{434}{}{O que você faz dos estábulos, Myron? Procurando algum talento?}
{435}{}{Ol 'man Mordino deixa você finalmente, Myron?}

# 10. (COMPANION: SPOUSE = FEMALE)
{440}{}{Mulher melhor tem meu dinheiro ...}
{441}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{442}{}{Bitch melhor não está me segurando ...}
{443}{}{Pegou Myron doin 'burro socos na minha mulher novamente.}
{444}{}{É melhor não pegar Myron fazendo o Cleveland Steamer na minha mulher novamente.}
{445}{}{Você precisa de um amigo para esta noite, irmão? Eu pego um amigo.}
{446}{}{Estes não são escravos, são profissionais, escutam o que estou dizendo?}
{447}{}{Eu sou tão brilhante, eu faço Reno parecer fraco.}
{448}{}{Você não consegue encontrar uma cauda mais doce, QUALQUER LUGAR.}
{449}{}{Você obteve as batatas fritas, você pode ter um gosto do paraíso.}
{450}{}{Você melhor não proxeneta essa cadela por aqui.}
{451}{}{Eu vejo qualquer fichas trocando as mãos por aquela cadela sua, eu e você vai ter palavras.}
{452}{}{Essa bitch melhor se refresca quando ela está nesta cidade.}
{453}{}{Ditch that bitch o 'seu, amigo. Eu tenho uma mulher que você pode usar para toda a noite.}
{454}{}{Eu tenho mulheres que fazem você um homem de verdade, só custam algumas fichas.}
{455}{}{Eu consegui o lode da mãe no meu estábulo.}
{456}{}{Se eu vejo você vender a sua mulher, eu vou lhe dar um sorriso vermelho de Reno em sua garganta.}
{457}{}{Ela é sua "esposa", hein? Bem, "hubbie", ela melhor assistir seu traseiro nesta cidade.}
{458}{}{Este é o meu canto. Não proxeneta sua cadela aqui.}
{459}{}{É melhor não ver você vender aquele ho na minha rua.}

# 11. FLOAT (MALE SLAVER)
{470}{}{Mulher melhor tem meu dinheiro ...}
{471}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{472}{}{Bitch melhor não está me segurando ...}
{473}{}{Yo escravidão! Você está procurando por ... molhar?}
{474}{}{Slaver, se você conseguir encontrar uma cauda mais barata em qualquer lugar, eu combinarei com ela.}
{475}{}{Eu sou tão brilhante, eu faço Reno parecer fraco.}
{476}{}{Slaver, você parece um homem com um FOGO abaixo.}
{477}{}{Fale comigo, escravidão. Eu tenho uma mulher que você pode usar para toda a noite.}
{478}{}{Você obteve as batatas fritas, você pode ter um gosto do paraíso.}
{479}{}{Você precisa de um amigo para esta noite, slaver? Eu pego um amigo.}
{480}{}{Estes são melhores que os escravos. São profissionais, ouvi o que estou dizendo?}
{481}{}{Você obteve algum estoque, escravidão? Preciso de um novo sangue.}
{482}{}{Ela pode sugar uma mangueira de jardim através de uma bola de golfe? Claro que sim.}
{483}{}{Eu tenho mulheres que fazem você um homem de verdade, só custam algumas fichas.}
{484}{}{Eu consegui o lode da mãe no meu estábulo.}
{485}{}{Slaver, se alguma das minhas mulheres desaparecer, espero que você esteja pagando, entende?}
{486}{}{Deixe-me configurá-lo, escravidão. Eu era proxeneta do ano dois anos consecutivos.}
{487}{}{Eu entendi essa mulher que você deveria olhar, escravidão; ela tem esse bico de frutas suculentas e suaves.}
{488}{}{Eu não estou olhando para comprar nenhum escravo, mas eu posso estar procurando vender algum lil 'mais tarde.}
{489}{}{Você não está fazendo nenhum saquinho de chá na minha mulher agora, escravidão.}
{490}{}{Melhor eu não pegar você não fazendo golpes de burro na minha mulher, escravidão.}
{491}{}{Aquela cadela punk-ass, Myron deu metade das minhas mulheres com cogumelos roxos.}
{492}{}{Eu vou bater em Myron como uma puta se eu o pegar fazendo um Cleveland Steamer em minhas mulheres novamente.}
{493}{}{Slaver, se alguma das minhas mulheres desaparecer, espero que você esteja pagando, entende?}
{494}{}{Se você conseguir encontrar uma cauda mais barata em qualquer lugar, escravidão, eu combinarei com ela.}
{495}{}{Você não está fazendo nenhum saquinho de chá na minha mulher agora, escravidão.}
{496}{}{Talvez eu tenha algum estoque para vender você mais tarde se minha mulher me derruba novamente.}
{497}{}{Os escravos sempre são bem-vindos nesta cidade.}

# 12. (FEMALE SLAVER)
{500}{}{Mulher melhor tem meu dinheiro ...}
{501}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{502}{}{Bitch melhor não está me segurando ...}
{503}{}{Eu sou tão brilhante, eu faço Reno parecer fraco.}
{504}{}{Você precisa de um amigo para esta noite, slaver? Eu levo uma coisa jovem, masculina ou feminina, o que quer que seja
 você quer.}
{505}{}{Eu entendi essa mulher que você deveria olhar, escravidão; ela tem esse bico de frutas suculentas e suaves.}
{506}{}{Slaver, você se parece com uma mulher que precisa caminhar pelo lado selvagem.}
{507}{}{Você precisa de um amigo para esta noite, slaver? Eu levo um amigo, masculino ou feminino, o que você quiser.}
{508}{}{Slaver, se alguma das minhas mulheres desaparecer, espero que você esteja pagando, entende?}
{509}{}{Talvez eu tenha algum estoque para vender você mais tarde se minha mulher me derruba novamente.}
{510}{}{Eu não estou olhando para comprar nenhum escravo, mas eu posso estar procurando vender algum lil 'mais tarde.}
{511}{}{Eu entendi essa mulher que você deveria olhar, escravidão; ela tem esse bico de frutas suculentas e suaves.}
{512}{}{Os escravos sempre são bem-vindos nesta cidade.}

# 13. (MALE, NO REP)
{520}{}{Mulher melhor tem meu dinheiro ...}
{521}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{522}{}{Bitch melhor não está me segurando ...}
{523}{}{Você está procurando alguma ação?}
{524}{}{Você está procurando por ... molhar?}
{525}{}{Você não consegue encontrar uma cauda mais doce, QUALQUER LUGAR.}
{526}{}{Eu sou tão brilhante, eu faço Reno parecer fraco.}
{527}{}{Você parece um homem com um FOGO abaixo.}
{528}{}{Fale comigo, amigo. Eu tenho uma mulher que você pode usar para toda a noite.}
{529}{}{Você obteve as batatas fritas, você pode ter um gosto do paraíso.}
{530}{}{Você precisa de um amigo para esta noite, irmão? Eu pego um amigo.}
{531}{}{Estes não são escravos, são profissionais, escutam o que estou dizendo?}
{532}{}{As melhores damas de todos os novos Reno. O seu para perguntar ... se você pegou as fichas.}
{533}{}{Ela pode sugar uma mangueira de jardim através de uma bola de golfe? Claro que sim.}
{534}{}{Eu tenho mulheres que fazem você um homem de verdade, só custam algumas fichas.}
{535}{}{Eu consegui o lode da mãe no meu estábulo.}
{536}{}{Deixe-me configurá-lo, cara. Eu era proxeneta do ano dois anos consecutivos.}
{537}{}{Eu consegui essa mulher que você experimentou; ela tem esse bico de frutas suculentas e suaves.}
{538}{}{Você não está fazendo nenhum saquinho de chá na minha mulher agora.}
{539}{}{É melhor eu não pegar você não fazendo golpes de burro na minha mulher.}
{540}{}{É melhor não dar às minhas mulheres sem cogumelos roxos, ouvi-lo?}
{541}{}{Eu pego você fazendo um Cleveland Steamer em QUALQUER das minhas mulheres, e eu vou matá-lo.}
{542}{}{Você está procurando alguma ação?}
{543}{}{Eu consegui as melhores putas em todo o novo Reno. Basta experimentá-los e ver.}

# 14. (FEMALE, NO REP)
{550}{}{Mulher melhor tem meu dinheiro ...}
{551}{}{Esses turistas não são tão gostosos quanto eu gostaria.}
{552}{}{Bitch melhor não está me segurando ...}
{553}{}{:: Escalonando você ::}
{554}{}{Caramba, venha falar comigo por um momento.}
{555}{}{Venha aqui, recebi uma posição profissional para você.}
{556}{}{Confira aquele bico suculento de frutas suculentas.}
{557}{}{Baby, venha, deixe-me espremer essa suculenta suculenta fruta e seu.}
{558}{}{Ei, linda. Você está interessado em fazer algum trabalho?}
{559}{}{Tenho algum trabalho para você; O benefício é que você consegue se deitar no trabalho.}
{560}{}{Você precisa de um lugar para ficar, açúcar e especiarias?}
{561}{}{Volte para o meu berço, o melhor lugar para ficar em todo o Reno.}
{562}{}{Você tem um lugar para ficar? Eu posso te pegar um.}
{563}{}{:: Escala você para fora ::}
{564}{}{Bebê, deixe-me espremer essa suculenta e suculenta fruta.}
{565}{}{Você está procurando ganhar algum arranhão fácil, mulher?}
