# 0. QUICK LOOK
{100}{}{Você vê o chefe do poço do cassino.}

# 0. LOOK
{150}{}{Você vê um homem bem vestido. Ele está pesquisando o cassino.}
{151}{}{Você vê um chefe de poço. Ele está pesquisando o cassino.}

# 1. FLOAT DIALOGUE: POWER ARMOR (WTG)
{200}{}{Uh ... você precisará remover essa armadura.}
{201}{}{Uh, senhor ... ou senhora ... você precisará remover essa armadura.}
{202}{}{Senhor ... senhora ... você não pode usar isso no cassino.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{205}{}{Uh, por que você está se esgueirando, senhor?}
{206}{}{Uh, você está disfarçado, senhor?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{210}{}{Uh, por que você está se esgueirando, senhora?}
{211}{}{Uh, você está embutido, senhora?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{215}{}{Boa noite,}
{1215}{}{, Senhor.}
{216}{}{Tarde,}
{1216}{}{, Senhor.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{220}{}{Boa noite,}
{1220}{}{, senhora.}
{221}{}{Tarde,}
{1221}{}{, senhora.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO (WTG)
{225}{}{Dia bom,}
{1225}{}{, Senhor.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO (WTG)
{230}{}{Dia bom,}
{1230}{}{, senhora.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO (WTG)
{235}{}{Amigo, você está entrando no casino errado.}
{236}{}{É melhor você sair. Agora.}
{237}{}{Este não é o lugar para jogar com sua vida. É melhor você sair.}
{238}{}{Cadela, você está entrando no cassino errado.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED) (WTG)
{245}{}{Senhor, desculpe, você terá que proteger essa arma.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED) (WTG)
{250}{}{Senhor, desculpe, você terá que proteger essa arma.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED) (WTG)
{255}{}{Querida, desculpe, não pode levar armas ao cassino. Heh-heh ... você é bastante mortal como está.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK) (WTG)
{260}{}{Querida, com um corpo como esse, você não poderá se esgueirar em qualquer lugar.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED) (WTG)
{265}{}{Tribal, é melhor você proteger essa arma agora.}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK) (WTG)
{270}{}{Tribal, é melhor você parar de se esconder por causa da merda agora.}

# 16. MYRON, MORDINO (WTG)
{275}{}{Ei, ei ... Myron! Não foi visto fora do laboratório há muito tempo.}
{276}{}{Você está aqui para experimentar algumas das novas mercadorias, Myron?}
{277}{}{Ei! Entre, Myron.}

# 17. MARCUS (WTG)
{285}{}{Não há mutantes. Ele espera lá fora.}
{286}{}{Eu não me importo se seu amigo um dos Ex-Men, os mutantes esperam lá fora.}
{287}{}{Esse tipo de mutante não é permitido aqui.}

# 18. ROBOBRAIN (WTG)
{295}{}{Sem droides.}
{296}{}{Nós não servimos droids.}
{297}{}{Sem droides. They wait outside.}

# 19. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE  (WTG)
{305}{}{Eu não estou interessado em conversar enquanto estava de plantão, mas estou feliz que você tenha chutado o traseiro do Enclave.}
{306}{}{Ei,}
{1306}{}{. Descanse de salvar o mundo e se divertir.}

# 20. FLOAT DIALOGUE: DAY (WTG)
{315}{}{Precisa de mais fichas na tabela três ...}
{316}{}{Boa multidão hoje ...}

# 21. FLOAT DIALOGUE: NIGHT (WTG)
{325}{}{Precisa de mais fichas na tabela três ...}
{326}{}{Boa noite esta noite ...}

# 22. INTRO (WTG)
{335}{}{Ei,}
{336}{}{! Heard yer the one who kicked the Enclave back to the stone age! I've been instructed to give you some chips,
 courtesy of the casino. Enjoy yourself, Senhor.}
{337}{}{! Heard yer the one who kicked the Enclave back to the stone age! I've been instructed to give you some chips,
 courtesy of the casino. Enjoy yourself, senhora.}
{338}{}{. O que há, chefe? Obter você qualquer coisa? Uma bebida? Uma garçonete?}
{339}{}{. A menina mais bonita do cassino. Obter você qualquer coisa? Uma bebida? Uma mesa privada?}
{340}{}{O que posso fazer por você, amigo?}
{341}{}{O que posso fazer por você, querida?}
{342}{}{Fooooooo foo foo fooooo}
{343}{}{Afastar-se}
{344}{}{Quem é Você?}
{345}{}{Qual casino é esse?}
{346}{}{Você pode me contar um pouco sobre o cassino?}
{347}{}{Você conhece alguém chamado Pretty Boy Lloyd?}
{348}{}{Quem é aquele velho na slot machine?}
{349}{}{Esse quadrinho que você conseguiu no palco é fraco. Atenção, se eu tentar?}
{350}{}{Obrigado. Você precisa de um dançarino durante a noite? Estou aberto para um compromisso limitado.}
{351}{}{Obrigado, eu vou.}
{352}{}{Nada, obrigado. Desculpe incomodá-lo.}
{353}{}{Apenas verificando as coisas. Continue.}

# 23. PORN STAR (WTG)
{360}{}{Ei,look who's here! Ei,}
{361}{}{. Bem-vindo ao [CN]. Ame seus filmes.}
{362}{}{Fooooooo foo foo fooooo}
{363}{}{Afastar-se}
{364}{}{Quem é Você?}
{365}{}{Qual casino é esse?}
{366}{}{Você pode me contar um pouco sobre o cassino?}
{367}{}{Você conhece alguém chamado Pretty Boy Lloyd?}
{368}{}{Quem é aquele velho na slot machine?}
{369}{}{Obrigado. Você precisa de um dançarino durante a noite? Estou aberto para um compromisso limitado.}
{370}{}{Obrigada, estou lisonjeada. Acabei de sair para dizer olá.}

# 24. I HAD SOME QUESTIONS (31, 32, 33, 34, 35, 36, 37, 38)
{280}{}{Atire. O que você quer saber?}
{281}{}{Fooooooo foo foo fooooo}
{282}{}{Afastar-se}
{283}{}{Quem é Você?}
{284}{}{Qual casino é esse?}
{285}{}{Você pode me contar um pouco sobre o cassino?}
{286}{}{Você conhece alguém chamado Pretty Boy Lloyd?}
{287}{}{Quem é aquele velho na slot machine?}
{288}{}{Esse quadrinho que você conseguiu no palco é fraco. Atenção, se eu tentar?}
{289}{}{Obrigado. Você precisa de um dançarino durante a noite? Estou aberto para um compromisso limitado.}
{290}{}{Obrigado, eu vou.}
{291}{}{Nada, obrigado. Desculpe incomodá-lo.}
{292}{}{Apenas verificando as coisas. Continue.}

# 25.  RETARD (22, 23, 24)
{300}{}{Uh, you better run along now, Senhor.}
{301}{}{Uh, you better run along now, senhora.}
{302}{}{Saia daqui, demora.}
{303}{}{Mamãe diz que eu era speshal}
{304}{}{Afastar-se}

# 26.  MOM SAYS I WAS SPESHAL (25)
{315}{}{Sim, sua mãe disse que eu também era especial. Agora faça uma caminhada ... talvez ela esteja pela rua Virgin em algum lugar.}
{316}{}{Oh, bom! Tchau tchau}
{317}{}{Afastar-se}

# 27.  WHO ARE YOU? (22, 23, 24, 29, 30, 31)
{325}{}{Eu sou o chefe do poço. Agora, o que posso fazer por você?}
{326}{}{Corro o chão do cassino aqui. Você precisa de algo, apenas pergunte.}
{327}{}{Qual casino é esse?}
{328}{}{Você pode me contar um pouco sobre o cassino?}
{329}{}{Nada, obrigado. Desculpe incomodá-lo.}

# 28.  WHAT CASINO IS THIS? (22, 23, 24, 27)
{335}{}{Isto é [CN]. Precisa de algo, basta perguntar.}
{336}{}{Isto é [CN]. Pelo menos, a última vez que chequei o sinal da porta. Agora, o que posso fazer por você?}
{337}{}{Quem é Você?}
{338}{}{Você pode me contar um pouco sobre o cassino?}
{339}{}{Nada, obrigado. Desculpe incomodá-lo.}

# 29.  WHAT CAN YOU TELL ME ABOUT THIS CASINO? (22, 23, 24, 27, 28, 30)
{345}{}{Melhor maldito cassino da cidade ... mas estou um pouco tendencioso. Mais alguma coisa que você queira saber?}
{346}{}{Melhor maldito cassino da cidade, melhores malditas mesas ... agora, por que você não corre agora, confira-os? Tudo certo?}
{347}{}{Quem é Você?}
{348}{}{Quem é dono deste cassino?}
{349}{}{Ok, obrigado. Desculpe incomodá-lo.}

# 30.  WHO OWNS THIS CASINO? (29)
{355}{}{A família [CA]. Eles atraíram muita vida para este lugar, tornaram-no um verdadeiro lugar noturno, uma jóia brilhante em New Reno.}
{356}{}{A Família [CA]. Que um problema? Porque se você não está aqui para apostar, então este não é o lugar para você. Compreendo?}
{357}{}{Quem é Você?}
{358}{}{Você pode me contar um pouco sobre o cassino?}
{359}{}{Entendo. Obrigado pelo seu tempo.}

# 31.  McGEE (22, 23, 24)
{365}{}{Aquele cara? Old Man McGee? Crazy sumabitch ... ele está jogando naquela máquina
 Há alguns anos, aguardando o grande jackpot. Sua fortuna de vida
 deve estar sentado naquela coisa, mas não lhe dará um único chip.}
{366}{}{Aquele cara? Old Man McGee? Crazy sumabitch, com certeza. Heh.
 Claro que estava chateado com você ganhando sua fortuna. Eu teria cuidado com ele.}
{367}{}{A maquinaria é manipulada?}
{368}{}{Tive algumas outras questões ...}
{369}{}{Obrigado pela informação.}

# 32.  IS THE MACHINE RIGGED? (31)
{375}{}{Não, é apenas teimoso ... assim como ele. Provavelmente poderia usar um pequeno trabalho de reparação, mas não temos nenhum slot
 Mecânica que pode consertar essa maldita coisa.}
{376}{}{Tive algumas outras questões ...}
{377}{}{Interesting. Obrigado pela informação.}

# 33.  PRETTY BOY LLOYD? (22, 23, 24)
{385}{}{Sim, aquele filho da puta veio aqui há cerca de uma semana, arrancou uma mesa de cerca de mil fichas e depois se salvou.
 Não sei onde ele está agora, mas ele costumava ter um quarto no Desperado.}
{386}{}{Sim, algum cara desse nome estava alinhando um dos quartos no andar de cima ... 204. Ele foi pago, mas ele renunciou
 alguns dias atrás, e ninguém o viu sair.}
{387}{}{O Sr. Salvatore mencionou que havia um revendedor específico que Lloyd ganhou o dinheiro. Quem era aquele?}
{388}{}{Tive algumas outras questões ...}
{389}{}{Obrigado pela informação.}

# 34.  NIKKI? (33)
{395}{}{Nikki? Sim, ela está lá, na mesa do meio. Existe algum tipo de problema?}
{396}{}{No problem. Just wanted to meet her. Tive algumas outras questões ...}
{397}{}{Obrigado pela informação.}

# 35.  NIKKI DEAD (33)
{405}{}{O nome dela era Nikki. Ela costumava trabalhar aqui, mas ela conseguiu ... não há muito tempo atrás.}
{406}{}{Hmmm. Você se importa se eu fizer algumas outras perguntas ...?}
{407}{}{Interesting. Obrigado pela informação.}

# 36.  NIKKI RAN (33)
{415}{}{O nome dela era Nikki. Ela costumava trabalhar aqui, mas ela não demorou muito tempo atrás. Apenas empacotou sua merda e resgatou.}
{416}{}{Você se importa se eu fizer algumas outras perguntas ...}
{417}{}{Interesting. Obrigado pela informação.}

# 37.  NEED A DANCER (22, 23, 24)
{425}{}{Claro, seja bom para os negócios. Sala de vestir nas costas ...}
{426}{}{Excelente. Estarei no palco em alguns minutos ...}
{427}{}{Not right now. Tive algumas outras questões ...}
{428}{}{Não agora, mas voltarei.}

# 38.  NEED A DANCER (22, 23, 24)
{435}{}{Não, ainda estamos recuperando do seu último show. Você pode querer verificar alguns dos outros casinos.}
{436}{}{All right, thanks. Say, Tive algumas outras questões ...}
{437}{}{Ok ... embora eu voltei.}

# 39.  PERFORM (37)
{445}{}{Você conta o recorde da noite. salgadinhos. Não é um mau lance.}
{446}{}{O couro era um toque agradável.}
{447}{}{A bola que você teve com você também não doeu.}
{448}{}{Eu vou fazer ainda melhor na próxima vez ...}

# 40.  PERFORM (22, 24)
{455}{}{Sim, ele fica pior do que a merda brahmin. Ainda você…? Ah, por que diabos não. Um pouco de improvisação não vai doer, mas
 é uma multidão áspera ... é melhor esperar que você esteja bem.}
{456}{}{Oh, eu estou bem ... apenas me observe.}
