# QUICK LOOK
{100}{}{Você vê uma prostituta.}

# EXAMINE
{150}{}{Você vê uma ... senhora da noite. Suas roupas esfarrapadas são drapejadas sedutoramente ao redor de seu corpo.}
{151}{}{Você vê uma prostituta. She winks at you.}
{152}{}{Você vê uma prostituta. Her eyes are like blown fuses.}
{153}{}{Você vê uma prostituta. She smells like flowers.}
{154}{}{Você vê uma prostituta. She smells like mother.}
{155}{}{Você vê uma prostituta. It is a mystery to you how her tattered rags manage to hold her breasts in.}
{156}{}{Você vê uma prostituta. She looks as if she kills her mates and eats them.}
{157}{}{Você vê uma prostituta. She is appraising you like a jeweler.}
{158}{}{Você vê uma prostituta. Her tattered clothes are draped seductively around her body.}

# 1. [MALE, ENCLAVE DESTROYED]
{175}{}{Oh meu ... é ele. .}
{176}{}{Você é o maior espetáculo do mundo.}
{177}{}{:: Swoons ::}
{178}{}{Sim,}
{179}{}{:: Claps ::}
{180}{}{::Felicidades::}
{181}{}{Oh meu ... é ela.}
{182}{}{Vai nessa, garota!}
{183}{}{:: Dá-lhe o thumbs up sign ::}

# 2. [POWER ARMOR]
{190}{}{Você não poderia me pagar fichas suficientes para fazer isso com você NADA.}

# 3. [MALE, PORN STAR]
{195}{}{Por aqui,}
{196}{}{Veja! É ele!}
{197}{}{Ei,}
{198}{}{Ei,sweetie? Any openings I could fill?}
{199}{}{Quando o seu próximo filme está saindo?}
{200}{}{Mmmm-mmmm. Trabalhe, querida.}
{201}{}{Para que você precisa de ME para, Boogie Man?}
{202}{}{Ooops. Deixei cair alguma coisa na sua calça. Deixe-me entender.}
{203}{}{Eu amei você em Great Balls for Hire.}
{204}{}{Eu amei-o em boa vontade, batendo.}
{205}{}{Eu amei você em Vault Sexteen.}
{206}{}{Você foi ótimo em Pokeahotass.}
{207}{}{Mmmmm-mmmm. Como você se mantém tão apto?}
{208}{}{Você pode me dar seu autógrafo? No meu baú?}
{209}{}{Posso atuar no seu próximo filme?}
{210}{}{Eu nunca falharia com você,}
{211}{}{Obtendo ... fraco. Não posso ... aguentar ... muito mais tempo. Deve ... ter ... sexo ... com você ...}

# 4. [PORN STAR, FEMALE]
{212}{}{Ela não é uma estrela, ela é apenas um lixo tribal ...}
{213}{}{Eu não percebi que permitiram que as estrelas pornô conseguissem isso gordo ...}
{214}{}{Ela é fugitiva.}
{215}{}{Ela tem todo o sex appeal de um saco de papel molhado ...}
{216}{}{Feio como pecado ...}
{217}{}{Do jeito que ela age, você pensaria que ela era um modelo de herói em vez de uma estrela pornô.}
{218}{}{Ela tenta qualquer coisa, eu vou assustá-la ...}
{219}{}{Não sei o que os Irmãos da Córsega vêem nela ...}
{220}{}{Ela é tão talentosa quanto uma pedra e duas vezes mais feia.}
{221}{}{É verdade, você MANTENHA andar.}
{222}{}{Me deixa com náusea apenas olhando para ela ...}
{223}{}{Olhe para ela, se pavoneando assim ...}
{224}{}{Ela tem um rosto que apenas um brâmane poderia amar.}
{225}{}{Bem, se não é a grande Rainha Turd.}
{226}{}{Se não é pequena, perdoa ...}
{227}{}{Se não é uma pequena estrela da pornografia ...}
{228}{}{Mais feio do que o burro de uma bruxa.}
{229}{}{Empurre! Esta é a nossa área, puta!}
{230}{}{Empurre o seu burro gordo fora da minha visão.}
{231}{}{Você é tão talentoso quanto meu sapato.}
{232}{}{Fique nesta rua, e nós vamos cortá-lo.}
{233}{}{Cadela.}
{234}{}{Prostituta furada ...}
{235}{}{Lixo...}
{236}{}{Hmphh!}
{237}{}{Saia daqui, você está arruinando o negócio.}
{238}{}{Meretriz escavada.}
{239}{}{Não fale comigo, puta.}
{240}{}{Volte para fazer o seu dinheiro o caminho lento, prostituta.}
{241}{}{Que parte de 'piss off' você não entende?}
{242}{}{Fale comigo novamente, vou cortar a língua.}
{243}{}{Gutterslut.}
{244}{}{:: Ignora você. ::}
{245}{}{:: Faz um gesto obsceno ::}
{246}{}{Saia daqui, "Miss Movie Star".}
{247}{}{Bata, puta.}
{248}{}{Você tenta qualquer coisa, eu vou cicatrizar você ...}
{249}{}{Não sei o que os Irmãos da Córsega vêem em você ...}
{250}{}{Você é tão talentoso como uma pedra e duas vezes mais feio.}
{251}{}{Eu não falo com o TRASH como você.}

# 5. [MALE, PRIZEFIGHTER]
{252}{}{Olhe para esses músculos! Me deixa fraco ...}
{253}{}{Daaaamn!}
{254}{}{:: Whistles ::}
{255}{}{Ele foi construído como um tanque. Confira esse barril.}
{256}{}{Confira o barril naquele tanque ...}
{257}{}{Ele é todo meu ...}
{258}{}{::Suspiro::}
{259}{}{O que é um mal.}
{260}{}{Esse garoto me deixa fraco.}
{261}{}{Se não é o Rei de Sting ...}
{262}{}{Ele liderou em seu lápis, é por certeza.}
{263}{}{Veja! Está}
{264}{}{}
{265}{}{Agora tenho algum problema em que eu quero entrar.}
{266}{}{Quer saltar no ringue comigo, campeão?}
{267}{}{Quer caixa, campeão?}
{268}{}{Como está pendurado,}
{269}{}{Procurando por mim?}
{270}{}{Por que você não vem mais frequentemente?}
{271}{}{Recebi uma abertura que você pode preencher.}
{272}{}{Precisa de alguma empresa,}
{273}{}{Você é um malvado.}
{274}{}{Você me deixa fraco, você sabe disso?}
{275}{}{Boa unidade que você chegou lá.}
{276}{}{Precisa de alguém para cuidar disso para você, campeão?}
{277}{}{Ei ... cuidado com o Masticador. Ele é um verdadeiro idiota. Ele tentou morder minha orelha uma vez.}

# 6. [FEMALE, PRIZEFIGHTER]
{278}{}{Veja! Está}
{279}{}{Precisa de alguma empresa,}
{280}{}{}
{281}{}{Ela é um maldito. Eu gostaria de poder chutar os jumentos de garoto como ela faz.}
{282}{}{Lá é uma mulher dura.}
{283}{}{Ela parece tão ... (arrepios) ... perigoso.}
{284}{}{Ela é muito sexy.}

# 7. [MADE MAN]
{285}{}{Oh meu ... é ele.}
{286}{}{Ele parece tão ... (arrepios) ... perigoso.}
{287}{}{Daaaamn!}
{288}{}{:: Whistles ::}
{289}{}{O que é um mal.}
{290}{}{Esse garoto me deixa fraco.}
{291}{}{Ele liderou em seu lápis, é por certeza.}
{292}{}{Hellooooo}
{293}{}{Precisa de alguma empresa,}
{294}{}{}
{295}{}{Oh meu ... é ela.}
{296}{}{Ela é tão malvada.}
{297}{}{Lá vai uma cadela dura.}
{298}{}{Ela parece tão ... (arrepios) ... perigoso.}
{299}{}{Ela é muito sexy.}

# 8. [SLAVER]
{300}{}{Meu nome é fácil, escravidão. O que é seu?}
{301}{}{Ei,slaver, need some comapny?}
{302}{}{Deixe-me ensinar-lhe algumas coisas que uma mulher pode ensinar.}
{303}{}{Precisa de alguém para compartilhar seu bedroll, slaver?}
{304}{}{Tem algumas pedras quentes lá, escravas.}
{305}{}{Cobra desagradável de virilha pequena.}
{306}{}{Procurando alguma ação?}
{307}{}{Slaver, você nunca teve amor até que você tivesse amor de Reno.}
{308}{}{Procurando uma data?}
{309}{}{Ouvi dizer que havia problemas na linha comercial ...}
{310}{}{À procura de alguma empresa?}
{311}{}{Quer dançar?}
{312}{}{Slaver, você nunca teve amor até que você tivesse amor de Reno.}
{313}{}{Claro, eu serei um dos seus "companheiros" para algumas fichas.}
{314}{}{Novo estranho no towm, parece ...}
{315}{}{Quer voar, escravidão?}
{316}{}{Quer jogar escravidão e servo?}
{317}{}{Nice aneto.}
{318}{}{Deixe-me te animar, palhaço triste.}
{319}{}{Perder o seu caminho, escravidão?}
{320}{}{Tem uma arma que você precisa para descarregar, escravidão?}
{321}{}{Esse homem poderia derreter o metal.}
{322}{}{Myron? Eu não o tocaria por um milhão de fichas. Faça dois milhões.}
{323}{}{À procura de um bom tempo, slaver?}
{324}{}{Eu gosto do olhar de seu gecko, escravo.}
{325}{}{Que um gecko no seu bolso?}
{326}{}{Ei, escravidão.}
{327}{}{Precisa de uma data, escravidão?}
{328}{}{Onde está o fogo, o escravidão?}
{329}{}{Childe, deixe-me fazer de você um homem.}
{330}{}{Quer jogar escravidão e servo?}
{331}{}{Queres fingir que somos mortes na temporada de acasalamento?}
{332}{}{Precisa abrir um clipe, escravidão?}
{333}{}{Quer ajudar uma virgem a perder a virgindade?}
{334}{}{Que o escravidista faz com que meu contador Geiger marque.}
{335}{}{Se você quiser que eu seja legal, isso será extra.}
{336}{}{[Canta.] "Vamos jogar - mestre e servo. Vamos jogar - mestre e servo".}
{337}{}{Faça uma aposta em mim, escravidão.}
{338}{}{Eu finalmente instaluei essa cabeceira acolchoada.}
{339}{}{O sabor do paraíso custará dez fichas.}
{340}{}{Quer jogar mestre e servo, escravidão?}
{341}{}{Myron: toda a cera. Sem pavio.}
{342}{}{Myron é um real twister ...}
{343}{}{AC-DC, B n 'D, seja o que for.}
{344}{}{O que ele espera que eu faça, dobre-se por ele?}
{345}{}{Precisa de alguém para arrancar sua coleira, escravidão?}
{346}{}{Myron ainda continua vindo ...}
{347}{}{Aquela bisbilhota é um coelhinho de cama.}
{348}{}{Ela não é Jet dependente, ela é uma dependente de OSS.}
{349}{}{Ação na Cat's Paw está aquecendo ...}
{350}{}{Tinha uma sessão de maratona fugindo de Myron ontem à noite ...}
{351}{}{À procura de um TLC, um escravo?}
{352}{}{Saiu dessa faixa desde ontem ...}
{353}{}{Como qualquer coisa que você vê, slaver?}
{354}{}{Você está à procura de amor, escravidão?}
{355}{}{Ei, escravidão! Venha conversar comigo.}
{356}{}{:: Whistles at you ::}
{357}{}{Vai ficar em Reno longo?}
{358}{}{Odeio boquilhas de chá.}
{359}{}{Por que você não me leva de volta para sua gaiola, escravidão?}
{360}{}{Só pega algumas fichas, chamando minha atenção.}
{361}{}{Amor puro de Reno, aqui mesmo.}
{362}{}{Eu vou te dar um pouco de jogo.}
{363}{}{Eu sou Filthy Spice.}
{364}{}{Eu sou tempero caseiro.}
{365}{}{Eu sou Slutty Spice.}
{366}{}{Eu sou Old Spice.}
{367}{}{Eu sou Sífilis ... er, Slutty Spice.}
{368}{}{Eu sou Dirty Spice.}
{369}{}{Wranglers na poeira, é o que eu quero.}
{370}{}{Eu tenho um amigo se você quiser um duplo cabeçalho, escravo.}
{371}{}{Gostaria que Myron fosse gay.}
{372}{}{Novo sangue na cidade ...}
{373}{}{Ainda não sei porque eles chamam de Virgin Street ...}
{374}{}{Você pode martelar um pico de seis polegadas através de uma placa com o seu pénis?}
{375}{}{Gostaria que ele usasse um saco de papel às vezes ...}
{376}{}{Comprar uma garota com uma bebida, escravidão?}
{377}{}{Pegue uma senhora solitária na cidade, escravidão?}
{378}{}{Precisa de um amigo para esta noite, slaver?}
{379}{}{Procurando por alguma mercadoria nova, o escravo?}
{380}{}{Venha aqui, escravidão, o show está prestes a começar ...}
{381}{}{Ouvi algumas das garotas da parte alta mataram seu cafetão.}
{382}{}{Mulher mais bonita nos resíduos, aqui mesmo ...}
{383}{}{Que Jules melhor me deixe em paz.}
{384}{}{Ainda tenho essa hematoma da cabeceira da cama ...}
{385}{}{Esgotado desde a última convenção ...}
{386}{}{Desejo que a convenção do escravo tenha ocorrido em alguma outra cidade.}
{387}{}{Senti a Terra se mover, mas era apenas o pimentão.}
{388}{}{Me faça derreter.}
{389}{}{Ele continua, ele vai derrubar seu ticker ...}
{390}{}{Eu cuidarei de você, escravidão.}
{391}{}{Sou virgem. Eu não sou muito bom nisso.}
{392}{}{Jules continua tentando lidar na segunda rua ...}
{393}{}{Ei,slaver! Need a guide?}
{394}{}{Jules continua querendo brindes.}
{395}{}{Precisa de sua gaiola rattled, slaver?}
{396}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{397}{}{As coisas são bastante lentas. Desejo que a caravana mostre.}
{398}{}{Então ele se veste neste traje do Deathclaw, então ...}
{399}{}{Preciso de ajuda para sair desse vestido.}
{400}{}{Feche-me? Então, de novo?}
{401}{}{Mmm-mmm. Parece época de acasalamento.}
{402}{}{Precisa de um amigo?}
{403}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{404}{}{Olhando para ir para a cidade, escravidão?}
{405}{}{Eles não me chamam de Lady Lucky por nada.}
{406}{}{Ame esses preservativos com sabor a brahmin.}
{407}{}{Mostre a uma senhora um bom tempo, escravidão?}
{408}{}{Myron continua me incomodando. Pelo menos o seu DINHEIRO é bom.}
{409}{}{Tudo o que você precisa é aqui.}
{410}{}{Procurando por Eden? Bem aqui.}
{411}{}{Você obteve o dinheiro, o escravidão, eu consegui o tempo.}
{412}{}{Pode me ajudar? Estou à procura da minha virgindade perdida.}
{413}{}{Sou virgem, mas preciso do dinheiro.}
{414}{}{Seja gentil, é a minha primeira vez. Hoje.}
{415}{}{Eu tão excitado.}
{416}{}{Você obteve o desejo, recebi a poupança.}
{417}{}{Deixe-me acordar o seu filho interior.}
{418}{}{Quer dançar, querido?}
{419}{}{Olhando para apostar em uma reivindicação?}
{420}{}{Quer me fazer gemer?}
{421}{}{:: Purrrrr ::}
{422}{}{:: Rrrrrowrrr ::}
{423}{}{:: Sopra-te um beijo ::}
{424}{}{Quer se juntar?}
{425}{}{Não sou barato, mas estou especial.}
{426}{}{Acelerar-se custos adicionais.}
{427}{}{Onde eu deixei meu chicote?}
{428}{}{Pronto como um freddie.}
{429}{}{Eu tive que vestir-me como WILMA ontem à noite, Fer Chrissakes.}
{430}{}{Estava com Myron ontem à noite. Por cerca de cinco segundos.}
{431}{}{Gostaria que eles saíssem com alguns óleos de corpo cheiro de jato ...}
{432}{}{O meu traseiro vai cair, Myron continua.}
{433}{}{Damn Temperance Union veio de novo ...}
{434}{}{:: Whistles ::}
{435}{}{Garanto que sou melhor do que o anexo do Pip Boy que você usou.}
{436}{}{Quer que eu aperte seus parafusos, escravas?}
{437}{}{Prefiro estar com Avellone.}
{438}{}{Eu queria que Nick Kesting estivesse aqui. Poderíamos conversar por horas!}
{439}{}{Nick Kesting é um cara muito legal. Temos excelentes conversas.}
{440}{}{Tommy the Balls é tão sonhador.}
{441}{}{Bem bem. Olha quem acabou de entrar na cidade ...}
{442}{}{Você parece alguém com algum tempo para queimar.}
{443}{}{Oh garoto! Um turista!}
{444}{}{Morder é extra.}
{445}{}{Meu nome é fácil, escrava-garota. O que é seu?}
{446}{}{Ei,slaver-girl. Looking for the other woman?}
{447}{}{Procurando um sabor do outro lado, querido?}
{448}{}{Precisa de um "escravo" para a noite, escrava-menina?}
{449}{}{Precisa de alguém para aquecer sua barraca, escrava-menina?}
{450}{}{Precisa de alguém para compartilhar seu bedroll, slaver-girl?}
{451}{}{Quer dançar, escrava-menina?}
{452}{}{Slaver-girl, você nunca teve amor até que você tivesse amor de Reno.}
{453}{}{Quer voar, escrava-menina?}
{454}{}{Perder o seu caminho, escravidão-menina?}
{455}{}{À procura de um bom tempo, escrava-menina?}
{456}{}{Não percebi que a aluna da escrava tinha mulheres agora ...}
{457}{}{Onde está o fogo, escrava-menina?}
{458}{}{Essa menina escravista é muito foxy.}
{459}{}{Essa escrava-garota faz meu tiquetaque do Geiger.}

# 9. (ANY) TO [COMPANION: ROBOBRAIN AND/OR MARCUS]
{460}{}{Garanto que estou melhor no saco que esse robô o seguisse.}
{461}{}{Esse robô é TOTALMENTE funcional?}
{462}{}{Isso é algum tipo de máquina caça-níqueis que o está seguindo?}
{463}{}{Isso é uma máquina robo-slot?}
{464}{}{Seu robô faz truques? Uh ... truques de mágica, quero dizer.}
{465}{}{Diga-me que não é um mutante.}
{466}{}{Esse mutante será extra. Muito mais.}
{467}{}{Uh-oh. Mutantes em New Reno. Deve significar problemas.}
{468}{}{Esse mutante é um grande mutha.}
{469}{}{Esse mutante parece que ele poderia me esmagar em uma mão. Hmmmnnn.}
{470}{}{Eu nem saberia o que cobrar por um mutante.}

# 10. [COMPANION: MYRON]
{471}{}{Ei,Myron!}
{472}{}{Myron! Mel! Quando você vai voltar e ver lil 'ol me?}
{473}{}{My-ron. Myyyyyy-ron.}
{474}{}{Myron, quem é seu amigo fofo?}
{475}{}{Myron, querida! Myron! Você está procurando alguma ação?}
{476}{}{Yoo-hoo! Myron!}
{477}{}{Estive com sua falta, Myron!}
{478}{}{Myron, você é tão sonhador. Bem, tipo de.}
{479}{}{Myron, quando você vai me ver de novo?}
{480}{}{Você pode me dar algum Jet, Myron?}
{481}{}{Quando você vai me arrumar com Jet, Myron?}
{482}{}{Você pode me ajudar a voar, Myron?}

# 11. [PLAYER IS MALE] + [COMPANION: BONE-NOSE]
{483}{}{Meu nome é fácil. O que é seu?}
{484}{}{Precisa de uma pequena empresa?}
{485}{}{Deixe-me ensinar-lhe algumas coisas que uma mulher pode ensinar.}
{486}{}{Precisa de alguém para aquecer sua barraca?}
{487}{}{Precisa de alguém para compartilhar seu bedroll?}
{488}{}{Tem algumas pedras quentes lá, amigo.}
{489}{}{Cobra desagradável de virilha pequena.}
{490}{}{Procurando alguma ação?}
{491}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{492}{}{Procurando uma data?}
{493}{}{Ouvi dizer que havia problemas na linha comercial ...}
{494}{}{À procura de alguma empresa?}
{495}{}{Apenas esportes em Reno hoje em dia no hóquei das tonsilas ...}
{496}{}{Quer dançar?}
{497}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{498}{}{Eu não posso acreditar quantos strippers estavam no Feargus 'despedida de solteiro.}
{499}{}{Novo estranho na cidade, parece ...}
{500}{}{Você pode martelar um pico de seis polegadas através de uma placa com o seu pénis?}
{501}{}{Quer voar?}
{502}{}{Não vi nenhuma caravana da Redding em um tempo.}
{503}{}{Nice aneto.}
{504}{}{Deixe-me te animar, palhaço triste.}
{505}{}{Perder o seu caminho, cowboy?}
{506}{}{Tem uma arma que você precisa descarregar, soldado?}
{507}{}{Esse homem poderia derreter o metal.}
{508}{}{Muitas revólveres nesta cidade, não há fichas suficientes para dar uma volta.}
{509}{}{Eu andei por esta rua desde a noite passada ...}
{510}{}{Precisa de um amigo para a noite? Ou apenas dez minutos?}
{511}{}{Procurando um bom tempo?}
{512}{}{Olhando para ir para a cidade?}
{513}{}{Eu gosto do olhar de seu gecko.}
{514}{}{Que um gecko no seu bolso?}
{515}{}{Você precisa de um guia em torno da cidade, sugah?}
{516}{}{Onde está o fogo?}
{517}{}{Childe, deixe-me fazer de você um homem.}
{518}{}{Às vezes, a forma como as mulheres nesta cidade são projetadas me ofende.}
{519}{}{Queres fingir que somos mortes na temporada de acasalamento?}
{520}{}{Esse homem faz com que meu balcão Geiger marque.}
{521}{}{Se eu tiver que conversar com você depois, isso é extra.}
{522}{}{Qualquer coisa com que eu possa ajudá-lo, estranho?}
{523}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{524}{}{Seu amigo com o osso no nariz ... ótimo truque.}
{525}{}{O seu amigo com o osso faz truques com o nariz ou o sumthin?}
{526}{}{Talvez eu devesse colocar um osso no nariz. Poderia atrair mais clientes do sexo feminino.}
{527}{}{Esse cara tem um osso no nariz do tamanho do meu braço. Keeee-rist.}
{528}{}{Eu nem quero saber como esse menino pegou esse osso no nariz dele.}
{529}{}{Seu amigo está com o osso no nariz no negócio?}
{530}{}{Quanto custa o seu amigo com o osso no nariz?}
{531}{}{Por trinta fichas, posso fazer esse osso no nariz do seu amigo maior.}
{532}{}{Seu amigo com o osso no nariz está compensando por alguma coisa?}
{533}{}{Eu finalmente instaluei essa cabeceira acolchoada.}
{534}{}{Gosto do paraíso? Dez fichas.}
{535}{}{Myron: toda a cera. Sem pavio.}
{536}{}{Myron é um verdadeiro ladrão.}
{537}{}{AC-DC, B n 'D, seja o que for.}
{538}{}{O que ele espera que eu faça, dobre-se por ele?}
{539}{}{Continue pensando que o sinal de Reno vai cair ...}
{540}{}{Aquela bisbilhota é um coelhinho de cama.}
{541}{}{Ela não é Jet dependente, ela é uma dependente de OSS.}
{542}{}{Eu ouvi Vault City tem apenas dois tipos de cidadãos. Talvez tenha sido um acidente de clonagem.}
{543}{}{Senti como se estivesse numa maratona na noite passada ...}
{544}{}{Procurando amor, querido?}
{545}{}{Gostaria que Myron se afastasse. Tão distante.}
{546}{}{Eu posso fazer QUALQUER COISA que você deseja ... pelo preço certo.}
{547}{}{Estou pronto para ir, querida. E quanto a você?}
{548}{}{:: Whistles at you ::}
{549}{}{Odeio boquilhas de chá.}
{550}{}{Faça uma aposta em mim, querida.}
{551}{}{Procurando um bom tempo?}
{552}{}{Amor puro de Reno, aqui mesmo.}
{553}{}{Eu vou te dar um pouco de jogo.}
{554}{}{Eu sou Filthy Spice.}
{555}{}{Eu sou tempero caseiro.}
{556}{}{Eu sou Slutty Spice.}
{557}{}{Eu sou Old Spice.}
{558}{}{Eu sou Sífilis ... er, Slutty Spice.}
{559}{}{Eu sou Dirty Spice.}
{560}{}{Wranglers na poeira, é o que eu quero.}
{561}{}{Tenho uma namorada se quiser um duplo cabeçalho.}
{562}{}{Gostaria que Myron fosse gay.}
{563}{}{Novo sangue na cidade ...}
{564}{}{Ainda não sei porque eles chamam de Virgin Street ...}
{565}{}{Gostaria que ele usasse um saco de papel às vezes ...}
{566}{}{Comprar uma garota com uma bebida?}
{567}{}{Pegue uma senhora solitária na cidade?}
{568}{}{Oh garoto! Um turista!}
{569}{}{Venha aqui, querido, o show está prestes a começar ...}
{570}{}{Ouvi algumas das garotas da parte alta mataram seu cafetão.}
{571}{}{Hellooooostranger.}
{572}{}{Que Jules melhor me deixe em paz.}
{573}{}{Ainda tenho essa hematoma da cabeceira da cama ...}
{574}{}{Esgotado desde a última convenção ...}
{575}{}{Gostaria que aqueles tribais iriam para outra cidade.}
{576}{}{Senti a Terra se mover, mas era apenas o pimentão.}
{577}{}{Me faça derreter.}
{578}{}{Ele continua, ele vai derrubar seu ticker ...}
{579}{}{O zumbido do néon continua me deixando louco ...}
{580}{}{Sou virgem. Eu não sou muito bom nisso.}
{581}{}{Para pensar que eu vim do Den por isso ...}
{582}{}{Ei,stranger! Need a guide?}
{583}{}{Jules continua querendo brindes.}
{584}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{585}{}{As coisas são bastante lentas. Desejo que a caravana mostre.}
{586}{}{Então ele se veste neste traje do Deathclaw, então ...}
{587}{}{Preciso de ajuda para sair desse vestido.}
{588}{}{Feche-me? Então, de novo?}
{589}{}{Mmm-mmm. Parece época de acasalamento.}
{590}{}{Quer perder algum tempo?}
{591}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{592}{}{Eles não me chamam de Lady Lucky por nada.}
{593}{}{Ame esses preservativos com sabor a brahmin.}
{594}{}{Mostre a uma dama um bom momento?}
{595}{}{Gostaria de inventar um placebo sexual para Myron.}
{596}{}{Precisa de um encontro tribal?}
{597}{}{Quer pow-wow, tribal?}
{598}{}{Quer fazer a dança da chuva no meu quarto, tribal?}
{599}{}{Tudo o que você precisa é uma noite comigo.}
{600}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{601}{}{Você pegou as fichas, eu recebi o tempo.}
{602}{}{Pode me ajudar? Estou à procura da minha virgindade perdida.}
{603}{}{Sou virgem, mas preciso do dinheiro.}
{604}{}{Seja gentil, é a minha primeira vez. Hoje.}
{605}{}{Eu tão excitado.}
{606}{}{Você obteve o desejo, recebi a poupança.}
{607}{}{Deixe-me acordar o seu filho interior.}
{608}{}{Quer dançar, querido?}
{609}{}{Olhando para apostar em uma reivindicação?}
{610}{}{Quer me fazer gemer?}
{611}{}{:: Purrrrr ::}
{612}{}{:: Rrrrrowrrr ::}
{613}{}{:: Sopra-te um beijo ::}
{614}{}{Já esteve na última noite ...}
{615}{}{Não sou barato, mas estou especial.}
{616}{}{Acelerar-se custos adicionais.}
{617}{}{Onde eu deixei meu chicote?}
{618}{}{Pronto como um freddie.}
{619}{}{Eu tive que vestir-me como WILMA ontem à noite, Fer Chrissakes.}
{620}{}{Estava com Myron ontem à noite. Por cerca de cinco segundos.}
{621}{}{Procurando por um clipe?}
{622}{}{Gostaria que eles saíssem com alguns óleos de corpo cheiro de jato ...}
{623}{}{Quer ajudar uma virgem a perder a virgindade?}
{624}{}{O meu traseiro vai cair, Myron continua.}
{625}{}{Damn Temperance Union veio de novo ...}
{626}{}{:: Whistles ::}
{627}{}{Morder é extra.}
{628}{}{Garanto que sou melhor do que o anexo do Pip Boy que você usou.}
{629}{}{Quer que eu aperte seus parafusos?}
{630}{}{Prefiro estar com Avellone.}
{631}{}{Eu queria que Nick Kesting estivesse aqui. Poderíamos conversar por horas!}
{632}{}{Nick Kesting é um cara muito legal. Temos excelentes conversas.}
{633}{}{Tommy the Balls é tão sonhador.}
{634}{}{Bem bem. Olha quem acabou de entrar na cidade.}
{635}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{636}{}{Faça uma aposta em mim, querida.}
{637}{}{Meu nome é fácil, garota. O que é seu?}
{638}{}{Ei,cutie. Looking for the other woman?}
{639}{}{Procurando um sabor do outro lado, querido?}
{640}{}{Precisa de uma pequena empresa?}
{641}{}{Menina, deixe-me ensinar-lhe algumas coisas que uma MULHER pode ensinar.}
{642}{}{Precisa de alguém para aquecer sua barraca, garota?}
{643}{}{Precisa de alguém para compartilhar seu bedroll, garota?}
{644}{}{Quer dançar, garota?}
{645}{}{Esqueça as máquinas caça-níqueis, garota. Minha recompensa é muito melhor.}
{646}{}{Menina, você nunca teve amor até que você tivesse amor de Reno.}
{647}{}{Quer voar, garota?}
{648}{}{Perder o seu caminho, vaqueira?}
{649}{}{Tenho uma arma que você precisa descarregar, G.I. Jane?}
{650}{}{À procura de um bom tempo, garota?}
{651}{}{Olhando para ir para a cidade, garota?}
{652}{}{Você precisa de um guia em torno da cidade, sugah?}
{653}{}{Onde está o fogo, garota?}
{654}{}{Essa mulher faz o meu cronô do Geiger marcar.}

# 12. [NO REP]
{655}{}{Meu nome é fácil. O que é seu?}
{656}{}{Precisa de uma pequena empresa?}
{657}{}{Deixe-me ensinar-lhe algumas coisas que uma mulher pode ensinar.}
{658}{}{Precisa de alguém para aquecer sua barraca?}
{659}{}{Precisa de alguém para compartilhar seu bedroll?}
{660}{}{Tem algumas pedras quentes lá, amigo.}
{661}{}{Cobra desagradável de virilha pequena.}
{662}{}{Procurando alguma ação?}
{663}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{664}{}{Procurando uma data?}
{665}{}{Ouvi dizer que havia problemas na linha comercial ...}
{666}{}{À procura de alguma empresa?}
{667}{}{Apenas esportes em Reno hoje em dia no hóquei das tonsilas ...}
{668}{}{Quer dançar?}
{669}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{670}{}{Eu não posso acreditar quantos strippers estavam no Feargus 'despedida de solteiro.}
{671}{}{Novo estranho na cidade, parece ...}
{672}{}{Você pode martelar um pico de seis polegadas através de uma placa com o seu pénis?}
{673}{}{Quer voar?}
{674}{}{Não vi nenhuma caravana da Redding em um tempo...}
{675}{}{Nice aneto.}
{676}{}{Deixe-me te animar, palhaço triste.}
{677}{}{Perder o seu caminho, cowboy?}
{678}{}{Tem uma arma que você precisa descarregar, soldado?}
{679}{}{Esse homem poderia derreter o metal.}
{680}{}{Muitas revólveres nesta cidade, não há fichas suficientes para dar uma volta.}
{681}{}{Estava caminhando nessa rua desde a noite passada ...}
{682}{}{Precisa de um amigo para a noite? Ou apenas dez minutos?}
{683}{}{Procurando um bom tempo?}
{684}{}{Olhando para ir para a cidade?}
{685}{}{Eu gosto do olhar de seu gecko.}
{686}{}{Que um gecko no seu bolso?}
{687}{}{Precisa de um guia em torno da cidade, sugah?}
{688}{}{Onde está o fogo?}
{689}{}{Childe, deixe-me fazer de você um homem.}
{690}{}{Mmmmm-mmmmm.}
{691}{}{Queres fingir que somos mortes na temporada de acasalamento?}
{692}{}{Esse homem faz com que meu balcão Geiger marque.}
{693}{}{Se eu tiver que conversar com você aftewards, isso é extra.}
{694}{}{Qualquer coisa com que eu possa ajudá-lo, estranho?}
{695}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{696}{}{Eu finalmente instaluei essa cabeceira acolchoada.}
{697}{}{O sabor do paraíso custará dez fichas.}
{698}{}{Myron: toda a cera. Sem pavio.}
{699}{}{Myron é um verdadeiro ladrão.}
{700}{}{AC-DC, B n 'D, seja o que for.}
{701}{}{O que ele espera que eu faça, dobre-se por ele?}
{702}{}{Continue pensando que o sinal de Reno vai cair ...}
{703}{}{Aquela bisbilhota é um coelhinho de cama.}
{704}{}{Ela não é Jet dependente, ela é uma dependente de OSS.}
{705}{}{Eu ouvi Vault City tem apenas dois tipos de cidadãos. Talvez tenha sido um acidente de clonagem.}
{706}{}{Senti como se estivesse numa maratona na noite passada ...}
{707}{}{Procurando amor, querido?}
{708}{}{Gostaria que Myron se afastasse. Tão distante.}
{709}{}{Eu posso fazer QUALQUER COISA que você deseja ... pelo preço certo.}
{710}{}{Estou pronto para ir, querida. E quanto a você?}
{711}{}{:: Whistles at you ::}
{712}{}{Odeio boquilhas de chá.}
{713}{}{Faça uma aposta em mim, querida.}
{714}{}{Procurando um bom tempo?}
{715}{}{Amor puro de Reno, aqui mesmo.}
{716}{}{Eu vou te dar um pouco de jogo.}
{717}{}{Eu sou Filthy Spice.}
{718}{}{Eu sou tempero caseiro.}
{719}{}{Eu sou Slutty Spice.}
{720}{}{Eu sou Old Spice.}
{721}{}{Eu sou Sífilis ... er, Slutty Spice.}
{722}{}{Eu sou Dirty Spice.}
{723}{}{Wranglers na poeira, é o que eu quero.}
{724}{}{Tenho uma namorada se quiser um duplo cabeçalho.}
{725}{}{Gostaria que Myron fosse gay.}
{726}{}{Novo sangue na cidade ...}
{727}{}{Ainda não sei porque eles chamam de Virgin Street ...}
{728}{}{Gostaria que ele usasse um saco de papel às vezes ...}
{729}{}{Comprar uma garota com uma bebida?}
{730}{}{Pegue uma senhora solitária na cidade?}
{731}{}{Oh garoto! Um turista!}
{732}{}{Venha aqui, querido, o show está prestes a começar ...}
{733}{}{Ouvi algumas das garotas da parte alta mataram seu cafetão.}
{734}{}{Helloooo, estranho.}
{735}{}{Que Jules melhor me deixe em paz.}
{736}{}{Ainda tenho essa hematoma da cabeceira da cama ...}
{737}{}{Esgotado desde a última convenção ...}
{738}{}{Os tribos do desejo deixariam de chegar aqui.}
{739}{}{Senti a Terra se mover, mas era apenas o pimentão.}
{740}{}{Me faça derreter.}
{741}{}{Ele continua, ele vai derrubar seu ticker ...}
{742}{}{O zumbido do néon está me deixando louco ...}
{743}{}{Sou virgem. Eu não sou muito bom nisso.}
{744}{}{Para pensar que eu vim do Den por isso ...}
{745}{}{Ei,stranger! Need a guide?}
{746}{}{Jules continua querendo brindes.}
{747}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{748}{}{As coisas são bastante lentas. Desejo que a caravana mostre.}
{749}{}{Então ele se veste neste traje do Deathclaw, então ...}
{750}{}{Preciso de ajuda para sair desse vestido.}
{751}{}{Feche-me? Então, de novo?}
{752}{}{Mmm-mmm. Parece época de acasalamento.}
{753}{}{Quer perder algum tempo?}
{754}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{755}{}{Eles não me chamam de Lady Lucky por nada.}
{756}{}{Ame esses preservativos com sabor a brahmin.}
{757}{}{Mostre a uma dama um bom momento?}
{758}{}{Gostaria de inventar um placebo sexual para Myron.}
{759}{}{Precisa de um encontro tribal?}
{760}{}{Quer pow-wow, tribal?}
{761}{}{Quer fazer a dança da chuva no meu quarto, tribal?}
{762}{}{Tudo o que você precisa é uma noite comigo.}
{763}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{764}{}{Você pegou as fichas, eu recebi o tempo.}
{765}{}{Pode me ajudar? Estou à procura da minha virgindade perdida.}
{766}{}{Sou virgem, mas preciso do dinheiro.}
{767}{}{Seja gentil, é a minha primeira vez. Hoje.}
{768}{}{Eu tão excitado.}
{769}{}{Você obteve o desejo, recebi a poupança.}
{770}{}{Deixe-me acordar o seu filho interior.}
{771}{}{Quer dançar, querido?}
{772}{}{Olhando para apostar em uma reivindicação?}
{773}{}{Quer me fazer gemer?}
{774}{}{:: Purrrrr ::}
{775}{}{:: Rrrrrowrrr ::}
{776}{}{:: Sopra-te um beijo ::}
{777}{}{Já esteve na última noite ...}
{778}{}{Não sou barato, mas estou especial.}
{779}{}{Acelerar-se custos adicionais.}
{780}{}{Onde eu deixei meu chicote?}
{781}{}{Pronto como um freddie.}
{782}{}{Eu tive que vestir-me como WILMA ontem à noite, Fer Chrissakes.}
{783}{}{Estava com Myron ontem à noite. Por cerca de cinco segundos.}
{784}{}{Procurando por um clipe?}
{785}{}{Gostaria que eles saíssem com alguns óleos de corpo cheiro de jato ...}
{786}{}{Quer ajudar uma virgem a perder a virgindade?}
{787}{}{O meu traseiro vai cair, Myron continua.}
{788}{}{Damn Temperance Union veio de novo ...}
{789}{}{:: Whistles ::}
{790}{}{Morder é extra.}
{791}{}{Garanto que sou melhor do que o anexo do Pip Boy que você usou.}
{792}{}{Quer que eu aperte seus parafusos?}
{793}{}{Prefiro estar com Avellone.}
{794}{}{Eu queria que Nick Kesting estivesse aqui. Poderíamos conversar por horas!}
{795}{}{Nick Kesting é um cara muito legal. Temos excelentes conversas.}
{796}{}{Tommy the Balls é tão sonhador.}
{797}{}{Bem bem. Olha quem acabou de entrar na cidade ...}
{798}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{799}{}{Faça uma aposta em mim, querida.}
{800}{}{Meu nome é fácil, garota. O que é seu?}
{801}{}{Ei,cutie. Looking for the other woman?}
{802}{}{Procurando um sabor do outro lado, querido?}
{803}{}{Precisa de uma pequena empresa?}
{804}{}{Menina, deixe-me ensinar-lhe algumas coisas que uma MULHER pode ensinar.}
{805}{}{Precisa de alguém para aquecer sua barraca, garota?}
{806}{}{Precisa de alguém para compartilhar seu bedroll, garota?}
{807}{}{Quer dançar, garota?}
{808}{}{Esqueça as máquinas caça-níqueis, garota. Minha recompensa é muito melhor.}
{809}{}{Menina, você nunca teve amor até que você tivesse amor de Reno.}
{810}{}{Quer voar, garota?}
{811}{}{Perder o seu caminho, vaqueira?}
{812}{}{Tenho uma arma que você precisa descarregar, G.I. Jane?}
{813}{}{À procura de um bom tempo, garota?}
{814}{}{Olhando para ir para a cidade, garota?}
{815}{}{Precisa de um guia em torno da cidade, sugah?}
{816}{}{Onde está o fogo, garota?}
{817}{}{Essa mulher faz o meu cronô do Geiger marcar.}

# 13. [ENCLAVE DESTROYED]
{818}{}{O Enclave? Presidente? Conte-me toda a história.}
{819}{}{Tom French me escreveu. Ele tem mãos suaves e suaves.}
{820}{}{Eles ainda estavam lutando contra a GUERRA? Mesmo! Bom, você desperdiçou esses bastardos.}
{821}{}{Você é um maldito total. Quero dizer, você começa a partir de uma simples tribuna
 - sem ofensa - e vá para salvar o mundo inteiro. Você chuta o traseiro. Fim da história.}
{822}{}{Você deve repetir o jogo como um tipo diferente de personagem.}
{823}{}{Conte-me tudo sobre sua luta com o Enclave ...}
{824}{}{Ei,if you want a freebie after saving the world, I'm sure you can talk me into it...}
{825}{}{Eu não sei como você sobreviveu aos bastardos do Enclave, mas você é a pessoa mais corajosa que eu tenho
 Sempre conhecido.}
{826}{}{Tim Cain? Sim, ele é um dos meus regulares.}
{827}{}{Beije-me, seu animal que encerra o Enclave.}
{828}{}{Ouço que os Irmãos estão procurando por você. Eles querem fazer um filme baseado em sua aventura.}
{829}{}{Nós sentimos falta de Tim Cain. Ele costumava cozinhar pão maravilhoso. Então ele nos espancaria como crianças pequenas.}
{830}{}{Eu percebi que sou apenas um NPC, mas estou profundamente ofendido pela forma como as mulheres são retratadas em New Reno.}
{831}{}{As mulheres nesta cidade parecem que foram projetadas por algum geek imaturo
 Que vive no porão de seus pais.}
{832}{}{O novo Reno foi desenhado por Chris Avellone e Tom French. Ambos são deuses do sexo feminino.}
{833}{}{Feargus ficou com um olhar franzido em seu rosto quando viu quantas mensagens de texto flutuantes eu tenho.
 Ele é um gatinho azedo.}
{834}{}{Você pontua é 192 de 208. Você realmente deveria ter usado o dedo mordido no Horrigan.}

# 14. [POWER ARMOR]
{835}{}{Alguma mulher deve ter quebrado seu coração terrivelmente por você ter recuado dentro desse terno blindado. Deixa-me ajudar.}
{836}{}{Olhe, Tin Man, se você quiser me vestir como Dorothy ou Toto, isso é extra.}
{837}{}{Olha, amigo, se você quer fazer isso, você terá que sair daqui; O metal machuca e deixa cicatrizes.}
{838}{}{Existe um alçapão, ou você tem que sair dessa coisa para conseguir um trabalho manual?}
{839}{}{Se você tiver uma ereção naquela coisa, você se machuca?}
{840}{}{Parece que você trouxe seu próprio preservativo.}
{841}{}{Isso é um novo preservativo do corpo?}
{842}{}{Você deve realmente ter medo de STDs para estar nessa coisa.}
{843}{}{Se você quiser que eu faça sexo com você nessa coisa, isso é extra.}
{844}{}{Se quiser continuar, você terá que sair daqui.}
{845}{}{Será que a minha umidade irá ferrugem?}
{846}{}{Bem ... ok. Mas, de nenhuma maneira no INFERNO, você estará no topo.}
{847}{}{Como você vai ao banheiro com essa coisa?}
{848}{}{Eu vou precisar do Jaws of Life para fazer você sair daqui?}
{849}{}{Isso é um novo tipo de vibrador?}
{850}{}{Acho que vi essa mesma situação em um vídeo Anime uma vez.}
{851}{}{Tem certeza de que não está procurando uma lavagem de carro?}
{852}{}{Olha, querido, você terá que sair daqui; O metal machuca e deixa cicatrizes.}
{853}{}{É algum novo dispositivo de controle de nascimento que você está vestindo?}

# 15. [FEMALE, PRIZEFIGHTER]
{854}{}{Quer brincar no ringue comigo, querido? Eu posso durar pelo menos 12 rodadas.}
{855}{}{Wanna box,}
{856}{}{Menina, você é tão malvado.}
{857}{}{Uau, olhe para seus músculos. Você é mais difícil do que muitos homens que conheço. E eu conheço muitos homens.}
{858}{}{Como tá indo,}
{859}{}{Procurando por mim?}
{860}{}{Por que você não vem mais frequentemente?}
{861}{}{Precisa de alguma empresa,}
{862}{}{Você conseguiu um rack agradável.}
{863}{}{Ei ... cuidado com o Masticador. Ele é um verdadeiro idiota. Ele tentou morder minha orelha uma vez.}
{864}{}{Você é muito sexy, garota, sabe disso?}

# 16. [MADE MAN]
{865}{}{}
{866}{}{Se você está procurando uma pequena empresa mais tarde ...}
{867}{}{}
{868}{}{Olá,}
{869}{}{Dê uma boa palavra com o chefe para mim?}
{870}{}{Bem, se não é o diabólico}
{871}{}{Eu posso fazer QUALQUER COISA que você quiser ... é tudo para pedir.}
{872}{}{Dê uma boa palavra com o chefe para mim?}
{873}{}{}
{874}{}{Um, se você está procurando por uma pequena empresa mais tarde, senhora ...}

# 17. [SLAVER]
{875}{}{Meu nome é fácil, escravidão. O que é seu?}
{876}{}{Precisa de alguém para arrancar sua coleira, escravidão?}
{877}{}{Por que você não me leva de volta para sua gaiola, escravidão?}
{878}{}{Precisa de sua gaiola rattled, slaver?}
{879}{}{Você é um escravidente frisky, não é?}
{880}{}{Você trouxe sua própria towelette?}
{881}{}{Sim, eles são reais, e NÃO, você não pode verificar.}
{882}{}{Quer discutir, cowboy?}
{883}{}{Quer me afundar com seu torpedo rosa?}
{884}{}{Deixe-me ensinar-lhe algumas coisas que uma mulher pode ensinar.}
{885}{}{Precisa de alguém para aquecer sua barraca, escravidão?}
{886}{}{Precisa de alguém para compartilhar seu bedroll, slaver?}
{887}{}{Tem algumas pedras quentes lá, escravas.}
{888}{}{Cobra desagradável de virilha pequena que você chegou lá, escravidão.}
{889}{}{Procurando alguma ação?}
{890}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{891}{}{Procurando uma data?}
{892}{}{Olhe, não há amostras grátis.}
{893}{}{Ouvi dizer que havia problemas na linha comercial ...}
{894}{}{À procura de alguma empresa?}
{895}{}{Apenas esportes em Reno hoje em dia no hóquei das tonsilas ...}
{896}{}{Quer dançar, escravidão?}
{897}{}{Slaver, você nunca teve amor até que você tivesse amor de Reno.}
{898}{}{Eu não posso acreditar quantos strippers estavam no Feargus 'despedida de solteiro.}
{899}{}{Meu trabalho? Eu giro os meninos para HOMENS.}
{900}{}{Você pode martelar um pico de seis polegadas através de uma placa com o seu pénis?}
{901}{}{Estive nesta cidade por muito tempo ...}
{902}{}{Precisa de um amigo para a noite, slaver? Ou apenas dez minutos?}
{903}{}{Quer voar?}
{904}{}{Não vi nenhuma caravana da Redding em um tempo...}
{905}{}{Nice aneto.}
{906}{}{Perder o seu caminho, escravidão?}
{907}{}{Tem uma arma que você precisa para descarregar, escravidão?}
{908}{}{Qualquer coisa com que eu possa ajudá-lo, estranho?}
{909}{}{Eu gosto do olhar de seu gecko, escravo.}
{910}{}{Que um gecko no seu bolso?}
{911}{}{Precisa de um guia em torno da cidade, sugah?}
{912}{}{Onde está o fogo, o escravidão?}
{913}{}{Childe, deixe-me fazer de você um homem.}
{914}{}{Quer dançar, escravidão?}
{915}{}{Olá, Sr. Tyler. Indo ... para baixo?}
{916}{}{Se eu tiver que conversar com você depois, isso é extra.}
{917}{}{Sim, eles são reais, e NÃO, você não pode verificar.}
{918}{}{Esse cara, Fred Hatch, queria saber se havia "grandes garotas" na cidade. Esquisito.}
{919}{}{[Canta.] "Vamos jogar - mestre e servo. Vamos jogar - mestre e servo".}
{920}{}{Quer jogar mestre e servo, escravidão?}
{921}{}{Se você quiser que eu fique acordado depois, isso é extra.}
{922}{}{Quer ir para onde estão as coisas selvagens?}
{923}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{924}{}{Não sou barato, mas estou especial.}
{925}{}{Eu vou te encaixar como um smoking de carne.}
{926}{}{Fale sobre mudflaps, baby, eu os peguei.}
{927}{}{Bem bem. Olha quem acabou de entrar na cidade ...}
{928}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{929}{}{Procurando alguma ação?}
{930}{}{Em caso de dúvida, chicoteie-o.}
{931}{}{Eu finalmente instaluei essa cabeceira acolchoada.}
{932}{}{O sabor do paraíso custará dez fichas.}
{933}{}{Myron: toda a cera. Sem pavio.}
{934}{}{Myron é um verdadeiro ladrão.}
{935}{}{AC-DC, B n 'D, seja o que for.}
{936}{}{Aquela bisbilhota é um coelhinho de cama.}
{937}{}{Ela não é Jet dependente, ela é uma dependente de OSS.}
{938}{}{Eu ouvi Vault City tem apenas dois tipos de cidadãos. Talvez tenha sido um acidente de clonagem.}
{939}{}{Senti como se estivesse numa maratona na noite passada ...}
{940}{}{Procurando amor, querido?}
{941}{}{Não beijos. É a regra.}
{942}{}{Gostaria que Myron se afastasse. Tão distante.}
{943}{}{Eu posso fazer QUALQUER COISA que você quer, escravidão ... pelo preço certo.}
{944}{}{Estou pronto para ir, querida. E quanto a você?}
{945}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{946}{}{Odeio boquilhas de chá.}
{947}{}{Faça uma aposta em mim, escravidão.}
{948}{}{Procurando um bom tempo?}
{949}{}{Amor puro de Reno, aqui mesmo.}
{950}{}{Eu vou te dar um pouco de jogo.}
{951}{}{Eu sou Filthy Spice.}
{952}{}{Eu sou tempero caseiro.}
{953}{}{Eu sou Slutty Spice.}
{954}{}{Eu sou Old Spice.}
{955}{}{Eu sou Sífilis ... er, Slutty Spice.}
{956}{}{Eu sou Dirty Spice.}
{957}{}{Say...Tenho uma namorada se quiser um duplo cabeçalho.}
{958}{}{Gostaria que Myron fosse gay.}
{959}{}{Ainda não sei porque eles chamam de Virgin Street ...}
{960}{}{Gostaria que ele usasse um saco de papel às vezes.}
{961}{}{Compre-me uma bebida, escravidão?}
{962}{}{Pegue uma senhora solitária na cidade, escravidão?}
{963}{}{Uh, claro, sou uma mulher. Apenas ignore a maçã de Adão.}
{964}{}{Ouvi algumas das garotas da parte alta mataram seu cafetão.}
{965}{}{Helloooo, estranho.}
{966}{}{Que Jules melhor me deixe em paz.}
{967}{}{Ainda tenho essa hematoma da cabeceira da cama ...}
{968}{}{Esgotado desde a última convenção do escravidão.}
{969}{}{Gostaria que Gen Con tivesse lugar em alguma outra cidade.}
{970}{}{Você poderia derreter o metal, você sabe disso?}
{971}{}{Senti a Terra se mover, mas era apenas o pimentão.}
{972}{}{Me faça derreter.}
{973}{}{Sou virgem. Eu não sou muito bom nisso.}
{974}{}{Precisa de um guia em torno da cidade, slaver?}
{975}{}{Uau. Isso vai custar extra.}
{976}{}{Jules continua querendo brindes.}
{977}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{978}{}{As coisas são bastante lentas. Desejo que a caravana mostre.}
{979}{}{Então ele se veste neste traje do Deathclaw, então ...}
{980}{}{Preciso de ajuda para sair desse vestido.}
{981}{}{Feche-me? Então, de novo?}
{982}{}{Desculpe, o que você estava dizendo? Eu estava muito ocupado olhando sua bunda.}
{983}{}{Quer perder algum tempo?}
{984}{}{Procurando um bom tempo?}
{985}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{986}{}{Olhando para ir para a cidade?}
{987}{}{Eles não me chamam de Lady Lucky por nada.}
{988}{}{DE CURSO Eu amo esses preservativos com sabor a brahmin. Yum.}
{989}{}{Mostre a uma senhora um bom tempo, escravidão?}
{990}{}{Gostaria de inventar um placebo sexual para Myron.}
{991}{}{Precisa de uma data, escravidão?}
{992}{}{Slaver, tudo que você precisa é uma noite comigo.}
{993}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{994}{}{Você obteve as fichas, o escravo, eu consegui o tempo.}
{995}{}{Pode me ajudar? Estou à procura da minha virgindade perdida.}
{996}{}{Sou virgem, mas preciso do dinheiro.}
{997}{}{Seja gentil, é a minha primeira vez. Hoje.}
{998}{}{Eu tão excitado.}
{999}{}{Você obteve o desejo, recebi a poupança.}
{1000}{}{Deixe-me acordar o seu filho interior.}
{1001}{}{Estou apenas fazendo isso para pagar a faculdade.}
{1002}{}{Olhe, pela última vez, não quero me vestir como o "Vault Dweller".}
{1003}{}{Olhando para apostar em uma reivindicação?}
{1004}{}{Quer me fazer gemer?}
{1005}{}{:: Purrrrr ::}
{1006}{}{:: Rrrrrowrrr ::}
{1007}{}{Pare de me fazer cócegas.}
{1008}{}{Já esteve na última noite ...}
{1009}{}{Queres fingir que somos mortes na temporada de acasalamento?}
{1010}{}{Não sou barato, mas estou especial.}
{1011}{}{Acelerar-se custos adicionais.}
{1012}{}{Onde eu deixei meu chicote?}
{1013}{}{Pronto como um freddie.}
{1014}{}{Eu tive que vestir-me como WILMA ontem à noite, Fer Chrissakes.}
{1015}{}{Estava com Myron ontem à noite. Por cerca de cinco segundos.}
{1016}{}{Procurando por um clipe?}
{1017}{}{Gostaria que eles saíssem com alguns óleos de corpo cheiro de jato ...}
{1018}{}{Quer ajudar uma virgem a perder a virgindade?}
{1019}{}{O meu traseiro vai cair, Myron continua.}
{1020}{}{Damn Temperance Union veio de novo ...}
{1021}{}{Você faz meu balcão Geiger marcar.}
{1022}{}{:: Whistles ::}
{1023}{}{Morder é extra.}
{1024}{}{Garanto que sou melhor do que o anexo do Pip Boy que você usou.}
{1025}{}{Quer que eu aperte seus parafusos?}
{1026}{}{Prefiro estar com Avellone.}
{1027}{}{Eu queria que Nick Kesting estivesse aqui. Poderíamos conversar por horas!}
{1028}{}{Nick Kesting é um cara muito legal. Temos excelentes conversas.}
{1029}{}{Tommy the Balls é tão sonhador.}
{1030}{}{Preciso de cinquenta dólares para fazer você gritar.}
{1031}{}{Meu nome é fácil, escrava-garota. O que é seu?}
{1032}{}{Precisa de alguém para arrancar sua coleira, escrava-menina?}
{1033}{}{Por que você não me leva de volta para sua gaiola, escrava-menina?}
{1034}{}{Ei,slaver. Looking for the other woman?}
{1035}{}{Procurando um sabor do outro lado, querido?}
{1036}{}{Precisa de sua gaiola chateada, escrava-garota?}
{1037}{}{Sentindo-se experimental, escrava-menina? Prove-o.}
{1038}{}{Quer dar um passeio no lado selvagem, escravidão?}
{1039}{}{Precisa de alguém para compartilhar sua tenda, escrava-menina?}
{1040}{}{Precisa de alguém para compartilhar seu bedroll, slaver-girl?}
{1041}{}{Tem algumas curvas agradáveis   lá, escrava-menina.}
{1042}{}{Quer dançar, escrava-menina?}
{1043}{}{Slaver-girl, você nunca teve amor até que você tivesse amor de Reno.}
{1044}{}{Meu trabalho? Eu gire os meninos para homens *. Eu realmente não sei o que eu invoco mulheres, mas eu gostaria de descobrir.}
{1045}{}{Perder o seu caminho, escravidão-menina?}
{1046}{}{À procura de um bom tempo, escrava-menina?}
{1047}{}{Precisa de uma data, escrava-menina?}
{1048}{}{Onde está o fogo, escrava-menina?}
{1049}{}{Você faz meu balcão Geiger, garoto-escravo.}

# 18. [BONENOSE]
{1050}{}{Meu nome é fácil. O que é seu?}
{1051}{}{Um pouco frisky, hein?}
{1052}{}{Você trouxe sua própria towelette?}
{1053}{}{Sim, eles são reais.}
{1054}{}{Sim, eles são reais, e NÃO, você não pode verificar.}
{1055}{}{Piss off, ass-for-brains.}
{1056}{}{Quer discutir, cowboy?}
{1057}{}{Quer me afundar com seu torpedo rosa?}
{1058}{}{Precisa de alguém para aquecer sua barraca?}
{1059}{}{Precisa de alguém para compartilhar seu bedroll?}
{1060}{}{Tem algumas pedras quentes lá, amigo.}
{1061}{}{Cobra desagradável de virilha pequena.}
{1062}{}{Procurando alguma ação?}
{1063}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{1064}{}{Procurando uma data?}
{1065}{}{Olhe, não há amostras grátis.}
{1066}{}{Ouvi dizer que havia problemas na linha comercial ...}
{1067}{}{À procura de alguma empresa?}
{1068}{}{Apenas esportes em Reno hoje em dia no hóquei das tonsilas ...}
{1069}{}{Quer dançar?}
{1070}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{1071}{}{Meu trabalho? Eu giro os meninos para HOMENS.}
{1072}{}{Você pode martelar um pico de seis polegadas através de uma placa com o seu pénis?}
{1073}{}{Estava caminhando nessa rua desde a noite passada ...}
{1074}{}{Precisa de um amigo para a noite? Ou apenas dez minutos?}
{1075}{}{Quer voar?}
{1076}{}{Não vi nenhuma caravana da Redding em um tempo...}
{1077}{}{Nice aneto.}
{1078}{}{Perder o seu caminho, cowboy?}
{1079}{}{Tem uma arma que você precisa descarregar, soldado?}
{1080}{}{Qualquer coisa com que eu possa ajudá-lo, estranho?}
{1081}{}{Procurando um bom tempo?}
{1082}{}{Olhando para ir para a cidade?}
{1083}{}{Eu gosto do olhar de seu gecko.}
{1084}{}{Que um gecko no seu bolso?}
{1085}{}{Você precisa de um guia em torno da cidade, sugah?}
{1086}{}{Onde está o fogo?}
{1087}{}{Você conseguiu o dinheiro, eu consegui o tempo.}
{1088}{}{Childe, deixe-me fazer de você um homem.}
{1089}{}{Olá, Sr. Tyler. Indo ... para baixo?}
{1090}{}{Se eu tiver que conversar com você depois, isso é extra.}
{1091}{}{Esse cara, Fred Hatch, queria saber se havia "grandes garotas" na cidade. Esquisito.}
{1092}{}{Seu amigo com o osso no nariz ... ótimo truque.}
{1093}{}{O seu amigo com o osso faz truques com o nariz ou o sumthin?}
{1094}{}{Talvez eu devesse colocar um osso no nariz. Poderia atrair mais clientes do sexo feminino.}
{1095}{}{Esse cara tem um osso no nariz do tamanho do meu braço. Keeee-rist.}
{1096}{}{Eu nem quero saber como esse menino pegou esse osso no nariz dele.}
{1097}{}{Seu amigo está com o osso no nariz no negócio?}
{1098}{}{Quanto custa o seu amigo com o osso no nariz?}
{1099}{}{Por trinta fichas, posso fazer esse osso no nariz do seu amigo maior.}
{1100}{}{Seu amigo com o osso no nariz está compensando por alguma coisa?}
{1101}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{1102}{}{Procurando alguma ação?}
{1103}{}{Em caso de dúvida, chicoteie-o.}
{1104}{}{Deixe-me ensinar-lhe algumas coisas que uma mulher pode ensinar.}
{1105}{}{Eu finalmente instaluei essa cabeceira acolchoada.}
{1106}{}{O sabor do paraíso custará dez fichas.}
{1107}{}{Myron: toda a cera. Sem pavio.}
{1108}{}{Myron é um verdadeiro ladrão.}
{1109}{}{AC-DC, B n 'D, seja o que for.}
{1110}{}{Aquela bisbilhota é um coelhinho de cama.}
{1111}{}{Ela não é Jet dependente, ela é uma dependente de OSS.}
{1112}{}{Eu ouvi Vault City tem apenas dois tipos de cidadãos. Talvez tenha sido um acidente de clonagem.}
{1113}{}{Senti como se estivesse numa maratona na noite passada ...}
{1114}{}{Procurando amor, querido?}
{1115}{}{Não beijos. É a regra.}
{1116}{}{Gostaria que Myron se afastasse. Tão distante.}
{1117}{}{Eu posso fazer QUALQUER COISA que você deseja ... pelo preço certo.}
{1118}{}{Estou pronto para ir, querida. E quanto a você?}
{1119}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{1120}{}{Odeio boquilhas de chá.}
{1121}{}{Faça uma aposta em mim, querida.}
{1122}{}{Procurando um bom tempo?}
{1123}{}{Eu não posso acreditar quantos strippers estavam no Feargus 'despedida de solteiro.}
{1124}{}{Amor puro de Reno, aqui mesmo.}
{1125}{}{Eu vou te dar um pouco de jogo.}
{1126}{}{Eu sou Filthy Spice.}
{1127}{}{Eu sou tempero caseiro.}
{1128}{}{Eu sou Old Spice.}
{1129}{}{Eu sou Slutty Spice.}
{1130}{}{Eu sou Sífilis ... er, Slutty Spice.}
{1131}{}{Eu sou Dirty Spice.}
{1132}{}{Tenho uma namorada se quiser um duplo cabeçalho.}
{1133}{}{Gostaria que Myron fosse gay.}
{1134}{}{Ainda não sei porque eles chamam de Virgin Street ...}
{1135}{}{Gostaria que ele usasse um saco de papel às vezes.}
{1136}{}{Comprar uma bebida?}
{1137}{}{Pegue uma senhora solitária na cidade?}
{1138}{}{Uh, claro, sou uma mulher. Apenas ignore a maçã de Adão.}
{1139}{}{Ouvi algumas das garotas da parte alta mataram seu cafetão.}
{1140}{}{Helloooo, estranho.}
{1141}{}{Que Jules melhor me deixe em paz.}
{1142}{}{Ainda tenho essa hematoma da cabeceira da cama ...}
{1143}{}{Esgotado desde a última convenção ...}
{1144}{}{Gostaria que Gen Con tivesse lugar em alguma outra cidade.}
{1145}{}{Você poderia derreter o metal, você sabe disso?}
{1146}{}{Senti a Terra se mover, mas era apenas o pimentão.}
{1147}{}{Me faça derreter.}
{1148}{}{Sou virgem. Eu não sou muito bom nisso.}
{1149}{}{Precisa de um guia em torno da cidade?}
{1150}{}{* Whoa. * Isso vai custar extra.}
{1151}{}{Jules continua querendo brindes.}
{1152}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{1153}{}{As coisas são bastante lentas. Desejo que a caravana mostre.}
{1154}{}{Então ele se veste neste traje do Deathclaw, então ...}
{1155}{}{Preciso de ajuda para sair desse vestido.}
{1156}{}{Feche-me? Então, de novo?}
{1157}{}{Desculpe, o que você estava dizendo? Eu estava muito ocupado olhando sua bunda.}
{1158}{}{Quer perder algum tempo?}
{1159}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{1160}{}{Eles não me chamam de Lady Lucky por nada.}
{1161}{}{De * curso * Eu amo esses preservativos com sabor a brahmin. Yum.}
{1162}{}{Mostre a uma dama um bom momento?}
{1163}{}{Gostaria de inventar um placebo sexual para Myron.}
{1164}{}{Precisa de um encontro tribal?}
{1165}{}{Quer pow-wow, tribal?}
{1166}{}{Quer fazer a dança da chuva no meu quarto, tribal?}
{1167}{}{Tudo o que você precisa é uma noite comigo.}
{1168}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{1169}{}{Pode me ajudar? Estou à procura da minha virgindade perdida.}
{1170}{}{Sou virgem, mas preciso do dinheiro.}
{1171}{}{Seja gentil, é a minha primeira vez. Hoje.}
{1172}{}{Eu tão excitado.}
{1173}{}{Você obteve o desejo, recebi a poupança.}
{1174}{}{Deixe-me acordar o seu filho interior.}
{1175}{}{Estou apenas fazendo isso para pagar a faculdade.}
{1176}{}{Quer dançar, querido?}
{1177}{}{Olhe, pela última vez, não vou me vestir como o "Vault Dweller".}
{1178}{}{Olhando para apostar em uma reivindicação?}
{1179}{}{Quer me fazer gemer?}
{1180}{}{:: Purrrrr ::}
{1181}{}{:: Rrrrrowrrr ::}
{1182}{}{Pare de me fazer cócegas.}
{1183}{}{Já esteve na última noite ...}
{1184}{}{Queres fingir que somos mortes na temporada de acasalamento?}
{1185}{}{Não sou barato, mas estou especial.}
{1186}{}{Acelerar-se custos adicionais.}
{1187}{}{Onde eu deixei meu chicote?}
{1188}{}{Pronto como um freddie.}
{1189}{}{Eu tive que vestir-me como WILMA ontem à noite, Fer Chrissakes.}
{1190}{}{Estava com Myron ontem à noite. Por cerca de cinco segundos.}
{1191}{}{Procurando por um clipe?}
{1192}{}{Gostaria que eles saíssem com alguns óleos de corpo cheiro de jato ...}
{1193}{}{Quer ajudar uma virgem a perder a virgindade?}
{1194}{}{O meu traseiro vai cair, Myron continua.}
{1195}{}{Damn Temperance Union veio de novo ...}
{1196}{}{Você faz meu balcão Geiger marcar.}
{1197}{}{:: Whistles ::}
{1198}{}{Morder é extra.}
{1199}{}{Garanto que sou melhor do que o anexo do Pip Boy que você usou.}
{1200}{}{Quer que eu aperte seus parafusos?}
{1201}{}{Prefiro estar com Avellone.}
{1202}{}{Eu queria que Nick Kesting estivesse aqui. Poderíamos conversar por horas!}
{1203}{}{Nick Kesting é um cara muito legal. Temos excelentes conversas.}
{1204}{}{Tommy the Balls é tão sonhador.}
{1205}{}{Preciso de cinquenta dólares para fazer você gritar.}
{1206}{}{Meu nome é fácil, garota. O que é seu?}
{1207}{}{Ei,cutie. Looking for the other woman?}
{1208}{}{Procurando um sabor do outro lado, querido?}
{1209}{}{Precisa de uma pequena empresa?}
{1210}{}{Menina, deixe-me ensinar-lhe algumas coisas que uma MULHER pode ensinar.}
{1211}{}{Precisa de alguém para aquecer sua barraca, querida?}
{1212}{}{Precisa de alguém para compartilhar seu bedroll, querido?}
{1213}{}{Quer dançar, garota?}
{1214}{}{Menina, você nunca teve amor até que você tivesse amor de Reno.}
{1215}{}{Quer voar, garota?}
{1216}{}{Perder o seu caminho, vaqueira?}
{1217}{}{Ei, G.I. Jane.}
{1218}{}{À procura de um bom tempo, garota?}
{1219}{}{Olhando para ir para a cidade, garota?}
{1220}{}{Você precisa de um guia em torno da cidade, sugah?}
{1221}{}{Onde está o fogo, garota?}
{1222}{}{Você pegou as fichas, menina, eu consegui o tempo.}

# 19. [NO REP]
{1223}{}{Meu nome é fácil. O que é seu?}
{1224}{}{Um pouco frisky, hein?}
{1225}{}{Você trouxe sua própria towelette?}
{1226}{}{Sim, eles são reais.}
{1227}{}{Sim, eles são reais, e NÃO, você não pode verificar.}
{1228}{}{Piss off, ass-for-brains.}
{1229}{}{Quer discutir, cowboy?}
{1230}{}{Quer me afundar com seu torpedo rosa?}
{1231}{}{Precisa de alguém para aquecer sua barraca?}
{1232}{}{Precisa de alguém para compartilhar seu bedroll?}
{1233}{}{Tem algumas pedras quentes lá, amigo.}
{1234}{}{Cobra desagradável de virilha pequena.}
{1235}{}{Procurando alguma ação?}
{1236}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{1237}{}{Procurando uma data?}
{1238}{}{Olha, não dou amostras grátis.}
{1239}{}{Ouvi dizer que houve problemas em Commercial Row ...}
{1240}{}{À procura de alguma empresa?}
{1241}{}{Apenas esportes em Reno hoje em dia no hóquei das tonsilas ...}
{1242}{}{Quer dançar?}
{1243}{}{Você nunca teve amor até que você tivesse amor de Reno.}
{1244}{}{Meu trabalho? Eu giro os meninos para HOMENS.}
{1245}{}{Você pode martelar um pico de seis polegadas através de uma placa com o seu pénis?}
{1246}{}{Estava caminhando nessa rua desde a noite passada ...}
{1247}{}{Precisa de um amigo para a noite? Ou apenas dez minutos?}
{1248}{}{Quer voar?}
{1249}{}{Não vi nenhuma caravana da Redding em um tempo...}
{1250}{}{Nice aneto.}
{1251}{}{Perder o seu caminho, cowboy?}
{1252}{}{Tem uma arma que você precisa descarregar, soldado?}
{1253}{}{Qualquer coisa com que eu possa ajudá-lo, estranho?}
{1254}{}{Procurando um bom tempo?}
{1255}{}{Olhando para ir para a cidade?}
{1256}{}{Eu gosto do olhar de seu gecko.}
{1257}{}{Que um gecko no seu bolso?}
{1258}{}{Você precisa de um guia em torno da cidade, sugah?}
{1259}{}{Onde está o fogo?}
{1260}{}{Você pegou as fichas, eu recebi o tempo.}
{1261}{}{Childe, deixe-me fazer de você um homem.}
{1262}{}{Olá, Sr. Tyler. Indo ... para baixo?}
{1263}{}{Se eu tiver que conversar com você depois, isso é extra.}
{1264}{}{Esse cara, Fred Hatch, queria saber se havia "grandes garotas" na cidade. Esquisito.}
{1265}{}{Se você quer que eu fique acordado depois do sexo, isso é extra.}
{1266}{}{Quer ir para onde estão as coisas selvagens?}
{1267}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{1268}{}{Não sou barato, mas estou especial.}
{1269}{}{Ei, querida.}
{1270}{}{Quer ardente?}
{1271}{}{Eu vou te encaixar como um smoking de carne.}
{1272}{}{Fale sobre mudflaps, baby, eu os peguei.}
{1273}{}{Bem bem. Olha quem acabou de entrar na cidade ...}
{1274}{}{Procurando pelo Jardim do Éden? Venha para o meu quarto.}
{1275}{}{Procurando alguma ação?}
{1276}{}{Em caso de dúvida, chicoteie-o.}
{1277}{}{Deixe-me ensinar-lhe algumas coisas que uma mulher pode ensinar.}
{1278}{}{Eu finalmente instaluei essa cabeceira acolchoada.}
{1279}{}{O sabor do paraíso custará dez fichas.}
{1280}{}{Myron: toda a cera. Sem pavio.}
{1281}{}{Myron é um verdadeiro ladrão.}
{1282}{}{AC-DC, B n 'D, seja o que for.}
{1283}{}{Aquela bisbilhota é um coelhinho de cama.}
{1284}{}{Ela não é Jet dependente, ela é uma dependente de OSS.}
{1285}{}{Eu ouvi Vault City tem apenas dois tipos de cidadãos. Talvez tenha sido um acidente de clonagem.}
{1286}{}{Senti como se estivesse numa maratona na noite passada ...}
{1287}{}{Procurando amor, querido?}
{1288}{}{Não beijos. É a regra.}
{1289}{}{Gostaria que Myron se afastasse. Tão distante.}
{1290}{}{Eu posso fazer QUALQUER COISA que você deseja ... pelo preço certo.}
{1291}{}{Estou pronto para ir, querida. E quanto a você?}
{1292}{}{Esqueça as máquinas caça-níqueis. Minha recompensa é muito melhor.}
{1293}{}{Odeio boquilhas de chá.}
{1294}{}{Faça uma aposta em mim, querida.}
{1295}{}{Procurando por um bom tempo, querida?}
{1296}{}{Eu não posso acreditar quantos strippers estavam no Feargus 'despedida de solteiro.}
{1297}{}{Lovin 'gosta de prata, aqui mesmo.}
{1298}{}{Eu vou te dar um pouco de jogo.}
{1299}{}{Eu sou Filthy Spice.}
{1300}{}{Eu sou tempero caseiro.}
{1301}{}{Eu sou Slutty Spice.}
{1302}{}{Eu sou Old Spice.}
{1303}{}{Eu sou Sífilis ... er, Slutty Spice.}
{1304}{}{Eu sou Dirty Spice.}
{1305}{}{Tenho uma namorada se quiser um duplo cabeçalho.}
{1306}{}{Gostaria que Myron fosse gay.}
{1307}{}{Ainda não sei porque eles chamam de Virgin Street ...}
{1308}{}{Gostaria que ele usasse um saco de papel às vezes.}
{1309}{}{Comprar uma bebida?}
{1310}{}{Pegue uma senhora solitária na cidade?}
{1311}{}{Uh, claro, sou uma mulher. Apenas ignore a maçã de Adão.}
{1312}{}{Ouvi algumas das garotas da parte alta mataram seu cafetão.}
{1313}{}{Melhor amor em todos os resíduos, aqui mesmo.}
{1314}{}{Que Jules melhor me deixe em paz.}
{1315}{}{Ainda tenho essa hematoma da cabeceira da cama ...}
{1316}{}{Esgotado desde a última convenção ...}
{1317}{}{Gostaria que Gen Con tivesse lugar em alguma outra cidade.}
{1318}{}{Você poderia derreter o metal, você sabe disso?}
{1319}{}{Senti a Terra se mover, mas era apenas o pimentão.}
{1320}{}{Me faça derreter.}
{1321}{}{Sou virgem. Eu não sou muito bom nisso.}
{1322}{}{Precisa de um guia em torno da cidade?}
{1323}{}{UAU. Isso vai custar mais.}
{1324}{}{Jules continua querendo brindes.}
{1325}{}{Eu ouço que as famílias estão ficando tensas novamente.}
{1326}{}{As coisas são bastante lentas. Desejo que a caravana mostre.}
{1327}{}{Então ele se veste neste traje do Deathclaw, então ...}
{1328}{}{Preciso de ajuda para sair desse vestido.}
{1329}{}{Feche-me? Então, de novo?}
{1330}{}{Desculpe, o que você estava dizendo? Eu estava muito ocupado olhando seu corpo tenso.}
{1331}{}{Quer perder algum tempo?}
{1332}{}{Eu chutei Jules em suas jóias da família na semana passada.}
{1333}{}{Eles não me chamam de Lady Lucky por nada.}
{1334}{}{DE CURSO Eu amo esses preservativos com sabor a brahmin. Yum.}
{1335}{}{Mostre a uma dama um bom momento?}
{1336}{}{Nada de errado com Myron uma bala não vai curar.}
{1337}{}{Precisa de um encontro tribal?}
{1338}{}{Quer pow-wow, tribal?}
{1339}{}{Quer fazer a dança da chuva no meu quarto, tribal?}
{1340}{}{Tudo o que você precisa é uma noite comigo.}
{1341}{}{Procurando por Eden? Bem, querida.}
{1342}{}{Pode me ajudar? Estou à procura da minha virgindade perdida.}
{1343}{}{Sou virgem, mas preciso do dinheiro.}
{1344}{}{Seja gentil, é a minha primeira vez. Hoje.}
{1345}{}{Eu tão excitado.}
{1346}{}{Você obteve o desejo, recebi a poupança.}
{1347}{}{Deixe-me acordar o seu filho interior.}
{1348}{}{Estou apenas fazendo isso para pagar a faculdade.}
{1349}{}{Quer dançar, querido?}
{1350}{}{Olhe, pela última vez, não vou me vestir como o "Vault Dweller".}
{1351}{}{Olhando para apostar em uma reivindicação?}
{1352}{}{Quer me fazer gemer?}
{1353}{}{:: Purrrrr ::}
{1354}{}{:: Rrrrrowrrr ::}
{1355}{}{Pare de me fazer cócegas.}
{1356}{}{Ficando cansado de estar em Reno ...}
{1357}{}{Queres fingir que somos mortes na temporada de acasalamento?}
{1358}{}{Não sou barato, mas estou especial.}
{1359}{}{Acelerar-se custos adicionais.}
{1360}{}{Onde eu deixei meu chicote?}
{1361}{}{Pronto como um freddie.}
{1362}{}{Eu tive que vestir-me como WILMA ontem à noite, Fer Chrissakes.}
{1363}{}{Estava com Myron ontem à noite. Por cerca de cinco segundos.}
{1364}{}{Procurando por um clipe?}
{1365}{}{Onde está o fogo?}
{1366}{}{Quer me ajudar a perder sua virgindade?}
{1367}{}{O meu traseiro vai cair, Myron continua.}
{1368}{}{Damn Temperance Union veio de novo ...}
{1369}{}{Você faz meu balcão Geiger marcar.}
{1370}{}{:: Whistles ::}
{1371}{}{Morder é extra.}
{1372}{}{Garanto que sou melhor do que o anexo do Pip Boy que você usou.}
{1373}{}{Quer que eu aperte seus parafusos?}
{1374}{}{Prefiro estar com Avellone.}
{1375}{}{Eu queria que Nick Kesting estivesse aqui. Poderíamos conversar por horas!}
{1376}{}{Nick Kesting é um cara muito legal. Temos excelentes conversas.}
{1377}{}{Tommy the Balls é tão sonhador.}
{1378}{}{Preciso de cinquenta dólares para fazer você gritar.}
{1379}{}{Meu nome é fácil, garota. O que é seu?}
{1380}{}{Ei,cutie. Looking for the other woman?}
{1381}{}{Procurando um sabor do outro lado, querido?}
{1382}{}{Precisa de uma pequena empresa?}
{1383}{}{Menina, deixe-me ensinar-lhe algumas coisas que uma MULHER pode ensinar.}
{1384}{}{Precisa de alguém para aquecer sua barraca, querida?}
{1385}{}{Precisa de alguém para compartilhar seu bedroll, querido?}
{1386}{}{Quer dançar, garota?}
{1387}{}{Menina, você nunca teve amor até que você tivesse amor de Reno.}
{1388}{}{Quer voar, garota?}
{1389}{}{Perder o seu caminho, vaqueira?}
{1390}{}{Ei, G.I. Jane?}
{1391}{}{À procura de um bom tempo, garota?}
{1392}{}{Olhando para ir para a cidade, garota?}
{1393}{}{À procura de alguma ação, sugah?}
{1394}{}{Onde está o fogo, querida?}
{1395}{}{Você conseguiu o dinheiro, garota, eu consegui o tempo.}

# SPECIAL CAT'S PAW WHORE DIALOGS START
# 0. QUICK LOOK
{3100}{}{Você vê uma das garotas do gato Paw.}

# EXAMINES
{3150}{}{Você vê uma ... senhora da noite. Suas roupas esfarrapadas são drapejadas sedutoramente ao redor de seu corpo.}
{3151}{}{Você vê uma das garotas do gato Paw. She winks at you.}
{3151}{}{Você vê uma das garotas do gato Paw. Her eyes are like blown fuses.}
{3152}{}{Você vê uma das garotas do gato Paw. She smells like flowers.}
{3153}{}{Você vê uma das garotas do gato Paw. She smells like mother.}
{3154}{}{Você vê uma das garotas do gato Paw. It is a mystery to you how her tattered rags manage to hold her breasts in.}
{3155}{}{Você vê uma das garotas do gato Paw. She looks as if she kills her mates and eats them.}
{3156}{}{Você vê uma das garotas do gato Paw. She is appraising you like a jeweler.}
{3157}{}{Você vê uma das garotas do gato Paw. Her tattered clothes are draped seductively around her body.}

#1. SOME OTHER RANDOM FLOAT TEXT [ANY DISTANCE] (WTG)
{3200}{}{Oh, Gawd! Oh, Gawd! OhGawdohGawdohGawd ... ooooooh Gaaaawd.}
{3201}{}{Sim! Sim! Yeeeeeeeees Sim, Sim Sim Sim SIM YESSSSS! Agora vá pagar o
 caixa.}
{3202}{}{Se apresse. O funcionamento do Meter.}
{3203}{}{Precisa de uma toalha úmida?}
{3204}{}{Dê-me, Pe ... Ni ... Sco ... uh, desculpe o seu nome novamente?}
{3205}{}{Oh Gawd, oh Gawd, oh Gawd! AGORA estamos terminados?}
{3206}{}{Uau. Isso vai custar mais.}
{3207}{}{Sim! Você é Colombo, eu sou a América!}
{3208}{}{Oh, Deus, esse foi o melhor. Agora, tire o inferno de mim e pague a
 caixa.}
{3209}{}{Ainda está?}
{3210}{}{Sim, você é o habitante do Vault. Sim, você encontrou o chip de água e bateu
 O mestre. Você é um HERÓI.}
{3211}{}{Você é tão robusto, você é como uma armadura de poder endurecida.}
{3212}{}{* Huff *}
{3213}{}{*Sopro*}
{3214}{}{Não, não vou usar as orelhas de Mikey Mouse.}
{3215}{}{Sim, sim, você tem "bolas monstah".}

# END LINES
{2175}{}{. Aquele que chutou o traseiro do Enclave.}
{2178}{}{! Maneira de chutar a bunda do Enclave!}
{2181}{}{. Aquele que chutou o traseiro do Enclave.}
{2195}{}{!}
{2197}{}{! Você pode me fazer um emprego no estúdio?}
{2210}{}{.}
{2263}{}{! Você vai, stud!}
{2264}{}{ Chuta tanto ass, você pensaria que ele era uma bota em outra vida.}
{2268}{}{?}
{2272}{}{?}
{2278}{}{! Vai nessa, garota!}
{2279}{}{?}
{2280}{}{ Chuta tanto ass, você pensaria que ela era uma bota em outra vida.}
{2285}{}{.}
{2292}{}{...}
{2293}{}{?}
{2294}{}{... over heeere, sweetie...}
{2295}{}{.}
{2855}{}{?}
{2858}{}{?}
{2861}{}{?}
{2865}{}{, you big hunk o' man...what have you been up to?}
{2867}{}{! Como você está?}
{2868}{}{. Can I help you with...*anything?*}
{2870}{}{.}
{2873}{}{, you little temptress...what have you been up to?}
