# 0. QUICK LOOK [FEMALE]
{100}{}{Você vê a pesquisadora principal, Marjorie Reed.}

# 0. LOOK [FEMALE]
{150}{}{Você vê uma mulher cansada. Sua cabeça foi calva careca, e ela está vestindo um casaco branco.}
{151}{}{Você vê Marjorie Reed. Ela está enchendo um hipodérmico, resmungando ligeiramente para si mesma.}

# 1. FLOAT (COMPANION = MYRON)
{200}{}{Olá, Myron.}
{201}{}{Myron, você tem um minuto ...?}
{202}{}{Mais uma palavra quando novos escravos serão entregues, Myron?}
{203}{}{Myron, esses novos resultados são muito promissores ...}
{204}{}{Myron, um minuto do seu tempo?}

# 2. FLOAT (NORMAL)
{215}{}{Onde diabos é Myron ...}
{216}{}{Receba Myron aqui. Ele tem que ver isso.}
{217}{}{Desejo que esses escravos se calassem ...}
{218}{}{Onde eu deixei essa seringa ...}
{219}{}{Alguém viu o número 31? Ele estava aqui apenas um segundo atrás.}
{220}{}{Os escravos trazem mais do Jet Beta.}
{221}{}{Os resultados dos testes do Jet Beta são muito promissores, mas ...}
{222}{}{"Alto" dura 15 minutos a uma hora ... calcule um período de dose / hora ... hmmmmnnn.}
{223}{}{O número 12 ainda continua com sangramento nasal ...}
{224}{}{Essa é a quinta vez que o número 12 sofreu convulsões ... até a dose, veja o que acontece ...}
{225}{}{Bem, qual o índice de alucinações que ele estava tendo?}
{226}{}{Verifique a taxa cardíaca. Se ainda estiver dentro dos limites toleráveis, até a dosagem.}
{227}{}{Por que o escravo no grupo controle se matou? Nós não estávamos nem testando ela!}
{228}{}{Damn guardas podem acompanhar seus próprios jumentos ...}

# 3. CLICK (COMPANION = MYRON)
{235}{}{Olá, Myron, senhor. Os testes estão sendo realizados conforme previsto.}
{236}{}{Myron, senhor, essa nova cepa de Jet é extremamente formadora de hábitos. Os escravos estão quase dispostos a se matar por isso.}
{237}{}{Myron, senhor, você ficará satisfeito ao notar que os escravos preferem levar Jet do que comer, é tão potente.}
{238}{}{Quem são essas pessoas com você, Myron? Novos assuntos?}
{239}{}{Myron, senhor, o terceiro grupo de teste parece fazer o melhor de todos os grupos.}
{240}{}{Myron, senhor, se você tiver um momento ... Eu acho que o próximo grupo de teste deve incluir pelo menos três crianças, senhor.}
{241}{}{Myron, senhor, o número 46 teve um ataque cardíaco; estamos restringindo as doses até seis vezes ao dia de agora em diante.}
{242}{}{Myron, senhor, por favor ... precisamos de um novo carregamento de hipodermia da Vault City. Não podemos continuar reutilizando estes.}
{243}{}{Mais uma palavra quando novos escravos serão entregues, Myron, senhor?}
{244}{}{Myron, senhor, mudamos três escravos do grupo de controle para o grupo de teste por causa das falhas respiratórias que tivemos na semana passada.}
{245}{}{Myron, más notícias, senhor. Tivemos que atirar em um escravo para tentar escapar. Que desperdício.}
{246}{}{Myron, este novo alucinógeno que você desenvolveu é promissor, mas não é tão hábito como o jato ...}

# 4. INTRO (WTG)
{250}{}{(A mulher calva nem olha para cima da prancheta.) Sim?}
{251}{}{Não!}
{252}{}{Sim!}
{253}{}{Heh heh. Você é careca. Você parece homem}
{254}{}{Delenn?}
{255}{}{Afastar-se}
{256}{}{Quem é Você?}
{257}{}{Desculpe, pensei que você fosse outra mulher careca com uma prancheta. Eu irei agora.}

# 5. RETARD (4)
{265}{}{(A mulher olha para cima e olha para você.) Você é um dos sujeitos de controle? Como se importa de qualquer maneira ... Guardas! Detenda esse escravo!}
{266}{}{Onde escravo? Eu não vejo um}

# 6. WHO ARE YOU? (4)
{275}{}{Olha, estou muito ocupado, então, se você não se importar ... [Olha para cima da sua prancheta para você, e depois garças a cara.] Quem é você? Como você chegou aqui?}
{276}{}{Olha, estou muito ocupado, então, se você não se importar ... [Olha para cima da sua prancheta para você, e depois garças a cara.] Você novamente? O que você quer agora?}
{277}{}{Sua porta do celeiro está aberta. Heh-heh ... entendeu? Eu me mato.}
{278}{}{Eu sou um dos novos funcionários atribuídos aqui.}
{279}{}{Estou procurando Myron. Ele está por perto?}
{280}{}{Os resultados do teste que você tem na área de transferência? Posso vê-los?}
{282}{}{Deixa pra lá. Desculpe incomodá-lo.}

# 7. DOOR WAS OPEN (6)
{295}{}{Esta área não está aberta para ... visitantes. Saia ou ligarei para os guardas.}
{296}{}{Mas oi, eu tive algumas perguntas para você ...}
{298}{}{Os resultados do teste que você tem na área de transferência? Posso vê-los? I'm something of a researcher myself.}
{300}{}{Muito bem. Desculpe incomodá-lo.}

# 8. BUT HEY. . . (7, 24)
{310}{}{Guardas! Guardas, detenha essa pessoa!}

# 9. I'M ONE OF THE NEW PERSONNEL (6, 7)
{315}{}{MAIS guardas. Ha! Como se eles fizessem algum bem ... olhe, você DEVE ter recebido as instruções de quem o enviou aqui. Conversa
 para os outros guardas para descobrir sua tarefa. Agora vá.}
{316}{}{Eu não sou um guarda; Eu sou um dos novos pesquisadores. Você tem uma tarefa para mim?}
{317}{}{Com licença, mas esperava que você pudesse me mostrar. Eu vi você de pé aqui e
 sentiu-se cheio de falar com você. Talvez depois da turnê pudéssemos jantar ...?}
{318}{}{Obrigado. Você foi muito útil.}

# 10. I'M ONE OF THE NEW RESEARCHERS (6, 7, 9)
{325}{}{Você é um PESQUISADOR ...? Hmmmm. Eu nunca vi você antes. Quanto você sabe sobre pesquisa farmacêutica?}
{326}{}{Uh, o suficiente. Sente-se e me veja.}
{327}{}{Conheço uma quantidade razoável sobre a composição e fabricação de compostos neuroquímicos de base, e eu acho que eu
 poderia ser de alguma ajuda em seus estudos.}
{328}{}{Eu tenho que ir.}

# 11. I'M ONE OF THE NEW RESEARCHERS (10)
{335}{}{Ha! Eu acho que vou apenas assistir você, período. Deixe antes de chamar os guardas.}
{336}{}{Tudo certo.}
{337}{}{Eu vou ... :: mumble :: ... sua cadela de cabeça calva.}

# 12. I KNOW QUITE A BIT ABOUT BASE NEUROCHEMCIAL COMPOUNDS . . . (10)
{345}{}{Hmmmm. Tudo bem então. Deixe-me dar uma avalanche sobre o que fazemos aqui: testamos os efeitos e a potência de uma metafefamina
 chamado Jet.}
{346}{}{Entendo. E como a pesquisa está chegando?}
{347}{}{Eu acho que tenho a ideia. Examinarei o resto da área de testes.}

# 13. I SEE. AND HOW IS THE RESEARCH COMING? (12, 22, 25)
{355}{}{Não muito bem. Nosso cronograma é apertado, e precisamos purificar o processo de fabricação do Jet em breve.}
{356}{}{Por quê? O jato parece já ter formado o hábito.}
{357}{}{Por que a agenda apertada?}
{358}{}{Parece um trabalho difícil. Olha, eu tenho que cuidar de algo realmente rápido - voltarei.}

# 14. WHY THE TIGHT SCHEDULE? (13)
{365}{}{Ninguém saiu e disse isso, mas provavelmente é devido à distribuição de Jet em Redding. Potente * Jet * suficiente, * mas
 Há um bom espaço de melhoria, e o "bronze" quer aumentar a confiança da Jet em Redding.}
{366}{}{Qual é o acordo com a Redding?}
{367}{}{Bem, boa sorte, cumprindo o cronograma.}

# 15. WHY? JET SEEMS ADDICTIVE ENOUGH ALREADY . . . (13)
{375}{}{É potente * suficiente, * mas há espaço para melhorias. O "bronze" quer aumentar a distribuição da Jet no
 Redding, e eles querem que a taxa de confiança seja tão próxima de 100% quanto possível. Isso vai exigir que tiremos algumas horas longas.}
{377}{}{Obrigado pela informação. Voltarei mais tarde.}

# 16. WHAT'S THE DEAL WITH REDDING? (14, 15)
{385}{}{Engate os mineiros em Redding para Jet, e quem controla o Jet, controla Redding. Jogo de poder típico.}
{386}{}{Então ... quem controla os chems?}

# 17. SO WHO DOES CONTROL THE DRUGS? (16)
{395}{}{Quem controla os chems? Os Mordinos. Claro, Myron colocou todas as bases para a composição da Jet.
 Nós fazemos principalmente o trabalho de limpeza.}
{396}{}{Myron é seu chefe?}

# 18. MYRON'S OUR BOSS? (17)
{405}{}{Você poderia chamá-lo assim. Ele é inteligente, vou dar-lhe isso, mas ele não se importa muito com o que se passa
 aqui em cima. Ele permanece principalmente no cofre do porão ... sem visitantes, exceto pelo trem de prostitutas. Líder de projeto típico.}
{406}{}{Eu poderia vê-lo?}
{407}{}{Sim, embora o marketing seja pior. De qualquer forma, obrigado pela informação. Voltarei mais tarde.}

# 19. COULD I SEE HIM? (18)
{415}{}{Suponho ... deixe-me lhe dar um crachá temporário; Apenas mostre para os guardas. Mantenha-o rápido, no entanto, Myron não
 como as pessoas ficando longas.}
{416}{}{Suponho ... deixe-me lhe dar um crachá temporário; Apenas mostre para os guardas. Mantenha-o rápido, no entanto, Myron não
 Como as pessoas ficam longas ... embora ele possa fazer uma exceção no seu caso.}
{417}{}{Obrigado pelo distintivo. Vejo você mais tarde.}

# 20. EXCUSE ME FOR BEING FORWARD (FEMALE) (9)
{425}{}{Olha, estou muito ocupado, então se você não se importa ...}
{426}{}{Olha, eu ... Estou bem, muito ocupado, então se você me desculpe ...}
{427}{}{Deixa pra lá então...}
{428}{}{Obrigado mesmo assim.}
{429}{}{Obrigado mesmo assim...::mumble:: …you uppity cue-balled bitch.}

# 21. EXCUSE ME FOR BEING FORWARD (GOOD) (9)
{435}{}{Isso ... hmm ... Estou muito lisonjeado, mas também estou muito ocupado no momento ... então ... uh ...}
{436}{}{Bem, você se importa se eu vim e peguei você depois do trabalho, então? Sem pressão ... apenas um jantar, alguns
 conversação. Você se parece com alguém que talvez precise fazer uma pequena pausa no trabalho. As coisas aqui devem mantê-lo muito ocupado.}
{437}{}{Well, I had to ask. Obrigado mesmo assim.}

# 22. DO YOU MIND IF I PICKED YOU UP AFTER WORK . . .? (21)
{445}{}{Oh, não está ocupado ... heh ... bem, não, muito ocupado. Quero dizer, principalmente o teste quimico de rotina e, ocasionalmente, temos
 um escravo ultrapassa a borda ...}
{446}{}{Não intencionalmente injetar metafetaminas experimentais em seres humanos escravizados fazem você questionar sua humanidade básica?}
{447}{}{Uau. Isso parece perigoso. Você já se machucou? Você tem muitas mortes por pacientes?}
{448}{}{Teste de quimica? Mesmo? Como vão as coisas?}
{449}{}{Parece interessante, mas tenho que ir ... .uh, volto, no entanto.}

# 23. DON'T YOU EVER QUESTION YOUR HUMANITY? (22)
{455}{}{Essa foi uma fraca tentativa de uma piada?}
{456}{}{Só perguntando. Quero dizer, e se você tivesse sido vendido em escravidão, foi levado aqui, então, cheio de chems?}
{457}{}{Uh, yes. Eu tenho que ir.}

# 24. PUMPED FULL OF DRUGS? (23)
{465}{}{Eu estou do lado de as barracas, eles estão do lado desse lado. Uma vez que estamos entrando em hipotéticos,
 VOCÊ gosta de descobrir o que é ser eles? Temos uma barraca extra ou duas.}
{466}{}{Agora aguarde um minuto ...}
{467}{}{Uh, não, obrigado. Desculpe incomodá-lo.}

# 25. PATIENT FATALTIES (22)
{475}{}{Mortes escravas? Um pouco. Principalmente overdoses acidentais - geralmente culpa de uma tecnologia - ou lesões auto-infligidas.
 Alguns ingerem muito Jet, e eles REALMENTE querem voar.}
{476}{}{Além disso, como está o teste de quimioterapia?}
{477}{}{Eu aposto. Bem, obrigado pela informação. Você foi muito útil.}

# 26. ACTUALLY, I WAS LOOKING FOR MYRON (6)
{485}{}{Experimente o andar de baixo no laboratório. A porta protegida. Se você vê-lo, diga-lhe para vir aqui quando ele tiver o
 chance. Se ele não estiver muito ocupado.}

# GET BADGE MESSAGE
{1000}{}{Você recebe uma passagem temporária da Marjorie.}
