# 0. QUICK LOOK
{100}{}{Você vê Renesco o Rocketman.}

# 0. LOOK (GLASSES = DISCOUNT, FREEBIE, DONE)
{150}{}{Você vê um homem velho com um par de óculos grandes e lúdicos. Ele sussurra irritado enquanto observa.}

# 0. LOOK (GLASSES = NOTHING)
{200}{}{Você vê Renesco o Rocketman. As you watch, he takes off his cracked glasses and polishes the one good lens.}
{201}{}{Você vê Renesco o Rocketman. As you watch, he takes off his cracked glasses and polishes the one good lens.}

# 1. FLOAT DIALOGUES (WTG)
{210}{}{Mais uma lente, é tudo o que eu pergunto.}
{211}{}{Óculos malditos!}
{212}{}{Maldito meus olhos!}
{213}{}{Você vai comprar algo?}
{214}{}{This ain't a soup kitchen. Você vai comprar algo?}
{215}{}{Eu vou ficar cego. Eu continuo com essa linha de trabalho.}
{216}{}{Vai precisar de mais uma base de quimioterapia nove ...}
{217}{}{Demand's picking ...}

# 2. FLOAT DIALOGUES (WTG)
{225}{}{Vá para o inferno.}
{226}{}{Saia daqui, ou eu vou te matar até a morte. Duas vezes.}
{227}{}{Saia daqui.}
{228}{}{Fora! Fora! Fora! Fora! Fora!}

# 3. INTRO SPIEL (WTG)
{235}{}{(O velho empurra seus óculos quebrados no nariz e suspira em exasperação.) SIM? O que é que você quer?}
{236}{}{Vamos, cara, com isso!}
{237}{}{Vamos, mulher, com isso!}
{238}{}{Ok, deixe-o sair ... é melhor você se afastar (Zip.)}
{239}{}{Okee Dokee. Precisa abrir o sutiã primeiro. Aguarde (Zip.)}
{240}{}{Whut me WANT? Whut you GOT?}
{241}{}{Olhe para ele por um segundo, apenas para se certificar de que ele é real, então vá embora}
{242}{}{Quem é Você?}
{243}{}{Ei, eu tenho um par de óculos, se você os quer.}
{244}{}{Como estão os óculos?}
{245}{}{Você sabe, existem marcas descafeitadas que sabem tão bom quanto o real.}
{246}{}{Cara, estou no lugar errado. Adeus.}

# 4.  RETARD (3, 5)
{255}{}{(Olha em estado de choque.)}
{256}{}{... outro naufrágio pós-abortado em um mundo pós-holocausto repleto de idiotas homens-filhos. (Eleva os punhos.)
 Fora da minha loja! Sair imediatamente! Você não volta, você ouve ?!}
{257}{}{Me desculpe pouco}
{258}{}{Eu não sei como colocar o sutiã de volta}
{259}{}{Não gritar em}
{260}{}{ odeio você!}
{261}{}{Eu vou, vou. Para agora.}

# 5.  WHO ARE YOU? (3)
{270}{}{Eu? Oh, eu sou alegre, meu santo Nick, você desafiou o meio-mundo de forma cranial.}
{271}{}{Eu? Sou bem santo Nick. E você deve ser aquele estúpido bandido por aluguel que tem andado por a cidade como um
 Cão faminto com fome de seus próprios excrementos.}
{272}{}{Eu? Sou alegre de São Nick. E você deve ser aquele estúpido pedaço de lixo de porco que está pendurado como
 um cavalo e tão estúpido como um.}
{273}{}{Eu? Sou alegre de São Nick. E VOCÊ deve ser aquele estúpido escorregadio de lixo porno que está sendo usado por trincheira
 Os homens usam para cumprir suas fantasias masturbatórias.}
{274}{}{Bem, fico feliz por não ter que apresentar-me então. O que você faz aqui, "Nick?"}
{275}{}{Santo Nick? Quem diabos é isso?}
{276}{}{Olhe vovô, mais um comentário como esse, e eu estarei usando seus dentes como um colar.}
{277}{}{Olha, vou deixar o seu comentário deslizar ... desta vez. Agora, quem é você?}
{278}{}{Vocabulário impressionante ... "Nick". Você por aqui?}
{279}{}{Esqueça isso. Estou fora daqui.}

# 6. WHO ARE YOU? (3, 5)
{290}{}{(Glares para você, depois ressonam.) Nome Renesco. Apenas me diga o que você quer, você ... bem, seja lá o que for.
 (Squints para você.) Você parece um daqueles primatas que adoram o sol sob todo o que se levanta.}
{291}{}{Eu sou de uma aldeia ao noroeste. Arroyo.}
{292}{}{O que você vende aqui?}
{293}{}{O que eu quero? Eu realmente não sei. Na maioria das vezes, ignoro minha busca e entrei nas casas dos outros,
 riffling através das prateleiras das pessoas ... oooh, como aqueles lá!}
{294}{}{Você tem um vocabulário interessante ... Renesco. Você é por aqui?}
{295}{}{Estou fora daqui.}

# 7. WHAT DO YOU SELL? (6, 36, 42)
{305}{}{Eu vendo chems recreacionais principalmente. É por isso que eles me deram essa idiota, "o Rocketman". Hmmmph. Eu
 também vendem alguns estoques de caravanas. Você PRECISA de tudo ou posso voltar a algo importante?}
{306}{}{Rocketman, hein? Conheça a linha na canção de Elton John, "Rocketman, queimando o mmmncfnfm lá em casa?" O que é
 ele realmente disse lá?}
{307}{}{Posso ver o que você tem no estoque?}
{308}{}{Você vende chems aqui na LOJA?}
{309}{}{Você quer dizer como vender chems ao filho de Wright?}
{310}{}{Volte para o que estava fazendo.}

# 8. ROCKETMAN/IGNORE QUEST (6, 7, 32, 36)
{320}{}{(Renesco olha para você. Parece que ele está se despindo mentalmente, depois rasgando seu membro do membro).}
{321}{}{Deixa pra lá então. Tive algumas outras questões ...}
{322}{}{Deixa pra lá então.}

# 9. YOU SELL DRUGS IN THE STORE? (7)
{330}{}{(Renesco olha para você com desgosto.) Sim. Na loja. Este não é o século 20, onde os chems são vendidos por
 baratas na esquina que vivem em constante medo das autoridades.}
{331}{}{Bem então -}
{332}{}{Mas -}
{333}{}{Uh, acho melhor.}

# 10. YOU SELL DRUGS IN THE STORE? (9)
{350}{}{Esta é a NOVA RENO. Não há policiais, nem lei, e há muitos clientes que não se importam em comprar veneno no
 farmácia na rua. Isso responde sua pergunta, primata?}
{351}{}{Todos exceto um: Richard Wright era um de seus clientes?}
{352}{}{Tudo bem, tudo bem ... o que você tem em estoque?}
{353}{}{Na verdade, eu tinha mais algumas perguntas ...}
{354}{}{Mas, como você disse, os chems são ... venenosos. Eles matam o espírito. Não incomoda você vendê-los?}
{355}{}{Claro. Eu irei agora.}

# 11. DOES IT BOTHER YOU TO SELL DRUGS IN THE STORE? (10)
{365}{}{Faz parte de mim para vendê-los a idiotas, escravas, criadas e tribais que o mundo seria melhor
 sem? Primata, três palavras: saia mais.}
{366}{}{OK ... posso ver o que você tem no estoque?}
{367}{}{Tudo bem, tudo bem. Olha, eu tive algumas outras perguntas ...}
{368}{}{Os chems aqui em New Reno estão encontrando seu caminho para outros lugares, e ferindo as pessoas lá. Isso não diz respeito a você?}
{369}{}{Vou começar por sair agora mesmo.}

# 12. YOU SELL DRUGS IN THE STORE 2? (11)
{375}{}{Assim? O que eu me importo com eles?}
{377}{}{A raça humana sofreu uma tragédia horrível. Agora estamos tentando reconstruir. Vender Jet parece ... contraproducente
 para essa reconstrução.}
{378}{}{Bem, tanto faz. Eu devo ir agora.}

# 13. SOME OF THE PEOPLE BEING HARMED ARE . . . (12)
{385}{}{Assim. O que. Ninguém está FORÇANDO esses idiotas para inalar Jet. Ninguém está por aí e bloqueando-os
 gargantas}
{386}{}{Entendo -}
{387}{}{Mas não -}
{388}{}{Esse é o seu -}

# 14. SOME OF THE PEOPLE BEING HARMED ARE . . . 2 (13)
{395}{}{Aqueles chimpanzés da lâmpada em Redding SABEM o que eles estão tomando, então eu não sinto um milímetro de piedade para eles!
 Por mais que me preocupe, o Jet deixa o lixo humano que deveria morrer quando as bombas caíram!}
{396}{}{Uh, está bem. Posso ver seu estoque?}
{397}{}{De onde é esse Redding de onde você fala? Por que você os menciona?}
{398}{}{Você mencionou especificamente a Redding. Por que Jet é tão prevalente em Redding?}
{400}{}{Esse é o seu direito de se sentir desse jeito. Eu devo ir agora.}

# 15. REDDING 1 (14)
{410}{}{Bem, o Redding é um ... caso especial. Veja, há pessoas em Reno que se certificam de que o Redding está bem abastecido. Afinal, você
 Experimente o Jet uma vez, você está viciado. É como eu faço a minha vida.}
{411}{}{Falando sobre isso, posso ver suas ações?}
{412}{}{Quem está se certificando de que o Redding está bem fornecido? E porque?}
{413}{}{Então notei. Olha, eu tive algumas outras perguntas ...}
{414}{}{Eu vejo ... eu tenho que ir agora.}

# 16. WHO'S SUPPLYING REDDING? (15)
{420}{}{Bem, tribal, duvido que você tenha a sensação de notar isso ainda, mas o New Reno não produz nada útil.
 É como uma garota de pradaria grande, brilhantemente iluminada, sentada no deserto. Agora, Redding, por outro lado ...}
{421}{}{Continue.}
{422}{}{... produz algo útil.}
{423}{}{Já ouvi o suficiente.}

# 17. . . . DOES PRODUCE SOMETHING USEFUL (16)
{430}{}{Primeira e última vez, vou avisá-lo, tribal: não termine minhas malditas frases. Eu não gosto de primatas inteligentes
 que falam quando devem ouvir. Não é de admirar que todos vocês ainda usem lanças ...}
{431}{}{Nem todos nós. Por exemplo, eu uso uma variedade de armas para matar pessoas ... deixe-me mostrar-lhe.}
{432}{}{Me perdoe. Por favor continue.}
{433}{}{Burn in hell. Estou fora daqui. }

# 18. GO ON ABOUT REDDING (16, 17)
{440}{}{Redding tem uma força de trabalho estável que mina matérias-primas, principalmente ouro. O novo Reno certamente poderia usar esse ouro. Alguém
 tudo o que temos que fazer é conseguir que esses mineiros se enganchem, e nós os conseguimos para a vida. Você entende agora?}
{441}{}{Sim ... exceto por uma coisa: de onde veio Jet?}
{442}{}{Quem está tentando engatar todos os mineiros?}
{443}{}{Sim eu entendo. Olha, eu tive algumas outras perguntas ...}
{444}{}{Eu não quero mais ouvir. Eu devo ir agora.}

# 19. WHERE DID JET COME FROM? (20)
{450}{}{(Pontos em Myron.) Por que você não pergunta a seu amigo pequeno sapo quente? Tenho certeza de que ele ficaria feliz em lhe contar. (Glares
 em Myron.) Certo, criança?}
{451}{}{Temos uma pessoa para agradecer a Jet. Você ouviu falar do pequeno garoto dourado da família Mordino, Myron? Bem, o pequeno
 bastardo CRIADO Jet. O grande Jesus Mordino deixa todos saberem onde podiam obtê-lo.}
{452}{}{Conte-me mais sobre Myron.}
{453}{}{Existe alguma cura para o Jet?}
{454}{}{Tive algumas outras questões ...}

# 20. WHERE DID JET COME FROM? (18)
{460}{}{O grande jato de Jesus Mordino Jet em Redding. Jogo de poder típico. Uma vez que o pipeline realmente começa, aqueles
 Os mineiros estão perdidos.}
{461}{}{De onde veio Jet?}
{463}{}{I see. Look, Tive algumas outras questões ...}

# 21. TALK ABOUT MYRON (19, 24)
{470}{}{Horny como um sapo e toda a moral de um. Garoto inteligente, no entanto. Alto QI. Desperdiçando seus cérebros produzindo chems, isso é
 por certo.}
{471}{}{Onde posso encontrá-lo?}
{472}{}{Entendo. Tive algumas outras questões ...}

# 22. WHERE CAN I FIND MYRON? (21)
{480}{}{Os Mordinos o levaram trancado em algum lugar. Com muita segurança, provavelmente. Não sei exatamente onde.}
{481}{}{Thanks for the information. Posso ver o que você tem no estoque?}

# 23. ANY CURE FOR JET? (19, 20)
{490}{}{Uma CURA para a dependência de metafeftamina ?! Ha! Só conheço dois: um é a morte. O outro está se trancando
 em uma gaiola por um ano sem Jet e suavize-o para fora do seu sistema. Hmmmph. "Cure", minha bunda! Que absurdo!}
{492}{}{Deve haver uma cura. Qual é a composição química da Jet?}

# 24. JET COMPOSITON? (23)
{505}{}{Por que você não pergunta a seu amigo lá? Ele projetou o químico.}
{506}{}{Acabei de vender as coisas. Gostaria de perguntar a um cientista. Ou Myron. Ele projetou o químico.}

# 25. TALK ABOUT VILLAGE (6, 42)
{515}{}{(Renesco olha para você em silêncio.)}
{516}{}{(Renesco olha para você novamente, desta vez em silêncio.)}
{517}{}{Eu acho que você gostaria de Arroyo. É uma aldeia pacífica. Exceto pelas plantas possuídas por espíritos malignos ... e, claro, o templo
 de provas preenchidas com as mortíferas armadilhas de lança e as formigas gigantes que comiam homens.}
{518}{}{Eh, você já ouviu falar de um Kit de Criação do Jardim do Éden? Ou o Vault 13?}
{519}{}{Ok, então ... estou fora daqui.}

# 26. TALK ABOUT VILLAGE 2 (25)
{525}{}{(Renesco continua a olhar para você).}
{526}{}{E às vezes o ancião fica chateado com pequenas coisas, como ... heh-heh ... aquela uma noite em que ignorei meu voto de
 celibato e fugiu com Reyna - Whose - Legs - Crush - With - Strength - of - Thousand - Snakes to the Arroyo canyon ...}
{1526}{}{E às vezes o ancião fica chateado com pequenas coisas, como ... heh-heh ... aquela uma noite em que ignorei meu voto de
 castidade e escapou com Kor - Who - Thunders - Like - a - Thousand - Stallions para o Arroyo Canyon}

# 27. TALK ABOUT VILLAGE 2 (26)
{535}{}{(Renesco lhe dá um olhar descontente.)}
{536}{}{Era como ontem. O corpo de Reyna brilhava como prata ao luar quando ela se ajoelhou e ... ei, você sabe o que?
 Você pode gostar do ancião. Ela tem aproximadamente sua idade.}
{1536}{}{Era como ontem. O corpo de Kor ondulou como bronze à luz da lua quando eu ajoelhei-me e ... ei, você sabe o que?
 Você pode gostar do ancião. Ela tem aproximadamente sua idade.}

# 28. WHO ARE YOU? (27)
{545}{}{(Renesco continua a olhar para você como se ele pudesse de alguma forma fazê-lo desaparecer apenas imaginando isso com bastante força.)}
{546}{}{Eu mencionei que Arroyo foi fundado por meu antepassado, o morador sagrado do Vault? Ele fez uma jornada lendária da
 sul depois de derrotar um grande mal. (Puff up chest e olhe orgulhosamente para a distância.) Agora, * I * sou o libertador do meu
 tribo escolhida para procurar o sagrado GECK!}
{547}{}{Ok, então, histórias suficientes ... É melhor eu seguir meu caminho. Elogie o Vault!}

# 29. GECK? (25, 26, 27, 28, 36)
{555}{}{(O resplendor de Renesco desmorona.)}
{556}{}{GECK? Como em 'Garden of Eden Creation Kit?' Vem com uma unidade de replicador básica, holodisc reader with selections
 da biblioteca do congresso e uma pequena lanterna de canetas?}
{557}{}{Sim, mas isso não é importante neste momento. Eu não terminei de falar sobre Arroyo.}
{558}{}{Sim! Minha aldeia está tendo problemas com culturas, e o GECK é necessário para restaurá-las. Você sabe onde posso encontrar um?}
{559}{}{É dito ser selado dentro do Vault 13, ou assim as lendas dizem. Você conhece esse lugar?}
{560}{}{Se você não vai ESCUTAR quando eu recitar as escrituras sagradas, estou fora daqui.}
{561}{}{Poderia ser. Olha, tenho que ir.}

# 30. I HAVEN'T FINISHED TELLING YOU ABOUT ARROYO (29)
{570}{}{Sua aldeia de banhos de banhos de águas remansas será condenada e você junto com ela. Por que é
 um primata como você procurando um GECK?}
{571}{}{Arroyo ... minha aldeia de lavagem de ervas, como você diz ... está tendo problemas com suas colheitas. O GECK é necessário
 para restaurá-los.}
{572}{}{É dito ser selado dentro do Vault 13. Você conhece esse lugar?}
{573}{}{Eu não acho que sinto como compartilhar isso no momento. Adeus.}

# 31. GECK NEEDED TO RESTORE VILLAGE (29, 30)
{580}{}{Hmmmmm. Com certeza poderia fazer isso ... fácil. Se você pudesse encontrar um. Nem sequer sabe onde você começaria a procurar. NCR
 ou Vault City, talvez, mas duvido que eles tivessem um ... ainda ...}
{581}{}{Ainda…?}

# 32. GECK NEEDED TO RESTORE VILLAGE (31)
{590}{}{Ainda assim, esses bastardos auto-justos podem apontar você em uma direção. Se eles falam lentamente e usam pequenas palavras ...}
{591}{}{NCR ou Vault City você diz? Eu irei em busca desses lugares e pergunte aos seus moradores sobre o GECK. Obrigado.}
{592}{}{Por que o GECK não estaria no sagrado Vault 13? As escrituras DIZEM que o GECK está selado dentro do sagrado Vault 13.}
{593}{}{Muito engraçado. Tive algumas outras questões ...}
{594}{}{Ok, então ... vou verificar. Obrigado.}

# 33. GECK NEEDED TO RESTORE VILLAGE (X)
{600}{}{Inferno não, primata. Já ouvi falar de cofres, com certeza, mas não do Vault 13. O mais próximo é Vault City ao nordeste ... e
 Se esses jackanapes aristocráticos habitaram um Vault uma vez, eles certamente não viverão mais lá.}
{601}{}{Vault City, você diz? Eu irei em busca desta cidade de Vault e pergunte aos seus moradores sobre o GECK.
 Obrigado, Renesco. Elogie o Vault!}
{602}{}{"Vaults?" Há mais de um Vault?}
{603}{}{Hmmm. Tive algumas outras questões ...}

# 34. THANKS (32, 33, 35)
{610}{}{Se você estiver indo para Vault City, não me agradeça, primata. Você está melhor em New Reno. Pelo menos as pessoas
 Escolhê-lo para um caixão são honestos sobre isso.}
{611}{}{Ok, então ... Eu vou para Vault City. Elogie o Vault!}
{612}{}{Entendo. Obrigado pelo aviso.}

# 35. MORE THAN ONE VAULT? (33)
{620}{}{Por que você acha que se chama Vault THIRTEEN, spearchucker? O que, sua tribo ficou curta em cérebros ou você apenas
 realizar lobotomias rituais para limpar a minúscula voz do motivo que fala na sua cabeça?}
{623}{}{Sim, você vai adivinhar-me de novo. Obrigado ... pela informação, pelo menos.}

# 36. YOUR VOCABULARY IS IMPRESSIVE (6, 42)
{630}{}{O passado de uma pessoa não é um tópico inteligente de conversa aqui em New Reno. Agora, o que você quer?}
{632}{}{Você soa como um homem educado. Você já ouviu falar de um GECK ou um lugar chamado Vault 13?}
{634}{}{Nada, esquece.}

# 37. GLASSES (3, 42)
{640}{}{(Renesco arranca os óculos de você e coloca-os. Seus olhos se alargam.) Doce Reno! É isso que isso é maldito
 A loja parece. (Frowns.) Que bagunça ... e o que é isso nas prateleiras? Parece uma merda bravo.}
{641}{}{Seja bem-vindo…}
{642}{}{Apreciar.}

# 38. YOU'RE WELCOME (37)
{650}{}{Hmpphh! Eu ... hmmm ... uh ... onde você conseguiu isso?}
{651}{}{Bem, havia este minúsculo radscorpion, ver, e havia esse cientista que estava treinando ele, e ... você sabe o que? Até eu
 não acredite. Basta mantê-los, está bem?}
{652}{}{Digamos que eu os encontrei. Algum lugar.}

# 39. YOU'RE WELCOME 2 (37)
{660}{}{Ei! Espere um minuto! Onde você conseguiu isso?}
{661}{}{Bem, havia este minúsculo radscorpion, ver, e havia esse cientista que estava treinando ele, e ... você sabe o que? Até eu
 não acredite. Basta mantê-los, está bem?}

# 40. I GOT THEM (38, 39)
{670}{}{Bem, eu ... hmnnn ... Estou ... eh, grato. Eu pensei que eu teria que sofrer com esses quadros quebrados para o
 pelo resto da minha vida. Se eu puder fazer algo por você, me avise ... e eu pensarei sobre isso.}
{671}{}{Que tal um desconto?}
{672}{}{Nevermind ... veja, apenas use-os em boa saúde, ok? Tive algumas outras questões ...}
{673}{}{Algum dia - e esse dia talvez nunca venha - vou convidar você para fazer um serviço para mim. Mas até esse dia
 aceite esses óculos como presente no dia do casamento da minha filha.}

# 41. DISCOUNT (40)
{680}{}{Ehhh ...}
{681}{}{Err ...}
{682}{}{Bem…}
{683}{}{OK! OK! Eu vou te dar um desconto! Hmphhh.}
{684}{}{Vamos lá. Apenas um pequeno desconto. Vamos lá…}
{687}{}{Ótimo! Vamos ver o que você tem, "amigo".}
{688}{}{Excelente! Diga, eu tive algumas outras perguntas ...}
{689}{}{Volto a comprar mais tarde.}

# 42. QUESTIONS? (8, 10, 11, 14, 15, 18, 19, 20, 21, 22, 23, 24, 32, 33, 41, 49, 50, 51, 54, 55, 57, 65, 66, 67, 68, 71, 72, 73, 74, 75)
{700}{}{Faça isso rápido.}
{701}{}{Olha, sou um homem ocupado ...}
{702}{}{Bem? Com isso já!}
{703}{}{Sim?}
{704}{}{Já lhe contei sobre minha aldeia Arroyo?}
{706}{}{Você vende Jet para Richard Wright?}
{707}{}{Venho recolher o tributo do Sr. Salvatore.}
{710}{}{Estou à procura de algumas partes da mina para Broken Hills ...}
{711}{}{Você tem um vocabulário interessante ... você é por aqui?}
{712}{}{Deixa pra lá.}

# 43.  TOOLS: SO? (3, 42)
{725}{}{(Olhos estreitos). Então?}
{726}{}{Bem, eu preciso das peças para consertar o purificador de ar em sua mina. Foi-me dito que você poderia me ajudar.}
{727}{}{Bem, eu preciso das peças para consertar o purificador de ar em sua mina. Zaius me enviou. Ele disse, uh ... disse ... uh ... merda.}
{728}{}{Bem, eu preciso das peças para consertar o purificador de ar em sua mina. Zaius me enviou. Ele disse: "O canário está chutando o balde".}

# 44.  TOOLS: SURE. HERE'S SOME MONEY (43)
{735}{}{Sim, tenho algumas peças que podem consertar o purificador de ar. 100 dólares.}
{736}{}{Eu vou levar. Aqui está.}
{737}{}{Como cerca de cinquenta dólares?}
{738}{}{Uh, eu não tenho cem em mim ... volto mais tarde com o dinheiro.}

# 45.  200 OR NOTHING (3, 42, 44)
{745}{}{Inflação devido a irritação gerencial com hagglers. 200 ou nada.}
{746}{}{(Frowns.) 200 ou nada.}
{747}{}{Duzentos?! Você disse uma centena de um segundo atrás!}
{748}{}{Uh, Eu vou levar. Aqui está.}
{749}{}{Uh, eu não tenho duzentos em mim ... Volto mais tarde com o dinheiro.}

# 46.  HE SAID: SHIT (43)
{755}{}{Duvido fortemente que é o que ele disse. Não foi 'O canário deu o balanço no balde', foi?}
{756}{}{Bem, sim.}

# 47.  HE SAID: AND . . . (43, 46)
{760}{}{E…?}
{761}{}{"E?"}

# 48.  SECOND PART? (47)
{765}{}{E a segunda parte foi ...?}
{766}{}{"Segunda parte?" Ele não disse nada sobre uma segunda parte. Esse bastão baixo-baixo -!}

# 49.  HE DIDN'T?! THAT BASTARD! (44, 45)
{769}{}{Apenas testando você. Não há uma segunda parte. Bem, se Zaius lhe enviou, SUPRIMO eu tenho algumas peças de sobra.}
{770}{}{Aqui está. Não os deixe cair.}
{771}{}{Obrigado. Tive algumas outras questões ...}
{772}{}{Uh, obrigado.}

# 50. YOU SELL DRUGS TO WRIGHT'S SON? (7, 10, 42)
{780}{}{Você nem prova nem põe essa acusação sobre mim. Você quer saber quem fez isso, peça a Tweedledum e Tweedledumber
 se eles ainda estão vendendo Jet atado com arsênico.}
{781}{}{'Tweedledum' e 'Tweedledumber?' Quem são eles?}
{782}{}{Jules disse para lhe perguntar. Ele diz que você vende cagar mal.}
{783}{}{Jagged Jimmy disse para lhe perguntar. Ele diz que você vende cagar mal.}
{784}{}{Ambos disseram para lhe perguntar sobre isso. Eles dizem que você vende cagar ruim.}
{785}{}{Eu não acho que foi arsênico ... acho que ele foi envenenado, no entanto.}
{786}{}{Você pode me contar alguma coisa sobre este vaso de jato vazio?}
{788}{}{Eu vou perguntar-lhes então.}

# 51. WHO ARE THEY? (50)
{795}{}{Esse javali Jules e aquela mentirosa repreendeu "Jagged Jimmy". Jules está sempre empoleirado perto da entrada
 para a cidade à procura de visitantes ignorantes para vitimizar, e Jagged Jimmy faz negócios na 2ª Rua para o resto do gado Reno.}
{798}{}{Eles disseram para lhe perguntar. Eles dizem que você vende cagar ruim. Merda que mata pessoas.}
{800}{}{Eu vou falar com eles então.}

# 52. THEY SAID ASK YOU. (51)
{805}{}{Olhe, primata ... você nem sabe sobre o que você está falando.}
{806}{}{Oh, acho que eu -}
{807}{}{Sim? Well then, why don't -}
{808}{}{Deixa pra lá.I had some other qu -}
{809}{}{Olha, é melhor eu ir -}

# 53. THEY SAID ASK YOU 2. (52)
{815}{}{Abra sua boca novamente e até mesmo um WHISPER, mesmo um HINT, chega ao Sr. Wright que eu ... ou você ... pode ter tido qualquer coisa
 para fazer o OD desse menino, nossas vidas não valem a merda brahmin. Se isso acontecer -}
{816}{}{Ah? Então você -}
{817}{}{Eu?! Agora aguarde apenas um -}

# 54. THEY SAID ASK YOU 3. (53)
{825}{}{Se ISSO acontecer, sua MORTE tribal, EU SOU, você vai morrer antes de eu fazer. Agora ... para a última hora, essa criança nunca comprou SHIT
 de mim, entende? Você nunca diz seu nome aqui novamente, ou então me ajude ...}
{826}{}{JULES diz que não vendeu para o filho. JIMMY diz que não vendeu para o filho. VOCÊ diz que não vendeu para ele. 1
 de você está mentindo.}
{827}{}{JULES diz que não vendeu para o filho. JIMMY diz que não vendeu para o filho. VOCÊ diz que não vendeu para ele. Ou
 você está mentindo, ou ... outra pessoa é responsável.}
{828}{}{Você pode me dizer algo mais sobre Richard Wright? Quem ele andou por aí que poderia ter usado chems?}
{829}{}{All right...look, Tive algumas outras questões ...}
{830}{}{Ok, ok ... vou agora.}

# 55. THEY SAID THEY DON'T KNOW. (54)
{835}{}{Posso responder tão fácil. Um desses dois mongrels está mentindo para salvar seus atrasos. Entre os dois, eles
 venda 90% do Jet em Reno, e esse é o único lugar em que o "menino" de que falamos poderia ter conseguido.}
{836}{}{Ou alguém que comprou de um de vocês três. Quem foi seus clientes no mês passado, que poderia ter tido contato?
 com ... a vítima?}
{837}{}{Você pode me dizer algo mais sobre Richard Wright? Ele escondeu alguém que poderia ter usado chems?}
{838}{}{I see...Tive algumas outras questões ...}
{839}{}{Eu estou indo agora.}

# 56. THEY SAID ASK YOU. (55)
{845}{}{Você é bastardo STUPID.}
{846}{}{Você é uma puta estúpida.}
{847}{}{EU DEVO-lhe que não diga seu nome aqui. Saia! Eu te vejo novamente, eu vou te matar. Se o Sr. Wright vem procurando
 Para mim, penso que matei seu menino, você morrerá primeiro.}
{848}{}{Não me ameace, velho ...}
{849}{}{Whoa. Eu estou indo agora.}

# 57. KILLER REVEALED! . . . (55)
{855}{}{Eu não faço ideia. Eu não conhecia o menino, então não conheço seus amigos ou seus hábitos. O único que poderia dizer
 você com certeza está muito ocupado sendo morto no Gólgota para lhe contar.}
{856}{}{Gólgota?}
{858}{}{Talvez eu faça isso. Adeus.}

# 58. TRIBUTE (3, 42)
{865}{}{Então você desperdiçou uma viagem. Paguei o Sr. Salvatore seu "tributo" * duas semanas atrás, * conforme o cronograma. Eu não sei
 quem você é, ou o que você acha que está fazendo, mas você não está recebendo um chip vermelho de mim. Obter.}
{866}{}{Olha, gramps. Pare de me dar um mal momento. Cough up as batatas fritas, ou você estará tossindo sangue.}
{867}{}{Eu sou o representante do Sr. Salvatore. Você me dará o tributo que pedi, e você fará isso agora.}
{868}{}{Vou verificar com o Sr. Salvatore sobre o cronograma, então voltarei.}

# 59. TRIBUTE 2 (58)
{875}{}{Você perde sua audição, menino?}
{876}{}{Você perde sua audiência, garota?}
{877}{}{EU DISSE I. PAGO. A. TRIBUTO. JÁ. * Duas semanas atrás. * Se você fosse realmente de Salvatore, você saberia disso. Agora, git!}
{878}{}{Veja. Última vez: entregue as fichas.}
{879}{}{Você é aquele que perdeu sua audiência. Eu sou o representante do Sr. Salvatore, e você pagará o tributo.}
{880}{}{Eu avisei você, gramps. Parece que estaremos fazendo isso da maneira mais difícil. Hora de morrer.}
{881}{}{Vou verificar com o Sr. Salvatore sobre o tributo, então voltarei.}

# 60. SPEECH SUCCESS (59)
{890}{}{Prove que você é do Salvatore, e CONSIDERAREi dar-lhe as fichas. De outra forma, você não está ficando merda.}
{891}{}{Não preciso provar a mim mesmo. Eu sou seu representante, e isso é tudo o que você precisa saber.}
{892}{}{O que, você acha que esta pistola a laser é apenas para mostrar?}
{893}{}{Se você não me der o tributo em cinco segundos, eu o matarei.}

# 61. SPEECH FAILURE (59, 60)
{900}{}{Saia daqui, vilão penny-ante! Você mostra o seu rosto aqui novamente, e eu vou atirar em você mesmo!}
{901}{}{Eu te avisei. Hora de morrer.}

# 62. SHOW OFFICIAL, CAN'T PAY (3, 42, 60)
{910}{}{Hmmmph. Não importa, não posso pagar. A última coleção quase me apagou.}
{911}{}{Essa não é minha preocupação. Você vai me receber o dinheiro agora. O Sr. Salvatore não quer ouvir suas desculpas.}

# 63. GIVE ME MONEY EVEN THOUGH YOU CAN'T PAY (62)
{920}{}{Me ameaçar não vai ajudar. O Sr. Salvatore quer o dinheiro dele. Eu não tenho isso. Ele ficará bravo comigo, mas ele vai
 fique brava com você, também. Salvatore não gosta de pessoas que o decepcionaram ... é melhor descobrir algo rápido.}
{921}{}{Eu já tenho. Eu pagarei sua participação por esse período. Em troca, você me dará um desconto na sua loja.}
{924}{}{Vou tentar descobrir algo ... Eu voltarei.}

# 64. IN EXCHANGE FOR FREE ACCESS TO YOUR STORE (63)
{930}{}{Agora mantenha-se, você neanderthal ...}
{931}{}{Não vou mais discutir com você. Minha paciência está no fim. Esses são meus termos.}

# 65. THOSE ARE MY TERMS (64)
{940}{}{Eu ... olhe, agora, eu ... hmmmm ... tudo bem, então. Você obtém um ... "desconto".}
{941}{}{Deixe-me ver o seu estoque. Vou fazer minhas "compras" agora.}
{943}{}{Eu não quero nada agora, mas não se preocupe, voltarei.}

# 66. HOW'S THE GLASSES (64)
{950}{}{(Folds arms.) Adequado. Se você está esperando algum folheto por ser um bom samaritano, você é GRAVEL
 confuso. Agora ... o que você quer?}
{951}{}{Maldito seja o que seja o Deathclaw ou o diretor de marketing que você gerou! Você quer algo?! Aqui! AQUI! Pegue isso!
 Pegue tudo o que eu tenho! Qualquer coisa para você DEIXAR-ME SEMPRE!}
{952}{}{Deixe-me ver o seu estoque.}
{953}{}{Eu tive algumas perguntas ...}
{955}{}{O que diabos é isso…?}

# 67. POISONED (50)
{960}{}{Poisoned? Sobre o que você está falando?}
{961}{}{A condição do corpo era consistente com a intoxicação por Radscorpion. Eu acho que ele morreu porque seu Jet foi envenenado,
 NÃO por causa de uma overdose.}
{962}{}{Encontrei um vaso de jato vazio em seu quarto. Tinha vestígios de veneno de Radscorpion.}
{963}{}{Deixa pra lá.Tive algumas outras questões ...}
{964}{}{Esqueça. Eu tenho que ir agora.}

# 68. POISONED 2 (67, 73, 74)
{970}{}{Radscorpion ...? (Renesco congela de repente, como se lembrasse de algo.)}
{971}{}{Você é filho da puta. Você * envenenou * o filho, não é?}
{972}{}{Você sabe algo sobre isso, não é?}

# 69. POISONED 3 (68)
{980}{}{Uau! Agora aguarde apenas um minuto ...!}
{981}{}{Não mexa comigo, Renesco! Você tenta sair daquele, e você vai se juntar a Richard. Compreendo?}
{982}{}{É isso aí. Eu e o Sr. Wright vão conversar um pouco. Bom dia, Renesco ... ou devo dizer "adeus".}

# 70. POISONED 4 (69)
{990}{}{Espere um minuto! Olhe ... eu não VENDO para o garoto! Ele nunca comprou nada de mim! Eu ... foi solicitado
 para fazer alguns Jet atado com veneno de radscorpion, mas ... mas EU NÃO O vendi para a criança!}
{991}{}{Você foi solicitado a fazer Jet envenenado? Para quem?}
{992}{}{A quem você vendeu?}

# 71. POISONED 5 (70)
{995}{}{Os Salvatores pediram - disseram que era uma ... "ordem especial". Eu não sabia que eles iriam dar
 para o garoto Wright. Você tem que acreditar em mim ... Eu não envenena as crianças!}
{996}{}{Apenas adultos, hein, Renesco? Você desculpa o filho da puta ...}
{997}{}{POR QUE você envenenou o Jet? Você tinha que saber que eles iriam matar alguém com isso.}
{998}{}{All right, all right, I believe you. Tive algumas outras questões ...}
{999}{}{Just shut up. Look, Tive algumas outras questões ...}
{1000}{}{Os Salvatores, hein? Penso que o Sr. Wright quer saber sobre isso.}

# 72. RESPONSE (71)
{1005}{}{Os Salvatores POSSAM-me, eles possuem esse lugar, e quando eles querem alguma coisa, eu dou a eles, ou eles vão matar
 eu e me substitui. Nunca quis dizer nenhum mal a esse garoto.}
{1007}{}{Apenas cale a boca. Olha, eu tinha algumas outras perguntas para você ...}
{1008}{}{Sim, tenho certeza de que você teve as melhores intenções enquanto estava espiando aquele jato com veneno. Adeus, Renesco.}
{1009}{}{Mais tarde, Renesco.}

# 73. JET CANISTER (50)
{1020}{}{Está vazio. É uma jarra de jato como as centenas de outras pessoas em todo New Reno. Mais alguma coisa, posso ajudá-lo?}
{1021}{}{Isso pertence a você?}
{1022}{}{Saiba alguma coisa sobre os traços de veneno de radscorpion que estão neste recipiente?}
{1023}{}{Yeah, Tive algumas outras questões ...}

# 74. JET CANISTER (73)
{1030}{}{Não. Mais do que eu possa ajudá-lo?}
{1033}{}{Não. Adeus.}

# 75. GOLGOTHA? (57)
{1040}{}{Gólgota? Mass graveyard outside of town to the south. Follow the stench...the one OTHER than your own.}
{1041}{}{Oh. Tive algumas outras questões ...}
{1042}{}{Você continua me falando assim, Renesco, e você morrerá muito.}
{1043}{}{Obrigado, Renesco.}

{2000}{}{Você expôs o envolvimento de Renesco na morte de Richard Wright.}

# END LINES
{5257}{}{ é tão grande. Eu vou agora}
{5259}{}{ nenhum grito POR QUE VOCÊ MANTA QUE PODE ESTAR PARANDO O DESCANSO}
{6259}{}{ MATAR VOCÊ}
{5260}{}{... * sniff * ... vá buscar um grande irmão para vencê-lo, velho! Então teremos sorvete e ... * sniff * ... BOLO
 e uma grande festa com palhaços e ...}
