# QUICK LOOK
{100}{}{Você vê um grande bandido.}
{101}{}{Você vê Rico.}

# EXAMINE
{150}{}{Você vê um homem enorme e de cara de pedra. Parece que ele come tijolos.}
{151}{}{Você vê o guarda-costas de Rico, Monte. Parece que ele come tijolos.}

# 1. FLOAT DIALOGUE
{175}{}{Hurggg}
{176}{}{Hnrfff}
{177}{}{Snffff}
{178}{}{Urb-luu}
{179}{}{Klurgggg}
{180}{}{Oog}

# 2. CLICK DIALOGUE
{200}{}{Amigo do Monte Monte VOCÊ amigo Monte?}
{201}{}{Eu bateu as pessoas Monte me diga para}
{202}{}{Eu bateu pessoas}
{203}{}{Eu bateu pessoas with fists like playing drum}
{204}{}{Eu gosto de bater}
{205}{}{:: Sorrisos sem dente ::}
{206}{}{:: Scratches self ::}
{207}{}{:: Flexões ::}
{208}{}{Grunhido}
{209}{}{Grunhido - Grunhido.}
{210}{}{Eu não gosto de falar}
{211}{}{Yoo cheiro guuud}
{212}{}{Yoo cheira como mamãe}
{213}{}{Yoo fofo. Eu não vou bater em você}
{214}{}{Yoo me faz corar}
{215}{}{Uhhh ... Me Rico ...}
