# QUICK LOOK
{100}{}{Você vê um dos homens de Salvatore.}

# LOOK (IF THUG HAS LASER WEAPON.)
{150}{}{Você vê um homem mal-humorado. Seu rosto está com uma careta, e ele está olhando para a frente.
 Ele está carregando uma estranha pistola na mão.}
{151}{}{Você vê um homem mal-humorado. Seu rosto está com uma careta, e ele está olhando para a frente.}
{152}{}{Você vê um dos homens de Salvatore. He looks like he hasn't relaxed in years.}
{153}{}{Você vê um dos homens de Salvatore. He is staring straight ahead with a grim expression.}
{154}{}{Você vê um dos homens de Salvatore. He looks silent, deadly, and possibly asleep.}
{155}{}{Você vê um dos homens de Salvatore. He looks silent, deadly, and potentially very bored.}

# 2. FLOAT/CLICK DIALOGUE: ENCLAVE DESTROYED IS TRUE
{160}{}{:: Nods Respeitosamente ::}
{161}{}{Você tem algum músculo para destruir o Enclave como você fez.}
{162}{}{Você é quase tão difícil como Tommy the Balls.}
{163}{}{Ouvi o que você fez no Enclave. A palavra viaja rapidamente.}
{164}{}{Pensou em reproduzir o jogo como um personagem diferente?}

# 3. FLOAT DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=SALVATORE, PRIZEFIGHTER, PORN STAR [SNEAK]
{170}{}{Por que você está se esgueirando?}
{171}{}{Por que o segredo? Alguém está procurando por você?}
{172}{}{Você está tentando manter um perfil baixo?}
{173}{}{Por que você está se esgueirando? Alguém perseguindo você?}

# 4. FLOAT DIALOGUE: PLAYER = MADE MAN, FA=NOT SALVATORE
{180}{}{Bem, se não for}
{181}{}{Você perdeu, amigo? É melhor você sair daqui.}
{182}{}{Este cara está pedindo problemas ...}
{183}{}{Saia daqui. Agora.}
{184}{}{A menos que você esteja procurando problemas, é melhor você sair agora.}
{185}{}{Bem, se não for}
{186}{}{Você perdeu, garota? É melhor você sair daqui.}
{187}{}{Esta garota está pedindo problemas ...}

# 6. FLOAT DIALOGUE: POLITE [ARMED]
{195}{}{Nenhuma arma é permitida aqui.}
{196}{}{Coloque essa arma longe.}

# 7. FLOAT DIALOGUE: FEMALE, PORN STAR, POLITE [ARMED]
{200}{}{Senhorita, tenho medo de ter que pedir-lhe que coloque a arma.}
{201}{}{Senhorita, desculpe, mas armas não são permitidas aqui.}

# 8. FLOAT DIALOGUE: SLAVER [ARMED]
{205}{}{Você! Slaver! Proteja essa arma AGORA.}
{206}{}{As armas não são permitidas aqui, slaver.}
{207}{}{Coloque essa arma longe, escravidão.}
{208}{}{Slaver, preciso que você assegure essa arma agora mesmo.}

# 9. FLOAT DIALOGUE: SLAVER [SNEAK]
{210}{}{Você! Slaver! Pare de se esgueirar por aqui!}

# 10. FLOAT DIALOGUE: NORMAL [ARMED]
{215}{}{Você! Proteja essa arma AGORA.}
{216}{}{As armas não são permitidas aqui.}
{217}{}{Coloque essa arma longe. Now.}
{218}{}{Proteja essa arma agora mesmo.}

# 11. FLOAT DIALOGUE: NORMAL [SNEAK]
{220}{}{Você! Pare de se esgueirar por aqui!}

# 12. FLOAT DIALOGUE: COMPANION: ROBOBRAIN
{225}{}{Os robôs não são permitidos aqui. Saia daqui. Agora.}
{226}{}{Não há robôs. Saia daqui.}

# 13. FLOAT DIALOGUE: COMPANION: MARCUS
{230}{}{Nenhum mutante é permitido aqui. Tire-o para fora daqui. Agora.}
{231}{}{Os mutantes não são permitidos aqui. Tire-o para fora daqui. Agora.}

# 15. CLICK DIALOGUE: POWER ARMOR
{235}{}{Como você vai ao banheiro com essa coisa?}

# 16. CLICK [MADE MAN, FA = SALVATORE]
{240}{}{Senhor.}
{241}{}{Olá senhor.}
{242}{}{Nada para denunciar, senhor.}
{243}{}{Qualquer coisa que você precisa, senhor?}
{244}{}{Qualquer um incomoda você, senhor, avise-nos.}
{245}{}{Cuidado com Tommy the Balls. Ele tem um longo pau e um temperamento curto.}
{246}{}{O Sr. Salvatore tem estado com pouca saúde enquanto o conheço. Ele é muito velho.}
{247}{}{Estas novas pistolas realmente nos permitiram ganhar terreno em New Reno.}
{248}{}{Estas novas pistolas podem parecer estranhas, mas são realmente fáceis de usar.}
{249}{}{Eu atirei este bispo com a minha nova pistola, e percorreu um buraco por ele e
 o muro atrás dele.}
{250}{}{Nenhum dos meninos realmente sabe de onde essas novas pistolas estão vindo. É melhor não perguntar.}
{251}{}{O resto das famílias tem nos dado muito espaço desde o massacre.}
{252}{}{As outras famílias têm nos dado muito espaço desde que recebemos essas novas pistolas.
 Eles sabem o que acontecerá se não o fizerem.}
{253}{}{Estas novas pistolas disparam feixes de luz. Os feixes perfuraram qualquer coisa.}
{254}{}{A família Salvatore tem sido boa para mim. Não há queixas.}
{255}{}{Os bispos falam muito. Salvatores não precisa falar.}
{256}{}{Tudo é silencioso na frente do norte.}
{257}{}{Viu alguns bispos hoje, e eles deixaram claro. Eles estão ficando mais inteligentes.}
{258}{}{Tudo está bastante quieto hoje.}
{259}{}{Senhora.}
{260}{}{Olá Madame.}
{261}{}{Nada para denunciar, senhora.}
{262}{}{Qualquer coisa que você precisa, senhora?}
{263}{}{Alguém que o incomoda, senhora, avise-nos.}

# 18. CLICK [MALE/FEMALE, MADE MAN, FA = NOT SALVATORE]
{275}{}{É melhor ir antes que haja problemas.}
{276}{}{Jogue com inteligência - deixe antes de termos dificuldade.}
{277}{}{Haverá problemas se você ficar ao redor.}
{278}{}{Não sei o que você quer}
{279}{}{Não sei o que você está tentando provar,}
{280}{}{Eu sugiro que você vá embora agora.}

# 19. CLICK [MALE/FEMALE, PRIZEFIGHTER]
{285}{}{Onde você aprendeu a lutar? Você é vicioso.}
{286}{}{Você sabe, Family Salvatore poderia realmente usar alguém como você.}
{287}{}{Você deve conversar com Mason sobre um trabalho.}
{288}{}{Se a cobrança de prêmios perder seu charme, você pode querer considerar juntar-se conosco.}
{289}{}{Eu ganhei US $ 20 em você!}
{290}{}{Ei, campeão! Essa última luta foi ótima!}
{291}{}{Viu você bater no ringue. Maldito bom gancho direito você joga.}
{292}{}{Quanto você bancou?}
{293}{}{Onde você trabalha fora?}
{294}{}{Cuidado com o Masticador. Ele tem gosto de ouvidos.}
{295}{}{Eu pegaria uma bebida se eu não tivesse jogado todo meu dinheiro apostando em seu oponente.}

# 20. CLICK [MALE, PORN STAR]
{305}{}{Algo que eu posso fazer por você?}
{306}{}{Este não é o estúdio da pornografia, amante do menino.}
{307}{}{Tome seu negócio em outro lugar, amante-menino.}

# 21. CLICK [PORN STAR, FEMALE]
{310}{}{Realmente sinto muito ... realmente ... mas não tenho tempo para falar agora. Pare depois do trabalho
 se você estiver livre então.}
{311}{}{Destrói meu coração, mas na verdade não consigo falar agora.}
{312}{}{Vamos agora, você está me distraindo, querido.}
{313}{}{Não posso ajudá-lo.}
{314}{}{Ouço Tommy the Balls quer dar uma seleção privada.}
{315}{}{Não agora, querido. O negócio.}
{316}{}{Eu conversaria, mas o chefe poderia estar assistindo.}

# 22. FLOAT DIALOGUE: SLAVER [ARMED]
{325}{}{Proteja essa arma AGORA, escravidão.}
{326}{}{As armas não são permitidas aqui, slaver.}
{327}{}{Coloque essa arma longe, escravidão.}

# 23. FLOAT DIALOGUE: SLAVER [SNEAK]
{330}{}{Pare de se esgueirar por aqui, escravidão.}
{331}{}{As pessoas que se escondem por aqui fazem meu dedo gatilho comichão.}
{332}{}{Sneaking por aqui pode fazer você disparar, escravidão.}

# 24. FLOAT DIALOGUE: NORMAL [ARMED]
{335}{}{Proteja essa arma AGORA.}
{336}{}{As armas não são permitidas aqui.}
{337}{}{Coloque essa arma longe. Now.}
{338}{}{Proteja essa arma agora mesmo.}

# 25. FLOAT DIALOGUE: NORMAL [SNEAK]
{340}{}{Pare de se esgueirar aqui, ou haverá problemas.}

# 26. [SLAVER, IF BAD REACTION]
{345}{}{Eu não sou a pessoa a quem falar sobre lidar com escravos. Fale com Mason.}
{346}{}{Salvatores já conseguiu todos os escravos que precisamos.}
{347}{}{Não tenho tempo para falar agora.}
{348}{}{Não posso ajudá-lo.}
{349}{}{Olha, não tenho tempo. Você quer uma conversa, vá para Virgin Street e fale com uma prostituta.}

# 27. [SLAVER, GOOD REACTION]
{355}{}{Se você está procurando lidar com alguns escravos, fale com o chefe.}
{356}{}{Não pense que o chefe esteja procurando por mais escravos, mas você pode querer experimentá-lo de qualquer maneira.}

# 28. CLICK [FEMALE/MALE, NO REP, GOOD REACTION]
{360}{}{Procurando por trabalho? Fale com Mason.}
{361}{}{Se você está procurando trabalho, você deve conversar com Mason.}

# 29. CLICK [NO REP, BAD REACTION]
{365}{}{Olha, não tenho tempo. Você quer uma conversa, vá para Virgin Street e fale com uma prostituta.}
{366}{}{Não tenho tempo para falar agora.}
{367}{}{Não posso ajudá-lo.}
{368}{}{Não posso ajudá-lo. Desculpa.}
{369}{}{Não agora, querido. O negócio.}
{370}{}{Eu conversaria, mas o chefe poderia estar assistindo.}
{371}{}{Olha, não tenho tempo para chit-chat.}

# 30. CLICK/FLOAT: LENNY
{380}{}{Que o melhor amigo se afaste agora.}
{381}{}{Se esse ghoul ainda estiver aqui quando eu me virar, vamos queimá-lo.}
{382}{}{Que ghoul está pedindo para ser uma tocha se ela se aproximar.}

# END OF LINES
{1180}{}{. Seu nome será cadáver se ele não sair daqui ...}
{1185}{}{. Seu nome será cadáver se ela não sair daqui ...}
{1278}{}{, mas é melhor levá-lo em outro lugar.}
{1279}{}{, mas eu o levaria para outro lugar.}
