# 0. QUICK LOOK
{100}{}{Você vê Louis Salvatore.}

# 0. LOOK
{150}{}{Você vê um cavalheiro idoso e bem vestido. Ele está carregando um tanque de oxigênio, e ele parece
 para ter dificuldade em respirar.}
{151}{}{Você vê Louis Salvatore. He is carrying an oxygen tank, and he seems
 to have difficulty breathing.}

# 1. FLOAT (WTG)
{200}{}{*Tosse*}
{201}{}{:: Wheeze ::}
{202}{}{*Tosse* *Tosse*}

# 2. FLOAT: INTRUDER (WTG)
{210}{}{Guardas! Gu ... * tosse * * tosse * ... Guardas!}

# 3. PERMISSION = FALSE (WTG, 5)
{215}{}{(Salvatore se volta para você com uma expressão de rosto de pedra. Ele estuda você por uma fração
 de um segundo, então faz um movimento estranho com a mão dele. Ao instante, um alarme toca em todo o cassino.)}
{216}{}{Owwww! Baixa o som! Orelhas prejudicadas! HURT EARS!}
{217}{}{ME CANT TALK OWN RINGING. DESLIGUE, NÓS CONVIDAMOS}
{218}{}{Eu vou te decepcionar, velho! Você nunca mais andará!}
{219}{}{Eu sabia que deveria ter conseguido permissão primeiro ...}
{220}{}{Merda!}
{221}{}{Uh, diga-me que era serviço de quarto.}

# 4. MAIN DIALOGUE INTRO (WTG)
{230}{}{(O homem idoso olha para você. Seu rosto é magro e coberto de manchas de fígado. Ele está segurando
 uma máscara de respiração, que está conectada a um tanque de oxigênio ao lado dele). O que ... você quer de mim?}
{231}{}{Eu quero ... eu não sei o que eu quero}
{232}{}{Eu quero}
{233}{}{Eu}
{234}{}{Afastar-se}
{235}{}{Tenho informações para você.}
{236}{}{Tenho informações para você, Sr. Salvatore.}
{237}{}{Estou à procura de trabalho.}
{238}{}{Sr. Salvatore, você tem reputação de força e justiça. Eu quero trabalhar para você.}
{239}{}{Eu queria saber onde você obtém os lightbringers.}
{240}{}{Palavra é que você teve o filho do Sr. Wright envenenado. Por quê?}
{241}{}{Eu acho que entrei no quarto errado. Perdoe-me.}

# 5. RETARD DEATH WARRANT/TOO MANY QUESTIONS (4, 6, 7, 13, 14, 17, 19, 20, 21, 28, 29, 30, 43)
{250}{}{Eu lhe disse o motivo pelo qual o menino foi morto. Não vai sair desta sala. (Salvatore
 faz um movimento estranho com a mão dele. Ao instante, um alarme toca em todo o cassino.)}
{251}{}{(Salvatore estuda por uma fração de segundo com desgosto, então faz um movimento estranho com a mão dele.
 Ao instante, um alarme toca em todo o cassino.)}
{254}{}{Eu vou te decepcionar, velho! Você nunca mais andará!}

# 6. INFORMATION (4)
{270}{}{(Soma uma respiração profunda da máscara dele, então balança a cabeça.) Você tem
 nada ... que eu preciso saber,}
{271}{}{Não me lembro de me apresentar. Como você sabe meu nome?}
{272}{}{Uh, okay. Well then, Estou à procura de trabalho.}
{276}{}{Na verdade, parece ter entrado no quarto errado. Perdoe-me.}

# 7. HOW DO YOU KNOW ME? (6)
{290}{}{(Olha para você silenciosamente por um minuto. Ele pode ser divertido em sua pergunta
 ou irritado ... é difícil dizer.) Mais uma vez,}
{291}{}{Uh…hmmm. Well, uh, Estou à procura de trabalho.}

# 8. I'M LOOKING FOR A JOB (IMPOLITE) . . . (4, 6, 7)
{305}{}{(Tira uma respiração da máscara de oxigênio, então dá um leve sorriso.) De ... Claro, você
 estamos. E por que eu deveria contratar você?}
{306}{}{Bem, porque não? Nomeie um emprego, eu vou fazer isso. Sou trabalhador e tenho habilidades para
 faça as coisas.}
{307}{}{Uau. Eu disse que estava procurando trabalho? Eu queria dizer que eu estava saindo.}

# 9. I'M LOOKING FOR A JOB (POLITE) . . . (4, 6, 7, 10)
{315}{}{(Tira uma respiração da máscara de oxigênio, então dá um leve sorriso.) De ... claro. Mas
 Eu preciso de um ... sinal de sua boa fé. Uma amostra de sua ... vontade de trabalhar para mim.}
{316}{}{O que você quer que eu faça?}
{317}{}{O que você faria de mim, Sr. Salvatore?}

# 10. I'M HARDWORKING, WELL-ARMED . . . (8)
{325}{}{(Batida ligeiramente a cabeça). Sua ingenuidade não tem lugar aqui. As palavras não são
 suficiente: você deseja trabalhar para Louis Salvatore? Então eu devo saber o quanto eu posso confiar em você.}
{326}{}{Olha, você pode CONTAR em mim.}
{327}{}{Deixe-me provar isso, Sr. Salvatore. Atribua-me uma tarefa.}

# 11. WHAT WOULD YOU HAVE ME DO? (9, 10)
{335}{}{(Toma uma respiração profunda da máscara de oxigênio.) Há ... um homem ... quem
 usou seu ... habilidade com cartas para me roubar. A soma é ... trivial. O insulto não é. Eu o quero matar e
 O dinheiro que ele roubou voltou.}
{336}{}{Quem é esse ladrão?}
{338}{}{Quanto ele roubou?}
{339}{}{Pode ser uma tarefa difícil: Posso ter uma dessas armas a laser que sua família usa?}
{340}{}{Uh, eu não faço hits no contrato. Eu vou sair agora.}

# 12. ANY QUESTION FROM ABOVE (11)
{350}{}{Mason terá ... os detalhes. (Nods at exit.) Vá agora.}
{351}{}{Tudo certo.}
{352}{}{Obrigado, Sr. Salvatore. Eu vou perguntar ao Mason.}

# 13. PUSS-OUT (8, 9, 10, 11, 12, 24, 25, 33, 34, 35, 37)
{360}{}{Então você é de ... não é útil para mim. Saia agora.}
{361}{}{Uh, waitaminute ... Eu mudei de idéia. Eu vou fazer isso.}
{362}{}{Deixe em silêncio.}

# 14. CAN I HAVE ONE OF THOSE LASER WEAPONS? (11, 34)
{370}{}{(Narra seus olhos. Suas próximas palavras são entregues em um silvo raspado.)
 :: Você ainda não se provou. :: Agora vá ver Mason. Ele terá os ... detalhes de sua tarefa.}
{371}{}{Tudo bem então. Esqueça as pistolas por enquanto.}
{372}{}{Eu entendo, Sr. Salvatore. Perdoe minha pergunta. Vou ver Mason.}
{373}{}{Olhe: se você não me armará devidamente, então não posso continuar trabalhando para você.}

# 15. MISSION IS ASSIGNED (WTG)
{380}{}{Fale com Mason. Ele terá os ... detalhes de sua tarefa.}

# 16. LLOYD MISSION ACCOMPLISHED (WTG)
{385}{}{(Salvatore olha para você, tira uma respiração da máscara.) Tem ... você descartou o ladrão?}
{386}{}{Naw ... Lloyd deixou a cidade com o dinheiro.}
{387}{}{Sim. Os abutres provavelmente custam pedaços dele agora mesmo.}
{388}{}{Ainda não.}
{389}{}{Não, Sr. Salvatore. Lloyd deixou a cidade com o dinheiro.}
{390}{}{Sim. Fiz um exemplo dele, Sr. Salvatore.}
{391}{}{Ainda não, Sr. Salvatore.}

# 17. LIE (16)
{400}{}{No entanto ... você disse a Mason que você cuidou da tarefa.}
{401}{}{Bem, sim, mas ...}

# 18. AND THE MONEY? (16)
{405}{}{(Coloca seus dedos juntos.) E ... o dinheiro. Foi recuperado?}
{406}{}{Não, não consegui encontrar o dinheiro.}
{407}{}{Não, Lloyd já gastou o dinheiro.}
{408}{}{Sim.}
{410}{}{Não, Sr. Salvatore, não consegui encontrar o dinheiro.}
{411}{}{Não, Sr. Salvatore, Lloyd já gastou o dinheiro.}
{412}{}{Sim, Sr. Salvatore.}

# 19. NO, NO MONEY (18)
{420}{}{Suas instruções foram para recuperar o dinheiro que ele roubou.
 Você não fez isso?}
{421}{}{Bem, não, porque -}
{422}{}{Uh, eu tenho o dinheiro -}
{423}{}{Bem, você vê, eu não -}

# 20. YES (18, 19)
{430}{}{Vou pegar o dinheiro agora.}
{431}{}{Bem, não tenho isso em mim ...}
{432}{}{Dê-lhe 250 fichas.}
{433}{}{Dê-lhe 500 fichas.}
{434}{}{Dê-lhe 750 fichas.}
{435}{}{Dê-lhe 1000 fichas.}
{436}{}{Dê-lhe 1000 fichas. (This is the correct amount.)}
{437}{}{(Faça uma pausa para isso.)}

# 21. WRONG AMOUNT (20)
{450}{}{Este montante ... não é o valor que foi roubado
 de mim. Talvez você não saiba o quanto foi roubado de mim. Ou talvez você esteja segurando
 fora de mim. De qualquer jeito…}
{451}{}{Oh, bem, eu devo ter desconhecido ...}

# 22. CORRECT AMOUNT (20)
{455}{}{(Salvatore assente com a cabeça enquanto lhe dão o dinheiro, mas ele levanta as mãos a meio caminho
 através da transação.) A ... metade restante é sua.}
{456}{}{Ei, obrigado.}
{468}{}{Obrigado, Sr. Salvatore.}

# 24. I HAVE ANOTHER JOB FOR YOU (22, 23)
{475}{}{(O Sr. Salvatore respira com a máscara). Eu tenho outro ... assunto que exige sua atenção.}
{476}{}{Claro, por que não? Qual é o trabalho - outra tarefa de matar e buscar?}
{477}{}{I am interested in the job, Mr. Salvatore. O que você quer que eu faça?}
{478}{}{Não, acabei de fazer trabalhos. Estou fazendo uma pausa limpa.}
{479}{}{Não há mais empregos para mim, Sr. Salvatore. Eu tenho que ir.}

# 25 MISSION TWO: EXTORTION (24)
{485}{}{Um constituinte no meu ... distrito não me pagou ... homenagem ... pelos serviços que presto.
 Cole-o. Se ele se opuser, informe-o que você é meu ... representante nesta matéria. Falar com
 Mason para os detalhes.}
{487}{}{Sim, Sr. Salvatore. I'll go see him.}
{488}{}{Não, obrigado, não faço trabalhos de extorsão.}

# 26. CAUGHT IN LIE (16)
{495}{}{Você está mentindo para mim. Eu sei que ele ainda mora.}

# 27. TRIBUTE (WTG)
{500}{}{Você já fez o que eu pedi?}
{501}{}{Sim, Sr. Salvatore, tenho o tributo que você me pediu para colecionar.}
{502}{}{Sim, o "tributo" está aqui mesmo.}
{503}{}{Ainda não. I haven't got the old guy to cough it up yet.}
{504}{}{Ainda não, Sr. Salvatore. When I return, I shall have it with me.}

# 28. NO, NO MONEY (27, 29)
{515}{}{Você disse a Mason que você colecionou meu tributo. Você não fez isso?}

# 29. I HAVE THE TRIBUTE (27, 28)
{525}{}{Muito bem. (Ele espera.)}
{527}{}{Dê-lhe 900 fichas.}
{528}{}{Dê-lhe 800 fichas.}
{529}{}{Na verdade, não tenho a homenagem em mim ...}

# 30. WRONG AMOUNT (29)
{540}{}{Este montante ... não é o valor que foi roubado
 de mim. Talvez você não saiba o quanto é o tributo exigido. Ou talvez você seja
 segurando-me. De qualquer jeito…}

# 31. CORRECT AMOUNT (29)
{545}{}{(Salvatore assente com a cabeça enquanto lhe dão o dinheiro.) Você fez ... bem. Você tem
 ganhou 25% do corte.}
{546}{}{(Salvatore acena com a cabeça enquanto lhe dá o dinheiro.) Você fez ... adequadamente. Você tem
 ganhou 10% do corte.}

# 32. COLD REFUSAL (22, 23, 31, WTG)
{555}{}{(Tira uma respiração de sua máscara.) Você fez ... feito como eu perguntei. eu não tenho
 necessidade adicional de seus ... serviços. (Pontos para a saída.) Deixe agora.}
{556}{}{Uh ... ok.}
{557}{}{Eu poderia ter uma dessas pistolas a laser como parte do meu pagamento antes de eu ir?}

# 33. I HAVE ANOTHER JOB FOR YOU (31)
{565}{}{(Tire uma respiração profunda da máscara.) Eu tenho outro ... assunto que eu poderia
 use sua ajuda com.}
{566}{}{Claro, por que não? Qual é o trabalho - mais extorsão?}
{568}{}{Não, terminei fazendo trabalhos de extorsão. Estou fazendo uma pausa limpa.}

# 34. MISSION THREE: GUARD ASSIGNMENT (33)
{575}{}{Uma ... transação sensível ocorrerá em breve. Preciso de um guarda extra ...
 para garantir que a transação funcione sem problemas. Você vai falar com Mason e fazer o que ele direcionar para você.}
{576}{}{O que é essa transação?}
{577}{}{Onde está ocorrendo esta transação?}
{578}{}{Posso ter uma dessas armas a laser que você usa?}
{579}{}{Não posso fazer esta missão agora, Sr. Salvatore. Eu devo ir.}

# 35. WHAT IS THIS TRANSACTION (34)
{585}{}{Mason terá ... os detalhes. Vá agora.}

# 36. CAN I HAVE ONE OF THOSE LASER WEAPONS? (YES) (34)
{595}{}{Yesss. Desta vez, sim. Mas você irá
 transportar outros armamentos também. Fale com Mason sobre os detalhes. Ele vai te dar
 um dos lightbringers.}
{596}{}{Tudo bem então.}

# 37. MADE MAN? (YES) (WTG)
{605}{}{Sentar,}
{607}{}{Eu ficaria honrado, Sr. Salvatore.}
{608}{}{Não posso. Tenho outras obrigações. Obrigado pela oferta, no entanto.}
{610}{}{Eu ficaria honrado, Sr. Salvatore, mas não posso. Tenho outros deveres para outro
 família ... notavelmente, minha mãe.}

# 37a. MADE MAN NO
{615}{}{Isso é uma pena. Não posso correr o risco de permanecer ... silencioso sobre
 o que você viu no deserto. Adeus,}
{616}{}{Uau! Espere um minuto...!}
{617}{}{Oh sim? Traga para que eu possa matar toda a sua família, um por um.}

# 38. MADE MAN? (CHOOSE) (37)
{620}{}{Muito bem. Você deve escolher um nome ...}
{621}{}{E se…}

# 39. MADE MAN? (CHOOSE) (38)
{630}{}{(Nods) Esse é um ... bom nome. Agora, fale com Mason. Ele terá…
algo para você.}

# 40. MADE MAN? (AFTER THE FACT) (WTG)
{640}{}{Saudações,}

# 41. SALVATORE_DONE = TRUE (AFTER THE FACT) (WTG)
{645}{}{Não tenho mais necessidade de seus serviços,}

# 42. SALVATORE CHOKING TO DEATH (WTG)
{650}{}{...}
{651}{}{... hurkkk ...}
{652}{}{... * gasp * ... I ... * tosse * ... * wheeze * ...}
{653}{}{... não ... eu ... * hurrkkk *}
{654}{}{... ajuda ... * suspiro * ... por favor ...}
{655}{}{...Tenha piedade...}
{656}{}{* wheeze *}
{657}{}{...EU...}
{658}{}{...EU...}
{659}{}{:: Pára a respiração. ::}
{660}{}{Heh heh. Eu amo matar pessoas idosas.}

# 43. MR. WRIGHT'S SON POISONED (4, 6, 7)
{675}{}{(O Sr. Salvatore olha para você por um longo tempo em silêncio, depois fala.) Nós
 Salvatores ... vamos governar New Reno. Se uma criança deve morrer para garantir isso, será
 ser feito. Não há outro motivo.}
{676}{}{O que matou o filho de Wright tem a ver com a decisão de New Reno? Isso não faz sentido.}
{677}{}{Você assassinou o FILHO de alguém, Salvatore. Você também pode ter assinado
 seu próprio mandado de morte ...}
{678}{}{Tudo bem então. Eu só queria saber por que você fez isso.}

{800}{}{Você assassinou o chefe Salvatore.}
{825}{}{Você bateu Boss Salvatore.}
{850}{}{Você resolveu a "situação" da Lloyd.}
{875}{}{Você recolheu o tributo do Sr. Salvatore.}
{900}{}{Você se tornou um homem feito da família Salvatore.}
{925}{}{Você concluiu com sucesso a transação secreta.}

# END LINES
{5233}{}{! Quem você?}
{5270}{}{. Agora ... o que você quer de mim?}
{5290}{}{: O que você quer de mim?}
{5605}{}{. Você fez ... tudo o que eu perguntei. Gostaria que você se juntasse à Família Salvatore
 e tornar-se ... um dos meus homens feitos.}
{5640}{}{.}
{5645}{}{.}
