# quick look
{100}{}{Você vê um cientista.}

# examines
{150}{}{Você vê um homem severo com uma prancheta e um hipodérmico. Ele ignora você.}
{151}{}{Ele parece extremamente cansado e irritável.}
{152}{}{Você vê uma mulher cansada. Ela está verificando uma área de transferência e olhando ao redor como
 Se esqueceu de algo.}
{153}{}{Ela está enchendo um hipodérmico, resmungando ligeiramente para si mesma.}

# FLOAT
# (COMPANION = MYRON)
{154}{}{Olá Myron, senhor.}
{155}{}{Myron ... senhor, você tem um minuto ...?}
{156}{}{Qualquer outra palavra quando novos escravos serão entregues, Myron, senhor?}
{157}{}{Myron ... senhor, esses novos resultados são muito promissores ...}
{158}{}{Myron? Um minuto do seu tempo, senhor?}
# (NORMAL)
{159}{}{Onde diabos é Myron ...}
{160}{}{Receba Myron aqui. Ele tem que ver isso.}
{161}{}{Desejo que esses escravos se calassem ...}
{162}{}{Onde eu deixei essa seringa ...}
{163}{}{Alguém viu o Assunto 31? Ele estava aqui apenas um segundo atrás.}
{164}{}{Os slaves trazem mais do Jet Beta.}
{165}{}{Os resultados dos testes do Jet Beta são muito promissores, mas ...}
{166}{}{"Alto" dura 15 minutos a uma hora ... calcule um período de dose / hora ... hmmmmnnn.}
{167}{}{O assunto 12 ainda continua sangrando nos pulmões ...}
{168}{}{Essa é a quinta vez que o Assunto 12 sofreu convulsões ... até a dose, veja o que acontece ...}
{169}{}{Bem, qual o índice de alucinações que ele estava tendo?}
{170}{}{Verifique a frequência cardíaca. Se ainda estiver dentro de limites toleráveis, até a dosagem.}
{171}{}{Por que o escravo no grupo controle se matou? Nós não estávamos nem testando ela!}

# CLICK
# (COMPANION = MYRON)
{200}{}{Os testes estão sendo realizados conforme previsto, Myron.}
{201}{}{Esta nova tensão de Jet é extremamente formadora de hábitos, senhor. Os escravos são quase
 Dispostos a matar uns aos outros por isso.}
{202}{}{Os escravos preferem pegar Jet do que comer, é tão potente.}
{203}{}{Quem são essas pessoas com você, Myron? Novos assuntos?}
{204}{}{O terceiro grupo de teste parece estar fazendo o melhor de todos os grupos, Myron, senhor.}
{205}{}{Myron, acho que o próximo grupo de testes deve incluir pelo menos três crianças, senhor.}
{206}{}{Myron, senhor, o assunto 46 teve um ataque cardíaco; Estamos restringindo doses a seis vezes
 Um dia a partir de agora.}
{207}{}{Myron? Precisamos de um novo carregamento de hipodermia da Vault City, em breve. Não podemos
 Continue reutilizando estes.}
{208}{}{Myron, finalmente! Mais uma palavra quando novos escravos serão entregues, senhor?}
{209}{}{Myron, senhor, mudamos três escravos do grupo de controle para o grupo de teste porque
 Das falhas respiratórias que tivemos na semana passada.}
{210}{}{Myron, senhor ... tivemos que atirar em um escravo por tentar escapar. Que desperdício.}
{211}{}{Myron ... este novo alucinógeno suave que você desenvolveu é promissor, mas não é tão hábito como o jato ...}
# NORMAL
{212}{}{Se você tiver alguma sugestão, escreva-a em um pedaço de papel e depois coloque-o bem
 Na lixeira lá.}
{213}{}{Sim, sim?}
{214}{}{Não conseguiremos obter resultados se você continuar interrompendo-nos.}
{215}{}{Parece que eles deixaram todos e sua mãe correrem aqui hoje em dia ...}
{216}{}{O que você quer?}
{217}{}{Por favor, desculpe-me, * eu * tenho trabalho para fazer.}
{218}{}{Se você tiver dúvidas, fale com os guardas, não comigo.}
{219}{}{Sim, tenho certeza de que tudo o que você precisa é de * grande * importância, mas eu tenho deveres
 Do meu próprio.}
{220}{}{Você está autorizado a estar aqui?}
{221}{}{Quem te permitiu aqui?}
{222}{}{Quando Myron ouve estranhos estavam entrando no laboratório ...}
{223}{}{Você tem os resultados do teste que eu pedi ... oh, desculpe. Achei que você era um técnico de laboratório.}
{224}{}{Muito ocupado para conversar agora, desculpe.}
{225}{}{Precisa de uma nova safra de escravos em breve ... estes estão ficando sem vapor.}
