{100}{}{Você vê ... Sheb.}

{150}{}{Você vê um homem magro com roupas azuis brilhantes. Como se suas roupas não fossem suficientemente altas, ele também está gritando no topo de seus pulmões.}

{200}{}{Booty, booty, boo-tay!}
{201}{}{Venha, amantes de botas!}
{202}{}{Aqui, no Cat's Paw, estamos reduzindo os preços ao meio!}
{203}{}{Dê-nos uma oferta em nossa principal seleção de saque! É uma explosão de botas!}
{204}{}{Nós temos botas brancas, botas pretas, botas do sul, botas do norte ...}
{205}{}{Nós conseguimos um pingo quente, um saque frio, nós conseguimos um botín fresco, nós conseguimos ... :: snfff :: ... * maldito * botin ...}
{206}{}{Nós conseguimos um saqueio tribal, nós conseguimos um saque de mutante, um saque de radscorpion, um saque de robô.}
{207}{}{Nós até conseguimos um saque de brahmin, um saque de ghoul, um saque de morte.}
{208}{}{Come on, you want booty? Venha, amantes de botas!}
{209}{}{If we don't got it, you don't want it! Venha, amantes de botas!}
{210}{}{Atenção compradores de botas! Aproveite esta venda de botas!}
{211}{}{Compre um pedaço de botina no preço normal, n 'você receberá outro pedaço de montante de igual ou menor valor para apenas um chip!}
{212}{}{Tente e vença o saque para um chip!}
{213}{}{Se você conseguir um saque mais barato em qualquer lugar ... POMA!}
