0. QUICK LOOK (NORMAL)
{100}{}{Você vê uma máquina caça-níqueis.}
1. QUICK LOOK (HIGH-ROLLER)
{101}{}{Você vê uma slot machine brilhante.}

0. LOOK (NORMAL)
{150}{}{Você vê uma máquina caça-níqueis. You swear you can see it looking at you out of the corner of your eye.}
{151}{}{Você vê uma máquina caça-níqueis. Its shiny frame and golden handle gleam seductively beneath New Reno's lights.}
{152}{}{Você vê uma slot machine brilhante. It is intended for high-rollers…minimum bet is }
{153}{}{ salgadinhos.}
{154}{}{Você vê uma slot machine brilhante.}

2. FLOAT DIALOGUE (PLAYER = DRUNK OR HIGH) (WTG)
{160}{}{* Venha tocar-me por um segundo, cowboy. *}
{161}{}{* Olá, marinheiro. *}
{162}{}{* Coloque um chip, puxe o braço. Eu serei gentil com você. *}
{163}{}{* Tick ... Tick ... Tiiiiick ... *}
{164}{}{*Olá linda. Venha me tocar por um segundo. *}
{165}{}{* Olá, linda. *}
{166}{}{* Bem, você não é uma lil 'coisa bonita. Por que você não vem me tocar? *}

3. FLOAT DIALOGUE (NORMAL) (WTG)
{175}{}{* Ding *}
{176}{}{* Bing *}
{177}{}{* Kaaa-ching *}
{178}{}{* Zzzzzzz *}
{179}{}{* Ring-a-ling *}
{180}{}{* Dingity-ding *}

4. RETARD (WTG)
{185}{}{Você vê uma estranha caixa de metal dourado com três olhos e um braço. É uma das coisas mais bonitas que você já viu.}
{186}{}{Eu}
{187}{}{ quem você}
{188}{}{Eumiss MOM. }
{189}{}{ miss ARR-YO. Euwant go home}
{190}{}{Agite a mão}
{191}{}{Você é um mutante estranho}
{192}{}{Elogie o Vault! Elogie o Vault!}
{193}{}{Você é um chip de água?}
{194}{}{Vagueie, procure outras coisas brilhantes}
{195}{}{Sair.}

5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{205}{}{A estranha caixa de metal dourada com três olhos e um braço não respondem.}
{206}{}{MIM}
{207}{}{ ME RESPONDA}
{208}{}{Agite a mão}
{209}{}{Euchild of Vault Dweller You talk to me NOW}
{210}{}{Você é um mutante estranho}
{211}{}{Você é um chip de água?}
{212}{}{Vagueie, procure outras coisas brilhantes}
{213}{}{Sair.}

6.  RETARD PULLS HANDLE (4, 5)
{220}{}{Você agarra seu braço e agita calorosamente. Como você faz, existe um * bzzzzzzz *, e a caixa fala! "Por favor ... insira ... dinheiro".}
{221}{}{Aighhhhh! Robô! Robô! Runnnnn}
{222}{}{Sair.}

7.  NO MONEY (WTG, 9)
{225}{}{Você tem dinheiro suficiente para jogar slots, e você amaldiçoa sua pobreza. Talvez outro tempo ...}
{226}{}{Sair.}

8.  PLAY. . . ? (WTG, 14, 15)
{230}{}{Você vê uma máquina caça-níqueis. Its shiny frame and golden handle gleam seductively beneath New Reno's lights. It's coin slot beckons you, and you feel your face flush with anticipation.}
{231}{}{(Your hand quivers as you reach for your salgadinhos. The machine continues to whisper at you.) *Come on, sugar…that's it…come on now…don't tease…*}
{232}{}{(Your hand quivers as you reach for your salgadinhos. The machine continues to whisper at you.) *Come on, honey…that's it…grab the handle…grip it firmly…come on now…*}
{233}{}{Você tem}
{234}{}{ Chip para o seu nome. Arriscar tudo?}
{235}{}{Você tem}
{236}{}{ salgadinhos. Aposta}
{237}{}{ lasca?}
{238}{}{Aposta}
{239}{}{ salgadinhos?}
{240}{}{Ligue-o uma noite.}
{241}{}{Ligue para um dia.}

9.  LOOOOOOSER (8)
{245}{}{A câmara gira, e ... não aparece nada.}
{246}{}{NADA. NADA! Você a ouve rindo, e você fica enfurecido ... os Bouncers são forçados a tirar seu corpo gritando da máquina.}
{247}{}{(A máquina ri.) * Obtive o que eu queria sair dessa relação. Desculpe, querido. Não deixe a porta do cassino bater na bunda no caminho para fora. Ja ha ha ha ha ha *}
{248}{}{Agora você tem}
{249}{}{ Pedaços restantes. Persiga suas perdas e continue jogando?}
{250}{}{Você tem}
{251}{}{ Chip esquerda. Arriscar tudo?}
{252}{}{Você está quebrado. Você é obrigado a chamá-lo uma noite.}
{253}{}{Você está quebrado. Você é obrigado a chamá-lo um dia.}
{254}{}{Ligue-o uma noite.}
{255}{}{Ligue para um dia.}

10.  WIN x1 (8)
{260}{}{Três punhais. Você se equilibra.}
{261}{}{(A máquina continua a sussurrar para você.) * Venha, sugue ... acontece com todos pelo menos uma vez ... tente novamente ... por favor ... *}
{262}{}{(A máquina continua a sussurrar para você.) * Venha, querido ... tente novamente ... pegue o punho ... aperte-o firmemente ... venha agora ... *}
{263}{}{Você ainda tem}
{264}{}{ lasca. Continue jogando?}
{265}{}{Você ainda tem}
{266}{}{ salgadinhos. Keep playing?}
{267}{}{Ligue-o uma noite.}
{268}{}{Ligue para um dia.}

11.  WIN x2 (8)
{275}{}{Três balas! Você duplica seu dinheiro!}
{276}{}{(A máquina dá um suspiro de prazer.) * É isso, sugah ... continue puxando a alça ... mais rápido, mais difícil, mais rápido ... venha agora ... *}
{277}{}{(A máquina dá um gemido de prazer.) * É isso, querido ... continue puxando a alça ... mais rápido, mais difícil, mais rápido ... venha agora ... *}
{278}{}{Agora você tem}
{279}{}{ salgadinhos! Continue jogando?}
{280}{}{Ligue-o uma noite.}
{281}{}{Ligue para um dia.}

12.  WIN x3 (8)
{290}{}{Três granadas! Cacete! Você triplica seu dinheiro!}
{291}{}{(A máquina grita de prazer enquanto os chips batem na bandeja.) * Aieeeeeeee! É isso mesmo, sugah! Oh Deus, sim! Sim! Sim, novamente! Mais rápido! Mais difíceis! O que você está esperando?! Novamente!*}
{292}{}{(A máquina grunhiu de prazer à medida que os chips batem na bandeja.) * Ennnnghhhh! É isso, querido! Quem é seu pai?! Quem é seu pai?!! Faça isso novamente! Diminuir esta vez! Mais difíceis!*}
{293}{}{Faça uma dança de vitória, gire seus quadris e jogue seus braços para cima no ar, então respire fundo e continue jogando.}
{294}{}{Vamos, granadas! O bebê precisa de um novo par de sapatos! (Continue jogando.)}
{295}{}{Agora você tem}
{296}{}{ salgadinhos. Keep playing?}
{297}{}{Ligue-o uma noite.}
{298}{}{Ligue para um dia.}

13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{305}{}{(Você vê uma máquina caça-níqueis. Its shiny frame and golden handle gleam seductively beneath New Reno's lights. Its coin slot beckons you, and you feel your face flush with anticipation. As you stare at it, one of its three windows winks at you. From the coin slot you hear a throaty voice.) *Well, my word! Helloooo there, sugah. Show a girl a good time?*}
{306}{}{(Você vê uma máquina caça-níqueis. Its strong, rugged frame and golden handle gleam like a sun god beneath New Reno's lights. Its coin slot beckons you seductively, and you feel your thighs burn with anticipation. As you stare at it, suddenly a heavy male voice whispers from the coin slot.) *Ain't seen a pretty woman like you around before, miss. You looking to take a chance?*}
{307}{}{:: Pinch Self ::}
{308}{}{Uh ... olá?}
{309}{}{:: Respire fundo, vá embora. ::}

14. DRUNK CONVERSATION 1 (13)
{315}{}{* Eu ainda estou aqui, linda. * (A máquina tragamigão diminui a voz.) * Olhe, venha ... você quer fazer uma aposta? *}
{316}{}{* Ah, ainda está aqui, sugah. * (A máquina caça-nufal diminui a voz.) * Você é um bom homem de hunka, você sabe disso? Venha agora ... você quer pegar algumas fichas no lil 'old me? *}
{317}{}{Whooo ARE yoooo?}
{318}{}{Surrh vou apostar uma aposta em yooo}
{319}{}{Acho que é melhor deixar antes de colocar algo em você, eu posso me arrepender.}
{320}{}{:: Respire fundo, vá embora. ::}

15. DRUNK 2 (14)
{325}{}{* Eu sou seu homem ideal. * (A máquina caça-níqueis dá uma piscadinha.) * Me dê algumas fichas, e eu vou agradar você de maneiras que nenhum homem NUNCA gostou. *}
{326}{}{* Eu sou sua mulher ideal, açúcar. Tudo o que quer, é uma pequena atenção. Você pode me ajudar muito velho? Vamos, apenas um chip ou dois? *}
{327}{}{Não podemos conversar}
{328}{}{Surrh vou apostar uma aposta em yooo}
{329}{}{Acho que é melhor deixar antes de colocar algo em você, eu posso me arrepender.}
{330}{}{:: Respire fundo, vá embora. ::}

16. DRUNK 3 (15)
{335}{}{* Curso que podemos, querido, claro que podemos. * (A máquina caça-níqueis parece simpatica.) * O que está preocupando sua linda cabeça pequena? *}
{336}{}{* Curso que podemos, sugah, claro, podemos. * (A máquina caça-níqueis parece simpatica.) * O que está perturbando você, bonito? *}
{337}{}{Eumiss MOM and miss ARROYO and I…canna find the GECK and…*sniff*}
{338}{}{Eumiss MOM and Arroyo wuz ATTACKED and I…dunna where they are…and…*sniff*}
{339}{}{Euneed to fix big ship…and I dunna know HOW…and muh-muh-my Mom's GONE and…*sniff*}
{340}{}{Eu lancei o jogo ... anna agora eu sou jusht wandrin 'round e ... ah estou preocupado com tudo o mais e ... * sniff *}
{341}{}{É provável que Fhallowt também não seporte meu cartão 3D Fxxxx e eu gasto tanto * monee * onnit e * sniff *}
{342}{}{Eu tentei obter um bom charactrr, mas acho que eu gastei o ponto todo * errado * ... n 'agora eu vejo um shitsee charactrr ... n' ... * sniff *}
{343}{}{Ahhm havinn um conversashun com um slot macheen, ah muito ruim fora}
{344}{}{:: Respire fundo, vá embora. ::}

17. DRUNK 4 (16)
{350}{}{* Lá, lá ... não incomode sua linda cabeça sobre isso, não mais ... deixe-me cuidar de tudo. Vamos, descanse sua cabeça em mim. Ai está. Bota tudo pra fora.*}
{351}{}{* Lá, lá ... não se preocupe mais com isso, sugah ... deixe-me cuidar de tudo. Vamos, descanse sua linda cabeça em mim. Ai está. Bota tudo pra fora.*}
{352}{}{Obrigado, slot macheen * sniff * você é o melhor}
{353}{}{Yooo onlee NICE pershun eu conheci até agora todo o outro é tão meeen n 'tentou ta Me dói e pegue meu dinheiro e ... * sniff *}
{354}{}{:: Respire fundo, vá embora. ::}

18. DRUNK 5 (17)
{360}{}{(Você descansa sua cabeça cansada na máquina).}
{361}{}{* Você vai ficar bem, querido? Eu não me sinto confortável deixando você sair sozinho quando você está assim. *}
{362}{}{* Você vai ficar bem, sugah? Ah, não sinta-se à vontade deixando você sair sozinho quando você é assim. *}
{363}{}{Eu serei todo o rite ... thasnk fer conversando comigo, slot macheen Eu te amo}

19. DRUNK 6 (18)
{370}{}{(Uma lágrima parece se formar em uma das janelas.)}
{371}{}{* Você é a única heroína que recebemos neste mundo de dois buracos e ladrões,}
{372}{}{. Você cuida de si mesmo, você ouve, querido? * (Desaparece.) * É melhor ir antes de começar a agir de forma não familiar. *}
{373}{}{* Você é o único herói que conseguimos neste mundo de dois buracos e ladrões,}
{374}{}{. Você ... você ... cuide-se agora, você ouve, sugah? * (Desaparece.) * É melhor ir antes de começar a soluçar. *}
{375}{}{Byeeeee}

20.  PLAY, HIGH-ROLLING MACHINE. . . ? (WTG, 14, 15, 21, 22, 23, 24)
{380}{}{Você vê uma slot machine com alta rotação - a aposta mínima é}
{381}{}{ salgadinhos. Its glittering frame and golden handle gleam seductively beneath New Reno's lights. It's coin slot beckons you, and you feel your face flush with anticipation.}
{382}{}{(Your hand quivers as you reach for your salgadinhos. The machine continues to whisper at you.) *Come on, sugar…that's it…come on now…don't tease…*}
{383}{}{(Your hand quivers as you reach for your salgadinhos. The machine continues to whisper at you.) *Come on, honey…that's it…grab the handle…grip it firmly…come on now…*}
{384}{}{Você tem}
{385}{}{ Chips restantes. Arriscar tudo?}
{386}{}{Você tem}
{387}{}{ salgadinhos. Aposta}
{388}{}{ salgadinhos?}
{389}{}{Aposta}
{390}{}{ salgadinhos?}
{391}{}{Ligue-o uma noite.}
{392}{}{Ligue para um dia.}

21.  LOOOOOOSER, HIGH-ROLLING (20)
{400}{}{A câmara gira, e ... não aparece nada.}
{401}{}{NADA. NADA! Você a ouve rindo, e você fica enfurecido ... os Bouncers são forçados a tirar seu corpo gritando da máquina.)}
{402}{}{(A máquina ri.) * Obtive o que eu queria sair dessa relação. Desculpe, querido. Não deixe a porta do cassino bater na bunda no caminho para fora. Ja ha ha ha ha ha *}
{403}{}{Agora você tem}
{404}{}{ Pedaços restantes. Persiga suas perdas e continue jogando?}
{405}{}{Você tem}
{406}{}{ Chips restantes. Arriscar tudo?}
{407}{}{Você não pode se dar ao luxo de jogar mais. Você é obrigado a chamá-lo uma noite.}
{408}{}{Você não pode se dar ao luxo de jogar mais. Você é obrigado a chamá-lo um dia.}
{409}{}{Ligue-o uma noite.}
{410}{}{Ligue para um dia.}

22.  WIN x1, HIGH-ROLLING (20)
{415}{}{Três bombas ... você se equilibra.}
{416}{}{(A máquina continua a sussurrar para você.) * Venha, sugue ... acontece com todos pelo menos uma vez ... tente novamente ... por favor ... *}
{417}{}{(A máquina continua a sussurrar para você.) * Venha, querido ... tente novamente ... pegue o punho ... aperte-o firmemente ... venha agora ... *}
{418}{}{Você ainda tem}
{419}{}{ salgadinhos. Keep playing?}
{420}{}{Ligue-o uma noite.}
{421}{}{Ligue para um dia.}

23.  WIN x2, HIGH-ROLLING (20)
{425}{}{Três armas nucleares! Você duplica seu dinheiro!}
{426}{}{(A máquina dá um suspiro de prazer.) * É isso, sugah ... continue puxando a alça ... mais rápido, mais difícil, mais rápido ... venha agora ... *}
{427}{}{(A máquina dá um gemido de prazer.) * É isso, querido ... continue puxando a alça ... mais rápido, mais difícil, mais rápido ... venha agora ... *}
{428}{}{Agora você tem}
{429}{}{ salgadinhos! Continue jogando?}
{430}{}{Ligue-o uma noite.}
{431}{}{Ligue para um dia.}

24.  WIN x3, HIGH-ROLLING (8)
{435}{}{Três Nuvens de Cogumelo! Você triplica seu dinheiro!}
{436}{}{(A máquina grita de prazer à medida que os chips batem na bandeja.) * Aieeeeee! É isso mesmo, sugah! Oh Deus, sim! Sim! Sim, novamente! Mais rápido! Mais difíceis! O que você está esperando?! Novamente!*}
{437}{}{(A máquina grunhiu de prazer à medida que os chips batem na bandeja.) * Ennnnghhhh! É isso, querido! Quem é seu pai?! Quem é seu pai?!! Faça isso novamente! Diminuir esta vez! Mais difíceis!*}
{438}{}{Faça uma dança de vitória, gire seus quadris e jogue seus braços para cima no ar, então respire fundo e continue jogando.}
{439}{}{Vamos chamar nuvens de cogumelos! O bebê precisa de um novo par de sapatos! (Continue jogando.)}
{440}{}{Agora você tem}
{441}{}{ salgadinhos. Keep playing?}
{442}{}{Ligue-o uma noite.}
{443}{}{Ligue para um dia.}

# use gambling skill on table, the +1 is for high roller tables
# critical failures
{1000}{}{As chances não parecem bem.}
{1001}{}{As chances parecem corretas.}
# failures
{1005}{}{Você não pode avaliar as probabilidades para certo.}
{1006}{}{As chances parecem ser sobre a razão.}
# success
{1010}{}{As chances parecem corretas.}
{1011}{}{As chances não parecem corretas.}
# critical success
{1015}{}{As chances parecem corretas.}
{1016}{}{As chances não parecem corretas.}
