# QUICK LOOK
{100}{}{Você vê um escravo doentio.}
{101}{}{Você vê um escravo queimado.}
{102}{}{Você vê um escravo.}

# EXAMINES
# 1. [SICKLY MALE SLAVE]
{150}{}{Você vê um homem de aparência quebrada. Os olhos dele dardos pela área, como se estivessem seguindo algum inseto invisível.}
{151}{}{Você vê um escravo doentio. He looks terribly frightened, and his eyes seem unable to focus on you.}
{152}{}{Você vê um escravo doentio. His clothes are in tatters, and his skin hangs loosely on his flesh.}
{153}{}{Você vê um escravo doentio. He is coughing violently, and his tattered shirt has blood stains on the front of it.}
{154}{}{Você vê um escravo doentio. The smell of dried urine and feces emanates from him.}
{155}{}{Você vê um escravo doentio. His teeth have fallen out, and his eyes are bloodshot.}
{156}{}{Você vê um escravo doentio. Some sort of rash covers his face and neck, and he scratches occasionally.}
# 2. [SICKLY FEMALE SLAVE]
{160}{}{Você vê uma mulher que parece quebrada. Ela olhou fixamente no chão, como se tivesse medo de procurar.}
{161}{}{Você vê um escravo doentio. She looks terribly frightened, and her eyes seem unable to focus on you.}
{162}{}{Você vê um escravo doentio. She doesn't seem to notice the bloodflies that land on her face and arms.}
{163}{}{Você vê um escravo doentio. Her clothes are in tatters, and her skin hangs loosely on her flesh.}
{164}{}{Você vê um escravo doentio. She is wheezing with every breath, and streams of mucus run from her nose.}
{165}{}{Você vê um escravo doentio. The smell of dried urine and feces emanates from her.}
{166}{}{Você vê um escravo doentio. She is scratching at some sort of rash that covers her face and neck.}
{167}{}{Você vê um escravo doentio. She looks like she is trying to cry, but no tears will come.}
# 3. [MALE SLAVE, DRUGGED]
{170}{}{Você vê um homem de aparência lenta. Ele está olhando para a frente com uma expressão vaga.}
{171}{}{Você vê um escravo queimado. His eyes dart around the area, never focusing on any one thing.}
{172}{}{Você vê um escravo queimado. As you watch, he bites his forearm and peels back some skin with his teeth, slowly chewing it.}
{173}{}{Você vê um escravo queimado. He has a faint smile on his face, but his eyes are glazed and vacant.}
{174}{}{Você vê um escravo queimado. He is gazing vacantly out into space, drool coming from his lips.}
{175}{}{Você vê um escravo queimado. As he sees you, he winces and gives a painful smile, as if you are too bright to look at.}
4. [DRUGGED FEMALE SLAVE]
{180}{}{Você vê uma mulher tremendo. Ela está olhando para o chão, como se tivesse medo que ele desaparecesse se ela deixasse de olhar para ele.}
{181}{}{Você vê um escravo queimado. She is giggling to herself, and there are traces of blood on the corners of her mouth.}
{182}{}{Você vê um escravo queimado. There are track marks on her arm intermixed with bruises and lash marks.}
{183}{}{Você vê um escravo queimado. She blinks rapidly, as if her eyes are dry.}
{184}{}{Você vê um escravo queimado. She is scratching the back her hands, so much so that the skin is tearing off.}
{185}{}{Você vê um escravo queimado. Vomit stains cover the front of her shirt, and she smells faintly of turpentine.}
# 5. [MALE SLAVE, BEATEN]
{190}{}{Você vê um homem magro. As marcas de lâmina cobrem seu corpo, e ele olha humildemente no chão, como se estivesse esperando ordens.}
{191}{}{Você vê um escravo espancado.}
{192}{}{Você vê um escravo fino. As marcas de lâmina cobrem seu corpo, e ele olha humildemente no chão, como se estivesse esperando ordens.}
# 6. [DRUGGED FEMALE SLAVE]
{195}{}{Você vê uma mulher tremendo. Seu corpo está coberto de marcas de chicotadas, e suas roupas estão em farrapos.}
{196}{}{Você vê uma escrava feminina.}
{197}{}{Você vê uma escrava feminina. She is shivering slightly, and her body is covered with lash marks.}

# FLOAT:
# 7. [SICKLY SLAVE]
{200}{}{:: Snnnffff ::}
{201}{}{:: Huhhhhk ::}
{202}{}{:: Tosse ::}
{203}{}{:: Scratches self. ::}
{204}{}{:: Brushes away flies ::}
# 8. [DRUGGED SLAVE]
{210}{}{:: Snnnffff ::}
{211}{}{* Giggle *}
{212}{}{Heeeeeeee}
{213}{}{Hee heeeee hee ... hee ...}
{214}{}{EeeeEEEEeeeeEEEE}

# CLICK:
# 9. [SICKLY SLAVE]
{220}{}{:: Looks blankly to you ::}
{221}{}{:: Crite em silêncio ::}
{222}{}{:: Olha para você sem limites ::}
{223}{}{:: Pisca em você estupidamente ::}
{224}{}{:: Dá uma tosse sibilante ::}
{225}{}{:: Mumble algo que você não pode distinguir. ::}
{226}{}{Hnnnnh ... .hnnn}
{227}{}{:: Wipes nose ::}
{228}{}{Hunnnnnh}
{229}{}{Rrrurrr..rr..:: Tosse ::}
# 10. [DRUGGED SLAVE]
{240}{}{:: Rubs eyes ::}
{241}{}{:: Snorts como um porco ::}
{242}{}{:: Rasca a cabeça e depois esfrega os olhos ::}
{243}{}{Hee heeeee hee ... hee ...}
{244}{}{Hootchie Kootchie Boochie}
{245}{}{Foo-Fooooo}
{246}{}{EeeeEEEEeeeeEEEE}
{247}{}{Meus olhos são grandes moscas negras}
{248}{}{Boooogety boooo}
{249}{}{Hwoo Hwooo}
{250}{}{Moooooooo}
{251}{}{Eu, meu bem, eu, meu bem}
{252}{}{Duplo mais bom}
# 11. [BEATEN SLAVE vs. SLAVER]
{260}{}{Sim, já sou de propriedade. Meu mestre tem os papéis.}
{261}{}{Por favor, deixe-me estar. Eu já sou de propriedade de outra pessoa.}
{262}{}{Peço-lhe: você viu dois filhos, cabelos escuros ...? Eles foram levados por outros escravos há dois anos e vendidos pelo Norte.}
{263}{}{Por favor ... não tenho permissão para falar com ninguém.}
{264}{}{Por favor ... deixe-me estar. O meu mestre voltará em breve.}
{265}{}{Se meu mestre me atrapalhar conversando com um escravo, eu serei espancado.}
{266}{}{Eu já tenho um mestre. Ela não ficará feliz se você continuar a falar comigo.}
{267}{}{Eu não posso falar com você. Eu tenho deveres.}
{268}{}{Se eu for pego falando com um escravo, eles começarão a testar os chems em mim.}
{269}{}{Vá embora, escravidão. Eu não quero nenhum problema.}
{270}{}{Escapar? Eu ... nunca tentei fugir daqui. Eu não ousaria desobedecer meu mestre.}
# 12. [BEATEN AND/OR GENERIC SLAVE]
{280}{}{Se eles me pegarem conversando com você, eles começarão a testar chems em mim.}
{281}{}{Eu costumava trabalhar com esse outro escravo, mas ele morreu de uma overdose alguns dias atrás.}
{282}{}{Eles testam novos chems sobre nós. Alguns são venenosos.}
{283}{}{Meu mestre é ... bom para mim.}
{284}{}{Meu mestre disse não falar com os outros.}
{285}{}{Por favor ... Não tenho permissão para falar com você.}
{286}{}{Por favor, deixe-me estar. O meu mestre voltará em breve.}
{287}{}{Se meu mestre me atrapalhar conversando com você, ele vai me vencer.}
{288}{}{Meu mestre é bom. Ele não me bate com frequência.}
{289}{}{Não sinto falta da minha família. Meu mestre é gentil.}
{290}{}{Eu fui tirado de uma aldeia tribal ao norte daqui. A vida é muito ... melhor aqui.}
{291}{}{Fui capturado pela primeira vez no Den.}
{292}{}{Eu não posso falar com você. Tenho trabalho a fazer.}
{293}{}{Devo terminar meus deveres antes do meu mestre retornar.}
{294}{}{Falar é contra as regras.}
{295}{}{Por favor vá embora. Eu te imploro. Você só vai me dar problemas.}
{296}{}{Escapar? Não há nenhum lugar para escapar de TO. Os Resíduos estão cheios de monstros horríveis que comerão fugitivos vivos.}
{297}{}{Os escravos que ficam doentes geralmente são mortos.}
{298}{}{Eu era um dos escravos que chegaram a New Reno. Dois outros ficaram doentes durante a viagem, então os escravos dispararam contra eles.}
{299}{}{Sim? Como posso ajudá-lo?}
{300}{}{Eu ouço rumores de uma estrada de ferro subterrânea, mas não conheço ninguém que escapou.}
{301}{}{Julia escapou, mas eles a pegaram no Gólgota no dia seguinte. Eles a amarraram a uma roda e a deixaram morrer de fome.}
{302}{}{Escravos fugitivos são capturados e deixados a morrer no Gólgota.}
{303}{}{Não, não sei onde está a minha família agora. Ainda penso neles às vezes, mas não muitas vezes.}
{304}{}{O novo Reno é ... bem, não é tão ruim quanto o Den. Em algumas formas.}
{305}{}{:: Desvio, assustado. ::}
{306}{}{:: Ignora você, assustado. ::}
{307}{}{Uma vez que você aprende as necessidades de seu novo mestre, as pioras se tornam menos ... freqüentes.}
{308}{}{Eu fui capturado por escravos há muito tempo. Apenas lembro disso.}
{309}{}{Eu costumava ter dois filhos, mas eles foram enviados para o norte. Espero que tenham acabado em algum lugar melhor do que aqui.}
{310}{}{Me desculpe, mas não tenho tempo para conversar.}
{311}{}{Meu mestre recentemente ficou aborrecido comigo. Ele diz que vai me vender aos estábulos se eu o irritar de novo.}
{312}{}{Os escravos fugitivos morrem no Gólgota ou são enviados para os estábulos para serem testados.}
