# 0. QUICK LOOK
{100}{}{Você vê um homem negro bem parecido ... er, não, espere. Você vê T-Ray.}

# 0. LOOK
{150}{}{Você vê um homem preto pesadamente musculoso com óculos grossos, uma barba leve e uma atitude.}
{151}{}{Você vê T-Ray. Ele se parece muito bem com jeans.}
{152}{}{Você vê T-Ray. Ele ocasionalmente flexiona e sente seu bíceps, sussurrando "maldito" para si mesmo.}
{153}{}{Você dificilmente pode distinguir a T-Ray após toda essa atitude.}

# 1. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE and PLAYER HAD SEX WITH T-RAY) (WTG)
{200}{}{Ei, não foi minha culpa que o preservativo que estávamos usando tivesse um buraco nisso.}
{201}{}{Uau! Eu não estava me vangloria com todos sobre você e eu fazendo isso. Mesmo! Musta foi outra pessoa.}
{202}{}{DAMN, mulher. Depois de bater nessas peles, você sai e salva o mundo. Esse é o poder de T-Ray para você.}

# 2. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE and PLAYER KNOWS T-RAY) (WTG)
{210}{}{Eu disse a todos que você e eu estamos certos. Que quando eu dou a palavra, é como se estivesse dando as ordens.}
{211}{}{Você tem sorte de que eu estivesse por perto para salvar sua bunda, ou o Enclave woulda tinha você para PEQUENO ALMOÇO.}
{212}{}{Eu, herói. Você tem certeza de dizer a todos que o T-Ray é o seu homem, a ai?}

# 3. FLOAT DIALOGUES (ENCLAVE_DESTROYED = TRUE) (WTG)
{220}{}{Whoa, estamos na presença da realeza. Grande herói, chegando.}
{221}{}{Você sabe, você poderia ter parado antes de ir e fazer essa merda, então eu poderia ajudá-lo a bater o presidente.}
{222}{}{Eu também teria ido para o Enclave, "ainda não fiquei falando demais no telefone".}

# 4. FLOAT DIALOGUES (POWER ARMOR) (WTG)
{230}{}{Quantos cavalos de potência fazem aquela coisa que você tem?}
{231}{}{Como você vai ao banheiro com essa coisa?}
{232}{}{Alguma chance de me deixar ter uma armadura um pouco? Eu não vou desgastá-lo, eu só quero pedir emprestado.}

# 5. FLOAT (NORMAL)
{250}{}{Se não é o homem, aqui para me oprimir de novo.}
{251}{}{Sim, Impala é um bom carro, mas não é Omni.}
{252}{}{Sempre que faço amor com você, é uma lava quente ...}
{253}{}{Porra, este carro precisa de uma corda de latão em volta da placa.}
{254}{}{O motor ainda é bom.}
{255}{}{O interior cheira como se alguém tivesse uma merda lá.}
{256}{}{O interior cheira a gecko assholes.}
{257}{}{Por que diabos um carro precisa correr?}
{258}{}{O carro não precisa correr para levá-lo para onde você precisa ir, nawimean?}
{259}{}{Meu carro não é rápido, mas meu amor é.}
{260}{}{Não posso acreditar que meu tijolo é tão grande quanto ele.}
{261}{}{Estou pendurado como um brahmin de duas cabeças.}
{262}{}{O Highwayman tem um sistema analógico completo, 800 + Potência, de 0 a 60 em menos de um segundo.}
{263}{}{Rápido? O Highwayman passa de 0 a 60 em menos de um segundo.}
{264}{}{O Highwayman tem o poder: 800+, na verdade.}
{265}{}{O Highwayman tem um sistema analógico completo e nenhum computador. Nenhuma das coisas extravagantes.}
{266}{}{O Highwayman é um carro doce; Chryslus certamente sabia como construí-los.}
{267}{}{Eu compartilho uma chance.}
{268}{}{Vou dar a sua peça uma chance.}

# 6. INTRO (WTG)
{275}{}{Quem é você? O que você está fazendo aqui?}
{276}{}{Droga. Olhe o que apenas entrou ... parece que os exercícios do corpo superior estão finalmente pagando. O que posso fazer por você, coisa doce?}
{277}{}{Você novamente? O que você quer agora?}
{278}{}{Droga, mulher ... você de novo? O que você quer agora? Eu não quero ouvir nenhuma merda sobre como eu fiquei grávida ...}
{279}{}{}
{280}{}{ Ir aonde}
{281}{}{ ir}
{282}{}{Afastar-se}
{283}{}{Onde você conseguiu aquele Highwayman? Eu gosto da aparência disso.}
{284}{}{Esse carro que você tem na garagem pertence a mim.}
{285}{}{Você aquele que roubou meu carro, idiota?}
{286}{}{Sou tenente do bispo,}
{5286}{}{. Estou aqui para o carro.}
{287}{}{Sou um dos tenentes do bispo. Estou aqui para o carro dele.}
{288}{}{Venho recolher as baterias gratuitas do Sr. Bishop.}
{289}{}{Você pode atualizar o Highwayman?}
{290}{}{Posso comprar algumas pilhas de você?}
{291}{}{Nothing. I'm iring now.}

# 7. ME GO WHERE ME GO (6, 17)
{300}{}{Man, this AIN'T no bathroom, and you shore as hell ain't iring in here. Now git.}
{301}{}{Girl, this AIN'T no bathroom, and you shore as hell ain't iring in here. Now git.}
{302}{}{You wanna GO? Here? Bem… (Looks you up and down) …a man's irtta do who a man's irtta do. Let's get down to bitness.}
{303}{}{Uh-huh}
{304}{}{Nuh-uh}
{306}{}{Começar a trabalhar.}
{307}{}{Uh, não, obrigado. Eu mudei de ideia. Adeus.}

# 8. UH-HUH (7)
{320}{}{Aiight então ...}
{321}{}{Uh-uh-uh}

# 9. NUH-UH (7, 17, 31, 35)
{330}{}{Aw, so you just PLAYING with T-Ray? All right, then. Get, woman…I irt better bitches to do with my time.}
{331}{}{Time keepz em tique-taque, tique-taque, tique-taque ... inta the fuuuuture}
{333}{}{Se suponha que você possa pegar cachorros, você pode fazer o que quiser com eles. Adeus.}
{334}{}{O fato de fazer sexo com cães não me surpreende. Adeus.}

# 10. I LIKE THAT HIGHWAYMAN IN THE GARAGE (6)
{340}{}{O Highwayman lá fora? Droga DIREITA, você gosta da aparência dela. Essa é uma máquina doce, uma aquisição recente ... estamos apenas
 Prestes a abaixá-la, fazer alguns ajustes, depois vendê-la para o bispo do homem.}
{341}{}{"Ajustes?" Que tipo de ajustes?}
{342}{}{Vender a BISHOP? Olha, idiota ... Dea do bispo ... quero dizer, eu posso encontrar a oferta de Bishop.}
{343}{}{Vender a Bishop? Inferno, posso encontrar a oferta de Bishop e levantar isso.}
{344}{}{What a coincidence. Sou tenente do bispo,}
{346}{}{Na verdade, você não vai vender esse carro a ninguém. O carro é meu.}
{347}{}{Sounds like a irod deal. Catch you later.}

# 11. ADJUSTMENTS? WHAT KIND OF ADJUSTMENTS? (10)
{360}{}{Aperfeiçoe o motor, limpe o interior, coloque uma corda de latão em volta da placa - e chute uma parte daquela merda
 Fora do baú, faça algum espaço. Quando terminarmos, valerão algumas fichas sérias para o Sr. Bishop.}
{361}{}{Vender a Bishop? Eu posso encontrar a oferta de Bishop e depois levantar isso.}
{362}{}{Que coincidência. Sou um dos tenentes do bispo:}
{365}{}{Sounds irod. Catch you later then.}

# 12. I CAN MEET BISHOP'S OFFER (10, 11, 13)
{375}{}{You're irnna match BISHOP'S offer? That's a lot of scrilla, man. A LOT of chips. Plus, he's one of the top men in
 Reno, y'know? I get him this machine, there's…FRINGE benefits.}
{376}{}{You're irnna match BISHOP'S offer? That's a lot of scrilla, woman. A LOT of chips. Plus, he's one of the top men in
 Reno, y'know? I get him this machine, there's…FRINGE benefits.}
{377}{}{Estou ouvindo…}
{378}{}{1000 chips mudam de idéia?}
{379}{}{750 chips mudam de idéia?}
{380}{}{500 chips mudam de idéia?}
{381}{}{Na verdade, não tenho fichas suficientes para fazer uma oferta agora ...}
{382}{}{How about a night with me, T-Ray? You ain't never iring to have anything better.}
{383}{}{Minha oferta é a seguinte: eu vou deixá-lo de uma só vez, se você me der o carro de volta agora.}
{384}{}{Nevermind...I have to be iring.}

# 13. THAT'S NOT ENOUGH (12)
{395}{}{Cara, esse montante não poderia se dar ao luxo de trocar minhas roupas, muito menos mudar minha mente.}
{396}{}{Mulher, esse montante não podia se dar ao luxo de trocar minhas roupas, muito menos mudar minha mente.}
{397}{}{Você deve pensar que os carros são baratos.}
{398}{}{Vamos re-negociar então.}
{399}{}{Olha, não posso te fazer uma oferta agora, mas uma vez que recebo as fichas juntas ...}
{401}{}{Não, mas sua vida é. Vou deixá-lo de uma só vez se você me devolver MEU carro agora.}
{402}{}{Não tenho tempo para isso agora. Adeus.}

# 14. SLEEP OFFER REJECTED FOR BATTERIES (27, 53)
{420}{}{Naw, I already irt one dog I give a bone to, and I ain't looking to start a kennel. From the looks of you, you ain't
 irt nothing that would be worth my time.}
{421}{}{Sua perda. Deixe-me ver seu estoque então.}
{422}{}{Know what? Eu estouSICK of listening to you and your bullshit. I'm iring to carve you into so many pieces you could
 start your own butcher shop.}
{423}{}{Tudo bem então. Estou indo embora.}

# 15. SLEEP OFFER REJECTED FOR HIGHWAYMAN (12, 13)
{436}{}{Atinente negociação, então. Me dê o meu carro de volta, agora mesmo. Se não.}
{437}{}{Forget this. I'm iring to carve you into so many pieces you could start your own butcher shop.}

# 16. SLEEP OFFER CONSIDERED (12, 13)
{445}{}{(Seus olhos deslizam para cima e para baixo do seu corpo.) Eu não sei se você vale tudo isso, mulher. Este é um HIGHWAYMAN sobre o qual estamos falando ...}
{446}{}{Oh, eu valho tudo a pena. E mais.}

# 17. INTRO SEX DEAL, CONSUMMATED (16)
{455}{}{Curse-me por um tolo ... é um acordo feito, então. Eu tenho algum tempo de brincadeira, então você pode dirigir aquele Highwayman fora daqui.}
{456}{}{Vamos lá, então.}
{457}{}{Negociação de parafusos. Me dê o meu carro de volta, agora mesmo. Se não.}
{458}{}{I've changed my mind. I think Eu estoujust iring to kill you instead.}
{459}{}{Esqueça. Estou indo embora.}

# 18. END OF DEAL (12, 13)
{470}{}{Look, why are you wasting my time? If you ain't irt the chips, then you ain't irt no business here. I irt better
 things to do than be talking to your cheap ass.}
{471}{}{A única coisa que é barato aqui é a sua vida. Vou deixá-lo de uma só vez se você me devolver MEU carro agora.}
{472}{}{You know, that was your last chance. Now Eu estoujust iring to KILL you.}

# 19. IT'S MY CAR (6, 10, 11, 12, 13, 15, 16, 17, 18)
{485}{}{O seu carro?}
{486}{}{Cara, nem sabe o que você está falando.}
{487}{}{Mulher, você nem sabe o que você está falando.}
{488}{}{That Highwayman was scrap, left lying around, and guess what? Now it's ours. 'Course, you irt an ISSUE with that, we
 could settle it here and now…}
{489}{}{Yeah, I irt an issue with it. Let's ir, chop shop boy...}
{490}{}{O que você está fazendo com o carro?}
{491}{}{Não, isso é legal. Você pode ter o maldito Highwayman. Pedaço de merda de qualquer maneira. Usa muito "tricidade", cheira a gecko por dentro,
 O tronco é muito pequeno ... seja perfeito para você, no entanto. Até mais.}
{492}{}{No, I haven't irt an issue with it...yet. See you.}

# 20. SMELLS LIKE SHIT ANYWAY . . . (19)
{500}{}{Whoa, aguarde! * Piada de merda? Cheira a Gecko? *}
{501}{}{Cara, o que Jet Jet ja estava tomando?}
{502}{}{Mulher, o que tipo de jato estava tomando?}
{503}{}{This is a HIGHWAYMAN. Not only does it run, but after I fix it up, it's irnna purr like a woman beneath me.}
{504}{}{Estou com vontade de ouvi-lo. Coma chumbo, chop shop boy ...}
{505}{}{O que você está corrigindo no carro?}
{506}{}{Tanto faz. Estou fora daqui.}

# 21. DON'T WANT NO TROUBLE (19)
{520}{}{Sim, é isso que PENSIAM. É melhor correr agora antes que mamãe se preocupe com você.}
{521}{}{Não, na verdade, é a SUA Mãe que fica preocupada sem mim por favor.}
{522}{}{Let it ir and leave quietly.}

# 22. BOUGHT HIGHWAYMAN, STRAIGHT-UP (12)
{530}{}{All right, then. It's a done deal. (Scans the money quickly, pockets it.) The Highwayman's all yours. It ain't irt no
 battery juice, of course, and it ain't irt none of the special amen-ities I was irnna add…}
{531}{}{De que amenidades você está falando?}
{532}{}{Estou cansada por essa besteira. Coma chumbo, chop shop boy ...}
{533}{}{Oh, mas você já me deu muito. Estou fora daqui.}

# 23. SEX FOR HIGHWAYMAN (7)
{540}{}{(T-Ray wipes the sweat off his body.) Goddamn, woman. All right then, the Highwayman's all yours. It ain't irt none
 of the special amen-ities I was irnna add…}
{541}{}{* Huff-huff * Que amenidades você está ... * huff-huff * ... falando sobre?}
{542}{}{Estou cansado disso ... * huff- * huff * ... bullshit run-around. Coma ... * wheeze * ... chumbo, chop shop boy ...}
{543}{}{Eu ... * huff-huff * ... voltou meu carro, e eu ... * huff-huff * ... não quero que você toque mais. Estou fora daqui.}

# 24. WHAT FIX-UPS? (6, 19, 22, 33, 54)
{550}{}{Claro que sim. Posso melhorar o carregador de bateria, engomar o motor, limpar o interior um pouco, dar um brilho, colocar
 Uma corda de latão ao redor da matrícula - e chutar uma parte daquela merda do cofre, fazer mais espaço. 500 fichas.}
{551}{}{Você sabe, toque o carregador de bateria, enrole o motor, limpe o interior um pouco, dê um brilho, coloque um bronze
 Encaixe a placa de matrícula - e chute uma parte daquela merda do tronco, faça mais espaço. Algum desses interessa você?
 Apenas 500 fichas.}
{552}{}{Certo. Aqui estão 500 fichas.}
{553}{}{Como cerca de 300 fichas?}
{554}{}{I ain't irt that much on me right now. How about I bring it back when I have the cash?}
{555}{}{Que tal um amor mais doce?}
{556}{}{Que tal meu corpo? Isso lhe interessa?}
{558}{}{Estou doente dessa besteira. Coma chumbo, chop shop boy ...}
{559}{}{Eu não quero que você toque meu carro mais. Estou fora daqui.}

# 25. END OF ADDITIONS DEAL (24, 26, 30)
{575}{}{Feito. (Toma dinheiro) Me dê algum tempo, e estará em frente a cidade para você. Não se preocupe ... ninguém vai apostar
 Reivindique-o enquanto você estiver ausente. Um olhar: você já precisa de baterias, venha falar comigo e eu vou ligar você.}
{576}{}{Posso ver o que você tem no estoque agora?}
{577}{}{Muito bem, obrigado. Pegue você mais tarde, T-Ray.}

# 26. NO 300 (24)
{590}{}{(Shakes his head.) Naw, that ain't irnna cut it. 500 or nothing.}

# 27. CAN I COME BACK (24, 26, 30)
{615}{}{Course you can. I'll leave your car out in fronta town for you. But don't worry...no one'll stake a claim on it while
 you're irne. An' look: you ever need any batteries for it, come talk to me, and I'll hook you up.}
{616}{}{Na verdade, preciso de algumas baterias agora.}
{617}{}{Eu poderia usar algumas pilhas, mas você sabe o que? Eu não sinto como pagar com batatas fritas ... você estaria interessado em algo ... ELSE?}
{619}{}{Tudo bem então. Pegue você mais tarde.}

# 28. SEX FOR BATTERIES, NO BATTERIES (27)
{630}{}{(Shrugs) Sorry, we ain't irt no batteries now…come back in a week or two, maybe some will have turned up.
 'Course…we could just conduct bitness ANYWAY…}
{631}{}{Tudo certo.}
{632}{}{Desculpe, só quando é negócio. Mais tarde, T-Ray.}

# 29. SEX FOR BATTERIES, HAVE BATTERIES (27)
{640}{}{Maldita puta! Eu acabei de te dar amor doce há cinco minutos! Você está me matando?}
{641}{}{Agora, segure ...}
{642}{}{C'mon, I need a charge, and only YOUR sweet love is iring to do it.}
{643}{}{Deixa pra lá então. Seja assim.}

# 30. REJECTION, SUPER CAR (24, 26)
{650}{}{Naw, I already irt one dog I give a bone to, and I ain't looking to start a kennel. From the looks of you, you ain't
 irt nothing that would be worth my time. 500 chips is what sprucing up the Highwayman's irnna cost.}
{651}{}{Tudo bem então. Aqui estão 500 fichas.}
{653}{}{Know what? Eu estouSICK of listening to your bullshit. I'm iring to put you down.}

# 31. SWEET LOVE FOR BATTERIES (29, 53)
{660}{}{(Deixa você antes de se afastar.) Agora segure um minuto, mulher. Eu não disse que não tive nenhum amor doce por você.
 Vamos diminuir o pouco.}
{661}{}{(Looks you up and down.) A man's irtta do who a man's irtta do. Let's get down to bitness.}
{662}{}{Vá para "bitness".}
{663}{}{Não, eu mudei de idéia. Tchau.}

# 33. ENCLAVE_DESTROYED (WTG)
{670}{}{Ei! O grande herói vem ao redor do pescoço de T-Ray na floresta! Bem-vindo bem vindo…}
{671}{}{Ei, doce coisa. Você volta para relaxar com o Ray depois de ter feito chutar a bunda do mundo?}
{672}{}{Say… I irt something you might be interested in for yo car…IF you still have it.}
{673}{}{Wut izzit}
{675}{}{What have you irt for the car?}

# 34. SWEET LOVE…AGAIN? SUPER CAR (24, 26)
{690}{}{Droga, mulher! Eu acabei de te dar amor doce há cinco minutos! Você está me matando?}
{691}{}{You wanna ir AGAIN? Damn, woman! Don't your legs EVER close?}
{692}{}{Bem…}
{693}{}{C'mon, I need a-fixin', and only YOUR sweet love is iring to do it.}

# 35. SWEET LOVE FOR SUPER CAR (34)

# 37. I'M ONE OF BISHOP'S MEN - DON'T BELIEVE (6, 10, 11)
{710}{}{(Estuda você, franziu a testa) Sim, claro que você é. Conheço os tenentes do Bispo de ALLA, e você não é um deles.
 (Nods na porta.) Saia daqui antes de perder a paciência.}
{711}{}{I AM one of Bishop's lieutenants. Now are we irnna deal, or what?}
{712}{}{Estou saindo, vou embora ...}

# 38. I'M ONE OF BISHOP'S MEN - WE GONNA DEAL OR WHAT (37)
{720}{}{(Sneers) Yeah, we're irnna deal all right. Better hope you ain't irt no family who's irnna miss you…}
{721}{}{You better hope that you irt a family that'll be able to find all your pieces.}

# 39. I'M ONE OF BISHOP'S MEN - BELIEVE (6, 10, 11)
{730}{}{(Estudos você.) Você é um dos lew-inquilinos de Bishop ?! Naw ... se você fosse, você seria um pouco mais alto, um pouco
 Mais ... (parece céptico) ... mal-burro.}
{731}{}{(Estudos você.) Você é}
{5731}{}{?! Eu ouvi}
{6731}{}{ Foi um pouco mais alto, um pouco mais ... (parece céptico) ... mal-burro.}
{732}{}{Eu sou legítimo. Você me desafia?}
{733}{}{Eu estou}
{5733}{}{. Você me desafia?}
{734}{}{Não acredite em tudo o que você ouve. Vamos falar sobre o carro do Sr. Bishop.}
{735}{}{Forget this conversation. Eu estououtta here.}

# 40. I'M ONE OF BISHOP'S MEN (39)
{745}{}{(Eleva as mãos na rendição simulada) Naw, naw, eu estava apenas brincando com a bruxa.}
{746}{}{Vamos falar sobre o carro do Sr. Bishop.}
{747}{}{Next time you better watch yourself. Eu estououtta here.}

# 41. I'M ONE OF BISHOP'S MEN (39, 40)
{755}{}{Aiight, aiight ... aqui está o acordo: podemos fazer todas as atualizações, avaliá-la e levá-la ao Sr. Bishop pronto.
 Preço ... (Shrugs, sorrisos) ... pergunta é: como você pode colocar um preço em um Highwayman como este?}
{756}{}{Continue.}
{757}{}{Eu não tenho tempo para sua besteira. Qual é a linha de fundo?}
{758}{}{Você está certo. Você não pode. Vou levar o carro comigo, e o Sr. Bishop irá deixar você continuar sua operação aqui.}
{759}{}{I don't have time for this. Eu estououtta here.}

# 42. GO ON. (41)
{770}{}{As I see it, this Highwayman…most likely the last of its kind in working order…is worth at LEAST 3000 chips…but
 y'know what? (Winks) Eu estouwilling to part with this fine machine for 2700 chips considerin' the condition. A-course, we'd
 need ta talk about FRINGE benefits: club privileges, free admission to the ho-house…}
{771}{}{2700? Feito. Olha Você aqui.}
{772}{}{O Sr. Bishop está preparado para lhe oferecer 1500 fichas.}
{773}{}{2700? Não, não ... Sr. Bishop levará por 900 fichas.}
{774}{}{Eu tenho uma contra-oferta. Vou levar o carro sem cobrança, e o Sr. Bishop permitirá que você continue sua operação aqui.}
{775}{}{Eu direi ao Sr. Bishop e volto com sua resposta.}

# 43. OKAY, 2700 chipS. (42)
{780}{}{(T-Ray pisca, então sorri lenta e de largura quando você passa as fichas). Agora, eu gosto de um acordo que concluiu rápido e
 simples; Prazer fazendo bitness com você, prazer fazendo bitness ... agora sobre esses benefícios marginais ...?}
{781}{}{Você terá que discutir aqueles com o Sr. Bishop. O Sr. Bishop tem um último pedido: baterias gratuitas da sua loja.
 Eu serei o serviço de correio para esses pick-ups.}
{782}{}{The other benefits you will have to discuss with Mr. Bishop himself. Be sure to ir to talk to him armed and
 shouting loudly about what he owes you. He respects men like that.}
{783}{}{Você terá que falar com o Sr. Bishop sobre seus benefícios adicionais. Adeus.}

# 44. 1500 chipS (42)
{790}{}{Cara, esse montante não poderia se dar ao luxo de mudar minhas roupas!}
{791}{}{Mulher, esse montante não poderia se dar ao luxo de mudar minhas roupas!}
{792}{}{O que, Bishop, acha que os carros são BARATOS ?!}
{793}{}{Talvez você sinta que está sendo tratado ... injustamente?}
{794}{}{O Sr. Bishop fez uma oferta genérica de 1500 fichas. Você não gostará da próxima oferta.}
{795}{}{Então, talvez uma oferta de 900 fichas seja mais do seu agrado. O Sr. Bishop ficará satisfeito pelo fato de seu trabalho chegar tão barato.}
{797}{}{Since his generous offer has been refused, Eu estouinstructed to take the car for no charge.}
{798}{}{Eu me canso dessa conversa. Eu voltarei mais tarde.}

# 45. 900 chipS (42, 44)
{810}{}{Nine hun ... cara, você está brincando ?!}
{811}{}{Nine hun ... mulher, você está brincando ?!}
{812}{}{Corte a merda do touro! Este é um HIGHWAYMAN. Eles não os fazem em nenhum lugar, veja? Há OUTRAS famílias que serão
 Vai pagar por isso se aquele Bastão Bishop barato não ...}
{816}{}{Então você está lidando com outras famílias? O Sr. Bishop ficará interessado em ouvir isso.}
{817}{}{Eu estousorry? What did you just call Mr. Bishop?}
{818}{}{Eu me canso disso. Vamos falar novamente mais tarde.}

# 46. I'M TAKING THE CAR (41, 42, 44, 45)
{830}{}{(T-Ray freezes. For a second, you think he's iring to attack you, but then he relaxes.) Man, this is a raw deal. }
{831}{}{(T-Ray freezes. For a second, you think he's iring to attack you, but then he relaxes.) Woman, this is a raw deal. }
{832}{}{O que eu já fiz para o Bispo merecer isso? Hã?}
{834}{}{Eu assumiria o cargo com o Sr. Bishop. Ah ... Sr. Bishop tem um último pedido: ele gostaria de baterias gratuitas da sua loja.
 Eu serei o serviço de correio para esses pick-ups.}
{835}{}{Eu estousure it was something. He doesn't like you much. Pleasure doing business with you.}

# 47. PERHAPS YOU THINK YOU ARE BEING TREATED UNFAIRLY (44, 45, 46)
{845}{}{Naw, naw, nada assim ...! Eu e o Sr. Bishop, vemos os olhos sobre isso, sem problemas. Ele me tratou bem e você
 Diga-lhe isso, aiight? Mas ... uh ... e os benefícios que eu mencionei ...?}
{846}{}{Você terá que discutir aqueles com o Sr. Bishop. O Sr. Bishop tem um último pedido: ele gostaria de baterias gratuitas do seu
 fazer compras. Eu serei o serviço de correio para esses pick-ups.}
{847}{}{The other benefits you will have to discuss with Mr. Bishop. Be sure to ir to talk to him armed and shouting loudly
 about what he owes you. He respects men like that.}

# 48. FREE BATTERIES . . . (43, 46, 47)
{855}{}{(O sorriso de T-Ray desaparece.) Aiight ... claro, claro ... não é problema.}
{856}{}{Excelente. Me dê todas as baterias que você tem no estoque agora.}
{857}{}{(Sair.)}

# 49. LEAVE . . . NO FREE BATTERIES (43, 46, 47)
{865}{}{Eu vou, vou ... ei, você diz a seu chefe que ele também pode comprar baterias de mim. Eu continuo encontrando novos todos os dias por aqui.}
{866}{}{Mesmo? Deixe-me ver o que você tem em estoque.}

# 50. BISHOP BATTERIES, NONE (6, 33, 48, 54)
{875}{}{We ain't irt any batteries right now; most of the cars we've stripped ain't turned up shit. Give us a week or two, aiight?}
{876}{}{Tudo certo. I'll let it slide. This time. See ya.}

# 51. BISHOP BATTERIES, YES (6, 33, 51, 54)
{885}{}{(T-Ray's shoulders slump a little.) Aiight, aiight. Here you ir. It's all I irt.}
{886}{}{Tudo certo. I'll be back in two weeks for the next batch. Have them ready for Mr. Bishop.}

# 52. BUY BATTERIES, NONE (6, 33, 54)
{896}{}{OK. Vou tentar mais tarde.}

# 53. BISHOP BATTERIES, YES (6, 33, 54)
{905}{}{Sure, we irt some.}
{906}{}{Eu poderia verificar o seu estoque?}
{907}{}{Bem, eu realmente gostaria de um, mas eu não quero pagar por isso. Há algo ... ELSE eu poderia fazer para pagar por isso?}
{909}{}{Apenas checando. Estar vendo você.}

# 54. RAM-PLATES (33)
{915}{}{Grav-plates! Essas belezas vão permitir que você voe atravesse o terreno deserto, e eles têm um chip de poder de reciclagem, então eles
 Apenas sugam qualquer suco. Como você gosta disso? Você os quer?}
{916}{}{Eu como eu pego}
{918}{}{Sounds irod. I'll take it.}
{919}{}{Not right now. Venho recolher as baterias gratuitas do Sr. Bishop.}
{920}{}{Não agora. Você pode atualizar o Highwayman sem adicionar as placas de gravar?}
{921}{}{Não agora. Posso comprar algumas baterias de você?}
{922}{}{Não, não no momento. Talvez mais tarde. Até mais.}

# 55. RAM-PLATES (54)
{930}{}{(T-Ray gasta uma hora ou duas na loja. Quando ele emerge, os grav-plates foram instalados).}
{931}{}{Thanks, T-Ray. Appreciate it. I'll ir try them out.}

# 56. FLOAT (HERO)
{940}{}{Ajude-se, herói.}
{941}{}{O que é meu é seu. Diga a todos que eu também disse isso.}
{942}{}{Damn. You save the world, and you STILL irt to ir through everybody's shit.}

# 57. FLOAT (WARNING)
{950}{}{Afaste-se da minha merda.}
{951}{}{Next time you touch my shit, you're iring to get yo ass beat.}

{1000}{}{You irt the car back without using violence.}
{1001}{}{Você criou com sucesso o T-Ray.}
{1002}{}{Você recebeu um fornecimento gratuito de baterias de carros.}

# EXPLODING T-RAY
{1100}{}{Muito ... muito ... sexo ... vai ... soprar ...}

{2000}{}{You irt a battery for the Highwayman.}
{2010}{}{You irt the upgrade for the Highwayman.}
