# quick look
{100}{}{Você vê um boxeador.}
{101}{}{Você vê Mike "o Masticador".}

# examines
{150}{}{Seus braços parecem troncos de árvores.}
{151}{}{Cada braço parece que pode dobrar como um tanque de barril.}
{152}{}{Quando ele se move, é como observar um oceano de músculo.}
{153}{}{Ele está olhando sua orelha avidamente.}
{157}{}{Seu rosto parece uma placa de carne crua.}

# FLOAT DIALOGUE
{158}{}{Hurgghhh.}
{159}{}{Gunhrrhh}
{160}{}{Mike smash}
{161}{}{Eu realmente gosto de sorvete de baunilha}
{162}{}{Gnarrrr}
{163}{}{Nrrrhhhh}
{164}{}{Mike gosta de ouvidos}
{165}{}{Orelhas mmmmmmm}
{166}{}{Grrrrrr}
{167}{}{Gr. Gr? Grrrrrrr.}
{168}{}{Gr?}
{169}{}{Rrrgggg}
{170}{}{Eu come ouvidos}
{171}{}{Ears yum}
{172}{}{Gr ... grrrgr?}
{173}{}{Snrggg}
{174}{}{Eu odeio Robbin 'Givens}
{175}{}{Grrrrrgrrrrgrrr ... grrr ... grrr ... grr! Grr! Grrr?}
{176}{}{O que significa "porcentagem"?}

# CLICK DIALOGUE
# (PRIZEFIGHTER)
{200}{}{:: Mike cowers como você se aproxima ::}
{201}{}{:: Mike geme como você se aproxima ::}
{202}{}{:: Mike levanta as mãos na rendição conforme você se aproxima ::}
# (FEMALE, ANY BUT PRIZEFIGHTER)
{203}{}{Você é fofo}
{204}{}{Eu como seus ouvidos}
{205}{}{Basta falar. Hora de dormir}
{206}{}{Robin? Que você?}
