# 0. QUICK LOOK (WTG)
{100}{}{Você vê Coffin Willie.}

# 0. LOOK (WTG)
{150}{}{Você vê um ghoul velho, fedorento e grosso. E menino, ele CHEIRA.}

# 1. DIG UP (WTG)
{200}{}{Uau. Esta grave CHEIROS.}
{201}{}{Oh, bem ... melhor continuar cavando.}
{202}{}{O que?}
{203}{}{Sobre o tempo de friggin! Você poderia cavar qualquer SLOWER, idjit?}
{204}{}{Fora meu caminho, smoothie.}
# lenny in party
{205}{}{D'Dad?}
{206}{}{Não agora, Lenny, eu não estou com vontade de falar.}

# 2. CLICK/FLOAT (WTG)
{300}{}{Jest pop inta Reno fer a lil 'bebendo n' whoring, n 'damned smoothies me atrapalham inna goddamn grave ...}
{301}{}{Bom, eu não tenho nariz, ou eu me engasgou no meu próprio fedor.}
{302}{}{Os espíritos espirituais não recebem nenhum alvo maldito.}
{303}{}{Acabei de parar na cidade para tomar uma bebida, e esses idiotas de Reno me enterram vivo.}
{304}{}{Nada mais chato do que ficar em um caixão por meses.}
{305}{}{Mãos fora, smoothie. Eu tenho lugares para ir.}
{306}{}{Obtenha suas luvas de smoothie fora de mim, smoothie.}

# HEADSTONE
{500}{}{A lápide lê: "Aqui está o filho da puta mais idiota para pisar em New Reno".}

{550}{}{Há um odor horrível que flui do túmulo.}

{600}{}{Ei!}
{601}{}{Ouvi dizer que alguns estão se movendo por aí!}
{602}{}{Não pise onna grave! Ele embala a sujeira!}
{603}{}{Rápido, GET A SHOVEL!}
{604}{}{Alguém já me descobriria? Eu preciso de uma bebida!}
{605}{}{Que um vermeiro eu sinto? Oh ... nunca mais.}
