# 0.QUICK LOOK
{100}{}{Você vê uma das crianças Wright.}

# 0.LOOK [ENCLAVE_DESTROYED = TRUE] (WTG)
{150}{}{Você vê uma pequena criança de cabelos negros com uma panela na cabeça.Ele está apontando o dedo para alguns agentes imaginários do Enclave e fazendo ruídos BLAM.}
{151}{}{Você vê uma das crianças Wright com uma panela na cabeça.}
{152}{}{Você vê uma das crianças Wright com uma panela na cabeça.He is pointing his finger at some imaginary Enclave agents and making BLAM noises.}

# 1.LOOK (NORMAL) (WTG)
{200}{}{Você vê uma pequena criança de cabelos negros com uma panela na cabeça.}
{201}{}{Você vê uma das crianças Wright com uma panela na cabeça.He is making *bzzzzing* noises like a hornet.}

# 2.FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{210}{}{Olhe para mim, sou o descendente do Vault Dweller!Elogie o Vault!}
{211}{}{Eu quero continuar a busca pelo Vault 13!}
{212}{}{Blam blam!Die, Enclave jerk-faces!}
{213}{}{Olhe, aqui vem o Enclave!}
{214}{}{Prisioneiro de guerra!Prisioneiro de guerra!Pegue isso, você Enclave jerks!}
{215}{}{Você é SEMPRE o Habitante do Vault!}
{216}{}{Tente matar todos com um vírus, hein? Tome isso, Sr.Presidente!}
{217}{}{Coma isso, Sr.Prezident!}
{218}{}{Eu quero ser o próximo jogo do Vault Dweller!}
{219}{}{Nuh-uh!Você me perdeu, amante do presidente!}
{220}{}{Uh-uh!Entendi!Entendi!}
{221}{}{Acabei de explodir o Enclave!Boooooom!}
{222}{}{Rápido!Todo mundo ao petroleiro!}
{223}{}{Coma isso, você Enclave Butt-faces!}
{224}{}{Eu te matei, Enclave-lover!}
{225}{}{Enclave Muthuhfugguhs vai provar meu metal.}
{226}{}{Tinha minha armadura de poder endurecida!Essa bala saltou imediatamente!}
{227}{}{Morra, Enclave-face!}
{228}{}{Aighhhhhhhh ...fui atingido ...}

# 3.FLOAT [WRIGHT CHILDREN PLAYING, NORMAL] (WTG)
{240}{}{Olhe para mim, eu sou o inseto de metal!Bzzzzzz}
{241}{}{Blam blam!}
{242}{}{Olhe, aqui vem o inseto de metal!}
{243}{}{Pegue isso!}
{244}{}{Você sempre é o inseto de metal!}
{245}{}{Bang bang!}
{246}{}{Eu quero ser o próximo jogo de insetos de metal!}
{247}{}{Nuh-uh!Voce estava com saudades de mim!}
{248}{}{Uh-uh!Entendi!Entendi!}
{249}{}{Bzzzzzzz}
{250}{}{Eu matei você morto!}
{251}{}{Zooommmm}
{252}{}{Muthuhfugguh vai provar meu metal.}
{253}{}{A minha força estava no campo!}
{254}{}{Morra, Salvatore-face!}
{255}{}{Aighhhhhhhh ...fui atingido ...}

# 4.CLICK [ENCLAVE_DESTROYED = TRUE] (WTG)
{270}{}{Sinto falta de Dogmeat de Fallout 1.}
{271}{}{Pense que haverá um Fallout 3? Eu quero ser o herói daquele!}
{272}{}{Fallout 2 foi trazido para você pela letra Z.}
{273}{}{O Enclave pode beijar minha bunda de sete anos de idade.O que se empurra.}
{274}{}{O Enclave era um verdadeiro idiota, não é? Sheesh.}
{275}{}{Você ficou assustado quando conheceu o presidente? Ele tinha grandes presas e garras?}
{276}{}{Eu queria poder ajudá-lo a destruir o Enclave.Eu ...não teria medo.Uh-uh.}
{277}{}{Ei!}
{5277}{}{!Conte-nos a história do Enclave!Pleeeease?}
{278}{}{}
{5278}{}{!Yaaaaay!}
{279}{}{Agradecemos a nós,}
{5279}{}{!}
{280}{}{Eu quero salvar o mundo como você quando cresço.}
{281}{}{Posso ser um herói como você quando eu crescer?}
{282}{}{Eu quero ser}
{5282}{}{ quando eu crescer.}

# 5.CLICK [POWER ARMOR] (WTG)
{300}{}{Aighhhh!É uma das pessoas de metal!Corre!}
{301}{}{É uma das pessoas do metal!Eles nos encontraram!Corre!}
{302}{}{Nós lamentamos!Nós lamentamos!Não insiram insetos metálicos sobre nós!Por favor!}

# 6.CLICK [SLAVER OR BAD REP] (WTG)
{310}{}{É melhor você correr antes que meu pai o veja.}
{311}{}{É melhor você correr antes que meus irmãos o vejam.}
{312}{}{É uma pessoa ruim.É melhor deixar o que quero dizer sobre você.}

# 7.INTRO (WTG)
{320}{}{(A criança pára * bzzzzzing * ao redor e levanta o pote para olhar para você.)}
{321}{}{lata}
{5321}{}{ jogar também?}
{322}{}{Sorree.Eu pensei que você era um pote Byeeee}
{323}{}{Por que você tem uma panela na sua cabeça?}
{324}{}{O que você está jogando?}
{325}{}{Onde estão seus pais?}
{326}{}{(Deixe-o jogar.)}

# 8.CAN [X] PLAY TOO? (7)
{330}{}{Bem ...ok.(Olha para cima e para baixo.) Mas eu sou o inseto de metal neste jogo!}
{331}{}{Okee Dokee Little Bee People}
{332}{}{ Tudo bem com isso.}
{333}{}{Que incesto?}
{334}{}{Não!}
{5334}{}{ quero ser incesto!}
{335}{}{Ooooh ...e aqui?}

# 9.OKEE DOKEE/X CAN DO THAT/[X] OKAY WITH THAT (8)
{340}{}{(O homem pequeno deixa o pote cair sobre sua cabeça, e retoma * bzzzzing * ao redor.)}
{341}{}{Corra com ele por um tempo fazendo barulhos * bzzzzing *.}
{342}{}{Shamble off}
{343}{}{(Sair.)}

# 10.WHAT INCEST? (8)
{350}{}{INSECT, stoo-pid!Nós conseguimos um quando estávamos no deserto!Era tão grande ...(respira profundamente.) ...tão grande como uma CASA!
 Não tinha pessoas de metal nele.}
{351}{}{Nuh-uh}
{352}{}{Não me chame de estúpido}
{353}{}{Não grite.}
{5353}{}{ não é como gritar.}
{354}{}{Você mente para}
{5354}{}{.Você FUN FUN de}
{6354}{}{.}
{7354}{}{ não parece.}
{355}{}{ matou muitas pessoas barulhentas como você ... talvez você seja o próximo?}
{356}{}{Afastar-se.}

# 11.NUH-UH 1 (10)
{360}{}{UH-HUH.We saw it.}
{362}{}{Uh-uh-uh-uh}
{363}{}{Huh-huh-huh-huh}
{364}{}{Vagueie e faça barulhos "uhhh" para outra pessoa.}

# 12.NUH-UH 2 (11)
{370}{}{Uh-huh!I'll show you!A bunch of us are going over there when it gets REALLY dark.}
{371}{}{Uh-huh!I'll show you!A bunch of us are going over there tonight.}
{372}{}{Wanna come? (The little person squints at you.) But you gotta be reeeally quiet.Reeeeally quiet.}
{373}{}{Okee-dokee (Siga-o.)}
{374}{}{Okee-dokee, eu vou saber ... oooooh, aquela areia lá?}

# 13.DON'T SHOUT.X NO LIKE SHOUT.(10, 13, 21)
{380}{}{I don't like you.You're a big stupid-head!(Sticks out his tongue.) Get outta here, stupid-head!}
{381}{}{NÃO ME CHAME STOOPID!VOCÊ STOOPID!VOCÊ STOOPID!}
{382}{}{Não gritar!Não gritar em}
{5382}{}{!}
{6382}{}{ ESMAGAR!}
{383}{}{Mude as lágrimas e fuja}
{384}{}{All right…this time.Go easy on the Jet, kid.}

# 14.UH-UH-UH-UH/HUH-HUH-HUH-HUH (11)
{390}{}{(Squints para você.) Você soa como minha mãe e meu pai quando eles vão para a cama.}
{391}{}{Onde você vê o incesto? Eu também quero ver}

# 15.YOU LIE TO [X].YOU MAKE FUN OF [X].[X] NOT LIKE.(10)
{400}{}{I'm not lying, stupid!A bunch of us are going over there when it gets REALLY dark.}
{401}{}{I'm not lying, stupid!A bunch of us are going over there tonight.}
{403}{}{NÃO me chame de estúpido, STOOPID}
{404}{}{Uh-huh (Siga-o.)}
{405}{}{Okee-dokee, eu quero com ... oooooh, aquela areia lá?}

# 16.WHERE HE SEE INCEST? I WANNA SEE IT TOO (14)
{410}{}{A bunch of us are going over there when it gets REALLY dark.}
{411}{}{A bunch of us are going over there tonight.}
{412}{}{Wanna come? (Squints at you.) But you gotta be reeeally quiet.Reeeeally quiet.}

# 17.WHY DO YOU HAVE A POT ON YOUR HEAD? (7, 32)
{420}{}{It's not a pot, STUPID!It's my helmet!}
{421}{}{Whoa, desculpe, temeroso guerreiro armado.}
{422}{}{Me chame de estúpido Ocasionalmente, pequena merda, e veremos o quão bem esse 'capacete' protege você de uma ferida de cabeça aberta.}
{423}{}{(Deixe-o brincar com o seu "capacete").}

# 18.WHOA, SORRY THERE, FEARSOME HELMED WARRIOR.(17)
{430}{}{(Olha para você com desconfiança.) Whaddya quer?}
{432}{}{I just wanted to know what kind of game you're playing.It looks like fun!}
{433}{}{Uh ... onde estão seus pais?}
{434}{}{Nada.}

# 19.CALL ME STUPID AGAIN .../ NO SHOUT!NO SHOUT AT X!X ESMAGAR!(10, 13, 17)
{440}{}{(O homem pequeno fica branco, dá um passo para trás, depois se vira e corre, gritando sua cabeça.)}
{441}{}{(O garoto fica branco, dá um passo para trás, depois vira e corre, gritando sua cabeça.)}
{442}{}{Hee hee...run, little mann!RUN!}
{443}{}{Little Punk ...}

# 20.WHAT ARE YOU PLAYING? (7, 18, 32)
{450}{}{Metal insects n' soldiers.}
{451}{}{(Looks at your equipment, spots one of your pistols.) lataI play with yer gun?}
{452}{}{Não, não ... é muito perigoso jogar com, jovem.}
{453}{}{No.You'll shoot your eye out.}
{454}{}{Why, sure you can, you little pothead.Here you go.(Give him an unloaded pistol.)}
{455}{}{Why, sure you can, you little pothead.Here you go.(Give him a loaded pistol.)}
{456}{}{"Insetos metálicos?"}
{457}{}{Oh, okay.I was just curious.}
{458}{}{Nooooo ... acho melhor eu ir.}

# 21.NO, TOO DANGEROUS.NO GUN FOR YOU (20, 21)
{470}{}{(Glares at you.) C'mon, I know how to use guns like that!I'm in Family Wright!Let me see it!Pleeease?}
{471}{}{Look: In the wrong hands, a gun is a deadly weapon.Well, I mean, it's ALWAYS a deadly weapon, but in the wrong hands…it's, uh…deadly…hold on, let me start over.}
{472}{}{Look, if your family trusted you with a gun they would have given you one.Forget it.}
{473}{}{Eu não me importo se você estiver na Family Badass, você não está recebendo essa arma.}
{474}{}{Well, all right.(Give him an unloaded pistol.)}
{475}{}{Well, all right.(Give him a loaded pistol.)}
{476}{}{Forget it.Go play with your friends.}

# 22.METAL INSECTS? TELL ME ABOUT THE METAL INSECTS.(28)
{485}{}{Yeah, metal insects!We SAW one when we were out in th' desert!It was as big… (Takes a deep breath.) …as big as
 a HOUSE!N'it had metal PEOPLE in it.}
{486}{}{Really!Wow!Where did you see it?}
{487}{}{Você está mentindo!}
{488}{}{I don't believe you.You're lying.}
{489}{}{You better go easy on the Jet, kid.That stuff'll kill you.Later.}
{490}{}{Really? That's amazing.I may have to go out there sometime and see for myself.Bye.}

# 23.REALLY? WOW!WHERE DID YOU SEE IT? DON'T TRUST (22)
{500}{}{In th' desert.(Squints at you suspiciously.) It's probably not there anymore, though.}
{501}{}{Tem certeza de que não gostaria de me mostrar de qualquer maneira?}
{502}{}{latayou show me where you saw it anyway?}
{503}{}{Oh, okay.See you, then.}

# 24.REALLY? WOW!WHERE DID YOU SEE IT? TRUST (22)
{510}{}{In th' desert.(Glances around, starts whispering.) A bunch of us are going out there when it gets REALLY dark.}
{511}{}{In th' desert.(Glances around, starts whispering.) A bunch of us are going out there tonight.}
{513}{}{I'm never quiet when I come.But just this once…}
{514}{}{I'll be quiet.Lead on, MacDuff.}
{515}{}{Uh, I don't think you'll be seeing that 'metal insect' anymore.It was actually a helicopter.}
{516}{}{Not tonight, thanks.Early day tomorrow.}

# 25.IT WAS A HELICOPTER (24, 27)
{530}{}{Hunh? (Frowns e ajusta o pote em sua cabeça.) O que é um hello-helicóptero?}
{531}{}{It's a…flying machine.It can hold people and stuff inside.}
{532}{}{A helicopter is...I guess the closest approximation you'd be familiar with is 'automobile.' A helicopter is like
 an automobile that's able to rise off the ground and hover through the use of vertically rotating blades.The helicopter's
 engine spins the blades so fast it keeps it aloft.Isn't that incredible?}
{533}{}{Nevermind.Just don't go wandering around outside of town again.It could get you killed.}

# 26.YOU'RE LYING!DON'T TRUST (22)
{540}{}{I'm NOT lying!We SAW it in the desert!(He glares at you sullenly.)}
{541}{}{Hmmm.Maybe you ARE telling the truth.latayou show me where you saw it?}
{542}{}{Okay, I believe you.Will you show me where you saw it?}
{543}{}{Okay, okay.Nevermind.Go back to playing your game.}

# 27.YOU'RE LYING!TRUST (22)
{550}{}{I'm NOT lying!We SAW it in the desert!I can PROVE it!(Glares at you.) A bunch of us are going over when it gets a little darker.}
{551}{}{I'm NOT lying!We SAW it in the desert!I can PROVE it!(Glares at you.) A bunch of us are going over there tonight.}
{552}{}{Come along, and I'll show it to you.(Sneers.) If yer not SCARED.}
{556}{}{No thanks.Go back to playing your game.}

# 28.SURE CAN./GIVE PISTOL (20, 21)
{560}{}{(You take your crappiest gun from your pack and give it to the kid.He smiles and holds it up, admiring it.) MY gun!Cool!}
{561}{}{Eu sei onde eu posso pegar munição também!}
{562}{}{Uh, you can't keep it.It's just a loan...}
{563}{}{Yep, all yours.Now tell me about these metal insects…}
{564}{}{Lock and load, kid.Say...why don't you go show your gun to Daddy? Be sure to wave it around a lot and pull that little
 switch beneath the gun there.}
{565}{}{Sure is.Enjoy.Catch you later.}

# 29.UH, YOU CAN'T KEEP IT.(28)
{570}{}{Tribal giver!It's mine!You gave it to me!It's my gun!}
{571}{}{Devolva, sua pequena merda!}
{572}{}{No, it's mine.I had to hurt a lot of people for that gun.lataI pleeeease have it back?}
{573}{}{Oh, hell.This post holocaust world can't get any worse.Go on and play with it.}

# 30.GIVE IT BACK, YOU LITTLE SHIT/NO, IT'S MINE.CAN I PLEEEEASE HAVE IT BACK? (29)
{580}{}{Nuh-uh!(He runs off with your gun.)}
{581}{}{Volte aqui, sua pequena merda!}

# 31.WHY DON'T YOU GO POINT IT AT DADDY? (28)
{590}{}{Okay!(He runs off.)}
{591}{}{Bem, esse pequeno ato de maldade pode demorar um pouco para dar frutos ... melhor deixar a área e voltar.}
{592}{}{(Calmemente deixe a vizinhança, assobiando inocentemente.)}

# 32.WHERE ARE YOUR PARENTS? (7, 18)
{600}{}{(Shrugs.) Papai está na casa, mamãe na igreja.}
{603}{}{All right then.Just curious.Thanks.}

# 33.LEAVE HIM AND LET HIM PLAY./WANDER OFF.(27)
{610}{}{(O garoto deixa o pote cair sobre sua cabeça e retoma * bzzzzing * em torno de.)}

# 34.SHRUG.(24, 25, 27)
{620}{}{(The kid shrugs.He lets the pot fall down over his head, and resumes *bzzzzing* around.)}

# 35."VIGOROUS" NO (23, 26)
{630}{}{(He shakes his head.He lets the pot fall down over his head, and resumes *bzzzzing* around.)}
{631}{}{Uh, está bem.}
{632}{}{Seu pequeno punk ... veja se eu salvar você quando estou salvando o mundo ...}

# 36.GO OUT INTO DESERT (12, 15, 16, 24, 27)
{640}{}{Você espera até ficar um pouco mais escura ...}
{641}{}{Você espera até ficar escuro ...}
{642}{}{... então você segue as crianças no deserto.}

# 37.SCREAMING
{700}{}{SAIA DE PERTO DE MIM!}
{701}{}{Ahhh...}
{702}{}{Ajude-me, ajude-me ...}
{703}{}{MEAN PERSON!GET AWAY!}
{704}{}{SAIA DE PERTO DE MIM!}

# 38.THANKS
{710}{}{Ei, obrigado pela arma legal, senhor.}
{711}{}{Eu lhe disse que adoro minha nova arma que você me deu?}
{711}{}{Ei, obrigado pela arma legal, senhora.}

# 39.LOST GUN
{720}{}{Um de vocês empurrou minha arma, esse cara me deu?}
{721}{}{Para onde foi minha arma?}
{722}{}{Eu sei que você me deu uma arma, o que eu fiz com isso?}
{723}{}{Um de vocês empurrou minha arma que esta senhora me deu?}
