# QUICK LOOK
{100}{}{Você vê um dos filhos de Wright.}
{101}{}{Você vê uma das filhas de Wright.}

# 0. LOOK [MALE]
{150}{}{Você vê um jovem com uma expressão de raiva. Ele está tentando parecer duro.}
{151}{}{Você vê um dos filhos de Wright. He looks like he's packing a few weapons and looks a little too young to know what to be doing with them.}
{152}{}{Você vê um dos filhos de Wright. He glares at you unsuccessfully.}
{153}{}{Você vê um dos filhos de Wright. He looks like he'd rather be off doing something…anything…else.}
# 1. LOOK [FEMALE]
{160}{}{Você vê uma jovem com uma expressão severa. Ela está tentando parecer difícil.}
{161}{}{Você vê uma das filhas de Wright. She's packing a few weapons and looks a little too young to know what to be doing with them.}
{162}{}{Você vê uma das filhas de Wright. She ignores you, but drops her hand to her holster meaningfully.}
{163}{}{Você vê uma das filhas de Wright. She looks meaner than a rattler.}
{164}{}{Você vê uma das filhas de Wright. She looks meaner than a rattler. For some reason, that excites you.}

# 2. CLICK/FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE
{200}{}{::Felicidades::}
{201}{}{:: Claps ::}
{202}{}{:: Whistles ::}
{203}{}{(Sings.) "Nós não precisamos de outro herói, não precisamos saber o caminho de casa ..."}
{204}{}{Ei!}
{1204}{}{! Maneira de chutar o traseiro do Enclave ... er, butt!}
{205}{}{Maneira de esmagar o Enclave,}
{1205}{}{. Isso tomou certezas graves.}
{206}{}{Você deve ter sido mais difícil do que Tommy the Balls para quebrar o Enclave como você fez.}
{207}{}{Aqueles amigos do Enclave soam como bastardos reais.}
{208}{}{Eles iriam despejar algum VIRUS novo no ar? Bastardos. Espero que você tenha disparado alguns para mim.}
{209}{}{Eu pensei que o presidente era um mito, um boogeyman costumava assustar crianças.}
{210}{}{Você parece ter atravessado o inferno e de volta. Relaxe por um tempo. Você merece isso.}
{211}{}{Você vai repetir o jogo como um personagem diferente? Eu recomendo um tipo de Outdoorsman.}
{212}{}{F.E.V.? O que é isso?}
{213}{}{O novo Reno foi desenhado por Chris Avellone e roteado por Tom French. Tom toca em uma banda. Chris joga consigo mesmo.}
{214}{}{Espero ter um personagem importante no Fallout 3, como Tandi ou Ian. Bein 'e um bandido é uma merda.}
{215}{}{Ouvi dizer que você entrou no Enclave para o sul. Você é muito corajoso.}

# 3. FLOAT DIALOGUE: POWER ARMOR
{225}{}{Como você vai ao banheiro com essa coisa?}

# 4. FLOAT/CLICK DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=WRIGHT [ARMED]
{230}{}{Mantenha essa arma fora da vista dos jovens, ok?}
{231}{}{Não fique com essa arma em torno dos jovens, ok?}

# 5. FLOAT/CLICK DIALOGUE: PLAYER = FEMALE/MALE, MADE MAN, FA=WRIGHT [SNEAK]
{235}{}{Você quase assustou o diabo fora de mim, sneakin 'como assim!}
{236}{}{Por que você está pensando assim?}
{237}{}{Uau! Pare de tentar fazer uma sombra ... Eu quase atirei em você, Fer Chrissakes! Sheesh.}

# 6. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM]
{240}{}{Howdy,}
{1240}{}{. O que você tem feito?}
{241}{}{Damn hot, innit,}
{1241}{}{?}
{242}{}{Howdy,}
{1242}{}{. Como estão as coisas?}

# 7. FLOAT/CLICK [MALE, MADE MAN, FA = NOT WRIGHT, ARMED]
{245}{}{É um dos}
{1245}{}{ família! E ele está armado! Ligue para os outros!}

# 8. FLOAT/CLICK [FEMALE, MADE MAN, FA = NOT WRIGHT, ARMED]
{250}{}{É um dos}
{1250}{}{ família! E ela está armada! Ligue para os outros!}

# 9. FLOAT/CLICK [MALE/FEMALE, MADE MAN, FA = NOT WRIGHT, SNEAK]
{255}{}{É um dos}
{1255}{}{ Família sneakin ao redor! Ligue para os outros!}

# 10. FLOAT/CLICK [MALE/FEMALE, MADE MAN, FA = NOT WRIGHT]
{260}{}{Saia daqui, antes de preenchê-lo cheio de buracos!}
{261}{}{Saia daqui! Sua família não é bem-vinda aqui!}

# 11. FLOAT/CLICK [SLAVER, ARMED]
{265}{}{Solte a arma, escravidão, ou vamos atirar!}

# 12. FLOAT/CLICK [SLAVER, SNEAK]
{270}{}{Por que diabos você se esquiva? Você está procurando ser baleado, escravidão?}

# 13. FLOAT/CLICK [FEMALE/MALE, PRIZEFIGHTER/PORN STAR/NO REP, ARMED]
{275}{}{Solte a arma! Agora!}
{276}{}{Coloque essa arma em baixo, ou vamos a atirar!}
{277}{}{Coloque a arma fora, ou vamos atirar!}

# 14. FLOAT/CLICK [FEMALE/MALE, PRIZEFIGHTER/PORN STAR/NO REP, SNEAK]
{280}{}{Por que você está se arruinando? Isso vai te fazer disparar.}
{281}{}{O que diabos ... er, heck, você sneakin around? Você está procurando ser baleado?}

# 15. FLOAT AND CLICK (ANY) TO [COMPANION: ROBOBRAIN]
{285}{}{É algum tipo de slot machine que está a seguir?}
{286}{}{Isso é uma máquina robo-slot?}
{287}{}{Isso é um cérebro dentro dessa coisa de robô? Yechhh.}
{288}{}{Que algum tipo de vitrine do rovin 'brain you you got with you?}
{289}{}{Que um robô? Nunca fui visto um desses antes.}

# 16. FLOAT (ANY) TO [COMPANION: MARCUS]
{295}{}{Diga-me que não é um mutante.}
{296}{}{Que um mutante?}
{297}{}{Holy Brahmin Turds. Mutantes em New Reno. Deve significar problemas ...}
{298}{}{Esse mutante é um grande mutha.}
{299}{}{Aquele mutante, o melhor, se olha por aqui e me escuta?}

# 17. FLOAT/CLICK [FEMALE/MALE, NORM]
{305}{}{O que você quer?}
{306}{}{Ajudá-lo com alguma coisa?}
{307}{}{Muito calor…}
{308}{}{Novo Reno fica mais feio todos os dias ...}
{309}{}{O que você está fazendo aqui?}
{310}{}{Se você está procurando álcool, vá para a estação de trem na parte norte da cidade ... nós não vendemos aqui.}
{311}{}{Veja seu passo aqui, amigo. Este é o território da família Wright.}

# 19. CLICK DIALOGUE: POWER ARMOR
{320}{}{Você deve jogar com os jovens com essa armadura. Eles adorariam isso.}
{321}{}{Não pise nenhum dos mais pequenos com essa armadura, y'hear?}
{322}{}{Você não está quente lá?}
{323}{}{Uma geladeira a pé. Agora eu já vi tudo.}
{324}{}{Você está procurando uma lavagem de carros?}
{325}{}{Parece que você pertence a um jogo de computador mech da batalha. Este é Fallout 2. Talvez você tenha aberto o
 Pasta errada no seu disco rígido?}
{326}{}{Como você vai ao banheiro com essa coisa?}

# 20. CLICK [FEMALE/MALE, MADE MAN, FA = WRIGHT OR PRIZEFIGHTER]
{335}{}{Como estás,}
{1335}{}{? Corra para qualquer problema com alguém na cidade?}
{336}{}{É bom ter você na família, uh, mesmo que você não seja família, sabe? Uh ... nunca mais.}
{337}{}{Ouvi Tommy the Balls voltou para a cidade. Assustador.}
{338}{}{Nós Wrights somos a família mais forte porque somos família.}
{339}{}{Vergonha com o meu irmão lil. Ele era um bom garoto, mas Jet está por toda essa cidade, é difícil evitá-lo ...}
{340}{}{Papai disse que nos estrangularia se algum dia ouvisse sobre nós tomando Jet.}
{341}{}{Papai ainda está chateado, então fique atento quando você fala com ele, e você?}
{342}{}{Chris vai ter um bom papel se ele fique espancando na bodega.}
{343}{}{Muito calor…}
{344}{}{Não é visto mamãe por um tempo. Se você a vê, não mencione nada sobre os alambiques, 'kay?}
{345}{}{Keith soltou o piano na semana passada e voltou a juntar-se. Garoto inteligente.}
{346}{}{Nós vamos cair para radscoroions novamente em alguns dias.}
{347}{}{Se você está procurando álcool, vá para a estação de trem na parte norte da cidade ... nós não vendemos aqui.}
{348}{}{Cuidado com as crianças por aqui, eles estão sempre sob os pés.}
{349}{}{Você pode me ensinar a lutar também?}
{350}{}{Você é aquele lutador,}
{1350}{}{Aincha? É bom no ringue, o melhor que já vi nessas partes.}
{351}{}{Você luta bem. Você deve conversar com o pai ... er, o chefe, sobre um emprego.}
{352}{}{Poderíamos usar um braço forte na cidade, se interessado.}
{353}{}{Quando você vai lutar de novo?}
{354}{}{Eu apostaria com você, mas a mãe fica tão chateada quando jogamos.}
{355}{}{Eles o construíram forte, sem dúvida.}
{356}{}{Cuidado com o Masticator, está bem? Ele é um meio. Mais cedo morda sua orelha do que olhar para você.}

# 22. CLICK [PORN STAR]
{360}{}{A mãe diz que é uma ferramenta do diabo. Ou que você tenha uma ferramenta do diabo. Algo parecido.}
{361}{}{Melhor não ficar em frente ... Mamãe pode vê-lo e começar a pregar.}
{362}{}{Então, como é no cinema? Mamãe não me deixa ver seus filmes.}
{363}{}{Não conte aos pequenos o que você faz.}
{364}{}{Mamãe vai jogar um jeito se ela o vir. Ela é tão histriónica.}
{365}{}{Se você está procurando álcool, vá para a estação de trem na parte norte da cidade ... nós não vendemos aqui.}
{366}{}{Nós Wrights somos a família mais forte porque somos família.}
{367}{}{Vergonha com o meu irmão lil. Ele era um bom garoto, mas Jet está por toda essa cidade, é difícil evitá-lo ...}
{368}{}{Papai disse que nos estrangularia se ele alguma vez nos lembre de nós, tentando Jet.}
{369}{}{Papai ainda está chateado, então tenha cuidado quando você fala com ele, você ouve?}
{370}{}{Chris vai ter um bom papel se ele fique espancando na bodega.}
{371}{}{Muito calor…}
{372}{}{Keith soltou o piano na semana passada e voltou a juntar-se. Garoto inteligente.}
{373}{}{Nós vamos cair para radscoroions novamente em alguns dias.}
{374}{}{Você realmente conversa com Deus quando está com sexo no palco?}
{375}{}{A mãe diz que é uma ferramenta do diabo.}
{376}{}{Mamãe diz que você é uma prostituta. Um estrondo de bronze. Não tenho ideia do que ela está fazendo.}

# 24. [FEMALE/MALE/, NO REP/SLAVER, REACTION NEUTRAL +]
{385}{}{Você está aqui para ver papai sobre negócios? Bem, boa sorte, não acho que ele esteja contratando mãos agora.}
{386}{}{Se você está procurando álcool, vá para a estação de trem na parte norte da cidade ... nós não vendemos aqui.}
{387}{}{Veja seu passo aqui, amigo. Este é o território da família Wright.}

# 25. CLICK [SLAVER, BAD REACTION]
{390}{}{Melhor tirar ... não aceitamos gentilmente os escravos.}
{391}{}{Você nem sequer pensa em seqüestrar alguém aqui. Você causa algum problema, nós o destruiremos.}
{392}{}{Apenas mantenha sua distância, escravidão. Se você tem negócios com Pa, faça isso, então obtenha.}
{393}{}{Você melhor não trouxe nenhum chems, ou então o pai matará você. Então eu vou matar você.}
{394}{}{Eu estou te observando, escravidão, então você observa o que você faz, ouviu?}
{395}{}{Você toca qualquer uma dessas crianças, escravas, e eu vou te atirar tanto que voce vai sair das botas.}
{396}{}{Toque qualquer uma dessas crianças, escravas, e eu vou matar você.}
{397}{}{Se você está procurando por álcool, escravidão, vá para a estação de trem na parte norte da cidade ... nós não vendemos aqui.}
{398}{}{Você prejudica qualquer Wright, escravagista, e nossa Família não descansará até que a sua pele esteja apodrecendo no Golgotha.}
{399}{}{Você está aqui para ver papai sobre negócios? Não creio que o pai faça negócios com os escravos. É melhor você git.}

# 26. [FEMALE/MALE, NO REP, REACTION < NEUTRAL]
{410}{}{Melhor tirar ... sem ofensa, mas papai não gosta muito das tribos.}
{411}{}{Você nem pensa em causar algum problema. Nós Wrights superamos em número por ... uh, muito.}
{412}{}{Apenas mantenha sua distância. Se você tiver negócios, faça isso, então obtenha.}
{413}{}{Você melhor não trouxe nenhum chems, ou então o pai matará você. Então eu vou matar você.}
{414}{}{Estou te observando, então você observa o que faz, ouviu?}
{415}{}{De onde você é? Não é visto seu tipo por aqui há algum tempo.}
{416}{}{Se você está procurando álcool, vá para a estação de trem na parte norte da cidade ... nós não vendemos aqui.}
{417}{}{Você prejudica qualquer Wright, e a Família não descansará até que a sua pele esteja apodrecendo no Golgotha.}
{418}{}{Você está aqui para ver o pai sobre negócios? Boa sorte, não acho que ele esteja contratando mãos agora.}

# 27. CLICK/FLOAT: LENNY
{425}{}{Esse ghoul não deveria estar por aqui. É melhor mandá-lo de volta ao Gecko.}
{426}{}{É melhor não trazer esse ghoul em torno das crianças. Eles podem obter envenenamento por radiação.}
{427}{}{Eu sugiro que você e seu amigo ghoul vão embora antes que haja problemas.}
