# QUICK LOOK
{100}{}{Você vê uma das crianças Wright.}

# LOOK (IF MALE) (WTG)
{150}{}{Você vê um garotinho de cabelos negros.}
{151}{}{Você vê uma garotinha de cabelos negros. Seu cabelo é curto, tanto que quase a confundiu com um garoto.}

{155}{}{Ele enfia a língua em você.}
{156}{}{Ele está olhando para você com tristeza.}
{157}{}{Ela tira a língua para você.}
{158}{}{Seu cabelo preto é cortado para que ela possa usar o modelo de personagem infantil masculino convenientemente.}
{159}{}{Ela está olhando para você com escuridão.}

# 2. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{175}{}{Fallout 2 foi trazido para você pela letra Z.}
{176}{}{Ei!}
{177}{}{}
{178}{}{Agradecemos a nós,}
{179}{}{Eu quero salvar o mundo como você quando cresço.}
{180}{}{Posso ser um herói como você quando eu crescer?}
{181}{}{Eu quero ser}

# 3. FLOAT [POWER ARMOR] (WTG)
{190}{}{Você é um robô?}
{191}{}{Como você vai fazer xixi naquela coisa?}
{192}{}{Posso andar de volta em seus ombros? Pleeease?}
{193}{}{Você virá brincar conosco? Pleeease?}

# 4. FLOAT AND CLICK [SLAVER OR BAD REP] (WTG)
{200}{}{É melhor você correr antes que meu pai o veja.}
{201}{}{É melhor você correr antes que meus irmãos o vejam.}
{202}{}{É uma pessoa ruim. É melhor deixar o que quero dizer sobre você.}

# 5. FLOAT AND CLICK [SNEAKING] (WTG)
{210}{}{Eu te vejo! Eu te vejo!}
{211}{}{Você está escondendo e vai procurar? Posso jogar também?}

# 6. FLOAT COMMENTS [ROBOBRAIN + MARCUS] (WTG)
{215}{}{Olhe para o robô! Olhe para o robô!}
{216}{}{Isso é um cérebro novo dentro desse robô?}
{217}{}{Oooooooh. Olhe para o robô!}
{218}{}{Olhe para o mutante! Olhe para o mutante!}
{219}{}{Mutante, fagulante, mutante, fecundo}
{220}{}{Isso é um mutante reeeal? Ele é fugitivo.}
{221}{}{Oooooooh. Olhe para o mutante!}
{222}{}{Esse mutante é GRANDE. Mais grande que o papai.}

# 7. FLOAT COMMENTS [LENNY + DOG] (WTG)
{230}{}{Canibal! Olhe, é um ghoul!}
{231}{}{Ewwwwwww! Canibal! Canibal!}
{232}{}{Ghoul-eee ghoul-eee ghoul-eee!}
{233}{}{Olhe para o cachorrinho de metal!}
{234}{}{Doggie! Aqui, cachorrinho!}
{235}{}{Eu quero uma cachorrinha também!}


# 10. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{290}{}{Eu quero salvar o mundo como você quando cresço.}
{291}{}{Posso ser um herói como você quando eu crescer?}
{292}{}{Eu quero seryou quando eu crescer.}
{293}{}{Por que você quer ser eu? Eu DUMB}
{294}{}{Eu, uma vez, usava a cabeça da menina como um chapéu.}
{295}{}{Afastar-se}
{296}{}{Heh heh. Por que obrigado, pequeno. Mas tire uma dica de}
{297}{}{Siga seus sonhos. Você pode alcançar seus objetivos. Sou prova viva.}
{298}{}{Certamente você pode. Diga, lamento ouvir o seu irmão, Richie. Você sabe o que aconteceu com ele?}
{299}{}{Uma vez, passei por três estados vestindo a cabeça dessa menina como um chapéu.}
{300}{}{(Deixe ele voltar a jogar.)}
{301}{}{(Deixe-a voltar a jogar.)}

# 11. WHY YOU WANNA BE ME? ME DUMB. (10)
{310}{}{Uh-uh! Yer SMART! Yer a HERO and yer BRAVE and Eu quero serYOU quando eu crescer. Thanks fer savin' us, }
{311}{}{Thankzz pouco perscríbem. Você faz}

# 12. FOLLOW YOUR DREAMS. (10)
{315}{}{OK,}
{316}{}{Você cuida agora, você ouve, um pequeno? Eu tenho mais coisas de herói para fazer.}

# 13. I'VE GOT SOME THINGS TO DO. (12)
{320}{}{(O garoto para você.) Um ...}
{321}{}{Uh ... não. Eu prometo.}
{322}{}{Uh ... não é o que você sabe.}
{323}{}{Não se preocupe, pequeno. Eu vou voltar e visitá-lo como um personagem diferente.}
{324}{}{Não se preocupe, pequeno. Você não sentirá nada.}

# 14. UH, HARD DRIVE (13)
{330}{}{Vamos sonhar?}
{331}{}{Uh ... claro. Claro que você vai.}
{332}{}{Me bate. Eu não parece sonhar, então você provavelmente também não. A vida é uma puta, né?}

# 15. POWER ARMOR 1 (WTG)
{341}{}{Watz um barco a remos?}
{344}{}{Heh heh. Você não é fofo? Não, não sou um robô, pequeno.}
{345}{}{Não, não, sou uma pessoa comum sob essa armadura. Por sinal, lamento ouvir o seu irmão, Richie.
 Você sabe o que aconteceu com ele?}

# 16. WATZ A ROBOT?/YER DUMB, PEE-FACE/MOOTANT? (15, 25, 27, 29, 41)
{355}{}{YER DUMB.}
{356}{}{ENTÃO É VOCÊ}
{357}{}{O mesmo para você, diga mais}
{358}{}{Yer dumb-errrr}
{359}{}{Aquele que o cheira tratou}
{360}{}{Toma um t'know one!}
{361}{}{Fugir de chorar}

# 17. YER DUMBERR (16)
{370}{}{Você é o mais tolo. Yer mais tonto!}

# 18. POOR RESPONSE (16, 17)
{395}{}{Nuh-uh, DUMBHEAD! (O garoto foge, sua risada toca cruelmente em seus ouvidos.)}
{396}{}{Eu não quero falar com você NADA ... * snfff * ... eu ... * snfff * ... tem um PARTIDO ...
 com * snfff * BOLO e ICE CREAM ... e você não pode ir [Deixe.]}

# 19. YER DUMB-ESSTT-ERR (17)
{405}{}{(O filho pisca, abre a boca e depois a fecha. Uma lágrima brota e se transforma em um soluço cheio.)}
{406}{}{Hee hee ME win}

# 20. I'M NOT A ROBOT (15, 28)
{410}{}{Oh. (Pensa por um momento, depois escreve sobre você.) Por que o ARENCHA é um robô?}
{411}{}{Uh ... porque ... bem, robôs e pessoas têm diferentes ... uh, partes.}
{412}{}{Eu tenho que ir.}

# 21. ROBOTS AND PEOPLE HAVE DIFFERENT PARTS (20)
{425}{}{Oh sim? (Parece suspeito.) Como o quê?}
{426}{}{Uh ... bem ... diga, criança, sua mãe e seu pai não explicaram isso?}
{427}{}{Uh ... bem! Olha as horas! Eu devo ir.}

# 22. DIDN'T MOMMY AND DADDY EXPLAIN THIS TO YOU? (21)
{435}{}{Explicar o quê?}
{436}{}{Uh ... bem ... robôs ... tem óleo lá dentro. Humans ... bem, humanos ... sangram.}

# 23. HUMANS BLEED (22)
{445}{}{Mamãe e minhas grandes irmãs sangraram todos os meses ou mais. Então eles ficam realmente malvados. Eu queria que fossem robôs.}
{446}{}{Uh ... sim. Ótimo garoto. Olha, eu tenho que ir - não diga a você que eu estava falando com você.}

# 24. POWER ARMOR 2 (WTG)
{456}{}{Eu apenas mijo, mas tenho que me acostumar com isso}
{459}{}{Heh heh. Na verdade, eu apenas urino na armadura e recicla tudo. Isso não é interessante?
 Você sabe o que significa "reciclagem", um pequeno?}
{460}{}{Não é confortavelmente, com certeza. Diga, lamento ouvir o seu irmão, Richie.
 Você sabe o que aconteceu com ele?}

# 25. I PEE IN ARMOR (24)
{475}{}{Isso é nojento.}
{476}{}{Sim! Reciclagem significa que você beija xixi!}
{477}{}{YER bruto, pee-pee FACE}
{479}{}{Uh, heh ... heh. Na verdade, significa ...}

# 26. NO, ACTUALLY, IT MEANS . . . (25, 26)
{485}{}{Você bebe xixi-xixi! Você bebe xixi-xixi!}
{486}{}{Uh, heh ... heh ... mantenha sua voz baixa, pequena ... reciclagem não significa que eu bebo p ... bem, não EXATAMENTE ... olhe ...}
{487}{}{Deixe a pequena merda voltar a jogar.}
{488}{}{(Sair.)}

# 27. CLICK [ROBOBRAIN] (WTG)
{495}{}{Isso é um robô REAL?}
{499}{}{O Robobrain? Por que sim, sim.}
{500}{}{PENSA que é. Não me faça começar.}
{501}{}{Sim, mas não o incomode. Eu acho que quer destruir a raça humana.}
{502}{}{Sim. Diga, lamento ouvir o seu irmão, Richie. Você sabe o que aconteceu com ele?}

# 28. CLICK [ROBOBRAIN] (27)
{515}{}{Você também é um robô?}

# 29. CLICK [MARCUS] (WTG)
{525}{}{Isso é um mutante REAL?}
{526}{}{Mootant?}
{529}{}{Por que sim, sim. O nome dele é Marcus. Não se preocupe, ele não morda.}
{530}{}{Por que, sim, é um mutante. Gosh, eu certamente espero que ele não tenha fome de crianças pequenas.}
{531}{}{Porque sim. Um mutante muito HUNGRY. E também está certo sobre o tempo de lanche. Quão conveniente.}
{532}{}{Sim ele é. Diga, lamento ouvir o seu irmão, Richie. Você sabe o que aconteceu com ele?}

# 30. INTRO (WTG)
{540}{}{O garoto pára e olha para você.}
{541}{}{Helloooo}
{544}{}{Olá, homem pequeno.}
{545}{}{Olá, garotinha.}
{546}{}{Lamentava saber sobre seu irmão, Richie. Você sabe o que aconteceu com ele?}

# 31. I DROVE THROUGH 3 STATES . . . (10, 15, 24, 27, 29 30, 41)
{555}{}{Você está doente?}
{556}{}{Por que você pergunta?}

# 32. WHY DO YOU ASK? (31)
{560}{}{Você está doente.}
{561}{}{Estou doente.}

# 33. I AM SICK. (32)
{565}{}{Você toma remédios?}
{566}{}{Não há remédio para o que tenho.}

# 34. THERE IS NO MEDICINE FOR WHAT I HAVE. (33)
{570}{}{Quer cantar?}
{571}{}{Cantar?}

# 35. SING? (34)
{575}{}{Você sabe "Ele tem todo o mundo nas mãos?"}
{576}{}{Sim eu quero.}

# 36. YES, I DO. (35)
{580}{}{:: Canta :: 'Ele tem todo o mundo nas mãos dele. Ele tem todo o mundo em suas mãos. Vamos.}
{581}{}{:: Sing :: Ele tem todo o mundo em suas mãos. Ele tem todo o mundo em suas mãos.}

# 37. SING TOGETHER (36)
{585}{}{:: Cantando juntos :: Ele tem todo o mundo em suas mãos. :: Cantando ventos baixos :: Ele tem todo o mundo em suas mãos.}
{586}{}{Obrigado por cantar comigo. Posso voltar depois ... se eu precisar de um chapéu.}

# 38. HELLO, LITTLE MAN/WOMAN. (14, 37)
{590}{}{(O filho pisca em você.)}
{591}{}{Tudo bem então. Falo com você mais tarde.}

# 39. TALK TO YOU LATER/LET HIM GO BACK TO PLAYING/THANKS FOR SINGING WITH ME (38)
{595}{}{(A criança corre.)}

# 40. HELLO (MALE) (30, 40, 42)
{648}{}{Oh.}
{650}{}{Mesmo? O quê mais?}

# 41. CLICK [LENNY] (WTG)
{665}{}{Isso é um ghoul REAL?}
{666}{}{Gool?}
{669}{}{Por que sim, sim. O nome dele é Lenny. Não se preocupe, ele não morda.}
{670}{}{Por que, sim, é um ghoul. Gosh, eu certamente espero que ele não tenha fome de crianças pequenas.}
{671}{}{Porque sim. Um ghoul muito HUNGRY. E também está certo sobre o tempo de lanche. Quão conveniente.}

# 42. HIS NAME IS MARCUS. (29, 40, 41)
{685}{}{Olá, Mar-cus mutante. Yer horrível grande. Hee-hee ... e sua animação animada é engraçada.}
{686}{}{Olá, Len-ee ghoul. Phew ... você está realmente sorridente.}
{687}{}{Com certeza, não é? Então ... o que há, garoto?}
{688}{}{Com certeza, não é? Então ... o que há de criança?}
{689}{}{Bem, tenho que ir. Até logo.}

# 43. MARCUS/LENNY IS HUNGRY (29, 40, 41)
{695}{}{(O garoto fica pálido, então foge, gritando.)}
{696}{}{Heh heh heh heh. "Izzat um REAL mutante?" Ensine a ela a não fazer perguntas.}
{697}{}{Mutante "faminto"! Sheesh. Todos sabem que os mutantes não comem zumbido, por que você está me olhando assim, Marcus?}
{698}{}{Heh heh heh heh. "Izzat um verdadeiro ghoul?" Ensine a ela a não fazer perguntas.}
{699}{}{Ghoul "com fome"! Sheesh. Todo mundo sabe que os ghouls não comem hum, por que você está me olhando assim, Lenny?}

# 44. OD (10, 15, 24, 27, 29, 30, 40, 41)
{710}{}{Uh-uh. Papai está realmente louco com isso por isso, ele não sabe quem matou Richie. Ele diz se ele alguma vez nos pega
 fazendo Jet, ele vai nos dar um "whippin '".}
{711}{}{Você sabe que OMS poderia ter dado Richie the Jet que o matou?}
{712}{}{Você sabe onde Richie conseguiu aquele Jet que o matou?}
{713}{}{Deixe a criança voltar a jogar.}

# 45. DO YOU KNOW WHO? (44, 46)
{720}{}{Uh-uh.}

# 46. DO YOU KNOW WHERE? (44, 45)
{730}{}{Uh-uh. Ele estava pendurado muito no lado oeste da cidade, em torno de Row Comercial, e papai nos disse que não vamos lá.}

# sleeping
{800}{}{* Shhh * Eu deveria estar dormindo.}
{801}{}{Preciso dormir um pouco. Eu tenho um grande jogo de guerreiro de insetos de metal amanhã.}
{802}{}{Se o papai descobre que não estou dormindo, ele será realmente, realmente louco.}

# 8/40. FLOAT [WRIGHT CHILDREN: BOYS] (WTG)
{900}{}{Meu ding-a-ling, meu ding-a-ling.}
{901}{}{:: Guarda arma falsa :: Alcance para os céus, varmit!}
{902}{}{Uma boa jogada merece outra, entre as pernas que pendura sua mãe.}
{903}{}{Eu quero sera pimp quando eu crescer.}
{904}{}{Eu vou governar New Reno quando eu crescer, assim como o papai.}
{905}{}{Eu quero uma cachorrinha. Papai diz que vai me dar uma puta quando eu for mais velho.}
{906}{}{Gostaria que o pai fosse tão legal quanto Tommy the Balls.}
{907}{}{Eu tenho um pénis.}
# self_is_male ^
{908}{}{:: Shriek ::}
{909}{}{:: Sticks out tongue ::}
{910}{}{Papai chama a mamãe de uma fábrica de bebês.}
{911}{}{Papai disse que nos chicotearia se ele nos pegasse pegando Jet.}
{912}{}{Papai diz que temos que ter cuidado quando sairmos.}
{913}{}{Papai nos chicoteará se nos esgueirar novamente.}
{914}{}{Papai ficou muito louco desde que meu irmão Richie morreu.}
{915}{}{O papai está fazendo uma nova coisa.}
{916}{}{O padre Tully é engraçado quando ele não consegue andar direto.}
{917}{}{Ele tem todo o mundo em suas mãos ... ele tem todo o mundo em suas mãos ...}
{918}{}{Eu fiz um poo poo.}
{919}{}{Sinto falta do meu irmão, Richie. Ele morreu porque ele tomou muito Jet.}
{920}{}{Nunca mais vejo Christopher.}
{921}{}{Vi Mikey beijando Mareee Mor-Dino.}
{922}{}{Eu vi mamãe e papai dançando um com o outro.}
{923}{}{Gostaria que Christopher jogasse comigo.}
{924}{}{Kyle bebe seu próprio xixi!}
{925}{}{Kyle tem os esguichos.}
{926}{}{Land rover, land rover, envia Kyle sobre.}
{927}{}{Olhe para mim! Olhe para mim!}
{928}{}{Mikey e Mareee sentados em uma árvore, K-I-S-S-I-N-G.}
{929}{}{Milicent é um grande significado.}
{930}{}{Leite, leite, limonada. Ao virar da esquina, o fudge é feito.}
{931}{}{Mamãe e papai conversavam com Deus novamente ontem à noite na cama.}
{932}{}{Mamãe estava chorando no outro dia. Eu acho que é porque o que aconteceu com meu irmão Richie.}
{933}{}{Mamãe ficou muito triste desde que meu irmão Richie morreu.}
{934}{}{Mamãe está de volta pela igreja novamente.}
{935}{}{Nossa família é a melhor.}
{936}{}{Phfttttt}
{937}{}{Poopy-head! Poopy-head!}
{938}{}{Tio Nick diz que não é necessário discutir. Tio Nick precisa sair mais.}
{939}{}{Quer jogar tribos e escravas?}
{940}{}{Temos dezessete irmãos e irmãs.}
{941}{}{Wheeeeeeee}
{942}{}{Sim!}
{943}{}{Você tem cooties!}
{944}{}{Você parece um radscorpion!}
# self_is_female v
{945}{}{Eu vou pedir a papai se eu puder ser uma prostituta quando eu crescer. Ele diz que ele realmente precisa de um.}
{946}{}{Eu quero sera whore quando eu crescer. Daddy says we need more of them.}
{947}{}{Eu tenho uma vagina.}

# line endings
{1176}{}{! Conte-nos a história do Enclave! Pleeeease?}
{1177}{}{! Yaaaaay!}
{1178}{}{!}
{1181}{}{ quando eu crescer.}
{1296}{}{: Você pode ser QUALQUER COISA que você deseja quando crescer.}
{1310}{}{. NUNCA fergit você.}
{1311}{}{ sentir-se melhor. Me alegro de que você tenha salvado você}
{1315}{}{. Eu não fergit, eu prometo, se eu vivo, seja um caçador.}
{1320}{}{? Você vai nos excluir do seu disco rígido agora que você terminou o jogo?}
