{100}{}{Bem-vindo ao New Reno, a maior cidade pequena do mundo. Fogo da Lixeira
 e os sinais de néon banham a cidade em um brilho infernal.}
{101}{}{Antes que você seja uma planície aborrecida com túmulos. Pólos ensangüentados
 Terra com os restos de cadáveres amarrados a eles.}
{102}{}{Isso parece uma antiga estação elétrica de carregamento pré-guerra. Um cemitério de
 carros despojados rodeiam os edifícios.}
{103}{}{Você chegou aos estábulos. Uma nova cerca chainlink envolve as duas fazendas
 entradas de seção.}

{150}{}{[ANTERIOR]}
{151}{}{[MAIS]}

# family name
{201}{}{Salvatore}
{202}{}{Bispo}
{203}{}{Mordino}
{204}{}{Wright}

{221}{}{Salvatore's}
{222}{}{o Tubarão Club}
{223}{}{o Desperado}
{224}{}{}


# made man name
{300}{}{}
{301}{}{Sussurro}
{302}{}{Aranha}
{303}{}{Medo}
{304}{}{Professor}
{305}{}{Motor}
{306}{}{Touro}
{307}{}{Capitão}
{308}{}{Shush}
{309}{}{Lefty}
{310}{}{Righty}
{311}{}{Sobrancelhas}
{312}{}{Tornado}
{313}{}{Moulty}
{314}{}{Monkey Boy}
{315}{}{Grumoso}
{316}{}{Mitts}
{317}{}{Gooch}
{318}{}{Cleaver De Carne}
{319}{}{Brocco}
{320}{}{Duas vezes}
{321}{}{Romeu}
{322}{}{Vinnie}
{323}{}{Torre}
{324}{}{Silenciador}
{325}{}{Martelo}
{326}{}{Juntas}
{327}{}{Dobrador}
{328}{}{Grocer}
{329}{}{Snake-eyes}
{330}{}{Lobo}
{331}{}{Hatchetman}
{332}{}{risonho}
{333}{}{Gorduras}
{334}{}{Pérola}
{335}{}{Reno Jimmy}
{336}{}{Jade}
{337}{}{Scarface}
{338}{}{Diamante}
{339}{}{Ás}
{340}{}{One-Eyed Jack}
{341}{}{Nikki}
{342}{}{Iceman}
{343}{}{Sly}
{344}{}{Liso}
{345}{}{Charlie}
{346}{}{Ópio}
{347}{}{Punhal}
{348}{}{Olhos de anjo}
{349}{}{Fixador}
{350}{}{Tubarão}
{351}{}{Hound}
{352}{}{Reverendo}
{353}{}{Magnum}
{354}{}{Iceberg}
{355}{}{Gina}
{356}{}{Vicki}
{357}{}{correr atrás}
{358}{}{Guilhotina}
{359}{}{geada}
{360}{}{Valentino}
{361}{}{Fabricante de caixão}
{362}{}{Little Joe}
{363}{}{Rainha de gelo}
{364}{}{Interruptor}
{365}{}{Bucks}
{366}{}{Salgadinhos}
{367}{}{Por sorte}
{368}{}{Santo}
{369}{}{Números}
{370}{}{louva a Deus}
{371}{}{Escorpião}
{372}{}{Homem gordo}
{373}{}{Sam}
{374}{}{Blue Lou}
{375}{}{Tommy the Gun}
{376}{}{Crazy Jane}
{377}{}{Viúva}
{378}{}{Lixeiro}
{379}{}{Nine Inch Nick}
{380}{}{Rainmaker}
{381}{}{Rei}
{382}{}{Assassino}
{383}{}{Santana}
{384}{}{Joey}
{385}{}{César}
{386}{}{Mickey}
{387}{}{Drifter}
{388}{}{Assassino}
{389}{}{açougueiro}
{390}{}{Vermelho}
{391}{}{Rubi}
{392}{}{X}
{393}{}{}

# prizefighter name

{400}{}{}
{401}{}{Jabby}
{402}{}{Spinning Jenny}
{403}{}{Pistão}
{404}{}{Furacão}
{405}{}{Big Muthuh}
{406}{}{Escolhido}
{407}{}{Raging Touro}
{408}{}{LaMotta}
{409}{}{Trenó}
{410}{}{Glass Joe}
{411}{}{New Reno Nancy}
{412}{}{Bald Touro}
{413}{}{Princesa}
{414}{}{Duque}
{415}{}{Machoman}
{416}{}{Dama de Ferro}
{417}{}{Estripador}
{418}{}{Valquíria}
{419}{}{Gancho}
{420}{}{Sidewinder}
{421}{}{Bad Grrrl}
{422}{}{Rockjaw}
{423}{}{Parede de pedra}
{424}{}{Motosserra}
{425}{}{Helen Wheels}
{426}{}{Tommy Gunn}
{427}{}{Black Viúva}
{428}{}{Esmagar}
{429}{}{Delilah}
{430}{}{Relâmpago}
{431}{}{Jocco}
{432}{}{Irmã Aço}
{433}{}{Super Trenó}
{434}{}{Apollo}
{435}{}{Sucata de ferro}
{436}{}{Tigresa}
{437}{}{Tyson}
{438}{}{Lady J}
{439}{}{Drago}
{440}{}{Clubber Lang}
{441}{}{Duquesa}
{442}{}{Tourodozer}
{443}{}{Graça}
{444}{}{Ironhand Luke}
{445}{}{Fé}
{446}{}{Doutor Fist}
{447}{}{Freira voadora}
{448}{}{Balboa}
{449}{}{Floyd Ray Willis}
{450}{}{Calamity Jane}
{451}{}{Cobra}
{452}{}{Assassinato sangrento}
{453}{}{Carrasco}
{454}{}{Trem de carga}
{455}{}{Super Vixen}
{456}{}{Novo Reno Jim}
{457}{}{Triturador}
{458}{}{Rico}
{459}{}{Martelohand}
{460}{}{Viúvamaker}
{461}{}{Baliff}
{462}{}{Butch Coolidge}
{463}{}{Gato do bairro}
{464}{}{Bad Mojo}
{465}{}{Tanque}
{466}{}{Bruiser}
{467}{}{Mynx}
{468}{}{Escorpiãon}
{469}{}{Punchy}
{470}{}{guepardo}
{471}{}{Veredito}
{472}{}{Juiz júri}
{473}{}{Piledriver}
{474}{}{Athena}
{475}{}{Cachorro Louco}
{476}{}{}

# special stupid names
{496}{}{Big Stu}
{497}{}{Miami}
{498}{}{X}
{499}{}{Seu nome}

# porn star name
# male
{500}{}{}
{501}{}{Rodd Rokks}
{502}{}{Randy Mercury}
{503}{}{Freddy Barkwood}
{504}{}{Dick Mountenjoy}
{505}{}{Ronny Rection}
{506}{}{Phil Chambers}
{507}{}{Rod Sweat}
{508}{}{Jack Shooter}
{509}{}{Kurt Loader}
{510}{}{Rick Dripps}
{511}{}{Dick Seamen}
{512}{}{"The Polish Martelo"}
{513}{}{Origos de Doug}
{514}{}{Galo da caminhada}
{515}{}{Vinnie LaJoya}
{516}{}{Sir Lance-a-lot}
{517}{}{Dick Smothers}
{518}{}{Jeremy Bolt}
{519}{}{Sr. Pink}
{520}{}{Ricky Rachtman}
{521}{}{Cuthbert}
{522}{}{Dave Handy}
{523}{}{Harry Canyon}
{524}{}{Richie Cunning Linguist}
{525}{}{Bret Bulge}
{526}{}{El Douche}
{527}{}{Johnson Long}
{528}{}{Parafusos Ebineezer}
{529}{}{Buck Fitch}
{530}{}{Arnold Swollenmember}
{531}{}{}
{532}{}{}
{533}{}{}
{534}{}{}
{535}{}{}
{536}{}{}
{537}{}{}
{538}{}{}
{539}{}{}
{540}{}{}
{541}{}{}
{542}{}{}
{543}{}{}
{544}{}{}
{545}{}{}
{546}{}{}
{547}{}{}
{548}{}{}
{549}{}{}
# female
{550}{}{}
{551}{}{Vixxxen}
{552}{}{Sementes Mable}
{553}{}{Amber Waves}
{554}{}{Lucy Loose}
{555}{}{Amy Ample}
{556}{}{Molly Mounds}
{557}{}{Melinhos de mel}
{558}{}{Patty Pitt}
{559}{}{Bolas de Ophelia}
{560}{}{Thelma Schoonmaker}
{561}{}{Alotta Fagina}
{562}{}{Carrie C}
{563}{}{Georgia O'Queef}
{564}{}{Jill Jacks}
{565}{}{Courtney Coxsleeve}
{566}{}{Maria Swallo}
{567}{}{Lady J}
{568}{}{Glenda Glenn}
{569}{}{rainha Elizabeth}
{570}{}{Jenna Jammison}
{571}{}{Bunny LaJoya}
{572}{}{Madame Butterfly}
{573}{}{Jenny X}
{574}{}{Sweet Jane}
{575}{}{Darlin 'Nikki}
{576}{}{Sharonna}
{577}{}{Suzy Q}
{578}{}{Corvega Sally}
{579}{}{Pokeahotass}
{580}{}{Dominatrish}
{581}{}{Princesa X}
{582}{}{Carlotta}
{583}{}{Beijando Maria}
{584}{}{Vinho de Abril}
{585}{}{Rubi Vermelho}
{586}{}{Christie Chipps}
{587}{}{Lisa Lix}
{588}{}{Ópio}
{589}{}{Gato do bairro}
{590}{}{Lady Chatterfly}
{591}{}{A Vendedora}
{592}{}{Missus Holmes}
{593}{}{Debbie Dare}
{594}{}{Jessica Long}
{595}{}{Mynx}
{596}{}{Sascha}
{597}{}{Valerie Vixen}
{598}{}{Cruel}
{599}{}{}

# other boxer names
{700}{}{Mal Fisto}
{701}{}{Tony Gunn}
{702}{}{"Steel" Mark Torrance}
{703}{}{Xander "The Sure Thing" Holyland}
{704}{}{Aranha}
{705}{}{Fino}
{706}{}{Sweet Jones}
{707}{}{Il Roche}
{708}{}{Tito}
{709}{}{Rudy}
{710}{}{Big George}
{711}{}{Gooch}
{712}{}{Fat Johnny}
{713}{}{Nicki}
{714}{}{LaMotta}
{715}{}{Ivan}
{716}{}{Glass Joe}
{717}{}{Drago}
{718}{}{Tommy Gunn}
{719}{}{Apollo}

{750}{}{Joqq}
{751}{}{Pete McKneely}
{752}{}{Evan Holyfeld}
{753}{}{O Masticador}

# GOING TO THE CHOP SHOP
{1000}{}{Jules leva você para os blocos da cidade destruídos em torno de New Reno. Você não acha que poderia ter encontrado
 Este lugar por conta própria. Logo depois de você chegar, Jules desaparece.}
{1100}{}{A trilha leva você para os blocos da cidade destruídos que cercam o New Reno.}

# MORDINO/MYRON STASH
{1200}{}{Você descobre uma pequena caixa de metal. Você não teria encontrado isso se não estivesse procurando por ele.}

# CODY/CHOP SHOP
{1300}{}{Cody leva você para os blocos da cidade destruídos em torno de New Reno, então corre atrás do jeito que ele veio. Você
 Não pense que você poderia ter encontrado este lugar sozinho.}

# BOXING LEVELS
{1400}{}{Você derrotou seu primeiro desafiante.}
{1401}{}{Você derrotou o seu segundo adversário.}
{1402}{}{Você derrotou seu terceiro desafiante.}
{1403}{}{Você derrotou o Masticator!}
{1404}{}{Você se tornou o campeão dos Heavyweight de New Reno.}

{1500}{}{Você convenceu a Sra. Wright para destruir os alambiques.}
{1550}{}{Você testemunhou a transação secreta.}

{1600}{}{No calor da luta, o Masticador arranca sua orelha.}
{1700}{}{Enraivecida, você destrói a orelha dos Masticadores.}
