# MAP ENTEREANCE MESSAGE
{100}{}{Você chegou a uma planície do deserto fora de New Reno.}

# 0. QUICK LOOK, BOXES (WTG)
{110}{}{Você vê várias caixas cheias de produtos químicos.}

# 0. LOOK, BOXES (WTG)
{120}{}{Você vê várias caixas cheias de produtos químicos. You can't identify the chemicals,
 but they have been packed VERY carefully.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{130}{}{Você vê um Vertibird.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{140}{}{Você vê um Vertibird... an advanced form of helicopter. Unfortunately, you have no
 idea how to operate it.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{150}{}{Você não tem idéia de como operá-lo.}

# 2. NORMAL ACTION SEQUENCE (WTG)
{200}{}{(Esses caras me dão os rancorosos ...)}
{201}{}{(Cale a boca. Aqui eles vêm.)}
{202}{}{* Zztttt * Você possui a carga que solicitamos? * Zzzttt *}
{203}{}{Sim, os produtos químicos estão todos aqui. Você pode verificá-los se quiser.}
{204}{}{* Zztttt * Isso não será necessário. * Zzzttt *}
{205}{}{* Zztttt * Você sabe o que acontecerá se os produtos químicos não atenderem às especificações
 Nós pedimos. * Zzzttt *}
{206}{}{Certo, claro. Uh, e você trouxe os lightbringers ...?}
{207}{}{* Zztttt * As armas a laser estão em nossa baía de carga. * Zzzttt **}
{208}{}{* Zztttt * Para garantir a sua cooperação, transmitiremos a sequência de armamento para eles
 Uma vez que os produtos químicos estão carregados. * Zzzttt *}
{209}{}{Uh ... bem ... tudo bem então. Carregue-a, meninos -}
{210}{}{* Zztttt * No. * Zzzttt *}
{211}{}{* Zztttt * Vamos carregar a carga. * Zzzttt *}
{212}{}{Uh, certo ... certo. Claro. Dê-lhes espaço, meninos.}
{213}{}{Tudo certo; Estamos bem aqui. O resto de vocês guardam a cabeça de volta para Reno. Nos encontraremos com você.}

# 3. FLOAT SEQUENCE: INTRUDER (WTG)
{250}{}{Veja! Alguém nos observou!}
{251}{}{Mate eles!}
{252}{}{Parece que nos conseguimos um espião ...!}
{253}{}{* Zztttt * Missão abortada. Seqüência de falha de carga ativada. * Zzzttt *}
{254}{}{* Zztttt * Terminar os hostis, depois retornar à base. * Zzzttt *}

# 4. FLOAT SEQUENCE: OUT OF POSITION WARNING (WTG)
{300}{}{Não fique perto desses garotos blindados. Eles vão te criar.}
{301}{}{Volte para a posição.}
{302}{}{Pare de se mexer ... aqueles garotos blindados não gostam muito disso.}

# 5. FLOAT SEQUENCE: OUT OF POSITION, FINAL (WTG)
{350}{}{Droga! O que você está fazendo, dipshit ?!}
{351}{}{Volte para sua postagem! Que diabos você está fazendo - ?!}
{352}{}{* Zztttt * Missão abortada. Seqüência de falha de carga ativada. * Zzzttt *}
{353}{}{* Zztttt * Terminar os hostis, depois retornar à base. * Zzzttt *}

# 6. VERTIBIRD SEQUENCE: (WTG)
{400}{}{[Parece que há uma porta. Abra e monte?]}
{401}{}{Sim}
{402}{}{Afastar-se}
{403}{}{Junta o Vertibird.}
{404}{}{Deixe-o em paz.}

# 7. VERTIBIRD: TAKE OFF (7)
{450}{}{[A porta se selha atrás de você, e o Vertibird decola! Você não pode abrir a porta!]}
{451}{}{Uh-oh}
{452}{}{Ah Merda...}

# 8. DISPLAY TEXT: BOXES (WTG)
{500}{}{Estas caixas estão cheias de latas de metais pesados. A julgar pela embalagem de cuidados
 Eles, suspeitam que eles contenham algum tipo de produtos químicos perigosos.}

# GENERAL TALK
{550}{}{Agora, provavelmente, não é o melhor momento para conversar.}
