# 0. QUICK LOOK
{100}{}{Você vê Myron! Myron, baby, Myron!}

# 0. LOOK [FEMALE, CHR > 5] (WTG)
{150}{}{Você vê um adolescente de rosto pastoso que lida com você. Seu cabelo é irrduroso, e ele cheira levemente ao formaldeído.}
{151}{}{Você vê Myron. Ele está escolhendo você para fora do canto de seus olhos.}

# 1. LOOK, NORMAL (WTG)
{200}{}{Você vê um adolescente de cara pastosa. Seu cabelo é irrduroso, e ele cheira levemente ao formaldeído.}
{201}{}{Você vê Myron. Ele está olhando como um furão.}
{202}{}{Você vê Myron. Ele cheira ocasionalmente, como se tivesse um resfriado.}
{203}{}{Você vê Myron. Ele parece entediado.}
{204}{}{Você vê Myron. Enquanto observa, ele dá um grande bocejo, depois esfrega os olhos.}

# 2. OVERHEAD COMMENTS, PC = ARMED, SNEAK INTO MYRON'S  (WTG)
{210}{}{Saia do seu jumento e entre aqui, rapazes! Nós temos um intruso!}

# 3. OVERHEAD COMMENTS (WTG)
{215}{}{O que diabos você quer?}
{216}{}{Se você está aqui para o Jet, não perca meu tempo, basta sair.}
{217}{}{Achei que cheirava alguma coisa ...}

# 4. OVERHEAD COMMENTS [FEMALE, CHR > 5 OR FEMALE PORN STAR] (WTG)
{225}{}{Hell-oooo, lindo.}
{226}{}{Venha aqui e fale comigo um minuto. Eu não mordo.}
{227}{}{Não tente. Venha acabar.}
{228}{}{Eu acho que o loooove simplesmente entrou.}
{229}{}{Venha aqui muitas vezes?}
{230}{}{Mmmm-mmmm. Essas pernas vão todo o caminho?}

# 5. COMPANIONS (BONE NOSE + MARCUS) (WTG)
{235}{}{Que cheiro é aquele? Cheira a tribal.}
{236}{}{Ótimo osso em seu amigo, lá. Muito chique.}
{237}{}{Aquele tribal seu escravo?}
{238}{}{Seu amigo tribal compensou por alguma coisa?}
{239}{}{Como diabos essa coisa chegou aqui?}
{240}{}{Ótimo. Agora eles estão deixando mutantes aqui.}
{241}{}{Isso é realmente um torno no ombro do seu mutante?}
{242}{}{Esse mutante é seu escravo?}
{243}{}{O amigo mutante feio fica louco fácil?}
{244}{}{Que cheiro é aquele? Cheira a um mutante.}

# 6. COMPANIONS (LENNY) (WTG)
{255}{}{O que fede? Cheira a algo morreu.}
{256}{}{Ótimo. Agora eles estão deixando ghouls aqui.}
{257}{}{Você precisa extrair aquele ghoul seu. Ele cheira muito maduro.}
{258}{}{Esse ghoul radioativo?}
{259}{}{Esfregue uma cassete no seu ghoul para que cheira melhor, OK?}

# 7. IF MYRON IS A COMPANION (NORMAL) (WTG)
{265}{}{Vamos fazer alguma coisa em breve?}
{266}{}{Vamos pegar mais mulheres nesta roupa de merda de galinha.}
{267}{}{Podemos ir a algum lugar onde haja mais mulheres?}
{268}{}{Você deve estar feliz por estar com você para apontar todos os seus erros estúpidos.}

# 8. I'M HURT (WTG)
{375}{}{Ei, estou morrendo por aqui! Dê-me um stimpack já!}
{376}{}{Esse é meu sangue?}
{377}{}{Médico!}
{378}{}{Owwwww. Porra! Owwwww, isso dói!}
{379}{}{Ow! Que inteligência!}
{380}{}{Owwwwwwww Owwwww Ow. Ow. Ow?}
{381}{}{Owwww. Quer que ALGUÉM pareça estas feridas.}

# 9. I'M BADLY HURT (WTG)
{390}{}{Me dê uma maldita estimulação antes de eu passar!}
{391}{}{Me dê uma maldita estimulação! Estou entrando em choque!}
{392}{}{Alguém me da alguns primeiros socorros, rápido! Estou morrendo aqui!}

# 10. I'M POISONED (WTG)
{400}{}{Whoa ... Estou me sentindo um pouco fraco ...}
{401}{}{Vamos ver ... Estou nauseante ... palpitações ... febre. Muito provavelmente veneno.}
{402}{}{Uh ... não pode ... durar ... muito ... mais ... veneno ... espalhando ...}
{403}{}{Alguém poderia sugar esse veneno?}

# 11. I'M IRRADIATED (WTG)
{410}{}{Isso é brilhante? Me dê algum RadX na próxima vez que nos rodeamos em zonas de radiação, ok?}
{411}{}{Preciso de um Rad-away antes que a radiação come meus Gnads.}
{412}{}{Por que não bebemos o iro radioativo na próxima vez? Pelo menos morreremos mais rápido!}
{413}{}{Eu poderia usar o novo Reno com todas as radiações no meu corpo.}
{414}{}{Estou brilhando mais brilhante do que o novo Reno à meia-noite. Alguém conseguiu algum Rad-away?}
{415}{}{Ótimo. Um pouco de radiação, e eu sou uma lanterna humana.}
{416}{}{Alguém me deixou segurar o Rad-Away. Não vou usar tudo isso. Eu prometo.}

# 12. I DON'T LIKE THIS PLACE (WTG)
{425}{}{Por que não voltamos para o primeiro nível da masmorra onde estão todos os kobolds?}
{426}{}{Bom, jogar D & D todos esses anos me ensinou algumas coisas sobre a coragem.}
{427}{}{Passe o Buffout. Eu acho que vou precisar disso em breve.}
{428}{}{Ótimo lugar. Ótimo lugar para visitar. Que tal manter nossa estadia curta?}
{429}{}{Oh, isso é muito melhor do que estar em uma casa de banho acolhedora.}
{430}{}{Entremos, saia, está bem?}
{431}{}{Que tal nós visitamos esse lugar mais tarde?}
{432}{}{Por que diabos estamos aqui?}
{433}{}{Este lugar não está fazendo muito por minha moral.}
{434}{}{Eu digo que enviamos ol 'Bonenose para verificar a área. Sozinho.}
{435}{}{Por que não enviamos ol 'Bone-nose para explorar a área?}

# 13. I DON'T LIKE THIS PLACE (WTG)
{445}{}{Por que não enviamos ol 'Marcus para explorar a área?}
{446}{}{Eu digo que enviamos Marcus para verificar essa área. Sozinho.}
{447}{}{Passe o Buffout. Eu acho que vou precisar disso em breve.}
{448}{}{Por que não voltamos para o primeiro nível da masmorra onde estão todos os kobolds?}
{449}{}{Bom, jogar D & D todos esses anos me ensinou algumas coisas sobre a coragem.}
{450}{}{Ótimo lugar. Ótimo lugar para visitar. Que tal manter nossa estadia curta?}
{451}{}{Oh, isso é muito melhor do que estar em uma casa de banho acolhedora.}
{452}{}{Entremos, saia, está bem?}
{453}{}{Que tal nós visitamos esse lugar mais tarde?}
{454}{}{Por que diabos estamos aqui?}
{455}{}{Este lugar não está fazendo muito por minha moral.}
{456}{}{Vamos enviar Ol 'Lenny para verificar esta área. Sozinho.}
{457}{}{Por que não enviamos ol 'Lenny para explorar a área?}

# 14. USE DRUGS ON MYRON (WTG)
{465}{}{Ei, obrigado. Eu poderia usar um pouco me pegar.}
{466}{}{Nada como um regime químico rigoroso para manter minha mente limpa.}
{467}{}{Isso não significa que somos casados, não é?}
{468}{}{Tem alguma erva?}
{469}{}{Deixe-me segurar o stimpacks, ok?}
{470}{}{Ahhhhhhhhh.}
{471}{}{Ooooooohhh. Aaaaaaaah. Mmmmmm.}
{472}{}{Adoro quando faz isso.}
{473}{}{Os chems me fazem sentir todo pixellado.}

# 15. USE JET ON MYRON (WTG)
{485}{}{Ei, não use essa merda comigo! Salve-o para relaxar!}
{486}{}{Olha, eu não quero voar, e você também não. Enterre essa merda em algum lugar.}
{487}{}{Por que você não dá essa merda ao Ol? Bone-nose?}

# 16. USE JET ON MYRON W/MARCUS + LENNY (WTG)
{495}{}{Por que você não dá essa merda ao Marcus?}
{496}{}{Ei, não use essa merda comigo! Salve-o para relaxar!}
{497}{}{Cara, eu não quero voar e você também não. Enterre essa merda em algum lugar.}
{498}{}{Por que você não dá essa merda ao Ol 'Lenny?}

# 17. USE SCIENCE SKILL (WTG)
{505}{}{Tudo bem, tudo bem. Estou com isso.}
{506}{}{Retire-se, idiota. Descobri-lo-ei.}
{507}{}{Isso parece simples. Afaste-se, está bem?}
{508}{}{Sem problemas.}
{509}{}{Tempo para a rotina ol '' dedos mágicos '...}

# 18. USE SCIENCE SKILL (SUCCESS) (WTG)
{515}{}{Bingo!}
{516}{}{Eureka!}
{517}{}{Fuckin 'Ay!}
{518}{}{Myron faz isso novamente. A multidão fica selvagem!}
{519}{}{Ei, encontrei algo.}
{520}{}{Tudo feito. Fineto.}
{521}{}{Mais fácil do que andar de bicicleta. Ou sua mãe! Ha-Ha-Ha-Ha-Ha!}
{522}{}{Sim. Myron é - o Deus da Ciência.}
{523}{}{Bip. Myron usou a habilidade SCIENCE com sucesso.}

# 19. USE SCIENCE SKILL (FAIL) (WTG)
{530}{}{Nada.}
{531}{}{Nada.}
{532}{}{Sem sorte.}
{533}{}{Porcaria! Eu tentei tudo ...}
{534}{}{Não posso fazer nada com isso.}
{535}{}{Não descobri nada. Desta vez.}
{536}{}{Talvez com alguns mentos eu poderia tirar isso ... mmmm. Mentats.}
{537}{}{Minha habilidade não é suficientemente alta. Gaste alguns pontos de habilidade em mim, então vou tentar novamente. Ha-Ha.}
{538}{}{Não aprendi nada.}
{539}{}{Não posso fazer um sucesso no Science Roll sob estas condições.}
{540}{}{Bip. Myron usou a habilidade SCIENCE sem sucesso.}

# 20. GET OUT OF MY WAY (WTG)
{550}{}{Tudo bem, tudo bem! Pare de empurrar!}
{551}{}{É melhor parar de me empurrar, ou vou ... bem, pare de me empurrar.}
{552}{}{Bem, excuuuuuse-me.}
{553}{}{Tudo certo. Mas da próxima vez, você sai do meu caminho.}
{554}{}{Eu estava aqui primeiro. Mas tenha o seu caminho.}

# 21. USE HEALING (WOUNDED) (WTG)
{560}{}{Não precisa me dizer duas vezes.}
{561}{}{Eu poderia usar alguma cura feminina, saber o que quero dizer?}
{562}{}{Ahhhhhhh. Bom, os estimpacks não são muito hábitos.}
{563}{}{Oooooh, sim. Bom, os estimpacks não são muito hábitos.}

# 22. USE HEALING (NOT WOUNDED) (WTG)
{570}{}{Não me injete com essa merda. Estou bem, ok?}
{571}{}{Pare de me importar. Estou bem.}
{572}{}{Ei, não sune. Estou bem. Mas deixe-me segurar os estimpacks de qualquer maneira.}

# 23. WAITING (WTG)
{580}{}{Ei, deixe-me juntar-se a você novamente! Vamos lá!}
{581}{}{Me desculpe por ser tão idiota. Me dê outra chance.}
{582}{}{Estou ficando cansado de esperar por você.}
{583}{}{Estou tão entediado. Vamos, deixe-me sair com você.}
{584}{}{Gostaria de ter trazido um livro.}
{585}{}{Eu não vou esperar por você muito mais tempo.}

# 24. SPOUSE: FEMALE (WTG)
{590}{}{Então ... a Miria é realmente sua esposa?}
{591}{}{Miria é meio fofa. Posso ... bem, você sabe ... e sobre isso?}
{592}{}{Sua esposa suuuure é um observador.}
{593}{}{Então ... você e Miria. Vocês dois são sérios ou ...?}
{594}{}{Então ... você e Miria. Vocês são ambos livres para ver outras pessoas, ou ...?}
{595}{}{Você quer trocar esposas? Você pode ter o meu assim que conseguir um.}

# 25. WAITING TO JOIN, 2 (WTG)
{600}{}{Pronto para ir?}

# 26. VAULT CITY (WTG)
{605}{}{Por que diabos estamos aQUI?}
{606}{}{Todo mundo nesta cidade precisa de um enema.}
{607}{}{Estar em Vault City me faz ... descontente.}
{608}{}{O que é sobre o Vault City que me faz querer?}
{609}{}{Quando vamos voltar para Reno?}

# 101. STANDARD PARTY OPTIONS (WTG)
{615}{myn102b}{Então você finalmente apareceu, né? Eu sabia que você faria. Você precisa de mim.}
{616}{myn102a}{Então você finalmente apareceu, né, linda? Eu sabia que você faria. Tudo bem, vou me juntar a você novamente.}
{617}{myn103a}{Sim o que? Não posso ver que estou pensando aqui?}
{618}{myn103b}{Então você finalmente sábio, lindo? Finalmente percebo que sou o único para você?}
{619}{}{Você não parece muito bom, Myron. Cure você mesmo.}
{620}{}{Espere aqui até eu, uh, volte.}
{621}{}{Coloque a arma antes de se machucar.}
{622}{}{Fique perto de mim.}
{623}{}{Dê uma pequena distância entre nós, Myron.}
{624}{}{Espalhe um pouco, Myron. É melhor para nós dois.}
{625}{}{Eu tive algumas perguntas ...}
{626}{}{Not now, Myron. Eu tive algumas perguntas ...}
{627}{}{Tudo bem então. Apresse-se e vamos.}
{628}{}{Não, você continua esperando aqui. Eu voltarei. Eu prometo.}
{629}{}{Eu deixarei você voltar a não fazer nada então.}
{630}{}{Myron, sua mão é o único "um" para você.}

# 105. Gologatha
{640}{myn105_b}{Está em torno do Gólgota em algum lugar ... Eu vou deixar você saber quando eu vejo isso.}
{641}{}{Tudo bem, Myron.}

# 106. I HAD SOME QUESTIONS . . . (101, 108, 109, 112-131, 133-137, 143, 145-149, 151-154, 1001, 1003, 1004, 1005, 1006)
{645}{myn106}{Sim. O que está em sua mente?}
{646}{}{Conte-me sobre Jet.}
{647}{}{Você pode fazer algum Chems?}
{648}{}{Você não olha em forma superior, Myron. Tente se corrigir.}
{650}{}{Onde estava esse Mordino escondido de que você estava falando?}

# 107. TELL ME ABOUT JET (106, 244)
{655}{myn107a}{Ah, meu melhor vício. E quanto a isso?}
{656}{myn107b}{Já passamos por isso. Não estou aqui para ser sua memória.}
{657}{myn107c}{Já passamos por isso. Olha, eu serei seu amor escravo, lindo, mas não serei sua memória.}
{658}{}{Como você criou?}
{659}{}{Existe alguma cura para isso?}
{660}{}{Você pode me fazer um Jet?}
{661}{}{Você será um cadáver se não responder às minhas perguntas. Como você criou o Jet?}
{662}{}{Corte a merda, Myron. Existe alguma cura para o Jet?}
{664}{}{Eu mais cedo lança uma fervura com a minha língua do que deixar você ser minha escrava sexual, Myron.}
{665}{}{Myron, "amor escravo" é a última coisa que cruza minha mente quando penso em você.}
{666}{}{Eu estava pensando em usá-lo mais como um manequim de prática do que um escravo de amor, na verdade.}
{667}{}{Antes disso, eu queria beijar Sulik do que deixar ser meu escravo amoroso. Uh ... sem ofensa, Sulik.}
{668}{}{Eu mais tarde beijaria Marcus do que te deixaria ser meu escravo amoroso. Uh ... sem ofensa, Marcus.}
{669}{}{Nevermind, Myron.}

# 108. HOW DID YOU DEVELOP IT? (107, 129, 137, 236)
{680}{myn108}{Uh, no meu laboratório. Próxima questão?}
{681}{}{COMO você desenvolveu, cara inteligente?}
{682}{}{Esqueça isso. Tópico diferente ...}
{683}{}{Posso ver onde isso está acontecendo. Nevermind, Myron.}

# 109. HOW DID YOU DEVELOP IT, SMART GUY, 1? (108)
{690}{myn109}{Ah, Cristo. Bem ... quando encontrei a família Mordino de volta quando, eles estavam cultivando cactos peyote e tentando vendê-lo para turistas como a "experiência Reno". Besteira total.}
{691}{}{Continue.}
{692}{}{Esqueça isso. Tive algumas outras questões ...}
{693}{}{Esqueço que eu mencionei isso.}

# 110. HOW DID YOU DEVELOP IT, SMART GUY, 2? (109)
{700}{myn110}{Quero dizer, peyote? Vamos lá. Não é nem metade da força de, digamos, LSD da velha escola.}
{701}{}{Uh, sobre o Jet -?}

# 112. HOW DID YOU DEVELOP IT, SMART GUY, 3? (111)
{710}{myn112}{Além disso, uma viagem de peyote é muito longa. O lucro é rápido e o alto vício. Como, uh, barbitutates antes do Big One, sabe?}
{711}{}{Espero que isso esteja a liderar em algum lugar.}
{712}{}{Se você diz.}
{713}{}{Barbitúricos ... como cocaína da velha escola, manivela, tudo isso?}
{714}{}{Você quer dizer barbitúricos ... como cocaína da velha escola, manivela, tudo isso?}
{716}{}{Nevermind, Myron. Eu não tenho tempo para sua besteira longa.}

# 113a.
{725}{myn113a}{Certo. Posso terminar?}
{5725}{}{Bem bem. Qual foi o problema de fazer barbitúricos?}

# 113b. CONTINUE 1 . . . (112)
{726}{myn113b}{O problema é que, no novo clima, não podemos cultivar a maioria dos vegetais necessários para as melhores drogas.}
{727}{}{Você irsta de ouvir a si mesmo falar, certo?}
{728}{}{Estou contigo.}
{729}{}{Você quer dizer "veggies" como em plantas de coca, papoulas de ópio, esse tipo de coisa.}

# 114A.
{740}{myn114a}{Não conseguiu cultivar plantas de coca, papoulas de ópio - e o homem tentamos - então achamos que a nossa melhor aposta era shrooms.}
{741}{myn114b}{Certo, Sherlock. E tentamos - então descobrimos que a nossa melhor aposta era shrooms.}
{5741}{}{Por quê?}

# 114B. CONTINUE 2 . . . (113)
{742}{myn114c}{Você pode crescê-los se você usar muito o 'brahmin shit como fertilizante.}
{743}{}{Speaking of plenty of shit...Continue.}
{744}{}{ESTÁ BEM...}

# 115. CONTINUE 3 . . . (114)
{755}{myn115}{Além disso, os alucinógenos têm baixa sobrecarga, então comecei a experimentar com derivados de dietilamida de ácido lisérgico e psilocibina. Ainda…}
{756}{}{Ainda...?}

# 116. CONTINUE 4 . . . (115)
{765}{myn116}{Ainda assim, eu realmente queria chicotear um duro-bateu que não dependesse de extratos vegetarianos. Homem, eu era um idiota, porque a resposta acabou por ser os extratos, ou, mais precisamente, o que eles estavam crescendo.}
{766}{}{Você não se importa com o que eu digo, não é? Você simplesmente irsta de contar sua história.}
{767}{}{O que você quer dizer?}

# 117. CONTINUE 5. . . (116)
{775}{myn117}{Veja, o velho Jesus Mordino queria algo que os mineiros Redding ficassem viciados em rápidos e os fizessem trabalhar mais. Então, eu disse: "não há problema", certo?}
{776}{}{O que foi sobre Redding?}
{777}{}{O que foi sobre Redding, novamente?}
{778}{}{Right. Continue.}
{779}{}{Sim, não há problema.}

# 118. CONTINUE 6 . . . (117, 120)
{790}{myn118}{Bem, não foi muito difícil encontrar uma boa parte superior. Uma amostra desse extrato de proteína pré-guerra, corrompido e bam - anfetamina decente.}
{791}{}{Explique-me sobre Redding, novamente?}
{792}{}{Uh, "extrato de proteína?"}

# 119. EXPLAIN TO ME ABOUT REDDING AGAIN (117, 118)
{800}{myn119}{Redding? Cidade cheia de escavadores de ouro. Mordino quer controlar tudo. Então ele vem para mim com sua voz sibilante e diz: "Myron, Myron, me faça algo que me dará Redding".}
{801}{}{E você diz…}

# 120. EXPLAIN TO ME ABOUT REDDING AGAIN (119)
{810}{myn120}{E eu digo, "ok, qual o período de tempo que estamos olhando?" Ele continua - claro - "ontem". Senhores do crime. Quer que tudo seja feito rápido e descuidado. Pelo menos eles não têm um departamento de marketing.}
{811}{}{Entendo. Volte a falar sobre a produção de Jet.}

# 121. PROTEIN 1? (118)
{820}{myn121}{Antes do Big One, algumas empresas de carne estavam experimentando um extrato de proteína barato para o cultivo de alimentos, mas eles tinham que abandoná-lo.
 Uma pequena bactéria da pele contaminá-la, e tudo é ferrado.}
{821}{}{Parafusado? Como?}

# 122. PROTEIN 2? (121)
{830}{myn122}{A versão contaminada atuou como uma anfetamina quando ingerida. Pouco efeito colateral. Não pergunte. É, uh, técnico.}
{831}{}{Então ... de alguma forma, você conseguiu segurar este extrato de proteína?}

# 123. PROTEIN 3? (122)
{840}{myn123}{Eu não precisava. Quando eles primeiro ferraram, eles contaminaram toneladas dessa merda. E ao invés de abandoná-lo, eles alimentaram isso para seus rebanhos brahmin para tentar recuperar suas perdas.}
{841}{}{Ok, ok ...}
{842}{}{É melhor ir a algum lugar, Myron.}
{843}{}{Então, você usou a merda brahmin como fertilizante para os shrooms, exceto que a contaminação protéica pré-guerra dá o que os shrooms crescem em merda brahmin ... certos ingredientes extras?}

# 124A. PROTEIN? (123)
{850}{myn124a}{Fechar...}
{5851}{}{Sim...?}

# 124B. PROTEIN? (123)
{851}{myn124b}{Veja, começamos a experimentar com a merda brahmin como fertilizante para os shrooms, exceto obter isso; então, percebemos que os escravos que trabalhavam com tanques de fertilizantes estavam ficando altos com os fumos ...}
{853}{}{Então, os fumos foram suficientes para produzir o efeito?}

# 125A. PROTEIN? (124)
{860}{myn125a}{Riiiight ...}
{5861}{}{Eu pensei assim.}

# 125B. PROTEIN? (124)
{861}{myn125b}{Ao colocar toneladas de merda brahmin nas cubas, descobrimos que os fumos dão mais do que o suficiente de um chute. Eureka. Literalmente. "Claro, tivemos que testar para obter o mix direito ...}
{862}{}{Uh, quanto teste?}
{863}{}{Quanta teste exatamente?}
{865}{}{Nevermind, Myron.}
{866}{}{Isso parece uma carga de porcaria ... literalmente. Não parece que você sabe alguma coisa sobre a fabricação de quimicos. "Brahmin Shit Fumes?" Por favor. Já ouvi o suficiente.}

# 126. TESTING? (125)
{870}{myn126}{Hmmm ... cerca de cem escravos? Principalmente ataques cardíacos, hemorragias cerebrais, episódios psicóticos ... esse tipo de coisa.}
{871}{}{Você está louco? Você matou uma centena de seres humanos apenas para testes quimicos ?!}
{872}{}{Figuras ... O jato pode ser coisa muito poderosa. Pelo menos ninguém importante morreu. Ainda assim, difícil de acreditar que você matou a muitos, no entanto ...}
{873}{}{Entendo. Olha, eu tive algumas outras perguntas ...}

# 127. YOU MATARED A HUNDRED HUMAN BEINGS . . . (126)
{880}{myn127}{Bem, não de propósito. Quero dizer, os escravos são caros. Ainda assim, recuperamos o dinheiro nos primeiros meses, então a família Mordino não estava muito irritada comigo.}
{881}{}{Eu acho que você e eu vamos nos dar bem, Myron. Termina justifica os meios. Diga, eu tive algumas outras perguntas ...}
{882}{}{Myron, você é mais baixo que a sombra de uma cobra. Matando humanos para teste de quimioterapia ... é a coisa mais fria que já ouvi.}
{883}{}{Myron, você matou mais de uma centena de seres humanos por causa do teste químico? Você conseguiu sua consciência lobotomizada quando era criança?}
{884}{}{Conte-me sobre isso. Os preços dos escravos continuam a subir. Se os seres humanos apenas criaram mais rápido. De qualquer forma, tive algumas outras perguntas ...}
{885}{}{Entendo. Olha, eu tive algumas outras perguntas ...}
{886}{}{Eu acho que já ouvi o suficiente.}
{887}{}{Oh, tudo bem, então, tudo bem. Já ouvi o suficiente. Estou fora daqui.}

# 128. OBJECTION . . . (127)
{890}{myn128}{Você está curvado para mim por um monte de escravos? Eh, nós precisamos ter certeza de que Jet não mataria nossos clientes.}
{891}{}{Você tem um ponto, Myron. Tive algumas outras questões ...}
{893}{}{Oh, tudo bem, então, tudo bem. Parabéns, Myron. Você atingiu o menor denominador comum possível para um ser humano. Estou fora daqui.}
{894}{}{Parece sensato. Talvez falemos mais tarde.}

# 129. IS THERE A CURE? (107, 137, 236)
{900}{myn129a}{Quão pitoresco. Uma cura. Certo. Você vai peru frio. Claro, fiquei certo de que era uma opção difícil para o Jet.}
{901}{myn129b}{Bela aparência. Isso é dependência de drogas, não uma DST. Apenas a cura é ir peru frio, heh heh, e essa é uma opção reeal difícil com Jet.}
{902}{}{Como você criou o Jet?}
{903}{}{Myron, você é um cara muito inteligente. Considere um desafio. O que seria necessário para fazer uma cura para o Jet?}

# 130. YOU'RE PRETTY SMART . . . (129)
{910}{myn130}{Ah por amor da puta, não pode ser feito, está tudo bem? É uma maldita droga, não uma infecção bacteriana.}
{911}{}{É basicamente uma meta-anfetamina altamente habitual, certo? Você não pode usar um supressor do sistema nervoso para quebrar a dependência?}
{913}{}{Nevermind, Myron. Esqueça que eu perguntei.}

# 131. IT'S BASICALLY A HIGHLY ADDICTIVE . . . (130)
{920}{myn131}{Prova agradável, sem dados. Jet não está bloqueado tão fácil. Uma vez que está no seu sistema, não está saindo.}
{921}{}{E quanto ao uso de algum tipo de bloqueador de endorfina? Isso reprimiria a adição química e psicológica, não seria?}
{924}{}{Deixa pra lá então.}

# 132. WHAT ABOUT AN ENDORPHINE BLOCKER 1 . . . ? (131)
{930}{myn132}{Kee-rist. Isso deve ser o mais estúpido ... hmmmm ...}
{931}{}{Bem?}

# 133. WHAT ABOUT AN ENDORPHINE BLOCKER 2 . . . ? (132)
{940}{myn133}{Bem ... talvez funcionasse, mas tenho certeza de que Jet apenas mordiria essa merda. Agora, wh-wh, por que diabos estamos falando sobre isso ?! Wh-onde você conseguirá suas mãos contra bloqueadores de endorfina de qualquer maneira?}
{941}{}{Você me conta, Myron. Você é um cara brilhante.}

# 134. YOU TELL ME . . . (133)
{950}{myn134}{Talvez Vault City. Eles têm um bom armazém médico. Muitas antigas bases pré-holocausto também costumavam armazená-las para evitar o vício em drogas de combate.}
{951}{}{Por que não tentamos o Vault City?}
{952}{}{Bases pré-holocausto? Onde?}
{954}{}{Tudo certo. Talvez eu possa encontrar algum lugar.}

# 135. VAULT CITY? (134, 136)
{960}{myn135}{Ha! Você teria melhor sorte para convencer um radscorpion a se separar com a cauda do que buscar a Vault City para desistir de qualquer coisa.}
{961}{}{E quanto a essas bases pré-holocausto? Onde estão esses?}
{962}{}{Sim talvez. Olha, eu tive algumas outras perguntas ...}
{963}{}{Não há mal em tentar.}

# 136. PRE-HOLOCAUST BASES? (134, 135)
{970}{myn136}{Parece um cartógrafo? Você quer explorar o deserto para eles, você vai logo na frente.}
{971}{}{E quanto ao Vault City?}
{973}{}{Obrigado por nada, Myron.}
{974}{}{Eu só poderia fazer isso.}

# 137. PUT-DOWN (107)
{980}{myn137}{Oooh ... com um espírito assim, você tem certeza de ser sábio e ir para mim, lindo. Você verá.}
{981}{}{Tanto faz. Como você criou o Jet?}
{983}{}{Yeah, we'll see. Você pode me fazer um Jet?}
{985}{}{Esqueça que perguntei tudo, Myron.}

# 139. BUZZ-OFF, MYRON (1002)
{990}{myn139}{Wha-a-a-você está falando sério? Whoa, whoa, hey, hey ... você me mantém, eu vou te fazer um favor. Hã? Wh-Whadda, você diz?}
{991}{}{Como esse tipo de favor?}
{992}{}{Esqueça favores. Agora zombie, você é uma praga irritante.}
{993}{}{Esqueça favores. Agora espere aqui, sua praga irritante.}
{994}{}{Esqueço que eu disse alguma coisa. Você pode ficar.}

# 140. YOU CAN STAY (139, 1002)
{1005}{myn140}{Hoh! Oh, então, o que foi isso, como o humor tribal? Sim, hardy-har-har. Muito divertido.}
{1006}{}{Sim, nós, tribais, somos famosos por isso. Vamos indo.}

# 141. OKAY, I'LL WAIT/I'LL LEAVE (139)
{1010}{myn141}{OK! OK! Eu esperarei aqui. Phew! Você poderia me mostrar um pouco mais de respeito, você sabe. Eu sou MYRON.}

# 142. WHAT KIND OF FAVOR . . . (139)
{1020}{myn142a}{Ouvi falar de um prédio secreto com muita vegetação estranha ao redor. Se eu estiver com você, posso apontá-lo em um mapa.}
{1021}{myn142b}{Poderia ser eu conheço um dos pequenos cachos de Mordino no Golgotha, fora de Reno. Lotsa chips. Lotsa drogas. Só tenho que me manter em paz.}
{1022}{myn142c}{Eu vou ... Eu irei levar mais de suas coisas! Sem aborrecimentos quando você me pede para fazer drogas! Apenas me guarde, ok?}
{1023}{}{OK. Você pode ficar.}
{1026}{}{Esquece, Myron. Espere aqui até eu voltar.}

# 143. I NEED SOME DRUGS (106, 145-149, 151-154)
{1035}{myn143a}{"Posso fazer drogas?" Eu sou Myron. Whaddya precisa?}
{1036}{myn143b}{Ei, não pode aguentar o suficiente, hein? Whaddya precisa?}
{1037}{}{Um antídoto para o veneno de radscorpion.}
{1038}{}{Algum jato.}
{1039}{}{Alguns estimpacks.}
{1040}{}{Você pode fazer superestimpacks?}
{1041}{}{Nada. Tive algumas outras questões ...}
{1042}{}{Deixa pra lá.}

# 145. I NEED SOME RAD-SCORPION ANTIDOTE (NO TAILS) (143)
{1050}{myn145a}{Uhm, vou precisar de alguns sacos de veneno de radscorpion primeiro. Irônico, não?}
{1051}{myn145b}{Oh, bem, irstaria muito, linda, mas eu preciso de caudas de radscorpion. Ah bem.}
{1052}{}{Você pode fazer outros chems?}
{1053}{}{Forget it then. Eu tive algumas perguntas ...}

# 146. I NEED SOME RAD-SCORPION ANTIDOTE (TAILS) (143)
{1060}{myn146a}{Hmmm, não deve ser muito difícil. Quantas garrafas de antídoto você quer?}
{1061}{myn146b}{Ah, por chorar em voz alta. Já pensou que seria mais fácil ficar longe dos escorpiões de friggin, em primeiro lugar, genial? Quantos você quer desta vez ?!}
{1062}{myn146c}{Qualquer coisa para você, linda. Ele-ha! Quantos voce quer?}
{1063}{}{Apenas um.}
{1065}{}{Três é um encanto.}
{1066}{}{Faça o antídoto de todas as caudas que temos. Eles não são bons para muito mais.}
{1067}{}{Forget it. Você pode fazer outros chems?}
{1068}{}{None; I've changed my mind. Eu tive algumas perguntas ...}

# 147. FINISHED RAD-SCORPION ANTIDOTE (TAILS) (146)
{1081}{myn147a}{Feito. Aqui está.}
{1082}{myn147b}{Lá. É isso aí. Nada mais dessa merda, tudo bem? Da próxima vez, vá buscar algum remédio para fazer isso.}
{1083}{myn147c}{Feito. Aqui você vai, lindo.}
{1085}{}{Thanks. Look, Eu tive algumas perguntas ...}
{1086}{}{Obrigado, Myron. Você é um esporte real.}

# 148. MAKE JET (107, 129, 137, 143, 145)
{1095}{myn148}{Desculpe, não tem as "matérias-primas" que eu preciso ... não quero realmente também.}
{1097}{}{Esqueça, então. Tive algumas outras questões ...}
{1098}{}{Tudo certo. Muito obrigado, Myron.}

# 149. MAKE STIM-PACKS (143)
{1105}{myn149a}{Moleza; fácil; baba. Quantos pacotes você deseja?}
{1106}{myn149b}{Ei, gênio. Você já pensou que pode ser mais fácil ficar sem problemas, hein? Ok, quantos?}
{1107}{myn149c}{Apenas me diga quanto e onde você quer, lindo.}
{1111}{}{Faça o máximo de estimulações possível com o que estamos carregando.}
{1113}{}{Você pode fazer superestimpacks?}
{1114}{}{Esqueça. Eu tive algumas perguntas ...}

# 151. CAN'T MAKE STIM-PACKS (143)
{1125}{myn151}{Desculpe, nós simplesmente não temos o que eu preciso para estimular um estímulo. Vamos ver: você precisará de alguma raiz xander ... algum rockflower ... e uma hipogmação vazia.}
{1126}{}{Você pode fazer alguns outros chems?}
{1127}{}{Se você pode fazer estimpacks, você não poderia fazer alguns superestimpacks?}
{1128}{}{Tudo bem então. Eu tive algumas perguntas ...}

# 152. CAN'T MAKE SUPER STIM-PACKS (143, 151)
{1135}{myn152}{Claro que eu poderia ... "não temos o que eu preciso". Alguma daquela fruta mutada para o ácido cítrico ... um respingo a 'Nuka Cola ... e um pacote de estímulo normal.}

# 153. MAKE SUPER STIM-PACKS (143, 151)
{1145}{myn153a}{Repita depois de mim: Myron é um gênio. Quantos pacotes você deseja?}
{1146}{myn153b}{E se. Fique. Fora. Do. Problema? Nevermind, obviamente um conceito muito difícil. Quantos desta vez?}
{1147}{myn153c}{Myron é seu homem, lindo. Quantos?}
{1149}{}{Me dê dois.}
{1151}{}{Faça o máximo de estimulações possível com o que estamos carregando.}

# 201. INTRO (WTG)
{1170}{myn201a}{Quem é você, como diabos você entrou aqui? Wh-onde são esses guardas?}
{1171}{myn201b}{Por que diabos, lindo. O que Myron pode fazer, ah-uh, para você?}
{1172}{}{Gud. Nuh-uh.}
{1173}{}{Hell-oooooo Moron. Eu}
{1174}{}{Gud. Ded.}
{1175}{}{Pessoas fracas assistindo a porta deixam de respirar quando eu machuco-las}
{1176}{}{Tchau tchau}
{1177}{}{Seus guardas estão muito ocupados sendo mortos para estar assistindo a porta.}
{1178}{}{Eu usei esse distintivo. Marjorie me enviou.}
{1179}{}{Quem é Você?}
{1180}{}{Você Myron?}
{1181}{}{Easy there, tiger. Keep those hormones in check. Quem é Você?}
{1182}{}{Easy there, tiger. Keep those hormones in check. Você Myron?}
{1183}{}{Desculpa. Parece que entrei no quarto errado.}

# 202. BADGE (201)
{1195}{myn202}{So. Quem é Você? Spill it, or I'll have the guards BEAT it out of you.}
{1196}{}{Seus guardas estão muito mortos para fazer qualquer coisa. Tem alguma outra pergunta, sua pequena merda?}
{1197}{}{Quem é Você?}
{1198}{}{Você Myron?}
{1199}{}{Eu acho que vou sair daqui. Muito prazer em conhece-lo.}

# 203. RETARD THREATENS (201)
{1205}{myn203}{Ótimo. Um dos anões mentais do andar de cima. Olha, eu não tenho muito aqui, mas você pode, tuh-tuh - pegue o que quiser.}
{1206}{}{WAN YOU DED}
{1207}{}{Wan Ull. Agora.}
{1208}{}{Hoo yoo? YooFREN de}
{6208}{}{?}
{1209}{}{Byeeeee}

# 204. GIVE ME EVERTHING (203, 210, 212, 214)
{1215}{myn204}{Certo! Pode apostar! Uh, aqui está você. Aqui está tudo. Agora uh, você volta para sua barraca agora, ok?}
{1216}{}{Nuh-uh. Matar.}
{1217}{}{Hoo yoo? YooAMIGO de}
{6218}{}{ ir}

# 205. HOO YOO? YOU FRIEND OF [x]? (203, 204)
{1225}{myn205}{Abso-fucking-lutely! Heh, you bet! You and I are irnna be the best of friends, okay?}
{1226}{}{Mentira?}
{6226}{}{ MATAR}
{1227}{}{Fren dá ull}

# 207. HELL-OOOOO MORON, ME [x] (201)
{1235}{myn207}{Claro que você é. Tenha um assento na cama. Posso pegar uma bebida, talvez um pouco ... Jet?}
{1236}{}{Sentar. Drenk.}
{1237}{}{Yoofren?}

# 208. OKAY ME HAVE SOME OF THOSE ME GUESS ME HAVE RUFF DAY (207, 210)
{1245}{myn208}{Excellent...here you ir. A little drink - help you re-lax, y'know what I mean?}
{1246}{}{Drenk}
{1247}{}{Yoo}
{6247}{}{'s fren?}

# 209. [x] HAVE TO GO NOW . . . (207, 208)
{1255}{myn209}{Uh, hey, hey, hey! Espere um minuto! Fique - tome uma bebida primeiro! Podemos conversar, ser amigos. Você quer que sejamos amigos, né?}
{6256}{}{ drenar}
{6257}{}{ fren?}

# 210. YOU BE [x]'S FRIEND (207, 208, 209)
{1265}{myn210}{Sou suura, seremos amigos.}
{1266}{}{Wan fren.}
{1267}{}{Fren. Giv ull. Não há dinheiro.}

# 211. TAKE DRINK (208, 209)
{1275}{myn211}{Agora, você relaxa, doce ...}
{1276}{}{Okeezzzzzzz Zznnzznn Zzznnnzzzz}

# 212. TAKE DRINK (CON RESISTANT) (208, 209)
{1285}{myn212}{Hmmmm. Você deve ter a constituição de um brahmin. Saia daqui, linda.}
{6287}{}{ ir.}

# 213. ME SEE NO ASS JACKALS (201)
{1295}{myn213}{Os guardas não valem as fichas que você paga por eles ... bem, meu amigo retardado, fomos apresentados, então por que você NÃO OBTER O INFERNO AQUI AQUI!}
{1296}{}{OW EARS. MATAR.}
{1297}{}{Nuh fren?}
{6298}{}{ ir, }

# 214. YOU FRIEND? (210, 212, 213)
{1305}{myn214a}{Sim, você aposta, amigo.}
{1306}{myn214b}{Sim, você acha, querida.}
{1307}{myn214c}{Você e eu - amigos para sempre nunca. Ou a próxima injeção. AGORA OBTENHA O INFERNO AQUI AQUI!}
{1308}{}{NUH FREN. MATAR.}
{1309}{}{Fren disse. Não há nada.}

# 215. YOU'RE GUARDS ARE TOO DEAD TO BE WATCHING DOOR (201, 202)
{1325}{myn215a}{Deus-DAMN it! Eu disse a Jesus que esses dois idiotas não podiam guardar uma pedra! Então, você congelou, hein? Vai me matar também?}
{1326}{myn215b}{Whoa. Hot and deadly! So you iced them, huh? You irnna kill me, too?}
{1327}{}{Eu estouthinking about it. You irt something to convince me otherwise…kid?}
{1328}{}{Not unless you do something stupid. Quem é Você?}
{1329}{}{Not unless you do something stupid. Você Myron?}
{1330}{}{Sim, porque não? Eu não matei ninguém desde que comecei essa conversa.}
{1331}{}{Agora não. Talvez mais tarde.}

# 216. I'M THINKING ABOUT IT . . . (215)
{1345}{myn216a}{Claro, amigo.}
{1346}{myn216b}{Claro, senhora.}
{1347}{myn216c}{Você aposta, lindo.}
{1348}{myn216d}{Eu ... eu posso te dar drogas. Você está olhando para voar?}
{1349}{}{Na verdade, eu quero tudo o que você tem. Entregue-o, e eu vou deixar você viver.}
{1350}{}{Sure. Give me all the chems you irt.}
{1351}{}{Eu não quero nada agora. Talvez mais tarde.}

# 217. GIVE ME EVERYTHING (216)
{1365}{myn217}{All right, all right. Here you ir. Now will you leave me alone?}
{1366}{}{No. Quem é Você?}
{1367}{}{No. Você Myron?}
{1368}{}{Certo. Por enquanto ... talvez eu esteja de volta.}

# 218. WHO ARE YOU? (SMART) (201, 202, 215)
{1375}{myn218a}{M-talvez. W, quem diabos é você?}
{1376}{myn218b}{Say, you one of Mordino's new whores or just a big fan of Myron? Ooh, you irt a name to ir with those legs, beautiful?}
{1377}{myn218c}{Quem diabos é você?}
{1378}{myn218d}{Eu sou alguém que estava procurando por alguém como você, lindo. E você é...?}
{1379}{}{.}
{6379}{}{Eu estou}
{1380}{}{Eu estoujust a traveler passing through.}
{1381}{}{Eu estousomeone who's in the wrong room. Later.}

# 219. I'M [x]/I'M JUST A TRAVELER PASSING THROUGH (218)
{1395}{myn219a}{É assim? Por quê você está aqui? Hã? Pensou que você poderia bater em Myron para obter algumas drogas gratuitas?}
{1396}{myn219b}{Seja o que for, lindo. Quer algumas drogas para quebrar o gelo, ou devemos simplesmente chegar a alguma dança de colchão?}
{1397}{}{Eu gostaria, mas não tenho dez segundos de sobra agora. Sobre o que você está falando?}
{1398}{}{Chems? Como o quê?}
{1399}{}{Eu estoudefinitely in the wrong room. Pardon me.}

# 220. DRUGS? LIKE WHAT? (219)
{1405}{myn220a}{Ei, estúpido! Jet, mãe fucker, Jet! Yer conversando com seu criador. Seu criador. É ... Deus.}
{1406}{myn220b}{Você é estúpido? Jet, puta, Jet! Yer conversando com seu criador. Seu criador. É ... Deus.}
{1407}{myn220c}{Você já ouviu falar da Jet, lindo? Bem, está falando com seu criador. Seu criador. É ... Deus.}
{1408}{}{Besteira. Você não fez Jet.}
{1409}{}{Você fez Jet?}
{1410}{}{Você fez Jet? No way! That stuff is making a MATARING on the streets!}
{1411}{}{Big deal. Eu estouout of here.}
{1412}{}{Sua mãe deve estar orgulhosa. Mais tarde, criança.}
{1413}{}{Really? Interesting. I have to ir now.}

# 221. BULLSHIT. YOU DIDN'T MAKE JET. (220)
{1425}{myn221a}{Eu fiz, então, faça Jet! O que, você acha que este laboratório é para show?}
{1426}{myn221b}{Desculpe provar que você está errado, lindo, mas olhe ao redor. Este laboratório não é apenas para mostrar.}
{1427}{}{Tudo certo. Talvez você fizesse Jet.}
{1428}{}{Por que você fez o Jet?}
{1430}{}{Your mother must be proud. Eu estouout of here.}

# 222. ALL RIGHT. MAYBE YOU DID MAKE JET. (220, 221)
{1445}{myn222}{Maldito seja o que fiz! Eu faço a merda que todo mundo quer e não pode obter o suficiente.}

# 223. WHY DID YOU MAKE JET? (221, 222)
{1455}{myn223}{"Por quê?" 'Cause I could. Family Mordino needed a product, Myron makes a product, Mordino makes Myron happy...at least as happy as they're able. Nice lil' circle o' love, huh?}
{1456}{}{Como você fez o Jet?}
{1457}{}{"Tão felizes quanto possível?" Você está feliz aqui?}
{1458}{}{Que tal eu sugiro um novo círculo para você? Mordino não conhece talento quando vê-lo - eu sei.}
{1459}{}{Yeah, great. I have to be iring now.}

# 224. HOW DID YOU MAKE JET? (223)
{1465}{myn224a}{Ha, você não entenderia. É FORTE acima de você.}
{1466}{myn224b}{Não se preocupe com sua bela cabeça, linda. Posso dar-lhe outra coisa para a sua cabeça para trabalhar.}
{1467}{}{Você está feliz aqui?}
{1468}{}{Sim, acho que um idiota como eu não poderia esperar para entender o processo de fabricação de um híbrido alucinógeno-anfetamina como Jet, hein?}
{1469}{}{Sim, acho que um bimbo como eu não poderia esperar para entender o processo de fabricação de um híbrido alucinógeno-anfetamina como Jet, hein?}
{1472}{}{I think you'd be surprised about how much I know about your amateurish hallucinogenic-amphetamine hybrid. Eu estounot convinced a child like you didn't just STUMBLE across it, Myron.}
{1473}{}{Well, thanks for making the effort, Myron. I have to be iring now.}

# 225. YOU HAPPY HERE? (223, 224, 246)
{1485}{myn225}{Pretty much. They give me whores, cash, drugs. My own lab. The creative freedom I need to make magic, but, well...no, naw, it's a irod gig.}
{1486}{}{Bem o que? Eles estão te tratando bem?}
{1487}{}{Good to hear it, Myron. I have to be iring now.}

# 226. WELL WHAT? (225)
{1495}{myn226}{Bem, veja, os Mordinos não mostram Myron o R-E-S-P-E-C-T, certo? Eu lhes digo o que eles deveriam fazer, eles dizem 'cale a boca, Myron' ou 'volte para o laboratório, Myron'. Bastardos.}
{1496}{}{Talvez eu possa ajudá-lo. Você quer abandonar esta cidade? Viaje comigo, e então os Mordinos vão acordar o quanto você é valioso e rápido.}
{1497}{}{Você é muito valioso para estar aqui, Myron. Você deve sair.}
{1498}{}{Too bad, Myron. I have to be iring now.}

# 227. WELL WHAT 2 (226)
{1505}{myn227}{They've forgotten I'M the reason they control Reno AND the reason why Redding'll be sucking at their tit in a few
 months. Most Mordinos irt more hair on their butt than brain cells, y'know what Eu estousaying?}
{1506}{}{Uh, eu disse, talvez eu poderia ajudá-lo ...}
{1507}{}{Você definitivamente é muito valioso para estar aqui, Myron ... você deveria sair, como eu estava dizendo.}
{1509}{}{Eu estoubeginning to see why they don't listen to you.}
{1510}{}{You bet, Myron. I have to be iring now.}

# 228. WELL WHAT 3 (227)
{1515}{myn228}{E outra coisa: os Mordinos não conseguem atravessar os crânios de que não estou interessado em purificar Jet. Ele faz o que é suposto fazer. Eu quero fazer novas drogas, não re-ferramenta antigas, sabe?}
{1516}{}{Posso te ajudar. Por que você não abandona esta cidade, viaja comigo, e então os Mordinos vão despertar para o quão valioso você é.}
{1517}{}{Você está absolutamente correto. Você é muito valioso para estar aqui, Myron! Você deve sair!}
{1518}{}{O que você dizia sobre Redding?}

# 229. MAYBE I CAN HELP YOU . . . (228, 231)
{1525}{myn229a}{Hmm .... seu menino se pergunta saindo da cidade. Ha. Isso os despertaria. Sim.}
{6525}{}{Claro que sim. Eu os faria ver o que eles realmente perderam.}

# 229B. MAYBE I CAN HELP YOU . . . (228, 231)
{1526}{myn229e}{Eu gosto disso.}
{1527}{myn229d}{Eu gosto do jeito que você pensa, lindo.}
{1528}{myn229c}{Então, onde nos dirigimos?}
{1529}{myn229b}{Então, onde nós fomos, lindos?}
{1530}{}{Apenas me acompanhe.}
{1531}{}{Então venha comigo.}
{1532}{}{Hold on a minute. I haven't said yes yet. What can you do, Myron? I can't just have anyone traveling with me. I irt standards.}
{1533}{}{First off, what are you irod at, Myron?}
{1534}{}{Em nenhum momento ainda. Diga, eu tinha mais algumas perguntas ...}
{1535}{}{Em nenhum outro momento, Myron. Volto para você, no entanto.}

# 230. JUST FOLLOW ME. (FULL UP) (229, 247)
{1545}{myn230a}{Naw, você parece cheio. Whydoncha abandonou o tribal. Parece que ele toma uma cabeça de osso muito a sério.}
{1546}{myn230b}{Naw, você parece cheio. E Myron não fica com o lixo mutante. Ah-heh, nenhuma ofensa, grande cara.}
{1547}{myn230c}{Uh, naw, você parece completo. E uh, Myron não fica com ghouls. Nunca saiba quando eles são gunna deixam cair uma parte do corpo em seu sapato.}
{1548}{myn230d}{Naw, eu não quero sair com outra família. Os Mordinos eram suficientes. Perca uma bagagem e depois venha falar comigo.}
{1549}{myn230e}{Okay, certo. As moscas não o seguiriam se você estivesse coberto de merda. Olá, esqueça.}
{1550}{}{Tudo bem então. Bem, eu tenho algumas outras perguntas ...}
{1551}{}{Atitude bem esclarecida. Pensarei nisso, Myron.}
{1552}{}{Não, ele vale pelo menos dois de vocês. Mais tarde, criança.}
{1553}{}{Kid, seu ego simplesmente escreveu um cheque no seu corpo não pode ganhar dinheiro. Prepare-se para morrer.}
{1554}{}{Eles também Você verá.}
{1555}{}{Sua perda, Myron. Mais tarde.}

# 231. FAST TALK: I SUGGEST A NEW CIRCLE (223)
{1565}{myn231}{Yeah? Eu estoulistening...}
{1566}{}{Talvez nós possamos ajudar uns aos outros. Eu poderia usar um homem com suas habilidades. Por que você não abandona esta cidade, viaja comigo por um tempo, e então os Mordinos vão despertar para o quão valioso você é.}
{1567}{}{Oh, esqueça o que eu disse. Diga, eu tive algumas outras perguntas ...}
{1568}{}{Esqueça. Não funcionaria de qualquer maneira.}

# 232. JUST FOLLOW ME. (FREE SLOT) (229, 231, 247)
{1575}{myn232a}{Tudo certo.}
{1576}{myn232b}{Tudo bem, lindo.}
{1577}{myn232c}{Por que diabos não? Vamos explodir este carrinho de palhaço.}
{1578}{}{Nós estamos fora daqui.}
{1579}{}{It's 106 miles to Arroyo, we irt a full fusion cell, half a pack of Radaway, it's midnight, and Eu estouwearing a 50-year old Vault 13 jumpsuit. Let's hit it.}

# 233. WHAT CAN YOU DO? (229, 247)
{1585}{myn233}{Ah! What, you need Myron's resume? Eu estouthe science guy. Know all, see all. Not to mention I can make whatever drugs you need. With the right raw materials.}
{1586}{}{Tudo bem então, você passou a entrevista. A parte sobre os chems ajudou. Me siga.}
{1587}{}{Vou pensar sobre isso. Tenho mais algumas perguntas para você ...}
{1588}{}{Bem, vou pensar sobre isso ... é só isso, bem, sem ofensa, mas os caras da ciência têm uma reputação notória por estarem sem valor no combate.}
{1589}{}{Preciso pensar sobre isso. Eu voltarei.}

# 234. WHAT WAS THAT ABOUT REDDING 1. . . ? (227, 228)
{1595}{myn119}{Redding? Cidade cheia de escavadores de ouro. Mordino quer controlar tudo. Então ele vem para mim com sua voz sibilante e diz: "Myron, Myron, me faça algo que me dará Redding".}
{1596}{}{E você diz...}
{1597}{}{Hmmm. Tive algumas outras questões ...}

# 235. WHAT WAS THAT ABOUT REDDING 2. . . ? (234)
{1605}{myn120}{And I say, 'okay, what timeframe we looking at?' He ires - of course - 'yesterday.' Crime lords. Want everything done fast and sloppy. At least they don't have a marketing department.}

# 236. I GUESS AN IDIOT . . . (224)
{1615}{myn236a}{Yeah. Por quê? You irnna try and prove me wrong, pal? }
{1616}{myn236b}{Yeah. Por quê? You irnna try and prove me wrong, lady? }
{1617}{myn236c}{Sim? Mas oi, não me defiende, lindo. Você não foi construído para cérebro, sabe?}
{5616}{}{Claro que estou. Me teste.}
{5617}{}{Eu acho que eu poderia te mostrar uma coisa ou duas.}

# 236B. I GUESS AN IDIOT . . . (224)
{1618}{myn236d}{Esqueci mais sobre a pesquisa farmacêutica do que você nunca saberá.}
{1619}{}{Existe alguma cura para o Jet?}
{1620}{}{Bem. Então, como você fez Jet?}
{1621}{}{Primeiro, responda-me isto: como você fez um alucinógeno híbrido-anfetamina? Jet parece ter algumas ... propriedades únicas.}
{1623}{}{Esqueça. Tive algumas outras questões ...}
{1624}{}{Forget this. Eu estououtta here.}
{1625}{}{Kiss my ass, you arrogant shit. Eu estououtta here.}

# 237. I GUESS AN IDIOT . . . (224)
{1635}{myn237}{Amador? Ama-amateur ?! O puro gênio de Jet, e você não esquece isso! E eu não tropecei por isso, EU FIZ.}
{1636}{}{Eu não acredito em você. Mostre-me o processo.}
{1637}{}{Whatever, kid. Eu estouout of here.}

# 238. FIRST OFF, ANSWER ME THIS ABOUT THE HYBRID . . . (236, 237)
{1645}{myn238}{Duas palavras: merda brahmin.}
{1646}{}{O que você usa para cultivar o alucinógeno?}
{1647}{}{Você usa a merda brahmin como fertilizante para cultivar a cultura Jet, certo? E quanto a isso?}
{1648}{}{Não quer me dizer? Bem. Então eu tenho algumas outras questões ...}
{1649}{}{All right then. I can see where this is iring. Deixa pra lá.}

# 239. THAT WHAT YOU USE TO GROW THE SHIT IN . . . (238)
{1655}{myn239a}{Very irod. And that's all yer ever irnna learn, pal. You wanna know, you figure it out.}
{1656}{myn239b}{Very irod. And that's all yer ever irnna learn, lady. You wanna know, you figure it out.}
{1657}{myn239c}{Very irod, beautiful. But that's all yer ever irnna learn, so don't trouble your pretty little head about it. Enough talk: why don't you and me, uh, hehh...}
{1658}{}{Então, a merda brahmin tem algumas propriedades químicas que estimulam o sistema nervoso humano?}
{1659}{}{Eu só poderia. Tive algumas outras questões ...}
{1660}{}{-- talk some more? Excellent! Eu tive algumas perguntas ...}
{1661}{}{Fine. I have to be iring.}
{1662}{}{Uh, por que você e eu não falamos mais tarde? Boa ideia. Até logo.}

# 240. SO THE BRAHMIN SHIT HAS SOME CHEMICAL PROPERTIES . . . (239)
{1675}{myn240}{You sure do ask a lot of irddamn questions. The answer is yeah, maybe...say, wh-where did you learn all this stuff anyway? You from Vault City or something?}
{1676}{}{Para responder a sua pergunta, sim ... PODE FAZER. Onde você aprendeu tudo isso?}
{1677}{}{Não exatamente. Eu simplesmente escolho essas coisas. É muito fácil, realmente.}
{1678}{}{Não. Olha, eu tive algumas outras perguntas ...}
{1679}{}{Vault City. Onde é isso?}
{1680}{}{Vou deixar você se perguntar. Você já me contou tudo o que preciso saber.}

# 241. TO ANSWER YOUR QUESTION, MAYBE  (240)
{1685}{myn241a}{Yeah, keep mouthing off, smartass. I could oxidize circles around you. Eu estoua natural. Self-taught. None of that bullshit Vault City 'purer-than-thou' 'tude, see?}
{1686}{myn241b}{Heh, hein, ha! Você é um afiado, bonito ... cabelo de corvo, dentes, garras ... mmm-mmm. Então você aprende sua merda na Vault City ou o quê?}
{1687}{}{Eu não aprendi na Vault City. Eu simplesmente escolho essas coisas. É muito fácil, realmente.}
{1689}{}{Tive algumas outras questões ...}

# 244. QUESTION NODE (108-110, 112-131, 133-137, 143, 145-149, 151-154, 229-231, 233-243, 245-247)
{1695}{myn244}{O que didja quer saber?}
{1696}{}{Conte-me sobre este lugar.}
{1697}{}{Conte-me sobre a família Mordino.}
{1699}{}{I'm iring to ir now.}

# 245. TELL ME ABOUT THIS PLACE (244)
{1705}{myn245a}{Os estábulos? Testamos novos tipos de Jet aqui. E quanto a isso?}
{1706}{myn245b}{Os estábulos? Uh, nós testamos novos tipos de Jet aqui. Que tal, linda?}

# 246. TELL ME ABOUT THE MORDINO FAMILY (244)
{1715}{myn246}{Eles são meus clientes. Eles estão bem ... acho.}
{1716}{}{Bem o que? Eles não estão tratando você bem?}

# 247. MYRON AGAIN (WTG)
{1725}{myn247}{You again. So…ready to ir?}
{1726}{}{Claro, Myron. Vamos sair daqui.}
{1727}{}{Hold on a minute. I haven't said yes yet. What can you do, Myron? I can't just have anyone traveling with me. I irt standards.}
{1728}{}{Primeiro, quais habilidades você tem o Myron?}
{1729}{}{Não, não exatamente. Eu tive algumas perguntas ...}
{1730}{}{Não no momento. Por que você não esfria seus calcanhares por um tempo?}

# 248. GOT A JUMPSUIT . . . (232)
{1735}{}{You're kind of weird...Eu gosto disso.}
{1736}{}{You're kind of weird...Eu gosto disso.}

# 1001. HEALING (101, 1001, 1003, 1004, 1005, 1006)
{1745}{myrn104a}{Pare de me importar.}
{1746}{myn104b}{Owww! Hurts! It hur - oh, it. No. No, Eu estoupretty much okay. Stings a little.}
{1747}{myn104c}{Eu estoudying over here! Gi-give me a stimpack. Or two. Or three.}
{1748}{myn104d}{Isso é você? Não posso ... ver ... perder ... consciência. * Tosse * * Tosse * Ajuda ... eu ...}
{1749}{}{Hmmmm. Cure-se novamente.}
{1753}{}{Me dê um pouco de distância, Myron.}
{1756}{}{Deixa pra lá então. Let's ir.}
{1757}{}{Suck it up, Myron. We irt a lot of ground to cover.}

# 1002. WAIT FOR ME HERE. (101, 1001, 1003, 1004, 1005, 1006)
{1765}{myn138}{Eh, desculpe-me. Espero por você aqui? Você está de brincadeira? Diga-me que você está brincando.}
{1766}{}{Fique. Aqui. Até. Eu vim. Costas. Compreendo?}
{1767}{}{Eu voltarei. Não sune.}

# 1003. PUT WEAPON AWAY (101, 1001, 1003, 1004, 1005, 1006)
{1775}{myn1003a}{Ah, vamos ... tudo bem. Ainda quero experimentar essa nova técnica de explosão de fogo em que estive trabalhando.}
{1776}{myn1003b}{Uh, essa arma? Oh ... desculpe por isso, lindo. Parece que ... sair todo o tempo, você sabe?}
{1781}{}{Talvez seja melhor você voltar um pouco, Myron.}
{1784}{}{Not while you're hanging with me, you won't. Now let's ir.}
{1785}{}{I heard it ires off prematurely, too. Now let's ir.}

# 1004. STAY CLOSE (101, 1001, 1003, 1005, 1006)
{1795}{myn1004a}{Eh ... tudo bem. Você não está batendo em mim, você está?}
{1796}{myn1004b}{Whatever you say, irrgeous. Rrrrooow.}
{1802}{}{Na verdade, me dê muita distância, Myron. É melhor para nós dois.}
{1804}{}{When I hit you, you'll know. Now let's ir.}
{1805}{}{Calm down, Myron. Let's ir.}

# 1005. STAY MEDIUM (101, 1001, 1003, 1004, 1006)
{1815}{myn1005a}{Bem ... tudo bem. Mas eu ouço que são os caras do meio que sempre conseguem primeiro.}
{1816}{myn1005b}{Tudo bem, vou assistir sua bunda ... er ... uh, de volta com cuidado.}
{1820}{}{Na verdade, esqueça isso: fique perto de mim em vez disso.}
{1822}{}{Espalhe ainda mais, Myron. É melhor para nós dois.}
{1824}{}{Eu estoucounting on it. Now let's ir.}
{1825}{}{Greeeeat. Let's ir.}

# 1006. STAY LONG (101, 1001, 1003, 1004, 1005)
{1835}{myn1006a}{All right, I'll keep an eye on things back here. Gives me a irod position to practice my burst-fire technique.}
{1836}{myn1006b}{Wha - eu tenho B.O. ou alguma coisa?! Sheesh.}
{1841}{}{Venha um pouco mais perto, Myron.}
{1844}{}{Tanto faz. Now let's ir.}
{1845}{}{If it was just your body odor, I could stand it. Let's ir.}

# 1100. REJOIN (101, 1001)
{1860}{myn232a}{Tudo certo.}
{1863}{}{Kid, seu ego simplesmente escreveu um cheque no seu corpo não pode ganhar dinheiro. Prepare-se para morrer.}
{1866}{}{Let's ir.}

# dude floats
{1870}{}{Mentir-se agora.}

# misc messages
{1875}{}{Você convenceu Myron de uma cura.}
{1880}{}{Essa é a sepultura onde o Big Jesus encontrou essas fichas extras.}
{1885}{}{Você convenceu Myron de deixar os estábulos.}

# 309. GET OUT OF MY WAY (WTG)
{1957}{}{Tudo bem, tudo bem! Pare de empurrar!}
{1958}{}{Ei, dê uma pausa. Eu não programei meu A.I.}
{1959}{}{Bem, excuuuuuse-me.}
{1960}{}{Tudo certo. Mas da próxima vez, você sai do meu caminho.}
{1961}{}{Eu estava aqui primeiro. Mas tenha o seu jeito.}

# 306. I NEEDED SOME TIME TO MYSELF (WTG)
{2091}{}{You irt some chips to share? I need to save some women from their virginity.}

# 242. I PICK IT UP PRETTY EASY (240, 241, 243)
{2675}{myn242a}{Easy, huh? Eu estouthe best. Twice as irod as any of those Vault City pecker checkers.}
{2676}{myn242b}{Ah, sim, você está certo sobre isso. Mais fáceis de aprender do que essas coisas, os verificadores pecadores da City do Vault o levariam a acreditar.}
{2678}{}{Let it ir, Mr. Insecurity. I had some other questions...}
{2679}{}{Que comando maravilhoso do idioma que você tem. Vejo você depois, Myron.}

# 243. VAULT CITY (240, 241, 242)
{2685}{myn243}{A city to the northeast. Buncha "genetically pure" humans. They irt their noses so high in the air they'll drown when it rains.}
{2686}{}{Well, Eu não aprendi na Vault City. Eu simplesmente escolho essas coisas. É muito fácil, realmente.}
{2687}{}{Interessante. Tive algumas outras questões ...}
{2688}{}{Que comando maravilhoso do idioma que você tem. Vejo você depois, Myron.}

# NEW PARTY STUFF
{2004}{myn324}{Que diabos você está falando?}
{2001}{myn321}{Isso é uma merda.}
{2033}{myn353}{Me bate.}
{2023}{myn343}{Eu antes de lamber as bolas de Marcus.}
{2024}{myn344}{Eu antes de lamber as bolas enrugadas de Lenny.}
{2025}{myn345}{Eu mais cedo deixaria aquele ciber-cão morder meus testículos.}

{3000}{}{Myron, acho que precisamos discutir ... distância.}
{3001}{}{Vamos falar sobre o seu equipamento por um segundo.}
{3002}{}{Esqueço que eu criei isso. Mantenha a mesma distância.}
{3003}{}{Preciso que tire a armadura que você está vestindo.}
{3004}{}{Que armas você é habilidoso com Myron? Qualquer?}
{3005}{}{Nunca perca, há outra coisa que eu precisava de você.}

{3025}{}{Tanto faz.}
