# QUICK LOOK

# EXAMINE
{150}{}{Você vê uma máquina caça-nítida feia e coberta de ferrugem.}
{151}{}{Você vê uma máquina caça-nítida de aparência feia. Está coberto de ferrugem e está abatido em vários lugares, como se tivesse atingido
 Repetidamente por um objeto pesado.}

# 1. FLOAT DIALOGUE (PLAYER = MALE, DRUNK OR HIGH) (WTG)
{200}{}{* Hey lá, youngst ... :: tosse :: :: tosse :: :: wheeze :: ... venha ... :: hack :: ... me toca por um segundo. *}
{201}{}{* Olá thar, youngst- :: tosse :: :: tosse :: *}
{202}{}{* Hey, jovem feller :: tose :: :: hack :: :: wheeze :: ... why ... :: hack :: ... doncha venha fazer uma aposta? *}
{203}{}{*Chocalho*}
{204}{}{* Clink *}
{205}{}{* Thwunk *}
{206}{}{* Ker-chunka-chunka *}
{207}{}{* Zzzztttt *}
{208}{}{* Ka-dink-thunk-snap *}
{209}{}{* Ka-chuuuunk-snap-creeeeeak *}
{210}{}{* Clunk *}
{211}{}{* Tink-tinkety-tink *}
{212}{}{* Silly efeito de som *}
{213}{}{* Hey, beaut ... :: tosse :: :: tosse :: :: wheeze :: ... venha ... :: hack :: ... me toca por um segundo. *}
{214}{}{* Olá thar, beauti- :: tosse :: :: tosse :: Dammit! *}
{215}{}{* Coloque um chip, puxe meu braço. Eu vou ser legal com você. Heh heh.*}
{216}{}{* Bem, você não é um belo lil '- :: tosse :: :: hack :: :: wheeze :: Por que ... :: hack :: ... doncha come play me? *}

# 4. RETARD (WTG)
{230}{}{Você vê uma estranha caixa de metal maçante com três olhos e um braço.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{235}{}{A estranha caixa de metal maçante com três olhos e um braço não responde.}

# 6.  RETARD PULLS HANDLE (4, 5)
{240}{}{Você agarra seu braço e agita calorosamente. Como você faz, há um som agudo!}

# PLAY. . . ? (WTG, 14, 15)
{245}{}{(Você vê uma máquina caça-níqueis. É talvez a máquina de fendas mais feia que você viu em New Reno. Seu identificador está dobrado, dois
 De suas janelas estão quebradas, e há dentes por toda parte.)}
{246}{}{Sua mão melhora quando você alcança suas fichas. (A máquina continua a sussurrar em você com sua voz grave).
 * Venha, agora ... :: tosse ... ... é isso ... *}

# LOOOOOOSER (8)
{250}{}{Há um ruído de estrangulamento no ouvido enquanto as câmaras giram, e ...}
{251}{}{NADA! (A máquina chora secamente.) * Melhor sorte da próxima vez, youngst - :: tosse :: :: tosse :: :: wheeze ::}

# WIN x1 (8)
{255}{}{(A máquina continua a sussurrar em você.) * Tente novamente, jovem ... uma vez mais para - :: tosse :: :: hack :: - sorte. *}

# WIN x2 (8)
{260}{}{Eventualmente, os tumblers chocam para parar de revelar ...}
{261}{}{(A máquina chove cordialmente.) * É isso, jovem. Eu sabia que você cou ... :: tosse :: :: tosse :: ... faça isso. *}

# WIN x3 (8)
{265}{}{(A máquina ri.) * É isso, whippersnapper! Eu sabia que ainda tinha ... :: wheeze :: ... moxy left! Heh heh!*}

# DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{270}{}{(Antes de você é talvez a máquina tragamoninha mais feia que você já viu. Ao olhar sua feiúra em fascínio mórbido,
 De repente, uma voz machucada masculina sussurra do slot da moeda.) * Não é visto um jovem como você ao redor antes - :: tosse ::
 :: tosse :: Você está procurando ... :: hack :: :: wheeze :: ... ta aproveitar? *}

# DRUNK CONVERSATION 1 (13)
{275}{}{* Eu ainda estou aqui, jovem, * os trapaceiros da máquina caça-níqueis. * Olhe, venha agora ... y'wanta faz uma aposta? Eu não demoro esse mundo. *}

# DRUNK 2 (14)
{280}{}{* Eu sou o bandido mais antigo de Reno. Eu estive por perto perto de ... :: tosse :: :: tosse :: ... bem, praticamente perto de sempre. Começando com ta
 Mostre, desculpe, diga. Olha, você vai apostar ou eu vou sentar aqui n 'ferrugem? *}

# DRUNK 3 (15)
{285}{}{:: Tosse :: :: Tosse :: * Não tem TIME ta atire na merda com você, jovem. E você, com certeza, deve ter mais coisas importantes do que conversar comigo, hein? Somente sobre sua mente? *}

# DRUNK 4 (16)
{295}{}{* Fácil lá, jovem. Pare com eles raindrops agora. Tudo bem está bem, yh? Estou olhando para você, 'kay? *}

# DRUNK 5 (17)
{300}{}{* Ei agora, vamos, o suficiente disso. Dê uma volta, limpe sua cabeça ... :: tosse ... ... ajude-o a relaxar. Você acha que vai ficar bem,
 jovem?*}
{301}{}{Eu serei todo o rite ... thasnk fer conversando comigo, oul slot macheen}

# DRUNK 6 (18)
{305}{}{* Pah! Não é necessário obrigado, [X]. Agora, você vai lá e dê-lhes HELL. O único herói que recebemos neste mundo de dois bits
 De bastardos e ladrões ... :: tosse :: :: wheeze :: :: tosse :: ... então você tenha cuidado, ouça? *}
{306}{}{Shurr vai - você também, okayyy?}

# JACKPOT! (8)
{310}{}{(Ao puxar a alça dobrada, você acha que ouve a máquina dar um suspiro aliviado, seguido de um longo silêncio. Apenas quando
 Você está prestes a abandonar isso, você ouve algo chacoalhando do fundo da máquina. Poucos segundos depois, o chocalho cresce
 Para um rugido ensurdecedor quando as moedas começam a se empilhar em uma avalanche!) JACKPOT!}
{311}{}{Colecione ganhos!}

# AFTER JACKPOT (WTG)
{315}{}{(Esta máquina parece que finalmente desistiu do fantasma. Parece que pagar o jackpot foi o seu chocalho de morte.
 Você não pode deixar de sentir um pouco de pena por isso.)}

# skill use
{320}{}{Esta máquina é antiga. É um milagre que ainda está funcionando.}
{321}{}{Você não pode trabalhar na máquina enquanto o velho está jogando.}
{322}{}{Esta máquina está fora de reparação.}
{323}{}{Não há nada mais que você possa fazer com esta máquina.}
{324}{}{Esta máquina é antiga. É um milagre que ainda está funcionando. You tinker with it for a bit until you hear a terrible
 grinding noise. You suddenly decide to leave it be.}
{325}{}{Esta máquina é antiga. É um milagre que ainda está funcionando. You tinker with it for a bit, but you can't seem to fix it.}
{326}{}{Esta máquina é antiga. É um milagre que ainda está funcionando. You tinker with it for a while and clean some of the
 gears, but it's still in sorry shape.}
