# 0.  LOOK, CLOSED (WTG)
{100}{}{Você vê uma combinação segura definida de forma segura na parede. Está fechado.}

# 1.  LOOK, OPEN (WTG)
{101}{}{Você vê uma combinação segura definida de forma segura na parede. Está aberto.}

# LOCKPICKING
# trapped
{120}{}{Assim como você está prestes a começar a bloquear o cofre, você percebe que um fusível está funcionando
 Na parede logo abaixo do cofre. Parece que esse otário está preso.}
{121}{}{O cofre ainda está preso.}

# successfull unlock
{150}{}{Existe um KER-KLANK como desbloqueio seguro.}

# lucky unlock
{160}{}{Você está girando o mostrador aleatoriamente, quando de repente o disco trava em um número ...
 Há um KER-KLANK e os desbloqueios seguros.}

# failed unlocks
{170}{}{Você gira o disco lentamente por vários minutos, mas você não consegue resolver nada.}
{171}{}{Você gira o mostrador por vários minutos, e nada acontece.}

# TRAPS
# disarm
{180}{}{Você encontra uma armadilha segura e desarmá-la com êxito.}
{181}{}{Você desarma com sucesso a armadilha no cofre.}

# find trap
{190}{}{Você encontra uma armadilha no cofre, mas não consegue desarmá-la.}

# fail
{200}{}{Não parece que haja uma armadilha no cofre.}
{201}{}{Você não consegue desarmar a armadilha no cofre.}

# fail critical

# CHANGING COMBO ON SAFE
# trap needs re-arming
{220}{}{Provavelmente seria melhor re-armar o cofre com explosivos plásticos ou dinamite primeiro.}

# changed combination
{230}{}{A combinação no cofre foi alterada com sucesso ... heh heh heh ...}
{231}{}{A combinação no cofre foi alterada com sucesso ... novamente.}

# no skills
{240}{}{Você não tem as habilidades para alterar a combinação.}
{241}{}{ Não tem habilidades para mudar a combinação.}

# it's open
{250}{}{O seguro precisa ser fechado.}

# REARMING TRAP
{260}{}{Parece haver uma armadilha já no cofre.}

{270}{}{Você não conseguiu prender o cofre.}
{271}{}{ Não conserta o cofre.}

{280}{}{A armadilha no cofre foi rearmada com sucesso.}

# trap_boom
{300}{}{Você ouve um boom abafado no andar de cima.}

{400}{}{Você puxa um pequeno painel no fundo do cofre. Você não acha que o teria encontrado
 Se a Sra. Bishop não tivesse contado sobre isso. O lado de dentro é um acessório de pip boy de aparência estranha.}

# critical fail
{290}{}{Ao procurar o cofre para uma armadilha, você desencadeou uma explosão.}
{291}{}{Você puxou o fio errado enquanto desarmava a armadilha.}
