{100}{}{Eu estacionei meu carro aqui mesmo!}
{150}{}{À medida que você passa mais perto de onde o carro estava estacionado, você percebe que as fracas marcas de derrapagem
 levando para o norte.}
{151}{}{Você vê marcas de deslizamento que levam para o norte.}
{152}{}{Você vê trilhas de carros!}
{153}{}{(Siga trax!)}
{154}{}{(Não segue trax.)}
{155}{}{(Siga as faixas do carro).}
{156}{}{(Ignore-os.)}
