{100}{}{Você vê uma morte. Ele o observa com olhos estranhamente inteligentes.}
{101}{}{Você vê Dar, o deathclaw.}
{102}{}{Você vê uma lei de morte típica. A criatura é enorme, com um corpo poderoso, dentes afiados e longos
 garras.}
{103}{}{Olá, humano.}
{104}{}{O que você quer?}
{105}{}{Oi. Quem você?}
{106}{}{Porque estás aqui?}
{107}{}{Você é inteligente como o resto?}
{108}{}{Estou entediado, eu vou.}
{109}{}{Desculpe incomodá-lo, mas quem é você?}
{110}{}{Qual é o seu trabalho no cofre?}
{111}{}{Por favor, não se ofenda, mas como você é educado?}
{112}{}{Bem, apenas passando o tempo.}
{113}{}{Eu Dar, guerreiro.}
{114}{}{Está bem.}
{115}{}{Você é o mesmo. Eu vou embora.}
{116}{}{Eu} #continue 137
{117}{}{Entendo. Bem, eu tenho que ir agora.}
{118}{}{Eu estou} #continue 138
{119}{}{Consegui.}
{120}{}{Guerreiro! Ha! Essa é boa. Saiba mais?}
{121}{}{Dar Guard Hall e manter a paz. Nada mais.}
{122}{}{Eu hear before.}
{123}{}{Está bem.}
{124}{}{Bem, você está bem, Dar. Apenas continue assim.}
{125}{}{Sim, eu pensei tanto.}
{126}{}{Nada novo aqui. Eu quess eu irei.}
{127}{}{Com um rosto como o seu, como você pode manter a paz?}
{128}{}{Você não é legal. Vá embora.}
{129}{}{Não muito, mas eu aprendo. Gruthar - ele líder - conte-nos todos aprender.}
{130}{}{Elder na aldeia me faz mesmo.}
{131}{}{Ah.}
{132}{}{Gruthar está certo; Vocês devem tentar educar-se.}
{133}{}{Consegui.}
{134}{}{Então, você é tão estúpido que outra pessoa tem que forçá-lo a educar-se. Quão legal.}
{135}{}{Olá. Você embala amigo.}
{136}{}{Grrrrrrrrr! Argggggghhhh.}

{137}{}{.}
{138}{}{, Dar.}
