{100}{}{Você vê um homem triste e mais velho.}
{101}{}{Você vê Dave, "Sr. Depressão".}
{102}{}{Você vê um homem mal-humorado e mais velho em seus anos sessenta. Ele tem um rosto resistido e parece que ele
 teve sua justa parcela de abuso.}
{103}{}{Oh. Eu não vi você parado ali.}
{104}{}{Como não vê? Eu grande.}
{105}{}{Parece triste. Por quê?}
{106}{}{Eu vou adeus.}
{107}{}{Está tudo bem, todos nós ficamos espaçosos às vezes. Diga, você parece mais baixo. Posso perguntar por que?}
{108}{}{Tanto faz. Por que você está tão baixo?}
{109}{}{Devo pressioná-lo com uma placa para chamar sua atenção na próxima vez?}
{110}{}{Tanto faz. Acabei de me lembrar de algum lugar que eu deveria estar.}
{111}{}{Ei, a merda acontece - e quando isso acontece, acontece comigo.}
{112}{}{Uh ... eu vou embora agora.}
{113}{}{Como o quê?}
{114}{}{Atitude agradável. O que causou isso?}
{115}{}{Posso dizer que quero estar em outro lugar.}
{116}{}{Nasci dois meses prematuro. Quando eu era um, eu fui caído na varanda. Quando eu tinha dois anos, eu
 tinha pneumonia. Quando eu tinha três anos, peguei a varíola. Quando eu tinha quatro anos, caí nas escadas e quebrei
 seis costelas. Quando eu tinha cinco anos, meu tio foi decapitado por uma melancia. Quando eu tinha seis anos, meus pais me atingiram
 na cabeça com uma pá. Quando eu tinha sete anos, perdi meu dedo indicador direito para o meu rato de estimação.}
{117}{}{Uh, eu ouço alguém ligar. Tchau!}
{118}{}{Desculpe coisas ruins.}
{119}{}{Passado mal, sem conversa. Coisas boas agora?}
{120}{}{Uau! Tenho certeza de que não sou você!}
{121}{}{Ok, eu entendo a foto. O que está incomodando você?}
{122}{}{Sinto muito por ter tido muita dor na sua vida. Espero que as coisas tenham melhorado?}
{123}{}{Espere um minuto. Esqueci que tenho outra coisa a fazer agora.}
{124}{}{Sim, bem, a merda acontece - e quando isso acontece, acontece comigo.}
{125}{}{O que acontece agora?}
{126}{}{Eu ouvi antes. Tchau.}
{127}{}{Então, o que está acontecendo agora para te chatear tanto?}
{128}{}{Eu realmente não quero ouvir isso. Acho que vou sair.}
{129}{}{Bem, lá estava eu, viajando pelo deserto, quando de repente meu brahmin cai morto. Sobre
 então eu percebi que estava com pouca água e não tomava uma bebida em um bom tempo. Mais tarde, meus ossos começaram a
 dor, minha cabeça começou a doer, meus intestinos ficaram soltos, e eu recebi essa erupção cutânea que simplesmente não iria embora.
 Era hora de sentar e morrer.}
{130}{}{Eu ... você ... você ... Você não tem esposa ou filho?}
{131}{}{Você não fala mais nada. Eu vou.}
{132}{}{Eu não quero mais ouvir. Eu tenho que sair daqui e longe de você. Tchau.}
{133}{}{Diga-me que você não tem filhos.}
{134}{}{Não. Quando tornei vinte e dois, esse estranho fungo começou a crescer no meu teste ...}
{135}{}{Arrg! Você não fala mais! Eu vou!}
{136}{}{Pare! Eu não quero saber!}
{137}{}{Oh. Oi. O que posso fazer para você?}
{138}{}{Uh, o que você história de novo?}
{139}{}{Desculpe, eu vou.}
{140}{}{Eu estava pensando se eu poderia ouvir sua história mais uma vez?}
{141}{}{Aguarde um minuto, pensei que você fosse outra pessoa.}
{142}{}{Por fim, chegou a minha hora. Você vai me matar agora?}
{143}{}{Sim.}
{144}{}{Não.}


{145}{}{Quando eu tinha oito anos, meu cão Spike foi atingido por um trator. Quando eu tinha nove anos, minha mãe perdeu o braço para um
 brahmin rabioso. Quando eu tinha dez anos, minha irmã foi destruída por um maço de cachorros. Quando eu tinha onze anos, meu
 o avô se matou porque era feio. Quando eu tinha doze anos, minha avó se matou porque
 Eu era feio. Quando eu tinha treze anos, meu pai esboçou os olhos com uma forca em um estupor bêbado.}
{146}{}{Quando eu tinha quatorze anos, meu irmão perdeu a mão para um Wallaby. Quando eu tinha quinze anos, minha tia sufocou
 morte em um osso de frango. Quando eu tinha dezesseis anos, perdi meu primo para um texugo. Quando eu tinha dezessete anos, eu cortei
 fora da minha mão esquerda com uma enxada. Quando eu tinha dezoito anos, meu pai perdeu sua perna direita para o mesmo trator
 Isso matou meu cachorro. Quando eu tinha dezenove anos ...}

{147}{}{Bem, lá eu estava sentada no deserto, esperando que o mundo engolisse minha existência miserável,
 quando aparece uma série de mortandras. Bem, estou pensando para mim mesmo, é isso. Agora eu posso morrer. Posso acabar
 como uma pilha de cunhas mortíferas no meio do deserto. Mas não ... o destino tinha outro cruel
 cartão para jogar contra mim.}
{148}{}{Você vê, os ciclos da morte não me mataram. Em vez disso, eles me deram água, me trouxeram aqui, me deram
 este quarto, me deu comida, me limpou e agora não me deixaram sair. Eu sei que eles estão engordando-me
 para algum destino desconhecido e horrível. Eu continuo dizendo-lhes que provavelmente gosto melhor se eu fosse
 mais enxuta, mas não é bom. Eles simplesmente sorriem - se você pode chamar isso - e me acaricie na cabeça e
 diga "Não se preocupe, humano, as coisas vão melhorar". Ha! Nós dois sabemos o que isso significa.}
{149}{}{De qualquer forma, para piorar as coisas, eles começaram a me dar algum tipo de medicação. isso foi
 tornando-me jazi, então eu parei de levá-lo - e é uma coisa boa que eu fiz. Eu acho que foi uma espécie de
 Pílula de "controle mental", porque eu comecei a sentir que as coisas não eram tão ruins quanto eu pensava!
 De qualquer forma, é sobre isso. Estou esperando que o sino do jantar toque, para que eles possam se deleitar com o meu
 corpo inchado.}
