{100}{}{Você vê uma jovem mulher em armadura metálica.}
{101}{}{Você vê Dalia.}
{102}{}{Você vê uma mulher muito jovem vestida com armadura metálica. Ela vê seus ambientes muito
 cuidadosamente.}
{103}{}{Bem, eu serei. Como vai você,} #continue to 153
{104}{}{Você Dalia. Eu lembro de você ajudar.}
{105}{}{As coisas estão bem. Eu vou agora.}
{106}{}{Dalia! Graças a você, tudo funcionou bem.}
{107}{}{As coisas estão bem, mas eu tenho que ir.}
{108}{}{Ei, estou feliz em ouvir isso. Foi um prazer fazer o que pude para você. Então, o que posso ajudar?
 você com?}
{109}{}{Eu tenho perguntas.}
{110}{}{Nada. Eu disse oi.}
{111}{}{Eu tenho algumas perguntas para você.}
{112}{}{Nada. Mas é bom ver você de novo. Tchau.}
{113}{}{O que você quer saber?}
{114}{}{Você é prisioneiro.}
{115}{}{Você sai quando quer?}
{116}{}{O que sabe sobre D'garra?}
{117}{}{Como você está aqui?}
{118}{}{Por que você se preocupa com segurança?}
{119}{}{Obrigado. Eu vou.}
{120}{}{Você é um prisioneiro aqui?}
{121}{}{Você pode sair sempre que quiser?}
{122}{}{O que você pode me falar sobre os cânceres da morte?}
{123}{}{Como você veio para estar aqui?}
{124}{}{Por que você está preocupado com a necessidade de um lugar de segurança?}
{125}{}{Obrigado. Eu falarei com você mais tarde.}
{126}{}{Não, eu não sou. Estou aqui de minha própria vontade e eu gosto disso. Penso que este será um lugar seguro para
 Eu vou ficar por um tempo.}
{127}{}{OK.}
{128}{}{Tchau.}
{129}{}{Tudo certo.}
{130}{}{Entendo. Bem, eu irei então.}
{131}{}{Sim, foi-me dito que estou livre para ir ou ficar. Eu vou ficar por agora.}
{132}{}{Eu vejo.}
{133}{}{Está bem então.}
{134}{}{Eu não sei mais sobre eles do que você, eu acho. Ainda estou tentando me acostumar
 Eles falando comigo em vez de rasgar minha cabeça e usá-la para uma bola de golfe. É assustador, você sabe?}
{135}{}{Sim, eu me incomodou.}
{136}{}{Na, eu costumava fazer isso.}
{137}{}{Sim, é de muitas maneiras.}
{138}{}{Não, eu venho aceitá-lo.}
{139}{}{Depois que eu deixei o Squat, não sabia o que fazer comigo mesmo. Eu pensei que eu apenas entraria em
 Outra cidade e outro trabalho de arma contratada ... então eu estava vagando pelo deserto tentando decidir exatamente onde
 Eu devo ir. Bem, um dia eu estava procurando por um bom lugar para acampar. Estava ficando tarde, e não fiz
 Quer sair ao ar livre depois do escuro. Fora na distância de um jeito, pensei que vi uma fogueira - então eu
 Decidiu ver quem estava lá.}
{140}{}{Uau.}
{141}{}{Isso é interessante.}
{142}{}{Quando eu deixo você por mim no Squat, quebrei meu contrato com meu empregador. Eu tinha certeza de que eu seria
 Caçou e morreu por causa disso. Vendo você aqui me convence de que não tenho que me preocupar
 aquele. Só posso assumir que meu empregador anterior não está mais em condições de se preocupar comigo
 Ou o meu paradeiro.}
{143}{}{Você está seguro agora. Dalia, não se preocupe.}
{144}{}{Você está seguro agora, Dalia. Você não terá que se preocupar com qualquer retribuição.}
{145}{}{Obrigado,} # continue 155
{146}{}{Bem vindo.}
{147}{}{Tchau.}
{148}{}{Seja bem-vindo.}
{149}{}{Eu vou te ver.}
{150}{}{Olá.}
{151}{}{Olá de novo. Como tá indo?}
{152}{}{Não tenho discussão contigo.}

{153}{}{. Espero que tudo aconteceu com você no Squat.}
{154}{}{Então, eu esgueirar-se neste campo de acampamento e há estes dois deathclaws sentados ao redor do fogo apenas
 Conversando. Idiota que eu sou, soltei um pequeno grito de surpresa, saltei e girei para correr - certo
 Nos braços de outra lei da morte, logo atrás de mim. De qualquer forma, para fazer uma longa história curta,
 Demorou um pouco para que eu percebesse que eu não estava prestes a ser posto em um cuspo e assado. Em vez disso, eu estava
 Trazido aqui e "entrevistado" por Gruthar. Agora eu posso viver aqui se quiser.}
{155}{}{. Isso tira uma carga da minha mente.}
