{100}{}{Você vê um homem magro com roupas longas. Ele parece estar no pensamento profundo.}
{101}{}{Você vê o Guardião do Santuário.}
{102}{}{Você vê um homem magro com roupas longas. Ele já está nos finais dos anos quarenta, e seus traços são suaves e
 sem compensação. Ele parece estar meditando.}
{103}{}{Bem-vindo, viajante. Eu sou chamado Gordon, e eu sou o Guardião do Santuário. Com o que posso ajudar?}
{104}{}{Santuário?}
{105}{}{Eu faz perguntas?}
{106}{}{Uh ... não lembro. Tchau.}
{107}{}{É um prazer conhecê-lo, Gordon. Eu estou} # continued 177
{108}{}{Você chama isso de santuário? Quem é dedicado deve estar virando sua sepultura!}
{109}{}{Bem, desculpe por ter perturbado você. Eu irei agora.}
{110}{}{Sim. Um santuário é um lugar de culto que geralmente é dedicado a um deus, um santo ou outro ser
 de poder.}
{111}{}{Ah. Ok. Eu faz perguntas?}
{112}{}{ESTÁ BEM. Tchau.}
{113}{}{Certamente você pode.}
{114}{}{O que você gostaria de saber?}
{115}{}{Para quem é o santuário?}
{116}{}{Quanto tempo você está aqui?}
{117}{}{D'garra mau?}
{118}{}{Por que você fica?}
{119}{}{Eu vou agora.}
{120}{}{Para quem é dedicado este santuário?}
{121}{}{À Quanto tempo você esteve aqui?}
{122}{}{O que você pode me falar sobre os cânceres da morte?}
{123}{}{Por que você fica aqui?}
{124}{}{Obrigado, Gordon. Adeus.}
{125}{}{Este santuário é dedicado a um herói sem nome conhecido apenas como o Vault Dweller. Ele, ou ela, era o
 salvador de todos os que viviam aqui há várias décadas. Nós não sabemos o que veio do nosso salvador, mas ele, ou
 ela vive em nossas mentes e corações.}
{126}{}{Que legal.}
{127}{}{Eu obrigado. Ondulado.}
{128}{}{Que piada! Um santuário para alguém que você nem pode lembrar!}
{129}{}{Entendo. Bem, eu tenho outras perguntas.}
{130}{}{Muito comendável, Gordon. Posso fazer mais algumas perguntas?}
{131}{}{Eu vivi toda a minha vida aqui neste cofre. Eu fui um Guardião do Santuário para a maioria desses
 anos.}
{132}{}{Você está aqui antes de D'garra?}
{133}{}{Ah. Precisa saber mais.}
{134}{}{Veio agora.}
{135}{}{Você é um homem muito dedicado. Posso fazer mais algumas perguntas?}
{136}{}{Isso é muito longo. Você pode responder algumas perguntas mais?}
{137}{}{É sua vida desperdiçada, como você vê, brote.}
{138}{}{Então você estava aqui quando os mortéis foram assumidos?}
{139}{}{Não, meu amigo, eu não estava. Eu deixei alguns meses atrás para visitar a estátua do morador da abóbada
 erguido no tribunal central da NCR (a Nova República da Califórnia a leste daqui). Quando voltei para
 o cofre, eu achei que os mortos foram já aqui. Escusado será dizer que eu estava com choque. No entanto, eu sou
 convencido de que eles não são responsáveis   pelo que aconteceu com os meus concidadãos. Se, por acaso, você
 Quer mais informações sobre este assunto, você pode procurar Goris na biblioteca.}
{140}{}{Ok, obrigado.}
{141}{}{Tudo bem tchau.}
{142}{}{Eu vou manter isso em mente.}
{143}{}{Eu não preciso de você me dizer para onde ir ou quem ver.}
{144}{}{Obrigado pela ajuda. Tenho ainda mais perguntas.}
{145}{}{Eu vivi com os códigos da morte por vários meses agora. Parecem ser honrados e
 direto nos seus tratos comigo e com os outros humanos que vivem aqui. Confio neles e, com o tempo, eu
 acho que você também.}
{146}{}{Uh ... Ok.}
{147}{}{Humph. Eu vou agora.}
{148}{}{Estou disposto a dar-lhes o benefício da dúvida por agora.}
{149}{}{Você pode confiar nos lagartos se quiser, mas vou reservar a minha opinião por enquanto, obrigado.}
{150}{}{Obrigado. Eu preciso saber mais.}
{151}{}{Meu lugar está aqui no Santuário. Não vou deixá-lo de bom grado.}
{152}{}{Ah.}
{153}{}{Eu deixo você agora.}
{154}{}{ESTÁ BEM.}
{155}{}{Você é dedicado ou um idiota. Eu voto para idiota!}
{156}{}{Sua dedicação é admirável.}
{157}{}{Você é um indivíduo grosseiro e verbalmente abusivo. Talvez se um dos guardas estivesse presente com
 nós, você abraçaria sua língua.}
{158}{}{Eu avisei você anteriormente que eu não toleraria seu abuso. Obviamente, você escolheu ignorar
 esse aviso. (Gordon olha para a porta) Guardas! Para o Santuário, por favor!}
{159}{}{Então você ainda escolhe ser um burro. (Movimentos de Gordon em direção ao guarda da morte) Guarda, pegue
 o lixo.}
{160}{}{Traga seu stooge! Posso chutar ambos os seus jumentos em um piscar de olhos.}
{161}{}{Desculpe, vou segurar minha língua.}
{162}{}{Minhas desculpas para você, Gordon. Por favor, perdoe minha explosão.}
{163}{}{Eu sinto Muito. Eu me esqueci. Por favor me perdoe.}
{164}{}{Ooops, desculpe.}
{165}{}{Eu estava ansioso para fazer algum plinking de lagarto!}
{166}{}{Guardas! Para o Santuário!}
{167}{}{}
{168}{}{}
{169}{}{Então, você retornou. Bem, eu tinha removido uma vez e eu posso ter removido novamente. Guardas! Para
 o Santuário! O lixo está de volta!}
{170}{}{}
{171}{}{}
{172}{}{Olá de novo. O que posso fazer para você?}
{173}{}{Fazer uma pergunta?}
{174}{}{Eu já estive aqui? Desculpa. Chegou.}
{175}{}{Eu queria conversar com você mais uma vez.}
{176}{}{Apenas dizendo olá.}

{177}{}{. Posso fazer-te algumas perguntas?}
