{100}{}{Você vê uma figura vestida.}
{101}{}{Você vê Goris o erudito.}
{102}{}{Você vê uma figura humanoide vestindo um manto de manga comprida e com capuz.Há algo não natural
 Sobre sua postura, mas você não tem certeza exatamente o que é isso.}
{103}{}{Olá, sou Goris.Eu não reconheço você; você é novo aqui?}
{104}{}{Eu} # 213
{105}{}{Eu go.}
{106}{}{Sim, e daí?}
{107}{}{Oi.Eu estou} # 214
{108}{}{Olá, Goris.Gruthar disse que eu deveria te procurar.Ele parece pensar que você é o homem com o
 Respostas.}
{109}{}{Posso fazer-te algumas perguntas?}
{110}{}{Desculpe, tenho que ir.}
{111}{}{É um prazer conhecer você,} # 215
{112}{}{Então você conversou com Gruthar.Ele tem uma opinião bastante infla de mim.Eu realmente não sei metade
 Tanto quanto ele pensa que eu faço.De qualquer forma...}
{113}{}{Então você é um estranho! Vi alguns como você; Alguns ficam aqui no cofre, mas você
 parece diferente.Você parece ser mais "temperado", se você sabe o que quero dizer.Aposto que você esteve por aí
 Um pouco e coisas bem sucedidas.Estou certo?}
{114}{}{Uh ...'temperado'?}
{115}{}{Eu go.}
{116}{}{Desculpe, mas acho que vou sair.}
{117}{}{Sim, tive algumas aventuras.Diga, se você não se importasse de responder algumas perguntas para mim, eu
 Poderia lhe contar algumas das minhas aventuras em troca.}
{118}{}{Não é da sua conta.}
{119}{}{Lembre-se de fazer algumas perguntas?}
{120}{}{É um acordo! Eu adoraria ouvir qualquer coisa que você puder me dizer.}
{121}{}{Além disso, não posso recusar um amigo de Gruthar.}
{122}{}{O que você gostaria de saber.}
{123}{}{O que você está fazendo aqui?}
{124}{}{Você é um prisioneiro aqui?}
{125}{}{À Quanto tempo você esteve aqui?}
{126}{}{O que você pode me falar sobre os cânceres da morte aqui?}
{127}{}{Você sabe o que aconteceu com as pessoas que costumavam morar aqui no cofre?}
{128}{}{O que você pode me falar sobre Gruthar?}
{129}{}{Você acha que os cânceres da morte são uma ameaça para os seres humanos?}
{130}{}{Você tem alguma informação sobre este Enclave de onde você falou?}
{131}{}{O que você sabe sobre esse vírus?}
{132}{}{Você mencionou que queria fazer algumas viagens.Que tal se juntar a mim?}
{133}{}{Desculpe, mas tenho que ir agora.}
{134}{}{Hmm ...Estou surpreso Gruthar não falou sobre mim.Ah bem.}
{135}{}{Eu sou uma espécie de estudante.Estou tentando aprender o máximo que posso sobre o mundo e os diferentes
 Culturas que se desenvolveram.Agora estou estudando a cultura que os deathclaws estão se formando e
 Comparando-o ao desenvolvimento humano em linhas semelhantes.Comprei quase todas as informações que eu
 Preciso aqui.Isso ajudaria minha pesquisa um ótimo negócio se eu pudesse fazer algumas viagens.No entanto, não quero
 Para ir sozinho, se você sabe o que quero dizer.}
{136}{}{Interessante.Posso fazer mais algumas perguntas?}
{137}{}{Então, você é um erudito.Isso é uma grande conquista no mundo de hoje.}
{138}{}{Que aborrecido.Oh, bem ...é a sua vida a perder o que quiser.Eu ainda preciso de mais informações.}
{139}{}{Não, posso deixar sempre que eu gosto.Não o fiz porque não quero viajar sozinho.Eu estou
 Muito difícil e pode cuidar de mim mesmo, mas eu ainda serei uma pessoa sozinha no deserto, se
 Aconteceu alguma coisa.}
{140}{}{Entendo.}
{141}{}{Ah, muito de um covarde para fazer isso sozinho.Entendi.}
{142}{}{Eu também não gosto de viajar sozinho, então não posso culpá-lo.}
{143}{}{Uh ...alguns meses na verdade.Eu vim aqui da costa um tempo atrás.}
{144}{}{Uau, você é muito novo aqui mesmo.Se você não se importa, eu preciso saber mais.}
{145}{}{Você não aguardou essa resposta.Tenho cuidado em me contar mais?}
{146}{}{Entendo.I need to ask a couple more questions.}
{147}{}{Estes não são os seus mortes médias, como tenho certeza de que você percebeu.Eles tiveram sua inteligência
 Melhorado por algum meio, não entendido por eles.Foi feito por um grupo de humanos conhecido como 'The
 Enclave.' Parece que este Enclave precisava de um exército e eles escolheram os códigos da morte por causa de sua ferocidade,
 Proeza física, e ...bem, você começa a foto.De qualquer forma, o único fato faltando a morte foi
 Sua inteligência.Eles precisavam ser inteligentes o suficiente para entender comandos complexos, mas não tão inteligentes
 Que eles representariam uma ameaça para os "responsáveis".}
{148}{}{Isso soa como a maior quantidade de merda que já ouvi na minha vida!}
{149}{}{Isso é incrível.Você parece muito experiente.Posso pedir-lhe mais?}
{150}{}{Hmm OK.}
{151}{}{:: suspiro: :) Eles foram capturados pelo Enclave.Gruthar e o pacote foram forçados a ajudar em seus
 capturar.Eles não tinham escolha, pois eram escravos no momento.O destino dos humanos pesou
 Fortemente na mente de Gruthar.Ele nunca se perdoou por sua complicidade no caso.o
 Os humanos foram levados vivos, mas quem sabe o que aconteceu com eles desde então?}
{152}{}{(Suspiro) Eles foram capturados por um grupo chamado 'The Enclave'.Gruthar e o pacote foram forçados a
 Ajuda na sua captura.Eles não tinham escolha, pois eram escravos no momento.O destino dos humanos tem
 Pesava pesadamente sobre a mente de Gruthar.Ele nunca se perdoou por sua cumplicidade no
 caso.Os seres humanos foram levados vivos, mas quem sabe o que aconteceu com eles desde então.}
{153}{}{Hmm ...Preciso fazer mais algumas perguntas.}
{154}{}{Eu sabia que os malditos deathclaws eram responsáveis   de alguma forma! Eu ainda preciso de mais informações.}
{155}{}{Às vezes, somos forçados a fazer coisas desagradáveis   por situações fora do nosso controle.
 Gruthar deveria aprender a se perdoar.}
{156}{}{Gruthar não é o monstro que ele parece ser.Ele realmente se preocupa com todos nós aqui, e
 Está fazendo tudo o que pode para garantir nossa segurança e sobrevivência.Todos nós confiamos nele com nossas vidas.Eu
 Não sei o que mais posso dizer sobre ele.Você teria que conhecê-lo e julgar por si mesmo.}
{157}{}{Não tomarei decisões sobre ele.Ele merece melhor.}
{158}{}{Certo.Vamos falar sobre outras coisas.}
{159}{}{Ele é um homem morto.Eu acho difícil acreditar que ele pode ter qualidades redentoras.}
{160}{}{Bem ...o potencial está lá, especialmente quando você leva em consideração sua nova inteligência.
 No entanto, não acho que Gruthar e seu pacote representem uma ameaça.Todos parecem respeitar a vida e
 Liberdade pessoal acima de tudo.Agora, não espero que você tome minha palavra sobre isso.Eu pediria que você
 Julgue por você mesmo.Há outros que vivem aqui, a quem você pode fazer suas perguntas.}
{161}{}{Apenas um idiota não conseguiu ver o potencial de ameaça desses mortíferos!}
{162}{}{Obrigado pelo conselho; Vou perguntar ao redor.Posso fazer mais algumas perguntas?}
{163}{}{Hmm ...Ok, e algumas perguntas mais?}
{164}{}{Não, apenas o que eu disse.Aguarde, há uma outra coisa.O Enclave mostrou interesse em algumas ruínas a oeste daqui.Por que, eu não sei.É sobre isso.}
{165}{}{Bem, todo um pouco de informação ajuda, e agradeço por você.}
{166}{}{Este é um assunto muito importante para mim e você me decepcionou!}
{167}{}{Entendo.}
{168}{}{Eu acho que é chamado de vírus FEV.O Enclave é, ou estava, fazendo uma pesquisa extensa sobre isso.Eu estou
 Desculpe, mas não sei mais nada.}
{169}{}{Tudo bem; Para outras coisas.}
{170}{}{Você deve se desculpar.Foi-me dito que você era uma fonte de conhecimento!}
{171}{}{Você foi muito útil, Goris.}
{172}{}{Eu mantive minha parte de nossa barganha e respondi todas as suas perguntas.Agora, que tal
 Histórias de aventura que você prometeu?}
{173}{}{Com alegria.É um prazer falar com você.}
{174}{}{Promessa?Que promessa?}
{175}{}{Sim claro.}
{176}{}{(Goris hesita e você tem a sensação de que você está sendo cuidadosamente examinado).Eu seria
 Honrado de se juntar a você!}
{177}{}{(Goris hesita e você sente que está sendo cuidadosamente examinado).Desculpe, mas eu
 Não pense que você e eu compartilhamos os mesmos ideais.Uma joint venture não seria do nosso melhor interesse.}
{178}{}{Ok, você perde.}
{179}{}{Compreendo.Talvez você reconsidere mais tarde.}
{180}{}{O que?Não sou bom o suficiente para sua empresa?Dane-se!}
{181}{}{Ok, eu entendo.}
{182}{}{Eu não tenho nada para dizer para voce.Não me incomode de novo.}
{183}{}{Eu pedi que não me incomodassem de novo.Talvez a violência seja o único idioma que você entende.}
{184}{}{}
{185}{}{Sim, você sabe, bem viajado ...experiente ...experiente ...Você não tem idéia do que sou
 Falando sobre você?}
{186}{}{Alimentos temperados, não eu.}
{187}{}{Eu go now.}
{188}{}{Uh huh.Well, your IQ may be smaller than your shoe size, but you obviously have something
 going for you to have survived in the world this long...Ok, let's try this.Eu want leave this place.
 Eu want travel with you.Ok?}
{189}{}{Uh hein.Bem, seu QI pode ser menor do que seu tamanho de sapato, mas você obviamente tem algo em ação
 Para que você tenha sobrevivido no mundo por muito tempo ...deve ser essa tendência média que posso sentir em você.Oh,
 bem.Adeus.}
{190}{}{Uh ...Ok.}
{191}{}{Eu go.}                                 1
{192}{}{Me desculpe, eu não pretendia entrar em seus assuntos particulares.}
{193}{}{Sim, bem, veja que você não faz isso de novo!}
{194}{}{Tanto faz.Eu preciso de algumas informações de você, no entanto.}
{195}{}{Me desculpe, Goris.Estou um pouco nervoso hoje.Queria lhe fazer algumas perguntas, se não se importasse.}
{196}{}{Você teve alguns momentos interessantes.Você é o material de que os heróis são feitos, e eu
 te invejo.Obrigado por me contar tudo.}
{197}{}{Bem ...você é uma missão para a carnificina, e acho que vou agora.Obrigado e tchau!}
{198}{}{De nada, Goris.}
{199}{}{Olá de novo.Estás bem?}
{200}{}{Você vem comigo?}
{201}{}{Uh...me lost.Eu go.}
{202}{}{Só pensei em parar e dizer olá.Te vejo mais tarde.}
{203}{}{Ei, estou à procura de um companheiro de viagem.Você faz isso?}
{204}{}{O que posso fazer para você,} # 216
{205}{}{Você é ruim! Por que não dizer?}
{206}{}{Você é um deathclaw?Existe uma razão pela qual você não mencionou isso?}
{207}{}{How do I put this...Bad thing you kill, no talk.Eu not tell you so you see me good thing.Not
 kill me.Okay me stay with you?}
{208}{}{Desculpe-me de te enganar, mas os humanos têm o hábito de matar as pernas à vista.eu senti
 Que seria da minha vantagem esconder minha identidade até que você pudesse ver por si mesmo que eu estou no seu
 Lado neste empreendimento.Se você quer que eu vá embora, eu farei isso.Mas prefiro ficar e ajudá-lo na sua
 busca.Quero mostrar que os humanos e os mortos podem trabalhar juntos como amigos e não como inimigos.}
{209}{}{Eu not like, you go.}
{210}{}{Ok, você fica.}
{211}{}{Me desculpe, mas não gosto de enganar.Você deve sair.}
{212}{}{Eu entendo por que você sentiu necessário esconder sua identidade.Eu acho que podemos trabalhar juntos, então
 Por favor fique - mas não me engane novamente, Goris.}

# the name usually precedes these lines
{213}{}{.Eu new here.}
{214}{}{.Sim, sou do lado de fora do cofre.}
{215}{}{.}
{216}{}{?}

{217}{}{Então, o Enclave começou a mexer com um vírus, ou alguma coisa assim, e injetou os mortéis
 com isso.Este vírus era conhecido por mutar seres humanos em algum tipo de seres super, então o Enclave queria
 Para ver o que isso faria para as leis da morte.Bem, o resultado foi uma raça de homens da morte tão inteligente que eles
 Podem ver que estavam destinados a escravidão.Então, eles ficaram tolos até conseguirem a liberdade deles.
 E estão aqui!}
{218}{}{Eu estou contra o ataque de qualquer deathclaw.}

{219}{}{De repente, sinto que meu pacote está com problemas.Lamento deixar você, mas devo verificar meus irmãos.}
{220}{}{OK.}
{221}{}{As câmeras de segurança registraram o que aconteceu.Você deve verificá-lo.}

{222}{}{Você vê uma lei de morte cinzenta.É o Goris.}
{223}{}{Você vê uma figura humanoide vestindo um manto de manga comprida e com capuz.É o Goris.}

#specific party messages
{1064}{}{Você fica perto.}
{1065}{}{Você não se afasta.}
{1066}{}{Você também está perto.Espalhar.}
{1073}{}{Fica perto de mim.}
{1074}{}{Não fique muito longe.}
{1075}{}{Devemos nos espalhar um pouco.}
{1001}{}{Você cura você mesmo.}
{1002}{}{Você espera aqui.Eu voltei e peguei.}
{1003}{}{Uh ...nenhuma arma agora.OK?}
{1167}{}{Eu think you need to move different.}
{1167}{}{Eu think you need to move different.}
{1008}{}{Você é D'garra?Por que você não conta?}
{1009}{}{Eu done.}
{1010}{}{Você deve se curar agora.}
{1011}{}{Preciso que você espere até eu voltar.}
{1012}{}{Certifique-se de que você não tem uma arma pronta, está bem?}
{1166}{}{Permite-nos mudar a distância entre nós.}
{1016}{}{Vamos.}
{1017}{}{Você é um deathclaw?Existe uma razão pela qual você não me mencionou isso antes?}
{1018}{}{É por enquanto.}
{1000}{}{Sim,}
{1156}{}{?}
{1019}{}{Estou curado e pronto para ir,}
{1020}{}{Estou quase completamente curada,}
{1021}{}{Eu estou principalmente curado, mas eu poderia usar alguma ajuda quando tivermos a chance,}
{1022}{}{Eu me curei o máximo que puder, mas ainda estou muito ferido,}
{1157}{}{.}
{1041}{}{Estarei esperando por você quando você voltar,}
{1060}{}{Eu faço o meu melhor para parecer discreto,}
{1079}{}{Eu ficarei o mais perto possível,}
{1078}{}{É por enquanto.}
{1098}{}{Vou me afastar um pouco e dar-lhe espaço para respirar,}
{1117}{}{Eu vou voltar e dar-lhe um espaço,}
{1136}{}{Eu sinto Muito,}
{1158}{}{, but you've got too many people with you now.I'll wait here until a position opens.}
{1159}{}{Eu acho que vou fazer melhor sozinho.}
{1160}{}{Você não é quem eu queira estar por perto. Estou indo embora.}
{1137}{}{I've learned a lot from our travels together.I'll gladly come with you, }
{1161}{}{Desejo vingar meus irmãos.}
{1162}{}{All right.Let's do it.}
{1163}{}{Talvez você deva fazer isso por conta própria.}
{1164}{}{Você matou direito.}
{1165}{}{Tu vais sozinho.}
