{100}{}{Você vê uma grande morte. A criatura é composta de músculos ondulantes, dentes afiados e garras.}
{101}{}{Você vê Gruthar, líder dos mortéis.}
{102}{}{Você vê a morte mais impressionante que você poderia imaginar. A criatura deve ser única entre ela
 tipo.}
{103}{}{Não me tema, humano. Não pretendo prejudicar você. Eu sou Gruthar, líder deste pacote deathclaw.
 Por que você veio aqui?}
{104}{}{Por que você veio aqui?}
{105}{}{Uh ...}
{106}{}{Para chutar sua bunda!}
{107}{}{Como é possível que um deathclaw possa falar ... e tão bem?}
{108}{}{Quero saber o que aconteceu com as pessoas que já viveram aqui.}
{109}{}{Procuro algo chamado GECK. Foi-me dito que poderia encontrar um aqui.}
{110}{}{Foi-me pedido que elimine uma cova de mortos perigosa ...}
{111}{}{Estou investigando incursões nas fazendas locais brahmin. Você sabe algo sobre isso?}
{112}{}{Acho que vou sair agora.}
{113}{}{Você não é idiota, humana. Eu posso ver a verdade disso em seus olhos. Por favor, não tente enganar
 mim. Não tenho paciência para esses jogos.}
{114}{}{Muito bem. Se você deseja ser pensado como um idiota, então seja assim. Retorne para mim se você mudar
 sua mente.}
{115}{}{Me desculpe. Você parece ser intelectualmente desafiado. Você não é uma ameaça para mim ou para o pacote. Você
 são bem-vindos aqui, e pode considerar este lugar como um refúgio seguro do mundo exterior. Não prejudique ninguém, fique
 sem problemas, e você sempre será bem-vindo aqui.}
{116}{}{Me perdoe. Não pretendo ser rude, mas não vejo que isso seja relevante para nossa conversa.
 Posso falar sua língua, posso ler sua palavra escrita. O que mais precisa ser dito?}
{117}{}{Entendo.}
{118}{}{Não quero falar, mas com certeza você pode entender meu interesse nesse assunto.}
{119}{}{Sim, bem, que tal me deixar decidir o que é ou não é relevante?}
{120}{}{Sim, certamente posso. Muito bem. Se nos separarmos como amigos, humanos, você deveria falar com Goris. Ele
 tem mais compreensão sobre este assunto do que eu. Ele geralmente pode ser encontrado na biblioteca do vault.}
{121}{}{Obrigado. Estou ansioso para conhecer Goris.}
{122}{}{Não tenho a intenção de adicionar um código morto à minha lista de amigos. Tchau!}
{123}{}{Tudo certo.}
{124}{}{Eles se foram, humanos. Nós não os matamos e levamos sua casa. Não é nossa maneira de matar. Eu
 entenda que talvez você não acredite em mim, mas espero que você me julgue por minhas ações em sua direção e
 não por medo ou por preconceito.}
{125}{}{Ei, talvez você imagine que eu posso chutar sua bunda?}
{126}{}{Parece ser um ser honrado, Gruthar.}
{127}{}{Sim, suponho.}
{128}{}{Um geck. Isso não é um pequeno lagarto ... não, espere ... isso é um gecko. Me desculpe, mas não sei
 que geck é, nem onde pode ser encontrado.}
{129}{}{Sim, acredito que você tenha mencionado isso uma vez antes. Eu não sei o que é um geck, nem onde pode ser
 encontrado.}
{130}{}{Você vai me deixar procurar por isso?}
{131}{}{Ei, esse pequeno comentário de lagarto foi realmente engraçado. Que um parente seu?}
{132}{}{É óbvio que falar com você é uma perda de tempo. Adeus.}
{133}{}{Para ser sincero com você, não tenho certeza do que sou eu mesmo. Estaria tudo bem com você se
 Eu procurei por isso?}
{134}{}{Me desculpe, mas não permito que ninguém passeie por esses salões. Sou responsável pela
 segurança de todos os que vivem aqui e devo ter cuidado. No entanto, vou procurar este geck, e se eu
 descobri-lo, eu vou deixar você saber.}
{135}{}{Me desculpe, mas não permito que ninguém passeie por esses salões. Sou responsável pela
 segurança de todos os que vivem aqui e devo ter cuidado.}
{136}{}{Veja. Não é como se você fosse o lugar. Talvez eu veja se você gosta ou não!}
{137}{}{Eu entendo, Gruthar, e vou respeitar o seu desejo de privacidade.}
{138}{}{Eu posso entender sua preocupação. Você não me conhece bem o suficiente para confiar em mim. E se eu pudesse ajudar
 você de alguma forma, e, em troca, você me permite olhar ao redor?}
{139}{}{(Gruthar olha para você atentamente por um momento.) Você estaria interessado em nos ajudar? Sim eu
 sinta pouco mal em você. Muito bem, devo confiar em você.}
{140}{}{(Gruthar olha para você atentamente por um momento.) Eu acho que não. Eu posso sentir o mal em você, humano.
 Eu não posso arriscar as vidas daqueles que eu protejo fazendo uma chance com você.}
{141}{}{Obrigado.}
{142}{}{Bem. Acho que uma lobotomia de bala é uma solução viável para o meu problema.}
{143}{}{Desculpe-me sentir assim, Gruthar.}
{144}{}{Eu vou sair, então.}
{145}{}{Há muitas máquinas aqui, máquinas construídas por humanos. As mãos Deathclaw não podem usar estas
 máquinas. No entanto, existe uma máquina que entende perguntas. Peço-lhe para executar as outras máquinas
 e obedece. Esta máquina não mais escuta. Já não executará as outras máquinas. Nós estamos correndo
 fora da comida e da água. Eu ordenei incursões nas terras humanas para que possamos sobreviver. Eu não estou orgulhoso
 disto e eu acabaria com isso. Se você reparar esta máquina, eu poderei alimentar meu povo uma vez
 novamente. Com prazer, eu vou parar as invasões. Você concordará com isso?}
{146}{}{Desculpe, não tenho ideia de como consertar uma coisa dessas.}
{147}{}{Não sou técnico, mas posso tentar.}
{148}{}{Hmm ... parece que o módulo de reconhecimento de voz ficou ruim com você. Vamos dar uma olhada.}
{149}{}{Eu mudei de ideia. Eu vou ter que pensar sobre isso um pouco mais.}
{150}{}{Eu farei o que posso por você.}
{151}{}{Eu me recuso a ajudar os cânceres da morte.}
{152}{}{Obrigado. The machine is in the vault control center on the third level. If you can repair it,
 please do so. I am placing my trust in you. Please do not betray it.  You are welcome here.}
{153}{}{Não vou decepcioná-lo, Gruthar. Você tem minha palavra nisso.}
{154}{}{Obrigado. Eu irei sobre isso.}
{155}{}{Há realmente um nascido a cada minuto ...}
{156}{}{Entendo... Well, deathclaws are dangerous by nature and great care must be taken when encountering
 them in the wild. However, I am certain that you have noticed that we are an exception. My pack poses
 no threat to you or your human communities. We have evolved beyond our base cousins and wish simply to
 be left alone.}
{157}{}{Uh ... yeah.}
{158}{}{Seu intelecto aumentado poderia torná-lo ainda mais uma ameaça do que a mortalidade média,
 Gruthar.}
{159}{}{Posso ver que vocês não são os assassinos selvagens que os cânceres da morte são conhecidos por serem.}
{160}{}{Passei muitas noites sem dormir, pensadas profundamente, ponderando apenas essas questões. Eu finalmente
 chegar à conclusão de que os encargos e responsabilidades associados ao dom da inteligência
 são incontáveis. Existem apenas duas opções disponíveis para qualquer ser pensante. Ou aceite a vida como ela
 vem e faz o melhor para você e para os outros, ou simplesmente deixa de ser. Eu escolhi aceitar
 os desafios da vida. Se isso me faz uma ameaça para a humanidade, então eu tenho pena da mente pequena que encontra
 então ...}
{161}{}{Sim, bem ... Posso ter uma mente pequena, mas também tenho uma grande arma.}
{162}{}{Eu não poderia concordar mais com você. Eu não acho que você é uma ameaça, Gruthar.}
{163}{}{Uh ... yeah. What you said.}
{164}{}{(Gruthar faz uma pausa e parece estar considerando cuidadosamente sua resposta). Lamento dizer
 que eu ordenei as incursões nas terras humanas. Sou responsável pelas vidas de muitos aqui. Nós estamos
 ficando sem comida, água e outros suprimentos. Até que eu possa corrigir a situação, eu preciso tomar
 O que eu, uma morte, não pode pedir aos humanos.}
{165}{}{Bem, agora que eu conheço a fonte dos ataques, eu vou simplesmente eliminá-lo!}
{166}{}{Sinto muito por ouvir isso. Existe alguma maneira de poder ajudá-lo para que você possa parar
 as invasões?}
{167}{}{Já ouvi o suficiente por enquanto. Preciso de algum tempo para pensar.}
{168}{}{Entendo...}
{169}{}{Estou descontente com a sua decisão, mas aceito. Você pode sair, mas volte se você
 reconsiderar.}
{170}{}{Feito.}
{171}{}{Olá} // Goes to 231
{172}{}{Não. Vou chegar a ele, no entanto.}
{173}{}{Me desculpe, Gruthar. O módulo de voz ficou ruim. Eu vou ter que ir buscar um.}
{174}{}{Não entendo o funcionamento de tais coisas, mas confio em você,} // 232
{175}{}{Feito.}
{176}{}{Devo voltar, você tem minha palavra.}
{177}{}{Olá} // 233
{178}{}{Não, ainda estou olhando.}
{179}{}{Sim, e aqui está!}
{180}{}{}
{181}{}{Você restaurou minha fé nos seres humanos. Agradeço por tudo o que você fez pelo pacote. É
 há algo que eu possa fazer por você em troca?}
{182}{}{Você disse que me informaria se você encontrou um geck aqui. Você localizou um?}
{183}{}{Sim, estou procurando um geck. Foi-me dito que eu poderia encontrá-lo aqui. Você sabe onde?
 é?}
{184}{}{Não, obrigado. Tenho tudo o que preciso.}
{185}{}{Sim, havia um geck na sala de armazenamento do vault. É seu com muito obrigado.}
{186}{}{Sim, havia um geck na sala de armazenamento do vault. No entanto, está faltando. sinto muito
 que não posso dar a você como recompensa por toda sua generosa ajuda.}
{187}{}{Obrigado!}
{188}{}{Uh ... that's okay. I'll try to locate one elsewhere.}
{189}{}{Olá again, human. I hope that you do not intend to play the fool with me.}
{190}{}{Quero me desculpar e começar de novo, Gruthar.}
{191}{}{Desculpe, tenho que ir.}
{192}{}{Uh, desculpe-me.}
{193}{}{Saudações, humanas. Você reconsiderou? Você vai me ajudar?}
{194}{}{De jeito nenhum. Eu só queria ouvir você carnicer o idioma um pouco mais.}
{195}{}{Não, eu não penso assim.}
{196}{}{Sim, Gruthar. Vou te ajudar.}
{197}{}{Saudações amigo. Já examinou a máquina?}
{198}{}{Ainda não, mas vou entender.}
{199}{}{Olá, my friend. You have saved the pack and we thank you.}
{200}{}{}
{201}{}{}
{202}{}{Morra, humano traiçoeiro!}
{203}{}{}
{204}{}{}
{205}{}{Não discuto contigo, humano, e não quero um. Estou tentando lidar com você civilmente.
 Por favor, devolva o favor!}
{206}{}{Tudo bem, vamos conversar então.}
{207}{}{Você é um deathclaw e isso significa uma sentença de morte ... para você, isso é!}
{208}{}{Me desculpe, Gruthar. Vamos conversar.}
{209}{}{Tanto faz. estou fora}
{210}{}{Não. Eu sou líder aqui, então eu decidir. Se você não gosta disso, você pode retornar às suas terras humanas!}
{211}{}{Explique-me!}
{212}{}{OK, eu irei agora.}
{213}{}{Claro, Gruthar. Esqueci-me por um momento.}
{214}{}{Garanto-lhe que não estava tentando ser engraçado ou brincar com você. Por favor, desculpe se eu lhe dediquei
 Essa impressão. Eu o ajudaria se pudesse.}
{215}{}{Bem, obrigado.}
{216}{}{Me desculpe, não queria sair assim assim.}
{217}{}{Desista do ato civilizado, broto. Não funciona comigo.}
{218}{}{(Gruthar emite uma série gutural de rosnados) Eu não posso possuir este lugar, humano, mas é minha casa
 e o lar de outros que dependem de mim para sua proteção. Não me empurre para que nenhum dos dois
 Nós vamos nos arrepender!}
{219}{}{Eu sinto Muito; Fui imprudente e ultrapassou meus limites.}
{220}{}{Aperte você e todos que se parecem com você!}
{221}{}{Uau! Estou fora daqui.}
{222}{}{Obrigado. Please go to the control room and replace the module.}
{223}{}{Considere isso feito!}
{224}{}{}
{225}{}{Você não é bem-vindo aqui neste momento. Você pode sair.}
{226}{}{Adeus}
{227}{}{Adeus.}
{228}{}{Feito.}
{229}{}{Apologia aceita, humana. Tenha um bom dia!}
{230}{}{Feito.}
{231}{}{. Você examinou a máquina?}
{232}{}{. Vou aguardar o seu retorno.}
{233}{}{. Você encontrou a peça para consertar a máquina?}

#added later
{234}{}{Uh, está bem.}
{235}{}{Espero que você esteja gostando da sua estadia.}
{236}{}{Infelizmente, teve que chegar a isso. Eu permiti que ele permanecesse ileso enquanto não apresentasse nenhuma ameaça à matilha. Ele escolheu o caminho dele. Espero que entenda.}
{237}{}{Você é ruim.}
{238}{}{Eu entendo, Gruthar.}
{239}{}{Sim. Matt não é bom.}
