{100}{}{Você vê um homem alto e magro com óculos grossos.}
{101}{}{Você vê Jimmy.}
{102}{}{Você vê um homem alto e esguio com óculos grossos. Sua testa está enrugada em um pensamento profundo e ele fala para si mesmo enquanto ele vaga na sala.}
{103}{}{Oh, olá, lá. Eu sou Jim, ou Jimmy. O que é que?}
{104}{}{Eu olho em volta.}
{105}{}{Eu}
{106}{}{Uh... Eu wander about. Eu go now.}
{107}{}{Apenas olhando por aí.}
{108}{}{Oi, Jim. Eu estou}
{109}{}{Nada do seu negócio, quatro olhos. Recuar.}
{110}{}{Eu apenas ando por aí. Eu vou sair agora.}
{111}{}{Sinta-se à vontade para olhar tudo o que quiser, mas não toque nada. Há alguns equipamentos sensíveis aqui.}
{112}{}{Eu just look around. Eu no touch.}
{113}{}{Estou só dando uma olhada. Não vou incomodar nada.}
{114}{}{Você é irritante. Vá embora.}
{115}{}{Ei, desculpe. Não queria pisar os dedos dos pés. Vou deixá-lo para o seu negócio.}
{116}{}{Boa.}
{117}{}{É um prazer conhecer você,}
{118}{}{O que você gostaria de saber?}
{119}{}{O que você faz aqui?}
{120}{}{O que toda essa máquina?}
{121}{}{Vault tem supervisor. Esta sala de supervisores?}
{122}{}{Você está aqui no cofre porque você quer ser?}
{123}{}{O que você pensa sobre D'garra?}
{124}{}{Parte de necessidade do computador. Você sabe para onde?}
{125}{}{Eu know enough. Eu go now.}
{126}{}{O que você faz aqui?}
{127}{}{Para que serve essa maquinaria?}
{128}{}{Não é este o quarto do supervisor do cofre?}
{129}{}{Você está aqui no cofre porque quer ser?}
{130}{}{O que você acha sobre o deathclaws?}
{131}{}{O computador precisa de uma parte. Você sabe onde eu poderia conseguir?}
{132}{}{Acho que irei agora.}
{133}{}{Bem ... estamos tendo alguns problemas de computador e estou olhando para ele. Infelizmente, o meu forte é o software, e não o hardware.}
{134}{}{Que problema?}
{135}{}{Qual é o problema?}
{136}{}{Sim, Gruthar mencionou isso para mim e me pediu para dar uma olhada. Você se importa?}
{137}{}{A interface de voz para o mainframe falhou, portanto Gruthar não pode fornecer as instruções do sistema para executar o cofre. Os processadores de alimentos e água já fecharam. Os sistemas de energia poderiam muito bem ser o próximo.}
{138}{}{Por que você não usa keebored?}
{139}{}{Por que não apenas dar entrada de teclado?}
{140}{}{Bem, você vê, essa é a parte estranha. O sistema se recusa a aceitar a entrada do teclado. Estou sem prejuízo do que fazer neste momento.}
{141}{}{Ok, eu olho?}
{142}{}{Tenho muita gentileza de dar uma olhada nisso?}
{143}{}{Sim, Gruthar mencionou isso para mim e me pediu para dar uma olhada. Você se importa?}
{144}{}{Bem ... sem ofensa, mas você tem certeza de que está qualificado? Oh, não importa. Você não pode tornar as coisas mais pior do que elas já são. Vá em frente.}
{145}{}{Você não pode fazer as coisas pior do que já são. Vá em frente.}
{146}{}{Ok, mas eu pergunto mais algumas perguntas.}
{147}{}{Tudo bem, mas preciso primeiro fazer algumas coisas.}
{148}{}{Este é um sistema de computador mainframe e dispositivos de suporte relacionados. A partir daqui, todas as funções do vault são controladas remotamente.}
{149}{}{Uh ... o que você disse.}
{150}{}{Ah, eu vejo.}
{151}{}{Normalmente, o supervisor do vault seria estacionado aqui, mas o Vault 13 foi totalmente automatizado.}
{152}{}{Por quê?}
{153}{}{Ok, eu pergunto mais.}
{154}{}{Por quê? I mean, isn't that unusual?}
{155}{}{Entendo. Vamos mudar de assunto.}
{156}{}{Não conheço a história completa, mas em um ponto da história do cofre houve uma rebelião. O supervisor foi morto ou derrubado, não tenho certeza qual. De qualquer forma, os líderes da revolução não queriam confiar o destino das pessoas a outro supervisor, então eles instalaram esse mainframe. Os registros dizem que foi comprado de ... oh, qual era o nome ... Ah, eu lembro, a "Irmandade do Aço".}
{157}{}{Você fala sobre a Irmandade?}
{158}{}{Você pode me contar alguma coisa sobre essa Irmandade?}
{159}{}{Não, desculpe, mas não tenho informações sobre eles. Tudo isso aconteceu há muito tempo e nunca encontrei nenhuma referência a eles além desse. No entanto, entendo que a Irmandade era uma roupa militar e há algumas ruínas do que parece ser uma base militar a oeste de aqui. Pode ser o que resta deles.}
{160}{}{Ok. Eu ask other thing.}
{161}{}{Tudo certo. Deixe-me perguntar-lhe outras coisas então.}
{162}{}{Oh sim. Eu gostei aqui desde que eu tropecei no lugar e eu realmente não quero sair. Eu sempre fui um solitário e não me importo muito com as pessoas, sem intenção de ofensa.}
{163}{}{Eu take none.}
{164}{}{Nenhum tomado.}
{165}{}{Bem ... De certa forma eu os admiro pelo que são e o que eles estão tentando tornar-se. De outras maneiras, eles me deixam mal. Eu não acho que vou me acostumar com o fato de que eles são tão inteligentes quanto eu ... bem, alguns deles são tão inteligentes.}
{166}{}{Você acha que eles ameaçam as pessoas?}
{167}{}{Você acha que eles são uma ameaça para a sociedade humana?}
{168}{}{Oh, absolutamente. Eles são muito superiores a nós fisicamente e eles são nossos iguais mentalmente. Isso os torna uma grande ameaça. No entanto, tudo se resume à moral e à ética no final. Felizmente, eles parecem ser éticos e moralmente bem desenvolvidos.}
{169}{}{Eu see.}
{170}{}{Sim, vejo o que você quer dizer.}
{171}{}{Olá. É bom ver você novamente. Com o que posso ajudar?}
{172}{}{Precisa perguntar.}
{173}{}{Just say hi. Eu go.}
{174}{}{Eu preciso te perguntar uma coisa.}
{175}{}{Só dizendo Oi.}
{176}{}{Bem, vamos ver ... Suponho que o melhor lugar para olhar seria Vault City, pois eles são o lugar mais moderno que eu posso pensar. Você pode querer dar uma nova tentativa de Reno. Eles estão mais perto e eles fazem muitas negociações com a Vault City.}
{177}{}{Obrigado.}
{178}{}{Obrigado por consertar o computador. Você salvou todas as nossas pontas.}
{179}{}{Eu tenho coisas melhores para fazer do que disparar para você, mas todos precisam de férias!}

{180}{}{. Eu ask question?}
{181}{}{. Posso fazer-te algumas perguntas?}
{182}{}{. Eu ficaria feliz em responder algumas perguntas.}
{183}{}{Você deve deixar Gruthar saber que você reparou o computador.}
