{100}{}{Você vê um homem curto carregando um livro nas mãos dele.}
{101}{}{Você vê Joseph, o herbalist.}
{102}{}{Você vê um homem curto com um livro chamado "ervas e seus usos medicinais".}
{103}{}{Olá, sou Joseph o herbalist. Com o que posso ajudar?}
{104}{}{Tenho owie. Voce conserta?}
{105}{}{Sinta-se icky. Voce conserta?}
{106}{}{Eu gimp, você conserta?}
{107}{}{Tem perguntas. OK?}
{108}{}{Desculpe, eu vou.}
{109}{}{Estou ferido. Pode me ajudar?}
{110}{}{Me sinto mal. Pode me ajudar?}
{111}{}{Estou aleijado. Pode me ajudar?}
{112}{}{Queria fazer algumas perguntas.}
{113}{}{Apenas dizendo olá.}
{114}{}{Por que, certamente. Hmmm. Você precisará tomar parte disso. Vou aplicar este bálsamo à ferida.
 Agora, volte e descanse por algumas horas.}
{115}{}{Obrigada. Tchau.}
{116}{}{Obrigado, Doc. Eu me sinto muito melhor.}
{117}{}{Por que, certamente. Hmmm. Isso levará um tempo, então você terá que ficar aqui durante a noite. Você vai
 Preciso tomar isso, beber isso - tudo isso, eu sei que é bom gosto. Agora, volte e vou acordar
 você na parte da manhã.}
{118}{}{Eu me sinto bem. Tchau.}
{119}{}{Obrigado. Isso fez o truque.}
{120}{}{Me desculpe, mas não sou médico e não posso fazer uma cirurgia. Eu sugiro que você
 vá para uma das cidades maiores e veja um cirurgião. Experimente a Nova República da Califórnia. Está a leste daqui.}
{121}{}{OK. Tchau.}
{122}{}{Tudo certo. Obrigado mesmo assim.}
{123}{}{O que você gostaria de saber?}
{124}{}{Você é prisioneiro?}
{125}{}{Você sai daqui quando quer?}
{126}{}{O que você sabe sobre D'garra?}
{127}{}{Como você está aqui?}
{128}{}{Eu vou agora.}
{129}{}{Você é um prisioneiro aqui?}
{130}{}{Você pode sair daqui se quiser?}
{131}{}{O que você pode me falar sobre os cânceres da morte?}
{132}{}{Como você veio para estar aqui em primeiro lugar?}
{133}{}{Obrigado pela informação. Eu vou sair agora.}
{134}{}{Não, eu não sou prisioneiro. Eu permaneço porque é necessário aqui. Aprendi a aceitar o fato de que
 Alguns dos meus pacientes são deathclaws.}
{135}{}{OK. Precisa saber mais.}
{136}{}{Obrigado. Tchau.}
{137}{}{Isso é muito louvável de você.}
{138}{}{Entendo.}
{139}{}{Essa é uma decisão com a qual não consigo concordar, mas é a sua vida.}
{140}{}{Sim, eu posso, e muitas vezes faço. Eu tenho que coletar minhas ervas de vez em quando, e nunca fui
 parado. Perguntei-me se os códigos da morte estavam me seguindo secretamente e se eles iriam ou não
 Pare-me se eu tentar sair. Então, um dia eu coloco a teoria para testar.}
{141}{}{Eu entendi. Vá agora.}
{142}{}{Precisa pedir mais.}
{143}{}{Você teve uma chance tola e você tem sorte, valeu a pena.}
{144}{}{Tudo certo.}
{145}{}{Boa ideia. Fico feliz em ver isso funcionar.}
{146}{}{Bem, vamos ver ... Mortes parecem ser mutantes camaleões de Jackson, a variedade de chifres.
 Há muitas semelhanças ainda presentes, mas um número ainda maior de diferenças. A mutação
 O fator é bastante alto. Esta espécie é altamente inteligente, sobre o equivalente a uma criança de oito anos,
 com alguns indivíduos atingindo o nível normal humano. Sua capacidade de aprendizagem é muito alta e eles são
 capaz de pensamento e raciocínio abstrato.}
{147}{}{Uh ... o que você disse.}
{148}{}{Veio agora.}
{149}{}{Uh-huh.}
{150}{}{Uau, estou impressionado com o seu conhecimento.}
{151}{}{Parece um monte de cacau para mim.}
{152}{}{Eu estava reunindo algumas ervas uma noite quando uma voz me chamou para fora da escuridão. 'Eu estive
 observando você ", disse," e eu sei que você é um curandeiro. Você dedica-se à sua arte o suficiente para curar
 alguém estrangeiro para você? Alguém a quem muitos considerariam um inimigo?}
{153}{}{Ugh.}
{154}{}{Obrigado. Eu vou embora agora.}
{155}{}{Que desperdício de estar aqui quando você poderia estar ajudando os outros.}
{156}{}{Você é verdadeiramente um homem dedicado que merece reconhecimento.}
{157}{}{Interessante.}
{158}{}{Não ajudarei alguém como você. Vá embora.}

{159}{}{Eu viajei para outra cidade e fiquei lá uma semana ou mais antes de retornar. Quando voltei, estava
 calorosamente recebido. Gruthar, o líder do grupo, veio para mim pessoalmente e pessoalmente me agradeceu pela vinda
 costas. Não, definitivamente estou aqui porque quero ser.}

{160}{}{Embora eles não tenham acordes vocais, os ciclos da morte parecem imitar o discurso humano muito o mesmo
 como faz um papagaio. Ainda não descobri o mecanismo exato por trás disso, então não posso dizer mais em
 desta vez. Socialmente, eles são animais de embalagem com um código de ética muito rígido. Eles são liderados por um 'alfa
 homem que governa com o consentimento mútuo da matilha. Eles parecem ser extremamente leais ao pacote como um
 inteiro, tratando-o como uma unidade familiar ao invés de ter famílias individuais como seres humanos.}
{161}{}{O seu senso de certo e errado está bem definido. Eles seguem um código de ética que é
 forçado pelo pacote como um todo. A violência nunca é usada como uma solução para um problema entre o pacote como
 tanto quanto posso ver. Não houve "crimes capitais" cometidos aqui, então não posso dizer como são esses
 manipulado. Hmmm. Isso é sobre tudo o que posso pensar por enquanto. Espero que isso ajude você.}

{162}{}{Eu respondi que respeitava toda a vida e faria o meu melhor para curar os feridos, independentemente de quem
 ou o que eram. Eu pensei que era um ladrão ou raider que se tinha ferido e precisava
 um médico. Você não pode começar a imaginar minha surpresa quando um par de pernas morreu fora do
 noite com um companheiro ferido. Alguém o atirou muito bem. Eu disse a eles que não poderia trabalhar com ele
 onde estávamos, então eles me reviram e me trouxeram aqui. Estive aqui a partir desse dia.}
