{100}{}{Você vê uma morte. Ele o observa com olhos estranhamente inteligentes.}
{101}{}{Você vê Jul, o deathclaw.}
{102}{}{Você vê uma lei de morte típica. A criatura é enorme, com um corpo poderoso, dentes afiados e longos
 garras.}
{103}{}{Pare. Você não vai aqui. Este lugar fora dos limites.}
{104}{}{OK. Eu vou.}
{105}{}{Qual é esse lugar?}
{106}{}{Quem você?}
{107}{}{Tudo bem, vou embora}
{108}{}{Eu vou para onde eu quero, respiração de lagarto!}
{109}{}{O que é este lugar?}
{110}{}{Quem é Você?}
{111}{}{Esse incubatório. Forneça a mãe dentro. Ovos dentro. Eu guardo. Todo o pacote de guarda.}
{112}{}{Eu quero falar mãe.}
{113}{}{Quem você?}
{114}{}{Eu vou agora.}
{115}{}{Eu irei então.}
{116}{}{Quem é Você?}
{117}{}{Gostaria de falar com a mãe.}
{118}{}{I Jul. Pack warrior. Eu protejo a incubadora. Eu guardo a mãe.}
{119}{}{Eu} #Continue 146
{120}{}{Eu vou agora.}
{121}{}{Guarda mãe trabalho importante. Você é importante.}
{122}{}{Eu estou} #Continue 147
{123}{}{A mãe guardadora é uma posição de grande responsabilidade. Você deve ser um membro importante do pacote.}
{124}{}{Acho que vou sair agora.}
{125}{}{Você espera. Peço à mãe.}
{126}{}{OK.}
{127}{}{Mãe diz que ela fala com você. Você entra. Você não causa problemas. Eu não quero machucá-lo, mas eu machuquei
 Você é ruim se causar problemas.}
{128}{}{Mãe diz que ela fala com você. Você entra, mas vai sozinho; amigos ficam aqui. Você não causa
 problema. Eu não quero machucá-lo, mas eu te machuquei mal se você causar problemas.}
{129}{}{OK.}
{130}{}{Você acha? Eu não olho para ele dessa maneira. Isso me faz sentir bem. Eu gosto. Obrigado.}
{131}{}{You welcome. Eu vou agora.}
{132}{}{Eu quero falar mãe.}
{133}{}{Seja bem-vindo. Eu tenho que ir agora.}
{134}{}{Posso falar com a mãe?}
{135}{}{Lizard breath ... Oh, entendi. Ha ha! Agora você obtém isso. Eu guardo aqui porque eu quero dizer,
 mais difícil, filho de puta implacável em todo o cofre. Parafusar comigo, você parafuso com o melhor.
 Você sai daqui ou eu rasgo você para se afastar e fazer você me olhar cagar a garganta.}
{136}{}{Eu irei agora.}
{137}{}{Oh sim? Vamos ver o quão duro você é!}
{138}{}{É você de novo. O que você quer?}
{139}{}{Eu say hi. Eu go.}
{140}{}{Quem você diz que você é?}
{141}{}{Qual é esse lugar?}
{142}{}{Apenas caiu para dizer olá.}
{143}{}{O que é este lugar?}
{144}{}{Quem é você novamente?}
{145}{}{Você já está morto. Você é tão burro demais para cair.}

{146}{}{. Eu quero falar mãe.}
{147}{}{, Jul, e eu gostaria de falar com a mãe, por favor.}
