{100}{}{Você vê uma morte.}
{101}{}{Você vê Kerith, a mãe mortal.}
{102}{}{Você vê uma lei de morte típica. A criatura é enorme, com um corpo poderoso, dentes afiados e longos
 garras. Este parece ser feminino, mas você não pode dizer com certeza. Você percebe as cicatrizes de várias lesões em seu tronco.}
{103}{}{Um visitante humano é um evento inesperado, mas não indesejável. Eu sou Kerith.}
{104}{}{Com o que posso ajudar?}
{105}{}{Você é dama mãe?}
{106}{}{Quem é o pai de D'Arg?}
{107}{}{A porta parece uma porcaria. O que acontece?}
{108}{}{Quem constrói o quarto do ninho?}
{109}{}{Eu vou agora.}
{110}{}{Então, você é a mãe da morte?}
{111}{}{Quem é o pai do deathclaw?}
{112}{}{O que aconteceu com a porta? Parece que tem visto dias melhores.}
{113}{}{Quem construiu esse incubatório?}
{114}{}{Eu vou sair agora.}
{115}{}{Sim. Eu sou a mãe do pacote atual. Depois que meus ovos escotilam, as outras mães terão seu turno.}
{116}{}{OK.}
{117}{}{Outras mães?}
{118}{}{Entendo.}
{119}{}{Existem outras mães?}
{120}{}{Sim, há mais mães. Se algo acontecer comigo, um será escolhido para ocupar meu lugar.
 O pacote deve sobreviver.}
{121}{}{Uh, eu entendo.}
{122}{}{Compreendo.}
{123}{}{Esses ovos foram gerados por Gruthar, o líder do pacote. É Gruthar quem decide quem vai se acasalar e
 quem não vai. O pacote será fortalecido pela Gruthar.}
{124}{}{Uh, está bem.}
{125}{}{Hmmm. Entendo. Selective breeding to improve the strain.}
{126}{}{Essa é uma memória dolorosa. Um humano traiçoeiro entrou aqui e plantou uma bomba entre os ovos
 enquanto eu estava dormindo. Felizmente, ele não foi tão furtivo e eu acordei para encontrar a bomba. Houve
 Não há tempo suficiente para lidar com o dispositivo corretamente, então eu joguei na porta e me coloquei entre
 e os ovos. Os ovos e eu sobrevivemos. A porta não o fez.}
{127}{}{O que aconteceu com o ser humano?}
{128}{}{Como ficar de guarda lá fora?}
{129}{}{Eu tenho mais perguntas.}
{130}{}{O que aconteceu com a pessoa que fez isso?}
{131}{}{Como essa pessoa chegou pelo guarda lá fora?}
{132}{}{Eu tenho mais algumas perguntas.}
{133}{}{O nome dele é Matt, e ele é um prisioneiro aqui. Pessoalmente, eu queria que ele morresse - mas Gruthar seria
 não permita isso. Não vejo a sabedoria nisso, mas a palavra de Gruthar é lei e ele será obedecido. Devemos
 você fala com este humano, tome cuidado. Ele não pode ser confiável!}
{134}{}{Como ficar de guarda lá fora?}
{135}{}{OK.}
{136}{}{Como essa pessoa chegou pelo guarda lá fora?}
{137}{}{OK.}
{138}{}{O guarda foi adicionado depois que este incidente ocorreu. Nós éramos mais confiantes naquela época. Agora somos nós
 mais cuidadoso.}
{139}{}{O que aconteceu com o ser humano?}
{140}{}{Eu entendi.}
{141}{}{O que aconteceu com essa pessoa?}
{142}{}{Entendo.}
{143}{}{Nós construímos a porção da caverna, e um amigo humano instalou a porta. Ele obteve as partes de um acordo
 nordeste daqui.}
{144}{}{Que legal.}
{145}{}{Isso é bom.}
{146}{}{Hello again. It is good to see you. Com o que posso ajudar?}
{147}{}{Me just say hello. Eu vou agora.}
{148}{}{Só dizendo Oi. Eu irei agora.}
{149}{}{Está triste por ter que matá-lo.}
