{100}{}{Você vê um homem alto e esbelto.}
{101}{}{Você vê Matt.}
{102}{}{Você vê um homem alto e delgado com cabelos curtos e um olhar selvagem em seus olhos. Você pode senti-lo olhando fixamente
 de volta a ti.}
{103}{}{Existe algo com o que posso ajudá-lo, estranho?}
{104}{}{Eu faz perguntas?}
{105}{}{Não, ondulado.}
{106}{}{Sim, gostaria de fazer algumas perguntas.}
{107}{}{Não, eu vou sair.}
{108}{}{O que você quer?}
{109}{}{Quem você?}
{110}{}{Você é prisioneiro?}
{111}{}{Eu vou agora.}
{112}{}{Quem é Você?}
{113}{}{Você é um prisioneiro aqui.}
{114}{}{Eu vou sair agora.}
{115}{}{Meu nome é Matt. Isso importa?}
{116}{}{Acho que não.}
{117}{}{Humph. Eu vou.}
{118}{}{Ok, vou embora.}
{119}{}{Na verdade não.}
{120}{}{Sim, na verdade, eu sou. Eu me deparei com este lugar e me peguei pelos cânceres da morte.
Eles me dão liberdade de movimento dentro dos níveis mais baixos do cofre, mas nunca posso ir ao nível 1, onde a saída é.}
{121}{}{Por quê?}
{122}{}{OK.}
{123}{}{Eu aqui fora.}
{124}{}{Por quê?}
{125}{}{Entendo.}
{126}{}{Eu irei agora.}
{127}{}{Porque, ao contrário do resto das ovelhas que vivem aqui, eu as reconheço como uma ameaça para a humanidade.
 Eles sabem que, se eu sair daqui, vou aguentar que eles sejam apagados da terra!
 Olhar: eles podem pensar por si mesmos, podem aprender, podem ler e até escrever se mergulharem uma garra
 na tinta. Eles são rápidos, duros, perceptivos e mortais. Se seus números crescerem o suficiente, eles serão
 A maior ameaça que a raça humana poderia enfrentar. Pense nisso. Eles precisam ser eliminados!}
{128}{}{Hmm. Você faz sentido.}
{129}{}{Eu acho que você está errado.}
{130}{}{Eu percebo que eles são uma ameaça potencial, mas eu confio neles.}
{131}{}{Você tem um ponto. O que deveríamos fazer?}
{132}{}{Sozinho, não tenho chance, mas juntos podemos lutar para sair daqui. Que tal?}
{133}{}{Sim.}
{134}{}{Não.}
{135}{}{Arrgh! Você é um tolo para confiar neles. Se você mudar de opinião, volte e me pegue.}
{136}{}{Tchau.}
{137}{}{Você mudou de idéia? Você vai me ajudar a sair daqui?}
{138}{}{Sim.}
{139}{}{Não.}
{140}{}{Você parece ter comprado uma tempestade de merda!}

{141}{}{Eu não aqui sobre a fuga. Eu aqui porque alguém quebra o computador. Você faz?}
{142}{}{Não estou aqui para falar sobre planos de fuga. Alguém sabotou a interface do computador mainframe. Sabe alguma coisa sobre isso?}
{143}{}{Você parece ter comprado uma tempestade de merda!}
{144}{}{Sim. Destruí o módulo de voz e desabilitei toda a entrada do teclado.}
{145}{}{Por quê?}
{146}{}{Com o mainframe offline, o vault acabará por desligar. Sem alimentos ou água, os mortandras serão forçados a começar a atacar terras humanas para suas necessidades. Eventualmente, serão descobertos e sua ameaça para a humanidade pode ser tratada.}
{147}{}{Outros aqui. Eles precisam de comida, água. Você não se importa com eles?}
{148}{}{E quanto aos outros que vivem aqui. Você não está preocupado com seu destino?}
{149}{}{Não no mínimo. Eles são simplesmente vítimas da guerra.}
{150}{}{Eu vou agora.}
{151}{}{Eu penso em me atirar em você agora.}
{152}{}{Bom trabalho.}
{153}{}{Entendo. Eu irei agora.}
{154}{}{Acho que vou te atirar agora. Você é obviamente perigoso.}
{155}{}{Bom trabalho!}
