{100}{}{Você vê uma menina pequena vestindo um vestido amarelo.}
{101}{}{Você vê Sandy, a criança.}
{102}{}{Você vê uma menina pequena vestindo um vestido amarelo com flores nele. Ela parece estar meando como
 um gato. Ela tem uma etiqueta de nome que diz "Sandy".}
{103}{}{Meow ... meow ... Eu sou um gato. E eu tenho poderes especiais que só os gatos têm. O que você é?}
{104}{}{Eu, doggy! Woof! Woof! Quem você?}
{105}{}{Urrh? (olhar cachorrinho confuso)}
{106}{}{Você é estranho. Eu fui embora.}
{107}{}{Eu sou a pessoa que vai chutar sua bunda se você não parar esse absurdo do gato e me contar seu
 nome.}
{108}{}{Eu sou apenas uma pessoa normal que está bastante impressionada com sua natureza especial. Você pode me dizer o seu
 nome?}
{109}{}{Deixa pra lá.}
{110}{}{(Giggles) Você parece engraçado! Meow ... eu sou Sandy. Eu não sou realmente um gato. Eu apenas gosto de jogar como eu
 sou.}
{111}{}{(Gritos) Mãe! Mamãe! Mamãe!}
{112}{}{Eu sou Sandy. Eu não sou realmente um gato, eu apenas gosto de jogar.}
{113}{}{Eu também jogo. Eu perguntei-lhe perguntas?}
{114}{}{Eu vou embora agora.}
{115}{}{Entendo. Posso fazer-te algumas perguntas?}
{116}{}{Ok, eu sou história.}
{117}{}{O que voce quer me perguntar?}
{118}{}{Você forçou ficar aqui?}
{119}{}{Você gosta de estar aqui?}
{120}{}{Você está seguro aqui?}
{121}{}{Deixa pra lá. Me leave.}
{122}{}{Você está forçado a ficar aqui?}
{123}{}{Você gosta daqui?}
{124}{}{Você está seguro aqui?}
{125}{}{Deixa pra lá. Bye}
{126}{}{Sim. Minha mãe sempre me diz onde posso e não posso ir. Ela me diz onde eu posso jogar e quando
 para comer e quando ir para a cama e quando ir em vaso e quando ir para a escola e tudo mais. Eu não penso
 É justo que ela possa fazer o que quiser, mas tenho que fazer o que ela diz o tempo todo.}
{127}{}{Está bem.}
{128}{}{Me despedi agora.}
{129}{}{Entendo.}
{130}{}{Eu acho que já ouvi o suficiente por enquanto. Tchau.}
{131}{}{Eu acho. Eu sinto falta de outras crianças para brincar, mas mamãe diz que vai mudar algum dia. Ela
 Acha que outras crianças virão morar aqui. Até que eles gostem de jogar com Valdis. Ele é engraçado e ele
 me dá passeios piggy back. Mamãe diz que devo deixar Valdis sozinho. Ele está ocupado e não tem tempo para
 jogar, mas ele sempre joga comigo quando eu perguntar a ele. Eu simplesmente não falo mais sobre essa mãe.}
{132}{}{Piggy ... (olhar cachorrinho confuso)}
{133}{}{Eu vou.}
{134}{}{Isso é bom.}
{135}{}{Ok te vejo por ai.}
{136}{}{Sim. Mamãe cuida de mim e Valdis não deixa ninguém me machucar. Estou a salvo aqui.}
{137}{}{Está bem. Me go now.}
{138}{}{Boa; Eu irei então.}
{139}{}{Oi.}
{140}{}{Vá embora! Eu não gosto de você!}
