{100}{}{Você vê uma morte. Observa você com olhos estranhamente inteligentes.}
{101}{}{Você vê Thearn, o deathclaw.}
{102}{}{Você vê uma morte típica. A criatura é enorme, com um corpo poderoso, dentes afiados e longos
 Garras.}
{103}{}{Perdoar. Eu não falo bem. Eu tento falar com você.}
{104}{}{Você quer o que?}
{105}{}{Quem você?}
{106}{}{O que você faz?}
{107}{}{Quão inteligente você?}
{108}{}{Eu vou agora.}
{109}{}{Quem é Você?}
{110}{}{O que você está fazendo aqui?}
{111}{}{Não há ofensa, mas o quão inteligente você é?}
{112}{}{Bem, apenas passando o tempo.}
{113}{}{I Thearn. Quem você?}
{114}{}{Eu}
{115}{}{Eu leave.}
{116}{}{Eu tenho que ir.}
{117}{}{É um prazer conhecê-lo, Thearn. Eu estou}
{118}{}{Consegui.}
{119}{}{Agora que eu penso nisso, eu não dou o traseiro de um radrat que você é.}
{120}{}{Eu guardo o corredor. Segurança do objetivo do pacote.}
{121}{}{Oh ... Uh ...}
{122}{}{Guarda? O que?}
{123}{}{Ok. Eu go.}
{124}{}{Bem, continue. Eu vou sair agora.}
{125}{}{Você está fazendo um excelente trabalho!}
{126}{}{Você se chama de guarda? Ha!}
{127}{}{O que você está protegendo contra o corredor?}
{128}{}{Intruso. Humanos, deathclaw, seja o que for. Pack ameaçado, eu ataque.}
{129}{}{Ah.}
{130}{}{Entendo.}
{131}{}{Eu ficaria surpreso se você fosse inteligente o suficiente para dizer a um amigo de um inimigo.}
{132}{}{Sinto pena de qualquer intruso que aconteça sobre você.}
{133}{}{Deixa pra lá. Te vejo em breve.}
{134}{}{Como eu julgo? Não sei. Algumas coisas entendem muito. Algumas coisas entendem pouco. Muitas coisas
 Não entenda.}
{135}{}{Você, eu, o mesmo.}
{136}{}{Sim, bem, isso também me descreve.}
{137}{}{Você está indo bem.}
{138}{}{Em outras palavras, você é um idiota.}
{139}{}{Você embala amigo. Você economiza o pacote pela máquina de reparação.}
{140}{}{Olá de novo. Eu ainda guardo aqui.}
{141}{}{}
{142}{}{Arrrrrrrrrgggh! Morrer!}

{143}{}{.}
