{100}{}{Você vê uma morte. Ele o observa com olhos estranhamente inteligentes.}
{101}{}{Você vê Valdis, o deathclaw.}
{102}{}{Você vê uma lei de morte típica. A criatura é enorme, com um corpo poderoso, dentes afiados e longos
 garras.}
{103}{}{Saudações, humanas.}
{104}{}{Como posso atendê-lo?}
{105}{}{Quem você é?}
{106}{}{O que você faz?}
{107}{}{Doença cerebral. Eu volto mais tarde.}
{108}{}{Olá quem é você?}
{109}{}{Qual é o teu trabalho?}
{110}{}{Não ofende os seus companheiros de morte, mas parece mais ... educado, devemos dizer?}
{111}{}{Bem, apenas passando o tempo.}
{112}{}{Eu sou chamado Valdis. E você é?}
{113}{}{Eu humano.}
{114}{}{Oooo! Algo brilhante. Eu vou.}
{115}{}{Ei, eu sou o único a fazer as perguntas aqui.}
{116}{}{Eu tenho que ir.}
{117}{}{Fico feliz em conhecê-lo, eu sou}
{118}{}{Consegui.}
{119}{}{Atualmente, estou guardando esta área do cofre contra qualquer pessoal não autorizado.}
{120}{}{Desconsolar a pessoa gelada?}
{121}{}{Uh ... claro.}
{122}{}{Você fala engraçado. Eu vou embora.}
{123}{}{Eu vou sair agora, Valdis.}
{124}{}{Entendo.}
{125}{}{Bem, você certamente parece conhecer seu trabalho bem.}
{126}{}{Você tem o cérebro para decidir quem é ou não está "autorizado"?}
{127}{}{Por que sim, eu sim. Eu também tenho crenças suficientes para decidir quem é ou não é um idiota - e eu tenho
 concluiu que você se destaca naquela categoria! Agora, por que você não vai embora antes de eu dançar no seu rosto por
 meia hora?}
{128}{}{Tudo certo.}
{129}{}{Bad lagarto. Agora eu tenho que atirar em você.}
{130}{}{Ei, desculpe. Eu vou ver minha língua a partir de agora.}
{131}{}{Sim. Somos muito diversos em nossos níveis de educação. Estou fazendo o meu melhor para continuar meu no meu
 tempo livre.}
{132}{}{Uma iguana com um objetivo. Que fofinho é fofo.}
{133}{}{Você está indo bem.}
{134}{}{Esse é um excelente objetivo. Mantem.}
{135}{}{Hã? Estou bem ciente de que você é humano. Eu estava perguntando sobre o seu nome.}
{136}{}{Não pergunte o nome, pergunte "você é". Eu sou humano.}
{137}{}{Eu sei. Eu apenas o testei. Uh ... você passa.}
{138}{}{Ouça alguém chamada. Eu vou.}
{139}{}{Entendo. Let us try this again. Hello. I am Valdis. What is your name?}
{140}{}{Eu}
{141}{}{Tchau.}
{142}{}{Unauthorized personnel. Euaning 'people who do not have permission to be here.'}
{143}{}{Ok. Eu understand.}
{144}{}{Eu get another of those headaches. Eu go now.}
{145}{}{Meu objetivo é manter toda a paciência possível, à luz do fato de que você está sendo rude.
 Se você não pode lidar comigo civilmente, então, deixe.}
{146}{}{Desculpe, vou tentar ser mais civil.}
{147}{}{Empurre-o.}
{148}{}{Sim.}
{149}{}{Bom dia para você.}
{150}{}{Lamento o fato de que eu deveria matá-lo.}

{151}{}{.}
