{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal da interface de voz.}
{102}{}{Você vê um terminal de computador padrão, modificado para comandos de voz.}
{103}{}{Você examina o terminal do computador, mas não consegue encontrar nada, obviamente, errado com ele. Fazer o que
 Você faz?}
{104}{}{Acerte nessa maneira "especial".}
{105}{}{Retroceda nesse ponto "especial".}
{106}{}{Execute o programa de diagnóstico.}
{107}{}{Abra-o e olhe para dentro.}
{108}{}{Deixe-o em paz.}
{109}{}{Você olha o console por um tempo e decide o melhor lugar para colocar um soco. Depois de dar
 O seu melhor 'isso vai consertar', o monitor pisca um par de vezes e depois se estabiliza. Há sim
 Nenhum outro efeito.

O que você faz?}
{110}{}{Retroceda nesse ponto "especial".}
{111}{}{Execute o programa de diagnóstico.}
{112}{}{Abra-o e olhe para dentro.}
{113}{}{Deixe-o em paz.}
{114}{}{Este conhecido método de reparo produz dois resultados. Primeiro, o monitor parece ficar mal
 Vários segundos e depois estabiliza. Em segundo lugar, você ouve um tipo de metal quebrando e o painel você
 Chutado cai no chão. O que você faz?}
{115}{}{Execute o programa de diagnóstico.}
{116}{}{Maldita coisa está aberta. Poderia também olhar para dentro.}
{117}{}{Deixe-o em paz.}
{118}{}{Você está certo de que o sistema deve ter um conjunto de rotinas de diagnóstico disponíveis. No entanto, o
 A entrada do teclado parece ter sido desabilitada. A unidade aceita apenas comandos de voz. O que você faz?}
{119}{}{O único que resta é olhar para dentro.}
{120}{}{Deixe-o em paz.}
{121}{}{Peering na massa de cabos e placas de circuito, você acha que o sistema foi saboteado deliberadamente.
 Uma das placas de circuito, o módulo de reconhecimento de voz, está além do reparo e deve ser substituído.
 Agora, tudo o que você precisa fazer é encontrar um módulo de substituição.}
{122}{}{Feito.}
{123}{}{Feito.}
{124}{}{Você instala o módulo no terminal. O sistema é reparado.}
{125}{}{O terminal precisa de um módulo de reconhecimento de voz instalado antes que ele possa se tornar operacional.}
{126}{}{Feito.}
{127}{}{O sistema está funcionando bem agora.}

{128}{}{Acessando imagens de segurança, carregando a reprodução holográfica ...}

{129}{}{Você é o último, Gruthar. A mancha de seu tipo em breve será limpa.}
{130}{}{Você diz ao seu chamado presidente que ele vai queimar por isso.}
{131}{}{Tanto faz. Você nunca mais foi um animal falante.}
{132}{}{Isso pode ser, mas fomos criados através de sua experimentação. Você nos deu vida!}
{133}{}{E agora eu dou a morte.}
{134}{}{Pegue seu corpo. O médico queria um espécime.}
{135}{}{Seu sangue corre como o Nilo!}
