# EXAMINES
{151}{}{}

# USE MESSAGES
{200}{}{Outlook bom.}
{201}{}{O Outlook não é tão bom.}
{202}{}{Minha resposta é não.}
{203}{}{Não conte com isso.}
{204}{}{Você pode confiar nisso.}
{205}{}{Pergunte novamente mais tarde.}
{206}{}{Provavelmente.}
{207}{}{Não é possível prever agora.}
{208}{}{Sim.}
{209}{}{Sim. Definitely.}
{210}{}{Melhor não te contar agora.}
{211}{}{É certo.}
{212}{}{Muito duvidoso.}
{213}{}{É decididamente assim.}
{214}{}{Concentre-se e pergunte novamente.}
{215}{}{Sinais apontam que sim.}
{216}{}{Minhas fontes dizem que não.}
{217}{}{Sem dúvida.}
{218}{}{Responda nebuloso, tente novamente.}
{219}{}{Como eu vejo, sim.}
{220}{}{Pare de me sacudir tão forte. Isso dói.}
{221}{}{Você tem um braço direito forte.}
{222}{}{Por favor, limpe suas mãos antes de me agitar de novo.}
{223}{}{Fora de serviço.}
{224}{}{Fechado por ordem do Conselho de RPG.}
{225}{}{Continue me sacudindo, e haverá problemas.}
{226}{}{Estou ficando doente.}
{227}{}{Estou com náuseas.}
{228}{}{Suas mãos estão quentes.}
{229}{}{Feargus estava contra me colocar no jogo. Ele é um grande mistério.}
{230}{}{Sua pontuação é de 23 em 100. Você ainda tem muitos caminhos a seguir.}
{231}{}{Scotty Everts suspira muito quando vê quantos itens de inventário estão no jogo.}
# 9 or greater luck
{232}{}{Olhe no banheiro do banheiro do primeiro andar no casino Mordino em New Reno.}
{233}{}{Se você ativar a cruz rotulada "Lixeira" no Golgotha, você encontrará um segredo.}
{234}{}{Volte e fale com o padre Tully em New Reno depois de terminar o jogo.}
{235}{}{Você pode usar-me como uma arma, você sabe.}
{236}{}{Pare de me sacudir tão forte.}
{237}{}{Sua LUCK é muito alta. Continue me sacudindo por pistas!}
{238}{}{Sim, nós SABEMOS A subida a Undermountain era uma porcaria.}
