{100}{}{Você vê um homem com um terno. Ele está olhando para o espaço. Como se ele estivesse olhando para você, mas ele não está olhando para você.}
{101}{}{Você vê o chefe do mundo livre, o Presidente dos Estados Unidos.}
{102}{}{Você vê um homem magro, nervoso e mais velho que parece tão cansado e desgastado quanto o traje que ele usa.}

{103}{prs1a}{Você está lá, o que você está fazendo fora do centro de recondicionamento?}
{104}{prs1b}{Eu conheço você? Em que projeto você está?}
{105}{prs1c}{E quem você acha que está entrando no meu escritório?}
{106}{}{Uh?}
{107}{}{Nuh.}
{108}{}{Tchau tchau.}

{109}{prs2a}{Ah, afetado pelos soros de teste, vejo. Eu vou te ajudar. Guardas!}
{110}{prs2b}{Doutor, acho que você esteve exposto ao F.E.V. Pobre alma, vou te ajudar. Guardas!}
{111}{prs2c}{Seja um bom mutante e fique pronto. Guardas!}
{112}{}{ESTÁ BEM.}
{113}{}{Uh uh. Tchau tchau.}

{114}{}{Apenas espere aqui.}
{115}{}{Uh, fique calmo. Alguém estará bem.}
{116}{}{Tudo está bem.}
{117}{}{Droga! Alguém virá e conseguirá isso ... pessoa?}
{118}{}{Oh, guardas! Há um idiota no meu escritório ... Não, não o veep.}

{119}{prs4}{Olá. Sou o Presidente Richardson e estou orgulhoso de conhecê-lo. Uh, Vault 13, eu vejo. Você fez seu país um serviço inestimável.}
{120}{}{Presidente? De qualquer modo, quem é você?}
{121}{}{Um serviço para o meu país? O que está acontecendo aqui de qualquer maneira?}
{122}{}{Uh, acho que tomei uma atitude errada no meu caminho para o laboratório. Desculpe senhor. Adeus.}

{123}{prs5a}{Olá doutor. Você tem um relatório? Boas notícias, espero. Nãossa salvação está nas mãos da sua equipe.}
{124}{prs5b}{Você não deveria estar trabalhando no Projeto? A salvação da humanidade depende de você.}
{125}{}{Quem é você?}
{126}{}{Salvação? Apenas o que está acontecendo aqui?}
{127}{}{Desculpe senhor. Volta no caminho para o laboratório. Adeus.}

{128}{prs6}{Oh, está tudo bem. Todos aqueles tiros de inoculação desorientariam qualquer um.}
{129}{}{Tiros de inoculação? O que você quer dizer?}
{130}{}{Acho que me sinto um pouco grogue. Mas sabendo que estou ajudando meu país a fazer com que tudo pareça valer a pena.}
{131}{}{Você pode dizer isso de novo. Bem, é melhor eu continuar.}

{132}{prs7}{Deixe-me pegar um dos Serviços Secretos para acompanhá-lo de volta.}
{133}{}{Isso é um pouco de você, mas acho que posso fazer isso sozinho. Adeus.}
{134}{}{Isso seria bom para você. Obrigado.}

{135}{prs8}{Não é nenhum problema. (falar com o interfone) Olá. Eu poderia usar um pouco de ajuda aqui.}
{136}{}{Uh. Gee, obrigado, senhor.}
{137}{}{É melhor não ligar para os seus guardas se quiser deixar este quarto vivo.}

{138}{prs9}{Ah bem. Tenho certeza de que podemos resolver algo. O que está em sua mente?}
{139}{}{Quero saber o que está acontecendo aqui.}
{140}{}{Eu só quero sair quietamente. Mantenha sua mão fora do alarme até eu sair daqui. Se não….}
{141}{}{Estou saindo aqui e levando você como um refém para garantir que minhas pessoas saem com segurança.}

{142}{prs10}{Você realmente acha que pode intimidar o Presidente dos Estados Unidos?}
{143}{}{Sem dúvida.}
{144}{}{Talvez não, mas eu sugiro que fique fora do meu caminho até eu sair.}

{145}{prs11a_a}{Para sua informação, os guardas têm ordens para me atirar em vez de deixar qualquer pessoa ou qualquer coisa pôr em perigo o projeto. Eu ... não seria de qualquer modo como refém.}
{146}{prs11b}{Você realmente não espera que isso funcione, você? Ha! Se você tentar, meus guardas têm ordens para me atirar em vez de deixar qualquer coisa, ou qualquer pessoa, pôr em perigo o projeto. Eu estou ficando aqui. Agora, você vai me atirar ou não?}
{147}{}{Talvez não, mas eu vou embora. Não toque nesse sinal sonoro.}
{148}{}{O projeto? Qual projeto?}
{149}{}{Sim vai. Eu vou gostar.}

{150}{prs12}{Agora, agora, agora. Agora, vamos ... vamos ... Uh, Wh-wh-o que você quer, de qualquer maneira?}
{151}{}{Quero saber o que está acontecendo aqui.}
{152}{}{Quero saber quem diabos você é.}
{153}{}{Eu quero você morto.}

{154}{prs13}{Tudo bem, seja lá o que você disser. Eu vou sentar aqui calmamente. É, prazer, conhecê-lo. Adeus.}
{155}{}{Isso é muito fácil. Antes de ir, gostaria de saber exatamente o que você está fazendo aqui.}
{156}{}{Tenha cuidado.}
{157}{}{Prazer em conhecê-lo, Sr. Presidente. Adeus.}

{158}{prs14}{Ahhh. Ahhh. Guardas? Guardas!}
{159}{}{Diga boa noite, Sr. Presidente.}

{160}{prs15}{Eu sou o Presidente dos Estados Unidos da América. O vice-presidente está no escritório lá fora. Se você pertencesse aqui, você saberia disso. Quem é você e o que você está fazendo aqui?}
{161}{}{Você é o presidente do que os Estados Unidos?}
{162}{}{Você é um loony.}
{163}{}{Vice presidente? Você quer dizer aquele idiota babando ao lado?}
{164}{}{Que coincidência, eu sou o Imperador do planeta Quetzl, aqui para a rendição da Terra.}
{165}{}{Eu apenas vou deixar você voltar para o negócio Sr., uh, presidente. Adeus.}

{166}{prs16}{Ah-ha. Oh, claro, sua eminência. Por que não ligo para ... alguns refrescos? Podemos conversar e resolver as coisas - não podemos simplesmente nos dar bem?}
{167}{}{Isso soa grandioso.}
{168}{}{Bom tentativa, Sr. Presidente.}

{169}{prs17}{Uh, bem, apenas um segundo. (no interfone) Ahh, eu gostaria de refrescos para mim e um * hóspede inesperado *. Um importante - inesperado - convidado. Imediatamente?}
{170}{}{Obrigado. Acho que você não é um cara tão mau depois de tudo.}
{171}{}{Isso foi estúpido. Agora, alguém vai ter que se machucar.}

{172}{prs18}{Alguém está louco aqui, tudo bem. Oh sim. Oooooh sim.}
{173}{}{Não olhe para mim. Eu não estou reivindicando ser o presidente dos Estados Unidos que caiu muito antes de nós nascermos.}

{174}{prs19}{Eu sou o representante eleito das pessoas. Os Estados Unidos ainda existem. Deus abençoe todos nós. Precisamos nos adaptar para sobreviver depois da guerra.}
{175}{}{Eu não entendo. O que você quer dizer?}

{176}{prs20a}{Você realmente não sabe, não é? Deixe-me falar sobre a salvação da humanidade. Um pouco de história primeiro ...}
{177}{prs20b}{Um pouco de história ...}
{178}{}{Continue, Sr. Presidente ....}
{179}{}{Primeiro, por que você tem uma base no Navarro?}
{180}{}{Antes de entrar nisso ... eu vi alguns de seus vertibirds fazendo algum comércio com New Reno. Sobre o que é isso?}
{181}{}{Não tenho tempo para esta loucura agora. Adeus.}

{182}{prs21a}{Bem, alô lá. Fico feliz em fazer tempo para um de nossos galantes soldados. Mas estou bastante ocupado. Então, uh, o que o Presidente dos Estados Unidos pode fazer por você?}
{183}{prs21b}{Você voltou? O que é que você quer?}
{184}{}{Você pode me dizer exatamente o que está acontecendo aqui.}
{185}{}{Eu, eu só estou checando esta área, senhor. Verificação de segurança. Sim. Tudo está bem aqui. Uh, adeus.}

{186}{prs22a}{Olá. Eu sou o Presidente dos Estados Unidos da América, e você é ...?}
{187}{prs22b}{Olá. Eu sou o Presidente dos Estados Unidos da América e devo dizer que raramente vi uma estranha, ou mais sorrateira, delegação de inadaptados em toda a minha vida. Quem é você para entrar em mim assim?}
{188}{}{Tenho muita curiosidade quanto ao que está acontecendo aqui.}
{189}{}{Eu sou seu executor.}
{190}{}{O presidente? Do que você está falando?}
{191}{}{Estou perdido. Posso ver que você é um homem ocupado, Sr. Presidente. Eu vou sair agora. Adeus.}

{192}{prs23}{Isso é uma vergonha. Uma conversa com um mutante genuíno como você? Certamente, me pintaria uma imagem do que é a vida naquele inferno radioativo no continente.}
{193}{}{Mutant? Por que você está me chamando de mutante?}
{194}{}{Inferno radioativo? Você não sai muito, não é?}
{195}{}{É isso aí. Basta falar. Hora de morrer.}
{196}{}{Sim, bem, todos nós temos que aprender a viver com decepção. Adeus.}

{197}{prs24}{Houve uma grande guerra muito antes de nascermos. Nãossos galantes soldados lutaram do Yukon para o Yangtze.}
{198}{}{Sim, eu sabia sobre essa parte. Continue.}

{199}{prs26}{O vice-presidente Bird pode parecer um idiota babando, mas eu vou saber que o homem é um herói nacional.}
{200}{}{Para você, provavelmente.}

{201}{prs27}{Ele é um dos homens mais corajosos que conheço. Ele se ofereceu para tentar uma das primeiras versões do F.E.V. antídoto de toxina. (suspiro) Infelizmente, não funcionou da maneira que esperávamos.}
{202}{}{Você quer dizer que isso não era o que você esperava?}

{203}{prs28}{São pequenas mentes zombadoras como a sua que provam a superioridade de humanos reais sobre os mutantes.}
{204}{}{Ele ainda é um idiota gibbering.}
{205}{}{Por que você está me chamando de mutante?}

{206}{prs29}{Ele ainda pode se aproximar. Na verdade, pode haver alguns benefícios imprevistos. Sua habilidade de ortografia realmente melhorou.}
{207}{}{Estou feliz por você. Mas por que você me chamou de mutante?}

{208}{prs30}{Porque você é. O DNA da sua tribo mudou desde que seu antepassado deixou o cofre. Inevitável. Toda a radiação de fundo em que você esteve exposto.}
{209}{}{Ok, então sou um mutante. Adivinhe o cara inteligente, você está prestes a se tornar um humano de morte pura morto.}
{210}{}{Então somos mutantes. E daí.}
{211}{}{As criaturas mudam o tempo todo. É chamado de evolução. Sem essa mudança, você e eu ainda seríamos dois pedaços de camuflagem protoplasmática.}

{212}{prs31}{Tentamos manter-nos seguros e protegidos contra a radiação. Isso é o que separa os seres humanos - como eu - de mutantes como você.}
{213}{}{Por que você continua me chamando de mutante?}
{214}{}{Basta falar. Tempo para você enfrentar essa grande faculdade eleitoral no céu.}
{215}{}{Eu matei homens por menos do que isso. Mas estou com pressa hoje. Adeus.}

{216}{prs32}{Nós também estávamos ganhando. E então, aqueles malditos Reds lançaram tudo o que tinham. Nós mal conseguimos nossos pássaros para cima.}
{217}{}{Parece que isso nos ajudou muito.}

{218}{prs33}{Bem, não, não. Mas pelo menos derrubou a maldita ameaça Vermelha na era da pedra.}
{219}{}{E nós com isso.}

{220}{prs34}{Bem não. Não ... não é bem. Você vê, nós tínhamos planejado para a frente. Estávamos prontos.}
{221}{}{O que você quer dizer?}

{222}{prs35}{Tivemos uma série de santuários que permitiriam que a gloriosa civilização americana durasse. Essas instalações - as abóbadas - faziam parte do ótimo plano.}
{223}{}{Aqueles malditos cofres não funcionavam da maneira que deveriam. Muitas pessoas morreram.}

{224}{prs36}{Na verdade, eles trabalhavam quase exatamente da maneira que deveriam. Você pode chamá-lo de uma experiência social em grande escala.}
{225}{}{Um experimento?}

{226}{prs36a}{Os cofres foram criados para testar a humanidade. Alguns não tinham sintetizadores de alimentos suficientes, outros tinham apenas homens neles, mas outros foram projetados para abrir depois de apenas 6 meses. Cada um deles tinha um conjunto único de circunstâncias destinadas a testar os ocupantes.}
{227}{}{E o Vault 13? Qual foi o propósito?}

{228}{prs37}{Ahh. O Vault 13 era um caso especial. Era suposto permanecer fechado até que os assuntos fossem necessários. O Vault 13 era, em linguagem científica, um grupo de controle.}
{229}{}{Mas todos teriam morrido se o meu antepassado não receber um chip de água de reposição. Isso não parece se encaixar no seu plano.}

{230}{prs38}{Um acidente infeliz e imprevisto. Não entanto, como se revela, é bastante fortuito.}
{231}{}{O que você quer dizer?}

{232}{prs39}{Quando se verificou, precisávamos de assuntos de teste de ações humanas não mantidas, pré-guerra, humanas - seus antepassados   no Vault 13 - e algumas ações recém-mutadas - os aldeões de Arroyo.}
{233}{}{Por quê?}

{234}{prs39a}{Para o projeto. Está quase pronto. A salvação da humanidade está quase à mão e os Estados Unidos da América serão o progenitor desse renascimento.}
{235}{}{Rebirth? O que você quer dizer?}

{236}{prs40a}{O único caminho para os verdadeiros seres humanos e a democracia, para estar seguro é limpar os mutantes do globo. Nós humanos devolveremos o que é legítimo nosso.}
{237}{prs40b}{O Projeto irá limpar todos os mutantes da nossa terra justa - e o resto do globo. Mais uma vez, a América será o policial do mundo.}
{238}{}{Eu também sou um verdadeiro humano.}
{239}{}{Limpe os mutantes? Isso parece um pouco drástico. Como você irá fazer aquilo?}

{240}{prs41}{Encontramos uma instalação de pesquisa em forma operacional há cerca de 70 anos. Uma antiga base militar que havia sido usada para pesquisar um vírus especial.}
{241}{}{Um vírus?}

{242}{prs42}{Sim, o F.E.V. vírus. Foi originalmente desenvolvido para transformar soldados em super-guerreiros, mas falhou. Os guerreiros eram fortes e fortes, mas muito estúpidos. Não entanto, nosso corpo químico brilhante alterou-o.}
{243}{}{Altered the virus? Por quê?}

{244}{prs43}{Para transformá-lo em um assassino assustadoramente eficaz. Qualquer humanoide que não seja inoculado contra seus efeitos antes da sua liberação, morrerá. Esse é o Projeto.}
{245}{}{Isso é insano.}

{246}{prs43a}{Não não. Essa é a última, melhor, esperança da humanidade. É o que temos trabalhado para todos esses anos.}
{247}{}{Ótimo, então você tem todo esse veneno e não há como espalhá-lo.}

{248}{prs44}{Perdimos alguns produtos químicos críticos. Podemos obtê-los dos laboratórios de drogas de New Reno. Se os mutantes-mafiosos usam nossas armas para matar-se, apenas nos salva o problema.}
{249}{}{Tudo funciona em seu favor, hein? Conte-me o resto da história.}

{250}{prs45}{Simples. Navarro é uma base isolada. Nãossos vertibirds têm um alcance limitado. Eles reabastecem lá.}
{251}{}{Faz sentido.}

{252}{prs46a}{Tenho certeza que você pensa assim. Mas os testes realizados em seus membros da tribo mostraram que você é culpado de mutação. É uma coisa muito boa que o Projeto esteja pronto.}
{253}{}{Por quê?}

{254}{prs46b}{Alguns membros da sua tribo estão apresentando mudanças extremamente interessantes. Se o perigo para a verdadeira humanidade não fosse tão grande, pensaria em estudá-los. Mas isso não deve ser.}
{255}{}{Não ser? Por que não?}

{256}{prs47}{Ah, mas essa é uma das vantagens do F.E.V. vírus. Nós podemos liberá-lo aqui e o jetstream irá transportá-lo em todo o mundo. Terá muito tempo para limpar todos os recantos do globo.}
{257}{}{ESTÁ BEM. Then why did you have to kidnap my villagers and the people from Vault 13?}

{258}{prs48}{Temas de teste. Seus aldeões são todos descendentes do estoque do cofre e nós precisamos ter certeza de que o F.E.V. a toxina ainda era efetiva. Os sujeitos do Vault 13 testaram isso e uma inoculação contra o VEF.}
{259}{}{Você não está testando a inoculação no meu povo?}

{260}{prs48a}{Não é necessário. Tenho certeza de que poderíamos e isso funcionaria, mas não há motivo para fazê-lo.}
{261}{}{Já aconteceu com você que o que você está fazendo é errado?}

{262}{prs49}{Nunca. Parte do trabalho do presidente é tomar decisões difíceis. Muitos seres humanos próximos sacrificarão suas vidas pelo retorno da humanidade. Os seres humanos prevalecerão.}
{263}{}{Não há nenhuma maneira no inferno que eu possa deixar você fazer isso.}
{264}{}{Apenas porque todos lá fora, não tem uma cópia exata do seu DNA que não lhe dá uma licença para exterminá-los.}

{265}{prs50}{Você não pode detê-lo. Os testes estão completos e a toxina está pronta para a liberação. Em horas, seus aldeões serão os primeiros a fazer o último sacrifício. Os outros mutantes seguirão. Uma nota de rodapé infeliz na história contínua da raça humana.}
{266}{}{Por que não começamos essa nota de rodapé com seu epitáfio, Sr. Presidente?}

{267}{prs51}{Oh, não gosto dessa decisão. Se houvesse outro caminho, mas não existe. Nenhum preço é muito alto para a sobrevivência da raça humana. Se você fosse humano, você sentiria o mesmo.}
{268}{}{Você realmente acredita nisso, não é?}

{269}{prs53}{Sim eu quero. Mesmo me matar não vai te ajudar. Não há nada que você possa fazer para interromper o lançamento.}
{270}{}{Talvez eu apenas descubra uma maneira de lhe dar uma amostra de seu próprio remédio.}
{271}{}{Vamos ver sobre isso. Eu tenho coisas para fazer. Adeus, o presidente Richardson.}
{272}{}{Eu discordo, Sr. Presidente. Eu acho que matar você vai ajudar. Eu me sentirei muito melhor.}

{273}{prs54}{Você poderia tentar, suponho, mas logo a equipe do Enclave e Navarro será inoculada.}
{274}{}{Eles ainda não estão?}

{275}{prs55}{Nós apenas temos que distribuir os suprimentos. Uma questão de horas. Além disso, o Enclave é uma unidade selada. Nenhum ar ou contaminantes entram ou saem.}
{276}{}{Veremos. Enquanto isso, eu estou tirando você da foto, pessoalmente.}

{277}{prs56}{Você pode achar isso mais difícil do que você pensa. Se o fizer, irei à minha recompensa sabendo que eu morri como patriota e serva da humanidade.}
{278}{}{Tempo para sua recompensa.}
{279}{}{Neste momento, vou deixar você pensar sobre a sua morte. Não toque no alarme. Adeus.}

{280}{prs57}{Muito em movimento. Mas as mudanças radicais que seus aldeões e outros mutantes mostram estão muito longe das mudanças graduais da evolução natural.}
{281}{}{Talvez nos mudemos para uma versão melhor da raça humana. Você ja pensou nisso?}

{282}{prs58}{Muito possível, na verdade. Nesse caso, nossa missão é ainda mais vital para a sobrevivência da raça humana.}
{283}{}{Hã? O que você quer dizer com isso?}

{284}{prs59}{Esse é o espírito. Deus abençoe a America. Você provavelmente deveria voltar para sua ala de isolamento agora.}
{285}{}{Sim, senhor. O que quer que você diga, senhor.}
{286}{}{Oh, eu vou poder encontrar meu próprio caminho de volta, senhor. Adeus.}

{287}{prs60}{Por que, contra o F.E.V. toxina, é claro. Damn brave sacrifício você e os outros membros do Vault 13 estão fazendo. Em nome do governo dos Estados Unidos e de toda a humanidade, agradeço-lhe. Agora, é melhor você voltar para sua ala.}
{288}{}{F.E.V. toxina? Que diabos você está falando? Oque esta acontecendo aqui?}
{289}{}{Uh, sim, senhor. O que quer que você diga, senhor.}
{290}{}{Oh, eu vou poder encontrar meu próprio caminho de volta, senhor. Adeus.}

{291}{prs61}{E daí? Se o seu tipo for autorizado a florescer, isso significará o fim da raça humana como a conhecemos. Não podemos permitir que freaks radioativos esmagem os seres humanos em extinção.}
{292}{}{Eu acho que você está superestimando as coisas um pouco.}

{293}{prs62}{De modo nenhum. Olhe para o futuro. Certidão e os homens podiam se dar um tempo, mas antes de conhecê-lo, a pressão numérica do seu tipo dirá. Não, uma linha deve ser desenhada na areia - o buck pára aqui.}
{294}{}{O que você pretende fazer sobre essa chamada ameaça?}
{295}{}{Não tenho tempo para ouvir suas ravações intolerantes e loucas. Adeus.}

{296}{prs63}{O governo dos Estados Unidos da América vem trabalhando para uma solução por algum tempo.}
{297}{}{Como assim? O que você está fazendo aqui?}

{298}{prs64}{Eu asseguro-lhe, eu sou bastante sã, assim como todos no projeto. Estamos dedicados à salvação da raça humana. Você pode chamar de dedicação única a uma loucura, suponho, mas, se assim for, é loucura divina.}
{299}{}{Do que você está falando? O que você está fazendo aqui?}
{300}{}{Que tal minha dedicação única a matar você agora?}
{301}{}{Você está louco. Eu não tenho tempo para sua loucura agora. Adeus.}

{302}{prs65}{Eu não acho que este velho planeta cansado é suficientemente grande para dois cães superiores. Se somos nós ou você ... Bem, vou escolher-nos.}
{303}{}{Eu não acho que você faça esse tipo de escolha.}

{304}{prs66}{Como encarnação do poder executivo, tenho o fardo de assegurar a sobrevivência e a prosperidade dos Estados Unidos e da própria humanidade. Um fardo pesado e, no entanto, se isso significa o retorno da terra aos nossos filhos e aos filhos, eu aceito com prazer.}
{305}{}{Como você pretende fazer isso? O que você está fazendo aqui?}
{306}{}{Deixe-me remover seu fardo. Permanentemente.}
{307}{}{Deve ser bom em sua dimensão. Vejo você mais tarde, Sr. Nutcake.}

# Start of Generic Recorded Dialog - Nãot being used!
{308}{}{Para o norte}
{309}{}{Para o nortewest}
{310}{}{Para o oeste}
{311}{}{Para o sudoeste}
{312}{}{Para o sul}
{313}{}{Para o suleast}
{314}{}{Para o leste daqui}
{315}{}{Para o norteeast}
{316}{}{sim}
{317}{}{Não}
{318}{}{Ouch}
{319}{}{(choro de dor)}
{320}{}{Por que está falando assim comigo?}
{321}{}{Eu não sei nada sobre isso.}
{322}{}{Você não é muito legal.}
{323}{}{Obrigado.}
{324}{}{Isso é bom.}
{325}{}{Isso não é bom.}
{326}{}{Tenho uma boa sensação sobre isso.}
{327}{}{Eu tenho um mau pressentimento sobre isso.}
{328}{}{Vocês são loucos.}
{329}{}{Do que você está falando?}
{330}{}{Todos estão loucos aqui?}
{331}{}{Deve haver outro caminho.}
{332}{}{Venha aqui.}
{333}{}{Eu não entendo.}
{334}{}{Eu não sei.}
{335}{}{Isso machuca.}
{336}{}{Isso realmente dói.}
{337}{}{Isso deve doer.}
# End of Generic Recorded Dialog - Nãot being used!
