{100}{}{Você vê uma brava fêmea.}
{101}{}{Você vê Blasphemous Bette, um mineiro da Morningstar Mine.}
{102}{}{Você vê uma mulher bem musculada eriçada com confiança.}
{103}{}{Caminetto, seus mineiros Kokoweef são todos shows e não vão.}
{104}{}{Vou mostrar para onde ir, Blasphemous Bette.}
{105}{}{Você não poderia me mostrar onde ir com um roteiro.}
{106}{}{Só porque eu não gostaria de chegar tão perto de você.}
{107}{}{Não se lisonjeie, você é pequeno.}
{108}{}{Você teria sorte para obter um runt em vez daquela máquina de perfuração que você normalmente usa.}
{109}{}{Bem, pelo menos, minha broca dura mais de trinta segundos.}
{110}{}{Não é de admirar que a maquinaria da Morningstar esteja sempre quebrando.}
{111}{}{Vou mostrar-te quebrado, com os meus punhos!}
{112}{}{Seus punhos? Sua respiração é ruim o suficiente.}
{113}{}{Eu não sei como você pode sentir o cheiro de seu próprio fedor de 3 semanas.}
{114}{}{Fedor? O inferno, olhando para você me causa dor suficiente.}
{115}{}{Você não conhece a dor, mas eu vou te ensinar algo.}
{116}{}{Você me ensina?}
{117}{}{Sim, está certo. Porque sua mãe certamente não.}
{118}{}{Você está falando sobre minha mãe agora? Isso não é criativo.}
{119}{}{Eu farei um melhor trabalho de criar um novo rosto para você. Aquele antigo com certeza não é muito para olhar.}
{120}{}{Você e o que exército?}
{121}{}{Apenas eu. Isso é tudo o que vai levar. Mas eu aposto-nos Morningstars pode levar você Woky Kokoweefs
 a qualquer momento.}
{122}{}{Acho que não. Kokoweef governa o poleiro aqui. Eu vou ter que aprender você isso.}
{123}{}{Vai ser difícil para você fazer isso quando eu vencê-lo inconsciente.}
{124}{}{Acha que você pode ter sorte então, hein?}
{125}{}{Eu não preciso de sorte para bater em você.}
{126}{}{Você vai me bater com sua gordura? Uh, agora eu estou com medo.}
{127}{}{Coloque ou cala a boca, pequeno camarão.}
{128}{}{Venha pegar um pouco, você adivinha.}
{129}{}{Agora, quem espera ter sorte?}
{130}{}{É isso mesmo, eu vou levá-lo para aquele.}
{131}{}{Quem diabos está nos observando?}
{132}{}{Alguém novo. Ei, isso é uma questão privada! Vamos vê-los!}
{133}{}{Fer uma vez que eu concorde com você. Pegue-os!}
{134}{}{Quem vai mina o ouro agora, huh, idiota?}
{135}{}{Eu poderia usar uma fodida férias.}
{136}{}{Eu tenho que compartilhar essa cárcere de cagado com esse idiota?}
{137}{}{Caminetto, seus dias de merda são numerados.}
{138}{}{Beija seu despedida por isso.}
{139}{}{Me tire o inferno daqui!}
{140}{}{Ei, foda, deixe-me sair daqui!}
{141}{}{Ei, xerife; Eu vou explodir você se você me deixar sair.}
{142}{}{Na próxima vez, vou resolver o seu hachinho.}
{143}{}{Que diabos você está olhando?}
{144}{}{O que você quer, dipshit?}
{145}{}{Eu não vou deixar você lutar entre si.}
{146}{}{Eu só queria saber o que está acontecendo aqui.}
{147}{}{Há um monte de merda neste bar e eu e meus mineiros da Morningstar vão empurrar para fora
 na rua. O maior turd ainda tem um nome - Caminetto.}
{148}{}{Por quê? O que começou?}
{149}{}{Entendo. Bem, não posso deixar você fazer isso. Você tem que dividi-lo agora.}
{150}{}{Basta olhar para o seu desculpa, o jeito coxo. Quem não gostaria de pisá-los de forma plana?}
{151}{}{Isso não é bom o suficiente. Não posso deixar você lutar.}
{152}{}{Bem, isso parece um problema, tudo bem. Eu não o culpo. Boa sorte.}
{153}{}{Que diabos você vai fazer sobre isso, seu maldito calcanhar?}
{154}{}{Vou matar a primeira pessoa a dar um soco.}
{155}{}{Eu só vou te perguntar muito bem. Então vou carregar minhas armas e aguardo alguns
 alvo prática.}
{156}{}{O xerife pediu-me para ajudá-lo enquanto ele estava preso com uma perna bum. Eu tenho que manter meu
 Palavra para ele.}
{157}{}{Sim? Que Marion é meio fofo. Ok, para ele, eu darei a esses pensamentos Kokoweef um cheque de chuva por um
 ass-kicking.}
{158}{}{Obrigado. Eu estava esperando que você visse as coisas desse jeito. Adeus.}
{159}{}{Você não acha que você é um tipo de cowboy asfalto quente. Eu não acho que eu gosto da sua merda
 atitude.}
{160}{}{Você não precisa gostar disso. Você vai caminhar comigo para a prisão ou eu vou arrastar o seu
 cadáver lá. Sua escolha.}
{161}{}{Oh, me desculpe. Eu certamente não queria ser rude. Eu vou sair agora. Adeus.}
{162}{}{Sim? Bem, eu digo o que. Eu irei se você encarcerar esse assentamento de Caminetto também.}
{163}{}{Você não está em condições de fazer negócios.}
{164}{}{Essa não é uma má idéia. Colocar algumas barras entre os dois deve arrepender as coisas um pouco.
 Venha, vocês dois.}
{165}{}{Você está sofrendo de uma inversão cranial-reta? Se você tentar qualquer coisa, todos nós vamos pular você apenas
 para um aquecimento. Depois, haverá sangue. Pense que o xerife goste do trabalho que você está fazendo então?}
{166}{}{Não, acho que ele não faria.}
{167}{}{Não é importante para mim. Não será * o meu * sangue derramado.}
{168}{}{Bem, talvez eu possa usar um poderoso descanso. Tenho trabalhado ultimamente com o meu maldito traseiro. (ao
 outros) quebrar, gang. Volto no trabalho amanhã.}
{169}{}{Boa escolha.}
{170}{}{Não se preocupe; Estou trazendo Caminetto para manter sua empresa. Certo, Caminetto?}
{171}{}{Você simplesmente não conseguiu, não é? Você tenta misturá-lo com nós e eu e aquilo
 Weiner-Dick Caminetto vai se deitar em você.}
{172}{}{Então eu vou ter que prender você e Caminetto.}
{173}{}{Então eu vou ter que matar tanto você quanto Caminetto.}
{174}{}{Hmm, acho que sou necessário em outra parte da cidade. Imediatamente. Adeus.}
{175}{}{Eu acho que você é mais brilhante do que parece. Mas então você deve ser; você está ereto. Basta executar em
 casa para mamãe e dizer que não havia nada que você tivesse coragem suficiente para fazer.}
{176}{}{É isso aí. Já tive o suficiente da sua boca. Uma última chance: vá em silêncio ou eu vou separar você.}
{177}{}{Talvez eu faça isso. Eu não quero machucar ninguém. Adeus.}
{178}{}{Eu vejo como isso está acontecendo, seu pequeno pedaço de merda. Tudo bem, você pode me levar, e Caminetto também.
 (para Caminetto) Certo, meu pequeno fuckface?}
{179}{}{Isso é mais parecido com isso.}
{180}{}{Não. Tarde de mais agora. Eu vou ter que abrir uma lata de grito sobre vocês dois.}
