{100}{}{Você vê uma mulher bastante desgastada.}
{101}{}{Você vê Fannie Mae, uma das apresentadoras do Salão Malamute.}
{102}{}{Você vê uma mulher que mostra mais desgaste da quilometragem do que de anos.}
{103}{}{(Fannie parece distintamente insalubre enquanto ela balança em sua direção) Ei, amante. Estou sentindo um
 Pouco tempo abaixo. Quer me dar algum dinheiro para um impulso rápido? Posso valer a pena
 enquanto. (Sorrisos)}
{104}{}{(Fannie parece distintamente insalubre enquanto ela balança em sua direção) Ei, irmã. Você pode poupar
 Alguns dólares para ajudar uma garota que está com a sorte? Até que eu volte a colocar meus pés novamente.}
{105}{}{(Fannie não parece muito bem) Ei, amigo. Pronto para uma diversão com Fannie?
 Meio preço para você, amante. Onde eu coloquei meu Jet?}
{106}{}{(Fannie não parece muito bem) Ei, senhora, poupe algum dinheiro? Ou um pouco o Jet Fuel
 até?}
{107}{}{Fannie, você parece um inferno. Por que você não demora o Jet por um tempo?}
{108}{}{Eu acho que você já desfrutou o suficiente da minha caridade, e não parecei ajudá-lo.}
{109}{}{Você já teve o suficiente por enquanto.}
{110}{}{Por que você não consegue dormir?}
{111}{}{Jet é o único que me faz voar. ./~Come voe comigo ./~ Dê-me um pouco de algo
 Especial, won'tcha?}
{112}{}{Oh, você está cheio de ótimas idéias agora, você não está. Bem, eu não preciso de você. Muita gente
 Ainda quer pagar os encantos de Fannie. Se você não me dará dinheiro para o Jet, então saia do meu
 vista.}
{113}{}{Eu tenho algo que deve curá-lo dessa confiança em Jet.}
{114}{}{Encontre-se outro otário, Fannie. Adeus.}
{115}{}{Você vai se matar se você continuar assim. Eu não quero assistir você fazer isso.
 Adeus.}
{116}{}{Você não é uma visão?}
{117}{}{Fannie não flop para nenhum idiota.}
{118}{}{Volte com algum dinheiro e talvez Fannie possa aprender com você alguma coisa.}
{119}{}{Você não é a ferramenta mais afiada no galpão, está?}
{120}{}{Você é tão inteligente como isca. Não é?}
{121}{}{Uma cura? O que, você está louco? Parece que quero curar? Você quer me fazer sentir melhor,
 açúcar? Me dê mais Jet.}
{122}{}{Bem, acho que um pouco mais para te atrapalhar não faria mal. Aqui está um Jet.}
{123}{}{Você já teve mais do que suficiente Jet. A última coisa que eu preciso fazer é assistir a outro Jet dependente.
 Adeus.}
{124}{}{Se eu tivesse um Jet, eu estaria usando isso sozinho. Adeus.}
{125}{}{Sim, é isso que eu preciso. Oh sim. Que correria. Mmmmm ...}
{126}{}{Bem, acho que vou deixar você se divertir agora. Adeus.}
{127}{}{Parece que você está realmente Jetted-up, agora. Eu te vejo por aí. Adeus.}
{128}{}{Ei, marinheiro. Venha aqui com frequência? Você vem aqui para visitar com Fannie Mae?}
{129}{}{Olá irmã. Procurando por trabalho?}
{130}{}{Uh, sim. Estou aqui para visitá-lo.}
{131}{}{Trabalhos? Que tipo de trabalho?}
{132}{}{Uh, eu só estava olhando ao redor. Adeus.}
{133}{}{Bem, você não é doce. Atuando tão tímido e tudo mais. Vai custar-lhe US $ 60 para uma visita com
 Eu, sugah.}
{134}{}{Talvez você dure um pouco mais desta vez, querida. Você obterá mais do que seus US $ 60 por esse valor.}
{135}{}{Agradável e lento, bebê. Vou te mostrar um bom momento para os seus US $ 60.}
{136}{}{US $ 60, hein? Parece um bom preço para mim. Aqui está o meu dinheiro.}
{137}{}{Obrigado pela oferta, mas talvez outra vez seja melhor. Adeus.}
{138}{}{$ 60? Eu não acho que eu quero visitá-lo se isso vai custar tanto. Adeus.}
{139}{}{Você foi tão legal comigo. Eu senti que você realmente quis dizer algo quando você fez isso. (Soluço) Eu
 Com certeza gostaria de ser assim o tempo todo.}
{140}{}{Bem, quando você está comigo, é.}
{141}{}{Você sabe como falar a conversa.}
{142}{}{Eu não quero mais fazer isso. Eu, meu cara, vou sair daqui e viver a vida
 direto. Assim que eu puder pagar a Lou.}
{143}{}{Pagar Lou?}
{144}{}{Ei, eu já lhe dei dinheiro. Do que você está falando?}
{145}{}{Sim, bem ... Eu devo dinheiro a Lou e não posso sair até eu pagar. Mas assim que eu fizer
 (Cheiro) Eu vou levar meu namorado e ficar tão longe dessa vida como eu posso. Se eu pudesse apenas
 Levante um pouco de massa extra.}
{146}{}{Quanto dinheiro extra você precisa para pagar a Lou?}
{147}{}{Seu namorado não pode ajudá-lo a sair da dívida?}
{148}{}{Essa é uma história triste, mas você deve ter o dinheiro que você precisa em breve. Contanto que você mantenha seu
 De volta ao colchão, isto é. Adeus.}
{149}{}{Tudo o que eu preciso agora é de US $ 200 e estou claro. Meu homem e eu estamos fora daqui, limpo e gratuito. Não
 Mais estranho, sujo, pessoas me tapando durante todo o dia e a noite. Uh, não quis dizer nenhuma ofensa.}
{150}{}{Nenhum tomado. Na verdade eu não sou palhaço, não é? De qualquer forma, eu poderia pagar o seu caminho para fora daqui. Aqui estão $ 200.}
{151}{}{Parece triste, tudo bem. Bem, acho que é melhor você ficar ocupado então. Adeus.}
{152}{}{Oh, obrigado, obrigado. Eu não pensei que havia alguém desse tipo fora do meu
 Sonhos. Você é o melhor. Obrigado novamente. Ei, quer um brinde? Na casa?}
{153}{}{Por que com certeza, Fannie. Acho que vou levá-lo a essa oferta.}
{154}{}{Isso não é realmente necessário, Fannie. Apenas use o dinheiro para sair desta vida. Adeus.}
{155}{}{Ele realmente quer, mas ele apenas está passando como mineiro. Continuamos esperando que ele faça um grande
 Greve, mas isso ainda não aconteceu. E na semana passada, um raio caiu sobre ele e quebrou a perna, então ele não pode
 trabalhos. Agora eu tenho que dar-lhe o pouco dinheiro que posso poupar até que ele melhore.}
{156}{}{Parece que vocês dois tiveram alguma má sorte. Quanto você disse que você precisa?}
{157}{}{Obrigado novamente. Não posso esperar para contar ao meu cara. Estaremos fora daqui assim que a perna dele
 Cura-se.}
{158}{}{Isso foi muito obrigado, Fannie. É melhor eu sair daqui enquanto eu ainda posso andar.
 Seja bem-vindo. Adeus.}
{159}{}{Vai ser uma perda para a profissão ver você ir, Fannie. Adeus.}
{160}{}{Olá. Você quer passar algum tempo com a Fannie?}
{161}{}{Não lhe dei dinheiro para que você pudesse parar de fazer isso?}
{162}{}{Claro, parece bom para mim. Bom, eu peguei você antes de você sair.}
{163}{}{Bem, sim ... mas resulta que eu devo Lou mais do que eu pensava.}
{164}{}{Quanto mais?}
{165}{}{Já ouvi o suficiente disso. Adeus.}
{166}{}{Uh, eu sei, e estou muito agradecido ... mas acho que eu devia a Lou mais do que eu pensava. eu preciso de mais
 dinheiro.}
{167}{}{Não posso acreditar! Quanto mais dinheiro você precisa para sair disso?}
{168}{}{Bem, você tem tudo o que você quer de mim. Adeus.}
{169}{}{Está tudo bem, querida. Você já ajudou o suficiente. (Cheiro) Eu só preciso de mais US $ 150, no entanto.}
{170}{}{Bem, acho que se é tudo o que você precisa. Mas é isso. Quero dizer.}
{171}{}{Sim claro. Estou fora daqui. Adeus.}
{172}{}{Ei, você voltou. Procurando um pouco de diversão, ou você voltou para me dar algum dinheiro?
 Para Lou?}
{173}{}{Só aqui por algum divertimento desta vez, Fannie. Veremos como vai.}
{174}{}{Quanto você precisa para Lou?}
{175}{}{Apenas parando, Fannie. Adeus.}
{176}{}{Sempre é bom ter algum negócio de repetição. Para você, eu vou mudar os lençóis.}
{177}{}{Você sabe como fazer um cara se sentir especial. Obrigado.}
{178}{}{Uh, acho que mudei de ideia. Até você, Fannie. Adeus.}
{179}{}{Você sabe, back-floppin 'work. Com uma aparência como a sua, eu aposto que você poderia fazer uma boa vida.}
{180}{}{Você sabe, back-floppin 'work. Mesmo do jeito que você olha, você poderia ganhar algum dinheiro. Os mineiros
 Não é muito particular, você sabe.}
{181}{}{Você acha? Hmm, talvez eu devesse.}
{182}{}{Não acho que seja para mim. Adeus.}
{183}{}{Bem, a costa ajuda se o nariz não está interessado. Esses mineiros não gostam muito de sabão e água.}
{184}{}{Mesmo? Talvez não seja para mim, afinal. Obrigado pela oferta, no entanto. Adeus.}
{185}{}{Eu não sei como você pode suportar isso, mas então eu acho que você não. Stand, isto é. Adeus.}
