{100}{}{Você vê alguém vestindo uma armadura de combate.}
{101}{}{Você vê um guarda.}
{102}{}{Ele parece estar aqui esperando que algo aconteça.}
{103}{}{Sim sim. Mova-se.}
{104}{}{Você se certifica de que é bom com o Sr. Buster, então não temos que desperdiçar ammo.}
{105}{}{Estou aqui para chutar bunda e mastigar chiclete. Bom para você, eu tenho uma vara a esquerda.}

{106}{}{Que diabos você está olhando? Golpe.}
{107}{}{Ei, não estou dentro disso. Certifique-se de manter uma boa distância de mim.}
{108}{}{Sim, é verdade, venha para papai. Por que não nos encontramos mais tarde para uma bebida?}
{109}{}{Querida, dormi com um brahmin antes de te olhar duas vezes.}

{110}{}{Apenas compre algo e saia daqui.}
