{100}{}{Você vê um pequeno homem manchado de gordura.}
{101}{}{Você está olhando para Buster, o homem da arma.}
{102}{}{As roupas deste homem são esfarrapadas e ele tem armas em todas as mãos, braços e rosto. Ainda assim, ele parece bastante alegre.}
{103}{}{Ei, bem-vindo ao Fine Emporium of Armament do Buster! Eu sou Buster e não há mais ninguém. Tenho alguns bons produtos aqui e nas minhas prateleiras. Confira. Estou pronto para lidar.}
{104}{}{Eh, de volta? O que posso fazer para você?}
{105}{}{Algo mais?}
{106}{}{Quer arma.}
{107}{}{O que você tem?}
{108}{}{Talvez você possa me arranjar algo especial?}
{109}{}{Eu tenho algumas perguntas}
{110}{}{Adeus.}
{111}{}{Uma boa escolha!}
{112}{}{Bem, você conseguiu roubar lá, parceiro.}
{113}{}{Para não apressar você, estranho, mas eu tenho trabalho para fazer.}
{114}{}{Claro, estranho, o que você quer saber?}
{115}{}{Conte-me sobre NCR}
{116}{}{Qual é o acordo com a Merk?}
{117}{}{O que você pode me falar sobre Frank Westin?}
{118}{}{Estou à procura de uma reunião com Old Man Carlson. Conheça alguém que possa me ajudar?}
{119}{}{Você tem um GECK?}
{120}{}{Isso é muito estranho, mas não sou uma instituição de caridade.}
{121}{}{Talvez. Só poderia ter um alcance de rifle Triveld x10 - caberia bem em um rifle de caça, se alguém estivesse interessado. Deixe-o ir barato - $ 500.}
{122}{}{Ei, você já me limpou.}
{123}{}{Claro, é um acordo}
{124}{}{Não, obrigado.}
{125}{}{Nova República da Califórnia - é isso que é. O presidente Tandi e o grupo dizem que estão tentando reconstruir os velhos tempos; Eu acho que eles estão apenas tentando agarrar tudo o que podem. Inferno, não recebi nenhuma queixa com eles - os velhos tempos são todos antes do meu tempo. Eles são um pouco um grupo de prissy, no entanto - não gostam de escravos, jogos de azar, nem outras coisas. É por isso que eu coloco aqui. Não gosto de regras - nunca tenha.}
{126}{}{Entendo.}
{127}{}{Adeus.}
{128}{}{Eu não toco com o Sr. Merk e não paga para ir a fofocar sobre ele. Você recebeu perguntas, pergunte sobre ele no Rawhide.}
{129}{}{Entendo.}
{130}{}{Adeus.}
{131}{}{Frank Westin? Você quer dizer aquele cara do Congresso? Obteve-se espalhado pelo oeste da cidade. brahmin man - grande roda na Stockman's Association. Ele sempre está procurando mãos, se você está querendo trabalho.}
{132}{}{Entendo.}
{133}{}{Adeus.}
{134}{}{Engraçado você vai perguntar isso depois do que aconteceu com Frank Westin. Não que eu soubesse, mas há um companheiro - Merk - no Rawhide que pode ser capaz de ajudá-lo.}
{135}{}{Entendo.}
{136}{}{Adeus}
{137}{}{Essa é uma das importações anteriores à guerra? Deixe-me adivinhar, munição de 14mm? Não, não tem um.}
{138}{}{Entendo.}
{139}{}{Adeus}
{140}{}{Olha, não posso fazer isso em nada além de um rifle de caça. É assim que o monte é construído, entende?}
{141}{}{Entendo.}
{142}{}{Adeus.}
{143}{}{A junção está fechada. Bug off.}
{144}{}{Deus! Volte para uma hora decente, você vai?}
{145}{}{Volte quando estou aberto - e feche a aba da tenda atrás de você.}
{146}{}{Estou fechado.}
{147}{}{Olhe, apenas saia ou o Sr. .45 vai ficar infeliz!}
{148}{}{Movimento errado, estranho.}
{149}{}{Aqui está o que eu tenho nesta prateleira. Se você precisar de mais alguma coisa, certifique-se de verificar as outras prateleiras também.}
