{100}{}{Você vê um garotinho cheio de nariz.}
{101}{}{É o filho do vice-presidente Carlson}
{102}{}{Parece um pequeno arruinado. Gordura também.}
{103}{}{O vice-presidente do meu pai, Carlson, então é melhor você me tratar bem! Quem é Você?}
{104}{}{[Nome do jogador]}
{105}{}{Sou um dos guardas do seu pai.}
{106}{}{Onde está o seu pai?}
{107}{}{Veja esta faca? Eu destruí as crianças bem mais do que você.}
{108}{}{Eu sou seu pior pesadelo, vômito.}
{109}{}{Desculpe garoto, estou ocupado.}
{110}{}{? Esse é um nome maldito. Você tem um nome estúpido! Nome estúpido!}
{111}{}{Então você tem que ser muito legal para mim ou eu vou contar ao meu pai.}
{112}{}{Ah Que tal eu (sussurro).}
{113}{}{Certo. Oh garoto.}
{114}{}{Ele está dentro. Em seu escritório. Ele está sempre lá.}
{115}{}{Onde está o escritório dele?}
{116}{}{OK. Obrigado.}
{117}{}{Pelo tanque de água. Eu toco lá às vezes. Eu olho para ele enquanto ele está trabalhando.}
{118}{}{Você é um pequeno pirralho irritante, não é?}
{119}{}{Obrigado garoto, você foi uma grande ajuda.}
{120}{}{Você não é um homem legal, você é um homem ruim! Eu vou dizer ao meu pai!}
{121}{}{Ei, é você de novo. O que está fazendo?}
{122}{}{Vá perguntar ao seu pai se eu posso vê-lo.}
{123}{}{Diga a você pai que tenho notícias sobre o Sr. Bishop. Você consegue lembrar disso?}
{124}{}{Fnuh.}
{125}{}{Você é um cérebro caca! Poop cérebro!}
{126}{}{OK.}
{127}{}{Notícias sobre o Sr. Mishop. OK?}
{128}{}{Bom o bastante.}
{129}{}{Papai diz que não pode te ver.}
{130}{}{Eu disse a papai isso. Eu acho que ele não gosta de você.}
{131}{}{Papai diz que você pode entrar na casa.}
{132}{}{Eu disse a papai que você era um homem ruim.}
{133}{}{Isso mesmo, eu sou o homem do boogy! E eu vou te comer.}
{134}{}{Você me entendeu errado.}
{135}{}{Eu não deveria falar com você mais.}
{136}{}{Meu pai está morto. Por que você não o salvou?}
