{100}{}{Ainda outro guarda. Alguém deve criá-los, já que todos se parecem.}
{101}{}{Ainda é um guarda. Provavelmente não gosta de você.}
{102}{}{Você olha para ele de perto e você está convencido de que ele é um guarda.}
{103}{}{Você não está autorizado a estar aqui.}
{104}{}{Posso ver o seu passe?}
{105}{}{Esta é propriedade do governo. Avança, estranho.}
{106}{}{Então você é o novo cara, hein?}
{107}{}{Se você não conversou com Carlson, é melhor você fazer isso.}
{108}{}{O Sr. Carlson está esperando por você.}
{109}{}{O Sr. Carlson irá vê-lo agora.}
{110}{}{Espero que isso seja importante. O Sr. Carlson é um homem ocupado.}
{111}{}{Ele está dentro. Eu sugeriria não ficar muito tempo.}
