{100}{}{Ainda outro guarda. Alguém deve criá-los, já que todos se parecem.}
{101}{}{Ainda é um guarda. Provavelmente não gosta de você.}
{102}{}{Você olha para ele de perto e você está convencido de que ele é um guarda.}
{103}{}{Você não está autorizado a estar aqui.}
{104}{}{Posso ver o seu passe?}
{105}{}{Esta é propriedade do governo. Avança, estranho.}
{106}{}{Você é o único que Merk chamou? Ok, deixe-o passar, meninos.}
{107}{}{Isso controla. Deixa de lado, meninos.}
{108}{}{Ok, você está claro. Abra o portão, meninos.}
{109}{}{Você é o único que Merk chamou? Ok, deixe-a passar, meninos.}
{110}{}{Estou de serviço. Não há tempo para socializar.}
{111}{}{Ei, bons sapatos.}
{112}{}{Você deve seguir seu negócio.}
