{100}{}{Você vê um personagem de fraude.}
{101}{}{Esse cara não deveria estar aqui.}
{102}{}{Ei, é um personagem de fraude.}
{103}{}{Ei, isso doeu.}
{104}{}{Olá o que você gostaria de acontecer.}
{105}{}{Definindo as bandeiras de Westin.}
{106}{}{Definir Aceitar Snuffing westin?}
{107}{}{Desmarque Aceite Snuffing Westin.}
{108}{}{Define Westin Dead.}
{109}{}{Desligue Westin Dead.}
{110}{}{Set Westin Cancel Snuff}
{111}{}{Dispare Westin Cancel Snuff.}
{112}{}{Defina Westin Drogas Conhecidas.}
{113}{}{Desconectado Westin Drogas conhecidas.}
{114}{}{Set Westin Fail}
{115}{}{Desconectado Westin Fail.}
{116}{}{Set Westin Complete}
{117}{}{Unset Westin Complete.}
{118}{}{Defina Westin Snuff Conhecido.}
{119}{}{Desconhece Westin Snuff conhecido.}
{120}{}{Definindo as Bandeiras de Carlson.}
{121}{}{Defina Carlson Accept Snuff.}
{122}{}{Unset Carlson Accept Snuff.}
{123}{}{Defina Carlson Dead.}
{124}{}{Unset Carlson Dead.}
{125}{}{Defina Carlson Security Duty.}
{126}{}{Unset Carlson Security Duty.}
{127}{}{Defina Carlson Cancel Snuff.}
{128}{}{Unset Carlson Cancel Snuff.}
{129}{}{Defina Carlson Complete.}
{130}{}{Unset Carlson Complete.}
{131}{}{Defina Carlson falhar.}
{132}{}{Unset Carlson Fail.}
