{100}{}{Você vê uma pessoa vestindo o uniforme da polícia NCR.}
{101}{}{Um policial.}
{102}{}{A julgar pelo rosto insensível, não espere muita piedade aqui.}
{103}{}{Coloque sua arma longe - AGORA!}
{104}{}{Mais estranho, nós temos uma política de não armas nesta cidade. Coloque sua arma longe.}
{105}{}{Afaste a arma e ninguém vai se machucar.}
{106}{}{É depois do toque de recolher, estranho. Por que você não dirige para casa?}
{107}{}{Mova-se agora. Não há nada para ver aqui.}
{108}{}{A noite não é um bom momento para passear pelas ruas.}
{109}{}{Bom dia, estranho. Novo na cidade?}
{110}{}{Mova-se agora. Não há nada para ver aqui.}
{111}{}{Estou em missão. Se houver problemas, você pode tentar denunciá-lo ao xerife.}

{112}{}{Ei, pare de mexer com isso.}
{113}{}{Afaste-se disso.}
{114}{}{Isso não deve ser adulterado.}
{115}{}{Se você não parar de enganar com isso estou autorizado a atirar em você.}
