{100}{}{Você vê uma jovem, muito garota, vestida com macacão de trabalho.}
{101}{}{É Dorothy, o engenheiro da cidade.}
{102}{}{De toda a gordura e sujeira nela, ela é um tipo de ferramenta prática, especialmente porque o botín de manutenção segue-a em todos os lugares.}
{103}{}{Oh meu Deus, alguém precisa fazer algo! O que eu faço? Preciso de ajuda rápida.}
{104}{}{Hã? Gug?}
{105}{}{O que está acontecendo?}
{106}{}{Você vem. Pare o homem ruim. Pare com ele sem quebrar máquina. OK?}
{107}{}{OK.}
{108}{}{Não, não venha.}
{109}{}{Oh, deus, é Jack. Ele está ameaçando explodir a usina. Não há tempo, você tem que detê-lo para mim. Você pode fazer isso, não pode?}
{110}{}{Pare de perder tempo. Ligue.}
{111}{}{Não é meu trabalho. Vá procurar alguém.}
{112}{}{Ouça - Jack está dentro. Ele está chateado com sua ex-esposa. As coisas não foram boas para ele ultimamente. Ele diz que ele tem uma bomba. Se assim for, provavelmente está ao lado do dínamo gerador. Olha, veja se você pode conversar com ele, mas o que quer que você não deixe a bomba disparar!}
{113}{}{Como eu deveria fazer isso?}
{114}{}{Não se preocupe, estou com isso.}
{115}{}{Eu não sei! Eu sou apenas o engenheiro da cidade. Você descobriu isso!}
{116}{}{Porcaria! Ele danificou a unidade central. Deve ser corrigido antes que as coisas realmente vão para o inferno. Você é bom em reparar coisas?}
{117}{}{Urrgh.}
{118}{}{Sim.}
{119}{}{Não}
{120}{}{O que eu estava pensando?}
{121}{}{Olhe, faça o que puder com o gerador. Eu tenho que estabilizar o núcleo. Você pensa que você tem cerca de 30 segundos. Depois disso, será muito tarde. Vamos, Toto.}
{122}{}{Droga! Então fique de volta. A menos que eu tenha muita sorte, tudo vai explodir. Vamos, Toto.}
{123}{}{Você corrigiu isso? Sem partes? Isso é incrível! Onde você aprendeu a fazer isso?}
{124}{}{Huh-huh!}
{125}{}{Apenas a mão é tudo.}
{126}{}{I get it. You're one of those moron types - what do they call them? Idiot savants. Well look, idiot or not, you've earned a reward. RE-WARD - you. I give you pretty books.  You see. Get money. Good... Nãot like you can read, after all.}
{127}{}{Olha, não é muito, mas tenho alguns livros - manuais de tecnologia antigos. Sao seus. Pegue eles.}
{128}{}{Olá, Toto. É o estranho que nos ajudou. Obrigado, senhor.}
{129}{}{Crap! The whole grid's down. This is going to take forever to fix. Não time to talk. Come on, Toto.}
{130}{}{Olha, eu não o culpo pelo que aconteceu, mas não estou com um humor sincero.}
{131}{}{Você o matou! Quero dizer, você precisou matá-lo? Não havia outra maneira?}
{132}{}{Sim.}
{133}{}{Não.}
{134}{}{Você deveria ter tentado então, em vez de simplesmente matá-lo. Saia daqui, seu monstro!}
{135}{}{É terrível. Pergunto-me o que o fez fazer isso? A cidade lhe deve agradecer. Olha, não é muito, mas aqui estão alguns manuais que recebi. Talvez você possa vendê-los ou algo assim.}
{136}{}{Não fale comigo, você está matando suínos.}
{137}{}{Não é possível conversar, estranho. Nome é Dorothy, engenheira da cidade, e isso é Toto. Tenho que correr.}
{138}{}{Você não tem um modulador de espaço de illudium Q-38, não é? Não pensou assim.}
{139}{}{Você falou com isso? Isso é incrível! A cidade deve-lhe grande, senhor. Olha, não é muito, mas aqui estão alguns manuais que recebi. Talvez você possa vendê-los ou algo assim.}
{140}{}{Eu só quero que você saiba que ainda estou impressionado com o que você fez com Jack. Eu e Toto temos que correr agora. "Tchau!}
{141}{}{Porcaria! Recebi uma palavra de conselho: FUNCIONE!}

{142}{}{Olá, Toto. É o estranho que nos ajudou. Obrigado, senhorita.}
{143}{}{Você falou com isso? Isso é incrível! A cidade te deve grande, irmã. Olha, não é muito, mas aqui estão alguns manuais que recebi. Talvez você possa vendê-los ou algo assim.}

{144}{}{Não perca tempo! Ele é sério.}
{145}{}{Você precisa fazer algo agora mesmo!}
{146}{}{Não fique parado lá - pare com ele!}
{147}{}{Apenas saia daqui, brahmin dung.}
{148}{}{Não fale comigo, covarde.}
{149}{}{Que uso é você?}
