{100}{}{Você vê um velho e amável companheiro.}
{101}{}{É Doc Jubileu.}
{102}{}{Ele é um homem velho com uma barba branca de neve e um olhar levemente vazio.}
{103}{}{Sou Doc Jubileu. O que há de errado, jovem?}
{104}{}{O que há de errado, jovem?}
{105}{}{Me machucou.}
{106}{}{Eu preciso de um doutor.}
{107}{}{Você não pode apenas pegar algumas pílulas ou algo assim e parar de me incomodar com este twaddle?}
{108}{}{Inferno, você está quase sangrando.}
{109}{}{Eu não sei. Não pense que eu possa salvá-lo. Podemos ter que cortar essa perna.}
{110}{}{Você está brincando.}
{111}{}{Ha-ha.}
{112}{}{Você está, filho.}
{113}{}{Novamente.}
{114}{}{Obrigado, Doc. Talvez você possa me ajudar com algumas respostas.}
{115}{}{Adeus.}
{116}{}{Vai custar-lhe US $ 50.}
{117}{}{Apenas me cure.}
{118}{}{Não vou ficar aqui.}
{119}{}{Você faz melhor.}
{120}{}{Eu vou agora.}
{121}{}{Não. Nunca brinque. Melhor eu cortar essa perna antes que a gangrena se ajeite.}
{122}{}{De jeito nenhum, você está cortando tudo, entende?}
{123}{}{É isso mesmo, vou embora.}
{124}{}{Bem, se festejar, não me culpe.}
{125}{}{Eu não administrai um hospital de caridade. Você precisará receber algum dinheiro antes de fazer qualquer coisa.}
{126}{}{Então o que posso fazer por você?}
{127}{}{Atire.}
{128}{}{Vault 13?}
{129}{}{Saiba onde eu poderia encontrar o Vault 13?}
{130}{}{Ouvi alguém dizer que o Sr. Westin não está bem. Isso é verdade? Estou preocupado que algo possa acontecer com ele. Ele me deve dinheiro.}
{131}{}{Há esse colega de Saltbeef diz que você roubou um mapa dele. Qual é o negócio?}
{132}{}{Estou à procura de trabalho. Sabe de qualquer?}
{133}{}{Doc, você não saberia nada sobre um grupo que está lutando contra esses escravos do mal, você faria?}
{134}{}{Bem, você não deveria se preocupar, filho. Enquanto ele não taxar seu sistema, ele provavelmente irá superar todos nós. - Claro que é que ele se importaria com meu médico ou seu remédio.}
{135}{}{Bem, é bom saber. Há algo mais que eu queria saber.}
{136}{}{Obrigado, doc.}
{137}{}{Esse velho bêbado! O único que eu já tirei dele foi minha pintura "Velvet Elvii" - em vez de dinheiro.}
{138}{}{A Velvet Elvii? Eu poderia ver isso?}
{139}{}{Não é exatamente um mapa, hein? Bem, deixe-me escolher seus cérebros sobre outras coisas.}
{140}{}{Bem, eu tenho que continuar.}
{141}{}{Não me ouvi falar disso desde que o velho Saltbeef foi trazido aqui. Insolação. Queimado com febre durante três dias, todo o tempo ranting como ele encontrou Vault 13, a mãe da mãe.}
{142}{}{Filão?}
{143}{}{Então, onde é?}
{144}{}{Onde cofre?}
{145}{}{Não poderia te dizer. Saltbeef sempre afirmou ter um mapa, mas ninguém nunca viu.}
{146}{}{Saltbeef?}
{147}{}{Peça mais.}
{148}{}{Bem, isso é mais do que o que eu tinha antes.}
{149}{}{O grande. Saltbeef é um antigo prospector de urânio - com mais precisão, um bebado. Vive o Westin espalhar estes dias.}
{150}{}{Outra pergunta...}
{151}{}{Obrigado pela história.}
#CMH changing per Fergus.. Now you have to pay 1000 or steal the painting off of him.
{152}{}{Bem, eu realmente estava esperando conseguir algum dinheiro para isso. Eu vou deixar isso por $}
{153}{}{Talvez mais tarde, outra pergunta ...}
{154}{}{Talvez mais tarde, eu tenho que ir.}
{155}{}{Saltbeef é um antigo prospector de urânio. Vive o Westin espalhar estes dias.}
{156}{}{Outra pergunta...}
{157}{}{Obrigado pela história.}
{158}{}{Você vai falar com o presidente Tandi. Ouvi dizer que ela está procurando por um tipo especial de pessoa.}
{159}{}{Outra pergunta...}
{160}{}{Obrigado.}
{161}{}{Eu poderia ... Existe um grupo contra a escravidão e ... bem, a maioria dos outros vícios também. Às vezes, você pode encontrá-los na grande loja, trabalhando em algum automóvel.}
{162}{}{Outra pergunta...}
{163}{}{Obrigado.}
{164}{}{Ei, tire as mãos disso, punk!}
{165}{}{Cuidado lá! Apenas leva pequenas coisas para se expor.}
{166}{}{Coloque isso de volta! Você poderia se machucar seriamente com essas coisas.}
{167}{}{Esses medicamentos são para o Sr. Westin, não você. Coloque-os de volta.}
{168}{}{Afaste-se disso. Tenho que ter cuidado, veja. Não quereria que o Sr. Westin obtivesse os medicamentos errados agora.}
{169}{}{Assista! Acabei de medir a dose do Sr. Westin.}

{170}{}{Sou Doc Jubileu. O que há de errado, senhorita?}
{171}{}{O que há de errado, senhorita?}
{172}{}{Você está, senhorita.}
{173}{}{Bem, você não deveria se preocupar, senhorita. Enquanto ele não taxar seu sistema, ele provavelmente irá superar todos nós. - Claro que é que ele se importaria com meu médico ou seu remédio.}
{174}{}{Certo. Aqui está o $}
{175}{}{Obrigado, tentei retirar o dinheiro do Saltbeef, mas esse bum nunca teve nenhum.}
{176}{}{.}
