{100}{}{As criaturas vieram do nordeste. Não deve ser difícil rastreá-los de volta ao seu ninho. (Exit Grid para o nordeste).}
{101}{}{Uau, isso é seguro é chato. Espero que algo aconteça.}
{102}{}{Olha as horas...}
{103}{}{Hmmm, isso é chato.}
{104}{}{Zzzz ... Zzz ... huhh, wah ...?}

{105}{}{Olhe - brahmin da guarda humana.}
{106}{}{Gruthar diz que vamos. Não feriu humanos.}

{107}{}{Veja. isto}
{108}{}{. Nós vamos.}

{109}{}{Isso é estranho. Coisas ruins falam?}
{110}{}{Falando na morte? Isso é estranho...}
