{100}{}{Você vê um cara de aparência vermelha e amigável.}
{101}{}{É Duppo. Ele dirige a Stockmen's Association.}
{102}{}{Ele é um companheiro viciado e com o rosto cada vez mais corado e choque de cabelo loiro fino. Ele caminha com uma leve coxa.}
{103}{}{Saudações, estranho. Não conheço essas partes, então isso significa que você não é um fazendeiro. Você vem procurando trabalho ou você está aqui para comprar?}
{104}{}{O que será, estranho?}
{105}{}{Trabalhos.}
{106}{}{Comprar.}
{107}{}{Bem, meu nome é Duppo. Suprimentos rurais e aluguel de salões, tudo feito aqui. Tenho que dizer que você não parece um perfurador de brahmin. Como você está com uma arma?}
{108}{}{Ainda procurando por alguns guardas, se você estiver interessado.}
{109}{}{Heh. Matar.}
{110}{}{Bom o bastante.}
{111}{}{Não estou na violência.}
{112}{}{Bem, aqui está o meu estoque. Certifique-se de olhar para todas as minhas tabelas para obter mais inventário. Se você não gosta do que recebi, pegue sua bunda para essa banca Buster. Claro, ele vai te roubar cego.}
{113}{}{Bem, parece que você vai fazer. Estamos à procura de guardas para um brahmin dirigido até Redding. Pay $ 2000 menos qualquer estoque perdido antes de chegar lá. Se você estiver interessado, fique no portão do lugar de Westin amanhã. Se você não mostrar, você não vai. Combinado?}
{114}{}{Eu venho.}
{115}{}{Não como. Eu não faço.}
{116}{}{Parece bom.}
{117}{}{Nah, eu não quero ir para Redding.}
{118}{}{Bem, então não há trabalho para você aqui. O campo é um lugar difícil. Nenhum lugar para fracos, estranho.}
{119}{}{Algo mais?}
{120}{}{Bom o bastante. Anything else, stranger?}
{121}{}{Comprar.}
{122}{}{Trabalhos.}
{123}{}{Wes-tin?}
{124}{}{Estou procurando por Roger Westin. Já ouviu falar dele?}
{125}{}{Onde posso encontrar o Frank Carlson?}
{126}{}{Carl-filho?}
{127}{}{Adeus.}
{128}{}{Você quer dizer Roger Weston? Oeste da cidade.}
{129}{}{Um dos acionistas neste lugar. Oeste da cidade. Eu não acho que ele está procurando por mãos do rancho, se é isso que você está pensando.}
{130}{}{Ele é o vice-presidente; Eu sei disso. Caso contrário, não posso te dizer nada, de verdade. Gasta todo seu tempo na Casa Presidencial. Quase nunca sai, especialmente agora, o que com todos os problemas que temos tido.}
{131}{}{Carlson. Grande chefe. Vive na casa grande. Isso tudo.}
{132}{}{Desculpe - acabou a temporada de gado. Volte em alguns meses.}

{133}{}{Sim, sim ... Existe alguma outra maneira de ganhar dinheiro rápido na cidade?}
{134}{}{Pode haver algo assim. Digamos que os funcionários não querem saber sobre uma oportunidade como essa.}
{135}{}{Bem, eu estaria disposto a pagar um pouco por alguma informação.}
{136}{}{Hmm, quanto você quer se separar?}
{137}{}{Como cerca de 500?}
{138}{}{Como cerca de 300?}
{139}{}{Como cerca de 200?}
{140}{}{Como cerca de 100?}
{141}{}{Bem, você não ouviu isso aqui, mas a senha para a porta na parte de trás é GANG PROBLEM LIMB.}
{142}{}{Hmm ... Não soa como algo em que eu estaria interessado.}
{143}{}{Hmmm .. Não se esqueça dos meus 10 filhos.}
{144}{}{Hmmm .. Bem, a esposa vai querer um novo pêlo.}
{145}{}{Hmmm ... Você vai ter que contribuir mais.}
{146}{}{Ah, um pouco curto em fundos nos dias de hoje?}
{147}{}{Eu acho.}
{148}{}{Venha agora, não seja barato.}
{149}{}{Você está ficando mais quente.}
{150}{}{Olha, vou precisar de um pouco mais de incentivo.}
{151}{}{Apresse-se, antes de alguém ver.}
{152}{}{Tem certeza de que não está envolvido com a lei?}
{153}{}{Olha, você está quase lá, apenas continue vindo.}
{154}{}{Tudo bem, apenas um pouco mais, eu prometo.}

{155}{}{Esteja no portão do lugar de Westin amanhã. Se você não mostra, você não vai, entende?}
