{100}{}{Você vê um cara careca de aparência densa, polindo um copo.}
{101}{}{É o barman.}
{102}{}{Ele é um cara de aspecto grosseiro com um nariz torto e apertou orelhas como se ele fosse um boxer há anos.}
{103}{}{O que posso fazer com você?}
{104}{}{Diga, você é o único que levou Jack a desistir, não é? Foi um bom trabalho. Então o que você quer?}
{105}{}{Certo.}
{106}{}{Beber.}
{107}{}{Quem é o grande cara lá?}
{108}{}{O que fazer nesta cidade?}
{109}{}{Adeus.}
{110}{}{Isso é Hoss, o menino do presidente Tandi. Problemas nascidos quando ele está bebendo, então eu ficaria longe dele se eu fosse você.}
{111}{}{Esse era o filho do presidente Tandi, Hoss. Garoto, você certamente ajudou o culo!}
{112}{}{Presidente Tandi?}
{113}{}{Tough guy, hein? Obrigado.}
{114}{}{Não muito. Se você está procurando problemas, vá beber algum outro lugar, como o Rawhide. Se você está procurando trabalho, há o lugar Westin a oeste da cidade. Ouvi algumas coisas sobre o presidente Tandi à procura de um especialista, também.}
{115}{}{Especialista?}
{116}{}{Presidente Tandi?}
{117}{}{Obrigado.}
{118}{}{Filha do presidente Aradesh, o cara que fundou a NCR. Ela é presidente há anos. Faz um bom trabalho também.}
{119}{}{E ela está procurando um especialista? Que tipo?}
{120}{}{Quem é o grande cara?}
{121}{}{Obrigado.}
{122}{}{Não sei. Gunther, seu assessor, provavelmente faz. Ele está no Salão do Congresso.}
{123}{}{Quem é o grande cara?}
{124}{}{obrigado}
{125}{}{Gostaria de uma bebida?}
{126}{}{Certo.}
{127}{}{Não.}
{128}{}{Deixe eu te pagar uma bebida! Eu tenho querido golpeá-lo por anos!}
{129}{}{Eu tenho algumas perguntas.}
{130}{}{Boa! Tchau.}
