{100}{}{Você vê uma mulher muito jovem vestida com roupas de combate.}
{101}{}{É Elise.}
{102}{}{Ela tem um ar não-absurdo sobre ela, como se estivesse acostumada a dar ordens e ter gente obedecida.}
{103}{}{O que você quer?}
{104}{}{Você novamente?}
{105}{}{Karl me enviou.}
{106}{}{Doc Jubileu disse que devo conversar com você.}
{107}{}{Quem é Você?}
{108}{}{Guh?}
{109}{}{Procuro uma roupa. Um que odia a escravidão. Ligue para si mesmo os New Rangers da Califórnia.}
{110}{}{Você pode consertar meu carro?}
{111}{}{Uh - Eu pensei que este lugar estava deserto.}
{112}{}{Ele agora? O que ele lhe disse?}
{113}{}{Não muito. Que você era uma boa gente e eu poderia querer ligar com você.}
{114}{}{Disse que pagou muito dinheiro.}
{115}{}{Eu sou Elise. Isso é Gond. Somos membros de um "grupo" que está tentando fazer o que é certo para pessoas.}
{116}{}{Você não parece uma instituição de caridade ou uma igreja.}
{117}{}{Soa interessante. De que maneira?}
{118}{}{Eu só quero arrumar meu carro.}
{119}{}{Apenas saia daqui. Saloon está de volta à rua principal.}
{120}{}{Odeia a escravidão, hein. Interessante. O que você faria se encontrou essa roupa?}
{121}{}{Eu pedi para se juntar a eles.}
{122}{}{Eu chutaria suas pontas.}
{123}{}{Nada.}
{124}{}{Não é da sua conta. Agora saia.}
{125}{}{Saímos do negócio do carro. Fechado permanentemente. Adeus.}
{126}{}{Não é. Adeus.}
{127}{}{Tudo bem, então, fale-me. Qual a opinião dos escravos?}
{128}{}{Odeie-os. Desagradável, vil escória da terra.}
{129}{}{Se eles me deixam em paz, deixo-os sozinhos.}
{130}{}{Alguns dos meus melhores amigos são escravos.}
{131}{}{Dinheiro de tudo o que você quer?}
{132}{}{Claro que não. Creio na verdade, na justiça e na luta pelos oprimidos,}
{133}{}{É um começo - até que alguém diga uma causa melhor para lutar.}
{134}{}{O que mais está lá?}
{135}{}{Não me trapaceie. Eu posso ver que tipo de pessoa você é. Adeus.}
{136}{}{Se você não sabe, estou perdendo meu tempo. Adeus.}
{137}{}{Não, não somos uma organização religiosa. Mente se eu fizer uma pergunta?}
{138}{}{Não, vá em frente.}
{139}{}{Não tão rápido. Você deve passar um teste para se juntar aos Rangers.}
{140}{}{Bem. Apenas me diga.}
{141}{}{Teste? O que é isto - escola?}
{142}{}{Há um escravo apenas fora da cidade. Talvez você tenha visto seu lugar. Livre os escravos lá e depois volte e fale conosco.}
{143}{}{Eu posso fazer isso.}
{144}{}{De jeito nenhum. Não quero causar problemas aqui.}
{145}{}{Bem, é o dia da sua sorte.}
{146}{}{Esse é o tipo de atitude que permite que a atrocidade da escravidão exista em primeiro lugar. Desculpe, mas não há lugar para você em nossa organização.}
{147}{}{Está bem.}
{148}{}{Então, mudou de idéia? Pronto para provar o seu valor?}
{149}{}{Certo.}
{150}{}{O que você queria fazer?}
{151}{}{Você não deveria estar fazendo alguma coisa? Não volte aqui até o trabalho terminar.}
{152}{}{Já ouvi as notícias já. Você libertou os escravos. Bom trabalho! Então, você está pronto para se tornar um Ranger?}
{153}{}{Sim.}
{154}{}{Não.}
{155}{}{Eu ouvi você ser aquele que liberou todos os escravos fora dos portões da cidade. Foi uma coisa boa que você fez e eu só quero apertar sua mão.}
{156}{}{Obrigado.}
{157}{}{Simples. Acreditamos que a escravidão está errada e faremos o que devemos para lutar contra ela. Na NCR, nós conseguimos muitos amigos em lugares altos. Graças a eles, já proibimos a escravidão para o sul, mas agora estamos esperando espalhar a palavra norte.}
{158}{}{Os Rangers soam como um grupo com o qual ficaria orgulhoso de me juntar. Assine-me.}
{159}{}{Interessante ... Eu vou ter que pensar sobre o que você disse.}
{160}{}{Você jura lutar contra a escravidão sempre que surge a oportunidade e para ajudar seus colegas Rangers sempre que eles precisam?}
{161}{}{Sim.}
{162}{}{Não,}
{163}{}{Parabéns, agora você é um Ranger.}
{164}{}{Bem conhecida, colega Ranger. Com medo, não há muito para você fazer por aqui neste momento. A maioria das pessoas já está fora de patrulha. Vou divulgar a palavra que você é um de nós agora. Eu não gostaria que você fosse baleado por um de nós.}
{165}{}{Bem, estamos sempre à procura de pessoas boas para promover a nossa causa. Se você mudar de idéia, procure-me. Tem certeza de que não aproveitará a oportunidade para se juntar agora?}
{166}{}{Tenho certeza.}
{167}{}{Bem, agora que você menciona isso, acho que gostaria de ser um Ranger.}
{168}{}{Entendo. Bem, eu represento um grupo chamado New California Rangers. Alguém com pontos de vista como o seu pode se qualificar para a adesão. Estás interessado?}
{169}{}{Ótimo! Assine-me.}
{170}{}{Soa interessante. O que você pode me falar sobre os Rangers?}
{171}{}{Entendo. Bem, obrigado por me parar, mas não consigo ver que temos mais alguma coisa a dizer um ao outro. Se você mudar de idéia, volte e me veja.}
{172}{}{Está bem.}
{173}{}{Sendo assim, tenho que pedir que você saia da minha vista. Agora!}
{174}{}{Está bem.}
{175}{}{Um escravidão! Saia daqui antes de remover sua tatuagem com uma bala!}
{176}{}{Certo.}
{177}{}{Tente!}

{178}{}{Temos agentes e simpatizantes em algumas cidades no norte. Estamos espalhando a palavra e atacando as pessoas escravas onde quer que possamos.}
{179}{}{Olá de novo. Você mudou sua opinião sobre se juntar a nós?}
{180}{}{Deixa pra lá.}


{181}{}{Isso não pertence a você. Agora saia ou ficarei violento.}
{182}{}{Eu não sei o que você fez com Gond, mas você vai pagar!}
