{100}{}{Você vê uma mulher impressionante com um longo manto.}
{101}{}{É o Iluminado.}
{102}{}{Seu olhar fixo e expressão de felicidade sem sentido seria perturbador se ela não estivesse tão tranquila.}
{103}{}{Saudações, criança. Você é um dos Iluminados?}
{104}{}{<Drool>}
{105}{}{Claro, por que não?}
{106}{}{Bem, eu sou o Escolhido.}
{107}{}{Eu realmente não sei do que você está falando.}
{108}{}{Então você é a coceira que Merk quer arranhar!}
{109}{}{Sim.}
{110}{}{Não.}
{111}{}{Eu só quero ficar sozinho.}
{112}{}{Olá? Alguém aí?}
{113}{}{Guh.}
{114}{}{Ninguém aqui.}
{115}{}{Oh, querido, um nível um. Ainda preso em estado primitivo. Talvez um alinhamento de zeta-scan ajude. Você gostaria disso?}
{116}{}{Zay-ta!}
{117}{}{Não!}
{118}{}{Por favor, não esqueça a Igreja do Hubology. São opressivos como você que fazem as coisas difíceis para o resto de nós. Oh céus. Eu sou todo turbulento!}
{119}{}{Escolhido? Você não significa AHS-One? De que texto você está trabalhando?}
{120}{}{É simples. Eu sou o Escolhido porque é o que deve ser.}
{121}{}{AHS um?}
{122}{}{É o que meu Ancião diz que eu sou.}
{123}{}{Do que você está falando?}
{124}{}{Podemos chegar à parte em que você polvilha água bendita em mim ou algo assim?}
{125}{}{Oh. Bem, você está buscando uma verdadeira compreensão e paz espiritual? Nós podemos ajudar.}
{126}{}{Não, estou procurando um GECK.}
{127}{}{Socorro? Como?}
{128}{}{Um foguista me dá toda a paz espiritual que preciso, senhora.}
{129}{}{"Verdadeiramente compreender" isso! (Gesto de mão grosseiro com o dedo do meio)}
{130}{}{Merk? O que ela quer?}
{131}{}{Simples. Ele quer você morto. Diga tchau.}
{132}{}{Eu não sei o que você fez, mas ele colocou um contrato em você.}
{133}{}{Maravilhoso, irmão. Então, qual o seu nível?}
{134}{}{Perguntei-lhe primeiro.}
{135}{}{Qual é o seu nível?}
{136}{}{Oh. Assumi que você poderia ver minha aura. Eu sinto Muito.}
{137}{}{Oh. Assumi que você poderia ver minha aura. Eu sinto Muito.}
{138}{}{ }
{139}{}{Why, I'm at Transcendency, of course.}
{140}{}{Uhhh...isn't it really impolite to go talking about levels?}
{141}{}{Honestly! I don't know what they expect me to accomplish surrounded by such rim meat!}
{142}{}{Ah, such enthusiasm. Come with me.}
{143}{}{"Lost are those who will not seek the Hub." If you should ever change your mind, you are always welcome.}
{144}{}{Do not shout! Now I've got a neurodyne to align!}
{145}{}{Predestination? What about free will? By your belief, nothing you do has any meaning since it's all determined in advance. It's like you're just a pawn in a game.}
{146}{}{You misunderstand. Only my potential as the Chosen One is pre-determined. My choices and my actions determine the fulfillment of that potential.}
{147}{}{Of course the universe is deterministic! After all, we've been put here for some purpose that's already known to our creator.}
{148}{}{Nonsense. There is no organizing force determining our fates. In fact there's no 'higher power' behind anything. The universe is just chance. I am the Chosen One because others have declared it. That's all.}
{149}{}{Aligned Hub Seeker. You are obviously not Enlightened.}
{150}{}{A primitive belief - but you show signs of great promise.  We can show you the higher path. Would you like to know more?}
{151}{}{Sim.}
{152}{}{Não.}
{153}{}{I can't help you with that. However, our scientists in San Francisco might know something. Perhaps you should travel there.}
{154}{}{By purging you of the negative psychic energy that keeps you in an oppressive state. Only then can you be Enlightened!}
{155}{}{Neurodynes are the psychic centers of the body. They become polluted by the spiritual remnants of the people who died in the War. Their psi-energies imprint into our neurodynes at birth and hold us in an oppressive state. Alignment erases these imprints.}
{156}{}{As long as your brain chemistry is affected by negative psychic energy, your true spiritual potential is oppressed. Worse still, oppressives can transmit this energy unless they are very, very strong-willed.}
{157}{}{Enlightenment happens when all your neurodynes are aligned. Then you become an AHS, Aligned Hub Seeker, which is the goal of all Hubonites.}
{158}{}{Neurodynes?}
{159}{}{Iluminado?}
{160}{}{Oppressive state?}
{161}{}{So how's this purging work? Is it painful?}
{162}{}{It's not painful. You just undergo a zeta-scan. I can do one now, if you like.}
{163}{}{Certo.}
{164}{}{No way!}
{165}{}{The Church of Hubology exists to free mankind from the chains that have kept his full spiritual potential in shackles.}
{166}{}{How do you do that?}
{167}{}{Oh yeah, like "Let my psyche go," right?}
{168}{}{That is not an ability that I possess. Is there something else that I can help you with? An alignment perhaps?}
{169}{}{I'll take the alignment.}
{170}{}{I need some information. Vault 13 - what do you know about it?}
{171}{}{How have things been going?}
{172}{}{Forget about it. No hard feelings. That's all.}
{173}{}{ }
{174}{}{Sim!}
{175}{}{ }


{176}{}{Transcendency?  Honestly, how do they expect me to spread the word out here when they don't even keep me up-to-date on the latest doctrine!?}
{177}{}{(Continuar)}
{178}{}{Were you asleep during indoctrination? Hmmph - you are not one of the Enlightened!}
{179}{}{So you're saying there's some higher power who creates us with a purpose and then just abandons us? I can't believe any being would be so callous. Come, embrace the Church of Hubology. Let us show you the true way.}
{180}{}{What true way?}
{181}{}{No thanks.}
{182}{}{Without control of your own life, though, what's the point? Nothing you do has any value. Did you choose to get up this morning? No, you're just a puppet by your own philosophy. Now, we at the church of Hubology have a true answer.}
{183}{}{Which is?}
{184}{}{Sure you do.}
{185}{}{Oh, what a sad and empty philosophy that is! Even if it were true, the only course for you is to seek to develop yourself. It is the only thing you have any control over. The Church of Hubology can help.}
{186}{}{Como?}
{187}{}{Oh, get out of my face.}
{188}{}{Vault 13? Our scientists have been searching for it somewhere to the west. That is all I know. Are you sure you don't want an alignment?}
{189}{}{Sure, why not.}
{190}{}{No thanks. I'm fine.}
{191}{}{I tell you, spreading the word of Hubology out here is harder than you can imagine! AHS-9 just doesn't understand the difficulty. In fact, I've written it all down. Say, would you be willing to deliver it to AHS-9 in San Francisco? I can't promise any reward, but I know AHS-9 will appreciate it.}
{192}{}{Claro, por que não?}
{193}{}{No thanks. I don't get involved.}
{194}{}{Excellent. Here is the letter. Now, can I do anything else for you? A zeta-scan?}
{195}{}{A scan? Why not.}
{196}{}{You've already done enough. Bye.}
{197}{}{Then I've spoken too much already. Goodbye}
{198}{}{Greetings again. How can the Church of Hubology help you?}
{199}{}{<Drool>}
{200}{}{Então você é a coceira que Merk quer arranhar!}
{201}{}{Eu realmente não sei do que você está falando.}
{202}{}{What does the church do?}
{203}{}{Oops. Wrong door.}
{204}{}{Killing me will serve no purpose. I'm not a threat to Merk, I simply irritate him because of my beliefs. I hope you'll refuse to honor the contract.}
{205}{}{Yeah, you seem harmless.}
{206}{}{Forget it. You're one dead Hubologist.}
{207}{}{I don't have time for idiots. Please go away.}
{208}{}{Out, apostate!}
{209}{}{There is nothing you can say to gain favor in the Church of Hubology, blasphemer.}
{210}{}{Close your eyes. This won't hurt a bit.}
{211}{}{There. We erased a few nasty imprints! You are now an AHS-1. Now, if you'll excuse me, I have to tend my church.}
{212}{}{Greetings, fellow seeker. There is nothing more I can do for you. You must continue your journey as an AHS-1 on your own.}
{213}{}{The church is closed. Come back tomorrow.}
{214}{}{I would love to help you, but even an AHS-4 must sleep. Come back in daylight.}
{215}{}{Intruder! Do you plan to desecrate this place? Out!}

{216}{}{Wonderful, sister. So what level are you?}
{217}{}{ }
{218}{}{You gain }
{219}{}{experience for taking care of the Hubologist for Merk.}
