{100}{}{Você vê um jovem de aparência simples com roupas respeitáveis.}
{101}{}{É o recepcionista do prédio.}
{102}{}{Não há nada excepcionalmente excepcional sobre o cara. Parece o epítome de um burocrata em broto.}
{103}{}{Bem-vindo ao Congresso. Como posso ajudá-lo?}
{104}{}{De volta, eu vejo. Como posso ajudá-lo desta vez?}
{105}{}{Agora, o que posso fazer por você?}
{106}{}{Uhhh ...}
{107}{}{Eu vejo Tandi?}
{108}{}{Eu vejo Tandi?}
{109}{}{Estou aqui para ver o presidente Tandi.}
{110}{}{Você pode me ajudar a encontrar o Vault 13?}
{111}{}{Não, a menos que você tenha um GECK.}
{112}{}{Tenho algumas novidades importantes para o seu chefe.}
{113}{}{Estou aqui para ver o presidente Tandi.}
{114}{}{Estou aqui para ver o presidente Tandi.}
{115}{}{Estou à procura de trabalho.}
{116}{}{O que é este lugar?}
{117}{}{Você não pode.}
{118}{}{Eu vou embora.}
{119}{}{Desculpe, não há banheiros públicos aqui. Por que você não se move?}
{120}{}{Relativo?}
{121}{}{Hmmm ... Por que você quer ver a Senhora Presidente?}
{122}{}{O homem diz que Tandi me contrata.}
{123}{}{Pequena cidade no deserto quer fazer amigos com Tandi.}
{124}{}{Eu ouvi o seu presidente ter um trabalho a ser feito.}
{125}{}{As pessoas da Vault 15 querem fazer um acordo.}
{126}{}{}
{127}{}{Tal como?}
{128}{}{Alguém já a vendeu.}
{129}{}{Não é da sua conta.}
{130}{}{Isso é bom. Este não é um salão de contratação. Por que você não tenta o centro da cidade?}
{131}{}{Esta é a Casa do Congresso, órgão legislativo da NCR.}
{132}{}{(Continuar)}
{133}{}{13? Ou você quis dizer 15?}
{134}{}{Eu disse 13.}
{135}{}{15?}
{136}{}{Não.}
{137}{}{(Continuar)}
{138}{}{Oh aquilo. Fale com o Sr. Gunther, de volta.}
{139}{}{Vault 15? Eles querem fazer um acordo? Interessante. Na conversa de volta para Gunther.}
{140}{}{Você pode dizer a ela você mesmo. Apenas vá falar com Gunther.}
{141}{}{Isso não soa bem. Agora, desculpe, tenho trabalho para fazer.}
{142}{}{Eu tenho que lhe dizer algo.}
{143}{}{Bem. Diga a ela que há um espião em seu escritório.}
{144}{}{Você apenas diz a ela que eu quero vê-la. Compreendo?}
{145}{}{Bem, não posso ajudá-lo com isso.}
{146}{}{(Continuar)}
{147}{}{Oh nada. Meu erro. Você disse 13, certo? Bem, não sei nada sobre isso.}
{148}{}{(Continuar)}

{149}{}{Eu reparo o problema. Mate o mau. Quer dinheiro.}
{150}{}{Diga a ela que resolvi seu problema de posse.}
{151}{}{Darion está morto? Oh, desculpe-me. Vá direto para dentro.}
{152}{}{Você fez? Bem ... Tenho certeza de que é uma notícia maravilhosa. Você aprendeu alguma outra coisa?}
{153}{}{Não}
{154}{}{Sim, há algo mais - algo sobre um espião.}
{155}{}{O que é um rel-eu quero dizer, fico feliz que tudo acabe. Vá direto para dentro.}

#messages for when the player is tampering with somthing he shouldn't
{500}{}{Com licença, mas você não pode entrar lá sem permissão.}
{501}{}{Eu tenho que pedir que você pare de adulterar com isso.}
{502}{}{Este é o seu último aviso - deixe ou seja tratado.}
{503}{}{Segurança, remova nosso "convidado".}
