{100}{}{Você vê um homem com couros e calor de embalagem.}
{101}{}{É Felix, o capataz do rancho.}
{102}{}{Ele parece um cliente mais frio e mais difícil do que o resto do lote por aqui.}
{103}{}{O que posso fazer por você estranho?}
{104}{}{Você novamente?}
{105}{}{Nyeh.}
{106}{}{O xerife me disse para vir - disse que o Sr. Westin poderia ter um emprego para mim.}
{107}{}{Estou aqui para ver o chefe.}
{108}{}{Estou procurando trabalho.}
{109}{}{Estou procurando pelo Vault 13.}
{110}{}{Apenas olhando por aí.}
{111}{}{Ótimo, outro idiota. Suponho que você queira ver o chefe?}
{112}{}{Uh-huh.}
{113}{}{Nooo.}
{114}{}{Bem. Continue.}
{115}{}{Está tarde. Volte pela manhã.}
{116}{}{Bem, então, saia daqui.}
{117}{}{Dumont, hein? Bem, isso é bom o suficiente para mim. O Sr. Westin está dentro.}
{118}{}{Isso é bom. O Sr. Westin não vê ninguém. Você tem alguma causa?}
{119}{}{Estou procurando pelo Vault 13.}
{120}{}{E se eu disser que o bispo em New Reno me enviou para matá-lo?}
{121}{}{Uh, não.}
{122}{}{Hah! Outro crackpot. Você deveria falar com Saltbeef. Você e ele se dão bem.}
{123}{}{Quem?}
{124}{}{Estou fora daqui.}
{125}{}{Saltbeef Bob - nos estábulos. O Sr. Westin deixa-o ficar lá. Agora pare de desperdiçar meu tempo.}
{126}{}{Obrigado.}
{127}{}{Então eu acho que nós temos que matá-lo.}
{128}{}{Feito com sua reunião?}
{129}{}{Westin. Trabalho. Eu}
{130}{}{Eu vou.}
{131}{}{Tudo bem, ele quer que você tenha um emprego; Eu consegui um emprego para você. Alguem, ou algo assim, mata moo-moos. Você vem para mim. Você guarda. Mantenha os moo-moos seguros. Faça o chefe feliz. OK?}
{132}{}{OK.}
{133}{}{Não, eu não matar.}
{134}{}{De volta, você está? Tarefa concluída?}
{135}{}{Sim.}
{136}{}{Não.}
{137}{}{Sim, ele deixou ordens. Ele está esperando você.}
{138}{}{EI VOCÊ! Afaste-se daí!}
{139}{}{OK.}
{140}{}{Foda-se!}
#addons
{141}{}{Sim. Ele disse para ver um problema com o brahmin.}
{142}{}{Sim. Estou fora daqui.}
{143}{}{Certo. Alguém, ou algo assim, matou brahmin no pasto oeste. Vou levá-lo lá e você cuida disso. Vamos.}
{144}{}{Esqueça isso!}

{145}{}{O Sr. Westin está esperando por você.}
{146}{}{Bem, nós estávamos tendo um problema com varmints, mas eles pararam de incomodar-nos. Você pode ver o Westin se quiser.}
{147}{}{Estou aqui a negócios da Vault City.}

{500}{}{Você toca essa porta novamente e haverá um inferno para pagar. Obteve isso, amigo?}
