{100}{}{Você vê uma mulher no uniforme blindado da NCR.}
{101}{}{É o capitão da guarda.}
{102}{}{Ela pode ser uma mulher, mas essa espingarda no quadril diz que ela não é nenhuma tentativa.}
{103}{}{Você vai ter que me desculpar, sou uma mulher ocupada. Não há tempo para chitchat.}
{104}{}{Apenas mantenha seu nariz limpo e nós vamos nos dar bem, estranho.}
{105}{}{Você recebeu perguntas? Olhe para o xerife Dumont. Ele irá preenchê-lo.}
{106}{}{As leis estão no quadro de avisos fora - sem armas, sem bêbados, sem problemas.}
{107}{}{O que posso fazer por você, estranho?}
{108}{}{Você novamente?}
{109}{}{Eu entro.}
{110}{}{Gostaria de entrar na NCR.}
{111}{}{Nada.}
{112}{}{Você não vai a lugar algum até você arrumar essas armas.}
{113}{}{Todo mundo tem que arrumar as armas.}
{114}{}{Hmm ... bem, você parece respeitável o suficiente. Qual o seu nome? Eu tenho que colocá-lo no livro de registro.}
{115}{}{}
{116}{}{Tudo bem então, eu vou ter o portão aberto para você em apenas um segundo.}
{117}{}{Você não deve manipular isso! Saia agora ou haverá problemas.}
