{100}{}{É um grande super mutante.}
{101}{}{É Gond, o super-mutante.}
{102}{}{É grande, é verde, e não é mais brilhante do que o resto desse tipo.}
{103}{}{Ei, Elise disse que você poderia estar aqui?}
{104}{}{Você também é um guarda florestal?}
{105}{}{Você não deve estar aqui.}
{106}{}{Saudações (irmão / irmã).}
{107}{}{O trabalho de uma Ranger nunca foi feito.}
{108}{}{Tome o coração! Nosso irmão bateu um campo de escravos na semana passada.}
