{100}{}{Parece um funcionário, já que ele usa um uniforme com um crachá NCR.}
{101}{}{É apenas um guarda da cidade.}
{102}{}{Vamos ver - cara duro, tem uma arma, tem um distintivo, tem armadura - hmm, pode ser um guarda.}
{103}{}{Bem-vindo à NCR. Apenas para informá-lo, se você tiver armas, mantenha-os inchados. Esta não é uma cidade de armas, estranha.}
{104}{}{Bem-vindo à NCR, capital da Nova República da Califórnia, decisão do presidente Tandi.}
{105}{}{Saudações, estranho. Venha fazer negócios com a NCR, não é?}
{106}{}{A NCR agradece-lhe - desde que não cause problemas.}
{107}{}{Ei, você destrói suas armas. A NCR não recebe esse tipo de problema.}
{108}{}{Mais estranho, a NCR tem leis e uma delas "sem armas". Coloque-o fora e não haverá problemas.}
{109}{}{Leia o sinal no caminho? "Sem armas", e nós queremos dizer isso. Compreendo?}
{110}{}{Vocês são todos iguais. Esta é uma cidade pacífica - isso significa que não precisamos de você para fazer hardware. Coloque suas armas e não haverá problemas.}
{111}{}{O portão está fechado para a noite. Se você pressionou negócios, leve-a para a casa de guarda.}
{112}{}{Você deve falar com o capitão do guarda se quiser através do portão.}
{113}{}{Um pouco tarde para chegar à cidade. Vá ver o capitão; talvez ela o deixe entrar.}
{114}{}{Giro e me afastaria muito rápido se eu fosse você.}
{115}{}{Você e seu tipo não são bem-vindos na NCR.}
{116}{}{Chegue mais perto e você vai se arrepender.}
{117}{}{Nós fomos avisados   sobre você, então deixe-se em paz. Compreendo?}
