{100}{}{Você vê um jovem esbelto com óculos.}
{101}{}{É Gunther, assessor do presidente Tandi. Pelo menos foi o que o sinal na porta disse.}
{102}{}{Ele parece oficioso e ocupado, o tipo nascido para ser um burocrata que outras pessoas odeiam.}
{103}{}{Posso ajudar?}
{104}{}{Você novamente?}
{105}{}{Uhhhh - trabalhe. Trabalhe Tandi.}
{106}{}{Quem é Você?}
{107}{}{Estou aqui para ver o presidente Tandi sobre um trabalho.}
{108}{}{Desculpe, escritório errado.}
{109}{}{Você quer emprego?}
{110}{}{Vamos tentar isso de novo. Você ajuda Tandi? Faça o trabalho para Tandi?}
{111}{}{Sim Sim SIM SIM!}
{112}{}{Tandi job. Eu quero.}
{113}{}{O que você faz?}
{114}{}{Uhhhh ... eu mato, eu mato grande!}
{115}{}{Uhhhh ... eu inteligente. Os idosos dizem que tenho cérebro de criança. Tenho 2 cérebros. Eu inteligente.}
{116}{}{Você não pode assumir o cargo de presidente!}
{117}{}{Não?}
{118}{}{Oh. OK.}
{119}{}{Certo. Não tenho certeza que é isso que ela está procurando. Bem, ela disse, envie-os para todos.

Você vai. Converse Tandi agora.}
{120}{}{NÃO! Você é idiota. O presidente deve ser inteligente, falar em palavras de duas sílabas! Você não é presidente.}
{121}{}{Oh. O que eu faço?}
{122}{}{Eu não, como você. Você grita. Homem mal.}
{123}{}{Meu nome é Gunther, assistente pessoal do presidente Tandi. Agora, o que posso fazer por você?}
{124}{}{Estou procurando pelo Vault 13.}
{125}{}{Estou procurando pelo GECK.}
{126}{}{Eu entendo que o presidente tem um trabalho a ser feito.}
{127}{}{Senhora Presidente, não concede mais entrevistas sobre o Vault 13. Desculpe. Ela está muito ocupada para ver todos os prospector que atravessam.}
{128}{}{Hã? Não entendi.}
{129}{}{E quanto a um GECK. Ela pode saber algo sobre isso?}
{130}{}{Houve uma conversa sobre um trabalho.}
{131}{}{Você é inútil. Vou.}
{132}{}{Então eu sugiro que você leia a placa na estátua do lado de fora. Agora, bom dia.}
{133}{}{Eu não tenho ideia do que você está falando. Você tem uma verdadeira pergunta?}
{134}{}{Estou procurando pelo Vault 13.}
{135}{}{Eu entendo que o presidente tem um trabalho a ser feito.}
{136}{}{Deixa pra lá.}
{137}{}{Ah sim. Bem, ela me instruiu a enviar qualquer pessoa perguntando sobre isso. Você está entrando. É a porta da minha direita.}
{138}{}{Senhora Presidente, terminou com você? Como as coisas aconteceram?}
{139}{}{Boa. Eu sou tchau.}
{140}{}{Bem. Agora, estou fora daqui.}
{141}{}{Aqui para denunciar o resultado do Vault 15?}
{142}{}{Sim.}
{143}{}{Não.}
{144}{}{Bem, desculpe, mas a senhora presidente está muito ocupada. Por que você não volta quando o trabalho está pronto?}
{145}{}{OK.}
{146}{}{Excelente! Vou chamar você diretamente.}
{147}{}{Seu desgraçado! Guardas! Assassino! Assassino!}
{148}{}{De volta tão cedo! O que agora?}
{149}{}{Recompensa.}
{150}{}{O presidente disse para ver uma recompensa.}
{151}{}{Dinheiro.}
{152}{}{Estou aqui para coletar meu salário.}
{153}{}{Seu presidente disse que você deveria saber que há um espião em sua casa - alguém chamado Feargus.}
{154}{}{Nada.}
{155}{}{Claro, ela acabou de me mexer sobre isso. Uma recompensa de $ 6000 e NCR agradece-lhe, disse ela. Agora, há trabalho a ser feito. Adeus.}
{156}{}{Vamos ver. Contrato diz $ 500. Olha Você aqui.}
{157}{}{Na verdade, ela simplesmente me chamou para mudar seu valor - parece que você ganhou um bônus. Aqui está, $ 900 e os agradecimentos da NCR. Agora, há trabalho a ser feito, então, adeus.}
{158}{}{Seu presidente disse que você deveria saber que há um espião em sua casa - alguém chamado Feargus.}
{159}{}{Adeus.}
{160}{}{Feargus? Eu não acredito nisso!}
{161}{}{Dê uma olhada neste disco.}
{162}{}{Tanto faz. Estou fora daqui.}
{163}{}{Droga. Parece sólido. Olha, nós vamos cuidar disso. Aqui estão $ 4000 para a informação.}
{164}{}{Eu não pego dinheiro no sangue. Estou fora daqui.}
{165}{}{Obrigado. Tenha um bom dia.}
{166}{}{Ah é você. Olha, este não é um bom momento. Na verdade, eu acho que a Sra Presidente gostaria de não envolver-se em nada mais. Obrigado e bom dia.}
{167}{}{Deixe-me deixar claro. O presidente não vai te ver, agora ou sempre. Você foi pago. Agora, vá embora.}

{171}{}{Eu vou.}
{172}{}{Absolutamente nada.}
{173}{}{Sua cadela Guardas! Assassino. Assassino!}

{174}{}{Fui ao Vault 15 e preciso falar com o seu chefe sobre isso.}
{175}{}{Eu preciso falar sobre o Vault 15.}

{176}{}{Você deve saber que há um espião em sua casa - alguém chamado F.}


#define GLOBAL Message response
{500}{}{Nós mantemos as portas trancadas por um motivo.}
{501}{}{Devo pedir que você vá embora.}
{502}{}{Este é o último aviso. Deixe antes que eu tenha removido.}
{503}{}{Segurança - por favor, lide com essa praga.}
