{100}{}{Ele é um cara musculoso, com um cofre de barril.}
{101}{}{É Hal, o capitão do brahmin drive.}
{102}{}{Ele está mordendo um punhado de algo que você espera que ele não cuspi por este caminho, porque fede ao céu alto.}
{103}{}{Você está aqui para a unidade?}
{104}{}{}
{105}{}{Sim.}
{106}{}{Não.}
{107}{}{Precisa de alguns flutuadores redding !!!}
{108}{}{Yuep precisa desses flutuadores redding !!}
{109}{}{Imagina o que os flutuadores da Redding vão aqui.}
{110}{}{Ótimo. Vamos lançar. Dirija-os para meninos Redding!}
{111}{}{Bem, então, deixe-me em paz. Eu consegui 500 cabeças de brâmane para entrar na trilha.}
{112}{}{Você novamente? Vá embora.}
{113}{}{Bem, essa foi a pena! Com medo de que não haja dinheiro nesta corrida para nenhum de nós. Apenas fique feliz por você estar vivo.}
{114}{}{Bem, os fazendeiros não são muito felizes - é apenas uma corrida de US $ 1000. Tough luck.}
{115}{}{Bem, tivemos uma pequena série de má sorte, mas tudo bem. Aqui estão os $ 2000 que você iniciou.}
{116}{}{Caramba, você estava bem! Há um bônus de $ 1000 para você. Isso e $ 2000 fazem seu pagamento. Redding melhor cuidado esta noite!}
{117}{}{Você esta por sua conta. Bom viajando com você.}
