{100}{}{Você vê um gemea com uma cabeça calva brilhante e óculos de lente grossa.}
{101}{}{É o Dr. Henry}
{102}{}{Esse cara está tão fora do lugar que é doloroso. Ele tem essa cabeça de ovo, não vivendo no ar do mundo real sobre ele, com certeza.}
{103}{}{Com licença, eu sou o Dr. Henry e estou muito ocupado. O que você quer?}
{104}{}{Você novamente? O que você quer?}
{105}{}{Hurgh.}
{106}{}{Eu estou}
{107}{}{Bastante bate-papo. Você tem alguns documentos que o Sr. Merk quer. Entregue-os e ninguém se machuca.}
{108}{}{Já ouvi falar de um lugar chamado Enclave?}
{109}{}{Não é da sua conta.}
{110}{}{Hmm, sub-par cranial development... Stunted intellectual development. No gross physical mutation, though. No, you just simply won't do, Eu estou afraid. Good day.}
{111}{}{The Chosen One? Of course, that makes sense.  Interesting... Eu estou afraid I can't help you. I was assigned to cyber-genetics research, not the Vault Behavioral Project.}
{112}{}{Do que você está falando?}
{113}{}{Projeto Behavioral Vault?}
{114}{}{Ciber-genética? Não lembro de nunca estudar isso.}
{115}{}{Certo. Você está bravo como um Hatter. Adeus.}
{116}{}{Oh, eu já disse mais do que deveria. Não importa, e se alguém perguntar não disse nada.}
{117}{}{Alguma coisa sobre condicionamento sociológico extremo. Lembre-se, pensei que era tudo muito mumbo-jumbo, nenhuma ciência real nele. Mas eu ouvi algo sobre 13 ter que ser improvisado durante o curso do experimento. Trabalho superficial, eu diria.}
{118}{}{Experimentar? Qual experiência?}
{119}{}{O que é isso sobre ciber-genética?}
{120}{}{Você espera que acredite nisso? Você é um mergulhador.}
{121}{}{Oh, it's a whole new field - very exciting. Why Eu estou working on some projects right now - a radical new concept for the mutant problem.  You see, it's really quite simple - mutancy isn't absolute. It can be cured.}
{122}{}{Claro, meus colegas de mente simples estavam apenas tentando resolver o problema todo o caminho mais grosseiro possível. Purificação, na verdade. Eu admitirei que houve alguns problemas iniciais, mas os fiz trabalhar agora ... acho.}
{123}{}{}
{124}{}{Continuar}
{125}{}{Na verdade, você poderia me ajudar a realizar o teste de campo. Interessado?}
{126}{}{Teste de Campo? O que você quer dizer?}
{127}{}{Não é uma chance.}
{128}{}{Preparei uma pequena amostra do soro, mas precisa ser injetada em um hospedeiro.}
{129}{}{Eu estou not letting you stick any needles in me!}
{130}{}{That's it, Eu estou out of here.}
{131}{}{Você? Oh, não - o soro não é refinado o suficiente para lidar com um quociente tão pouco mutagênico. Ele deve ser usado em um super mutante. Injete o soro para um super mutante e depois volte e relate os resultados. Entendo que Broken Hills está cheio deles.}
{132}{}{O que é isso?}
{133}{}{O que há para mim?}
{134}{}{Bem, isso deve causar uma regressão na matriz genética que resulta na desestabilização e assimilação do DNA abberante, deixando o hospedeiro livre de potencial mutagênico. Se eu soubesse com certeza, não precisaria de você para testá-lo.}
{135}{}{O que há para mim?}
{136}{}{Você estará participando de um experimento importante, de fato, o mais importante, científico, você quer dizer dinheiro. Bem, eu tenho um Cyber-Hound Mk. II, modelo de segurança pessoal, que trouxe comigo. Suponho que eu poderia tê-lo ativado e on-line no momento em que você voltou. Isso faria isso?}
{137}{}{Cyber-hound? Claro, por que não.}
{138}{}{Você está fora de si. Apenas completamente desconcertante.}
{139}{}{Excelente. Aqui está o soro, instalado em uma hipox de estímulo. Tudo o que você precisa fazer é usá-lo em um super mutante e, em seguida, informar de volta para mim. Como eu disse, Broken Hills - esse é o lugar para olhar. Boa sorte.}
{140}{}{Diga ao Sr. Merk que minha resposta não mudou. Não tenho interesse em nenhuma das suas "joint ventures". Obrigado e bom dia.}
{141}{}{It's no use, Eu estou not going back. None of you appreciated the work I was doing, so don't pretend to be my friend. Thank you very much!}
{142}{}{Bem, não temos nada para falar. Dia bom.}
{143}{}{Então, como foi? O teste é feito?}
{144}{}{Sim.}
{145}{}{Não.}
{146}{}{Well, if you don't mind, would you please get on with it? Eu estou not a young man anymore.}
{147}{}{E ... como funcionou?}
{148}{}{Isso o matou! Você disse que curaria os mutantes!}
{149}{}{Ele está morto, Jim.}
{150}{}{Você entendeu mal. Eu disse que eliminaria o potencial mutagênico deles. No entanto, o processo parece violento no sistema. Oh, bem, mais refinado para fazer.}
{151}{}{E o meu salário?}
{152}{}{Você é um monstro! Eu não quero nada com você.}
{153}{}{Ainda tenho alguns erros, vejo. Bem, tente e tente novamente.}
{154}{}{E o meu salário?}
{155}{}{Você é um monstro! Eu não quero nada com você.}
{156}{}{Claro. O cyberdog é todo seu. Agora, tenho trabalho a fazer.}
{157}{}{... então a taxa de mutação estabiliza-me não me incomoda agora.}
{158}{}{Adaptação primitiva às condições ambientais. Fascinante.}
{159}{}{Você não tem um calibrador oscilante? Não, claro que não.}
{160}{}{, the Chosen One. Eu estou looking for Vault 13.}
{161}{}{Good day, my ass, bucko, Eu estou here to be polite. You hand over those papers or I'll start removing fingers. Let's see how good of a doc you are then.}
{162}{}{Tudo bem, eu vou avisá-lo.}
{163}{}{Uh ... Ok, os papéis estão na minha mesa lá. Pegue eles; Apenas não machuque minhas mãos. Ok?}
{164}{}{Beije minha bunda, você critin! Guardas! Guardas!}
{165}{}{Agora você está sendo razoável. Vou deixar o Sr. Merk saber.}
{166}{}{Você vai se arrepender disso, Doc.}
{167}{}{Ei! Você tem exatamente dez segundos para colocar esses documentos de volta antes de chamar os guardas.}
{168}{}{Pegou você novamente, hein? Tudo bem, eu deixarei a lei lidar com você. Guardas! Guardas!}
