{100}{}{Você vê um lunk grande, burro e musculoso.}
{101}{}{É Hoss}
{102}{}{Ele não parece estar armado, com armas ou sagacidade.}
{103}{}{Ei, cara-cara. Eu não gosto de você. Eu acho que você deveria me comprar uma bebida.}
{104}{}{Ei, baby, venha aqui e eu vou te dar um bom e molhado.}
{105}{}{<Fart!>}
{106}{}{Morde-me.}
{107}{}{Eu não quero nenhum problema.}
{108}{}{Então, você acha que é difícil? Vou limpar sua bunda por todo o chão. Poemas nus, aqui mesmo, agora mesmo.}
{109}{}{"Eu não quero nenhum problema!" Bem, você vai ter isso. Você quer me lutar ou eu vou dizer a todos o que é um bebê pequeno e sem graça, você é. Punhos nus, aqui mesmo.}
{110}{}{Tudo bem, vamos dançar.}
{111}{}{Na verdade, não pude.}
{112}{}{Haw! Que piada. Saia daqui, água-viva.}
{113}{}{Ow! Você me quebrou o nariz! Eu desisto! Não me acerte mais!}
{114}{}{OK sinto muito. Eu só estava brincando. Você não terá mais problemas comigo ... por favor, não me mate!}
{115}{}{Ei, estou recuando. Ok, não me toca?}
