{100}{}{Você vê um jovem vestindo o emblema da polícia NCR}
{101}{}{É Karl, o deputado da cidade.}
{102}{}{Você vê um jovem quase fora de sua adolescência. Ele parece ansioso para agradar.}
{103}{}{Bem-vindo, estranho. Sou deputado Karl. O que posso fazer para você?}
{104}{}{Tal como?}
{105}{}{Uh ... nugh ..}
{106}{}{Eu sou novo na NCR. O que você pode me falar sobre sua cidade?}
{107}{}{Bem, estou procurando pelo Vault 13.}
{108}{}{O presidente Tandi enviou-me para falar com um prisioneiro que você tem.}
{109}{}{Meu nome é}
{110}{}{Estou procurando um cara chamado Jack. Algumas pessoas o chamam de Whack Jack.}
{111}{}{Onde posso encontrar Roger Westin?}
{112}{}{Ok, teve um pouco de festa, você? Olha, há uma cela desbloqueada lá atrás. Por que você não vai voltar e dormir?}
{113}{}{Olhe, pegue meu conselho - pegue seus amigos para levá-lo para casa, para que você possa dormir. Bêbado no crime público aqui.}
{114}{}{Este é NCR, capitólio da Nova República da Califórnia. População 3000 e crescente. Sem escravidão, sem jogo, sem chems. Presidente é a Sra. Tandi, meu chefe é xerife Dumont. Isso responde suas perguntas?}
{115}{}{Bem, eu tenho algumas outras perguntas.}
{116}{}{Sim, é tudo.}
{117}{}{Então eu quando eu era criança. Deixe-me saber se você acha!}
{118}{}{Bem, eu tenho algumas outras perguntas.}
{119}{}{Caramba, valeu.}
{120}{}{Seu nome é Oswald. Isso é tudo o que podemos sair dele. Ele deveria ser um possegador, do cofre 15, mas ... eu duvido disso. Ele é um pouco difícil demais. Você sabe o que eu quero dizer?}
{121}{}{Tough guy, hein?}
{122}{}{O que você vai fazer com ele?}
{123}{}{Diga, eu ouvi falar de você não? Sim - algumas coisas muito boas. Olha, há algumas pessoas que eu conheço, eles poderiam usar um colega como você. Basta ir à loja de automóveis e pedir Elise. Diga a ela que Karl envia seus cumprimentos.}
{124}{}{Trabalhos? A Stockmen's Association está à procura de guardas. Raiders estava batendo duramente no gado. E ouvi dizer que o presidente Tandi tem procurado por alguém "engenhoso", como diz ela. Isso ajuda?}
{125}{}{Bem, eu tenho algumas outras perguntas.}
{126}{}{Alguns. Obrigado.}
{127}{}{Esse é o oficial Jack, estranho. Um dos nossos homens. Você não conversou com Mira, não é?}
{128}{}{Sim.}
{129}{}{Mira quem?}
{130}{}{Esse SOB? Ele tem uma propagação fora da cidade. Pegue a estrada após Stockmen's.}
{131}{}{Você não gosta muito dele.}
{132}{}{Bem, eu tenho algumas outras perguntas.}
{133}{}{Obrigado.}
{134}{}{Sim. Ele é muito ruim. Matou dois de nossos homens e não disse nada.}
{135}{}{Me dê um pouco de tempo com ele. Talvez eu possa convencê-lo a ser cooperativo.}
{136}{}{Posso vê-lo agora?}
{137}{}{Pendure o bastardo, espero. Ele e seus amigos mataram dois bons homens. Não haverá dor para mim vê-lo morto.}
{138}{}{Posso vê-lo agora?}
{139}{}{Ela e Jack costumavam se casar, você sabe. Eles tiveram um divórcio realmente bagunçado. Eu não acreditaria cuspir dela, não sobre Jack.
Faça um favor, fique fora dela. Jack é um bom homem, é só que este material o fez ficar um pouco nervoso.}
{140}{}{Ok, vamos para outros tópicos.}
{141}{}{Bem, obrigado gentilmente por esse conselho, deputado.}
{142}{}{Seu ex, isso é tudo. Se ele não está aqui, ele pode estar acabado no powerplant. Ele está olhando para lá para Dorothy.}
{143}{}{Bem, eu tenho algumas outras perguntas.}
{144}{}{Obrigado.}
{145}{}{Acho que eu sou bastante óbvio. Muitas pessoas olham para ele porque ele é vereador, mas não eu. Ele acha que ele é um homem grande, como a lei nem sempre se aplica a ele. Gostaria de derrubá-lo um ou dois minutos um dia.}
{146}{}{As coisas mais estranhas aconteceram. O que você pode me falar sobre ele?}
{147}{}{Eu tenho que ir. Bem fora da cidade, você diz?}
{148}{}{Sem problemas. Próximos cinco minutos, talvez eu não ouça nada. Me siga.}
{149}{}{Claro, por que bom ele vai fazer você.}
{150}{}{Bem, há alguns anos, ele teve um acidente vascular cerebral e agora o Doc Jubilee levou-o a algum tipo de remédio. O que é para você, afinal?}
{151}{}{Nada, apenas fale. Vou deixar de perder o seu tempo.}
{152}{}{. Preciso de um trabalho honesto.}
