{100}{}{Um mutante - e um doméstico com isso.}
{101}{}{Isso é Lenny, lembra? O desagradável.}
{102}{}{Hoo-boy - esse rapaz é um trabalho. Além do fato de ele ser verde e feio, ele tem mais cicatrizes nele do que uma velha prostituta. Este é um lutador, com certeza.}
{103}{}{Eu sou Lenny e você é escória da lagoa. Saia daqui.}
{104}{}{Por que você incomoda Lenny, seu pequeno grub branco?}
{105}{}{O que você quer com Lenny, sem valor humano?}
{106}{}{Continue me cutucando e você pode dizer ao seu fabricante que Lenny lhe enviou.}
{107}{}{Prazer em conhecê-lo. Eu sou Lenny - você deve ser Shit-for-crins. Ha, ha!}
{108}{}{Diga ao seu mestre mutante que meu nome é Lenny, escravo.}
{109}{}{Ei, irmão mutie, Lenny se pergunta por que você está pendurado com essa lesma humana?}
{110}{}{Lenny não fala com ninguém. Faz mutile seus escravos, grub.}
{111}{}{Lenny diz que você e seu mutie de beijos, Tom podem ir para o inferno.}
{112}{}{Cuidado. Lenny não é um mutie tão doméstico como aquele que você recebeu agora.}
{113}{}{Ei, as costas da pele pálida!}
{114}{}{Saia do meu caso, humano.}
{115}{}{Perder-se, chump.}
{116}{}{Qual é o problema? Precisa de alguém para trocar sua fralda?}
{117}{}{Você é tão denso como uma pilha de tijolos, humanos.}
