{100}{}{Você vê um homem bem vestido e pesado que se move com uma lentidão deliberada.}
{101}{}{Merk - gente o chama de The Man por aqui.}
{102}{}{Este sujeito tem um ar de frieza arrogante para ele, como ele não se importa com você, não mais do que a mosca que ele acabou de espreitar entre os dedos.}
{103}{}{Ei, eu vi você nos filmes! Venha me mostrar uma ação, você?}
{104}{}{Whaddya significa, perturbando minha paz assim? Saia daqui.}
{105}{}{Com licença, tenho negócios para conduzir.}
{106}{}{Você quer falar de negócios, me veja no Rawhide. Caso contrário, deixe-me em paz.}
{107}{}{Eu vi você na tela prateada, não é? Você ficou impressionante, uh, credenciais.}
{108}{}{Você tem esse olhar certo em seus olhos. Pare com o Rawhide - eu sempre poderia usar alguém como você.}
{109}{}{Merda, qual é esse cheiro? Algo simplesmente entrou na sala.}
{110}{}{Vá buscar outro whisky - rápido agora.}
{111}{}{Não tenho tempo agora.}
{112}{}{Eu sou um convidado aqui. Pare de me incomodar.}
{113}{}{Ei, baby, bons trilhos que você conseguiu. O gosto de Carlson está melhorando.}
{114}{}{Eu não faço negócios aqui.}
{115}{}{Eu não conheço você. Eu sou um homem de negócios respeitável.}
{116}{}{Bem, se não é o wuss. Continuar e me deixe em paz.}
{117}{}{Então, decidi me procurar depois de tudo, eh baby?}
{118}{}{Não sei nada sobre nada, entenda.}
{119}{}{O veep não vai gostar de você incomodar seus convidados.}
{120}{}{Damn fine booze o homem serve aqui.}
{121}{}{Saia do meu caminho!}
{122}{}{Você quer conversar com alguém, vá comprar um amigo.}
{123}{}{Não dou indicações e não desmascolho a mudança. Bug off.}
{124}{}{O que é isso - hora social?}
{125}{}{Eu sou o Merk. Whattya quer?}
{126}{}{Você novamente?}
{127}{}{Bem, mantenha-o educado, punk, ou isso pode ficar feio.}
{128}{}{Oort.}
{129}{}{Estou procurando trabalho.}
{130}{}{Fontes informadas dizem que você é o homem a ver sobre fazer negócios, se você sabe o que quero dizer.}
{131}{}{Eles dizem que você é o homem que arrancou meu carro.}
{132}{}{Estou procurando por alguma informação.}
{133}{}{Alguns dizem que você pode saber uma coisa ou duas sobre, oh diga, coisas que faltam nos carros.}
{134}{}{Você novamente? So's the job done?}
{135}{}{Glub.}
{136}{}{Não.}
{137}{}{Eu tenho algumas perguntas}
{138}{}{Hmm ... Forte. Mudo ... Se você quer um emprego, fale com Mira. Compreendo? Mi-ra. Lá.}
{139}{}{Como fazer ruídos? Será que alguém tirará este brahmin turd daqui?}
{140}{}{Você é tão estúpido? Você acha que eu vou contratar alguém? Você trabalha para mim, você deve provar que você é bom para algo.}
{141}{}{Que tal eu acabei de atirar em Lenny, ai? Ele merece.}
{142}{}{Prove como como?}
{143}{}{Você conhece alguém que gostaria de um jato, talvez?}
{144}{}{Ouça, eu sou} //258
{145}{}{Certo. Como eu tenho que me provar a você. Esqueça você, slugwort.}
{146}{}{Era esse maldito Doofus, não era? Esse pequeno viciado fala muito com seu próprio bem. Diga-lhe o que - você o protege para mim - chame isso de favor - e depois conversaremos.}
{147}{}{Combinado.}
{148}{}{Whoa - eu não sou tão frio!}
{149}{}{E eles vão dizer que você era um burro burro. Rapazes-}
{150}{}{Interessante. Agora, quem iria dizer algo assim?}
{151}{}{Não me trapaceie, homem gordo. Se eu não voltar o que é meu, alguém vai comprar seu enterro.}
{152}{}{Fofa. Você vai responder a minha pergunta ou não?}
{153}{}{Oh, é só uma coisa que ouvi. Só queria ver o que você diria.}
{154}{}{Supondo que eu conheça alguma coisa. E daí?}
{155}{}{Agora, se um homem tivesse algumas coisas desaparecidas, você acha que ele poderia comprar essas coisas de volta?}
{156}{}{Eu quero minha merda de volta, homem gordo!}
{157}{}{Que tal eu falo com a lei?}
{158}{}{Estou cansado disso. Meninos - cuide do nosso convidado.}
{159}{}{Eu não acho que Lenny gostaria disso.}
{160}{}{Provavelmente, mas não estava perguntando a ele.}
{161}{}{Tenha o seu caminho.}
{162}{}{Verdade. Foi tão aborrecido por aqui. Tempo para um pouco um-em-um no porão. Vamos, Lenny, eu quero assistir você matar isso}
{163}{}{Como se eu tivesse problemas que precisam ser resolvidos.}
{164}{}{Tal como?}
{165}{}{Jato? Você está propondo alguma coisa ...?}
{166}{}{Meu amigo aqui sabe como fazê-lo. Interessado?}
{167}{}{Algo ilegal? Não, eu não faria isso.}
{168}{}{Intrigante. Eu lhe darei $ 1000 por seus serviços - permanentemente.}
{169}{}{Combinado.}
{170}{}{Não, não posso fazer isso com um amigo.}
{171}{}{Parece que podemos fazer negócios, amigo. Aqui está o acordo - há um cientista lobo na cidade - Dr. Henry. Ele tem alguns papéis que eu gostaria. Eu pagarei $ 1000 por eles. Ah, e eu não quero nenhum mal para vir ao Dr. Henry. Ele é útil vivo. Interessado?}
{172}{}{Estou com isso.}
{173}{}{Não, não meu estilo.}
{174}{}{O conhecimento custa você. Estou limpo?}
{175}{}{"O preço da sabedoria está acima dos rubis".}
{176}{}{Aqui estão $ 50.}
{177}{}{Esqueça.}
{178}{}{Oh, você é essa pessoa.}
{179}{}{Continuar}
{180}{}{Bem, no que me diz respeito, aqui você é apenas uma pilha de esterco.}
{181}{}{Eu tinha imaginado por um wuss.}
{182}{}{OK. Sem problemas. Não quero problemas. Eu vou te dizer o que, eu mesmo vou ter meus meninos colocar as coisas de volta, onde elas encontraram.}
{183}{}{É melhor ser, ou voltarei.}
{184}{}{Não me dê isso bs!}
{185}{}{Tal pessoa só pode ser capaz de.}
{186}{}{Agora, sugiro que você vá embora.}
{187}{}{Por todos os meios, ligue para os oficiais. Claro, suponho que você tenha evidências para apoiar sua acusação selvagem.}
{188}{}{Sim claro.}
{189}{}{Deixa pra lá.}
{190}{}{Como há um maldito Hubologist na cidade que me irritou. Uma vez que esta coceira é arranhada, volte e fale comigo.}
{191}{}{Considere isso feito. Eu tenho apenas o backscratcher para ele, mas ... o que é um Hubologist e onde eu o encontro?}
{192}{}{Como você ousa falar contra a verdadeira crença!}
{193}{}{Desculpe, não me envolvo em guerras religiosas.}
{194}{}{Bem, sou um homem sábio. Qual é a sua pergunta?}
{195}{}{Pergunta à vontade.}
{196}{}{Estou procurando pelo Vault 13.}
{197}{}{Já ouviu falar de um GECK?}
{198}{}{O que você sabe sobre alguma roupa chamada Rangers?}
{199}{}{O que você pode me falar sobre um cara chamado Westin?}
{200}{}{Estou à procura de informações sobre o vice-presidente Carlson.}
{201}{}{É isso aí.}
{202}{}{Seu pagamento recebe uma pergunta. Outro custa mais US $ 50.}
{203}{}{Ok, aqui.}
{204}{}{Tenho todos os fatos que preciso.}
{205}{}{Só acontece, eu tenho um mapa para o Vault 13. É apenas 1000 dólares. Estás interessado?}
{206}{}{Certo. Eu vou levar.}
{207}{}{E eu aposto que você também tem uma ponte para vender.}
{208}{}{Talvez mais tarde.}
{209}{}{É algum tipo de químico de New Reno? Eu nunca ouvi sobre isso.}
{210}{}{Não. Ainda tenho mais algumas perguntas.}
{211}{}{Isso era tudo o que eu precisava saber.}
{212}{}{Aqueles bastardos? Melhor ficar fora do meu lugar ou vou colocar um buraco neles.}
{213}{}{Bem, isso foi informativo. Outra pergunta.}
{214}{}{Isso era tudo o que eu precisava saber.}
{215}{}{O fazendeiro, hein? Veio aqui uma vez, sobre croaked. Town doc teve que se apressar com algumas pílulas - parece que Westin tem uma condição cardíaca. Negócio arruinado pelo resto da noite.}
{216}{}{Obrigado pela informação. Eu tenho mais algumas perguntas.}
{217}{}{Isso era tudo o que eu precisava saber.}
{218}{}{Como um bom cidadão, aplaudo a oposição de Carlson a qualquer nova influência de Reno por aqui. Agora que o Westin está morto, eu tenho ajudado com segurança para o vice-presidente.}
{219}{}{Bem, acho que nunca vou conhecer o homem. Também ouvi muito sobre ele.}
{220}{}{Isso era tudo o que eu precisava saber.}
{221}{}{Isso tudo?}
{222}{}{Não, eu tenho mais algumas perguntas}
{223}{}{Sim, é por enquanto.}
{224}{}{Ei, um homem tem que tentar. O Vault 13 é praticamente uma religião por aqui. Eles até construíram uma estátua para um chump que supostamente veio de lá. Isso é tudo que eu sei.}
{225}{}{Eu vendi um mapa para você. Tente usar isso.}
{226}{}{Esse mapa não expôs? Desculpa. O cara jurou que era genuíno. Como eu sabia? Não sei onde é o Vault 13.}
{227}{}{Eu tenho mais algumas perguntas.}
{228}{}{Isso é tudo o que preciso saber.}
{229}{}{Dizer-te o que. Gosto do seu trabalho e Carlson poderia usar outro guarda. Dê um pouco de tempo e haverá um emprego esperando por você lá embaixo.}
{230}{}{Estou com isso, Merk.}
{231}{}{Não preciso de emprego. Obrigado mesmo assim.}
{232}{}{Excelente. Volte quando terminar.}
{233}{}{Isso é muito preocupante.

Meninos, matá-lo e recuperar essa evidência.}
{234}{}{Suas fracas tentativas de me intimidar são quase divertidas, mas agora eu sugiro que você vá antes de me cansar desse jogo.}
{235}{}{Ah, eu ouvi as notícias. Você ainda está interessado em um emprego?}
{236}{}{Sim, estou cansado de brindes. Eu poderia usar o trabalho.}
{237}{}{Não.}
{238}{}{Que diabos você está fazendo na minha casa?}
{239}{}{Eu estava fora da linha antes. Não vou fazer isso de novo. Eu só quero um pouco do seu tempo.}
{240}{}{Eu vou fazer o que eu quero, você comenta.}
{241}{}{Saia daqui, seu warthog!}
{242}{}{Então, o que você está fazendo aqui, merda muda? Você quer me impressionar, então faça as coisas!}
{243}{}{Eu não estou falando com você até o trabalho estar pronto!}
{244}{}{Isso me decepciona. Normalmente removo coisas que me decepcionam. No entanto, no seu caso, posso ser generoso. Apenas vá embora e não volte e vou esquecer tudo sobre isso.}
{245}{}{Então, esse pequeno negócio com o Dr. Henry fez?}
{246}{}{Sim, eu tenho os papéis que você deseja.}
{247}{}{Não.}
{248}{}{Dias como este me deixam tão feliz. Bem, vamos concluir o nosso negócio.}
{249}{}{Chegou à minha atenção que o médico engenheiro expirou durante sua visita. Isso foi contra minhas ordens. Para recuperar as perdas futuras, penso que será necessário receber um reembolso.}
{250}{}{Olha, vou dar-lhe 500 dólares e esqueceremos todo o acordo.}
{251}{}{Dane-se.}
{252}{}{Bem, sucesso em seus empreendimentos. Não vejo motivo para conversarmos novamente.}
{253}{}{Por mim tudo bem.}
{254}{}{Deal - mas apenas porque eu gosto de você. Eu sugiro que você não volte sempre em breve.}
{255}{}{Eu acho que vou simplesmente matá-lo, recuperar meu dinheiro e coletar uma recompensa. Afinal, é disso que é um bom cidadão.}
{256}{}{Você novamente! MORRER!}
{257}{}{Eu pensei que eu disse que não me incomoda mais.}
{258}{}{ e eu sou um mau amigo. Basta perguntar a qualquer um.}
{259}{}{ cara.}
{260}{}{ garota.}
{261}{}{Um Hubologist é um fanático religioso de frutos secos. Pode ser encontrado na igreja na cidade.}
{262}{}{Estou a caminho.}

{263}{}{Eu não estou falando com você até o trabalho estar pronto! I need those papers from Dr. Henry's place, pronto.}
{264}{}{Não, mas preciso de alguma informação.}
{265}{}{Eu sei que a morte de Lenny não é um acidente, seu bastardo.}
{266}{}{Ei, esse mapa era um falso.}
{267}{}{Bem, e o dinheiro que eu lhe dei?}
{268}{}{Como eu disse, desculpe, não foi para você.}
{269}{}{Bem, como você come essa bala para o meu problema.}
{270}{}{Hmmff.}

{271}{}{Você ganha}
{272}{}{exp para os papéis do Retriving Dr. Henry.}
