{100}{}{Você vê um kebabs de lagarto hawking com um homem afiado.}
{101}{}{É o vendedor de lagarto-em-um-bastão.}
{102}{}{Para um vendedor lizard-on-a-stick, esse cara tem estilo. Ele está limpo, bem vestido e corre uma pequena operação impecável.}
{103}{}{Com fome, estranho? Eu tenho o melhor lagarto por aí. Pergunte a qualquer um!}
{104}{}{O que posso fazer com você?}
{105}{}{Dê a carne.}
{106}{}{Vou pegar um.}
{107}{}{O que você pode me falar sobre essa cidade?}
{108}{}{Adeus.}
{109}{}{Aproveite, estranho!}
{110}{}{Há mostarda e cebolas por aí.}
{111}{}{Ei amigo.}
{112}{}{Sim tchau.}
{113}{}{Próximo!}
{114}{}{Olha, eu tenho uma regra. Não digo nada sobre ninguém. É uma boa regra, porque se eu manter a boca fechada, mantenho-me fora de problemas. Capice?}
{115}{}{Não escuto nada, não vejo nada e especialmente não digo nada. Agora, pare de me incomodar sobre isso.}
{116}{}{Bem. Olha, estou com fome.}
{117}{}{Você tem um GECK?}
{118}{}{Desculpe por ter preocupado, Cristo!}
{119}{}{UM GECK? Bem, essa é história antiga, então, o que diabos. Você quer dizer o antigo Kit Garden of Eden. Nós tínhamos um - quero dizer, nossos avós tinham um. Usou isso quando eles saíram do Vault 15. Este lugar começou, eles dizem. Tudo está esgotado agora.}
{120}{}{Continuo com fome.}
{121}{}{Bem, obrigado por não muito.}
