{100}{}{Você adivinharia que, mesmo com o cabelo verde e o carranca, ela é a barman desta união.}
{101}{}{Isso é Mira. Ela mistura um meio de Rad-A-Waster}
{102}{}{Bem, ela é jovem e atraente, mas há apenas um olhar em seus olhos que diz que ela não tira nada de ninguém. Isso e as pontas de ponta penduradas na corrente ao redor de seu pescoço.}
{103}{}{Mira é o nome. O que você terá, estranho?}
{104}{}{Olá de novo. O que será?}
{105}{}{Beber.}
{106}{}{Vault 13?}
{107}{}{GECK?}
{108}{}{Eu não ligo. Me dê a casa especial.}
{109}{}{Dá uma cerveja}
{110}{}{Em formação.}
{111}{}{Estou procurando trabalho.}
{112}{}{Bem, você não é o único! Assim como eu gosto deles.}
{113}{}{De volta?}
{114}{}{Yubba.}
{115}{}{Whoa - ya acabou de trabalhar com Lenny. Imprensivo! Tomar uma bebida na casa.}
{116}{}{O que você fez com Lenny - foi perverso!}
{117}{}{Oh meu, um conversacional deslumbrante. O que você vai pegar - um Rad-A-Waster? Apenas dez dólares.}
{118}{}{Sim.}
{119}{}{Não.}
{120}{}{Você vai comprar uma bebida? $ 10.}
{121}{}{Sim.}
{122}{}{Não.}
{123}{}{Um Rad-A-Waster está chegando! $ 10.}
{124}{}{OK.}
{125}{}{Dez dólares? Demais para mim.}
{126}{}{Claro, um dólar.}
{127}{}{OK.}
{128}{}{Muito dinheiro para mim.}
{129}{}{Você pode tentar Merk na sala dos fundos.}
{130}{}{Não há nada para você aqui, estranho.}
{131}{}{Obrigado, acho.}
{132}{}{Então, isso, estranho?}
{133}{}{Vault 13?}
{134}{}{GECK?}
{135}{}{Tem algum tempo para algumas perguntas?}
{136}{}{Eu vou adeus.}
{137}{}{Isso é tudo.}
{138}{}{Saia daqui, pra você, morto!}
{139}{}{Claro, eu tenho algum tempo. Isso é o que os bartenders devem fazer. Apenas não obtenha ideias.}
{140}{}{Para você, eu sempre tenho tempo, amor. O que você quer?}
{141}{}{Certo.}
{142}{}{Conte-me sobre esta cidade.}
{143}{}{Já ouviu falar do Vault 13?}
{144}{}{Estou procurando uma coisa chamada GECK. Saiba alguma coisa sobre isso?}
{145}{}{Qual é o acordo sobre esse Merk?}
{146}{}{Há um policial na cidade dizendo algumas coisas bastante difíceis sobre você. Qual é o negócio?}
{147}{}{Bem, isso mata essa idéia.}
{148}{}{Nome da NCR. Solía   ser Shady Sands, mas depois da derrota do Mestre, Aradesh e os outros fundaram a República. Agora, a NCR fica bem na fronteira. Em todo o sul da atual República.}
{149}{}{Palavra de conselho. Mantenha seu nariz limpo na cidade. Os tribunais não são muito amigáveis   com nossos tipos, se você sabe o que quero dizer. Os cidadãos obtiveram mais direitos do que você.}
{150}{}{Olha, é só isso que eu tenho a dizer sobre isso.}
{151}{}{Hmm.}
{152}{}{Mais algumas perguntas ...}
{153}{}{Bem, obrigado. Eu vou lembrar disso.}
{154}{}{Ya outro deles whackos à procura de tesouro perdido? Você deveria ver Saltbeef Bob no Westin's Ranch. Ele sempre está falando de tesouro. Talvez você precise molhar seu assobio.}
{155}{}{Saltbeef? Eu vou.}
{156}{}{Mais algumas perguntas ...}
{157}{}{Bem, obrigado. Eu vou lembrar disso.}
{158}{}{Diga-me como misturá-lo e vou derramar para você.}
{159}{}{Não há bebida. GECK é .... GECK.}
{160}{}{Não é uma bebida. É um Kit de Criação do Jardim do Éden.}
{161}{}{Mais algumas perguntas ...}
{162}{}{Bem, obrigado. Eu vou lembrar disso.}
{163}{}{Ele é um ótimo cara. Ele é meu chefe. O que você espera que eu diga?}
{164}{}{Mais algumas perguntas ...}
{165}{}{Bem, obrigado. Eu vou lembrar disso.}
{166}{}{Esse bastardo ... Foi apenas um divórcio bagunçado, só isso.}
{167}{}{Bem, que tal falar sobre outra coisa?}
{168}{}{Bem, acho que irei.}
{169}{}{Oh, muito informativo. Olha, você pode tentar o Dr. Henry na cidade, mas eu tenho outras coisas para fazer, Dumbo.}
{170}{}{Kit de criação do jardim do Eden? Soa técnico. Você pode tentar procurar Dorothy, o engenheiro da cidade.}
{171}{}{Mais algumas perguntas ...}
{172}{}{Bem, obrigado. Eu vou lembrar disso.}
{173}{}{Hmm - trabalho? Quer trabalho? Ajuda Mira?}
{174}{}{Sim.}
{175}{}{Não.}
{176}{}{Ouça, o homem pequeno machucou Mira. Nome do homem ruim Jack. Hurt um homem ruim. Mira como você, faça uma boa arma. Boa?}
{177}{}{Sim.}
{178}{}{Não.}
{179}{}{Boa! Mira tem uma corda sobre a parede. Vá de noite. Encontre corda. Sneak in. Vá o grande lugar pelo portão. Encontre Jack. Hurt Jack. Mira dá-lhe arma.}
{180}{}{Vá de noite. Encontre corda. Sneak in. Vá o grande lugar pelo portão. Encontre Jack. Hurt Jack. Mira dá-lhe arma. Agora vá embora. Eu ser visto com você - não é bom. Ajude a Mira e volte. Compreendo?}
{181}{}{Mira, Jack ficou magoado. Bom trabalho, Dumbo. Aqui, arma, pegue. Obrigado.}
{182}{}{Toque você também. Nunca serei livre desse bastardo.}
#latter additions
{183}{}{Você precisa falar com Merk, mas ele não está aqui. Volte de noite. É mais o seu tempo.}
{184}{}{Não sei o que você fez com Lenny, mas não ficaria aqui. Não vai fazer você popular.}
{185}{}{Ei, eu avisei você. Ah bem. ...}

{186}{}{Você é Mira, certo? Alguns policiais estavam falando sobre você.}
{187}{}{Você Mira? Bad Jack diz coisas.}
{188}{}{Aquele bastardo Jack? O que ele disse agora?}
{189}{}{Jack morto. Go boom.}
{190}{}{Eu mato. Ele homem ruim.}
{191}{}{Eu não me importaria com isso. Ele está morto. Explodiu-se na central eléctrica.}
{192}{}{Não muito agora. Eu o matei.}
{193}{}{Você está brincando? Essa foi a melhor notícia que tive durante todo o dia! Espero que seus cérebros tenham feito um bom papel de parede. Maldito psicótico mereceu. Tenha um Rad-a-Waster em mim.}
{194}{}{Eu gosto.}
{195}{}{Eu vou agora.}
{196}{}{Obrigado - eu acho. Diga, tem tempo para uma pergunta?}
{197}{}{Obrigado. Apenas pensei que você deveria saber.}
{198}{}{Você fez o que? Ah, se eu não estivesse de plantão, eu iria subir sobre esse bar e ... bem, beijar você. A pequena espinha mereceu. Na verdade, não conte a ninguém, mas eu estava esperando para obter algum boi estúpido para fazer o trabalho para mim. Tinha uma pequena recompensa reservada. É seu agora - no que me diz respeito, você ganhou.}
{199}{}{Obrigado - eu acho. Diga, tem tempo para uma pergunta?}
{200}{}{Obrigado. Apenas pensei que você deveria saber.}
{201}{}{Dumbo, você me fez a mulher mais feliz! Tenho um pequeno presente para você, logo atrás do bar. É todo seu.}
{202}{}{Eu, como Mira.}
{203}{}{Eu como arma. Eu vou adeus.}
