{100}{}{Parece outro cara que pensa mais com os punhos do que a cabeça dele.}
{101}{}{Hmmm. Um dos guardas de Merk.}
{102}{}{Grande. Resistente. Burro. Escolta.}
{103}{}{Retire-se. Dê ao Sr. Merk seu espaço.}
{104}{}{Uhh ...}
{105}{}{Não devo conversar com ninguém de plantão.}
{106}{}{Você nos dá problemas, é por isso que estou aqui. Compreendo?}
{107}{}{Por que você não segue, ok?}
{108}{}{Não me incomode.}
{109}{}{O Sr. Merk não quer ser perturbado.}
