{100}{}{Você vê um homem vestindo um crachá da polícia NCR.}
{101}{}{É Jack, deputado assistente da lei NCR.}
{102}{}{A ferida desse cara mais apertada do que uma mola de relógios. Sua mandíbula está permanentemente apertada, as veias se destacam em sua testa, e não há um lugar de alegria ou felicidade em qualquer lugar nele.}
{103}{}{Eu não quero ouvir seus problemas agora. Leve para outra pessoa.}
{104}{}{Você sabe, eu não tenho que aguentar isso - de você ou de qualquer pessoa.}
{105}{}{Maldita ex-esposa me levou por tudo o que tinha.}
{106}{}{Ela fez um tolo fora de mim, você sabe. Ninguém se engana de Jack.}
{107}{}{Um desses dias eu vou mostrar a ela. Vou mostrar a todos ...}
{108}{}{O que você está olhando? Scram!}
{109}{}{Morde-me! Este é Jack! As pessoas melhor me escutam agora!}
{110}{}{Recebi uma bomba aqui, então não tente nada!}
{111}{}{As pessoas sempre riem de Jack, chamando-o de Whack Jack - bem, quem está rindo agora?}
{112}{}{Eu estou contando com três e se Mira não está aqui até então, eu vou explodir o lugar. 1...}
{113}{}{Dois...}
{114}{}{Três....}
{115}{}{O que você quer? Por que você está olhando para mim?}
{116}{}{Deixe-me em paz, entenda?}
{117}{}{Maldita ex-esposa - é culpa sua.}
{118}{}{Fique atrás! Eu tenho uma bomba!}
{119}{}{Não faça isso, Jack. Há sempre uma solução melhor.}
{120}{}{Uhh - pare.}
{121}{}{Sim claro. O que você saberia sobre isso?}
{122}{}{Eu sei que as coisas às vezes parecem ruins, mas soprar as coisas não resolve nada.}
{123}{}{Nada. Não conheço porcaria sobre seus problemas. Talvez seja melhor você me contar.}
{124}{}{O que é isso: algum tipo de truque? Stall Jack até que seus amigos venham matá-lo?}
{125}{}{Quem quer matar você?}
{126}{}{Não se preocupe, ninguém vai te machucar.}
{127}{}{Essa puta da minha ex-esposa, Mira, por um lado. Ela quer me morrer.}
{128}{}{Então, deixe a lei lidar com ela. Não assim, Jack.}
{129}{}{Você está certo. Ela me contratou para matar você. Então o que você diz? Que tal, Jack?}
{130}{}{Quem é o inferno Mira?}
{131}{}{Tudo bem, bastardo. Vamos fazer isso!}
{132}{}{Que piada! Eu sou a lei. Veja o que é bom.}
{133}{}{Jack, pense nisso.}
{134}{}{Então, explodir o powerplant vai consertar Mira?}
{135}{}{Como eu disse. O meu ex. Eu a pego dormindo e agora ela está dizendo que eu sou o cara mau. Peguei o tribunal para lhe dar tudo e ela ainda está tentando me ferrar.}
{136}{}{Whoa - isso é difícil. Completamente injusto.}
{137}{}{Você pode se recuperar. Tudo passa com o tempo. Ela vai se esquecer de você.}
{138}{}{Claro ... Não. Crap, eu não sei. Tenho que fazer alguma coisa. Deixe as pessoas saberem que não podem andar por Jack.}
{139}{}{Eles sabem, Jack. Olhe para eles. Você exploda-se agora e eles não o respeitarão.}
{140}{}{Olhe, pense disso. Explodir este lugar e apenas provará tudo o que ela diz sobre você.}
{141}{}{Não é brincadeira, Sherlock. Agora as pessoas vão me ouvir.}
{142}{}{Ninguém vai te ouvir com uma bomba em suas mãos. Coloque-o para baixo, venha para fora, e podemos resolver isso.}
{143}{}{Olhe, pense disso. Explodir este lugar e as pessoas vão dizer: "Jack tomou o caminho fraco. Deixe-se ser empurrado por sua ex-esposa". Ela ganha, você perde.}
{144}{}{Você realmente pensa assim?}
{145}{}{Sim, Jack. É verdade.}
{146}{}{Claro. O que você acha? Estou mentindo?}
{147}{}{Eu não sei.}
{148}{}{Não deixe que ela vença, Jack.}
{149}{}{Agora é a sua chance. Seja o grande homem. Realmente a detém para baixo.}
{150}{}{Aperte. Você está cheio disso. Você não se importa comigo!}
{151}{}{Ah, inferno, talvez você esteja certo. Esta não era a melhor idéia de qualquer maneira.}
{152}{}{Eu teria feito isso, você sabe.}
{153}{}{Damn Mira, agora ela conseguirá o dela.}
{154}{}{Agora as pessoas sabem quem é Jack, com certeza.}
{155}{}{Apenas volte! Eu não quero machucá-lo!}
{156}{}{Isso não diz respeito a você!}
{157}{}{Vá em frente, mate-me. O que eu mais me importo?}
{158}{}{Esta não é a sua luta. Me deixe em paz.}
{159}{}{Eu explico ou você me mata. O que é importante?}
{160}{}{Não estou tentando machucá-lo! Só quero que eles se lembrem ...}
{161}{}{Você ganha}
{162}{}{ Experiência para cuidar de Jack para Mira.}
