{100}{}{Você vê um homem com roupas sujas e manchadas de sangue.}
{101}{}{É o prisioneiro que eles pegaram.}
{102}{}{Seu rosto e braços têm uma escotilha cruzada de velhas cicatrizes de faca e há um olhar enlouquecido em seus olhos que diz que ele é um brawler e um fora da lei.}
{103}{}{Você está perdendo seu tempo. Não tenho palavra para dizer a você ou a qualquer outra pessoa.}
{104}{}{Vá embora e me deixe em paz, porco.}
{105}{}{Será que de repente cheira mal aqui?}
{106}{}{O que você vai fazer - me assuste em falar?}
{107}{}{Você não me assusta.}
{108}{}{Por que você não beija minhas botas?}
{109}{}{Que diabos? Você está tentando me matar! Guarda!}
{110}{}{Fale ou eu mate você.}
{111}{}{Ninguém está vindo para ajudá-lo. Se você quiser viver, você fala.}
{112}{}{Está bem, está bem! O que você quer saber? Apenas não me machuque de novo.}
{113}{}{Vault 15 - você conta.}
{114}{}{O que você conhece sobre o Vault 15?}
{115}{}{Olha, sou apenas um cara, não o cara responsável - é Darion. Ele é o que você deseja. Ele tem essa coisa sobre Shady Sands e aquela velha cadela Tandi. Ele tem um esconderijo no Vault 15, até que os habitantes locais pensem que ele está do lado deles. Isso é tudo que eu sei. Honesto!}
{116}{}{Realmente, eu não sei mais nada! Eu contei-lhe tudo o que sei, realmente! Não me machuque mais.}
{117}{}{De jeito nenhum! Eu não estou me apaixonando por esse truque. BANG! - abatido enquanto escapava. Esqueça!}
