{100}{}{Você vê um habitante da cidade.}
{101}{}{Você vê o local do povo local.}
{102}{}{Não há nada referente à maneira como essa pessoa se parece.}
#Personal Enemy
{103}{}{Ahhh, deixe-me.}
{104}{}{Sinto muito. Não vou fazer isso de novo.}
{105}{}{Eu estava indo embora.}
{106}{}{Guardas, ele está de volta!}
{107}{}{Por favor, deixe-me só.}
{108}{}{Olha, eu também não quero estar à sua volta.}

#Child Killer
{109}{}{Você é apenas um mal. Por favor, não fale comigo.}
{110}{}{Deixe nossos filhos sozinhos.}
{111}{}{Você é um tipo de criminoso doente. Espero que os guardas o peguem.}
{112}{}{Apenas vá embora, ok?}
{113}{}{Ei, você não deve matar ninguém - especialmente crianças.}
{114}{}{Eu não acho que eu gosto de você.}

#Berserker
{115}{}{Ei, deixe-me saber quando você vai para o correio.}
{116}{}{Eu tenho que ir.}
{117}{}{Quem diabos você acha que está - entrando nesta cidade?}
{118}{}{Apenas vá embora antes que alguém se machuque.}
{119}{}{Eu não gosto de você.}
{120}{}{O justo matará tudo como você.}

#Low Town Rep
{121}{}{Qual é o seu problema?}
{122}{}{Não podemos simplesmente nos dar bem?}
{123}{}{Não fale comigo.}
{124}{}{Seja o que for, diga a outra pessoa.}
{125}{}{Eu não acho que você é tão difícil.}
{126}{}{Por que você não vai embora?}

#normal
{127}{}{Bem, eu tenho que pegar alguns ovos.}
{128}{}{Você sabe como colocar o tapume de lata?}
{129}{}{Olá.}
{130}{}{Por favor, não me incomode, estou muito ocupado.}
{131}{}{Gostaria de saber se há mais hamburgueres de brâmane na Dusty's.}
{132}{}{Às vezes eu me pergunto para onde eu estou indo.}
{133}{}{Umm, obrigado, eu realmente tenho que ir.}
{134}{}{Mais tarde podemos fazer o almoço.}
{135}{}{Ohh, sim, você é o novo cara da cidade.}
{136}{}{Você deveria conversar com o xerife.}

{137}{}{Ouça que eles estarão construindo novas casas em breve.}
{138}{}{A cidade está bastante tranquila desde que Dumont foi eleito.}
{139}{}{Bom dia, estranho.}
{140}{}{Lugar bastante tranquilo que chegamos aqui. Bom, eh?}
{141}{}{Novo na cidade? Veja o lugar do meu primo Duppo.}
{142}{}{Eu ouço que os tempos são difíceis para o sul. Quando o governo vai fazer alguma coisa?}
{143}{}{Você do norte? Não tenha muitos norther aqui.}
{144}{}{Ouvi dizer que todo mundo da terra desolada é um mutante ou um selvagem!}
{145}{}{Não há tempo para conversar. Tenho que começar a trabalhar.}
{146}{}{Eles estão tendo uma venda no Duppo's? Oh, não importa.}
