{100}{}{Parece mais um outro barfly.}
{101}{}{O mesmo bêbado que você viu na última vez.}
{102}{}{Não se parece às mais bonitas, mas com muita bebida, quem faz?}
{103}{}{Olha, eu apenas estou bebendo. Me deixe em paz.}
{104}{}{Eu não falo com estranhos. Mau por sua saúde neste bar.}
{105}{}{Já ouvi sobre você. Porra, mas você não está no lugar errado!}
{106}{}{Você quer problemas? Vá falar com o Merk.}
{107}{}{Ei, de boa aparência, você quer ir em algum lugar privado e se divertir um pouco?}
{108}{}{Não fale comigo! Eu não quero outra onda.}
{109}{}{Maldito whisky barato! Sabe, eles servem o pior licor aqui.}
{110}{}{Merda! Não queria derramar minha bebida em você. Deixe-me limpar isso. Desculpe, desculpe.}
{111}{}{Fique longe de mim!}
{112}{}{Já ouvi sobre você. Por favor, não me bata.}
{113}{}{Novo na cidade? A palavra é a de Merk à procura de homens duros.}
{114}{}{O que você é, um tipo de cara difícil? Saia da minha cara!}
{115}{}{Nunca deveriam ter feito isso. Algum dia estranho, vou ter uma arma e depois vou mostrar-lhes.}
{116}{}{Como você gosta de ser minha escrava amorosa, bonita?}
{117}{}{Beber e falar - inferno, nada excitante nunca acontece nesta cidade.}
{118}{}{Vá embora, você está me incomodando.}
{119}{}{Você ouviu aquele sobre ...}
{120}{}{Então eu digo a ele: "Olhe", eu digo ...}
{121}{}{Experimente o mole-ratão assado. É o melhor ao redor.}
{122}{}{Oi. Qual é o seu signo?}
{123}{}{Se você está procurando trabalho, estranho, vá até o Stockmen's.}
{124}{}{Merda! Você viu aquilo?}
{125}{}{Oh cara, eu vou ficar doente.}
{126}{}{Não há mais para mim.}
{127}{}{Ei, me misture um desses!}
{128}{}{Eu tinha um Rad-a-Waster como esse uma vez ...}
