{100}{}{É um monte de trapos que podem ter uma pessoa debaixo disso.}
{101}{}{Você vê Ratch, provavelmente pegando alguns piolhos.}
{102}{}{Pode ser um ser humano. Pode ser um mutante. Tudo o que você pode dizer com certeza é que cheira realmente, muito ruim.}
{103}{}{Lixo para venda, lixo para venda. Procure, faça uma oferta.}
{104}{}{Claro, seja o que for.}
{105}{}{Uh ... hein.}
{106}{}{Então, o que está à venda?}
{107}{}{Você parece ser bom com suas mãos. Você tem as mãos, não é?}
{108}{}{Eu recebi US $ 5. Você tem boas fofocas?}
{109}{}{Adeus.}
{110}{}{Veja aquele lá? Esse é o meu favorito - esse é Edna. Eu nomeo todas as minhas coisas, veja - elas são como chidlren para mim. Odeio ter que vendê-los, mas eu tenho que comer.}
{111}{}{Você está mexendo com todos os meus filhos!}
{112}{}{Okay, certo. Aqui está um fiver. Você conhece boas fofocas?}
{113}{}{O-kay - você não é apenas especial! Talvez eu devesse comprar outro lugar.}
{114}{}{Deixe-me olhar seu estoque novamente.}
{115}{}{Eu acho que eu e Edna irão agora.}
{116}{}{Bem, graças a Deus, esse estranho não te levou criança ... Meu material é como meus filhos, veja.}
{117}{}{Uhh - claro.}
{118}{}{Bem, acho que vou agora.}
{119}{}{Posso consertar todo tipo de coisas. Obtive-me um ventilador, chamou-o de Claudia, se encaixa na maioria dos carros - dê muito mais poder. Apenas US $ 1000. Estás interessado?}
{120}{}{Manequim, já falamos sobre isso.}
{121}{}{Você aposta, Claudia é o meu tipo - o que quer que seja.}
{122}{}{Talvez outra coisa.}
{123}{}{Ouvi dizer que há um doc aqui na cidade, diz que ele tem alguma cura milagrosa. Eu não estou aceitando isso ...}
{124}{}{Depois, há Saltbeef. Old Coot diz que encontrou uma mina de ouro ...}
{125}{}{Miss Dorothy e Toto estavam aqui na semana passada, procurando por algumas partes para consertar o powerplant. Eu não poderia ajudá-los, no entanto ...}
{126}{}{Há conversa na cidade de que o que aconteceu com Westin não foi um acidente. Algumas pessoas acham que há muitos desconfiados desconhecidos ...}
{127}{}{Obrigado pelo dinheiro, mas não sei mais nada.}
{128}{}{Aqui está outro fiver.}
{129}{}{Posso ver suas coisas?}
{130}{}{Bem, obrigado pela informação.}
{131}{}{Bem, dê seis horas. Eu deveria tê-lo corrigido até então.}
{132}{}{Antes de você, um pouco mais do seu tempo.}
{133}{}{Bom o bastante. Vejo você mais tarde.}
{134}{}{Olha, se você receber o dinheiro, volte. Provavelmente ainda vou ter.}
{135}{}{Justo.}
{136}{}{Adeus.}
{137}{}{Lá está ela! Claudia está tudo instalado.}
{138}{}{Dê um pouco mais de tempo. Ainda estou trabalhando na coisa mais complicada.}
{139}{}{Uau! Eu não acho que tenho um cérebro de reposição para você.}
