{100}{}{Você vê um estranho meio cão, meio metal. Parece estar ativado.}
{101}{}{É Robodog! O animal de estimação favorito de todos!}
{102}{}{Ou essa coisa é uma combinação horrível combinada de cachorro e máquina ou é toda a máquina, assustada para se parecer com um cachorro. É difícil dizer.}
{103}{}{Arf! <Clique> Woof!}
{104}{}{... bzzzzzz ...}
{105}{}{.whirrrr ... Eu não sou um Daggit.}
{106}{}{Grrrrrrrrrrrrrrr--}
{107}{}{Woof! Wo-wo-wo- <clique> woof.}
{108}{}{<Sprzzzt> Meow ... erro.}
{109}{}{Barkbarkbarkbarkbarkbarkbark!}
{110}{}{Grrr ...}
{111}{}{Como-woooo! <Clique-clique> How-wooo!}
{112}{}{Yipe! Yipe! Yipe!}
{113}{}{Perigo! Perigo!}
{114}{}{Rowf! <Tick-tick-tick> Rowf!}
{115}{}{<Whirrr> Não pássaro, nem avião, nem mesmo sapo, apenas lil 'old me - Robodog! <Clique>}
{116}{}{Rooby-Doo!}
{117}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{}{Woof!}
{119}{}{GRRR-ROWF!}
{120}{}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{Está bem}
{122}{}{Eu não acho que eu quero voltar para você ainda. Adeus.}
{123}{}{Rowf? <Boing> Raggy?}
{124}{}{Como você está?}
{125}{}{Preciso que você espere até eu voltar.}
{126}{}{É por enquanto.}
{127}{}{<Clique> chorão}
{128}{}{Deixa pra lá.}
{129}{}{Está bem}
{130}{}{HP:}
{131}{}{O Cyberdog já não pode ser reparado neste momento.}
{132}{}{Cyberdog foi reparado por alguns.}
{133}{}{O Cyberdog está tudo pronto.}

#specific party messages
{1000}{}{Woof! Wo-wo-wo- <clique> woof?}
{1100}{}{Arf! <Clique> Woof!}
{1200}{}{Rowf? <Boing> Raggy?}
{1300}{}{<Clique> chorão.}
{1400}{}{Como-woooo! <Clique-clique> How-wooo!}
{1500}{}{Ee-bee-dee-bee-ee-bee-dee-bee!} //Wait here resoponse
{1600}{}{Certo, vou deixar isso longe.}  //Put weapons away
{1700}{}{Arf-arf proximidade definida para fechar.} //Close
{1800}{}{A proximidade de Arf-arf é definida para médio.} //Medium
{1900}{}{A proximidade de Arf-arf é definida como distante.} //Far
{2000}{}{.whirrrr ... Eu não sou um Daggit.}
{2100}{}{GRRR-ROWF!}
{2200}{}{Woof! Wo-wo-wo- <clique> woof?}

{2204}{}{Ok, está a uma boa distância por enquanto.}
