{100}{}{Você vê um homem com roupas manchadas de gordura, provavelmente um mecânico.}
{101}{}{É Rondo, dono desta articulação.}
{102}{}{Você acha que ele é um mecânico, mas ele está usando uma armadilha que parece um pouco estranha.}
{103}{}{Saudações, guarda florestal. O tempo tem sido bom, espero.}
{104}{}{Algum dia vamos acabar com esses escravos.}
{105}{}{Bem (nome do jogador), o resto está de volta.}
{106}{}{Desculpe, estamos sem negócios.}
{107}{}{Esta é uma propriedade privada. Você se importa?}
{108}{}{Eu não estou trabalhando mais agora, ok?}
{109}{}{Ei, bastardo, você não deve mexer com os Rangers.}
{110}{}{Toque qualquer uma das minhas coisas novamente e eu vou ter que abrir o 'bessy' em você.}
