{100}{}{Você vê um homem velho e sujo com cabelos fibrosos.}
{101}{}{É o cara que eles chamam de Saltbeef Bob}
{102}{}{Ele tem cerca de três dentes e um rosto atravessou as pequenas veias de um bêbado. Ele também cheira ruim.}
{103}{}{Howdy, estranho!}
{104}{}{Gruh?}
{105}{}{Quem é Você?}
{106}{}{Nome do Bob. Saltbeef Bob, sim. E quanto a você?}
{107}{}{O que você disse que seu nome era novamente, estranho? Eu sou Saltbeef Bob.}
{108}{}{[Nome do jogador]}
{109}{}{Saltbeef? Que tipo de nome é esse?}
{110}{}{O que você está fazendo aqui?}
{111}{}{Esse é um nome bom, sim. Diga que você não tomaria uma bebida, pardner?}
{112}{}{Sim.}
{113}{}{Não.}
{114}{}{Afaste-se de mim, seu vago fedorento!}
{115}{}{Bem, não há necessidade de ser grosseiro com isso. Só queria um pouco de sorvete, veja. Mantenha meus nervos ...}
{116}{}{Hoo-wee! Parece que você conseguiu um bom sucesso aqui! Diga, a respeito de compartilhar um pouco? Apenas um pequeno sorvo.}
{117}{}{Beber! Boa!}
{118}{}{Grrrg!}
{119}{}{Fácil, pardner! Não posso culpar um homem perguntando, pode? Vou deixá-lo então.}
{120}{}{(Gulp, gulp, gulp) Aaaahhhh! Está bem, você é estranho! Boa pessoa, na verdade. Um homem deveria ter como seu pardner. (Gole)

Eu já lhe contei sobre o tempo que fiz a minha grande greve?}
{121}{}{Não?}
{122}{}{Ei, deixe de beber todas as minhas bebidas!}
{123}{}{Rahhhg!}
{124}{}{Estava de volta no '78 e eu e Bessie - o melhor 'bot que um homem já teve - nós fomos u-ra-ni-um prospectando o oeste do' aqui. Não tínhamos aparecido o valor de um valor de rad's quando de repente cinco - não, tenho certeza de que eram dez - os mortandras nos saltaram.}
{125}{}{Eles lutaram como hellcats. Eu disparei tanto que derreti meu tambor de rifle e estava indo na faca deles para garra quando o velho Bessie finalmente fundiu sua última placa de circuito. Bem, eu tentei salvá-la, mas isso não ajuda. Finalmente, teve que cortar e correr, mantendo-os com rochas até o final.}
{126}{}{Bem, as coisas pareciam ruins quando eu me deparei com essa caverna. Pensei que eu estava com certeza. Imaginei que eram suas guaridas - mas eu tive minha tocha, então entrei. Hoo-wee, era uma caverna profunda. E foi quando eu vi.}
{127}{}{Era uma grande porta grande, como eles tipos que você vê nos velhos vídeos. Grande e feito de aço. Um sobre ele foi esculpido um grande, grande 13!}
{128}{}{Eu sabia que eu achava isso, a mãe lode, o Vault 13. Sentei-me e fiz um mapa. Maldito perto, morreu saindo, lá fora, passando as pernas mortíferas e depois o sol do deserto e sem água.}
{129}{}{Quando cheguei em Shady Sands, eu estava quase morto. Me levou ao doc e me corrigiu, mas esse documento roubou meu mapa. Eu sei disso e é tudo o que eu sei dizer.}
# took this out -- Got anymore o' that drink, stranger?
{130}{}{(Continuar)}
{131}{}{Tarnation, é um nome bom e honesto, é o que é! Os meninos me deixaram cozinhar por aqui e, se você não fosse um tinhorn, você saberia isso e sabia respeitar seus anciãos.}
{132}{}{Desculpe, o veterano não queria torcer você.}
{133}{}{Bem, morda-me, temporizador antigo!}
{134}{}{Rile me? Rile me! Você ainda não me viu irritado! Agora, jes 'git outta minha visão antes que você me deixa realmente chateado! Gwan! Git!}
{135}{}{Bem, morda-me também! Agora está falando. Não tire nenhum lábio de ninguém, pardner!

Diga, você conseguiu algum hooch em você? Só um pequeno sorvo?}
{136}{}{Sim.}
{137}{}{Não.}
{138}{}{Afaste-se de mim, bum fedorento!}
{139}{}{Hee, hee, hee! É meu agora, pardner. Você vai ter que encontrar seu próprio!}
{140}{}{Chefe, deixe-me ficar aqui. Eu corro esse estábulo! Faça um pouco de limpeza, mantenha um acampamento quadrado.}
{141}{}{Saltbeef? Que tipo de nome é esse?}
{142}{}{Prazer em conhecê-lo. Eu estou}
{143}{}{Inferno e trovão, você novamente? Git Yer Scrawny ass fora da minha visão!}
{144}{}{Morde-me!}
{145}{}{Você é um fiesty, temporizador antigo}
{146}{}{Maldito seja mesmo! Você não tem um pouco de bebida com você, você agora? Fer um homem velho.}
{147}{}{Sim.}
{148}{}{Não.}
{149}{}{Afaste-se de mim, bum fedorento!}
{150}{}{.}
