{100}{}{Você vê um homem de cabelos grisalhos no uniforme da polícia da NCR.}
{101}{}{É o xerife da NCR.}
{102}{}{Esse sujeito é tão regulador quanto eles vieram - tripulação cortada e prateleira, um verdadeiro tipo de bobagem sem sentido.}
{103}{}{Bem-vindo à NCR, estranha. Name Dumont - Sheriff Dumont. Espero que você tenha um bom momento de paz aqui.}
{104}{}{Dê uma palavra de conselho do xerife Dumont, estranho - esta cidade não se importa com o seu tipo. Qualquer problema e eu descer com dificuldade. Agora, há algo que eu possa fazer por você?}
{105}{}{Olá de novo. Algo que eu possa fazer por você?}
{106}{}{Bem, cuspi-lo.}
{107}{}{Urrgh.}
{108}{}{Estou procurando o Vault 13. Você sabe onde está?}
{109}{}{Você tem um GECK?}
{110}{}{Estou procurando algum trabalho honesto. Pode me ajudar?}
{111}{}{Oh, tudo bem. Tudo foi apenas peachy.}
{112}{}{Primitive, hein? Você. Questões? Me pergunte. OK?}
{113}{}{Vault 13?}
{114}{}{GECK?}
{115}{}{OK.}
{116}{}{Não, eu não. Isso é mesmo até o presidente Tandi gostaria de saber. Resolva muitos problemas.}
{117}{}{Problemas?}
{118}{}{Presidente Tandi?}
{119}{}{Ótimo. Apenas minha sorte. Obrigado.}
{120}{}{Ouça, eu lanço uma vida limpa e saudável! Eu não tenho GECK ou qualquer outra coisa.}
{121}{}{Desculpa! O que você sabe sobre o Vault 13?}
{122}{}{Vamos esquecer que perguntei. Vou deixá-lo em paz agora.}
{123}{}{Posso pensar em algumas coisas, se você estiver realmente interessado.}
{124}{}{Você está brincando certo? Depois do que você fez com Jack? Suponho que você possa encontrar um trabalho constante.}
{125}{}{Como o quê?}
{126}{}{Não, vamos mudar o assunto.}
{127}{}{Esqueça, eu mudei de idéia. Adeus.}
{128}{}{No Vault 13. Vault 15, sim.}
{129}{}{Quinze?}
{130}{}{Não. Thir-teen!}
{131}{}{Sim, 15! Você fala com Tandi. Grande chefe NCR. Tandi conhece o Vault. Quero ajuda. Você vai Tandi.}
{132}{}{Tandi?}
{133}{}{Não vá. Quer 13!}
{134}{}{Ouço. No Vault 13. Nenhum achado. Não veja. No 13. Vault 15 - as pessoas acham. As pessoas vivem no Vault 15. Você entende?}
{135}{}{No thir-teen? Quinze?}
{136}{}{NÃO. QUERO TERCEIROS!}
{137}{}{Arrgh! NÃO HÁ 13, VOCÊ DUMB CAIXA DE ROCHAS! Não 13. Nenhum achado. Nunca! Sempre!}
{138}{}{Tandi, grande chefe. Tandi quer ajuda. Você fala com Tandi. Vá casa Con-gress. OK?}
{139}{}{GECK?}
{140}{}{OK.}
{141}{}{Sem GECK. Eu saudável. Não doente.}
{142}{}{Vault 13?}
{143}{}{OK.}
{144}{}{Olhe a sua volta. NCR é um lugar crescente. Precisamos de peças, computadores, outras coisas. Foi um problema desde que esses invasores se mudaram para o Vault 15.}
{145}{}{Vault 15? Squatters? O que está acontecendo?}
{146}{}{What's this about Presidente Tandi?}
{147}{}{Obrigado pela informação.}
{148}{}{Presidente da NCR, quem mais? As coisas a deixaram tão preocupada que ela mesmo pediu emprestar um de meus deputados para uma missão especial. Odiava desviá-la, mas não posso poupar a mão-de-obra.}
{149}{}{E quanto a mim? Talvez você possa me recomendar.}
{150}{}{Hmm. Vida difícil, eu acho.}
{151}{}{Você? Hmmm ... não pude. Nem conhece você - mas ela está procurando contratar alguém para que você possa conversar com ela. Seu escritório está no Salão do Congresso.}
{152}{}{Obrigado. Eu farei isso.}
{153}{}{Saiba alguma coisa sobre um GECK?}
{154}{}{Bem, tudo bem com você, estranho - e muito presunçoso, também. Eu não conheço você de Adão e Eva e não gosto da maneira como você parece! Não estou recomendando você a ninguém. Agora, tenho trabalho a fazer.}
{155}{}{Bem, há Duppo no Stockmen. Ele faz a contratação para as unidades brahmin. Depois, há o Sr. Westin. Se você falar com ele, diga-lhe que eu enviei você. Mesmo o presidente Tandi perguntou por alguma ajuda.}
{156}{}{Duppo up na Stockmen's Association discute as mãos para as unidades brahmin. Vá tentar ele.}


{157}{}{Westin?}
{158}{}{Presidente Tandi?}
{159}{}{Tenho que ir.}
{160}{}{Roger Westin. Sua propagação é apenas pelo portão oeste. Ele tem tido algum problema com os varmits. Ele cuidaria dele mesmo, mas sua saúde não é o que costumava ser. Carrapato, diz Doc Jubilee.}
{161}{}{Sim?}
{162}{}{Algum trabalho a ser realizado nesta cidade?}
{163}{}{Deixa pra lá. Vou.}
{164}{}{Certifique-se de que as coisas permaneçam assim. Adeus.}
{165}{}{Esse é um excelente trabalho que você fez com o velho Jack, estranho. Como o xerife, vou tomar se daqui.}
{166}{}{Ele é todo seu.}
{167}{}{E quanto a uma recompensa?}
{168}{}{Bem, não posso dizer que tenho dinheiro de recompensa para dar. O melhor que posso fazer é o meu obrigado.}
{169}{}{Esperar. Eu tenho algumas perguntas.}
{170}{}{Oh, eu entendo tudo bem.}
{171}{}{Desculpe, não posso falar agora. Já estou atrasado para o inquérito do forense. Parece muito claro para mim.}
{172}{}{Desculpe, sem crime, sem tempo.}
{173}{}{Ratos do deserto. Você deve entender - esta cidade traça suas raízes de volta a 15. Parece que houve algum problema lá há muito tempo e os sobreviventes fundaram Shady Sands. Então, por direito, o Vault 15 é nossa propriedade. Poucos anos atrás, alguns invasores se mudaram e já houve problemas desde então. Você deveria conversar com Tandi sobre isso.}
{174}{}{Tandi?}
{175}{}{Eu tomarei isso sob consulta.}
{176}{}{Não há mais trabalho que eu esteja ciente.}
{177}{}{Duppo up na Stockmen's Association discute as mãos para as unidades brahmin. O presidente Tandi vem perguntando por alguma ajuda.}
{178}{}{Qualquer outra pessoa da sua estatura deixaria a cidade e muito menos procuraria o trabalho.}
{179}{}{Duppo up na Stockmen's Association discute as mãos para as unidades brahmin. Vá tentar ele. Then there's Mr. Westin. If you talk to him, tell him I sent you.}
