{100}{}{Você vê um punk fino.}
{101}{}{É Doofus, o ônibus do carro.}
{102}{}{Este cara é uma erva pequena áspera, torções cheias e tiques, sem dúvida uma dependência de algo.}
{103}{}{Isso é bom transporte, cara, muito bem! Oh cara, eu sou o único para você - assista seu carro, mantenha-o seguro dos percevejos. Cinco dólares, não há problema. Cinco dólares e Doofus estão no trabalho! Nunca durma - 24 horas, sempre lá, cara.}
{104}{}{Eu sou o carro hop, cara. Eu assisto carros - $ 5. Ninguém os toca, porque Doofus está no trabalho.}
{105}{}{Certo, certo, homem.}
{106}{}{Então, homem, você quer minha proteção?}
{107}{}{Boa. Faz..}
{108}{}{Não. Não toque.}
{109}{}{Eu não sou um homem!}
{110}{}{Que lugar é esse?}
{111}{}{Combinado. $ 5 - você assiste o carro.}
{112}{}{Perda, skuzz!}
{113}{}{Whoa man, há como esse gigante falando comigo! Isso é tão legal ou o quê?}
{114}{}{Gurg?}
{115}{}{Eu não sou um homem!}
{116}{}{Que lugar é esse?}
{117}{}{Está certo. Eu sou um gigante muito poderoso! Você vai me obedecer.}
{118}{}{Junkie inútil - perca-se!}
{119}{}{O que você quer com Doofus, cara?}
{120}{}{Whoa, nos conhecemos antes? O que posso fazer para você?}
{121}{}{Certo, certo, homem.}
{122}{}{Squa?}
{123}{}{Eu não sou um homem!}
{124}{}{O que você faz?}
{125}{}{O que é este lugar?}
{126}{}{Nada. Achei que você era outra pessoa. Tchau.}
{127}{}{Whoa, cara, eu avisei você. Lugar ruim. Gente má por aqui. Ouvi dizer que o seu transporte ganhou.}
{128}{}{Brak?}
{129}{}{Como você sabia?}
{130}{}{Ótimo. Obrigado. Bem.}
{131}{}{Doofus irá executar, cara. Nem mesmo uma mosca vai pousar sua merda no seu au-to-mo-bile!}
{132}{}{O que é este lugar?}
{133}{}{Boa. Cale-se.}
{134}{}{Se você não tem o macaco, basta sair daqui! Eu tenho coisas importantes para fazer.}
{135}{}{Ei cara, Doofus avisou você.}
{136}{}{Foda-se. Não respondo às suas perguntas.}
{137}{}{O que é este lugar?}
{138}{}{Adeus}
{139}{}{Tchau tchau.}
{140}{}{Whoa, pensou comunicação! Estou pegando vibrações mentais! Ok, deixe-me tentar ... uhhh ... Uhhh ...}
{141}{}{Sim?}
{142}{}{Não?}
{143}{}{Você é um maldito caso de cabeça! Estou fora daqui.}
{144}{}{Esta é a NCR - a República Nova da Califórnia alta, poderosa, justa, absolutamente e sempre correta. Eles são os únicos que levará as pessoas como nós a sair do deserto e no futuro novo e perfeito. Você pode cavá-lo?}
{145}{}{Vamos terminar este negócio}
{146}{}{Yeah, thanks. Adeus.}
{147}{}{Gurg, spaal ladal!}
{148}{}{TAK!}
{149}{}{Doof? Ganya kulk zar!}
{150}{}{Certo - obedeça o gigante, cara. É assim que as coisas deveriam ser. O que devo fazer, gigante?}
{151}{}{O homem é muito. Gigante, eu sou Doofus e eu sou um ônibus e eu deveria assistir a carros que as pessoas trazem aqui, mas, você sabe, eu entendi isso, vejo, e às vezes eu preciso de um pouco de dinheiro extra e Coisas, veja?}
{152}{}{Okay, certo. Então, às vezes, eu sou um pouco curto e eu tenho minhas necessidades, entendo, como quando eu começo a me sentir doente, então eu tenho que me marcar algumas tampas ou algo assim, então vou falar com o Merk.}
{153}{}{Cara, Merk é o homem. Ele tem ação e coisas. Às vezes ele me deixa dormir no Rawhide depois de fechar. Mas então ele quer que eu faça pequenos favores.}
{154}{}{Estou chegando a isso - uau, as cores, cara! Merk ele às vezes quer coisas de carros que eu assisto. Mas eu o engano!}
{155}{}{Veja que eu só pego dos carros. Não pago para assistir. Ele acha que estou engolindo meus clientes, mas não faço isso.
   Cara, eu tenho que parar de falar. Eu gosto de ver coisas ... oh, cara, o brilho. É tudo sobre incandescência.}
{156}{}{Me dê todas as suas coisas.}
{157}{}{Diga-me o que você sabe.}
{158}{}{Isso basta, não posso aguentar mais.}
{159}{}{Oh, cala a sua merda idiota!}
{160}{}{Tchau tchau.}
{161}{}{Ah voce sabe. Às vezes eu ouço coisas. Eu ouço muito; Nem sempre lembro disso.}
{162}{}{$ 50 dólares dizem que você se lembra disso.}
{163}{}{Lembre-se ou eu explodir sua cabeça de merda.}
{164}{}{Aperte isso. Não tenho tempo para desperdiçar com um viciado.}
{165}{}{Isso mesmo, cara. Vá ver Merk. Ele sempre tem as coisas que precisam fazer.}
{166}{}{Vá adeus!}
{167}{}{Oh cara, você explodiu! Merk não vai ficar feliz quando ele ouvir isso.}
{168}{}{Adeus, dope-head}
{169}{}{OK! Olhe, foi a tripulação da Merk. Eles estavam empilhando carros na noite passada. Pergunte ao redor e você pode encontrá-los.}
{170}{}{Você mente, eu mato.}
{171}{}{Não esteja mentindo. Eu voltarei se você estiver.}
{172}{}{Certo. Você me aterrou.}
{173}{}{$ 50 dólares dizem que você se lembra disso.}
{174}{}{Morda-me, homem estúpido.}
{175}{}{Morde-me. Estou fora daqui.}
{176}{}{Precisa de um carro assistido? Sem problemas. Eu posso fazer isso.}

{177}{}{Sim, eu vejo carros, sim, CARROS ... CARROS ... sim, carros ...!}
{178}{}{LA LA LA LA CARS, ei, dê um carro e eu vou vê-lo ...}
{179}{}{RELÓGIO relogio RELÓGIO relogio RELÓGIO WHKATCH watch}
{180}{}{Escreveu uma música sobre isso, wana aqui, aqui vai}
{181}{}{Carros CARROS CARROS Carros KARS KKKARS Carros CATS}
{182}{}{Kats ?! Sim, eu também posso assistir gatos. Alguém tem um CAT !!}
{183}{}{EU GOSTO DE GATOS OS SONS DA PALAVRA COMO CARRO E É O QUE EU VER?}
{184}{}{Você gosta de carros que eu olho como um falcão com olhos pequenos e claros.}
{185}{}{Nunca saia do meu site Eu fui observado em algumas pessoas falando, mas eu apenas vejo}
{186}{}{Sim, estou bem. YEAH, IM FINE, sim.}

{187}{}{Claro, cara, pegue tudo.}
