{100}{}{Big guy - arma - de pé ao redor. Guarda.}
{101}{}{Ainda é um guarda.}
{102}{}{Ele tem uma tatuagem escravista na testa, o que não o faz parecer mais brilhante.}
{103}{}{Fale com o Sr. Vortis, não comigo.}
{104}{}{Uhh ...}
{105}{}{Você recebeu perguntas? Fale com Vortis.}
{106}{}{Você nos dá problemas, é por isso que estou aqui. Compreendo?}
{107}{}{Bem, nos conseguimos um intruso.}
{108}{}{Toque o alarme. Intruder nas instalações!}
{109}{}{Sr. Vortis - incursores!}
{110}{}{Oh, você cometeu um grande erro.}
