{100}{}{Você vê um miserável miserável de ser humano.}
{101}{}{Você ainda vê um miserável miserável de um ser humano.}
{102}{}{Você vê um miserável realmente, miserável de um ser humano. Por que você está olhando?}
{103}{}{Ajude-me! Por favor, não me vire as costas.}
{104}{}{Meu mestre diz que não devo falar com ninguém.}
{105}{}{Deixe-me dizer-lhe algo - meu mestre é um verdadeiro idiota.}
{106}{}{Realmente, não me importo de ser escravo. É uma boa vida - eu recebo refeições e minha amante é muito boa para mim.}
{107}{}{Vá embora! Me deixe em paz!}
{108}{}{Você! Você deve nos ajudar! Derrube os opressores!}
{109}{}{Não fale comigo! Não quero uma outra paliza.}
{110}{}{A escravidão é apenas uma construção mental. Afinal, você é realmente grátis?}
{111}{}{Não mais! Por favor, não a Casa da Dor!}
{112}{}{Fique longe de mim!}
{113}{}{Monstro! Você e seu tipo fizeram isso comigo!}
{114}{}{O julgamento do Todo-Poder cairá sobre você!}
{115}{}{Eu obedece a todas as suas palavras.}
{116}{}{E os mansos herdarão a terra.}
{117}{}{Serei bom. Sou um bom escravo.}
{118}{}{Liberdade! Doce liberdade abençoada!}
{119}{}{Olhe o que você fez - você arruinou minha vida!}
{120}{}{Não pode parar. Tenho que correr. Não posso deixá-los me pegar.}
{121}{}{Merda! Eu condenado - eles vão me caçar e me matar.}
{122}{}{Onde eu vou agora? O que eu faço?}
{123}{}{Muito obrigado. Agora eu tenho um pouco de sangue escravo para derramar.}
{124}{}{Eu não acredito nisso - estou livre!}
