{100}{}{Você vê um homem cansado com uma metralhadora embaixo do braço.}
{101}{}{É o escravo supervisor.}
{102}{}{Bem, de sua tatuagem você sabe que ele é um escravo. Parece que ele está no comando dos guardas por aqui.}
{103}{}{O que diabos você é? Algum tipo de ladrão?}
{104}{}{NCR se intrometendo! Eu recebi uma cura para você.}
{105}{}{Vortis, temos um intruso!}
{106}{}{Guardas! Alerta!}
{107}{}{O que você quer?}
{108}{}{Kurg?}
{109}{}{O que é este lugar?}
{110}{}{Os Rangers me enviaram.}
{111}{}{Estou à procura do proprietário.}
{112}{}{Irmão escravista, tenho algumas perguntas.}
{113}{}{Desculpe, cara errado.}
{114}{}{Continue, saia daqui. Eu já tenho suficientes guardas idiotas!}
{115}{}{O que você é chump, cego? Esta é uma caneta escrava. Você quer saber mais, fale com Vortis.}
{116}{}{Isso é assim? Bem, eu estou enviando você de volta para uma bolsa de corpo.}
{117}{}{Esse seria Vortis, o velho.}
{118}{}{Obrigado. Diga, você parece um cara brilhante. Aposto que você pode me ajudar com algumas perguntas}
{119}{}{O velho, eh? OK.}
{120}{}{Bem, agora, você disse assim, na verdade não posso dizer não. O que está em sua mente?}
{121}{}{Obrigado, estranho.}
{122}{}{Eu sei que mais do que Old Vortis me dá crédito, você sabe.}
{123}{}{Bem, eu fiz muito mais do que a maioria das pessoas suspeita. Como esse trabalho, no entanto. É legal e confortável.}
{124}{}{Tanto faz.}
{125}{}{Qual é o acordo com esses Rangers dos quais eu ouvi falar?}
{126}{}{Estou procurando o Vault 13. Já ouviu falar sobre isso?}
{127}{}{Já ouviu falar de um GECK?}
{128}{}{Saiba alguma coisa sobre uma roupa chamada Enclave?}
{129}{}{Estou procurando trabalho. Conheça alguém que esteja contratando?}
{130}{}{Esqueça. Eu não quero levar seu tempo.}
{131}{}{Aqueles bastardos mataram meu irmão e então disseram que era para o bem das pessoas! Quero que eles estejam mortos. Se você pode ajudar, fale com Vortis.}
{132}{}{Parece uma boa idéia para mim.}
{133}{}{Vortis, hein? Você é uma fonte de sabedoria. O que mais você conhece?}
{134}{}{Certo. Pense que vou fazer isso agora.}
{135}{}{Todo mundo ouviu falar do Vault 13. Quando eu era criança, eu e meus amigos costumávamos prosseguir por isso. Suposto estar a leste daqui, então procuramos tudo, mas nunca o encontramos.}
{136}{}{Tenho certeza de que você tentou muito. Gostaria de fazer mais algumas perguntas, já que você sabe muito.}
{137}{}{Bem, eu tenho que ir.}
{138}{}{GECK, hein? Quando eu estava estudando tecnologia do Vault, eu li sobre aqueles. Supostamente, cada cofre tinha um e era suposto ser a primeira coisa usada uma vez que um cofre aberto. Eles dizem que é assim que a Shady Sands começou - de um GECK. Isso ajuda em tudo?}
{139}{}{Você estudou tecnologia de vault? Impressionante. Diga, eu tenho mais algumas perguntas para você.}
{140}{}{Bem, eu tenho que ir.}
{141}{}{O Enclave ... Você sabe, há um doc na cidade, passa pelo nome de Henry. Uma noite, quando ele estava bêbado, ele começou a falar sobre alguns caras que ele chamou de Enclave.}
{142}{}{Foi exatamente o que eu precisava saber. Você é um homem bem informado.}
{143}{}{É só isso que eu preciso incomodar. Obrigado.}
{144}{}{Eu, eu sempre estou atento - o problema é que ninguém nunca quer contratar um escravo mais. Vortis, meu chefe, tem algo de silêncio. E na cidade, os fazendeiros da Stockmen's Association estão sempre contratando mais Dorothy sempre pode usar uma mão no powerplant se você tiver habilidades. A palavra é mesmo o presidente Tandi está à procura de um especialista.}
{145}{}{Cara, você sabe muito. Eu poderia passar o dia todo fazendo perguntas.}
{146}{}{Bem, irei direto sobre essas ligações.}
{147}{}{Você cortou ... você sabe ... para mim, ok?}
{148}{}{Sem problemas. Há algumas outras coisas que eu gostaria de saber, no entanto.}
{149}{}{Eu vou cuidar deles, não se preocupe.}
