{100}{}{Você vê um velho velho com uma caneta presa atrás de sua orelha e espetáculos equilibrados no final do nariz.}
{101}{}{É Vortis, o dono desta caneta escrava.}
{102}{}{Ele tem cerca de três dentes. Os dedos e a camisa são manchados com tinta azul. Há uma tatuagem de escravidão realmente desbotada em sua testa.}
{103}{}{Então o que você quer?}
{104}{}{Irmão, seja bem vindo ao salão de Vortis. Como posso ajudá-lo?}
{105}{}{Você está começando a me irritar.}
{106}{}{Este lugar é meu lugar e eu, Vortis, administrai negócios honestos e legítimos, não importa o que qualquer um da NCR lhe diga. Como a NCR não permite escravos dentro dos portões, eu me importo com pessoas que têm negócios dentro.}
{107}{}{O que você é denso? Esta é uma caneta escrava. Eu tenho licenças para isso.}
{108}{}{}
{109}{}{Só tenho algumas perguntas.}
{110}{}{Estou procurando trabalho.}
{111}{}{Uh?}
{112}{}{Não há dependências? Eu vou embora.}
{113}{}{O que faz esse lugar?}
{114}{}{Nada. Lugar errado.}
{115}{}{Oh, olha - o goody dois-sapatos, garoto pirulito. Meninos, escoltam este paradigma hipócrita de santa virtude fora da minha vista!}
{116}{}{Foda-se isso.}
{117}{}{Bem?}
{118}{}{Estou procurando pelo Vault 13.}
{119}{}{Você tem um GECK?}
{120}{}{O que você pode me falar sobre essa cidade?}
{121}{}{Você é escravista do escravo Por que eu não deveria te matar?}
{122}{}{Ouvi dizer que existem esses caras - New California Rangers. Eles estiveram te dando algum problema?}
{123}{}{Mente se eu dê uma olhada ao redor?}
{124}{}{Trabalhos? Bem ... pode haver alguma coisa. Você já ouviu falar sobre os New Rangers da Califórnia?}
{125}{}{Sim.}
{126}{}{Não.}
{127}{}{Foda-se. Meninos, escoltam esse irritante crud fora da minha vista.}
{128}{}{Morde-me!}
{129}{}{Vault 13! Saia daqui. Maldito lugar é um mito. Vault 13, minha bunda.}
{130}{}{Outra pergunta...}
{131}{}{Bem, obrigado por nada.}
{132}{}{Um que? Bem, seja lá o que for, eu não entendi.}
{133}{}{Outra pergunta...}
{134}{}{Bem, obrigado por nada.}
{135}{}{Nãova República da Califórnia - nada além de tipos de temperança e comerciantes. Tenho um bug sobre escravos e escravidão, mas o que diabos, isso faz o meu negócio.}
{136}{}{Outra pergunta...}
{137}{}{Obrigado, tenho que ir.}
{138}{}{Alguém conduziu você errado. Não tenho problemas com ninguém - especialmente não com Rangers. Sou legal, então não há nada em mim.}
{139}{}{Outra pergunta...}
{140}{}{Qualquer coisa que você diga. Eu irei.}
{141}{}{Sim, talvez eu tenha alguns sentimentos sobre os Rangers. Você está procurando trabalho?}
{142}{}{Sim.}
{143}{}{Não.}
{144}{}{Não, você pode não dar uma olhada, merda para o cérebro! Este não é um museu!}
{145}{}{Outra pergunta...}
{146}{}{Você é tão sensível para mim. Estou indo embora.}
{147}{}{Bem, então, você deve saber que algumas pessoas as vêem como um problema potencial. Seria extremamente útil se tivéssemos um mapa de suas casas seguras através do norte - New Reno, Klamath, onde quer que. Eu estaria disposto a pagar, oh dizer, $ 500 por algo assim. Você acha que conseguiu isso por mim?}
{148}{}{Certo.}
{149}{}{Acho que não.}
{150}{}{Deixe-me dizer-lhe, então. Estes Rangers conseguiram em suas cabeças destruir a escravidão e os escravos - pela força. Eles criaram muitos problemas para pessoas de trabalho duro.}
{151}{}{Eles trabalham em segredo, especialmente no norte.}
{152}{}{Jeez, eu tenho que explicar isso para você? Eles atacam os escravos, expulsam o estoque e contrabande-os para o sul para as terras da NCR, onde a escravidão é ilegal. Então você está interessado?}
{153}{}{Não há "e"! Você quer o trabalho ou não?}
{154}{}{E?}
{155}{}{Então, o que você quer que eu faça?}
{156}{}{Bem. Quando você me pegar um mapa, eu estarei aqui.}
{157}{}{Onde eu vou encontrar um mapa?}
{158}{}{Ok, eu tenho algumas outras perguntas, no entanto.}
{159}{}{Estou com isso. Vejo você então.}
{160}{}{Como diabos eu deveria saber? Se eu soubesse, eu teria, não? Olha, é suposto ser uma cela na cidade. Encontre-os e veja o que você pode fazer.}
{161}{}{Apenas mais algumas perguntas.}
{162}{}{Bem. Eu voltarei.}
{163}{}{Você está de volta. Você conseguiu esse mapa?}
{164}{}{Sim.}
{165}{}{Não}
{166}{}{Eu ainda estou esperando por você para terminar o primeiro trabalho!}
{167}{}{Ah, eu esqueci}
{168}{}{Nãot since you did your job. Thanks.}
{169}{}{Apenas uma pergunta ou duas.}
{170}{}{Não problem. Bye.}
{171}{}{Good work. Nãow you best make yourself scarce, in case those Rangers ever wise up.}
{172}{}{Prazer em fazer negócios.}
{173}{}{Bem, não passe por aqui, seu idiota! Alguém vai suspeitar.}
{174}{}{Tudo bem, eu recebo a dica.}
{175}{}{Por que diabos? Guardas! Nós temos um intruso!}
{176}{}{Entre lá e eu explodirei sua cabeça. Compreendo?}
