{100}{}{Você vê um homem vestido com roupas extravagantes.}
{101}{}{É o conselheiro Westin.}
{102}{}{Anéis de prata e turquesa, fivela de cinto de prata, pistola ao seu lado, esse cara é claramente usado para ter dinheiro e ter seu próprio caminho.}
{103}{}{Eu sou Roger Westin e você não pode entrar aqui. O que você quer?}
{104}{}{Você novamente? O que você quer?}
{105}{}{O que você quer?}
{106}{}{Duh ...}
{107}{}{Eu vejo o Vault 13? Você ajuda?}
{108}{}{Estou procurando o Vault 13. Você pode me ajudar?}
{109}{}{Eu terminei seu trabalho sujo.}
{110}{}{São coisas ruins. Eu estou com medo. Moo-moos seguro.}
{111}{}{Sobre o seu problema brahmin - parece que tudo o que você precisa fazer é postar um homem lá fora. Ele nem precisa fazer nada, apenas estar lá. Eu sei que isso parece estranho, mas vai funcionar. Você mencionou algum salário?}
{112}{}{Estou aqui sobre um trabalho.}
{113}{}{O primeiro cidadão Lynette envia seus cumprimentos. Ela tem algo para você.}
{114}{}{Bispo me enviou.}
{115}{}{Oops.}
{116}{}{Isso tudo? Fale com o meu chefe, Felix.}
{117}{}{Você não entende. Estou aqui para fazer um trabalho.}
{118}{}{O xerife sugeriu que eu venha falar com você pessoalmente.}
{119}{}{Bem. Seja assim.}
{120}{}{Eu devia ter adivinhado. O que ele prometeu - dinheiro, chems ou sexo? Não importa. Você nunca verá nada disso.}
{121}{}{O que você quer dizer?}
{122}{}{Cale-se.}
{123}{}{Oh, você é simples? Que coisa triste. Deve ser uma cruz difícil de suportar.

Ouça - você vai, fale com Fee-lix. Ele lhe dá trabalho. Savvy?}
{124}{}{Uh-huh.}
{125}{}{O que você acha? Você sabe muito. E se você voltar para a NCR e vendê-lo - ou ameaçar? Você já está bem morto.

Por outro lado, eu tenho uma oferta melhor.}
{126}{}{Tal como?}
{127}{}{Eu não acredito em você.}
{128}{}{Retire o bispo em vez disso. Eu pagarei em dinheiro, seja lá o que ele pagasse mais 50%. Quanto foi?}
{129}{}{(Precisa de informações de Chris)}
{130}{}{(Avellone, isto é)}
{131}{}{Bem.}
{132}{}{Combinado.}
{133}{}{Muito ruim para você, velho.}
{134}{}{Estou ansioso para ouvir de você. Agora, saia do jeito que você veio.}
{135}{}{Excelente. Eu sabia que você era a pessoa certa. Bem, prometi pagar e não negociei minhas ofertas. Aqui está o seu dinheiro.}
{136}{}{Mais alguma coisa que eu possa fazer por você?}
{137}{}{Obrigado. Talvez você possa me ajudar. Estou tentando encontrar o Vault 13.}
{138}{}{Adeus.}
{139}{}{Dumont recomendou você? Bem, isso é bom o suficiente para mim. Algo ou alguém tem atacado meu brahmin à noite. Preciso descobrir o que há de novo. Que tal ir lá e olhar para mim? Eu pagarei por seu problema.}
{140}{}{Parece trabalho fácil. Eu vou fazer isso.}
{141}{}{Eu decidi contra isso.}
{142}{}{Algo ou alguém tem atacado meu brahmin à noite. Preciso descobrir o que há de novo. Que tal ir lá e olhar para mim? Eu pagarei por seu problema.}
{143}{}{Parece uma boa ideia. Eu vou fazer isso.}
{144}{}{Não, obrigado. Sentado em um campo, esperando algum mantoid para mostrar sons chatos.}
{145}{}{Excelente. Felix irá guiá-lo lá fora. Agora, se você me desculpar.}
{146}{}{Bem, talvez eu possa. Ouvi muitas histórias sobre Tandi e o Vaultdweller. Parece que ele salvou sua vida anos antes da NCR ter sido fundada. De qualquer forma, a lenda diz que ele passou muito tempo explorando um cofre no leste de aqui. Se não for um vault 13, talvez você encontre uma pista que o guie.}
{147}{}{Ooooh. Boa.}
{148}{}{Obrigado!}
{149}{}{Bem, talvez eu possa. No entanto, eu preciso primeiro de você. Alguma coisa, ou alguém, tem atacado meu brahmin à noite. Preciso descobrir o que há de novo. Que tal ir lá e olhar para mim? Eu pagarei por isso e eu vou te dizer o que sei.}
{150}{}{Parece uma boa ideia. Eu vou fazer isso.}
{151}{}{Não, obrigado. Sentado em um campo, esperando algum mantoid para mostrar sons chatos.}
{152}{}{Bem, então, você vai. Prazer em conhecê-lo, estranho.}
{153}{}{Não tenho certeza se acredito em você, mas aqui está o seu salário. Inferno, se você estiver mentindo, meus meninos vão te encontrar. Eu também disse que eu lhe daria algumas informações, então aqui está. Ouvi muitas histórias sobre Tandi e o Vaultdweller. Parece que ele salvou sua vida anos antes da NCR ter sido fundada. De qualquer forma, a lenda diz que ele passou muito tempo explorando um cofre no leste de aqui. Se não for o Vault 13, talvez você encontre uma pista que o guie.}
{154}{}{Me tanque você!}
{155}{}{Obrigado.}
{156}{}{O primeiro cidadão? Excelente, isso é o que eu esperava. Você é um cidadão do vaqueiro?}
{157}{}{Sim.}
{158}{}{Não.}
{159}{}{E você é um bom cidadão, tenho certeza. Eu quero que você tire este holodisco de volta para o primeiro cidadão. É importante. Tem a informação que ela precisa para expor este plano NCR-New Reno.}
{160}{}{Eu tenho outras questões.}
{161}{}{Sim senhor.}
{162}{}{Bem, isso é tudo.}
{163}{}{Eu tenho outras questões.}
{164}{}{Tanto faz.}
{165}{}{Um trabalho. Você quer dizer--}
{166}{}{Bispo me enviou. Got a little message for you.}
{167}{}{Adeus e durma bem, velho.}
{168}{}{dólares é. Você faz o trabalho, eu pago. Você diz que não, você não sai daqui vivo. Bem?}

{169}{}{Oh, sim. Bem, eu estava tendo algum problema com varmits, mas eles pararam de vir. Me desculpe por isso. Tente Felix e veja se ele tem algo para você fazer.}
{170}{}{Ok, obrigado.}

{171}{}{Ehhh .... eu tenho uma condição cardíaca ruim ... não posso tomar ...}
{172}{}{Deve ..... ttteeeelll Feeellliixx.}
{173}{}{Uau, acho que ele teve um problema cardíaco.}

{174}{}{AHHAHH !!! AHAHAHHAH !!! AHHAHAH !!! QUEIMA!!!}
