{100}{}{Você vê um guarda.}
{101}{}{Você vê Grant, o guarda}
{102}{}{Você vê um guarda. His armor and weapons are in excellent condition.}
{103}{}{Esta é uma propriedade privada, por favor, avance.}
{104}{}{Quem mora aqui?}
{105}{}{Ok, eu vou.}
{106}{}{Com licença, mas quem mora aqui?}
{107}{}{Tudo bem, eu irei.}
{108}{}{Você está pronto para partir?}
{109}{}{Eu quero ir.}
{110}{}{Não, eu fico.}
{111}{}{Sim, eu preciso ir agora.}
{112}{}{Não, vou ficar um pouco mais por aí.}
{113}{}{Este é Westin Ranch, lar do vereador Westin.}
{114}{}{Eu preciso ver.}
{115}{}{Está bem. Tchau.}
{116}{}{Preciso ver o vereador, por favor.}
{117}{}{Entendo. Bem, vou estar no caminho.}
{118}{}{Que negócios você tem com o Sr. Westin?}
{119}{}{Eu preciso de emprego.}
{120}{}{Só quero conversar.}
{121}{}{Uh ...}
{122}{}{Deixa pra lá.}
{123}{}{Estou procurando trabalho e ouço que ele está contratando.}
{124}{}{Gostaria de conversar com o Sr. Westin.}
{125}{}{Não importa, volto mais tarde.}
{126}{}{Hmm ... Parece lembrar algo sobre o trabalho estar disponível. Tudo bem, entre. Não cause nenhum problema, eu vou estar observando você.}
{127}{}{Obrigada.}
{128}{}{Obrigado.}
{129}{}{O Sr. Westin não apenas "conversa" com quem entra na rua. Se você não tem negócios específicos com ele, então sugiro que você deixe até o momento. Agora, vá embora.}
{130}{}{Feito.}
{131}{}{(suspiro) Eu ouvi dizer que o Sr. Westin tem um ponto fraco para pessoas como você. Entre.}
{132}{}{Eu obrigado.}
{133}{}{Sim sim. Estou no meio de alguma coisa.}
{134}{}{Ei, afaste-se daí!}
{135}{}{Você deve perguntar antes de jogar com coisas que não são suas.}

{136}{}{Olá. Você precisou ver o Sr. Westin novamente?}
{137}{}{Sim.}
{138}{}{Não.}

{139}{}{Eu tenho coisas da Vault City para o Sr. Westin.}
{140}{}{Eu tenho algo da Cidade do Vault para o Sr. Westin.}
{141}{}{Tudo bem, entre. Não cause nenhum problema, eu vou estar observando você.}
{142}{}{Você não é permitido na fazenda sem o ônibus oficial.}
