{100}{}{Você vê uma pessoa com roupas de trabalho empoeiradas.}
{101}{}{Uma das mãos do rancho de Westin.}
{102}{}{Poderia ser apenas uma mão da fazenda, mas também poderia ser um assassino. Certamente parece pronto para problemas.}
{103}{}{Você deveria vagar por aqui?}
{104}{}{Fale com Felix se você estiver procurando emprego, estranho.}
{105}{}{Estou tão cansada de brahmin.}
{106}{}{Eu ouço os Bispos obtê-lo para o nosso chefe.}
{107}{}{Você quer conversar com alguém, fale com o capataz, Felix.}
{108}{}{Você não está com os Bispos, você está?}
{109}{}{Sabemos que foi assassinato. Pegamos a cobra, sua morte não será rápida.}
{110}{}{Felix jura que os Bispos estavam atrás disso. Diz que há dinheiro para alguém.}
{111}{}{Bem, acho que é hora de se mudar. As coisas foram para o inferno aqui.}
