{100}{}{Você vê uma mulher idosa, magra e resistida.}
{101}{}{Você vê Tandi, presidente da NCR.}
{102}{}{Você vê uma mulher dura e auto-confiante. É claro que ela está acostumada com o respeito dos outros.}

{103}{tand1}{Eu sou Tandi, presidente da NCR. Meus meninos me dizem que você está procurando trabalho. O que você é útil?}
{104}{}{Eu, boa arma. Um dos melhores.}
{105}{}{Eu bom falar pessoas.}
{106}{}{Eu bom lutador. Arrebentar.}
{107}{}{Eu sneaky. Chegue onde quer. Não veja nem ouça.}
{108}{}{Eu tenho muitos talentos.}
{109}{}{Uh, apenas coisas.}
{110}{}{Estou bem com uma arma. Um dos melhores.}
{111}{}{Foi-me dito, Senhora Presidente, que eu tenho um jeito com as palavras.}
{112}{}{Eu sou bom em combate desarmado, de perto e pessoal.}
{113}{}{Eu sou bom em chegar onde eu preciso ir sem ser visto ou ouvido.}
{114}{}{Eu tenho muitos talentos, e eles estão todos à sua disposição.}
{115}{}{Apenas acho que acho.}

{116}{tand2}{Hmmm. Você não é exatamente o que estou procurando. Certo, você pode lidar com você mesmo?}
{117}{}{Eu não sei. Que trabalho?}
{118}{}{Eu acredito em si mesmo. Eu posso fazer!}
{119}{}{Isso depende do trabalho que você está oferecendo.}
{120}{}{Sim, estou confiante nas minhas habilidades e eu mesmo.}

{121}{tand3}{Você parece apenas o que é necessário.}
{122}{}{Boa. Como eu ajudo?}
{123}{}{Excelente, como posso ajudá-lo?}

{124}{tand4}{Precisamos de algumas partes do computador da nossa base antiga - Vault 15. Problema, há os invasores lá que não vão deixar ninguém. Alguém tem que convencê-los a nos deixar entrar - ou simplesmente trazer de volta as peças. Para o trabalho?}
{125}{}{Eu não gosto. Eu vou.}
{126}{}{Eu faço por você.}
{127}{}{Eu estava lá. Squatters quer negociar. Você ensina, você ajuda, eles lhe dão vault.}
{128}{}{Eu estava lá. Eu consegui peças.}
{129}{}{Eu estava lá. Squatters quer negociar. Você ensina, você ajuda, eles lhe dão vault. Here parts also.}
{130}{}{Desculpe, isso não soa como minha linha de trabalho.}
{131}{}{Eu ficaria feliz em ajudá-lo.}
{132}{}{Estou interessado, mas o que o trabalho paga?}
{133}{}{Já manipulei a maior parte disso. Os invasores querem um acordo. Você os ajuda a tornar-se auto-suficientes e eles vão te dar acesso ao cofre.}
{134}{}{Estive lá e tenho as peças que você procura.}
{135}{}{Eu já lidei isso. Os invasores querem um acordo. Você os ajuda a tornar-se auto-suficiente e eles vão te dar o cofre. Além disso, aqui estão as peças.}

{136}{tand5}{Inferno e trovão ... Sua escolha - mas se você mudar de idéia ...}
{137}{}{Feito.}

{138}{tand6a}{Justo. Faça isso bem e há uma recompensa.}
{139}{tand6b}{Senhor, eu sei que estou cometendo um erro, mas ... dê uma chance - se você entendeu alguma coisa que eu disse.}
{140}{}{Está bem. Eu vou.}
{141}{}{Eu tenho perguntas.}
{142}{}{Tudo certo. Eu estou fora.}
{143}{}{Gostaria de fazer algumas perguntas.}

{144}{tand7a}{Bem, consegui um pouco de sobra.}
{145}{tand7b}{O que você quer saber?}
{146}{}{O que você diz sobre o Vault 15?}
{147}{}{Por que não fazer negócios com invasores?}
{148}{}{Você sabe onde o vault 13?}
{149}{}{Eu procuro geck. Você tem?}
{150}{}{O que você conta sobre New Reno?}
{151}{}{O que você fala sobre Frank Westin?}
{152}{}{O que você conta sobre Carlson?}
{153}{}{Elder conta a história. Fale sobre Vaultdweller, Tandi. Você que Tandi?}
{154}{}{Este Shadeesans Elder fala sobre?}
{155}{}{Isso tudo. Eu vou agora.}
{156}{}{O que você pode me falar sobre o vault 15?}
{157}{}{Por que você não fez um acordo com os invasores?}
{158}{}{Você sabe onde é o vault 13?}
{159}{}{Estou procurando um geck. Você teria um?}
{160}{}{O que você pode me falar sobre o New Reno?}
{161}{}{O que você pode me falar sobre Frank Westin?}
{162}{}{O que você pode me falar sobre Carlson?}
{163}{}{O Ancião conta uma história sobre o Vaultdweller e alguém chamado Tandi. Você é Tandi?}
{164}{}{É o que o Shadeesands Elder fala?}
{165}{}{É tudo por agora. Eu irei.}

{166}{tand8}{Está a leste daqui, um abrigo subterrâneo da guerra. A maioria das famílias da NCR veio disso, então é legítimo nossa.}
{167}{}{Conte mais.}
{168}{}{Continue.}

{169}{tand9}{Alguns anos atrás, alguns invasores entraram e construíram uma favela na superfície. Eles chamam de 'The Squat'. Não são mais que cachorros na manjedoura. Eles não podem entrar no cofre, mas eles nos impedem.}
{170}{}{Eu tenho mais perguntas.}
{171}{}{Entendo. Preciso lhe perguntar sobre algumas outras coisas.}

{172}{tand10}{Eu tentei. Enviei algumas pessoas para lá, mas, depois dos primeiros, eles pararam de voltar. Não posso provar que os invasores também são responsáveis. Meus meninos conseguiram capturar um deles, mas ele não conversará. Os peguei no centro da cidade.}
{173}{}{Precisa saber mais.}
{174}{}{Mais algumas perguntas, por favor.}

{175}{tand11}{Conheça isso. Não consigo passar o dia com você.}
{176}{}{Ok, eu me apresso}
{177}{}{Vou tentar ser rápido.}

{178}{tand12}{Com esse fato que você estava vestindo, achei que você já sabia.}
{179}{}{O traje estava na aldeia há muito tempo. Pertence a Vaultdweller, fundador da tribo.}
{180}{}{Este terno esteve em nossa aldeia desde o início. Pertenceu ao Vaultdweller, nosso fundador.}

{181}{tand13}{Você é sério, não é? Se estamos falando sobre a mesma pessoa, ele salvou minha vida. (Snorts) Então desapareceu. Quando eu começar a pensar que era apenas um sonho, eu vou olhar para a estátua na frente.}
{182}{}{Estátua?}

{183}{tand14a}{Está certo. Por assustar os incursores. Eles ficaram longe de Shady Sands depois que conseguimos tempo para nos arrumarmos. Nós o fizemos um herói ... mesmo que não acreditássemos uma palavra sobre ele vindo do Vault 13.}
{184}{}{Me lembro. Pergunte mais?}
{185}{}{Eu vou manter isso em mente. Posso pedir-lhe mais alguma coisa?}

{186}{tand15}{Vault 13? Porque perguntas?}
{187}{}{Eu curioso.}
{188}{}{Me Escolhido. Eu descendente Vaultdweller.}
{189}{}{Não importa. Eu faz perguntas.}
{190}{}{Ouvi histórias e tenho curiosidade.}
{191}{}{Eu sou o Escolhido da minha aldeia. Sou descendente do Vaultdweller.}
{192}{}{Deixa pra lá. Eu só estava curioso.}

{193}{tand16}{É apenas um maldito mito como minas de urânio perdidas. Eu conheci um estranho uma vez que alegou ser de lá. Muitas pessoas morreram tentando encontrar aquele cofre depois.}
{194}{}{Vaultdweller real. Eu descendente.}
{195}{}{Eu preciso saber mais.}
{196}{}{O Vaultdweller era real. Eu sou um dos seus descendentes.}
{197}{}{Entendo. Deixe-me perguntar-lhe sobre outra coisa.}

{198}{tand17}{Um geck? Como o lagarto? Nós os conseguimos por toda parte.}
{199}{}{Não é lagarto ... não importa. Eu pergunto.}
{200}{}{Não, não os malditos lagartos ... não importa. Preciso lhe pedir outra coisa.}

{201}{tand18}{Novo Reno? Um maldito balde de brahmin cuspiu. Cada vício existe. Devemos ser difíceis com eles se vamos unificar esta terra. O Congresso tem que entender isso.}
{202}{}{O que sabe sobre Bishop?}
{203}{}{Conte sobre o congresso?}
{204}{}{Eu pedi mais.}
{205}{}{E quanto aos Bispos?}
{206}{}{Conte-me sobre o congresso.}
{207}{}{Entendo. Você pode me contar um pouco mais?}

{208}{tand19}{Bem, vou falar com uma cobra, mas não espero que eu o abrace. Se você vê-los, você pode contar a eles também.}
{209}{}{Eu ouço NCR fazer negócios com Bishop.}
{210}{}{Está bem. Eu preciso saber mais.}
{211}{}{Há rumores de que a NCR está fazendo um acordo com os Bispos.}
{212}{}{Ok, para outras coisas.}

{213}{tand20}{Nenhum ponto, tentando manter segredos por aqui. Estamos negociando com New Reno para ser membro da NCR. Eles deveriam ter alguma atração com lugares como o Vault City.}
{214}{}{Eu vejo.}
{215}{}{Tudo certo.}

{216}{tand21}{Na maioria, temos que trabalhar com o New Reno de uma forma ou de outra. Mas pessoas como Westin e os fazendeiros culpam o novo Reno por rustling o gado dirige entre aqui e Redding.}
{217}{}{Humph.}
{218}{}{Quem Westin?}
{219}{}{Entendo.}
{220}{}{Quem é essa pessoa Westin?}

{221}{tand22}{Deputado Westin? Um dos maiores fazendeiros brahmins ao redor. Seio se espalha no lado oeste da cidade. Apenas não traga o novo Reno se você falar com ele - ele o faz acontecer. Se você está procurando um emprego estável ... mas você não é esse tipo, não é?}
{222}{}{Não, obrigado.}

{223}{tand23}{Teimoso como uma mula ... mas um bom homem. Por quê?}
{224}{}{Estou curioso sobre o trabalho.}
{225}{}{Estou curioso sobre o trabalho.}
{226}{}{Estou curioso sobre algum trabalho.}
{227}{}{Estou curioso sobre algum trabalho.}

{228}{tand24}{Parece-me que já tem o suficiente no seu prato.}
{229}{}{ESTÁ BEM. Deixa pra lá.}
{230}{}{Sim você está certo.}

{231}{tand25}{Desde que Westin morreu, Carlson está escondido em seu escritório. Provavelmente não o vejo, mas você pode conversar com seus meninos.}
{232}{}{Está bem.}

{233}{tand26}{Ouço. Muitas pessoas, incluídas, como o velho Carlson, mesmo que não concordemos com o novo Reno. Algo acontece com ele, não aceitamos gentilmente isso. Qualquer um que pensasse que sua vida seria mais fácil se ele fosse embora é muito, muito errado. Compreendo?}
{234}{}{Sim. Eu entendo.}
{235}{}{Sim, eu entendo.}

{236}{tand27}{Senhor, isso foi há muito tempo! Não me lembro de quem eu era então - apenas uma menina ingênua. Aquele que você chama o Vaultdweller - ele ainda está vivo?}
{237}{}{Ele é o antepassado agora. Viva com espíritos. Vive em mim.}
{238}{}{O Vaultdweller é meu antepassado. Ele vive em mim.}

{239}{tand28}{Sim ... há uma semelhança - você também pegou o mesmo fogo. Sempre tive medo de não ser mais que um esqueleto em algum lugar do deserto.}
{240}{}{Eu quero ouvir sua história.}
{241}{}{Gostaria de ouvir sua história.}

{242}{tand29}{Figuras. (Suspiro) Bem, eu era muito jovem quando nos conhecemos. Havia uma gangue de incursores - Os Khans - Quem me apoderou de mim. As coisas estavam muito ruins quando, de repente, esse estranho aparece e me resgata. Seu Vaultdweller.}
{243}{}{Vaultdweller tem muitas aventuras.}
{244}{}{O Vaultdweller teve muitas dessas aventuras.}

{245}{tand30}{Eu costumava invejá-los assim. Eu queria uma vida de aventura, mas fiquei aqui e assumi o cargo de prefeito quando meu pai morreu. Estabelecendo esse lugar e criando a NCR desde então. Acho que acabou por ser uma vida muito grande, afinal.}
{246}{}{Elder seja feliz, você ainda está vivo. Desculpe, mas eu preciso pedir mais.}
{247}{}{O Ancião ficará feliz em saber que você ainda está vivo. Desculpe, mas preciso saber mais.}

{248}{tand31}{Was Shady Sands; A maioria das pessoas chama isso de NCR agora. Nova República da Califórnia - nome bastante impressionante, hein?}
{249}{}{Conte sobre NCR.}
{250}{}{Eu pergunto sobre outra coisa.}
{251}{}{Conte-me sobre a NCR, por favor.}
{252}{}{Deixe-me perguntar-lhe outra coisa.}

{253}{tand32}{Senhor, eu poderia falar sobre isso para sempre e eu simplesmente não tenho tempo. Aqui está um holodisco na NCR. Nós os fazemos para espalhar a boa palavra.}
{254}{}{Uh, obrigado.}

{255}{tand33}{Então, eles finalmente ficaram razoáveis. Posso torcer o Congresso para enviar suprimentos e técnicos. Você tem certeza de que podemos entrar no cofre?}
{256}{}{Com certeza. Lowlifes lá, mas eu chute o traseiro.}
{257}{}{Sem dúvida. Havia alguns lowlifes lá, mas eu chutei sua bunda.}

{258}{tand34}{Eu sempre acreditei em salários justos por um trabalho justo. O meu assistente irá acalmar as coisas.}
{259}{}{Eu acho um problema. Você parece disco. Há espionagem na NCR.}
{260}{}{Eu preciso saber mais uma coisa. E se eu encontrasse um vault 13?}
{261}{}{Receio que você tenha outro problema. Se você olhar para este holodisco você verá que você tem um espião na NCR.}
{262}{}{Só mais uma coisa. E se eu lhe dissesse que encontrei o vault 13?}
{263}{}{Obrigado.}

{264}{tand35}{Droga, a única pessoa que sabia tudo isso era Feargus! Não estou sugerindo nada, mas talvez Gunther devesse saber sobre isso.}
{265}{}{Eu contai. Eu vou agora.}
{266}{}{Eu preciso saber mais uma coisa. E se eu encontrasse um vault 13?}
{267}{}{Só mais uma coisa. E se eu lhe dissesse que encontrei o vault 13?}
{268}{}{Eu vou falar com ele. Tchau.}

{269}{tand36}{Tudo é negócio, hein? Bem. Quinhentos, quando terminar. Eu não regateio, então pegue ou não perca meu tempo.}
{270}{}{Eu preciso, mas eu preciso fazer perguntas}
{271}{}{Não estou interessado.}
{272}{}{Vou levá-lo, mas preciso de alguma informação.}
{273}{}{Não interessado.}

{274}{tand37a}{Eu sou Tandi, presidente da NCR. Então você sujou meu filho, Hoss, em Dusty's? Talvez você seja o homem certo no momento certo. Interessado em algum trabalho?}
{275}{tand37b}{Eu sou Tandi, presidente da NCR. Então você é a garota que ajudou o meu filho Hoss? Eu deveria ter tido uma tal filha! Eu tenho um emprego que você pode querer. Interessado?}
{276}{}{Talvez. Que trabalho?}
{277}{}{Eu posso ser, qual é o trabalho?}

{278}{tand38}{Eu sou Tandi, presidente da Nova República da Califórnia. Bem-vindo ao Shady Sands. Eu ouço algumas coisas bastante impressionantes sobre você. Nenhum ponto em dançar. Tenho alguns negócios que eu quero discutir.}
{279}{}{Uh, ok.}
{280}{}{Tudo bem, o que posso fazer por você?}

{281}{tand39}{Você voltou. Então, você está interessado em um trabalho ou não?}
{282}{}{Não.}
{283}{}{Está bem.}

{284}{tand40}{De volta, você é estranho? Então o trabalho está feito? Temos acesso ao cofre?}
{285}{}{Estou trabalhando nisso. Tchau.}
{286}{}{Eu estava lá. Squatters quer negociar. Você ensina, você ajuda, eles lhe dão vault.}
{287}{}{Eu estava lá. Eu consegui peças.}
{288}{}{Eu estava lá. Squatters quer negociar. Você ensina, você ajuda, eles lhe dão vault. Here parts also.}
{289}{}{Eu ainda estou trabalhando nisso. Eu vou te ver.}
{290}{}{Já manipulei a maior parte disso. Os invasores querem um acordo. Você os ajuda a tornar-se auto-suficientes e eles vão te dar acesso ao cofre.}
{291}{}{Estive lá e tenho as peças que você procura.}
{292}{}{Eu já lidei isso. Os invasores querem um acordo. Você os ajuda a tornar-se auto-suficiente e eles vão te dar o cofre. Além disso, aqui estão as peças.}

{293}{tand41}{Inferno e trovão! Então pare de desperdiçar meu tempo!}
{294}{}{Desculpa.}

{295}{tand42}{Vault 13 - você encontrou? Isso resolve todos os nossos problemas! Cadê?}
{296}{}{Uh, antes de mim dizer, há um problema com o vault.}
{297}{}{Me desenhar o mapa. Aqui.}
{298}{}{Antes de lhe dizer, há um pequeno problema com o cofre.}
{299}{}{Eu elaborei um mapa. É seu.}
{300}{}{Eu não sou um só para entregar uma mina de ouro de graça. Eu quero 20 milhas ou você pode esquecer.}

{301}{tand43}{O que?}
{302}{}{Está cheio de D'garra. Inteligentes. Eles falam.}
{303}{}{Está cheio de mortandras inteligentes. Eles podem até falar.}

{304}{tand44a}{Certo. (Shakes head) Senhor, você é mais idiota do que Hoss nunca foi! (Suspiro) Há a porta.}
{305}{tand44b}{Certo. (Agita a cabeça) Bem, vamos parar de perder o tempo do outro. (Suspiro) Há a porta.}
{306}{}{Eu vou agora.}
{307}{}{Certo. Eu vou sair.}

{308}{tand45}{Você ganhou um bônus. O meu assistente irá acalmar as coisas.}
{309}{}{}
{310}{}{Obrigado.}

{311}{tand46}{Um verdadeiro comerciante de cavalos que você é. Tudo bem, veja Gunther. Ele tratará os arranjos.}
{312}{}{Obrigado.}

{313}{tand47}{Meninos, pegue esta boca de brahmin do meu escritório! Tempo para você se dirigir para fora estranho.}
{314}{}{Feito}

{315}{tand14b}{Meu pai e Seth procuraram por anos tentando encontrar o Vault 13. Eles morreram olhando - sempre dizia que era o oeste daqui. Se alguém encontrasse o Vault 13, isso nos faria até melhor do que 15.}

# Float
{316}{}{Você terá que falar com o meu assessor, Gunther, sobre isso.}
