{100}{}{Você vê uma estante usada para armazenar inventário.}
{101}{}{Uma estante velha fica aqui. Parece robusto o suficiente, você provavelmente poderia armazenar coisas em suas prateleiras.}
{195}{}{Esta estante de livros não parece estar presa.}
{200}{}{ não acha que esta estante está presa.}
{206}{}{Ei, não planifique isso aqui!}
{207}{}{Deixe as malditas estantes sozinhas antes de impor sanções extremas ao seu traseiro.}
{208}{}{Não faça isso.}
