#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Você vê uma porta de madeira.}
{101}{}{Você vê uma porta de metal.}

# description_proc

# Perception Check Critical Success
{102}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Lockpicks e uma armadilha altamente explosiva no quadro da porta, que
 Você pode abrir-se.}
{103}{}{Você vê uma porta resistente com um bloqueio e uma
 Armadilha explosiva no batente da porta, que você poderá
 Abrir-se.}
{104}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente e
 Uma armadilha altamente explosiva no quadro da porta, que você pode
 Abrir-se.}
{105}{}{Você vê uma porta resistente com uma trava velha e enferrujada e uma
 Armadilha explosiva no batente da porta, que você poderá puxar
 aberto.}

{106}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Lockpicks e uma armadilha no quadro da porta, que você poderá
 Abrir-se.}
{107}{}{Você vê uma porta resistente com um bloqueio e uma armadilha em
 O quadro da porta, que você poderá abrir.}
{108}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente e
 Uma armadilha no quadro da porta, que você poderá abrir.}
{109}{}{Você vê uma porta resistente com uma trava velha e enferrujada e uma armadilha
 No quadro da porta, que você poderá abrir.}

{110}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Trancas e um fio cortado no quadro da porta, que você pode ser
 Capaz de abrir.}
{111}{}{Você vê uma porta resistente com um bloqueio e um fio cortado
 No quadro da porta, que você poderá abrir.}
{112}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente e
 Um fio cortado no quadro da porta, que você pode conseguir
 aberto.}
{113}{}{Você vê uma porta resistente com um bloqueio velho e enferrujado e um corte
 Fio no quadro da porta, que você poderá abrir.}

{114}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Lockpicks, que você poderá abrir.}
{115}{}{Você vê uma porta resistente com um bloqueio nele, o que você pode ser
 Capaz de abrir.}
{116}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente,
 Que você poderá abrir.}
{117}{}{Você vê uma porta resistente com um bloqueio velho e enferrujado, que
 Você pode abrir-se.}

# Perception Check Success

{118}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Lockpicks e uma armadilha altamente explosiva no quadro da porta.}
{119}{}{Você vê uma porta resistente com um bloqueio e uma
 Armadilha explosiva no quadro da porta.}
{120}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente e
 Uma armadilha altamente explosiva no quadro da porta.}
{121}{}{Você vê uma porta resistente com uma trava velha e enferrujada e uma
 Armadilha explosiva no quadro da porta.}

{122}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Lockpicks e uma armadilha no quadro da porta.}
{123}{}{Você vê uma porta resistente com um bloqueio e uma armadilha em
 O quadro da porta.}
{124}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente e
 Uma armadilha no batente da porta.}
{125}{}{Você vê uma porta resistente com uma trava velha e enferrujada e uma armadilha
 No batente da porta.}

{126}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Trancadas e um fio cortado no quadro da porta.}
{127}{}{Você vê uma porta resistente com um bloqueio e um fio cortado
 No batente da porta.}
{128}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente e
 Um fio cortado no quadro da porta.}
{129}{}{Você vê uma porta resistente com um bloqueio velho e enferrujado e um corte
 Fio no quadro da porta.}

{130}{}{Você vê uma porta de estudo com uma fechadura que pode ser colhida com
 Lockpicks.}
{131}{}{Você vê uma porta resistente com um bloqueio nele.}
{132}{}{Você vê uma porta resistente com nenhum dispositivo de bloqueio aparente.}
{133}{}{Você vê uma porta resistente com um bloqueio velho e enferrujado.}

# Perception Check Critical Failure

{134}{}{Você vê uma porta danificada com um bloqueio que pode ser colhido com
 Lockpicks e uma armadilha altamente explosiva no quadro da porta.}
{135}{}{Você vê uma porta danificada com um bloqueio e uma
 Armadilha explosiva no quadro da porta.}
{136}{}{Você vê uma porta danificada sem dispositivo de bloqueio aparente e
 Uma armadilha altamente explosiva no quadro da porta.}
{137}{}{Você vê uma porta danificada com um bloqueio velho e enferrujado e uma
 Armadilha explosiva no quadro da porta.}

{138}{}{Você vê uma porta danificada com um bloqueio que pode ser colhido com
 Lockpicks e uma armadilha no quadro da porta.}
{139}{}{Você vê uma porta danificada com um bloqueio e uma armadilha em
 O quadro da porta.}
{140}{}{Você vê uma porta danificada sem dispositivo de bloqueio aparente e
 Uma armadilha no batente da porta.}
{141}{}{Você vê uma porta danificada com um bloqueio velho e enferrujado e uma armadilha
 No batente da porta.}

{142}{}{Você vê uma porta danificada com um bloqueio que pode ser colhido com
 Trancadas e um fio cortado no quadro da porta.}
{143}{}{Você vê uma porta danificada com um bloqueio e um fio cortado
 No batente da porta.}
{144}{}{Você vê uma porta danificada sem dispositivo de bloqueio aparente e
 Um fio cortado no quadro da porta.}
{145}{}{Você vê uma porta danificada com um bloqueio velho e enferrujado e um corte
 Fio no quadro da porta.}

{146}{}{Você vê uma porta danificada com um bloqueio que pode ser colhido com
 Lockpicks.}
{147}{}{Você vê uma porta danificada com um bloqueio nele.}
{148}{}{Você vê uma porta danificada sem dispositivo de bloqueio aparente.}
{149}{}{Você vê uma porta danificada com um bloqueio velho e enferrujado.}

# Perception Check Failure

{150}{}{Você vê uma porta velha com um bloqueio que pode ser colhido com
 Lockpicks e uma armadilha altamente explosiva no quadro da porta.}
{151}{}{Você vê uma porta velha com um bloqueio e uma
 Armadilha explosiva no quadro da porta.}
{152}{}{Você vê uma porta velha sem dispositivo de bloqueio aparente e
 Uma armadilha altamente explosiva no quadro da porta.}
{153}{}{Você vê uma porta velha com um bloqueio velho e enferrujado e um
 Armadilha explosiva no quadro da porta.}

{154}{}{Você vê uma porta velha com um bloqueio que pode ser colhido com
 Lockpicks e uma armadilha no quadro da porta.}
{155}{}{Você vê uma porta velha com um bloqueio nele e uma armadilha em
 O quadro da porta.}
{156}{}{Você vê uma porta velha sem dispositivo de bloqueio aparente e
 Uma armadilha no batente da porta.}
{157}{}{Você vê uma porta velha com um bloqueio velho e enferrujado e uma armadilha
 No batente da porta.}

{158}{}{Você vê uma porta velha com um bloqueio que pode ser colhido com
 Trancadas e um fio cortado no quadro da porta.}
{159}{}{Você vê uma porta velha com um bloqueio e um fio cortado
 No batente da porta.}
{160}{}{Você vê uma porta velha sem dispositivo de bloqueio aparente e
 Um fio cortado no quadro da porta.}
{161}{}{Você vê uma porta velha com um bloqueio velho e enferrujado e um corte
 Fio no quadro da porta.}

{162}{}{Você vê uma porta velha com um bloqueio que pode ser colhido com
 Lockpicks.}
{163}{}{Você vê uma porta velha com um bloqueio nele.}
{164}{}{Você vê uma porta velha sem dispositivo de bloqueio aparente.}
{165}{}{Você vê uma porta velha com um bloqueio velho e enferrujado.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# Você desencadeou a armadilha e foi atingido por[x] Pontos de dano.
# NPC sets of the trap and was hit for [x] Pontos de dano.

# Player sets off the trap
{166}{}{Você desencadeou a armadilha e foi atingido por}
{167}{}{ Pontos de dano.}

# NPC sets off the trap
{168}{}{ Desencadeia a armadilha e foi atingido por}
{169}{}{ Pontos de dano.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Você escolhe habilmente o bloqueio na porta.}
{171}{}{Sua falta de habilidade bloqueou a fechadura nesta porta.}
{172}{}{Você não consegue escolher o bloqueio nesta porta.}

# Lock Door
{189}{}{Você habilmente bloqueia a porta.}
{190}{}{Você não bloqueia a porta.}

# Find Trap on the Door
{194}{}{Você encontra uma armadilha na porta.}
{195}{}{Você não consegue encontrar armadilhas na porta.}

# Disarm the Trap on the Door
{196}{}{Você habilmente desarmar a armadilha.}
{198}{}{Você não consegue desarmar a armadilha.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ Escolhe habilmente a fechadura na porta.}
{174}{}{A falta de habilidade atolou a fechadura nesta porta.}
{175}{}{ Não conseguiu escolher o bloqueio nesta porta.}

# Lock Door
{191}{}{ Bloqueia habilmente a porta.}
{192}{}{ Não conseguiu bloquear a porta.}

# Find Trap on the Door
{199}{}{ Encontra uma armadilha na porta.}
{200}{}{ Não consegue encontrar armadilhas na porta.}

# Disarm the Trap on the Door
{201}{}{ Destrói habilmente a armadilha.}
{202}{}{ Não desarmar a armadilha.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Você corta a fechadura da porta.}
{177}{}{Você pressiona suas costas enquanto tenta abafar o bloqueio e
 Tomar um ponto de dano.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] Pontos de dano.

{178}{}{Você pressiona suas costas enquanto tenta abafar o bloqueio e
 levar}
{179}{}{ Pontos de dano.}
{180}{}{Você é muito fraco para destruir o bloqueio.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ Bifurca o bloqueio da porta.}
{182}{}{ Estica as costas enquanto tenta abater a fechadura e leva
 Um ponto de dano.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ Estica as costas enquanto tenta abater a fechadura e leva}
{184}{}{ Pontos de dano.}

{185}{}{ É muito fraco para destruir o bloqueio.}
{186}{}{ Estica as costas enquanto tenta abater a fechadura e leva
 Um ponto de dano.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ Estica as costas enquanto tenta abater a fechadura e leva}
{188}{}{ Pontos de dano.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Os explosivos nem sequer colocam um risco na porta.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{A porta parece estar bloqueada.}
{204}{}{Você percebe uma armadilha no engarrafamento da porta.}

# NPC finds trap
# The following line is to be translated as:
# NPC Percebe uma armadilha no engate da porta.

{205}{}{ Percebe uma armadilha no engate da porta.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Você não consegue colocar uma armadilha nesta porta, porque
 a porta está aberta.}

# NPC tries to set a trap on an open door
{207}{}{ É incapaz de colocar uma armadilha nesta porta, porque a
 A porta está aberta.}

# Player tries to set a trap on a closed door
{208}{}{Você habilmente configurou uma armadilha na moldura da porta.}
{209}{}{Você não configura adequadamente a armadilha no quadro da porta.}

# NPC tries to set a trap on a closed door
{210}{}{ Habilmente define uma armadilha na moldura da porta.}
{211}{}{ Não configura adequadamente a armadilha no quadro da porta.}

# This is used specificly for this door
{212}{}{Esta porta não desbloqueia aqui.}
{213}{}{A porta não se moverá.}
