{100}{}{Você vê um terminal.}
{101}{}{Este é um terminal de computador. Muitas vezes, ele é usado para controlar outros objetos.}

# Specific
{200}{}{Este terminal parece controlar as portas deste bloco celular.}
{201}{}{Seqüência de código inválida.}
{202}{}{As portas estão agora abertas.}
{203}{}{As portas agora estão fechadas.}
{204}{}{Idéia interessante, mas não funcionou.}
{205}{}{Hmmm, essas coisas do computador são complicadas.}
