{100}{}{Você vê uma porta.}
{101}{}{Parece muito resistente.}
{102}{}{A porta não parece se mexer.}
{103}{}{(Você percebe um pequeno orifício na porta da qual o som parece estar vindo.) Olá?}
{104}{}{Uhh, oi?}
{105}{}{Desde quando as portas podem falar?}
{106}{}{Uhh, oi.}
{107}{}{GANG PROBLEM LIMB.}
{108}{}{Clique ... (A porta desbloqueia.)}
{109}{}{Desculpe, não precisamos de nada disso.}
{110}{}{A porta está aparafusada do outro lado. Não parece haver nada para escolher.}
{111}{}{A porta está nivelada no quadro e não tem lugar para colocar uma armadilha.}
{112}{}{A porta range e quebra sob a tensão.}
{113}{}{A porta já está destrancada.}
{114}{}{A porta não é um desafio para você.}
