{100}{}{Você vê um quadro de avisos.}
{101}{}{Você vê um quadro de avisos com as leis publicadas da NCR.}
{102}{}{Este é um quadro de avisos típico com várias folhas de papel inseridas. Entre os avisos destacam-se as leis da NCR.}
{103}{}{Bem-vindo à Nova República da Califórnia! Antes de entrar na nossa cidade justa, tome um momento para se familiarizar com as seguintes regras e regulamentos.}
{104}{}{Nenhuma arma pode ser carregada abertamente dentro dos limites da cidade.}
{105}{}{As pessoas encontradas sob a influência de álcool ou chems serão presas.}
{106}{}{A escravidão, o jogo e a prostituição não são permitidos dentro dos limites da cidade.}
{107}{}{Desconhecimento da lei não é desculpa. Um idiota conseguirá seu traseiro chutado tão rápido como um smartass.}
{108}{}{Se você não pode viver com essas leis - então, saia do ar!}
{109}{}{É melhor arrumar as armas. Nós queremos dizer isso.}
{110}{}{Obedecer a lei é uma boa cidadania.}
{111}{}{Costas}
{112}{}{Eu li o suficiente disso.}
{113}{}{Isso não é bom para seus hábitos recreativos.}
{114}{}{Bom, não haverá bêbados ou viciados que o incomodem por consertar dinheiro.}
{115}{}{Costas}
{116}{}{Eu li o suficiente disso.}
{117}{}{Bem, vão algumas margens lucrativas diretamente pelo pônei de porcelana!}
{118}{}{Parece que eles estão tentando criar uma comunidade respeitável e decente para as pessoas viverem.}
{119}{}{Costas}
{120}{}{Eu li o suficiente disso.}
{121}{}{Palavras bastante duras. Você pode apenas ter que ver se você pode levá-los a comê-los.}
{122}{}{A igualdade perante a lei é uma coisa boa.}
{123}{}{Costas}
{124}{}{Eu li o suficiente disso.}
{125}{}{Ensinar a esses caras, algum respeito está ganhando prioridade em sua lista de coisas para fazer.}
{126}{}{É um pouco contundente, mas isso faz frente.}
{127}{}{Costas}
{128}{}{Eu li o suficiente disso.}
