{100}{}{Você vê Amanda.}
{101}{}{Você vê uma mulher cansada. Parece que ela está chorando.}
{102}{}{Você vê Amanda.}
{103}{}{Você vê uma mulher cansada. Parece que ela está chorando.}
{104}{}{Você vê Amanda. She is looking much happier now that Joshua is free.}
{105}{}{Você vê Amanda.}
{106}{}{Você vê Amanda. She is looking much happier now that Joshua is free.}
{107}{}{Oh, Joshua ...}
{108}{}{O que eu vou fazer?}
{109}{}{O dinheiro está acabado ...}
{110}{}{Se apenas os Cidadãos o deixassem ir ...}
{111}{}{Joshua, estou tão feliz por você ser livre. Eu estava tão preocupado...}
{112}{}{Me desculpe, não tenho nenhum folheto para lhe dar.}
{113}{}{Por favor, deixe-me em paz, ou ligarei para os guardas.}
{114}{}{O que você quer?}
{115}{}{Você está bem? Você parece chateado.}
{116}{}{Nada. Lamento perturbá-lo.}
{117}{}{Eu ... bem, eu ... é meu marido Joshua. Ele ... entrou em algum problema em ... o bar. Ele acidentalmente atingiu um cidadão e foi preso. Ele não quis dizer, mas ele estava bebendo e ...}
{118}{}{Preso? Onde ele está agora?}
{119}{}{Se ele estivesse bêbado e atacasse alguém, então ele deveria ser preso.}
{120}{}{Sinto muito por ouvir isso. Espero que o deixem ir.}
{121}{}{Dentro da cidade, no Centro de Alocação de Serventes ... eles disseram que poderia resolver sua sentença de prisão como Servente, mas isso levará anos!}
{122}{}{O que pode ser feito?}
{123}{}{Se ele estivesse bêbado e atacasse alguém, então ele deveria ser preso.}
{124}{}{Sinto muito por ouvir isso. Espero que o deixem ir.}
{125}{}{Mas foi um acidente! Eu ... ele não queria fazê-lo!}
{126}{}{Onde ele está agora?}
{127}{}{Ele não quis atacar alguém? Certo. Talvez esta seja uma boa lição para você.}
{128}{}{Sinto muito por ouvir isso. Espero que o deixem ir.}
{129}{}{Não tenho muito dinheiro, e teremos que sair em breve se não pudermos pagar os protetores por proteção. Eles disseram que se quisermos ficar com Joshua, então eles poderiam nos fazer servos, também ...}
{130}{}{Isso parece uma solução. Eles tratam bem os servos em Vault City, não é?}
{131}{}{Deixe-me ver o que posso fazer, ok? Talvez eu possa falar com alguém no Centro de Atribuição.}
{132}{}{Eu poderia te ajudar. Mas vai custar-lhe.}
{133}{}{Sinto muito por ouvir isso. Espero que o deixem ir.}
{134}{}{Eu não quero que meu filho seja criado como escravo! Chegamos a Vault City porque ouvimos que era uma cidade livre ... mas chegamos aqui ... e há todas essas leis e pagamentos aos guardas e ... não é nada como o que nos disseram.}
{135}{}{Deixe-me ver o que posso fazer, ok? Talvez eu possa falar com alguém no Centro de Atribuição.}
{136}{}{Sinto muito por ouvir isso. Espero que o deixem ir.}
{137}{}{O homem responsável é Barkus, Officer Barkus. Eu não podia nem entrar na cidade para vê-lo. Eu nem sei se Joshua está bem! EU...}
{138}{}{Não se preocupe. Verei o que posso fazer.}
{139}{}{Mas eu não tenho muito dinheiro e ...}
{140}{}{Eu não estava pensando em dinheiro.}
{141}{}{Deixa pra lá. Talvez eu possa falar com alguém no Centro de Atribuição.}
{142}{}{Lamentamos ouvir isso, então. Talvez eles apenas o deixem ir. Adeus.}
{143}{}{O que você m ...? Ah não. Eu ... não poderia. Digo, eu...}
{144}{}{Você quer o seu marido livre ou não? Seu marido nunca precisa saber.}
{145}{}{Deixa pra lá. Talvez eu possa falar com alguém no Centro de Atribuição.}
{146}{}{Sinto muito por ouvir isso. Parece que você é marido nunca será livre. Adeus.}
{147}{}{Se você promete libertar meu marido, eu ... eu ... muito bem. Eu ... fecho a aba da barraca. Eu ... acho que meu filho ainda está jogando fora, então não nos incomodaremos.}
{148}{}{Não se preocupe, vou liberar seu marido. Depois de receber o meu pagamento.}
{149}{}{Esqueça. Talvez eu possa falar com alguém no Centro de Atribuição.}
{150}{}{Deixa pra lá. Esqueça que nos conhecemos.}
{151}{}{Ei, e quanto a mim ?!}
{152}{}{Por favor, salve Joshua. Ele está dentro da cidade no Centro de Atribuição de Servos.}
{153}{}{Obrigado por resgatar meu marido! Por favor ... aceite isso como uma recompensa. Não é muito, mas ...}
{154}{}{Obrigado novamente por resgatar meu marido. Vamos em breve.}
{155}{}{Uh ... obrigado por resgatar meu marido ... por favor, não diga o que aconteceu entre nós.}
