{100}{}{Você vê ... outro ... funcionário da Vault City.}
{101}{}{Você vê Barkus, o coordenador do servo da cidade de Vault.}
{102}{}{O que ... ?! Um mutante! Em Vault City! Guardas! Guardas!}
{103}{}{O que ... ?! Um ghoul! Em Vault City! Guardas! Guarda!}
{104}{}{Umm ... hurnhh?}
{105}{}{Se é uma luta que você quer ...}
{106}{}{O Centro de Alocação de Serventes está fechado. Por favor, voltei de manhã.}
{107}{}{Sim, capitão?}
{108}{}{Sim, cidadão?}
{109}{}{Sim o que é isso? Estou atrasado em minhas atribuições.}
{110}{}{Umm ... Me luuwk Valt!}
{111}{}{Shamble off}
{112}{}{O que é esse edifício?}
{113}{}{Estou procurando o Vault.}
{114}{}{Estou à procura de um servo particular ... Joshua, eu acredito. Ele está aqui?}
{115}{}{Você está procurando comprar algum escravo ... er, criados?}
{116}{}{Nada hoje, obrigado.}
{117}{}{Este? Por que, este é o Servant Assignment Center. Você precisava de um servo?}
{118}{}{Este é o Servant Assignment Center.}
{119}{}{Servant Assignment Center? O que é isso?}
{120}{}{Estou à procura de um servo particular ... Joshua, eu acredito. Ele está aqui?}
{121}{}{Alocação de Servas, hein? Você compra escravos ... er, criados aqui?}
{122}{}{Não, apenas curioso. Obrigado.}
{123}{}{Apenas curioso. obrigado.}
{124}{}{O cofre? É esse enorme buraco na montanha no lado leste da cidade. Sair da porta da frente, vire à esquerda e siga em frente. Você não pode perder isso.}
{125}{}{O que é esse edifício?}
{126}{}{Alguém pode entrar?}
{127}{}{Tive outra pergunta para você.}
{128}{}{Obrigado pelas instruções. Adeus.}
{129}{}{O que? Você é um dos novos servos?}
{130}{}{Sim}
{131}{}{Uh-uh me deixa agora}
{132}{}{Você deve ser novo aqui. Vou explicar isso ... devagar.}
{133}{}{Os cidadãos que necessitam de ajuda com tarefas domésticas vêm aqui para ter um Servo atribuído a eles para o dia.}
{134}{}{Isso soa muito como a escravidão.}
{135}{}{Ah, então é onde os escravos estão armazenados? Por que você não disse isso?}
{136}{}{Onde você recebe todos esses servos?}
{137}{}{Estou à procura de um servo particular ... Joshua, eu acredito. Ele está aqui?}
{138}{}{Você está procurando comprar escravos ... er, criados, agora mesmo?}
{139}{}{Tudo bem, apenas curioso, obrigado. Dia bom.}
{140}{}{Estou cansado de serem enviados Servidores sem autorização ... * suspiro * ... vamos ver, você disse que estava procurando o Vault?
 Essa deve ser sua tarefa para o dia. Muito bem. Eu vou ter alguém escoltando você lá.}
{141}{}{Valt! Valt!}
{142}{}{Eu assistiria esse tipo de conversa se eu fosse você. Não é escravidão. Nós cuidamos desses refugiados,
 e eles têm uma boa vida ... melhor do que eles iriam entrar nos resíduos.}
{143}{}{Onde você os obtém?}
{144}{}{Ah, eu tive algumas outras perguntas ...}
{145}{}{Foi o que eu precisava saber, obrigado. Dia bom.}
{146}{}{Não, você precisa ser um cidadão para ser permitido no Vault. Agora, olhe, eu estou muito ocupado no momento, então, se você me desculpe por favor ...}
{147}{}{Apenas mais uma pergunta ...}
{148}{}{Tudo certo. Adeus.}
{149}{}{Nossos servos geralmente são refugiados de ataques de invasores ou prisioneiros contratuais que desejam trabalhar fora de sua sentença de maneira produtiva.}
{150}{}{Oh, você quer dizer scripts? Eu conheci esse cara chamado Dan uma vez que ...}
{151}{}{Ao custo de sua liberdade, hein?}
{152}{}{Você tem um prisioneiro contratual chamado Joshua sob custódia?}
{153}{}{Você está procurando comprar qualquer escravo ... er, criados ... agora mesmo?}
{154}{}{Hmmm. Eu tive outra pergunta ...}
{155}{}{Entendo. Obrigado pela informação.}
{156}{}{Não, não scripts, você é idiota.}
{157}{}{Idiota? Eu tive que trabalhar duro para obter o mínimo de 9 Inteligência e Percepção para encontrar esse nó. De qualquer forma, você estava dizendo?}
{158}{}{Você é um bom para fazer julgamentos morais, escravos. Saia daqui.}
{159}{}{Você soa muito como aquele idiota Moore ... exatamente o que a Cidade do Vault precisa. Olha, quem quer que você seja, eu tenho trabalho a fazer, então, se você se retirar ...}
{160}{}{Tudo bem, tudo bem...}
{161}{}{Por que você não me deixa?}
{162}{}{Joshua? Sim, nós temos um servo com esse nome, mas você não quer que ele seja atribuído a você.
 Treinar ele foi ... difícil. Não tenho certeza de que ele possa ser treinado.}
{163}{}{Joshua? Acho que já tínhamos um servo com esse nome, mas não mais.}
{164}{}{Eu preciso questioná-lo sobre uma questão de segurança da Vault City. Peça-o para o pátio
 de uma vez só.}
{165}{}{Gostaria que ele fosse atribuído a mim de qualquer maneira.}
{166}{}{Difícil?}
{167}{}{Oh, não quero que ele seja atribuído a mim. Longe disso. Estou preocupado com o fato de ele estar infectado.}
{168}{}{Hmmm. Outra pergunta então ...}
{169}{}{Tudo certo. Adeus.}
{170}{}{Eu não acho que seja uma boa idéia. Aguarde até que ele tenha passado por algum treinamento mais primeiro, então eu vou considerá-lo.}
{171}{}{Você disse que tem sido difícil?}
{172}{}{Apenas mais uma pergunta ...}
{173}{}{Tudo certo. Adeus.}
{174}{}{Sim, ele é mais teimoso do que quase qualquer Servo que já tivemos aqui. Se eu não soubesse
 melhor, eu assumiria que seu pai era um brâmane.}
{175}{}{Você sabe, esse tipo de atitude pode ser um problema. E se o resto do
 Os servos começam a seguir o exemplo dele?}
{176}{}{Eu poderia comprá-lo e tirá-lo de suas mãos. O Centro leva ... "doações?"}
{177}{}{Apenas mais uma pergunta ...}
{178}{}{Tudo certo. Adeus.}
{179}{}{Isso é verdade. Eu tive que separá-lo de alguns dos outros ... e apenas ontem um dos Servos realmente teve a audácia de questionar um dos meus pedidos.}
{180}{}{Você deve libertá-lo agora antes de piorar.}
{181}{}{Joshua? Sim, temos um Servidor com esse nome. Ele foi recentemente transferido do Centro de correções. Seu interesse por ele é ...?}
{182}{}{Gostaria de negociar o seu lançamento.}
{183}{}{Eu suspeito que ele tenha uma doença contagiosa. Você pode querer liberá-lo antes que ele infecte os outros servos.}
{184}{}{Sem motivo. Tive algumas outras questões ...}
{185}{}{Tudo certo. Adeus.}
{186}{}{Sério? E o que faz você pensar que eu iria liberá-lo?}
{187}{}{Uma doação importante para o fundo operacional do Centro de Alocação Servant, talvez?}
{188}{}{Eu suspeito que ele tenha uma doença contagiosa. Você pode querer liberá-lo antes que ele infecte os outros servos.}
{189}{}{Sem motivo. Tive algumas outras questões ...}
{190}{}{Tudo certo. Adeus.}
{191}{}{Não, eu estava pensando em uma doação mais importante.}
{192}{}{Hmmn. As doações são bem-vindas para assegurar o bom funcionamento do Centro, mas exigiria uma doação importante antes que eu pudesse libertar Joshua em seu cuidado.}
{193}{}{Como cerca de US $ 1000?}
{194}{}{Como cerca de US $ 750?}
{195}{}{Como cerca de US $ 500?}
{196}{}{Como cerca de US $ 250?}
{197}{}{Vou pensar sobre isso. Tive algumas outras questões ...}
{198}{}{Entendo. Posso voltar mais tarde.}
{199}{}{Entendo. Posso voltar mais tarde quando tiver fundos suficientes para uma doação.}
{200}{}{Bem ... isso não é tanto de uma doação como eu gostaria, mas vai fazer. Eu vou velar por que este Joshua você tenha
 solicitado é enviado para o Courtyard para processamento. Deixe-me fazer os arranjos necessários.}
{201}{}{OK.}
{202}{}{Está feito. Joshua não é mais um servo da cidade de Vault, e ele foi transferido para o pátio com o resto
 dos Outworlders.}
{203}{}{Obrigado. Tive algumas outras questões ...}
{204}{}{Muito bem. Eu vou buscá-lo lá, então.}
{205}{}{Parece bom. Espero que ele não volte para a cidade.}
{206}{}{É assim mesmo? Você está ciente de que cada Servente é cuidadosamente verificado antes de ser admitido no Centro de Atribuição?}
{207}{}{Maybe I was wrong. Nevertheless, Gostaria de negociar o seu lançamento.}
{208}{}{Você está ciente de}
{209}{}{Síndrome de S? Não aparece na maioria das varreduras médicas, e seus sintomas podem ficar dormentes por semanas.}
{210}{}{Nos resíduos, existe uma doença chamada}
{211}{}{Síndrome de s. Talvez você tenha percebido o nível de energia reduzido de seus Servos recentemente? Sua superação geral?}
{212}{}{Isso é absurdo. Agora, se você acabou de perder meu tempo com suas mentiras ...}
{213}{}{Tudo bem, esqueça "}
{214}{}{Síndrome de S ". Eu ainda gostaria de negociar o lançamento de Joshua.}
{215}{}{Deixa pra lá então. Tive algumas outras questões ...}
{216}{}{Estou indo embora. Adeus.}
{217}{}{Infectado? Infectado com o quê?}
{218}{}{Sintomas? Que tipo de sintomas?}
{219}{}{Talvez você tenha percebido o nível de energia reduzido de seus Servos recentemente? Alcance de atenção curto? A sua incapacidade de ouvir ordens e segui-las corretamente? Esses são apenas os estágios iniciais.}
{220}{}{Uh ...}
{221}{}{Síndrome de s. Muitos Outworlders têm isso. Seus sintomas incluem, uh, falando quando não é falado. E usando
 linguagem grosseira.}
{222}{}{Hmmmm. Não faria se os cidadãos começassem a relatar problemas com os servos ... muito bem, eu vou soltar Joshua em
 uma vez. Se você me desse um momento para fazer os arranjos ...}
{223}{}{Sim ... Observei esses sintomas nos Servos tarde. Contagioso, você diz? Hmmm. Bem, se este Joshua é um
 transportador, eu o liberarei imediatamente. Dê-me um momento para fazer os arranjos ...}
{224}{}{Sem problemas. Joshua seria melhor com os Outworlders de qualquer maneira.}
{225}{}{Claro, capitão. Eu vou cuidar disso agora.}
{226}{}{Excelente. Obrigado, cidadão.}
{227}{}{Possivelmente. Você tem algum que deseja vender?}
{228}{}{Sim, tenho um aqui comigo. Dê uma olhada e me faça uma oferta.}
{229}{}{Sim, tenho alguns aqui comigo. Dê uma olhada e me faça uma oferta.}
{230}{}{Na verdade não. Tive algumas perguntas para você ...}
{231}{}{Não, não hoje, na verdade. Adeus.}
{232}{}{Hmmm. Aquela mulher lá, Miria, é? Ela tem braços fortes ... e quadris agradáveis. Vou comprá-la de você por US $ 250.}
{233}{}{Hmmm. aquele garoto, Davin, não é? Ele parece relativamente livre da contaminação do Outworlder. Vou comprá-lo de você por US $ 250.}
{234}{}{Hmmm. Aquele tribal que você tem. Ele cheira ... fortemente. Mas ele parece saudável. Vou levá-lo por US $ 100.}
{235}{}{Hmmm. Aquele homem lá ... Vic, não é? Embora seja velho, ele parece um handyman. $ 100.}
{236}{}{Talvez você devesse voltar quando tiver um servo de valor para me mostrar. Seu estoque atual ...
 não é impressionante.}
{237}{}{Vamos, o escravo vale mais do que isso.}
{238}{}{Esse é um preço justo. O servo é todo seu.}
{239}{}{Na verdade, não estou procurando vender aquele ainda. Tive algumas perguntas que queria lhe perguntar ...}
{240}{}{Na verdade, não estou olhando para vender esse escravo. Vamos tratar outra hora.}
{241}{}{Muito bem. Eu tive algumas perguntas para você, no entanto ...}
{242}{}{Tudo certo. Mais uma vez, quando eu tiver um estoque melhor, então.}
{243}{}{Não, acho que não ... 250 ou nada.}
{244}{}{Não, o garoto parece que seria difícil treinar ... 200 ou nada.}
{245}{}{Veja. Vai demorar uma semana a lavar o cheiro dessa tribal. 100 ou nada.}
{246}{}{Você não pode nem me prometer que ele não terá um ataque de calor uma vez que ele deixa seu cuidado. Ele vendeu. 100 ou nada.}
{247}{}{Tudo bem, isso é justo. O servo é todo seu.}
{248}{}{Esqueça, então. Tive algumas perguntas que queria lhe perguntar ...}
{249}{}{Nada é, então. Não posso permitir que meu servo vá por esse preço. Talvez outra hora.}
{250}{}{Hmmmm ... Ela parece um espécime saudável ... talvez eu possa colocá-la para trabalhar por aqui. $ 500. E essa é a minha oferta final.}
{251}{}{Hmmmm. Ele é um espécime saudável. US $ 400 para ele, então.}
{252}{}{Hmmmm. Tudo certo. $ 200, então. E não mais regatear.}
{253}{}{Hmmmmmmm. $ 200. E não um dólar mais.}
{254}{}{Isso é justo. O servo é todo seu.}
{255}{}{Na verdade, não estou procurando vender aquele ainda. Tive algumas perguntas que queria lhe perguntar ...}
{256}{}{Na verdade, não estou olhando para vender esse escravo. Vamos tratar outra hora.}
{257}{}{Excelente. Aqui está o seu dinheiro. Eu irei embarcar para testes médicos e processamento.}
{258}{}{Excelente. Aqui está o seu dinheiro. Vou mandá-lo para testes médicos e processamento.}
{259}{}{Excelente. Aqui está o seu dinheiro. Eu terei o tribal enviado para testes médicos e processamento.}
{260}{}{Excelente. Aqui está o seu dinheiro. Vou ter o velho enviado para testes médicos e processamento.}
{261}{}{Dê-me um momento para cuidar dos arranjos ...}
{262}{}{Certo. Espero aqui.}
{263}{}{Muito bem. Seu servo foi reassentado para testes médicos e re-condicionado.
 Curioso ... o Servo parecia bastante surpreso com todo o assunto. Levou um pouco de tranquilizante
 Dardos para suavizar as coisas. Coloquei tudo que o Servente estava carregando na caixa no meu escritório.}
{264}{}{Bem, os servos serão servos. Eu tive algumas outras perguntas que eu queria lhe perguntar ...}
{265}{}{Mesmo? Bem, eu tenho certeza que eles serão mais dóceis com o passar do tempo. Você está interessado em outros companheiros?}
{266}{}{Sim, podem ser um pouco difíceis no início; eles se acostumarão com isso. Dia bom.}
{267}{}{O que você está fazendo de volta aqui? Eu enviei você para o Vault! De todos os ... muito bem, vou ter alguém escoltá-lo de volta.}
{268}{}{Oh-keeeee}
{269}{}{Você convenceu Barkus para libertar Joshua.}
