{100}{}{Você vê um homem idoso com rugas profundas ao longo do rosto. Se ele percebe que você olha para ele, ele não dá nenhum sinal.}
{101}{}{Você vê Cassidy.}
{102}{}{Você vê um homem idoso com rugas profundas ao longo do rosto. Ele acena com a cabeça para você.}
{103}{}{Bem agora. Eu não te vi antes, estranho. Nome Cassidy. Eu corro esse lugar. O que posso fazer para você?}
{104}{}{Bem, agora, se não é o estranho misterioso. O que eu posso fazer para você hoje?}
{105}{}{Ug Nog?}
{106}{}{Shamble off}
{107}{}{Estou procurando o Vault.}
{108}{}{Você está procurando sair daqui ainda?}
{109}{}{O que você tem na torneira?}
{110}{}{Alguma coisa interessante acontecendo aqui?}
{111}{}{Nada hoje, obrigado.}
{112}{}{Ataque na cabeça um pouco com muita frequência, hein? Desculpe, eu não falo imbecil.}
{113}{}{Bee-sil?}
{114}{}{Cofre? Apenas o Vault que conheço é aquele dentro da cidade. Grande buraco de friggin ... você não pode perder, confie em mim.}
{115}{}{O que você tem para beber aqui?}
{116}{}{Alguma coisa interessante acontecendo aqui?}
{117}{}{Obrigado pelas instruções. Adeus.}
{118}{}{Cerveja por US $ 20, tiro de uísque por US $ 30. Nada especial. Por que, você quer alguma coisa?}
{119}{}{Estou procurando o Vault.}
{120}{}{Vou tomar uma cerveja.}
{121}{}{Vou tirar uma chance.}
{122}{}{Alguma coisa interessante acontecendo aqui?}
{123}{}{Na verdade não. Obrigado mesmo assim.}
{124}{}{"Interessante?" Heh. Amigo, Vault City não é um lugar "interessante" ... a menos que os guardas se aborreçam, então você
 Melhor se cobrir. Por que está perguntando? Você está procurando alguma coisa neste poço?}
{125}{}{O que você tem para beber aqui?}
{126}{}{Actually, Estou procurando o Vault.}
{127}{}{Não pode ser tão ruim aqui.}
{128}{}{Na verdade não. Obrigado mesmo assim.}
{129}{}{Aqui está. Beber. Isso pode ajudá-lo a esquecer onde você está.}
{130}{}{Este lugar não pode ser tão ruim assim.}
{131}{}{Obrigado pela bebida. Eu tenho que ir.}
{132}{}{Sério? Bem, então, eu devo me enganar, considerando VOCÊ é a autoridade e tudo. Adivinha que você deve ter dormido durante a incursão na semana passada?}
{133}{}{Raid?}
{134}{}{Aw, sim, uma bela vista era. Uma patrulha de guarda entrou aqui procurando por "substâncias ilegais". Eles derrubaram a porta, arruinaram meu estoque, e depois invadiram alguns dos meus clientes também.}
{135}{}{O que aconteceu depois disso?}
{136}{}{Desculpe ouvir isso. Eu falarei com você mais tarde.}
{137}{}{Depois que eles tiraram esse cara, Joshua, por resistir à prisão, eles multaram minha bunda por encontrar - pegue isso - whisky REAL nas instalações. Não pergunte que recebi uma licença da Stark três meses antes. Bastardos.}
{138}{}{Uau. Sem brincadeiras.}
{139}{}{Desculpe ouvir isso. Eu falarei com você mais tarde.}
{140}{}{Isso fica melhor. Agora estou em dívida com os guardas pela multa, e "eu tive que comprar um novo caso de álcool de um comerciante no triplo da minha taxa padrão. Estou esperando que os guardas vençam a bater novamente em breve, apenas para derrubar minhas costeletas.}
{141}{}{Como é a maior parte do tempo?}
{142}{}{Espero que as coisas o busquem no futuro. Até logo.}
{143}{}{Mesmo os bons dias não valem a pena. Os cidadãos não bebem muito, então estou preso aqui derramando bebidas para comerciantes. O próximo sonuvabitch barato, que regateou uma bebida, estará vestindo sua bunda como chapéu.}
{144}{}{Por que você está aqui se você odeia tanto?}
{145}{}{Desculpe ouvir isso. Estou procurando um Vault. Você pode me ajudar?}
{146}{}{Desculpe ouvir isso. Espero que as coisas melhorem.}
{147}{}{Eu tenho um coração ruim. Preciso de tiros de reforço cardio para mantê-lo batendo. Esta cidade é o único lugar para obter cuidados médicos reais, então pensei que eu me conformaria aqui, tentaria e ganharia a vida.}
{148}{}{Você parece muito alimentado com o lugar.}
{149}{}{Entendo. Diga, estou procurando um Vault. Você pode me ajudar?}
{150}{}{Espero que as coisas melhorem para você a partir daqui. Até logo.}
{151}{}{Me faz querer fechar a loja e deixar esta cidade apodrecer. Toque-os em tudo.}
{152}{}{Por que você não sai?}
{153}{}{Desculpe ouvir isso. Espero que as coisas funcionam para você.}
{154}{}{Ir para os resíduos sozinho? Ha! Estou cansado deste lugar, mas não sou estúpido.}
{155}{}{Estou indo de novo assim. Por que você não vem?}
{156}{}{Bem, boa sorte para você então.}
{157}{}{Não há ofensa nem nada, mas você não parece muito capaz de liderar ninguém. Parece que os resíduos o teriam para o jantar.}
{158}{}{Naw, eu não viajo com escravas. Eles têm um hábito desagradável de vender você quando eles ganham pouco dinheiro. Sem ofensa.}
{159}{}{Naw, você tem a aparência de alguém com um pé no túmulo e outro no inferno. Eu não acho que eu preciso manchar minha reputação mais do que é.}
{160}{}{Naw ... você parece que já tem bastante de uma multidão.}
{161}{}{Tudo certo. Bem, boa sorte.}
{162}{}{Esqueça que eu perguntei então, idiota. Volte para cuidar da barra em este bairro de água quente.}
{163}{}{Deixa pra lá então. Sua perda.}
{164}{}{Heh. Está falando sério?}
{165}{}{Certo. Por que diabos não? Você parece saber como se cuidar em uma luta.}
{166}{}{Pensando bem, é muito perigoso lá fora, especialmente para alguém com problemas cardíacos. Você seria melhor aqui.}
{167}{}{Tudo bem, conte-me.}
{168}{}{Vamos bater nisso.}
{169}{}{}
{170}{}{}
{171}{}{Estás bem? Você tem que "eu preciso dizer-lhe algo que você não pode gostar", olhe novamente.}
{172}{}{Sim?}
{173}{}{Estás bem? Você conseguiu que "eu estou puxando rank" olhe novamente.}
{174}{}{Queria fazer algumas perguntas ...}
{175}{}{Parece que você tirou algum dano. Use alguns stims e cure-se.}
{176}{}{Cassidy, eu preciso que você espere até eu voltar.}
{177}{}{Coloque sua arma longe.}
{178}{}{Fica perto de mim.}
{179}{}{Não fique muito longe.}
{180}{}{Devemos nos espalhar um pouco.}
{181}{}{Vamos, Cassidy. Tempo para sair.}
{182}{}{Nada, esquece.}

{261}{}{Você quer que eu coloque uma bala na cabeça de Myron, é isso? Não haveria problemas. Apenas dê a palavra.}
{262}{}{O que está em sua mente?}
{263}{}{Por que você quer usar o Myron?}
{264}{}{Com quais armas você é especialista?}
{265}{}{Na verdade, eu tinha outra coisa que queria que você fizesse ...}
{266}{}{Na verdade, eu tinha algo que queria que você fizesse ...}
{267}{}{Deixa pra lá. Vamos continuar.}
{268}{}{Não, não machuque Myron. Hoje em dia não hoje. Vou mantê-lo informado.}
{269}{}{Bem, espingardas e rifles, principalmente ... apenas preferência pessoal. Eu também não sou um tiro ruim com pistolas.}
{270}{}{Algo mais?}
{271}{}{OK. Tive algumas outras questões ...}
{272}{}{Tudo certo. Apenas checando.}
{273}{}{Se você precisar aprender algumas maneiras de forma íntima e pessoal, deslize-me algumas juntas de bronze, e eu posso tapdance no rosto com os meus punhos.}
{274}{}{Great. Algo mais?}
{275}{}{OK. Tive algumas outras questões ...}
{276}{}{Tudo certo. Apenas checando.}
{277}{}{Uh, bem ... apenas entre você e eu, eu também posso usar uma lança muito boa. Eu e meus amigos costumávamos caçar radscorpions com lanças de volta quando ... fato eu estou vivo e eles não podem dizer uma coisa.}
{278}{}{Nada de errado em usar uma lança.}
{279}{}{OK. Tive algumas outras questões ...}
{280}{}{Tudo certo. Apenas checando.}
{281}{}{Diz você. Apenas não me chame de tribal, e nos daremos bem.}
{282}{}{Não quero que as pessoas me confundam com o nariz de osso lá. Heh heh. Nunca fui visto nenhum tribal fazer algo tão burro como amarrar um osso no nariz.}
{283}{}{Claro que não existe. A lança é uma arma fina. Muitos amigos tribais os utilizam.}
{284}{}{Você sabia que eu sou um "tribal"?}
{285}{}{Hmmm. Olha, eu tive algumas outras perguntas ...}
{286}{}{Tudo certo. Obrigado pelo rescaldo.}
{287}{}{Ah, não esteja brincando com ol 'Cassidy agora. Você não é tribal.}
{288}{}{Sim eu estou.}
{289}{}{Tanto faz. Olha, eu tive algumas outras perguntas ...}
{290}{}{Esqueça. Eu não quero entrar nisso com você agora mesmo.}
{291}{}{Bem, tudo bem, você pode ter minhas desculpas aqui e agora. Eu não quis dizer nenhuma ofensa.}
{292}{}{Claro que você não. Olha, eu tive algumas outras perguntas ...}
{293}{}{Esqueça. Vamos continuar.}
{294}{}{Bem, agora, antes de ir, recebi uma pergunta para você. O que estamos fazendo aqui fora? Parece que estamos correndo por todo o lado procurando algo. Temos algum tipo de plano?}
{295}{}{Estamos à procura de um GECK - um Kit de Criação do Jardim do Éden. Minha aldeia precisa restaurar suas colheitas.}
{296}{}{Nós vamos para o Vault, depois devolvemos o GECK à minha aldeia.}
{297}{}{Minha aldeia foi sequestrada. Estou tentando descobrir o que aconteceu com eles.}
{298}{}{As coisas vêm em kits agora, hein? Cara, o bom livro não menciona isso, não é? Bem, tudo bem então. Vamos caçar.}
{299}{}{Hã. Tudo bem então, apenas checando.}
{300}{}{Eu não me importaria de tapar alguns buracos em alguns sequestradores. Uma pequena fronteira justiça nunca machucou ninguém ... bem, pelo menos não eu.}
{301}{}{Tudo certo. Vamos.}
{302}{}{As coisas que o pequeno cuss diz não são adequadas para ouvidos decentes.}
{303}{}{Especialmente de uma mulher.}
{304}{}{Por quê, Cassidy, eu não sabia que você se importava. O meu coração está todo a flutter.}
{305}{}{Assim? O que você está dizendo?}
{306}{}{Você sabe, tambem custam muito, Cassidy.}
{307}{}{Conte-me sobre isso. Vamos indo.}
{308}{}{Sim, mas quando eu faço isso, tem estilo. Ele é apenas uma pequena boca do lixo.}
{309}{}{E eu não gosto da maneira como ele olha você, também.}
{310}{}{Por quê, Cassidy, eu não sabia que você se importava. O meu coração está todo a flutter.}
{311}{}{Assim? O que você está dizendo?}
{312}{}{Conte-me sobre isso. Vamos indo.}
{313}{}{Agora aguarde, eu não quis dizer isso assim.}
{314}{}{Tudo o que estou dizendo é que o pequeno idiota de boa-fé vai fazer com que seu número seja marcado um dia quando é só eu e ele e um buraco no deserto.}
{315}{}{Bem, a vida pode ser uma professora áspera por conta própria. Eu tive algumas outras perguntas para você ...}
{316}{}{Bem, ele é obrigado a mordê-lo a qualquer momento agora mesmo. Eu não me importaria com isso.}
{317}{}{Apenas acalme-se, Cassidy. Deixe Myron sozinho.}
{318}{}{Eu odeio este lugar.}
{319}{}{Eu estava esperando que nos afugentássemos deste lugar para sempre.}
{320}{}{Cidade dos índices ...}
{321}{}{Este lugar parece pior do que o Vault City.}
{322}{}{Bom, eu verifiquei minhas armas antes de entrar aqui.}
{323}{}{Se eu chutar a balde, não me enterre aqui.}
{324}{}{Fique atento por aqui. Os habitantes locais não são muito amigáveis.}
{325}{}{Heh. Nunca pensei em ver San Francisco.}
{326}{}{Nunca pensei que você faria um temporizador antigo como eu por muito tempo. Vamos fazer esse trabalho e ir para casa.}
{327}{}{Redding é uma cidade mineira. Ouro, principalmente. Muitas caravanas chegaram a Vault City a partir daqui.}
{328}{}{Broken Hills é uma cidade mineira ... principalmente minério de urânio. Pode ser um lugar difícil, então fique atento.}
{329}{}{Eu consegui algum veneno correndo pelo meu sistema. Tem algum antídoto?}
{330}{}{Estou brilhando como um sinal de néon por aqui. Tem chems anti-radiação?}
{331}{}{Estou sofrendo muito ruim por aqui. Tem alguma vítima?}
{332}{}{Você mantém seu nariz limpo, Myron. Estou te observando.}
{333}{}{Saia da linha, Myron, e eu vou te cortar.}
{334}{}{Droga, Lenny, você precisa de um banho. Ou algum desinfetante.}
{335}{}{Ghoul-boy, é melhor você manter sua dificil distância. Shoooo-weee, você fede.}
{336}{}{Esse é o cachorro mais malvado que já vi.}
{337}{}{Fácil, cachorrinho. Cassidy é seu amigo, tudo bem?}
{338}{}{Pergunte-se o que o cyberdog come. Humanos, provavelmente.}
{339}{}{Se esse cyberdog começar a jorrar minha perna, eu vou detê-lo.}
{340}{}{Ahhhh. Boy, fico feliz por ter feito milhões dessas coisas antes que a bomba caiu.}
{341}{}{Obrigado, amigo.}
{342}{}{Espero que essas vítimas não prejudiquem meu coração ...}
{343}{}{O que ... ?! Não, meu coração! Eu ... * hrrrkkk *}
{344}{}{Desculpe, eu estava apenas admirando a visão.}
{345}{}{Inferno, vou ficar de pé aqui, então.}
{346}{}{Minhas desculpas, amigo. Não queria bloquear o seu caminho.}
{347}{}{Ahhhhh. Isso atingiu o local. Obrigado gentilmente.}
{348}{}{* Hic * Heh-heh. Nada como uma boa água de fogo para obter o bombeamento de sangue.}
{349}{}{Obrigado. Inferno, você também deveria pegar um gole.}
{350}{}{Esse é o Vault. Grande coisa de friggin, ai?}
{351}{}{Você quer que eu se junte a você novamente?}
{352}{}{Eu sou bom ir sempre que estiver.}
{353}{}{Claro, você não precisa da minha ajuda?}
{354}{}{Estou comendo para começar.}
{355}{}{Claro que poderia fumar.}
{356}{}{Papai me chamou depois de um personagem de quadrinhos antes da guerra. Disse que ele era um malvado sonuvabitch também.}
{357}{}{É bom viajar de novo. Viver em Vault City estava me dando uma úlcera.}
{358}{}{Espero que meu coração não aja enquanto estamos viajando ...}
{359}{}{Claro que poderia usar uma bebida.}
{360}{}{Melhor verificar minha engrenagem novamente.}
{361}{}{Maldita artrite ...}
{362}{}{Se eu fosse vinte anos mais novo, eu iria para o leste e exploraria o Centro-Oeste. Muito tarde agora, suponho.}
{363}{}{Eu ouvi dizer que eles chegaram a uma distância de 120 quilômetros de largura no Centro-Oeste. É uma grande poeira de água radioativa agora.}
{364}{}{Pergunto se o Texas sobreviveu à guerra ...}
{365}{}{Obrigado, amigo. I...whoa. Now my vision's getting all cloudy.}
{366}{}{Ouvi isso, faz você alucina ... whoa! De onde diabos todas essas cobras vêm ?!}
{367}{}{Sempre que tomo essas coisas, tenho flashbacks.}
{368}{}{Nada como um pouco de cura tribal ...}
{369}{}{Estou prestes a ter algumas muletas e uma cadeira de rodas aqui.}
{370}{}{Cassidy morre de um ataque cardíaco.}
{371}{}{Você convenceu Cassidy a participar da sua festa.}

{1000}{}{Bem ... tudo bem, então. Espero até você voltar.}
{1100}{}{Certo. Não posso prometer que não vou retirá-lo novamente se houver problemas.}
{1200}{}{Tudo bem, vou ficar perto de você então. Você deve estar esperando problemas.}
{1300}{}{Tudo bem, vou manter distância. Obtenha um melhor ponto de vista dessa maneira.}
{1400}{}{Tudo bem, eu estarei observando suas costas. Você precisa de mim, grita e eu vou correr.}

{2000}{}{Não há ofensa nem nada, mas você não parece muito capaz de liderar ninguém. Parece que os resíduos o teriam para o jantar.}
{2100}{}{Naw, eu não viajo com escravas. Eles têm um hábito desagradável de vender você quando eles ganham pouco dinheiro. Sem ofensa.}
{2200}{}{Naw, você tem a aparência de alguém com um pé no túmulo e outro no inferno. Eu não acho que eu preciso manchar minha reputação mais do que é.}
{2300}{}{Naw ... você parece que já tem bastante de uma multidão.}
{2400}{}{Tudo bem então.}

{2999}{}{Tudo certo. Tome cuidado, então.}
{3000}{}{Vamos sair.}
{3100}{}{Esqueça que eu perguntei então, idiota.}
{3200}{}{Deixa pra lá então. Sua perda.}

{4100}{}{Ok, tudo está costurado. Eu sou bom para ir.}
{4200}{}{Ok, praticamente tudo está remendado.}
{4300}{}{Isso praticamente aconteceu, mas eu poderia usar um par de stims mais.}
{4400}{}{Usei o que pude, mas ainda estou bastante desarrumado. Se você tiver mais alguma súvida, eu poderia usá-los. Ainda posso andar.}

{9999}{}{Queria fazer algumas perguntas ...}
{10001}{}{Pegue um pouco mais e se cure.}
{10002}{}{Cassidy, eu preciso que você espere até eu voltar.}
{10003}{}{Coloque sua arma longe.}
{10004}{}{Fica perto de mim.}
{10005}{}{Não fique muito longe.}
{10006}{}{Devemos nos espalhar um pouco.}
{10100}{}{Vamos, Cassidy. Tempo para sair.}
{10007}{}{Vamos então.}

# NEW TOM PARTY MEMBER ADDITIONS

# NODE 1007 WE NEED TO CHANGE DISTANCE
{20000}{}{Tudo bem, eu estou ouvindo.}

# NODE 1008 TALK ABOUT GEAR
{20001}{}{Meu equipamento? E quanto a isso?}

# NODE 1009 REMOVE ARMOR
{20002}{}{Sem problemas. Muito quente para esse tipo de engrenagem, de qualquer maneira. Me faz suar como uma nova prostituta de Reno.}

# NODE 1010 WHAT WEAPONS CAN YOU USE -- DAN NEEDS TO REPLACE THIS.

# NODE 1100 CAN'T JOIN PARTY BECAUSE LOW CHR -- DAN NEEDS TO REPLACE THIS.

# We need to change our distance from one another
{20003}{}{Vamos tentar uma formação diferente.}
# Eu preciso falar com você sobre sua equipe.
{20004}{}{Eu preciso falar com você sobre sua equipe.}
# On second thought, I think this distance is OK for now.
{20005}{}{Esqueça. Vamos manter a formação que temos agora.}
# Actually, I guess there's nothing I need to really know right about your gear.
{20006}{}{Deixa pra lá. Não há nada que eu preciso saber sobre o seu equipamento.}
# I need to remove the armor that you're wearing.
{20007}{}{Preciso que você remova essa armadura que você está vestindo.}
# I need to know what kind of weapons you can use. Transplant original comment from Question Node Line: 264
