{100}{}{Você vê Charlie.}
{101}{}{Você vê um homem magro. Seu cabelo é rebocado em sua cabeça em grumos irregulares, e sua pele está pendurada vagamente em seu corpo.}
{102}{}{Você vê Charlie.}
{103}{}{Você vê um homem magro. Seu cabelo é rebocado em sua cabeça em grumos irregulares, e sua pele está pendurada vagamente em seu corpo.}
{104}{}{Você vê um homem magro ... parece que ele tem sintomas de envenenamento por radiação.}
{105}{}{Você vê Charlie.}
{106}{}{Você vê um homem magro ... parece que ele tem sintomas de envenenamento por radiação.}
{107}{}{Você vê Charlie... he looks like he has put on weight, and is breathing normally.}
{108}{}{Você vê Charlie.}
{109}{}{Você vê Charlie...he looks like he has put on weight, and is breathing normally.}
{110}{}{Este homem tem envenenamento por radiação. Suas habilidades não podem ajudá-lo. Ele precisa de medicação.}
{111}{}{Este homem parece terrivelmente doente. Você não tem certeza do que está errado.}
{112}{}{Obrigado, mas estou bem, na verdade. Essa coisa de Rad-Away fez o truque.}
{113}{}{Você encontra uma veia e injetou o Radaway no sistema de Charlie.}
{114}{}{* Urhkkkk * ...}
{115}{}{3 segundos}
{116}{}{Unhhhhh ... * tosse * * tosse * ...}
{117}{}{3 segundos}
{118}{}{Hrnnhhhh ... eh ... ahhhhh}
{119}{}{3 segundos}
{120}{}{O que aconteceu? Eu sinto toneladas melhor.}
{121}{}{Você curou Charlie.}
{122}{}{* Errhhhhhh *}
{123}{}{* Wheeze *}
{124}{}{*COF cof*}
{125}{}{* Urhkkkk *}
{126}{}{A última vez que eu bebo a água maldita nesta cidade, isso é seguro.}
{127}{}{Surpreso, eu ainda não estou brilhando ...}
{128}{}{Damn Rad-Away me dá as corridas ...}
{129}{}{Obrigado, estranho. Eu aprecio sua ajuda ... Eu não poderia pagar o Autodoc.}
{130}{}{Desejo que eu possa recompensá-lo, mas nem sequer tenho duas tampas para esfregar juntos.}
{131}{}{A última vez que eu bebo a água maldita nesta cidade, isso é seguro.}
{132}{}{Surpreso, eu ainda não estou brilhando ...}
{133}{}{Damn Rad-Away me dá as corridas ...}
