{100}{}{Você vê o Chefe de Alocações Ilícitas, Chet.}
{101}{}{Você vê um homem de aparência deslumbrante que usa um macacão Vault 13.}
{102}{}{Você vê o Chefe de Alocações Ilícitas, Chet.}
{103}{}{Você vê um homem de aparência deslumbrante que usa um macacão Vault 13.}
{104}{}{Olá. Eu sou o Chefe de Alocações Ilícitas ... mas você pode me chamar de Chet. Você precisa de algo?}
{105}{}{Precisa de mais alguma coisa?}
{106}{}{Defina a bandeira final, Chet. Estou tudo pronto.}
{107}{}{Faça-me Capitão da Guarda. Agora.}
{108}{}{Faça-me um cidadão real, se você quiser.}
{109}{}{Faça-me um cidadão falso e me dê os papéis.}
{110}{}{Faça-me um cidadão expulso.}
{111}{}{Mude minha reputação.}
{112}{}{(Não funciona) Preciso de um personagem no meu grupo.}
{113}{}{Não, nada.}
{114}{}{Para quê?}
{115}{}{Faça-me um escravo.}
{116}{}{Faça-me um criador de filhos.}
{117}{}{Nada ... basta diminuir o meu carma por um 100.}
{118}{}{Deixa pra lá. Eu queria algo mais ...}
{119}{}{Não, nada.}
{120}{}{Quem?}
{121}{}{Marcus.}
{122}{}{Lenny.}
{123}{}{Vic.}
{124}{}{Myron.}
{125}{}{Ninguém. Eu tenho mais necessidades.}
{126}{}{Deixa pra lá. Tchau.}
