{100}{}{Você vê um barman.}
{101}{}{Você vê um homem alto em um terno elegante. Ele está olhando para a frente e não presta atenção aos clientes ao seu redor.}
{102}{}{Você vê um barman.}
{103}{}{Este homem parece com uma pedra. Se ele perceber, ele não mostra nenhum sinal.}
{104}{}{Cuide de uma bebida, herói?}
{105}{}{Bem-vindo, herói. Por favor, sente-se no bar.}
{106}{}{Por favor! Sente-se, descanse por um tempo!}
{107}{}{Bom dia, capitão.}
{108}{}{Vault City prevalece, capitão.}
{109}{}{Bom dia, cidadão.}
{110}{}{Vault City prevalece, Citizen.}
{111}{}{Um mutante! Guardas! Guardas!}
{112}{}{Um ghoul! Guardas! Guardas!}
{113}{}{Me desculpe, mas o bar está fechado para a noite.}
{114}{}{A barra está fechada. Volto para casa uma vez que eu termine esta lista de inventário.}
{115}{}{Você não tem casas para ir?}
{116}{}{Bem vinda! Todos nós ouvimos sobre suas façanhas contra o Enclave. Posso pegar algo para beber?}
{117}{}{Awnt-awnt}
{118}{}{Shamble off}
{119}{}{O que há na torneira?}
{120}{}{Eu estava procurando alguma informação.}
{121}{}{Nada hoje, obrigado.}
{122}{}{Heh-heh, "awnt-awnt" para você, também. Tenha cuidado nos resíduos.}
{123}{}{Oonnt-oooont!}
{124}{}{Shamble off}
{125}{}{O que posso fazer por você, capitão?}
{126}{}{O que posso fazer por você, cidadão?}
{127}{}{Sim? Posso ajudar?}
{128}{}{Awnt-awnt}
{129}{}{Shamble off}
{130}{}{O que há na torneira?}
{131}{}{Eu estava procurando alguma informação.}
{132}{}{Nada hoje, obrigado.}
{133}{}{Sim, "awnt-awnt" para você, também. Segure um momento enquanto eu convoco os guardas para "tear-tear" você para o portão da frente.}
{134}{}{Urnt? Urnt-urnt.}
{135}{}{Shamble off}
{136}{}{"Na torneira?" Como ... pitoresco.}
{137}{}{Nós temos água mineral, água destilada e água com gás. Também temos vários álcoois sintetizados.}
{138}{}{Um ... que álcoois sintetizados você tem?}
{139}{}{Uh, você tem alguma bebida real?}
{140}{}{Alguma água seria excelente.}
{141}{}{Never mind. Eu estava procurando alguma informação.}
{142}{}{Nada hoje, obrigado.}
{143}{}{Muito bom, senhor.}
{144}{}{Muito bem, senhora.}
{145}{}{Qual você gostaria? Mineral? Destilado? Ou Espumante? Cada um tem preços moderados em cinco dólares por copo.}
{146}{}{Mineral, por favor.}
{147}{}{Vou tentar uma dessas águas destiladas.}
{148}{}{Coloque-me com alguma daquela água com gás.}
{149}{}{Que álcoois sintetizados você tem?}
{150}{}{Never mind. Eu estava procurando alguma informação.}
{151}{}{Isso é um pouco íngreme para mim. Voltarei quando tiver mais dinheiro.}
{152}{}{Acho que vou passar, obrigado.}
{153}{}{Temos derivados sintéticos H e T, e recentemente fabricamos uma mistura extremamente popular, "Alcohol-Z", que possui um rico sabor pseudo micro-cervejaria. Cada um tem preços moderados em vinte dólares por copo.}
{154}{}{Como você fabrica esses álcoois sintetizados?}
{155}{}{Uh, você tem alguma bebida real?}
{156}{}{Apenas vou tomar água, penso.}
{157}{}{Hmmm. Vou tentar um pouco de álcool delicioso.}
{158}{}{Nevermind. Eu estava procurando alguma informação.}
{159}{}{Isso é um pouco íngreme. Voltarei quando tiver mais dinheiro.}
{160}{}{Nada hoje, obrigado.}
{161}{}{Você gostaria de mais alguma coisa?}
{162}{}{Gostaria de mais um pouco de água, obrigado.}
{163}{}{Que álcoois sintetizados você tem?}
{164}{}{Never mind. Eu estava procurando alguma informação.}
{165}{}{Nada hoje, obrigado.}
{166}{}{Você está bem, senhor? Beber tudo o que "álcool-Z" parece ter tido algum tipo de efeito sobre você. Tem certeza de que quer mais?}
{167}{}{Você está bem, senhor? Beber tudo o que "álcool-Z" parece ter tido algum tipo de efeito sobre você. Tem certeza de que quer mais?}
{168}{}{Você gostaria de mais alguma coisa?}
{169}{}{Eu não me sinto tão bem ... Eu vou sair do diálogo por um segundo e verificar meus melhores pontos de vida.}
{170}{}{Não, não, eu me sinto ótimo! Eu só vou sair do diálogo por um segundo e verificar os meus melhores pontos de vida.}
{171}{}{Apenas vou tomar água, penso.}
{172}{}{Vou ter mais álcool-Z mais delicioso.}
{173}{}{Como você fabrica esses álcoois sintetizados?}
{174}{}{Actually, Eu estava procurando alguma informação.}
{175}{}{Nada mais hoje, obrigado.}
{176}{}{O Auto-Docs dentro da Vault City pode preparar substitutos sintéticos para substâncias que formam hábitos. Como eu entendi, esses sintéticos foram usados   como placebos para quimiantes antes da guerra.}
{177}{}{Você parece saber muito sobre esses sintéticos.}
{178}{}{Uh, você tem alguma bebida real?}
{179}{}{Oh. Bem, eu gostaria apenas de uma água então.}
{180}{}{Hmmm. Vou tentar um pouco desse álcool-Z.}
{181}{}{Interesting. Say, Eu estava procurando alguma informação...}
{182}{}{Entendo. Obrigado pela informação. Adeus.}
{183}{}{Eu era um servo do Dr. Troy por alguns meses antes de ser reatribuído aqui. Ele exigiu que eu fosse fluente com o banco de dados médico da Vault City.}
{184}{}{"Fluente?" Ele pode legalmente pedir que você faça isso com um computador?}
{185}{}{Banco de dados médico?}
{186}{}{Interesting. Say, Eu estava procurando alguma informação...}
{187}{}{Entendo. Obrigado pela informação. Adeus.}
{188}{}{Uh ... "fluente" significa proficiente, habilidoso, bem aprendido.}
{189}{}{Hã. Bem, se isso faz com que você se sinta melhor para colocar assim, bem. O que se tratava de um banco de dados médico?}
{190}{}{Eu estava procurando por alguma outra informação ...}
{191}{}{Se a negação o faz sentir melhor, eu entendo. Eu falarei com você mais tarde.}
{192}{}{Sim, vários dos computadores no primeiro andar do Vault contêm uma vasta gama de informações médicas. É tudo bastante fascinante, embora o jargão possa ser confuso se você não tiver treinamento médico.}
{193}{}{Jargão? Ele é o responsável pelos computadores?}
{194}{}{Interesting. Say, Eu estava procurando alguma informação...}
{195}{}{Hmmmm. Talvez eu vá verificá-los, então.}
{196}{}{Uh, não. "Jargão" refere-se a linguagem, terminologia, geralmente relacionada a uma determinada profissão.}
{197}{}{Uh, sure it does, sure it does. Just testing you. Say, Eu estava procurando alguma informação...}
{198}{}{Se você diz. Apenas deixe este jargão saber que eu vou falar com ele, está bem? Adeus.}
{199}{}{Se você quer dizer o que passa pelo álcool nos resíduos, então não.}
{200}{}{Nunca sentimos a necessidade de envenenar nossos sistemas com essas misturas de bactérias. A barra no pátio pode ser menos ... discriminatória.}
{201}{}{Eu só vou tomar água, então.}
{202}{}{Espere um minuto. O que 'bebidas sintetizadas' você tem?}
{203}{}{Eu estava procurando alguma informação.}
{204}{}{Eu vou verificá-lo então, obrigado.}
{205}{}{Talvez eu vá para outro lugar, então.}
{206}{}{Então talvez você deva estar em nosso centro de informações em vez de este estabelecimento. Está localizado no centro da cidade. Agora, mude ... Tenho outros clientes.}
{207}{}{Aguarde, eu queria uma bebida. O que você tem na torneira?}
{208}{}{Não, acho que você vai me dizer o que eu quero saber primeiro. E você deixará essa atitude fora de sua voz, também se você souber o que é bom para você.}
{209}{}{Tudo bem então. Dia bom.}
{210}{}{Claro. O que você precisava saber, senhor?}
{211}{}{Claro. O que você precisava saber, senhora?}
{212}{}{Claro. O que você precisava saber, capitão?}
{213}{}{Claro. O que você precisava saber, Citizen?}
{214}{}{Você pode me dizer quem é o líder da Vault City?}
{215}{}{Você pode me contar um pouco sobre a escravidão aqui em Vault City?}
{216}{}{Deixa pra lá. Eu queria uma bebida. O que você tem na torneira?}
{217}{}{Nada hoje, obrigado.}
{218}{}{Por que, primeiro cidadão Lynette, é claro. Ela tem sido First Citizen por quase dois termos agora. Ela ainda é responsável pelo conselho, mas é responsável pela maior parte da legislação básica da cidade de Vault.}
{219}{}{Conselho?}
{220}{}{Você pode me contar um pouco sobre a escravidão aqui em Vault City?}
{221}{}{Deixa pra lá. Eu queria uma bebida. O que você tem na torneira?}
{222}{}{Interessante. Obrigado pela informação. Adeus.}
{223}{}{Sim, também há um conselho da Vault City. Seu porta-voz é o conselheiro sênior McClure. (Leans in.) McClure e o First Citizen têm muitas cabeças várias vezes, na verdade.}
{224}{}{Mesmo...?}
{225}{}{Você pode me contar um pouco sobre a escravidão aqui em Vault City?}
{226}{}{Deixa pra lá. Eu queria uma bebida. O que você tem na torneira?}
{227}{}{Interessante. Obrigado pela informação. Adeus.}
{228}{}{Ai sim. Recentemente, alguns cidadãos pediram a McClure e ao conselho para anular algumas das decisões do primeiro cidadão. Isso criou bastante agitação, deixe-me dizer-lhe.}
{229}{}{Hmmm. Eu estava curioso sobre outra coisa ...}
{230}{}{Entendo. Bem, eu poderia usar uma bebida. O que você tem na torneira?}
{231}{}{Interessante. Obrigado pela informação. Adeus.}
{232}{}{Oh, não, não ... não é escravidão. As pessoas que você vê trabalhando na cidade são criadas ... eu mesmo incluído. Nós somos tratados muito bem aqui, ensinamos a ler e escrever, e nos cuidados médicos, casas e alimentos.}
{233}{}{Tudo menos sua liberdade, hein?}
{234}{}{Se você não tiver queixas, então não é problema. Esqueça que eu perguntei.}
{235}{}{Deixa pra lá. Eu queria uma bebida. O que você tem na torneira?}
{236}{}{Entendo. Bem, obrigado por falar comigo. Adeus.}
{237}{}{Se você não vai pedir uma bebida, talvez seja melhor sair, senhora.}
{238}{}{Se você não vai pedir uma bebida, talvez seja melhor sair, senhor.}
{239}{}{Se você não tem queixas sobre sua ... servidão, então não é problema. Esqueça que eu perguntei.}
{240}{}{Vou tomar uma bebida, então. O que você tem na torneira?}
{241}{}{Talvez eu seja melhor. Dia bom.}
{242}{}{Eu devo. Agora, existe algo com o que posso ajudá-lo?}
{243}{}{Vou tomar uma bebida, então. O que você tem na torneira?}
{244}{}{Não hoje, na verdade. Dia bom.}
{245}{}{Zzzzzz.}
