{100}{}{Você vê um homem sujo mas forte.}
{101}{}{Você vê Connar.}
{102}{}{Ei você! O que você está fazendo!}
{103}{}{Fique onde está por agora, vagabundo. O que você está fazendo aqui?}
{104}{}{Estou matando os monstros aqui.}
{105}{}{Por que, o que é isso para você?}
{106}{}{Por que você grita!}
{107}{}{Aposto que os bastardos da Vault City lhe enviaram. Bem, você está bem, e deixe tudo o resto
 vivo.}
{108}{}{Bem, está um pouco atrasado para isso.}
{109}{}{Por quê?}
{110}{}{Desculpe, tenho um trabalho a fazer.}
{111}{}{Essas criaturas são a única coisa que está impedindo o Vault City de nos fazer o chamado
 funcionários.}
{112}{}{Bem, eles estão me pagando para me livrar dos monstros, e é isso que eu vou fazer.}
{113}{}{Eles não me disseram isso.}
{114}{}{Eles estão me pagando para se livrar deles, e o trabalho está pronto.}
{115}{}{Seu idiota! Por que diabos você fez isso!}
{116}{}{Eu precisava do dinheiro.}
{117}{}{Eles virão para nós se você fizer isso, você sabe.}
{118}{}{Não é problema meu.}
{119}{}{Bem, espero que você se afaste. Eles estarão aqui para nós em breve.}
{120}{}{Eu não sabia que era por isso que eles queriam o trabalho feito.}
{121}{}{Sim, bem, eu não ligo com lixo como você de qualquer maneira.}
{122}{}{Bem, não podemos deixar você fazer isso.}
{123}{}{Você tem que fazer o que você tem que fazer.}
{124}{}{Você acreditou no valor nominal? Você tem muito a aprender sobre o mundo, amigo.}
{125}{}{Existe alguma coisa que eu possa fazer para ajudar?}
{126}{}{Os meninos da City do Vault não são os mais valentes. Você mostra-lhes qualquer tipo de luta e eles correm para a
 Colinas. Se tivéssemos algumas armas, acho que poderíamos detê-las.}
{127}{}{Que tipo de armas?}
{128}{}{Bem, eu estou bem com uma espingarda, e nós temos algumas pessoas aqui que podem lidar com um rifle. eu acho que
 Três deles fariam.}
{129}{}{Verei o que posso fazer.}
{130}{}{Você não é procurado aqui. Saia agora.}
{131}{}{Eu mudei de ideia. O que posso fazer para ajudar?}
{132}{}{Sim, bem, você não vai estar aqui por muito tempo, de qualquer maneira.}
{133}{}{Como eu me importo.}
{134}{}{Você voltou! Você tem armas para nós?}
{135}{}{O que você precisava de novo?}
{136}{}{Sim, aqui estão eles.}
{137}{}{Precisamos de três rifles e uma espingarda. Quanto mais cedo você pode obtê-los para nós, melhor.}
{138}{}{OK.}
{139}{}{Com estes, poderemos fazer algo deste lugar nos próximos meses. Se você precisar
 Um lugar para descansar, você sempre será bem-vindo aqui.}
{140}{}{Seja bem-vindo.}
{141}{}{Bem vindo de volta. As coisas estão indo bem. Vamos trabalhar na expansão do Village.}
{142}{}{Olá de novo! As coisas estão indo bem, como você pode ver. Olhe em volta se você tiver o tempo.}
{143}{}{Ainda estamos construindo. Esperamos expandir as paredes novamente no próximo mês.}
{144}{}{Saudações! A vila expandiu-se novamente como esperávamos. Você sempre como sempre.}
{145}{}{Não temos nada a temer da cidade de Vault por mais tempo, e poderemos morar aqui em paz.
 Obrigado novamente, vagabundo.}
{146}{}{Apenas não mate nada lá fora, você simplifica.}
