{100}{}{Você vê Curtis.}
{101}{}{Você vê um pequeno menino de cabelos castanhos. Parece que ele está chorando.}
{102}{}{Você vê Curtis.}
{103}{}{Você vê um pequeno menino de cabelos castanhos. Parece que ele está chorando.}
{104}{}{Você vê um pequeno menino de cabelos castanhos. Ele parece muito mais feliz do que antes.}
{105}{}{Você vê Curtis.}
{106}{}{Você vê um pequeno menino de cabelos castanhos. Ele parece muito mais feliz do que antes.}
{107}{}{* Snfffff *}
{108}{}{Gostaria de um pouco de chá, Sr. Nixon?}
{109}{}{"Por que sim eu faria, Curtis".}
{110}{}{Aqui está. Beber!}
{111}{}{"Obrigado, Curtis".}
{112}{}{Obrigado, Sr. Nixon.}
{113}{}{"Você quer escavar a chave inglesa do papai?"}
{114}{}{Não, Sr. Nixon. Papai ficará louco, nós enterramos isso.}
{115}{}{"Mas está enterrado sob aquelas rochas logo atrás do bar. Podemos obtê-lo agora".}
{116}{}{Não, papai ficará louco. É melhor mentir, assim como você me disse, Sr. Nixon.}
{117}{}{Perdi meu amigo enquanto jogava no pátio. O nome dele é o Sr. Nixon.}
{118}{}{O Sr. Nixon tem uma camisa azul e um grande nariz. Ele é realmente, muito curto.}
{119}{}{Você viu o Sr. Nixon? Eu perdi ele.}
{120}{}{Obrigado por encontrar o Sr. Nixon. Ele também diz obrigado.}
{121}{}{Yer mutante é assustador.}
{122}{}{Yer ghoul é assustador.}
{123}{}{Yer cachorrinho de metal parece que ele quer me comer.}
{124}{}{Perdi o Sr. Nixon. Não sei onde o deixei.}
{125}{}{Thizzz Nixxson?}
{126}{}{Shamble off}
{127}{}{Este ele? Ele também estava olhando para você.}
{128}{}{Eu tenho o Sr. Nixon aqui. Mas você sabe o que? Eu acho que o Sr. Nixon deveria ser punido por sair sozinho. Algum desmembramento ritual pode estar em ordem. Então, primeiro eu vou tirar os braços, então ...}
{129}{}{Nem eu.}
{130}{}{Você o encontrou! Você encontrou o Sr. Nixon!}
{131}{}{Byeee Mistuh Nixxson}
{132}{}{Claro que sim. Ele não foi longe. Agora fique de olho nele a partir de agora, ok?}
{133}{}{NÃO! NAO! Não! Pare com isso! Sto--}
{134}{}{Ooops. Parece que Nixon era um pouco mais frágil do que eu pensava. Muito ruim, criança.}
{135}{}{O Sr. Nixon vai voltar do túmulo e matá-lo.}
{136}{}{O Sr. Nixon irá assombrá-lo pelo resto dos seus dias. Quero dizer.}
{137}{}{Quando crescer, você será velho, e farei com você o que fez com o Sr. Nixon.}
{138}{}{Você devolveu o Sr. Nixon a Curtis.}
{139}{}{Você ensinou a Curtis que a vida é cruel e injusta.}
