{100}{}{Você vê Lydia.}
{101}{}{Você vê uma mulher de cabelos castanhos vestida de fadiga marrom e armadura de metal. Parece o barman.}
{102}{}{Você vê Lydia.}
{103}{}{Você vê uma mulher de cabelos castanhos vestida de fadiga marrom e armadura de metal. Parece o barman.}
{104}{}{Bem vinda! Cuide de uma bebida, Escolhido?}
{105}{}{Bem-vindo, Escolhido! Por favor, sente-se no bar.}
{106}{}{Por favor! Sente-se, descanse por um tempo!}
{107}{}{É o Escolhido! Todo mundo desistir do HERO de Fallout 2!}
{108}{}{Bom dia, capitão.}
{109}{}{Vault City prevalece, capitão.}
{110}{}{Bom dia, cidadão.}
{111}{}{Vault City prevalece, Citizen.}
{112}{}{Um mutante! Guardas! Guardas!}
{113}{}{Um ghoul! Guardas! Guardas!}
{114}{}{Estamos fechados. Volte pela manhã.}
{115}{}{Desculpe, a última ligação foi há algum tempo. Volte pela manhã.}
{116}{}{Estamos fechados. Uma vez que eu termine de fazer essa lista de nossas ações, eu vou fechar.}
{117}{}{Ei, Escolhido! Nós estávamos apenas falando sobre sua aventura ... posso te fazer beber alguma coisa?}
{118}{}{Dwinkie-winkie me faz stinkie}
{119}{}{Shamble off}
{120}{}{O que há na torneira?}
{121}{}{Eu estava procurando alguma informação.}
{122}{}{Eu tenho esse envio de álcool que você queria.}
{123}{}{Nada hoje, obrigado.}
{124}{}{Uh ... então eu cheiro. Um, obrigado novamente por salvar o mundo e tudo mais.}
{125}{}{Stinkie-blinkie me faz twinkie!}
{126}{}{Shamble off}
{127}{}{Olha, talvez você tenha salvado o mundo e tudo, mas um poeta, você não é. Agora corte isso.}
{128}{}{Flinkie-flinkie klinkie-klinkie!}
{129}{}{Shamble off}
{130}{}{Olhe, pegue isso e saia daqui, ok? Eles devem manter sua boca ocupada por um tempo.}
{131}{}{Thankie wankie my stankie}
{132}{}{Shamble off}
{133}{}{Uh ... o que posso fazer por você, capitão?}
{134}{}{O que posso fazer por você, cidadão?}
{135}{}{Sim? Posso ajudar?}
{136}{}{Você? Yoo? Teixo? Yewwwww. E-yewwww é som que outro faz quando me veja}
{137}{}{Shamble off}
{138}{}{O que há na torneira?}
{139}{}{Eu estava procurando alguma informação.}
{140}{}{Eu tenho esse envio de álcool que você queria.}
{141}{}{Nada hoje, obrigado.}
{142}{}{Essa é talvez a coisa mais fascinante que já ouvi. Segure um segundo ... Eu quero que os guardas também o ouviram.}
{143}{}{Também? Tew. Tewwwww. Tewwww sexeee fur my clothez}
{144}{}{Shamble off}
{145}{}{Temos cervejas e licores sintéticos ... vodka-H, derivados da tequila W e W2. Ah, e água. E o leite brahmin. Cerveja ou licor é dez dólares, água ou leite de três dólares.}
{146}{}{Gostar...?}
{147}{}{Uh, você tem algum álcool real?}
{148}{}{Eu poderia fazer uma cerveja sintética.}
{149}{}{Alguma vodka sintética atingiria o local.}
{150}{}{Algum tequila W2 seria ótimo.}
{151}{}{Alguma água seria ótima.}
{152}{}{leite de braçim.}
{153}{}{Actually, Eu estava procurando alguma informação.}
{154}{}{Voltarei quando tiver mais dinheiro.}
{155}{}{Acho que vou passar, obrigado.}
{156}{}{O leite brahmin não está na torneira ... bem, não exatamente. Eu teria que sair e me enganar muito rápido.}
{157}{}{Isso é bom. Não me importo de esperar. Eu apenas sinto vontade de ter um copo refrescante de leite. Mmmmm-mmm. Isso realmente atingiu o local.}
{158}{}{Acho que vou tentar outra coisa então.}
{159}{}{Never mind then. Say, Eu estava procurando alguma informação...}
{160}{}{Esqueça. Voltarei em algum outro momento.}
{161}{}{Ai está. Algo mais?}
{162}{}{Uh, você tem algum álcool real?}
{163}{}{Eu poderia fazer uma cerveja sintética.}
{164}{}{Alguma vodka sintética atingiria o local.}
{165}{}{Algum tequila W2 seria ótimo.}
{166}{}{Alguma água seria excelente.}
{167}{}{leite de braçim.}
{168}{}{Actually, Eu estava procurando alguma informação.}
{169}{}{Voltarei quando tiver mais dinheiro.}
{170}{}{Acho que vou passar, obrigado.}
{171}{}{Ah? Como o quê?}
{172}{}{Quem está no comando da Vault City?}
{173}{}{Onde está o Vault?}
{174}{}{Você pode me falar sobre a escravidão em Vault City?}
{175}{}{A Vault City tem muito contato com o mundo exterior?}
{176}{}{O que você tem na torneira?}
{177}{}{Eu tenho esse envio de álcool que você queria.}
{178}{}{Tudo bem então. Dia bom.}
{179}{}{Uh, o primeiro cidadão Lynette ... você é um cidadão, não é?}
{180}{}{Primeiro cidadão Lynette. Ela está no conselho construindo o norte se precisar conversar com ela.}
{181}{}{Eu queria saber mais alguma coisa ...}
{182}{}{Tudo certo. Eu vou falar com ela, então.}
{183}{}{Uh, é o grande buraco no lado da montanha a leste daqui ... diga, você é um cidadão, não é?}
{184}{}{É esse grande buraco na montanha a leste daqui. Você não pode perder isso. Você também não pode entrar, a menos que você seja cidadão.}
{185}{}{Eu queria saber mais alguma coisa ...}
{186}{}{Mas eu sou um cidadão.}
{187}{}{Sim, apenas me ajudando, obrigado. Eu vou verificar isso.}
{188}{}{Hmmm. Obrigado pela informação.}
{189}{}{Com certeza você é. Eu apenas tomaria cuidado com quem você diz isso: "Cidadão". Alguém vai reconhecer os papéis roubados que você comprou daquela mulher de sangue Skeev. Então fique com a cabeça baixa, está bem?}
{190}{}{Uh, okay. Say, Eu queria saber mais alguma coisa ...}
{191}{}{Oh. Bem, obrigado pelo conselho.}
{192}{}{Olha, primeiro eu tenho que dizer que é melhor você não chamar de "escravidão" por aqui ou você vai se meter em toda uma bagunça de problemas. Eles são chamados de "servos", não escravos. Apenas um conselho.}
{193}{}{Point taken. Say, Eu queria saber mais alguma coisa ...}
{194}{}{Obrigado. Eu vou manter isso em mente.}
{195}{}{Não muito. A maioria dos contatos que temos com Outsiders são os comerciantes que viajam pela trilha do Caravan Big Circle de Broken Hills, New Reno e Redding. Apenas outro lugar fora da trilha da caravana que conheço é Gecko.}
{196}{}{Conte-me sobre Broken Hills.}
{197}{}{Conte-me sobre New Reno.}
{198}{}{Conte-me sobre Redding.}
{199}{}{Conte-me sobre Gecko.}
{200}{}{Eu queria saber mais alguma coisa ...}
{201}{}{Obrigado pela informação.}
{202}{}{É uma comunidade de mineração como a Redding, exceto que está localizada no extremo sul. Recebemos muitos dos nossos envios de urânio a partir daí.}
{203}{}{Conte-me sobre New Reno.}
{204}{}{Conte-me sobre Redding.}
{205}{}{Conte-me sobre Gecko.}
{206}{}{Eu queria saber mais alguma coisa ...}
{207}{}{Obrigado pela informação.}
{208}{}{É um caminho para o sudoeste. Eu ouço relatórios conflitantes sobre Reno. Alguns comerciantes, especialmente os escravos, realmente adoram lá. Outros comerciantes ... não. Cidade com muito brilho ... e muitos problemas, eu ouço.}
{209}{}{Conte-me sobre Broken Hills.}
{210}{}{Conte-me sobre Redding.}
{211}{}{Conte-me sobre Gecko.}
{212}{}{Eu queria saber mais alguma coisa ...}
{213}{}{Obrigado pela informação.}
{214}{}{É uma cidade mineira muito a oeste. Nós não vimos muitas caravanas deles recentemente, e alguns dos altos estão um pouco preocupados. Especialista sênior McClure especialmente.}
{215}{}{Conte-me sobre Broken Hills.}
{216}{}{Conte-me sobre New Reno.}
{217}{}{Conte-me sobre Gecko.}
{218}{}{Eu queria saber mais alguma coisa ...}
{219}{}{Obrigado pela informação.}
{220}{}{Uma cidade de ghouls menos de um dia de viagem ao nordeste, como eu entendo. O rumor é que eles se alimentam de viajantes que entram em seu território. Melhor ficar longe.}
{221}{}{Conte-me sobre Broken Hills.}
{222}{}{Conte-me sobre New Reno.}
{223}{}{Conte-me sobre Redding.}
{224}{}{Eu queria saber mais alguma coisa ...}
{225}{}{Obrigado pela informação.}
{226}{}{Por quê? Você procura algo com mais chute do que essas bebidas sintéticas?}
{227}{}{Possivelmente. Beber álcool sintético na verdade não pode comparar o real.}
{228}{}{Na verdade não. Eu estava procurando alguma informação em vez disso ...}
{229}{}{Hoje nao.}
{230}{}{Isso é certeza. Eu costumava ter um ... bem, eu conhecia esse comerciante que tinha uma garrafa de Maddog 30/30. Material amargo ... não conseguiria sentir a minha língua depois, mas era refrescantemente diferente.}
{231}{}{O que aconteceu com o estocão deste "comerciante"?}
{232}{}{Eu estava procurando alguma informação.}
{233}{}{Entendo. Bem, foi bom falar com você.}
{234}{}{Ficou bêbado. Ou então eu ouvi. Havia alguns outros "amigos" aqui em Vault City, que ajudaram esse amigo comercial a beber o esconderijo. Eles estavam dispostos a pagar um bom preço para ter as coisas reais para uma mudança.}
{235}{}{Aposto. Você sabe, eu provavelmente poderia obter mais algumas coisas reais, fácil. Eu tenho viajado os resíduos muito, e conseguir um porão de álcool não é grande coisa.}
{236}{}{Eu estava procurando alguma informação.}
{237}{}{Entendo. Bem, foi bom falar com você.}
{238}{}{É assim mesmo? Bem, se você estivesse procurando aliviar-se de algum álcool real, então eu poderia fazer valer a pena. Se você pudesse ficar quieto sobre o nosso negócio. E pegue o contrabando após o portão.}
{239}{}{Qual seria o álcool real que você precisaria?}
{240}{}{Diga, uma caixa de dez garrafas de álcool premium e dez garrafas de cerveja. E nenhuma dessas coisas radioativas que eu ouço, sai de Gecko. Apenas bom velho "bebida", está bem?}
{241}{}{Eu tenho apenas esse valor aqui.}
{242}{}{I might be able to get you some. Say, Eu estava procurando alguma informação...}
{243}{}{Hmmmm. Vou pensar sobre isso e voltar para você.}
{244}{}{Excelente! Aqui é algo para você ... esse valor é o dobro do preço que os casos valem. E essa transação nunca aconteceu, está tudo bem?}
{245}{}{No problem. Hey, Eu estava procurando alguma informação...}
{246}{}{Obrigado. Prazer em fazer negócios com você.}
{247}{}{Não, essas misturas de terra firme que eles chamam de álcool são ilegais aqui na cidade de Vault. Eu nem quero saber como os preparam. Agora você queria algo para beber, Capitão ...?}
{248}{}{Nada de errado com um pouco de álcool real de vez em quando. Claro, sua percepção sofre, mas pode quando você também possui muito pó de cura.}
{249}{}{Eu vou ter outra coisa, então.}
{250}{}{Nevermind then. Eu estava procurando alguma informação...}
{251}{}{Entendo. Obrigado mesmo assim.}
{252}{}{Eu não saberia nada sobre isso. Só sirvo álcool sintético aqui. Se algum álcool real entrasse em Vault City, não saberia nada sobre isso.}
{253}{}{Never mind then. Eu estava procurando alguma informação...}
{254}{}{Entendo. Obrigado mesmo assim.}
{255}{}{Entendo. Bem, cuide agora. OK?}
{256}{}{Thankie wankie my stankie}
{257}{}{Shamble off}
{258}{}{Zzzzzzzz.}
