{100}{}{Você vê um cidadão com um macacão azul brilhante. Parece o terno do Habitante do Vault, mas não há número na parte de trás.}
{101}{}{Você vê um Cidadão da Cidade do Vault.}
{102}{}{Você vê um cidadão com um macacão azul brilhante. Parece o terno do Habitante do Vault, mas não há número na parte de trás.}
{103}{}{:: aplausos ::}
{104}{}{É o herói! Veja!}
{105}{}{Minha palavra! É o herói, aqui, no Vault City!}
{106}{}{Bom dia, capitão.}
{107}{}{Vault City prevalece, capitão.}
{108}{}{Você vai ficar para jantar, capitão?}
{109}{}{Bom dia, cidadão.}
{110}{}{Vault City prevalece, Citizen.}
{111}{}{Você vai ficar para o jantar?}
{112}{}{Um mutante! Guardas! Guardas!}
{113}{}{Um ghoul! Guardas! Guardas!}
{114}{}{Por favor, limpe seus pés antes de entrar na casa.}
{115}{}{Desculpe, nós o convidamos?}
{116}{}{Posso ajudar?}
{117}{}{Vocês Estranhos poderiam suportar aprender algumas maneiras.}
{118}{}{Típico de um Outsider, invadindo aqui ...}
{119}{}{Ouvi falar de seus corajosos atos. Você fez um ótimo serviço para o Vault City ... e o mundo.}
{120}{}{Sua batalha contra o Enclave impressionou até o Primeiro Cidadão.}
{121}{}{Eu ouvi você viajar tão longe do sul como San ... Fran ... Cisco. Isso é verdade?}
{122}{}{Talvez a Vault City * possa * receber Outsiders.}
{123}{}{Era verdade? O governo do velho mundo ainda estava travando a guerra?}
{124}{}{Você deve catalogar suas viagens no computador da Vault City para que outras pessoas possam ler sobre elas.}
{125}{}{É possível ficar o tempo que desejar, herói.}
{126}{}{Você deve catalogar suas façanhas heróicas contra o Enclave em uma lista agradável e arrumada.}
{127}{}{* Yawn * ... hrmnnn? Sim? O que é isso?}
{128}{}{Está um pouco atrasado para os visitantes.}
{129}{}{A maioria dos cidadãos ficaria dormindo a esta hora.}
{130}{}{Adormecido? Não, não mais.}
{131}{}{Por favor ... volte pela manhã. Tenho um longo dia de fazer listas amanhã.}
{132}{}{Bom dia, capitão.}
{133}{}{Vault City prevalece, capitão.}
{134}{}{Você vai ficar para jantar, capitão? Our Servant is making a delicious goulash.}
{135}{}{Gostaria de alguns rosquinhas, capitão?}
{136}{}{Qualquer coisa errada, capitão?}
{137}{}{Espero que nenhum desses estranhos Outsiders esteja lhe dando problemas, capitão.}
{138}{}{Quer algum alimento para levar a seus guardas, Capitão?}
{139}{}{Bom dia, cidadão.}
{140}{}{Vault City prevalece, Citizen.}
{141}{}{Como cidadão, é parte do nosso dever cívico fazer e manter listas.}
{142}{}{Fique no jantar, cidadão. Nosso servo está fazendo um goulash delicioso.}
{143}{}{Passei a maior parte do dia fazendo essa lista para o Proconsul, depois verificando. Eu adoro fazer listas.}
{144}{}{Eu trabalho no Office de Lista. A maioria de nós faz. Nós aqui no Vault City * love * fazendo listas.}
{145}{}{Passei a maior parte do dia hoje atualizando essa lista para o List Office. Foi um trabalho bom, honesto e produtivo.}
{146}{}{Ouvi dizer que você realmente viajou pelo mundo exterior. Como você sobreviveu entre aqueles estranhos Outsiders?}
{147}{}{Ah! Você é o novo cidadão. Bem-vindo ao Vault City.}
{148}{}{Você precisa de um lugar para ficar enquanto você está na cidade?}
{149}{}{O Conselho tem nossos interesses no coração.}
{150}{}{Devemos ter cuidado para manter nossa bela cidade limpa.}
{151}{}{Cada família recebe um quarto na casa comum.}
{152}{}{A cidade nos fornece tudo o que precisamos.}
{153}{}{Os servos? Oh, nós os usamos para tarefas menores.}
{154}{}{Hmmmm. Preciso conseguir um servo para arrumar a sala da loja ...}
{155}{}{Um servo deveria terminar mais tarde para cortar o jardim ...}
{156}{}{A reunião do Conselho de ontem foi muito produtiva. Nós fizemos * lotes * de listas. Nós aqui no Vault City adoramos fazer listas.}
{157}{}{Sim?}
{158}{}{Perdoe-me, posso ajudá-lo?}
{159}{}{É educado perguntar antes de entrar na casa de alguém.}
{160}{}{Por favor, limpe seus pés antes de entrar na casa.}
{161}{}{Desculpe, nós o convidamos?}
{162}{}{Posso ajudar?}
{163}{}{Vocês Estranhos poderiam suportar aprender algumas maneiras.}
{164}{}{A cidade nos fornece tudo o que precisamos.}
{165}{}{Os servos? Oh, nós os usamos para tarefas menores.}
{166}{}{Hmmmm. Preciso conseguir um servo para arrumar a sala da loja ...}
{167}{}{Um servo deveria terminar mais tarde para cortar o jardim ...}
{168}{}{Sim, eu posso cheirar ... er, veja, você é um Outsider.}
{169}{}{Você é um estranho? Quão pitoresco.}
