{100}{}{Você vê Proconsul Gregory.}
{101}{}{Você vê um burocrata sombrio com um rosto estreito e sobrancelhas grossas.}
{102}{}{Você vê Proconsul Gregory.}
{103}{}{Você vê um burocrata sombrio com um rosto estreito e sobrancelhas grossas.}
{104}{}{Por seu ato de bravura, você recebeu acesso total à Vault City. Ah ... o primeiro cidadão disse que queria te ver.}
{105}{}{Um intruso! Guardas! Guardas!}
{106}{}{Wh- ?! Um mutante! GUARDAS! GUARDAS!}
{107}{}{Wh-? Um ghoul! GUARDAS! GUARDAS!}
{108}{}{Bom dia, capitão.}
{109}{}{Vault City prevalece, capitão.}
{110}{}{Bom dia, cidadão.}
{111}{}{Vault City prevalece, Citizen.}
{112}{}{Listas, listas, listas ... como eu amo listas!}
{113}{}{Compile o formulário 5632 no servidor de lista ...}
{114}{}{Faça uma lista das listas 43A a 121B ... então insira-as no arquivo da lista ...}
{115}{}{É um lindo dia para compilar listas.}
{116}{}{Ainda preciso terminar essas listas antes de me aposentar para a noite ...}
{117}{}{Volte pela manhã. Eu deveria terminar com essas listas até então.}
{118}{}{Filthy mutant ...}
{119}{}{Não sei como você se tornou cidadão. Você não é mais que um mutante para mim. Se alguém me acreditasse ...}
{120}{}{Não sei como você se tornou Capitão. Você não é mais que um mutante para mim. Se alguém me acreditasse ...}
{121}{}{Me desculpe ... posso ajudá-lo?}
{122}{}{Hep Yew.}
{123}{}{Shamble off}
{124}{}{Quem é Você?}
{125}{}{Apenas olhando ao redor, obrigado.}
{126}{}{Ainda outro servo que se desviou de suas rondas ?! Vou colocar Barkus no relatório se ele continuar deixando vagar ... agora, você ... Shoo! Shoo!}
{127}{}{SHOOT yew? OK.}
{128}{}{Shamble off}
{129}{}{* Tchh * Esses servos parecem ficar cada dia mais impressionantes.}
{130}{}{Eu sou Proconsul Gregory. O escritório que você estava procurando, ou ...?}
{131}{}{"Procônsul?" O que diabos é um "Proconsul?"}
{132}{}{O que você faz aqui?}
{133}{}{Apenas olhando ao redor, obrigado.}
{134}{}{Eu sou o ASSISTENTE ao primeiro cidadão. Planejo suas consultas, administro o teste de Cidadania para potenciais candidatos e atualize todas as listas no servidor da Cidade do Vault. Nenhuma tarefa pequena, eu lhe asseguro.}
{135}{}{O teste de cidadania?}
{136}{}{Falando sobre o teste de cidadania, quero retomá-lo novamente.}
{137}{}{Posso fazer-te algumas perguntas?}
{138}{}{Entendo. Bem, eu tenho que ir.}
{139}{}{Sim, há o caminho certo ... você pode se tornar cidadão ao fazer o teste de Cidadania.}
{140}{}{Sim, eu sou responsável por administrar o teste de Cidadania a qualquer pessoa que deseje se tornar cidadã da Cidade do Vault.}
{141}{}{Qual é o teste, exatamente?}
{142}{}{Quero testar novamente.}
{143}{}{Quais os benefícios de ser um cidadão?}
{144}{}{Posso fazer algumas outras perguntas?}
{145}{}{Entendo. Talvez voltemos a falar mais tarde.}
{146}{}{Benefícios? Por que, olhe em volta ... Vault City é a cidade mais segura e segura em todos os resíduos. Os cidadãos recebem tratamento médico gratuito, os alimentos e a água são abundantes, e não há crime ou doença para falar.}
{147}{}{Qual é exatamente o teste?}
{148}{}{Parece bom. Gostaria de fazer o teste novamente.}
{149}{}{Posso fazer algumas outras perguntas?}
{150}{}{Entendo. Talvez voltemos a falar mais tarde.}
{151}{}{É um exame abrangente, dividido em várias partes ... matemática avançada, relações espaciais, raciocínio dedutivo, compreensão da linguagem ... ah, e também há um exame físico completo.}
{152}{}{Wh ... matemática avançada-ma-what? Uh, não há algum objeto que eu possa obter ou alguém que eu possa lutar para obter cidadania?}
{153}{}{Soa ... complicado. Uh, posso fazer o teste?}
{154}{}{Parece difícil. Gostaria de fazer o teste, se puder.}
{155}{}{Soa elementar. Eu gostaria de tomar este teste de cidadania.}
{156}{}{Você não está testando a acuidade visual ou as habilidades de lógica do sujeito? Hmmm. Bem, talvez você considere revisar este teste no futuro ... depois de aceitá-lo.}
{157}{}{I see. Posso fazer algumas outras perguntas?}
{158}{}{Interessante. Obrigado pelo seu tempo.}
{159}{}{Bem, se você terminar essa tarefa para o Primeiro Cidadão, ela lhe dará sua Cidadania, não que você mereça isso. Suponho que ela tenha seus motivos.}
{160}{}{Não. Se você deseja se tornar um cidadão, você deve fazer o teste.}
{161}{}{Você desaprova que ela me ofereça cidadania para isso?}
{162}{}{Vou dar uma chance ao teste.}
{163}{}{Eu vou dar o teste novamente, então.}
{164}{}{Hmmm. Posso fazer algumas outras perguntas?}
{165}{}{Obrigado pelo seu tempo. Adeus.}
{166}{}{Você deseja fazer o teste? Excelente, excelente! Nada me agrada mais do que testar potenciais candidatos ... mas devo avisá-lo, o teste dura várias horas. Deseja levá-lo agora?}
{167}{}{Bem, qualquer um pode fazer o teste. Penso que no seu caso, no entanto, seria uma perda de tempo ... para nós dois. Alguém de seu calibre simplesmente não é material cidadão.}
{168}{}{Certo.}
{169}{}{Not now. Posso fazer algumas outras perguntas?}
{170}{}{Talvez outra hora.}
{171}{}{Gostaria de fazer o teste de qualquer maneira.}
{172}{}{Apenas me dê a maldita prova.}
{173}{}{Forget it then. Posso fazer algumas outras perguntas?}
{174}{}{Tanto faz. Estou fora daqui.}
{175}{}{Muito bem.}
{176}{}{Hmmm. Bem, esse é o seu direito, embora duvido que isso seja importante.}
{177}{}{Aqui estão os formulários 5028, 6112 e o console de resposta do Pip Boy. Certifique-se de preencher cada círculo COMPLETAMENTE. Agora, se você se sentar aqui ...}
{178}{}{Tudo certo.}
{179}{}{Já terminou? Tem certeza de que não deseja verificar suas respostas?}
{180}{}{Tudo bem, o tempo está pronto. Vamos ver o seu formulário.}
{181}{}{Já fiz. Aqui.}
{182}{}{Esperar! Apenas um minuto mais ... ah, esqueça. Aqui.}
{183}{}{Hmmm ... não, não ... isso está errado ... isso também não está certo ... uma divisão por zero erro aqui ... hmmm ... precisava carregar os dois ... oh meu, seu vocabulário é Infelizmente, também faltam, vejo.}
{184}{}{Vamos ver ... Vejo que você perdeu a identificação da equação sub-derivada ... e perdeu o significado essencial do parágrafo sete, ambas as partes ... e a pirâmide desse diagrama pode ser cruzada oito vezes e não três.}
{185}{}{Bem, as respostas que você conseguiu colocar parecem excelentes ... é a oportunidade em que você fez o teste ... e os erros gramaticais brilhantes e ...}
{186}{}{Assim...?}
{187}{}{Bem, lamento informar-lhe que não posso conceder-lhe Cidadania neste momento.}
{188}{}{Francamente, você não parece ter a inteligência necessária para entender a matemática superior.}
{189}{}{Se posso dizer, sua compreensão das relações espaciais limita-se a imperceptivel.}
{190}{}{Se eu posso dizer, você não parece testar bem. Talvez você tenha mais sorte na próxima vez.}
{191}{}{Talvez em algum outro momento, então.}
{192}{}{Bem, vamos dar uma olhada ... primeiro, vamos ver se ... oh, muito bom, eu vejo que você conseguiu isso, e você ... porque sim, você carregou os dois, muito inteligente, muito inteligente ... Mas por que você ... oh, você aplicou o derivado para # 5 ... brilhante!}
{193}{}{CURSO foi brilhante.}
{194}{}{Por que ... você passou! Parabéns.}
{195}{}{Ótimo. Então eu sou um cidadão?}
{196}{}{Bem, ainda temos que realizar o exame físico. Felizmente, tenho todo o equipamento aqui. Você pode querer tirar suas botas.}
{197}{}{OK.}
{198}{}{Você ... você tem um sexto dedo! Você é um mutante! Como você ousa tentar se tornar um de nós ... você ... você abominação! Saia! Fora! E nunca mais volte!}
{199}{}{Aqui vem a parte quando eu perdi minha paciência e mato todos os Cidadãos em Vault City por diversão. Começando com você.}
{200}{}{Eu vou sair, vou embora!}
{201}{}{Sua pressão sanguínea parece boa, não há doenças transmissíveis que posso encontrar ... parabéns, cidadão. Bem-vindo ao Vault City.}
{202}{}{Obrigado. É bom estar aqui.}
{203}{}{Você novamente. Posso ajudar?}
{204}{}{Suponho ... o que você gostaria de saber?}
{205}{}{O que você faz aqui novamente?}
{206}{}{Posso fazer o teste de cidadania?}
{207}{}{Posso fazer o teste de cidadania novamente?}
{208}{}{O que você pode me falar sobre Gecko?}
{209}{}{Deixa pra lá. Talvez voltemos a falar mais tarde.}
{210}{}{Bem, se você terminar essa tarefa para o Primeiro Cidadão, ela lhe dará sua Cidadania, não que você mereça isso. Suponho que ela tenha seus motivos.}
{211}{}{Existe outra maneira de se tornar um cidadão?}
{212}{}{Você desaprova que ela me ofereça cidadania para isso?}
{213}{}{Posso fazer algumas outras perguntas?}
{214}{}{Hmm. Adeus.}
{215}{}{Não é meu lugar questionar as ações do Primeiro Cidadão.}
{216}{}{Existe outra maneira de se tornar um cidadão?}
{217}{}{Posso fazer algumas outras perguntas?}
{218}{}{Deixa pra lá então.}
{219}{}{Gecko? É uma pequena favela ao norte, habitada por essas criaturas, aquelas ... "ghouls". Eles são responsáveis   por envenenar nossas águas subterrâneas, você sabe! É um ato óbvio de terrorismo contra Vault City!}
{220}{}{Como estão envenenando a água?}
{221}{}{Hmmm. Posso fazer algumas outras perguntas?}
{222}{}{Obrigado, adeus.}
{223}{}{Sua favela é construída em torno dos restos de uma antiga usina de energia atômica ... uma planta em que algum dia começou a funcionar novamente e agora está vazando radiação! Essas criaturas precisam ser expulsas e essa planta desligou!}
{224}{}{Hmmm. Posso fazer algumas outras perguntas?}
{225}{}{Obrigado pela informação. Adeus.}
{226}{}{Você passou pelo teste de cidadania e se tornou cidadão de Vault City.}
