{100}{}{Você vê uma mulher de aparência severa com óculos grossos, usando um macacão da Cidade do Vault. A julgar pelo seu porte, ela parece importante.}
{101}{}{Você vê o primeiro cidadão Lynette. Ela parece preocupada.}
{102}{}{Você vê o primeiro cidadão Lynette. Ela parece preocupada.}
{103}{}{Está tarde. Programe uma consulta para amanhã de manhã, e eu vou recebê-lo então.}
{104}{}{Como eu disse, não recebo visitantes tão tarde. A maioria dos cidadãos se aposentou na cama por este tempo.}
{105}{}{Programe uma consulta para amanhã de manhã. Eu vou recebê-lo então.}
{106}{}{Vou falar com você MAIOR.}
{107}{}{Eu não sei como você passou os guardas e nas minhas câmaras privadas, mas é melhor você sair.}
{108}{}{Eu não sei o que você pretende ganhar clicando em mim, mas não vou tolerar muito mais.}
{109}{}{Talvez você encontre clicando em mim ... divertida. Talvez você encontre o Centro de correções tão humorístico.}
{110}{}{Agradeço sua atenção, mas eu realmente sou bastante perigoso quando é irritado.}
{111}{}{Eu sou o primeiro cidadão! Devo ter o meu sono!}
{112}{}{Sair!}
{113}{}{Saia!}
{114}{}{Fora! Fora! Fora!}
{115}{}{Admiro sua persistência. Eu gostaria de admirá-lo de uma distância.}
{116}{}{Isso é uma espécie de tentativa desajeitada de me informar que você é atraído por mim?}
{117}{}{Você gosta dos meus pequenos dreadlocks? Acho que Scott Rodenhizer tem um estranho senso de humor.}
{118}{lyn002}{A palavra de sua ação corajosa viajou rapidamente. É verdade? O governo ainda estava travando a guerra?}
{119}{}{Wahr? Wahr whar?}
{120}{}{Sim. Eles iriam usar um vírus para exterminar toda a vida. Eles planejaram começar de novo ... em
 O custo de tudo o que você construiu aqui.}
{121}{}{Você ouviu incorretamente. Eu sou apenas um viajante, nada mais ... e certamente nenhum herói. Agora eu só
 Desejo ser deixado em paz, permitido perambular pelos resíduos em busca do meu lugar neste novo mundo. Adeus, primeiro cidadão ... para sempre.}
{122}{lyn003}{Das coisas mais simples - e certamente você é - mesmo a grandeza pode crescer.
 Tome cuidado, meu doce imbecil ... toda a cidade de Vault agradece.}
{123}{}{Abrace-a.}
{124}{}{Oo. Tchau tchau.}
{125}{lyn004}{Awwwww ... lá, lá. Sempre que precisar de um abraço, você vê a tia Lynette, está bem?}
{126}{}{Okeee-dokeee.}
{127}{}{Tchau tchau.}
{128}{lyn005}{Quão insensível! Que cruel! Eles não estavam conscientes da comunidade que construíramos aqui?}
{129}{}{Talvez uma lição importante possa ser aprendida aqui, Lynette. Isolado do mundo, o
 O governo estava preparado para destruí-lo, sem sequer reconhecer o valor de sua comunidade. Possivelmente
 Vault City deve dar uma olhada no mundo exterior ... e seu lugar nele.}
{130}{}{Callous, cruel ... talvez. Tudo o que sei é que eu tinha poder de fogo superior. Adeus, primeiro cidadão.}
{131}{lyn006}{Esse pode ser um ponto válido. Na próxima vez, devemos fazer um esforço mais forte para encontrar esses restos
 Do governo e ally-nos com eles. Eu ouvi que eles têm uma grande armadura de poder.}
{132}{}{Mas ... ah, esqueça. Boa sorte, First Citizen.}
{133}{}{Você não conhece a metade, First Citizen! Direção hidráulica, reciclagem de fluidos corporais, ameaça
 Exterior ... muito legal.}
{134}{}{Adeus, primeiro cidadão. Devo voltar ao mundo exterior ... e encontrar meu lugar nele.}
{135}{lyn007}{Por favor, ligue para mim, Lynette. Viaje com cuidado ... meu amigo. Nunca devemos esquecê-lo.
 Você sempre deve ter uma casa aqui dentro dos muros da Cidade do Vault.}
{136}{}{Obrigado ... Lynette.}
{137}{}{Sim, tudo bem, eu tenho uma casa aqui. Com estes novos problemas e meu poder de fogo superior, seria
 Leve cinco segundos para que eu abatei todos nesta distopia de águas remotas. Durma fácil, Lynette. Ha Ha Ha Ha Ha.}
{138}{lyn008}{Você está vestindo um terno de abóbada! Nunca imaginei que eu conhecesse um habitante de outro cofre.
 Este Vault 13 ... onde está localizado?}
{139}{}{Hunh?}
{140}{}{Valt! Valt!}
{141}{}{Hed funneee.}
{142}{}{Tchau tchau}
{143}{}{Não é esse o Vault do meu antepassado originalmente?}
{144}{}{Eu não sei. Venho de uma aldeia no oeste.}
{145}{}{Eu não sei. Estou tentando achar o Vault do meu antepassado ... você pode me ajudar?}
{146}{}{Não tenho tempo para explicar toda a história agora. Dia bom.}
{147}{lyn009}{Esse deve ser o seu QI no seu macacão, e não um número do Vault.}
{148}{}{Hrnnnn?}
{149}{}{Nooom-ber}
{150}{}{Har funeee!}
{151}{}{Shamble off}
{152}{lyn010}{Eu não sei como você reuniu o poder do cérebro para entrar na cidade, mas eu me certificarei
 Você não se aproxima aqui ... guardas! Acompanhe esse imbecil fora das paredes!}
{153}{}{NÃO!}

# player's name prepended to line 154
{154}{}{ Ir com pessoas de metal}
{155}{lyn011}{Bom dia para você, estranho. Eu sou o primeiro cidadão Lynette. Posso consultar o seu negócio aqui?}
{156}{}{Bizzzness? Bzzzzz-neff?}
{157}{}{Eer!}
{158}{}{Tchau tchau.}
{159}{}{Estou procurando um Kit de Criação do Jardim do Éden. Você tem um?}
{160}{}{Estou em busca de um Kit de Criação do Jardim do Éden, First Citizen. A sua cidade possui um que eu possa comprar?}
{161}{}{Você é o ... Supervisor deste cofre?}
{162}{}{Desculpe minha ignorância, First Citizen ... o título "First Citizen" significa que você é o Supervisor deste cofre?}
{163}{}{Esta é Vault City? Por que você não mora em um cofre?}
{164}{}{Nenhum negócio hoje. Talvez outra hora.}
{165}{}{Nada hoje. Minhas desculpas por perturbá-lo, First Citizen. Dia bom.}
{166}{lyn012a}{Onde um de vocês, como você, ouviu falar de um Kit de Criação do Jardim do Éden?}
{167}{lyn012b}{Essa tecnologia não é para Outsiders.}
{168}{}{Você obteve um PROBLEMA com Outsiders, mulher?}
{169}{}{Você obteve um PROBLEMA com Outsiders?}
{170}{}{Minhas desculpas ... existe um problema em ser um Outsider, First Citizen?}
{171}{}{Eu sou o descendente do Vault Dweller. O GECK é necessário para ajudar minha aldeia.}
{172}{}{Eu sou o descendente do Vault Dweller, First Citizen. O GECK é necessário para ajudar minha aldeia.}
{173}{}{Mulher, me dê o GECK agora, ou eu vou pegar com força.}
{174}{}{Me dê o GECK agora, ou eu tomarei isso pela força.}
{175}{}{Então não temos mais nada para discutir. Dia bom.}
{176}{lyn013}{O problema é que todos os Estranhos desejam se juntar à nossa sociedade, o que simplesmente não é viável.
 Nós, sem dúvida, afundaríamos na mesma anarquia que aflige o exterior.}
{177}{}{Entendo. Quero falar com o Supervisor do Vault. Você pode me levar para ele?}
{178}{}{Como se trata de se tornar um de vocês, o Vault Dwellers?}
{179}{}{Se você odeia muito o mundo exterior, por que você mora lá fora, e não no cofre?}
{180}{}{Já ouvi o suficiente. Adeus.}
{181}{}{Compreendo. Obrigado pelo seu tempo, First Citizen.}
{182}{lyn014}{Acho todos vocês Outsiders ofensivos. Você é inculto e primitivo, não é melhor do que
 Animais! Agora vá embora. Ou eu vou ter você removido à força.}
{183}{}{Não! Não vou embora até receber respostas!}
{184}{}{"Forçado removido?" Tente. Eu vou gostar.}
{185}{}{Eu vou em silêncio ... desta vez.}
{186}{}{Eu vou sair, vou embora.}
{187}{lyn015a}{"Encarregado de obra?" Porque nao. Não houve um Supervisor em cem anos. Como você sabe de
 Os Supervisores de Vault?}
{188}{lyn015b}{Já lhe disse. Os supervisores são do passado distante.}
{189}{}{Eu sou descendente do primeiro morador do Vault. Ouvi ... muitas histórias do Supervisor.}
{190}{}{O que aconteceu com o Supervisor? Eu devo falar com ele.}
{191}{}{Você não é o único que eu preciso falar. Procure o Supervisor de uma só vez, mulher.}
{192}{}{Você não é o único que eu preciso falar. Procure o Supervisor de uma só vez.}
{193}{}{Deixa pra lá. Eu devo ir. Dia bom.}
{194}{lyn016}{"Descendente do Vault Dweller?" O que você quer dizer?}
{195}{}{Eu sou o bisneto do primeiro Vault Dweller.}
{196}{}{Mulher, estou perdendo muito tempo conversando com você. Procure o Supervisor de uma só vez.}
{197}{}{Estou perdendo muito tempo conversando com você. Procure o Supervisor de uma só vez.}
{198}{}{Nada, esquece. Continuaremos essa conversa mais tarde.}
{199}{lyn017a}{Você entra em minhas câmaras e depois tem a audácia de me insultar, Lynette, First Citizen of Vault City ?!}
{200}{lyn017b}{Você entra em minhas câmaras e então tem a audácia de fazer demandas de mim, Lynette, First Citizen of Vault City ?!}
{201}{lyn017c}{Sair. Você não é mais bem vindo nesta cidade.}
{202}{}{Eu não vou embora até obter algumas respostas.}
{203}{}{Eu irei ... por agora.}
{204}{lyn018}{Não, não, não vivemos no cofre. Eles eram uma medida temporária para proteger um escolhido
 Poucos da guerra e os ajudam na construção subsequente de um novo mundo.}
{205}{}{Como você soube quando sair do cofre? Ouvi dizer que os cofres estavam isolados do mundo exterior.}
{206}{}{É importante que eu fale com o Supervisor. Você pode me levar para ele?}
{207}{}{Estou perdendo muito tempo conversando com você. Procure o Supervisor de uma só vez, mulher.}
{208}{}{Estou perdendo muito tempo conversando com você. Procure o Supervisor de uma só vez.}
{209}{}{Já ouvi o suficiente. Adeus.}
{210}{}{Obrigado pelo seu tempo, First Citizen. Dia bom.}
{211}{lyn019}{Não existe um "Supervisor". Quando chegamos à superfície, formamos um novo governo. A posição do Supervisor era supérflua.}
{212}{}{Novo governo? Conte-me sobre isso.}
{213}{}{Então você é o líder dos antigos habitantes do cofre?}
{214}{}{Inteligente. Livrar-se do Supervisor corrupto.}
{215}{}{Entendo. Obrigado pela informação. Dia bom.}
{216}{lyn020}{O que você ouviu estava incorreto. Nossos arquivos são bastante claros: nosso cofre recebeu o sinal totalmente claro dois anos depois de ser selado.}
{217}{}{O sinal "tudo claro"? De onde?}
{218}{}{Onde estão esses arquivos?}
{219}{}{Onde está o Supervisor? Eu devo falar com ele.}
{220}{}{Bem, NOSSA lenda tribal afirma que o Vault foi fechado por anos ... e nenhum sinal "claro" já veio.}
{221}{}{Você mente! O todo-claro nunca veio!}
{222}{}{Entendo. Obrigado pela informação. Dia bom.}
{223}{lyn021}{Por que ... dos monitores de superfície, suponho. Estou certo de que houve monitoramento de sensores
 o ambiente. Como o Supervisor saberia quando era seguro sair?}
{224}{}{Esses monitores ainda existem? Posso vê-los?}
{225}{}{Então ... a ordem de deixar o cofre veio do Supervisor?}
{226}{}{Falando do Supervisor, onde ele está? Gostaria de falar com ele.}
{227}{}{Você mente! O sinal totalmente claro nunca veio!}
{228}{}{Ainda não tenho certeza ... Dia bom.}
{229}{lyn022}{Provavelmente foram desmontados e usados   como atualizações para outros sistemas.}
{230}{}{Hmmm. Mas o Supervisor foi quem deu a ordem de deixar o cofre?}
{231}{}{Onde está o Supervisor? Devo falar com ele sobre isso.}
{232}{}{Eu não acredito em você. Estou lhe dizendo que o sinal totalmente claro nunca veio!}
{233}{}{Entendo. Obrigado pela informação. Dia bom.}
{234}{lyn023}{Sim ... pelo menos, é isso que lembro dos arquivos. No entanto, estou certo de que muitos
 Os cidadãos foram responsáveis   pelo monitoramento dos sensores de superfície.}
{235}{}{Alguma idéia de onde esses sensores de superfície estão agora?}
{236}{}{Onde estão esses arquivos?}
{237}{}{Onde está o Supervisor? Eu devo falar com ele.}
{238}{}{Você mente! O sinal totalmente claro nunca veio!}
{239}{}{Entendo. Obrigado pela informação. Dia bom.}
{240}{lyn024}{Se você fosse capaz de examinar seu argumento, a falha rapidamente se tornaria aparente.
 Os arquivos não permitem a mesma forma de corrupção ... suas "lendas tribais" fazem.}
{241}{}{Onde estão esses arquivos?}
{242}{}{Onde está o Supervisor? Eu devo falar com ele.}
{243}{}{Olha, estou lhe dizendo ... o sinal todo claro nunca veio!}
{244}{}{Já ouvi o suficiente. Dia bom.}
{245}{lyn025}{You have the audacity to accuse me, Lynette, the First Citizen of Vault City, of LYING?!
 Sair! You are no longer welcome in this city.}
{246}{}{Não vou embora até receber respostas!}
{247}{}{Devo ... agora.}
{248}{lyn026}{Os arquivos são armazenados dentro do nosso cofre. Apenas os cidadãos têm acesso a eles ... eles são
 NÃO para Outsiders.}
{249}{}{Bem. Onde está o Supervisor? Vou perguntar-lhe sobre esses arquivos.}
{250}{}{Mas eu sou um cidadão.}
{251}{}{Como um se torna um de vocês, Vault Dwellers?}
{252}{}{Como posso me tornar um cidadão?}
{253}{}{Já ouvi o suficiente. Dia bom.}
{254}{lyn027}{Não nos consideramos mais "Vault Dwellers" ... nos referimos a nós mesmos como
 "Cidadãos". Se você deseja se tornar parte de nossa comunidade, você deve primeiro provar seu valor.}
{255}{}{Prove meu valor? Como?}
{256}{}{Eu sou o descendente do primeiro Vault Dweller - isso deve ser suficiente.}
{257}{}{Vou pensar sobre isso. Dia bom.}
{258}{lyn028}{Você entende mal ... não é o mundo a que nos opomos, são as pessoas nele. Veja
 Ao redor - dentro dessas paredes é tudo o que resta da civilização anterior à guerra.}
{259}{}{Onde está o Supervisor? Preciso falar com ele.}
{260}{}{Não está certo, você não compartilha. É sua responsabilidade ajudar todos ... não apenas aqueles
 Que vivem nessas paredes.}
{261}{}{Entendo. Obrigado pelo seu tempo. Dia bom.}
{262}{lyn029}{Vocês Outsiders são bons para dar uma palestra sobre "responsabilidade". Você implora incessantemente por
 Ajude, ainda não faça nada para melhorar você mesmo. Nossa conversa acabou ... deixe agora, antes de convocar os guardas.}
{263}{}{É melhor convocar os guardas agora, porque você não terá outra chance.}
{264}{}{Não vou embora até ver o Supervisor!}
{265}{}{Estou saindo ... por enquanto.}
{266}{}{Muito bem. Obrigado por falar comigo. Dia bom.}
{267}{lyn030}{"O primeiro morador do Vault?" O que? Você deve significar outro Vault! Nós nunca estivemos em
 Contato com outro Vault! Onde está localizado?}
{268}{}{Eu acho que ESTA foi o cofre do meu antepassado originalmente veio.}
{269}{}{Eu não vivo em um Vault. Venho de uma aldeia tribal do oeste.}
{270}{}{Eu não sei ... você vê, estou tentando encontrar o Vault do meu antepassado.}
{271}{}{Quando eu encontrá-lo, vou ter a certeza de que você sabe. Dia bom.}
{272}{lyn031}{Saímos do Vault há 120 anos e, com a ajuda do nosso kit Eden, iniciamos a construção
 Da Vault City. Dez anos depois, o Supervisor se aposentou e um Conselho de Cidadãos foi estabelecido. o
 O Conselho nomeou o primeiro cidadão inicial.}
{273}{}{Falando sobre o GECK, você tem outro que eu poderia ter?}
{274}{}{Então você é o líder desta cidade, então?}
{275}{}{Há 120 anos? Isso foi 70 anos antes que o morador da barraca parasse o mestre. Isso não pode ser o
 Abóbada que estou procurando.}
{276}{}{Entendo. Dia bom.}
{277}{lyn032}{Corrigido ... Eu sou o primeiro cidadão de Vault City.}
{278}{}{Primeiro cidadão, tenho um pedido urgente: minha aldeia está em extrema necessidade de uma criação do Jardim do Éden
 Kit. Você possui um que eu possa ter?}
{279}{}{Então você é quem eu procuro. Venho em nome das pessoas de Arroyo para reivindicar o que é
 Legitimamente nosso: o sagrado GECK.}
{280}{}{Entendo. Obrigado por falar comigo. Dia bom.}
{281}{lyn033}{Corrupto ?! O Supervisor era um grande homem e um líder impecável. Seus ensinamentos e sabedoria
 Ainda compreendem grande parte da nossa escolaridade.}
{282}{}{Isso não soa como Overseer o Vault Dweller sabia.}
{283}{}{Depois de salvar o Vault, o Habitante do Vault foi banido pelo Supervisor. Que tipo de lição é essa?}
{284}{}{Então você foi criado um tolo. Não desperdice mais do meu tempo, mulher. Procure alguém que possa me ajudar.}
{285}{}{Então você foi criado um tolo. Não desperdice mais do meu tempo. Procure alguém que possa me ajudar.}
{286}{}{Isso é uma pena. Dia bom.}
{287}{lyn034a}{Você pode falar com Proconsul Gregory. Ele tem autoridade para administrar a Cidadania
 teste. Ele pode ser encontrado na sala de reuniões pelo corredor.}
{288}{lyn034b}{Ou ... há outra maneira de se tornar um cidadão ...}
{289}{}{Outra maneira? O que é isso?}
{290}{}{Eu acho que vou falar com o Proconsul. Adeus.}
{291}{}{Eu vou falar com o Proconsul, então.}
{292}{}{Eu irei falar com Gregory. Obrigado pelo seu tempo, First Citizen.}
{293}{lyn035}{Bastante impossível. No século, vivemos fora do Cofre, ninguém escolheu
 deixar. Embora houvesse dois cidadãos exilados da nossa cidade há muito tempo ... como punição por seus crimes.}
{294}{}{Vocês são os que REALIZARAM o morador do Vault! Eu vim para o que é legítimo meu!}
{295}{}{O que esses cidadãos fizeram?}
{296}{}{Se este não for o Vault certo, então eu devo encontrar o que meu antepassado veio.}
{297}{}{Eu tenho que ir. Dia bom.}
{298}{lyn036a}{Aldeia? Mas você está vestindo um terno Vault ... em que é a aldeia da qual você fala? Falar
 Claramente: minha paciência está desgastando.}
{299}{lyn036b}{Aldeia? Primeiro, você me diz que é de um cofre, agora de uma aldeia. Qual e?! Minhas
 A paciência para a sua dupla conversa é desgastada.}
{300}{}{Aguarde, você me entende mal. O Vault Dweller foi o fundador da minha aldeia.}
{301}{}{Minha paciência para você está usando uma mulher fina. Procure alguém ... alguém que possa me ajudar.}
{302}{}{Minha paciência para você está vestindo fina. Procure alguém ... alguém que possa me ajudar.}
{303}{}{Acho que só vou voltar mais tarde. Dia bom.}
{304}{lyn037}{Oh ... agora entendo. Mas que prova você tem que seu Ancestor era de um Vault?}
{305}{}{Histórias, transmitidas pelo Ancião da minha Aldeia.}
{306}{}{Eu tenho os artefatos sagrados do Vault Dweller ... este terno da Abóbada e este frasco sagrado.}
{307}{}{Eu tenho este macacão de vaqueiro e essa cantina. Eles pertenciam ao meu antepassado.}
{308}{}{Estou cansado de suas perguntas. Eu vou encontrar alguém que possa me ajudar.}
{309}{}{Eu tenho que ir. Dia bom.}
{310}{lyn038}{Hmm ... talvez alguma menção do seu Vault esteja nos arquivos do nosso computador.}
{311}{}{Bem, podemos verificar?}
{312}{}{Primeiro cidadão, é muito importante para mim descobrir a localização do Vault do meu antepassado.
 Se eu pudesse verificar os arquivos, eu ficaria grato.}
{313}{}{Hmmmm. Obrigado pela informação. Dia bom.}
{314}{lyn039}{Me desculpe, mas usamos o nosso para começar a Cidade do Vault. Eu não acredito que houvesse peças sobressalentes,
 Mas você pode verificar o Escritório de Aquisições. Está localizado junto à entrada do nosso cofre.}
{315}{}{Obrigado. Tive algumas outras questões ...}
{316}{}{Você saberia onde o Vault 13 está localizado?}
{317}{}{Ótimo! Eu irei lá, então. Dia bom.}
{318}{lyn040}{Um terno de abóbada suja e uma cantina maltratada? Essa é a sua prova? Quem sabe onde você
 Eliminou essas "relíquias" de ... ou quem matou para roubá-las.}
{319}{}{Por favor ... olhe para eles de novo. Eles são genuínos.}
{320}{}{Viajei por todo esse caminho. Pelo menos olhe para eles, mulher!}
{321}{}{Viajei por todo esse caminho. Pelo menos olhe para eles!}
{322}{}{Se não forem suficientes para convencê-lo, não há mais nada a dizer. Dia bom.}
{323}{lyn041a}{Você tem alguma concepção de quão ocupado estou? Eu corro essa cidade, e eu tenho um pouco precioso
 Tempo para desperdiçar com você e suas reivindicações selvagens.}
{324}{lyn041b}{Você tem alguma concepção de quão ocupado estou? Eu corro essa cidade, e eu tenho um pouco precioso
 Tempo para perder com você.}
{325}{lyn041c}{Agora, saia imediatamente, ou eu chamarei os guardas.}
{326}{}{Vá em frente e ligue para eles. Eles não chegarão a tempo para salvar sua vida.}
{327}{}{Bem. Estou indo embora.}
{328}{}{Muito bem, primeiro cidadão. Dia bom.}
{329}{lyn042}{Uma lenda tribal? Você precisará de algo mais substancial do que alguns ... MITO tribal se você
 Quer que alguém acredite em sua reivindicação.}
{330}{}{But Eu tenho os artefatos sagrados do Vault Dweller ... este terno da Abóbada e este frasco sagrado.}
{331}{}{Eu tenho este macacão de vaqueiro e essa cantina. Eles pertenciam ao meu antepassado.}
{332}{}{O que eu tenho que fazer para provar minha herança, se você não acreditar na minha palavra ?!}
{333}{}{Bem. Estou indo embora.}
{334}{}{Muito bem, então não temos mais nada a discutir. Bom dia, primeiro cidadão.}
{335}{lyn043}{Podemos verificar os computadores do Vault. Eles provavelmente teriam a informação que você procura.
 Mas apenas os cidadãos podem acessar os arquivos.}
{336}{}{Mas eu sou um cidadão.}
{337}{}{Existe alguma maneira de eu me tornar um cidadão?}
{338}{}{Acho que estou sem sorte, então. Dia bom.}
{339}{lyn044}{Em vez de fazer o teste, você pode provar seu compromisso com os Vaults em um ...
Maneira substancial. Como um Outsider, você está em uma posição única para resolver uma situação difícil ... para nós.}
{340}{}{Que tipo de situação?}
{341}{}{Claro. Independentemente do que os cofres precisam, é meu dever entregar.}
{342}{}{Eu não sei ... não é o procedimento padrão de teste de cidadania?}
{343}{}{Eu não acho que sou o único para o trabalho ... adeus.}
{344}{}{Não, obrigado, eu realmente deveria ir. Bom dia, primeiro cidadão.}
{345}{lyn045}{Assassinos, ambos. Boyarsky foi exilado há dez anos, e Richard Moreau foi exilado
 Pouco depois de sairmos do Vault. A cidadania é uma confiança sagrada - o crime não é tolerado dentro dos nossos muros.}
{346}{}{Se este não for o Vault certo, então eu devo encontrar o que meu antepassado veio.}
{347}{}{Como uma pessoa se torna cidadã?}
{348}{}{Já ouvi o suficiente. Eu tenho que ir.}
{349}{}{Entendo. Bem, obrigado pelo seu tempo, First Citizen. Dia bom.}
{350}{lyn046}{Do que você está falando? Você deve estar enganado. Seja o que for ... "Vault Dweller" YOU'RE
 Falar de deve ser de algum outro Vault.}
{351}{}{Se isso for verdade, então preciso encontrar este outro Vault.}
{352}{}{Você mente! ESTE é o Vault do qual meu antepassado é!}
{353}{}{Talvez por isso. Obrigado por falar comigo. Adeus.}
{354}{lyn047}{Há uma cidade ... se você pudesse chamar isso ... ao nordeste da nossa cidade. Está preenchido
 Com ... criaturas que estão poluindo as águas subterrâneas com radiação perigosa.}
{355}{}{Como estão envenenando as águas subterrâneas?}
{356}{}{O que você quer que eu faça sobre isso?}
{357}{}{Pensando bem, isso não soa como algo em que eu estaria interessado. Tchau.}
{358}{lyn048}{Desative sua planta, de forma permanente, para que não possam causar mais danos.}
{359}{}{Soa bastante fácil. Eu voltarei quando a situação ... "resolvido".}
{360}{}{Como exatamente esta planta está liberando radiação?}
{361}{}{Deixe-me pensar sobre isso. Eu voltarei para você.}
{362}{lyn049}{Essas ... coisas ... estão operando uma planta de energia atômica danificada. Você vê, eles são
 Imune à radiação ... eles não se importam que eles lentamente nos matam com seus venenos.}
{363}{}{Eu cuidarei do problema. Eu voltarei quando a situação ... "resolvido".}
{364}{}{Parece que estão fazendo o mundo um serviço. Encontre algum outro "Estrangeiro" para fazer seu trabalho sujo.}
{365}{}{Eu vou ter que pensar sobre isso. Eu voltarei para você.}
{366}{lyn050}{Muito bem, deixe-me ver ... Estes ... são autênticos! Inacreditável ... você é um
 Sobrevivente de outro cofre! Bem-vindo à nossa Cidade ... você deve ter sofrido muito no mundo exterior.}
{367}{}{Eu preciso encontrar o Vault do meu povo.}
{368}{}{Preciso de um kit do Jardim do Éden. Você tem um?}
{369}{}{Oh, então agora sou bem-vindo em sua cidade? Esqueça isso ... Estou fora daqui.}
{370}{}{Você não tem idéia ... mas eu vou falar sobre o templo dos ensaios em algum outro momento. Adeus.}
{371}{lyn051}{Estou lhe dando uma oportunidade que alguns Outsiders já receberam. Você pode fazer o teste, se você
 desejo. Mas resolver esta situação para nós pode ser mais gratificante. Você me entende?}
{372}{}{All right then. Que tipo de situação?}
{373}{}{Compreendo. Independentemente do que os cofres precisam, é meu dever entregar.}
{374}{}{Eu não acho que sou o único para o trabalho ... adeus.}
{375}{}{Eu acho que realmente deveria ir. Bom dia, primeiro cidadão.}
{376}{lyn052}{Ah ... está certo. O Proconsul mencionou que ganhamos um novo cidadão. Bem vinda,
 Cidadão. Quanto aos arquivos, sim ... eles estão localizados dentro do nosso Vault. Perceba-os em seu lazer.}
{377}{}{Antes de examinar os arquivos, queria fazer algumas outras perguntas ...}
{378}{}{Você também tem um GECK?}
{379}{}{Ótimo! Obrigado.}
{380}{}{Obrigado, primeiro cidadão.}
{381}{lyn053a}{Sim? Com o que posso ajudá-lo?}
{382}{lyn053b}{Sim? O que é isso?}
{383}{}{Hunh?}
{384}{}{Valt! Valt!}
{385}{}{Olhos de Funnneee!}
{386}{}{Tchau tchau}
{387}{}{Tive algumas perguntas que eu queria lhe fazer.}
{388}{}{Tive algumas perguntas que eu queria lhe fazer.}
{389}{}{Como se torna um Citizen of Vault City?}
{390}{}{Tenho reconsiderado sua oferta de cidadania.}
{391}{}{Sobre a usina Gecko ...}
{392}{}{Tenho algumas informações sobre os invasores que atacaram a cidade.}
{393}{}{Descobri mais algumas informações sobre os invasores que estavam atacando a cidade.}
{394}{}{Eu encontrei algo no cofre de Bishop, você pode estar interessado.}
{395}{}{Eu acredito que o Dr. Troy está envolvido em algo ilegal.}
{396}{}{Eu devo falar com você na entrega desse disco holo.}
{397}{}{Eu mudei de ideia. Vou entregar esse disco holo para o Conselheiro na NCR.}
{398}{}{Nada. Lamento perturbá-lo.}
{399}{lyn054a}{Claro. Com o que posso ajudá-lo, cidadão?}
{400}{lyn054b}{Claro. Com o que posso ajudá-lo, capitão?}
{401}{}{O que você pode me falar sobre esses ataques Raider em nossa cidade?}
{402}{}{Eu encontrei este centro do cidadão, Thomas Moore. Quem é ele?}
{403}{}{Você tem um GECK?}
{404}{}{Estou procurando pelo Vault 13.}
{405}{}{Esta é Vault City? Por que você não mora em um cofre?}
{406}{}{Por que você tolera a escravidão?}
{407}{}{Nada hoje, obrigado.}
{408}{lyn055}{Para um não-cidadão, você certamente exige uma grande parte do meu tempo.}
{409}{}{Mas EU SOU Cidadão.}
{410}{}{Você tem um GECK?}
{411}{}{Estou procurando pelo Vault 13.}
{412}{}{O que eu preciso fazer para se tornar cidadão?}
{413}{}{Esta é Vault City? Por que você não mora em um cofre?}
{414}{}{Por que você tolera a escravidão?}
{415}{}{Deixa pra lá então. Dia bom.}
{416}{lyn056}{O que é isso?! Eu não tenho tempo para suas bobagens!}
{417}{}{Eu estava esperando que eu pudesse fazer outra pergunta.}
{418}{}{Peço desculpas pelos meus comentários anteriores, First Citizen. Eu fui
 Espero poder fazer algumas perguntas sobre o Vault City.}
{419}{}{Você sabe, existem marcas descafeinadas que sabem tão bom quanto o real.}
{420}{}{Deixa pra lá.}
{421}{}{Minhas desculpas, First Citizen. Lamento perturbá-lo.}
{422}{lyn057}{O que é isso? Você já não cuida deles?}
{423}{}{É um pouco mais complicado do que isso. Você vê esses caras não eram uma banda itinerante de invasores ...
 Eram mercenários.}
{424}{}{Deixa pra lá. Adeus.}
{425}{lyn058}{Não lembro de sua indução. Deixe-me ver seus documentos.}
{426}{}{Aqui está. Tudo deve estar em ordem.}
{427}{}{Umm ... Eu não tenho meus papéis comigo.}
{428}{}{Meus papéis? Eles ainda não foram processados. Eles deveriam estar encontrando sua mesa todos os dias agora.}
{429}{}{Meus papéis? Eles ainda não foram processados. Eles deveriam estar encontrando sua mesa todos os dias agora.}
{430}{lyn059}{Não brinque comigo, "Citizen", ou fico com certeza de que nunca mais caminhe pelas ruas da cidade de Vault. Agora vá embora.}
{431}{}{Não há problema ... Eu vou estar indo agora. Adeus.}
{432}{}{Bom dia, primeiro cidadão.}
{433}{lyn060}{Você me leva para um LIÇO? Se alguém soubesse que estas eram falsas, seria eu mesmo! Quem
 Te deu esses papéis ?! Se você me disser, eu permitirei que você mantenha seu Passe de Dia.}
{434}{}{Era um cidadão chamado Skeev no portão da frente.}
{435}{}{Eu, eu não lembro.}
{436}{}{Você terá que me pegar primeiro.}
{437}{lyn061}{Hmmmm ... muito bem. Mas não apareça novamente até que você tenha seus papéis Citizenship. Dia bom.}
{438}{}{Adeus.}
{439}{}{Bom dia, primeiro cidadão.}
{440}{lyn062}{Sério? Isso confirma minhas suspeitas. O acesso da Vault City agora é revogado. Mão
 Ao longo do seu Day Pass e vá com os meus guardas para o portão da frente.}
{441}{}{O que? Você disse que me deixaria manter meu Passe de Dia!}
{442}{}{Eu não estou indo a lugar nenhum. Você quer este Passe de Dia, você vem buscá-lo.}
{443}{}{Tudo bem, eu vou. Não quero problemas.}
{444}{lyn063}{Você tem? Então você vai parar o Gecko de contaminar nossa água? Por qualquer meio necessário?}
{445}{}{Sim, vou - em troca da Cidadania e acesso aos seus computadores do Vault.}
{446}{}{Não, na verdade não. Estava apenas a verificar se a oferta ainda estava aberta.}
{447}{lyn064}{Muito bem então. Informe-me quando terminar o trabalho e conceder-lhe-ei Cidadania.}
{448}{}{Posso fazer-lhe outra pergunta antes de eu ir?}
{449}{}{Tudo certo. Eu voltarei quando a situação for atendida.}
{450}{lyn065}{Você resolveu a situação?}
{451}{}{Descobri que tudo o que eles precisam para manter a fábrica corretamente é um regulador de magnetosfera hidrelétrica.}
{452}{}{A usina elétrica foi destruída. Se eu fosse você, eu me certificaria de que seu brahmin passasse no sudoeste a partir de agora.}
{453}{}{Eu cuidei da usina de Gecko. Você não deveria ter mais problemas com o vazamento de radiação.}
{454}{}{Não, ainda não. Eu ainda estou trabalhando nisso.}
{455}{lyn066}{Então não perca meu tempo. Retorne quando tiver algo a ser reportado.}
{456}{}{Tudo certo. Voltarei mais tarde.}
{457}{}{Muito bem. Bom dia, primeiro cidadão.}
{458}{lyn067a}{Então você não se preocupou com o problema?}
{459}{lyn067b}{Se você ainda quiser cidadania, é melhor lidar com isso.}
{460}{}{Como eu entendo, você tem a parte aqui em Vault City para consertar sua planta.}
{461}{}{Tudo certo. Voltarei mais tarde.}
{462}{}{Muito bem. Bom dia, primeiro cidadão.}
{463}{lyn068}{E se o fizermos? Essa é apenas uma solução temporária. FIXE o problema, NÃO o seu poder
 plantar. Estou me deixando claro?}
{464}{}{Primeiro cidadão, quero dizer, sem desrespeito, mas há uma maneira de resolver seu problema sem matar os ghouls
 Ou desligando seu reator. Agora, se eu pudesse obter a parte ...?}
{465}{}{Você disse que queria que eu consertei a planta, não o massacre Gecko.}
{466}{}{Cristal. Voltarei mais tarde.}
{467}{}{Sim. Bom dia, primeiro cidadão.}
{468}{lyn069a}{O que é isso ... criatura ... você tem com você ?! Tais ... as coisas não são permitidas dentro
 Vault City! Guardas! Acompanhe esses intrusos no portão da frente de uma só vez!}
{469}{lyn069b}{Ah, eu? Parece lembrar de você alegando que você era cidadão. Você não é mais
 Permitido dentro da Vault City. Meus guardas vão escoltá-lo até o portão da frente.}
{470}{lyn069c}{Eu já tive o suficiente de sua tolice! Você não está mais autorizado dentro da Vault City. Minhas
 Os guardas vão escoltá-lo até o portão da frente.}
{471}{}{Morra glazzeeeye!}
{472}{}{Uh-huh}
{473}{}{Você não gosta do meu amigo, hein? Isso é ruim. Porque ele gosta de você ... para JANTAR.}
{474}{}{Seus guardas não chegarão a tempo de salvar sua vida ... "Primeiro cidadão".}
{475}{}{Não há necessidade dos guardas - vou deixar pacificamente.}
{476}{lyn070}{O que? Você destruiu a fábrica ?! A contaminação! Seu idiota. Pelo menos, esses ghouls são
 Ido ... Saia da minha vista.}
{477}{}{Uau! E quanto a essa cidadania que você prometeu?}
{478}{}{Olha, causando muita destruição não foi fácil! Eu espero ALGUNS compensação ...}
{479}{}{Tudo bem, tudo bem. Estou indo embora.}
{480}{}{Bom dia, primeiro cidadão.}
{481}{lyn071}{Não brinque comigo, ou fico certo de que nunca mais caminhe pelas ruas de Vault City.}
{482}{}{You watch yourself, "First Citizen." Adeus.}
{483}{}{Bom dia, primeiro cidadão.}
{484}{lyn072a}{Você fez isso! Excelente! Você realizou um serviço valioso para a Vault City. Por favor
 Aceite isso como um sinal de nossa apreciação. Para pensar que uma banda de RAIDERS estava causando tantos problemas ...}
{485}{lyn072b}{Excelente. Não mais do que eles mereciam. Para pensar que uma banda de RAIDERS estava causando tantos problemas ...}
{486}{}{Bem, eles não eram realmente uma banda itinerante de invasores ... acabou por serem mercenários.}
{487}{lyn073}{Então você desativou sua planta?}
{488}{}{Não, reparei. O conselheiro McClure me deu a parte que eu precisava e isso foi suficiente para que a fábrica funcionasse corretamente.}
{489}{}{Está tudo cuidado.}
{490}{lyn074}{O que?! Ele fez?! Suponho que ele lhe concedeu cidadania, também! A fixação da planta de Gecko não
 Resolver qualquer coisa. Aqueles ... criaturas! Eles não podem ser confiáveis! O que acontece quando a planta começa a escorrer de novo ?!}
{491}{}{Eu não sei ... talvez AJUDE-os a corrigi-lo?}
{492}{}{Olhem, as águas subterrâneas já não estão sendo contaminadas, e ninguém se machucou. O problema está resolvido.}
{493}{}{Eu voltarei mais tarde, quando você se acalmou.}
{494}{}{Eu tenho que sair, First Citizen. Dia bom.}
{495}{lyn075}{É melhor você assistir seu passo nesta cidade, "Cidadão". Eu vou estar observando você. Um passo falso, e você será exilado.}
{496}{}{Isso faz isso. Ninguém me ameaça, especialmente uma cadela explodida com uma bengala na bunda. Hora de morrer.}
{497}{}{Comigo, Lynette e Vault City precisarão de um novo primeiro cidadão. Compreendo?}
{498}{}{Assim? Vou pegar a McClure para recuperar minha cidadania. Ele parece ser um material real do primeiro cidadão.}
{499}{}{Eu voltarei mais tarde, quando você se acalmou.}
{500}{}{Bom dia, primeiro cidadão.}
{501}{lyn076a}{Excelente. Você se conduziu como um verdadeiro Cidadão do Vault.}
{502}{lyn076b}{Tenho o prazer de conceder-lhe Cidadania, com privilégios e acesso às nossas instalações.}
{503}{}{Ei, eu estava esperando obter alguma compensação monetária.}
{504}{}{No problem. Just doing my job. Adeus.}
{505}{}{Foi um prazer, primeiro cidadão. Dia bom.}
{506}{}{Ótimo, obrigado. Eu vou verificá-los agora.}
{507}{}{Agradeço tudo o que você fez por mim, First Citizen. Dia bom.}
{508}{lyn077ab}{Você já recebeu muito, Outsider. A cidadania é sua própria recompensa.}
{509}{lyn077b}{A cidadania é sua própria recompensa.}
{510}{}{Como o inferno! Algum dinheiro melhor mude de mãos agora, ou a Vault City vai precisar de um novo primeiro cidadão.}
{511}{}{No problem... I was just curious. Adeus.}
{512}{}{Muito bem, primeiro cidadão. Dia bom.}
{513}{lyn077_a}{Absolutamente não.}
{514}{}{Eu me pergunto quem vai assumir o controle depois que você está morto ... em cerca de um minuto a partir de agora.}
{515}{}{No problem... Thought I'd give it a try. Adeus.}
{516}{lyn078}{Dr. Troy ?! O que te faz dizer isso?}
{517}{}{Ele me pediu para contrabandear alguns chems ilegais na cidade.}
{518}{}{Ele só administra cicatrização para Cidadãos.}
{519}{}{Nada ... eu falo mal. Dia bom.}
{520}{lyn079}{Quem você está acusando um cidadão de tais crimes? Guardas! Escort este Outsider para os portões!}
{521}{}{Seus guardas não chegarão a tempo de salvar sua vida ... "Primeiro cidadão".}
{522}{}{Não há necessidade dos guardas - vou deixar pacificamente.}
{523}{}{Mas é a verdade! Você tem que acreditar em mim! Eu tenho pr -!}
{524}{lyn080}{Essa é uma acusação muito séria. Como você é cidadão, eu devo levá-lo à sua palavra ...
 Mas você está absolutamente certo? Se fosse verdade, sua cidadania seria revogada e ele seria exilado.}
{525}{}{Olha, eu sei que é difícil para você acreditar, mas ele me pediu para contrabando Jet na Cidade do Vault para ele.}
{526}{}{Não é um pouco áspero? Você não pode apenas reabilitá-lo e mantê-lo como médico?}
{527}{}{Oh. Uh ... eu falo mal. Eu quis dizer que o Dr. Troy está envolvido em atividades PARALEGAL, não ilegais.}
{528}{}{Hmmmm. Eu vou ver se eu posso encontrar qualquer outra coisa.}
{529}{lyn081}{Não posso acreditar que um cidadão de tal estatura se tornará viciado em drogas. Obrigado pelo seu
 Honestidade, cidadão. Eu vou cuidar disso imediatamente.}
{530}{}{Tive algumas outras questões ...}
{531}{}{Great. The entire situation had me concerned. Adeus.}
{532}{}{Obrigado, primeiro cidadão. I only wanted to see justice carried out.}
{533}{lyn082a}{Informe-me de uma só vez se você descobrir algo mais.}
{534}{lyn082b}{Vault City prevalece, Citizen.}
{535}{}{Tive algumas outras questões ...}
{536}{}{Sure. Adeus.}
{537}{}{I will. Obrigado, primeiro cidadão.}
{538}{lyn083}{A lei é a lei. As exceções não nos tornam melhores do que os Outsiders. Mais uma vez, você está
 Absolutamente certo de suas acusações?}
{539}{}{Então, subornando-me para resolver a sua situação de Gecko com os documentos da Cidadania ... isso é legal?}
{540}{}{Sim. Ele me pediu para contrabandear Jet para Vault City para ele.}
{541}{}{Oh. Uh ... eu falo mal. Eu quis dizer que o Dr. Troy está envolvido em atividades PARALEGAL, não ilegais.}
{542}{}{Hmmmm. Eu vou ver se eu posso encontrar qualquer outra coisa.}
{543}{lyn084a}{É melhor ver o que você diz.}
{544}{lyn084b}{É melhor ver o que você diz, Outsider.}
{545}{lyn084c}{Se eu souber de você causar problemas para o Dr. Troy, ou qualquer outro cidadão, você nunca andará
 As ruas de Vault City novamente. Entendido?}
{546}{}{Uh...s ure. Sorry. Tive algumas outras questões ...}
{547}{}{Claro como cristal. Eu vou estar indo agora.}
{548}{}{Minhas desculpas, First Citizen. Dia bom.}
{549}{lyn085}{DE CURSO ele só trata os cidadãos. Ele não tem tempo para tratar Outsiders ... nós temos um Auto Doc
 No pátio por isso.}
{550}{}{Bem, você pode querer saber que o médico me pediu para contrabando alguns chems ilegais para a cidade.}
{551}{}{Oh. Look, Tive algumas outras questões ...}
{552}{}{Sim, para aqueles que podem pagar ... e isso é assumir que eles saem do Autodoc de uma só peça.}
{553}{}{All right, never mind then. Adeus.}
{554}{}{Minhas desculpas, First Citizen. Dia bom.}
{555}{lyn086}{Eu acredito que é hora de você ter deixado. Eu sugiro que você fique sua estadia em Vault City curta.}
{556}{}{Antes de ir, tive mais algumas perguntas ...}
{557}{}{Tudo certo. Estou indo embora.}
{558}{lyn087}{Moore? Ele é um perturbador. É o que ele é.}
{559}{}{Você está certo. Ele tem ... interesses externos.}
{560}{}{Por que você diz que ele é um problemático?}
{561}{}{Posso fazer-lhe outra pergunta?}
{562}{}{Falei com ele ... e muito do que ele diz faz sentido.}
{563}{}{Concordo. Você quer que eu ... cuide dele?}
{564}{}{Você deve revogar sua cidadania, então.}
{565}{}{Entendo. Certamente ficarei claro dele então. Dia bom.}
{566}{lyn088}{Ele procura constantemente convencer os Cidadãos a transformar a cidade de Vault em uma ... "democracia"
 Como ele o chama, com todos os que participam das leis e da tomada de decisões. * Eu * chamo isso de regra mob.}
{567}{}{"Democracia?"}
{568}{}{Como ele tenta convencer os Cidadãos?}
{569}{}{Ele parece um problema. Que tal eu ... cuidar dele?}
{570}{}{Você não pode simplesmente expulsá-lo?}
{571}{}{Tive algumas outras questões ...}
{572}{}{Oh. Bem, obrigado pela informação. Dia bom.}
{573}{lyn089}{Os arquivos afirmam que muitas nações do velho mundo tinham esse governo. Nós sabemos onde isso
 Obteve-os. Você pode imaginar quanto tempo demoraria para fazer algo em tal sociedade? É inconcebível.}
{574}{}{Inconcebível? Por quê?}
{575}{}{Como Moore tenta convencer os Cidadãos?}
{576}{}{Tive algumas outras questões ...}
{577}{}{Eu suponho que sim. Eu tenho que ir.}
{578}{}{Obrigado pelo seu tempo, First Citizen. Dia bom.}
{579}{lyn090}{Um governo precisa de um líder forte e capaz que possa tomar decisões rapidamente e tem o
 Poder para impô-los. O governo por comitê não é um tipo de governo.}
{580}{}{Como Moore tenta convencer os Cidadãos de que Vault City deve ser uma democracia?}
{581}{}{Tive algumas outras questões ...}
{582}{}{Eu suponho que sim. Eu tenho que ir.}
{583}{}{Obrigado pelo seu tempo, First Citizen. Dia bom.}
{584}{lyn091}{Principalmente, se libertando em público e fazendo um tolo de si mesmo. Ele toca com nossas simpatias com
 Contos de uma praga na NCR, como se NÓS pudéssemos cuidar do mundo inteiro.}
{585}{}{Parece um problema real. Você quer que eu ... cuide dele?}
{586}{}{Você sabe que ele está certo: você provavelmente poderia. Sua tecnologia médica é bastante impressionante.}
{587}{}{Você não pode simplesmente expulsá-lo?}
{588}{}{Oh. Bem, eu estava curioso sobre ele. Dia bom.}
{589}{lyn092}{Você também? Um cidadão é livre de suas próprias crenças, mas isso ... ESTE! Talvez você seja incapaz
 De responsabilidade da Cidadania!}
{590}{}{Whoa ... desculpe! Olha, não importa ... Eu tive algumas outras perguntas que queria te perguntar ...}
{591}{}{Se isso significa concordar cegamente com você, então talvez você seja o único incapaz de assumir a responsabilidade da Cidadania.}
{592}{}{Thomas Moore é um cidadão, e ele é o líder desse movimento.}
{593}{}{Esta é uma nova era, é hora da mudança.}
{594}{}{Lamento que você se sinta assim. Tchau.}
{595}{lyn093}{Não. Ele não é um cidadão VERDADEIRO ... não mais. Quando ele veio até nós dois anos atrás, ele parecia
 Tudo o que queremos em um cidadão. Mas apenas um ano depois ele ... mudou. Ele se virou contra nós.}
{596}{}{Você sabe, isso explicaria algumas coisas. Moore provavelmente estava apenas desempenhando um papel por um tempo.}
{597}{}{Talvez seja hora de uma mudança.}
{598}{}{Lamento que você não considere Moore como um "verdadeiro" cidadão. Talvez você deva examinar o que significa
 Seja um cidadão.}
{599}{}{Talvez ele apenas visse a luz. Dia bom.}
{600}{lyn094}{Nós prosperamos neste mundo, onde muitos outros falharam, e você me diz que precisamos
 mudar? Olhe para o mundo exterior! Anarquia, depravação, doença ... Vault City é um paraíso!}
{601}{}{É exatamente por isso que é necessária uma mudança. Você deve compartilhar suas realizações com outras pessoas.}
{602}{}{É um paraíso para algumas pessoas, talvez. Eu acho que seus escravos não concordariam.}
{603}{}{I'm not going to argue this with you anymore. Adeus.}
{604}{lyn095}{Vault City foi construído através do trabalho árduo e do sofrimento de muitos cidadãos. O lado de fora
 O mundo deve olhar para o nosso exemplo e segui-lo, não se sentar fora de nossos muros e implorar por folhetos.}
{605}{}{O trabalho árduo de Citizens? Em todo lugar que eu vou na sua cidade, vejo o verdadeiro trabalho feito pelos escravos.}
{606}{}{I'm not going to argue this with you anymore. Adeus.}
{607}{lyn096}{Por que defendemos a escravidão? O sistema está em vigor há muitos anos e funciona
 muito bem. Ambas as partes se beneficiam da instituição.}
{608}{}{I see. Posso fazer-lhe outra pergunta?}
{609}{}{Tenho certeza de que seus escravos não concordariam.}
{610}{}{Mas ... você compra e vende seres humanos como brahmin. Não mantém os escravos incomodando você?}
{611}{}{Já ouvi o suficiente. Adeus.}
{612}{}{Obrigado pelo seu tempo, First Citizen. Dia bom.}
{613}{lyn097}{Eles não são escravos, eles são nossos "servos". Nós lhes damos casas, comida, roupas,
 E um propósito. Nós lhes demos uma vida.}
{614}{}{Certo. Por que ser livre quando eles poderiam trabalhar para você?}
{615}{}{Olhe, não importa quais palavras de som que você usa para cobrir o fedor, ainda é escravidão.}
{616}{}{Uh... sure. Look, Tive algumas outras questões ...}
{617}{}{I'm not going to argue this with you anymore. Adeus.}
{618}{}{Hmmmm. Eu não tinha considerado isso antes. Eu vou ter que pensar nisso.}
{619}{lyn098}{Sua hipocrisia é bastante notável. Você tem a marca do Slaver's Guild, mas você não concorda com a escravidão.}
{620}{}{Eu não discordo da escravidão, apenas estou apontando que eles fazem todo o trabalho real por aqui.}
{621}{}{Olha, eu tenho a marca apenas para obter alguma informação ... Não sou escravista.}
{622}{}{Eu era jovem ... eu precisava do dinheiro ...}
{623}{}{I'm not going to argue this with you anymore. Adeus.}
{624}{lyn099}{O que você quer dizer?}
{625}{}{Moore está realmente trabalhando para a Nova República da Califórnia.}
{626}{}{Never mind. Tive algumas outras questões ...}
{627}{}{Nothing.  I have to be going. Adeus.}
{628}{}{Nothing. I misspoke. Bom dia, primeiro cidadão.}
{629}{lyn100}{Mate ele?! O assassinato não é de nenhuma maneira, forma ou forma permitida na Cidade do Vault - mesmo que seja o melhor. Nunca mais fale sobre isso.}
{630}{}{Entendido. Posso fazer algumas outras perguntas?}
{631}{}{Olhe, "assassinato" é uma palavra tão feia. Eu poderia organizar algum tipo de acidente. . . Uma sobredosagem química,
 Mauled por um brahmin ... qualquer uma das várias coisas pode acontecer neste mundo perigoso.}
{632}{}{Tudo certo. Estou indo embora.}
{633}{}{Muito bem, primeiro cidadão. Dia bom.}
{634}{lyn101}{Esta não é uma conduta de um cidadão! Estou revogando sua Cidadania. Meus guardas vão te mostrar o portão da frente.}
{635}{}{Seus guardas não chegarão a tempo de salvar sua vida ... "Primeiro cidadão".}
{636}{}{Não há necessidade dos guardas. Eu vou deixar pacificamente.}
{637}{lyn102}{Embora sirva os interesses da Vault City, não posso ... desde que ele não quebre nenhuma lei,
 Moore tem permissão para dizer o que quiser.}
{638}{}{Você quer que eu ... cuide dele?}
{639}{}{Ah, mas ele tem. Você vê, Moore não é apenas um cidadão ... ele está cuidando dos interesses de outra pessoa.}
{640}{}{Posso fazer-lhe outra pergunta?}
{641}{}{Bem, ele provavelmente vai enterrar-se à taxa que ele está indo. Falo com você mais tarde.}
{642}{}{Compreendo. Bem, obrigado pelo seu tempo, First Citizen.}
{643}{lyn103}{Um espião para a NCR? Isso ... que ... explicaria muitas coisas. Obrigado, cidadão. Eu
 Vai lidar com isso imediatamente.}
{644}{}{Tive algumas outras questões ...}
{645}{}{Great, thanks. Adeus.}
{646}{}{Obrigado, primeiro cidadão.}
{647}{lyn104}{Eles começaram há vários meses. As torres laser foram capazes de segurá-las, mas eu
 Não sei quanto tempo mais podemos detê-los.}
{648}{}{Quem são esses incursores?}
{649}{}{Tive algumas outras questões ...}
{650}{}{I have to be going. Adeus.}
{651}{}{I'm sorry to hear that; perhaps they will go elsewhere in search of easier targets. Bom dia, primeiro cidadão.}
{652}{lyn105}{Lixo do Outsider. Por mais de um século, os Estranhos tentaram saquear nossa cidade ... e ter
 Sempre falhou. Eventualmente, vamos vencer esse grupo.}
{653}{}{Uh ... "eventualmente?" Por que você não os apagou já?}
{654}{}{Posso fazer-lhe outra pergunta?}
{655}{}{I have to be going. Adeus.}
{656}{}{I have to go. Bom dia, primeiro cidadão.}
{657}{lyn106}{Encontrar a base deles provou ser difícil. Além disso, eles também têm uma grande quantidade de
 potência de fogo. No entanto, repelimos cada ataque ... com baixas mínimas.}
{658}{}{Posso fazer-lhe outra pergunta?}
{659}{}{I have to be going. Adeus.}
{660}{}{Obrigado pelo seu tempo. Bom dia, primeiro cidadão.}
{661}{lyn107}{O que é isso?}
{662}{}{Encontrei sua base. Eles estão escondidos em uma série de cavernas no sopé do sul.}
{663}{}{Limpei-os. Eles estavam escondidos em uma série de cavernas no sopé do sul.}
{664}{}{A informação tem seu preço.}
{665}{}{Deixa pra lá. I have to be going.}
{666}{lyn108}{Você tem? Excelente! Mas os guardas da cidade já estão esticados ... E você?
 Você poderia acabar com os ataques? Eu te pagarei.}
{667}{}{Não, estou muito ocupado no momento.}
{668}{}{Verei o que posso fazer.}
{669}{lyn109}{Muito bem. Se você me desculpa, também estou muito ocupado. Você pode encontrar sua própria saída.}
{670}{}{Eu tive algumas outras perguntas que eu queria lhe fazer primeiro ...}
{671}{}{Tudo bem, vou embora.}
{672}{}{Muito bem. Bom dia, primeiro cidadão.}
{673}{lyn110a}{Mercenários? Quem os contratou?}
{674}{lyn110b}{Sim, acredito que você tenha mencionado isso antes. Você sabe quem os contratou?}
{675}{}{Eu aposto que era a Bishop Family in New Reno.}
{676}{}{A Bishop Family in New Reno.}
{677}{}{Eu ainda não tenho certeza. Ainda estou olhando para ele.}
{678}{lyn111a}{O que?! Como você sabe disso? Que provas você tem?}
{679}{lyn111b}{Você tem alguma evidência?}
{680}{}{Eu não tenho nenhuma prova real, mas a palavra em New Reno é que os Bispos estão por trás disso.}
{681}{}{Encontrei este livro de contas nos pagamentos de cotações seguras dos invasores do Bishop por um período de três meses
 Campanha de terror contra a sua cidade ... uh, com opções para extensões de um mês se você fosse teimoso.}
{682}{}{Eu realmente não tenho nenhuma prova difícil. Eu ainda estou trabalhando nisso.}
{683}{lyn112}{Eu não ficaria surpreso. O Bispo visitou a cidade de Vault há pouco tempo, e sugeriu uma
 aliança. Eu recusei, é claro. Não nos associamos com criminosos.}
{684}{}{Talvez essa fosse sua maneira de forçá-lo a uma aliança.}
{685}{lyn113}{Preferiria pedir ajuda à NCR. Se você se deparar com qualquer prova difícil de Bishop's
 Envolvimento, por favor me trate de uma só vez.}
{686}{}{Fair enough. Tive algumas outras questões ...}
{687}{}{Se eu descobrir qualquer coisa, eu vou deixar você saber.}
{688}{}{Eu farei, First Citizen. Dia bom.}
{689}{lyn114}{Não estou surpreso. O bispo visitou não há muito tempo e sugeriu uma aliança. Eu recusei, de
 curso. Não nos associamos com criminosos.}
{690}{}{Eu acho que ele esperava isso. Encontrei este holodisc no cofre de Bishop. Ele foi contratado pela NCR para obter
 Vault City para se juntar à República. Quando você recusou sua oferta, ele contratou os mercenários para atacar você
 Então você pediu ajuda à NCR.}
{691}{}{Talvez essa fosse sua maneira de forçá-lo a uma aliança.}
{692}{lyn115}{Possivelmente ... mas nunca funcionaria. Preferiria pedir ajuda à NCR. Você fez o Vault
 Cidade um ótimo serviço. Por favor, tome isso como um sinal de nossa apreciação.}
{693}{}{Obrigado. Tive algumas outras questões ...}
{694}{}{Se eu ouvir algo mais, eu vou deixar você saber.}
{695}{}{Meu prazer, First Citizen. Dia bom.}
{696}{lyn116}{Claro. Eles enviaram mercenários para assassinar meu povo porque eu não iria se juntar aos seus
 governo? Eu ... mal posso acreditar nisso.}
{697}{}{É ainda mais complicado. Thomas Moore também está envolvido.}
{698}{}{Existe alguma coisa que eu possa fazer para ajudar?}
{699}{}{É um mundo difícil. De qualquer forma, sobre a compensação -}
{700}{lyn117}{Esta não é a conduta de um cidadão. Mas eu preciso dessa informação. Qual é o seu preço?}
{701}{}{$ 100}
{702}{}{$ 200}
{703}{}{$ 400}
{704}{}{$ 500}
{705}{}{Deixa pra lá. Vou contar-lhe as informações que tenho de graça.}
{706}{lyn118}{Muito bem, aqui está o seu dinheiro. Agora me diga o que você sabe.}
{707}{}{Encontrei sua base. Eles estão escondidos em uma série de cavernas no sopé do sul.}
{708}{}{Limpei-os. Eles estavam escondidos em uma série de cavernas no sopé do sul.}
{709}{}{Na verdade, eu realmente não sei muito de nada.}
{710}{}{Obrigado pelo dinheiro. Eu tenho que ir agora.}
{711}{lyn119}{Preciso que você vá imediatamente para a Nova República da Califórnia e encontre o Conselheiro Oestein,
 Roger Oestein. Dê-lhe o disco holo. Isso deve garantir que não mais "incursores" sejam contratados.}
{712}{}{Uh ... você não ouviu? O Oestein está morto. Quero dizer, ele teve um acidente. Um mortal. É uma longa história.}
{713}{}{Espere um minuto. Ir para a NCR? Não foram eles responsáveis   por tudo isso?}
{714}{}{Tudo bem, eu vou fazer isso.}
{715}{}{Não, obrigado. Estou tão ocupado como está.}
{716}{lyn120}{Roger Oestein foi provavelmente o único homem honesto da Nova República e um simpático
 Para a nossa causa ... a sua morte é uma perda terrível.}
{717}{}{Sim, ele era um velho e resistente. Bom cara. Muitos pontos de vida. Então ... eu ainda recebo uma recompensa por
 Encontrando toda essa informação para você, ou ...?}
{718}{}{Sim, lamento também falar sobre isso. Era como se eu o visse ontem.}
{719}{lyn121a}{Lembro-me já de pagar por informações sobre esses "incursores". Você foi compensado. Agora vá embora.}
{720}{lyn121b}{Sim, sim ... você fez muito bem. Por favor ... faça isso como uma recompensa.}
{721}{}{Nenhuma recompensa?! Descobrir toda essa besteira política não foi uma tarefa fácil. Eu acho que eu mereço algo extra, não é ?!}
{722}{}{Hold on, I'm not done yet. Tive algumas outras questões ...}
{723}{}{Tudo bem, vou embora.}
{724}{}{Obrigado. Tive algumas outras questões ...}
{725}{}{Ótimo! Obrigado...I better be going now.}
{726}{}{Obrigado, primeiro cidadão.}
{727}{lyn122}{Roger Oestein é provavelmente o único homem honesto da Nova República e simpatizante da nossa causa.}
{728}{}{Tudo bem, vou entregar o disco para ele.}
{729}{}{Não, obrigado. Estou muito ocupado agora.}
{730}{lyn123}{O seu patriotismo não será desprezado. Agora apressar-se. Tempo é essencial.}
{731}{}{Before I go, Tive algumas outras questões ...}
{732}{}{Estou com isso.}
{733}{}{Você pode contar comigo, First Citizen. Eu irei depois que eu entreguei o disco para o Oestein.}
{734}{lyn124}{No entanto, Vault City prevalecerá. Você realizou um serviço valioso ...
 Aceite esse sinal de nossa apreciação.}
{735}{}{Obrigado. Tive algumas outras questões ...}
{736}{}{Ótimo! Obrigado... I better be going now.}
{737}{}{Obrigado, primeiro cidadão.}
{738}{lyn125}{Você entregou?}
{739}{}{Não. Eu estava pensando, qual é a recompensa de que você falou?}
{740}{}{Não, estou muito ocupado para entregar o disco.}
{741}{}{Não, ainda não. Mas eu tive algumas perguntas ...}
{742}{}{Entreguei o disco ao Conselheiro Oestein.}
{743}{}{Ainda não. Eu voltarei quando eu fizer.}
{744}{}{Ainda não, First Citizen. Voltarei quando entregasse a Oestein.}
{745}{lyn126}{Você irá?! Excelente! Pegue o disco que obteve de Bishop e apresse-se. Tempo é essencial.}
{746}{}{Before I go, Tive algumas outras questões ...}
{747}{}{Estou com isso.}
{748}{}{Você pode contar comigo, First Citizen. Eu irei depois que eu entreguei o disco para o Oestein.}
{749}{lyn127}{Acredite, não ficará desapontado. Agora entregue esse disco Holo.}
{750}{}{Before I go, Tive algumas outras questões ...}
{751}{}{All right. Estou com isso.}
{752}{}{Você pode contar comigo, First Citizen. Eu irei depois que eu entreguei o disco para o Oestein.}
{753}{lyn128}{Posso ver que o nosso acordo não significou nada para você. Muito bem então; Privilégios da sua Vault City
 São revogadas. Meus guardas vão escoltá-lo até o portão da frente.}
{754}{}{Eu matarei aqueles guardas ... depois de eu te matar.}
{755}{}{OK! Aqui, pegue o disco e irei.}
{756}{lyn129}{Obrigado! Você fez um excelente serviço! Oestein enviou correspondência?}
{757}{}{Sim, estou começando a me sentir como o Postman. Aqui, ele queria que eu desse este disco.}
{758}{}{Não, eu perdi.}
{759}{}{Não, ele nunca me deu uma.}
{760}{lyn130a}{Excelente. Deixe-me analisar isso.}
{761}{}{Desligue 3 segundos}
{762}{lyn130b}{Não teremos problemas com a NCR por muito tempo.}
{763}{}{São boas notícias.}
{764}{lyn131}{Agora ... em relação ao pagamento: relatório para Randal, o Chief Amenities Officer. Diga-lhe que enviei
 Você, e ele irá apresentá-lo com sua recompensa. Obrigado novamente.}
{765}{}{Before I go, Tive algumas outras questões ...}
{766}{}{Tudo certo. Recompensa, aqui eu venho.}
{767}{}{Obrigado, primeiro cidadão. Dia bom.}
{768}{lyn132}{O seu serviço tem sido exemplar. Tanto que é minha honra nomear você Capitão da
 Guarda. Parabéns, capitão. Você merece isso.}
{769}{}{Uh ... obrigado.}
{770}{}{Obrigado, primeiro cidadão.}
{771}{lyn133}{Além disso, informe ao Randal, o Chief Amenities Officer. Diga-lhe que mandei você, e
 Receba sua recompensa. Estamos em sua dívida ... Capitão.}
{772}{}{Before I go, Tive algumas outras questões ...}
{773}{}{Tudo certo. Recompensa, aqui eu venho!}
{774}{}{Obrigado, primeiro cidadão. Dia bom.}
{775}{lyn134}{Você perdeu?! Essa correspondência foi extremamente importante! Muito bem ... aqui está seu
 Pagamento pela entrega do disco. Agora, se você me desculpar ...}
{776}{}{Hold on a minute. Before I go, Tive algumas outras questões ...}
{777}{}{Até logo.}
{778}{}{Bom dia, primeiro cidadão.}
{779}{lyn135}{Ele não lhe deu nada? Estranho ... em qualquer caso, aqui está o seu pagamento pela entrega
 O disco. Agora, se você me desculpar ...}
{780}{}{Hold on a minute. Before I go, Tive algumas outras questões ...}
{781}{}{Até logo.}
{782}{}{Bom dia, primeiro cidadão.}
{783}{lyn136}{O que é isso?}
{784}{}{Encontrei este holodisc no cofre de Bishop. Ele foi contratado pela NCR para obter Vault City para se juntar ao
 República. Quando você recusou sua oferta inicial, ele contratou os mercenários para atacá-lo para que você perguntasse
 NCR para obter ajuda.}
{785}{lyn099}{O que você quer dizer?}
{786}{}{Moore está realmente trabalhando para a Nova República da Califórnia.}
{787}{lyn138}{Um espião para a NCR? Isso ... que ... explicaria muitas coisas. Obrigado por expor
 Isso, cidadão. A esse problema, eu posso cuidar imediatamente.}
{788}{}{Sobre o problema NCR ... existe alguma coisa que eu possa fazer para ajudar?}
{789}{}{Isso é bom para ouvir. De qualquer forma, por descobrir todas essas coisas sobre Reno e NCR, eu queria saber se havia uma rew -}

# Generic line from 790 to 846 are not used. If this changes, we will need to do the lip-syncing and attach voc files.
{790}{}{Guardas!}
{791}{}{Por favor, veja o Proconsul. Ele terá o que você precisa.}
{792}{}{Por favor, consulte o Conselheiro Sénior McClure. Ele terá o que você precisa.}
{793}{}{Por favor, veja meu assistente. Ele terá o que você precisa.}
{794}{}{Norte}
{795}{}{Sul}
{796}{}{Leste}
{797}{}{Oeste}
{798}{}{Nortewest}
{799}{}{Norteeast}
{800}{}{Sulwest}
{801}{}{Suleast}
{802}{}{To the Norte}
{803}{}{To the Sul}
{804}{}{To the Leste}
{805}{}{To the Oeste}
{806}{}{To the Nortewest}
{807}{}{To the Norteeast}
{808}{}{To the Sulwest}
{809}{}{To the Suleast}
{810}{}{Eu não quero isso.}
{811}{}{Obrigado.}
{812}{}{Obrigado pelo seu tempo.}
{813}{}{Guardas!}
{814}{}{Eu amo Scott Rodenhiser.}
{815}{}{Meus pequenos dreadlocks são fofos.}
{816}{}{T-Ray pensa um pouco demais em si mesmo.}
{817}{}{Esta é uma boa notícia.}
{818}{}{Muito bem.}
{819}{}{Dia bom.}
{820}{}{Bom dia, cidadão.}
{821}{}{Vou ficar com isso.}
{822}{}{Me dê isso.}
{823}{}{Não sei nada sobre isso.}
{824}{}{Eu não sei.}
{825}{}{Sim.}
{826}{}{Não.}
{827}{}{Certamente.}
{828}{}{Claro.}
{829}{}{Um lugar para outro.}
{830}{}{Exatamente.}
{831}{}{Certo.}
{832}{}{Hmpphhh.}
{833}{}{Explique-me novamente porque Fallout 2 não tem modelos de heróis pretos?}
{834}{}{Vault City prevalece.}
{835}{}{Vault City prevalece, Citizen.}
{836}{}{Oh garoto! Dormir! É lá que eu sou um Viking!}
{837}{}{Degenerar!}
{838}{}{Outsider}
{839}{}{Outsider filth ...}
{840}{}{* Snorts *}
{841}{}{* Zzzzzzzzzzz *}
{842}{}{O que está contida no disco deve interromper-se; Os incursores foram expostos e, se
 O conteúdo do disco deveria sair para os distritos exteriores da NCR, eles nunca mais seriam confiáveis.}
{843}{}{Minhas fontes no Gecko me asseguram que ainda existem ghouls dentro da cidade. Sua cidadania
 Depende de resolver esta situação ... completamente. Estou me deixando claro?}
{844}{}{Desculpe, pensei ter matado todos eles.}
{845}{}{Esse é um bom começo, mas nossas águas subterrâneas ainda estão contaminadas. Você precisa desativar
 Sua planta.}
{846}{}{Isso ajuda, mas isso não para o nosso principal problema: a contaminação das águas subterrâneas.
 Você precisa impedir que a planta escape de radiação.}
# End of Unused Dialog

{847}{}{O Ancião da minha aldeia me deu uma garrafa de água, mas não tenho isso comigo. Ainda assim, as histórias
 O Ancião nos disse que disse que meu antepassado era de um cofre.}
{848}{}{Você quer dizer os ghouls? Sim, descobri o que há de errado com a planta.}
{849}{}{A planta precisa de um hidro-ímã, uh, thingy para fazê-lo funcionar. Os ghouls
 Disse que você tinha um aqui, então eu só preciso disso, e eles podem fazer a planta limpa.}
{850}{}{Eles precisam de um regulador de magnetosfera hidrelétrica para consertar a planta e
 Evite que ele polua as águas subterrâneas. Eles afirmam ter um aqui em Vault City. Então, se eu pudesse
 Pegue a parte ...}
{851}{}{Deixa pra lá. Podemos falar sobre isso em algum outro momento.}
{852}{lyn047b}{E se o fizermos? Essa é apenas uma solução temporária.}
{853}{}{Bem, eu não conheço os detalhes, mas parece que o magneto-thingie pode ajudar os dois
 Gecko e Vault City. Posso obter o papel?}
{854}{}{Na verdade, o regulador poderia fazer a fábrica funcionar durante vários anos. Então, se eu pudesse obter a parte ...?}
{855}{}{Deixa pra lá. Talvez eu possa encontrar alguém para me ajudar.}
{856}{}{Você está certo, First Citizen. Eu vou ver o que posso fazer para lidar com esse problema sozinho.}
{857}{}{Eu não acho que eu entendo. Existe algum problema com Gecko ... ou com os ghouls?}
{858}{}{Primeiro cidadão, ouça-me ... tem algum problema em conseguir a parte? Poderia
 Resolva seus problemas com Gecko e ajude os ghouls também ...}
{859}{}{Deixa pra lá. Maybe I can find someone else to help me.}
{860}{}{Desculpe por perturbá-lo, First Citizen.}
{861}{}{Eles não estão tentando machucar ninguém. Eles simplesmente não têm a parte que precisam fazer
 A fábrica corre limpa. Então, se você pudesse me dar a parte ...}
{862}{}{Deixa pra lá. Talvez eu possa encontrar alguém para me ajudar.}
{863}{}{Muito bem. Sorry to disturb you, First Citizen.}
{864}{lyn017b}{Você entra em minhas câmaras e então tem a audácia de fazer exigências de ME, Lynette, First Citizen of Vault City ?!}
{865}{lyn041c}{Agora, saia imediatamente, ou eu chamarei os guardas.}
{866}{}{Isso faz isso. Você está com muita necessidade de uma lição dolorosa.}
{867}{}{Deixa pra lá. Talvez eu possa encontrar alguém para me ajudar.}
{868}{}{Desculpe por perturbá-lo, First Citizen.}
{869}{}{Preciso de uma parte para consertar a usina Gecko.}
{870}{}{You delivered Oestein's holodisk to Lynette.}
{871}{}{You delivered Oestein's holodisk to Lynette and became Captain of the Guard.}
{872}{}{Você aniquilou os incursores e ajudou a Vault City.}
{873}{}{Você expôs Moore como um espião para a NCR.}
{874}{}{Você provou que Bishop contratou os incursores.}
{875}{}{Você provou que Bishop foi contratado pela NCR.}
{876}{}{Eu preciso de um para salvar meu -}
{877}{}{Espere um segundo --}
{878}{}{Esqueça isso. Estou indo embora.}
{879}{}{Parece que estou desperdiçando meu tempo com você também. Talvez seja melhor você ir buscar alguém que possa me ajudar.}
{880}{}{Sorry to bother you, then. Adeus.}
{881}{}{Isso é bom para ouvir. Assim...?}
{882}{}{Obrigado, primeiro cidadão.}
{883}{}{Uh, foi meu erro ... Eu não queria dizer -}
{884}{}{Minhas desculpas, First Citizen. EU --}
{885}{}{Guardas!}
