{100}{}{Você vê Val. Ou Valerie. Como queiras.}
{101}{}{Você vê uma mulher de cabelos castanhos vestida de uniforme marrom e armadura de metal. Ela parece um mecânico.}
{102}{}{Você vê Val. Ou Valerie. Como queiras.}
{103}{}{Você vê uma mulher de cabelos castanhos vestida de uniforme marrom e armadura de metal. Ela parece um mecânico.}
{104}{}{Oh, olá, "papai".}
{105}{}{1 segundo}
{106}{}{Valerie. Bom te ver de novo.}
{107}{}{Oh, oi, pai. É bom te ver. Mesmo.}
{108}{}{1 segundo}
{109}{}{Olá, Valerie. É bom ver você também.}
{110}{}{É melhor tirar esse mutante daqui antes que os guardas vejam isso.}
{111}{}{É melhor tirar esse ghoul daqui antes que os guardas vejam isso.}
{112}{}{Stupid metal bore's age de novo ...}
{113}{}{Esse torno de metal precisa ser oleado novamente ...}
{114}{}{Precisa fazer uma lista dessas peças excedentes para o primeiro cidadão.}
{115}{}{Trabalho, seu pedaço estúpido de lixo!}
{116}{}{Estou cercado de idiotas...}
{117}{}{Se eu tivesse as ferramentas certas!}
{118}{}{Eu vou matar esse macaco de cabeça calva no escritório de compras ...}
{119}{}{Está tarde. Volte pela manhã.}
{120}{}{A loja está fechada. Depois de terminar esta lista para o Primeiro Cidadão, vou para casa.}
{121}{}{Estou ocupado. Volte em um dia ou mais, e eu deveria estar pronto.}
{122}{}{Eu tenho uma acumulação de coisas que precisam ser consertadas. Volte em um dia ou dois.}
{123}{}{Bem, se não é o "chefe" do meu pai.}
{124}{}{Sim?!}
{125}{}{Você quer algo, ou você vai ficar parado olhando como um idiota?}
{126}{}{Mooo-ron}
{127}{}{Shamble off}
{128}{}{Whoa, fácil. Eu estava apenas parando para ver o que é esse lugar.}
{129}{}{Veja isso. Eu não estou com vontade de fazer qualquer besteira hoje.}
{130}{}{Eu estava procurando o Vault. Você pode me dizer onde fica?}
{131}{}{Na verdade, eu estava saindo.}
{132}{}{É aquele grande buraco na montanha a leste, além desses dois guardas armados. Qualquer outra coisa que você quer perguntar ou posso voltar ao trabalho?}
{133}{}{O que é este lugar?}
{134}{}{Veja isso. Eu não estou com vontade de fazer qualquer besteira hoje.}
{135}{}{Obrigado pelas instruções. Adeus.}
{136}{}{Como se a Vault City não tivesse brahmin humano suficiente ... olha, você CINTA ESTÁ AQUI, OK? Você poderia HURT você mesmo! AGORA, ESTEJA! IR!}
{137}{}{* Snfff * Você é grande meenie ... * snff * ... eu vou sumplace n 'tenho paye de partee wiff ... * snfff * ... e creme de gelo ... e kake ... e eu não invento me imagino Povo como VOCÊ!}
{138}{}{Shamble off}
{139}{}{Saia daqui. Ou eu vou convocar os guardas para fazer você sair.}
{140}{}{Tente. Eu vou gostar.}
{141}{}{Tudo bem, vou embora.}
{142}{}{É o galpão de manutenção da Vault City. Ou você acabou de aguardar a falta do enorme sinal?
 O lado do edifício?}
{143}{}{Não, desculpe. Eu pensei que isso poderia ser uma loja de algum tipo.}
{144}{}{Esqueça. Lamento perturbá-lo.}
{145}{}{Você tem o "certo", mesmo assim. Olha, você precisou de algo reparado ou você só queria me fazer um monte de perguntas idiotas?}
{146}{}{O que você repara aqui?}
{147}{}{Veja isso. Eu não estou com vontade de fazer qualquer besteira hoje.}
{148}{}{Apenas perguntas idiotas hoje, na verdade. Falo com você mais tarde.}
{149}{}{Distribuidores de álcool sintético, rádios, armas de fogo, peças de torreta a laser, monitores de computador, você o nomeia ... quando posso obter as ferramentas para fazer meu trabalho.}
{150}{}{Ferramentas?}
{151}{}{Parece um trabalho difícil. Vou deixá-lo para isso.}
{152}{}{Agora, eu tenho o torno de metal mal trabalhando, e minha chave desapareceu ... NOVA ... e os dentes dos meus alfinetes estão despojados.}
{153}{}{Tudo o que eu poderia ajudar?}
{154}{}{Qual o problema de obter mais ferramentas?}
{155}{}{Tudo bem então. Dia bom.}
{156}{}{Você? Eu duvido.}
{157}{}{Bem, eu tenho uma chave inglesa e um par de alicates aqui.}
{158}{}{Você conseguiria uma nova chave e um conjunto de alicates o ajudaria?}
{159}{}{Qual o problema de obter mais ferramentas?}
{160}{}{Só pensei em oferecer ajuda. Deixa pra lá então.}
{161}{}{O PROBLEMA é, não posso sair e comprar alguns novos, tenho que requisitá-los da Cidade do Vault. Isso significa preencher cinco bilhões de listas, apresentando-as em triplicado, então ESPERA.}
{162}{}{Então, por que d -?}
{163}{}{Desculpe h -}
{164}{}{Inferior, eu pedi um Kit de Ferramentas Super Snap-Off MESES atrás, mas, como sempre, não será exibido até que eu não precise mais disso. É uma maravilha que alguma vez seja feita por aqui ...}
{165}{}{Talvez eu possa ajudá-lo.}
{166}{}{Oh. Bem, lamento ouvir isso. Posso estar de volta.}
{167}{}{Sim. Por quê?}
{168}{}{Bem, eu tenho uma chave inglesa e um par de alicates aqui.}
{169}{}{Talvez eu possa encontrar alguns e trazê-los de volta para você.}
{170}{}{Qual o problema de obter mais ferramentas?}
{171}{}{Oh. Bem, obrigado pelo conselho.}
{172}{}{Não vou segurar a respiração, mas se você quiser, vá em frente. É o seu tempo, não o meu. Talvez eu possa juntar um pouco para pagar seu problema.}
{173}{}{Se eu encontrar uma chave inglesa e um par de alicates, eu as trarei.}
{174}{}{Você faz?}
{175}{}{Sim. Aqui está.}
{176}{}{Uh ... obrigado. Quero dizer, eles não são ótimos, mas eles vão fazer. Onde você ... oh, não importa. Não é importante. Aqui estão alguns dólares por seu problema.}
{177}{}{Obrigado. Diga, eu tive algumas perguntas ...}
{178}{}{Talvez você possa usar essas ferramentas para ajudar a consertar essa atitude sua.}
{179}{}{Sem problemas. Feliz em ajudar.}
{180}{}{Sim, sim ... olha, tenho algum trabalho a fazer. Volte em um dia ou dois, tudo bem? eu terei
 Hora de conversar então.}
{181}{}{Até amanhã, então.}
{182}{}{Está bem. Eu voltarei em um dia ou dois. Adeus.}
{183}{}{Você não vai acreditar nisso. Não menos do que um DIA depois que você me deu essas ferramentas, o Super Tool Kit que eu pedi chegou. Mas não apenas um. Eles me enviaram CINCO. O que diabos está errado com o escritório de pedidos ?!}
{184}{}{Você poderia se separar de um desses kits de ferramentas?}
{185}{}{Por que não?! O que eu vou fazer com CINCO ?! Pegue! Eu juro que vou bater o alcatrão vivo fora do List Office para isso.}
{186}{}{Obrigado. Diga, eu tive algumas perguntas ...}
{187}{}{Apreciá-lo. Vou colocar este kit de bom uso.}
{188}{}{Oh, eu vejo como é isso. Bem, o que você quer?}
{189}{}{O que? Não tenho tempo para conversar o dia todo.}
{190}{}{Sim? O que?}
{191}{}{Você pode reparar qualquer coisa minha?}
{192}{}{O que você tem em estoque?}
{193}{}{Qual é o trato com você e seu pai?}
{194}{}{Deixa pra lá. Vou deixá-lo no seu trabalho.}
{195}{}{Nada vale a pena mencionar. Ele veio aqui há vinte anos atrás em uma de suas viagens de caravana, nocauteou a mãe e saiu. Até que ele parou, eu não o vi em cerca de cinco anos. Sem perda.}
{196}{}{Parece que você e ele têm algumas coisas para resolver.}
{197}{}{Oh. Bem, eu tive algumas outras perguntas ...}
{198}{}{Deixa pra lá. Vou deixá-lo no seu trabalho.}
{199}{}{Não, nós não. Nós dissemos tudo o que precisamos dizer há muito tempo.}
{200}{}{Você tem certeza?}
{201}{}{Tudo bem então. Tive algumas outras questões ...}
{202}{}{Eu deixarei você no seu trabalho então.}
{203}{}{Sim eu tenho certeza. Bem ... exceto pelo fato de que eu acho que ele deveria perder algum peso. Ele está com um pneu de reposição. E ele deveria parar de vagar por todos os resíduos que vendiam lixo para tribos. Isso é praticamente isso.}
{204}{}{Olha, ele estava com problemas com escravos, e ele está tentando recuperar o tempo perdido agora. Mas você está certo, ele poderia suportar perder peso.}
{205}{}{Oh, ok. Tive algumas outras questões ...}
{206}{}{Deixa pra lá. Vou deixá-lo no seu trabalho.}
{207}{}{Heh heh. Você tem uma vantagem sarcástica. Eu gosto disso. Quanto ao ol "Papai" ... bem ... hmmm. Vou tentar ser um pouco mais civilizado. Por enquanto, de qualquer forma.}
{208}{}{Um ... certifique-se de ficar sem problemas, está bem?}
{209}{}{Ótimo. Olha, eu tinha outra coisa que queria te perguntar ...}
{210}{}{Vou fazer o meu melhor. Eu tinha outra coisa que eu queria lhe perguntar ...}
{211}{}{É isso que eu pergunto. Vou deixá-lo no seu trabalho.}
{212}{}{Vou tentar. Ele parece encontrá-lo onde quer que vá. Vejo você, Valerie.}
{213}{}{Olha, eu não tenho nada em "estoque". Esta não é uma loja. A maioria das coisas que eu conserto aqui acaba no Office de Serviços ... está fora da porta e à sua esquerda.}
{214}{}{Como eu disse ANTES, esta não é uma loja. Vá para o escritório de amenidades se quiser uma arma. Venha aqui se quiser algo reparado.}
{215}{}{Oh. Bem, você pode reparar qualquer coisa minha?}
{216}{}{Você pode reparar qualquer coisa minha?}
{217}{}{Tudo bem, tudo bem. Adeus.}
{218}{}{Bem, talvez. Vamos ver o que você obteve.}
{219}{}{Mostre suas pistolas.}
{220}{}{Mostre-lhe seus rifles.}
{221}{}{Mostre seu inventário geral.}
{222}{}{Deixa pra lá. Eu queria saber outra coisa ...}
{223}{}{Talvez outra hora.}
{224}{}{Eu poderia colocar um carregador de velocidade sobre o seu magnum por US $ 800.}
{225}{}{Hmmmm. Que Desert Eagle você tenha ... Eu poderia dar uma revista expandida, se você quiser. Isso custará US $ 1000.}
{226}{}{Atualize o magnum.}
{227}{}{Como cerca de US $ 650 para a atualização magnum em vez disso?}
{228}{}{Atualize o Desert Eagle.}
{229}{}{Como cerca de US $ 850 para o Desert Eagle?}
{230}{}{Esqueça as pistolas. Você pode atualizar minhas outras armas?}
{231}{}{Eu queria saber outra coisa ...}
{232}{}{Volto quando tiver mais dinheiro.}
{233}{}{Hmmm. Talvez outra hora.}
{234}{}{Esse rifle de assalto que você chegou lá ... Eu posso dar uma revista expandida por US $ 1500.}
{235}{}{Hmmmm. Eu tenho um escopo de pouca luz, posso colocar esse FN FAL que você obteve por US $ 3500.}
{236}{}{Expandir a revista do rifle de assalto AK-112.}
{237}{}{Como cerca de US $ 1350 para atualizar o rifle de assalto?}
{238}{}{Anexe esse escopo de luz baixa no FN FAL.}
{239}{}{Como cerca de US $ 3100 para o escopo de baixa luz?}
{240}{}{Você poderia atualizar uma das minhas outras armas?}
{241}{}{Deixa pra lá. Eu queria algo mais ...}
{242}{}{Na verdade, nenhum deles. Eu tenho que ir.}
{243}{}{Volto quando tiver mais dinheiro de sobra.}
{244}{}{Suponho que eu poderia aguentar esse projeto de gado para você. Vai custar-lhe US $ 750.}
{245}{}{Tudo certo.}
{246}{}{Quais os $ 650 em vez disso?}
{247}{}{Na verdade, você poderia atualizar uma das minhas outras armas em vez disso?}
{248}{}{Deixa pra lá. Eu queria algo mais ...}
{249}{}{Na verdade, nenhum deles. Eu tenho que ir.}
{250}{}{Muito rico para o meu sangue. Volto quando tiver mais dinheiro.}
{251}{}{Eu vejo que você pegou alguns truques do meu pai cheapskate. Me dê cerca de uma hora, e será bom ir ...}
{252}{}{Tudo bem, tudo bem. Você soa como meu pai cheapskate. Me dê cerca de uma hora, e será bom ir ...}
{253}{}{Tudo bem, me dê cerca de uma hora, e será bom ir ...}
{254}{}{Tudo certo.}
{255}{}{Ai está. Algo mais?}
{256}{}{Tive algumas outras questões ...}
{257}{}{Você pode atualizar qualquer outra coisa que eu tenha?}
{258}{}{Nada mais, hoje. Obrigado.}
{259}{}{O que você ... uh ... papai?}
{260}{}{Eu sinto Muito?}
{261}{}{Uh, não, não estou. Quero dizer, eu não penso assim.}
{262}{}{Papai?!}
{263}{}{2 segundos}
{264}{}{Valerie ?! Querida, é você?}
{265}{}{2 segundos}
{266}{}{Onde diabos você estava?! Ainda correu ao redor dos resíduos, vendendo lixo brilhante para tribos?}
{267}{}{4 segundos}
{268}{}{Uh, heh-heh ... ignora-a, Boss, ela não sabe o que está dizendo ... Val, querida ... você vê, havia escravas e ...}
{269}{}{4 segundos}
{270}{}{Corte a porcaria, pai. Você ainda está chamando todos que conhece "Chefe?" Sempre detestei isso por você.}
{271}{}{4 segundos}
{272}{}{Valerie, querida, por favor ... deixe-me explicar ... você vê ...}
{273}{}{2 segundos, then Fade Out}
{274}{}{... e foi assim que saímos do Den.}
{275}{}{2 segundos}
{276}{}{Que carga de merda de brahmin.}
{277}{}{2 segundos}
{278}{}{É a verdade!}
{279}{}{2 segundos}
{280}{}{Você não começa. Fico feliz que mamãe não esteja aqui para ouvir isso.}
{281}{}{2 segundos}
{282}{}{O que? O que aconteceu com sua mãe?}
{283}{}{2 segundos}
{284}{}{Febre cerebral. Pegou-o sobre os resíduos. Provavelmente procurando por você.}
{285}{}{2 segundos}
{286}{}{Oh. Eu ... uh ... desculpe, Val.}
{287}{}{2 segundos}
{288}{}{Estou apenas brincando.}
{289}{}{2 segundos}
{290}{}{Wh - ?!}
{291}{}{2 segundos}
{292}{}{Ela realmente morreu de envenenamento por radiação. Ela tomou bem a água não filtrada do pátio.}
{293}{}{4 segundos}
{294}{}{Wha ... o quê ?!}
{295}{}{2 segundos}
{296}{}{Não foi sua culpa. Ela tinha muitos rads que atravessavam seu sistema para o Dr. Troy para salvá-la. Ela estava brilhando como uma lâmpada.}
{297}{}{2 segundos}
{298}{}{Oh. Eu ... bem, eu ...}
{299}{}{2 segundos}
{300}{}{Não se preocupe. Ela era muito barulhenta antes disso, mesmo assim. Era apenas uma questão de tempo.}
{301}{}{3 segundos}
{302}{}{Ainda sinto muito, não tive a chance de vê-la novamente.}
{303}{}{2 segundos}
{304}{}{Não, você não está. Você costumava chamá-la de "víbora do deserto", não é?}
{305}{}{2 segundos}
{306}{}{Bem, sim. Mas você não deveria ligar para sua mãe}
{307}{}{2 segundos}
{308}{}{Por que não? Era verdade. Ela poderia ser uma cadela horrível quando quisesse ser.}
{309}{}{3 segundos}
{310}{}{Uh ... parece que você fez bem para si mesmo. Herdou o talento de seu pai para reparar coisas, parece.}
{311}{}{4 segundos}
{312}{}{Papai ... você mal consegue amarrar seus cadarços, muito menos reparar qualquer coisa com peças móveis.}
{313}{}{3 segundos}
{314}{}{Wh- ?! O diabo que você diz!}
{315}{}{2 segundos}
{316}{}{Pergunte ao seu "chefe".}
{317}{}{2 segundos}
{318}{}{Bem ... ele pode consertar rádios. E outras coisas.}
{319}{}{Ub nuwb ub}
{320}{}{2 segundos}
{321}{}{Se você lhe der todas as peças, certo?}
{322}{}{Vejo que você está viajando com pessoas um pouco mais inteligentes do que você.}
{323}{}{2 segundos}
{324}{}{Bem, sim.}
{325}{}{Ub nuwm ub?}
{326}{}{2 segundos}
{327}{}{Ha! Eu sabia. Sloppy, descuidado.}
{328}{}{Seu "chefe" provavelmente é melhor para corrigir coisas do que você é.}
{329}{}{2 segundos}
{330}{}{Bem, Val, a última vez que te vi, quase não podes contar uma porca de uma chave inglesa.}
{331}{}{2 segundos}
{332}{}{Continue, pai, e você PRECISA de uma chave para tirar minha bota da sua bunda.}
{333}{}{2 segundos}
{334}{}{Oh sim?! Bem, "querida", é melhor vê-lo ou -}
{335}{}{2 segundos}
{336}{}{Cale-se! Feche seus dois! Isso passou por muito tempo! Agora, vamos, Vic, vamos continuar.}
{337}{}{UGRGHH! IR! NÃO MAIS FALA! NÓS VAMOS!}
{338}{}{3 segundos}
{339}{}{Falaremos mais tarde, Val.}
{340}{}{2 segundos}
{341}{}{Sim, claro, pai.}
{342}{}{2 segundos}
{343}{}{Fade out for 3 segundos}
{344}{}{Ei! Ainda bem que você voltou. Por último, ouvi, você estava viajando para o sul, armando tanques antigos e explodindo as estradas de petróleo.}
{345}{}{Você volta aqui para um pouco de paz e tranquilidade, Sr. Big Hero?}
{346}{}{Você volta aqui para um pouco de paz e tranquilidade, Sra. Big Heroine?}
{347}{}{HE-wo? Hee-hee! Sim!}
{348}{}{Shamble off}
{349}{}{Achei que voltaria e toque a base com o Vault City por um tempo. A paz e a tranquilidade também não doem. Eu precisava de algo primeiro, no entanto ...}
{350}{}{Nada hoje, obrigado. Cuidar.}
{351}{}{Bem, você tem cuidado por aqui, você ouve? Não esteja explodindo Vault City se você puder ajudar. E ... ei, obrigado por nos salvar a todos.}
{352}{}{Swure! Tchau tchau!}
{353}{}{Shamble off}
{354}{}{Deixa pra lá. Eu falarei com você mais tarde.}
{355}{}{Você ajudou Valerie a obter novas ferramentas.}
{356}{}{Você convenceu Val para dar a ela uma chance.}
{357}{}{ *** NÃO DELETE A LINHA PRÓXIMA (# 358)! É NECESSÁRIO PARA O SCRIPT. NÃO SEJA TRABALHANDO ESTE, nem ***}
{358}{}{}
{359}{}{Ei, eu tenho as ferramentas que você queria.}
{360}{}{Não parece que você tenha muito de qualquer coisa com a qual eu possa mexer. Eu principalmente faço pistolas, rifles, esse tipo de coisa.}
