{100}{}{Você vê o Membro do Conselho Sénior McClure.}
{101}{}{Você vê um funcionário antigo da Vault City. Seu cabelo está grisalho pelas bordas.}
{102}{}{Você vê o Membro do Conselho Sénior McClure.}
{103}{}{Você vê um funcionário antigo da Vault City. Seu cabelo está grisalho pelas bordas.}
{104}{}{Ouvi falar de seu ato de heroísmo. Estamos todos em sua dívida ... Escolhido.}
{105}{}{Tenho que tabular essas listas antes de sair. Volte de manhã, e depois falo com você.}
{106}{}{Um ghoul ?! Guardas! Guardas!}
{107}{}{Um mutante ?! Guardas! Guardas!}
{108}{}{Eu não tenho nada para dizer para voce. Saia, ou chamarei os guardas.}
{109}{}{Bom dia ... Capitão, não é? Ouvi falar muito sobre você. Existe algo com o que eu poderia ajudá-lo?}
{110}{}{Bom dia ... Cidadão, não é? Eu tinha ouvido que ganhamos um novo membro da comunidade. Existe alguma coisa com que eu poderia ajudá-lo?}
{111}{}{Olá posso te ajudar?}
{112}{}{Bom dia, capitão. Tudo está bem, eu confio?}
{113}{}{Bom dia, cidadão. Posso ajudar?}
{114}{}{Sim? Havia algo mais que você queria?}
{115}{}{San-tah Klass?}
{116}{}{Shamble off}
{117}{}{Posso fazer-te algumas perguntas?}
{118}{}{Quem é Você?}
{119}{}{Apenas olhando ao redor, obrigado. Dia bom.}
{120}{}{Como você entrou em nossa cidade? Guardas! Nós temos um Outworlder que precisa ser acompanhado até o portão!}
{121}{}{Eu não vou, eu não vou}
{122}{}{Ahhh ... Ples no go? Eu seja bom}
{123}{}{Claro, capitão.}
{124}{}{Claro, cidadão.}
{125}{}{O que você gostaria de saber?}
{126}{}{Qual é o seu trabalho aqui?}
{127}{}{Procuro um Kit de Criação do Jardim do Éden.}
{128}{}{O que você pode me falar sobre o primeiro cidadão?}
{129}{}{Gostaria de fazer algumas perguntas sobre o Gecko.}
{130}{}{O que você pode me falar sobre Redding?}
{131}{}{Preciso falar com você sobre a Redding.}
{132}{}{Como se torna um cidadão?}
{133}{}{Eu acho que você pode ter uma parte que poderia consertar a planta de energia da Gecko.}
{134}{}{Eu reparei a planta de Gecko.}
{135}{}{Eu tenho um disco de dados econômicos aqui que você pode achar interessante.}
{136}{}{Encontrei uma maneira de otimizar o reator Gecko.}
{137}{}{Aqui está o disco do reator Gecko. Você pode otimizar?}
{138}{}{Nada hoje, obrigado.}
{139}{}{Eu sou o conselheiro sênior McClure. E você é...?}
{140}{}{Não é da sua conta.}
{141}{}{. Prazer em conhecê-lo.}
{142}{}{Eu realmente tenho que correr. Talvez possamos fazer apresentações algum outro momento.}
{143}{}{Eu espero esse tipo de descortesia de um Outworlder, não um cidadão. Eu sou membro do Conselho Municipal da Vault, e você me mostrará o devido respeito, ou eu revogarei sua Cidadania. Você me entende?}
{144}{}{Enrole você, velho.}
{145}{}{Tanto faz. Acabei de falar com você de qualquer maneira.}
{146}{}{Desculpa. Não queria ofender você.}
{147}{}{Bem, esta é a descortesia que eu esperava dos Outworlders! Me dê seu Day Pass e vá com os guardas. Não há lugar para o seu tipo em nossa cidade.}
{148}{}{Não estou lhe dando nada. Você quer isso? Você vem buscá-lo.}
{149}{}{Eu não sou um Outworlder. Eu sou um cidadão.}
{150}{}{Ok, estou indo.}
{151}{}{Acho isso difícil de acreditar. Deixe-me ver seus documentos.}
{152}{}{Aqui, leve-os!}
{153}{}{Você os quer? Você vem buscá-los.}
{154}{}{Não sei como alguém de sua criação inferior se tornou cidadão, mas esses documentos parecem estar em ordem. Estranho ... Não lembro de te conhecer antes. Não importa, devo honrar a sua cidadania.}
{155}{}{Você está bem, você honrará minha Cidadania!}
{156}{}{Okay, certo. Estou fora daqui.}
{157}{}{Nunca mais me fale comigo. Se você fizer isso, eu revogarei sua cidadania. Dia bom.}
{158}{}{Dia bom.}
{159}{}{Você tenta revogar minha cidadania, você se arrependerá.}
{160}{}{Seus poderes são fracos, velho. Você não é igual para mim.}
{161}{}{É isso aí! Cidadão ou não, você está fora daqui. Guardas, mostre isso degenerado aos portões!}
{162}{}{Vou. Este lugar sugado de qualquer maneira.}
{163}{}{Eu não estou indo a lugar nenhum.}
{164}{}{O que posso fazer para você?}
{165}{}{Eu não sei, velho. O que você pode fazer por mim?}
{166}{}{Procuro um Kit de Criação do Jardim do Éden.}
{167}{}{Posso fazer-te algumas perguntas?}
{168}{}{Nada hoje. Eu estava apenas fazendo um passeio pelo edifício do conselho.}
{169}{}{UM GECK? Como eu entendi, nós só tivemos um. Eu li que durou muito tempo, mas quebrou alguns anos antes de eu nascer. Nós deveríamos ter dois ...}
{170}{}{Suposto?}
{171}{}{... mas, aparentemente, o antigo governo desperdiçou as remessas e recebemos uma remessa que deveria ser feita para um número da Vault ... treze, acho que era. Provavelmente receberam o nosso outro GECK.}
{172}{}{O que estava no carregamento destinado ao Vault 13?}
{173}{}{O que aconteceu com o GECK que quebrou?}
{174}{}{Posso fazer-lhe outra pergunta?}
{175}{}{Entendo. Obrigado pela informação.}
{176}{}{Chips de água, uma centena de ou mais. Não sei por que eles enviaram tantos ... nunca precisamos substituir o nosso. Tivemos o mesmo chip de água desde o dia em que nossa gente viveu no subsolo no Vault.}
{177}{}{O que aconteceu com o GECK que quebrou?}
{178}{}{Posso fazer-lhe outra pergunta?}
{179}{}{Interessante. Obrigado pelo seu tempo.}
{180}{}{A ironia é afiada. Talvez falemos mais tarde depois de parar o sangramento.}
{181}{}{Foi desmontado, e suas peças foram usadas para outras aplicações.}
{182}{}{O que estava no envio significava para o Vault 13?}
{183}{}{Posso fazer-lhe outra pergunta?}
{184}{}{Entendo. Obrigado pelo seu tempo.}
{185}{}{Ela é a líder das pessoas. A Cidade dos Cidadãos da Vault olha para ela para obter orientação, mas os Cidadãos, através do Conselho, ainda têm uma palavra final sobre assuntos. Nestes tempos difíceis, ela é um pilar da nossa sociedade.}
{186}{}{"Tentando tempos?" O que você quer dizer?}
{187}{}{O que você faz?}
{188}{}{Posso fazer-lhe outra pergunta?}
{189}{}{Obrigado por você. Adeus.}
{190}{}{Gecko? O que você quer saber?}
{191}{}{Onde está Gecko?}
{192}{}{O que é Gecko?}
{193}{}{Posso fazer-lhe outra pergunta?}
{194}{}{Obrigado por você. Adeus.}
{195}{}{Não há muito a dizer, além do fato de que nossos embarques de minério se tornaram poucos e distantes.}
{196}{}{Alguma idéia de por quê?}
{197}{}{Onde está a Redding?}
{198}{}{Posso fazer-lhe outra pergunta?}
{199}{}{Obrigado por você. Adeus.}
{200}{}{Eu sou o membro do conselho sênior. Eu supervisiono as reuniões do conselho.}
{201}{}{Então, o que faz o primeiro cidadão?}
{202}{}{Posso fazer-lhe outra pergunta?}
{203}{}{Obrigado pelo seu tempo. Adeus.}
{204}{}{Bem, a cidadania não é para todos, você entende. Você parece mais um aventureiro para mim ... Eu realmente não acho que a cidadania seja para você.}
{205}{}{Ah, vamos ... apenas me diga o que preciso fazer para se tornar cidadão.}
{206}{}{Eu ainda gostaria de me tornar cidadão de qualquer maneira.}
{207}{}{Posso fazer-lhe outra pergunta?}
{208}{}{Deixa pra lá então.}
{209}{}{Você deseja se tornar cidadão? Bem, gostaríamos de ter você. Tudo o que você precisa fazer é conversar com Proconsul Gregory e ele lhe dará o teste de Cidadania.}
{210}{}{Onde posso encontrar Proconsul Gregory?}
{211}{}{Posso fazer-lhe outra pergunta?}
{212}{}{Obrigado. Eu vou buscá-lo agora. Adeus.}
{213}{}{Muito bem. Tudo o que você precisa é conversar com Proconsul Gregory e ele lhe dará o teste de Cidadania.}
{214}{}{Onde posso encontrar Proconsul Gregory?}
{215}{}{Posso fazer-lhe outra pergunta?}
{216}{}{Tudo certo. Eu vou falar com o Proconsul agora.}
{217}{}{Você o encontrará na Ala Leste. Seu escritório está em frente ao First Citizen's.}
{218}{}{Posso fazer-lhe outra pergunta?}
{219}{}{Obrigado por você. Adeus.}
{220}{}{As coisas foram difíceis nos últimos dois anos. A NCR vem se tornando mais agressiva em suas tentativas de obter a Vault City para se juntar à República.}
{221}{}{Eles nos dizem que, se nos juntássemos, eles poderiam nos defender dos ataques de invasores em nossa cidade. Até o momento, esses ataques de invasores tornaram-se mais brutais.}
{222}{}{Além disso, temos ghouls em Gecko contaminando nossas águas subterrâneas.}
{223}{}{Onde está Gecko?}
{224}{}{O que é Gecko?}
{225}{}{Trying times, indeed. Posso fazer-lhe outra pergunta?}
{226}{}{Desculpe ouvir isso. Obrigado pelo seu tempo. Adeus.}
{227}{}{É apenas a nordeste daqui, mas se você está planejando ir lá, eu aconselharia você a comprar alguns chems anti-radiação. Se eles estão contaminando nossa água, é provável que sua própria cidade seja irradiada.}
{228}{}{O que é Gecko?}
{229}{}{Posso fazer-lhe outra pergunta?}
{230}{}{Obrigado pelo aviso. Adeus.}
{231}{}{É um lugar abandonado, uma favela construída em torno dos restos de uma antiga usina de energia atômica.}
{232}{}{Onde está o Gecko localizado?}
{233}{}{Posso fazer-lhe outra pergunta?}
{234}{}{Obrigado por você. Adeus.}
{235}{}{Não. Não entendo nada. Estamos dispostos a pagar o dólar superior pelo seu minério, mas sempre que tentamos falar com eles sobre isso, eles se tornam evasivos. Se eu soubesse o que estava acontecendo ...}
{236}{}{Eu poderia verificá-lo para você.}
{237}{}{Onde está a Redding?}
{238}{}{Obrigado por você. Adeus.}
{239}{}{Você irá? Não está no meu poder pagar você, mas sua ajuda será muito apreciada.}
{240}{}{Onde está a Redding?}
{241}{}{Sem problemas. Eu vou verificar e voltar quando descobrir o que está errado.}
{242}{}{Redding é uma semana ou mais a oeste daqui. Eu nunca estive lá. Nunca estive fora da Vault City, para esse assunto. Como eu entendo, Redding é suposto ser um dos assentamentos mais agradáveis   nos resíduos.}
{243}{}{Você tem alguma idéia do que está causando o envio dos embarques?}
{244}{}{Entendo. Obrigado pela informação.}
{245}{}{O que é isso? Qualquer coisa que você possa me dizer seria uma grande ajuda.}
{246}{}{O que você pode me falar sobre Redding?}
{247}{}{Descobri que uma grande parte da Redding é dependente de um químico chamado Jet. Os mineiros estão negociando a maior parte do seu minério com o New Reno apenas para manter o fornecimento.}
{248}{}{Dr. Troy criou um antídoto para Jet.}
{249}{}{Entreguei o antídoto à Redding.}
{250}{}{O que é este "Jet" sobre o qual eles são todos dependentes?}
{251}{}{Eu direi-lhe mais tarde quando eu descobrir mais.}
{252}{}{É um químico com uma taxa de confiança de 100% e retiradas severas.}
{253}{}{Por favor, mantenha-me informado.}
{254}{}{Posso fazer algumas outras perguntas?}
{255}{}{Certo.}
{256}{}{Esta é uma triste notícia, precisamos encontrar uma maneira de parar isso. Se isso continuar, nossos suprimentos de minério diminuirão para nada. Por favor nos ajude.}
{257}{}{Verei o que posso fazer.}
{258}{}{Ele tem? Bem, então, o que você está fazendo aqui? Pegue a Doc Johnson em Redding! Ele deve poder encontrar uma maneira de administrá-lo aos mineiros.}
{259}{}{Eu sei, você já me disse. Por favor, leve-o para Redding e veja se você pode ajudá-los.}
{260}{}{Antes de ir, posso fazer algumas outras perguntas?}
{261}{}{Ok, adeus.}
{262}{}{Obrigado! Agora, tudo o que podemos fazer é esperar. Felizmente, isso corrige nosso problema. Obrigado novamente por toda a sua assistência.}
{263}{}{Seja bem-vindo. Fiquei satisfeito por estar de serviço.}
{264}{}{Não é um problema. Posso fazer algumas outras perguntas?}
{265}{}{Whoa ... não consigo nada por meus problemas?}
{266}{}{Se é dinheiro que você quer, dinheiro que você receberá. Aqui estão $ 500 para seus problemas. Agora, bom dia.}
{267}{}{Obrigado.}
{268}{}{Cinco hun -? É melhor tossir um pouco mais rápido e sua vida não valerá US $ 2.}
{269}{}{O que você quer dizer?}
{270}{}{Se eu tivesse um regulador de magnetosfera hidrelétrica, eu poderia fazer sua planta funcionar limpa.}
{271}{}{Oh nada. Desculpe-te incomodar.}
{272}{}{Essa é uma solução aceitável. Parar o envenenamento por radiação é tudo o que me interessa.}
{273}{}{Estou preocupado com o fato de Lynette reter minha cidadania se eu corrigir a planta.}
{274}{}{Ótimo! Onde posso obter a parte?}
{275}{}{Eu vou manter isso em mente.}
{276}{}{Se você consertar sua planta, eu lhe darei cidadania, e não há nada que possa fazer sobre isso.}
{277}{}{Excelente! Onde posso obter a parte?}
{278}{}{Vá ver Randal, o Chief Amenities Officer. Ele deveria ter a peça em estoque.}
{279}{}{Obrigado. Eu vou vê-lo agora mesmo.}
{280}{}{Há outra coisa. Você pode achar interessante este disco de dados econômicos.}
{281}{}{Excelente! Estava preocupado com o fato de a acumulação de radiação nos forçar a mudar de lugar. Você deve ser elogiado em um trabalho bem feito.}
{282}{}{Vault City prevalece, Citizen.}
{283}{}{Vault City, prevalece, capitão.}
{284}{}{Aqui estão os documentos da Cidadania. Se você precisar de alguma coisa, venha me ver.}
{285}{}{Vault City prevalece, Conselheiro.}
{286}{}{Obrigado.}
{287}{}{Sim, você mencionou isso.}
{288}{}{Muito bem, capitão.}
{289}{}{Bem feito, cidadão.}
{290}{}{Bem feito.}
{291}{}{Tive algumas outras questões ...}
{292}{}{Obrigado.}
{293}{}{I'm sorry... an economic data disk? O que você quer dizer?}
{294}{}{Aqui, dê uma olhada.}
{295}{}{É um disco de dados econômicos que mostra a quantidade de energia que a usina de energia atômica de Gecko produziu antes da guerra ... e poderia produzir de novo.}
{296}{}{Deixa pra lá. Tive algumas outras questões.}
{297}{}{Nada. Lamento perturbá-lo.}
{298}{}{Muito bem. Me dê um momento...}
{299}{}{Tudo certo.}
{300}{}{Hmmm. Como você veio por este disco?}
{301}{}{Eu encontrei.}
{302}{}{Encontrei isso enquanto procurava alguns dos arquivos na biblioteca da Vault City.}
{303}{}{Eu entendi de alguém no Gecko.}
{304}{}{Eu recebi isso de um ghoul em Gecko. O nome dele é Gordon Gecko. Ele está interessado em otimizar a usina e compartilhar a energia com o Vault City ... em troca da tecnologia médica da Vault City.}
{305}{}{Entendo. Assim. O que isso tem a ver comigo?}
{306}{}{Bem, como eu entendo, o gerador de energia da Vault City só pode suportar tantas pessoas. Na verdade, já está se aproximando do limite.}
{307}{}{Eu não vou perguntar-lhe como você veio por essa informação, mas se fosse verdade, o que você está propondo?}
{308}{}{Uma vez que a central de energia Gecko está fixa, o disco indica que é possível que ele também produza energia suficiente para a Vault City. Parece que o reator precisaria primeiro ser otimizado.}
{309}{}{O disco mostra que a usina de Gecko ... se fosse otimizada ... poderia produzir uma grande quantidade de energia. Muito mais do que Gecko precisa. Vault City poderia usar essa energia.}
{310}{}{Você está sugerindo que SEICAMOS Gecko e tomemos sua usina? Eu não irei -}
{311}{}{Não, não ... se Gecko pudesse receber os dados de otimização para sua fábrica, eu aposto que estariam dispostos a trocar o excesso de poder por assistência médica.}
{312}{}{Hmmm. No que diz respeito à assistência médica, não sou antipático para a situação dos ghouls. Eles certamente sofreram o suficiente ... mas como podemos otimizar sua planta?}
{313}{}{Eu não sei. Talvez tenha alguém com quem eu possa falar depois que a planta for reparada.}
{314}{}{Eu não sei. Talvez haja alguém com quem eu possa conversar na fábrica.}
{315}{}{Eu só precisaria acessar o computador do Vault City. Poderia otimizar o disco do reator da usina e permitir que a planta funcione mais suavemente.}
{316}{}{Não tenho objecções à sua proposta. Se você conseguir encontrar algum meio de otimizar a planta, avise-me.}
{317}{}{Tudo certo. I'll go get that part from Randal and see about repairing the reactor first.}
{318}{}{Muito bem, capitão.}
{319}{}{Muito bem, cidadão.}
{320}{}{Você tem minha permissão para usar o computador do Vault e otimizar o disco do reator. Você pode encontrá-lo no terceiro nível do Vault, perto da sala de operações.}
{321}{}{Excelente. Obrigado, Conselheiro. Eu vou fazer isso.}
{322}{}{Está feito. Aqui está.}
{323}{}{Vou manter o disco econômico e estudá-lo um pouco mais ... Talvez eu possa persuadir o Conselho a entrar em negociações com a Gecko para negociar pelo seu poder. O disco de dados seria um argumento forte por si só.}
{324}{}{I appreciate it. Obrigado.}
{325}{}{Hmmm. Bem, não consigo permitir o acesso ao Vault, mas eu poderia otimizar o disco do reator para você.}
{326}{}{Tudo certo. But I don't have the reactor disk on me. I'll be back with it.}
{327}{}{Seria ótimo.}
{328}{}{Excelente!}
{329}{}{Tudo certo.}
{330}{}{Deixe-me pegar o disco do reator, e eu terei o computador central do Vault otimizado.}
{331}{}{Great. Obrigado.}
{332}{}{O que é isso?}
{333}{}{Eu tenho um disco de dados do reator aqui do Gecko. De acordo com ... o técnico uh, na fábrica de energia, o computador da Cidade Vault pode otimizar o disco do reator e fazer funcionar a fábrica com mais facilidade.}
{334}{}{Guardas! Guardas!}
{335}{}{}
{336}{}{Você contou a McClure sobre o problema da confiança do Redding Jet.}
{337}{}{Você forneceu o disco de dados econômicos para o McClure.}
{338}{}{Ainda estou procurando uma maneira de otimizar a usina.}
{339}{}{Ainda estou procurando uma maneira de otimizar a usina.}
{340}{}{Eu queria poder ajudar, mas temo que meu conhecimento de reatores seja ... limitado. Talvez um
 dos técnicos da fábrica de Gecko saberiam como otimizar a planta?}
{341}{}{Perhaps. Tive algumas outras questões ...}
{342}{}{Talvez assim. Eu irei ver.}
{343}{}{Você disse a McClure sobre a entrega do antídoto Jet.}
