{100}{}{Você vê o assistente médico residente, Phyllis.}
{101}{}{Você vê uma jovem magro. Ela chega fraca de anti-séptico.}
{102}{}{Você vê RMA Phyllis.}
{103}{}{Você vê uma jovem magro. Ela chega fraca de anti-séptico.}
{104}{}{Você arriscou sua própria vida para nos salvar TODOS. Você é a pessoa mais corajosa que já conheci.}
{105}{}{Um intruso! Aieeeeee! Guardas!}
{106}{}{Um mutante! Aieeeeee! Guardas!}
{107}{}{Um ghoul! Aieeeeee! Guardas!}
{108}{}{Precisa imprimir os gráficos de Gregory ...}
{109}{}{Vamos ver. Temos três inoculações Servant programadas para 1400 ...}
{110}{}{Todo esse beeping está me deixando louco ...}
{111}{}{Eu juro que as bases de dados médicas estão falando entre si ...}
{112}{}{Vamos ver ... três hypodermics, anti-sépticos, três ampolas de RadX ...}
{113}{}{Melhor prepare o Dr. Troy nesse seminário para amanhã ...}
{114}{}{Sim, eles me fazem trabalhar de novo NOVA. Principalmente fazendo listas.}
{115}{}{Você pode querer voltar pela manhã.}
{116}{}{Eu acho que eu coloco você na lista para amanhã de manhã, se for uma emergência.}
{117}{}{Não posso esperar para ir para casa. Fazer todas essas listas me desgasta.}
{118}{}{Seria melhor se você voltasse de manhã. Eu tenho que compilar essas listas.}
{119}{}{Pobre Dr. Troy. Ele não fez nada!}
{120}{}{Por que eles exilaram o Dr. Troy?}
{121}{}{Espero que o Dr. Troy esteja bem no Outworld ...}
{122}{}{Hmmph. Estou muito ocupado para falar com você agora. Se você precisar de alguma coisa, consulte o Dr. Troy.}
{123}{}{Ah! Olá. Eu não o vi antes ... você é um novo cidadão?}
{124}{}{Ah! Olá de novo.}
{125}{}{Sit-Zen?}
{126}{}{Contra?}
{127}{}{Got ouchie ... * snfff * ... ouchie HURT}
{128}{}{Na verdade, sou o novo Capitão da Guarda.}
{129}{}{Sim, acabei de receber minha cidadania.}
{130}{}{Uh, sim, acabei de receber minha cidadania.}
{131}{}{Desculpe, pensei que você fosse outra pessoa. Dia bom.}
{132}{}{Oh meu, você está ferido, não é? Desculpe, deveria ter prestado mais atenção. Vá ver o Dr. Troy. Ele cuidará de você.}
{133}{}{Uh ... kay? Yup-yup.}
{134}{}{Posso fazer algumas perguntas primeiro?}
{135}{}{Obrigado. Eu vou vê-lo agora.}
{136}{}{Ah! Você deve ser um dos servos designados aqui para o dia. Você deveria ... uh, hmmm. VOCÊ - GO - MARTIN.}
{137}{}{Uh ... hmmm. Ouça-me novamente, de perto esta vez: VOCÊ - GO - MARTIN.}
{138}{}{HUGO MARTIN.}
{139}{}{Got ouchie ... * snfff * ... ouchie HURT}
{140}{}{Shamble off}
{141}{}{SIM, MARTIN. GO - BOTTOM - LEVEL.}
{142}{}{SIM, MAR-TIN. VALE NIVEL INFERIOR.}
{143}{}{Got ouchie ... * snfff * ... ouchie HURT}
{144}{}{Shamble off}
{145}{}{GO - BOTTOM - LEVEL. NÍVEL - TRÊS. AGORA.}
{146}{}{ME GO BOTTOM LEVEL TREE NOW}
{147}{}{Got ouchie ... * snfff * ... ouchie HURT}
{148}{}{Shamble off}
{149}{}{Talvez nossos servos tenham algum tipo de síndrome de deficiência de inteligência ...}
{150}{}{Ah! Bem, bem-vindo ao Vault City, capitão.}
{151}{}{Bem, bem-vindo ao Vault City, colega Cidadão.}
{152}{}{Não vemos muitos rostos novos por aqui. Eu sou Phyllis. Qual o seu nome?}
{153}{}{Meu nome é}
{154}{}{Eu estou}
{155}{}{Se eu quisesse lhe dar meu nome, eu teria dito a você, "Syphyllis" ... ou seja qual for o motivo do seu nome.}
{156}{}{Desculpe, não tenho tempo para falar agora.}
{157}{}{Por que, de todos os ...! Nunca conheci alguém tão baixo quanto você. Eu sugiro que você vá embora. Agora.}
{158}{}{Eu sugiro que você assista esse tom seu ou que vai ter problemas.}
{159}{}{Whatever. Eu estoudone talking to you anyway.}
{160}{}{Guardas! Dr. Troy! Socorro!}
{161}{}{Então é assim que vai ser, hein? Tudo bem então...}
{162}{}{Eu estouthe Resident Medical Assistant. I work for Dr. Troy.}
{163}{}{O que você acha do Dr. Troy?}
{164}{}{Posso fazer-te algumas perguntas?}
{165}{}{Ótimo. Eu poderia usar alguma assistência médica.}
{166}{}{Desculpe, não tenho tempo para falar agora.}
{167}{}{Bem vindo de volta. Tudo o que posso ajudá-lo?}
{168}{}{Claro. O que você gostaria de saber?}
{169}{}{O que você acha do Dr. Troy?}
{170}{}{Você pode me dizer onde é o computador central?}
{171}{}{Preciso de alguma cura.}
{172}{}{O que você faz aqui?}
{173}{}{Você pode me falar sobre Vault City?}
{174}{}{Na verdade, não importa. Obrigado mesmo assim.}
{175}{}{Oh, o Dr. Troy pode ser muito rigoroso às vezes, mas tudo em tudo, ele é um bom homem. Vault City tem a sorte de tê-lo.}
{176}{}{Bem, ele me pediu para contrabando alguns chems para a cidade para ele.}
{177}{}{Posso fazer-lhe outra pergunta?}
{178}{}{Obrigado pelo seu tempo. Adeus.}
{179}{}{}
{180}{}{}
{181}{}{Você está certo? Isso não soa como o Dr. Troy. Ainda ... ele tem trabalhado duro ultimamente ... não, não, isso é impossível. Você deve estar enganado.}
{182}{}{Acho que não. Ele era muito claro sobre o que queria.}
{183}{}{Hmmmm. Posso fazer-lhe outra pergunta?}
{184}{}{Deixa pra lá então.}
{185}{}{Eu seria muito cuidadoso sobre o que você diz sobre o Dr. Troy em Vault City. Ele é um membro respeitado da nossa comunidade.}
{186}{}{All right, then. Posso fazer-lhe outra pergunta?}
{187}{}{Obrigado pelo aviso. Talvez eu deva falar com outra pessoa.}
{188}{}{Está no terceiro nível, se bem me lembro. Não foram lá em anos.}
{189}{}{Por que não?}
{190}{}{Posso fazer-lhe outra pergunta?}
{191}{}{Obrigado pelas instruções. Adeus.}
{192}{}{Oh, eu não sei. Não há muitas razões para descer no Vault. É usado principalmente para espaço de armazenamento hoje em dia. O único lá embaixo é Martin, e ... bem, apenas entre você e eu, ele não é um excelente conversador.}
{193}{}{Uhh ... Por que eles o fizeram conversacionalista se ele não é bom em seu trabalho?}
{194}{}{Posso fazer-lhe outra pergunta?}
{195}{}{Entendo. Obrigado pela informação.}
{196}{}{Uh ... talvez você DEVE ir falar com ele. Vocês dois podem ter mais em comum do que eu pensava.}
{197}{}{Posso fazer-lhe outra pergunta primeiro?}
{198}{}{Tudo bem então. Eu vou falar com ele.}
{199}{}{Vault City? Bem, na verdade, não há muito o que dizer. Quero dizer, eu fui um cidadão toda a minha vida ... mas não há muito para fazer na Cidade do Vault. Em absoluto.}
{200}{}{Parece ser uma pena que uma bela jovem, como você, não consiga encontrar QUALQUER COISA em Vault City.}
{201}{}{Nada mesmo? Vamos.}
{202}{}{Posso fazer-lhe outra pergunta ...}
{203}{}{Ah bem. Só pensei em perguntar.}
{204}{}{Olha, eu sei que você é um novo Cidadão e tudo, e não quero deixar um amortecedor em sua Cidadania, mas essa cidade pode ser muito aborrecida às vezes.}
{205}{}{Maçante? Como assim?}
{206}{}{Isso é ruim. Tive algumas outras questões ...}
{207}{}{Ah bem. Desculpe ouvir isso.}
{208}{}{I mean, have you noticed how similar everyone is? And OLD? Most of the seminars and extracurricular activities are geared towards octogenarians. Eu estoubarely twenty-five, and this city makes me feel like Eu estoufifty.}
{209}{}{Uh ... octo-generianos? Você quer dizer os guardas?}
{210}{}{Falando de idade, notei que não há crianças na cidade.}
{211}{}{EU VISTIVEi a semelhança dos Cidadãos.}
{212}{}{Ah bem. Só pensei em perguntar.}
{213}{}{Uh não ... "octogeneriano" é um adjetivo que se refere a uma pessoa com oitenta anos de idade.}
{214}{}{Uh, okay. Posso fazer-lhe outra pergunta?}
{215}{}{Tudo bem então. Talvez possamos falar mais tarde.}
{216}{}{Bem, sim. Na verdade, não há. Ainda. Não sei se alguém lhe disse ainda, a Vault City é uma comunidade planejada. Não devemos outro ciclo de gravidez até alguns anos.}
{217}{}{Uh ... um ciclo de gravidez?}
{218}{}{Posso fazer-lhe outra pergunta?}
{219}{}{Entendo. Bem, obrigado pela informação.}
{220}{}{Sim. As gravidezes só são permitidas durante determinados anos estabelecidos pelo Conselho.}
{221}{}{E se você engravidar de qualquer maneira?}
{222}{}{Oh. Tive algumas outras questões ...}
{223}{}{Entendo. Bem, obrigado pela informação.}
{224}{}{Como isso aconteceria?}
{225}{}{Uh, o último que ouvi, o SEX pode fazer alguém ficar grávida.}
{226}{}{Esqueça que eu perguntei. Olha, eu tive algumas outras perguntas ...}
{227}{}{Deixa pra lá. É melhor eu ir.}
{228}{}{Oh, você quer dizer relações sexuais? O intercâmbio ainda é permitido fora dos ciclos de gravidez.}
{229}{}{Isso não faz as pessoas grávidas?}
{230}{}{Oh. Tive algumas outras questões ...}
{231}{}{Ah bem. Só pensei em perguntar.}
{232}{}{Oh, não, não ... você vê, nossas gravidezes não resultam de relações sexuais.}
{233}{}{Eu estouafraid to ask. But I will anyway.}
{234}{}{Eu não quero mais saber. Mas eu tive algumas outras perguntas ...}
{235}{}{Eu acho que já ouvi o suficiente.}
{236}{}{Cidadãos masculinos "doam" para o Auto-Doc aqui no Vault e os jogos mais favoráveis   são escolhidos pelo computador. Então, o Citizen feminino apropriado é semeado pelo Auto-Doc.}
{237}{}{Posso doar?}
{238}{}{As pessoas ainda engravidam da relação sexual? E quanto a gravidez acidental?}
{239}{}{Você sabe, eu gostaria muito de lhe fazer qualquer outra pergunta agora.}
{240}{}{Would you excuse me? Eu estougoing to go see if I can get my Citizenship revoked.}
{241}{}{I think Eu estougoing to go somewhere and be violently ill. Goodbye.}
{242}{}{Certamente. Agradecemos sua contribuição. Vault City poderia usar algum material genético novo.}
{243}{}{Tudo bem então...}
{244}{}{Posso obter uma revista ou algo assim?}
{245}{}{Sua contribuição é impressionante ... você mesmo parece ser bastante talentoso. Como você está se sentindo?}
{246}{}{Excelente! Obrigado.}
{247}{}{Hmmm. Talvez sua contribuição não tenha sido tão valiosa quanto eu pensava. Obviamente, mesmo assim.}
{248}{}{Posso dizer honestamente que nunca perdi o charme primitivo de Arroyo mais até esse momento.}
{249}{}{Nunca senti a necessidade de ter mais do que neste momento.}
{250}{}{Não, obrigado.}
{251}{}{Bem, na verdade ... você vê, isso é algo em que eu pensei recentemente, mas os cidadãos não parecem ter gravidezes acidentais. As únicas gravidezes bem sucedidas foram facilitadas pelo Auto-Doc.}
{252}{}{Você sabe, a radiação de fundo pode resultar em esterilidade ou, pior ainda, em danos cromossômicos. Pode valer a pena conferir.}
{253}{}{Talvez seja só porque eles não têm muito sexo real por aqui.}
{254}{}{Ah bem. Só pensei em perguntar.}
{255}{}{Você sabia, eu estava pensando o mesmo. Talvez eu deva falar com o Dr. Troy. Ele tem estado muito ocupado para ver isso recentemente, mas o próximo ciclo de gravidez está chegando, então ...}
{256}{}{Posso fazer algumas outras perguntas?}
{257}{}{Mencioná-lo para o Dr. Troy seria uma boa idéia. Boa sorte.}
{258}{}{É como se fossem todos ... clones. Todos se vestem parecidos, atuam de maneira semelhante, e a pior parte é que todos parecem felizes com isso. Eu ... bem, às vezes eu me preocupo que acabei sendo assim como elas. Isso provavelmente parece bobo, hein?}
{259}{}{De modo nenhum. A pressão para se conformar deve ser bastante áspera por aí, especialmente considerando o quão insular é uma comunidade Vault City.}
{260}{}{Ah bem. Só pensei em perguntar.}
{261}{}{Sim, pode ser meio irresistível às vezes. Mas aqui estou, derrubando sua opinião sobre o Vault City. Não me entenda mal. É um ótimo lugar para se viver.}
{262}{}{Apenas uma sugestão, mas você pode querer viajar um pouco fora da Vault City. Mesmo falando com alguns dos comerciantes do pátio. Eles podem ser capazes de ampliar seus horizontes um pouco.}
{263}{}{It's got its advantages, no doubt. Posso fazer algumas outras perguntas?}
{264}{}{Fico feliz que você esteja feliz aqui. Talvez possamos falar novamente.}
{265}{}{Bem, fiquei tentado a sair do portão, mas os outros cidadãos me avisaram contra isso ...}
{266}{}{Esse é apenas outro motivo para fazê-lo. Você não quer fazer o que os outros cidadãos fazem, não é? Eles estão todos em seus caminhos.}
{267}{}{Bem, pode ser perigoso lá fora. Diga, posso fazer-lhe outra pergunta?}
{268}{}{Eles estão certos. Provavelmente não é uma boa idéia. É melhor eu ir.}
{269}{}{Você sabe que está certo. Talvez eu saia do portão quando tiver a chance. Gostaria de saber mais sobre o mundo exterior.}
{270}{}{Ótimo. Diga, posso fazer-lhe outra pergunta?}
{271}{}{Vai ser bom para você. Cuidar.}
{272}{}{Perdoe-me?}
{273}{}{Não pude deixar de notar que você é uma jovem atraente que poderia suportar sair de vez em quando. Que tal você e eu jantamos?}
{274}{}{Never mind. Posso fazer-lhe outra pergunta?}
{275}{}{Ah bem. Só pensei em perguntar.}
{276}{}{Oh. Eu ... você sabe, eu adoraria, mas não posso.}
{277}{}{Oh. Bem, eu ... eu adoraria.}
{278}{}{Aw, c'mon. Eu estounew. I'll get into trouble if I go around by myself.}
{279}{}{Tudo certo. Posso fazer algumas perguntas então?}
{280}{}{Ah bem. Só pensei em perguntar.}
{281}{}{Ótimo! Vamos.}
{282}{}{Obrigado pela maravilhosa noite.}
{283}{}{Uh ... claro. Talvez nós saibamos mais uma vez. Eu ... eu ligo para você. Tchau.}
{284}{}{Eu estousorry, but no.}
{285}{}{Tudo certo. Posso fazer algumas perguntas em vez disso?}
{286}{}{Ah bem. Só pensei em perguntar.}
{287}{}{Bem, é bom ver o preconceito do mesmo sexo estar vivo e bem na cidade de Vault. Tchau.}
{288}{}{. O que você faz por aqui?}
{289}{}{. Lembre-se de fazer algumas perguntas?}
{290}{}{Oh, bem, pensei que não havia filhos, porque esta poderia ser a versão européia de Fallout 2. Adeus.}
{291}{}{Você deu uma doação à Cidade do Vault e introduziu material genético favorável em sua comunidade.}
{292}{}{Você deu uma doação à Cidade do Vault e introduziu material genético novo em sua comunidade.}
{293}{}{Você deu uma doação ao Vault City ... pelo que vale a pena.}
{294}{}{Você convenceu Phyllis para falar com o Dr. Troy sobre a potencial esterilidade em Vault City.}
{295}{}{Você convenceu Phyllis a ver o mundo exterior.}
{296}{}{Você descobre rapidamente que Phyllis é bastante aborrecido e auto-centrado. Você resolve nunca mais namorar com alguém como ela novamente.}
{297}{}{Falando em octo-genérico, uh, octo-ians, uh, pessoas idosas, notei que não há crianças na cidade de Vault.}
