{100}{}{Você vê um velho com um brilho louco em seus olhos.}
{101}{}{Você vê Old Joe, o sábio idiota local.}
{102}{}{Olá. Não te vi há algum tempo.}
{103}{}{Eu conheço você?}
{104}{}{Ah sim. Faz algum tempo. O que você tem feito?}
{105}{}{Bem, já faz um tempo. O que você tem feito?}
{106}{}{Isso e aquilo. de onde você me conhece?}
{107}{}{Olha, velho, não sei quem diabos você é.}
{108}{}{Claro. Bem, eu estive em volta; finalmente acabou aqui neste lugar abandonado por Deus. Não é como o
 bons velhos tempos. Não senhor.}
{109}{}{Sim, bons velhos tempos. Lembre-se daquela hora em que ...}
{110}{}{Não foi o mesmo ultimamente, com certeza. Agora ... o que fizemos juntos?}
{111}{}{Não me lembre de você, não é? Bem, você parece ser um pouco jovem.}
{112}{}{O que você está tentando me dizer?}
{113}{}{Você parece tão familiar, no entanto. Ah, devem ser meus velhos olhos. Bem, bom dia para você.}
{114}{}{Uh, sim ... adeus.}
{115}{}{Sim, certamente demos o inferno do Mestre, não é? A merda caiu depois que você foi embora. Tive
 mova-se e mude meu nome. Onde você terminou?}
{116}{}{Eu vivi em uma pequena aldeia.}
{117}{}{Bem, é melhor você ter cuidado por aqui. As coisas não são tão claras quanto antes. Você vê melhor
 suas costas.}
{118}{}{Ok, obrigado.}
{119}{}{Sim, eu procurei seu Vault por um tempo, mas nunca encontrei. Então você tem boas histórias para
 seu velho amigo Ian?}
{120}{}{Ian?}
{121}{}{Sim, Ian. Você não se lembra de mim? Tem sido um monte de anos. Você pensaria que alguém não iria
 esquecer seu melhor amigo. Bem ... exceto pelo tiro na parte de trás. Desculpe por isso novamente.}
{122}{}{Me desculpe, mas você deve pensar que eu sou o Vault Dweller. Minha aldeia foi fundada por quem
 veio do Vault.}
{123}{}{Bem, isso faz um pouco mais de sentido. Bem, é bom ouvir meu amigo ter feito bem. Bem, Ian's Old
 tenho algum conselho para você. Você tem cuidado lá fora. Este lugar não é tão pungente quanto parece.}
{124}{}{Oque esta acontecendo aqui?}
{125}{}{Bem, os Cidadãos do Vault pensam muito de sua linhagem e não se importam muito com
 pessoas como eu e você. Você pega essa arma. Isso irá protegê-lo se as coisas ficarem fora de controle.
 Você provavelmente não deve ser visto conversando com esse velho louco. O melhor está a caminho.}
{126}{}{Obrigado pela ajuda.}
{127}{}{Deixe um velho descansar.}
{128}{}{Tão familiar ...}
{129}{}{Deixe-me ser agora.}
{130}{}{É melhor você começar.}
{131}{}{Eles ficarão suspeitos se conversarmos mais.}
{132}{}{Continue, pegue. Faço meu velho amigo orgulhoso.}
