{100}{}{Você vê Randal, o Chief Amenities Offcier.}
{101}{}{Você vê um homem de meia idade com cabelos pretos finos.}
{102}{}{Você vê Randal, o Chief Operations Officer.}
{103}{}{Você vê um homem de meia idade com cabelos pretos finos.}
{104}{}{Parabéns,}
{105}{}{Maneira de colocar aqueles Enclave assh -... er, empurrões, em seu lugar!}
{106}{}{Ouvi dizer que você chutou uma grande cauda para o sul. Maneira de ir.}
{107}{}{Um intruso! Guardas! Guardas!}
{108}{}{Wh- ?! Um mutante! Guardas!}
{109}{}{Wh-? Um ghoul! Guardas!}
{110}{}{Bom dia, capitão.}
{111}{}{Vault City prevalece, capitão.}
{112}{}{Bom dia, cidadão.}
{113}{}{Vault City prevalece, Citizen.}
{114}{}{Precisa enviar gráficos de distribuição para Sub-Amenities Offices A e B ...}
{115}{}{Precisa compilar os inventários de estoque mais recentes e colocá-los no servidor da lista ...}
{116}{}{Sinto falta do DOS. Este novo sistema operacional dificulta a inserção de listas.}
{117}{}{O primeiro cidadão ainda precisa dessas listas de inventário ...}
{118}{}{Desculpe, estamos fechados para a noite. Volte pela manhã.}
{119}{}{Estamos fechados. Estou apenas compilando essas listas antes de ir para casa.}
{120}{}{Olá, estranho. Sempre um prazer ver um novo rosto. Nome Randal ... Eu sou o Chief Amenities Officer. Preciso de algo?}
{121}{}{Gechkk}
{122}{}{Nooooooooo-pe}
{123}{}{Shamble off}
{124}{}{Bem, isto depende. O que é este lugar?}
{125}{}{Nada hoje, na verdade.}
{126}{}{UM GECK? Esse é um Kit de Criação do Jardim do Éden, uma espécie de malha cinzenta que olha coisa, certo? Não ouvi ninguém falar de um desses ... bem, desde ... quase pra sempre.}
{127}{}{PRECISA Gechkkk}
{128}{}{Shamble off}
{129}{}{Você tem um?}
{130}{}{Mente se eu lhe fizer outra coisa?}
{131}{}{Bem, não importa então.}
{132}{}{Odeio quebrar isso para você, amigo, mas já não temos mais o nosso. Usou-o para fazer Vault City ... * poof. * Tudo foi.}
{133}{}{PRECISA Gechkkk.}
{134}{}{Shamble off}
{135}{}{Oh ... bem, você conhece algum lugar que possa ter um?}
{136}{}{Mente se eu lhe fizer outra coisa?}
{137}{}{Bem, nunca mais perceber.}
{138}{}{Bem, hmmm. Aqui está o seu problema, como eu vejo: o GECK é um antigo pedaço de tecnologia ... tecnologia de pré-guerra, na verdade. Você simplesmente não pode "encontrá-los" mais. Eles só foram emitidos para Vaults.}
{139}{}{PRECISA de Valt.}
{140}{}{Shamble off}
{141}{}{Você sabe onde eu poderia encontrar outros Vaults?}
{142}{}{Mente se eu lhe fizer outra coisa?}
{143}{}{Bem, não importa então.}
{144}{}{Você poderia digitalizar o Computador central do Vault, veja se ele possui coordenadas para outros Vaults. Eu duvido, mas não prejudico na verificação.}
{145}{}{Bem, se você tivesse acesso ao nosso Computador central do Vault, talvez você possa encontrar alguma menção de outros Vaults. Mas apenas os cidadãos são permitidos no Vault.}
{146}{}{Tanques}
{147}{}{Mente se eu lhe fizer outra coisa?}
{148}{}{Obrigado pela informação.}
{149}{}{Ei, bem vindo de volta. Algo que eu possa fazer por você?}
{150}{}{Certo. O que está em sua mente?}
{151}{}{Gechkk?}
{152}{}{Shamble off}
{153}{}{O que é esse lugar de novo?}
{154}{}{Você tem um GECK em estoque?}
{155}{}{Valerie no depósito de manutenção poderia usar uma chave inglesa nova e alguns alicates.}
{156}{}{O conselheiro McClure disse que você teria um ... uh, hydro-magneto-thingie que eu poderia ter para a usina Gecko.}
{157}{}{O conselheiro McClure disse que você teria um regulador de magnetosfera hidrelétrica em estoque que eu poderia ter.}
{158}{}{O primeiro cidadão me enviou aqui para pedir minha recompensa.}
{159}{}{Nada hoje, na verdade.}
{160}{}{Este é o escritório de amenidades. Tenho seu estoque típico ... necessidades básicas de vida, alguns livros, "como" manuais, algumas ferramentas, estimulações, suprimentos médicos, isso e aquilo.}
{161}{}{Parece bom. Posso ver o que você tem no estoque?}
{162}{}{Você tem um GECK?}
{163}{}{Valerie no depósito de manutenção poderia usar uma chave inglesa nova e alguns alicates.}
{164}{}{O conselheiro McClure disse que você teria um ... uh, hydro-magneto-thingie que eu poderia ter para a usina Gecko.}
{165}{}{O conselheiro McClure disse que você teria um regulador de magnetosfera hidrelétrica em estoque que eu poderia ter.}
{166}{}{O primeiro cidadão me enviou aqui para pedir minha recompensa.}
{167}{}{Lembre-se de fazer algumas outras perguntas?}
{168}{}{Talvez eu esteja de volta em algum outro momento.}
{169}{}{Bem, desculpe por infringi-lo, mas só estou autorizado a fazer transações com cidadãos. Não ofende por você, mas é a regra, você sabe? Você pode tentar o Harry feliz no pátio.}
{170}{}{Bem, desculpe por infringi-lo, mas só estou autorizado a fazer transações com cidadãos. Não ofende por você, mas é a regra, você sabe? Você pode tentar o Harry feliz no pátio.}
{171}{}{Como posso me tornar um cidadão?}
{172}{}{Mas ... eu sou um cidadão. Você não se lembra de mim?}
{173}{}{Olha, meu dinheiro é tão bom quanto qualquer cidadão.}
{174}{}{O conselheiro McClure disse que você teria um regulador de magentosfera hidrelétrico em estoque que eu poderia ter.}
{175}{}{O primeiro cidadão me enviou aqui para pedir minha recompensa.}
{176}{}{Lembre-se de fazer algumas outras perguntas?}
{177}{}{Bem. Adeus.}
{178}{}{Você pode fazer o teste de Cidadania. Proconsul Gregory dá a qualquer Outsider que se torne um cidadão. Você provavelmente deveria conversar primeiro com o primeiro cidadão Lynette. Ela faz o show por aqui.}
{179}{}{Tudo certo. Onde ela está?}
{180}{}{Entendo. Mente se eu lhe fizer outra pergunta?}
{181}{}{Obrigado pela informação. I'll go look for her.}
{182}{}{Ela está no Edifício do Conselho ... siga o prédio aqui, dê a direita e continue caminhando pela rua após o parque. Você deve correr direito com isso.}
{183}{}{Entendo. Mente se eu lhe fizer outra pergunta?}
{184}{}{Obrigado pela informação. I'll go look for her.}
{185}{}{Mesmo? Não posso dizer que lembro de você. Você tem algum documento sobre você? Poderia esclarecer o assunto.}
{186}{}{Não, eu não tenho eles em mim agora.}
{187}{}{Sim. Aqui está.}
{188}{}{Deixa pra lá. Eu falarei com você mais tarde.}
{189}{}{Bem, deixe-me passar pelo leitor aqui, e nós teremos certeza de que tudo está acontecendo. Não levará apenas um momento.}
{190}{}{Wh- ?! Uau! Devolva esses documentos!}
{191}{}{Uh ... na verdade, não tenho tempo para comprar nada agora. Deixe-me ter os documentos de volta, e eu irei em frente.}
{192}{}{Tudo certo. Tenho certeza de que tudo está em ordem.}
{193}{}{Bem ... está bem.}
{194}{}{Mente se eu lhe fizer algumas perguntas?}
{195}{}{Vejo você mais tarde.}
{196}{}{Tudo é verificado. Aqui estão os seus documentos de volta. O que posso fazer para você?}
{197}{}{Deixe-me ver o que você tem no estoque.}
{198}{}{Na verdade, você se importa se eu lhe fizer algumas perguntas?}
{199}{}{Nada hoje, na verdade.}
{200}{}{Então ... você é cidadão}
{201}{}{Sim, ele disse que você estaria parando ...}
{202}{}{Tudo certo.}
{203}{}{Na verdade, não importa, volto mais tarde para isso.}
{204}{}{Ok, aqui você vai. One Hy-Mag. Um pouco parece uma lâmpada de lava, não é? Oh, não deixe cair ... é muito frágil.}
{205}{}{Diga, o que você tem em estoque?}
{206}{}{Mente se eu lhe fizer algumas perguntas?}
{207}{}{Obrigado. Eu posso olhar para isso por algumas horas antes de levá-lo para a planta de Gecko.}
{208}{}{Consegui. Obrigado pela parte.}
{209}{}{Sim, o primeiro cidadão disse que você estaria parando ... Capitão. (Winks.) Deixe-me dizer-lhe, Capitão, você tem uma BELEZA esperando por você.}
{210}{}{Sim, o primeiro cidadão disse que você estaria parando. Bem, deixe-me dizer-lhe, amigo, você tem uma BELEZA esperando por você.}
{211}{}{O que é isso?}
{212}{}{Na verdade, continue com isso. Eu vou buscá-lo mais tarde.}
{213}{}{Nada menos que um Heckler e Koch G11, uma das melhores armas de assalto já feitas ... (arma de armário, passa para você) ... dispara um cartucho sem mancha de 4,7 mm, revista de 50 rodadas. Quando fala, as pessoas ouvem.}
{214}{}{Aposto. Obrigado.}
{215}{}{Sem problemas. Além disso, aqui ... tenho algumas granadas de fragmentos em mim. Considere meus agradecimentos por limpar esses invasores.}
{216}{}{Ótimo. Posso ver o que você tem em estoque?}
{217}{}{Posso fazer algumas outras perguntas?}
{218}{}{Obrigado. Vou colocá-los de bom uso.}
{219}{}{Isso vai fazer isso por você, então?}
{220}{}{Lembre-se de fazer algumas outras perguntas?}
{221}{}{Sim, isso será para hoje.}
{222}{}{Sim, eu sei. Ainda estou aguardando as listas de requisições para limpar o servidor, mas vai demorar. Não sei o que dizer. As coisas apenas levam tempo.}
{223}{}{I see. Lembre-se de fazer algumas outras perguntas?}
{224}{}{Talvez eu possa encontrar essas ferramentas em outro lugar, então.}
{225}{}{!}
{226}{}{, Hã? Aguarde um minuto, e irei buscar o Magneto Hidrelétrico ... uh, o Hy-Mag.}
{227}{}{, certo? Aguarde um minuto, e irei buscar o Magneto Hidrelétrico ... uh, o Hy-Mag.}

{228}{}{Obrigado.}
{229}{}{[continuar]}
