{100}{}{Você vê o Assistente de Wallace, Skeev.}
{101}{}{Você vê um jovem jovem e magro. Seus olhos estão correndo para trás e para frente.}
{102}{}{Você vê o Assistente de Wallace, Skeev.}
{103}{}{Você vê um jovem jovem e magro. Seus olhos estão correndo para trás e para frente.}
{104}{}{Ei, você tem algum pedaço de Horrigan? Eu poderia vendê-los por cinquenta, cem dólares um pop, dar-lhe 10% da ação.}
{105}{}{Dá o fora.}
{106}{}{Cai fora. Não tenho nada para te dizer.}
{107}{}{Oh, eh, ei, capitão. Bom dia, hein?}
{108}{}{Bem, se não é o novo cidadão.}
{109}{}{Ei, "Cidadão".}
{110}{}{Você não pode trazer esse mutante aqui.}
{111}{}{Você não pode trazer esse ghoul aqui.}
{112}{}{Estamos desligados pela noite. Volte pela manhã.}
{113}{}{Olha, Outsider, se você tiver negócios aduaneiros, Wallace está de volta, ok? Ele irá configurá-lo com todas as formas que você precisa.}
{114}{}{Furms precisa?}
{115}{}{Shamble off}
{116}{}{Uh ... o que é esse lugar?}
{117}{}{Tudo certo. Obrigado.}
{118}{}{Este é o escritório ADUANEIRO. Como o sinal fora diz. Se você não tem negócios aduaneiros, o que você está fazendo aqui?}
{119}{}{Eu estava procurando o Vault.}
{120}{}{Eu estava olhando para entrar na cidade.}
{121}{}{Como você é parte dos costumes e tudo, eu queria saber se você tinha algum "conselho" sobre como levar certos itens dentro da cidade.}
{122}{}{Nada. Desculpe incomodá-lo.}
{123}{}{O cofre? Está dentro da cidade. Por quê? Você está procurando passar do portão?}
{124}{}{Sim.}
{125}{}{Não, apenas olhando ao redor. Obrigado.}
{126}{}{Bem, você poderia ir ver meu chefe, Wallace, e TRY para obter permissão para entrar, mas você estaria perdendo seu tempo. Ele nunca deixa alguém. Claro, existem outras maneiras ...}
{127}{}{Que outras formas?}
{128}{}{Obrigado. Eu vou ver Wallace então.}
{129}{}{Conselhos? Bem, o conselho é caro, Outsider. Você tem algum dinheiro?}
{130}{}{Dê-lhe $ 50.}
{131}{}{Dê-lhe $ 75.}
{132}{}{Dê-lhe $ 100.}
{133}{}{Provavelmente não é suficiente para lhe interessar. Eu voltarei quando tiver mais.}
{134}{}{Deixa pra lá. Talvez falemos mais tarde.}
{135}{}{Bem, há algumas coisas que você pode fazer. Um é um cidadão. Eles nunca pesquisam cidadãos. Claro, suas chances de se tornar um cidadão são próximas de nada.}
{136}{}{Por quê?}
{137}{}{O que mais eu poderia fazer?}
{138}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{139}{}{Se você não nasceu um cidadão, então você deve fazer uma prova para se tornar um cidadão. Número de Estranhos que tomaram o teste e se tornaram Cidadãos? Zero. Suas chances? MENOS do que zero.}
{140}{}{Qual é esse teste?}
{141}{}{O que mais eu poderia fazer para vencer os costumes?}
{142}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{143}{}{Gregory, o Proconsul, dá um "teste" a qualquer Estrangeiro que queira se tornar cidadão. Ele mede sua inteligência e
 Percepção, e você tem que ter muita sorte de passar, também. A maioria dos cidadãos teria problemas com isso.}
{144}{}{Então, o que o torna tão difícil?}
{145}{}{O que mais eu poderia fazer para vencer os costumes além de se tornar cidadão?}
{146}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{147}{}{Como a maioria dos Estranhos não consegue ler, fazer trigonometria, ou soletrar "Australopithecus", você descobre. É apenas uma desculpa para impedir que os Outsiders se tornem cidadãos.}
{148}{}{O que mais eu poderia fazer para vencer os costumes além de se tornar cidadão?}
{149}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{150}{}{Esconda os bens aos seus escravos ... seus "Servos". Você vê, a mentalidade de Vault City é a seguinte:
Eles não parecem apanhar que alguém permitiria que os Servos carregassem algo importante ... ou questionável. Vai saber.}
{151}{}{Alguma outra opção?}
{152}{}{Tudo bem então. Obrigado.}
{153}{}{Bem, você pode se tornar um cidadão ... não oficialmente.}
{154}{}{Do que você está falando?}
{155}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{156}{}{Se você obteve o dinheiro, então vou entrar em detalhes. De outra forma...}
{157}{}{Eu tenho o dinheiro. O que você está vendendo?}
{158}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{159}{}{$ 200, e os papéis são seus.}
{160}{}{Por duzentos dólares, posso fazer você um cidadão de pleno direito. Você terá passagem livre
 O portão, sem aborrecimentos. Posso imprimir os documentos, registrar seu número de série e ter você no seu caminho
 em cinco minutos.}
{161}{}{E se eu dissesse a alguém que estava vendendo papéis de cidadania?}
{162}{}{Parece bom. Aqui estão $ 200.}
{163}{}{Bem, dois cem são bastante íngremes. Eu só tenho $ 150 em mim.}
{164}{}{Eu não tenho esse tipo de dinheiro em mim. Talvez outra hora.}
{165}{}{Não, obrigado. Talvez outra hora.}
{166}{}{Simples. Eles não ACREDITAM-lo. Você é um Outsider, eu sou um cidadão. Adivinha a quem eles vão acreditar?}
{167}{}{Vou pegar os documentos da Cidadania, então.}
{168}{}{Vou pegar os papéis Citizenship ... mas por US $ 150, não $ 200.}
{169}{}{Bem, US $ 200 são muito íngremes para mim. Talvez eu esteja de volta se eu conseguir mais dinheiro.}
{170}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{171}{}{Hmmm. Bem, tudo bem ... hoje me sinto caridoso. Mas não conte nenhum de seus outros Outsider
 Amigos, vocês os conseguiram tão baratos.}
{172}{}{Tudo certo.}
{173}{}{Apenas me dê os papéis malditos.}
{174}{}{Tudo bem, tudo acabou de imprimir. Aqui você é ... "Cidadão". E não conte a ninguém sobre isso,
 ESPECIALMENTE Wallace, tudo bem?}
{175}{}{Sem problemas. Nunca pensaria em fazer tal coisa para um cidadão permanente, como
 Você mesmo, especialmente quando tenho provas de suas atividades ilegais sentadas aqui no meu bolso.}
{176}{}{Consegui. Sem problemas.}
{177}{}{O que? Ninguém vai acreditar em você, Outsider! Será sua palavra sobre a minha!}
{178}{}{Normalmente, seria. Mas esses papéis falsos falam por si mesmos. E eles,
 A menos que você possa pagar por seu silêncio.}
{179}{}{Claro que sim. Até logo.}
{180}{}{Eu ... wh ... você está sujo ...}
{181}{}{Cuidado ... Eu assistiria sua língua se eu fosse você.}
{182}{}{Doce me falando, não vai ajudar, Skeev.}
{183}{}{Tudo bem, recebi um POUCO dinheiro escondido. Aqui. Pegue ... trezentos dólares.
 Agora, você ficará quieto?}
{184}{}{Tanto quanto você sabe. Até logo.}
{185}{}{Sem problemas. Você tem meu silêncio.}
{186}{}{Duzentos ou nada, Outsider. É a única maneira que você vai entrar no portão.}
{187}{}{Acho que vou tentar os canais oficiais.}
{188}{}{Não, obrigado.}
{189}{}{Ha! Boa sorte, Outsider. A única maneira que você obterá um Passe de Dia, o homem Wallace, é se você pey
 A partir de seus dedos distorcidos e mortos.}
{190}{}{Eu tentarei ele de qualquer maneira.}
{191}{}{Se é isso que é preciso ...}
{192}{}{Você reconsidere?}
{193}{}{Você novamente. O que você quer?}
{194}{}{Vant? Vant!}
{195}{}{Shamble off}
{196}{}{O que é este lugar?}
{197}{}{Eu gostaria de entrar na cidade.}
{198}{}{Gostaria de comprar os documentos falsos da Cidadania que você estava oferecendo antes.}
{199}{}{Eu decidi transformá-lo por vender documentos falsos da Cidadania.}
{200}{}{Como você é parte dos costumes e tudo, eu queria saber se você tinha algum "conselho" sobre como levar certos itens dentro da cidade.}
{201}{}{Deixa pra lá.}
{202}{}{Olhe, fraca, saia daqui, ou ligarei para os guardas.}
{203}{}{Olhe, dim, saia de h - Mmmm. Espere um minuto. Talvez...}
{204}{}{Hurnh?}
{205}{}{Shamble off}
{206}{}{Venha comigo um segundo, fraco. Eu tenho alguém com quem você deve conhecer.}
{207}{}{Okee-dokeee}
{208}{}{Nuh-uh ME STAY}
{209}{}{Encontrou este Outsider vagando nos resíduos, Barkus. Parece um bom material Servant.}
{210}{}{Encontrou esse grupo vagando pelos resíduos, Barkus. Este Outsider aqui parece um bom material Servant.}
{211}{}{2 segundos}
{212}{}{Você só pode estar brincando. É obviamente retardado.}
{213}{}{1 Em segundo lugar, não remova o flutuador Barkus ainda.}
{214}{}{Re-tar-dead! Pooooo!}
{215}{}{2 segundos}
{216}{}{Vamos lá. Você precisa de alguém para trabalhar no Vault, não é?}
{217}{}{1 Em segundo lugar, não remova o flutuador Barkus ainda.}
{218}{}{Valt! Gechkk!}
{219}{}{2 segundos}
{220}{}{Bem ... hmmm. Suponho que você estará esperando a taxa de um buscador?}
{221}{}{2 segundos}
{222}{}{Os Outsiders comem suas próprias fezes? DE CURSO Eu quero uma taxa de finder.}
{223}{}{1 Em segundo lugar, não remova o flutuador da Skeev}
{224}{}{Feeee? Peeeeeeee!}
{225}{}{1 segundo}
{226}{}{Muito bem. Vou enviá-lo para o Vault então. Talvez possa esclarecer os armazéns.}
{227}{}{Uau. Como você escapou?}
{228}{}{Uau. Como você escapou? You better get back inside before Barkus gets mad. C'mon...}
{229}{}{Oh-keeee}
{230}{}{Shamble off}
{231}{}{Como eu disse antes, posso fazer você um cidadão de pleno direito por US $ 200. Você terá passagem gratuita
 Através do portão, sem aborrecimentos. Posso imprimir os documentos, registrar seu número de série,
 E você está a caminho em cinco minutos.}
{232}{}{O que é necessário para se tornar um cidadão real?}
{233}{}{E se eu fizer? Eu poderia dizer-lhe agora que você está vendendo documentos falsos da Cidadania.}
{234}{}{Eu certamente espero que sim. Eu posso ser bastante persuasivo.}
{235}{}{Veremos sobre isso.}
{236}{}{Ha! Gostaria de ver você tentar. Wallace nunca vai acreditar em você.}
{237}{}{Oh, acho que ele fará uma vez que ele veja os falsos documentos de cidadania que você me deu. Claro, se você
 Acontece ter algum dinheiro com você, pode ser nosso pequeno segredo.}
{238}{}{Veremos sobre isso.}
{239}{}{Vou pegar os documentos da Cidadania, então.}
{240}{}{Bem, US $ 200 são muito íngremes para mim. Talvez eu esteja de volta se eu conseguir mais dinheiro.}
{241}{}{Não, obrigado. Talvez outra hora.}
{242}{}{O que é necessário para se tornar um cidadão real?}
{243}{}{Hmmmm. Quanto para os documentos da Cidadania de novo?}
{244}{}{Se eu tiver que tirá-lo de seus dedos mortos, eu farei.}
{245}{}{Como você se torna um cidadão real?}
{246}{}{Nada, esquece.}
{247}{}{Não, obrigado. Talvez outra hora.}
{248}{}{Se você não nasceu um cidadão, então você deve fazer uma prova para se tornar um cidadão. Número de
 Estranhos que tomaram o teste e se tornaram cidadãos? Zero. Suas chances? MENOS do que zero.}
{249}{}{Qual é esse teste?}
{250}{}{Entendo. Quanto para esses documentos de novo?}
{251}{}{Deixa pra lá. Talvez falemos mais uma vez.}
{252}{}{Gregory, o Proconsul, dá um "teste" a qualquer Estrangeiro que queira se tornar cidadão. isto
 Mede sua inteligência e percepção, e você tem que ser terrível de passar, também.
 A maioria dos cidadãos teria problemas com isso.}
{253}{}{Então, o que o torna tão difícil?}
{254}{}{Entendo. Quanto para aqueles pspers novamente?}
{255}{}{Hmmmm. Talvez falemos mais uma vez.}
{256}{}{Como a maioria dos Estranhos não consegue ler, fazer trigonometria ou soletrar "Australopithecus", você acha isso
 Fora. É apenas uma desculpa para impedir que os Outsiders se tornem cidadãos.}
{257}{}{Entendo. Quanto para esses documentos de novo?}
{258}{}{Hmmm. Talvez falemos mais uma vez.}
