{100}{}{Você vê Wallace.}
{101}{}{Você vê um homem magro com um rosto comprimido. Ele está vestindo um terno de Vault fortemente pressionado.}
{102}{}{Você vê Wallace, o oficial de alfândega da cidade de Vault.}
{103}{}{Você vê um homem magro com um rosto comprimido. Ele está vestindo um terno de Vault fortemente pressionado.}
{104}{}{Nós ouvimos sobre suas façanhas heróicas. Por ordem do Conselho, você ... e quaisquer companheiros ... podem entrar na Cidade do Vault sempre que desejar.}
{105}{}{A Alfândega está fechada para a noite. Volte pela manhã.}
{106}{}{A Alfândega está fechada para a noite. Eu irei para casa depois de tabular todas essas listas.}
{107}{}{Não tenho nada para dizer a quem viaje com ... ghouls. Seu tipo pertence ao pátio.}
{108}{}{Não tenho nada para dizer a quem viaja com ... mutantes. Seu tipo pertence ao pátio.}
{109}{}{Olá, capitão. Existe algo com o que posso ajudá-lo?}
{110}{}{Olá, cidadão. Existe algo com o que posso ajudá-lo?}
{111}{}{Olá, viajante. Bem-vindo ao Vault City. Existe algo com o que posso ajudá-lo?}
{112}{}{Frazz-urb-luuw!}
{113}{}{Shamble off}
{114}{}{Quem é Você?}
{115}{}{O que é este lugar?}
{116}{}{Eu acredito que seu assistente, Skeev, está envolvido em práticas ilegais.}
{117}{}{Nada hoje, obrigado.}
{118}{}{Bem, vejo que vou ter que conversar com os guardas no pátio. Eles parecem estar deixando quase qualquer Outsider em Vault City hoje em dia.}
{119}{}{Dayz. Daze? Daiseeee.}
{120}{}{Shamble off}
{121}{}{Idiota.}
{122}{}{"Daiseee", você diz? Quão fascinante. Por que você não volta para o pátio e conta para o resto de seus amigos de Outsider inbreídos sobre isso?}
{123}{}{Okee!}
{124}{}{Na verdade, agora que eu penso nisso, talvez seja melhor deixar suas armas e armaduras aqui. Apenas pela segurança da Vault City.}
{125}{}{Uh-kuh}
{126}{}{Melhor fazer a armadura primeiro, então, ei ... o que é que você está vestindo sob sua armadura?}
{127}{}{Hnuh?}
{128}{}{Wh--? Por que ... você está vestindo uma armadilha original!}
{129}{}{Sim. Valt sut quente. Como a mãe.}
{130}{}{Sim eu estou. E você não vai acreditar no que eu tive que passar para obter a coisa DAMN -}
{131}{}{Aqui, pegue este Passe de Dia e fale com o nosso Primeiro Cidadão - Tenho certeza que ela terá muitas perguntas para você.}
{132}{}{Uh-kuh.}
{133}{}{Obrigado. Uh, acho que vou ter algumas perguntas para ela.}
{134}{}{O que você quer?}
{135}{}{Citeee? Eu entro?}
{136}{}{Hewooo?}
{137}{}{Shamble off}
{138}{}{Gostaria de voltar para a cidade.}
{139}{}{Queria fazer algumas perguntas ...}
{140}{}{Deixa pra lá.}
{141}{}{Deixe de me incomodar, seu idiota.}
{142}{}{Eu não FUL. VOCÊ FUL.}
{143}{}{Shamble off}
{144}{}{Olha, talvez possamos resolver algo ...?}
{145}{}{Uh, adeus, então.}
{146}{}{Você foi expulso de Vault City por algum motivo, Outworlder. Não há segundas chances.}
{147}{}{Outro? O que aconteceu com o primeiro?}
{148}{}{ME ENTRAR. AGORA.}
{149}{}{Pwease?}
{150}{}{Shamble off}
{151}{}{Olha, foi tudo um mal-entendido.}
{152}{}{Bem, eu não tenho isso em mim. Você não pode me emitir outro?}
{153}{}{Deixa pra lá então.}
{154}{}{Esqueça.}
{155}{}{Eu posso. Mas há uma taxa de US $ 50 por cada Passe de Dia que eu emite depois da primeira.}
{156}{}{Tudo certo. Aqui está o dinheiro.}
{157}{}{Deixa pra lá. I don't need it that badly.}
{158}{}{Deixa pra lá então. Eu voltarei quando tiver mais algum dinheiro.}
{159}{}{Aqui está. POR FAVOR, tente mantê-lo em você o tempo todo. Eu não quero ter que acompanhar vários Passes de Dia para todos.}
{160}{}{Eu tive algumas outras perguntas que eu queria lhe fazer.}
{161}{}{Entendido. Obrigado.}
{162}{}{Wallace do nome. Eu sou o Alfândega da Vault City. Eu aceito aqueles que desejam realizar negócios dentro de nossos grandes muros.}
{163}{}{Eu gostaria de entrar na cidade.}
{164}{}{"Acomodar?" O que você quer dizer?}
{165}{}{Entendo. Obrigado pela informação.}
{166}{}{Se você quiser entrar na Cidade do Vault, então você precisará de um bom motivo. Apenas um Cidadão do Vault tem o direito de ir e vir como quiserem. Todos os outros devem adquirir uma passagem de dia.}
{167}{}{O que é um Passe de Dia?}
{168}{}{É muito importante que você me informe para falar com seu líder.}
{169}{}{Uh, mas eu sou um cidadão. Aqui, olhe.}
{170}{}{Entendo. Obrigado pela informação.}
{171}{}{Este é o Escritório de Alfândega da Cidade do Vault. Somos responsáveis   por manter um registro de todos os bens que nos chegam através das caravanas e supervisionando todas as transações. Todos os comerciantes devem passar pela alfândega antes de entrar na cidade.}
{172}{}{Eu gostaria de entrar na cidade.}
{173}{}{Que mercadorias você recebe das caravanas?}
{174}{}{Entendo. Obrigado pela informação.}
{175}{}{Uh ... você tem certeza?}
{176}{}{Wh-? Quem você está acusando um Cidadão de Vault de qualquer coisa?}
{177}{}{Bem, ele me vendeu essa cidadania falsa. Aqui, olhe.}
{178}{}{Deixa pra lá. Eu devo ter me enganado.}
{179}{}{Aqueles que precisam lidar diretamente com os comerciantes ou o primeiro cidadão recebem uma passagem de dia. Somente aqueles com Passes de Dia podem entrar na cidade.}
{180}{}{Excelente! Você soa como a pessoa que eu estava procurando. Preciso falar com o primeiro cidadão. É urgente.}
{181}{}{Bem, eu preciso falar com o primeiro cidadão.}
{182}{}{Quem é o primeiro cidadão?}
{183}{}{O que é que você faz, exatamente?}
{184}{}{Obrigado pela informação. Adeus.}
{185}{}{Bem, claro. Todo mundo deseja uma audiência com o First Citizen. Infelizmente, seu tempo é apenas para assuntos de extrema importância.}
{186}{}{Você não parece importante o suficiente para garantir seu tempo, eu tenho medo.}
{187}{}{Por isso é vital falar com ela. Tenho certeza de lançar uma boa palavra sobre a eficiência com que o Escritório de Alfândega está sendo executado. Mas se você não pode me ajudar, então ...}
{188}{}{A informação que possuo é realmente importante. Mesmo.}
{189}{}{Se eu fosse você, eu assistiria o seu tom. Eu disse que preciso vê-la. Agora.}
{190}{}{Deixa pra lá então.}
{191}{}{Oh, diga. Eu vou correr até o primeiro cidadão para entregar a notícia pessoalmente.}
{192}{}{Bem, eu não disse que não poderia ajudá-lo, é só isso ... bem ... qual é o propósito de sua visita?}
{193}{}{Uh ... Eu tenho informações que ... podem levar a estabelecer uma rede de ... um, todos os cofres existentes em todo o país. É isso aí.}
{194}{}{Eu não posso falar com você pessoalmente, oficial, tanto quanto eu gostaria. É para os ouvidos do primeiro cidadão sozinhos. Por isso é vital falar com ela.}
{195}{}{Bem ... é ... uh, realmente, realmente importante. Eu mencionei o quão importante era?}
{196}{}{Uma ... rede de Vaults?}
{197}{}{Hmmmm. Bem ... hmmmm. Isso é MAIS irregular ...}
{198}{}{Sim. Uma rede ... de, uh, Vaults. Você vê, muitos não sabem disso ... mas a Cidade do Vault não era o único Vault para sobreviver. Há outros. Uma rede, por assim dizer.}
{199}{}{Eu não iria incomodá-lo se não fosse uma questão de extrema urgência, Oficial. Vou ter certeza de mencionar o quão útil você estava quando falo com o primeiro cidadão.}
{200}{}{Nevermind. Eu tive algumas outras perguntas que eu queria lhe fazer...}
{201}{}{Esqueça. I'll come back some other time.}
{202}{}{Bem ... certamente isso parece ser um assunto para o primeiro cidadão. Aqui está o seu Passo de Dia. Só é bom durante o dia - à noite, você será convidado a deixar a cidade. Os cidadãos também se reservam o direito de cancelar os privilégios do Passe de Dia a qualquer momento, então se comportam.}
{203}{}{Entendido. Posso fazer algumas outras perguntas?}
{204}{}{Obrigado.}
{205}{}{Não perca mais do meu tempo, Outsider. Sair.}
{206}{}{Eu sugiro que você vá agora, ou eu vou convocar os guardas.}
{207}{}{NÃO Uuu DEIXE-SE ou EU HIT U}
{208}{}{Shamble off}
{209}{}{Eu não estou indo a lugar nenhum. Você quer tentar me mover, vá em frente.}
{210}{}{Tudo bem, tudo bem.}
{211}{}{E, onde posso perguntar, você veio por esta cidadania fraudulenta? Estes números de série são os mesmos que os documentos da Cidadania roubados no mês passado.}
{212}{}{Se eu lhe disser, você vai me dar uma passagem de dia?}
{213}{}{Foi seu assistente, Skeev. Ele vendeu para mim.}
{214}{}{Eu não sei do que você está falando. Eu sou um cidadão.}
{215}{}{Hmmmm ... muito bem. Se você me disser, vou lhe dar um Passe de Dia. Agora, onde você conseguiu esses papéis?}
{216}{}{Foi seu assistente, Skeev. Ele vendeu para mim.}
{217}{}{Eu mudei de ideia. Não estou lhe dizendo nada.}
{218}{}{Você Outsider degenerou. Eu não sou um com quem ser incomodado! Você nunca põe o pé na nossa cidade agora! Saia antes de convocar os guardas!}
{219}{}{Vá em frente, ligue para eles. Eu vou lidar com eles depois de terminar de matar você.}
{220}{}{Estou indo embora. Para agora.}
{221}{}{Skeev? É assim que eu sou reembolsado por levá-lo como meu filho! Ele será tratado, asseguro-lhe.}
{222}{}{Para os meus problemas, posso obter uma passagem de dia?}
{223}{}{Claro. Posso fazer-te algumas perguntas?}
{224}{}{Sem problemas. Adeus.}
{225}{}{Skeev? Esse desgraçado ingrato! Isso será tratado imediatamente!}
{226}{}{Sem problemas. Posso fazer-te algumas perguntas?}
{227}{}{Ooooooh, estou com medo. Obrigado pela Day Pass, amigo.}
{228}{}{Entendido. Obrigado.}
{229}{}{Muito bem, você ganhou. Aqui está. O passe é bom apenas durante o dia; À noite, você será convidado a deixar a cidade. Os cidadãos também se reservam o direito de cancelar os privilégios Day Pass a qualquer momento, então se comportam.}
{230}{}{Consegui. Diga: Posso fazer algumas perguntas?}
{231}{}{Entendido. Obrigado.}
{232}{}{Desculpa. A menos que você tenha uma razão premente, não posso ajudá-lo.}
{233}{}{Uh ... mas eu tenho um motivo premente. Mesmo.}
{234}{}{Bem, eu tive algumas outras perguntas para você ...}
{235}{}{Mas eu sou o descendente do Vault Dweller original!}
{236}{}{Deixa pra lá então. Goodbye.}
{237}{}{Por quê, QUANDO TAMBÉM de mim. Eu deveria ter sabido que alguém da sua criação superior veio do estoque do Vault Dweller. Pah! Não desperdice mais do meu tempo, Outsider.}
{238}{}{Você me deixa entrar, e você me deixará entrar, ou a próxima coisa que é desperdiçada aqui é você.}
{239}{}{Tudo bem, vou embora.}
{240}{}{Muito bem. O que você queria saber?}
{241}{}{Olá, capitão. Existe algo com o que posso ajudá-lo?}
{242}{}{Olá, cidadão. Existe algo com o que posso ajudá-lo?}
{243}{}{Você novamente. Havia algo mais que você queria, ou ...?}
{244}{}{Claro, capitão. O que mais você queria saber?}
{245}{}{Claro, Cidadão. O que mais você queria saber?}
{246}{}{O que mais você queria saber?}
{247}{}{Frazz-urb-luuw!}
{248}{}{Shamble off}
{249}{}{O que é este lugar?}
{250}{}{Que tipo de envios você recebe aqui?}
{251}{}{Seu assistente, Skeev, está envolvido em práticas ilegais.}
{252}{}{Posso obter outro Passe de Dia?}
{253}{}{Encontrei a causa dos embarques abrandados da Redding.}
{254}{}{Encontrei o campo dos invasores.}
{255}{}{Encontrei o acampamento dos incursores e exterminou-os.}
{256}{}{O que você pode me falar sobre o seu líder?}
{257}{}{Nada hoje, obrigado.}
{258}{}{Nada mais hoje, obrigado.}
{259}{}{Depende de onde a caravana é proveniente. Recebemos remessas de muitos lugares ... Servos do Den, urânio de Broken Hills e minério de metal da Redding.}
{260}{}{O que você pode me falar sobre o Den?}
{261}{}{O que você pode me falar sobre Broken Hills?}
{262}{}{O que você pode me falar sobre Redding?}
{263}{}{Posso fazer-lhe outra pergunta?}
{264}{}{Entendo. Obrigado pela informação.}
{265}{}{É uma ... comunidade a oeste daqui. Muitas vezes, compramos servos de seus comerciantes. É um lugar bastante difícil, do que eu ouvi.}
{266}{}{Tenho certeza de que ... O servo apropriador ... como você tem um conhecimento muito mais profundo desse lugar do que eu.}
{267}{}{Um lugar encantador, na verdade. Assassinos, ladrões ... a escória Outsider usual. Um lugar onde um como você se sentiria em casa.}
{268}{}{O que você pode me falar sobre Broken Hills?}
{269}{}{O que você pode me falar sobre Redding?}
{270}{}{Eu tive algumas outras perguntas para você ...}
{271}{}{Obrigado pela informação.}
{272}{}{Pensava que eu pedi de qualquer maneira. Adeus.}
{273}{}{*Obrigado.* Goodbye.}
{274}{}{Broken Hills é uma cidade mineira ao sul. Como eu entendo, os mutantes minam o urânio, e eles o enviam aqui pela caravana.}
{275}{}{Eles parecem um pouco empolgantes, mas bons demais ... bem, bom o suficiente para os Estranhos, mesmo assim. Sem ofensa.}
{276}{}{Por curiosidade, quanto você paga pelo urânio?}
{277}{}{O que você pode me falar sobre o Den?}
{278}{}{O que você pode me falar sobre Redding?}
{279}{}{Uh, yeah... look, Eu tive algumas outras perguntas para você ...}
{280}{}{Nenhum tomado. Adeus.}
{281}{}{É uma cidade mineira muito a oeste. As caravanas de lá foram as mais agradáveis   para lidar, mas recentemente as remessas de minério diminuíram consideravelmente. Nos tem um pouco preocupado ... dependemos do seu minério um ótimo negócio.}
{282}{}{Eu sei por que as remessas da Redding diminuíram.}
{283}{}{O que você pode me falar sobre o Den?}
{284}{}{O que você pode me falar sobre Broken Hills?}
{285}{}{Entendo. Tive algumas outras questões ...}
{286}{}{Obrigado pela informação. Adeus.}
{287}{}{Você tem? Esta é uma excelente notícia! Por favor, informe o conselheiro McClure imediatamente.}
{288}{}{Você tem? Essa é uma excelente notícia! Deixe-me dar-lhe uma passagem de dia para que você possa falar com o conselheiro McClure. O passe é bom apenas durante o dia; À noite, você será convidado a sair. Agora vá.}
{289}{}{Posso fazer-lhe outra pergunta antes de eu ir?}
{290}{}{Eu farei isso.}
{291}{}{Vou falar com ele imediatamente.}
{292}{}{Engraçado você deve mencionar isso. O preço vem subindo até tarde ... nada que não podemos pagar,
 Mente você. Estamos certamente recebendo um melhor negócio do que o Gecko. Esses ladrões imundos precisam do urânio
 Muito mais do que nós.}
{293}{}{O que você pode me falar sobre o Den?}
{294}{}{O que você pode me falar sobre Redding?}
{295}{}{Entendo. Tive algumas outras questões ...}
{296}{}{Hmmm. Interesting. Obrigado pela informação.}
{297}{}{Nosso primeiro cidadão é Joanne Lynette. Ela fez muitas coisas boas para a nossa cidade em seus dez anos de serviço.}
{298}{}{Tal como?}
{299}{}{Ela manteve nossa cidade intocada pelo mundo exterior. Mesmo com a NCR pressionando-nos para se juntar ao
 A República e os ataques dos invasores, ela manteve nossa cidade forte. Agora há problemas com Gecko ....}
{300}{}{O que é o NCR?}
{301}{}{Quem são esses incursores?}
{302}{}{Qual é o problema com o Gecko?}
{303}{}{Posso fazer algumas outras perguntas?}
{304}{}{Desculpe ouvir isso. Talvez eu possa ouvir mais sobre isso em algum outro momento.}
{305}{}{NCR é a "Nova República da Califórnia". Eles afirmam que estão tentando unificar toda a Califórnia
 Sob um governo, mas podemos ver diretamente através de seu ruse patético.}
{306}{}{"Ruse?" Isso é uma arma que NCR h--?}
{307}{}{Ruse? Você tem certeza?}
{308}{}{Mesmo que fossem sinceros, por que queríamos compartilhar nossos recursos com os hackers
 E ladrões que vivem fora dessas paredes? Eu acho que não.*}
{309}{}{Entendo. O que você estava falando sobre os incursores antes?}
{310}{}{Quais são os problemas da Vault City com o Gecko?}
{311}{}{Posso fazer algumas outras perguntas?}
{312}{}{Isso é um pouco mais do que eu precisava saber. Adeus.}
{313}{}{Recentemente, experimentamos uma erupção de ataques de invasores particularmente brutais. Tivemos ataques em
 O passado, mas nada assim. Temo que esses invasores possam eventualmente violar nossas defesas de torreta a laser.}
{314}{}{Você não terá mais que se preocupar com esses invasores. Limpei-os.}
{315}{}{Você pode me dizer algo mais sobre esses incursores?}
{316}{}{Lamento ouvir isso. O que você disse sobre a NCR?}
{317}{}{Quais são os problemas da Vault City com o Gecko?}
{318}{}{Eles soam como um problema real. Eu te desejo sorte.}
{319}{}{Não muito. Não conseguimos achar de onde eles estão atrapalhando. Nosso Sargento Cidadão Stark
 Pode saber mais, mas ele está no Centro de Correções dentro da cidade.}
{320}{}{Se eu rastrear esses invasores, você vai me deixar na cidade?}
{321}{}{Tive algumas outras questões ...}
{322}{}{Eu vou ver o que eu posso descobrir sobre esses invasores.}
{323}{}{Obrigado pela informação.}
{324}{}{Certamente. Se você pode encontrar o acampamento base dos incursores, conceder-lhe-ei uma passagem de dia.}
{325}{}{I'll see what I can do. But first, Tive algumas outras questões ...}
{326}{}{É um acordo. Adeus.}
{327}{}{Você tem? Essa é uma excelente notícia! Por favor, diga ao First Citizen imediatamente.}
{328}{}{Você tem? Essa é uma excelente notícia! Deixe-me dar-lhe uma passagem de dia para que você possa contar ao primeiro cidadão.
 Aqui está. O passe é bom apenas durante o dia; À noite, você será convidado a sair. Agora vá.}
{329}{}{Antes de partir, posso fazer-lhe outra pergunta?}
{330}{}{Eu vou fazer isso.}
{331}{}{Obrigado. Goodbye.}
{332}{}{Oh, uh, esse não é o meu lugar para dizer. Você teria que falar com o primeiro cidadão sobre tais assuntos.}
{333}{}{O que você estava falando sobre a NCR?}
{334}{}{O que você estava falando sobre incursores?}
{335}{}{Ok, posso fazer algumas outras perguntas?}
{336}{}{Entendo. Bem, obrigado pela informação.}
{337}{}{UM GECK? Bem, isso não significa nada para mim ... e se não significa nada para mim, certamente significará
 Nada para o primeiro cidadão. Agora foi o que você queria ver o primeiro cidadão sobre ou
 Era outra coisa?}
{338}{}{Estou procurando um GECK para salvar minha aldeia.}
{339}{}{Olhe, deixe-me entrar, e eu vou deixar você continuar respirando.}
{340}{}{Deixa pra lá. Talvez falemos mais tarde.}
{341}{}{Obrigado pela sua ajuda, Outsider.}
{342}{}{Bem, como prometido, aqui está o seu Passo de Dia ... mas você vai sair da linha, eu o revogarei. Você me escuta?}
{343}{}{Oh, uh ... bem, eu sou um comerciante. Eu tinha planejado negociar com os outros comerciantes da cidade. Posso obter um passe de dia de você?}
{344}{}{Você é um comerciante? Mesmo. E o que você poderia vender? Minério? Algumas dessas peles de lagarto de wastelander imundo?}
{345}{}{(Olhares para o seu companheiro.) Ou você está procurando vender alguns servos?}
{346}{}{Sim, estou procurando vender alguns servos na cidade.}
{347}{}{Estou vendendo alguns desses ... uh ... peles de Gecko sujas.}
{348}{}{Na verdade, eu tenho algumas boas peles de Gecko de ouro comigo.}
{349}{}{Estou vendendo um pouco de minério de ouro.}
{350}{}{Estou vendendo um pouco de minério de urânio.}
{351}{}{Eu não tenho nenhuma dessas coisas ... ainda. Talvez eu esteja de volta.}
{352}{}{Na verdade, eu perdi mal. Desculpe incomodá-lo.}
{353}{}{Hmmmm. Bem, vamos ver o que você tem. Uma vez que eu inspecionar seu estoque, eu posso processar a papelada para o seu Passe de Dia.}
{354}{}{Tudo certo. Uh, tudo o que tenho é uma amostra do meu estoque aqui. O resto está em ... uh, minha caravana. Fora da cidade.}
{355}{}{Hmmmm. Muito bem.}
{356}{}{Bem, esta amostra é adequada.}
{357}{}{Existe uma taxa de passagem de dia para comerciantes, quinhentos dólares. Isso inclui privilégios de negociação diurna
 Vault City paredes e é bom por até cinco anos após a data de emissão.}
{358}{}{Tudo certo. Eu vou levar.}
{359}{}{Hmmm ... Isso é um pouco íngreme. Eu vou passar por agora.}
{360}{}{Quinhentos são um pouco mais do que eu posso pagar agora. Talvez outra hora.}
{361}{}{Excelente. Aqui você vai ... novamente, só é bom durante o dia - de noite você será convidado a deixar a cidade. Os cidadãos também se reservam o direito de cancelar os privilégios do Passe de Dia a qualquer momento, então se comportam.}
{362}{}{Entendido. Posso fazer algumas outras perguntas?}
{363}{}{Obrigado.}
