{100}{}{Você vê um terminal de aprendizado do Vault City.}
{101}{}{Este computador parece ser um sistema de ensino de algum tipo. Um amigável Pip Boy está do lado.}
{102}{}{Você vê o sistema de ensino de computadores do Vault City.}
{103}{}{Você brincadeira com o computador um pouco, mas você precisará usar alguma habilidade científica para realmente obter algo útil do terminal.}
{104}{}{Você passa algum tempo estudando os arquivos do computador.}
{105}{}{Você passa algum tempo estudando os arquivos, mas não aprende mais nada de importância.}
