{100}{}{Um terminal de computador.}
{101}{}{O protetor de tela está ativo}
{103}{}{Skynet Security Systems
                                  Intruder Level 2
                                                   Medidas de controle de ativação Nível 2
                        Medidas de contador - Transmissão interrompida
                        Ativando o Sistema Automatizado de Reparo}
{104}{}{Skynet Security Systems
                                     Intruder Level 2
                                             Medidas de controle de ativação Nível 2
                            Tentando redirecionar energia para geradores de campo}
{105}{}{Skynet Security Systems
                                 Intruder Level 2
                                                 Medidas de controle de ativação Nível 2}
{106}{}{Terminar o nível de alarme 2 - Falso alarme}
{107}{}{[Você percebe um botão no teclado com a ajuda rotulada.] Pressione a tecla.}
{108}{}{Corte em sistemas de segurança}
{109}{}{Tente desativar o alarme.}
{110}{}{Saída.}
{111}{}{Arg! [Você bate no punho no teclado com frustração.]}
{113}{}{Skynet Security Systems
                                         Atenção! Intruso Detectado Nível 1
                                Retina Scanner ativado
                                       Digitalização
                                                             Pesquisa de banco de dados}
{300}{}{ - ID confirmada}
{301}{}{Último acesso:}
{302}{}{Liberando o bloqueio do elevador}

{303}{}{Cabo Dixon}
{304}{}{General Clifton}
{305}{}{5 de dezembro de 2120}
{306}{}{ dias atrás.}

{114}{}{Skynet Security Systems
                                             Atenção! Nível Detectado por Intruso}
{307}{}{Skynet Security Systems
                                     Atenção! Níveis Detectados por Intruso:}
{115}{}{Ativar sistema de alarme nível 2}
{116}{}{Execute o programa de autodiagnóstico.}
{117}{}{Saída}
{118}{}{Arg! [Você bate no punho no teclado com frustração.]}
{120}{}{Skynet Security Systems
                                      O acesso a este terminal é negado}
{122}{}{Saída.}
{124}{}{Erro!
                                                                 Nenhum arquivo de programa está presente
                                            Por favor reinicie}
{126}{}{Saída}
{127}{}{Analisando Comando Aguarde ...
                                  Substituindo o Comando do Usuário
                                            Acesso negado}
{128}{}{[Mais]}
{129}{}{To Deactivate Alarm Press - 1
                                    To Run Diagnostic Program Press - 2
                             To Saída Press - 3}
{130}{}{Pressione 1}
{131}{}{Pressione 2}
{132}{}{Pressione 3}
{133}{}{Saída}
{134}{}{Atenção! Este programa funciona melhor se você desligar tudo
 Programas. Você deseja fazê-lo agora?}
{135}{}{Sim.}
{136}{}{Não.}
{137}{}{Saída}
{138}{}{Desligando o Programa de Segurança da Skynet
                         Analisando a estrutura de dados ...
                                     Diagnóstico Interrompido
                                    Programa de diagnóstico encerrado
                                   Reiniciando o Programa de Segurança
                                    Alarme de reinicialização
                                                      Sistema de Segurança Skynet - Status Ready}
{139}{}{Saída}
{140}{}{Acesso negado...
                                                  Acesso negado...
                                                  Acesso concedido
                                          Terminando sistemas de alarme Nível 2}
{141}{}{Saída}
{142}{}{Acesso não autorizado
                                        Iniciando o bloqueio de segurança deste terminal}
{143}{}{Saída}
{144}{}{Analisando Comando Aguarde ...
                           Terminar al ...
                                                         Override By Skynet Code 667
                                      O acesso a este terminal está terminado.}
{145}{}{Saída}
{146}{}{Saídaing Diagnostic Program.}
{147}{}{[Mais]}
