{100}{}{Você vê um terminal de computador ativo.}
{101}{}{Olhando de perto para o terminal, você observa o sinal dizendo "I * tel Inside".}
{102}{}{Você não consegue ler o que está no monitor.}

#NPC is unable to read what is on the monitor
{200}{}{ é incapaz de ler o que está no monitor.}

{103}{}{Potência principal = Offline
                       Poder de backup = Online
                                             Reiniciando o Programa de Segurança
                                  Aviso - Baixa Potência - Campos de força a 50%
                      Terminou de carregar ...
                                                  Skynet Security Check Point 1
                               Digite senha: _}
{104}{}{Skynet Security Check Point 1
                             Digite senha: _}
{105}{}{Tchaikovsky}
{106}{}{Open Says Me}
{107}{}{Serra}
{108}{}{Armageddon}
{109}{}{Hack em sistemas de segurança}
{110}{}{Você não tem uma pista. Saída.}
{113}{}{Campos de Força Desativados - Nível 1}
{115}{}{Saída}
{117}{}{O acesso a este terminal foi encerrado.}
{119}{}{Saída}
{121}{}{Erro 29
                                                            Incapaz de contactar o servidor
                                     Por favor reinicie}
{123}{}{Saída}
{124}{}{Acesso concedido
                                                 Campos de Força Nível 1: Desativado}
{125}{}{Saída}
{126}{}{senha inválida
                                                      Acesso negado
                                                      Digite senha: _}
{127}{}{Tchaikovsky}
{128}{}{Open Says Me}
{129}{}{Serra}
{130}{}{Armageddon}
{131}{}{Hack em sistemas de segurança}
{132}{}{Você não tem uma pista. Saída.}
{133}{}{[Pressionar <Ctrl> <Alt> <C> faz com que o programa falhe. Você espera que o resto das medidas de segurança seja tão fácil de derrotar.]}
{134}{}{Saída.}
{135}{}{Nível de violação de segurança 1
                                   Ativando o Protocolo de Segurança
                                   O acesso do usuário a este terminal é encerrado
                      Transmissão final}
{136}{}{Saída}
{137}{}{A sua ineptidão causou que você desencadeie o sistema de alarme.}
{138}{}{Não adianta, o programa é muito complicado para você entender.}
{139}{}{Saída}

{300}{}{O computador parece ter algum tipo de mecanismo de defesa.}
{301}{}{Você está chocado por}
{302}{}{ está chocado com}
{303}{}{ pontos de dano.}
