{100}{}{Um terminal de computador.}
{101}{}{O protetor de tela está ativo.}
{102}{}{Você não consegue ler o que está no monitor.}
{103}{}{Skynet Security Systems
                                            Intruder Level 1
                                                  Medidas de ativação do contador Nível 1
                              Medidas de contador - Transmissão interrompida
                        Ativando sistemas de reparo automatizados}
{104}{}{Skynet Security Systems
                                            Intruder Level 1
                                                  Medidas de ativação do contador Nível 1
                        Tentando redirecionar energia para geradores de campo}
{105}{}{Skynet Security Systems
                                           Intruder Level 1
                                               Medidas de ativação do contador Nível 1}
{106}{}{Terminar o nível de alarme 1 - Alarme falso}
{107}{}{[Você percebe uma tecla no teclado com a etiqueta "Ajuda"]. Pressione a tecla.}
{108}{}{Corte em sistemas de segurança}
{109}{}{Saída}
{110}{}{Arg! [Você bate seu punho no teclado com frustração]}
{112}{}{Skynet Security Systems
                                           Intrusos detectados - Perímetro exterior
                       Realizações automatizadas iniciadas
                                    Porta principal - mau funcionamento
                                    Reinicializando ...
                                                     Main Door informa que os parafusos de bloqueio ainda estão no lugar
                    Retornando ao modo de economia de energia}
{113}{}{Ativar sistema de alarme Nível 1}
{114}{}{Execute o programa de autodiagnóstico.}
{115}{}{Saída}
{116}{}{Arg! [Você bate seu punho no teclado com frustração]}
{118}{}{Skynet Security Systems
                                          O acesso a este terminal é negado.}
{120}{}{Saída}
{122}{}{Erro 29
                                                             Incapaz de contactar o servidor
                                           Por favor reinicie}
{124}{}{Saída}
{125}{}{Analisando Command Please Wait ..
                                    Concedido
                                                             Terminando Sistemas de Alarme Nível 1}
{126}{}{[With security as shoddy as this, it's no wonder they blew themselves up.] Saída}
{127}{}{[A menu appears]
                                                   To Deactivate Alarm Press - 1
                                     For Diagnostic check Press - 2
                                   To Saída Press - 3}
{128}{}{Pressione 1}
{129}{}{Pressione 2}
{130}{}{Pressione 3}
{131}{}{Atenção! Este programa funciona melhor se você desligar todos os programas. Você deseja fazê-lo agora?}
{132}{}{sim}
{133}{}{Não}
{134}{}{Saída}
{135}{}{Desligando todos os programas
                                  Desligando o Programa de Segurança Skynet - Nível 1
        O sistema da última vez foi diagnosticado em 15 de outubro de 1990
        Sistema de análise ...
                                             Tempo estimado até a conclusão 99: 24: 60: 60}
{136}{}{[You don't think this is going to be done any time soon.] Saída.}
{137}{}{Acesso negado
                                                 Acesso negado
                                                 Jzaedd negou
                                                       Quada Adjfjef
                                                 Acesso concedido
                                                 Terminando Sistemas de Alarme Nível 1}
{138}{}{Saída}
{139}{}{Acesso não autorizado
                                            Iniciando bloqueio de segurança do terminal remoto
                  O acesso do usuário a este terminal é TERMINADO}
{140}{}{Saída}

{200}{}{Computador em modo de diagnóstico. Aguarde até a rotina de diagnóstico terminar.}
