{100}{}{Um terminal de computador.}
{101}{}{Fotos de mulheres escassamente vestidas estão afixadas em vários pontos no computador.}
{102}{}{Você não consegue ler o que está no monitor.}
{103}{}{Terminal de acesso às munições
                                        Campo de Força - Desativado
                                              Placas de Choque - Desabilitadas}
{104}{}{Terminal de acesso às munições
                                         Campo de Força - Desativado
                                         Chapas de Choque - Ativo}
{105}{}{Terminal de acesso às munições
                                     Campo de força - ativo
                                                  Placas de Choque - Desabilitadas}
{106}{}{Terminal de acesso às munições
                                         Campo de força - ativo
                                                  Chapas de Choque - Ativo}
{107}{}{Disable Shock Plates}
{108}{}{Disable Force Fields}
{109}{}{Ler o correio}
{110}{}{Saída}
{111}{}{[Não importa como você tente, as linhas squiggly não fazem sentido para você.]}
{112}{}{Disable Shock Plates
                                               Digite a senha:}
{113}{}{Hack em sistemas de segurança}
{114}{}{Guess Password}
{115}{}{Retornar ao menu principal}
{116}{}{Saída}
{117}{}{[Este programa é muito complexo para você entender.]}
{118}{}{Retornar ao menu principal.}
{119}{}{Saída}
{120}{}{[Você consegue ignorar a senha e desligar as Placas de Choque.]}
{121}{}{Retornar ao menu principal}
{122}{}{Saída}
{123}{}{Disable Force Fields
                                                  Digite a senha:}
{124}{}{Hack em sistemas de segurança}
{125}{}{Guess Password}
{126}{}{Retornar ao menu principal}
{127}{}{Saída}
{128}{}{[Os arquivos são criptografados e sem um decodificador você não consegue ler nada.]}
{129}{}{Retornar ao menu principal}
{130}{}{Saída}
{131}{}{[Mero jogo infantil. Os campos de força estão agora desativados.]}
{132}{}{Retornar ao menu principal}
{133}{}{Saída}
{134}{}{[Alguém esqueceu de fechar sua caixa postal.]
                     Confirmação de pedido
                                                Aviso para Evacuar
                                                   Cumprimentos de correspondência
                                                      Comércio}
{135}{}{[Escolha um arquivo para ler]}
{136}{}{Leia a confirmação da ordem}
{137}{}{Leia o Aviso para Evacuar}
{138}{}{Leia os cumprimentos do penpal}
{139}{}{Leia Comércio}
{140}{}{Retornar ao menu principal}
{141}{}{Saída}
{142}{}{Isto é para confirmar o seu pedido de vídeo para Debbie Does the Army e Deep Throat volume 1059. Seu pedido deve chegar por correio em 2-4 semanas. Obrigado pelo seu pedido.}
{143}{}{Leia mais e-mail}
{144}{}{Saída}
{145}{}{A evacuação do Sierra Army Depot foi movida para cima por uma semana. Todas as medidas de segurança devem estar em vigor até então. Por ordem do general Clifton.}
{146}{}{Leia mais e-mail}
{147}{}{Saída}
{148}{}{[Você ouve um leve ruído de zumbido quando a fumaça começa a subir do terminal do computador. Você fica de pé e vê como o teclado se derrete em uma poça de goo. Hmm ... deve ter sido um desses vírus que você está ouvindo.]}
{149}{}{Saída}
{150}{}{Este é o Klinger do 8063. Estamos em necessidade desesperada da peça número 102-53B. Eu tenho um caso de Chateau Lafayette 2155 se você puder agilizar o pedido. Volte para mim o mais rápido possível.}
{151}{}{Leia mais e-mail}
{152}{}{Saída}
{153}{}{[Que sorte incrível! Você consegue adivinhar a senha correta. "Hooters"]
                                                Desativando placas de choque}
{154}{}{Retornar ao menu principal}
{155}{}{Saída}
{156}{}{[Não importa o quão difícil você tente, não pode adivinhar a senha.]}
{157}{}{Retornar ao menu principal}
{158}{}{Saída}
{159}{}{[Esta pessoa deve ter uma infatuação com seios. A senha era "mamilos"]
                                Desativando campos de força}
{160}{}{Retornar ao menu principal}
{161}{}{Saída}
{162}{}{[Não importa o quão difícil você tente, não pode adivinhar a senha.]}
{163}{}{Retornar ao menu principal}
{164}{}{Saída}
{165}{}{[De alguma forma, sua adulteração faz com que o terminal exploda no seu rosto.]}
{166}{}{Saída}

{200}{}{[Este terminal não está mais operacional.]}
