#############################################################
#  Message File: ZCBrahmn.msg                               #
#                                                           #
#       Body Type:  Brahmin                                 #
#       Combat AI: None                                     #
#       Weapons: None                                       #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Você vê um brahmin doméstico domesticado.}
{101}{}{O motivo do brahmin com duas cabeças é devido a
 Exposição precoce da radação ao que costumava ser chamado de
 vaca.}
{102}{}{Você não percebe nada de incomum no brahmin.}
{103}{}{Brahmin não é muito para conversas.}
{104}{}{Você não tem nada a fazer melhor do que sentar em torno de falar
 Para uma vaca de duas cabeças?}
{105}{}{É um brâmane. Tem duas cabeças.}

{201}{}{Mooo ...}
{202}{}{Mooo Mooo Mooo ...}
{203}{}{Mooo ...}
{204}{}{Moooooo ...}
{205}{}{Mooooooooo ...}
{206}{}{:: GRUNHIDO ::}
