{100}{}{Você vê um homem com um olho afiado e uma atitude de negócios.}
{101}{}{Você vê um comerciante de craps.}
{102}{}{Ele tem uma vara e muitas fichas. Você poderia tentar sua sorte com ele.}

{103}{}{Faça suas apostas. Temos outro rolo.}
{104}{}{Quanto você apostará no PASSLINE?}
{105}{}{Quanto você apostará no DO PASSLINE?}
{106}{}{Quanto você apostará no COMELINE?}
{107}{}{Quanto você apostará no NÃO COMELINE?}
{108}{}{Quanto você apostará no FIELD?}
{157}{}{Quanto você apostará no seu PLACEBET?}
#options
# 2 3 12 crap out. 7 11 win auto..

{109}{}{Point's on}

{110}{}{Passar linha.}
{111}{}{Não faça Passar linha.}

{112}{}{Venha linha.}
{113}{}{Não faça Venha linha.}

{114}{}{Apostas de proposição ...}
{115}{}{Coloque apostas ...}
{116}{}{Apostar em campo}
{118}{}{Lista}

{119}{}{Aposta de linha de passagem definida em:}
{120}{}{Não passe a linha de aposta definida em:}
{121}{}{Venha linha definida em:}
{122}{}{Não venha definir a linha em:}

{123}{}{7:}
{124}{}{D3s:}
{125}{}{D4s:}
{126}{}{D5s:}
{127}{}{D2s:}
{128}{}{1 e 2:}
{129}{}{5 e 6:}
{130}{}{1 e 1:}
{131}{}{6 e 6:}
{132}{}{Craps:}

{133}{}{Pls 4:}
{134}{}{Pls 5:}
{135}{}{Pls 6:}
{136}{}{Pls 8:}
{137}{}{Pls 9:}
{138}{}{Pls 10:}

{139}{}{Em 4:}
{140}{}{Em 5:}
{141}{}{Em 6:}
{142}{}{Em 8:}
{143}{}{Em 9:}
{144}{}{Em 10:}

{145}{}{Probabilidades 4:}
{146}{}{Probabilidade 5:}
{147}{}{Probabilidades 6:}
{148}{}{Probabilidades 8:}
{149}{}{Probabilidades 9:}
{150}{}{Odds 10:}

{151}{}{Aposta de campo definida em:}

{152}{}{Qual PROPOSIÇÃO BET?}
{153}{}{Quantos?}
{154}{}{Single Lista bets...}
{155}{}{Apostas Hardway ...}
{156}{}{Que tipo de aposta?}

#proposition bets
{200}{}{Rolo 7 (5 a 1 saldar)}
{201}{}{Duplo 3s (10 a 1 saldar)}
{202}{}{Duplo 4s (10 a 1 saldar)}
{203}{}{Duplo 5s (8 a 1 saldar)}
{204}{}{Duplo 2s (8 a 1 saldar)}
{205}{}{1 e 2 (15 a 1 pagam)}
{206}{}{5 e 6 (15 a 1 pagam)}
{207}{}{1 e 1 (30 a 1 pagam)}
{208}{}{6 e 6 (30 a 1 pagam)}
{209}{}{Qualquer Craps (8 para 1 saldar)}

#place bets
{299}{}{Qual é o LUGAR BET?}
{300}{}{Em 4 (1.8 pay off)}
{301}{}{Em 5 (1.4 saldar)}
{302}{}{Em 6 (1.16 pagar)}
{303}{}{Em 8 (1.16 pagar)}
{304}{}{Em 9 (1.4 pay off)}
{305}{}{Em 10 (1.8 saldar)}

{400}{}{Costas...}

{500}{}{$}
{501}{}{.}

#reward messages
#pass line strings
{600}{}{Sete pague as linhas, aponte.}
{601}{}{Onze pagam as linhas.}
{602}{}{Dois, os craps perdem as linhas.}
{603}{}{Três, craps perdem as linhas.}
{604}{}{Doze, craps perdem as linhas.}

#don't pass line strings
{610}{}{Sete perdem as linhas não, aponte.}
{611}{}{Eleven solta as linhas não.}
{612}{}{Dois, craps pagam as linhas não.}
{613}{}{Três, craps pagam as linhas não.}
{614}{}{Doze, craps empurrar as linhas não.}

#proposition begs
{620}{}{Prop 7}
{621}{}{Prop. Dobro de 3s}
{622}{}{Prop bet double 4s}
{623}{}{Prop bet double 5s}
{624}{}{Prop bet double 2s}
{625}{}{Prop 1 e 2}
{626}{}{Prop 5 e 6}
{627}{}{Prop 1 e 1}
{628}{}{Aposta da proposta 6 e 6}
{629}{}{Prop bet Craps 2,3,12}
{630}{}{Perde!}
{631}{}{Ganha!}

#place bets
{650}{}{Coloque a aposta 4}
{651}{}{Coloque a aposta 5}
{652}{}{Coloque a aposta 6}
{653}{}{Coloque a aposta 8}
{654}{}{Coloque a aposta 9}
{655}{}{Coloque a aposta 10}

#field bets
{660}{}{Aposta de campo 2 ganha o dobro.}
{661}{}{Aposta de campo 3 vitórias.}
{662}{}{Aposta de campo 4 vitórias.}
{663}{}{Aposta de campo 9 vitórias.}
{664}{}{Aposta de campo 10 vitórias.}
{665}{}{Aposta de campo 11 vitórias.}
{666}{}{Aposta de campo 12 vitórias triplas.}
{667}{}{Aposta de campo perde.}

#flat bet
{670}{}{Aposta plana 4}
{671}{}{Aposta plana 5}
{672}{}{Aposta plana 6}
{673}{}{Aposta plana 8}
{674}{}{Aposta plana 9}
{675}{}{Aposta plana 10}

{680}{}{Aposta de sorte 4}
{681}{}{Odds bet 5}
{682}{}{Odds bet 6}
{683}{}{Aposta de sorte 8}
{684}{}{Odds bet 9}
{685}{}{Odds bet 10}

{700}{}{Nenhuma chance de ponto retornou.}
{701}{}{Toque}
{702}{}{Não faça}

{710}{}{Die1:}
{711}{}{Die2:}

{712}{}{Desculpe, tenho que sair.}
{713}{}{Desculpe, não quero fazer essa aposta.}
{714}{}{O ponto está fora.}

#odds bet stuff
{800}{}{Take Odds on Toque Numbers.}
{801}{}{Escolha o multiplicador de probabilidades. Probabilidades sobre:}
{802}{}{X's odds.}
{803}{}{Atualmente em:}
{804}{}{Odds bet on 4.}
{805}{}{Odds bet on 5.}
{806}{}{Odds bet on 6.}
{807}{}{Odds bet on 8.}
{808}{}{Odds bet on 9.}
{809}{}{Odds bet on 10.}
{810}{}{Apostar em qual número?}

{1100}{}{Você vê uma mulher com um olho afiado e uma atitude de negócios.}
{1102}{}{Ela tem uma vara e muitas batatas fritas. Você poderia tentar sua sorte com ela.}
