{100}{}{Você vê uma mesa Black Jack.}
{101}{}{Você vê um negociante da Black Jack.}
# Cuide de jogar um Black Jack? Aposta mínima é $(money amount).
{102}{}{Cuide de jogar um Black Jack? Aposta mínima é $}
{103}{}{.}
{104}{}{Certo.}
{105}{}{Não, obrigado.}
{106}{}{Wuh blak juk?}
{107}{}{Desculpe, você não parece ter o valor mínimo da aposta. Volte quando
 você tem mais dinheiro.}
{108}{}{Okey, todas as apostas mínimas estão em.}
{109}{}{[acordo]}
#Esta é uma mesa Black Jack. Aposta mínima é $(dollar amount).
{110}{}{Esta é uma mesa Black Jack. Aposta mínima é $}
{111}{}{.}
# Você desenha um(card fás like #201-213) do(card suit like #251-254), a
#    (card fás like #201-213) do(card suit like #251-254) and a
#    (card fás like #201-213) do(card suit like #251-254) for
#    (Black Jack, umabust, or the total dothe cards ranging from 15-21)
{112}{}{Você desenha um}
{113}{}{ do}
{114}{}{, uma}
{115}{}{ e um}
{116}{}{ para}
{117}{}{. Black Jack}
{118}{}{. Busto}
{119}{}{.}
# this is to replás the first part dothe previous dialogs with the dealer
#    instead, it just repláss #112
{120}{}{O revendedor tem um}
{121}{}{[Mais]}
{122}{}{[enquanto remaneja] Cuide para jogar de novo?}
{123}{}{Desculpe, acho que você chegou ao seu limite aqui. Eu vou ter que pedir que você vá embora.}
{124}{}{Você ganha a mão.}
{125}{}{O revendedor ganha a mão.}
{126}{}{O jogo é um empurrão.}
{127}{}{Claro, não há problema.}
{128}{}{Vou mostrar-lhe o meu limite.}
{129}{}{Você não pode mais jogar aqui. Por favor saia.}
{130}{}{Oh, desculpe.}
{131}{}{Você ganha $}
{132}{}{.}

{201}{}{ás}
{202}{}{dois}
{203}{}{três}
{204}{}{quatro}
{205}{}{cinco}
{206}{}{seis}
{207}{}{Sete}
{208}{}{oito}
{209}{}{nove}
{210}{}{dez}
{211}{}{Jack}
{212}{}{rainha}
{213}{}{rei}

{251}{}{Corações}
{252}{}{Diamantes}
{253}{}{Espadas}
{254}{}{Clubes}
