# 0. QUICK LOOK
{100}{}{Você vê um revendedor.}
{101}{}{Você vê uma tabela de dados.}
# has no gambling skill messages
{110}{}{Você vê uma garota.}
{111}{}{Você vê uma mesa.}

# 0. EXAMINES
# table
{140}{}{Você vê uma mesa para jogar jogos de dados.}
# no skill
{141}{}{Você vê uma mesa com coisas nele.}

# dealer
{150}{}{Você vê um dos revendedores de cassinos.}
{151}{}{Você vê um dos revendedores de cassinos. She motions for you to come over and play.}
{152}{}{Você vê um dos revendedores de cassinos. Her dress barely covers her body.}
{153}{}{Você vê um dos revendedores de cassinos. Ela tem alguns gams agradáveis.}
{154}{}{Você vê um dos revendedores de cassinos. Ela piscou para você.}
{155}{}{Você vê um dos revendedores de cassinos. She smells reeeally nice.}
# no skill
{160}{}{Você vê uma mulher bonita.}
{161}{}{Ela está acenando para que você venha.}
{162}{}{Seu vestido é meio pequeno.}
{163}{}{Ela tem alguns gams agradáveis.}
{164}{}{Ela piscou para você.}
{165}{}{Ela cheira bem legal.}

# use gambling skill on dealer
# dealer dice amounts are screwed up
{175}{}{NENHUM DICE !!!}
{176}{}{DEMASIADO DICE !!!}
# dealer has loaded dice planted by player
{177}{}{As chances parecem ser verdadeiras desde que você trocou os dados.}
{178}{}{As chances não parecem bem.}
{179}{}{Você não pode avaliar as probabilidades para certo.}
# dealer has regular dice
{185}{}{As chances parecem corretas.}
{186}{}{Você não pode avaliar as probabilidades para certo.}
{187}{}{As chances não parecem bem.}

# 2. FLOAT [ENCLAVE_DESTROYED == TRUE]
{200}{}{::Felicidades::}
{201}{}{:: Claps ::}
{202}{}{:: Whistles ::}
{203}{}{}
{204}{}{Achei que você havia se esquecido de nós enquanto você estava fora de salvar o mundo.}

# 3. FLOAT [MADE MAN, SAME CASINO] (WTG)
{215}{}{Olá,}
{216}{}{Se você está procurando uma pequena empresa mais tarde ...}
{217}{}{Ei, você ... [piscadinha] ... você está procurando apostar?}
{218}{}{Ele parece tão ... [arrepios] ... perigoso.}
{219}{}{Bem-vindo ao cassino,}
{220}{}{Dê uma boa palavra com o chefe para mim?}
{221}{}{Olá,ma'am. Deixe-me saber se posso ajudá-lo com qualquer coisa.}
{222}{}{Olhando para apostar, senhora?}
{223}{}{Ela parece tão ... [arrepios] ... perigoso.}

# 5. FLOAT [MADE MAN, WRONG CASINO] (WTG)
{235}{}{Parece que este já está jogando com sua vida.}
{236}{}{Uh, acho que ele entrou no cassino errado ...}
{237}{}{Se ele não partir antes que os meninos o vejam ...}
{238}{}{Uh-oh. Problema…}
{239}{}{Parece que este já está jogando com sua vida.}
{240}{}{Uh, acho que ela entrou no cassino errado ...}
{241}{}{Se ela não partir antes que os meninos a vejam ...}

# 7. FLOAT [MALE, PRIZEFIGHTER] (WTG)
{250}{}{Ei, músculos. Você está procurando gastar algumas fichas?}
{251}{}{Ei, campeão ... [piscadinha] ... você está olhando para jogar?}
{252}{}{Ei, campeão ... [sorrisos] ... quer ter uma chance?}
{253}{}{Se você está procurando uma pequena empresa mais tarde ...}
{254}{}{Eu me pergunto se eu deveria conversar com ele ...}
{255}{}{Ei,}
{256}{}{Se você está olhando para ganhar algumas fichas, você veio ao lugar certo.}
{257}{}{Lady Luck está na casa esta noite ... nada além de vencedores!}
{258}{}{Passa para a direita,}
{259}{}{Precisa de outra bebida?}
{260}{}{Bem-vindo ao cassino,}
{261}{}{Olá,}
{262}{}{Procurando apostar,}
{263}{}{Bem-vindo ao cassino,}

# 9. FLOAT [PORN STAR] (WTG)
{270}{}{Ei, cara do filme. Você está procurando gastar algumas fichas?}
{271}{}{Ei,}
{272}{}{Ei,}
{273}{}{Se você está olhando para ganhar algumas fichas}
{274}{}{Lady Luck está na casa esta noite ... nada além de vencedores!}
{275}{}{Passa para a direita,}
{276}{}{Precisa de outra bebida?}
{277}{}{Bem-vindo ao cassino,}
{278}{}{Olá, Sra. Estrela do Filme. Olhando para gastar um cheque de pagamento?}
{279}{}{Você dança esta noite?}

# 11. FLOAT [MALE, NO REP] (WTG)
{290}{}{Ei, querida. Você está procurando gastar algumas fichas?}
{291}{}{Ei,sweetie…[winks]…you looking to gamble?}
{292}{}{Ei,sweetie…[smiles]…wanna take a chance?}
{293}{}{Se você está olhando para ganhar algumas fichas, você veio ao lugar certo.}
{294}{}{Lady Luck está na casa esta noite ... nada além de vencedores!}
{295}{}{Passa para a direita,win some chips.}
{296}{}{Precisa de outra bebida, querida?}
{297}{}{Bem-vindo ao cassino,honey.}
{298}{}{Esta tabela é gratuita se você está procurando jogar ...}
{299}{}{Ei, querida. Você está procurando gastar algumas fichas?}
{300}{}{Procurando apostar,honey?}
{301}{}{Bem-vindo ao cassino,honey.}

# 13.  PLACE YOUR BETS (WTG)
{320}{}{[O negociante olha para você nervosamente, então mastica o lábio.]Um, coloque suas apostas ... aposta mínima $}
{321}{}{Coloque sua aposta, senhor. Aposta mínima $}
{322}{}{Faça a sua aposta, senhora. Aposta mínima $}
{323}{}{Faça suas apostas, aposta mínima $}
{324}{}{Eu melhor que você}
{325}{}{Eu toco craps em calças}
{326}{}{Qual é esse jogo? Você pode apostar na pele gecko? Eu tenho geck ... ooooh ... lindas luzes! [Afastar-se.]}
{327}{}{[Você tem $}
{328}{}{Apostar $}
{329}{}{Whoa, muito rico para o meu sangue.}
{330}{}{Nenhuma aposta hoje, obrigado.}
{331}{}{Uhhh, desculpe, eu não sei como jogar esses jogos loucos.}

# 14.  RETARD (14)
{340}{}{Um ... eu ouço que eles estão deixando os cérebros de volta. Talvez você deva verificá-lo.}
{341}{}{Uh, muito bem, senhor. Volte logo.}
{342}{}{Uh, muito bem, senhora. Volte logo.}
{343}{}{Byeee-byeeee}
{344}{}{Gooodie.}
{345}{}{Uh ... cérebro ... o que eles ?! Eu vou ver!}

# 15. POOR MAN (13)
{350}{}{Muito bem, senhor. Volte logo.}
{351}{}{Muito bem, senhora. Volte logo.}
{352}{}{[O negociante ergue uma sobrancelha.]$}
{354}{}{Eu vou, obrigado.}
{355}{}{Talvez assim.}

# 16. LOOOOOOSER (13)
{400}{}{Desculpe, melhor sorte na próxima vez.}
{401}{}{Desculpe senhor. Mais sorte da próxima vez.}
{402}{}{Desculpe, senhora. Mais sorte da próxima vez.}

{410}{}{Vencedora!}
{411}{}{Vencedora! Well done, sir!}
{412}{}{Vencedora! Well done, ma'am!}

{420}{}{Vencedora! You've doubled your money!}
{421}{}{Vencedora! You've doubled your money! Well done, sir!}
{422}{}{Vencedora! You've doubled your money! Well done, ma'am!}

{430}{}{Vencedora! You've tripled your money!}
{431}{}{Vencedora! You've tripled your money! Luck is in the house tonight! Well done, sir!}
{432}{}{Vencedora! You've tripled your money! Luck is in the house tonight! Well done, sir!}

{440}{}{Ligue para um dia.}
{441}{}{Ligue para uma noite.}

#17. TABLE TAMPER
{450}{}{Desculpe, esta tabela foi fechada. Alguém tem adulterado os dados.}
{451}{}{Desculpe, senhor, esta tabela foi fechada. Alguém tem adulterado os dados.}
{452}{}{Desculpe, senhora, esta tabela foi fechada. Alguém tem adulterado os dados.}
{453}{}{Uhhh, ok.}
{454}{}{Desculpe ouvir isso. Obrigado.}

# message parts
{2203}{}{! Bem-vindo ao cassino,hero!}
{2215}{}{. Posso lhe ajudar com algo?*}
{2219}{}{.}
{2255}{}{. Olhando para gastar algumas fichas?}
{2258}{}{, ganhe algumas fichas.}
{2260}{}{.}
{2261}{}{. Deixe-me saber se posso ajudá-lo com qualquer coisa.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{. Faça suas apostas…}
{2327}{}{.]}
{2328}{}{.}
{2344}{}{ sempre pode usar novo item de inventário [Deixar.]}
{2352}{}{? 'Too rich for your blood?' [Scoffs.]Pal, you're in the wrong town.}
{2353}{}{? 'Too rich for your blood?' [Scoffs.]Girl, you're in the wrong town.}
