#############################################################
#  Message File: ziGenGrv.msg                               #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 15, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

# 100-199 are for grave site messages
{100}{}{Você vê um túmulo.}
{101}{}{Você vê uma sepultura descoberta.}
{102}{}{Este é um túmulo.}
{103}{}{Esta sepultura foi descoberta.}
{150}{}{O túmulo foi coberto.}
{151}{}{O túmulo foi descoberto.}

# 200 on are all for headstones
{200}{}{Você vê uma lápide.}
{201}{}{Você vê um marcador grave.}

# 250 + long descriptions
# generic no name sites
{250}{}{Não há marcações nesta lápide.}
{251}{}{O nome na lápide foi arranhado.}
{252}{}{O nome na lápide lê John Doe.}
{253}{}{O nome e a data desta lápide foram desgastadas pelo clima.}
# for crosses
{260}{}{Não há marcas neste marcador grave.}
{261}{}{O nome no marcador da sepultura foi arranhado.}
{262}{}{O nome no marcador da sepultura lê John Doe.}
{263}{}{O nome e a data desta lápide foram desgastadas pelo clima.}

# leader
{275}{}{A lápide lê:}
{276}{}{O marcador grave diz:}

# specific cases
{300}{}{"Aqui está Chris Avellone, Rei da Dança".}
{301}{}{"Chris Jones. Nightwing".}
{302}{}{"Christopher Michael Holland, também conhecido como" Chris Holland ", também conhecido como" Chris ": há dois motivos e meio para ler esta lápide ... Normalmente, você esperaria que esses motivos fossem listados".}
{303}{}{"Colin McComb: Outra vida inútil"}
{304}{}{"David Hendee: o mais alto entre os mortos. Pode descansar em paz, em silêncio".}
{305}{}{"Ed Hyland. Ele disse ao mundo para" aspirar ".}
{306}{}{"Eric Elimínio. O TRUE Combat Boy".}
{307}{}{"Feargus Urquhart: fez apenas uma lista muito grande".}
{308}{}{"Fred Hatch. Morrei gravando a voz de Myron".}
{309}{}{"Gary Platner. Matou por não fazer mais modelos Cidadão do Vault".}
{310}{}{"Jason Anderson: não é mais um deus vivo".}
{311}{}{"Jason G. Suinn".}
{312}{}{"Jason Taylor".}
{313}{}{"Jeremy Barnes. O macaco de cabeça calva da Ilha Negra".}
{314}{}{"Jesse Reynolds. O gengibre gosta muito. Muito."}
{315}{}{"John Deiley".}
{316}{}{"John Price".}
{317}{}{"Leonard Boyarski. Exile from Vault City".}
{318}{}{"Rupert Dinkos, morreu Winter '00".}
{319}{}{"Matt Norton. Ele poderia ter sido alguém. Ele poderia ter sido uma contenda, em vez de um vagabundo, que era o que ele era".}
{320}{}{"Nick Kesting". [Há um pequeno balde de balas de cobre redondas na parte superior]}
{321}{}{"Robert Collier. Silencioso. Deadly. Rob."}
{322}{}{"Robert Hertenstein 2. Seu médico tentou dizer a ele, mas ele insistiu:" Esse é um pouco demais de informação ".}
{323}{}{"Scott Campbell. Não é a sopa".}
{324}{}{"Aqui está Scott Everts. Tarde para o trabalho. Tarde pela vida".}
{325}{}{"Scott Rodenhizer. Built 3D heads".}
{326}{}{"Thomas French: morreu enquanto tentava dominar a Guillotina Voadora".}
{327}{}{"Tim Cain. Fundador, amante, lutador, programador".}
{328}{}{"Tramell Ray Isaac: Ouça é um dos homens mais trabalhadores do mercado. Animator extraordinare (sp?). Penso. R..P. T.Ray"}
{329}{}{"Zeb - ainda mais antigo do que a sujeira"}
{330}{}{"Dennis Presnell. Nós podemos quase aqui ele agora." Você chama isso de funeral ?! Isso nunca foi morrendo novamente! Blah blah blah ... "Arranha abaixo, diz, "Deus descanse" Cryin 'D, deveria ter mantido o remendo ".}
{331}{}{"Rupert Diukos, morreu 24/9/96"}
{332}{}{"Sal De Ban, morreu 24/9/96"}
{333}{}{"Greg Zeschule, Fall '99"}
{334}{}{"Ray Muzyka, Summer '98"}
{335}{}{"Evan Chantland, 74 -: Ele não era paranóico, eles realmente estavam atrás dele".}
{336}{}{"Aqui está Moose, frio e morto. Nós o encontramos aqui, sem a cabeça dele."}
{337}{}{"Amy Presnell"}
{338}{}{"Stephen Bokkes, de 25 anos. Reduzido em seu auge pelas lanças e flechas da fortuna ultrajante".}
{339}{}{"R.I.P. Doug" Skully "Finch (Data não importa) Morto por fumar no mercado francês. Últimas palavras -" Donkey Punches to ya! "}
{340}{}{"Aqui está Donnie Cornwell, bom e morto. Em um caixão extra grande para caber sua cabeça extra grande".}
{341}{}{"Rob Giampa viveu sua vida como se ele gostasse de suas mulheres: rápido, barato e fácil".}
{342}{}{"T. D. Hamilton: Ouça mentiras uma pipa forte que deveria ter morrido há muito tempo. Descanse no inferno, BITCH!"}
{343}{}{"Outra vítima do prazo".}
{344}{}{"Dogbomb está morto. Viva o cão".}
{345}{}{"Kris Snider: muito competitivo"}
{346}{}{"Você está fazendo algo útil com sua vida?"}
{347}{}{"Por que não se matar e salvar alguém com dificuldade?"}
{348}{}{"Charles Cuevas: Uma vez ele disse:" Me dê hóquei ou me dê a morte ". Ele não conseguiu o hóquei ".}
{349}{}{"William Lebus"}
{350}{}{"Reg Arnedo: ainda podemos ouvir sua voz nos corredores".}
{351}{}{"Shanna SanPaolo"}
{352}{}{"brahmin Wrangler"}
{353}{}{"Josh Walters, 1971-2011. Morreu de complicações durante o quinto transplante de fígado".}
{354}{}{"Doug Avery. Odiava a guerra por destruir o estilo de vida do trailer park".}
# joke ones
{355}{}{"Aqui está Ezekial Aikle, 102 anos. Os bons morrem jovens".}
{356}{}{"Aqui está Ann Mann, que viveu uma velha criada, mas morreu um velho Mann. 8 de dezembro de 1767"}
{357}{}{"Os filhos de Israel queriam pão e o Senhor lhes enviou maná, o antigo balconista Wallace queria uma esposa, e o Diabo enviou-lhe Anna".}
{358}{}{"Aqui está Johnny Yeast. Perdoe-me por não subir".}
{359}{}{"Aqui está o corpo de Jonathan Blake pisou no gás em vez do freio".}
{360}{}{"Aqui estabelece Butch, nós o plantamos em bruto. Ele foi rápido no gatilho, mas lento no sorteio".}
{361}{}{"Sagrado para a memória de meu marido, John Barnes, que morreu em 3 de janeiro de 1803. Sua viúva viúva, com 23 anos, tem muitas qualificações de uma boa esposa e anseia por ser consolada".}
{362}{}{"Sir John Strange, aqui está um advogado honesto, e isso é estranho".}
{363}{}{"Eu era alguém. Quem, não é seu negócio".}
{364}{}{"Aqui está Lester Moore, quatro limas de um .44, nada menos, não mais".}
{365}{}{"Eu disse que estava doente!"}
{366}{}{"Leitor se o dinheiro que você tiver na falta de escavar 4 metros de profundidade e você encontrará uma moeda de um centavo".}
{367}{}{"Ela sempre disse que seus pés a estavam matando, mas ninguém acreditava nela".}
{368}{}{"No dia 22 de junho - Jonathan Fiddle - Fiquei fora de sintonia".}
{369}{}{"Aqui está o corpo de nossa Anna feito até a morte por uma banana. Não era o fruto que a colocava baixa, mas a pele da coisa que a fazia ir".}
{370}{}{"Saiu de Owen Moore do que ele poderia pagar".}
{371}{}{"Na Memória de Little Chris Wood. Aqui encontra-se uma madeira fechada em madeira, uma Madeira dentro de outra. A madeira exterior é muito boa, embora não possamos elogiar a outra.}
{372}{}{"Sob o cofre e sob as árvores está o corpo de Jonathan Pease. Ele não está aqui, só existe a vagem: Pease descascou e foi a Deus".}
{373}{}{"Quem foi queimado fatalmente em 21 de março de 1870 pela explosão de uma lâmpada cheia de" R.E. Fluido queimador não explosivo da Danforth ""}
{374}{}{"Nascido em 1903 - Morreu 1942. Olhou para o elevador para ver se o carro estava no caminho para baixo. Foi".}
{375}{}{"Aqui está um ateu vestido e nenhum lugar para ir".}
{376}{}{"Eileen Suh: Foi para W & M Law School, agora é Eileen Sue"}
{377}{}{"Sarah Smart: Orator, Autor, Professor, De Amicitia".}
{378}{}{"Tim Winkle - Não cumprei nenhuma hipocrisia, mas a minha própria"}
{379}{}{"Jughead - King of Queen Archie's World"}
# new additions
{380}{}{"R.I.P Casey Donahue morreu 8/6/98 morto por Mutated Ill-Tempered Sea Bass".}
{381}{}{"Christopher 'Nightwing' Jones: administrador da hematoma de cogumelo"}
{382}{}{"Jay" Batata Feet "Nielson. Músico. Passado aos 104 anos, durante um solo de bateria".}
{383}{}{"Nitsa - A razão pela qual Charles não conseguiu o hóquei".}
{384}{}{"Thuy Dang. Que Deus tenha misericórdia de seu nome".}

# trapping the grave
{500}{}{Você habilmente colocou uma armadilha no túmulo.}
{501}{}{Você não configura adequadamente a armadilha no túmulo.}

{510}{}{ habilmente coloca uma armadilha no túmulo.}
{511}{}{ não consegue ajustar adequadamente a armadilha no túmulo.}

# Find Trap on grave
{515}{}{Você encontra uma armadilha no túmulo.}
{516}{}{Você não encontra armadilhas na sepultura.}

{520}{}{ encontra uma armadilha no túmulo.}
{521}{}{ não encontra armadilhas na sepultura.}

# Disarm the Trap on grave
{525}{}{Você habilmente desarmar a armadilha.}
{526}{}{Você não consegue desarmar a armadilha.}

{530}{}{ Destrói habilmente a armadilha.}
{531}{}{ não desarmar a armadilha.}
