# lockpick
# dude
{100}{}{Você desabilita com êxito o bloqueio.}
{101}{}{Você não pode desativar o bloqueio.}
{102}{}{Você bloqueou com sucesso o objeto.}
{103}{}{Você não conseguiu bloquear o objeto.}
# other critter
{200}{}{ Desabilitou com sucesso o bloqueio.}
{201}{}{ não é possível desativar o bloqueio.}
{202}{}{ bloqueou com sucesso o objeto.}
{203}{}{ não bloqueia o objeto.}

# explosion
{300}{}{A explosão destrói o bloqueio do objeto.}
{301}{}{A explosão não consegue remover o bloqueio do objeto.}

# pry
# dude
{400}{}{Você abriga com sucesso o bloqueio no objeto.}
{401}{}{Você não conseguiu abrir o bloqueio no objeto aberto.}
# other critter
{500}{}{ Aperte com sucesso o bloqueio no objeto.}
{501}{}{ falha ao abrir o bloqueio no objeto aberto.}
