# quick looks
# unknown
{100}{}{Você vê uma máquina estranha.}
# normal
{101}{}{Você vê uma máquina caça-níqueis.}
# high roller
{102}{}{Você vê uma slot machine brilhante.}
# jackpot
{103}{}{Você vê uma slot machine brilhante.}

# examines
# unknown
{130}{}{Tem três olhos e um braço.}
# bet amount
{140}{}{A aposta mínima é $}
{141}{}{.}
# normal
{150}{}{Você jura que você pode vê-lo olhando para você fora do canto do seu olho.}
{151}{}{Seu quadro brilhante e alça dourada brilham sedutoramente sob as luzes.}
# high roller
{165}{}{É destinado a rolos de alta velocidade.}
# jackpot
{180}{}{Sua alta quantia de recompensa parece poderosa atraente.}

# slot machine first play message
{200}{}{(A sua mão estremece quando você alcança suas moedas.A máquina continua a sussurrar em você.) * Venha, açúcar ...isso é
 isso ...venha agora ...não provoque ...*}
{201}{}{Você vê uma máquina caça-níqueis.Seu quadro brilhante e alça dourada brilham sedutoramente sob as luzes.Its coin slot
 beckons you, and you feel your face flush with anticipation.}
{202}{}{(A sua mão tremula quando você alcança suas moedas.A máquina continua a sussurrar em você.) * Venha, querida ...isso é
 ...pegue o punho ...aperte-o com firmeza ...venha agora ...*}

# insert coin messages
{250}{}{Inserir $}
{251}{}{.}
{252}{}{Jogue o último $}
{253}{}{.}
{254}{}{Ligue para um dia.}
{255}{}{You are broke.You are forced to call it a night.}
{256}{}{Ligue para uma noite.}
{257}{}{You are broke.You are forced to call it a day.}
{258}{}{Isso faz isso! Estou indo embora!}
{259}{}{Isso faz isso! Estou indo embora!}

# this is the message for when the machine is played
{500}{}{The rolls spin on the machine...}
# this goes between every symbol, example:   "cereja...laranja...Melão..."
{599}{}{...}

# pay off types
{600}{}{Nothing.}
{601}{}{One cereja.}
{602}{}{Two cerejas.}
# Três[symbol].
{603}{}{Três}
{613}{}{.}
{604}{}{JACKPOT!}
{605}{}{DOBRO JACKPOT !!!}

# payoff amount message
{700}{}{O pagamento é $}
{701}{}{.}
# symbol types
# singular
{1001}{}{cereja}
{1002}{}{laranja}
{1003}{}{ameixa}
{1004}{}{Sino}
{1005}{}{Barra}
{1006}{}{Melão}
{1007}{}{Sete}
# plural
{1101}{}{cerejas}
{1102}{}{laranjas}
{1103}{}{ameixas}
{1104}{}{Sinos}
{1105}{}{Barras}
{1106}{}{Melãos}
{1107}{}{Setes}

# float messages
{2000}{}{* Venha tocar-me por um segundo, vaqueiro. *}
{2001}{}{* Olá, marinheiro. *}
{2002}{}{*Put in a cap, pull the arm.I'll be nice to you.*}
{2003}{}{* Tick ... Marque ... Tiiiiick ... *}
{2004}{}{* Ding *}
{2005}{}{* Bing *}
{2006}{}{* Kaaa-ching *}
{2007}{}{* Zzzzzzz *}
{2008}{}{* Ring-a-ling *}
{2009}{}{* Dingity-ding *}
{2010}{}{*Hey there, beautiful.Come play me for a second.*}
{2011}{}{* Olá, linda. *}
{2012}{}{*Well ain't you a pretty lil' thing.Why don't you come play me?*}

# 3.NO MONEY (WTG, 9)
# no money to play
{2175}{}{(You stare at the slot machine realizing you don't have enough to play, and you curse your poverty.Perhaps another time…)}
{2176}{}{Sair.}
# won jackpot block
{2185}{}{(A luz "FORA DE SERVIÇO" na slot machine está piscando e desligando.)}
{2186}{}{Sair.}

# 4.RETARD (WTG)
{2100}{}{You see a strange golden metal box with three eyes and one arm.It is one of the
 prettiest things you have ever seen.}
{2101}{}{Eu}
{2102}{}{ quem é que?}
{2103}{}{Eumiss MOM.}
{2104}{}{ miss ARR-YO.Euwant go home}
{2105}{}{(Agite sua mão)}
{2106}{}{você é um mutante estranho}
{2107}{}{Elogie o Vault! Elogie o Vault!}
{2108}{}{Você é um chip de água?}
{2109}{}{Vagueie, procure outras coisas brilhantes}
{2110}{}{Sair.}

# 5.RETARD TALKS TO SLOT MACHINE (4, 5)
{2130}{}{A estranha caixa de metal dourada com três olhos e um braço não respondem.}
{2131}{}{MIM}
{2132}{}{! YU RESPONDE-ME!}
{2133}{}{(Agite sua mão)}
{2134}{}{Euchild of Vault Dweller.You talk to me NOW.}
{2135}{}{você é um mutante estranho}
{2136}{}{Você é um chip de água?}
{2137}{}{Vagueie, procure outras coisas brilhantes}
{2138}{}{(Sair.)}

# 6.RETARD PULLS HANDLE (4, 5)
{2151}{}{You grab its arm and shake it warmly.As you do, there is a *bzzzzzzz,* and the box
 speaks! "Please… insert… money."}
{2152}{}{Aighhhhh! Robô! Robô! Runnnnn}
{2153}{}{(Sair.)}

# slot machine taunts loss
# male
{2200}{}{(Você pode ouvi-la rir de você.)}
{2201}{}{* Hehehe, por que você não desiste doçura. *}
{2202}{}{* Talvez você deva deixar alguém puxar minha alça. *}
# any
{2204}{}{(Você ouve a slot machine rindo de você.)}
{2205}{}{(A máquina de engate ri de você.)}
{2206}{}{* Venha agora perdedor, não desista de mim *}
# female
{2207}{}{*I got what I wanted from you baby.Why don't you give up?*}
{2208}{}{*Lixo!*}
{2209}{}{* Não deixe a porta do cassino bater na sua bunda ao sair. *}

# slot machine taunts win
# male [3X - 1X]
{2247}{}{* Aieeeeeeee! É isso, sugah! Oh Deus, sim! Sim! Sim, novamente! Mais rápido! Mais difíceis! O que você está esperando?! Novamente!*}
{2248}{}{* É isso, sugah ... continue puxando a alça ... mais rápido, mais difícil, mais rápido ... venha agora ... *}
{2249}{}{* Vamos, açúcar ... acontece a cada um pelo menos uma vez ... tente novamente ... por favor ... *}
# any
{2250}{}{* Por favor, não desista de mim ainda bebê! Eu preciso de você mais agora do que nunca! *}
# female [1X - 3X]
{2251}{}{* Venha, querida ... tente novamente ... pegue o punho ... aperte-o firmemente ... venha agora ... *}
{2252}{}{* É isso, querido ... continue puxando a alça ... mais rápido, mais difícil, mais rápido ... venha agora ... *}
{2253}{}{* Ennnnghhhh! É isso mesmo, querido! Quem é seu pai?! Quem é seu pai?!! Faça isso novamente! Yank mais difícil desta vez! Mais difíceis!*}

# 13.DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{2280}{}{(Você vê uma máquina caça-níqueis.Its shiny frame and golden handle gleam seductively beneath New Reno's lights.Its coin slot beckons you, and you feel your face flush with anticipation.As you stare at it, one of its three windows winks at you.From the coin slot you hear a throaty voice.) *Well, my word! Helloooo there, sugah.Show a girl a good time?*}
{2281}{}{(Você vê uma máquina caça-níqueis.Its strong, rugged frame and golden handle gleam like a sun god beneath New Reno's lights.Its coin slot beckons you seductively, and you feel your thighs burn with anticipation.As you stare at it, suddenly a heavy male voice whispers from the coin slot.) *Ain't seen a pretty woman like you around before, miss.You looking to take a chance?*}
{2282}{}{:: Pinch Self ::}
{2283}{}{Uh ... olá?}
{2284}{}{:: Respire fundo, vá embora. ::}

# 14.DRUNK CONVERSATION 1 (13)
{2300}{}{* Eu ainda estou aqui, linda senhora. * (A máquina caça-nufar diminui a voz.) * Olhe, venha ... você quer fazer uma aposta? *}
{2301}{}{* Ah, ainda está aqui, sugah. * (A máquina caça-nufal diminui a voz.) * Você é um bom homem de hunka, você sabe disso? Venha agora ... você quer colocar algumas moedas em mim?}
{2302}{}{Whooo * são * yoooo?}
{2303}{}{Surrh vou apostar uma aposta em yooo}
{2304}{}{I think I better leave before I stick something in you I might regret.(Sair.)}
{2305}{}{:: Respire fundo, vá embora. :: (Sair.)}

# 15.DRUNK 2 (14)
{2320}{}{* Eu sou o seu homem ideal. * (A máquina caça-níqueis dá uma piscadela.) * Me dê algumas moedas, e eu vou agradar você de maneiras que nenhum homem NUNCA gostou. *}
{2321}{}{*I'm your ideal woman, sugar.All's ah want is a little attention.Can you help pretty old me? Come on, just a coin or two?*}
{2322}{}{Não podemos conversar}

# 16.DRUNK 3 (15)
{2340}{}{* Curso que podemos, querido, claro que podemos. * (A máquina caça-níqueis parece simpatica.) * O que está preocupando sua linda cabeça pequena? *}
{2341}{}{* Curso que podemos, sugah, claro que podemos. * (A máquina caça-níqueis parece simpatica.) * O que está perturbando você, bonito? *}
{2342}{}{Eumiss MOM and miss ARROYO and I…canna find the GECK and…*sniff*}
{2343}{}{Eumiss MOM and Arroyo wuz ATTACKED and I…dunna where they are…and…*sniff*}
{2344}{}{Euneed to fix big ship…and I dunna know HOW…and muh-muh-my Mom's GONE and…*sniff*}
{2345}{}{Eu fiz o jogo ... anna agora eu sou jusht wandrin 'round e ... ah estou preocupado com tudo em tudo e ... * sniff *}
{2346}{}{É provável que Fhallowt também não ajude meu cartão 3D Fxxxx e eu gasto tanto * monee * onnit e * sniff *}
{2347}{}{Eu tentei obter um bom charactrr, mas acho que gastei o ponto todo * errado * ... n 'agora eu tenho um personagem de trabalho ... n' ... * sniff *}
{2348}{}{ahhm havinn conversashun com um slot macheen, ah bastante ruim}

# 17.DRUNK 4 (16)
{2370}{}{*There, there...don't trouble your pretty little head about it no more…just let me take care of everything.Vamos lá,rest your head on me.There you go.Let it all out.*}
{2371}{}{*There, there...don't trouble yourself about it no more, sugah…just let me take care of everything.Vamos lá,rest your handsome head on me.There you go.Let it all out.*}
{2372}{}{Obrigado, slot macheen * sniff * você é o melhor}
{2373}{}{Yooo onlee * nice * pershun eu conheci até agora everybodee else is so meeen n 'try ta * hurt * eu' pego meu dinheiro e ... * sniff *}

# 18.DRUNK 5 (17)
{2380}{}{* Você vai ficar bem, querido? Eu não me sinto confortável deixando você sair sozinho quando você está assim. *}
{2381}{}{(Você descansa sua cabeça cansada na máquina.)}
{2382}{}{* Você vai ficar bem, sugah? Ah, não sinta-se à vontade deixando você sair sozinho quando você está assim. *}
{2383}{}{Eu serei todo o rite ... thasnk fer conversando comigo, slot macheen Eu te amo}

# 19.DRUNK 6 (18)
{2400}{}{* Você é a única heroína que recebemos neste mundo de dois buracos e ladrões! Você cuida de si agora, você ouve, querido? * (Desliga.) * É melhor ir antes de eu começar a agir de forma não familiar. *}
{2401}{}{(Uma lágrima parece se formar em uma das janelas.)}
{2402}{}{* Você é o único herói que conseguimos neste mundo de dois buracos e ladrões! Você ... você ... cuide-se agora, você ouve, sugah? * (Se afasta.) * É melhor ir antes de começar a soluçar. *}
{2403}{}{Byeeeee}

# rollin' messages
{3000}{}{Vamos lá,}
{3001}{}{! Baby precisa de um novo par de sapatos!}
{3002}{}{! Papai precisa de um novo riffle de plasma!}

# can't play
{4000}{}{Parece haver alguém bloqueando a máquina.}
