{100}{}{Este carro não parece ser funcional. Ainda assim, parece estar em melhor forma do que os outros carros
 na área. Talvez este possa ser consertado.}
{101}{}{Atualmente, este carro não parece ser funcional, ele precisa de um controlador de célula de combustível.}

{200}{}{Você reparou com êxito o carro com o controlador de célula de combustível.}
{210}{}{Você não repara o carro. Você não repara o carro com o controlador de célula de combustível.}

{300}{}{Você não repara o carro. Talvez com o controlador da célula de combustível que Smitty estava falando
 sobre isso poderia ser reparado.}

{400}{}{Seria muito barulhento para abrir o capô e trabalhar no carro.}
