{100}{}{Um cartaz querido com um esboço de carvão bruto de uma pessoa procurada. A pessoa no cartaz parece familiar.}
{101}{}{A legenda lê.}
{102}{}{Wanted Dead or Alive for Child Killing e sendo um Rat Bastard. Recompensa $ 10.000 mortos ou $ 5.000 vivos.}
{103}{}{Querido morto ou vivo para matar crianças. Recompensa $ 10.000 mortos ou $ 5.000 vivos.}
{104}{}{Querido morto ou vivo por ser um bastão de ratos. Recompensa $ 10.000 mortos ou $ 5.000 vivos.}
