#
# FALLOUT BATTLECRIES
# When the Bomb Drops, the real fun begins - So let's get to Work!!!
#
# Version 1.0  May 13, 1997  Scott Bennie
#         1.1  May 14, 1997  Chris Taylor (edits and line number change)
#         1.2  June 19, 1997 Leonard, Jason, Chris (edits)
#
# Version 2.0 July 29, 1998 Feargus Urquhart - modified for Fallout 2, most text has been rearranged, however some lines were still authored by the above people.
#
#  READ THIS!! READ THIS!! READ THIS!! READ THIS!!
#
#  This new file is different than the old one in that body locations are listed in a generic fashion first and are only listed for particular types of characters.  This is followed by a list of generic characters, which is then followed by the more specific taunts and party member taunts.
#
#
####################################################################################
#
#                    Generic Body Parts
#
####################################################################################
#
#                     Notes
#
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#
#                     1000 Wimpy Person
#                     1100 Normal Person
#                     1200 Tough Person
#                     1300 Berserk Person
#                     1400 Robot
#                     1500 Primitive
#                     1600 Ghoul
#                     1700 Raider (Khan)
#                     1800 Junkie
#
####################################################################################
#
#
############################################
# 1000 Wimpy Person
############################################
#
# target hit in head
#
{1000}{}{Meu rosto! Meu rosto!}
{1001}{}{Ow! Isso dói!}
{1002}{}{Ouch! Preciso de gelo para a minha cabeça}
#
# target hit in left arm
#
{1010}{}{Ow, meu braço}
{1011}{}{Ow!}
{1012}{}{Você quebrou meu braço!}
#
# target hit in right arm
#
{1020}{}{Ow, meu braço}
{1021}{}{Wahhhh!}
{1022}{}{Meu Deus! Meu braço!}
#
# target hit in torso
#
{1030}{}{Ow! Isso realmente machucou!}
{1031}{}{Eu acho que vou desmaiar}
{1032}{}{Ouch!}
{1033}{}{Oooof!}
{1034}{}{Isso dói!}
{1035}{}{Apenas me deixe em paz!}
{1036}{}{Ohhh, dor!}
#
# target hit in right leg
#
{1060}{}{Ow, minha perna}
{1061}{}{Meu joelho!}
{1062}{}{Ow!}
#
# target hit in left leg
#
{1070}{}{Ow, minha perna}
{1071}{}{Meu joelho!}
{1072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{1080}{}{Ow !! Meus olhos!}
{1081}{}{Meu rosto! Meus olhos! Arrrrgh!}
{1082}{}{Meus olhos!}
#
# target hit in groin
#
{1090}{}{Ooooooooo, minha virilha! Ooooooo ...}
{1091}{}{Oww ... Burns!}
{1092}{}{Urp!}
{1093}{}{Ooorp! Aoooww ...}
{1094}{}{Eu ... não posso ... respirar ...}
{1095}{}{A dor, a dor ...}
#
############################################
# 1100 Normal Person
############################################
#
# target hit in head
#
{1100}{}{Droga!}
{1101}{}{Meu crânio dolorido}
{1102}{}{Meu rosto! Meu rosto!}
#
# target hit in left arm
#
{1110}{}{Aggghhh! Meu braço}
{1111}{}{Meu braço!}
{1112}{}{Oh cara, isso dói!}
#
# target hit in right arm
#
{1120}{}{Aggghhh! Meu braço}
{1121}{}{Meu braço!}
{1122}{}{}
#
# target hit in torso
#
{1130}{}{}
{1131}{}{Oof!}
{1132}{}{Ouch!}
{1133}{}{Oof! Minhas costelas doem}
{1134}{}{Ugh! Isso dói!}
{1135}{}{Droga! I spit on you!}
{1136}{}{Argh!}
{1138}{}{Oh, minhas costelas!}
{1139}{}{Ow !!!}
{1140}{}{Oof!}
#
# target hit in right leg
#
{1160}{}{Aggghhh! Minha perna}
{1161}{}{Minha perna!}
{1162}{}{Lá vai o meu joelho}
#
# target hit in left leg
#
{1170}{}{Aggghhh! Minha perna}
{1171}{}{Minha perna!}
{1172}{}{Lá vai o meu joelho}
#
# target hit in eyes
#
{1180}{}{Aggghhh! Eu estou cego!}
{1181}{}{Meus olhos! Meus olhos!}
{1182}{}{Meu olho! Você pagará por aquele!}
#
# target hit in groin
#
{1190}{}{Oooooo, minha virilha!}
{1191}{}{Oooooooooo!}
{1192}{}{Eu ... não posso ... respirar ...}
{1193}{}{Erg! Direito nas jóias!}
{1194}{}{A dor, a dor ...}
{1195}{}{Droga, isso dói!}
#
############################################
# 1200 Tough Person
############################################
#
# target hit in head
#
{1200}{}{Ow! Você filho de um ...}
{1201}{}{Você me quebrou o nariz!}
{1202}{}{Eu vou tirar sua cabeça!}
#
# target hit in left arm
#
{1210}{}{Ow, meu braço}
{1211}{}{Você cometeu o maior erro de sua vida}
{1212}{}{Meu braço!}
#
# target hit in right arm
#
{1220}{}{Ow, meu braço}
{1221}{}{Você cometeu o maior erro de sua vida}
{1222}{}{Meu braço!}
#
# target hit in torso
#
{1230}{}{Urp!}
{1231}{}{Oof!}
{1232}{}{Ouch!}
{1233}{}{}
{1234}{}{Ugh! Isso dói!}
{1235}{}{Ouch!}
{1236}{}{Argh!}
{1237}{}{Oh, acho que você quebrou uma costela!}
{1238}{}{Ow !!! Meu baço!}
{1239}{}{Oof!}
#
# target hit in right leg
#
{1260}{}{Ow, minha perna}
{1261}{}{Eu não preciso suportar matá-lo!}
{1262}{}{Meu joelho!}
#
# target hit in left leg
#
{1270}{}{Ow, minha perna}
{1271}{}{Eu não preciso suportar matá-lo!}
{1272}{}{Meu joelho!}
#
# target hit in eyes
#
{1280}{}{Não consigo ver!}
{1281}{}{Esta luta está piorando no segundo}
{1282}{}{Esse foi um tiro barato real!}
#
# target hit in groin
#
{1290}{}{Oooooo, minha virilha!}
{1291}{}{Eu sentirei isso pela manhã}
{1292}{}{}
{1293}{}{Urp!}
{1294}{}{}
{1295}{}{}
#
############################################
# 1300 Berserk Person
############################################
#
# target hit in head
#
{1300}{}{Essa será uma cicatriz legal!}
{1301}{}{Estou começando a ficar irritado}
{1302}{}{Faça isso novamente, porco}
#
# target hit in left arm
#
{1310}{}{Você voou-me!}
{1311}{}{}
{1312}{}{Você quebrou meu braço, mas vou quebrar seu pescoço}
#
# target hit in right arm
#
{1320}{}{}
{1321}{}{É apenas um arranhão ...}
{1322}{}{Você quebrou meu braço, então eu vou quebrar seu pescoço}
#
# target hit in torso
#
{1330}{}{Um pouco de sangue não está machucado ninguém}
{1331}{}{Oof! Eu vou te raspar por isso ...}
{1332}{}{Ow!}
{1333}{}{Eu gosto da dor!}
{1334}{}{Eu amo o som de costelas de cracking!}
{1335}{}{Isso não é nada!}
{1336}{}{Arg!}
#
# target hit in right leg
#
{1360}{}{Eu amo o som de esmagamento de ossos}
{1361}{}{}
{1362}{}{Você quebrou a perna, mas vou quebrar o pescoço}
#
# target hit in left leg
#
{1370}{}{Eu amo o som de esmagamento de ossos}
{1371}{}{}
{1372}{}{Você quebrou meu braço, mas vou quebrar seu pescoço}
#
# target hit in eyes
#
{1380}{}{Ei, sou cego}
{1381}{}{Não consigo ver. Isso tornará isso justo}
{1382{}{My eyes, bitch!}
#
# target hit in groin
#
{1390}{}{Oof, minha virilha!}
{1391}{}{Esse foi um movimento de bolas}
{1392}{}{}
{1393}{}{}
{1394}{}{Então é assim que você quer jogar}
{1395}{}{Ack!}
#
############################################
# 1400 Robot
############################################
#
# target hit in CPU
#
{1400}{}{Aviso, mau funcionamento da CPU registrado!}
{1401}{}{Atenção! Dano da CPU! Processamento prejudicado!}
{1402}{}{Atenção! CPU danificado! Sistema crítico de rerouting!}
#
# target hit in left manipulator
#
{1410}{}{Dano do manipulador registrado}
{1411}{}{Unidade atingida no manipulador esquerdo. Avaliação de danos}
{1412}{}{Manipulador atingido registrado. Tentando compensar}
#
# target hit in right manipulator
#
{1420}{}{Dano do manipulador registrado}
{1421}{}{Unidade atingida no manipulador direito. Avaliação de danos}
{1422}{}{Manipulador atingido registrado. Tentando compensar}
#
# target hit in frame
#
{1430}{}{Frame hit. Corrigindo danos}
{1431}{}{Frame hit. Reformas internas iniciadas}
{1432}{}{Estrutura principal sob ataque}
{1433}{}{Armadura penetrou}
{1434}{}{Estrutura principal sob ataque. Correcting}
{1435}{}{Esta unidade está sob ataque}
{1436}{}{Tentando manobra de combate}
{1437}{}{Brzzt!}
{1438}{}{Dano menor}
{1439}{}{Brzzt!}
#
# target hit in right motivator
#
{1460}{}{Dano de motivação registrado}
{1462}{}{Unidade atingida no motivador certo. Avaliação de danos}
{1463}{}{Motivador hit registrado. Tentando compensar}
#
# target hit in left motivator
#
{1470}{}{Dano de motivação registrado}
{1471}{}{Unidade atingida no motivator esquerdo. Avaliação de danos}
{1472}{}{Motivador hit registrado. Tentando compensar}
#
# target hit in sensors
#
{1480}{}{Sensor hit! Sensor hit!}
{1481}{}{Sensores prejudicados! Sensores prejudicados!}
{1482}{}{Mau funcionamento do sistema de sensores, tentativa de bypass}
#
# target hit in regulator
#
{1490}{}{O mau funcionamento do regulador está registrado!}
{1491}{}{Dano do regulador! Regulação prejudicada!}
{1492}{}{Regulador danificado! Sistema crítico de rerouting!}
#
#
############################################
# 1500 Primitive
############################################
#
# target hit in head
#
{1500}{}{Minha cabeça está cheia de espíritos malignos.}
{1501}{}{Posso ouvir meus ancestrais me chamarem.}
{1502}{}{Isso vai muito bem.}
{1503}{}{Ouuuuch!}
{1504}{}{Minha cabeça está em chamas!}
{1505}{}{Queima, queima!}
{1506}{}{A dor.}
{1507}{}{Sua magia é poderosa.}
{1508}{}{Você não pode roubar minha alma dessa maneira.}
{1509}{}{Sua magia não pode me matar.}
#
# target hit in left arm
#
{1510}{}{Vou usar meu braço direito para matar você.}
{1511}{}{Eu só preciso de uma mão para matá-lo.}
{1512}{}{Sua dor será ainda maior!}
{1513}{}{Eu não precisava de tantos dedos de qualquer maneira.}
{1514}{}{Esse braço era um pouco longo demais.}
{1515}{}{Vou levar os dois braços para isso.}
{1516}{}{Por isso, eu mato você devagar.}
{1517}{}{Youch!}
{1518}{}{Tanto sangue.}
{1519}{}{Algo para mostrar aos jovens.}
 #
# target hit in right arm
#
{1520}{}{Vou matá-lo com a mão esquerda.}
{1521}{}{Seu objetivo é tão ruim?}
{1522}{}{Eu só preciso de uma mão para matá-lo.}
{1523}{}{Eu não precisava de tantos dedos de qualquer maneira.}
{1524}{}{Por isso, eu mato você devagar.}
{1525}{}{Vou levar os dois braços para isso.}
{1526}{}{Você pega meu braço, eu tomarei sua cabeça!}
{1527}{}{Você procura me paralisar?}
{1528}{}{Eu vou jantar em suas entranhas para isso.}
{1529}{}{Você vai demorar muito para morrer.}
#
# target hit in torso
#
{1530}{}{Awwwwwg!}
{1531}{}{Meus interiores queimam!}
{1532}{}{As minhas tripas estão em chamas!}
{1533}{}{Meus espíritos da vida fogem de mim.}
{1534}{}{Fiquei aberto!}
{1535}{}{Posso viver o tempo suficiente para terminar você.}
{1536}{}{Antepassados, estou chegando.}
{1537}{}{Nunca mais veremos a aldeia.}
{1538}{}{Pelo menos vou morrer com honra.}
{1539}{}{Meus irmãos devem vingar-me.}
{1540}{}{Não tenho mais fôlego em mim.}
{1541}{}{Você pegou minha alma.}
{1542}{}{Você me mutilaria?}
{1543}{}{Eu sou destruído como um brâmane.}
{1544}{}{Não me sinto bem.}
{1545}{}{Não consigo sentir minhas pernas.}
{1546}{}{De repente, sinto-me quente e com sono.}
{1547}{}{Errggggg!}
{1548}{}{Gack! COF cof.}
{1549}{}{Deve continuar, deve matar o inimigo ...}
{1550}{}{A escuridão me acena.}
{1551}{}{A hora da minha morte se aproxima.}
{1552}{}{O Shaman estava certo, eu não volto.}
{1553}{}{O outworlder me matou.}
{1554}{}{Eu sou morto.}
{1555}{}{Minhas entranhas são afuniladas da minha espinha!}
{1556}{}{Não me deixe envergonhar na morte.}
{1557}{}{Porra desses intestinos traquinas.}
{1558}{}{Ei, olhe aqui, eu posso ver meu almoço.}
{1559}{}{Onde tem todo o ar?}
#
# target hit in right leg
#
{1560}{}{Eu vou rastejar para matar você.}
{1561}{}{Deve continuar em pé, deve ....}
{1562}{}{Não me faça correr para te pegar!}
{1563}{}{Você me paralisaria, Coward!}
{1564}{}{Awwwwgg!}
{1565}{}{Osso? Então, branco ...}
{1566}{}{Por que não posso andar?}
{1567}{}{Arrrrrrgh.}
{1568}{}{Unnhhh.}
{1569}{}{A perna parece fogo.}
#
# target hit in left leg
#
{1570}{}{Eu vou rastejar para matar você.}
{1571}{}{Deve continuar em pé, deve ....}
{1572}{}{Não me faça correr para te pegar!}
{1573}{}{Você me paralisaria, Coward!}
{1574}{}{Awwwwgg!}
{1575}{}{Osso? Então, branco ...}
{1576}{}{Não é possível andar. Oh, a dor ...}
{1577}{}{Vou queimar seu pé por isso.}
{1578}{}{Ooooo-ouuuuch!}
{1579}{}{A perna queima como fogo.}
#
# target hit in eyes
#
{1580}{}{A escuridão está aqui.}
{1581}{}{Onde está você?}
{1582}{}{Ajuda, ajude-me.}
{1583}{}{Ainda posso ouvi-lo.}
{1584}{}{Procurando me cegar? Seu covarde!}
{1585}{}{Minha visão foi roubada.}
{1586}{}{Você pode pegar meus olhos, mas não minha coragem!}
{1587}{}{Venha aqui para que eu possa te matar!}
{1588}{}{A escuridão, a escuridão, Aaaiiiieee!}
{1589}{}{Onde está o meu olho, onde está?}
#
# target hit in groin
#
{1590}{}{Tenho muitos jovens prontos.}
{1591}{}{Você luta sem honra.}
{1592}{}{Eu sou casado, não usei de qualquer maneira.}
{1593}{}{Espíritos sagrados, o mundo acabou de explodir.}
{1594}{}{Gasp ... não consigo respirar ...}
{1595}{}{Em alto, discreto, voz - Ouch!}
{1596}{}{Unnhhh. Preciso sentar um pouco.}
{1597}{}{Você bastardo - eu mato você lentamente por isso.}
{1598}{}{Você não sabe nada de honra.}
{1599}{}{Eu o açougueiro gosta de animal por isso.}
#
#
############################################
 # 1600 Ghoul
############################################
#
# target hit in head
#
{1600}{}{Oh, meu lindo rosto}
{1601}{}{Meus cérebros doem.}
{1602}{}{Agora eu pareço Van Gogh.}
{1603}{}{Droga, vai o meu nariz.}
{1604}{}{Ei, esse é meu último dente.}
{1605}{}{Eu fui escalado!}
{1606}{}{Prefiro ter uma garrafa na frente de mim ...}
{1607}{}{Deixe-me dar uma idéia da minha mente.}
{1608}{}{Esse é um bom olho, Arrr.}
{1609}{}{Traz uma lágrima para mim um bom olho.}
#
# target hit in left arm
#
{1610}{}{Você me desarmou!}
{1611}{}{Ooohh, da dor, da dor.}
{1612}{}{Ainda tenho alguns dedos para a esquerda.}
{1613}{}{Eu só preciso de um dedo para * you * bub.}
{1614}{}{Acho que vou te dar uma mão então.}
{1615}{}{Isso é pior do que um hangnail.}
{1616}{}{Isso vai matar meu backswing.}
{1617}{}{Vou apalpá-lo com meu coto!}
{1618}{}{Ei, onde foram os meus dedos?}
{1619}{}{Isso será ótimo para esse olhar do Capt. Hook.}
#
# target hit in right arm
#
{1620}{}{Eu deveria ter usado direito-guarda.}
{1621}{}{Você quebrou meu braço!}
{1622}{}{Você vai se arrepender disso!}
{1623}{}{Eu estou sendo moyderd heya.}
{1624}{}{Lá Wimbledon.}
{1625}{}{Sieg ... oh, não importa.}
{1626}{}{Você me desarmou!}
{1627}{}{Eu só preciso de um dedo para * you * bub.}
{1628}{}{Vou matá-lo então.}
{1629}{}{Lá minha luva de lantejouha de prata!}
#
# target hit in torso
#
{1630}{}{Isso é * meu * fígado, devolva-o!}
{1631}{}{Apenas um pouco mais para a direita, ahhh, isso é melhor.}
{1632}{}{Gerrk!}
{1633}{}{Qual é o cheiro de mofo? Oh, são minhas entranhas.}
{1634}{}{Agora que você me escondeu, eu sou tão esbelta! Obrigado!}
{1635}{}{./~ Eu deixei meu coração ... / ~}
{1636}{}{Isso fez cócegas nas minhas costelas.}
{1633}{}{Quem precisa de um apêndice de qualquer maneira.}
{1634}{}{Apenas um pouco fora das bordas, doc.}
{1635}{}{Arrggghh, minha espinha!}
{1636}{}{My legs, Não consigo sentir minhas pernas.}
{1637}{}{É um Sargento de ferida intestinal.}
{1638}{}{Os pulmões são para mariquinhas.}
{1639}{}{Ei, eu tenho costelas!}
#
# target hit in right leg
#
{1660}{}{Ow, minha perna}
{1661}{}{Você vai pagar por isso!}
{1662}{}{Argh! Você quebra minha perna, eu quebro seu pescoço!}
{1663}{}{Droga, vai meu Tango.}
{1664}{}{Maldita seja, meus dedos do pé estão lá.}
{1665}{}{Acho que preciso de uma vantagem.}
{1666}{}{Você arrumou meus sapatos de camurça azul!}
{1667}{}{Você bateu as pontas das asas!}
{1668}{}{E eu apenas raspei-os também.}
{1669}{}{Vou morder suas rótulas!}
#
# target hit in left leg
#
{1670}{}{Minha perna!}
{1671}{}{Você engoliu o meu Gucci!}
{1672}{}{Ouch! Ei! Isso está abaixo do cinto!}
{1673}{}{Você pode gerar problemas como ninguém.}
{1674}{}{Spank me mamãe, eu fui travesso.}
{1675}{}{Isso vai crescer bem.}
{1676}{}{Todo esse sangue é meu?}
{1677}{}{Marshall Dillon, Marshall Dillon!}
{1678}{}{Isso vai dar uma bolha.}
{1679}{}{Kai, yai, yippee, ai, ay!}
#
# target hit in eyes
#
{1680}{}{Maldito sangue nos meus olhos!}
{1681}{}{Meu olho! Você pagará por aquele!}
{1682}{}{Desgraçado!}
{1683}{}{Quem desligou as luzes?}
{1684}{}{Hah, esse foi o meu olho de vidro!}
{1685}{}{Esmaga como uma uva madura, não é?}
{1686}{}{Eu tenho o meu olho em você, uh, você poderia devolvê-lo por favor?}
{1687}{}{Eu ainda posso rastreá-lo pelo som sozinho!}
{1688}{}{Aiyeee! Aiyeee! meu olho!}
{1689}{}{Você está me cegando porque tem medo, não é você.}
#
# target hit in groin
#
{1690}{}{Você não é cavalheiresco?}
{1691}{}{Yooooouuuuch!}
{1692}{}{Unnhhhhh!}
{1693}{}{Talvez se eu simplesmente não me mudar um pouco ...}
{1694}{}{Essa é a minha Bolonha de carne de bovino!}
{1695}{}{Lá vai a minha vida social.}
{1693}{}{Acho que preciso sentar um pouco.}
{1694}{}{Gee, se houvesse algum ghouls feminino, estaria com raiva de você.}
{1695}{}{Oohh, isso doeu.}
{1696}{}{Isso ...? Oh, sim, isso dói.}
{1697}{}{Ei, olhe! Ostras de pradaria.}
{1698}{}{Nozes picado, alguém?}
{1699}{}{Não mais escrevendo meu nome na neve.}
#
############################################
# 1700 Raider (Khan)
############################################
#
# target hit in head
#
{1700}{}{Não é o fricken cabeça você ...}
{1701}{}{Minha ... cabeça ... ficando tonta}
{1702}{}{Ugnnn!}
{1703}{}{Não é o rosto! Não é o rosto!}
#
# target hit in left arm
#
{1710}{}{Eu posso vencê-lo com um braço!}
{1711}{}{Médico! Meu braço está fodido!}
{1712}{}{Ack! Bom, eu sou ambi ... o que quer que seja.}
#
# target hit in right arm
#
{1720}{}{Você quebrou meu braço! Now the fight is fair!}
{1721}{}{Médico! Meu braço está fodido!}
{1722}{}{Você precisará remover mais do que o meu braço para salvar sua bunda!}
#
# target hit in torso
#
{1730}{}{Ahhg! Gut shot!}
{1731}{}{Hnrgggg! Não posso ... respirar ...}
{1732}{}{Minhas costelas doem. Em breve vou remover o seu! Isso é justo!}
{1733}{}{Você ... vai ... pagar ... por ... isso!}
{1734}{}{* Ooooof * Deus, eu odeio isso ...}
{1735}{}{Nggg! Plexo solar!}
#
# target hit in right leg
#
{1760}{}{Dammit! Minha perna!}
{1761}{}{Não preciso de duas pernas para chutar sua bunda.}
{1762}{}{Preciso de um estímulo para a minha perna ...}
{1763}{}{Urggg ... leg's ... ferrado ...}
#
# target hit in left leg
#
{1770}{}{Dammit! Minha perna!}
{1771}{}{* Ergg * Vai ter uma coxa após essa ...}
{1772}{}{Preciso de um estímulo para a minha perna ...}
{1773}{}{Urggg ... leg's ... ferrado ...}
#
# target hit in eyes
#
{1780}{}{Merda! Não são os olhos!}
{1781}{}{Tentando paralisar minha percepção de profundidade, hein?}
{1782}{}{Não consigo ... ver ... sangue ... em ... olhos ...}
{1783}{}{Não tenho que te ver, ainda posso sentir o seu cheiro!}
#
# target hit in groin
#
{1790}{}{O que você acha disso? Algum filme de ação barato?}
{1791}{}{Minhas bolas!!! Venha aqui e deixe-me fazer isso com você!}
{1792}{}{Bem, vão minhas bolas de bronze.}
{1793}{}{Desculpe-me por um momento enquanto viro por mim mesmo.}
{1794}{}{Ótimo. Eu lutei com alguém com uma fixação de bola.}
{1795}{}{Deixe-me deitar-se por um segundo, então eu vou matar você.}
{1796}{}{Nuts! Bem, não há filhos para mim.}
#
############################################
# 1800 Junkie
############################################
#
# target hit in head
#
{1800}{}{Uau. Algo apenas me atingiu no rosto.}
{1801}{}{O que acabou de me bater na cabeça?}
{1802}{}{Ngggg}
{1803}{}{Fico feliz por ter sido derramado no Jet, ou isso teria prejudicado.}
{1804}{}{Owwwww! Alguém me pegue um stimpack! Ou algum Jet!}
#
# target hit in left arm
#
{1810}{}{Ei! Alguém apenas bateu no meu braço!}
{1811}{}{Olha, meu braço é apenas para agulhas. Pare de atacá-lo.}
{1812}{}{Nggggg}
{1813}{}{Owwwww! Alguém me pegue um stimpack! Ou algum Jet!}
#
# target hit in right arm
#
{1820}{}{Ei! Alguém apenas bateu no meu braço!}
{1821}{}{Olha, meu braço é apenas para agulhas. Pare de atacá-lo.}
{1822}{}{Nggggg}
{1823}{}{Owwwww! Alguém me pegue um stimpack! Ou algum Jet!}
#
# target hit in torso
#
{1830}{}{Meu baço!}
{1831}{}{Ow! Owwww, meu baú estúpido! Ow!}
{1832}{}{Ei! O que você me bateu no baú, idiota ?!}
{1833}{}{Pare de me bater no peito!}
{1834}{}{Uau. Meu peito. Você acertou. Legal.}
{1835}{}{Nrgggg}
{1836}{}{* hfff *}
{1837}{}{Owwwww! Alguém me pegue um stimpack! Ou algum Jet!}
#
# target hit in right leg
#
{1860}{}{Ei! Alguém apenas atingiu minha perna!}
{1861}{}{Ei! Eu ando com essa perna!}
{1862}{}{Owwwww! Alguém me pegue um stimpack! Ou algum Jet!}
#
# target hit in left leg
#
{1870}{}{Ei! Alguém apenas atingiu minha perna!}
{1871}{}{Ei! Eu ando com essa perna!}
{1872}{}{Owwwww! Alguém me pegue um stimpack! Ou algum Jet!}
#
# target hit in eyes
#
{1880}{}{Isso não se sentiu como uma agulha nos meus olhos ...}
{1881}{}{Ei! Eu vejo com esse olho!}
{1882}{}{Meus olhos! Meus olhos! My eyes hurt!}
#
# target hit in groin
#
{1890}{}{Estou tão despejado no Jet, que mal sentia isso. Oh ... não, espere.}
{1891}{}{* Hurhkkkk *}
{1892}{}{Me chute na virilha, você vai ?!}
{1893}{}{Nghhhhh!}
{1894}{}{Não é a virilha! Não é a virilha!}
{1895}{}{Meus órgãos genitais! Meus genitais pobres!}
{1896}{}{Perdoe-me enquanto eu viro por todo o lugar.}
{1897}{}{Isso ... doeu ... um ... LOTE.}
{1898}{}{Espero que a minha virilha tenha ido ao céu genital.}
#
####################################################################################
#
#                    Generic People
#
####################################################################################
#
#                     Notes
#
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed.
#
#                     2000 Wimpy Person
#                     2100 Normal Person
#                     2200 Tough Person
#                     2300 Berserk Person
#                     2400 Guard (Normal)
#                     2500 Guard (Tough)
#                     2600 Primitive
#                     2700 Soldier
#                     2800 Leader
#                     2900 Raider (Khan)
#                     3000 Robot
#                     3100 Ghoul
#                     3200 Junkie
#
####################################################################################
#
#
############################################
# 2000 Wimpy Person
############################################
#
#  running away
#
{2000}{}{Misericórdia!}
{2001}{}{Alguém me ajude!}
{2002}{}{Por favor pare!}
{2003}{}{Socorro!}
{2004}{}{Aaaaahhhh!}
{2005}{}{Misericórdia!}
#
# moving in to attack
#
{2020}{}{Hmm, uh, pare!}
{2021}{}{Eu não gosto do seu tipo ...}
{2022}{}{Eu realmente esperava que não viesse a isso ...}
{2023}{}{Eu acho que tenho que me defender}
{2024}{}{Eu acho que tenho que me defender}
{2025}{}{Eu realmente esperava que não viesse a isso ...}
#
# attacking
#
{2040}{}{Pegue isso!}
{2041}{}{Você não deveria ter começado isso!}
{2042}{}{Você pediu isso!}
{2043}{}{Como você gosta disso?}
{2044}{}{}
{2045}{}{Você é besta!}
{2046}{}{Eu não quero fazer isso!}
{2047}{}{}
{2048}{}{Eu não queria essa luta, mas ...}
{2049}{}{Você cad!}
#
# target being missed
#
{2060}{}{}
{2061}{}{Voce estava com saudades de mim!}
{2062}{}{Uau, isso poderia ter doído!}
{2063}{}{Whew! Eu ainda estou vivo!}
{2064}{}{Ei! Isso poderia ter doído!}
{2065}{}{Whew! Eu ainda estou vivo!}
#
############################################
# 2100 Normal Person
############################################
#
#  running away
#
{2100}{}{Ataque alguém, por favor!}
{2101}{}{Tenha piedade!}
{2102}{}{Alguém me ajude!}
{2103}{}{Por favor pare!}
{2104}{}{}
{2105}{}{Eu não estou ansioso por isso!}
#
# moving in to attack
#
{2120}{}{Espere até eu te pegar ...}
{2121}{}{}
{2122}{}{Ei você!}
{2123}{}{Você não é bem-vindo aqui}
{2124}{}{Ninguém está tomando este lugar ...}
{2125}{}{Quem você pensa que é?}
#
# attacking
#
{2140}{}{Você não deveria ter feito isso}
{2141}{}{Nós cuidamos dos nossos}
{2142}{}{Isto é o que fazemos para vermes!}
{2143}{}{Você é mutante, louco!}
{2144}{}{Seu desgraçado!}
{2145}{}{Vou alimentá-lo aos cachorros}
{2146}{}{Isso vai te aprender!}
{2147}{}{Bem. Você pediu isso.}
{2148}{}{Seu animal!}
{2149}{}{Você merece o que está acontecendo com você!}
#
# target being missed
#
{2160}{}{Eu não sou tão ruim, eu estou?}
{2161}{}{Eu vi brahmin mais esperto do que você}
{2162}{}{Whew!}
{2163}{}{Eu não sou nenhum empurrão}
{2164}{}{Agradeça aos deuses}
{2165}{}{Você perdeu!}
#
############################################
# 2200 Tough Person
############################################
#
#  running away
#
{2200}{}{Isso não vale a pena!}
{2201}{}{Eu tenho coisas melhores para fazer}
{2202}{}{Alguém me ajude!}
{2203}{}{Você conseguiu o melhor de mim ... desta vez}
{2204}{}{Você receberá o que está acontecendo com você!}
{2205}{}{Eu não estou ansioso por isso!}
#
# moving in to attack
#
{2220}{}{É tarde demais para correr}
{2221}{}{Quem te deixou aqui?}
{2222}{}{Ei você!}
{2223}{}{Nós não gostamos do seu tipo por aqui!}
{2224}{}{Ninguém está tomando este lugar ...}
{2225}{}{Quem você pensa que é?}
#
# attacking
#
{2240}{}{Pegue isso!}
{2241}{}{Como você gosta disso?}
{2242}{}{Isto é o que fazemos para vermes!}
{2243}{}{Isto é para você!}
{2244}{}{Adeus!}
{2245}{}{Vamos obtê-lo em!}
{2246}{}{Troublemaking scum!}
{2247}{}{Eu vou vencê-lo como um enteado de cabeça vermelha}
{2248}{}{Seu animal!}
{2249}{}{Você vai se arrepender de colocar o pé aqui!}
#
# target being missed
#
{2260}{}{Você não é tão bom quanto você pensa}
{2261}{}{Patético}
{2262}{}{Você é apenas um bandido comum}
{2263}{}{Você não tem nada de especial}
{2264}{}{Eu não serei sua vítima}
{2265}{}{Esse foi o seu último erro}
#
############################################
# 2300 Berserk Person
############################################
#
#  running away
#
{2300}{}{Eu estou tomando o lam}
{2301}{}{Eu voltarei!}
{2302}{}{Mais tarde, punk!}
{2303}{}{Isso foi divertido, mas eu já fui!}
{2304}{}{Você pagará por isso - mais tarde!}
{2305}{}{Vamos fazer isso novamente em breve!}
#
# moving in to attack
#
{2320}{}{Eu vou arrumar seus ouvidos de volta!}
{2321}{}{Carne fresca!}
{2322}{}{Você fez meu dia!}
{2323}{}{Você vai ser minha cadela!}
{2324}{}{Eu vou arrumar seus ouvidos de volta!}
{2325}{}{Eu vou resolver o seu hash!}
#
# attacking
#
{2340}{}{Vou pegar o cha!}
{2341}{}{Hora de brincar!}
{2342}{}{Por favor, não implore. A morte deve ser digna.}
{2343}{}{Espero que você não morra muito rápido}
{2344}{}{Tem alguma última palavra?}
{2345}{}{Pegue isso!}
{2346}{}{Morrer! Morrer! Morrer! Morrer! Morrer!}
{2347}{}{Morrer!}
{2348}{}{Vamos abri-lo um pouco ...}
{2349}{}{Você é amante do cão, amigo.}
#
# target being missed
#
{2360}{}{Você nem me voou}
{2361}{}{Você me aborreceu até as lágrimas}
{2362}{}{Vamos, punk. Me dê uma briga!}
{2363}{}{É o melhor que você pode fazer?}
{2364}{}{Você é um merda!}
{2365}{}{Isso vai ser mais fácil do que eu pensava}
#
############################################
# 2400 Guard (Normal)
############################################
#
#  running away
#
{2400}{}{Estou fora daqui!}
{2401}{}{Talvez não tenha sido uma boa idéia}
{2402}{}{Ataque alguém, ok!}
{2403}{}{Yikes!}
{2404}{}{Eu não estou ansioso por isso!}
{2405}{}{Isso é demais para mim}
#
# moving in to attack
#
{2420}{}{Ei você!}
{2421}{}{Eu vou te ensinar algumas maneiras}
{2422}{}{Nós não gostamos do seu tipo por aqui!}
{2423}{}{Você precisa aprender algum respeito!}
{2424}{}{Tempo para ganhar o meu salário ...}
{2425}{}{Espere até eu te pegar ...}
{2426}{}{Por que você vai e deve fazer isso?}
{2427}{}{Há sempre idiotas como você ao redor para mexer um turno}
#
# attacking
#
{2440}{}{Pegue isso!}
{2441}{}{Parece bem, hein?}
{2442}{}{Deveria deixá-lo sozinho}
{2443}{}{Como você gosta disso?}
{2444}{}{Onde está sua mãe agora?}
{2445}{}{Tome tudo!}
{2446}{}{Vamos ver o quão difícil você é ...}
{2447}{}{Punk}
{2448}{}{Skag!}
{2449}{}{Eu estou te deixando longe}
#
# target being missed
#
{2460}{}{Sua mãe te ensina esse movimento?}
{2461}{}{Você apenas suga!}
{2462}{}{Você não é bom o suficiente}
{2463}{}{Esse foi o seu último erro}
{2464}{}{Amador}
{2465}{}{Você aprende a lutar em bares?}
#
############################################
# 2500 Guard (Tough)
############################################
#
#  running away
#
{2500}{}{Tenho que sair daqui!}
{2501}{}{Eu voltarei...}
{2502}{}{Você não está me matando hoje!}
{2503}{}{Mais tarde, punk!}
{2504}{}{Você não é visto o último de mim!}
{2505}{}{Você pagará por isso - mais tarde!}
#
# moving in to attack
#
{2520}{}{Você é história!}
{2521}{}{Carne fresca...}
{2522}{}{Vou dançar no seu túmulo}
{2523}{}{Todo mundo! É a prática alvo!}
{2524}{}{Você está pronto, puta!}
{2525}{}{Eu vou gostar disso ...}
#
# attacking
#
{2540}{}{Tome tudo!!!}
{2541}{}{Não se preocupe gritando por misericórdia ...}
{2542}{}{Esta é a melhor parte...}
{2543}{}{Você quer mais disso !!! Hã?!}
{2544}{}{Vou alimentá-lo aos cachorros}
{2545}{}{Não deve começar o que você não pode terminar}
{2546}{}{Espero que você não morra muito rápido}
{2547}{}{Apenas um de nós está se afastando}
{2548}{}{Morrer!}
{2549}{}{Eu como punks como você para o café da manhã}
{2550}{}{Eu vou te alimentar para minha iguana de estimação}
{2551}{}{A última coisa que você verá é o meu rosto louco}
{2552}{}{Este é o meu trabalho favorito}
#
# target being missed
#
{2560}{}{Você é uma piada}
{2561}{}{É o melhor que você pode fazer?}
{2562}{}{Você está fazendo isso fácil}
{2563}{}{Apenas patético ...}
{2564}{}{Muito devagar!}
{2565}{}{Fracassado}
#
############################################
# 2600 Primitive
############################################
#
#  running away
#
{2600}{}{ Corra do Evil One!}
{2601}{}{Os espíritos me pedem para me salvar}
{2602}{}{Nosso inimigo usou magias poderosas - Execute! Alguém pegue o Shaman!}
{2603}{}{O espírito escuro é forte neste. A morte anda pela terra!}
{2604}{}{O escuro está aqui!}
{2605}{}{O escuro procura castigar-nos. Corre! Minha alma foge e eu devo seguir!}
{2606}{}{ Aiiieeeee !!}
#
# moving in to attack
#
{2620}{}{Ancestrais guiam meu braço de arma!}
{2621}{}{Sua força será minha.}
{2622}{}{Grande será a minha glória.}
{2623}{}{Devo desonrar a sua tribo.}
{2624}{}{Ayah! Nabataluk!}
{2625}{}{Os espíritos estão comigo!}
{2626}{}{Venha, deixe nossas lâminas dançar.}
{2627}{}{Deixe começar!}
{2628}{}{U-Suthoooo!}
{2629}{}{Os espíritos estão comigo!}
#
# attacking
#
{2640}{}{Seus antepassados   o abandonaram.}
{2641}{}{Sua derrota me trará uma grande honra. Minha magia não conhece a derrota!}
{2642}{}{Desista agora e não comemos seu coração.}
{2643}{}{Você luta bravamente - Vou comer sua coragem. Os Shamans vão cantar da minha vitória.}
{2644}{}{Vou me banhar no seu sangue!}
{2645}{}{Eu não tenho medo de você!}
{2646}{}{Eu te traga paz, perdi uma.}
{2647}{}{Glória na batalha compra vida eterna! Eu o honro, estranho.}
{2648}{}{As névoas convidam você.}
{2649}{}{Os nossos ancestrais têm sede de sua alma.}
{2650}{}{Minha lâmina cresce com sede}
{2651}{}{Deixe-nos beber do copo da batalha!}
#
# target being missed
#
{2660}{}{ Seus olhos estão nublados de ódio.}
{2661}{}{ Seus espíritos o abandonaram.}
{2662}{}{ Nossa magia está funcionando!}
{2663}{}{ Minha magia me faz invencível!}
{2664}{}{ Sua força de vida está enfraquecendo!}
{2665}{}{ O medo é o assassino da mente}
{2666}{}{ Minha música de batalha está funcionando!}
{2667}{}{ Nossos filhos sabem mais da batalha!}
{2668}{}{ Você conheceu a paz por muito tempo.}
{2669}{}{ Toda a sua tribo é tão fraca?}
#
############################################
# 2700 Soldier
############################################
#
#  running away
#
{2700}{}{Reforços!}
{2701}{}{Eles podem me fazer uma corte marcial ...}
{2702}{}{Médico!}
{2703}{}{Retiro! Retiro!}
{2704}{}{Cair pra trás! Cair pra trás!}
{2705}{}{Você pode ter vencido a batalha ...}
#
# moving in to attack
#
{2720}{}{Vamos obtê-lo em!}
{2721}{}{Hoo-Yah!}
{2722}{}{Eu vou te ensinar algumas maneiras}
{2723}{}{Você é história!}
{2724}{}{Ataque!}
{2725}{}{Vamos enterrar esse perdedor!}
{2726}{}{Travar e carregar!}
{2727}{}{Vamos deixar Deus resolver o que resta de você}
#
# attacking
#
{2740}{}{Pegue isso!}
{2741}{}{Agora eu tenho você!}
{2742}{}{Agora você morre!}
{2743}{}{Como você gosta disso?}
{2744}{}{Este não é apenas um trabalho para nós}
{2745}{}{Não deve começar o que você não pode terminar}
{2746}{}{É melhor rezar pelos deuses!}
{2747}{}{Você nem vai chegar às 6 da manhã}
{2748}{}{Se sentir bem?}
{2749}{}{Vejo você no inferno}
#
# target being missed
#
{2760}{}{Tente treinar alguns}
{2761}{}{É o melhor que você pode fazer?}
{2762}{}{Vamos perder. Dê uma briga!}
{2763}{}{Tente apontar na próxima vez}
{2764}{}{Civil...}
{2765}{}{Deixe para os profissionais da próxima vez}
#
############################################
# 2800 Leader
############################################
#
#  running away
#
{2800}{}{}
{2801}{}{}
{2802}{}{}
{2803}{}{}
{2804}{}{}
{2805}{}{}
#
# moving in to attack
#
{2820}{}{}
{2821}{}{}
{2822}{}{}
{2823}{}{}
{2824}{}{}
{2825}{}{}
{2826}{}{}
{2828}{}{}
#
# attacking
#
{2840}{}{}
{2841}{}{}
{2842}{}{}
{2843}{}{}
{2844}{}{}
{2845}{}{}
{2846}{}{}
{2847}{}{}
{2848}{}{}
{2849}{}{}
#
# target being missed
#
{2860}{}{}
{2861}{}{}
{2862}{}{}
{2863}{}{}
{2864}{}{}
{2865}{}{}
#
############################################
# 2900 Raider
############################################
#
#  running away
#
{2900}{}{Fugir! Fugir!}
{2901}{}{Retiro!}
{2902}{}{Reagrupar!}
{2903}{}{Cair pra trás!}
{2904}{}{Retirar o!}
{2905}{}{Aaaaghhh!}
#
# moving in to attack
#
{2920}{}{Mate esse idiota!}
{2921}{}{Carne fresca...}
{2922}{}{Pilhagem!}
{2923}{}{Este é meu!}
{2924}{}{Ahhhhhhh!}
{2925}{}{Ataque!}
#
# attacking
#
{2940}{}{Aproveite os últimos segundos da sua vida}
{2941}{}{Sangue! Sangue! Sangue!}
{2942}{}{Seu coração é meu!}
{2943}{}{RAAAAAAARRRR !!}
{2944}{}{Suas armas serão meus troféus!}
{2945}{}{Morte!}
{2946}{}{Você é meu para matar!}
{2947}{}{Seus ossos devem lixiviar nos resíduos!}
{2948}{}{Sangue e escuridão!}
{2949}{}{YAAAAAAAAAAAAH!}
{2950}{}{Explora o bastardo scraggin!}
#
# target being missed
#
{2960}{}{Esforço desperdiçado!}
{2961}{}{Você falhou!}
{2962}{}{Meu sangue é mais forte que o seu!}
{2963}{}{Eu vivo!!}
{2964}{}{Seu corpo é fraco e lamentável!}
#
############################################
# 3000 Robot
############################################
#
#  running away
#
{3000}{}{Opção de retirada iniciada}
{3001}{}{Plano tático: retiro}
{3002}{}{Combate o mínimo efetivo. Retiro recomendado}
{3003}{}{Análise tática completa. Retiro recomendado.}
{3004}{}{Download do programa de escape}
{3005}{}{Secção de retirada iniciada}
#
# moving in to attack
#
{3020}{}{Alvo adquirido!}
{3021}{}{Terminar! Terminar!}
{3022}{}{O humanóide não deve escapar}
{3023}{}{Terminar o intruso}
{3024}{}{Seqüência de combate iniciada}
{3025}{}{Carregando programa de combate}
#
# attacking
#
{3040}{}{Seqüência de combate iniciada}
{3041}{}{Alvo atacante}
{3042}{}{Iniciando a sequência de ataque}
{3043}{}{O intruso deve ser destruído!}
{3044}{}{Seleção de opções táticas concluída}
{3045}{}{Iniciando ataque}
{3046}{}{O alvo será destruído}
{3047}{}{Começou a sequência de terminação do inimigo}
{3048}{}{O alvo deve ser eliminado}
{3049}{}{Seleção ofensiva concluída}
#
# target being missed
#
{3060}{}{Análise. Sucesso do programa defensivo}
{3061}{}{Análise. Delito ofensivo insignificante.}
{3062}{}{O ataque do alvo falhou. Cálculo da resposta}
{3063}{}{A unidade foi ileso por ataque}
{3064}{}{Recalcular habilidades ofensivas do alvo}
{3065}{}{Análise. O alvo errou na seleção tática. Unidade intacta}
#
############################################
# 3100 Ghoul
############################################
#
#  running away
#
{3100}{}{Tenho que ir para lá!}
{3101}{}{Eu voltarei...}
{3102}{}{Você não está me matando hoje!}
{3103}{}{Mais tarde, normie!}
{3104}{}{Você não foi ouvido o último de mim!}
{3105}{}{Você pagará por isso - mais tarde!}
{3106}{}{Eu não estou duas vezes.}
{3107}{}{Os pés não me faltam agora!}
{3108}{}{Estou apenas executando um avanço retrógrado.}
{3109}{}{Uh, hora de uma retirada tática aqui.}
{3110}{}{Sair, etapa esquerda.}
{3111}{}{É mais tarde do que eu pensava.}
{3112}{}{Tenho que correr. Até mais.}
{3113}{}{Corra bem!}
{3114}{}{Tenho que voltar a colocar algumas peças.}
{3115}{}{Esses ossos velhos não podem mais aguentar isso.}
{3116}{}{Não são os anos, é a quilometragem.}
{3117}{}{Que mundo, que mundo ...}
{3118}{}{Acho que você aprendeu sua lição, eu estou aqui!}
{3119}{}{Ei, pare de me afastar de mim.}
#
# moving in to attack
#
{3120}{}{Você é história!}
{3121}{}{Carne fresca...}
{3122}{}{Carne de bovino, carne de bovino, carne bovina - Bolonha!}
{3123}{}{Cérebro ...}
{3124}{}{Eu vou cavar seu túmulo ...}
{3125}{}{Espero poder manter sua cabeça intacta ...}
{3126}{}{More Cérebro ....}
{3127}{}{Envie mais policiais!}
{3128}{}{Envie mais paramédicos!}
{3129}{}{Eu poderia usar algumas peças novas.}
{3130}{}{Tartar de bife chegando.}
{3131}{}{Venha e consiga!}
{3132}{}{Ainda é sopa?}
{3133}{}{Onde está o bife?}
{3134}{}{Mmm, eu adoro os lisos.}
{3135}{}{Você atravessou minha sombra ... ou sumthin '}
{3136}{}{Eu sabia que ouvi o chow-bell.}
{3137}{}{Adivinha quem vem jantar.}
{3138}{}{Peças são partes.}
{3139}{}{Então, você é meu próximo doador de órgãos, hein?}
#
# attacking
#
{3140}{}{Seu número está pronto!}
{3141}{}{Não se preocupe gritando por misericórdia ...}
{3142}{}{Eu vou gostar disso}
{3143}{}{Oooo, isso deve doer!}
{3144}{}{Slicin '& Dicin' tempo.}
{3145}{}{Eu vou comer seu fígado!}
{3146}{}{Espero que você não morra muito rápido}
{3147}{}{Hora do jantar!}
{3148}{}{Morrer!}
{3149}{}{Eu como punks como você para o café da manhã, and lunch}
{3150}{}{Como tudo pode ser mau?}
{3151}{}{Lemme 'apenas tenha um gosto!}
{3152}{}{Dê um pouco de açúcar ao papai, baby!}
{3153}{}{Eu consegui para você!}
{3154}{}{Ficar parado! Vai magoar menos.}
{3155}{}{Pare o seu agasalho, o chef está na cozinha!}
{3156}{}{Eu adoro vê-los torcer.}
{3157}{}{Delicioso e nutritivo também!}
{3158}{}{Você seguramente sangrará muito. Deve ser macio e suculento.}
{3159}{}{Acho que é mais medo do que emoção.}
#
# target being missed
#
{3160}{}{Você não pode me machucar!}
{3161}{}{E você acha que * Ghouls * são lentos?}
{3162}{}{Você perdeu, normie!}
{3163}{}{Você perdeu, normie!}
{3164}{}{Você não pode matar o que não pode bater!}
{3165}{}{Muito devagar!}
{3166}{}{Ok, vamos tentar isso com a velocidade máxima agora.}
{3167}{}{Você estava realmente apontando para mim?}
{3168}{}{O que é que foi isso?}
{3169}{}{Esta não é uma charada.}
{3170}{}{O combate requer concentração total.}
{3171}{}{É uma pena que a sua primeira vez seja o seu último também.}
{3172}{}{Você está olhando para mim?}
{3173}{}{Você quer tentar isso de novo quando sabe o que está fazendo?}
{3174}{}{Não, não, não, o * pointy-end * vai para * me. * Obteve?}
{3175}{}{O que você estava fazendo, ou você estava aiminar?}
{3176}{}{Qual é o seu principal mau funcionamento nozes?}
{3177}{}{Você nunca fez isso antes de ter você?}
{3178}{}{A minha vez é a próxima!}
{3179}{}{Foi realmente o seu * melhor * tiro? Cara, você está com problemas.}
#
############################################
# 3200 Junkie
############################################
#
#  running away
#
{3200}{}{Uau. Estou bem fora daqui.}
{3201}{}{Eu voltarei...after I get another hit.}
{3202}{}{Sabia que eu deveria ter tomado mais Buffout ...}
{3203}{}{Não posso disparar quando estou morto ...}
{3204}{}{Aieeeeeee! Não me machuque! Não me machuque!}
{3205}{}{Esta alucinação tornou-se muito real para mim ...}
#
# moving in to attack
#
{3220}{}{Coma isso!}
{3221}{}{É melhor esperar que você tenha alguns estimulantes ... ou algum Jet.}
{3222}{}{Talvez eu possa vender seu corpo para algum Jet ...}
{3223}{}{Vou ... bater ... você ... quando ... eu ... pego ... você.}
{3224}{}{Talvez matar você será a solução que eu preciso ...}
{3225}{}{Eu vou matar você! Eu vou matar você! Eu vou matar você!}
{3226}{}{Matando você vai superar meu alto bem ...}
#
# attacking
#
{3240}{}{Coma isso!}
{3241}{}{Eu vou matar você! Eu vou matar você! Eu vou matar você!}
{3242}{}{Você quer um pouco disso ?!}
{3243}{}{Nrrrg}
{3244}{}{Hiyaaaaaa}
{3245}{}{Eu vou matar você devagar ...}
{3246}{}{Você está indo para baixo como uma meretriz de 2 capitães ...}
#
# target being missed
#
{3260}{}{Feche, mas não Jet.}
{3261}{}{Estou tão alto, você nunca me tocará!}
{3262}{}{Qual de mim você está apontando?}
{3263}{}{Uau. Quase me pegou.}
{3264}{}{Eu sabia que Jet iria me tornar mais rápido ...}
{3265}{}{Você luta muito mal por uma alucinação induzida por quimioterapia.}
#
####################################################################################
#
#                   Area People
#
####################################################################################
#
#
#                     4000  Arroyo
#                     6000  The Den
#                     8000  Modoc
#                     10000  Klamath
#                     12000  Vault City / Raiders
#                     14000  Gecko
#                     16000 Broken Hills
#                     18000 New Reno
#                     20000 Sierra Army Depot
#                     22000 Redding
#                     24000 NCR
#                     26000 V13 / V15
#                     28000 Military Base
#                     30000 Navarro
#                     32000 San Fransisco
#                     34000 The Enclave
#                     36000 Special (Encounters and Created)
#
#                     Note : Some of these people will just have run away, moving to attack, attacking, and getting
#                                missed.  Others will also have cataloged hit locations.
#
####################################################################################
#
####################################################################################
#
# 4000 Arroyo
#
#                   4000 The Elder
#                   4100 Hakunin
#                   4200 Standing Fist
#
####################################################################################
#
#
####################################################################################
#
# 12000 Vault City / Raiders
#
#                   12000 Raider Mercs
#                   12100 Raider Captain
#                   12200 Gangster
#                   12300 Raider (Hit Locations)
#
####################################################################################
#
############################################
# 12000 Raider Mercs
############################################
#
#  running away
#
{12000}{}{De jeito nenhum, fico neste clusterfuck ...}
{12001}{}{Retiro!}
{12002}{}{Tempo para sair do Dodge ...}
{12003}{}{Scatter!}
{12004}{}{Cair pra trás!}
{12005}{}{Espero para conseguir esses fuckers quando Fallout 3 sair ...}
{12006}{}{Bishop pode manter seu maldito dinheiro ...}
#
# moving in to attack
#
{12020}{}{Alvo adquirido!}
{12021}{}{Alguém me cobre!}
{12022}{}{Hut hut hut hut hut hut}
{12023}{}{Hut hut hut hut hut hut}
{12024}{}{Hut hut hut hut hut hut}
{12025}{}{Beije seu culo adeus ...}
{12026}{}{Tempo para esmagar esta mãe fucker ...}
{12027}{}{Travar e carregar!}
{12028}{}{Rock and roll!}
{12029}{}{Olha quem entrou na zona de fogo livre ...}
{12030}{}{Melhor espero que você tenha embalado alguns estimulantes, tribais ...}
{12031}{}{Contato!}
{12032}{}{A área foi violada!}
{12033}{}{Nos conseguimos um intruso, meninos!}
{12034}{}{Scramble, meninos, nós temos um intruso!}
{12035}{}{Você tem alguma areia aqui dentro ...}
{12036}{}{Pelo número, pessoas, pelos números.}
{12037}{}{Atenção aos detalhes, pessoas!}
{12038}{}{Coloque algum fogo suprimindo! Mantenha a cabeça baixa!}
#
# attacking
#
{12040}{}{Desperte-os!}
{12041}{}{Você é uma merda sem sorte, tribal ...}
{12042}{}{Eu vou colocar minha bota até agora em seu traseiro, você sentirá cheiro de sapato por uma semana.}
{12043}{}{:: Eu quero ser um ranger aéreo ... ::}
{12044}{}{Seja crítico!}
{12045}{}{Você quer um pouco disso ?! YOU WANT SOME OF THIS?!}
{12046}{}{Hiyaaaaaa !!!}
{12047}{}{Pegar algum!}
{12048}{}{Melhor espero que você tenha embalado alguns estimulantes, tribais ...}
{12049}{}{Beije seu culo adeus ...}
#
# target being missed
#
{12060}{}{Você luta como pessoas velhas foda!}
{12061}{}{Ha! Perdido!}
{12062}{}{Muito rápido para você ...}
{12063}{}{Você vai morrer muito ...}
{12064}{}{Sloppy ...}
{12065}{}{Fraco E lento, vejo.}
#
############################################
# 12100 Raider Captain
############################################
#
#  running away
#
{12100}{}{Tenho que sair daqui!}
{12101}{}{Eu voltarei...}
{12102}{}{Você não está me matando hoje!}
{12103}{}{Mais tarde, normie!}
{12104}{}{Você não foi ouvido o último de mim!}
{12105}{}{Você pagará por isso - mais tarde!}
#
# moving in to attack
#
{12120}{}{Você é história!}
{12121}{}{Carne fresca...}
{12122}{}{Ah, chegou o jantar.}
{12123}{}{Cérebro ...}
{12124}{}{Eu vou cavar seu túmulo ...}
{12125}{}{Espero poder manter sua cabeça intacta ...}
#
# attacking
#
{12140}{}{Seu número está pronto!}
{12141}{}{Não se preocupe gritando por misericórdia ...}
{12142}{}{Eu vou gostar disso}
{12143}{}{Oooo, isso deve doer!}
{12144}{}{}
{12145}{}{Eu vou comer seu fígado!}
{12146}{}{Espero que você não morra muito rápido}
{12147}{}{Hora do jantar!}
{12148}{}{Morrer!}
{12149}{}{Eu como punks como você para o café da manhã, and lunch}
#
# target being missed
#
{12160}{}{Você não pode me machucar!}
{12161}{}{}
{12162}{}{Você perdeu, normie!}
{12163}{}{Você perdeu, normie!}
{12164}{}{Você não pode matar o que não pode bater!}
{12165}{}{Muito devagar!}
#
############################################
# 12200 Gangster (Combat Messages)
############################################
#
#  running away
#
{12200}{}{Whoa, esta merda está ficando muito pesada.}
{12201}{}{Hora de ir buscar alguns dos outros meninos ...}
{12202}{}{Eu terei você na próxima vez!}
{12203}{}{Você só tem sorte, eu não tenho nenhum estimpacks em mim ...}
{12204}{}{Tempo para sair do Dodge.}
{12205}{}{Precisa encontrar alguns estimpacks, rápido ...}
#
# moving in to attack
#
{12220}{}{Eu vou rolar você como um dado.}
{12221}{}{E aqui estava eu, pensando que não iria matar ninguém hoje ...}
{12222}{}{Parece que o Gólgota acabou de receber um novo residente ...}
{12223}{}{Parece que vamos fazer isso da maneira mais difícil ...}
{12224}{}{Eu vou tirar os dentes e tirar os dados deles.}
{12225}{}{Parece que alguém joga com a vida deles ...}
{12226}{}{Eu vou matar você, sua família, então seu cachorro.}
{12227}{}{Tempo para tirar o lixo ...}
{12228}{}{Vou encaixá-lo como um wishbone ...}
#
# attacking
#
{12240}{}{Eu vou chutar sua bunda com tanta força que você estará vestindo sua bunda como chapéu.}
{12241}{}{Lady Luck não está com você hoje ...}
{12242}{}{Eu vou vencê-lo até você ser feio.}
{12243}{}{Tempo para colocar sua bunda num túmulo.}
{12244}{}{Vou arrancar seu coração e pisá-lo.}
{12245}{}{Gostaria de ter tempo para colocar sua cabeça em um torno ...}
{12246}{}{Deixe-me mostrar-lhe o que fazemos com lixo por aqui ...}
{12247}{}{Eu vou te bater muito, você vai pensar que é um terremoto ...}
{12248}{}{Eu já tive o suficiente deste turd ...}
{12249}{}{Diga olá aos anjos para mim ...}
#
# target being missed
#
{12260}{}{Movimentos como esse vão colocá-lo no hospital ...}
{12261}{}{Você bate como uma cadela ...}
{12262}{}{Agradável. Vou mostrar-lhe como é feito em um segundo.}
{12263}{}{Você é cego e estúpido?}
{12264}{}{Voce voa em Jet ou algo assim?}
{12265}{}{Você não conseguiu atingir o lado largo de um cassino.}
{12266}{}{Se você tentou bater no ar, você sentiria falta.}
#
############################################
# 12300 Raider (Hit Locations)
############################################
#
# target hit in head
#
{12300}{}{Ngggg}
{12301}{}{Minha ... cabeça ... ficando tonta}
{12302}{}{Ugnnn!}
{12303}{}{Não é o rosto! Não é o rosto!}
#
# target hit in left arm
#
{12310}{}{Meu ... braço ... meu ... lindo ... braço.}
{12311}{}{Médico! Meu braço está fodido!}
{12312}{}{* hffff *}
#
# target hit in right arm
#
{12320}{}{Minha mão do golpe! Você não tem vergonha ?!}
{12321}{}{Médico! Meu braço está fodido!}
{12322}{}{Parece que não posso polir minha arma com essa mão mais ...}
#
# target hit in torso
#
{12330}{}{Meu baço!}
{12331}{}{Hnrgggg}
{12332}{}{* hff *}
{12333}{}{Você ... vai ... pagar ... por ... isso!}
{12334}{}{* Ooooof *}
{12335}{}{Nggg! Plexo solar!}
#
# target hit in right leg
#
{12360}{}{Dammit! Minha perna!}
{12361}{}{* Ergg *}
{12362}{}{Preciso de um estímulo para a minha perna ...}
{12363}{}{Urggg ... leg's ... ferrado ...}
#
# target hit in left leg
#
{12370}{}{Dammit! Minha perna!}
{12371}{}{* Ergg *}
{12372}{}{Preciso de um estímulo para a minha perna ...}
{12373}{}{Urggg ... leg's ... ferrado ...}
#
# target hit in eyes
#
{12380}{}{Meu olho! Meu lindo olho!}
{12381}{}{Tentando paralisar minha percepção de profundidade, hein?}
{12382}{}{Não consigo ... ver ... sangue ... em ... olhos ...}
#
# target hit in groin
#
{12390}{}{O que você acha disso? Algum filme de ação barato?}
{12391}{}{Agora eu não posso soar como se tivesse um par.}
{12392}{}{Bem, vão minhas bolas de bronze.}
{12393}{}{Desculpe-me por um momento enquanto viro por mim mesmo.}
{12394}{}{Ótimo. Um personagem de jogador com uma fixação de bola.}
{12395}{}{Deixe-me deitar-se por um segundo, então eu vou matar você.}
{12396}{}{Nuts!}
#
####################################################################################
#
# 26000         V13/V15
#
#                    26000  Normal Khan
#                    26100  Tough Khan
#
####################################################################################
#
############################################
# 26000 Khan - Normal
############################################
#
#  running away
{26000}{}{Fugir! Fugir!}
{26001}{}{Retiro!}
{26002}{}{Reagrupar!}
{26003}{}{Cair pra trás!}
{26004}{}{Retirar o!}
{26005}{}{Estou fora daqui!}
#
# moving in to attack
#
{26020}{}{Mate esse idiota!}
{26021}{}{Você já está morto...}
{26022}{}{Eu vou te fuder!}
{26023}{}{Este é meu!}
{26024}{}{Pegue-os!}
{26025}{}{Suas orelhas farão um bom troféu!}
#
# attacking
#
{26040}{}{Aproveite os últimos segundos da sua vida}
{26041}{}{Sangue! Sangue! Sangue!}
{26042}{}{Seu coração é meu!}
{26043}{}{Eu adoro fazer isso com você!}
{26044}{}{Suas armas serão meus troféus!}
{26045}{}{Morte e desmembramento. Apenas duas das minhas coisas favoritas!}
{26046}{}{Você é meu para matar!}
{26047}{}{Seus ossos devem lixiviar nos resíduos!}
{26048}{}{Sangue e escuridão!}
{26049}{}{Vou pegar seu cadáver!}
{26050}{}{Explora o bastardo scraggin!}
#
############################################
# 26100 Khan - Tough
############################################
#
#  running away
#
{26100}{}{Khans! Me proteja!}
{26101}{}{Retiro!}
{26102}{}{Reagrupar!}
{26103}{}{Cair pra trás!}
{26104}{}{Retirar o!}
{26105}{}{Romper e reagrupar!}
#
# moving in to attack
#
{26106}{}{Deixe o desafio começar!}
{26107}{}{Eu vou usar você para a prática do alvo!}
{26108}{}{Não tenha piedade para você!}
{26109}{}{Este é meu!}
{26110}{}{Khans ataca!}
{26111}{}{É hora da festa!}
{26111}{}{Alguém por favor matará esse desperdício de carne!}
#
# attacking
#
{26112}{}{Khans matar!}
{26113}{}{Khans são a elite dos resíduos!}
{26114}{}{Eu sou supremo!}
{26115}{}{Khans vai governar!}
{26116}{}{Khans são invencíveis!}
{26117}{}{Não retroceder! Nenhuma rendição!}
{26118}{}{Você é meu para matar!}
{26119}{}{Eu vou fazer um colar fora de seus dentes!}
{26120}{}{Sangue e escuridão!}
{26121}{}{Khans são os fortes!}
#
# target being missed
#
{26122}{}{Boa forma, mas estou aqui!}
{26123}{}{Eu não posso ser tocado!}
{26124}{}{Eu sou indestrutível!}
{26125}{}{Meu sangue é mais forte que o seu!}
{26126}{}{Talvez devêssemos parar o tempo suficiente para você conseguir alguns tiros de prática!}
{26127}{}{Você não é digno de combater comigo!}
{26128}{}{Por que estou desperdiçando meu tempo com você?}
#
####################################################################################
#
# 32000        San Fransisco
#
#                    32000  Shi Hit Location Messages
#                    32100  The Dragon
#                    32200  Lo Pan
#                    32300  Chip
#                    32400  Badger
#                    32500  Ryan
#                    32600  Shi Guards
#                    32700  Elron Hit Locations
#                    32800  Elron Guards
#                    32900  Ron Cruz/Nikki Goldman
#                    33000  OZ-9
#                    33100  OZ-7
#                    33200  Punk (Hit Locations)
#
####################################################################################
#
############################################
# 32000 Shi Hit Locations
############################################
#
# target hit in head
#
{32000}{}{Meu rosto! Meu rosto!}
{32001}{}{Meu couro cabeludo!}
{32002}{}{oooh ... meus ouvidos ...}
#
# target hit in left arm
#
{32010}{}{Ow, meu braço!}
{32011}{}{Ow!}
{32012}{}{Você quebrou meu braço!}
#
# target hit in right arm
#
{32020}{}{Ow, meu braço!
{32021}{}{Wahhhh!}
{32022}{}{Meu Deus! Meu braço!}
#
# target hit in torso
#
{32030}{}{OUCH!}
{32031}{}{Eu acho que vou desmaiar...}
{32032}{}{Hey! Meu baço!}
{32033}{}{Oooof!}
{32034}{}{Isso dói!}
{32035}{}{Eu acho que você atingiu meu fígado!}
{32036}{}{Ohhh, dor!}
#
# target hit in right leg
#
{32060}{}{Ow, minha perna}
{32061}{}{Meu joelho!}
{32062}{}{Direito na artéria!}
#
# target hit in left leg
#
{32070}{}{Ow, minha perna}
{32071}{}{:: hop ... hop ::}
{32072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32080}{}{Não consigo ver! Seu desgraçado!}
{32081}{}{Meu rosto! Meus olhos! Arrrrgh!}
{32082}{}{Onde está você? Socorro!}
#
# target hit in groin
#
{32090}{}{Ooooooooo, minha virilha! Ooooooo ...}
{32091}{}{Eu ... eu ... ouch ...}
{32092}{}{::choradeira::}
{32093}{}{::vomitar::}
{32094}{}{Eu ... não posso ... respirar ...}
{32095}{}{A dor, a dor ...}
#
############################################
# 32100 The Dragon
############################################
#
#  running away
#
{32100}{}{Seu kung fu é melhor do que o meu!}
{32101}{}{Você é verdadeiramente poderoso. Adeus.}
{32102}{}{Aieee! O mal triunfa!}
{32103}{}{Ah não...}
{32104}{}{Eu falhei.}
{32105}{}{Estou desonrado.}
#
# moving in to attack
#
{32120}{}{Me aflige em atacar você.}
{32121}{}{Eu aconselho você a fugir.}
{32122}{}{Apenas um covarde usa armas.}
{32123}{}{Fuga enquanto você pode.}
{32124}{}{Prepare-se, malfeitor.}
{32125}{}{Corra e não vou te machucar.}
{32126}{}{Se você insistir em lutar ...}
{32128}{}{Você acha que pode me vencer?}
#
# attacking
#
{32140}{}{Haiiiiiiii-YA!}
{32141}{}{Chop-socky!}
{32142}{}{rooOOOooo!}
{32143}{}{Hai!
{32144}{}{Huh!}
{32145}{}{Hai oooOOo!}
{32146}{}{Hai - ah!}
{32147}{}{Mostre-me alguns!}
{32148}{}{MAMÃ BEEF!}
{32149}{}{Um chute nos olhos!}
#
# target being missed
#
{32160}{}{Apenas um covarde usa armas.}
{32161}{}{Você tem medo de enfrentar um verdadeiro lutador?}
{32162}{}{Seu kung fu não é bom aqui.}
{32163}{}{Entrega!}
{32164}{}{Você chama isso de luta?}
{32165}{}{Você se move como um iaque grávida.}
#
############################################
# 32200 Lo Pan
############################################
#
#  running away
#
{32200}{}{Estou à procura de uma menina de olhos verdes ... adeus!}
{32201}{}{Sim senhor ... o cheque está no correio.}
{32202}{}{Eu acho que tenho uma consulta ...}
{32203}{}{Ok, você ganha!}
{32204}{}{Desisto!}
{32205}{}{Seu kung-fu é mais forte do que o meu!}
#
# moving in to attack
#
{32220}{}{Relâmpago! Trovão! Mate-os para mim!}
{32221}{}{Seus poderes são fracos!}
{32222}{}{Seu kung fu não pode me machucar!}
{32223}{}{Sou invencível!}
{32224}{}{Fuja, sem fim!}
{32225}{}{O trovão rola em sua direção!}
{32226}{}{Flutuar como uma borboleta!}
{32228}{}{Ferroa como uma abelha!}
#
# attacking
#
{32240}{}{Quem é Jack Burton?}
{32241}{}{É demais pedir que você morra ?!}
{32242}{}{Você pagou suas dívidas, Jack?}
{32243}{}{Há um problema com o seu rosto.}
{32244}{}{O cheque está no CORREIO!}
{32245}{}{O Inferno espera por você!}
{32246}{}{Saude seus antepassados   por mim!}
{32247}{}{Eu sou imortal!}
{32248}{}{Chop-suey!}
{32249}{}{Hai-YA!}
#
# target being missed
#
{32260}{}{Feelin 'meio invencível!}
{32261}{}{Dê-me o seu melhor tiro.}
{32262}{}{Eu posso aceitar isso.}
{32263}{}{Você não sabe como lutar, não é?}
{32264}{}{Você chama isso de luta?}
{32265}{}{:: bocejos ::}
#
############################################
# 32300 Chip
############################################
#
#  running away
#
{32300}{}{Eu tenho uma esposa e filhos!}
{32301}{}{Noo ... é meu aniversário!}
{32302}{}{Ow ... meu baço ...}
{32303}{}{De volta ao hospital!}
{32304}{}{Deve ... proteger. ... buraco de baço ...}
{32305}{}{Ah, meu fígado dolorido.}
#
# moving in to attack
#
{32320}{}{Não me faça usar a faca trapaceira.}
{32321}{}{Eu vou te dar uma batida tão baixa ...}
{32322}{}{Você come pequenos pedaços de merda para o café da manhã?}
{32323}{}{Vou chutar o seu maldito traseiro.}
{32324}{}{Eu vou te cortar!}
{32325}{}{Eu acho que é tudo o que tenho a dizer.}
#
# attacking
#
{32340}{}{Estrondo!}
{32341}{}{Eu repreendei sua bunda!}
{32342}{}{SIM!}
{32343}{}{Sim, querida, sim!}
{32344}{}{Você quer algo disso?}
{32345}{}{Não se mova desse jeito!}
{32346}{}{Shagadelic, bay-by!}
{32347}{}{Oh, esse é o seu rosto?}
{32348}{}{Você é um rosto cheio de feio, aintcha?}
#
# target being missed
#
{32360}{}{Perdi meu baço! Ha ha!}
{32361}{}{Você é um merda!}
{32362}{}{Ha ha! Eu mando!}
{32363}{}{Me dê um beijo, doçura.}
{32364}{}{Hora de filmar, bebê.}
{32365}{}{Eu vou te cortar!}
#
############################################
 # 32400 Badger
############################################
#
#  running away
#
{32400}{}{O rosto! Não toque na cara!}
{32401}{}{Meu cabelo está arruinado, você é besta!}
{32402}{}{Desgraçado! I'll sodomize you for that!}
{32403}{}{Eu preciso de uma arma maior!}
{32404}{}{Waaaaaaaaaaa !!!}
{32405}{}{AAGGH !! Você me disparou na bunda !!}
#
# moving in to attack
#
{32420}{}{Eu vou fazer você desejar que seu pai saia cedo!}
{32421}{}{Diga ... você tem um rosto como uma bunda!}
{32422}{}{Vamos ver o que você tem, dickcheese.}
{32423}{}{Curve-se e pegue seus tornozelos, bub!}
{32424}{}{Para Shane !!}
{32425}{}{Vou tentar tornar isso tão doloroso quanto possível.}
{32426}{}{Mente se eu quebre suas rótulas primeiro?}
{32428}{}{Vamos, garotinha. Mostre-me o que você conseguiu.}
#
# attacking
#
{32440}{}{Espero que você não precise desse braço ...}
{32441}{}{Maldita seja, é preciso machucar, hein?}
{32442}{}{Uf-da!}
{32443}{}{Adoro o cheiro de sangue pela manhã ...}
{32444}{}{Menino, você é um sangramento, não é?}
 {32445}{}{::::arroto!:::::}
{32446}{}{Você quebrou a camisa, cara !!!!}
{32447}{}{Enema de chumbo quente chegando!}
{32448}{}{Coma isso!!}
#
# target being missed
#
{32460}{}{Você atira pior do que a minha mãe!}
{32461}{}{Porra, você sugam!}
{32462}{}{Volte para L.A., ya puss!}
{32463}{}{Quer que eu fique parado para você?}
{32464}{}{::: brapp :::}
{32465}{}{Oh, bom ...}
#
############################################
# 32500 Ryan
############################################
#
#  running away
#
{32500}{}{Holy gee, eu queria lamber-lhes!}
{32501}{}{La la la ... ajuda!}
{32502}{}{Ha ha OW!}
{32503}{}{AT! AT! Em at at at at!}
{32504}{}{Ay carumba!}
{32505}{}{Heeeelp!}
#
# moving in to attack
#
{32520}{}{Você não quer nada disso!}
{32521}{}{Venha pegar algum!}
{32522}{}{Você quer algo disso? Huh? Huh?}
{32523}{}{Vamos! Eu vou te violar!}
{32524}{}{Você está tão morto.}
{32525}{}{Você acabou de abrir toda uma lata de whoopass.}
{32526}{}{Eu tenho um pouco para você, oh, sim.}
#
# attacking
#
{32540}{}{Você deve lutar por essa merda.}
{32541}{}{:: canta ::}
{32542}{}{Iii ... sempre amará YOOUUUUU}
{32543}{}{Não podemos simplesmente nos dar bem?}
{32544}{}{Você está tão morto.}
{32545}{}{Curva por um segundo ...}
{32546}{}{Recebi um presente para você.}
{32547}{}{Você quer uma parte de mim?}
{32548}{}{Ele dispara ... ele marca!}
{32549}{}{Que tal um pouco de amor?}
#
# target being missed
#
{32560}{}{Está certo!}
{32561}{}{Está certo!}
{32562}{}{Ha ha ha!}
{32563}{}{Você já melhorou?}
{32564}{}{Não é possível tocar isso!}
{32565}{}{Ow! Ha ha ... apenas brincando.}
#
############################################
# 32600 Shi Guards
############################################
#
#  running away
#
{32600}{}{Aiee!}
{32601}{}{Próxima classificação, entre!}
{32602}{}{Cair pra trás!}
{32603}{}{Fugir! Fugir!}
{32604}{}{Fugir!}
#
# moving in to attack
#
{32620}{}{Prepare-se para ser desonrado.}
{32621}{}{Os pilares do céu tremem ...}
{32622}{}{... as flechas de veneno caem ...}
{32623}{}{Aqui vem o Porkchop Express.}
{32624}{}{Nós o advertimos ...}
{32625}{}{Um ex-gaijin, chegando!}
{32626}{}{Adeus, morto.}
#
# attacking
#
{32640}{}{Algo para você...}
{32641}{}{... algo para sua mãe ...}
{32642}{}{... algo para o seu pai ...}
{32643}{}{... algo para sua irmã ...}
{32644}{}{... e algo para seus antepassados!}
{32645}{}{Saia!}
{32646}{}{Morrer!}
{32647}{}{Adeus!}
{32648}{}{Deixe-me desonrar você!}
{32649}{}{Sua presença me ofende.}
#
# target being missed
#
{32660}{}{Está tudo dentro dos reflexos.}
{32661}{}{Gaijin tolo!}
{32662}{}{:: suspiros :: Quando lutamos com alguém BOM?}
{32663}{}{Isso vai acabar?}
{32664}{}{Quando você começa a me bater?}
{32665}{}{Isso está ficando velho ...}
#
############################################
# 32700 Elron Hit Locations
############################################
#
# target hit in head
#
{32700}{}{Meu rosto! Meu rosto!}
{32701}{}{Star Father! Curta-me!}
{32702}{}{Ouch! Preciso de gelo para a minha cabeça}
#
# target hit in left arm
#
{32710}{}{Ow, meu braço}
{32711}{}{Ow!}
{32712}{}{Você quebrou meu braço!}
#
# target hit in right arm
#
{32720}{}{Ow, meu braço}
{32721}{}{Wahhhh!}
{32722}{}{By Elron! Meu braço!}
#
# target hit in torso
#
{32730}{}{Ow! Isso realmente machucou!}
{32731}{}{Eu acho que vou desmaiar}
{32732}{}{Ouch!}
{32733}{}{Star Father! Ajude-me!}
{32734}{}{Isso dói!}
{32735}{}{Apenas me deixe em paz!}
{32736}{}{Ohhh, dor!}
#
# target hit in right leg
#
{32760}{}{Ow, minha perna!}
{32761}{}{Meu joelho!}
{32762}{}{Ow!}
#
# target hit in left leg
#
{32770}{}{Ow, minha tíbia!}
{32771}{}{Meu joelho!}
{32772}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32780}{}{Ow !! Meus olhos!}
{32781}{}{Meu rosto! Meus olhos! Arrrrgh!}
{32782}{}{Meus olhos!}
#
# target hit in groin
#
{32790}{}{Ooooooooo, minha virilha! Ooooooo ...}
{32791}{}{Oww ... Burns!}
{32792}{}{Urp!}
{32793}{}{::suspiro::}
{32794}{}{Eu ... não posso ... respirar ...}
{32795}{}{Bom ... já estou ... estéril ...}
#
############################################
# 32800 Elron Guards
############################################
#
#  running away
#
{32800}{}{Star Father! Ajude-nos!}
{32801}{}{Meus anodins!}
{32802}{}{Eu quero viver para ver o Quetzel!}
{32803}{}{Eeek!}
{32804}{}{Salve nossas celebridades!}
{32805}{}{OZ-9! Ajude-nos!}
#
# moving in to attack
#
{32820}{}{Eu vou "ajustar" você tão difícil ...}
{32821}{}{Estarei tão feliz quando deixarmos o seu tipo atrás ...}
{32822}{}{Muito ruim, você não verá o futuro.}
{32823}{}{Nunca desafie o Pai das Estrelas.}
{32824}{}{Elron vai feri-lo!}
{32825}{}{Nós somos a vingança do Pai da Estrela!}
{32826}{}{Morte aos não iniciados!}
{32828}{}{Pense nisso como um zeta-scan diferente.}
#
# attacking
#
{32840}{}{Você tem energia suja!}
{32841}{}{Para o Pai da Estrela!}
{32842}{}{Para Elron!}
{32843}{}{Para Quetzel!}
{32844}{}{Para OZ-9!}
{32845}{}{Morra, não lavado!}
{32846}{}{Sully não nosso santuário!}
{32847}{}{Isto é para OZ-9!}
#
# target being missed
#
{32860}{}{Sua energia está desalinhada.}
{32861}{}{Se você fosse um de nós, você teria me atingido.}
{32862}{}{Você tem energia suja.}
{32863}{}{Não acredite em um verdadeiro crente!}
{32864}{}{Isso irá redefinir seus anodynes!}
{32865}{}{Impuro!}
#
############################################
# 32900 Ron Cruz/Nikki Goldman
############################################
#
#  running away
#
{32900}{}{Eu sou uma estrela de cinema!}
{32901}{}{Celebridade chegando!}
{32902}{}{Isso não está no script!}
{32903}{}{Star Father! Socorro!}
{32904}{}{Mas eu sou famoso!}
#
############################################
# 33000 OZ-9
############################################
#
#  running away
#
{33000}{}{Star Father! Ajude-me!}
{33001}{}{Não! Eu não!}
{33002}{}{Por favor, mate alguém!}
{33003}{}{Não me mate! Eu sou OZ-9!}
{33004}{}{Guardas! Ajude-me!}
{33005}{}{Você não pode me matar! Eu sou muito importante!}
#
# moving in to attack
#
{33020}{}{Você poderia ter sido um de nós.}
{33021}{}{O estúpido sempre liga seus melhores.}
{33022}{}{Sua impureza brilha!}
{33023}{}{Se você tivesse tomado os juramentos ...}
{33024}{}{O Pai das Estrelas te derrubará.}
{33025}{}{Você nunca verá o planeta Quetzel.}
{33026}{}{Você é um traidor da evolução da humanidade.}
{33028}{}{Indigna e impura.}
#
# attacking
#
{33040}{}{Meu toque irá purificá-lo!}
{33041}{}{Eu vou te morrer!}
{33042}{}{Em nome de Elron!}
{33043}{}{Para a glória de Star Father!}
{33044}{}{Sinta a ira de Elron!}
{33045}{}{Isso otimizará você!}
#
# target being missed
#
{33060}{}{O Pai das Estrelas me salva!}
{33061}{}{Elron protege-me!}
{33062}{}{Seus anodins estão entupidos!}
{33063}{}{Sua energia não é boa.}
{33064}{}{Você não sabe como se concentrar?}
#
############################################
# 33100 OZ-7
############################################
#
#  running away
#
{33100}{}{Star Father! Ajude-me!}
{33101}{}{Prefiro estar no Quetzel!}
{33102}{}{Eu não! Não me mate!}
{33103}{}{Eu sou apenas um lacaio!}
{33104}{}{Eu não tomo as decisões!}
{33105}{}{Eu não sou o único que você quer!}
#
# moving in to attack
#
{33120}{}{Eu prefiro não fazer isso ...}
{33121}{}{Tem certeza de que não preferiria desistir?}
{33122}{}{Podemos resolver isso, não podemos?}
{33123}{}{Se o OZ-9 diz que você é ruim, você deve estar mal.}
{33124}{}{Para ... um ... a glória de Elron!}
{33125}{}{Lutar é ruim para seus anodinos ...}
{33126}{}{Não sou bom com essas coisas ameaçadoras.}
{33128}{}{Minhas desculpas se estou prestes a te machucar.}
#
# attacking
#
{33140}{}{Tenha cuidado!}
{33141}{}{:: ele balança os olhos e ataca ::}
{33142}{}{Aqui vem outro ataque ...}
{33143}{}{Se você fugir, não teria que fazer isso.}
{33144}{}{Continue! Saia daqui!}
{33145}{}{Shoo! Shoo!}
{33146}{}{Pare de lutar!}
{33147}{}{Hoooooooowdy ho!}
{33148}{}{Você cheira como flores.}
{33149}{}{Nós podemos resolver isso!}
#
# target being missed
#
{33160}{}{Por que você está tentando me machucar?}
{33161}{}{O que eu já fiz com você?}
{33162}{}{Nós não temos que lutar, você sabe!}
{33163}{}{Eu não quero machucá-lo!}
{33164}{}{Eu não quero que você me machuque!}
{33165}{}{Podemos resolver isso como adultos?}

############################################
# 33200 Punk Hit Locations
############################################
#
# target hit in head
#
{33200}{}{Eu acho que você quebrou meu maxilar!}
{33201}{}{Meu pêndolo!}
{33202}{}{Isso deixará uma cicatriz desagradável.}
#
# target hit in left arm
#
{33210}{}{Minha mão escrita!}
{33211}{}{Meu cotovelo!}
{33212}{}{Ei! Assista!}
#
# target hit in right arm
#
{33220}{}{Ahhh! Aiee! Ahh!}
{33221}{}{Wahhhh!}
{33222}{}{Ow! Meu ulna !!}
#
# target hit in torso
#
{33230}{}{Eu acho que você conseguiu meu rim!}
{33231}{}{Meu plexo solar!}
{33232}{}{:: ofegante ::}
{33233}{}{Oooof!}
{33234}{}{Você não precisa fazer isso ...}
{33235}{}{Ok, isso doeu.}
{33236}{}{Ohhh ... owwww}
#
# target hit in right leg
#
{33260}{}{Minha fibia!}
{33261}{}{Meu joelho!}
{33262}{}{Ow!}
#
# target hit in left leg
#
{33270}{}{Oooh, meu fêmur!}
{33271}{}{Meu joelho!}
{33272}{}{Isso será um limper ...}
#
# target hit in eyes
#
{33280}{}{Eu acho que você separou minha retina!}
{33281}{}{Meu humor aquoso! Meu humor vítreo!}
{33282}{}{Eu estou cego! Eu estou cego!}
#
# target hit in groin
#
{33290}{}{Isso é ... isso é ... doloroso ...}
{33291}{}{Mãe...}
{33292}{}{::choradeira::}
{33293}{}{Doce mãe de DEUS!}
{33294}{}{Hmmm. Ow. Hmmm.}
{33295}{}{Acho que vou entrar em estado de choque agora.}
#
####################################################################################
#
# 36000        Special Encounters (Randoms)
#
#                   36000 Kaga (Hit Locations)
#                   36100 Kaga (Combat Messages - Area 1)
#                   36200 Kaga (Combat Messages - Area 2)
#                   36300 Kaga (Combat Messages - Area 3)
#                   36400 Kaga (Combat Messages - Area 4)
#                   36500 Kaga (Combat Messages - Area 5)
#                   36600 Super Mutant (Master Army) - Hit Locations
#                   36700 Super Mutant (Master Army) - Combat Messages
#                   36800 Bounty Hunters - Combat Messages
#
####################################################################################
#
############################################
# 36000 Kaga (Hit Locations)
############################################
#
# target hit in head
#
{36000}{}{Gawd! Isso me atingiu na cabeça!}
{36001}{}{Ow! Minha cabeça!}
{36002}{}{Oof! A cabeça de Kaga está em chamas!}
#
# target hit in left arm
#
{36010}{}{Minha mão!}
{36011}{}{Ow! Bom, eu sou dobrada}
{36012}{}{Ow !!}
#
# target hit in right arm
#
{36020}{}{Ow, meu braço}
{36021}{}{Você quebrou meu braço!}
{36022}{}{Você vai se arrepender disso!}
#
# target hit in torso
#
{36030}{}{(Grunhido!)}
{36031}{}{É apenas uma ferida de carne!}
{36032}{}{Grrr!}
{36033}{}{Você vai se arrepender disso!}
{36034}{}{Você deve parar enquanto estiver à frente!}
{36035}{}{Bom tiro. Minha vez}
#
# target hit in right leg
#
{36060}{}{Ow, minha perna}
{36061}{}{Você vai pagar por isso!}
{36062}{}{Ah! MINHA PERNA!}
#
# target hit in left leg
#
{36070}{}{Minha perna!}
{36071}{}{Unh! Visando um pouco baixo você não está?}
{36072}{}{Você não estava tentando bater na minha perna, você estava??!}
#
# target hit in eyes
#
{36080}{}{Maldito sangue nos meus olhos!}
{36081}{}{Meu olho! Você pagará por aquele!}
{36082}{}{Desgraçado!}
#
# target hit in groin
#
{36090}{}{Oooooo, tempo limite, eu tenho que pegar algo}
{36091}{}{Ooo! Kaga precisa aprender esse movimento ...}
{36092}{}{Urg! Petey! Você está bem lá embaixo?}
{36093}{}{Isso ... wheeeeze ... doeu!}
{36094}{}{Urp!}
{36095}{}{Suspiro!}
#
############################################
# 36100 Kaga (Combat Messages) Area 1
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36100}{}{Nós nos encontraremos novamente!}
{36101}{}{Eu voltarei...}
{36102}{}{Nunca fui espancado antes!}
{36103}{}{Vou me dedicar a caçá-lo!}
{36104}{}{Você não foi ouvido o último de mim!}
{36105}{}{Você pagará por isso - mais tarde!}
#
# moving in to attack
#
{36120}{}{Eu deveria ter sido o Escolhido!}
{36121}{}{Arroyo vai se arrepender de me expulsar}
{36122}{}{Eu vou me vingar de você!}
{36123}{}{Kaga enviará você para a próxima vida}
{36124}{}{Outro Escolhido para matar!}
#
# attacking
#
{36140}{}{Sua mãe não está aqui para ajudá-lo}
{36141}{}{Eu vou gostar disso}
{36142}{}{Oooo, isso deve doer!}
{36143}{}{Vou levar sua cabeça de volta ao Idoso}
{36144}{}{Eu vou comer seu fígado!}
{36145}{}{Espero que você não morra tão rápido quanto os outros}
{36146}{}{Outro Escolhido para matar!}
{36147}{}{Morrer!}
{36148}{}{Grite por mim}
#
# target being missed
#
{36160}{}{Você não pode me machucar!}
{36161}{}{Os espíritos estão me protegendo.}
{36162}{}{Espero que não seja o seu melhor tiro.}
{36163}{}{Bwahaha. Kaga nem teve que pato!}
{36164}{}{Você não pode matar o que não pode bater!}
{36165}{}{Muito devagar!}
#
############################################
# 36200 Kaga (Combat Messages) Area 2
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36200}{}{Nós nos encontraremos novamente!}
{36201}{}{Eu voltarei...}
{36202}{}{Você não pode matar o Great Kaga!}
{36203}{}{Você está com sorte! Kaga tem negócios em outro lugar}
{36204}{}{Você e Kaga se encontrarão de novo}
{36205}{}{Você pagará por isso - mais tarde!}
#
# moving in to attack
#
{36220}{}{Depois de matá-lo, vou arder Arroyo no chão!}
{36221}{}{Eu sou temido por todos}
{36222}{}{Kaga terá sua cabeça para um troféu}
{36223}{}{Entregue-se e farei sua morte rapidamente}
#
# attacking
#
{36240}{}{Sinta a ira de Kaga!}
{36241}{}{Não se preocupe gritando por misericórdia ...}
{36242}{}{Eu vou gostar disso}
{36243}{}{Oooo, Kaga sentiu aquele daqui}
{36244}{}{Vou levar sua cabeça de volta ao Idoso}
{36245}{}{Eu vou esculpir seu coração com uma colher!}
{36246}{}{Espero que você não morra tão rápido quanto os outros}
{36247}{}{Outro Escolhido para matar!}
{36248}{}{Morrer!}
{36249}{}{Grite por mim}
#
# target being missed
#
{36260}{}{Você não pode me machucar!}
{36261}{}{Os espíritos estão me protegendo.}
{36262}{}{Espero que não seja o seu melhor tiro.}
{36263}{}{Bwahaha. Kaga nem teve que pato!}
{36264}{}{Você não pode matar o que não pode bater!}
{36265}{}{Muito devagar!}
#
############################################
# 36300 Kaga (Combat Messages) Area 3
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36300}{}{Isso está a ser um mau hábito}
{36301}{}{Kaga precisa de mais treinamento}
{36302}{}{Eu voltarei. Yada yada yada Eu vou matar você}
{36303}{}{Você está com sorte! Kaga tem negócios em outro lugar}
{36304}{}{Você e Kaga se encontrarão de novo}
{36305}{}{Você pagará por isso - mais tarde!}
#
# moving in to attack
#
{36320}{}{Kaga e o Escolhido se encontram de novo}
{36321}{}{Vamos acabar com isso}
{36322}{}{Você vai se arrepender de ter ouvido o nome de Kaga!}
{36323}{}{Minhas habilidades aumentaram desde a última vez que nos encontramos}
#
# attacking
#
{36340}{}{Sinta a ira de Kaga!}
{36341}{}{Eu vou gostar disso}
{36342}{}{Oooo, Kaga sentiu aquele daqui}
{36343}{}{Vou levar sua cabeça de volta ao Idoso}
{36344}{}{Eu vou esculpir seu coração com uma colher!}
{36345}{}{Espero que você não morra tão rápido quanto os outros}
{36346}{}{Outro Escolhido para matar!}
{36347}{}{Morrer!}
{36348}{}{Grite por mim}
#
# target being missed
#
{36360}{}{Você não pode me machucar!}
{36361}{}{Os espíritos estão me protegendo.}
{36362}{}{Espero que não seja o seu melhor tiro.}
{36363}{}{Bwahaha. Kaga nem teve que pato!}
{36364}{}{Você não pode matar o que não pode bater!}
{36365}{}{Muito devagar!}
#
############################################
# 36400 Kaga (Combat Messages) Area 4
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36400}{}{Isso está a ser um mau hábito}
{36401}{}{Kaga precisa de mais treinamento}
{36402}{}{Este não é o último que você verá de Kaga}
{36403}{}{Você está com sorte! Kaga tem negócios em outro lugar}
{36404}{}{Você e Kaga se encontrarão de novo}
{36405}{}{Você pagará por isso - mais tarde!}
#
# moving in to attack
#
{36420}{}{O Escolhido nunca mais voltará para Arroyo!}
{36421}{}{Kaga vai te esmagar!}
{36422}{}{Kaga não teme a ninguém!}
{36423}{}{Deixe Kaga ensinar-lhe novas habilidades que ele aprendeu}
#
# attacking
#
{36440}{}{Sinta a ira de Kaga!}
{36441}{}{Mantenha-se parado para que Kaga possa obter um bom tiro}
{36442}{}{Eu vou gostar disso}
{36443}{}{Oooo, Kaga sentiu aquele daqui}
{36444}{}{Vou levar sua cabeça de volta ao Idoso}
{36445}{}{Eu vou esculpir seu coração com uma colher!}
{36446}{}{Espero que você não morra tão rápido quanto os outros}
{36447}{}{Outro Escolhido para matar!}
{36448}{}{Morrer!}
{36449}{}{Grite por mim}
#
# target being missed
#
{36460}{}{Você não pode me machucar!}
{36461}{}{Os espíritos estão me protegendo.}
{36462}{}{Espero que não seja o seu melhor tiro.}
{36463}{}{Bwahaha. Kaga nem teve que pato!}
{36464}{}{Você não pode matar o que não pode bater!}
{36465}{}{Muito devagar!}
#
############################################
# 36500 Kaga (Combat Messages) Area 5
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36500}{}{}
{36501}{}{}
{36502}{}{}
{36503}{}{}
{36504}{}{}
{36505}{}{}
#
# moving in to attack
#
{36520}{}{Kaga está pronto para você agora}
{36521}{}{Você não é igual para Kaga}
{36522}{}{Kaga enviará você para a próxima vida}
{36523}{}{Kaga vai sentir sua falta}
#
# attacking
#
{36540}{}{Sinta a ira de Kaga!}
{36541}{}{Kaga será famosa por matar você}
{36542}{}{Eu vou gostar disso}
{36543}{}{Oooo, Kaga sentiu aquele daqui}
{36544}{}{Vou levar sua cabeça de volta ao Idoso}
{36545}{}{Ele termina aqui Escolhido}
{36546}{}{Kaga tem que te matar agora}
{36547}{}{Morrer!}
{36548}{}{Grite por mim}
#
# target being missed
#
{36560}{}{Você não pode me machucar!}
{36561}{}{Os espíritos estão me protegendo.}
{36562}{}{Espero que não seja o seu melhor tiro.}
{36563}{}{Bwahaha. Kaga nem teve que pato!}
{36564}{}{Você não pode matar o que não pode bater!}
{36565}{}{Muito devagar!}
#
#
############################################
# 36600 Super Mutant (Master Army) - Hit Locations
############################################
#
# target hit in head
#
{36600}{}{Ahhhgh! Meu rosto!}
{36601}{}{Meu rosto! Você deve sofrer!}
{36602}{}{Ahhhgh! Eu rasgo você em pedaços!}
#
# target hit in left arm
#
{36610}{}{Ahhhgh!}
{36611}{}{Ow! Você quase machucou Escolhido!}
{36612}{}{Ahhhgh! Eu encolho seu pescoço por isso!}
#
# target hit in right arm
#
{36620}{}{Ahhhgh!}
{36621}{}{Ow! Você quase machucou Escolhido!}
{36622}{}{Ahhhgh! Eu encolho seu pescoço por isso!}
#
# target hit in torso
#
{36630}{}{Oof!}
{36631}{}{Grrr!}
{36632}{}{Eu mato você por isso!}
{36633}{}{Você não me machucou quando você está morto!}
{36634}{}{Eu ri do seu ataque fraco!}
{36635}{}{Ah!}
{36636}{}{Eu vou mergulhar você!}
{36637}{}{Grrr! Você me irrita}
{36638}{}{Agh!}
{36639}{}{Eu vou te devolver essa dor!}
{36640}{}{Oof!}
{36641}{}{Ouch!}
{36642}{}{Hmm, você pode ser um problema}
{36643}{}{Grrr! Estou ansioso para a sua morte}
{36644}{}{Você pode me machucar, mas você não pode ganhar!}
{36645}{}{Ow! Não foi boa idéia me machucar}
#
# target hit in right leg
#
{36660}{}{Ahhhgh! Minha perna}
{36661}{}{Você chama essa dor? Eu ri!}
{36662}{}{Ahhhgh! Eu encolho seu pescoço por isso!}
#
# target hit in left leg
#
{36670}{}{Ahhhgh! Minha perna}
{36671}{}{Você chama essa dor? Eu ri!}
{36672}{}{Ahhhgh! Devo pegar o pescoço para isso!}
#
# target hit in eyes
#
{36680}{}{Ahhhgh! Miserável humano! Eu sou cego!}
{36681}{}{Ahhhgh! Dor! O que é que você fez!}
{36682}{}{Ahhhgh! Eu torturarei muitos dias!}
#
# target hit in groin
#
{36690}{}{Isso é fraqueza humana!}
{36691}{}{Você chama essa dor? Eu ri!}
{36692}{}{Você é estúpido, humano!}
{36693}{}{Por que você me ataca lá?}
{36694}{}{Eu vou machucá-lo por muitas horas}
{36695}{}{Por que você me ataca lá?}
#
############################################
# 36600 Super Mutant (Master Army) - Combat Messages
############################################
#
#  running away
#
{36700}{}{Corre!}
{36701}{}{Você não vai me matar!}
{36702}{}{Eu retornarei!}
{36703}{}{Meus amigos conseguem você por mim!}
{36704}{}{Você paga por isso - mais tarde!}
{36705}{}{Nós somos escolhidos! Você morre mais tarde!}
#
# moving in to attack
#
{36720}{}{Sua morte vem!}
{36721}{}{Aqueles que incomodam Escolhido, não incomodem ninguém!}
{36722}{}{As armas humanas não podem me prejudicar!}
{36723}{}{Você sofrerá, sofrerá grande!}
{36724}{}{Quando eu lutar, eu mato!}
{36725}{}{Quem é estúpido o suficiente para nos irritar?}
{36726}{}{Eu vejo inimigos para destruir!}
{36727}{}{Você sofrerá, sofrerá grande!}
#
# attacking
#
{36740}{}{Agora você morre}
{36741}{}{Ninguém te poupa agora!}
{36742}{}{Deixe-me ver sua dor!}
{36743}{}{Agora você morre burning death!}
{36744}{}{Morra tolo humano!}
{36745}{}{Agora você morre a screaming death}
{36746}{}{Sofra!}
{36747}{}{Agora eu te amo}
{36748}{}{Você não pode lutar contra o Escolhido!}
{36749}{}{Sofre, humano!}
#
# target being missed
#
{36760}{}{Por que você luta?}
{36761}{}{É o melhor que os humanos podem fazer!}
{36762}{}{Você não tem poder!}
{36763}{}{Você me faz rir muito!}
{36764}{}{Isso foi um ataque?}
{36765}{}{Nós somos os escolhidos!}
#
####################################################################################
#
#                    Party Members
#
####################################################################################
#
#                     Notes
#
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed
#
#                     40000 Sulik *
#                     40400 Vic
#                     40800 MacRae *
#                     41200 Lenny *
#                     41600 Marcus *
#                     42000 Myron *
#                     42400 Davin
#                     42800 Miria
#                     43200 Laddie
#                     43600 Cyberdog
#                     44000 Robo-Brain (Idiot/Chimp) *
#                     44400 Robo-Brain (Human/Cybernetic) *
#                     44800 Goris **
#
####################################################################################
#
############################################
# 44800 Goris
############################################
#
# target hit in head
#
{44800}{}{Estou cheio de pernas, mas isso ainda doeu.}
{44801}{}{Tenho uma grande dor de cabeça.}
{44802}{}{Umph. Não é a cabeça!}
{44803}{}{Eu também posso fazer tiros na cabeça, você sabe!}
{44804}{}{Arrrgh! Tonto...}
#
# target hit in left arm
#
{44810}{}{Eu vou matar você com meu outro braço.}
{44811}{}{Não preciso de ambos os braços para arruinar o seu dia!}
{44812}{}{Eu não uso esse braço de qualquer maneira.}
{44813}{}{Ouch! Posso usar um estilingue por aqui.}
{44814}{}{Um braço para baixo, um para ir!}
 #
# target hit in right arm
#
{44820}{}{Ei, esse é o meu braço de luta!}
{44821}{}{Maldito que o braço dói!}
{44822}{}{Eu posso tomar o gosto de você com apenas um braço.}
{44823}{}{Braço direito ... arrgh!}
{44824}{}{Você bateu no meu braço. Eu arranco seu braço!}
#
# target hit in torso
#
{44830}{}{Umph ... não pode ... respirar.}
{44831}{}{Eu sou menos algumas costelas depois disso.}
{44832}{}{Ouch! Eu odeio tiros.}
{44833}{}{Arrghhh! Dores no peito!}
{44834}{}{Plexo solar ... eegad que dói!}
{44835}{}{Isso é uma briga ou você está apenas tentando chamar minha atenção?}
{44836}{}{Deixe-me saber se isso deveria doer. Vou chorar por você.}
{44837}{}{Sua mãe te ensinou como lutar?}
{44838}{}{Oh, a dor (bocejo). Por favor, não me machuque mais.}
{44839}{}{Você chama isso de sucesso. Deixe-me mostrar-lhe como é feito!}
{44840}{}{Eu vou chutar sua bunda por essa.}
{44841}{}{Uau! Isso pica um pouco.}
{44842}{}{Eu deixei o cofre para isso !?}
{44843}{}{Eu vou precisar de férias.}
{44844}{}{Yeeeouch! Isso machuca!}
{44845}{}{Isso não doeu nada}
{44846}{}{Onde é um stimpak quando você precisa de um?}
{44847}{}{Assim que eu puder me mudar de novo, você já teve}
{44848}{}{Eu sou impermeável à dor!}
{44849}{}{Eu vou fazer o monster mash em seu rosto!}
#
# target hit in right leg
#
{44860}{}{Ótimo. Eu serei o único Deathclaw em casa com uma coxa.}
{44861}{}{Ouch! Minha perna...}
{44862}{}{Você pagará com sua perna pelo que você fez com a minha.}
{44863}{}{Vou perder essa perna ...}
{44864}{}{Não preciso de duas pernas para matar você.}
#
# target hit in left leg
#
{44870}{}{Ótimo. Uma perna bum.}
{44871}{}{Droga! A perna...}
{44872}{}{Não é a perna ... não pode caminhar como está.}
{44873}{}{Você paralisou minha perna, eu abaixei sua perna.}
{44874}{}{Arrggh! Esse joelho dói!}
#
# target hit in eyes
#
{44880}{}{Não consigo ver!}
{44881}{}{Não são os olhos!}
{44882}{}{Sangue ... nos olhos ... não pode ver.}
{44883}{}{Não consigo vê-lo, mas posso sentir o seu cheiro.}
{44884}{}{Eu vou precisar de óculos depois daquele!}
#
# target hit in groin
#
{44890}{}{A virilha é um tiro tão barato!}
{44891}{}{Não ... batendo ... abaixo ... o cinto!}
{44892}{}{Isso está lutando sujo. Que tal se eu bater na virilha?}
{44893}{}{Odeio os tiros da virilha! Unngh ...}
{44894}{}{Tiro de Crotch ... bom, eu não sou humano!}
#
#  running away
#
{44900}{}{Tempo de fiança!}
{44901}{}{Estou indo embora!}
{44902}{}{Retiro!}
{44903}{}{Cair pra trás!}
{44904}{}{Estou fora daqui!}
{44905}{}{Os pés não me faltam agora!}
{44906}{}{Fora do caminho, estou indo embora!}
{44907}{}{Não estou recuando, esta é uma retirada estratégica.}
{44908}{}{Eu já tive o suficiente dessa merda!}
{44909}{}{Eu tenho que sair daqui!}
#
# moving in to attack
#
{44920}{}{Venha aqui para que eu possa bater em você!}
{44921}{}{Você é todo meu!}
{44922}{}{É você ou eu ... e eu voto voce!}
{44923}{}{É o seu funeral!}
{44924}{}{Venha e pegue!}
{44925}{}{Prepare-se para encontrar sua desgraça!}
{44926}{}{Melhor beijar seu despedida, enquanto você ainda pode.}
{44927}{}{Eu vou pintar você vermelho!}
{44928}{}{É hora da festa!}
{44929}{}{Eu estou indo em!}
{44930}{}{Eu vou te ver na linha de frente!}
{44931}{}{Tempo para chegar e tocar em alguém!}
{44932}{}{Avançar e aniquilar!}
{44933}{}{Eu vou cair em você como feio em um ser humano!}
{44934}{}{Tempo para se tornar físico!}
{44935}{}{Levando-se de perto e pessoal.}
{44936}{}{Bad ass em movimento!}
{44937}{}{Entrada!}
{44938}{}{Locked no alvo e homing!}
{44939}{}{Há uma tempestade que vem!}
#
# attacking
#
{44940}{}{Eu vou machucá-lo ... ruim!}
{44941}{}{Isso vai te machucar muito mais do que eu.}
{44942}{}{Faça aos outros antes que eles façam com você!}
{44943}{}{Se há uma parte de você que não dói, é a próxima!}
{44944}{}{Contato com esportes. Eu amo isso!}
{44945}{}{Diga-me seu nome para que eu possa contatar seus parentes mais próximos.}
{44946}{}{Eu sou aquele que colocou a "morte" no deathclaw!}
{44947}{}{É melhor dar do que receber!}
{44948}{}{Espero que você esteja gostando tanto quanto eu.}
{44949}{}{Isso doeu? Caso contrário, posso fazê-lo mais difícil na próxima vez.}
{44950}{}{Nós temos um sangramento aqui!}
{44951}{}{Vai demorar mais do que um estimulante para corrigi-lo quando terminar.}
{44952}{}{Espero que você tenha um seguro médico. Você vai precisar disso.}
{44953}{}{Aqui, um rip, há um rip, em todos os lugares, um rip rip ...}
{44954}{}{Eu não me importo com quem começou, eu pretendo terminá-lo!}
{44955}{}{Eu adoro o som de carne rasgada, não é?}
{44956}{}{Apenas aquecendo, o melhor ainda está por vir.}
{44957}{}{Apenas afiando minhas garras.}
{44958}{}{Ooops! Espero que você não tenha precisado disso!}
{44959}{}{Se você cair e ficar lá eu vou embora!}
#
# target being missed
#
{44960}{}{Você vai parar de se mudar para que eu possa bater em você?}
{44961}{}{Óculos. Deve procurar obter alguns óculos.}
{44962}{}{Não ria. Quando eu atingi-lo, vai doer!}
{44963}{}{Arrg! Grng! Ghrr! Lá! (Palavras de quatro letras de Deathclaw)}
{44964}{}{Eu acho que não devo fazer uma carreira fora da luta.}
{44965}{}{Como eu poderia perder alguma coisa tão grande quanto você!}
{44966}{}{Assim que eu chegar, você está com problemas.}
{44967}{}{Você não é uma pequena merda ágil.}
{44968}{}{Fico feliz que minha mãe não me tenha visto fazer isso.}
{44969}{}{Por que estou balançando lá quando você está aqui?}
{44970}{}{Que embaraçoso. Por favor, não conte a ninguém que fiz.}
{44971}{}{Isso realmente me irrita!}
{44972}{}{Está bem. Eu perdi! Pode acontecer com qualquer um!}
{44973}{}{Eu terei você na próxima vez.}
{44974}{}{Muito bom, Grace!}
{44975}{}{Esse foi um exemplo brilhante de perder o alvo!}
{44976}{}{Estou começando a pensar que não estou preparado para isso.}
{44977}{}{Arrggh! Não posso acreditar que senti sua falta!}
{44978}{}{Eu abaixei o ar naquele que eu fiz!}
{44979}{}{Eu apenas sinto sua falta ou o que!}
#
