#
# Messages used in gdialog.c for custom NPC combat control.
#
{0}{}{Explosão}
{1}{}{Fugir}
{2}{}{Pref de armas.}
{3}{}{Distância}
{4}{}{Ataque Quem}
{5}{}{Uso de Chem}

{10}{}{Feito}
{11}{}{Cancelar}

#
# Explosão options.
#
{99}{}{Não aplicável.}
{100}{}{Sempre!}
{101}{}{Às vezes, não se preocupe em me bater}
{102}{}{Certifique-se de que você não me atingirá}
{103}{}{Tenha cuidado para não bater em mim}
{104}{}{Tenha certeza de que não me atingirá}

#
# Run away options.
#
{200}{}{Abjeto covarde}
{201}{}{O seu dedo machuca}
{202}{}{Você está sangrando um pouco}
{203}{}{Não me sinto bem}
{204}{}{Você precisa de um torniquete}
{205}{}{Nunca!}

#
# Weapon pref options.
#
{300}{}{Nenhum}
{301}{}{Melee}
{302}{}{Melee então variou}
{303}{}{A distância, em melee}
{304}{}{Ranged}
{305}{}{Desarmado}

#
# Distância options.
#
{400}{}{Fica perto de mim}
{401}{}{Carregar!}
{402}{}{Snipe o inimigo}
{403}{}{Por si só}
{404}{}{Fique onde está}

#
# Attack who options.
#
{500}{}{Quem está me atacando}
{501}{}{O mais forte}
{502}{}{O mais fraco}
{503}{}{Quem quiser}
{504}{}{Quem está mais perto}

#
# Chem use options.
#
{600}{}{estou limpo}
{601}{}{Stimpacks quando machucou um pouco}
{602}{}{Stimpacks quando machucou muito}
{603}{}{Alguma parte do tempo}
{604}{}{Qualquer quimico a qualquer momento}
