{100}{}{Foguete}
{200}{}{Bola de plasma}
{300}{}{Explosão}
{400}{}{Sangue}
{500}{}{Hex não-trans}
{501}{}{}
{600}{}{faca}
{700}{}{lança}
{800}{}{EMP Explosão}
{900}{}{Laser Blast}
{1000}{}{Explosão de plasma}
{1100}{}{Explosão}
{1200}{}{Bloqueador de rolagem}
{1300}{}{Bolt de eletricidade}
{1400}{}{Explosão}
{1500}{}{Explosão}
{1600}{}{Grade de saída}
{1700}{}{Grade de saída}
{1800}{}{Grade de saída}
{1900}{}{Grade de saída}
{2000}{}{Grade de saída}
{2100}{}{Grade de saída}
{2200}{}{Grade de saída}
{2300}{}{Grade de saída}
{2400}{}{Flare}
{2500}{}{Grenade}
{2600}{}{Rocha}
{2700}{}{Explosão}
{2800}{}{Explosão}
{2900}{}{Explosão}
{3000}{}{Coquetel Molotov}
{3100}{}{Grade de saída}
{3200}{}{Grade de saída}
{3300}{}{Grade de saída}
{3400}{}{Grade de saída}
{3500}{}{Grade de saída}
{3600}{}{Grade de saída}
{3700}{}{Grade de saída}
{3800}{}{Grade de saída}
{3900}{}{Grade de saída}
{4000}{}{Grade de saída}
{4100}{}{Grade de saída}
{4200}{}{Grade de saída}
{4300}{}{Grade de saída}
{4400}{}{Grade de saída}
{4500}{}{Grade de saída}
{4600}{}{Grade de saída}
{4700}{}{Robot Foguete}
{4701}{}{}
{4800}{}{Ka-Pow!}
{4801}{}{}
{4900}{}{Plant Spike}
{4901}{}{}
{5000}{}{Dual Bola de plasma}
