{100}{}{Armadura de couro}
{101}{}{Seu fato básico de couro. Finamente trabalhada a partir de couro brahmin bronzeado.}
{200}{}{Metal Armor}
{201}{}{Placas de metal polidas, formando rapidamente um terno de armadura.}
{300}{}{Power Armor}
{301}{}{Um terno autônomo de armadura de tecnologia avançada. Alimentado por um reator de microfusão, com combustível suficiente para durar uma centena de anos.}
{400}{}{Faca}
{401}{}{Uma arma de corte e punhalada. Min ST: 2.}
{500}{}{Clube}
{501}{}{Um bastão militar ou policial. Madeira pesada. Min ST: 3.}
{600}{}{Marreta}
{601}{}{Um grande martelo com alça grande. Muito popular com a multidão muscular. Min ST: 6.}
{700}{}{Lança}
{701}{}{Um barramento com ponta de barbear. O eixo é de madeira e a ponta é aço trabalhado. Min ST: 4.}
{800}{}{Pistola de 10mm}
{801}{}{Uma pistola autoloading de Colt 6520 10mm. Cada puxão do gatilho irá recarregar automaticamente a arma de fogo até o compartimento estar vazio. Apenas tiro único, usando a poderosa rodada de 10mm. Min ST: 3.}
{900}{}{SMG de 10mm}
{901}{}{H & K MP9 Submachinegun (variante de 10 mm). Um SMG de tamanho médio, capaz de disparar e disparar. Min ST: 4.}
{1000}{}{Rifle de caça}
{1001}{}{Um rifle semi-automático de Colt Rangemaster, em calibre .223. Single-shot apenas. Min ST: 5.}
{1100}{}{Flamer}
{1101}{}{Um lança-chamas modelo Flambe 450, variação varmiter. Atire um curto spray de líquido extremamente quente e inflamável. Requer combustível especializado para funcionar corretamente. Min ST: 6.}
{1200}{}{Minigun}
{1201}{}{Um Rochawell CZ53 Personal Minigun. Um chaingun de canas múltiplas que dispara munição de 5mm em mais de 60.000 RPM. Min ST: 7.}
{1300}{}{Lançador de foguetes}
{1301}{}{Um lançador de foguete Rochawell BigBazooka. Com o gatilho deluxe de 3 lb. Fires AP ou Rochaet Explosivos. Min ST: 6.}
{1400}{}{Rochaet Explosivo}
{1401}{}{Um foguete com uma grande ogiva explosiva.}
{1500}{}{Rifle Plasma}
{1501}{}{A Winchester Model P94 Rifle Plasma. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by Micro Fusion Cells. Min ST: 6.}
{1600}{}{Pistola a laser}
{1601}{}{A Wattz 1000 Pistola a laser. Civilian model, so the wattage is lower than military or police versions. Uses small energy cells. Min ST: 3.}
{1700}{}{Armadura de combate}
{1701}{}{Armadura de alta tecnologia, feita de polímeros defensivos avançados.}
{1800}{}{Águia do deserto .44}
{1801}{}{Uma antiga pistola de Eagle do deserto, em .44 magnum. O interesse por filmes do final do século 20 tornou esta uma das armas de mão mais populares de todos os tempos. Min ST: 4.}
{1900}{}{Rocha}
{1901}{}{É uma pedra. O Granite-Inc. modelo é uma versão atualizada. Min ST: 1.}
{2000}{}{Pé de cabra}
{2001}{}{Um metal muito sólido e pesado, especialmente concebido para exercer alavancagem. Ou pound heads. Min ST: 5.}
{2100}{}{Juntas de bronze}
{2101}{}{Aperto de junção endurecido que é realmente feito de aço. Eles protegem sua mão e fazem mais danos, em combate desarmado. Min ST: 1.}
{2200}{}{Pistola de 14mm}
{2201}{}{Uma pistola automática Sig-Sauer 14mm. Grande revólver de tiro simples. Excelente artesanato. Min ST: 4.}
{2300}{}{Rifle de assalto}
{2301}{}{An AK-112 5mm Rifle de assalto. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds. Min ST: 5.}
{2400}{}{Pistola de plasma}
{2401}{}{Glock 86 Pistola de plasma. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a small energy cell. Min ST: 4.}
{2500}{}{Grenade (Frag)}
{2501}{}{Uma granada de fragmentação genérica. Contém uma pequena quantidade de explosivos altos, o próprio recipiente formando a maior parte dos fragmentos prejudiciais. Explode no contato. Min ST: 3.}
{2600}{}{Grenade (Plasma)}
{2601}{}{Uma unidade de entrega de plasma magneticamente selada, com explosivos detonantes. Cria uma explosão de plasma superaquecido no contato. Min ST: 4.}
{2700}{}{Grenade (Pulso)}
{2701}{}{Uma granada de pulso eletromagnético, gerando um intenso campo magnético na detonação. Não afeta criaturas biológicas. Fuze contato. Min ST: 4.}
{2800}{}{Gatling Laser}
{2801}{}{Um laser H & K L30 Gatling. Projetados especificamente para uso militar, estes estavam no estágio do protótipo no início da Guerra. Vários barris permitem um disparo mais longo antes do superaquecimento. Alimentado por Micro Fusion Cells. Min ST: 6.}
{2900}{}{JHP de 10mm}
{2901}{}{Munição. Calibre: 10mm, pontos vazios}
{3000}{}{AP 10mm}
{3001}{}{Munição. Calibre: 10mm, piercing de armadura.}
{3100}{}{.44 Magnum JHP}
{3101}{}{Um tijolo de munição, .44 calibre magnum, pontos ocos.}
{3200}{}{Combustível de lança-chamas}
{3201}{}{Um cilindro contendo um combustível líquido extremamente inflamável para lança-chamas.}
{3300}{}{AP de 14mm}
{3301}{}{Munição de grande calibre. Piercing de armadura de 14mm.}
{3400}{}{.223 FMJ}
{3401}{}{Um caso de munição, calibre .223, Full Metal Jacket.}
{3500}{}{JHP de 5mm}
{3501}{}{Um tijolo de munição pequena e leve. Calibre: 5mm, ponto vazio com camisa.}
{3600}{}{AP de 5mm}
{3601}{}{Um tijolo de munição de calibre pequeno. Piercing de armadura de 5mm.}
{3700}{}{Rochaet AP}
{3701}{}{Um casco de foguete, com um explosivo menor, mas projetado para perfurar a armadura.}
{3800}{}{Pequena célula de energia}
{3801}{}{Uma unidade de armazenamento de energia pequena e autônoma.}
{3900}{}{Micro Fusion Cell}
{3901}{}{Uma unidade de produção de energia de médio porte. Planta de fusão autônoma.}
{4000}{}{Stimpak}
{4001}{}{Uma cura química. Quando injetado, o quim proporciona cura imediata de feridas menores.}
{4100}{}{Dinheiro}
{4101}{}{Licitação legal para o mundo dos resíduos.}
{4200}{}{Geladeira}
{4201}{}{Uma geladeira. Fora do refrigerante.}
{4300}{}{Cofre de gelo}
{4301}{}{No baú de gelo antigo. As dobradiças estão em bom estado de funcionamento.}
{4400}{}{Cofre de gelo}
{4401}{}{No baú de gelo antigo. As dobradiças estão em bom estado de funcionamento.}
{4500}{}{Throwing Faca}
{4501}{}{Uma faca, equilibrada especificamente para jogar. Fabricado em titânio e laser afiado. Min ST: 3.}
{4600}{}{Bolsa}
{4601}{}{Uma bolsa de tamanho médio. Feito de cabelos de brâmana tecendo.}
{4700}{}{Kit de primeiros socorros}
{4701}{}{Um pequeno kit contendo equipamentos médicos básicos. Bandagens, envoltórios, spray anti-séptico e muito mais.}
{4800}{}{RadAway}
{4801}{}{Uma solução química que se liga a partículas de radiação e passa por seu sistema. Toma tempo para trabalhar.}
{4900}{}{Antídoto}
{4901}{}{Uma garrafa contendo um antídoto preparado para o veneno. Um líquido leitoso com pedaços flutuantes de carne de radscorpion.}
{5000}{}{Item Reservado}
{5001}{}{Este é um item reservado. NÃO USE.}
{5100}{}{Dinamite}
{5101}{}{Um alto explosivo, constituído por nitroglicerina misturada com a substância absorvente kiselguhr. Inclui um temporizador.}
{5200}{}{Contador Geiger}
{5201}{}{A Wattz Electronics C-Radz model Contador Geiger. Detects the presence and strength of radiation fields.}
{5300}{}{Mentats}
{5301}{}{Uma pilha de chems que alteram a mente. Aumenta as funções relacionadas à memória e acelera outros processos mentais. Muito formador de hábitos.}
{5400}{}{Stealth Boy}
{5401}{}{Um dispositivo furtivo pessoal RobCo Stealth Boy 3001. Gera um campo modulador que transmite a luz refletida de um lado de um objeto para o outro.}
{5500}{}{Chip de água}
{5501}{}{Este é um chip de água Vault-Tec. Eles geralmente são embalados em grupos de cinco para uma caixa.}
{5600}{}{Tags para cães}
{5601}{}{Um conjunto de etiquetas de cães militares. O nome de Darkwater é legível, mas não é demais.}
{5700}{}{Erro}
{5701}{}{Um microfone em miniatura e um dispositivo transmissor.}
{5800}{}{Fita}
{5801}{}{Uma fita Holodisc Wattz Electronics. Esta fita em particular parece estar em condições muito precárias.}
{5900}{}{Sensor de movimento}
{5901}{}{Um sensor de movimento modelo Wattz Electronics C-U. Detecta o movimento do material biológico a uma distância de metros usando um dispositivo de radar sintonizado. Ter um em seu inventário também irá ajudá-lo a evitar encontros ao ar livre (+ 20% de habilidade de Outdoorsman).}
{6000}{}{Estante}
{6001}{}{Uma estante de madeira.}
{6100}{}{Estante}
{6101}{}{Uma estante de madeira.}
{6200}{}{Estante}
{6201}{}{Uma estante de madeira.}
{6300}{}{Estante}
{6301}{}{Uma estante de madeira.}
{6400}{}{Estante}
{6401}{}{Uma estante de madeira.}
{6500}{}{Estante}
{6501}{}{Uma estante de madeira.}
{6600}{}{Escrivaninha}
{6601}{}{Uma mesa de madeira.}
{6700}{}{Escrivaninha}
{6701}{}{Uma mesa de madeira.}
{6800}{}{Cômoda}
{6801}{}{Uma cômoda de madeira.}
{6900}{}{Cômoda}
{6901}{}{Uma cômoda de madeira.}
{7000}{}{Cômoda}
{7001}{}{Uma cômoda de madeira.}
{7100}{}{Fruta}
{7101}{}{Um pedaço de fruta estranho. Não foram adicionados conservantes e nenhuma corante alimentar adicional.}
{7200}{}{Pasta}
{7201}{}{Uma maleta, com um rótulo Made-in-USA. Couro. Bom estado, mas o bloqueio de combinação está quebrado.}
{7300}{}{Grande livro da ciência}
{7301}{}{Um conjunto de livros, contendo informações sobre diferentes campos científicos.}
{7400}{}{Jaqueta de couro}
{7401}{}{Uma jaqueta de couro preta e pesada.}
{7500}{}{Ferramenta}
{7501}{}{Um conjunto de ferramentas, contendo várias ferramentas úteis, incluindo alicate.}
{7600}{}{Deans Electronics}
{7601}{}{Um livro de estudo sobre o campo da eletrônica. Uma nota na capa diz que é para o "jovem eletricista em desenvolvimento em todos!"}
{7700}{}{Electronic Lockpick}
{7701}{}{Um Wattz Electronics Micromanipulator FingerCoisa bloqueio eletrônico. Para derrotar bloqueios eletrônicos e dispositivos de segurança.}
{7800}{}{Pintura Fuzzy}
{7801}{}{Uma imagem de um cantor. Obviamente, muito antigo. A imagem tem um revestimento de feltro que ainda está em boas condições.}
{7900}{}{Flare}
{7901}{}{Um alargamento. Cria luz por um curto período de tempo. O papel está um pouco gasto, mas, de outro modo, está em boas condições. Torça o topo para ativá-lo.}
{8000}{}{Livro de primeiros socorros}
{8001}{}{Um livro de estudo sobre os conceitos e o uso prático de habilidades de primeiros socorros.}
{8100}{}{Iguana-on-a-stick}
{8101}{}{Uma iguana cozida, assada na própria pele.}
{8200}{}{Chave}
{8201}{}{Uma chave. Uma chave abrirá um bloqueio particular.}
{8300}{}{Chave Ring}
{8301}{}{Múltiplas chaves.}
{8400}{}{Lockpicks}
{8401}{}{Um conjunto de ferramentas de serralheiro. Inclui todas as escolhas e chaves de tensão necessárias para abrir fechaduras convencionais e travões.}
{8500}{}{Explosivos plásticos}
{8501}{}{Um pedaço de Cordex, uma marca militar de explosivos plásticos. Altamente estável, muito destrutivo. Inclui um temporizador.}
{8600}{}{Manual do Escoteiro}
{8601}{}{Um livro sobre os métodos e ideais do Escotismo. Informações muito práticas sobre a vida ao ar livre.}
{8700}{}{Buffout}
{8701}{}{Esteróides altamente avançados. Enquanto isso, eles aumentam a força e os reflexos. Muito formador de hábitos.}
{8800}{}{Assistir}
{8801}{}{Um relógio caro. Na verdade, não funciona, mas ainda parece legal.}
{8900}{}{Motor}
{8901}{}{Um motor elétrico de 40 hp.}
{9000}{}{Mochila}
{9001}{}{Uma mochila básica, com tiras de transporte opcionais.}
{9100}{}{Doctor's Bolsa}
{9101}{}{Este saco marrom contém instrumentos e chems utilizados pelos médicos na aplicação do seu comércio.}
{9200}{}{Cauda Escorpião}
{9201}{}{A cauda cortada de um radscorpion.}
{9300}{}{Bolsa}
{9301}{}{Uma bolsa de tamanho médio. Feito de cabelos de brâmana tecendo.}
{9400}{}{Espingarda}
{9401}{}{Uma espingarda Winchester Widowmaker com dois canos de calibre 12. Barril curto, com aderência de mogno. Min ST: 4.}
{9500}{}{12 ga. Espingarda Shells}
{9501}{}{Espingarda ammunition. This particular ammo is marked: "12-gauge shells, not for use by children under the age of 3."}
{9600}{}{Red Pass Chave}
{9601}{}{Uma chave de segurança eletrônica, codificada por cores em vermelho.}
{9700}{}{Blue Pass Chave}
{9701}{}{Uma chave de segurança eletrônica, com cores codificadas em azul.}
{9800}{}{Lixo}
{9801}{}{Uma pilha de peças sucatas. Um pouco de tudo.}
{9900}{}{Gold Locket}
{9901}{}{Um valioso medalhão de ouro.}
{10000}{}{Rádio}
{10001}{}{A model 2043B Rádio Communicator, from the fine people at Wattz Electronics. Dependable, rugged, and camouflaged. With the optional RS-121 interface.}
{10100}{}{Isqueiro}
{10101}{}{Um isqueiro butano prateado, em boas condições.}
{10200}{}{Armas e balas}
{10201}{}{Um pano de arma. Uma revista dedicada ao uso prático de armas de fogo, e a revisão tendenciosa ocasional.}
{10300}{}{Iguana-on-a-stick}
{10301}{}{Alguns carne e vegetais carbonizados em uma vara de cozinhar.}
{10400}{}{Fita Recorder}
{10401}{}{Um gravador de fita Wattz Electronics Play-It-For-Me. Reproduz e grava as fitas de gravação de alta densidade padrão de 30 minutos.}
{10500}{}{Chave}
{10501}{}{Uma chave especial de algum tipo.}
{10600}{}{Nuka-Cola}
{10601}{}{Uma garrafa de Nuka-Cola, o softdrink aromatizado do mundo pós-nuclear. Quente e plana.}
{10700}{}{Ossos}
{10701}{}{Uma coleção de ossos estranhos.}
{10800}{}{Ossos}
{10801}{}{Uma coleção de ossos estranhos.}
{10900}{}{Rad-X}
{10901}{}{Chems anti-radiação a serem tomadas antes da exposição. Não há efeitos colaterais conhecidos.}
{11000}{}{Psicopata}
{11001}{}{Um sistema de entrega único preenchido com produtos químicos estranhos e desconhecidos de origem provavelmente militar. É suposto aumentar o potencial de combate de um soldado.}
{11100}{}{.44 magnum FMJ}
{11101}{}{Um tijolo de munição, .44 magnum calibre, casaco de metal cheio.}
{11200}{}{Urna}
{11201}{}{Uma bela urna dourada, com o nome "Harriet" inscrito na frente e cinzas por dentro.}
{11300}{}{Robes}
{11301}{}{Robes das crianças da catedral.}
{11400}{}{Mão de Tangler}
{11401}{}{Um manipulador cibernético, na forma e forma de uma mão. Danificado devido à natureza desleixada do processo de remoção.}
{11500}{}{Super Sledge}
{11501}{}{A Super Marreta, manufactured by the Brotherhood of Steel, using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback. Min ST: 5.}
{11600}{}{Estripador}
{11601}{}{A Estripador(tm) vibroblade. Powered by a small energy cell, the chainblade rips and tears into it's target. Min ST: 4.}
{11700}{}{Flor}
{11701}{}{Uma linda flor.}
{11800}{}{Laser Rifle}
{11801}{}{Um Wattz 2000 Laser Rifle. Usa células de microfusão para lasers mais poderosos e um barril prolongado para alcance adicional. Min ST: 6.}
{11900}{}{Colar}
{11901}{}{Um colar de aparência cara, feito de prata, ouro e diamantes pressionados.}
{12000}{}{Alien Blaster}
{12001}{}{Uma arma estranha de origem obviamente alienígena. Parece que pode suportar pequenas células de energia, no entanto. Min ST: 2.}
{12100}{}{Bola de 9 milímetros}
{12101}{}{Uma coleção de rodadas antigas de 9x19mm. Graxa pesada para preservá-los do meio ambiente. Balas padrão.}
{12200}{}{Mauser de 9mm}
{12201}{}{A Mauser M / 96, em Parabellum 9x19mm. Em excelente estado de conservação. Extremamente preciso. Min ST: 3.}
{12300}{}{Nulador psíquico}
{12301}{}{Um dispositivo estranho, construído a partir de uma tecnologia estranha.}
{12400}{}{Cerveja}
{12401}{}{Algum tipo de cerveja caseira.}
{12500}{}{Booze}
{12501}{}{Um licor antigo, da era pré-guerra.}
{12600}{}{Frasco de água}
{12601}{}{Um recipiente para a retenção e conservação de água ou outros líquidos.}
{12700}{}{Corda}
{12701}{}{Uma linha forte e grossa. Cerca de 45 pés de comprimento.}
{12800}{}{Footlocker}
{12801}{}{Seu footlocker básico. Possui coisas, fica ao pé da cama, pode ser trancado.}
{12900}{}{Footlocker}
{12901}{}{Seu footlocker básico. Possui coisas, fica ao pé da cama, pode ser trancado.}
{13000}{}{Footlocker}
{13001}{}{Seu footlocker básico. Possui coisas, fica ao pé da cama, pode ser trancado.}
{13100}{}{Footlocker}
{13101}{}{Seu footlocker básico. Possui coisas, fica ao pé da cama, pode ser trancado.}
{13200}{}{Armário}
{13201}{}{Um recipiente de armazenamento.}
{13300}{}{Armário}
{13301}{}{Um recipiente de armazenamento.}
{13400}{}{Armário}
{13401}{}{Um recipiente de armazenamento.}
{13500}{}{Armário}
{13501}{}{Um recipiente de armazenamento.}
{13600}{}{Armário}
{13601}{}{Um recipiente de armazenamento.}
{13700}{}{Armário}
{13701}{}{Um recipiente de armazenamento.}
{13800}{}{Armário}
{13801}{}{Um recipiente de armazenamento.}
{13900}{}{Armário}
{13901}{}{Um recipiente de armazenamento.}
{14000}{}{Cartão de acesso}
{14001}{}{Um cartão de acesso de segurança. Ainda em condições de trabalho.}
{14100}{}{Emblema COC}
{14101}{}{Um emblema na forma do símbolo Children of the Cathedral. De um lado você observa solavancos e entalhes, quase lembrando você de uma chave.}
{14200}{}{Emblema COC}
{14201}{}{Um emblema na forma do símbolo Children of the Cathedral. De um lado você observa solavancos e entalhes, quase lembrando você de uma chave.}
{14300}{}{Sniper Rifle}
{14301}{}{Um DKS-501 Sniper Rifle. Excelente arma de projétil de longo alcance. Originalmente .308, este está localizado no calibre .223 mais comum. Min ST: 5.}
{14400}{}{Super Stimpak}
{14401}{}{Um químico de cura avançado. Muito poderoso. Superstims causará uma pequena quantidade de dano após um período de tempo devido à natureza poderosa dos produtos químicos utilizados.}
{14500}{}{Estante de livros}
{14501}{}{Uma estante de madeira.}
{14600}{}{Estante de livros}
{14601}{}{Uma estante de madeira.}
{14700}{}{Estante de livros}
{14701}{}{Uma estante de madeira.}
{14800}{}{Estante de livros}
{14801}{}{Uma estante de madeira.}
{14900}{}{Estante de livros}
{14901}{}{Uma estante de madeira.}
{15000}{}{Estante de livros}
{15001}{}{Uma estante de madeira.}
{15100}{}{Prateleiras}
{15101}{}{Um conjunto de prateleiras de madeira.}
{15200}{}{Prateleiras}
{15201}{}{Um conjunto de prateleiras de madeira.}
{15300}{}{Prateleiras}
{15301}{}{Um conjunto de prateleiras de madeira.}
{15400}{}{Prateleiras}
{15401}{}{Um conjunto de prateleiras de madeira.}
{15500}{}{Prateleiras}
{15501}{}{Um conjunto de prateleiras de madeira.}
{15600}{}{Prateleiras}
{15601}{}{Um conjunto de prateleiras de madeira.}
{15700}{}{Workbench}
{15701}{}{Um banco de trabalho. Sim, seu padrão antigo, funcionamento do moinho, bancada de trabalho. Parece legal sentado lá, também.}
{15800}{}{Ferramenta Board}
{15801}{}{Este quadro possui uma variedade de ferramentas acima do popular banco de trabalho.}
{15900}{}{Coquetel Molotov}
{15901}{}{Uma granada inflamável caseira. Min ST: 3.}
{16000}{}{Gado Prod}
{16001}{}{Um produto de gado de modelo do melhor amigo do fazendeiro da Wattz Electronics. Usa pequenas células de energia para poder. Min ST: 4.}
{16100}{}{Red Ryder BB Gun}
{16101}{}{Uma arma do Red Ryder BB. O clássico. Min ST: 3.}
{16200}{}{Red Ryder LE BB Gun}
{16201}{}{Uma edição limitada da arma Red Ryder BB. Um verdadeiro clássico. Min ST: 3.}
{16300}{}{BB's}
{16301}{}{Um pacote de BB's antes da guerra. Em excelente estado de conservação. Aço inoxidável.}
{16400}{}{Brotherhood Fita}
{16401}{}{Um holodisc de considerar a Brotherhood of Steel.}
{16500}{}{Stand Iguana}
{16501}{}{A casa de Iguana Bits de Bob. O que não é amar sobre a iguana torrada?}
{16600}{}{Mesa}
{16601}{}{Uma tabela genérica. Contém coisas do chão.}
{16700}{}{Mesa}
{16701}{}{Uma tabela genérica. Contém coisas do chão.}
{16800}{}{Coisa}
{16801}{}{Estes são itens diversos, também conhecidos como "coisas".}
{16900}{}{Coisa}
{16901}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17000}{}{Coisa}
{17001}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17100}{}{Coisa}
{17101}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17200}{}{Coisa}
{17201}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17300}{}{Coisa}
{17301}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17400}{}{Coisa}
{17401}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17500}{}{Coisa}
{17501}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17600}{}{Coisa}
{17601}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17700}{}{Coisa}
{17701}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17800}{}{Coisa}
{17801}{}{Estes são itens diversos, também conhecidos como "coisas".}
{17900}{}{Coisa}
{17901}{}{Estes são itens diversos, também conhecidos como "coisas".}
{18000}{}{Caixa}
{18001}{}{Uma caixa de madeira cheia de material genérico.}
{18100}{}{Escrivaninha}
{18101}{}{Uma mesa genérica. Visto uma mesa, você viu todos eles.}
{18200}{}{Escrivaninha}
{18201}{}{Uma mesa genérica.}
{18300}{}{Escrivaninha}
{18301}{}{Uma mesa genérica.}
{18400}{}{Escrivaninha}
{18401}{}{Uma mesa genérica.}
{18500}{}{Escrivaninha}
{18501}{}{Uma mesa genérica.}
{18600}{}{Escrivaninha}
{18601}{}{Uma mesa genérica.}
{18700}{}{Escrivaninha}
{18701}{}{Uma mesa genérica.}
{18800}{}{Armário}
{18801}{}{Um armário.}
{18900}{}{Armário}
{18901}{}{Um armário.}
{19000}{}{Disco FEV}
{19001}{}{Um holotape contendo informações médicas. Pode ser usado para inserir informações em seu PIPBoy.}
{19100}{}{Disco de segurança}
{19101}{}{Uma holotape com a escrita "Log de segurança" no rótulo. Você pode usá-lo para transferir os dados que ele contém para o seu PIPBoy.}
{19200}{}{Disco de Experiência Alpha}
{19201}{}{O rótulo deste holotape lê: "Alpha Experiment Log"}
{19300}{}{Disco de Experiência Delta}
{19301}{}{O rótulo deste holotape lê: "Delta Experiment Log"}
{19400}{}{Disco Experimental de Vree}
{19401}{}{Este holotape foi atualizado com provas médicas de Vree of the BoS. Ele pode ser usado para transferir os dados para o seu PIPBoy.}
{19500}{}{Código de honra da Irmandade}
{19501}{}{Uma holotape, com um símbolo áspero da Irmandade do Aço inscrita nela. Use a fita para transferir os dados para o seu PIPBoy.}
{19600}{}{Transmissões mutantes}
{19601}{}{Este holotape parece que foi configurado para gravar dados de áudio de um rádio. Use a fita para transferir a informação para o seu PIPBoy.}
{19700}{}{Caixa}
{19800}{}{Caixa}
{19900}{}{Caixa}
{20000}{}{Caixa}
{20100}{}{Caixa}
{20200}{}{Caixa}
{20300}{}{Caixa}
{20400}{}{Caixa}
{20500}{}{Flare}
{20501}{}{Um alargamento. Cria luz por um curto período de tempo. O papel está um pouco gasto, mas, de outro modo, está em boas condições. Está acesa.}
{20600}{}{Dinamite}
{20601}{}{Um alto explosivo, constituído por nitroglicerina misturada com a substância absorvente kiselguhr. Inclui um temporizador, que está marcando.}
{20700}{}{Contador Geiger}
{20701}{}{A Wattz Electronics C-Radz model Contador Geiger. Detects the presence and strength of radiation fields. It is on.}
{20800}{}{Sensor de movimento}
{20801}{}{Um sensor de movimento modelo Wattz Electronics C-U. Detecta o movimento do material biológico a uma distância de metros usando um dispositivo de radar sintonizado. Está ligado.}
{20900}{}{Explosivos plásticos}
{20901}{}{Um pedaço de Cordex, uma marca militar de explosivos plásticos. Altamente estável, muito destrutivo. Inclui um temporizador, que está marcando.}
{21000}{}{Stealth Boy}
{21001}{}{Um dispositivo furtivo pessoal RobCo Stealth Boy 3001. Gera um campo modulador que transmite a luz refletida de um lado de um objeto para o outro.}
{21100}{}{Ossos}
{21101}{}{Você vê Ed. Ed está morto.}
{21200}{}{Tandi}
{21201}{}{Você está trocando pelo lançamento de Tandi.}
{21300}{}{Restos de Gizmo}
{21301}{}{Gizmo, former crime boss of Lixotown, is dead. And pretty stinky, too.}
{21400}{}{Escrivaninha}
{21401}{}{Uma mesa. Após uma observação adicional, você decide que ainda é uma mesa.}
{21500}{}{História da Irmandade}
{21501}{}{Um holotape contendo informações relativas à Brotherhood of Steel. Pode ser usado para inserir informações em seu PIPBoy 2000.}
{21600}{}{História de Maxson}
{21700}{}{Maxson's Journal}
{21800}{}{Cura leve}
{21801}{}{Troque por esta opção se desejar uma cura de luz.}
{21900}{}{Cura Média}
{21901}{}{Troque por esta opção se desejar cura média.}
{22000}{}{Cura pesada}
{22001}{}{Troque por esta opção se desejar muito cuidado e muita cura.}
{22100}{}{Cartão de segurança}
{22101}{}{Um cartão com um nível de segurança codificado dentro da eletrônica é muito simples.}
{22200}{}{Interruptor de campo}
{22201}{}{Um dispositivo de transmissão eletrônica, com um botão de alternar muito simples e grande. Parece que foi feito recentemente e projetado para mãos muito grandes.}
{22300}{}{Yellow Pass Chave}
{22301}{}{Uma chave de segurança eletrônica, com cores codificadas em amarelo.}
{22400}{}{Estatueta pequena}
{22401}{}{Você acha que isso pode ser uma escultura do "Pip Boy", mas você não pode ter certeza.}
{22500}{}{Cat Paw Magazine}
{22501}{}{Uma questão da revista Cat's Paw.}
{22600}{}{Caixa Of Noodles}
{22601}{}{Você não faz ideia do que significa "Spaghetti instantâneo".}
{22700}{}{Small Dusty Caixa Of Some Sort}
{22701}{}{Um jantar de televisão. Você não tem certeza, mas definitivamente não é comestível. Você não tem certeza se alguma vez foi.}
{22800}{}{Manual técnico}
{22801}{}{Um manual de reparo técnico na T-51b Power Armor.}
{22900}{}{Pequena peça de máquinas}
{22901}{}{Você vê um Motivador Sistólico. Esta peça incomum de máquinas é muito pequena.}
{23000}{}{Registros de Vault}
{23001}{}{Um compêndio de eventos e gravações importantes de um sistema informático Vault. Possivelmente danificado.}
{23100}{}{Código de Segurança da Base Militar}
{23101}{}{ }
{23200}{}{Hardened Power Armor}
{23201}{}{A suit of T-51b Power Armor. The hardening process has improved the defensive capability of this high-tech armor system.}
{23300}{}{Turbo Rifle Plasma}
{23301}{}{A modified Winchester P94 plasma rifle. The plasma bolt chamber has been hotwired to accelerate the bolt formation process. Min ST: 6.}
{23400}{}{Spiked Knuckles}
{23401}{}{An improved version of the classic Juntas de bronze. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat. Min ST: 1.}
{23500}{}{Power Fist}
{23501}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by small energy cells. Min ST: 1.}
{23600}{}{Combat Faca}
{23601}{}{A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use! Min ST: 2.}
{23700}{}{Chemistry Journals}
{23701}{}{A random pile of literature regarding the field of Chemistry. The papers on Molecular Chemistry are particularly interesting.}
{23800}{}{Regulator Transmission}
{23801}{}{A holotape recording of an audio transmission.}
{23900}{}{Brotherhood Armor}
{23901}{}{A superior version of Armadura de combate. The Brotherhood of Steel have made many improvements over the standard version.}
{24000}{}{Tesla Armor}
{24001}{}{This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks.}
{24100}{}{.223 Pistol}
{24101}{}{A .223 rifle modified and cut down to a pistol. This is a one-of-a-kind firearm, obviously made with love and skill. Min ST: 5.}
{24200}{}{Combat Espingarda}
{24201}{}{A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability. Min ST: 5.}
{24300}{}{Maconha}
{24301}{}{A finely crafted clay pot.}
{24400}{}{Maconha}
{24401}{}{A finely crafted clay pot.}
{24500}{}{Peito}
{24501}{}{A wooden chest.}
{24600}{}{Estante}
{24601}{}{A wood shelf with miscellaneous items.}
{24700}{}{Estante}
{24701}{}{A wood shelf with miscellaneous items.}
{24800}{}{Maconha}
{24801}{}{A finely crafted clay pot.}
{24900}{}{Maconha}
{24901}{}{A finely crafted clay pot.}
{25000}{}{Ossos}
{25001}{}{A pile of human bones.}
{25100}{}{Anna's Ossos}
{25101}{}{These bones seem unsettled.}
{25200}{}{Anna's Gold Locket}
{25201}{}{This well-worn golden locket opens to reveal a charming picture.}
{25300}{}{Fuel Cell Controller}
{25301}{}{This chip controls the flow of power into a car's electric engines. Many drivers quickly burnt out this chip through frequent rapid acceleration. Still a valuable part to have-- if you only had a car to install it in.}
{25400}{}{Fuel Cell Regulator}
{25401}{}{Some car-owners installed this regulator, that doubles your car's mileage between charges, but most drivers didn't care how much juice their cars consumed, after all, power's cheap and plentiful so why worry.}
{25500}{}{Day Pass}
{25501}{}{This slightly crumpled piece of paper grants you access to all areas of Vault City, except the Vault itself, during daylight hours only.}
{25600}{}{False Citizenship Papers}
{25601}{}{This is a set of false Citizenship Papers. They look authentic enough, but you doubt they could pass a serious inspection.}
{25700}{}{Cornelius' Gold Assistir}
{25701}{}{This is an ancient time-piece known as a pocket watch. Time ran out for this keepsake, many long years ago.}
{25800}{}{Hydroelectric Part}
{25801}{}{This is a Hydroelectric Magnetosphere Regulator.}
{25900}{}{Jato}
{25901}{}{Jato is a powerful metamphetamine that stimulates the central nervous system. The initial euphoric rush rarely lasts more than a few minutes, but during that time, the user is filled with a rush of energy & strength.}
{26000}{}{Jato Antídoto}
{26001}{}{This antidote cures the reliant effects of Jato.}
{26100}{}{Jonny's BB Gun}
{26101}{}{A Red Ryder BB gun with the name 'Jonny' scratched on the stock. Min ST: 3.}
{26200}{}{Rubber Boots}
{26201}{}{An old pair of sturdy rubber work boots. They look durable enough to keep out sludge, at least for a while.}
{26300}{}{Slag Message}
{26301}{}{This is a message from the leader of the Slags to the townspeople of Modoc.}
{26400}{}{Smith's Cool Item}
{26401}{}{LONG DESCRIPTION HERE.}
{26500}{}{Combat Jaqueta de couro}
{26501}{}{This heavily padded leather jacket is unusual in that it has two sleeves. You'll definitely make a fashion statement whenever, and wherever, you rumble.}
{26600}{}{Vic's Rádio}
{26601}{}{This hand-held radio doesn't work but it looks as though it's still in pretty good condition. Some of its parts could probably be salvaged for use in other radios.}
{26700}{}{Vic's Frasco de água}
{26701}{}{This relic of the Vault was probably used to contain some sacred sacrament. The Holy number 13 is emblazoned on the side of this precious link to your people's past, and hopeful future.}
{26800}{}{H&K CAWS}
{26801}{}{The CAWS, short for Close Assault Weapons System, shotgun is a useful tool for close-range combat. The bullpup layout gives the weapon a short, easily handleable, length while still retaining enough barrel length for its high velocity shells. Min ST: 6.}
{26900}{}{Robot Parts}
{26901}{}{A pile of damaged robot parts.}
{27000}{}{Robo Lançador de foguetes}
{27001}{}{Only used by rocket equipped robots.}
{27100}{}{Broc Flor}
{27101}{}{The plentiful flower that forms the base for the powder of healing.}
{27200}{}{Xander Root}
{27201}{}{The rare root that gives healing properties to the powder of healing.}
{27300}{}{Healing Powder}
{27301}{}{A very powerful healing magic- though it will bring the feeling of sleep to your head.}
{27400}{}{Robo Rochaet Ammo}
{27401}{}{Only used by rocket equipped robots.}
{27500}{}{Trophy of Recognition}
{27501}{}{A solid gold trophy with the inscription "To: Dave, From: DC's, For: Being a Special Person."}
{27600}{}{Gecko Pelt}
{27601}{}{This is the dried and cured hide of a Gecko.}
{27700}{}{Golden Gecko Pelt}
{27701}{}{This is the dried and cured hide of a Golden Gecko.}
{27800}{}{pedra}
{27801}{}{A stone used to sharpen weapons.}
{27900}{}{Neural Interface}
{27901}{}{It appears to be a set of electrodes built into a head unit with a standard computer interface plug.}
{28000}{}{Sharpened Lança}
{28001}{}{A razor tipped polearm. The shaft is wooden, and the tip is sharpened steel. Min ST: 4.}
{28100}{}{Dixon's Eye}
{28101}{}{A small jar containing a human eye suspended in some kind of liquid. The label says Corporal Dixon.}
{28200}{}{Clifton's Eye}
{28201}{}{A small jar containing a human eye suspended in some kind of liquid. The label says General Clifton.}
{28300}{}{Tommy Gun}
{28301}{}{This Thompson M1928 submachine gun is a sinister looking weapon; every time you hold it, you have an urge to put on a fedora hat and crack your knuckles. The Thompson is well-fed by a large 50 round drum magazine. Min ST: 6.}
{28400}{}{Meat Jerky}
{28401}{}{These smoked and dried chunks of beast-flesh remain chewy-licious and even somewhat nutritious for years, and years, and years....}
{28500}{}{Radscorpion Limbs}
{28501}{}{These Radscorpion pincers are hollowed out and have a strap with a broken buckle at the end.}
{28600}{}{Lenha}
{28601}{}{A pile of firewood and kindling.}
{28700}{}{Scoped Rifle de caça}
{28701}{}{Nothing's better than seeing that surprised look on your target's face. The Loophole x20 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for. Min ST: 5.}
{28800}{}{Car Fuel Cell}
{28801}{}{A car fuel cell.}
{28900}{}{Pá}
{28901}{}{This is a shovel for digging ditches and stuff.}
{29000}{}{Robo Melee Weapon 1}
{29001}{}{For Floating Eye Robot. Does Electrical Damage.}
{29100}{}{Robo Melee Weapon 2}
{29101}{}{For Floating Eye Robot. Does Electrical damage.}
{29200}{}{Caixaing Gloves}
{29201}{}{A pair of boxing gloves that smell faintly of sweat. They look like they have seen a lot of use: many old blood stains still remain.}
{29300}{}{Plated Caixaing Gloves}
{29301}{}{Someone has "accidentally" slipped metal plates into these boxing gloves. It could technically be considered cheating, but you prefer to think of it as an increased opportunity to dispense bone-crunching damage.}
{29400}{}{Vault 13 Holodisk}
{29401}{}{A holodisk which supposedly has the location of Vault 13.}
{29500}{}{Cheezy Poofs}
{29501}{}{A box of cheese flavored puffs. They are extremely good.}
{29600}{}{HK P90c}
{29601}{}{The Heckler & Koch P90c was just coming into use at the time of the war. The weapon's bullpup layout, and compact design, make it easy to control. The durable P90c is prized for its reliability, and high firepower in a ruggedly-compact package. Min ST: 4.}
{29700}{}{Metal Pole}
{29701}{}{It's a long metal pole. What did you expect?}
{29800}{}{Trapper Town Chave}
{29801}{}{A standard key.}
{29900}{}{Pipe Rifle}
{29901}{}{This is a hand-made single shot rifle. Min ST: 5.}
{30000}{}{Zip Gun}
{30001}{}{A handmade single shot pistol. Min ST: 4.}
{30100}{}{Prancheta}
{30101}{}{This is a clipboard with the coolant report.}
{30200}{}{Gecko Holodisk}
{30201}{}{The label on this holotape reads: "Gecko Economic Data." It's difficult to interpret most of the technical charts, tables, and formulae here, but the majority of the information seems to highlight the advantages of a Vault City -- Gecko alliance.}
{30300}{}{Reactor Holodisk}
{30301}{}{The label on this holotape reads: "Gecko Reactor Performance Data." This disk contains a string of numbers that mean nothing to you. There sure is a lot of information here and it must be important to someone, somehow.}
{30400}{}{Deck of "Tragic" Cards}
{30401}{}{This is a deck of cards for a collectible card game. Looks like it could be an expensive hobby if you got hooked.}
{30500}{}{Yellow Reactor Chavecard}
{30501}{}{Uma chave de segurança eletrônica, com cores codificadas em amarelo.}
{30600}{}{Red Reactor Chavecard}
{30601}{}{An electronic security key, color coded red.}
{30700}{}{Plasma Transformer}
{30701}{}{This is a Three-step Plasma Transformer.}
{30800}{}{Super Ferramenta Kit}
{30801}{}{An impressive tool set made by "Snap-Off".}
{30900}{}{Talismã}
{30901}{}{A talisman which is worn by followers of The Brain.}
{31000}{}{Gamma Gulp Cerveja}
{31001}{}{A bottle of Gamma Gulp beer. It glows in the dark!}
{31100}{}{Roentgen Rum}
{31101}{}{A bottle of Roentgen rum. It glows in the dark!}
{31200}{}{Part Requisition Form}
{31201}{}{This is a Part Requisition Request form.}
{31300}{}{.44 Magnum Revolver}
{31301}{}{Being that this is the most powerful handgun in the world, and can blow your head clean-off, you've got to ask yourself one question. Do I feel lucky? Well, do ya punk?. Min ST: 5.}
{31400}{}{Condom (Blue Package)}
{31401}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one is ribbed for her pleasure.}
{31500}{}{Condom (Green package)}
{31501}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosphorous green dye #2 and is slathered in spermicidal lubricant for added protection.}
{31600}{}{Condom (Red Package)}
{31601}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosophorous red dye #5 and has a yummy cinnamon bun flavor... or so you heard.}
{31700}{}{Cosmetics Case}
{31701}{}{This is a genuine Mary May brand cosmetics case.}
{31800}{}{Empty hipopótamodermic}
{31801}{}{This is an empty hypodermic.}
{31900}{}{Canivete}
{31901}{}{The blade of this small knife is held by a spring. When a button on the handle is pressed, the blades shoots out with a satisfying "Sssssshk" sound. Min ST: 1.}
{32000}{}{Sharpened Pole}
{32001}{}{A wood pole sharpened at one end. Min ST: 4.}
{32100}{}{Cybernetic Brain}
{32101}{}{A human brain that has been enhanced by the addition of electronic and robotic attachments.}
{32200}{}{Human Brain}
{32201}{}{A typical human brain. Normally they are found in human skulls. Yuck.}
{32300}{}{Chimpanzee Brain}
{32301}{}{A monkey brain. It's soft and squishy.}
{32400}{}{Abnormal Brain}
{32401}{}{Quite possibly a human brain. The color doesn't seem quite right and the left hemisphere of the brain has caved in on itself.}
{32500}{}{Dados}
{32501}{}{A standard pair of gambling dice. It'd be cool to get a fuzzy pair for your car.}
{32600}{}{Loaded Dados}
{32601}{}{A pair of loaded dice. Don't be flashing these around the casino.}
{32700}{}{Easter Egg}
{32701}{}{This is a hard boiled chicken egg painted with colored dyes.}
{32800}{}{Magic 8-Ball}
{32801}{}{This black sphere is some strange precognitive device... a small window on the top seems to be able to predict the future! Pre-war humanity must have been geniuses to invent such a wonder!}
{32900}{}{Mutagenic Serum}
{32901}{}{A strange organic concoction that could possibly reverse the Mutation Factor in humans.}
{33000}{}{Crashed Verti-Bird}
{33001}{}{This is wreakage from a verti-bird. Looks like it crashed here months ago.}
{33100}{}{Cat's Paw Issue #5}
{33101}{}{This is the hard to find Issue 5 of Cat's Paw magazine. The pictures aside, this issue has a wonderful article on energy weapons.}
{33200}{}{M3A1 "Grease Gun" SMG}
{33201}{}{This submachine gun filled National Guard arsenals after the Army replaced it with newer weapons. However, the "Grease Gun" was simple and cheap to manufacture so there are still quite a few still in use. Min ST: 4.}
{33300}{}{Heart Pills}
{33301}{}{These pills are used by people with heart problems.}
{33400}{}{Poção}
{33401}{}{A hypodermic needle full of powerful poison.}
{33500}{}{Moore's Pasta}
{33501}{}{Thomas Moore asked you to take this brahmin hide briefcase to the Bishop family in New Reno. It is securely locked, and you can't seem to open it.}
{33600}{}{Moore's Pasta}
{33601}{}{Thomas Moore asked you to take this brahmin hide briefcase to the Bishop family in New Reno. It is securely locked, and you can't seem to open it.}
{33700}{}{Lynette Holodisk}
{33701}{}{This is the holodisk you got from Lynette.}
{33800}{}{Westin Holodisk}
{33801}{}{This is the holodisk you got from Westin.}
{33900}{}{NCR Spy Holodisk}
{33901}{}{This holodisk contains reports of NCR caravan schedules and security information. It's addressed to Darion and signed "F". With this info, it's easy to see how the raiders have avoided capture.}
{34000}{}{Doctor's Papers}
{34001}{}{A set of very detailed plans for a Cybernetic Canine Guard Unit. With this and the right facilities, a person just might be able to build a robo-dog.}
{34100}{}{Presidential Pass}
{34101}{}{The bearer of this document is Security Clearance A-Prime as authorized by the authority of the President of the New California Republic. It's signed by President Tandi.}
{34200}{}{Ranger Pin}
{34201}{}{This pin says you're an official New California Ranger. Look -- it's got a code wheel and everything!}
{34300}{}{Ranger's Map}
{34301}{}{A map of the surrounding area -- it won't help you much -- but there are code names on it for the Ranger safe houses in the north.}
{34400}{}{Gravesite}
{34500}{}{Gravesite}
{34600}{}{Gravesite}
{34700}{}{Gravesite}
{34800}{}{Advanced Power Armor}
{34801}{}{This powered armor is composed of lightweight metal alloys, reinforced with ceramic castings at key points. The motion-assist servo-motors appear to be high quality models as well.}
{34900}{}{Adv. Power Armor MKII}
{34901}{}{This powered armor appears to be composed of entirely of lightweight ceramic composites rather than the usual combination of metal and ceramic plates. It seems as though it should give even more protection than the standard Advanced Power Armor.}
{35000}{}{Bozar}
{35001}{}{The ultimate refinement of the sniper's art. Although, somewhat finicky and prone to jamming if not kept scrupulously clean, the big weapon's accuracy more than makes up for its extra maintenance requirements. Min ST: 6.}
{35100}{}{FN FAL}
{35101}{}{This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation. Min ST: 5.}
{35200}{}{H&K G11}
{35201}{}{This gun revolutionized assault weapon design. The weapon fires a caseless cartridge consisting of a block of propellant with a bullet buried inside. The resultant weight and space savings allow this weapon to have a very high magazine capacity. Min ST: 5.}
{35300}{}{XL70E3}
{35301}{}{This was an experimental weapon at the time of the war. Manufactured, primarily, from high-strength polymers, the weapon is almost indestructible. It's light, fast firing, accurate, and can be broken down without the use of any tools. Min ST: 5.}
{35400}{}{Pancor Jackhammer}
{35401}{}{The Jackhammer, despite its name, is an easy to control shotgun, even when fired on full automatic. The popular bullpup design, which places the magazine behind the trigger, makes the weapon well balanced & easy to control. Min ST: 5.}
{35500}{}{Light Support Weapon}
{35501}{}{This squad-level support weapon has a bullpup design. The bullpup design makes it difficult to use while lying down. Because of this it was remanded to National Guard units. It, however, earned a reputation as a reliable weapon that packs a lot of punch for its size. Min ST: 6.}
{35600}{}{Computer Voice Module}
{35601}{}{A circuit board with several unidentifiable parts, a microphone, and an inscription that reads "Vault-Tec Voice Recognition Module."}
{35700}{}{.45 Caliber}
{35701}{}{Munição. .45 Caliber.}
{35800}{}{2mm EC}
{35801}{}{Munição.}
{35900}{}{4.7mm Caseless}
{35901}{}{Munição. Caliber: 4.7mm, caseless.}
{36000}{}{9mm}
{36001}{}{Munição. Caliber: 9mm.}
{36100}{}{HN Needler Cartridge}
{36101}{}{Munição. This cartridge appears to be ammo for the HN Needler Pistol. Each 'bullet' is a small hypodermic designed to inject a target with its contents upon impact.}
{36200}{}{HN AP Needler Cartridge}
{36201}{}{Munição. This cartridge appears to be armor-piercing ammo for the HN Needler Pistol. The hypodermic tips are made of a strange alloy and are incredibly sharp.}
{36300}{}{7.62mm}
{36301}{}{Munição. Caliber: 7.62mm.}
{36400}{}{Robot Motivator}
{36401}{}{This is the drive mechanism for a robot.}
{36500}{}{Plant Spike}
{36501}{}{An organic seed-spike that the carnivorous plants spit at potential food or seed carriers.}
{36600}{}{G.E.C.K.}
{36601}{}{The Garden of Eden Creation Kit. This unit is standard equipment for all Vault-Tec vaults. A GECK is the resource for rebuilding civilization after the bomb. Just add water and stir.}
{36700}{}{Ammo Caixa}
{36800}{}{Ammo Caixa}
{36900}{}{Ammo Caixa}
{37000}{}{Ammo Caixa}
{37100}{}{Garra}
{37101}{}{Garra}
{37200}{}{Garra}
{37201}{}{Garra}
{37300}{}{Vault 15 Chavecard}
{37301}{}{An electronic security key, color coded red.}
{37400}{}{Gravesite}
{37500}{}{Gravesite}
{37600}{}{Gravesite}
{37700}{}{Vault 15 Computer Parts}
{37701}{}{Miscellaneous computer parts with various functions. A computer geek's dream.}
{37800}{}{Biscoito}
{37801}{}{A chocolate chip cookie. Yum!}
{37900}{}{Armadura de couro Mark II}
{37901}{}{An enhanced version of the basic leather armor with extra layers of protection. Finely crafted from tanned brahmin hide.}
{38000}{}{Metal Armor Mark II}
{38001}{}{Polished metal plates, finely crafted into a suit of armor.}
{38100}{}{Armadura de combate Mark II}
{38101}{}{Armadura de alta tecnologia, feita de polímeros defensivos avançados.}
{38200}{}{Combustível de lança-chamas MKII}
{38201}{}{This flamethrower fuel uses an advanced super-burn mix.}
{38300}{}{Shiv}
{38301}{}{This home-made knife is as dangerous as it is easily concealed. Its presence can't be detected by others. Min ST: 1.}
{38400}{}{Chave}
{38401}{}{A typical wrench used by mechanics. Min ST: 3.}
{38500}{}{Sawed-Off Espingarda}
{38501}{}{Someone took the time to chop the last few inches off the barrel and stock of this shotgun. Now, the wide spread of this hand-cannon's short-barreled shots makes it perfect for short-range crowd control. Min ST: 4.}
{38600}{}{Louisville Slugger}
{38601}{}{This all-American, hardwood, baseball bat will knock anything right out of the park. Min ST: 4.}
{38700}{}{M60}
{38701}{}{This relatively light machine gun was prized by militaries around for world for its high rate of fire. This reliable, battlefield-proven design, was used on vehicles and for squad level fire-support. Min ST: 7.}
{38800}{}{Needler Pistol}
{38801}{}{You suspect this Bringham needler pistol was once used for scientific field studies. It uses small hard-plastic hypodermic darts as ammo. Min ST: 3.}
{38900}{}{Avenger Minigun}
{38901}{}{Rochawell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality. Min ST: 7.}
{39000}{}{Solar Scorcher}
{39001}{}{Without the sun's rays to charge this weapon's cpacitors this gun can't light a match. However, in full daylight, the experimental photo-electric cells that power the Scorcher allow it to turn almost anything into a crispy critter. Min ST: 3.}
{39100}{}{H&K G11E}
{39101}{}{This gun revolutionized squad level support weapon design. The gun fires a caseless cartridge consisting of a block of propellant with a bullet buried inside. The resultant weight and space savings allow it to have a very high magazine capacity. Min ST: 6.}
{39200}{}{M72 Gauss Rifle}
{39201}{}{The M72 rifle is of German design. It uses an electromagnetic field to propel rounds at tremendous speed... and pierce almost any obstacle. Its range, accuracy and stopping power is almost unparalleled. Min ST: 6.}
{39300}{}{Phazer}
{39301}{}{NEED LONG DESCRIPTION. Min ST: 3.}
{39400}{}{PPK12 Gauss Pistol}
{39401}{}{Praised for its range and stopping power, the PPK12 Gauss Pistol is of German design. The pistol uses an electromagnetic field to propel rounds at tremendous speed and punch through almost any armor. Min ST: 4.}
{39500}{}{Vindicator Minigun}
{39501}{}{The German Rheinmetal AG company created the ultimate minigun. The Vindicator throws over 90,000 caseless shells per minute down its six carbon-polymer barrels. As the pinnacle of Teutonic engineering skill, it is the ultimate hand-held weapon. Min ST: 7.}
{39600}{}{YK32 Pulse Pistol}
{39601}{}{The YK32 is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. Though powerful, the YK32 was never considered a practical weapon due to its inefficient energy usage and bulky design. Min ST: 3.}
{39700}{}{YK42B Pulse Rifle}
{39701}{}{The YK42B is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. It is considered a far superior weapon to the YK32 pistol, having a greater charge capacity and range. Min ST: 3.}
{39800}{}{.44 Magnum (Speed Load)}
{39801}{}{A .44 Magnum Revolver with a speed loader. Min ST: 5.}
{39900}{}{Super Gado Prod}
{39901}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge. Min ST: 4.}
{40000}{}{Improved Flamer}
{40001}{}{A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly. This model has been modified to fire a hotter mixture which causes greater combustibility. Min ST: 6.}
{40100}{}{Laser Rifle (Ext. Cap.)}
{40101}{}{This Wattz 2000 laser rifle has had its recharging system upgraded and a special recycling chip installed that reduces the drain on the micro fusion cell by 50%. Min ST: 6.}
{40200}{}{Magneto-Pistola a laser}
{40201}{}{This Wattz 1000 laser pistol has been upgraded with a magnetic field targeting system that tightens the laser emission, giving this pistol extra penetrating power. Min ST: 3.}
{40300}{}{FN FAL (Night Sight)}
{40301}{}{This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation. This weapon has been equipped with a night sight for greater night accuracy. Min ST: 5.}
{40400}{}{Desert Eagle (Exp. Mag.)}
{40401}{}{An ancient Desert Eagle pistol, in .44 magnum. Interest in late 20th century films made this one of the most popular handguns of all times. This one has been equipped with an expanded magazine for longer fun and games! Min ST: 4.}
{40500}{}{Rifle de assalto (Exp. Mag.)}
{40501}{}{This Rifle de assalto has an extended, military sized, ammunition clip. The expanded magazine capacity makes it more fun than ever to Spray-and-Pray. Min ST: 5.}
{40600}{}{Pistola de plasma (Ext. Cap.)}
{40601}{}{This Glock 86 Pistola de plasma has had its magnetic housing chamber realigned to reduce the drain on its energy cell. Its efficiency has doubled, allowing it to fire more shots before the battery is expended. Min ST: 4.}
{40700}{}{Mega Power Fist}
{40701}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. This one has upgraded power servos for increased strength. Powered by small energy cells. Min ST: 1.}
{40800}{}{Field Medic Kit de primeiros socorros}
{40801}{}{A small kit containing basic emergency medical equipment. Bandages, wraps, antiseptic spray, and more.}
{40900}{}{Paramedics Bolsa}
{40901}{}{This bag contains instruments and chems used by paramedics in the field. The tools contained are specifically designed for high trauma and emergency cases.}
{41000}{}{Expanded Lockpick Set}
{41001}{}{Um conjunto de ferramentas de serralheiro. Inclui todas as escolhas e chaves de tensão necessárias para abrir fechaduras convencionais e travões. This set also includes some special tools for more difficult mechanical locking mechanisms.}
{41100}{}{Electronic Lockpick MKII}
{41101}{}{This is the second generation Wattz Electronics Micromanipulator FingerCoisa electronic lockpick. For defeating electronic locks and security devices. This Mark II version includes updated software and interface tools.}
{41200}{}{Oil Can}
{41201}{}{You see a can of Armor-Go. A space-age, polymer, lubricant for powered armor.}
{41300}{}{Stables ID Badge}
{41301}{}{This is a temporary ID badge. It has a red stripe through it, which seems to indicate that you are a "Stables Researcher."}
{41400}{}{Vault 15 Shack Chave}
{41401}{}{A standard key.}
{41500}{}{Óculos}
{41501}{}{A set of spectacles for eye correction.}
{41600}{}{Empty Jato Canister}
{41601}{}{This empty jet canister was found in Richard Wright's room. It still has traces of Jato inside.}
{41700}{}{Oxygen Tank}
{41701}{}{This is the oxygen tank for Salvatore's breathing apparatus.}
{41800}{}{Poção Tank}
{41801}{}{This tank looks suspiciously like an oxygen tank, but there is a small skull and crossbones symbol etched in the bottom. If you hadn't examined it closely, you wouldn't have seen the symbol.}
{41900}{}{Mine Parts}
{41901}{}{You see a bundle of parts that are clearly labeled "GX-9 Air Purifier". Using your incredible deductive skills, you decide that they are probably parts for a broken air purifier.}
{42000}{}{Morningstar Mine Scrip}
{42001}{}{This is a small chit probably used to pay Morningstar Mine Workers.}
{42100}{}{Holy Hand Grenade}
{42101}{}{A Holy relic of godly might.}
{42200}{}{Excavator Chip}
{42201}{}{This chip appears to be for some sort of large industrial machine. Beneath the dirt and dust, it appears to be in surprisingly good shape.}
{42300}{}{Gold Nugget}
{42301}{}{A nugget of gold.}
{42400}{}{Monument Chunk}
{42401}{}{This is a piece of the disgruntled stone monument you found out in the desert. Although many of your village would no doubt regard it as a sacred relic, somehow you suspect that you have been cheated.}
{42500}{}{Stone Head}
{42501}{}{A huge stone monument.}
{42600}{}{Uranium Ore}
{42601}{}{A chunk of Uranium Ore, unrefined.}
{42700}{}{Flame Breath}
{42800}{}{Medical Supplies}
{42801}{}{A box of assorted medical supplies. Nothing I can make use of though.}
{42900}{}{Gold Tooth}
{42901}{}{This gold tooth used to belong to Jules, but it's yours now.}
{43000}{}{Howitzer Shell}
{43001}{}{A 75mm Howitzer shell. The casing has mostly corroded away, but you can make out these letters. EXP. 9-25-98.}
{43100}{}{Ramirez Caixa, Closed}
{43101}{}{This is the box you received from Big Jesus Mordino to give to Ramirez at the Stables.}
{43200}{}{Ramirez Caixa, Open}
{43201}{}{This is the box you received from Big Jesus Mordino to give to Ramirez at the Stables. It is open, and you have removed the Jato that was inside.}
{43300}{}{Mirrored Shades}
{43301}{}{This is a pair of fashionable and deadly-looking mirrored shades. Just having them in your inventory makes you feel cool.}
{43400}{}{Vagão}
{43401}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43500}{}{Vagão}
{43501}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43600}{}{Deck of Cards}
{43601}{}{A standard set of playing cards.}
{43700}{}{Pack of Marked Cards}
{43701}{}{Every card in this set is a red queen. Must make for some boring games.}
{43800}{}{Temple Chave}
{43801}{}{A key for the Arroyo Temple door.}
{43900}{}{Pocket Lint}
{43901}{}{Some fuzz you found in a pocket.}
{44000}{}{Bio Med Gel}
{44001}{}{A jar of Bio Gel used in the biomedical field.}
{44100}{}{Blondie's Tags para cães}
{44101}{}{These dog tags have the owner's name scratched off and the name "Blondie" scrawled on the back. Beneath the name is the number "11."}
{44200}{}{Angel-Eyes' Tags para cães}
{44201}{}{These dog tags list the owner as "Angel-Eyes." Beneath the name is the number "16."}
{44300}{}{Tuco's Tags para cães}
{44301}{}{These foul-smelling dog tags list the owner as "Tuco Benedicto Pacifico Juan Maria Ramirez," followed by the number "27."}
{44400}{}{Raiders Map}
{44401}{}{This is a crumpled map of pre-war Northern California. Reno and the surrounding caravan trails are outlined in red, and there is a red "X" far to the east of Reno with "Raiders" scrawled beneath it.}
{44500}{}{Sheriff's Badge}
{44501}{}{A Badge worn by the Sheriff of a town.}
{44600}{}{Vertibird Plans}
{44601}{}{A set of plans for building Vertibirds.}
{44700}{}{Bishop's Holodisk}
{44701}{}{This holodisk contains incriminating information on Bishop's secret deal with NCR. Apparently, Bishop hired mercenaries to attack Vault City in the hopes that Vault City would turn to NCR for military aid. This holodisk is audio only and has no text data. Vault City might be interested in this.}
{44800}{}{Account Book}
{44801}{}{This account book lists a series of monthly payments made to the mercenary band from the Bishop Family in New Reno. The payments depend heavily on how much "pressure" the mercenaries put on Vault City. Vault City might be interested in this.}
{44900}{}{Não utilizado}
{44901}{}{Não utilizado}
{45000}{}{Torn Paper 1}
{45001}{}{You see a piece of paper with writing on it. It looks like it's part of a code of some sort. Unfortunately, the code is incomplete. If only you could find all three pieces. You can make out the following: 1. Physics Password KSLJ, 2. Chemistry Password TIU, 3. Biology Password INTL}
{45100}{}{Torn Paper 2}
{45101}{}{You see a piece of paper with writing on it. It looks like it's part of a code of some sort. Unfortunately, the code is incomplete. If only you could find all three pieces. You can make out the following: KJ: Ken-Lee-9, ASPO- Lo-S, VR- Dnky-Pnch-}
{45200}{}{Torn Paper 3}
{45201}{}{You see a piece of paper with writing on it. It looks like it's part of a code of some sort. Unfortunately, the code is incomplete. If only you could find all three pieces. You can make out the following: 7313, hi-S12908, 98790}
{45300}{}{Password Paper}
{45301}{}{This is three pieces of a single page that, when assembled, reveal three passwords. The text reads: 1. Physics Password KSLJKJ: Ken-Lee-97313, 2. Chemistry Password TIUASPO- Lo-Shi-S12908, 3. Biology Password INTLVR- Dnky-Pnch-98790}
{45400}{}{Explosive Switch}
{45401}{}{This toggle switch is the final conponent of an explosive device.}
{45500}{}{Car Trunk}
{45501}{}{The trunk is a great place to store your stuff.}
{45600}{}{Cell Door Chave}
{45601}{}{This key fits the Cell Door in Broken Hills.}
{45700}{}{Hubologist Field Report}
{45701}{}{A field office report for the membership drive in the True Faith.}
{45800}{}{M.B. Holodisk 5}
{45801}{}{The label reads: Message to CHQ- Confidential.}
{45900}{}{M.B. Holodisk 1}
{45901}{}{The label reads: Rádio Transmission log checkpoint 1.}
{46000}{}{M.B. Holodisk 2}
{46001}{}{The label reads: Rádio transmission log checkpoint 2.}
{46100}{}{M.B. Holodisk 3}
{46101}{}{The label reads: Rádio transmission log checkpoint 3.}
{46200}{}{M.B. Holodisk 4}
{46201}{}{The label reads: Rádio transmission log research team.}
{46300}{}{Evacuation Holodisk}
{46301}{}{The label reads: Base evacuation notice.}
{46400}{}{Experiment Holodisk}
{46401}{}{The label reads: Research log.}
{46500}{}{Medical Holodisk}
{46501}{}{The label reads: Medical log.}
{46600}{}{Password Paper}
{46601}{}{A sheet of folded paper with the word "TCHAIKOVSKY" written on it.}
{46700}{}{Jesse's Container}
{46800}{}{Smitty's Meal}
{46801}{}{It's some kind of salad and a sandwich made out of what you think is Brahmin meat covered in a thick dark yellow sauce. There is also a strange pickled green vegetable on the side.}
{46900}{}{Rot Gut}
{46901}{}{A very strong liquor or cleaning fluid, you decide.}
{47000}{}{Ball Gag}
{47001}{}{A questionable sexual device. If you need to ask, you don't want to know.}
{47100}{}{"The Lavender Flor"}
{47101}{}{It appears to be some kind of romance novel written by Dorothy Rixon. The cover has a woman laying on a bed surrounded by a hundred flowers.}
{47200}{}{Hubologist Holodisk}
{47201}{}{This holodisk is labeled "Hubology: The Truth Behind the Lies". It looks like it works with your PIPBoy.}
{47300}{}{Mutated Toe}
{47301}{}{You see your sixth toe. It is a small mutated part of yourself. For some reason, you feel a terrible sense of loss as you look at the tiny amputated toe.}
{47400}{}{Margaridas}
{47401}{}{A flower pot of daisies. Aren't they nice?}
{47500}{}{Não utilizado}
{47501}{}{Não utilizado}
{47600}{}{Enlightened One's Letter}
{47601}{}{A report addressed to AHS-9 in San Francisco. It's really dry reading- tables of oppressive adjustments, expense reports, and other twaddle not worth wasting your time on.}
{47700}{}{Broadcast Holodisk}
{47701}{}{The label reads: "Galaxy News Network."}
{47800}{}{Sierra Mission Holodisk}
{47801}{}{The label reads: "Mission Statement."}
{47900}{}{NavCom Parts}
{47901}{}{These are computer parts that look like they slot into the interior of a machine. The fact that they say "Poseidon Oil" and "Navigational Computer" on them lead you to believe they fit into a Poseidon Oil Navigational Computer.}
{48000}{}{Bonus +1 Agility}
{48100}{}{Bonus +1 Intelligence}
{48200}{}{Bonus +1 Strength}
{48300}{}{Fallout 2 Hintbook}
{48301}{}{Well, THIS would have been good to have at the beginning of the goddamn game.}
{48400}{}{Player's Ear}
{48401}{}{This is your ear. The Masticator bit it off during the fight and spit it on your unconscious body. If you are reading this, it probably means you will be reloading soon. Of course, it is possible this item has some special value.}
{48500}{}{Masticator's Ear}
{48501}{}{This is the Masticator's ear. You bit it off after pummeling him senseless. Congratulations on beating him. He's one of the toughest NPC's in the game, especially when you don't have any weapons or armor.}
{48600}{}{Refined Uranium Ore}
{48601}{}{A chunk of Uranium Ore. This ore seems to have been processed somehow. It seems heavier.}
{48700}{}{Note from Francis}
{48701}{}{"Zaius, Marcus isn't doing anything about that mutant-hater Jacob and his damned conspirators. First they disable the air purifier... and then what? I found their secret meeting tunnels. I figure a body or two down there could implicate Jacob. If you want in, let me know. And burn the damn note this time!" -Signed, Francis.}
{48800}{}{K-9 Motivator}
{48801}{}{This is the drive mechanism for a K-9 series robot.}
{48900}{}{Special Caixaer Weapon}
{49000}{}{NCR History Holodisk}
{49001}{}{The label reads: "History of NCR."}
{49100}{}{Mr. Nixon Doll}
{49101}{}{You see a small doll with a big red nose. For some reason, you don't trust this seemingly-innocent child's toy.}
{49200}{}{Tanker Fob}
{49201}{}{An encoded passkey that provides access to high security areas.}
{49300}{}{Teachings Holodisk}
{49301}{}{The label reads: "Hubologist Teachings."}
{49400}{}{Kokoweef Mine Scrip}
{49401}{}{This is a small chit probably used to pay Kokoweef Mine Workers.}
{49500}{}{Presidential Access Chave}
{49501}{}{This access key has what looks like the presidential seal on it. It appears as though it's used to gain Presidential level access to computers.}
{49600}{}{Caixaing Gloves}
{49601}{}{A pair of boxing gloves that smell faintly of sweat. They look like they have seen a lot of use: many old blood stains still remain.}
{49700}{}{Plated Caixaing Gloves}
{49701}{}{Someone has "accidentally" slipped metal plates into these boxing gloves. It could technically be considered cheating, but you prefer to think of it as an increased opportunity to dispense bone-crunching damage.}
{49800}{}{Dual Plasma Cannon}
{49801}{}{Only use for Gun Turret critter.}
{49900}{}{Pip Boy Lingual Enhancer}
{49901}{}{This Pip Boy lingual enhancer consists of a storage holodisk, a microfilament cord, headgear, and an optical sensor that is placed over the user's right eye. When used, an optical flash transmits an entire dictionary into the user's memory, permanently improving the user's speech skills.}
{50000}{}{FN FAL HPFA}
{50100}{}{Wall Safe}
{50200}{}{Floor Safe}
{50300}{}{Blue Memory Module}
{50301}{}{A read only computer memory module containing medical information. This module details charisma enhancements.}
{50400}{}{Green Memory Module}
{50401}{}{A read only computer memory module containing medical information. This module details perception enhancements.}
{50500}{}{Red Memory Module}
{50501}{}{A read only computer memory module containing medical information. This module details strength enhancements.}
{50600}{}{Yellow Memory Module}
{50601}{}{A read only computer memory module containing medical information. This module details intelligence enhancements.}
{50700}{}{Decomposing Body}
{50701}{}{This is a partially decomposed body of a humanoid creature.}
{50800}{}{Rubber Doll}
{50801}{}{An inflatable rubber sex doll. This model is called "Tandi".}
{50900}{}{Damaged Rubber Doll}
{50901}{}{This inflatable rubber sex doll has a torn seam. It's obviously been well used.}
{51000}{}{Pool Mesa}
{51100}{}{Pool Mesa}
{51200}{}{Pool Mesa}
{51300}{}{Pool Mesa}
{51400}{}{Pool Mesa}
{51500}{}{Pool Mesa}
{51600}{}{Pip Boy Medical Enhancer}
{51601}{}{This Pip Boy medical enhancer consists of a storage holodisk, microfilament cord, headgear, and an optical sensor that is placed over the user's left eye. When used, an optical flash transmits a dictionary of physician skills and know-how into the user's memory, permanently improving the user's doctor skill.}
{51700}{}{"Little Jesus"}
{51701}{}{This wicked looking blade once belonged to Lil' Jesus Mordino. It has numerous nicks and cuts along its surface, but its edge is razor sharp. On its handle is carved "Little Jesus."}
{51800}{}{Dual Minigun}
{51801}{}{Only use for Auto-Cannon critter.}
{51900}{}{Bottle Caps}
{51901}{}{These are worthless bottle caps. You've heard that at one time they were used as money, though you suspect its only a story.}
{52000}{}{Heavy Dual Minigun}
{52001}{}{Only use for Auto-Cannon Critter.}
{52100}{}{Poor Caixa}
{52101}{}{A small box used to collect money for the poor.}
{52200}{}{Wakizashi Blade}
{52201}{}{A short finely crafted knife. The tip seems to be designed to pierce armor.}
{52300}{}{Survey Map}
{52301}{}{It looks like a geological survey map of the Bay area.}
{52400}{}{Bridgekeeper's Robes}
{52401}{}{This smelly, filthy garment must be made out of some special fabric in order to have withstood the foulness of the bridgekeeper's body. Oddly enough, it has plasma burns and scorch marks all over it, as if these weapons were used against it... to no effect. You have NO idea why it's purple.}
{52500}{}{hipopótamo}
{52501}{}{A medical injection instrument of some kind. It looks very high tech. You don't know what it's filled with but it appears to have only one dose left.}
{52600}{}{Dead Redshirt}
{52601}{}{This guy has a weird red uniform you have never seen. It looks like he died from dehydration.}
{52700}{}{Dead Redshirt}
{52701}{}{This guy has a weird red uniform you have never seen. It looks like he died from dehydration.}
{52800}{}{Dead Redshirt}
{52801}{}{This guy has a weird red uniform you have never seen. It looks like he died from dehydration.}
{52900}{}{Mining Machine}
{53000}{}{End Boss Faca}
{53100}{}{End Boss Plasma Gun}
