{100}{}{Barrararil de metal ardente}
{101}{}{O barril contém papel em chamas e outros resíduos inflamados.}
{200}{}{Porta de madeira}
{201}{}{Uma porta, feita de madeira.}
{300}{}{Mesa de madeira}
{301}{}{Uma mesa, feita de madeira.}
{400}{}{Mesa de madeira}
{401}{}{Uma mesa, feita de madeira.}
{500}{}{Barrararil de metal}
{501}{}{Um barril antigo, feito de aço.}
{600}{}{Barrararil de metal}
{601}{}{Um barril antigo, feito de aço.}
{700}{}{Pilha de pneus}
{701}{}{Uma pilha de pneus de borracha antigos. Eles foram vulcanizados e endurecidos, provavelmente devido ao calor.}
{800}{}{Porta de segurança}
{801}{}{Esta porta parece muito segura. Fornece proteção contra elementos do mundo exterior e criaturas perigosas.}
{900}{}{Computador}
{901}{}{Um terminal de computador, conectado a um computador mainframe.}
{1000}{}{Coluna}
{1001}{}{Uma coluna de suporte, fornecendo alívio do estresse para todo o complexo.}
{1100}{}{Computador}
{1101}{}{Um terminal de computador, conectado a um computador mainframe.}
{1200}{}{Computador}
{1201}{}{Um terminal de computador, conectado a um computador mainframe.}
{1300}{}{Monitor}
{1301}{}{Um monitor de tela verde, que mostra vários bits de dados. Alguns bytes ocasionalmente aparecem.}
{1400}{}{Monitor}
{1401}{}{Um monitor de tela verde, que mostra vários bits de dados.}
{1500}{}{Holo Generator}
{1501}{}{Um reprodutor de fita de entretenimento THT em grande escala. Nenhum filme novo foi feito em 80 anos.}
{1600}{}{Telas}
{1601}{}{Uma série de três monitores de exibição, mostrando vários bits de dados.}
{1700}{}{Telas}
{1701}{}{Um conjunto de três monitores de exibição, mostrando vários bits de dados em torno do Vault.}
{1800}{}{Porta}
{1801}{}{Ainda é uma porta depois de um exame mais aprofundado.}
{1900}{}{Porta}
{1901}{}{Ainda é uma porta depois de um exame mais aprofundado.}
{2000}{}{Vent}
{2001}{}{Um respiradouro, fornecendo ar processado e limpo para todo o complexo.}
{2100}{}{Vent}
{2101}{}{Um respiradouro, fornecendo ar processado e limpo para todo o complexo.}
{2200}{}{Vault 13 Porta}
{2201}{}{Uma porta pesada, construída para sobreviver a todos os tipos de dano e trauma.}
{2300}{}{Vault 13 Porta}
{2301}{}{Uma porta pesada, construída para sobreviver a todos os tipos de dano e trauma.}
{2400}{}{Pedestal}
{2401}{}{Um elevador hidráulico, projetado para ajudar a fornecer suporte, energia e linhas de comunicação para a plataforma.}
{2500}{}{Monitor}
{2501}{}{Se você viu um monitor, você os viu todos.}
{2600}{}{Monitor}
{2601}{}{Um monitor de computador, exibindo vários bits de dados.}
{2700}{}{Grating}
{2701}{}{Uma grade de chão.}
{2800}{}{Tubos}
{2801}{}{Alguns tubos. Após um exame mais detalhado, eles ainda são canos.}
{2900}{}{Vent}
{2901}{}{Sistema de ventilação Vault-Tec padrão.}
{3000}{}{Coluna}
{3001}{}{Um sistema de suporte de coluna Vault-Tec padrão.}
{3100}{}{Coluna}
{3101}{}{Um sistema de suporte de coluna Vault-Tec padrão.}
{3200}{}{Vent}
{3201}{}{Sistema de ventilação Vault-Tec padrão.}
{3300}{}{Vent}
{3301}{}{Sistema de ventilação Vault-Tec padrão.}
{3400}{}{Cama}
{3401}{}{Uma cama, parece muito confortável depois do que você dormiu.}
{3500}{}{Cama}
{3501}{}{Uma cama padrão. Parece confortável.}
{3600}{}{Cama}
{3601}{}{Uma cama padrão. Parece confortável.}
{3700}{}{Cama}
{3701}{}{Uma cama padrão. Parece confortável.}
{3800}{}{Elevador}
{3801}{}{Este é um elevador maintanence.}
{3900}{}{Cadeira}
{3901}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{4000}{}{Cadeira}
{4001}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{4100}{}{Cadeira}
{4101}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{4200}{}{Cadeira}
{4201}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{4300}{}{Monitor}
{4301}{}{Um monitor de computador, exibindo vários bits de dados.}
{4400}{}{Monitor}
{4401}{}{Um monitor de computador, exibindo vários bits de dados.}
{4500}{}{Monitor}
{4501}{}{Um monitor de computador, exibindo vários bits de dados.}
{4600}{}{Monitor}
{4601}{}{Um monitor de computador, exibindo vários bits de dados.}
{4700}{}{Monitor}
{4701}{}{Um monitor de computador, exibindo vários bits de dados.}
{4800}{}{Monitor}
{4801}{}{Um monitor de computador, exibindo vários bits de dados.}
{4900}{}{Exit Grid Map Marcador}
{4901}{}{Exit Grid Map Marcador}
{5000}{}{Unidade de processamento de ar}
{5001}{}{Uma APU limpa o ar antigo para fornecer novo ar para o complexo. Este está quebrado.}
{5100}{}{Cadeira}
{5101}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{5200}{}{Cadeira}
{5201}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{5300}{}{Cadeira}
{5301}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{5400}{}{Cadeira}
{5401}{}{É uma cadeira. Muito ruim você não tem tempo para se sentar e relaxar.}
{5500}{}{VDU}
{5501}{}{Esta unidade de exibição de vídeo possui uma variedade de monitores de computador e outras telas. Parece muito, muito ocupado.}
{5600}{}{VDU}
{5601}{}{Esta unidade de exibição de vídeo possui uma variedade de monitores de computador e outras telas. Parece muito, muito ocupado.}
{5700}{}{Cadeira}
{5701}{}{É uma cadeira. Parece poderoso confortável.}
{5800}{}{Cadeira}
{5801}{}{É uma cadeira. Parece poderoso confortável.}
{5900}{}{Cadeira}
{5901}{}{É uma cadeira. Parece poderoso confortável.}
{6000}{}{Cadeira}
{6001}{}{É uma cadeira. Parece poderoso confortável.}
{6100}{}{Mesa}
{6101}{}{É uma mesa. Antes das mesas, as pessoas tinham que manter suas coisas no chão.}
{6200}{}{Mesa}
{6201}{}{É definitivamente uma mesa.}
{6300}{}{Tumbleweed}
{6301}{}{É uma baguela. Claro, você nunca viu uma verdadeira tumbaweed antes. É melhor você observar de perto.}
{6400}{}{Cacto}
{6401}{}{Você não vê nada especial sobre esse cacto.}
{6500}{}{Cacto}
{6501}{}{Você não vê nada importante sobre este cacto.}
{6600}{}{Árvore}
{6601}{}{Uma árvore morta. Nada dá certo aqui.}
{6700}{}{Bloqueio Secreto Hex}
{6701}{}{Se você pode ver isso, culpe o designer técnico.}
{6800}{}{Escadas}
{6801}{}{Um conjunto de escadas.}
{6900}{}{Estalagmite}
{6901}{}{Uma extensão natural do piso da rocha.}
{7000}{}{Estalagmite}
{7001}{}{Uma extensão natural do piso da rocha.}
{7100}{}{Mancha de sangue}
{7101}{}{Não há nada fora do comum com essa mancha sangrenta. Exceto, é claro, que alguém ou alguma coisa morreu aqui.}
{7200}{}{Rocha Coluna}
{7201}{}{Esta espessa coluna de rocha se estende do chão ao teto.}
{7300}{}{Rocha Coluna}
{7301}{}{Esta fina coluna de rocha se estende do chão ao teto.}
{7400}{}{Rochas}
{7401}{}{Você estuda as rochas por um tempo, mas nunca se move.}
{7500}{}{Rochas}
{7501}{}{Você observa atentamente essas rochas, caso elas se movam para atacar você.}
{7600}{}{Piso de parede do carro}
{7601}{}{REMOVIDO}
{7700}{}{Portão}
{7701}{}{Um portão de madeira.}
{7800}{}{Rochas}
{7801}{}{Uma grande pilha de rochas. Parecem indígenas nesta região.}
{7900}{}{Rochas}
{7901}{}{Uma pequena pilha de pedras.}
{8000}{}{Rochas}
{8001}{}{Uma pequena pilha de pedras.}
{8100}{}{Rochas}
{8101}{}{Uma grande pilha de rochas.}
{8200}{}{Ossos}
{8201}{}{Uma grande pilha de ossos de animais branqueados. Pelo menos, você acha que todos os ossos são animais ...}
{8300}{}{Ossos}
{8301}{}{Uma grande pilha de ossos de animais branqueados. Pelo menos, você acha que todos os ossos são animais ...}
{8400}{}{Ossos}
{8401}{}{Uma pilha muito grande de ossos branqueados. Você não pode determinar as espécies dos criaturas mortas.}
{8500}{}{Ossos}
{8501}{}{Você acha que estes podem ser ossos de canguru Horned, mas você não pode ter certeza. Eles estão muito degradados para fazer uma determinação final.}
{8600}{}{Ossos}
{8601}{}{Você vê os ossos de uma grande vaca de duas cabeças.}
{8700}{}{Portão}
{8701}{}{Um portão de madeira. It opens, and closes, and opens, and closes, and...}
{8800}{}{Portão}
{8801}{}{Um portão de madeira.}
{8900}{}{Portão}
{8901}{}{Um portão de madeira.}
{9000}{}{Rochas}
{9001}{}{Uma grande pilha de pedras. Eles parecem perigosos apenas sentados lá.}
{9100}{}{Rochas}
{9101}{}{Uma grande pilha de rochas. If you look closely, you can see the faces of little old men in the sides of the stones.}
{9200}{}{Rochas}
{9201}{}{Rochas, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{Rochas}
{9301}{}{Uma pequena pilha de pedras.}
{9400}{}{Barrara}
{9401}{}{Este bar possui uma coleção de bebidas preparadas para derramar.}
{9500}{}{Cadeira}
{9501}{}{Uma cadeira velha podre feita de um antigo assento de carro.}
{9600}{}{Cadeira}
{9601}{}{Uma velha cadeira cheia de cheiro que costumava ser para um assento de carro. As molas perderam a sua primavera.}
{9700}{}{Cadeira}
{9701}{}{Uma cadeira velha e apimentada sentada em tijolos para apoio. Parece muito desconfortável.}
{9800}{}{Cadeira}
{9801}{}{Uma cadeira velha e apimentada sentada em tijolos para apoio. Parece muito desconfortável.}
{9900}{}{Sofá}
{9901}{}{Um dispositivo sentado de aparência muito desconfortável, às vezes conhecido como um sofá.}
{10000}{}{Sofá}
{10001}{}{Um dispositivo sentado de aparência muito desconfortável, às vezes conhecido como um sofá.}
{10100}{}{Pneu}
{10101}{}{Um pneu de borracha velho sentado no meio de algumas ervas daninhas.}
{10200}{}{Esfregar}
{10201}{}{Alguma espécie de erva daninha do deserto.}
{10300}{}{Esfregar}
{10301}{}{Alguma espécie de erva daninha do deserto.}
{10400}{}{Esfregar}
{10401}{}{Alguma espécie de erva daninha do deserto.}
{10500}{}{Esfregar}
{10501}{}{Alguma espécie de erva daninha do deserto.}
{10600}{}{Lixo}
{10601}{}{É uma porta de carro enferrujada encostada a um barril de metal enferrujado. Está ocorrendo muita ferrugem.}
{10700}{}{Lixo}
{10701}{}{Um banheiro quebrado, meio enterrado na areia. A vida é um pisser, então você morre.}
{10800}{}{Ervas daninhas}
{10801}{}{Alguma espécie de esfregaço do deserto. Se estava crescendo no passado recente, não é agora.}
{10900}{}{Lixo}
{10901}{}{Um pneu de carro, enterrado na areia. Alguns pequenos pedaços de madeira são empilhados ao redor.}
{11000}{}{Rochas}
{11001}{}{Em um exame mais atento, você acha que estes podem ser realmente pedaços de madeira petrificada.}
{11100}{}{Sujeira}
{11101}{}{Uma pequena pilha de sujeira, com uma erva mortal que sai fora dela.}
{11200}{}{Sujeira}
{11201}{}{Uma pequena pilha de sujeira.}
{11300}{}{Sujeira}
{11301}{}{Uma pequena pilha de sujeira.}
{11400}{}{Sujeira}
{11401}{}{Uma pequena pilha de sujeira.}
{11500}{}{Erva daninha}
{11501}{}{Uma pequena pilha de sujeira, com uma erva seca que sai fora dela.}
{11600}{}{Lixo}
{11601}{}{Um pedaço torcido de metal enferrujado.}
{11700}{}{Lixo}
{11701}{}{Alguns pedaços de madeira quebrados.}
{11800}{}{Lixo}
{11801}{}{Uma pequena pilha de lixo aleatório.}
{11900}{}{Sujeira}
{11901}{}{Uma pequena pilha de sujeira.}
{12000}{}{Sujeira}
{12001}{}{Uma pequena pilha de sujeira.}
{12100}{}{Sujeira}
{12101}{}{Uma pequena pilha de sujeira.}
{12200}{}{Sujeira}
{12201}{}{Uma pequena pilha de sujeira.}
{12300}{}{Sujeira}
{12301}{}{Uma pequena pilha de sujeira.}
{12400}{}{Sujeira}
{12401}{}{Uma pequena pilha de sujeira.}
{12500}{}{Erva daninha}
{12501}{}{Uma erva genérica do deserto.}
{12600}{}{Erva daninha}
{12601}{}{Uma erva genérica do deserto.}
{12700}{}{Erva daninha}
{12701}{}{Uma erva genérica do deserto.}
{12800}{}{Blocking Hex (NoLuz)}
{12900}{}{parede}
{13000}{}{parede}
{13100}{}{parede}
{13200}{}{parede}
{13300}{}{parede}
{13400}{}{parede}
{13500}{}{Drenar}
{13501}{}{Existe algum tipo de classificação, cheiro desagradável proveniente deste dreno de esgoto. Depois de alguns momentos, não cheira tão mal.}
{13600}{}{Drenar}
{13601}{}{Você dificilmente consegue algum movimento atrás da grelha que cobre esse dreno. Você pode ver pequenos olhos vermelhos olhando para você. Olhos de rato.}
{13700}{}{Drenar}
{13701}{}{Surgem os dutos da água gurgling deste dreno. Também é um fedor realmente vil.}
{13800}{}{Drenar}
{13801}{}{Os sons da água de Gurgling vêm de além deste dreno. O mesmo acontece com um cheiro muito vil.}
{13900}{}{Escada}
{13901}{}{É uma escada antiga e bastante deserta. Parece que ele apenas apoiará seu peso.}
{14000}{}{Alcance de esgoto}
{14001}{}{Parece um buraco de acesso para o sistema de esgoto.}
{14100}{}{Fonte de luz}
{14200}{}{Porta}
{14201}{}{Isso parece uma porta de Vault padrão que foi danificada, talvez queimada. Ainda é funcional, no entanto.}
{14300}{}{Porta}
{14301}{}{Isso parece uma porta de Vault padrão que foi danificada, talvez queimada. Ainda é funcional, no entanto.}
{14400}{}{Tampa}
{14401}{}{Uma pesada capa de furo. Parece que está em boa forma, e que foi recentemente movido.}
{14500}{}{Buraco}
{14501}{}{Um grande buraco foi explodido por esta porta.}
{14600}{}{Buraco}
{14601}{}{Um grande buraco foi explodido por esta porta.}
{14700}{}{Vidro a prova de balas}
{14701}{}{Vidro completamente inquebrável. Nem tente.}
{14800}{}{Vidro a prova de balas}
{14801}{}{Vidro completamente inquebrável. Nem tente.}
{14900}{}{Vidro a prova de balas}
{14901}{}{Vidro completamente inquebrável. Nem tente.}
{15000}{}{Vidro a prova de balas}
{15001}{}{Vidro completamente inquebrável. Nem tente.}
{15100}{}{Porta}
{15101}{}{Esta porta é uma peça de construção de alta tecnologia. Ele abre dilatando enquanto gira as três peças que compõem a porta.}
{15200}{}{Porta}
{15201}{}{Esta porta é uma peça de construção de alta tecnologia. Ele abre dilatando enquanto gira as três peças que compõem a porta.}
{15300}{}{Porta}
{15301}{}{Esta porta está marcada com o símbolo da Irmandade do Aço.}
{15400}{}{Porta}
{15401}{}{Esta porta está marcada com o símbolo da Irmandade do Aço.}
{15500}{}{Elevador}
{15501}{}{Este é o interior de um elevador da Fraternidade. É limpo.}
{15600}{}{Elevador}
{15601}{}{Este é o interior de um elevador da Fraternidade. É limpo.}
{15700}{}{Marcador}
{15701}{}{Este é o símbolo da Irmandade do Aço. Este marcador diz ao pouso que esta é a sua área e para sair imediatamente.}
{15800}{}{Monitor}
{15801}{}{Você vê um monitor de computador. É feito a partir da tecnologia da Fraternidade.}
{15900}{}{Monitor}
{15901}{}{Você vê um monitor de computador. É feito a partir da tecnologia da Fraternidade.}
{16000}{}{Computador}
{16001}{}{Este é um banco de dados de memória do computador. É, obviamente, a tecnologia Brotherhood.}
{16100}{}{Computador}
{16101}{}{Este é um banco de dados de memória do computador. É, obviamente, a tecnologia Brotherhood.}
{16200}{}{Computador}
{16201}{}{Um computador de alta tecnologia, usando modernos dispositivos de armazenamento de carretel a bobina em vez dos antiquados cartões de perfuração.}
{16300}{}{Computador}
{16301}{}{Um computador de alta tecnologia, usando modernos dispositivos de armazenamento de carretel a bobina em vez dos antiquados cartões de perfuração.}
{16400}{}{Monitor}
{16401}{}{Você vê um monitor de computador. É feito a partir da tecnologia da Fraternidade.}
{16500}{}{Monitor}
{16501}{}{Você vê um monitor de computador. É feito a partir da tecnologia da Fraternidade.}
{16600}{}{Fio}
{16601}{}{Alguma tipo de fiação de computador.}
{16700}{}{Fio}
{16701}{}{Alguma tipo de fiação de computador.}
{16800}{}{Fio}
{16801}{}{Alguma tipo de fiação de computador.}
{16900}{}{Coluna}
{16901}{}{Uma coluna de suporte.}
{17000}{}{Coluna}
{17001}{}{Uma coluna de suporte.}
{17100}{}{Porta Entry Computador}
{17101}{}{Este computador controla a grande porta do abóbada. Você deve inserir um código de acesso específico para o computador funcionar.}
{17200}{}{Sinal de casino}
{17201}{}{Parece um anúncio para o Gizmo's Casino.}
{17300}{}{Vault 13 Outer Porta}
{17301}{}{Esta grande porta é o elo entre o cofre e o mundo exterior.}
{17400}{}{Vault 13 Outer Porta}
{17401}{}{Esta grande porta é o elo entre o cofre e o mundo exterior.}
{17500}{}{Sinal de casino}
{17501}{}{Esta parte do sinal contém um motor elétrico que está girando lentamente o sinal de néon em anexo.}
{17600}{}{Seta para baixo}
{17700}{}{Seta para cima}
{17800}{}{Caixa}
{17900}{}{Caixa}
{18000}{}{Caixa}
{18100}{}{Elevador Top}
{18101}{}{Você está olhando uma porção de um elevador.}
{18200}{}{Computador Console}
{18201}{}{Este é um terminal estúpido, ligado por cabo a um computador grande. É a tecnologia da Fraternidade.}
{18300}{}{Computador Console}
{18301}{}{Este é um terminal estúpido, ligado por cabo a um computador grande. É a tecnologia da Fraternidade.}
{18400}{}{Emblemaaa}
{18401}{}{O símbolo da Irmandade. As engrenagens representam seu conhecimento de engenharia, a espada é sua vontade de se defender e as asas são a esperança edificante.}
{18500}{}{Emblemaaa}
{18501}{}{O símbolo da Irmandade. As engrenagens representam seu conhecimento de engenharia, a espada é sua vontade de se defender e as asas são a esperança edificante.}
{18600}{}{Sinal de nível 'One'}
{18601}{}{Você acha que isso pode significar que você está no nível um da Irmandade.}
{18700}{}{Sinal de nível 'dois'}
{18701}{}{Você está no nível dois da Irmandade.}
{18800}{}{Sinal de nível 'três'}
{18801}{}{Isso deve significar que você está no nível três da Irmandade.}
{18900}{}{Sinal de nível 'quatro'}
{18901}{}{Você deve estar no nível quatro da Irmandade.}
{19000}{}{Bunk Cama}
{19001}{}{Um beliche de estilo militar. Parece muito desconfortável. Também parece que você poderia saltar um quarto de estas folhas.}
{19100}{}{Bunk Cama}
{19101}{}{Um beliche de estilo militar. Parece muito desconfortável. Também parece que você poderia saltar um quarto de estas folhas.}
{19200}{}{Bunk Cama}
{19201}{}{Um beliche de estilo militar. Parece muito desconfortável. Também parece que você poderia saltar um quarto de estas folhas.}
{19300}{}{Caixa}
{19400}{}{Máquina Nuka-Cola}
{19401}{}{A publicidade no lado desta máquina promove o seu refrigerante popular.}
{19500}{}{parede}
{19600}{}{Alçapão}
{19601}{}{Parece um trapalhão perfeitamente bom.}
{19700}{}{Bueiro}
{19701}{}{A escada neste orifício conduz à escuridão abaixo. Ahhh, assustador.}
{19800}{}{Altar}
{19801}{}{Este é um altar.}
{19900}{}{Púlpito}
{19901}{}{As pessoas ficam por trás disso e falam. Parece que tem um pequeno lugar para manter um discurso preparado.}
{20000}{}{Pew}
{20001}{}{Isso parece exatamente o que você esperaria. Nada de especial sobre este banco.}
{20100}{}{Placapost}
{20101}{}{O sinal nesta publicação parece um pouco enferrujado.}
{20200}{}{Placapost}
{20201}{}{O sinal nesta publicação parece um pouco enferrujado.}
{20300}{}{Placapost}
{20301}{}{O sinal nesta publicação parece um pouco enferrujado.}
{20400}{}{Placapost}
{20401}{}{O sinal nesta publicação parece um pouco enferrujado.}
{20500}{}{Placapost}
{20501}{}{O sinal nesta publicação parece um pouco enferrujado.}
{20600}{}{Colchão velho}
{20601}{}{Um colchão antigo e espancado. Você acha que você vê algum tipo de pequena bicho de insetos como infestante.}
{20700}{}{Colchão velho}
{20701}{}{Mesmo que você estivesse a dormir sozinho, não iria dormir sozinho.}
{20800}{}{Cama}
{20801}{}{Uma cama de mudança de mão. O material foi eliminado de alguma outra fonte.}
{20900}{}{Cama}
{20901}{}{Uma cama de mudança de mão. O material foi eliminado de alguma outra fonte.}
{21000}{}{Cama}
{21001}{}{Esta cama já viu dias melhores (e provavelmente noites também).}
{21100}{}{Cama}
{21101}{}{Em um exame mais atento, você determina que as folhas não foram alteradas em muito, muito tempo.}
{21200}{}{Cama}
{21201}{}{Há algumas manchas de origem duvidosa sobre este dispositivo de dormir bem gasto.}
{21300}{}{Cama}
{21301}{}{Esta cama tem visto muito uso e desgaste. Algo deve ter rastejado entre os colchões e morreu também.}
{21400}{}{Estante}
{21500}{}{Estante}
{21600}{}{Estante}
{21700}{}{Estante}
{21800}{}{Estante}
{21900}{}{Estante}
{22000}{}{Caixas}
{22001}{}{Estas caixas de madeira estão caindo do clima.}
{22100}{}{Caixas}
{22101}{}{Você não encontra nenhum valor digno de menção sobre essas caixas de madeira.}
{22200}{}{Caixas}
{22201}{}{Você tem muito tempo em suas mãos para estar olhando atentamente sobre esse lixo rotrado.}
{22300}{}{Caixas}
{22301}{}{Estas caixas de madeira estão caindo do clima.}
{22400}{}{Carrorororororororororo}
{22401}{}{Este automóvel tem uma forma terrível. Você não consegue pensar em uma maneira de restaurá-lo.}
{22500}{}{Carrorororororororororo}
{22501}{}{Este fragmento enferrujado de sucata não pode ser restaurado.}
{22600}{}{Carrorororororororororo}
{22601}{}{Você determina que este veículo nunca mais dirigirá. Mesmo.}
{22700}{}{Carrorororororororororo}
{22701}{}{Não há nenhuma maneira de que esse aspirante a junkyard dirija novamente.}
{22800}{}{Carrorororororororororo}
{22801}{}{Se o Mecânico do Ano de repente apareceu ao seu lado, ambos não conseguiram consertar esta pilha enferrujada.}
{22900}{}{Cadeira}
{22901}{}{Uma cadeira confortável.}
{23000}{}{Cadeira}
{23001}{}{Esta cadeira parece ter visto melhores anos.}
{23100}{}{Cadeira}
{23101}{}{Esta cadeira é mofada e grosseira. Como você pode adivinhar, isso também fede.}
{23200}{}{Cadeira}
{23201}{}{Esta cadeira está caindo aos pedaços. Rapidamente.}
{23300}{}{Cadeira}
{23301}{}{Se alguém lhe pagou muito dinheiro, e você poderia usar calças de aço, você pode considerar sentar-se nesta cadeira.}
{23400}{}{Cadeira}
{23401}{}{Isso parece uma cadeira de escritório antiga, ainda em muito boa forma depois de todos esses anos.}
{23500}{}{Cadeira}
{23501}{}{Esta é uma cadeira de escritório antiga. Pode até suportar o peso de uma pessoa.}
{23600}{}{Cadeira}
{23601}{}{Esta cadeira de escritório viu dias melhores. É muito lixo, agora.}
{23700}{}{Cadeira}
{23701}{}{Isso parece uma cadeira que você veria no escritório de um morticien - morto.}
{23800}{}{Escrivaninha}
{23900}{}{Escrivaninha}
{24000}{}{Cômoda}
{24100}{}{Cômoda}
{24200}{}{Cômoda}
{24300}{}{Hidrante}
{24301}{}{Esta é uma boca de incêndio. Sem aspersores de teto do Vault, você pode precisar de um desses para apagar os incêndios.}
{24400}{}{Postarararare de iluminação}
{24401}{}{Esta lâmpada parece que ainda está em condições de funcionamento. Imagine isso, algo que funciona aqui.}
{24500}{}{Postarararare de iluminação}
{24501}{}{Esta lâmpada nunca mais funcionará.}
{24600}{}{Postarararare de iluminação}
{24601}{}{Esta é uma lâmpada de trabalho. À noite, lança uma luz pálida e gentil que não lembra absolutamente nada.}
{24700}{}{Postarararare de iluminação}
{24701}{}{Esta é uma lâmpada quebrada. Não pode ser consertado.}
{24800}{}{Postarararare de iluminação}
{24801}{}{Esta luminária é operacional.}
{24900}{}{Postarararare de iluminação}
{24901}{}{A luz neste poste da lâmpada é destruída além de reparar.}
{25000}{}{Postarararare de iluminação}
{25001}{}{Esta é uma lâmpada funcional.}
{25100}{}{Portão}
{25101}{}{O bloqueio deste portão foi bloqueado e as barras parecem muito resistentes.}
{25200}{}{Lixo}
{25201}{}{Lixo definitivamente inútil, sem dúvida.}
{25300}{}{Lixo}
{25301}{}{Lixo definitivamente inútil, sem dúvida.}
{25400}{}{Lixo}
{25401}{}{Lixo definitivamente inútil, sem dúvida.}
{25500}{}{Lixo}
{25501}{}{Lixo definitivamente inútil, sem dúvida.}
{25600}{}{Lixo}
{25601}{}{Lixo definitivamente inútil, sem dúvida.}
{25700}{}{Caixa de correio}
{25701}{}{A caixa de correio está vazia. Você tem a sensação de ser assim por algum tempo.}
{25800}{}{Porta}
{25801}{}{Uma porta de madeira bem trabalhada, em boas condições.}
{25900}{}{Porta}
{25901}{}{Uma porta de madeira bem trabalhada, em boas condições.}
{26000}{}{Porta}
{26001}{}{Uma porta de madeira bem trabalhada, em boas condições.}
{26100}{}{Porta}
{26101}{}{Uma porta de madeira bem trabalhada, em boas condições.}
{26200}{}{Pew}
{26201}{}{Este banco de madeira cai lentamente.}
{26300}{}{Pew}
{26301}{}{Este banco foi negligenciado e está mostrando sinais de desgaste.}
{26400}{}{Pew}
{26401}{}{Um banco de madeira que sucumbiu aos efeitos da idade e do abuso.}
{26500}{}{Máquina de jornal}
{26501}{}{A máquina do jornal está vazia.}
{26600}{}{Máquina de jornal}
{26601}{}{A máquina do jornal está vazia.}
{26700}{}{Máquina de jornal}
{26701}{}{A máquina do jornal está vazia.}
{26800}{}{Máquina de jornal}
{26801}{}{A máquina do jornal está vazia.}
{26900}{}{Máquina de jornal}
{26901}{}{A máquina do jornal está vazia.}
{27000}{}{Máquina de jornal}
{27001}{}{A máquina do jornal está vazia. It looks like it once held adult magazines.}
{27100}{}{Lixo}
{27101}{}{Um colchão de cama em condições terríveis. Mesmo os ratos não dormem dentro ou sobre ele.}
{27200}{}{Lixo}
{27201}{}{Um colchão de duas camas que tem visto muitos dias melhores do que este.}
{27300}{}{Lixo}
{27301}{}{Uma pilha de madeira podre e resistida. Não vale a pena ponderar, bem, qualquer coisa.}
{27400}{}{Lixo}
{27401}{}{Uma pilha de madeira, com algumas unhas oxidadas e inofensivas embutidas profundamente.}
{27500}{}{Caixas}
{27501}{}{Uma pilha de caixas de papelão antigas. Você não acredita que tenham sobrevivido por muito tempo.}
{27600}{}{Caixas}
{27601}{}{Uma pilha de caixas de papelão antigas.}
{27700}{}{Lixo}
{27701}{}{Algum lixo que você acha que poderia ter sido um colchão de cama antes de ser destruído pelo meio ambiente.}
{27800}{}{Rochas}
{27900}{}{Rochas}
{28000}{}{Rochas}
{28100}{}{Destroços, Pedregulho}
{28101}{}{Uma pequena pilha de pedras e pedras entalhadas. Veja seu passo!}
{28200}{}{Pia}
{28201}{}{Uma pia de porcelana que há muito perdeu a capacidade de funcionar.}
{28300}{}{Pia}
{28301}{}{Uma pia de porcelana quebrada. Há pequena poça de água marrom na bacia, com um rato morto flutuante.}
{28400}{}{Pia}
{28401}{}{Esta pia não é funcional. Você pode dizer isso da grande rachadura no meio.}
{28500}{}{Pia}
{28501}{}{Uma pia de porcelana quebrada. Há pequena poça de água marrom na bacia, com um rato morto flutuante.}
{28600}{}{Sinal de parada}
{28601}{}{Um sinal vermelho com a palavra STOP escrito em grandes letras em bloco.}
{28700}{}{Sinal de parada}
{28701}{}{Um sinal vermelho com a palavra STOP escrito em grandes letras em bloco. The large bullet hole was added after manufacturing.}
{28800}{}{Luz de parada}
{28801}{}{Este é um antigo dispositivo de controle de tráfego de automóveis.}
{28900}{}{Luz de parada}
{28901}{}{Este é um antigo dispositivo de controle de tráfego de automóveis.}
{29000}{}{Luz de parada}
{29001}{}{Este é um antigo dispositivo de controle de tráfego de automóveis.}
{29100}{}{Iluminação pública}
{29101}{}{Esta luz de rua fornece iluminação após a queda da noite, ou em áreas escuras.}
{29200}{}{Iluminação pública}
{29201}{}{Esta luz de rua fornece iluminação após a queda da noite, ou em áreas escuras.}
{29300}{}{Iluminação pública}
{29301}{}{Esta luz de rua fornece iluminação após a queda da noite, ou em áreas escuras.}
{29400}{}{Iluminação pública}
{29401}{}{Esta luz de rua fornece iluminação após a queda da noite, ou em áreas escuras.}
{29500}{}{Iluminação pública}
{29501}{}{Esta luz de rua poderia fornecer iluminação em áreas escuras, se não estivesse completamente quebrada.}
{29600}{}{Iluminação pública}
{29601}{}{Esta luz de rua poderia fornecer iluminação em áreas escuras, se não estivesse completamente quebrada.}
{29700}{}{Iluminação pública}
{29701}{}{Esta luz de rua poderia fornecer iluminação em áreas escuras, se não estivesse completamente quebrada.}
{29800}{}{Placapost}
{29801}{}{Este sinal deve marcar em que rua está, mas as letras desapareceram na obscuridade.}
{29900}{}{Placapost}
{29901}{}{Este sinal deve marcar em que rua está, mas as letras desapareceram na obscuridade.}
{30000}{}{Mesa}
{30001}{}{Uma mesa de madeira, em condição justa a média.}
{30100}{}{Mesa}
{30101}{}{Uma mesa de madeira, em condição justa a média.}
{30200}{}{Mesa}
{30201}{}{Uma mesa de madeira, em condições medíocres.}
{30300}{}{Mesa}
{30301}{}{Uma mesa de madeira, com superfície de plástico, que foi quebrada por um tempo.}
{30400}{}{Mesa}
{30401}{}{Uma mesa de madeira, pintada de uma cor verde vomitada, que está além de reparar.}
{30500}{}{Mesa}
{30501}{}{Isso parece uma mesa de café velha, baixa para o chão para aqueles mutantes muito curtos.}
{30600}{}{Mesa}
{30601}{}{Isso parece uma mesa de café velha, baixa para o chão para aqueles mutantes muito curtos.}
{30700}{}{Banheiro}
{30701}{}{As arestas afiadas ao redor do assento fazem deste um lugar muito desconfortável para se sentar.}
{30800}{}{Banheiro}
{30801}{}{Este banheiro está quebrado.}
{30900}{}{Banheiro}
{30901}{}{Que nojo! Quem usou este último não tirou!}
{31000}{}{Banheiro}
{31001}{}{Este banheiro está quebrado e definitivamente não é utilizável se você é uma mulher.}
{31100}{}{Lixo}
{31101}{}{Alguns tubos quebrados meio enterrados na sujeira. Nada importante para ver aqui. Mova-se.}
{31200}{}{Lixo}
{31201}{}{Alguns pedaços de vidro e outros pedaços de lixo arruinados.}
{31300}{}{Lixo}
{31301}{}{Alguns pedaços de vidro e outros pedaços de lixo arruinados.}
{31400}{}{Lixo}
{31401}{}{Um tubo que foi disparado pela metade. Parece que ele estava enferrujado até que desabou sob seu próprio peso.}
{31500}{}{Lixo Can}
{31501}{}{Uma lata de lixo. Você mal consegue ler o rótulo: Mantenha as ruas da sua cidade limpas!}
{31600}{}{Árvore}
{31601}{}{É uma árvore morta.}
{31700}{}{Árvore}
{31701}{}{Um coto. Nada excitante. Na verdade, esta pode ser a coisa menos emocionante em que você já colocou seus olhos.}
{31800}{}{Árvore}
{31801}{}{É uma árvore morta.}
{31900}{}{Árvore}
{32000}{}{Árvore}
{32100}{}{Árvore}
{32200}{}{Caminhão}
{32300}{}{Caminhão}
{32301}{}{Os restos arruinados de um caminhão diesel. Esse pedaço de metal nunca mais se moverá novamente.}
{32400}{}{Caminhão}
{32401}{}{Este caminhão diesel está além da ajuda. Muito além da ajuda.}
{32500}{}{Banheira}
{32501}{}{Esta banheira está quebrada e quebrada.}
{32600}{}{Banheira}
{32601}{}{Em um exame mais atento, você percebe que você não vai tomar seu banho nessa banheira, afinal.}
{32700}{}{Mictório}
{32701}{}{É apenas um urinol.}
{32800}{}{Mictório}
{32801}{}{É apenas um urinol.}
{32900}{}{Mictório}
{32901}{}{É apenas um urinol. Nothing special.}
{33000}{}{Mictório}
{33001}{}{É apenas um urinol. Nothing special.}
{33100}{}{Tanque de água}
{33101}{}{Um grande tanque que contém líquidos. Neste caso, você acredita que foi projetado para armazenar água.}
{33200}{}{Porta}
{33201}{}{Uma porta de madeira. Nada extremamente interessante sobre isso.}
{33300}{}{Porta}
{33301}{}{Uma porta de madeira. Fornece uma entrada e saída deste edifício.}
{33400}{}{parede Luminária}
{33401}{}{Esta lâmpada parece que está em boas condições de funcionamento.}
{33500}{}{parede Luminária}
{33501}{}{Uma lâmpada quebrada. Não é surpreendente que isso não funcione.}
{33600}{}{parede Luminária}
{33601}{}{Esta lâmpada parece que está em boas condições de funcionamento.}
{33700}{}{parede Luminária}
{33701}{}{Uma lâmpada quebrada. Não é surpreendente que isso não funcione.}
{33800}{}{parede Luminária}
{33801}{}{Esta lâmpada parece que está em boas condições de funcionamento.}
{33900}{}{parede Luminária}
{33901}{}{Uma lâmpada quebrada. Não é surpreendente que isso não funcione.}
{34000}{}{parede Luminária}
{34001}{}{Esta lâmpada parece que está em boas condições de funcionamento.}
{34100}{}{parede Luminária}
{34101}{}{Uma lâmpada quebrada. Não é surpreendente que isso não funcione.}
{34200}{}{Sinal de rendimento}
{34201}{}{Este foi um sinal para controlar o fluxo de tráfego.}
{34300}{}{Sinal de rendimento}
{34301}{}{O sinal está desbotado, mas você pode distinguir o RENDIMENTO mundial.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{Se você pode ver isso, culpe o designer técnico.}
{34500}{}{Chão}
{34600}{}{Porta}
{34601}{}{Uma porta de madeira ornamentada. É obviamente feito de mão de obra fina.}
{34700}{}{Pew}
{34701}{}{Este assento é suportado por grandes tijolos de concreto. Isso não é importante, mas você é o único que olhou.}
{34800}{}{Escadaria}
{34801}{}{Esta escada conduz.}
{34900}{}{Escadaria}
{34901}{}{Esta escada conduz.}
{35000}{}{Escadaria}
{35001}{}{Esta escada conduz.}
{35100}{}{Escadaria}
{35101}{}{Esta escada conduz.}
{35200}{}{Escadaria}
{35201}{}{Esta escada conduz.}
{35300}{}{Escadaria}
{35301}{}{Esta escada conduz.}
{35400}{}{Escadaria}
{35401}{}{Esta escada conduz.}
{35500}{}{Escadaria}
{35501}{}{Esta escada conduz.}
{35600}{}{Escadaria}
{35601}{}{Esta escada desce.}
{35700}{}{parede}
{35701}{}{Você está olhando para o exterior da Catedral.}
{35800}{}{parede}
{35801}{}{Você está olhando para o exterior da Catedral.}
{35900}{}{parede}
{35901}{}{Você está olhando para o exterior da Catedral.}
{36000}{}{parede}
{36001}{}{Você está olhando para o exterior da Catedral.}
{36100}{}{Cortina}
{36101}{}{Essa cortina parece que foi criada por meios primitivos, mas é muito funcional.}
{36200}{}{Cortina}
{36201}{}{Essa cortina parece que foi criada por meios primitivos, mas é muito funcional.}
{36300}{}{tigela}
{36301}{}{Uma tigela de madeira finamente trabalhada. Parece que foi projetado para esmagar e separar grãos.}
{36400}{}{tigela}
{36401}{}{Uma tigela de madeira finamente trabalhada.}
{36500}{}{Maconha}
{36501}{}{Um pote finamente crafted.}
{36600}{}{Plantararararararararararararar}
{36601}{}{Parece um repolho mutado para você. Parece estar prosperando no clima quente.}
{36700}{}{Plantararararararararararararar}
{36701}{}{Parece um repolho mutado para você. Parece estar prosperando no clima quente.}
{36800}{}{Carrorororororororororot}
{36801}{}{Um carrinho agrícola bruto, mas eficaz, agrícola.}
{36900}{}{Plantararararararararararararar}
{36901}{}{Um fio de milho mutado. Parece estar prosperando nessas condições.}
{37000}{}{Plantararararararararararararar}
{37001}{}{Um fio de milho mutado. Parece estar prosperando nessas condições.}
{37100}{}{Plantararararararararararararar}
{37101}{}{Um fio de milho mutado. Parece estar prosperando nessas condições.}
{37200}{}{Maconha}
{37201}{}{Um pote de barro finamente elaborado.}
{37300}{}{Ancinho}
{37301}{}{Este ancinho é propriedade de seus proprietários. Você não pode nem conceber um uso para isso.}
{37400}{}{Ancinho}
{37401}{}{Este ancinho é propriedade de seus proprietários. Você não pode nem conceber um uso para isso.}
{37500}{}{Ancinho}
{37501}{}{Este ancinho é propriedade de seus proprietários. Você não pode nem conceber um uso para isso.}
{37600}{}{Tapete}
{37601}{}{Um tapete simples. O tecelão era obviamente muito talentoso.}
{37700}{}{Tapete}
{37701}{}{Um tapete simples. O tecelão era obviamente muito talentoso.}
{37800}{}{Tapete}
{37801}{}{Um tapete simples. O tecelão era obviamente muito talentoso.}
{37900}{}{Pá}
{37901}{}{Esta pá é propriedade de seus proprietários. Você não pode nem conceber um uso para isso.}
{38000}{}{Pá}
{38001}{}{Esta pá é propriedade de seus proprietários. Você não pode nem conceber um uso para isso.}
{38100}{}{Pá}
{38101}{}{Esta pá é propriedade de seus proprietários. Você não pode nem conceber um uso para isso.}
{38200}{}{Vaso}
{38201}{}{Um vaso de argila muito bonito.}
{38300}{}{Bem}
{38301}{}{Um típico bem encontrado no deserto.}
{38400}{}{Pólo}
{38401}{}{Este pólo ajuda a apoiar a erva.}
{38500}{}{Pólo}
{38501}{}{Este pólo ajuda a apoiar a erva.}
{38600}{}{Pólo}
{38601}{}{Este pólo ajuda a apoiar a erva.}
{38700}{}{Pólo}
{38701}{}{Este pólo ajuda a apoiar a erva.}
{38800}{}{Pólo}
{38801}{}{Este pólo ajuda a apoiar a erva.}
{38900}{}{Pólo}
{38901}{}{Este pólo ajuda a apoiar a erva.}
{39000}{}{Vault Porta}
{39001}{}{Esta porta do abóbada é agora apenas um pedaço pesado de sucata.}
{39100}{}{parede}
{39101}{}{O mecanismo para abrir e fechar a porta da abóbada pesada foi danificado além do reparo.}
{39200}{}{Braçadeira}
{39201}{}{Este suporte ajuda a apoiar a parede defensiva.}
{39300}{}{Braçadeira}
{39301}{}{Este suporte ajuda a apoiar a parede defensiva.}
{39400}{}{Braçadeira}
{39401}{}{Este suporte ajuda a apoiar a parede defensiva.}
{39500}{}{Braçadeira}
{39501}{}{Este suporte ajuda a apoiar a parede defensiva.}
{39600}{}{Barrararil de metal}
{39601}{}{Um barril de metal enferrujado. Ele está vazio.}
{39700}{}{Barrararil de metal}
{39701}{}{Este barril provavelmente está vazio do som oco.}
{39800}{}{Barrararil de metals}
{39801}{}{Esses barris estão provavelmente vazios de seu som oco.}
{39900}{}{Barrararil de metals}
{39901}{}{Esses barris estão provavelmente vazios de seu som oco.}
{40000}{}{Saída de ar}
{40001}{}{Este respiradouro parece ser para uma estrutura subterrânea.}
{40100}{}{Caixa}
{40101}{}{Uma caixa de madeira. Não parece tão ruim da forma.}
{40200}{}{Caixa}
{40201}{}{Uma simples caixa de madeira. Em condições bastante boas.}
{40300}{}{Caixa}
{40301}{}{Esta simples caixa de madeira entrou em colapso sob o próprio peso.}
{40400}{}{Escrivaninha}
{40401}{}{Uma mesa simples com um computador.}
{40500}{}{Escrivaninha}
{40501}{}{Uma mesa simples com um computador.}
{40600}{}{Porta}
{40601}{}{Uma porta de madeira, em forma justa.}
{40700}{}{Cave In}
{40701}{}{Uma grande quantidade de rock, muito mais do que nunca poderia ser movido facilmente.}
{40800}{}{Carrorororororororororo}
{40801}{}{Este carro submerso não pode ser reparado.}
{40900}{}{Carrorororororororororo}
{40901}{}{Este carro está um pouco molhado e não pode ser reparado.}
{41000}{}{Carrorororororororororo}
{41001}{}{Este carro foi mal estacionado. Infelizmente, está além de reparar.}
{41100}{}{Lixo}
{41101}{}{Este lixo foi arruinado pela água do mar contaminada.}
{41200}{}{Lixo}
{41201}{}{Esta lixo quase foi lavada.}
{41300}{}{Lixo}
{41301}{}{Uma seleção seletiva de lixo inútil.}
{41400}{}{Tubos}
{41401}{}{Esses tubos costumavam transferir combustível de um tanque subterrâneo para a garagem. Eles não foram usados   há muito tempo.}
{41500}{}{Tubo}
{41501}{}{Esses tubos costumavam transferir combustível de um tanque subterrâneo para a garagem. Eles não foram usados   há muito tempo.}
{41600}{}{Tubos}
{41601}{}{Esses tubos costumavam transferir combustível de um tanque subterrâneo para a garagem. Eles não foram usados   há muito tempo.}
{41700}{}{Elevador Shaft}
{41701}{}{Parte de um sistema de elevador.}
{41800}{}{Elevador Shaft}
{41801}{}{Um eixo do elevador que se estende profundamente no chão. Foi danificado.}
{41900}{}{Elevador}
{41901}{}{Um elevador. Use-o para subir e descer entre os níveis.}
{42000}{}{Elevador Shaft}
{42001}{}{Um eixo do elevador que se estende profundamente no chão. Foi danificado.}
{42100}{}{Elevador Porta}
{42101}{}{Esta porta leva ao elevador. Se você deseja usar o elevador, primeiro você deve abrir esta porta.}
{42200}{}{Tubo}
{42201}{}{Um tubo de metal. Mais detalhes não são importantes.}
{42300}{}{Sujeira}
{42400}{}{Caixa}
{42500}{}{Caixa}
{42600}{}{Caixa}
{42700}{}{Caixa}
{42800}{}{Rochas}
{42801}{}{Uma pilha de rochas. Não é muito interessante.}
{42900}{}{Rochas}
{42901}{}{Uma pilha de rochas. Não é muito interessante.}
{43000}{}{Rochas}
{43001}{}{Uma pequena pilha de pedras. Not in the least bit interesting to you.}
{43100}{}{Rochas}
{43101}{}{Uma pilha muito pequena de rochas.}
{43200}{}{Rochas}
{43201}{}{Uma pilha muito pequena de rochas.}
{43300}{}{Rochas}
{43301}{}{Uma pilha muito pequena de rochas.}
{43400}{}{Rochas}
{43401}{}{Uma pilha muito pequena de rochas.}
{43500}{}{Rochas}
{43501}{}{Uma pilha muito pequena de rochas.}
{43600}{}{Vault Porta}
{43601}{}{Esta porta do abóbada é muito semelhante à do Vault-13. O mecanismo da porta foi desabilitado.}
{43700}{}{Porta}
{43701}{}{Uma porta de madeira finamente construída, reforçada com aparelhos de metal ornamentado de um design quase hipnótico.}
{43800}{}{Porta}
{43801}{}{Uma porta de madeira finamente construída, reforçada com aparelhos de metal ornamentado de um design quase hipnótico.}
{43900}{}{Vats}
{43901}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44000}{}{Vats}
{44001}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44100}{}{Vats}
{44101}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44200}{}{Vats}
{44201}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44300}{}{Vats}
{44301}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44400}{}{Vats}
{44401}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44500}{}{Vats}
{44501}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44600}{}{Vats}
{44601}{}{Um complexo de algum tipo. Você não tem certeza, mas você pode ver grandes cubas de um goo esverdeado que parece vagamente importante.}
{44700}{}{parede}
{44800}{}{Porta}
{44801}{}{Uma porta de segurança. Parece fortemente blindado.}
{44900}{}{Warhead nuclear}
{45000}{}{Bem}
{45001}{}{Um típico bem encontrado no deserto.}
{45100}{}{Craps Mesa}
{45101}{}{Esta é uma mesa de jogo.}
{45200}{}{Craps Mesa}
{45201}{}{Esta é uma mesa de jogo.}
{45300}{}{Craps Mesa}
{45301}{}{Esta é uma mesa de jogo.}
{45400}{}{Craps Mesa}
{45401}{}{Esta é uma mesa de jogo.}
{45500}{}{Craps Mesa}
{45501}{}{Esta é uma mesa de jogo.}
{45600}{}{Craps Mesa}
{45601}{}{Esta é uma mesa de jogo.}
{45700}{}{Craps Mesa}
{45701}{}{Esta é uma mesa de jogo.}
{45800}{}{Craps Mesa}
{45801}{}{Esta é uma mesa de jogo.}
{45900}{}{Craps Mesa}
{45901}{}{Esta é uma mesa de jogo.}
{46000}{}{Craps Mesa}
{46001}{}{Esta é uma mesa de jogo.}
{46100}{}{Rocha}
{46101}{}{Uma pequena rocha, completamente desinteressante no contexto desta história.}
{46200}{}{Rocha}
{46300}{}{Rocha}
{46400}{}{Rocha}
{46500}{}{Slot Máquina}
{46501}{}{Esta é uma máquina de jogar.}
{46600}{}{Slot Máquina}
{46601}{}{Esta é uma máquina de jogar.}
{46700}{}{Portaway}
{46800}{}{Elevador}
{46900}{}{Elevador}
{47000}{}{Elevador Porta}
{47100}{}{Janela}
{47101}{}{Em vez de vidro, esta janela está usando papel de cera.}
{47200}{}{Janela}
{47201}{}{Em vez de vidro, esta janela está usando papel de cera.}
{47300}{}{Janela}
{47301}{}{Em vez de vidro, esta janela está usando papel de cera.}
{47400}{}{Janela}
{47401}{}{Em vez de vidro, esta janela está usando papel de cera.}
{47500}{}{Porta}
{47501}{}{Esta grande porta de rolo de metal foi fechada por dentro.}
{47600}{}{Porta}
{47601}{}{Esta grande porta de rolo de metal foi fechada por dentro.}
{47700}{}{Porta}
{47701}{}{Esta grande porta de rolo de metal foi fechada por dentro. It reads LOADING ONLY.}
{47800}{}{Porta}
{47801}{}{Esta grande porta de rolo de metal foi fechada por dentro.}
{47900}{}{Porta}
{47901}{}{Esta grande porta de rolo de metal foi fechada por dentro.}
{48000}{}{Porta}
{48001}{}{Esta grande porta de rolo de metal foi fechada por dentro. It reads LOADING ONLY.}
{48100}{}{Porta}
{48101}{}{Esta porta parece com desconfiança a porta que você encontraria em um armazém.}
{48200}{}{Porta}
{48201}{}{Esta porta parece com desconfiança a porta que você encontraria em um armazém.}
{48300}{}{Weather Vane}
{48301}{}{Esta simples vaga de clima ajuda as pessoas de Shady Sands a estudar o clima.}
{48400}{}{Altar}
{48401}{}{Um altar simples feito de madeira pintada.}
{48500}{}{Pódio}
{48501}{}{Este é um pódio normal para falar em público.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{Um monitor grande, apenas preto e branco. A recepção é muito boa para estar dentro de casa sem uma antena.}
{48800}{}{Monitor}
{48801}{}{Um monitor grande, apenas preto e branco. A figura vestida está recitando o dogma religioso a um ritmo febril.}
{48900}{}{Campo de força}
{48901}{}{Este é um poderoso campo de energia.}
{49000}{}{Campo de força}
{49001}{}{Este é um poderoso campo de energia.}
{49100}{}{Campo de força}
{49101}{}{Este é um poderoso campo de energia.}
{49200}{}{Campo de força}
{49201}{}{Este é um poderoso campo de energia.}
{49300}{}{Mesa}
{49301}{}{Uma mesa de madeira bastante comum.}
{49400}{}{Mesa}
{49401}{}{Uma mesa de madeira bastante comum.}
{49500}{}{Mesa}
{49501}{}{Uma mesa de madeira bastante comum.}
{49600}{}{Mesa}
{49601}{}{Uma mesa de madeira bastante comum.}
{49700}{}{Mesa}
{49701}{}{Uma mesa de madeira bastante comum.}
{49800}{}{Mesa}
{49801}{}{Uma mesa de madeira bastante comum.}
{49900}{}{Estante}
{50000}{}{Estante}
{50100}{}{Estante}
{50200}{}{Estante}
{50300}{}{Estante}
{50400}{}{Estante}
{50500}{}{Altar}
{50501}{}{Um altar simples feito de madeira pintada.}
{50600}{}{Altar}
{50601}{}{Um altar simples feito de madeira pintada.}
{50700}{}{Altar}
{50701}{}{Um altar simples feito de madeira pintada.}
{50800}{}{Altar}
{50801}{}{Um altar simples feito de madeira pintada.}
{50900}{}{Destroços, Pedregulho}
{50901}{}{Uma seção colapsada do telhado formou esta pilha de escombros. Sua corda leva de volta à superfície.}
{51000}{}{Estante de livros}
{51100}{}{Estante de livros}
{51200}{}{Estante de livros}
{51300}{}{Estante de livros}
{51400}{}{Estante de livros}
{51500}{}{Estante de livros}
{51600}{}{Mesa}
{51601}{}{Esta grande mesa parece importante. Talvez tenham reuniões aqui?}
{51700}{}{Mesa}
{51701}{}{Esta grande mesa parece importante. Talvez tenham reuniões aqui?}
{51800}{}{Mesa}
{51801}{}{Esta grande mesa parece importante. Talvez tenham reuniões aqui?}
{51900}{}{Mesa}
{51901}{}{Esta grande mesa parece importante. Talvez tenham reuniões aqui?}
{52000}{}{Mesa}
{52001}{}{Esta grande mesa parece importante. Talvez tenham reuniões aqui?}
{52100}{}{Mesa}
{52101}{}{Esta grande mesa parece importante. Talvez tenham reuniões aqui?}
{52200}{}{Altar}
{52201}{}{Um altar projetado e usado pela Brotherhood of Steel. Seu símbolo é demonstrado descaradamente.}
{52300}{}{Altar}
{52301}{}{Um altar projetado e usado pela Brotherhood of Steel. Seu símbolo é demonstrado descaradamente.}
{52400}{}{Altar}
{52401}{}{Um altar projetado e usado pela Brotherhood of Steel. Seu símbolo é demonstrado descaradamente.}
{52500}{}{Pew}
{52501}{}{Uma aparência maravilhosa e poderosa e desconfortável.}
{52600}{}{Pódio}
{52601}{}{Um bom pódio de madeira. Há uma tela de tele-prompter incorporada, de frente para o alto-falante.}
{52700}{}{Vagão}
{52701}{}{Um vagão de caravana convertido dos restos destruídos de um antigo automóvel.}
{52800}{}{Vagão}
{52801}{}{Um vagão de caravana convertido dos restos destruídos de um antigo automóvel.}
{52900}{}{Vagão}
{52901}{}{Um vagão de caravana convertido dos restos destruídos de um antigo automóvel.}
{53000}{}{Vagão}
{53001}{}{Um vagão de caravana convertido dos restos destruídos de um antigo automóvel.}
{53100}{}{Vagão}
{53101}{}{Um vagão de caravana convertido dos restos destruídos de um antigo automóvel.}
{53200}{}{Vagão}
{53201}{}{Um vagão de caravana convertido dos restos destruídos de um antigo automóvel.}
{53300}{}{Esteira}
{53301}{}{Uma esteira de treinamento.}
{53400}{}{Esteira}
{53401}{}{Uma esteira de treinamento.}
{53500}{}{Esteira}
{53501}{}{Uma esteira de treinamento.}
{53600}{}{Esteira}
{53601}{}{Uma esteira de treinamento.}
{53700}{}{Saco de pancadas}
{53701}{}{Este é um saco de punção StrongMan (tm).}
{53800}{}{Stepper Stepper}
{53801}{}{Uma máquina de exercícios.}
{53900}{}{Stepper Stepper}
{54000}{}{Esteira}
{54001}{}{Uma máquina de exercícios.}
{54100}{}{Esteira}
{54101}{}{Uma máquina de exercícios.}
{54200}{}{Supino}
{54201}{}{Uma máquina de exercícios.}
{54300}{}{Supino}
{54301}{}{Uma máquina de exercícios.}
{54400}{}{Placas de madeira}
{54401}{}{Estas tábuas de madeira robustas foram firmemente unidas.}
{54500}{}{Placas de madeira}
{54501}{}{Estas tábuas de madeira robustas foram firmemente unidas.}
{54600}{}{Roulette Mesa}
{54601}{}{Esta é uma mesa de jogo.}
{54700}{}{Roulette Mesa}
{54701}{}{Esta é uma mesa de jogo.}
{54800}{}{Roulette Mesa}
{54801}{}{Esta é uma mesa de jogo.}
{54900}{}{Roulette Mesa}
{54901}{}{Esta é uma mesa de jogo.}
{55000}{}{Roulette Mesa}
{55001}{}{Esta é uma mesa de jogo.}
{55100}{}{Barrararel}
{55101}{}{Este barril de metal vazio tem o símbolo de trefoil nuclear pintado ao lado em tinta amarela brilhante.}
{55200}{}{Barrararel}
{55201}{}{Este barril contém algum goo verde brilhante. O símbolo de trefoil nuclear dá uma pista para o que o goo pode ser.}
{55300}{}{Computador}
{55301}{}{Um computador muito moderno.}
{55400}{}{Computador}
{55401}{}{Um computador muito moderno.}
{55500}{}{Tanque de Suspensão}
{55501}{}{Algum tipo de aparelho médico ou experimental, parece que poderia conter um corpo humano ou de tamanho maior.}
{55600}{}{Broken Tanque de Suspensão}
{55601}{}{Um equipamento quebrado. Está além de reparado.}
{55700}{}{Mainframe}
{55701}{}{Um super super computador. Provavelmente, o computador mais rápido que você já viu.}
{55800}{}{Plataforma de suporte}
{55801}{}{Esta plataforma suporta o super super computador sobre os tanques de refrigeração.}
{55900}{}{Não use}
{56000}{}{Não use}
{56100}{}{Cama}
{56101}{}{Um beliche de estilo militar. Parece muito desconfortável. Também parece que você poderia saltar um quarto de estas folhas.}
{56200}{}{Cama}
{56201}{}{Um beliche de estilo militar. Parece muito desconfortável. Também parece que você poderia saltar um quarto de estas folhas.}
{56300}{}{Cama}
{56301}{}{Um beliche de estilo militar. Parece muito desconfortável. Também parece que você poderia saltar um quarto de estas folhas.}
{56400}{}{Fio}
{56401}{}{Parece um cabo serial de algum tipo.}
{56500}{}{Fio}
{56501}{}{Parece um cabo serial de algum tipo.}
{56600}{}{Placa}
{56601}{}{O letreiro lê BAR. Isso deve ser bem evidente.}
{56700}{}{Beam}
{56701}{}{Este feixe forte está estacionado sobre o orifício da cratera.}
{56800}{}{Beam}
{56801}{}{Existe uma corda seguramente fixada ao feixe. Parece que você pode descer na cratera agora.}
{56900}{}{Prateleiras}
{56901}{}{Você vê algumas prateleiras metálicas muito vazias.}
{57000}{}{Prateleiras}
{57001}{}{Você vê algumas prateleiras metálicas muito vazias.}
{57100}{}{Prateleiras}
{57101}{}{Você vê algumas prateleiras metálicas muito vazias.}
{57200}{}{Prateleiras}
{57201}{}{Você vê algumas prateleiras metálicas muito vazias.}
{57300}{}{arbusto}
{57301}{}{Uma erva do deserto de algum tipo. Não é importante para esta história.}
{57400}{}{arbusto}
{57401}{}{Uma erva do deserto de algum tipo.}
{57500}{}{arbusto}
{57501}{}{Uma erva do deserto de algum tipo.}
{57600}{}{Terra}
{57601}{}{Uma bela vista dos Boneyards a partir deste nível da torre. Você tem uma boa sensação de quão alto no céu você está.}
{57700}{}{Terra}
{57701}{}{Uma bela vista dos Boneyards a partir deste nível da torre.}
{57800}{}{parede}
{57801}{}{Uma boa vista do lado de fora da Catedral.}
{57900}{}{parede}
{57901}{}{Uma boa vista do lado de fora da Catedral.}
{58000}{}{parede}
{58001}{}{Uma boa vista do lado de fora da Catedral.}
{58100}{}{Porta}
{58101}{}{Uma porta que parece perfeitamente em casa em uma cela.}
{58200}{}{Placa}
{58201}{}{Este sinal diz que esta loja é chamada de Darkwater.}
{58300}{}{Escada}
{58301}{}{Esta escada conduz à escuridão abaixo.}
{58400}{}{Escada}
{58401}{}{Esta escada conduz à escuridão abaixo.}
{58500}{}{Máquinas}
{58501}{}{Parece uma antiga impressora ou fabricação doohikey.}
{58600}{}{Máquinas}
{58601}{}{Parece uma antiga impressora ou fabricação doohikey.}
{58700}{}{Máquinas}
{58701}{}{Parece uma antiga impressora ou fabricação doohikey.}
{58800}{}{Máquinas}
{58801}{}{Parece uma antiga impressora ou fabricação doohikey.}
{58900}{}{Máquinas}
{58901}{}{Parece uma antiga impressora ou fabricação doohikey.}
{59000}{}{Máquinas}
{59001}{}{Parece uma antiga impressora ou fabricação doohikey.}
{59100}{}{Mesa}
{59101}{}{Esta mesa de metal parece em boas condições. Existe um dreno no centro.}
{59200}{}{Mesa}
{59201}{}{Esta mesa de metal parece em boas condições. Existe um dreno no centro.}
{59300}{}{Mesa}
{59301}{}{A mesa de metal é coberta por algum tipo de biomassa.}
{59400}{}{Mesa}
{59401}{}{A mesa de metal é coberta por algum tipo de biomassa.}
{59500}{}{Mesa}
{59501}{}{A mesa de metal é coberta por algum tipo de biomassa.}
{59600}{}{Quadro de avisos}
{59601}{}{Os avisos para o emprego estão grampeados para o conselho. Parece bem usado.}
{59700}{}{Barraraca de guarda}
{59701}{}{Esta cabana de guarda tem mais de cem anos, mas ainda está em excelente estado.}
{59800}{}{Placa}
{59801}{}{Este sinal diz: General Store.}
{59900}{}{Placa}
{59901}{}{Este sinal diz: General Store.}
{60000}{}{Placa}
{60001}{}{Este sinal diz: Mercado}
{60100}{}{Slime Pool}
{60101}{}{Parece muito insalubre. Você pode querer usar troncos de nadar blindados antes de dar um mergulho.}
{60200}{}{Slime Pool}
{60201}{}{Parece muito insalubre. Você pode querer usar troncos de nadar blindados antes de dar um mergulho.}
{60300}{}{Slime Pool}
{60301}{}{Parece muito insalubre. Você pode querer usar troncos de nadar blindados antes de dar um mergulho.}
{60400}{}{Mesa}
{60401}{}{Uma mesa de metal bonita.}
{60500}{}{Mesa}
{60501}{}{Uma mesa de metal bonita.}
{60600}{}{Mesa}
{60601}{}{Uma mesa de metal bonita.}
{60700}{}{Mesa}
{60701}{}{Uma mesa de metal bonita.}
{60800}{}{Mesa}
{60801}{}{Esta mesa de metal não foi bem tratada. A ferrugem é muito penetrante.}
{60900}{}{Mesa}
{60901}{}{Uma boa mesa de metal, exceto a ferrugem.}
{61000}{}{Mesa}
{61001}{}{Uma boa mesa de metal, exceto a ferrugem.}
{61100}{}{Mesa}
{61101}{}{Uma boa mesa de metal, exceto a ferrugem.}
{61200}{}{Fogo Pit}
{61201}{}{O fogo está queimando.}
{61300}{}{Espelho}
{61301}{}{Você se vê por um tempo.}
{61400}{}{Espelho}
{61401}{}{Você olha sua imagem no espelho por um tempo.}
{61500}{}{Pia}
{61501}{}{Uma pia em pleno funcionamento. Agradável e limpo também.}
{61600}{}{Banheiro}
{61601}{}{Este banheiro é muito limpo. Funciona também.}
{61700}{}{Mictório}
{61701}{}{Esse urinol é funcional.}
{61800}{}{Banheiro}
{61801}{}{Se você tivesse um fetiche no banheiro, então isso seria um bom banheiro.}
{61900}{}{Pia}
{61901}{}{Esta pia está em perfeitas condições.}
{62000}{}{Mictório}
{62001}{}{Este urinol está em perfeitas condições.}
{62100}{}{Chuveiro}
{62101}{}{Um banho de estilo militar. Não deve ser usado por pessoas modestas.}
{62200}{}{Chuveiro}
{62201}{}{Um banho de estilo militar. Não deve ser usado por pessoas modestas.}
{62300}{}{Chuveiro}
{62301}{}{Um banho de estilo militar. Não deve ser usado por pessoas modestas.}
{62400}{}{Chuveiro}
{62401}{}{Um banho de estilo militar. Não deve ser usado por pessoas modestas.}
{62500}{}{Chuveiro}
{62501}{}{Um banho de estilo militar. Não deve ser usado por pessoas modestas.}
{62600}{}{Chuveiro}
{62601}{}{Um banho de estilo militar. Não deve ser usado por pessoas modestas.}
{62700}{}{Cama}
{62701}{}{Uma cama muito confortável.}
{62800}{}{Cama}
{62801}{}{Uma cama muito confortável.}
{62900}{}{Cama}
{62901}{}{Um beliche estruturalmente melhorado.}
{63000}{}{Cama}
{63001}{}{Um beliche estruturalmente melhorado.}
{63100}{}{Cama}
{63101}{}{Um beliche estruturalmente melhorado.}
{63200}{}{terminal}
{63300}{}{terminal}
{63400}{}{Bandeira}
{63401}{}{Esta bandeira é o símbolo dos Filhos da Catedral.}
{63500}{}{Bandeira}
{63501}{}{Esta bandeira é o símbolo dos Filhos da Catedral.}
{63600}{}{Bandeira}
{63601}{}{Esta bandeira é o símbolo dos Filhos da Catedral.}
{63700}{}{Computador}
{63701}{}{Um computador grande.}
{63800}{}{Computador}
{63801}{}{Um computador grande.}
{63900}{}{Computador}
{63901}{}{Um computador grande.}
{64000}{}{terminal}
{64001}{}{O terminal para um computador grande.}
{64100}{}{Corpo morto}
{64101}{}{Parece que essa pessoa morreu muito dolorosamente.}
{64200}{}{Corpo morto}
{64201}{}{Parece que essa pessoa morreu muito dolorosamente.}
{64300}{}{Corpo morto}
{64301}{}{Parece que essa pessoa morreu muito dolorosamente.}
{64400}{}{Corpo morto}
{64401}{}{Parece que essa pessoa morreu muito dolorosamente.}
{64500}{}{Porta}
{64501}{}{Esta porta barrada funciona bem como a porta de uma cela.}
{64600}{}{terminal}
{64700}{}{terminal}
{64800}{}{Empilhadeira}
{64801}{}{A empilhadeira é inoperável.}
{64900}{}{Empilhadeira}
{64901}{}{A empilhadeira é inoperável.}
{65000}{}{Equipamento}
{65100}{}{Medical Mesa}
{65101}{}{Esta mesa está muito enferrujada. O dreno no centro da mesa está entupido.}
{65200}{}{Medical Mesa}
{65201}{}{Esta mesa está muito enferrujada.}
{65300}{}{Portão}
{65301}{}{Este portão tem uma barra que aumenta e diminui.}
{65400}{}{Tubo}
{65500}{}{Tubo}
{65600}{}{Gerador de energia}
{65601}{}{A Wattz ElectroCaixa power generator. Fairly standard as back-up generators before the war.}
{65700}{}{Tanque}
{65701}{}{Um grande tanque de água. Parece bem conservado, o que provavelmente é bom.}
{65800}{}{Police Caixa}
{65801}{}{Uma caixa de polícia do Reino Unido, por volta de 1960.}
{65900}{}{Mesa}
{65901}{}{Uma mesa bem feita. Feito à mão, mas parece muito melhor do que qualquer mesa que você já viu antes.}
{66000}{}{Mesa}
{66001}{}{Uma mesa bem feita. Feito à mão, mas parece muito melhor do que qualquer mesa que você já viu antes.}
{66100}{}{Mesa}
{66101}{}{Uma mesa bem feita. Feito à mão, mas parece muito melhor do que qualquer mesa que você já viu antes.}
{66200}{}{Cadeira}
{66201}{}{Uma cadeira muito bonita.}
{66300}{}{Cadeira}
{66301}{}{Uma cadeira muito bonita.}
{66400}{}{Cadeira}
{66401}{}{Uma cadeira muito bonita.}
{66500}{}{Cadeira}
{66501}{}{Uma cadeira muito bonita.}
{66600}{}{Cadeira}
{66601}{}{Uma cadeira muito bonita.}
{66700}{}{Cadeira}
{66701}{}{Uma cadeira muito bonita.}
{66800}{}{Cadeira}
{66801}{}{Uma cadeira muito bonita.}
{66900}{}{Cadeira}
{66901}{}{Uma cadeira muito bonita.}
{67000}{}{Cadeira}
{67001}{}{Uma cadeira muito bonita.}
{67100}{}{Cadeira}
{67101}{}{Uma cadeira muito bonita.}
{67200}{}{Cadeira}
{67201}{}{Uma cadeira muito bonita.}
{67300}{}{Cadeira}
{67301}{}{Uma cadeira muito bonita.}
{67400}{}{Cadeira}
{67401}{}{Uma cadeira muito bonita.}
{67500}{}{Cadeira}
{67501}{}{Uma cadeira muito bonita.}
{67600}{}{Cadeira}
{67601}{}{Uma cadeira muito bonita.}
{67700}{}{Cadeira}
{67701}{}{Uma cadeira muito bonita.}
{67800}{}{Cama}
{67801}{}{Uma cama muito bonita.}
{67900}{}{Cama}
{67901}{}{Uma cama muito bonita.}
{68000}{}{Cama}
{68001}{}{Uma cama muito bonita.}
{68100}{}{Cama}
{68101}{}{Uma cama muito bonita.}
{68200}{}{Fogão}
{68201}{}{Um fogão a lenha funcional.}
{68300}{}{Fogão}
{68301}{}{Um fogão a lenha funcional.}
{68400}{}{Fogão}
{68401}{}{Um fogão a lenha funcional.}
{68500}{}{Fogão}
{68501}{}{Um fogão a lenha funcional.}
{68600}{}{Broken Postarararar}
{68700}{}{Entrada destruída}
{68800}{}{Rochas}
{68801}{}{Uma grande formação de rochas. Esta não foi uma ocorrência natural.}
{68900}{}{Rochas}
{68901}{}{Uma grande formação de rochas. Esta não foi uma ocorrência natural.}
{69000}{}{Banheiro}
{69001}{}{Um vaso de água bruta, mas eficaz. Há algumas folhas caídas no buraco para controlar o odor.}
{69100}{}{Montanha}
{69101}{}{Essas paredes de montanhas parecem muito inacessíveis.}
{69200}{}{Montanha}
{69201}{}{Essas paredes de montanhas parecem muito inacessíveis.}
{69300}{}{Montanha}
{69301}{}{Essas paredes de montanhas parecem muito inacessíveis.}
{69400}{}{Montanha}
{69401}{}{Essas paredes de montanhas parecem muito inacessíveis.}
{69500}{}{Montanha}
{69501}{}{Essas paredes de montanhas parecem muito inacessíveis.}
{69600}{}{Montanha}
{69601}{}{Essas paredes de montanhas parecem muito inacessíveis.}
{69700}{}{Goo}
{69701}{}{Você vê algum estranho biológico noxious biológico.}
{69800}{}{Goo}
{69801}{}{Você vê algum estranho biológico noxious biológico.}
{69900}{}{Goo}
{69901}{}{Você vê algum estranho biológico noxious biológico.}
{70000}{}{Goo}
{70001}{}{Você vê algum estranho biológico noxious biológico.}
{70100}{}{Goo}
{70101}{}{Você vê algum estranho biológico noxious biológico.}
{70200}{}{Goo}
{70201}{}{Você vê algum estranho biológico noxious biológico.}
{70300}{}{Goo}
{70301}{}{Você vê algum estranho biológico noxious biológico.}
{70400}{}{Goo}
{70401}{}{Você vê algum estranho biológico noxious biológico.}
{70500}{}{Goo}
{70501}{}{Você vê algum estranho biológico noxious biológico.}
{70600}{}{Goo}
{70601}{}{Você vê algum estranho biológico noxious biológico.}
{70700}{}{Goo}
{70701}{}{Você vê algum estranho biológico noxious biológico.}
{70800}{}{Goo}
{70801}{}{Você vê algum estranho biológico noxious biológico.}
{70900}{}{Goo}
{70901}{}{Você vê algum estranho biológico noxious biológico.}
{71000}{}{Goo}
{71001}{}{Você vê algum estranho biológico noxious biológico.}
{71100}{}{Goo}
{71101}{}{Você vê algum estranho biológico noxious biológico.}
{71200}{}{Goo}
{71201}{}{Você vê algum estranho biológico noxious biológico.}
{71300}{}{Goo}
{71301}{}{Você vê algum estranho biológico noxious biológico.}
{71400}{}{Goo}
{71401}{}{Você vê algum estranho biológico noxious biológico.}
{71500}{}{Goo}
{71501}{}{Você vê algum estranho biológico noxious biológico.}
{71600}{}{Goo}
{71601}{}{Você vê algum estranho biológico noxious biológico.}
{71700}{}{Goo}
{71701}{}{Você vê algum estranho biológico noxious biológico.}
{71800}{}{Goo}
{71801}{}{Você vê algum estranho biológico noxious biológico.}
{71900}{}{Goo}
{71901}{}{Você vê algum estranho biológico noxious biológico.}
{72000}{}{Goo}
{72001}{}{Você vê algum estranho biológico noxious biológico.}
{72100}{}{Goo}
{72101}{}{Você vê algum estranho biológico noxious biológico.}
{72200}{}{Goo}
{72201}{}{Você vê algum estranho biológico noxious biológico.}
{72300}{}{Goo}
{72301}{}{Você vê algum estranho biológico noxious biológico.}
{72400}{}{Goo}
{72401}{}{Você vê algum estranho biológico noxious biológico.}
{72500}{}{Goo}
{72501}{}{Você vê algum estranho biológico noxious biológico.}
{72600}{}{Goo}
{72601}{}{Você vê algum estranho biológico noxious biológico.}
{72700}{}{Goo}
{72701}{}{Você vê algum estranho biológico noxious biológico.}
{72800}{}{Goo}
{72801}{}{Você vê algum estranho biológico noxious biológico.}
{72900}{}{Goo}
{72901}{}{Você vê algum estranho biológico noxious biológico.}
{73000}{}{Goo}
{73001}{}{Você vê algum estranho biológico noxious biológico.}
{73100}{}{Goo}
{73101}{}{Você vê algum estranho biológico noxious biológico.}
{73200}{}{Goo}
{73201}{}{Você vê algum estranho biológico noxious biológico.}
{73300}{}{Goo}
{73301}{}{Você vê algum estranho biológico noxious biológico.}
{73400}{}{Goo}
{73401}{}{Você vê algum estranho biológico noxious biológico.}
{73500}{}{Goo}
{73501}{}{Você vê algum estranho biológico noxious biológico.}
{73600}{}{Goo}
{73601}{}{Você vê algum estranho biológico noxious biológico.}
{73700}{}{Goo}
{73701}{}{Você vê algum estranho biológico noxious biológico.}
{73800}{}{Goo}
{73801}{}{Você vê algum estranho biológico noxious biológico.}
{73900}{}{Goo}
{73901}{}{Você vê algum estranho biológico noxious biológico.}
{74000}{}{Goo}
{74001}{}{Você vê algum estranho biológico noxious biológico.}
{74100}{}{Goo}
{74101}{}{Você vê algum estranho biológico noxious biológico.}
{74200}{}{Goo}
{74201}{}{Você vê algum estranho biológico noxious biológico.}
{74300}{}{Goo}
{74301}{}{Você vê algum estranho biológico noxious biológico.}
{74400}{}{Goo}
{74401}{}{Você vê algum estranho biológico noxious biológico.}
{74500}{}{Goo}
{74501}{}{Você vê algum estranho biológico noxious biológico.}
{74600}{}{Goo}
{74601}{}{Você vê algum estranho biológico noxious biológico.}
{74700}{}{Goo}
{74701}{}{Você vê algum estranho biológico noxious biológico.}
{74800}{}{Goo}
{74801}{}{Você vê algum estranho biológico noxious biológico.}
{74900}{}{Computador}
{74901}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75000}{}{Computador}
{75001}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75100}{}{Computador}
{75101}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75200}{}{Computador}
{75201}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75300}{}{Computador}
{75301}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75400}{}{Computador}
{75401}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75500}{}{Computador}
{75501}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75600}{}{Computador}
{75601}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75700}{}{Computador}
{75701}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75800}{}{Computador}
{75801}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{75900}{}{Computador}
{75901}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{76000}{}{Computador}
{76001}{}{A quantidade de goo neste computador torna muito difícil acessar.}
{76100}{}{Monitores}
{76101}{}{Você não pode ler nada no monitor devido à quantidade de goo salpicada pelas telas.}
{76200}{}{Monitores}
{76201}{}{Você não pode ler nada no monitor devido à quantidade de goo salpicada pelas telas.}
{76300}{}{Monitores}
{76301}{}{Você não pode ler nada no monitor devido à quantidade de goo salpicada pelas telas.}
{76400}{}{Monitores}
{76401}{}{Você não pode ler nada no monitor devido à quantidade de goo salpicada pelas telas.}
{76500}{}{Chão}
{76501}{}{Você iria jurar que há algo movendo no chão.}
{76600}{}{Pedestal}
{76601}{}{O pedestal parece como se estivesse lentamente entrando e saindo.}
{76700}{}{Chão}
{76800}{}{Bombear}
{76801}{}{Esta é uma bomba nuclear. Parece muito perigoso, sentado aqui.}
{76900}{}{Base de suporte}
{76901}{}{Esta base acumula a bomba nuclear que está sentada nela.}
{77000}{}{Computador Console}
{77001}{}{Este é um computador de acesso nuclear. O computador parece muito seguro. Existe um slot para uma chave de forma estranha.}
{77100}{}{Fios}
{77101}{}{Esses fios estão conectando a bomba ao computador.}
{77200}{}{Cadeira}
{77201}{}{Não há nada de incomum nesta cadeira.}
{77300}{}{Cadeira}
{77301}{}{Não há nada de incomum nesta cadeira.}
{77400}{}{Cadeira}
{77401}{}{Não há nada de incomum nesta cadeira.}
{77500}{}{Cadeira}
{77501}{}{Não há nada de incomum nesta cadeira.}
{77600}{}{Cadeira}
{77601}{}{Não há nada de incomum nesta cadeira.}
{77700}{}{Cadeira}
{77701}{}{Não há nada de incomum nesta cadeira.}
{77800}{}{Cadeira}
{77801}{}{Não há nada de incomum nesta cadeira.}
{77900}{}{Cadeira}
{77901}{}{Não há nada de incomum nesta cadeira.}
{78000}{}{Pilar}
{78001}{}{Um pilar de apoio.}
{78100}{}{Pilar}
{78101}{}{Um pilar de apoio.}
{78200}{}{Pilar}
{78201}{}{Um pilar de apoio.}
{78300}{}{Pilar}
{78301}{}{Um pilar de apoio.}
{78400}{}{Cama}
{78401}{}{Esta cama está em condição miserável.}
{78500}{}{Cama}
{78501}{}{Esta cama está em muito mau estado.}
{78600}{}{Cama}
{78601}{}{Esta cama está em mau estado.}
{78700}{}{Cama}
{78701}{}{Esta cama está em muito ruim.}
{78800}{}{Monitores}
{78801}{}{Esses monitores estão quebrados e não podem funcionar.}
{78900}{}{Monitores}
{78901}{}{Esses monitores estão quebrados e não podem funcionar.}
{79000}{}{Monitores}
{79001}{}{Esses monitores estão quebrados e não podem funcionar.}
{79100}{}{Monitores}
{79101}{}{Esses monitores estão quebrados e não podem funcionar.}
{79200}{}{Vent}
{79201}{}{Muito pouco ar fresco vem deste respiradouro.}
{79300}{}{Vent}
{79301}{}{Quase nenhum ar fresco está vindo deste respiradouro.}
{79400}{}{Vent}
{79401}{}{Nenhum ar fresco está vindo deste respiradouro.}
{79500}{}{Vent}
{79501}{}{Apenas uma pequena quantidade de ar fresco é proveniente desse respiradouro.}
{79600}{}{Mesa}
{79601}{}{Não há nada incomum nesta mesa, exceto que está quase destruído.}
{79700}{}{Mesa}
{79701}{}{Esta tabela estava gravemente danificada.}
{79800}{}{Mesa}
{79801}{}{Esta tabela está em muito mau estado.}
{79900}{}{Mesa}
{79901}{}{Não há motivos para pesquisar nesta tabela.}
{80000}{}{Monitores}
{80001}{}{As telas de exibição neste banco de monitores foram destruídas.}
{80100}{}{Monitores}
{80101}{}{As telas de exibição neste banco de monitores foram danificadas além de reparo.}
{80200}{}{Monitor}
{80201}{}{A tela do monitor é quebrada e destruída.}
{80300}{}{Monitor}
{80301}{}{Este monitor não tem valor com uma tela de exibição quebrada.}
{80400}{}{Computador}
{80401}{}{Este computador está quebrado.}
{80500}{}{Computador}
{80501}{}{Este computador está quebrado.}
{80600}{}{Computador}
{80601}{}{Este computador está quebrado.}
{80700}{}{Cadeira}
{80701}{}{Esta cadeira está arruinada.}
{80800}{}{Cadeira}
{80801}{}{Esta cadeira está arruinada.}
{80900}{}{Cadeira}
{80901}{}{Esta cadeira está arruinada.}
{81000}{}{Cadeira}
{81001}{}{Esta cadeira está arruinada.}
{81100}{}{Vent}
{81101}{}{Este respiradouro foi danificado além do reparo.}
{81200}{}{Vent}
{81201}{}{Este respiradouro está muito danificado e não pode ser reparado.}
{81300}{}{Vent}
{81301}{}{Este respiradouro não está funcionando.}
{81400}{}{Computador}
{81401}{}{Este computador parece que é pouco funcional.}
{81500}{}{Computador}
{81501}{}{Este computador parece que é pouco funcional.}
{81600}{}{Monitor}
{81601}{}{O monitor está mal trabalhando.}
{81700}{}{Monitor}
{81701}{}{O monitor está mal trabalhando.}
{81800}{}{Computador}
{81801}{}{O computador não está funcionando.}
{81900}{}{Computador}
{81901}{}{O computador não está funcionando.}
{82000}{}{Monitor}
{82001}{}{O monitor não está funcionando.}
{82100}{}{Monitor}
{82101}{}{O monitor não está funcionando.}
{82200}{}{Portaway}
{82201}{}{Parece uma porta muito agradável. Faz o trabalho de segurar uma porta muito bem.}
{82300}{}{Monitores}
{82301}{}{Os monitores estão em boas condições.}
{82400}{}{Monitores}
{82401}{}{Os monitores estão em boas condições.}
{82500}{}{parede}
{82600}{}{Bank Porta}
{82601}{}{Uma porta de vaivén de banco muito robusta. A porta parece muito segura.}
{82700}{}{Luz}
{82701}{}{Uma luz de segurança.}
{82800}{}{Luz}
{82801}{}{Uma luz de segurança.}
{82900}{}{Pilar}
{82901}{}{Este pilar é o show do quadrado Shady Sands. Ele conta histórias para lembrar as pessoas de esperança e paz.}
{83000}{}{Receptáculo de robô}
{83001}{}{Este é um compartimento de recarga de robôs. Quando não estiver em serviço, os robôs encaixarão aqui para desligar e recarregar.}
{83100}{}{Receptáculo de robô}
{83101}{}{Este é um compartimento de recarga de robôs. Quando não estiver em serviço, os robôs encaixarão aqui para desligar e recarregar.}
{83200}{}{Receptáculo de robô}
{83201}{}{Este é um compartimento de recarga de robôs. Quando não estiver em serviço, os robôs encaixarão aqui para desligar e recarregar.}
{83300}{}{Receptáculo de robô}
{83301}{}{Este é um compartimento de recarga de robôs. Quando não estiver em serviço, os robôs encaixarão aqui para desligar e recarregar.}
{83400}{}{Receptáculo de robô}
{83401}{}{Este é um compartimento de recarga de robôs. Quando não estiver em serviço, os robôs encaixarão aqui para desligar e recarregar.}
{83500}{}{Máquina}
{83501}{}{Esta máquina tem algo a ver com as baías de serviços de robôs. Não parece particularmente interessante.}
{83600}{}{Máquina}
{83601}{}{Esta máquina tem algo a ver com as baías de serviços de robôs. Não parece muito interessante.}
{83700}{}{Listra}
{83800}{}{Listra}
{83900}{}{Listra}
{84000}{}{Listra}
{84100}{}{Listra}
{84200}{}{Listra}
{84300}{}{Listra}
{84400}{}{Listra}
{84500}{}{Listra}
{84600}{}{Listra}
{84700}{}{Listra}
{84800}{}{Porta}
{84801}{}{Uma porta de madeira muito normal.}
{84900}{}{Porta}
{84901}{}{Uma porta de madeira muito normal.}
{85000}{}{Porta}
{85001}{}{Uma porta de madeira muito normal.}
{85100}{}{Placa}
{85101}{}{Este sinal significa Friendly Lending Company.}
{85200}{}{Emblemaaa}
{85201}{}{Isso parece ser um emblema religioso.}
{85300}{}{Medical Mesa}
{85301}{}{Isso parece uma mesa de exame médico.}
{85400}{}{Placa}
{85401}{}{Este é um sinal de néon para o falcão maltês.}
{85500}{}{Graffiti}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Placa}
{86901}{}{Diz: GUNS. Eles podem vender armas lá.}
{87000}{}{Placa}
{87001}{}{O letreiro diz: Polícia.}
{87100}{}{Placa}
{87101}{}{Este é o sinal dos Far Go Traders.}
{87200}{}{Placa}
{87201}{}{Este sinal é rotulado como: Gunrunners.}
{87300}{}{Placa}
{87301}{}{This is the sign of the Crimson Carrorororororororororoavan trading company.}
{87400}{}{Placa}
{87401}{}{Este sinal lê: Hospital. Isso pode ser uma coisa boa.}
{87500}{}{Placa}
{87501}{}{Este é o sinal da Crash House.}
{87600}{}{Placa}
{87601}{}{This very unlikely sign reads: Bob's Pre-Owned Carrorororororororororo Mart.}
{87700}{}{Placa}
{87701}{}{Este é o sinal da agua Merchants, uma empresa comercial do Hub.}
{87800}{}{Casca De Ovos}
{87801}{}{Peças de casca de ovo quebrada.}
{87900}{}{Casca De Ovos}
{87901}{}{Peças de casca de ovo quebrada.}
{88000}{}{Casca De Ovos}
{88001}{}{Peças de casca de ovo quebrada.}
{88100}{}{Casca De Ovos}
{88101}{}{Peças de casca de ovo quebrada.}
{88200}{}{Casca De Ovos}
{88201}{}{Peças de casca de ovo quebrada.}
{88300}{}{Casca De Ovos}
{88301}{}{Peças de casca de ovo quebrada.}
{88400}{}{Casca De Ovos}
{88401}{}{Peças de casca de ovo quebrada.}
{88500}{}{Casca De Ovos}
{88501}{}{Peças de casca de ovo quebrada.}
{88600}{}{Postarararare de iluminação}
{88601}{}{Uma lâmpada. Parece que está em bom estado de funcionamento.}
{88700}{}{Placa}
{88701}{}{O letreiro diz: Motel.}
{88800}{}{Cogumelos}
{88801}{}{Este plantador de mesa foi preenchido com esterco, e os cogumelos crescem felizmente nele.}
{88900}{}{Cogumelos}
{88901}{}{Este plantador de mesa foi preenchido com esterco, e os cogumelos crescem felizmente nele.}
{89000}{}{Esqueleto}
{89100}{}{Placa}
{89101}{}{Este sinal lê: prisão.}
{89200}{}{Placa}
{89201}{}{Este é o sinal da barra Skum Pitt e loucinha.}
{89300}{}{Placa}
{89301}{}{Um anúncio para as lâminas de barbear da marca Blades.}
{89400}{}{Chuveiro}
{89401}{}{Uma cabine de banho bastante normal.}
{89500}{}{Chuveiro}
{89501}{}{Uma cabine de banho bastante normal.}
{89600}{}{Placa}
{89601}{}{Este é o sinal da Friendly Lending Company.}
{89700}{}{Placa}
{89701}{}{Este é o sinal da Friendly Lending Company.}
{89800}{}{Postararararer}
{89801}{}{Este é um cartaz de cinema para um filme de terror dos dias anteriores à guerra.}
{89900}{}{Postararararer}
{89901}{}{Este é um cartaz de cinema para um filme de terror dos dias anteriores à guerra.}
{90000}{}{Barrara}
{90001}{}{Há uma urna sentada neste bar. A urna parece um pouco espancada, mas pode ser valiosa.}
{90100}{}{Elevador Shaft}
{90101}{}{O eixo tem uma corda pendurada acima.}
{90200}{}{Elevador Shaft}
{90201}{}{O eixo tem uma corda pendurada na borda.}
{90300}{}{Medical Cama}
{90301}{}{Esta cama possui uma tela embutida para monitorar o progresso dos pacientes.}
{90400}{}{Bomba de água}
{90401}{}{Esta é uma peça de maquinaria que bombeia água de baixo.}
{90500}{}{Medical Cama}
{90501}{}{Esta cama possui uma tela embutida para monitorar o progresso dos pacientes.}
{90600}{}{Peças de armadura de energia}
{90601}{}{Estas são peças para um terno de Power Armor.}
{90700}{}{Luz}
{90701}{}{Esta luz de segurança está pulsando atualmente um vermelho brilhante.}
{90800}{}{Luz}
{90801}{}{Esta luz de segurança está pulsando atualmente um vermelho brilhante.}
{90900}{}{Símbolo}
{91000}{}{Símbolo}
{91100}{}{Símbolo}
{91200}{}{Símbolo}
{91300}{}{Símbolo}
{91400}{}{Símbolo}
{91500}{}{Corda}
{91600}{}{Corda}
{91700}{}{Corda}
{91800}{}{Corda}
{91900}{}{Corda}
{92000}{}{Corda}
{92100}{}{Corda}
{92200}{}{Corda}
{92300}{}{Canyon}
{92400}{}{Canyon}
{92500}{}{Canyon}
{92600}{}{Canyon}
{92700}{}{Canyon}
{92800}{}{Canyon}
{92900}{}{Canyon}
{93000}{}{Canyon}
{93100}{}{Cave Chão}
{93200}{}{Impenetrable Porta}
{93201}{}{Esta porta parece não ter nenhum mecanismo de abertura.}
{93300}{}{Destroyed Porta}
{93301}{}{A porta foi aberta.}
{93400}{}{Porta}
{93401}{}{Uma porta com um bloqueio intrincado.}
{93500}{}{Tocha}
{93501}{}{Uma tocha acesa em um aplique de parede.}
{93600}{}{Tocha}
{93601}{}{Uma tocha acesa em um aplique de parede.}
{93700}{}{Monumento de pedra}
{93800}{}{Monumento de pedra}
{93900}{}{Monumento de pedra}
{94000}{}{Skull Pólo}
{94001}{}{Um poste com crânios humanos em anexo.}
{94100}{}{Skull Pólo}
{94101}{}{Um poste com crânios humanos em anexo.}
{94200}{}{Skull Pólo}
{94201}{}{Um poste com crânios humanos em anexo.}
{94300}{}{Plantararararararararararararar}
{94301}{}{}
{94400}{}{Plantararararararararararararar}
{94500}{}{Árvore}
{94600}{}{Árvore}
{94700}{}{Árvore}
{94800}{}{Cama}
{94900}{}{Cama}
{95000}{}{Buraco}
{95001}{}{Um buraco suspeito na parede.}
{95100}{}{Placa de pedra levantada}
{95101}{}{Uma placa de pedra levantada.}
{95200}{}{Placa de pedra desabilitada}
{95201}{}{Uma placa de pedra desabilitada.}
{95300}{}{Placa de pedra desencadeada}
{95301}{}{Uma placa de pedra desencadeada.}
{95400}{}{Porta}
{95500}{}{Porta}
{95600}{}{Porta}
{95700}{}{Porta}
{95800}{}{Porta}
{95900}{}{Porta}
{96000}{}{Porta}
{96100}{}{Porta}
{96200}{}{Porta}
{96300}{}{Plantararararararararararararar}
{96301}{}{Um fio de milho mutado.}
{96400}{}{Plantararararararararararararar}
{96401}{}{Um fio de milho mutado.}
{96500}{}{Plantararararararararararararar}
{96501}{}{Um fio de milho mutado. This one is sick.}
{96600}{}{Plantararararararararararararar}
{96601}{}{Um fio de milho mutado.}
{96700}{}{Plantararararararararararararar}
{96701}{}{Um fio de milho mutado.}
{96800}{}{Plantararararararararararararar}
{96801}{}{Um fio de milho mutado.}
{96900}{}{Suporte de madeira}
{97000}{}{Suporte de madeira}
{97100}{}{Suporte de madeira}
{97200}{}{Suporte de madeira}
{97300}{}{Suporte de madeira}
{97400}{}{Suporte de madeira}
{97500}{}{Damaged Suporte de madeira}
{97501}{}{Este suporte parece que poderia colapsar se forçado.}
{97600}{}{Collapsed Chão}
{97601}{}{O piso de pedra entrou em colapso no nível inferior.}
{97700}{}{Escada Down}
{97701}{}{Um buraco feito com uma escada que conduz para baixo.}
{97800}{}{Porta}
{97900}{}{parede}
{98000}{}{Reactor 5 Placa}
{98100}{}{Porta}
{98200}{}{Porta}
{98300}{}{Porta}
{98400}{}{Porta}
{98500}{}{Goo radioativo}
{98600}{}{Goo radioativo}
{98700}{}{Goo radioativo}
{98800}{}{Goo radioativo}
{98900}{}{Porta de segurança}
{99000}{}{Vault Porta}
{99100}{}{Guindaste utilitário}
{99200}{}{Guindaste utilitário}
{99300}{}{Bem}
{99400}{}{Bem}
{99500}{}{Outhouse}
{99600}{}{Buraco}
{99601}{}{Você não pode ver o fundo deste poço.}
{99700}{}{Chão Plate}
{99701}{}{Você vê uma armadilha de placa de chão.}
{99800}{}{Disabled Chão Plate}
{99801}{}{Esta armadilha da placa do chão foi desativada.}
{99900}{}{Triggered Chão Plate}
{99901}{}{Esta armadilha de placa de chão foi desencadeada. Opps!}
{100000}{}{Ainda}
{100001}{}{Isso parece um álcool queima de lenha ainda.}
{100100}{}{Rad Scorpion Parts}
{100101}{}{Você vê uma grande pilha de peças de Radscorpion. Eles foram esvaziados e têm alças presas a eles.}
{100200}{}{Powerplant Máquinas}
{100201}{}{Esta é a máquina Plutonium-Gamma Shield para o reator.}
{100300}{}{Powerplant Máquinas}
{100301}{}{Esta é a máquina Jupiter Wave Compiler para o reator.}
{100400}{}{Powerplant Máquinas}
{100401}{}{Esta é a máquina de transmissão de urânio-haste para o reator.}
{100500}{}{Powerplant Máquinas}
{100501}{}{Esta é a máquina impulsora Neptunium para o reator.}
{100600}{}{Powerplant Máquinas}
{100601}{}{Esta é a máquina de condensação de classe Saturno para o reator.}
{100700}{}{Controle da bomba do poder}
{100701}{}{Esta é a máquina de bombeamento de refrigerante para o reator.}
{100800}{}{Lado do brahmin}
{100900}{}{Carrorororororororororo}
{101000}{}{Chrysalis Motors Carrorororororororororo}
{101001}{}{Este Chrysalis Motors Highwayman parece estar em boa forma para a sua idade.}
{101100}{}{Carrorororororororororo}
{101200}{}{Gravesite}
{101201}{}{Está localizado um túmulo aqui.}
{101300}{}{Headstone}
{101301}{}{Headstone}
{101400}{}{Headstone}
{101401}{}{Headstone}
{101500}{}{Headstone}
{101501}{}{Headstone}
{101600}{}{Headstone}
{101601}{}{Headstone}
{101700}{}{Arado}
{101701}{}{Este arado é projetado para ser arrastado por um brahmin.}
{101800}{}{Arado}
{101801}{}{Este arado é projetado para ser arrastado por um brahmin.}
{101900}{}{agua}
{102000}{}{Placa}
{102001}{}{O sinal de entrada para New Reno.}
{102100}{}{Placa}
{102101}{}{O sinal de entrada para New Reno.}
{102200}{}{Placa}
{102201}{}{O sinal de entrada para New Reno.}
{102300}{}{Placa}
{102301}{}{O sinal de entrada para New Reno.}
{102400}{}{Placa}
{102401}{}{O sinal de entrada para New Reno.}
{102500}{}{Placa}
{102501}{}{O sinal de entrada para New Reno.}
{102600}{}{Sombra}
{102700}{}{Sombra}
{102800}{}{Sombra}
{102900}{}{Graffiti}
{103000}{}{Graffiti}
{103100}{}{Graffiti}
{103200}{}{Graffiti}
{103300}{}{Graffiti}
{103400}{}{Graffiti}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Graffiti}
{104800}{}{Graffiti}
{104900}{}{Graffiti}
{105000}{}{Graffiti}
{105100}{}{Graffiti}
{105200}{}{Graffiti}
{105300}{}{Graffiti}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Graffiti}
{105800}{}{Graffiti}
{105900}{}{Graffiti}
{106000}{}{Placa}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Graffiti}
{107200}{}{Graffiti}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Graffiti}
{108800}{}{Graffiti}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Graffiti}
{109900}{}{Graffiti}
{110000}{}{Graffiti}
{110100}{}{Graffiti}
{110200}{}{Graffiti}
{110300}{}{Graffiti}
{110400}{}{Graffiti}
{110500}{}{Graffiti}
{110600}{}{Graffiti}
{110700}{}{Graffiti}
{110800}{}{Graffiti}
{110900}{}{Graffiti}
{111000}{}{Placa}
{111100}{}{Placa}
{111200}{}{Placa}
{111300}{}{Placa}
{111400}{}{Placa}
{111500}{}{Placa}
{111600}{}{Placa}
{111700}{}{Placa}
{111800}{}{paredepaper}
{111900}{}{paredepaper}
{112000}{}{paredepaper}
{112100}{}{paredepaper}
{112200}{}{paredepaper}
{112300}{}{paredepaper}
{112400}{}{paredepaper}
{112500}{}{paredepaper}
{112600}{}{paredepaper}
{112700}{}{paredepaper}
{112800}{}{paredepaper}
{112900}{}{paredepaper}
{113000}{}{paredepaper}
{113100}{}{paredepaper}
{113200}{}{paredepaper}
{113300}{}{paredepaper}
{113400}{}{paredepaper}
{113500}{}{paredepaper}
{113600}{}{paredepaper}
{113700}{}{paredepaper}
{113800}{}{paredepaper}
{113900}{}{paredepaper}
{114000}{}{paredepaper}
{114100}{}{Câmera de filme}
{114200}{}{Caixão}
{114300}{}{Caixão}
{114400}{}{Caixão}
{114500}{}{Caixão}
{114600}{}{Steel Barraras}
{114700}{}{Steel Barraras}
{114800}{}{Steel Janela Tampa}
{114900}{}{Steel Janela Tampa}
{115000}{}{Laser Tripwire}
{115100}{}{Laser Tripwire}
{115200}{}{Mining Carrorororororororororot}
{115300}{}{Mining Carrorororororororororot with Steel Pólo}
{115400}{}{Mining Carrorororororororororot with Dynamite}
{115500}{}{"Out of Business" Placa}
{115600}{}{"Out of Business" Placa}
{115700}{}{Buckner House Placa}
{115800}{}{Vic's Placa}
{115900}{}{parede}
{116000}{}{parede}
{116100}{}{Scanner Retinal}
{116101}{}{Este é um dispositivo de segurança que varre o padrão retinal de uma pessoa.}
{116200}{}{Control Room Placa}
{116300}{}{Control Room Placa}
{116400}{}{Control Room Placa}
{116500}{}{Construction Zone Placa}
{116600}{}{Construction Zone Placa}
{116700}{}{Máquina}
{116701}{}{Uma máquina não funcional.}
{116800}{}{Máquina}
{116801}{}{Uma máquina não funcional.}
{116900}{}{Porta}
{117000}{}{Porta}
{117100}{}{Tubos}
{117101}{}{Um conjunto de tubos indo para o reator.}
{117200}{}{Tanque}
{117300}{}{Tanques}
{117400}{}{Tanques}
{117500}{}{Tanques}
{117600}{}{Vent}
{117700}{}{Vent}
{117800}{}{Harp Placa}
{117900}{}{Sawhorse}
{118000}{}{Sawhorse}
{118100}{}{Sawhorse}
{118200}{}{Vent}
{118300}{}{Vent}
{118400}{}{Máquina Shop Placa}
{118500}{}{Manager's Office Placa}
{118600}{}{Supply Room Placa}
{118700}{}{Radiation Warning Placa}
{118800}{}{Vapor}
{118900}{}{Máquina}
{118901}{}{Um misc. equipamento para a usina.}
{119000}{}{Tanque}
{119100}{}{Fogo}
{119200}{}{agua}
{119300}{}{Trapper Town Placa}
{119400}{}{Golden Gecko Placa}
{119500}{}{Bath House Placa}
{119600}{}{Arte da caverna}
{119700}{}{Arte da caverna}
{119800}{}{Arte da caverna}
{119900}{}{Arte da caverna}
{120000}{}{Fogopit}
{120100}{}{Cave parede}
{120200}{}{Cave parede}
{120300}{}{Cave parede}
{120400}{}{Cave parede}
{120500}{}{Cave parede}
{120600}{}{Cave parede}
{120700}{}{Cave parede}
{120800}{}{Cave parede}
{120900}{}{Cave parede}
{121000}{}{Cave parede}
{121100}{}{Cave parede}
{121200}{}{Cave parede}
{121300}{}{Cave parede}
{121400}{}{Cave parede}
{121500}{}{Cave parede}
{121600}{}{Estaca}
{121601}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{121700}{}{Estaca}
{121701}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{121800}{}{Estaca}
{121801}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{121900}{}{Estaca}
{121901}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{122000}{}{Estaca}
{122001}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{122100}{}{Estaca}
{122101}{}{Esta estaca parece ter uma pessoa empalada no topo!}
{122200}{}{Estaca}
{122201}{}{Esta estaca parece ter um crânio humano colocado no topo.}
{122300}{}{Estaca}
{122301}{}{Esta estaca parece ter um crânio humano colocado no topo.}
{122400}{}{Estaca}
{122401}{}{Esta estaca vazia parece pronta para uma vítima que não está disposta.}
{122500}{}{Estaca}
{122501}{}{Esta estaca vazia parece pronta para uma vítima que não está disposta.}
{122600}{}{Estaca}
{122601}{}{Esta estaca vazia parece pronta para uma vítima que não está disposta.}
{122700}{}{Estaca}
{122701}{}{Esta estaca vazia parece pronta para uma vítima que não está disposta.}
{122800}{}{Wanted Placa}
{122801}{}{A imagem deste sinal parece estranhamente como você!}
{122900}{}{Chão}
{123000}{}{Robobrain desativado}
{123001}{}{Um corpo cibernético incompleto que está faltando várias partes.}
{123100}{}{Howitzer}
{123101}{}{Este canhão de aparência estranha parece uma relíquia dos dias anteriores à guerra. Você se pergunta como isso acabou aqui.}
{123200}{}{Placa}
{123300}{}{Placa}
{123400}{}{Placa}
{123500}{}{Placa}
{123600}{}{Interruptor de energia}
{123700}{}{Cruz}
{123800}{}{Cruz}
{123900}{}{Cruz}
{124000}{}{Cruz}
{124100}{}{Cruz}
{124200}{}{Cruz}
{124300}{}{Bomba de gasolina}
{124400}{}{Bomba de gasolina}
{124500}{}{Bomba de gasolina}
{124600}{}{Pep Gas Placa}
{124700}{}{Placa Sombra}
{124800}{}{Haybed}
{124900}{}{Haybed}
{125000}{}{Haybed}
{125100}{}{Haybed}
{125200}{}{Haybed}
{125300}{}{Haybed}
{125400}{}{Dusty's Cantina Placa}
{125500}{}{Son of Bob's Store}
{125501}{}{Um vendedor de rua.}
{125600}{}{Son of Bob's Store}
{125601}{}{Um vendedor de rua.}
{125700}{}{Son of Bob's Store}
{125701}{}{Um vendedor de rua.}
{125800}{}{Son of Bob's Store}
{125801}{}{Um vendedor de rua.}
{125900}{}{NCR Placa}
{126000}{}{Hall of Congress Placa}
{126100}{}{Hall of Congress Placa}
{126200}{}{Cartaz NCR}
{126300}{}{Cartaz NCR}
{126400}{}{Cartaz NCR}
{126500}{}{Cartaz NCR}
{126600}{}{Rawhide Saloon Placa}
{126700}{}{Sinal de casino}
{126800}{}{Sinal de casino}
{126900}{}{Sinal de casino}
{127000}{}{Sinal de casino}
{127100}{}{Sinal de casino}
{127200}{}{Sinal de casino}
{127300}{}{Pile of Rochas}
{127301}{}{Essas rochas parecem estar mantendo alguma coisa.}
{127400}{}{Beam}
{127500}{}{Beam}
{127600}{}{Beam}
{127700}{}{Beam}
{127800}{}{Beam}
{127900}{}{Beam}
{128000}{}{Beam}
{128100}{}{Beam}
{128200}{}{Beam}
{128300}{}{Beam}
{128400}{}{Sombra}
{128500}{}{Sombra}
{128600}{}{Sombra}
{128700}{}{Sombra}
{128800}{}{Sombra}
{128900}{}{Sombra}
{129000}{}{Sombra}
{129100}{}{Sombra}
{129200}{}{Sombra}
{129300}{}{Elevador Stub}
{129400}{}{Bomba de gasolina}
{129500}{}{Bomba de gasolina}
{129600}{}{Bomba de gasolina}
{129700}{}{Corda}
{129800}{}{Buraco}
{129900}{}{Brahmin Carne}
{130000}{}{Brahmin Carne}
{130100}{}{Brahmin Carne}
{130200}{}{Brahmin Carne}
{130300}{}{Brahmin Carne}
{130400}{}{Brahmin Carne}
{130500}{}{Beam}
{130600}{}{Beam}
{130700}{}{Beam}
{130800}{}{Beam}
{130900}{}{Beam}
{131000}{}{Beam}
{131100}{}{Beam}
{131200}{}{Beam}
{131300}{}{Sombra}
{131400}{}{Sombra}
{131500}{}{Sombra}
{131600}{}{Sombra}
{131700}{}{Sombra}
{131800}{}{Sombra}
{131900}{}{Sombra}
{132000}{}{Sombra}
{132100}{}{Sangue}
{132200}{}{Sangue}
{132300}{}{Sangue}
{132400}{}{Sangue}
{132500}{}{Sangue}
{132600}{}{Sangue}
{132700}{}{Sangue with Ossos}
{132800}{}{Sangue with Ossos}
{132900}{}{Sangue with Ossos}
{133000}{}{Cave Boca}
{133100}{}{Equipamento Access}
{133200}{}{Equipamento Access}
{133300}{}{Equipamento Access}
{133400}{}{Equipamento Access}
{133500}{}{Computador}
{133501}{}{Um terminal de computador Vault, conectado ao computador principal do Vault.}
{133600}{}{Computador}
{133601}{}{Um terminal de computador Vault, conectado ao computador principal do Vault.}
{133700}{}{Vault City Portão}
{133800}{}{Vault City Portão}
{133900}{}{parede}
{134000}{}{parede}
{134100}{}{parede}
{134200}{}{parede}
{134300}{}{parede}
{134400}{}{parede}
{134500}{}{parede}
{134600}{}{parede}
{134700}{}{Porta}
{134800}{}{Blown Open Porta}
{134900}{}{Porta Debris}
{135000}{}{Construção}
{135100}{}{Construção}
{135200}{}{Construção}
{135300}{}{Construção}
{135400}{}{Construção}
{135500}{}{Construção}
{135600}{}{Construção}
{135700}{}{Construção}
{135800}{}{Porta}
{135900}{}{Templo}
{136000}{}{Templo}
{136100}{}{Templo}
{136200}{}{Templo}
{136300}{}{Templo}
{136400}{}{Templo}
{136500}{}{Fogopit}
{136600}{}{Fogopit}
{136700}{}{Howitizer}
{136701}{}{Este canhão de aparência estranha parece uma relíquia dos dias anteriores à guerra. Você se pergunta como isso acabou aqui.}
{136800}{}{Templo}
{136900}{}{Templo}
{137000}{}{Montanha}
{137100}{}{Caverna}
{137200}{}{Porta Rastrear}
{137300}{}{Tocha}
{137301}{}{Uma tocha acesa em um aplique de parede.}
{137400}{}{Tocha}
{137401}{}{Uma tocha acesa em um aplique de parede.}
{137500}{}{Tocha}
{137501}{}{Uma tocha acesa em um aplique de parede.}
{137600}{}{Tocha}
{137601}{}{Uma tocha acesa em um aplique de parede.}
{137700}{}{Vertibird}
{137701}{}{PRECISA DESCRIÇÃO LONGO.}
{137800}{}{Destroyed Porta}
{137801}{}{A porta da central elétrica é destruída.}
{137900}{}{Destroyed Porta}
{137901}{}{A porta da central elétrica é destruída.}
{138000}{}{parede}
{138100}{}{parede}
{138200}{}{parede}
{138300}{}{parede}
{138400}{}{parede}
{138500}{}{parede}
{138600}{}{Luz}
{138700}{}{Porta}
{138800}{}{Porta}
{138900}{}{Porta}
{139000}{}{Porta}
{139100}{}{Porta}
{139200}{}{Porta}
{139300}{}{Bandeira}
{139400}{}{Postarararar}
{139500}{}{Postarararar}
{139600}{}{Bandeira}
{139700}{}{Bandeira}
{139800}{}{Postarararar}
{139900}{}{Postarararar}
{140000}{}{Bandeira}
{140100}{}{Sombra}
{140200}{}{Sombra}
{140300}{}{Bandeira}
{140400}{}{Bandeira}
{140500}{}{Bandeira}
{140600}{}{Bandeira}
{140700}{}{Cat's Paw Placa}
{140800}{}{Cat's Paw Placa}
{140900}{}{Placa}
{141000}{}{Jungle Gym Placa}
{141100}{}{Jungle Gym Placa}
{141200}{}{Jungle Gym Placa}
{141300}{}{Renesco's Pharmacy Placa}
{141400}{}{New Reno Arms Placa}
{141500}{}{Salvatore's Barrara Placa}
{141600}{}{Estátua}
{141700}{}{Warehouse Porta}
{141800}{}{Warehouse Porta}
{141900}{}{Doc Johnson Placa}
{142000}{}{Sheriff Placa}
{142100}{}{Malamute Saloon Placa}
{142200}{}{Morningstar Mine Placa}
{142300}{}{Kokowebe Mine Placa}
{142400}{}{Kokowebe Mine Placa}
{142500}{}{Kokowebe Mine Placa}
{142600}{}{Placapost}
{142601}{}{Este sinal de madeira aponta para New Reno e "Hell". Você suspeita que as direções são revertidas.}
{142700}{}{Number 1 Placa}
{142800}{}{Number 2 Placa}
{142900}{}{Number 3 Placa}
{143000}{}{Number 4 Placa}
{143100}{}{Number 5 Placa}
{143200}{}{Number 6 Placa}
{143300}{}{Corda}
{143301}{}{Você pode escalar a parede com esta corda.}
{143400}{}{Porta}
{143500}{}{Porta}
{143600}{}{Janela}
{143700}{}{Janela}
{143800}{}{Janela}
{143900}{}{Janela}
{144000}{}{Janela}
{144100}{}{Janela}
{144200}{}{Janela}
{144300}{}{Janela}
{144400}{}{Janela}
{144500}{}{Janela}
{144600}{}{Janela}
{144700}{}{Janela}
{144800}{}{Pool Escada}
{144900}{}{Porta}
{145000}{}{Arco}
{145100}{}{Arco}
{145200}{}{Arco}
{145300}{}{Arco}
{145400}{}{Arco}
{145500}{}{Arco}
{145600}{}{Arco}
{145700}{}{Arco}
{145800}{}{Sombra}
{145900}{}{Sombra}
{146000}{}{Sombra}
{146100}{}{Arco}
{146200}{}{Arco}
{146300}{}{Arco}
{146400}{}{Sombra}
{146500}{}{Sombra}
{146600}{}{Cerca Porta}
{146700}{}{Cerca Porta}
{146800}{}{Assento de comando}
{146801}{}{É aqui que o Supervisor se senta normalmente.}
{146900}{}{Abismo}
{147000}{}{Abismo}
{147100}{}{Abismo}
{147200}{}{Abismo}
{147300}{}{Entrada de cassino}
{147400}{}{Entrada de cassino}
{147500}{}{Carrorororororororororopet}
{147600}{}{Entrada de cassino}
{147700}{}{Entrada de cassino}
{147800}{}{Entrada de cassino}
{147900}{}{Casino Porta}
{148000}{}{Casino Porta}
{148100}{}{Entrada de cassino}
{148200}{}{Entrada de cassino}
{148300}{}{Entrada de cassino}
{148400}{}{Entrada de cassino}
{148500}{}{Entrada de cassino}
{148600}{}{Entrada de cassino}
{148700}{}{Entrada de cassino}
{148800}{}{Entrada de cassino}
{148900}{}{Entrada de cassino}
{149000}{}{Entrada de cassino}
{149100}{}{Casino Porta}
{149200}{}{Casino Porta}
{149300}{}{parede Luz}
{149400}{}{parede Luz}
{149500}{}{parede Luz}
{149600}{}{parede Luz}
{149700}{}{parede Luz}
{149800}{}{parede}
{149900}{}{parede}
{150000}{}{Ventilador}
{150100}{}{Ventilador}
{150200}{}{Fogo Ext.}
{150300}{}{Fogo Ext.}
{150400}{}{Tubo}
{150500}{}{Distribuidor de energia}
{150600}{}{Distribuidor de energia}
{150700}{}{parede}
{150800}{}{parede}
{150900}{}{parede}
{151000}{}{parede}
{151100}{}{parede}
{151200}{}{parede}
{151300}{}{parede}
{151400}{}{parede}
{151500}{}{parede}
{151600}{}{Painel de madeira}
{151700}{}{Painel de madeira}
{151800}{}{Tubo}
{151900}{}{Tubo}
{152000}{}{Tubo}
{152100}{}{Tubo}
{152200}{}{Tubo}
{152300}{}{Tubo}
{152400}{}{Tubo}
{152500}{}{Tubo}
{152600}{}{Tubo}
{152700}{}{Tubo}
{152800}{}{Tubo}
{152900}{}{Saída de ar}
{153000}{}{Saída de ar}
{153100}{}{Porta}
{153200}{}{Porta}
{153300}{}{Porta}
{153400}{}{Porta}
{153500}{}{Porta}
{153600}{}{Porta}
{153700}{}{Chuveiro}
{153800}{}{Transporte parede}
{153900}{}{Transporte parede}
{154000}{}{Transporte parede}
{154100}{}{Transporte parede}
{154200}{}{Transporte parede}
{154300}{}{Transporte parede}
{154400}{}{Transporte parede}
{154500}{}{Transporte parede}
{154600}{}{Transporte parede}
{154700}{}{Transporte parede}
{154800}{}{Campo de força}
{154900}{}{Campo de força}
{155000}{}{Unidade de Extração de Órgãos}
{155001}{}{O modelo mais recente na série de cirurgia "Do It Yourself" da Vault-Tec. Remove os órgãos automaticamente com a pressão de um botão.}
{155100}{}{Transporte}
{155200}{}{Transporte}
{155300}{}{Transporte}
{155400}{}{Transporte}
{155500}{}{Transporte}
{155600}{}{Transporte}
{155700}{}{Transporte}
{155800}{}{Transporte}
{155900}{}{Transporte}
{156000}{}{Transporte}
{156100}{}{Transporte}
{156200}{}{Transporte}
{156300}{}{Transporte}
{156400}{}{Transporte}
{156500}{}{Transporte}
{156600}{}{Sombra}
{156700}{}{Sombra}
{156800}{}{Sombra}
{156900}{}{Sombra}
{157000}{}{Sombra}
{157100}{}{Sombra}
{157200}{}{Trono}
{157300}{}{Porta}
{157400}{}{Porta}
{157500}{}{Porta}
{157600}{}{Porta}
{157700}{}{Saída de ar}
{157800}{}{Auto-Doc}
{157801}{}{Este Auto-Doc é projetado para curar doenças e administração de vários chems.}
{157900}{}{Estátua}
{157901}{}{Uma pequena estátua do famoso Vault Dweller.}
{158000}{}{Pile of Rochas}
{158100}{}{Campo de força}
{158101}{}{Um campo de energia está bloqueando seu caminho.}
{158200}{}{Campo de força}
{158201}{}{Um campo de energia está bloqueando seu caminho.}
{158300}{}{Campo de força}
{158301}{}{Um campo de energia está bloqueando seu caminho.}
{158400}{}{Campo de força}
{158401}{}{Um campo de energia está bloqueando seu caminho.}
{158500}{}{Tanqueer}
{158600}{}{Tanqueer}
{158700}{}{Tanqueer}
{158800}{}{Tanqueer}
{158900}{}{Tanqueer}
{159000}{}{Tanqueer}
{159100}{}{Tanqueer}
{159200}{}{Tanqueer}
{159300}{}{Tanqueer}
{159400}{}{Tanqueer}
{159500}{}{Tanqueer}
{159600}{}{Tanqueer}
{159700}{}{Tanqueer}
{159800}{}{Tanqueer}
{159900}{}{Tanqueer}
{160000}{}{parede}
{160100}{}{parede}
{160200}{}{Chão Depression}
{160300}{}{Banco de Pedra}
{160400}{}{Banco de Pedra}
{160500}{}{Queimador de incenso}
{160600}{}{Antena parabólica}
{160700}{}{Antena parabólica}
{160800}{}{Sombra}
{160900}{}{Dock Sombra}
{161000}{}{Dock Sombra}
{161100}{}{Dock Sombra}
{161200}{}{Dock Sombra}
{161300}{}{Beam}
{161400}{}{Beam}
{161500}{}{Dock Sombra}
{161600}{}{Dock Sombra}
{161700}{}{Dock Sombra}
{161800}{}{Dock Sombra}
{161900}{}{Escadas}
{162000}{}{Desativado Cyberdog}
{162001}{}{Você vê um Cyberdog desativado.}
{162100}{}{Destroyed Gerador de energia}
{162101}{}{Você vê um gerador de energia destruído.}
{162200}{}{Rastrear}
{162300}{}{Rastrear}
{162400}{}{Rastrear}
{162500}{}{Mine Carrorororororororororot}
{162600}{}{Mine Carrorororororororororot with Steel Pólo}
{162700}{}{Mine Carrorororororororororot with Dynamite}
{162800}{}{Destroyed Mine Carrorororororororororot}
{162900}{}{Mine Carrorororororororororot}
{163000}{}{Pool Mesa}
{163100}{}{Pool Mesa}
{163200}{}{Pool Mesa}
{163300}{}{Pool Mesa}
{163400}{}{Pool Mesa}
{163500}{}{Pool Mesa}
{163600}{}{Escrivaninha}
{163700}{}{Bandeira}
{163800}{}{parede}
{163900}{}{parede}
{164000}{}{parede}
{164100}{}{parede}
{164200}{}{Porto de escape}
{164300}{}{Escrivaninha}
{164400}{}{Escrivaninha}
{164500}{}{Escadas Down}
{164600}{}{Escadas Up}
{164700}{}{Escadas Up}
{164800}{}{Escadas Up}
{164900}{}{Mainframe Computador}
{165000}{}{Mainframe Computador}
{165100}{}{Mainframe Computador}
{165200}{}{Carrorororororororororoavan Office Placa}
{165300}{}{Caixão Mesa}
{165400}{}{Caixão Mesa}
{165500}{}{Mine Elevador}
{165600}{}{Mine Elevador}
{165700}{}{Bandeirapole}
{165800}{}{NCR Bandeira}
{165900}{}{Poseidon Gasoline Placa}
{166000}{}{Escadas Down}
{166100}{}{Clinic Placa}
{166200}{}{Corrections Center Placa}
{166300}{}{Customs Placa}
{166400}{}{Customs Placa}
{166500}{}{Greeting Office Placa}
{166600}{}{Happy Harry's Placa}
{166700}{}{The Buraco Placa}
{166800}{}{Information Center Placa}
{166900}{}{Information Center Placa}
{167000}{}{Logotipo da cidade de Vault}
{167100}{}{Main Council Placa}
{167200}{}{Main Council Placa}
{167300}{}{Centro de manutenção}
{167400}{}{Parlor Room Placa}
{167500}{}{Tap House Placa}
{167600}{}{Westin Ranch Placa}
{167700}{}{Amenities Placa}
{167800}{}{Construção A Placa}
{167900}{}{Construção B Placa}
{168000}{}{Centro de Alocação de Servidores}
{168100}{}{Centro de Alocação de Servidores}
{168200}{}{Amenities Office Placa}
{168300}{}{Amenities Office Placa}
{168400}{}{Mine Elevador}
{168500}{}{Mine Elevador}
{168600}{}{Mine Elevador}
{168700}{}{Mine Elevador}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Sombra}
{169400}{}{Sombra}
{169500}{}{Sombra}
{169600}{}{Sombra}
{169700}{}{Vertibird Crashed}
{169800}{}{Vertibird Crashed}
{169900}{}{Vertibird Crashed}
{170000}{}{Vertibird Crashed}
{170100}{}{Vertibird Crashed}
{170200}{}{Vertibird Crashed}
{170300}{}{Sombra}
{170400}{}{Sombra}
{170500}{}{Sombra}
{170600}{}{Ponte destruída}
{170601}{}{Você vê o que resta da ponte Arroyo. Não há como voltar para a aldeia agora.}
{170700}{}{Ponte destruída}
{170701}{}{Você vê o que resta da ponte Arroyo. Não há como voltar para a aldeia agora.}
{170800}{}{Canyon}
{170900}{}{Porta}
{171000}{}{Porta}
{171100}{}{parede}
{171200}{}{parede}
{171300}{}{parede}
{171400}{}{parede}
{171500}{}{parede}
{171600}{}{parede}
{171700}{}{parede}
{171800}{}{parede}
{171900}{}{Saída de ar}
{172000}{}{Saída de ar}
{172100}{}{Vidro a prova de balas}
{172200}{}{Vidro a prova de balas}
{172300}{}{Vidro a prova de balas}
{172400}{}{Torreta de laser pesado}
{172500}{}{Torreta de laser pesado}
{172600}{}{Rochas}
{172700}{}{Rochas}
{172800}{}{Rochas}
{172900}{}{Rochas}
{173000}{}{Rochas}
{173100}{}{Rochas}
{173200}{}{Rochas}
{173300}{}{Rochas}
{173400}{}{Rochas}
{173500}{}{Rochas}
{173600}{}{Rochas}
{173700}{}{Becky's Sinal de casino}
{173800}{}{Becky's Placa}
{173900}{}{Last Gasp Saloon Placa}
{174000}{}{Mom's Diner Placa}
{174100}{}{Slaver's Guild Placa}
{174200}{}{Survival/Gear Locker Placa}
{174300}{}{Tubby's Placa}
{174400}{}{Tubby's Placa}
{174500}{}{Mine Elevador Portão}
{174600}{}{Ventilador}
{174700}{}{Ventilador}
{174800}{}{President's Office Porta}
{174900}{}{Gráfico de olho}
{175000}{}{Ruínas}
{175100}{}{Guardião de Forever}
{175200}{}{Out of Order Placa}
{175300}{}{Collapsed Chão}
{175400}{}{Banheiro}
{175500}{}{Cruz}
{175600}{}{parede}
{175700}{}{parede}
{175800}{}{parede}
{175900}{}{parede}
{176000}{}{parede}
{176100}{}{parede}
{176200}{}{parede}
{176300}{}{parede}
{176400}{}{Construção}
{176500}{}{Construção}
{176600}{}{Construção}
{176700}{}{Construção}
{176800}{}{Construção}
{176900}{}{Construção}
{177000}{}{Suportes de aço}
{177100}{}{Suportes de aço}
{177200}{}{Suportes de aço}
{177300}{}{agua}
{177400}{}{agua}
{177500}{}{agua}
{177600}{}{agua}
{177700}{}{agua}
{177800}{}{agua}
{177900}{}{aguafall}
{178000}{}{Estrada}
{178100}{}{Estrada}
{178200}{}{Estrada}
{178300}{}{Estrada}
{178400}{}{Estrada}
{178500}{}{Estrada}
{178600}{}{Estrada}
{178700}{}{Suporte de ponte}
{178800}{}{Suporte de ponte}
{178900}{}{Suporte de ponte}
{179000}{}{Cerca}
{179100}{}{Luminária}
{179200}{}{Luminária}
{179300}{}{Baleia morta}
{179301}{}{Esta baleia parecia ter caído de uma grande altura.}
{179400}{}{Baleia morta}
{179401}{}{Esta baleia parecia ter caído de uma grande altura.}
{179500}{}{Barbatana}
{179501}{}{A barbatana de uma baleia morta.}
{179600}{}{Olho de baleia}
{179601}{}{O olho de uma baleia morta.}
{179700}{}{Pedaço de baleia}
{179701}{}{Um pedaço de baleia!}
{179800}{}{Pedaço de baleia}
{179801}{}{Um pedaço de baleia!}
{179900}{}{Pedaço de baleia}
{179901}{}{Um pedaço de baleia!}
{180000}{}{Pedaço de baleia}
{180001}{}{Um pedaço de baleia!}
{180100}{}{Pedaço de baleia}
{180101}{}{Um pedaço de baleia!}
{180200}{}{Pernas de patrão}
{180300}{}{Rochas}
{180400}{}{Rochas}
{180500}{}{Rochas}
{180600}{}{Rochas}
{180700}{}{Tannery Placa}
{180800}{}{Rose's B&B Placa}
{180900}{}{Vortis Holding Placa}
{181000}{}{Vortis Holding Placa}
{181100}{}{Great Wamamingo Mine Placa}
{181200}{}{Ascorti's Placa}
{181300}{}{Crashed Transporte}
{181301}{}{Um veículo espacial de algum tipo. Parece que ele caiu recentemente.}
{181400}{}{Caixão}
{181500}{}{Stockman's Assoc. Placa}
{181600}{}{Slaughter-House Placa}
{181700}{}{Prancha}
{181800}{}{Wood Porta}
{181900}{}{Wood Porta}
{182000}{}{Refrigerador de cola}
{182100}{}{Refrigerador de cola}
{182200}{}{Fogão}
{182300}{}{Fogão}
{182400}{}{Fogão}
{182500}{}{Fogão}
{182600}{}{Coisa}
{182700}{}{Coisa}
{182800}{}{Coisa}
{182900}{}{Coisa}
{183000}{}{Coisa}
{183100}{}{Coisa}
{183200}{}{Coisa}
{183300}{}{Coisa}
{183400}{}{President's Cadeira}
{183500}{}{Escadas}
{183600}{}{Mapa mundial}
{183700}{}{Mapa de Situação}
{183800}{}{War Room Mesa}
{183900}{}{Council Room Mesa}
{184000}{}{Council Room Mesa}
{184100}{}{War Room Mesa}
{184200}{}{Árvore}
{184300}{}{Árvore}
{184400}{}{Rampa}
{184500}{}{Golden Globes Porn Placa}
{184600}{}{Roda do navio}
{184700}{}{Controle de velocidade do navio}
{184800}{}{Estação Comm}
{184900}{}{Computador Console}
{185000}{}{Viewport Shutters}
{185100}{}{Vapor}
