{100}{}{Herói macho}
{101}{}{}
{200}{}{Herói Feminino}
{201}{}{}
{300}{}{Aldeão}
{400}{}{Aldeão}
{500}{}{Radscorpion}
{501}{}{Um pequeno escorpião mutado.}
{600}{}{Radscorpion}
{601}{}{Um escorpião mutado.}
{700}{}{Deathclaw}
{701}{}{Uma Deathclaw imaturo.}
{800}{}{Deathclaw}
{801}{}{Uma Deathclaw imaturo.}
{900}{}{Cachorro}
{901}{}{Um canino, provavelmente de uma raça mista.}
{1000}{}{brâmane}
{1001}{}{Uma vaca mutante de duas cabeças.}
{1100}{}{Rato}
{1101}{}{Um grande rato típico.}
{1200}{}{louva a Deus}
{1201}{}{A mutated louva a Deus.}
{1300}{}{Mais velho}
{1400}{}{Hakunin}
{1500}{}{Mynoc}
{1600}{}{Planta de Spore}
{1601}{}{Uma planta carnívora.}
{1700}{}{Slave bonito}
{1800}{}{Escravo bonito}
{1900}{}{Escravo saudável}
{2000}{}{Escravo saudável}
{2100}{}{Escravo forte}
{2200}{}{Escravo forte}
{2300}{}{Escravo de combate}
{2400}{}{Escravo de combate}
{2500}{}{Escravo Inteligente}
{2600}{}{Escravo Inteligente}
{2700}{}{Escravo Genérico}
{2800}{}{Escravo Genérico}
{2900}{}{Anna}
{3000}{}{Tug Thug}
{3100}{}{Tug Thug}
{3200}{}{Longe de corpo a corpo}
{3300}{}{Longe de corpo a corpo}
{3400}{}{Águia águia}
{3500}{}{Águia águia}
{3600}{}{Lagarta}
{3700}{}{Lagarta}
{3800}{}{Big Lagarta}
{3900}{}{Big Lagarta}
{4000}{}{Tough Guard}
{4100}{}{Tough Guard}
{4200}{}{Guarda corpo a corpo}
{4300}{}{Guarda corpo a corpo}
{4400}{}{Agile Guard}
{4500}{}{Agile Guard}
{4600}{}{Guarda de armas}
{4700}{}{Guarda de armas}
{4800}{}{Big Guarda de armas}
{4900}{}{Big Guarda de armas}
{5000}{}{Órfão (Masculino)}
{5100}{}{Órfão (Feminino)}
{5200}{}{Criança (Masculino)}
{5300}{}{Criança (Feminino)}
{5400}{}{Fracassado}
{5500}{}{Fracassado}
{5600}{}{Comerciante ruim}
{5700}{}{Comerciante ruim}
{5800}{}{Comerciante médio}
{5900}{}{Comerciante médio}
{6000}{}{Master Trader}
{6100}{}{Master Trader}
{6200}{}{Vic}
{6300}{}{Camponês fraco}
{6400}{}{Camponês fraco}
{6500}{}{Camponês médio}
{6600}{}{Camponês médio}
{6700}{}{Camponês forte}
{6800}{}{Camponês forte}
{6900}{}{Weak Guarda corpo a corpo}
{7000}{}{Weak Guarda corpo a corpo}
{7100}{}{Weak Guarda de armas}
{7200}{}{Weak Guarda de armas}
{7300}{}{Repair Bot}
{7400}{}{Reparar Bot Mark II}
{7500}{}{Robobrain}
{7600}{}{Botão de olho flutuante}
{7700}{}{Sentry Bot}
{7800}{}{Sentry Bot Mark II}
{7900}{}{Robobrain}
{8000}{}{Little Gecko}
{8100}{}{Tough Lil Gecko}
{8200}{}{Wild Cachorro}
{8201}{}{Um cão feral de raça mista.}
{8300}{}{Golden Gecko}
{8400}{}{Deathclaw}
{8500}{}{Deathclaw Spawn}
{8600}{}{Gecko dourado resistente}
{8700}{}{Lynette}
{8800}{}{Dr. Troy}
{8900}{}{John Cassidy}
{9000}{}{Gregory}
{9100}{}{Cidadão (Feminino)}
{9200}{}{Cidadão (Masculino)}
{9300}{}{Up Class Citizen (F)}
{9400}{}{Up Class Citizen (M)}
{9500}{}{Caçador}
{9600}{}{Caçador}
{9700}{}{Sulik}
{9800}{}{Maida Buckner}
{9900}{}{Torr}
{10000}{}{Grumoso}
{10100}{}{Reactor Incandescente}
{10200}{}{Reator Ghoul}
{10300}{}{Protetor de Reator}
{10400}{}{Zomak}
{10500}{}{Skeeter}
{10600}{}{O cérebro}
{10700}{}{Lenny}
{10800}{}{Wooz}
{10900}{}{Harold}
{11000}{}{Rato toupeirao}
{11100}{}{Greater Rato toupeirao}
{11200}{}{Rato de porcoo}
{11300}{}{Tough Rato de porcoo}
{11400}{}{Weak brâmane}
{11401}{}{Uma vaca mutante de duas cabeças.}
{11500}{}{A.Pwr.Armor (não use)}
{11600}{}{Rato Mutatedo}
{11601}{}{Um rato mutante resistente.}
{11700}{}{Rato Mutatedo toupeirao}
{11701}{}{Um rato mole mutante resistente.}
{11800}{}{Rato Mutatedo de porcoo}
{11801}{}{Um rato de porco mutante resistente.}
{11900}{}{Super Mutant}
{12000}{}{Poderoso mutante}
{12100}{}{Melchoir}
{12200}{}{Hero Andro (não use)}
{12300}{}{Hero Andro (não use)}
{12400}{}{Herói macho (don't use)}
{12500}{}{Herói Feminino (don't use)}
{12600}{}{Herói macho (don't use)}
{12700}{}{Herói Feminino (don't use)}
{12800}{}{Herói macho (don't use)}
{12900}{}{Herói Feminino (don't use)}
{13000}{}{Herói macho (don't use)}
{13100}{}{Herói Feminino (don't use)}
{13200}{}{Herói macho (don't use)}
{13300}{}{Herói Feminino (don't use)}
{13400}{}{Vault City Guard}
{13500}{}{Vault City Guard}
{13600}{}{Cyberdog}
{13700}{}{NCR Guard}
{13800}{}{NCR Guard}
{13900}{}{NCR Guarda corpo a corpo}
{14000}{}{Slaver Guard}
{14100}{}{Slaver Overseer}
{14200}{}{Grand Master Trader}
{14300}{}{Grand Master Trader}
{14400}{}{Tandi}
{14500}{}{Merc}
{14600}{}{Ratoch}
{14700}{}{Skeeter}
{14800}{}{Mikey}
{14900}{}{NCR Barman}
{15000}{}{Dono da loja}
{15100}{}{Gruthar}
{15200}{}{Goris}
{15300}{}{Molerat Fighter}
{15400}{}{Molerat Fighter}
{15500}{}{Molerat Fighter}
{15600}{}{Molerat Fighter}
{15700}{}{Molerat Fighter}
{15800}{}{Molerat Fighter}
{15900}{}{Ghoul Genérico}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Doc Jones}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Rapaz}
{16600}{}{Rondó}
{16700}{}{Mão do rancho}
{16800}{}{Mão do rancho}
{16900}{}{Mão do rancho}
{17000}{}{Bouncer}
{17100}{}{Bouncer}
{17200}{}{Fraco Mr. Handy}
{17300}{}{Generic Glowing One}
{17400}{}{Dar}
{17500}{}{Dalia}
{17600}{}{Gordon}
{17700}{}{teste (não use)}
{17800}{}{Reator Ghoul}
{17900}{}{Ghoul Genérico}
{18000}{}{Matt}
{18100}{}{B. Hunter Lead (1-6)}
{18200}{}{Caçador de recompensas (1-6)}
{18300}{}{B. Hunter Lead (7-12)}
{18400}{}{Bounty Hunter (7-12)}
{18500}{}{Bounty Hunter (7-12)}
{18600}{}{B. Hunter Lead (13-18)}
{18700}{}{Caçador de recompensas (13-18)}
{18800}{}{Caçador de recompensas (13-18)}
{18900}{}{B. Hunter Lead (19-?)}
{19000}{}{Bounty Hunter (19-?)}
{19100}{}{Bess}
{19101}{}{Uma vaca mutante de duas cabeças.}
{19200}{}{Balthas}
{19300}{}{Grisham}
{19400}{}{Phil}
{19500}{}{Frango}
{19600}{}{Karl}
{19700}{}{Jonny}
{19800}{}{Jo}
{19900}{}{Zeke}
{20000}{}{açougueiro}
{20100}{}{Petey}
{20200}{}{Caçador primitivo}
{20300}{}{Caçador primitivo}
{20400}{}{Canibal}
{20500}{}{Canibal}
{20600}{}{Homem sagrado}
{20700}{}{Santa mulher}
{20800}{}{Nomad-Low}
{20900}{}{Nomad-Med}
{21000}{}{Nomad-Low}
{21100}{}{Nomad-Med}
{21200}{}{Bandido}
{21300}{}{Bandido}
{21400}{}{Agricultor}
{21500}{}{Agricultor}
{21600}{}{louva a Deus}
{21700}{}{Slaver}
{21800}{}{Slaver}
{21900}{}{Wild brâmane}
{22000}{}{Homesteader}
{22100}{}{Homesteader}
{22200}{}{Vault City Patrol}
{22300}{}{Vault City Patrol}
{22400}{}{Escravo forter}
{22500}{}{Escravo forter}
{22600}{}{Loucos}
{22700}{}{Scavengers}
{22800}{}{Glow Loucos}
{22900}{}{Gladiadores}
{23000}{}{Pescador}
{23100}{}{Mulher de pesca}
{23200}{}{mais selvagem}
{23300}{}{mais selvagem}
{23400}{}{Bootlegger}
{23500}{}{Bootlegger}
{23600}{}{Prospector}
{23700}{}{Prospector}
{23800}{}{Corsário}
{23900}{}{Corsário}
{24000}{}{Fire Gecko}
{24100}{}{Teck Fire Gecko}
{24200}{}{Estrangeiro}
{24300}{}{Tough Estrangeiro}
{24400}{}{Sm Death Death}
{24500}{}{Trombo da morte}
{24600}{}{Flutuante}
{24700}{}{Nasty Flutuante}
{24800}{}{Centauro}
{24900}{}{Mean Centauro}
{25000}{}{Enclave Patrol}
{25100}{}{Enclave Patrol}
{25200}{}{Gang da imprensa}
{25300}{}{Gang da imprensa}
{25400}{}{Mercenário}
{25500}{}{Mercenário}
{25600}{}{Nightkin}
{25700}{}{Tough Nightkin}
{25800}{}{Ghoul Tough}
{25900}{}{Mafioso}
{26000}{}{Yakuza}
{26100}{}{NCR Ranger}
{26200}{}{NCR Ranger}
{26300}{}{Maurader}
{26400}{}{Maurader}
{26500}{}{Pretty Boy Lloyd}
{26600}{}{Rato Vorpalo}
{26700}{}{Vault 13 Man}
{26800}{}{Vault 13 Woman}
{26900}{}{Bridge Guardian}
{27000}{}{Misterioso estranho}
{27100}{}{Misterioso estranho}
{27200}{}{Hakeswill}
{27300}{}{Big Jesus Mordino}
{27400}{}{Dumar}
{27500}{}{Mãe Deathclaw}
{27600}{}{O Dragão}
{27700}{}{Lo Pan}
{27800}{}{Hubologist}
{27900}{}{Hubologist}
{28000}{}{Misterioso estranho}
{28100}{}{Misterioso estranho}
{28200}{}{Misterioso estranho}
{28300}{}{Misterioso estranho}
{28400}{}{Misterioso estranho}
{28500}{}{Misterioso estranho}
{28600}{}{Misterioso estranho}
{28700}{}{Misterioso estranho}
{28800}{}{Pres. Escolta}
{28900}{}{Ovo Deathclaw}
{29000}{}{Metzger}
{29100}{}{Enclave Guard}
{29200}{}{Enclave Guard}
{29300}{}{Presidente}
{29400}{}{Vice presidentee}
{29500}{}{Technicion}
{29600}{}{Texugo}
{29700}{}{Dr. Fung}
{29800}{}{Criança}
{29900}{}{Criança}
{30000}{}{Gun Merchant}
{30100}{}{Shi Lab Tech}
{30200}{}{Shi Guard}
{30300}{}{Shi Camponês}
{30400}{}{Shi Camponês}
{30500}{}{Lo Pan Camponês}
{30600}{}{Lo Pan Camponês}
{30700}{}{Dock Worker}
{30800}{}{Shi Merchant}
{30900}{}{Keeng Ra'at}
{31000}{}{Sulik - Estágio 1}
{31100}{}{Sulik - Estágio 2}
{31200}{}{Sulik - Estágio 3}
{31300}{}{Sulik - Stage 4}
{31400}{}{Sulik - Fase 5}
{31500}{}{Sulik - Estágio 6}
{31600}{}{Lenny - Estágio 1}
{31700}{}{Lenny - Estágio 2}
{31800}{}{Lenny - Estágio 3}
{31900}{}{Goris - Estágio 1}
{32000}{}{Goris - Estágio 2}
{32100}{}{Goris - Estágio 3}
{32200}{}{Goris - Estágio 4}
{32300}{}{Goris - Stage 5}
{32400}{}{Goris - Estágio 6}
{32500}{}{Myron - Estágio 1}
{32600}{}{Myron - Estágio 2}
{32700}{}{Myron - Estágio 3}
{32800}{}{Myron - Estágio 4}
{32900}{}{Marcus - Stage 1}
{33000}{}{Marcus - Stage 2}
{33100}{}{Marcus - Stage 3}
{33200}{}{Marcus - Stage 4}
{33300}{}{Marcus - Stage 5}
{33400}{}{Cyberdog - Estágio 1}
{33500}{}{Cyberdog - Estágio 2}
{33600}{}{Cyberdog - Estágio 3}
{33700}{}{Cyberdog - Stage 4}
{33800}{}{Cassidy - Estágio 1}
{33900}{}{Cassidy - Estágio 2}
{34000}{}{Cassidy - Estágio 3}
{34100}{}{Cassidy - Estágio 4}
{34200}{}{Cachorromeat}
{34300}{}{Cachorromeat - Stage 1}
{34400}{}{Cachorromeat - Stage 2}
{34500}{}{Cachorromeat - Stage 3}
{34600}{}{Cachorromeat - Stage 4}
{34700}{}{Cachorromeat - Stage 5}
{34800}{}{Cachorromeat - Stage 6}
{34900}{}{Robobrain - Estágio 1}
{35000}{}{Robobrain - Estágio 2}
{35100}{}{Robobrain - Estágio 3}
{35200}{}{Robobrain - Fase 4}
{35300}{}{Robobrain - Estágio 5}
{35400}{}{Queen Estrangeiro}
{35500}{}{Black Radscorpion}
{35600}{}{Black Radscorpion}
{35700}{}{Spud}
{35800}{}{Mercenário Captain}
{35900}{}{Mercenário}
{36000}{}{Mercenário}
{36100}{}{Shadow-Who-Walks}
{36200}{}{Punk}
{36300}{}{Punk}
{36400}{}{Marc}
{36500}{}{Dave H.}
{36600}{}{Capitão A. Ron Meyers}
{36700}{}{Lasca}
{36800}{}{AHS-9}
{36900}{}{Guarda Hubologist}
{37000}{}{Guarda Hubologist}
{37100}{}{Juan}
{37200}{}{Vikki}
{37300}{}{Vic - Estágio 1}
{37400}{}{Vic - Estágio 2}
{37500}{}{Vic - Estágio 3}
{37600}{}{Vic - Estágio 4}
{37700}{}{Vic - Estágio 5}
{37800}{}{Vic - Estágio 6}
{37900}{}{RoboBrain - Chimpanzé}
{38000}{}{Robobrain - Anormal}
{38100}{}{Robobrain - Humano}
{38200}{}{Formiga gigante}
{38300}{}{Tough Formiga gigante}
{38400}{}{Pariah Cachorro}
{38500}{}{Zurak}
{38600}{}{Imbot}
{38700}{}{Jimmy}
{38800}{}{Wejungh}
{38900}{}{Erva}
{39000}{}{Loopal}
{39100}{}{Jobe}
{39200}{}{Smitty}
{39300}{}{Rube}
{39400}{}{Mestre Krall}
{39500}{}{Ziggy}
{39600}{}{Master Khung}
{39700}{}{John Bishop}
{39800}{}{Angela Bishop}
{39900}{}{Sra. Bishop}
{40000}{}{Guarda do Bispo 1}
{40100}{}{Bishop's Guarda 2}
{40200}{}{Bisoto 1 do bispo}
{40300}{}{Bishop's Thug 2}
{40400}{}{Angry brâmane}
{40500}{}{Lil 'Jesus}
{40600}{}{Big Jesus}
{40700}{}{Mordino Men 1}
{40800}{}{Mordino Men 2}
{40900}{}{Mordino Men 3}
{41000}{}{Myron's Guarda 1}
{41100}{}{Myron's Guarda 2}
{41200}{}{Sr. Wright}
{41300}{}{Sra. Wright}
{41400}{}{Chris Wright}
{41500}{}{Keith Wright}
{41600}{}{Wright Son 1}
{41700}{}{Wright Son 2}
{41800}{}{Wright Daughter 1}
{41900}{}{Wright Daughter 2}
{42000}{}{Sr. Salvatore}
{42100}{}{Pedreiro}
{42200}{}{Salvatore Thug 1}
{42300}{}{Salvatore Thug 2}
{42400}{}{Genérico Barman 1}
{42500}{}{Generic Barman 2}
{42600}{}{Genérico Barman 3}
{42700}{}{Boxer 1}
{42800}{}{Boxer 2}
{42900}{}{Boxer 3}
{43000}{}{Boxer 4}
{43100}{}{Mike the Masticator}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Stuart Little}
{43500}{}{Irmãos da Córsega}
{43600}{}{Cadelas corsas}
{43700}{}{Padre Tully}
{43800}{}{Casino Bouncer 1}
{43900}{}{Casino Bouncer 2}
{44000}{}{Casino Girl}
{44100}{}{Drug Dealer / Pimp1}
{44200}{}{Drug Dealer / Pimp2}
{44300}{}{Drug Dealer / Pimp3}
{44400}{}{Drug Dealer / Pimp4}
{44500}{}{McGee}
{44600}{}{Miss Kitty}
{44700}{}{Slut genérico 1}
{44800}{}{Genéricos Slut 2}
{44900}{}{Jagged Jimmy J}
{45000}{}{Renesco}
{45100}{}{Cientista}
{45200}{}{Eldridge}
{45300}{}{Algernon}
{45400}{}{Jules}
{45500}{}{Burocrata 1}
{45600}{}{Burocrata 2}
{45700}{}{Comerciante 1}
{45800}{}{Trader 2}
{45900}{}{Guarda 1}
{46000}{}{Guarda 2}
{46100}{}{Guarda 3}
{46200}{}{Guarda 4}
{46300}{}{Soldado 1}
{46400}{}{Soldado 2}
{46500}{}{Soldier 3}
{46600}{}{Soldado 4}
{46700}{}{Sargento. Rígido}
{46800}{}{"Doc" Andrew}
{46900}{}{Barman}
{47000}{}{Torre de armas}
{47001}{}{Esta é uma torre de pistão automatizada equipada com um Dual Plasma Cannon.}
{47100}{}{K-9 (base)}
{47200}{}{K-9 (fase 1)}
{47300}{}{K-9 (fase 2)}
{47400}{}{K-9 (fase 3)}
{47500}{}{K-9 (fase 4)}
{47600}{}{Genéricos Cyberdog}
{47700}{}{Wanamingo Egg}
{47800}{}{Lo Pan Guard}
{47900}{}{Marjorie}
{48000}{}{Auto-Cannon}
{48100}{}{Especial Gecko Critter}
{48200}{}{Ceifador}
{48300}{}{Frank Horrigan}
{48301}{}{The Presidente's Body Guard}
