{100}{}{Parede de aço}
{200}{}{Parede de aço}
{300}{}{Parede de aço}
{400}{}{Parede de aço}
{500}{}{Parede de aço}
{600}{}{Parede de aço}
{700}{}{Parede de aço}
{800}{}{Parede de aço}
{900}{}{Parede de aço}
{1000}{}{Parede de aço}
{1100}{}{Parede de aço}
{1200}{}{Parede de aço}
{1300}{}{Parede de aço}
{1400}{}{Parede de aço}
{1500}{}{Parede de aço}
{1600}{}{Parede de aço}
{1700}{}{Parede de aço}
{1800}{}{Parede de aço}
{1801}{}{}
{1900}{}{Parede de aço Corner}
{2000}{}{Parede de aço Corner}
{2100}{}{Parede de aço Corner}
{2200}{}{Parede de aço Corner}
{2300}{}{Parede de aço}
{2400}{}{Parede de aço}
{2500}{}{Parede de aço Corner}
{2600}{}{Parede de aço}
{2700}{}{Parede de aço}
{2800}{}{Parede de aço Corner}
{2900}{}{Parede de aço}
{3000}{}{Parede de aço}
{3001}{}{}
{3100}{}{Parede T de aço}
{3200}{}{Parede T de aço}
{3300}{}{Parede T de aço}
{3400}{}{Parede de 4 vias de aço}
{3500}{}{Parede de aço End}
{3600}{}{Parede de aço End}
{3700}{}{Parede de aço End}
{3800}{}{Parede de aço End}
{3900}{}{Porta de entrada}
{4000}{}{Porta de entrada}
{4100}{}{Porta de entrada}
{4200}{}{Porta de entrada}
{4300}{}{Porta de entrada}
{4400}{}{Porta de entrada}
{4500}{}{Porta de entrada}
{4600}{}{Porta de entrada}
{4700}{}{Porta de entrada}
{4800}{}{Porta de entrada}
{4900}{}{Porta de entrada}
{5000}{}{parede}
{5100}{}{parede}
{5200}{}{parede}
{5300}{}{parede}
{5400}{}{parede}
{5500}{}{Janela de aço}
{5600}{}{Tubo}
{5700}{}{Tubo}
{5800}{}{Tubo}
{5900}{}{Equipamento}
{5901}{}{}
{6000}{}{Tubos}
{6100}{}{Tubo}
{6200}{}{Tubo}
{6300}{}{Tubo}
{6400}{}{Tubo}
{6500}{}{Tubo}
{6600}{}{Tubo}
{6700}{}{Tubos}
{6800}{}{Tubos}
{6900}{}{Tubos}
{7000}{}{Tubo}
{7100}{}{Tubo}
{7200}{}{Tubo}
{7300}{}{Tubo}
{7400}{}{Tubo}
{7500}{}{Equipamento}
{7501}{}{}
{7600}{}{Tubos}
{7700}{}{Equipamento}
{7701}{}{}
{7800}{}{Tubo}
{7900}{}{Tubos}
{8000}{}{Tubos}
{8100}{}{Tubo}
{8200}{}{Tubos}
{8300}{}{Tubo}
{8400}{}{Tubo}
{8500}{}{Gizmo}
{8600}{}{Cerca de madeira}
{8700}{}{Cerca de madeira}
{8800}{}{Cerca de madeira}
{8900}{}{Cerca de madeira}
{9000}{}{Cerca de madeira}
{9100}{}{Cerca de madeira}
{9200}{}{parede}
{9300}{}{parede}
{9400}{}{parede}
{9500}{}{parede}
{9600}{}{Tin parede}
{9700}{}{Tin parede}
{9800}{}{Wooden parede}
{9900}{}{Wooden parede}
{10000}{}{Tin parede}
{10100}{}{Tin parede}
{10200}{}{Wooden parede}
{10300}{}{Wooden parede}
{10400}{}{Tin Porta de entrada}
{10500}{}{Tin Porta de entrada}
{10600}{}{Tin Porta de entrada}
{10700}{}{Tin Porta de entrada}
{10800}{}{Parede de aço}
{10900}{}{Parede de aço}
{11000}{}{Wooden parede}
{11100}{}{Wooden parede}
{11200}{}{Tin parede}
{11300}{}{Wooden parede}
{11400}{}{Wooden parede}
{11500}{}{Wooden parede}
{11600}{}{Wooden parede}
{11700}{}{Wooden parede}
{11800}{}{Wooden parede}
{11900}{}{Wooden parede}
{12000}{}{Wooden parede}
{12100}{}{Wooden parede}
{12200}{}{Wooden parede}
{12300}{}{Janela}
{12400}{}{Wooden parede}
{12500}{}{Wooden parede}
{12600}{}{Wooden parede}
{12700}{}{Wooden parede}
{12800}{}{Wooden parede}
{12900}{}{Wooden parede}
{13000}{}{Wooden parede}
{13100}{}{Wooden Porta de entrada}
{13200}{}{Wooden Porta de entrada}
{13300}{}{Tin parede}
{13400}{}{Tin parede}
{13500}{}{parede}
{13600}{}{Tin parede}
{13700}{}{Tin parede}
{13800}{}{Tin parede}
{13900}{}{Tin parede}
{14000}{}{Tin parede}
{14100}{}{Cerca de madeira}
{14200}{}{Cerca de madeira}
{14300}{}{Cerca de madeira}
{14400}{}{Cerca de madeira}
{14500}{}{Cerca de madeira}
{14600}{}{Cerca de madeira}
{14700}{}{Cerca de madeira}
{14800}{}{Cerca de madeira}
{14900}{}{Cerca de madeira}
{15000}{}{Cerca de madeira}
{15100}{}{Cerca de madeira}
{15200}{}{Cerca de madeira}
{15300}{}{Tin parede}
{15400}{}{Tin parede}
{15500}{}{Stone parede}
{15600}{}{Stone Porta de entrada}
{15700}{}{Stone Porta de entrada}
{15800}{}{Stone parede}
{15900}{}{Stone parede}
{16000}{}{Stone parede}
{16100}{}{Barrararararararararararararararararararararagem em aço}
{16200}{}{Barrararararararararararararararararararararagem em aço}
{16300}{}{Barrararararararararararararararararararararagem em aço}
{16400}{}{Barrararararararararararararararararararararagem em aço}
{16500}{}{Barrararararararararararararararararararararagem em aço}
{16600}{}{Barrararararararararararararararararararararagem em aço}
{16700}{}{Barrararararararararararararararararararararagem em aço}
{16800}{}{Barrararararararararararararararararararararagem em aço}
{16900}{}{Barrararararararararararararararararararararagem em aço}
{17000}{}{Barrararararararararararararararararararararagem em aço}
{17100}{}{Barrararararararararararararararararararararagem em aço}
{17200}{}{Barrararararararararararararararararararararagem em aço}
{17300}{}{Barrararararararararararararararararararararagem em aço}
{17400}{}{Cave parede}
{17500}{}{Cave parede}
{17600}{}{Cave parede}
{17700}{}{Cave parede}
{17800}{}{Cave parede}
{17900}{}{Cave parede}
{18000}{}{Cave parede}
{18100}{}{Cave parede}
{18200}{}{Cave parede}
{18300}{}{Cave parede}
{18400}{}{Cave parede}
{18500}{}{Cave parede}
{18600}{}{Cave parede}
{18700}{}{Cave parede}
{18800}{}{Cave parede}
{18900}{}{Cave parede}
{19000}{}{Cave parede}
{19100}{}{Cave parede}
{19200}{}{Cave parede}
{19300}{}{Cave parede}
{19400}{}{Cave parede}
{19500}{}{Cave parede}
{19600}{}{Cave parede}
{19700}{}{Cave parede}
{19800}{}{Cave parede}
{19900}{}{Cave parede}
{20000}{}{Cave parede}
{20100}{}{Cave parede}
{20200}{}{Cave parede}
{20300}{}{Cave parede}
{20400}{}{Cave parede}
{20500}{}{Cave parede}
{20600}{}{Cave parede}
{20700}{}{Cave parede}
{20800}{}{Cave parede}
{20900}{}{Cave parede}
{21000}{}{Cave parede}
{21100}{}{Cave parede}
{21200}{}{Cave parede}
{21300}{}{Cave parede}
{21400}{}{Cave parede}
{21500}{}{Cave parede}
{21600}{}{Cave parede}
{21700}{}{Cave parede}
{21800}{}{Cave parede}
{21900}{}{Cave parede}
{22000}{}{Cave parede}
{22100}{}{Cave parede}
{22200}{}{Cave parede}
{22300}{}{Cave parede}
{22400}{}{Cave parede}
{22500}{}{Cave parede}
{22600}{}{Cave parede}
{22700}{}{Cave parede}
{22800}{}{Cave parede}
{22900}{}{Cave parede}
{23000}{}{Cave parede}
{23100}{}{Cave parede}
{23200}{}{Cave parede}
{23300}{}{Cave parede}
{23400}{}{Cave parede}
{23500}{}{Cave parede}
{23600}{}{Cave parede}
{23700}{}{Cave parede}
{23800}{}{Cave parede}
{23900}{}{Cave parede}
{24000}{}{Cave parede}
{24100}{}{Cave parede}
{24200}{}{Cave parede}
{24300}{}{Cave parede}
{24400}{}{Wooden parede}
{24500}{}{Wooden parede}
{24600}{}{Wooden parede}
{24700}{}{Wooden parede}
{24800}{}{Wooden parede}
{24900}{}{Wooden parede}
{25000}{}{Wooden parede}
{25100}{}{}
{25200}{}{parede}
{25300}{}{parede}
{25400}{}{parede}
{25500}{}{parede}
{25600}{}{parede}
{25700}{}{parede}
{25800}{}{parede}
{25900}{}{parede}
{26000}{}{parede}
{26100}{}{parede}
{26200}{}{parede}
{26300}{}{parede}
{26400}{}{parede}
{26500}{}{parede}
{26600}{}{parede}
{26700}{}{parede}
{26800}{}{parede}
{26900}{}{parede}
{27000}{}{parede}
{27100}{}{parede}
{27200}{}{parede}
{27300}{}{parede}
{27400}{}{parede}
{27500}{}{parede}
{27600}{}{parede}
{27700}{}{parede}
{27800}{}{parede}
{27900}{}{parede}
{28000}{}{}
{28100}{}{parede}
{28200}{}{parede}
{28300}{}{parede}
{28400}{}{parede}
{28500}{}{parede}
{28600}{}{parede}
{28700}{}{parede}
{28800}{}{parede}
{28900}{}{parede}
{29000}{}{parede}
{29100}{}{parede}
{29200}{}{parede}
{29300}{}{parede}
{29400}{}{parede}
{29500}{}{parede}
{29600}{}{parede}
{29700}{}{parede}
{29800}{}{parede}
{29900}{}{parede}
{30000}{}{parede}
{30100}{}{parede}
{30200}{}{parede}
{30300}{}{parede}
{30400}{}{parede}
{30500}{}{parede}
{30600}{}{parede}
{30700}{}{parede}
{30800}{}{parede}
{30900}{}{parede}
{31000}{}{parede}
{31100}{}{parede}
{31200}{}{parede}
{31300}{}{parede}
{31400}{}{parede}
{31500}{}{parede}
{31600}{}{parede}
{31700}{}{parede}
{31800}{}{parede}
{31900}{}{parede}
{32000}{}{parede}
{32100}{}{parede}
{32200}{}{parede}
{32300}{}{parede}
{32400}{}{parede}
{32500}{}{parede}
{32600}{}{parede}
{32700}{}{parede}
{32800}{}{parede}
{32900}{}{parede}
{33000}{}{parede}
{33100}{}{parede}
{33200}{}{parede}
{33300}{}{parede}
{33400}{}{parede}
{33500}{}{parede}
{33600}{}{parede}
{33700}{}{parede}
{33800}{}{parede}
{33900}{}{parede}
{34000}{}{parede}
{34100}{}{parede}
{34200}{}{parede}
{34300}{}{parede}
{34400}{}{parede}
{34500}{}{parede}
{34600}{}{parede}
{34700}{}{parede}
{34800}{}{parede}
{34900}{}{parede}
{35000}{}{parede}
{35100}{}{parede}
{35200}{}{parede}
{35300}{}{parede}
{35400}{}{parede}
{35500}{}{parede}
{35600}{}{parede}
{35700}{}{parede}
{35800}{}{parede}
{35900}{}{parede}
{36000}{}{parede}
{36100}{}{parede}
{36200}{}{parede}
{36300}{}{parede}
{36400}{}{parede}
{36500}{}{parede}
{36600}{}{Wooden parede}
{36700}{}{Wooden parede}
{36800}{}{parede}
{36900}{}{parede}
{37000}{}{parede}
{37100}{}{parede}
{37200}{}{parede}
{37300}{}{parede}
{37400}{}{parede}
{37500}{}{parede}
{37600}{}{parede}
{37700}{}{parede}
{37800}{}{parede}
{37900}{}{parede}
{38000}{}{parede}
{38100}{}{parede}
{38200}{}{parede}
{38300}{}{parede}
{38400}{}{parede}
{38500}{}{parede}
{38600}{}{parede}
{38700}{}{parede}
{38800}{}{parede}
{38900}{}{parede}
{39000}{}{parede}
{39100}{}{parede}
{39200}{}{parede}
{39300}{}{parede}
{39400}{}{parede}
{39500}{}{parede}
{39600}{}{parede}
{39700}{}{parede}
{39800}{}{parede}
{39900}{}{parede}
{40000}{}{parede}
{40100}{}{parede}
{40200}{}{parede}
{40300}{}{parede}
{40400}{}{parede}
{40500}{}{parede}
{40600}{}{parede}
{40700}{}{parede}
{40800}{}{parede}
{40900}{}{parede}
{41000}{}{parede}
{41100}{}{parede}
{41200}{}{parede}
{41300}{}{parede}
{41400}{}{parede}
{41500}{}{parede}
{41600}{}{parede}
{41700}{}{parede}
{41800}{}{parede}
{41900}{}{Wooden parede}
{42000}{}{Wooden parede}
{42100}{}{Wooden parede}
{42200}{}{parede}
{42300}{}{parede}
{42400}{}{parede}
{42500}{}{parede}
{42600}{}{parede}
{42700}{}{parede}
{42800}{}{parede}
{42900}{}{parede}
{43000}{}{parede}
{43100}{}{parede}
{43200}{}{parede}
{43300}{}{parede}
{43400}{}{parede}
{43500}{}{parede}
{43600}{}{parede}
{43700}{}{parede}
{43800}{}{parede}
{43900}{}{parede}
{44000}{}{parede}
{44100}{}{parede}
{44200}{}{parede}
{44300}{}{parede}
{44400}{}{parede}
{44500}{}{parede}
{44600}{}{parede}
{44700}{}{parede}
{44800}{}{parede}
{44900}{}{parede}
{45000}{}{parede}
{45100}{}{parede}
{45200}{}{parede}
{45300}{}{parede}
{45400}{}{parede}
{45500}{}{parede}
{45600}{}{parede}
{45700}{}{parede}
{45800}{}{parede}
{45900}{}{parede}
{46000}{}{parede}
{46100}{}{parede}
{46200}{}{parede}
{46300}{}{parede}
{46400}{}{parede}
{46500}{}{parede}
{46600}{}{parede}
{46700}{}{Barrararararararararararararararararararara}
{46800}{}{Barrararararararararararararararararararara}
{46900}{}{Barrararararararararararararararararararara}
{47000}{}{Barrararararararararararararararararararara}
{47100}{}{Barrararararararararararararararararararara}
{47200}{}{Barrararararararararararararararararararara}
{47300}{}{Barrararararararararararararararararararara}
{47400}{}{Barrararararararararararararararararararara}
{47500}{}{Barrararararararararararararararararararara}
{47600}{}{Barrararararararararararararararararararara}
{47700}{}{Barrararararararararararararararararararara}
{47800}{}{Barrararararararararararararararararararara}
{47900}{}{Barrararararararararararararararararararara}
{48000}{}{Barrararararararararararararararararararara}
{48100}{}{Barrararararararararararararararararararara}
{48200}{}{Barrararararararararararararararararararara}
{48300}{}{Barrararararararararararararararararararara}
{48400}{}{Barrararararararararararararararararararara}
{48500}{}{Barrararararararararararararararararararara}
{48600}{}{Barrararararararararararararararararararara}
{48700}{}{Cerca de madeira}
{48800}{}{Cerca de madeira}
{48900}{}{Moldura da porta}
{49000}{}{Moldura da porta}
{49100}{}{Moldura da porta}
{49200}{}{Moldura da porta}
{49300}{}{Moldura da porta}
{49400}{}{Moldura da porta}
{49500}{}{Moldura da porta}
{49600}{}{parede}
{49700}{}{parede}
{49800}{}{parede}
{49900}{}{parede}
{50000}{}{parede}
{50100}{}{parede}
{50200}{}{parede}
{50300}{}{parede}
{50400}{}{parede}
{50500}{}{parede}
{50600}{}{parede}
{50700}{}{parede}
{50800}{}{parede}
{50900}{}{parede}
{51000}{}{parede}
{51100}{}{parede}
{51200}{}{parede}
{51300}{}{parede}
{51400}{}{parede}
{51500}{}{parede}
{51600}{}{parede}
{51700}{}{parede}
{51800}{}{parede}
{51900}{}{parede}
{52000}{}{parede}
{52100}{}{parede}
{52200}{}{parede}
{52300}{}{parede}
{52400}{}{parede}
{52500}{}{parede}
{52600}{}{parede}
{52700}{}{parede}
{52800}{}{parede}
{52900}{}{parede}
{53000}{}{parede}
{53100}{}{parede}
{53200}{}{parede}
{53300}{}{parede}
{53400}{}{parede}
{53500}{}{parede}
{53600}{}{parede}
{53700}{}{parede}
{53800}{}{parede}
{53900}{}{parede}
{54000}{}{parede}
{54100}{}{parede}
{54200}{}{parede}
{54300}{}{parede}
{54400}{}{parede}
{54500}{}{parede}
{54600}{}{parede}
{54700}{}{parede}
{54800}{}{parede}
{54900}{}{parede}
{55000}{}{parede}
{55100}{}{parede}
{55200}{}{parede}
{55300}{}{parede}
{55400}{}{parede}
{55500}{}{parede}
{55600}{}{parede}
{55700}{}{parede}
{55800}{}{parede}
{55900}{}{parede}
{56000}{}{parede}
{56100}{}{parede}
{56200}{}{Porta de entrada}
{56300}{}{Porta de entrada}
{56400}{}{Janela}
{56500}{}{parede}
{56600}{}{parede}
{56700}{}{parede}
{56800}{}{parede}
{56900}{}{parede}
{57000}{}{parede}
{57100}{}{parede}
{57200}{}{parede}
{57300}{}{parede}
{57400}{}{parede}
{57500}{}{parede}
{57600}{}{parede}
{57700}{}{parede}
{57800}{}{parede}
{57900}{}{parede}
{58000}{}{Porta de entrada}
{58100}{}{parede}
{58200}{}{Porta de entrada}
{58300}{}{Porta de entrada}
{58400}{}{Janela}
{58500}{}{parede}
{58600}{}{parede}
{58700}{}{parede}
{58800}{}{parede}
{58900}{}{parede}
{59000}{}{parede}
{59100}{}{parede}
{59200}{}{parede}
{59300}{}{parede}
{59400}{}{parede}
{59500}{}{parede}
{59600}{}{parede}
{59700}{}{parede}
{59800}{}{parede}
{59900}{}{parede}
{60000}{}{parede}
{60100}{}{parede}
{60200}{}{parede}
{60300}{}{parede}
{60400}{}{parede}
{60500}{}{parede}
{60600}{}{parede}
{60700}{}{parede}
{60800}{}{parede}
{60900}{}{parede}
{61000}{}{parede}
{61100}{}{parede}
{61200}{}{parede}
{61300}{}{parede}
{61400}{}{parede}
{61500}{}{parede}
{61600}{}{parede}
{61700}{}{parede}
{61800}{}{parede}
{61900}{}{parede}
{62000}{}{parede}
{62100}{}{parede}
{62200}{}{parede s.t.}
{62300}{}{parede}
{62400}{}{parede}
{62500}{}{parede}
{62600}{}{parede}
{62700}{}{parede}
{62800}{}{parede}
{62900}{}{parede}
{63000}{}{parede}
{63100}{}{parede}
{63200}{}{parede}
{63300}{}{parede}
{63400}{}{parede}
{63500}{}{parede}
{63600}{}{parede}
{63700}{}{parede}
{63800}{}{Janela}
{63900}{}{Janela}
{64000}{}{Janela}
{64100}{}{Janela}
{64200}{}{Janela}
{64300}{}{Janela}
{64400}{}{Janela}
{64500}{}{Janela}
{64600}{}{parede}
{64700}{}{parede}
{64800}{}{parede}
{64900}{}{parede}
{65000}{}{parede}
{65100}{}{parede}
{65200}{}{parede}
{65300}{}{parede}
{65400}{}{parede}
{65500}{}{parede}
{65600}{}{parede}
{65700}{}{parede}
{65800}{}{parede}
{65900}{}{parede}
{66000}{}{Porta de entrada}
{66100}{}{Porta de entrada}
{66200}{}{Porta de entrada}
{66300}{}{Porta de entrada}
{66400}{}{Janela}
{66500}{}{Janela}
{66600}{}{parede}
{66700}{}{parede}
{66800}{}{parede}
{66900}{}{parede}
{67000}{}{parede}
{67100}{}{parede}
{67200}{}{parede}
{67300}{}{parede}
{67400}{}{parede}
{67500}{}{parede}
{67600}{}{parede}
{67700}{}{parede}
{67800}{}{parede}
{67900}{}{parede}
{68000}{}{parede}
{68100}{}{parede}
{68200}{}{parede}
{68300}{}{parede}
{68400}{}{parede}
{68500}{}{parede}
{68600}{}{parede}
{68700}{}{parede}
{68800}{}{parede}
{68900}{}{parede}
{69000}{}{parede}
{69100}{}{parede}
{69200}{}{parede}
{69300}{}{parede}
{69400}{}{parede}
{69500}{}{parede}
{69600}{}{parede}
{69700}{}{parede}
{69800}{}{parede}
{69900}{}{parede}
{70000}{}{parede}
{70100}{}{Porta de entrada}
{70200}{}{parede}
{70300}{}{Porta de entrada}
{70400}{}{Porta de entrada}
{70500}{}{Porta de entrada}
{70600}{}{parede}
{70700}{}{Porta de entrada}
{70800}{}{Porta de entrada}
{70900}{}{Porta de entrada}
{71000}{}{Porta de entrada}
{71100}{}{parede}
{71200}{}{parede}
{71300}{}{parede}
{71400}{}{parede}
{71500}{}{parede}
{71600}{}{parede}
{71700}{}{parede}
{71800}{}{parede}
{71900}{}{parede}
{72000}{}{parede}
{72100}{}{parede}
{72200}{}{parede}
{72300}{}{parede}
{72400}{}{parede}
{72500}{}{parede}
{72600}{}{parede}
{72700}{}{parede}
{72800}{}{Wooden parede}
{72900}{}{parede}
{73000}{}{parede}
{73100}{}{parede}
{73200}{}{parede}
{73300}{}{parede}
{73400}{}{parede}
{73500}{}{parede}
{73600}{}{parede}
{73700}{}{parede}
{73800}{}{parede}
{73900}{}{parede}
{74000}{}{parede}
{74100}{}{parede}
{74200}{}{Porta de entrada}
{74300}{}{Porta de entrada}
{74400}{}{Porta de entrada}
{74500}{}{Porta de entrada}
{74600}{}{parede}
{74700}{}{Porta de entrada}
{74800}{}{parede}
{74900}{}{parede}
{75000}{}{parede}
{75100}{}{parede}
{75200}{}{parede}
{75300}{}{parede}
{75400}{}{parede}
{75500}{}{parede}
{75600}{}{parede}
{75700}{}{parede}
{75800}{}{parede}
{75900}{}{parede}
{76000}{}{parede}
{76100}{}{parede}
{76200}{}{parede}
{76300}{}{parede}
{76400}{}{parede}
{76500}{}{parede}
{76600}{}{parede}
{76700}{}{parede}
{76800}{}{parede}
{76900}{}{parede}
{77000}{}{parede}
{77100}{}{parede}
{77200}{}{parede}
{77300}{}{parede}
{77400}{}{parede}
{77500}{}{parede}
{77600}{}{parede}
{77700}{}{parede}
{77800}{}{parede}
{77900}{}{parede}
{78000}{}{parede}
{78100}{}{parede}
{78200}{}{parede}
{78300}{}{parede}
{78400}{}{parede}
{78500}{}{parede}
{78600}{}{parede}
{78700}{}{parede}
{78800}{}{parede}
{78900}{}{parede}
{79000}{}{Porta de entrada}
{79100}{}{Porta de entrada}
{79200}{}{Porta de entrada}
{79300}{}{Porta de entrada}
{79400}{}{Porta de entrada}
{79500}{}{Porta de entrada}
{79600}{}{Porta de entrada}
{79700}{}{Porta de entrada}
{79800}{}{Porta de entrada}
{79900}{}{Porta de entrada}
{80000}{}{Cerca}
{80100}{}{Cerca}
{80200}{}{Cerca}
{80300}{}{Cerca}
{80400}{}{Cerca}
{80500}{}{Cerca}
{80600}{}{Cerca}
{80700}{}{Cerca}
{80800}{}{Cerca}
{80900}{}{Cerca}
{81000}{}{Cerca}
{81100}{}{Cerca}
{81200}{}{Cerca}
{81300}{}{Cerca}
{81400}{}{Cerca}
{81500}{}{Cerca}
{81600}{}{Cerca}
{81700}{}{Cerca}
{81800}{}{Cerca}
{81900}{}{Cerca}
{82000}{}{Cerca}
{82100}{}{Cerca}
{82200}{}{Cerca}
{82300}{}{Cerca}
{82400}{}{parede}
{82500}{}{parede}
{82600}{}{Arco}
{82700}{}{Arco}
{82800}{}{Arco}
{82900}{}{Arco}
{83000}{}{Arco}
{83100}{}{Arco}
{83200}{}{Arco}
{83300}{}{Arco}
{83400}{}{parede}
{83500}{}{parede}
{83600}{}{parede}
{83700}{}{parede}
{83800}{}{parede}
{83900}{}{Janela}
{84000}{}{Janela}
{84100}{}{Janela}
{84200}{}{Janela}
{84300}{}{parede}
{84400}{}{Pilar}
{84500}{}{Porta de entrada}
{84600}{}{Porta de entrada}
{84700}{}{parede}
{84800}{}{parede}
{84900}{}{parede}
{85000}{}{parede}
{85100}{}{parede}
{85200}{}{Porta de entrada}
{85300}{}{Porta de entrada}
{85400}{}{Porta de entrada}
{85500}{}{Porta de entrada}
{85600}{}{parede}
{85700}{}{parede}
{85800}{}{parede}
{85900}{}{parede}
{86000}{}{Porta de entrada}
{86100}{}{Porta de entrada}
{86200}{}{parede}
{86300}{}{parede}
{86400}{}{parede}
{86500}{}{parede}
{86600}{}{parede}
{86700}{}{parede}
{86800}{}{parede}
{86900}{}{Porta de entrada}
{87000}{}{Porta de entrada}
{87100}{}{parede}
{87200}{}{parede}
{87300}{}{Porta de entrada}
{87400}{}{Porta de entrada}
{87500}{}{parede}
{87600}{}{parede}
{87700}{}{parede}
{87800}{}{parede}
{87900}{}{parede}
{88000}{}{parede}
{88100}{}{parede}
{88101}{}{parede}
{88200}{}{parede}
{88201}{}{parede}
{88300}{}{parede}
{88400}{}{parede}
{88500}{}{parede}
{88600}{}{parede}
{88700}{}{parede}
{88800}{}{parede}
{88900}{}{parede}
{89000}{}{parede}
{89100}{}{parede}
{89200}{}{parede}
{89300}{}{parede}
{89400}{}{parede}
{89500}{}{parede}
{89600}{}{parede}
{89700}{}{parede}
{89800}{}{parede}
{89900}{}{parede}
{90000}{}{parede}
{90100}{}{parede}
{90200}{}{parede}
{90300}{}{parede}
{90400}{}{parede}
{90500}{}{parede}
{90600}{}{parede}
{90700}{}{parede}
{90800}{}{parede}
{90900}{}{parede}
{91000}{}{parede}
{91100}{}{parede}
{91200}{}{parede}
{91300}{}{parede}
{91400}{}{parede}
{91500}{}{parede}
{91600}{}{parede}
{91700}{}{parede}
{91800}{}{parede}
{91900}{}{parede}
{92000}{}{parede}
{92100}{}{parede}
{92200}{}{parede}
{92300}{}{parede}
{92400}{}{parede}
{92500}{}{parede}
{92600}{}{parede}
{92700}{}{parede}
{92800}{}{parede}
{92900}{}{parede}
{93000}{}{parede}
{93100}{}{parede}
{93200}{}{parede}
{93300}{}{parede}
{93400}{}{parede}
{93500}{}{parede}
{93600}{}{parede}
{93700}{}{parede}
{93800}{}{parede}
{93900}{}{parede}
{94000}{}{parede}
{94100}{}{parede}
{94200}{}{parede}
{94300}{}{parede}
{94400}{}{parede}
{94500}{}{parede}
{94600}{}{parede}
{94700}{}{parede}
{94800}{}{parede}
{94900}{}{parede}
{95000}{}{parede}
{95100}{}{parede}
{95200}{}{parede}
{95300}{}{parede}
{95400}{}{parede}
{95500}{}{parede}
{95600}{}{parede}
{95700}{}{Cerca}
{95800}{}{Cerca}
{95900}{}{Cerca}
{96000}{}{Cerca}
{96100}{}{Cerca}
{96200}{}{Cerca}
{96300}{}{Cerca}
{96400}{}{Cerca}
{96500}{}{Cerca}
{96600}{}{Cerca}
{96700}{}{Cerca}
{96800}{}{Cerca}
{96900}{}{Cerca}
{97000}{}{Cerca}
{97100}{}{Cerca}
{97200}{}{Cerca}
{97300}{}{Cerca}
{97400}{}{Cerca}
{97500}{}{Cerca}
{97600}{}{Cerca}
{97700}{}{Caminhão}
{97800}{}{Caminhão}
{97900}{}{Caminhão}
{98000}{}{Caminhão}
{98100}{}{Caminhão}
{98200}{}{Caminhão}
{98300}{}{Caminhão}
{98400}{}{Caminhão}
{98500}{}{Caminhão}
{98600}{}{Caminhão}
{98700}{}{Caminhão}
{98800}{}{Cave parede}
{98900}{}{parede}
{99000}{}{parede}
{99100}{}{parede}
{99200}{}{parede}
{99300}{}{parede}
{99400}{}{parede}
{99500}{}{parede}
{99600}{}{parede}
{99700}{}{parede}
{99800}{}{parede}
{99900}{}{parede}
{100000}{}{parede}
{100100}{}{parede}
{100200}{}{parede}
{100300}{}{parede}
{100400}{}{parede}
{100500}{}{parede}
{100600}{}{parede}
{100700}{}{parede}
{100800}{}{parede}
{100900}{}{parede}
{101000}{}{parede}
{101100}{}{parede}
{101200}{}{parede}
{101300}{}{parede}
{101400}{}{parede}
{101500}{}{parede}
{101600}{}{parede}
{101700}{}{parede}
{101800}{}{Porta de entrada}
{101900}{}{parede}
{102000}{}{Porta de entrada}
{102100}{}{Porta de entrada}
{102200}{}{Dooway}
{102300}{}{parede}
{102400}{}{parede}
{102500}{}{parede}
{102600}{}{parede}
{102700}{}{parede}
{102800}{}{parede}
{102900}{}{parede}
{103000}{}{parede}
{103100}{}{parede}
{103200}{}{parede}
{103300}{}{Porta de entrada}
{103400}{}{Porta de entrada}
{103500}{}{Porta de entrada}
{103600}{}{Porta de entrada}
{103700}{}{Porta de entrada}
{103800}{}{Porta de entrada}
{103900}{}{parede}
{104000}{}{parede}
{104100}{}{parede}
{104200}{}{parede}
{104300}{}{parede}
{104400}{}{parede}
{104500}{}{parede}
{104600}{}{parede}
{104700}{}{parede}
{104800}{}{parede}
{104900}{}{parede}
{105000}{}{parede}
{105100}{}{parede}
{105200}{}{parede}
{105300}{}{parede}
{105400}{}{parede}
{105500}{}{parede}
{105600}{}{parede}
{105700}{}{parede}
{105800}{}{parede}
{105900}{}{parede}
{106000}{}{parede}
{106100}{}{parede}
{106200}{}{Porta de entrada}
{106300}{}{Porta de entrada}
{106400}{}{parede}
{106500}{}{parede}
{106600}{}{parede}
{106700}{}{parede}
{106800}{}{parede}
{106900}{}{parede}
{107000}{}{parede}
{107100}{}{parede}
{107200}{}{parede}
{107300}{}{parede}
{107400}{}{parede}
{107500}{}{parede}
{107600}{}{parede}
{107700}{}{parede}
{107800}{}{parede}
{107900}{}{parede}
{108000}{}{parede}
{108100}{}{parede}
{108200}{}{parede}
{108300}{}{parede}
{108400}{}{parede}
{108500}{}{parede}
{108600}{}{parede}
{108700}{}{parede}
{108800}{}{parede}
{108900}{}{parede}
{109000}{}{parede}
{109100}{}{parede}
{109200}{}{parede}
{109300}{}{parede}
{109400}{}{parede}
{109500}{}{parede}
{109600}{}{parede}
{109700}{}{parede}
{109800}{}{parede}
{109900}{}{parede}
{110000}{}{parede}
{110100}{}{parede}
{110200}{}{parede}
{110300}{}{parede}
{110400}{}{parede}
{110500}{}{parede}
{110600}{}{parede}
{110700}{}{parede}
{110800}{}{parede}
{110900}{}{parede}
{111000}{}{parede}
{111100}{}{parede}
{111200}{}{parede}
{111300}{}{parede}
{111400}{}{parede}
{111500}{}{parede}
{111600}{}{parede}
{111700}{}{parede}
{111800}{}{parede}
{111900}{}{parede}
{112000}{}{parede}
{112100}{}{parede}
{112200}{}{parede}
{112300}{}{parede}
{112400}{}{parede}
{112500}{}{parede}
{112600}{}{parede}
{112700}{}{Porta de entrada}
{112800}{}{parede}
{112900}{}{parede}
{113000}{}{Porta de entrada}
{113100}{}{parede}
{113200}{}{Porta de entrada}
{113300}{}{Porta de entrada}
{113400}{}{Porta de entrada}
{113500}{}{Forcefield Emitter}
{113600}{}{Forcefield Emitter}
{113700}{}{Forcefield Emitter}
{113800}{}{Forcefield Emitter}
{113900}{}{parede}
{114000}{}{parede}
{114100}{}{parede}
{114200}{}{parede}
{114300}{}{parede}
{114400}{}{Tanque de água}
{114401}{}{}
{114500}{}{Tanque de água}
{114501}{}{}
{114600}{}{Tanque de água}
{114601}{}{}
{114700}{}{Tanque de água}
{114701}{}{}
{114800}{}{Tanque de água}
{114801}{}{}
{114900}{}{Tanque de água}
{114901}{}{}
{115000}{}{Tanque de água}
{115001}{}{}
{115100}{}{Tanque de água}
{115200}{}{Tanque de água}
{115300}{}{Tanque de água}
{115400}{}{parede}
{115500}{}{Entrada destruída}
{115600}{}{Entrada destruída}
{115700}{}{parede}
{115800}{}{parede}
{115900}{}{parede}
{116000}{}{parede}
{116100}{}{parede}
{116200}{}{parede}
{116300}{}{parede}
{116400}{}{parede}
{116500}{}{parede}
{116600}{}{parede}
{116700}{}{parede}
{116800}{}{parede}
{116900}{}{parede}
{117000}{}{parede}
{117100}{}{parede}
{117200}{}{parede}
{117300}{}{parede}
{117400}{}{Porta de entrada}
{117500}{}{Porta de entrada}
{117600}{}{Porta de entrada}
{117700}{}{parede}
{117800}{}{parede}
{117900}{}{parede}
{118000}{}{parede}
{118100}{}{parede}
{118200}{}{parede}
{118300}{}{parede}
{118400}{}{parede}
{118500}{}{parede}
{118600}{}{parede}
{118700}{}{parede}
{118800}{}{parede}
{118900}{}{parede}
{119000}{}{parede}
{119100}{}{parede}
{119200}{}{parede}
{119300}{}{parede}
{119400}{}{parede}
{119500}{}{parede}
{119600}{}{parede}
{119700}{}{parede}
{119800}{}{parede}
{119900}{}{parede}
{120000}{}{parede}
{120100}{}{Trilhos}
{120200}{}{Trilhos}
{120300}{}{Trilhos}
{120400}{}{Trilhos}
{120500}{}{Trilhos}
{120600}{}{Trilhos}
{120700}{}{Trilhos}
{120800}{}{Trilhos}
{120900}{}{Trilhos}
{121000}{}{Trilhos}
{121100}{}{Trilhos}
{121200}{}{Trilhos}
{121300}{}{Trilhos}
{121400}{}{Trilhos}
{121500}{}{Trilhos}
{121600}{}{Trilhos}
{121700}{}{Trilhos}
{121800}{}{Trilhos}
{121900}{}{Trilhos}
{122000}{}{Trilhos}
{122100}{}{Trilhos}
{122200}{}{Trilhos}
{122300}{}{Trilhos}
{122400}{}{Trilhos}
{122500}{}{Trilhos}
{122600}{}{Trilhos}
{122700}{}{Porta de entrada}
{122800}{}{Porta de entrada}
{122900}{}{Coluna}
{123000}{}{parede}
{123100}{}{parede}
{123200}{}{parede}
{123300}{}{parede}
{123400}{}{parede}
{123500}{}{parede}
{123600}{}{parede}
{123700}{}{parede}
{123800}{}{Porta de entrada}
{123900}{}{Porta de entrada}
{124000}{}{Porta de entrada}
{124100}{}{Porta de entrada}
{124200}{}{Suporte de madeira}
{124300}{}{Suporte de madeira}
{124400}{}{Suporte de madeira}
{124500}{}{Suporte de madeira}
{124600}{}{Suporte de madeira}
{124700}{}{Suporte de madeira}
{124800}{}{Suporte de madeira}
{124900}{}{Suporte de madeira}
{125000}{}{Suporte de madeira}
{125100}{}{Suporte de madeira}
{125200}{}{Suporte de madeira}
{125300}{}{parede}
{125400}{}{parede}
{125500}{}{parede}
{125600}{}{parede}
{125700}{}{Porta de entrada}
{125800}{}{Porta de entrada}
{125900}{}{Porta de entrada}
{126000}{}{Porta de entrada}
{126100}{}{Porta de entrada}
{126200}{}{Porta de entrada}
{126300}{}{parede}
{126400}{}{parede}
{126500}{}{parede}
{126600}{}{parede}
{126700}{}{parede}
{126800}{}{parede}
{126900}{}{parede}
{127000}{}{Cerca de madeira}
{127100}{}{Cerca de madeira}
{127200}{}{Cerca de madeira}
{127300}{}{Cerca de madeira}
{127400}{}{Cerca de madeira}
{127500}{}{Cerca de madeira}
{127600}{}{Cerca de madeira}
{127700}{}{Cerca de madeira}
{127800}{}{Cerca de madeira}
{127900}{}{Cerca de madeira}
{128000}{}{Cerca de madeira}
{128100}{}{Cerca de madeira}
{128200}{}{Cerca}
{128300}{}{Portão}
{128400}{}{Portão}
{128500}{}{Portão}
{128600}{}{Portão}
{128700}{}{Portão}
{128800}{}{Portão}
{128900}{}{Portão}
{129000}{}{Portão}
{129100}{}{Portão}
{129200}{}{Portão}
{129300}{}{Portão}
{129400}{}{Portão}
{129500}{}{Portão}
{129600}{}{parede}
{129700}{}{parede}
{129800}{}{parede}
{129900}{}{parede}
{130000}{}{parede}
{130100}{}{parede}
{130200}{}{parede}
{130300}{}{parede}
{130400}{}{parede}
{130500}{}{parede}
{130600}{}{parede}
{130700}{}{parede}
{130800}{}{parede}
{130900}{}{parede}
{131000}{}{parede}
{131100}{}{parede}
{131200}{}{parede}
{131300}{}{parede}
{131400}{}{parede}
{131500}{}{parede}
{131600}{}{parede}
{131700}{}{parede}
{131800}{}{parede}
{131900}{}{parede}
{132000}{}{parede}
{132100}{}{parede}
{132200}{}{parede}
{132300}{}{parede}
{132400}{}{parede}
{132500}{}{parede}
{132600}{}{parede}
{132700}{}{parede}
{132800}{}{parede}
{132900}{}{parede}
{133000}{}{parede}
{133100}{}{parede}
{133200}{}{parede}
{133300}{}{parede}
{133400}{}{parede}
{133500}{}{parede}
{133600}{}{parede}
{133700}{}{parede}
{133800}{}{parede}
{133900}{}{parede}
{134000}{}{parede}
{134100}{}{parede}
{134200}{}{parede}
{134300}{}{parede}
{134400}{}{parede}
{134500}{}{parede}
{134600}{}{parede}
{134700}{}{parede}
{134800}{}{parede}
{134900}{}{parede}
{135000}{}{parede}
{135100}{}{parede}
{135200}{}{parede}
{135300}{}{parede}
{135400}{}{parede}
{135500}{}{parede}
{135600}{}{parede}
{135700}{}{parede}
{135800}{}{parede}
{135900}{}{parede}
{136000}{}{parede}
{136100}{}{parede}
{136200}{}{parede}
{136300}{}{parede}
{136400}{}{parede}
{136500}{}{parede}
{136600}{}{parede}
{136700}{}{parede}
{136800}{}{parede}
{136900}{}{parede}
{137000}{}{parede}
{137100}{}{parede}
{137200}{}{parede}
{137300}{}{parede}
{137400}{}{parede}
{137500}{}{parede}
{137600}{}{parede}
{137700}{}{parede}
{137800}{}{parede}
{137900}{}{parede}
{138000}{}{parede}
{138100}{}{parede}
{138200}{}{Cerca de madeira}
{138300}{}{Cerca de madeira}
{138400}{}{Cerca de madeira}
{138500}{}{Cerca de madeira}
{138600}{}{Cerca de madeira}
{138700}{}{Cerca de madeira}
{138800}{}{parede}
{138900}{}{parede}
{139000}{}{parede}
{139100}{}{parede}
{139200}{}{parede}
{139300}{}{parede}
{139400}{}{parede}
{139500}{}{parede}
{139600}{}{parede}
{139700}{}{parede}
{139800}{}{parede}
{139900}{}{parede}
{140000}{}{parede}
{140100}{}{parede}
{140200}{}{parede}
{140300}{}{parede}
{140400}{}{parede}
{140500}{}{parede}
{140600}{}{parede}
{140700}{}{parede}
{140800}{}{Coluna}
{140900}{}{parede}
{141000}{}{parede}
{141100}{}{parede}
{141200}{}{parede}
{141300}{}{parede}
{141400}{}{parede}
{141500}{}{parede}
{141600}{}{parede}
{141700}{}{parede}
{141800}{}{parede}
{141900}{}{parede}
{142000}{}{parede}
{142100}{}{parede}
{142200}{}{parede}
{142300}{}{parede}
{142400}{}{Arco}
{142500}{}{Arco}
{142600}{}{Arco}
{142700}{}{Arco}
{142800}{}{parede}
{142900}{}{parede}
{143000}{}{parede}
{143100}{}{parede}
{143200}{}{parede}
{143300}{}{parede}
{143400}{}{parede}
{143500}{}{parede}
{143600}{}{parede}
{143700}{}{parede}
{143800}{}{parede}
{143900}{}{parede}
{144000}{}{parede}
{144100}{}{parede}
{144200}{}{parede}
{144300}{}{parede}
{144400}{}{parede}
{144500}{}{parede}
{144600}{}{parede}
{144700}{}{parede}
{144800}{}{parede}
{144900}{}{parede}
{145000}{}{parede}
{145100}{}{parede}
{145200}{}{parede}
{145300}{}{parede}
{145400}{}{parede}
{145500}{}{parede}
{145600}{}{parede}
{145700}{}{parede}
{145800}{}{parede}
{145900}{}{parede}
{146000}{}{parede}
{146100}{}{parede}
{146200}{}{parede}
{146300}{}{parede}
{146400}{}{parede}
{146500}{}{parede}
{146600}{}{parede}
{146700}{}{parede}
{146800}{}{parede}
{146900}{}{parede}
{147000}{}{parede}
{147100}{}{parede}
{147200}{}{parede}
{147300}{}{parede}
{147400}{}{parede}
{147500}{}{parede}
{147600}{}{parede}
{147700}{}{parede}
{147800}{}{parede}
{147900}{}{parede}
{148000}{}{parede}
{148100}{}{parede}
{148200}{}{parede}
{148300}{}{parede}
{148400}{}{parede}
{148500}{}{parede}
{148600}{}{parede}
{148700}{}{parede}
{148800}{}{parede}
{148900}{}{parede}
{149000}{}{parede}
{149100}{}{parede}
{149200}{}{parede}
{149300}{}{parede}
{149400}{}{parede}
{149500}{}{parede}
{149600}{}{parede}
{149700}{}{parede}
{149800}{}{parede}
{149900}{}{parede}
{150000}{}{parede}
{150100}{}{parede}
{150200}{}{parede}
{150300}{}{parede}
{150400}{}{parede}
{150500}{}{parede}
{150600}{}{parede}
{150700}{}{parede}
{150800}{}{parede}
{150900}{}{parede}
{151000}{}{parede}
{151100}{}{parede}
{151200}{}{parede}
{151300}{}{parede}
{151400}{}{parede}
{151500}{}{parede}
{151600}{}{parede}
{151700}{}{parede}
{151800}{}{Coluna}
{151900}{}{parede}
{152000}{}{parede}
{152100}{}{parede}
{152200}{}{parede}
{152300}{}{parede}
{152400}{}{parede}
{152500}{}{Entrada de minas}
{152600}{}{Entrada de minas}
{152700}{}{Porta de entrada}
{152800}{}{Porta de entrada}
{152900}{}{Porta de entrada}
{153000}{}{Porta de entrada}
{153100}{}{Shuttle parede}
{153200}{}{Shuttle parede}
{153300}{}{Shuttle parede}
{153400}{}{Shuttle parede}
{153500}{}{Shuttle parede}
{153600}{}{Shuttle parede}
{153700}{}{Shuttle parede}
{153800}{}{Shuttle parede}
{153900}{}{Shuttle parede}
{154000}{}{Shuttle parede}
{154100}{}{Shuttle parede}
{154200}{}{Shuttle parede}
{154300}{}{Shuttle parede}
{154400}{}{Shuttle parede}
{154500}{}{Shuttle parede}
{154600}{}{Shuttle parede}
{154700}{}{Shuttle parede}
{154800}{}{Shuttle parede}
{154900}{}{Shuttle parede}
{155000}{}{Shuttle parede}
{155100}{}{Shuttle parede}
{155200}{}{Shuttle parede}
{155300}{}{Forcefield Emitter}
{155400}{}{parede}
{155500}{}{parede}
{155600}{}{parede}
{155700}{}{Forcefield Emitter}
{155800}{}{Porta de entrada}
{155900}{}{Porta de entrada}
{156000}{}{Porta de entrada}
{156100}{}{Porta de entrada}
{156200}{}{Porta de entrada}
{156300}{}{Porta de entrada}
{156400}{}{Porta de entrada}
{156500}{}{Porta de entrada}
{156600}{}{Porta de entrada}
{156700}{}{Porta de entrada}
{156800}{}{Porta de entrada}
{156900}{}{Porta de entrada}
{157000}{}{Porta de entrada}
{157100}{}{Porta de entrada}
{157200}{}{Porta de entrada}
{157300}{}{Porta de entrada}
{157400}{}{parede}
{157500}{}{Forcefield Emitter}
{157600}{}{parede}
{157700}{}{parede}
{157800}{}{Forcefield Emitter}
{157900}{}{Forcefield Emitter}
{158000}{}{Forcefield Emitter}
{158100}{}{parede}
{158200}{}{parede}
{158300}{}{Forcefield Emitter}
{158400}{}{Forcefield Emitter}
{158500}{}{parede}
{158600}{}{parede}
{158700}{}{Porta de entrada}
{158800}{}{Porta de entrada}
{158900}{}{Porta de entrada}
{159000}{}{Porta de entrada}
{159100}{}{Porta de entrada}
{159200}{}{Porta de entrada}
{159300}{}{parede}
{159400}{}{parede}
{159500}{}{parede}
{159600}{}{parede}
{159700}{}{parede}
{159800}{}{parede}
{159900}{}{parede}
{160000}{}{parede}
{160100}{}{parede}
{160200}{}{parede}
{160300}{}{parede}
{160400}{}{parede}
{160500}{}{parede}
{160600}{}{parede}
{160700}{}{parede}
{160800}{}{parede}
{160900}{}{parede}
{161000}{}{parede}
{161100}{}{parede}
{161200}{}{parede}
{161300}{}{parede}
{161400}{}{parede}
{161500}{}{parede}
{161600}{}{parede}
{161700}{}{parede}
{161800}{}{parede}
{161900}{}{parede}
{162000}{}{Porta de entrada}
{162100}{}{Porta de entrada}
{162200}{}{Porta de entrada}
{162300}{}{Porta de entrada}
{162400}{}{parede}
{162500}{}{parede}
{162600}{}{parede}
{162700}{}{parede}
{162800}{}{parede}
{162900}{}{parede}
{163000}{}{parede}
{163100}{}{Porta de entrada}
{163200}{}{Porta de entrada}
{163300}{}{parede}
