#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#


#
# Arroyo Quests
#
{100}{}{Mate as plantas malignas que infestam o jardim de Hakunin.}
{110}{}{Obtenha pederneira para que Mynoc afie sua lança.}
{120}{}{Resgate o cão de Nagor, o fumo, dos selvagens.}
{130}{}{Recupere o GECK para Arroyo.}
{140}{}{Encontre Vic the Trader.}

#
# Den Quests
#
{200}{}{Vic livre de sua dívida, obtendo seu rádio de sua casa em Klamath e pagando a Metzger.}
{201}{}{Sabotagem Becky ainda está.}
{202}{}{Pegue uma peça de carro para o Smitty.}
{203}{}{Retorne o medalhão de Anna.}
{204}{}{Colete dinheiro com Fred.}
{205}{}{Obter livro de Derek.}
{206}{}{Entregue uma refeição para Smitty para a mãe.}
{207}{}{Lara quer saber o que está sendo guardado na igreja.}
{208}{}{Obter permissão de Metzger para a guerra de gangues.}
{209}{}{Encontre fraqueza na gangue de Tyler guardando a igreja.}
{210}{}{Ajude Lara a atacar a brigada de Tyler.}

#
# Klamath Quests
#
{300}{}{Reabasteça o imóvel.}
{301}{}{Resgate Smiley the Trapper.}
{302}{}{Guarda o braim.}
{303}{}{Rustle o brahmin.}
{304}{}{Mate o Deus do rato.}
{305}{}{Rescue Torr.}

#
# Modoc Quests
#
{400}{}{Algo estranho está acontecendo na fazenda a nordeste de Modoc. Investigue e informe de volta para Jo.}
{401}{}{Cornelius perdeu seu relógio de bolso de ouro. Encontre e volte para ele.}
{402}{}{Farrel quer que você encontre o relógio de bolso dourado de Cornelius. Encontre-o e devolva-o a Farrel.}
{403}{}{Jonny está faltando. Encontre-o e traga-o para casa para Balthas.}
{404}{}{Jonny está nas cavernas da Escória. Encontre uma maneira de obter Jonny de volta para casa em Balthas.}
{405}{}{Farrel tem um problema de roedores em seu jardim. Remova a infestação.}
{406}{}{Entregue uma mensagem Escória para Jo em Modoc.}
{407}{}{Jo é suspeito de Slags. Descubra os cadáveres da Ghost Farm e descubra o que aconteceu com Karl.}
{408}{}{Vá para o Den e diga a Karl que está certo voltar para casa.}

#
# Vault City Quests
#
{500}{}{Pegue um arado para o Sr. Smith.}
{501}{}{Entregue a maleta de Moore ao Sr. Bishop em New Reno.}
{502}{}{Entregue uma amostra de jato para o Dr. Troy.}
{503}{}{Resolva o problema do motor de Gecko.}
{504}{}{Entregue o holodisco de Lynette para Westin na NCR.}
{505}{}{Resgate o marido de Amanda, Joshua.}
{506}{}{Entregue cerveja e bebidas (10 a cada) para Lydia.}
{507}{}{Entregue alicate (ferramentas) e uma chave inglesa para Valerie.}
{508}{}{Scout os oito setores em torno de Gecko e retornar para Stark.}
{509}{}{Entre na NCR e volte para o Stark.}

#
# Gecko Quests
#
{600}{}{Resolva o problema do motor de Gecko.}
{601}{}{Repare o powerplant.}
{602}{}{Otimize o powerplant.}
{603}{}{Obtenha um kit super reparo para o Skeeter.}
{604}{}{Obter transformador de plasma de 3 passos para o Skeeter.}
{605}{}{Encontre Woody o ghoul para Percy. Experimente o Den.}

#
# Broken Hills Quests
#
{700}{}{}
{701}{}{Corrigir o purificador de ar da mina.}
{702}{}{Encontre as pessoas desaparecidas para Marcus.}
{703}{}{Bata Francis no combate.}
{704}{}{Retire Manson e Franc da prisão.}
{705}{}{Explodir o purificador de ar da mina.}
{706}{}{Desvie mais energia elétrica para a casa de Eric.}

#
# New Reno Quests
#
{800}{}{Recupere seu carro roubado.}
{801}{}{Descubra quem foi responsável pela overdose de Richard Wright.}
{802}{}{     Suspeito: Jagged Jimmy J}
{803}{}{     Suspeito: Jules}
{804}{}{     Suspeito: Lil 'Jesus Mordino}
{805}{}{     Suspeito: Renesco}
{806}{}{Encontre um caminho para a Base da Serra do Exército.}
{807}{}{Acompanhe Pretty Boy Lloyd, recupere o dinheiro roubado e faça um ... exemplo dele.}
{808}{}{Visite Renesco Rocketman e colecione o tributo do Sr. Salvatore de US $ 1000.}
{809}{}{Ajude a proteger uma transação secreta ocorrendo no deserto.}
{810}{}{Encontre alguns bloqueadores da endorfina para fazer uma cura para o Jet.}
{811}{}{Bust Wright ainda está abaixo da estação de trem.}
{812}{}{Assassine Westin na NCR sem fazer parecer um assassinato.}
{813}{}{Assassinato Carlson na NCR.}
{814}{}{Entregue dez revistas de Cat Paw para Miss Kitty.}
{815}{}{Entregue uma pistola a laser para Eldridge.}
{816}{}{Entregue o pacote do Big Jesus para Ramirez nos estábulos.}
{817}{}{Recolha tributo dos Irmãos da Córsega.}
{818}{}{Assassine o chefe Salvatore para o grande Jesus Mordino.}

#
# Sierra Army Base Quests
#
{900}{}{}

#
# Vault 15 Quests
# Moved it to 3000 on accedent
{1000}{}{}

#
# New California Republic Quests
#
{1100}{}{Retrive Parts / Gain Access to Vault 15.}
{1101}{}{"Cuide o oficial Jack" para Mira.}
{1102}{}{Complete brahmin drive.}
{1103}{}{Retrive os papéis do Dr. Henry.}
{1104}{}{Teste o soro mutagênico em um super mutante. Experimente Broken Hills.}
{1105}{}{Elimine o Sr. Bishop.}
{1106}{}{Entregue o holodisco de Westin para Lynette na cidade de Vault.}
{1107}{}{Obter o mapa dos NCR Rangers, para Vortis the slaver.}
{1108}{}{Livre os escravos na caneta escrava, para os Rangers.}
{1109}{}{Entregue o relatório de campo da Hubologist à AHS-9 em San Francisco.}
{1110}{}{Mate o Hubologist na NCR para Merk.}
{1111}{}{Pare brahmin raids}
#
# Vault 13 Quests
#
{1200}{}{Corrija o computador do Vault 13.}
{1201}{}{Fale com Goris.}

#
# Military Base Quests
#
{1300}{}{}

#
# Redding Quests
#
{1400}{}{Descubra quem cortou a prostituta.}
{1401}{}{Encontre o chip da escavadeira}
{1402}{}{Rompa a briga da barra.}
{1403}{}{Kill Frog Morton.}

#
# San Francisco Quests
#
{1500}{}{O petroleiro precisa de combustível.}
{1501}{}{O computador de navegação precisa que a parte NavComp funcione.}
{1502}{}{Você precisa usar um FOB para acessar o computador de navegação.}
{1503}{}{Mate o Imperador Shi.}
{1504}{}{Os Hubologists precisam de planos para um vertibird de Navarro.}
{1505}{}{Roube os planos de vertigues do Shi.}
{1506}{}{Os Hubologists precisam de combustível para sua nave espacial.}
{1507}{}{Mate o texugo para que os vagabundos dos tanques abraçam o Eixo.}
{1508}{}{Mate o AHS-9.}
{1509}{}{O Shi precisa de planos para um vertibird de Navarro.}
{1510}{}{Roube os planos de vertibird dos Hubologists.}
{1511}{}{Encontre a namorada de Badger no porão abaixo do navio.}
{1512}{}{O Dragão quer que você tire Lo Pan - mão a mão.}
{1513}{}{Lo Pan quer que você tire o Dragão - mão a mão, se possível.}
{1514}{}{Obtenha o baço de Chip.}
{1515}{}{Obtenha alguma armadura de poder endurecida da Crockett.}
{1516}{}{Obtenha os planos de vertibird para a Brotherhood of Steel.}
#
# Navarro Quests
#
#1515, ...
{1600}{}{Lide com a morte.}
{1601}{}{Corrigir K9.}
{1602}{}{Recupere o FOB da base Commander.}

#
# The Enclave Quests
#
{1700}{}{}

#
# The Abbey Quests
#
{1800}{}{}

#
# Primitive Tribe Quests
#
{1900}{}{}

#
# EPA Quests
#
{2000}{}{}

#
# Ghost Town Quests
#
{2100}{}{}

#
# Car outta Gas Quests
#
{2200}{}{}

#
# Destroyed Arroyo Quests
#
{2300}{}{}

#
# Toxic Caves Quests
#
{2400}{}{}

#
# Den Slave Run Quests
#
{2500}{}{}

#
# Raiders Quests
#
{2600}{}{}

#
# Desert Encounter Quests
#
{2700}{}{}

#
# Mountain Encounter Quests
#
{2800}{}{}

#
# Ruined City Encounter Quests
#
{2900}{}{}

#
# Coast Encounter Quests
#
{3000}{}{}

#
# Golgotha Quests
#
{3100}{}{}


#
# Vault 15 Quests
#
{3200}{}{Resgate Chrissy}
{3201}{}{Matar Darion}
{3202}{}{Complete Deal with NCR.}
{3203}{}{Dê Spy Holodisk à autoridade na NCR.}
