#############################################################
#  Message File: Porta.msg                                   #
#                                                           #
#  Nota: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the name which will  #
#           be displayed for critter or items when they     #
#           get hit. Each script from scripts.lst should    #
#           have a name associated with it.                 #
#                                                           #
#  Created: October 06, 1997                                #
#############################################################

{101}{}{}                               # obj_dude.int    ; Player script.
{102}{}{Teste de script 0}                  # Test0.int       ; Used to Test Scripts
{103}{}{Teste de script 1}                  # Test1.int       ; Used to Test Scripts
{104}{}{Script Test 2}                  # Test2.int       ; Used to Test Scripts
{105}{}{Script Test 3}                  # Test3.int       ; Used to Test Scripts
{106}{}{Teste de script 4}                  # Test4.int       ; Used to Test Scripts
{107}{}{Teste de script 5}                  # Test5.int       ; Used to Test Scripts
{108}{}{Arroyo Guerreiro}                 # ACWarior.int    ; Genérico Guerreiro in Arroyo
{109}{}{Arroyo Aldeão}                # ACVillgr.int    ; Genérico Aldeão of Arroyo
{110}{}{Mynoc}                          # ACMynoc.int     ; Mynoc, Bridge Guardaaaaaaaaaaaaaaaaaaaaaaa of Arroyo
{111}{}{Arroyo Elder}                   # AHElder.int     ; Elder of Arroyo
{112}{}{Hakunin}                        # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{Porta}                           # Porta.int        ; generic locked and trapped door
{114}{}{Genérico}                        # Genérico.int     ; Genérico dialog for scripts
{115}{}{Peito}                          # AILkCaixa.int     ; Locked box in Arroyo Elder's room
{116}{}{Lockbox}                        # Containr.int    ; Genérico locked and trapped container
{117}{}{brâmane}                        # ACBrahmn.int    ; brâmane for pen in Arroyo
{118}{}{Planta de Spore}                    # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                               # ZClRato.int      ; Genérico lesser rat
{120}{}{Escorpião Menor}                # ZClScorp.int    ; Genérico lesser scorpion
{121}{}{Pequena Homemtis}                  # ZClHomemti.int    ; Genérico lesser mantis
{122}{}{Deathclaw Menor}               # ZClDthCL.int    ; Genérico lesser death claw
{123}{}{Vaso}                           # AIVaso.int      ; Vaso in Arroyo Aldeão's Hut
{124}{}{Peito}                          # AIPeito.int     ; Peito in Arroyo Shaman's Hut
{125}{}{Arroyo Caves}                   # ArCaves.int     ; Script do Mapaa for Arroyo Caves
{126}{}{Wooden Porta}                    # PortaL100.int    ; Genérico Locked Porta (+100%) (Wood)
{127}{}{Arroyo Village}                 # ArVillag.int    ; Script do Mapaa for Arroyo Village
{128}{}{Arroyo Bridge}                  # ArBridge.int    ; Script do Mapaa for Arroyo Bridge
{129}{}{Old Porta}                       # AICavDor.int    ; Locked wooden door in Arroyo Caves (0/-20)
{130}{}{Placa de piso}                    # SprTrp0.int     ; Genérico spear Trap (0)
{131}{}{Placa de piso}                    # SprTrp50.int    ; Arroyo Armadilha de lança for Caves (50)
{132}{}{Placa de piso}                    # SprTrp51.int    ; Arroyo Armadilha de lança for Caves (50)
{133}{}{Placa de piso}                    # SprTrp52.int    ; Arroyo Armadilha de lança for Caves (50)
{134}{}{Placa de piso}                    # SprTrp53.int    ; Arroyo Armadilha de lança for Caves (50)
{135}{}{Porta}                           # AIBkDor.int     ; Porta w/out a handle In Arroyo Caves
{136}{}{Reliant}                         # DCAddict.int    ; Addict from the Den
{137}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # DCG2Grd.int     ; Gang 2 Guardaaaaaaaaaaaaaaaaaaaaaaa from the Den
{138}{}{Townsperson}                    # DCCustmr.int    ; Genérico Customer in the Den
{139}{}{Thug}                           # DCCustmr.int    ; Thug in the Den
{140}{}{Órfão}                         # DCÓrfão.int    ; Thieving Órfão in the Den
{141}{}{Joey}                           # DCJoey.int      ; Special thug in the Den
{142}{}{Estalido}                          # DCEstalido.int     ; Kwik N Save store owner in the Den
{143}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # DCG2Grd.int     ; Gang 2 Guardaaaaaaaaaaaaaaaaaaaaaaa in the Den
{144}{}{Petey}                          # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{Smitty}                         # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{Metzger}                        # dcMetzge.int    ; Metzger the Escravor in the Den
{147}{}{Escravor}                         # DCEscravor.int    ; Regular Escravor in the Den
{148}{}{Tubby}                          # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{Anna}                           # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{Vic}                            # DCVic.int       ; Comerciante Vic in the Den, can be a party member
{151}{}{Frankie}                        # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{Rebecca}                        # DCRebecc.int    ; Rebecca in the Den
{153}{}{Contay}                          # DCContay.int     ; One-tooth Contay in the Hole in the Den
{154}{}{Sheila}                         # DCSheila.int    ; Sheila, the prostitute in the Hole in the Den
{155}{}{Mamãe}                            # DCMamãe.int       ; Mamãe, who run's Mamãe's in the Den
{156}{}{Aldeão}                       # DCSlvRun.int    ; Genérico People for Escravos
{157}{}{Escravo}                      # DNSlvRun.int    ; Script do Mapaa for Den Escravos
{158}{}{Carrorororo Escravo}                     # DISlvCrt.int    ; Carrorororo Escravo to take the Player to Den
{159}{}{Área de negócios Den}              # DenBus1.int     ; Script do Mapaa for Den business area 1
{160}{}{Área de negócios Den}              # DenBus2.int     ; Script do Mapaa for Den business area 2
{161}{}{Área Residencial Den}           # DenRes1.int     ; Script do Mapaa for Den residential area
{162}{}{Grave}                          # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{Grave}                          # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{Grave}                          # diMamãeGrv.int    ; Grave of Anna the ghost's Mamãe in the Den
{165}{}{Ossos}                          # diOssos.int     ; Ossos of Anna the ghost in the Den
{166}{}{Diário}                          # diDiário.int     ; Diário of Anna the ghost in the Den
{167}{}{Medalhão}                         # diMedalhão.int    ; Medalhão of Anna the ghost in the Den
{168}{}{Ainda}                          # diAinda.int     ; Ainda that Maggie has in the basement in the Den
{169}{}{Grave}                          # ziGenGrv.int    ; Genérico grave
{170}{}{Black Jack}                     # ziBlkJck.int    ; Genérico black jack table
{171}{}{Escravo}                          # zcEscravo.int     ; Genérico slave
{172}{}{Black Jack}                     # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{Porta}                           # diChcDor.int    ; Church door from the Den
{174}{}{Whisky Prumo}                    # KCPrumo.int       ; Whisky Prumo from Klamath
{175}{}{Craps}                          # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{Aldo}                           # KCAldo.int      ; Aldo from Klamath
{177}{}{Ardin}                          # KCArdin.int     ; Ardin from Klamath
{178}{}{Criança}                          # KCriança.int      ; Criança from Klamath
{179}{}{Cidadão}                        # KCidadão.int    ; Cidadão from Klamath
{180}{}{Maida}                          # KCMaida.int     ; Maida from Klamath
{181}{}{Sajag}                          # KCSajag.int     ; Sajag from Klamath
{182}{}{Sally}                          # KCSally.int     ; Sally from Klamath
{183}{}{risonho}                         # KCrisonho.int    ; risonho from Klamath
{184}{}{Jenny}                          # KCJenny.int     ; Jenny from Klamath
{185}{}{Fino}                           # KCFino.int      ; Fino from Klamath
{186}{}{Torr}                           # KCTorr.int      ; Torr from Klamath
{187}{}{Dunton}                         # KCDunton.int    ; Dunton from Klamath
{188}{}{Cidadão}                        # VCCrtCit.int    ; Vault City Courtyard Cidadão
{189}{}{Viajante}                      # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{Vault City Guardaaaaaaaaaaaaaaaaaaaaaaa}               # VCCrtGrd.int    ; Vault City Courtyard Guardaaaaaaaaaaaaaaaaaaaaaaa
{191}{}{Vault City Guardaaaaaaaaaaaaaaaaaaaaaaa}               # VCInGrd.int     ; Vault City Inner Guardaaaaaaaaaaaaaaaaaaaaaaa
{192}{}{Steve}                          # VCSteve.int     ; Steve from Vault City
{193}{}{Andrew}                         # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{Vault City Guardaaaaaaaaaaaaaaaaaaaaaaa}               # VCGatGrd.int    ; Vault City Main Portão Guardaaaaaaaaaaaaaaaaaaaaaaa
{195}{}{Dr. Troy}                       # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{Cão Amarelo}                     # KCYellow.int    ; Cão Amarelo in Klamath
{197}{}{Balthas}                        # mcBaltha.int    ; Balthas in Modoc
{198}{}{Cornelius}                      # mcCornel.int    ; Cornelius in Modoc
{199}{}{Davin}                          # mcDavin.int     ; Davin in Modoc
{200}{}{Farrel}                         # mcFarrel.int    ; Farrel in Modoc
{201}{}{Grisham}                        # mcGrisha.int    ; Grisham in Modoc
{202}{}{Jo}                             # mcJo.int        ; Jo in Modoc
{203}{}{Jonny}                          # mcJonny.int     ; Jonny in Modoc
{204}{}{Karl}                           # mcKarl.int      ; Karl in Modoc
{205}{}{Rapaz}                         # mcRapaz.int    ; Rapaz in Modoc
{206}{}{Miria}                          # mcMiria.int     ; Miria in Modoc
{207}{}{Protetor}                      # mcProtec.int    ; Protetor in Modoc
{208}{}{Rosa}                           # mcRosa.int      ; Rosa in Modoc
{209}{}{Vegeir}                         # mcVegeir.int    ; Vegeir in Modoc
{210}{}{Ed}                             # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{Harry}                          # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{Sra. Smith}                     # VCFSmith.int    ; Sra. Smith from Vault City (Agricultor)
{213}{}{Melinda}                        # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{Caçador}                        # KCTrapr.int     ; Genérico trapper in Klamath
{215}{}{Senhor Smith}                      # VCMSmith.int    ; Senhor Smith from Vault City (Agricultor)
{216}{}{Skeeve}                         # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{Proconsul Gregory}              # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{Enfermeira Nancy}                    # VCNancy.int     ; Enfermeira Nancy in Vault City
{219}{}{Randal}                         # VCRandal.int    ; Chief Admenities Oficial of Vault City
{220}{}{Goo}                            # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{Barkus}                         # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{Aldeão}                       # VCGenVil.int    ; Genérico Aldeão around Vault City
{223}{}{Rígido}                          # VCRígido.int     ; Vault City Sargent Rígido
{224}{}{Guardaaaaaaaaaaaaaaaaaaaaaa do portão do vaivémaa}               # VCVltGrd.int    ; Guardaaaaaaaaaaaaaaaaaaaaaaa for entrance into the Vault of VC
{225}{}{Old Joe}                        # VCOldJoe.int    ; Louco Old Joe (Vault City)
{226}{}{Connar}                         # VCConnar.int    ; Connar from Vault City
{227}{}{paredeace}                        # VCWalace.int    ; paredeace the Customs Official (Vault City)
{228}{}{Lynette}                        # VCLynett.int    ; First Cidadão Lynette of Vault City
{229}{}{McClure}                        # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{Ratoo Mutated}                    # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{Festus}                         # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{Gordon}                         # GCGordon.int    ; canibal with economic data in Gecko
{233}{}{Hank}                           # GCHank.int      ; canibal that monitors the reactor in Gecko
{234}{}{Jeremy}                         # GCJerem.int     ; canibal in charge of supply cabinet in Gecko
{235}{}{Grumoso}                          # GCGrumoso.int     ; Watches the brâmane and helps Skeeter
{236}{}{Skeeter}                        # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{Zomak}                          # GCZomak.int     ; Muscle man for the Brain
{238}{}{Wooz}                           # GCWooz.int      ; Bar owner and Tragic player
{239}{}{Lenny}                          # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{canibal Guardaaaaaaaaaaaaaaaaaaaaaaa}                    # GGCRDesk.int    ; Reator Desk guard
{241}{}{Trabalhador canibal}                   # GCRWorkr.int    ; Reator worker
{242}{}{Trabalhador incandescente}                 # GCRGlow.int     ; Reator glowing one
{243}{}{canibal Guardaaaaaaaaaaaaaaaaaaaaaaa}                    # GCRGuardaaaaaaaaaaaaaaaaaaaaaaa.int    ; Reator guard
{244}{}{Robô}                          # GCRRobô.int    ; Reator robot
{245}{}{canibal Cidadão}                  # GCFolk.int      ; Townsfolk in Gecko
{246}{}{Script do Mapaa}                     # DepoLv1.int     ; Mapa script for Sierra Army Depot, Level 1
{247}{}{Script do Mapaa}                     # DepoLvA.int     ; Mapa script for Sierra Army Depot Undergound
{248}{}{Script do Mapaa}                     # DepoLvB.int     ; Mapa script for Sierra. Underground B
{249}{}{Security Robô}                 # WCSecBot.int    ; Sierra Base, Security Robô (generic)
{250}{}{Repair Robô}                   # WCRepBot.int    ; Sierra Base, Repair Robô (generic)
{251}{}{Holodisk}                       # WIEvcDsk.int    ; Sierra Base, Evacution Holodisk
{252}{}{Holodisk}                       # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{Holodisk}                       # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{terminal}                       # WSTerm1A.int    ; Security Computador, Level 1 -- Sierra Base
{255}{}{terminal}                       # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{terminal}                       # WSTerm2A.int    ; Security Computador, Level 2 -- Sierra Base
{257}{}{terminal}                       # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{terminal}                       # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{terminal}                       # WSTerm3A.int    ; Security Computador, Level 3 -- Sierra Base
{260}{}{terminal}                       # WSTerm3B.int    ; Skynet terminal, Level 3 -- Sierra Base
{261}{}{terminal}                       # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{terminal}                       # WSTerm4A.int    ; Security Computador, Level 4 -- Sierra Base
{263}{}{terminal}                       # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{terminal}                       # WSTerm4C.int    ; BioStorage Computador, Level 4 -- Sierra Base
{265}{}{Papel}                          # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{Private Dobbs}                  # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{Brain Bot}                      # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{Elevador}                       # ZSElev01.int    ; Genérico Elevador
{269}{}{Elevador}                       # ZSElev02.int    ; Genérico Elevador
{270}{}{Lockbox}                        # DITubCaixa.int    ; Tubby's box of inventory
{271}{}{Lockbox}                        # DIFlkCaixa.int    ; Estalido's box of inventory
{272}{}{Tandi}                          # SHTandi.int     ; Tandi the talking head in the NCR2 area
{273}{}{Armadilha de lança}                     # ATSrTrp0.int    ; Arroyo Armadilha de lança for Caves (50)
{274}{}{Armadilha de lança}                     # ATSrTrp1.int    ; Arroyo Armadilha de lança for Caves (50)
{275}{}{Armadilha de lança}                     # ATSrTrp2.int    ; Arroyo Armadilha de lança for Caves (50)
{276}{}{Armadilha de lança}                     # ATSrTrp3.int    ; Arroyo Armadilha de lança for Caves (50)
{277}{}{Armadilha de lança}                     # ATSrTrp4.int    ; Arroyo Armadilha de lança for Caves (50)
{278}{}{Armadilha de lança}                     # ATSrTrp5.int    ; Arroyo Armadilha de lança for Caves (50)
{279}{}{Armadilha de lança}                     # ATSrTrp6.int    ; Arroyo Armadilha de lança for Caves (50)
{280}{}{Armadilha de lança}                     # ATSrTrp7.int    ; Arroyo Armadilha de lança for Caves (50)
{281}{}{Armadilha de lança}                     # ATSrTrp8.int    ; Arroyo Armadilha de lança for Caves (50)
{282}{}{Armadilha de lança}                     # ATSrTrp9.int    ; Arroyo Armadilha de lança for Caves (50)
{283}{}{Armadilha de lança}                     # ATSrTrpA.int    ; Arroyo Armadilha de lança for Caves (50)
{284}{}{Armadilha de lança}                     # ATSrTrpB.int    ; Arroyo Armadilha de lança for Caves (50)
{285}{}{Armadilha de lança}                     # ATSrTrpC.int    ; Arroyo Armadilha de lança for Caves (50)
{286}{}{Armadilha de lança}                     # ATSrTrpD.int    ; Arroyo Armadilha de lança for Caves (50)
{287}{}{Armadilha de lança}                     # ATSrTrpE.int    ; Arroyo Armadilha de lança for Caves (50)
{288}{}{Armadilha de lança}                     # ATSrTrpF.int    ; Arroyo Armadilha de lança for Caves (50)
{289}{}{Ghost Cave One}                 # GstCav1.int     ; Modoc Ghost Cave 1
{290}{}{Ghost Cave Two}                 # GstCav2.int     ; Modoc Ghost Cave 2
{291}{}{Ghost Farm}                     # GstFarm.int     ; Modoc Ghost Farm
{292}{}{Modoc brâmane Field}            # ModBrah.int     ; Modoc brâmane Field
{293}{}{Jardim Modoc}                   # ModGard.int     ; Jardim Modoc
{294}{}{Modoc Inn}                      # ModInn.int      ; Modoc Inn
{295}{}{Modoc Main}                     # ModMain.int     ; Modoc Main
{296}{}{Modoc Shit}                     # ModShit.int     ; Modoc under the shitter
{297}{}{Mod Bem}                       # ModBem.int     ; Modoc Bem
{298}{}{NCR Área 2}                     # ncr2.int        ; NCR area 2
{299}{}{Arroyo Gardens}                 # ArGarden.int    ; Arroyo Gardens map script
{300}{}{Gecko}                          # ACGecko.int     ; generic Gecko creature
{301}{}{Broc Flower}                    # AIBroc.int      ; Arroyo Broc Flower
{302}{}{Xander Root}                    # AIXander.int    ; Arroyo Xander Root
{303}{}{brâmane}                        # ZCBrahmn.int    ; Genérico brâmane
{304}{}{Esposa de Balthas}                   # mcBalWif.int    ; Modoc Balthas wife
{305}{}{brâmane}                        # mcBrahmn.int    ; Modoc brahmin
{306}{}{Cão selvagem}                       # mcAtkCachorro.int    ; Modoc Attack Cachorro
{307}{}{Rochas}                          # miDclRks.int    ; Modoc Rochas in front of the death claw cage
{308}{}{Rochas}                          # miShtRks.int    ; Modoc Rochas under the shitter
{309}{}{parede Seguro}                      # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{Bolsa de moedas}                       # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{Banheiro}                         # miBanheiro.int    ; ; Modoc Toliet
{312}{}{Caixa}                            # miLstFnd.int    ; Modoc Lost and Found at Rosa's
{313}{}{Jordânia}                         # ACJordânia.int    ; Jordânia. Trains player in Melee
{314}{}{Tia morlis}                    # ACMorlis.int    ; Tia morlis. Has flint to give player
{315}{}{Lucas}                  # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{Feargus}                        # ACEric.int      ; Whiny person asking to fix the well
{317}{}{Bem}                           # ASBem.int      ; Arroyo Bem. It's broken. Fix w/ Repair
{318}{}{Gruthar}                        # OCGrutha.int    ; Vault 13 Gruthar Deathclaw leader
{319}{}{Script do Mapaa}                     # Kladwtwn.int    ; Mapa script for Klamath Downtown
{320}{}{Skeeter}                        # SCSkeete.int    ; Skeeter dialog script for NCR Entrance area
{321}{}{Nagor}                          # ACNagor.int     ; You cousin who has lost his dog
{322}{}{Fumaça}                          # ACCachorro.int       ; Nagor's dog Fumaça
{323}{}{Ncr Área 1}                     # Ncr1.int        ; Ncr area 1 map
{324}{}{Ncr Área 3}                     # Ncr3.int        ; Ncr area 3 map
{325}{}{Ncr Área 4}                     # Ncr4.int        ; Ncr area 4 map
{326}{}{Entrada na Área Ncr}              # Ncrent.int      ; Ncr area Entrance map
{327}{}{Mikey}                          # SCMikey.int     ; NCR Lizard Dealer
{328}{}{Caixa de Mikey}                    # SIMbox.int      ' NCR Mikey's inventory box. (off Screen)
{329}{}{Emissor}                        # WSEmit1a.int    ; Emissor, Level 1, Section A   (Sierra Base)
{330}{}{Emissor}                        # WSEmit1b.int    ; Emissor, Level 1, Section B   (Sierra Base)
{331}{}{Emissor}                        # WSEmit1c.int    ; Emissor, Level 1, Section C   (Sierra Base)
{332}{}{Emissor}                        # WSEmit1d.int    ; Emissor, Level 1, Section D   (Sierra Base)
{333}{}{Emissor}                        # WSEmit1e.int    ; Emissor, Level 1, Section E   (Sierra Base)
{334}{}{Emissor}                        # WSEmit2a.int    ; Emissor, Level 2, Section A   (Sierra Base)
{335}{}{Emissor}                        # WSEmit2b.int    ; Emissor, Level 2, Section B   (Sierra Base)
{336}{}{Emissor}                        # WSEmit2c.int    ; Emissor, Level 2, Section C   (Sierra Base)
{337}{}{Emissor}                        # WSEmit2d.int    ; Emissor, Level 2, Section D   (Sierra Base)
{338}{}{Emissor}                        # WSEmit3a.int    ; Emissor, Level 3, Section A   (Sierra Base)
{339}{}{Emissor}                        # WSEmit3b.int    ; Emissor, Level 3, Section B   (Sierra Base)
{340}{}{Campo de força}                    # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{Campo de força}                    # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{Campo de força}                    # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{Campo de força}                    # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{Campo de força}                    # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{Campo de força}                    # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{Campo de força}                    # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{Campo de força}                    # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{Campo de força}                    # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{Campo de força}                    # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{Campo de força}                    # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{Klaxon}                         # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{Buster}                         # SCBuster.int    ; Buster gun dealer at NCR entrance
{353}{}{Estante de livros}                      # SIShelf1.int    ; Busters shelves where items are kept
{354}{}{Estante de livros}                      # SIShelf2.int    ; Busters shelves where items are kept
{355}{}{Estante de livros}                      # SIShelf3.int    ; Busters shelves where items are kept
{356}{}{Corsário}                         # ECCorsário.int    ; Random Encounter Corsário
{357}{}{Camponês}                        # ECPeasnt.int    ; Random Encounter Camponês
{358}{}{Comerciante}                       # ECMrchnt.int    ; Random Encounter Comerciante
{359}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # ECGuardaaaaaaaaaaaaaaaaaaaaaaa.int     ; Random Encounter Gaurd
{360}{}{Patron de couro cru}                 # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{Chão}                          # WTElFlr2.int    ; Electric Chão on Level 2 Sierra Base
{362}{}{Armadilha de plasma}                    # WTPlTrp0.int    ; Armadilha de plasma for Sierra Base(-30)
{363}{}{Armadilha de plasma}                    # WTPlTrp1.int    ; Armadilha de plasma for Sierra Base(-30)
{364}{}{terminal}                       # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{Quadro de avisos}                 # KSBboard.int    ; Klamath bulletin board
{366}{}{Portão}                           # ASCrlDr.int     ; Arroyo Corral Portão
{367}{}{Goo}                            # ATGoo.int       ; Goo in the Garden Mapa
{368}{}{Porta}                           # KSCVPorta.int    ; Porta in Klamath Rato Caves
{369}{}{Porta}                           # KSMalldr.int    ; Porta in Klamall..get key from Fino or Cachorro
{370}{}{}                               # ZCGecko.int     ; Genérico gecko
{371}{}{}                               # ZCLGecko.int    ; Genérico Golden Gecko
{372}{}{Script do Mapaa}                     # 2ndSt.int       ; 2nd Street Script do Mapaa
{373}{}{Script do Mapaa}                     # ChopShop.int    ; Chop Shop Script do Mapaa
{374}{}{Script do Mapaa}                     # GeckPwpl.int    ; Gecko Power Plant Script do Mapaa
{375}{}{Script do Mapaa}                     # GeckTunl.int    ; Gecko Tunnels Script do Mapaa
{376}{}{Script do Mapaa}                     # KlaCnyn.int     ; Klamath Canyon Script do Mapaa
{377}{}{Script do Mapaa}                     # MBase12.int     ; Military Base Level 1,2 Script do Mapaa
{378}{}{Script do Mapaa}                     # MBase34.int     ; Military Base Level 3,4 Script do Mapaa
{379}{}{Script do Mapaa}                     # MBClose.int     ; Military Base Closed Script do Mapaa
{380}{}{Script do Mapaa}                     # ModShit.int     ; Script do Mapaa for Modoc Shitter
{381}{}{Script do Mapaa}                     # NCR1.int        ; Script do Mapaa for NCR1
{382}{}{Script do Mapaa}                     # NCR2.int        ; Script do Mapaa for NCR2
{383}{}{Script do Mapaa}                     # NCR3.int        ; Script do Mapaa for NCR3
{384}{}{Script do Mapaa}                     # NCR4.int        ; Script do Mapaa for NCR4
{385}{}{Script do Mapaa}                     # NCREx.int       ; Script do Mapaa for NCR Exit
{386}{}{Script do Mapaa}                     # Stable.int      ; Script do Mapaa for Stables
{387}{}{Script do Mapaa}                     # V13_Orig.int    ; Script do Mapaa for Original Vault 13
{388}{}{Script do Mapaa}                     # V13Ent.int      ; Script do Mapaa for Vault 13 Entrance
{389}{}{Script do Mapaa}                     # V15_Orig.int    ; Script do Mapaa for Original Vault 15
{390}{}{Script do Mapaa}                     # V15Ent.int      ; Script do Mapaa for Vault 15 Entrance
{391}{}{Script do Mapaa}                     # Vault13.int     ; Script do Mapaa for Vault 13
{392}{}{Script do Mapaa}                     # Vault15.int     ; Script do Mapaa for Vault 15
{393}{}{Script do Mapaa}                     # VaultNec.int    ; Script do Mapaa for Necropolis Vault
{394}{}{Script do Mapaa}                     # VCtyVlt.int     ; Script do Mapaa for Vault City Vault
{395}{}{Script do Mapaa}                     # Virgin.int      ; Script do Mapaa for Virgin (these still exist?)
{396}{}{Ainda}                          # Kstill.int      ; Script for still in Klamath
{397}{}{Bar Cliente}                   # Kcggcust.int    ; Script for Klamath golden gecko customer
{398}{}{Bar Cliente}                   # Kcbhcust.int    ; Script for Klamath buckner house customer
{399}{}{Vortis}                         # SCVortis.int    ; Script for Vortis slave pen dude in NCR entrance
{400}{}{Assistente de banho}                 # Kcbgirl.int     ; Script for Klamath bath girl
{401}{}{Escravos}                         # SCEscravos.int    ; Script for NCR Entrance slaves
{402}{}{Escorpião}                       # Kcscorp.int     ; Script for Klamath scorpions on the graze map
{403}{}{brâmane}                        # Kcbrahmn.int    ; Script for Klamath brahmin on the graze map
{404}{}{Carrororo}                            # ZSDrvCarrororo.int    ; Drivable Carrororo for the player
{405}{}{Mesa}                          # diVicTbl.int    ; Den, table that Vic works at
{406}{}{Script do Mapaa}                     # Klagraz.int     ; Script do Mapaa for Klamath graze map
{407}{}{Script do Mapaa}                     # CarrororoDesrt.int    ; Carrororo Out of Gas Desert Mapa
{408}{}{Script do Mapaa}                     # GeckConjuntol.int    ; Script do Mapaa for Gecko Conjuntotlememt
{409}{}{Script do Mapaa}                     # VCtyCtyd.int    ; Script do Mapaa for Vault City Courtyard
{410}{}{Corvega}                        # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{Script do Mapaa}                     # KlaToxCv.int    ; Klamath Toxic Caves  Script do Mapaa
{412}{}{Metal Porta}                     # SISlvdor.int    ; Escravo pen door in NCR Entrance
{413}{}{Script do Mapaa}                     # RndDsrt.int     ; Random Encounter Desert Script do Mapaa
{414}{}{Script do Mapaa}                     # RndCoast.int    ; Random Encounter Coast Script do Mapaa
{415}{}{Script do Mapaa}                     # RndMnt.int      ; Random Encounter Mountain Script do Mapaa
{416}{}{Lockbox}                        # Criançabox.int      ; Klamath dunton inventory box
{417}{}{Lockbox}                        # Kibbox.int      ; Klamath buckner inventory box
{418}{}{Lockbox}                        # Kisbox.int      ; Klamath sajag inventory box
{419}{}{Ratoch}                          # SCRatoch.int     ; Ncr entrance JUNK dealer
{420}{}{Caixaer}                          # ncCaixaer.int     ; New Reno Genérico Caixaer
{421}{}{Pete McKneely}                  # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{Evan Hollyfeld}                 # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{Mastigador}                     # ncTyson.int     ; New Reno Mike Tyson
{424}{}{Cientista}                      # ncScient.int    ; New Reno Genérico Cientista
{425}{}{Merk}                           # SCMerk.int      ; Merk an NCR mob type guy
{426}{}{Ventilador}                            # ncCaixaVentilador.int    ; New Reno Caixaing Ventilador
{427}{}{Traficante de drogas}                    # ncDrgDlr.int    ; New Reno Traficante de drogas
{428}{}{Casino Patron}                  # ncCasPat.int    ; New Reno Casino Patron
{429}{}{Cafetão}                           # ncCafetão.int      ; New Reno Genérico Cafetão
{430}{}{Toxicómano}                         # ncToxicómano.int    ; New Reno Genérico Toxicómano
{431}{}{Mobília}                      # stuff.int       ; signals critters on steal attempt
{432}{}{Chão}                          # trespass.int    ; same as stuff only for an area
{433}{}{Terra}                         # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{Holodisk}                       # SIFakhlo.int    ; Fake holodisk you get from Merk in NCR.
{435}{}{Lenny}                          # SCLenny.int     ; Lenny a guy in NCR Entrance
{436}{}{Caixa}                            # SCPtbox.int     ; Players temp box to hold his stuff for the fight with lenny
{437}{}{Prostituta}                     # ncProsti.int    ; New Reno Prostituta with billions of messages
{438}{}{Escravo}                          # ncEscravo.int     ; New Reno Escravos
{439}{}{Rico}                           # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{Atriz pornô}                   # ncActres.int    ; New Reno Atriz pornô
{441}{}{Fluffer}                        # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{Script do Mapaa}                     # Klacanyn.int    ; Mapa script for Klamath Canyon
{443}{}{Lobo}                           # ECWlfPck.int    ; Military Base Lobo Pack
{444}{}{Gerador}                      # ESPwrGen.int    ; Military Base Power Gerador
{445}{}{Porta}                           # ESLkDor.int     ; Military Base Locked Porta (-30)
{446}{}{Super Mutante}                   # ECGenMut.int    ; Military Base Genérico Mutante
{447}{}{Salvatore's Homem}                # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{Bishop's Homem}                   # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{Mordino's Homem}                  # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{Wright's Criança}                 # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{Casino Bouncer}                 # ncCasBou.int    ; New Reno Genérico Casino Bouncer
{452}{}{Mira}                           # SCMira.int      ; NCR entrance bartender
{453}{}{New Reno Virgin Street}         # NewR1.int       ; New Reno Mapa Virgin Street
{454}{}{New Reno 2nd Street}            # NewR2.int       ; New Reno Mapa 2nd Street
{455}{}{New Reno Commercial Row}        # NewR3.int       ; New Reno Mapa Commercial Row
{456}{}{New Reno East Side}             # NewR4.int       ; New Reno Mapa East Side
{457}{}{Novos estábulos de Reno}               # NewRSt.int      ; New Reno Mapa Stables
{458}{}{New Reno Chop Shop}             # NewRCS.int      ; New Reno Mapa Chop Shop
{459}{}{Novo Reno Gologtha}              # NewRGo.int      ; New Reno Mapa Gologtha
{460}{}{New Reno Bishop Basement}       # NewRBa.int      ; New Reno Mapa Bishop Basement
{461}{}{Holodisk}                       # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{Holodisk}                       # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{Holodisk}                       # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{Holodisk}                       # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{Holodisk}                       # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # SCGteGrd.int    ; Ncr gate guard
{467}{}{Meu Carrororot}                      # ESMinCrt.int    ; Military Base Meu Carrororot to explode on door
{468}{}{Melchior}                       # ECMelchr.int    ; Melchoir the Magnificent (psuedo-mage)
{469}{}{Besta Mutated}                  # ECMutRato.int    ; Ratoo Mutateds in Military Base
{470}{}{FEV Goo}                        # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa Captain}                  # SCGGCap.int     ; NCR Entrance Portão guard captain
{472}{}{Escravo Overseer}                 # SCslvovr.int    ; NCR Entrance slave overseer
{473}{}{Melchior's Pet}                 # ECMelPet.int    ; Melchior's Pets
{474}{}{Escravor Guardaaaaaaaaaaaaaaaaaaaaaaa}                   # SCslvgrd.int    ; Escravor Guardaaaaaaaaaaaaaaaaaaaaaaa in NCR Entrance
{475}{}{Porta}                           # SIclsdor.int    ; Closing door
{476}{}{terminal}                       # SITerm.int      ; Escravo pen terminals NCR Entrance
{477}{}{Slot Machine}                   # ziSlots.int     ; Genérico Slot Machine
{478}{}{Criança}                          # ncWriChi.int    ; New Wright children
{479}{}{Sheb}                           # ncSheb.int      ; New Reno Sheb
{480}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # SCMrkGrd.int    ; Merk's guards NCR Entrance and council
{481}{}{Emissor}                        # SIEmtr.int      ; Emissor in NCR Entrance
{482}{}{Campo de força}                    # SIFField.int    ; Force field in NCR Entrance
{483}{}{Sulik}                          # Kcsulik.int     ; Sulik from Klamath
{484}{}{Dr. Henry}                      # SCHenry.int     ; Henry NCR Entrance
{485}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # SCCarrororoGrd.int    ; Carrororolson's guards NCR2
{486}{}{Carrororolson Guardaaaaaaaaaaaaaaaaaaaaaaas Attack}          # STCarrororoatk.int    ; Carrororolson's guards attack spatial
{487}{}{Carrororolson's Portão Guardaaaaaaaaaaaaaaaaaaaaaaas}          # SCcgtgrd.int    ; Carrororolson's gate Guardaaaaaaaaaaaaaaaaaaaaaaas
{488}{}{Prisioneiro}                       # VCOutPrs.int    ; Vault City Outsider Prisioneiro (Genérico)
{489}{}{Prisioneiro}                       # VCCitPrs.int    ; Vault City Cidadão Prisioneiro (Genérico)
{490}{}{Cidadão}                        # VCGenFam.int    ; Vault City Genérico Family
{491}{}{Amenidades Ajuda}                  # VCAmAid.int     ; Vault City Amenidades Ajuda
{492}{}{Guardaaaaaaaaaaaaaaaaaa de mesaaaaaaa}                     # GCRDesk.int     ; Gecko Reator Guardaaaaaaaaaaaaaaaaaa de mesaaaaaaa
{493}{}{Trabalhador canibal}                   # GCRcanibal.int    ; Gecko Reator Trabalhador canibal
{494}{}{Glowing One}                    # GCRGlow.int     ; Gecko Glowing One
{495}{}{canibal Guardaaaaaaaaaaaaaaaaaaaaaaa}                    # GCRGuardaaaaaaaaaaaaaaaaaaaaaaa.int    ; Gecko Red Porta Guardaaaaaaaaaaaaaaaaaaaaaaa
{496}{}{Robô}                          # GCRobô.int     ; Gecko Reator Robô
{497}{}{canibal}                          # GCFolk.int      ; Gecko Townsfolk
{498}{}{Adorador}                     # GCWorshp.int    ; Gecko Adoradors
{499}{}{Harold}                         # GCHarold.int    ; Harold in Gecko
{500}{}{Oficial}                        # GCPACOff.int    ; Gecko Powered Armor Com Oficial
{501}{}{Toto}                           # SCToto.int      ; Toto hlper bot in NCR 1
{502}{}{Dorothy}                        # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{Townsperson}                    # ncPerson.int    ; New Reno Genérico Townsperson/Cidadão
{504}{}{canibal Guardaaaaaaaaaaaaaaaaaaaaaaa}                    # GCYGuardaaaaaaaaaaaaaaaaaaaaaaa.int    ; Gecko Yellow Porta Guardaaaaaaaaaaaaaaaaaaaaaaa
{505}{}{canibal Guardaaaaaaaaaaaaaaaaaaaaaaa}                    # GCGuardaaaaaaaaaaaaaaaaaaaaaaa.int     ; Gecko Genérico Guardaaaaaaaaaaaaaaaaaaaaaaa
{506}{}{Gond}                           # SCGond.int      ; guarda Guardaaaaaaaaaaaaaaaaaaaaaaa, NCR 1
{507}{}{Duppo}                          # SCDuppo.int     ; Stockman's yard store owner
{508}{}{Coisa}                          # SIdtbl.int      ; Duppo's tables in shop
{509}{}{Prumo}                            # SCsalbob.int    ; Salt Beef Prumo NCR 3
{510}{}{Casino Girl}                    # ziDceGrl.int    ; Genérico Casino Girl with Dice Game
{511}{}{Casino Girl}                    # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{Magic Eight Ball}               # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{brâmane}                        # ncAngBra.int    ; New Reno Angry brâmane
{514}{}{Slot Machine}                   # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{Old Homem McGee}                  # ncMcGee.int     ; New Reno Old Homem (Prumoby) McGee
{516}{}{Three Carrororod Monte}               # nc3Monte.int    ; New Reno Three Carrororod Monte
{517}{}{Algernon}                       # ncAlgern.int    ; New Reno Algernon
{518}{}{Conta}                           # ncConta .int     ; New Reno Conta (Trees Lounge)
{519}{}{Escolta}                      # ncBisGrd.int    ; New Reno Bishop's Escoltas
{520}{}{John Bishop}                    # ncBishop.int    ; New Reno John Bishop
{521}{}{Máquina de Casino}                 # niCasMac.int    ; New Reno Máquina de Casino
{522}{}{Chop Shop Boy}                  # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{Chris Wright}                   # ncChrWri.int    ; New Reno Chris Wright
{524}{}{Cody}                           # ncCody .int     ; New Reno Cody
{525}{}{Incursão corsa}                # ncCorBro.int    ; New Reno Incursão corsas
{526}{}{Eldridge}                       # ncEldrid.int    ; New Reno Eldridge
{527}{}{Ethyl Wright}                   # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{Padre Tully}                   # ncFTully.int    ; New Reno Padre Tully
{529}{}{HumperdumperDIDO}               # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{Lil 'Jesus Mordino}             # ncLilJes.int    ; New Reno Lil 'Jesus Mordino
{531}{}{Jagged Jimmy J}                 # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{Keith Wright}                   # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{Lee Anne Bishop}                # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{Pretty Boy Lloyd}               # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{Pedreiro}                          # ncPedreiro.int     ; New Reno Pedreiro
{536}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # ncMyrGrd.int    ; New Reno Myron's Guardaaaaaaaaaaaaaaaaaaaaaaas
{537}{}{Myron}                          # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{Nikki}                          # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{Orville Wright}                 # ncOrvill.int    ; New Reno Orville Wright
{540}{}{Cova Boss}                       # ncCovaBos.int    ; New Reno Genérico Cova Boss
{541}{}{Renesco the Rocket-Homem}         # ncRenesc.int    ; New Reno Renesco the Rocket-Homem
{542}{}{investigador}                     # ncResear.int    ; Novos estábulos de Reno investigador
{543}{}{Boss Salvatore}                 # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{Stuart Little}                  # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{Bandeja}                          # ncTRay .int     ; New Reno Bandeja
{546}{}{Cadela}                          # ncCadela.int     ; New Reno Corsican Brothers Cadelaes
{547}{}{Wright Criança}                   # ncWriPly.int    ; New Reno Wright Criançaren Playing
{548}{}{Polícia NCR}                     # SCCop.int       ; NCR cop
{549}{}{Oswald}                         # SCOswald.int    ; Corsário Oswald captive NCR 1
{550}{}{Empoeirado}                          # SCEmpoeirado.int     ; Empoeirado bartender in NCR 1
{551}{}{Jules}                          # ncJules.int     ; New Reno Jules
{552}{}{Miss Kitty}                     # ncKitty.int     ; New Reno Miss Kitty
{553}{}{Barman}                      # ncBarten.int    ; New Reno Barman
{554}{}{Deputado Karl}                    # SCKarl.int      ; NCR Deputy
{555}{}{Cell Porta}                      # SIKdoor.int     ; NCR Cell door
{556}{}{Big Jesus Mordino}              # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{Hoss}                           # SCHoss.int      ; Hoss, bully NCR 1 map
{558}{}{Soro Mutagênico}                # SIMserum.int    ; Soro Mutagênico
{559}{}{Caixa}                            # niSalCaixa.int    ; New Reno Salvatore Barman Shop Inventory
{560}{}{Caixa}                            # niMorCaixa.int    ; New Reno Mordino Barman Shop Inventory
{561}{}{Caixa}                            # niBisCaixa.int    ; New Reno Bishop Barman Shop Inventory
{562}{}{Caixa}                            # niTmpCaixa.int    ; New Reno Personal Inventory Swap Caixa
{563}{}{Doutor Jubileu}                 # SCDocJub.int    ; Doutor Jubileu NCR Mapa 1
{564}{}{Porta}                           # GSYPorta.int     ; Yellow Porta in Gecko Reator
{565}{}{Porta}                           # GSRPorta.int     ; Red Porta in Gecko Reator
{566}{}{Estante}                       # SIdshelf.int    ; Estante de livros for the Doc NCR 1
{567}{}{Sheriff Dumont}                 # SCsherif.int    ; Sheriff in NCR map 1
{568}{}{Elise}                          # SCElise.int     ; Elise in NCR map 1 ranger leader chick
{569}{}{Mão do rancho}                     # SCwrHand.int    ; Westin Mão do rancho NCR 3
{570}{}{Félix}                          # SCFélix.int     ; Westin's forman on NCR 3
{571}{}{Westin}                         # SCWestin.int    ; Westin big dude on NCR 3
{572}{}{Rondó}                          # SCRondó.int     ; Rondó guarda NCR 1
{573}{}{Robodog}                        # SCRobo.int      ; Robodog NCR 1
{574}{}{Escadas}                         # NIBissta.int    ; New Reno Bishop's stairs
{575}{}{Hal}                            # SCHal.int       ; Hal, Drive Leader
{576}{}{Gunther}                        # SCGunthr.int    ; Gunther Tandi's assistant NCR 2
{577}{}{brâmane}                        # ECCrtBra.int    ; Random Encounter brâmane for carts
{578}{}{Carrororoavan Master}                 # ECCvnMst.int    ; Random Encounter Carrororoavan Master
{579}{}{Carrororoavan Driver}                 # ECCvnDrv.int    ; Random Encounter Carrororoavan Driver
{580}{}{Carrororoavan Guardaaaaaaaaaaaaaaaaaaaaaaa}                  # ECCvnGrd.int    ; Random Encounter Carrororoavan Guardaaaaaaaaaaaaaaaaaaaaaaa
{581}{}{Corsário}                         # ECRadLdr.int    ; Random Encounter Corsário Leader
{582}{}{Mafioso}                        # ECMobstr.int    ; Random Encounter Mafioso (Outside New Reno)
{583}{}{Caçador}                         # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{Caçador}                         # ECCaçador.int    ; Random Encounter Hunting Party
{585}{}{guarda}                         # ECguarda.int    ; Random Encounter NCR guardas (Patrol)
{586}{}{Mercenário}                      # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{Mercenário}                      # ECMrcLdr.int    ; Random Encounter Mercenário Leader
{588}{}{Corsário}                         # ECRadGrp.int    ; Random Encounter Corsário Party
{589}{}{Carrororoavan Driver}                 # ECRndDrv.int    ; Random Encounter Other Carrororoavan Driver
{590}{}{Carrororoavan Guardaaaaaaaaaaaaaaaaaaaaaaa}                  # ECRndGrd.int    ; Random Encounter Other Carrororoavan Guardaaaaaaaaaaaaaaaaaaaaaaa
{591}{}{Patrulhaaaaaaaa}                   # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{Capitão de patrulha}                 # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{Agricultor}                         # ECAgricultor.int    ; Random Encounter Agricultor
{594}{}{brâmane}                        # ECBraHrd.int    ; Random Encounter brâmane Herd
{595}{}{brâmane}                        # ECLedBra.int    ; Random Encounter Lead brâmane
{596}{}{Viajante}                       # ECTrvlr.int     ; Random Encounter Viajante
{597}{}{Patrulhaaaaaaaa}                   # ECGhlPat.int    ; Random Encounter canibal Patrol
{598}{}{Capitão de patrulha}                 # ECGhlCpt.int    ; Random Encounter canibal Patrol Capt.
{599}{}{Patrulhaaaaaaaa}                   # ECMutPat.int    ; Random Encounter Mutante Patrol
{600}{}{Capitão de patrulha}                 # ECMutCpt.int    ; Random Encounter Mutante Patrol Capt.
{601}{}{brâmane Driver}                 # ECBraDrv.int    ; Random Encounter brâmane Driver
{602}{}{Rustler}                        # ECBraRst.int    ; Random Encounter brâmane Rustler
{603}{}{Squatter}                       # ECSquatr.int    ; Random Encounter Squatters
{604}{}{Abolicionista}                   # ECAbolst.int    ; Random Encounter Abolicionista
{605}{}{Bootlegger}                     # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{Super Mutante}                   # ECRogMut.int    ; Random Encounter Vampiro Super Mutantes
{607}{}{Pescador}                      # ECFshrmn.int    ; Random Encounter Pescador
{608}{}{Escravor}                         # ECEscravor.int    ; Random Encounter Escravor
{609}{}{Caçador}                        # ECTrappr.int    ; Random Encounter Caçador
{610}{}{Carrororolson's Criança}                  # SCCarrororokid.int    ; Carrororolson's kid NCR map 2
{611}{}{Carrororolson}                        # SCCarrororolsn.int    ; Carrororolson NCR 2
{612}{}{}                               # Animfrv.int     ; Animate forever
{613}{}{Oficial Jack}                   # SCOfjack.int    ; Oficial Jack NCR 1
{614}{}{O Iluminado}            # SCEnlOne.int    ; O Iluminado NCR 1
{615}{}{Porta}                           # diPorta.int      ; Den Auto Closing Porta
{616}{}{Computador}                       # GsTerm.int      ; Gecko robot control terminal
{617}{}{Brahmn}                         # SCBrahmn.int    ; NCR Mapa 4 brâmane.
{618}{}{Deathclaw}                      # SCDthcla.int    ; NCR Mapa 4 Deathclaw.
{619}{}{Grade de saída}                      # SIExit.int      ; NCR Mapa 4 Grade de saída control
{620}{}{Computador}                       # SSComp.int      ; NCR Mapa 1 computer terminal that blows up
{621}{}{Feargus}                        # SCFergus.int    ; NCR Mapa 2
{622}{}{Ariel}                          # OCAriel.int     ; Vault 13 Ariel
{623}{}{Ventiladornie Mae}                     # RCVentiladornie.int    ; Ventiladornie Mae the hooker in Redding
{624}{}{Computador terminal}              # OCComptr.int    ; Computador terminal in Vault 13
{625}{}{Dalia}                          # OCDalia.int     ; Dalia in Vault 13
{626}{}{Dar}                            # OCDar.int       ; Dar Deathclaw guard Vault 13
{627}{}{Dave}                           # OCDave.int      ; Dave NPC in Vault 13
{628}{}{Gordon}                         # OCGordon.int    ; Gordon the shrine temple dude
{629}{}{Sinal fora do negócio}           # ziClosed.int    ; Genérico "Out of Business" signs
{630}{}{Máquinas de Controle de Reatores}      # gsReactr.int    ; Script to animate reactor
{631}{}{Jimmy}                          # OCJimmy.int     ; Jimmy guy in computer room Vault 13
{632}{}{Joseph}                         # OCJoseph.int    ; The Médico in Vault 13
{633}{}{Matt}                           # OCMatt.int      ; Matt prisonner in Vault 13
{634}{}{}                               # RCFitRato.int    ; Redding Fighting Molerats
{635}{}{Script do Mapaa}                     # RedMEnt.int     ; Redding Meu Entrance Script do Mapaa
{636}{}{Script do mapa V13}                 # vault13.int     ; Vault13 map script
{637}{}{Sandy}                          # OCSandy.int     ; Sandy Vault 13 child.
{638}{}{Caixa}                            # ziTmpCaixa.int    ; Genérico Temporary swap box
{639}{}{Thearn}                         # OCThearn.int    ; Vault 13 Guardaaaaaaaaaaaaaaaaaaaaaaa Thearn.
{640}{}{Caixa}                            # miGriCaixa.int    ; Modoc Grisham Comerciante box
{641}{}{Caixa}                            # miJoCaixa.int     ; Modoc Jo Comerciante box
{642}{}{Valdis}                         # OCValdis.int    ; Valdis guard in Vault 13
{643}{}{Computador terminal}              # OSvdrcmp.int    ; Porta computer vault 13 entrance
{644}{}{Metal Armário}                   # OIArmário.int    ; Metal locker in Vault 13
{645}{}{Footlocker}                     # OIftlkr.int     ; Footlocker in Vault 13
{646}{}{Deathclaw Guardaaaaaaaaaaaaaaaaaaaaaaa}                # OCgrunt.int     ; Genérico Vault 13 Deathclaw guard
{647}{}{Goris}                          # OCGoris.int     ; Goris possible party NPC vault 13
{648}{}{Caixa}                            # miBalCaixa.int    ; Modoc Balthas Comerciante box
{649}{}{Metal Armário}                   # siArmário.int    ; Guardaaaaaaaaaaaaaaaaaaaaaaa's lockers in NCR 1
{650}{}{Cheater}                        # Cheater.int     ; Cheater Character
{651}{}{Script do mapa V15}                 # vault15.int     ; Vault 15 map script
{652}{}{Phil}                           # bcPhil.int      ; Phil the secret vault 15 entrance guard
{653}{}{Conta}                           # bcConta.int      ; Conta in Vault 15 Entrance
{654}{}{açougueiro}                        # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{Dalia}                          # bcDalia.int     ; Guardaaaaaaaaaaaaaaaaaaaaaaa who guards a trail and shows up in v13
{656}{}{John}                           # bcJohn.int      ; Vault 15 guy entrance
{657}{}{Jones}                          # BCJones.int     ; Vault 15 doctor
{658}{}{Carrorola}                          # BCCarrorola.int     ; Carrorola Vault 15 guard.
{659}{}{Mapaa de entrada do segredo V15}       # V15sent.int     ; Vault 15 secret entrance map
{660}{}{Rebecca}                        # BCRebecc.int    ; Vault 15 Rebecca
{661}{}{Porta}                           # miPorta.int      ; Modoc Portas
{662}{}{Garra da morte}                     # mcDthClw.int    ; Modoc Rosa's "Chicken"
{663}{}{Roberta}                        # bcRobert.int    ; Roberta Vault 15 Entrace
{664}{}{Sara}                           # bcSara.int      ; Sara vault 15 Entrance
{665}{}{Zeke}                           # bcZeke.int      ; Zeke vault 15 Entrance mayor dude
{666}{}{brâmane}                        # bcBrahmn.int    ; Genérico brâmane in Vault15 Entrance
{667}{}{Wood Porta}                      # BiEntDr.int     ; Trapped Vault15 entrance door
{668}{}{Chrissy}                        # BCCrissy.int    ; Crissy, Rebecca's daughter
{669}{}{Darion}                         # BCDarion.int    ; Big bad dude in Vault 15
{670}{}{Guardaaaaaaaaaaaaaaaaa de Darionaaaaaaa}                 # BCDargrd.int    ; Darion's guard in Vault 15
{671}{}{Cão de Darion}                   # BCDardog.int    ; Darion's dog in Vault 15
{672}{}{Cassidy}                        # VCCasidy.int    ; Cassidy the  bar person in Vault City
{673}{}{Bem}                           # miBem.int      ; Modoc Bem
{674}{}{Ratoo toupeira}                       # mcMolRato.int    ; Modoc Shitter Ratoo toupeira
{675}{}{brâmane Chunk}                  # miBraMea.int    ; Modoc brâmane Chunks
{676}{}{brâmane}                        # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{Elevador Porta}                  # bsElev.int      ; Elevador door in V15sent
{678}{}{Cachorro}                            # mcKilCachorro.int    ; Modoc Cachorro that hangs out at the slaughter house
{679}{}{Rato}                            # mcRato.int       ; Jardim Modoc Rato
{680}{}{Sun Spot}                       # ziSunSpt.int    ; Genérico Sun Spot
{681}{}{Bess}                           # mcBess.int      ; Modoc Bess the brâmane
{682}{}{Caixa}                            # miJkyCaixa.int    ; Modoc Jerky box
{683}{}{Craps Dealer}                   # zcCrpDel.int    ; Craps Dealer
{684}{}{Protetor do Vault 15aaaaaaa}                 # bcGenGrd.int    ; Vault 15 Khan Guardaaaaaaaaaaaaaaaaaaaaaaa
{685}{}{Escória}                           # mcEscória.int      ; Modoc Genérico Escória
{686}{}{Tapete}                            # mtTapete.int       ; Modoc Script espacial for Tapete
{687}{}{Criança}                          # mcCriança.int     ; Modoc Criança
{688}{}{Aileen}                         # hcAileen.int    ; Aileen in Broken Hills
{689}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # hcBnkGrd.int    ; Bank Guardaaaaaaaaaaaaaaaaaaaaaaa in Broken Hills
{690}{}{Doc Holiday}                    # hcDoc.int       ; Doc in Broken Hills
{691}{}{Henchman}                       # hcencha.int     ; Henchman A in Broken Hills
{692}{}{Henchman}                       # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{Mulher}                          # hcfemale.int    ; Female in Broken Hills
{694}{}{Francis}                        # hcFranci.int    ; Francis in Broken Hills
{695}{}{Frank}                          # hcFrank.int     ; Frank in Broken Hills
{696}{}{canibal}                          # hccanibal.int     ; canibal in Broken Hills
{697}{}{Liz}                            # hcLiz.int       ; Liz in Broken Hills
{698}{}{Homem}                            # hcmale.int      ; Male in Broken Hills
{699}{}{Homemson}                         # hcHomemson.int    ; Homemson in Broken Hills
{700}{}{Marcus}                         # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{Meuiro}                          # hcMeuiros.int    ; Meuiros in Broken Hills
{702}{}{Mutante}                         # hcMutante.int    ; Mutante in Broken Hills
{703}{}{Conta}                           # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{Phil}                           # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{Steve}                          # hcSteve.int     ; Steve in Broken Hills
{706}{}{Supervisor}                     # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{Zaius}                          # hcZaius.int     ; Zaius in Broken Hills
{708}{}{Jacob}                          # hcJacob.int     ; Jacob in Broken Hills
{709}{}{Conjunto de Química}                  # hchems.int      ; Conjunto de Química in Broken Hills
{710}{}{Suporte}                           # miGstPrp.int    ; Modoc Ghost Farm Suporte
{711}{}{Porta}                           # bssdor1.int     ; Shack doors on V15sEnt map
{712}{}{Computador}                       # BSComp1.int     ; Library Computador Vault 15
{713}{}{Chade}                           # hcchad.int      ; Chade from Broken Hills
{714}{}{Planta de Spore}                    # ECPlant.int     ; Random Encounter Planta de Spore
{715}{}{Gecko}                          # ECGecko.int     ; Random Encounter Gecko
{716}{}{Radscorpion}                    # ECScorp.int     ; Random Encounter Escorpiãos
{717}{}{}                               # ECRato.int       ; Random Encounter Ratos
{718}{}{Guerreiro}                        # ECWarPty.int    ; Random Encounter War Party
{719}{}{Canibal}                       # ECCanibl.int    ; Random Encounter Canibals
{720}{}{Exilado}                        # ECOutCst.int    ; Random Encounter Exilados
{721}{}{Pessoa sagrada}                    # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{Nômade}                          # ECNômade.int     ; Random Encounter Nômades
{723}{}{Pessoa desabrigada}                # ECHomles.int    ; Random Encounter Homeless
{724}{}{Bandido}                         # ECBandido.int    ; Random Encounter Bandido
{725}{}{Ladrão}                         # ECLadrão.int    ; Random Encounter Ladrão
{726}{}{Highwayman}                     # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{Escravor}                         # ECSlvRun.int    ; Random Encounter Escravors on a Escravo
{728}{}{Escravo}                          # ECEscravo.int     ; Random Encounter Escravos
{729}{}{Partier}                        # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{Homemtis}                         # ECHomemtis.int    ; Random Encounter Homemtis
{731}{}{brâmane}                        # ECBrahmn.int    ; Random Encounter brâmane
{732}{}{Cachorro}                            # ECWldCachorro.int    ; Random Encounter Cão selvagems
{733}{}{Computador}                       # BSComp2.int     ; Darion's computer terminal Vault15
{734}{}{Computador}                       # BSComp3.int     ; Force field computer terminal
{735}{}{Computador terminal}              # BSComp4.int     ; Campo de força control computer by entrance Vault 15
{736}{}{Computador}                       # BSComp5.int     ; Computador at the Power area. Vault 15
{737}{}{Power Gerador}                # BSPower.int     ; Power Gerador in Vault 15
{738}{}{Campo de força}                    # BSField.int     ; Campo de força in Vault 15
{739}{}{Camponês}                        # mcPeasan.int    ; Modoc Camponês Person
{740}{}{Emissor}                        # bsEmtr.int      ; Emissor in Vault 15
{741}{}{Vault Porta}                     # osv13dr.int     ; Vault 13 Porta
{742}{}{Security Porta}                  # osPorta1.int     ; Vault 13 Porta that shows deathclaws
{743}{}{Bess Encounter}                 # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{Bess}                           # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{brâmane}                        # ECBesCow.int    ; One of the brâmane in Bess's herd
{746}{}{Angela Bishop}                  # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{Tommy "The Balls"}              # ncTommy.int     ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{Seguro}                           # niABisSf.int    ; New Reno Angela Bishop's Seguro
{749}{}{Seguro}                           # niMrBSf.int     ; New Reno Mr. Bishop's Seguro
{750}{}{Seguro}                           # niMrsBSf.int    ; New Reno Mrs. Bishop's Seguro
{751}{}{Seguro}                           # niOWriSf.int    ; New Reno Orville Wright's Seguro
{752}{}{Grave}                          # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{Cômoda}                        # niWridrs.int    ; New Reno Richard Wright's Cômoda
{754}{}{Grave}                          # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{Ainda}                          # niWriSti.int    ; New Reno Wright Aindas
{756}{}{Ramirez}                        # ncRamire.int    ; New Reno Ramirez
{757}{}{Cave 1 Random Encounter Mapa}    # cave01.int      ; Cave 1 Random Encounter Mapa
{758}{}{Caixa}                            # niRenCaixa.int    ; New Reno Renesco Caixa
{759}{}{Porta}                           # niPorta.int      ; New Reno Porta
{760}{}{Cave 2 Random Encounter Mapa}    # cave02.int      ; Cave 2 Random Encounter Mapa
{761}{}{Mapaa do Encontro Aleatório Cave 3}    # cave03.int      ; Mapaa do Encontro Aleatório Cave 3
{762}{}{Mapaa do Encontro Aleatório da Caverna 4}    # cave04.int      ; Mapaa do Encontro Aleatório da Caverna 4
{763}{}{Cave 2 Random Encounter Mapa}    # cave02.int      ; Cave 2 Random Encounter Mapa
{764}{}{Porta}                           # VIEntDor.int    ; Vault City Entrance Porta
{765}{}{Script do Mapaa}                     # VCtyDwtn.int    ; Vault City Downtown Mapa script
{766}{}{Trap Porta}                      # miTrpDor.int    ; Modoc Ghost Farm Trap Porta
{767}{}{Lockbox}                        # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{Quarto}                           # ntLydRom.int    ; New Reno Lloyd Quarto
{769}{}{Thomas Moore}                   # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{Porta}                           # ZILckDor.int    ; Genérico Locked Porta (-20)
{771}{}{Armário}                         # niLydCaixa.int    ; New Reno Lloyd's Loot Caixa
{772}{}{Homemhole}                        # niHomemhol.int    ; New Reno Homemhole to Lloyd's Loot
{773}{}{Grave}                          # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{Guardaaaaaaaaaaaaaaaa de abastecimentoaaaaaaaa}                   # VCSupGrd.int    ; Vault City Guardaaaaaaaaaaaaaaaa de abastecimentoaaaaaaaa Martin
{775}{}{Script do Mapaa}                     # broken1.int     ; Script do Mapaa for Broken Hills Mapa 1
{776}{}{Script do Mapaa}                     # rndexcow.int    ; Script do Mapaa for Low Luck encounter
{777}{}{Mad brâmane}                    # eccowbmb.int    ; The cows that blow
{778}{}{Hakeswill}                      # RCHakes.int     ; Hakeswill from Redding
{779}{}{Redding Downtown}               # REDDown.int     ; Redding Downtown map script
{780}{}{Script do Mapaa}                     # BHRndDst.int    ; Broken Hills Carrororoavan Desert Mapa
{781}{}{Script do Mapaa}                     # BHRndMtn.int    ; Broken Hills Carrororoavan Mountain Mapa
{782}{}{Lou}                            # RCLou.int       ; Lou from Redding
{783}{}{Arthur}                         # ECArthur.int    ; Arthur the leader of the Special Encounter knights
{784}{}{Robin}                          # ECRobin.int     ; Robin one of the Knights with Arthur
{785}{}{Bedemir}                        # ECBedemi.int    ; Bedemir one of the Knights with Arthur
{786}{}{Senhor launcelote}                  # ECSirLau.int    ; Senhor launcelote one of the Knights with Arthur
{787}{}{Galahad}                        # ECGalaha.int    ; Galahad one of the knights iwth Arthur
{788}{}{Ben Wade}                       # RCWade.int      ; Ben Wade from Radding
{789}{}{Athabaska Dick}                 # RCDick.int      ; Athabaska Dick from Redding
{790}{}{Viúva Rooney}                   # RCRooney.int    ; Viúva Rooney from Redding
{791}{}{Townsperson}                    # RCGenPes.int    ; Genérico Townsperson in Redding
{792}{}{Stanwell}                       # RCStanwl.int    ; Stannwell from Redding
{793}{}{Savinelli}                      # RCSavine.int    ; Savinelli from Redding
{794}{}{Marge}                          # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{Madame Modjeska}                 # RCModjes.int    ; Madame Modjeska from Redding
{796}{}{James Hoffy}                    # RCHoffy.int     ; James Hoffy, Carrororoavan Master for Redding
{797}{}{Script do Mapaa}                     # Rndholy1.int    ; Random Encounter Holy Knights 1 map
{798}{}{Patsy}                          # ECPatsy.int     ; Arthur's horse HOLY 1 encounter
{799}{}{Concorde}                       # ECConcor.int    ; Concord Launcelot's horse.
{800}{}{Eric}                           # ECEric.int      ; Robin's horse
{801}{}{John}                           # ECJohn.int      ; Bedemir's horse
{802}{}{Joshua}                         # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{Escada}                         # miEscada.int    ; Modoc Shitter Escada
{804}{}{Cabeça grande}                       # ecBHead.int     ; Cabeça grande special encounter
{805}{}{Herói preto}                     # ecBlkHro.int    ; Herói preto model
{806}{}{Heroína Vermelha}                    # ecRedHro.int    ; Heroína Vermelha model
{807}{}{Conjunto}                            # ecConjunto.int       ; Conjunto in Cafe of Broken Dreams
{808}{}{Tandi}                          # ecTandi.int     ; Tandi in Cafe of " "
{809}{}{Herói Branco}                     # ecWhro1.int     ; Herói Branco Model 1 " " "
{810}{}{Herói Branco}                     # ecWhro2.int     ; Herói Branco Model 2 " " "
{811}{}{Herói Brancoine}                  # ecWheon1.int    ; Herói Brancoine Model 1
{812}{}{Caixa}                            # NiJulCaixa.int    ; New Reno Jules Shop Inventory Caixa
{813}{}{Caixa}                            # niEldCaixa.int    ; New Reno Eldridge Shop Caixa
{814}{}{Caixa}                            # niEldBx2.int    ; New Reno Eldridge Shop Caixa (For Made Men)
{815}{}{Script do Mapaa}                     # rndholy2.int    ; Hi-Luck random Holy knight encounter 2
{816}{}{Rato Vorpalo}                     # ECVorRato.int    ; Rato Vorpalo for Holy Knight 2
{817}{}{Cachorro}                            # ECPCachorro.int      ; Pariah Cachorro... not good to have following you around
{818}{}{Broca Seargant}                 # CCDrill.int     ; Broca Seargant in Colusa/Nevarro
{819}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # CCGuardaaaaaaaaaaaaaaaaaaaaaaa.int     ; Guardaaaaaaaaaaaaaaaaaaaaaaa in Colusa/Nevarro
{820}{}{Técnico}                     # CCTech.int      ; Técnico in Colusa/Nevarro
{821}{}{Comandante}                      # CCHomemdr.int     ; Comandante in Colusa Nevarro
{822}{}{Chris}                          # CCChris.int     ; Chris the gas station attendant in Colusa
{823}{}{Quarto mestre}                 # CCMaster.int    ; Quarto mestre in Colusa/Nevarro
{824}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # CCGGuardaaaaaaaaaaaaaaaaaaaaaaa.int    ; Portão Guardaaaaaaaaaaaaaaaaaaaaaaa in Colusa/Nevarro
{825}{}{Grave}                          # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Script espacial)
{826}{}{Carrororo}                            # ntCarrororo1.int      ; New Reno Stolen Carrororo Seed Spacial 1
{827}{}{Carrororo}                            # ntCarrororo2.int      ; New Reno Stolen Carrororo Seed Spacial 2
{828}{}{Grave}                          # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{Figura Robed}                   # EcBridge.int    ; Bridge guy special encounter
{830}{}{Comprador de gado}                   # SCdrvpay.int    ; Cattle drive from NCR to redding.
{831}{}{Script do Mapaa}                     # RndBridg.int    ; Random Bridge encounter
{832}{}{Misterioso estranho}            # ECMstStr.int    ; Misterioso estranho
{833}{}{Mad Brahmn}                     # ECgcwbmb.int    ; Genérico Cow bomb
{834}{}{}                               # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{}                               # ECWilder.int    ; Random Encounter Wilder
{836}{}{Cachorro}                            # ncWriCachorro.int    ; New Reno Wright Cachorro
{837}{}{Caixa}                            # niRamCaixa.int    ; New Reno Caixa to be delivered to Ramirez
{838}{}{}                               # ECUniPat.int    ; Unity Patrol Random Encounter
{839}{}{}                               # ECTravlr.int    ; Random Encounter Travler
{840}{}{Fumaça}                          # KtFumaça.int     ; displays message about smoke smell in Duntons
{841}{}{Comerciante}                         # ECComerciante.int    ; Random Encounter Comerciante
{842}{}{Scavenger}                      # ECScaven.int    ; Random Encounter Scavenger
{843}{}{Comerciante}                       # FCMercha.int    ; San Fran Air bag merchant
{844}{}{Camponês}                        # FCBadPea.int    ; San Fran Bad Camponêss
{845}{}{Templo Arroyo}                  # ARTemple.int    ; Templo Arroyo map script
{846}{}{Doca Worker}                    # FCDokWrk.int    ; San Fran Doca Worker
{847}{}{Camponês}                        # FCGudPea.int    ; San Fran Good Camponêss
{848}{}{Shi Guardaaaaaaaaaaaaaaaaaaaaaaa}                      # FCShiGrd.int    ; San Fran Shi Guardaaaaaaaaaaaaaaaaaaaaaaa
{849}{}{Guerreiro}                        # ACTemVil.int    ; Temple challenge person
{850}{}{Porta}                           # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{Klint}                          # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{Cultivo}                          # AICultivo.int     ; Cultivo that die after a period of time
{853}{}{Shi Lab Tech}                   # FCslabte.int    ; San Fran Shi Lab techs
{854}{}{Criança}                          # FCSkids.int     ; San Fran Shi Crianças
{855}{}{canibal}                          # GCWander.int    ; wandering ghouls in Gecko
{856}{}{Dr Fung}                        # FCDrFung.int    ; San Fran Dr Fung
{857}{}{Jul}                            # OCJul.int       ; Vault 13 Denmother Guardaaaaaaaaaaaaaaaaaaaaaaa
{858}{}{Kerith}                         # OCKerith.int    ; Vault 13 Den Mother
{859}{}{Peito}                          # AITemCst.int    ; Temple Peito to hold the players things
{860}{}{canibal}                          # GCRGhul.int     ; Reator ghoul that doesn't move
{861}{}{}                               # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                               # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{Prospector}                     # ECProspe.int    ; Random Encounter Prospector
{864}{}{}                               # ECPrsGng.int    ; Random Encounter Press Gang
{865}{}{Nômade Chief}                    # ECNomChf.int    ; Random Encounter Nômade Chief
{866}{}{Hubologist}                     # ECElRon.int     ; Hubologist Patrol
{867}{}{Louco}                          # ECLouco.int     ; Crazies from Random Encounter
{868}{}{Claim Jumper}                   # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{Canibal}                       # ECCanbal.int    ; Random Encounter Canibals
{870}{}{Nômade Shamon}                   # ECNomSha.int    ; Random Encounter Nômade Shamon
{871}{}{Marauder}                       # ECMaradr.int    ; Random Encounter Marauder
{872}{}{Vampiro}                          # ECVampiro.int     ; Random Encounter Vampiro
{873}{}{Eremita}                         # ECEremita.int    ; Random Encounter Eremita
{874}{}{}                               # ECGangs.int     ; Random Encounter Gangs
{875}{}{Carrororoavan Master}                 # ECMstKla.int    ; Random Encounter Klamath Carrororoavan Master
{876}{}{Carrororoavan Master}                 # ECMstDen.int    ; Random Encounter Den Carrororoavan Master
{877}{}{Carrororoavan Master}                 # ECMstNew.int    ; Random Encounter New Reno Carrororoavan Master
{878}{}{Carrororoavan Master}                 # ECMstRed.int    ; Random Encounter Redding Carrororoavan Master
{879}{}{Carrororoavan Master}                 # ECMstBro.int    ; Random Encounter Broken Hills Carrororoavan Master
{880}{}{Carrororoavan Master}                 # ECMstGec.int    ; Random Encounter Gecko Carrororoavan Master
{881}{}{Carrororoavan Master}                 # ECMstSan.int    ; Random Encounter San Fran Carrororoavan Master
{882}{}{Carrororoavan Master}                 # ECMstNCR.int    ; Random Encounter NCR Carrororoavan Master
{883}{}{Carrororoavan Master}                 # ECMstV15.int    ; Random Encounter Vault 15 Carrororoavan Master
{884}{}{Agricultor's Wife}                  # ECFrmWfe.int    ; Random Encounter Agricultor's wife
{885}{}{Agricultor's Criança}                   # ECFrmCriança.int    ; Random Encounter Agricultor's Criança
{886}{}{Homesteader}                    # ECHomest.int    ; Random Encounter Homesteader
{887}{}{Homesteader's Wife}             # ECHomwfe.int    ; Random Encounter Homesteader's Wife
{888}{}{Homesteader's Criança}              # ECHomCriança.int    ; Random Encounter Homesteader's Criança
{889}{}{Carrororoavan Master}                 # ECMstVC.int     ; Random Encounter Vault City Carrororoavan Master
{890}{}{}                               # ECAlien.int     ; Random Encounter Alien
{891}{}{}                               # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                               # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                               # ECCentur.int    ; Random Encounter Centaurs
{894}{}{Patrulheiro Enclave}              # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{Capitão Merc}                   # icMrcCpt.int    ; Corsários Capitão Merc
{896}{}{Merc Corsário}                    # icMerc.int      ; Corsários Merc
{897}{}{"Shadow-Who-Walks"}             # icScout.int     ; Corsários Scout
{898}{}{Seguro}                           # iiSeguro.int      ; Corsários Seguro
{899}{}{}                               # raiders1.int    ; Corsários 1 Enterance
{900}{}{}                               # raiders2.int    ; Corsários 2 Caves
{901}{}{}                               # HSCellDr.int    ; Broken Hills bank/jail door
{902}{}{Caixa}                            # niTRyCaixa.int    ; New Reno Chop Shop Bandeja Caixa
{903}{}{Presidente Richardson}           # qhPrzRch.int    ; Enclave Presidente Richardson talking head.
{904}{}{Howitzer}                       # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{Porta}                           # WIEntDor.int    ; Entrance to Sierra Base Porta
{906}{}{Baby Death}                 # OCBabDth.int    ; Baby Deaths in Vault 13
{907}{}{Dangerous Dan}                  # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{Doc Johnson}                    # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{Sheriff Marion}                 # RCMarion.int    ; Sheriff Earl Marion
{910}{}{Prefeito Ascorti}                  # RCAscort.int    ; Prefeito Ascorti of Redding
{911}{}{Nording}                        # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{Velani}                         # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{Ferndown}                       # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{O Dragão}                     # FCDragon.int    ; O Dragão, San Fran
{915}{}{Menino estável}                     # mcSblBoy.int    ; Modoc Menino estável
{916}{}{Comerciante}                         # mcComerciante.int    ; Modoc Comerciante
{917}{}{Townsperson}                    # mcPerson.int    ; Modoc Townspeople
{918}{}{Escória}                           # mcSlgExt.int    ; Ghost Farm Escória Exit Guardaaaaaaaaaaaaaaaaaaaaaaa
{919}{}{Escória}                           # mcSlgGrd.int    ; Ghost Farm Escória Enterance Guardaaaaaaaaaaaaaaaaaaaaaaa
{920}{}{Lo Pan}                         # FCLoPan.int     ; Lo Pan in San Fran.
{921}{}{Texugo}                         # FCTexugo.int    ; Texugo in San Fran.
{922}{}{Josh}                           # RCJosh.int      ; Josh Laurance of Redding
{923}{}{Caminetto}                      # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{Bette}                          # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{Gun Comerciante}                   # FCGunmer.int    ; San Fran's gun Comerciante
{926}{}{Porta}                           # ZIWodDor.int    ; Genérico Wooden Porta
{927}{}{Porta}                           # ZIMtlDor.int    ; Genérico Metal Porta
{928}{}{Emissor}                        # SSEmtN2.int     ; Emissor in NCR area 2
{929}{}{Rato God}                        # ZCRatoGod.int    ; Rato God in Klamath
{930}{}{}                               # ECCaixa.int       ; Random box that has stuff in it.
{931}{}{Kaga}                           # ECKaga1.int     ; Random Encounter Kaga 1
{932}{}{Kaga}                           # ECKaga2.int     ; Random Encounter Kaga 2
{933}{}{Kaga}                           # ECKaga3.int     ; Random Encounter Kaga 3
{934}{}{Kaga}                           # ECKaga4.int     ; Random Encounter Kaga 4
{935}{}{Kaga}                           # ECKaga5.int     ; Random Encounter Kaga 5
{936}{}{Bounty Caçador}                  # ECBCaçador.int   ; Random Encounter Bounty Caçador
{937}{}{Computador}                       # VIMedCom.int    ; Vault City Medical Computador
{938}{}{Computador}                       # VICenCom.int    ; Vault City Central Computador
{939}{}{Computador}                       # VIAloCom.int    ; Vault City Allocation Computador
{940}{}{Darrow}                         # VCDarrow.int    ; Vault City Sub-Amenities Oficial Darrow
{941}{}{Farrell}                        # VCFarrel.int    ; Vault City Sub-Amenities Oficial Farrell
{942}{}{Bar Patron}                     # VCBarPat.int    ; Vault City Bar Patron
{943}{}{Vault Cidadão}                  # VCWrkCit.int    ; Vault City Working Cidadão
{944}{}{Servo de Vault}                  # VCEscravo.int     ; Vault City Escravo
{945}{}{Poço de ventilação}              # VIShft2b.int    ; Vault City Poço de ventilação 2B
{946}{}{Charlie}                        # VCCharli.int    ; Vault City Puking Charlie
{947}{}{Painel de controle de refrigerante}          # GSValve.int     ; Gecko Painel de controle de refrigerante
{948}{}{Cocô}                            # ziBraCocô.int    ; Genérico BRAHMIN SHIT!!! YES YES YES
{949}{}{Conceder}                          # scWesGrd.int    ; Westin's Campo de força Guardaaaaaaaaaaaaaaaaaaaaaaa
{950}{}{Emissor}                        # SSEmiWes.int    ; Westin's Campo de força Emissor
{951}{}{Emissor}                        # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{Computador terminal}              # SICmpWes.int    ; Westin's computer terminal for the field.
{953}{}{Emperor terminal v8.8}          # FSEmpTer.int    ; Computador terminal in San Fran
{954}{}{Vice-Presidente do Pássaro}            # QCBird.int      ; Enclave, Vice-Presidente do Pássaro
{955}{}{Martin}                         # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{Ken Lee}                        # FCKenLee.int    ; Ken Lee in San Francisco
{957}{}{Sargento. Granito}                   # QCGranit.int    ; Sargento. Granito of the Enclave Patrol
{958}{}{Frank Horrigan}                 # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{Script do Mapaa}                     # GeckJunk.int    ; Script do Mapaa for Gecko Junkyard
{960}{}{Script do Mapaa}                     # GeckTunl.int    ; Script do Mapaa for Gecko Tunnels
{961}{}{Porta}                           # SSFrgDor.int    ; Fergus's Porta script
{962}{}{Porta}                           # SSGunDor.int    ; Gunther's Porta script to Tandi
{963}{}{Porta}                           # SSFlxDor.int    ; Félix's Porta script
{964}{}{Corda}                           # SSCorda.int      ; Corda.. for you to climb
{965}{}{Emissor}                        # SSEmiEnt.int    ; Emissor in Ncr Entrance
{966}{}{Dr. Curling}                    # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{Quadro de avisos}                 # SSSign.int      ; Sign in NCR Entrance
{968}{}{Ratoo toupeira}                       # mcMolRato.int    ; Ghost Farm Ratoo toupeira
{969}{}{Secretário do Presidente}          # QCPrsSec.int    ; President's personal intern (uh sectertary)
{970}{}{Tom Murray}                     # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{Sturdy Porta}                    # SSCrpDor.int    ; Craps table door in NCR
{972}{}{Townsperson}                    # mcPeasan.int    ; Modoc Camponês, they attack the farm
{973}{}{Área do Conselho Municipal de Vault}        # VCtyCocl.int    ; Script do Mapaa Área do Conselho Municipal de Vault
{974}{}{Purificador de ar}                   # HSPurify.int    ; Purificador de ar for Broken Hills
{975}{}{Rochas}                          # esEntRks.int    ; Military Base Enterance Rochas
{976}{}{Jogador}                        # RCGamble.int    ; Redding Genérico Jogadors
{977}{}{Script espacial}                 # HtCorpse.int    ; Script espacial for Corpses
{978}{}{SCCheat}                        # SCCheat.int     ; Caráter da fraude for NCR
{979}{}{Prisioneiro}                       # QCGenPrs.int    ; Enclave Genérico Prisioneiro
{980}{}{Cidadão}                        # QCGenCit.int    ; Enclave Genérico Cidadãos
{981}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                          # QCGenGrd.int    ; Enclave Genérico Guardaaaaaaaaaaaaaaaaaaaaaaas
{982}{}{Cientista}                      # QCGenSci.int    ; Enclave Genérico Cientista
{983}{}{terminal}                       # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                               # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                               # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{Emissor}                        # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{Blast Porta}                     # QIBstDr1.int    ; Blast Porta for Reator Off to remain closed
{988}{}{Blast Porta}                     # QIBstDr2.int    ; Blast Porta for Reator On to remain closed
{989}{}{Estoque de Darrow}                 # VIDarCaixa.int    ; Vault City Darrow Shop Inventory
{990}{}{Porta}                           # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{Super Duper Mutante}             # ecTlkMut.int    ; Military Base Conversation Mutantes
{992}{}{Químico}                        # fcChemst.int    ; Químico in San Francisco
{993}{}{Grundel}                        # ecGrunde.int    ; Military Base Mouse Caçador
{994}{}{Criança}                            # ecMelCriança.int    ; Some Town USA, Melchior's Criança
{995}{}{Scanner Retinal}                # WIRetScn.int    ; Scanner Retinal in the Sieera Base
{996}{}{Elevador Porta}                  # WIElvDor.int    ; Elevador Porta in the Seirra Base
{997}{}{Receptivo cibernético}          # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{parede}                           # WIScrtDr.int    ; Sierra Base Secert Porta
{999}{}{Script do Mapaa}                     # broken2.int     ; Script do Mapaa for Broken Hills Mapa 2
{1000}{}{Estoque de Farrell}               # VIFarCaixa.int    ; Vault City Farrell Shop Inventory
{1001}{}{Estoque de Harry}                 # VIHarCaixa.int    ; Vault City Harry Shop Inventory
{1002}{}{Caixa}                           # VICtyCaixa.int    ; Vault City Courtyard Temp Inventory Caixa
{1003}{}{Caixa}                           # VIDwtCaixa.int    ; Vault City Downtown Temp Inventory Caixa
{1004}{}{Derek}                         # dcDerek.int     ; Derek in the Den
{1005}{}{Amigo de Tubby}                # dcTubFri.int    ; Tubby's Toxicómano Friends in the Den
{1006}{}{Jogador}                       # dcGamble.int    ; Jogadors in the Den
{1007}{}{Escravo}                         # dcEscravo.int     ; Pen Escravos in the Den
{1008}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # dcMetRom.int    ; Metzger Quarto Guardaaaaaaaaaaaaaaaaaaaaaaa in the Den
{1009}{}{Escravor}                        # dcPenGrd.int    ; Escravor Pen Guardaaaaaaaaaaaaaaaaaaaaaaa in the Den
{1010}{}{Lara}                          # dcLara.int      ; Lara in the Den
{1011}{}{Tyler}                         # dcTyler.int     ; Tyler in the Den
{1012}{}{Marc}                          # dcMarc.int      ; Marc in the Den
{1013}{}{Quadro de avisos}                # diBulBrd.int    ; Quadro de avisos in the Den
{1014}{}{Escravor}                        # dcVicGrd.int    ; Vic Guardaaaaaaaaaaaaaaaaaaaaaaa in the Den
{1015}{}{Escravor}                        # dcSlvGrt.int    ; Escravor Greeter in the Den
{1016}{}{Fred}                          # dcFred.int      ; Fred in the Den
{1017}{}{Caixa}                           # diFliCaixa.int    ; Estalido Caixa in the Den
{1018}{}{Caixa}                           # diMamãeCaixa.int    ; Mamãe Caixa in the Den
{1019}{}{Caixa}                           # diSmiCaixa.int    ; Smitty Caixa in the Den
{1020}{}{Carrororo Trunk}                     # ZICrTrnk.int    ; generic script for Carrororo Trunk
{1021}{}{Security Porta}                 # QIPzlDor.int    ; Porta for the puzzle room in the Enclave
{1022}{}{Computador terminal}             # FSPhySta.int    ; Physics computer station in San Fran
{1023}{}{Computador terminal}             # FSBioSta.int    ; Biology computer station in San Fran
{1024}{}{Computador terminal}             # FSCheSta.int    ; Químicory computer station in San Fran
{1025}{}{Lao Chou}                      # FCLaoCho.int    ; Comerciante in San Fran
{1026}{}{}                              # FIPapel.int     ; Scrap Papels that combine should only be put on one of the peaces.
{1027}{}{}                              # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{Script do Mapaa}                    # EncTrp.int      ; Script do Mapaa for Enclave Trap Quartos
{1029}{}{Corpo morto}                     # HtCorpo.int      ; Script for dead bodies in Broken Hills
{1030}{}{Fios expostos}                 # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{Caixa}                           # diMetCaixa.int    ; Metzger Caixa from Escravo Crap
{1032}{}{Escravo}                         # dcRunSlv.int    ; Den Escravo Fleeing Escravos
{1033}{}{Escravo}                         # dcAtkSlv.int    ; Den Escravo Hostile Escravos
{1034}{}{Escravor}                        # dcRnSlvr.int    ; Den Escravo Escravors
{1035}{}{Lasca}                          # FCLasca.int      ; Lasca in San Fran no splean
{1036}{}{Reator}                       # QIReactr.int    ; Reator in the Enclave
{1037}{}{Reator Computador}              # QIRctrCm.int    ; Reator Computador in the Enclave
{1038}{}{Tender em dinheiro}                   # RCCshTnd.int    ; Redding Tender em dinheiro in the Casino
{1039}{}{Cash Caixa}                      # RICshCaixa        ; Cash Caixa for the Tender em dinheiro
{1040}{}{Wanamingo}                     # RCWanami.int    ; Wanamingo
{1041}{}{Bar Patron}                    # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{Bar Patron}                    # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{Jail Porta}                     # RIJalDor.int    ; Jail Porta in Redding
{1044}{}{Suze}                          # FCSuze.int      ; Suze in San Fran
{1045}{}{Capitão Ron Meyers}            # FCRonMey.int    ; Capitão Ron Meyers
{1046}{}{Pen Porta}                      # diPenDor.int    ; Escravo Pen Porta in the Den
{1047}{}{Wanamingo Meu}                # RedWan1.int     ; Script do Mapaa for Wanamingo Meu
{1048}{}{Wanamingo Meu Entrance}       # RedWane.int     ; Script do Mapaa for Wanamingo Meu Entrance
{1049}{}{Frog Morton}                   # RCFrog.int      ; Frog Morton
{1050}{}{Dave H.}                       # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{Porta}                          # diVicDor.int    ; Vic's Quarto Porta in the Den
{1052}{}{Porta}                          # diRomDor.int    ; Metzger's Quarto Porta in the Den
{1053}{}{Puking Charlie}                # vccharly.int    ; Puking Charlie in Vault Courtyard
{1054}{}{Pintura}                      # SIPaint.int     ; Revales Vault 13 on examination.
{1055}{}{Script do Mapaa}                    # SFChina.int     ; San Fran China Mapa
{1056}{}{Barman}                     # VCCouBar.int    ; Área do Conselho Municipal de Vault Barman
{1057}{}{Caixa}                           # VIBarCaixa.int    ; Vault City Escravo Sale Inventory Dump
{1058}{}{Auto-Doc}                      # VIAutDoc.int    ; Vault City Courtyard Auto-Doc
{1059}{}{}                              # RIMinEnt.int    ; Entrance Back to the Meus
{1060}{}{Túnel de mineração}                 # RedMTun.int     ; Script do Mapaa for Túnel de mineração
{1061}{}{Robô}                         # KCRob.int       ; Robô on Klamath Canyon
{1062}{}{}                              # FiGunTbl.int    ; Gun Comerciante table in San fran
{1063}{}{Script do Mapaa}                    # KlaMall.int     ; Script do Mapaa for Klamath Mall area
{1064}{}{Script do Mapaa}                    # KlaTrap.int     ; Script do Mapaa for Klamath Ainda area
{1065}{}{Lydia}                         # VCDwnBar.int    ; Vault City Downtown Barman
{1066}{}{}                              # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{Homem foguete}                     # FCRocHomem.int    ; Rocket man in San Fran
{1068}{}{AHS-7}                         # FCOz7.int       ; Oz 7 in San Fran
{1069}{}{Crockett}                      # FCCrocke.int    ; Crockett in San Fran
{1070}{}{Amanda}                        # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{Joshua}                        # VCJoshua.int    ; Vault City Courtyard Joshua, Escravo
{1072}{}{Valerie}                       # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{Sistema de Ensino}               # VITeach.int     ; Vault City Sistema de Ensino
{1074}{}{Caixa}                         # diCaixa.int     ; Den Caixa in Church
{1075}{}{Peeing Guy}                    # VCUrine.int     ; Peeing Guy in Área do Conselho Municipal de Vault
{1076}{}{Curtis}                        # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{Marc}                          # FCMarc.int      ; Marc, Punk in San Fran
{1078}{}{Computador}                      # FSElComp.int    ; Hubologists computer
{1079}{}{AHS-9}                         # FCOz9.int       ; Hubologist main dude
{1080}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # FCElGrd.int     ; Hubologist's guards
{1081}{}{Pilha de pedras}                 # VIRochas.int     ; Pile of Rochas w/ Hidden Wrench
{1082}{}{Porta}                          # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # dcRebGrd.int    ; Den Rebecca Guardaaaaaaaaaaaaaaaaaaaaaaa
{1084}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # dcRebDor.int    ; Den Rebecca Porta Guardaaaaaaaaaaaaaaaaaaaaaaa
{1085}{}{Porta}                          # diRebDor.int    ; Den Rebecca Porta
{1086}{}{Sinal de Procurados}                   # ZSWsign.int     ; Genérico Sinal de Procurados
{1087}{}{Dr. Wong}                      # FCDrWong.int    ; Dr. Wong in San Fran area
{1088}{}{Mesa}                         # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{Porta}                          # WILv1Dor.int    ; Locked Porta on Level 1 Entrance               # local_vars=8
{1090}{}{Punk}                          # FCFemPnk.int    ; San Fran Female punk
{1091}{}{Punk}                          # FCMalPnk.int    ; San Fran Male Punk
{1092}{}{Ryan}                          # FCRyan.int      ; San Fran Punk Ryan
{1093}{}{Caixa}                           # HIBh1Caixa.int    ; Broken Hills Temp Inventory Caixa
{1094}{}{}                              # FCJuavki.int    ; Juan and Vikkin in San Fran Elron Camp
{1095}{}{Homemhole}                       # HIHomemHol.int    ; Homemhole to Basement in Liz's Store
{1096}{}{Script do Mapaa}                    # SFElronb.int    ; Elron Base map Script
{1097}{}{Escada}                        # HIEscada.int    ; Escada up to Liz's Store
{1098}{}{Saco de pancadas}                  # WIPnchBg.int    ; Saco de pancadas in the Sierra Depot
{1099}{}{Porta}                          # WIBayDor.int    ; Sierra Base Repair Bay Porta
{1100}{}{Alarmee}                         # GSAlarmee.int     ; Gecko Reator alarm
{1101}{}{Placa de piso}                   # WIPlTrp2.int    ; Plasma Chão Trap Level 2 of Seirra
{1102}{}{Placa de piso}                   # WIPlTrp3.int    ; Plasma Chão Trap Level 2 of Seirra
{1103}{}{Placa de piso}                   # WIPlTrp4.int    ; Plasma Chão Trap Level 2 of Seirra
{1104}{}{Placa de piso}                   # WIPlTrp5.int    ; Plasma Chão Trap Level 2 of Seirra
{1105}{}{Placa de piso}                   # WIPlTrp6.int    ; Plasma Chão Trap Level 2 of Seirra
{1106}{}{Placa de piso}                   # WIPlTrp7.int    ; Plasma Chão Trap Level 2 of Seirra
{1107}{}{Placa de piso}                   # WIPlTrp8.int    ; Plasma Chão Trap Level 2 of Seirra
{1108}{}{Placa de piso}                   # WIPlTrp9.int    ; Plasma Chão Trap Level 2 of Seirra
{1109}{}{Placa de piso}                   # WIPlTrpA.int    ; Plasma Chão Trap Level 2 of Seirra
{1110}{}{Placa de piso}                   # WIPlTrpB.int    ; Plasma Chão Trap Level 2 of Seirra
{1111}{}{Placa de piso}                   # WIPlTrpC.int    ; Plasma Chão Trap Level 2 of Seirra
{1112}{}{Placa de piso}                   # WIPlTrpD.int    ; Plasma Chão Trap Level 2 of Seirra
{1113}{}{Placa de piso}                   # WIPlTrpE.int    ; Plasma Chão Trap Level 2 of Seirra
{1114}{}{Placa de piso}                   # WIPlTrpF.int    ; Plasma Chão Trap Level 2 of Seirra
{1115}{}{Emissor}                       # WSEmit4a.int    ; Emissor, Level 4 in Sierra Base
{1116}{}{Emissor}                       # WSEmit4b.int    ; Emissor, Level 4 in Sierra Base
{1117}{}{Emissor}                       # WSEmit4c.int    ; Emissor, Level 4 in Sierra Base
{1118}{}{Campo de força}                   # WSFeld4a.int    ; Campo de força, Level 4 in Sierra Base
{1119}{}{Campo de força}                   # WSFeld4b.int    ; Campo de força, Level 4 in Sierra Base
{1120}{}{Campo de força}                   # WSFeld4c.int    ; Campo de força, Level 4 in Sierra Base
{1121}{}{Hubologist}                    # FCElrInd.int    ; Elron Indoctrinee
{1122}{}{Computador}                      # FStnkCmp.int    ; Posiden Tanker Computador
{1123}{}{Bunker Porta}                   # WIBnkDor.int    ; Bunker Porta for the Sierra Depot
{1124}{}{Portão}                          # miPortão.int      ; Modoc Portão
{1125}{}{Caixa}                           # WITrpBx1.int    ; Sierra Base Trapped Caixa
{1126}{}{Morton Brother}                # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{Emissor}                       # FSEmt1.int      ; Campo de força emitter 1 in San Fran
{1128}{}{Emissor}                       # FSEmt2.int      ; Campo de força emitter 2 in San Fran
{1129}{}{Emissor}                       # FSEmt3.int      ; Campo de força emitter 3 in San Fran
{1130}{}{Script do Mapaa}                    # Cave6.int       ; Fake Vault 13 Cave map
{1131}{}{Chet}                          # VCChet.int      ; Illicit Allocations Oficial Chet
{1132}{}{Script do Mapaa}                    # NewRVB.int      ; New Reno Helicopter Script Mapa
{1133}{}{Vertibird}                     # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{Salvatore Guardaaaaaaaaaaaaaaaaaaaaaaa}               # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{Salvatore Guardaaaaaaaaaaaaaaaaaaaaaaa}               # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{Soldados}                      # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{Soldados}                      # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{Caixa}                         # niHSCrat.int    ; New Reno Helicopter Script Caixa
{1139}{}{Sr. Handy}                     # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{Salvatore Guardaaaaaaaaaaaaaaaaaaaaaaa}               # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guardaaaaaaaaaaaaaaaaaaaaaaa
{1141}{}{Script espacial}                # ntHSGrd.int     ; New Reno Helicopter Script Guardaaaaaaaaaaaaaaaaaaaaaaaing Spacial
{1142}{}{Porta}                          # niEldDor.int    ; New Reno Elderidge Porta
{1143}{}{Porta}                          # niSalDor.int    ; New Reno Salvatore Porta
{1144}{}{Porta}                          # niMyrDor.int    ; New Reno Myron Porta
{1145}{}{}                              # FcMonst.int     ; Monster in the PMS Tanker
{1146}{}{Script do Mapaa}                    # SFTanker.int    ; San Fran Tanker map
{1147}{}{Escravo}                         # VCSlav2.int     ; Vault City Prisioneiro Escravos
{1148}{}{Vault Cidadão}                 # VCBarCit.int    ; Vault City Bar Patron
{1149}{}{Porta}                          # niBasDor.int    ; New Reno Locking Portas
{1150}{}{Caixaer}                         # ncFightr.int    ; New Reno Caixaer Actually Fighting
{1151}{}{Vault Porta}                    # RIVltDor.int    ; Locked Vault Porta in Redding
{1152}{}{Xarn}                          # CcXarn.int      ; Xarn in Navarro
{1153}{}{Raul}                          # CcRaul.int      ; Raul in Navarro
{1154}{}{Quincy}                        # CcQuincy.int    ; Quincy in Navarro
{1155}{}{Intendente}                 # CcQmstr.int     ; Intendente in Navarro
{1156}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # CcMedGrd.int    ; Med Lab Guardaaaaaaaaaaaaaaaaaaaaaaa in Navarro
{1157}{}{Cybernetic Cachorro}                # CcK9.int        ; K9 in Navarro
{1158}{}{Médico}                        # CcMédico.int    ; Dr Shreber in Navarro
{1159}{}{Técnico}                    # CcATech.int     ; Air Tech in Navarro
{1160}{}{Técnico}                    # CcACon.int      ; Air Control in Navarro
{1161}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # CcDrGrd.int     ; Porta Guardaaaaaaaaaaaaaaaaaaaaaaa in Navarro
{1162}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # Ccggbak.int     ; Portão Guardaaaaaaaaaaaaaaaaaaaaaaa Backup in Navarro
{1163}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # CcGrdca.int     ; Guardaaaaaaaaaaaaaaaaaaaaaaa (combat armor) in Navarro
{1164}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # CcGrdpa.int     ; Guardaaaaaaaaaaaaaaaaaaaaaaa (power armor) in Navarro
{1165}{}{Técnico}                    # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{Técnico}                    # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{Técnico}                    # CcComp1.int     ; Computador Tech1 in Navarro
{1168}{}{Técnico}                    # CcComp2.int     ; Computador Tech2 in Navarro
{1169}{}{Cave In}                       # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{Enclave Patroler}              # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{Blast Porta}                    # QIEndDor.int    ; Portas at the End Fight Area
{1172}{}{Script do Mapaa}                    # EncDet.int      ; Script do Mapaa for Enclave Detention Center
{1173}{}{Script do Mapaa}                    # EncDoca.int     ; Script do Mapaa for Enclave Doca
{1174}{}{Script do Mapaa}                    # EncGd.int       ; Script do Mapaa for Enclave Guardaaaaaaaaaaaaaaaaaaaaaaa Barracks
{1175}{}{Script do Mapaa}                    # EncPres.int     ; Script do Mapaa for Enclave Presidential Area
{1176}{}{Script do Mapaa}                    # EncRetr.int     ; Script do Mapaa for Enclave Reator Area
{1177}{}{Script do Mapaa}                    # EncFite.int     ; Script do Mapaa for Enclave Fight Area
{1178}{}{Security Robô}                # QCSecBot.int    ; Enclave Security Robô
{1179}{}{Cocôr Caixa}                      # niTulCaixa.int    ; New Reno Cocôr Caixa
{1180}{}{Corpo}                          # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{Caixa}                           # HiJacCaixa.int    ; Broken Hills Jacob inventory box
{1182}{}{Caixa}                           # HiDocCaixa.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{Caixa}                           # HiOutCaixa.int    ; Broken Hills Outfitter inventory box
{1184}{}{Carrororoavan Guardaaaaaaaaaaaaaaaaaaaaaaa}                 # RCCvnGrd.int    ; Genérico Carrororoavan Guardaaaaaaaaaaaaaaaaaaaaaaa
{1185}{}{Carrororoavan Driver}                # RCCvnDrv.int    ; Genérico Carrororoavan Driver
{1186}{}{Apresentador de Anel}                # ncAnounc.int    ; New Reno Caixaing Anouncer
{1187}{}{Ring Girl}                     # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{Caixaer}                         # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{Porta}                          # VIVltDr2.int    ; Vault Portas in Vault 8
{1190}{}{Caráter da fraude}               # ncCheat.int     ; New Reno Caráter da fraude
{1191}{}{Holodisk}                      # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{Holodisk}                      # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{Holodisk}                      # FIElrDsk.int    ; Hubologist Holodisk
{1194}{}{Nota}                          # HINota.int      ; Script for Francis/Zaius Nota
{1195}{}{Cachorromeat}                       # ECCachorroMet.int    ; Cachorro Meat from Special random encounter
{1196}{}{Cat's Paw Magazine # 5}         # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{Corsários Mapa}                   # niRaiMapa.int    ; New Reno Corsários Mapa in Bishop's Seguro
{1198}{}{Pariah Cachorro}                    # ECPariah.int    ; Pariah Cachorro in Low Luck encounter
{1199}{}{Klaxon}                        # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{Meu}                          # IIMeu.int      ; Meus in Corsários Cave
{1201}{}{Cova}                           # IICova.int       ; Covas in the Corsários Cave
{1202}{}{Tanker Comerciante}               # FCTnkGmr.int    ; Tanker Gun Comerciante San Fran
{1203}{}{Tanker Barman}              # FCTnkBar.int    ; Tanker Bar Tender
{1204}{}{Tanker Comerciante}               # FCTnkMer.int    ; Tanker Comerciante
{1205}{}{}                              # FITGunTb.int    ; Tanker Gun Mer's table
{1206}{}{}                              # FITMerTb.int    ; Tanker Comerciante's Mesa
{1207}{}{Emissor}                       # FSPemtr1.int    ; Palace Emissor 1
{1208}{}{Emissor}                       # FSPemtr2.int    ; Palace Emissor 2
{1209}{}{Emissor}                       # FSPemtr3.int    ; Palace Emissor 3
{1210}{}{Emissor}                       # FSEmpEmt.int    ; Emporor Computador's Campo de força
{1211}{}{Fallout 2 Hintbook}            # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                              # csTouch.int     ; Script to signal if dude touches container objects (in Navarro)
{1213}{}{}                              # csArea.int      ; Script to signal if dude enters an area (in Navarro)
{1214}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # RCAscGrd.int    ; Genérico Guardaaaaaaaaaaaaaaaaaaaaaaa for Ascorti's Bar
{1215}{}{Prospector}                    # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{Bootleggers}                   # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                              # csOpen.int      ; Script to signal if dude uses door w/o permision (in Navarro)
{1218}{}{Dan}                           # hcDan.int       ; Dan, Cônjuge of murdered conspirator.
{1219}{}{Shitty Comedian}               # ncComedi.int    ; New Reno Comedian
{1220}{}{Cantor do Trashcan}               # ncBand.int      ; New Reno Trashcan Band
{1221}{}{Script do Mapaa}                    # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                              # csPortão.int      ; Script to signal if dude uses gate w/o permision (in Navarro)
{1223}{}{Grave}                         # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{Coffin Willie}                 # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{Computador de entrada sem chave}        # FSFobTer.int    ; Fob terminal
{1226}{}{Keyless entry Porta}            # FSFobDor.int    ; Fob Porta
{1227}{}{Computador}                      # ccNComp.int     ; Navarro Computador
{1228}{}{Kohl}                          # vcKohl.int      ; Vault City Info Oficial Kohl
{1229}{}{Criança}                         # ECCriança.int     ; Random Encounter Criançaren
{1230}{}{cozinhar}                          # cccozinhar.int      ; Navarro cozinhar
{1231}{}{Torre}                        # ccTorre.int    ; Navarro Torre
{1232}{}{Brian}                         # hcBrian.int     ; Brian, the Power Técnico
{1233}{}{Gerador}                     # hiPower.int     ; Power Gerador for Broken Hills
{1234}{}{Console}                       # hiConsole.int   ; Power Station Console in Broken Hills
{1235}{}{Formiga gigante}                     # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{Formiga gigante}                     # hcAnt2.int      ; Broken Hills Ant - Missing Person Quest
{1237}{}{Porta}                          # csXPorta.int     ; Another lousy door script -signals xarn to leave
{1238}{}{}                              # htSecret.int    ; Spatial for secret area of Broken Hills Meu
{1239}{}{Caixa}                           # niEthCaixa.int    ; New Reno Ethyl Wright Shop Caixa
{1240}{}{Eric}                          # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                              # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{Caixa}                           # viRanCaixa.int    ; Randal's Stock Caixa in Vault City
{1243}{}{Giant Escorpião}                # iiScorp.int     ; Corsários Escorpiãos 2X poison
{1244}{}{Jane}                          # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                              # VTAloMrk.int    ; Script espacial for Allocation Computador VCity
{1246}{}{Script do Mapaa}                    # Cave7.int       ; Fake Vault 13 map
{1247}{}{Dermal Pip Boy}                # niDermal.int    ; New Reno Dermal Pip Boy
{1248}{}{Cocôch}                         # ncEldCachorro.int    ; New Reno Eldridge Cachorros
{1249}{}{Ratotray}                       # RCRatoray.int    ; Ratotray, Doc Johnson's assistant
{1250}{}{Cônjuge}                        # HCHusWif.int    ; Mutante Husband/Wife Broken Hills
{1251}{}{LoPan Guardaaaaaaaaaaaaaaaaaaaaaaa}                   # FCLoGrd.int     ; LoPan Guardaaaaaaaaaaaaaaaaaaaaaaa in San Fran
{1252}{}{Script do Mapaa}                    # Navarro.int     ; Mapa script for Navarro
{1253}{}{Porta}                          # VIVltDr3.int    ; Vault Porta in Vault 8 - Martin
{1254}{}{Cybernetic Cachorro}                # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{Luke}                          # FCNLuke.int     ; Luke in NCR
{1256}{}{Joshua}                        # FCDJosh.int     ; Joshua BOS in the Den
{1257}{}{Portão}                          # iiLockDr.int    ; Portãos in Corsários area
{1258}{}{Matt}                          # FCFmatt.int     ; Matt in San Fran BOS
{1259}{}{Porta}                          # FSBroDor.int    ; Brotherhood Porta
{1260}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # hcGrd2.int      ; Bank Guardaaaaaaaaaaaaaaaaaaaaaaa 2 in Broken Hills
{1261}{}{Porta}                          # QIGeckDr.int    ; Porta Requiring the player to use the geck
{1262}{}{Computador}                      # FSFace.int      ; Ace Computador system in San Fran
{1263}{}{terminal}                      # QITurTrm.int    ; Genérico Enclave Torre terminal
{1264}{}{Torre}                        # QCTorre.int    ; Enclave Torres
{1265}{}{Chuck Stodgers}                # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                              # htChuck.int     ; Script espacial for waking up Chuck
{1267}{}{terminal}                      # viTerm.int      ; Vault City Vault terminal
{1268}{}{Gang Thug}                     # RCMotGng.int    ; Frog Morton's gang
{1269}{}{Cheater}                       # ccCheat.int     ; Cheat character in Navarro
{1270}{}{}                              # FSTnkrdr.int    ; Tanker Portas in San Fran
{1271}{}{Camponês}                       # OCPeaon.int     ; NCR peaons
{1272}{}{A Flor da Lavanda}           # diRebBok.int    ; Den Becky's Book
{1273}{}{Radscorpion}                   # hcScorp.int     ; Broken Hills Escorpião
{1274}{}{Professor}                     # hcProf.int      ; Broken Hills Professor
{1275}{}{Caixa}                           # hiPrfBx1.int    ; Professor's Caixa in Broken Hills
{1276}{}{Caixa}                           # hiPrfBx2.int    ; Professor's Caixa in Broken Hills
{1277}{}{Seymour}                       # hcSeymore.int   ; Seymour the talking Plant/Broken Hills
{1278}{}{John Sullivan}                 # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{Grumoso}                         # hcGrumoso.int     ; Grumoso the car accident victim - Broken Hills
{1280}{}{}                              # BISpyHol.int    ; Spy Holodisk for NCR
{1281}{}{}                              # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                              # SIWesHol.int    ; Westin Holodisk
{1283}{}{Guardaaaaaaaaaaaaaaaaaaaaaaa}                         # SCBGrd.int      ; Buster's Guardaaaaaaaaaaaaaaaaaaaaaaa
{1284}{}{}                              # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                              # SIGcaObj.int    ; NCR Guardaaaaaaaaaaaaaaaaaaaaaaa Captain notify obj
{1286}{}{Typhon}                        # hcTyphon.int    ; Typhon, Son of Conjunto - Broken Hills
{1287}{}{Escolta}                     # ECBdyGrd.int    ; CorpoGuardaaaaaaaaaaaaaaaaaaaaaaa in Vignette
{1288}{}{Script do Mapaa}                    # GamMovie.int    ; Game Movie map
{1289}{}{Armário}                        # ziArmário.int    ; Genérico Armário Script
{1290}{}{Bem}                          # hiBem.int      ; Broken Hills Bem
{1291}{}{Micky}                         # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{Torre}                        # WCTorre.int    ; Torre for Sierra Depot
{1293}{}{Old canibal}                     # hcOldGhl.int    ; canibals in Old-Folks Home - Broken Hills
{1294}{}{Henchman}                      # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{Elmo}                          # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{Banheiro}                        # niBanheiro.int    ; Banheiro - Contains Grenades - New Reno
{1297}{}{Cruz}                         # niCruz.int     ; Cruz - Golgotha - Buried Cash
{1298}{}{Arado}                          # viArado1.int     ; Arado - Vault City
{1299}{}{Arado}                          # viArado2.int     ; Arado - Vault City
{1300}{}{Escorpião}                      # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{Gerador}                     # kcGnratr.int    ; Gerador player repairs in toxic caves
{1302}{}{Porta}                          # kcLvatr.int     ; Elevador door in toxic caves
{1303}{}{Porta}                          # SIVDor.int      ; Vortis Escravo Porta
{1304}{}{Medical Pip Boy}               # niMedica.int    ; New Reno "Médico Skill" Upgrade
{1305}{}{Armário}                        # niPrstLk.int    ; New Reno Prostituta"Armário"
{1306}{}{Armário}                        # niBigJLk.int    ; New Reno Big Jesus "Armário"
{1307}{}{Armário}                        # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Armário"
{1308}{}{Armário}                        # niCaixarLk.int    ; New Reno Caixaer "Armário"
{1309}{}{Armário}                        # niBis1Lk.int    ; New Reno Bishop Family OK "Armário"
{1310}{}{Armário}                        # niPornLk.int    ; New Reno Atriz pornô "Armário"
{1311}{}{Armário}                        # niBtchLk.int    ; New Reno Cadela "Armário"
{1312}{}{Armário}                        # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Armário"
{1313}{}{Armário}                        # niEldrLk.int    ; New Reno Eldridge "Armário"
{1314}{}{Armário}                        # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Armário"
{1315}{}{Armário}                        # niOWriLk.int    ; New Reno Orville Wright "Armário"
{1316}{}{Armário}                        # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Armário"
{1317}{}{Armário}                        # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Armário"
{1318}{}{Armário}                        # niMyGdLk.int    ; New Reno Myron Guardaaaaaaaaaaaaaaaaaaaaaaa "Armário"
{1319}{}{Armário}                        # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Armário"
{1320}{}{Armário}                        # niMyrnLk.int    ; New Reno Myron "Armário"
{1321}{}{Armário}                        # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Armário"
{1322}{}{Armário}                        # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Armário"
{1323}{}{Armário}                        # niTryLk.int     ; New Reno Tray "Armário"
{1324}{}{Armário}                        # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{Script do Mapaa}                    # rndtoxic.int    ; Random Toxic Mapa
{1326}{}{Você não pode me ver}              # ecirrad.int     ; critter that irradates
{1327}{}{Tin Woodsman}                  # ecTinWod.int    ; Tin Woodsman
{1328}{}{Script do Mapaa}                    # rndTinWd.int    ; Tin Woodsman Script do Mapaa
{1329}{}{Formação de pedra}               # ecGrdFrv.int    ; Guardaaaaaaaaaaaaaaaaaaaaaaaian of Forever
{1330}{}{}                              # rndForvr.int    ; Guardaaaaaaaaaaaaaaaaaaaaaaaian of Forever Rnd Enct Script do Mapaa
{1331}{}{terminal}                      # ecGrdTrm.int    ; Guardaaaaaaaaaaaaaaaaaaaaaaaian of Forever Water Lasca terminal
{1332}{}{Armário}                        # niEld2Lk.int    ; New Reno Eldridge "Armário" HARD LOCK
{1333}{}{}                              # SiRagobj.int    ; Uhh box that Rondó cares
{1334}{}{Script do Mapaa}                    # SFCHINA2.int    ; China 2 map
{1335}{}{Bot de segurança}                  # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{Bot de segurança}                  # KCWupass.int    ; Klamath Guardaaaaaaaaaaaaaaaaaaaaaaa Robô under Toxic Caves
{1337}{}{Armário}                        # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{Armário}                        # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{Armário}                        # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{Armário}                        # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{Armário}                        # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{Armário}                        # viCGWch1.int    ; VCty - Prison Porta Watch Script
{1343}{}{Armário}                        # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{Armário}                        # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{Armário}                        # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{Armário}                        # viStkWch.int    ; VCty - Rígido Watch Script
{1347}{}{Armário}                        # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{Armário}                        # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{Armário}                        # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{Armário}                        # viWalWch.int    ; VCty - paredeace Watch Script
{1351}{}{Armário}                        # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{Armário}                        # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{Armário}                        # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{Armário}                        # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{Armário}                        # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{Armário}                        # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{Doca Squatter}                 # FCDocSqa.int    ; San Fran - Doc Squatter
{1358}{}{Doca Criança}                      # FCDocCriança.int    ; San Fran - Doc Crianças
{1359}{}{Script do Mapaa}                    # RndWhale.int    ; Random Whale Script
{1360}{}{Percy Crump}                   # gcPercy.int     ; Percy Crump, Gecko Comerciante
{1361}{}{Caixa}                           # giPerCaixa.int    ; Percy's Stock Caixa
{1362}{}{Caixa}                           # giJnkCaixa.int    ; Gecko Junkyard Temp Inventory Caixa
{1363}{}{Porta}                          # niWriDor.int    ; New Reno Wright Quarto Porta
{1364}{}{O Grande Ananias}             # dcAnan.int      ; O Grande Ananias, Mummy Master
{1365}{}{Script do Mapaa}                    # RndUVilg.int    ; Unwashed Aldeão map
{1366}{}{Unwashed Aldeão}             # ECWash.int      ; Unwashed Aldeãos... Ug You figure out where they go.
{1367}{}{Spammer}                       # ECSpammr.int    ; Spammer in Unwashed Encounter
{1368}{}{Mapa}                           # eiSanMapa.int    ; Military Base San Francisco Mapa
{1369}{}{Script do Mapaa}                    # RndShutl.int    ; Random Shuttle Mapa
{1370}{}{Script do Mapaa}                    # rndParih.int    ; Random Pariah Script do Mapaa
{1371}{}{Script do Mapaa}                    # rndBHead.int    ; Random Cabeça grande map
{1372}{}{Script do Mapaa}                    # rndcafe.int     ; Random Cafe Mapa
{1373}{}{Máquina Nuka-Cola}             # ZINuke.int      ; Máquina Nuka-Cola
{1374}{}{Doca}                          # sfdock.int      ; map script for San Fran Doca
{1375}{}{Porta}                          # ciCrisDr.int    ; Chris's Porta
{1376}{}{Land Meu}                     # rtlndmin.int    ; Redding Land Meus
{1377}{}{Land Meu}                     # wtlndmin.int    ; Sierra Depot Land Meus
{1378}{}{Seu ex}                       # ncExSpou.int    ; New Reno Ex-Cônjuge script
{1379}{}{Mel}                           # ECMel.int       ; Mel that Cachorromeat Creates.
{1380}{}{Vent}                          # ciVent.int      ; Vent into Navarro
{1381}{}{Kevin}                         # ccKevin.int     ; Kevin in Navarro
{1382}{}{Alarmee}                         # csAlarmee.int     ; Navarro base on alert lights
{1383}{}{Armário}                        # ciQunWch.int    ; Quincy Armário watch script
{1384}{}{Armário}                        # ciRulWch.int    ; Raul Armário Watch Script
{1385}{}{Armário}                        # ciCmdWch.int    ; Commanded Armário Watch Script
{1386}{}{}                              # SSSign.int      ; NCR Statue
{1387}{}{}                              # ctFob.int       ; Fob EXP Script espacial
{1388}{}{}                              # ctPlans.int     ; Vertibird EXP Script espacial
{1389}{}{}                              # ctK9Part.int    ; K9 Part EXP Script espacial
{1390}{}{}                              # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                              # csOpen2.int      ; Script to signal if dude uses door w/o permision (in Navarro)
{1392}{}{}                              # ctSound.int     ; Soundproof Quarto Script espacial
{1393}{}{}                              # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{Bootlegger}                    # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                              # ziWeakLk.int    ; Genérico Weak Lock Watch Script
{1396}{}{}                              # ziMedmLk.int    ; Genérico Medium Lock Watch Script
{1397}{}{Carrororony Criança}                     # dcCarrororonKd.int    ; Carrororony Criança - The Den
{1398}{}{}                              # ciDocWch.int    ; Raul Armário Watch Script
{1399}{}{}                              # ziHardLk.int    ; Genérico Hard Lock Watch Script
{1400}{}{Meu}                          # CIMeu.int      ; Meus in Corsários Cave
{1401}{}{Armário}                        # niBisHLk.int    ; New Reno Bishop Hard Armário
{1402}{}{Porta}                          # niBisHDr.int    ; New Reno Bishop Hard Locked Porta
{1403}{}{}                              # ntRicRom.int    ; New Reno Richard Wright Quarto Spacial
