#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#
# Text labels and messages used by town and world map
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#

#
# Town map entry-point selection names
#
# Format:
#	city type.
#	Up to 10 selection names
#
# Arroyo
{200}{}{Ponte}
{201}{}{Aldeia}
{202}{}{Entrada do Templo}
{203}{}{Região selvagem}
{204}{}{Interior do Templo}
#
# Den
{210}{}{lado oeste}
{211}{}{zona leste}
{212}{}{Den residencial}
#
# Klamath
{220}{}{Centro da cidade}
{221}{}{Cidade Trapper}
{222}{}{Cavernaaaaaaaaas de ratos}
{223}{}{Trapping Grounds}
{224}{}{Área de pastoreio}
{225}{}{Canyon}
#
# Modoc
{230}{}{Rua principal}
{231}{}{Bed and Breakfast}
{232}{}{Brahmin Pastas de Grisham}
{233}{}{Jardim de Farrel}
{234}{}{Down the John}
{235}{}{Cidade Bem}
#
# Cofre Cidade
{240}{}{Pátio}
{241}{}{Cidade Inner}
{242}{}{Conselho}
{243}{}{Cofre}
#
# Gecko
{250}{}{Assentamento}
{251}{}{Usina elétrica}
{252}{}{Junkyard}
{253}{}{Túneis de acesso}
#
# Broken Hills
{260}{}{Centro da cidade}
{261}{}{residencial}
#
# New Reno
{270}{}{Virgin Street}
{271}{}{Rua 2}
{272}{}{Fila Comercial}
{273}{}{zona leste}
{274}{}{Chop Shop}
{275}{}{Arena de boxe}
{276}{}{Área Vertibird}
#
# Sierra Army Base
{280}{}{Campo de batalha}
{281}{}{Depósito Nível 1: Pessoal}
{282}{}{Depósito Nível 2: Armazém Baía}
{283}{}{Depósito Nível 3: Laboratório de robótica}
{284}{}{Depot Nível 4: Bio Research Lab}
#
# Cofre 15
{290}{}{The Squat}
{291}{}{Squatters}
{292}{}{Squatters}
{293}{}{Cofre 15}
{294}{}{Entrada do Leste}
#
# New California Republic
{300}{}{Bazar}
{301}{}{Conselho 2}
{302}{}{Centro da cidade}
{303}{}{Conselho Hall}
{304}{}{Westin Ranch}
{305}{}{Terras de pastagem}
#
# Cofre 13
{310}{}{Entrada da caverna}
{311}{}{Cofre 13}
#
# Military Base
{320}{}{Entrada}
{321}{}{Nível 1}
{322}{}{Nível 2}
{323}{}{Nível 3}
{324}{}{Nível 4}
#
# Redding
{330}{}{Centro da cidade}
{331}{}{Great Wanamingo Mine}
{332}{}{Wanamingo Mine}
{333}{}{Acampamento de mineração}
{334}{}{Centro da cidade Tunnels}
{335}{}{Túneis de minas}
#
# San Francisco
{340}{}{Chinatown}
{341}{}{Doca}
{342}{}{Petroleiro}
{343}{}{Shuttle Exterior}
{344}{}{Shuttle Interior}
{345}{}{Hubologists}
{346}{}{Templo de Shi}
#
# Navarro
{350}{}{Posto de gasolina}
{351}{}{Portão principal}
#
# The Enclave
{360}{}{Doca}
{361}{}{Centro de Detenção}
{362}{}{End Boss}
{363}{}{Casernas}
{364}{}{Área Presidencial}
{365}{}{Reator}
{366}{}{Sala de armadilhas}
#
# Abbey
{370}{}{Erro: em branco}
#
# Primitive Tribe
{380}{}{Erro: em branco}
#
# Environmental Protection Agency
{390}{}{Erro: em branco}
#
# Modoc: Ghost Town Sub-Area
{400}{}{The Ghost Town}
{401}{}{Cavernaaaaaaaaa principal}
{402}{}{Lago subterrâneo}
#
# Car Out of Gas
{410}{}{Car outta power}
#
# Destroyed Arroyo
{420}{}{Destroyed Ponte}
#
# Klamath Cavernaaaaaaaaas tóxicas
{430}{}{Cavernaaaaaaaaas tóxicas}
#
# Den Slave Runs
{440}{}{Den Slave Run}
#
# Raiders
{450}{}{Bem}
{451}{}{Penhasco}
{452}{}{Cave de entrada}
#
# Random Encounter Desertoooooooooooooooooooo
{460}{}{Desertoooooooooooooooooooo}
{461}{}{Desertoooooooooooooooooooo}
{462}{}{Desertoooooooooooooooooooo}
{463}{}{Desertoooooooooooooooooooo}
{464}{}{Desertoooooooooooooooooooo}
{465}{}{Desertoooooooooooooooooooo}
{466}{}{Desertoooooooooooooooooooo}
{467}{}{Desertoooooooooooooooooooo}
{468}{}{Desertoooooooooooooooooooo}
{469}{}{Desertoooooooooooooooooooo}
#
# Random Encounter Montanha
{470}{}{Montanha}
{471}{}{Cavernaaaaaaaa}
{472}{}{Montanha}
{473}{}{Cavernaaaaaaaa}
{474}{}{Cavernaaaaaaaa}
{475}{}{Cavernaaaaaaaa}
{476}{}{Cavernaaaaaaaa}
{477}{}{Cavernaaaaaaaa}
{478}{}{Montanha}
{479}{}{Montanha}
#
# Random Encounter Cidade
{480}{}{Cidade arruinada}
{481}{}{Cidade arruinada}
{482}{}{Cidade arruinada}
{483}{}{Cidade arruinada}
{484}{}{Cidade arruinada}
{485}{}{Cidade arruinada}
{486}{}{Cidade arruinada}
{487}{}{Cidade arruinada}
#
# Random Encounter Costa
{490}{}{Litoral}
{491}{}{Litoral}
{492}{}{Litoral}
{493}{}{Litoral}
{494}{}{Litoral}
{495}{}{Litoral}
{496}{}{Litoral}
{497}{}{Litoral}
{498}{}{Litoral}
{499}{}{Litoral}
#
# New Reno: Golgatha
{500}{}{Gólgota}
#
# Special Encounter: Whale Encounter
{510}{}{Tripas de baleias esmagadas}
#
# Special Encounter: Tin Woodsman
{520}{}{Tin Woodsman}
#
# Special Encounter: Cabeça grande
{521}{}{Cabeça grande}
#
# Special Encounter: Crashed Federation Shuttle
{530}{}{Local de acidente}
#
# Special Encounter: Unwashed Aldeiars
{540}{}{Desertoooooooooooooooooooo}
#
# Special Encounter: Ponte Guardian
{550}{}{Ponte}
#
# Special Encounter: Cafe of Broken Dreams
{560}{}{Cafe of Broken Dreams}
#
# Special Encounter: Holy Hand Grenade 1
{570}{}{Desertoooooooooooooooooooo}
#
# Special Encounter: Holy Hand Grenade 2
{580}{}{Cavernaaaaaaaa}
#
# Special Encounter: Guardião de Forever
{590}{}{Guardião de Forever}
#
# Special Encounter: Descarga de resíduos tóxicos
{600}{}{Descarga de resíduos tóxicos}
#
# Special Encounter: Pariahs
{610}{}{Desertoooooooooooooooooooo}
#
# Special Encounter: Mad Brahmin
{620}{}{Rebanho de brahmin}
#
# Caravan Encounters
{630}{}{Desertoooooooooooooooooooo}
{631}{}{Montanha}
#
# Fake Cofre 13 A
{640}{}{Cofre 13 Cavernaaaaaaaa}
#
# Fake Cofre 13 B
{650}{}{Cavernaaaaaaaa}
#
# Shadow Areas (Those which fit nowhere else
{660}{}{Litoral}
{661}{}{Litoral}
{662}{}{Desertoooooooooooooooooooo}
{663}{}{Desertoooooooooooooooooooo}
{664}{}{Desertoooooooooooooooooooo}
{665}{}{Montanha}
{666}{}{Montanha}
{667}{}{Desertoooooooooooooooooooo}
{668}{}{Desertoooooooooooooooooooo}
#
# New Reno Estábulos
{670}{}{Estábulos}


#
# Terrain type names for world map hover button
#
{1000}{}{Desertoooooooooooooooooooo}
{1001}{}{Montanhas}
{1002}{}{Cidade}
{1003}{}{Costa}
{1004}{}{Desconhecido}  # Desconhecido/visited city


# Misc messages
{1500}{}{Você ganhou 10.000 pontos de experiência!}
{1501}{}{Ruínas}
{1502}{}{O carro está fora do poder.}
{1503}{}{Este é um carro. Não parece que está funcionando.}



#
# Worldmap Encounter messages
#

{2998}{}{Você encontra:}
{2999}{}{Você deseja encontrar:}

# Encounter Table 0
{3000}{}{Um grupo de incursores.}
{3001}{}{Alguns radscorpions.}
{3002}{}{Ratos gigantes.}
{3003}{}{Uma festa mercante.}
{3004}{}{<Especial>}

# Encounter Table 1
{3050}{}{Um grupo de incursores.}
{3051}{}{Alguns manti.}
{3052}{}{Um grupo de geckos.}
{3053}{}{Um grupo de ratos mole.}
{3054}{}{Um grupo de radscorpions.}
{3055}{}{Um grupo de ratos gigantes.}
{3056}{}{Uma festa mercante.}
{3057}{}{<Especial>}

# Encounter Table 2
{3100}{}{Um grupo de incursores.}
{3101}{}{Um grupo de radscorpions.}
{3102}{}{Um grupo de ratos gigantes.}
{3103}{}{Uma festa mercante.}
{3104}{}{<Especial>}

# Encounter Table 3
{3150}{}{Um grupo de incursores.}

# Encounter Table 4
{3200}{}{Um grupo de incursores.}

# Encounter Table 5
{3250}{}{Um grupo de incursores.}

# Encounter Table 6
{3300}{}{Uma festa de guerra.}
{3301}{}{Um grupo de canibais.}
{3302}{}{Um grupo de plantas de esporos e alguns geckos de prata.}
{3303}{}{Um grupo de geckos de prata.}
{3304}{}{Alguns caçadores de recompensas.}
{3305}{}{Alguns caçadores de recompensas.}
{3306}{}{Alguns caçadores de recompensas.}
{3307}{}{Alguns caçadores de recompensas.}
{3308}{}{Alguns caçadores de recompensas.}
{3309}{}{Alguns caçadores de recompensas.}
{3310}{}{Alguns caçadores de recompensas.}
{3311}{}{Alguns caçadores de recompensas.}
{3312}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3313}{}{Um grupo de escorpiões.}
{3314}{}{Um grupo de plantas de esporos.}
{3315}{}{Um grupo de ratos de porco.}
{3316}{}{Um grupo de ratos.}
{3317}{}{Um caçador que luta contra os canibais.}
{3318}{}{Um grupo de formigas.}
{3319}{}{Uma festa de caça lutando contra escorpiões.}
{3320}{}{Um pequeno grupo de ratos de porco.}
{3321}{}{Um pequeno grupo de radscorpions.}
{3322}{}{Um pequeno grupo de formigas.}
{3323}{}{Uma festa de caça.}
{3324}{}{Um grupo de nômades.}
{3325}{}{Um homem que guarda uma ponte.}
{3326}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 7
{3350}{}{Descarga de resíduos tóxicos}
{3351}{}{Um cão sobrevivente solitário.}
{3352}{}{Um rebanho de brahmin.}
{3353}{}{Uma festa de guerra.}
{3354}{}{Alguns caçadores de recompensas.}
{3355}{}{Alguns caçadores de recompensas.}
{3356}{}{Alguns caçadores de recompensas.}
{3357}{}{Alguns caçadores de recompensas.}
{3358}{}{Alguns caçadores de recompensas.}
{3359}{}{Alguns caçadores de recompensas.}
{3360}{}{Alguns caçadores de recompensas.}
{3361}{}{Alguns caçadores de recompensas.}
{3362}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3363}{}{Um grupo de canibais.}
{3364}{}{Um grupo de plantas de esporos e alguns geckos de prata.}
{3365}{}{Um grupo de geckos de prata.}
{3366}{}{Um grupo de escorpiões.}
{3367}{}{Um grupo de plantas de esporos.}
{3368}{}{Um grupo de ratos de porco.}
{3369}{}{Um grupo de ratos.}
{3370}{}{Um caçador que luta contra os canibais.}
{3371}{}{Um grupo de formigas.}
{3372}{}{Uma festa de caça lutando contra escorpiões.}
{3373}{}{Um pequeno grupo de ratos de porco.}
{3374}{}{Um pequeno grupo de radscorpions.}
{3375}{}{Um pequeno grupo de formigas.}
{3376}{}{Uma festa de caça.}
{3377}{}{Um grupo de nômades.}
{3378}{}{Os restos de uma baleia.}
{3379}{}{Uma cabeça de pedra gigante.}
{3380}{}{Um ônibus acidentado.}
{3381}{}{Um Portal de Guardiões.}
{3382}{}{Cavaleiros do Rei Arthur.}
{3383}{}{Um homem de madeira de lata}
{3384}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 8
{3400}{}{Uma festa de guerra.}
{3401}{}{Um grupo de canibais.}
{3402}{}{Um grupo de plantas de esporos e alguns geckos de prata.}
{3403}{}{Um grupo de geckos de prata.}
{3404}{}{Alguns caçadores de recompensas.}
{3405}{}{Alguns caçadores de recompensas.}
{3406}{}{Alguns caçadores de recompensas.}
{3407}{}{Alguns caçadores de recompensas.}
{3408}{}{Alguns caçadores de recompensas.}
{3409}{}{Alguns caçadores de recompensas.}
{3410}{}{Alguns caçadores de recompensas.}
{3411}{}{Alguns caçadores de recompensas.}
{3412}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3413}{}{Um grupo de escorpiões.}
{3414}{}{Um grupo de plantas de esporos.}
{3415}{}{Um grupo de ratos de porco.}
{3416}{}{Um grupo de ratos.}
{3417}{}{Um caçador que luta contra os canibais.}
{3418}{}{Um grupo de formigas.}
{3419}{}{Uma festa de caça lutando contra escorpiões.}
{3420}{}{Um pequeno grupo de ratos de porco.}
{3421}{}{Um pequeno grupo de radscorpions.}
{3422}{}{Um pequeno grupo de formigas.}
{3423}{}{Uma festa de caça.}
{3424}{}{Um grupo de nômades.}

# Encounter Table 9
{3450}{}{Descarga de resíduos tóxicos}
{3451}{}{Um cão sobrevivente solitário.}
{3452}{}{Um rebanho de brahmin.}
{3453}{}{Uma banda de parias.}
{3454}{}{Alguns caçadores de recompensas.}
{3455}{}{Alguns caçadores de recompensas.}
{3456}{}{Alguns caçadores de recompensas.}
{3457}{}{Alguns caçadores de recompensas.}
{3358}{}{Alguns caçadores de recompensas.}
{3359}{}{Alguns caçadores de recompensas.}
{3360}{}{Alguns caçadores de recompensas.}
{3361}{}{Alguns caçadores de recompensas.}
{3362}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3463}{}{Um grupo de pessoas sagradas.}
{3464}{}{Alguns geckos e alguns molerats.}
{3465}{}{Alguns geckos.}
{3466}{}{Alguns radscorpions escondidos entre plantas de esporos.}
{3467}{}{Algumas plantas de esporos.}
{3468}{}{Uma família de radscorpions.}
{3469}{}{Um grupo de Molerats.}
{3470}{}{Um grupo de pessoas sagradas que se deslocam de uma festa de guerra.}
{3471}{}{Uma banda de nômades}
{3472}{}{Os restos de uma baleia.}
{3473}{}{Uma cabeça de pedra gigante.}
{3474}{}{Um ônibus acidentado.}
{3475}{}{Um Portal de Guardiões.}
{3476}{}{Cavaleiros do Rei Arthur.}
{3477}{}{Um homem de madeira de lata}
{3478}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 10
{3500}{}{Uma banda de parias.}
{3501}{}{Um grupo de pessoas sagradas.}
{3502}{}{Alguns caçadores de recompensas.}
{3503}{}{Alguns caçadores de recompensas.}
{3504}{}{Alguns caçadores de recompensas.}
{3505}{}{Alguns caçadores de recompensas.}
{3506}{}{Alguns caçadores de recompensas.}
{3507}{}{Alguns caçadores de recompensas.}
{3508}{}{Alguns caçadores de recompensas.}
{3509}{}{Alguns caçadores de recompensas.}
{3510}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3511}{}{Alguns geckos de prata escondidos entre as plantas de esporos.}
{3512}{}{Alguns geckos.}
{3513}{}{Alguns radscorpions escondidos entre plantas de esporos.}
{3514}{}{Algumas plantas de esporos.}
{3515}{}{Uma família de radscorpions.}
{3516}{}{Um grupo de Molerats.}
{3517}{}{Um grupo de pessoas sagradas que se deslocam de uma festa de guerra.}
{3518}{}{Uma banda de nômades}
{3519}{}{Um homem que guarda uma ponte.}
{3520}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 11
{3550}{}{Descarga de resíduos tóxicos}
{3551}{}{Um cão sobrevivente solitário.}
{3552}{}{Um rebanho de brahmin.}
{3553}{}{Um pacote de geckos dourados e uma família de radscorpions.}
{3554}{}{Alguns bandidos.}
{3555}{}{Um grupo de pessoas sem-teto.}
{3556}{}{Um pacote de geckos dourados.}
{3557}{}{Alguns caçadores de recompensas.}
{3558}{}{Alguns caçadores de recompensas.}
{3559}{}{Alguns caçadores de recompensas.}
{3560}{}{Alguns caçadores de recompensas.}
{3561}{}{Alguns caçadores de recompensas.}
{3562}{}{Alguns caçadores de recompensas.}
{3563}{}{Alguns caçadores de recompensas.}
{3564}{}{Alguns caçadores de recompensas.}
{3565}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3566}{}{Uma família de radscorpions.}
{3567}{}{Algumas plantas de esporos.}
{3568}{}{Alguns bandidos atacados por alguns geckos dourados.}
{3569}{}{Alguns agricultores defendem contra alguns geckos.}
{3570}{}{Alguns fazendeiros defendem alguns geckos dourados.}
{3571}{}{Alguns caçadores lutaram contra alguns gecos dourados.}
{3572}{}{Alguns caçadores defendem alguns bandidos.}
{3573}{}{Um grupo de caçadores subjugando alguns geckos.}
{3574}{}{Alguns bandidos emboscando pessoas sem-teto.}
{3575}{}{Alguns desabrigados matando alguns agricultores.}
{3576}{}{Alguns bandidos que atacam alguns agricultores.}
{3577}{}{Alguns agricultores defendem alguns escorpiões.}
{3578}{}{Alguns caçadores lutando contra alguns escorpiões.}
{3579}{}{Alguns caçadores atacam alguns ratos.}
{3580}{}{Alguns agricultores rooteiam uma infestação de ratos de porco.}
{3581}{}{Alguns agricultores.}
{3582}{}{Um grupo de caçadores.}
{3483}{}{Os restos de uma baleia.}
{3484}{}{Uma cabeça de pedra gigante.}
{3485}{}{Um ônibus acidentado.}
{3486}{}{Um Portal de Guardiões.}
{3487}{}{Cavaleiros do Rei Arthur.}
{3488}{}{Um homem de madeira de lata}
{3489}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 12
{3600}{}{Um pacote de geckos dourados e uma família de radscorpions.}
{3601}{}{Alguns bandidos.}
{3602}{}{Um grupo de pessoas sem-teto.}
{3603}{}{Um pacote de geckos dourados.}
{3604}{}{Alguns caçadores de recompensas.}
{3605}{}{Alguns caçadores de recompensas.}
{3606}{}{Alguns caçadores de recompensas.}
{3607}{}{Alguns caçadores de recompensas.}
{3608}{}{Alguns caçadores de recompensas.}
{3609}{}{Alguns caçadores de recompensas.}
{3610}{}{Alguns caçadores de recompensas.}
{3611}{}{Alguns caçadores de recompensas.}
{3612}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3613}{}{Uma família de radscorpions.}
{3614}{}{Algumas plantas de esporos.}
{3615}{}{Alguns bandidos atacados por alguns geckos dourados.}
{3616}{}{Alguns agricultores defendem contra alguns geckos.}
{3617}{}{Alguns fazendeiros defendem alguns geckos dourados.}
{3618}{}{Alguns caçadores lutaram contra alguns gecos dourados.}
{3619}{}{Alguns caçadores defendem alguns bandidos.}
{3620}{}{Um grupo de caçadores subjugando alguns geckos.}
{3621}{}{Alguns bandidos emboscando pessoas sem-teto.}
{3622}{}{Alguns desabrigados matando alguns agricultores.}
{3623}{}{Alguns bandidos que atacam alguns agricultores.}
{3624}{}{Alguns agricultores defendem alguns escorpiões.}
{3625}{}{Alguns caçadores lutando contra alguns escorpiões.}
{3626}{}{Alguns caçadores atacam alguns ratos.}
{3627}{}{Alguns agricultores rooteiam uma infestação de ratos de porco.}
{3628}{}{Alguns agricultores.}
{3629}{}{Um grupo de caçadores.}
{3630}{}{Um homem que guarda uma ponte.}
{3631}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 13
{3650}{}{Descarga de resíduos tóxicos}
{3651}{}{Um cão sobrevivente solitário.}
{3652}{}{Um rebanho de brahmin.}
{3653}{}{Um comerciante e alguns guardas.}
{3654}{}{Alguns caçadores de recompensas.}
{3655}{}{Alguns caçadores de recompensas.}
{3656}{}{Alguns caçadores de recompensas.}
{3657}{}{Alguns caçadores de recompensas.}
{3658}{}{Alguns caçadores de recompensas.}
{3659}{}{Alguns caçadores de recompensas.}
{3660}{}{Alguns caçadores de recompensas.}
{3661}{}{Alguns caçadores de recompensas.}
{3662}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3663}{}{Alguns caçadores.}
{3664}{}{Alguns bandidos atacando uma festa mercante.}
{3665}{}{Alguns bandidos emboscando alguns caçadores.}
{3666}{}{Uma família de radicorpores atacando uma festa mercante.}
{3667}{}{Alguns caçadores tentando pegar radscorpions.}
{3668}{}{Um grupo de radscorpions.}
{3669}{}{Uma família de molerats.}
{3670}{}{Alguns bandidos.}
{3671}{}{Uma banda de caçadores tentando pegar alguns geckos dourados.}
{3672}{}{Alguns escorpiões lutando contra alguns geckos dourados.}
{3673}{}{Alguns escorpiões atacando alguns molerados e ratos de porco.}
{3674}{}{Alguns caçadores e uma festa mercante contra os bandidos.}
{3675}{}{Alguns geckos dourados.}
{3676}{}{Alguns caçadores lutando contra molerats e ratos de porco.}
{3677}{}{Uma festa mercante defendendo alguns molerats e ratos de porco.}
{3678}{}{Os restos de uma baleia.}
{3679}{}{Uma cabeça de pedra gigante.}
{3680}{}{Um ônibus acidentado.}
{3681}{}{Um Portal de Guardiões.}
{3682}{}{Cavaleiros do Rei Arthur.}
{3683}{}{Um homem de madeira de lata}
{3684}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 14
{3700}{}{Descarga de resíduos tóxicos}
{3701}{}{Um cão sobrevivente solitário.}
{3702}{}{Um rebanho de brahmin.}
{3703}{}{Uma banda de bandolimistas.}
{3704}{}{Alguns caçadores de recompensas.}
{3705}{}{Alguns caçadores de recompensas.}
{3706}{}{Alguns caçadores de recompensas.}
{3707}{}{Alguns caçadores de recompensas.}
{3708}{}{Alguns caçadores de recompensas.}
{3709}{}{Alguns caçadores de recompensas.}
{3710}{}{Alguns caçadores de recompensas.}
{3711}{}{Alguns caçadores de recompensas.}
{3712}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3713}{}{Uma banda de ladrões.}
{3714}{}{Uma banda de ladrões e bandolimistas.}
{3715}{}{Alguns geckos dourados e alguns radscorpions.}
{3716}{}{Uma família de geckos dourados.}
{3717}{}{Uma família de molerats.}
{3718}{}{Um grande grupo de radscorpions.}
{3719}{}{Uma grande infestação de plantas de esporos.}
{3720}{}{Uma banda de ladrões contestando um grupo de bandolimistas.}
{3721}{}{Uma festa mercante defendendo alguns bandolimistas.}
{3722}{}{Um partido mercante que afasta alguns ladrões.}
{3723}{}{Um partido mercante defendendo alguns radscorpions.}
{3724}{}{Um grupo de geckos dourados lutando contra alguns radscorpions.}
{3725}{}{Um comerciante com alguns guardas.}
{3726}{}{Os restos de uma baleia.}
{3727}{}{Uma cabeça de pedra gigante.}
{3728}{}{Um ônibus acidentado.}
{3729}{}{Um Portal de Guardiões.}
{3730}{}{Cavaleiros do Rei Arthur.}
{3731}{}{Um homem de madeira de lata}
{3732}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 15
{3750}{}{Uma banda de bandolimistas.}
{3751}{}{Uma banda de ladrões.}
{3752}{}{Uma banda de ladrões e bandolimistas.}
{3753}{}{Alguns geckos dourados e alguns radscorpions.}
{3754}{}{Alguns caçadores de recompensas.}
{3755}{}{Alguns caçadores de recompensas.}
{3756}{}{Alguns caçadores de recompensas.}
{3757}{}{Alguns caçadores de recompensas.}
{3758}{}{Alguns caçadores de recompensas.}
{3759}{}{Alguns caçadores de recompensas.}
{3760}{}{Alguns caçadores de recompensas.}
{3761}{}{Alguns caçadores de recompensas.}
{3762}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3763}{}{Uma família de geckos dourados.}
{3764}{}{Uma família de molerats.}
{3765}{}{Um grande grupo de radscorpions.}
{3766}{}{Uma grande infestação de plantas de esporos.}
{3767}{}{Uma banda de ladrões contestando um grupo de bandolimistas.}
{3768}{}{Uma festa mercante defendendo alguns bandolimistas.}
{3769}{}{Um partido mercante que afasta alguns ladrões.}
{3770}{}{Um partido mercante defendendo alguns radscorpions.}
{3771}{}{Um grupo de geckos dourados lutando contra alguns radscorpions.}
{3772}{}{Um comerciante com alguns guardas.}
{3773}{}{Um homem que guarda uma ponte.}
{3774}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 16
{3800}{}{Descarga de resíduos tóxicos}
{3801}{}{Um cão sobrevivente solitário.}
{3802}{}{Um rebanho de brahmin.}
{3803}{}{Um grupo de escravos e escravos.}
{3804}{}{Alguns caçadores de recompensas.}
{3805}{}{Alguns caçadores de recompensas.}
{3806}{}{Alguns caçadores de recompensas.}
{3807}{}{Alguns caçadores de recompensas.}
{3808}{}{Alguns caçadores de recompensas.}
{3809}{}{Alguns caçadores de recompensas.}
{3810}{}{Alguns caçadores de recompensas.}
{3811}{}{Alguns caçadores de recompensas.}
{3812}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3813}{}{Um grupo de bandolimistas.}
{3814}{}{Uma banda de ladrões.}
{3815}{}{Alguns geckos dourados escondidos entre um grande número de plantas de esporos.}
{3816}{}{Um pacote de radscorpions e alguns molerats.}
{3817}{}{Um pacote de radscorpions.}
{3818}{}{Um grupo de molerats.}
{3819}{}{Uma banda de assaltantes emboscando um grupo de bandolimistas.}
{3820}{}{Um grupo de escravas tentando escravizar algumas pessoas.}
{3821}{}{Um grupo de escravos e escravos afastando alguns ladrões.}
{3822}{}{Alguns escravos e escravos defendem alguns geckos dourados.}
{3823}{}{Alguns radscorpions invadiram um partido Rave.}
{3824}{}{Uma festa de desgraça.}
{3825}{}{Os restos de uma baleia.}
{3826}{}{Uma cabeça de pedra gigante.}
{3827}{}{Um ônibus acidentado.}
{3828}{}{Um Portal de Guardiões.}
{3829}{}{Cavaleiros do Rei Arthur.}
{3830}{}{Um homem de madeira de lata}
{3831}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 17
{3850}{}{Um grupo de escravos e escravos.}
{3851}{}{Um grupo de bandolimistas.}
{3852}{}{Uma banda de ladrões.}
{3853}{}{Alguns geckos dourados escondidos entre um grande número de plantas de esporos.}
{3854}{}{Alguns caçadores de recompensas.}
{3855}{}{Alguns caçadores de recompensas.}
{3856}{}{Alguns caçadores de recompensas.}
{3857}{}{Alguns caçadores de recompensas.}
{3858}{}{Alguns caçadores de recompensas.}
{3859}{}{Alguns caçadores de recompensas.}
{3860}{}{Alguns caçadores de recompensas.}
{3861}{}{Alguns caçadores de recompensas.}
{3862}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3863}{}{Um pacote de radscorpions e alguns molerats.}
{3864}{}{Um pacote de radscorpions.}
{3865}{}{Um grupo de molerats.}
{3866}{}{Uma banda de assaltantes emboscando um grupo de bandolimistas.}
{3867}{}{Um grupo de escravas tentando escravizar algumas pessoas.}
{3868}{}{Um grupo de escravos e escravos afastando alguns ladrões.}
{3869}{}{Alguns escravos e escravos defendem alguns geckos dourados.}
{3870}{}{Um homem que guarda uma ponte.}
{3871}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 18
{3900}{}{Alguns salteadores e ladrões.}
{3901}{}{Alguns salteadores de estradas.}
{3902}{}{Um grande pacote de geckos dourados.}
{3903}{}{Alguns escorpiões escondidos nas plantas de esporos.}
{3904}{}{Alguns caçadores de recompensas.}
{3905}{}{Alguns caçadores de recompensas.}
{3906}{}{Alguns caçadores de recompensas.}
{3907}{}{Alguns caçadores de recompensas.}
{3908}{}{Alguns caçadores de recompensas.}
{3909}{}{Alguns caçadores de recompensas.}
{3910}{}{Alguns caçadores de recompensas.}
{3911}{}{Alguns caçadores de recompensas.}
{3912}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3913}{}{Alguns ladrões lutando contra alguns escorpiões.}
{3914}{}{Alguns ladrões.}
{3915}{}{Um grupo mercante atacado por bandolimistas.}
{3916}{}{Um grupo mercante emboscado por ladrões.}
{3917}{}{Alguns bandolim atacados por algumas plantas de esporos.}
{3918}{}{Uma festa mercante.}
{3919}{}{Um homem que guarda uma ponte.}
{3920}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 19
{3950}{}{Alguns salteadores de estradas.}
{3951}{}{Alguns ladrões.}
{3952}{}{Alguns sem-teto.}
{3953}{}{Alguns geckos dourados e mantis.}
{3954}{}{Alguns caçadores de recompensas.}
{3955}{}{Alguns caçadores de recompensas.}
{3956}{}{Alguns caçadores de recompensas.}
{3957}{}{Alguns caçadores de recompensas.}
{3958}{}{Alguns caçadores de recompensas.}
{3959}{}{Alguns caçadores de recompensas.}
{3960}{}{Alguns caçadores de recompensas.}
{3961}{}{Alguns caçadores de recompensas.}
{3962}{}{Uma banda de rufiões liderada por um irmão Morton.}
{3963}{}{Algum brahmin selvagem.}
{3964}{}{Alguns escorpiões.}
{3965}{}{Alguns moonshiners atacados por alguns bandolimistas.}
{3966}{}{Alguns bandolimistas atacam pessoas sem-teto.}
{3967}{}{Alguns moonshiners e fazendeiros.}
{3968}{}{Algumas mantis que atacam alguns agricultores.}
{3969}{}{Alguns moonshiners lutando contra alguns agricultores.}
{3970}{}{Alguns brahmin que defendem algumas mantis.}
{3971}{}{Algumas mantis que atacam alguns molerados.}
{3972}{}{Alguns moonshiners.}
{3973}{}{Alguns agricultores.}
{3974}{}{Um rebanho de brahmin.}
{3975}{}{Um homem que guarda uma ponte.}
{3976}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 20
{4000}{}{Alguns ruteiros rastreando com cachorros selvagens.}
{4001}{}{Alguns ladrões que procuram com cachorros selvagens.}
{4002}{}{Uma banda de ladrões.}
{4003}{}{Uma banda de bandolimistas.}
{4004}{}{Alguns caçadores de recompensas.}
{4005}{}{Alguns caçadores de recompensas.}
{4006}{}{Alguns caçadores de recompensas.}
{4007}{}{Alguns caçadores de recompensas.}
{4008}{}{Alguns caçadores de recompensas.}
{4009}{}{Alguns caçadores de recompensas.}
{4010}{}{Alguns caçadores de recompensas.}
{4011}{}{Alguns caçadores de recompensas.}
{4012}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4013}{}{Um enxame de mantis que infesta algumas plantas de esporos.}
{4014}{}{Um pacote de cachorros selvagens entre algumas plantas de esporos.}
{4015}{}{Um enxame de mantis.}
{4016}{}{Um pacote de cachorros selvagens.}
{4017}{}{Alguns ladrões defendem alguns cachorros selvagens.}
{4018}{}{Uma caravana atacada por cães selvagens.}
{4019}{}{Uma caravana emboscada por ladrões.}
{4020}{}{Uma caravana emboscada por bandolimistas.}
{4021}{}{Uma caravana.}
{4022}{}{Um homem que guarda uma ponte.}
{4023}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 21
{4050}{}{Descarga de resíduos tóxicos}
{4051}{}{Um cão sobrevivente solitário.}
{4052}{}{Um rebanho de brahmin.}
{4053}{}{Alguns ruteiros rastreando com cachorros selvagens.}
{4054}{}{Alguns caçadores de recompensas.}
{4055}{}{Alguns caçadores de recompensas.}
{4056}{}{Alguns caçadores de recompensas.}
{4057}{}{Alguns caçadores de recompensas.}
{4058}{}{Alguns caçadores de recompensas.}
{4059}{}{Alguns caçadores de recompensas.}
{4060}{}{Alguns caçadores de recompensas.}
{4061}{}{Alguns caçadores de recompensas.}
{4062}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4063}{}{Alguns ladrões que procuram com cachorros selvagens.}
{4064}{}{Uma banda de ladrões.}
{4065}{}{Uma banda de bandolimistas.}
{4066}{}{Um enxame de mantis que infesta algumas plantas de esporos.}
{4067}{}{Um pacote de cachorros selvagens entre algumas plantas de esporos.}
{4068}{}{Um enxame de mantis.}
{4069}{}{Um pacote de cachorros selvagens.}
{4070}{}{Alguns ladrões defendem alguns cachorros selvagens.}
{4071}{}{Uma caravana atacada por cães selvagens.}
{4072}{}{Uma caravana emboscada por ladrões.}
{4073}{}{Uma caravana emboscada por bandolimistas.}
{4074}{}{Uma caravana.}
{4075}{}{Os restos de uma baleia.}
{4076}{}{Uma cabeça de pedra gigante.}
{4077}{}{Um ônibus acidentado.}
{4078}{}{Um Portal de Guardiões.}
{4079}{}{Cavaleiros do Rei Arthur.}
{4080}{}{Um homem de madeira de lata}
{4081}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 22
{4100}{}{Alguns geckos dourados.}
{4101}{}{Um enxame de mantis.}
{4102}{}{Alguns radscorpions.}
{4103}{}{Algum brahmin selvagem.}
{4104}{}{Alguns caçadores de recompensas.}
{4105}{}{Alguns caçadores de recompensas.}
{4106}{}{Alguns caçadores de recompensas.}
{4107}{}{Alguns caçadores de recompensas.}
{4108}{}{Alguns caçadores de recompensas.}
{4109}{}{Alguns caçadores de recompensas.}
{4110}{}{Alguns caçadores de recompensas.}
{4111}{}{Alguns caçadores de recompensas.}
{4112}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4113}{}{Um comerciante e guardas lutando contra geckos dourados.}
{4114}{}{Um enxame de mantis massacrando uma banda de comércio.}
{4115}{}{Um enxame de mantis lutando contra brahmins selvagens.}
{4116}{}{Alguns radscorpions se banqueteavam com mantis.}
{4117}{}{Alguns radscorpions matando algum brahmin selvagem.}
{4118}{}{Um comerciante e guardas.}
{4119}{}{Um homem que guarda uma ponte.}
{4120}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 23
{4150}{}{Descarga de resíduos tóxicos}
{4151}{}{Um cão sobrevivente solitário.}
{4152}{}{Um rebanho de brahmin.}
{4153}{}{Alguns geckos dourados.}
{4154}{}{Alguns caçadores de recompensas.}
{4155}{}{Alguns caçadores de recompensas.}
{4156}{}{Alguns caçadores de recompensas.}
{4157}{}{Alguns caçadores de recompensas.}
{4158}{}{Alguns caçadores de recompensas.}
{4159}{}{Alguns caçadores de recompensas.}
{4160}{}{Alguns caçadores de recompensas.}
{4161}{}{Alguns caçadores de recompensas.}
{4162}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4163}{}{Um enxame de mantis.}
{4164}{}{Alguns radscorpions.}
{4165}{}{Algum brahmin selvagem.}
{4166}{}{Um comerciante e guardas lutando contra geckos dourados.}
{4167}{}{Um enxame de mantis massacrando uma banda de comércio.}
{4168}{}{Um enxame de mantis lutando contra brahmins selvagens.}
{4169}{}{Alguns radscorpions se banqueteavam com mantis.}
{4170}{}{Alguns radscorpions matando algum brahmin selvagem.}
{4171}{}{Um comerciante e guardas.}
{4172}{}{Os restos de uma baleia.}
{4173}{}{Uma cabeça de pedra gigante.}
{4174}{}{Um ônibus acidentado.}
{4175}{}{Um Portal de Guardiões.}
{4176}{}{Cavaleiros do Rei Arthur.}
{4177}{}{Um homem de madeira de lata}
{4178}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 24
{4200}{}{Descarga de resíduos tóxicos}
{4201}{}{Um cão sobrevivente solitário.}
{4202}{}{Um rebanho de brahmin.}
{4203}{}{Alguns molerados mutados.}
{4204}{}{Alguns caçadores de recompensas.}
{4205}{}{Alguns caçadores de recompensas.}
{4206}{}{Alguns caçadores de recompensas.}
{4207}{}{Alguns caçadores de recompensas.}
{4208}{}{Alguns caçadores de recompensas.}
{4209}{}{Alguns caçadores de recompensas.}
{4210}{}{Alguns caçadores de recompensas.}
{4211}{}{Alguns caçadores de recompensas.}
{4212}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4213}{}{Alguns ratos de porco mutados.}
{4214}{}{Algumas plantas de esporos.}
{4215}{}{Um eremita e alguns cães lutando contra molerados mutados.}
{4216}{}{Um eremita que tira alguns cachorros selvagens.}
{4217}{}{Um eremita que afasta alguns ratos de porco mutados.}
{4218}{}{Um eremita com alguns cães lutando contra molerados mutados.}
{4219}{}{Alguns molerados mutados lutando contra ratos de porco mutados.}
{4220}{}{Alguns molerados mutados lutando contra algumas plantas de esporos.}
{4221}{}{Alguns ratos de porco mutados lutaram contra cães selvagens.}
{4222}{}{Um eremita.}
{4223}{}{Os restos de uma baleia.}
{4224}{}{Uma cabeça de pedra gigante.}
{4225}{}{Um ônibus acidentado.}
{4226}{}{Um Portal de Guardiões.}
{4227}{}{Cavaleiros do Rei Arthur.}
{4228}{}{Um homem de madeira de lata}
{4229}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 25
{4250}{}{Alguns molerados mutados.}
{4251}{}{Alguns ratos de porco mutados.}
{4252}{}{Algumas plantas de esporos.}
{4253}{}{Um eremita e alguns cães lutando contra molerados mutados.}
{4254}{}{Alguns caçadores de recompensas.}
{4255}{}{Alguns caçadores de recompensas.}
{4256}{}{Alguns caçadores de recompensas.}
{4257}{}{Alguns caçadores de recompensas.}
{4258}{}{Alguns caçadores de recompensas.}
{4259}{}{Alguns caçadores de recompensas.}
{4260}{}{Alguns caçadores de recompensas.}
{4261}{}{Alguns caçadores de recompensas.}
{4262}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4263}{}{Um eremita que tira alguns cachorros selvagens.}
{4264}{}{Um eremita que afasta alguns ratos de porco mutados.}
{4265}{}{Um eremita com alguns cães lutando contra molerados mutados.}
{4266}{}{Alguns molerados mutados lutando contra ratos de porco mutados.}
{4267}{}{Alguns molerados mutados lutando contra algumas plantas de esporos.}
{4268}{}{Alguns ratos de porco mutados lutaram contra cães selvagens.}
{4269}{}{Um eremita.}
{4270}{}{Um homem que guarda uma ponte.}
{4271}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 26
{4300}{}{Uma banda de escravas e alguns cães.}
{4301}{}{Uma banda de escravas.}
{4302}{}{Alguns geckos dourados.}
{4303}{}{Um pacote de cachorros selvagens.}
{4304}{}{Alguns caçadores de recompensas.}
{4305}{}{Alguns caçadores de recompensas.}
{4306}{}{Alguns caçadores de recompensas.}
{4307}{}{Alguns caçadores de recompensas.}
{4308}{}{Alguns caçadores de recompensas.}
{4309}{}{Alguns caçadores de recompensas.}
{4310}{}{Alguns caçadores de recompensas.}
{4311}{}{Alguns caçadores de recompensas.}
{4312}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4313}{}{Uma unidade de patrulha e cães subjugando escravos}
{4314}{}{Uma banda de escravos que afastava alguns geckos dourados.}
{4315}{}{Uma unidade de patrulha lutando contra escravos.}
{4316}{}{Uma unidade de patrulha lutando contra alguns gecos dourados.}
{4317}{}{Uma unidade de patrulha defendendo cachorros selvagens.}
{4318}{}{Uma unidade de patrulha.}
{4319}{}{Um homem que guarda uma ponte.}
{4320}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 27
{4350}{}{Descarga de resíduos tóxicos}
{4351}{}{Um cão sobrevivente solitário.}
{4352}{}{Um rebanho de brahmin.}
{4353}{}{Uma banda de escravas e alguns cães.}
{4354}{}{Alguns caçadores de recompensas.}
{4355}{}{Alguns caçadores de recompensas.}
{4356}{}{Alguns caçadores de recompensas.}
{4357}{}{Alguns caçadores de recompensas.}
{4358}{}{Alguns caçadores de recompensas.}
{4359}{}{Alguns caçadores de recompensas.}
{4360}{}{Alguns caçadores de recompensas.}
{4361}{}{Alguns caçadores de recompensas.}
{4362}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4363}{}{Uma banda de escravas.}
{4364}{}{Alguns geckos dourados.}
{4365}{}{Um pacote de cachorros selvagens.}
{4366}{}{Uma unidade de patrulha e cães subjugando escravos}
{4367}{}{Uma banda de escravos que afastava alguns geckos dourados.}
{4368}{}{Uma unidade de patrulha lutando contra escravos.}
{4369}{}{Uma unidade de patrulha lutando contra alguns gecos dourados.}
{4370}{}{Uma unidade de patrulha defendendo cachorros selvagens.}
{4371}{}{Uma unidade de patrulha.}
{4372}{}{Os restos de uma baleia.}
{4373}{}{Uma cabeça de pedra gigante.}
{4374}{}{Um ônibus acidentado.}
{4375}{}{Um Portal de Guardiões.}
{4376}{}{Cavaleiros do Rei Arthur.}
{4377}{}{Um homem de madeira de lata}
{4378}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 28
{4400}{}{Uma série de catadores.}
{4401}{}{Alguns catadores de ghoul.}
{4402}{}{Um monte de loucos.}
{4403}{}{Alguns ghoul crazies.}
{4404}{}{Alguns caçadores de recompensas.}
{4405}{}{Alguns caçadores de recompensas.}
{4406}{}{Alguns caçadores de recompensas.}
{4407}{}{Alguns caçadores de recompensas.}
{4408}{}{Alguns caçadores de recompensas.}
{4409}{}{Alguns caçadores de recompensas.}
{4410}{}{Alguns caçadores de recompensas.}
{4411}{}{Alguns caçadores de recompensas.}
{4412}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4413}{}{Alguns geckos.}
{4414}{}{Um pacote de cachorros selvagens.}
{4415}{}{Uma família de radscorpions.}
{4416}{}{Um monte de ratos de porco mutados.}
{4417}{}{Um pacote de ratos mutados.}
{4418}{}{Alguns catadores lutaram contra um monte de loucos.}
{4419}{}{Alguns destruidores de ghoul defendem algumas loucuras}
{4420}{}{Alguns geckos lutando contra alguns loucos.}
{4421}{}{Alguns ratos mutantes infestaram alguns bombeadores de ghoul.}
{4422}{}{Um homem que guarda uma ponte.}
{4423}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 29
{4450}{}{Descarga de resíduos tóxicos}
{4451}{}{Um cão sobrevivente solitário.}
{4452}{}{Um rebanho de brahmin.}
{4453}{}{Uma série de catadores.}
{4454}{}{Alguns caçadores de recompensas.}
{4455}{}{Alguns caçadores de recompensas.}
{4456}{}{Alguns caçadores de recompensas.}
{4457}{}{Alguns caçadores de recompensas.}
{4458}{}{Alguns caçadores de recompensas.}
{4459}{}{Alguns caçadores de recompensas.}
{4460}{}{Alguns caçadores de recompensas.}
{4461}{}{Alguns caçadores de recompensas.}
{4462}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4463}{}{Alguns catadores de ghoul.}
{4464}{}{Um monte de loucos.}
{4465}{}{Alguns ghoul crazies.}
{4466}{}{Alguns geckos.}
{4467}{}{Um pacote de cachorros selvagens.}
{4468}{}{Uma família de radscorpions.}
{4469}{}{Um monte de ratos de porco mutados.}
{4470}{}{Um pacote de ratos mutados.}
{4471}{}{Alguns catadores lutaram contra um monte de loucos.}
{4472}{}{Alguns destruidores de ghoul defendem algumas loucuras}
{4473}{}{Alguns geckos lutando contra alguns loucos.}
{4474}{}{Alguns ratos mutantes infestaram alguns bombeadores de ghoul.}
{4475}{}{Os restos de uma baleia.}
{4476}{}{Uma cabeça de pedra gigante.}
{4477}{}{Um ônibus acidentado.}
{4478}{}{Um Portal de Guardiões.}
{4479}{}{Cavaleiros do Rei Arthur.}
{4480}{}{Um homem de madeira de lata}
{4481}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 30
{4500}{}{Alguns canibais.}
{4501}{}{Alguns fanáticos.}
{4502}{}{Uma festa de guerra.}
{4503}{}{alguns parados.}
{4504}{}{Alguns caçadores de recompensas.}
{4505}{}{Alguns caçadores de recompensas.}
{4506}{}{Alguns caçadores de recompensas.}
{4507}{}{Alguns caçadores de recompensas.}
{4508}{}{Alguns caçadores de recompensas.}
{4509}{}{Alguns caçadores de recompensas.}
{4510}{}{Alguns caçadores de recompensas.}
{4511}{}{Alguns caçadores de recompensas.}
{4512}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4513}{}{Uma família de radscorpions.}
{4514}{}{Alguns molerats.}
{4515}{}{Alguns pescadores defendem alguns canibais.}
{4516}{}{Alguns canibais lutando contra alguns fanfarrões.}
{4517}{}{Alguns radscorpions atacam alguns fanfarrões.}
{4518}{}{Alguns pescadores.}

# Encounter Table 31
{4550}{}{Descarga de resíduos tóxicos}
{4551}{}{Um cão sobrevivente solitário.}
{4552}{}{Um rebanho de brahmin.}
{4553}{}{Alguns canibais.}
{4554}{}{Alguns caçadores de recompensas.}
{4555}{}{Alguns caçadores de recompensas.}
{4556}{}{Alguns caçadores de recompensas.}
{4557}{}{Alguns caçadores de recompensas.}
{4558}{}{Alguns caçadores de recompensas.}
{4559}{}{Alguns caçadores de recompensas.}
{4560}{}{Alguns caçadores de recompensas.}
{4561}{}{Alguns caçadores de recompensas.}
{4562}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4563}{}{Alguns marginalizados.}
{4564}{}{Alguns fanáticos.}
{4565}{}{Uma festa de guerra.}
{4566}{}{Alguns geckos escondidos em algumas plantas de esporos.}
{4567}{}{Alguns geckos e alguns radscorpions.}
{4568}{}{Alguns geckos.}
{4569}{}{Alguns radscorpions escondidos em algumas plantas de esporos.}
{4570}{}{Alguns escorpiões.}
{4571}{}{Some geckos attacking alguns parados.}
{4572}{}{Alguns geckos lutando contra outros.}
{4573}{}{Alguns radscorpions lutando contra alguns canibais.}
{4574}{}{Alguns radscorpions atacando um eremita.}
{4575}{}{Um eremita.}
{4576}{}{Os restos de uma baleia.}
{4577}{}{Uma cabeça de pedra gigante.}
{4578}{}{Um ônibus acidentado.}
{4579}{}{Um Portal de Guardiões.}
{4580}{}{Cavaleiros do Rei Arthur.}
{4581}{}{Um homem de madeira de lata}
{4582}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 32
{4600}{}{Alguns canibais.}
{4601}{}{Alguns marginalizados.}
{4602}{}{Alguns fanáticos.}
{4603}{}{Uma festa de guerra.}
{4604}{}{Alguns caçadores de recompensas.}
{4605}{}{Alguns caçadores de recompensas.}
{4606}{}{Alguns caçadores de recompensas.}
{4607}{}{Alguns caçadores de recompensas.}
{4608}{}{Alguns caçadores de recompensas.}
{4609}{}{Alguns caçadores de recompensas.}
{4610}{}{Alguns caçadores de recompensas.}
{4611}{}{Alguns caçadores de recompensas.}
{4612}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4613}{}{Alguns geckos escondidos em algumas plantas de esporos.}
{4614}{}{Alguns geckos e alguns radscorpions.}
{4615}{}{Alguns geckos.}
{4616}{}{Alguns radscorpions escondidos em algumas plantas de esporos.}
{4617}{}{Alguns escorpiões.}
{4618}{}{Some geckos attacking alguns parados.}
{4619}{}{Alguns geckos lutando contra outros.}
{4620}{}{Alguns radscorpions lutando contra alguns canibais.}
{4621}{}{Alguns radscorpions atacando um eremita.}
{4622}{}{Um eremita.}
{4623}{}{Um homem que guarda uma ponte.}
{4624}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 33
{4650}{}{Descarga de resíduos tóxicos}
{4651}{}{Um cão sobrevivente solitário.}
{4652}{}{Um rebanho de brahmin.}
{4653}{}{Uma caravana Den.}
{4654}{}{Alguns caçadores de recompensas.}
{4655}{}{Alguns caçadores de recompensas.}
{4656}{}{Alguns caçadores de recompensas.}
{4657}{}{Alguns caçadores de recompensas.}
{4658}{}{Alguns caçadores de recompensas.}
{4659}{}{Alguns caçadores de recompensas.}
{4660}{}{Alguns caçadores de recompensas.}
{4661}{}{Alguns caçadores de recompensas.}
{4662}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4663}{}{Alguns salteadores e ladrões.}
{4664}{}{Alguns salteadores de estradas.}
{4665}{}{Alguns ladrões.}
{4666}{}{Uma caravana Redding que se afasta de bandolimistas.}
{4667}{}{Uma nova caravana Reno evitando ladrões.}
{4668}{}{Uma caravana de den que afasta os bandolimistas.}
{4669}{}{Alguns ladrões emboscam uma caravana.}
{4670}{}{A Den caravan attacking a Cofre Cidade caravan.}
{4671}{}{Alguns bandidos de estradas lutaram contra assaltantes.}
{4672}{}{A Cofre Cidade caravan.}
{4673}{}{Uma caravana Den.}
{4674}{}{Os restos de uma baleia.}
{4675}{}{Uma cabeça de pedra gigante.}
{4676}{}{Um ônibus acidentado.}
{4677}{}{Um Portal de Guardiões.}
{4678}{}{Cavaleiros do Rei Arthur.}
{4679}{}{Um homem de madeira de lata}
{4680}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 34
{4700}{}{Uma caravana Den.}
{4701}{}{Alguns salteadores e ladrões.}
{4702}{}{Alguns salteadores de estradas.}
{4703}{}{Alguns ladrões.}
{4704}{}{Alguns caçadores de recompensas.}
{4705}{}{Alguns caçadores de recompensas.}
{4706}{}{Alguns caçadores de recompensas.}
{4707}{}{Alguns caçadores de recompensas.}
{4708}{}{Alguns caçadores de recompensas.}
{4709}{}{Alguns caçadores de recompensas.}
{4710}{}{Alguns caçadores de recompensas.}
{4711}{}{Alguns caçadores de recompensas.}
{4712}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4713}{}{Uma caravana Redding que se afasta de bandolimistas.}
{4714}{}{Uma nova caravana Reno evitando ladrões.}
{4715}{}{Uma caravana de den que afasta os bandolimistas.}
{4716}{}{Alguns ladrões emboscam uma caravana.}
{4717}{}{A Den caravan attacking a Cofre Cidade caravan.}
{4718}{}{Alguns bandidos de estradas lutaram contra assaltantes.}
{4719}{}{A Cofre Cidade caravan.}
{4720}{}{Uma caravana Den.}
{4721}{}{Um homem que guarda uma ponte.}
{4722}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 35
{4750}{}{Descarga de resíduos tóxicos}
{4751}{}{Um cão sobrevivente solitário.}
{4752}{}{Um rebanho de brahmin.}
{4753}{}{Alguns geckos e alguns lobos.}
{4754}{}{Alguns caçadores de recompensas.}
{4755}{}{Alguns caçadores de recompensas.}
{4756}{}{Alguns caçadores de recompensas.}
{4757}{}{Alguns caçadores de recompensas.}
{4758}{}{Alguns caçadores de recompensas.}
{4759}{}{Alguns caçadores de recompensas.}
{4760}{}{Alguns caçadores de recompensas.}
{4761}{}{Alguns caçadores de recompensas.}
{4762}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4763}{}{Alguns afirmam jumpers.}
{4764}{}{Alguns lobos.}
{4765}{}{Alguns geckos.}
{4766}{}{Alguns garimpeiros que lutam contra alguns reivindicam jumpers.}
{4767}{}{Alguns caçadores lutando contra alguns geckos.}
{4768}{}{Alguns guerreiros lutando contra lobos.}
{4769}{}{Alguns homesteaders lutando contra alguns pretendentes.}
{4770}{}{Alguns homesteaders defendem alguns lobos.}
{4771}{}{Alguns contrabandistas.}
{4772}{}{Alguns caçadores.}
{4773}{}{Alguns garimpeiros.}
{4774}{}{Os restos de uma baleia.}
{4775}{}{Uma cabeça de pedra gigante.}
{4776}{}{Um ônibus acidentado.}
{4777}{}{Um Portal de Guardiões.}
{4778}{}{Cavaleiros do Rei Arthur.}
{4779}{}{Um homem de madeira de lata}
{4780}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 36
{4800}{}{Alguns geckos e alguns lobos.}
{4801}{}{Alguns afirmam jumpers.}
{4802}{}{Alguns lobos.}
{4803}{}{Alguns geckos.}
{4804}{}{Alguns caçadores de recompensas.}
{4805}{}{Alguns caçadores de recompensas.}
{4806}{}{Alguns caçadores de recompensas.}
{4807}{}{Alguns caçadores de recompensas.}
{4808}{}{Alguns caçadores de recompensas.}
{4809}{}{Alguns caçadores de recompensas.}
{4810}{}{Alguns caçadores de recompensas.}
{4811}{}{Alguns caçadores de recompensas.}
{4812}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4813}{}{Alguns garimpeiros que lutam contra alguns reivindicam jumpers.}
{4814}{}{Alguns caçadores lutando contra alguns geckos.}
{4815}{}{Alguns guerreiros lutando contra lobos.}
{4816}{}{Alguns homesteaders lutando contra alguns pretendentes.}
{4817}{}{Alguns homesteaders defendem alguns lobos.}
{4818}{}{Alguns contrabandistas.}
{4819}{}{Alguns caçadores.}
{4820}{}{Alguns garimpeiros.}
{4821}{}{Um homem que guarda uma ponte.}
{4822}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 37
{4850}{}{Um grupo de lobos e alguns molerados.}
{4851}{}{Alguns radscorpions e alguns lobos.}
{4852}{}{Alguns molerados mutados e alguns radscorpions}
{4853}{}{Um pacote de geckos.}
{4854}{}{Alguns caçadores de recompensas.}
{4855}{}{Alguns caçadores de recompensas.}
{4856}{}{Alguns caçadores de recompensas.}
{4857}{}{Alguns caçadores de recompensas.}
{4858}{}{Alguns caçadores de recompensas.}
{4859}{}{Alguns caçadores de recompensas.}
{4860}{}{Alguns caçadores de recompensas.}
{4861}{}{Alguns caçadores de recompensas.}
{4862}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4863}{}{Um bando de lobos.}
{4864}{}{Um pacote de molerados mutados.}
{4865}{}{Um pacote de radscorpions}
{4866}{}{Um maço de lobos e alguns geckos.}
{4867}{}{Alguns molerados mutantes lutaram contra alguns geckos.}
{4868}{}{Alguns molerats lutaram contra alguns radscorpions.}
{4869}{}{Um homem que guarda uma ponte.}
{4870}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 38
{4900}{}{Uma banda de incursores.}
{4901}{}{Alguns lobos.}
{4902}{}{Uma caravana evitando alguns incursores.}
{4903}{}{Uma caravana evitando alguns incursores.}
{4904}{}{Alguns caçadores de recompensas.}
{4905}{}{Alguns caçadores de recompensas.}
{4906}{}{Alguns caçadores de recompensas.}
{4907}{}{Alguns caçadores de recompensas.}
{4908}{}{Alguns caçadores de recompensas.}
{4909}{}{Alguns caçadores de recompensas.}
{4910}{}{Alguns caçadores de recompensas.}
{4911}{}{Alguns caçadores de recompensas.}
{4912}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4913}{}{Uma caravana evitando alguns incursores.}
{4914}{}{Uma caravana evitando alguns incursores.}
{4915}{}{Uma caravana.}
{4916}{}{Uma caravana.}
{4917}{}{Uma caravana.}
{4918}{}{Uma caravana.}
{4919}{}{Um homem que guarda uma ponte.}
{4920}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 39
{4950}{}{Descarga de resíduos tóxicos}
{4951}{}{Um cão sobrevivente solitário.}
{4952}{}{Um rebanho de brahmin.}
{4953}{}{Uma banda de incursores.}
{4954}{}{Alguns caçadores de recompensas.}
{4955}{}{Alguns caçadores de recompensas.}
{4956}{}{Alguns caçadores de recompensas.}
{4957}{}{Alguns caçadores de recompensas.}
{4958}{}{Alguns caçadores de recompensas.}
{4959}{}{Alguns caçadores de recompensas.}
{4960}{}{Alguns caçadores de recompensas.}
{4961}{}{Alguns caçadores de recompensas.}
{4962}{}{Uma banda de rufiões liderada por um irmão Morton.}
{4963}{}{Alguns lobos.}
{4964}{}{Uma caravana evitando alguns incursores.}
{4965}{}{Uma caravana evitando alguns incursores.}
{4966}{}{Uma caravana evitando alguns incursores.}
{4967}{}{Uma caravana evitando alguns incursores.}
{4968}{}{Uma caravana.}
{4969}{}{Uma caravana.}
{4970}{}{Uma caravana.}
{4971}{}{Uma caravana.}
{4972}{}{Os restos de uma baleia.}
{4973}{}{Uma cabeça de pedra gigante.}
{4974}{}{Um ônibus acidentado.}
{4975}{}{Um Portal de Guardiões.}
{4976}{}{Cavaleiros do Rei Arthur.}
{4977}{}{Um homem de madeira de lata}
{4978}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 40
{5000}{}{Uma banda de incursores levando alguns lobos.}
{5001}{}{Algumas plantas de esporos e alguns lobos.}
{5002}{}{Uma banda de incursores.}
{5003}{}{Um bando de lobos.}
{5004}{}{Alguns caçadores de recompensas.}
{5005}{}{Alguns caçadores de recompensas.}
{5006}{}{Alguns caçadores de recompensas.}
{5007}{}{Alguns caçadores de recompensas.}
{5008}{}{Alguns caçadores de recompensas.}
{5009}{}{Alguns caçadores de recompensas.}
{5010}{}{Alguns caçadores de recompensas.}
{5011}{}{Alguns caçadores de recompensas.}
{5012}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5013}{}{Um pacote de radscorpions.}
{5014}{}{Um grupo de lobos lutando contra incursores.}
{5015}{}{Um homem que guarda uma ponte.}
{5016}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 41
{5050}{}{Descarga de resíduos tóxicos}
{5051}{}{Um cão sobrevivente solitário.}
{5052}{}{Um rebanho de brahmin.}
{5053}{}{Uma banda de incursores levando alguns lobos.}
{5054}{}{Alguns caçadores de recompensas.}
{5055}{}{Alguns caçadores de recompensas.}
{5056}{}{Alguns caçadores de recompensas.}
{5057}{}{Alguns caçadores de recompensas.}
{5058}{}{Alguns caçadores de recompensas.}
{5059}{}{Alguns caçadores de recompensas.}
{5060}{}{Alguns caçadores de recompensas.}
{5061}{}{Alguns caçadores de recompensas.}
{5062}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5063}{}{Algumas plantas de esporos e alguns lobos.}
{5064}{}{Uma banda de incursores.}
{5065}{}{Um bando de lobos.}
{5066}{}{Um pacote de radscorpions.}
{5067}{}{Um grupo de lobos lutando contra incursores.}
{5068}{}{Os restos de uma baleia.}
{5069}{}{Uma cabeça de pedra gigante.}
{5070}{}{Um ônibus acidentado.}
{5071}{}{Um Portal de Guardiões.}
{5072}{}{Cavaleiros do Rei Arthur.}
{5073}{}{Um homem de madeira de lata}
{5074}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 42
{5100}{}{Descarga de resíduos tóxicos}
{5101}{}{Um cão sobrevivente solitário.}
{5102}{}{Um rebanho de brahmin.}
{5103}{}{Uma Patrulha de Enclave.}
{5104}{}{Alguns caçadores de recompensas.}
{5105}{}{Alguns caçadores de recompensas.}
{5106}{}{Alguns caçadores de recompensas.}
{5107}{}{Alguns caçadores de recompensas.}
{5108}{}{Alguns caçadores de recompensas.}
{5109}{}{Alguns caçadores de recompensas.}
{5110}{}{Alguns caçadores de recompensas.}
{5111}{}{Alguns caçadores de recompensas.}
{5112}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5113}{}{Os restos de uma baleia.}
{5114}{}{Uma cabeça de pedra gigante.}
{5115}{}{Um ônibus acidentado.}
{5116}{}{Um Portal de Guardiões.}
{5117}{}{Cavaleiros do Rei Arthur.}
{5118}{}{Um homem de madeira de lata}
{5119}{}{The Unwashed Aldeiars hunting a spammer.}
{5120}{}{O café dos sonhos quebrados.}

# Encounter Table 43
{5150}{}{Uma Patrulha de Enclave.}
{5151}{}{Alguns caçadores de recompensas.}
{5152}{}{Alguns caçadores de recompensas.}
{5153}{}{Alguns caçadores de recompensas.}
{5154}{}{Alguns caçadores de recompensas.}
{5155}{}{Alguns caçadores de recompensas.}
{5156}{}{Alguns caçadores de recompensas.}
{5157}{}{Alguns caçadores de recompensas.}
{5158}{}{Alguns caçadores de recompensas.}
{5159}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5160}{}{Um homem que guarda uma ponte.}
{5161}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 44
{5200}{}{Uma Patrulha de Enclave.}
{5201}{}{Alguns caçadores de recompensas.}
{5202}{}{Alguns caçadores de recompensas.}
{5203}{}{Alguns caçadores de recompensas.}
{5204}{}{Alguns caçadores de recompensas.}
{5208}{}{Alguns caçadores de recompensas.}
{5209}{}{Alguns caçadores de recompensas.}
{5210}{}{Alguns caçadores de recompensas.}
{5211}{}{Alguns caçadores de recompensas.}
{5212}{}{Uma banda de rufiões liderada por um irmão Morton.}

# Encounter Table 45
{5250}{}{Descarga de resíduos tóxicos}
{5251}{}{Um cão sobrevivente solitário.}
{5252}{}{Um rebanho de brahmin.}
{5253}{}{Alguns alienígenas e deathclaws}
{5254}{}{Alguns caçadores de recompensas.}
{5255}{}{Alguns caçadores de recompensas.}
{5256}{}{Alguns caçadores de recompensas.}
{5257}{}{Alguns caçadores de recompensas.}
{5258}{}{Alguns caçadores de recompensas.}
{5259}{}{Alguns caçadores de recompensas.}
{5260}{}{Alguns caçadores de recompensas.}
{5261}{}{Alguns caçadores de recompensas.}
{5262}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5263}{}{Um exército de flutuadores e centauros.}
{5264}{}{Alguns geckos de fogo.}
{5265}{}{Um grande pacote de alienígenas.}
{5266}{}{Alguns mortíferos.}
{5267}{}{Alguns geckos de fogo.}
{5268}{}{Alguns alienígenas.}
{5269}{}{Um grupo de centauros.}
{5270}{}{Um enxame de flutuadores.}
{5271}{}{Os restos de uma baleia.}
{5272}{}{Uma cabeça de pedra gigante.}
{5273}{}{Um ônibus acidentado.}
{5274}{}{Um Portal de Guardiões.}
{5275}{}{Cavaleiros do Rei Arthur.}
{5276}{}{Um homem de madeira de lata}
{5277}{}{The Unwashed Aldeiars hunting a spammer.}
{5278}{}{O café dos sonhos quebrados.}

# Encounter Table 46
{5300}{}{Alguns alienígenas e deathclaws}
{5301}{}{Um exército de flutuadores e centauros.}
{5302}{}{Alguns geckos de fogo.}
{5303}{}{Um grande pacote de alienígenas.}
{5304}{}{Alguns caçadores de recompensas.}
{5305}{}{Alguns caçadores de recompensas.}
{5306}{}{Alguns caçadores de recompensas.}
{5307}{}{Alguns caçadores de recompensas.}
{5308}{}{Alguns caçadores de recompensas.}
{5309}{}{Alguns caçadores de recompensas.}
{5310}{}{Alguns caçadores de recompensas.}
{5311}{}{Alguns caçadores de recompensas.}
{5312}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5313}{}{Alguns mortíferos.}
{5314}{}{Alguns geckos de fogo.}
{5315}{}{Alguns alienígenas.}
{5316}{}{Um grupo de centauros.}
{5317}{}{Um enxame de flutuadores.}
{5318}{}{Um homem que guarda uma ponte.}
{5319}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 47
{5350}{}{Alguns alienígenas e deathclaws}
{5351}{}{Um exército de flutuadores e centauros.}
{5352}{}{Alguns geckos de fogo.}
{5353}{}{Um grande pacote de alienígenas.}
{5354}{}{Alguns caçadores de recompensas.}
{5355}{}{Alguns caçadores de recompensas.}
{5356}{}{Alguns caçadores de recompensas.}
{5357}{}{Alguns caçadores de recompensas.}
{5358}{}{Alguns caçadores de recompensas.}
{5359}{}{Alguns caçadores de recompensas.}
{5360}{}{Alguns caçadores de recompensas.}
{5361}{}{Alguns caçadores de recompensas.}
{5362}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5363}{}{Alguns mortíferos.}
{5364}{}{Alguns geckos de fogo.}
{5365}{}{Alguns alienígenas.}
{5366}{}{Um grupo de centauros.}
{5367}{}{Um enxame de flutuadores.}

# Encounter Table 48
{5400}{}{Descarga de resíduos tóxicos}
{5401}{}{Um cão sobrevivente solitário.}
{5402}{}{Um rebanho de brahmin.}
{5403}{}{Um pacote de geckos de fogo.}
{5404}{}{Alguns caçadores de recompensas.}
{5405}{}{Alguns caçadores de recompensas.}
{5406}{}{Alguns caçadores de recompensas.}
{5407}{}{Alguns caçadores de recompensas.}
{5408}{}{Alguns caçadores de recompensas.}
{5409}{}{Alguns caçadores de recompensas.}
{5410}{}{Alguns caçadores de recompensas.}
{5411}{}{Alguns caçadores de recompensas.}
{5412}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5413}{}{Um pacote de geckos de fogo.}
{5414}{}{Um grande pacote de geckos dourados.}
{5415}{}{Os restos de uma baleia.}
{5416}{}{Uma cabeça de pedra gigante.}
{5417}{}{Um ônibus acidentado.}
{5418}{}{Um Portal de Guardiões.}
{5419}{}{Cavaleiros do Rei Arthur.}
{5420}{}{Um homem de madeira de lata}
{5421}{}{The Unwashed Aldeiars hunting a spammer.}
{5422}{}{O café dos sonhos quebrados.}

# Encounter Table 49
{5450}{}{Um pacote de geckos de fogo.}
{5451}{}{Um pacote de geckos de fogo.}
{5452}{}{Um grande pacote de geckos dourados.}
{5453}{}{Alguns caçadores de recompensas.}
{5454}{}{Alguns caçadores de recompensas.}
{5455}{}{Alguns caçadores de recompensas.}
{5456}{}{Alguns caçadores de recompensas.}
{5457}{}{Alguns caçadores de recompensas.}
{5458}{}{Alguns caçadores de recompensas.}
{5459}{}{Alguns caçadores de recompensas.}
{5460}{}{Alguns caçadores de recompensas.}
{5461}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5462}{}{Um homem que guarda uma ponte.}
{5463}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 50
{5500}{}{Um pacote de geckos de fogo.}
{5501}{}{Um pacote de geckos de fogo.}
{5502}{}{Um grande pacote de geckos dourados.}
{5503}{}{Alguns caçadores de recompensas.}
{5504}{}{Alguns caçadores de recompensas.}
{5505}{}{Alguns caçadores de recompensas.}
{5506}{}{Alguns caçadores de recompensas.}
{5507}{}{Alguns caçadores de recompensas.}
{5508}{}{Alguns caçadores de recompensas.}
{5509}{}{Alguns caçadores de recompensas.}
{5510}{}{Alguns caçadores de recompensas.}
{5511}{}{Uma banda de rufiões liderada por um irmão Morton.}

# Encounter Table 51
{5550}{}{Descarga de resíduos tóxicos}
{5551}{}{Um cão sobrevivente solitário.}
{5552}{}{Um rebanho de brahmin.}
{5553}{}{Um pacote de mortes.}
{5554}{}{Alguns caçadores de recompensas.}
{5555}{}{Alguns caçadores de recompensas.}
{5556}{}{Alguns caçadores de recompensas.}
{5557}{}{Alguns caçadores de recompensas.}
{5558}{}{Alguns caçadores de recompensas.}
{5559}{}{Alguns caçadores de recompensas.}
{5560}{}{Alguns caçadores de recompensas.}
{5561}{}{Alguns caçadores de recompensas.}
{5562}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5563}{}{Um pacote de geckos de fogo.}
{5564}{}{Uma caravana que afasta os ferimentos da morte.}
{5565}{}{Uma caravana que afasta os ferimentos da morte.}
{5566}{}{Uma caravana que afasta os gecos de fogo.}
{5567}{}{Uma caravana que afasta os gecos de fogo.}
{5568}{}{Uma caravana.}
{5569}{}{Uma caravana.}
{5570}{}{Uma caravana.}
{5571}{}{Uma caravana.}
{5572}{}{Os restos de uma baleia.}
{5573}{}{Uma cabeça de pedra gigante.}
{5574}{}{Um ônibus acidentado.}
{5575}{}{Um Portal de Guardiões.}
{5576}{}{Cavaleiros do Rei Arthur.}
{5577}{}{Um homem de madeira de lata}
{5578}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 52
{5600}{}{Um pacote de mortes.}
{5601}{}{Um pacote de geckos de fogo.}
{5602}{}{Uma caravana que afasta os ferimentos da morte.}
{5603}{}{Uma caravana que afasta os ferimentos da morte.}
{5604}{}{Alguns caçadores de recompensas.}
{5605}{}{Alguns caçadores de recompensas.}
{5606}{}{Alguns caçadores de recompensas.}
{5607}{}{Alguns caçadores de recompensas.}
{5608}{}{Alguns caçadores de recompensas.}
{5609}{}{Alguns caçadores de recompensas.}
{5610}{}{Alguns caçadores de recompensas.}
{5611}{}{Alguns caçadores de recompensas.}
{5612}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5613}{}{Uma caravana que afasta os gecos de fogo.}
{5614}{}{Uma caravana que afasta os gecos de fogo.}
{5615}{}{Uma caravana.}
{5616}{}{Uma caravana.}
{5617}{}{Uma caravana.}
{5618}{}{Uma caravana.}
{5619}{}{Um homem que guarda uma ponte.}
{5620}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 53
{5650}{}{Descarga de resíduos tóxicos}
{5651}{}{Um cão sobrevivente solitário.}
{5652}{}{Um rebanho de brahmin.}
{5653}{}{Alguns yakuza.}
{5654}{}{Alguns caçadores de recompensas.}
{5655}{}{Alguns caçadores de recompensas.}
{5656}{}{Alguns caçadores de recompensas.}
{5657}{}{Alguns caçadores de recompensas.}
{5658}{}{Alguns caçadores de recompensas.}
{5659}{}{Alguns caçadores de recompensas.}
{5660}{}{Alguns caçadores de recompensas.}
{5661}{}{Alguns caçadores de recompensas.}
{5662}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5663}{}{Uma gangue.}
{5664}{}{Um bando de lobos.}
{5665}{}{Alguns mafiosos que lutam contra um pouco de Yakuza.}
{5666}{}{Alguns mafiosos que lutam contra uma gangue.}
{5667}{}{Alguns mafiosos.}
{5668}{}{Um viajante.}
{5669}{}{Os restos de uma baleia.}
{5670}{}{Uma cabeça de pedra gigante.}
{5671}{}{Um ônibus acidentado.}
{5672}{}{Um Portal de Guardiões.}
{5673}{}{Cavaleiros do Rei Arthur.}
{5674}{}{Um homem de madeira de lata}
{5675}{}{The Unwashed Aldeiars hunting a spammer.}
{5676}{}{O café dos sonhos quebrados.}

# Encounter Table 54
{5700}{}{Alguns yakuza.}
{5701}{}{Uma gangue.}
{5702}{}{Um bando de lobos.}
{5703}{}{Alguns mafiosos que lutam contra um pouco de Yakuza.}
{5704}{}{Alguns caçadores de recompensas.}
{5705}{}{Alguns caçadores de recompensas.}
{5706}{}{Alguns caçadores de recompensas.}
{5707}{}{Alguns caçadores de recompensas.}
{3308}{}{Alguns caçadores de recompensas.}
{3309}{}{Alguns caçadores de recompensas.}
{3310}{}{Alguns caçadores de recompensas.}
{3311}{}{Alguns caçadores de recompensas.}
{3312}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5713}{}{Alguns mafiosos que lutam contra uma gangue.}
{5714}{}{Alguns mafiosos.}
{5715}{}{Um viajante.}
{5716}{}{Um homem que guarda uma ponte.}
{5717}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 55
{5750}{}{Alguns yakuza.}
{5751}{}{Uma gangue.}
{5752}{}{Um bando de lobos.}
{5753}{}{Alguns mafiosos que lutam contra um pouco de Yakuza.}
{5754}{}{Alguns caçadores de recompensas.}
{5755}{}{Alguns caçadores de recompensas.}
{5756}{}{Alguns caçadores de recompensas.}
{5757}{}{Alguns caçadores de recompensas.}
{5758}{}{Alguns caçadores de recompensas.}
{5759}{}{Alguns caçadores de recompensas.}
{5760}{}{Alguns caçadores de recompensas.}
{5761}{}{Alguns caçadores de recompensas.}
{5762}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5763}{}{Alguns mafiosos que lutam contra uma gangue.}
{5764}{}{Alguns mafiosos.}
{5765}{}{Um viajante.}

# Encounter Table 56
{5800}{}{Descarga de resíduos tóxicos}
{5801}{}{Um cão sobrevivente solitário.}
{5802}{}{Um rebanho de brahmin.}
{5803}{}{Um bandido e alguns lobos.}
{5804}{}{Alguns caçadores de recompensas.}
{5805}{}{Alguns caçadores de recompensas.}
{5806}{}{Alguns caçadores de recompensas.}
{5807}{}{Alguns caçadores de recompensas.}
{5808}{}{Alguns caçadores de recompensas.}
{5809}{}{Alguns caçadores de recompensas.}
{5810}{}{Alguns caçadores de recompensas.}
{5811}{}{Alguns caçadores de recompensas.}
{5812}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5813}{}{Uma banda de pífagos.}
{5814}{}{Um bando de lobos.}
{5815}{}{Um pacote de radscorpions.}
{5816}{}{Uma floresta de plantas de esporos.}
{5817}{}{Uma patrulha da Unidade lutando contra alguns bandidos.}
{5818}{}{Uma patrulha da Unidade lutando contra lobos.}
{5819}{}{Uma patrulha da Unidade.}
{5820}{}{Os restos de uma baleia.}
{5821}{}{Uma cabeça de pedra gigante.}
{5822}{}{Um ônibus acidentado.}
{5823}{}{Um Portal de Guardiões.}
{5824}{}{Cavaleiros do Rei Arthur.}
{5825}{}{Um homem de madeira de lata}
{5826}{}{The Unwashed Aldeiars hunting a spammer.}

# Encounter Table 57
{5850}{}{Um bandido e alguns lobos.}
{5851}{}{Uma banda de pífagos.}
{5852}{}{Um bando de lobos.}
{5853}{}{Um pacote de radscorpions.}
{5854}{}{Alguns caçadores de recompensas.}
{5855}{}{Alguns caçadores de recompensas.}
{5856}{}{Alguns caçadores de recompensas.}
{5857}{}{Alguns caçadores de recompensas.}
{5858}{}{Alguns caçadores de recompensas.}
{5859}{}{Alguns caçadores de recompensas.}
{5860}{}{Alguns caçadores de recompensas.}
{5861}{}{Alguns caçadores de recompensas.}
{5862}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5863}{}{Uma floresta de plantas de esporos.}
{5864}{}{Uma patrulha da Unidade lutando contra alguns bandidos.}
{5865}{}{Uma patrulha da Unidade lutando contra lobos.}
{5866}{}{Uma patrulha da Unidade.}
{5867}{}{Um homem que guarda uma ponte.}
{5868}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 58
{5900}{}{Uma banda de mercenários.}
{5901}{}{Uma gangue de imprensa.}
{5902}{}{Um rebanho de mortíferas.}
{5903}{}{Um lote de geckos de fogo.}
{5904}{}{Alguns caçadores de recompensas.}
{5905}{}{Alguns caçadores de recompensas.}
{5906}{}{Alguns caçadores de recompensas.}
{5907}{}{Alguns caçadores de recompensas.}
{5908}{}{Alguns caçadores de recompensas.}
{5909}{}{Alguns caçadores de recompensas.}
{5910}{}{Alguns caçadores de recompensas.}
{5911}{}{Alguns caçadores de recompensas.}
{5912}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5913}{}{Uma série de alienígenas.}
{5914}{}{Hubologists lutando contra mercenários.}
{5915}{}{Hubologists se afasta de uma gangue de imprensa.}
{5916}{}{Hubologists.}

# Encounter Table 59
{5950}{}{Uma banda de mercenários.}
{5951}{}{Uma gangue de imprensa.}
{5952}{}{Um rebanho de mortíferas.}
{5953}{}{Um lote de geckos de fogo.}
{5954}{}{Alguns caçadores de recompensas.}
{5955}{}{Alguns caçadores de recompensas.}
{5956}{}{Alguns caçadores de recompensas.}
{5957}{}{Alguns caçadores de recompensas.}
{5958}{}{Alguns caçadores de recompensas.}
{5959}{}{Alguns caçadores de recompensas.}
{5960}{}{Alguns caçadores de recompensas.}
{5961}{}{Alguns caçadores de recompensas.}
{5962}{}{Uma banda de rufiões liderada por um irmão Morton.}
{5963}{}{Uma série de alienígenas.}
{5964}{}{Hubologists lutando contra mercenários.}
{5965}{}{Hubologists se afasta de uma gangue de imprensa.}
{5966}{}{Hubologists.}
{5967}{}{Um homem que guarda uma ponte.}
{5968}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 60
{6000}{}{Uma banda de mercenários.}
{6001}{}{Uma gangue de imprensa.}
{6002}{}{Um rebanho de mortíferas.}
{6003}{}{Um lote de geckos de fogo.}
{6004}{}{Alguns caçadores de recompensas.}
{6005}{}{Alguns caçadores de recompensas.}
{6006}{}{Alguns caçadores de recompensas.}
{6007}{}{Alguns caçadores de recompensas.}
{6008}{}{Alguns caçadores de recompensas.}
{6009}{}{Alguns caçadores de recompensas.}
{6010}{}{Alguns caçadores de recompensas.}
{6011}{}{Alguns caçadores de recompensas.}
{6012}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6013}{}{Uma série de alienígenas.}
{6014}{}{Hubologists lutando contra mercenários.}
{6015}{}{Hubologists se afasta de uma gangue de imprensa.}
{6016}{}{Hubologists.}

# Encounter Table 61
{6050}{}{Descarga de resíduos tóxicos}
{6051}{}{Um cão sobrevivente solitário.}
{6052}{}{Um rebanho de brahmin.}
{6053}{}{Uma banda de mercenários.}
{6054}{}{Alguns caçadores de recompensas.}
{6055}{}{Alguns caçadores de recompensas.}
{6056}{}{Alguns caçadores de recompensas.}
{6057}{}{Alguns caçadores de recompensas.}
{6058}{}{Alguns caçadores de recompensas.}
{6059}{}{Alguns caçadores de recompensas.}
{6050}{}{Alguns caçadores de recompensas.}
{6061}{}{Alguns caçadores de recompensas.}
{6062}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6063}{}{Uma gangue de imprensa.}
{6064}{}{Um rebanho de mortíferas.}
{6065}{}{Um lote de geckos de fogo.}
{6066}{}{Uma série de alienígenas.}
{6067}{}{Hubologists lutando contra mercenários.}
{6068}{}{Hubologists se afasta de uma gangue de imprensa.}
{6069}{}{Hubologists.}
{6070}{}{Os restos de uma baleia.}
{6071}{}{Uma cabeça de pedra gigante.}
{6072}{}{Um ônibus acidentado.}
{6073}{}{Um Portal de Guardiões.}
{6074}{}{Cavaleiros do Rei Arthur.}
{6075}{}{Um homem de madeira de lata}
{6076}{}{The Unwashed Aldeiars hunting a spammer.}
{6077}{}{O café dos sonhos quebrados.}

# Encounter Table 62
{6100}{}{Descarga de resíduos tóxicos}
{6101}{}{Um cão sobrevivente solitário.}
{6102}{}{Um rebanho de brahmin.}
{6103}{}{Uma banda de mercenários.}
{6104}{}{Alguns caçadores de recompensas.}
{6105}{}{Alguns caçadores de recompensas.}
{6106}{}{Alguns caçadores de recompensas.}
{6107}{}{Alguns caçadores de recompensas.}
{6108}{}{Alguns caçadores de recompensas.}
{6109}{}{Alguns caçadores de recompensas.}
{6110}{}{Alguns caçadores de recompensas.}
{6111}{}{Alguns caçadores de recompensas.}
{6112}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6113}{}{Um pacote de mortes.}
{6114}{}{Um pacote de geckos de fogo.}
{6115}{}{Uma série de alienígenas.}
{6116}{}{Uma caravana afastando mercenários.}
{6117}{}{Uma caravana afastando mercenários.}
{6118}{}{Uma caravana que afasta os gecos de fogo.}
{6119}{}{Uma caravana que afasta os alienígenas.}
{6120}{}{Uma caravana.}
{6121}{}{Uma caravana.}
{6122}{}{Os restos de uma baleia.}
{6123}{}{Uma cabeça de pedra gigante.}
{6124}{}{Um ônibus acidentado.}
{6125}{}{Um Portal de Guardiões.}
{6126}{}{Cavaleiros do Rei Arthur.}
{6127}{}{Um homem de madeira de lata}
{6128}{}{The Unwashed Aldeiars hunting a spammer.}
{6129}{}{O café dos sonhos quebrados.}

# Encounter Table 63
{6150}{}{Uma banda de mercenários.}
{6151}{}{Um pacote de mortes.}
{6152}{}{Um pacote de geckos de fogo.}
{6153}{}{Uma série de alienígenas.}
{6154}{}{Alguns caçadores de recompensas.}
{6155}{}{Alguns caçadores de recompensas.}
{6156}{}{Alguns caçadores de recompensas.}
{6157}{}{Alguns caçadores de recompensas.}
{6158}{}{Alguns caçadores de recompensas.}
{6159}{}{Alguns caçadores de recompensas.}
{6160}{}{Alguns caçadores de recompensas.}
{6161}{}{Alguns caçadores de recompensas.}
{6162}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6163}{}{Uma caravana afastando mercenários.}
{6164}{}{Uma caravana afastando mercenários.}
{6165}{}{Uma caravana que afasta os gecos de fogo.}
{6166}{}{Uma caravana que afasta os alienígenas.}
{6167}{}{Uma caravana.}
{6168}{}{Uma caravana.}

# Encounter Table 64
{6200}{}{Descarga de resíduos tóxicos}
{6201}{}{Um cão sobrevivente solitário.}
{6202}{}{Um rebanho de brahmin.}
{6203}{}{Uma patrulha do Enclave.}
{6204}{}{Alguns caçadores de recompensas.}
{6205}{}{Alguns caçadores de recompensas.}
{6206}{}{Alguns caçadores de recompensas.}
{6207}{}{Alguns caçadores de recompensas.}
{6208}{}{Alguns caçadores de recompensas.}
{6209}{}{Alguns caçadores de recompensas.}
{6210}{}{Alguns caçadores de recompensas.}
{6211}{}{Alguns caçadores de recompensas.}
{6212}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6213}{}{Restos do exército do mestre.}
{6214}{}{Um pacote de Deathclaws.}
{6215}{}{Um enxame de mantis.}
{6216}{}{Os restos de uma baleia.}
{6217}{}{Uma cabeça de pedra gigante.}
{6218}{}{Um ônibus acidentado.}
{6219}{}{Um Portal de Guardiões.}
{6220}{}{Cavaleiros do Rei Arthur.}
{6221}{}{Um homem de madeira de lata}
{6222}{}{The Unwashed Aldeiars hunting a spammer.}
{6223}{}{O café dos sonhos quebrados.}

# Encounter Table 65
{6250}{}{Uma patrulha do Enclave.}
{6251}{}{Restos do exército do mestre.}
{6252}{}{Um pacote de Deathclaws.}
{6253}{}{Um enxame de mantis.}
{6254}{}{Alguns caçadores de recompensas.}
{6255}{}{Alguns caçadores de recompensas.}
{6256}{}{Alguns caçadores de recompensas.}
{6257}{}{Alguns caçadores de recompensas.}
{6258}{}{Alguns caçadores de recompensas.}
{6259}{}{Alguns caçadores de recompensas.}
{6260}{}{Alguns caçadores de recompensas.}
{6261}{}{Alguns caçadores de recompensas.}
{6262}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6263}{}{Um homem que guarda uma ponte.}
{6264}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 66
{6300}{}{Descarga de resíduos tóxicos}
{6301}{}{Um cão sobrevivente solitário.}
{6302}{}{Um rebanho de brahmin.}
{6303}{}{Uma caravana que afastava os restos do exército do Mestre.}
{6304}{}{Alguns caçadores de recompensas.}
{6305}{}{Alguns caçadores de recompensas.}
{6306}{}{Alguns caçadores de recompensas.}
{6307}{}{Alguns caçadores de recompensas.}
{6308}{}{Alguns caçadores de recompensas.}
{6309}{}{Alguns caçadores de recompensas.}
{6310}{}{Alguns caçadores de recompensas.}
{6311}{}{Alguns caçadores de recompensas.}
{6312}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6313}{}{Uma caravana que afastava os restos do exército do Mestre.}
{6314}{}{Uma caravana afastando alguns feridos da morte.}
{6315}{}{Uma caravana.}
{6316}{}{Uma caravana.}
{6317}{}{Uma caravana.}
{6318}{}{Os restos de uma baleia.}
{6319}{}{Uma cabeça de pedra gigante.}
{6320}{}{Um ônibus acidentado.}
{6321}{}{Um Portal de Guardiões.}
{6322}{}{Cavaleiros do Rei Arthur.}
{6323}{}{Um homem de madeira de lata}
{6324}{}{The Unwashed Aldeiars hunting a spammer.}
{6325}{}{O café dos sonhos quebrados.}

# Encounter Table 67
{6350}{}{Uma caravana que afastava os restos do exército do Mestre.}
{6351}{}{Uma caravana que afastava os restos do exército do Mestre.}
{6352}{}{Uma caravana afastando alguns feridos da morte.}
{6353}{}{Uma caravana.}
{6354}{}{Alguns caçadores de recompensas.}
{6355}{}{Alguns caçadores de recompensas.}
{6356}{}{Alguns caçadores de recompensas.}
{6357}{}{Alguns caçadores de recompensas.}
{6358}{}{Alguns caçadores de recompensas.}
{6359}{}{Alguns caçadores de recompensas.}
{6360}{}{Alguns caçadores de recompensas.}
{6361}{}{Alguns caçadores de recompensas.}
{6362}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6363}{}{Uma caravana.}
{6364}{}{Uma caravana.}
{6365}{}{Um homem que guarda uma ponte.}
{6366}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 68
{6400}{}{Um bando de lobos.}
{6401}{}{Um enxame de mantis.}
{6402}{}{Uma família de radscorpions.}
{6403}{}{Alguns caçadores de recompensas.}
{6404}{}{Alguns caçadores de recompensas.}
{6405}{}{Alguns caçadores de recompensas.}
{6406}{}{Alguns caçadores de recompensas.}
{6407}{}{Alguns caçadores de recompensas.}
{6408}{}{Alguns caçadores de recompensas.}
{6409}{}{Alguns caçadores de recompensas.}
{6410}{}{Alguns caçadores de recompensas.}
{6411}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6412}{}{Um homem que guarda uma ponte.}
{6413}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 69
{6450}{}{Descarga de resíduos tóxicos}
{6451}{}{Um cão sobrevivente solitário.}
{6452}{}{Um rebanho de brahmin.}
{6453}{}{Um bando de lobos.}
{6454}{}{Alguns caçadores de recompensas.}
{6455}{}{Alguns caçadores de recompensas.}
{6456}{}{Alguns caçadores de recompensas.}
{6457}{}{Alguns caçadores de recompensas.}
{6458}{}{Alguns caçadores de recompensas.}
{6459}{}{Alguns caçadores de recompensas.}
{6460}{}{Alguns caçadores de recompensas.}
{6461}{}{Alguns caçadores de recompensas.}
{6462}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6463}{}{Um enxame de mantis.}
{6464}{}{Uma família de radscorpions.}
{6465}{}{Os restos de uma baleia.}
{6466}{}{Uma cabeça de pedra gigante.}
{6467}{}{Um ônibus acidentado.}
{6468}{}{Um Portal de Guardiões.}
{6469}{}{Cavaleiros do Rei Arthur.}
{6470}{}{Um homem de madeira de lata}
{6471}{}{The Unwashed Aldeiars hunting a spammer.}
{6472}{}{O café dos sonhos quebrados.}

# Encounter Table 70
{6500}{}{Descarga de resíduos tóxicos}
{6501}{}{Um cão sobrevivente solitário.}
{6502}{}{Um rebanho de brahmin.}
{6503}{}{Uma banda de artilheiros.}
{6504}{}{Alguns caçadores de recompensas.}
{6505}{}{Alguns caçadores de recompensas.}
{6506}{}{Alguns caçadores de recompensas.}
{6507}{}{Alguns caçadores de recompensas.}
{6508}{}{Alguns caçadores de recompensas.}
{6509}{}{Alguns caçadores de recompensas.}
{6510}{}{Alguns caçadores de recompensas.}
{6511}{}{Alguns caçadores de recompensas.}
{6512}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6513}{}{Um bando de lobos.}
{6514}{}{Um pacote de radscorpions.}
{6515}{}{Uma caravana que afasta os mocassins.}
{6516}{}{Uma caravana que afasta os mocassins.}
{6517}{}{Uma caravana que afasta os lobos.}
{6518}{}{Uma caravana que protege radscorpions.}
{6519}{}{Uma caravana.}
{6520}{}{Uma caravana.}
{6521}{}{Uma caravana.}
{6522}{}{Uma caravana.}
{6523}{}{Um viajante.}
{6524}{}{Os restos de uma baleia.}
{6525}{}{Uma cabeça de pedra gigante.}
{6526}{}{Um ônibus acidentado.}
{6527}{}{Um Portal de Guardiões.}
{6528}{}{Cavaleiros do Rei Arthur.}
{6529}{}{Um homem de madeira de lata}
{6530}{}{The Unwashed Aldeiars hunting a spammer.}
{6531}{}{O café dos sonhos quebrados.}

# Encounter Table 71
{6550}{}{Uma banda de artilheiros.}
{6551}{}{Um bando de lobos.}
{6552}{}{Um pacote de radscorpions.}
{6553}{}{Uma caravana que afasta os mocassins.}
{6554}{}{Alguns caçadores de recompensas.}
{6555}{}{Alguns caçadores de recompensas.}
{6556}{}{Alguns caçadores de recompensas.}
{6557}{}{Alguns caçadores de recompensas.}
{6558}{}{Alguns caçadores de recompensas.}
{6559}{}{Alguns caçadores de recompensas.}
{6560}{}{Alguns caçadores de recompensas.}
{6561}{}{Alguns caçadores de recompensas.}
{6562}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6563}{}{Uma caravana que afasta os mocassins.}
{6564}{}{Uma caravana que afasta os lobos.}
{6565}{}{Uma caravana que protege radscorpions.}
{6566}{}{Uma caravana.}
{6567}{}{Uma caravana.}
{6568}{}{Uma caravana.}
{6569}{}{Uma caravana.}
{6570}{}{Um viajante.}
{6571}{}{Um homem que guarda uma ponte.}
{6572}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 72
{6600}{}{Um deteramento dos exércitos do mestre.}
{6601}{}{Uma banda de artilheiros.}
{6602}{}{Alguns Rangers defendem um esquadrão dos exércitos do Mestre.}
{6603}{}{Alguns Rangers lutando contra alguns mocassim.}
{6604}{}{Alguns caçadores de recompensas.}
{6605}{}{Alguns caçadores de recompensas.}
{6606}{}{Alguns caçadores de recompensas.}
{6607}{}{Alguns caçadores de recompensas.}
{6608}{}{Alguns caçadores de recompensas.}
{6609}{}{Alguns caçadores de recompensas.}
{6610}{}{Alguns caçadores de recompensas.}
{6611}{}{Alguns caçadores de recompensas.}
{6612}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6613}{}{Alguns agricultores defendem partes dos exércitos do mestre.}
{6614}{}{Alguns agricultores defendem os saqueadores.}
{6615}{}{Um destacamento de NCR Rangers.}
{6616}{}{Alguns agricultores.}
{6617}{}{Um homem que guarda uma ponte.}
{6618}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 73
{6650}{}{Descarga de resíduos tóxicos}
{6651}{}{Um cão sobrevivente solitário.}
{6652}{}{Um rebanho de brahmin.}
{6653}{}{Um destacamento dos exércitos do mestre.}
{6654}{}{Alguns caçadores de recompensas.}
{6655}{}{Alguns caçadores de recompensas.}
{6656}{}{Alguns caçadores de recompensas.}
{6657}{}{Alguns caçadores de recompensas.}
{6658}{}{Alguns caçadores de recompensas.}
{6659}{}{Alguns caçadores de recompensas.}
{6660}{}{Alguns caçadores de recompensas.}
{6661}{}{Alguns caçadores de recompensas.}
{6662}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6663}{}{Uma banda de artilheiros.}
{6664}{}{Alguns Rangers defendem um esquadrão dos exércitos do Mestre.}
{6665}{}{Alguns Rangers lutando contra alguns mocassim.}
{6666}{}{Alguns agricultores defendem partes dos exércitos do mestre.}
{6667}{}{Alguns agricultores defendem os saqueadores.}
{6668}{}{Um destacamento de NCR Rangers.}
{6669}{}{Alguns agricultores.}
{6670}{}{Os restos de uma baleia.}
{6671}{}{Uma cabeça de pedra gigante.}
{6672}{}{Um ônibus acidentado.}
{6673}{}{Um Portal de Guardiões.}
{6674}{}{Cavaleiros do Rei Arthur.}
{6675}{}{Um homem de madeira de lata}
{6676}{}{The Unwashed Aldeiars hunting a spammer.}
{6677}{}{O café dos sonhos quebrados.}

# Encounter Table 74
{6700}{}{Os restos do exército do mestre combatendo molerados mutantes.}
{6701}{}{Restos dos exércitos do mestre.}
{6702}{}{Um enxame de mantis.}
{6703}{}{Um pacote de molerados mutados.}
{6704}{}{Alguns caçadores de recompensas.}
{6705}{}{Alguns caçadores de recompensas.}
{6706}{}{Alguns caçadores de recompensas.}
{6707}{}{Alguns caçadores de recompensas.}
{6708}{}{Alguns caçadores de recompensas.}
{6709}{}{Alguns caçadores de recompensas.}
{6710}{}{Alguns caçadores de recompensas.}
{6711}{}{Alguns caçadores de recompensas.}
{6712}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6713}{}{Um pacote de radscorpions.}
{6714}{}{Um homem que guarda uma ponte.}
{6715}{}{Cavaleiros do Rei Arthur lutando contra um rato.}

# Encounter Table 75
{6750}{}{Descarga de resíduos tóxicos}
{6751}{}{Um cão sobrevivente solitário.}
{6752}{}{Um rebanho de brahmin.}
{6753}{}{Os restos do exército do mestre combatendo molerados mutantes.}
{6754}{}{Alguns caçadores de recompensas.}
{6755}{}{Alguns caçadores de recompensas.}
{6756}{}{Alguns caçadores de recompensas.}
{6757}{}{Alguns caçadores de recompensas.}
{6758}{}{Alguns caçadores de recompensas.}
{6759}{}{Alguns caçadores de recompensas.}
{6760}{}{Alguns caçadores de recompensas.}
{6761}{}{Alguns caçadores de recompensas.}
{6762}{}{Uma banda de rufiões liderada por um irmão Morton.}
{6763}{}{Restos dos exércitos do mestre.}
{6764}{}{Um enxame de mantis.}
{6765}{}{Um pacote de molerados mutados.}
{6766}{}{Um pacote de radscorpions.}
{6767}{}{Os restos de uma baleia.}
{6768}{}{Uma cabeça de pedra gigante.}
{6769}{}{Um ônibus acidentado.}
{6770}{}{Um Portal de Guardiões.}
{6771}{}{Cavaleiros do Rei Arthur.}
{6772}{}{Um homem de madeira de lata}
{6773}{}{The Unwashed Aldeiars hunting a spammer.}
{6774}{}{O café dos sonhos quebrados.}
